<s>
Service_VV0 Oriented_JJ Architecture_NN1 (_( SOA_NP1 )_) :_: a_AT1 study_NN1 of_IO adaption_NN1 intention_NN1 factors_NN2 for_IF applying_VVG new_JJ technology_NN1 1_MC1 INTRODUCTION_NN1 Organizations_NN2 are_VBR increasingly_RR dependent_JJ on_II their_APPGE IT_NN1 infrastructure_NN1 to_TO help_VVI them_PPHO2 to_TO achieve_VVI business_NN1 success_NN1 ._. 
</s>
<s>
A_AT1 company_NN1 that_CST manages_VVZ to_TO implement_VVI their_APPGE IT_NN1 infrastructure_NN1 to_TO support_VVI their_APPGE business_NN1 goals_NN2 will_VM increase_VVI their_APPGE potential_NN1 of_IO keeping_VVG them_PPHO2 competitive_JJ in_II the_AT market_NN1 (_( Piccoli_NP1 ,_, 12/2005_MF )_) et_RA21 al_RA22 ._. 
</s>
<s>
Service_VV0 Oriented_JJ Architecture_NN1 (_( SOA_NP1 )_) IT-governance_JJ concept_NN1 has_VHZ been_VBN around_RP for_IF more_DAR than_CSN a_AT1 decade_NNT1 (_( Schulte_NP1 W_ZZ1 ,_, 1996_MC )_) and_CC recent_JJ studies_NN2 of_IO SOA_NP1 suggest_VV0 that_CST there_EX are_VBR several_DA2 business_NN1 benefits_NN2 to_TO be_VBI gained_VVN through_II utilizing_VVG SOA_NP1 IT-governance_JJ approach_NN1 (_( Erl_NP1 ,_, 2009_MC )_) ,_, (_( Papazoglou_NP1 ;_; Traterso_NP1 ;_; Dustdar_NP1 ;_; &;_NULL Leymann_NP1 ,_, 2007_MC )_) et_RA21 al_RA22 ._. 
</s>
<s>
However_RR ,_, many_DA2 of_IO the_AT earlier_JJR studies_NN2 on_II SOA_NP1 have_VH0 mostly_RR dealt_VVN with_IW explaining_VVG and_CC describing_VVG what_DDQ SOA_NN1 is_VBZ ;_; how_RRQ it_PPH1 can_VM be_VBI used_VVN ,_, what_DDQ kind_NN1 of_IO technology_NN1 and_CC product_NN1 solutions_NN2 there_EX are_VBR to_TO help_VVI companies_NN2 utilizing_VVG it_PPH1 (_( Erickson_NP1 &;_NULL Siau_NP1 ,_, 2008_MC )_) ._. 
</s>
<s>
Contemporary_JJ studies_NN2 seem_VV0 to_TO demonstrate_VVI that_CST there_EX is_VBZ much_DA1 potential_NN1 in_II SOA_NP1 to_TO improve_VVI companies_NN2 IT-governance_NN1 and_CC find_VVI new_JJ ways_NN2 of_IO gaining_VVG competitive_JJ advantages_NN2 of_IO it_PPH1 ._. 
</s>
<s>
Despite_II these_DD2 promises_NN2 ,_, there_EX is_VBZ still_JJ lack_NN1 of_IO studies_NN2 that_CST would_VM show_VVI what_DDQ possible_JJ factors_NN2 trigger_VV0 companies_NN2 to_TO adopt_VVI new_JJ technology_NN1 innovations_NN2 like_II SOA_NP1 ._. 
</s>
<s>
As_II a_AT1 result_NN1 ,_, no_AT appropriate_JJ theory_NN1 seems_VVZ to_TO exist_VVI regarding_II the_AT adaption_NN1 intentions_NN2 of_IO SOA_NP1 IT-governance_JJ approach_NN1 ._. 
</s>
<s>
Question_NN1 is_VBZ what_DDQ kind_NN1 of_IO theory_NN1 or_CC adaption_NN1 model_NN1 would_VM properly_RR describe_VVI the_AT companies_NN2 '_GE willingness_NN1 to_TO utilize_VVI SOA_NN1 ?_? 
</s>
<s>
What_DDQ kinds_NN2 of_IO factors_NN2 contribute_VV0 or_CC lessen_VV0 the_AT potential_NN1 of_IO using_VVG SOA_NN1 in_II the_AT industry_NN1 ?_? 
</s>
<s>
This_DD1 paper_NN1 evaluates_VVZ the_AT possible_JJ factors_NN2 that_CST have_VH0 either_RR positive_JJ or_CC negative_JJ impact_NN1 on_II companies_NN2 '_GE adaption_NN1 intention_NN1 to_TO adapt_VVI to_II SOA_NP1 IT-governance_JJ approach_NN1 ._. 
</s>
<s>
In_II this_DD1 paper_NN1 ,_, the_AT author_NN1 will_VM present_VVI a_AT1 model_NN1 of_IO SOA_NP1 adaption_NN1 intention_NN1 ,_, which_DDQ is_VBZ based_VVN on_II innovation_NN1 adaption_NN1 model_NN1 by_II (_( Rogers_NP1 ,_, 1995_MC )_) and_CC (_( Tsai_FW ;_; Lee_NP1 ;_; &;_NULL Wu_NP1 ,_, 2010/47_MF )_) ,_, but_CCB modified_VVD by_II the_AT author_NN1 according_II21 to_II22 comprehensive_JJ literature_NN1 of_IO SOA_NN1 to_TO fit_VVI the_AT specific_JJ features_NN2 on_II SOA_NP1 ._. 
</s>
<s>
This_DD1 model_NN1 will_VM include_VVI the_AT following_JJ factors_NN2 :_: Relative_JJ advantages_NN2 of_IO SOA_NP1 ,_, Complexity_NN1 issues_NN2 of_IO SOA_NP1 ,_, Supply-chain_JJ integration_NN1 issues_NN2 ,_, Organizational_JJ readiness_NN1 concerns_NN2 ,_, Communication_NN1 channel_NN1 affects_VVZ ,_, all_DB or_CC which_DDQ will_VM be_VBI described_VVN in_II detail_NN1 in_II coming_VVG section_NN1 of_IO this_DD1 paper_NN1 ._. 
</s>
<s>
The_AT construction_NN1 of_IO this_DD1 paper_NN1 will_VM be_VBI to_TO first_MD introduce_VVI the_AT topic_NN1 and_CC research_NN1 objective_NN1 ._. 
</s>
<s>
Secondly_RR to_TO present_VVI the_AT current_JJ understanding_NN1 of_IO SOA_NP1 concept_NN1 ,_, principles_NN2 and_CC architecture_NN1 basics_NN2 through_II literature_NN1 reviews_NN2 ._. 
</s>
<s>
This_DD1 will_VM be_VBI carried_VVN out_RP so_CS21 that_CS22 the_AT reader_NN1 may_VM follow_VVI the_AT later_JJR discussion_NN1 and_CC understand_VVI the_AT argumentations_NN2 related_VVN to_II the_AT presented_JJ topics_NN2 ._. 
</s>
<s>
The_AT third_MD part_NN1 will_VM contain_VVI the_AT SOA_NN1 adaption_NN1 intention_NN1 model_NN1 and_CC the_AT empirical_JJ study_NN1 based_VVN on_II the_AT model_NN1 ._. 
</s>
<s>
The_AT firth_NN1 part_NN1 will_VM present_VVI the_AT study_NN1 results_NN2 based_VVN to_II the_AT analysis_NN1 and_CC reflections_NN2 with_IW the_AT SOA_NN1 adaption_NN1 intention_NN1 model_NN1 ._. 
</s>
<s>
This_DD1 part_NN1 is_VBZ used_VVN to_TO observe_VVI the_AT theories_NN2 in_II31 light_II32 of_II33 the_AT real_JJ industry_NN1 IT-governance_NN1 practices_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ also_RR used_VVN to_TO discuss_VVI how_RRQ SOA_NP1 is_VBZ used_VVN and_CC if_CS SOA_NP1 promises_NN2 hold_VV0 fast_RR in_II reality_NN1 ._. 
</s>
<s>
In_II the_AT final_JJ stage_NN1 the_AT conclusions_NN2 are_VBR drawn_VVN out_II21 of_II22 the_AT empirical_JJ study_NN1 in_II31 light_II32 of_II33 the_AT literature_NN1 review_NN1 and_CC the_AT research_NN1 questions_NN2 of_IO this_DD1 paper._NNU 2_MC SOA_NP1 DESCRIPTION_NN1 SECTION_NN1 Since_CS SOA_NP1 is_VBZ very_RG abstract_JJ paradigm_NN1 in_II the_AT first_MD place_NN1 ,_, it_PPH1 is_VBZ sufficient_JJ to_TO describe_VVI its_APPGE concepts_NN2 ,_, terms_NN2 ,_, techniques_NN2 of_IO this_DD1 technology_NN1 architecture_NN1 ._. 
</s>
<s>
This_DD1 will_VM help_VVI the_AT reader_NN1 to_TO better_RRR follow_VVI the_AT later_JJR discussion_NN1 of_IO SOA_NP1 's_GE possibilities_NN2 and_CC challenges_NN2 of_IO applying_VVG SOA._NP1 2.1_MC ._. 
</s>
<s>
SOA_NP1 definition_NN1 To_TO define_VVI SOA_NN1 is_VBZ a_RR21 bit_RR22 tricky_JJ ._. 
</s>
<s>
One_PN1 can_VM come_VVI across_II a_AT1 myriad_NN1 of_IO definitions_NN2 of_IO SOA_NN1 depending_II21 on_II22 a_AT1 person_NN1 you_PPY ask_VV0 about_II it_PPH1 or_CC how_RRQ one_PN1 a_AT1 book_NN1 or_CC article_NN1 author_NN1 defines_VVZ it_PPH1 ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 ,_, the_AT definitions_NN2 of_IO SOA_NP1 luckily_RR do_VD0 not_XX differ_VVI so_RG much_DA1 either_RR ._. 
</s>
<s>
Here_RL is_VBZ one_MC1 definition_NN1 that_CST reflects_VVZ how_RRQ this_DD1 study_NN1 is_VBZ characterizing_VVG SOA_NN1 ._. 
</s>
<s>
An_AT1 SOA_NN1 is_VBZ as_II an_AT1 interconnected_JJ set_NN1 of_IO services_NN2 which_DDQ in_II its_APPGE basic_JJ form_NN1 is_VBZ a_AT1 message-based_JJ interaction_NN1 between_II software_NN1 agents_NN2 ,_, each_DD1 accessible_JJ through_II standard_JJ interfaces_NN2 and_CC messaging_VVG protocols_NN2 ._. 
</s>
<s>
These_DD2 agents_NN2 can_VM be_VBI service_NN1 providers_NN2 or_CC service_NN1 requesters_NN2 (_( clients_NN2 )_) interacting_VVG with_IW service_NN1 discovery_NN1 agencies_NN2 ,_, and_CC the_AT services_NN2 in_II the_AT SOA_NN1 should_VM be_VBI technology_NN1 neutral_JJ ,_, loosely_RR coupled_VVN (_( not_XX tightly_RR integrated_VVN into_II the_AT requester_NN1 's_GE process_NN1 )_) ,_, and_CC support_VV0 location_NN1 transparency_NN1 ._. "_" 
</s>
<s>
(_( Papazoglou_NN1 M._NN1 ,_, 2003._MC )_) 2.2_MC ._. 
</s>
<s>
Overview_NN1 of_IO SOA_NP1 technology_NN1 According_II21 to_II22 literature_NN1 web_NN1 services_NN2 are_VBR most_RGT often_RR used_VVN when_CS implementing_VVG SOA_NP1 (_( ref_NN1 )_) ._. 
</s>
<s>
This_DD1 is_VBZ the_AT reason_NN1 this_DD1 study_NN1 focuses_VVZ only_JJ web_NN1 service_NN1 technology_NN1 implementation_NN1 approach_NN1 regarding_II SOA_NP1 architecture_NN1 ._. 
</s>
<s>
In_II principle_NN1 ,_, SOA_NP1 is_VBZ independent_JJ of_IO any_DD specific_JJ system_NN1 set-up_NN1 ,_, implementation_NN1 language_NN1 ,_, or_CC platform_NN1 technology_NN1 used_VVD ._. 
</s>
<s>
In_II SOA_NP1 architecture_NN1 ,_, standardized_JJ web_NN1 service_NN1 technologies_NN2 are_VBR used_VVN to_TO build_VVI the_AT enterprise_NN1 system_NN1 infrastructure_NN1 ._. 
</s>
<s>
Web_NN1 services_NN2 are_VBR enabling_VVG an_AT1 open_JJ communications_NN2 ,_, sharing_VVG of_IO information_NN1 and_CC data_NN exchange_NN1 between_II heterogeneous_JJ system_NN1 environments_NN2 ._. 
</s>
<s>
(_( Derrick_NP1 Huang_NP1 ,_, 2004_MC )_) 2.3_MC ._. 
</s>
<s>
SOA_NP1 fundamental_JJ principles_NN2 Service-oriented_JJ architecture_NN1 is_VBZ a_AT1 flexible_JJ design_NN1 architecture_NN1 based_VVN on_II a_AT1 set_NN1 of_IO principles_NN2 that_CST are_VBR used_VVN during_II the_AT systems_NN2 development_NN1 and_CC integration_NN1 of_IO the_AT organizations_NN2 IT-environment_NN1 ._. 
</s>
<s>
Thus_RR ,_, it_PPH1 is_VBZ important_JJ that_CST these_DD2 principles_NN2 are_VBR followed_VVN accordingly_RR to_TO enable_VVI a_AT1 SOA_NN1 compliant_JJ IT-environment_NN1 ._. 
</s>
<s>
The_AT introduced_JJ SOA_NN1 principles_NN2 that_CST will_VM be_VBI presented_VVN here_RL are_VBR in_II no_AT precedence_NN1 order_NN1 ._. 
</s>
<s>
This_DD1 study_NN1 focuses_VVZ on_II Web-service_JJ technology_NN1 implementation_NN1 approach_NN1 and_CC therefore_RR only_RR those_DD2 principles_NN2 that_CST apply_VV0 for_IF that_DD1 technology_NN1 are_VBR presented_VVN here_RL ._. 
</s>
<s>
These_DD2 principles_NN2 are_VBR received_VVN from_II (_( Erl_NP1 ,_, 2009_MC )_) ,_, http_NNU :_: and_CC (_( K._NP1 Laskey_NP1 &;_NULL K._NP1 Laskey_NP1 ,_, 2009_MC )_) et_RA21 al_RA22 ._. 
</s>
<s>
Firstly_RR ,_, the_AT services_NN2 need_VV0 to_TO be_VBI discoverable_JJ and_CC this_DD1 is_VBZ done_VDN by_II providing_VVG a_AT1 registry_NN1 that_CST enables_VVZ this_DD1 ._. 
</s>
<s>
This_DD1 registry_NN1 is_VBZ a_AT1 service_NN1 description_NN1 interface_NN1 which_DDQ makes_VVZ it_PPH1 possible_JJ to_TO discover_VVI automatically_RR the_AT available_JJ services_NN2 that_CST are_VBR provided_VVN on_II the_AT enterprise_NN1 network_NN1 ._. 
</s>
<s>
This_DD1 registry_NN1 needs_VVZ to_TO be_VBI dynamic_JJ in_II character_NN1 ,_, allowing_VVG flexible_JJ adding_NN1 ,_, removing_VVG ,_, modifying_VVG of_IO the_AT provided_VVN services_NN2 ._. 
</s>
<s>
Secondly_RR ,_, the_AT services_NN2 need_VV0 to_TO share_VVI a_AT1 formal_JJ contract_NN1 ._. 
</s>
<s>
For_IF service_NN1 to_TO interact_VVI ,_, they_PPHS2 need_VV0 to_TO share_VVI a_AT1 formal_JJ contract_NN1 that_CST describes_VVZ each_DD1 service_NN1 and_CC defines_VVZ the_AT terms_NN2 for_IF the_AT possible_JJ information_NN1 exchange_NN1 ._. 
</s>
<s>
Thirdly_RR ,_, services_NN2 need_VV0 to_TO have_VHI an_AT1 interaction_NN1 control_NN1 feature_NN1 ._. 
</s>
<s>
The_AT service_NN1 access_NN1 control_NN1 function_NN1 makes_VVZ sure_JJ that_CST only_JJ consumers_NN2 with_IW proper_JJ access_NN1 rights_NN2 are_VBR allowed_VVN to_TO utilize_VVI the_AT needed_VVN services_NN2 ._. 
</s>
<s>
Fourthly_RR ,_, the_AT service_NN1 infrastructure_NN1 needs_VVZ to_TO be_VBI applicable_JJ for_IF information_NN1 exchange_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ often_RR done_VDN so_CS21 that_CS22 the_AT overall_JJ service_NN1 system_NN1 environment_NN1 is_VBZ be_VBI transparent_JJ for_IF the_AT consumer_NN1 and_CC the_AT service_NN1 bus2_FO performs_VVZ the_AT needed_VVN functions_NN2 for_IF the_AT service_NN1 requestors_NN2 ._. 
</s>
<s>
Later_RRR on_RP in_II this_DD1 chapter_NN1 this_DD1 issues_VVZ will_VM be_VBI described_VVN in_II more_DAR detail._NNU 2.4_MC ._. 
</s>
<s>
SOA_NP1 terms_NN2 and_CC characteristics_NN2 In_II31 addition_II32 to_II33 the_AT above_JJ principles_NN2 ,_, it_PPH1 is_VBZ important_JJ to_TO understand_VVI some_DD main_JJ terms_NN2 and_CC attributes_NN2 or_CC characteristics_NN2 related_VVN to_II SOA_NP1 architecture_NN1 as_CSA they_PPHS2 are_VBR defined_VVN in_II the_AT literature_NN1 (_( Erl_NP1 ,_, 2009_MC )_) ,_, W3C_FO 2004_MC and_CC Papazoglou_NP1 ,_, M.P_NNA ,_, 2003_MC ._. 
</s>
<s>
In_II modularity_NN1 ,_, the_AT services_NN2 in_II the_AT SOA_NN1 architecture_NN1 are_VBR developed_VVN as_CSA independent_JJ modules_NN2 of_IO functionality_NN1 ,_, offering_VVG well-defined_JJ interfaces_NN2 to_II the_AT service_NN1 users_NN2 ._. 
</s>
<s>
The_AT services_NN2 represent_VV0 a_AT1 logical_JJ view_NN1 of_IO operations_NN2 (_( e.g._REX ,_, customer_NN1 verification_NN1 )_) as_CSA relatively_RR granular_JJ or_CC coarse-grained_JJ in_II scope_NN1 ._. 
</s>
<s>
Loose_JJ coupling_NN1 is_VBZ one_MC1 of_IO the_AT most_RGT common_JJ terms_NN2 used_VVN in_II SOA_NP1 context_NN1 ._. 
</s>
<s>
Here_RL the_AT underlying_JJ functionality_NN1 is_VBZ encapsulated_VVN so_CS21 that_CS22 the_AT implementation_NN1 is_VBZ logically_RR decoupled_VVN from_II the_AT invoking_JJ entity_NN1 ._. 
</s>
<s>
Services_NN2 may_VM encapsulate_VVI functionality_NN1 at_II various_JJ levels_NN2 from_II components_NN2 within_II an_AT1 application_NN1 to_II components_NN2 or_CC sub-systems_NN2 communicating_VVG across_II enterprises_NN2 as_CS31 long_CS32 as_CS33 they_PPHS2 represent_VV0 discrete_JJ meaningful_JJ business_NN1 functions_NN2 ._. 
</s>
<s>
Loosely_RR coupling_NN1 facilitates_VVZ the_AT composition_NN1 of_IO these_DD2 services_NN2 into_II complex_JJ services_NN2 and_CC applications_NN2 ._. 
</s>
<s>
Technology_NN1 neutrality_NN1 is_VBZ achieved_VVN by_II making_VVG the_AT services_NN2 universally_RR usable_JJ by_II any_DD requester_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ possible_JJ due_JJ that_CST the_AT communication_NN1 between_II services_NN2 is_VBZ message_NN1 based_VVN ,_, with_IW the_AT message_NN1 format_NN1 of_IO web_NN1 technology_NN1 standards_NN2 and_CC this_DD1 enables_VVZ platform-_JJ neutrality_NN1 ._. 
</s>
<s>
Location_NN1 transparency_NN1 is_VBZ accomplished_VVN by_II making_VVG the_AT services_NN2 self_NN1 describing_VVG ._. 
</s>
<s>
Services_NN2 use_VV0 formal_JJ documented_JJ interfaces_NN2 that_CST are_VBR well_RR known_VVN ,_, and_CC they_PPHS2 are_VBR easily_RR located_VVN and_CC accessed_VVN over_RP a_AT1 network_NN1 ._. 
</s>
<s>
According_II21 to_II22 Papazoglou_NP1 (_( 2003_MC )_) ,_, the_AT service_NN1 interface_NN1 is_VBZ "_" known_VVN where_RRQ to_TO be_VBI found_VVN not_XX only_RR by_II agents_NN2 who_PNQS designed_VVD the_AT services_NN2 but_CCB also_RR by_II agents_NN2 who_PNQS do_VD0 not_XX know_VVI about_II how_RRQ the_AT service_NN1 has_VHZ been_VBN designed_VVN and_CC yet_RR want_VV0 to_TO access_VVI and_CC use_VVI it_PPH1 "_" ._. 
</s>
<s>
2.5_MC ._. 
</s>
<s>
SOA_NP1 Architecture_NN1 a_AT1 big_JJ picture_NN1 The_AT architecture_NN1 infrastructure_NN1 construction_NN1 is_VBZ the_AT essential_JJ part_NN1 of_IO SOA_NP1 concept_NN1 ._. 
</s>
<s>
Here_RL the_AT author_NN1 describes_VVZ the_AT basic_JJ components_NN2 that_CST build_VV0 SOA_NN1 architecture_NN1 ._. 
</s>
<s>
"_" SOAs_NN2 may_VM be_VBI viewed_VVN as_CSA application_NN1 architectures_NN2 within_II which_DDQ all_DB functions_NN2 are_VBR defined_VVN as_CSA independent_JJ services_NN2 with_IW well-defined_JJ inviolable_JJ interfaces_NN2 ,_, which_DDQ can_VM be_VBI called_VVN in_II defined_JJ sequences_NN2 to_TO form_VVI business_NN1 processes_NN2 "_" (_( Channabasavaiah_NP1 K._NP1 ,_, 2004_MC )_) 2.5.1_MC ._. 
</s>
<s>
SOA_NP1 web-services_NN2 "_" The_AT fundamental_JJ architectural_JJ unit_NN1 for_IF an_AT1 SOA_NN1 is_VBZ a_AT1 "_" service_NN1 "_" ._. 
</s>
<s>
Service_NN1 ,_, per_II our_APPGE definition_NN1 of_IO SOA_NN1 is_VBZ units_NN2 of_IO business_NN1 capabilities_NN2 ,_, processes_NN2 or_CC functions_NN2 that_CST are_VBR delivered_VVN in_II a_AT1 repeatable_JJ way_NN1 to_II consumers_NN2 of_IO those_DD2 services_NN2 ._. "_" 
</s>
<s>
(_( Marks_NP1 &;_NULL Bell_NP1 ,_, 2006_MC )_) p.Exhibit_NNU 1.10_MC ._. 
</s>
<s>
The_AT most_RGT common_JJ implementation_NN1 of_IO SOA_NN1 is_VBZ by_II using_VVG Web_NN1 services_NN2 (_( C._NP1 Derrick_NP1 Huang_NP1 ,_, Qing_NP1 Hu_NP1 ,_, 2004_MC )_) et_RA21 al_RA22 ._. 
</s>
<s>
SOA_NP1 is_VBZ a_AT1 design_NN1 approach_NN1 where_CS the_AT enterprises_NN2 IT-infrastructure_NN1 is_VBZ standardized_VVN ,_, based_VVN on_II Web_NN1 Service_NN1 and_CC protocol_NN1 standards_NN2 ._. 
</s>
<s>
SOA_NP1 enables_VVZ the_AT technical_JJ capacity_NN1 to_TO make_VVI process_NN1 implementation_NN1 independent_NN1 between_II various_JJ system_NN1 modules_NN2 and_CC applications_NN2 ._. 
</s>
<s>
The_AT goal_NN1 of_IO using_VVG web-services_NN2 technology_NN1 is_VBZ to_TO enable_VVI using_VVG organization_NN1 's_GE IT_NN1 systems_NN2 as_CSA reusable_JJ services_NN2 that_CST can_VM communicate_VVI and_CC integrate_VVI more_RGR easily_RR and_CC quickly_RR ._. 
</s>
<s>
The_AT intention_NN1 with_IW SOA_NP1 is_VBZ to_TO eliminate_VVI the_AT integration_NN1 problems_NN2 that_CST exist_VV0 in_II many_DA2 enterprises_NN2 today_RT ._. 
</s>
<s>
SOA_NP1 offers_VVZ a_AT1 standardized_JJ communication_NN1 framework_NN1 for_IF systematic_JJ way_NN1 to_TO integrate_VVI current_JJ system_NN1 functions_NN2 and_CC to_TO develop_VVI new_JJ applications_NN2 ._. 
</s>
<s>
SOA_NN1 designed_VVN by_II using_VVG web-services_NN2 uses_VVZ an_AT1 asynchronous_JJ processing_NN1 technique_NN1 to_TO encapsulate_VVI the_AT underlying_JJ application_NN1 logic_NN1 into_II standardized_JJ interfaces_NN2 ._. 
</s>
<s>
These_DD2 interfaces_NN2 can_VM then_RT be_VBI called_VVN or_CC interacted_VVD asynchronously_RR ._. 
</s>
<s>
This_DD1 is_VBZ what_DDQ is_VBZ called_VVN loosely_RR coupling_NN1 -_- enabling_VVG flexible_JJ interaction_NN1 between_II components_NN2 ._. 
</s>
<s>
This_DD1 allows_VVZ SOA_NN1 architecture_NN1 to_TO be_VBI a_AT1 collection_NN1 of_IO independent_JJ IT_NN1 systems_NN2 ,_, software_NN1 or_CC hardware_NN1 components_NN2 and_CC application_NN1 functions_VVZ that_CST appears_VVZ to_II its_APPGE users_NN2 as_II a_AT1 single_JJ logical_JJ system_NN1 ._. 
</s>
<s>
The_AT following_JJ four_MC Web_NN1 service_NN1 standards_NN2 forms_VVZ the_AT foundation_NN1 of_IO this_DD1 technology_NN1 (_( C._NP1 Derrick_NP1 Huang_NP1 ,_, Qing_NP1 Hu_NP1 ,_, 2004_MC )_) ,_, (_( Erl_NP1 ,_, 2009_MC )_) p.73_FO :_: Simple_JJ Object_NN1 Access_NN1 Protocol_NN1 (_( SOAP_NN1 )_) ._. 
</s>
<s>
This_DD1 enables_VVZ the_AT interoperability_NN1 between_II systems_NN2 and_CC heterogeneous_JJ platforms_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ for_IF invoking_VVG functions_NN2 and_CC procedures_NN2 on_II remote_JJ systems_NN2 and_CC exchanging_VVG data_NN between_II processes_NN2 ._. 
</s>
<s>
This_DD1 is_VBZ done_VDN by_II sending_VVG service_NN1 messages_NN2 encoded_VVD according_II21 to_II22 SOAP_NN1 1.1_MC specifications_NN2 ._. 
</s>
<s>
Web_NN1 services_NN2 Description_NN1 Language_NN1 (_( WSDL_NP1 )_) is_VBZ for_IF describing_VVG the_AT specific_JJ services_NN2 a_AT1 software_NN1 component_NN1 or_CC application_NN1 provides_VVZ and_CC the_AT interface_NN1 binding_VVG details_NN2 ._. 
</s>
<s>
Universal_JJ Description_NN1 ,_, Discovery_NN1 ,_, and_CC Integration_NN1 (_( UDDI_NP1 )_) is_VBZ for_IF publishing_VVG and_CC searching_VVG Web_NN1 services_NN2 over_II the_AT Internet_NN1 by_II creating_VVG public_JJ and_CC private_JJ Web_NN1 services_NN2 registries_NN2 that_CST enable_VV0 service_NN1 discovery_NN1 and_CC interface_VV0 binding_JJ ._. 
</s>
<s>
The_AT XML_NP1 data_NN representation_NN1 format_NN1 (_( syntax_NN1 )_) establishes_VVZ the_AT structure_NN1 of_IO the_AT messages_NN2 traveling_VVG in_II the_AT SOA_NN1 architecture_NN1 ._. 
</s>
<s>
XML_NP1 format_NN1 enables_VVZ and_CC validates_VVZ service_NN1 message_NN1 to_II communication_NN1 between_II and_CC within_II the_AT heterogeneous_JJ systems_NN2 and_CC components_NN2 the_AT SOA_NN1 architecture_NN1 environment_NN1 ._. 
</s>
<s>
The_AT figure_NN1 below_RL explains_VVZ and_CC illustrates_VVZ the_AT relations_NN2 and_CC interactions_NN2 between_II these_DD2 technology_NN1 components_NN2 ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) The_AT transformation_NN1 of_IO an_AT1 enterprise_NN1 's_GE business_NN1 processes_NN2 to_II services_NN2 according_II21 to_II22 SOA_NP1 principles_NN2 opens_VVZ totally_RR new_JJ possibilities_NN2 of_IO strategic_JJ partnerships_NN2 with_IW suppliers_NN2 ,_, partners_NN2 ,_, and_CC customers_NN2 (_( Hagel_NP1 ,_, J.I._NP1 and_CC J.S._NP2 Brown_NP1 ,_, ,_, 2001_MC )_) ._. 
</s>
<s>
This_DD1 approach_NN1 allows_VVZ services_NN2 from_II external_JJ service_NN1 providers_NN2 to_TO be_VBI included_VVN as_II part_NN1 of_IO company_NN1 's_GE own_DA system_NN1 without_IW having_VHG to_TO understand_VVI the_AT underlying_JJ implementation_NN1 of_IO the_AT service_NN1 ._. 
</s>
<s>
According_II21 to_II22 H._NP1 Luthria_NP1 ,_, F._NP1 Rabhi_NP1 and_CC M._NN1 Briers_NN2 (_( 2007_MC )_) "_" the_AT most_RGT significant_JJ advantage_NN1 of_IO a_AT1 service-based_JJ business_NN1 model_NN1 in_II the_AT context_NN1 of_IO inter-enterprise_JJ integration_NN1 is_VBZ that_CST services_NN2 have_VH0 interfaces_NN2 that_CST are_VBR location_NN1 transparent_JJ "_" ._. 
</s>
<s>
This_DD1 means_VVZ that_CST the_AT services_NN2 are_VBR reachable_JJ independent_NN1 of_IO whether_CSW they_PPHS2 are_VBR implemented_VVN within_II the_AT boundaries_NN2 of_IO the_AT same_DA business_NN1 process_NN1 ,_, in_II another_DD1 business_NN1 process_NN1 within_II the_AT organization_NN1 ,_, or_CC in_II a_AT1 business_NN1 process_NN1 in_II an_AT1 external_JJ (_( partner_NN1 or_CC customer_NN1 )_) domain_NN1 ._. 
</s>
<s>
This_DD1 opportunity_NN1 extends_VVZ companies_NN2 business_NN1 strategies_NN2 beyond_II organizational_JJ boundaries_NN2 ._. 
</s>
<s>
The_AT web-service_JJ system_NN1 environment_NN1 is_VBZ often_RR made_VVN transparent_JJ for_IF the_AT service_NN1 consumer_NN1 by_II using_VVG a_AT1 service_NN1 bus_NN1 architecture_NN1 solution_NN1 ._. 
</s>
<s>
This_DD1 technique_NN1 is_VBZ not_XX described_VVN in_II very_JJ detail_NN1 in_II this_DD1 paper_NN1 ,_, but_CCB the_AT below_II figure_NN1 illustrates_VVZ how_RRQ it_PPH1 is_VBZ used_VVN and_CC constructed_VVN in_II IT-infrastructures_NN2 ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) Service_NN1 bus_NN1 performs_VVZ the_AT needed_VVN functions_NN2 (_( e.g._REX provides_VVZ a_AT1 customer_NN1 order_NN1 information_NN1 etc._RA )_) for_IF the_AT service_NN1 requestors_NN2 and_CC hides_VVZ the_AT underlying_JJ it-system_JJ source_NN1 where_CS the_AT actual_JJ data_NN and_CC information_NN1 is_VBZ retrieved_VVN from_II ._. 
</s>
<s>
Service_NN1 bus_NN1 solution_NN1 makes_VVZ the_AT communication_NN1 ,_, interaction_NN1 possible_JJ with_IW the_AT various_JJ heterogeneous_JJ systems_NN2 and_CC component_JJ possible_JJ ,_, regardless_RR of_IO their_APPGE internal_JJ architecture_NN1 construction_NN1 or_CC process_VV0 logic_NN1 and_RR31 so_RR32 forth._RR33 2.6_MC ._. 
</s>
<s>
Why_RRQ SOA_NP1 ?_? 
</s>
<s>
Today_RT 's_GE enterprise_NN1 IT-infrastructure_NN1 and_CC system_NN1 set-ups_NN2 are_VBR very_RG complex_JJ and_CC they_PPHS2 are_VBR very_RG demanding_JJ to_TO maintain_VVI as_II31 well_II32 as_II33 challenging_VVG to_TO make_VVI new_JJ development_NN1 on_II them_PPHO2 ._. 
</s>
<s>
This_DD1 is_VBZ due_II21 to_II22 various_JJ vendor_NN1 systems_NN2 ,_, platforms_NN2 ,_, applications_NN2 and_CC components_NN2 that_CST were_VBDR not_XX meant_VVN to_TO interact_VVI with_IW each_PPX221 other_PPX222 ._. 
</s>
<s>
The_AT earlier_JJR legacy_NN1 systems_NN2 ,_, monolithic_JJ hard_JJ coded_JJ and_CC coupled_VVD entities_NN2 ,_, the_AT proprietary_JJ environment_NN1 were_VBDR built_VVN to_TO function_VVI on_II their_APPGE own_DA ._. 
</s>
<s>
They_PPHS2 were_VBDR not_XX designed_VVN to_TO communicate_VVI with_IW other_JJ applications_NN2 and_CC systems_NN2 outside_II their_APPGE "_" boundaries_NN2 "_" ._. 
</s>
<s>
Those_DD2 system_NN1 set-ups_NN2 did_VDD not_XX allow_VVI any_DD business_NN1 intelligent_JJ to_TO work_VVI beyond_RL to_II what_DDQ they_PPHS2 were_VBDR designed_VVN to_TO accomplish_VVI ._. 
</s>
<s>
It_PPH1 required_JJ normal_JJ software-projects_NN2 to_TO make_VVI any_DD changes_NN2 to_II 9_MC them_PPHO2 and_CC this_DD1 could_VM be_VBI very_RG difficult_JJ accomplish_VV0 since_CS the_AT changes_NN2 had_VHD often_RR impact_NN1 on_II the_AT whole_JJ environment_NN1 ._. 
</s>
<s>
J._NP1 Noel_NP1 (_( 2005_MC )_) calls_VVZ this_DD1 as_II a_AT1 "_" result_NN1 of_IO integration_NN1 spaghetti_NN1 "_" ._. 
</s>
<s>
Also_RR ,_, the_AT results_NN2 were_VBDR not_XX always_RR exactly_RR what_DDQ the_AT company_NN1 were_VBDR expecting_VVG ._. 
</s>
<s>
Companies_NN2 are_VBR today_RT aware_JJ of_IO these_DD2 problems_NN2 and_CC have_VH0 found_VVN this_DD1 old_JJ faction_NN1 system_NN1 development_NN1 very_RG ineffective_JJ ,_, time_NNT1 consuming_VVG and_CC expensive_JJ ._. 
</s>
<s>
What_DDQ is_VBZ it_PPH1 that_DD1 SOA_NN1 architecture_NN1 approach_NN1 offers_NN2 beyond_II what_DDQ earlier_JJR concepts_NN2 ,_, techniques_NN2 or_CC development_NN1 methods_NN2 made_VVD possible_JJ ?_? 
</s>
<s>
Can_VV0 SOA_NN1 be_VBI the_AT "_" silver_NN1 bullet_NN1 "_" of_IO solving_VVG complex_JJ IT-integration_JJ challenges_NN2 ?_? 2.6.1_MC ._. 
</s>
<s>
SOA_NP1 Promise_NN1 SOA_NN1 possesses_VVZ a_AT1 lot_NN1 of_IO promise_NN1 according_II21 to_II22 the_AT author_NN1 's_GE literature_NN1 review_NN1 of_IO this_DD1 subject_NN1 ._. 
</s>
<s>
Most_DAT of_IO the_AT papers_NN2 and_CC books_NN2 about_II this_DD1 subject_NN1 are_VBR praising_VVG and_CC speaking_VVG only_RR good_JJ things_NN2 about_II SOA_NP1 ._. 
</s>
<s>
The_AT idea_NN1 of_IO creating_VVG new_JJ value_NN1 from_II existing_JJ systems_NN2 ,_, eliminate_VV0 communication_NN1 barriers_NN2 to_II (_( old_JJ )_) legacy_NN1 systems_NN2 and_CC enabling_VVG seamless_JJ enterprise_NN1 integration_NN1 is_VBZ something_PN1 that_CST raise_VV0 organizations_NN2 interest_NN1 of_IO finding_VVG more_RRR about_II SOA_NP1 (_( ref_NN1 )_) ._. 
</s>
<s>
One_PN1 could_VM argue_VVI that_CST it_PPH1 must_VM be_VBI most_RGT rational_JJ to_TO utilize_VVI such_DA a_AT1 technology_NN1 opportunity_NN1 that_CST SOA_NP1 offers_NN2 ._. 
</s>
<s>
There_EX must_VM be_VBI money_NN1 and_CC time_NNT1 to_TO win_VVI compared_VVN to_II normal_JJ old_JJ fashion_NN1 system_NN1 development_NN1 where_CS cost-_JJ and_CC time-overruns_NN2 is_VBZ everyday_JJ life_NN1 ._. 
</s>
<s>
Due_II21 to_II22 the_AT limitation_NN1 of_IO this_DD1 paper_NN1 ,_, the_AT author_NN1 is_VBZ not_XX going_VVGK to_TO discuss_VVI more_RGR deeply_RR of_IO this_DD1 particular_JJ issue_NN1 ,_, but_CCB these_DD2 will_VM be_VBI discussed_VVN in_II detail_NN1 in_II the_AT following_JJ Thesis_NN1 paper_NN1 ._. 
</s>
<s>
The_AT below_II figure_NN1 illustrates_VVZ what_DDQ business_NN1 and_CC technology_NN1 challenges_NN2 SOA_NN1 architecture_NN1 "_" solution_NN1 "_" technology_NN1 is_VBZ promising_JJ to_TO cover_VVI and_CC tackle_NN1 ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) 2.7_MC ._. 
</s>
<s>
SOA_NP1 Challenge_NN1 According_II21 to_II22 Erickson_NP1 and_CC Siau_NP1 (_( 2008_MC )_) there_EX are_VBR very_RG few_DA2 critical_JJ studies_NN2 about_II SOA_NP1 ,_, which_DDQ is_VBZ very_RG unfortunate_JJ due_II21 to_II22 the_AT increased_JJ interest_NN1 towards_II this_DD1 technology_NN1 (_( Erl_NP1 ,_, 2009_MC )_) et_RA21 al_RA22 ._. 
</s>
<s>
Though_CS ,_, there_EX are_VBR now_RT emerging_VVG some_DD doubts_NN2 of_IO the_AT real_JJ value_NN1 of_IO adopting_VVG SOA_NP1 (_( Dorman_NP1 (_( 2007_MC )_) ,_, Havenstein_NP1 (_( 2007_MC )_) ,_, Ricadela_NP1 (_( 2006_MC )_) and_CC Trembly_NP1 (_( 2007_MC )_) )_) ._. 
</s>
<s>
Here_RL the_AT author_NN1 will_VM bring_VVI up_RP some_DD criticism_NN1 or_CC challenges_NN2 against_II SOA_NP1 architecture_NN1 implementation_NN1 approach_NN1 ._. 
</s>
<s>
There_EX are_VBR more_RRR ,_, but_CCB those_DD2 will_VM not_XX be_VBI covered_VVN in_II this_DD1 paper_NN1 ._. 
</s>
<s>
One_MC1 of_IO the_AT main_JJ concerns_NN2 according_II21 to_II22 SOA_NP1 literature_NN1 are_VBR immature_JJ SOA_NN1 standards_NN2 (_( Erl_NP1 ,_, 2009_MC )_) (_( Marks_NP1 &;_NULL Bell_NP1 ,_, 2006_MC )_) et_RA21 al_RA22 ._. 
</s>
<s>
The_AT technologies_NN2 that_CST are_VBR used_VVN in_II SOA_NP1 are_VBR based_VVN on_II standards_NN2 ._. 
</s>
<s>
Many_DA2 of_IO the_AT standards_NN2 are_VBR still_RR developing_JJ and_CC are_VBR not_XX mature_JJ enough_RR to_TO be_VBI closed_VVN as_CSA some_DD specific_JJ version_NN1 number_NN1 ._. 
</s>
<s>
Also_RR ,_, many_DA2 standards_NN2 are_VBR overlapping_VVG with_IW each_PPX221 other_PPX222 which_DDQ bring_VV0 additional_JJ challenges_NN2 into_II the_AT SOA_NN1 developing_JJ arena_NN1 ._. 
</s>
<s>
Due_II21 to_II22 this_DD1 "_" problems_NN2 "_" ,_, companies_NN2 ,_, partners_NN2 and_CC SOA_NP1 solution_NN1 vendors_NN2 can_VM use_VVI and_CC interpret_VVI these_DD2 floating_JJ standards_NN2 as_CSA they_PPHS2 please_RR ._. 
</s>
<s>
This_DD1 is_VBZ problematic_JJ in_II situations_NN2 when_RRQ different_JJ systems_NN2 and_CC components_NN2 needs_VVZ to_TO communicate_VVI with_IW each_PPX221 other_PPX222 and_CC when_CS they_PPHS2 are_VBR build_NN1 based_VVN on_II different_JJ specifications_NN2 or_CC standard_JJ versions_NN2 ._. 
</s>
<s>
These_DD2 kind_NN1 of_IO scenarios_NN2 can_VM unable_JJ the_AT system_NN1 to_TO work_VVI properly_RR ._. 
</s>
<s>
Implementing_VVG SOA_NN1 is_VBZ not_XX only_RR a_AT1 technology_NN1 matter_NN1 or_CC challenge_NN1 ._. 
</s>
<s>
According_II21 to_II22 SOA_NP1 books_NN2 and_CC papers_NN2 (_( (_( Erl_NP1 ,_, 2009_MC )_) ,_, (_( Erickson_NP1 &;_NULL Siau_NP1 ,_, 2008_MC )_) et_RA21 al._RA22 ,_, peoples_NN2 (_( employees_NN2 )_) attitude_NN1 to_II system_NN1 or_CC infrastructure_NN1 changes_NN2 is_VBZ also_RR a_AT1 challenge_NN1 organizations_NN2 need_VV0 to_TO deal_VVI with_IW when_CS considering_VVG or_CC implementing_VVG SOA_NN1 ._. 
</s>
<s>
Giving_VVG them_PPHO2 right_JJ kind_NN1 of_IO training_NN1 and_CC preparation_NN1 time_NNT1 to_TO overcome_VVI the_AT challenges_NN2 of_IO the_AT changes_NN2 ._. 
</s>
<s>
Security_NN1 is_VBZ more_RGR challenging_JJ issue_NN1 in_II SOA_NP1 environment_NN1 compared_VVN to_II "_" normal_JJ "_" client-_JJ server_NN1 architecture_NN1 with_IW single_JJ point_NN1 of_IO authentication_NN1 ._. 
</s>
<s>
In_II the_AT loosely_RR coupled_VVN and_CC distributed_JJ system_NN1 set-up_NN1 environment_NN1 of_IO SOA_NP1 ,_, this_DD1 is_VBZ not_XX possible_JJ ._. 
</s>
<s>
Security_NN1 becomes_VVZ significantly_RR more_RGR complex_JJ and_CC demanding_VVG to_TO handle_VVI safely_RR (_( Erl_NP1 ,_, 2009_MC )_) p._NN1 290_MC ._. 
</s>
<s>
There_EX is_VBZ no_AT "_" one_MC1 way_NN1 "_" how_RRQ to_TO deal_VVI with_IW this_DD1 concern_NN1 ,_, but_CCB there_EX needs_VVZ to_TO be_VBI appropriate_JJ plans_NN2 how_RRQ to_TO deal_VVI with_IW this_DD1 challenge._NNU 3_MC RESEARCH_NN1 METHODOLOGY_NN1 (_( Note_VV0 this_DD1 part_NN1 is_VBZ still_RR written_VVN in_II planning_VVG format_NN1 ,_, but_CCB it_PPH1 will_VM be_VBI changed_VVN to_II how_RRQ things_NN2 was_VBDZ done_VDN ,_, when_CS they_PPHS2 are_VBR done_VDN )_) This_DD1 study_NN1 will_VM use_VVI quantitative_JJ research_NN1 method_NN1 where_CS the_AT author_NN1 is_VBZ sending_VVG survey_NN1 of_IO SOA_NP1 adaption_NN1 intention_NN1 factors_NN2 to_II IT-managers_NN2 and_CC architects_NN2 in_II the_AT industry_NN1 ._. 
</s>
<s>
For_IF this_DD1 part_NN1 the_AT author_NN1 is_VBZ willing_JJ to_TO analyze_VVI and_CC test_VVI some_DD hypothesis_NN1 with_IW research_NN1 variables_NN2 and_CC specifying_VVG and_CC interpreting_VVG relationships_NN2 between_II them_PPHO2 ._. 
</s>
<s>
This_DD1 is_VBZ done_VDN to_TO find_VVI possible_JJ facts_NN2 or_CC information_NN1 of_IO possible_JJ SOA_NN1 innovation_NN1 adaption_NN1 factors_NN2 ._. 
</s>
<s>
The_AT author_NN1 is_VBZ also_RR conducting_VVG some_DD interviews_NN2 with_IW people_NN that_CST possess_VV0 firsthand_JJ knowledge_NN1 of_IO SOA_NP1 technology_NN1 ._. 
</s>
<s>
Here_RL a_AT1 qualitative_JJ research_NN1 approach_NN1 is_VBZ used_VVN to_TO deepen_VVI the_AT understanding_NN1 of_IO this_DD1 new_JJ technology_NN1 and_CC its_APPGE adaption_NN1 intention_NN1 factors_NN2 ._. 
</s>
<s>
This_DD1 is_VBZ done_VDN to_TO describe_VVI some_DD specific_JJ characteristics_NN2 of_IO SOA_NP1 technology_NN1 and_CC it_PPH1 usage_NN1 in_II industry._NNU 3.1_MC ._. 
</s>
<s>
Research_NN1 model_NN1 and_CC hypotheses_NN2 The_AT research_NN1 study_NN1 is_VBZ based_VVN on_II Roger_NP1 's_GE (_( 1995_MC )_) Diffusion_NN1 Innovation_NN1 Theory_NN1 ,_, but_CCB this_DD1 theory_NN1 is_VBZ further_RRR modified_VVN according_II21 to_II22 adaption_NN1 intention_NN1 model_NN1 constructed_VVN by_II (_( Tsai_FW ;_; Lee_NP1 ;_; &;_NULL Wu_NP1 ,_, 2010/47_MF )_) which_DDQ is_VBZ the_AT research_NN1 model_NN1 that_CST this_DD1 paper_NN1 uses_NN2 ._. 
</s>
<s>
This_DD1 study_NN1 slightly_RR transforms_VVZ adaption_NN1 intention_NN1 model_NN1 to_II the_AT specific_JJ needs_NN2 and_CC features_NN2 of_IO SOA_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ done_VDN according_II21 to_II22 the_AT literature_NN1 review_NN1 of_IO this_DD1 subject_NN1 by_II the_AT author_NN1 of_IO this_DD1 paper_NN1 ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) The_AT study_NN1 hypothesis_NN1 and_CC related_JJ statements_NN2 are_VBR presented_VVN in_II the_AT following_JJ table_NN1 ._. 
</s>
<s>
Hypothesis_NN1 Attribute_NN1 Statement_NN1 H1_FO :_: Relative_JJ advantage_NN1 has_VHZ a_AT1 positive_JJ effect_NN1 on_II adaption_NN1 intention._NNU 12_MC R1_FO Increased_JJ cost_NN1 efficiency_NN1 R2_FO Enhances_VVZ system_NN1 development_NN1 R3_FO Enhances_VVZ business_NN1 and_CC IT_NN1 strategy_NN1 alignment_NN1 R4_FO Improves_VVZ reuse_NN1 of_IO system_NN1 environment/components_FU ._. 
</s>
<s>
R5_FO Improves_VVZ company_NN1 's_GE competitive_JJ advantage_NN1 H2_FO :_: Complexity_NN1 has_VHZ a_AT1 negative_JJ effect_NN1 on_II adaption_NN1 intention_NN1 C1_FO Risks_VVZ involved_JJ in_II SOA_NP1 C2_FO Immature_JJ and_CC overlapping_JJ SOA_NN1 standards_NN2 C3_FO SOA_NN1 security_NN1 concerns_VVZ H3_FO :_: Supply-chain_JJ integration_NN1 has_VHZ a_AT1 possitive_JJ effect_NN1 on_II adaption_NN1 intention_NN1 ._. 
</s>
<s>
S1_FO Improves_VVZ information_NN1 sharing_VVG S2_FO Enables_VVZ operation_NN1 integration_NN1 S3_FO Enable_VV0 service_NN1 outsourcing_VVG H4_FO :_: Organizational_JJ readiness_NN1 has_VHZ a_AT1 possitive_JJ effect_NN1 on_II adaption_NN1 intention_NN1 O1_FO Top_JJ management_NN1 support_NN1 O2_FO Organizational_JJ attitude_NN1 to_II changes_NN2 O3_FO IT_NN1 expertise_NN1 O4_FO Innovation_NN1 alertness_NN1 H5_FO :_: Communication_NN1 channel_NN1 has_VHZ on_II positive_JJ effect_NN1 on_II adaption_NN1 intention_NN1 ._. 
</s>
<s>
Organizational_JJ decision_NN1 making_VVG culture_NN1 'Opinion_NN1 leaders_NN2 '_GE or_CC 'change_VV0 agents_NN2 '_GE impact_NN1 effects_NN2 Championing_VVG image_NN1 Successful_JJ SOA_NN1 implementations_NN2 The_AT research_NN1 hypotheses_NN2 are_VBR conducted_VVN out_II21 of_II22 the_AT research_NN1 model_NN1 as_CSA dependent_JJ variables_NN2 ,_, which_DDQ each_DD1 have_VH0 their_APPGE own_DA unique_JJ independent_JJ variables_NN2 ._. 
</s>
<s>
The_AT hypotheses_NN2 in_II this_DD1 study_NN1 are_VBR then_RT tested_VVN against_II the_AT independent_JJ variables_NN2 to_TO measure_VVI if_CSW the_AT predictions_NN2 can_VM be_VBI confirmed_VVN by_II the_AT empirical_JJ data_NN of_IO the_AT survey._NNU 3.2_MC ._. 
</s>
<s>
Sample_NN1 and_CC data_NN collection_NN1 The_AT data_NN collection_NN1 methods_NN2 that_CST were_VBDR used_VVN in_II this_DD1 study_NN1 included_VVD survey_NN1 (_( questionnaire_NN1 )_) that_DD1 was_VBDZ sent_VVN to_TO target_VVI persons_NN2 of_IO IT-managers_NN2 and_CC architects_NN2 working_VVG in_II Finland_NP1 who_PNQS had_VHD prior_JJ knowledge_NN1 of_IO SOA_NN1 ._. 
</s>
<s>
The_AT selected_JJ sample_NN1 population_NN1 for_IF the_AT survey_NN1 was_VBDZ randomly_RR selected_VVN through_II Hanken_JJ library_NN1 industry_NN1 databases_NN2 and_CC internet_NN1 ._. 
</s>
<s>
The_AT persons_NN2 for_IF the_AT interview_NN1 part_NN1 were_VBDR selected_VVN by_II the_AT author_NN1 whom_PNQO he_PPHS1 knew_VVD knows_VVZ about_II SOA_NP1 and_CC who_PNQS would_VM be_VBI able_JK to_TO answer_VVI the_AT research_NN1 questions_NN2 for_IF this_DD1 study._NNU 4_MC RESEARCH_NN1 RESULTS_NN2 4.1_MC ._. 
</s>
<s>
Descriptive_JJ statistics_NN Questionnaire_NN1 was_VBDZ sent_VVN to_II 26_MC persons_NN2 ..._... 
</s>
<s>
Response_NN1 rate_NN1 ,_, time_NNT1 to_TO answer_VVI 4.2_MC ._. 
</s>
<s>
Findings_NN2 on_II hypotheses_NN2 SPSS_NP1 was_VBDZ used_JJ Hypotheses_NN2 1_MC1 ,_, 2_MC 3_MC 4.3_MC ._. 
</s>
<s>
A_AT1 Critical_JJ Evaluation_NN1 of_IO the_AT Results_NN2 Validity_NN1 ,_, reliability_NN1 ,_, generalizability_NN1 5_MC CONCLUSIONS_NN2 5.1_MC ._. 
</s>
<s>
Summary_NN1 and_CC analysis_NN1 of_IO the_AT paper_NN1 Will_VM be_VBI written_VVN when_CS there_EX is_VBZ something_PN1 to_TO say_VVI .._... 5.2_MC ._. 
</s>
<s>
Suggestions_NN2 for_IF further_JJR research_NN1 
</s>
