<s>
1_MC1 ._. 
</s>
<s>
Introduction_NN1 
</s>
<s>
For_IF many_DA2 enterprises_NN2 internationalization_NN1 can_VM be_VBI an_AT1 attractive_JJ way_NN1 to_TO seek_VVI new_JJ markets_NN2 ,_, expand_VV0 operations_NN2 ,_, and_CC eventually_RR maintain_VV0 greater_JJR incomes_NN2 ._. 
</s>
<s>
Mergers_NN2 and_CC acquisitions_NN2 are_VBR a_AT1 fast_JJ way_NN1 for_IF companies_NN2 to_TO grow_VVI and_CC expand_VVI their_APPGE functions_NN2 abroad_RL ._. 
</s>
<s>
However_RR ,_, companies_NN2 going_VVG abroad_RL face_VV0 many_DA2 challenges_NN2 that_CST are_VBR not_XX as_RG dominant_JJ ,_, if_CS even_RR existent_JJ ,_, on_II the_AT domestic_JJ market_NN1 ._. 
</s>
<s>
Many_DA2 of_IO the_AT challenges_NN2 have_VH0 to_TO do_VDI with_IW differences_NN2 in_II culture_NN1 ,_, both_RR national_JJ and_CC organizational_JJ culture_NN1 ._. 
</s>
<s>
As_CSA internationals_NN2 mergers_NN2 and_CC acquisitions_NN2 take_VV0 place_NN1 more_RRR and_CC more_RGR often_RR it_PPH1 is_VBZ important_JJ to_TO study_VVI the_AT factors_NN2 behind_II their_APPGE success_NN1 and_CC failure_NN1 ._. 
</s>
<s>
Since_CS Human_JJ resource_NN1 is_VBZ the_AT department_NN1 of_IO the_AT company_NN1 that_CST takes_VVZ care_NN1 of_IO the_AT employees_NN2 ,_, they_PPHS2 possess_VV0 a_AT1 key_JJ position_NN1 in_II assuring_VVG the_AT success_NN1 of_IO the_AT merger_NN1 or_CC the_AT acquisition_NN1 ,_, and_CC it_PPH1 is_VBZ the_AT perspective_NN1 that_CST will_VM be_VBI used_VVN in_II this_DD1 study_NN1 ._. 
</s>
<s>
The_AT purpose_NN1 of_IO this_DD1 study_NN1 is_VBZ to_TO recognize_VVI and_CC analyze_VVI the_AT largest_JJT and_CC most_RGT common_JJ challenges_NN2 that_CST HR_NNU faces_NN2 in_II the_AT process_NN1 of_IO international_JJ mergers_NN2 and_CC acquisitions_NN2 ._. 
</s>
<s>
According_II21 to_II22 a_AT1 McKinsey_NP1 study_NN1 conducted_VVN in_II 2000_MC the_AT factors_NN2 having_VHG a_AT1 key_JJ role_NN1 in_II the_AT success_NN1 of_IO mergers_NN2 and_CC acquisitions_NN2 are_VBR 1_MC1 ._. 
</s>
<s>
Retention_NN1 of_IO key_JJ talent_NN1 ,_, 2_MC ._. 
</s>
<s>
Effective_JJ communication_NN1 ,_, 3_MC ._. 
</s>
<s>
Executive_NN1 retention_NN1 ,_, 4_MC ._. 
</s>
<s>
Cultural_JJ integration_NN1 ._. 
</s>
<s>
An_AT1 overview_NN1 of_IO academic_JJ literature_NN1 written_VVN about_II the_AT subject_NN1 will_VM be_VBI presented_VVN ._. 
</s>
<s>
It_PPH1 will_VM be_VBI discussed_VVN if_CS academic_JJ studies_NN2 support_VV0 the_AT argument_NN1 made_VVN by_II McKinsey_NP1 ._. 
</s>
<s>
The_AT theoretical_JJ framework_NN1 is_VBZ divided_VVN into_II three_MC parts_NN2 ;_; the_AT first_MD two_MC are_VBR based_VVN on_II academic_JJ literature_NN1 ._. 
</s>
<s>
In_II the_AT first_MD part_NN1 the_AT process_NN1 of_IO mergers_NN2 and_CC acquisitions_NN2 will_VM be_VBI presented_VVN ._. 
</s>
<s>
In_II the_AT second_MD part_NN1 ,_, the_AT main_JJ challenges_NN2 of_IO the_AT process_NN1 will_VM be_VBI analyzed_VVN from_II a_AT1 Human_JJ resource-_JJ perspective_NN1 ._. 
</s>
<s>
In_II the_AT last_MD part_NN1 ,_, the_AT literature_NN1 presented_VVN will_VM be_VBI analyzed_VVN ,_, and_CC compared_VVN to_II the_AT findings_NN2 of_IO McKinsey_NP1 ,_, as_CSA mentioned_VVN earlier._NNU 1.1_MC ._. 
</s>
<s>
Research_NN1 question_NN1 The_AT research_NN1 question_NN1 in_II this_DD1 study_NN1 will_VM be_VBI 1_MC1 ._. 
</s>
<s>
What_DDQ are_VBR the_AT main_JJ challenges_NN2 of_IO Human_JJ resource_NN1 management_NN1 in_II international_JJ mergers_NN2 and_CC acquisitions_NN2 ?_? 1.2_MC ._. 
</s>
<s>
Definitions_NN2 Merger_NN1 A_ZZ1 merger_NN1 is_VBZ formed_VVN when_CS two_MC separate_JJ entities_NN2 come_VV0 together_RL to_TO build_VVI a_AT1 new_JJ company_NN1 with_IW combined_JJ assets_NN2 ._. 
</s>
<s>
(_( Schuler_NP1 &;_NULL Jackson_NP1 ,_, 2001_MC )_) Acquisition_NN1 In_II an_AT1 acquisition_NN1 one_MC1 company_NN1 purchases_VVZ the_AT majority_NN1 of_IO another_DD1 companys_NN2 stocks_NN2 ,_, the_AT purchased_JJ company_NN1 becomes_VVZ a_AT1 part_NN1 of_IO the_AT other_JJ company_NN1 ._. 
</s>
<s>
(_( Schuler_NP1 &;_NULL Jackson_NP1 ,_, 2001_MC )_) International_JJ Merger_NN1 and_CC acquisition_NN1 Mergers_NN2 and_CC acquisitions_NN2 are_VBR defined_VVN international_JJ when_CS the_AT companies_NN2 involved_VVN have_VH0 head_JJ quarters_NN in_II different_JJ countries_NN2 ._. 
</s>
<s>
2_MC ._. 
</s>
<s>
Theoretical_JJ framework_NN1 There_EX have_VH0 been_VBN several_DA2 theories_NN2 presented_VVN on_II the_AT roles_NN2 of_IO Human_JJ Resource_NN1 department_NN1 ._. 
</s>
<s>
Perhaps_RR the_AT most_RGT widely_RR known_VVN and_CC accepted_VVN in_II academic_JJ research_NN1 is_VBZ the_AT one_PN1 presented_VVD by_II Ulrich_NP1 in_II 1997_MC ._. 
</s>
<s>
According_II21 to_II22 the_AT study_NN1 conducting_VVG four_MC different_JJ roles_NN2 can_VM be_VBI identified_VVN :_: 1_MC1 ._. 
</s>
<s>
Strategic_JJ partner_NN1 ,_, 2_MC ._. 
</s>
<s>
Administrative_JJ Expert_NN1 ,_, 3_MC ._. 
</s>
<s>
Employee_NN1 champion_NN1 ,_, and_CC 4_MC ._. 
</s>
<s>
Change_VV0 agent_NN1 ._. 
</s>
<s>
According_II21 to_II22 Antila_NP1 (_( Antila_NP1 ,_, 2006_MC )_) all_DB of_IO these_DD2 four_MC can_VM be_VBI found_VVN in_II the_AT processes_NN2 of_IO international_JJ mergers_NN2 and_CC acquisitions_NN2 ._. 
</s>
<s>
However_RRQV it_PPH1 is_VBZ important_JJ to_TO acknowledge_VVI that_CST the_AT role_NN1 of_IO an_AT1 HR_NNU expert_NN1 is_VBZ not_XX similar_JJ in_II all_DB organizations_NN2 ,_, it_PPH1 can_VM vary_VVI depending_II21 on_II22 the_AT person_NN1 ,_, the_AT job_NN1 description_NN1 or_CC the_AT situations_NN2 ._. 
</s>
<s>
Antila_NP1 (_( Antila_NP1 ,_, 2006_MC )_) argues_VVZ that_CST the_AT challenges_NN2 faced_VVN by_II Human_JJ resource_NN1 management_NN1 start_NN1 already_RR before_II the_AT actual_JJ merger_NN1 or_CC acquisition_NN1 ._. 
</s>
<s>
As_CSA Ulrich_NP1 has_VHZ also_RR presented_VVN ,_, Human_JJ resource_NN1 management_NN1 should_VM be_VBI involved_VVN already_RR in_II the_AT strategy_NN1 creating_VVG process_NN1 ._. 
</s>
<s>
According_II21 to_II22 Antila_NP1 (_( Antila_NP1 ,_, 2006_MC )_) this_DD1 nowadays_RT also_RR is_VBZ often_RR the_AT situation_NN1 in_II practice_NN1 ._. 
</s>
<s>
The_AT findings_NN2 of_IO the_AT study_NN1 also_RR indicate_VV0 that_CST if_CS the_AT HR_NNU management_NN1 is_VBZ not_XX involved_JJ in_II the_AT strategic_JJ work_NN1 the_AT implementation_NN1 of_IO the_AT strategy_NN1 is_VBZ very_RG negatively_RR affected_VVN as_CSA it_PPH1 becomes_VVZ more_RGR difficult_JJ for_IF the_AT people_NN involved_VVD to_TO implement_VVI a_AT1 strategy_NN1 created_VVN by_II others_NN2 ._. 
</s>
<s>
This_DD1 point_NN1 of_IO view_NN1 is_VBZ supported_VVN by_II Schuler_NP1 and_CC Jacksons_NP2 study_VV0 also_RR (_( Schuler_NP1 &;_NULL Jackson_NP1 ,_, 2001_MC )_) ._. 
</s>
<s>
They_PPHS2 acclaim_VV0 that_CST in_BCL21 order_BCL22 for_IF the_AT merger_NN1 or_CC the_AT acquisition_NN1 to_TO be_VBI successful_JJ HR_NNU management_NN1 shall_VM be_VBI developing_VVG the_AT strategy_NN1 and_CC the_AT process_NN1 ._. 
</s>
<s>
When_CS it_PPH1 comes_VVZ to_II the_AT implementation_NN1 of_IO the_AT strategy_NN1 ,_, Antila_NP1 (_( Antila_NP1 ,_, 2006_MC )_) writes_VVZ that_CST the_AT HR_NNU management_NN1 is_VBZ responsible_JJ for_IF controlling_VVG and_CC planning_VVG the_AT strategy_NN1 implementation_NN1 ,_, but_CCB also_RR for_IF the_AT integration_NN1 process_NN1 ._. 
</s>
<s>
Another_DD1 important_JJ aspect_NN1 is_VBZ that_CST according_II21 to_II22 the_AT study_NN1 HR_NNU management_NN1 play_VV0 a_AT1 key_JJ role_NN1 in_II taking_VVG care_NN1 of_IO administrative_JJ work_NN1 during_II the_AT merger_NN1 or_CC acquisition_NN1 process_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ even_RR considered_VVN given_VVN ,_, that_DD1 HR_NNU management_NN1 has_VHZ responsibility_NN1 over_II the_AT legal_JJ aspects_NN2 of_IO the_AT implementation_NN1 and_CC all_DB the_AT agreements_NN2 ,_, as_II31 well_II32 as_II33 pay_NN1 roll_NN1 policies_NN2 and_CC activities_NN2 ._. 
</s>
<s>
As_II a_AT1 part_NN1 of_IO being_VBG responsible_JJ for_IF the_AT pay_NN1 roll_NN1 activities_NN2 ,_, HR_NNU management_NN1 is_VBZ often_RR a_AT1 lot_NN1 in_II contact_NN1 with_IW local_JJ labor_NN1 unions_NN2 ._. 
</s>
<s>
Antila_NN1 writes_VVZ that_CST this_DD1 can_VM be_VBI a_AT1 challenge_NN1 that_CST often_RR is_VBZ ignored_VVN in_II studies_NN2 of_IO international_JJ mergers_NN2 and_CC acquisitions_NN2 ._. 
</s>
<s>
Focus_NN1 was_VBDZ also_RR given_VVN ,_, however_RGQV little_RR ,_, to_II managing_VVG cultural_JJ challenges_NN2 ._. 
</s>
<s>
Same_DA phenomena_NN2 can_VM be_VBI seen_VVN in_II the_AT study_NN1 of_IO Schuler_NP1 and_CC Jackson_NP1 (_( Schuler_NP1 &;_NULL Jackson_NP1 ,_, 2001_MC )_) as_CSA they_PPHS2 mention_VV0 the_AT importance_NN1 of_IO integrating_VVG and_CC managing_VVG the_AT eventual_JJ cultural_JJ issues_NN2 that_CST may_VM occur_VVI ._. 
</s>
<s>
However_RR ,_, neither_DD1 of_IO the_AT studies_NN2 gives_VVZ any_DD solutions_NN2 on_II how_RRQ to_TO manage_VVI these_DD2 challenges_NN2 ._. 
</s>
<s>
In_II the_AT process_NN1 of_IO implementing_VVG the_AT merger_NN1 or_CC the_AT acquisition_NN1 ,_, Antila_NP1 highlights_VVZ that_DD1 communication_NN1 is_VBZ one_MC1 of_IO the_AT focus_NN1 points_NN2 of_IO HR_NNU managements_NN2 work_VV0 ._. 
</s>
<s>
This_DD1 is_VBZ supported_VVN by_II the_AT study_NN1 made_VVN by_II Schuler_NP1 and_CC Jackson_NP1 (_( Schuler_NP1 &;_NULL Jackson_NP1 ,_, 2001_MC )_) ._. 
</s>
<s>
Antila_NN1 discusses_VVZ more_RRR the_AT role_NN1 of_IO HR_NNU management_NN1 as_II the_AT one_PN1 taking_VVG care_NN1 of_IO the_AT communication_NN1 towards_II all_DB directions_NN2 ;_; between_II executives_NN2 and_CC line_NN1 managers_NN2 ,_, between_II the_AT old_JJ and_CC the_AT new_JJ company_NN1 and_CC information_NN1 to_II all_DB the_AT employees_NN2 of_IO the_AT company_NN1 ._. 
</s>
<s>
Schuler_NP1 and_CC Jackson_NP1 focus_VV0 more_RRR on_II the_AT responsibility_NN1 of_IO providing_VVG an_AT1 efficient_JJ way_NN1 of_IO communication_NN1 within_II the_AT company_NN1 and_CC overseeing_VVG that_CST everybody_PN1 is_VBZ kept_VVN informed_VVN ._. 
</s>
<s>
Mergers_NN2 and_CC acquisitions_NN2 are_VBR great_JJ changes_NN2 in_II all_DB companies_NN2 ,_, and_CC therefore_RR there_EX is_VBZ often_RR somebody_PN1 in_II31 charge_II32 of_II33 the_AT change_NN1 process_NN1 ._. 
</s>
<s>
Antila_NN1 writes_VVZ that_CST according_II21 to_II22 the_AT study_NN1 conducted_VVD ,_, HR_NNU management_NN1 often_RR work_VV0 in_II the_AT background_NN1 ,_, consulting_VVG the_AT line_NN1 managers_NN2 on_II how_RRQ the_AT implement_NN1 the_AT actions_NN2 of_IO change_NN1 in_II the_AT organization_NN1 ._. 
</s>
<s>
However_RRQV Schuler_NP1 and_CC Jackson_NP1 argue_VV0 for_IF a_AT1 more_RGR active_JJ role_NN1 for_IF the_AT HR_NNU management_NN1 in_II leading_JJ change_NN1 ._. 
</s>
<s>
Their_APPGE point_NN1 of_IO view_NN1 is_VBZ though_CS the_AT alignment_NN1 of_IO right_JJ people_NN to_II the_AT different_JJ tasks_NN2 in_BCL21 order_BCL22 to_TO guarantee_VVI successful_JJ operations_NN2 ._. 
</s>
<s>
They_PPHS2 do_VD0 nt_XX mention_VVI about_II supervising_VVG concretely_RR the_AT operations_NN2 ,_, or_CC even_RR consulting_VVG the_AT line_NN1 managers_NN2 about_RG 3_MC ._. 
</s>
<s>
Discussion_NN1 When_CS we_PPIS2 compare_VV0 the_AT theoretical_JJ framework_NN1 to_II the_AT theory_NN1 presented_VVN by_II McKinsey_NP1 consultants_NN2 ,_, we_PPIS2 can_VM see_VVI that_CST the_AT McKinsey_NP1 concentrates_VVZ more_RRR on_II the_AT practical_JJ implementation_NN1 of_IO the_AT strategy_NN1 ._. 
</s>
<s>
In_II the_AT theory_NN1 ,_, focus_NN1 was_VBDZ laid_VVN also_RR on_II HRs_NNU2 responsibilities_NN2 and_CC roles_NN2 in_II formulating_VVG the_AT strategy_NN1 ._. 
</s>
<s>
Similarities_NN2 between_II theories_NN2 presented_VVN and_CC the_AT McKinsey_NP1 framework_NN1 are_VBR several_DA2 ._. 
</s>
<s>
A_II21 propos_II22 the_AT implementation_NN1 ,_, Antila_NP1 argues_VVZ that_CST one_MC1 of_IO the_AT most_RGT important_JJ aspects_NN2 is_VBZ integration_NN1 ._. 
</s>
<s>
In_II Antilas_NP2 work_VV0 ,_, the_AT importance_NN1 of_IO communication_NN1 as_II a_AT1 part_NN1 of_IO HR_NNU managements_NN2 responsibilities_NN2 is_VBZ also_RR highlighted_VVN ._. 
</s>
<s>
The_AT focus_NN1 on_II McKinseys_NP1 model_NN1 was_VBDZ largely_RR the_AT retention_NN1 of_IO talent_NN1 and_CC knowledge_NN1 ._. 
</s>
<s>
These_DD2 aspects_NN2 are_VBR very_RG moderately_RR ,_, if_CS at_RR21 all_RR22 ,_, discussed_VVN in_II the_AT academic_JJ studies_NN2 ._. 
</s>
<s>
This_DD1 surprises_VVZ me_PPIO1 greatly_RR ,_, given_CS21 that_CS22 it_PPH1 is_VBZ the_AT knowledge_NN1 that_CST creates_VVZ value_NN1 in_II companies_NN2 ._. 
</s>
<s>
Therefore_RR the_AT retention_NN1 of_IO talent_NN1 and_CC knowledge_NN1 should_VM be_VBI a_AT1 natural_JJ part_NN1 of_IO the_AT work_NN1 of_IO HR_NNU management_NN1 ,_, not_XX only_RR in_II international_JJ mergers_NN2 and_CC acquisitions_NN2 ,_, but_CCB in_II everything_PN1 that_CST is_VBZ done_VDN ._. 
</s>
<s>
It_PPH1 is_VBZ common_JJ in_II mergers_NN2 and_CC acquisitions_NN2 that_CST a_AT1 lot_NN1 of_IO the_AT personnel_NN2 change_VV0 ,_, as_CSA the_AT situation_NN1 change_NN1 ._. 
</s>
<s>
Therefore_RR it_PPH1 is_VBZ even_RR more_RGR crucial_JJ for_IF the_AT company_NN1 to_TO guarantee_VVI that_CST the_AT knowledge_NN1 does_VDZ nt_XX leave_VVI the_AT company_NN1 even_CS21 if_CS22 the_AT employees_NN2 do_VD0 ._. 
</s>
