<s>
Change_VV0 management_NN1 in_II post-transaction_JJ integration_NN1 processes_VVZ 1_MC1 ._. 
</s>
<s>
Introduction_NN1 Macroeconomic_NP1 developments_NN2 of_IO the_AT past_JJ decades_NNT2 have_VH0 presented_VVN new_JJ challenges_NN2 for_IF companies_NN2 at_II an_AT1 increasing_JJ rate_NN1 ._. 
</s>
<s>
Companies_NN2 are_VBR expected_VVN to_TO perform_VVI better_RRR on_II fewer_DAR resources_NN2 ._. 
</s>
<s>
Not_XX only_RR are_VBR companies_NN2 expected_VVD to_TO streamline_VVI their_APPGE organizations_NN2 and_CC production_NN1 processes_NN2 ,_, they_PPHS2 also_RR face_VV0 pressure_NN1 to_TO develop_VVI new_JJ products_NN2 while_CS increasing_JJ production_NN1 and_CC entering_VVG new_JJ markets_NN2 ._. 
</s>
<s>
Growth_NN1 is_VBZ considered_VVN a_AT1 prerequisite_NN1 for_IF competitive_JJ advantage_NN1 ._. 
</s>
<s>
Mergers_NN2 and_CC acquisitions_NN2 are_VBR sometimes_RT considered_VVN viable_JJ solutions_NN2 ._. 
</s>
<s>
Theoretically_RR ,_, they_PPHS2 can_VM offer_VVI a_AT1 rapid_JJ introduction_NN1 to_II new_JJ markets_NN2 ,_, stronger_JJR position_NN1 on_II current_JJ markets_NN2 and_CC elimination_NN1 of_IO overlapping_JJ functions_NN2 ._. 
</s>
<s>
However_RR ,_, studies_NN2 suggest_VV0 that_CST mergers_NN2 and_CC acquisitions_NN2 seldom_RR achieve_VV0 their_APPGE projected_JJ results_NN2 (_( Bennebroek_NP1 Gravenhorst_NP1 et_RA21 al._RA22 ,_, 1999_MC ;_; Porter_NP1 ,_, 1987_MC ;_; Young_NP1 ,_, 1981_MC )_) ,_, and_CC are_VBR moreoften_VV0 detrimental_JJ than_CSN profitable_JJ (_( Ravenscraft_NP1 and_CC Scherer_NP1 ,_, 1989_MC )_) ._. 
</s>
<s>
The_AT past_JJ few_DA2 decades_NNT2 has_VHZ seen_VVN a_AT1 steady_JJ rise_NN1 of_IO research_NN1 on_II mergers_NN2 and_CC acquisitions_NN2 ,_, although_CS much_DA1 of_IO it_PPH1 is_VBZ limited_VVN to_II pre-transaction_JJ phases_NN2 ._. 
</s>
<s>
This_DD1 paper_NN1 will_VM argue_VVI that_CST mergers_NN2 and_CC acquisitions_NN2 will_VM most_RGT likely_RR fail_VVI despite_II careful_JJ preparation_NN1 ,_, unless_CS the_AT post-transaction_JJ integration_NN1 process_NN1 is_VBZ properly_RR managed_VVN ._. 
</s>
<s>
This_DD1 can_VM be_VBI attributed_VVN to_II claims_NN2 that_CST academics_NN2 have_VH0 traditionally_RR neglected_VVN to_TO study_VVI how_RRQ organizations_NN2 react_VV0 when_RRQ merged_JJ (_( Datta_NP1 ,_, 1991_MC )_) ._. 
</s>
<s>
Today_RT it_PPH1 is_VBZ widely_RR recognized_VVN that_CST a_AT1 successful_JJ merger_NN1 is_VBZ the_AT result_NN1 of_IO much_DA1 more_DAR than_CSN a_AT1 well_RR chosen_VVN counterpart_NN1 ._. 
</s>
<s>
Mark_NP1 Feldman_NP1 (_( 1999_MC ,_, 2000_MC )_) ,_, who_PNQS has_VHZ conducted_VVN several_DA2 studies_NN2 on_II the_AT post-transaction_JJ integration_NN1 process_NN1 ,_, concludes_VVZ that_CST failures_NN2 can_VM often_RR be_VBI attributed_VVN to_II problems_NN2 in_II communication_NN1 and_CC structuring_NN1 ._. 
</s>
<s>
Disruptions_NN2 in_II these_DD2 factors_NN2 will_VM cause_VVI delays_NN2 ,_, prime_JJ catalysts_NN2 for_IF failure_NN1 ._. 
</s>
<s>
A_AT1 study_NN1 conducted_VVN by_II PricewaterhouseCoopers_NP1 revealed_VVD that_CST companies_NN2 running_VVG their_APPGE integration_NN1 projects_VVZ as_RG fast_RR as_CSA possible_JJ reached_VVD 80_MC percent_NNU of_IO their_APPGE goals_NN2 on_II schedule_NN1 (_( Feldman_NP1 and_CC Spratt_NP1 ,_, 1999:22_MC )_) ._. 
</s>
<s>
The_AT aim_NN1 of_IO this_DD1 paper_NN1 is_VBZ to_TO study_VVI integration_NN1 processes_NN2 as_CSA change_NN1 management_NN1 challenges_NN2 ._. 
</s>
<s>
In_II31 accordance_II32 with_II33 Birkinshaw_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2000_MC )_) ,_, this_DD1 paper_NN1 will_VM treat_VVI an_AT1 integration_NN1 project_NN1 as_II an_AT1 amalgamation_NN1 of_IO two_MC different_JJ types_NN2 of_IO integration_NN1 :_: task_NN1 integration_NN1 and_CC human_JJ integration_NN1 ._. 
</s>
<s>
Task_NN1 integration_NN1 consists_VVZ of_IO processes_NN2 that_CST integrates_VVZ the_AT functions_NN2 of_IO one_MC1 organization_NN1 into_II another_DD1 and_CC vice_RR21 versa_RR22 ,_, while_CS human_JJ integration_NN1 consists_VVZ of_IO communication-_NN1 and_CC HRM_NP1 processes_NN2 ._. 
</s>
<s>
The_AT main_JJ objective_NN1 of_IO this_DD1 paper_NN1 is_VBZ to_TO study_VVI whether_CSW there_EX are_VBR change_NN1 management_NN1 models_NN2 in_II structuring_NN1 and_CC process_VV0 planning_VVG that_CST could_VM be_VBI used_VVN in_II task_NN1 integration_NN1 ,_, and_CC which_DDQ (_( if_CS any_DD )_) change_VV0 management_NN1 models_NN2 in_II communication_NN1 and_CC HRM_NP1 could_VM be_VBI useful_JJ in_II human_JJ integration_NN1 ._. 
</s>
<s>
The_AT findings_NN2 suggest_VV0 that_CST several_DA2 integration_NN1 projects_NN2 may_VM have_VHI been_VBN conducted_VVN without_IW notable_JJ usage_NN1 of_IO change_NN1 management_NN1 models_NN2 ._. 
</s>
<s>
This_DD1 is_VBZ supported_VVN by_II studying_VVG the_AT reasons_NN2 as_II21 to_II22 why_RRQ integration_NN1 projects_NN2 tend_VV0 to_TO fail_VVI ,_, and_CC comparing_VVG them_PPHO2 to_II the_AT models_NN2 in_II this_DD1 paper_NN1 ._. 
</s>
<s>
A_AT1 central_JJ part_NN1 of_IO this_DD1 argument_NN1 will_VM be_VBI Feldmans_NP2 (_( 2000_MC )_) article_NN1 Avoiding_VVG the_AT Seven_MC Deadly_JJ Sins_NN2 of_IO Postmerger_NP1 Integration_NN1 ._. 
</s>
<s>
This_DD1 paper_NN1 is_VBZ organized_VVN into_II 4_MC parts_NN2 ,_, the_AT literature_NN1 view_NN1 starting_VVG with_IW an_AT1 introductory_JJ description_NN1 of_IO change_NN1 as_II a_AT1 conflict_NN1 situation_NN1 ._. 
</s>
<s>
This_DD1 will_VM introduce_VVI the_AT task_NN1 integration_NN1 part_NN1 of_IO the_AT paper_NN1 ,_, presenting_VVG a_AT1 process-based_JJ view_NN1 of_IO change_NN1 management_NN1 and_CC how_RRQ it_PPH1 could_VM contribute_VVI to_II a_AT1 successful_JJ integration_NN1 of_IO processes_NN2 ._. 
</s>
<s>
The_AT human_JJ integration_NN1 part_NN1 of_IO the_AT paper_NN1 will_VM discuss_VVI Elvings_NP1 (_( 2005_MC )_) model_NN1 of_IO communication_NN1 during_II a_AT1 change_NN1 project_NN1 ._. 
</s>
<s>
The_AT paper_NN1 will_VM then_RT discuss_VVI the_AT effect_NN1 these_DD2 models_NN2 may_VM have_VHI in_II an_AT1 integration_NN1 project_NN1 ,_, and_CC conclude_VV0 by_II offering_VVG guidelines_NN2 for_IF future_JJ mergers_NN2 and_CC acquisistions._NNU 2_MC ._. 
</s>
<s>
Roots_NN2 of_IO Conflict_NN1 :_: Wilfried_JJ Krgers_NN2 Iceberg_NN1 As_CSA stated_VVN earlier_RRR ,_, organizations_NN2 facing_VVG change_NN1 often_RR generate_VV0 conflict_NN1 ._. 
</s>
<s>
In_II the_AT case_NN1 of_IO mergers_NN2 ,_, conflict_NN1 does_VDZ not_XX appear_VVI exclusively_RR in_II the_AT target_NN1 organization_NN1 ,_, as_CSA changes_NN2 caused_VVN by_II the_AT deal_NN1 also_RR affect_VV0 the_AT acquirers_NN2 ._. 
</s>
<s>
Wilfried_NP1 Krgers_NP1 Iceberg_NN1 is_VBZ a_AT1 theoretical_JJ model_NN1 describing_VVG the_AT origins_NN2 of_IO conflict_NN1 within_II an_AT1 organization_NN1 ,_, divided_VVN into_II tangible_JJ (_( visible_JJ )_) and_CC intangible_JJ (_( invisible_JJ )_) groups_NN2 ._. 
</s>
<s>
This_DD1 division_NN1 is_VBZ an_AT1 important_JJ aspect_NN1 of_IO change_NN1 management_NN1 as_CSA it_PPH1 reflects_VVZ the_AT seemingly_RR chaotic_JJ nature_NN1 of_IO integration_NN1 projects_NN2 :_: As_CSA suggested_VVN in_II many_DA2 studies_NN2 (_( this_DD1 included_VVN )_) ,_, mergers_NN2 and_CC acquisitions_NN2 tend_VV0 to_TO fail_VVI because_CS managers_NN2 focus_VV0 mainly_RR on_II the_AT clearly_RR visible_JJ and_CC easily_RR monitored_VVN aspects_NN2 of_IO the_AT project_NN1 ._. 
</s>
<s>
The_AT model_NN1 depiction_NN1 of_IO this_DD1 features_VVZ an_AT1 iceberg_NN1 ,_, with_IW the_AT visible_JJ aspects_NN2 above_II the_AT surface_NN1 and_CC the_AT rest_NN1 below_RL :_: Management_NN1 tends_VVZ to_TO overlook_VVI factors_NN2 that_CST hide_VV0 under_II the_AT surface_NN1 ,_, focusing_VVG only_RR on_II the_AT visible_JJ parts_NN2 of_IO the_AT project_NN1 ._. 
</s>
<s>
These_DD2 parts_NN2 are_VBR quality_NN1 ,_, cost_NN1 and_CC time_NNT1 ,_, and_CC they_PPHS2 all_DB share_VV0 qualities_NN2 that_CST make_VV0 them_PPHO2 easy_JJ to_TO convey_VVI to_II investors_NN2 ._. 
</s>
<s>
However_RR ,_, the_AT model_NN1 represents_VVZ these_DD2 three_MC parts_NN2 as_CSA directly_RR affected_VVN by_II the_AT underlying_JJ factors_NN2 ,_, suggesting_VVG that_CST any_DD claims_NN2 as_II21 to_II22 the_AT state_NN1 of_IO the_AT organization_NN1 is_VBZ unreliable_JJ without_IW extensive_JJ knowledge_NN1 of_IO these_DD2 hidden_JJ aspects_NN2 ._. 
</s>
<s>
In_II31 addition_II32 to_II33 being_VBG difficult_JJ to_TO describe_VVI in_II reports_NN2 ,_, Management_NN1 of_IO Perceptions_NN2 and_CC Beliefs_NN2 and_CC Power_NN1 and_CC Politics_NN1 Management_NN1 are_VBR also_RR challenging_VVG to_TO manage_VVI in_II a_AT1 change_NN1 project_NN1 ._. 
</s>
<s>
Krger_NN1 suggests_VVZ that_DD1 conflict_NN1 is_VBZ significantly_RR affected_VVN by_II the_AT type_NN1 of_IO change_NN1 the_AT organization_NN1 is_VBZ facing_VVG ,_, and_CC the_AT hidden_JJ factors_NN2 play_VV0 an_AT1 intricate_JJ part_NN1 in_II shaping_VVG the_AT type_NN1 of_IO opposition_NN1 ._. 
</s>
<s>
The_AT rate_NN1 at_II which_DDQ an_AT1 organization_NN1 will_VM oppose_VVI change_NN1 correlates_VVZ with_IW how_RRQ extensively_RR the_AT project_NN1 calls_VVZ for_IF adjustment_NN1 in_II the_AT underlying_JJ factors_NN2 ._. 
</s>
<s>
The_AT model_NN1 also_RR identifies_VVZ four_MC types_NN2 of_IO actors_NN2 that_CST may_VM appear_VVI in_II an_AT1 organization_NN1 undergoing_VVG change_NN1 ,_, ranging_VVG from_II individuals_NN2 that_CST promote_VV0 change_NN1 to_II those_DD2 that_CST oppose_VV0 it_PPH1 ._. 
</s>
<s>
The_AT models_NN2 objective_NN1 in_II this_DD1 sense_NN1 is_VBZ to_TO give_VVI insight_NN1 as_II how_RRQ to_TO minimize_VVI the_AT negative_JJ effects_NN2 provided_VVN by_II these_DD2 actors_NN2 and_CC how_RRQ to_TO promote_VVI the_AT positive_JJ ones_NN2 ._. 
</s>
<s>
Opponents_NN2 view_VV0 the_AT project_NN1 in_II a_AT1 negative_JJ light_NN1 in_II31 addition_II32 to_II33 acting_VVG against_II it_PPH1 ,_, while_CS hidden_JJ opponents_NN2 will_VM go_VVI along_RP while_CS masking_VVG their_APPGE animosity_NN1 ._. 
</s>
<s>
The_AT latter_DA is_VBZ considered_VVN more_RGR dangerous_JJ than_CSN the_AT former_DA ,_, especially_RR if_CS the_AT person_NN1 in_II question_NN1 is_VBZ in_II a_AT1 position_NN1 of_IO power_NN1 ._. 
</s>
<s>
Potential_JJ promoters_NN2 do_VD0 not_XX actively_RR voice_VVI their_APPGE approval_NN1 of_IO the_AT project_NN1 ,_, although_CS they_PPHS2 do_VD0 approve_VVI of_IO it_PPH1 ,_, while_CS promoters_NN2 are_VBR seen_VVN as_II a_AT1 driving_JJ force_NN1 in_II a_AT1 change_NN1 process._NNU 3_MC ._. 
</s>
<s>
Task_NN1 Integration_NN1 :_: Change_VV0 management_NN1 in_II phases_NN2 The_AT notion_NN1 of_IO describing_VVG organizational_JJ change_NN1 as_II a_AT1 series_NN of_IO phases_NN2 is_VBZ a_AT1 relatively_RR old_JJ one_PN1 ,_, although_CS its_APPGE merits_NN2 have_VH0 not_XX been_VBN addressed_VVN in_II practice_NN1 ,_, as_CSA evidenced_VVN in_II studies_NN2 conducted_VVN on_II failed_JJ mergers_NN2 and_CC acquisitions_NN2 ._. 
</s>
<s>
The_AT number_NN1 of_IO phases_NN2 described_VVN in_II theoretical_JJ models_NN2 have_VH0 increased_VVN from_II three_MC (_( Lewin_NP1 ,_, 1947_MC )_) to_II five_MC (_( Pettigrew_NP1 &;_NULL Whipp_NP1 ,_, 1991_MC )_) and_CC then_RT eight_MC (_( Kotter_NP1 ,_, 1995_MC )_) ._. 
</s>
<s>
The_AT argument_NN1 behind_II these_DD2 theories_NN2 is_VBZ that_DD1 organizational_JJ change_NN1 is_VBZ too_RG complex_JJ to_TO effectively_RR describe_VVI in_II one_MC1 phase_NN1 ,_, although_CS one_PN1 could_VM also_RR argue_VVI that_CST it_PPH1 is_VBZ too_RG complex_JJ for_IF merely_RR eight_MC phases_NN2 ._. 
</s>
<s>
Then_RT again_RT ,_, it_PPH1 is_VBZ widely_RR accepted_VVN that_CST a_AT1 multiprocess_NN1 approach_NN1 is_VBZ beneficial_JJ as_CSA it_PPH1 demonstrates_VVZ that_DD1 change_NN1 does_VDZ not_XX happen_VVI overnight_RT ._. 
</s>
<s>
This_DD1 section_NN1 will_VM concentrate_VVI on_II Kotters_NP1 model_NN1 of_IO change_NN1 in_II eight_MC phases_NN2 after_II having_VHG a_AT1 short_JJ look_NN1 on_II the_AT three-phase_JJ model_NN1 by_II Lewin_NP1 and_CC the_AT five-phase_JJ model_NN1 by_II Pettigrew_NP1 and_CC Whipp_NP1 ._. 
</s>
<s>
One_MC1 of_IO the_AT first_MD models_NN2 describing_VVG organizational_JJ change_NN1 as_II a_AT1 series_NN of_IO phases_NN2 was_VBDZ developed_VVN by_II Kurt_NP1 Lewin_NP1 (_( 1947_MC ,_, 1951_MC ,_, 1999_MC )_) ._. 
</s>
<s>
It_PPH1 features_VVZ a_AT1 three-phase_JJ approach_NN1 ,_, which_DDQ each_DD1 phase_NN1 facing_VVG driving_JJ and_CC opposing_JJ forces_NN2 ._. 
</s>
<s>
The_AT first_MD phase_NN1 is_VBZ called_VVN unfreezing_NN1 ,_, referring_VVG to_II a_AT1 process_NN1 in_II which_DDQ existing_JJ norms_NN2 are_VBR brought_VVN into_II question_NN1 ,_, allowing_VVG (_( in_II theory_NN1 )_) a_AT1 more_RGR flexible_JJ environment_NN1 to_TO emerge_VVI ._. 
</s>
<s>
The_AT second_MD phase_NN1 involves_VVZ the_AT actual_JJ change_NN1 process_NN1 ,_, in_II which_DDQ the_AT agenda_NN1 is_VBZ realized_VVN and_CC the_AT proposed_JJ changes_NN2 executed_VVD ._. 
</s>
<s>
The_AT third_MD phase_NN1 calls_VVZ for_IF re-freezing_JJ ,_, which_DDQ translates_VVZ to_II a_AT1 process_NN1 in_II which_DDQ the_AT new_JJ changes_NN2 are_VBR solidified_VVN as_II a_AT1 part_NN1 of_IO the_AT organizational_JJ culture_NN1 ._. 
</s>
<s>
Lewin_NP1 points_VVZ out_RP that_CST each_DD1 phase_NN1 should_VM be_VBI accompanied_VVN by_II an_AT1 extensive_JJ communication_NN1 strategy_NN1 to_TO prevent_VVI any_DD uncertainly_RR and_CC misinformation_NN1 to_TO cause_VVI corrosion_NN1 to_II the_AT project_NN1 and_CC the_AT organization_NN1 ._. 
</s>
<s>
However_RR ,_, this_DD1 part_NN1 pertains_VVZ to_II the_AT human_JJ integration_NN1 part_NN1 of_IO the_AT study_NN1 and_CC will_VM therefore_RR be_VBI olaborated_VVN upon_II in_II a_AT1 later_JJR section_NN1 ._. 
</s>
<s>
In_II31 addition_II32 to_II33 its_APPGE five_MC phases_NN2 ,_, Pettigrew_NP1 &;_NULL Whipps_NP1 (_( 1991_MC )_) model_NN1 features_NN2 three_MC dimensions_NN2 which_DDQ play_VV0 an_AT1 intricate_JJ part_NN1 in_II each_DD1 phase_NN1 ._. 
</s>
<s>
First_MD ,_, we_PPIS2 have_VH0 content_JJ ,_, which_DDQ encompasses_VVZ the_AT objective_NN1 ,_, purpose_NN1 and_CC goal_NN1 of_IO the_AT phase_NN1 ._. 
</s>
<s>
Second_MD ,_, process_VV0 ,_, which_DDQ describes_VVZ how_RRQ the_AT phase_NN1 is_VBZ executed_VVN ._. 
</s>
<s>
Third_MD ,_, context_NN1 which_DDQ clarifies_VVZ which_DDQ aspects_NN2 of_IO the_AT organization_NN1 is_VBZ undergoing_VVG change_NN1 ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, the_AT dimensions_NN2 could_VM be_VBI construed_VVN as_II WHAT_DDQ ,_, HOW_RRQ and_CC WHERE_RRQ ._. 
</s>
<s>
The_AT difference_NN1 in_RP regards_VVZ to_II Lewins_NP2 and_CC Kotters_VVZ theories_NN2 is_VBZ that_CST this_DD1 model_NN1 does_VDZ not_XX necessitate_VVI a_AT1 certain_JJ sequence_NN1 in_II its_APPGE phases_NN2 ,_, but_CCB should_VM rather_RR be_VBI seen_VVN as_II a_AT1 series_NN of_IO aspects_NN2 important_JJ to_II every_AT1 change_NN1 project_NN1 ._. 
</s>
<s>
The_AT five_MC aspects_NN2 are._NNU 1_MC1 ._. 
</s>
<s>
Environmental_JJ assessment_NN1 -_- continuous_JJ monitoring_NN1 of_IO both_DB2 the_AT internal_JJ and_CC external_JJ environment_NN1 &lsqb;_( competition_NN1 &rsqb;_) of_IO the_AT organization_NN1 through_II open_JJ learning_NN1 systems_NN2 2_MC ._. 
</s>
<s>
Human_JJ resources_NN2 as_CSA assets_NN2 and_CC liabilities_NN2 -_- employees_NN2 should_VM know_VVI they_PPHS2 are_VBR seen_VVN as_CSA valuable_JJ and_CC feel_VV0 trusted_VVN by_II the_AT organization_NN1 3_MC ._. 
</s>
<s>
Linking_VVG strategic_JJ and_CC operational_JJ change_NN1 -_- Intentions_NN2 are_VBR implemented_VVN and_CC transformed_VVN through_II time_NNT1 ,_, bundling_VVG of_IO operational_JJ activities_NN2 is_VBZ powerful_JJ and_CC can_VM lead_VVI to_II new_JJ strategic_JJ changes_NN2 4_MC ._. 
</s>
<s>
Leading_JJ change_NN1 -_- Move_VV0 the_AT organization_NN1 forwards_RL ;_; creating_VVG the_AT right_JJ climate_NN1 for_IF change_NN1 ,_, coordinating_VVG activities_NN2 ,_, steering_VVG ._. 
</s>
<s>
Setting_VVG the_AT agenda_NN1 not_XX only_RR for_IF the_AT direction_NN1 of_IO the_AT change_NN1 ,_, but_CCB also_RR for_IF the_AT right_JJ vision_NN1 and_CC values_NN2 )_) 5_MC ._. 
</s>
<s>
Overall_JJ coherence_NN1 -_- a_AT1 change_NN1 strategy_NN1 should_VM be_VBI consistent_JJ (_( clear_JJ goals_NN2 )_) ,_, consonant_NN1 (_( with_IW its_APPGE environment_NN1 )_) ,_, provide_VV0 a_AT1 competitive_JJ edge_NN1 and_CC be_VBI feasible_JJ (_( Pettigrew_NP1 &;_NULL Whipp_NP1 ,_, 1991_MC ,_, copied_VVN from_II )_) 3.1_MC Kotters_NN2 model_VV0 This_DD1 model_NN1 offers_VVZ a_AT1 general_JJ view_NN1 on_II how_RRQ structures_NN2 and_CC processes_NN2 can_VM be_VBI integrated_VVN by_II following_VVG a_AT1 clear_JJ and_CC standardized_JJ strategy_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ worth_II noting_VVG that_CST every_AT1 integration_NN1 is_VBZ unique_JJ ,_, and_CC utilizing_VVG a_AT1 strategy_NN1 from_II a_AT1 previous_JJ project_NN1 in_II a_AT1 new_JJ one_PN1 is_VBZ not_XX a_AT1 guarantee_NN1 of_IO success_NN1 (_( Ashkenas_NN2 et_RA21 al_RA22 ._. 
</s>
<s>
1998_MC )_) ._. 
</s>
<s>
In_II response_NN1 ,_, this_DD1 model_NN1 does_VDZ not_XX go_VVI into_II specifics_NN2 and_CC keeps_VVZ every_AT1 guideline_NN1 vague_JJ to_TO facilitate_VVI improvisation_NN1 ._. 
</s>
<s>
Also_RR ,_, many_DA2 of_IO these_DD2 phases_NN2 are_VBR active_JJ simultaneously_RR ,_, Phase_NN1 1_MC1 :_: Create_VV0 urgency_NN1 Phase_NN1 one_PN1 is_VBZ active_JJ simultaneously_RR with_IW other_JJ phases_NN2 ,_, as_CSA it_PPH1 stresses_VVZ the_AT need_NN1 of_IO keeping_VVG and_CC organization_NN1 susceptible_JJ to_TO change_VVI throghout_VV0 the_AT whole_JJ process_NN1 ._. 
</s>
<s>
According_II21 to_II22 Kotter_NP1 ,_, it_PPH1 is_VBZ important_JJ to_TO start_VVI every_AT1 change_NN1 project_NN1 by_II developing_VVG a_AT1 base_NN1 upon_II which_DDQ the_AT rest_NN1 of_IO the_AT phases_NN2 can_VM stand_VVI on_RP ._. 
</s>
<s>
The_AT comparison_NN1 with_IW the_AT first_MD phase_NN1 in_II Lewins_NP2 model_NN1 is_VBZ apparent_JJ ,_, although_CS Kotter_NP1 stresses_VVZ the_AT necessity_NN1 of_IO maintaining_VVG it_PPH1 ._. 
</s>
<s>
The_AT need_NN1 for_IF a_AT1 new_JJ base_NN1 rests_VVZ on_II the_AT notion_NN1 that_CST complacency_NN1 is_VBZ one_MC1 of_IO the_AT prime_JJ reasons_NN2 for_IF delays_NN2 in_II organizational_JJ change_NN1 ,_, which_DDQ loosely_RR translates_VVZ to_II people_NN being_VBG unsure_JJ as_II21 to_II22 why_RRQ change_NN1 is_VBZ necessary_JJ ._. 
</s>
<s>
In_II a_AT1 worst_JJT case_NN1 scenario_NN1 ,_, the_AT project_NN1 grinds_VVZ to_II a_AT1 halt_NN1 because_CS the_AT urgency_NN1 for_IF change_NN1 was_VBDZ not_XX effectively_RR communicated_VVN ._. 
</s>
<s>
Complancency_NN1 can_VM manifest_VVI in_II an_AT1 organization_NN1 facing_VVG success_NN1 ,_, no_AT visible_JJ threats_NN2 ,_, low_JJ standards_NN2 and_CC lack_NN1 of_IO external_JJ feedback_NN1 ,_, just_RR to_TO name_VVI a_AT1 few_DA2 ,_, and_CC it_PPH1 can_VM prove_VVI detrimental_JJ to_II a_AT1 change_NN1 project_NN1 if_CS the_AT organization_NN1 does_VDZ not_XX see_VVI any_DD need_NN1 for_IF change_NN1 ._. 
</s>
<s>
Creating_VVG a_AT1 base_NN1 for_IF change_NN1 involves_VVZ instigating_VVG a_AT1 sense_NN1 of_IO urgency_NN1 ,_, fostering_VVG a_AT1 cultural_JJ shift_NN1 towards_II a_AT1 change-oriented_JJ organization_NN1 ._. 
</s>
<s>
Maintaining_VVG the_AT base_NN1 is_VBZ equally_RR important_JJ ._. 
</s>
<s>
As_II the_AT project_NN1 moves_VVZ forward_RL ,_, the_AT organization_NN1 faces_VVZ a_AT1 constant_JJ threat_NN1 of_IO a_AT1 relapse_NN1 to_II complacency_NN1 which_DDQ is_VBZ why_RRQ phase_NN1 one_PN1 encompasses_VVZ the_AT entire_JJ duration_NN1 ._. 
</s>
<s>
In_II fact_NN1 ,_, maintaining_VVG some_DD phase_NN1 one_MC1 operations_VVZ even_RR after_II the_AT project_NN1 is_VBZ finished_VVN is_VBZ not_XX unheard_JJ of_IO as_CSA Kotter_NP1 suggests_VVZ that_CST complete_VV0 cultural_JJ integration_NN1 can_VM remain_VVI elusive_JJ decades_NNT2 after_CS financially_RR acceptable_JJ integration_NN1 has_VHZ been_VBN achieved_VVN (_( Kotter_NP1 ,_, 1995_MC )_) Phase_NN1 2_MC :_: Form_VV0 a_AT1 powerful_JJ coalition_NN1 Kotter_NN1 suggests_VVZ that_CST a_AT1 small_JJ group_NN1 led_VVN by_II a_AT1 change_NN1 leader_NN1 is_VBZ the_AT most_RGT effective_JJ in_II representing_VVG the_AT new_JJ organization_NN1 and_CC leading_VVG the_AT change_NN1 process_NN1 ._. 
</s>
<s>
This_DD1 group_NN1 should_VM be_VBI empowered_VVN in_BCL21 order_BCL22 to_TO perform_VVI effectively_RR and_CC have_VHI means_NN of_IO communicating_VVG with_IW the_AT entire_JJ organization_NN1 ._. 
</s>
<s>
This_DD1 part_NN1 is_VBZ critical_JJ and_CC often_RR neglected_VVN ,_, leaving_VVG the_AT coalition_NN1 inefficient_JJ in_II its_APPGE duty_NN1 ._. 
</s>
<s>
Ashkenas_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 1998_MC )_) shares_VVZ this_DD1 view_NN1 ,_, pointing_VVG out_RP that_CST leading_VVG a_AT1 change_NN1 project_NN1 is_VBZ a_AT1 full-time_JJ job_NN1 ._. 
</s>
<s>
Kotter_NN1 goes_VVZ on_RP to_TO point_VVI out_RP the_AT importance_NN1 of_IO including_VVG managers_NN2 from_II day-to_NNT1 day_NNT1 operations_NN2 in_II the_AT coalition_NN1 ,_, a_AT1 view_NN1 supported_VVN by_II Pettigrew_NP1 and_CC Whipp_NP1 (_( 1991_MC )_) in_II the_AT third_MD factor_NN1 of_IO their_APPGE model_NN1 (_( the_AT link_NN1 between_II strategic_JJ and_CC operative_JJ change_NN1 )_) Phases_NN2 3_MC and_CC 4_MC :_: Create_VV0 and_CC communicate_VV0 a_AT1 vision_NN1 of_IO change_NN1 The_AT benefits_NN2 of_IO urgency_NN1 and_CC coalitions_NN2 can_VM not_XX be_VBI realized_VVN without_IW a_AT1 effectively_RR communicated_VVN common_JJ vision_NN1 ._. 
</s>
<s>
Along_II21 with_II22 phases_NN2 1_MC1 ,_, 2_MC and_CC 5_MC ,_, it_PPH1 is_VBZ important_JJ to_TO start_VVI working_VVG on_II a_AT1 vision_NN1 and_CC the_AT means_NN of_IO communicating_VVG it_PPH1 early_RR on_RP ._. 
</s>
<s>
A_AT1 well_NN1 designed_VVD vision_NN1 is_VBZ ineffective_JJ when_CS not_XX communicated_VVN properly_RR to_II the_AT organization_NN1 ._. 
</s>
<s>
Kotter_NP1 (_( 1995_MC )_) and_CC Elving_NP1 (_( 2005_MC )_) both_DB2 stress_VV0 the_AT importance_NN1 of_IO communication_NN1 as_II a_AT1 tool_NN1 for_IF relaying_VVG information_NN1 and_CC creating_VVG common_JJ ground_NN1 ._. 
</s>
<s>
Kotter_NN1 mentions_VVZ three_MC instances_NN2 when_RRQ a_AT1 coalition_NN1 is_VBZ ineffective_JJ in_II communicating_VVG the_AT projects_NN2 vision_NN1 ._. 
</s>
<s>
In_II the_AT first_MD example_NN1 the_AT group_NN1 uses_VVZ more_DAR time_NNT1 formulating_VVG the_AT vision_NN1 than_CSN communicating_VVG it_PPH1 ._. 
</s>
<s>
In_II most_DAT cases_NN2 the_AT vision_NN1 is_VBZ communicated_VVN only_RR through_II a_AT1 few_DA2 meetings_NN2 and_CC a_AT1 memo_NN1 ,_, a_AT1 method_NN1 deemed_VVN inefficient_JJ as_CSA it_PPH1 should_VM only_RR encompass_VVI a_AT1 fraction_NN1 of_IO the_AT communication_NN1 during_II integration_NN1 ._. 
</s>
<s>
In_II the_AT second_MD example_NN1 the_AT responsibility_NN1 for_IF communication_NN1 is_VBZ borne_VVN only_RR by_II the_AT project_NN1 leader_NN1 ,_, while_CS it_PPH1 should_VM involve_VVI all_DB managers_NN2 ._. 
</s>
<s>
In_II his_APPGE third_MD example_NN1 ,_, Kotter_NP1 describes_VVZ a_AT1 well_NN1 communicated_VVD vision_NN1 which_DDQ unfortunately_RR is_VBZ not_XX acted_VVN upon_II by_II managers_NN2 ._. 
</s>
<s>
Feldman_NP1 (_( 1995_MC )_) and_CC Kotter_VV0 both_RR suggest_VV0 that_CST the_AT best_JJT results_NN2 in_II communicating_VVG a_AT1 new_JJ vision_NN1 can_VM be_VBI achieved_VVN when_CS managers_NN2 demonstrate_VV0 that_CST they_PPHS2 are_VBR not_XX above_RL it_PPH1 ._. 
</s>
<s>
Phase_NN1 5_MC :_: Remove_VV0 obstacles_NN2 This_DD1 phase_NN1 is_VBZ mainly_RR a_AT1 continuation_NN1 to_II phase_NN1 2_MC and_CC it_PPH1 involves_VVZ empowering_VVG the_AT coalition_NN1 ,_, allowing_VVG them_PPHO2 to_TO remove_VVI any_DD obstacles_NN2 that_CST may_VM prevent_VVI the_AT project_NN1 from_II being_VBG realized_VVN ._. 
</s>
<s>
Phase_NN1 6_MC :_: Create_VV0 short-term_JJ wins_NN2 Kotter_VV0 credits_NN2 short-term_JJ wins_NN2 as_CSA they_PPHS2 are_VBR effective_JJ in_II demonstrating_VVG that_CST the_AT project_NN1 is_VBZ moving_VVG forward_RL and_CC preventing_VVG stagnation_NN1 ._. 
</s>
<s>
Without_IW short-term_JJ wins_NN2 ,_, hidden_JJ opponents_NN2 may_VM become_VVI opponents_NN2 as_CSA per_II Krgers_NP1 model_NN1 ._. 
</s>
<s>
Kotter_NN1 mentions_VVZ 6_MC factors_NN2 that_CST describe_VV0 the_AT merits_NN2 of_IO short-term_JJ wins_NN2 :_: 1_MC1 ._. 
</s>
<s>
They_PPHS2 demonstrate_VV0 that_CST the_AT project_NN1 is_VBZ worth_II the_AT short-term_NN1 sacrifices_VVZ it_PPH1 requires_VVZ 2_MC ._. 
</s>
<s>
They_PPHS2 function_VV0 as_RG positive_JJ feedback_NN1 for_IF the_AT core_NN1 group_NN1 3_MC ._. 
</s>
<s>
Short-term_JJ wins_NN2 are_VBR a_AT1 good_JJ indicator_NN1 for_IF areas_NN2 that_CST need_VV0 improvement_NN1 4._MC and_CC 5_MC ._. 
</s>
<s>
They_PPHS2 are_VBR effective_JJ data_NN for_IF reports_NN2 to_II investors_NN2 and_CC executives_NN2 ,_, who_PNQS may_VM or_CC may_VM not_XX be_VBI sceptical_JJ in_RP regards_VVZ to_II the_AT project_NN1 6_MC ._. 
</s>
<s>
The_AT sixth_MD factor_NN1 is_VBZ best_RRT described_VVN in_II31 terms_II32 of_II33 the_AT Iceberg_NN1 model_NN1 ,_, as_CSA it_PPH1 mentions_VVZ the_AT effect_NN1 of_IO short-term_JJ wins_NN2 on_II members_NN2 of_IO the_AT organization_NN1 ._. 
</s>
<s>
Progress_NN1 has_VHZ the_AT effect_NN1 of_IO transforming_VVG potential_JJ promoters_NN2 to_II promoters_NN2 and_CC opponents_NN2 to_II potential_JJ promoters_NN2 ._. 
</s>
<s>
Phase_NN1 7_MC :_: Build_VV0 on_II change_NN1 Kotter_NN1 warns_VVZ against_II declaring_VVG triumph_NN1 too_RG early_RR ,_, which_DDQ is_VBZ a_AT1 common_JJ mistake_NN1 ,_, mainly_RR because_CS it_PPH1 quickly_RR generates_VVZ complacency_NN1 ._. 
</s>
<s>
Management_NN1 may_VM find_VVI themselves_PPX2 tempted_VVN to_TO declare_VVI the_AT project_NN1 successful_JJ because_II21 of_II22 short-term_JJ wins_NN2 ._. 
</s>
<s>
This_DD1 in_II turn_NN1 highlights_VVZ the_AT importance_NN1 of_IO a_AT1 well_NN1 formulated_VVN and_CC communicated_VVN vision_NN1 that_CST allows_VVZ the_AT project_NN1 to_TO proceed_VVI at_II the_AT required_JJ fast_JJ pace_NN1 ._. 
</s>
<s>
Phase_NN1 8_MC :_: Anchor_VV0 the_AT Changes_NN2 in_II Corporate_JJ Culture_NN1 Organizational_JJ culture_NN1 is_VBZ slow_JJ to_TO change_VVI ,_, which_DDQ may_VM cause_VVI this_DD1 phase_NN1 to_TO continue_VVI long_RR after_II the_AT project_NN1 has_VHZ officially_RR finished_VVN ._. 
</s>
<s>
However_RR ,_, if_CS the_AT new_JJ changes_NN2 are_VBR not_XX anchored_VVN in_II culture_NN1 ,_, the_AT organization_NN1 risks_NN2 eventually_RR returning_VVG to_II an_AT1 earlier_JJR state_NN1 ._. 
</s>
<s>
Kotter_NN1 suggests_VVZ that_CST the_AT changes_NN2 are_VBR best_RRT rooted_VVN in_II the_AT organizational_JJ culture_NN1 by_II recruiting_VVG new_JJ people_NN in_II key_JJ positions_NN2 and_CC indoctrinating_VVG them_PPHO2 into_II the_AT new_JJ culture_NN1 through_II mentoring_VVG programs._NNU 4_MC ._. 
</s>
<s>
Human_JJ Integration_NN1 :_: Elvings_NP1 Model_NN1 Elving_NP1 describes_VVZ communication_NN1 as_II having_VHG two_MC roles_NN2 in_II organizational_JJ change_NN1 ;_; communication_NN1 has_VHZ to_TO inform_VVI and_CC create_VVI unity_NN1 during_II an_AT1 change_NN1 process_NN1 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, the_AT model_NN1 takes_VVZ into_II account_NN1 the_AT organizations_NN2 readiness_NN1 to_TO change_VVI ._. 
</s>
<s>
The_AT model_NN1 is_VBZ described_VVN on_II the_AT basis_NN1 of_IO six_MC statements_NN2 considered_VVD important_JJ in_II planning_VVG a_AT1 communication_NN1 strategy_NN1 ,_, which_DDQ in_II turn_NN1 helps_VVZ the_AT change_NN1 project_VVI itself_PPX1 ._. 
</s>
<s>
These_DD2 statements_NN2 also_RR function_VV0 as_CSA suggestion_NN1 for_IF further_JJR research_NN1 in_II organizational_JJ communication._NNU 1_MC1 ._. 
</s>
<s>
An_AT1 effective_JJ change_NN1 process_NN1 has_VHZ little_RR or_CC no_AT opposition_NN1 ,_, and/or_CC a_AT1 workforce_NN1 willing_JJ to_TO change_VVI 2_MC ._. 
</s>
<s>
One_MC1 of_IO the_AT prime_JJ objectives_NN2 of_IO communication_NN1 is_VBZ to_TO inform_VVI the_AT members_NN2 of_IO the_AT organization_NN1 about_II the_AT project_NN1 and_CC how_RRQ it_PPH1 affects_VVZ them_PPHO2 ._. 
</s>
<s>
This_DD1 will_VM have_VHI a_AT1 direct_JJ effect_NN1 on_II the_AT organizations_NN2 readiness_NN1 to_II change._NNU 3_MC ._. 
</s>
<s>
Communication_NN1 fosters_VVZ unity_NN1 ,_, which_DDQ in_II turn_NN1 creates_VVZ a_AT1 commitment_NN1 towards_II the_AT organization_NN1 and_CC its_APPGE management_NN1 4_MC ._. 
</s>
<s>
Uncertainty_NN1 has_VHZ a_AT1 negative_JJ effect_NN1 on_II an_AT1 organizations_NN2 ability_NN1 to_TO change_VVI 5_MC ._. 
</s>
<s>
Uncertainty_NN1 has_VHZ a_AT1 significant_JJ effect_NN1 on_II the_AT organizations_NN2 ability_NN1 to_TO change_VVI when_RRQ the_AT process_NN1 involves_VVZ streamlining_VVG and_CC the_AT loss_NN1 of_IO jobs_NN2 6_MC ._. 
</s>
<s>
Communication_NN1 has_VHZ an_AT1 effect_NN1 on_II uncertainty_NN1 regarding_II the_AT organization_NN1 itself_PPX1 and_CC the_AT future_NN1 of_IO jobs_NN2 ._. 
</s>
<s>
Communication_NN1 in_II change_NN1 projects_NN2 is_VBZ mainly_RR connected_VVN to_II the_AT role_NN1 of_IO mitigating_JJ uncertainty_NN1 ._. 
</s>
<s>
If_CS not_XX addressed_VVN properly_RR ,_, uncertainly_RR will_VM spawn_VVI rumors_NN2 and_CC false_JJ truths_NN2 which_DDQ may_VM have_VHI a_AT1 detrimental_JJ effect_NN1 on_II the_AT project_NN1 ._. 
</s>
<s>
Kotter_NP1 (_( 1995_MC )_) and_CC Feldman_NP1 &;_NULL Spratt_NP1 (_( 1999_MC )_) all_DB point_VV0 out_RP that_DD1 communication_NN1 should_VM work_VVI both_DB2 ways_NN2 ,_, and_CC not_XX merely_RR function_VV0 as_II an_AT1 information_NN1 outlet_NN1 ._. 
</s>
<s>
DeGreene_NP1 (_( 1982_MC )_) mentions_VVZ several_DA2 downsides_NN2 to_II a_AT1 one-way_JJ communication_NN1 strategy_NN1 ,_, ranging_VVG from_II the_AT effects_NN2 of_IO erroneous_JJ information_NN1 to_II gaps_NN2 in_II the_AT information_NN1 chain._NNU 5_MC ._. 
</s>
<s>
Discussion_NN1 :_: Integration_NN1 and_CC conflicts_NN2 After_II comparing_VVG the_AT theories_NN2 in_II the_AT task_NN1 integration_NN1 part_NN1 of_IO the_AT literature_NN1 review_NN1 with_IW the_AT most_RGT common_JJ mistakes_NN2 in_II change_NN1 projects_NN2 according_II21 to_II22 Feldman_NP1 (_( list_NN1 found_VVN at_II http_NNU :_: )_) ,_, I_PPIS1 will_VM suggest_VVI that_CST several_DA2 integrations_NN2 are_VBR attempted_VVN without_IW knowledge_NN1 of_IO process-based_JJ change_NN1 management_NN1 models_NN2 ._. 
</s>
<s>
Managers_NN2 seem_VV0 to_TO overwhelm_VVI themselves_PPX2 with_IW information_NN1 ,_, create_VV0 rigid_JJ organizations_NN2 that_CST are_VBR not_XX suitable_JJ for_IF rapid_JJ change_NN1 ,_, get_VV0 marred_VVN in_II cultural_JJ difficulties_NN2 and_CC neglect_VV0 developing_VVG a_AT1 functioning_JJ communication_NN1 strategy_NN1 ._. 
</s>
<s>
All_DB of_IO these_DD2 factors_NN2 may_VM cause_VVI delays_NN2 the_AT the_AT project_NN1 ,_, which_DDQ Kotter_NP1 (_( 1995_MC )_) and_CC Feldman_NP1 (_( 2000_MC )_) describe_VV0 as_II a_AT1 prime_JJ reason_NN1 for_IF complication_NN1 ._. 
</s>
<s>
I_PPIS1 will_VM not_XX swear_VVI to_II the_AT infallibility_NN1 of_IO the_AT models_NN2 ,_, but_CCB the_AT sheer_JJ volume_NN1 of_IO failed_JJ mergers_NN2 contra_NN1 the_AT popularity_NN1 of_IO the_AT theories_NN2 I_PPIS1 have_VH0 chosen_VVN suggest_VV0 a_AT1 correlation_NN1 ._. 
</s>
<s>
The_AT main_JJ objective_NN1 of_IO this_DD1 paper_NN1 was_VBDZ to_TO determine_VVI whether_CSW the_AT high_JJ failure_NN1 rate_NN1 of_IO mergers_NN2 and_CC acquisitions_NN2 could_VM be_VBI mitigated_VVN if_CS managers_NN2 were_VBDR better_RRR versed_VVN in_II change_NN1 management_NN1 theory_NN1 ._. 
</s>
<s>
Corporate_JJ management_NN1 being_VBG a_AT1 broad_JJ subject_NN1 ,_, of_IO which_DDQ integration_NN1 projects_NN2 are_VBR but_CCB a_AT1 small_JJ (_( although_CS increasingly_RR important_JJ )_) part_NN1 ,_, the_AT difficulties_NN2 many_DA2 companies_NN2 face_VV0 in_II integrations_NN2 suggest_VV0 that_CST managers_NN2 are_VBR not_XX familiar_JJ on_II how_RRQ to_TO lead_VVI organizations_NN2 in_II change_NN1 ._. 
</s>
<s>
Ashkenas_NP1 et_RA21 al_RA22 (_( 1998_MC )_) suggest_VV0 that_CST a_AT1 reason_NN1 behind_II this_DD1 may_VM be_VBI the_AT fact_NN1 that_CST few_DA2 organizations_NN2 face_VV0 a_AT1 merger_NN1 more_DAR than_CSN once_RR ._. 
</s>
<s>
In_II fact_NN1 ,_, during_II the_AT research_NN1 process_NN1 ,_, I_PPIS1 seldom_RR ran_VVD into_II an_AT1 article_NN1 that_CST discussed_VVD integrations_NN2 and_CC change_VV0 management_NN1 ._. 
</s>
<s>
Kotter_VV0 ,_, Burke_NP1 and_CC Litwin_NP1 and_CC Elving_VVG only_RR mention_VV0 smaller_JJR change_NN1 projects_NN2 ,_, not_XX integrations_NN2 ,_, which_DDQ is_VBZ surprising_JJ considering_II the_AT financial_JJ expectations_NN2 and_CC impact_NN1 a_AT1 large-scale_JJ integration_NN1 project_NN1 can_VM have_VHI on_II an_AT1 organization_NN1 ,_, especially_RR considering_II the_AT high_JJ risk_NN1 involved_VVN (_( Feldman_NP1 and_CC Spratt_NP1 ,_, 1999_MC )_) ._. 
</s>
<s>
One_MC1 reason_NN1 for_IF this_DD1 may_VM be_VBI found_VVN by_II having_VHG a_AT1 closer_JJR look_NN1 at_II the_AT first_MD phases_NN2 of_IO an_AT1 integration_NN1 ,_, including_II the_AT ones_NN2 pre-deal_NN1 ._. 
</s>
<s>
A_AT1 study_NN1 by_II Datta_NP1 (_( 1991_MC )_) suggests_VVZ that_CST organizations_NN2 are_VBR more_RGR interested_JJ in_II research_NN1 on_II pre-deal_JJ phases_NN2 ,_, which_DDQ include_VV0 extensive_JJ due_JJ diligence_NN1 processes_NN2 ,_, which_DDQ by_II themselves_PPX2 are_VBR draining_VVG both_RR in_II31 terms_II32 of_II33 resources_NN2 and_CC psychologically_RR ._. 
</s>
<s>
After_CS these_DD2 phases_NN2 are_VBR complete_JJ and_CC the_AT deal_NN1 signed_VVD ,_, many_DA2 organizations_NN2 expect_VV0 the_AT integration_NN1 to_TO happen_VVI by_II itself_PPX1 ._. 
</s>
<s>
In_II fact_NN1 ,_, when_CS the_AT deal_NN1 is_VBZ signed_VVN ,_, the_AT due_JJ diligence_NN1 managers_NN2 ,_, who_PNQS have_VH0 become_VVN experts_NN2 on_II the_AT newly_RR acquired_VVN organization_NN1 ,_, are_VBR sent_VVN away_RL to_II new_JJ similar_JJ projects_NN2 (_( Ashkenas_NN2 et_RA21 al_RA22 ,_, 1998_MC )_) ._. 
</s>
<s>
If_CS managers_NN2 were_VBDR to_TO follow_VVI theoretical_JJ guidelines_NN2 from_II change_NN1 management_NN1 litetature_NN1 ,_, they_PPHS2 would_VM include_VVI at_RR21 least_RR22 a_AT1 few_DA2 of_IO these_DD2 experts_NN2 in_II the_AT integration_NN1 project_NN1 (_( the_AT powerful_JJ coalition_NN1 as_CSA described_VVN in_II Kotters_NP1 model_NN1 )_) ._. 
</s>
<s>
These_DD2 experts_NN2 will_VM have_VHI better_JJR knowledge_NN1 at_II identifying_VVG the_AT causes_NN2 and_CC effects_NN2 of_IO conflict_NN1 ._. 
</s>
<s>
As_CSA stated_VVN in_II the_AT literature_NN1 review_NN1 ,_, a_AT1 high_JJ rate_NN1 of_IO integration_NN1 will_VM most_RGT likely_RR cause_VVI a_AT1 high_JJ level_NN1 of_IO opposition_NN1 along_II21 with_II22 the_AT occasional_JJ support_NN1 ,_, embodied_VVN by_II the_AT four_MC types_NN2 of_IO actors_NN2 identified_VVN in_II Krgers_NP1 model_NN1 ._. 
</s>
<s>
Feldman_NP1 and_CC Spratts_NP2 (_( 1999_MC )_) notion_NN1 that_CST conflict_NN1 arises_VVZ from_II uncertainty_NN1 rather_CS21 than_CS22 change_VVI itself_PPX1 combined_VVN with_IW with_IW the_AT theoretical_JJ framework_NN1 provided_VVN by_II Krgers_NP1 model_NN1 could_VM by_II itself_PPX1 be_VBI a_AT1 powerful_JJ tool_NN1 for_IF change_NN1 leaders_NN2 ,_, but_CCB evidently_RR many_DA2 integrations_NN2 are_VBR still_RR managed_VVN poorly_RR ._. 
</s>
<s>
As_CSA uncertainty_NN1 has_VHZ a_AT1 negative_JJ effect_NN1 on_II the_AT task_NN1 integration_NN1 part_NN1 of_IO the_AT project_NN1 ,_, one_PN1 could_VM therefore_RR speculate_VVI that_DD1 human_JJ integration_NN1 does_VDZ not_XX receive_VVI enough_DD attention_NN1 ._. 
</s>
<s>
Disruptions_NN2 in_II task_NN1 integration_NN1 has_VHZ been_VBN a_AT1 common_JJ theme_NN1 throughout_II this_DD1 paper_NN1 ,_, with_IW change_NN1 projects_NN2 failing_VVG at_II achieveing_VVG their_APPGE goals_NN2 due_II21 to_II22 unexpected_JJ delays_NN2 and_CC conflict_NN1 ._. 
</s>
<s>
Elvings_NP1 studies_NN2 on_II creating_VVG unity_NN1 by_II using_VVG a_AT1 communication_NN1 strategy_NN1 mirrors_NN2 the_AT observations_NN2 that_CST led_VVD Birkinshaw_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2000_MC )_) to_TO identify_VVI human_JJ integration_NN1 as_II an_AT1 important_JJ part_NN1 of_IO an_AT1 integration_NN1 project_NN1 ._. 
</s>
<s>
Human_JJ integration_NN1 and_CC communication_NN1 could_VM almost_RR be_VBI seen_VVN as_CSA synonymous_JJ in_II this_DD1 instance_NN1 ,_, which_DDQ solidifies_VVZ Elvings_NP1 model_NN1 as_CSA one_MC1 of_IO the_AT cornerstones_NN2 of_IO human_JJ integration_NN1 ._. 
</s>
<s>
I_PPIS1 have_VH0 noticed_VVN a_AT1 pattern_NN1 when_CS studying_VVG articles_NN2 on_II communication_NN1 in_II organizational_JJ change_NN1 :_: as_CSA management_NN1 contemplates_VVZ on_II what_DDQ information_NN1 they_PPHS2 want_VV0 to_TO convey_VVI in_RP regards_VVZ to_II the_AT change_NN1 process_NN1 ,_, they_PPHS2 often_RR neglect_VV0 the_AT most_RGT common_JJ questions_NN2 ._. 
</s>
<s>
These_DD2 questions_NN2 are_VBR often_RR of_IO a_AT1 simple_JJ nature_NN1 regarding_II the_AT future_NN1 of_IO jobs_NN2 ,_, compensation_NN1 and_CC benefits_NN2 ,_, while_CS only_RR a_AT1 small_JJ percentage_NN1 of_IO the_AT workforce_NN1 is_VBZ interested_JJ in_II the_AT vision_NN1 (_( Feldman_NP1 &;_NULL Spratt_NP1 ,_, 1999_MC )_) (_( Elving_NP1 ,_, 2005_MC )_) (_( Ashkenas_NN2 et_RA21 al._RA22 ,_, 1998_MC )_) ._. 
</s>
<s>
This_DD1 brings_VVZ into_II question_NN1 the_AT importance_NN1 of_IO certain_JJ parts_NN2 in_II Kotters_NP1 model_NN1 that_CST stress_VV0 the_AT importance_NN1 of_IO a_AT1 well_NN1 communicated_VVD vision_NN1 ._. 
</s>
<s>
Elvings_NP1 model_NN1 has_VHZ its_APPGE weakness_NN1 too_RR ,_, as_CSA it_PPH1 only_RR describes_VVZ communication_NN1 within_II the_AT organization_NN1 ,_, while_CS Feldman_NP1 (_( 1999_MC )_) stresses_VVZ the_AT importance_NN1 of_IO external_JJ communication_NN1 ._. 
</s>
<s>
This_DD1 translates_VVZ to_II keeping_VVG clients_NN2 and_CC investors_NN2 informed_VVN on_II the_AT project_NN1 ,_, as_CSA integrations_NN2 are_VBR potentially_RR high-cost_JJ and_CC high-risk_JJ investments_NN2 ._. 
</s>
<s>
This_DD1 leads_VVZ us_PPIO2 to_II external_JJ threats_NN2 to_II an_AT1 integration_NN1 ,_, which_DDQ is_VBZ an_AT1 aspect_NN1 not_XX touched_VVN upon_II in_II this_DD1 paper_NN1 ._. 
</s>
<s>
Unfortunately_RR ,_, it_PPH1 will_VM have_VHI to_TO be_VBI included_VVN in_II another_DD1 study_NN1 ,_, as_CSA various_JJ restrictions_NN2 prevent_VV0 me_PPIO1 from_II addressing_VVG it_PPH1 here._NNU 6_MC ._. 
</s>
<s>
Conclusions_NN2 ,_, and_CC limitations_NN2 and_CC suggestions_NN2 As_II the_AT market_NN1 sees_VVZ a_AT1 steady_JJ rise_NN1 in_II mergers_NN2 and_CC acquisitions_NN2 ,_, Ashkenas_NN2 et_RA21 al_RA22 (_( 1998_MC )_) point_VV0 out_RP that_CST only_RR a_AT1 few_DA2 corporations_NN2 have_VH0 prior_JJ experience_NN1 of_IO an_AT1 integration_NN1 project_NN1 ._. 
</s>
<s>
As_CSA I_PPIS1 have_VH0 argued_VVN in_II this_DD1 study_NN1 ,_, many_DA2 of_IO the_AT failed_JJ integrations_NN2 could_VM have_VHI been_VBN redeemed_VVN if_CS the_AT managers_NN2 were_VBDR familiar_JJ with_IW change_NN1 management_NN1 theory_NN1 ,_, dividing_VVG the_AT project_NN1 into_II task-_NN1 and_CC human_JJ integration_NN1 ,_, devising_VVG a_AT1 fast_JJ and_CC efficient_JJ strategy_NN1 and_CC not_XX shirking_VVG communication_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ worth_II noting_VVG that_CST none_PN of_IO the_AT change_NN1 management_NN1 models_NN2 claim_VV0 complete_JJ applicability_NN1 to_II such_DA large-scale_JJ change_NN1 projects_NN2 as_CSA integrations_NN2 ._. 
</s>
<s>
Furthermore_RR ,_, This_DD1 study_NN1 is_VBZ limited_VVN to_II describing_VVG internal_JJ threats_NN2 to_II organizational_JJ change_NN1 ._. 
</s>
<s>
An_AT1 organization_NN1 is_VBZ vulnerable_JJ during_II any_DD large-scale_JJ project_NN1 ,_, integration_NN1 being_VBG no_AT exception_NN1 ._. 
</s>
<s>
Therefore_RR ,_, it_PPH1 is_VBZ worth_II noting_VVG that_CST managers_NN2 should_VM prepare_VVI for_IF external_JJ disruptions_NN2 to_II the_AT process_NN1 ,_, and_CC that_CST a_AT1 study_NN1 on_II that_DD1 subject_NN1 could_VM easily_RR equal_JJ this_DD1 paper_NN1 in_II lenght_NN1 ._. 
</s>
<s>
A_AT1 prevalent_JJ limitation_NN1 in_II this_DD1 study_NN1 is_VBZ its_APPGE lack_NN1 of_IO an_AT1 empirical_JJ study_NN1 ._. 
</s>
<s>
Although_CS it_PPH1 is_VBZ possible_JJ to_TO form_VVI some_DD assumptions_NN2 based_VVN on_II existing_JJ data_NN on_II failed_JJ mergers_NN2 and_CC studies_NN2 conducted_VVN by_II others_NN2 in_II31 regard_II32 to_II33 main_JJ reasons_NN2 for_IF those_DD2 failures_NN2 ,_, one_PN1 should_VM still_RR treat_VVI this_DD1 paper_NN1 as_II a_AT1 suggestion_NN1 for_IF further_JJR study_NN1 rather_II21 than_II22 a_AT1 full-fledged_JJ study_NN1 by_II itself_PPX1 ._. 
</s>
<s>
As_CSA stated_VVN earlier_RRR ,_, the_AT theoretical_JJ models_NN2 described_VVN in_II this_DD1 study_NN1 are_VBR mainly_RR aimed_VVN towards_II smaller_JJR scale_NN1 change_NN1 projects_NN2 ._. 
</s>
<s>
Furthermore_RR ,_, as_CSA most_DAT studies_NN2 on_II integrations_NN2 are_VBR conducted_VVN in_II the_AT United_NP1 States_NP1 ,_, their_APPGE applicability_NN1 on_II a_AT1 global_JJ scale_NN1 is_VBZ brought_VVN into_II question_NN1 ._. 
</s>
<s>
A_AT1 extensive_JJ study_NN1 on_II the_AT applicability_NN1 of_IO traditional_JJ change_NN1 management_NN1 theories_NN2 in_II large-scale_JJ integrations_NN2 on_II a_AT1 global_JJ scale_NN1 could_VM be_VBI beneficial_JJ to_II both_DB2 the_AT academic_JJ community_NN1 and_CC organizations_NN2 ._. 
</s>
