<s>
Fundamental_JJ indexation_NN1 in_II the_AT framework_NN1 of_IO modern_JJ finance_NN1 theory_NN1 1_MC1 ._. 
</s>
<s>
Introduction_NN1 One_MC1 of_IO the_AT last_MD bastions_NN2 of_IO capital_NN1 asset_NN1 equilibrium_NN1 based_VVN finance_NN1 is_VBZ the_AT school_NN1 of_IO passive_JJ ,_, indexed_VVD investing_JJ ._. 
</s>
<s>
This_DD1 simple_JJ and_CC elegant_JJ strategy_NN1 relies_VVZ on_II the_AT notion_NN1 that_CST buying_NN1 and_CC holding_VVG the_AT market_NN1 portfolio_NN1 is_VBZ a_AT1 superior_JJ investment_NN1 alternative_NN1 for_IF an_AT1 average_JJ investor_NN1 ._. 
</s>
<s>
Indexation_NN1 as_II an_AT1 investment_NN1 strategy_NN1 has_VHZ not_XX lost_VVN its_APPGE appeal_NN1 even_RR as_CSA the_AT foundations_NN2 of_IO efficient_JJ market_NN1 hypothesis_NN1 have_VH0 crumbled_VVN in_II academia_NN1 and_CC among_II practitioners_NN2 ._. 
</s>
<s>
On_II the_AT contrary_NN1 ,_, indexed_VVD investing_JJ has_VHZ grown_VVN in_II popularity_NN1 in_II recent_JJ years_NNT2 as_RG more_RGR private_JJ and_CC institutional_JJ funds_NN2 are_VBR moved_VVN to_II different_JJ indexed_JJ investment_NN1 vehicles_NN2 ,_, such_II21 as_II22 index_NN1 mutual_JJ funds_NN2 and_CC exchange_NN1 traded_VVD funds_NN2 (_( ETFs_NP2 )_) ._. 
</s>
<s>
According_II21 to_II22 Investment_NN1 Company_NN1 Institute_NN1 (_( 2010_MC )_) ,_, in_II the_AT United_NP1 States_NP1 alone_RR ,_, net_JJ assets_NN2 invested_VVN in_II index_NN1 funds_NN2 totaled_VVD $837_NNU billion_NNO in_II 2009_MC and_CC index_NN1 funds_NN2 share_NN1 of_IO equity_NN1 mutual_JJ fund_NN1 total_JJ net_JJ assets_NN2 have_VH0 risen_VVN from_II 4.0_MC per_NNU21 cent_NNU22 in_II 1995_MC to_II 13.7_MC per_NNU21 cent_NNU22 in_II 2009_MC ._. 
</s>
<s>
The_AT beauty_NN1 of_IO indexed_JJ investing_JJ lies_NN2 in_II its_APPGE conceptual_JJ simplicity_NN1 and_CC compliance_NN1 with_IW classical_JJ finance_NN1 theory_NN1 as_II31 well_II32 as_II33 its_APPGE characteristic_JJ low-cost_JJ portfolio_NN1 construction_NN1 ._. 
</s>
<s>
In_II a_AT1 2005_MC article_NN1 "_" Fundamental_JJ Indexation_NN1 "_" Robert_NP1 D._NP1 Arnott_NP1 ,_, Jason_NP1 Hsu_NP1 and_CC Philip_NP1 Moore_NP1 came_VVD forth_RR with_IW the_AT conclusion_NN1 that_CST the_AT common_JJ practice_NN1 of_IO weighting_VVG portfolios_NN2 by_II market_NN1 capitalization_NN1 is_VBZ inherently_RR flawed_JJ ._. 
</s>
<s>
They_PPHS2 argue_VV0 that_CST in_II a_AT1 noisy1_FO market_NN1 environment_NN1 capitalization-weighted_NN1 indexation_NN1 produces_VVZ portfolios_NN2 that_CST allocate_VV0 more_DAR money_NN1 to_II overvalued_JJ securities_NN2 and_CC less_DAR money_NN1 to_II undervalued_JJ securities_NN2 ,_, which_DDQ leads_VVZ to_II a_AT1 persistent_JJ performance_NN1 drag_VV0 ._. 
</s>
<s>
This_DD1 notion_NN1 has_VHZ since_RR gained_VVN further_RRR acknowledgement_NN1 from_II several_DA2 finance_VV0 heavyweights_NN2 ,_, including_II Jeremy_NP1 Siegel_NP1 ,_, Harry_NP1 Markowitz_NP1 ,_, Jack_NP1 Treynor_NP1 and_CC the_AT late_JJ Peter_NP1 Bernstein_NP1 ._. 
</s>
<s>
As_II a_AT1 solution_NN1 ,_, Arnott_NP1 et_RA21 al_RA22 (_( 2005_MC )_) propose_VV0 a_AT1 weighting_NN1 scheme_NN1 based_VVN on_II company_NN1 fundamentals_NN2 ,_, indifferent_JJ of_IO investors_NN2 subjective_JJ valuation_NN1 that_CST is_VBZ subject_II21 to_II22 pricing_VVG error_NN1 and_CC noise_NN1 created_VVN by_II speculative_JJ investors_NN2 and_CC momentum_NN1 traders_NN2 ._. 
</s>
<s>
This_DD1 indexation_NN1 method_NN1 is_VBZ said_VVN to_TO eliminate_VVI the_AT performance_NN1 drag_VV0 inherent_JJ in_II cap-_JJ weighted_JJ portfolios_NN2 ._. 
</s>
<s>
Arnott_VV0 et_RA21 al_RA22 (_( 2008_MC )_) demonstrate_VV0 that_CST fundamentally_RR weighted_JJ portfolios_NN2 place_VV0 lower_JJR weight_NN1 on_II high_JJ valuation_NN1 multiple_NN1 companies_NN2 than_CSN cap-weighted_JJ portfolios_NN2 ,_, making_VVG the_AT investor_NN1 less_RRR exposed_VVN to_TO price_VVI bubbles_NN2 and_CC ,_, consequently_RR ,_, generating_VVG a_AT1 more_RGR satisfying_JJ cyclically-adjusted_JJ performance_NN1 ._. 
</s>
<s>
The_AT "_" noise-in-price_JJ "_" framework_NN1 adds_VVZ another_DD1 perspective_NN1 to_II the_AT discussion_NN1 of_IO the_AT persistent_JJ size-_NN1 and_CC value_NN1 premia_NN1 in_II equity_NN1 market_NN1 performance_NN1 in_II capital_NN1 markets_NN2 ._. 
</s>
<s>
On_II the_AT other_JJ side_NN1 of_IO the_AT argument_NN1 is_VBZ the_AT efficient_JJ market_NN1 camp_NN1 ,_, who_PNQS offers_VVZ rational_JJ ,_, risk-based_JJ explanations_NN2 to_II the_AT equity_NN1 premium_NN1 puzzle_NN1 ._. 
</s>
<s>
The_AT discussion_NN1 regarding_II cap-weighting_NN1 and_CC valuation-indifferent_JJ indexation_NN1 boils_VVZ down_RP to_II the_AT same_DA problem_NN1 ._. 
</s>
<s>
Theoretical_JJ discussion_NN1 regarding_II fundamental_JJ indexation_NN1 has_VHZ so_RG far_RR been_VBN polarized_VVN between_II proponents_NN2 of_IO the_AT so_JJ21 called_JJ22 noisy-_NN1 and_CC efficient_JJ market_NN1 hypotheses_NN2 ._. 
</s>
<s>
It_PPH1 should_VM also_RR be_VBI noted_VVN that_CST the_AT most_RGT audible_JJ advocates_NN2 of_IO fundamental_JJ indexation_NN1 (_( in_II published_JJ research_NN1 papers_NN2 )_) are_VBR closely_RR associated_VVN with_IW investment_NN1 management_NN1 companies_NN2 offering_VVG fundamental_JJ index_NN1 funds_NN2 to_II individual_JJ and_CC institutional_JJ clients_NN2 ._. 
</s>
<s>
Whether_CSW these_DD2 papers_NN2 are_VBR a_AT1 marketing_NN1 gimmick_NN1 or_CC evidence_NN1 of_IO the_AT claimed_JJ superiority_NN1 of_IO fundamental_JJ indexation_NN1 is_VBZ inconclusive_JJ ._. 
</s>
<s>
Empirical_JJ research_NN1 based_VVN on_II backtesting_VVG of_IO historical_JJ data_NN supports_VVZ the_AT view_NN1 that_CST fundamental_JJ indexation_NN1 ,_, and_CC valuation-indifferent_JJ index_NN1 weighting_VVG in_RR21 general_RR22 ,_, produces_VVZ more_RGR mean-variance_JJ efficient_JJ portfolios_NN2 than_CSN cap-_JJ weighting_NN1 ,_, but_CCB research_NN1 on_II the_AT causality_NN1 of_IO these_DD2 excess_JJ returns_NN2 is_VBZ still_RR lacking_VVG ._. 
</s>
<s>
What_DDQ are_VBR the_AT value_NN1 drivers_NN2 of_IO the_AT reported_JJ outperformance_NN1 ?_? 
</s>
<s>
Do_VD0 they_PPHS2 stem_VVI from_II pricing_VVG errors_NN2 in_II the_AT market_NN1 ,_, as_CSA claimed_VVN by_II Arnott_NP1 et_RA21 al_RA22 ,_, or_CC is_VBZ a_AT1 fundamental_JJ indexation_NN1 strategy_NN1 subject_II21 to_II22 hidden_JJ risks_NN2 not_XX captured_VVN by_II simple_JJ return_NN1 analysis_NN1 ?_? 
</s>
<s>
Going_VVG forward_RL ,_, this_DD1 is_VBZ the_AT most_RGT significant_JJ research_NN1 question_NN1 for_IF investors_NN2 considering_II adopting_VVG a_AT1 fundamental_JJ indexation_NN1 strategy_NN1 instead_II21 of_II22 a_AT1 passive_JJ ,_, cap-weighted_JJ strategy_NN1 ._. 
</s>
<s>
Contribution_NN1 1.1_MC ._. 
</s>
<s>
Purpose_NN1 of_IO the_AT study_NN1 The_AT purpose_NN1 of_IO this_DD1 study_NN1 is_VBZ to_TO investigate_VVI the_AT theoretical_JJ justifications_NN2 for_IF the_AT claimed_JJ outperformance_NN1 of_IO valuation-indifferent_JJ portfolio_NN1 weighting_VVG relative_II21 to_II22 a_AT1 cap-weighted_JJ indexation._NNU 1.2_MC ._. 
</s>
<s>
Structure_NN1 of_IO the_AT thesis_NN1 The_AT paper_NN1 is_VBZ organized_VVN as_CSA follows_VVZ :_: 2_MC ._. 
</s>
<s>
The_AT Noisy_JJ Market_NN1 Hypothesis_NN1 This_DD1 chapter_NN1 presents_VVZ the_AT fundamental_JJ problem_NN1 in_II using_VVG cap_NN1 weighting_NN1 Development_NN1 of_IO EMH_NP1 and_CC CAPM_NP1 shortly_RR A_AT1 short_JJ recap_NN1 of_IO classical_JJ finance_NN1 theory_NN1 is_VBZ necessary_JJ to_TO fully_RR grasp_VVI the_AT theoretical_JJ justification_NN1 for_IF the_AT supposed_JJ underperformance_NN1 of_IO cap_NN1 weighting_NN1 ,_, also_RR known_VVN as_II noisy_JJ market_NN1 hypothesis_NN1 ._. 
</s>
<s>
According_II21 to_II22 the_AT efficient_JJ market_NN1 hypothesis_NN1 ,_, the_AT price_NN1 of_IO every_AT1 security_NN1 traded_VVN on_II capital_NN1 markets_NN2 represents_VVZ the_AT best_JJT ,_, unbiased_JJ estimate_NN1 of_IO the_AT true_JJ underlying_JJ value_NN1 at_II all_DB times_NNT2 ._. 
</s>
<s>
This_DD1 does_VDZ not_XX mean_VVI that_DD1 mispricing_NN1 does_VDZ not_XX occur_VVI ,_, but_CCB that_CST it_PPH1 is_VBZ impossible_JJ to_TO distinguish_VVI which_DDQ securities_NN2 are_VBR mispriced_VVN through_II security_NN1 analysis_NN1 ._. 
</s>
<s>
It_PPH1 can_VM be_VBI shown_VVN that_CST in_II an_AT1 efficiently_RR priced_VVN market_NN1 ,_, a_AT1 capitalization-weighted_JJ portfolio_NN1 offers_VVZ the_AT best_JJT performance_NN1 in_II a_AT1 mean-variance_JJ space_NN1 ._. 
</s>
<s>
Failure_NN1 of_IO CAPM_NP1 (_( market_VV0 portfolio_NN1 is_VBZ not_XX mean-variance_JJ efficient_JJ )_) relevant_JJ anomalies&lsqb;size_JJ (_( Banz_NP1 ,_, Keim_NP1 )_) ,_, value_NN1 (_( Basu_NP1 ,_, Dreman_NP1 )_) and_CC momentum_NN1 (_( ?_? )_) ,_, other_JJ anomalies_NN2 have_VH0 also_RR been_VBN detected_VVN Historical_JJ backtesting_NN1 of_IO following_VVG a_AT1 small_JJ cap_NN1 or_CC value_NN1 strategy_NN1 could_VM not_XX be_VBI rationalized_VVN by_II existing_JJ pricing_NN1 models_NN2 ._. 
</s>
<s>
The_AT magnitude_NN1 of_IO these_DD2 excess_JJ returns_NN2 caused_VVD turbulence_NN1 in_II academia_NN1 and_CC severely_RR hurt_VV0 the_AT credibility_NN1 of_IO the_AT capital_NN1 market_NN1 equilibrium_NN1 theory_NN1 developed_VVD more_DAR than_CSN two_MC decades_NNT2 earlier_RRR ._. 
</s>
<s>
CAPM_NP1 extensions_NN2 (_( multifactor_NN1 ,_, consumption_NN1 )_) ,_, hidden_JJ risks_NN2 ,_, behavioral_JJ explanations_NN2 (_( time_VV0 varying_JJ risk_NN1 premiums_NN2 )_) )_) If_CS prices_NN2 observed_VVN in_II the_AT market_NN1 are_VBR the_AT best_JJT ,_, unbiased_JJ estimators_NN2 of_IO fair_JJ market_NN1 value_NN1 ,_, a_AT1 cap-weighted_JJ portfolio_NN1 will_VM be_VBI the_AT superior_JJ portfolio_NN1 choice_NN1 in_II the_AT investor_NN1 opportunity_NN1 set_NN1 ,_, but_CCB empirical_JJ tests_NN2 on_II CAPM_NP1 show_VV0 that_CST the_AT cap-weighted_JJ equity_NN1 market_NN1 portfolio_NN1 has_VHZ not_XX been_VBN a_AT1 mean-variance_JJ efficient_JJ portfolio_NN1 in_II the_AT past_NN1 ._. 
</s>
<s>
&lsqb;_( Ref._NN1 &rsqb;_) equities_NN2 a_AT1 poor_JJ proxy_NN1 There_EX is_VBZ also_RR a_AT1 problem_NN1 with_IW using_VVG an_AT1 equity_NN1 market_NN1 portfolio_NN1 as_II a_AT1 basis_NN1 for_IF CAPM_NP1 ._. 
</s>
<s>
Theoretically_RR ,_, the_AT CAPM_NP1 market_NN1 portfolio_NN1 should_VM include_VVI all_DB capital_NN1 assets_NN2 ,_, non-traded_JJ assets_NN2 included_VVD ,_, that_CST are_VBR in_II positive_JJ net_JJ supply_NN1 ._. 
</s>
<s>
Therefore_RR ,_, a_AT1 market_NN1 portfolio_NN1 based_VVN on_II traded_JJ equities_NN2 can_VM be_VBI seen_VVN as_II an_AT1 unfit_JJ proxy_NN1 for_IF an_AT1 all-asset_JJ market_NN1 portfolio_NN1 ._. 
</s>
<s>
(_( Mayers_NP2 1976_MC )_) Background_NN1 Taking_VVG these_DD2 inconsistencies_NN2 with_IW the_AT efficient_JJ market_NN1 hypothesis_NN1 into_II notion_NN1 ,_, it_PPH1 seems_VVZ rather_RG odd_JJ that_CST a_AT1 large_JJ quantity_NN1 of_IO investment_NN1 advisors_NN2 and_CC investment_NN1 literature_NN1 suggest_VV0 that_CST a_AT1 casual_JJ investor_NN1 should_VM stick_VVI to_II following_VVG a_AT1 passive_JJ ,_, low-cost_JJ indexation_NN1 strategy_NN1 based_VVN on_II replicating_VVG the_AT return_NN1 of_IO a_AT1 broad_JJ ,_, well-diversified_JJ equity_NN1 index_NN1 ._. 
</s>
<s>
If_CS the_AT CAPM_NP1 assumptions_NN2 are_VBR not_XX empirically_RR robust_JJ ,_, it_PPH1 is_VBZ highly_RR likely_JJ that_CST an_AT1 investment_NN1 strategy_NN1 based_VVN on_II the_AT assumption_NN1 that_CST the_AT market_NN1 portfolio_NN1 is_VBZ mean-variance_JJ efficient_JJ is_VBZ not_XX the_AT best_JJT possible_JJ investment_NN1 alternative_NN1 for_IF the_AT casual_JJ investor_NN1 ._. 
</s>
<s>
What_DDQ is_VBZ noisy_JJ market_NN1 hypothesis_NN1 Being_VBG in_II direct_JJ opposition_NN1 to_II the_AT efficient_JJ market_NN1 hypothesis_NN1 ,_, the_AT noisy_JJ market_NN1 hypothesis_NN1 makes_VVZ the_AT claim_NN1 that_CST the_AT observed_JJ market_NN1 price_NN1 is_VBZ not_XX always_RR the_AT best_JJT ,_, unbiased_JJ estimate_NN1 of_IO the_AT fair_JJ market_NN1 value_NN1 of_IO a_AT1 security_NN1 ._. 
</s>
<s>
Siegel_NP1 (_( 2006_MC )_) argues_VVZ that_DD1 price_NN1 formation_NN1 in_II the_AT market_NN1 is_VBZ subject_II21 to_II22 structural_JJ disturbances_NN2 ,_, such_II21 as_II22 taxes_NN2 and_CC liquidity_NN1 ,_, as_II31 well_II32 as_II33 speculative_JJ behavior_NN1 on_II part_NN1 of_IO investors_NN2 ._. 
</s>
<s>
These_DD2 unpredictable_JJ and_CC temporal_JJ shocks_NN2 ,_, dubbed_VVN as_CSA "_" noise_NN1 "_" ,_, obscure_VV0 the_AT intrinsic_JJ value_NN1 of_IO securities_NN2 ._. 
</s>
<s>
If_CS individual_JJ share_NN1 prices_NN2 are_VBR noisy_JJ ,_, this_DD1 pricing_NN1 error_NN1 will_VM also_RR affect_VVI the_AT index_NN1 weights_NN2 in_II cap-weighted_JJ indices_NN2 ._. 
</s>
<s>
The_AT basic_JJ intuition_NN1 of_IO Arnott_NP1 et_RA21 al_RA22 (_( 2005_MC )_) argument_NN1 is_VBZ this_DD1 :_: suppose_VV0 pricing_VVG error_NN1 is_VBZ randomly_RR distributed_VVN around_II the_AT intrinsic_JJ value_NN1 of_IO a_AT1 stock_NN1 ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, the_AT equity_NN1 market_NN1 provides_VVZ a_AT1 statistically_RR unbiased_JJ "_" best_JJT guess_NN1 "_" of_IO the_AT future_JJ discounted_JJ cash_NN1 flows_NN2 of_IO a_AT1 stock_NN1 ._. 
</s>
<s>
In_II a_AT1 valuation-indifferent_JJ portfolio_NN1 ,_, such_II21 as_II22 an_AT1 equally-_JJ weighted_JJ portfolio_NN1 ,_, portfolio_NN1 weights_NN2 are_VBR unaffected_JJ by_II the_AT emergence_NN1 of_IO pricing_VVG error_NN1 in_II the_AT share_NN1 prices_NN2 ._. 
</s>
<s>
In_II a_AT1 reasonably_RR large_JJ valuation-indifferent_JJ portfolio_NN1 ,_, the_AT net_JJ impact_NN1 of_IO pricing_VVG errors_NN2 will_VM be_VBI negligible_JJ as_CSA portfolio_NN1 holdings_NN2 are_VBR evenly_RR distributed_VVN among_II overvalued_JJ and_CC undervalued_VVN securities_NN2 ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 ,_, in_II a_AT1 cap-weighted_JJ portfolio_NN1 ,_, portfolio_NN1 weights_NN2 will_VM have_VHI a_AT1 positive_JJ correlation_NN1 with_IW pricing_VVG error_NN1 as_CSA overvalued_JJ securities_NN2 get_VV0 a_AT1 larger_JJR relative_JJ share_NN1 of_IO the_AT portfolio_NN1 ._. 
</s>
<s>
If_CS and_CC when_RRQ share_NN1 prices_NN2 revert_VV0 to_II their_APPGE intrinsic_JJ value_NN1 ,_, cap-weighted_JJ portfolios_NN2 suffer_VV0 a_AT1 performance_NN1 drag_VV0 due_II21 to_II22 this_DD1 correlation_NN1 ._. 
</s>
<s>
However_RR ,_, the_AT effect_NN1 of_IO pricing_VVG errors_NN2 in_II capital_NN1 markets_NN2 on_II portfolio_NN1 performance_NN1 is_VBZ not_XX an_AT1 easy_JJ subject_II21 to_II22 investigate_VV0 ,_, as_CSA the_AT intrinsic_JJ value_NN1 of_IO assets_NN2 is_VBZ not_XX observable_JJ ._. 
</s>
<s>
Furthermore_RR ,_, there_EX is_VBZ no_AT assurance_NN1 that_CST asset_NN1 prices_NN2 ultimately_RR regress_VV0 to_II fair_JJ value_NN1 ._. 
</s>
<s>
In_II this_DD1 sense_NN1 ,_, an_AT1 exacerbation_NN1 of_IO pricing_VVG errors_NN2 can_VM be_VBI favorable_JJ to_II an_AT1 investor_NN1 following_VVG a_AT1 cap-weighted_JJ indexation_NN1 strategy_NN1 ._. 
</s>
<s>
&lsqb;_( Arnott_VV0 example_NN1 of_IO cap-weighted_JJ outperformance_NN1 during_II booms_NN2 &rsqb;_) In_II an_AT1 efficient_JJ market_NN1 ,_, asset_NN1 prices_NN2 would_VM be_VBI static_JJ and_CC no_AT trading_NN1 would_VM need_VVI to_TO take_VVI place_NN1 ,_, unless_CS new_JJ and_CC unexpected_JJ information_NN1 about_II the_AT asset_NN1 emerges_VVZ ._. 
</s>
<s>
&lsqb;_( out_II21 of_II22 place_NN1 ?_? &rsqb;_) 
</s>
<s>
Formal_JJ mathematical_JJ proof_NN1 (_( Treynor_NP1 ,_, Hsu_NP1 )_) It_PPH1 can_VM be_VBI shown_VVN that_CST in_II the_AT presence_NN1 of_IO noise_NN1 ,_, capitalization-weighted_JJ portfolios_NN2 offer_VV0 inferior_JJ risk-adjusted_NN1 returns_VVZ relative_II21 to_II22 valuation-indifferent_JJ portfolios_NN2 ._. 
</s>
<s>
Treynor_NP1 (_( 2005_MC )_) offers_VVZ a_AT1 formal_JJ demonstration_NN1 of_IO the_AT underperformance_NN1 of_IO cap-weighted_JJ portfolios_NN2 relative_II21 to_II22 valuation-indifferent_JJ portfolios_NN2 in_II a_AT1 "_" price_NN1 in_II noise_NN1 "_" framework_NN1 ._. 
</s>
<s>
Mean_JJ reversion_NN1 effect_NN1 Critique_NN1 of_IO Arnotts_NP2 rationale_NN1 2.1_MC ._. 
</s>
<s>
Can_VV0 noise_NN1 explain_VV0 the_AT size-_NN1 and_CC value_NN1 anomalies_NN2 ?_? 
</s>
<s>
The_AT noisy_JJ market_NN1 hypothesis_NN1 offers_VVZ a_AT1 possible_JJ explanation_NN1 for_IF the_AT size_NN1 and_CC value_NN1 anomalies_NN2 ._. 
</s>
<s>
&lsqb;_( Other_JJ studies_NN2 claiming_VVG pricing_NN1 inefficiency_NN1 as_CSA source_NN1 of_IO anomalies_NN2 ?_? &rsqb;_) 
</s>
<s>
If_CS a_AT1 stock_NN1 price_NN1 falls_VVZ because_II21 of_II22 noise_NN1 ,_, i.e._REX without_IW a_AT1 change_NN1 in_II the_AT company_NN1 fundamentals_NN2 ,_, overweighting_VVG that_DD1 stock_NN1 will_VM probably_RR yield_VVI a_AT1 positive_JJ excess_JJ return_NN1 ._. 
</s>
<s>
Conversely_RR ,_, if_CS a_AT1 stock_NN1 price_NN1 moves_VVZ up_RP without_IW a_AT1 change_NN1 in_II fundamentals_NN2 ,_, that_DD1 stock_NN1 will_VM probably_RR underperform_VVI ._. 
</s>
<s>
Stocks_NN2 whose_DDQGE price_NN1 exceeds_VVZ their_APPGE fundamental_JJ value_NN1 become_VV0 large-cap_JJ stocks_NN2 and_CC therefore_RR are_VBR more_RGR likely_JJ to_TO underperform_VVI (_( Siegel_NP1 2006_MC )_) ._. 
</s>
<s>
Risk-based_JJ explanation_NN1 for_IF size-_NN1 and_CC value_NN1 effects_NN2 3_MC ._. 
</s>
<s>
The_AT case_NN1 for_IF index_NN1 investing_VVG This_DD1 section_NN1 explains_VVZ the_AT use_NN1 of_IO indexing_NN1 and_CC its_APPGE pros_NN2 and_CC cons_VVZ as_II an_AT1 investment_NN1 strategy_NN1 What_DDQ is_VBZ index_NN1 ?_? -_- Arnotts_VVZ requirements_NN2 ?_? 
</s>
<s>
Discussion_NN1 (_( S_ZZ1 &P;_NULL 500_MC )_) and_CC my_APPGE own_DA definition_NN1 (_( portfolio_NN1 construction_NN1 method_NN1 )_) ._. 
</s>
<s>
apply_VV0 a_AT1 rule-based_JJ rebalancing_JJ scheme_NN1 ._. 
</s>
<s>
FI=portfolio_FO What_DDQ is_VBZ cap_NN1 weighting_NN1 ?_? 
</s>
<s>
In_II a_AT1 capitalization-weighted_JJ index_NN1 ,_, each_DD1 company_NN1 in_II the_AT index_NN1 weighed_VVN in_II31 accordance_II32 with_II33 their_APPGE market_NN1 capitalization_NN1 (_( i.e._REX market_NN1 value_NN1 or_CC share_NN1 price_NN1 times_II the_AT number_NN1 of_IO shares_NN2 outstanding_JJ )_) relative_II21 to_II22 the_AT total_JJ market_NN1 capitalization_NN1 of_IO all_DB companies_NN2 included_VVN in_II the_AT index_NN1 ._. 
</s>
<s>
Most_DAT of_IO the_AT well_NN1 known_VVN capitalization-weighted_JJ equity_NN1 indices_NN2 ,_, such_II21 as_II22 those_DD2 developed_VVN by_II Standard_JJ &;_NULL Poors_NN2 (_( S_ZZ1 &P;_NULL 500_MC )_) ,_, Russell_NP1 Investment_NN1 Group_NN1 (_( Russell_NP1 1000_MC )_) or_CC Wilshire_NP1 Associates_NN2 (_( Wilshire_NP1 5000_MC )_) ,_, are_VBR float-adjusted_JJ meaning_NN1 that_CST the_AT number_NN1 of_IO shares_NN2 owned_VVN by_II company_NN1 insiders_NN2 and_CC the_AT government_NN1 are_VBR not_XX taken_VVN into_II account_NN1 in_II the_AT calculation_NN1 of_IO market_NN1 capitalization_NN1 ._. 
</s>
<s>
The_AT aforementioned_JJ indices_NN2 are_VBR rebalanced_VVN annually_RR ._. 
</s>
<s>
The_AT holdings_NN2 in_II the_AT indices_NN2 do_VD0 not_XX necessarily_RR consist_VVI of_IO the_AT largest_JJT U.S._NP1 based_VVD companies_NN2 measured_VVN by_II market_NN1 capitalization_NN1 ,_, but_CCB instead_RR the_AT portfolio_NN1 selection_NN1 is_VBZ made_VVN by_II a_AT1 committee_NN1 ._. 
</s>
<s>
Positive_JJ traits_NN2 with_IW cap_NN1 weighted_JJ indexation_NN1 :_: 1_MC1 ._. 
</s>
<s>
Capitalization_NN1 weighting_NN1 is_VBZ a_AT1 "_" buy_NN1 and_CC hold_VV0 "_" strategy_NN1 that_CST is_VBZ often_RR associated_VVN with_IW low_JJ portfolio_NN1 turnover_NN1 and_CC ,_, hence_RR ,_, generates_VVZ relatively_RR little_JJ trading_NN1 costs_NN2 ._. 
</s>
<s>
Stocks_NN2 in_II the_AT portfolio_NN1 are_VBR automatically_RR rebalanced_VVN as_II the_AT market_NN1 constantly_RR reconsiders_VVZ its_APPGE expectations_NN2 of_IO a_AT1 stocks_NN2 return_VV0 and_CC riskiness_NN1 ._. 
</s>
<s>
A_AT1 cap-weighted_JJ portfolio_NN1 requires_VVZ rebalancing_VVG only_RR when_CS there_EX are_VBR changes_NN2 in_II the_AT constituents_NN2 in_II the_AT underlying_JJ benchmark_NN1 due_II21 to_II22 corporate_JJ events_NN2 such_II21 as_II22 mergers_NN2 ,_, acquisitions_NN2 ,_, bankruptcies_NN2 et_RR21 cetera._RR22 2_MC ._. 
</s>
<s>
Cap_VV0 weighted_JJ indices_NN2 give_VV0 the_AT largest_JJT weight_NN1 to_II stocks_NN2 with_IW high_JJ trading_NN1 liquidity_NN1 further_RRR reducing_VVG trading_NN1 costs._NNU cap_NN1 index_NN1 theoretical_JJ justification_NN1 ,_, elegance_NN1 ,_, empirical_JJ performance_NN1 ,_, a_AT1 good_JJ measure_NN1 of_IO the_AT market_NN1 portfolio_NN1 Indexation_NN1 as_II an_AT1 investment_NN1 strategy_NN1 (_( pros_NN2 &;_NULL cons_VVZ )_) Research_NN1 on_II long-term_JJ equity_NN1 returns_VVZ versus_II and_CC the_AT relatively_RR poor_JJ performance_NN1 of_IO actively_RR managed_VVN funds_NN2 performance_NN1 prompted_VVD a_AT1 demand_NN1 for_IF indexed_JJ investing_JJ ._. 
</s>
<s>
The_AT first_MD index_NN1 fund_NN1 was_VBDZ set_VVN up_RP for_IF institutional_JJ investors_NN2 in_II 1973_MC and_CC for_IF private_JJ individuals_NN2 in_II 1976_MC (_( Arnott_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2008_MC )_) ._. 
</s>
<s>
An_AT1 argument_NN1 commonly_RR set_VVN forth_RR by_II index_NN1 fund_NN1 providers_NN2 is_VBZ that_CST actively_RR managed_VVN funds_NN2 seldom_RR can_VM consistently_RR beat_VVI a_AT1 cap-weighted_JJ market_NN1 portfolio_NN1 adjusted_VVN for_IF survivorship_NN1 bias_NN1 ,_, management_NN1 fees_NN2 and_CC trading_NN1 costs_NN2 ._. 
</s>
<s>
&lsqb;_( Ref_NN1 ._. &rsqb;_) 
</s>
<s>
An_AT1 intuitive_JJ explanation_NN1 for_IF this_DD1 phenomenon_NN1 is_VBZ that_CST if_CS we_PPIS2 subtract_VV0 index_NN1 funds_NN2 from_II the_AT cap-_JJ weighted_JJ market_NN1 portfolio_NN1 ,_, were_VBDR left_VVN with_IW a_AT1 market_NN1 portfolio_NN1 collectively_RR owned_VVN by_II actively_RR managed_VVN funds_NN2 ._. 
</s>
<s>
Net_NN1 of_IO costs_NN2 ,_, this_DD1 actively_RR managed_VVN market_NN1 portfolio_NN1 can_VM not_XX outperform_VVI itself_PPX1 ._. 
</s>
<s>
Capitalization-weighting_NN1 is_VBZ a_AT1 method_NN1 to_TO replicate_VVI the_AT market_NN1 portfolio_NN1 and_CC should_VM the_AT market_NN1 price_VVI assets_NN2 efficiently_RR ,_, given_VVN no_AT information_NN1 asymmetries_NN2 or_CC other_JJ imperfections_NN2 ,_, this_DD1 portfolio_NN1 will_VM offer_VVI investors_NN2 the_AT best_JJT risk-return_NN1 combination_NN1 ._. 
</s>
<s>
What_DDQ is_VBZ valuation-indifferent_JJ weighing_NN1 ?_? 4_MC ._. 
</s>
<s>
Valuation_NN1 indifferent_JJ indexation_NN1 This_DD1 section_NN1 explains_VVZ the_AT rationale_NN1 behind_II valuation-indifferent_JJ indexation_NN1 (_( focus_VV0 on_II fund_NN1 ._. 
</s>
<s>
indexation_NN1 )_) A_ZZ1 valuation-indifferent_JJ index_NN1 differs_VVZ from_II the_AT cap_NN1 weighted_JJ index_NN1 in_II the_AT way_NN1 that_CST ,_, instead_II21 of_II22 market_NN1 capitalization_NN1 ,_, the_AT weight_NN1 of_IO a_AT1 security_NN1 included_VVN in_II the_AT index_NN1 is_VBZ based_VVN on_II a_AT1 non-price_JJ related_JJ metric_JJ ._. 
</s>
<s>
The_AT main_JJ idea_NN1 is_VBZ to_TO break_VVI the_AT link_NN1 between_II equity_NN1 price_NN1 and_CC index_NN1 weighing_NN1 ._. 
</s>
<s>
An_AT1 example_NN1 of_IO a_AT1 valuation-indifferent_JJ weighing_NN1 scheme_NN1 is_VBZ the_AT equal_JJ weighting_NN1 ._. 
</s>
<s>
In_II this_DD1 method_NN1 ,_, every_AT1 index_NN1 constituent_NN1 is_VBZ given_VVN the_AT same_DA index_NN1 weight_NN1 relative_II21 to_II22 each_PPX221 other_PPX222 ._. 
</s>
<s>
For_REX21 instance_REX22 ,_, if_CS a_AT1 portfolio_NN1 consists_VVZ of_IO n_ZZ1 stock_NN1 ,_, each_DD1 stock_NN1 will_VM be_VBI given_VVN the_AT weight_NN1 of_IO 1/n_FU in_II an_AT1 equally_RR weighted_JJ portfolio_NN1 ._. 
</s>
<s>
The_AT weighting_NN1 is_VBZ thus_RR completely_RR unrelated_JJ to_II the_AT individual_JJ stock_NN1 prices_NN2 ._. 
</s>
<s>
Random_JJ weighting_NN1 ?_? 
</s>
<s>
What_DDQ is_VBZ fundamental_JJ indexation_NN1 ?_? economic_JJ weight_NN1 The_AT main_JJ focus_NN1 in_II this_DD1 thesis_NN1 is_VBZ on_II investigating_VVG a_AT1 concept_NN1 known_VVN as_II fundamental_JJ indexation_NN1 ._. 
</s>
<s>
Similar_JJ to_II a_AT1 cap-weighted_JJ portfolio_NN1 ,_, fundamentally_RR indexed_VVN portfolios_NN2 do_VD0 not_XX involve_VVI security_NN1 analysis_NN1 ,_, but_CCB instead_II21 of_II22 market_NN1 value_NN1 the_AT holdings_NN2 are_VBR proportional_JJ to_II a_AT1 suitable_JJ fundamental_JJ metric_JJ of_IO company_NN1 size_NN1 ._. 
</s>
<s>
There_EX is_VBZ no_AT definite_JJ measure_NN1 of_IO company_NN1 size_NN1 or_CC its_APPGE significance_NN1 in_II the_AT economy_NN1 ._. 
</s>
<s>
Portfolio_NN1 managers_NN2 following_VVG a_AT1 fundamental_JJ index_NN1 strategy_NN1 usually_RR measure_VV0 a_AT1 companys_NN2 economic_JJ weight_NN1 using_VVG balance_NN1 sheet_NN1 data_NN ._. 
</s>
<s>
The_AT commonly_RR chosen_VVN size_NN1 metrics_NN2 include_VV0 :_: revenue/sales_FU ,_, book_NN1 value_NN1 of_IO equity_NN1 ,_, earnings_NN2 ,_, cash_NN1 flow_NN1 ,_, dividends_NN2 and_CC employment_NN1 ._. 
</s>
<s>
Fundamental_JJ indexation_NN1 as_CSA such_DA does_VDZ not_XX indicate_VVI which_DDQ weighting_NN1 method_NN1 is_VBZ used_VVN ._. 
</s>
<s>
Fundamental_JJ indexation_NN1 is_VBZ a_AT1 valuation-indifferent_JJ weighting_NN1 method_NN1 due_JJ as_CS31 long_CS32 as_CS33 the_AT weight_NN1 metric_JJ is_VBZ unrelated_JJ to_II the_AT market_NN1 value_NN1 of_IO a_AT1 company_NN1 ._. 
</s>
<s>
On_II a_AT1 conceptual_JJ level_NN1 ,_, fundamental_JJ indexation_NN1 is_VBZ a_AT1 step_NN1 away_II21 from_II22 a_AT1 market-centric_JJ approach_NN1 where_RRQ investors_NN2 view_VV0 their_APPGE investment_NN1 opportunity_NN1 set_VVN relative_II21 to_II22 the_AT stock_NN1 market_NN1 ._. 
</s>
<s>
This_DD1 approach_NN1 is_VBZ supported_VVN by_II classical_JJ finance_NN1 theory_NN1 where_RRQ ,_, given_VVN the_AT liberty_NN1 of_IO some_DD simplifications_NN2 ,_, stock_NN1 prices_NN2 incorporate_VV0 all_DB available_JJ information_NN1 concerning_II expected_JJ future_JJ cash_NN1 flows_NN2 and_CC the_AT risk_NN1 characteristics_NN2 of_IO these_DD2 cash_NN1 flows_NN2 ._. 
</s>
<s>
In_II this_DD1 approach_NN1 ,_, securities_NN2 traded_VVN in_II the_AT market_NN1 ,_, at_RR21 least_RR22 in_II the_AT long_JJ run_NN1 ,_, are_VBR priced_VVN correctly_RR ._. 
</s>
<s>
Instead_RR ,_, Arnott_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2008_MC )_) prefer_VV0 to_TO view_VVI their_APPGE indexation_NN1 method_NN1 as_II an_AT1 economy-centric_JJ approach_NN1 ,_, where_CS portfolio_NN1 holdings_NN2 are_VBR weighted_VVN according_II21 to_II22 their_APPGE relative_JJ size_NN1 in_II the_AT economy_NN1 ._. 
</s>
<s>
Time_NNT1 perspective_NN1 (_( estimating_VVG future_JJ performance_NN1 vs._II measuring_VVG past_JJ performance_NN1 )_) ,_, subjective(valuation)_NN1 vs._II objective(fundamentals)_NN2 Problem_NN1 :_: sector_NN1 tilts_NN2 ,_, taxation_NN1 and_CC structural_JJ issues(dividends)_NN2 Solution_NN1 :_: to_TO use_VVI a_AT1 composite_JJ combining_VVG several_DA2 size_NN1 metrics_NN1 Arnotts_VVZ rationale_NN1 (_( price_NN1 randomly_RR distributed_VVN around_II true_JJ value_NN1 and_CC not_XX vice_RR21 versa_RR22 )_) Critique_NN1 Asness_NN1 ,_, Malkiel_NP1 Kaplan_NP1 ,_, Perold_NP1 Averaging_NN1 (_( not_XX current_JJ data_NN )_) Wikipedia_NP1 Own_DA critique_NN1 (_( no_AT definite_JJ metrics_NN2 ,_, if_CS theory_NN1 correct_JJ success_NN1 relies_VVZ on_II continued_JJ irrationality_NN1 ,_, etc_RA ._. )_) 
</s>
<s>
Empirical_JJ research_NN1 US_NP1 evidence_NN1 (_( Arnott_NP1 )_) International_JJ evidence_NN1 Evidence_NN1 from_II other_JJ markets_NN2 (_( bonds_NN2 ,_, real_JJ estate_NN1 )_) Costs_VVZ In_II contrast_NN1 to_TO cap_VVI weighted_JJ portfolios_NN2 ,_, which_DDQ rebalance_NN1 automatically_RR as_CSA security_NN1 prices_NN2 change_VV0 ,_, fundamentally_RR weighted_JJ portfolios_NN2 are_VBR rebalanced_VVN periodically_RR ._. 
</s>
<s>
In_II practice_NN1 ,_, this_DD1 means_VVZ purchasing_VVG shares_NN2 in_II companies_NN2 whose_DDQGE share_NN1 price_NN1 have_VH0 risen_VVN more_RRR than_CSN the_AT fundamental_JJ metric_JJ and_CC selling_VVG shares_NN2 in_II companies_NN2 whose_DDQGE share_NN1 price_NN1 has_VHZ dropped_VVN more_RRR than_CSN the_AT fundamental_JJ metric_JJ ._. 
</s>
<s>
Rebalancing_NP1 generates_VVZ trading_NN1 costs_NN2 ,_, which_DDQ depend_VV0 on_II rebalancing_VVG frequency_NN1 ,_, portfolio_NN1 size_NN1 ,_, market_VV0 liquidity_NN1 factors_NN2 and_CC the_AT maximum_JJ tracking_JJ error_NN1 a_AT1 portfolio_NN1 manager_NN1 is_VBZ prepared_VVN to_TO tolerate_VVI ._. 
</s>
<s>
Investing_VVG in_II fundamental_JJ indices_NN2 (_( in_II Finland_NP1 and_CC abroad_RL )_) 5_MC ._. 
</s>
<s>
Conclusions_NN2 and_CC summary_NN1 Further_JJR theoretical_JJ considerations_NN2 :_: Pricing_VVG errors_NN2 must_VM persist_VVI in_II the_AT future_NN1 (_( irrationality_NN1 of_IO investors_NN2 ,_, hedge_NN1 funds_NN2 etc_RA )_) Strategy_NN1 not_XX adopted_VVN by_II investment_NN1 professionals_NN2 (_( slow_JJ adjustment_NN1 in_II the_AT investment_NN1 community_NN1 
</s>
