<s>
Implementing_VVG an_AT1 Enterprise_NN1 Resource_NN1 Planning_NN1 System_NN1 Introduction_NN1 Enterprise_NN1 Resource_NN1 Planning_NN1 systems_NN2 (_( ERP_NP1 )_) have_VH0 their_APPGE roots_NN2 in_II Material_NN1 Requirement_NN1 Planning_NN1 (_( MRP_NP1 )_) systems_NN2 that_CST were_VBDR developed_VVN in_II the_AT 1970s_MC2 ,_, and_CC in_II Manufacturing_NN1 Resource_NN1 Planning_NN1 (_( MRPII_NP1 )_) that_CST emerged_VVD from_II MRP_NP1 in_II the_AT 1980s_MC2 ._. 
</s>
<s>
In_II the_AT 1990s_MC2 information_NN1 technology_NN1 had_VHD developed_VVN to_II a_AT1 stage_NN1 where_RRQ it_PPH1 was_VBDZ possible_JJ to_TO incorporate_VVI all_DB resources_NN2 of_IO an_AT1 enterprise_NN1 into_II one_MC1 unified_JJ system_NN1 ,_, and_CC so_RR the_AT development_NN1 of_IO ERP_NN1 systems_NN2 began_VVD ._. 
</s>
<s>
Since_II then_RT ,_, ERPII_NP1 was_VBDZ developed_VVN in_II the_AT early_JJ 2000s_MC2 ._. 
</s>
<s>
This_DD1 study_NN1 will_VM concentrate_VVI on_II implementation_NN1 of_IO ERP_NN1 systems_NN2 ._. 
</s>
<s>
(_( Turner_NP1 &;_NULL Weickenannt_NP1 ,_, 2009_MC )_) ERP_VV0 systems_NN2 offer_VV0 a_AT1 multimodule_NN1 software_NN1 system_NN1 that_CST combines_VVZ all_DB business_NN1 processes_NN2 into_II one_MC1 single_JJ software_NN1 system_NN1 ,_, needing_VVG only_RR on_II database_NN1 ._. 
</s>
<s>
Implementing_VVG an_AT1 ERP_NN1 system_NN1 is_VBZ very_RG expensive_JJ ._. 
</s>
<s>
There_EX is_VBZ no_AT room_NN1 for_IF error_NN1 and_CC if_CS one_PN1 does_VDZ occur_VVI ,_, it_PPH1 can_VM be_VBI very_RG costly_JJ to_TO make_VVI up_RP for_IF the_AT mistakes_NN2 ._. 
</s>
<s>
However_RR in_II todays_NN2 competitive_JJ market_NN1 ERP_NN1 systems_NN2 are_VBR also_RR a_AT1 measure_NN1 for_IF gaining_VVG competitive_JJ advantage_NN1 ._. 
</s>
<s>
The_AT benefits_NN2 provided_VVN by_II an_AT1 ERP_NN1 system_NN1 can_VM be_VBI broken_VVN down_RP into_II two_MC categories_NN2 :_: 1_MC1 )_) a_AT1 unified_JJ enterprise_NN1 view_NN1 of_IO the_AT business_NN1 that_CST encompasses_VVZ all_DB functions_NN2 and_CC departments_NN2 ;_; and_CC 2_MC )_) an_AT1 enterprise_NN1 database_NN1 where_CS all_DB business_NN1 transactions_NN2 are_VBR entered_VVN ,_, recorded_VVD ,_, processed_VVD ,_, monitored_VVD ,_, and_CC reported_VVD ._. 
</s>
<s>
(_( Umble_VV0 ;_; Haft_NP1 ;_; &;_NULL Umble_NP1 ,_, 2003_MC )_) The_AT implementation_NN1 process_NN1 has_VHZ in_II many_DA2 cases_NN2 proven_VVN to_TO be_VBI everything_PN1 but_II simple_JJ and_CC straight_JJ21 forward_JJ22 as_CSA depicted_VVN by_II ERP_NP1 vendors_NN2 ._. 
</s>
<s>
This_DD1 study_NN1 intends_VVZ to_TO clarify_VVI the_AT risk_NN1 and_CC potential_JJ benefits_NN2 that_CST can_VM follow_VVI an_AT1 implementation_NN1 of_IO an_AT1 ERP_NN1 system_NN1 ._. 
</s>
<s>
The_AT first_MD objective_NN1 of_IO the_AT research_NN1 is_VBZ to_TO identify_VVI the_AT most_RGT crucial_JJ risks_NN2 when_CS implementing_VVG an_AT1 ERP_NN1 system_NN1 ._. 
</s>
<s>
Linking_VVG these_DD2 risks_NN2 to_II modules_NN2 that_CST make_VV0 part_NN1 of_IO an_AT1 ERP_NN1 system_NN1 will_VM also_RR make_VVI part_NN1 of_IO this_DD1 objective_NN1 ._. 
</s>
<s>
The_AT second_MD objective_NN1 of_IO the_AT research_NN1 is_VBZ to_TO assess_VVI what_DDQ potential_JJ benefit_NN1 that_CST can_VM be_VBI gained_VVN if_CS an_AT1 implementation_NN1 process_NN1 is_VBZ successfully_RR done_VDN ._. 
</s>
<s>
The_AT research_NN1 will_VM be_VBI based_VVN on_II already_RR existing_JJ research_NN1 and_CC data_NN ._. 
</s>
<s>
Due_II21 to_II22 the_AT fact_NN1 that_CST implementation_NN1 of_IO ERP_NN1 systems_NN2 has_VHZ been_VBN a_AT1 current_JJ topic_NN1 for_IF almost_RR twenty_MC years_NNT2 ,_, there_EX exists_VVZ a_AT1 substantial_JJ amount_NN1 of_IO research_NN1 and_CC this_DD1 will_VM be_VBI more_DAR than_CSN adequate_JJ to_TO supply_VVI answers_NN2 for_IF my_APPGE objectives_NN2 ._. 
</s>
<s>
The_AT paper_NN1 is_VBZ organized_VVN into_II six_MC sections_NN2 ._. 
</s>
<s>
The_AT following_JJ section_NN1 explains_VVZ the_AT different_JJ steps_NN2 for_IF implementing_VVG an_AT1 ERP_NN1 system_NN1 and_CC presents_VVZ a_AT1 framework_NN1 for_IF it_PPH1 by_II Umble_NP1 ,_, Haftb_NP1 and_CC Umble_NP1 (_( Umble_NP1 ;_; Haft_NP1 ;_; &;_NULL Umble_NP1 ,_, 2003_MC )_) ._. 
</s>
<s>
This_DD1 section_NN1 will_VM also_RR present_VVI four_MC additional_JJ aspects_NN2 to_TO take_VVI into_II account_NN1 when_CS implementing_VVG an_AT1 ERPS_NN2 ._. 
</s>
<s>
The_AT third_MD section_NN1 covers_VVZ potential_JJ benefits_NN2 to_TO be_VBI gained_VVN from_II an_AT1 ERPS_NN2 ._. 
</s>
<s>
The_AT fifth_MD section_NN1 consists_VVZ of_IO an_AT1 analysis_NN1 of_IO the_AT results_NN2 ._. 
</s>
<s>
The_AT final_JJ section_NN1 is_VBZ conclusions_NN2 ,_, where_CS the_AT high_JJ points_NN2 of_IO the_AT research_NN1 are_VBR rendered_VVN ._. 
</s>
<s>
2_MC Implementing_VVG an_AT1 ERP_NN1 system_NN1 Many_DA2 potential_JJ advantages_NN2 await_VV0 the_AT managers_NN2 that_CST are_VBR willing_JJ to_TO engage_VVI the_AT process_NN1 of_IO implementing_VVG an_AT1 Enterprise_NN1 Resource_NN1 Planning_NN1 System_NN1 (_( ERPS_NP2 )_) ._. 
</s>
<s>
Complete_JJ packages_NN2 that_CST make_VV0 information_NN1 flow_NN1 seamless_JJ throughout_II the_AT organization_NN1 ,_, the_AT ERPS_NP2 is_VBZ indeed_RR a_AT1 tempting_JJ solution_NN1 for_IF managers_NN2 that_CST struggle_NN1 with_IW several_DA2 old_JJ21 fashioned_JJ22 unsynchronized_JJ information_NN1 systems_NN2 ._. 
</s>
<s>
Yet_RR ,_, the_AT implementation_NN1 has_VHZ proven_VVN itself_PPX1 to_TO be_VBI anything_PN1 else_RR but_CCB easy_JJ ._. 
</s>
<s>
Even_RR defining_VVG the_AT success_NN1 of_IO the_AT implementation_NN1 has_VHZ shown_VVN to_TO be_VBI a_AT1 difficult_JJ task_NN1 ._. 
</s>
<s>
Some_DD companies_NN2 have_VH0 experienced_VVN initial_JJ signals_NN2 indicating_VVG a_AT1 successful_JJ implementation_NN1 ,_, just_RR to_TO discover_VVI a_AT1 year_NNT1 later_RRR problems_NN2 that_CST show_VV0 anything_RR21 but_RR22 a_AT1 successful_JJ implementation_NN1 ._. 
</s>
<s>
Errors_NN2 like_II these_DD2 can_VM prove_VVI out_RP to_TO be_VBI very_RG costly_JJ for_IF the_AT company_NN1 and_CC is_VBZ something_PN1 that_CST any_DD manager_NN1 wishes_VVZ to_TO avoid_VVI ._. 
</s>
<s>
Unfortunately_RR most_DAT of_IO the_AT companies_NN2 that_CST choose_VV0 to_TO implement_VVI an_AT1 ERPS_NN2 encounter_VV0 errors_NN2 or_CC delays_NN2 during_II their_APPGE ERPS_NN2 implementation_NN1 processes_NN2 ._. 
</s>
<s>
(_( Larsen_NP1 &;_NULL Myers_NP1 ,_, 1999_MC )_) The_AT company_NN1 might_VM not_XX only_RR face_VVI economic_JJ losses_NN2 ._. 
</s>
<s>
A_AT1 poorly_JJ planned_JJ ERPS_NN2 implementation_NN1 process_NN1 can_VM result_VVI in_II disruption_NN1 in_II the_AT companys_NN2 culture_NN1 ,_, demand_VV0 for_IF extensive_JJ employee_NN1 training_NN1 and_CC even_RR results_VVZ in_II declining_JJ productivity_NN1 ._. 
</s>
<s>
In_II fact_NN1 research_NN1 show_VV0 that_CST 90%_NNU of_IO ERPS_NP2 implementation_NN1 processes_NN2 are_VBR over_II budget_NN1 or_CC delayed_VVD ._. 
</s>
<s>
The_AT losses_NN2 can_VM be_VBI extensive_JJ and_CC some_DD studies_NN2 have_VH0 shown_VVN that_CST the_AT losses_NN2 can_VM be_VBI persistent_JJ for_IF up_RG21 to_RG22 six_MC years_NNT2 ._. 
</s>
<s>
(_( Umble_VV0 ,_, Haft_NP1 ,_, &;_NULL Umble_NP1 ,_, 2003_MC )_) 2.1_MC Implementation_NN1 framework_NN1 ERPs_NN2 offer_VV0 substantial_JJ advantages_NN2 for_IF them_PPHO2 who_PNQS manage_VV0 to_TO navigate_VVI around_II the_AT pitfalls_NN2 which_DDQ are_VBR scattered_VVN along_II the_AT path_NN1 to_II success_NN1 ._. 
</s>
<s>
Achieving_VVG a_AT1 successful_JJ implementation_NN1 isnt_VV0 easy_JJ ._. 
</s>
<s>
Elisabeth_NP1 J_NP1 Umblea_NP1 ,_, Ronald_NP1 R_NP1 Haftb_NP1 ,_, M.Michael_NP1 Umblea_NP1 2003_MC have_VH0 made_VVN a_AT1 framework_NN1 to_II in_BCL21 order_BCL22 to_TO make_VVI ERPS_NP2 implementation_NN1 process_NN1 more_RGR likely_JJ to_TO succeed_VVI ._. 
</s>
<s>
The_AT framework_NN1 consists_VVZ of_IO 11_MC steps_NN2 :_: 1_MC1 ._. 
</s>
<s>
Review_VV0 the_AT pre-implementation_JJ process_NN1 to_II date_NN1 ._. 
</s>
<s>
Make_VV0 sure_JJ the_AT system_NN1 selection_NN1 process_NN1 has_VHZ been_VBN satisfactorily_RR completed_VVN and_CC all_DB factors_NN2 critical_JJ to_II implementation_NN1 success_NN1 are_VBR in_II place._NNU 2_MC ._. 
</s>
<s>
Install_VV0 and_CC test_VV0 any_DD new_JJ hardware_NN1 ._. 
</s>
<s>
Before_II attempting_VVG to_TO install_VVI any_DD software_NN1 ,_, it_PPH1 is_VBZ essential_JJ to_TO make_VVI sure_JJ that_CST the_AT hardware_NN1 is_VBZ reliable_JJ and_CC is_VBZ running_VVG as_RG expected._NNU 3_MC ._. 
</s>
<s>
Install_VV0 the_AT software_NN1 and_CC perform_VV0 the_AT computer_NN1 room_NN1 pilot_NN1 ._. 
</s>
<s>
A_AT1 technical_JJ support_NN1 person_NN1 from_II the_AT software_NN1 supplier_NN1 will_VM often_RR install_VVI the_AT software_NN1 and_CC run_VVI a_AT1 few_DA2 tests_NN2 to_TO make_VVI sure_JJ it_PPH1 is_VBZ installed_VVN correctly._NNU 4_MC ._. 
</s>
<s>
Attend_VV0 system_NN1 training_NN1 ._. 
</s>
<s>
Software_NN1 training_NN1 will_VM teach_VVI users_NN2 the_AT keystrokes_NN2 and_CC transactions_NN2 required_VVN to_TO run_VVI the_AT system._NNU 5_MC ._. 
</s>
<s>
Train_VV0 on_II the_AT conference_NN1 room_NN1 pilot_NN1 ._. 
</s>
<s>
The_AT conference_NN1 room_NN1 pilot_NN1 exercises_VVZ the_AT systems_NN2 and_CC tests_VVZ the_AT users_NN2 understanding_NN1 of_IO the_AT system_NN1 ._. 
</s>
<s>
The_AT project_NN1 team_NN1 creates_VVZ a_AT1 skeletal_JJ business_NN1 case_NN1 test_NN1 environment_NN1 which_DDQ takes_VVZ the_AT business_NN1 processes_NN2 from_II the_AT beginning_NN1 ,_, when_CS a_AT1 customer_NN1 order_NN1 is_VBZ received_VVN ,_, to_II the_AT end_NN1 ,_, when_CS the_AT customer_NN1 order_NN1 is_VBZ shipped._NNU 6_MC ._. 
</s>
<s>
Establish_VV0 security_NN1 and_CC necessary_JJ permissions_NN2 ._. 
</s>
<s>
Once_CS the_AT training_NN1 phase_NN1 is_VBZ finished_VVN ,_, during_II the_AT conference_NN1 room_NN1 pilot_NN1 ,_, begin_VV0 setting_VVG the_AT security_NN1 and_CC permissions_NN2 necessary_JJ to_TO ensure_VVI that_CST everyone_PN1 has_VHZ access_NN1 to_II the_AT information_NN1 they_PPHS2 need._NNU 7_MC ._. 
</s>
<s>
Ensure_VV0 that_CST all_DB data_NN bridges_NN2 are_VBR sufficiently_RR robust_JJ and_CC the_AT data_NN are_VBR sufficiently_RR accurate_JJ ._. 
</s>
<s>
The_AT data_NN brought_VVD across_RL from_II the_AT old_JJ system_NN1 must_VM be_VBI sufficiently_RR accurate_JJ for_IF people_NN to_TO start_VVI trusting_VVG the_AT new_JJ system._NNU 8_MC ._. 
</s>
<s>
Document_NN1 policies_NN2 and_CC procedures_NN2 ._. 
</s>
<s>
The_AT policy_NN1 statement_NN1 is_VBZ a_AT1 statement_NN1 of_IO what_DDQ is_VBZ intended_VVN to_TO be_VBI accomplished_VVN ;_; the_AT procedural_JJ steps_NN2 to_TO accomplish_VVI that_DD1 statement_NN1 may_VM be_VBI detailed_VVN in_II a_AT1 flowchart_NN1 format._NNU 9_MC ._. 
</s>
<s>
Bring_VV0 the_AT entire_JJ organization_NN1 on-line_JJ ,_, either_RR in_II a_AT1 total_JJ cutover_NN1 or_CC in_II a_AT1 phased_JJ approach_NN1 ._. 
</s>
<s>
In_II a_AT1 cold_JJ turkey_NN1 approach_NN1 ,_, the_AT whole_JJ company_NN1 is_VBZ eventually_RR brought_VVN onto_II the_AT new_JJ system_NN1 ._. 
</s>
<s>
The_AT entire_JJ company_NN1 prepares_VVZ for_IF the_AT cutover_NN1 date_NN1 ,_, which_DDQ would_VM preferably_RR be_VBI during_II a_AT1 plant_NN1 shutdown_NN1 of_IO one_MC1 to_II two_MC weeks_NNT2 ._. 
</s>
<s>
In_II a_AT1 phased_JJ approach_NN1 ,_, modules/products/plants_NN2 are_VBR brought_VVN on-line_JJ sequentially_RR ._. 
</s>
<s>
After_CS the_AT first_MD module/product/plant_NN1 is_VBZ live_JJ ,_, procedures_NN2 may_VM be_VBI refined_JJ and_CC adjusted_VVN ,_, then_RT the_AT remaining_JJ modules/products/plants_NN2 are_VBR sequentially_RR implemented_VVN ._. 
</s>
<s>
The_AT phased_JJ approach_NN1 may_VM allow_VVI for_IF improvements_NN2 to_TO be_VBI made_VVN during_II the_AT implementation._NNU 10_MC ._. 
</s>
<s>
Celebrate_VV0 ._. 
</s>
<s>
This_DD1 can_VM be_VBI the_AT most_RGT important_JJ step_NN1 ._. 
</s>
<s>
The_AT company_NN1 has_VHZ just_RR completed_VVN a_AT1 major_JJ project_NN1 ;_; the_AT celebration_NN1 recognizes_VVZ this_DD1 and_CC clearly_RR demonstrates_VVZ the_AT importance_NN1 of_IO the_AT project_NN1 to_II the_AT organization._NNU 11_MC ._. 
</s>
<s>
Improve_VV0 continually_RR ._. 
</s>
<s>
The_AT organization_NN1 can_VM only_RR absorb_VVI a_AT1 limited_JJ amount_NN1 of_IO change_NN1 during_II a_AT1 finite_JJ time_NNT1 period_NN1 ._. 
</s>
<s>
Change_NN1 is_VBZ an_AT1 on-going_JJ process_NN1 ;_; successful_JJ companies_NN2 understand_VV0 this_DD1 and_CC encourage_VV0 their_APPGE employees_NN2 to_TO use_VVI the_AT system_NN1 to_TO continue_VVI to_TO improve_VVI ._. 
</s>
<s>
(_( Umble_VV0 ,_, Haft_NP1 ,_, &;_NULL Umble_NP1 ,_, 2003_MC ,_, ss._NNU 249-250_MCMC )_) 2.2_MC Critical_JJ success_NN1 factors_NN2 (_( CSF_NP1 )_) Koh_NP1 ,_, Gunasekaran_NP1 ,_, &;_NULL Goodman_NP1 conducted_VVD a_AT1 research_NN1 in_II an_AT1 attempt_NN1 to_TO identify_VVI the_AT drivers_NN2 and_CC barriers_NN2 for_IF implementing_VVG a_AT1 ERP_NN1 system.They_NNU found_VVD that_CST he_PPHS1 drivers_NN2 for_IF implementing_VVG ERP_NN1 system_NN1 can_VM be_VBI acknowledge_VV0 as_RG strategically_RR or_CC operationally_RR oriented_VVD ._. 
</s>
<s>
Where_CS it_PPH1 was_VBDZ possible_JJ the_AT three_MC objectives_NN2 (_( barriers_NN2 ,_, drivers_NN2 and_CC critical_JJ success_NN1 factors_NN2 (_( CSF_NP1 )_) )_) were_VBDR analyzed_VVN against_II four_MC perspectives_NN2 that_CST were_VBDR affected_VVN by_II an_AT1 implementation_NN1 of_IO ERP_NP1 system_NN1 ._. 
</s>
<s>
The_AT four_MC perspectives_NN2 are_VBR :_: vendors/consultants_NN2 ,_, suppliers_NN2 ,_, central_JJ supply_NN1 chain_NN1 enterprises_NN2 and_CC customers_NN2 ._. 
</s>
<s>
All_DB of_IO these_DD2 perspectives_NN2 had_VHD specific_JJ need_NN1 and_CC knew_VVD how_RRQ they_PPHS2 would_VM like_VVI the_AT ERP_NN1 system_NN1 to_TO fulfill_VVI these_DD2 needs_NN2 ._. 
</s>
<s>
No_AT relationship_NN1 between_II the_AT ERPs_NP2 CSF_NP1 and_CC the_AT four_MC perspectives_NN2 were_VBDR found_VVN ._. 
</s>
<s>
This_DD1 indicates_VVZ that_CST it_PPH1 is_VBZ very_RG hard_JJ to_TO distinguish_VVI specific_JJ ERP_NP1 CSF_NP1 at_II the_AT beginning_NN1 of_IO a_AT1 products_NN2 lifecycle_NN1 ._. 
</s>
<s>
The_AT research_NN1 was_VBDZ however_RR capable_JJ of_IO identifying_VVG CSF_NP1 that_CST are_VBR required_VVN by_II an_AT1 organization_NN1 in_BCL21 order_BCL22 to_TO implement_VVI an_AT1 ERP_NN1 system_NN1 successfully_RR ._. 
</s>
<s>
(_( Koh_NN1 ,_, Gunasekaran_NP1 ,_, &;_NULL Goodman_NP1 ,_, 2011_MC )_) According_II21 to_II22 Tan_NN1 ,_, Carter-Steel_NP1 and_CC Toleman_NP1 (_( 2009_MC )_) the_AT most_RGT important_JJ five_MC CSFs_NP1 are_VBR senior_JJ management_NN1 support_NN1 ,_, relationship_NN1 with_IW vendors_NN2 ,_, change_VV0 in_II corporate_JJ culture_NN1 and_CC project_NN1 governance_NN1 and_CC execution_NN1 ._. 
</s>
<s>
(_( Tan_NN1 ,_, Carter-_JJ Steel_NN1 ,_, &;_NULL Toleman_NP1 ,_, 2009_MC )_) ._. 
</s>
<s>
One_MC1 of_IO the_AT key_JJ CSF_NP1 suggested_VVD by_II research_NN1 is_VBZ creating_VVG and_CC maintaining_VVG collaborative_JJ partner_NN1 relationship_NN1 ._. 
</s>
<s>
Therefore_RR a_AT1 good_JJ relationship_NN1 with_IW all_DB the_AT perspectives_NN2 ,_, that_CST were_VBDR mentioned_VVN earlier_RRR ,_, involved_JJ in_II the_AT ERP_NN1 system_NN1 is_VBZ crucial_JJ for_IF an_AT1 ERP_NN1 implementation_NN1 to_TO be_VBI successful_JJ ._. 
</s>
<s>
Other_JJ CSF_NP1 that_CST also_RR should_VM be_VBI accounted_VVN for_IF are_VBR :_: clear_JJ vision_NN1 ,_, robust_JJ planning_NN1 ,_, organizational_JJ resources_NN2 and_CC project_NN1 management_NN1 ._. 
</s>
<s>
(_( Koh_NN1 ,_, Gunasekaran_NP1 ,_, &;_NULL Goodman_NP1 ,_, 2011_MC )_) For_IF a_AT1 successful_JJ implementation_NN1 strong_JJ leadership_NN1 and_CC involvement_NN1 from_II the_AT top_JJ management_NN1 is_VBZ needed_VVN ._. 
</s>
<s>
The_AT management_NN1 should_VM have_VHI full_JJ understanding_NN1 for_IF ERP_NN1 systems_NN2 ,_, be_VBI able_JK to_TO rethink_VVI the_AT existing_JJ business_NN1 processes_NN2 and_CC fully_RR support_VV0 the_AT costs_NN2 ._. 
</s>
<s>
The_AT management_NN1 should_VM be_VBI seen_VVN as_II a_AT1 motivating_JJ factor_NN1 as_II31 well_II32 as_II33 a_AT1 driving_JJ force_NN1 for_IF the_AT rest_NN1 of_IO the_AT company_NN1 ._. 
</s>
<s>
(_( Koh_NN1 ,_, Gunasekaran_NP1 ,_, &;_NULL Goodman_NP1 ,_, 2011_MC )_) 2.3_MC Actors_NN2 involved_JJ in_II the_AT implementation_NN1 process_VV0 The_AT CSFs_NP1 can_VM be_VBI linked_VVN to_II specific_JJ actors_NN2 that_CST all_DB have_VH0 their_APPGE own_DA specific_JJ role_NN1 for_IF making_VVG the_AT implementation_NN1 process_VVI a_AT1 success_NN1 ._. 
</s>
<s>
However_RRQV the_AT actors_NN2 linked_VVN to_II the_AT CSFs_NP1 are_VBR company_NN1 specific_JJ ,_, and_CC are_VBR necessarily_RR not_XX the_AT same_DA in_II all_DB cases_NN2 for_IF implementation_NN1 ._. 
</s>
<s>
(_( Tan_NN1 ,_, Carter-_JJ Steel_NN1 ,_, &;_NULL Toleman_NP1 ,_, 2009_MC )_) The_AT actors_NN2 involved_JJ in_II the_AT implementation_NN1 usually_RR consist_VV0 of_IO a_AT1 team_NN1 that_CST is_VBZ responsible_JJ for_IF the_AT implementation_NN1 process_NN1 ._. 
</s>
<s>
Management_NN1 must_VM communicate_VVI frequently_RR with_IW the_AT implementation_NN1 team_NN1 ,_, but_CCB it_PPH1 is_VBZ also_RR important_JJ that_CST the_AT team_NN1 has_VHZ the_AT opportunity_NN1 to_TO make_VVI rapid_JJ decision_NN1 and_CC should_VM therefore_RR be_VBI enabled_VVN empowered_JJ decision_NN1 making_VVG ._. 
</s>
<s>
Usually_RR the_AT team_NN1 members_NN2 ,_, the_AT key_JJ actors_NN2 ,_, are_VBR information_NN1 system_NN1 experts_NN2 and_CC representatives_NN2 for_IF the_AT companys_NN2 different_JJ departments_NN2 and_CC represent_VV0 the_AT specific_JJ need_NN1 of_IO these_DD2 departments_NN2 ._. 
</s>
<s>
The_AT composition_NN1 of_IO the_AT teamwork_NN1 is_VBZ very_RG important_JJ throughout_II the_AT implementation_NN1 since_CS these_DD2 actors_NN2 are_VBR responsible_JJ for_IF the_AT most_RGT important_JJ activities_NN2 ._. 
</s>
<s>
(_( Francois_NP1 ,_, Bourgault_NP1 ,_, &;_NULL Pellerin_NP1 ,_, 2009_MC )_) The_AT team_NN1 is_VBZ responsible_JJ for_IF the_AT project_NN1 plan_NN1 throughout_II the_AT project_NN1 ._. 
</s>
<s>
They_PPHS2 plan_VV0 the_AT initial_NN1 ,_, detailed_JJ project_NN1 plan_NN1 and_CC are_VBR also_RR responsible_JJ for_IF the_AT overall_JJ schedule_NN1 ._. 
</s>
<s>
The_AT team_NN1 also_RR makes_VVZ sure_JJ that_CST all_DB resources_NN2 needed_VVN are_VBR available_JJ at_II the_AT time_NNT1 theyre_NN1 required_VVN ._. 
</s>
<s>
(_( Umble_VV0 ,_, Haft_NP1 ,_, &;_NULL Umble_NP1 ,_, 2003_MC )_) 2.4_MC Budgeting_VVG The_AT problem_NN1 with_IW any_DD new_JJ investment_NN1 is_VBZ getting_VVG the_AT budgeted_JJ right_NN1 ._. 
</s>
<s>
When_CS implementing_VVG a_AT1 new_JJ system_NN1 it_PPH1 is_VBZ clear_JJ that_CST some_DD kind_NN1 of_IO roof_NN1 should_VM be_VBI made_VVN in_II order_NN1 to_TO not_XX have_VHI expenses_NN2 running_VVG sky_NN1 high_JJ ._. 
</s>
<s>
IS_VBZ the_AT primary_JJ roof_NN1 for_IF expenses_NN2 relevant_JJ ,_, should_VM also_RR be_VBI considered_VVN ._. 
</s>
<s>
The_AT company_NN1 might_VM have_VHI to_TO invest_VVI more_RRR in_II the_AT project_NN1 that_CST they_PPHS2 initially_RR estimated_VVN ,_, but_CCB it_PPH1 is_VBZ important_JJ to_TO have_VHI a_AT1 budget_NN1 that_CST is_VBZ somewhat_RR flexible_JJ ._. 
</s>
<s>
If_CS the_AT company_NN1 has_VHZ already_RR invested_VVN money_NN1 in_II the_AT project_NN1 ,_, cost_NN1 of_IO raising_VVG the_AT budget_NN1 might_VM be_VBI smaller_JJR than_CSN the_AT cost_NN1 for_IF not_XX investing_VVG a_RR21 bit_RR22 more_RRR in_II the_AT project_NN1 ._. 
</s>
<s>
When_CS implementing_VVG something_PN1 that_CST has_VHZ nt_XX been_VBN done_VDN before_II that_DD1 is_VBZ custom_NN1 and_CC is_VBZ being_VBG made_VVN for_IF a_AT1 specific_JJ purpose_NN1 ,_, it_PPH1 is_VBZ very_RG hard_JJ to_TO estimate_VVI the_AT final_JJ cost_NN1 ._. 
</s>
<s>
According_II21 to_II22 research_NN1 by_II Hunton_NP1 ,_, Wright_NP1 ,_, &;_NULL Wright_NP1 (_( 2004_MC )_) the_AT financial_JJ auditors_NN2 were_VBDR reluctant_JJ to_TO consult_VVI IT_NN1 audit_NN1 during_II implementation_NN1 of_IO ERPS_NP2 ._. 
</s>
<s>
Results_NN2 showed_VVD that_DD1 risk_NN1 assessment_NN1 of_IO an_AT1 IT-audit_NN1 compared_VVN to_II a_AT1 financial_JJ audit_NN1 is_VBZ significantly_RR higher_JJR ._. 
</s>
<s>
This_DD1 suggests_VVZ that_CST the_AT type_NN1 of_IO auditors_NN2 should_VM interact_VVI in_BCL21 order_BCL22 to_TO minimize_VVI risk_NN1 of_IO failure_NN1 ._. 
</s>
<s>
A_AT1 reason_NN1 for_IF the_AT financial_JJ auditors_NN2 reluctance_NN1 to_TO consult_VVI IT_NN1 audits_NN2 could_VM be_VBI explained_VVN with_IW an_AT1 economical_JJ factor_NN1 ;_; when_CS financial_JJ auditors_NN2 consult_VV0 IT_PPH1 audits_VVZ this_DD1 increases_VVZ their_APPGE audit_NN1 costs_NN2 and_CC since_CS specialists_NN2 fee_NN1 usually_RR is_VBZ higher_JJR than_CSN normal_JJ fees_NN2 ,_, this_DD1 could_VM be_VBI accounted_VVN for_IF as_II a_AT1 reason_NN1 ._. 
</s>
<s>
(_( Hunton_NP1 ,_, Wright_NP1 ,_, &;_NULL Wright_NP1 ,_, 2004_MC )_) In_II the_AT research_NN1 done_VDN by_II Hunton_NP1 ,_, Wright_NP1 and_CC Wright_NP1 (_( 2004_MC )_) the_AT companies_NN2 had_VHD not_XX foreseen_VVN a_AT1 problem_NN1 like_II this_DD1 ._. 
</s>
<s>
By_II being_VBG reluctant_JJ to_TO consult_VVI the_AT IT_NN1 audits_VVZ the_AT financial_JJ audits_NN2 increased_VVD the_AT possibility_NN1 of_IO failure_NN1 ._. 
</s>
<s>
The_AT problem_NN1 could_VM have_VHI been_VBN avoided_VVN by_II adding_VVG IT_NN1 audits_NN2 to_II the_AT financial_JJ audits_NN2 team_VV0 for_IF the_AT implementation_NN1 process_NN1 or_CC even_RR budgeting_VVG consulting_JJ fees_NN2 in_II the_AT implementation_NN1 project_NN1 ._. 
</s>
<s>
We_PPIS2 can_VM conclude_VVI that_CST conducting_VVG a_AT1 budget_NN1 ,_, for_IF the_AT implementation_NN1 process_NN1 ,_, correctly_RR is_VBZ crucial._NNU 2.5_MC Reengineering_VVG the_AT company_NN1 As_CSA ways_NN2 of_IO conducting_VVG business_NN1 changes_NN2 ,_, it_PPH1 is_VBZ also_RR important_JJ to_TO change_VVI processes_NN2 in_II an_AT1 organization_NN1 to_TO support_VVI these_DD2 new_JJ ways_NN2 of_IO conducting_VVG business_NN1 ._. 
</s>
<s>
Producing_VVG ,_, collecting_VVG and_CC distributing_VVG information_NN1 in_II an_AT1 effective_JJ way_NN1 can_VM make_VVI a_AT1 business_NN1 more_RGR productive_JJ and_CC more_RGR valuable_JJ ._. 
</s>
<s>
It_PPH1 might_VM however_RR not_XX be_VBI enough_DD to_TO buy_VVI fancy_JJ computer_NN1 systems_NN2 to_TO make_VVI an_AT1 organization_NN1 more_RGR effective_JJ ._. 
</s>
<s>
Granlund_NP1 &;_NULL Malmi_NP1 conducted_VVD an_AT1 interesting_JJ research_NN1 on_II the_AT topic_NN1 ._. 
</s>
<s>
The_AT companies_NN2 that_CST were_VBDR involved_JJ in_II the_AT research_NN1 were_VBDR all_DB in_II the_AT implementation_NN1 face_NN1 of_IO an_AT1 ERPS_NN2 ._. 
</s>
<s>
All_DB of_IO the_AT companies_NN2 had_VHD only_RR implemented_VVN the_AT technical_JJ part_NN1 of_IO the_AT system_NN1 without_IW changing_VVG the_AT old_JJ processes_NN2 ._. 
</s>
<s>
They_PPHS2 were_VBDR only_RR speeding_VVG up_RP the_AT old_JJ process_NN1 with_IW better_JJR software_NN1 ._. 
</s>
<s>
A_AT1 reason_NN1 for_IF this_DD1 was_VBDZ given_VVN as_II an_AT1 economical_JJ factor_NN1 ._. 
</s>
<s>
The_AT companies_NN2 thought_VVD that_CST it_PPH1 would_VM be_VBI too_RG expensive_JJ to_TO change_VVI processes_NN2 and_CC implement_VVI a_AT1 new_JJ system_NN1 at_II the_AT same_DA time_NNT1 ._. 
</s>
<s>
The_AT managers_NN2 seemed_VVD to_TO be_VBI afraid_JJ of_IO the_AT risk_NN1 involving_VVG implementation_NN1 and_CC possible_JJ mistakes_NN2 that_CST could_VM turn_VVI out_RP to_TO be_VBI very_RG costly_JJ ._. 
</s>
<s>
I_PPIS1 wonder_VV0 if_CSW they_PPHS2 thought_VVD about_II what_DDQ could_VM potentially_RR be_VBI gained_VVN if_CS both_DB2 technical_JJ and_CC more_RGR practical_JJ change_NN1 would_VM have_VHI been_VBN done_VDN at_II the_AT same_DA time_NNT1 ._. 
</s>
<s>
It_PPH1 is_VBZ risky_JJ but_CCB as_CSA any_DD investment_NN1 done_VDN ,_, the_AT risk_NN1 of_IO failure_NN1 and_CC victory_NN1 should_VM be_VBI calculated_VVN so_CS21 that_CS22 the_AT possible_JJ gain_NN1 or_CC loss_NN1 can_VM be_VBI measured_VVN in_II hard_JJ numbers_NN2 ._. 
</s>
<s>
Implementing_VVG one_MC1 face_NN1 at_II the_AT time_NNT1 might_VM be_VBI less_RGR risky_JJ ,_, but_CCB is_VBZ it_PPH1 really_RR less_RGR expensive_JJ and_CC how_RGQ much_DA1 could_VM the_AT company_NN1 gain_VVI if_CSW the_AT implementation_NN1 would_VM be_VBI successful_JJ for_IF both_DB2 parts_NN2 ?_? 
</s>
<s>
(_( Granlund_NP1 &;_NULL Malmi_NP1 ,_, 2002_MC )_) 3_MC Benefits_NN2 to_TO be_VBI gained_VVN from_II a_AT1 successful_JJ implementation_NN1 The_AT benefits_NN2 provided_VVN by_II ERPs_NN2 can_VM be_VBI broken_VVN down_RP into_II two_MC categories_NN2 :_: 1_MC1 )_) a_AT1 unified_JJ enterprise_NN1 view_NN1 of_IO the_AT business_NN1 that_CST encompasses_VVZ all_DB functions_NN2 and_CC departments_NN2 ;_; and_CC 2_MC )_) an_AT1 enterprise_NN1 database_NN1 where_CS all_DB business_NN1 transactions_NN2 are_VBR entered_VVN ,_, recorded_VVD ,_, processed_VVD ,_, monitored_VVD ,_, and_CC reported_VVD ._. 
</s>
<s>
(_( Umble_VV0 ,_, Haft_NP1 ,_, &;_NULL Umble_NP1 ,_, 2003_MC )_) This_DD1 section_NN1 will_VM cover_VVI what_DDQ kinds_NN2 of_IO benefits_NN2 an_AT1 implementation_NN1 can_VM bring_VVI a_AT1 company._NNU 3.1_MC ERP_NN1 benefits_NN2 in_II five_MC dimensions_NN2 Most_DAT of_IO the_AT benefits_NN2 gained_VVN from_II an_AT1 ERPS_NN2 implementation_NN1 can_VM be_VBI accounted_VVN for_IF as_RG decreased_JJ in_II the_AT companys_NN2 expenses_NN2 and_CC in_II an_AT1 overall_JJ increased_JJ efficiency_NN1 ._. 
</s>
<s>
Shang_VV0 and_CC Seddon_NP1 (_( 2002_MC )_) present_JJ benefits_NN2 gained_VVN by_II an_AT1 ERP_NN1 implementation_NN1 in_II five_MC dimensions_NN2 ._. 
</s>
<s>
The_AT five_MC dimensions_NN2 accounted_VVN for_IF are_VBR :_: Operational_JJ Managerial_JJ Strategic_JJ IT_NN1 infrastructure_NN1 Organizational_JJ Operation_NN1 benefits_NN2 are_VBR mainly_RR reduction_NN1 of_IO cost_NN1 and_CC cycle_NN1 time_NNT1 ._. 
</s>
<s>
Faster_JJR cycle_NN1 time_NNT1 means_VVZ that_CST less_DAR labor_NN1 hours_NNT2 is_VBZ needed_VVN for_IF producing_VVG a_AT1 product_NN1 ._. 
</s>
<s>
By_II minimizing_VVG cycle_NN1 times_NNT2 more_RRR products_NN2 can_VM be_VBI made_VVN in_II a_AT1 shorter_JJR time_NNT1 space_NN1 ._. 
</s>
<s>
The_AT produced_JJ products_NN2 become_VV0 cheaper_JJR for_IF the_AT company_NN1 by_II increased_JJ efficiency_NN1 and_CC hence_RR adding_VVG to_II better_JJR results_NN2 ._. 
</s>
<s>
Managerial_JJ benefits_NN2 are_VBR better_JJR performance_NN1 ,_, decision_NN1 making_VVG and_CC resource_VV0 management_NN1 ._. 
</s>
<s>
ERP_NP1 system_NN1 enables_VVZ the_AT managers_NN2 to_TO have_VHI information_NN1 in_II real_JJ time_NNT1 ._. 
</s>
<s>
Informed_JJ managers_NN2 are_VBR able_JK to_TO more_RRR accurate_JJ assessments_NN2 of_IO a_AT1 situation_NN1 and_CC make_VV0 better_JJR decisions_NN2 for_IF the_AT company_NN1 ._. 
</s>
<s>
Strategic_JJ benefits_NN2 can_VM be_VBI accounted_VVN for_IF as_II the_AT new_JJ system_NN1 allows_VVZ the_AT managers_NN2 to_TO develop_VVI better_JJR strategic_JJ plans_NN2 for_IF the_AT company_NN1 ._. 
</s>
<s>
IT_NN1 infrastructure_NN1 experiences_NN2 benefits_NN2 by_II cost_NN1 reduction_NN1 and_CC increased_JJ capability_NN1 ._. 
</s>
<s>
Organizational_JJ benefits_NN2 can_VM be_VBI seen_VVN as_II a_AT1 change_NN1 in_II processes_NN2 ,_, employee_NN1 empowerment_NN1 and_CC in_II increased_JJ moral_JJ and_CC satisfaction_NN1 of_IO the_AT employees_NN2 ._. 
</s>
<s>
(_( Shang_NP1 &;_NULL Seddon_NP1 ,_, 2002_MC )_) For_REX21 example_REX22 Granlund_NP1 &;_NULL Malmi_NP1 found_VVD that_CST an_AT1 ERPS_NN2 implementation_NN1 made_VVD it_PPH1 possible_JJ for_IF accountants_NN2 to_TO spend_VVI less_DAR time_NNT1 doing_VDG routine_NN1 tasks_NN2 and_CC more_DAR time_NNT1 analyzing_VVG data_NN ._. 
</s>
<s>
In_II some_DD cases_NN2 the_AT accountants_NN2 were_VBDR given_VVN new_JJ tasks_NN2 and_CC in_II some_DD cases_NN2 this_DD1 even_RR led_VVN to_II a_AT1 reduction_NN1 of_IO accountants_NN2 in_II the_AT companies_NN2 ._. 
</s>
<s>
(_( Granlund_NP1 &;_NULL Malmi_NP1 ,_, 2002_MC )_) 3.2_MC Estimating_VVG value_NN1 gained_VVN by_II an_AT1 ERPS_NN2 implementation_NN1 One_MC1 of_IO the_AT most_RGT interesting_JJ issues_NN2 of_IO accounting_NN1 and_CC information_NN1 systems_NN2 is_VBZ the_AT measuring_NN1 of_IO value_NN1 of_IO Information_NN1 Technology_NN1 (_( IT_NN1 )_) ._. 
</s>
<s>
Several_DA2 researchers_NN2 have_VH0 tried_VVN to_TO come_VVI up_RP with_IW a_AT1 measurement_NN1 that_CST would_VM properly_RR reflect_VVI the_AT value_NN1 increase_VV0 that_DD1 is_VBZ due_II21 to_II22 an_AT1 ERPS_NN2 implementation_NN1 ._. 
</s>
<s>
So_RG far_RR research_NN1 has_VHZ not_XX made_VVN a_AT1 significant_JJ breakthrough_NN1 ._. 
</s>
<s>
The_AT topic_NN1 is_VBZ still_RR being_VBG explored_VVN ._. 
</s>
<s>
Davern_VV0 and_CC Wilkin_NP1 (_( 2010_MC )_) explored_VVD two_MC approaches_NN2 to_TO estimate_VVI the_AT value_NN1 that_CST can_VM be_VBI gained_VVN from_II a_AT1 successful_JJ implementation_NN1 ._. 
</s>
<s>
The_AT first_MD approach_NN1 is_VBZ objective_JJ approach_NN1 ._. 
</s>
<s>
The_AT data_NN is_VBZ based_VVN on_II hard_JJ numbers_NN2 such_II21 as_II22 ,_, capital_NN1 market_NN1 reactions_NN2 and_CC comparative_JJ analysis_NN1 of_IO published_JJ financial_JJ reports_NN2 ._. 
</s>
<s>
The_AT problem_NN1 is_VBZ that_CST a_AT1 change_NN1 in_II market_NN1 value_NN1 is_VBZ hard_JJ to_TO connect_VVI directly_RR to_II the_AT change_NN1 in_II IT_NN1 as_CSA market_NN1 value_NN1 is_VBZ constantly_RR affected_VVN by_II other_JJ news_NN1 at_II the_AT market_NN1 as_RR21 well_RR22 ._. 
</s>
<s>
Is_VBZ the_AT change_NN1 in_II market_NN1 value_NN1 really_RR a_AT1 result_NN1 of_IO IT_NN1 related_VVD managerial_JJ decision_NN1 ,_, or_CC is_VBZ it_PPH1 a_AT1 result_NN1 of_IO some_DD other_JJ noise_NN1 on_II the_AT market_NN1 ._. 
</s>
<s>
(_( Daver_NP1 &;_NULL Wilkin_NP1 ,_, 2010_MC )_) Evaluate_VV0 if_CSW an_AT1 implementation_NN1 has_VHZ been_VBN successful_JJ can_VM be_VBI a_AT1 difficult_JJ and_CC cumbersome_JJ task_NN1 ._. 
</s>
<s>
The_AT problem_NN1 is_VBZ defining_VVG what_DDQ success_NN1 is_VBZ ._. 
</s>
<s>
Researchers_NN2 have_VH0 tried_VVN to_TO resolve_VVI this_DD1 problem_NN1 by_II benchmarking_NN1 and_CC by_II setting_VVG certain_JJ goals_NN2 for_IF specific_JJ attribute_NN1 ._. 
</s>
<s>
Thomas_NP1 (_( 2007_MC )_) conducted_VVD a_AT1 research_NN1 in_II which_DDQ the_AT result_NN1 showed_VVD that_CST the_AT greatest_JJT reductions_NN2 are_VBR made_VVN in_II scheduling_NN1 and_CC planning_NN1 (_( 50_MC %_NNU )_) ,_, reduction_NN1 in_II production_NN1 time_NNT1 (_( 10_MC %_NNU )_) ,_, in_II inventory_NN1 (_( 10_MC %_NNU )_) and_CC in_II delayed_JJ delivery_NN1 times_NNT2 (_( 25_MC %_NNU )_) ._. 
</s>
<s>
The_AT research_NN1 also_RR showed_VVD that_CST the_AT companies_NN2 that_CST implemented_VVD an_AT1 ERP_NN1 system_NN1 managed_VVD to_TO meet_VVI their_APPGE return_NN1 on_II investment_NN1 in_II 32_MC ,_, 5_MC %_NNU of_IO the_AT time_NNT1 and_CC reach_VV0 their_APPGE attributes_NN2 14_MC ,_, 3_MC %_NNU of_IO the_AT time_NNT1 ._. 
</s>
<s>
(_( Thomas_NP1 ,_, 2007_MC )_) The_AT second_MD approach_NN1 explored_VVN by_II Davern_NP1 and_CC Wilkin_NP1 (_( 2010_MC )_) is_VBZ based_VVN on_II behavioral_JJ science_NN1 ._. 
</s>
<s>
The_AT idea_NN1 is_VBZ that_CST the_AT end-users_NN2 and_CC stakeholders_NN2 are_VBR to_TO provide_VVI a_AT1 better_JJR assessment_NN1 of_IO what_DDQ value_VV0 the_AT implementation_NN1 of_IO an_AT1 IT_NN1 system_NN1 adds_VVZ to_II the_AT product_NN1 ._. 
</s>
<s>
The_AT problem_NN1 here_RL however_RR is_VBZ that_DD1 human_JJ judgment_NN1 can_VM not_XX be_VBI seen_VVN as_II an_AT1 objective_JJ measurement_NN1 ,_, and_CC can_VM be_VBI stated_VVN as_II a_AT1 perceptual_JJ measurement_NN1 ._. 
</s>
<s>
Even_CS21 though_CS22 researchers_NN2 havent_NN1 been_VBN able_JK to_TO conduct_VVI a_AT1 research_NN1 that_CST could_VM supply_VVI accurate_JJ results_NN2 on_II this_DD1 topic_NN1 it_PPH1 should_VM be_VBI recognized_VVN that_DD1 value_NN1 is_VBZ created_VVN on_II this_DD1 level_NN1 as_RR21 well_RR22 ._. 
</s>
<s>
(_( Daver_NP1 &;_NULL Wilkin_NP1 ,_, 2010_MC )_) A_ZZ1 business_NN1 organizations_NN2 task_NN1 is_VBZ to_TO create_VVI value_NN1 and_CC then_RT capture_VVI as_RG much_DA1 of_IO that_DD1 value_NN1 as_CSA it_PPH1 can_VM and_CC handing_VVG it_PPH1 over_RP to_II the_AT owners_NN2 ._. 
</s>
<s>
Giving_VVG the_AT end_NN1 user_NN1 more_DAR value_NN1 can_VM however_RR result_VVI in_II a_AT1 better_JJR relationship_NN1 with_IW the_AT customer_NN1 ._. 
</s>
<s>
If_CS the_AT company_NN1 manages_VVZ to_TO gain_VVI the_AT customers_NN2 loyalty_NN1 ,_, chances_NN2 are_VBR higher_JJR the_AT old_JJ consumer_NN1 will_VM become_VVI a_AT1 new_JJ costumer_NN1 again_RT ._. 
</s>
<s>
If_CS so_RR ,_, the_AT company_NN1 has_VHZ managed_VVN to_TO establish_VVI a_AT1 long-term_JJ relationship_NN1 with_IW the_AT consumer_NN1 and_CC this_DD1 relationship_NN1 will_VM show_VVI monetary_JJ benefit_NN1 several_DA2 times_NNT2 for_IF the_AT company_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ why_RRQ an_AT1 integrated_JJ research_NN1 is_VBZ crucial_JJ for_IF estimating_VVG value_NN1 ._. 
</s>
<s>
Once_RR created_VVN ,_, the_AT value_NN1 created_VVN does_VDZ exist_VVI ._. 
</s>
<s>
We_PPIS2 just_RR have_VH0 to_TO find_VVI a_AT1 way_NN1 to_TO see_VVI all_DB of_IO it._NNU 4_MC Analysis_NN1 and_CC discussion_NN1 Who_PNQS captures_VVZ the_AT value_NN1 that_CST is_VBZ created_VVN by_II IT_NN1 ?_? 
</s>
<s>
The_AT question_NN1 is_VBZ hard_JJ to_TO answer_VVI because_CS the_AT stakeholders_NN2 probably_RR will_VM assess_VVI the_AT value_NN1 differently_RR than_CSN managers_NN2 or_CC think_VV0 that_CST no_AT value_NN1 was_VBDZ added_VVN at_RR21 all_RR22 ._. 
</s>
<s>
This_DD1 makes_VVZ measuring_VVG value_NN1 in_II31 terms_II32 of_II33 hard_JJ numbers_NN2 very_RG hard_RR ._. 
</s>
<s>
The_AT value_NN1 in_II the_AT stock_NN1 price_NN1 might_VM not_XX show_VVI after_II implementation_NN1 ,_, since_CS the_AT increase_NN1 in_II efficiency_NN1 isnt_NN1 shown_VVN in_II the_AT companys_NN2 result_VV0 the_AT very_RG next_MD balance_NN1 sheet_NN1 ,_, due_II21 to_II22 the_AT cost_NN1 of_IO investment_NN1 ._. 
</s>
<s>
Despite_II this_DD1 ,_, the_AT value_NN1 created_VVN for_IF the_AT owners_NN2 is_VBZ probably_RR still_RR the_AT easiest_JJT value_NN1 to_TO estimate_VVI ._. 
</s>
<s>
By_II comparing_VVG residual_JJ income_NN1 before_II a_AT1 managerial_JJ IT_NN1 decision_NN1 ,_, an_AT1 estimation_NN1 of_IO value_NN1 increase_NN1 or_CC decrease_NN1 is_VBZ gained_VVN ._. 
</s>
<s>
The_AT question_NN1 remains_VVZ if_CS we_PPIS2 can_VM consider_VVI this_DD1 to_TO be_VBI reliable_JJ since_CS the_AT stock_NN1 prices_NN2 could_VM also_RR be_VBI influenced_VVN by_II other_JJ noises_NN2 on_II the_AT market_NN1 as_RR21 well_RR22 ._. 
</s>
<s>
The_AT main_JJ question_NN1 that_CST arises_VVZ when_CS reading_VVG this_DD1 essay_NN1 is_VBZ :_: Is_VBZ implementing_VVG an_AT1 ERP_NN1 system_NN1 worth_II the_AT risks_NN2 ?_? 
</s>
<s>
Obviously_RR this_DD1 is_VBZ a_AT1 question_NN1 that_CST no_AT research_NN1 can_VM provide_VVI an_AT1 absolute_JJ answer_NN1 for_IF ._. 
</s>
<s>
The_AT advantages_NN2 that_CST can_VM be_VBI gained_VVN depend_VV0 on_RP to_II which_DDQ extent_NN1 a_AT1 company_NN1 is_VBZ willing_JJ to_TO implement_VVI the_AT system_NN1 ._. 
</s>
<s>
As_CSA previously_RR shown_VVN only_RR 32_MC ,_, 5_MC %_NNU meet_VV0 their_APPGE return_NN1 on_II investment_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ a_AT1 very_RG small_JJ number_NN1 that_CST implies_VVZ that_CST the_AT investment_NN1 in_II ERP_NP1 system_NN1 in_II the_AT majority_NN1 of_IO times_NNT2 leads_VVZ to_II economic_JJ losses_NN2 ._. 
</s>
<s>
Greater_JJR benefits_NN2 can_VM be_VBI gained_VVN if_CS the_AT company_NN1 chooses_VVZ to_TO implement_VVI both_DB2 the_AT technical_JJ part_NN1 of_IO the_AT system_NN1 and_CC change_VV0 their_APPGE processes_NN2 ._. 
</s>
<s>
It_PPH1 all_DB comes_VVZ down_RP to_II how_RGQ much_DA1 risk_NN1 the_AT managers_NN2 and_CC the_AT shareholders_NN2 are_VBR willing_JJ to_TO take_VVI ._. 
</s>
<s>
With_IW greater_JJR risk_NN1 comes_VVZ greater_JJR victory_NN1 ,_, but_CCB if_CS failure_NN1 is_VBZ meet_VV0 it_PPH1 will_VM be_VBI equally_RR destructive_JJ for_IF the_AT company_NN1 ._. 
</s>
<s>
The_AT future_JJ trend_NN1 in_II enterprise_NN1 systems_NN2 are_VBR leaning_VVG towards_II greater_JJR SC_FO collaboration_NN1 and_CC is_VBZ more_DAR web_NN1 orientated_VVN ._. 
</s>
<s>
(_( Tan_NN1 ,_, Carter-_JJ Steel_NN1 ,_, &;_NULL Toleman_NP1 ,_, 2009_MC )_) I_PPIS1 suggest_VV0 that_CST if_CS one_MC1 of_IO the_AT key_JJ CSFs_NP1 is_VBZ the_AT relationship_NN1 the_AT organization_NN1 has_VHZ with_IW its_APPGE perspectives_NN2 ,_, more_DAR studies_NN2 should_VM be_VBI made_VVN also_RR from_II the_AT perspectives_NN2 point_NN1 of_IO view_NN1 ._. 
</s>
<s>
Most_DAT of_IO the_AT studies_NN2 made_VVD ,_, concerning_VVG implementation_NN1 of_IO ERP_NN1 systems_NN2 ,_, are_VBR made_VVN from_II the_AT implementing_VVG organizations_NN2 point_NN1 of_IO view_NN1 ._. 
</s>
<s>
I_PPIS1 suggest_VV0 that_CST more_DAR research_NN1 need_NN1 to_TO be_VBI done_VDN with_IW focus_NN1 on_II developing_VVG lean_JJ relationships_NN2 with_IW collaborating_VVG partners._NNU 5_MC Conclusions_NN2 The_AT companies_NN2 of_IO today_RT have_VH0 adjusted_VVN to_II the_AT new_JJ ways_NN2 of_IO doing_VDG business_NN1 ._. 
</s>
<s>
Keeping_VVG up_RP with_IW the_AT new_JJ ways_NN2 of_IO ,_, for_REX21 example_REX22 ,_, serving_VVG customer_NN1 on_II the_AT internet_NN1 has_VHZ forced_VVN companies_NN2 to_TO accept_VVI new_JJ innovated_JJ ideas_NN2 ._. 
</s>
<s>
During_II the_AT last_MD twenty_MC years_NNT2 managers_NN2 have_VH0 turned_VVN to_II information_NN1 systems_NN2 in_II hope_NN1 to_TO create_VVI a_AT1 more_RGR competitive_JJ business_NN1 ._. 
</s>
<s>
ERP_VV0 systems_NN2 offer_VV0 a_AT1 multimodule_NN1 software_NN1 system_NN1 that_CST combines_VVZ all_DB business_NN1 processes_NN2 into_II one_MC1 single_JJ software_NN1 system_NN1 ,_, needing_VVG only_RR on_II database_NN1 ._. 
</s>
<s>
The_AT potential_JJ benefits_NN2 to_TO be_VBI gained_VVN can_VM definitely_RR increase_VVI the_AT companys_NN2 competitive_JJ advantage_NN1 but_CCB it_PPH1 comes_VVZ at_II a_AT1 price_NN1 ._. 
</s>
<s>
The_AT risks_NN2 are_VBR equally_RR high_JJ and_CC potential_JJ errors_NN2 have_VH0 high_JJ chance_NN1 of_IO becoming_VVG very_RG costly_JJ ._. 
</s>
<s>
In_II this_DD1 essay_NN1 we_PPIS2 have_VH0 explored_VVN a_AT1 framework_NN1 for_IF ERPS_NN2 implementation_NN1 by_II Umble_NP1 ,_, Haft_NP1 ,_, &;_NULL Umble_NP1 (_( 2003_MC )_) ._. 
</s>
<s>
In_II31 addition_II32 to_II33 the_AT framework_NN1 the_AT essay_NN1 also_RR gaised_JJ uppon_NN1 four_MC other_JJ aspects_NN2 to_TO consider_VVI during_II an_AT1 implementation_NN1 ._. 
</s>
<s>
The_AT therd_NN1 section_NN1 rendered_VVN benefits_NN2 to_TO be_VBI gained_VVN when_CS an_AT1 ERPS_NN2 is_VBZ implemented_VVN successfully_RR ._. 
</s>
<s>
The_AT section_NN1 also_RR covered_VVN reseach_NN1 done_VDN on_II estimation_NN1 of_IO the_AT value_NN1 created_VVN due_II21 to_II22 an_AT1 implemenatation_NN1 of_IO an_AT1 ERP_NN1 system_NN1 ._. 
</s>
<s>
The_AT fourth_MD section_NN1 offered_VVD an_AT1 analytical_JJ diskussion_NN1 of_IO the_AT findings_NN2 ._. 
</s>
<s>
We_PPIS2 concluded_VVD that_CST estimating_VVG the_AT created_JJ value_NN1 by_II an_AT1 ERP_NN1 implementaiton_NN1 is_VBZ ,_, for_IF time_NNT1 being_NN1 and_CC measures_NN2 availble_VV0 ,_, a_AT1 very_RG difficult_JJ task_NN1 that_CST is_VBZ yet_RR to_TO be_VBI conqured_VVN ._. 
</s>
