<s>
Introduction_NN1 The_AT recent_JJ rise_NN1 of_IO social_JJ media_NN has_VHZ helped_VVN companies_NN2 and_CC other_JJ causes_NN2 in_II building_NN1 and_CC maintaining_VVG online_JJ brand_NN1 communities_NN2 ._. 
</s>
<s>
In_II the_AT world_NN1 of_IO marketing_NN1 ,_, social_JJ media_NN is_VBZ the_AT new_JJ black_JJ ._. 
</s>
<s>
The_AT plethora_NN1 of_IO different_JJ social_JJ media_NN services_NN2 and_CC the_AT segmentation_NN1 of_IO the_AT online_JJ crowd_NN1 has_VHZ its_APPGE downsides_NN2 :_: choice_NN1 overload_NN1 ._. 
</s>
<s>
Surplus_NN1 is_VBZ often_RR a_AT1 desired_JJ feature_NN1 ,_, but_CCB when_CS talking_VVG about_II managing_VVG your_APPGE online_JJ community_NN1 ,_, every_AT1 added_JJ service_NN1 needs_NN2 looking_VVG after_II ._. 
</s>
<s>
There_EX is_VBZ a_AT1 library_NN1 of_IO research_NN1 on_II online_JJ communities_NN2 and_CC social_JJ media_NN ,_, from_II analysing_VVG online_JJ brand_NN1 community_NN1 participation_NN1 (_( Madupu_NP1 ,_, 2006_MC )_) ,_, to_II longitudinal_JJ studies_NN2 of_IO social_JJ media_NN usage_NN1 by_II the_AT Fortune_NN1 500_MC companies_NN2 (_( Barnes_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
Most_DAT theoretical_JJ research_NN1 focuses_VVZ on_II communication_NN1 and_CC consumer_NN1 behaviour_NN1 ,_, while_CS practical_JJ research_NN1 mainly_RR analyses_VVZ corporate_JJ level_JJ social_JJ media_NN usage_NN1 ._. 
</s>
<s>
Apart_II21 from_II22 the_AT horde_NN1 of_IO ,_, more_RGR or_CC less_RGR generic_JJ ,_, social_JJ media_NN best_VV0 practice_NN1 guides_NN2 found_VVD online_RR ,_, little_JJ research_NN1 has_VHZ been_VBN done_VDN on_II smaller_JJR segments_NN2 ._. 
</s>
<s>
How_RRQ do_VD0 small_JJ brands_NN2 ,_, with_IW a_AT1 very_RG constrained_JJ amount_NN1 of_IO time_NNT1 and_CC money_NN1 ,_, choose_VV0 to_TO allocate_VVI their_APPGE social_JJ media_NN resources_NN2 ?_? 
</s>
<s>
For_IF this_DD1 paper_NN1 I_PPIS1 have_VH0 chosen_VVN to_TO analyse_VVI the_AT social_JJ media_NN and_CC online_JJ brand_NN1 community_NN1 management_NN1 methods_NN2 implemented_VVN by_II stunt_NN1 and_CC prank_NN1 groups_NN2 ._. 
</s>
<s>
Most_DAT stunt_NN1 and_CC prank_NN1 groups_NN2 have_VH0 evolved_VVN from_II amateur_NN1 to_II professional_NN1 level_NN1 quite_RG organically_RR ,_, and_CC this_DD1 can_VM be_VBI seen_VVN in_II their_APPGE online_JJ brand_NN1 management_NN1 and_CC fan_VV0 interaction_NN1 ._. 
</s>
<s>
For_IF these_DD2 groups_NN2 ,_, the_AT loyal_JJ fan_NN1 community_NN1 plays_VVZ a_AT1 central_JJ part_NN1 ,_, arguably_RR even_RR more_RGR so_RR than_CSN in_II the_AT music_NN1 industry_NN1 ._. 
</s>
<s>
This_DD1 makes_VVZ stunt_NN1 and_CC prank_NN1 groups_NN2 an_AT1 excellent_JJ segment_NN1 for_IF an_AT1 exploratory_JJ study_NN1 ._. 
</s>
<s>
The_AT rest_NN1 of_IO this_DD1 research_NN1 paper_NN1 is_VBZ divided_VVN into_II three_MC sections_NN2 ._. 
</s>
<s>
The_AT first_MD section_NN1 discusses_VVZ online_JJ brand_NN1 communities_NN2 and_CC social_JJ media_NN on_II a_AT1 theoretical_JJ level_NN1 ._. 
</s>
<s>
The_AT second_MD section_NN1 identifies_VVZ the_AT chosen_JJ stunt_NN1 and_CC prank_NN1 groups_NN2 ,_, describes_VVZ the_AT survey_NN1 method_NN1 ,_, and_CC presents_VVZ the_AT results_NN2 ._. 
</s>
<s>
The_AT final_JJ section_NN1 summarises_VVZ and_CC analyses_VVZ the_AT results_NN2 ,_, and_CC renders_VVZ the_AT conclusions_NN2 ._. 
</s>
<s>
Brand_NN1 communities_NN2 BUILDING_VVG COMMUNITIES_NN2 FOR_IF PERFORMING_VVG BRANDS_NN2 ._. 
</s>
<s>
WHAT_DDQ EFFECT_VV0 SOCIAL_JJ MEDIA_NN HAS_VHZ ON_II COMMUNITY_NN1 BUILDING_NN1 ._. 
</s>
<s>
WHICH_DDQ ARE_VBR THE_AT CENTRAL_JJ SOCIAL_JJ MEDIA_NN TOOLS_NN2 AND_CC HOW_RRQ ARE_VBR THEY_PPHS2 IMPLEMENTED_VVN ON_II WEB_NN1 PAGES_NN2 ._. 
</s>
<s>
Stunt_VV0 and_CC prank_NN1 groups_NN2 WHAT_DDQ I_PPIS1 CONSIDER_VV0 STUNT_NN1 AND_CC PRANK_NN1 GROUPS_NN2 &;_NULL WHICH_DDQ ONES_NN2 I_PPIS1 CHOSE_VVD ._. 
</s>
<s>
Jackass_NN1 is_VBZ the_AT most_RGT well_JJ known_JJ American_JJ stunt_NN1 and_CC prank_NN1 group_NN1 ,_, originally_RR shown_VVN on_II MTV_NP1 for_IF three_MC seasons_NNT2 between_II 2000_MC and_CC 2002_MC ._. 
</s>
<s>
Although_CS the_AT television_NN1 series_NN ended_VVN in_II 2002_MC the_AT brand_NN1 has_VHZ stayed_VVN active_JJ ,_, releasing_VVG three_MC feature_NN1 films_NN2 since_II then_RT ,_, of_IO which_DDQ the_AT last_MD ,_, Jackass_VV0 3D_NNU ,_, was_VBDZ released_VVN in_II late_JJ 2010_MC ._. 
</s>
<s>
(_( Wikipedia_NN1 ,_, 2011_MC )_) Nitro_NN1 Circus_NN1 is_VBZ an_AT1 American_JJ stunt_NN1 group_NN1 doing_VDG mainly_RR dirt_NN1 bike_NN1 and_CC other_JJ motor-based_JJ stunts_NN2 ._. 
</s>
<s>
Their_APPGE original_JJ show_NN1 was_VBDZ a_AT1 miniseries_NN2 Fuel_NN1 TV_NN1 in_II 2006_MC ,_, but_CCB they_PPHS2 had_VHD a_AT1 two_MC season_NNT1 recurring_JJ show_NN1 on_II MTV_NP1 during_II 2009_MC ._. 
</s>
<s>
According_II21 to_II22 Wikipedia_NP1 ,_, a_AT1 Nitro_NN1 Circus_NN1 movie_NN1 might_VM be_VBI released_VVN during_II the_AT summer_NNT1 of_IO 2011_MC ._. 
</s>
<s>
The_AT group_NN1 also_RR does_VDZ live_VVI shows_NN2 ;_; the_AT latest_JJT live_JJ tour_NN1 was_VBDZ in_II Australia_NP1 in_II 2010_MC ._. 
</s>
<s>
(_( Wikipedia_NN1 ,_, 2011_MC )_) Dirty_JJ Sanches_NN2 is_VBZ a_AT1 British_JJ group_NN1 doing_VDG extreme_JJ and_CC dangerous_JJ stunts_NN2 and_CC pranks_NN2 ._. 
</s>
<s>
Their_APPGE show_NN1 was_VBDZ originally_RR show_VV0 on_II MTV_NP1 UK_NP1 ,_, from_II 2003_MC to_II 2007_MC Jackass_NP1 Nitro_NP1 Circus_NN1 Dirty_JJ Sanchez_NP1 Crazy_JJ Monkey_NN1 Rad_NP1 Girls_NN2 The_AT Dudesons_NN2 Data_NN collection_NN1 methodology_NN1 SHORT_JJ DESCRIPTION_NN1 OF_IO THE_AT DATA_NN COLLECTION_NN1 ._. 
</s>
<s>
Data_NN presentation_NN1 PRESENT_NN1 DATA_NN COMPILED_VVN BY_II SOCIAL_JJ NETWORK_NN1 (_( FACEBOOK_NP1 ,_, TWITTER_VV0 ,_, MYSPACE_VV0 ?_? )_) ._. 
</s>
<s>
Analysis_NN1 and_CC findings_NN2 MOST_RGT USED_JJ SOCIAL_JJ NETWORKING_NN1 TOOLS_NN2 ._. 
</s>
<s>
MOST_DAT SOCIAL_JJ GROUP_NN1 ._. 
</s>
<s>
CORPORATE_JJ WEB_NN1 SITES_NN2 VS_II GROUP_NN1 OWNED_VVD ._. 
</s>
<s>
ACTIVE_JJ GROUPS_NN2 VS_II NON-ACTIVE_JJ GROUPS_NN2 ._. 
</s>
<s>
ORGANIC_JJ STRATEGY_NN1 ,_, NOT_XX PLANNED_VVN ._. 
</s>
<s>
Conclusion_NN1 DISCUSS_VV0 THE_AT SUITABILITY_NN1 OF_IO THE_AT RESEARCH_NN1 METHOD_NN1 AND_CC SCOPE_NN1 ._. 
</s>
<s>
USABILITY_NN1 OF_IO THE_AT RESULTS_NN2 ._. 
</s>
<s>
PRESENT_VV0 THE_AT REAL_JJ ADDED_JJ KNOWLEDGE_NN1 OF_IO THE_AT PAPER_NN1 ._. 
</s>
<s>
IMPROVMENTS_NN2 AND_CC POSSIBLE_JJ FUTURE_JJ RESEARCH_NN1 ._. 
</s>
