<s>
Bankruptcy_NN1 of_IO Russian_JJ tour_NN1 operators_NN2 :_: reason_NN1 and_CC possible_JJ solutions_NN2 Introduction_NN1 Tourism_NN1 is_VBZ now_RT one_MC1 of_IO the_AT leading_JJ industries_NN2 in_II several_DA2 countries_NN2 ,_, being_VBG both_RR the_AT main_JJ employer_NN1 and_CC the_AT largest_JJT source_NN1 of_IO income_NN1 there_RL ._. 
</s>
<s>
Despite_II the_AT fact_NN1 that_CST the_AT development_NN1 of_IO tourism_NN1 industry_NN1 requires_VVZ a_AT1 lot_NN1 of_IO investment_NN1 ;_; it_PPH1 stimulates_VVZ to_TO evolve_VVI other_JJ sectors_NN2 of_IO economy_NN1 :_: construction_NN1 ,_, service_NN1 ,_, trade_NN1 ,_, agriculture_NN1 ,_, etc_RA ._. 
</s>
<s>
Tourism_NN1 in_II Russia_NP1 is_VBZ one_MC1 of_IO the_AT most_RGT rapidly_RR developing_JJ and_CC profitable_JJ sectors_NN2 of_IO national_JJ economy_NN1 ;_; nevertheless_RR ,_, it_PPH1 faces_VVZ a_AT1 lot_NN1 of_IO difficulties_NN2 nowadays_RT ._. 
</s>
<s>
Considering_CS the_AT influence_NN1 of_IO tourism_NN1 on_II other_JJ industries_NN2 ,_, it_PPH1 is_VBZ essential_JJ to_TO develop_VVI this_DD1 sector_NN1 in_BCL21 order_BCL22 to_TO diversify_VVI Russian_JJ economy_NN1 and_CC ensure_VVI the_AT stable_JJ growth_NN1 in_II the_AT future_NN1 ._. 
</s>
<s>
Tourism_NN1 industry_NN1 is_VBZ like_II a_AT1 coin_NN1 and_CC has_VHZ two_MC sides_NN2 :_: inbound_VV0 and_CC outbound_VV0 tourism_NN1 ._. 
</s>
<s>
On_II the_AT one_MC1 hand_NN1 ,_, problems_NN2 seem_VV0 to_TO exist_VVI only_RR within_II inbound_NN1 sector_NN1 :_: the_AT shortage_NN1 of_IO investment_NN1 and_CC appropriate_JJ infrastructure_NN1 is_VBZ aggravated_VVN by_II the_AT deficiency_NN1 in_II legislation_NN1 and_CC the_AT necessity_NN1 to_TO determine_VVI private_JJ property_NN1 rights_NN2 ._. 
</s>
<s>
This_DD1 problem_NN1 is_VBZ discussed_VVN widely_RR in_II Russian_JJ academic_JJ and_CC business_NN1 circles_NN2 ,_, though_CS heated_JJ arguments_NN2 on_II the_AT reasons_NN2 which_DDQ prevent_VV0 Russian_JJ tourism_NN1 industry_NN1 from_II developing_VVG still_RR exist_VV0 ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 ,_, outbound_VV0 tourism_NN1 in_II Russia_NP1 seems_VVZ to_TO be_VBI a_AT1 prosperous_JJ sector_NN1 of_IO national_JJ economy_NN1 ._. 
</s>
<s>
During_II the_AT last_MD ten_MC years_NNT2 this_DD1 branch_NN1 has_VHZ experienced_VVN a_AT1 dramatic_JJ rise_NN1 ,_, with_IW Russians_NN2 being_VBG better-off_JJR and_CC the_AT number_NN1 of_IO tourists_NN2 increasing_VVG every_AT1 year_NNT1 ._. 
</s>
<s>
Package_NN1 tours_NN2 to_II Turkey_NP1 ,_, Egypt_NP1 ,_, Greece_NP1 or_CC Spain_NP1 are_VBR the_AT most_RGT popular_JJ and_CC convenient_JJ way_NN1 for_IF Russian_JJ citizens_NN2 to_TO spend_VVI their_APPGE holiday_NN1 especially_RR because_II21 of_II22 low_JJ prices_NN2 ._. 
</s>
<s>
As_CSA consequence_NN1 ,_, recently_RR the_AT number_NN1 of_IO tour_NN1 operators_NN2 in_II the_AT country_NN1 has_VHZ soared_VVN ;_; competition_NN1 between_II them_PPHO2 being_VBG increased_VVN significantly_RR ._. 
</s>
<s>
However_RR ,_, this_DD1 year_NNT1 a_AT1 number_NN1 of_IO tour_NN1 operators_NN2 in_II the_AT country_NN1 have_VH0 become_VVN bankrupt_JJ ;_; this_DD1 fact_NN1 has_VHZ revealed_VVN problems_NN2 in_II outbound_NN1 tourism_NN1 branch_NN1 ,_, considering_CS especially_RR the_AT size_NN1 of_IO the_AT companies_NN2 ._. 
</s>
<s>
Due_II21 to_II22 the_AT high_JJ cost_NN1 of_IO tours_NN2 within_II Russia_NP1 and_CC low_JJ level_NN1 of_IO infrastructure_NN1 ,_, the_AT majority_NN1 of_IO citizens_NN2 prefer_VV0 going_VVG abroad_RL ;_; which_DDQ ,_, consequently_RR ,_, leads_VVZ to_II the_AT rise_NN1 in_II the_AT number_NN1 of_IO tour_NN1 operators_NN2 and_CC tour_NN1 agencies_NN2 ._. 
</s>
<s>
According_II21 to_II22 Russian_JJ Federal_JJ State_NN1 Statistics_NN Service_NN1 (_( Rosstat_NP1 )_) the_AT number_NN1 of_IO trips_NN2 abroad_RL rose_VVD by_II 15%_NNU last_MD year_NNT1 against_II 2010_MC ._. 
</s>
<s>
Taking_VVG this_DD1 fact_NN1 into_II account_NN1 ,_, a_AT1 number_NN1 of_IO bankruptcies_NN2 of_IO tour_NN1 operators_NN2 ,_, occurred_VVD during_II the_AT recent_JJ year_NNT1 ,_, seems_VVZ to_TO be_VBI obscure_JJ ,_, illogical_JJ ,_, and_CC groundless_JJ ._. 
</s>
<s>
Nowadays_RT this_DD1 topic_NN1 is_VBZ widely_RR discussed_VVN in_II Russia_NP1 ,_, but_CCB there_EX is_VBZ no_AT single_JJ opinion_NN1 on_II both_DB2 the_AT reasons_NN2 for_IF the_AT bankruptcies_NN2 and_CC the_AT possible_JJ effect_NN1 on_II the_AT economy_NN1 of_IO the_AT country_NN1 ._. 
</s>
<s>
Some_DD people_NN believe_VV0 that_CST the_AT insolvency_NN1 is_VBZ the_AT result_NN1 of_IO economic_JJ downturn_NN1 and_CC these_DD2 incidents_NN2 will_VM not_XX affect_VVI the_AT whole_JJ tourism_NN1 industry_NN1 of_IO the_AT country_NN1 ._. 
</s>
<s>
Others_NN2 think_VV0 that_CST the_AT current_JJ situation_NN1 is_VBZ an_AT1 evidence_NN1 of_IO serious_JJ problems_NN2 in_II Russian_JJ tourism_NN1 industry_NN1 and_CC predict_VV0 that_CST bankruptcies_NN2 will_VM continue_VVI ._. 
</s>
<s>
Nevertheless_RR ,_, the_AT insolvency_NN1 of_IO countrys_NN2 major_JJ tour_NN1 operators_NN2 can_VM not_XX be_VBI ignored_VVN as_CSA it_PPH1 definitely_RR signals_VVZ for_IF some_DD problems_NN2 of_IO the_AT national_JJ economy_NN1 which_DDQ can_VM affect_VVI its_APPGE state_NN1 in_II the_AT future_NN1 ._. 
</s>
<s>
However_RR ,_, in_BCL21 order_BCL22 to_TO find_VVI the_AT proper_JJ solution_NN1 it_PPH1 is_VBZ necessary_JJ ,_, first_MD of_IO all_DB ,_, to_TO state_VVI the_AT real_JJ reasons_NN2 for_IF the_AT current_JJ situation_NN1 ._. 
</s>
<s>
As_II the_AT topic_NN1 of_IO the_AT insolvency_NN1 of_IO Russian_JJ tour_NN1 operators_NN2 is_VBZ a_AT1 recent_JJ one_PN1 ,_, there_EX are_VBR no_AT researches_NN2 or_CC theoretical_JJ works_NN on_II this_DD1 subject_NN1 ._. 
</s>
<s>
That_DD1 is_VBZ why_RRQ articles_NN2 in_II newspapers_NN2 ,_, magazines_NN2 ,_, and_CC journals_NN2 are_VBR the_AT only_JJ sources_NN2 of_IO information_NN1 on_II this_DD1 matter_NN1 which_DDQ implies_VVZ too_RG subjective_JJ approach_NN1 to_II the_AT problem_NN1 ._. 
</s>
<s>
Although_CS this_DD1 paper_NN1 is_VBZ intended_VVN to_TO be_VBI a_AT1 review_NN1 of_IO different_JJ articles_NN2 written_VVN on_II the_AT topic_NN1 in_II question_NN1 ,_, it_PPH1 will_VM also_RR provide_VVI the_AT authors_NN2 own_DA opinion_NN1 as_II31 well_II32 as_II33 statistics_NN data_NN ._. 
</s>
<s>
The_AT paper_NN1 investigates_VVZ the_AT likely_JJ reasons_NN2 for_IF insolvency_NN1 of_IO tour_NN1 operators_NN2 in_II Russia_NP1 ,_, the_AT possible_JJ consequences_NN2 for_IF both_DB2 the_AT tourism_NN1 industry_NN1 and_CC the_AT national_JJ economy_NN1 ,_, and_CC the_AT solutions_NN2 to_II the_AT problem_NN1 which_DDQ are_VBR likely_JJ to_TO be_VBI implemented_VVN ._. 
</s>
<s>
An_AT1 overview_NN1 of_IO the_AT series_NN of_IO insolvency_NN1 of_IO Russian_JJ tour_NN1 operators_NN2 The_AT first_MD bankruptcy_NN1 ,_, which_DDQ initiates_VVZ the_AT chain_NN1 of_IO insolvency_NN1 of_IO Russian_JJ tour_NN1 operators_NN2 ,_, occurred_VVD in_II November_NPM1 ,_, 2011_MC ._. 
</s>
<s>
Capital_NN1 Tour_NP1 ,_, the_AT third_MD largest_JJT tour_NN1 operator_NN1 in_II the_AT country_NN1 with_IW income_NN1 of_IO more_DAR than_CSN 16_MC billion_NNO roubles_NN2 in_II 2009_MC (_( Ria_NP1 Novosti_NP1 ,_, ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ,_, ?_? ?_? ?_? ?_? ?_? ?_? ?_? 15.11.2010_MC )_) ,_, announced_VVD the_AT temporary_JJ default_NN1 on_II its_APPGE obligations_NN2 ;_; the_AT overall_JJ debt_NN1 of_IO the_AT company_NN1 being_VBG more_DAR than_CSN 1.3_MC billion_NNO roubles_NN2 (_( www.BFM.ru_NNU ,_, ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? 50_MC ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ,_, 17.10.2010_MC )_) ._. 
</s>
<s>
This_DD1 incident_NN1 affected_VVN 8.3_MC thousand_NNO people_NN (_( "_" ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? "_" ,_, ?_? 162_MC (_( 4947_MC )_) ,_, 31.08.2012_MC )_) who_PNQS lost_VVD their_APPGE tourist_NN1 vouchers_NN2 as_II31 well_II32 as_II33 those_DD2 who_PNQS had_VHD difficulties_NN2 in_II returning_VVG back_RP to_II Russia_NP1 ,_, as_CSA their_APPGE hotel_NN1 reservations_NN2 and_CC airplane_NN1 tickets_NN2 were_VBDR not_XX paid_VVN ._. 
</s>
<s>
The_AT overall_JJ debt_NN1 of_IO the_AT tour_NN1 operator_NN1 amounted_VVD to_II 1.3_MC billion_NNO roubles_NN2 and_CC among_II its_APPGE creditors_NN2 were_VBDR nine_MC banks_NN2 ,_, several_DA2 tour_NN1 agencies_NN2 ,_, Red_JJ Wings_NN2 air_NN1 company_NN1 and_CC even_RR an_AT1 insurance_NN1 company_NN1 ._. 
</s>
<s>
(_( "_" ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? "_" ,_, ?_? 162_MC (_( 4947_MC )_) ,_, 31.08.2012_MC )_) Although_CS the_AT liability_NN1 of_IO the_AT tour_NN1 operator_NN1 itself_PPX1 was_VBDZ insured_VVN with_IW Innogarant_NP1 ,_, the_AT total_JJ amount_NN1 of_IO insurance_NN1 coverage_NN1 100_MC million_NNO roubles_NN2 (_( www.tourprom.ru_NNU ,_, ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ,_, 17.12.2010_MC )_) was_VBDZ insufficient_JJ to_TO repay_VVI the_AT debts_NN2 and_CC even_RR to_TO compensate_VVI the_AT losses_NN2 ,_, which_DDQ bore_VV0 companys_NN2 customers_NN2 ._. 
</s>
<s>
Capital_NN1 tour_NN1 ,_, being_VBG one_MC1 the_AT largest_JJT tour_NN1 operators_NN2 in_II Russia_NP1 with_IW turnover_NN1 of_IO more_DAR than_CSN 16.1_MC billion_NNO roubles_NN2 and_CC annual_JJ tourist_NN1 flow_NN1 of_IO 2_MC million_NNO people_NN ,_, was_VBDZ the_AT first_MD warning_NN1 of_IO problems_NN2 ,_, existing_VVG in_II the_AT industry_NN1 ._. 
</s>
<s>
The_AT incident_NN1 made_VVD Russian_JJ tourism_NN1 industry_NN1 union_NN1 think_VV0 about_II revising_VVG the_AT regulation_NN1 concerning_II financial_JJ guarantees_NN2 for_IF tour_NN1 operators_NN2 ._. 
</s>
<s>
However_RR ,_, the_AT insolvency_NN1 of_IO Capital_NN1 Tour_NP1 was_VBDZ followed_VVN by_II a_AT1 series_NN of_IO less_RGR noticeable_JJ financial_JJ collapses_NN2 of_IO smaller_JJR tour_NN1 operators_NN2 and_CC at_II the_AT end_NN1 of_IO January_NPM1 ,_, 2012_MC another_DD1 major_JJ company_NN1 in_II Russian_JJ tourism_NN1 industry_NN1 -_- Lanta-tour_JJ -_- also_RR became_VVD bankrupt_JJ ._. 
</s>
<s>
As_II the_AT result_NN1 ,_, more_DAR than_CSN three_MC thousand_NNO people_NN were_VBDR left_VVN abroad_RL with_IW no_AT possibility_NN1 to_TO return_VVI home_RL ;_; and_CC another_DD1 8_MC thousand_NNO lost_VVD their_APPGE tour_NN1 vouchers_NN2 ._. 
</s>
<s>
Founded_VVN in_II 1991_MC ,_, Lanta-tour_NN1 was_VBDZ one_MC1 of_IO the_AT oldest_JJT tour_NN1 operators_NN2 in_II Russia_NP1 and_CC according_II21 to_II22 the_AT ranking_NN1 of_IO 2009_MC the_AT company_NN1 was_VBDZ the_AT 17th_MD largest_JJT on_II the_AT market_NN1 with_IW annual_JJ turnover_NN1 of_IO 3.3_MC billion_NNO roubles_NN2 (_( www.utro.ru_NNU ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? -_- ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ,_, 28.01.2012_MC )_) ._. 
</s>
<s>
Lanta-tour_NN1 faced_VVD difficulties_NN2 when_RRQ Master_NN1 Bank_NN1 refused_VVD to_TO accommodate_VVI the_AT company_NN1 with_IW another_DD1 loan_NN1 ,_, which_DDQ led_VVD to_II the_AT shortage_NN1 of_IO working_VVG capital_NN1 and_CC inability_NN1 of_IO the_AT tour_NN1 operator_NN1 to_TO pay_VVI for_IF hotels_NN2 and_CC airplane_NN1 tickets_NN2 for_IF its_APPGE customers_NN2 ._. 
</s>
<s>
The_AT liability_NN1 of_IO Lanta-tour_NN1 was_VBDZ insured_VVN with_IW Ingostrach_NP1 company_NN1 for_IF the_AT amount_NN1 of_IO 100_MC million_NNO roubles_NN2 ,_, though_CS it_PPH1 was_VBDZ not_XX sufficient_JJ even_RR to_TO compensate_VVI its_APPGE customers_NN2 the_AT losses_NN2 they_PPHS2 incurred_VVD ._. 
</s>
<s>
The_AT overall_JJ debt_NN1 of_IO the_AT tour_NN1 operator_NN1 amounted_VVD to_II 1.1_MC billion_NNO roubles_NN2 (_( www.vz.ru_NNU ,_, ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? -_- ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ,_, 28.09.2012_MC )_) ._. 
</s>
<s>
The_AT insolvency_NN1 of_IO Capital_NN1 tour_NN1 was_VBDZ quite_RG expected_JJ ,_, as_CSA there_EX were_VBDR rumours_NN2 about_II the_AT poor_JJ financial_JJ standing_NN1 of_IO the_AT company_NN1 for_IF about_RG a_AT1 year_NNT1 before_II the_AT incident_NN1 ._. 
</s>
<s>
Despite_II this_DD1 fact_NN1 the_AT bankruptcy_NN1 of_IO Lanta-tour_NN1 was_VBDZ a_AT1 surprise_NN1 ._. 
</s>
<s>
Considering_CS the_AT fact_NN1 that_CST Lanta-tour_NN1 was_VBDZ one_MC1 of_IO the_AT oldest_JJT and_CC largest_JJT players_NN2 on_II the_AT market_NN1 ;_; the_AT reputation_NN1 of_IO Russain_JJ tour_NN1 operators_NN2 was_VBDZ tarnished_VVN ,_, and_CC a_AT1 severe_JJ problem_NN1 in_II the_AT industry_NN1 in_II question_NN1 was_VBDZ revealed_VVN ._. 
</s>
<s>
Later_RRR during_II this_DD1 year_NNT1 a_AT1 number_NN1 of_IO smaller_JJR tour_NN1 operators_NN2 also_RR announced_VVD the_AT temporary_JJ default_NN1 on_II their_APPGE obligations_NN2 ._. 
</s>
<s>
In_II April_NPM1 the_AT tour_NN1 operator_NN1 ITC_NN1 ,_, based_VVN in_II Moscow_NP1 ,_, was_VBDZ not_XX able_JK to_TO pay_VVI its_APPGE debts_NN2 ,_, which_DDQ affected_VVD around_RG 100_MC Russian_JJ tourists_NN2 being_VBG abroad_RL at_II that_DD1 time_NNT1 ._. 
</s>
<s>
That_DD1 month_NNT1 another_DD1 operator_NN1 The_AT ideal_JJ world_NN1 was_VBDZ accused_VVN of_IO fabricating_VVG air_NN1 tickets_NN2 ,_, causing_VVG the_AT problem_NN1 for_IF 200_MC Russian_JJ people_NN in_II going_VVG to_II Israel_NP1 or_CC coming_VVG home_RL ._. 
</s>
<s>
Two_MC months_NNT2 later_RRR ,_, in_II June_NPM1 ,_, tour_NN1 operator_NN1 Around_II the_AT world_NN1 ,_, which_DDQ specialized_VVD in_II the_AT countries_NN2 of_IO South-East_ND1 Asia_NP1 ,_, informed_VVN about_II the_AT suspension_NN1 of_IO the_AT activity_NN1 due_II21 to_II22 financial_JJ obligation_NN1 problems_NN2 ._. 
</s>
<s>
In_II the_AT end_NN1 of_IO August_NPM1 about_RG 200_MC Russian_JJ citizens_NN2 being_VBG on_II holiday_NN1 in_II Egypt_NP1 were_VBDR not_XX able_JK to_TO leave_VVI the_AT country_NN1 because_II21 of_II22 financial_JJ problems_NN2 of_IO El_NP1 Voyage_NP1 tour_NN1 operator_NN1 ._. 
</s>
<s>
Only_RR several_DA2 days_NNT2 after_II CherryTour_NP1 company_NN1 and_CC several_DA2 dozens_NNO2 of_IO its_APPGE clients_NN2 faced_VVD the_AT same_DA difficulties_NN2 in_II Croatia_NP1 ._. 
</s>
<s>
The_AT most_RGT recent_JJ case_NN1 of_IO bankruptcy_NN1 occurred_VVD in_II September_NPM1 with_IW tour_NN1 operator_NN1 Global_JJ Travel_NN1 ,_, which_DDQ also_RR faced_VVN financial_JJ difficulties_NN2 and_CC ceased_VVN operations_NN2 ._. 
</s>
<s>
All_DB above_RL mentioned_VVD incidents_NN2 taken_VVN place_NN1 after_II January_NPM1 ,_, 2012_MC did_VDD not_XX result_VVI in_II insolvency_NN1 of_IO tour_NN1 operators_NN2 because_II21 of_II22 relatively_RR small_JJ size_NN1 of_IO the_AT companies_NN2 ._. 
</s>
<s>
Their_APPGE insurance_NN1 coverage_NN1 was_VBDZ big_JJ enough_RR in_BCL21 order_BCL22 to_TO settle_VVI their_APPGE debts_NN2 ._. 
</s>
<s>
Nevertheless_RR ,_, this_DD1 chain_NN1 of_IO insolvency_NN1 signifies_VVZ some_DD problems_NN2 both_RR in_II tourism_NN1 industry_NN1 in_II Russia_NP1 and_CC in_II the_AT way_NN1 tour_NN1 operators_NN2 conduct_VV0 their_APPGE financial_JJ activity_NN1 ._. 
</s>
<s>
Moreover_RR ,_, the_AT two_MC big_JJ companies_NN2 Capital_NN1 Tour_NP1 and_CC Lanta-tour_NN1 became_VVD bankrupt_JJ ;_; which_DDQ definitely_RR indicates_VVZ serious_JJ problems_NN2 in_II the_AT industry_NN1 ._. 
</s>
<s>
The_AT reasons_NN2 for_IF insolvency_NN1 An_AT1 overview_NN1 of_IO Russian_JJ tourism_NN1 market_NN1 will_VM contribute_VVI to_II better_JJR understanding_NN1 of_IO the_AT factors_NN2 caused_VVD the_AT series_NN of_IO insolvency_NN1 of_IO companies_NN2 operating_VVG in_II the_AT industry_NN1 in_II question_NN1 ._. 
</s>
<s>
Nowadays_RT tourism_NN1 industry_NN1 in_II Russia_NP1 is_VBZ one_MC1 of_IO the_AT most_RGT rapidly_RR developing_JJ ,_, annual_JJ growth_NN1 rates_NN2 being_NN1 10-25%_FO since_II 2004_MC (_( www.svobodanews.ru_NNU ,_, ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? ?_? -_- ?_? ?_? ?_? ,_, 3.02.2012_MC )_) ._. 
</s>
<s>
It_PPH1 experienced_VVD an_AT1 insignificant_JJ decrease_NN1 in_II 2008-2009_MCMC due_II21 to_II22 the_AT world_NN1 economic_JJ downturn_NN1 ;_; nevertheless_RR ,_, next_MD years_NNT2 there_EX was_VBDZ again_RT an_AT1 increase_NN1 in_II growth_NN1 rates_NN2 ,_, though_CS not_XX as_RG big_JJ as_CSA the_AT previously_RR ._. 
</s>
<s>
Russian_JJ tourism_NN1 market_NN1 is_VBZ also_RR characterized_VVN by_II a_AT1 cut-throat_JJ competition_NN1 ,_, the_AT number_NN1 of_IO tour_NN1 operators_NN2 and_CC agencies_NN2 being_VBG more_DAR than_CSN two_MC thousand_NNO ._. 
</s>
<s>
Consequently_RR ,_, tourism_NN1 industry_NN1 of_IO the_AT country_NN1 can_VM be_VBI called_VVN a_AT1 buyers_NN2 market_VV0 ,_, i.e._REX supply_NN1 exceeds_VVZ demand_NN1 and_CC tourists_NN2 themselves_PPX2 dictate_VV0 terms_NN2 ._. 
</s>
<s>
Taking_VVG into_II consideration_NN1 relatively_RR low_JJ average_JJ income_NN1 in_II Russia_NP1 (_( 21000_MC roubles_NN2 530_MC euros_NN2 ,_, Rosstat_NP1 ,_, 2009_MC )_) ,_, price_NN1 is_VBZ the_AT main_JJ factor_NN1 defining_VVG customers_NN2 preferences_NN2 for_IF certain_JJ tourism_NN1 directions_NN2 ._. 
</s>
<s>
Thereby_RR ,_, the_AT only_JJ way_NN1 for_IF tour_NN1 companies_NN2 in_II Russia_NP1 to_TO attract_VVI as_RG many_DA2 clients_NN2 as_CSA possible_JJ is_VBZ to_TO reduce_VVI prices_NN2 ._. 
</s>
<s>
Although_CS each_DD1 case_NN1 of_IO insolvency_NN1 of_IO Russian_JJ tour_NN1 operators_NN2 is_VBZ unique_JJ ,_, according_II21 to_II22 the_AT majority_NN1 of_IO experts_NN2 there_EX is_VBZ one_MC1 common_JJ cause_NN1 dumping_VVG prices_NN2 ._. 
</s>
<s>
Tour_NP1 operators_NN2 as_II31 well_II32 as_II33 tour_NN1 agencies_NN2 have_VH0 got_VVN used_JJ to_II steadily_RR increasing_JJ market_NN1 ,_, though_CS they_PPHS2 were_VBDR overcautious_JJ in_II 2009_MC and_CC reduce_VV0 the_AT volume_NN1 of_IO sales_NN ,_, thus_RR operated_VVN in_II the_AT black_JJ that_DD1 year_NNT1 ._. 
</s>
<s>
However_RR ,_, in_II the_AT hope_NN1 of_IO rapid_JJ recovery_NN1 of_IO the_AT market_NN1 in_II 2010_MC they_PPHS2 overestimated_VVD their_APPGE abilities_NN2 and_CC booked_VVN too_RG many_DA2 air_NN1 tickets_NN2 and_CC hotels_NN2 ._. 
</s>
<s>
As_II the_AT result_NN1 ,_, only_JJ part_NN1 of_IO tours_NN2 was_VBDZ sold_VVN and_CC companies_NN2 had_VHD to_TO reduce_VVI the_AT price_NN1 as_RG much_DA1 as_CSA possible_JJ ._. 
</s>
<s>
According_II21 to_II22 the_AT data_NN of_IO Russian_JJ tour_NN1 operators_NN2 association_NN1 the_AT profitability_NN1 of_IO tourism_NN1 business_NN1 in_II the_AT country_NN1 in_II 2011_MC decreased_VVD to_II 2-3%_FO against_II 5-6%_FO previously_RR ._. 
</s>
<s>
Tour_NP1 operators_NN2 have_VH0 been_VBN using_VVG dumping_VVG prices_NN2 for_IF many_DA2 years_NNT2 already_RR ,_, but_CCB the_AT scheme_NN1 proved_VVD to_TO be_VBI a_AT1 failure_NN1 only_RR after_II the_AT crisis_NN1 years_NNT2 of_IO 2008-2009_MCMC ._. 
</s>
<s>
Tour_NP1 operators_NN2 have_VH0 three_MC main_JJ sources_NN2 of_IO income_NN1 for_IF conducting_VVG their_APPGE activity_NN1 ._. 
</s>
<s>
The_AT first_MD one_PN1 is_VBZ the_AT money_NN1 a_AT1 company_NN1 gets_VVZ from_II its_APPGE customers_NN2 ._. 
</s>
<s>
Usually_RR a_AT1 tour_NN1 operator_NN1 books_NN2 rooms_NN2 in_II hotels_NN2 and_CC charters_NN2 before_II the_AT tourist_NN1 season_NNT1 ,_, paying_VVG large_JJ amounts_NN2 of_IO money_NN1 in_II advance_NN1 ._. 
</s>
<s>
Although_CS sold_VVN tour_NN1 packages_NN2 are_VBR supposed_JJ to_TO compensate_VVI for_IF the_AT cost_NN1 ,_, sometimes_RT companies_NN2 do_VD0 not_XX manage_VVI to_TO sell_VVI all_DB tours_NN2 ._. 
</s>
<s>
In_II this_DD1 case_NN1 a_AT1 tour_NN1 operator_NN1 does_VDZ not_XX obtain_VVI enough_DD working_JJ capital_NN1 ;_; and_CC when_CS paying_VVG for_IF a_AT1 tour_NN1 ,_, tourists_NN2 usually_RR cover_VV0 expenses_NN2 of_IO someone_PN1 elses_VVZ tour_NN1 ._. 
</s>
<s>
Consequently_RR ,_, tour_NN1 operators_NN2 work_VV0 in_II the_AT hope_NN1 that_CST the_AT amount_NN1 of_IO future_JJ customers_NN2 will_VM be_VBI sufficient_JJ to_TO compensate_VVI for_IF cost_NN1 of_IO previous_JJ tours_NN2 as_RG well_RR as_CSA to_TO prepay_VVI for_IF following_VVG ones_NN2 ._. 
</s>
<s>
Thereby_RR ,_, if_CS a_AT1 company_NN1 overestimates_VVZ future_JJ growth_NN1 of_IO the_AT market_NN1 ,_, it_PPH1 is_VBZ likely_JJ to_TO become_VVI bankrupt_JJ or_CC at_RR21 least_RR22 face_VVI grave_JJ financial_JJ difficulties_NN2 ._. 
</s>
<s>
Second_MD way_NN1 of_IO obtaining_VVG money_NN1 is_VBZ increasing_JJ receivables_NN2 ._. 
</s>
<s>
Tour_NP1 operators_NN2 make_VV0 long-term_JJ contracts_NN2 with_IW air_NN1 companies_NN2 and_CC hotels_NN2 ,_, accumulating_VVG debts_NN2 and_CC paying_VVG them_PPHO2 off_RP when_CS receiving_VVG money_NN1 from_II customers_NN2 ._. 
</s>
<s>
Usually_RR both_RR air_NN1 companies_NN2 and_CC hotels_NN2 are_VBR willing_JJ to_TO wait_VVI for_IF tour_NN1 operators_NN2 to_TO settle_VVI their_APPGE debts_NN2 as_CSA they_PPHS2 are_VBR constant_JJ suppliers_NN2 of_IO customers_NN2 for_IF them_PPHO2 ._. 
</s>
<s>
However_RR ,_, sometimes_RT an_AT1 air_NN1 company_NN1 or_CC a_AT1 hotel_NN1 are_VBR not_XX ready_JJ to_TO wait_VVI any_RR21 longer_RR22 and_CC cancel_VVI a_AT1 contract_NN1 with_IW a_AT1 tour_NN1 operator_NN1 ,_, which_DDQ can_VM eventually_RR lead_VVI to_II insolvency_NN1 of_IO the_AT latter_DA ._. 
</s>
<s>
The_AT third_MD way_NN1 is_VBZ to_TO obtain_VVI a_AT1 bank_NN1 loan_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ more_RGR typical_JJ for_IF large_JJ companies_NN2 with_IW big_JJ turnover_NN1 and_CC annual_JJ income_NN1 ._. 
</s>
<s>
Banks_NN2 are_VBR usually_RR eager_JJ to_TO cooperate_VVI with_IW major_JJ tour_NN1 operators_NN2 ,_, though_CS for_IF companies_NN2 it_PPH1 is_VBZ the_AT most_RGT risky_JJ way_NN1 because_II21 of_II22 high_JJ interest_NN1 rate_NN1 ._. 
</s>
<s>
All_DB above_RL mentioned_VVD cases_NN2 are_VBR the_AT usual_JJ way_NN1 of_IO conducting_VVG business_NN1 in_II Russian_JJ tourism_NN1 industry_NN1 ._. 
</s>
<s>
Although_CS it_PPH1 may_VM suit_VVI an_AT1 increasing_JJ market_NN1 ,_, it_PPH1 is_VBZ definitely_RR inappropriate_JJ in_II times_NNT2 of_IO economic_JJ crisis_NN1 ._. 
</s>
<s>
Furthermore_RR ,_, as_CSA mentioned_VVN before_II tour_NN1 operators_NN2 use_VV0 dumping_VVG prices_NN2 in_BCL21 order_BCL22 to_TO attract_VVI customers_NN2 and_CC occupy_VVI sufficient_JJ market_NN1 share_NN1 ._. 
</s>
<s>
According_II21 to_II22 Irina_NP1 Tuyrina_NP1 ,_, a_AT1 spokesman_NN1 of_IO Russian_JJ tour_NN1 industry_NN1 union_NN1 ,_, 40-45%_FO of_IO all_DB tours_NN2 in_II the_AT country_NN1 are_VBR sold_VVN lower_RRR than_CSN the_AT breakeven_NN1 point_NN1 ._. 
</s>
<s>
Usually_RR tour_NN1 operators_NN2 use_VV0 dumping_VVG prices_NN2 in_II the_AT most_RGT popular_JJ directions_NN2 expecting_VVG to_TO compensate_VVI it_PPH1 by_II the_AT volume_NN1 of_IO sales_NN and_CC selling_VVG less_RGR popular_JJ but_CCB more_RGR expensive_JJ tours_NN2 ._. 
</s>
<s>
In_II Russia_NP1 dumping_VVG prices_NN2 are_VBR typical_JJ for_IF package_NN1 tours_NN2 to_II Turkey_NP1 ,_, Egypt_NP1 ,_, Greece_NP1 and_CC Thailand_NP1 ._. 
</s>
<s>
Dumping_VVG is_VBZ also_RR a_AT1 common_JJ way_NN1 for_IF a_AT1 tour_NN1 operator_NN1 to_TO develop_VVI new_JJ directions_NN2 as_RG well_RR as_CSA for_IF a_AT1 new_JJ a_AT1 company_NN1 to_TO enter_VVI the_AT market_NN1 ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO reduce_VVI price_NN1 for_IF their_APPGE products_NN2 tour_NN1 operators_NN2 also_RR cooperate_VV0 with_IW companies_NN2 which_DDQ provide_VV0 discount_NN1 coupons_NN2 ._. 
</s>
<s>
That_DD1 was_VBDZ the_AT cause_NN1 of_IO financial_JJ problems_NN2 of_IO El_NP1 voyage_NN1 and_CC Ideal_JJ world_NN1 tour_NN1 operators_NN2 :_: discount_NN1 coupon_NN1 companies_NN2 sold_VVD their_APPGE tours_NN2 and_CC did_VDD not_XX transfer_VVI the_AT money_NN1 in_II time_NNT1 ,_, so_CS the_AT tour_NN1 operators_NN2 were_VBDR not_XX able_JK to_TO settle_VVI their_APPGE debts_NN2 ._. 
</s>
<s>
Over_II abundant_JJ supply_NN1 on_II Russian_JJ tourism_NN1 market_NN1 results_NN2 also_RR in_II increase_NN1 of_IO sale_NN1 of_IO last_MD minute_NNT1 tours_NN2 ,_, which_DDQ is_VBZ a_AT1 popular_JJ way_NN1 for_IF tour_NN1 operators_NN2 to_TO attract_VVI customers_NN2 ._. 
</s>
<s>
Provided_CS21 that_CS22 the_AT situation_NN1 in_II the_AT industry_NN1 is_VBZ characterized_VVN as_II the_AT buyers_NN2 market_VV0 and_CC tourists_NN2 in_II Russia_NP1 are_VBR getting_VVG accustomed_JJ to_II cheap_JJ package_NN1 tours_NN2 ;_; it_PPH1 is_VBZ becoming_VVG more_RRR and_CC more_RGR difficult_JJ for_IF tour_NN1 operators_NN2 to_TO make_VVI profit_NN1 ,_, as_CSA they_PPHS2 have_VH0 to_TO sell_VVI their_APPGE goods_NN2 at_II breakeven_NN1 point_NN1 level_NN1 or_CC even_RR lower_JJR ._. 
</s>
<s>
Although_CS dumping_VVG prices_NN2 are_VBR considered_VVN to_TO be_VBI the_AT main_JJ reason_NN1 for_IF the_AT series_NN of_IO insolvency_NN1 of_IO tour_NN1 operators_NN2 in_II Russia_NP1 ,_, the_AT majority_NN1 of_IO players_NN2 on_II the_AT market_NN1 have_VH0 been_VBN using_VVG this_DD1 scheme_NN1 for_IF many_DA2 years_NNT2 already_RR ._. 
</s>
<s>
It_PPH1 is_VBZ proved_VVN to_TO be_VBI a_AT1 failure_NN1 only_RR after_II the_AT world_NN1 economic_JJ downturn_NN1 of_IO 2008_MC when_RRQ tour_NN1 operators_NN2 overestimated_VVD their_APPGE abilities_NN2 and_CC did_VDD not_XX react_VVI to_II the_AT situation_NN1 in_II an_AT1 appropriate_JJ way_NN1 ._. 
</s>
<s>
Thereby_RR ,_, the_AT economic_JJ crisis_NN1 has_VHZ helped_VVN Russian_JJ tourism_NN1 market_NN1 to_II some_DD extent_NN1 ,_, as_CSA it_PPH1 revealed_VVD grave_JJ problems_NN2 in_II the_AT industry_NN1 and_CC the_AT necessity_NN1 of_IO restructuring_NN1 of_IO the_AT whole_JJ industry_NN1 ._. 
</s>
<s>
According_II21 to_II22 experts_NN2 ,_, first_MD of_IO all_DB ,_, Russian_JJ tourism_NN1 market_NN1 has_VHZ to_TO abandon_VVI using_VVG last_MD minute_NNT1 tours_NN2 ._. 
</s>
<s>
Furthermore_RR ,_, all_DB financial_JJ transactions_NN2 should_VM become_VVI official_JJ ,_, and_CC the_AT amount_NN1 of_IO financial_JJ provision_NN1 of_IO the_AT players_NN2 on_II the_AT market_NN1 should_VM be_VBI increased_VVN ._. 
</s>
