<s>
Strategy_NN1 in_II military_JJ and_CC business_NN1 contexts_NN2 Introduction_NN1 Strategy_NN1 is_VBZ perhaps_RR the_AT most_RGT used_JJ single_JJ word_NN1 ,_, term_NN1 or_CC concept_NN1 ,_, in_II business_NN1 in_RR21 general_RR22 and_CC management_NN1 in_RR21 particular_RR22 ._. 
</s>
<s>
The_AT word_NN1 strategy_NN1 is_VBZ used_VVN in_II management_NN1 ,_, accounting_VVG ,_, finance_VV0 ,_, marketing_NN1 and_CC personnel_NN2 policy_NN1 with_IW seemingly_RR different_JJ meanings_NN2 depending_II21 on_II22 the_AT discipline_NN1 that_CST uses_VVZ it_PPH1 ._. 
</s>
<s>
This_DD1 can_VM lead_VVI to_II a_AT1 confusion_NN1 for_IF a_AT1 reader_NN1 not_XX familiar_JJ with_IW the_AT different_JJ meanings_NN2 ._. 
</s>
<s>
When_CS looking_VVG at_II how_RRQ the_AT word_NN1 is_VBZ defined_VVN in_II literature_NN1 one_PN1 can_VM see_VVI that_CST there_EX are_VBR as_RG many_DA2 definitions_NN2 as_CSA there_EX are_VBR writers_NN2 ._. 
</s>
<s>
This_DD1 makes_VVZ the_AT word_NN1 ,_, term_NN1 or_CC concept_NN1 of_IO strategy_NN1 highly_RR nebulous_JJ and_CC very_RG imprecise_JJ ._. 
</s>
<s>
Due_II21 to_II22 this_DD1 the_AT word_NN1 ,_, term_NN1 or_CC concept_NN1 risks_NN2 loosing_VVG its_APPGE meaning_NN1 altogether_RR and_CC becoming_VVG irrelevant_JJ ._. 
</s>
<s>
Purpose_VV0 The_AT purpose_NN1 of_IO this_DD1 paper_NN1 is_VBZ to_TO examine_VVI how_RRQ strategy_NN1 moved_VVN from_II a_AT1 purely_RR military_JJ context_NN1 to_II a_AT1 business_NN1 context_NN1 and_CC what_DDQ kind_NN1 of_IO differences_NN2 there_EX are_VBR in_II both_RR meaning_VVG and_CC usage_NN1 of_IO the_AT word_NN1 ,_, or_CC term_NN1 ._. 
</s>
<s>
The_AT paper_NN1 starts_VVZ with_IW the_AT etymology_NN1 of_IO the_AT word_NN1 and_CC its_APPGE original_JJ meaning_NN1 ._. 
</s>
<s>
Texts_NN2 of_IO military_JJ strategists_NN2 are_VBR examined_VVN so_BCL21 as_BCL22 to_TO establish_VVI whether_CSW there_EX are_VBR commonalties_NN2 in_II them_PPHO2 with_IW the_AT intention_NN1 to_TO establish_VVI a_AT1 common_JJ meaning_NN1 ._. 
</s>
<s>
An_AT1 ancillary_JJ purpose_NN1 of_IO this_DD1 paper_NN1 is_VBZ to_TO provide_VVI the_AT reader_NN1 with_IW a_AT1 better_JJR understanding_NN1 of_IO a_AT1 very_RG important_JJ term_NN1 used_VVD widely_RR in_II business_NN1 contexts_NN2 ._. 
</s>
<s>
Origins_NN2 of_IO the_AT word_NN1 strategy_NN1 The_AT word_NN1 strategy_NN1 is_VBZ derived_VVN from_II a_AT1 Greek_JJ word_NN1 strategos_NN2 which_DDQ means_VVZ leader_NN1 or_CC commander_NN1 of_IO an_AT1 army_NN1 ,_, a_AT1 general_NN1 ._. 
</s>
<s>
The_AT word_NN1 in_II turn_NN1 is_VBZ a_AT1 combination_NN1 of_IO two_MC Greek_JJ words_NN2 stratos_NN2 army_NN1 or_CC host_NN1 and_CC agos_NN2 leader_NN1 or_CC chief_NN1 ._. 
</s>
<s>
The_AT words_NN2 meaning_NN1 is_VBZ very_RG clear_JJ in_II the_AT military_JJ context_NN1 whereas_CS its_APPGE use_NN1 in_II the_AT business_NN1 context_NN1 is_VBZ very_RG obscure_JJ ._. 
</s>
<s>
Military_JJ strategy_NN1 Commonalities_NN2 in_II military_JJ strategy_NN1 There_EX are_VBR significant_JJ commonalities_NN2 in_II the_AT text_NN1 of_IO military_JJ strategists_NN2 ._. 
</s>
<s>
These_DD2 commonalities_NN2 are_VBR not_XX restricted_VVN to_II time_NNT1 period_NN1 or_CC culture_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ possible_JJ to_TO give_VVI a_AT1 common_JJ description_NN1 of_IO what_DDQ the_AT word_NN1 strategy_NN1 in_II the_AT military_JJ context_NN1 means_VVZ ._. 
</s>
<s>
There_EX are_VBR many_DA2 factors_NN2 that_CST are_VBR the_AT same_DA regardless_RR of_IO origin_NN1 of_IO the_AT text_NN1 ._. 
</s>
<s>
Leading_JJ or_CC commanding_VVG an_AT1 army_NN1 seems_VVZ to_TO require_VVI the_AT same_DA things_NN2 from_II the_AT generals_NN2 ._. 
</s>
<s>
Below_RL is_VBZ a_AT1 description_NN1 of_IO what_DDQ the_AT requirements_NN2 for_IF leading_VVG an_AT1 army_NN1 are_VBR and_CC what_DDQ duties_NN2 and_CC responsibilities_NN2 the_AT commander_NN1 has_VHZ ._. 
</s>
<s>
Business_NN1 strategy_NN1 Origins_NN2 of_IO business_NN1 strategy_NN1 Introducing_VVG strategy_NN1 into_II the_AT business_NN1 context_NN1 is_VBZ widely_RR contributed_VVN to_II Igor_NP1 Ansoff_NP1 ._. 
</s>
<s>
His_APPGE book_NN1 Corporate_JJ Strategy_NN1 that_CST was_VBDZ published_VVN in_II 1965_MC was_VBDZ the_AT very_RG first_MD book_NN1 in_II which_DDQ strategy_NN1 was_VBDZ used_VVN as_CSA tool_NN1 for_IF planning_VVG business_NN1 activities_NN2 ._. 
</s>
<s>
Previously_RR planning_VVG had_VHD not_XX been_VBN as_RG systematic_JJ ._. 
</s>
<s>
Still_RR there_EX is_VBZ little_RR doubt_VV0 that_CST corporations_NN2 had_VHD had_VHN strategies_NN2 long_RR before_II 1965_MC ,_, they_PPHS2 were_VBDR just_RR not_XX called_VVN strategies_NN2 ._. 
</s>
<s>
Schools_NN2 of_IO business_NN1 strategy_NN1 Researchers_NN2 (_( Mintzberg_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2000_MC )_) have_VH0 identified_VVN ten_MC major_JJ different_JJ schools_NN2 of_IO strategy_NN1 and_CC grouped_VVD authors_NN2 accordingly_RR ._. 
</s>
<s>
Differences_NN2 in_II business_NN1 strategy_NN1 The_AT differences_NN2 in_II how_RRQ business_NN1 strategists_NN2 use_VV0 the_AT word_NN1 strategy_NN1 can_VM at_RR21 least_RR22 partly_RR be_VBI explained_VVN by_II the_AT concept_NN1 of_IO mental_JJ models_NN2 ._. 
</s>
<s>
Mental_JJ models_NN2 Link_VV0 between_II military_JJ and_CC business_NN1 Chandler_NP1 (_( 1993_MC )_) describes_VVZ how_RRQ the_AT link_NN1 between_II military_JJ thinking_NN1 and_CC business_NN1 thinking_NN1 was_VBDZ formed_VVN ._. 
</s>
<s>
In_II the_AT late_JJ nineteenth_MD century_NNT1 USA_NP1 business_NN1 enterprises_NN2 were_VBDR growing_VVG fast_JJ and_CC thus_RR there_EX arose_VVD a_AT1 need_NN1 for_IF a_AT1 more_RGR systematic_JJ way_NN1 of_IO managing_VVG them_PPHO2 ._. 
</s>
<s>
Companies_NN2 were_VBDR operating_VVG over_RP large_JJ areas_NN2 and_CC had_VHD thousands_NNO2 of_IO employees_NN2 that_CST had_VHD somehow_RR to_TO be_VBI supervised_VVN and_CC managed_VVN ._. 
</s>
<s>
The_AT owners_NN2 of_IO the_AT companies_NN2 started_VVD to_TO hire_VVI military_JJ officers_NN2 as_CSA overseers_NN2 and_CC as_II what_DDQ is_VBZ today_RT called_VVN managers_NN2 ._. 
</s>
<s>
These_DD2 officers_NN2 had_VHD received_VVN their_APPGE officers_NN2 training_VVG at_II West_NP1 Point_NP1 ,_, the_AT military_JJ academy_NN1 of_IO the_AT USA_NP1 ._. 
</s>
<s>
They_PPHS2 were_VBDR experienced_VVN at_II commanding_JJ large_JJ numbers_NN2 of_IO men_NN2 and_CC they_PPHS2 had_VHD had_VHN an_AT1 opportunity_NN1 to_II practice_NN1 their_APPGE skills_NN2 in_II the_AT US_NP1 Civil_JJ War_NN1 ._. 
</s>
<s>
They_PPHS2 organised_VVD the_AT companies_NN2 according_II21 to_II22 the_AT best_JJT military_JJ knowledge_NN1 of_IO the_AT time_NNT1 ._. 
</s>
<s>
Companies_NN2 started_VVD to_TO resemble_VVI military_JJ organisations_NN2 with_IW chains_NN2 of_IO command_NN1 and_CC strict_JJ definitions_NN2 of_IO responsiblities_NN2 ._. 
</s>
<s>
Hoskin_NP1 et_RA21 al_RA22 (_( 1997_MC )_) view_VV0 military_JJ and_CC business_NN1 strategy_NN1 more_RRR as_II twins_NN2 rather_II21 than_II22 being_VBG parent_NN1 and_CC offspring_NN ._. 
</s>
<s>
People_NN tend_VV0 to_TO use_VVI methods_NN2 and_CC practices_NN2 with_IW which_DDQ they_PPHS2 are_VBR familiar_JJ when_CS encountering_VVG new_JJ situations_NN2 that_CST the_AT have_VH0 never_RR before_RT experienced_VVN (_( Drner_NP1 )_) ._. 
</s>
<s>
Military_JJ officers_NN2 introduced_VVD the_AT methods_NN2 they_PPHS2 were_VBDR familiar_JJ with_IW and_CC which_DDQ they_PPHS2 knew_VVD worked_VVN ._. 
</s>
<s>
Comparison_NN1 of_IO military_JJ and_CC business_NN1 strategists_NN2 Comparing_VVG the_AT backgrounds_NN2 of_IO military_JJ and_CC business_NN1 strategists_NN2 is_VBZ useful_JJ because_CS it_PPH1 will_VM explain_VVI some_DD of_IO the_AT differences_NN2 that_CST can_VM be_VBI found_VVN in_II the_AT respective_JJ disciplines_NN2 ._. 
</s>
<s>
This_DD1 comparison_NN1 will_VM be_VBI useful_JJ when_CS explaining_VVG the_AT differences_NN2 in_II how_RRQ strategy_NN1 is_VBZ defined_VVN by_II the_AT respective_JJ groups_NN2 of_IO strategists_NN2 ._. 
</s>
<s>
Military_JJ strategists_NN2 There_EX is_VBZ ,_, however_RR ,_, only_RR little_RR precise_JJ information_NN1 on_II the_AT earliest_JJT writers_NN2 on_II military_JJ strategy_NN1 such_II21 as_II22 Sun_NN1 Tzu_NN1 and_CC Vegetius_NP1 ._. 
</s>
<s>
They_PPHS2 seem_VV0 to_TO have_VHI been_VBN military_JJ men_NN2 of_IO some_DD sort_NN1 but_CCB the_AT details_NN2 are_VBR very_RG diffuse_JJ ._. 
</s>
<s>
Later_JJR strategists_NN2 such_II21 as_II22 Maurice_NP1 are_VBR well_RR documented_VVN ._. 
</s>
<s>
The_AT best_JJT documentation_NN1 can_VM be_VBI found_VVN on_II De_NP1 Jomini_NP1 ,_, Clausewitz_NP1 ,_, Maurice_NP1 de_NP1 Saxe_NP1 ,_, Alfred_NP1 Thayer_NP1 Mahan_NP1 ._. 
</s>
<s>
All_DB military_JJ strategists_NN2 seem_VV0 to_TO have_VHI been_VBN soldiers_NN2 with_IW first_MD hand_NN1 experience_NN1 of_IO command_NN1 in_II actual_JJ war_NN1 in_II31 addition_II32 to_II33 extensive_JJ studies_NN2 of_IO the_AT subject_NN1 ._. 
</s>
<s>
Business_NN1 strategists_NN2 The_AT backgrounds_NN2 of_IO business_NN1 strategists_NN2 are_VBR generally_RR very_RG well_RR documented_VVN ._. 
</s>
<s>
All_DB have_VH0 at_RR21 least_RR22 a_AT1 degree_NN1 in_II business_NN1 administration_NN1 and_CC many_DA2 have_VH0 also_RR a_AT1 degree_NN1 in_II engineering_NN1 ._. 
</s>
<s>
Most_DAT have_VH0 never_RR worked_VVN in_II business_NN1 organisations_NN2 as_CSA members_NN2 of_IO management_NN1 with_IW responsibility_NN1 of_IO business_NN1 operations_NN2 ._. 
</s>
<s>
Most_DAT have_VH0 worked_VVN as_CSA researchers_NN2 at_II universities_NN2 ,_, business_NN1 schools_NN2 or_CC at_II consulting_JJ companies_NN2 ._. 
</s>
<s>
This_DD1 brings_VVZ out_RP an_AT1 interesting_JJ aspect_NN1 of_IO the_AT development_NN1 of_IO business_NN1 strategy_NN1 thinking_NN1 ._. 
</s>
<s>
The_AT majority_NN1 of_IO business_NN1 strategists_NN2 are_VBR western_JJ in_RR21 general_RR22 and_CC Anglo-American_JJ in_RR21 particular_RR22 ._. 
</s>
<s>
They_PPHS2 work_VV0 usually_RR at_II American_JJ business_NN1 schools_NN2 and_CC their_APPGE research_NN1 objects_NN2 are_VBR American_JJ or_CC multinational_JJ corporations_NN2 led_VVN and_CC managed_VVN by_II Americans_NN2 who_PNQS have_VH0 been_VBN trained_VVN at_II American_JJ business_NN1 schools_NN2 by_II American_JJ professors_NN2 who_PNQS have_VH0 based_VVN their_APPGE strategic_JJ thinking_NN1 on_II research_NN1 made_VVN at_II corporations_NN2 led_VVN by_II Americans_NN2 who_PNQS have_VH0 been_VBN trained_VVN at_II American_JJ business_NN1 schools_NN2 by_II American_JJ professors_NN2 and_RR31 so_RR32 on_RR33 ._. 
</s>
<s>
This_DD1 creates_VVZ a_AT1 closed_JJ loop_NN1 into_II which_DDQ fresh_JJ thinking_NN1 and_CC new_JJ ideas_NN2 are_VBR rarely_RR introduced_VVN ._. 
</s>
<s>
Few_DA2 if_CS any_DD business_NN1 strategists_NN2 have_VH0 first_MD hand_NN1 experience_NN1 in_II leading_VVG a_AT1 corporation_NN1 of_IO any_DD size_NN1 ._. 
</s>
<s>
Whereas_CS the_AT majority_NN1 of_IO military_JJ strategists_NN2 base_VV0 their_APPGE work_NN1 and_CC ideas_NN2 on_II personal_JJ experiences_NN2 gained_VVN from_II war_NN1 ._. 
</s>
<s>
Sources_NN2 Texts_NN2 from_II various_JJ time_NNT1 periods_NN2 of_IO time_NNT1 and_CC different_JJ cultures_NN2 are_VBR used_VVN ._. 
</s>
<s>
Ideas_NN2 of_IO military_JJ strategists_NN2 such_II21 as_II22 Vegetius_NP1 ,_, Maurice_NP1 from_II Rome_NP1 and_CC Byzantium_NN1 as_II31 well_II32 as_II33 Sun_NN1 Tzu_NN1 from_II China_NP1 and_CC Kautiliya_NP1 from_II India_NP1 are_VBR examined_VVN ._. 
</s>
<s>
More_RGR modern_JJ such_II21 as_II22 De_NP1 Jomini_NP1 ,_, Clausewitz_NP1 and_CC Musashi_NP1 are_VBR also_RR considered_VVN ._. 
</s>
<s>
These_DD2 are_VBR examined_VVN to_TO establish_VVI similarities_NN2 or_CC dissimilarities_NN2 over_II time_NNT1 and_CC between_II cultures_NN2 ._. 
</s>
<s>
Text_NN1 on_II strategy_NN1 in_II the_AT modern_JJ business_NN1 context_NN1 by_II Igor_NP1 Ansoff_NP1 ,_, Henry_NP1 Minztberg_NP1 and_CC Michael_NP1 Porter_NP1 are_VBR used_VVN ._. 
</s>
<s>
Ansoff_NN1 is_VBZ widely_RR considered_VVN the_AT Father_NN1 of_IO Strategic_JJ Management_NN1 ._. 
</s>
<s>
The_AT latter_DA two_MC can_VM be_VBI considered_VVN the_AT most_RGT influential_JJ theorists_NN2 of_IO business_NN1 strategy_NN1 ._. 
</s>
<s>
Textbooks_NN2 popular_JJ at_II business_NN1 schools_NN2 will_VM also_RR be_VBI examined_VVN as_CSA they_PPHS2 are_VBR influencing_VVG coming_JJ generations_NN2 of_IO managers_NN2 ._. 
</s>
<s>
Psychological_JJ factors_NN2 ,_, such_II21 as_II22 mental_JJ models_NN2 ,_, and_CC their_APPGE influence_NN1 on_II how_RRQ strategy_NN1 is_VBZ defined_VVN are_VBR also_RR considered_VVN ._. 
</s>
<s>
The_AT influence_NN1 of_IO psychological_JJ factors_NN2 on_II strategy_NN1 as_II31 well_II32 as_II33 strategy_NN1 as_II a_AT1 psychological_JJ phenomenon_NN1 will_VM be_VBI examined_VVN ._. 
</s>
<s>
Psychology_NN1 and_CC psychological_JJ warfare_NN1 are_VBR important_JJ aspects_NN2 in_II the_AT oriental_JJ strategic_JJ tradition_NN1 ._. 
</s>
<s>
The_AT tie_NN1 between_II military_JJ and_CC business_NN1 strategy_NN1 is_VBZ much_RR tighter_JJR in_II Japan_NP1 and_CC China_NP1 as_II both_DB2 fields_NN2 have_VH0 their_APPGE roots_NN2 in_II Zen_NP1 Buddhism_NN1 ._. 
</s>
<s>
The_AT study_NN1 will_VM be_VBI based_VVN on_II literature_NN1 that_CST is_VBZ more_RGR or_CC less_RGR publicly_RR available_JJ ._. 
</s>
<s>
The_AT study_NN1 should_VM not_XX be_VBI considered_VVN an_AT1 exhaustive_JJ study_NN1 of_IO strategy_NN1 ,_, its_APPGE origins_NN2 and_CC its_APPGE definition_NN1 in_II business_NN1 and_CC military_JJ contexts_NN2 ._. 
</s>
<s>
Its_APPGE aim_NN1 is_VBZ to_TO give_VVI the_AT reader_NN1 an_AT1 overview_NN1 of_IO the_AT complexity_NN1 of_IO the_AT field_NN1 of_IO strategy_NN1 and_CC act_VV0 as_II a_AT1 primer_NN1 for_IF further_JJR more_RRR detailed_JJ studies_NN2 of_IO the_AT subject_NN1 ._. 
</s>
<s>
Conclusions_NN2 There_EX is_VBZ no_AT strong_JJ and_CC significant_JJ connection_NN1 between_II military_JJ strategy_NN1 and_CC business_NN1 strategy_NN1 ._. 
</s>
<s>
The_AT connection_NN1 between_II them_PPHO2 is_VBZ more_RGR or_CC less_RGR created_JJ by_II the_AT use_NN1 of_IO terminology_NN1 which_DDQ have_VH0 their_APPGE roots_NN2 in_II military_JJ strategy_NN1 ._. 
</s>
<s>
Terms_NN2 such_II21 as_II22 captains_NN2 of_IO industry_NN1 which_DDQ refer_VV0 to_II managers_NN2 ,_, campaign_NN1 which_DDQ refers_VVZ to_II business_NN1 activities_NN2 with_IW limited_JJ scope_NN1 ,_, division_NN1 for_IF different_JJ parts_NN2 of_IO the_AT company_NN1 ,_, to_TO name_VVI but_CCB a_AT1 few_DA2 ._. 
</s>
<s>
This_DD1 inference_NN1 is_VBZ strengthened_VVN by_II quoting_VVG military_JJ strategists_NN2 such_II21 as_II22 Sun_NN1 Tzu_NN1 and_CC Miyamoto_NP1 Musashi_NP1 which_DDQ in_II fact_NN1 have_VH0 very_RG little_DA1 to_TO do_VDI with_IW contemporary_JJ western_JJ business_NN1 strategy_NN1 ._. 
</s>
<s>
It_PPH1 could_VM be_VBI said_VVN that_CST these_DD2 ,_, and_CC many_DA2 other_JJ ,_, military_JJ strategists_NN2 are_VBR twice_RR removed_VVN from_II business_NN1 contexts_NN2 ._. 
</s>
<s>
They_PPHS2 are_VBR culturally_RR removed_VVN from_II western_JJ thinking_NN1 which_DDQ forms_VVZ the_AT core_NN1 of_IO main_JJ stream_NN1 business_NN1 strategy_NN1 thinking_NN1 and_CC as_RG previously_RR noted_VVN are_VBR not_XX related_VVN in_II any_DD meaningful_JJ way_NN1 to_II business_NN1 strategy_NN1 as_CSA they_PPHS2 are_VBR military_JJ strategists_NN2 .._... 
</s>
<s>
Further_RRR research_VV0 The_AT largest_JJT change_NN1 in_II management_NN1 thinking_NN1 and_CC practice_NN1 occurred_VVD after_II World_NN1 War_NN1 II_MC ._. 
</s>
<s>
It_PPH1 would_VM be_VBI interesting_JJ to_TO investigate_VVI what_DDQ influence_VV0 the_AT home_NN1 coming_VVG officers_NN2 have_VH0 had_VHN on_II this_DD1 development_NN1 ._. 
</s>
<s>
What_DDQ influence_VV0 have_VH0 been_VBN exerted_VVN on_II the_AT behaviour_NN1 of_IO future_JJ managers_NN2 by_II the_AT officers_NN2 training_NN1 they_PPHS2 received_VVD and_CC by_II the_AT actual_JJ warfighting_NN1 they_PPHS2 were_VBDR involved_JJ in_II ._. 
</s>
