<s>
What_DDQ Affects_VVZ a_AT1 Consumer_NN1 's_GE Choice_NN1 of_IO Grocery_NN1 Retail_JJ Store_NN1 ?_? 
</s>
<s>
Comparing_VVG Stockmann_NP1 Herkku_NP1 and_CC LIDL_VV0 1_MC1 ._. 
</s>
<s>
Introduction_NN1 1.1_MC ._. 
</s>
<s>
Research_NN1 Question_NN1 This_DD1 study_NN1 builds_VVZ upon_II the_AT theory_NN1 of_IO customer_NN1 value_NN1 propositions_NN2 ._. 
</s>
<s>
In_II everyday_JJ shopping_NN1 the_AT consumer_NN1 experiences_NN2 the_AT following_JJ values_NN2 :_: economic_JJ value_NN1 ,_, functional_JJ value_NN1 ,_, emotional_JJ and_CC symbolic_JJ values_NN2 (_( Rintamki_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2007_MC in_II Vkel_NP1 2010_MC )_) ._. 
</s>
<s>
The_AT research_NN1 field_NN1 is_VBZ related_VVN to_II behavioral_JJ science_NN1 and_CC can_VM show_VVI how_RRQ the_AT customer_NN1 experiences_NN2 value_NN1 of_IO his_APPGE or_CC her_APPGE purchasing_NN1 decisions_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ essential_JJ for_IF any_DD company_NN1 searching_VVG for_IF competitive_JJ advantages_NN2 in_II the_AT long_JJ run_NN1 to_TO understand_VVI how_RRQ the_AT customer_NN1 perceives_VVZ value_NN1 ._. 
</s>
<s>
The_AT topic_NN1 is_VBZ interrelated_VVN with_IW other_JJ marketing_NN1 research_NN1 areas_NN2 ;_; Rintamki_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2007_MC )_) study_VV0 competitive_JJ customer_NN1 value_NN1 propositions_NN2 ,_, whereas_CS Fournier_NP1 (_( 1998_MC )_) views_VVZ the_AT consumer_NN1 and_CC retailer_NN1 within_II a_AT1 relationship_NN1 theory_NN1 framework_NN1 focused_VVN on_II brands_NN2 ._. 
</s>
<s>
Furthermore_RR ,_, Messinger_NP1 and_CC Narasimhan_NP1 (_( 1997_MC )_) study_VV0 retail_JJ shopping_NN1 from_II a_AT1 perspective_NN1 of_IO behavioral_JJ science_NN1 centralized_VVN around_II the_AT actual_JJ shopping_NN1 situation_NN1 inside_II the_AT store_NN1 ._. 
</s>
<s>
People_NN often_RR choose_VV0 one_MC1 store_NN1 where_CS they_PPHS2 favor_VV0 to_TO do_VDI their_APPGE grocery_NN1 shopping_NN1 ._. 
</s>
<s>
Many_DA2 of_IO us_PPIO2 probably_RR recognize_VV0 ourselves_PPX2 having_VHG a_AT1 certain_JJ routine_NN1 to_II our_APPGE grocery_NN1 shopping_NN1 :_: the_AT same_DA store_NN1 ,_, the_AT same_DA time_NNT1 ,_, the_AT same_DA products_NN2 and_RR31 so_RR32 on_RR33 ._. 
</s>
<s>
For_IF the_AT case_NN1 of_IO the_AT retailer_NN1 it_PPH1 is_VBZ well_JJ worth_II knowing_VVG the_AT factors_NN2 that_CST influence_VV0 the_AT consumer_NN1 when_CS choosing_VVG a_AT1 grocery_NN1 store_NN1 ._. 
</s>
<s>
Most_DAT previous_JJ studies_NN2 in_II the_AT field_NN1 have_VH0 been_VBN theory_NN1 driven_VVN ,_, assuming_VVG certain_JJ research_NN1 perspectives_NN2 ._. 
</s>
<s>
However_RR ,_, I_PPIS1 believe_VV0 that_CST there_EX is_VBZ not_XX one_MC1 single_JJ theory_NN1 that_CST can_VM adequately_RR explain_VVI customer_NN1 value_NN1 perception_NN1 in_II retail_JJ shopping_NN1 ._. 
</s>
<s>
There_EX is_VBZ very_RG little_DA1 research_NN1 combining_VVG different_JJ marketing_NN1 theories_NN2 on_II this_DD1 topic_NN1 ,_, this_DD1 study_NN1 is_VBZ focused_VVN on_II studying_VVG the_AT retail_JJ shopping_NN1 experience_NN1 with_IW the_AT possibility_NN1 of_IO adopting_VVG several_DA2 theoretical_JJ frameworks_NN2 ._. 
</s>
<s>
The_AT question_NN1 is_VBZ -_- can_VM we_PPIS2 take_VVI a_AT1 small_JJ step_NN1 towards_II describing_VVG the_AT customer_NN1 perceived_VVD value_NN1 in_II grocery_NN1 retail_JJ shopping_NN1 in_II a_AT1 more_RGR complete_JJ setting_NN1 ?_? 
</s>
<s>
This_DD1 study_NN1 will_VM use_VVI qualitative_JJ methods_NN2 documenting_VVG how_RRQ one_MC1 respondent_NN1 experiences_NN2 two_MC very_RG different_JJ retail_JJ store_NN1 alternatives_NN2 presented_VVN to_II him_PPHO1 ._. 
</s>
<s>
The_AT two_MC alternatives_NN2 can_VM in_II some_DD way_NN1 be_VBI considered_VVN as_CSA extremes_NN2 :_: Stockmann_NP1 Herkku_NP1 ,_, representing_VVG a_AT1 high-end_JJ choice_NN1 ;_; and_CC LIDL_NP1 ,_, representing_VVG a_AT1 cost-conscious_JJ alternative_NN1 ._. 
</s>
<s>
The_AT underlying_JJ fictional_JJ scenario_NN1 for_IF the_AT study_NN1 is_VBZ :_: if_CS the_AT respondent_NN1 would_VM move_VVI to_II a_AT1 new_JJ neighborhood_NN1 where_CS Stockmann_NP1 and_CC LIDL_NP1 are_VBR located_VVN equally_RR close_RR to_II home_NN1 ,_, based_VVN on_II which_DDQ retail_JJ store_NN1 specific_JJ aspects_NN2 would_VM the_AT respondent_NN1 evaluate_VVI and_CC choose_VVI a_AT1 preferred_JJ retail_JJ store_NN1 for_IF his_APPGE or_CC her_APPGE regular_JJ grocery_NN1 shopping_NN1 ?_? 1.2_MC ._. 
</s>
<s>
Aim_NN1 of_IO the_AT Study_NN1 The_AT aim_NN1 of_IO this_DD1 study_NN1 is_VBZ to_TO describe_VVI the_AT specific_JJ factors_NN2 that_CST a_AT1 consumer_NN1 considers_VVZ when_CS doing_VDG local_JJ grocery_NN1 shopping_NN1 ._. 
</s>
<s>
This_DD1 study_NN1 focuses_VVZ on_II two_MC different_JJ case_NN1 studies_NN2 that_CST can_VM be_VBI considered_VVN as_CSA extremes_NN2 :_: Stockmann_NP1 Herkku_NP1 and_CC LIDL_NP1 ._. 
</s>
<s>
The_AT aim_NN1 of_IO this_DD1 study_NN1 is_VBZ not_XX to_TO see_VVI which_DDQ grocery_NN1 retailer_NN1 the_AT consumer_NN1 respondent_NN1 actually_RR chooses_VVZ ,_, but_CCB rather_RR to_TO explore_VVI how_RRQ the_AT consumer_NN1 experiences_NN2 the_AT factors_NN2 involved_VVN when_CS faced_VVN with_IW two_MC extreme_JJ cases_NN2 ._. 
</s>
<s>
The_AT study_NN1 will_VM provide_VVI rich_JJ data_NN on_II how_RRQ the_AT respondent_NN1 experiences_NN2 the_AT stores_NN2 ._. 
</s>
<s>
The_AT results_NN2 can_VM be_VBI used_VVN by_II retail_JJ professionals_NN2 as_CSA support_NN1 for_IF further_RRR studying_VVG strategic_JJ positioning_NN1 questions_NN2 ._. 
</s>
<s>
1.3_MC ._. 
</s>
<s>
Structure_NN1 of_IO the_AT Study_NN1 This_DD1 study_NN1 is_VBZ structured_VVN in_II the_AT following_JJ way_NN1 :_: after_CS the_AT Introduction_NN1 part_NN1 I_PPIS1 present_VV0 theory_NN1 on_II Customer_NN1 Value_NN1 Propositions_NN2 and_CC Retail_JJ Shopping_NN1 ._. 
</s>
<s>
In_II chapter_NN1 three_MC I_PPIS1 present_VV0 the_AT Method_NN1 used_VVN for_IF the_AT study_NN1 ,_, this_DD1 chapter_NN1 includes_VVZ the_AT choice_NN1 of_IO Sampling_NN1 and_CC Observations_NN2 ._. 
</s>
<s>
In_II chapter_NN1 four_MC I_PPIS1 present_VV0 my_APPGE Analysis_NN1 ,_, which_DDQ is_VBZ followed_VVN by_II a_AT1 Discussion_NN1 part_NN1 in_II chapter_NN1 five_MC ._. 
</s>
<s>
Finally_RR ,_, in_II chapter_NN1 six_MC I_PPIS1 summarize_VV0 the_AT main_JJ findings_NN2 of_IO the_AT study_NN1 in_II the_AT Conclusions_NN2 chapter_NN1 ._. 
</s>
<s>
2_MC ._. 
</s>
<s>
Customer_NN1 Value_NN1 Propositions_NN2 and_CC Retail_JJ Shopping_NN1 The_AT theory_NN1 for_IF the_AT study_NN1 builds_VVZ upon_II customer_NN1 value_NN1 propositions_NN2 ._. 
</s>
<s>
In_II everyday_JJ shopping_NN1 the_AT consumer_NN1 experiences_NN2 the_AT following_JJ values_NN2 :_: economic_JJ value_NN1 ,_, functional_JJ value_NN1 ,_, emotional_JJ and_CC symbolic_JJ values_NN2 (_( Rintamki_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2007_MC in_II Vkel_NP1 2010_MC )_) ._. 
</s>
<s>
In_II31 addition_II32 to_II33 this_DD1 ,_, there_EX are_VBR also_RR other_JJ factors_NN2 presented_VVN in_II research_NN1 literature_NN1 that_CST can_VM affect_VVI the_AT consumers_NN2 choice_NN1 of_IO grocery_NN1 shopping_NN1 ._. 
</s>
<s>
Brands_NN2 have_VH0 a_AT1 clear_JJ role_NN1 ,_, especially_RR when_CS it_PPH1 comes_VVZ to_II the_AT products_NN2 available_JJ at_II the_AT retail_JJ store_NN1 (_( Fournier_NP1 1998_MC )_) ._. 
</s>
<s>
We_PPIS2 should_VM note_VVI that_CST the_AT brand_NN1 factor_NN1 can_VM also_RR be_VBI represented_VVN in_II the_AT emotional_JJ and_CC symbolic_JJ value_NN1 ._. 
</s>
<s>
Research_NN1 shows_VVZ that_CST especially_RR grocery_NN1 shopping_NN1 is_VBZ a_AT1 function_NN1 of_IO optimizing_VVG shopping_NN1 time_NNT1 and_CC price_NN1 ;_; that_REX21 is_REX22 ,_, the_AT consumer_NN1 wishes_VVZ to_TO spend_VVI as_RG little_DA1 time_NNT1 shopping_NN1 as_CSA possible_JJ (_( Messinger_NP1 and_CC Narasimhan_NP1 1997_MC )_) ._. 
</s>
<s>
Russell_NP1 and_CC Vincent-Wayne_NP1 (_( 1999_MC )_) found_VVD that_DD1 grocery_NN1 shopping_NN1 is_VBZ the_AT most_RGT stressful_JJ shopping_NN1 form_NN1 ._. 
</s>
<s>
Regarding_II these_DD2 theories_NN2 I_PPIS1 would_VM expect_VVI to_TO make_VVI observations_NN2 related_VVD to_TO stress_VVI and_CC hurry_NN1 of_IO the_AT subject_NN1 in_II the_AT field_NN1 ,_, and_CC this_DD1 in_II turn_NN1 will_VM affect_VVI the_AT experience_NN1 the_AT subject_NN1 has_VHZ of_IO the_AT retail_JJ store_NN1 ._. 
</s>
<s>
3_MC ._. 
</s>
<s>
Method_NN1 3.1_MC ._. 
</s>
<s>
Sampling_VVG According_II21 to_II22 Patton_NP1 (_( 2002_MC )_) ,_, sampling_NN1 is_VBZ to_TO design_VVI the_AT unit_NN1 or_CC units_NN2 of_IO analysis_NN1 ._. 
</s>
<s>
Sampling_VVG strategy_NN1 and_CC sample_NN1 size_NN1 depend_VV0 on_II decisions_NN2 about_II the_AT appropriate_JJ unit_NN1 of_IO analysis_NN1 to_TO study_VVI ._. 
</s>
<s>
There_EX is_VBZ a_AT1 wide_JJ range_NN1 of_IO sampling_VVG strategies_NN2 available_JJ to_II the_AT researcher_NN1 ._. 
</s>
<s>
For_IF this_DD1 study_NN1 I_PPIS1 have_VH0 chosen_VVN the_AT use_NN1 of_IO one_MC1 respondent_NN1 ._. 
</s>
<s>
Because_II21 of_II22 limited_JJ resources_NN2 ,_, this_DD1 is_VBZ done_VDN through_II convenience_NN1 sampling_NN1 combined_VVN with_IW criterion_NN1 sampling_NN1 ._. 
</s>
<s>
The_AT respondent_NN1 has_VHZ to_TO fulfill_VVI some_DD certain_JJ criteria_NN2 in_BCL21 order_BCL22 to_TO be_VBI purposeful_JJ for_IF this_DD1 study_NN1 (_( Patton_NP1 2002_MC )_) ._. 
</s>
<s>
It_PPH1 should_VM be_VBI noted_VVN that_CST the_AT income_NN1 level_NN1 of_IO the_AT consumer_NN1 /_FO respondent_NN1 will_VM affect_VVI the_AT choice_NN1 of_IO preferred_JJ grocery_NN1 retailer_NN1 to_II a_AT1 large_JJ extent_NN1 ._. 
</s>
<s>
Therefore_RR ,_, the_AT chosen_JJ respondent_NN1 has_VHZ a_AT1 medium_JJ high_JJ income_NN1 ,_, so_CS21 that_CS22 he_PPHS1 would_VM have_VHI the_AT possibility_NN1 to_TO choose_VVI either_RR one_MC1 of_IO the_AT stores_NN2 ._. 
</s>
<s>
Naturally_RR ,_, it_PPH1 could_VM be_VBI expected_VVN that_CST he_PPHS1 would_VM prefer_VVI Stockmann_NP1 Herkku_NP1 because_II21 of_II22 income_NN1 level_NN1 ._. 
</s>
<s>
However_RR ,_, this_DD1 is_VBZ not_XX completely_RR relevant_JJ for_IF this_DD1 particular_JJ study_NN1 ;_; by_II experiencing_VVG the_AT two_MC extreme_JJ cases_NN2 ,_, this_DD1 study_NN1 aims_VVZ to_TO find_VVI out_RP what_DDQ are_VBR the_AT factors_NN2 that_CST this_DD1 particular_JJ consumer_NN1 appreciates_VVZ and_CC dislikes_VVZ in_II the_AT two_MC retail_JJ stores_NN2 in_BCL21 order_BCL22 to_TO define_VVI the_AT factors_NN2 involved_VVD ._. 
</s>
<s>
My_APPGE main_JJ subject_NN1 is_VBZ Daniel_NP1 ,_, who_PNQS is_VBZ my_APPGE husband_NN1 ._. 
</s>
<s>
For_IF the_AT case_NN1 of_IO shopping_NN1 type_NN1 I_PPIS1 chose_VVD groceries_NN2 for_IF my_APPGE sample_NN1 ,_, because_CS grocery_NN1 shopping_NN1 is_VBZ done_VDN regularly_RR and_CC therefore_RR concerned_JJ with_IW loyalty_NN1 ._. 
</s>
<s>
It_PPH1 has_VHZ been_VBN shown_VVN that_DD1 food_NN1 shopping_NN1 involves_VVZ feelings_NN2 and_CC is_VBZ also_RR related_VVN to_II the_AT identity_NN1 of_IO the_AT consumer_NN1 (_( Vkel_NP1 2010_MC )_) ._. 
</s>
<s>
The_AT study_NN1 builds_VVZ upon_II the_AT case_NN1 of_IO testing_VVG two_MC extreme_JJ cases_NN2 of_IO retail_JJ stores_NN2 -_- upscale_NN1 vs._II affordable_JJ ;_; the_AT sample_NN1 chosen_VVN is_VBZ Stockmann_NP1 Herkku_NP1 and_CC LIDL_NP1 ._. 
</s>
<s>
They_PPHS2 are_VBR actually_RR located_VVN close_RR to_II each_PPX221 other_PPX222 in_II Helsinki_NP1 center_NN1 and_CC the_AT consumer_NN1 could_VM in_II fact_NN1 be_VBI faced_VVN with_IW choosing_VVG one_MC1 of_IO these_DD2 stores_NN2 for_IF regular_JJ grocery_NN1 shopping_NN1 ._. 
</s>
<s>
I_PPIS1 make_VV0 the_AT limitation_NN1 and_CC assumption_NN1 that_CST a_AT1 consumer_NN1 will_VM choose_VVI one_MC1 single_JJ retail_JJ store_NN1 where_CS he_PPHS1 or_CC she_PPHS1 will_VM favor_VVI to_TO do_VDI regular_JJ grocery_NN1 shopping_VVG as_II a_AT1 loyal_JJ customer_NN1 ._. 
</s>
<s>
The_AT time_NNT1 of_IO the_AT shopping_NN1 event_NN1 and_CC observation_NN1 has_VHZ been_VBN chosen_VVN to_TO realistically_RR represent_VVI a_AT1 typical_JJ situation_NN1 when_CS most_DAT people_NN do_VD0 their_APPGE grocery_NN1 shopping_NN1 (_( Patton_NP1 2002_MC )_) ._. 
</s>
<s>
Finally_RR ,_, I_PPIS1 have_VH0 chosen_VVN to_TO do_VDI the_AT interview_NN1 the_AT day_NNT1 after_II the_AT shopping_NN1 event_NN1 ._. 
</s>
<s>
By_II doing_VDG so_RR ,_, I_PPIS1 believe_VV0 the_AT event_NN1 will_VM be_VBI fresh_JJ in_II mind_NN1 for_IF the_AT respondent_NN1 ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 ,_, if_CS the_AT interview_NN1 would_VM have_VHI taken_VVN place_NN1 immediately_RR after_II the_AT event_NN1 ,_, the_AT results_NN2 might_VM be_VBI biased_VVN due_II21 to_II22 the_AT stress_NN1 from_II shopping_NN1 ,_, tiredness_NN1 or_CC other_JJ enhanced_JJ feelings_NN2 of_IO the_AT moment_NN1 ._. 
</s>
<s>
3.2_MC ._. 
</s>
<s>
Observations_NN2 My_APPGE observation_NN1 approach_NN1 for_IF studying_VVG the_AT shopping_NN1 events_NN2 of_IO the_AT respondent_NN1 can_VM be_VBI described_VVN as_CSA naturalistic_JJ ._. 
</s>
<s>
Naturalism_NN1 or_CC naturalistic_JJ observation_NN1 is_VBZ commonly_RR used_VVN by_II social_JJ scientists_NN2 and_CC refers_VVZ to_II observing_VVG the_AT subjects_NN2 in_II a_AT1 natural_JJ environment_NN1 (_( Belk_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
1988_MC )_) ._. 
</s>
<s>
I_PPIS1 used_VVD three_MC different_JJ sources_NN2 for_IF gathering_VVG data_NN :_: photos_NN2 ,_, field_NN1 observations_NN2 ,_, and_CC an_AT1 interview_NN1 ._. 
</s>
<s>
For_IF doing_VDG the_AT fieldwork_NN1 I_PPIS1 had_VHD a_AT1 few_DA2 choices_NN2 regarding_II the_AT technique_NN1 to_TO use_VVI ._. 
</s>
<s>
Firstly_RR ,_, should_VM I_PPIS1 myself_PPX1 be_VBI a_AT1 participant_NN1 or_CC should_VM this_DD1 be_VBI a_AT1 non-participant_JJ observation_NN1 Silverman_NN1 (_( 2006_MC )_) ._. 
</s>
<s>
Belk_VV0 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 1988_MC )_) state_VV0 that_CST typically_RR ,_, a_AT1 naturalistic_JJ researcher_NN1 travels_VVZ along_II the_AT continuum_NN1 from_II passive_NN1 to_II participant_NN1 observation_NN1 ._. 
</s>
<s>
I_PPIS1 realize_VV0 that_CST it_PPH1 would_VM be_VBI very_RG difficult_JJ to_TO maintain_VVI a_AT1 non-participant_JJ role_NN1 and_CC passively_RR observe_VV0 my_APPGE subject_NN1 in_II this_DD1 case_NN1 ._. 
</s>
<s>
If_CS we_PPIS2 would_VM not_XX know_VVI each_PPX221 other_PPX222 ,_, it_PPH1 might_VM be_VBI a_AT1 possibility_NN1 to_TO do_VDI observation_NN1 from_II aside_RL ;_; however_RR ,_, I_PPIS1 am_VBM used_JJ to_II shopping_VVG together_RL with_IW Daniel_NP1 and_CC I_PPIS1 believe_VV0 the_AT best_JJT option_NN1 is_VBZ participant_NN1 observation_NN1 ._. 
</s>
<s>
Therefore_RR ,_, I_PPIS1 chose_VVD the_AT most_RGT natural_JJ setting_NN1 that_CST can_VM be_VBI made_VVN :_: me_PPIO1 and_CC Daniel_NP1 are_VBR shopping_VVG together_RL just_RR as_CSA we_PPIS2 normally_RR would_VM do_VDI ,_, except_CS21 that_CS22 I_PPIS1 am_VBM making_VVG field_NN1 notes_NN2 and_CC documenting_VVG at_II the_AT same_DA time_NNT1 ._. 
</s>
<s>
By_II being_VBG a_AT1 participant_NN1 ,_, the_AT observer_NN1 can_VM pick_VVI up_RP on_II different_JJ things_NN2 ,_, for_REX21 example_REX22 ,_, on_II the_AT mood_NN1 and_CC frustration_NN1 of_IO a_AT1 subject_NN1 ._. 
</s>
<s>
3.2.1_MC ._. 
</s>
<s>
Photos_NN2 During_II our_APPGE visit_NN1 to_II the_AT two_MC grocery_NN1 stores_NN2 I_PPIS1 was_VBDZ documenting_VVG Daniels_NP1 shopping_NN1 by_II taking_VVG photos_NN2 with_IW my_APPGE phone_NN1 camera_NN1 ._. 
</s>
<s>
I_PPIS1 took_VVD a_AT1 total_NN1 of_IO 75_MC photos_NN2 during_II the_AT shopping_NN1 in_II both_DB2 stores_NN2 ._. 
</s>
<s>
Belk_VV0 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 1988_MC )_) state_VV0 that_CST it_PPH1 is_VBZ standard_JJ practice_NN1 to_TO record_VVI as_RG much_DA1 detail_NN1 as_CSA possible_JJ ,_, usually_RR well_RR beyond_II what_DDQ the_AT inquirer_NN1 at_II the_AT time_NNT1 thinks_VVZ will_VM be_VBI necessary_JJ ._. 
</s>
<s>
Out_II21 of_II22 the_AT 75_MC photos_NN2 I_PPIS1 chose_VVD 18_MC that_CST I_PPIS1 found_VVD particularly_RR interesting_JJ for_IF this_DD1 study_NN1 ;_; 9_MC were_VBDR taken_VVN in_II Stockmann_NP1 Herkku_NP1 and_CC 9_MC in_II LIDL_NP1 ._. 
</s>
<s>
These_DD2 photos_NN2 can_VM be_VBI found_VVN in_II Appendix_NN1 1_MC1 ._. 
</s>
<s>
The_AT photo_NN1 data_NN has_VHZ been_VBN categorized_VVN in_II two_MC sets_NN2 according_II21 to_II22 the_AT shopping_NN1 site_NN1 ,_, each_DD1 exhibit_NN1 is_VBZ numbered_VVN in_II the_AT appendix_NN1 ._. 
</s>
<s>
3.2.2_MC ._. 
</s>
<s>
Field_NN1 Notes_NN2 During_II the_AT shopping_NN1 I_PPIS1 took_VVD field_NN1 notes_NN2 ;_; the_AT day_NNT1 after_II the_AT field_NN1 research_NN1 I_PPIS1 went_VVD through_II the_AT notes_NN2 and_CC added_VVD a_AT1 few_DA2 things_NN2 that_CST came_VVD to_II my_APPGE mind_NN1 ._. 
</s>
<s>
In_II31 addition_II32 to_II33 the_AT observational_JJ field_NN1 notes_NN2 ,_, which_DDQ I_PPIS1 made_VVD on_II the_AT subject_NN1 and_CC the_AT surroundings_NN2 ,_, I_PPIS1 also_RR documented_VVD a_AT1 self-reflection_JJ part_NN1 ._. 
</s>
<s>
All_DB of_IO these_DD2 texts_NN2 can_VM be_VBI found_VVN in_II Appendix_NN1 2_MC ._. 
</s>
<s>
Self-reflection_NN1 is_VBZ important_JJ in_II order_NN1 to_TO openly_RR show_VVI the_AT reader_NN1 how_RRQ the_AT research_NN1 was_VBDZ conducted_VVN and_CC also_RR the_AT possible_JJ mistakes_NN2 ;_; this_DD1 adds_VVZ to_II the_AT reliability_NN1 of_IO the_AT research_NN1 ._. 
</s>
<s>
The_AT researchers_NN2 journals_NN2 contain_VV0 valuable_JJ information_NN1 that_CST can_VM add_VVI to_II the_AT observations_NN2 and_CC results_NN2 of_IO the_AT study_NN1 (_( Belk_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
1988_MC )_) ._. 
</s>
<s>
In_II my_APPGE field_NN1 notes_VVZ I_PPIS1 have_VH0 preliminary_JJ categorized_VVD my_APPGE data_NN according_II21 to_II22 the_AT observations_NN2 in_II chronological_JJ order_NN1 (_( see_VV0 Appendix_NN1 2_MC )_) ._. 
</s>
<s>
As_CSA this_DD1 study_NN1 contains_VVZ a_AT1 quite_RG small_JJ amount_NN1 of_IO data_NN ,_, I_PPIS1 consider_VV0 that_CST no_AT further_JJR categorization_NN1 was_VBDZ needed_VVN ._. 
</s>
<s>
In_II chapter_NN1 4_MC of_IO this_DD1 report_NN1 the_AT observations_NN2 will_VM be_VBI coded_VVN according_II21 to_II22 emerging_JJ patterns_NN2 of_IO the_AT research_NN1 focus_NN1 ._. 
</s>
<s>
3.2.3_MC ._. 
</s>
<s>
Interviews_NN2 The_AT interview_NN1 with_IW my_APPGE subject_NN1 ,_, Daniel_NP1 ,_, was_VBDZ carried_VVN out_RP on_II Monday_NPD1 ,_, Feb_NPM1 14th_MD 2011_MC ._. 
</s>
<s>
That_DD1 was_VBDZ two_MC days_NNT2 after_II the_AT shopping_NN1 took_VVD place_NN1 in_II the_AT field_NN1 ._. 
</s>
<s>
The_AT interview_NN1 was_VBDZ carried_VVN out_RP at_II our_APPGE home_NN1 and_CC we_PPIS2 did_VDD not_XX have_VHI any_DD significant_JJ time_NNT1 limit_NN1 ._. 
</s>
<s>
Patton_NP1 (_( 2002_MC )_) reports_VVZ that_CST using_VVG an_AT1 open-ended_JJ interview_NN1 can_VM provide_VVI the_AT most_RGT detailed_JJ and_CC deep_JJ understanding_NN1 of_IO subjective_JJ matters_NN2 ._. 
</s>
<s>
However_RR ,_, for_IF an_AT1 inexperienced_JJ interviewer_NN1 using_VVG this_DD1 technique_NN1 it_PPH1 is_VBZ risky_JJ since_CS it_PPH1 requires_VVZ the_AT most_DAT skill_NN1 in_II the_AT interviewer_NN1 ._. 
</s>
<s>
Therefore_RR ,_, I_PPIS1 believe_VV0 it_PPH1 was_VBDZ motivated_VVN to_TO use_VVI an_AT1 interview_NN1 guide_NN1 to_TO establish_VVI the_AT topics_NN2 of_IO interest_NN1 that_CST were_VBDR to_TO be_VBI covered_VVN during_II the_AT interview_NN1 ._. 
</s>
<s>
The_AT interview_NN1 guide_VV0 that_DD1 was_VBDZ prepared_VVN can_VM be_VBI found_VVN in_II Appendix_NN1 3_MC ._. 
</s>
<s>
The_AT interview_NN1 guide_NN1 was_VBDZ structured_VVN in_II different_JJ topics_NN2 according_II21 to_II22 the_AT theoretical_JJ framework_NN1 on_II customer_NN1 value_NN1 propositions_NN2 :_: price_NN1 ,_, quality_NN1 ,_, and_CC emotions_NN2 ._. 
</s>
<s>
Also_RR ,_, the_AT focus_NN1 on_II time_NNT1 and_CC cost_NN1 optimization_NN1 theory_NN1 lead_NN1 to_II a_AT1 topic_NN1 on_II time_NNT1 ._. 
</s>
<s>
An_AT1 important_JJ part_NN1 was_VBDZ also_RR to_TO determine_VVI the_AT feelings_NN2 involved_JJ with_IW shopping_NN1 ,_, there_EX is_VBZ a_AT1 separate_JJ set_NN1 of_IO questions_NN2 focused_VVN on_II the_AT emotions_NN2 of_IO the_AT interviewee_NN1 ,_, for_REX21 example_REX22 ,_, what_DDQ feelings_NN2 arouse_VV0 in_II the_AT stores_NN2 ?_? ._. 
</s>
<s>
In_II31 addition_II32 to_II33 using_VVG the_AT interview_NN1 guide_NN1 ,_, I_PPIS1 decided_VVD to_TO use_VVI a_AT1 projection_NN1 technique_NN1 at_II the_AT end_NN1 of_IO the_AT interview_NN1 ._. 
</s>
<s>
A_AT1 projection_NN1 technique_NN1 can_VM refer_VVI to_II using_VVG photos_NN2 or_CC other_JJ documents_NN2 in_II order_NN1 to_II getting_VVG the_AT interviewee_NN1 to_TO recall_VVI things_NN2 better_RRR (_( Patton_NP1 2002_MC )_) ._. 
</s>
<s>
Since_CS I_PPIS1 had_VHD the_AT photos_NN2 from_II the_AT field_NN1 when_CS we_PPIS2 were_VBDR shopping_VVG ,_, I_PPIS1 decided_VVD that_CST showing_VVG them_PPHO2 to_II Daniel_NP1 might_VM make_VVI him_PPHO1 remember_VVI some_DD details_NN2 and_CC maybe_RR reflect_VV0 on_II things_NN2 in_II a_AT1 different_JJ way_NN1 ,_, once_CS he_PPHS1 has_VHZ some_DD distance_NN1 to_II the_AT event_NN1 ._. 
</s>
<s>
4_MC ._. 
</s>
<s>
Analysis_NN1 4.1_MC ._. 
</s>
<s>
Analysis_NN1 of_IO Field_NN1 Notes_NN2 and_CC Photos_NN2 An_AT1 early_JJ concept_NN1 for_IF further_JJR investigation_NN1 was_VBDZ to_TO divide_VVI the_AT factors_NN2 that_CST affect_VV0 the_AT consumer_NN1 the_AT most_RRT into_II a_AT1 few_DA2 categories_NN2 with_IW subcategories_NN2 ._. 
</s>
<s>
For_IF reaching_VVG the_AT abstraction_NN1 of_IO which_DDQ concepts_NN2 to_TO use_VVI ,_, a_AT1 number_NN1 of_IO processes_NN2 were_VBDR used_VVN :_: comparison_NN1 ,_, dimensionalization_NN1 ,_, integration_NN1 ,_, iteration_NN1 ,_, and_CC refutation_NN1 (_( Spiggle_NP1 1994_MC )_) ._. 
</s>
<s>
Because_CS this_DD1 study_NN1 is_VBZ faced_VVN with_IW two_MC competing_JJ alternatives_NN2 or_CC samples_NN2 ,_, Stockmann_NP1 Herkku_NP1 and_CC LIDL_NP1 ,_, it_PPH1 is_VBZ natural_JJ to_TO use_VVI comparison_NN1 as_II an_AT1 important_JJ tool_NN1 for_IF analysis_NN1 ._. 
</s>
<s>
Comparison_NN1 is_VBZ done_VDN throughout_II the_AT research_NN1 and_CC shows_VVZ similarities_NN2 and_CC differences_NN2 (_( Spiggle_NP1 1994_MC )_) ._. 
</s>
<s>
The_AT dimensional_JJ ranges_NN2 are_VBR presented_VVN below_RL in_II Table_NN1 5_MC and_CC the_AT respective_JJ observations_NN2 in_II Table_NN1 6_MC ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) &lsqb;_( Table_NN1 &rsqb;_) I_PPIS1 used_VVD the_AT photos_NN2 recorded_VVN in_II the_AT field_NN1 mainly_RR as_II a_AT1 tool_NN1 for_IF recollecting_VVG the_AT events_NN2 ,_, both_RR for_IF me_PPIO1 and_CC the_AT interviewee_NN1 during_II the_AT interview_NN1 ._. 
</s>
<s>
The_AT exhibits_NN2 in_II Appendix_NN1 1_MC1 will_VM hopefully_RR help_VVI the_AT reader_NN1 to_TO relate_VVI with_IW the_AT experiment_NN1 ._. 
</s>
<s>
I_PPIS1 will_VM briefly_RR point_VVI out_RP the_AT most_RGT interesting_JJ observations_NN2 within_II the_AT photos_NN2 ._. 
</s>
<s>
In_II Exhibit_NN1 1_MC1 we_PPIS2 see_VV0 the_AT entrance_NN1 to_II Stockmann_NP1 ;_; Daniel_NP1 points_VVZ out_RP in_II the_AT interview_NN1 that_CST Stockmann_NP1 was_VBDZ really_RR crowded_VVN ._. 
</s>
<s>
However_RR ,_, by_II looking_VVG at_II the_AT photos_NN2 from_II Stockmann_NP1 and_CC LIDL_NP1 (_( Exhibit_VV0 10._MC )_) ,_, it_PPH1 seems_VVZ that_CST there_EX were_VBDR equally_RR much_DA1 people_NN in_II the_AT shopping_NN1 space_NN1 of_IO both_DB2 stores_NN2 ._. 
</s>
<s>
Stockmanns_NP1 store_NN1 is_VBZ nevertheless_RR very_RG differently_RR designed_VVN ,_, especially_RR in_II the_AT vegetables_NN2 area_NN1 customers_NN2 can_VM move_VVI in_II all_DB directions_NN2 between_II shelves_NN2 ,_, whereas_CS in_II LIDL_NP1 the_AT corridors_NN2 are_VBR straight_JJ and_CC customers_NN2 can_VM not_XX move_VVI in_II any_DD direction_NN1 ._. 
</s>
<s>
The_AT Stockmann_NP1 design_NN1 seems_VVZ more_RGR attractive_JJ to_II the_AT eye_NN1 probably_RR ,_, but_CCB LIDLs_VVZ design_NN1 is_VBZ clearly_RR more_RGR practical_JJ during_II rush_NN1 hours_NNT2 ._. 
</s>
<s>
In_II Exhibit_NN1 8_MC we_PPIS2 see_VV0 Daniel_NP1 yawning_VVG at_II the_AT cashier_NN1 ._. 
</s>
<s>
Additional_JJ data_NN in_II the_AT interview_NN1 and_CC field_NN1 notes_NN2 support_VV0 that_CST the_AT shopping_NN1 experience_NN1 in_II Stockmann_NP1 Herkku_NP1 was_VBDZ not_XX in_II any_DD way_NN1 exciting_JJ and_CC was_VBDZ focused_VVN on_II getting_VVG the_AT items_NN2 on_II the_AT shopping_NN1 list_NN1 ._. 
</s>
<s>
4.2_MC ._. 
</s>
<s>
Analysis_NN1 of_IO the_AT Interview_NN1 In_II the_AT previous_JJ chapter_NN1 I_PPIS1 have_VH0 described_VVN my_APPGE process_NN1 of_IO analyzing_VVG field_NN1 notes_NN2 and_CC photos_NN2 ._. 
</s>
<s>
The_AT analysis_NN1 of_IO the_AT interview_NN1 follows_VVZ the_AT same_DA concepts_NN2 and_CC methods_NN2 described_VVN there_RL ._. 
</s>
<s>
According_II21 to_II22 theory_NN1 (_( Fournier_NP1 1998_MC )_) the_AT brand_NN1 will_VM matter_VVI when_RRQ shopping_NN1 ._. 
</s>
<s>
In_II the_AT interview_NN1 material_NN1 I_PPIS1 also_RR found_VVN suggestions_NN2 for_IF this_DD1 being_VBG true_JJ :_: I_PPIS1 would_VM expect_VVI to_TO find_VVI all_DB things_NN2 in_II Stockmann_NP1 ._. 
</s>
<s>
Its_APPGE a_AT1 large_JJ department_NN1 store_NN1 that_CST has_VHZ everything_PN1 and_CC has_VHZ a_AT1 good_JJ name_NN1 for_IF it_PPH1 ._. 
</s>
<s>
It_PPH1 seems_VVZ here_RL that_CST Daniel_NP1 was_VBDZ expecting_VVG Stockmann_NP1 to_TO have_VHI everything_PN1 ,_, but_CCB since_CS Stockmann_NP1 did_VDD not_XX ,_, he_PPHS1 experienced_VVD a_AT1 disappointment_NN1 ._. 
</s>
<s>
This_DD1 could_VM be_VBI compared_VVN with_IW service_NN1 marketing_NN1 theory_NN1 on_II how_RRQ a_AT1 service_NN1 gap_NN1 will_VM have_VHI negative_JJ effects_NN2 (_( Grnroos_NP1 2007_MC )_) ._. 
</s>
<s>
A_AT1 further_JJR quote_NN1 from_II the_AT interviewee_NN1 states_VVZ that_CST it_PPH1 matters_VVZ that_CST he_PPHS1 did_VDD nt_XX find_VVI what_DDQ he_PPHS1 expected_VVD :_: Well_RR I_PPIS1 guess_VV0 ,_, its_APPGE annoying_JJ if_CS you_PPY do_VD0 nt_XX find_VVI what_DDQ you_PPY came_VVD for_IF ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 of_IO this_DD1 issue_NN1 there_EX were_VBDR interesting_JJ observations_NN2 on_II how_RRQ Daniel_NP1 found_VVD items_NN2 that_CST were_VBDR not_XX on_II his_APPGE shopping_NN1 list_NN1 in_II LIDL_NP1 ._. 
</s>
<s>
The_AT field_NN1 observations_NN2 state_VV0 that_CST the_AT shopping_NN1 in_II LIDL_NP1 was_VBDZ more_RGR relaxed_JJ and_CC that_CST the_AT shoppers_NN2 talked_VVD more_RRR ._. 
</s>
<s>
In_II LIDL_NP1 there_EX were_VBDR several_DA2 items_NN2 bought_VVD that_CST were_VBDR not_XX on_II the_AT original_JJ shopping_NN1 list_NN1 ,_, I_PPIS1 call_VV0 this_DD1 impulse_NN1 buying_VVG in_II my_APPGE construct_NN1 in_II Table_NN1 5_MC ._. 
</s>
<s>
On_II the_AT question_NN1 whether_CSW Daniel_NP1 was_VBDZ happy_JJ with_IW the_AT shopping_NN1 experience_NN1 at_II LIDL_NP1 ,_, his_APPGE answer_NN1 was_VBDZ :_: Yes_UH ,_, very_JJ !_! 
</s>
<s>
We_PPIS2 got_VVD a_AT1 lot_NN1 of_IO useful_JJ stuff_NN1 that_CST we_PPIS2 need_VV0 ._. 
</s>
<s>
I_PPIS1 really_RR planned_VVD to_TO get_VVI those_DD2 Omega_NN1 3_MC ,_, but_CCB I_PPIS1 just_RR forgot_VVD or_CC do_VD0 nt_XX have_VHI time_NNT1 to_TO go_VVI looking_VVG ._. 
</s>
<s>
Daniel_NP1 is_VBZ clearly_RR happy_JJ with_IW the_AT outcome_NN1 of_IO the_AT shopping_NN1 at_II LIDL_NP1 and_CC immediately_RR states_VVZ that_CST all_DB the_AT necessary_JJ purchases_NN2 were_VBDR done_VDN and_CC even_RR some_DD extra_JJ ._. 
</s>
<s>
This_DD1 statement_NN1 is_VBZ very_RG interesting_JJ and_CC leads_VVZ to_II the_AT observation_NN1 that_DD1 time_NNT1 and_CC productivity_NN1 of_IO the_AT shopping_NN1 is_VBZ a_AT1 very_RG important_JJ factor_NN1 ._. 
</s>
<s>
Concerning_II the_AT efficiency_NN1 of_IO shopping_NN1 I_PPIS1 have_VH0 also_RR noted_VVN during_II the_AT field_NN1 research_NN1 that_CST stress_NN1 influenced_VVN the_AT behavior_NN1 of_IO Daniel_NP1 as_CSA he_PPHS1 was_VBDZ shopping_VVG ._. 
</s>
<s>
Later_RRR in_II the_AT interview_NN1 he_PPHS1 also_RR brings_VVZ it_PPH1 up_RP :_: Stockmann_NP1 was_VBDZ really_RR stressful_JJ !_! 
</s>
<s>
There_EX were_VBDR so_RG much_DA1 people_NN and_CC you_PPY bumped_VVD into_II people_NN all_DB the_AT time_NNT1 ._. 
</s>
<s>
LIDL_NP1 felt_VVD much_RR more_RGR comfortable_JJ in_II that_DD1 way_NN1 ._. 
</s>
<s>
Later_RRR when_CS talking_VVG about_II the_AT brand_NN1 image_NN1 of_IO LIDL_NP1 ,_, he_PPHS1 also_RR comments_VVZ :_: LIDL_NP1 is_VBZ all_DB about_II cheap_JJ ;_; they_PPHS2 have_VH0 stuff_NN1 in_II huge_JJ piles_NN2 and_CC neon_NN1 signs_NN2 with_IW great_JJ offers_NN2 ._. 
</s>
<s>
I_MC1 cant_NN1 say_VV0 that_CST I_PPIS1 like_VV0 that_CST ,_, but_CCB still_RR I_PPIS1 felt_VVD much_RR better_RRR in_II LIDL_NP1 because_CS there_EX was_VBDZ much_DA1 less_DAR stress_NN1 ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, for_IF Daniel_NP1 minimizing_VVG stress_NN1 is_VBZ more_RGR important_JJ than_CSN the_AT brand_NN1 image_NN1 of_IO the_AT store_NN1 ._. 
</s>
<s>
In_II our_APPGE setting_NN1 we_PPIS2 are_VBR interested_JJ in_II which_DDQ store_VV0 Daniel_NP1 would_VM choose_VVI in_CS21 case_CS22 he_PPHS1 was_VBDZ moving_VVG into_II the_AT area_NN1 were_VBDR Stockmann_NP1 Herkku_NP1 and_CC LIDL_NP1 are_VBR located_VVN ,_, to_II this_DD1 question_NN1 he_PPHS1 answered_VVD :_: I_PPIS1 would_VM choose_VVI LIDL_NN1 for_IF basic_JJ need_VV0 shopping_NN1 ._. 
</s>
<s>
Its_APPGE quicker_JJR ,_, easier_RRR and_CC less_RGR stressful_JJ ._. 
</s>
<s>
But_II21 for_II22 getting_VVG better_JJR products_NN2 ,_, maybe_RR for_IF some_DD weekends_NNT2 and_CC dinners_NN2 I_PPIS1 would_VM go_VVI to_II Stockmann_NP1 ._. 
</s>
<s>
Just_RR as_CSA in_II the_AT case_NN1 of_IO field_NN1 work_NN1 and_CC doing_VDG field_NN1 notes_VVZ it_PPH1 is_VBZ important_JJ for_IF the_AT researcher_NN1 to_TO analyze_VVI the_AT process_NN1 in_II a_AT1 critical_JJ fashion_NN1 ._. 
</s>
<s>
The_AT reflections_NN2 of_IO the_AT researcher_NN1 can_VM provide_VVI additional_JJ insight_NN1 for_IF the_AT reader_NN1 ._. 
</s>
<s>
During_II the_AT interview_NN1 I_PPIS1 was_VBDZ trying_VVG to_TO observe_VVI the_AT behavior_NN1 of_IO Daniel_NP1 as_II31 well_II32 as_II33 critically_RR analyzing_VVG my_APPGE own_DA behavior_NN1 and_CC my_APPGE interviewing_JJ technique_NN1 ._. 
</s>
<s>
The_AT interview_NN1 was_VBDZ in_RR21 general_RR22 pretty_RG smooth_JJ and_CC easy_JJ to_TO do_VDI because_CS Daniel_NP1 was_VBDZ really_RR eager_JJ to_TO help_VVI out_RP ._. 
</s>
<s>
However_RR ,_, this_DD1 might_VM not_XX have_VHI been_VBN the_AT case_NN1 with_IW someone_PN1 unknown_JJ ._. 
</s>
<s>
Therefore_RR ,_, I_PPIS1 do_VD0 realize_VVI that_CST there_EX were_VBDR some_DD things_NN2 lacking_VVG in_II my_APPGE interview_NN1 guide_NN1 and_CC technique_NN1 ._. 
</s>
<s>
Some_DD of_IO my_APPGE original_JJ questions_NN2 were_VBDR designed_VVN in_II a_AT1 dichotomous_JJ way_NN1 ;_; that_REX21 is_REX22 ,_, the_AT answer_NN1 is_VBZ often_RR yes_UH or_CC no_UH ._. 
</s>
<s>
Fortunately_RR ,_, the_AT respondent_NN1 in_II this_DD1 case_NN1 still_RR elaborated_VVN on_II the_AT answers_NN2 ._. 
</s>
<s>
I_PPIS1 have_VH0 developed_VVN an_AT1 improved_JJ interview_NN1 guide_NN1 to_TO point_VVI out_RP these_DD2 possible_JJ improvements_NN2 that_CST could_VM have_VHI resulted_VVN in_II a_AT1 deeper_JJR and_CC more_RGR enlightening_JJ interview_NN1 ._. 
</s>
<s>
4.3_MC ._. 
</s>
<s>
Integrated_JJ construct_VV0 For_IF reaching_VVG constructs_NN2 that_CST can_VM evolve_VVI into_II theory_NN1 ,_, the_AT researcher_NN1 uses_VVZ an_AT1 approach_NN1 of_IO integration_NN1 ._. 
</s>
<s>
This_DD1 refers_VVZ to_II integrating_VVG constructs_NN2 and_CC categories_NN2 that_CST have_VH0 been_VBN found_VVN (_( Strauss_NP1 and_CC Corbin_NP1 1990_MC ,_, in_II Spiggle_NP1 1994_MC )_) ._. 
</s>
<s>
For_IF this_DD1 study_NN1 the_AT integration_NN1 will_VM look_VVI at_II integrating_VVG the_AT observations_NN2 and_CC the_AT interview_NN1 results_NN2 ._. 
</s>
<s>
In_II table_NN1 7_MC I_PPIS1 present_VV0 an_AT1 integrated_JJ construct_VV0 that_CST divides_VVZ the_AT factors_NN2 involved_JJ in_II grocery_NN1 shopping_VVG into_II two_MC categories_NN2 :_: 1_MC1 )_) consumer_NN1 oriented_VVD factors_NN2 ,_, and_CC 2_MC )_) product_NN1 and_CC store_NN1 oriented_VVD factors_NN2 ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) My_APPGE analysis_NN1 of_IO field_NN1 notes_NN2 ,_, photos_NN2 ,_, and_CC an_AT1 interview_NN1 shows_VVZ that_CST there_EX are_VBR many_DA2 factors_NN2 involved_VVN when_CS shopping_NN1 groceries_NN2 ._. 
</s>
<s>
I_PPIS1 have_VH0 divided_VVN the_AT factors_NN2 in_II two_MC general_JJ categories_NN2 :_: 1_MC1 )_) consumer_NN1 oriented_VVD factors_NN2 (_( time_NNT1 optimization_NN1 ,_, stress_NN1 ,_, convenience_NN1 )_) ;_; and_CC 2_MC )_) product_NN1 and_CC store_NN1 oriented_VVD factors_NN2 (_( price_NN1 ,_, quality_NN1 ,_, brand_NN1 ,_, service_NN1 )_) ._. 
</s>
<s>
Rintamki_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2007_MC )_) present_JJ customer_NN1 value_NN1 propositions_NN2 as_II a_AT1 way_NN1 for_IF determining_VVG what_DDQ matters_VVZ in_II grocery_NN1 shopping_NN1 ._. 
</s>
<s>
These_DD2 value_NN1 propositions_NN2 are_VBR :_: economic_JJ value_NN1 ,_, functional_JJ value_NN1 ,_, emotional_JJ ,_, and_CC symbolic_JJ value_NN1 ._. 
</s>
<s>
My_APPGE data_NN and_CC analysis_NN1 found_VVD some_DD support_VV0 that_CST all_DB of_IO these_DD2 things_NN2 matter_VV0 for_IF the_AT respondent_NN1 Daniel_NP1 when_CS choosing_VVG a_AT1 grocery_NN1 store_NN1 ;_; however_RR ,_, none_PN of_IO them_PPHO2 were_VBDR very_RG important_JJ ._. 
</s>
<s>
He_PPHS1 did_VDD not_XX compare_VVI prices_NN2 ,_, and_CC thought_NN1 prices_NN2 for_IF groceries_NN2 do_VD0 not_XX vary_VVI much_RR ._. 
</s>
<s>
He_PPHS1 had_VHD tested_VVN most_DAT of_IO the_AT products_NN2 after_II the_AT shopping_NN1 and_CC did_VDD not_XX see_VVI any_DD major_JJ difference_NN1 between_II product_NN1 brands_NN2 ._. 
</s>
<s>
He_PPHS1 might_VM favor_VVI domestic_JJ products_NN2 slightly_RR because_II21 of_II22 ideals_NN2 but_CCB not_XX because_II21 of_II22 quality_NN1 ._. 
</s>
<s>
The_AT brand_NN1 factors_NN2 impact_NN1 is_VBZ difficult_JJ to_TO determine_VVI in_II this_DD1 study_NN1 ;_; Daniel_NP1 was_VBDZ clearly_RR aware_JJ that_CST LIDL_NP1 has_VHZ a_AT1 low-cost_JJ brand_NN1 image_NN1 and_CC he_PPHS1 also_RR expected_VVN that_CST Stockmann_NP1 would_VM carry_VVI the_AT products_NN2 he_PPHS1 is_VBZ looking_VVG for_IF because_CS it_PPH1 has_VHZ a_AT1 good_JJ image_NN1 ._. 
</s>
<s>
In_II this_DD1 case_NN1 the_AT marketing_NN1 theory_NN1 shows_VVZ that_CST Daniel_NP1 was_VBDZ pleasantly_RR surprised_JJ with_IW Stockmann_NP1 ,_, but_CCB disappointed_JJ with_IW Stockmann_NP1 because_II21 of_II22 high_JJ expectations_NN2 ._. 
</s>
<s>
However_RR ,_, he_PPHS1 does_VDZ nt_XX bring_VVI up_RP this_DD1 as_II a_AT1 major_JJ factor_NN1 when_CS asked_VVN in_II the_AT interview_NN1 ._. 
</s>
<s>
For_IF the_AT case_NN1 of_IO grocery_NN1 shopping_NN1 ,_, the_AT interaction_NN1 with_IW service_NN1 personnel_NN2 was_VBDZ minimal_JJ and_CC therefore_RR it_PPH1 did_VDD not_XX play_VVI any_DD role_NN1 for_IF the_AT subject_NN1 of_IO this_DD1 study_NN1 ._. 
</s>
<s>
I_PPIS1 acknowledge_VV0 that_CST in_II this_DD1 case_NN1 the_AT behavior_NN1 might_VM be_VBI very_RG different_JJ for_IF another_DD1 individual_NN1 ._. 
</s>
<s>
For_IF the_AT subject_NN1 of_IO my_APPGE study_NN1 ,_, Daniel_NP1 ,_, it_PPH1 was_VBDZ established_VVN in_II several_DA2 data_NN sources_NN2 that_CST the_AT shopping_NN1 experience_NN1 in_II LIDL_NP1 was_VBDZ much_RR more_RGR pleasant_JJ ._. 
</s>
<s>
In_II LIDL_NP1 the_AT shopping_NN1 was_VBDZ also_RR experienced_VVN as_RG much_DA1 more_DAR successful_JJ because_CS all_DB items_NN2 were_VBDR found_VVN and_CC also_RR something_PN1 that_CST was_VBDZ not_XX planned_VVN ,_, this_DD1 was_VBDZ a_AT1 major_JJ factor_NN1 for_IF Daniel_NP1 ._. 
</s>
<s>
Daniel_NP1 also_RR experienced_VVD the_AT stress_NN1 and_CC crowds_NN2 in_II Stockmann_NP1 very_RG negatively_RR ._. 
</s>
<s>
Dividing_VVG the_AT factors_NN2 that_CST influence_VV0 grocery_NN1 store_NN1 choice_NN1 in_II two_MC categories_NN2 clearly_RR shows_VVZ that_CST for_IF Daniel_NP1 the_AT most_RGT important_JJ are_VBR the_AT consumer_NN1 oriented_VVN factors_NN2 ;_; that_REX21 is_REX22 ,_, the_AT things_NN2 that_CST he_PPHS1 experiences_VVZ in_II practice_NN1 when_CS shopping_VVG ._. 
</s>
<s>
Although_CS I_PPIS1 call_VV0 them_PPHO2 consumer_NN1 oriented_VVD ,_, it_PPH1 does_VDZ not_XX mean_VVI that_CST the_AT retailer_NN1 can_VM not_XX affect_VVI them_PPHO2 ._. 
</s>
<s>
For_REX21 example_REX22 ,_, when_CS comparing_VVG Stockmann_NP1 and_CC LIDL_NP1 ,_, I_PPIS1 found_VVD that_CST the_AT design_NN1 of_IO the_AT store_NN1 and_CC shelves_NN2 can_VM have_VHI an_AT1 effect_NN1 on_II how_RRQ consumers_NN2 move_VV0 ,_, and_CC therefore_RR ,_, also_RR how_RRQ they_PPHS2 experience_VV0 crowds_NN2 and_CC the_AT following_JJ stress_NN1 factor_NN1 ._. 
</s>
<s>
It_PPH1 might_VM be_VBI that_CST it_PPH1 is_VBZ not_XX the_AT intention_NN1 of_IO Stockmann_NP1 to_TO be_VBI a_AT1 store_NN1 that_CST is_VBZ optimally_RR designed_VVN for_IF everyday_JJ grocery_NN1 shopping_NN1 ._. 
</s>
<s>
In_II the_AT interview_NN1 Daniel_NP1 states_VVZ that_CST he_PPHS1 would_VM do_VDI his_APPGE everyday_JJ shopping_NN1 in_II LIDL_NP1 ,_, but_CCB chooses_VVZ to_TO buy_VVI better_JJR fresh_JJ quality_NN1 products_NN2 at_II Stockmann_NP1 when_CS cooking_VVG for_IF a_AT1 dinner_NN1 party_NN1 ._. 
</s>
<s>
Although_CS this_DD1 study_NN1 does_VDZ not_XX consider_VVI the_AT specific_JJ marketing_NN1 ,_, operational_JJ and_CC brand_NN1 strategies_NN2 of_IO the_AT cases_NN2 Stockmann_VV0 and_CC LIDL_NP1 ,_, I_PPIS1 believe_VV0 the_AT results_NN2 are_VBR interesting_JJ for_IF showing_VVG how_RRQ a_AT1 consumer_NN1 behaves_VVZ and_CC rationalizes_VVZ when_CS choosing_VVG retail_JJ store_NN1 for_IF grocery_NN1 shopping_NN1 ._. 
</s>
<s>
6_MC ._. 
</s>
<s>
Conclusions_NN2 
</s>
