<s>
Goals_NN2 1_MC1 ._. 
</s>
<s>
Introduction_NN1 1.1_MC Research_NN1 topic_NN1 Having_VHG started_VVN in_II humble_JJ beginnings_NN2 ,_, project_NN1 management_NN1 has_VHZ become_VVN a_AT1 management_NN1 discipline_NN1 ,_, which_DDQ in_II today_RT 's_GE professional_JJ world_NN1 is_VBZ in_II many_DA2 ways_NN2 of_IO central_JJ significance_NN1 ._. 
</s>
<s>
According_II21 to_II22 a_AT1 statistic_NN1 published_VVN by_II the_AT Project_NN1 Management_NN1 Institute_NN1 in_II 2001_MC ,_, roughly_RR one_MC1 fourth_MD of_IO the_AT world_NN1 GNP_NN1 is_VBZ produced_VVN in_II project-like_JJ ventures_NN2 (_( Schwalbe_NP1 2006:2_MC )_) ._. 
</s>
<s>
According_II21 to_II22 another_DD1 statistic_NN1 projects_NN2 in_II SME_NP1 's_GE alone_JJ make_VV0 up_RP approximately_RR one_MC1 fifth_MD of_IO the_AT European_JJ Union_NN1 's_GE GDP_NN1 (_( Turner_NP1 ,_, Ledwith_NP1 &;_NULL Kelly_NP1 2009:744_MC )_) ._. 
</s>
<s>
Owing_II21 to_II22 its_APPGE origin_NN1 as_II a_AT1 practitioner-driven_JJ management_NN1 discipline_NN1 (_( Citation_NN1 :_: multiple_JJ )_) ,_, the_AT foundations_NN2 of_IO project_NN1 management_NN1 are_VBR not_XX built_VVN of_IO theories_NN2 ,_, but_CCB are_VBR in_II stead_NN1 largely_RR based_VVN on_II the_AT codification_NN1 of_IO experienced_JJ best_JJT practices_NN2 (_( Citation_NN1 :_: Lenfle_NP1 &;_NULL Koch_NP1 )_) ._. 
</s>
<s>
Nevertheless_RR ,_, during_II the_AT last_MD three_MC decades_NNT2 ,_, project_NN1 management_NN1 has_VHZ received_VVN a_AT1 lot_NN1 of_IO attention_NN1 from_II academia_NN1 as_II31 well_II32 as_II33 from_II management_NN1 gurus_NN1 ._. 
</s>
<s>
This_DD1 development_NN1 has_VHZ to_TO be_VBI seen_VVN as_RG positive_JJ as_CSA well_RR as_CSA deserved_VVN ._. 
</s>
<s>
Simultaneously_RR ,_, the_AT practical_JJ discipline_NN1 has_VHZ seen_VVN some_DD consolidation_NN1 in_II the_AT sense_NN1 that_CST many_DA2 major_JJ practical_JJ actors_NN2 have_VH0 gone_VVN on_RP to_TO create_VVI frameworks_NN2 ,_, which_DDQ can_VM be_VBI described_VVN as_II standards_NN2 ,_, to_TO homogenize_VVI the_AT practicing_NN1 of_IO project_NN1 management_NN1 ._. 
</s>
<s>
However_RR ,_, the_AT academic_JJ research_NN1 into_II project_NN1 management_NN1 seems_VVZ to_TO largely_RR disregard_VVI investigating_VVG the_AT one_MC1 element_NN1 in_II projects_NN2 ,_, which_DDQ is_VBZ no_AT less_DAR than_CSN the_AT very_JJ reason_NN1 for_IF the_AT projects_NN2 '_GE existence_NN1 :_: the_AT setting_NN1 of_IO project_NN1 goals_NN2 ._. 
</s>
<s>
A_AT1 project_NN1 's_GE goal_NN1 is_VBZ of_IO an_AT1 immense_JJ significance_NN1 to_II any_DD project_NN1 -_- not_XX only_RR does_VDZ the_AT goal_NN1 rationalize_VVI the_AT very_JJ existence_NN1 of_IO the_AT project_NN1 there_EX are_VBR numerous_JJ studies_NN2 ,_, which_DDQ largely_RR attribute_VV0 a_AT1 project_NN1 's_GE success_NN1 or_CC failure_NN1 to_II the_AT project_NN1 goals_NN2 ._. 
</s>
<s>
To_TO name_VVI a_AT1 few_DA2 ,_, Nelson_NP1 ,_, in_II his_APPGE study_NN1 of_IO 10_MC infamous_JJ project_NN1 failures_NN2 in_II IT-projects_NN2 names_VVZ "_" bad_JJ goals_NN2 "_" and_CC related_JJ reasons_NN2 as_II the_AT culprit_NN1 to_TO project_VVI failure_NN1 in_II the_AT majority_NN1 of_IO cases_NN2 (_( Nelson_NP1 2007:67-76_MCMC )_) ._. 
</s>
<s>
Similarly_RR there_EX are_VBR claims_NN2 that_CST project_NN1 goals_NN2 constitute_VV0 the_AT foundation_NN1 of_IO any_DD project_NN1 ,_, and_CC that_CST it_PPH1 is_VBZ of_IO immense_JJ importance_NN1 that_CST these_DD2 goals_NN2 are_VBR set_VVN well_RR (_( Williams_NP1 &;_NULL Samset_NP1 2010:39-43_MCMC ;_; Frame_NN1 1995:21-22_MCMC )_) ._. 
</s>
<s>
Paradoxically_RR ,_, most_RGT comprehensive_JJ works_NN on_II project_NN1 management_NN1 disregard_VV0 the_AT process_NN1 of_IO project_NN1 goal_NN1 setting_VVG almost_RR entirely_RR ._. 
</s>
<s>
Thus_RR the_AT question_NN1 remains_VVZ :_: how_RRQ are_VBR project_NN1 goals_NN2 set_VV0 ?_? 
</s>
<s>
The_AT purpose_NN1 of_IO this_DD1 paper_NN1 is_VBZ thus_RR to_TO attempt_VVI to_TO offer_VVI project_NN1 management_NN1 researchers_NN2 and_CC practitioners_NN2 alike_RR a_AT1 usable_JJ framework_NN1 for_IF evaluating_VVG and_CC understanding_NN1 project_NN1 management_NN1 goal_NN1 setting_NN1 ._. 
</s>
<s>
We_PPIS2 will_VM thus_RR begin_VVI with_IW exploring_VVG in_II detail_NN1 ,_, what_DDQ the_AT discipline_NN1 of_IO project_NN1 management_NN1 and_CC has_VHZ to_TO offer_VVI us_PPIO2 on_II the_AT process_NN1 of_IO project_NN1 goal_NN1 setting_NN1 ._. 
</s>
<s>
This_DD1 description_NN1 offered_VVN by_II the_AT project_NN1 management_NN1 discipline_NN1 will_VM thereafter_RT be_VBI contrasted_VVN with_IW some_DD well-established_JJ relevant_JJ theories_NN2 from_II within_II the_AT generic_JJ management_NN1 literature_NN1 (_( especially_RR regarding_II decision_NN1 making_VVG and_CC behavior_NN1 in_II organizations_NN2 )_) ._. 
</s>
<s>
Thereafter_RT the_AT author_NN1 aims_VVZ at_II creating_VVG a_AT1 synthesis._NNU 1.2_MC Methodology_NN1 and_CC limitations_NN2 This_DD1 paper_NN1 views_NN2 project_VV0 goals_NN2 as_II a_AT1 result_NN1 of_IO human_JJ decision_NN1 making_VVG not_XX as_CSA something_PN1 which_DDQ fell_VVD from_II the_AT sky_NN1 ._. 
</s>
<s>
Thus_RR it_PPH1 also_RR implies_VVZ ,_, that_CST there_EX is_VBZ a_AT1 considerable_JJ freedom_NN1 in_II selecting_VVG ,_, which_DDQ goals_NN2 a_AT1 project_NN1 shall_VM meet_VVI ._. 
</s>
<s>
As_CSA such_DA we_PPIS2 turn_VV0 to_II Simon_NP1 ,_, who_PNQS in_II his_PPGE widely_RR cited_VVN text_NN1 states_NN2 ,_, that_CST a_AT1 decision_NN1 process_NN1 in_II its_APPGE simplest_JJT form_NN1 contains_VVZ three_MC steps_NN2 ,_, which_DDQ usually_RR happen_VV0 in_II the_AT order_NN1 of_IO :_: 1_MC1 )_) searching_VVG for_IF situations_NN2 necessitating_VVG decision-making_NN1 ;_; 2_MC )_) identifying_VVG or_CC creating_VVG alternative_JJ solutions_NN2 and_CC 3_MC )_) choice_NN1 of_IO the_AT best_JJT alternative_JJ solution_NN1 ._. 
</s>
<s>
Simon_NP1 further_RRR notes_VVZ that_CST ,_, although_CS decision-making_JJ usually_RR encompasses_VVZ these_DD2 three_MC steps_NN2 ,_, every_AT1 single_JJ step_NN1 can_VM also_RR contain_VVI an_AT1 entire_JJ decision-making_JJ process_NN1 of_IO its_APPGE own_DA (_( the_AT formulation_NN1 of_IO an_AT1 alternative_JJ solution_NN1 can_VM be_VBI seen_VVN as_II a_AT1 decision-making_JJ process_NN1 )_) ,_, and_CC that_CST later_JJR steps_NN2 can_VM create_VVI the_AT necessity_NN1 to_TO "_" take_VVI a_AT1 step_NN1 back_RP "_" and_CC search_NN1 for_IF new_JJ information_NN1 ._. 
</s>
<s>
(_( Simon_NP1 1977:4044_MC )_) Using_VVG Simon_NP1 's_GE model_NN1 as_CSA starting_NN1 point_NN1 ,_, we_PPIS2 divide_VV0 the_AT goal-setting_JJ process_NN1 in_II projects_NN2 into_II two_MC stages_NN2 :_: collation_NN1 of_IO alternative_JJ goals_NN2 and_CC choice_NN1 of_IO which_DDQ goals_NN2 to_TO pursue_VVI ._. 
</s>
<s>
Thus_RR we_PPIS2 need_VV0 to_TO study_VVI the_AT goal_NN1 setting_NN1 process_NN1 in_II projects_NN2 from_II two_MC different_JJ dimensions_NN2 :_: The_AT first_MD dimension_NN1 is_VBZ the_AT contextual_JJ dimension_NN1 ,_, which_DDQ largely_RR corresponds_VVZ to_II steps_NN2 one_MC1 and_CC two_MC of_IO Simon_NP1 's_GE model_NN1 (_( intelligence_NN1 and_CC design_NN1 )_) ._. 
</s>
<s>
The_AT contextual_JJ dimension_NN1 encompasses_VVZ the_AT subjective_JJ need_NN1 for_IF a_AT1 project_NN1 (_( objectives_NN2 for_IF the_AT project_NN1 )_) and_CC the_AT different_JJ parties_NN2 '_GE expectations_NN2 for_IF the_AT project_NN1 ._. 
</s>
<s>
The_AT second_MD dimension_NN1 is_VBZ the_AT decision-making_JJ dimension_NN1 ,_, which_DDQ corresponds_VVZ to_II Simon_NP1 's_GE third_MD step_NN1 (_( choice_NN1 )_) ._. 
</s>
<s>
Thus_RR the_AT decision-making_JJ dimension_NN1 concerns_VVZ itself_PPX1 with_IW the_AT selection_NN1 of_IO the_AT project_NN1 goals_NN2 among_II those_DD2 alternative_JJ solutions_NN2 mapped_VVN out_RP in_II the_AT contextual_JJ dimension_NN1 ._. 
</s>
<s>
Both_DB2 these_DD2 dimensions_NN2 will_VM be_VBI summarized_VVN based_VVN on_II project_NN1 management_NN1 literature_NN1 (_( although_CS project_NN1 management_NN1 literature_NN1 says_VVZ very_RG little_DA1 about_II the_AT decision-_NN1 making_VVG dimension_NN1 )_) ._. 
</s>
<s>
Further_RRR ,_, theories_NN2 about_II decision-making_NN1 in_RR21 general_RR22 will_VM be_VBI summarized_VVN based_VVN on_II literature_NN1 on_II decision-making_NN1 and_CC organizational_JJ behavior_NN1 in_RR21 general_RR22 ._. 
</s>
<s>
Thus_RR the_AT paper_NN1 's_GE main_JJ content_NN1 could_VM be_VBI described_VVN as_II an_AT1 attempt_NN1 at_II interdisciplinary_JJ synthesis_NN1 between_II the_AT fields_NN2 and_CC literatures_NN2 of_IO project_NN1 management_NN1 and_CC those_DD2 of_IO organizational_JJ behavior_NN1 ._. 
</s>
<s>
Due_II21 to_II22 the_AT interdisciplinary_JJ nature_NN1 of_IO the_AT paper_NN1 some_DD strategic_JJ decisions_NN2 have_VH0 to_TO be_VBI made_VVN ._. 
</s>
<s>
Firstly_RR ,_, the_AT paper_NN1 aims_VVZ to_TO cover_VVI the_AT topic_NN1 on_II a_AT1 level_NN1 ,_, which_DDQ is_VBZ as_RG abstract_JJ and_CC non-_JJ specific_JJ as_CSA possible_JJ ._. 
</s>
<s>
Secondly_RR ,_, to_TO be_VBI able_JK to_TO cover_VVI 'the_NN1 state_NN1 of_IO project_NN1 management_NN1 thought'_NN1 ,_, the_AT project_NN1 management_NN1 literature_NN1 will_VM be_VBI used_VVN as_RG widely_RR as_CSA possible_JJ ._. 
</s>
<s>
Thus_RR this_DD1 paper_NN1 will_VM not_XX limit_VVI itself_PPX1 to_II scientific_JJ papers_NN2 ,_, but_CCB will_VM also_RR use_VVI practitioners_NN2 '_GE guides_NN2 as_CSA reference_NN1 ._. 
</s>
<s>
Owing_II21 to_II22 a_AT1 it_PPH1 's_VBZ significance_NN1 as_CSA basis_NN1 of_IO project_NN1 management_NN1 certification_NN1 "_" The_AT Project_NN1 Management_NN1 Body_NN1 of_IO Knowledge_NN1 (_( PMBOK_NP1 )_) Guide_NN1 "_" is_VBZ the_AT discipline_NN1 's_GE de-facto_JJ standard_NN1 and_CC can_VM thus_RR not_XX be_VBI disregarded._NNU 1.3_MC Definitions_NN2 As_II the_AT project_NN1 management_NN1 discipline_NN1 is_VBZ not_XX fully_RR consistent_JJ in_II its_APPGE use_NN1 of_IO terminology_NN1 and_CC as_CSA this_DD1 paper_NN1 takes_VVZ an_AT1 interdisciplinary_JJ approach_NN1 ,_, some_DD terms_NN2 used_VVN will_VM be_VBI defined_VVN and_CC explained_VVN ._. 
</s>
<s>
Further_RRR ,_, as_CSA this_DD1 paper_NN1 aims_VVZ to_TO be_VBI as_RG non-specific_JJ as_CSA possible_JJ ,_, the_AT author_NN1 intends_VVZ to_TO make_VVI no_AT difference_NN1 between_II different_JJ types_NN2 of_IO organizations_NN2 ._. 
</s>
<s>
All_DB organizations_NN2 ,_, whether_CSW private_JJ companies_NN2 ,_, public_JJ institutions_NN2 or_CC of_IO some_DD other_JJ type_NN1 ,_, will_VM be_VBI referred_VVN to_II as_CSA organizations_NN2 existing_VVG in_II an_AT1 environment_NN1 ._. 
</s>
<s>
Likewise_RR ,_, this_DD1 paper_NN1 does_VDZ not_XX differentiate_VVI between_II internal_JJ projects_NN2 (_( in_II which_DDQ the_AT project_NN1 owner_NN1 and_CC the_AT project_NN1 team_NN1 belong_VV0 to_II the_AT same_DA legal_JJ unit_NN1 )_) ,_, external_JJ projects_NN2 (_( in_II which_DDQ the_AT owner_NN1 belongs_VVZ to_II one_MC1 unit_NN1 and_CC the_AT team_NN1 to_II another_DD1 )_) or_CC network_NN1 projects_NN2 (_( in_II which_DDQ the_AT owner(s)_NN2 and_CC team(s)_NN2 may_VM belong_VVI to_II several_DA2 units_NN2 )_) ._. 
</s>
<s>
There_EX is_VBZ no_AT consensus_NN1 on_II the_AT exact_JJ definition_NN1 of_IO a_AT1 project_NN1 ._. 
</s>
<s>
Within_II this_DD1 paper_NN1 ,_, a_AT1 project_NN1 is_VBZ defined_VVN as_CSA "_" A_ZZ1 unique_JJ venture_NN1 having_VHG specific_JJ goals_NN2 ,_, which_DDQ by_II nature_NN1 is_VBZ temporary_JJ and_CC utilizes_VVZ different_JJ types_NN2 of_IO resources_NN2 with_IW the_AT aim_NN1 to_TO produce_VVI a_AT1 result_NN1 ._. 
</s>
<s>
A_AT1 project_NN1 creates_VVZ an_AT1 own_DA organization_NN1 within_II its_APPGE parent_NN1 organization(s)_NN2 ._. "_" 
</s>
<s>
The_AT term_NN1 project_NN1 management_NN1 is_VBZ seen_VVN as_CSA encompassing_VVG both_DB2 elements_NN2 project_VV0 leadership_NN1 and_CC project_NN1 administration_NN1 ._. 
</s>
<s>
The_AT project_NN1 organization_NN1 is_VBZ used_VVN to_TO describe_VVI the_AT form_NN1 of_IO organization_NN1 within_II projects_NN2 and_CC in_II contrast_NN1 to_II the_AT process_NN1 organization_NN1 ._. 
</s>
<s>
The_AT project_NN1 organization_NN1 shall_VM not_XX be_VBI mixed_VVN up_RP with_IW the_AT term_NN1 projectile_NN1 organization_NN1 ,_, which_DDQ in_II turn_NN1 refers_VVZ to_II a_AT1 parent_NN1 organization_NN1 organized_VVD around_RP projects_NN2 ._. 
</s>
<s>
In_II contrast_NN1 with_IW the_AT project_NN1 ,_, the_AT venture_NN1 striving_VVG for_IF unique_JJ results_NN2 ,_, and_CC the_AT project_NN1 organization_NN1 ,_, the_AT sub_JJ organization_NN1 created_VVN to_TO suit_VVI the_AT project_NN1 ,_, the_AT organization_NN1 's_GE process_NN1 is_VBZ defined_VVN as_II the_AT organization_NN1 's_GE repeating_JJ tasks_NN2 and_CC the_AT process_NN1 organization_NN1 (_( without_IW regard_NN1 to_II what_DDQ specialization_NN1 criteria_NN2 is_VBZ used_VVN as_CSA orientation_NN1 )_) as_II the_AT organization_NN1 created_VVN to_TO support_VVI those_DD2 ._. 
</s>
<s>
The_AT project_NN1 owner_NN1 is_VBZ that_DD1 part_NN1 of_IO the_AT process_NN1 organization_NN1 ,_, which_DDQ functions_VVZ as_CSA client_NN1 to_II the_AT project_NN1 ._. 
</s>
<s>
The_AT project_NN1 owner_NN1 is_VBZ interpreted_VVN as_II a_AT1 group_NN1 of_IO individuals_NN2 and_CC thus_RR as_II an_AT1 organization_NN1 ._. 
</s>
<s>
Project_NN1 goals_NN2 and_CC goals_NN2 for_IF projects_NN2 will_VM be_VBI categorized_VVN as_CSA follows_VVZ ._. 
</s>
<s>
There_EX is_VBZ a_AT1 clear_JJ differentiation_NN1 between_II a_AT1 project_NN1 's_GE goals_NN2 the_AT metrics_NN1 the_AT project_NN1 shall_VM fulfill_VVI and_CC a_AT1 project_NN1 's_GE objectives_NN2 what_DDQ is_VBZ expected_VVN of_IO the_AT project_NN1 ._. 
</s>
<s>
Further_RRR it_PPH1 shall_VM be_VBI noted_VVN that_CST individuals_NN2 and_CC groups_NN2 can_VM have_VHI their_APPGE own_DA expectations_NN2 for_IF a_AT1 project_NN1 ._. 
</s>
<s>
Within_II the_AT realm_NN1 of_IO this_DD1 paper_NN1 ,_, the_AT term_NN1 party_NN1 or_CC parties_NN2 are_VBR used_VVN to_TO denote_VVI groups_NN2 of_IO individuals_NN2 who_PNQS have_VH0 a_AT1 specific_JJ interest_NN1 regarding_II an_AT1 issue_NN1 ._. 
</s>
<s>
Depending_II21 on_II22 the_AT situation_NN1 ,_, a_AT1 party_NN1 can_VM either_RR be_VBI the_AT entire_JJ organization_NN1 ,_, a_AT1 subunit_NN1 of_IO an_AT1 organization_NN1 (_( e.g._REX the_AT accounting_NN1 department_NN1 )_) or_CC a_AT1 group_NN1 of_IO people_NN holding_VVG a_AT1 common_JJ view_NN1 on_II the_AT issue_NN1 ._. 
</s>
<s>
In_II some_DD situations_NN2 an_AT1 organization_NN1 may_VM also_RR be_VBI a_AT1 party_NN1 ._. 
</s>
<s>
Within_II this_DD1 paper_NN1 ,_, the_AT use_NN1 of_IO party_NN1 is_VBZ used_VVN to_TO emphasize_VVI the_AT perceived_JJ significance_NN1 of_IO the_AT relevant_JJ party_NN1 's_GE specific_JJ interests_NN2 ._. 
</s>
<s>
A_AT1 single-person_JJ party_NN1 is_VBZ defined_VVN as_II a_AT1 player_NN1 ._. 
</s>
<s>
As_II the_AT term_NN1 'professional'_NN1 could_VM be_VBI seen_VVN as_CSA referring_VVG to_II persons_NN2 having_VHG project_NN1 management_NN1 certificates_NN2 ,_, the_AT paper_NN1 will_VM coin_VVI people_NN who_PNQS work_VV0 as_CSA project_NN1 manager_NN1 's_GE practitioners._NNU 1.4_MC Description_NN1 of_IO contents_NN2 This_DD1 chapter_NN1 will_VM describe_VVI the_AT structure_NN1 of_IO the_AT paper._NNU 2_MC ._. 
</s>
<s>
Project_NN1 goal_NN1 setting_NN1 Introduction_NN1 and_CC description_NN1 of_IO chapter_NN1 2_MC ._. 
</s>
<s>
In_II this_DD1 paper_NN1 's_GE description_NN1 of_IO project_NN1 goal_NN1 setting_NN1 we_PPIS2 will_VM utilize_VVI Simon_NP1 's_GE definition_NN1 of_IO goals_NN2 (_( in_II organizations_NN2 )_) :_: "_" By_II goals_NN2 we_PPIS2 shall_VM mean_VVI value_NN1 premises_NN2 that_CST can_VM serve_VVI as_CSA inputs_NN2 to_II decisions_NN2 ._. "_" 
</s>
<s>
(_( Simon_NP1 1964:3_MC )_) ._. 
</s>
<s>
In_II the_AT context_NN1 of_IO this_DD1 paper_NN1 ,_, the_AT definition_NN1 implies_VVZ that_CST any_DD definition_NN1 or_CC specification_NN1 ,_, which_DDQ is_VBZ intended_VVN to_TO steer_VVI individual_JJ decision_NN1 making_VVG and_CC an_AT1 individual_NN1 's_GE subsequent_JJ action_NN1 towards_II a_AT1 wished-for_JJ end-result_NN1 constitutes_VVZ a_AT1 goal._NNU 2.1_MC The_AT importance_NN1 of_IO the_AT contextual_JJ dimension_NN1 The_AT importance_NN1 of_IO the_AT early_JJ stages_NN2 in_II projects_NN2 has_VHZ been_VBN well_RR known_VVN for_IF some_DD time_NNT1 (_( Miller_NP1 &;_NULL Hobbs_NP1 2005:43_MC )_) ._. 
</s>
<s>
Nevertheless_RR ,_, the_AT discipline_NN1 's_GE advance_NN1 in_II these_DD2 early_JJ stages_NN2 has_VHZ been_VBN significantly_RR slower_RRR than_CSN it_PPH1 has_VHZ been_VBN concerning_VVG the_AT implementation_NN1 phase_NN1 (_( Williams_NP1 &;_NULL Samset_NP1 2010:39_MC )_) ._. 
</s>
<s>
In_II the_AT following_JJ paragraphs_NN2 this_DD1 paper_NN1 aims_VVZ to_TO present_VVI the_AT project_NN1 management_NN1 literature_NN1 's_GE view_NN1 on_II project_NN1 goals_NN2 and_CC their_APPGE origins_NN2 ._. 
</s>
<s>
To_TO be_VBI able_JK to_TO describe_VVI this_DD1 complex_JJ topic_NN1 ,_, this_DD1 paper_NN1 divides_VVZ the_AT topic_NN1 into_II four_MC subtopics_NN2 ._. 
</s>
<s>
Firstly_RR we_PPIS2 will_VM explore_VVI basic_JJ questions_NN2 such_II21 as_II22 the_AT amount_NN1 of_IO goals_NN2 as_II31 well_II32 as_II33 inter-goal_JJ relations_NN2 ._. 
</s>
<s>
Secondly_RR we_PPIS2 will_VM delve_VVI into_II the_AT effect_NN1 the_AT properties_NN2 of_IO goals_NN2 have_VH0 for_IF a_AT1 project_NN1 ._. 
</s>
<s>
Thirdly_RR we_PPIS2 will_VM describe_VVI where_RRQ goals_NN2 come_VV0 from_II ,_, and_CC how_RRQ they_PPHS2 come_VV0 into_II existence_NN1 ._. 
</s>
<s>
Finally_RR ,_, as_CSA neither_RR projects_NN2 nor_CC their_APPGE goals_NN2 exist_VV0 in_II isolation_NN1 ,_, we_PPIS2 will_VM study_VVI the_AT project_NN1 selection_NN1 process_NN1 in_II31 view_II32 of_II33 how_RRQ it_PPH1 might_VM affect_VVI project_NN1 goals._NNU 2.1.1_MC One_MC1 goal_NN1 ?_? 
</s>
<s>
Several_DA2 goals_NN2 ?_? 
</s>
<s>
That_DD1 projects_NN2 are_VBR oriented_VVN towards_II goals_NN2 is_VBZ beyond_II doubt_NN1 (_( Frame_NN1 1995:2_MC ;_; Choudhury_NP1 1988:3_MC ;_; Harrison_NP1 1981:1_MC )_) ._. 
</s>
<s>
Therefore_RR we_PPIS2 would_VM like_VVI to_TO be_VBI able_JK to_TO assume_VVI ,_, that_CST the_AT literature_NN1 would_VM be_VBI in_II agreement_NN1 over_II such_DA elementary_JJ questions_NN2 as_CSA how_RGQ many_DA2 goals_NN2 projects_NN2 have_VH0 or_CC how_RRQ these_DD2 goals_NN2 relate_VV0 to_II each_PPX221 other_PPX222 ._. 
</s>
<s>
Sadly_RR this_DD1 assumption_NN1 would_VM be_VBI quite_RG erroneous_JJ ._. 
</s>
<s>
The_AT simplest_JJT way_NN1 to_TO describe_VVI a_AT1 projects_NN2 goals_NN2 is_VBZ to_TO define_VVI the_AT project_NN1 as_II a_AT1 venture_NN1 aimed_VVN to_II fulfilling_VVG specific_JJ qualitative_JJ goals_NN2 ,_, in_II a_AT1 way_NN1 that_CST the_AT projects_NN2 costs_NN2 do_VD0 not_XX exceed_VVI a_AT1 given_JJ limit_NN1 while_CS also_RR finishing_VVG the_AT project_NN1 before_II a_AT1 given_JJ deadline_NN1 ._. 
</s>
<s>
This_DD1 simple_JJ model_NN1 is_VBZ called_VVN the_AT triple_JJ constraint_NN1 (_( Berggren_NP1 2001:1617_MC )_) and_CC can_VM in_II this_DD1 paper_NN1 be_VBI described_VVN as_II a_AT1 relation_NN1 between_II use_NN1 of_IO time_NNT1 ,_, the_AT use_NN1 of_IO money_NN1 and_CC the_AT fulfillment_NN1 of_IO the_AT qualitative_JJ goals_NN2 ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) The_AT triple_JJ constraint_NN1 ,_, similarly_RR as_II a_AT1 significant_JJ part_NN1 of_IO the_AT literature_NN1 ,_, builds_VVZ on_II the_AT hypothesis_NN1 that_CST projects_NN2 are_VBR started_VVN to_TO fulfill_VVI specific_JJ qualitative_JJ goals_NN2 ,_, and_CC that_CST the_AT quantitative_JJ goals_NN2 cost_VV0 and_CC time_NNT1 use_NN1 are_VBR calculated_VVN based_VVN on_II what_DDQ reaching_VVG the_AT qualitative_JJ goals_NN2 can_VM be_VBI assumed_VVN to_TO necessitate_VVI ._. 
</s>
<s>
This_DD1 model_NN1 practically_RR implies_VVZ ,_, that_CST the_AT qualitative_JJ goals_NN2 are_VBR decisive_JJ ,_, and_CC that_CST the_AT kvantitative_JJ goals_NN2 are_VBR derived_VVN from_II the_AT qualitative_JJ goals_NN2 ._. 
</s>
<s>
Therefore_RR ,_, the_AT literature_NN1 often_RR describes_VVZ the_AT qualitative_JJ goals_NN2 as_CSA actual_JJ or_CC proper_JJ goals_NN2 ,_, and_CC calls_VVZ the_AT kvantitative_JJ goals_NN2 "_" limitations_NN2 "_" ._. 
</s>
<s>
Although_CS this_DD1 view_NN1 has_VHZ it_PPH1 's_VBZ critics_NN2 it_PPH1 nevertheless_RR represents_VVZ the_AT mainstream_NN1 of_IO the_AT literature_NN1 and_CC vill_VV0 thus_RR be_VBI used_VVN as_CSA basis_NN1 in_II this_DD1 paper_NN1 ._. 
</s>
<s>
Therefore_RR the_AT focus_NN1 of_IO this_DD1 paper_NN1 will_VM also_RR be_VBI on_II studying_VVG the_AT goal_NN1 setting_NN1 process_NN1 of_IO the_AT qualitative_JJ goals_NN2 (_( henceforth_RT "_" goals_NN2 "_" will_VM point_VVI to_II qualitative_JJ goals_NN2 and_CC "_" limitations_NN2 "_" to_II quantitative_JJ goals_NN2 )_) and_CC will_VM disregard_VVI the_AT limitations_NN2 ._. 
</s>
<s>
Some_DD authors_NN2 state_VV0 that_CST a_AT1 project_NN1 may_VM only_RR have_VHI one_MC1 goal_NN1 (_( Wysocki_NP1 &;_NULL McGary_NP1 2003:5_MC )_) ,_, whereas_CS others_NN2 state_VV0 that_CST projects_NN2 can_VM have_VHI several_DA2 goals_NN2 ,_, but_CCB must_VM have_VHI at_RR21 least_RR22 one_MC1 goal_NN1 (_( Futrell_NP1 ,_, Shafer_NP1 &;_NULL Shafer_NP1 2002:226_MC )_) ,_, or_CC further_RRR ,_, that_DD1 projects_VVZ usually_RR have_VH0 several_DA2 (_( two_MC to_II five_MC )_) main_JJ goals_NN2 and_CC a_AT1 multitude_NN1 of_IO detail-level_JJ goals_NN2 (_( Andersen_NP1 et_RA21 al._RA22 2004:42_MC )_) ._. 
</s>
<s>
As_II the_AT view_NN1 that_CST project_NN1 may_VM have_VHI more_DAR than_CSN one_MC1 goal_NN1 is_VBZ espoused_VVN by_II most_DAT writers_NN2 ,_, this_DD1 paper_NN1 will_VM continue_VVI based_VVN on_II that_DD1 assumption_NN1 ._. 
</s>
<s>
That_DD1 projects_VVZ may_VM have_VHI several_DA2 goals_NN2 brings_VVZ up_RP an_AT1 important_JJ question_NN1 :_: how_RRQ do_VD0 the_AT different_JJ goals_NN2 relate_VV0 to_II each_PPX221 other_PPX222 ?_? 
</s>
<s>
To_TO exemplify_VVI the_AT problem_NN1 we_PPIS2 can_VM utilize_VVI the_AT example_NN1 given_VVN by_II Futrell_NP1 et_RA21 al._RA22 :_: that_CST the_AT organization_NN1 aims_VVZ to_II (_( besides_RR reaching_VVG the_AT project_NN1 's_GE functional_JJ goals_NN2 )_) use_VV0 the_AT project_NN1 as_II a_AT1 vehicle_NN1 for_IF developing_VVG its_APPGE personnel_NN2 and_CC as_II a_AT1 reference_NN1 (_( Futrell_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2002:227_MC )_) ._. 
</s>
<s>
This_DD1 example_NN1 is_VBZ suitable_JJ in_CS21 that_CS22 it_PPH1 point_VV0 out_RP that_DD1 attainment_NN1 of_IO one_MC1 goal_NN1 can_VM be_VBI dependent_JJ upon_II the_AT attainment_NN1 of_IO another_DD1 goal_NN1 (_( if_CS the_AT functional_JJ goals_NN2 are_VBR not_XX attained_VVN ,_, the_AT project_NN1 wo_VM n't_XX be_VBI usable_JJ as_CSA reference_NN1 )_) and_CC that_CST they_PPHS2 likewise_RR be_VBI independent_JJ of_IO each_PPX221 other_PPX222 (_( the_AT personnel_NN2 can_VM be_VBI developed_VVN even_RR although_CS the_AT project_NN1 would_VM not_XX reach_VVI its_APPGE functional_JJ goals_NN2 )_) ._. 
</s>
<s>
Andersen_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
state_VV0 that_DD1 project_NN1 goals_NN2 should_VM be_VBI structured_VVN in_II complete_JJ hierarchies_NN2 ,_, meaning_VVG that_DD1 higher-level_NN1 ,_, abstract_JJ goals_NN2 should_VM be_VBI divided_VVN up_RP into_II the_AT more_RGR tangible_JJ goals_NN2 ,_, which_DDQ are_VBR necessary_JJ to_TO attain_VVI to_TO be_VBI able_JK to_TO fulfill_VVI the_AT higher-level_JJ goals_NN2 (_( Andersen_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2004:3848_MC )_) ._. 
</s>
<s>
The_AT hierarchical_JJ goal_NN1 structures_NN2 presented_VVN by_II Andersen_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
can_VM be_VBI described_VVN as_II :_: The_AT project_NN1 's_GE purpose_NN1 ,_, which_DDQ necessitates_VVZ the_AT fulfillment_NN1 of_IO Project_NN1 's_GE 1st_MD (_( main_JJ )_) goal_NN1 is_VBZ attained_VVN ,_, which_DDQ necessitates_VVZ the_AT fulfillment_NN1 of_IO Goal_NN1 a#_FO Goal_NN1 b#_FO Project_NN1 's_GE 2nd_MD (_( main_JJ )_) goal_NN1 is_VBZ attained_VVN ,_, which_DDQ necessitates_VVZ the_AT fulfillment_NN1 of_IO Goal_NN1 c#_FO and_RR31 so_RR32 on_RR33 &lsqb;_( Figure_NN1 &rsqb;_) Furthermore_RR ,_, it_PPH1 needs_VVZ to_TO be_VBI stated_VVN ,_, that_CST all_DB projects_NN2 always_RR concern_VV0 more_DAR than_CSN one_MC1 party_NN1 ,_, even_CS21 when_CS22 the_AT project_NN1 is_VBZ internal_JJ the_AT project_NN1 owner_NN1 (_( client_NN1 )_) and_CC the_AT project_NN1 performers_NN2 (_( project_NN1 team_NN1 )_) ._. 
</s>
<s>
The_AT relation_NN1 between_II parties_NN2 can_VM be_VBI seen_VVN as_CSA being_VBG in_II ceaseless_JJ conflict_NN1 :_: The_AT project_NN1 owner_NN1 wants_VVZ to_TO maximize_VVI his_APPGE goal-attainment_NN1 ,_, as_RG quickly_RR and_CC cheaply_RR as_CSA possible_JJ ._. 
</s>
<s>
The_AT project_NN1 team_NN1 's_GE wishes_NN2 would_VM be_VBI practically_RR the_AT opposite_JJ ._. 
</s>
<s>
(_( Turner_NP1 1993:5254_MC )_) As_CSA Simon_NP1 states_VVZ ,_, in_II situations_NN2 like_II these_DD2 one_MC1 party_NN1 's_GE limitation_NN1 may_VM be_VBI the_AT other_JJ party_NN1 's_GE goal_NN1 (_( Simon_NP1 1964:8_MC )_) ._. 
</s>
<s>
The_AT delimitation_NN1 between_II goals_NN2 and_CC limitations_NN2 is_VBZ thus_RR first_MD and_CC foremost_JJT a_AT1 question_NN1 of_IO perspective_NN1 (_( Simon_NP1 1964:20_MC )_) ,_, because_CS the_AT whole_NN1 can_VM also_RR be_VBI seen_VVN as_II a_AT1 set_NN1 of_IO limitations_NN2 ,_, and_CC if_CS no_AT solution_NN1 can_VM be_VBI found_VVN that_CST satisfies_VVZ all_DB limitations_NN2 (_( or_CC conversely_RR ,_, all_DB goals_NN2 )_) then_RT the_AT project_NN1 will_VM not_XX be_VBI begun_VVN (_( Simon_NP1 1964:89_MC )_) ._. 
</s>
<s>
In_II any_DD case_NN1 ,_, we_PPIS2 are_VBR forced_VVN to_TO concede_VVI that_CST the_AT different_JJ parties_NN2 partaking_VVG in_II a_AT1 project_NN1 will_VM have_VHI differing_JJ wishes_NN2 and_CC expectations_NN2 for_IF the_AT projects_NN2 ._. 
</s>
<s>
Further_RRR we_PPIS2 can_VM extrapolate_VVI that_CST as_II the_AT number_NN1 of_IO parties_NN2 partaking_VVG in_II a_AT1 project_NN1 increase_NN1 ,_, the_AT amount_NN1 of_IO expectations_NN2 for_IF the_AT project_NN1 will_VM probably_RR increase_VVI as_RR21 well._RR22 2.1.2_MC The_AT significance_NN1 of_IO project_NN1 goals_NN2 A_ZZ1 project_NN1 's_GE lifecycle_NN1 is_VBZ usually_RR described_VVN through_II partitioning_VVG the_AT project_NN1 in_II different_JJ phases_NN2 or_CC stages_NN2 ,_, based_VVN on_II the_AT idealized_JJ chronological_JJ procession_NN1 ._. 
</s>
<s>
The_AT de-facto_JJ standard_NN1 ,_, the_AT PBMOK-guide_NN1 defines_VVZ these_DD2 phases_NN2 as_CSA 1_MC1 )_) starting_VVG the_AT project_NN1 ,_, 2_MC )_) planning_NN1 and_CC organizing_VVG ,_, 3_MC )_) carrying_VVG out_RP the_AT project_NN1 work_NN1 and_CC 4_MC )_) closing_VVG the_AT project_NN1 (_( PMI_NP1 2008:1522_MC )_) ._. 
</s>
<s>
In_II contrast_NN1 ,_, Schultz_NP1 ,_, Slevin_NP1 and_CC Pinto_NP1 describe_VV0 projects_NN2 as_II a_AT1 whole_NN1 composed_VVN of_IO a_AT1 strategic_JJ phase_NN1 decision_NN1 making_VVG on_II project_NN1 goals_NN2 and_CC planning_VVG on_II how_RRQ these_DD2 shall_VM be_VBI reached_VVN and_CC a_AT1 tactical_JJ phase_NN1 -_- beskriver_NN1 projekt_NN1 som_NNU1 en_FW helhet_VV0 som_NNU1 har_NN1 en_FW strategisk_VV0 del_FW beslutsfattandet_NN1 om_NN1 mlsttningar_NN1 och_UH planeringen_NN1 om_NN1 hur_NN1 de_NP1 ska_NN1 uppns_VVZ och_UH en_FW taktisk_VV0 del_FW implementing_VVG the_AT strategy_NN1 (_( Schultz_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
1987:3435_MC )_) ._. 
</s>
<s>
This_DD1 partitioning_NN1 proposed_VVN by_II the_AT PMBOK-guide_NN1 is_VBZ unsuitable_JJ for_IF a_AT1 study_NN1 of_IO project_NN1 goal_NN1 setting_NN1 ,_, as_CSA it_PPH1 is_VBZ obscure_JJ regarding_II how_RRQ the_AT goal-setting_JJ process_NN1 is_VBZ divided_VVN between_II the_AT first_MD two_MC phases_NN2 ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 ,_, the_AT more_RGR coarse_JJ division_NN1 proposed_VVN by_II Schultz_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
does_VDZ not_XX suffer_VVI this_DD1 handicap_NN1 ,_, and_CC will_VM thus_RR constitute_VVI the_AT basis_NN1 for_IF the_AT next_MD chapters_NN2 ._. 
</s>
<s>
Besides_II the_AT decisions_NN2 made_VVN regarding_II the_AT project_NN1 goals_NN2 necessarily_RR constituting_VVG the_AT basis_NN1 of_IO the_AT entire_JJ project_NN1 ,_, they_PPHS2 are_VBR of_IO critical_JJ importance_NN1 also_RR as_CSA they_PPHS2 are_VBR made_VVN at_II a_AT1 very_RG early_JJ stage_NN1 and_CC thus_RR have_VH0 a_AT1 long_JJ time_NNT1 to_TO influence_VVI the_AT project_NN1 (_( Williams_NP1 &;_NULL Samset_NP1 2010:39_MC )_) ._. 
</s>
<s>
The_AT discussion_NN1 of_IO the_AT properties_NN2 of_IO project_NN1 goals_NN2 can_VM be_VBI divided_VVN into_II two_MC categories_NN2 ._. 
</s>
<s>
On_II one_MC1 hand_NN1 there_EX is_VBZ a_AT1 discussion_NN1 on_II what_DDQ kind_NN1 of_IO goals_NN2 have_VH0 a_AT1 string_NN1 influence_NN1 ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 there_EX is_VBZ a_AT1 discussion_NN1 on_II what_DDQ kind_NN1 of_IO goals_NN2 led_VVN to_II the_AT desired_JJ results_NN2 ._. 
</s>
<s>
The_AT discussion_NN1 could_VM thus_RR be_VBI described_VVN as_II a_AT1 division_NN1 into_II separate_JJ discussions_NN2 on_II good_JJ goals_NN2 (_( effective_JJ goals_NN2 )_) on_II one_MC1 hand_NN1 and_CC right_JJ goals_NN2 (_( efficient_JJ goals_NN2 )_) on_II the_AT other_JJ ._. 
</s>
<s>
(_( Williams_NP1 &;_NULL Samset_NP1 2010:43_MC )_) For_IF linguistic_JJ convenience_NN1 ,_, I_PPIS1 will_VM describe_VVI the_AT dichotomy_NN1 as_II being_VBG between_II "_" effective_JJ goals_NN2 "_" and_CC "_" right_JJ goals_NN2 "_" ._. 
</s>
<s>
As_II the_AT question_NN1 of_IO which_DDQ goals_NN2 are_VBR "_" right_RR "_" is_VBZ strongly_RR situation_NN1 dependent_NN1 (_( i.e._REX the_AT right_JJ goals_NN2 depend_VV0 on_II the_AT purpose_NN1 of_IO the_AT project_NN1 )_) ,_, it_PPH1 is_VBZ impossible_JJ to_TO generalize_VVI specific_JJ right_JJ goals_NN2 ._. 
</s>
<s>
Thus_RR the_AT question_NN1 of_IO right_JJ goals_NN2 will_VM be_VBI saved_VVN for_IF the_AT next_MD chapter_NN1 ._. 
</s>
<s>
In_II contrast_NN1 ,_, the_AT discussion_NN1 on_II effective_JJ goals_NN2 will_VM be_VBI attacked_VVN right_RR away_RL ._. 
</s>
<s>
Goals_NN2 shall_VM be_VBI clear_JJ (_( clarity_NN1 )_) ._. 
</s>
<s>
This_DD1 conclusion_NN1 is_VBZ cited_VVN in_II a_AT1 large_JJ number_NN1 of_IO sources_NN2 and_CC take_VV0 different_JJ forms_NN2 ._. 
</s>
<s>
According_II21 to_II22 some_DD sources_NN2 ,_, goals_NN2 must_VM be_VBI specific_JJ ,_, measureable_JJ and_CC not_XX too_RG complex_JJ (_( Kerzner_NP1 2009:296_MC )_) ,_, measureable_JJ and_CC monitor_VV0 able_JJ (_( Krishna_NP1 2006:6061_MC )_) ,_, well_RR communicated_VVN ,_, understood_VVN and_CC generally_RR accepted_VVN (_( Hong_NP1 ,_, Nahm_NP1 &;_NULL Doll_NN1 2004:12741275_MC )_) and_CC that_CST teams_NN2 shall_VM be_VBI provided_VVN with_IW simple_JJ ,_, unequivocal_JJ directions_NN2 (_( McComb_NP1 &;_NULL Green_NP1 1999:11_MC )_) ._. 
</s>
<s>
Furthermore_RR Turner_NP1 and_CC Cochrane_NP1 use_VV0 the_AT clarity_NN1 of_IO goals_NN2 (_( whether_CSW they_PPHS2 are_VBR clear_JJ or_CC not_XX )_) as_CSA one_MC1 of_IO two_MC criteria_NN2 to_TO classify_VVI project_NN1 risk_NN1 categories_NN2 (_( Turner_NP1 &;_NULL Cochrane_NP1 1993:9395_MC )_) ._. 
</s>
<s>
In_II an_AT1 empirical_JJ study_NN1 on_II what_DDQ competencies_NN2 project_VV0 managers_NN2 need_VV0 in_II different_JJ project_NN1 stages_NN2 Skulmoski_NN1 and_CC Hartman_NP1 note_VV0 that_CST the_AT project_NN1 's_GE strategic_JJ phase_NN1 necessitate_VV0 above_II all_DB communication_NN1 competencies_NN2 and_CC the_AT ability_NN1 to_TO articulate_VVI complex_JJ situations_NN2 in_II an_AT1 understandable_JJ manner_NN1 (_( Skulmoski_NP1 &;_NULL Hartman_NP1 2010:6466_MC )_) ._. 
</s>
<s>
Again_RT ,_, these_DD2 definitions_NN2 point_VV0 to_II a_AT1 dichotomy_NN1 ,_, in_II which_DDQ some_DD authors_NN2 emphasize_VV0 the_AT importance_NN1 of_IO communication_NN1 (_( which_DDQ I_PPIS1 will_VM call_VVI the_AT communication-school_NN1 )_) to_TO reach_VVI clarity_NN1 ,_, whereas_CS others_NN2 see_VV0 clarity_NN1 as_CSA something_PN1 ,_, which_DDQ is_VBZ primarily_RR reached_VVN through_II goals_NN2 being_VBG quantifiable_JJ and_CC measureable_JJ (_( which_DDQ I_PPIS1 will_VM call_VVI the_AT quantification-school_NN1 )_) ._. 
</s>
<s>
The_AT quantification-school_NN1 is_VBZ further_RRR supported_VVN by_II the_AT S.M.A.R.T_NP1 method_NN1 ,_, which_DDQ states_VVZ that_CST goals_NN2 must_VM be_VBI specific_JJ ,_, measureable_JJ ,_, attainable_JJ ,_, relevant_JJ and_CC tangible_JJ (_( Kerzner_NP1 2009_MC :_: 296_MC )_) ._. 
</s>
<s>
In_II contrast_NN1 to_II the_AT quantification-school_NN1 ,_, some_DD authors_NN2 even_RR point_VV0 to_II the_AT existence_NN1 of_IO hidden_JJ goals_NN2 (_( Frame_NN1 1995:49_MC ;_; Turner_NP1 1993:5556_MC ;_; Nash_NP1 ,_, Plugge_NP1 &;_NULL Eurelings_NP1 2000:1_MC ;_; Kotsalo-Mustonen_NN1 1996:4950_MC )_) ._. 
</s>
<s>
Turner_NP1 further_RRR notes_VVZ about_II hidden_JJ goals_NN2 ,_, that_CST they_PPHS2 can_VM either_RR support_VVI or_CC counteract_VVI the_AT overt_JJ goals_NN2 ,_, and_CC also_RR gives_VVZ some_DD examples_NN2 of_IO hidden_JJ goals_NN2 ,_, e.g._REX that_CST a_AT1 project_NN1 should_VM lead_VVI to_II enabling_VVG layoffs_NN2 (_( Turner_NP1 1993:55_MC )_) ._. 
</s>
<s>
Although_CS Frame_NN1 and_CC Nash_NP1 neither_RR state_VV0 how_RRQ or_CC why_RRQ goals_NN2 should_VM become_VVI or_CC be_VBI kept_VVN hidden_VVN ,_, Saravirta_NP1 offers_VVZ one_MC1 possible_JJ explanation_NN1 (_( using_VVG Nonaka_NP1 's_GE and_CC Takeuchi_NP1 's_GE terminology_NN1 )_) ,_, that_CST goals_NN2 which_DDQ can_VM be_VBI articulated_VVN are_VBR either_RR explicit_JJ (_( if_CS they_PPHS2 have_VH0 been_VBN articulated_VVN )_) or_CC implicit_JJ (_( if_CS they_PPHS2 have_VH0 not_XX yet_RR been_VBN articulated_VVN )_) ,_, whereas_CS goals_NN2 which_DDQ can_VM not_XX be_VBI articulated_VVN stay_VV0 tacit_JJ (_( hidden_VVN )_) (_( Saravirta_NP1 2001:5455_MC )_) ._. 
</s>
<s>
Kotsalo-Mustonen_NN1 further_RRR states_VVZ that_CST organizations_NN2 as_II31 well_II32 as_II33 players_NN2 can_VM have_VHI tacit_JJ goals_NN2 ,_, and_CC that_CST in_II organizations_NN2 these_DD2 tacit_JJ goals_NN2 usually_RR relate_VV0 to_II organizational_JJ tradition_NN1 and_CC culture_NN1 ,_, whereas_CS players_NN2 '_GE tacit_JJ goal_NN1 usually_RR exist_VV0 to_TO serve_VVI the_AT individual_NN1 's_GE personal_JJ valuations_NN2 and_CC ambitions_NN2 (_( Kotsalo-_JJ Mustonen_NN1 1996:4950_MC )_) ._. 
</s>
<s>
In_II summary_NN1 ,_, there_EX seems_VVZ to_TO be_VBI two_MC different_JJ ways_NN2 to_TO look_VVI at_II how_RRQ to_TO make_VVI goals_NN2 effective_JJ ._. 
</s>
<s>
The_AT difference_NN1 can_VM be_VBI described_VVN as_II the_AT striving_NN1 for_IF creating_VVG and_CC publicizing_VVG quantifiable_JJ goals_NN2 ,_, which_DDQ need_VM not_XX be_VBI actively_RR communicated_VVN on_II one_MC1 hand_NN1 ,_, while_CS on_II the_AT other_JJ hand_NN1 emphasis_NN1 is_VBZ placed_VVN on_II more_RGR qualitative_JJ goals_NN2 and_CC the_AT project_NN1 manager_NN1 's_GE capacity_NN1 and_CC willingness_NN1 to_TO communicate_VVI these_DD2 to_II the_AT team_NN1 ._. 
</s>
<s>
As_CSA hidden_VVN goals_NN2 can_VM neither_RR be_VBI quantified_VVN ,_, nor_CC communicated_VVD ,_, neither_DD1 school_NN1 can_VM explain_VVI the_AT existence_NN1 of_IO these._NNU 2.2_MC The_AT setting_NN1 of_IO right_JJ goals_NN2 Introduction_NN1 Goals_NN2 are_VBR important_JJ ._. 
</s>
<s>
Different_JJ goals_NN2 lead_VV0 to_II different_JJ projects_NN2 (_( Abdel-Hamid_NN1 ,_, Sengupta_NP1 &;_NULL Swett_NP1 1999:546547_MC )_) ._. 
</s>
<s>
Choosing_VVG the_AT right_JJ goals_NN2 is_VBZ of_IO immense_JJ importance_NN1 (_( Williams_NP1 &;_NULL Samset_NP1 2010:3839_MC )_) ._. 
</s>
<s>
Right_JJ goals_NN2 are_VBR not_XX something_PN1 general_JJ ._. 
</s>
<s>
The_AT "_" rightness_NN1 "_" of_IO goals_NN2 depend_VV0 how_RGQ well_RR the_AT project_NN1 goals_NN2 match_VV0 the_AT expectations_NN2 of_IO central_JJ actors._NNU 2.2.1_MC Who_PNQS have_VH0 expectations_NN2 of_IO a_AT1 project_NN1 Starting_VVG with_IW central_JJ parties_NN2 (_( owner_NN1 and_CC team_NN1 )_) ,_, going_VVG on_RP to_II project_NN1 manager_NN1 (_( Krishna_NP1 2006:60_MC ,_, PMI_NP1 2008:73_MC ;_; Andersen_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2004:4851_MC ;_; Turner_NP1 1993:427_MC ;_; PMI_NP1 2008:7377_MC )_) Continuing_VVG to_II stakeholders_NN2 ..._... 
</s>
<s>
(_( Turner_NP1 1993:5455_MC ;_; PMI_NP1 2008:2326_MC ;_; Turner_NP1 1993:54_MC ;_; Englund_NP1 2006:353355_MC ;_; Sahlin-Andersson_NP1 1986:156158_MC ;_; Cleland_NP1 1994:140_MC 142_MC )_) Going_VVG to_II players_NN2 (_( Frame_NN1 1995:4849_MC ;_; Kirby_NP1 1996:211_MC )_) ._. 
</s>
<s>
Strategy_NN1 as_CSA "_" player_NN1 "_" in_II goals_NN2 (_( Artto_NP1 et_RA21 al_RA22 2006:17_MC ;_; PMI_NP1 2008:1011_MC ;_; Turner_NP1 1993:18_MC ,_, 3743_MC ;_; Cleland_NP1 1994:8182_MC ;_; Schwalbe_NP1 2006:3233_MC ;_; Wysocki_NP1 &;_NULL McGary_NP1 2003:357358_MC ;_; Artto_NP1 &;_NULL Wikstrm_NP1 2005:349350_MC ;_; Artto_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2006:373_MC )_) ._. 
</s>
<s>
PSO-view_NN1 (_( Andersen_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2004:17_MC ,_, 3748_MC ;_; Turner_NP1 1993:5256_MC ,_, 6366_MC )_) Top_JJ management_NN1 (_( PMI_NP1 2008:24,73_MC )_) and_CC sponsors_NN2 (_( Artto_NP1 et_NP1 ._. 
</s>
<s>
al_NP1 2006:42_MC ;_; Kerzner_NP1 2009:19_MC ;_; Kerzner_NP1 2009:393_MC ;_; Miller_NP1 &;_NULL Hobbs_NP1 2005:45_MC ;_; Meredith_NP1 &;_NULL Mantel_NP1 2010:117_MC )_) ._. 
</s>
<s>
Link_VV0 to_II next._NNU 2.2.2_MC Project_NN1 selection_NN1 Introductory_JJ paragraph_NN1 (_( relevancy_NN1 )_) ._. 
</s>
<s>
Economic_JJ feasibility_NN1 (_( Schwalbe_NP1 2006:3743_MC )_) and_CC strategic_JJ fit_NN1 (_( Artto_NP1 et_RA21 al._RA22 2006:371372_MC )_) are_VBR some_DD simple_JJ metrics_NN2 ._. 
</s>
<s>
Further_RRR complex_JJ models_NN2 of_IO analysis_NN1 can_VM be_VBI utilized_VVN (_( Cleland_NP1 1994:8688_MC ;_; Schwalbe_NP1 2006:4345_MC )_) ,_, even_RR a_AT1 balanced_JJ scorecard_NN1 can_VM be_VBI used_VVN (_( Schwalbe_NP1 2006:45_MC )_) ._. 
</s>
<s>
There_EX are_VBR weaknesses_NN2 :_: interrelations_NN2 can_VM not_XX be_VBI estimated_VVN and_CC estimates_NN2 are_VBR made_VVN based_VVN on_II highly_RR tenuous_JJ information_NN1 ._. 
</s>
<s>
Sum_NN1 of_IO projects_NN2 :_: strategic_JJ fit_NN1 (_( Cleland_NP1 1994:8185_MC )_) ._. 
</s>
<s>
Methods_NN2 for_IF increasing_VVG inter-_JJ organization_NN1 and_CC synergies_NN2 (_( PMI_NP1 2008:910_MC )_) ._. 
</s>
<s>
Summary_NN1 of_IO project_NN1 selection_NN1 's_GE effect_NN1 on_II project_NN1 goals_NN2 :_: Hurdle-clearing_JJ behavior_NN1 (_( Williams_NP1 &;_NULL Samset_NP1 2010:43_MC )_) ,_, effects_NN2 of_IO other_JJ projects_NN2 on_II new_JJ project_NN1 and_CC competition_NN1 for_IF limited_JJ resources_NN2 (_( Graham_NP1 &;_NULL Englund_NP1 1997:3839_MC )_) ._. 
</s>
<s>
2.3_MC Summary_NN1 of_IO project_NN1 goal_NN1 setting_NN1 Introduction_NN1 to_TO recap_VVI of_IO (_( 2.1_MC 2.2_MC )_) Recap_NN1 of_IO 2.1_MC ._. 
</s>
<s>
Quite_RG detailed_JJ ._. 
</s>
<s>
Recap_NN1 of_IO 2.2_MC ._. 
</s>
<s>
Quite_RG detailed_JJ ._. 
</s>
<s>
Summary_NN1 of_IO recaps_NN2 ._. 
</s>
<s>
Shining_VVG the_AT light_NN1 on_II the_AT weak_JJ areas_NN2 in_II project_NN1 management_NN1 literature_NN1 ._. 
</s>
<s>
Link_VV0 to_II next._NNU 3_MC ._. 
</s>
<s>
Information-processing_NN1 and_CC decision-making_JJ Introduction_NN1 ,_, explanation_NN1 of_IO structure_NN1 3.1_MC Models_NN2 and_CC perspectives_NN2 on_II decision-making_NN1 3.1.1_MC Simon_NP1 's_GE model_NN1 of_IO decision_NN1 making_VVG Detailed_JJ re-examination_NN1 of_IO Simon_NP1 's_GE model_NN1 ._. 
</s>
<s>
(_( Simon_NP1 1977:4044_MC )_) 3.1.2_MC Different_JJ perspectives_NN2 on_II decision-making_NN1 What_DDQ are_VBR decision-making_JJ perspectives_NN2 ,_, what_DDQ is_VBZ their_APPGE relevance_NN1 ?_? 
</s>
<s>
Quote_VV0 some_DD comparative_JJ studies_NN2 (_( =_FO Bjrkman_NP1 ,_, =_FO Allison_NP1 The_AT rational_JJ choice_NN1 -perspective_NN1 Description_NN1 of_IO rational_JJ choice_NN1 perspective_NN1 ._. 
</s>
<s>
(_( Bjrkman_NN1 ,_, others_NN2 ..._... )_) ._. 
</s>
<s>
The_AT Description_NN1 of_IO justification_NN1 perspective_NN1 ._. 
</s>
<s>
(_( Bjrkman_NN1 ,_, others_NN2 ..._... )_) ._. 
</s>
<s>
The_AT political_JJ perspective_NN1 Description_NN1 of_IO political_JJ perspective_NN1 (_( Cyert_VV0 &;_NULL March_NPM1 1963_MC ;_; March_NPM1 1981_MC ;_; Pfeffer_NP1 1981_MC )_) ._. 
</s>
<s>
The_AT rule-based_JJ perspective_NN1 Description_NN1 of_IO rule-based_JJ perspective_NN1 (_( March_NPM1 1981_MC ;_; Bjrkman_NP1 1987:1012_MC )_) ._. 
</s>
<s>
Summary_NN1 of_IO perspectives_NN2 Summary_NN1 of_IO perspectives_NN2 with_IW emphasis_NN1 on_II information-processing_NN1 ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) 3.2_MC The_AT decision-making_JJ dimension_NN1 Recap_NN1 and_CC summary_NN1 ,_, who_PNQS influence_VV0 project_NN1 goals_NN2 Recap_VV0 and_CC summary_NN1 ,_, how_RRQ are_VBR decisions_NN2 on_II project_NN1 goals_NN2 made_VVN ?_? 
</s>
<s>
We_PPIS2 do_VD0 n't_XX know_VVI ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) &lsqb;_( Figure_NN1 &rsqb;_) Expert_NN1 judgment_NN1 ?_? ?_? ?_? 
</s>
<s>
(_( PMI_NP1 2008:7377_MC )_) ._. 
</s>
<s>
The_AT project_NN1 literature_NN1 does_VDZ not_XX take_VVI stance_NN1 on_II decision-making_JJ perspectives_NN2 ._. 
</s>
<s>
Two_MC different_JJ interpretations_NN2 :_: either_RR projects_NN2 are_VBR always_RR decided_VVN on_II objectively_RR (_( rational_JJ choice_NN1 )_) or_CC this_DD1 is_VBZ a_AT1 major_JJ lapse_NN1 ._. 
</s>
<s>
Next_MD step_NN1 :_: to_TO be_VBI able_JK to_TO prove_VVI a_AT1 lapse_NN1 ,_, I_PPIS1 need_VV0 to_TO disprove_VVI the_AT first_MD interpretation_NN1 ._. 
</s>
<s>
Link_VV0 to_II next._NNU 3.3_MC The_AT project_NN1 goal_NN1 setting_NN1 process_NN1 ._. 
</s>
<s>
Summary_NN1 and_CC hypothesis_NN1 ._. 
</s>
<s>
Rationalization_NN1 of_IO situation_NN1 ._. 
</s>
<s>
Definition_NN1 of_IO hypothesis_NN1 1_MC1 :_: If_CS political_JJ decision-making_NN1 exists_VVZ ,_, this_DD1 implies_VVZ that_CST there_EX is_VBZ more_DAR than_CSN one_MC1 party_NN1 to_II the_AT process_NN1 ,_, and_CC that_CST the_AT parties_NN2 are_VBR undecided_JJ on_II either_DD1 what_DDQ decision_NN1 should_VM be_VBI made_VVN or_CC how_RRQ it_PPH1 should_VM be_VBI made_VVN ._. 
</s>
<s>
Rationalization_NN1 and_CC hypothesis_NN1 2_MC :_: If_CS other_JJ perspectives_NN2 exist_VV0 in_II projects_NN2 ,_, there_EX is_VBZ no_AT reason_NN1 to_TO believe_VVI they_PPHS2 would_VM not_XX impart_VVI on_II goal_NN1 setting._NNU 4_MC ._. 
</s>
<s>
Indices_NN2 of_IO decision-making_JJ perspectives_NN2 in_II project_NN1 management_NN1 literature_NN1 Introduction_NN1 Weight_NN1 on_II political_JJ perspective_NN1 (_( or_CC focus_VV0 solely_RR on_II political_JJ perspective_NN1 )_) 4.1_MC Rule-based_JJ decision-making_JJ Introduction_NN1 Circumstantial_JJ evidence_NN1 of_IO rules_NN2 in_II information-processing_NN1 (_( Schwalbe_NP1 2006:73_MC 77_MC ;_; Meredith_NP1 &;_NULL Mantel_NP1 2010:4258_MC ,_, 70_MC ;_; Frame_NN1 2002:205206_MC )_) ._. 
</s>
<s>
Normative_JJ nature_NN1 of_IO practitioners_NN2 '_GE books_NN2 ,_, existence_NN1 of_IO a_AT1 de-facto_JJ standard_NN1 and_CC certification_NN1 system_NN1 (_( Hodgson_NP1 2002:807_MC ;_; Lenfle_NP1 &;_NULL Koch_NP1 2010:43_MC )_) ._. 
</s>
<s>
Academic_JJ interest_NN1 in_II heuristic_JJ research_NN1 (_( success/failure_NN1 factors_NN2 )_) ,_, tendency_NN1 to_TO use_VVI case_NN1 studies_NN2 and_CC anecdotal_JJ evidence._NNU 4.2_MC Justification-based_JJ decision-making_JJ Introduction_NN1 Hurdle-clearing_NN1 behavior_NN1 (_( Williams_NP1 &;_NULL Samoset_NP1 2010_MC ;_; Gilbreath_NP1 1986:3536_MC )_) and_CC deliberate_JJ misestimating_NN1 (_( Gilbreath_NP1 1986:156_MC )_) ._. 
</s>
<s>
4.3_MC Political_JJ decision-making_JJ Introduction_NN1 :_: Political_JJ behavior_NN1 (_( Link_VV0 to_II OB_FO )_) ._. 
</s>
<s>
Structure_NN1 :_: Is_VBZ political_JJ behavior_NN1 related_VVN to_II political-based_JJ decision-making_NN1 ?_? 
</s>
<s>
Explanation_NN1 of_IO the_AT concept_NN1 of_IO power_NN1 ._. 
</s>
<s>
Description_NN1 of_IO purpose._NNU 4.3.1_MC What_DDQ is_VBZ political_JJ behavior_NN1 Building_VVG a_AT1 definition_NN1 (_( Pfeffer_NP1 1981_MC ;_; Rollinson_NP1 2008:405_MC )_) ._. 
</s>
<s>
Implications_NN2 :_: Power_NN1 and_CC politics_NN1 are_VBR related_VVN (_( Rollinson_NP1 2008:405_MC )_) ._. 
</s>
<s>
Instability_NN1 breeds_NN2 politics_NN1 (_( Rollinson_NP1 2008:405_MC ;_; Pinto_NP1 1996_MC ;_; Englund_NP1 2006:356_MC )_) ._. 
</s>
<s>
Politics_NN1 creates_VVZ conflict_NN1 but_CCB also_RR helps_VVZ solve_VVI disputes_NN2 (_( Rollinson_NP1 2008:405_MC )_) ._. 
</s>
<s>
Political_JJ decision-making_NN1 and_CC political_JJ behavior_NN1 are_VBR related_VVN ._. 
</s>
<s>
Cartwright_NN1 says_VVZ political_JJ behavior_NN1 is_VBZ human_JJ (_( Cartwright_NP1 2002:142_MC )_) and_CC politics_NN1 can_VM neither_RR be_VBI deemed_VVN intrinsically_RR negative_JJ or_CC positive_JJ (_( Cavanagh_NP1 ,_, Moberg_NP1 &;_NULL Velasquez_NP1 1981:369371_MC )_) ._. 
</s>
<s>
Power_NN1 constitutes_VVZ a_AT1 central_JJ part_NN1 in_II understanding_VVG organizations_NN2 (_( Cavanagh_NP1 et_RA21 al._RA22 1981:363_MC )_) ._. 
</s>
<s>
Politics_NN1 can_VM not_XX be_VBI understood_VVN without_IW power_NN1 :_: Link_VV0 to_II next._NNU 4.3.2_MC Power_NN1 in_II organizations_NN2 Power_NN1 is_VBZ influence_NN1 (_( French_JJ &;_NULL Raven_NN1 1959:6171_MC )_) ._. 
</s>
<s>
Two_MC views_NN2 :_: All_DB use_NN1 of_IO power_NN1 is_VBZ political_JJ (_( Martin_NP1 &;_NULL Sims_NP1 1956:2528_MC )_) ,_, only_RR unsanctioned_JJ use_NN1 of_IO power_NN1 is_VBZ political_JJ (_( Mayes_NP1 &;_NULL Allen_NP1 1977:674677_MC )_) ._. 
</s>
<s>
4.3.3_MC Politik_NP1 i_ZZ1 projekt_VV0 Different_JJ views_NN2 :_: Project_NN1 management_NN1 in_II inextricably_RR linked_VVN to_II politics_NN1 ,_, due_II21 to_II22 several_DA2 factors_NN2 (_( Pinto_NP1 2000:8586_MC )_) Politics_NN1 is_VBZ central_JJ to_TO project_VVI management_NN1 ,_, and_CC the_AT fact_NN1 that_CST managers_NN2 are_VBR ignorant_JJ of_IO this_DD1 ,_, only_RR makes_VVZ it_PPH1 worse_JJR (_( Pinto_NP1 &;_NULL Kharbanda_NP1 1995:41_MC )_) ._. 
</s>
<s>
Project_NN1 managers_NN2 need_VV0 political_JJ competence_NN1 to_TO hold_VVI their_APPGE own_DA against_II all_DB other_JJ parties_NN2 ,_, who_PNQS are_VBR politically_RR competent_JJ ,_, and_CC do_VD0 not_XX shy_VVI away_II21 from_II22 using_VVG their_APPGE power_NN1 (_( Pinto_NP1 1997:12_MC )_) Pinto_NP1 's_GE reasoning_NN1 is_VBZ believable_JJ ,_, as_CSA it_PPH1 links_VVZ to_II many_DA2 of_IO projects_NN2 '_GE special_JJ features_NN2 (_( instability_NN1 etc_RA ._. )_) 
</s>
<s>
Projects_NN2 are_VBR rife_JJ with_IW rampant_JJ politics_NN1 ._. 
</s>
<s>
Because_CS teams_NN2 are_VBR temporary_JJ organizations_NN2 ,_, the_AT risk_NN1 of_IO politic_JJ dispute_NN1 within_II teams_NN2 is_VBZ accentuated_VVN ._. 
</s>
<s>
A_AT1 Project_NN1 manager_NN1 must_VM interest_NN1 himself_PPX1 of_IO every_AT1 player_NN1 and_CC try_VV0 to_TO ascertain_VVI every_AT1 player_NN1 's_GE expectations_NN2 for_IF the_AT project_NN1 ,_, whether_CSW they_PPHS2 are_VBR explicit_JJ or_CC hidden_VVN ._. 
</s>
<s>
(_( Frame_NN1 2002:149160_MC )_) Project_NN1 managers_NN2 and_CC politicians_NN2 are_VBR very_RG alike_RR ,_, they_PPHS2 do_VD0 n't_XX have_VHI the_AT power_NN1 ,_, but_CCB they_PPHS2 influence_VV0 (_( Frame_NN1 1995:47_MC )_) ._. 
</s>
<s>
Empirical_JJ studies_NN2 show_VV0 ,_, that_DD1 politics_NN1 in_II projects_NN2 happen_VV0 (_( Ewusi-Mensah_NP1 &;_NULL Przasnyski_NP1 1991:82_MC )_) ._. 
</s>
<s>
Even_RR sponsors_NN2 need_VV0 to_TO be_VBI politically_RR adept_JJ (_( Kloppenborg_NP1 ,_, Tesch_NP1 ,_, Manolis_NP1 &;_NULL Heitkamp_NP1 2006:17_MC )_) ._. 
</s>
<s>
Politics_NN1 in_II projects_NN2 is_VBZ unavoidable_JJ ,_, and_CC not_XX wanting_VVG to_TO take_VVI part_NN1 bodes_VVZ trouble_NN1 ._. 
</s>
<s>
(_( PMI_NP1 2008:420_MC )_) ._. 
</s>
<s>
4.3.4_MC Politics_NN1 in_II projects_NN2 good_JJ or_CC bad_JJ Introduction_NN1 Politics_NN1 is_VBZ perceived_VVN as_CSA negative_JJ (_( Pinto_NP1 2000:85_MC ;_; Englund_NP1 2006:451_MC )_) but_CCB possibly_RR it_PPH1 can_VM not_XX be_VBI avoided_VVN ._. 
</s>
<s>
But_CCB what_DDQ stance_NN1 should_VM project_VVI managers_NN2 take_VV0 ?_? 
</s>
<s>
You_PPY can_VM see_VVI it_PPH1 as_RG unavoidable_JJ (_( Pinto_NP1 2000:85,86_MC )_) ,_, and_CC Project_NN1 managers_NN2 should_VM thus_RR learn_VVI to_TO play_VVI the_AT game_NN1 (_( Pinto_NP1 2000:86_MC ;_; Pinto_NP1 &;_NULL Kharbanda_NP1 1995:42_MC )_) ._. 
</s>
<s>
Or_CC you_PPY can_VM see_VVI politics_NN1 as_II an_AT1 integral_JJ (_( and_CC neutral_JJ )_) aspect_NN1 of_IO project_NN1 management_NN1 ,_, and_CC project_NN1 managers_NN2 should_VM see_VVI political_JJ ability_NN1 just_RR as_CSA any_DD other_JJ relative_JJ skill_NN1 (_( Frame_NN1 2002:156157_MC ;_; Englund_NP1 2006:349_MC )_) ._. 
</s>
<s>
My_APPGE opinion_NN1 is_VBZ irrelevant_JJ 4.4_MC Summary_NN1 of_IO decision-making_JJ perspectives_NN2 in_II project_NN1 management_NN1 Summary_NN1 of_IO findings_NN2 ._. 
</s>
<s>
Summary_NN1 :_: Politics_NN1 exist_VV0 ._. 
</s>
<s>
And_CC given_VVN the_AT nature_NN1 of_IO projects_NN2 it_PPH1 should_VM surprise_VVI no-one_PN1 ._. 
</s>
<s>
To_TO reflect_VVI on_II the_AT hypotheses_NN2 :_: Hypothesis_NN1 1_MC1 :_: If_CS political_JJ decision-making_NN1 exists_VVZ ,_, this_DD1 implies_VVZ that_CST there_EX is_VBZ more_DAR than_CSN one_MC1 party_NN1 to_II the_AT process_NN1 ,_, and_CC that_CST the_AT parties_NN2 are_VBR undecided_JJ on_II either_DD1 what_DDQ decision_NN1 should_VM be_VBI made_VVN or_CC how_RRQ it_PPH1 should_VM be_VBI made_VVN ._. 
</s>
<s>
Hypothesis_NN1 2_MC :_: If_CS other_JJ perspectives_NN2 exist_VV0 in_II projects_NN2 ,_, there_EX is_VBZ no_AT reason_NN1 to_TO believe_VVI they_PPHS2 would_VM not_XX impart_VVI on_II goal_NN1 setting_NN1 ._. 
</s>
<s>
On_II H1_FO :_: Political_JJ decision-making_NN1 exists_VVZ ,_, we_PPIS2 can_VM assume_VVI the_AT crowd_NN1 is_VBZ divided_VVN On_II H2_FO :_: Different_JJ perspectives_NN2 exist_VV0 ._. 
</s>
<s>
We_PPIS2 must_VM thus_RR assume_VVI even_RR goal-setting_JJ decisions_NN2 may_VM be_VBI politicized._NNU 5_MC ._. 
</s>
<s>
Summary_NN1 and_CC conclusions_NN2 5.1_MC Summary_NN1 Introduction_NN1 :_: Purpose_NN1 5.1.1_MC The_AT contextual_JJ dimension_NN1 in_II project_NN1 literature_NN1 Reflection_NN1 on_II Chapter_NN1 2_MC 5.1.2_MC The_AT decision-making_JJ dimension_NN1 in_II project_NN1 literature_NN1 Reflection_NN1 on_II the_AT things_NN2 lacking_VVG in_II PM_NP1 literature_NN1 :_: Decisions_NN2 are_VBR not_XX made_VVN ,_, they_PPHS2 come_VV0 automatically_RR ._. 
</s>
<s>
There_EX is_VBZ never_RR a_AT1 human_JJ choice_NN1 to_TO be_VBI made_VVN appraisal_NN1 ,_, calculation_NN1 and_CC expert_NN1 judgment_NN1 know_VV0 no_AT alternatives_NN2 ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 ,_, the_AT field_NN1 of_IO organizational_JJ behavior_NN1 gives_VVZ a_AT1 totally_RR different_JJ ,_, and_CC very_RG nuanced_JJ picture._NNU 5.1.3_MC Synthesis_NN1 of_IO dimensions_NN2 Contextual_JJ dimension_NN1 from_II project_NN1 literature_NN1 :_: exists_VVZ Decision-making_JJ dimension_NN1 from_II project_NN1 literature_NN1 :_: does_VDZ not_XX exists_VVZ No_AT synthesis_NN1 possible_JJ !_! 
</s>
<s>
Synthesizing_VVG contextual_JJ dimension_NN1 from_II project_NN1 literature_NN1 with_IW decision-making_JJ views_NN2 from_II organizational_JJ behavior_NN1 leads_VVZ to_II "_" Buttler_NP1 's_GE model_NN1 "_" (_( linguistic_JJ convenience_NN1 )_) :_: &lsqb;_( Figure_NN1 &rsqb;_) Explication_NN1 of_IO Buttler_NP1 's_GE model_NN1 ._. 
</s>
<s>
Implication_NN1 of_IO Buttler_NP1 's_GE model_NN1 Advantages_NN2 of_IO Buttler_NP1 's_GE model_NN1 over_II view_NN1 espoused_VVN by_II PM_NP1 literature_NN1 :_: 1_MC1 Understanding_NN1 how_RRQ goals_NN2 are_VBR set_VVN 2_MC Usable_JJ for_IF analysis_NN1 3_MC Gives_VVZ framework_NN1 for_IF analyzing_VVG hidden_VVN goals._NNU 5.2_MC Conclusions_NN2 and_CC implications_NN2 Introduction_NN1 :_: practical_JJ research_NN1 5.2.1_MC Implications_NN2 for_IF practitioners_NN2 PM_NP1 role_NN1 in_II goal-setting_NN1 (_( Lenfle_NP1 &;_NULL Koch_NP1 2010:48_MC )_) ._. 
</s>
<s>
PM_NP1 merely_RR a_AT1 implementer_NN1 ?_? 
</s>
<s>
(_( Cicmil_NP1 &;_NULL Hodgson_NP1 2006:111_MC )_) Relevant_JJ information_NN1 for_IF bosses_NN2 in_II process_NN1 organization_NN1 as_RG well_RR as_CSA for_IF project_NN1 managers_NN2 ._. 
</s>
<s>
Too_RG few_DA2 competent_JJ and_CC experienced_VVD PM_NP1 's_GE available_JJ as_CSA business_NN1 grows_VVZ (_( Pinto_NP1 &;_NULL Kharbanda_NP1 1995:41_MC )_) ._. 
</s>
<s>
The_AT accidental_JJ profession_NN1 (_( Frame_NN1 1995:xii_FO )_) ._. 
</s>
<s>
New_JJ PM_NP1 is_VBZ typically_RR a_AT1 former_DA specialist_NN1 (_( Meredith_NP1 &;_NULL Mantel_NP1 2010:109_MC )_) ._. 
</s>
<s>
Summary_NN1 ._. 
</s>
<s>
Projects_NN2 are_VBR characterized_VVN by_II change_NN1 (_( Choudhury_NP1 1988:3_MC ;_; Meredith_NP1 &;_NULL Mantel_NP1 2010:501_MC ;_; m.fl._NNU )_) ,_, thus_RR PM_NP1 's_VBZ should_VM be_VBI able_JK to_TO handle_VVI change_NN1 ._. 
</s>
<s>
Consternation_NN1 ._. 
</s>
<s>
Disbelief_NN1 ._. 
</s>
<s>
Summary_NN1 of_IO implications._NNU 5.2.2_MC Implications_NN2 for_IF research_NN1 The_AT project_NN1 management_NN1 discipline_NN1 has_VHZ had_VHN to_TO face_VVI a_AT1 tough_JJ set_NN1 of_IO challenges_NN2 :_: especially_RR getting_VVG it_PPH1 done_VDN on_II the_AT first_MD attempt_NN1 ._. 
</s>
<s>
The_AT discipline_NN1 has_VHZ focused_VVN on_II building_VVG the_AT project_NN1 manager_NN1 's_GE toolbox_NN1 ._. 
</s>
<s>
(_( Lenfle_NP1 &;_NULL Koch_NP1 2010:4243_MC )_) ._. 
</s>
<s>
This_DD1 is_VBZ no_AT minor_JJ deed_NN1 ._. 
</s>
<s>
But_CCB the_AT discipline_NN1 has_VHZ lost_VVN it_PPH1 's_VBZ roots_NN2 the_AT goals_NN2 ._. 
</s>
<s>
It_PPH1 's_VBZ dangerous_JJ to_TO know_VVI the_AT tools_NN2 ,_, without_IW knowing_VVG why_RRQ to_TO use_VVI them_PPHO2 (_( Meredith_NP1 &;_NULL Mantel_NP1 2010:35_MC )_) ._. 
</s>
<s>
Still_RR ,_, this_DD1 seems_VVZ to_TO be_VBI exactly_RR what_DDQ the_AT mainstream_JJ aims_NN2 at_II ._. 
</s>
<s>
(_( Lenfle_NP1 &;_NULL Koch_NP1 2010:32_MC )_) Further_JJR the_AT mechanistic_JJ worldview_NN1 of_IO ventral_JJ actors_NN2 in_II the_AT mainstream_NN1 has_VHZ done_VDN nothing_PN1 to_TO help_VVI ._. 
</s>
<s>
Unwillingness_NN1 to_TO see_VVI human_JJ individuals_NN2 as_CSA central_JJ actors_NN2 has_VHZ led_VVN into_II a_AT1 quagmire_NN1 ._. 
</s>
<s>
Conclusion_NN1 :_: Disregarding_VVG non-objective_JJ decision-making_JJ models_NN2 ,_, while_CS attempting_VVG to_II distance_NN1 the_AT project_NN1 professional_NN1 from_II fundamental_JJ decision-making_NN1 has_VHZ led_VVN to_II a_AT1 view_NN1 ,_, which_DDQ could_VM have_VHI been_VBN defensible_JJ in_II ancient_JJ Egypt_NP1 while_CS using_VVG slave_NN1 labor_NN1 to_TO build_VVI the_AT pyramids_NN2 but_CCB in_II today_RT 's_GE world_NN1 ,_, where_CS PM_NP1 is_VBZ spreading_VVG to_II ever_RR new_JJ fields_NN2 ,_, it_PPH1 is_VBZ not_XX compatible_JJ with_IW reality_NN1 ._. 
</s>
