<s>
How_RRQ price_NN1 affects_VVZ young_JJ adults_NN2 regarding_II Smartphone_NP1 Applications_NN2 1_MC1 ._. 
</s>
<s>
Introduction_NN1 In_II this_DD1 section_NN1 I_PPIS1 will_VM introduce_VVI some_DD background_NN1 information_NN1 regarding_II the_AT mobile_JJ phone_NN1 industryand_VV0 the_AT product_NN1 in_II question_NN1 ._. 
</s>
<s>
After_CS this_DD1 I_PPIS1 will_VM explain_VVI the_AT problem_NN1 I_PPIS1 aim_VV0 to_TO revolve_VVI my_APPGE study_NN1 around_RP ._. 
</s>
<s>
Lastly_RR I_PPIS1 will_VM shortly_RR introduce_VVI the_AT aim_NN1 and_CC structure_NN1 of_IO this_DD1 paper_NN1 ._. 
</s>
<s>
1.1_MC Background_NN1 The_AT first_MD mobile_JJ phone_NN1 was_VBDZ produced_VVN in_II 1973_MC by_II Motorola_NP1 and_CC weighing_VVG 2_MC kilograms_NNU2 (_( BBC_NP1 News_NN1 ,_, 2010_MC )_) ._. 
</s>
<s>
Since_II then_RT the_AT mobile_JJ phone_NN1 has_VHZ developed_VVN tremendously_RR and_CC gone_VVN through_II many_DA2 phases_NN2 ._. 
</s>
<s>
Today_RT ,_, most_RGT mobile_JJ phones_NN2 that_CST can_VM befound_VVI in_II stores_NN2 are_VBR so_JJ21 called_JJ22 smartphones_NN2 ._. 
</s>
<s>
The_AT term_NN1 smartphone_NN1 was_VBDZ first_MD introduced_VVN with_IW the_AT introduction_NN1 of_IO Ericsson_NP1 GS88_FO in_II 1997_NN1 (_( Stockholm_NP1 Smartphone_NP1 )_) ._. 
</s>
<s>
However_RR ,_, Smartphones_NN2 have_VH0 evolved_VVN notably_RR since_II then_RT andone_VV0 of_IO the_AT most_RGT notable_JJ changes_NN2 is_VBZ the_AT ability_NN1 to_TO modify_VVI your_APPGE own_DA phone_NN1 with_IW the_AT help_NN1 ofApplications_NN2 ._. 
</s>
<s>
Applications_NN2 canbe_NN1 downloaded_VVD from_II various_JJ sites_NN2 using_VVG an_AT1 internet_NN1 connection_NN1 either_RR for_IF free_JJ or_CC for_IF a_AT1 price_NN1 ._. 
</s>
<s>
The_AT smartphone_NN1 penetration_NN1 in_II Finland_NP1 is_VBZ growing_VVG rapidly_RR ._. 
</s>
<s>
In_II the_AT first_MD quarter_NN1 of_IO 2011_MC ,_, 29_MC %_NNU of_IO Finns_NN2 owned_VVD one_PN1 ._. 
</s>
<s>
In_II only_RR one_MC1 year_NNT1 this_DD1 number_NN1 had_VHD increased_VVN to_II 38_MC %_NNU and_CC in_II the_AT end_NN1 of_IO 2012_MC the_AT number_NN1 is_VBZ expected_VVN to_TO reach_VVI 50_MC %_NNU ._. 
</s>
<s>
Furthermore_RR ,_, the_AT market_NN1 value_NN1 for_IF sold_JJ applications_NN2 to_II these_DD2 smartphones_NN2 reached_VVD 4_MC million_NNO euros_NN2 in_II 2011_MC and_CC is_VBZ expected_VVN to_TO grow_VVI to_II 10_MC million_NNO euros_NN2 in_II 2012_MC ,_, which_DDQ means_VVZ it_PPH1 is_VBZ expected_VVN to_TO more_RRR than_CSN double_JJ in_II value_NN1 (_( Idean_NP1 ,_, 2012_MC )_) ._. 
</s>
<s>
1.2_MC Problem_NN1 Zone_NN1 The_AT price_NN1 of_IO a_AT1 product_NN1 has_VHZ a_AT1 big_JJ influence_NN1 on_II customers_NN2 decision_NN1 whether_CSW31 or_CSW32 not_CSW33 to_TO buy_VVI a_AT1 product_NN1 ._. 
</s>
<s>
Since_CS there_EX are_VBR such_DA a_AT1 big_JJ variety_NN1 of_IO applications_NN2 available_JJ for_IF smartphone_NN1 users_NN2 ,_, the_AT price_NN1 is_VBZ often_RR what_DDQ influences_VVZ the_AT potential_JJ customers_NN2 decision_NN1 first_MD ._. 
</s>
<s>
According_II21 to_II22 Kardes_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2008_MC )_) customers_NN2 often_RR rely_VV0 on_II price_NN1 in_BCL21 order_BCL22 to_TO judge_VVI a_AT1 products_NN2 quality_NN1 given_CS21 that_CS22 they_PPHS2 do_VD0 not_XX know_VVI about_II anything_PN1 about_II the_AT attributes_NN2 of_IO the_AT product_NN1 ._. 
</s>
<s>
However_RR ,_, one_PN1 can_VM often_RR access_VVI reviews_NN2 and_CC recommendations_NN2 of_IO apps_NN2 ._. 
</s>
<s>
Furthermore_RR ,_, price_NN1 is_VBZ one_MC1 of_IO the_AT four_MC important_JJ factors_NN2 that_CST determine_VV0 a_AT1 products_NN2 success_NN1 according_II21 to_II22 the_AT marketing_NN1 mix_NN1 theory_NN1 ._. 
</s>
<s>
Since_CS the_AT prices_NN2 within_II the_AT smartphone_NN1 application_NN1 industry_NN1 has_VHZ started_VVN to_TO decline_VVI ,_, and_CC that_CST the_AT revenue_NN1 from_II this_DD1 industry_NN1 is_VBZ predicted_VVN to_TO increase_VVI from_II $_NN 7.3_MC billion_NNO in_II 2011_MC to_II $36.7_NNU in_II 2015_MC (_( Mobithinking_NP1 ,_, 2012_MC )_) makes_VVZ pricing_VVG decisions_NN2 even_RR more_RGR important_JJ ._. 
</s>
<s>
Despite_II the_AT growth_NN1 ,_, there_EX is_VBZ very_RG little_DA1 information_NN1 regarding_II pricing_VVG strategies_NN2 for_IF smartphone_NN1 applications_NN2 ._. 
</s>
<s>
Since_CS this_DD1 industry_NN1 is_VBZ expecting_VVG a_AT1 massive_JJ growth_NN1 in_II the_AT close_JJ future_NN1 ,_, makes_VVZ this_DD1 an_AT1 important_JJ aspect_NN1 to_TO gather_VVI more_DAR knowledge_NN1 within.Moreover_NNU ,_, according_II21 to_II22 a_AT1 study_NN1 by_II Idean_NP1 (_( 2012_MC )_) the_AT average_JJ smartphone_NN1 user_NN1 in_II Finland_NP1 had_VHD seventeen_MC applications_NN2 installed_VVN on_II their_APPGE phone_NN1 ._. 
</s>
<s>
Out_II21 of_II22 these_DD2 17_MC applications_NN2 only_RR three_MC applications_NN2 were_VBDR paid_VVN for_IF ,_, which_DDQ means_VVZ the_AT common_JJ strategy_NN1 within_II application_NN1 sellers_NN2 is_VBZ to_TO simply_RR provide_VVI customers_NN2 with_IW free_JJ applications_NN2 ._. 
</s>
<s>
1.3_MC Aim_NN1 and_CC structure_NN1 of_IO this_DD1 study_NN1 The_AT aim_NN1 of_IO this_DD1 study_NN1 is_VBZ to_TO gain_VVI better_JJR knowledge_NN1 regarding_II young_JJ adults_NN2 attitude_NN1 towards_II prices_NN2 within_II the_AT smartphone_NN1 application_NN1 marketin_NN1 Finland_NP1 ._. 
</s>
<s>
With_IW this_DD1 study_NN1 I_PPIS1 hope_VV0 to_TO help_VVI those_DD2 who_PNQS sell_VV0 smartphone_NN1 applications_NN2 aimed_VVN for_IF young_JJ adults_NN2 to_TO price_VVI their_APPGE applications_NN2 more_RGR accurately_RR ._. 
</s>
<s>
For_IF the_AT academic_JJ community_NN1 this_DD1 will_VM also_RR serve_VVI as_II a_AT1 database_NN1 for_IF those_DD2 doing_VDG any_DD research_NN1 within_II the_AT smartphone_NN1 application_NN1 industry_NN1 ._. 
</s>
<s>
As_CSA mentioned_VVN earlier_RRR ,_, only_RR three_MC out_II21 of_II22 seventeen_MC applications_NN2 installed_VVN on_II smartphones_NN2 in_II 2011_MC were_VBDR paid_VVN for_IF ._. 
</s>
<s>
I_PPIS1 want_VV0 to_TO know_VVI more_RRR if_CS this_DD1 is_VBZ a_AT1 worthwhile_JJ strategy_NN1 or_CC not_XX ._. 
</s>
<s>
Personally_RR I_PPIS1 have_VH0 never_RR paid_VVN for_IF an_AT1 application_NN1 for_IF my_APPGE smartphone_NN1 ._. 
</s>
<s>
More_RGR specifically_RR ,_, the_AT research_NN1 question_NN1 that_CST I_PPIS1 wish_VV0 to_TO answer_VVI is_VBZ :_: How_RRQ does_VDZ price_VVI affect_NN1 young_JJ Finnish_JJ adults_NN2 regarding_II Smartphone_NP1 applications_NN2 The_AT structure_NN1 of_IO this_DD1 paper_NN1 will_VM be_VBI as_CSA follows_VVZ :_: First_MD I_PPIS1 will_VM introduce_VVI the_AT literature_NN1 related_VVN to_II my_APPGE research_NN1 question_NN1 ._. 
</s>
<s>
After_CS this_DD1 I_PPIS1 will_VM present_VVI my_APPGE methodology_NN1 and_CC results_NN2 ._. 
</s>
<s>
Following_VVG this_DD1 I_PPIS1 will_VM present_VVI a_AT1 discussion_NN1 with_II31 reference_II32 to_II33 the_AT literature_NN1 ._. 
</s>
<s>
2_MC ._. 
</s>
<s>
Literature_NN1 Review_NN1 &lsqb;_( will_NN1 add_VVI more_DAR sources_NN2 and_CC text_NN1 &rsqb;_) The_AT price_NN1 a_AT1 consumer_NN1 is_VBZ willing_JJ to_TO pay_VVI for_IF a_AT1 product_NN1 depends_VVZ on_II various_JJ factors_NN2 ._. 
</s>
<s>
J._NP1 Paul_NP1 Peter_NP1 and_CC Jerry_NP1 C._NP1 Olson_NP1 (_( 2008_MC )_) has_VHZ compiled_VVN a_AT1 framework_NN1 calledThe_VV0 pivotal_JJ role_NN1 of_IO price_NN1 in_II marketing_NN1 exchangesregarding_VVG which_DDQ factors_VVZ that_CST decide_VV0 the_AT price_NN1 a_AT1 consumer_NN1 is_VBZ willing_JJ to_TO pay_VVI for_IF a_AT1 product_NN1 and_CC which_DDQ factors_VVZ that_CST decides_VVZ the_AT price_NN1 companies_NN2 are_VBR willing_JJ to_TO sell_VVI a_AT1 product_NN1 for_IF ._. 
</s>
<s>
However_RR ,_, the_AT factors_NN2 involving_VVG which_DDQ factors_VVZ that_CST decide_VV0 the_AT selling_NN1 price_NN1 of_IO a_AT1 product_NN1 for_IF companies_NN2 will_VM not_XX be_VBI presented_VVN since_CS these_DD2 factors_NN2 do_VD0 not_XX help_VVI answering_VVG the_AT research_NN1 question_NN1 ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) 2.1_MC Consumer_NN1 costs_VVZ Consumer_NN1 costs_NN2 refer_VV0 to_II the_AT factor_NN1 that_CST decides_VVZ the_AT price_NN1 consumers_NN2 are_VBR willing_JJ to_TO pay_VVI for_IF a_AT1 product_NN1 ._. 
</s>
<s>
These_DD2 factors_NN2 are_VBR money_NN1 ,_, time_NNT1 ,_, cognitive_JJ activity_NN1 ,_, and_CC behavior_NN1 effort.Although_NNU these_DD2 factors_NN2 do_VD0 not_XX always_RR affect_VVI the_AT consumer_NN1 for_IF every_AT1 purchase_NN1 ,_, they_PPHS2 are_VBR frequently_RR used_VVN ._. 
</s>
<s>
2.1.1_MC Money_NN1 Money_NN1 in_II this_DD1 contextmeans_VVZ the_AT amount_NN1 of_IO money_NN1 that_CST is_VBZ spent_VVN on_II a_AT1 product_NN1 alone_RR ,_, i.e._REX the_AT price_NN1 of_IO the_AT product_NN1 ._. 
</s>
<s>
Most_DAT pricing_JJ research_NN1 has_VHZ concentrated_VVN on_II money_NN1 alone_RR and_CC these_DD2 researches_NN2 have_VH0 concluded_VVN that_CST the_AT same_DA amount_NN1 of_IO money_NN1 used_VVN is_VBZ perceived_VVN differently_RR among_II different_JJ individuals_NN2 or_CC market_VV0 segments_NN2 ._. 
</s>
<s>
For_REX21 example_REX22 ,_, money_NN1 earned_VVN from_II work_NN1 has_VHZ a_AT1 different_JJ value_NN1 than_CSN if_CS received_VVN e.g._REX as_II a_AT1 gift_NN1 or_CC from_II gambling_NN1 ._. 
</s>
<s>
Furthermore_RR ,_, the_AT final_JJ price_NN1 on_II a_AT1 product_NN1 is_VBZ also_RR different_JJ depending_II21 on_II22 the_AT paying_JJ method_NN1 e.g._REX credit_NN1 card_NN1 versus_II cash_NN1 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, prices_NN2 are_VBR also_RR different_JJ depending_II21 on_II22 where_RRQ you_PPY buy_VV0 the_AT product_NN1 ._. 
</s>
<s>
A_AT1 product_NN1 bought_VVN from_II internet_NN1 might_VM have_VHI extra_JJ shipping_NN1 costs_NN2 or_CC a_AT1 product_NN1 bought_VVN in_II a_AT1 convenient_JJ store_NN1 most_RGT probably_RR have_VH0 a_AT1 higher_JJR price_NN1 for_IF the_AT same_DA product_NN1 compared_VVN to_II a_AT1 big_JJ supermarket_NN1 ._. 
</s>
<s>
However_RR ,_, in_BCL21 order_BCL22 to_TO get_VVI the_AT cheapest_JJT price_NN1 for_IF a_AT1 product_NN1 you_PPY might_VM have_VHI to_TO spend_VVI money_NN1 for_IF travelling_VVG costs_NN2 ,_, thus_RR increasing_VVG the_AT final_JJ price_NN1 ._. 
</s>
<s>
In_II this_DD1 context_NN1 the_AT amount_NN1 of_IO money_NN1 you_PPY pay_VV0 for_IF internet_NN1 connection_NN1 is_VBZ more_RGR relevant_JJ (_( J._NP1 Paul_NP1 Peter_NP1 ,_, Jerry_NP1 C._NP1 Olson_NP1 ,_, 2008_MC )_) ._. 
</s>
<s>
2.1.2_MC Time_NNT1 When_CS referring_VVG to_II this_DD1 factor_NN1 ,_, time_NNT1 spent_VVN travelling_NN1 in_BCL21 order_BCL22 to_TO buy_VVI a_AT1 product_NN1 is_VBZ usually_RR mentioned_VVN ._. 
</s>
<s>
However_RR ,_, mobile_JJ phone_NN1 applications_NN2 are_VBR bought_VVN online_RR and_CC can_VM thus_RR be_VBI bought_VVN in_II a_AT1 matter_NN1 of_IO minutes_NNT2 ,_, granted_VVD that_CST an_AT1 internet_NN1 connection_NN1 is_VBZ available_JJ for_IF the_AT consumer_NN1 ._. 
</s>
<s>
This_DD1 factor_NN1 should_VM still_RR not_XX be_VBI completely_RR ruled_VVN out_RP ,_, considering_CS21 that_CS22 the_AT time_NNT1 spent_VVN reading_VVG reviews_NN2 and_CC looking_VVG for_IF other_JJ options_NN2 within_II the_AT same_DA product_NN1 category_NN1 is_VBZ also_RR of_IO importance_NN1 when_CS talking_VVG about_II time_NNT1 in_II this_DD1 context_NN1 ._. 
</s>
<s>
Furthermore_RR ,_, there_EX are_VBR many_DA2 different_JJ websites_NN2 serving_VVG as_CSA selling_VVG platforms_NN2 for_IF mobile_JJ phone_NN1 applications_NN2 which_DDQ means_VVZ that_CST even_CS21 though_CS22 these_DD2 sites_NN2 can_VM be_VBI accessed_VVN instantly_RR ,_, individuals_NN2 might_VM choose_VVI to_TO spend_VVI time_NNT1 looking_VVG for_IF the_AT cheapest_JJT option_NN1 ._. 
</s>
<s>
(_( J._NP1 Paul_NP1 Peter_NP1 ,_, Jerry_NP1 C._NP1 Olson_NP1 ,_, 2008_MC )_) ._. 
</s>
<s>
2.1.3_MC Cognitive_JJ Activity_NN1 Cognitive_JJ activity_NN1 refers_VVZ to_II the_AT thinking_NN1 and_CC deciding_VVG in_II regard_NN1 of_IO what_DDQ to_TO buy_VVI ._. 
</s>
<s>
If_CS there_EX are_VBR too_RG many_DA2 options_NN2 for_IF the_AT consumer_NN1 this_DD1 might_VM cause_VVI a_AT1 negative_JJ effect_NN1 making_VVG the_AT consumer_NN1 stressed_VVD ._. 
</s>
<s>
For_REX21 example_REX22 an_AT1 inexperienced_JJ smartphone_NN1 user_NN1 might_VM find_VVI it_PPH1 very_RG stressful_JJ to_II being_VBG forced_VVN to_TO use_VVI a_AT1 credit_NN1 card_NN1 in_BCL21 order_BCL22 to_TO complete_VVI the_AT payment_NN1 for_IF an_AT1 application_NN1 ._. 
</s>
<s>
The_AT decision_NN1 making_VVG cost_NN1 is_VBZ however_RR easy_JJ for_IF the_AT costumer_NN1 to_TO reduce_VVI or_CC eliminate_VVI ._. 
</s>
<s>
To_TO have_VHI rules_NN2 when_CS buying_VVG products_NN2 is_VBZ one_MC1 way_NN1 of_IO reducing_VVG or_CC eliminating_VVG the_AT decision_NN1 making_VVG cost_NN1 ._. 
</s>
<s>
Examplesof_VV0 rulesarefor_NN1 example_NN1 to_TO always_RR buy_VVI the_AT cheapest_JJT option_NN1 or_CC to_TO buy_VVI the_AT brand_NN1 your_APPGE father_NN1 use_NN1 to_TO buy_VVI ._. 
</s>
<s>
This_DD1 reduces_VVZ the_AT consumers_NN2 effort_NN1 in_II deciding_VVG and_CC thus_RR reducing_VVG both_RR stress_VV0 and_CC time_NNT1 ._. 
</s>
<s>
However_RR ,_, some_DD consumers_NN2 seek_VV0 cognitive_JJ involvement_NN1 in_II deciding_VVG on_II which_DDQ product_NN1 to_TO buy_VVI ._. 
</s>
<s>
These_DD2 individuals_NN2 might_VM be_VBI experts_NN2 within_II a_AT1 certain_JJ area_NN1 and_CC enjoys_VVZ comparing_VVG every_AT1 option_NN1 (_( J._NP1 Paul_NP1 Peter_NP1 ,_, Jerry_NP1 C._NP1 Olson_NP1 ,_, 2008_MC )_) ._. 
</s>
<s>
2.1.4_MC Behavior_NP1 Effort_NN1 A_ZZ1 synonym_NN1 for_IF behavior_NN1 effort_NN1 in_II this_DD1 context_NN1 is_VBZ physical_JJ effort_NN1 ._. 
</s>
<s>
In_RR21 short_RR22 ,_, this_DD1 means_VVZ the_AT actual_JJ effort_NN1 in_II walking_VVG around_RP a_AT1 shop_NN1 to_TO pick_VVI the_AT product_NN1 of_IO the_AT shelf_NN1 or_CC putting_VVG the_AT bed_NN1 chair_VV0 you_PPY bought_VVD from_II IKEA_NN1 together_RL ._. 
</s>
<s>
However_RR ,_, again_RT ,_, since_CS mobile_JJ phone_NN1 applications_NN2 are_VBR bought_VVN and_CC downloaded_VVN via_II your_APPGE phone_NN1 this_DD1 factor_NN1 is_VBZ not_XX a_AT1 crucial_JJ matter_NN1 for_IF the_AT consumer_NN1 when_CS they_PPHS2 want_VV0 to_TO buy_VVI a_AT1 mobile_JJ phone_NN1 application_NN1 ._. 
</s>
<s>
Still_RR ,_, mobile_JJ phone_NN1 applications_NN2 are_VBR special_JJ as_II a_AT1 product_NN1 in_II the_AT way_NN1 that_CST if_CS you_PPY have_VH0 the_AT expertise_NN1 to_TO develop_VVI applications_NN2 the_AT cost_NN1 to_TO produce_VVI one_PN1 is_VBZ very_RG low_JJ ._. 
</s>
<s>
This_DD1 makes_VVZ certain_JJ people_NN able_JK to_TO produce_VVI some_DD of_IO the_AT applications_NN2 themselves_PPX2 thus_RR reducing_VVG the_AT money_NN1 cost_NN1 to_TO zero_VVI (_( J._NP1 Paul_NP1 Peter_NP1 ,_, Jerry_NP1 C._NP1 Olson_NP1 ,_, 2008_MC )_) ._. 
</s>
<s>
2.1.5Value_FO In_II contrast_NN1 to_II the_AT costs_NN2 ,_, value_NN1 is_VBZ what_DDQ you_PPY gain_VV0 from_II buying_VVG a_AT1 product_NN1 ._. 
</s>
<s>
A_AT1 consumer_NN1 views_VVZ a_AT1 buy_NN1 as_CSA good_JJ if_CS the_AT consumer_NN1 perceives_VVZ that_CST they_PPHS2 gained_VVD more_DAR value_NN1 than_CSN what_DDQ they_PPHS2 spent_VVD on_II the_AT product_NN1 ._. 
</s>
<s>
Every_AT1 factor_NN1 of_IO the_AT consumer_NN1 costs_VVZ that_CST we_PPIS2 earlier_RRR discussed_VVN are_VBR not_XX however_RR always_RR being_VBG taken_VVN into_II account_NN1 ,_, when_CS a_AT1 consumer_NN1 decides_VVZ to_TO buy_VVI a_AT1 product_NN1 (_( J._NP1 Paul_NP1 Peter_NP1 ,_, Jerry_NP1 C._NP1 Olson_NP1 ,_, 2008_MC )_) ._. 
</s>
<s>
There_EX are_VBR many_DA2 free_JJ mobile_JJ phone_NN1 applications_NN2 available_JJ ._. 
</s>
<s>
These_DD2 applications_NN2 might_VM however_RR have_VHI a_AT1 negative_JJ value_NN1 for_IF the_AT customer_NN1 ._. 
</s>
<s>
Many_DA2 applications_NN2 are_VBR only_RR used_VVN once_RR ,_, and_CC left_VVN on_II the_AT mobile_JJ phone_NN1 only_RR taking_VVG up_RP space_NN1 after_II being_VBG downloaded_VVN ._. 
</s>
<s>
This_DD1 might_VM lead_VVI to_II slowing_VVG down_RP your_APPGE mobile_JJ phone_NN1 as_II31 well_II32 as_II33 making_VVG it_PPH1 less_RRR organized_VVN ._. 
</s>
<s>
3_MC ._. 
</s>
<s>
Methodology_NN1 In_II this_DD1 part_NN1 I_PPIS1 will_VM explain_VVI my_APPGE choice_NN1 of_IO informants_NN2 as_II31 well_II32 as_II33 how_RRQ I_PPIS1 gathered_VVD the_AT data_NN ._. 
</s>
<s>
3.1_MC Choice_NN1 of_IO Informants_NN2 Since_CS the_AT aim_NN1 of_IO this_DD1 study_NN1 was_VBDZ to_TO interview_VVI young_JJ adults_NN2 in_II Finland_NP1 regarding_II how_RRQ price_NN1 affects_VVZ when_RRQ they_PPHS2 download_VV0 mobile_JJ phone_NN1 applications_NN2 ,_, it_PPH1 was_VBDZ natural_JJ to_TO look_VVI for_IF participants_NN2 among_II my_APPGE friends_NN2 ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO fulfill_VVI the_AT aim_NN1 I_PPIS1 aimed_VVD to_TO interview_VVI 5-10_MCMC informants_NN2 ._. 
</s>
<s>
These_DD2 informants_NN2 were_VBDR found_VVN among_II my_APPGE friends_NN2 and_CC were_VBDR all_DB within_II the_AT target_NN1 age_NN1 ,_, 18-24_MCMC year_NNT1 olds_NN2 ._. 
</s>
<s>
The_AT interviews_NN2 were_VBDR conducted_VVN face-to-face_JJ ,_, Skype_NP1 and_CC Facebook_NP1 ._. 
</s>
<s>
This_DD1 method_NN1 is_VBZ called_VVN convenience_NN1 sampling_NN1 and_CC is_VBZ a_AT1 type_NN1 of_IO nonprobability_NN1 sampling_NN1 ._. 
</s>
<s>
This_DD1 method_NN1 is_VBZ best_RRT used_VVN when_CS the_AT amount_NN1 of_IO informants_NN2 are_VBR expected_VVN to_TO be_VBI low_JJ and_CC when_CS you_PPY try_VV0 to_TO target_VVI a_AT1 certain_JJ target_NN1 group_NN1 (_( Kauppinen-Risnen_NN1 ,_, 2011_MC )_) ._. 
</s>
<s>
3.2_MC Choice_NN1 of_IO Method_NN1 Previous_JJ research_NN1 is_VBZ limited_VVN in_II this_DD1 area_NN1 which_DDQ is_VBZ why_RRQ qualitative_JJ types_NN2 of_IO interviews_NN2 were_VBDR conducted_VVN and_CC also_RR why_RRQ the_AT amount_NN1 of_IO informants_NN2 was_VBDZ relatively_RR low_JJ ._. 
</s>
<s>
This_DD1 is_VBZ recommended_VVN during_II such_DA data_NN means_VVZ that_CST the_AT data_NN consists_VVZ of_IO words_NN2 or_CC sentences_NN2 (_( Kauppinen-Risnen_NN1 ,_, 2011_MC )_) ._. 
</s>
<s>
An_AT1 interview_NN1 guide_NN1 was_VBDZ used_VVN in_BCL21 order_BCL22 for_IF the_AT interviews_NN2 to_TO discuss_VVI the_AT same_DA topics_NN2 and_CC thus_RR not_XX go_VV0 off-topic._NNU 3.3_MC Conducting_NN1 of_IO the_AT data_NN To_TO be_VBI completed_VVN 4_MC ._. 
</s>
<s>
Results_NN2 To_TO be_VBI completed_VVN 5_MC ._. 
</s>
<s>
Discussion_NN1 To_TO be_VBI completed_VVN 
</s>
