<s>
I_ZZ1 r_ZZ1 rational_JJ ?_? 
</s>
<s>
The_AT Hidden_JJ Forces_NN2 that_CST Shape_NN1 Decisions_NN2 1_MC1 ._. 
</s>
<s>
Introduction_NN1 The_AT field_NN1 of_IO behavioural_JJ economics_NN1 is_VBZ nothing_PN1 new_JJ in_II fact_NN1 its_APPGE roots_NN2 can_VM be_VBI drawn_VVN from_II the_AT classical_JJ era_NN1 and_CC Adam_NP1 Smith_NP1 's_GE work_NN1 The_AT Theory_NN1 of_IO Moral_JJ Sentiments_NN2 ._. 
</s>
<s>
However_RR ,_, since_CS the_AT concept_NN1 of_IO Homo_NP1 Economicus_NP1 a_AT1 rational_JJ being_VBG emerged_VVN in_II the_AT late_JJ 19th_MD century_NNT1 ,_, it_PPH1 has_VHZ predominated_VVN the_AT field_NN1 and_CC left_JJ soft_JJ values_NN2 more_RGR or_CC less_RGR untouched_JJ ._. 
</s>
<s>
&lsqb;_( bridge_NN1 to_II paragraph_NN1 &rsqb;_) With_IW the_AT advent_NN1 of_IO emerging_JJ technology_NN1 capable_JJ of_IO better_RRR studying_VVG the_AT human_JJ brain_NN1 ,_, new_JJ studies_NN2 in_II this_DD1 field_NN1 are_VBR being_VBG carried_VVN out_RP and_CC interest_NN1 in_II the_AT topic_NN1 has_VHZ subsequently_RR grown_VVN rapidly_RR ._. 
</s>
<s>
Numerous_JJ studies_NN2 into_II the_AT breeches_NN2 of_IO the_AT human_JJ mind_NN1 have_VH0 of_RR21 course_RR22 been_VBN performed_VVN during_II the_AT years_NNT2 ,_, but_CCB the_AT brunt_NN1 of_IO these_DD2 have_VH0 been_VBN firmly_RR anchored_VVN in_II the_AT field_NN1 of_IO psychology_NN1 ._. 
</s>
<s>
This_DD1 field_NN1 ,_, by_II some_DD not_XX considered_VVN an_AT1 objective_JJ science_NN1 <citation>_NULL due_II21 to_II22 heavy_JJ reliance_NN1 on_II surveys_NN2 and_CC questionnaires_NN2 is_VBZ fundamentally_RR different_JJ from_II economics_NN1 ,_, where_CS the_AT very_RG basic_JJ idea_NN1 of_IO rationality_NN1 provides_VVZ the_AT foundation_NN1 for_IF economic_JJ theories_NN2 ,_, predictions_NN2 ,_, and_CC recommendations_NN2 (_( Berglund_NP1 ,_, 1998_MC )_) ._. 
</s>
<s>
After_CS the_AT publication_NN1 of_IO his_APPGE 2008_MC book_NN1 Predictably_RR Irrational_JJ ,_, Dan_NP1 Ariely_NP1 has_VHZ brought_VVN behavioural_JJ economics_NN1 into_II the_AT public_NN1 eye_NN1 and_CC raised_VVD the_AT awareness_NN1 of_IO the_AT lay_JJ audience_NN1 ._. 
</s>
<s>
In_II early_RR 2008_MC ,_, the_AT former_DA Federal_JJ Reserve_JJ chairman_NN1 Alan_NP1 Greenspan_NP1 told_VVD Congress_NN1 that_CST he_PPHS1 was_VBDZ shocked_VVN that_CST the_AT markets_NN2 did_VDD not_XX work_VVI as_RG anticipated_JJ ,_, or_CC automatically_RR self-correct_JJ as_CSA they_PPHS2 were_VBDR supposed_JJ to_TO ._. 
</s>
<s>
Ariely_NP1 (_( 2008_MC )_) states_VVZ that_CST the_AT first_MD step_NN1 toward_II recovery_NN1 is_VBZ admitting_VVG you_PPY have_VH0 a_AT1 problem_NN1 ,_, and_CC ponders_VVZ whether_CSW relying_VVG on_II standard_JJ economic_JJ theory_NN1 alone_RR might_VM ,_, in_II fact_NN1 ,_, be_VBI dangerous_JJ ._. 
</s>
<s>
A_AT1 broader_JJR perspective_NN1 than_CSN just_RR the_AT neo-classical_JJ Keynesian_JJ view_NN1 is_VBZ required_VVN to_TO fully_RR understand_VVI economic_JJ decisions_NN2 ,_, and_CC this_DD1 has_VHZ prompted_VVN me_PPIO1 to_TO perform_VVI my_APPGE own_DA research_NN1 in_II behavioural_JJ economics_NN1 ._. 
</s>
<s>
This_DD1 paper_NN1 will_VM try_VVI to_TO replicate_VVI Ariely_NP1 's_GE experiments_NN2 regarding_II relativity_NN1 ,_, the_AT way_NN1 zero_NN1 skews_VVZ our_APPGE thinking_NN1 and_CC why_RRQ some_DD people_NN are_VBR ready_JJ to_TO pay_VVI a_AT1 higher_JJR amount_NN1 for_IF the_AT same_DA service_NN1 ._. 
</s>
<s>
An_AT1 additional_JJ point_NN1 of_IO view_NN1 will_VM come_VVI in_II comparing_VVG the_AT results_NN2 of_IO an_AT1 American_JJ versus_II a_AT1 European_JJ university_NN1 ._. 
</s>
<s>
The_AT paper_NN1 is_VBZ structured_VVN as_CSA follows_VVZ ._. 
</s>
<s>
After_CS a_AT1 description_NN1 of_IO the_AT theoretical_JJ framework_NN1 ,_, I_PPIS1 will_VM present_VVI the_AT methodology_NN1 used_VMK to_TO perform_VVI the_AT study_NN1 ._. 
</s>
<s>
The_AT outlines_NN2 of_IO the_AT experiments_NN2 will_VM be_VBI described_VVN and_CC the_AT tools_NN2 and_CC methods_NN2 used_VMK to_TO analyse_VVI the_AT data_NN will_VM be_VBI described_VVN ._. 
</s>
<s>
The_AT main_JJ part_NN1 of_IO the_AT paper_NN1 will_VM be_VBI the_AT analysis_NN1 of_IO the_AT results_NN2 and_CC following_II that_DD1 ,_, a_AT1 discussion_NN1 regarding_II the_AT findings_NN2 will_VM ensue_VVI ._. 
</s>
<s>
2_MC ._. 
</s>
<s>
Theoretical_JJ Framework_NN1 In_II this_DD1 chapter_NN1 I_PPIS1 will_VM describe_VVI the_AT theoretical_JJ framework_NN1 used_VVN in_II the_AT project_NN1 ,_, as_II31 well_II32 as_II33 delve_VV0 deeper_RRR into_II the_AT underlying_JJ causality_NN1 of_IO the_AT subject_NN1 ._. 
</s>
<s>
Introduction_NN1 to_II the_AT field_NN1 of_IO behavioural_JJ economics_NN1 ,_, history_NN1 of_IO the_AT field_NN1 ._. 
</s>
<s>
Explore_VV0 leading_JJ theories_NN2 and_CC references_NN2 ._. 
</s>
<s>
Select_VV0 a_AT1 few_DA2 key_JJ components_NN2 and_CC analyse_VV0 these_DD2 further_JJR ._. 
</s>
