<s>
An_AT1 Extended_JJ TAM_NP1 Model_NN1 for_IF the_AT Adoption_NN1 of_IO E-_JJ Banking_NN1 in_II an_AT1 Emerging_JJ Economy_NN1 Introduction_NN1 Information_NN1 technology_NN1 has_VHZ changed_VVN peoples_NN2 life_NN1 greatly_RR ._. 
</s>
<s>
World_NN1 Wide_JJ Web_NN1 has_VHZ been_VBN introduced_VVN in_II the_AT 90s_MC2 last_MD century_NNT1 ,_, the_AT number_NN1 of_IO internet_NN1 users_NN2 has_VHZ been_VBN skyrocketing_VVG ._. 
</s>
<s>
Apart_II21 from_II22 the_AT traditional_JJ internet_NN1 usage_NN1 like_II website_NN1 surfing_VVG ,_, or_CC online_RR chatting_VVG ,_, more_RRR and_CC more_DAR people_NN began_VVD to_TO handle_VVI their_APPGE personal_JJ life_NN1 online_RR ,_, too._NNU (_( ref_NN1 )_) The_AT introduction_NN1 of_IO E-banking_NN1 is_VBZ one_MC1 example_NN1 of_IO internet_NN1 usage_NN1 ._. 
</s>
<s>
E-banking_NN1 is_VBZ a_AT1 way_NN1 of_IO distributing_VVG financial_JJ services_NN2 or_CC products_NN2 using_VVG an_AT1 electronic_JJ channel_NN1 ._. 
</s>
<s>
(_( E-banking_NN1 ,_, 2010_MC )_) Unlike_II the_AT traditional_JJ face-to-face_JJ banking_NN1 services_NN2 ,_, E-banking_NN1 provides_VVZ real-time_JJ services_NN2 to_II customer_NN1 ._. 
</s>
<s>
Bank_NN1 clients_NN2 can_VM get_VVI access_NN1 to_II their_APPGE bank_NN1 accounts_NN2 without_IW time_NNT1 or_CC physical_JJ limitation_NN1 ._. 
</s>
<s>
Narrowly_RR speaking_VVG ,_, e-banking_NN1 can_VM be_VBI only_RR limited_VVN to_II the_AT on-line_JJ website_NN1 services_NN2 provided_VVN by_II banks_NN2 ;_; however_RR ,_, in_II fact_NN1 ,_, ATM_NN1 (_( automated_JJ teller_NN1 machine_NN1 )_) ,_, phone_NN1 banking_NN1 etc_RA ,_, can_VM be_VBI also_RR regarded_VVN as_II parts_NN2 of_IO e-banking_NN1 ._. 
</s>
<s>
(_( E-banking_NN1 ,_, 2010_MC )_) E-banking_JJ services_NN2 can_VM also_RR be_VBI divided_VVN in_RP to_II two_MC categories_NN2 according_II21 to_II22 the_AT characteristics_NN2 of_IO customers_NN2 :_: private_JJ and_CC corporate_JJ users_NN2 ._. 
</s>
<s>
Based_VVN on_II this_DD1 separation_NN1 ,_, the_AT financial_JJ services_NN2 are_VBR quite_RG different_JJ ,_, corporate_JJ customers_NN2 may_VM have_VHI more_DAR demand_NN1 for_IF secure_JJ transaction_NN1 than_CSN private_JJ ones_NN2 ,_, due_II21 to_II22 the_AT large_JJ amount_NN1 of_IO each_DD1 transaction_NN1 ._. 
</s>
<s>
Though_CS corporate_JJ customers_NN2 are_VBR important_JJ to_II banks_NN2 ,_, the_AT author_NN1 will_VM only_RR focus_VVI on_II the_AT attitude_NN1 of_IO private_JJ users_NN2 (_( human-being_JJ )_) towards_II the_AT adoption_NN1 of_IO E-banking_NN1 in_II this_DD1 paper_NN1 ._. 
</s>
<s>
Compared_VVN to_II the_AT usual_JJ financial_JJ services_NN2 ,_, it_PPH1 has_VHZ been_VBN argued_VVN that_CST though_CS the_AT e-banking_NN1 is_VBZ aiming_VVG to_TO achieve_VVI cost_NN1 efficiency_NN1 ,_, from_II accounting_VVG point_NN1 of_IO view_NN1 ,_, its_APPGE obvious_JJ that_CST direct_JJ material_NN1 and_CC labor_NN1 cost_NN1 of_IO banks_NN2 will_VM have_VHI been_VBN declining_VVG as_II the_AT adoption_NN1 of_IO E-banking_NN1 ,_, for_REX21 instance_REX22 ,_, decreasing_JJ consumption_NN1 of_IO papers_NN2 and_CC number_NN1 of_IO employee_NN1 ._. 
</s>
<s>
However_RR ,_, evidences_NN2 show_VV0 that_DD1 E-banking_NN1 in_II the_AT world_NN1 has_VHZ nt_XX performed_VVN as_CSA expected_VVN due_II21 to_II22 the_AT heavy_JJ burden_NN1 of_IO overhead_JJ cost_NN1 ._. 
</s>
<s>
(_( Delgado_NP1 ,_, Hernando_NP1 and_CC Nieto_NP1 ,_, 2007_MC )_) Its_APPGE clear_JJ that_CST the_AT maintenance_NN1 and_CC innovation_NN1 of_IO E-banking_JJ systems_NN2 cost_VV0 quite_RG much_DA1 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, the_AT threats_NN2 or_CC shortcomings_NN2 of_IO E-banking_NN1 have_VH0 also_RR been_VBN argued_VVN from_II banks_NN2 perspective_NN1 ,_, that_REX21 is_REX22 ,_, the_AT loyalty_NN1 of_IO their_APPGE customers_NN2 would_VM not_XX be_VBI as_RG stable_JJ as_CSA before_RT after_II the_AT adoption_NN1 of_IO e-banking_NN1 ._. 
</s>
<s>
(_( Durkin_NP1 ,_, ODonnell_NP1 ,_, Mullholland_NP1 ,_, Crowe_NP1 ,_, 2007_MC )_) therefore_RR ,_, its_APPGE very_RG important_JJ for_IF all_DB banks_NN2 to_TO analyse_VVI customers_NN2 attitudes_NN2 towards_II E-banking_JJ adoption_NN1 ,_, to_TO avoid_VVI unnecessary_JJ overhead_JJ costs_NN2 ._. 
</s>
<s>
There_EX are_VBR plentiful_JJ of_IO models_NN2 with_II31 respect_II32 to_II33 the_AT research_NN1 of_IO IT_NN1 acceptance_NN1 ,_, each_DD1 of_IO which_DDQ contains_VVZ various_JJ determinants_NN2 ._. 
</s>
<s>
Many_DA2 researchers_NN2 have_VH0 great_JJ interests_NN2 in_II investigating_VVG the_AT factors_NN2 affecting_VVG the_AT adoption_NN1 and_CC diffusion_NN1 of_IO e-banking_NN1 from_II consumers_NN2 perspective_NN1 ._. 
</s>
<s>
(_( Venkatesh_NN1 and_CC Davis_NP1 ,_, 1996_MC ;_; Johnson_NP1 and_CC Marakas_NP2 ,_, 2000_MC ;_; Hong_NP1 ,_, 2001_MC ;_; Chau_NP1 ,_, 2001_MC ;_; Wang_NP1 ,_, 2003_MC ;_; Pikkarainen_NP1 ,_, 2004_MC )_) ._. 
</s>
<s>
Technology_NN1 acceptance_NN1 model_NN1 (_( TAM_NP1 )_) has_VHZ been_VBN generally_RR regarded_VVN as_II the_AT base_NN1 model_NN1 to_TO analyze_VVI customer_NN1 behaviors_NN2 to_II the_AT acceptance_NN1 of_IO computer_NN1 technology_NN1 ._. 
</s>
<s>
This_DD1 model_NN1 was_VBDZ initiated_VVN by_II Davis(1989)_FO and_CC has_VHZ been_VBN applied_VVN in_II many_DA2 fields_NN2 of_IO information_NN1 technology_NN1 ._. 
</s>
<s>
There_EX are_VBR two_MC main_JJ factors_NN2 which_DDQ influence_VV0 customers_NN2 attitudes_NN2 towards_II the_AT adoption_NN1 of_IO an_AT1 information_NN1 system_NN1 :_: perceived_JJ usefulness_NN1 and_CC perceived_JJ ease-of-use_NN1 which_DDQ relate_VV0 to_II the_AT quality_NN1 and_CC convenience_NN1 of_IO the_AT information_NN1 system_NN1 ._. 
</s>
<s>
(_( Davis_NP1 ,_, 1989_MC )_) Earlier_JJR studies_NN2 have_VH0 proved_VVN that_CST these_DD2 two_MC factors_NN2 are_VBR positively_RR related_VVN with_IW the_AT customers_NN2 adoption_NN1 of_IO E-banking_NN1 ._. 
</s>
<s>
(_( Venkatesh_NN1 and_CC Davis_NP1 ,_, 1996_MC ;_; Johnson_NP1 and_CC Marakas_NP2 ,_, 2000_MC ;_; Hong_NP1 ,_, 2001_MC ;_; Chau_NP1 ,_, 2001_MC ;_; Wang_NP1 ,_, 2003_MC ;_; Pikkarainenet_NP1 ,_, 2004_MC )_) ._. 
</s>
<s>
Though_CS the_AT investigations_NN2 done_VDN by_II many_DA2 researchers_NN2 empirically_RR identified_VVN the_AT creditability_NN1 of_IO TAM_NP1 ,_, However_RR ,_, most_DAT of_IO the_AT studies_NN2 have_VH0 been_VBN conducted_VVN in_II well-_JJ developed_JJ countries_NN2 ._. 
</s>
<s>
(_( ref_NN1 )_) The_AT question_NN1 remains_VVZ if_CS this_DD1 model_NN1 is_VBZ also_RR applicable_JJ in_II developing_JJ countries_NN2 ,_, or_CC if_CS more_RGR independent_JJ variables_NN2 should_VM be_VBI brought_VVN into_II this_DD1 model_NN1 to_TO get_VVI better_JJR predictive_JJ results_NN2 with_II31 respect_II32 to_II33 customers_NN2 attitude_NN1 towards_II E-banking_JJ adoption_NN1 ._. 
</s>
<s>
There_EX are_VBR some_DD research_NN1 which_DDQ have_VH0 been_VBN done_VDN in_II India_NP1 ,_, Jordan_NP1 ,_, Malaysia._NP1 (_( ref_NN1 )_) E-banking_NN1 can_VM be_VBI regarded_VVN as_II the_AT sum_NN1 of_IO very_RG diversified_JJ on-line_JJ banking_NN1 services_NN2 ,_, including_II the_AT on-line_JJ website_NN1 services_NN2 ,_, ATM_NN1 (_( automated_JJ teller_NN1 machine_NN1 )_) ,_, and_CC phone_NN1 banking_NN1 ._. 
</s>
<s>
(_( E-banking_NN1 ,_, 2010_MC )_) Additionally_RR ,_, a_AT1 new_JJ term_NN1 mobile_NN1 banking_NN1 has_VHZ emerged_VVN with_IW the_AT development_NN1 of_IO information_NN1 technology_NN1 ._. 
</s>
<s>
Mobile_JJ banking_NN1 has_VHZ the_AT similiar_NN1 fuctions_NN2 like_II other_JJ E-banking_JJ products_NN2 with_IW the_AT help_NN1 of_IO a_AT1 mobile_JJ phone_NN1 or_CC Personal_JJ Digital_JJ Assistant_NN1 (_( PDA_NP1 )_) through_II SMS_NP1 or_CC mobile_JJ internet_NN1 ._. 
</s>
<s>
In_II this_DD1 paper_NN1 ,_, E-banking_JJ means_NN PC_NN1 banking_NN1 and_CC mobile_JJ banking_NN1 ._. 
</s>
<s>
(_( Tiwari_NN2 and_CC Buse_NP1 ,_, 2007_MC )_) This_DD1 thesis_NN1 empirically_RR evaluates_VVZ the_AT applicability_NN1 of_IO a_AT1 modified_JJ TAM_NP1 model_NN1 in_II China_NP1 ._. 
</s>
<s>
This_DD1 extended_JJ model_NN1 will_VM be_VBI presented_VVN after_II the_AT literature_NN1 review_NN1 ._. 
</s>
<s>
The_AT data_NN will_VM be_VBI collected_VVN by_II a_AT1 survey_NN1 ,_, and_CC factor_NN1 analysis_NN1 and_CC correlation_NN1 analysis_NN1 will_VM be_VBI used_VVN to_TO investigate_VVI whether_CSW the_AT independent_JJ variables_NN2 have_VH0 significant_JJ relationships_NN2 with_IW the_AT dependent_JJ variable_NN1 ---_NN1 the_AT adoption_NN1 of_IO E-banking_NN1 ._. 
</s>
<s>
The_AT structure_NN1 of_IO the_AT paper_NN1 is_VBZ as_CSA follows_VVZ ._. 
</s>
<s>
The_AT first_MD section_NN1 will_VM introduce_VVI the_AT background_NN1 of_IO E-banking_NN1 and_CC research_NN1 questions_NN2 ;_; the_AT second_MD section_NN1 will_VM give_VVI an_AT1 general_JJ literature_NN1 review_NN1 with_IW the_AT summarization_NN1 and_CC comparison_NN1 of_IO previous_JJ research_NN1 ;_; the_AT next_MD section_NN1 will_VM present_VVI empirical_JJ framework_NN1 with_IW design_NN1 and_CC results_NN2 of_IO the_AT survey_NN1 ;_; the_AT last_MD section_NN1 will_VM be_VBI the_AT analysis_NN1 and_CC conclusion_NN1 ._. 
</s>
<s>
Theoretical_JJ Background_NN1 In_II this_DD1 part_NN1 ,_, the_AT author_NN1 will_VM briefly_RR describe_VVI TAM_NP1 ,_, and_CC extend_VVI TAM_NP1 ,_, and_CC UTAUT_NP1 ,_, by_II reviewing_VVG the_AT studies_NN2 which_DDQ have_VH0 been_VBN done_VDN from_II 1980s_MC2 till_II now_RT ._. 
</s>
<s>
A_AT1 current_JJ situation_NN1 of_IO internet_NN1 banking_NN1 in_II China_NP1 will_VM be_VBI also_RR presented_VVN ._. 
</s>
<s>
Factors_NN2 affecting_VVG the_AT adoption_NN1 of_IO e-banking_NN1 will_VM be_VBI identified_VVN ,_, and_CC there_EX will_VM be_VBI a_AT1 comparison_NN1 and_CC evaluation_NN1 of_IO these_DD2 research_NN1 findings_NN2 as_II31 well_II32 as_II33 their_APPGE generalizations_NN2 and_CC validities_NN2 ._. 
</s>
<s>
Several_DA2 hypotheses_NN2 will_VM be_VBI presented_VVN in_II the_AT end_NN1 of_IO this_DD1 part_NN1 ._. 
</s>
<s>
On_II e-banking_JJ adoption_NN1 :_: from_II banker_NN1 perception_NN1 to_II customer_NN1 reality_NN1 Mark_NP1 Durkin_NP1 ,_, Aodheen_NP1 ODonnell_NP1 ,_, Gwyneth_NP1 Mullholland_NP1 ,_, Joseph_NP1 Crowe_NP1 ,_, Journal_NN1 of_IO Strategic_JJ Marketing_NN1 15_MC 237-252_MCMC ,_, 2007_MC The_AT authors_NN2 intend_VV0 to_TO find_VVI the_AT factors_NN2 which_DDQ have_VH0 influence_NN1 on_II the_AT adoption_NN1 of_IO internet_NN1 banking_NN1 ,_, as_II31 well_II32 as_II33 evaluating_VVG the_AT perception_NN1 of_IO senior_JJ bank_NN1 managers_NN2 about_II which_DDQ the_AT predictor_NN1 factors_NN2 are_VBR with_II31 regard_II32 to_II33 the_AT adoption_NN1 of_IO internet_NN1 banking_NN1 ._. 
</s>
<s>
(_( Durkin_NP1 ,_, ODonnell_NP1 ,_, Mullholland_NP1 ,_, Crowe_NP1 ,_, 2007_MC )_) This_DD1 paper_NN1 examined_VVD the_AT characteristics_NN2 of_IO customer_NN1 behavior_NN1 in_II internet_NN1 banking_NN1 registration_NN1 by_II conducting_VVG a_AT1 quantitative_JJ analysis_NN1 both_RR from_II customers_NN2 perspective_NN1 and_CC managers_NN2 perspective_NN1 focusing_VVG on_II the_AT internet_NN1 bank_NN1 registration_NN1 by_II specifically_RR testing_VVG customer_NN1 communication_NN1 preferences_NN2 with_IW bank_NN1 focusing_VVG on_II the_AT internet_NN1 banking_NN1 registration_NN1 ._. 
</s>
<s>
(_( Durkin_NP1 ,_, ODonnell_NP1 ,_, Mullholland_NP1 ,_, Crowe_NP1 ,_, 2007_MC )_) The_AT authors_NN2 pointed_VVD out_RP the_AT importance_NN1 of_IO analyzing_VVG customers_NN2 adoption_NN1 behavior_NN1 for_IF e-banking_NN1 by_II identifying_VVG the_AT advantages_NN2 for_IF bank_NN1 to_TO implement_VVI e-banking_JJ service_NN1 ,_, and_CC its_APPGE persuasiveness_NN1 in_II current_JJ daily_JJ life_NN1 ._. 
</s>
<s>
In_II empirical_JJ part_NN1 ,_, first_MD ,_, the_AT authors_NN2 make_VV0 a_AT1 survey_NN1 about_II customer_NN1 satisfaction_NN1 about_II services_NN2 and_CC delivery_NN1 quality_NN1 relating_VVG to_II the_AT registration_NN1 of_IO internet_NN1 banking_NN1 ._. 
</s>
<s>
Then_RT ,_, the_AT estimation_NN1 of_IO senior_JJ manager_NN1 about_II factors_NN2 influencing_VVG customers_NN2 choice_NN1 of_IO registration_NN1 of_IO internet_NN1 bank_NN1 has_VHZ also_RR been_VBN identified_VVN ._. 
</s>
<s>
(_( Durkin_NP1 ,_, ODonnell_NP1 ,_, Mullholland_NP1 ,_, Crowe_NP1 ,_, 2007_MC )_) The_AT study_NN1 shows_VVZ that_CST there_EX is_VBZ a_AT1 managerial_JJ knowledge_NN1 gap_NN1 between_II managers_NN2 and_CC customers_NN2 ._. 
</s>
<s>
The_AT managers_NN2 failed_VVD to_TO identify_VVI two_MC factors_NN2 which_DDQ influence_VV0 the_AT choice_NN1 of_IO customer_NN1 to_II the_AT registration_NN1 of_IO internet_NN1 bank_NN1 ._. 
</s>
<s>
One_PN1 is_VBZ relationship_NN1 management_NN1 status_NN1 ,_, which_DDQ indicates_VVZ that_CST customers_NN2 who_PNQS are_VBR relationship_NN1 managed_VVN are_VBR more_RGR willing_JJ to_TO sign_VVI up_RP for_IF internet_NN1 bank_NN1 ._. 
</s>
<s>
The_AT other_JJ factor_NN1 is_VBZ that_CST the_AT managers_NN2 underestimate_VV0 the_AT willingness_NN1 of_IO customer_NN1 to_TO use_VVI new_JJ technology_NN1 ._. 
</s>
<s>
(_( Durkin_NP1 ,_, ODonnell_NP1 ,_, Mullholland_NP1 ,_, Crowe_NP1 ,_, 2007_MC )_) The_AT determinants_NN2 of_IO customer_NN1 interactions_NN2 with_IW internet-enabled_JJ e-banking_JJ services_NN2 (_( 2008_MC )_) Z.Liao_NP1 and_CC WK_NP1 Wong_NP1 ,_, Journal_NN1 of_IO the_AT Operational_JJ Research_NN1 Society_NN1 59_MC ,_, 1201-1210_MCMC The_AT purpose_NN1 of_IO this_DD1 study_NN1 is_VBZ to_TO illustrate_VVI the_AT determinants_NN2 of_IO the_AT adoption_NN1 and_CC acceptance_NN1 of_IO customers_NN2 use_NN1 of_IO internet_NN1 banking_NN1 ._. 
</s>
<s>
The_AT authors_NN2 point_VV0 that_CST its_APPGE vital_JJ for_IF bank_NN1 which_DDQ implement_VV0 on-line_JJ banking_NN1 systems_NN2 to_TO achieve_VVI the_AT actual_JJ market_NN1 penetration_NN1 and_CC make_VVI the_AT expected_JJ profit_NN1 ._. 
</s>
<s>
(_( Liao_NN1 ,_, Wong_NP1 ,_, 2008_MC )_) This_DD1 paper_NN1 mainly_RR used_JJ technology_NN1 acceptance_NN1 model_NN1 (_( TAM_NP1 )_) as_II a_AT1 base_NN1 to_TO illustrate_VVI customer_NN1 behavior_NN1 to_II computer_NN1 technology_NN1 ._. 
</s>
<s>
This_DD1 model_NN1 was_VBDZ initiated_VVN by_II Davis_NP1 and_CC has_VHZ been_VBN applied_VVN in_II a_AT1 quite_RG big_JJ field_NN1 of_IO information_NN1 technology_NN1 ._. 
</s>
<s>
Through_II time_NNT1 ,_, the_AT summarization_NN1 of_IO users_NN2 behaviors_NN2 has_VHZ been_VBN developed_VVN regarding_VVG to_II the_AT use_NN1 of_IO any_DD kind_NN1 of_IO information_NN1 system_NN1 ._. 
</s>
<s>
Based_VVN on_II this_DD1 original_JJ model_NN1 and_CC other_JJ research_NN1 findings_NN2 ,_, a_AT1 more_RGR modified_JJ model_NN1 has_VHZ been_VBN built_VVN up_RP ._. 
</s>
<s>
In_II this_DD1 new_JJ model_NN1 ,_, the_AT authors_NN2 add_VV0 more_DAR elements_NN2 such_DA security_NN1 ,_, responsiveness_NN1 and_CC convenience_NN1 ,_, with_II31 regard_II32 to_II33 the_AT special_JJ features_NN2 of_IO bank_NN1 service_NN1 industry_NN1 ._. 
</s>
<s>
Various_JJ hypotheses_NN2 have_VH0 been_VBN presented_VVN in_II this_DD1 paper_NN1 and_CC more_RGR specific_JJ questionnaires_NN2 with_IW responding_VVG variable_NN1 were_VBDR gathered_VVN ._. 
</s>
<s>
(_( Liao_NN1 ,_, Wong_NP1 ,_, 2008_MC )_) The_AT results_NN2 showed_VVD that_CST the_AT perceived_JJ usefulness_NN1 ,_, ease_NN1 of_IO use_NN1 ,_, security_NN1 ,_, responsiveness_NN1 and_CC convenience_NN1 have_VH0 significant_JJ relationship_NN1 with_IW customer_NN1 interaction_NN1 with_IW e-banking_NN1 ._. 
</s>
<s>
Specially_RR ,_, the_AT customer_NN1 would_VM rank_VVI security_NN1 most_RGT important_JJ part_NN1 regarding_VVG to_II the_AT decision_NN1 of_IO signing_VVG up_RP for_IF e-banking_NN1 ._. 
</s>
<s>
The_AT limitation_NN1 of_IO this_DD1 article_NN1 lied_VVD to_II the_AT asymmetric_JJ demographic_JJ distribution_NN1 of_IO respondents_NN2 ,_, which_DDQ mostly_RR are_VBR comprised_VVN of_IO young_JJ people_NN ._. 
</s>
<s>
The_AT authors_NN2 assume_VV0 that_CST there_EX might_VM be_VBI some_DD variations_NN2 of_IO answers_NN2 regarding_VVG to_II the_AT age_NN1 or_CC different_JJ experiences_NN2 ._. 
</s>
<s>
Therefore_RR ,_, the_AT authors_NN2 suggest_VV0 that_CST further_JJR researches_NN2 should_VM be_VBI done_VDN by_II different_JJ demographic_JJ data_NN or_CC under_RP in_II different_JJ social_JJ context_NN1 ,_, which_DDQ means_VVZ culture_NN1 probably_RR would_VM play_VVI some_DD part_NN1 in_II the_AT determining_VVG the_AT adoption_NN1 of_IO e-banking_NN1 It_PPH1 has_VHZ been_VBN suggested_VVN that_CST traditional_JJ bank_NN1 institutions_NN2 should_VM continuously_RR improve_VVI business_NN1 process_NN1 reengineering_VVG to_TO achieve_VVI market_NN1 penetrations_NN2 ._. 
</s>
<s>
(_( Liao_NN1 ,_, Wong_NP1 ,_, 2008_MC )_) An_AT1 Experimental_JJ Investigation_NN1 of_IO Online_JJ Banking_NN1 Adoption_NN1 in_II China_NP1 ,_, Guangying_NP1 Hua_NP1 (_( 2009_MC )_) Jounal_JJ of_IO Internet_NP1 Banking_NN1 and_CC Commerce_NN1 April_NPM1 ,_, vol.14_FO ,_, no.1_FO This_DD1 paper_NN1 researches_VVZ the_AT situation_NN1 of_IO online_JJ banking_NN1 acceptance_NN1 in_II China_NP1 in_II the_AT context_NN1 that_CST online-banking_JJ has_VHZ been_VBN delayed_VVN the_AT development_NN1 of_IO e-commerce_NN1 in_II China_NP1 ._. 
</s>
<s>
The_AT researcher_NN1 conducted_VVD an_AT1 experiment_NN1 to_TO analyze_VVI how_RRQ users_NN2 perceive_VV0 online_JJ banking_NN1 with_IW the_AT influence_NN1 of_IO the_AT perceived_JJ ease_NN1 of_IO use_NN1 of_IO website_NN1 and_CC the_AT privacy_NN1 policy_NN1 provided_VVN by_II the_AT online_JJ banking_NN1 website_NN1 ._. 
</s>
<s>
The_AT findings_NN2 of_IO this_DD1 paper_NN1 revealed_VVD that_CST users_NN2 adoption_NN1 of_IO online_JJ banking_NN1 is_VBZ significantly_RR affected_VVN by_II perceived_JJ ease_NN1 of_IO use_NN1 and_CC privacy_NN1 policy_NN1 ._. 
</s>
<s>
It_PPH1 also_RR has_VHZ been_VBN discovered_VVN about_II the_AT ranking_NN1 of_IO the_AT importance_NN1 of_IO perceived_JJ ease_NN1 of_IO use_NN1 ,_, privacy_NN1 and_CC security_NN1 ,_, the_AT latter_DA two_MC are_VBR more_RGR important_JJ ._. 
</s>
<s>
Moreover_RR ,_, security_NN1 is_VBZ the_AT most_RGT important_JJ factor_NN1 affecting_VVG users_NN2 adoption_NN1 ._. 
</s>
<s>
(_( Hua_NN1 ,_, 2009_MC )_) The_AT author_NN1 designed_VVD a_AT1 laboratory_NN1 experiment_NN1 in_II this_DD1 research_NN1 ._. 
</s>
<s>
Moreover_RR ,_, a_AT1 questionnaire_NN1 was_VBDZ developed_VVN for_IF this_DD1 purpose_NN1 ._. 
</s>
<s>
There_EX are_VBR several_DA2 limitations_NN2 in_II this_DD1 paper_NN1 ._. 
</s>
<s>
It_PPH1 had_VHD been_VBN claimed_VVN that_CST this_DD1 was_VBDZ an_AT1 experimental_JJ study_NN1 ;_; however_RR ,_, there_EX was_VBDZ no_AT real_JJ website_NN1 for_IF testing_VVG in_II this_DD1 experiment_NN1 ,_, only_JJ questionnaires_NN2 had_VHD been_VBN filled_VVN and_CC the_AT sample_NN1 was_VBDZ quite_RG limited_JJ :_: only_JJ students_NN2 were_VBDR involved_VVN ,_, which_DDQ may_VM cause_VVI great_JJ bias_NN1 on_II the_AT final_JJ results_NN2 ._. 
</s>
<s>
(_( Hua_NN1 ,_, 2009_MC )_) Factor_NN1 Underlying_JJ Attitude_NN1 Formation_NN1 towards_II Online_JJ Banking_NN1 in_II Finland_NP1 ,_, Heikki_NP1 Karjaluoto_NP1 ,_, Minna_NP1 Mattila_NP1 ,_, Tapio_NP1 Pento_NP1 ,_, International_JJ Jounal_JJ of_IO Bank_NN1 Marketing_NN1 261-272_MCMC (_( 2002_MC )_) The_AT purpose_NN1 of_IO this_DD1 article_NN1 is_VBZ to_TO find_VVI the_AT factors_NN2 which_DDQ have_VH0 impact_NN1 on_II the_AT attitude_NN1 and_CC behaviors_NN2 of_IO bank_NN1 customers_NN2 to_II internet_NN1 banking_NN1 and_CC differences_NN2 in_II demographics_NN2 and_CC perceptions_NN2 ._. 
</s>
<s>
The_AT article_NN1 is_VBZ based_VVN on_II the_AT theory_NN1 of_IO Theory_NN1 of_IO Reasoned_JJ Action_NN1 (_( TRA_NP1 )_) and_CC Technology_NN1 Acceptance_NN1 Model_NN1 (_( TAM_NP1 )_) ._. 
</s>
<s>
After_II reviewing_VVG the_AT previous_JJ articles_NN2 with_IW relevant_JJ topics_NN2 ,_, the_AT authors_NN2 summarized_VVD the_AT factors_NN2 which_DDQ influence_VV0 customers_NN2 attitude_NN1 with_IW regards_VVZ to_II internet_NN1 banking_NN1 ,_, the_AT factors_NN2 are_VBR as_CSA follows_VVZ :_: Consumer_NN1 demographics_NN2 and_CC personality_NN1 traits_NN2 ,_, prior_JJ experience_NN1 of_IO computers_NN2 and_CC technology_NN1 ,_, personal_JJ banking_NN1 experience_NN1 ,_, and_CC reference_NN1 group_NN1 influence_NN1 ._. 
</s>
<s>
The_AT authors_NN2 performed_VVD a_AT1 factor_NN1 analysis_NN1 to_TO classify_VVI the_AT factors_NN2 and_CC demographic_JJ features_NN2 of_IO the_AT respondents_NN2 ._. 
</s>
<s>
(_( Karjaluoto_NN1 ,_, Mattila_NP1 ,_, and_CC Pento_NP1 ,_, 2002_MC )_) The_AT results_NN2 show_VV0 that_CST the_AT attitudes_NN2 and_CC behaviors_NN2 of_IO the_AT customers_NN2 to_TO use_VVI internet_NN1 banking_NN1 are_VBR affected_VVN by_II prior_JJ experience_NN1 of_IO computers_NN2 and_CC technology_NN1 ,_, and_CC attitude_NN1 towards_II computers_NN2 ._. 
</s>
<s>
The_AT authors_NN2 pointed_VVD that_CST its_APPGE very_JJ import_NN1 for_IF banks_NN2 to_TO provide_VVI more_RGR comprehensive_JJ education_NN1 in_II using_VVG computer_NN1 ,_, because_CS the_AT more_RGR sufficient_JJ knowledge_NN1 a_AT1 customer_NN1 have_VH0 in_II computer_NN1 technology_NN1 ,_, the_AT more_RGR possible_JJ he_PPHS1 or_CC she_PPHS1 would_VM like_VVI to_TO use_VVI internet_NN1 banking_NN1 service_NN1 ._. 
</s>
<s>
(_( Karjaluoto_NN1 ,_, Mattila_NP1 ,_, and_CC Pento_NP1 ,_, 2002_MC )_) The_AT author_NN1 also_RR found_VVN that_CST customers_NN2 internet_NN1 banking_NN1 behaviors_NN2 have_VH0 been_VBN greatly_RR influenced_VVN by_II demographic_JJ factors_NN2 ,_, in_II these_DD2 factors_NN2 ,_, occupation_NN1 and_CC income_NN1 are_VBR quite_RG significant_JJ ._. 
</s>
<s>
The_AT authors_NN2 also_RR are_VBR aware_JJ that_CST the_AT culture_NN1 difference_NN1 may_VM have_VHI impacts_NN2 on_II the_AT results_NN2 ,_, since_CS this_DD1 research_NN1 was_VBDZ only_RR carried_VVN in_II Finland_NP1 ._. 
</s>
<s>
(_( Karjaluoto_NN1 ,_, Mattila_NP1 ,_, and_CC Pento_NP1 ,_, 2002_MC )_) Consumers_NN2 attitudes_NN2 towards_II online_JJ and_CC mobile_JJ banking_NN1 in_II China_NP1 Sylvie_NP1 Laforet_NP1 ,_, Xiaoyan_NP1 Li_NP1 International_JJ Jounal_JJ of_IO Bank_NN1 Marketing_NN1 Vol._NN1 23_MC No_AT 5_MC ,_, 2005_MC p362-380_MC ,_, 2005_MC The_AT authors_NN2 of_IO this_DD1 article_NN1 intended_VVD to_TO analyze_VVI current_JJ market_NN1 situation_NN1 for_IF internet_NN1 banking_NN1 in_II China_NP1 by_II testing_VVG customers_NN2 attitudes_NN2 ,_, and_CC behaviors_NN2 ,_, their_APPGE demographic_JJ information_NN1 and_CC classify_VV0 the_AT targeted_JJ group_NN1 of_IO consumers_NN2 of_IO internet_NN1 banking_NN1 ,_, were_VBDR also_RR included_VVN ._. 
</s>
<s>
Especially_RR ,_, the_AT authors_NN2 were_VBDR aware_JJ of_IO the_AT cultural_JJ impact_NN1 on_II the_AT decision_NN1 marking_NN1 of_IO customers_NN2 to_II internet_NN1 banking_NN1 ._. 
</s>
<s>
The_AT authors_NN2 review_VV0 the_AT previous_JJ researches_NN2 about_II customer_NN1 adoption_NN1 of_IO internet_NN1 banking_NN1 ,_, their_APPGE attitude_NN1 ,_, motives_NN2 ,_, and_CC culture_NN1 difference_NN1 ,_, Chinese_JJ culture_NN1 was_VBDZ the_AT focus_NN1 one_MC1 ._. 
</s>
<s>
The_AT authors_NN2 did_VDD nt_XX use_VVI specific_JJ logistic_JJ regression_NN1 or_CC other_JJ method_NN1 ,_, they_PPHS2 briefed_VVD with_IW comprehensive_JJ descriptive_JJ statistical_JJ graphs_NN2 and_CC table_NN1 ._. 
</s>
<s>
(_( Laforet_VV0 ,_, Li_NP1 ,_, 2005_MC )_) They_PPHS2 found_VVD the_AT demographic_JJ features_NN2 of_IO Chinese_JJ internet_NN1 banking_NN1 users_NN2 are_VBR quite_RG different_JJ from_II their_APPGE counterparts_NN2 in_II western_JJ countries_NN2 ._. 
</s>
<s>
For_REX21 instance_REX22 ,_, Chinese_JJ users_NN2 think_VV0 security_NN1 is_VBZ most_RGT important_JJ factor_NN1 in_II adopting_VVG internet_NN1 banking_NN1 service_NN1 ,_, on_II the_AT contrary_NN1 ,_, users_NN2 from_II western_JJ countries_NN2 would_VM be_VBI more_RRR emphasized_VVN on_II other_JJ issues_NN2 ._. 
</s>
<s>
(_( Laforet_VV0 ,_, Li_NP1 ,_, 2005_MC )_) They_PPHS2 also_RR discovered_VVD that_CST there_EX has_VHZ been_VBN only_RR a_AT1 small_JJ proportion_NN1 of_IO group_NN1 are_VBR currently_RR adopting_VVG internet_NN1 banking_NN1 ,_, because_CS ordinary_JJ people_NN are_VBR lack_NN1 of_IO the_AT knowledge_NN1 about_II this_DD1 service_NN1 ,_, which_DDQ also_RR can_VM be_VBI seen_VVN in_II demographic_JJ features_NN2 ,_, the_AT average_JJ education_NN1 level_NN1 in_II western_JJ countries_NN2 are_VBR relatively_RR higher_JJR ._. 
</s>
<s>
Therefore_RR ,_, banks_NN2 should_VM place_VVI more_DAR education_NN1 on_II the_AT adoption_NN1 of_IO internet_NN1 banking_NN1 and_CC also_RR banks_NN2 should_VM spend_VVI more_RRR on_II the_AT promotion_NN1 to_TO persuade_VVI customers_NN2 beliefs_NN2 on_II the_AT security_NN1 and_CC advantages_NN2 of_IO internet_NN1 banking_NN1 ._. 
</s>
<s>
(_( Laforet_VV0 ,_, Li_NP1 ,_, 2005_MC )_) Customers_NN2 perspective_NN1 on_II online_JJ banking_NN1 services_NN2 Maria_NP1 Marvi_NP1 George_NP1 Loannou_NP1 International_JJ Journal_NN1 of_IO Consumer_NN1 Studies_NN2 30_MC ,_, 6_MC ,_, November_NPM1 2006_MC ,_, pp_NNU2 552-560_MCMC The_AT purpose_NN1 of_IO this_DD1 article_NN1 is_VBZ to_TO adopt_VVI a_AT1 methodology_NN1 to_TO investigate_VVI the_AT factors_NN2 affecting_VVG customers_NN2 decision_NN1 of_IO choosing_VVG internet_NN1 banking_NN1 service_NN1 ._. 
</s>
<s>
The_AT authors_NN2 also_RR used_VVD TAM_NP1 model_NN1 as_CSA base_NN1 model_NN1 ,_, exacted_VVD the_AT factors_NN2 in_II this_DD1 model_NN1 ,_, and_CC built_VVD a_AT1 logistic_JJ regression_NN1 model_NN1 to_TO predict_VVI customers_NN2 attitude_NN1 towards_II internet_NN1 banking_NN1 ._. 
</s>
<s>
they_PPHS2 identified_VVD that_CST customers_NN2 age_NN1 ,_, perception_NN1 about_II the_AT difficulty_NN1 of_IO using_VVG internet_NN1 ,_, reluctance_NN1 to_II changing_VVG with_II31 respect_II32 to_II33 technology_NN1 development_NN1 ,_, and_CC lack_NN1 of_IO information_NN1 of_IO financial_JJ products_NN2 ,_, these_DD2 factors_NN2 perform_VV0 significantly_RR ,_, however_RR ,_, the_AT speed_NN1 of_IO response_NN1 and_CC cost_NN1 considerations_NN2 are_VBR not_XX the_AT significant_JJ ones_NN2 ._. 
</s>
<s>
(_( Marvi_NP1 ,_, Loannou_NP1 ,_, 2006_MC )_) Chong_VV0 ,_, A._NP1 Ooi_NP1 K._NP1 ,_, Lin_NP1 ,_, B._NP1 ,_, Tan_JJ B._NP1 (_( 2010_MC )_) Online_JJ banking_NN1 adoption_NN1 :_: an_AT1 empirical_JJ analysis_NN1 International_JJ journal_NN1 of_IO bank_NN1 marketing_NN1 ,_, Vol.28_FO ,_, No._NN1 4_MC ,_, pp.267-287_MC The_AT authors_NN2 intend_VV0 to_TO investigate_VVI the_AT customers_NN2 perception_NN1 about_II the_AT acceptance_NN1 of_IO online_JJ banking_NN1 in_II Vietnam_NP1 and_CC find_VV0 out_RP the_AT determinants_NN2 or_CC predictors_NN2 of_IO their_APPGE perceptions_NN2 ._. 
</s>
<s>
Empirical_JJ Framework_NN1 Research_NN1 Design_NN1 In_II this_DD1 part_NN1 ,_, a_AT1 survey_NN1 will_VM be_VBI conducted_VVN ._. 
</s>
<s>
The_AT population_NN1 will_VM be_VBI young_JJ university_NN1 students_NN2 in_II China_NP1 due_II21 to_II22 time_NNT1 limitation_NN1 and_CC research_NN1 convenience_NN1 ._. 
</s>
<s>
Questionnaires_NN2 by_II email_NN1 will_VM be_VBI sent_VVN to_II 50_MC students_NN2 of_IO university_NN1 of_IO China_NP1 ._. 
</s>
<s>
The_AT Findings_NN2 Descriptive_JJ statistics_NN Gender_NN1 ,_, educational_JJ level_NN1 ,_, age_NN1 and_CC other_JJ demographical_JJ items_NN2 will_VM be_VBI presented_VVN ._. 
</s>
<s>
A_AT1 normality_NN1 test_NN1 will_VM be_VBI conducted_VVN to_TO test_VVI the_AT basis_NN1 of_IO the_AT sample_NN1 data_NN ._. 
</s>
<s>
Factor_NN1 analysis_NN1 Conclusion_NN1 
</s>
