<s>
The_AT Development_NN1 of_IO Sina_NP1 Micro_NN1 Blog_NN1 Marketing_NN1 in_II China_NP1 Introduction_NN1 Twitter_NN1 is_VBZ a_AT1 website_NN1 started_VVN by_II Jack_NP1 Dorsey_NP1 on_II March_NPM1 21_MC ,_, 2006_MC ._. 
</s>
<s>
It_PPH1 serves_VVZ the_AT role_NN1 that_CST people_NN use_VV0 it_PPH1 as_RG online_RR social_JJ network_NN1 and_CC microblog_NN1 ._. 
</s>
<s>
After_CS the_AT golden_JJ days_NNT2 of_IO blog_NN1 ,_, Twitter_NN1 grasped_VVD the_AT characteristic_NN1 of_IO human_JJ beings_NN2 mind_VV0 :_: fragmentation_NN1 ._. 
</s>
<s>
Writing_VVG an_AT1 article_NN1 is_VBZ hard_RR but_CCB saying_VVG a_AT1 sentence_NN1 or_CC just_RR a_AT1 few_DA2 words_NN2 is_VBZ much_RR easier_JJR ,_, thus_RR Twitter_VV0 replaced_JJ blog_NN1 to_TO be_VBI the_AT most_RGT popular_JJ way_NN1 of_IO social_JJ networking_NN1 online_RR immediately_RR ._. 
</s>
<s>
Information_NN1 on_II Twitter_NN1 can_VM be_VBI spread_VVN a_RR21 lot_RR22 more_RGR quickly_RR ,_, so_RR if_CS one_MC1 thing_NN1 is_VBZ known_VVN by_II one_MC1 person_NN1 and_CC he_PPHS1 or_CC she_PPHS1 tweets_VVZ about_II it_PPH1 ,_, it_PPH1 is_VBZ known_VVN by_II the_AT world_NN1 ._. 
</s>
<s>
When_CS Osama_NP1 Bin_NN1 Laden_VVN was_VBDZ executed_VVN on_II May_NPM1 2_MC ,_, 2011_MC ,_, Twitter_VV0 users_NN2 first_MD got_VVN to_TO know_VVI it_PPH1 ._. 
</s>
<s>
Keith_NP1 Urbahn_NP1 ,_, chief_NN1 of_IO staff_NN to_II former_DA US_NP1 defence_NN1 secretary_NN1 Donald_NP1 Rumsfeld_NP1 wrote_VVD :_: So_RR I_PPIS1 'm_VBM told_VVN by_II a_AT1 reputable_JJ person_NN1 they_PPHS2 have_VH0 killed_VVN Osama_NP1 Bin_VV0 Laden._NP1 (_( BBC_NP1 News_NN1 ,_, Bin_VV0 Laden_JJ raid_NN1 was_VBDZ revealed_VVN on_II Twitter_NN1 )_) The_AT power_NN1 of_IO Twitter_NN1 has_VHZ been_VBN proved_VVN a_AT1 lot_NN1 of_IO times_NNT2 ,_, from_II Obamas_NP2 campaign_NN1 to_II Egypts_NP2 revolution_NN1 ._. 
</s>
<s>
This_DD1 power_NN1 is_VBZ not_XX only_RR used_VVN in_II political_JJ events_NN2 ,_, but_CCB also_RR in_II business_NN1 ._. 
</s>
<s>
Business_NN1 has_VHZ the_AT most_RGT sensitive_JJ feeling_NN1 that_CST can_VM always_RR find_VVI the_AT newest_JJT way_NN1 to_TO make_VVI profits_NN2 because_CS interest_NN1 is_VBZ the_AT strongest_JJT incentive_NN1 ._. 
</s>
<s>
Twitter_VV0 marketing_NN1 is_VBZ not_XX a_AT1 new_JJ thing_NN1 ._. 
</s>
<s>
Companies_NN2 sign_VV0 up_RP on_II Twitter_NN1 with_IW their_APPGE brand_NN1 names_NN2 and_CC post_NN1 news_NN1 about_II their_APPGE companies_NN2 ._. 
</s>
<s>
In_CS21 Case_CS22 and_CC Kings_NN2 paper_NN1 Twitter_NN1 Usage_NN1 in_II the_AT Fortune_NN1 50_MC :_: A_AT1 Marketing_NN1 Opportunity_NN1 ?_? ,_, they_PPHS2 investigated2009_FO Fortune_NN1 50_MC companies_NN2 and_CC found_VVD out_RP that_CST 54_MC percent_NNU of_IO the_AT firms_NN2 have_VH0 Twitter_NN1 accounts_NN2 and_CC 37_MC percent_NNU of_IO them_PPHO2 have_VH0 more_DAR than_CSN one_MC1 account_NN1 ._. 
</s>
<s>
Moreover_RR ,_, 85_MC percent_NNU of_IO the_AT companies_NN2 use_VV0 their_APPGE accounts_NN2 to_II post_NN1 news_NN1 ,_, which_DDQ indicates_VVZ that_CST nowadays_RT Twitter_VV0 marketing_NN1 is_VBZ quite_RG an_AT1 important_JJ part_NN1 of_IO modern_JJ marketing_NN1 ,_, partly_RR because_II21 of_II22 its_APPGE broad_JJ audience_NN1 ,_, quick_JJ spread_NN1 ,_, and_CC various_JJ forms_NN2 ._. 
</s>
<s>
Sysomos_NN2 conducted_VVD a_AT1 survey_NN1 in_II June_NPM1 2009_MC and_CC revealed_VVD that_CST 15_MC percent_NNU of_IO the_AT people_NN who_PNQS identify_VV0 themselves_PPX2 as_CSA marketers_NN2 follow_VV0 more_DAR than_CSN 2000_MC people_NN ,_, but_CCB only_RR 0.29_MC percent_NNU of_IO the_AT rest_NN1 Twitter_NN1 users_NN2 follow_VV0 more_DAR than_CSN 2000_MC people_NN ._. 
</s>
<s>
(_( Thomases_VVZ 65_MC )_) Marketers_NN2 regard_VV0 Twitter_NN1 as_II a_AT1 symbol_NN1 of_IO keeping_VVG up_RP with_IW the_AT times_NNT2 and_CC if_CS a_AT1 marketer_NN1 doesnot_NN1 use_NN1 Twitter_NN1 ,_, he_PPHS1 or_CC she_PPHS1 will_VM be_VBI considered_VVN out_II21 of_II22 game_NN1 ._. 
</s>
<s>
(_( Thomases_VVZ 66_MC )_) The_AT previousresearches_NN2 seldom_RR involve_VV0 the_AT comparison_NN1 of_IO Twitter_NN1 marketing_NN1 in_II Western_JJ world_NN1 and_CC in_II developing_JJ countries_NN2 ,_, specifically_RR China_NP1 ,_, mostly_RR because_CS there_EX is_VBZ no_AT access_NN1 to_II Twitter_NN1 in_II China_NP1 ._. 
</s>
<s>
People_NN in_II China_NP1 have_VH0 to_TO go_VVI across_II the_AT Chinese_JJ Great_JJ Firewall_NN1 to_TO enter_VVI Facebook_NP1 ,_, YouTube_NP1 ,_, Twitter_VV0 ,_, and_CC a_AT1 huge_JJ amount_NN1 of_IO other_JJ prohibited_JJ websites_NN2 ;_; besides_RR ,_, going_VVG across_II the_AT Wall_NN1 is_VBZ much_DA1 more_DAR than_CSN clicking_VVG a_AT1 few_DA2 times.The_NNU situation_NN1 contributes_VVZ to_II a_AT1 gap_NN1 between_II Chinese_JJ online_JJ social_JJ network_NN1 and_CC global_JJ online_JJ social_JJ network_NN1 ,_, which_DDQ leads_VVZ to_II the_AT ignorance_NN1 of_IO the_AT comparison_NN1 of_IO social_JJ network_NN1 marketing_NN1 academically_RR ._. 
</s>
<s>
After_II all_DB ,_, how_RRQ could_VM China_NP1 has_VHZ Twitter_NN1 marketing_NN1 when_CS Chinese_JJ people_NN can_VM not_XX sign_VVI up_RP on_II Twitter_NN1 ?_? 
</s>
<s>
However_RR ,_, not_XX allowing_VVG the_AT access_NN1 to_II Twitter_NN1 doesnot_NN1 mean_VV0 that_CST Chinese_JJ people_NN do_VD0 not_XX have_VHI their_APPGE own_DA micro_NN1 blog_NN1 ._. 
</s>
<s>
Sina_NN1 Micro_NN1 Blog_NN1 is_VBZ the_AT Chinese_JJ Twitter_NN1 ._. 
</s>
<s>
Many_DA2 famous_JJ people_NN like_II movie_NN1 stars_NN2 and_CC model_NN1 singers_NN2 used_VVD their_APPGE real_JJ name_NN1 to_TO sign_VVI up_RP and_CC post_NN1 about_II their_APPGE lives_NN2 at_RR21 first_RR22 and_CC it_PPH1 caused_VVD the_AT popularity_NN1 of_IO Sina_NP1 Micro_NN1 Blog_NN1 among_II ordinary_JJ people_NN ._. 
</s>
<s>
It_PPH1 is_VBZ started_VVN on_II August_NPM1 14_MC ,_, 2009_MC ,_, 3_MC years_NNT2 after_II Twitter_NN1 started_VVD ._. 
</s>
<s>
Now_RT Sina_NP1 Micro_NN1 Blog_NN1 has_VHZ become_VVN the_AT most_RGT popular_JJ microblog_NN1 website_NN1 in_II China_NP1 ,_, taking_VVG an_AT1 87_MC percent_NNU share_NN1 of_IO the_AT tweet_NN1 activities_NN2 ._. 
</s>
<s>
Having_VHG 300_MC million_NNO users_NN2 ,_, Sina_NP1 Micro_NN1 Blog_NN1 has_VHZ a_AT1 huge_JJ potential_NN1 of_IO marketing_NN1 and_CC Chinese_JJ business_NN1 along_II21 with_II22 foreign_JJ business_NN1 in_II China_NP1 have_VH0 noticed_VVN and_CC started_VVN to_TO explore_VVI the_AT potential_NN1 ._. 
</s>
<s>
(_( Wikipedia_NN1 ,_, Sina_NP1 Weibo_NP1 )_) The_AT late_JJ start_NN1 seems_VVZ to_TO mean_VVI late_JJ development_NN1 ,_, so_RR how_RRQ is_VBZ Sina_NP1 Micro_NN1 Blog_NN1 marketing_NN1 in_II China_NP1 exactly_RR ?_? 
</s>
<s>
We_PPIS2 have_VH0 organized_VVN the_AT rest_NN1 of_IO this_DD1 paper_NN1 by_II the_AT introduction_NN1 of_IO the_AT current_JJ methods_NN2 that_CST Sina_NP1 Micro_NN1 Blog_NN1 marketing_NN1 is_VBZ using_VVG ._. 
</s>
<s>
The_AT usage_NN1 shows_VVZ maturity_NN1 and_CC the_AT attitude_NN1 behind_II the_AT simple_JJ methods_NN2 shows_VVZ whether_CSW Sina_NP1 Micro_NN1 Blog_NN1 marketing_NN1 is_VBZ taken_VVN seriously_RR as_II a_AT1 means_NN of_IO marketing_NN1 in_II modern_JJ Chinese_JJ business_NN1 ._. 
</s>
<s>
The_AT philosophy_NN1 can_VM be_VBI indicated_VVN by_II the_AT marketing_NN1 methods_NN2 and_CC the_AT management_NN1 of_IO marketing_NN1 teams_NN2 ,_, so_CS it_PPH1 will_VM also_RR be_VBI discussed_VVN ._. 
</s>
<s>
Method_NN1 To_TO introduce_VVI the_AT current_JJ situation_NN1 of_IO Sina_NP1 Micro_NN1 Blog_NN1 marketing_NN1 ,_, a_AT1 number_NN1 of_IO exampleswill_NN1 be_VBI came_VVN up_RP with_IW ,_, and_CC the_AT analysis_NN1 of_IO the_AT examples_NN2 will_VM take_VVI a_AT1 large_JJ portion_NN1 of_IO the_AT text_NN1 ._. 
</s>
<s>
Sina_NN1 Micro_NN1 Blog_NN1 marketing_NN1 ,_, as_CSA a_AT1 rather_RG new_JJ way_NN1 of_IO online_JJ marketing_NN1 ,_, has_VHZ not_XX entered_VVN the_AT academic_JJ world_NN1 deeply_RR ,_, lacking_VVG serious_JJ and_CC deep_JJ research_NN1 ,_, so_RG specific_JJ data_NN is_VBZ difficult_JJ to_TO find_VVI ,_, especially_RR general_JJ data_NN about_II the_AT whole_JJ business_NN1 which_DDQ requires_VVZ great_JJ academic_JJ efforts_NN2 to_TO get_VVI ._. 
</s>
<s>
In_II this_DD1 situation_NN1 ,_, the_AT data_NN will_VM be_VBI first-hand_RR ,_, thus_RR there_EX will_VM not_XX be_VBI any_DD references_NN2 ,_, but_CCB it_PPH1 will_VM be_VBI clarified_VVN when_CS it_PPH1 happens.The_NNU first-hand_JJ data_NN is_VBZ always_RR obtained_VVN by_II basic_JJ methods_NN2 ._. 
</s>
<s>
We_PPIS2 follow_VV0 companies_NN2 on_II Twitter_NN1 and_CC Sina_NP1 Micro_NN1 Blog_NN1 ,_, count_VV0 their_APPGE tweets_NN2 or_CC microblogs_NN2 ,_, observe_VV0 the_AT frequency_NN1 of_IO their_APPGE tweeting_NN1 and_CC the_AT content_NN1 of_IO the_AT tweets_NN2 and_CC micro_NN1 blogs_NN2 ,_, and_CC analyze_VV0 their_APPGE method_NN1 and_CC philosophy_NN1 of_IO marketing_NN1 ._. 
</s>
<s>
The_AT companies_NN2 that_CST are_VBR selected_VVN to_TO explain_VVI the_AT situation_NN1 often_RR have_VH0 long_RR enough_DD history_NN1 of_IO Twitter_NN1 or_CC Sina_NP1 Micro_NN1 Blog_NN1 use_NN1 and_CC have_VH0 large_JJ enough_RR fan_VV0 teams_NN2 to_TO make_VVI the_AT samples_NN2 reliable_JJ and_CC meaningful_JJ ._. 
</s>
<s>
In_II the_AT analysis_NN1 of_IO the_AT examples_NN2 ,_, the_AT essential_JJ elements_NN2 of_IO marketing_NN1 ,_, such_II21 as_II22 methods_NN2 ,_, frequency_NN1 ,_, content_NN1 ,_, attention-drawing_JJ actions_NN2 ,_, and_CC philosophy_NN1 behind_II it_PPH1 ,_, will_VM be_VBI focused_VVN on_RP ._. 
</s>
<s>
Analysis_NN1 Marketing_NN1 is_VBZ eventually_RR more_RRR about_II the_AT brand_NN1 than_CSN specific_JJ products_NN2 ,_, and_CC the_AT brand_NN1 need_VV0 an_AT1 image_NN1 ._. 
</s>
<s>
Twitter_VV0 and_CC Sina_NP1 Micro_NN1 Blog_NN1 enables_VVZ companies_NN2 to_TO express_VVI themselves_PPX2 like_II real_JJ persons_NN2 ,_, which_DDQ never_RR happens_VVZ before_II the_AT online_JJ marketing_NN1 time_NNT1 started_VVD ._. 
</s>
<s>
The_AT most_RGT important_JJ thing_NN1 of_IO setting_VVG up_RP an_AT1 image_NN1 by_II Twitter_NN1 or_CC Sina_NP1 Micro_NN1 Blog_NN1 is_VBZ the_AT content_NN1 of_IO tweeting_VVG or_CC micro_NN1 blogging_VVG ._. 
</s>
<s>
Most_DAT of_IO time_NNT1 Sina_NP1 Micro_NN1 Blog_NN1 serves_VVZ the_AT role_NN1 as_II an_AT1 activity_NN1 publisher_NN1 and_CC that_DD1 is_VBZ the_AT most_RGT common_JJ way_NN1 companies_NN2 use_VV0 to_TO publicize_VVI themselves_PPX2 ,_, creating_VVG a_AT1 regular_JJ pattern_NN1 of_IO showing_VVG up_RP in_II31 front_II32 of_II33 public_NN1 with_IW low_JJ cost_NN1 ._. 
</s>
<s>
In_II this_DD1 aspect_NN1 ,_, companies_NN2 in_II China_NP1 do_VD0 as_RG good_JJ as_CSA Western_JJ companies_NN2 in_II Twitter_NN1 ._. 
</s>
<s>
For_REX21 instance_REX22 ,_, after_CS I_PPIS1 follow_VV0 KPMG_NP1 China_NP1 in_II Sina_NP1 Micro_NN1 Blog_NN1 ,_, I_PPIS1 realized_VVD that_CST I_PPIS1 would_VM connect_VVI with_IW this_DD1 company_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ all_DB about_II the_AT lives_NN2 of_IO staffs_NN2 in_II KPMG_NP1 China_NP1 and_CC the_AT recruitment_NN1 information_NN1 ._. 
</s>
<s>
It_PPH1 micro_NN1 blogged_VVD about_II the_AT staffs_NN2 playing_VVG football_NN1 games_NN2 ,_, learning_VVG about_II coffee_NN1 ,_, making_VVG cakes_NN2 ,_, taking_VVG fancy_JJ pictures_NN2 ,_, and_CC teaching_VVG children_NN2 in_II small_JJ villages_NN2 ,_, making_VVG the_AT life_NN1 in_II KPMG_NP1 China_NP1 admirable_JJ and_CC noble_JJ ._. 
</s>
<s>
It_PPH1 says_VVZ nothing_PN1 about_II the_AT hard_JJ work_NN1 and_CC the_AT difficulties_NN2 faced_VVN in_II the_AT whole_JJ auditing_NN1 business_NN1 ,_, which_DDQ really_RR exists_VVZ according_II21 to_II22 the_AT news_NN1 and_CC hearsays_NN2 from_II elders_NN2 in_II my_APPGE school_NN1 ._. 
</s>
<s>
Moreover_RR ,_, KPMG_NP1 China_NP1 micro_NN1 blogged_VVD a_AT1 lot_NN1 about_II the_AT recruitment_NN1 plan_NN1 ,_, showing_VVG a_AT1 lot_NN1 of_IO pictures_NN2 and_CC comments_NN2 about_II their_APPGE elite_NN1 program_NN1 and_CC school_NN1 bus_NN1 activities_NN2 ,_, which_DDQ both_DB2 are_VBR related_VVN to_TO employ_VVI interns_NN2 and_CC formal_JJ staffs_NN2 ._. 
</s>
<s>
In_II a_AT1 conclusion_NN1 ,_, KPMG_NP1 China_NP1 uses_VVZ its_APPGE Sina_NN1 Micro_NN1 Blog_NN1 account_NN1 to_TO do_VDI brand_NN1 marketing_NN1 towards_II potential_JJ employees_NN2 ._. 
</s>
<s>
It_PPH1 first_MD describes_VVZ desirable_JJ life_NN1 in_II KPMG_NP1 China_NP1 ,_, and_CC then_RT provides_VVZ all_DB the_AT information_NN1 about_II applying_VVG for_IF a_AT1 position_NN1 ._. 
</s>
<s>
Sina_NN1 Micro_NN1 Blog_NN1 has_VHZ also_RR become_VV0 an_AT1 excellent_JJ way_NN1 of_IO dealing_VVG with_IW public_JJ relations_NN2 crisis_NN1 ._. 
</s>
<s>
Bawang_NN1 is_VBZ a_AT1 company_NN1 in_II China_NP1 that_CST provides_VVZ shampoo_NN1 with_IW Chinese_JJ herbal_JJ medicine_NN1 ingredient_NN1 ,_, preventing_VVG hair_NN1 loss_NN1 ._. 
</s>
<s>
On_II July_NPM1 14_MC ,_, 2010_MC ,_, Next_MD Magazine_NN1 in_II Hong_NP1 Kong_NP1 published_VVD an_AT1 article_NN1 called_VVN Bawang_NP1 Leads_VVZ to_II Cancer_NN1 ,_, accusing_VVG that_CST many_DA2 kinds_NN2 of_IO Bawang_NP1 Chinese_JJ herbal_JJ medicine_NN1 shampoo_NN1 had_VHD been_VBN tested_VVN by_II Hong_NP1 Kong_NP1 Notary_NN1 and_CC the_AT result_NN1 was_VBDZ that_CST there_EX is_VBZ dioxane_NN1 found_VVD ,_, which_DDQ is_VBZ recognized_VVN to_TO be_VBI cancerogenic_JJ in_II USA_NP1 ._. 
</s>
<s>
It_PPH1 is_VBZ astonishing_JJ and_CC Bawangs_VVZ products_NN2 had_VHD to_TO be_VBI suspended_VVN that_DD1 afternoon_NNT1 ._. 
</s>
<s>
Despite_II of_IO the_AT traditional_JJ ways_NN2 of_IO handling_VVG this_DD1 kind_NN1 of_IO crisis_NN1 ,_, Bawang_NP1 turned_VVD to_II the_AT new_JJ media_NN path_NN1 ,_, using_VVG Sina_NP1 Micro_NN1 Blog_NN1 to_TO deal_VVI with_IW it_PPH1 ._. 
</s>
<s>
Bawang_NP1 signed_VVD up_RP immediately_RR after_II the_AT event_NN1 burst_VVD out_RP and_CC micro_NN1 blogged_VVD about_II the_AT rumor_NN1 ,_, explaining_VVG and_CC posting_VVG positive_JJ news_NN1 about_II the_AT company_NN1 ._. 
</s>
<s>
(_( Gao_NP1 ,_, pars_NN2 ._. 
</s>
<s>
11_MC )_) Bawang_VV0 micro_NN1 blogged_VVD 17_MC times_NNT2 that_DD1 day_NNT1 and_CC 17_MC times_NNT2 afterwards_RT about_II the_AT event_NN1 ,_, getting_VVG 766_MC forwards_RL and_CC 1122_MC comments_NN2 ,_, which_DDQ is_VBZ quite_RG an_AT1 impressive_JJ result_NN1 given_CS21 that_CS22 it_PPH1 is_VBZ a_AT1 new-signed-up_JJ account_NN1 ._. 
</s>
<s>
Bawang_NN1 is_VBZ a_AT1 famous_JJ brand_NN1 in_II China_NP1 ,_, so_CS the_AT event_NN1 drew_VVD a_AT1 lot_NN1 of_IO attention_NN1 ._. 
</s>
<s>
The_AT quick_JJ reaction_NN1 of_IO Bawang_NP1 effectivelycontrolled_VVD the_AT public_NN1 opinion_NN1 ,_, won_VVD enough_DD time_NNT1 for_IF testing_VVG in_II the_AT State_NN1 Food_NN1 and_CC Drug_NN1 Administration_NN1 ,_, and_CC got_VVD the_AT testing_NN1 results_VVZ that_CST the_AT amount_NN1 of_IO dioxane_NN1 in_II Bawang_NP1 shampoo_NN1 is_VBZ not_XX enough_RR to_TO harm_VVI the_AT consumers_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ a_AT1 successful_JJ example_NN1 of_IO using_VVG Sina_NP1 Micro_NN1 Blog_NN1 to_TO handle_VVI public_JJ relations_NN2 crisis_NN1 ,_, indicating_VVG that_DD1 Chinese_JJ companies_NN2 have_VH0 got_VVN the_AT sense_NN1 of_IO using_VVG new_JJ online_JJ methods_NN2 to_TO deal_VVI with_IW problems_NN2 in_II31 terms_II32 of_II33 marketing_NN1 ._. 
</s>
<s>
Sina_NN1 Micro_NN1 Blog_NN1 is_VBZ full_JJ of_IO people_NN who_PNQS love_VV0 forwarding_NN1 ._. 
</s>
<s>
They_PPHS2 are_VBR the_AT prefect_NN1 audience_NN1 of_IO this_DD1 kind_NN1 of_IO companies_NN2 micro_NN1 blog_NN1 ._. 
</s>
<s>
The_AT broad_JJ and_CC quick_JJ spread_NN1 of_IO truth_NN1 is_VBZ essential_JJ when_CS there_EX are_VBR rumors_NN2 ._. 
</s>
<s>
In_II the_AT past_NN1 ,_, it_PPH1 is_VBZ not_XX basically_RR possible_JJ because_CS people_NN tend_VV0 to_TO believe_VVI untruthful_JJ opinions_NN2 ,_, but_CCB today_RT ,_, a_AT1 website_NN1 like_II Sina_NP1 Micro_NN1 Blog_NN1 can_VM make_VVI it_PPH1 happen_VVI ._. 
</s>
<s>
That_DD1 is_VBZ why_RRQ Sina_NP1 Micro_NN1 Blog_NN1 has_VHZ become_VVN the_AT first_MD choice_NN1 of_IO companies_NN2 when_CS they_PPHS2 face_VV0 rumors_NN2 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, a_AT1 common_JJ way_NN1 of_IO Sina_NP1 Micro_NN1 Blog_NN1 marketing_NN1 is_VBZ to_TO use_VVI the_AT hot_JJ topic_NN1 of_IO the_AT moment_NN1 to_TO draw_VVI attention_NN1 ._. 
</s>
<s>
On_II June_NPM1 23_MC ,_, 2011_MC ,_, a_AT1 heavy_JJ rain_NN1 in_II Beijing_NP1 kept_VVD many_DA2 people_NN indoors_RL ,_, only_RR getting_VVG Sina_NP1 Micro_NN1 Blog_NN1 to_TO kill_VVI time_NNT1 ._. 
</s>
<s>
At_II that_DD1 day_NNT1 ,_, one_MC1 micro_NN1 blog_NN1 about_II using_VVG Durex_NP1 condoms_NN2 to_TO protect_VVI shoes_NN2 from_II getting_VVG wet_JJ suddenly_RR became_VVD the_AT hottest_JJT in_II Sina_NP1 Micro_NN1 Blog_NN1 ._. 
</s>
<s>
A_AT1 person_NN1 posted_VVD a_AT1 series_NN of_IO pictures_NN2 showing_VVG how_RRQ to_II sheath_NN1 shoes_NN2 with_IW Durex_NP1 condoms_NN2 along_II21 with_II22 words_NN2 like_VV0 With_IW Durex_NP1 ,_, no_AT wet_JJ shoes_NN2 ._. 
</s>
<s>
The_AT creativity_NN1 and_CC humor_NN1 draws_VVZ a_AT1 lot_NN1 of_IO attention_NN1 ,_, getting_VVG 90140_MC times_NNT2 of_IO forwarding_NN1 and_CC 17847_MC comments_NN2 ,_, involving_VVG 95015_MC micro_NN1 bloggers_NN2 ,_, and_CC becoming_VVG much_RR hotter_JJR than_CSN the_AT heavy_JJ rain_NN1 itself_PPX1 that_DD1 day_NNT1 ._. 
</s>
<s>
In_II fact_NN1 ,_, this_DD1 is_VBZ a_AT1 case_NN1 of_IO Durexs_NP2 Sina_NP1 Micro_NN1 Blog_NN1 marketing_NN1 ._. 
</s>
<s>
That_DD1 person_NN1 who_PNQS posted_VVD the_AT micro_NN1 blog_NN1 is_VBZ a_AT1 member_NN1 of_IO Durexs_NP2 marketing_NN1 team_NN1 ,_, and_CC the_AT micro_NN1 blog_NN1 was_VBDZ forwarded_VVN by_II Durexs_NP2 official_JJ Sina_NN1 Micro_NN1 Blog_NN1 account_NN1 at_II the_AT beginning_NN1 ._. 
</s>
<s>
An_AT1 issue_NN1 that_CST everybody_PN1 faces_VVZ adds_VVZ the_AT sense_NN1 of_IO humor_NN1 and_CC creativity_NN1 is_VBZ a_AT1 success_NN1 in_II Sina_NP1 Micro_NN1 Blog_NN1 marketing_NN1 ._. 
</s>
<s>
Although_CS Durex_NP1 is_VBZ a_AT1 foreign_JJ company_NN1 ,_, the_AT managing_NN1 and_CC marketing_NN1 ideas_NN2 of_IO Durex_NP1 China_NP1 are_VBR made_VVN by_II Chinese_JJ staffs_NN2 ,_, who_PNQS are_VBR mostly_RR young_JJ or_CC middle-aged_JJ Sina_NN1 Micro_NN1 Blog_NN1 users_NN2 ._. 
</s>
<s>
They_PPHS2 realized_VVD the_AT essential_JJ characteristic_NN1 of_IO Sina_NP1 Micro_NN1 Blog_NN1 and_CC use_VV0 it_PPH1 to_TO contribute_VVI to_II the_AT marketing_NN1 job_NN1 they_PPHS2 are_VBR responsible_JJ for_IF ._. 
</s>
<s>
Actually_RR ,_, in_II the_AT example_NN1 above_RL ,_, Durexs_NP2 marketing_NN1 team_NN1 not_XX only_RR started_VVD a_AT1 topic_NN1 and_CC made_VVD people_NN laugh_VVI ,_, but_CCB also_RR conducted_VVN an_AT1 effective_JJ move_NN1 of_IO marketing_NN1 ._. 
</s>
<s>
There_EX was_VBDZ a_AT1 huge_JJ discussion_NN1 of_IO Durex_NP1 as_CSA shoes_NN2 protector_NN1 that_DD1 day_NNT1 ,_, and_CC though_CS the_AT discussion_NN1 is_VBZ mostly_RR about_II fun_NN1 ,_, 55%_NNU of_IO the_AT discussion_NN1 mentioned_VVD Durex_NP1 ,_, 34%_NNU of_IO the_AT discussion_NN1 showed_VVD positive_JJ emotion_NN1 like_II recognition_NN1 of_IO the_AT brand_NN1 and_CC 3%_NNU of_IO the_AT discussion_NN1 is_VBZ clearly_RR about_II purchasing_VVG Durex_NP1 products_NN2 ._. 
</s>
<s>
Companies_NN2 use_VV0 marketing_NN1 strategy_NN1 to_TO publicize_VVI the_AT brand_NN1 ,_, and_CC the_AT key_NN1 of_IO brand_NN1 marketing_NN1 is_VBZ showing_VVG up_RP all_DB the_AT time_NNT1 ._. 
</s>
<s>
Never_RR let_VV0 people_NN forget_VVI about_II you_PPY ._. 
</s>
<s>
Only_RR when_CS people_NN need_VV0 something_PN1 ,_, your_APPGE companys_NN2 name_NN1 is_VBZ the_AT only_JJ word_NN1 that_CST emerges_VVZ in_II his_APPGE or_CC her_APPGE mind_NN1 ,_, your_APPGE brand_NN1 marketing_NN1 is_VBZ doing_VDG well_RR ._. 
</s>
<s>
Twitter_VV0 or_CC Sina_NP1 Micro_NN1 Blog_NN1 marketing_NN1 makes_VVZ showing_VVG up_RP all_DB the_AT time_NNT1 such_DA an_AT1 easy_JJ task_NN1 to_TO accomplish_VVI that_CST it_PPH1 is_VBZ hard_JJ to_TO imagine_VVI some_DD company_NN1 would_VM let_VVI its_APPGE account_NN1 on_II Sina_NP1 Micro_NN1 Blog_NN1 remain_VV0 silent_JJ for_IF a_AT1 week_NNT1 or_CC even_RR longer_RRR ._. 
</s>
<s>
But_CCB this_DD1 is_VBZ exactly_RR the_AT situation_NN1 in_II China_NP1 since_CS the_AT ignorance_NN1 of_IO the_AT significance_NN1 of_IO Sina_NP1 Micro_NN1 Blog_NN1 marketing_NN1 is_VBZ still_RR common_JJ ._. 
</s>
<s>
Many_DA2 companies_NN2 know_VV0 that_DD1 being_VBG present_JJ all_DB the_AT time_NNT1 is_VBZ the_AT basic_JJ rule_NN1 of_IO online_JJ social_JJ network_NN1 marketing_NN1 ,_, but_CCB given_CS21 that_CS22 Sina_NP1 Micro_NN1 Blog_NN1 marketing_NN1 has_VHZ not_XX developed_VVN to_TO be_VBI complete_JJ ,_, not_XX every_AT1 company_NN1 pay_NN1 attention_NN1 to_II this_DD1 rule_NN1 ._. 
</s>
<s>
KPMG_NP1 China_NP1 ,_, for_REX21 example_REX22 ,_, micro_NN1 blogged_VVD almost_RR once_RR or_CC twice_RR in_II one_MC1 week_NNT1 after_II the_AT recruitment_NN1 period_NN1 past_RL ._. 
</s>
<s>
It_PPH1 is_VBZ natural_JJ since_CS KPMG_NP1 China_NP1 recognizes_VVZ itself_PPX1 as_CSA propaganda_NN1 for_IF recruitment_NN1 ,_, but_CCB this_DD1 kind_NN1 of_IO action_NN1 makes_VVZ it_PPH1 absent_VVI from_II public_JJ notice_NN1 in_II a_AT1 very_RG long_JJ time_NNT1 throughout_II the_AT year_NNT1 ,_, which_DDQ is_VBZ absolutely_RR not_XX expected_VVN in_II31 terms_II32 of_II33 marketing_NN1 ._. 
</s>
<s>
KPMG_NP1 US_NP1 on_II Twitter_NN1 ,_, on_II the_AT contrary_NN1 ,_, keeps_VVZ showing_VVG up_RP ._. 
</s>
<s>
It_PPH1 tweets_VVZ several_DA2 times_NNT2 a_AT1 day_NNT1 even_CS21 when_CS22 there_EX is_VBZ no_AT information_NN1 about_II recruitment_NN1 to_TO give_VVI ._. 
</s>
<s>
The_AT example_NN1 of_IO KPMG_NP1 China_NP1 is_VBZ classic_JJ ,_, it_PPH1 seems_VVZ that_CST the_AT account_NN1 of_IO the_AT company_NN1 is_VBZ charged_VVN by_II a_AT1 girl_NN1 who_PNQS gets_VVZ a_AT1 lot_NN1 of_IO stuff_NN1 to_TO do_VDI and_CC Sina_NP1 Micro_NN1 Blog_NN1 marketing_NN1 is_VBZ just_RR as_RG important_JJ as_CSA a_AT1 copy_NN1 task_NN1 ._. 
</s>
<s>
We_PPIS2 wish_VV0 that_CST as_II the_AT importance_NN1 of_IO Sina_NP1 Micro_NN1 Blog_NN1 marketing_NN1 becomes_VVZ more_DAR and_CC more_RGR obvious_JJ ,_, companies_NN2 would_VM take_VVI it_PPH1 more_RGR seriously_RR and_CC actually_RR use_VV0 it_PPH1 as_II a_AT1 true_JJ marketing_NN1 tool_NN1 rather_II21 than_II22 a_AT1 game_NN1 ._. 
</s>
<s>
Forming_VVG a_AT1 team_NN1 to_TO charge_VVI the_AT whole_JJ Sina_NN1 Micro_NN1 Blog_NN1 marketing_NN1 is_VBZ one_MC1 way_NN1 to_TO make_VVI it_PPH1 professional_JJ and_CC well-took-care-of_NN1 ._. 
</s>
<s>
One_MC1 person_NN1 is_VBZ easy_JJ to_TO ignore_VVI the_AT importance_NN1 of_IO maintaining_VVG Sina_NP1 Micro_NN1 Blog_NN1 ,_, forget_VV0 about_II micro_NN1 blogging_VVG on_II a_AT1 daily_JJ basis_NN1 or_CC an_AT1 even_RR more_RGR regular_JJ basis_NN1 ,_, and_CC be_VBI sluggish_JJ about_II holding_VVG up_RP new_JJ events_NN2 and_CC thinking_VVG about_II new_JJ ideas_NN2 ,_, but_CCB when_CS it_PPH1 comes_VVZ to_II a_AT1 team_NN1 ,_, and_CC the_AT teams_NN2 responsibility_NN1 is_VBZ clearly_RR Sina_NP1 Micro_NN1 Blog_NN1 marketing_NN1 ,_, the_AT attitude_NN1 will_VM be_VBI more_RGR serious_JJ and_CC brainstorming_NN1 will_VM be_VBI truly_RR useful_JJ and_CC productive_JJ ._. 
</s>
<s>
For_REX21 example_REX22 ,_, the_AT Durex_NP1 Sina_NP1 Micro_NN1 Blog_NN1 marketing_NN1 team_NN1 works_VVZ quite_RG effectively_RR ,_, which_DDQ is_VBZ rare_JJ in_II the_AT Chinese_JJ business_NN1 environment_NN1 and_CC this_DD1 is_VBZ a_AT1 team_NN1 that_CST can_VM show_VVI the_AT philosophy_NN1 of_IO Sina_NP1 Micro_NN1 Blog_NN1 marketing_NN1 well_RR ._. 
</s>
<s>
The_AT topic_NN1 of_IO SNS_NN2 is_VBZ to_TO share_VVI and_CC it_PPH1 changed_VVD the_AT way_NN1 in_II which_DDQ companies_NN2 communicate_VV0 with_IW consumers_NN2 ._. 
</s>
<s>
If_CS a_AT1 brand_NN1 does_VDZ not_XX consider_VVI changing_JJ ,_, it_PPH1 will_VM face_VVI the_AT danger_NN1 of_IO being_VBG eliminated_VVN ,_, says_VVZ Chu_NP1 Wen_NP1 ,_, the_AT managing_JJ partner_NN1 of_IO Ogilvy_JJ Public_JJ Relations_NN2 ,_, the_AT best_RRT about_II SNS_NN2 is_VBZ that_CST it_PPH1 forces_VVZ every_AT1 brand_NN1 to_TO be_VBI sincere._NNU Being_VBG sincere_JJ is_VBZ fundamental_JJ for_IF the_AT success_NN1 of_IO Twitter_NN1 or_CC Sina_NP1 Micro_NN1 Blog_NN1 marketing_NN1 ._. 
</s>
<s>
The_AT example_NN1 above_RL about_II KPMG_NP1 China_NP1 indicates_VVZ that_CST many_DA2 companies_NN2 are_VBR using_VVG Sina_NP1 Micro_NN1 Blog_NN1 marketing_NN1 ,_, but_CCB they_PPHS2 are_VBR not_XX sincere_JJ enough_RR ._. 
</s>
<s>
Durex_NP1 ,_, on_II the_AT other_JJ hand_NN1 ,_, at_RR21 least_RR22 formed_VVN a_AT1 team_NN1 to_TO conduct_VVI it_PPH1 ._. 
</s>
<s>
The_AT team_NN1 consists_VVZ of_IO about_RG 20_MC persons_NN2 ,_, who_PNQS are_VBR all_DB humorous_JJ ,_, smart_JJ ,_, and_CC talkative_JJ people_NN ._. 
</s>
<s>
The_AT team_NN1 splits_VVZ the_AT marketing_NN1 job_NN1 into_II many_DA2 specific_JJ aspects_NN2 ;_; for_REX21 example_REX22 ,_, there_EX are_VBR 3_MC aspects_NN2 of_IO work_NN1 in_II31 terms_II32 of_II33 content_NN1 of_IO the_AT micro_NN1 blog_NN1 :_: content_JJ ,_, copywriter_NN1 ,_, and_CC reply_NN1 ._. 
</s>
<s>
Content_JJ staffs_NN2 are_VBR in_II31 charge_II32 of_II33 the_AT most_DAT information_NN1 publishing_NN1 ._. 
</s>
<s>
Copywriter_JJR staffs_NN2 are_VBR in_II31 charge_II32 of_II33 planning_VVG topics_NN2 and_CC reply_VV0 staffs_NN2 are_VBR responsible_JJ for_IF screening_VVG interesting_JJ information_NN1 among_II all_DB the_AT micro_NN1 blogs_VVZ that_CST @_II Durexs_NP2 official_JJ micro_NN1 blog_NN1 account_NN1 and_CC reply_VV0 some_DD comments_NN2 ._. 
</s>
<s>
The_AT meticulous_JJ division_NN1 of_IO labor_NN1 makes_VVZ it_PPH1 possible_JJ to_TO take_VVI Sina_NP1 Micro_NN1 Blog_NN1 marketing_NN1 to_II a_AT1 more_RGR professional_JJ level_NN1 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, everything_PN1 posted_VVD on_II Durexs_NP2 official_JJ Sina_NN1 Micro_NN1 Blog_NN1 are_VBR classified_VVN in_II a_AT1 data_NN base_NN1 and_CC the_AT amounts_NN2 of_IO forwarding_NN1 and_CC comments_NN2 are_VBR counted_VVN every_AT1 5_MC days_NNT2 ._. 
</s>
<s>
At_II the_AT end_NN1 of_IO each_DD1 month_NNT1 ,_, the_AT data_NN will_VM be_VBI analyzed_VVN deeply_RR to_TO find_VVI out_RP what_DDQ is_VBZ good_JJ and_CC what_DDQ is_VBZ bad_JJ ,_, and_CC this_DD1 kind_NN1 of_IO analysis_NN1 can_VM be_VBI real_JJ and_CC opportune_JJ ,_, pointing_VVG out_RP the_AT direction_NN1 that_CST the_AT marketing_NN1 should_VM head_VVI to_II ._. 
</s>
<s>
Furthermore_RR ,_, Durexs_NP2 success_NN1 in_II the_AT competition_NN1 of_IO Sina_NP1 Micro_NN1 Blog_NN1 marketing_NN1 can_VM be_VBI attributed_VVN to_II the_AT clear_JJ positioning_NN1 of_IO the_AT brand_NN1 ._. 
</s>
<s>
At_RR21 first_RR22 ,_, Durex_NP1 position_NN1 itself_PPX1 as_II an_AT1 Otaku_NP1 ,_, which_DDQ means_VVZ indoorsman_NN1 ._. 
</s>
<s>
But_CCB later_RRR ,_, Durexs_NP2 marketing_NN1 team_NN1 realized_VVD that_CST it_PPH1 is_VBZ not_XX an_AT1 appropriate_JJ position_NN1 for_IF Durex_NP1 ,_, so_CS they_PPHS2 changed_VVD into_II an_AT1 image_NN1 of_IO a_AT1 man_NN1 ,_, who_PNQS is_VBZ gentle_JJ and_CC evil_NN1 at_II the_AT same_DA time_NNT1 and_CC knows_VVZ deeply_RR about_II life_NN1 and_CC entertainment_NN1 ,_, just_RR like_II a_AT1 handsome_JJ guy_NN1 in_II a_AT1 night_NNT1 pub_NN1 ._. 
</s>
<s>
This_DD1 image_NN1 suits_VVZ Durex_NP1 ,_, a_AT1 brand_NN1 of_IO condoms_NN2 ,_, very_RG well_RR ,_, and_CC gives_VVZ Durexs_NP2 Sina_NP1 Micro_NN1 Blog_NN1 marketing_NN1 team_NN1 a_AT1 much_RR larger_JJR space_NN1 to_TO develop_VVI ideas_NN2 ._. 
</s>
<s>
Choosing_VVG suitable_JJ positioning_NN1 and_CC making_VVG the_AT image_NN1 real_JJ and_CC vivid_JJ are_VBR the_AT basic_JJ steps_NN2 of_IO functioning_VVG a_AT1 companys_NN2 Sina_NP1 Micro_NN1 Blog_NN1 marketing_NN1 ._. 
</s>
<s>
The_AT setting-up_NN1 part_NN1 is_VBZ fundamental_JJ ,_, but_CCB the_AT maintaining_VVG part_NN1 is_VBZ the_AT one_PN1 that_CST determines_VVZ whether_CSW the_AT marketing_NN1 can_VM go_VVI on_RP for_IF a_AT1 long_JJ time_NNT1 ,_, accumulate_VV0 a_AT1 huge_JJ fans_NN2 foundation_NN1 ,_, and_CC make_VV0 the_AT marketing_NN1 really_RR useful_JJ ._. 
</s>
<s>
According_II21 to_II22 Chu_NP1 Wen_NP1 ,_, there_EX is_VBZ difference_NN1 between_II traditional_JJ media_NN and_CC social_JJ media_NN about_II the_AT company_NN1 positioning_NN1 ._. 
</s>
<s>
By_II traditional_JJ media_NN companies_NN2 tell_VV0 consumers_NN2 who_PNQS they_PPHS2 are_VBR and_CC consumers_NN2 just_RR accept_VV0 it_PPH1 ;_; however_RR ,_, companies_NN2 that_CST use_VV0 social_JJ media_NN to_TO set_VVI up_RP images_NN2 communicate_VV0 with_IW consumers_NN2 like_II person_NN1 to_II person_NN1 ._. 
</s>
<s>
Consumers_NN2 get_VV0 dynamic_JJ images_NN2 through_II the_AT communication_NN1 and_CC the_AT companies_NN2 action_NN1 ,_, and_CC that_DD1 is_VBZ why_RRQ the_AT maintenance_NN1 of_IO Sina_NP1 Micro_NN1 Blog_NN1 account_NN1 is_VBZ very_RG significant_JJ ._. 
</s>
<s>
Taking_VVG Durex_NP1 as_II an_AT1 example_NN1 ,_, the_AT language_NN1 of_IO Durexs_NP2 official_JJ Sina_NN1 Micro_NN1 Blog_NN1 account_NN1 is_VBZ always_RR humorous_JJ and_CC lighthearted_VVD since_CS the_AT positioningwas_NN2 fixed_VVN ._. 
</s>
<s>
When_CS Durex_NP1 and_CC Fang_NN1 Zhouzi_NN1 ,_, a_AT1 Chinese_JJ fraud-fighter_NN1 ,_, had_VHD a_AT1 war_NN1 of_IO words_NN2 ,_, this_DD1 language_NN1 style_NN1 was_VBDZ quite_RG attractive_JJ ._. 
</s>
<s>
No_RGQV31 matter_RGQV32 how_RGQV33 offensive_JJ Fang_NN1 Zhouzi_NN1 was_VBDZ ,_, Durex_NP1 always_RR took_VVD it_PPH1 easy_JJ and_CC behaved_VVD gently_RR ._. 
</s>
<s>
After_CS the_AT event_NN1 ,_, Durex_NP1 gained_VVD 6,000_MC more_DAR fans_NN2 ,_, and_CC Fang_NN1 Zhouzi_NN1 lost_VVD a_AT1 few_DA2 thousand_NNO fans_NN2 ._. 
</s>
<s>
Durex_NP1 China_NP1 is_VBZ a_AT1 great_JJ example_NN1 of_IO the_AT best_JJT companies_NN2 can_VM do_VDI with_IW Sina_NP1 Micro_NN1 Blog_NN1 ._. 
</s>
<s>
When_CS Durex_NP1 signed_VVD up_RP on_II Sina_NP1 Micro_NN1 Blog_NN1 ,_, one_MC1 of_IO its_APPGE competitors_NN2 ,_, Jissbon_NP1 ,_, had_VHD gotten_VVN 10700_MC fans_NN2 ;_; however_RR ,_, Durexs_NP2 number_NN1 of_IO fans_NN2 reached_VVD 210,000_MC in_II the_AT October_NPM1 of_IO 2011_MC ,_, but_CCB Jissbons_NP1 number_NN1 of_IO fans_NN2 is_VBZ just_RR 20,000_MC ._. 
</s>
<s>
(_( CEIBS_VVZ Business_NN1 Review_NN1 ,_, Interpretation_NN1 of_IO the_AT micro_NN1 bloggingfans_NN2 behavior_NN1 )_) This_DD1 is_VBZ the_AT result_NN1 of_IO good_JJ marketing_NN1 management_NN1 and_CC proper_JJ self-positioning_NN1 ._. 
</s>
<s>
In_II a_AT1 nutshell_NN1 ,_, when_CS you_PPY treat_VV0 Sina_NP1 Micro_NN1 Blog_NN1 marketing_NN1 seriously_RR ,_, it_PPH1 feeds_VVZ back_RP you_PPY richly_RR ._. 
</s>
<s>
Discussion_NN1 China_NP1 ,_, as_CSA a_AT1 country_NN1 governed_VVN by_II Peoples_NN2 Congress_NN1 and_CC led_VVD only_RR by_II Communist_JJ Party_NN1 ,_, has_VHZ been_VBN in_II an_AT1 awkward_JJ position_NN1 in_II the_AT world_NN1 for_IF a_AT1 long_JJ time_NNT1 ._. 
</s>
<s>
As_CSA one_MC1 of_IO the_AT young_JJ generation_NN1 of_IO China_NP1 ,_, my_APPGE feeling_NN1 about_II my_APPGE own_DA country_NN1 is_VBZ also_RR complicated_JJ ._. 
</s>
<s>
China_NP1 was_VBDZ always_RR a_AT1 strong_JJ country_NN1 until_II 1840_MC ,_, and_CC then_RT it_PPH1 went_VVD through_RP anearly_RR modern_JJ history_NN1 full_JJ of_IO failure_NN1 and_CC shame_NN1 ._. 
</s>
<s>
We_PPIS2 got_VVD a_AT1 chance_NN1 to_TO evaluate_VVI ourselves_PPX2 again_RT ,_, but_CCB the_AT danger_NN1 of_IO national_JJ subjugation_NN1 did_VDD not_XX give_VVI Chinese_JJ people_NN to_TO develop_VVI a_AT1 new_JJ way_NN1 of_IO dealing_VVG with_IW the_AT modern_JJ world_NN1 ._. 
</s>
<s>
Communism_NN1 ,_, in_II a_AT1 simple_JJ and_CC plain_JJ way_NN1 ,_, brought_VVD Chinese_JJ people_NN together_RL to_TO fight_VVI against_II invaders_NN2 ._. 
</s>
<s>
However_RR ,_, we_PPIS2 did_VDD not_XX do_VDI well_RR in_II the_AT transition_NN1 from_II an_AT1 old_JJ country_NN1 suffered_VVN from_II wars_NN2 for_IF tens_MC2 of_IO years_NNT2 to_II a_AT1 modern_JJ country_NN1 that_CST has_VHZ enough_RR strengthand_JJ dignity_NN1 to_TO develop_VVI a_AT1 healthy_JJ and_CC friendly_JJ relationship_NN1 with_IW Western_JJ world_NN1 ._. 
</s>
<s>
We_PPIS2 want_VV0 to_TO accept_VVI new_JJ thoughts_NN2 and_CC develop_VVI our_APPGE traditional_JJ philosophy_NN1 at_II the_AT same_DA time_NNT1 ,_, which_DDQ leads_VVZ to_II the_AT chaos_NN1 of_IO thought_NN1 ,_, especially_RR among_II the_AT young_JJ generation_NN1 ._. 
</s>
<s>
Similarly_RR ,_, we_PPIS2 want_VV0 to_TO let_VVI the_AT country_NN1 be_VBI democratic_JJ ,_, but_CCB releasing_VVG power_NN1 steadily_RR is_VBZ much_RR more_RGR difficult_JJ than_CSN fighting_VVG for_IF the_AT power_NN1 ._. 
</s>
<s>
The_AT information_NN1 block_NN1 in_II the_AT Internet_NN1 is_VBZ only_RR one_MC1 aspect_NN1 of_IO Chinas_NP2 struggle_NN1 ,_, but_CCB it_PPH1 also_RR involves_VVZ another_DD1 conflict_NN1 in_II modern_JJ China_NN1 ._. 
</s>
<s>
We_PPIS2 want_VV0 to_TO be_VBI open_JJ to_II the_AT high-speeded_JJ world_NN1 ,_, catching_VVG up_RP with_IW it_PPH1 and_CC developing_VVG in_II the_AT same_DA speed_NN1 ,_, but_CCB we_PPIS2 have_VH0 to_TO keep_VVI a_AT1 distance_NN1 from_II the_AT modern_JJ time_NNT1 in_BCL21 order_BCL22 to_TO stabilize_VVI the_AT internal_JJ Chinese_JJ society_NN1 ._. 
</s>
<s>
The_AT distance_NN1 ,_, in_II certain_JJ ways_NN2 ,_, forms_VVZ the_AT reason_NN1 why_RRQ we_PPIS2 always_RR follow_VV0 behind_II the_AT steps_NN2 of_IO Western_JJ countries_NN2 ,_, not_XX only_JJ economy_NN1 and_CC technology_NN1 ,_, but_CCB also_RR information_NN1 and_CC thought_VVD ._. 
</s>
<s>
We_PPIS2 can_VM not_XX get_VVI access_NN1 to_II Twitter_NN1 ,_, so_CS we_PPIS2 create_VV0 Sina_NP1 Micro_NN1 Blog_NN1 3_MC years_NNT2 later_RRR ._. 
</s>
<s>
Twitter_VV0 or_CC Sina_NP1 Micro_NN1 Blog_NN1 marketing_NN1 is_VBZ still_RR in_II the_AT experimental_JJ phase_NN1 ,_, no_AT matter_NN1 in_II Western_JJ countries_NN2 or_CC in_II China_NP1 ,_, and_CC that_DD1 is_VBZ the_AT main_JJ reason_NN1 that_CST there_EX is_VBZ no_AT huge_JJ gap_NN1 between_II Twitter_NN1 marketing_NN1 and_CC Sina_NP1 Micro_NN1 Blog_NN1 marketing_NN1 ._. 
</s>
<s>
However_RR ,_, just_RR like_II other_JJ techniques_NN2 or_CC market_VV0 operating_VVG elements_NN2 ,_, Twitter_NN1 or_CC Sina_NP1 Micro_NN1 Blog_NN1 marketing_NN1 would_VM embrace_VVI its_APPGE innovative_JJ time_NNT1 ,_, and_CC at_II that_DD1 time_NNT1 ,_, it_PPH1 is_VBZ essential_JJ that_CST if_CS China_NP1 can_VM grasp_VVI the_AT opportunity_NN1 and_CC catch_VVI up_RP immediately_RR ,_, or_CC even_RR start_VV0 the_AT innovation_NN1 ._. 
</s>
<s>
Steve_NP1 Jobs_NN2 used_VVD his_APPGE talent_NN1 to_TO start_VVI Apple_NN1 Inc._JJ and_CC create_VVI a_AT1 series_NN of_IO digital_JJ products_NN2 ,_, changing_VVG peoples_NN2 relationship_NN1 with_IW digital_JJ time_NNT1 and_CC digital_JJ productsdeveloping_JJ direction_NN1 forever_RT ._. 
</s>
<s>
David_NP1 Ogilvy_NP1 ,_, from_II the_AT 1940s_MC2 to_II 1970s_MC2 ,_, took_VVD Ogilvy_NP1 &Mather;_NULL Worldwide_RL to_II a_AT1 peak_NN1 of_IO advertising_NN1 ,_, starting_VVG a_AT1 new_JJ period_NN1 of_IO advertising_NN1 and_CC creating_VVG a_AT1 complete_JJ and_CC mature_JJ advertising_NN1 philosophy_NN1 at_II the_AT same_DA time_NNT1 ._. 
</s>
<s>
This_DD1 kind_NN1 of_IO innovation_NN1 ,_, I_PPIS1 believe_VV0 ,_, will_VM also_RR happen_VVI to_II Twitter_NN1 or_CC Sina_NP1 Micro_NN1 Blog_NN1 marketing_NN1 one_MC1 day_NNT1 ._. 
</s>
<s>
All_DB is_VBZ needed_VVN is_VBZ the_AT maturity_NN1 of_IO this_DD1 way_NN1 of_IO marketing_NN1 and_CC a_AT1 talents_NN2 birth_NN1 ._. 
</s>
<s>
No_PN121 one_PN122 can_VM control_VVI where_RRQ this_DD1 talent_NN1 will_VM be_VBI born_VVN ,_, but_CCB companies_NN2 and_CC scholars_NN2 can_VM control_VVI the_AT maturity_NN1 of_IO the_AT marketing_NN1 environment_NN1 ._. 
</s>
<s>
China_NP1 is_VBZ in_II a_AT1 time_NNT1 of_IO transition_NN1 in_II all_DB aspects_NN2 ,_, and_CC the_AT policy_NN1 now_RT is_VBZ to_TO do_VDI it_PPH1 steadily_RR ._. 
</s>
<s>
However_RR ,_, the_AT development_NN1 of_IO economy_NN1 and_CC market_NN1 has_VHZ always_RR been_VBN fast_JJ since_CS the_AT reform_NN1 and_CC opening-up_NN1 policy_NN1 in_II 1970s_MC2 ,_, so_CS it_PPH1 is_VBZ reasonable_JJ to_TO say_VVI that_CST Sina_NP1 Micro_NN1 Blog_NN1 marketing_NN1 will_VM develop_VVI faster_RRR and_CC reach_VVI its_APPGE innovative_JJ point_NN1 early_RR enough_RR to_TO meet_VVI the_AT innovative_JJ point_NN1 of_IO Twitter_NN1 marketing_NN1 ,_, or_CC better_RRR ,_, Sina_NP1 Micro_NN1 Blog_NN1 marketing_NN1 becomes_VVZ Twitter_NN1 marketing_NN1 ,_, because_CS then_RT people_NN in_II China_NP1 can_VM sign_VVI up_RP on_II Twitter_NN1 and_CC get_VVI information_NN1 as_RG free_JJ as_CSA people_NN in_II Western_JJ countries_NN2 ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 ,_, Chinese_JJ society_NN1 is_VBZ moving_VVG forward_RL too_RG fast_RR ,_, distracting_VVG peoples_NN2 attention_NN1 from_II the_AT really_RR valuable_JJ things_NN2 to_II the_AT illusions_NN2 caused_VVN by_II the_AT high_JJ developing_JJ speed_NN1 ._. 
</s>
<s>
The_AT emergence_NN1 of_IO cheap_JJ copy_NN1 products_NN2 ,_, for_REX21 example_REX22 ,_, is_VBZ always_RR considered_VVN to_TO be_VBI the_AT sign_NN1 of_IO the_AT lack_NN1 of_IO imagination_NN1 and_CC innovation_NN1 ability_NN1 ._. 
</s>
<s>
Furthermore_RR ,_, the_AT popularity_NN1 of_IO cheap_JJ copy_NN1 products_NN2 shows_VVZ that_CST Chinese_JJ society_NN1 ,_, as_II a_AT1 whole_NN1 ,_, has_VHZ not_XX formed_VVN the_AT appreciation_NN1 of_IO original_JJ thoughts_NN2 and_CC ideas_NN2 ._. 
</s>
<s>
Many_DA2 famous_JJ companies_NN2 copy_VV0 other_JJ companies_NN2 new_JJ idea_NN1 to_TO make_VVI their_APPGE own_DA products_NN2 ._. 
</s>
<s>
For_REX21 example_REX22 ,_, the_AT copy_NN1 of_IO iPhone_NN1 is_VBZ quite_RG commonin_NN1 Chinese_JJ cellphone_NN1 market_NN1 ,_, and_CC when_RRQ people_NN can_VM not_XX afford_VVI iPhone_NN1 ,_, these_DD2 copycats_NN2 are_VBR perfect_JJ substitutes_NN2 ._. 
</s>
<s>
No_PN121 one_PN122 really_RR care_VV0 about_II the_AT originality_NN1 of_IO the_AT cellphone_NN1 ,_, and_CC if_CS this_DD1 kind_NN1 of_IO people_NN take_VV0 the_AT larger_JJR part_NN1 of_IO the_AT consumers_NN2 ,_, it_PPH1 is_VBZ hard_JJ to_TO predict_VVI that_CST some_DD companies_NN2 will_VM pay_VVI much_RR on_II innovation_NN1 since_CS simply_RR copying_VVG can_VM lead_VVI to_II much_RR lower_JJR cost_NN1 thus_RR much_RR higher_JJR profit_NN1 ._. 
</s>
<s>
Cheap_JJ copying_NN1 is_VBZ just_RR an_AT1 indication_NN1 of_IO Chinese_JJ societys_NN2 ignorance_NN1 of_IO intellectual_JJ value_NN1 ,_, and_CC the_AT ignorance_NN1 certainly_RR does_VDZ not_XX contribute_VVI to_II a_AT1 good_JJ environment_NN1 for_IF a_AT1 breakthrough_NN1 in_II the_AT case_NN1 of_IO Sina_NP1 Micro_NN1 Blog_NN1 marketing_NN1 ._. 
</s>
<s>
The_AT only_JJ hope_NN1 is_VBZ that_CST in_II a_AT1 few_DA2 years_NNT2 ,_, people_NN will_VM start_VVI to_TO realize_VVI the_AT importance_NN1 of_IO intellectual_JJ originality_NN1 ,_, and_CC it_PPH1 is_VBZ not_XX too_RG late_JJ ._. 
</s>
