<s>
COBIT_VV0 AS_CSA AUDITING_VVG AND_CC CONTROL_VV0 FRAMEWORK_NN1 Introduction_NN1 All_DB control_VV0 frameworks_NN2 can_VM be_VBI organized_VVN into_II three_MC broad_JJ categories_NN2 ,_, namely_REX business_NN1 oriented_VVD controls_NN2 ,_, like_II COSO_NP1 (_( Committee_NN1 of_IO Sponsoring_VVG Organization_NN1 )_) or_CC SAS_NP1 (_( Statement_NN1 of_IO Auditing_VVG Standards_NN2 )_) ;_; IT_NN1 (_( Information_NN1 Technology_NN1 )_) focused_VVD on_II controls_NN2 namely_REX ,_, ITIL_NP1 (_( The_AT IT_NN1 Infrastructure_NN1 Library_NN1 )_) or_CC ISO/IEC_NP1 17799:2000_MC (_( The_AT International_JJ Organization_NN1 for_CS Standardization/the_FU Electro_JJ technical_JJ Commission_NN1 )_) ;_; and_CC a_AT1 third_MD category_NN1 of_IO controls_NN2 that_CST bring_VV0 together_RL IT_PPH1 controls_VVZ and_CC business_NN1 goals_NN2 ,_, particularly_RR ,_, COBIT_NP1 (_( Control_NN1 Objectives_NN2 for_IF Information_NN1 and_CC related_JJ Technology_NN1 )_) ._. 
</s>
<s>
COBIT_NP1 is_VBZ a_AT1 framework_NN1 developed_VVN by_II ISACA_NP1 (_( Information_NN1 Systems_NN2 Audit_NN1 and_CC Control_NN1 Association_NN1 )_) for_IF information_NN1 technology_NN1 management_NN1 and_CC governance_NN1 ._. 
</s>
<s>
Its_APPGE function_NN1 is_VBZ to_TO support_VVI organizations_NN2 in_II achieving_VVG their_APPGE business_NN1 objectives_NN2 in_II the_AT best_JJT possible_JJ way_NN1 ,_, and_CC its_APPGE mission_NN1 is_VBZ to_TO research_VVI ,_, develop_VV0 ,_, publicize_VV0 ,_, and_CC promote_VV0 an_AT1 authoritative_JJ ,_, up-to-date_JJ ,_, international_JJ set_NN1 of_IO generally_RR accepted_JJ information_NN1 technology_NN1 control_NN1 objectives_NN2 for_IF day-to-day_JJ use_NN1 by_II business_NN1 managers_NN2 and_CC auditors._NNU (_( ISACA_NP1 ,_, 2000_MC )_) ._. 
</s>
<s>
Originally_RR ,_, COBIT_NP1 was_VBDZ proposed_VVN to_TO be_VBI used_VVN as_II a_AT1 benchmarking_NN1 tool_NN1 comprising_VVG the_AT best_JJT practices_NN2 related_VVN to_II IT_NN1 controls_NN2 (_( Tuttle_NP1 and_CC Vandervelde_NP1 ,_, 2007_MC )_) ;_; however_RR ,_, it_PPH1 has_VHZ been_VBN recognized_VVN also_RR as_II a_AT1 control_NN1 framework_NN1 ,_, for_IF its_APPGE capability_NN1 to_TO offer_VVI a_AT1 defined_JJ and_CC recognized_JJ set_NN1 of_IO IT_NN1 control_NN1 processes_NN2 ,_, objectives_NN2 ,_, and_CC activities_NN2 (_( Ramos_NP1 ,_, 2004_MC )_) ,_, and_CC many_DA2 international_JJ accounting_NN1 companies_NN2 have_VH0 employed_VVN this_DD1 framework_NN1 for_IF measuring_VVG the_AT effectiveness_NN1 of_IO internal_JJ controls_NN2 of_IO their_APPGE clients_NN2 (_( Winters_NP1 ,_, 2004_MC )_) ._. 
</s>
<s>
Control_VV0 frameworks_NN2 are_VBR widely_RR used_VVN by_II organizations_NN2 and_CC auditors_NN2 during_II the_AT internal_JJ controls_NN2 design_NN1 and_CC evaluation_NN1 phases_NN2 ;_; but_CCB especially_RR the_AT applicability_NN1 of_IO internal_JJ control_NN1 frameworks_NN2 has_VHZ increased_VVN with_IW the_AT passage_NN1 of_IO the_AT SarbanesOxley_NP1 Act_NN1 of_IO 2002_MC ,_, Auditing_VVG Standard_NN1 No.2_FO in_II 2004_MC (_( Tuttle_NP1 and_CC Vandervelde_NP1 ,_, 2007_MC )_) ,_, and_CC Auditing_VVG Standard_JJ No._NN1 5_MC in_II 2007_MC ,_, which_DDQ forces_VVZ organizations_NN2 to_TO implement_VVI internal_JJ control_NN1 frameworks_NN2 and_CC to_TO report_VVI on_II their_APPGE effectiveness_NN1 (_( Bernroider_NP1 and_CC Ivanov_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
Organizations_NN2 and_CC auditors_NN2 have_VH0 been_VBN adopting_VVG COBIT_NN1 to_TO supplement_VVI COSO_NP1 (_( Committee_NN1 of_IO Sponsoring_VVG Organizations_NN2 )_) framework_NN1 (_( Tuttle_NP1 and_CC Vandervelde_NP1 ,_, 2007_MC )_) ._. 
</s>
<s>
Ridley_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2004_MC )_) claim_VV0 that_CST since_CS COBIT_NP1 framework_NN1 takes_VVZ into_II account_NN1 all_DB major_JJ aspects_NN2 of_IO information_NN1 and_CC its_APPGE supportive_JJ IT_NN1 functions_NN2 ,_, COBIT_NP1 could_VM be_VBI used_VVN as_II a_AT1 tool_NN1 for_IF providing_VVG an_AT1 appropriate_JJ control_NN1 system_NN1 for_IF IT_NN1 ._. 
</s>
<s>
Moreover_RR ,_, Summerfield_NP1 (_( 2005_MC )_) claims_VVZ that_CST every_AT1 major_JJ accounting_NN1 firm_NN1 has_VHZ adopted_VVN COBIT_NN1 in_II31 connection_II32 with_II33 their_APPGE review_NN1 of_IO internal_JJ control_NN1 ._. 
</s>
<s>
Prior_JJ research_NN1 offers_VVZ empirical_JJ evidence_NN1 showing_VVG that_DD1 COBIT_NN1 framework_NN1 can_VM assist_VVI organizations_NN2 in_II complying_VVG with_IW SOX_NN2 requirements_NN2 (_( Lin_NP1 ,_, Guan_NP1 ,_, and_CC Fang_NN1 ,_, 2010_MC )_) ;_; it_PPH1 can_VM also_RR provide_VVI guidelines_NN2 for_IF auditors_NN2 to_II internal_JJ control_NN1 structure_NN1 and_CC metrics_NN1 assessments_NN2 (_( Lainhart_NP1 ,_, 2001_MC ;_; Wallhoff_NP1 ,_, 2004_MC )_) ;_; and_CC it_PPH1 is_VBZ suitable_JJ for_IF high_JJ level_JJ governance_NN1 and_CC control_NN1 (_( Gaynor_NP1 ,_, 2002_MC ;_; Hardy_NP1 ,_, 2006_MC )_) ._. 
</s>
<s>
However_RR ,_, observations_NN2 by_II Ridley_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2008_MC )_) suggest_VV0 that_CST in_II31 spite_II32 of_II33 increasing_JJ popularity_NN1 and_CC applicability_NN1 of_IO COBIT_NP1 ,_, it_PPH1 has_VHZ received_VVN very_RG limited_JJ empirical_JJ and_CC theoretical_JJ support_NN1 from_II academia_NN1 and_CC little_RR academic_JJ attention_NN1 has_VHZ been_VBN devoted_VVN to_II investigation_NN1 of_IO utilization_NN1 of_IO COBIT_NP1 (_( Ridley_NP1 et_RA21 al._RA22 ,_, 2004_MC )_) ._. 
</s>
<s>
This_DD1 term_NN1 paper_NN1 will_VM collect_VVI the_AT issues_NN2 and_CC the_AT results_NN2 of_IO different_JJ academic_JJ research_NN1 studies_NN2 and_CC try_VV0 to_TO form_VVI a_AT1 general_JJ portrait_NN1 of_IO concepts_NN2 ,_, methods_NN2 ,_, and_CC applicability_NN1 of_IO COBIT_NP1 framework_NN1 for_IF control_NN1 and_CC auditing_VVG purposes_NN2 so_BCL21 as_BCL22 to_TO gather_VVI the_AT evidence_NN1 whether_CSW COBIT_NP1 can_VM be_VBI useful_JJ tool_NN1 for_IF auditors_NN2 and_CC internal_JJ controllers_NN2 ._. 
</s>
<s>
Thus_RR ,_, the_AT term_NN1 paper_NN1 will_VM provide_VVI a_AT1 contribution_NN1 to_II the_AT theoretical_JJ studies_NN2 in_II the_AT field_NN1 ._. 
</s>
<s>
The_AT preference_NN1 will_VM be_VBI given_VVN to_II the_AT scientific_JJ articles_NN2 published_VVN in_II peer-reviewed_JJ journals_NN2 ._. 
</s>
<s>
The_AT articles_NN2 will_VM be_VBI selected_VVN in_II a_AT1 manner_NN1 that_CST they_PPHS2 discuss_VV0 the_AT problem_NN1 under_II the_AT investigation_NN1 from_II different_JJ perspectives_NN2 ._. 
</s>
<s>
The_AT reminder_NN1 of_IO this_DD1 paper_NN1 is_VBZ divided_VVN into_II three_MC content_JJ sections_NN2 ._. 
</s>
<s>
The_AT following_JJ section_NN1 outlines_NN2 the_AT development_NN1 and_CC the_AT general_JJ concepts_NN2 of_IO the_AT framework_NN1 ._. 
</s>
<s>
The_AT third_MD part_NN1 will_VM survey_VVI the_AT applicability_NN1 of_IO the_AT framework_NN1 ,_, based_VVN on_II the_AT review_NN1 of_IO the_AT literature_NN1 ._. 
</s>
<s>
The_AT content_JJ section_NN1 four_MC closes_VVZ this_DD1 term_NN1 paper_NN1 with_IW conclusions_NN2 and_CC guidelines_NN2 for_IF future_JJ research_NN1 in_II this_DD1 area_NN1 ._. 
</s>
<s>
2_MC Framework_NN1 Frameworks_NN2 are_VBR widely_RR used_VVN by_II organizations_NN2 and_CC auditors_NN2 in_BCL21 order_BCL22 to_TO guide_VVI the_AT design_NN1 and_CC evaluation_NN1 of_IO internal_JJ controls_NN2 ._. 
</s>
<s>
Especially_RR ,_, the_AT role_NN1 and_CC applicability_NN1 of_IO internal_JJ control_NN1 frameworks_NN2 has_VHZ grown_VVN in_II importance_NN1 after_II the_AT release_NN1 of_IO the_AT SarbanesOxley_NP1 Act_NN1 of_IO 2002_MC and_CC Auditing_VVG Standard_JJ No._NN1 2_MC (_( AS2_FO )_) in_II 2004_MC ._. 
</s>
<s>
Historical_JJ development_NN1 In_II 1996_MC the_AT Information_NN1 Systems_NN2 Audit_NN1 and_CC Control_NN1 Foundation_NN1 (_( ISACF_NP1 )_) published_VVD the_AT Control_NN1 Objectives_NN2 for_IF Information_NN1 and_CC Related_JJ Technology_NN1 (_( COBIT_NP1 )_) ._. 
</s>
<s>
ISACF_NP1 was_VBDZ founded_VVN in_II 1969_MC by_II a_AT1 group_NN1 of_IO IT_NN1 auditors_NN2 ._. 
</s>
<s>
Currently_RR ,_, this_DD1 organization_NN1 is_VBZ known_VVN as_II Information_NN1 Systems_NN2 Audit_NN1 and_CC Control_NN1 Association_NN1 (_( ISACA_NP1 )_) and_CC is_VBZ a_AT1 global_JJ organization_NN1 with_IW over_RG 50_MC 000_MC members_NN2 in_II more_DAR than_CSN 140_MC countries_NN2 ._. 
</s>
<s>
COBIT_NP1 was_VBDZ developed_VVN in_II the_AT response_NN1 to_II growing_JJ need_NN1 for_IF control_NN1 within_II IT_NN1 organizations_NN2 and_CC at_II that_DD1 point_NN1 lacking_VVG network_NN1 of_IO information_NN1 and_CC guidance_NN1 in_II the_AT industry_NN1 ._. 
</s>
<s>
As_II the_AT role_NN1 of_IO IT_NN1 continuing_VVG to_TO increase_VVI ,_, in_II 1998_MC ISACA_NP1 established_VVD separate_JJ institute_NN1 ,_, the_AT IT_NN1 Governance_NN1 Institute_NN1 (_( ITGI_NP1 )_) ,_, who_PNQS is_VBZ responsible_JJ for_IF COBIT_NN1 ._. 
</s>
<s>
Initially_RR ,_, COBIT_NP1 was_VBDZ developed_VVN as_II a_AT1 tool_NN1 to_TO control_VVI IT_NN1 and_CC reduce_VVI risks_NN2 within_II IT_NN1 organizations_NN2 and_CC was_VBDZ aimed_VVN at_II finance_NN1 and_CC e-business_JJ industries_NN2 ._. 
</s>
<s>
However_RR ,_, with_IW time_NNT1 it_PPH1 took_VVD more_DAR business_NN1 oriented_VVD course_NN1 and_CC nowadays_RT it_PPH1 provides_VVZ an_AT1 essential_JJ guidance_NN1 to_II management_NN1 and_CC process_VV0 owners_NN2 on_II how_RRQ to_TO optimize_VVI resources_NN2 and_CC asset_NN1 allocation_NN1 and_CC what_DDQ should_VM be_VBI done_VDN within_II an_AT1 organization_NN1 to_TO achieve_VVI the_AT goals_NN2 ._. 
</s>
<s>
The_AT second_MD edition_NN1 of_IO COBIT_NP1 was_VBDZ released_VVN in_II 1998_MC ._. 
</s>
<s>
This_DD1 version_NN1 was_VBDZ enhanced_VVN by_II new_JJ material_NN1 on_II IT_NN1 Governance_NN1 and_CC Management_NN1 Guidelines_NN2 and_CC released_VVN as_CSA third_MD edition_NN1 in_II 2000_MC ._. 
</s>
<s>
The_AT current_JJ version_NN1 ,_, fourth_MD ,_, was_VBDZ released_VVN in_II 2005_MC ._. 
</s>
<s>
ISACA_NP1 claims_VVZ that_CST organizations_NN2 benefit_NN1 of_IO using_VVG COBIT_NN1 because_CS it_PPH1 helps_VVZ to_TO understand_VVI their_APPGE IT_NN1 systems_NN2 and_CC determine_VVI the_AT optimum_JJ level_NN1 of_IO security_NN1 and_CC control_VV0 that_DD1 is_VBZ required_VVN to_TO protect_VVI organizations_NN2 assets_NN2 through_II the_AT implementation_NN1 of_IO IT_NN1 control_NN1 model_NN1 ._. 
</s>
<s>
Damianides_NN2 (_( 2004_MC )_) in_II this_DD1 respect_NN1 carried_VVD out_RP the_AT case_NN1 study_NN1 at_II Charles_NP1 Schwab_NP1 Corporation_NN1 ,_, one_MC1 of_IO largest_JJT U.S._NP1 financial_JJ services_NN2 firms_NN2 ,_, and_CC investigated_VVD what_DDQ benefits_NN2 company_NN1 achieved_VVN by_II implementing_VVG COBIT_NN1 ._. 
</s>
<s>
Besides_II the_AT advantages_NN2 of_IO established_JJ IT_NN1 governance_NN1 program_NN1 ,_, consistent_JJ risk_NN1 management_NN1 and_CC enhanced_JJ IT_NN1 and_CC business_NN1 processes_NN2 ,_, it_PPH1 also_RR ensured_VVD that_DD1 audit_NN1 approach_NN1 is_VBZ consistent_JJ with_IW regulatory_JJ guidelines_NN2 ,_, it_PPH1 educated_JJ stakeholders_NN2 on_II control_NN1 concepts_NN2 ,_, and_CC improved_JJ information_NN1 systems_NN2 control_VV0 environment_NN1 ._. 
</s>
<s>
Concept_NN1 and_CC methodology_NN1 COBIT_NN1 is_VBZ based_VVN on_II the_AT concept_NN1 that_CST IT_PPH1 has_VHZ to_TO provide_VVI the_AT information_NN1 that_CST is_VBZ crucial_JJ for_IF the_AT organization_NN1 in_BCL21 order_BCL22 to_TO achieve_VVI its_APPGE objectives_NN2 ._. 
</s>
<s>
The_AT framework_NN1 serves_VVZ as_II a_AT1 high_JJ level_JJ guidance_NN1 for_IF management_NN1 and_CC business_NN1 process_NN1 owners_NN2 ._. 
</s>
<s>
Under_II this_DD1 framework_NN1 ,_, all_DB business_NN1 processes_NN2 have_VH0 assigned_VVN owners_NN2 ;_; meanwhile_RR business_NN1 process_NN1 owners_NN2 have_VH0 total_JJ responsibility_NN1 for_IF all_DB aspects_NN2 of_IO the_AT business_NN1 processes_NN2 ,_, but_CCB COBIT_NP1 promotes_VVZ a_AT1 process_NN1 focus_NN1 and_CC process_VV0 ownership_NN1 through_II adequate_JJ controls_NN2 ._. 
</s>
<s>
The_AT framework_NN1 is_VBZ based_VVN on_II three_MC separate_JJ documents_NN2 :_: Control_NN1 Objectives_NN2 ,_, that_DD1 describes_VVZ the_AT 34_MC processes_NN2 and_CC the_AT control_NN1 objectives_NN2 to_II each_DD1 process_NN1 employed_VVN by_II COBIT_NP1 ._. 
</s>
<s>
The_AT COBIT_NN1 control_NN1 objectives_NN2 are_VBR divided_VVN into_II four_MC domains_NN2 that_CST describe_VV0 the_AT risks_NN2 and_CC activities_NN2 within_II IT_NN1 that_CST need_VV0 to_TO be_VBI managed_VVN ._. 
</s>
<s>
The_AT four_MC COBIT_NN1 domains_NN2 are_VBR :_: Plan_VV0 and_CC Organize_VV0 ,_, Acquire_VV0 and_CC Implement_NN1 ,_, Deliver_VV0 and_CC Support_NN1 and_CC Monitor_NN1 and_CC Evaluate_VV0 ,_, and_CC they_PPHS2 provide_VV0 an_AT1 understanding_NN1 of_IO the_AT purpose_NN1 of_IO the_AT processes_NN2 ._. 
</s>
<s>
The_AT domains_NN2 are_VBR divided_VVN into_II 34_MC different_JJ high_JJ level_JJ control_NN1 objectives_NN2 ._. 
</s>
<s>
Within_II each_DD1 domain_NN1 there_EX are_VBR specific_JJ processes_NN2 that_CST an_AT1 institution_NN1 should_VM apply_VVI at_II different_JJ levels_NN2 of_IO the_AT IT_NN1 organization_NN1 in_BCL21 order_BCL22 to_TO address_VVI and_CC achieve_VVI detailed_JJ and_CC specific_JJ IT_NN1 related_JJ control_NN1 objectives_NN2 ._. 
</s>
<s>
Each_DD1 process_NN1 comprises_VVZ detailed_JJ control_NN1 objectives_NN2 ,_, activities_NN2 ,_, roles_NN2 ,_, different_JJ metrics_NN2 and_CC a_AT1 measurement_NN1 scale_NN1 ._. 
</s>
<s>
The_AT roles_NN2 consider_VV0 responsibilities_NN2 that_CST are_VBR associated_VVN with_IW activities_NN2 ._. 
</s>
<s>
Control_VV0 Objectives_NN2 The_AT owner_NN1 of_IO the_AT framework_NN1 ,_, ITGI_NP1 ,_, defines_VVZ control_NN1 as_II the_AT policies_NN2 ,_, procedures_NN2 ,_, practices_NN2 and_CC organizational_JJ structures_NN2 designed_VVN to_TO provide_VVI reasonable_JJ assurance_NN1 that_CST business_NN1 objectives_NN2 will_VM be_VBI achieved_VVN and_CC that_DD1 undesired_JJ events_NN2 will_VM be_VBI prevented_VVN or_CC detected_VVD and_CC corrected_VVN ._. 
</s>
<s>
Whereas_CS IT_NN1 Control_NN1 Objective_NN1 is_VBZ a_AT1 statement_NN1 of_IO the_AT desired_JJ result_NN1 or_CC purpose_NN1 to_TO be_VBI achieved_VVN by_II implementing_VVG control_NN1 procedures_NN2 in_II a_AT1 particular_JJ IT_NN1 activity_NN1 ._. 
</s>
<s>
Organizations_NN2 need_VV0 information_NN1 in_BCL21 order_BCL22 to_TO satisfy_VVI their_APPGE business_NN1 objectives_NN2 ;_; moreover_RR ,_, the_AT information_NN1 has_VHZ to_TO follow_VVI certain_JJ criteria_NN2 ._. 
</s>
<s>
In_II the_AT framework_NN1 ,_, COBIT_NP1 combines_VVZ the_AT principles_NN2 embedded_VVN in_II existing_JJ and_CC known_JJ reference_NN1 models_NN2 and_CC establishes_VVZ the_AT list_NN1 of_IO the_AT business_NN1 requirements_NN2 for_IF information_NN1 ._. 
</s>
<s>
These_DD2 requirements_NN2 concern_VV0 quality_NN1 ,_, fiduciary_NN1 ,_, reliability_NN1 ,_, and_CC security_NN1 ._. 
</s>
<s>
Control_VV0 objectives_NN2 are_VBR concerned_JJ with_IW the_AT IT_NN1 resources_NN2 ,_, which_DDQ are_VBR identified_VVN in_II COBIT_NP1 as_CSA data_NN in_II its_APPGE broadest_JJT sense_NN1 ,_, application_NN1 systems_NN2 (_( both_DB2 manual_JJ and_CC programmed_VVD procedures_NN2 )_) ,_, technology_NN1 in_II a_AT1 sense_NN1 of_IO hardware_NN1 ,_, operating_NN1 systems_NN2 ,_, database_NN1 management_NN1 systems_NN2 ,_, networking_VVG ,_, multimedia_NN ,_, facilities_NN2 for_IF housing_VVG and_CC supporting_JJ information_NN1 systems_NN2 ,_, and_CC people_NN ,_, accommodating_VVG staff_NN skills_NN2 ,_, awareness_NN1 and_CC productivity_NN1 to_TO plan_VVI ,_, organize_VV0 ,_, acquire_VV0 ,_, deliver_VV0 ,_, support_NN1 and_CC monitor_VV0 information_NN1 systems_NN2 and_CC services_NN2 ._. 
</s>
<s>
COBIT_NP1 defines_VVZ high-level_JJ control_NN1 objectives_NN2 for_IF each_DD1 process_NN1 for_IF identifying_VVG important_JJ information_NN1 criteria_NN2 ,_, stating_VVG resource_NN1 requirement_NN1 ,_, and_CC providing_VVG guidelines_NN2 for_IF IT_NN1 processes_NN2 controls_VVZ ._. 
</s>
<s>
Each_DD1 high-level_JJ control_NN1 objective_NN1 is_VBZ supplemented_VVN by_II detailed_JJ control_NN1 objectives_NN2 ,_, 318_MC in_II all_DB ,_, explaining_VVG how_RRQ control_NN1 should_VM be_VBI carried_VVN out_RP over_II that_DD1 particular_JJ process_NN1 and_CC how_RRQ objectives_NN2 should_VM be_VBI built_VVN ._. 
</s>
<s>
The_AT underlying_JJ theory_NN1 for_IF the_AT classification_NN1 of_IO the_AT control_NN1 objectives_NN2 is_VBZ based_VVN on_II the_AT approach_NN1 that_CST there_EX are_VBR three_MC levels_NN2 of_IO IT_NN1 efforts_NN2 when_CS considering_VVG the_AT management_NN1 of_IO IT_NN1 resources_NN2 ._. 
</s>
<s>
The_AT first_MD layer_NN1 is_VBZ activities_NN2 and_CC tasks_NN2 that_CST are_VBR needed_VVN to_TO achieve_VVI a_AT1 measurable_JJ result_NN1 ._. 
</s>
<s>
Processes_NN2 are_VBR then_RT defined_VVN on_II the_AT second_MD level_NN1 and_CC combine_VV0 sequences_NN2 of_IO joined_JJ activities_NN2 or_CC tasks_NN2 ._. 
</s>
<s>
At_II the_AT third_MD level_JJ processes_NN2 are_VBR grouped_VVN together_RL into_II domains_NN2 where_CS they_PPHS2 correspond_VV0 with_IW responsibility_NN1 areas_NN2 in_II an_AT1 organizational_JJ structure_NN1 and_CC are_VBR coherent_JJ IT_NN1 processes_NN2 lifecycle_NN1 ._. 
</s>
<s>
The_AT conceptual_JJ framework_NN1 is_VBZ approached_VVN from_II three_MC vantage_NN1 points_VVZ :_: IT-processes_NN2 (_( domains_NN2 ,_, processes_NN2 ,_, activities_NN2 )_) ,_, IT-resources_NN2 (_( people_NN ,_, applications/systems_NN2 ,_, technology_NN1 ,_, facilities_NN2 ,_, data_NN )_) and_CC information_NN1 criteria_NN2 (_( quality_NN1 ,_, fiduciary_NN1 ,_, security_NN1 )_) ._. 
</s>
<s>
3_MC Applicability_NN1 Frameworks_NN2 are_VBR helpful_JJ tools_NN2 to_TO be_VBI used_VVN in_II the_AT assessment_NN1 of_IO internal_JJ controls_NN2 because_CS they_PPHS2 give_VV0 structure_NN1 to_II the_AT control_NN1 process_NN1 ,_, conceptualize_VV0 the_AT most_RGT important_JJ aspects_NN2 of_IO the_AT control_NN1 ,_, and_CC make_VV0 assessment_NN1 more_RGR reliable_JJ and_CC complete_JJ ._. 
</s>
<s>
This_DD1 is_VBZ particularly_RR valuable_JJ in_II information_NN1 technology_NN1 concentrated_JJ surroundings_NN2 when_RRQ systems_NN2 ,_, processes_NN2 ,_, and_CC organization_NN1 increase_NN1 in_II their_APPGE complexity_NN1 and_CC auditors_NN2 need_VV0 plans_NN2 to_II structure_NN1 their_APPGE work_NN1 ,_, and_CC when_CS due_II21 to_II22 the_AT changes_NN2 in_II legislations_NN2 more_RRR and_CC more_DAR emphasis_NN1 has_VHZ been_VBN placed_VVN on_II information_NN1 controls_NN2 ._. 
</s>
<s>
Tuttle_NP1 and_CC Vandervelde_NP1 (_( 2007_MC )_) refer_VV0 to_II prior_JJ field_NN1 studies_NN2 by_II Fedorowitz_NP1 and_CC Gelinas_NP2 (_( 1998_MC )_) and_CC Lainhart_NP1 (_( 2001_MC )_) ,_, which_DDQ claim_VV0 that_DD1 COBIT_NN1 can_VM be_VBI used_VVN for_IF internal_JJ controls_NN2 assessment_NN1 and_CC corporate_JJ governance_NN1 ,_, and_CC empirically_RR examine_VV0 the_AT conceptual_JJ model_NN1 underlying_JJ COBIT_NN1 for_IF its_APPGE applicability_NN1 to_II an_AT1 audit_NN1 setting_NN1 and_CC whether_CSW it_PPH1 can_VM guide_VVI auditors_NN2 during_II assessment_NN1 of_IO internal_JJ controls_NN2 and_CC their_APPGE compliance_NN1 with_IW COSO_NN1 requirements_NN2 ._. 
</s>
<s>
Auditors_NN2 and_CC internal_JJ controllers_NN2 have_VH0 been_VBN referring_VVG to_TO COBIT_VVI as_II a_AT1 tool_NN1 to_TO supplement_VVI COSO_NN1 ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO support_VVI COBIT_NN1 as_II an_AT1 IT_NN1 internal_JJ control_NN1 framework_NN1 for_IF an_AT1 audit_NN1 function_NN1 ,_, Tuttle_NP1 and_CC Vandervelde_NP1 (_( 2007_MC )_) use_VV0 COBIT_NN1 assessment_NN1 constructs_NN2 provided_VVN by_II panel_NN1 of_IO experts_NN2 and_CC supplemented_VVN by_II postings_NN2 from_II the_AT Information_NN1 Systems_NN2 audit_NN1 and_CC Control_NN1 Assocoations_NN2 general_JJ listserv_NN1 ._. 
</s>
<s>
So_BCL21 as_BCL22 to_TO strengthen_VVI their_APPGE study_NN1 findings_NN2 and_CC produce_VVI consistent_JJ and_CC compelling_JJ evidence_NN1 ,_, the_AT authors_NN2 used_VVD two_MC separate_JJ data_NN sources_NN2 ,_, survey_NN1 data_NN and_CC archival_JJ data_NN ,_, to_TO examine_VVI whether_CSW COBIT_NP1 is_VBZ capable_JJ to_TO support_VVI operational_JJ ,_, compliance_NN1 ,_, and_CC financial_JJ auditing_NN1 ._. 
</s>
<s>
The_AT findings_NN2 from_II the_AT study_NN1 suggest_VV0 that_CST COBIT_VV0 framework_NN1 can_VM be_VBI used_VVN for_IF risk_NN1 assessment_NN1 of_IO the_AT process_NN1 ._. 
</s>
<s>
It_PPH1 also_RR can_VM be_VBI used_VVN for_IF providing_VVG help_NN1 to_II auditors_NN2 during_II IT_NN1 auditing_NN1 ._. 
</s>
<s>
Therefore_RR ,_, COBIT_NP1 could_VM be_VBI viewed_VVN as_II an_AT1 appropriate_JJ supplement_NN1 to_II COSO_NP1 and_CC in_II an_AT1 IT_NN1 setting_NN1 ._. 
</s>
<s>
However_RR ,_, the_AT final_JJ results_NN2 also_RR revealed_VVN that_CST the_AT framework_NN1 is_VBZ not_XX capable_JJ to_TO support_VVI some_DD of_IO items_NN2 of_IO the_AT distinct_JJ dimensions_NN2 ._. 
</s>
<s>
Chan_NP1 (_( 2004_MC )_) argues_VVZ that_CST COBIT_NP1 is_VBZ in_II31 line_II32 with_II33 SOX_NN2 requirements_NN2 for_IF compliance_NN1 efforts_NN2 ,_, control_VV0 activities_NN2 and_CC information_NN1 and_CC communication_NN1 demands_NN2 ;_; therefore_RR it_PPH1 serves_VVZ auditors_NN2 as_II a_AT1 helpful_JJ tool_NN1 in_II auditing_VVG IT_NN1 in_II compliance_NN1 with_IW SOX_NN2 ._. 
</s>
<s>
Lin_NP1 ,_, Guan_NP1 ,_, and_CC Fang_NN1 (_( 2010_MC )_) carry_VV0 out_RP the_AT study_NN1 where_CS they_PPHS2 empirically_RR investigate_VV0 whether_CSW COBIT_NP1 can_VM provide_VVI an_AT1 adequate_JJ support_NN1 for_IF auditors_NN2 in_II evaluating_VVG IT_NN1 internal_JJ control_NN1 structures_NN2 ._. 
</s>
<s>
The_AT data_NN was_VBDZ collected_VVN through_II sending_VVG out_RP 925_MC questionnaires_NN2 to_II Taiwanese_JJ certified_JJ public_JJ accountant_NN1 firms_NN2 ._. 
</s>
<s>
In_II the_AT final_JJ analysis_NN1 128_MC (_( 13,84%_NNU )_) questionnaires_NN2 were_VBDR used_VVN ._. 
</s>
<s>
The_AT paper_NN1 provides_VVZ evidence_NN1 that_CST auditors_NN2 can_VM use_VVI COBIT_NN1 as_CSA guidelines_NN2 when_RRQ developing_JJ approach_NN1 for_IF internal_JJ control_NN1 structure_NN1 as_II31 well_II32 as_II33 adopting_VVG COBIT_NP1 helps_VVZ in_II complying_VVG with_IW SOX_NN2 ._. 
</s>
<s>
However_RR ,_, an_AT1 important_JJ observation_NN1 made_VVN by_II the_AT authors_NN2 is_VBZ that_CST auditors_NN2 who_PNQS use_VV0 COBIT_NN1 should_VM have_VHI greater_JJR IT_NN1 knowledge_NN1 and_CC should_VM have_VHI received_VVN better_RRR technical_JJ training_NN1 ._. 
</s>
<s>
The_AT IT_NN1 Process_NN1 Institute_NN1 (_( 2006_MC )_) carried_VVD out_RP a_AT1 survey_NN1 and_CC investigated_VVD whether_CSW IT_PPH1 controls_VVZ can_VM improve_VVI audit_NN1 and_CC internal_JJ control_NN1 activities_NN2 ._. 
</s>
<s>
The_AT study_NN1 surveyed_VVD respondents_NN2 from_II 98_MC IT_NN1 organizations_NN2 and_CC covered_VVD many_DA2 industries_NN2 ._. 
</s>
<s>
The_AT survey_NN1 questions_NN2 were_VBDR designed_VVN so_RR to_TO support_VVI analysis_NN1 of_IO COBIT_NP1 control_NN1 activities_NN2 and_CC audit_NN1 performance_NN1 measures_NN2 ._. 
</s>
<s>
The_AT evidence_NN1 obtained_VVD was_VBDZ consistent_JJ with_IW expectations_NN2 that_CST control_VV0 activities_NN2 if_CS they_PPHS2 are_VBR designed_VVN in_II31 line_II32 with_II33 COBIT_NP1 framework_NN1 ,_, have_VH0 significant_JJ impact_NN1 on_II audit_NN1 measures_NN2 and_CC control_NN1 activities_NN2 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, the_AT results_NN2 of_IO the_AT study_NN1 also_RR revealed_VVN that_CST if_CS applied_VVN ,_, the_AT best_JJT practices_NN2 outlined_VVN in_II the_AT COBIT_NN1 framework_NN1 do_VD0 improve_VVI overall_JJ performance_NN1 measures_NN2 of_IO the_AT organization_NN1 ._. 
</s>
<s>
4_MC Discussion_NN1 and_CC conclusion_NN1 COBIT_NN1 is_VBZ an_AT1 international_JJ and_CC generally_RR accepted_JJ IT_NN1 control_NN1 framework_NN1 supporting_VVG institutions_NN2 during_II implementation_NN1 of_IO IT_NN1 Governance_NN1 concepts_NN2 covering_VVG the_AT entire_JJ organization_NN1 ._. 
</s>
<s>
The_AT framework_NN1 has_VHZ been_VBN adopted_VVN in_II corporations_NN2 and_CC by_II governmental_JJ entities_NN2 throughout_II the_AT world_NN1 ._. 
</s>
<s>
Initially_RR ,_, its_APPGE purpose_NN1 was_VBDZ to_TO assist_VVI management_NN1 in_II aligning_VVG control_NN1 objectives_NN2 with_IW business_NN1 goals_NN2 ,_, but_CCB recently_RR the_AT framework_NN1 has_VHZ been_VBN gaining_VVG more_DAR attention_NN1 from_II auditors_NN2 and_CC internal_JJ controllers_NN2 as_CSA has_VHZ been_VBN found_VVN valuable_JJ in_II assisting_VVG IT_NN1 managers_NN2 and_CC consultants_NN2 to_TO evaluate_VVI the_AT state_NN1 of_IO internal_JJ control_NN1 and_CC to_TO manage_VVI IT_PPH1 related_JJ risks_NN2 in_II the_AT organization_NN1 ._. 
</s>
<s>
One_MC1 of_IO the_AT reasons_NN2 why_RRQ the_AT framework_NN1 besides_II its_APPGE main_JJ intentions_NN2 has_VHZ been_VBN also_RR used_VVN for_IF other_JJ purposes_NN2 ,_, like_II internal_JJ controls_NN2 and_CC auditing_NN1 ,_, is_VBZ that_DD1 released_JJ SOX_NN2 and_CC COSO_NP1 require_VV0 that_CST organizations_NN2 implement_VV0 an_AT1 appropriate_JJ controls_NN2 ,_, but_CCB did_VDD not_XX provide_VVI a_AT1 guidance_NN1 or_CC endorsed_VVD a_AT1 specific_JJ IT_NN1 control_NN1 framework_NN1 on_II what_DDQ and_CC how_RRQ should_VM be_VBI controlled_VVN ._. 
</s>
<s>
Therefore_RR auditors_NN2 and_CC management_NN1 were_VBDR looking_VVG for_IF tools_NN2 that_CST could_VM provide_VVI the_AT required_JJ support_NN1 and_CC COBIT_NP1 was_VBDZ one_MC1 of_IO those_DD2 ._. 
</s>
<s>
The_AT evidence_NN1 provided_VVN by_II academic_JJ studies_NN2 generally_RR support_VV0 COBIT_NN1 as_II a_AT1 control_NN1 and_CC audit_NN1 framework_NN1 ;_; however_RR ,_, it_PPH1 has_VHZ been_VBN argued_VVN that_CST COBIT_NP1 does_VDZ not_XX adequately_RR consider_VVI the_AT environment_NN1 around_II the_AT organization_NN1 (_( Tuttle_NP1 and_CC Vandervelde_NP1 ,_, 2007_MC )_) as_II the_AT variables_NN2 associated_VVN with_IW the_AT competitive_JJ ,_, legal_JJ and_CC economic_JJ environment_NN1 around_II the_AT organization_NN1 might_VM impact_VVI the_AT IT_NN1 processes_NN2 ,_, but_CCB they_PPHS2 are_VBR not_XX addressed_VVN through_II associated_JJ listeserv_NN1 postings_NN2 ._. 
</s>
<s>
This_DD1 has_VHZ been_VBN noted_VVN as_II a_AT1 weakness_NN1 within_II the_AT security_NN1 issues_NN2 in_II COBIT_NP1 (_( Tuttle_NP1 and_CC Vandervelde_NP1 ,_, 2007_MC )_) ._. 
</s>
<s>
The_AT reason_NN1 could_VM be_VBI related_VVN to_II the_AT circumstances_NN2 ,_, that_CST COBIT_VV0 actually_RR was_VBDZ not_XX intended_VVN to_TO be_VBI an_AT1 auditing_NN1 framework_NN1 or_CC control_NN1 framework_NN1 ;_; instead_RR it_PPH1 was_VBDZ developed_VVN as_II a_AT1 tool_NN1 for_IF managing_JJ IT_NN1 so_CS21 that_CS22 it_PPH1 best_RRT complies_VVZ with_IW organizations_NN2 business_NN1 goals_NN2 ._. 
</s>
<s>
COBIT_NP1 is_VBZ built_VVN so_CS21 that_CS22 it_PPH1 incorporates_VVZ the_AT best_JJT practices_NN2 for_IF a_AT1 company_NN1 ,_, however_RR ,_, that_DD1 does_VDZ not_XX oblige_VVI them_PPHO2 to_TO coincide_VVI with_IW auditing_VVG perspective_NN1 ._. 
</s>
<s>
Another_DD1 aspect_NN1 that_CST researchers_NN2 ask_VV0 to_TO pay_VVI attention_NN1 ,_, one_MC1 example_NN1 is_VBZ study_NN1 by_II Abu-Musa_NP1 (_( 2008_MC )_) ,_, is_VBZ auditor_NN1 skills_NN2 in_II auditing_VVG IT_NN1 processes_NN2 on_II objectives_NN2 ._. 
</s>
<s>
Abu-Musa_NP1 (_( 2008_MC )_) calls_VVZ for_IF the_AT need_NN1 to_TO enhance_VVI internal_JJ auditors_NN2 knowledge_NN1 and_CC skills_NN2 of_IO computerized_JJ information_NN1 systems_NN2 in_BCL21 order_BCL22 to_TO be_VBI capable_JJ to_TO plan_VVI ,_, direct_JJ ,_, supervise_VV0 and_CC review_VVI the_AT work_NN1 performed_VVD ._. 
</s>
<s>
Currently_RR ,_, it_PPH1 leads_VVZ to_II the_AT situation_NN1 when_CS internal_JJ auditors_NN2 focus_VV0 primarily_RR on_II traditional_JJ IT_NN1 risks_NN2 and_CC controls_NN2 ,_, such_II21 as_II22 IT_NN1 data_NN integrity_NN1 ,_, privacy_NN1 and_CC security_NN1 ,_, and_CC insufficient_JJ attention_NN1 has_VHZ been_VBN directed_VVN to_II information_NN1 system_NN1 risks_NN2 per_RR21 se_RR22 ._. 
</s>
<s>
Thus_RR ,_, one_PN1 might_VM not_XX obtain_VVI all_DB possible_JJ benefits_NN2 that_CST COBIT_VV0 as_II a_AT1 control_NN1 framework_NN1 provides_VVZ ._. 
</s>
<s>
In_II31 spite_II32 of_II33 COBIT_NP1 as_II a_AT1 framework_NN1 has_VHZ been_VBN getting_VVG attention_NN1 from_II practitioners_NN2 and_CC has_VHZ been_VBN advised_VVN to_TO use_VVI as_II a_AT1 basis_NN1 for_IF internal_JJ control_NN1 theory_NN1 development_NN1 ,_, this_DD1 topic_NN1 has_VHZ been_VBN lacking_VVG attention_NN1 from_II academics_NN2 ._. 
</s>
<s>
Ridley_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2004_MC )_) performed_VVD extensive_JJ literature_NN1 review_NN1 and_CC summarized_VVD findings_NN2 and_CC research_NN1 efforts_NN2 relevant_JJ to_TO COBIT_VVI and_CC reported_VVD that_CST only_RR 7%_NNU of_IO publications_NN2 are_VBR classified_VVN as_CSA having_VHG an_AT1 academic_JJ orientation_NN1 ._. 
</s>
<s>
Council_NN1 (_( 2006_MC )_) also_RR argued_VVN that_CST despite_II myriad_NN1 literature_NN1 on_II COBIT_NP1 ,_, very_RG little_DA1 rigorous_JJ research_NN1 exists_VVZ ._. 
</s>
<s>
Ridley_NN1 and_CC coauthors_NN2 (_( 2004_MC )_) speculate_VV0 that_CST it_PPH1 might_VM be_VBI because_CS the_AT electronic_JJ sources_NN2 available_JJ on_II COBIT_NP1 are_VBR primarily_RR designed_VVN for_IF IT_NN1 and_CC audit_NN1 practitioners_NN2 ._. 
</s>
<s>
Knowledge_NN1 creation_NN1 about_II COBIT_NP1 conceptual_JJ framework_NN1 is_VBZ important_JJ for_IF three_MC target_NN1 audiences_NN2 ._. 
</s>
<s>
First_MD ,_, users_NN2 of_IO the_AT framework_NN1 ,_, who_PNQS have_VH0 to_TO know_VVI if_CSW the_AT underlying_JJ conceptual_JJ model_NN1 is_VBZ reliable_JJ ._. 
</s>
<s>
Second_MD ,_, auditors_NN2 ,_, accounting_VVG firms_NN2 ,_, and_CC policy-makers_NN2 who_PNQS need_VV0 evidence_NN1 which_DDQ either_RR supports_VVZ or_CC rejects_VVZ the_AT conceptual_JJ foundation_NN1 of_IO auditing_VVG practices_NN2 ._. 
</s>
<s>
Third_MD ,_, it_PPH1 could_VM assist_VVI in_II developing_VVG internal_JJ control_NN1 theory_NN1 ,_, as_CSA no_AT academic_JJ theory_NN1 of_IO internal_JJ control_NN1 exists_VVZ so_RG far_RR ._. 
</s>
<s>
Considering_CS21 that_CS22 COBIT_NP1 has_VHZ been_VBN widely_RR used_VVN as_II an_AT1 auditing_NN1 framework_NN1 and_CC scarce_JJ number_NN1 of_IO academic_JJ studies_NN2 about_II the_AT framework_NN1 and_CC its_APPGE implications_NN2 ,_, there_EX is_VBZ clear_JJ demand_NN1 for_IF such_DA studies_NN2 ._. 
</s>
<s>
Tuttle_NP1 and_CC Vandervelde_NP1 (_( 2007_MC )_) call_VV0 for_IF developing_VVG an_AT1 exhaustive_JJ ,_, substantiate_VV0 ,_, real-world_JJ related_JJ ,_, and_CC generally_RR accepted_JJ theory_NN1 of_IO IT_NN1 controls_NN2 ._. 
</s>
<s>
The_AT relevant_JJ topics_NN2 could_VM cover_VVI control_NN1 shortages_NN2 and_CC aspects_NN2 of_IO IT_NN1 audit_NN1 risks_NN2 ._. 
</s>
