<s>
Corporate_JJ Social_JJ Responsibility_NN1 in_II Icelandic_JJ banks_NN2 Introduction_NN1 The_AT level_NN1 of_IO Social_JJ Responsibility_NN1 (_( CSR_NP1 )_) in_II Icelandic_JJ banks_NN2 is_VBZ the_AT field_NN1 of_IO this_DD1 study_NN1 ._. 
</s>
<s>
CSR_NP1 has_VHZ become_VVN a_AT1 popular_JJ way_NN1 for_IF corporations_NN2 to_TO portray_VVI their_APPGE interest_NN1 in_II their_APPGE stakeholders_NN2 and_CC the_AT society_NN1 they_PPHS2 coexist_VV0 in_RP ._. 
</s>
<s>
It_PPH1 is_VBZ interesting_JJ to_TO examine_VVI the_AT Icelandic_JJ financial_JJ sector_NN1 mainly_RR due_II21 to_II22 two_MC factors_NN2 ._. 
</s>
<s>
Firstly_RR ,_, there_EX are_VBR only_RR four_MC banks_NN2 in_II Iceland_NP1 ,_, all_DB of_IO similar_JJ size_NN1 ;_; therefore_RR it_PPH1 is_VBZ easy_JJ to_TO compare_VVI them_PPHO2 ._. 
</s>
<s>
Secondly_RR ,_, the_AT Icelandic_JJ financial_JJ system_NN1 came_VVD to_II a_AT1 complete_JJ halt_NN1 in_II the_AT autumn_NNT1 of_IO 2009_MC ,_, and_CC the_AT banks_NN2 have_VH0 tried_VVN to_TO establish_VVI trust_NN1 with_IW society_NN1 ever_RR since_RR ._. 
</s>
<s>
Research_NN1 on_II CSR_NP1 in_II Iceland_NP1 has_VHZ been_VBN quite_RG scarce_JJ ;_; the_AT few_DA2 researches_NN2 that_CST have_VH0 been_VBN made_VVN do_VDI point_VVI to_II the_AT fact_NN1 that_CST Iceland_NP1 is_VBZ a_AT1 part_NN1 of_IO the_AT European_JJ Economic_JJ Area_NN1 (_( EEA_NP1 )_) and_CC complies_VVZ with_IW many_DA2 EU_NP1 directives_NN2 ,_, therefore_RR environmental_JJ and_CC social_JJ standards_NN2 are_VBR in_II31 line_II32 with_II33 EU_NP1 countries_NN2 ._. 
</s>
<s>
Research_NN1 has_VHZ revealed_VVN a_AT1 lack_NN1 of_IO CSR_NP1 plans_VVZ in_II Icelandic_JJ companies_NN2 (_( Thorsteinsdottir_NP1 ,_, CSR_NP1 in_II Iceland_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
However_RR ,_, according_II21 to_II22 a_AT1 study_NN1 made_VVN by_II the_AT European_JJ Commission_NN1 in_II 2002_MC ,_, philanthropy_NN1 is_VBZ a_AT1 common_JJ practice_NN1 by_II Icelandic_JJ companies_NN2 (_( European_JJ Commission_NN1 ,_, 2002_MC ,_, p._NN1 20_MC )_) ._. 
</s>
<s>
Previous_JJ researches_NN2 have_VH0 focused_VVN on_II the_AT Icelandic_JJ market_NN1 as_II a_AT1 whole_NN1 ,_, but_CCB not_XX the_AT financial_JJ sector_NN1 ._. 
</s>
<s>
Since_CS the_AT financial_JJ sector_NN1 is_VBZ very_RG dependent_JJ on_II good_JJ international_JJ relations_NN2 and_CC foreign_JJ investment_NN1 ;_; a_AT1 logical_JJ assumption_NN1 might_VM be_VBI that_CST they_PPHS2 should_VM be_VBI innovative_JJ in_II developing_VVG their_APPGE CSR_NP1 policies_NN2 ,_, but_CCB are_VBR they_PPHS2 ?_? 
</s>
<s>
How_RGQ far_RR have_VH0 the_AT Icelandic_JJ banks_NN2 come_VV0 in_II developing_VVG their_APPGE CSR_NP1 plans_VVZ ?_? 
</s>
<s>
Where_RRQ do_VD0 they_PPHS2 stand_VVI compared_VVN with_IW other_JJ European_JJ banks_NN2 ?_? 
</s>
<s>
The_AT main_JJ purpose_NN1 of_IO this_DD1 research_NN1 is_VBZ to_TO Compare_VV0 the_AT 4_MC Icelandic_JJ banks_NN2 of_IO Arion_NN1 banki_NN2 ,_, slandsbanki_NN2 ,_, Landsbankinn_NP1 and_CC MP_NN1 banki_NN2 ,_, to_TO evaluate_VVI the_AT level_NN1 of_IO their_APPGE CSR_NP1 plans_NN2 ._. 
</s>
<s>
Once_CS the_AT Icelandic_JJ banks_NN2 have_VH0 been_VBN evaluated_VVN they_PPHS2 can_VM be_VBI compared_VVN with_IW the_AT benchmark_NN1 ,_, Deutsche_NP1 bank_NN1 which_DDQ is_VBZ a_AT1 leading_JJ organization_NN1 in_II CSR_NP1 ._. 
</s>
<s>
This_DD1 paper_NN1 hopes_VVZ to_TO show_VVI that_DD1 Icelandic_JJ banks_NN2 are_VBR well_JJ ahead_RL in_II their_APPGE social_JJ responsibilities_NN2 ,_, but_CCB lack_VV0 a_AT1 formal_JJ policy_NN1 ._. 
</s>
<s>
The_AT importance_NN1 of_IO this_DD1 policy_NN1 will_VM also_RR be_VBI explained_VVN ._. 
</s>
<s>
The_AT remainder_NN1 of_IO this_DD1 paper_NN1 is_VBZ structured_VVN as_CSA follows_VVZ ;_; the_AT first_MD section_NN1 is_VBZ a_AT1 theoretical_JJ introduction_NN1 as_II21 to_II22 which_DDQ theories_NN2 this_DD1 research_NN1 is_VBZ built_VVN on_RP ._. 
</s>
<s>
The_AT second_MD section_NN1 is_VBZ the_AT main_JJ body_NN1 ,_, where_CS I_PPIS1 discuss_VV0 the_AT background_NN1 of_IO the_AT Icelandic_JJ banks_NN2 up_JJ31 to_JJ32 date_JJ33 ,_, the_AT methodology_NN1 of_IO the_AT research_NN1 and_CC current_JJ state_NN1 of_IO the_AT research_NN1 field_NN1 ._. 
</s>
<s>
The_AT third_MD part_NN1 consists_VVZ of_IO the_AT results_NN2 and_CC the_AT fourth_MD section_NN1 holds_VVZ the_AT conclusions_NN2 of_IO the_AT study_NN1 ._. 
</s>
<s>
Theoretical_JJ part_NN1 CSR_NP1 and_CC the_AT Pyramid_NN1 of_IO CSR_NP1 Globalization_NN1 has_VHZ given_VVN cause_NN1 for_IF a_AT1 unified_JJ international_JJ standard_NN1 of_IO ethics_NN and_CC socially_RR sustainable_JJ companies_NN2 ._. 
</s>
<s>
Consumers_NN2 want_VV0 to_TO know_VVI how_RRQ their_APPGE products_NN2 are_VBR made_VVN on_II the_AT other_JJ side_NN1 of_IO the_AT planet_NN1 ._. 
</s>
<s>
Governments_NN2 and_CC international_JJ institutions_NN2 are_VBR involved_VVN by_II regulating_VVG and_CC establishing_VVG guidelines_NN2 and_CC standards_NN2 for_IF companies_NN2 to_TO follow_VVI ._. 
</s>
<s>
The_AT European_JJ Union_NN1 has_VHZ become_VVN very_RG concerned_JJ with_IW the_AT social_JJ aspect_NN1 of_IO companies_NN2 in_II the_AT Union_NN1 ._. 
</s>
<s>
Defining_VVG Corporate_JJ Social_JJ Responsibility_NN1 has_VHZ been_VBN a_AT1 constant_JJ battle_NN1 between_II academics_NN2 in_II the_AT last_MD 50_MC years_NNT2 ._. 
</s>
<s>
The_AT Pyramid_NN1 of_IO CSR_NP1 by_II Archie_NP1 Carroll_NP1 (_( 1979_MC )_) gives_VVZ a_AT1 good_JJ overview_NN1 of_IO the_AT matter_NN1 ._. 
</s>
<s>
In_II fact_NN1 it_PPH1 is_VBZ the_AT basis_NN1 for_IF the_AT most_RGT recognized_JJ definition_NN1 up_JJ31 to_JJ32 date_JJ33 ._. 
</s>
<s>
CSR_NP1 encompasses_VVZ the_AT economic_JJ ,_, legal_JJ ethical_JJ ,_, and_CC discretionary_JJ or_CC philanthropic_JJ expectations_NN2 that_CST society_NN1 has_VHZ of_IO organizations_NN2 at_II a_AT1 given_JJ point_NN1 in_II time._NNU (_( Carroll_NP1 ,_, 1979_MC )_) Economical_JJ Responsibilities_NN2 :_: The_AT most_RGT important_JJ thing_NN1 in_II corporate_JJ existence_NN1 is_VBZ to_TO be_VBI profitable_JJ ,_, otherwise_RR it_PPH1 will_VM cease_VVI to_TO exist_VVI or_CC cause_NN1 damage_NN1 to_II society_NN1 ._. 
</s>
<s>
Legal_JJ Responsibilities_NN2 :_: whilst_CS making_VVG a_AT1 profit_NN1 ,_, corporations_NN2 must_VM obey_VVI the_AT law_NN1 ,_, so_RR society_NN1 may_VM function_VVI ._. 
</s>
<s>
Ethical_JJ Responsibilities_NN2 :_: as_CSA being_VBG a_AT1 profitable_JJ and_CC law_NN1 abiding_JJ corporation_NN1 ,_, a_AT1 corporation_NN1 must_VM be_VBI ethical_JJ ,_, fundamentally_RR that_DD1 means_VVZ doing_VDG right_RR by_II stakeholders_NN2 and_CC society_NN1 ._. 
</s>
<s>
Finally_RR ,_, Philanthropic_JJ Responsibilities_NN2 :_: to_TO be_VBI a_AT1 good_JJ corporate_JJ citizen_NN1 improving_VVG the_AT life_NN1 of_IO others_NN2 by_II distributing_VVG company_NN1 resources_NN2 ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) ISO_NP1 26000_MC The_AT International_JJ Organization_NN1 for_IF Standardization_NN1 or_CC ISO_NP1 which_DDQ is_VBZ the_AT largest_JJT standards_NN2 publisher_NN1 in_II the_AT world_NN1 has_VHZ formed_VVN an_AT1 International_JJ guidance_NN1 mechanism_NN1 of_IO CSR_NP1 ,_, called_VVN ISO_NP1 26000_MC ._. 
</s>
<s>
It_PPH1 does_VDZ not_XX provide_VVI regulation_NN1 or_CC a_AT1 certification_NN1 of_IO standard_NN1 ._. 
</s>
<s>
The_AT ISO_NP1 26000_MC is_VBZ a_AT1 guideline_NN1 for_IF companies_NN2 that_CST wish_VV0 to_TO develop_VVI and_CC establish_VVI a_AT1 sustainable_JJ CSR_NP1 policy_NN1 ._. 
</s>
<s>
All_DB companies_NN2 regardless_RR their_APPGE scope_NN1 ,_, size_NN1 or_CC type_NN1 can_VM use_VVI the_AT guidelines_NN2 ._. 
</s>
<s>
First_MD they_PPHS2 must_VM get_VVI familiar_JJ with_IW the_AT terms_NN2 and_CC definitions_NN2 of_IO CSR_NP1 and_CC understand_VV0 the_AT history_NN1 and_CC characteristics_NN2 as_II31 well_II32 as_II33 the_AT relationship_NN1 between_II CSR_NP1 and_CC sustainable_JJ development_NN1 ._. 
</s>
<s>
There_EX are_VBR seven_MC principles_NN2 of_IO social_JJ responsibility_NN1 to_TO follow_VVI at_II the_AT early_JJ stages_NN2 of_IO the_AT development_NN1 ,_, they_PPHS2 are_VBR :_: 1_MC1 ._. 
</s>
<s>
Accountability_NN1 2_MC ._. 
</s>
<s>
Transparency_NN1 3_MC ._. 
</s>
<s>
Ethical_JJ behaviour_NN1 4_MC ._. 
</s>
<s>
Respect_NN1 for_IF stakeholder_NN1 interest_NN1 5_MC ._. 
</s>
<s>
Respect_NN1 for_IF the_AT rule_NN1 of_IO law_NN1 6_MC ._. 
</s>
<s>
Respect_NN1 for_IF international_JJ norms_NN2 of_IO behaviour_NN1 7_MC ._. 
</s>
<s>
Respect_NN1 for_IF human_JJ rights_NN2 The_AT ISO_NP1 26000_MC guideline_NN1 builds_VVZ on_II fundamentals_NN2 and_CC 7_MC core_NN1 subjects_NN2 that_CST are_VBR recommended_VVN for_IF companies_NN2 to_TO focus_VVI on_RP when_CS building_VVG their_APPGE programme_NN1 ._. 
</s>
<s>
According_II21 to_II22 ISO_NP1 26000_MC there_EX are_VBR two_MC fundamental_JJ practices_NN2 of_IO social_JJ responsibilities_NN2 each_DD1 company_NN1 must_VM identify_VVI ._. 
</s>
<s>
First_MD ,_, recognizing_VVG social_JJ responsibility_NN1 ,_, and_CC second_NNT1 ,_, to_TO identify_VVI and_CC engage_VVI stakeholders_NN2 ._. 
</s>
<s>
Then_RT the_AT company_NN1 can_VM focus_VVI on_II the_AT core_NN1 subjects_NN2 ._. 
</s>
<s>
The_AT core_NN1 subjects_NN2 are_VBR :_: 1_MC1 ._. 
</s>
<s>
Organizational_JJ Governance_NN1 2_MC ._. 
</s>
<s>
Human_JJ rights_NN2 3_MC ._. 
</s>
<s>
Labour_JJ practices_NN2 4_MC ._. 
</s>
<s>
The_AT environment_NN1 5_MC ._. 
</s>
<s>
Fair_JJ operating_NN1 practices_NN2 6_MC ._. 
</s>
<s>
Consumer_NN1 Issues_NN2 7_MC ._. 
</s>
<s>
Community_NN1 involvement_NN1 and_CC development_NN1 Finally_RR the_AT integration_NN1 of_IO the_AT social_JJ responsibility_NN1 policy_NN1 can_VM begin_VVI ,_, in_BCL21 order_BCL22 to_TO do_VDI so_RR the_AT company_NN1 must_VM take_VVI care_NN1 of_IO the_AT communication_NN1 ,_, relationships_NN2 and_CC characteristics_NN2 within_II the_AT company_NN1 ._. 
</s>
<s>
Ensuring_VVG understanding_NN1 about_II social_JJ responsibility_NN1 for_IF all_DB stakeholders_NN2 ,_, making_VVG voluntary_JJ initiatives_NN2 and_CC enhancing_VVG credibility_NN1 is_VBZ important_JJ ._. 
</s>
<s>
Reviewing_VVG and_CC improving_VVG the_AT companys_NN2 actions_NN2 and_CC practices_NN2 is_VBZ then_RT an_AT1 ongoing_JJ process_NN1 (_( http_NNU :_: //www.iso.org_FU ,_, 2012_MC )_) ._. 
</s>
<s>
UN_NP1 Global_JJ Compact_NN1 The_AT United_JJ Nations_NN2 Global_JJ Compact_NN1 is_VBZ a_AT1 strategic_JJ policy_NN1 initiative_NN1 for_IF businesses_NN2 that_CST are_VBR committed_VVN to_II aligning_VVG their_APPGE operations_NN2 and_CC strategies_NN2 with_IW ten_MC universally_RR accepted_JJ principles_NN2 in_II the_AT areas_NN2 of_IO human_JJ rights_NN2 ,_, labour_NN1 ,_, environment_NN1 and_CC anti-corruption._JJ The_AT compact_NN1 is_VBZ an_AT1 attempt_NN1 to_TO build_VVI a_AT1 universal_JJ code_NN1 of_IO CSR_NP1 that_CST aims_VVZ to_TO manage_VVI the_AT risks_NN2 and_CC opportunities_NN2 in_II environmental_JJ ,_, social_JJ end_NN1 governance_NN1 structures_NN2 ._. 
</s>
<s>
With_IW close_JJ to_II 9000_MC participants_NN2 the_AT compact_NN1 is_VBZ voluntary_JJ ,_, but_CCB to_TO prove_VVI their_APPGE commitment_NN1 a_AT1 yearly_JJ Communication_NN1 on_II Progress_NN1 (_( COP_NN1 )_) must_VM be_VBI posted_VVN by_II the_AT company_NN1 to_TO ensure_VVI transparency_NN1 and_CC accountability_NN1 amongst_II the_AT participants_NN2 ._. 
</s>
<s>
The_AT ten_MC universal_JJ principles_NN2 the_AT UN_NP1 Compact_NN1 is_VBZ built_VVN on_RP are_VBR divided_VVN into_II four_MC sections_NN2 :_: human_JJ rights_NN2 ,_, labour_NN1 ,_, environment_NN1 and_CC anti-corruption_JJ ._. 
</s>
<s>
(_( UN_NP1 Global_JJ Compact_NN1 )_) Methods_NN2 In_BCL21 order_BCL22 to_TO investigate_VVI the_AT level_NN1 of_IO CSR_NP1 in_II the_AT Icelandic_JJ banks_NN2 I_PPIS1 compared_VVD the_AT information_NN1 on_II their_APPGE websites_NN2 with_IW the_AT Deutsche_NP1 bank_NN1 website_NN1 ._. 
</s>
<s>
The_AT banks_NN2 in_II question_NN1 ,_, Arion_NP1 banki_NN2 ,_, slandsbanki_NN2 ,_, Landsbankinn_NP1 and_CC MP_NN1 banki_NN2 were_VBDR therefore_RR the_AT sample_NN1 and_CC Deutsche_NP1 bank_VV0 the_AT benchmark_NN1 ._. 
</s>
<s>
First_MD I_PPIS1 determined_VVD the_AT main_JJ issues_NN2 of_IO CSR_NP1 in_II the_AT Deutsche_NP1 bank_NN1 CSR_NP1 policy_NN1 and_CC made_VVD a_AT1 questionnaire_NN1 ._. 
</s>
<s>
The_AT questionnaire_NN1 was_VBDZ also_RR in_II close_JJ relations_NN2 with_IW the_AT emphasis_NN1 of_IO Archie_NP1 Carrolls_NP2 Pyramid_NN1 of_IO CSR_NP1 ._. 
</s>
<s>
Each_DD1 question_NN1 could_VM give_VVI either_RR 1_MC1 or_CC 3_MC points_NN2 ,_, bringing_VVG the_AT total_NN1 to_II 29_MC points_NN2 ._. 
</s>
<s>
If_CS the_AT answers_NN2 were_VBDR not_XX positive_JJ ,_, 0_MC points_NN2 were_VBDR given_VVN ._. 
</s>
<s>
Next_MD the_AT comparison_NN1 of_IO total_JJ points_NN2 was_VBDZ given_VVN and_CC what_DDQ it_PPH1 possibly_RR means_VVZ for_IF these_DD2 banks_NN2 ._. 
</s>
<s>
Finally_RR ,_, a_AT1 more_RGR detailed_JJ review_NN1 was_VBDZ given_VVN on_II each_DD1 bank_NN1 and_CC what_DDQ fields_NN2 they_PPHS2 should_VM focus_VVI on_RP when_CS building_VVG up_RP their_APPGE CSR_NP1 policy_NN1 ._. 
</s>
<s>
Questionnaire_NN1 When_CS comparing_VVG the_AT banks_NN2 and_CC the_AT level_NN1 they_PPHS2 are_VBR at_II in_II CSR_NP1 development_NN1 I_PPIS1 decided_VVD to_TO compare_VVI them_PPHO2 with_IW a_AT1 bank_NN1 that_CST has_VHZ been_VBN internationally_RR accredited_VVN for_IF its_APPGE CSR_NP1 policy_NN1 worldwide_RL ,_, Deutsche_NP1 bank_NN1 ._. 
</s>
<s>
Deutsche_NP1 bank_NN1 has_VHZ a_AT1 sophisticated_JJ and_CC honoured_VVD CSR_NP1 policy_NN1 ._. 
</s>
<s>
The_AT bank_NN1 receives_VVZ multiple_JJ awards_NN2 every_AT1 year_NNT1 for_IF its_APPGE socially_RR responsible_JJ projects_NN2 ._. 
</s>
<s>
After_II studying_VVG their_APPGE website_NN1 ,_, http_NNU :_: //www.db.com/csr_VV0 ,_, I_PPIS1 established_VVD a_AT1 questionnaire_NN1 that_CST would_VM cover_VVI the_AT main_JJ issues_NN2 the_AT CSR_NP1 policy_NN1 of_IO Deutsche_NP1 bank_NN1 has_VHZ ._. 
</s>
<s>
Each_DD1 question_NN1 can_VM give_VVI 1_MC1 point_NN1 ._. 
</s>
<s>
However_RR ,_, the_AT most_RGT important_JJ questions_NN2 in_II this_DD1 study_NN1 are_VBR nr._II 1,2_MC ,_, and_CC ,_, 3_MC ,_, therefore_RR they_PPHS2 will_VM give_VVI 3_MC points_VVZ each_DD1 ,_, if_CS answered_VVN positively_RR ._. 
</s>
<s>
1_MC1 ._. 
</s>
<s>
Is_VBZ there_EX an_AT1 official_JJ CSR_NP1 policy_NN1 ?_? 2_MC ._. 
</s>
<s>
Do_VD0 they_PPHS2 comply_VVI with_IW the_AT International_JJ Organization_NN1 for_IF Standardization_NN1 's_GE guidelines_NN2 for_IF social_JJ responsibility_NN1 (_( ISO_NP1 26000_MC )_) 3_MC ._. 
</s>
<s>
Do_VD0 they_PPHS2 comply_VVI with_IW the_AT principles_NN2 of_IO the_AT UN_NP1 's_GE Global_JJ Compact_NN1 ?_? 4_MC ._. 
</s>
<s>
Is_VBZ there_EX a_AT1 sustainability_NN1 plan_NN1 ?_? a-Environmental_JJ issues_NN2 b-Social_JJ issues_NN2 c-Governance_JJ issues_NN2 5_MC ._. 
</s>
<s>
Do_VD0 they_PPHS2 have_VHI an_AT1 education_NN1 program_NN1 ?_? a-Domestic_NN1 b-International_JJ 6_MC ._. 
</s>
<s>
Do_VD0 they_PPHS2 participate_VVI in_II social_JJ investments_NN2 ?_? a-Environmental_JJ investments_NN2 b-Poverty_JJ c-Health_JJ d-Disaster_JJ zones_NN2 7_MC ._. 
</s>
<s>
Do_VD0 they_PPHS2 support_VVI Art_NN1 and_CC Music_NN1 in_II the_AT community_NN1 ?_? 8_MC ._. 
</s>
<s>
Do_VD0 they_PPHS2 support_VVI athletes_NN2 ?_? 9_MC ._. 
</s>
<s>
Do_VD0 they_PPHS2 support_VVI employee_NN1 engagement_NN1 ?_? a-society_NN1 b-environment_JJ c-education_JJ d-healthy_JJ living_NN1 10_MC ._. 
</s>
<s>
Do_VD0 they_PPHS2 participate_VVI in_II Innovation_NN1 grants/support_FU ?_? 
</s>
<s>
Results_NN2 and_CC Interpretation_NN1 Landsbankinn-results_NN2 and_CC improvement_NN1 Landsbankinn_NP1 recieved_VVD 22/29_MF points_NN2 and_CC scored_VVD the_AT best_RRT out_II21 of_II22 the_AT Icelandic_JJ banks_NN2 ._. 
</s>
<s>
An_AT1 interpretation_NN1 of_IO the_AT 7_MC points_NN2 missing_VVG is_VBZ necessary_JJ to_TO understand_VVI the_AT level_NN1 of_IO CSR_NP1 in_II Landsbankinn_NP1 ._. 
</s>
<s>
The_AT lack_NN1 of_IO a_AT1 sustainability_NN1 policy_NN1 on_II the_AT website_NN1 might_VM be_VBI work_NN1 in_II progress_NN1 ._. 
</s>
<s>
The_AT fact_NN1 that_CST nothing_PN1 is_VBZ available_JJ on_II governance_NN1 issues_NN2 is_VBZ something_PN1 that_CST should_VM be_VBI improved_VVN ._. 
</s>
<s>
Landsbankinn_NN1 does_VDZ not_XX support_VVI education_NN1 on_II an_AT1 international_JJ level_NN1 and_CC is_VBZ quite_RG understandable_JJ ,_, due_II21 to_II22 the_AT fact_NN1 that_CST the_AT country_NN1 is_VBZ still_RR in_II the_AT midst_NN1 of_IO an_AT1 international_JJ crisis_NN1 ,_, and_CC is_VBZ receiving_VVG financial_JJ aid_NN1 from_II IMF_NP1 ,_, focusing_VVG on_II domestic_JJ ground_NN1 is_VBZ understandable_JJ and_CC justifiable_JJ ._. 
</s>
<s>
The_AT same_DA can_VM be_VBI said_VVN regarding_II disaster_NN1 zones_NN2 which_DDQ are_VBR not_XX mentioned_VVN in_II the_AT policy_NN1 ._. 
</s>
<s>
Support_VV0 to_II athletes_NN2 ,_, art_NN1 and_CC music_NN1 is_VBZ not_XX a_AT1 part_NN1 of_IO their_APPGE CSR_NP1 policy_NN1 but_CCB may_VM be_VBI a_AT1 preference_NN1 or_CC an_AT1 attempt_NN1 to_TO differentiate_VVI the_AT bank_NN1 from_II Islandsbanki_NP1 ._. 
</s>
<s>
Landsbanki_NP1 does_VDZ support_VVI the_AT involvement_NN1 of_IO their_APPGE employees_NN2 but_CCB they_PPHS2 are_VBR missing_VVG direct_JJ societal_JJ projects_NN2 ._. 
</s>
<s>
This_DD1 involves_VVZ employees_NN2 doing_VDG philanthropic_JJ aid_NN1 in_II their_APPGE own_DA free_JJ time_NNT1 or_CC finding_VVG sustainable_JJ ways_NN2 for_IF the_AT bank_NN1 to_TO assist_VVI or_CC support_VVI individuals_NN2 and_CC projects_NN2 ._. 
</s>
<s>
This_DD1 could_VM be_VBI an_AT1 opportunity_NN1 for_IF improvement_NN1 ,_, but_CCB perhaps_RR this_DD1 is_VBZ deliberate_JJ ._. 
</s>
<s>
It_PPH1 may_VM not_XX be_VBI considered_VVN appropriate_JJ whilst_CS economical_JJ problems_NN2 are_VBR still_RR the_AT main_JJ issue_NN1 to_TO focus_VVI on_II these_DD2 matters_NN2 ._. 
</s>
<s>
All_DB in_II all_DB Landsbankinn_NP1 has_VHZ an_AT1 official_JJ and_CC genuine_JJ policy_NN1 but_CCB it_PPH1 is_VBZ yet_RR work_VV0 in_II progress_NN1 ._. 
</s>
<s>
To_TO have_VHI a_AT1 complete_JJ policy_NN1 I_PPIS1 believe_VV0 Landsbankinn_NP1 should_VM focus_VVI on_II their_APPGE sustainability_NN1 policy_NN1 which_DDQ according_II21 to_II22 the_AT ISO_NP1 26000_MC is_VBZ the_AT ultimate_JJ goal_NN1 for_IF having_VHG a_AT1 CSR_NP1 policy_NN1 ._. 
</s>
<s>
Once_CS their_APPGE sustainability_NN1 policy_NN1 has_VHZ been_VBN published_VVN they_PPHS2 need_VV0 to_TO emphasize_VVI their_APPGE compliance_NN1 with_IW governance_NN1 codes_NN2 ._. 
</s>
<s>
Without_IW governance_NN1 codes_NN2 international_JJ investors_NN2 might_VM be_VBI confused_VVN and_CC uneasy_JJ ._. 
</s>
<s>
There_EX is_VBZ of_RR21 course_RR22 room_NN1 for_IF improvement_NN1 in_II supporting_JJ areas_NN2 but_CCB mostly_RR in_II supporting_VVG and_CC developing_JJ employee_NN1 involvement_NN1 in_II their_APPGE society_NN1 (_( Landsbankinn_NP1 )_) ._. 
</s>
<s>
Islandsbanki_NN2 and_CC improvement_NN1 Islandsbanki_NN1 scored_VVN 19/29_MF points_NN2 ._. 
</s>
<s>
Islandsbanki_NP1 has_VHZ not_XX followed_VVN the_AT ISO_NP1 26000_MC guidelines_NN2 and_CC that_DD1 is_VBZ the_AT main_JJ difference_NN1 between_II Landsbanki_NP1 and_CC Islandsbanki_NP1 ._. 
</s>
<s>
Islandsbanki_NP1 has_VHZ no_AT education_NN1 support_NN1 in_II their_APPGE policy_NN1 ;_; this_DD1 is_VBZ an_AT1 area_NN1 where_CS the_AT bank_NN1 can_VM extend_VVI their_APPGE policy_NN1 especially_RR domestic_JJ support_NN1 in_II the_AT form_NN1 of_IO scholarships_NN2 ._. 
</s>
<s>
No_AT support_NN1 to_II disaster_NN1 zones_NN2 is_VBZ quite_RG understandable_JJ as_CSA in_II Landsbankinn_NP1 ._. 
</s>
<s>
The_AT lack_NN1 of_IO governance_NN1 codes_NN2 is_VBZ also_RR a_AT1 concern_NN1 but_CCB could_VM easily_RR be_VBI improved_VVN ._. 
</s>
<s>
Islandsbanki_NP1 emphasizes_VVZ employee_NN1 involvement_NN1 in_II all_DB areas_NN2 and_CC is_VBZ obviously_RR the_AT leading_JJ bank_NN1 in_II employee_NN1 involvement_NN1 (_( Islandsbanki_NP1 )_) ._. 
</s>
<s>
MP_NN1 banki_NN2 and_CC Arion_NN1 banki_NN2 and_CC improvement_NN1 Both_DB2 banks_NN2 scored_VVN 0/29_MF points_NN2 ._. 
</s>
<s>
Social_JJ responsibility_NN1 is_VBZ not_XX mentioned_VVN in_II their_APPGE website_NN1 ._. 
</s>
<s>
Conclusion_NN1 and_CC Discussions_NN2 Deutsche_NP1 bank_NN1 is_VBZ an_AT1 international_JJ company_NN1 with_IW over_RG 100,000_MC employees_NN2 working_VVG in_II 70_MC countries_NN2 ._. 
</s>
<s>
That_DD1 is_VBZ almost_RR one_MC1 third_MD of_IO the_AT Icelandic_JJ population_NN1 ._. 
</s>
<s>
This_DD1 fact_NN1 must_VM be_VBI taken_VVN into_II account_NN1 when_CS comparing_VVG the_AT CSR_NP1 policies_NN2 of_IO these_DD2 banks_NN2 with_IW Deutsche_NP1 bank_NN1 ._. 
</s>
<s>
That_DD1 is_VBZ why_RRQ I_PPIS1 tried_VVD to_TO have_VHI the_AT questionnaire_NN1 broad_JJ and_CC kept_VVD to_TO key_VVI issues_NN2 ._. 
</s>
<s>
My_APPGE opinion_NN1 is_VBZ that_CST a_AT1 comprehensive_JJ CSR_NP1 plan_NN1 is_VBZ necessary_JJ and_CC doable_JJ for_IF all_DB companies_NN2 regardless_RR of_IO their_APPGE size_NN1 ._. 
</s>
<s>
MP_NN1 bank_NN1 and_CC Arion_NP1 have_VH0 no_AT official_JJ policy_NN1 ,_, no_AT ethical_JJ standards_NN2 and_CC do_VD0 not_XX participate_VVI in_II any_DD philanthropic_JJ projects_NN2 ._. 
</s>
<s>
This_DD1 was_VBDZ surprising_JJ since_CS CSR_NP1 is_VBZ a_AT1 very_RG popular_JJ topic_NN1 today_RT and_CC Icelandic_JJ banks_NN2 are_VBR in_II dire_JJ need_NN1 of_IO strengthening_VVG their_APPGE reputation_NN1 ._. 
</s>
<s>
Does_VDZ this_DD1 have_VHI an_AT1 influence_NN1 on_II employees_NN2 ,_, customers_NN2 and_CC other_JJ stakeholders_NN2 ?_? 
</s>
<s>
It_PPH1 would_VM be_VBI very_RG interesting_JJ to_TO examine_VVI whether_CSW this_DD1 affects_VVZ ROE_NN ._. 
</s>
<s>
Does_VDZ a_AT1 CSR_NP1 policy_NN1 have_VH0 a_AT1 positive_JJ effect_NN1 on_II the_AT financial_JJ side_NN1 ?_? 
</s>
<s>
Does_VDZ this_DD1 have_VHI an_AT1 influence_NN1 on_II stakeholders_NN2 ?_? 
</s>
<s>
Is_VBZ there_EX pressure_NN1 from_II stakeholders_NN2 to_TO invest_VVI in_II a_AT1 CSR_NP1 policy_NN1 ?_? 
</s>
<s>
It_PPH1 is_VBZ fair_JJ to_TO say_VVI that_CST there_EX is_VBZ a_AT1 great_JJ difference_NN1 in_II the_AT level_NN1 of_IO CSR_NP1 amongst_II the_AT Icelandic_JJ banks_NN2 ._. 
</s>
<s>
Landsbankinn_VV0 and_CC Islandsbanki_NP1 have_VH0 developed_VVN internationally_RR approved_VVD CSR_NP1 policies_NN2 and_CC are_VBR compatible_JJ with_IW their_APPGE fellow_JJ banks_NN2 in_II Europe_NP1 ._. 
</s>
<s>
However_RRQV Arion_NN1 banki_NN2 and_CC MP_NN1 banki_NN2 have_VH0 a_AT1 long_JJ way_NN1 to_TO go_VVI ._. 
</s>
