<s>
Developing_JJ insurance_NN1 packages_NN2 for_IF young_JJ adults_NN2 Are_VBR and_CC inexpensive_JJ services_NN2 the_AT key_JJ to_TO appeal_VVI to_II young_JJ customers_NN2 ?_? 
</s>
<s>
Introduction_NN1 In_II recent_JJ years_NNT2 ,_, insurances_NN2 have_VH0 been_VBN marketed_VVN to_II customers_NN2 with_IW various_JJ types_NN2 of_IO advertisements_NN2 ,_, campaigns_NN2 and_CC promotions_NN2 ,_, and_CC often_RR the_AT focus_NN1 has_VHZ been_VBN on_II communication_NN1 of_IO the_AT benefits_NN2 that_CST canbe_VV0 achieved_VVN with_IW the_AT insurances_NN2 ._. 
</s>
<s>
Although_CS home_NN1 insurance_NN1 is_VBZ perhaps_RR the_AT most_RGT common_JJ type_NN1 ofinsurances_NN2 ,_, still_RR many_DA2 Finnish_JJ people_NN especially_RR the_AT young_JJ adults_NN2 have_VH0 not_XX insured_VVN their_APPGE house_NN1 orapartment_NN1 with_IW a_AT1 home_NN1 insurance_NN1 (_( Kervinen_NP1 ,_, 2009_MC )_) ._. 
</s>
<s>
The_AT research_NN1 by_II insurance_NN1 company_NN1 TrygVesta(2009)_FO suggests_VVZ that_CST the_AT poor_JJ reputation_NN1 of_IO the_AT insurance_NN1 industry_NN1 might_VM affect_VVI that_DD1 young_JJ adults_NN2 donot_VV0 rely_VV0 on_II insurance_NN1 companies_NN2 ,_, and_CC therefore_RR do_VD0 not_XX purchase_VVI insurances_NN2 ;_; and_CC that_DD1 young_JJ adultsregard_NN1 the_AT insurance_NN1 prices_NN2 being_VBG unaffordable_JJ for_IF them_PPHO2 ._. 
</s>
<s>
As_CSA contrary_JJ results_NN2 (_( FinanssialanKeskusliitto_NP1 ,_, 2010_MC )_) have_VH0 been_VBN presented_VVN too_RR ,_, it_PPH1 is_VBZ of_IO great_JJ interest_NN1 to_TO know_VVI ,_, how_RRQ insurancecompanies_NN2 have_VH0 taken_VVN into_II account_NN1 these_DD2 kinds_NN2 of_IO research_NN1 results_NN2 in_II their_APPGE marketing_NN1 for_IF the_AT segmentyoung_JJ adults_NN2 ._. 
</s>
<s>
Therefore_RR ,_, there_EX obviously_RR is_VBZ need_NN1 for_IF a_AT1 contrastive_JJ research_NN1 that_CST examines_VVZ ,_, how_RRQ homeinsurances_NN2 are_VBR marketed_VVN to_II young_JJ adults_NN2 by_II the_AT insurance_NN1 companies_NN2 ._. 
</s>
<s>
As_II the_AT earlier_JJR researches_NN2 havenot_NN1 examined_VVD the_AT marketing_NN1 material_NN1 itself_PPX1 ,_, it_PPH1 is_VBZ still_RR unclear_JJ ,_, how_RRQ the_AT marketing_NN1 material_NN1 is_VBZ designedto_NN1 appeal_NN1 to_II young_JJ adults_NN2 ._. 
</s>
<s>
This_DD1 paper_NN1 examines_VVZ ,_, what_DDQ kind_NN1 of_IO benefits_NN2 ,_, attributes_NN2 and_CC insurance_NN1 packages_NN2 are_VBR presented_VVN in_II theelectronic_JJ marketing_NN1 material_NN1 of_IO three_MC Finnish_JJ insurance_NN1 companies_NN2 (_( Pohjola_NP1 ,_, if_CS and_CC Fennia_NP1 )_) ,_, whoall_NN1 have_VH0 created_VVN special_JJ insurance_NN1 packages_NN2 for_IF young_JJ adults_NN2 ._. 
</s>
<s>
The_AT material_NN1 is_VBZ analysed_VVN qualitativelyto_NN1 be_VBI able_JK to_TO explain_VVI and_CC understand_VVI the_AT motives_NN2 and_CC possible_JJ differences_NN2 in_II the_AT marketing_NN1 material_NN1 ._. 
</s>
<s>
The_AT purpose_NN1 of_IO the_AT study_NN1 is_VBZ to_TO map_VVI ,_, which_DDQ attributes_VVZ the_AT insurance_NN1 companies_NN2 emphasize_VV0 in_II theirmarketing_VVG material_NN1 (_( websites_NN2 ,_, e-catalogues_NN2 ,_, product_NN1 pages_NN2 and_CC online_JJ advertisements_NN2 )_) ,_, and_CC how_RRQ dothey_NN1 motivate_VV0 ,_, why_RRQ young_JJ adults_NN2 should_VM purchase_VVI an_AT1 insurance_NN1 package_NN1 from_II them_PPHO2 ._. 
</s>
<s>
Background_NN1 and_CC research_NN1 aim_NN1 Internet_NN1 has_VHZ made_VVN it_PPH1 possible_JJ for_IF everyone_PN1 to_TO compare_VVI and_CC purchase_VVI any_DD products_NN2 and_CC services_NN2 ._. 
</s>
<s>
Thisapplies_NP1 also_RR to_II financial_JJ services_NN2 ,_, for_REX21 instance_REX22 insurances_NN2 (_( Robertshaw_NP1 2011_MC ,_, 13_MC )_) ._. 
</s>
<s>
Although_CS thepurchase_NN1 of_IO a_AT1 young_JJ adult_NN1 insurance_NN1 package_NN1 is_VBZ very_RG easy_JJ ,_, still_RR many_DA2 households_NN2 lack_VV0 for_IF examplehome_NN1 insurance_NN1 (_( Hakanen_NP1 ,_, 2009_MC )_) ._. 
</s>
<s>
According_II21 to_II22 Hakanen_NP1 38_MC %_NNU of_IO young_JJ adults_NN2 ,_, aged_VVN between_II 18-28_MCMC years_NNT2 ,_, do_VD0 not_XX have_VHI a_AT1 home_NN1 insurance_NN1 and_CC more_DAR than_CSN a_AT1 third_MD do_VD0 not_XX even_RR have_VHI an_AT1 accidentinsurance_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ quite_RG surprising_JJ considering_CS21 that_CS22 life-related_JJ issues_NN2 (_( such_II21 as_II22 unemployment_NN1 ,_, temporary_JJ dismissal_NN1 and_CC disability_NN1 )_) were_VBDR regarded_VVN as_II the_AT most_RGT important_JJ areas_NN2 to_TO be_VBI covered_VVN withinsurances_NN2 among_II the_AT young_JJ people_NN in_II a_AT1 recent_JJ survey_NN1 (_( Vakuutustutkimus_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
It_PPH1 is_VBZ still_RR unclear_JJ ,_, why_RRQ so_RG many_DA2 young_JJ adults_NN2 do_VD0 not_XX buy_VVI a_AT1 home_NN1 insurance_NN1 and_CC other_JJ related_JJ insurances_NN2 ._. 
</s>
<s>
According_II21 to_II22 life_NN1 insurance_NN1 company_NN1 Prudential_NP1 's_GE publishing_NN1 from_II 2011_MC ,_, insurance_NN1 companies_NN2 haveconcentrated_VVD servicing_VVG senior_JJ customers_NN2 ,_, but_CCB the_AT needs_NN2 of_IO their_APPGE children_NN2 (_( generations_NN2 X_ZZ1 and_CC Y_ZZ1 ,_, bornbetween_NN1 1965_MC and_CC 1994_MC )_) have_VH0 been_VBN forgotten_VVN (_( Prudential_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
According_II21 to_II22 TrygVesta_NP1 's_GE research_NN1 (_( in_II Hakanen_NP1 ,_, 2009_MC )_) ,_, Nordic_JJ young_JJ adults_NN2 regard_VV0 insurances_NN2 as_CSA difficult_JJ ,_, indefinite_JJ and_CC complicatedservices_NN2 ._. 
</s>
<s>
The_AT image_NN1 of_IO insurance_NN1 companies_NN2 is_VBZ rather_RG weak_JJ ,_, and_CC over_RG half_DB of_IO the_AT respondents_NN2 inTrygVestas_NN2 research_NN1 believed_VVD that_DD1 insurance_NN1 companies_NN2 would_VM do_VDI anything_PN1 in_II31 case_II32 of_II33 an_AT1 accidentfor_NN1 not_XX need_VV0 to_TO pay_VVI the_AT compensation_NN1 to_II their_APPGE customers_NN2 (_( Kervinen_NP1 ,_, 2009_MC )_) ._. 
</s>
<s>
Therefore_RR young_JJ adultsmight_NN1 not_XX be_VBI eager_JJ to_TO purchase_VVI insurances_NN2 ._. 
</s>
<s>
Another_DD1 reason_NN1 is_VBZ according_II21 to_II22 the_AT Trygvesta_NP1 's_GE researchthat_NN1 young_JJ adults_NN2 feel_VV0 insurances_NN2 being_VBG unaffordable_JJ for_IF them_PPHO2 (_( Kervinen_NP1 ,_, 2009_MC )_) ._. 
</s>
<s>
Federation_NN1 of_IO Finnish_JJ Financial_JJ Services_NN2 (_( FFI_NP1 )_) explores_VVZ every_AT1 fourth_MD year_NNT1 the_AT Finnish_JJ consumersattitudes_NN2 towards_II financial_JJ services_NN2 ._. 
</s>
<s>
The_AT recent_JJ study_NN1 from_II 2010_MC reveals_VVZ that_CST the_AT attitudes_NN2 towardsinsurance_NN1 companies_NN2 have_VH0 improved_VVN compared_VVN to_II the_AT earlier_JJR researchers_NN2 and_CC 69%_NNU of_IO therespondents_NN2 regarded_VVN insurance_NN1 companies_NN2 as_CSA reliable_JJ partners_NN2 to_TO make_VVI a_AT1 commitment_NN1 with_IW ._. 
</s>
<s>
Theamount_NN1 of_IO purchased_JJ home_NN1 insurances_NN2 has_VHZ grown_VVN in_II each_DD1 age_NN1 group_NN1 of_IO Finnish_JJ people_NN ,_, but_CCB still_RR only68%_FO of_IO young_JJ adults_NN2 who_PNQS live_VV0 in_II rented_JJ flats_NN2 ,_, have_VH0 purchased_VVN a_AT1 home_NN1 insurance_NN1 ._. 
</s>
<s>
(_( Vakuutustutkimus_NN1 ,_, 2010_MC ._. )_) 
</s>
<s>
Nevertheless_RR ,_, it_PPH1 is_VBZ somewhat_RR inconsistent_JJ that_CST 90%_NNU of_IO the_AT respondents_NN2 regarded_VVN homeinsurances_NN2 being_VBG an_AT1 important_JJ insurance_NN1 for_IF every_AT1 household_NN1 ._. 
</s>
<s>
As_CSA can_VM be_VBI seen_VVN ,_, there_EX is_VBZ need_NN1 for_IF a_AT1 research_NN1 that_CST explores_VVZ how_RRQ the_AT poor_JJ home_NN1 insurance_NN1 rates_NN2 can_VM beexplained_VVD ._. 
</s>
<s>
The_AT earlier_JJR researchers_NN2 have_VH0 not_XX investigated_VVN whether_CSW the_AT reasons_NN2 for_IF not_XX taking_VVG a_AT1 homeinsurance_NN1 are_VBR price_NN1 and/or_CC policy_NN1 conditions_NN2 related_VVD ._. 
</s>
<s>
Another_DD1 unknown_JJ research_NN1 question_NN1 is_VBZ ,_, whetherinsurance_NN1 companies_NN2 are_VBR miscommunicating_VVG the_AT benefits_NN2 of_IO insurances_NN2 and_CC the_AT company_NN1 image_NN1 thata_NN1 consumer_NN1 could_VM identify_VVI oneself_PNX1 with_IW ._. 
</s>
<s>
The_AT research_NN1 task_NN1 for_IF this_DD1 study_NN1 therefore_RR is_VBZ to_TO identify_VVI the_AT attributes_NN2 in_II insurance_NN1 companies_NN2 homeinsurance_NN1 packages_NN2 '_GE marketing_NN1 that_CST are_VBR not_XX like_JJ to_TO appeal_VVI to_II young_JJ adults_NN2 ._. 
</s>
<s>
The_AT sub_JJ research_NN1 problem_NN1 is_VBZ to_TO evaluate_VVI ,_, whether_CSW insurance_NN1 companies_NN2 have_VH0 priced_VVN themselvesunaffordable_JJ for_IF young_JJ adults_NN2 and_CC whether_CSW the_AT communication_NN1 towards_II young_JJ adults_NN2 is_VBZ ineffectiveand_NN1 difficult_JJ to_TO understand_VVI ._. 
</s>
<s>
The_AT working_JJ hypothesis_NN1 in_II the_AT study_NN1 is_VBZ that_CST the_AT motivations_NN2 could_VM be_VBI price_NN1 related_VVN or_CC have_VH0 to_TO do_VDI withthe_NN1 flaws_NN2 in_II the_AT insurance_NN1 company_NN1 customer_NN1 communication_NN1 ._. 
</s>
<s>
Defining_VVG central_JJ concepts_NN2 and_CC presentation_NN1 of_IO case_NN1 companies_NN2 As_II a_AT1 home_NN1 insurance_NN1 package_NN1 (_( or_CC insurance_NN1 package_NN1 )_) in_II this_DD1 study_NN1 is_VBZ regarded_VVN a_AT1 bundle_NN1 of_IO insuranceservices_NN2 that_CST include_VV0 home_NN1 insurance_NN1 and/or_CC complementing_VVG insurances_NN2 such_II21 as_II22 a_AT1 health_NN1 insurance_NN1 ,_, atravel_VV0 insurance_NN1 or_CC an_AT1 accident_NN1 insurance_NN1 ._. 
</s>
<s>
The_AT customer_NN1 segment_NN1 young_JJ adults_NN2 refers_VVZ to_II a_AT1 group_NN1 of_IO people_NN aged_VVN between_II 18-30_MCMC years_NNT2 ._. 
</s>
<s>
Communication_NN1 refers_VVZ to_II all_DB the_AT customer_NN1 care_NN1 channels_NN2 that_CST insurance_NN1 companies_NN2 in_II Finland_NP1 offerfor_NN1 their_APPGE customers_NN2 ._. 
</s>
<s>
Depending_II21 on_II22 the_AT company_NN1 ,_, the_AT channels_NN2 might_VM include_VVI offices_NN2 or_CC drop-incentres_NN2 ,_, telephone_NN1 service_NN1 ,_, online_JJ services_NN2 and_CC partner_NN1 networks_NN2 ._. 
</s>
<s>
Marketing_NN1 material_NN1 consists_VVZ of_IO electronic_JJ marketing_NN1 and_CC advertisement_NN1 :_: e-brochures_NN2 ,_, web_NN1 servicesand_NN1 web_NN1 catalogues_NN2 and_CC online_JJ advertisements_NN2 and_CC customer_NN1 magazines_NN2 ._. 
</s>
<s>
Case_NN1 companiesPohjola_NN1 is_VBZ a_AT1 part_NN1 of_IO the_AT Op-Pohjola_NP1 group_NN1 and_CC is_VBZ at_II the_AT moment_NN1 the_AT leading_JJ corporate_JJ and_CC public-sector_JJ insurer_NN1 ._. 
</s>
<s>
In_II31 terms_II32 of_II33 premiums_NN2 written_VVN ,_, Pohjola_NP1 is_VBZ the_AT Finnish_JJ largest_JJT insurance_NN1 company_NN1 ._. 
</s>
<s>
(_( Op-Pohjola_NP1 ,_, 2012._MC )_) if_CS is_VBZ the_AT leading_JJ insurer_NN1 in_II the_AT Nordic_JJ countries_NN2 and_CC a_AT1 part_NN1 of_IO the_AT Sampo_NN1 group_NN1 ._. 
</s>
<s>
It_PPH1 has_VHZ approximately3,6_FO million_NNO customers_NN2 (_( if_CS ,_, 2012_MC )_) ._. 
</s>
<s>
Fennia_NN1 is_VBZ a_AT1 part_NN1 of_IO the_AT Fennia_NP1 group_NN1 and_CC offers_NN2 various_JJ insurance_NN1 services_NN2 such_II21 as_II22 life_NN1 ,_, non-life_JJ andpension_NN1 insurances_NN2 (_( Fennia_NP1 ,_, 2012_MC )_) ._. 
</s>
<s>
Structure_NN1 of_IO the_AT studyThe_JJ paper_NN1 is_VBZ divided_VVN into_II three_MC sections_NN2 ._. 
</s>
<s>
The_AT first_MD section_NN1 discusses_VVZ the_AT current_JJ insurance_NN1 offeringfor_NN1 the_AT young_JJ adults_NN2 of_IO the_AT case_NN1 insurance_NN1 companies_NN2 and_CC problematizes_VVZ why_RRQ young_JJ adults_NN2 do_VD0 nottend_VVI to_TO purchase_VVI insurances_NN2 ._. 
</s>
<s>
The_AT second_MD section_NN1 investigates_VVZ ,_, how_RRQ home_NN1 insurance_NN1 packages_NN2 aremarketed_VVD to_II young_JJ adults_NN2 ,_, and_CC identifies_NN1 attributes_VVZ that_CST are_VBR emphasized_VVN in_II the_AT current_JJ marketingcommunication_NN1 and_CC material_NN1 ._. 
</s>
<s>
This_DD1 empirical_JJ section_NN1 also_RR explores_VVZ ,_, whether_CSW the_AT insurance_NN1 packagesfor_NN1 young_JJ adults_NN2 are_VBR unaffordable_JJ as_CSA they_PPHS2 are_VBR stated_VVN to_TO be_VBI ._. 
</s>
<s>
The_AT concluding_JJ section_NN1 presents_VVZ theimprovement_NN1 ideas_NN2 how_RRQ insurance_NN1 companies_NN2 could_VM develop_VVI their_APPGE marketing_NN1 and_CC communication_NN1 forthe_NN1 segment_NN1 young_JJ adults_NN2 so_CS21 that_CS22 the_AT insurance_NN1 companies_NN2 could_VM better_RRR respond_VVI to_II the_AT challengesand_NN1 weaknesses_NN2 revealed_VVN by_II the_AT earlier_JJR studies_NN2 ._. 
</s>
<s>
Literature_NN1 review_NN1 Online_RR buying_VVG behaviour_NN1 The_AT electronic_JJ commerce_NN1 (_( e-commerce_NN1 )_) has_VHZ grown_VVN rapidly_RR during_II the_AT last_MD years_NNT2 ._. 
</s>
<s>
The_AT foregoers_NN2 inonline_VV0 shopping_NN1 has_VHZ been_VBN young_JJ people_NN ,_, and_CC according_II21 to_II22 the_AT earlier_JJR researches_NN2 age_NN1 is_VBZ one_MC1 of_IO themajor_NN1 reasons_NN2 that_CST affects_VVZ online_JJ buying_NN1 ,_, especially_RR impulsive_JJ purchases_NN2 ._. 
</s>
<s>
(_( Wells_NP1 ,_, Parboteeah_NP1 &;_NULL Valacich_NP1 2011_MC ;_; 33_MC ,_, 35_MC ._. )_) 
</s>
<s>
When_CS it_PPH1 comes_VVZ to_II the_AT X_ZZ1 and_CC Y_ZZ1 generations_NN2 that_CST were_VBDR discussed_VVN earlier_RRR ,_, themarketers_NN2 should_VM according_II21 to_II22 Prudential_NP1 (_( 2011_MC )_) know_VV0 the_AT differences_NN2 between_II people_NN of_IO differentage_NN1 ._. 
</s>
<s>
According_II21 to_II22 Prudential_NP1 vice_JJ president_NN1 and_CC chief_JJ marketing_NN1 officer_NN1 Mark_NP1 Hug_NN1 "_" today'sconsumers_NN2 do_VD0 not_XX want_VVI to_TO be_VBI `_" sold'_JJ insurance_NN1 -_- -_- they_PPHS2 want_VV0 to_TO be_VBI empowered_VVN to_TO buy_VVI it_PPH1 "_" (_( Prudential2011_FO ,_, 2_MC )_) ._. 
</s>
<s>
The_AT insurance_NN1 company_NN1 Prudential_NP1 has_VHZ compiled_VVN a_AT1 list_NN1 of_IO attributes_NN2 that_CST generation_NN1 X_ZZ1 andY_JJ consumers_NN2 appreciate_VV0 in_II insurance_NN1 services_NN2 ._. 
</s>
<s>
The_AT list_NN1 illustrate_VV0 appealing_JJ attributes_NN2 for_IF lifeinsurances_NN2 ,_, but_CCB since_CS the_AT purchase_NN1 process_NN1 of_IO all_DB other_JJ types_NN2 of_IO insurances_NN2 is_VBZ quite_RG similar_JJ ,_, the_AT list_NN1 isfor_NN1 the_AT most_RGT part_RR applicable_JJ to_II home_NN1 insurance_NN1 packages_NN2 too_RR ._. 
</s>
<s>
According_II21 to_II22 Prudential_NP1 (_( 2011_MC ,_, 2_MC )_) thefollowing_VVG attributes_NN2 appeal_VV0 to_II generations_NN2 X_ZZ1 and_CC Y_ZZ1 in_II insurance_NN1 services_NN2 :_: Easy-to-understand_VV0 coverageAbility_NN1 to_TO meet_VVI multiple_JJ needsConvertibilityNo_NN1 coverage_NN1 gapsLevel_VV0 premiumsAdequate_JJ death_NN1 benefitA_NN1 highly_RR rated_VVN carrierA_NN1 trusted_JJ advisor_NN1 Why_RRQ should_VM the_AT insurance_NN1 companies_NN2 then_RT be_VBI interested_JJ in_II attributes_NN2 that_CST appeal_VV0 for_IF certaincustomer_NN1 segments_NN2 ?_? 
</s>
<s>
At_RR21 least_RR22 for_IF offering_VVG good_JJ customer_NN1 service_NN1 and_CC creating_VVG profits_NN2 by_II acquiringnew_NN1 customers_NN2 ._. 
</s>
<s>
By_II offering_VVG for_REX21 example_REX22 insurance_NN1 products_NN2 that_CST fulfil_VV0 the_AT customer_NN1 's_GE needs_NN2 ,_, thecustomer_NN1 becomes_VVZ very_RG likely_RR more_RGR satisfied_JJ with_IW the_AT company_NN1 compared_VVN to_II a_AT1 situation_NN1 wherehis/her_FU needs_NN2 would_VM not_XX have_VHI been_VBN taken_VVN into_II account_NN1 ._. 
</s>
<s>
As_CSA Saaty_NP1 (_( 2011_MC ,_, 291_MC )_) explains_VVZ ,_, "_" customersatisfaction_NN1 is_VBZ the_AT key_JJ issue_NN1 for_IF increasing_JJ customer_NN1 loyalty_NN1 "_" ._. 
</s>
<s>
Loyalty_NN1 is_VBZ of_RR21 course_RR22 important_JJ for_IF anycompany_NN1 to_TO create_VVI a_AT1 solid_JJ income_NN1 flow_NN1 and_CC i.e._REX to_TO create_VVI positive_JJ word-of-mouth_NN1 and_CC to_TO improve_VVI thecompany_NN1 image_NN1 ._. 
</s>
<s>
According_II21 to_II22 the_AT research_NN1 by_II Saaty_NP1 ,_, highly_RR satisfied_JJ customers_NN2 are_VBR also_RR very_JJ likelyto_NN1 purchase_VV0 new_JJ insurance_NN1 policies_NN2 in_II future_NN1 (_( Saaty_NP1 2011_MC ,_, 298_MC )_) ._. 
</s>
<s>
The_AT main_JJ issue_NN1 therefore_RR is_VBZ ,_, how_RRQ to_TO market_VVI the_AT insurances_NN2 online_RR by_II a_AT1 way_NN1 that_CST appeals_VVZ tocustomers_NN2 ,_, causes_NN2 (_( impulsive_JJ )_) insurance_NN1 purchases_NN2 and_CC communicates_VVZ positive_JJ image_NN1 of_IO thecompany_NN1 ._. 
</s>
<s>
According_II21 to_II22 Saaty_NP1 three_MC factors_NN2 that_CST insurance_NN1 customers_NN2 are_VBR not_XX typically_RR satisfied_JJ withare_NN1 "_" the_AT advertisement_NN1 of_IO the_AT company_NN1 ,_, the_AT promotions_NN2 and_CC discounts_NN2 of_IO the_AT company_NN1 and_CC mostimportantly_RR the_AT claim_NN1 settlement_NN1 process_NN1 of_IO the_AT insurance_NN1 companies_NN2 "_" (_( Saaty_NP1 2011_MC ,_, 298_MC )_) ._. 
</s>
<s>
The_AT resultsare_NN1 similar_JJ to_II the_AT TrygVesta_NP1 's_GE research_NN1 that_CST was_VBDZ presented_VVN earlier_RRR ,_, indicating_VVG that_DD1 affordable_JJ price_NN1 ,_, clear_JJ and_CC easy-to-understand_VV0 communication_NN1 and_CC the_AT simple_JJ insurance_NN1 purchase_NN1 process_NN1 are_VBR the_AT keyattributes_NN2 that_CST young_JJ adult_NN1 customers_NN2 appreciate_VV0 in_II31 case_II32 of_II33 insurance_NN1 services_NN2 ._. 
</s>
<s>
Taking_VVG in_II consideration_NN1 the_AT special_JJ nature_NN1 of_IO online_JJ buying_NN1 ,_, the_AT earlier_JJR researches_NN2 suggest_VV0 thatsecurity_NN1 and_CC privacy_NN1 issues_NN2 ,_, easiness_NN1 of_IO the_AT checkout_NN1 process_NN1 and_CC provided_VVD information_NN1 on_II theinternet_NN1 site_NN1 are_VBR three_MC key_JJ factors_NN2 that_CST correlate_VV0 positively_RR for_IF making_VVG online_JJ purchases_NN2 (_( Bellman_NN1 ,_, Lohse_NP1 &;_NULL Johnson_NP1 1999_MC ;_; 34_MC ,_, 35_MC ,_, 38_MC )_) ._. 
</s>
<s>
In_RR21 addition_RR22 environmental_JJ features_NN2 such_II21 as_II22 navigability_NN1 of_IO thewebsite_NN1 ,_, security_NN1 ,_, download_VV0 speed_NN1 ,_, design_NN1 of_IO the_AT website_NN1 and_CC pleasantness_NN1 of_IO the_AT website_NN1 are_VBR factorsthat_NN1 affect_NN1 positively_RR the_AT customers_NN2 purchase_VV0 intentions_NN2 ,_, especially_RR the_AT impulsive_JJ ones_NN2 (_( Wells_NP1 et_RA21 al._RA22 2011_MC ,_, 35_MC )_) ._. 
</s>
<s>
Empirical_JJ research_NN1 and_CC methodology_NN1 A_ZZ1 qualitative_JJ study_NN1 was_VBDZ conducted_VVN to_TO analyse_VVI the_AT marketing_NN1 material_NN1 of_IO the_AT insurance_NN1 packages_NN2 foryoung_VVD adults_NN2 ._. 
</s>
<s>
The_AT case_NN1 companies_NN2 were_VBDR selected_VVN with_IW purposeful_JJ sampling_NN1 ._. 
</s>
<s>
The_AT online_JJ marketingmaterial_NN1 was_VBDZ collected_VVN on_II 3rd_MD of_IO March_NPM1 from_II the_AT websites_NN2 of_IO the_AT case_NN1 companies_NN2 ._. 
</s>
<s>
Each_DD1 of_IO thecompanies_NN2 has_VHZ an_AT1 insurance_NN1 package_NN1 for_IF young_JJ adults_NN2 that_CST include_VV0 usually_RR home_RL insurance_NN1 that_CST canbe_VV0 complemented_VVN with_IW other_JJ insurances_NN2 ._. 
</s>
<s>
In_II the_AT table_NN1 1_MC1 below_II the_AT information_NN1 regarding_II each_DD1 of_IO thepackages_NN2 is_VBZ collected_VVN ._. 
</s>
<s>
The_AT mandatory_JJ insurances_NN2 that_CST the_AT packages_NN2 have_VH0 to_TO include_VVI are_VBR marked_JJ with(M)_NN1 and_CC complementary_JJ insurance_NN1 services_NN2 with_IW (_( C_ZZ1 )_) ._. 
</s>
<s>
The_AT price_NN1 of_IO the_AT package_NN1 is_VBZ calculated_VVN with_IW thefollowing_VVG information_NN1 :_: a_AT1 flat_NN1 in_II Helsinki_NP1 with_IW 30_MC square_JJ meters_NN2 ,_, the_AT insured_JJ person_NN1 is_VBZ a_AT1 25-year_JJ oldman_NN1 who_PNQS is_VBZ single_JJ and_CC student_NN1 ._. 
</s>
<s>
The_AT compensation_NN1 amounts_NN2 are_VBR the_AT insurance_NN1 company_NN1 's_GE suggestedmaximum_JJ amounts_NN2 ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) Analysis_NN1 of_IO the_AT dataThe_NN1 material_NN1 will_VM be_VBI analysed_VVN with_IW content_JJ analysis_NN1 ._. 
</s>
<s>
(_( a_AT1 brief_JJ description_NN1 of_IO the_AT method_NN1 and_CC theanalyse_VV0 process_VV0 here_RL )_) ._. 
</s>
<s>
Discussion_NN1 and_CC conclusions_NN2 Discussion_NN1 of_IO the_AT analysed_JJ marketing_NN1 material_NN1 :_: evaluation_NN1 of_IO the_AT simplicity_NN1 of_IO the_AT communication_NN1 (_( used_JJ terminology_NN1 ,_, easiness_NN1 to_TO purchase_VVI an_AT1 insurance_NN1 package_NN1 and_CC to_TO modify_VVI it_PPH1 ,_, availability_NN1 andexplanation_NN1 regarding_II the_AT insurance_NN1 policies_NN2 etc_RA )_) and_CC prices_NN2 (_( discounts_NN2 ,_, campaigns_NN2 ,_, possibility_NN1 topay_NN1 in_II instalments_NN2 etc_RA )_) ._. 
</s>
