<s>
Firm_JJ performance_NN1 and_CC quality_NN1 of_IO corporate_JJ governance_NN1 reporting_VVG 1_MC1 Introduction_NN1 Research_NN1 of_IO corporate_JJ governance_NN1 has_VHZ risen_VVN after_II fraud_NN1 scandals_NN2 like_II Enron_NP1 and_CC during_II the_AT financial_JJ crisis_NN1 ._. 
</s>
<s>
One_MC1 of_IO the_AT main_JJ questions_NN2 behind_RL of_IO the_AT research_NN1 has_VHZ been_VBN :_: Does_VDZ corporate_JJ governance_NN1 increase_NN1 protection_NN1 of_IO the_AT owners_NN2 of_IO the_AT company_NN1 ?_? (_( reference_VV0 to_TO research_VVI done_VDN lately_RR )_) ._. 
</s>
<s>
There_EX has_VHZ been_VBN many_DA2 different_JJ aspects_NN2 which_DDQ researches_NN2 have_VH0 been_VBN concentrated_VVN :_: the_AT impact_NN1 of_IO the_AT shareholders_NN2 to_II firms_NN2 performance_NN1 (_( Keinonen_NP1 ,_, H._NP1 2009_MC ,_, and_CC some_DD other_JJ examples_NN2 )_) ,_, difference_NN1 of_IO shareholder_NN1 protection_NN1 between_II different_JJ countries_NN2 (_( reference_VV0 to_TO research_VVI )_) ,_, and_CC overall_JJ quality_NN1 of_IO corporate_JJ governance_NN1 reporting_NN1 (_( PwC_NP1 2009_MC ,_, 2010_MC ,_, and_CC 2011_MC )_) ._. 
</s>
<s>
Corporate_JJ governance_NN1 is_VBZ the_AT tool_NN1 to_TO protect_VVI the_AT shareholders_NN2 ._. 
</s>
<s>
The_AT agency_NN1 theory_NN1 ,_, the_AT main_JJ theory_NN1 of_IO corporate_JJ governance_NN1 ,_, suggests_VVZ that_CST owners_NN2 of_IO the_AT company_NN1 hires_VVZ management_NN1 to_TO take_VVI care_NN1 of_IO their_APPGE owning_VVG ,_, i.e._REX to_TO increase_VVI the_AT value_NN1 of_IO the_AT company_NN1 ._. 
</s>
<s>
(_( Shleifer_VV0 ,_, A._NP1 &;_NULL Vishny_NP1 ,_, R._NP1 1997_MC ;_; La_NP1 Porta_NP1 ,_, R._NP1 ,_, Lopez-de-Silanes_NP1 ,_, F._NP1 ,_, Shleifer_NP1 ,_, A._NP1 and_CC Vishny_NP1 ,_, R._NP1 1999_MC )_) One_MC1 way_NN1 the_AT owners_NN2 of_IO the_AT company_NN1 can_VM evaluate_VVI the_AT work_NN1 managers_NN2 do_VD0 ,_, is_VBZ the_AT different_JJ reports_NN2 which_DDQ tells_VVZ about_II the_AT performance_NN1 ,_, but_CCB also_RR how_RRQ the_AT company_NN1 is_VBZ governed_VVN ,_, how_RRQ management_NN1 has_VHZ been_VBN compensated_VVN ,_, and_CC how_RRQ risks_NN2 have_VH0 been_VBN managed_VVN ._. 
</s>
<s>
The_AT theory_NN1 claims_VVZ that_CST managers_NN2 have_VH0 an_AT1 intensive_JJ to_TO misuse_VVI their_APPGE position_NN1 in_II the_AT firm_NN1 ,_, so_CS they_PPHS2 might_VM waste_VVI money_NN1 trusted_VVN on_II them_PPHO2 ._. 
</s>
<s>
(_( Shleifer_VV0 ,_, A._NP1 &;_NULL Vishny_NP1 ,_, R._NP1 1997_MC ;_; La_NP1 Porta_NP1 ,_, R._NP1 ,_, Lopez-de-Silanes_NP1 ,_, F._NP1 ,_, Shleifer_NP1 ,_, A._NP1 and_CC Vishny_NP1 ,_, R._NP1 1999_MC )_) ._. 
</s>
<s>
If_CS so_RR ,_, it_PPH1 would_VM affect_VVI to_II the_AT firms_NN2 performance_NN1 and_CC in_II that_DD1 case_NN1 managers_NN2 might_VM not_XX be_VBI willing_JJ publish_VV0 the_AT best_JJT possible_JJ corporate_JJ governance_NN1 reports_NN2 in_BCL21 order_BCL22 to_TO save_VVI their_APPGE own_DA position_NN1 and_CC hide_VVI the_AT misuse_NN1 of_IO equity_NN1 they_PPHS2 have_VH0 done_VDN ._. 
</s>
<s>
If_CS the_AT performance_NN1 of_IO the_AT company_NN1 does_VDZ affect_VVI to_II the_AT quality_NN1 of_IO the_AT corporate_JJ governance_NN1 reporting_VVG in_II real_JJ life_NN1 ,_, or_CC not_XX ,_, has_VHZ not_XX been_VBN researched_VVN widely_RR ._. 
</s>
<s>
The_AT purpose_NN1 of_IO this_DD1 term_NN1 paper_NN1 is_VBZ to_TO research_VVI if_CSW firm_JJ performance_NN1 has_VHZ an_AT1 impact_NN1 to_II the_AT quality_NN1 of_IO corporate_JJ governance_NN1 report_NN1 quality_NN1 in_II listed_JJ companies_NN2 in_II Finland_NP1 ._. 
</s>
<s>
To_TO give_VVI a_AT1 theoretical_JJ background_NN1 to_II the_AT reader_NN1 ,_, this_DD1 paper_NN1 begins_VVZ with_IW a_AT1 short_JJ review_NN1 of_IO corporate_JJ governance_NN1 theory_NN1 and_CC the_AT central_JJ research_NN1 done_VDN on_II the_AT field_NN1 ._. 
</s>
<s>
The_AT research_NN1 part_NN1 includes_VVZ analyzing_VVG PriceWaterhouseCoopers_NP1 research_NN1 about_II corporate_JJ governance_NN1 reporting_NN1 quality_NN1 in_II Finnish_JJ listed_JJ firms_NN2 in_II years_NNT2 2008_MC ,_, 2009_MC ,_, and_CC 2010_MC ,_, and_CC comparing_VVG these_DD2 results_NN2 to_II annual_JJ reports_NN2 of_IO these_DD2 firms_NN2 collected_VVN by_II FactSet_NP1 ._. 
</s>
<s>
This_DD1 paper_NN1 will_VM broaden_VVI the_AT understanding_NN1 of_IO corporate_JJ governance_NN1 reporting_NN1 quality_NN1 by_II showing_VVG if_CS firm_JJ performance_NN1 has_VHZ an_AT1 impact_NN1 to_II the_AT quality_NN1 or_CC not_XX ._. 
</s>
<s>
If_CS it_PPH1 does_VDZ ,_, the_AT result_NN1 strengthens_VVZ the_AT corporate_JJ governance_NN1 reportings_NN2 position_VV0 as_II an_AT1 important_JJ tool_NN1 for_IF the_AT shareholders_NN2 to_TO monitor_VVI the_AT work_NN1 of_IO the_AT managers_NN2 ._. 
</s>
<s>
This_DD1 term_NN1 paper_NN1 is_VBZ divided_VVN to_II five_MC parts_NN2 ._. 
</s>
<s>
After_CS this_DD1 introduction_NN1 a_AT1 brief_JJ review_NN1 of_IO relevant_JJ theories_NN2 and_CC previous_JJ research_NN1 will_VM be_VBI made_VVN ._. 
</s>
<s>
In_II third_MD part_NN1 ther_NN1 research_NN1 method_NN1 ,_, data_NN and_CC main_JJ results_NN2 are_VBR presented_VVN ._. 
</s>
<s>
The_AT last_MD chapter_NN1 ,_, conclusions_NN2 ,_, will_VM end_VVI this_DD1 paper_NN1 ._. 
</s>
<s>
2_MC Theoretical_JJ framework_NN1 In_II this_DD1 chapter_NN1 the_AT first_MD part_NN1 concentrates_VVZ to_II the_AT main_JJ problems_NN2 in_II separation_NN1 of_IO ownership_NN1 and_CC control_NN1 ._. 
</s>
<s>
The_AT second_MD part_NN1 will_VM present_VVI reasons_NN2 why_RRQ corporate_JJ governance_NN1 reporting_NN1 can_VM be_VBI seen_VVN as_II a_AT1 important_JJ tool_NN1 for_IF shareholders_NN2 to_TO monitor_VVI management_NN1 ._. 
</s>
<s>
The_AT last_MD part_NN1 is_VBZ a_AT1 brief_JJ review_NN1 of_IO previous_JJ research_NN1 on_II the_AT field_NN1 in_II question_NN1 ._. 
</s>
<s>
2.1_MC Corporate_JJ governance_NN1 Corporate_JJ governance_NN1 has_VHZ many_DA2 different_JJ definitions_NN2 ._. 
</s>
<s>
Adam_NP1 Smith_NP1 (_( 1776_MC )_) can_VM be_VBI seen_VVN the_AT first_MD who_PNQS stated_VVD it_PPH1 to_TO deal_VVI with_IW the_AT separation_NN1 of_IO ownership_NN1 and_CC control_NN1 ,_, also_RR cited_VVN to_II agency_NN1 theory_NN1 ._. 
</s>
<s>
From_II sepration_NN1 of_IO ownership_NN1 and_CC control_NN1 point_NN1 of_IO view_NN1 corporate_JJ governance_NN1 can_VM be_VBI seen_VVN dealing_VVG with_IW the_AT ways_NN2 which_DDQ suppliers_NN2 of_IO finance_NN1 to_II corporations_NN2 assure_VV0 themselves_PPX2 of_IO getting_VVG a_AT1 return_NN1 on_II their_APPGE investment_NN1 (_( Shleifer_NP1 ,_, A._NP1 &;_NULL Vishny_NP1 ,_, R._NP1 1997_MC )_) or_CC mechanisms_NN2 through_II which_DDQ outside_JJ investors_NN2 protect_VV0 themselves_PPX2 agains_NN2 expropriation_NN1 by_II the_AT insiders_NN2 (_( La_NP1 Porta_NP1 ,_, R._NP1 &;_NULL all_DB ,_, 1999_MC )_) ._. 
</s>
<s>
Two_MC broad_JJ principles_NN2 are_VBR accepted_VVN widely_RR to_TO deal_VVI with_IW these_DD2 issues_NN2 ,_, duty_NN1 of_IO care_NN1 and_CC duty_NN1 of_IO loyalty_NN1 ._. 
</s>
<s>
Duty_NN1 of_IO care_NN1 refers_VVZ to_II responsibilities_NN2 of_IO corporate_JJ managers_NN2 ,_, whom_PNQO need_VV0 to_TO act_VVI as_II a_AT1 reasonable_JJ ,_, prudent_JJ or_CC rational_JJ person_NN1 would_VM act_VVI in_II that_DD1 same_DA position_NN1 ._. 
</s>
<s>
This_DD1 principle_NN1 is_VBZ known_VVN also_RR as_CSA the_AT business_NN1 judgment_NN1 rule_NN1 ._. 
</s>
<s>
The_AT duty_NN1 of_IO loyalty_NN1 requires_VVZ that_CST insiders_NN2 of_IO corporation_NN1 do_VD0 not_XX profit_VVI at_II the_AT expense_NN1 of_IO shareholders_NN2 or_CC of_IO the_AT corporation_NN1 itself_PPX1 ,_, as_CSA the_AT case_NN1 may_VM be_VBI ,_, depending_II21 on_II22 whom_PNQO they_PPHS2 legally_RR owe_VV0 loyalty_NN1 to_II ._. 
</s>
<s>
If_CS there_EX is_VBZ a_AT1 great_JJ risk_NN1 to_II managerial_JJ expropriation_NN1 of_IO invested_JJ funds_NN2 ,_, why_RRQ to_TO have_VHI a_AT1 managers_NN2 in_II first_MD place_NN1 ?_? 
</s>
<s>
The_AT financiers_NN2 need_VV0 the_AT manager_NN1 's_GE specialized_JJ human_JJ capital_NN1 to_TO generate_VVI returns_NN2 on_II their_APPGE funds_NN2 ._. 
</s>
<s>
So_RR why_RRQ to_TO give_VVI any_DD control_NN1 rights_NN2 to_II manager_NN1 then_RT ?_? 
</s>
<s>
In_II31 case_II32 of_II33 decision_NN1 making_VVG ,_, it_PPH1 would_VM be_VBI extremely_RR time_NNT1 consuming_VVG if_CSW every_AT1 time_NNT1 ,_, the_AT financers_NN2 should_VM decide_VVI together_RL what_DDQ to_TO do_VDI and_CC on_II the_AT other_JJ hand_NN1 the_AT financers_NN2 might_VM not_XX be_VBI qualified_VVN or_CC informed_VVD enough_RR to_TO do_VDI the_AT decision_NN1 and_CC thats_VVZ the_AT reason_NN1 they_PPHS2 needed_VVD the_AT manager_NN1 in_II first_MD place_NN1 ._. 
</s>
<s>
With_IW significant_JJ control_NN1 rights_NN2 how_RRQ to_TO allocate_VVI investors_NN2 '_GE funds_NN2 makes_VVZ possible_JJ manager_NN1 to_TO expropriate_VVI this_DD1 money_NN1 in_II numerous_JJ ways_NN2 :_: pyramid_NN1 schemes_NN2 ,_, transfer_VV0 pricing_NN1 ,_, perquisites_NN2 ,_, expanding_VVG the_AT firm_NN1 beyond_II that_DD1 is_VBZ rational_JJ ,_, reinvesting_VVG the_AT free_JJ cash_NN1 flows_NN2 ,_, pursuing_VVG pet_NN1 projects_NN2 ,_, resisting_VVG take-over_NN1 actions_NN2 ,_, entrenching_VVG themselves_PPX2 and_CC staying_VVG on_II the_AT job_NN1 even_CS21 if_CS22 they_PPHS2 are_VBR no_RR21 longer_RR22 competent_JJ of_IO qualified_JJ to_TO run_VVI the_AT firm_NN1 ._. 
</s>
<s>
Corporate_JJ governance_NN1 deals_VVZ with_IW how_RRQ to_TO reduce_VVI this_DD1 kind_NN1 of_IO ex_NN1 post_NN1 misallocation_NN1 ._. 
</s>
<s>
One_MC1 way_NN1 is_VBZ the_AT contract_NN1 signed_VVN between_II financiers_NN2 and_CC management_NN1 ._. 
</s>
<s>
A_AT1 contract_NN1 specifies_VVZ what_DDQ manager_NN1 does_VDZ with_IW the_AT invested_JJ funds_NN2 ,_, and_CC how_RRQ the_AT returns_NN2 of_IO this_DD1 investment_NN1 are_VBR divided_VVN between_II him_PPHO1 and_CC the_AT financiers_NN2 ._. 
</s>
<s>
Complete_JJ contracts_NN2 are_VBR technologically_RR infeasible_JJ ,_, as_CSA all_DB possible_JJ situations_NN2 are_VBR impossible_JJ to_TO write_VVI down_RP ._. 
</s>
<s>
When_RRQ contracts_NN2 are_VBR incomplete_JJ and_CC mangers_NN2 possess_VV0 more_DAR expertise_NN1 than_CSN shareholders_NN2 ,_, managers_NN2 typically_RR end_VV0 up_RP with_IW the_AT residual_JJ rights_NN2 of_IO control_NN1 ,_, giving_VVG them_PPHO2 enormous_JJ latitude_NN1 for_IF self-interested_JJ behavior_NN1 ._. 
</s>
<s>
This_DD1 might_VM result_VVI in_II managers_NN2 taking_VVG highly_RR inefficient_JJ actions_NN2 ,_, like_RR mentioned_VVN in_II last_MD paragraph_NN1 ,_, which_DDQ cost_VV0 investors_NN2 far_RG more_DAR than_CSN the_AT personal_JJ benefits_NN2 to_II managers_NN2 ._. 
</s>
<s>
One_MC1 solution_NN1 to_II this_DD1 kind_NN1 of_IO situation_NN1 is_VBZ to_TO grant_VVI a_AT1 manager_NN1 an_AT1 incentive_NN1 contract_NN1 ex_JJ21 ante_JJ22 to_TO align_VVI his_APPGE interests_NN2 with_IW those_DD2 of_IO investors_NN2 ,_, like_II share_NN1 ownership_NN1 ,_, stock_NN1 options_NN2 or_CC threat_NN1 of_IO dismissal_NN1 if_CS returns_NN2 are_VBR too_RG low_JJ (_( Jensen_NP1 &;_NULL Meckling_NP1 1976_MC )_) ._. 
</s>
<s>
2.2_MC Protection_NN1 of_IO minority_NN1 shareholders_NN2 The_AT individual_JJ shareholders_NN2 have_VH0 less_DAR protection_NN1 from_II expropriation_NN1 than_CSN other_JJ stakeholders_NN2 like_II employees_NN2 ,_, who_PNQS get_VV0 paid_VVN almost_RR immediately_RR for_IF their_APPGE efforts_NN2 ._. 
</s>
<s>
The_AT shareholders_NN2 have_VH0 no_AT claim_NN1 to_II specific_JJ assets_NN2 of_IO the_AT firm_NN1 and_CC have_VH0 no_AT right_NN1 to_TO pull_VVI the_AT collateral_NN1 either_RR like_II creditors_NN2 has_VHZ ._. 
</s>
<s>
The_AT shareholders_NN2 may_VM never_RR get_VVI anything_PN1 back_RP at_RR21 all_RR22 ._. 
</s>
<s>
The_AT principal_JJ reason_NN1 that_CST investors_NN2 provide_VV0 external_JJ financing_NN1 to_II firms_NN2 is_VBZ that_CST they_PPHS2 receive_VV0 control_NN1 rights_NN2 in_II exchange_NN1 ._. 
</s>
<s>
The_AT most_RGT important_JJ legal_JJ right_JJ shareholders_NN2 have_VH0 is_VBZ the_AT right_NN1 to_TO vote_VVI on_II important_JJ corporate_JJ matters_NN2 ._. 
</s>
<s>
Like_RR stated_VVN in_II the_AT beginning_NN1 of_IO this_DD1 chapter_NN1 ,_, one_MC1 way_NN1 to_TO see_VVI corporate_JJ governance_NN1 is_VBZ that_DD1 corporate_JJ governance_NN1 is_VBZ a_AT1 set_NN1 of_IO mechanisms_NN2 through_II which_DDQ outside_JJ investors_NN2 protect_VV0 themselves_PPX2 against_II expropriation_NN1 by_II the_AT insiders_NN2 ._. 
</s>
<s>
According_II21 to_II22 La_NP1 Porta_NP1 et_NP1 all_RR (_( 1999_MC )_) the_AT legal_JJ protection_NN1 of_IO investors_NN2 is_VBZ a_AT1 useful_JJ way_NN1 of_IO thinking_VVG about_II corporate_JJ governance_NN1 ._. 
</s>
<s>
Strong_JJ investor_NN1 protection_NN1 is_VBZ associated_VVN with_IW effective_JJ corporate_JJ governance_NN1 ,_, valuable_JJ and_CC broad_JJ financial_JJ markets_NN2 ,_, dispersed_JJ ownership_NN1 of_IO shares_NN2 and_CC efficient_JJ allocation_NN1 of_IO capital_NN1 across_II firms_NN2 ._. 
</s>
<s>
La_NP1 Porta_NP1 et_NP1 all_RR (_( 1999_MC )_) concludes_VVZ that_CST legal_JJ protection_NN1 makes_VVZ the_AT expropriation_NN1 technology_NN1 less_RGR efficient_JJ ._. 
</s>
<s>
When_CS investor_NN1 protection_NN1 is_VBZ very_RG good_JJ and_CC investor_NN1 rights_NN2 such_II21 as_II22 the_AT voting_NN1 rights_NN2 of_IO the_AT shareholders_NN2 ,_, disclosure_NN1 and_CC accounting_VVG rules_NN2 ,_, right_RR to_TO sue_VVI directors_NN2 or_CC the_AT majority_NN1 for_IF suspected_JJ expropriation_NN1 ,_, and_CC the_AT reorganization_NN1 and_CC liquidation_NN1 rights_NN2 of_IO the_AT creditors_NN2 are_VBR extensive_JJ and_CC well_RR enforced_VVN by_II regulators_NN2 or_CC courts_NN2 ,_, investors_NN2 are_VBR willing_JJ to_TO finance_VVI firms_NN2 ._. 
</s>
<s>
Then_RT the_AT most_DAT the_AT insiders_NN2 can_VM do_VDI is_VBZ overpay_NN1 themselves_PPX2 ,_, put_VV0 relatives_NN2 in_II management_NN1 and_CC undertake_VV0 some_DD wasteful_JJ projects_NN2 ._. 
</s>
<s>
And_CC after_II a_AT1 point_NN1 ,_, it_PPH1 may_VM be_VBI better_RRR just_RR to_TO pay_VVI dividends._NNU WORK_NN1 WITH_IW TEXT_NN1 BELOW_RL ,_, FACTS_NN2 ARE_VBR FROM_II ARTICLE_NN1 La_NP1 Porta_NP1 ,_, R._NP1 ,_, Lopez-de-Silanes_NP1 ,_, F._NP1 ,_, Shleifer_NP1 ,_, A._NP1 ,_, Vishny_NP1 ,_, R._NP1 W._NP1 ,_, 2000_MC ._. 
</s>
<s>
Investor_NN1 protection_NN1 and_CC corporate_JJ governance_NN1 ._. 
</s>
<s>
Journal_NN1 of_IO Financial_JJ Economics_NN1 58_MC ,_, 3-27_MCMC ._. :_: 
</s>
<s>
Law_NN1 may_VM seek_VVI to_TO regulate_VVI the_AT approval_NN1 process_NN1 and_CC require_VVI a_AT1 review_NN1 by_II independent_JJ third_MD parties_NN2 ._. 
</s>
<s>
These_DD2 practices_NN2 might_VM work_VVI because_CS ,_, when_CS problematic_JJ deals_NN2 are_VBR publicly_RR disclosed_VVN ,_, they_PPHS2 are_VBR criticized_VVN in_II the_AT press_NN1 or_CC stimulate_VV0 the_AT activism_NN1 of_IO large_JJ outside_JJ shareholders_NN2 ._. 
</s>
<s>
Cash_NN1 flow_NN1 ownership_NN1 by_II an_AT1 entrepreneur_NN1 reduces_VVZ incentives_NN2 for_IF expropriation_NN1 and_CC raises_VVZ incentives_NN2 to_TO pay_VVI out_RP dividends_NN2 ._. 
</s>
<s>
Need_VV0 for_IF higher_JJR cash_NN1 flow_NN1 ownership_NN1 as_II a_AT1 commitment_NN1 to_TO limit_VVI expropriation_NN1 is_VBZ higher_JJR in_II countries_NN2 with_IW inferior_JJ shareholder_NN1 protection_NN1 ._. 
</s>
<s>
The_AT ease_NN1 with_IW which_DDQ shareholders_NN2 can_VM prove_VVI wrongdoing_NN1 depends_VVZ on_II disclosure_NN1 requirements_NN2 in_II annual_JJ reports_NN2 and_CC periodic_JJ filings_NN2 may_VM facilitate_VVI the_AT scrunity_NN1 of_IO related-party_JJ transactions_NN2 by_II outside_JJ shareholders_NN2 ._. 
</s>
<s>
Plaintiffs_NN2 are_VBR more_RGR likely_JJ to_TO prevail_VVI if_CSW access_NN1 to_II evidence_NN1 is_VBZ extensive_JJ ._. 
</s>
<s>
Disclosure_NN1 requirements_NN2 are_VBR more_RGR stringent_JJ and_CC it_PPH1 is_VBZ easier_JJR for_IF plaintiffs_NN2 to_TO prove_VVI wrongdoing_NN1 in_II court_NN1 in_II common_JJ law_NN1 countries_NN2 than_CSN in_II civil_JJ ones_NN2 ._. 
</s>
<s>
Legal_JJ families_NN2 also_RR differ_VV0 in_II the_AT burden_NN1 of_IO proof_NN1 for_IF rescinding_VVG the_AT transaction_NN1 as_RG well_RR as_CSA for_IF holding_VVG liable_JJ controlling_JJ shareholders_NN2 and_CC directors_NN2 ._. 
</s>
<s>
The_AT law_NN1 may_VM deter_VVI wrongdoing_NN1 by_II sanctioning_VVG the_AT controlling_JJ shareholder_NN1 and_CC those_DD2 who_PNQS approved_VVD the_AT transaction_NN1 with_IW fines_NN2 and_CC prison_NN1 terms_NN2 ._. 
</s>
<s>
Prison_NN1 terms_NN2 for_IF those_DD2 who_PNQS approve_VV0 the_AT transaction_NN1 are_VBR more_RGR severe_JJ in_II civil_JJ law_NN1 countries_NN2 than_CSN in_RR21 common_RR22 law_NN1 ._. 
</s>
<s>
Public_JJ enforcement_NN1 shows_VVZ no_AT variation_NN1 across_II legal_JJ origins_NN2 ._. 
</s>
<s>
Enforcement_NN1 of_IO laws_NN2 is_VBZ as_RG crucial_JJ as_CSA their_APPGE contents_NN2 ._. 
</s>
<s>
Enforcing_NP1 is_VBZ done_VDN by_II in_RR21 part_RR22 by_II market_NN1 regulators_NN2 ,_, in_RR21 part_RR22 by_II courts_NN2 and_CC in_RR21 part_RR22 by_II market_NN1 participants_NN2 themselves_PPX2 ._. 
</s>
<s>
When_CS the_AT enforcement_NN1 of_IO private_JJ contracts_NN2 through_II the_AT court_NN1 system_NN1 is_VBZ costly_JJ enough_RR ,_, other_JJ forms_NN2 of_IO protecting_VVG property_NN1 rights_NN2 ,_, such_II21 as_II22 judicially-enforced_JJ laws_NN2 or_CC even_RR government-enforced_JJ regulations_NN2 ,_, may_VM be_VBI more_RGR efficient.The_NNU quality_NN1 of_IO enforcement_NN1 is_VBZ higher_JJR in_II richer_JJR countries_NN2 ._. 
</s>
<s>
Scandinavian_NN1 and_CC German_JJ legal_JJ origin_NN1 countries_NN2 receive_VV0 the_AT best_JJT scores_NN2 on_II the_AT efficiency_NN1 of_IO the_AT judiciary_NN1 ._. 
</s>
<s>
The_AT French_NN1 have_VH0 the_AT worst._NNU How_RGQ well_RR legal_JJ rules_NN2 protect_VV0 outside_JJ investors_NN2 varies_VVZ systematically_RR across_II legal_JJ origins_NN2 ._. 
</s>
<s>
Common_JJ law_NN1 countries_NN2 have_VH0 the_AT strongest_JJT protection_NN1 both_RR shareholders_NN2 and_CC creditors_NN2 ._. 
</s>
<s>
French_JJ civil_JJ law_NN1 countries_NN2 have_VH0 the_AT weakest_JJT protection_NN1 ._. 
</s>
<s>
German_JJ civil_JJ law_NN1 and_CC Scandinavian_JJ countries_NN2 fall_VV0 in_RL21 between_RL22 ,_, although_CS comparatively_RR speaking_VVG they_PPHS2 have_VH0 stronger_JJR protection_NN1 of_IO creditors._NNU The_AT judicial_JJ explanation_NN1 of_IO why_RRQ common_JJ law_NN1 protects_VVZ investors_NN2 better_RRR than_CSN civil_JJ law_NN1 can_VM be_VBI found_VVN from_II the_AT principles_NN2 of_IO duty_NN1 and_CC fairness_NN1 ._. 
</s>
<s>
Judges_NN2 in_II common_JJ law_NN1 countries_NN2 are_VBR expected_VVN to_TO rule_VVI on_II new_JJ situations_NN2 by_II applying_VVG these_DD2 general_JJ principles_NN2 ._. 
</s>
<s>
Expansion_NN1 of_IO legal_JJ precedents_NN2 to_II additional_JJ violations_NN2 of_IO fiduciary_JJ duty_NN1 ,_, and_CC the_AT fear_NN1 of_IO such_DA expansion_NN1 ,_, limit_VV0 the_AT expropriation_NN1 by_II the_AT insiders_NN2 in_II common_JJ law_NN1 countries_NN2 ._. 
</s>
<s>
Laws_NN2 in_II civil_JJ law_NN1 systems_NN2 are_VBR made_VVN by_II legislatures_NN2 ,_, a_AT1 corporate_JJ insider_NN1 who_PNQS finds_VVZ a_AT1 way_NN1 not_XX explicitly_RR forbidden_VVN by_II the_AT statutes_NN2 to_TO expropriate_VVI outside_JJ investors_NN2 can_VM proceed_VVI without_IW fear_NN1 of_IO an_AT1 adverse_JJ judicial_JJ ruling._NNU There_RL is_VBZ little_DA1 evidence_NN1 that_CST investor_NN1 protection_NN1 varies_VVZ by_II income_NN1 level_NN1 ,_, but_CCB ex-post_JJ private_JJ control_NN1 of_IO self-dealing_NN1 is_VBZ highest_JJT in_II rich_JJ countries_NN2 and_CC the_AT strength_NN1 of_IO public_JJ enforcement_NN1 is_VBZ the_AT lowest_RRT in_II poor_JJ countries_NN2 ._. 
</s>
<s>
The_AT regulation_NN1 of_IO self-dealing_NN1 varies_VVZ across_II legal_JJ origins_NN2 and_CC is_VBZ associated_VVN with_IW more_RGR developed_JJ securities_NN2 markets_NN2 ._. 
</s>
<s>
Effective_JJ tax_NN1 enforcement_NN1 can_VM prevent_VVI some_DD self-dealing_JJ transactions_NN2 ._. 
</s>
<s>
Tax_NN1 evasion_NN1 is_VBZ significant_JJ for_IF stock_NN1 market_NN1 capitalization_NN1 and_CC domestic_JJ firms_NN2 per_RR21 capita_RR22 ._. 
</s>
<s>
Countries_NN2 with_IW successful_JJ stock_NN1 markets_NN2 mandate_NN1 that_CST shareholders_NN2 receive_VV0 the_AT information_NN1 they_PPHS2 need_VV0 and_CC the_AT power_NN1 to_TO act_VVI including_II both_RR voting_VVG and_CC litigation_NN1 on_II this_DD1 information_NN1 ._. 
</s>
<s>
There_EX is_VBZ no_AT evidence_NN1 that_CST these_DD2 countries_NN2 rely_VV0 heavily_RR on_II fines_NN2 and_CC criminal_JJ sanctions_NN2 ._. 
</s>
<s>
Investor_NN1 protection_NN1 influences_VVZ the_AT real_JJ economy_NN1 ._. 
</s>
<s>
Firms_NN2 in_II countries_NN2 with_IW better_JJR shareholder_NN1 protection_NN1 have_VH0 higher_JJR Tobin_NP1 's_GE Q_NN1 and_CC higher_JJR insider_NN1 cash_NN1 flow_NN1 ownership_NN1 is_VBZ associated_VVN with_IW higher_JJR corporate_JJ valuation._NNU (_( Djankov_NP1 &;_NULL all_DB 2008_MC )_) 2.3_MC Previous_JJ research_NN1 briefly_RR 3_MC Empirical_JJ research_NN1 and_CC results_NN2 What_DDQ is_VBZ it_PPH1 about_RP in_II this_DD1 chapter_NN1 ?_? 3.1_MC Methodology_NN1 and_CC the_AT data_NN Tell_VV0 briefly_RR about_II research_NN1 methodology_NN1 and_CC describe_VV0 the_AT data_NN ._. 
</s>
<s>
3.2_MC Main_JJ results_NN2 The_AT main_JJ results_NN2 of_IO the_AT results_NN2 ._. 
</s>
<s>
4_MC Conclusion_NN1 Conclusions_NN2 of_IO main_JJ findings_NN2 and_CC recommendations_NN2 for_IF future_JJ research_NN1 ._. 
</s>
