<s>
Security_NN1 Threats_NN2 in_II Humanitarian_JJ Logistics_NN1 A_ZZ1 focus_VV0 on_II disaster_NN1 relief_NN1 operations_NN2 1_MC1 ._. 
</s>
<s>
Introduction_NN1 The_AT Asian_JJ tsunami_NN2 2004_MC ,_, the_AT Post-election_JJ crisis_NN1 in_II Kenya_NP1 2007_MC ,_, the_AT earthquake_NN1 in_II Haiti_NP1 2010_MC ,_, the_AT floods_NN2 in_II Pakistan_NP1 2010_MC ,_, these_DD2 are_VBR a_AT1 few_DA2 of_IO many_DA2 humanitarian_JJ crises_NN2 that_CST have_VH0 taken_VVN place_NN1 recently_RR ._. 
</s>
<s>
Van_NP1 Wassenhove_NP1 (_( 2006_MC )_) estimates_VVZ that_CST up_RG21 to_RG22 80_MC %_NNU of_IO the_AT costs_NN2 related_VVN to_II the_AT humanitarian_JJ aid_NN1 is_VBZ due_II21 to_II22 logistics_NN1 ._. 
</s>
<s>
Therefore_RR the_AT logistics_NN1 operations_NN2 in_II humanitarian_JJ relief_NN1 ,_, i.e._REX humanitarian_JJ logistics_NN1 are_VBR of_IO essence_NN1 in_II any_DD crisis_NN1 response_NN1 ._. 
</s>
<s>
Humanitarian_JJ logistics_NN1 differs_VVZ from_II ordinary_JJ logistics_NN1 due_II21 to_II22 the_AT special_JJ environment_NN1 the_AT humanitarian_JJ supply_NN1 chain_NN1 functions_VVZ in_RP ._. 
</s>
<s>
Humanitarian_JJ logistics_NN1 can_VM be_VBI divided_VVN into_II two_MC main_JJ fields_NN2 :_: continuous_JJ aid_NN1 and_CC disaster_NN1 relief_NN1 ._. 
</s>
<s>
Especially_RR disaster_NN1 relief_NN1 operations_NN2 are_VBR faced_VVN with_IW challenges_NN2 that_CST do_VD0 not_XX affect_VVI commercial_JJ supply_NN1 chains_NN2 to_II the_AT same_DA extent_NN1 ._. 
</s>
<s>
(_( Kovcs_NN2 and_CC Spens_NP1 ,_, 2007_MC )_) There_EX are_VBR several_DA2 constraints_NN2 that_CST humanitarian_JJ logistics_NN1 have_VH0 to_TO deal_VVI with_IW ._. 
</s>
<s>
For_REX21 example_REX22 unpredictable_JJ supply_NN1 and_CC demand_NN1 ,_, lack_NN1 of_IO information_NN1 ,_, biased_JJ funding_NN1 ,_, lack_NN1 of_IO information_NN1 ,_, destabilized_VVD infrastructure_NN1 ,_, cultural_JJ and_CC language_NN1 barriers_NN2 ,_, and_CC a_AT1 lack_NN1 of_IO cooperation_NN1 between_II humanitarian_JJ actors_NN2 are_VBR challenges_NN2 humanitarian_JJ logistics_NN1 faces_NN2 (_( Kovcs_NP2 and_CC Spens_NP1 ,_, 2007_MC )_) ._. 
</s>
<s>
Gustavsson_NP1 (_( 2003_MC )_) raises_VVZ the_AT issue_NN1 of_IO lack_NN1 of_IO investment_NN1 in_II technology_NN1 and_CC communication_NN1 ,_, a_AT1 lack_NN1 of_IO capacity_NN1 ,_, and_CC security_NN1 threats_NN2 ._. 
</s>
<s>
These_DD2 before_II mentioned_VVD studies_NN2 ,_, and_CC several_DA2 other_JJ studies_NN2 ,_, for_REX21 example_REX22 Pettit_NP1 and_CC Beresford_NP1 (_( 2009_MC )_) ,_, focus_VV0 on_II the_AT whole_JJ picture_NN1 of_IO challenges_NN2 for_IF the_AT humanitarian_JJ relief_NN1 chain_NN1 in_II a_AT1 wide_JJ scope_NN1 of_IO disasters_NN2 ._. 
</s>
<s>
However_RR ,_, when_CS studying_VVG cases_NN2 like_II the_AT earthquake_NN1 in_II Haiti_NP1 (_( IFRC_NP1 ,_, 2010_MC )_) and_CC post-election_JJ crisis_NN1 in_II Kenya_NP1 in_II 2007_MC (_( Hertz_NNU ,_, 2011_MC )_) ,_, it_PPH1 is_VBZ evident_JJ that_CST there_EX is_VBZ one_MC1 challenge_NN1 that_CST affects_VVZ the_AT overall_JJ supply_NN1 chain_NN1 externally_RR security_NN1 constraints_NN2 ._. 
</s>
<s>
Where_CS supply_NN1 ,_, demand_NN1 and_CC information_NN1 management_NN1 can_VM be_VBI handled_VVN through_II management_NN1 tools_NN2 and_CC preparedness_NN1 ,_, security_NN1 issues_NN2 usually_RR come_VV0 from_II external_JJ sources_NN2 (_( van_NP1 Wassenhove_NP1 2006_MC )_) ._. 
</s>
<s>
For_IF people_NN engaged_VVN in_II any_DD humanitarian_JJ operations_NN2 ,_, security_NN1 is_VBZ an_AT1 issue_NN1 and_CC the_AT organizations_NN2 they_PPHS2 work_VV0 for_IF are_VBR trying_VVG to_TO provide_VVI their_APPGE workers_NN2 guidelines_NN2 as_CSA on_II how_RRQ to_TO avoid_VVI security_NN1 threats_NN2 ._. 
</s>
<s>
(_( Roberts_NP1 ,_, 2005_MC p.15_FO )_) especially_RR since_CS Sheik_NN1 et_NP1 ._. 
</s>
<s>
al_NP1 ._. 
</s>
<s>
(_( 2000_MC )_) point_VV0 out_RP that_CST several_DA2 humanitarian_JJ organizations_NN2 think_VV0 that_CST the_AT death_NN1 toll_NN1 among_II humanitarian_JJ workers_NN2 is_VBZ on_II the_AT rise_NN1 ._. 
</s>
<s>
As_CSA Kovcs_NN2 and_CC Spens_NP1 (_( 2007_MC and_CC 2009_MC )_) conclude_VV0 ,_, the_AT field_NN1 of_IO humanitarian_JJ logistics_NN1 is_VBZ a_AT1 relatively_RR little_RR studied_VVN area_NN1 in_II the_AT field_NN1 of_IO logistics_NN1 and_CC many_DA2 aspects_NN2 have_VH0 not_XX gathered_VVN that_RG much_DA1 attention_NN1 academically_RR ._. 
</s>
<s>
The_AT issue_NN1 of_IO security_NN1 as_II an_AT1 overall_JJ impediment_NN1 for_IF the_AT logistical_JJ operations_NN2 has_VHZ been_VBN mentioned_VVN but_CCB not_XX studied_VVN ._. 
</s>
<s>
In_II other_JJ fields_NN2 of_IO research_NN1 there_EX is_VBZ though_RR research_VV0 in_II security_NN1 related_JJ issues_NN2 ,_, for_REX21 example_REX22 Thomas_NP1 and_CC Tow_NN1 (_( 2002_MC )_) states_VVZ that_CST human_JJ security_NN1 is_VBZ a_AT1 promising_JJ but_CCB still_RR underdeveloped_JJ paradigmatic_JJ approach_NN1 to_II understanding_VVG contemporary_JJ security_NN1 politics_NN1 ._. 
</s>
<s>
Human_JJ security_NN1 is_VBZ a_AT1 paradigm_NN1 that_CST focuses_VVZ on_II a_AT1 more_RGR human-centered_JJ view_NN1 in_II security_NN1 issues_NN2 related_VVN to_II international_JJ relations_NN2 (_( IR_NN1 )_) ._. 
</s>
<s>
The_AT concept_NN1 of_IO human_JJ security_NN1 challenges_VVZ the_AT traditional_JJ way_NN1 of_IO interpreting_VVG security_NN1 related_VVN to_II states_NN2 and_CC sovereignty_NN1 ._. 
</s>
<s>
(_( Thomas_NP1 and_CC Tow_NN1 ,_, 2002_MC )_) This_DD1 more_RGR people-oriented_JJ view_NN1 could_VM be_VBI related_VVN to_II the_AT field_NN1 of_IO humanitarian_JJ operations_NN2 ,_, but_CCB there_EX has_VHZ so_RG far_RR been_VBN very_RG little_DA1 research_NN1 to_TO fill_VVI this_DD1 gap_NN1 ._. 
</s>
<s>
Therefore_RR the_AT aim_NN1 of_IO this_DD1 paper_NN1 is_VBZ to_TO try_VVI to_TO see_VVI the_AT linkages_NN2 between_II challenges_NN2 and_CC security_NN1 threats_NN2 in_II humanitarian_JJ logistics_NN1 ,_, related_VVN to_II the_AT concept_NN1 of_IO human_JJ security_NN1 ._. 
</s>
<s>
In_II31 addition_II32 to_II33 this_DD1 I_PPIS1 will_VM try_VVI to_TO map_VVI out_RP the_AT major_JJ security_NN1 treats_VVZ in_II humanitarian_JJ logistics_NN1 disaster_NN1 relief_NN1 operations_NN2 ._. 
</s>
<s>
1.1_MC ._. 
</s>
<s>
Relevance_NN1 of_IO the_AT study_NN1 As_II Kovcs_NP2 and_CC Spens_NP1 (_( 2007_MC and_CC 2009_MC )_) conclude_VV0 ,_, the_AT field_NN1 of_IO humanitarian_JJ logistics_NN1 is_VBZ a_AT1 relatively_RR little_RR studied_VVN area_NN1 in_II the_AT field_NN1 of_IO logistics_NN1 and_CC many_DA2 aspects_NN2 have_VH0 not_XX gathered_VVN that_RG much_DA1 attention_NN1 academically_RR ._. 
</s>
<s>
The_AT issue_NN1 of_IO security_NN1 as_II an_AT1 overall_JJ impediment_NN1 for_IF the_AT logistical_JJ operations_NN2 has_VHZ been_VBN mentioned_VVN but_CCB not_XX studied_VVN ._. 
</s>
<s>
Therefore_RR my_APPGE aim_NN1 in_II this_DD1 paper_NN1 is_VBZ to_TO try_VVI to_TO Map_VV0 out_RP the_AT major_JJ security_NN1 treats_VVZ in_II humanitarian_JJ logistics_NN1 disaster_NN1 relief_NN1 operations_NN2 ._. 
</s>
<s>
1.2_MC ._. 
</s>
<s>
Method_NN1 The_AT paper_NN1 will_VM be_VBI a_AT1 literature_NN1 study_NN1 and_CC will_VM focus_VVI on_II reviewing_VVG the_AT existing_JJ literature_NN1 and_CC field_NN1 studies_NN2 to_TO see_VVI what_DDQ views_VVZ they_PPHS2 provide_VV0 on_II the_AT security_NN1 matter_NN1 ._. 
</s>
<s>
The_AT theoretical_JJ aspects_NN2 provided_VVN by_II the_AT research_NN1 articles_NN2 in_II the_AT field_NN1 of_IO both_DB2 humanitarian_JJ logistics_NN1 and_CC human_JJ security_NN1 will_VM be_VBI used_VVN as_CSA analytical_JJ tools_NN2 ._. 
</s>
<s>
The_AT knowledge_NN1 gained_VVN will_VM then_RT be_VBI analyzed_VVN to_TO see_VVI if_CSW there_EX is_VBZ a_AT1 more_RGR general_JJ pattern_NN1 concerning_II security_NN1 threats_NN2 in_II humanitarian_JJ logistics_NN1 ._. 
</s>
<s>
My_APPGE intention_NN1 is_VBZ to_TO use_VVI the_AT current_JJ research_NN1 as_II a_AT1 base_NN1 for_IF creating_VVG a_AT1 framework_NN1 for_IF identifying_VVG challenges_NN2 and_CC risks_NN2 concerning_II security_NN1 in_II the_AT humanitarian_JJ supply_NN1 chain_NN1 ._. 
</s>
<s>
2_MC ._. 
</s>
<s>
Literature_NN1 review_NN1 and_CC theoretical_JJ framework_NN1 In_II this_DD1 literature_NN1 review_VV0 I_PPIS1 will_VM first_MD look_VVI at_II the_AT challenges_NN2 related_VVN to_II security_NN1 that_CST are_VBR mentioned_VVN in_II humanitarian_JJ logistics_NN1 and_CC then_RT elaborate_VV0 on_II the_AT concept_NN1 of_IO human_JJ security_NN1 ._. 
</s>
<s>
This_DD1 theoretical_JJ knowledge_NN1 will_VM then_RT be_VBI used_VVN to_TO analyze_VVI the_AT interrelations_NN2 between_II the_AT two_MC fields_NN2 and_CC possible_JJ patterns_NN2 of_IO security_NN1 threats_NN2 in_II humanitarian_JJ logistics_NN1 ._. 
</s>
<s>
2.1_MC ._. 
</s>
<s>
Humanitarian_JJ logistics_NN1 The_AT aim_NN1 of_IO humanitarian_JJ logistics_NN1 ,_, that_DD1 makes_VVZ it_PPH1 different_JJ from_II basic_JJ business_NN1 logistics_NN1 ,_, is_VBZ that_DD1 humanitarian_JJ logistics_NN1 provide_VV0 beneficiaries_NN2 in_II need_NN1 with_IW the_AT immediate_JJ relief_NN1 in_II different_JJ kinds_NN2 of_IO disasters_NN2 (_( Kovcs_NP2 and_CC Spens_NP1 ,_, 2007_MC )_) ._. 
</s>
<s>
When_CS discussing_VVG humanitarian_JJ logistics_NN1 ,_, it_PPH1 is_VBZ important_JJ to_TO note_VVI the_AT complex_JJ environment_NN1 of_IO humanitarian_JJ operations_NN2 ._. 
</s>
<s>
This_DD1 has_VHZ a_RR21 lot_RR22 to_II do_VD0 with_IW the_AT differences_NN2 in_II disaster-types_NN2 discussed_VVN by_II Van_NP1 Wassenhove_NP1 (_( 2006_MC )_) ._. 
</s>
<s>
Disasters_NN2 can_VM be_VBI either_RR natural_JJ or_CC man-made_JJ ,_, sudden-onset_JJ or_CC slow-onset_NN1 (_( Figure_NN1 1_MC1 )_) ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) This_DD1 division_NN1 of_IO disasters_NN2 would_VM indicate_VVI a_AT1 difference_NN1 in_II context_NN1 of_IO disasters_NN2 ._. 
</s>
<s>
When_CS it_PPH1 comes_VVZ to_II the_AT challenges_NN2 related_VVN to_II the_AT disaster_NN1 types_VVZ Kovcs_NP2 and_CC Spens_NP1 (_( 2009_MC )_) further_RRR elaborate_VV0 on_II the_AT division_NN1 made_VVN by_II Van_NP1 Wassenhove_NP1 (_( 2006_MC )_) by_II discussing_VVG complex_JJ emergencies_NN2 ._. 
</s>
<s>
The_AT issue_NN1 concerning_II complex_JJ emergencies_NN2 is_VBZ that_CST many_DA2 natural_JJ phenomena_NN2 ,_, like_II floods_NN2 ,_, can_VM be_VBI worsened_VVN by_II man_NN1 ,_, making_VVG them_PPHO2 devastating_JJ disasters_NN2 ._. 
</s>
<s>
Also_RR conflict_VV0 situations_NN2 and_CC political_JJ circumstances_NN2 affect_VV0 disasters_NN2 ,_, making_VVG them_PPHO2 more_RGR complex_JJ and_CC making_VVG the_AT work_NN1 in_II the_AT humanitarian_JJ field_NN1 more_RGR challenging_JJ (_( Kocs_NP2 and_CC Spens_NP1 ,_, 2009_MC )_) ._. 
</s>
<s>
Also_RR Sheik_NN1 et_NP1 ._. 
</s>
<s>
Al_NP1 ._. 
</s>
<s>
(_( 2000_MC )_) note_VV0 that_CST the_AT the_AT nature_NN1 of_IO relief_NN1 work_NN1 has_VHZ changes_NN2 dramatically_RR in_II the_AT past_JJ decade_NNT1 as_CSA conflicts_NN2 have_VH0 ceased_VVN being_VBG wars_NN2 between_II states_NN2 and_CC are_VBR now_RT largely_RR internal_JJ conflicts_NN2 taking_VVG place_NN1 amid_II the_AT anarchy_NN1 of_IO weakened_JJ or_CC collapsed_VVD states_NN2 ._. 
</s>
<s>
Roberts_NP1 (_( 2005_MC ,_, p._NN1 17_MC )_) points_VVZ out_RP that_CST there_EX is_VBZ a_AT1 link_NN1 between_II having_VHG a_AT1 basic_JJ understanding_NN1 about_II the_AT risks_NN2 involved_JJ with_IW the_AT work_NN1 in_II a_AT1 conflict_NN1 environment_NN1 and_CC basic_JJ risk_NN1 reduction_NN1 ._. 
</s>
<s>
He_PPHS1 highlights_VVZ the_AT workers_NN2 personal_JJ responsibility_NN1 to_TO guard_VVI their_APPGE safety_NN1 and_CC security_NN1 ._. 
</s>
<s>
The_AT judgment_NN1 of_IO which_DDQ actions_NN2 are_VBR to_TO avoid_VVI is_VBZ in_II the_AT hands_NN2 of_IO the_AT humanitarian_JJ worker_NN1 ,_, when_CS he/she_PPHS1 is_VBZ acting_VVG in_II the_AT field_NN1 ._. 
</s>
<s>
The_AT worker_NN1 should_VM therefore_RR try_VVI to_TO gain_VVI information_NN1 ,_, use_VV0 common-sense_NN1 judgment_NN1 and_CC try_VV0 to_TO do_VDI basic_JJ forecasting_VVG on_II the_AT basis_NN1 of_IO the_AT given_JJ information_NN1 ._. 
</s>
<s>
Roberts_NP1 (_( 2005_MC ,_, p._NN1 18_MC )_) therefore_RR conclude_VV0 that_CST the_AT security_NN1 of_IO individuals_NN2 as_II31 well_II32 as_II33 the_AT organization_NN1 depends_VVZ on_II :_: the_AT individual_JJ behavior_NN1 of_IO workers_NN2 ,_, the_AT workers_NN2 ability_NN1 to_TO listen_VVI and_CC the_AT organizations_NN2 ability_NN1 of_IO information_NN1 exchange_NN1 ._. 
</s>
<s>
(_( Roberts_NP1 ,_, 2005_MC pp._NNU2 17-19_MCMC )_) The_AT humanitarian_JJ space_NN1 has_VHZ the_AT basis_NN1 in_II the_AT humanitarian_JJ principles_NN2 of_IO humanity_NN1 ,_, neutrality_NN1 and_CC impartiality_NN1 ._. 
</s>
<s>
The_AT essential_JJ message_NN1 in_II this_DD1 is_VBZ that_CST the_AT organizations_NN2 operating_VVG in_II the_AT humanitarian_JJ filed_VVN will_VM not_XX influence_VVI the_AT outcome_NN1 of_IO a_AT1 conflict_NN1 with_IW their_APPGE interventions_NN2 ;_; and_CC will_VM not_XX favor_VVI one_MC1 group_NN1 for_IF beneficiaries_NN2 over_II another_DD1 ._. 
</s>
<s>
The_AT space_NN1 refers_VVZ to_II both_DB2 the_AT need_NN1 of_IO the_AT humanitarian_JJ workers_NN2 to_TO do_VDI their_APPGE job_NN1 efficiently_RR ,_, without_IW interference_NN1 ._. 
</s>
<s>
(_( Van_NP1 Wassenhove_NP1 ,_, 2006_MC )_) Larson_NP1 (_( 2011_MC )_) discusses_VVZ the_AT concept_NN1 of_IO the_AT humanitarian_JJ space_NN1 and_CC how_RRQ the_AT loss_NN1 of_IO it_PPH1 can_VM cause_VVI security_NN1 threats_NN2 ,_, since_CS the_AT humanitarian_JJ workers_NN2 might_VM become_VVI targets_NN2 ._. 
</s>
<s>
For_REX21 example_REX22 in_II the_AT US-led_JJ invasion_NN1 of_IO Iraq_NP1 ,_, the_AT local_JJ defendants_NN2 did_VDD nt_XX distinguish_VVI between_II the_AT military_JJ and_CC the_AT humanitarian_JJ workers_NN2 ,_, which_DDQ lead_VV0 to_II them_PPHO2 becoming_VVG targets_NN2 ._. 
</s>
<s>
This_DD1 is_VBZ a_AT1 severe_JJ security_NN1 threat_NN1 ,_, since_CS the_AT military_NN1 is_VBZ increasingly_RR participating_VVG in_II humanitarian_JJ operations_NN2 ,_, distributing_VVG relief_NN1 items_NN2 and_CC working_VVG to_TO provide_VVI security_NN1 to_II the_AT local_JJ community_NN1 ._. 
</s>
<s>
This_DD1 loss_NN1 of_IO humanitarian_JJ space_NN1 threats_NN2 the_AT humanitarian_JJ workers_NN2 ,_, especially_RR in_II humilitarian_JJ relationships_NN2 where_RRQ humanitarian_JJ organizations_NN2 work_VV0 together_RL with_IW the_AT military_JJ ._. 
</s>
<s>
(_( Larson_NN1 ,_, 2011_MC )_) 2.2_MC ._. 
</s>
<s>
Different_JJ levels_NN2 of_IO security_NN1 threats_NN2 In_II humanitarian_JJ operations_NN2 banditry_NN1 and_CC crime_NN1 can_VM also_RR occur_VVI in_II many_DA2 different_JJ situations_NN2 ,_, when_RRQ people_NN in_II need_NN1 or_CC people_NN who_PNQS want_VV0 to_TO take_VVI advantage_NN1 of_IO the_AT situation_NN1 steal_VV0 or_CC otherwise_RR try_VV0 to_TO get_VVI their_APPGE hands_NN2 on_II for_REX21 example_REX22 relief_NN1 items_NN2 (_( Roberts_NP1 ,_, 2005_MC )_) ._. 
</s>
<s>
Mntyvaara_NP1 (_( 2011_MC )_) mentions_VVZ that_CST for_REX21 example_REX22 the_AT Red_JJ Cross_NN1 strives_VVZ to_TO reduce_VVI the_AT risks_NN2 of_IO theft_NN1 and_CC security_NN1 threats_NN2 related_VVN to_II this_DD1 by_II for_REX21 example_REX22 employing_JJ local_JJ security_NN1 companies_NN2 or_CC local_JJ people_NN as_CSA security_NN1 personnel_NN2 ._. 
</s>
<s>
Other_JJ security_NN1 threats_NN2 that_CST humanitarian_JJ workers_NN2 face_VV0 in_II the_AT field_NN1 are_VBR straight_JJ21 forward_JJ22 accidents_NN2 (_( Sheik_NN1 et_NP1 ._. 
</s>
<s>
al_NP1 2000_MC )_) ._. 
</s>
<s>
Ill-health_NN1 do_VD0 nt_XX affect_VVI the_AT immediate_JJ security_NN1 of_IO humanitarian_JJ workers_NN2 ,_, unless_CS an_AT1 illness_NN1 although_CS illness_NN1 is_VBZ a_AT1 direct_JJ threat_NN1 to_II human_JJ life_NN1 ._. 
</s>
<s>
The_AT most_RGT common_JJ illnesses_NN2 amongst_II humanitarian_JJ workers_NN2 are_VBR malaria_NN1 ,_, diarrhea_NN1 and_CC other_JJ blood-borne_JJ diseases_NN2 such_II21 as_II22 hepatitis_NN1 and_CC HIV_NP1 ._. 
</s>
<s>
(_( Roberts_NP1 ,_, 2005_MC )_) ._. 
</s>
<s>
Deaths_NN2 are_VBR the_AT worst_JJT threat_NN1 to_II humanitarian_JJ workers_NN2 ._. 
</s>
<s>
Sheik_NN1 et_NP1 ._. 
</s>
<s>
al_NP1 ._. 
</s>
<s>
(_( 2000_MC )_) have_VH0 in_II their_APPGE study_NN1 concluded_VVD the_AT following_JJ main_JJ causes_NN2 of_IO death_NN1 among_II humanitarian_JJ workers_NN2 :_: international_JJ violence_NN1 ,_, unintended_JJ violence_NN1 ,_, and_CC motor_NN1 vehicle_NN1 accidents_NN2 ._. 
</s>
<s>
Here_RL it_PPH1 is_VBZ also_RR important_JJ to_TO note_VVI that_CST humans_NN2 with_IW weapons_NN2 rather_CS21 than_CS22 motor_VVI vehicles_NN2 pose_VV0 the_AT greatest_JJT threat_NN1 (_( Sheik_NN1 et_NP1 ._. 
</s>
<s>
al_NP1 ._. 
</s>
<s>
2000_MC )_) One_MC1 third_MD of_IO all_DB deaths_NN2 among_II humanitarian_JJ workers_NN2 happened_VVD during_II the_AT first_MD 90_MC days_NNT2 of_IO their_APPGE service_NN1 ,_, and_CC seventeen_MC percent_NNU of_IO these_DD2 were_VBDR during_II the_AT first_MD 30_MC days_NNT2 of_IO service_NN1 ._. 
</s>
<s>
(_( Sheik_NN1 et_NP1 ._. 
</s>
<s>
al_NP1 ._. 
</s>
<s>
2000_MC )_) ._. 
</s>
<s>
This_DD1 is_VBZ essential_JJ information_NN1 since_CS many_DA2 humanitarian_JJ organizations_NN2 have_VH0 their_APPGE delegates_NN2 or_CC voluntary_JJ workers_NN2 working_VVG in_II 90_MC days_NNT2 shifts_NN2 (_( Mntyvaara_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
2.3_MC ._. 
</s>
<s>
The_AT human_JJ security_NN1 paradigm_NN1 Human_NN1 security_NN1 is_VBZ a_AT1 paradigm_NN1 that_CST focuses_VVZ on_II a_AT1 more_RGR human-centered_JJ view_NN1 in_II security_NN1 issues_NN2 related_VVN to_II international_JJ relations_NN2 (_( IR_NN1 )_) and_CC Thomas_NP1 and_CC Tow_NN1 (_( 2002_MC )_) argue_VV0 that_CST the_AT concept_NN1 of_IO human_JJ security_NN1 could_VM be_VBI used_VVN as_II an_AT1 instrument_NN1 in_II solving_VVG issues_NN2 related_VVN to_II IR_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ because_CS human_JJ security_NN1 issues_NN2 do_VD0 not_XX generate_VVI from_II one_MC1 single_JJ source_NN1 such_II21 as_II22 a_AT1 pandemic_JJ ,_, a_AT1 military_JJ conflict_NN1 or_CC an_AT1 environmental_JJ disaster_NN1 ,_, but_CCB the_AT factors_NN2 leading_VVG to_II situations_NN2 threatening_VVG human_JJ security_NN1 are_VBR very_RG complex_JJ and_CC derive_VV0 from_II several_DA2 different_JJ sources_NN2 ._. 
</s>
<s>
When_CS dealing_VVG with_IW human_JJ security_NN1 threats_NN2 large_JJ scale_NN1 activities_NN2 and_CC societal_JJ interrelations_NN2 ,_, such_II21 as_II22 social_JJ and_CC economical_JJ reforms_NN2 in_II31 addition_II32 to_II33 military_JJ involvement_NN1 needs_VVZ to_TO be_VBI considered_VVN in_II restoring_VVG human_JJ security_NN1 ._. 
</s>
<s>
(_( Thomas_NP1 and_CC Tow_NN1 ,_, 2002_MC )_) In_II human_JJ security_NN1 the_AT interrelation_NN1 between_II poverty_NN1 and_CC violence_NN1 is_VBZ acknowledged_VVN and_CC different_JJ kinds_NN2 of_IO development_NN1 policies_NN2 provide_VV0 better_JJR value_NN1 in_II reducing_VVG human_JJ security_NN1 threats_NN2 than_CSN do_VD0 military_JJ involvement_NN1 (_( Glasius_NP1 ,_, 2008_MC )_) ._. 
</s>
<s>
3_MC ._. 
</s>
<s>
Analysis_NN1 Human_NN1 security_NN1 is_VBZ interesting_JJ as_II a_AT1 concept_NN1 in_II humanitarian_JJ logistics_NN1 ,_, because_CS it_PPH1 brings_VVZ in_II the_AT international_JJ aspect_NN1 of_IO policies_NN2 and_CC country_NN1 relations_NN2 that_CST also_RR affect_VV0 the_AT humanitarian_JJ field_NN1 ._. 
</s>
<s>
There_EX is_VBZ a_AT1 wide_JJ range_NN1 of_IO human_JJ security_NN1 issues_NN2 that_CST need_VV0 to_TO be_VBI addressed_VVN and_CC there_EX are_VBR three_MC categories_NN2 of_IO victims_NN2 that_CST need_VV0 special_JJ attention_NN1 :_: the_AT victims_NN2 of_IO wars_NN2 and_CC armed_JJ conflicts_NN2 ,_, socio-economic_JJ disasters_NN2 ,_, and_CC natural_JJ disasters_NN2 ._. 
</s>
<s>
(_( Thomas_NP1 and_CC Tow_NN1 ,_, 2002_MC )_) When_CS looking_VVG at_II this_DD1 categorization_NN1 we_PPIS2 can_VM see_VVI a_AT1 link_NN1 to_II humanitarian_JJ logistics_NN1 ,_, since_CS the_AT humanitarian_JJ field_NN1 is_VBZ involved_JJ in_II all_DB these_DD2 kinds_NN2 of_IO disasters_NN2 (_( Figure_NN1 1_MC1 ._. )_) ._. 
</s>
<s>
In_II the_AT Sheik_NN1 et_NP1 ._. 
</s>
<s>
al_NP1 ._. 
</s>
<s>
(_( 2000_MC )_) study_VV0 it_PPH1 is_VBZ though_RR important_JJ to_TO consider_VVI that_CST when_CS studying_VVG deaths_NN2 of_IO humanitarian_JJ workers_NN2 ,_, UN_NP1 peacekeepers_NN2 have_VH0 been_VBN included_VVN in_II the_AT study_NN1 ._. 
</s>
<s>
These_DD2 are_VBR of_RR21 course_RR22 also_RR actors_NN2 in_II the_AT humanitarian_JJ filed_JJ ,_, but_CCB here_RL we_PPIS2 can_VM see_VVI the_AT line_NN1 blurring_VVG in_II the_AT sense_NN1 Larson_NP1 (_( 2011_MC )_) mentions_VVZ in_II loss_NN1 of_IO humanitarian_JJ space_NN1 ._. 
</s>
<s>
Also_RR Glasius_NP1 (_( 2008_MC )_) mentions_VVZ this_DD1 problem_NN1 area_NN1 as_CSA present_JJ during_II the_AT tsunami_NN2 in_II Indonesian_JJ Aceh_NN1 were_VBDR civilian_JJ relief_NN1 workers_NN2 were_VBDR skeptical_JJ of_IO soldiers_NN2 involvement_NN1 in_II humanitarian_JJ aid_NN1 as_CSA they_PPHS2 did_VDD not_XX believe_VVI a_AT1 military_JJ role_NN1 could_VM be_VBI combined_VVN with_IW relief_NN1 work_NN1 ._. 
</s>
<s>
The_AT notion_NN1 of_IO human_JJ security_NN1 was_VBDZ also_RR mentioned_VVN in_II the_AT critique_NN1 against_II the_AT U.S._NP1 intervention_NN1 in_II Iraq_NP1 ,_, because_CS civilians_NN2 were_VBDR at_II risk_NN1 and_CC there_EX were_VBDR disruptions_NN2 of_IO both_RR food_NN1 and_CC refugee_NN1 flows_NN2 (_( Glasius_NP1 ,_, 2008_MC )_) ._. 
</s>
<s>
Here_RL there_EX is_VBZ again_RT a_AT1 link_NN1 between_II human_JJ security_NN1 concerns_NN2 and_CC humanitarian_JJ logistics_NN1 as_CSA also_RR Larson_NP1 (_( 2011_MC )_) mentions_VVZ this_DD1 lost_VVD humanitarian_JJ space_NN1 as_CSA threatening_VVG humanitarian_JJ workers_NN2 security_NN1 ._. 
</s>
<s>
So_RR the_AT security_NN1 risks_NN2 in_II humanitarian_JJ logistics_NN1 seem_VV0 to_TO be_VBI connected_VVN to_II general_JJ patterns_NN2 of_IO human_JJ security_NN1 ._. 
</s>
<s>
Roberts_NP1 (_( 2005_MC )_) emphasize_VV0 the_AT importance_NN1 of_IO common_JJ sense_NN1 and_CC knowledge_NN1 prior_II21 to_II22 coming_VVG to_II the_AT conflict_NN1 site_NN1 ._. 
</s>
<s>
In_RR21 addition_RR22 we_PPIS2 can_VM also_RR see_VVI that_CST one_PN1 third_MD of_IO all_DB deaths_NN2 happened_VVD during_II the_AT first_MD 90_MC days_NNT2 that_CST the_AT humanitarian_JJ worker_NN1 is_VBZ in_II the_AT field_NN1 (_( Sheik_NN1 et_NP1 ._. 
</s>
<s>
al_NP1 ._. 
</s>
<s>
2000_MC )_) ._. 
</s>
<s>
This_DD1 argues_VVZ for_IF the_AT statement_NN1 of_IO Roberts_NP1 (_( 2005_MC )_) that_DD1 experience_NN1 and_CC common_JJ sense_NN1 is_VBZ to_TO be_VBI used_VVN in_II the_AT field_NN1 ._. 
</s>
<s>
It_PPH1 could_VM also_RR be_VBI argued_VVN that_CST the_AT feedback_NN1 and_CC experience_NN1 of_IO workers_NN2 who_PNQS have_VH0 been_VBN in_II the_AT field_NN1 should_VM be_VBI better_RRR taken_VVN into_II the_AT loop_NN1 of_IO evaluation_NN1 in_II humanitarian_JJ organizations_NN2 ,_, so_CS21 that_CS22 essential_JJ information_NN1 would_VM not_XX be_VBI lost_VVN ._. 
</s>
<s>
As_CSA mentioned_VVN earlier_RRR ,_, the_AT aim_NN1 of_IO humanitarian_JJ logistics_NN1 is_VBZ to_TO provide_VVI beneficiaries_NN2 in_II need_NN1 with_IW the_AT immediate_JJ relief_NN1 in_II different_JJ kinds_NN2 of_IO disasters_NN2 ._. 
</s>
<s>
In_II this_DD1 relief_NN1 work_VV0 the_AT final_JJ aim_NN1 will_VM always_RR be_VBI capacity_NN1 building_NN1 ,_, so_CS21 that_CS22 the_AT community_NN1 has_VHZ better_JJR conditions_NN2 to_TO tackle_VVI any_DD kind_NN1 of_IO disasters_NN2 in_II the_AT future_NN1 ._. 
</s>
<s>
(_( Kovcs_NN2 and_CC Spens_NP1 ,_, 2007_MC )_) ._. 
</s>
<s>
Human_JJ security_NN1 requires_VVZ human_JJ development_NN1 as_CSA Glasius_NP1 (_( 2008_MC )_) states_NN2 and_CC here_RL humanitarian_JJ logistics_NN1 plays_VVZ a_AT1 crucial_JJ role_NN1 in_II bringing_VVG in_II the_AT first_MD contributions_NN2 to_II degelopment_NN1 in_II a_AT1 crisis_NN1 situation_NN1 ._. 
</s>
<s>
The_AT same_DA kind_NN1 of_IO threats_NN2 ,_, like_II climate_NN1 change_NN1 and_CC global_JJ terrorism_NN1 ,_, that_CST Kovcs_NN2 and_CC Spens_NP1 (_( 2009_MC )_) see_VV0 as_CSA challenges_NN2 to_II humanitarian_JJ logistics_NN1 are_VBR mentioned_VVN by_II Glasius_NP1 (_( 2008_MC )_) as_CSA issues_NN2 in_II human_JJ security_NN1 ._. 
</s>
<s>
So_RR therefore_RR it_PPH1 is_VBZ possible_JJ to_TO distinguish_VVI a_AT1 connection_NN1 between_II general_JJ human_JJ security_NN1 threats_NN2 and_CC threats_NN2 and_CC challenges_NN2 faced_VVN by_II humanitarians_NN2 in_II the_AT field_NN1 ._. 
</s>
<s>
There_EX is_VBZ also_RR a_AT1 close_JJ connection_NN1 in_II31 terms_II32 of_II33 the_AT complexities_NN2 Kovcs_NN2 and_CC Spens_NP1 (_( 2009_MC )_) mentions_VVZ ,_, since_CS it_PPH1 derives_VVZ from_II man-made_JJ intervention_NN1 that_CST makes_VVZ disputes_NN2 and_CC disasters_NN2 more_RGR difficult_JJ to_TO handle_VVI ._. 
</s>
<s>
When_CS it_PPH1 then_RT comes_VVZ to_II the_AT more_RGR practical_JJ issues_NN2 concerning_II security_NN1 threats_NN2 of_IO humanitarian_JJ workers_NN2 Sheik_NN1 et_NP1 ._. 
</s>
<s>
al_NP1 ._. 
</s>
<s>
(_( 2000_MC )_) mentions_VVZ the_AT importance_NN1 of_IO giving_VVG the_AT humanitarian_JJ workers_NN2 rest_VV0 and_CC time_NNT1 away_II21 from_II22 their_APPGE job_NN1 ,_, in_BCL21 order_BCL22 to_TO prevent_VVI accidents_NN2 ._. 
</s>
<s>
This_DD1 goes_VVZ in_II31 line_II32 with_II33 the_AT notion_NN1 of_IO Roberts_NP1 (_( 2005_MC )_) who_PNQS conclude_VV0 that_CST both_DB2 the_AT individual_JJ worker_NN1 and_CC the_AT organization_NN1 are_VBR responsible_JJ for_IF the_AT security_NN1 of_IO a_AT1 humanitarian_JJ worker_NN1 ._. 
</s>
<s>
4_MC ._. 
</s>
<s>
Discussion_NN1 and_CC conclusions_NN2 When_CS discussing_VVG humanitarian_JJ logistics_NN1 and_CC security_NN1 threats_NN2 ,_, the_AT complexity_NN1 of_IO disasters_NN2 has_VHZ to_TO be_VBI considered_VVN as_II31 well_II32 as_II33 the_AT linkages_NN2 to_II the_AT context_NN1 of_IO the_AT emergencies_NN2 at_II a_AT1 whole_NN1 ._. 
</s>
<s>
As_CSA I_PPIS1 have_VH0 presented_VVN in_II this_DD1 study_NN1 ,_, there_EX seems_VVZ to_TO be_VBI a_AT1 connection_NN1 between_II the_AT complexity_NN1 of_IO human_JJ security_NN1 and_CC humanitarian_JJ operations_NN2 ,_, since_CS they_PPHS2 both_DB2 derive_VV0 from_II the_AT same_DA kinds_NN2 of_IO global_JJ issues_NN2 ._. 
</s>
<s>
There_EX are_VBR several_DA2 aspects_NN2 of_IO security_NN1 ._. 
</s>
<s>
The_AT responsibility_NN1 of_IO the_AT worker_NN1 and_CC the_AT organization_NN1 he/she_PPHS1 works_VVZ for_IF ,_, the_AT disaster_NN1 type_NN1 ,_, the_AT information_NN1 he/she_PPHS1 has_VHZ and_CC the_AT role_NN1 he/she_PPHS1 is_VBZ seen_VVN in_RP ._. 
</s>
<s>
Therefore_RR the_AT more_RGR general_JJ pattern_NN1 for_IF security_NN1 threats_NN2 seems_VVZ to_TO be_VBI the_AT complexity_NN1 of_IO the_AT context_NN1 ,_, causing_VVG security_NN1 threats_NN2 ._. 
</s>
<s>
The_AT most_RGT common_JJ security_NN1 issues_NN2 seems_VVZ to_TO be_VBI banditry_NN1 and_CC theft_NN1 ,_, severe_JJ diseases_NN2 ,_, accidents_NN2 ,_, and_CC a_AT1 death_NN1 risk_NN1 deriving_VVG from_II military_JJ conflict_NN1 ._. 
</s>
<s>
The_AT risk_NN1 of_IO these_DD2 all_RR can_VM be_VBI decreased_VVN by_II internal_JJ information_NN1 flow_NN1 and_CC personal_JJ responsibility_NN1 and_CC use_NN1 of_IO common_JJ sense_NN1 (_( Roberts_NP1 ,_, 2005_MC )_) ._. 
</s>
<s>
But_CCB from_II a_AT1 more_RGR general_JJ perspective_NN1 of_IO human_JJ security_NN1 ,_, the_AT security_NN1 threats_NN2 caused_VVN by_II complex_JJ emergencies_NN2 ,_, is_VBZ very_RG hard_JJ to_TO eliminate_VVI ._. 
</s>
<s>
This_DD1 study_NN1 is_VBZ limited_VVN ,_, because_CS it_PPH1 is_VBZ done_VDN only_RR as_II a_AT1 literature_NN1 study_NN1 and_CC the_AT literature_NN1 in_II the_AT field_NN1 of_IO humanitarian_JJ logistics_NN1 field_NN1 ,_, is_VBZ ,_, as_CSA previously_RR mentioned_VVN ,_, scarce_JJ ._. 
</s>
<s>
The_AT study_NN1 draws_VVZ conclusions_NN2 on_II a_AT1 very_RG general_JJ level_NN1 ,_, not_XX going_VVG into_II detail_NN1 considering_II different_JJ disaster_NN1 types_NN2 ._. 
</s>
<s>
It_PPH1 could_VM also_RR be_VBI useful_JJ to_TO study_VVI the_AT different_JJ disaster_NN1 types_NN2 per_RR21 se_RR22 to_TO see_VVI at_II the_AT disaster-specific_JJ risks_NN2 and_CC challenges_NN2 ._. 
</s>
<s>
A_AT1 study_NN1 like_II this_DD1 could_VM though_RR be_VBI limited_VVN by_II the_AT intertwined_JJ character_NN1 of_IO the_AT field_NN1 ._. 
</s>
<s>
To_TO get_VVI a_AT1 more_RGR holistic_JJ picture_NN1 ,_, there_EX would_VM be_VBI a_AT1 need_NN1 for_IF a_AT1 wide_JJ empirical_JJ study_NN1 with_IW cross-analysis_NN1 of_IO different_JJ cases_NN2 of_IO humanitarian_JJ operations_NN2 ._. 
</s>
<s>
There_EX are_VBR certainly_RR many_DA2 questions_NN2 for_IF further_JJR research_NN1 to_TO address_VVI ._. 
</s>
<s>
As_CSA mentioned_VVN ,_, comparative_JJ case_NN1 studies_NN2 could_VM be_VBI conducted_VVN for_IF deeper_JJR analysis_NN1 of_IO security_NN1 threats_NN2 ._. 
</s>
<s>
In_II31 addition_II32 to_II33 this_DD1 the_AT preventive_JJ work_NN1 linked_VVN to_II security_NN1 should_VM also_RR be_VBI studied_VVN ,_, as_CSA to_TO see_VVI the_AT real_JJ causes_NN2 of_IO security_NN1 threats_NN2 ._. 
</s>
<s>
This_DD1 kind_NN1 of_IO cause-effect_JJ analysis_NN1 could_VM be_VBI used_VVN to_TO reduce_VVI risks_NN2 in_II the_AT future_NN1 ._. 
</s>
<s>
When_CS discussing_VVG humanitarian_JJ logistics_NN1 ,_, the_AT whole_JJ process_NN1 throughout_II the_AT supply_NN1 chain_NN1 could_VM be_VBI analyzed_VVN ,_, taking_VVG preventive_JJ actions_NN2 into_II consideration_NN1 ._. 
</s>
<s>
The_AT general_JJ conclusion_NN1 of_IO this_DD1 study_NN1 is_VBZ that_CST there_EX seem_VV0 to_TO be_VBI a_AT1 connection_NN1 between_II globalization_NN1 ,_, more_RGR complex_JJ security_NN1 concerns_VVZ in_II conflicts_NN2 and_CC disasters_NN2 which_DDQ leads_VVZ to_II a_AT1 more_RGR complex_JJ issue_NN1 of_IO security_NN1 in_II the_AT humanitarian_JJ field_NN1 as_RR21 well_RR22 ._. 
</s>
<s>
Still_RR the_AT issue_NN1 needs_VVZ further_JJR research_NN1 in_BCL21 order_BCL22 to_TO get_VVI a_AT1 better_JJR understanding_NN1 of_IO the_AT concept_NN1 of_IO security_NN1 in_II humanitarian_JJ logistics_NN1 ._. 
</s>
