<s>
What_DDQ factors_NN2 and_CC motives_NN2 influence_VV0 devoted_JJ wine_NN1 consumers_NN2 purchase_VV0 behavior_NN1 ?_? 2_MC ._. 
</s>
<s>
Introduction_NN1 During_II the_AT past_JJ decade_NNT1 ,_, the_AT consumption_NN1 of_IO wine_NN1 has_VHZ increased_VVN by_II approximately_RR 2%in_FO Finland_NP1 annually_RR ._. 
</s>
<s>
According_II21 to_II22 Alkos_NP1 statistics_NN ,_, over_RG 90_MC %_NNU of_IO the_AT red_NN1 and_CC white_JJ wine_NN1 purchased_VVN in_II 2010_MC cost_VV0 less_DAR than_CSN 10_MC euros_NN2 per_II bottle_NN1 and_CC surprisingly_RR over_RG 50_MC %_NNU less_DAR than_CSN 7_MC euros_NN2 ._. 
</s>
<s>
Nearly_RR 70%_NNU of_IO all_DB wine_NN1 bottles_NN2 available_JJ in_II Alkos_NP1 shelves_NN2 are_VBR priced_VVN over_RG 10_MC Euros_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ clear_JJ that_CST the_AT demand_NN1 and_CC supply_NN1 do_VD0 not_XX match_VVI ._. 
</s>
<s>
This_DD1 study_NN1 concentrated_VVN on_II facts_NN2 which_DDQ could_VM improve_VVI the_AT marketing_NN1 of_IO quality_NN1 wine_NN1 and_CC increase_VV0 consumers_NN2 interest_NN1 towards_II them_PPHO2 ._. 
</s>
<s>
This_DD1 was_VBDZ achieved_VVN by_II identifying_VVG what_DDQ factors_NN2 and_CC motives_NN2 influence_VV0 devoted_JJ wine_NN1 consumers_NN2 purchase_VV0 behavior_NN1 ._. 
</s>
<s>
Previous_JJ research_NN1 has_VHZ shown_VVN that_CST consumers_NN2 interesttowards_RL ,_, knowledgeof_VV0 ,_, and_CC experienceofthe_VV0 wine_NN1 play_VV0 a_AT1 critical_JJ role_NN1 in_II the_AT decision-making_JJ process_NN1 ._. 
</s>
<s>
For_IF this_DD1 reason_NN1 ,_, consumers_NN2 can_VM be_VBI assigned_VVN to_II two_MC groups_NN2 based_VVN on_II their_APPGE enthusiasm_NN1 :_: consumers_NN2 who_PNQS are_VBR highly_RR involved_JJ with_IW wine_NN1 ,_, devoted_JJ wine_NN1 enthusiasts_NN2 and_CC those_DD2 that_CST are_VBR not_XX ._. 
</s>
<s>
Consumers_NN2 level_NN1 of_IO wine_NN1 enthusiasm_NN1 ,_, therefore_RR ,_, shows_VVZ different_JJ factors_NN2 and_CC motives_NN2 behind_II the_AT decision-making_JJ process_NN1 (_( Lockshin_NP1 ,_, 2003_MC ;_; Yan_NP1 ,_, So_RG &Chakravarty,;_NULL 2005_MC )_) ._. 
</s>
<s>
In_II recent_JJ years_NNT2 ,_, researchers_NN2 have_VH0 become_VVN increasingly_RR interested_JJ in_II the_AT influence_NN1 of_IO the_AT wine_NN1 packaging_NN1 ,_, emerging_VVG trends_NN2 such_II21 as_II22 organic_JJ wine_NN1 ,_, as_RG well_RR as_CSA in_II motivational_JJ factors_NN2 e.g._REX nationality_NN1 ,_, culture_NN1 ,_, age_NN1 ,_, or_CC gender_NN1 in_II the_AT process_NN1 ofselecting_VVG a_AT1 bottle_NN1 of_IO wine.Additionally_NNU ,_, the_AT knowledge_NN1 of_IO wine_NN1 consumers_NN2 with_IW low_JJ involvement_NN1 has_VHZ offered_VVN valuable_JJ insight_NN1 into_II the_AT attributes_NN2 ofthe_VV0 purchasebehavior_NN1 (_( Barber_NP1 ,_, Ismail_NP1 &;_NULL Dodd_NP1 ,_, 2008_MC )_) ._. 
</s>
<s>
However_RR ,_, there_EX is_VBZ a_AT1 clear_JJ need_NN1 to_TO increase_VVI in-depth_JJ understanding_NN1 and_CC knowledge_NN1 of_IO devoted_JJ wine_NN1 consumers_NN2 motives_NN2 and_CC factors_NN2 ._. 
</s>
<s>
Wine_NN1 differs_VVZ from_II traditional_JJ consumer_NN1 goods_NN2 due_II21 to_II22 the_AT fact_NN1 that_CST its_APPGE quality_NN1 can_VM not_XX be_VBI judged_VVN until_CS it_PPH1 has_VHZ been_VBN consumed.This_NNU requires_VVZ eitherthe_NN1 use_NN1 of_IO a_AT1 variety_NN1 of_IO information_NN1 sources_NN2 ,_, prior_JJ knowledge_NN1 ,_, and_CC preferences_NN2 (_( Dodd_NP1 ,_, Laverie_NP1 ,_, Wilcox_NP1 &Dohan,;_NULL 2005_MC )_) ,_, or_CC factors_NN2 that_CST happen_VV0 during_II the_AT actual_JJ purchase_NN1 event_NN1 such_II21 as_II22 offers_NN2 ,_, description_NN1 of_IO wines_NN2 characteristics_NN2 ,_, or_CC appearance_NN1 of_IO the_AT wine_NN1 bottle_NN1 ._. 
</s>
<s>
This_DD1 study_NN1 advancesthe_NN1 knowledge_NN1 by_II introducing_VVG a_AT1 new_JJ model-based_JJ theory_NN1 of_IO devoted_JJ consumers_NN2 purchase_VV0 processes_NN2 and_CC interrelationships_NN2 between_II the_AT studied_JJ factors_NN2 and_CC motives_NN2 ._. 
</s>
<s>
3_MC ._. 
</s>
<s>
Literature_NN1 Review_NN1 In_II this_DD1 chapter_NN1 relevant_JJ concepts_NN2 ,_, such_II21 as_II22 product_NN1 involvement_NN1 ,_, perceived_VVD quality_NN1 ,_, and_CC consumer_NN1 knowledge_NN1 ,_, are_VBR discussed_VVN ._. 
</s>
<s>
3.1_MC ._. 
</s>
<s>
Product_NN1 involvement_NN1 Several_DA2 studies_NN2 (_( Lockshin_NP1 ,_, 2003_MC ;_; Yan_NP1 ,_, So_RG &Chakravarty,;_NULL 2005_MC ;_; Dodd_NP1 ,_, Pinkleton_NP1 and_CC Gustafson_NP1 ,_, 1996_MC )_) )_) indicate_VV0 that_DD1 wine_NN1 consumers_NN2 can_VM be_VBI segmented_VVN according_II21 to_II22 their_APPGE level_NN1 of_IO involvement_NN1 to_II low-involvement_NN1 and_CC high-involvement_JJ wine_NN1 consumers_NN2 ._. 
</s>
<s>
Zaichkowsky_NP1 (_( 1985_MC :_: 342_MC )_) defines_VVZ involvement_NN1 as_II a_AT1 persons_NN2 relevance_NN1 of_IO the_AT consumption_NN1 ._. 
</s>
<s>
The_AT relevance_NN1 can_VM be_VBI further_RRR divided_VVN into_II product_NN1 involvement_NN1 and_CC purchase_VV0 decision_NN1 involvement_NN1 (_( Charters_NN2 and_CC Pettigrew_NP1 ,_, 2006_MC )_) ._. 
</s>
<s>
This_DD1 study_NN1 concentrates_VVZ on_II high-involvement_JJ wine_NN1 consumers_NN2 who_PNQS can_VM also_RR be_VBI described_VVN as_CSA devoted_JJ wine_NN1 enthusiasts_NN2 ._. 
</s>
<s>
The_AT study_NN1 of_IO Dodd_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 1996_MC )_) identified_VVD four_MC features_NN2 that_CST characterize_VV0 high-involvement_JJ wine_NN1 consumers_NN2 :_: firstly_RR ,_, they_PPHS2 use_VV0 larger_JJR number_NN1 of_IO information_NN1 sources_NN2 to_TO educate_VVI themselves_PPX2 ._. 
</s>
<s>
Secondly_RR ,_, they_PPHS2 use_VV0 information_NN1 sources_NN2 as_II a_AT1 media_NN to_TO form_VVI opinions_NN2 ._. 
</s>
<s>
Thirdly_RR ,_, high-involvement_JJ wine_NN1 consumers_NN2 are_VBR more_RGR knowledgeable_JJ regarding_II features_NN2 of_IO wine_NN1 such_II21 as_II22 grapes_NN2 or_CC country_NN1 of_IO origin_NN1 ._. 
</s>
<s>
Finally_RR ,_, their_APPGE behavior_NN1 shows_VVZ more_RGR variety-seeking_JJ behaviorthan_NN1 low-involvement_NN1 consumers_NN2 which_DDQ means_VVZ that_CST they_PPHS2 are_VBR more_RGR innovative_JJ and_CC open-minded_JJ when_CS trying_VVG new_JJ products_NN2 and_CC use_VV0 their_APPGE knowledge_NN1 and_CC information_NN1 sources_NN2 to_TO determine_VVI which_DDQ brands_VVZ ,_, wine_NN1 areas_NN2 ,_, or_CC product_NN1 types_NN2 are_VBR of_IO most_DAT interest_NN1 for_IF them_PPHO2 ._. 
</s>
<s>
3.2_MC ._. 
</s>
<s>
Perceived_JJ quality_NN1 The_AT research_NN1 problem_NN1 of_IO this_DD1 study_NN1 is_VBZ to_TO examine_VVI factors_NN2 which_DDQ could_VM improve_VVI the_AT marketing_NN1 of_IO quality_NN1 wines_NN2 and_CC increase_VV0 consumers_NN2 interest_NN1 towards_II them_PPHO2 ._. 
</s>
<s>
Therefore_RR ,_, it_PPH1 is_VBZ important_JJ to_TO understand_VVI how_RRQ the_AT consumers_NN2 perceive_VV0 the_AT quality_NN1 of_IO wine_NN1 ,_, how_RRQ they_PPHS2 evaluate_VV0 it_PPH1 ,_, and_CC how_RRQ the_AT consumers_NN2 level_NN1 of_IO involvement_NN1 influence_VV0 the_AT evaluation_NN1 ._. 
</s>
<s>
According_II21 to_II22 Charters_NN2 and_CC Pettigrew_NP1 (_( 2006_MC )_) there_EX is_VBZ a_AT1 clear_JJ connection_NN1 between_II the_AT perceived_JJ wine_NN1 quality_NN1 and_CC the_AT wine_NN1 consumers_NN2 level_NN1 of_IO interest_NN1 and_CC involvement_NN1 ._. 
</s>
<s>
In_II31 addition_II32 to_II33 that_CST their_APPGE results_NN2 indicated_VVD that_CST higher-involvement_JJ wine_NN1 consumers_NN2 perceive_VV0 quality_NN1 as_CSA objective_JJ ,_, whereas_CS low-involvement_JJ consumers_NN2 conceptualize_VV0 it_PPH1 as_RG subjective_JJ ._. 
</s>
<s>
This_DD1 means_VVZ that_DD1 subjectivity_NN1 correlates_VVZ to_II persons_NN2 own_DA experiences_NN2 and_CC views_NN2 while_CS objectivity_NN1 is_VBZ measured_VVN by_II broader_JJR knowledge_NN1 of_IO wine_NN1 and_CC external_JJ norms_NN2 ._. 
</s>
<s>
Because_CS quality_NN1 can_VM be_VBI viewed_VVN from_II very_RG different_JJ perspectives_NN2 depending_II21 on_II22 the_AT individual_NN1 ,_, researchers_NN2 have_VH0 used_VVN correlates_NN2 of_IO quality_NN1 (_( Garvin_NP1 ,_, 1984_MC )_) in_BCL21 order_BCL22 to_TO define_VVI related_JJ factors_NN2 and_CC motives_NN2 to_TO identify_VVI the_AT meaning_NN1 of_IO quality_NN1 ._. 
</s>
<s>
The_AT broader_JJR knowledge_NN1 of_IO wines_NN2 enables_VVZ high-involvement_JJ wine_NN1 consumers_NN2 to_TO use_VVI more_RGR cognitive_JJ correlates_NN2 to_TO describe_VVI quality_NN1 such_DA as_II complexity_NN1 while_CS low-involvement_JJ wine_NN1 consumers_NN2 appear_VV0 to_TO use_VVI more_RGR sensory_JJ dimensions_NN2 such_II21 as_II22 smoothness_NN1 (_( Charters_NN2 and_CC Pettigrew_NP1 ,_, 2006_MC )_) ._. 
</s>
<s>
Furthermore_RR ,_, low-involvement_JJ consumers_NN2 tend_VV0 to_TO use_VVI price_NN1 as_CSA indicator_NN1 of_IO quality_NN1 while_CS high-involvement_JJ consumers_NN2 see_VV0 quality_NN1 relative_II21 to_II22 situation_NN1 (_( Charters_NN2 and_CC Pettigrew_NP1 ,_, 2006_MC )_) ._. 
</s>
<s>
3.3_MC ._. 
</s>
<s>
Consumer_NN1 knowledge_NN1 Researchers_NN2 have_VH0 found_VVN that_DD1 wine_NN1 education_NN1 and_CC improved_JJ knowledge_NN1 of_IO wines_NN2 increase_VV0 consumers_NN2 interest_NN1 towards_II them_PPHO2 and_CC how_RGQ important_JJ they_PPHS2 consider_VV0 wine_NN1 products_NN2 to_TO be_VBI (_( Taylor_NP1 ,_, Dodd_NP1 and_CC Barber_NP1 ,_, 2009_MC ;_; Park_NP1 and_CC Moon_NN1 ,_, 2003_MC ;_; Brucks_NP1 ,_, 1985_MC ;_; Barber_NP1 ,_, 2008_MC )_) ._. 
</s>
<s>
Therefore_RR ,_, wine_NN1 education_NN1 is_VBZ considered_VVN to_TO be_VBI one_MC1 of_IO the_AT key_JJ factors_NN2 when_RRQ low-involvement_JJ consumers_NN2 gradually_RR turn_VV0 into_II high-involvement_JJ wine_NN1 enthusiasts_NN2 ._. 
</s>
<s>
From_II marketers_NN2 point_NN1 of_IO view_NN1 this_DD1 kind_NN1 of_IO development_NN1 is_VBZ desirable_JJ because_CS high-involvement_JJ wine_NN1 consumers_NN2 tend_VV0 to_TO purchase_VVI larger_JJR quantities_NN2 ,_, higher_RRR priced_VVN products_NN2 ,_, and_CC the_AT variety_NN1 of_IO products_NN2 purchased_VVN is_VBZ greater_JJR (_( Charters_NN2 and_CC Pettigrew_NP1 ,_, 2006_MC )_) ._. 
</s>
<s>
Knowledge_NN1 of_IO wines_NN2 has_VHZ a_AT1 positive_JJ effect_NN1 on_II consumers_NN2 confidence_NN1 in_II wine_NN1 purchase_VV0 decision-making_JJ process_NN1 and_CC increases_VVZ their_APPGE experimentation_NN1 of_IO new_JJ brands_NN2 and_CC product_NN1 types_NN2 ._. 
</s>
<s>
According_II21 to_II22 Park_NP1 and_CC Moon_NN1 (_( 2003_MC )_) products_NN2 can_VM be_VBI categorized_VVN into_II two_MC product_NN1 types_NN2 :_: function_NN1 and_CC performance_NN1 ._. 
</s>
<s>
Functionality_NN1 refers_VVZ to_II utilitarian_JJ value_NN1 while_CS performance_NN1 correlates_VVZ with_IW pleasure_NN1 and_CC hedonic_JJ value_NN1 (_( Taylor_NP1 et_RA21 al._RA22 ,_, 2009_MC )_) ._. 
</s>
<s>
Both_DB2 values_NN2 are_VBR considered_VVN when_CS consumers_NN2 evaluate_VV0 the_AT quality_NN1 ._. 
</s>
<s>
Abstract_JJ concepts_NN2 such_II21 as_II22 quality_NN1 and_CC value_NN1 of_IO products_NN2 bear_VV0 different_JJ meanings_NN2 to_II people_NN ._. 
</s>
<s>
Therefore_RR ,_, they_PPHS2 are_VBR difficult_JJ to_TO measure_VVI ._. 
</s>
<s>
However_RR ,_, quality_NN1 and_CC value_NN1 are_VBR interrelated_JJ and_CC the_AT same_DA dimensions_NN2 of_IO subjectivity_NN1 and_CC objectivity_NN1 apply_VV0 to_TO both_RR value_NN1 and_CC quality_NN1 ._. 
</s>
<s>
One_PN1 can_VM further_RRR argue_VVI that_CST all_DB knowledge_NN1 of_IO consumers_NN2 is_VBZ subject_NN1 and_CC related_VVN to_II their_APPGE experiences_NN2 in_II some_DD way_NN1 or_CC another_DD1 ._. 
</s>
<s>
Yet_RR ,_, objectivity_NN1 is_VBZ increased_VVN at_II the_AT same_DA time_NNT1 with_IW the_AT knowledge_NN1 ._. 
</s>
<s>
Furthermore_RR ,_, the_AT knowledge_NN1 of_IO wine_NN1 and_CC consumers_NN2 value_NN1 perception_NN1 impact_NN1 on_II wine_NN1 preferences_NN2 and_CC appreciation_NN1 of_IO wine_NN1 (_( Taylor_NP1 et_RA21 al._RA22 ,_, 2009_MC )_) ._. 
</s>
<s>
4_MC ._. 
</s>
<s>
Method_NN1 This_DD1 chapter_NN1 focuses_VVZ on_II the_AT methods_NN2 of_IO the_AT study_NN1 ._. 
</s>
<s>
The_AT methodology_NN1 ,_, data_NN collection_NN1 and_CC analysis_NN1 are_VBR presented_VVN ._. 
</s>
<s>
Thus_RR ,_, the_AT trustworthiness_NN1 of_IO data_NN is_VBZ discussed_VVN ._. 
</s>
<s>
4.1_MC ._. 
</s>
<s>
Methodology_NN1 Wine_NN1 consumer_NN1 behavior_NN1 has_VHZ been_VBN studied_VVN from_II both_DB2 qualitative_JJ and_CC quantitative_JJ perspectives_NN2 depending_II21 on_II22 the_AT aim_NN1 ._. 
</s>
<s>
Quantitative_JJ methods_NN2 aim_VV0 at_II verification_NN1 of_IO hypothesis_NN1 and_CC generalization_NN1 of_IO the_AT results_NN2 (_( Hair_NN1 et_RA21 al._RA22 ,_, 2010_MC )_) ;_; whereas_CS the_AT purpose_NN1 of_IO qualitative_JJ studies_NN2 is_VBZ to_TO gain_VVI in-depth_JJ understanding_NN1 from_II smaller_JJR samples_NN2 (_( Patton_NP1 ,_, 2002_MC )_) ._. 
</s>
<s>
Qualitative_JJ research_NN1 was_VBDZ selected_VVN as_II the_AT method_NN1 of_IO this_DD1 study_NN1 in_BCL21 order_BCL22 to_TO gain_VVI deeper_JJR understanding_NN1 of_IO devoted_JJ wine_NN1 consumer_NN1 purchase_NN1 behavior_NN1 and_CC to_TO discover_VVI underlying_JJ factors_NN2 and_CC motives_NN2 which_DDQ have_VH0 an_AT1 impact_NN1 on_II their_APPGE decision-making_NN1 ._. 
</s>
<s>
The_AT choice_NN1 of_IO qualitative_JJ approach_NN1 will_VM add_VVI to_II previous_JJ knowledge_NN1 by_II discovering_VVG new_JJ categories_NN2 and_CC their_APPGE interrelationships_NN2 ._. 
</s>
<s>
Furthermore_RR ,_, the_AT use_NN1 of_IO qualitative_JJ triangulation_NN1 ,_, including_II the_AT combination_NN1 of_IO observation_NN1 and_CC interview_NN1 ,_, was_VBDZ selected_VVN in_BCL21 order_BCL22 to_TO study_VVI why_RRQ and_CC how_RRQ consumers_NN2 act_VV0 in_II a_AT1 certain_JJ way_NN1 ._. 
</s>
<s>
The_AT triangulation_NN1 was_VBDZ also_RR used_VVN to_TO increase_VVI the_AT validity_NN1 and_CC reliability_NN1 of_IO the_AT study_NN1 ._. 
</s>
<s>
The_AT research_NN1 approach_NN1 can_VM be_VBI described_VVN asabductive_JJ because_CS the_AT previous_JJ theories_NN2 of_IO wine_NN1 consumer_NN1 purchase_NN1 behavior_NN1 was_VBDZ utilized_VVN as_II a_AT1 pre-understanding_NN1 when_RRQ formulating_VVG the_AT observation_NN1 and_CC interview_NN1 guides_NN2 and_CC also_RR analyzed_VVD simultaneously_RR with_IW the_AT emerged_JJ results_NN2 of_IO this_DD1 study_NN1 ._. 
</s>
<s>
4.2_MC ._. 
</s>
<s>
Sampling_VVG The_AT target_NN1 population_NN1 of_IO the_AT study_NN1 included_VVD high-involvement_JJ wine_NN1 consumers_NN2 who_PNQS can_VM be_VBI described_VVN to_TO have_VHI enthusiastic_JJ relationship_NN1 with_IW the_AT wine_NN1 ._. 
</s>
<s>
Therefore_RR ,_, the_AT study_NN1 utilizedAlko_NN1 Etiquette_NN1 Wine_NN1 Clubs_NN2 member_NN1 register_NN1 as_II the_AT basis_NN1 for_IF the_AT sample_NN1 selection_NN1 ._. 
</s>
<s>
The_AT sample_NN1 was_VBDZ chosen_VVN randomly_RR so_CS21 that_CS22 all_DB individuals_NN2 had_VHD an_AT1 equal_JJ chance_NN1 of_IO selection_NN1 (_( Hirvonen_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
The_AT homogeneous_JJ sampling_NN1 was_VBDZ chosen_VVN as_II the_AT sampling_NN1 strategy_NN1 of_IO the_AT study_NN1 in_BCL21 order_BCL22 to_TO study_VVI and_CC describe_VVI the_AT segment_NN1 of_IO high-involvement_JJ wine_NN1 consumers_NN2 in-depth_JJ (_( Patton_NP1 ,_, 2002_MC )_) ._. 
</s>
<s>
The_AT sample_NN1 size_NN1 includedone_NN1 informant_NN1 who_PNQS was_VBDZ studied_VVN in-depth_JJ and_CC the_AT results_NN2 gained_VVN from_II him_PPHO1 answered_VVN to_II the_AT purpose_NN1 of_IO the_AT study_NN1 ._. 
</s>
<s>
The_AT sample_NN1 details_NN2 are_VBR described_VVN in_II the_AT table_NN1 1_MC1 ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) 4.3_MC ._. 
</s>
<s>
Data_NN collection_NN1 The_AT data_NN collection_NN1 included_VVD two_MC phases_NN2 :_: firstly_RR ,_, to_TO monitor_VVI the_AT informant_NN1 through_II observation_NN1 when_CS he_PPHS1 did_VDD wine_NN1 shopping_VVG in_RP naturally_RR occurring_VVG situation.The_NNU event_NN1 took_VVD place_NN1 in_II Alko_NP1 ,_, in_II the_AT mall_NN1 of_IO IsoOmena_NP1 ._. 
</s>
<s>
The_AT purpose_NN1 of_IO the_AT observation_NN1 was_VBDZ to_TO monitor_VVI consumers_NN2 behaviour_NN1 ,_, processes_NN2 ,_, and_CC patterns_NN2 when_RRQ he_PPHS1 purchased_VVD wine_NN1 and_CC to_TO increase_VVI pre-understanding_NN1 before_II the_AT second_MD phase_NN1 ._. 
</s>
<s>
Secondly_RR ,_, the_AT same_DA informant_NN1 was_VBDZ interviewed_VVN one_MC1 week_NNT1 laterwith_NN1 the_AT use_NN1 of_IO structured_JJ interview_NN1 strategy_NN1 (_( general_JJ interview_NN1 guide_NN1 approach_NN1 )_) ._. 
</s>
<s>
This_DD1 particular_JJ interview_NN1 technique_NN1 was_VBDZ selected_VVN in_BCL21 order_BCL22 to_TO secure_VVI all_DB relevant_JJ data_NN in_II31 relation_II32 to_II33 the_AT aim_NN1 ,_, to_TO make_VVI the_AT data_NN collection_NN1 more_RGR systematic_JJ ,_, and_CC to_TO enable_VVI probing_JJ (_( Silverman_NP1 ,_, 2006:110_MC )_) ._. 
</s>
<s>
The_AT interview_NN1 method_NN1 was_VBDZ chosen_VVN to_TO find_VVI out_RP informants_NN2 opinions_NN2 ,_, thoughts_NN2 ,_, intentions_NN2 ,_, and_CC feelings_NN2 which_DDQ can_VM not_XX be_VBI gained_VVN through_II observation_NN1 (_( Patton_NP1 ,_, 2002_MC :_: chapter_NN1 7_MC )_) ._. 
</s>
<s>
Besides_RR structured_JJ interview_NN1 strategy_NN1 ,_, the_AT narrative_JJ approach_NN1 was_VBDZ used_VVN at_II the_AT end_NN1 of_IO the_AT interview_NN1 ._. 
</s>
<s>
The_AT informant_NN1 was_VBDZ asked_VVN to_TO tell_VVI a_AT1 story_NN1 about_II the_AT observed_JJ shopping_NN1 event_NN1 in_II his_APPGE own_DA words_NN2 by_II the_AT help_NN1 of_IO auto-memoing_VVG technique_NN1 (_( Spiggle_NP1 ,_, 1994_MC )_) in_II which_DDQ the_AT informant_NN1 was_VBDZ able_JK to_TO look_VVI at_II pictures_NN2 of_IO himself_PPX1 in_BCL21 order_BCL22 to_TO trace_VVI back_RP the_AT feelings_NN2 and_CC thoughts_NN2 ._. 
</s>
<s>
The_AT data_NN from_II the_AT observation_NN1 was_VBDZ collected_VVN with_IW the_AT help_NN1 of_IO observation_NN1 guide_NN1 ._. 
</s>
<s>
Additionally_RR ,_, the_AT researcher_NN1 took_VVD several_DA2 photos_NN2 and_CC made_VVD field_NN1 notes_NN2 ._. 
</s>
<s>
The_AT interview_NN1 was_VBDZ recorded_VVN and_CC transcribed_VVN which_DDQ enabled_VVD iteration_NN1 and_CC increased_JJ trustworthiness_NN1 of_IO the_AT data_NN ._. 
</s>
<s>
Observation_NN1 and_CC interview_NN1 guides_NN2 were_VBDR based_VVN on_II the_AT studies_NN2 of_IO Barber_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2008_MC )_) ;_; Dodd_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 1996_MC )_) ;_; Charters_NN2 and_CC Pettigrew_NP1 (_( 2006_MC )_) ._. 
</s>
<s>
The_AT interviews_NN2 included_VVD following_VVG themes_NN2 :_: 1_MC1 ._. 
</s>
<s>
Meaning_NN1 of_IO wine_NN1 :_: definition_NN1 &;_NULL description_NN1 2_MC ._. 
</s>
<s>
Consumption_NN1 situation_NN1 :_: when_CS &;_NULL with_IW whom_PNQO 3_MC ._. 
</s>
<s>
Purchase_VV0 behavior_NN1 :_: where_RRQ 4_MC ._. 
</s>
<s>
Purchase_VV0 motives_NN2 and_CC factors_NN2 :_: who_PNQS &;_NULL how_RRQ 5_MC ._. 
</s>
<s>
Preferences_NN2 6_MC ._. 
</s>
<s>
Questions_NN2 about_II the_AT observation_NN1 :_: narrative_JJ &;_NULL auto-memoing_JJ technique_NN1 Hirvonen_NN1 (_( 2011_MC )_) 4.4_MC Data_NN analysis_NN1 The_AT raw_JJ data_NN was_VBDZ analyzed_VVN simultaneously_RR with_IW the_AT data_NN collection_NN1 which_DDQ increased_VVD the_AT quality_NN1 ,_, adjusted_VVN the_AT aim_NN1 of_IO the_AT study_NN1 ,_, and_CC enabled_VVD iteration_NN1 as_II a_AT1 part_NN1 of_IO the_AT data_NN analysis_NN1 ._. 
</s>
<s>
The_AT collected_JJ data_NN was_VBDZ then_RT analyzed_VVN in_II four_MC stages_NN2 based_VVN on_II theories_NN2 of_IO Miles_NP1 and_CC Huberman_NP1 ,_, (_( 1994_MC )_) ;_; Spiggle_NP1 (_( 1994_MC )_) ,_, and_CC Silverman_NP1 (_( 2004:153_MC )_) ._. 
</s>
<s>
The_AT process_NN1 of_IO data_NN analysis_NN1 started_VVD by_II understanding_NN1 and_CC organizing_VVG the_AT data_NN and_CC followed_VVN by_II analysis_NN1 of_IO the_AT conclusions_NN2 ,_, and_CC verification_NN1 of_IO the_AT results_NN2 ._. 
</s>
<s>
The_AT process_NN1 of_IO data_NN analysis_NN1 is_VBZ illustrated_VVN in_II the_AT figure_NN1 1_MC1 ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) The_AT first_MD three_MC stages_NN2 of_IO the_AT analysis_NN1 process_NN1 were_VBDR interpreted_VVN and_CC examined_VVN according_II21 to_II22 five_MC techniques_NN2 introduced_VVN bySpiggle_NN1 (_( 1994_MC )_) :_: abstraction_NN1 ,_, categorization_NN1 ,_, dimensionalizion_NN1 ,_, integration_NN1 ,_, and_CC iteration_NN1 ._. 
</s>
<s>
The_AT results_NN2 confirmed_VVN in_II the_AT early_JJ phase_NN1 that_CST the_AT consumersdecision-making_NN1 can_VM be_VBI divided_VVN into_II spontaneous_JJ and_CC pre-determined_JJ purchase_NN1 behavior_NN1 (_( abstraction_NN1 )_) ._. 
</s>
<s>
Categorization_NN1 process_NN1 revealed_VVD five_MC main_JJ factors_NN2 and_CC motives_NN2 which_DDQ influence_VV0 devoted_JJ wine_NN1 consumers_NN2 purchase_VV0 behavior_NN1 ._. 
</s>
<s>
Dimensionalization_NN1 identified_VVN three_MC dimensions_NN2 :_: balance_NN1 between_II trying_VVG new_JJ and_CC buying_VVG favorites_NN2 ,_, planning_VVG or_CC no_AT planning_NN1 ,_, and_CC consumed_VVN at_II home_NN1 or_CC outside_JJ home_NN1 ._. 
</s>
<s>
Axial_JJ coding_NN1 (_( integration_NN1 )_) defined_VVD two_MC new_JJ concepts_NN2 :_: food_NN1 &;_NULL wine_NN1 and_CC enjoyment_NN1 ._. 
</s>
<s>
Iteration_NN1 between_II the_AT observation_NN1 and_CC interview_NN1 was_VBDZ performed_VVN as_II a_AT1 continuous_JJ process_NN1 ._. 
</s>
<s>
6.1_MC ._. 
</s>
<s>
Trustworthiness_NN1 of_IO data_NN The_AT trustworthiness_NN1 of_IO data_NN was_VBDZ evaluated_VVN based_VVN on_II the_AT theoretical_JJ frameworks_NN2 of_IO Lincoln_NP1 and_CC Guba_NP1 (_( 1985_MC )_) ,_, Wallendorf_NP1 &;_NULL Belk_NP1 (_( 1989_MC )_) ,_, and_CC Miles_NP1 &Huberman;_NULL (_( 1994_MC )_) ._. 
</s>
<s>
The_AT assessment_NN1 criteria_NN2 included_VVD pre-understanding_NN1 ,_, credibility_NN1 ,_, transferability_NN1 ,_, dependability_NN1 ,_, confirmability_NN1 ,_, integrity_NN1 ,_, and_CC utilization_NN1 (_( see_VV0 table_NN1 2_MC )_) ._. 
</s>
<s>
Limitations_NN2 of_IO the_AT quality_NN1 will_VM be_VBI discussed_VVN at_II the_AT end_NN1 of_IO this_DD1 chapter_NN1 ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) The_AT limitations_NN2 of_IO the_AT study_NN1 are_VBR now_RT discussed_VVN ._. 
</s>
<s>
The_AT researcher_NN1 is_VBZ a_AT1 member_NN1 of_IO Alko_NP1 Etiquette_NN1 Wine_NN1 Club_NN1 which_DDQ can_VM either_RR be_VBI seen_VVN as_CSA increased_JJ pre-understanding_NN1 or_CC bias_NN1 ._. 
</s>
<s>
The_AT low_JJ number_NN1 of_IO respondents_NN2 can_VM also_RR be_VBI seen_VVN as_CSA limitation_NN1 of_IO the_AT study_NN1 since_CS higher_JJR number_NN1 of_IO respondents_NN2 would_VM have_VHI increased_VVN the_AT validity_NN1 and_CC reliability_NN1 of_IO the_AT study_NN1 ._. 
</s>
<s>
Increased_JJ number_NN1 of_IO informants_NN2 ,_, prolonged_JJ engagement_NN1 ,_, and_CC several_DA2 observations_NN2 with_IW the_AT informant_NN1 would_VM also_RR have_VHI increased_VVN the_AT variability_NN1 of_IO the_AT findings_NN2 ._. 
</s>
<s>
7_MC ._. 
</s>
<s>
Analysis_NN1 In_II this_DD1 section_NN1 the_AT analysis_NN1 of_IO observation_NN1 and_CC interview_NN1 are_VBR discussed_VVN and_CC reported_VVN ._. 
</s>
<s>
7.1_MC ._. 
</s>
<s>
Analysis_NN1 of_IO observation_NN1 Theinformant_NN1 used_VVD a_AT1 wine_NN1 shopping_NN1 list_NN1 and_CC tried_VVD to_TO find_VVI the_AT wines_NN2 in_II the_AT list_NN1 by_II wandering_VVG back_RP and_CC forth_RR between_II the_AT shelves_NN2 ._. 
</s>
<s>
He_PPHS1 picked_VVD bottles_NN2 one_PN1 at_II a_AT1 time_NNT1 and_CC examined_VVD themcarefully_RR by_II reading_VVG the_AT product_NN1 labels_NN2 and_CC Alkos_NP1 descriptions_NN2 in_II the_AT shelves_NN2 before_II putting_VVG them_PPHO2 into_II the_AT shopping_NN1 basket_NN1 ._. 
</s>
<s>
However_RR ,_, he_PPHS1 did_VDD not_XX buy_VVI all_DB the_AT listed_JJ items_NN2 but_CCB refused_VVD to_TO buy_VVI some_DD of_IO the_AT listed_JJ products_NN2 ._. 
</s>
<s>
Instead_RR he_PPHS1 picked_VVD substituting_VVG products_NN2 spontaneously_RR ._. 
</s>
<s>
&lsqb;_( Picture_NN1 &rsqb;_) The_AT informant_NN1 interacted_VVN with_IW the_AT sales_NN person_NN1 when_CS he_PPHS1 searched_VVD for_IF two_MC items_NN2 and_CC asked_VVD sales_NN persons_NN2 opinion_NN1 about_II the_AT wines_NN2 ._. 
</s>
<s>
The_AT communication_NN1 between_II the_AT sales_NN person_NN1 and_CC the_AT informant_NN1 was_VBDZ fluent_JJ and_CC friendly_JJ ._. 
</s>
<s>
The_AT interaction_NN1 with_IW the_AT sales_NN personnel_NN2 indicated_VVD that_CST Alkos_NP1 personnel_NN2 can_VM be_VBI viewed_VVN as_CSA one_MC1 information_NN1 source_NN1 that_CST can_VM influence_VVI informants_NN2 purchase_VV0 behavior_NN1 ._. 
</s>
<s>
The_AT informant_NN1 concentrated_VVN on_II examining_VVG mostly_RR wines_NN2 but_CCB he_PPHS1 also_RR bought_VVN a_AT1 vacuum_NN1 pump_NN1 and_CC special_JJ edition_NN1 beers_NN2 ._. 
</s>
<s>
The_AT later_JJR examination_NN1 of_IO the_AT bought_VVN bottles_NN2 showed_VVD concentration_NN1 on_II red_JJ wines_NN2 (_( 4_MC of_IO 6_MC )_) and_CC wines_NN2 from_II Italy_NP1 (_( 3_MC of_IO 6_MC )_) ._. 
</s>
<s>
Half_DB of_IO the_AT products_NN2 were_VBDR from_II the_AT New_JJ World_NN1 and_CC half_DB from_II Europe_NP1 ._. 
</s>
<s>
The_AT average_JJ price_NN1 per_II bottle_NN1 was_VBDZ around_RG 10_MC euros._NNU 7.2_MC ._. 
</s>
<s>
Analysis_NN1 of_IO interview_NN1 The_AT interview_NN1 confirmed_VVD the_AT findings_NN2 from_II the_AT observation_NN1 ._. 
</s>
<s>
The_AT informant_NN1 said_VVD that_CST he_PPHS1 uses_VVZ prior_JJ shopping_NN1 list_NN1 approximately_RR half_DB of_IO the_AT times_NNT2 and_CC relies_VVZ on_II favorite_JJ brands_NN2 or_CC shops_NN2 otherwise_RR spontaneously_RR the_AT other_JJ half_NN1 ._. 
</s>
<s>
According_II21 to_II22 him_PPHO1 spontaneous_JJ shopping_NN1 is_VBZ influenced_VVN by_II Alkos_NP1 appealing_JJ wine_NN1 descriptions_NN2 from_II which_DDQ he_PPHS1 looks_VVZ for_IF meaningful_JJ magic_JJ words_NN2 and_CC novelties_NN2 from_II familiar_JJ producers_NN2 ,_, favorite_JJ areas_NN2 ,_, or_CC grapes_NN2 ._. 
</s>
<s>
He_PPHS1 also_RR stated_VVD that_CST besides_II his_APPGE own_DA experiences_NN2 ,_, thewine_VV0 knowledge_NN1 has_VHZ an_AT1 effect_NN1 on_II his_APPGE spontaneous_JJ shopping_NN1 ._. 
</s>
<s>
The_AT respondent_NN1 listed_JJ wine_NN1 literature_NN1 ,_, magazines_NN2 ,_, tastings_NN2 ,_, Alko_NP1 and_CC its_APPGE personnel_NN2 ,_, wine_NN1 clubs_NN2 ,_, friends_NN2 and_CC family_NN1 ,_, own_DA experiences_NN2 ,_, internet_NN1 ,_, restaurants_NN2 ,_, as_II31 well_II32 as_II33 wineries_NN2 and_CC special_JJ wine_NN1 shops_NN2 abroad_RL as_CSA information_NN1 sources_NN2 which_DDQ influence_VV0 his_APPGE purchase_NN1 behavior_NN1 ._. 
</s>
<s>
The_AT purchase_NN1 location_NN1 played_VVD a_AT1 major_JJ roll_NN1 to_II the_AT respondent_NN1 ._. 
</s>
<s>
He_PPHS1 divided_VVD the_AT purchase_NN1 locations_NN2 into_II Finland_NP1 and_CC abroad_RL when_CS travelling_VVG ._. 
</s>
<s>
He_PPHS1 characterized_VVD Alko_NP1 to_II either_DD1 Convenience_NN1 Alko_NN1 which_DDQ has_VHZ a_AT1 convenient_JJ location_NN1 or_CC to_II Service_NN1 Alko_NN1 which_DDQ has_VHZ better_JJR wine_NN1 selection_NN1 and_CC more_RGR knowledgeable_JJ personnel_NN2 ._. 
</s>
<s>
Abroad_RL he_PPHS1 buys_VVZ wine_NN1 from_II the_AT airports_NN2 ,_, ferries_NN2 ,_, straight_RR from_II the_AT wineries_NN2 ,_, or_CC from_II specialized_JJ wine_NN1 shops_NN2 ._. 
</s>
<s>
The_AT respondent_NN1 said_VVD that_CST both_DB2 the_AT occasion_NN1 when_CS the_AT wine_NN1 is_VBZ consumed_VVN and_CC with_IW whom_PNQO the_AT wine_NN1 is_VBZ consumed_VVN has_VHZ a_AT1 major_JJ effect_NN1 on_II the_AT choice_NN1 of_IO wine_NN1 ._. 
</s>
<s>
He_PPHS1 consumes_VVZ wine_NN1 home_RL with_IW food_NN1 or_CC as_II an_AT1 enjoyment_NN1 ._. 
</s>
<s>
Occasions_NN2 when_RRQ the_AT wine_NN1 is_VBZ consumed_VVN outside_RL included_VVD work-related_JJ happenings_NN2 ,_, gatherings_NN2 with_IW friends_NN2 ,_, or_CC eating_VVG at_II restaurants_NN2 ._. 
</s>
<s>
Furthermore_RR ,_, he_PPHS1 consumes_VVZ wine_NN1 with_IW his_APPGE family_NN1 members_NN2 ,_, friends_NN2 ,_, and_CC people_NN from_II work_NN1 ,_, and_CC sometimes_RT alone_RR ._. 
</s>
<s>
At_II the_AT end_NN1 he_PPHS1 said_VVD that_CST there_EX are_VBR some_DD factors_NN2 which_DDQ hinder_VV0 him_PPHO1 from_II particular_JJ purchase_NN1 behavior_NN1 ._. 
</s>
<s>
He_PPHS1 would_VM like_VVI order_NN1 directly_RR from_II Alkos_NP1 separate_JJ ordering_NN1 system_NN1 (_( minimum_JJ order_NN1 quantity_NN1 is_VBZ 6_MC bottles_NN2 per_II item_NN1 )_) ,_, straight_RR from_II wineries_NN2 or_CC wine_NN1 shops_NN2 abroad_RL if_CS he_PPHS1 had_VHD space_NN1 to_II storage_NN1 them_PPHO2 properly_RR or_CC if_CS the_AT quantities_NN2 were_VBDR smaller_JJR ._. 
</s>
<s>
8_MC ._. 
</s>
<s>
Results_NN2 and_CC discussion_NN1 This_DD1 study_NN1 concentrated_VVN on_II facts_NN2 which_DDQ could_VM improve_VVI the_AT marketing_NN1 of_IO quality_NN1 wines_NN2 and_CC increase_VV0 consumers_NN2 interest_NN1 towards_II them_PPHO2 ._. 
</s>
<s>
That_DD1 was_VBDZ achieved_VVN by_II identifying_VVG what_DDQ factors_NN2 and_CC motives_NN2 influence_VV0 devoted_JJ wine_NN1 consumers_NN2 purchase_VV0 behavior_NN1 ._. 
</s>
<s>
In_II this_DD1 section_NN1 ,_, the_AT results_NN2 are_VBR reported_VVN and_CC discussed_VVN ._. 
</s>
<s>
Wine_NN1 enthusiasts_NN2 consider_VV0 wine_NN1 as_CSA enjoyment_NN1 ,_, source_NN1 of_IO relaxation_NN1 ,_, and_CC gastronomical_JJ experience_NN1 to_II which_DDQ they_PPHS2 relate_VV0 positive_JJ images_NN2 such_II21 as_II22 travelling_NN1 ,_, social_JJ life_NN1 ,_, and_CC leisure_NN1 time.Therefore_NNU ,_, it_PPH1 is_VBZ suggested_VVN that_CST the_AT use_NN1 of_IO these_DD2 positive_JJ images_NN2 could_VM be_VBI seen_VVN beneficiary_NN1 in_II marketing_NN1 of_IO quality_NN1 wines.Furthermore_NNU ,_, the_AT quality_NN1 of_IO wine_NN1 was_VBDZ described_VVN as_CSA balanced_VVN ,_, sophisticated_JJ ,_, rich_JJ in_II flavors_NN2 ,_, or_CC innovative_JJ ._. 
</s>
<s>
The_AT price_NN1 was_VBDZ not_XX considered_VVN as_II the_AT indicator_NN1 of_IO quality_NN1 as_II such_DA ,_, like_VV0 for_IF low-involvement_JJ wine_NN1 consumers_NN2 ,_, but_CCB was_VBDZ rather_RR described_VVN to_TO be_VBI in_II par_NN1 with_IW the_AT taste_NN1 ._. 
</s>
<s>
However_RR ,_, it_PPH1 was_VBDZ also_RR mentioned_VVN that_CST higher_JJR price_NN1 means_VVZ usually_RR higher_JJR quality_NN1 ._. 
</s>
<s>
The_AT results_NN2 showed_VVD that_CST the_AT decision-making_JJ process_NN1 has_VHZ two_MC levels_NN2 :_: Firstly_RR ,_, the_AT wine_NN1 purchase_NN1 behavior_NN1 can_VM be_VBI divided_VVN into_II either_RR spontaneous_JJ or_CC pre-determined_JJ ._. 
</s>
<s>
Secondly_RR ,_, the_AT study_NN1 indicated_VVD that_CST the_AT next_MD level_NN1 includes_VVZ five_MC categories_NN2 :_: purchase_VV0 location_NN1 ,_, information_NN1 sources_NN2 ,_, occasion_NN1 when_CS the_AT wine_NN1 is_VBZ consumed_VVN ,_, with_IW whom_PNQO the_AT wine_NN1 is_VBZ consumed_VVN ,_, and_CC hindering_VVG factors_NN2 which_DDQ can_VM be_VBI turned_VVN into_II future_JJ possibilities_NN2 (_( see_VV0 table_NN1 3_MC )_) ._. 
</s>
<s>
The_AT study_NN1 suggests_VVZ that_CST the_AT marketing_NN1 of_IO quality_NN1 wines_NN2 can_VM benefit_VVI from_II discovering_VVG marketing_NN1 possibilities_NN2 in_II these_DD2 categories_NN2 of_IO factors_NN2 and_CC motives_NN2 ._. 
</s>
<s>
The_AT results_NN2 discovered_VVD the_AT importance_NN1 of_IO information_NN1 sources_NN2 which_DDQ can_VM also_RR be_VBI confirmed_VVN by_II earlier_JJR studies_NN2 (_( see_VV0 for_REX21 example_REX22 Dodd_NP1 et_RA21 al_RA22 ,_, 1996_MC ;_; Taylor_NP1 et_RA21 al_RA22 ,_, 2009_MC )_) how_RRQ developing_JJ consumers_NN2 knowledge_NN1 through_II wine_NN1 education_NN1 or_CC the_AT use_NN1 of_IO external_JJ information_NN1 sources_NN2 can_VM turn_VVI low-involvement_JJ wine_NN1 consumers_NN2 to_II high-involvement_JJ enthusiasts_NN2 ._. 
</s>
<s>
In_II this_DD1 way_NN1 the_AT variety_NN1 of_IO purchased_JJ wines_NN2 increases_NN2 and_CC the_AT price-range_NN1 expands_VVZ which_DDQ then_RT results_VVZ in_II the_AT increase_NN1 of_IO quality_NN1 wines_NN2 ._. 
</s>
<s>
Therefore_RR ,_, special_JJ attention_NN1 is_VBZ suggested_VVN to_TO be_VBI paid_VVN to_II the_AT utilization_NN1 of_IO information_NN1 sources_NN2 ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) 
</s>
