<s>
Leaders_NN2 are_VBR born_VVN not_XX made_VVN Introduction_NN1 The_AT age_NN1 old_JJ saying_NN1 of_IO being_VBG born_VVN a_AT1 leader_NN1 is_VBZ commonly_RR used_VVN without_IW giving_VVG the_AT ramifications_NN2 of_IO it_PPH1 much_RR thought_VVN ._. 
</s>
<s>
One_MC1 of_IO the_AT unspoken_JJ assumptions_NN2 is_VBZ that_CST the_AT person_NN1 was_VBDZ not_XX made_VVN a_AT1 leader_NN1 ,_, but_CCB rather_RR he_PPHS1 had_VHD the_AT qualities_NN2 of_IO a_AT1 leader_NN1 already_RR when_CS born_VVN ,_, or_CC rather_RR ;_; leaders_NN2 are_VBR born_VVN ,_, not_XX made_VVN ._. 
</s>
<s>
This_DD1 ,_, of_RR21 course_RR22 ,_, is_VBZ quite_RG a_AT1 controversial_JJ statement_NN1 ,_, as_CS21 if_CS22 this_DD1 were_VBDR true_JJ ,_, courses_NN2 such_II21 as_II22 leadership_NN1 would_VM not_XX be_VBI necessary_JJ at_RR21 all_RR22 ._. 
</s>
<s>
This_DD1 approach_NN1 is_VBZ actually_RR one_MC1 of_IO the_AT first_MD attempts_NN2 to_TO systematically_RR study_VVI leadership_NN1 ,_, called_VVN the_AT great_JJ man_NN1 theories_NN2 ._. 
</s>
<s>
These_DD2 studies_NN2 focused_VVN on_II studying_VVG great_JJ leaders_NN2 such_II21 as_II22 Thomas_NP1 Jefferson_NP1 or_CC Mohandas_NP2 Ghandi_NP1 and_CC finding_VVG innate_JJ qualities_NN2 and_CC characteristics_NN2 that_CST they_PPHS2 possessed_VVD (_( Northouse_NP1 ,_, 15_MC )_) ._. 
</s>
<s>
Meaning_VVG that_CST the_AT studies_NN2 were_VBDR focusing_VVG on_II the_AT person_NN1 itself_PPX1 and_CC his_APPGE biological_JJ personality_NN1 traits_NN2 that_CST were_VBDR inherited_VVN ,_, i.e._REX he/she_PPHS1 was_VBDZ born_VVN with_IW them_PPHO2 ._. 
</s>
<s>
It_PPH1 is_VBZ important_JJ to_TO define_VVI born_VVN ,_, because_CS though_CS a_AT1 person_NN1 is_VBZ born_VVN with_IW these_DD2 traits_NN2 it_PPH1 is_VBZ still_RR necessary_JJ to_TO develop_VVI them_PPHO2 with_IW upbringing_NN1 and_CC education_NN1 ._. 
</s>
<s>
The_AT traits_NN2 ,_, skills_NN2 and_CC style_NN1 approach_NN1 will_VM be_VBI used_VVN to_TO try_VVI and_CC clarify_VVI wether_VV0 or_CC not_XX leadership_NN1 is_VBZ hereditary_JJ ._. 
</s>
<s>
Traits_NN2 Approach_VV0 Firstly_RR ,_, in_II examining_VVG this_DD1 statement_NN1 ,_, a_AT1 historical_JJ perspective_NN1 to_II the_AT traits_NN2 studies_NN2 is_VBZ useful_JJ ,_, as_CSA I_PPIS1 would_VM assume_VVI ,_, many_DA2 people_NN still_RR operate_VV0 under_II the_AT pretense_NN1 that_CST great_JJ leaders_NN2 are_VBR simply_RR born_VVN ._. 
</s>
<s>
Although_CS there_EX is_VBZ some_DD truth_NN1 to_II this_DD1 belief_NN1 ,_, a_AT1 more_RGR complete_JJ picture_NN1 is_VBZ necessary_JJ to_TO explain_VVI the_AT flaws_NN2 behind_II this_DD1 reckoning_NN1 ._. 
</s>
<s>
The_AT great_JJ man_NN1 theory_NN1 mentioned_VVN above_RL ,_, concentrated_VVN on_II identifying_VVG specific_JJ traits_NN2 that_CST clearly_RR differentiated_VVN leaders_NN2 from_II followers_NN2 (_( Bass_NP1 ,_, 1990_MC ;_; Jago_NP1 1982_MC ,_, cited_VVN in_II Northouse_NP1 2007_MC )_) ._. 
</s>
<s>
However_RR in_II the_AT mid-1900s_MC2 ,_, Stogdill_NP1 suggested_VVD that_CST no_AT one_MC1 set_NN1 of_IO traits_NN2 were_VBDR consistent_JJ when_CS a_AT1 variety_NN1 of_IO situations_NN2 were_VBDR taken_VVN into_II account_NN1 ._. 
</s>
<s>
Stogdill_NP1 summarised_VVD the_AT different_JJ studies_NN2 and_CC surmised_VVD that_CST the_AT traits_NN2 that_CST comprise_VV0 the_AT difference_NN1 between_II leaders_NN2 and_CC subordinates_NN2 are_VBR :_: intelligence_NN1 ,_, alertness_NN1 ,_, insight_NN1 ,_, responsibility_NN1 ,_, initiative_NN1 ,_, persistence_NN1 ,_, self-confidence_NN1 ,_, and_CC sociability_NN1 ._. 
</s>
<s>
The_AT most_RGT important_JJ point_NN1 was_VBDZ that_CST individuals_NN2 do_VD0 not_XX simply_RR become_VVI leaders_NN2 because_CS they_PPHS2 possess_VV0 the_AT traits_NN2 ,_, it_PPH1 is_VBZ a_AT1 specific_JJ situation_NN1 that_CST is_VBZ relevant_JJ to_II these_DD2 traits_NN2 that_CST makes_VVZ a_AT1 leader_NN1 (_( Northouse_NP1 ,_, 2007_MC )_) ._. 
</s>
<s>
As_CSA we_PPIS2 are_VBR talking_VVG about_II historical_JJ studies_NN2 ,_, of_RR21 course_RR22 the_AT big_JJ question_NN1 of_IO gender_NN1 pops_VVZ up_RP ,_, especially_RR as_CSA the_AT traditional_JJ leader_NN1 is_VBZ seen_VVN as_II a_AT1 male_JJ figure_NN1 ._. 
</s>
<s>
In_II Mann_NP1 's_GE (_( Mann_NP1 ,_, 1959_MC ,_, cited_VVN in_II Northouse_NP1 2007_MC )_) findings_NN2 he_PPHS1 stated_VVD that_CST characteristics_NN2 such_II21 as_II22 masculinity_NN1 ,_, and_CC dominance_NN1 were_VBDR one_MC1 of_IO the_AT traits_NN2 that_CST were_VBDR found_VVN in_II leaders_NN2 ._. 
</s>
<s>
Which_DDQ was_VBDZ probably_RR more_DAR than_CSN true_JJ at_II this_DD1 point_NN1 in_II time_NNT1 ._. 
</s>
<s>
Mann_NP1 even_RR points_VVZ out_RP that_DD1 conservatism_NN1 was_VBDZ one_MC1 of_IO the_AT important_JJ traits_NN2 in_II leaders_NN2 ,_, which_DDQ is_VBZ quite_RG humorous_JJ when_CS comparing_VVG to_II todays_NN2 requirements_NN2 for_IF leaders_NN2 ._. 
</s>
<s>
Even_RR Lord_NP1 ._. 
</s>
<s>
et_NP1 ._. 
</s>
<s>
al_NP1 ._. 
</s>
<s>
States_VVZ that_CST one_MC1 of_IO the_AT leader_NN1 traits_NN2 is_VBZ masculinity_NN1 as_RG late_RR as_CSA 1986_MC ._. 
</s>
<s>
This_DD1 research_NN1 was_VBDZ mostly_RR based_VVN on_II the_AT fact_NN1 that_CST leaders_NN2 are_VBR born_VVN with_IW these_DD2 traits_NN2 and_CC that_CST these_DD2 same_DA traits_NN2 are_VBR necessary_JJ to_TO become_VVI a_AT1 leader_NN1 ._. 
</s>
<s>
In_II 1991_MC the_AT traits_NN2 approach_NN1 was_VBDZ fine-tuned_VVN by_II Kirkpatrick_NP1 and_CC Locke_NP1 (_( 1991_MC ,_, cited_VVN in_II Northouse_NP1 2007_MC )_) who_PNQS stated_VVD that_CST leaders_NN2 differ_VV0 from_II their_APPGE counterparts_NN2 in_II six_MC traits_NN2 ;_; drive_VV0 ,_, desire_VV0 to_TO lead_VVI ,_, honesty_NN1 and_CC integrity_NN1 ,_, self-confidence_NN1 ,_, cognitive_JJ ability_NN1 ,_, and_CC knowledge_NN1 of_IO the_AT business_NN1 ._. 
</s>
<s>
This_DD1 in_II itself_PPX1 is_VBZ not_XX so_RG revolutionary_JJ ,_, however_RRQV they_PPHS2 stated_VVD that_CST individuals_NN2 can_VM be_VBI born_VVN with_IW them_PPHO2 or_CC learn_VV0 them_PPHO2 or_CC both_DB2 ._. 
</s>
<s>
As_CSA such_DA the_AT term_NN1 traits_NN2 ,_, which_DDQ has_VHZ historically_RR been_VBN used_VVN to_TO imply_VVI genetic_JJ traits_NN2 ,_, also_RR means_VVZ ones_NN2 which_DDQ have_VH0 been_VBN learned_VVN ._. 
</s>
<s>
The_AT traits_NN2 theory_NN1 has_VHZ over_RG a_AT1 hundred_NNO years_NNT2 of_IO research_NN1 to_TO back_VVI it_PPH1 up_RP ,_, yet_RR the_AT traits_NN2 it_PPH1 has_VHZ produced_VVN are_VBR still_RR not_XX consistent_JJ with_IW each_PPX221 other_PPX222 and_CC sometimes_RT arbitrary_JJ ,_, and_CC many_DA2 still_RR believe_VV0 in_II traits_NN2 as_CSA being_VBG built_VVN in_RP ,_, and_CC not_XX learnable_JJ ._. 
</s>
<s>
Emotional_JJ Intelligence_NN1 Secondly_RR ,_, being_VBG born_VVN a_AT1 leader_NN1 ,_, does_VDZ not_XX really_RR hold_VVI up_RP against_II tough_JJ inspection_NN1 ,_, as_CSA the_AT next_MD case_NN1 of_IO emotional_JJ intelligence_NN1 comes_VVZ into_II play_NN1 ._. 
</s>
<s>
Emotional_JJ intelligence_NN1 being_VBG all_RR the_AT rage_NN1 lately_RR in_II the_AT corporate_JJ world_NN1 and_CC something_PN1 which_DDQ one_PN1 definitely_RR ca_VM n't_XX be_VBI born_VVN with_IW ._. 
</s>
<s>
Emotional_JJ intelligence_NN1 ,_, as_CSA the_AT name_NN1 suggests_VVZ ,_, has_VHZ to_TO do_VDI with_IW the_AT emotional_JJ part_NN1 of_IO the_AT thinking_NN1 process_NN1 rather_II21 than_II22 the_AT cognitive_JJ one_PN1 (_( Northouse_NP1 ,_, 2007_MC )_) ._. 
</s>
<s>
It_PPH1 is_VBZ the_AT EQ_NN1 (_( Emotional_JJ quota_NN1 )_) rather_II21 than_II22 the_AT IQ_NN1 (_( intelligence_NN1 quota_NN1 )_) ._. 
</s>
<s>
The_AT fact_NN1 that_CST ,_, leaders_NN2 must_VM be_VBI able_JK to_TO understand_VVI and_CC have_VHI empathy_NN1 towards_II their_APPGE subordinates_NN2 in_BCL21 order_BCL22 to_TO foster_VVI a_AT1 working_JJ relationship_NN1 ._. 
</s>
<s>
The_AT ability_NN1 to_TO effectively_RR manage_VVI ones_NN2 own_DA emotions_NN2 and_CC emotions_NN2 in_II relationship_NN1 to_II others_NN2 is_VBZ paramount_JJ to_II being_VBG a_AT1 good_JJ leader_NN1 ._. 
</s>
<s>
In_II a_AT1 paper_NN1 written_VVN by_II Cary_NP1 Cherniss_NP1 on_II emotional_JJ intelligence_NN1 ,_, she_PPHS1 quotes_VVZ many_DA2 researches_NN2 that_CST show_VV0 the_AT importance_NN1 of_IO EQ_NN1 in_II31 relation_II32 to_II33 IQ_NN1 ._. 
</s>
<s>
For_REX21 example_REX22 the_AT Somerville_NP1 study_NN1 followed_VVD 450_MC boys_NN2 over_II a_AT1 40_MC year_NNT1 phase_NN1 and_CC concluded_VVD that_DD1 IQ_NN1 had_VHD little_RR to_II no_AT relation_NN1 in_II the_AT success_NN1 of_IO their_APPGE lives_NN2 ._. 
</s>
<s>
The_AT biggest_JJT differences_NN2 were_VBDR childhood_NN1 abilities_NN2 such_II21 as_II22 being_VBG able_JK to_TO handle_VVI frustration_NN1 ,_, control_VV0 emotions_NN2 ,_, and_CC get_VV0 along_RR with_IW people_NN (_( Cherniss_NP1 ,_, 2000_MC )_) ._. 
</s>
<s>
These_DD2 sound_VV0 like_II very_RG basic_JJ abilities_NN2 ,_, which_DDQ in_II essence_NN1 they_PPHS2 are_VBR ,_, but_CCB the_AT point_NN1 being_NN1 that_CST the_AT ability_NN1 to_TO master_VVI these_DD2 emotions_NN2 is_VBZ anything_RR21 but_RR22 child_NN1 's_GE play_NN1 ._. 
</s>
<s>
These_DD2 abilities_NN2 are_VBR ones_NN2 which_DDQ have_VH0 to_TO ,_, by_II definition_NN1 ,_, be_VBI honed_VVN as_II a_AT1 child_NN1 and_CC are_VBR a_AT1 vital_JJ part_NN1 of_IO growing_VVG up_RP ._. 
</s>
<s>
No_AT child_NN1 that_CST has_VHZ been_VBN brought_VVN up_RP by_II a_AT1 lax_JJ and_CC uncaring_JJ parent_NN1 can_VM naturally_RR inhibit_VVI and_CC control_VVI its_APPGE emotions_NN2 ,_, it_PPH1 is_VBZ the_AT teaching_NN1 a_AT1 loving_JJ of_IO a_AT1 caring_JJ parent_NN1 that_CST nurtures_VVZ a_AT1 child_NN1 to_TO be_VBI emotionally_RR balanced_VVN ._. 
</s>
<s>
Rather_II21 than_II22 being_VBG overly_RR intelligent_JJ ,_, the_AT qualities_NN2 of_IO being_VBG able_JK to_TO persist_VVI in_II the_AT face_NN1 of_IO difficulty_NN1 and_CC get_VV0 along_RR with_IW e.g._REX colleagues_NN2 is_VBZ more_RGR important_JJ for_IF success_NN1 (_( Cherniss_NP1 ,_, 2000_MC )_) ._. 
</s>
<s>
A_AT1 further_JJR study_NN1 showed_VVD that_CST most_DAT effective_JJ leaders_NN2 in_II the_AT US_NP1 Navy_NN1 were_VBDR warmer_JJR ,_, emotionally_RR expressive_JJ ,_, dramatic_JJ and_CC sociable_JJ ,_, in_II other_JJ words_NN2 had_VHD high_JJ EQs_NN2 ._. 
</s>
<s>
In_II other_JJ words_NN2 EQ_NN1 is_VBZ not_XX something_PN1 that_CST one_PN1 is_VBZ born_VVN with_IW and_CC the_AT fact_NN1 that_CST it_PPH1 is_VBZ so_RG important_JJ to_II leaders_NN2 points_VVZ to_II the_AT fact_NN1 that_CST leaders_NN2 can_VM definitely_RR ,_, and_CC are_VBR definitely_RR being_VBG made_VVN all_DB the_AT time_NNT1 ._. 
</s>
<s>
Skills_NN2 Approach_VV0 The_AT Third_MD approach_NN1 utilized_VVN in_II this_DD1 essay_NN1 is_VBZ the_AT Skills_NN2 approach_NN1 ._. 
</s>
<s>
As_II31 opposed_II32 to_II33 the_AT traits_NN2 theory_NN1 ,_, the_AT skills_NN2 theory_NN1 is_VBZ based_VVN on_II the_AT skills_NN2 and_CC abilities_NN2 of_IO a_AT1 leader_NN1 that_CST can_VM be_VBI learned_VVN and_CC developed_VVN ._. 
</s>
<s>
It_PPH1 goes_VVZ without_IW saying_VVG that_CST simply_RR the_AT fact_NN1 that_CST there_EX is_VBZ a_AT1 whole_JJ approach_NN1 on_II learning_VVG leadership_NN1 skills_NN2 obviously_RR points_VVZ to_II the_AT fact_NN1 that_CST leaders_NN2 are_VBR not_XX simply_RR born_VVN ._. 
</s>
<s>
The_AT skills_NN2 approach_NN1 states_VVZ that_CST although_CS the_AT personality_NN1 traits_NN2 are_VBR important_JJ ,_, knowledge_NN1 and_CC actual_JJ ability_NN1 are_VBR necessary_JJ for_IF effective_JJ leadership_NN1 (_( Northouse_NP1 ,_, 2007_MC )_) ._. 
</s>
<s>
The_AT limited_JJ and_CC narrow_JJ view_NN1 of_IO leadership_NN1 we_PPIS2 were_VBDR presented_VVN in_II the_AT traits_NN2 view_NN1 is_VBZ broadened_VVN up_RP by_II the_AT skills_NN2 approach_NN1 ._. 
</s>
<s>
Instead_II21 of_II22 focusing_VVG solely_RR on_II definitive_JJ traits_NN2 ,_, the_AT idea_NN1 was_VBDZ to_TO determine_VVI developable_JJ skills_NN2 ._. 
</s>
<s>
The_AT three-skills_NN2 approach_VV0 as_CSA it_PPH1 is_VBZ known_VVN from_II the_AT research_NN1 of_IO Robert_NP1 Katz_NP1 ,_, argued_VVD that_CST the_AT traits_NN2 approach_NN1 is_VBZ what_DDQ leaders_NN2 are_VBR ,_, and_CC the_AT skills_NN2 approach_NN1 is_VBZ what_DDQ they_PPHS2 can_VM accomplish_VVI (_( Northouse_NP1 ,_, 2007_MC )_) ._. 
</s>
<s>
So_RR is_VBZ a_AT1 person_NN1 is_VBZ capable_JJ of_IO learning_VVG from_II their_APPGE experiences_NN2 they_PPHS2 are_VBR capable_JJ of_IO acquiring_VVG leadership_NN1 ._. 
</s>
<s>
Meaning_VVG that_CST we_PPIS2 come_VV0 to_II the_AT approach_NN1 where_CS leadership_NN1 is_VBZ made_VVN and_CC not_XX inherited_VVN ._. 
</s>
<s>
Katz'_JJ approach_NN1 was_VBDZ fine_RR tuned_VVN into_II the_AT modern_JJ and_CC empirical_JJ skills_NN2 theory_NN1 known_VVN today_RT ._. 
</s>
<s>
This_DD1 modern_JJ theory_NN1 states_VVZ that_CST at_II the_AT heart_NN1 of_IO the_AT skills_NN2 model_NN1 is_VBZ competencies_NN2 ._. 
</s>
<s>
Which_DDQ is_VBZ further_RRR divided_VVN into_II Problem-solving_NN1 skills_NN2 ,_, social_JJ judgement_NN1 skills_NN2 ,_, and_CC knowledge_NN1 ._. 
</s>
<s>
These_DD2 subheadings_NN2 will_VM be_VBI analyzed_VVN with_II31 reference_II32 to_II33 the_AT question_NN1 of_IO being_VBG born_VVN a_AT1 leader_NN1 ._. 
</s>
<s>
Problem-solving_NN1 skills_NN2 are_VBR defined_VVN as_II a_AT1 leaders_NN2 creative_JJ ability_NN1 to_TO solve_VVI ill-defined_JJ organizational_JJ problems_NN2 (_( Northouse_NP1 ,_, 2007_MC )_) ._. 
</s>
<s>
It_PPH1 may_VM well_RR be_VBI that_CST some_DD people_NN are_VBR born_VVN with_IW traits_NN2 that_CST if_CS properly_RR nurtured_VVN lead_NN1 to_II developed_JJ problem-solving_NN1 skills_NN2 ,_, however_RRQV it_PPH1 is_VBZ exactly_RR the_AT upbringing_NN1 and_CC education_NN1 that_CST perfect_VV0 this_DD1 skill_NN1 ._. 
</s>
<s>
Social_JJ Judgment_NN1 skills_NN2 relate_VV0 directly_RR to_II emotional_JJ intelligence_NN1 which_DDQ can_VM be_VBI read_VVN about_II above_RL ._. 
</s>
<s>
The_AT third_MD aspect_NN1 is_VBZ knowledge_NN1 ,_, which_DDQ adds_VVZ a_AT1 bit_NN1 of_IO both_DB2 born_VVN and_CC made_VVN into_II the_AT analysis_NN1 ._. 
</s>
<s>
Part_NN1 of_IO knowledge_NN1 is_VBZ the_AT accumulation_NN1 of_IO information_NN1 over_II a_AT1 period_NN1 of_IO time_NNT1 ,_, every_AT1 leader_NN1 needs_VVZ to_TO know_VVI the_AT ins_NN2 and_CC outs_NN2 of_IO their_APPGE specific_JJ task_NN1 (_( Northouse_NP1 ,_, 2007_MC )_) ._. 
</s>
<s>
This_DD1 represent_VV0 the_AT part_NN1 of_IO leaders_NN2 being_VBG made_VVN ._. 
</s>
<s>
However_RR ,_, the_AT other_JJ part_NN1 of_IO knowledge_NN1 is_VBZ the_AT storing_VVG and_CC organizing_NN1 of_IO this_DD1 information_NN1 into_II mental_JJ structures_NN2 called_VVN schema_NN1 ._. 
</s>
<s>
As_CSA information_NN1 is_VBZ stored_VVN and_CC organized_VVN it_PPH1 becomes_VVZ more_RGR meaningful_JJ and_CC knowledge_NN1 is_VBZ created_VVN (_( Northouse_NP1 2007_MC )_) ._. 
</s>
<s>
These_DD2 complex_JJ brain_NN1 functions_NN2 are_VBR something_PN1 that_CST some_DD people_NN are_VBR born_VVN with_IW and_CC although_CS much_DA1 can_VM be_VBI developed_VVN and_CC learned_VVN upon_II ,_, this_DD1 constitutes_VVZ a_AT1 skill_NN1 which_DDQ a_AT1 person_NN1 can_VM and_CC is_VBZ born_VVN with_IW ._. 
</s>
<s>
This_DD1 ties_VVZ in_RP with_IW the_AT attribute_NN1 of_IO general_JJ cognitive_JJ ability_NN1 (_( GCA_NP1 )_) which_DDQ is_VBZ listed_VVN under_II the_AT individual_JJ aspects_NN2 of_IO the_AT skills_NN2 model_NN1 ._. 
</s>
<s>
In_II this_DD1 section_NN1 Northouse_NN1 (_( 2007:48_MC )_) goes_VVZ as_CS31 far_CS32 as_CS33 saying_VVG that_DD1 general_JJ cognitive_JJ ability_NN1 is_VBZ linked_VVN to_II biology_NN1 ,_, not_XX to_II experience._NNU GCA_NN1 is_VBZ described_VVN as_II core_NN1 intelligence_NN1 ,_, something_PN1 the_AT brain_NN1 is_VBZ born_VVN with_IW and_CC grows_VVZ and_CC expands_VVZ during_II early_JJ adulthood_NN1 and_CC declines_VVZ with_IW age_NN1 ._. 
</s>
<s>
GCA_NP1 is_VBZ of_IO the_AT utmost_JJ importance_NN1 in_II problem-solving_NN1 and_CC knowledge_NN1 and_CC is_VBZ therefore_RR important_JJ for_IF leadership_NN1 ._. 
</s>
<s>
Essentially_RR ,_, something_PN1 one_PN1 is_VBZ biologically_RR born_VVN with_IW ._. 
</s>
<s>
Motivation_NN1 is_VBZ the_AT last_MD attribute_NN1 in_II this_DD1 approach_NN1 ._. 
</s>
<s>
Without_IW being_VBG motivated_VVN there_RL is_VBZ no_AT leadership_NN1 ._. 
</s>
<s>
A_AT1 leader_NN1 has_VHZ to_TO firstly_RR ,_, be_VBI willing_JJ to_TO lead_VVI to_TO even_RR be_VBI able_JK to_TO ._. 
</s>
<s>
Leaders_NN2 must_VM want_VVI to_TO exert_VVI their_APPGE influences_NN2 and_CC be_VBI committed_VVN to_II the_AT social_JJ good_JJ of_IO the_AT organization_NN1 in_II question_NN1 (_( Northouse_NP1 ,_, 2007_MC )_) ._. 
</s>
<s>
Motivation_NN1 is_VBZ a_AT1 tough_JJ attribute_NN1 to_TO classify_VVI into_II wether_VV0 it_PPH1 is_VBZ a_AT1 biological_JJ trait_NN1 or_CC something_PN1 that_CST is_VBZ learned_VVN ._. 
</s>
<s>
According_II21 to_II22 one_MC1 study_NN1 ,_, academic_JJ motivation_NN1 is_VBZ directly_RR related_VVN to_II parenting_NN1 practices_NN2 and_CC the_AT quality_NN1 of_IO the_AT home_NN1 environment_NN1 (_( Luster_NP1 ,_, Lekskul_NP1 ,_, Oh_UH ,_, 2004_MC )_) ._. 
</s>
<s>
Academic_JJ motivation_NN1 being_VBG important_JJ of_RR21 course_RR22 to_TO develop_VVI other_JJ attributes_NN2 such_II21 as_II22 knowledge_NN1 or_CC cognitive_JJ ability_NN1 ,_, even_CS21 though_CS22 we_PPIS2 are_VBR referring_VVG to_II motivation_NN1 in_RR21 general_RR22 ._. 
</s>
<s>
So_RR it_PPH1 seems_VVZ as_CS21 if_CS22 this_DD1 important_JJ leadership_NN1 characteristic_NN1 is_VBZ something_PN1 which_DDQ is_VBZ learned_VVN during_II adolescence_NN1 ._. 
</s>
<s>
Style_NN1 Approach_NN1 Lastly_RR ,_, the_AT approach_NN1 that_CST will_VM be_VBI analyzed_VVN here_RL is_VBZ the_AT style_NN1 approach_NN1 ,_, which_DDQ emphasizes_VVZ the_AT behavior_NN1 of_IO the_AT leader_NN1 ._. 
</s>
<s>
The_AT style_NN1 approach_NN1 is_VBZ based_VVN on_II two_MC different_JJ kinds_NN2 of_IO leadership_NN1 behaviors_NN2 task_NN1 and_CC relationship_NN1 behaviors_NN2 (_( Northouse_NP1 ,_, 2007_MC )_) ._. 
</s>
<s>
The_AT style_NN1 approach_NN1 sets_VVZ out_RP to_TO explain_VVI how_RRQ leaders_NN2 combine_VV0 these_DD2 two_MC approaches_NN2 to_TO create_VVI effective_JJ leading_JJ ._. 
</s>
<s>
This_DD1 is_VBZ an_AT1 interesting_JJ approach_NN1 to_TO end_VVI this_DD1 essay_NN1 with_IW as_II it_PPH1 aims_VVZ to_TO understand_VVI what_DDQ types_NN2 of_IO behaviors_NN2 leaders_NN2 are_VBR prone_JJ to_TO ._. 
</s>
<s>
As_CSA we_PPIS2 have_VH0 now_RT seen_VVN the_AT different_JJ personal_JJ traits_NN2 of_IO leadership_NN1 can_VM be_VBI either_RR born_VVN with_IW or_CC developed_VVD ._. 
</s>
<s>
Some_DD of_IO these_DD2 styles_NN2 will_VM now_RT be_VBI analyzed_VVN to_TO determine_VVI what_DDQ sort_NN1 of_IO traits_NN2 they_PPHS2 require_VV0 ,_, and_CC wether_VV0 good_JJ leaders_NN2 can_VM only_RR be_VBI someone_PN1 who_PNQS has_VHZ simply_RR been_VBN taught_VVN leadership_NN1 ._. 
</s>
<s>
The_AT style_NN1 approach_NN1 is_VBZ popularly_RR portrayed_VVN with_IW the_AT leadership_NN1 grid_NN1 where_CS different_JJ styles_NN2 are_VBR given_VVN two_MC sets_NN2 of_IO point_NN1 from_II 1-9._MCMC e.g._REX Authority_NN1 compliance_NN1 :_: (_( 9,1_MC )_) ._. 
</s>
<s>
In_II this_DD1 style_NN1 there_EX is_VBZ not_XX much_DA1 communication_NN1 with_IW subordinates_NN2 except_VV0 to_TO relay_VVI instructions_NN2 ,_, the_AT leader_NN1 is_VBZ very_RG over-powering_JJ (_( Northouse_NP1 ,_, 2007_MC )_) ._. 
</s>
<s>
This_DD1 would_VM be_VBI a_AT1 very_RG simple_JJ leadership_NN1 style_NN1 ,_, one_PN1 which_DDQ do_VD0 not_XX require_VVI many_DA2 hereditary_JJ traits_NN2 ,_, and_CC can_VM be_VBI quite_RG easily_RR developed_VVN ._. 
</s>
<s>
A_AT1 stern_JJ style_NN1 of_IO leadership_NN1 that_CST is_VBZ overtly_RR conservative_JJ ._. 
</s>
<s>
Not_XX a_AT1 great_JJ style_NN1 of_IO leadership_NN1 ,_, but_CCB still_RR a_AT1 style_NN1 that_CST most_DAT people_NN could_VM learn_VVI ._. 
</s>
<s>
The_AT country_NN1 club_NN1 style_NN1 of_IO leading_JJ scores_NN2 the_AT same_DA amount_NN1 (_( 1,9_MC )_) but_CCB on_II the_AT other_JJ side_NN1 of_IO the_AT scale_NN1 ._. 
</s>
<s>
This_DD1 style_NN1 requires_VVZ a_AT1 lot_NN1 of_IO EQ_NN1 ,_, where_CS everyone_PN1 is_VBZ made_VVN to_TO feel_VVI as_RG comfortable_JJ as_CSA possible_JJ with_IW a_AT1 positive_JJ and_CC uncontroversial_JJ climate_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ again_RT not_XX something_PN1 one_PN1 is_VBZ born_VVN with_IW ,_, but_CCB depends_VVZ on_II the_AT upbringing_NN1 and_CC parenting_NN1 that_CST the_AT person_NN1 has_VHZ experienced_VVN ._. 
</s>
<s>
A_AT1 neglected_JJ child_NN1 will_VM probably_RR have_VHI a_AT1 skewered_JJ emotional_JJ intelligence_NN1 ._. 
</s>
<s>
Lastly_RR the_AT team_NN1 management_NN1 style_NN1 of_IO leading_JJ (_( 9,9_MC )_) is_VBZ one_MC1 where_CS a_AT1 high_JJ priority_NN1 is_VBZ set_VVN both_RR on_II the_AT tasks_NN2 and_CC the_AT interpersonal_JJ relationships_NN2 (_( Northouse_NP1 ,_, 2007_MC )_) ._. 
</s>
<s>
This_DD1 is_VBZ where_RRQ cognitive_JJ prowess_NN1 comes_VVZ into_II play_NN1 ._. 
</s>
<s>
Without_IW the_AT ability_NN1 to_TO use_VVI the_AT knowledge_NN1 in_II a_AT1 way_NN1 where_RRQ tasks_NN2 and_CC relationships_NN2 can_VM be_VBI balanced_VVN ,_, it_PPH1 is_VBZ not_XX possible_JJ to_TO reach_VVI this_DD1 level_NN1 of_IO leadership_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ the_AT highest_JJT scoring_NN1 leadership_NN1 style_NN1 and_CC therefore_RR also_RR the_AT best_JJT ._. 
</s>
<s>
This_DD1 requires_VVZ the_AT born_JJ with_IW ability_NN1 of_IO high_JJ general_JJ cognitive_JJ ability_NN1 ._. 
</s>
<s>
Conclusion_NN1 In_II conclusion_NN1 ,_, the_AT ability_NN1 to_TO be_VBI a_AT1 leader_NN1 and_CC a_AT1 good_JJ one_PN1 at_II that_DD1 depends_VVZ on_II many_DA2 factors_NN2 ._. 
</s>
<s>
Wether_VV0 these_DD2 factors_NN2 are_VBR something_PN1 one_PN1 is_VBZ born_VVN with_IW or_CC not_XX is_VBZ up_RP for_IF debate_NN1 ._. 
</s>
<s>
Most_DAT of_IO the_AT factors_NN2 analyzed_VVD herein_RR point_VV0 to_II the_AT fact_NN1 that_CST one_PN1 is_VBZ not_XX born_VVN with_IW the_AT necessary_JJ characteristics_NN2 ,_, but_CCB that_DD1 they_PPHS2 are_VBR attained_VVN later_RRR in_II life_NN1 ._. 
</s>
<s>
However_RR ,_, as_CSA the_AT last_MD example_NN1 points_VVZ out_RP general_JJ cognitive_JJ ability_NN1 stands_VVZ out_RP as_II a_AT1 trait_NN1 which_DDQ is_VBZ strictly_RR hereditary_JJ ._. 
</s>
<s>
It_PPH1 is_VBZ the_AT basic_JJ framework_NN1 and_CC capacity_NN1 of_IO the_AT brain_NN1 ._. 
</s>
<s>
Although_CS people_NN will_VM have_VHI to_TO develop_VVI this_DD1 ability_NN1 to_TO make_VVI it_PPH1 usable_JJ ,_, it_PPH1 is_VBZ a_AT1 slight_JJ advantage_NN1 ._. 
</s>
<s>
We_PPIS2 are_VBR however_RR reminded_VVN that_CST for_IF this_DD1 ability_NN1 to_TO actually_RR exhibit_VVI and_CC edge_NN1 would_VM mean_VVI that_CST all_DB other_JJ leadership_NN1 abilities_NN2 are_VBR on_II par_NN1 ,_, which_DDQ is_VBZ highly_RR unlikely_JJ ._. 
</s>
<s>
Overall_RR ,_, there_EX are_VBR definitely_RR traits_NN2 that_CST help_VV0 in_II becoming_VVG a_AT1 well-balanced_JJ leader_NN1 ._. 
</s>
<s>
Ultimately_RR these_DD2 traits_NN2 are_VBR all_DB moot_JJ unless_CS they_PPHS2 are_VBR harnessed_VVN by_II caring_JJ parents_NN2 and_CC a_AT1 balanced_JJ upbringing_NN1 and_CC education_NN1 ._. 
</s>
<s>
Leaders_NN2 are_VBR made_VVN ,_, not_XX born_VVN ._. 
</s>
