<s>
Deregulation_NN1 of_IO the_AT Swedish_JJ pharmacy_NN1 monopole_NN1 Introduction_NN1 Because_II21 of_II22 the_AT safety_NN1 concerns_VVZ the_AT pharmacy_NN1 sector_NN1 has_VHZ always_RR been_VBN a_AT1 target_NN1 for_IF regulations_NN2 of_IO different_JJ kind_NN1 ._. 
</s>
<s>
In_II many_DA2 cases_NN2 the_AT government_NN1 has_VHZ been_VBN playing_VVG a_AT1 major_JJ role_NN1 in_II this_DD1 regulation_NN1 ._. 
</s>
<s>
One_MC1 of_IO the_AT most_RGT extreme_JJ cases_NN2 could_VM previously_RR be_VBI found_VVN in_II Sweden_NP1 ._. 
</s>
<s>
Up_II21 until_II22 2010_MC the_AT whole_JJ pharmaceutical_JJ trade_NN1 was_VBDZ totally_RR controlled_VVN by_II the_AT Swedish_JJ government_NN1 ._. 
</s>
<s>
During_II the_AT year_NNT1 of_IO 2010_MC the_AT monopoly_NN1 was_VBDZ abolished_VVN and_CC anyone_PN1 (_( meeting_VVG certain_JJ legal_JJ requirements_NN2 )_) could_VM start_VVI selling_VVG pharmaceuticals_NN2 in_II Sweden_NP1 ._. 
</s>
<s>
The_AT deregulation_NN1 of_IO a_AT1 state_NN1 run_NN1 monopoly_NN1 is_VBZ an_AT1 interesting_JJ phenomenon_NN1 in_II itself_PPX1 ,_, as_CSA an_AT1 empty_JJ field_NN1 is_VBZ colonized_VVN by_II new_JJ actors_NN2 ._. 
</s>
<s>
But_II21 for_II22 countries_NN2 like_II Finland_NP1 ,_, with_IW a_AT1 strictly_RR regulated_VVN pharmaceutical_JJ ,_, market_VV0 the_AT process_NN1 is_VBZ of_IO special_JJ interest_NN1 as_II the_AT future_JJ decisions_NN2 in_II this_DD1 area_NN1 might_VM be_VBI much_RR dependent_JJ on_II the_AT consequences_NN2 of_IO the_AT event_NN1 in_II Sweden_NP1 ._. 
</s>
<s>
The_AT Finnish_JJ and_CC Swedish_JJ societies_NN2 are_VBR very_RG similar_JJ and_CC therefore_RR relatively_RR easy_JJ to_TO compare_VVI ._. 
</s>
<s>
The_AT reasons_NN2 for_IF the_AT deregulation_NN1 laid_VVN in_II making_VVG the_AT pharmaceutical_JJ market_NN1 more_RGR consumer-friendly_JJ ._. 
</s>
<s>
The_AT inability_NN1 to_TO adapt_VVI to_II customer_NN1 needs_NN2 was_VBDZ one_MC1 of_IO the_AT main_JJ reasons_NN2 for_IF the_AT deregulation_NN1 process_NN1 ,_, which_DDQ was_VBDZ pointed_VVN out_RP in_II the_AT research_NN1 carried_VVD out_RP prior_II21 to_II22 initiating_VVG the_AT process_NN1 (_( Swedish_JJ government_NN1 ,_, 2007_MC )_) ._. 
</s>
<s>
One_MC1 year_NNT1 after_II the_AT actual_JJ deregulation_NN1 the_AT first_MD figures_NN2 indicating_VVG the_AT results_NN2 of_IO the_AT process_NN1 are_VBR starting_VVG to_TO show_VVI ._. 
</s>
<s>
Although_CS it_PPH1 is_VBZ still_RR very_RG early_JJ to_TO draw_VVI final_JJ conclusions_NN2 of_IO the_AT whole_JJ process_NN1 ,_, an_AT1 early_JJ analysis_NN1 could_VM give_VVI indications_NN2 on_II the_AT success_NN1 of_IO this_DD1 major_JJ change_NN1 ._. 
</s>
<s>
The_AT consumers_NN2 and_CC their_APPGE situation_NN1 are_VBR especially_RR interesting_JJ at_II this_DD1 point_NN1 ,_, as_CSA they_PPHS2 were_VBDR pointed_VVN out_RP as_II the_AT main_JJ reason_NN1 for_IF the_AT change_NN1 ._. 
</s>
<s>
Even_CS21 if_CS22 some_DD of_IO the_AT problems_NN2 found_VVN in_II the_AT research_NN1 ,_, done_VDN prior_II21 to_II22 the_AT deregulation_NN1 ,_, can_VM be_VBI addressed_VVN by_II opening_VVG the_AT market_NN1 to_II new_JJ actors_NN2 ,_, there_EX is_VBZ still_JJ areas_NN2 that_CST might_VM not_XX improve_VVI ._. 
</s>
<s>
Sweden_NP1 is_VBZ a_AT1 big_JJ country_NN1 with_IW long_JJ distances_NN2 ._. 
</s>
<s>
Have_VH0 the_AT improvements_NN2 affected_VVN all_DB pharmacy_NN1 customers_NN2 equally_RR and_CC have_VH0 the_AT problems_NN2 indentified_VVN actually_RR improved_VVN ?_? 
</s>
<s>
In_BCL21 order_BCL22 to_TO study_VVI these_DD2 questions_NN2 a_AT1 SWOT-analysis_NN1 is_VBZ made_VVN comparing_VVG the_AT situation_NN1 prior_II21 to_II22 the_AT deregulation_NN1 to_II the_AT current_JJ situation_NN1 ,_, based_VVN on_II figures_NN2 published_VVN by_II the_AT pharmacy_NN1 sector_NN1 and_CC focusing_VVG on_II the_AT problems_NN2 identified_VVN in_II the_AT evaluation_NN1 studies_NN2 done_VDN prior_II21 to_II22 the_AT deregulation_NN1 ._. 
</s>
<s>
A_AT1 SWOT-analysis_NN1 reviews_VVZ the_AT market_NN1 based_VVN on_II its_APPGE strengths_NN2 ,_, weaknesses_NN2 ,_, opportunities_NN2 and_CC threats_NN2 and_CC can_VM be_VBI used_VVN to_TO analyze_VVI larger_JJR entireties_NN2 (_( **citation_FO needed**_FO )_) ._. 
</s>
<s>
This_DD1 paper_NN1 is_VBZ divided_VVN into_II three_MC main_JJ sections_NN2 ;_; A_ZZ1 short_JJ introduction_NN1 to_II the_AT deregulation_NN1 process_NN1 of_IO the_AT pharmacy_NN1 market_NN1 in_II Sweden_NP1 ;_; A_AT1 SWOT-analysis_NN1 of_IO the_AT consumers_NN2 situation_NN1 before_II and_CC after_CS the_AT abolishment_NN1 of_IO the_AT monopoly_NN1 ;_; general_JJ conclusions_NN2 of_IO the_AT situation_NN1 right_RR now_RT and_CC a_AT1 picture_NN1 of_IO what_DDQ further_RRR changes_VVZ the_AT future_NN1 might_VM bring_VVI to_II this_DD1 area_NN1 ._. 
</s>
<s>
In_II31 addition_II32 to_II33 this_DD1 the_AT impact_NN1 these_DD2 events_NN2 could_VM have_VHI on_II the_AT Finnish_JJ market_NN1 will_VM also_RR be_VBI discussed_VVN ._. 
</s>
<s>
Background_NN1 Background_NN1 on_II when/why_RRQ the_AT monopoly_NN1 was_VBDZ formed_VVN and_CC why_RRQ it_PPH1 was_VBDZ abolished_VVN Consumer_NN1 demand_NN1 on_II the_AT pharmacy_NN1 market_NN1 According_II21 to_II22 a_AT1 study_NN1 conducted_VVN by_II the_AT Swedish_JJ Consumers_NN2 Agency_NN1 during_II the_AT spring_NN1 of_IO 2008_MC (_( before_CS the_AT deregulation_NN1 process_NN1 begun_VVN )_) showed_VVD that_CST most_DAT people_NN were_VBDR relatively_RR happy_JJ with_IW the_AT pharmacy_NN1 system_NN1 in_II place_NN1 at_II the_AT time_NNT1 ._. 
</s>
<s>
The_AT overall_JJ rating_NN1 given_VVN by_II the_AT customers_NN2 in_II the_AT study_NN1 was_VBDZ 4,4_MC on_II a_AT1 scale_NN1 from_II 1-5_MCMC ._. 
</s>
<s>
The_AT study_NN1 also_RR showed_VVD that_CST most_DAT people_NN had_VHD less_DAR than_CSN 15_MC minutes_NNT2 to_II their_APPGE closest_JJT (_( konsumentv._NNU 2008_MC )_) In_II research_NN1 med_VVD on_II the_AT pharmacy_NN1 customer_NN1 demands_VVZ one_MC1 of_IO the_AT things_NN2 the_AT pharmacy_NN1 customers_NN2 valued_VVD the_AT most_RRT was_VBDZ that_CST the_AT personnel_NN2 in_II pharmacies_NN2 had_VHD proper_JJ education_NN1 and_CC knowledge_NN1 about_II the_AT medicines_NN2 ._. 
</s>
<s>
Another_DD1 thing_NN1 that_CST was_VBDZ highly_RR valued_VVN was_VBDZ the_AT availability_NN1 of_IO medicines_NN2 ,_, i.e._REX not_XX having_VHG to_TO wait_VVI more_DAR than_CSN 24_MC hours_NNT2 before_II getting_VVG the_AT right_JJ medication_NN1 (_( konsumentv_NN1 2009_MC )_) ._. 
</s>
<s>
Prices_NN2 on_II the_AT medicines_NN2 was_VBDZ another_DD1 issue_NN1 which_DDQ concerned_VVD many_DA2 of_IO the_AT customers_NN2 Additional_JJ services_NN2 ._. 
</s>
<s>
(_( konsumentv_NN1 2009_MC )_) Methods_NN2 In_BCL21 order_BCL22 to_TO analyze_VVI the_AT changes_NN2 that_CST the_AT Swedish_JJ pharmacy_NN1 market_NN1 has_VHZ under_RG gone_VVN ,_, a_AT1 SWOT-analysis_NN1 is_VBZ conducted_VVN ._. 
</s>
<s>
The_AT SWOT-analysis_NN1 is_VBZ well_RR suited_VVN for_IF this_DD1 study_NN1 as_II the_AT method_NN1 can_VM be_VBI applied_VVN on_II bigger_JJR wholes_NN2 such_II21 as_II22 the_AT entire_JJ pharmacy_NN1 market_NN1 ,_, rather_CS21 than_CS22 just_RR one_MC1 single_JJ company_NN1 and_CC its_APPGE situation_NN1 on_II the_AT market_NN1 ._. 
</s>
<s>
The_AT method_NN1 is_VBZ especially_RR well_RR suited_VVN for_IF finding_VVG areas_NN2 of_IO improvement_NN1 and_CC therefore_RR it_PPH1 is_VBZ well_RR suited_VVN for_IF this_DD1 particular_JJ case_NN1 (_( Armstrong_NP1 M_ZZ1 )_) ._. 
</s>
<s>
Validity_NN1 and_CC reliability_NN1 This_DD1 analysis_NN1 is_VBZ based_VVN on_II figures_NN2 and_CC information_NN1 gathered_VVN by_II and_CC from_II the_AT actor_NN1 on_II the_AT pharmacy_NN1 market_NN1 in_II Sweden_NP1 ._. 
</s>
<s>
Prior_II21 to_II22 2010_MC the_AT data_NN has_VHZ been_VBN collected_VVN by_II the_AT state-run_JJ Apoteket_NN1 Ab_FO ,_, the_AT owner_NN1 of_IO all_DB pharmacies_NN2 at_II that_DD1 time_NNT1 and_CC contains_VVZ information_NN1 from_II all_DB of_IO the_AT companys_NN2 retail_JJ locations_NN2 ._. 
</s>
<s>
After_CS the_AT deregulation_NN1 the_AT data_NN has_VHZ been_VBN gathered_VVN by_II the_AT Swedish_JJ Pharmacy_NN1 Association_NN1 (_( Sveriges_NP2 apoteksfrening_VVG )_) ,_, an_AT1 umbrella_NN1 association_NN1 for_IF all_DB pharmacies_NN2 in_II Sweden_NP1 ._. 
</s>
<s>
This_DD1 data_NN does_VDZ also_RR cover_VVI all_DB pharmacies_NN2 in_II Sweden_NP1 ,_, which_DDQ means_VVZ that_CST the_AT data_NN from_II both_DB2 sources_NN2 should_VM be_VBI comparable_JJ even_CS21 though_CS22 the_AT actors_NN2 on_II the_AT market_NN1 have_VH0 changed_VVN ._. 
</s>
<s>
Because_CS the_AT party_NN1 gathering_VVG the_AT information_NN1 is_VBZ at_II the_AT same_DA time_NNT1 an_AT1 actor_NN1 or_CC an_AT1 organization_NN1 working_VVG for_IF the_AT actors_NN2 on_II the_AT market_NN1 ,_, the_AT reliability_NN1 of_IO the_AT fact_NN1 could_VM be_VBI argued_VVN ._. 
</s>
<s>
But_CCB as_CSA this_DD1 study_NN1 focuses_VVZ on_II notifying_VVG changes_NN2 in_II the_AT customers_NN2 situation_NN1 this_DD1 should_VM not_XX interfere_VVI with_IW the_AT results_NN2 ._. 
</s>
<s>
In_II31 addition_II32 to_II33 this_DD1 data_NN gathered_VVN by_II the_AT neutral_JJ party_NN1 the_AT Swedish_JJ Consumers_NN2 Agency_NN1 (_( konsumentverket_NN1 )_) ,_, covering_VVG the_AT pharmacy_NN1 deregulation_NN1 ,_, is_VBZ also_RR reviewed_VVN in_BCL21 order_BCL22 to_TO increase_VVI the_AT reliability_NN1 ._. 
</s>
<s>
As_CSA indicated_VVN by_II literature_NN1 the_AT SWOT_NN1 analysis_NN1 is_VBZ a_AT1 valid_JJ method_NN1 for_IF analyzing_VVG markets_NN2 and_CC detecting_VVG areas_NN2 In_II31 need_II32 of_II33 improvements_NN2 ._. 
</s>
<s>
Because_II21 of_II22 the_AT limitations_NN2 on_II the_AT extent_NN1 of_IO this_DD1 study_NN1 no_AT other_JJ methods_NN2 for_IF analysis_NN1 are_VBR used_VVN ._. 
</s>
<s>
SWOT-analysis_NN1 The_AT SWOT-anlysis_NN1 is_VBZ a_AT1 method_NN1 of_IO structuring_VVG a_AT1 study_NN1 on_II a_AT1 larger_JJR field_NN1 ._. 
</s>
<s>
The_AT aim_NN1 is_VBZ to_TO identify_VVI internal_JJ affecting_VVG the_AT situation_NN1 at_RR21 present_RR22 (_( strengths_NN2 ,_, weaknesses_NN2 )_) and_CC external_JJ (_( opportunities_NN2 ,_, threats_NN2 )_) that_CST affect_VV0 the_AT studied_JJ object_NN1 now_RT or_CC in_II the_AT future_NN1 ._. 
</s>
<s>
(_( Armstrong_NP1 )_) The_AT when_CS conducting_VVG a_AT1 SWOT_NN1 analysis_NN1 ,_, the_AT features_NN2 of_IO the_AT object_NN1 of_IO study_NN1 are_VBR separated_VVN into_II four_MC categories_NN2 :_: strengths_NN2 ,_, weaknesses_NN2 ,_, opportunities_NN2 ,_, and_CC threats_NN2 ._. 
</s>
<s>
By_II doing_VDG this_DD1 ,_, the_AT most_RGT interesting_JJ areas_NN2 should_VM be_VBI emphasized_VVN ._. 
</s>
<s>
That_REX21 is_REX22 ,_, areas_NN2 in_II31 need_II32 of_II33 improvement_NN1 or_CC areas_NN2 that_CST have_VH0 affected_VVN the_AT customers_NN2 situation_NN1 negatively_RR as_II31 well_II32 as_II33 the_AT areas_NN2 where_RRQ the_AT customers_NN2 are_VBR satisfied_JJ and_CC where_CS the_AT situation_NN1 has_VHZ improved_VVN since_CS the_AT deregulation_NN1 ._. 
</s>
<s>
Analysis_NN1 Strengths_NN2 The_AT most_RGT significant_JJ change_NN1 for_IF the_AT better_RRR has_VHZ been_VBN in_II the_AT area_NN1 of_IO opening_JJ hours_NNT2 ._. 
</s>
<s>
AS_CSA prior_JJ data_NN shows_VVZ that_CST only_RR a_AT1 small_JJ number_NN1 of_IO pharmacies_NN2 were_VBDR open_JJ in_II the_AT weekends_NNT2 and_CC after_II 6_MC pm_RA on_II weekdays_NNT2 (_( AAB_NP1 )_) ._. 
</s>
<s>
Now_RT the_AT situation_NN1 is_VBZ significantly_RR better_JJR in_II this_DD1 area_NN1 ._. 
</s>
<s>
(_( apo_NN1 fr_NNU 2011_MC )_) number_NN1 of_IO pharmacies-job_JJ opportunities_NN2 Weaknesses_NN2 safety_NN1 of_IO non-prescription_JJ medicine_NN1 waiting_VVG times_II no_AT decrease_NN1 in_II prices_NN2 The_AT network_NN1 of_IO paharmacies_NN2 built_VVD up_RP by_II Apoteket_NP1 Ab_FO was_VBDZ planned_VVN in_BCL21 order_BCL22 to_TO make_VVI the_AT services_NN2 available_JJ to_II everyone_PN1 regardless_RR of_IO the_AT area_NN1 they_PPHS2 lived_VVD in_RP ._. 
</s>
<s>
In_II a_AT1 country_NN1 like_II Sweden_NP1 where_RRQ distances_NN2 are_VBR long_JJ and_CC the_AT population_NN1 unevenly_RR spread_VV0 this_DD1 can_VM cause_VVI challenges_NN2 ._. 
</s>
<s>
However_RR ,_, as_CSA the_AT results_NN2 of_IO studies_NN2 made_VVD previously_RR to_II the_AT deregulation_NN1 show_VV0 most_DAT people_NN were_VBDR very_RG happy_JJ with_IW their_APPGE access_NN1 to_II pharmacies_NN2 (_( konsumentv_NN1 ._. )_) ._. 
</s>
<s>
After_CS the_AT deregulation_NN1 the_AT number_NN1 of_IO pharmacies_NN2 have_VH0 increased_VVN drastically_RR ,_, but_CCB as_CSA probably_RR also_RR could_VM be_VBI predicted_VVN most_DAT of_IO the_AT new_JJ pharmacies_NN2 have_VH0 been_VBN founded_VVN in_II densely_RR built-up_JJ areas_NN2 ,_, mainly_RR in_II the_AT regions_NN2 of_IO Stockholm_NP1 ,_, Gothenburg_NP1 and_CC Malm_VV0 the_AT three_MC major_JJ cities_NN2 of_IO Sweden_NP1 (_( apo_NN1 fr_NNU )_) ._. 
</s>
<s>
This_DD1 means_VVZ that_CST the_AT growth_NN1 has_VHZ mainly_RR taken_VVN place_NN1 in_II the_AT areas_NN2 where_RRQ the_AT distances_NN2 to_II the_AT pharmacies_NN2 already_RR where_CS the_AT shortest_JJT ._. 
</s>
<s>
In_II a_AT1 free_JJ market_NN1 this_DD1 comes_VVZ natural_JJ as_II the_AT market_NN1 grows_VVZ where_RRQ the_AT biggest_JJT demand_NN1 is_VBZ found_VVN ._. 
</s>
<s>
It_PPH1 is_VBZ not_XX profitable_JJ to_II found_VVD new_JJ pharmacies_NN2 in_II areas_NN2 with_IW only_RR a_AT1 small_JJ population_NN1 ad_NN1 where_CS the_AT distances_NN2 between_II warehouses_NN2 and_CC the_AT businesses_NN2 might_VM be_VBI very_RG long_JJ ._. 
</s>
<s>
Even_CS21 if_CS22 the_AT present_JJ situation_NN1 is_VBZ not_XX showing_VVG an_AT1 immediate_JJ decrease_NN1 in_II the_AT level_NN1 of_IO service_NN1 outside_II big_JJ cities_NN2 ,_, the_AT results_NN2 clearly_RR show_VV0 that_CST the_AT customers_NN2 of_IO the_AT country-side_NN1 are_VBR not_XX paid_VVN as_RG much_DA1 attention_NN1 to_II as_CSA the_AT urban_JJ population_NN1 ._. 
</s>
<s>
Opportunities_NN2 A_ZZ1 tendency_NN1 that_CST can_VM clearly_RR be_VBI noticed_VVN is_VBZ that_CST many_DA2 of_IO the_AT companies_NN2 that_CST are_VBR developing_VVG new_JJ pharmacy-chains_NN2 in_II Sweden_NP1 at_II the_AT moment_NN1 have_VH0 some_DD connections_NN2 to_II the_AT wholesale_JJ industry_NN1 ._. 
</s>
<s>
Kronans_NP1 droghandel_NN1 ,_, one_MC1 of_IO the_AT biggest_JJT chains_NN2 of_IO pharmacies_NN2 at_II the_AT moment_NN1 with_IW more_DAR than_CSN 200_MC pharmacies_NN2 are_VBR owned_VVN by_II Oriola-KD_NP1 a_AT1 Finnish_JJ wholesale_JJ company_NN1 active_JJ in_II the_AT Nordic_JJ and_CC the_AT Baltic_JJ region_NN1 (_( Oriola-KD_NP1 )_) ._. 
</s>
<s>
Doc_NN1 Morris_NP1 another_DD1 big_JJ chain_NN1 ,_, consisting_VVG of_IO almost_RR 100_MC newly_RR founded_VVN pharmacies_NN2 ,_, is_VBZ owned_VVN by_II the_AT big_JJ German_JJ wholesale_JJ company_NN1 Celesio_NP1 AG_FO (_( Doc_NN1 Morris_NP1 )_) ._. 
</s>
<s>
This_DD1 kind_NN1 of_IO integration_NN1 can_VM lead_VVI to_II synergy_NN1 effects_NN2 that_CST could_VM benefit_VVI both_DB2 the_AT companies_NN2 and_CC the_AT customers_NN2 ._. 
</s>
<s>
These_DD2 companies_NN2 have_VH0 the_AT possibility_NN1 to_TO create_VVI a_AT1 more_RGR efficient_JJ supply_NN1 chain_NN1 compared_VVN to_II other_JJ competitors_NN2 ,_, which_DDQ can_VM create_VVI a_AT1 competitive_JJ edge_NN1 ._. 
</s>
<s>
For_IF the_AT customers_NN2 the_AT companies_NN2 have_VH0 better_JJR possibilities_NN2 to_TO produce_VVI additional_JJ services_NN2 such_II21 as_II22 electronic_JJ prescription_NN1 systems_NN2 or_CC additional_JJ healthcare_NN1 services_NN2 ._. 
</s>
<s>
Smaller_JJR companies_NN2 might_VM not_XX have_VHI the_AT resources_NN2 to_TO develop_VVI or_CC even_RR offer_VVI similar_JJ services_NN2 ._. 
</s>
<s>
One_MC1 of_IO the_AT things_NN2 Apoteket_VV0 Ab_FO was_VBDZ criticized_VVN for_IF was_VBDZ that_CST they_PPHS2 did_VDD not_XX develop_VVI their_APPGE service_NN1 ,_, rather_RG only_RR continued_VVN to_TO maintain_VVI the_AT same_DA services_NN2 they_PPHS2 always_RR had_VHD provided_VVN ._. 
</s>
<s>
Threats_NN2 The_AT Indirect_JJ cost-higher_JJR cost_NN1 for_IF customer_NN1 big_JJ changes_NN2 ahead_RL personnel_NN2 (_( educated_JJ and_CC non-educated_NN1 )_) competition_NN1 Conclusions_NN2 and_CC discussion_NN1 on_II applicability_NN1 to_II Finland_NP1 It_PPH1 is_VBZ still_RR very_RG early_JJ to_TO draw_VVI any_DD final_JJ conclusions_NN2 about_II all_DB of_IO the_AT consequences_NN2 of_IO the_AT deregulation_NN1 in_II Sweden_NP1 ._. 
</s>
<s>
A_AT1 process_NN1 like_II this_DD1 will_VM probably_RR take_VVI years_NNT2 before_II the_AT situation_NN1 becomes_VVZ stable_JJ ,_, but_CCB some_DD changes_NN2 can_VM already_RR be_VBI discussed_VVN ._. 
</s>
<s>
During_II the_AT last_MD couple_NN1 of_IO years_NNT2 the_AT end-customer_NN1 has_VHZ unquestionably_RR noticed_VVN lots_PN of_IO changes_NN2 in_II the_AT pharmacy_NN1 market_NN1 directly_RR affecting_VVG the_AT customer_NN1 directly_RR ._. 
</s>
<s>
The_AT most_RGT noticeable_JJ is_VBZ probably_RR the_AT amount_NN1 of_IO different_JJ service_NN1 providers_NN2 ._. 
</s>
<s>
At_II the_AT end_NN1 of_IO 2010_MC there_EX were_VBDR 20_MC different_JJ companies_NN2 selling_VVG prescription_NN1 drugs_NN2 to_II the_AT public_NN1 ,_, compared_VVN to_II one_MC1 (_( Apoteket_NP1 Ab_FO )_) prior_II21 to_II22 the_AT deregulation_NN1 ._. 
</s>
<s>
*****_FO The_AT areas_NN2 that_CST have_VH0 improved_VVN the_AT most_RRT were_VBDR actually_RR not_XX considered_VVN very_RG big_JJ problems_NN2 prior_II21 to_II22 the_AT deregulation_NN1 ._. 
</s>
<s>
Availability_NN1 of_IO the_AT pharmacies_NN2 seems_VVZ to_TO have_VHI increased_VVN marginally_RR The_AT areas_NN2 that_CST were_VBDR actually_RR valued_VVN more_RRR ,_, such_II21 as_II22 competence_NN1 of_IO the_AT staff_NN and_CC availability_NN1 of_IO medicines_NN2 seem_VV0 to_TO actually_RR have_VHI worsened_VVN after_II the_AT deregulation_NN1 ._. 
</s>
<s>
This_DD1 might_VM be_VBI a_AT1 partially_RR caused_VVN by_II the_AT process_NN1 of_IO change_NN1 ,_, where_CS lots_PN of_IO staff_NN changes_NN2 employers_NN2 and_CC new_JJ enterprises_NN2 are_VBR built_VVN up_RP and_CC still_RR struggling_VVG to_TO get_VVI their_APPGE processes_NN2 running_VVG smoothly_RR ._. 
</s>
<s>
But_CCB it_PPH1 is_VBZ remarkable_JJ to_TO observe_VVI that_CST the_AT features_NN2 valued_VVN by_II the_AT customers_NN2 are_VBR actually_RR the_AT ones_NN2 that_CST have_VH0 improved_VVN the_AT least_RRT ._. 
</s>
<s>
Keeping_VVG in_II mind_NN1 that_CST the_AT process_NN1 of_IO change_NN1 is_VBZ still_RR under_RR21 way_RR22 it_PPH1 is_VBZ still_RR important_JJ to_TO keep_VVI in_II mind_NN1 the_AT possibilities_NN2 this_DD1 change_NN1 also_RR can_VM provide_VVI ._. 
</s>
<s>
With_IW experiences_NN2 from_II other_JJ countries_NN2 the_AT bigger_JJR chains_NN2 can_VM provide_VVI new_JJ services_NN2 that_CST help_VV0 the_AT customers_NN2 and_CC possibly_RR the_AT whole_JJ healthcare_NN1 system_NN1 ._. 
</s>
<s>
But_CCB if_CS this_DD1 actually_RR will_VM be_VBI the_AT case_NN1 remains_VVZ to_TO be_VBI seen_VVN ._. 
</s>
<s>
If_CS the_AT Swedish_JJ situation_NN1 is_VBZ compared_VVN to_II the_AT Finnish_JJ there_EX is_VBZ both_RR similarities_NN2 and_CC distinct_JJ differences_NN2 ._. 
</s>
<s>
In_II Finland_NP1 we_PPIS2 also_RR have_VH0 had_VHN a_AT1 strict_JJ regulation_NN1 on_II the_AT pharmacy_NN1 ,_, but_CCB the_AT community_NN1 pharmacies_NN2 have_VH0 never_RR been_VBN run_VVN as_II a_AT1 state_NN1 monopoly_NN1 ._. 
</s>
<s>
The_AT pharmacies_NN2 in_II Finland_NP1 have_VH0 mostly_RR been_VBN owned_VVN by_II private_JJ entrepreneurs_NN2 personally_RR responsible_JJ for_IF their_APPGE own_DA business_NN1 ._. 
</s>
<s>
The_AT ownership_NN1 has_VHZ been_VBN limited_VVN to_II one_MC1 pharmacy_NN1 per_II person_NN1 ,_, and_CC the_AT location_NN1 of_IO the_AT pharmacy_NN1 has_VHZ also_RR been_VBN predetermined_VVN (_( apteekkariliitto_NN1 )_) ._. 
</s>
<s>
A_AT1 deregulation_NN1 in_II Finland_NP1 would_VM probably_RR also_RR here_RL generate_VVI the_AT growth_NN1 of_IO a_AT1 number_NN1 of_IO bigger_JJR chains_NN2 ._. 
</s>
<s>
Wholesale_JJ companies_NN2 or_CC private_JJ investment_NN1 groups_NN2 would_VM probably_RR also_RR here_RL be_VBI the_AT main_JJ actors_NN2 ._. 
</s>
<s>
The_AT two_MC big_JJ food_NN1 retail_JJ corporations_NN2 ,_, Kesko_NP1 and_CC Hok-Elanto_NP1 ,_, could_VM also_RR possibly_RR be_VBI interested_JJ in_II expanding_VVG their_APPGE operations_NN2 to_II the_AT pharmacy_NN1 sector_NN1 ._. 
</s>
<s>
This_DD1 means_VVZ that_CST there_EX probably_RR is_VBZ a_AT1 commercial_JJ interest_NN1 in_II opening_VVG up_RP the_AT regulations_NN2 also_RR in_II Finland_NP1 ._. 
</s>
<s>
The_AT situation_NN1 for_IF the_AT customer_NN1 is_VBZ similar_JJ in_II Sweden_NP1 and_CC Finland_NP1 ._. 
</s>
<s>
In_II many_DA2 areas_NN2 the_AT population_NN1 is_VBZ spread_VVN across_II a_AT1 large_JJ area_NN1 and_CC the_AT distances_NN2 to_II the_AT pharmacy_NN1 might_VM be_VBI long_JJ ._. 
</s>
<s>
One_MC1 big_JJ difference_NN1 is_VBZ that_CST as_CSA we_PPIS2 do_VD0 nt_XX have_VHI a_AT1 state-run_JJ company_NN1 that_CST could_VM cover_VVI the_AT areas_NN2 where_RRQ the_AT commercial_JJ interest_NN1 is_VBZ lacking_VVG ._. 
</s>
<s>
This_DD1 could_VM create_VVI a_AT1 worse_JJR situation_NN1 for_IF the_AT Finnish_JJ pharmacy_NN1 customers_NN2 of_IO the_AT sparsely_RR populated_VVN areas_NN2 than_CSN for_IF their_APPGE Swedish_JJ peers_NN2 ._. 
</s>
<s>
But_CCB on_II the_AT other_JJ hand_NN1 if_CS the_AT deregulation_NN1 helps_VVZ to_TO develop_VVI the_AT pharmacy_NN1 sector_NN1 towards_II a_AT1 more_RGR versatile_JJ service_NN1 provider_NN1 the_AT benefits_NN2 could_VM be_VBI significant_JJ ._. 
</s>
<s>
As_CSA most_DAT of_IO the_AT pharmacies_NN2 in_II Finland_NP1 are_VBR small_JJ enterprises_NN2 ,_, the_AT ability_NN1 and_CC willingness_NN1 to_TO develop_VVI new_JJ services_NN2 is_VBZ restricted_VVN ._. 
</s>
<s>
Whether_CSW the_AT decision_NN1 to_TO deregulate_VVI the_AT pharmacy_NN1 market_NN1 in_II Sweden_NP1 was_VBDZ the_AT best_JJT solution_NN1 for_IF the_AT customer_NN1 or_CC not_XX can_VM ,_, as_CSA also_RR this_DD1 analysis_NN1 shows_NN2 ,_, be_VBI argued_VVN ._. 
</s>
<s>
However_RRQV a_AT1 totally_RR state_VV0 controlled_JJ monopoly_NN1 is_VBZ not_XX in_II31 line_II32 with_II33 the_AT society_NN1 advocated_VVN by_II the_AT EU_NP1 and_CC most_RGT other_JJ western_JJ communities_NN2 ,_, where_CS competition_NN1 should_VM be_VBI free_JJ and_CC driven_VVN by_II demand_NN1 on_II the_AT market_NN1 ._. 
</s>
<s>
In_II the_AT end_NN1 competition_NN1 is_VBZ usually_RR the_AT driving_JJ force_NN1 for_IF progress_NN1 and_CC development_NN1 ._. 
</s>
<s>
And_CC new_JJ ideas_NN2 are_VBR certainly_RR needed_VVN in_BCL21 order_BCL22 to_TO cope_VVI with_IW concerns_NN2 caused_VVN by_II the_AT ageing_JJ population_NN1 ,_, which_DDQ is_VBZ the_AT situation_NN1 in_II many_DA2 Western_JJ counties_NN2 not_XX least_RRT the_AT Nordic_JJ countries_NN2 ._. 
</s>
