<s>
CEO_NN1 payments_NN2 in_II Finland_NP1 -_- too_RG much_DA1 or_CC enough_RR ?_? 1_MC1 ._. 
</s>
<s>
Introduction_NN1 Executive_NN1 compensation_NN1 is_VBZ a_AT1 topic_NN1 that_CST receives_VVZ a_AT1 lot_NN1 of_IO attention_NN1 and_CC raises_VVZ debate_NN1 ._. 
</s>
<s>
Critics_NN2 argue_VV0 that_CST CEOs_NN2 are_VBR greatly_RR overpaid_VVN and_CC not_XX paid_VVN according_II21 to_II22 performance_NN1 ._. 
</s>
<s>
Furthermore_RR ,_, critics_NN2 claim_VV0 that_CST boards_NN2 are_VBR doing_VDG a_AT1 lousy_JJ job_NN1 compensating_VVG and_CC supervising_VVG the_AT CEOs_NN2 (_( Jensen_NP1 et_RA21 al_RA22 2004_MC )_) ._. 
</s>
<s>
There_EX is_VBZ a_AT1 large_JJ literature_NN1 on_II CEO_NN1 payments_NN2 ,_, primarily_RR based_VVN on_II US_NP1 data_NN ._. 
</s>
<s>
Some_DD studies_NN2 argue_VV0 that_CST CEOs_NN2 are_VBR overpaid_VVN ,_, other_JJ studies_NN2 e.g._REX Kaplan_NP1 (_( 2008_MC )_) claim_VV0 the_AT opposite_JJ ._. 
</s>
<s>
It_PPH1 is_VBZ obvious_JJ that_CST corporate_JJ governance_NN1 and_CC CEO_NN1 compensation_NN1 are_VBR not_XX perfect_JJ ,_, but_CCB large_JJ amounts_NN2 of_IO data_NN indicate_VV0 that_DD1 CEO_NN1 payments_NN2 are_VBR determined_VVN by_II market_NN1 forces_NN2 (_( Kaplan_NP1 and_CC Rauh_NP1 2004_MC )_) ._. 
</s>
<s>
Most_DAT of_IO the_AT previous_JJ studies_NN2 are_VBR geographically_RR concentrated_VVN to_II the_AT U.S._NP1 This_DD1 research_NN1 describes_VVZ the_AT situation_NN1 in_II Finland_NP1 including_II the_AT most_RGT recent_JJ data_NN available_JJ ._. 
</s>
<s>
This_DD1 paper_NN1 attempts_NN2 to_TO analyze_VVI the_AT Finnish_JJ market_NN1 and_CC to_TO identify_VVI factors_NN2 which_DDQ drive_VV0 CEO_NN1 compensation_NN1 ._. 
</s>
<s>
The_AT topic_NN1 can_VM be_VBI found_VVN as_II a_AT1 current_JJ matter_NN1 since_CS CEO_NN1 payments_NN2 have_VH0 lately_RR been_VBN a_AT1 hot_JJ topic_NN1 in_II the_AT press_NN1 ._. 
</s>
<s>
E.g._REX Nordea_NP1 's_GE Chairman_NN1 of_IO the_AT Board_NN1 ,_, Bjrn_NP1 Wahlroos_NP1 '_GE comments_NN2 on_II Nordea_NP1 's_GE CEO_NN1 ,_, Christian_JJ Clausen_NP1 's_GE payments_NN2 have_VH0 given_VVN rise_NN1 to_II an_AT1 aggressive_JJ debate_NN1 on_II executive_NN1 payments_NN2 ,_, perks_NN2 and_CC pension_NN1 plans_NN2 ._. 
</s>
<s>
Among_II other_JJ things_NN2 ,_, Wahlroos_NP1 stated_VVD that_CST he_PPHS1 would_VM be_VBI more_DAR than_CSN glad_JJ to_TO raise_VVI Clausen_NP1 's_GE compensations_NN2 so_CS21 that_CS22 Clausen_NP1 can_VM buy_VVI more_DAR apartments_NN2 in_II Stockholm_NP1 if_CS he_PPHS1 wishes_VVZ ._. 
</s>
<s>
This_DD1 was_VBDZ said_VVN simultaneously_RR as_CSA Nordea_NP1 was_VBDZ firing_VVG thousands_NNO2 of_IO employees_NN2 due_II21 to_II22 its_APPGE cost_NN1 savings_NN2 plans_NN2 ._. 
</s>
<s>
New_JJ recommendations_NN2 on_II corporate_JJ governance_NN1 for_IF listed_JJ companies_NN2 ,_, is_VBZ also_RR being_VBG considered_VVN in_II this_DD1 study_NN1 ._. 
</s>
<s>
Companies_NN2 are_VBR nowadays_RT increasingly_RR forced_VVN to_TO report_VVI management_NN1 compensation_NN1 ._. 
</s>
<s>
Some_DD earlier_JJR studies_NN2 on_II the_AT topic_NN1 have_VH0 been_VBN limited_VVN due_II21 to_II22 the_AT fact_NN1 that_CST companies_NN2 have_VH0 restrained_VVN in_II reporting_VVG compensations._NNU 1.1_MC ._. 
</s>
<s>
Purpose_NN1 of_IO the_AT study_NN1 The_AT purpose_NN1 of_IO this_DD1 paper_NN1 is_VBZ to_TO compare_VVI CEO_NN1 payments_NN2 of_IO Finnish_JJ companies_NN2 with_IW a_AT1 minimum_JJ current_JJ market_NN1 cap_NN1 of_IO EUR_NN1 100m_NNU ._. 
</s>
<s>
Moreover_RR ,_, the_AT paper_NN1 try_VV0 to_TO identify_VVI what_DDQ affects_VVZ CEO_NN1 payments_NN2 in_II Finland_NP1 ._. 
</s>
<s>
Own_DA conclusion_NN1 to_II the_AT matter_NN1 whether_CSW CEOs_NN2 in_II Finland_NP1 are_VBR overpaid_VVN or_CC not_XX will_VM also_RR be_VBI given._NNU 1.2_MC ._. 
</s>
<s>
Limitations_NN2 The_AT research_NN1 is_VBZ limited_VVN to_II CEO_NN1 payments_NN2 of_IO the_AT Finnish_JJ companies_NN2 with_IW a_AT1 current_JJ market_NN1 cap_NN1 of_IO at_RR21 least_RR22 EUR_NN1 100m_NNU ._. 
</s>
<s>
Financial_JJ companies_NN2 have_VH0 been_VBN excluded_VVN because_II21 of_II22 differing_JJ income_NN1 statement_NN1 and_CC balance_NN1 sheet_NN1 structure_NN1 ._. 
</s>
<s>
Voluntary_JJ pension_NN1 compensations_NN2 are_VBR included_VVN in_II this_DD1 study._NNU 2_MC ._. 
</s>
<s>
Separation_NN1 of_IO ownership_NN1 and_CC control_VV0 :_: Agency_NN1 problem_NN1 The_AT separation_NN1 of_IO ownership_NN1 and_CC control_NN1 is_VBZ the_AT background_NN1 of_IO corporate_JJ governance_NN1 and_CC is_VBZ closely_RR connected_VVN with_IW the_AT agency_NN1 theory_NN1 or_CC the_AT agency_NN1 problem_NN1 occurring_VVG between_II management_NN1 and_CC shareholders_NN2 ._. 
</s>
<s>
Berle_NP1 and_CC Means_NN (_( 1932_MC )_) were_VBDR the_AT first_MD introducing_VVG the_AT agency_NN1 theory_NN1 and_CC many_DA2 other_JJ studies_NN2 have_VH0 thereafter_RT confirmed_VVN it_PPH1 and_CC explored_VVD it_PPH1 further_RRR ._. 
</s>
<s>
Managers_NN2 may_VM use_VVI their_APPGE position_NN1 and_CC power_NN1 to_TO benefit_VVI themselves_PPX2 personally_RR in_II a_AT1 variety_NN1 of_IO ways_NN2 ._. 
</s>
<s>
This_DD1 is_VBZ referred_VVN to_II the_AT agency_NN1 problem_NN1 ,_, a_AT1 conflict_NN1 of_IO interest_NN1 arising_VVG between_II shareholders_NN2 and_CC management_NN1 because_II21 of_II22 differing_JJ goals_NN2 (_( Shleifer_NP1 &;_NULL Vishny_NP1 1997_MC )_) ._. 
</s>
<s>
Managers_NN2 may_VM e.g._REX engage_VVI in_II unprofitable_JJ empire_NN1 building_NN1 ,_, or_CC may_VM fail_VVI in_II distributing_VVG excess_JJ cash_NN1 in_II a_AT1 poor_JJ business_NN1 opportunity_NN1 environment_NN1 or_CC may_VM perhaps_RR strengthen_VVI their_APPGE position_NN1 so_CS21 that_CS22 it_PPH1 can_VM be_VBI hard_JJ to_TO displace_VVI them_PPHO2 although_CS the_AT company_NN1 performs_VVZ poorly_RR (_( Schleifer_NP1 &;_NULL Vishny_NP1 1989_MC )_) ._. 
</s>
<s>
How_RRQ can_VM shareholders_NN2 then_RT be_VBI sure_JJ that_CST the_AT management_NN1 is_VBZ not_XX expropriating_VVG them_PPHO2 or_CC simultaneously_RR spending_VVG too_RG much_DA1 money_NN1 on_II unnecessary_JJ things_NN2 instead_II21 of_II22 maximizing_VVG the_AT shareholder_NN1 value_NN1 ?_? 
</s>
<s>
It_PPH1 's_VBZ important_JJ to_TO address_VVI that_CST any_DD discussion_NN1 of_IO executive_NN1 compensation_NN1 must_VM proceed_VVI the_AT bottom-line_JJ agency_NN1 problem_NN1 distressing_JJ the_AT decision_NN1 making_NN1 of_IO management_NN1 (_( Bebchuk_NP1 &;_NULL Fried_VVD 2003_MC )_) ._. 
</s>
<s>
3_MC ._. 
</s>
<s>
Prior_JJ research_NN1 In_II this_DD1 chapter_NN1 the_AT prior_JJ research_NN1 considering_II CEO_NN1 compensation_NN1 from_II the_AT Finnish_JJ and_CC the_AT US_NP1 market_NN1 will_VM be_VBI presented._NNU 3.1_MC ._. 
</s>
<s>
Steven_NP1 N._NP1 Kaplan_NP1 (_( 2008_MC )_) Kaplan_NP1 investigates_VVZ in_II his_APPGE article_NN1 "_" Are_VBR U.S._NP1 Ceo_NN1 `_" s_ZZ1 really_RR overpaid_VVD "_" the_AT CEO_NN1 pay_NN1 for_IF U.S._NP1 listed_VVD firms_NN2 on_II the_AT S_ZZ1 &P;_NULL 500_MC during_II the_AT time-period_NN1 1993-2006_MCMC ._. 
</s>
<s>
The_AT main_JJ issue_NN1 that_CST he_PPHS1 wanted_VVD to_TO address_VVI with_IW his_APPGE survey_NN1 was_VBDZ whether_CSW the_AT pay_NN1 of_IO CEO_NN1 `_" s_ZZ1 is_VBZ a_AT1 largely_RR market_VV0 phenomena_NN2 or_CC if_CS it_PPH1 is_VBZ driven_VVN by_II the_AT power_NN1 of_IO the_AT CEO_NN1 `_" s_ZZ1 and_CC the_AT weakness_NN1 of_IO companies_NN2 '_GE boards_NN2 ._. 
</s>
<s>
Kaplan_JJ measured_JJ CEO_NN1 pay_NN1 in_II two_MC different_JJ ways_NN2 ._. 
</s>
<s>
The_AT first_MD way_NN1 was_VBDZ measured_VVN by_RP that_CST he_PPHS1 looked_VVD at_II ex._JJ21 ante_JJ22 value_NN1 of_IO CEO_NN1 pay_NN1 ._. 
</s>
<s>
This_DD1 measure_NN1 includes_VVZ the_AT CEOs_NN2 ;_; salary_NN1 ,_, bonus_NN1 the_AT value_NN1 of_IO restricted_JJ stocks_NN2 and_CC the_AT estimated_JJ value_NN1 of_IO the_AT options_NN2 that_CST was_VBDZ issued_VVN that_DD1 year_NNT1 ._. 
</s>
<s>
This_DD1 measure_NN1 is_VBZ not_XX what_DDQ the_AT CEO_NN1 actually_RR gets_VVZ paid_VVN during_II a_AT1 year_NNT1 ,_, it_PPH1 is_VBZ only_RR a_AT1 estimation_NN1 from_II the_AT boards_NN2 sight_NN1 of_IO view_NN1 ._. 
</s>
<s>
The_AT second_MD measure_NN1 of_IO pay_NN1 is_VBZ a_AT1 true_JJ fact_NN1 of_IO what_DDQ the_AT CEO_NN1 earns_VVZ during_II a_AT1 year_NNT1 ._. 
</s>
<s>
It_PPH1 is_VBZ called_VVN realized_JJ pay_NN1 and_CC it_PPH1 is_VBZ based_VVN on_II the_AT same_DA variables_NN2 as_CSA the_AT ex._JJ21 ante_JJ22 way_NN1 ._. 
</s>
<s>
The_AT only_JJ thing_NN1 that_CST differs_VVZ is_VBZ the_AT pay_NN1 of_IO the_AT options_NN2 is_VBZ calculated_VVN through_II looking_VVG at_II the_AT exercised_VVN pay_NN1 of_IO the_AT options_NN2 ._. 
</s>
<s>
Kaplan_NN1 also_RR looked_VVN at_II the_AT pay_NN1 development_NN1 for_IF other_JJ highly_RR paid_VVN talents_NN2 such_II21 as_II22 lawyers_NN2 ,_, hedge-fund_JJ managers_NN2 and_CC athletes_NN2 (_( top-_JJ level_NN1 )_) ._. 
</s>
<s>
Further_RRR on_RP ,_, as_CSA has_VHZ been_VBN done_VDN in_II previous_JJ research_NN1 he_PPHS1 looks_VVZ at_II the_AT relationship_NN1 between_II CEO_NN1 pay_NN1 and_CC performance_NN1 ._. 
</s>
<s>
The_AT survey_NN1 showed_VVD that_CST the_AT CEO_NN1 pay_NN1 has_VHZ declined_VVN since_II year_NNT1 2000_MC or_CC been_VBN kept_VVN unchanged_JJ ._. 
</s>
<s>
In_II comparison_NN1 to_II other_JJ sectors_NN2 with_IW similarly_RR talented_JJ individuals_NN2 has_VHZ gone_VVN up_RP at_RR21 least_RR22 as_RG much_DA1 since_II 1994_MC ._. 
</s>
<s>
The_AT survey_NN1 concludes_VVZ that_CST high_JJ CEO_NN1 pay_NN1 is_VBZ largely_RR a_AT1 market_NN1 phenomenon_NN1 since_CS Kaplan_NP1 argues_VVZ that_CST many_DA2 other_JJ groups_NN2 have_VH0 seen_VVN their_APPGE compensation_NN1 increase_NN1 substantially_RR and_CC at_II the_AT same_DA level_NN1 as_CSA CEOs_NN2 ._. 
</s>
<s>
The_AT survey_NN1 also_RR shows_VVZ that_CST the_AT realized_JJ pay_NN1 for_IF a_AT1 CEO_NN1 is_VBZ strongly_RR related_VVN to_II the_AT stock_NN1 performance._NNU 3.2_MC ._. 
</s>
<s>
Mkinen_NP1 (_( 2007_MC )_) In_II the_AT discussion_NN1 paper_NN1 CEO_NN1 compensation_NN1 ,_, firm_JJ size_NN1 and_CC firm_JJ performance_NN1 :_: evidence_NN1 from_II Finnish_JJ panel_NN1 data_NN the_AT author_NN1 examined_VVD how_RRQ CEO_NN1 pay_NN1 is_VBZ related_VVN to_II firm_JJ size_NN1 and_CC to_II firm_JJ performance_NN1 ._. 
</s>
<s>
The_AT time-period_NN1 is_VBZ from_II 1996-2002_MCMC and_CC the_AT data_NN set_NN1 is_VBZ Finnish_JJ listed_JJ companies_NN2 ._. 
</s>
<s>
CEO_NN1 annual_JJ compensations_NN2 were_VBDR collected_VVN from_II the_AT Finnish_JJ tax_NN1 authorities_NN2 ._. 
</s>
<s>
Firm_JJ level_JJ financial_JJ statement_NN1 was_VBDZ accessed_VVN through_II Balance_NN1 consulting_NN1 ,_, which_DDQ is_VBZ a_AT1 Finnish_JJ consulting_JJ firm_NN1 ._. 
</s>
<s>
When_CS measuring_VVG firm_JJ performance_NN1 two_MC different_JJ measures_NN2 were_VBDR used_VVN ;_; one_PN1 is_VBZ an_AT1 accounting_NN1 based_VVN (_( ROA_NP1 )_) and_CC the_AT other_JJ one_PN1 is_VBZ a_AT1 stock-_NN1 based_VVN (_( returns_VVZ )_) measure_NN1 ._. 
</s>
<s>
The_AT method_NN1 used_VMK to_TO check_VVI for_IF the_AT relationship_NN1 between_II CEO_NN1 pay_NN1 and_CC firm_JJ size_NN1 is_VBZ estimated_VVN by_II OLS_NN2 separate_VV0 cross-section_NN1 model_NN1 and_CC a_AT1 pooled_JJ model_NN1 ._. 
</s>
<s>
The_AT study_NN1 shows_VVZ that_DD1 CEO_NN1 average_NN1 compensation_NN1 has_VHZ increased_VVN substantially_RR during_II the_AT period_NN1 of_IO investigation_NN1 ._. 
</s>
<s>
An_AT1 interesting_JJ finding_NN1 is_VBZ the_AT fact_NN1 that_CST shares_NN2 with_IW foreign_JJ ownership_NN1 is_VBZ positively_RR and_CC statistically_RR significant_JJ associated_JJ with_IW the_AT level_NN1 of_IO compensation_NN1 ._. 
</s>
<s>
Further_RRR concentrated_JJ ownership_NN1 is_VBZ showed_VVN to_TO have_VHI a_AT1 negative_JJ impact_NN1 to_II the_AT level_NN1 of_IO compensation_NN1 ,_, but_CCB only_RR in_II the_AT pooled_JJ model_NN1 ._. 
</s>
<s>
When_CS comparing_VVG CEOs_NN2 and_CC industrial_JJ workers_NN2 ratio_NN1 ,_, the_AT mean_JJ total_JJ compensation_NN1 was_VBDZ 7_MC in_II 1996_MC ,_, peaked_VVN at_II 24_MC in_II 2000_MC and_CC thereafter_RT dropped_VVD down_RP to_II 13_MC in_II 2002_MC ._. 
</s>
<s>
According_II21 to_II22 the_AT author_NN1 this_DD1 development_NN1 of_IO CEO_NN1 pay_NN1 is_VBZ strongly_RR related_VVN to_II the_AT market_NN1 boom_NN1 on_II the_AT Helsinki_NP1 Stock_NN1 exchange_NN1 ._. 
</s>
<s>
In_II 1999_MC the_AT ratio_NN1 was_VBDZ 16_MC and_CC compared_VVN to_II other_JJ studies_NN2 this_DD1 ratio_NN1 exceeds_VVZ the_AT results_NN2 reported_VVN from_II Germany_NP1 (_( 13_MC )_) ,_, Sweden_NP1 (_( 13_MC )_) and_CC France_NP1 (_( 15_MC )_) ._. 
</s>
<s>
But_CCB when_CS comparing_VVG to_II U.S_NP1 ,_, they_PPHS2 show_VV0 a_AT1 ratio_NN1 of_IO (_( 475_MC )_) which_DDQ shows_VVZ that_CST the_AT European_JJ compensations_NN2 are_VBR quite_RG small._NNU 3.3_MC ._. 
</s>
<s>
Vittaniemi_NN2 (_( 1997_MC )_) In_II the_AT survey_NN1 "_" Top_NN1 executive_NN1 Compensation_NN1 and_CC Company_NN1 performance_NN1 in_II Finland_NP1 "_" the_AT author_NN1 examines_VVZ CEO_NN1 compensation_NN1 both_RR for_IF listed_JJ and_CC unlisted_JJ companies_NN2 '_GE Finnish_JJ companies_NN2 ,_, as_CSA a_AT1 theoretical_JJ framework_NN1 the_AT principal_JJ agent_NN1 problem_NN1 ._. 
</s>
<s>
The_AT data_NN set_NN1 consists_VVZ of_IO a_AT1 sample_NN1 of_IO 500_MC largest_JJT companies_NN2 ranked_VVN based_VVN on_II sales_NN ._. 
</s>
<s>
The_AT final_JJ sample_NN1 included_VVD 48_MC listed_JJ companies_NN2 and_CC 70_MC private_JJ companies_NN2 ._. 
</s>
<s>
The_AT method_NN1 that_CST was_VBDZ used_VVN was_VBDZ a_AT1 pooled_JJ regression_NN1 model_NN1 ._. 
</s>
<s>
The_AT aim_NN1 of_IO the_AT survey_NN1 was_VBDZ to_TO examine_VVI the_AT relationship_NN1 between_II compensation_NN1 and_CC firm_JJ performance_NN1 ._. 
</s>
<s>
CEO_NN1 salary_NN1 is_VBZ defined_VVN in_II two_MC different_JJ ways_NN2 ._. 
</s>
<s>
The_AT first_MD does_VDZ only_RR include_VVI base_NN1 salary_NN1 while_CS the_AT other_NN1 is_VBZ taking_VVG performance_NN1 pay_NN1 into_II consideration_NN1 ._. 
</s>
<s>
To_TO investigate_VVI the_AT financial_JJ performance_NN1 measures_VVZ the_AT author_NN1 used_JJ key-figures_NN2 as_CSA ROI_NN1 and_CC ROA_NP1 ._. 
</s>
<s>
The_AT econometric_JJ results_NN2 for_IF the_AT listed_JJ companies_NN2 showed_VVD that_CST performance-_JJ sensitive_JJ compensation_NN1 as_CSA stock-options_NN2 ,_, deferred_JJ stock_NN1 ownership_NN1 and_CC dividends_NN2 are_VBR important_JJ to_TO find_VVI a_AT1 statistically_RR pay_VV0 for_IF performance_NN1 relationship_NN1 ._. 
</s>
<s>
When_CS looking_VVG at_II the_AT financial_JJ key_NN1 figures_VVZ the_AT study_NN1 showed_VVD that_DD1 last_MD periods_NN2 change_VV0 in_II ROI1_FO has_VHZ a_AT1 statically_RR significant_JJ effect_NN1 on_II total_JJ CEO_NN1 compensation_NN1 concerning_II the_AT second_MD measure_NN1 ROE_NN the_AT author_NN1 did_VDD not_XX find_VVI a_AT1 significant_JJ relationship_NN1 ._. 
</s>
<s>
Further_RRR on_II the_AT author_NN1 states_VVZ that_CST a_AT1 firms_NN2 share_VV0 performance_NN1 and_CC size_NN1 together_RL are_VBR the_AT most_RGT important_JJ determinants_NN2 of_IO executive_NN1 compensation_NN1 ._. 
</s>
<s>
Concerning_II private_JJ companies_NN2 the_AT study_NN1 found_VVD that_CST the_AT pay_NN1 for_IF performance_NN1 relationship_NN1 is_VBZ much_RR weaker_JJR compared_VVN to_II listed_JJ companies._NNU 4_MC ._. 
</s>
<s>
Alternative_JJ compensation_NN1 systems_NN2 for_IF CEOs_NN2 This_DD1 chapter_NN1 focuses_VVZ on_II what_DDQ alternatives_NN2 there_EX are_VBR for_IF compensating_VVG the_AT CEO_NN1 ._. 
</s>
<s>
However_RR ,_, this_DD1 paper_NN1 only_RR analyzes_VVZ the_AT CEO_NN1 taxable_JJ income_NN1 in_II the_AT empirical_JJ part_NN1 ._. 
</s>
<s>
As_CSA stated_VVN earlier_RRR there_EX have_VH0 been_VBN several_DA2 attempts_NN2 in_II the_AT corporate_JJ governance_NN1 literature_NN1 to_TO construct_VVI the_AT perfect_JJ compensation_NN1 scheme_NN1 ,_, which_DDQ would_VM dilute_VVI the_AT agency_NN1 problem_NN1 occurring_VVG between_II management_NN1 and_CC shareholders_NN2 ._. 
</s>
<s>
The_AT differences_NN2 in_II compensation_NN1 systems_NN2 around_II the_AT world_NN1 are_VBR big_JJ and_CC most_DAT of_IO the_AT previous_JJ studies_NN2 are_VBR done_VDN on_II US_NP1 data_NN ._. 
</s>
<s>
The_AT main_JJ point_NN1 is_VBZ that_CST the_AT total_JJ compensation_NN1 should_VM be_VBI competitive_JJ and_CC make_VV0 the_AT CEO_NN1 to_TO make_VVI decisions_NN2 that_CST would_VM maximize_VVI the_AT wealth_NN1 of_IO the_AT shareholders_NN2 ._. 
</s>
<s>
As_CSA mentioned_VVN ,_, the_AT compensation_NN1 system_NN1 should_VM be_VBI structured_VVN in_II the_AT way_NN1 that_CST the_AT agency_NN1 problem_NN1 between_II managers_NN2 and_CC shareholders_NN2 is_VBZ diluted_VVN ._. 
</s>
<s>
CEO_NN1 compensation_NN1 can_VM be_VBI constructed_VVN of_IO base_NN1 salary_NN1 ,_, bonuses_NN2 ,_, company_NN1 shares_NN2 and_CC options_NN2 and_CC various_JJ fringe_NN1 benefits._NNU 1_MC1 An_AT1 increase_NN1 in_II ROI_NN1 with_IW 1%_NNU increased_JJ CEO_NN1 compensation_NN1 with_IW 0,017_MC 4.1_MC ._. 
</s>
<s>
Base_NN1 salary_NN1 Essentially_RR ,_, every_AT1 CEO_NN1 has_VHZ a_AT1 base_NN1 salary_NN1 ._. 
</s>
<s>
The_AT base_NN1 salary_NN1 is_VBZ usually_RR paid_VVN every_AT1 month_NNT1 and_CC is_VBZ correlated_VVN with_IW the_AT size_NN1 of_IO the_AT company_NN1 (_( Ciscel_NP1 &;_NULL Carroll_NP1 1980_MC )_) (_( Jensen_NP1 &;_NULL Murphy_NP1 1990_MC )_) ._. 
</s>
<s>
It_PPH1 is_VBZ important_JJ that_CST the_AT base_NN1 salary_NN1 is_VBZ competitive_JJ on_II the_AT market_NN1 so_CS21 that_CS22 the_AT company_NN1 succeeds_VVZ in_II attracting_VVG highly_RR professional_JJ and_CC skilled_JJ managers_NN2 ._. 
</s>
<s>
The_AT monthly_JJ salary_NN1 functions_NN2 in_II a_AT1 manner_NN1 that_CST the_AT CEO_NN1 is_VBZ committed_VVN and_CC focused_VVN on_II his_APPGE task_NN1 ,_, but_CCB has_VHZ also_RR incentive_NN1 problems_NN2 ._. 
</s>
<s>
When_CS the_AT CEO_NN1 's_GE salary_NN1 is_VBZ correlated_VVN to_II the_AT firm_JJ size_NN1 ,_, the_AT manager_NN1 can_VM try_VVI to_TO increase_VVI his_APPGE salary_NN1 in_II engaging_VVG in_II unprofitable_JJ empire_NN1 building_NN1 ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 one_PN1 can_VM think_VVI that_CST a_AT1 too_RG big_JJ salary_NN1 can_VM make_VVI the_AT manager_NN1 risk-averse_JJ and_CC thus_RR tries_VVZ to_TO minimize_VVI the_AT company_NN1 risks_NN2 to_TO ensure_VVI his_APPGE positions_NN2 and_CC enjoy_VVI his_APPGE salary._NNU 4.2_MC ._. 
</s>
<s>
Performance_NN1 based_VVN salary_NN1 To_TO dilute_VVI the_AT agency_NN1 problem_NN1 between_II managers_NN2 and_CC shareholders_NN2 ,_, many_DA2 firms_NN2 have_VH0 tied_VVN the_AT total_JJ compensation_NN1 to_II the_AT performance_NN1 of_IO the_AT firm_NN1 ._. 
</s>
<s>
Performance_NN1 based_VVN salaries_NN2 can_VM include_VVI bonuses_NN2 ,_, options_NN2 and_CC company_NN1 shares_NN2 ._. 
</s>
<s>
It_PPH1 's_VBZ quite_RG common_JJ that_CST executives_NN2 receive_VV0 a_AT1 part_NN1 of_IO their_APPGE compensation_NN1 in_II forms_NN2 of_IO company_NN1 shares_NN2 and_CC options_NN2 ._. 
</s>
<s>
Share_NN1 based_VVN compensation_NN1 have_VH0 increased_VVN lately_RR due_II21 to_II22 corporate_JJ governance_NN1 recommendations_NN2 and_CC from_II the_AT demand_NN1 of_IO shareholders_NN2 ._. 
</s>
<s>
In_II this_DD1 way_NN1 the_AT managers_NN2 are_VBR seen_VVN to_TO engage_VVI in_II more_RGR long-term_JJ planning_NN1 and_CC consequently_RR creating_VVG sustainable_JJ profitability_NN1 (_( Geretey_NP1 ,_, Hoi_UH &;_NULL Robin_NP1 2001_MC )_) ._. 
</s>
<s>
But_CCB other_JJ studies_NN2 claim_VV0 that_CST e.g._REX stock_NN1 options_NN2 are_VBR all_RR too_RG often_RR just_RR extra_JJ compensation_NN1 and_CC not_XX effective_JJ incentives_NN2 (_( Stewart_NP1 III_MC 2000_MC )_) ._. 
</s>
<s>
Likewise_RR ,_, according_II21 to_II22 Bebchuk_NP1 and_CC Fried_JJ (_( 2003_MC )_) stock_NN1 option_NN1 plans_VVZ also_RR fail_VV0 to_TO filter_VVI out_RP stock_NN1 price_NN1 rises_VVZ due_II21 to_II22 successful_JJ managerial_JJ job_NN1 and_CC company_NN1 performance_NN1 and_CC rises_VVZ that_CST are_VBR due_II21 to_II22 industry_NN1 and_CC general_JJ market_NN1 trends_NN2 ._. 
</s>
<s>
The_AT same_DA argument_NN1 could_VM be_VBI used_VVN for_IF bonuses_NN2 ,_, if_CS the_AT market_NN1 is_VBZ blooming_VVG ;_; even_RR executives_NN2 whose_DDQGE companies_NN2 perform_VV0 poorly_RR relative_II21 to_II22 the_AT industry_NN1 may_VM earn_VVI large_JJ profits_NN2 ,_, because_CS bonuses_NN2 are_VBR to_II a_AT1 large_JJ extent_NN1 tied_VVN to_II accounting_VVG numbers_NN2 ._. 
</s>
<s>
There_EX are_VBR two_MC ways_NN2 for_IF share_NN1 based_VVN compensation_NN1 ._. 
</s>
<s>
The_AT manager_NN1 can_VM either_RR obtain_VVI company_NN1 shares_NN2 directly_RR or_CC commit_VV0 to_II the_AT company_NN1 's_GE option_NN1 scheme_NN1 ._. 
</s>
<s>
If_CS the_AT manager_NN1 obtains_VVZ directly_RR company_NN1 shares_NN2 ,_, there_EX are_VBR usually_RR restrictions_NN2 in_II when_RRQ the_AT shares_NN2 can_VM be_VBI sold_VVN ._. 
</s>
<s>
One_PN1 can_VM estimate_VVI that_DD1 performance_NN1 based_VVN salary_NN1 results_NN2 in_II managers_NN2 taking_VVG more_DAR risk_NN1 (_( but_CCB not_XX too_RG much_RR )_) and_CC become_VV0 more_RGR efficient_JJ and_CC concerned_JJ about_II the_AT company_NN1 performance_NN1 ,_, but_CCB they_PPHS2 also_RR have_VH0 their_APPGE pitfalls._NNU 4.3_MC ._. 
</s>
<s>
Other_JJ compensation_NN1 In_II31 addition_II32 to_II33 base_NN1 salary_NN1 ,_, and_CC performance_NN1 based_VVN salary_NN1 ,_, executives_NN2 also_RR obtain_VV0 various_JJ fringe_NN1 benefits_NN2 from_II the_AT company_NN1 ._. 
</s>
<s>
Some_DD examples_NN2 are_VBR a_AT1 company_NN1 car_NN1 ,_, company_NN1 boat_NN1 or_CC even_RR vantage_NN1 to_TO hunt_VVI (_( Pietarinen_NP1 ,_, Taloussanoma_NP1 2012_MC )_) These_DD2 fringe_NN1 benefits_NN2 do_VD0 usually_RR not_XX have_VHI any_DD significant_JJ effects_NN2 regarding_II corporate_JJ governance_NN1 ._. 
</s>
<s>
It_PPH1 's_VBZ important_JJ to_TO mention_VVI pension_NN1 benefits_NN2 and_CC other_JJ stealth_NN1 compensations_NN2 under_II this_DD1 subtitle_NN1 ._. 
</s>
<s>
These_DD2 compensation_NN1 methods_NN2 make_VV0 the_AT total_JJ executive_NN1 pay_NN1 less_RGR transparent_JJ and_CC may_VM not_XX necessarily_RR be_VBI connected_VVN with_IW the_AT executive_NN1 's_GE performance_NN1 ._. 
</s>
<s>
Moreover_RR ,_, compensations_NN2 given_VVN to_II executives_NN2 after_CS they_PPHS2 retire_VV0 do_VD0 not_XX have_VHI to_TO be_VBI included_VVN in_II firm_NN1 's_GE public_JJ compensation_NN1 tables_NN2 or_CC calculations_NN2 ._. 
</s>
<s>
Pension_NN1 plans_NN2 or_CC other_JJ postponed_JJ compensation_NN1 is_VBZ not_XX taken_VVN into_II account_NN1 in_II the_AT empirical_JJ part_NN1 of_IO this_DD1 paper._NNU 5_MC ._. 
</s>
<s>
Arguments_NN2 for_IF and_CC against_II "_" CEOs_NN2 are_VBR overpaid_VVN in_II Finland_NP1 "_" This_DD1 chapter_NN1 will_VM give_VVI some_DD arguments_NN2 for_IF and_CC against_II why_RRQ CEOs_NN2 in_II Finland_NP1 would_VM be_VBI overpaid_VVN ._. 
</s>
<s>
As_II a_AT1 starting_NN1 point_NN1 of_IO view_NN1 it_PPH1 's_VBZ good_JJ to_TO mention_VVI that_CST the_AT question_NN1 itself_PPX1 does_VDZ n't_XX have_VHI a_AT1 correct_JJ answer_NN1 ,_, since_CS it_PPH1 's_VBZ all_DB about_II opinions_NN2 ._. 
</s>
<s>
There_EX is_VBZ no_AT such_DA thing_NN1 as_II a_AT1 "_" fair_JJ "_" payment_NN1 for_IF CEOs_NN2 as_CSA Edwin_NP1 Lock_NP1 among_II others_NN2 have_VH0 stated_VVN (_( Society_NN1 for_IF industrial_JJ &organizational;_NULL psychology_NN1 )_) ._. 
</s>
<s>
Another_DD1 thing_NN1 worth_II mentioning_VVG is_VBZ as_RG well_JJ that_CST many_DA2 of_IO the_AT statements_NN2 presented_VVN here_RL are_VBR general_JJ statements_NN2 about_II CEOs_NN2 compensations_NN2 ._. 
</s>
<s>
These_DD2 statements_NN2 are_VBR valid_JJ both_RR in_II Finland_NP1 as_II31 well_II32 as_II33 in_II other_JJ countries._NNU 5.1_MC ._. 
</s>
<s>
Arguments_NN2 claiming_VVG overpayment_NN1 5.1.1_MC ._. 
</s>
<s>
CEO_NN1 payments_NN2 increased_VVN faster_RRR compared_VVN to_II other_JJ employees_NN2 Many_DA2 people_NN have_VH0 claimed_VVN that_CST the_AT CEO_NN1 payments_NN2 have_VH0 increased_VVN much_RR faster_RRR than_CSN the_AT compensation_NN1 for_IF other_JJ employees_NN2 ._. 
</s>
<s>
In_II fact_NN1 ,_, when_CS looking_VVG at_II a_AT1 sample_NN1 of_IO three_MC Finnish_JJ large_JJ cap_NN1 companies_NN2 (_( YIT_NP1 ,_, Metso_NP1 and_CC Fortum_NP1 )_) the_AT average_JJ increase_NN1 in_II the_AT CEO_NN1 payments_NN2 had_VHD been_VBN 7,92_MC %_NNU between_II the_AT years_NNT2 2003-2010_MCMC ._. 
</s>
<s>
A_AT1 comparable_JJ figure_NN1 for_IF the_AT average_JJ pay_NN1 taker_NN1 in_II Finland_NP1 was_VBDZ 3,92_MC %_NNU (_( Tilastokeskus_NP1 )_) ._. 
</s>
<s>
See_VV0 graph_NN1 1_MC1 ._. 
</s>
<s>
However_RR ,_, as_RG earlier_RRR stated_VVD Kaplan_NP1 (_( 2008_MC )_) showed_VVD that_CST the_AT payment_NN1 for_IF also_RR other_JJ talented_JJ and_CC fortunate_JJ groups_NN2 have_VH0 increased_VVN strongly_RR ,_, in_II fact_NN1 even_RR faster_RRR than_CSN the_AT CEO_NN1 payments._NNU 5.1.2_MC ._. 
</s>
<s>
Compensations_NN2 not_XX related_VVN to_II performance_NN1 The_AT most_RGT important_JJ task_NN1 for_IF the_AT management_NN1 of_IO a_AT1 firm_NN1 is_VBZ to_TO maximize_VVI the_AT shareholder_NN1 value_NN1 ._. 
</s>
<s>
In_II contrast_NN1 to_II this_DD1 Cooper_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2009_MC )_) found_VVD that_DD1 industry_NN1 and_CC size_NN1 adjusted_VVN CEO_NN1 pay_NN1 is_VBZ negatively_RR related_VVN to_II future_JJ shareholder_NN1 wealth_NN1 ._. 
</s>
<s>
According_II21 to_II22 their_APPGE study_NN1 ,_, CEOs_NN2 in_II the_AT top_NN1 ten_MC percent_NNU of_IO pay_NN1 earn_VV0 negative_JJ abnormal_JJ share_NN1 price_NN1 returns_VVZ over_II the_AT next_MD five_MC years_NNT2 of_IO approximately_RR -13%_FO ._. 
</s>
<s>
The_AT effect_NN1 was_VBDZ found_VVN to_TO be_VBI even_RR stronger_JJR for_IF CEOs_NN2 who_PNQS received_VVD higher_JJR incentives_NN2 compared_VVN to_II their_APPGE peers_NN2 ._. 
</s>
<s>
If_CS the_AT CEO_NN1 compensation_NN1 would_VM be_VBI truly_RR related_VVN to_II performance_NN1 ,_, studies_NN2 like_II Coopers_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
should_VM show_VVI correlation_NN1 between_II better_JJR abnormal_JJ return_NN1 for_IF companies_NN2 with_IW CEOs_NN2 who_PNQS receive_VV0 higher_JJR salary_NN1 ._. 
</s>
<s>
Even_CS21 if_CS22 the_AT most_RGT important_JJ factor_NN1 regarding_II the_AT CEO_NN1 payments_NN2 should_VM be_VBI that_CST the_AT compensation_NN1 is_VBZ connected_VVN to_II the_AT firms_NN2 '_GE performance_NN1 ,_, as_CSA Edwin_NP1 Locke_NP1 among_II others_NN2 have_VH0 stated_VVN ,_, this_DD1 does_VDZ not_XX however_RR seem_VVI to_TO be_VBI the_AT case_NN1 (_( Society_NN1 for_IF industrial_JJ &;_NULL organizational_JJ psychology_NN1 )_) ._. 
</s>
<s>
A_AT1 regression_NN1 study_NN1 regarding_II which_DDQ variables_NN2 affects_VVZ the_AT CEO_NN1 compensation_NN1 in_II Finland_NP1 will_VM be_VBI presented_VVN later._NNU 5.1.3_MC ._. 
</s>
<s>
CEOs_NN2 influence_VV0 their_APPGE own_DA salary_NN1 There_EX are_VBR several_DA2 ways_NN2 how_RRQ CEOs_NN2 can_VM try_VVI to_TO influence_VVI their_APPGE salary_NN1 ._. 
</s>
<s>
First_MD of_IO all_DB it_PPH1 is_VBZ claimed_VVN that_CST CEOs_NN2 typically_RR try_VV0 to_TO protect_VVI their_APPGE payments_NN2 from_II falling_VVG stock_NN1 prices_NN2 in_II different_JJ ways_NN2 ._. 
</s>
<s>
One_MC1 way_NN1 of_IO doing_VDG this_DD1 is_VBZ by_II trying_VVG to_TO tie_VVI stock_NN1 options_NN2 to_II favorable_JJ low_JJ market_NN1 value_NN1 circumstances_NN2 ._. 
</s>
<s>
Previous_JJ studies_NN2 like_II Brookman_NP1 &;_NULL Craig_NP1 (_( 2006_MC )_) showed_VVD that_CST CEOs_NN2 compensations_NN2 were_VBDR approximately_RR similar_JJ to_II those_DD2 of_IO a_AT1 bull_NN1 market_NN1 through_II a_AT1 bear_NN1 market_NN1 ._. 
</s>
<s>
However_RR ,_, their_APPGE study_NN1 consisted_VVN of_IO small_JJ market_NN1 capitalization_NN1 firms_NN2 which_DDQ partly_RR can_VM explain_VVI the_AT smaller_JJR stock_NN1 price_NN1 performance_NN1 sensitivity_NN1 to_II CEO_NN1 payments_NN2 ._. 
</s>
<s>
Another_DD1 way_NN1 how_RRQ CEOs_NN2 can_VM influence_VVI their_APPGE own_DA salary_NN1 is_VBZ by_II having_VHG good_JJ relationships_NN2 to_II the_AT board_NN1 of_IO directors_NN2 who_PNQS are_VBR deciding_VVG about_II CEOs_NN2 compensations_NN2 ._. 
</s>
<s>
Main_JJ et_RA21 al._RA22 (_( 1995_MC )_) found_VVD that_CST so_JJ21 called_JJ22 "_" social_JJ influence_NN1 "_" may_VM be_VBI responsible_JJ for_IF significant_JJ increments_NN2 in_II the_AT CEO_NN1 compensation_NN1 beyond_II what_DDQ economic_JJ theories_NN2 would_VM predict._NNU 5.2_MC ._. 
</s>
<s>
Arguments_NN2 denying_VVG overpayment_NN1 5.2.1_MC ._. 
</s>
<s>
Increasing_JJ CEO_NN1 turnover_NN1 Many_DA2 prior_JJ studies_NN2 have_VH0 shown_VVN that_CST the_AT CEO_NN1 turnover_NN1 has_VHZ increased_VVN ._. 
</s>
<s>
In_II other_JJ words_NN2 CEOs_NN2 are_VBR fired_VVN more_RGR frequently_RR today_RT than_CSN historically_RR ._. 
</s>
<s>
Kaplan_NP1 &;_NULL Minton_NP1 (_( 2007_MC )_) showed_VVD in_II their_APPGE study_NN1 that_CST the_AT average_JJ annual_JJ CEO_NN1 turnover_NN1 was_VBDZ 15,6_MC %_NNU from_II 1992-_NN1 2005_MC for_IF a_AT1 sample_NN1 of_IO large_JJ U.S_NP1 companies_NN2 ._. 
</s>
<s>
In_II 1998_MC the_AT CEO_NN1 turnover_NN1 was_VBDZ 17.4_MC %_NNU ._. 
</s>
<s>
This_DD1 implies_VVZ that_CST the_AT turnover_NN1 had_VHD an_AT1 increasing_JJ trend_NN1 ._. 
</s>
<s>
According_II21 to_II22 a_AT1 study_NN1 by_II Taloussanomat_NP1 the_AT situation_NN1 is_VBZ similar_JJ in_II Finland_NP1 ._. 
</s>
<s>
A_AT1 CEO_NN1 kept_VVD his_APPGE or_CC her_APPGE position_NN1 in_II average_NN1 4.5_MC years_NNT2 in_II 2007_MC ._. 
</s>
<s>
The_AT comparable_JJ figure_NN1 for_IF 2004_MC was_VBDZ six_MC years_NNT2 (_( Pennanen_NP1 ,_, 2008_MC )_) ._. 
</s>
<s>
The_AT increasing_JJ CEO_NN1 turnover_NN1 explains_VVZ that_CST the_AT CEO_NN1 position_NN1 is_VBZ more_RGR unstable_JJ now_RT days_NNT2 and_CC therefore_RR it_PPH1 's_VBZ possible_JJ to_TO argue_VVI that_CST CEOs_NN2 should_VM be_VBI compensated_VVN more_RRR today_RT than_CSN historical_JJ levels_NN2 imply._NNU 5.2.2_MC ._. 
</s>
<s>
The_AT CEO_NN1 payment_NN1 is_VBZ just_RR the_AT "_" normal_JJ market_NN1 price_NN1 "_" The_AT CEO_NN1 payment_NN1 is_VBZ just_RR more_RRR or_CC less_RRR the_AT market_NN1 price_NN1 where_CS demand_NN1 and_CC supply_NN1 meets_VVZ ._. 
</s>
<s>
This_DD1 is_VBZ something_PN1 what_DDQ professor_NN1 Edwin_NP1 Lock_NP1 at_II the_AT University_NN1 of_IO Maryland_NP1 has_VHZ argued_VVN (_( Society_NN1 for_IF industrial_JJ &organizational;_NULL psychology_NN1 )_) ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 ;_; Albert_NP1 Cannella_NP1 professor_NN1 at_II A.B_NP1 ._. 
</s>
<s>
Freeman_NN1 School_NN1 of_IO Business_NN1 at_II Tulane_NP1 University_NN1 argues_VVZ that_CST the_AT market_NN1 for_IF CEOs_NN2 does_VDZ n't_XX work_VVI as_II a_AT1 normal_JJ marketplace_NN1 since_CS there_EX is_VBZ not_XX enough_DD buying_NN1 and_CC selling_NN1 going_VVG on_II (_( Society_NN1 for_IF industrial_JJ &organizational;_NULL psychology_NN1 )_) ._. 
</s>
<s>
He_PPHS1 continues_VVZ by_II stating_VVG that_CST it_PPH1 's_VBZ extremely_RR rare_JJ that_CST CEO_NN1 's_VBZ would_VM frequently_RR leave_VVI their_APPGE positions_NN2 for_IF higher_JJR salaries_NN2 as_CSA it_PPH1 's_VBZ more_RGR likely_JJ that_CST the_AT CEO_NN1 acts_VVZ in_II a_AT1 way_NN1 to_TO secure_VVI his_APPGE or_CC her_APPGE position._NNU 6_MC ._. 
</s>
<s>
Method_NN1 1_MC1 :_: What_DDQ affects_VVZ the_AT CEO_NN1 payments_NN2 in_II Finland_NP1 ?_? 
</s>
<s>
In_II the_AT first_MD method_NN1 a_AT1 regression_NN1 is_VBZ built_VVN up_RP which_DDQ simply_RR explains_VVZ which_DDQ are_VBR the_AT most_RGT significant_JJ variables_NN2 affecting_VVG the_AT amount_NN1 of_IO CEO_NN1 payment._NNU 6.1_MC ._. 
</s>
<s>
Data_NN The_AT data_NN consists_VVZ of_IO all_DB the_AT listed_JJ OMXH_NN1 companies_NN2 with_IW a_AT1 current_JJ market_NN1 cap_NN1 greater_JJR than_CSN EUR_NP1 100m_NNU ._. 
</s>
<s>
Financial_JJ companies_NN2 have_VH0 been_VBN excluded_VVN since_CS their_APPGE differing_JJ income_NN1 statement_NN1 and_CC balance_NN1 sheet_NN1 structure_NN1 ._. 
</s>
<s>
For_IF a_AT1 complete_JJ list_NN1 of_IO companies_NN2 included_VVD ,_, please_RR see_VV0 appendix_NN1 1_MC1 ._. 
</s>
<s>
The_AT data_NN has_VHZ been_VBN collected_VVN from_II the_AT Bloomberg_NP1 database_NN1 ._. 
</s>
<s>
The_AT CEO_NN1 salary_NN1 data_NN have_VH0 been_VBN collected_VVN from_II the_AT companies_NN2 '_GE webpages._NNU 6.1.1_MC ._. 
</s>
<s>
Descriptive_JJ statistics_NN &lsqb;_( Table_NN1 &rsqb;_) &lsqb;_( Table_NN1 &rsqb;_) &lsqb;_( Table_NN1 &rsqb;_) As_II the_AT dependent_JJ variable_NN1 the_AT total_JJ CEO_NN1 compensation_NN1 have_VH0 been_VBN chosen_VVN ._. 
</s>
<s>
As_II the_AT explaining_NN1 variables_NN2 :_: net_JJ income_NN1 growth_NN1 ,_, share_NN1 price_NN1 performance_NN1 ,_, ROE_NN ,_, ebit_VV0 margin_NN1 and_CC market_VV0 cap_NN1 have_VH0 been_VBN used_VVN ._. 
</s>
<s>
All_DB explaining_VVG variable_NN1 are_VBR averages_NN2 of_IO 2006-2010_MCMC ._. 
</s>
<s>
It_PPH1 's_VBZ expected_VVN that_CST the_AT market_NN1 cap_NN1 is_VBZ the_AT only_JJ variable_NN1 which_DDQ will_VM show_VVI any_DD significant_JJ results._NNU 6.3_MC ._. 
</s>
<s>
Method_NN1 1_MC1 results_NN2 &lsqb;_( Table_NN1 &rsqb;_) As_CSA can_VM see_VVI from_II the_AT result_NN1 table_NN1 above_RL ,_, the_AT most_RGT significant_JJ variable_NN1 is_VBZ the_AT size_NN1 of_IO the_AT firm_NN1 ,_, as_CSA expected_VVN ._. 
</s>
<s>
Bigger_JJR firms_NN2 pay_VV0 their_APPGE CEOs_NN2 more_RRR ._. 
</s>
<s>
All_DB the_AT other_JJ variables_NN2 were_VBDR more_RGR or_CC less_DAR not_XX significant_JJ even_CS21 if_CS22 some_DD of_IO them_PPHO2 statistically_RR showed_VVD some_DD significance_NN1 ._. 
</s>
<s>
The_AT conclusion_NN1 from_II the_AT first_MD model_NN1 is_VBZ the_AT most_RGT important_JJ factor_NN1 determining_VVG the_AT CEO_NN1 payment_NN1 is_VBZ the_AT firm_JJ size_NN1 ._. 
</s>
<s>
This_DD1 might_VM lead_VVI to_II empire_NN1 building_NN1 which_DDQ was_VBDZ described_VVN earlier_RRR in_II the_AT agency_NN1 problem_NN1 section._NNU 7_MC ._. 
</s>
<s>
Method_NN1 2_MC :_: What_DDQ changes_VVZ the_AT CEO_NN1 payment_NN1 ?_? (_( work_VV0 in_II progress_NN1 )_) The_AT second_MD method_NN1 is_VBZ going_VVGK to_TO look_VVI at_II factors_NN2 which_DDQ affect_VV0 the_AT change_NN1 of_IO the_AT CEO_NN1 compensation_NN1 ._. 
</s>
<s>
As_II the_AT dependent_JJ variable_NN1 the_AT method_NN1 is_VBZ now_RT looking_VVG at_II the_AT change_NN1 in_II the_AT CEO_NN1 payment_NN1 instead_II21 of_II22 the_AT total_JJ Lg_NP1 of_IO CEO_NN1 compensation_NN1 ,_, as_CSA method_NN1 1_MC1 did._NNU 7.1_MC ._. 
</s>
<s>
Planned_JJ variables_NN2 (_( work_VV0 in_II progress_NN1 )_) &lsqb;_( Table_NN1 &rsqb;_) 8_MC ._. 
</s>
<s>
Conclusions_NN2 (_( work_VV0 in_II progress_NN1 )_) 
</s>
