<s>
Marketing_NN1 to_II women_NN2 Introduction_NN1 Nowadays_RT ,_, marketing_VVG to_II women_NN2 is_VBZ booming_VVG in_II the_AT field_NN1 of_IO marketing_NN1 and_CC women_NN2 become_VV0 markets_NN2 hot_JJ keyword.Faith_NNU popcorn_NN1 ,_, a_AT1 futurologist_NN1 ,_, said_VVD that_CST 21_MC centuries_NNT2 is_VBZ centuries_NNT2 of_IO EVEolution_NN1 which_DDQ is_VBZ a_AT1 compound_NN1 word_NN1 formed_VVN from_II the_AT words_NN2 Eve_NP1 and_CC Evolution_NN1 ._. 
</s>
<s>
From_II women-only_JJ credit_NN1 cards_NN2 to_II mobile_JJ communication_NN1 service_NN1 ,_, lots_PN of_IO services_NN2 and_CC products_NN2 only_RR for_IF women_NN2 are_VBR rapidly_RR rising_VVG ._. 
</s>
<s>
Women_NN2 buyers_NN2 are_VBR getting_VVG more_DAR attention_NN1 from_II marketers_NN2 than_CSN ever_RR before.Women_NNU make_VV0 85%_NNU of_IO all_DB consumer_NN1 buying_NN1 decisions_NN2 and_CC spend_VV0 more_DAR than_CSN 3.3_MC trillion_NNO annually_RR ._. 
</s>
<s>
Considering_CS those_DD2 statistics_NN ,_, marketing_VVG to_II women_NN2 is_VBZ regarded_VVN as_II the_AT best_JJT and_CC fastest_JJT way_NN1 to_TO make_VVI profits_NN2 in_II todays_NN2 market_VV0 ._. 
</s>
<s>
Marketing_NN1 expert_NN1 Tom_NP1 Peters_VVZ says_VVZ ,_, I_PPIS1 have_VH0 never_RR before_RT tripped_VVN over_RP an_AT1 opportunity_NN1 this_DD1 size._NNU Approaching_JJ women_NN2 is_VBZ not_XX a_AT1 recommendable_JJ thing_NN1 to_TO do_VDI but_CCB what_DDQ marketers_NN2 must_VM do_VDI ._. 
</s>
<s>
According_II21 to_II22 this_DD1 tendency_NN1 ,_, many_DA2 companies_NN2 from_II automobile_NN1 market_NN1 to_II sports_NN2 market_VV0 want_VV0 and_CC need_VV0 to_TO attract_VVI women_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ not_XX wonder_VV0 that_DD1 marketing_NN1 to_II women_NN2 has_VHZ become_VVN a_AT1 priority_NN1 to_II a_AT1 lot_NN1 ofcompanies_NN2 and_CC marketers.In_NNU reality_NN1 ,_, however_RR ,_, not_XX all_DB of_IO them_PPHO2 are_VBR successful_JJ and_CC about_RG 70%_NNU of_IO women_NN2 feel_VV0 misunderstood_VVN by_II marketers_NN2 ._. 
</s>
<s>
That_REX21 is_REX22 ,_, despite_II of_IO the_AT importance_NN1 of_IO women_NN2 in_II todays_NN2 market_VV0 ,_, marketers_NN2 are_VBR not_XX approaching_VVG them_PPHO2 in_II a_AT1 proper_JJ way_NN1 ._. 
</s>
<s>
Why_RRQ isit_VVI so_RR ?_? 
</s>
<s>
Women_NN2 market_VV0 is_VBZ different_JJ from_II Men_NN2 market_VV0 and_CC other_JJ markets_NN2 ._. 
</s>
<s>
It_PPH1 seems_VVZ that_CST previous_JJ studies_NN2 have_VH0 not_XX paid_VVN attention_NN1 to_II the_AT reasons_NN2 why_RRQ they_PPHS2 react_VV0 differently.This_NNU paper_NN1 emphasizes_VVZ that_DD1 understanding_NN1 gender_NN1 differences_NN2 is_VBZ the_AT keyin_NN1 theapproach_NN1 of_IO women_NN2 ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO attract_VVI women_NN2 ,_, itiscrucial_JJ to_TO understand_VVI why_RRQ women_NN2 have_VH0 different_JJ purchasingdecisions_NN2 than_CSN men_NN2 and_CC how_RRQ they_PPHS2 react_VV0 differently_RR to_II similar_JJ marketing.In_NNU order_NN1 to_TO accomplish_VVI that_DD1 ,_, this_DD1 paper_NN1 focuses_VVZ on_II findings_NN2 about_II differences_NN2 between_II men_NN2 and_CC women_NN2 from_II fields_NN2 such_II21 as_II22 anthropology_NN1 and_CC psychology_NN1 ._. 
</s>
<s>
In_II doing_VDG so_RR ,_, this_DD1 paper_NN1 hopes_VVZ to_TO answer_VVI to_II What_DDQ is_VBZ the_AT best_JJT way_NN1 to_TO approach_VVI women_NN2 market_VV0 and_CC to_TO attract_VVI them_PPHO2 ?_? 
</s>
<s>
By_II examining_VVG many_DA2 cases_NN2 that_CST show_VV0 the_AT strategies_NN2 and_CC outcomes_NN2 of_IO companies_NN2 which_DDQ tried_VVD to_TO approach_VVI women_NN2 market_VV0 ,_, it_PPH1 is_VBZ possible_JJ to_TO figure_VVI out_RP what_DDQ kind_NN1 of_IO strategies_NN2 can_VM be_VBI successful_JJ ._. 
</s>
<s>
This_DD1 paper_NN1 is_VBZ organized_VVN into_II four_MC sections_NN2 ._. 
</s>
<s>
Above_II all_DB ,_, it_PPH1 is_VBZ important_JJ to_TO answer_VVI Why_RRQ women_NN2 market_VV0 ?_? 
</s>
<s>
In_BCL21 order_BCL22 to_TO find_VVI out_RP the_AT reason_NN1 we_PPIS2 have_VH0 to_TO focus_VVI on_II women_NN2 ,_, this_DD1 paper_NN1 will_VM examine_VVI the_AT current_JJ purchasing_NN1 power_NN1 of_IO women_NN2 ._. 
</s>
<s>
Next_MD ,_, knowing_VVG current_JJ marketing_NN1 effort_NN1 to_TO reach_VVI women_NN2 is_VBZ essential_JJ ._. 
</s>
<s>
We_PPIS2 need_VV0 to_II learnwhy_NN1 some_DD marketers_NN2 are_VBR failing_VVG in_II attracting_JJ women_NN2 ,_, because_CS failure_NN1 teaches_VVZ success.By_NNU researching_VVG cases_NN2 that_CST can_VM show_VVI what_DDQ went_VVD wrong_RR and_CC right_RR ,_, we_PPIS2 can_VM find_VVI the_AT right_JJ direction_NN1 to_TO take_VVI ._. 
</s>
<s>
Then_RT ,_, studying_VVG the_AT differences_NN2 that_CST make_VV0 difference_NN1 between_II male_NN1 and_CC female_NN1 is_VBZ needed_VVN ._. 
</s>
<s>
To_TO better_RRR understand_VVI women_NN2 ,_, it_PPH1 is_VBZ crucial_JJ to_TO know_VVI what_DDQ makes_VVZ women_NN2 react_VVI differently_RR ._. 
</s>
<s>
At_RR21 last_RR22 ,_, finding_VVG the_AT key_NN1 to_II approaching_VVG women_NN2 is_VBZ possible_JJ ._. 
</s>
<s>
Based_VVN on_II the_AT fact_NN1 we_PPIS2 examinein_NN1 previous_JJ chapters_NN2 ,_, the_AT right_JJ way_NN1 to_TO attract_VVI women_NN2 can_VM bedefined_VVD ._. 
</s>
<s>
Why_RRQ women_NN2 market_VV0 ?_? 
</s>
<s>
All_RR over_II the_AT world_NN1 ,_, the_AT influence_NN1 of_IO women_NN2 in_II the_AT market_NN1 is_VBZ rapidly_RR growing_VVG ._. 
</s>
<s>
Why_RRQ ?_? 
</s>
<s>
In_II modern_JJ society_NN1 ,_, womens_VVZ status_NN1 is_VBZ changed_VVN a_AT1 lot_NN1 ._. 
</s>
<s>
According_II21 to_II22 the_AT womens_NN2 increased_JJ level_NN1 of_IO education_NN1 and_CC income_NN1 ,_, elite_NN1 women_NN2 such_II21 as_II22 Alpha_NN1 girl_NN1 ,_, Gold_NN1 miss_VV0 ,_, SWAN_NP1 (_( Strong_JJ Women_NN2 Achiever_VV0 ,_, No_AT Spouse_NN1 )_) are_VBR briskly_RR participating_VVG in_II social_JJ activities.They_NNU earn_VV0 ,_, own_VV0 ,_, and_CC purchase_VV0 more_DAR than_CSN ever_RR before_RT ._. 
</s>
<s>
Womens_NP1 income_NN1 around_II the_AT world_NN1 reached_VVN about_RG 20_MC trillion_NNO dollars_NNU2 ._. 
</s>
<s>
This_DD1 figure_NN1 is_VBZ expected_VVN to_TO increase_VVI by_II up_RG21 to_RG22 28_MC trillion_NNO dollars_NNU2 in_II 2014_MC which_DDQ is_VBZ more_DAR than_CSN 2_MC times_NNT2 greater_JJR than_CSN the_AT sum_NN1 of_IO Indian_JJ and_CC Chinese_JJ market_NN1 ._. 
</s>
<s>
According_II21 to_II22 these_DD2 tendencies_NN2 ,_, women_NN2 became_VVD major_JJ consumer_NN1 with_IW enormous_JJ economic_JJ power_NN1 ._. 
</s>
<s>
In_II fact_NN1 ,_, households_NN2 across_II America_NP1 can_VM thank_VVI womens_NN2 earning_VVG powerfor_NN1 their_APPGE steadygrowth_NN1 in_II standard_NN1 of_IO living_NN1 ._. 
</s>
<s>
Its_APPGE true_JJ now_RT ,_, and_CC its_APPGE just_RR getting_VVG truer_JJR :_: overthe_VV0 next_MD two_MC decades_NNT2 we_PPIS2 will_VM see_VVI the_AT immense_JJ assets_NN2 of_IO two_MC generations_NN2 becomeincreasingly_RR concentrated_VVN in_II the_AT hands_NN2 of_IO Baby_NN1 Boomer_NP1 women_NN2 ._. 
</s>
<s>
What_DDQ that_DD1 means_VVZ is_VBZ thattheres_NN2 an_AT1 existing_JJ market_NN1 and_CC a_AT1 potential_JJ market_NN1 ._. 
</s>
<s>
Lets_VVZ look_NN1 at_II a_AT1 few_DA2 reasons_NN2 for_IF thischange_NN1 in_II both_DB2 the_AT current_JJ and_CC future_NN1 womens_VVZ markets_NN2 :_: Soaring_JJ Income_NN1 :_: Over_II the_AT past_JJ three_MC decades_NNT2 (_( 1970-1998_MCMC )_) ,_, mens_VVZ median_JJ incomehas_NN2 barely_RR budged_VVD ,_, while_CS womens_NN2 has_VHZ soared_VVN ._. 
</s>
<s>
Narrowing_VVG Wage_NN1 Gap_NN1 :_: While_CS its_APPGE true_JJ that_CST on_II average_NN1 ,_, full-time_JJ year-round_JJ workingwomen_NN2 earn_VV0 only_RR 76_MC cents_NNU2 on_II the_AT dollar_NNU1 compared_VVN to_II their_APPGE male_JJ counterparts_NN2 ,_, thatwage_VV0 gap_NN1 is_VBZ narrowing_VVG rapidly_RR ._. 
</s>
<s>
In_II 1998_MC ,_, women_NN2 25-34_MCMC earned_VVD 83_MC cents_NNU2 on_II the_AT dollar_NNU1 and_CC young_JJ women_NN2 19-24_MCMC earned_VVD 89_MC cents_NNU2 ._. 
</s>
<s>
Earning_VVG More_RRR :_: As_II21 of_II22 1999_MC ,_, 30%_NNU of_IO women_NN2 out-earned_VVD their_APPGE husbands_NN2 ._. 
</s>
<s>
Over_II the_AT next_MD decade_NNT1 ,_, women_NN2 will_VM control_VVI two_MC thirds_MF of_IO consumer_NN1 wealth_NN1 in_II the_AT United_NP1 States_NP1 and_CC be_VBI the_AT beneficiaries_NN2 of_IO the_AT largest_JJT transference_NN1 of_IO wealth_NN1 in_II our_APPGE countrys_NN2 history_NN1 ._. 
</s>
<s>
Estimates_NN2 range_VV0 from_II $12_NNU to_II $40_NNU trillion_NNO ._. 
</s>
<s>
Many_DA2 Boomer_NP1 women_NN2 will_VM experience_VVI a_AT1 double_JJ inheritance_NN1 windfall_NN1 ,_, from_II both_RR parents_NN2 and_CC husband_NN1 ._. 
</s>
<s>
The_AT Boomer_NP1 woman_NN1 is_VBZ a_AT1 consumer_NN1 that_CST luxury_JJ brands_NN2 want_VV0 to_TO resonate_VVI with.The_NNU number_NN1 of_IO wealthy_JJ women_NN2 investors_NN2 in_II the_AT U.S._NP1 is_VBZ growing_VVG at_II a_AT1 faster_JJR rate_NN1 than_CSN that_DD1 of_IO men_NN2 ._. 
</s>
<s>
In_II a_AT1 two-year_JJ period_NN1 ,_, the_AT number_NN1 of_IO wealthy_JJ women_NN2 in_II the_AT U.S._NP1 grew_VVD 68%_NNU ,_, while_CS the_AT number_NN1 of_IO men_NN2 grew_VVD only_RR 36%_NNU ._. 
</s>
<s>
Wealthy_JJ boomer_NN1 women_NN2 are_VBR the_AT marquee_NN1 players_NN2 in_II our_APPGE countrys_NN2 culture_NN1 and_CC commerce_NN1 ._. 
</s>
<s>
Single_JJ women_NN2 are_VBR spending_VVG enormous_JJ money_NN1 in_II variety_NN1 areas_NN2 such_II21 as_II22 finance_NN1 ,_, premium_JJ clothes_NN2 ,_, and_CC cultural_JJ activities_NN2 and_CC it_PPH1 is_VBZ much_RR higher_RRR compare_VV0 to_II single_JJ men_NN2 ._. 
</s>
<s>
The_AT more_RGR attractive_JJ thing_NN1 in_II women_NN2 purchasing_NN1 power_NN1 is_VBZ that_CST ,_, however_RR ,_, in_II31 addition_II32 to_II33 their_APPGE own_DA income_NN1 and_CC consumption_NN1 ,_, women_NN2 are_VBR controlling_VVG most_DAT of_IO the_AT spending_NN1 in_II the_AT household.MariaT_NNU ._. 
</s>
<s>
Bailey_NP1 ,_, a_AT1 pioneer_NN1 of_IO Mom_NN1 marketing_NN1 ,_, pointed_VVD that_CST women_NN2 have_VH0 cardinal_JJ meanings_NN2 in_CS21 that_CS22 they_PPHS2 purchase_VV0 all_DB daily_JJ necessaries_NN2 and_CC household_NN1 establishments_NN2 ._. 
</s>
<s>
That_REX21 is_REX22 ,_, moms_NN2 propensity_NN1 to_TO consume_VVI has_VHZ an_AT1 influence_NN1 on_II consumption_NN1 habit_NN1 and_CC purchasing_VVG decision_NN1 of_IO their_APPGE family_NN1 members.Also_NNU ,_, as_CSA mom_NN1 can_VM affect_VVI their_APPGE young_JJ children_NN2 ,_, they_PPHS2 can_VM form_VVI future_JJ consumers_NN2 behavior_NN1 ._. 
</s>
<s>
The_AT generally_RR accepted_JJ estimate_NN1 of_IO womens_NN2 buying_VVG power_NN1 puts_VVZ it_PPH1 at_II 80%_NNU ofall_NN1 household_NN1 spending_NN1 ._. 
</s>
<s>
Women_NN2 account_VV0 for_IF the_AT following_JJ :_: 85_MC percent_NNU of_IO all_DB consumer_NN1 purchases_NN2 ,_, ranging_VVG from_II cars_NN2 to_II computes_VVZ 91_MC percent_NNU of_IO new_JJ homes_NN2 66_MC percent_NNU of_IO personal_JJ computers_NN2 92_MC percent_NNU of_IO vacations_NN2 80_MC percent_NNU of_IO health_NN1 care_NN1 decisions_NN2 65_MC percent_NNU of_IO new_JJ cars_NN2 89_MC percent_NNU of_IO bank_NN1 accounts_NN2 93_MC percent_NNU of_IO food_NN1 purchases_NN2 93_MC percent_NNU of_IO over-the-counter_JJ pharmaceuticals_NN2 As_CSA you_PPY can_VM see_VVI above_RL ,_, womens_VVZ purchasing_NN1 power_NN1 is_VBZ very_RG enormous_JJ and_CC more_RGR profitable_JJ than_CSN any_DD other_JJ segment_NN1 market_NN1 ._. 
</s>
<s>
Another_DD1 reason_NN1 marketers_NN2 are_VBR focusing_VVG on_II women_NN2 buyers_NN2 is_VBZ the_AT fact_NN1 that_CST their_APPGE ripple_NN1 effect_NN1 is_VBZ huge_JJ ._. 
</s>
<s>
Women_NN2 do_VD0 not_XX enjoy_VVI shopping_VVG alone_RR ._. 
</s>
<s>
Their_APPGE characteristic_NN1 which_DDQ is_VBZ communicative_JJ and_CC developed_JJ linguistic_JJ sense_NN1 is_VBZ applied_VVN to_II consumption_NN1 too_RR ,_, so_CS they_PPHS2 shop_VV0 with_IW friends_NN2 ._. 
</s>
<s>
Also_RR ,_, women_NN2 converse_VV0 about_II their_APPGE purchasing_NN1 item_NN1 with_IW others_NN2 6.3_MC times_NNT2 more_RRR than_CSN men_NN2 do_VD0 ,_, which_DDQ causes_VVZ accompanied_VVN spending_NN1 ._. 
</s>
<s>
From_II this_DD1 point_NN1 of_IO view_NN1 ,_, women_NN2 are_VBR the_AT best_JJT target_NN1 for_IF WOM_NP1 (_( Word_NN1 of_IO mouth_NN1 )_) marketing_NN1 or_CC Buzz_FU marketing_NN1 ._. 
</s>
<s>
Moreover_RR ,_, recently_RR women_NN2 power_NN1 in_II WOM_NP1 marketing_NN1 is_VBZ sharply_RR growing_VVG according_II21 to_II22 a_AT1 huge_JJ number_NN1 of_IO women_NN2 communities_NN2 and_CC wife-loggers_NN2 thanks_NN2 to_II the_AT internet.Since_NNU women_NN2 are_VBR really_RR affected_VVN by_II recommend_VV0 or_CC opinion_NN1 of_IO their_APPGE friends_NN2 when_CS they_PPHS2 make_VV0 purchasing_VVG decision_NN1 ,_, womens_VVZ word_NN1 of_IO mouth_NN1 can_VM be_VBI powerful_JJ promotion_NN1 means_VVZ ._. 
</s>
<s>
Finally_RR ,_, women_NN2 show_VV0 relatively_RR stable_JJ propensity_NN1 to_TO consume_VVI in_II a_AT1 dull_JJ season_NNT1 ._. 
</s>
<s>
Of_RR21 course_RR22 their_APPGE consumptions_NN2 also_RR shrink_VV0 ,_, but_CCB are_VBR less_RRR affected_VVN compare_VV0 to_II men_NN2 ._. 
</s>
<s>
Thats_NN2 because_CS main_JJ consumption_NN1 items_NN2 of_IO women_NN2 are_VBR necessaries_NN2 such_II21 as_II22 cosmetics_NN2 ,_, clothes_NN2 ,_, and_CC groceries_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ different_JJ from_II mens_NN2 decreasing_VVG consumption_NN1 of_IO alcoholic_JJ beverages_NN2 in_II a_AT1 slack_JJ time_NNT1 ._. 
</s>
<s>
In_RR21 short_RR22 ,_, marketers_NN2 should_VM focus_VVI on_II women_NN2 market_VV0 in_II that_DD1 they_PPHS2 have_VH0 rapidly_RR growing_JJ economicpower_NN1 ,_, an_AT1 enormous_JJ influence_NN1 as_II a_AT1 purchasing_NN1 representative_NN1 ,_, huge_JJ ripple_NN1 effects_NN2 and_CC stable_JJ propensity_NN1 ._. 
</s>
<s>
What_DDQ is_VBZ happening_VVG in_II current_JJ market_NN1 ?_? 
</s>
<s>
In_II the_AT past_NN1 ,_, marketing_VVG to_II women_NN2 was_VBDZ limited_VVN to_II cosmetic_JJ and_CC clothing_NN1 market_NN1 ,_, but_CCB recently_RR it_PPH1 has_VHZ been_VBN applied_VVN to_TO market_VVI which_DDQ was_VBDZ mainly_RR men_NN2 market_VV0 such_II21 as_II22 finance_NN1 ,_, IT_NN1 ,_, and_CC alcoholic_JJ beverages_NN2 ._. 
</s>
<s>
To_TO understand_VVI current_JJ effort_NN1 to_TO attract_VVI women_NN2 ,_, let_VM21 's_VM22 have_VHI a_AT1 closer_JJR look_NN1 at_II some_DD cases_NN2 ._. 
</s>
<s>
Wyndham_NP1 Worldwide_JJ Hotel_NN1 :_: Women_NN2 on_II their_APPGE way_NN1 Wyndham_NN1 Worldwide_RL is_VBZ one_MC1 of_IO the_AT world_NN1 's_GE largest_JJT hospitality_NN1 companies_NN2 across_II six_MC continents_NN2 ._. 
</s>
<s>
This_DD1 hotel_NN1 which_DDQ is_VBZ world-renowned_JJ hotel_NN1 brand_NN1 has_VHZ focused_VVN on_II marketing_NN1 to_II women_NN2 who_PNQS have_VH0 business_NN1 trip_NN1 and_CC travel_VV0 alone_RR ._. 
</s>
<s>
As_II a_AT1 result_NN1 ,_, the_AT percentage_NN1 female_NN1 customer_NN1 which_DDQ was_VBDZ only_RR 1_MC1 percent_NNU accounts_VVZ for_IF more_DAR than_CSN 50%_NNU now_RT ._. 
</s>
<s>
Women_NN2 on_II Their_APPGE Way_NN1 is_VBZ the_AT hospitality_NN1 industry_NN1 's_GE longest-running_JJT branded_JJ program_NN1 entirely_RR dedicated_VVN to_II female_JJ travelers_NN2 ._. 
</s>
<s>
Since_CS the_AT program_NN1 's_GE launch_NN1 in_II 1995_MC ,_, Wyndham_NP1 has_VHZ supported_VVN women_NN2 travelers_NN2 as_CSA they_PPHS2 've_VH0 emerged_VVN from_II a_AT1 niche_NN1 market_NN1 to_II a_AT1 formidable_JJ force_NN1 ,_, listening_VVG and_CC responding_VVG to_II women_NN2 's_GE feedback_NN1 ,_, which_DDQ has_VHZ resulted_VVN in_II a_AT1 better_JJR hotel_NN1 experience_NN1 for_IF all_DB travelers_NN2 ;_; including_II the_AT addition_NN1 of_IO various_JJ amenities_NN2 to_II hotel_NN1 rooms_NN2 such_II21 as_II22 coffee_NN1 makers_NN2 ,_, full_JJ length_NN1 mirrors_NN2 and_CC healthier_JJR room_NN1 service_NN1 menus_NN2 ._. 
</s>
<s>
Today_RT ,_, Wyndham_NP1 is_VBZ committed_VVN to_II women_NN2 travelers_NN2 more_RRR than_CSN ever_RR ._. 
</s>
<s>
Ideas_NN2 and_CC suggestions_NN2 from_II women_NN2 are_VBR keys_NN2 in_II improving_VVG the_AT hotel_NN1 travel_NN1 experience_NN1 for_IF everyone_PN1 -_- not_XX just_RR women_NN2 ._. 
</s>
<s>
Wyndham_NN1 takes_VVZ pride_NN1 in_II being_VBG a_AT1 community_NN1 to_II its_APPGE customers_NN2 and_CC has_VHZ a_AT1 long_JJ history_NN1 of_IO its_APPGE commitment_NN1 to_II women_NN2 and_CC their_APPGE families_NN2 ._. 
</s>
<s>
Wyndham_NN1 is_VBZ proud_JJ to_TO call_VVI the_AT WOMEN_NN2 ON_II THEIR_APPGE WAY_NN1 program_NN1 a_AT1 success_NN1 ._. 
</s>
<s>
As_CSA evidenced_VVN by_II women_NN2 business_NN1 travelers_NN2 who_PNQS recognize_VV0 and_CC appreciate_VV0 the_AT program_NN1 's_GE efforts_NN2 ,_, Wyndham_NP1 continues_VVZ to_TO lead_VVI the_AT industry_NN1 's_GE women_NN2 travel_VV0 market_NN1 with_IW innovative_JJ programs_NN2 and_CC opportunities_NN2 for_IF women_NN2 and_CC their_APPGE families_NN2 ._. 
</s>
<s>
Volvo_NP1 :_: YCC_NP1 (_( Your_APPGE Concept_NN1 Car_NN1 )_) Women_NN2 form_VV0 an_AT1 increasingly_RR important_JJ customer_NN1 group_NN1 for_IF Volvo_NP1 Cars_NN2 ._. 
</s>
<s>
In_II theUnited_JJ States_NP1 ,_, 54_MC per_NNU21 cent_NNU22 of_IO all_DB Volvo_NP1 buyers_NN2 are_VBR women_NN2 and_CC the_AT percentage_NN1 offemale_NN1 customers_NN2 in_II Europe_NP1 is_VBZ growing_VVG steadily_RR too.Marti_NNU Barletta_NP1 ,_, an_AT1 American_JJ expert_NN1 on_II female_JJ consumerpatterns_NN2 ,_, claimed_VVD :_: If_CS you_PPY meet_VV0 the_AT expectations_NN2 of_IO women_NN2 ,_, you_PPY exceedthe_VV0 expectations_NN2 of_IO men_NN2 ._. 
</s>
<s>
It_PPH1 was_VBDZ a_AT1 fantastic_JJ opportunity_NN1 for_IF Volvo_NP1 ,_, and_CC being_VBG inspired_VVN by_II those_DD2 facts_NN2 and_CC Marti_NP1 ,_, the_AT managers_NN2 of_IO Volvo_NP1 decided_VVD to_TO develop_VVI YCC_NN1 ._. 
</s>
<s>
The_AT Volvo_NP1 YCC_NP1 launched_VVD at_II the_AT Geneva_NP1 motor_NN1 show_NN1 in_II 2004_MC is_VBZ a_AT1 concept_NN1 car_NN1 designed_VVD bywomen_NN2 for_IF women_NN2 keen_JJ to_TO change_VVI the_AT way_NN1 most_DAT cars_NN2 are_VBR designed_VVN with_IW male_JJ drivers_NN2 in_II mind_NN1 ._. 
</s>
<s>
The_AT stated_JJ goal_NN1 of_IO this_DD1 car_NN1 is_VBZ to_TO meet_VVI the_AT particular_JJ needs_NN2 of_IO women_NN2 driverstargeting_VVG the_AT most_RGT demanding_JJ premium_NN1 customer:the_FO independent_JJ ,_, professional_JJ woman_NN1 ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO do_VDI so_RR ,_, Volvo_NP1 assembled_VVD a_AT1 design_NN1 team_NN1 entirely_RR made_VVN up_RP of_IO women_NN2 ._. 
</s>
<s>
It_PPH1 was_VBDZ a_AT1 major_JJ exercise_NN1 in_II ergonomics_NN1 from_II the_AT perspective_NN1 of_IO a_AT1 female_JJ driver.Unlike_NNU other_JJ car_NN1 companies_NN2 which_DDQ advertise_VV0 that_CST they_PPHS2 made_VVD car_NN1 for_IF women_NN2 only_RR after_II modifying_VVG several_DA2 part_NN1 of_IO car_NN1 for_IF the_AT convenience_NN1 of_IO the_AT female_JJ customers_NN2 ,_, Volvo_NP1 made_VVD the_AT YCC_NN1 a_AT1 women-only_JJ car_NN1 from_II the_AT planning_NN1 stage_NN1 ._. 
</s>
<s>
Comfort_VV0 for_IF female_JJ drivers_NN2 is_VBZ an_AT1 area_NN1 traditional_JJ car_NN1 designers_NN2 often_RR ignore_VV0 ,_, according_II21 to_II22 Volvos_NP2 women_NN2 ._. 
</s>
<s>
They_PPHS2 have_VH0 implemented_VVN a_AT1 body_NN1 scanning_VVG system_NN1 which_DDQ enables_VVZ the_AT car_NN1 toautomatically_RR adjust_VV0 seats_NN2 ,_, mirrors_NN2 ,_, steering_VVG wheels_NN2 and_CC pedals_NN2 ._. 
</s>
<s>
And_CC for_IF women_NN2 with_IW ponytails_NN2 ,_, there_EX is_VBZ even_RR a_AT1 split_NN1 in_II the_AT middle_NN1 of_IO the_AT headrest_JJT ._. 
</s>
<s>
"_" It_PPH1 is_VBZ very_RG uncomfortable_JJ to_TO drive_VVI with_IW a_AT1 ponytail_NN1 ,_, "_" said_VVD Ms._NNB Christiansen_NP1 ,_, design_NN1 manager_NN1 of_IO Volvo_NP1 ._. 
</s>
<s>
Besides_RR ,_, it_PPH1 is_VBZ designed_VVN to_TO make_VVI it_PPH1 easy_JJ for_IF women_NN2 to_TO get_VVI in_RP and_CC out_II21 of_II22 the_AT car_NN1 ._. 
</s>
<s>
Entry_NN1 into_II the_AT car_NN1 was_VBDZ by_II the_AT means_NN of_IO two_MC gull-wing_JJ doors_NN2 on_II the_AT sides_NN2 ._. 
</s>
<s>
It_PPH1 also_RR had_VHD an_AT1 upwards_JJ opening_NN1 hatchback_NN1 door_NN1 giving_VVG access_NN1 to_II the_AT trunk_NN1 and_CC cargo_NN1 area_NN1 ._. 
</s>
<s>
All_DB three_MC doors_NN2 were_VBDR motorized_VVN for_IF a_AT1 sensor-based_JJ keyless_JJ entry_NN1 ._. 
</s>
<s>
Pressing_VVG on_II a_AT1 single_JJ button_NN1 on_II the_AT keychain_NN1 automatically_RR opened_VVD the_AT nearest_JJT door_NN1 ,_, making_VVG it_PPH1 easy_JJ for_IF somebody_PN1 holding_VVG bags_NN2 of_IO groceries_NN2 or_CC other_JJ sundries_NN2 to_TO get_VVI the_AT things_NN2 in_II the_AT car_NN1 without_IW putting_VVG anything_PN1 on_II the_AT pavement_NN1 or_CC the_AT sidewalk_NN1 ._. 
</s>
<s>
Furthermore_RR ,_, there_EX are_VBR many_DA2 functions_NN2 for_IF womens_NN2 convenience_NN1 ._. 
</s>
<s>
YCC_NP1 is_VBZ designed_VVN to_TO help_VVI women_NN2 usually_RR not_XX good_JJ at_II parking_NN1 park_NN1 with_IW ease_NN1 ._. 
</s>
<s>
Also_RR ,_, more_DAR choices_NN2 and_CC flexibility_NN1 exist_VV0 which_DDQ is_VBZ good_JJ news_NN1 to_II women_NN2 who_PNQS likes_VVZ sensuous_JJ things_NN2 ._. 
</s>
<s>
You_PPY can_VM radically_RR change_VVI the_AT look_NN1 of_IO the_AT car_NN1 interior_NN1 whenever_RRQV you_PPY feel_VV0 likeit_NN1 ._. 
</s>
<s>
There_EX are_VBR eight_MC exchangeable_JJ seat_NN1 pad_NN1 options_NN2 to_TO choose_VVI from_II ,_, everything_PN1 fromdark_VV0 brown_JJ leather_NN1 ,_, linen_NN1 and_CC wool_NN1 boucl_NN1 ,_, to_II a_AT1 shimmering_JJ yellow-green_JJ embroidered_JJ seat_NN1 pad_NN1 ._. 
</s>
<s>
As_CSA you_PPY can_VM see_VVI above_RL ,_, YCC_NP1 is_VBZ made_VVN thinking_VVG women_NN2 from_II first_MD to_TO last_VVI ._. 
</s>
<s>
In_II doing_VDG so_RR ,_, Volvo_NP1 could_VM captivate_VVI womens_NN2 heart_NN1 ._. 
</s>
<s>
What_DDQ makes_VVZ differences_NN2 ?_? 
</s>
<s>
In_II31 accordance_II32 with_II33 the_AT huge_JJ influence_NN1 of_IO women_NN2 in_II market_NN1 and_CC economics_NN1 ,_, it_PPH1 seems_VVZ that_DD1 attention_NN1 to_II women_NN2 will_VM increase_VVI more_DAR and_CC more_RRR ._. 
</s>
<s>
If_CS so_RR ,_, female_JJ consumers_NN2 ,_, how_RRQ differentare_VV0 they_PPHS2 really_RR ?_? 
</s>
<s>
In_BCL21 order_BCL22 to_TO understand_VVI them_PPHO2 deeply_RR ,_, lets_VVZ examine_VVI psychological_JJ ,_, physical_JJ ,_, and_CC social_JJ features_NN2 of_IO female_JJ consumers_NN2 ._. 
</s>
<s>
Psychological_JJ difference_NN1 If_CS the_AT women_NN2 are_VBR expressed_VVN in_II a_AT1 word_NN1 ,_, it_PPH1 would_VM be_VBI emotional_JJ animal_NN1 ._. 
</s>
<s>
Female_JJ consumers_NN2 are_VBR the_AT leading_JJ part_NN1 of_IO sensitive_JJ consumption_NN1 ._. 
</s>
<s>
Sensitivity_NN1 which_DDQ is_VBZ one_MC1 of_IO the_AT main_JJ keyword_NN1 of_IO 21_MC centuries_NNT2 is_VBZ in_II the_AT central_JJ part_NN1 of_IO their_APPGE consumption_NN1 ._. 
</s>
<s>
They_PPHS2 also_RR want_VV0 to_TO express_VVI their_APPGE emotions_NN2 in_II words_NN2 and_CC to_TO have_VHI connection_NN1 with_IW other_JJ people_NN ._. 
</s>
<s>
Women_NN2 like_VV0 to_TO share_VVI their_APPGE emotions_NN2 with_IW others_NN2 and_CC to_TO gain_VVI the_AT sympathy_NN1 ._. 
</s>
<s>
Thats_NN2 why_RRQ emotion-based_JJ advertising_NN1 has_VHZ a_AT1 powerful_JJ pull_NN1 for_IF women_NN2 ._. 
</s>
<s>
Its_APPGE important_JJ for_IF women_NN2 to_TO have_VHI a_AT1 shared_JJ moment_NN1 and_CC shared_JJ feelings_NN2 ._. 
</s>
<s>
When_CS it_PPH1 comes_VVZ to_II actuallymaking_VVG the_AT decision_NN1 ,_, women_NN2 generally_RR make_VV0 purchase_NN1 decisions_NN2 on_II a_AT1 more_RGR emotive_JJ level_NN1 ,_, whereas_CS men_NN2 go_VV0 more_RRR with_IW the_AT facts_NN2 and_CC data_NN ._. 
</s>
<s>
Womenprefer_VV0 a_AT1 narrative_NN1 ,_, a_AT1 story_NN1 with_IW the_AT faces_NN2 and_CC the_AT interaction_NN1 and_CC the_AT relationships_NN2 that_CST are_VBR occurring._NNU Physical_JJ difference_NN1 Depending_II21 on_II22 hormones_NN2 ,_, there_EX is_VBZ a_AT1 discrepancy_NN1 between_II women_NN2 and_CC men_NN2 ._. 
</s>
<s>
Testosterone_NN1 ,_, which_DDQ is_VBZ representative_JJ of_IO the_AT male_JJ hormone_NN1 ,_, deals_VVZ with_IW mens_NN2 characteristic_NN1 of_IO aggression_NN1 ,_, assertiveness_NN1 ,_, lust_NN1 for_IF control_NN1 ,_, competition_NN1 ,_, adventure_NN1 ._. 
</s>
<s>
There_EX are_VBR estrogen_NN1 and_CC progesterone_VV0 as_II a_AT1 representative_NN1 of_IO the_AT female_JJ hormone_NN1 ._. 
</s>
<s>
Estrogen_NN1 gives_VVZ satisfaction_NN1 to_II the_AT child_NN1 care_NN1 and_CC home_NN1 care_NN1 and_CC inhibits_VVZ the_AT induction_NN1 and_CC testosterone_NN1 ._. 
</s>
<s>
Progesterone_NN1 is_VBZ a_AT1 hormone_NN1 that_CST stimulates_VVZ the_AT maternal_JJ instinct_NN1 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, oxytocin_NN1 and_CC serotonin_NN1 are_VBR hormones_NN2 which_DDQ make_VV0 women_NN2 pursue_VVI a_AT1 relationship_NN1 with_IW others_NN2 Also_RR ,_, the_AT brain_NN1 function_NN1 of_IO women_NN2 and_CC men_NN2 can_VM tell_VVI the_AT difference_NN1 ._. 
</s>
<s>
Men_NN2 use_VV0 brain_NN1 locally_RR and_CC partially_RR so_CS21 that_CS22 it_PPH1 can_VM work_VVI intensively_RR ._. 
</s>
<s>
However_RR ,_, women_NN2 use_VV0 different_JJ areas_NN2 of_IO the_AT brain_NN1 ,_, so_CS the_AT ability_NN1 to_TO correlate_VVI is_VBZ outstanding_JJ ,_, so_CS men_NN2 have_VH0 detailed_VVN thinking_VVG and_CC women_NN2 have_VH0 integrative_JJ thinking_NN1 ._. 
</s>
<s>
Female_NN1 are_VBR more_RGR intuitive_JJ than_CSN men_NN2 because_CS they_PPHS2 have_VH0 rich_JJ corpus_NN1 compare_VV0 to_II men_NN2 ._. 
</s>
<s>
According_II21 to_II22 brain_NN1 scientists_NN2 ,_, mans_NN2 brain_NN1 has_VHZ more_RGR excellent_JJ ability_NN1 to_TO link_VVI back_RP and_CC forth_RR of_IO the_AT brain_NN1 ,_, so_RR to_TO rush_VVI forward_RL to_TO chase_VVI the_AT target_NN1 is_VBZ easy_JJ ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, they_PPHS2 are_VBR good_JJ at_II targeting_VVG to_TO hunt_VVI and_CC concentrate_VVI on_II it_PPH1 ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 ,_, woman_NN1 has_VHZ developed_VVN ability_NN1 to_TO connect_VVI the_AT sides_NN2 of_IO their_APPGE brain_NN1 and_CC it_PPH1 is_VBZ good_JJ structure_NN1 to_TO analyze_VVI circumstance_NN1 comprehensively_RR and_CC apply_VVI ._. 
</s>
<s>
While_CS men_NN2 do_VD0 step-thinking_JJ to_TO deduce_VVI ,_, women_NN2 do_VD0 web-thinking_JJ not_XX thinking_VVG straightly_RR but_CCB going_VVG and_CC coming_VVG here_RL and_CC there_RL ._. 
</s>
<s>
Men_NN2 tend_VV0 to_TO be_VBI single-minded_JJ and_CC focused_VVD ,_, whereas_CS women_NN2 tend_VV0 to_TO be_VBI multi-minded_JJ and_CC integrated_JJ ._. 
</s>
<s>
Men_NN2 like_VV0 to_II structure_NN1 their_APPGE lives_NN2 linearly_RR :_: first_MD things_NN2 first_MD ,_, finish_VV0 one_MC1 thing_NN1 before_CS you_PPY go_VV0 on_RP to_II the_AT next_MD ,_, get_VV0 the_AT most_RGT important_JJ things_NN2 done_VDN before_CS you_PPY tackle_VV0 anything_PN1 lower_JJR on_II the_AT list_NN1 ._. 
</s>
<s>
Women_NN2 pursue_VV0 several_DA2 tasks_NN2 simultaneously_RR ._. 
</s>
<s>
In_II31 addition_II32 to_II33 that_DD1 ,_, women_NN2 have_VH0 a_AT1 keen_JJ sense_NN1 speaking_NN1 of_IO body_NN1 structure_NN1 ._. 
</s>
<s>
Commonly_RR it_PPH1 is_VBZ believed_VVN that_CST women_NN2 have_VH0 more_RRR developed_VVN five_MC senses_NN2 ._. 
</s>
<s>
Even_CS21 if_CS22 they_PPHS2 buy_VV0 a_AT1 small_JJ item_NN1 ,_, female_JJ consumers_NN2 have_VH0 a_AT1 strong_JJ desire_NN1 to_TO experience_VVI and_CC check_VVI with_IW their_APPGE five_MC senses_NN2 such_II21 as_II22 seeing_VVG ,_, hearing_VVG ,_, and_CC touching_JJ ._. 
</s>
<s>
It_PPH1 is_VBZ generalized_JJ to_TO equip_VVI with_IW testers_NN2 which_DDQ make_VV0 people_NN experience_VVI products_NN2 directly_RR in_II the_AT stores_NN2 whose_DDQGE main_JJ consumers_NN2 are_VBR women_NN2 such_II21 as_II22 perfumes_NN2 and_CC cosmetics_NN2 ._. 
</s>
<s>
Recently_RR an_AT1 eye-catching_JJ color_NN1 and_CC fragrance_NN1 marketing_NN1 is_VBZ also_RR a_AT1 way_NN1 to_TO stimulate_VVI their_APPGE senses_NN2 ,_, evoking_VVG the_AT desire_NN1 to_TO purchase_VVI ._. 
</s>
<s>
Social_JJ difference_NN1 Compared_VVN to_II male_JJ consumers_NN2 ,_, female_JJ consumers_NN2 have_VH0 excellent_JJ socialization_NN1 and_CC friendly_JJ communication_NN1 skills_NN2 ._. 
</s>
<s>
Women_NN2 have_VH0 characteristic_NN1 which_DDQ is_VBZ to_TO love_VVI to_TO come_VVI together_RL and_CC talk_VVI about_II things_NN2 and_CC it_PPH1 forms_VVZ Word_NN1 of_IO Mouth_NN1 which_DDQ has_VHZ huge_JJ influence_NN1 on_II purchasing_VVG decision_NN1 ._. 
</s>
<s>
Difference_NN1 in_II purchasing_VVG Men_NN2 prefer_VV0 to_TO focus_VVI in_RP on_II the_AT important_JJ things_NN2 -namely_REX the_AT top_JJ few_DA2 items_NN2 on_II theirlist_NN1 of_IO criteria_NN2 ._. 
</s>
<s>
Once_CS they_PPHS2 find_VV0 something_PN1 that_CST meets_VVZ all_DB the_AT key_JJ criteria_NN2 ,_, theyare_VV0 ready_JJ to_TO move_VVI ahead_RL on_II a_AT1 decision_NN1 ._. 
</s>
<s>
Men_NN2 define_VV0 the_AT productor_NN1 service_NN1 they_PPHS2 want_VV0 in_II31 terms_II32 of_II33 the_AT features_NN2 that_CST are_VBR most_RGT important_JJ to_II them_PPHO2 ,_, formulating_VVG a_AT1 short_JJ ,_, focused_VVD list_NN1 of_IO key_JJ decision_NN1 criteria_NN2 and_CC then_RT finding_VVG a_AT1 solution_NN1 that_CST meets_VVZ those_DD2 criteria_NN2 ._. 
</s>
<s>
When_CS they_PPHS2 find_VV0 the_AT solution_NN1 ,_, they_PPHS2 buythey_NN1 are_VBR done_VDN ._. 
</s>
<s>
Women_NN2 ,_, on_II the_AT other_JJ hand_NN1 ,_, start_VV0 with_IW a_AT1 more_RGR generalized_JJ sense_NN1 of_IO the_AT situation_NN1 they_PPHS2 want_VV0 to_TO address_VVI ,_, factor_NN1 in_II additional_JJ considerations_NN2 as_CSA they_PPHS2 move_VV0 through_II the_AT decision_NN1 process_NN1 ,_, and_CC keep_VV0 exploring_VVG options_NN2 until_CS they_PPHS2 are_VBR satisfied_JJ that_CST they_PPHS2 have_VH0 found_VVN not_XX just_RR a_AT1 workable_JJ solution_NN1 ,_, but_CCB the_AT best_JJT possible_JJ answer_NN1 ._. 
</s>
<s>
In_II shorthand_NN1 :_: men_NN2 are_VBR buyers_NN2 ,_, whereas_CS women_NN2 are_VBR shoppers_NN2 ._. 
</s>
<s>
According_II21 to_II22 research_NN1 ,_, 61_MC percent_NNU of_IO women_NN2 say_VV0 that_CST when_CS making_VVG a_AT1 clothing_NN1 purchase_NN1 they_PPHS2 visit_VV0 several_DA2 different_JJ stores_NN2 before_II deciding_VVG what_DDQ to_TO buy_VVI ._. 
</s>
<s>
When_CS embarking_VVG on_II a_AT1 new_JJ purchase_NN1 ,_, men_NN2 go_VV0 looking_VVG for_IF a_AT1 good_JJ solution_NN1 ,_, whereas_CS women_NN2 set_VV0 out_RP to_TO find_VVI the_AT Perfect_JJ Answer_NN1 ._. 
</s>
<s>
When_RRQ buy_VV0 something_PN1 men_NN2 discard_VV0 unimportant_JJ criteria_NN2 ,_, but_CCB women_NN2 are_VBR more_RGR likely_JJ to_TO be_VBI adding_VVG them_PPHO2 ._. 
</s>
<s>
In_RR21 short_RR22 ,_, the_AT differences_NN2 between_II men_NN2 and_CC women_NN2 come_VV0 from_II their_APPGE psychological_JJ ,_, physical_JJ ,_, and_CC social_JJ features_NN2 and_CC it_PPH1 makes_VVZ them_PPHO2 have_VHI different_JJ behavior_NN1 and_CC reaction_NN1 in_II decision_NN1 making_VVG and_CC purchasing_NN1 ._. 
</s>
<s>
The_AT key_NN1 to_II attracting_JJ women_NN2 From_II previous_JJ chapters_NN2 ,_, it_PPH1 can_VM be_VBI concluded_VVN that_CST understanding_VVG their_APPGE sensitivity_NN1 ,_, physical_JJ features_NN2 ,_, and_CC social_JJ inclination_NN1 is_VBZ crucial_JJ in_BCL21 order_BCL22 to_TO approach_VVI and_CC attract_VVI female_JJ consumers_NN2 ._. 
</s>
<s>
Lets_VVZ see_VVI what_DDQ marketers_NN2 should_VM do_VDI to_II with_IW these_DD2 findings_NN2 ._. 
</s>
<s>
Forget_VV0 about_II stereotyped_JJ image_NN1 of_IO women_NN2 ._. 
</s>
<s>
Marketers_NN2 should_VM notice_VVI that_CST women_NN2 are_VBR not_XX women_NN2 in_II the_AT past_NN1 any_DD more_DAR ._. 
</s>
<s>
They_PPHS2 start_VV0 to_TO enjoy_VVI rock-climbing_NN1 and_CC off-road_JJ driving_JJ ride_NN1 Harley_NP1 Davidson_NP1 ._. 
</s>
<s>
To_TO discard_VVI old_JJ prejudices_NN2 and_CC see_VVI things_NN2 from_II a_AT1 new_JJ perspective_NN1 is_VBZ needed_VVN ._. 
</s>
<s>
Lets_VVZ talk_NN1 about_II Nike_NP1 which_DDQ launched_VVD women_NN2 sports_NN2 apparel_NN1 successfully_RR ._. 
</s>
<s>
Nike_NN1 is_VBZ gaining_VVG sensational_JJ popularity_NN1 from_II female_JJ customer_NN1 by_II showing_VVG comfortable_JJ ,_, simple_JJ ,_, and_CC active_JJ sportswear_NN1 for_IF women_NN2 ._. 
</s>
<s>
In_II the_AT 21_MC centuries_NNT2 ,_, sports_NN2 and_CC fitness_NN1 trends_NN2 were_VBDR led_VVN by_II women_NN2 not_XX men_NN2 because_II21 of_II22 the_AT popularity_NN1 of_IO yoga_NN1 and_CC various_JJ dancing_NN1 ._. 
</s>
<s>
According_II21 to_II22 this_DD1 movement_NN1 ,_, Nike_NP1 could_VM be_VBI successful_JJ by_II changing_VVG their_APPGE concept_NN1 of_IO sports_NN2 as_II what_DDQ women_NN2 do_VD0 and_CC actively_RR marketing_VVG to_II women_NN2 ._. 
</s>
<s>
This_DD1 example_NN1 shows_VVZ that_CST to_TO break_VVI the_AT prejudice_NN1 such_II21 as_II22 women_NN2 ?_? sports_VVZ is_VBZ important_JJ ._. 
</s>
<s>
Womens_NP1 sensitivity_NN1 should_VM be_VBI satisfied_VVN ._. 
</s>
<s>
There_EX are_VBR two_MC way_NN1 to_TO do_VDI that_DD1 ._. 
</s>
<s>
Make_VV0 them_PPHO2 princess_NN1 or_CC emotionally_RR satisfied_JJ ._. 
</s>
<s>
Women_NN2 consumers_NN2 have_VH0 a_AT1 strong_JJ desire_NN1 to_TO be_VBI treated_VVN ._. 
</s>
<s>
In_RR21 particular_RR22 ,_, the_AT busy_JJ housewives_NN2 who_PNQS are_VBR sick_JJ and_CC tired_JJ of_IO the_AT things_NN2 with_IW all_DB the_AT households_NN2 have_VH0 stronger_JJR desire_NN1 ._. 
</s>
<s>
If_CS female_JJ consumers_NN2 feel_VV0 that_CST they_PPHS2 become_VV0 a_AT1 princess_NN1 when_CS entering_VVG the_AT shop_NN1 or_CC using_VVG products_NN2 ,_, that_DD1 would_VM be_VBI successful_JJ ._. 
</s>
<s>
The_AT point_NN1 is_VBZ that_DD1 approach_NN1 women_NN2 with_IW Concierge_NN1 marketing_NN1 from_II the_AT eye_NN1 level_NN1 of_IO women_NN2 consumers_NN2 to_TO provide_VVI what_DDQ they_PPHS2 want_VV0 ._. 
</s>
<s>
Using_VVG a_AT1 small_JJ space_NN1 for_IF women-only_JJ shelter_NN1 or_CC powder_NN1 room_NN1 can_VM be_VBI an_AT1 example_NN1 ._. 
</s>
<s>
In_II31 addition_II32 to_II33 that_DD1 ,_, emotional_JJ marketing_NN1 should_VM be_VBI used_JJ to_II women_NN2 ._. 
</s>
<s>
The_AT importance_NN1 of_IO emotion_NN1 in_II the_AT latest_JJT marketing_NN1 is_VBZ well-known_JJ ._. 
</s>
<s>
For_REX21 example_REX22 Starbucks_NP1 coffee_NN1 shops_NN2 could_VM achieve_VVI great_JJ success_NN1 with_IW their_APPGE own_DA emotional_JJ marketing_NN1 ._. 
</s>
<s>
They_PPHS2 stayed_VVD away_II21 from_II22 coffee_NN1 sales_NN and_CC approach_NN1 consumer_NN1 with_IW relaxed_JJ atmosphere_NN1 and_CC unique_JJ Starbucks_NN2 culture_NN1 ._. 
</s>
<s>
As_CSA seen_VVN in_II this_DD1 example_NN1 ,_, the_AT shop_NN1 should_VM be_VBI a_AT1 place_NN1 that_CST can_VM help_VVI consumer_NN1 to_TO better_RRR understand_VVI the_AT products_NN2 and_CC feel_VV0 friendly_JJ with_IW it_PPH1 so_CS21 that_CS22 it_PPH1 can_VM stimulate_VVI consumers_NN2 '_GE hidden_JJ emotions_NN2 ._. 
</s>
<s>
In_RR21 particular_RR22 ,_, since_CS the_AT female_JJ consumers_NN2 see_VV0 the_AT things_NN2 in_II the_AT peripheral_JJ vision_NN1 ,_, they_PPHS2 are_VBR influenced_VVN by_II the_AT atmosphere_NN1 and_CC customer_NN1 service_NN1 ._. 
</s>
<s>
Make_VV0 busy_JJ women_NN2 less_RGR busy_JJ ._. 
</s>
<s>
Of_RR21 course_RR22 men_NN2 are_VBR also_RR busy_JJ ,_, but_CCB recently_RR womens_VVZ lives_NN2 are_VBR even_RR more_RGR complex_JJ than_CSN that_DD1 of_IO men_NN2 according_II21 to_II22 the_AT increased_JJ social_JJ participation_NN1 of_IO women_NN2 ._. 
</s>
<s>
As_CSA more_DAR and_CC more_DAR women_NN2 are_VBR entering_VVG the_AT workforce_NN1 ,_, she_PPHS1 has_VHZ to_TO wear_VVI many_DA2 hats_NN2 ._. 
</s>
<s>
Especially_RR housewives_NN2 who_PNQS have_VH0 to_TO go_VVI to_TO work_VVI also_RR have_VH0 to_TO do_VDI shopping_NN1 ,_, cooking_VVG ,_, cleaning_VVG ,_, laundry_NN1 ,_, childcare_NN1 ,_, and_CC taking_VVG care_NN1 of_IO all_DB other_JJ things_NN2 for_IF family_NN1 ._. 
</s>
<s>
As_II a_AT1 result_NN1 ,_, they_PPHS2 have_VH0 trouble_NN1 in_II doing_VDG so_RR ._. 
</s>
<s>
Thus_RR ,_, companies_NN2 can_VM get_VVI female_JJ consumers_NN2 purchasing_NN1 power_NN1 by_II providing_VVG programs_NN2 or_CC products_NN2 that_CST can_VM help_VVI women_NN2 deal_VVI with_IW their_APPGE complex_JJ tasks_NN2 ._. 
</s>
<s>
Also_RR ,_, since_CS they_PPHS2 live_VV0 in_II a_AT1 busy_JJ and_CC complex_JJ life_NN1 ,_, companies_NN2 should_VM not_XX sit_VVI and_CC wait_VVI ._. 
</s>
<s>
That_REX21 is_REX22 ,_, they_PPHS2 should_VM jump_VVI directly_RR to_II womens_NN2 life_NN1 in_BCL21 order_BCL22 to_TO make_VVI it_PPH1 easier_JJR for_IF them_PPHO2 to_TO save_VVI time_NNT1 and_CC energy_NN1 and_CC feel_VVI convenient_JJ ._. 
</s>
<s>
In_II doing_VDG so_RR ,_, it_PPH1 is_VBZ possible_JJ to_TO get_VVI closer_JJR to_TO busy_VVI women_NN2 and_CC get_VVI loyalty_NN1 from_II them_PPHO2 ._. 
</s>
<s>
Use_VV0 word-of-mouth_JJ tactics_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ essential_JJ to_TO take_VVI advantage_NN1 of_IO womens_NN2 word-of-mouth_JJ effect_NN1 ._. 
</s>
<s>
Business_NN1 can_VM be_VBI successful_JJ by_II using_VVG this_DD1 tactics_VVZ ._. 
</s>
<s>
According_II21 to_II22 Faith_NN1 popcorn_NN1 ,_, a_AT1 futurologist_NN1 ,_, women_NN2 instinctively_RR liked_VVN to_TO be_VBI connected_VVN each_PPX221 other_PPX222 ._. 
</s>
<s>
There_EX are_VBR lots_PN of_IO information_NN1 and_CC recommendation_NN1 about_II what_DDQ they_PPHS2 have_VH0 and_CC buy_VV0 among_II women_NN2 who_PNQS connected_VVD each_PPX221 other_PPX222 ._. 
</s>
<s>
If_CS marketers_NN2 make_VV0 the_AT best_JJT use_NN1 of_IO these_DD2 women_NN2 characteristics_NN2 ,_, therefore_RR ,_, it_PPH1 would_VM be_VBI easier_JJR to_TO attract_VVI women_NN2 ._. 
</s>
<s>
Companies_NN2 can_VM build_VVI high_JJ confidence_NN1 relationship_NN1 between_II company_NN1 and_CC customers_NN2 by_II establishing_VVG community_NN1 and_CC relationship_NN1 among_II female_JJ consumers_NN2 who_PNQS can_VM share_VVI their_APPGE experience_NN1 about_II service_NN1 and_CC products_NN2 and_CC by_II connecting_VVG them_PPHO2 with_IW company_NN1 ._. 
</s>
<s>
Until_II now_RT ,_, this_DD1 paper_NN1 focused_VVN on_II characteristics_NN2 of_IO female_JJ consumers_NN2 who_PNQS are_VBR getting_VVG more_RRR and_CC more_DAR attention_NN1 recently_RR and_CC answered_VVN to_II how_RRQ to_II marketing_NN1 to_II them_PPHO2 ._. 
</s>
<s>
Companies_NN2 should_VM understand_VVI the_AT difference_NN1 between_II men_NN2 and_CC women_NN2 and_CC apply_VV0 it_PPH1 to_II their_APPGE marketing_NN1 ._. 
</s>
<s>
In_II doing_VDG so_RR ,_, they_PPHS2 can_VM approach_VVI and_CC attract_VVI female_JJ consumers_NN2 ._. 
</s>
