<s>
1_MC1 Introduction_NN1 The_AT financial_JJ crisis_NN1 that_CST took_VVD place_NN1 in_II years_NNT2 2007-2009_MCMC raised_VVD a_AT1 need_NN1 to_TO review_VVI whether_CSW and_CC how_RGQ financial_JJ regulation_NN1 should_VM be_VBI reformed_VVN ._. 
</s>
<s>
The_AT formulated_JJ regulation_NN1 solution_NN1 ,_, in_II the_AT framework_NN1 of_IO Basel_NP1 III_MC ,_, has_VHZ spurred_VVN a_AT1 vivid_JJ academic_JJ discussion_NN1 as_II the_AT paradigm_NN1 of_IO deregulation_NN1 of_IO financial_JJ markets_NN2 seems_VVZ to_TO be_VBI in_II a_AT1 turning_JJ point_NN1 ._. 
</s>
<s>
While_CS before_CS the_AT crisis_NN1 there_EX were_VBDR some_DD alarmist_NN1 voices_NN2 demanding_VVG more_RGR comprehensive_JJ supervision_NN1 and_CC regulation_NN1 ,_, now_RT there_EX is_VBZ hardly_RR anyone_PN1 saying_VVG that_DD1 financial_JJ regulation_NN1 structure_NN1 does_VDZ not_XX need_VVI a_AT1 reform_NN1 ._. 
</s>
<s>
However_RR ,_, the_AT consensus_NN1 has_VHZ not_XX been_VBN reached_VVN in_II the_AT level_NN1 of_IO regulation_NN1 and_CC between_II the_AT different_JJ regulation_NN1 approaches_NN2 ._. 
</s>
<s>
Basel_VV0 Accords_NN2 ,_, which_DDQ lay_VVD out_RP the_AT international_JJ standards_NN2 for_IF banking_NN1 regulation_NN1 ,_, have_VH0 previously_RR focused_VVN mainly_RR to_II capital_NN1 regulation_NN1 ._. 
</s>
<s>
The_AT new_JJ accord_NN1 ,_, Basel_NP1 III_MC ,_, introduces_VVZ new_JJ liquidity_NN1 requirements_NN2 to_TO fix_VVI the_AT serious_JJ inadequacies_NN2 exposed_VVN by_II the_AT recent_JJ crisis_NN1 ._. 
</s>
<s>
The_AT effect_NN1 of_IO the_AT liquidity_NN1 requirements_NN2 have_VH0 been_VBN less_RRR researched_VVN ._. 
</s>
<s>
The_AT question_NN1 arises_VVZ what_DDQ will_VM these_DD2 new_JJ liquidity_NN1 requirements_NN2 add_VV0 to_II the_AT capital_NN1 requirements_NN2 and_CC will_VM they_PPHS2 solve_VVI the_AT deficiencies_NN2 present_VV0 in_II the_AT banking_NN1 system_NN1 ._. 
</s>
<s>
The_AT paper_NN1 reviews_VVZ the_AT dominant_JJ paradigm_NN1 of_IO banking_NN1 regulation_NN1 that_CST has_VHZ stressed_VVN the_AT capital_NN1 requirements_NN2 as_II a_AT1 tool_NN1 to_TO keep_VVI the_AT banks_NN2 afloat_JJ ._. 
</s>
<s>
The_AT implications_NN2 of_IO the_AT recent_JJ crisis_NN1 will_VM be_VBI studied_VVN and_CC an_AT1 overview_NN1 made_VVN to_II the_AT new_JJ Basel_NP1 III_MC regulation_NN1 ._. 
</s>
<s>
The_AT new_JJ liquidity_NN1 rules_NN2 will_VM presented_VVD and_CC a_AT1 discussion_NN1 of_IO their_APPGE effect_NN1 will_VM be_VBI carried_VVN out_RP ._. 
</s>
<s>
The_AT exact_JJ projection_NN1 of_IO the_AT effectiveness_NN1 of_IO the_AT new_JJ the_AT Banking_NN1 regulation_NN1 package_NN1 is_VBZ of_RR21 course_RR22 extremely_RR difficult_JJ -_- if_CS not_XX impossible_JJ ._. 
</s>
<s>
In_II this_DD1 paper_NN1 I_PPIS1 will_VM conclude_VVI that_CST the_AT desired_JJ stability_NN1 will_VM come_VVI with_IW a_AT1 cost_NN1 ._. 
</s>
<s>
The_AT more_RGR burdensome_JJ regulation_NN1 will_VM probably_RR slower_RRR the_AT economic_JJ growth_NN1 ._. 
</s>
<s>
The_AT remainder_NN1 of_IO this_DD1 paper_NN1 has_VHZ five_MC sections_NN2 ._. 
</s>
<s>
The_AT first_MD will_VM explain_VVI the_AT rational_JJ for_IF the_AT banking_NN1 regulation_NN1 ._. 
</s>
<s>
The_AT second_NNT1 will_VM give_VVI background_NN1 information_NN1 about_II the_AT framework_NN1 of_IO Basel_NP1 Accords_VVZ ._. 
</s>
<s>
The_AT third_MD will_VM evaluate_VVI the_AT capital_NN1 adequacy_NN1 regulation_NN1 ._. 
</s>
<s>
The_AT fourth_MD will_VM introduce_VVI the_AT new_JJ liquidity_NN1 requirements_NN2 and_CC the_AT fifth_MD will_VM discuss_VVI their_APPGE effects_NN2 ._. 
</s>
<s>
2_MC Prudential_JJ regulation_NN1 of_IO banks_NN2 2.1_MC Rationale_NN1 for_IF regulation_NN1 The_AT financial_JJ system_NN1 is_VBZ crucial_JJ to_II the_AT health_NN1 of_IO the_AT economy_NN1 because_CS it_PPH1 performs_VVZ the_AT essential_JJ function_NN1 in_II an_AT1 economy_NN1 of_IO channeling_VVG funds_NN2 from_II savings_NN2 to_II those_DD2 individuals_NN2 or_CC firms_NN2 that_CST have_VH0 productive_JJ investment_NN1 opportunities_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ possible_JJ to_TO satisfy_VVI the_AT concurrent_JJ needs_NN2 of_IO funding_NN1 and_CC investment_NN1 activities_NN2 only_RR through_II financial_JJ markets_NN2 and_CC the_AT supporting_JJ institutions_NN2 ,_, which_DDQ together_RL form_VV0 the_AT financial_JJ system_NN1 ._. 
</s>
<s>
Bank_NN1 acts_VVZ as_CSA supervisor_NN1 of_IO debtors_NN2 and_CC risk_NN1 assessor_NN1 of_IO their_APPGE credit_NN1 risk_NN1 ._. 
</s>
<s>
Although_CS the_AT banks_NN2 hold_VV0 natural_JJ advantages_NN2 of_IO collecting_VVG information_NN1 that_CST come_VV0 from_II the_AT benefit_NN1 of_IO the_AT large_JJ scale_NN1 operation_NN1 the_AT problem_NN1 of_IO instability_NN1 is_VBZ inherent_JJ to_II the_AT nature_NN1 of_IO banking_NN1 activity_NN1 ._. 
</s>
<s>
As_CSA it_PPH1 has_VHZ been_VBN learned_VVN from_II the_AT all_DB pervasive_JJ effects_NN2 that_CST financial_JJ market_NN1 failures_NN2 can_VM have_VHI ,_, governments_NN2 have_VH0 a_AT1 great_JJ incentive_NN1 to_TO control_VVI the_AT soundness_NN1 of_IO banks_NN2 ._. 
</s>
<s>
With_IW prudential_JJ supervision_NN1 governments_NN2 regulate_VV0 and_CC monitor_VV0 the_AT banking_NN1 system_NN1 to_TO ensure_VVI its_APPGE safety_NN1 and_CC soundness_NN1 ._. 
</s>
<s>
The_AT need_NN1 for_IF banking_NN1 regulation_NN1 and_CC supervision_NN1 stems_VVZ from_II asymmetric_JJ information_NN1 and_CC the_AT harmful_JJ side-effects_NN2 that_CST come_VV0 with_IW the_AT government_NN1 created_VVD safety_NN1 nets_NN2 ._. 
</s>
<s>
Serious_JJ downsides_NN2 of_IO the_AT government_NN1 safety_NN1 net_NN1 arise_VV0 from_II moral_JJ hazard_NN1 and_CC adverse_JJ selection_NN1 ._. 
</s>
<s>
Because_CS depositors_NN2 are_VBR aware_JJ that_CST with_IW a_AT1 safety_NN1 net_NN1 they_PPHS2 will_VM not_XX suffer_VVI losses_NN2 if_CS a_AT1 bank_NN1 fails_VVZ ,_, they_PPHS2 do_VD0 not_XX impose_VVI market_NN1 discipline_NN1 on_II banks_NN2 by_II withdrawing_VVG deposits_NN2 when_CS they_PPHS2 suspect_VV0 that_CST the_AT bank_NN1 is_VBZ taking_VVG on_RP too_RG much_DA1 risk_NN1 ._. 
</s>
<s>
As_II a_AT1 consequence_NN1 ,_, banks_NN2 with_IW a_AT1 government_NN1 safety_NN1 net_NN1 have_VH0 an_AT1 incentive_NN1 to_TO take_VVI on_RP greater_JJR risks_NN2 than_CSN they_PPHS2 otherwise_RR would_VM ._. 
</s>
<s>
The_AT purpose_NN1 of_IO prudential_JJ supervision_NN1 is_VBZ to_TO limit_VVI the_AT strong_JJ incentive_NN1 to_TO take_VVI on_RP excessive_JJ risks_NN2 ._. 
</s>
<s>
Otherwise_RR the_AT safety_NN1 net_NN1 may_VM do_VDI more_DAR harm_NN1 than_CSN good_JJ and_CC promote_VV0 banking_NN1 crisis_NN1 rather_CS21 than_CS22 prevent_VVI them_PPHO2 ._. 
</s>
<s>
Prudential_JJ supervision_NN1 is_VBZ comprised_VVN of_IO government_NN1 regulations_NN2 to_TO reduce_VVI risk_NN1 taking_NN1 and_CC monitoring_NN1 of_IO the_AT banks_NN2 to_TO see_VVI that_CST they_PPHS2 are_VBR complying_VVG with_IW these_DD2 regulations_NN2 ._. 
</s>
<s>
2.2_MC The_AT Basel_NP1 framework_NN1 Basel_NP1 Committee_NN1 on_II Banking_NN1 Supervision_NN1 (_( BCBS_NP1 )_) ,_, founded_VVN in_II the_AT year_NNT1 1974_MC by_II central-bank_JJ governors_NN2 of_IO G-10_FO ,_, has_VHZ established_VVN itself_PPX1 as_II the_AT forum_NN1 where_CS international_JJ standards_NN2 for_IF banking_NN1 supervision_NN1 are_VBR formulated_VVN ._. 
</s>
<s>
Interestingly_RR it_PPH1 possesses_VVZ no_AT statutory_JJ authority_NN1 and_CC issues_VVZ no_AT binding_JJ regulation_NN1 and_CC is_VBZ not_XX considered_VVN as_CSA classical_JJ multilateral_JJ organization_NN1 ,_, because_CS it_PPH1 operates_VVZ outside_II international_JJ law_NN1 ._. 
</s>
<s>
Acting_VVG as_II an_AT1 informal_JJ forum_NN1 to_TO find_VVI policy_NN1 solutions_NN2 and_CC to_TO promulgate_VVI standards_NN2 the_AT main_JJ task_NN1 of_IO the_AT BCBS_NP1 is_VBZ to_TO prevent_VVI risk_NN1 of_IO bank_NN1 failures_NN2 and_CC the_AT resulting_JJ risk_NN1 for_IF financial_JJ systems_NN2 from_II possible_JJ bank_NN1 crises_NN2 ._. 
</s>
<s>
The_AT BCBS_NP1 has_VHZ produced_VVN various_JJ standards_NN2 regarding_II different_JJ aspects_NN2 of_IO banking_NN1 supervision_NN1 ._. 
</s>
<s>
The_AT most_RGT important_JJ has_VHZ been_VBN the_AT capital_NN1 adequacy_NN1 standard_NN1 issued_VVN in_II 1988_MC (_( Basel_NP1 I_ZZ1 )_) that_CST imposed_VVD the_AT minimum_JJ ratio_NN1 of_IO capital_NN1 to_II risk-weighted_JJ assets_NN2 of_IO 8_MC percent_NNU ._. 
</s>
<s>
This_DD1 standard_NN1 specified_VVD the_AT minimum_JJ amount_NN1 of_IO capital_NN1 reserves_VVZ that_CST any_DD internationally_RR active_JJ bank_NN1 needed_VVD to_TO retain_VVI in_BCL21 order_BCL22 to_TO be_VBI safe_JJ from_II financial_JJ and_CC operational_JJ risks_NN2 that_CST banks_NN2 face_VV0 ._. 
</s>
<s>
The_AT process_NN1 for_IF revised_JJ structure_NN1 started_VVD in_II year_NNT1 1999_MC and_CC the_AT outcome_NN1 New_JJ Capital_NN1 Framework_NN1 was_VBDZ issued_VVN by_II the_AT BCBS_NP1 in_II year_NNT1 2004_MC (_( Basel_NP1 II_MC )_) ._. 
</s>
<s>
Basel_VV0 II_MC changed_VVD Basel_NP1 I_ZZ1 by_II expanding_VVG the_AT capital_NN1 requirement_NN1 rules_NN2 and_CC by_II further_RRR introducing_VVG internal_JJ risk_NN1 assessment_NN1 processes_NN2 ._. 
</s>
<s>
As_II a_AT1 result_NN1 of_IO recent_JJ financial_JJ crisis_NN1 BCBS_NP1 has_VHZ taken_VVN rapid_JJ steps_NN2 to_TO revise_VVI the_AT framework_NN1 again_RT ._. 
</s>
<s>
New_JJ capital_NN1 adequacy_NN1 and_CC liquidity_NN1 requirements_NN2 ,_, denoted_VVD Basel_NP1 III_MC ,_, were_VBDR issued_VVN in_II December_NPM1 2010._MC 2.3_MC Capital_JJ adequacy_NN1 requirement_NN1 Capital_NN1 functions_NN2 as_II a_AT1 buffer_NN1 that_CST absorbs_VVZ failed_JJ investments_NN2 to_TO protect_VVI depositors_NN2 and_CC to_TO keep_VVI the_AT bank_NN1 afloat_JJ ._. 
</s>
<s>
Shareholders_NN2 suffer_VV0 losses_NN2 when_RRQ capital_NN1 is_VBZ consumed_VVN to_TO cover_VVI declined_VVN assets_NN2 ,_, but_CCB this_DD1 is_VBZ considered_VVN a_AT1 private_JJ matter_NN1 ,_, whereas_CS there_EX are_VBR strong_JJ public_JJ policy_NN1 reasons_NN2 to_TO protect_VVI depositors_NN2 ._. 
</s>
<s>
Capital_NN1 requirements_NN2 had_VHD arisen_VVN over_II the_AT time_NNT1 to_II a_AT1 central_JJ position_NN1 in_II the_AT prudential_JJ regulation_NN1 due_II21 to_II22 changes_NN2 in_II banking_NN1 environment_NN1 even_RR before_II the_AT Basel_NP1 I._NP1 The_AT dominant_JJ reliance_NN1 on_II capital_NN1 requirements_NN2 has_VHZ only_RR intensified_VVN through_II the_AT adoption_NN1 of_IO Basel_NP1 Accords_NN2 and_CC is_VBZ considered_VVN broadly_RR accepted_JJ approach_NN1 to_II prudential_JJ regulation_NN1 ._. 
</s>
<s>
Although_CS ,_, the_AT various_JJ factors_NN2 that_CST expose_VV0 banks_NN2 to_II instability_NN1 have_VH0 been_VBN historically_RR regulated_VVN in_II many_DA2 different_JJ ways_NN2 ,_, capital_NN1 adequacy_NN1 regulation_NN1 has_VHZ become_VVN increasingly_RR central_JJ to_II prudential_JJ regulation_NN1 ._. 
</s>
<s>
Tarullo_NN1 reflects_VVZ that_CST this_DD1 trend_NN1 has_VHZ created_VVN a_AT1 closer_JJR conceptual_JJ link_NN1 between_II one_MC1 important_JJ rationale_NN1 for_IF bank_NN1 regulation_NN1 and_CC the_AT dominant_JJ regulatory_JJ paradigm_NN1 ._. 
</s>
<s>
The_AT question_NN1 of_IO how_RGQ much_DA1 capital_NN1 banks_NN2 should_VM be_VBI required_VVN to_TO hold_VVI is_VBZ at_RR21 least_RR22 equally_RR important_JJ but_CCB perhaps_RR a_RR21 lot_RR22 more_RGR difficult_JJ than_CSN the_AT question_NN1 whether_CSW banks_NN2 should_VM be_VBI subjects_NN2 to_II capital_NN1 requirements_NN2 at_RR21 all_RR22 ._. 
</s>
<s>
The_AT setting_NN1 of_IO desired_JJ level_NN1 of_IO capital_NN1 requirement_NN1 involves_VVZ a_AT1 trade-off_NN1 between_II the_AT cost_NN1 of_IO capital_NN1 to_II firms_NN2 and_CC individuals_NN2 and_CC the_AT possibility_NN1 of_IO harmful_JJ bank_NN1 failures_NN2 ._. 
</s>
<s>
The_AT related_JJ contributing_JJ factors_NN2 and_CC probabilities_NN2 are_VBR very_RG hard_JJ to_TO quantify_VVI which_DDQ makes_VVZ it_PPH1 clear_JJ that_CST no_AT financial_JJ model_NN1 can_VM provide_VVI unquestionable_JJ formula_NN1 for_IF capital_NN1 requirements_NN2 ._. 
</s>
<s>
If_CS risks_NN2 that_CST the_AT banks_NN2 face_VV0 can_VM be_VBI quantified_VVN then_RT the_AT regulators_NN2 can_VM better_RRR judge_VVI how_RGQ much_DA1 capital_NN1 will_VM be_VBI needed_VVN as_II a_AT1 buffer_NN1 to_TO reach_VVI a_AT1 specified_JJ level_NN1 of_IO stability_NN1 ._. 
</s>
<s>
Nevertheless_RR ,_, the_AT fact_NN1 is_VBZ that_CST a_AT1 bank_NN1 is_VBZ exposed_VVN to_II various_JJ risks_NN2 that_CST could_VM cause_VVI trouble_NN1 to_II its_APPGE solvency_NN1 such_II21 as_II22 credit_NN1 risk_NN1 ,_, market_VV0 risk_NN1 ,_, operational_JJ risk_NN1 ,_, interest_NN1 rate_NN1 risk_NN1 ,_, liquidity_NN1 risk_NN1 and_CC political_JJ risk_NN1 ._. 
</s>
<s>
Perhaps_RR the_AT most_RGT highlighted_JJ risk_NN1 by_II the_AT recent_JJ crisis_NN1 is_VBZ the_AT systemic_JJ risk_NN1 that_CST has_VHZ nt_XX been_VBN regulated_VVN previously_RR at_RR21 all_RR22 ._. 
</s>
<s>
To_TO calculate_VVI all_DB these_DD2 risks_NN2 correctly_RR is_VBZ a_AT1 daunting_JJ task_NN1 ._. 
</s>
<s>
So_RG far_RR ,_, capital_NN1 requirements_NN2 have_VH0 mainly_RR attempted_VVN to_TO cover_VVI only_JJ credit_NN1 risk_NN1 and_CC operational_JJ risk_NN1 ._. 
</s>
<s>
2.4_MC Capital_JJ regulation_NN1 in_II Basel_NP1 Accords_VVZ 2.5_MC Basel_NP1 III_MC as_II a_AT1 response_NN1 to_II crisis_NN1 3_MC Liquidity_NN1 risk_NN1 regulation_NN1 3.1_MC What_DDQ is_VBZ a_AT1 liquidity_NN1 risk_NN1 ?_? 3.2_MC Liquidity_NN1 risk_NN1 regulation_NN1 in_II Basel_NP1 III_MC 4_MC Assessing_VVG the_AT Basel_NP1 III_MC liquidity_NN1 regulation_NN1 5_MC Conclusion_NN1 
</s>
