<s>
FAIR_JJ USE_NN1 IN_II DEFENDING_JJ REMIX_NN1 CULTURE_NN1 IN_II THE_AT EUROPEAN_JJ UNION_NN1 INTRODUCTION_NN1 Inarguably_RR ,_, the_AT way_NN1 music_NN1 is_VBZ consumed_VVN today_RT is_VBZ very_RG different_JJ from_II what_DDQ it_PPH1 used_VMK to_TO be_VBI ._. 
</s>
<s>
The_AT digitalisation_NN1 and_CC the_AT development_NN1 of_IO the_AT internet_NN1 have_VH0 led_VVN to_II a_AT1 myriad_NN1 of_IO new_JJ ways_NN2 to_TO distribute_VVI and_CC consume_VVI music_NN1 ._. 
</s>
<s>
According_II21 to_II22 European_JJ Commission_NN1 ,_, user-generated_JJ content_NN1 is_VBZ emerging_JJ and_CC having_VHG a_AT1 new_JJ and_CC important_JJ role_NN1 alongside_RL professionally_RR produced_VVN content_NN1 ._. 
</s>
<s>
This_DD1 has_VHZ an_AT1 increasing_JJ social_JJ ,_, cultural_JJ and_CC economic_JJ impact_NN1 on_II content_JJ industries_NN2 ,_, as_CSA consumers_NN2 expect_VV0 more_DAR freedom_NN1 and_CC flexibility_NN1 to_TO express_VVI themselves_PPX2 by_II re-creating_VVG new_JJ works_NN from_II previous_JJ works_NN ._. 
</s>
<s>
This_DD1 can_VM be_VBI seen_VVN as_CSA consumers_NN2 becoming_VVG content_JJ providers_NN2 on_II sites_NN2 like_II YouTube_NP1 ,_, Daily_NP1 Motion_NN1 and_CC MySpace_NP1 in_II what_DDQ is_VBZ nowadays_RT called_VVN the_AT "_" second-generation_JJ internet_NN1 "_" ._. 
</s>
<s>
One_MC1 of_IO the_AT many_DA2 examples_NN2 of_IO this_DD1 kind_NN1 of_IO creativity_NN1 are_VBR so-called_JJ mash-ups_NN2 ,_, which_DDQ are_VBR created_VVN by_II combining_VVG parts_NN2 of_IO several_DA2 different_JJ songs_NN2 in_BCL21 order_BCL22 to_TO create_VVI a_AT1 new_JJ ,_, arguably_RR original_JJ ,_, piece_NN1 of_IO music_NN1 ._. 
</s>
<s>
For_REX21 instance_REX22 ,_, Girl_NN1 Talk_NN1 ,_, a_AT1 well_NN1 known_VVN artist_NN1 in_II this_DD1 genre_NN1 ,_, has_VHZ a_AT1 song_NN1 consisting_VVG of_IO 200_MC to_II 250_MC samples_NN2 from_II 167_MC artists_NN2 ._. 
</s>
<s>
This_DD1 new_JJ phenomenon_NN1 ,_, however_RR ,_, is_VBZ in_II contradiction_NN1 with_IW the_AT current_JJ state_NN1 of_IO the_AT copyright_NN1 law_NN1 ._. 
</s>
<s>
According_II21 to_II22 Directive_NN1 2001/29/EC_FU ,_, the_AT authors_NN2 shall_VM have_VHI the_AT exclusive_JJ right_NN1 to_TO reproduce_VVI a_AT1 work_NN1 "_" in_II whole_NN1 or_CC in_RR21 part_RR22 "_" (_( Article_NN1 2_MC )_) ,_, which_DDQ means_VVZ that_CST a_AT1 license_NN1 should_VM be_VBI sought_VVN for_IF even_RR a_AT1 part_NN1 of_IO copyrighted_JJ material_NN1 included_VVN in_II a_AT1 mash-up_NN1 piece_NN1 ._. 
</s>
<s>
Inpractical_NP1 ,_, time_NNT1 consuming_VVG and_CC costly_JJ as_CSA this_DD1 can_VM become_VVI ,_, most_DAT of_IO the_AT creators_NN2 of_IO the_AT new_JJ digital_JJ era_NN1 never_RR seek_VV0 for_IF these_DD2 licenses_NN2 ._. 
</s>
<s>
As_II21 regards_II22 to_II Girl_NN1 Talk_NN1 ,_, since_CS no_AT permission_NN1 was_VBDZ asked_VVN from_II the_AT authors_NN2 of_IO the_AT songs_NN2 ,_, his_APPGE song_NN1 was_VBDZ removed_VVN from_II several_DA2 online_JJ shops_NN2 quite_RG shortly_RR after_II his_APPGE emergence_NN1 in_II the_AT public_NN1 's_GE and_CC especially_RR the_AT copyright_NN1 owners_NN2 '_GE awareness_NN1 ._. 
</s>
<s>
Thus_RR ,_, this_DD1 remix_NN1 culture_NN1 ,_, as_CSA Lessig_NP1 calls_VVZ it_PPH1 ,_, is_VBZ unable_JK to_TO survive_VVI in_II the_AT current_JJ legal_JJ environment_NN1 ,_, because_CS the_AT efforts_NN2 and_CC the_AT financial_JJ resources_NN2 required_VVN to_TO ensure_VVI its_APPGE legitimacy_NN1 are_VBR unfeasible_JJ ._. 
</s>
<s>
The_AT fundamental_JJ point_NN1 of_IO interest_NN1 in_II31 relation_II32 to_II33 the_AT remix_NN1 culture_NN1 from_II a_AT1 legal_JJ viewpoint_NN1 is_VBZ the_AT scope_NN1 of_IO limitations_NN2 applied_VVN to_II copyright_NN1 protection_NN1 ._. 
</s>
<s>
The_AT Directive_NN1 2001/29/EC_FU aims_VVZ to_TO harmonise_VVI these_DD2 exceptions_NN2 on_II a_AT1 European_JJ level_NN1 in_II an_AT1 exhaustive_JJ list_NN1 in_II Article_NN1 5_MC :_: Exceptions_NN2 and_CC limitations_NN2 ._. 
</s>
<s>
They_PPHS2 include_VV0 certain_JJ technical_JJ as_II31 well_II32 as_II33 practical_JJ cases_NN2 where_RRQ copyrighted_JJ material_NN1 can_VM be_VBI used_VVN without_RL there_EX being_VBG an_AT1 infringement_NN1 ._. 
</s>
<s>
However_RR ,_, only_JJ Article_NN1 5(3)_FO (_( k_ZZ1 )_) is_VBZ in_II a_AT1 remote_JJ relation_NN1 to_II abovementioned_JJ remixing_NN1 ,_, excluding_VVG copyright_NN1 protection_NN1 in_II cases_NN2 of_IO caricature_NN1 ,_, parody_NN1 or_CC pastiche_NN1 ._. 
</s>
<s>
As_II21 for_II22 now_RT ,_, there_EX is_VBZ no_AT legal_JJ support_NN1 for_IF remix_NN1 works_VVZ relying_VVG on_II still_RR protected_JJ material_NN1 as_II such_DA ,_, and_CC the_AT only_JJ way_NN1 would_VM be_VBI to_TO show_VVI that_CST the_AT work_NN1 one_PN1 has_VHZ created_VVN is_VBZ a_AT1 parody_NN1 of_IO some_DD kind_NN1 ._. 
</s>
<s>
In_II the_AT core_NN1 of_IO the_AT issue_NN1 lies_VVZ a_AT1 dilemma_NN1 :_: should_VM user-generated_JJ content_NN1 ,_, that_DD1 uses_VVZ material_NN1 from_II copyrighted_JJ works_NN ,_, be_VBI allowed_VVN and_CC accepted_VVN as_II a_AT1 modern_JJ output_NN1 of_IO creativity_NN1 ,_, or_CC should_VM the_AT traditional_JJ philosophy_NN1 behind_II copyright_NN1 be_VBI respected_VVN and_CC thus_RR the_AT exclusivity_NN1 valued_VVN on_II the_AT cost_NN1 of_IO a_AT1 new_JJ ,_, potentially_RR flourishing_JJ ,_, market_NN1 of_IO remix_NN1 culture_NN1 ?_? 
</s>
<s>
This_DD1 study_NN1 aims_VVZ to_TO discover_VVI ,_, whether_CSW31 or_CSW32 not_CSW33 the_AT legislative_JJ development_NN1 in_II Europe_NP1 is_VBZ shifting_VVG towards_II preferring_VVG the_AT existence_NN1 of_IO works_NN built_VVN upon_II existing_JJ copyrighted_JJ works_NN ._. 
</s>
<s>
The_AT research_NN1 lies_VVZ on_II the_AT principal_NN1 of_IO fair_JJ use_NN1 ,_, which_DDQ is_VBZ an_AT1 exception_NN1 to_II copyright_NN1 protection_NN1 ,_, and_CC the_AT research_NN1 question_NN1 will_VM be_VBI whether_CSW31 or_CSW32 not_CSW33 the_AT European_JJ concept_NN1 of_IO exceptions_NN2 and_CC limitations_NN2 is_VBZ likely_JJ to_TO cover_VVI for_IF remix_NN1 culture_NN1 in_II audiovisual_JJ works_NN made_VVD available_JJ online_JJ in_II the_AT future_NN1 ._. 
</s>
<s>
This_DD1 study_NN1 will_VM be_VBI conducted_VVN by_II using_VVG a_AT1 qualitative_JJ research_NN1 method_NN1 ,_, where_CS legal_JJ cases_NN2 and_CC rulings_NN2 the_AT Court_NN1 of_IO Justice_NN1 of_IO the_AT European_JJ Communities_NN2 (_( further_RRR referred_VVN to_II as_CSA ECJ_NP1 )_) from_II the_AT last_MD five_MC years_NNT2 function_NN1 as_CSA indications_NN2 of_IO how_RRQ Article_NN1 5_MC of_IO Directive_NN1 2001/29/EC_FU is_VBZ interpreted_VVN within_II modern_JJ legal_JJ practice_NN1 ._. 
</s>
<s>
It_PPH1 will_VM then_RT be_VBI assessed_VVN whether_CSW31 or_CSW32 not_CSW33 these_DD2 cases_NN2 and_CC rulings_NN2 have_VH0 given_VVN an_AT1 increasing_JJ preference_NN1 towards_II allowing_VVG remix_NN1 culture_NN1 to_TO exist_VVI and_CC be_VBI made_VVN available._NNU 1_MC1 Remix_NN1 culture_NN1 In_II this_DD1 chapter_NN1 it_PPH1 will_VM explained_VVD what_DDQ remix_VV0 culture_NN1 is_VBZ ,_, how_RRQ it_PPH1 has_VHZ developed_VVN and_CC what_DDQ are_VBR the_AT basic_JJ consequences_NN2 ,_, good_JJ and_CC bad_JJ ,_, of_IO it_PPH1 ._. 
</s>
<s>
The_AT term_NN1 ,_, as_II such_DA ,_, is_VBZ used_VVN by_II Laurence_NP1 Lessig_NP1 ,_, an_AT1 American_JJ lawyer_NN1 practicing_VVG within_II copyright_NN1 issues_NN2 and_CC having_VHG written_VVN extensively_RR on_II issues_NN2 related_VVN to_II new_JJ technology_NN1 and_CC copyright_NN1 ._. 
</s>
<s>
Other_JJ literature_NN1 is_VBZ also_RR used_VVN for_IF describing_VVG the_AT emerging_JJ artform_NN1 ._. 
</s>
<s>
The_AT chapter_NN1 will_VM demostrate_VVI the_AT issues_NN2 and_CC problems_NN2 faced_VVN when_CS dealing_VVG with_IW remix_NN1 culture_NN1 ,_, be_VBI it_PPH1 in_II the_AT form_NN1 of_IO creating_VVG or_CC distributing_VVG and_CC sharing._NNU 2_MC Fundamentals_NP1 of_IO copyright_NN1 law_NN1 Certain_JJ aspects_NN2 of_IO copyright_NN1 law_NN1 will_VM be_VBI uncovered_VVN to_TO give_VVI a_AT1 basic_JJ understanding_NN1 of_IO the_AT philosophy_NN1 why_RRQ copyright_NN1 protection_NN1 is_VBZ granted_VVN and_CC how_RRQ it_PPH1 functions_VVZ ._. 
</s>
<s>
The_AT chapter_NN1 will_VM discuss_VVI the_AT scope_NN1 of_IO copyright_NN1 protection_NN1 ,_, its_APPGE function_NN1 as_II an_AT1 incentive_NN1 to_TO create_VVI as_II31 well_II32 as_II33 the_AT idea_NN1 of_IO giving_VVG a_AT1 limited_JJ monopoly._NNU 3_MC Fair_JJ use_NN1 in_II the_AT European_JJ Union_NN1 This_DD1 chapter_NN1 explains_VVZ what_DDQ the_AT concept_NN1 fair_JJ use_NN1 means_NN and_CC how_RRQ it_PPH1 functions_VVZ in_II the_AT European_JJ copyright_NN1 legislation_NN1 ._. 
</s>
<s>
Fair_JJ use_NN1 is_VBZ used_VVN in_II the_AT American_JJ copyright_NN1 system_NN1 as_II an_AT1 umbrella_NN1 term_NN1 for_IF all_DB exceptions_NN2 to_II the_AT scope_NN1 of_IO protection_NN1 of_IO a_AT1 copyrighted_JJ work_NN1 ._. 
</s>
<s>
In_II Europe_NP1 ,_, these_DD2 exceptions_NN2 are_VBR described_VVN in_II an_AT1 exhaustive_JJ list_NN1 in_II Article_NN1 5_MC of_IO the_AT InfoSoc_NP1 Directive_NN1 2001_MC ._. 
</s>
<s>
This_DD1 chapter_NN1 will_VM elaborate_VVI on_II some_DD of_IO those_DD2 exceptions_NN2 that_RG best_RRT connect_VV0 with_IW the_AT issue_NN1 at_II hand_NN1 ._. 
</s>
<s>
There_EX are_VBR differences_NN2 in_II the_AT national_JJ implementations_NN2 of_IO the_AT Directive_NN1 ,_, because_CS most_DAT of_IO the_AT exceptions_NN2 there_EX are_VBR permissive_JJ ,_, in_II other_JJ words_NN2 giving_VVG the_AT Member_NN1 States_VVZ the_AT possibility_NN1 to_TO choose_VVI whether_CSW31 or_CSW32 not_CSW33 they_PPHS2 would_VM like_VVI to_TO implement_VVI certain_JJ amount_NN1 of_IO them_PPHO2 in_II their_APPGE own_DA copyright_NN1 legislation_NN1 ._. 
</s>
<s>
This_DD1 leads_VVZ to_II an_AT1 unharmonised_JJ situation_NN1 in_II31 relation_II32 to_II33 exceptions_NN2 and_CC limitations._NNU 3.1_MC Exceptions_NN2 and_CC limitations_NN2 There_EX are_VBR certain_JJ uses_NN2 that_CST are_VBR not_XX regulated_VVN by_II copyright_NN1 law_NN1 ,_, for_REX21 example_REX22 those_DD2 of_IO public_JJ interest_NN1 ._. 
</s>
<s>
It_PPH1 must_VM be_VBI secured_VVN that_DD1 property_NN1 rights_NN2 are_VBR not_XX used_VVN oppressively_RR or_CC contrary_II21 to_II22 countervailing_JJ public_JJ interests_NN2 ._. 
</s>
<s>
This_DD1 is_VBZ why_RRQ there_EX are_VBR exceptions_NN2 and_CC limitations_NN2 to_II the_AT protection_NN1 of_IO copyright_NN1 that_CST allow_VV0 certain_JJ kind_NN1 of_IO use_NN1 of_IO the_AT copyrighted_JJ material_NN1 ._. 
</s>
<s>
This_DD1 chapter_NN1 will_VM explain_VVI what_DDQ kinds_NN2 of_IO exceptions_NN2 are_VBR found_VVN from_II the_AT InfoSoc_NP1 Directive_NN1 ._. 
</s>
<s>
Those_DD2 that_RG best_RRT connect_VV0 with_IW the_AT issue_NN1 at_II hand_NN1 will_VM be_VBI elaborated_VVN on._NNU 3.2_MC National_JJ implementations_NN2 Since_CS the_AT field_NN1 of_IO national_JJ laws_NN2 in_II31 relation_II32 to_II33 exceptions_NN2 and_CC limitations_NN2 is_VBZ unharmonised_JJ ,_, there_EX are_VBR certain_JJ differences_NN2 between_II national_JJ copyright_NN1 laws_NN2 of_IO the_AT Member_NN1 States_VVZ within_II the_AT EU_NP1 ._. 
</s>
<s>
This_DD1 chapter_NN1 will_VM uncover_VVI some_DD of_IO those_DD2 differences_NN2 in_BCL21 order_BCL22 to_TO describe_VVI the_AT fragmentation_NN1 of_IO the_AT field_NN1 of_IO copyright_NN1 law_NN1 within_II the_AT EU._NP1 4_MC Research_NN1 problem_NN1 and_CC research_NN1 question_NN1 There_EX are_VBR several_DA2 examples_NN2 of_IO a_AT1 new_JJ form_NN1 of_IO culture_NN1 that_CST is_VBZ created_VVN from_II existing_JJ pieces_NN2 of_IO music_NN1 ._. 
</s>
<s>
The_AT creators_NN2 of_IO this_DD1 culture_NN1 regard_VV0 themselves_PPX2 as_II creators_NN2 of_IO new_JJ works_NN ,_, rather_CS21 than_CS22 someone_PN1 who_PNQS merely_RR steals_VVZ the_AT intellectual_JJ property_NN1 of_IO others_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ unknown_JJ as_II21 of_II22 now_RT whether_CSW31 or_CSW32 not_CSW33 there_EX is_VBZ a_AT1 possibility_NN1 for_IF this_DD1 form_NN1 of_IO culture_NN1 to_TO legally_RR exist_VVI in_II the_AT future_NN1 ._. 
</s>
<s>
Therefore_RR it_PPH1 needs_VVZ to_TO be_VBI researched_VVN how_RRQ the_AT issue_NN1 is_VBZ perceived_VVN within_II the_AT European_JJ case_NN1 law_NN1 in_BCL21 order_BCL22 to_TO establish_VVI what_DDQ the_AT future_JJ direction_NN1 might_VM be_VBI ._. 
</s>
<s>
The_AT research_NN1 question_NN1 will_VM be_VBI :_: Is_VBZ fair_JJ use_NN1 as_II a_AT1 concept_NN1 likely_JJ to_TO cover_VVI for_IF remix_NN1 culture_NN1 within_II the_AT EU_NP1 in_II the_AT future_NN1 ?_? 5_MC Case_NN1 law_NN1 :_: Fair_JJ use_NN1 in_II defending_VVG remix_NN1 culture_NN1 in_II the_AT EU_NP1 This_DD1 chapter_NN1 will_VM give_VVI an_AT1 overview_NN1 of_IO legal_JJ cases_NN2 in_II both_DB2 the_AT Court_NN1 of_IO Justice_NN1 of_IO the_AT European_JJ Communities_NN2 and_CC national_JJ courts_NN2 of_IO the_AT Member_NN1 States_NP1 ._. 
</s>
<s>
The_AT decisions_NN2 will_VM be_VBI analysed_VVN from_II the_AT viewpoint_NN1 of_IO how_RRQ they_PPHS2 line_VV0 up_RP with_IW the_AT exceptions_NN2 and_CC limitations_NN2 in_II Article_NN1 5_MC of_IO the_AT InfoSoc_NP1 Directive._NP1 5.1_MC Rulings_NN2 of_IO the_AT Court_NN1 of_IO Justice_NN1 of_IO the_AT European_JJ Communities_NN2 ECJ_VV0 rulings_NN2 will_VM be_VBI uncovered_VVN and_CC analysed_VVN here_RL ._. 
</s>
<s>
Important_JJ aspects_NN2 in_II the_AT rulings_NN2 include_VV0 the_AT references_NN2 to_II Article_NN1 5_MC in_II the_AT InfoSoc_NP1 Directive_NN1 and_CC how_RRQ this_DD1 article_NN1 is_VBZ interpreted_VVN in_II31 relation_II32 to_II33 different_JJ kinds_NN2 of_IO uses_NN2 of_IO copyrighted_JJ material._NNU 5.2_MC National_JJ case_NN1 law_NN1 of_IO the_AT Member_NN1 States_VVZ Decisions_NN2 from_II the_AT national_JJ courts_NN2 of_IO the_AT Member_NN1 States_NN2 will_VM be_VBI presented_VVN and_CC analysed_VVN here_RL ._. 
</s>
<s>
If_CS there_EX are_VBR certain_JJ national_JJ courts_NN2 ruling_NN1 in_II a_AT1 substantially_RR different_JJ way_NN1 from_II other_JJ national_JJ courts_NN2 ,_, this_DD1 will_VM be_VBI highlighted._NNU 6_MC Conclusions_NN2 The_AT results_NN2 and_CC their_APPGE implications_NN2 will_VM be_VBI discussed_VVN here_RL ._. 
</s>
<s>
Conclusions_NN2 will_VM be_VBI drawn_VVN in_II order_NN1 to_TO finally_RR answer_VVI the_AT research_NN1 question_NN1 based_VVN on_II the_AT finding_NN1 in_II the_AT case_NN1 laws_NN2 of_IO ECJ_NP1 and_CC the_AT national_JJ courts_NN2 ._. 
</s>
<s>
Patterns_NN2 will_VM be_VBI looked_VVN for_IF in_II31 terms_II32 of_II33 how_RRQ remix_NN1 uses_NN2 are_VBR regarded_VVN in_II these_DD2 courts_NN2 ,_, especially_RR in_II31 relation_II32 to_II33 the_AT Article_NN1 5_MC of_IO the_AT InfoSoc_NP1 Directive_NN1 ._. 
</s>
