<s>
Life_NN1 Cycle_NN1 Management_NN1 of_IO Open_JJ Source_NN1 ERPs_VVZ in_II SMEs_NN2 1_MC1 Introduction_NN1 The_AT magnitude_NN1 of_IO an_AT1 ERP_NN1 implementation_NN1 initiative_NN1 is_VBZ a_AT1 classic_JJ issue_NN1 of_IO discussion_NN1 in_II ERP_NP1 research_NN1 ._. 
</s>
<s>
Traditionally_RR companies_NN2 have_VH0 relied_VVN on_II big_JJ and_CC expensive_JJ commercial_JJ ERP_NN1 solutions_NN2 from_II well_RR known_VVN vendors_NN2 ,_, such_II21 as_II22 SAP_NN1 ,_, Oracle_NN1 and_CC Infor_NP1 ._. 
</s>
<s>
Usually_RR such_DA companies_NN2 charge_VV0 prices_NN2 starting_VVG from_II millions_NNO2 of_IO euros_NN2 for_IF the_AT installation_NN1 ,_, consultation_NN1 ,_, training_NN1 and_CC other_JJ required_JJ tasks_NN2 related_VVN to_II the_AT installation_NN1 of_IO an_AT1 ERP_NN1 ._. 
</s>
<s>
Large_JJ enterprises_NN2 are_VBR typically_RR in_II31 possession_II32 of_II33 enough_DD resources_NN2 to_TO cover_VVI all_DB required_JJ expenses_NN2 ,_, whereas_CS proprietary_JJ ERPs_NN2 are_VBR much_RR less_RGR affordable_JJ to_II SMEs_NN2 ._. 
</s>
<s>
Thus_RR research_VV0 and_CC development_NN1 of_IO open_JJ source_NN1 ERP_NN1 is_VBZ significant_JJ for_IF SMEs_NN2 ._. 
</s>
<s>
The_AT success_NN1 factors_NN2 in_II the_AT implementation_NN1 of_IO ERP_NN1 into_II enterprises_NN2 has_VHZ been_VBN studied_VVN extensively_RR in_II the_AT past_JJ decade_NNT1 ._. 
</s>
<s>
Of_IO the_AT many_DA2 CSFs_NP1 ,_, allocation_NN1 of_IO experts_NN2 ,_, balanced_JJ team_NN1 ,_, definition_NN1 of_IO scope_NN1 and_CC goals_NN2 ,_, deliverable_JJ dates_NN2 ,_, management_NN1 support_NN1 and_CC commitment_NN1 to_TO change_VVI have_VH0 been_VBN the_AT most_RGT extensively_RR studied_VVN &lsqb;_( Xia_NP1 ,_, Lok_NP1 ,_, and_CC Yang_NP1 ,_, 2009_MC &rsqb;_) ._. 
</s>
<s>
Likewise_RR the_AT factors_NN2 of_IO failure_NN1 have_VH0 received_VVN considerable_JJ attention_NN1 ,_, including_II issues_NN2 related_VVN to_II the_AT organization_NN1 culture_NN1 ,_, management_NN1 base_NN1 ,_, allocation_NN1 of_IO experts_NN2 and_CC limitation_NN1 of_IO capital_NN1 &lsqb;_( Xia_NP1 et_RA21 al._RA22 ,_, 2009_MC &rsqb;_) ._. 
</s>
<s>
A_AT1 large_JJ body_NN1 of_IO data_NN suggests_VVZ that_CST most_DAT companies_NN2 attempting_VVG to_TO integrate_VVI ERPs_NN2 have_VH0 failed_VVN &lsqb;_( Chen_NP1 ,_, Law_NN1 ,_, and_CC Yang_NP1 ,_, 2009_MC ,_, Kumar_NP1 ,_, Suresh_NP1 ,_, and_CC Prashanth_NP1 ,_, 2009_MC ,_, Xia_NP1 et_RA21 al._RA22 ,_, 2009_MC ,_, Capaldo_NP1 and_CC Rippa_NP1 ,_, 2008_MC ,_, Johansson_NP1 and_CC Sudzina_NP1 ,_, 2008_MC &rsqb;_) ._. 
</s>
<s>
As_CSA ERPs_VVZ often_RR are_VBR the_AT single_JJ most_RGT expensive_JJ information_NN1 technology_NN1 (_( IT_NN1 )_) investment_NN1 for_IF enterprises_NN2 ,_, knowledge_NN1 of_IO how_RRQ to_TO increase_VVI the_AT success_NN1 rate_NN1 of_IO such_DA initiatives_NN2 has_VHZ great_JJ importance_NN1 for_IF industries_NN2 ._. 
</s>
<s>
A_AT1 long-standing_JJ problem_NN1 has_VHZ been_VBN to_TO obtain_VVI more_DAR information_NN1 on_II CSF_NP1 relating_VVG to_TO open_VVI source_NN1 ERP_NN1 ,_, which_DDQ are_VBR especially_RR attractive_JJ to_II SMEs_NN2 due_II21 to_II22 the_AT smaller_JJR commitments_NN2 involved_VVD ._. 
</s>
<s>
Many_DA2 investigators_NN2 have_VH0 recently_RR turned_VVN to_TO research_VVI open_JJ source_NN1 ERP_NN1 success_NN1 factors_NN2 ,_, while_CS researching_VVG less_RRR and_CC less_DAR ERP_NN1 which_DDQ is_VBZ not_XX open_JJ source_NN1 ._. 
</s>
<s>
The_AT change_NN1 can_VM be_VBI seen_VVN in_II the_AT amount_NN1 of_IO published_JJ articles_NN2 (_( see_VV0 appendix_NN1 B_ZZ1 )_) ._. 
</s>
<s>
The_AT general_JJ features_NN2 of_IO ERP_NP1 implementation_NN1 process_NN1 models_NN2 are_VBR well_RR mapped_VVN &lsqb;_( Chen_NP1 et_RA21 al._RA22 ,_, 2009_MC ,_, Kumar_NP1 et_RA21 al._RA22 ,_, 2009_MC ,_, Xia_NP1 et_RA21 al._RA22 ,_, 2009_MC ,_, Capaldo_NP1 and_CC Rippa_NP1 ,_, 2008_MC ,_, Manarvi_NP1 ,_, Irfan_NP1 and_CC Ahmad_NP1 ,_, 2008_MC ,_, Motwani_NP1 ,_, Subramanian_JJ ,_, and_CC Gopalakrishna_NP1 ,_, 2005_MC &rsqb;_) ._. 
</s>
<s>
E.g._REX one_MC1 standard_JJ ERP_NN1 implementation_NN1 framework_NN1 consists_VVZ of_IO three_MC phases_NN2 :_: pre-implementation_NN1 (_( including_II understanding_VVG the_AT goals_NN2 of_IO ERP_NP1 ,_, commitment_NN1 by_II top_JJ management_NN1 and_CC cultural_JJ and_CC structural_JJ changes_NN2 )_) ,_, implementation_NN1 (_( inculding_VVG project_NN1 management_NN1 ,_, package_NN1 selection_NN1 and_CC establishing_VVG common_JJ communication_NN1 policies_NN2 )_) and_CC post-implementation_NN1 (_( including_II audit_NN1 and_CC documentation_NN1 )_) &lsqb;_( Motwani_NP1 et_RA21 al._RA22 ,_, 2005_MC &rsqb;_) ._. 
</s>
<s>
It_PPH1 is_VBZ generally_RR accepted_VVN that_CST open_JJ source_NN1 ERP_NN1 can_VM bring_VVI SMEs_NN2 huge_JJ savings_NN2 over_II choosing_VVG commercial_JJ packages_NN2 ._. 
</s>
<s>
Yet_RR at_II the_AT same_DA time_NNT1 consultants_NN2 of_IO open_JJ source_NN1 ERP_NN1 might_VM cost_VVI double_RR that_DD1 of_IO consultants_NN2 of_IO commercial_JJ solutions_NN2 Johansson_NP1 and_CC Sudzina_NP1 &lsqb;_( 2008_MC &rsqb;_) ._. 
</s>
<s>
For_IF both_DB2 types_NN2 of_IO ERP_NP1 there_EX are_VBR common_JJ costs_NN2 ,_, such_II21 as_II22 learning_NN1 ,_, installation_NN1 and_CC maintenance_NN1 costs_NN2 ._. 
</s>
<s>
Observations_NN2 by_II Chen_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
&lsqb;_( 2009_MC &rsqb;_) suggest_VV0 that_CST the_AT following_NN1 six_MC project_NN1 management_NN1 areas_NN2 are_VBR CSF_NP1 in_II ERP_NP1 implementation_NN1 :_: scope_NN1 ,_, human_JJ resource_NN1 ,_, risk_NN1 ,_, communications_NN2 ,_, procurement_NN1 and_CC integration_NN1 ._. 
</s>
<s>
Kumar_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
&lsqb;_( 2009_MC &rsqb;_) argued_VVD that_CST the_AT following_JJ things_NN2 are_VBR crucial_JJ for_IF a_AT1 successful_JJ implementation_NN1 :_: provision_NN1 of_IO exact_JJ data_NN from_II legacy_NN1 systems_NN2 and_CC on_II entry_NN1 to_II the_AT new_JJ system_NN1 ,_, undertaking_NN1 of_IO proper_JJ training_NN1 of_IO new_JJ system_NN1 ,_, avoidance_NN1 of_IO usage_NN1 of_IO parallel_JJ systems_NN2 ,_, doing_VDG at_RR21 least_RR22 one_MC1 conference_NN1 room_NN1 pilot_NN1 before_II system_NN1 launch_NN1 ,_, practice_NN1 of_IO employee_NN1 retention_NN1 programs_NN2 ,_, less_DAR than_CSN 30_MC %_NNU customization_NN1 of_IO initial_JJ packages_NN2 and_CC clarity_NN1 in_II management_NN1 objectives_NN2 and_CC expectations_NN2 and_CC identification_NN1 of_IO all_DB stakeholders_NN2 ._. 
</s>
<s>
Data_NN have_VH0 been_VBN presented_VVN in_II the_AT literature_NN1 which_DDQ show_VV0 that_CST in_II SMEs_NN2 in_II China_NP1 the_AT following_JJ issues_NN2 can_VM be_VBI problematic_JJ when_CS implementating_VVG ERPs_NN2 :_: organization_NN1 culture_NN1 ,_, management_NN1 base_NN1 ,_, absence_NN1 of_IO IT_NN1 engineer_NN1 and_CC limitation_NN1 of_IO capital_NN1 &lsqb;_( Xia_NP1 et_RA21 al._RA22 ,_, 2009_MC &rsqb;_) ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 it_PPH1 has_VHZ been_VBN suggested_VVN that_CST CSF_NP1 are_VBR :_: top_JJ management_NN1 support_NN1 ,_, great_JJ competence_NN1 tea_NN1 ,_, right_JJ implementation_NN1 scope_NN1 ,_, management_NN1 program_NN1 change_NN1 ,_, data_NN accuracy_NN1 and_CC education_NN1 and_CC training_NN1 &lsqb;_( Xia_NP1 et_RA21 al._RA22 ,_, 2009_MC &rsqb;_) ._. 
</s>
<s>
Johansson_NN1 and_CC Sudzina_NP1 &lsqb;_( 2008_MC &rsqb;_) concluded_VVD that_CST clearly_RR there_EX are_VBR other_JJ factors_NN2 than_CSN cost_NN1 which_DDQ need_VV0 to_TO be_VBI taken_VVN into_II consideration_NN1 when_CS choosing_VVG whether_CSW to_TO adopt_VVI a_AT1 open_JJ source_NN1 ERP_NN1 or_CC a_AT1 proprietary_JJ ._. 
</s>
<s>
A_AT1 considerable_JJ amount_NN1 of_IO research_NN1 has_VHZ been_VBN carried_VVN out_RP relating_VVG to_II life_NN1 cycle_NN1 management_NN1 of_IO ERP_NP1 and_CC about_II open_JJ source_NN1 ERP_NN1 ._. 
</s>
<s>
However_RR ,_, less_DAR attention_NN1 has_VHZ been_VBN paid_VVN to_II critical_JJ success_NN1 factors_NN2 in_II life_NN1 cycle_NN1 management_NN1 of_IO open_JJ source_NN1 ERP_NN1 in_II SMEs_NN2 ._. 
</s>
<s>
The_AT purpose_NN1 of_IO this_DD1 paper_NN1 is_VBZ to_TO describe_VVI how_RRQ to_TO manage_VVI the_AT life_NN1 cycle_NN1 of_IO free_JJ and_CC open_JJ source_NN1 ERP_NN1 ._. 
</s>
<s>
The_AT research_NN1 questions_NN2 are_VBR :_: 1_MC1 ._. 
</s>
<s>
How_RRQ are_VBR open_JJ source_NN1 ERP_VV0 different_JJ from_II proprietary_JJ ERP_NN1 ?_? 2_MC ._. 
</s>
<s>
What_DDQ does_VDZ ERP_VVI LCM_NP1 consist_VV0 of_IO ?_? 3_MC ._. 
</s>
<s>
How_RRQ is_VBZ open_JJ source_NN1 ERP_NP1 LCM_NP1 different_JJ from_II proprietary_JJ ERP_NP1 LCM_NP1 ?_? 4_MC ._. 
</s>
<s>
Based_VVN on_II the_AT paper_NN1 's_GE findings_NN2 ,_, which_DDQ available_JJ open_JJ source_NN1 ERP_NN1 are_VBR suitable_JJ for_IF SMEs_NN2 ?_? 
</s>
<s>
The_AT paper_NN1 is_VBZ structured_VVN as_CSA follows_VVZ ._. 
</s>
<s>
Section_NN1 2_MC presents_VVZ a_AT1 history_NN1 of_IO ERP_NP1 ,_, shows_VVZ some_DD statistics_NN about_II the_AT present_JJ market_NN1 shares_NN2 and_CC describes_VVZ how_RRQ ERPs_NN2 are_VBR categorized_VVN ._. 
</s>
<s>
Section_NN1 3_MC describes_VVZ the_AT difference_NN1 between_II open_JJ source_NN1 ERP_NN1 and_CC proprietary_JJ ERP_NN1 ._. 
</s>
<s>
Section_NN1 4_MC presents_VVZ the_AT life_NN1 cycle_NN1 management_NN1 or_CC ERP_NP1 and_CC what_DDQ needs_VVZ to_TO be_VBI considered_VVN in_II the_AT process_NN1 ._. 
</s>
<s>
In_II section_NN1 5_MC ,_, the_AT differences_NN2 in_II LCM_NP1 of_IO open_JJ source_NN1 ERP_NN1 and_CC proprietary_JJ ERP_NN1 are_VBR presented_VVN ._. 
</s>
<s>
Next_MD ,_, section_NN1 6_MC reviews_VVZ present_JJ open_JJ source_NN1 ERPs_NN2 based_VVN on_II the_AT literature_NN1 review_NN1 and_CC suggests_VVZ a_AT1 method_NN1 to_TO distinguish_VVI between_II the_AT different_JJ ERPs_NN2 ._. 
</s>
<s>
Penultimately_RR ,_, section_NN1 7_MC presents_VVZ the_AT contributions_NN2 of_IO the_AT paper_NN1 ._. 
</s>
<s>
Finally_RR ,_, section_NN1 8_MC explains_VVZ the_AT limitations_NN2 and_CC tells_VVZ the_AT conclusions_NN2 of_IO the_AT paper._NNU 2_MC Enterprise_NN1 Resource_NN1 Planning_VVG The_AT purpose_NN1 of_IO this_DD1 chapter_NN1 is_VBZ to_TO describe_VVI the_AT history_NN1 of_IO ERP_NP1 ,_, why_RRQ it_PPH1 is_VBZ relevant_JJ for_IF business_NN1 and_CC how_RRQ ERP_NP1 is_VBZ categorized_VVN ._. 
</s>
<s>
To_TO put_VVI the_AT topic_NN1 into_II a_AT1 larger_JJR perspective_NN1 a_AT1 brief_JJ history_NN1 of_IO ERP_NN1 is_VBZ presented_VVN ._. 
</s>
<s>
In_II the_AT 1960s_MC2 the_AT first_MD predecessors_NN2 of_IO ERP_NP1 were_VBDR introduced_VVN ;_; the_AT first_MD systems_NN2 (_( computerized_JJ reorder_NN1 point_NN1 systems_NN2 )_) being_VBG able_JK to_TO notify_VVI when_RRQ a_AT1 reorder_NN1 of_IO inventory_NN1 should_VM take_VVI place_NN1 ._. 
</s>
<s>
Soon_RR the_AT first_MD manufacturing_NN1 planning_NN1 and_CC control_NN1 systems_NN2 (_( MPCs_NP1 )_) were_VBDR devised_VVN ._. 
</s>
<s>
MPCs_NP1 could_VM read_VVI and_CC write_VVI on_II magnetic_JJ tapes_NN2 ,_, which_DDQ contained_VVD item_NN1 lists_NN2 ,_, transactions_NN2 ,_, bills_NN2 of_IO material_NN1 (_( BOMs_NN2 )_) etc_RA ._. 
</s>
<s>
Later_RRR that_DD1 decade_NNT1 material_NN1 requirements_NN2 planning_VVG systems_NN2 (_( MRP_NP1 )_) were_VBDR developed_VVN ,_, with_IW the_AT breakthrough_NN1 of_IO random_JJ access_NN1 memory_NN1 (_( RAM_NN1 )_) ._. 
</s>
<s>
The_AT first_MD MRPs_NP1 were_VBDR huge_JJ ,_, expensive_JJ and_CC required_VVN much_RR technical_JJ staff_NN ._. 
</s>
<s>
MRP_NP1 continued_VVD to_TO develop_VVI until_CS the_AT next_MD breakthrough_NN1 happened_VVD in_II the_AT late_JJ 1970s_MC2 ,_, when_CS MRP_NP1 saw_VVD a_AT1 great_JJ increase_NN1 in_II demand_NN1 ,_, mainly_RR due_II21 to_II22 its_APPGE status_NN1 as_II the_AT de_JJ21 facto_JJ22 system_NN1 for_IF parts_NN2 and_CC materials_NN2 planning_VVG ._. 
</s>
<s>
All_DB through_II the_AT 1970s_MC2 many_DA2 ERP_VV0 related_JJ companies_NN2 were_VBDR established_VVN ,_, including_II SAP_NN1 ,_, Oracle_NN1 ,_, Lawson_NP1 Software_NN1 and_CC The_AT Baan_JJ Corporation_NN1 ._. 
</s>
<s>
Manufacturing_NN1 management_NN1 and_CC account_VV0 system_NN1 (_( MMAS_NP2 )_) was_VBDZ introduced_VVN in_II 1975_MC ._. 
</s>
<s>
It_PPH1 enabled_VVD users_NN2 to_TO create_VVI general_JJ ledger_NN1 postings_NN2 ,_, job_NN1 costing_VVG and_CC forecasting_VVG based_VVN on_II inventory_NN1 and_CC production_NN1 transactions_NN2 as_II31 well_II32 as_II33 generate_VV0 manufacturing_NN1 orders_NN2 from_II customer_NN1 orders_NN2 ._. 
</s>
<s>
According_II21 to_II22 Jacobs_NP2 and_CC Weston_NP1 Jr_NNA ._. 
</s>
<s>
&lsqb;_( 2007_MC &rsqb;_) the_AT next_MD version_NN1 ,_, introduced_VVN in_II 1978_MC ,_, manufacturing_NN1 ,_, accounting_VVG and_CC production_NN1 information_NN1 and_CC control_NN1 system_NN1 (_( MAPICS_NP1 )_) ,_, included_VVD "_" general_JJ ledger_NN1 ,_, accounts_VVZ payable_JJ ,_, order_NN1 entry_NN1 and_CC invoicing_NN1 ,_, accounts_VVZ receivable_JJ ,_, sales_NN analysis_NN1 ,_, payroll_NN1 ,_, data_NN collection_NN1 systems_NN2 support_VV0 ,_, product_NN1 and_CC production_NN1 definitions_NN2 &lsqb;_( ..._... &rsqb;_) ,_, inventory_NN1 management_NN1 ,_, material_NN1 requirements_NN2 planning_VVG &lsqb;_( ..._... &rsqb;_) ,_, production_NN1 monitoring_NN1 and_CC control_NN1 capabilities_NN2 &lsqb;_( ..._... &rsqb;_) forecasting_VVG ,_, capacity_NN1 requirements_NN2 planning_VVG ,_, purchasing_VVG ,_, and_CC full_JJ scale_NN1 master_NN1 production_NN1 schedule_NN1 planning_NN1 modules_NN2 "_" ._. 
</s>
<s>
Until_CS the_AT early_JJ 1980s_MC2 the_AT MRPs_NP1 evolved_VVD enough_RR for_IF a_AT1 new_JJ term_NN1 to_TO be_VBI coined_VVN ._. 
</s>
<s>
Manufacturing_NN1 resource_NN1 planning_NN1 (_( MRP-II_MC )_) referred_VVD to_II more_RGR sophisticated_JJ systems_NN2 than_CSN MRP_NP1 and_CC included_VVD flexible_JJ disk_NN1 drives_NN2 ._. 
</s>
<s>
During_II the_AT 1980s_MC2 many_DA2 innovations_NN2 were_VBDR made_VVN which_DDQ enabled_VVD more_RGR flexible_JJ MRP-II_MC ,_, including_II usage_NN1 of_IO the_AT programming_NN1 language_NN1 RPG2_FO ,_, usage_NN1 of_IO multi-user_JJ supporting_JJ UNIX_NN1 ,_, wide_JJ availability_NN1 of_IO the_AT SQL_NN1 database_NN1 system_NN1 by_II Oracle_NN1 and_CC the_AT human_JJ resource_NN1 management_NN1 system_NN1 (_( HRMS_NP1 )_) offered_VVD by_II PeopleSoft_NP1 ._. 
</s>
<s>
In_II the_AT 1990s_MC2 the_AT term_NN1 ERP_NN1 was_VBDZ coined_VVN ,_, distinguishing_VVG it_PPH1 from_II its_APPGE predecessor_NN1 mainly_RR by_II the_AT extend_VV0 that_CST it_PPH1 is_VBZ integrated_VVN across_RL and_CC within_II functional_JJ silos_NN2 ._. 
</s>
<s>
In_II 1992_MC SAP_NN1 introduced_VVD R/3_FU ,_, which_DDQ was_VBDZ based_VVN on_II an_AT1 open_JJ client-server_JJ architecture_NN1 ,_, enabling_VVG third-party_JJ companies_NN2 develop_VV0 software_NN1 that_CST could_VM be_VBI integrated_VVN and_CC different_JJ operating_NN1 systems_NN2 run_VV0 the_AT software_NN1 ._. 
</s>
<s>
The_AT Y2K_FO problem_NN1 ,_, later_RRR that_DD1 decade_NNT1 ,_, drove_VVD demand_NN1 of_IO ERP_NP1 high_RR as_RG many_DA2 companies_NN2 had_VHD to_TO change_VVI their_APPGE legacy_NN1 systems_NN2 to_II newer_JJR ones_NN2 ,_, which_DDQ were_VBDR Y2K_FO compliant_JJ ._. 
</s>
<s>
After_II 2000_MC and_CC its_APPGE dot_NN1 com_NN1 bubble_NN1 ,_, several_DA2 ERP_VV0 companies_NN2 merged_VVN and_CC in_II 2005_MC the_AT only_JJ major_JJ players_NN2 left_VVD were_VBDR SAP_NN1 and_CC Oracle_NN1 ._. 
</s>
<s>
The_AT present_JJ situation_NN1 of_IO ERP_NN1 is_VBZ marked_VVN by_II the_AT need_NN1 to_TO drive_VVI the_AT implementation_NN1 time_NNT1 down_RP to_II less_DAR than_CSN 6_MC months_NNT2 by_II having_VHG more_DAR specialized_VVN standard_JJ packages_NN2 available_JJ ._. 
</s>
<s>
Other_JJ trends_NN2 include_VV0 :_: ability_NN1 to_TO transmit_VVI data_NN in_II any_DD format_VV0 anywhere_RL in_II real-time_NN1 ,_, better_JJR simulation_NN1 capability_NN1 support_NN1 and_CC optimization_NN1 systems_NN2 ,_, consolidation_NN1 within_II the_AT ERP_NN1 industry_NN1 and_CC increased_JJ awareness_NN1 of_IO world_NN1 cultures_NN2 in_II the_AT design_NN1 of_IO ERP_NN1 systems_NN2 ._. 
</s>
<s>
&lsqb;_( Jacobs_NP2 and_CC Weston_NP1 Jr._NNA ,_, 2007_MC &rsqb;_) Next_MD some_DD statistics_NN about_II ERP_NP1 vendors_NN2 are_VBR presented_VVN ._. 
</s>
<s>
According_II21 to_II22 Pan_NP1 &lsqb;_( 2010a_FO &rsqb;_) ,_, in_II 2009_MC SAP_NN1 had_VHD 31%_NNU ,_, Oracle_NN1 had_VHD 25%_NNU and_CC MS_NNB Dynamics_NP1 had_VHD 15%_NNU of_IO the_AT total_JJ ERP_NN1 vendor_NN1 market_NN1 share_NN1 ._. 
</s>
<s>
35.5%_FO of_IO ERP_NN1 projects_NN2 took_VVD longer_RRR than_CSN planned_VVN and_CC 51.4%_FO went_VVD over_II the_AT budget_NN1 &lsqb;_( Pan_NP1 ,_, 2010a_FO &rsqb;_) ._. 
</s>
<s>
28.3%_FO of_IO the_AT companies_NN2 chose_VVD ERPs_NP2 without_IW customizations_NN2 ,_, whereas_CS 23.8%_FO chose_VVD "_" completely_RR customized_VVD "_" or_CC "_" heavily_RR customized_VVD "_" ERPs_NP2 &lsqb;_( Pan_NP1 ,_, 2010a_FO &rsqb;_) ._. 
</s>
<s>
Only_RR 12.4%_FO of_IO the_AT companies_NN2 were_VBDR "_" satisfied_JJ "_" or_CC "_" very_RG satisfied_JJ "_" with_IW their_APPGE selection_NN1 of_IO ERP_NP1 vendor_NN1 &lsqb;_( Pan_NP1 ,_, 2010a_FO &rsqb;_) ._. 
</s>
<s>
According_II21 to_II22 Pan_NP1 &lsqb;_( 2010b_FO &rsqb;_) ,_, the_AT geographical_JJ market_NN1 shares_NN2 are_VBR as_CSA follows_VVZ :_: North_ND1 America_NP1 31%_NNU ,_, Asia_NP1 Pacific_NP1 31%_NNU ,_, Europe_NP1 14%_NNU ,_, Africa_NP1 8%_NNU and_CC South_ND1 America_NP1 3%_NNU ._. 
</s>
<s>
The_AT study_NN1 concluded_VVN with_IW stating_VVG that_DD1 ERP_NN1 implementation_NN1 initiatives_NN2 are_VBR marked_VVN by_II five_MC issues_NN2 ,_, which_DDQ are_VBR :_: they_PPHS2 take_VV0 longer_RRR than_CSN expected_JJ and_CC are_VBR likewise_RR more_RGR costly_JJ ,_, they_PPHS2 under-deliver_VV0 business_NN1 value_NN1 ,_, software_NN1 as_II a_AT1 service_NN1 (_( SaaS_NP2 )_) take_VV0 less_DAR time_NNT1 than_CSN on-site_JJ ERP_NN1 implementation_NN1 while_CS contributing_VVG less_DAR business_NN1 value_NN1 and_CC last_VV0 that_CST organizations_NN2 do_VD0 not_XX effectively_RR take_VVI care_NN1 of_IO organizational_JJ changes_NN2 related_VVN to_II the_AT ERP_NN1 implementation_NN1 ._. 
</s>
<s>
Next_MD the_AT typical_JJ modules_NN2 and_CC categorization_NN1 of_IO ERP_NN1 is_VBZ presented_VVN ._. 
</s>
<s>
According_II21 to_II22 Rashid_NP1 ,_, Hossain_NN1 ,_, and_CC Patrick_NP1 &lsqb;_( 2002_MC &rsqb;_) typical_JJ ERP_NN1 modules_NN2 are_VBR :_: Accounting_VVG management_NN1 Financial_JJ management_NN1 Manufacturing_NN1 management_NN1 Production_NN1 management_NN1 Transportation_NN1 management_NN1 Sales_NN &;_NULL distribution_NN1 management_NN1 Human_NN1 resources_NN2 management_NN1 Supply_NN1 chain_NN1 management_NN1 Customer_NN1 relationship_NN1 management_NN1 E-Business_NP1 To_TO make_VVI ERPs_NN2 dynamic_JJ and_CC enable_VVI decentralization_NN1 ,_, typically_RR they_PPHS2 follow_VV0 a_AT1 client/server_NN1 architecture_NN1 ._. 
</s>
<s>
This_DD1 enables_VVZ splitting_VVG up_RP of_IO the_AT functionality_NN1 of_IO the_AT system_NN1 into_II a_AT1 presentation_NN1 layer_NN1 ,_, application_NN1 layer_NN1 and_CC a_AT1 database_NN1 layer_NN1 &lsqb;_( Rashid_NP1 et_RA21 al._RA22 ,_, 2002_MC &rsqb;_) ._. 
</s>
<s>
Practically_RR it_PPH1 means_VVZ that_CST each_DD1 layer_NN1 may_VM be_VBI served_VVN on_II virtually_RR or_CC physically_RR separate_JJ devices_NN2 ,_, allowing_VVG more_DAR flexibility_NN1 ._. 
</s>
<s>
One_MC1 study_NN1 &lsqb;_( Parr_NP1 and_CC Shanks_NN2 ,_, 2000_MC &rsqb;_) distinguishes_VVZ between_II three_MC types_NN2 of_IO ERP_NN1 implementations_NN2 ,_, based_VVN on_II the_AT physical_JJ scope_NN1 ,_, business_NN1 process_NN1 re-engineering_NN1 (_( BPR_NP1 )_) scope_NN1 ,_, resource_VV0 scope_NN1 ,_, time_NNT1 scope_NN1 and_CC technical_JJ scope_NN1 and_CC module_NN1 implementation_NN1 strategy_NN1 ._. 
</s>
<s>
The_AT ERP_NN1 implementation_NN1 types_NN2 are_VBR :_: "_" comprehensive_JJ "_" ,_, "_" middle_JJ road_NN1 "_" and_CC "_" vanilla_NN1 "_" ._. 
</s>
<s>
Comprehensive_JJ implementation_NN1 involves_VVZ multiple_JJ site_NN1 or_CC international_JJ implementation_NN1 ,_, local_JJ or_CC international_JJ BPR_NP1 ,_, minor_JJ or_CC major_JJ customization_NN1 ,_, broad_JJ module_NN1 implementation_NN1 ,_, time_NNT1 greater_JJR or_CC equal_JJ to_II four_MC years_NNT2 and_CC budget_VV0 greater_JJR or_CC equal_JJ to_II $10_NNU million_NNO ._. 
</s>
<s>
Middle-road_JJ implementation_NN1 differs_VVZ from_II the_AT previous_JJ by_II including_VVG single_JJ ,_, rather_II21 than_II22 international_JJ implementation_NN1 ,_, BPR_NP1 alignment_NN1 to_TO ERP_VVI rather_II21 than_II22 international_JJ BPR_NP1 ,_, not_XX including_II industry_NN1 specific_JJ module_NN1 implementation_NN1 and_CC having_VHG a_AT1 time_NNT1 budget_NN1 of_IO over_RG a_AT1 year_NNT1 and_CC a_AT1 monetary_JJ budget_NN1 greater_JJR or_CC equal_JJ to_II $3_NNU million_NNO ._. 
</s>
<s>
Vanilla_NN1 implementation_NN1 only_RR includes_VVZ single_JJ implementation_NN1 ,_, BPR_NP1 alignment_NN1 to_TO ERP_VVI ,_, minute_JJ modification_NN1 or_CC ERP_NP1 and_CC a_AT1 similar_JJ module_NN1 implementation_NN1 strategy_NN1 as_CSA middle-road_JJ ._. 
</s>
<s>
The_AT time_NNT1 scope_NN1 of_IO vanilla_NN1 is_VBZ half_DB to_II one_MC1 year_NNT1 and_CC the_AT monetary_JJ budget_NN1 is_VBZ between_II one_MC1 and_CC two_MC million_NNO USD_NN1 ._. 
</s>
<s>
&lsqb;_( Parr_NN1 and_CC Shanks_NN2 ,_, 2000_MC &rsqb;_) The_AT descriptions_NN2 of_IO this_DD1 chapter_NN1 shows_VVZ some_DD statistics_NN of_IO ERP_NP1 vendor_NN1 market_NN1 shares_NN2 and_CC geographical_JJ distribution_NN1 ._. 
</s>
<s>
Also_RR modules_NN2 and_CC categorization_NN1 of_IO ERPs_NP2 were_VBDR presented_VVN ._. 
</s>
<s>
The_AT rest_NN1 of_IO the_AT paper_NN1 focuses_VVZ on_II vanilla_NN1 ERP_NN1 implementation_NN1 solely_RR ,_, because_CS it_PPH1 is_VBZ the_AT category_NN1 that_CST fits_VVZ best_JJT SMEs._NP1 3_MC Open_JJ Source_NN1 ERP_VV0 This_DD1 chapter_NN1 describes_VVZ how_RRQ open_JJ source_NN1 ERPs_NN2 differ_VV0 from_II proprietary_JJ ERPs_NN2 ._. 
</s>
<s>
According_II21 to_II22 OS2_FO a_AT1 software_NN1 is_VBZ open_JJ source_NN1 if_CS it_PPH1 conforms_VVZ with_IW the_AT following_JJ criteria_NN2 :_: 1_MC1 ._. 
</s>
<s>
Redistribution_NN1 must_VM be_VBI unregulated_JJ 2_MC ._. 
</s>
<s>
The_AT source_NN1 code_NN1 must_VM be_VBI accessible_JJ 3_MC ._. 
</s>
<s>
The_AT source_NN1 code_NN1 can_VM be_VBI modified_VVN and_CC so_RR under_II the_AT same_DA license_NN1 as_CSA the_AT original_JJ 4_MC ._. 
</s>
<s>
The_AT author_NN1 might_VM require_VVI that_CST the_AT original_JJ source_NN1 code_NN1 be_VBI not_XX edited_VVN ,_, but_CCB rather_RR allow_VV0 modifications_NN2 through_II distribution_NN1 of_IO patches_NN2 that_CST make_VV0 the_AT software_NN1 functionally_RR different_JJ ._. 
</s>
<s>
The_AT author_NN1 can_VM require_VVI that_CST the_AT derived_JJ softwares_NN2 use_VV0 different_JJ names_NN2 than_CSN the_AT original._NNU 5_MC ._. 
</s>
<s>
"_" No_AT Discrimination_NN1 Against_II Persons_NN2 or_CC Groups_NN2 "_" 6_MC ._. 
</s>
<s>
"_" No_AT Discrimination_NN1 Against_II Fields_NN2 of_IO Endeavor_NP1 "_" 7_MC ._. 
</s>
<s>
The_AT rights_NN2 stated_VVN in_II the_AT license_NN1 of_IO the_AT software_NN1 applies_VVZ to_II all_DB who_PNQS acquire_VV0 the_AT software_NN1 8_MC ._. 
</s>
<s>
"_" License_NN1 Must_VM Not_XX Be_VBI Specific_JJ to_II a_AT1 Product_NN1 "_" 9_MC ._. 
</s>
<s>
"_" License_NN1 Must_VM Not_XX Restrict_VV0 Other_JJ Software_NN1 "_" 10_MC ._. 
</s>
<s>
"_" License_NN1 Must_VM Be_VBI Technology-Neutral_JJ "_" Thus_RR software_NN1 which_DDQ is_VBZ not_XX open_JJ source_NN1 might_VM brake_VVI one_MC1 or_CC more_DAR of_IO the_AT rules_NN2 ._. 
</s>
<s>
Two_MC obvious_JJ benefits_NN2 are_VBR that_RG open_JJ source_NN1 software_NN1 is_VBZ free_JJ and_CC open_VV0 ,_, which_DDQ implies_VVZ savings_NN2 through_II lower_JJR spendings_NN2 and_CC ability_NN1 to_TO modify_VVI the_AT software_NN1 at_II will_NN1 ._. 
</s>
<s>
Thus_RR it_PPH1 is_VBZ especially_RR suitable_JJ for_IF SMEs_NN2 ,_, which_DDQ can_VM not_XX necessarily_RR afford_VVI expensive_JJ proprietary_JJ ERPs_NN2 ._. 
</s>
<s>
According_II21 to_II22 Riehle_NP1 &lsqb;_( 2007_MC &rsqb;_) there_EX are_VBR two_MC types_NN2 of_IO open_JJ source_NN1 :_: community_NN1 developed_VVN and_CC commercial_JJ ._. 
</s>
<s>
The_AT main_JJ difference_NN1 between_II these_DD2 is_VBZ that_CST the_AT commercial_NN1 is_VBZ owned_VVN by_II a_AT1 company_NN1 which_DDQ maintains_VVZ a_AT1 copyright_NN1 ,_, whereas_CS community_NN1 developed_JJ software_NN1 is_VBZ controlled_VVN by_II the_AT community_NN1 ._. 
</s>
<s>
Company_NN1 ruled_VVD open_JJ source_NN1 software_NN1 is_VBZ typically_RR free_JJ for_IF nonprofit_JJ users_NN2 and_CC might_VM be_VBI free_JJ for_IF profit_NN1 purposes_NN2 ._. 
</s>
<s>
The_AT main_JJ source_NN1 of_IO revenue_NN1 for_IF commercial_JJ open_JJ source_NN1 business_NN1 models_NN2 is_VBZ the_AT selling_NN1 of_IO support_NN1 services_NN2 and_CC software_NN1 add-ons_NN2 ._. 
</s>
<s>
The_AT conclusion_NN1 is_VBZ that_DD1 community_NN1 developed_VVD open_JJ source_NN1 ERP_NN1 is_VBZ definitely_RR free_JJ in_II every_AT1 sense_NN1 ,_, whereas_CS commercial_JJ open_JJ source_NN1 ERPs_NN2 might_VM be_VBI free_JJ ._. 
</s>
<s>
Summary_NN1 comes_VVZ here._NNU 4_MC ERP_NP1 LCM_NP1 This_DD1 section_NN1 describes_VVZ the_AT life_NN1 cycle_NN1 management_NN1 of_IO ERPs_NP2 ,_, including_II what_DDQ the_AT phases_NN2 are_VBR ,_, how_RRQ they_PPHS2 are_VBR categorized_VVN ,_, what_DDQ they_PPHS2 include_VV0 and_CC how_RRQ you_PPY manage_VV0 them_PPHO2 ._. 
</s>
<s>
Summary_NN1 comes_VVZ here._NNU 5_MC Open_JJ Source_NN1 ERP_NP1 LCM_NP1 Summary_NN1 comes_VVZ here._NNU 6_MC Open_JJ Source_NN1 ERP_NN1 Review_NN1 This_DD1 section_NN1 will_VM review_VVI existing_JJ open_JJ source_NN1 ERP_NN1 based_VVN on_II the_AT literature_NN1 review_NN1 and_CC will_VM try_VVI to_TO suggest_VVI a_AT1 method_NN1 to_II chose_VVD a_AT1 suitable_JJ open_JJ source_NN1 ERP_NN1 ._. 
</s>
<s>
Summary_NN1 comes_VVZ here._NNU 7_MC Contribution_NN1 This_DD1 section_NN1 describes_VVZ the_AT contribution_NN1 of_IO the_AT paper_NN1 ._. 
</s>
<s>
Summary_NN1 comes_VVZ here._NNU 8_MC Limitations_NN2 and_CC Conclusions_NN2 Here_RL the_AT limitations_NN2 (_( counter_VV0 arguments_NN2 and_CC rebuttal_NN1 )_) ,_, conclusions_NN2 and_CC future_JJ research_NN1 are_VBR presented_VVN ._. 
</s>
