<s>
Determinants_NN2 that_CST affect_VV0 the_AT Asset_NN1 Backed_VVD Security_NN1 (_( ABS_JJ )_) spread_VVD 1_MC1 ._. 
</s>
<s>
Introduction_NN1 The_AT importance_NN1 of_IO derivatives_NN2 has_VHZ grown_VVN enormously_RR during_II the_AT 21st_MD century_NNT1 ._. 
</s>
<s>
The_AT growth_NN1 of_IO the_AT past_JJ decade_NNT1 has_VHZ been_VBN relatively_RR dynamic_JJ and_CC the_AT derivative_JJ market_NN1 has_VHZ become_VVN a_AT1 trillion_NNO dollar_NNU1 business_NN1 ._. 
</s>
<s>
Because_II21 of_II22 derivatives_NN2 ,_, companies_NN2 have_VH0 an_AT1 opportunity_NN1 to_TO hedge_VVI themselves_PPX2 against_II price_NN1 fluctuation_NN1 in_II commodities_NN2 like_II oil_NN1 or_CC cotton_NN1 ._. 
</s>
<s>
By_II taking_VVG for_REX21 example_REX22 a_AT1 short_JJ position_NN1 in_II oil_NN1 ,_, a_AT1 company_NN1 like_II Fortum_NP1 or_CC Shell_NN1 can_VM hedge_VVI itself_PPX1 against_II a_AT1 possible_JJ drop_NN1 in_II the_AT oil_NN1 price_NN1 ._. 
</s>
<s>
This_DD1 possibility_NN1 gives_VVZ companies_NN2 an_AT1 ability_NN1 to_TO secure_VVI themselves_PPX2 against_II price_NN1 fluctuations_NN2 and_CC therefore_RR make_VV0 their_APPGE economic_JJ activity_NN1 more_RGR stable_JJ (_( Carter_NP1 ,_, Roger_NP1 &;_NULL Simkins_NP1 :_: 2006_MC )_) ._. 
</s>
<s>
The_AT financial_JJ crisis_NN1 has_VHZ brought_VVN forward_RL a_AT1 new_JJ topic_NN1 :_: securitization_NN1 ._. 
</s>
<s>
It_PPH1 has_VHZ been_VBN one_MC1 of_IO the_AT many_DA2 causes_NN2 for_IF the_AT emergence_NN1 of_IO the_AT financial_JJ crisis_NN1 -_- which_DDQ many_DA2 economists_NN2 have_VH0 said_VVN to_TO be_VBI the_AT biggest_JJT economic_JJ crisis_NN1 this_DD1 planet_NN1 has_VHZ seen_VVN since_CS the_AT stock_NN1 market_NN1 crash_NN1 in_II 1929_MC ._. 
</s>
<s>
Securitization_NN1 involves_VVZ basically_RR three_MC parties_NN2 ;_; lenders_NN2 ,_, borrowers_NN2 and_CC a_AT1 financial_JJ institution_NN1 that_CST acts_VVZ as_II an_AT1 intermediary_NN1 ._. 
</s>
<s>
One_MC1 type_NN1 of_IO these_DD2 derivatives_NN2 that_CST pool_VV0 the_AT borrowing_NN1 entities_NN2 together_RL are_VBR Asset_NN1 Backed_VVD Securities_NN2 (_( ABS_JJ )_) ._. 
</s>
<s>
An_AT1 ABS_JJ combines_VVZ many_DA2 investors_NN2 into_II a_AT1 pool_NN1 and_CC therefore_RR ,_, together_RL with_IW the_AT acting_JJ intermediary_NN1 ,_, makes_VVZ the_AT investment_NN1 more_RRR diversified_VVN and_CC resistant_JJ to_II defaults_NN2 ._. 
</s>
<s>
The_AT lending_NN1 party_NN1 acts_VVZ also_RR as_II a_AT1 pool_NN1 and_CC makes_VVZ it_PPH1 possible_JJ for_IF the_AT intermediary_NN1 to_TO issue_VVI large_JJ amounts_NN2 of_IO loans_NN2 ._. 
</s>
<s>
The_AT academic_JJ field_NN1 has_VHZ nt_XX been_VBN very_RG active_JJ studying_VVG the_AT topic_NN1 ABS_JJ that_RG much_DA1 and_CC therefore_RR it_PPH1 is_VBZ a_AT1 very_RG interesting_JJ topic_NN1 to_TO study_VVI ._. 
</s>
<s>
Firstly_RR ,_, ABS_JJ was_VBDZ a_AT1 very_RG focal_JJ security_NN1 during_II the_AT financial_JJ crisis_NN1 ;_; the_AT way_NN1 in_II which_DDQ assets_NN2 were_VBDR bundled_VVN was_VBDZ one_MC1 of_IO the_AT reasons_NN2 why_RRQ the_AT market_NN1 crashed_VVD ._. 
</s>
<s>
Secondly_RR ,_, investors_NN2 do_VD0 nt_XX generally_RR know_VVI what_DDQ the_AT determinants_NN2 are_VBR that_CST influence_VV0 the_AT ABS_JJ rate_NN1 of_IO return_NN1 ._. 
</s>
<s>
Similar_JJ studies_NN2 have_VH0 been_VBN conducted_VVN widely_RR in_II the_AT corporate_JJ bond_NN1 market_NN1 but_CCB not_XX many_DA2 which_DDQ are_VBR contemplating_VVG ABS_JJ ._. 
</s>
<s>
However_RR ,_, there_EX are_VBR some_DD previous_JJ studies_NN2 that_CST show_VV0 that_CST different_JJ macroeconomic_JJ variables_NN2 have_VH0 a_AT1 fairly_RR high_JJ correlation_NN1 with_IW price_NN1 fluctuation_NN1 on_II ABS_JJ spreads_NN2 ._. 
</s>
<s>
This_DD1 study_NN1 will_VM focus_VVI on_II Asset_NN1 Backed_VVD Securities_NN2 and_CC what_DDQ determinants_NN2 have_VH0 affected_VVN its_APPGE price_NN1 movement_NN1 during_II the_AT financial_JJ crises_NN2 ._. 
</s>
<s>
2_MC ._. 
</s>
<s>
Theoretical_JJ framework_NN1 This_DD1 section_NN1 of_IO the_AT paper_NN1 will_VM compile_VVI the_AT most_RGT important_JJ theory_NN1 that_CST is_VBZ needed_VVN to_TO understand_VVI the_AT topic_NN1 about_II securitization_NN1 and_CC the_AT pooling_NN1 of_IO assets_NN2 in_II Asset_NN1 Backed_VVD Securities_NN2 ._. 
</s>
<s>
2.1_MC ._. 
</s>
<s>
Securitization_NN1 Securitization_NN1 is_VBZ a_AT1 type_NN1 of_IO tool_NN1 where_RRQ assets_NN2 are_VBR gathered_VVN to_II a_AT1 common_JJ pool_NN1 ._. 
</s>
<s>
Financial_JJ intermediaries_NN2 ,_, such_II21 as_II22 banks_NN2 ,_, use_VV0 securitization_NN1 to_II pool_NN1 together_RL ,_, or_CC in_II other_JJ words_NN2 buy_VV0 ,_, assets_NN2 and_CC after_RT that_CST sell_VV0 them_PPHO2 forward_RL to_II the_AT public_NN1 against_II a_AT1 premium_NN1 ._. 
</s>
<s>
These_DD2 assets_NN2 can_VM be_VBI categorized_VVN into_II many_DA2 different_JJ asset_NN1 classes_NN2 such_II21 as_II22 Mortgage_NN1 Backed_VVD Securities_NN2 (_( MBOs_NP2 )_) ,_, Credit_NN1 Default_NN1 Obligations_NN2 (_( CDOs_NP2 )_) and_CC Asset_NN1 Backed_VVD Securities_NN2 (_( ABSs_NP1 )_) ._. 
</s>
<s>
The_AT first_MD two_MC mentioned_VVN derive_VV0 their_APPGE value_NN1 from_II mortgage_NN1 loans_NN2 ,_, i.e._REX those_DD2 assets_NN2 that_CST the_AT intermediary_NN1 buys_NN2 and_CC sells_VVZ forward_RL ._. 
</s>
<s>
This_DD1 paper_NN1 focuses_VVZ on_II ABSs_NN1 which_DDQ consist_VV0 of_IO a_AT1 pool_NN1 of_IO consumption_NN1 base_NN1 assets_NN2 ,_, e.g._REX car_NN1 loans_NN2 ,_, consumption_NN1 loans_NN2 and_CC credit_NN1 card_NN1 loans_NN2 ._. 
</s>
<s>
The_AT figure_NN1 bellow_NN1 illustrates_VVZ how_RRQ the_AT concept_NN1 of_IO securitization_NN1 of_IO ABSs_NP1 works_VVZ :_: &lsqb;_( Figure_NN1 &rsqb;_) The_AT so_JJ21 called_JJ22 borrower_NN1 borrows_VVZ assets_NN2 to_II the_AT investor_NN1 which_DDQ in_II this_DD1 case_NN1 can_VM be_VBI an_AT1 individual_JJ or_CC a_AT1 company_NN1 which_DDQ has_VHZ for_REX21 example_REX22 a_AT1 credit_NN1 card_NN1 or_CC wants_VVZ to_TO take_VVI a_AT1 car_NN1 loan_NN1 ._. 
</s>
<s>
The_AT borrower_NN1 finances_NN2 this_DD1 procedure_NN1 by_II issuing_JJ debt_NN1 to_II the_AT entity_NN1 called_VVN the_AT originator_NN1 ._. 
</s>
<s>
When_CS a_AT1 pool_NN1 of_IO assets_NN2 is_VBZ gathered_VVN the_AT borrower_NN1 sells_VVZ this_DD1 pool_NN1 of_IO assets_NN2 to_II a_AT1 Special_JJ Purpose_NN1 Vehicle_NN1 (_( SPV_NP1 )_) ._. 
</s>
<s>
The_AT assets_NN2 are_VBR transferred_VVN to_II the_AT SPV_NP1 because_CS if_CS the_AT investor_NN1 ,_, which_DDQ has_VHZ a_AT1 liability_NN1 to_II the_AT SPV_NP1 and_CC furthermore_RR to_II the_AT originator_NN1 ,_, files_NN2 bankruptcy_NN1 the_AT borrower_NN1 is_VBZ not_XX directly_RR responsible_JJ to_II the_AT originator_NN1 ._. 
</s>
<s>
The_AT SPV_NP1 is_VBZ said_VVN to_TO be_VBI bankruptcy_NN1 remote_JJ which_DDQ means_VVZ that_CST if_CS the_AT investor_NN1 defaults_VVZ the_AT SPV_NP1 does_VDZ nt_XX have_VHI to_TO pay_VVI the_AT originator_NN1 any_DD kind_NN1 of_IO compensation_NN1 ._. 
</s>
<s>
As_CSA already_RR mentioned_VVD the_AT financial_JJ intermediary_NN1 pools_NN2 these_DD2 assets_NN2 together_RL which_DDQ is_VBZ important_JJ because_CS then_RT the_AT investor_NN1 and_CC originator_NN1 do_VD0 nt_XX have_VHI to_TO find_VVI themselves_PPX2 at_II the_AT market_NN1 ._. 
</s>
<s>
Upon_II that_DD1 if_CS there_EX wouldnt_NN1 be_VBI any_DD intermediary_NN1 either_DD1 of_IO the_AT parties_NN2 would_VM have_VHI to_TO find_VVI an_AT1 opposite_JJ part_NN1 that_CST matches_VVZ the_AT exact_JJ same_DA needs_NN2 ,_, i.e._REX the_AT same_DA amount_NN1 of_IO borrowing_NN1 or_CC lending_NN1 and_CC a_AT1 contract_NN1 that_CST has_VHZ for_REX21 example_REX22 the_AT same_DA type_NN1 of_IO interest_NN1 rate_NN1 ._. 
</s>
<s>
2.2_MC ._. 
</s>
<s>
Tranches_NN2 The_AT originator_NN1 can_VM invest_VVI in_II different_JJ tranches_NN2 in_II these_DD2 ABS_JJ pools_NN2 ._. 
</s>
<s>
When_CS for_REX21 example_REX22 a_AT1 car_NN1 loan_NN1 is_VBZ issued_VVN the_AT credit_NN1 rating_NN1 of_IO the_AT investor_NN1 is_VBZ measured_VVN every_AT1 time_NNT1 to_TO make_VVI an_AT1 estimate_NN1 what_DDQ the_AT possibility_NN1 of_IO a_AT1 default_NN1 is_VBZ ._. 
</s>
<s>
Standard_JJ &;_NULL Poors_NN2 (_( S_ZZ1 &P),;_NULL which_DDQ is_VBZ a_AT1 financial_JJ service_NN1 company_NN1 all_DB around_II the_AT world_NN1 ,_, provides_VVZ credit_NN1 ratings_NN2 mostly_RR for_IF companies_NN2 ._. 
</s>
<s>
The_AT ratings_NN2 can_VM though_RR be_VBI applied_VVN for_IF anyone_PN1 who_PNQS is_VBZ granted_VVN any_DD type_NN1 of_IO a_AT1 loan_NN1 ._. 
</s>
<s>
The_AT S_NP1 &P;_NULL credit_NN1 rating_NN1 scale_NN1 ranges_VVZ from_II AAA_NP1 to_II as_RG low_JJ as_CSA D_ZZ1 ,_, i.e._REX the_AT first_MD mentioned_VVN being_VBG the_AT best_JJT possible_JJ rating_NN1 (_( less_RGR likely_JJ to_TO default_VVI )_) and_CC the_AT second_MD mentioned_VVD almost_RR certain_JJ of_IO default_NN1 ._. 
</s>
<s>
These_DD2 tranches_NN2 were_VBDR built_VVN upon_II these_DD2 verities_NN2 of_IO credit_NN1 ratings_NN2 which_DDQ the_AT originators_NN2 invested_VVD in_RP ._. 
</s>
<s>
In_II this_DD1 process_NN1 the_AT assets_NN2 that_CST had_VHD the_AT best_JJT possible_JJ ratings_NN2 contained_VVD less_DAR risk_NN1 than_CSN the_AT assets_NN2 that_CST were_VBDR categorized_VVN as_CSA investment_NN1 grade_NN1 ,_, ._. i.e._REX those_DD2 assets_NN2 with_IW the_AT worst_JJT credit_NN1 rating_NN1 ._. 
</s>
<s>
The_AT choice_NN1 that_CST the_AT investor_NN1 must_VM make_VVI is_VBZ what_DDQ kind_NN1 of_IO a_AT1 risk-return_NN1 relation_NN1 is_VBZ suitable_JJ ._. 
</s>
<s>
The_AT best_JJT possible_JJ ratings_NN2 contain_VV0 least_DAT risk_NN1 but_CCB offer_VV0 on_II the_AT other_JJ hand_NN1 lower_JJR yields_NN2 (_( interest_NN1 rates_NN2 )_) than_CSN the_AT investment_NN1 grade_NN1 assets_NN2 ._. 
</s>
<s>
2.3_MC ._. 
</s>
<s>
Advantages_NN2 and_CC disadvantages_NN2 of_IO the_AT securitization_NN1 process_VV0 The_AT whole_JJ securitization_NN1 process_NN1 has_VHZ a_AT1 great_JJ impact_NN1 on_II how_RRQ liquid_NN1 the_AT assets_NN2 of_IO the_AT ABS_JJ are_VBR for_IF the_AT investor_NN1 and_CC the_AT originator_NN1 part_NN1 ._. 
</s>
<s>
The_AT investors_NN2 (_( originators_NN2 )_) have_VH0 an_AT1 opportunity_NN1 to_TO earn_VVI a_AT1 higher_JJR rate_NN1 of_IO return_NN1 on_II their_APPGE investment_NN1 than_CSN if_CS they_PPHS2 would_VM go_VVI directly_RR to_II the_AT market_NN1 ._. 
</s>
<s>
The_AT different_JJ ABS_JJ pools_NN2 make_VV0 it_PPH1 possible_JJ for_IF the_AT investor_NN1 to_TO freely_RR choose_VVI what_DDQ kind_NN1 of_IO a_AT1 risk-return_NN1 level_NN1 is_VBZ suitable_JJ ._. 
</s>
<s>
Furthermore_RR ,_, the_AT investor_NN1 can_VM choose_VVI what_DDQ asset_NN1 type_NN1 is_VBZ the_AT appropriate_JJ one_PN1 to_TO invest_VVI in_RP ._. 
</s>
<s>
The_AT issuer_NN1 has_VHZ a_AT1 very_RG central_JJ role_NN1 in_II the_AT process_NN1 and_CC therefore_RR the_AT ground_NN1 rules_NN2 are_VBR more_RGR or_CC less_RRR done_VDN by_II it_PPH1 ._. 
</s>
<s>
The_AT profit_NN1 margin_NN1 (_( premium_NN1 )_) can_VM be_VBI fairly_RR easily_RR altered_VVN by_II the_AT issuer_NN1 while_CS it_PPH1 is_VBZ the_AT one_PN1 who_PNQS borrows_VVZ the_AT assets_NN2 from_II the_AT originator_NN1 and_CC issues_NN2 debt_NN1 to_II the_AT investors_NN2 who_PNQS have_VH0 a_AT1 liability_NN1 to_II the_AT issuer_NN1 ._. 
</s>
<s>
The_AT originator_NN1 carries_VVZ less_DAR risk_NN1 because_CS it_PPH1 basically_RR transfers_VVZ the_AT risk_NN1 from_II one_MC1 party_NN1 to_II the_AT other_JJ ._. 
</s>
<s>
This_DD1 requires_VVZ a_AT1 lower_JJR amount_NN1 of_IO equity_NN1 invested_VVN in_II the_AT company_NN1 ,_, i.e._REX assets_NN2 that_CST are_VBR bound_VVNK to_TO be_VBI able_JK to_TO be_VBI an_AT1 intermediary_NN1 which_DDQ borrows_VVZ and_CC sells_VVZ assets_NN2 ._. 
</s>
<s>
The_AT securitization_NN1 advantage_NN1 lies_VVZ also_RR in_II the_AT fact_NN1 that_CST while_CS the_AT intermediary_NN1 can_VM sell_VVI the_AT assets_NN2 to_II the_AT SPV_NP1 the_AT asset_NN1 is_VBZ off_II the_AT intermediarys_NN2 balance_NN1 sheet_NN1 which_DDQ enables_VVZ it_PPH1 to_TO lend_VVI at_II a_AT1 lower_JJR rate_NN1 of_IO return_NN1 ._. 
</s>
<s>
This_DD1 gives_VVZ a_AT1 cost_NN1 saving_NN1 edge_NN1 ._. 
</s>
<s>
For_IF all_DB the_AT three_MC groups_NN2 one_MC1 ground_NN1 rule_NN1 applies_VVZ ;_; all_DB the_AT assets_NN2 are_VBR diversified_VVN which_DDQ lowers_VVZ the_AT systematic_JJ risk_NN1 involved_JJ in_II the_AT investment_NN1 ._. 
</s>
<s>
2.4_MC ._. 
</s>
<s>
The_AT ABS_JJ spread_NN1 The_AT ABS_JJ spread_NN1 is_VBZ defined_VVN as_CSA follows_VVZ ._. 
</s>
<s>
It_PPH1 is_VBZ the_AT spread_NN1 between_II the_AT interest_NN1 rate_NN1 of_IO the_AT specific_JJ ABS_JJ security_NN1 and_CC a_AT1 risk-free_JJ interest_NN1 rate_NN1 ._. 
</s>
<s>
The_AT risk-free_JJ interest_NN1 rate_NN1 is_VBZ usually_RR categorized_VVN as_II the_AT 3_MC month_NNT1 t-bill_JJ rate_NN1 in_II the_AT United_NP1 States_NP1 ._. 
</s>
<s>
(_( Vink_VV0 &;_NULL Thibeault:2008_FO )_) 3_MC ._. 
</s>
<s>
The_AT financial_JJ crisis_NN1 perspective_NN1 During_II the_AT financial_JJ crisis_NN1 these_DD2 securities_NN2 played_VVD an_AT1 important_JJ role_NN1 while_CS the_AT mortgage_NN1 market_NN1 bubble_NN1 burst_VVN in_II the_AT United_NP1 States_NP1 ._. 
</s>
<s>
President_NNB George_NP1 Bushs_NP2 intention_NN1 was_VBDZ that_CST every_AT1 American_NN1 should_VM be_VBI able_JK to_TO afford_VVI an_AT1 apartment_NN1 and_CC therefore_RR mortgage_NN1 loans_NN2 were_VBDR issued_VVN to_II people_NN that_CST did_VDD nt_XX have_VHI the_AT opportunity_NN1 to_TO do_VDI it_PPH1 before_RT ._. 
</s>
<s>
The_AT interest_NN1 rates_NN2 on_II these_DD2 loans_NN2 were_VBDR in_II some_DD cases_NN2 extremely_RR high_JJ and_CC the_AT total_JJ amount_NN1 of_IO loan_NN1 was_VBDZ on_II average_NN1 fairly_RR big_JJ compared_VVN to_II the_AT salary_NN1 level_NN1 of_IO the_AT borrower_NN1 ._. 
</s>
<s>
When_CS the_AT market_NN1 crashed_VVD the_AT value_NN1 of_IO the_AT houses_NN2 fell_VVD to_II a_AT1 level_NN1 that_CST was_VBDZ fateful_JJ to_II many_DA2 holders_NN2 of_IO a_AT1 mortgage_NN1 loan_NN1 ._. 
</s>
<s>
The_AT value_NN1 of_IO the_AT mortgage_NN1 loan_NN1 remained_VVD the_AT same_DA while_CS the_AT price_NN1 of_IO the_AT house_NN1 depreciated_VVD drastically_RR ._. 
</s>
<s>
This_DD1 phenomenon_NN1 had_VHD a_AT1 fateful_JJ effect_NN1 financially_RR on_II many_DA2 holders_NN2 of_IO a_AT1 mortgage_NN1 loan_NN1 which_DDQ furthermore_RR had_VHN an_AT1 effect_NN1 on_II the_AT financial_JJ intermediary_NN1 and_CC the_AT investor_NN1 in_II the_AT pool_NN1 of_IO mortgages_NN2 which_DDQ were_VBDR involved_JJ in_II the_AT process_NN1 of_IO securitization_NN1 ._. 
</s>
<s>
The_AT securitization_NN1 process_NN1 described_VVN above_RL involved_VVD securities_NN2 which_DDQ were_VBDR belong_VV0 to_II the_AT classes_NN2 of_IO MBS_NNU2 and_CC CDO_NP1 ._. 
</s>
<s>
This_DD1 had_VHD of_RR21 course_RR22 also_RR an_AT1 immediate_JJ effect_NN1 on_II ABS_JJ ._. 
</s>
<s>
If_CS people_NN (_( the_AT borrowers_NN2 )_) that_CST had_VHD a_AT1 mortgage_NN1 loan_NN1 had_VHD difficulties_NN2 in_II making_VVG loan_NN1 amortizations_NN2 had_VHD also_RR major_JJ difficulties_NN2 in_II paying_VVG back_RP their_APPGE credit_NN1 card_NN1 bill(s)_NN2 ,_, car_NN1 loan_NN1 and_CC consumption_NN1 loan_NN1 ._. 
</s>
<s>
When_CS the_AT borrowers_NN2 couldnt_VV0 pay_VV0 their_APPGE mortgage_NN1 loans_NN2 any_DD more_DAR the_AT financial_JJ intermediaries_NN2 alongside_RL with_IW the_AT investors_NN2 found_VVD themselves_PPX2 in_II a_AT1 situation_NN1 where_RRQ their_APPGE investments_NN2 had_VHD dropped_VVN in_II value_NN1 dramatically_RR ._. 
</s>
<s>
Only_RR those_DD2 investors_NN2 that_CST belonged_VVD to_II the_AT group_NN1 which_DDQ were_VBDR in_II a_AT1 higher_JJR trench_NN1 group_NN1 ,_, i.e._REX had_VHD a_AT1 higher_JJR credit_NN1 rating_NN1 ,_, got_VVD a_AT1 fairly_RR high_JJ amount_NN1 of_IO their_APPGE money_NN1 back_NN1 ._. 
</s>
<s>
4_MC ._. 
</s>
<s>
Previous_JJ research_NN1 The_AT previous_JJ research_NN1 has_VHZ found_VVN different_JJ factors_NN2 involved_JJ in_II the_AT securitization_NN1 process_VV0 that_CST have_VH0 a_AT1 correlation_NN1 with_IW the_AT ABS_JJ spread_NN1 (_( definition_NN1 of_IO ABS_JJ spread_NN1 see_VV0 section_NN1 2.4_MC ._. )_) ._. 
</s>
<s>
In_II other_JJ words_NN2 these_DD2 factors_NN2 have_VH0 been_VBN seen_VVN to_TO have_VHI a_AT1 correlation_NN1 ,_, i.e._REX similar_JJ behavior_NN1 ,_, with_IW the_AT average_JJ spread_NN1 of_IO the_AT ABS_JJ ._. 
</s>
<s>
This_DD1 paper_NN1 focuses_VVZ mostly_RR on_II the_AT article_NN1 written_VVN by_II Vink_NP1 &;_NULL Thibeault_NP1 (_( 2008_MC )_) where_CS they_PPHS2 determine_VV0 factors_NN2 that_CST could_VM have_VHI an_AT1 effect_NN1 on_II the_AT ABS_JJ spread_NN1 ._. 
</s>
<s>
They_PPHS2 use_VV0 a_AT1 multiple_JJ regression_NN1 model_NN1 which_DDQ can_VM be_VBI seen_VVN in_II the_AT figure_NN1 below_RL ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) The_AT ABS_JJ spread_NN1 can_VM be_VBI seen_VVN as_II a_AT1 control_NN1 variable_NN1 on_II the_AT left-hand_JJ side_NN1 of_IO the_AT equation_NN1 while_CS all_DB the_AT explanatory_JJ variables_NN2 can_VM be_VBI seen_VVN on_II the_AT right-hand_JJ side_NN1 ._. 
</s>
<s>
All_DB these_DD2 explanatory_JJ variables_NN2 try_VV0 to_TO explain_VVI why_RRQ the_AT ABS_JJ spread_NN1 is_VBZ behaving_VVG as_CSA it_PPH1 is_VBZ behaving_VVG ._. 
</s>
<s>
4.1_MC ._. 
</s>
<s>
Results_NN2 of_IO the_AT previous_JJ research_NN1 The_AT results_NN2 which_DDQ were_VBDR obtained_VVN from_II the_AT study_NN1 by_II Vink_NP1 &;_NULL Thibeault_NP1 (_( 2008_MC )_) were_VBDR quite_RG interesting_JJ ._. 
</s>
<s>
Some_DD of_IO the_AT factors_NN2 had_VHD and_CC extremely_RR high_JJ correlation_NN1 with_IW the_AT ABS_JJ spread_NN1 while_CS others_NN2 couldnt_VV0 explain_VV0 why_RRQ the_AT spread_NN1 is_VBZ behaving_VVG as_CSA it_PPH1 is_VBZ behaving_VVG ._. 
</s>
<s>
According_II21 to_II22 Vink_NP1 &;_NULL Thibeault_NP1 (_( 2008_MC )_) credit_NN1 rating_NN1 has_VHZ a_AT1 major_JJ effect_NN1 on_II the_AT magnitude_NN1 of_IO the_AT ABS_JJ spread_NN1 ._. 
</s>
<s>
Almost_RR every_AT1 credit_NN1 rating_NN1 class_NN1 had_VHD a_AT1 statistically_RR significant_JJ relationship_NN1 with_IW the_AT ABS_JJ spread_NN1 ._. 
</s>
<s>
The_AT transaction_NN1 size_NN1 had_VHD also_RR a_AT1 fairly_RR good_JJ explanatory_JJ power_NN1 in_II explaining_VVG the_AT ABS_JJ spread_NN1 ._. 
</s>
<s>
The_AT larger_JJR the_AT transaction_NN1 size_NN1 the_AT higher_JJR the_AT spread_NN1 also_RR becomes_VVZ while_CS the_AT risk_NN1 on_II larger_JJR transactions_NN2 are_VBR higher_JJR ._. 
</s>
<s>
Maturity_NN1 could_VM explain_VVI also_RR the_AT ABS_JJ spread_NN1 in_II a_AT1 fairly_RR good_JJ manner_NN1 ._. 
</s>
<s>
The_AT longer_JJR the_AT maturity_NN1 of_IO a_AT1 security_NN1 the_AT higher_JJR the_AT ABS_JJ spread_NN1 also_RR because_CS investors_NN2 want_VV0 compensation_NN1 if_CS they_PPHS2 have_VH0 to_TO bind_VVI their_APPGE money_NN1 for_IF longer_JJR periods_NN2 ._. 
</s>
<s>
Factors_NN2 that_CST did_VDD nt_XX have_VHI major_JJ difference_NN1 in_II the_AT ABS_JJ spread_NN1 were_VBDR for_REX21 example_REX22 the_AT type_NN1 of_IO originator_NN1 ._. 
</s>
<s>
In_II the_AT last_MD version_NN1 of_IO this_DD1 end-of-term_JJ paper_NN1 this_DD1 sections_VVZ among_II others_NN2 will_VM we_PPIS2 more_RRR thoroughly_RR described_VVN ._. 
</s>
<s>
5_MC ._. 
</s>
<s>
Analysis_NN1 and_CC discussion_NN1 In_II the_AT section_NN1 of_IO previous_JJ research_NN1 different_JJ determinants_NN2 that_CST have_VH0 or_CC could_VM have_VHI an_AT1 impact_NN1 on_II the_AT ABS_JJ spread_NN1 have_VH0 been_VBN presented_VVN ._. 
</s>
<s>
These_DD2 determinants_NN2 are_VBR involved_JJ in_II a_AT1 way_NN1 or_CC another_DD1 in_II the_AT process_NN1 of_IO securitization_NN1 of_IO ABS_JJ ._. 
</s>
<s>
They_PPHS2 have_VH0 a_AT1 direct_JJ or_CC indirect_JJ influence_NN1 on_II what_DDQ the_AT rate_NN1 of_IO return_NN1 of_IO the_AT specific_JJ ABS_JJ will_VM be_VBI ._. 
</s>
<s>
This_DD1 section_NN1 will_VM be_VBI discussed_VVN broadly_RR after_II all_DB the_AT aspects_NN2 (_( determinants_NN2 )_) have_VH0 been_VBN presented_VVN in_II the_AT section_NN1 of_IO previous_JJ research_NN1 ._. 
</s>
<s>
6_MC ._. 
</s>
<s>
Conclusion_NN1 This_DD1 paper_NN1 has_VHZ examined_VVN what_DDQ are_VBR the_AT determinants_NN2 that_CST have_VH0 been_VBN vital_JJ in_II determine_VV0 the_AT ABS_JJ spread_NN1 ._. 
</s>
<s>
There_EX will_VM be_VBI a_AT1 thorough_JJ conclusion_NN1 after_II the_AT couple_NN1 last_MD sections_NN2 have_VH0 been_VBN written_VVN ._. 
</s>
