<s>
How_RGQ Chinese_JJ Culture_NN1 and_CC Legal_JJ Regulations_NN2 Influence_VV0 Venture_NN1 Capital_NN1 Cycle_NN1 Dear_JJ professor_NN1 ,_, I_PPIS1 changed_VVD my_APPGE topic_NN1 several_DA2 times_NNT2 ._. 
</s>
<s>
The_AT truth_NN1 is_VBZ that_CST there_EX are_VBR not_XX so_RG many_DA2 related_JJ papers_NN2 but_CCB I_PPIS1 really_RR want_VV0 to_TO do_VDI some_DD contribution_NN1 to_II my_APPGE thesis_NN1 and_CC keep_VV0 on_II this_DD1 research_NN1 area_NN1 ._. 
</s>
<s>
Here_RL is_VBZ all_DB I_PPIS1 can_VM catch_VVI before_II the_AT deadline_NN1 ._. 
</s>
<s>
I_PPIS1 will_VM send_VVI you_PPY another_DD1 one_PN1 in_II a_AT1 week_NNT1 ._. 
</s>
<s>
Sorry_JJ for_IF bothering_VVG so_RG much_DA1 ._. 
</s>
<s>
Thank_VV0 you_PPY so_RG much_DA1 !_! 1_MC1 ._. 
</s>
<s>
Introduction_NN1 As_II an_AT1 important_JJ part_NN1 of_IO the_AT private_JJ equity_NN1 ,_, venture_VV0 capitals_NN2 (_( VC_NN1 )_) fill_VV0 the_AT void_NN1 of_IO the_AT traditional_JJ financial_JJ market_NN1 by_II funding_VVG the_AT high-potential_NN1 but_CCB also_RR high-risk_JJ start-up_JJ companies_NN2 ,_, which_DDQ can_VM hardly_RR get_VVI money_NN1 through_II the_AT traditional_JJ capital_NN1 channels_NN2 such_II21 as_II22 government_NN1 funding_NN1 or_CC loan_NN1 from_II banks_NN2 (_( Zider_NP1 1998_MC )_) ._. 
</s>
<s>
Especially_RR in_II the_AT developed_JJ countries_NN2 such_II21 as_II22 American_JJ and_CC some_DD European_JJ countries_NN2 where_RRQ VC_NN1 industry_NN1 is_VBZ set_VVN in_II a_AT1 mature_JJ legal_JJ system_NN1 and_CC innovative_JJ culture_NN1 background_NN1 ,_, VC_NN1 plays_VVZ such_DA an_AT1 important_JJ role_NN1 in_II supporting_VVG newly_RR started_VVD company_NN1 to_TO realize_VVI their_APPGE idea_NN1 with_IW necessary_JJ funding_NN1 and_CC promoting_VVG the_AT emergence_NN1 of_IO numerous_JJ high-growth_JJ firms_NN2 (_( Ahlstrom_VV0 &Bruton2006);_NULL that_DD1 VC_NN1 is_VBZ essential_JJ to_II active_JJ a_AT1 countrys_NN2 entrepreneurship_NN1 and_CC innovation_NN1 thereafter_RT contributes_VVZ to_II one_MC1 countrys_VVZ economic_JJ growth_NN1 (_( Bruton_NP1 &Ahlstrom;_NULL 2006_MC )_) ._. 
</s>
<s>
However_RR ,_, the_AT situation_NN1 that_CST VC_NN1 faces_NN2 will_VM be_VBI different_JJ in_II the_AT country_NN1 that_CST does_VDZ not_XX create_VVI a_AT1 comfortable_JJ environment_NN1 for_IF the_AT VC_NN1 industry_NN1 ,_, so_CS the_AT way_NN1 in_II which_DDQ the_AT VC_NN1 will_VM be_VBI operatedwill_NN1 also_RR be_VBI different_JJ (_( Ahlstrom_NP1 &Bruton;_NULL 2003_MC )_) ._. 
</s>
<s>
In_II Hazarika_NP1 ,_, Nahata_NP1 and_CC Tandonsstudy_NP1 (_( 2009_MC )_) ,_, the_AT cultural_JJ dimension_NN1 and_CC the_AT institutional_JJ context_NN1 ,_, which_DDQ includes_VVZ political_JJ ,_, economic_JJ and_CC legal_JJ factors_NN2 ,_, can_VM significantly_RR influence_VVI the_AT VCs_NN2 performance_NN1 ,_, practices_NN2 ,_, and_CC success_NN1 ._. 
</s>
<s>
During_II the_AT past_JJ decades_NNT2 ,_, China_NP1 has_VHZ experienced_VVN big_JJ boom_NN1 in_II its_APPGE economy_NN1 and_CC becomes_VVZ one_MC1 of_IO the_AT fast_JJ developing_JJ countries_NN2 and_CC one_MC1 of_IO the_AT biggest_JJT emerging_JJ markets_NN2 ._. 
</s>
<s>
The_AT economic_JJ boom_NN1 gives_VVZ rise_NN1 to_II the_AT development_NN1 of_IO Chinese_JJ financial_JJ market_NN1 ,_, including_II the_AT VC_NN1 industry.However_NNU ,_, at_II the_AT same_DA time_NNT1 ,_, as_CSA China_NP1 is_VBZ a_AT1 developing_JJ country_NN1 that_CST has_VHZ more_DAR than_CSN five_MC thousand_NNO years_NNT2 history_NN1 and_CC experienced_JJ various_JJ political_JJ and_CC economic_JJ revolutions_NN2 in_II different_JJ time_NNT1 ,_, China_NP1 formulates_VVZ a_AT1 relatively_RR complicated_JJ background_NN1 with_IW special_JJ culture_NN1 ,_, politics_NN1 ,_, and_CC legal_JJ systems_NN2 ._. 
</s>
<s>
According_II21 to_II22 the_AT institutional_JJ theory_NN1 ,_, which_DDQ points_VVZ out_RP that_CST the_AT beliefs_NN2 ,_, goals_NN2 ,_, and_CC actions_NN2 of_IO individuals_NN2 and_CC communities_NN2 arestrongly_RR affected_VVN by_II various_JJ environmental_JJ institutions_NN2 (_( Scott_NP1 ,_, 1995_MC )_) that_CST are_VBR developed_VVN under_II the_AT influence_NN1 of_IO culture_NN1 ,_, politics_NN1 ,_, economics_NN1 ,_, and_CC legal_JJ regulations_NN2 ,_, Chinese_JJ special_JJ background_NN1 can_VM influence_VVI the_AT VCs_NN2 development_NN1 and_CC make_VVI Chinese_NP1 VC_NNA industry_NN1 different_JJ from_II that_DD1 in_II other_JJ western_JJ countries_NN2 ._. 
</s>
<s>
Concerning_II the_AT institutional_JJ theory_NN1 covers_VVZ too_RG many_DA2 different_JJ aspects_NN2 of_IO the_AT environment_NN1 that_CST an_AT1 institution_NN1 is_VBZ in_RP and_CC will_VM be_VBI too_RG broad_JJ for_IF a_AT1 short_JJ paper_NN1 to_TO analyze_VVI ,_, this_DD1 paper_NN1 will_VM only_RR focus_VVI on_II the_AT legal_JJ regulation_NN1 dimension_NN1 and_CC cultural_JJ influences_NN2 on_II different_JJ segment_NN1 of_IO VC_NN1 cycle_NN1 ._. 
</s>
<s>
The_AT paper_NN1 will_VM be_VBI structured_VVN as_CSA follows_VVZ :_: At_II the_AT beginning_NN1 ,_, some_DD basic_JJ knowledge_NN1 of_IO venture_NN1 capital_NN1 cycle_NN1 will_VM be_VBI given_VVN out_RP ._. 
</s>
<s>
For_IF every_AT1 single_JJ venture_NN1 capital_NN1 cycle_NN1 ,_, there_EX are_VBR mainly_RR three_MC segments_NN2 :_: pre-investment_NN1 ,_, post-investment_JJ management_NN1 ,_, and_CC exit_NN1 ._. 
</s>
<s>
The_AT pre-investment_NN1 process_NN1 is_VBZ a_AT1 selection_NN1 for_IF prospective_JJ potential_JJ funded_JJ firms_NN2 ;_; venture_VV0 capitalists_NN2 in_II post-investmentmainly_RR focus_VV0 on_II structuring_NN1 relationships_NN2 andmonitoring_VVG the_AT invested_JJ firm_NN1 ,_, and_CC maybe_RR do_VD0 value-added_JJ activities_NN2 to_II the_AT funded_JJ firm_NN1 ;_; and_CC in_II the_AT exit_NN1 phase_NN1 ,_, venture_VV0 capitalists_NN2 employ_VV0 different_JJ exit_NN1 strategies_NN2 to_TO convert_VVI their_APPGE non-liquid_JJ equity_NN1 in_II the_AT invested_JJ firms_NN2 into_II liquid_JJ equity_NN1 (_( Ahlstrom_NP1 &Bruton;_NULL 2003_MC ,_, Clercq_NP1 ,_, De_NP1 Dirk_NP1 ,_, et_RA21 al._RA22 ,_, 2006_MC )_) ._. 
</s>
<s>
For_IF the_AT pre-investment_NN1 and_CC post-investment_JJ phases_NN2 of_IO VC_NN1 cycle_NN1 ,_, this_DD1 paper_NN1 will_VM pick_VVI up_RP the_AT most_RGT cultural_JJ relative_JJ features_NN2 of_IO the_AT VC_NN1 and_CC check_VV0 how_RGQ Chinese_JJ culture_NN1 affects_VVZ these_DD2 features_NN2 ._. 
</s>
<s>
For_IF the_AT exit_NN1 phase_NN1 ,_, I_PPIS1 will_VM analyze_VVI how_RGQ Chinese_JJ legal_JJ regulation_NN1 affects_VVZ the_AT VCs_NN2 exit_VV0 in_II China_NP1 ._. 
</s>
<s>
2_MC ._. 
</s>
<s>
Characteristics_NN2 of_IO Venture_NN1 Capital_NN1 Cycle_NN1 2.1_MC Description_NN1 of_IO Venture_NN1 Capital_NN1 Venture_NN1 capital_NN1 is_VBZ an_AT1 equity_NN1 financing_NN1 of_IO young_JJ ,_, high_JJ risk_NN1 companies_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ the_AT capital_NN1 seeking_VVG for_IF high_JJ returns_NN2 behind_II the_AT high_JJ risks_NN2 ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO generate_VVI a_AT1 high_JJ return_NN1 from_II the_AT invested_JJ company_NN1 ,_, venture_VV0 capitalists_NN2 would_VM do_VDI some_DD value-added_JJ services_NN2 to_TO foster_VVI the_AT enterprises_NN2 high_JJ growth_NN1 ._. 
</s>
<s>
The_AT typical_JJ and_CC classicalVC_NN1 tends_VVZ to_TO have_VHI the_AT following_JJ basic_JJ characteristics_NN2 :_: (_( 1_MC1 )_) Invest_VV0 to_II the_AT Star-up_NN1 ,_, small_JJ and_CC medium_JJ enterprises_NN2 and_CC high-tech_JJ enterprises_NN2 ._. 
</s>
<s>
(_( 2_MC )_) The_AT investment_NN1 period_NN1 is_VBZ around_RG 3-5_MCMC years_NNT2 ._. 
</s>
<s>
VCs_NN2 investment_NN1 is_VBZ generally_RR equity_NN1 investment_NN1 ,_, and_CC typically_RR accounts_VVZ for_IF more_DAR than_CSN 50%_NNU of_IO the_AT shares_NN2 of_IO the_AT invested_JJ enterprise_NN1 to_TO get_VVI the_AT controlling_JJ stake_NN1 ._. 
</s>
<s>
The_AT investment_NN1 from_II VC_NN1 does_VDZ not_XX need_VVI any_DD collateral_NN1 from_II the_AT invested_JJ firm_NN1 ._. 
</s>
<s>
(_( 3_MC )_) Investment_NN1 decisions_NN2 are_VBR made_VVN on_II the_AT basis_NN1 of_IO highly_RR specialized_JJ procedures_NN2 ._. 
</s>
<s>
(_( 4_MC )_) Venture_VV0 capitalistsoften_VV0 get_VV0 involved_JJ in_II the_AT management_NN1 of_IO portfolio_NN1 companies_NN2 and_CC providing_VVG value-added_JJ services_NN2 ;_; In_II31 addition_II32 to_II33 the_AT seed_NN1 stage_NN1 (_( seed_NN1 )_) financing_NN1 ,_, generally_RR on_II the_AT subsequent_JJ stages_NN2 of_IO development_NN1 in_II the_AT investment_NN1 and_CC corporate_JJ finance_NN1 needs_VVZ to_TO be_VBI met._NNU (_( 5_MC )_) Investment_NN1 in_II the_AT pursuit_NN1 of_IO excess_JJ returns_NN2 ,_, after_II being_VBG put_VVN in_II corporate_JJ value-added_JJ ,_, investment_NN1 capital_NN1 by_II the_AT withdrawal_NN1 of_IO listing_NN1 of_IO the_AT IPO_NN1 ,_, mergers_NN2 and_CC acquisitions_NN2 ,_, or_CC other_JJ ways_NN2 of_IO equity_NN1 transfer_NN1 ,_, to_TO achieve_VVI value-added_JJ ._. 
</s>
<s>
(_( 6_MC )_) VC_NN1 is_VBZ high_JJ investment_NN1 with_IW high_JJ risk.The_NNU average_JJ possibility_NN1 of_IO an_AT1 investment_NN1 to_TO be_VBI a_AT1 failure_NN1 is_VBZ about_RG 70%_NNU ,_, but_CCB if_CS the_AT investment_NN1 is_VBZ successful_JJ ,_, it_PPH1 will_VM obtain_VVI high_JJ return_NN1 ._. 
</s>
<s>
2.2_MC Venture_NN1 Capital_NN1 Cycle_NN1 The_AT steps_NN2 that_CST every_AT1 VC_NN1 cycle_NN1 needs_VVZ to_TO follow_VVI can_VM be_VBI illustrated_VVN as_II the_AT Figure_NN1 1_MC1 ._. 
</s>
<s>
Every_AT1 step_NN1 has_VHZ special_JJ implications_NN2 for_IF the_AT VC_NN1 practices_NN2 ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) 2.2.1_MC Pre-investment_NN1 2.2.2_MC Post-investment_JJ 2.2.3_MC Exit_NN1 3_MC ._. 
</s>
<s>
Analysis_NN1 
</s>
