<s>
Literature_NN1 overview_NN1 of_IO studies_NN2 related_VVN to_II health_NN1 promoting_VVG activities_NN2 Introduction_NN1 The_AT quality_NN1 and_CC the_AT actions_NN2 of_IO the_AT management_NN1 team_NN1 are_VBR important_JJ when_CS explaining_VVG reasons_NN2 for_IF both_DB2 short-_JJ and_CC long-term_JJ sick_JJ leaves_NN2 ._. 
</s>
<s>
These_DD2 factors_NN2 can_VM also_RR be_VBI taken_VVN into_II consideration_NN1 when_CS examining_VVG sustainable_JJ work-related_JJ health_NN1 and_CC improved_JJ health_NN1 among_II the_AT employees_NN2 and_CC the_AT leaders_NN2 subordinates_NN2 ._. 
</s>
<s>
The_AT leaders_NN2 of_IO a_AT1 company_NN1 can_VM affect_VVI the_AT work_NN1 environment_NN1 both_RR directly_RR and_CC indirectly_RR ._. 
</s>
<s>
Direct_JJ influences_NN2 are_VBR decisions_NN2 with_IW the_AT aim_NN1 to_TO reduce_VVI work-related_JJ burdens_NN2 ._. 
</s>
<s>
Indirect_JJ influences_NN2 emerge_VV0 when_RRQ conditions_NN2 enable_VV0 better_JJR management_NN1 of_IO work-related_JJ burdens_NN2 ._. 
</s>
<s>
(_( Dellve_NP1 &;_NULL Skagert_NP1 &;_NULL Vilhelmsson_NP1 2007:471_MC )_) Future_JJ leaders_NN2 and_CC persons_NN2 who_PNQS are_VBR currently_RR working_VVG as_CSA leaders_NN2 will_VM gain_VVI advantages_NN2 of_IO knowing_VVG how_RRQ to_TO prevent_VVI sick_JJ leaves_NN2 ,_, and_CC generally_RR improve_VV0 the_AT health_NN1 of_IO the_AT employees_NN2 ._. 
</s>
<s>
The_AT power_NN1 of_IO making_VVG decisions_NN2 in_II a_AT1 company_NN1 is_VBZ allocated_VVN to_II the_AT leaders_NN2 ,_, which_DDQ means_VVZ that_CST they_PPHS2 have_VH0 the_AT greatest_JJT ability_NN1 to_TO really_RR affect_VVI the_AT level_NN1 of_IO well_RR being_VBG among_II the_AT workers_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ therefore_RR qualified_VVN to_TO focus_VVI on_II what_DDQ the_AT management_NN1 can_VM do_VDI to_TO prevent_VVI sick_JJ leaves_NN2 ._. 
</s>
<s>
Work-related_JJ health_NN1 has_VHZ been_VBN researched_VVN from_II many_DA2 aspects_NN2 ._. 
</s>
<s>
Dellve_VV0 ,_, Skagert_NP1 &;_NULL Vilhelmsson_NP1 have_VH0 focused_VVN on_II the_AT role_NN1 of_IO leadership_NN1 when_CS trying_VVG to_TO decrease_VVI work-related_JJ disorders_NN2 and_CC sick_JJ leaves_NN2 ._. 
</s>
<s>
In_II 2005_MC ,_, Roskes_NP2 ,_, Donders_NP1 &;_NULL van_NN1 der_FU Gulden_NNU1 published_JJ a_AT1 study_NN1 on_II health-_NN1 and_CC work-related_JJ aspects_NN2 associated_VVN with_IW sick_JJ leave_NN1 ._. 
</s>
<s>
The_AT authors_NN2 did_VDD a_AT1 comparison_NN1 of_IO chronically_RR ill_JJ and_CC non-chronically_RR ill_JJ workers_NN2 ._. 
</s>
<s>
The_AT results_NN2 of_IO the_AT study_NN1 showed_VVD that_DD1 fatigue_NN1 ,_, emotional_JJ exhaustion_NN1 and_CC perceived_JJ health_NN1 complaints_NN2 are_VBR associated_VVN with_IW sick_JJ leaves_NN2 ._. 
</s>
<s>
However_RR ,_, the_AT study_NN1 was_VBDZ not_XX focused_VVN on_II what_DDQ the_AT management_NN1 can_VM do_VDI to_TO prevent_VVI these_DD2 sick_JJ leaves_NN2 ._. 
</s>
<s>
(_( Dellve_NP1 &;_NULL Skagert_NP1 &;_NULL Vilhelmsson_NP1 2007:471_MC ;_; Roskes_NP2 &;_NULL Donders_VVZ &;_NULL van_NN1 der_FU Gulden_NNU1 2005:275_MC )_) This_DD1 paper_NN1 is_VBZ a_AT1 literature_NN1 overview_NN1 of_IO the_AT studies_NN2 related_VVN to_II what_DDQ the_AT management_NN1 of_IO a_AT1 company_NN1 can_VM do_VDI in_BCL21 order_BCL22 to_TO prevent_VVI sick_JJ leaves_NN2 among_II the_AT workers_NN2 ._. 
</s>
<s>
The_AT studies_NN2 will_VM be_VBI collected_VVN from_II different_JJ academic_JJ journals_NN2 ,_, mostly_RR medical_JJ and_CC health_NN1 journals_NN2 ._. 
</s>
<s>
The_AT aim_NN1 of_IO the_AT paper_NN1 is_VBZ to_TO gather_VVI information_NN1 about_II the_AT factors_NN2 that_CST have_VH0 the_AT greatest_JJT impact_NN1 on_II the_AT level_NN1 of_IO absenteeism_NN1 ._. 
</s>
<s>
Conclusions_NN2 can_VM then_RT be_VBI drawn_VVN on_II which_DDQ factors_VVZ the_AT leaders_NN2 of_IO the_AT company_NN1 should_VM focus_VVI on_RP ._. 
</s>
<s>
Some_DD literature_NN1 overviews_NN2 on_II the_AT same_DA topic_NN1 can_VM be_VBI found_VVN in_II the_AT academic_JJ research_NN1 papers_NN2 written_VVN previously_RR ._. 
</s>
<s>
However_RR ,_, these_DD2 literature_NN1 overviews_NN2 do_VD0 not_XX include_VVI both_DB2 studies_NN2 on_II what_DDQ the_AT reasons_NN2 for_IF the_AT sick_JJ leaves_NN2 are_VBR and_CC studies_NN2 on_II what_DDQ the_AT management_NN1 can_VM do_VDI to_TO decrease_VVI the_AT amount_NN1 of_IO absenteeism_NN1 ._. 
</s>
<s>
This_DD1 paper_NN1 seeks_VVZ to_TO combine_VVI these_DD2 two_MC kinds_NN2 of_IO studies_NN2 in_BCL21 order_BCL22 to_TO present_VVI absenteeism-reducing_JJ activities_NN2 that_CST are_VBR logically_RR associated_VVN with_IW the_AT reasons_NN2 for_IF sick_JJ leaves_NN2 ._. 
</s>
<s>
After_CS this_DD1 brief_JJ introduction_NN1 follows_VVZ a_AT1 more_RGR detailed_JJ overview_NN1 of_IO the_AT main_JJ tasks_NN2 of_IO the_AT management_NN1 ,_, and_CC whether_CSW sick_JJ leaves_NN2 are_VBR a_AT1 common_JJ phenomenon_NN1 ._. 
</s>
<s>
The_AT third_MD part_NN1 of_IO the_AT paper_NN1 consists_VVZ of_IO a_AT1 presentation_NN1 of_IO studies_NN2 in_II this_DD1 area_NN1 ._. 
</s>
<s>
An_AT1 analysis_NN1 of_IO the_AT studies_NN2 will_VM be_VBI made_VVN in_II the_AT fourth_MD part_NN1 ,_, and_CC a_AT1 conclusion_NN1 of_IO the_AT paper_NN1 is_VBZ done_VDN in_II the_AT last_MD part_NN1 ._. 
</s>
<s>
Background_NN1 information_NN1 The_AT roles_NN2 and_CC tasks_NN2 of_IO the_AT manager_NN1 The_AT tasks_NN2 and_CC responsibilities_NN2 of_IO the_AT managers_NN2 can_VM be_VBI described_VVN in_II many_DA2 ways_NN2 ._. 
</s>
<s>
Some_DD examples_NN2 will_VM be_VBI given_VVN in_II this_DD1 chapter_NN1 ._. 
</s>
<s>
The_AT amount_NN1 of_IO different_JJ characteristics_NN2 that_CST is_VBZ used_VVN in_II the_AT academic_JJ literature_NN1 to_TO describe_VVI a_AT1 good_JJ manager_NN1 is_VBZ overwhelming_JJ ._. 
</s>
<s>
However_RR ,_, the_AT key_JJ points_NN2 seem_VV0 to_TO be_VBI quite_RG similar_JJ to_II each_PPX221 other_PPX222 ._. 
</s>
<s>
It_PPH1 is_VBZ important_JJ that_CST the_AT managers_NN2 understand_VV0 that_CST they_PPHS2 have_VH0 the_AT main_JJ responsibilities_NN2 for_IF the_AT activities_NN2 of_IO the_AT firm_NN1 ,_, and_CC that_CST they_PPHS2 are_VBR in_II31 charge_II32 of_II33 motivating_VVG and_CC training_VVG the_AT employees_NN2 to_TO do_VDI a_AT1 great_JJ job_NN1 ._. 
</s>
<s>
de_NP1 Jong_NP1 ,_, Leenders_NP1 and_CC Thijssen_NP1 have_VH0 studied_VVN how_RRQ the_AT HRD_NP1 (_( human_JJ resource_NN1 development_NN1 )_) tasks_NN2 are_VBR carried_VVN out_RP by_II first-level_JJ managers_NN2 ._. 
</s>
<s>
The_AT authors_NN2 wanted_VVD to_TO collect_VVI empirical_JJ data_NN on_II how_RRQ the_AT decentralization_NN1 of_IO HRD_NP1 responsibilities_NN2 to_II the_AT first-level_JJ managers_NN2 is_VBZ implemented_VVN in_II companies_NN2 ._. 
</s>
<s>
The_AT question_NN1 they_PPHS2 hoped_VVD to_TO answer_VVI was_VBDZ :_: What_DDQ do_VD0 first-level_JJ managers_NN2 actually_RR do_VD0 to_TO realize_VVI their_APPGE HRD_NP1 responsibility_NN1 ?_? (_( de_NP1 Jong_NP1 &;_NULL Leenders_NP1 &;_NULL Thijssen_NP1 1999:176_MC )_) After_II interviewing_VVG 23_MC HRD_NP1 directors_NN2 ,_, the_AT authors_NN2 found_VVD three_MC types_NN2 of_IO roles_NN2 that_CST the_AT managers_NN2 use_VV0 ._. 
</s>
<s>
The_AT first_MD one_PN1 is_VBZ the_AT analytic_JJ role_NN1 ._. 
</s>
<s>
The_AT managers_NN2 are_VBR analyzing_VVG and_CC solving_VVG performance_NN1 problems_NN2 among_II the_AT workers_NN2 ._. 
</s>
<s>
The_AT second_MD role_NN1 is_VBZ the_AT supportive_JJ role_NN1 ,_, which_DDQ is_VBZ achieved_VVN by_II creating_VVG favorable_JJ conditions_NN2 for_IF learning_NN1 ._. 
</s>
<s>
The_AT third_MD one_PN1 is_VBZ the_AT trainer_NN1 role_NN1 ._. 
</s>
<s>
This_DD1 role_NN1 includes_VVZ directly_RR influencing_VVG work_NN1 behavior_NN1 ._. 
</s>
<s>
Further_RRR ,_, the_AT authors_NN2 found_VVD that_CST the_AT supportive_JJ role_NN1 and_CC the_AT trainer_NN1 role_NN1 merely_RR were_VBDR found_VVN in_II large_JJ companies_NN2 ,_, while_CS the_AT analytic_JJ role_NN1 was_VBDZ descriptive_JJ for_IF smaller_JJR companies_NN2 ._. 
</s>
<s>
(_( de_NP1 Jong_NP1 &;_NULL Leenders_NP1 &;_NULL Thijssen_NP1 1999:181_MC )_) Harrington_NP1 defines_VVZ managers_NN2 as_CSA people_NN who_PNQS accomplish_VV0 tasks_NN2 through_II their_APPGE effective_JJ use_NN1 of_IO processes_NN2 and_CC enablers_NN2 ._. 
</s>
<s>
He_PPHS1 also_RR states_VVZ that_CST it_PPH1 is_VBZ easy_JJ to_TO list_VVI their_APPGE areas_NN2 of_IO responsibility_NN1 ._. 
</s>
<s>
Examples_NN2 of_IO tasks_NN2 are_VBR :_: selecting_VVG and_CC training_NN1 employees_NN2 ,_, allocating_VVG resources_NN2 and_CC developing_VVG the_AT processes_NN2 ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO liberate_VVI the_AT enthusiasm_NN1 and_CC creativity_NN1 that_CST can_VM be_VBI found_VVN in_II the_AT employees_NN2 ,_, the_AT management_NN1 needs_VVZ to_TO fulfill_VVI these_DD2 responsibilities_NN2 ._. 
</s>
<s>
(_( Harrington_NP1 1999:5_MC )_) Harrington_NP1 proceeds_VVZ by_II naming_VVG a_AT1 few_DA2 basic_JJ principles_NN2 that_CST are_VBR a_AT1 part_NN1 of_IO the_AT sophisticated_JJ management_NN1 method_NN1 ._. 
</s>
<s>
The_AT managers_NN2 should_VM not_XX be_VBI afraid_JJ of_IO disagreement_NN1 ._. 
</s>
<s>
Disagreement_NN1 between_II managers_NN2 and_CC workers_NN2 can_VM be_VBI healthy_JJ ,_, if_CS the_AT managers_NN2 can_VM use_VVI the_AT information_NN1 to_TO make_VVI the_AT best_JJT decision_NN1 ._. 
</s>
<s>
A_AT1 positive_JJ attitude_NN1 is_VBZ essential_JJ for_IF going_VVG concern_NN1 ._. 
</s>
<s>
Another_DD1 important_JJ factor_NN1 is_VBZ the_AT communication_NN1 system_NN1 ._. 
</s>
<s>
The_AT management_NN1 should_VM provide_VVI information_NN1 upward_RL ,_, downward_JJ ,_, sideways_RL ,_, to_II the_AT suppliers_NN2 and_CC to_II the_AT customers_NN2 ._. 
</s>
<s>
One_MC1 of_IO the_AT best_JJT investments_NN2 an_AT1 organization_NN1 can_VM make_VVI is_VBZ offering_VVG the_AT employees_NN2 necessary_JJ training_NN1 and_CC help_NN1 ._. 
</s>
<s>
(_( Harrington_NP1 1999:6_MC )_) Instead_II21 of_II22 gaining_VVG approval_NN1 of_IO decisions_NN2 from_II upper_JJ managers_NN2 ,_, the_AT middle-managers_NN2 should_VM discuss_VVI with_IW the_AT affected_JJ workers_NN2 before_II making_VVG the_AT final_JJ decision_NN1 ._. 
</s>
<s>
A_AT1 good_JJ manager_NN1 should_VM also_RR have_VHI the_AT courage_NN1 to_TO break_VVI free_JJ from_II the_AT traditional_JJ chain_NN1 of_IO command_NN1 ._. 
</s>
<s>
This_DD1 means_VVZ ,_, that_CST the_AT manager_NN1 should_VM be_VBI able_JK to_TO work_VVI with_IW anybody_PN1 in_BCL21 order_BCL22 to_TO get_VVI the_AT job_NN1 done_VDN ._. 
</s>
<s>
Another_DD1 argument_NN1 of_IO Harrington_NP1 is_VBZ that_CST the_AT manager_NN1 should_VM give_VVI a_AT1 pay_NN1 that_CST is_VBZ based_VVN on_II knowledge_NN1 and_CC contribution_NN1 instead_II21 of_II22 the_AT time_NNT1 spent_VVN on_II the_AT job_NN1 ._. 
</s>
<s>
(_( Harrington_NP1 1999:7_MC )_) The_AT amount_NN1 of_IO sick_JJ leaves_NN2 Guinan_NN1 discusses_VVZ a_AT1 study_NN1 that_CST showed_VVD that_CST the_AT workers_NN2 in_II the_AT United_NP1 Kingdom_NP1 took_VVD 21_MC million_NNO suspect_NN1 sickies_VVZ during_II 2006_MC ._. 
</s>
<s>
The_AT cost_NN1 of_IO these_DD2 sick_JJ leaves_NN2 was_VBDZ approximately_RR 1,6_MC billion_NNO pounds_NN2 ._. 
</s>
<s>
The_AT survey_NN1 was_VBDZ done_VDN by_II the_AT organization_NN1 CBI_NP1 and_CC the_AT insurer_NN1 AXA_NP1 ._. 
</s>
<s>
Further_JJR results_NN2 showed_VVD that_CST 70%_NNU of_IO the_AT employers_NN2 suspected_VVD their_APPGE workers_NN2 to_II time_NNT1 the_AT sick_JJ leaves_NN2 to_II Mondays_NPD2 or_CC Fridays_NPD2 ,_, to_TO get_VVI an_AT1 extended_JJ weekend_NNT1 ._. 
</s>
<s>
39%_NNU of_IO the_AT employers_NN2 believed_VVD fake_JJ sick_JJ leaves_NN2 can_VM be_VBI connected_VVN to_II major_JJ events_NN2 ,_, like_II sporting_JJ tournaments_NN2 ._. 
</s>
<s>
(_( Guinan_NP1 2007:21_MC )_) According_II21 to_II22 Guinan_NP1 ,_, some_DD workers_NN2 see_VV0 the_AT paid_JJ sick_JJ leaves_NN2 as_CSA benefits_NN2 that_CST should_VM be_VBI used_VVN irrespective_II21 of_II22 whether_CSW the_AT worker_NN1 is_VBZ ill_JJ or_CC not_XX ._. 
</s>
<s>
Some_DD employees_NN2 are_VBR even_RR planning_VVG the_AT sick_JJ leave_NN1 in_II advance_NN1 ._. 
</s>
<s>
By_II planning_VVG extra_JJ days_NNT2 to_TO take_VVI off_RP in_II advance_NN1 ,_, the_AT workers_NN2 are_VBR covering_VVG for_IF each_PPX221 other_PPX222 on_II the_AT absence_NN1 ._. 
</s>
<s>
Guinan_NP1 explains_VVZ that_CST the_AT planning_NN1 of_IO sick_JJ leaves_NN2 in_II advance_NN1 happens_VVZ even_RR among_II public_JJ sector_NN1 workers_NN2 ._. 
</s>
<s>
(_( Guinan_NP1 2007:21_MC )_) Worrall_NP1 has_VHZ also_RR looked_VVN at_II a_AT1 study_NN1 conducted_VVN by_II the_AT organization_NN1 CBI_NP1 ._. 
</s>
<s>
Again_RT ,_, the_AT CBI_NP1 made_VVD a_AT1 survey_NN1 on_II sick_JJ leaves_NN2 ,_, and_CC revealed_VVD a_AT1 result_NN1 showing_VVG that_CST the_AT absence_NN1 bill_NN1 for_IF 2007_MC was_VBDZ 13,2_MC billion_NNO pounds_NN2 ._. 
</s>
<s>
A_AT1 few_DA2 years_NNT2 ago_RA ,_, Worrall_NP1 himself_PPX1 made_VVD a_AT1 survey_NN1 on_II the_AT topic_NN1 of_IO absenteeism_NN1 ._. 
</s>
<s>
The_AT results_NN2 showed_VVD that_CST some_DD of_IO the_AT very_RG large_JJ companies_NN2 are_VBR not_XX aware_JJ of_IO the_AT real_JJ costs_NN2 of_IO absence_NN1 ._. 
</s>
<s>
Therefore_RR these_DD2 companies_NN2 have_VH0 no_AT efficient_JJ mechanisms_NN2 for_IF managing_JJ absence_NN1 intelligently_RR ._. 
</s>
<s>
(_( Worrall_VV0 2008:18_MC )_) The_AT results_NN2 of_IO the_AT surveys_NN2 mentioned_VVN above_RL show_VV0 that_CST the_AT large_JJ amount_NN1 of_IO sick_JJ leaves_NN2 ,_, based_VVN on_II both_DB2 real_JJ and_CC fake_JJ diseases_NN2 ,_, is_VBZ a_AT1 problem_NN1 that_CST needs_VVZ to_TO be_VBI solved_VVN ._. 
</s>
<s>
If_CS the_AT subordinates_NN2 of_IO the_AT managers_NN2 have_VH0 a_AT1 high_JJ rate_NN1 of_IO absence_NN1 ,_, something_PN1 isnt_VV0 working_VVG properly_RR in_II the_AT company_NN1 ._. 
</s>
<s>
The_AT reasons_NN2 for_IF the_AT absenteeism_NN1 can_VM presumably_RR be_VBI found_VVN in_II the_AT responsibilities_NN2 of_IO the_AT managers_NN2 ,_, as_CSA they_PPHS2 are_VBR in_II31 charge_II32 of_II33 motivating_VVG the_AT personnel_NN2 ._. 
</s>
<s>
Studies_NN2 on_II the_AT topic_NN1 Eriksson_NP1 ,_, Axelsson_NP1 and_CC Axelsson_NP1 examined_VVD an_AT1 intervention_NN1 program_NN1 with_IW the_AT purpose_NN1 to_TO develop_VVI health_NN1 promoting_VVG leadership_NN1 ._. 
</s>
<s>
More_RGR specifically_RR ,_, they_PPHS2 wanted_VVD to_TO find_VVI the_AT critical_JJ aspects_NN2 of_IO the_AT program_NN1 ,_, where_CS the_AT aim_NN1 is_VBZ to_TO develop_VVI a_AT1 health_NN1 promoting_VVG workplace_NN1 ._. 
</s>
<s>
The_AT design_NN1 of_IO the_AT research_NN1 is_VBZ a_AT1 case_NN1 study_NN1 ._. 
</s>
<s>
Managers_NN2 supporting_VVG the_AT program_NN1 were_VBDR subjects_NN2 of_IO the_AT paper_NN1 ._. 
</s>
<s>
The_AT authors_NN2 held_VVD 17_MC interviews_NN2 ._. 
</s>
<s>
(_( Eriksson_NP1 &;_NULL Axelsson_NP1 &;_NULL Axelsson_NP1 2010:109_MC )_) The_AT workplaces_NN2 used_VVN in_II the_AT study_NN1 are_VBR situated_VVN in_II Gothenburg_NP1 ,_, Sweden_NP1 ._. 
</s>
<s>
The_AT city_NN1 is_VBZ divided_VVN into_II four_MC districts_NN2 ._. 
</s>
<s>
The_AT personnel_NN2 managers_NN2 in_II these_DD2 districts_NN2 came_VVD up_RP with_IW the_AT idea_NN1 of_IO creating_VVG a_AT1 leadership_NN1 intervention_NN1 ._. 
</s>
<s>
They_PPHS2 had_VHD noticed_VVN a_AT1 high_JJ rate_NN1 of_IO sickness_NN1 absences_NN2 in_II all_DB of_IO the_AT districts_NN2 ,_, so_CS the_AT aim_NN1 of_IO the_AT intervention_NN1 was_VBDZ to_TO help_VVI the_AT unit_NN1 managers_NN2 building_VVG a_AT1 health_NN1 promoting_VVG leadership_NN1 ._. 
</s>
<s>
The_AT long_JJ term_NN1 goal_NN1 would_VM then_RT be_VBI to_TO reduce_VVI the_AT sickness_NN1 rate_NN1 and_CC increase_VVI the_AT level_NN1 of_IO work_NN1 attendance_NN1 ._. 
</s>
<s>
(_( Eriksson_NP1 &;_NULL Axelsson_NP1 &;_NULL Axelsson_NP1 2010:112_MC )_) The_AT program_NN1 was_VBDZ built_VVN on_II different_JJ parts_NN2 ._. 
</s>
<s>
The_AT content_NN1 of_IO one_MC1 part_NN1 was_VBDZ to_TO provide_VVI knowledge_NN1 about_II health_NN1 and_CC health_NN1 promotion_NN1 ._. 
</s>
<s>
Another_DD1 part_NN1 was_VBDZ to_TO change_VVI the_AT attitudes_NN2 and_CC behavior_NN1 of_IO the_AT managers_NN2 to_II a_AT1 more_DAR health_NN1 promoting_VVG direction_NN1 ._. 
</s>
<s>
More_RGR concretely_RR ,_, the_AT program_NN1 included_VVD knowledge-oriented_JJ group_NN1 discussions_NN2 ._. 
</s>
<s>
A_AT1 working_JJ material_NN1 based_VVN on_II health_NN1 promotion_NN1 at_II the_AT work_NN1 place_NN1 was_VBDZ also_RR discussed_VVN ._. 
</s>
<s>
The_AT unit_NN1 managers_NN2 were_VBDR also_RR given_VVN coaching_VVG in_II order_NN1 to_TO better_RRR understand_VVI their_APPGE new_JJ responsibilities_NN2 ._. 
</s>
<s>
(_( Eriksson_NP1 &;_NULL Axelsson_NP1 &;_NULL Axelsson_NP1 2010:115_MC )_) The_AT authors_NN2 named_VVD a_AT1 few_DA2 positive_JJ outcomes_NN2 from_II the_AT intervention_NN1 ._. 
</s>
<s>
The_AT results_NN2 from_II the_AT discussion_NN1 groups_NN2 were_VBDR action_NN1 plans_NN2 for_IF workplace_NN1 health_NN1 promotion_NN1 ._. 
</s>
<s>
The_AT actions_NN2 were_VBDR then_RT specified_VVN ._. 
</s>
<s>
The_AT chance_NN1 for_IF their_APPGE sustainability_NN1 was_VBDZ strengthen_VV0 as_II the_AT management_NN1 group_NN1 supervised_VVD the_AT implementation_NN1 ._. 
</s>
<s>
The_AT managers_NN2 interviewed_VVD pointed_VVN out_RP that_CST the_AT reflections_NN2 and_CC sharing_NN1 of_IO experiences_NN2 with_IW other_JJ managers_NN2 helped_VVD them_PPHO2 developing_VVG themselves_PPX2 ._. 
</s>
<s>
(_( Eriksson_NP1 &;_NULL Axelsson_NP1 &;_NULL Axelsson_NP1 2010:119_MC )_) The_AT results_NN2 of_IO the_AT intervention_NN1 program_NN1 showed_VVD the_AT importance_NN1 of_IO seeing_VVG the_AT development_NN1 of_IO health_NN1 promoting_VVG leadership_NN1 as_CSA means_VVZ to_TO strengthen_VVI the_AT organizational_JJ capacity_NN1 ._. 
</s>
<s>
However_RR ,_, the_AT extensive_JJ amount_NN1 of_IO the_AT program_NN1 content_NN1 was_VBDZ seen_VVN as_CSA something_PN1 that_CST should_VM be_VBI amended_VVN ._. 
</s>
<s>
The_AT integration_NN1 of_IO the_AT program_NN1 and_CC other_JJ similar_JJ activities_NN2 were_VBDR also_RR seen_VVN as_CSA something_PN1 that_CST can_VM cause_VVI problems_NN2 ._. 
</s>
<s>
According_II21 to_II22 the_AT authors_NN2 ,_, the_AT benefits_NN2 of_IO this_DD1 program_NN1 will_VM probably_RR still_RR be_VBI bigger_JJR than_CSN the_AT cost_NN1 ,_, which_DDQ makes_VVZ an_AT1 implementation_NN1 of_IO the_AT new_JJ leadership_NN1 worthwhile_JJ ._. 
</s>
<s>
(_( Eriksson_NP1 &;_NULL Axelsson_NP1 &;_NULL Axelsson_NP1 2010:119_MC )_) Other_JJ studies_NN2 on_II interventions_NN2 concerning_II health_NN1 and_CC absenteeism_NN1 have_VH0 also_RR been_VBN made_VVN ._. 
</s>
<s>
Marzec_NN1 ,_, Golaszewski_NP1 ,_, Musich_NP1 ,_, Powers_NP1 ,_, Shewry_NP1 and_CC Edington_NP1 have_VH0 studied_VVN how_RRQ the_AT employee_NN1 health_NN1 status_NN1 can_VM be_VBI improved_VVN by_II using_VVG an_AT1 environmental_JJ approach_NN1 ._. 
</s>
<s>
In_II this_DD1 study_NN1 ,_, the_AT environmental_JJ interventions_NN2 were_VBDR integrated_VVN into_II the_AT worksite_NN1 environment_NN1 ._. 
</s>
<s>
The_AT study_NN1 was_VBDZ conducted_VVN between_II 2005_MC and_CC 2007_MC ,_, and_CC about_RG 2300_MC employees_NN2 were_VBDR involved_VVN ._. 
</s>
<s>
(_( Marzec_NP1 &;_NULL Golaszewski_NP1 &;_NULL Musich_NP1 &;_NULL Powers_NP1 &;_NULL Shewry_NP1 &;_NULL Edington_NP1 2011:200_MC )_) The_AT senior_JJ management_NN1 at_II the_AT company_NN1 that_CST was_VBDZ participating_VVG in_II the_AT research_NN1 had_VHD noticed_VVN that_CST the_AT environment_NN1 at_II the_AT workplace_NN1 did_VDD nt_XX facilitate_VVI healthy_JJ choices_NN2 ,_, like_II chances_NN2 to_TO be_VBI physically_RR active_JJ during_II the_AT day_NNT1 ,_, or_CC choosing_VVG healthy_JJ food_NN1 ._. 
</s>
<s>
The_AT measures_NN2 used_VVN in_II the_AT study_NN1 were_VBDR changes_NN2 in_II the_AT workplace_NN1 environment_NN1 ,_, change_VV0 in_II the_AT health_NN1 risks_NN2 of_IO the_AT population_NN1 and_CC a_AT1 change_NN1 in_II the_AT level_NN1 of_IO absenteeism_NN1 ._. 
</s>
<s>
(_( Marzec_NN1 et.al._NNU 2011:202_MC )_) A_ZZ1 committee_NN1 consisting_VVG of_IO employees_NN2 from_II different_JJ divisions_NN2 worked_VVD together_RL with_IW the_AT aim_NN1 to_TO present_VVI ideas_NN2 with_IW health_NN1 promoting_VVG effects_NN2 in_BCL21 order_BCL22 to_TO change_VVI the_AT workplace_NN1 environment_NN1 to_II the_AT senior_JJ management_NN1 ._. 
</s>
<s>
They_PPHS2 created_VVD a_AT1 campaign_NN1 named_VVN Know_VV0 your_APPGE numbers_NN2 ,_, which_DDQ should_VM be_VBI held_VVN annually_RR ._. 
</s>
<s>
During_II the_AT campaign_NN1 ,_, the_AT employees_NN2 are_VBR given_VVN free_JJ blood_NN1 pressure_NN1 and_CC body_NN1 fat_NN1 screenings_NN2 ._. 
</s>
<s>
Another_DD1 idea_NN1 was_VBDZ to_TO improve_VVI the_AT stairwell_NN1 ._. 
</s>
<s>
The_AT stairs_NN2 were_VBDR given_VVN easier_JJR access_NN1 and_CC new_JJ paint_NN1 ._. 
</s>
<s>
The_AT use_NN1 of_IO the_AT stairs_NN2 was_VBDZ encouraged_VVN by_II motivational_JJ signs_NN2 ._. 
</s>
<s>
A_AT1 solution_NN1 to_II the_AT unhealthy_JJ food_NN1 options_NN2 was_VBDZ healthier_JJR choices_NN2 at_II a_AT1 deli_NN1 situated_VVN nearby_RL ._. 
</s>
<s>
The_AT company_NN1 held_VVD meetings_NN2 with_IW the_AT owners_NN2 of_IO the_AT deli_NN1 ,_, and_CC as_II a_AT1 result_NN1 the_AT deli_NN1 promoted_VVN more_DAR fruit_NN and_CC other_JJ healthy_JJ food_NN1 ._. 
</s>
<s>
(_( Marzec_NN1 et.al._NNU 2011:202-203_MCMC )_) The_AT level_NN1 of_IO employee_NN1 health_NN1 risk_NN1 was_VBDZ measured_VVN through_II a_AT1 questionnaire_NN1 called_VVN HRA_NP1 (_( Health_NN1 Risk_NN1 Appraisal_NN1 )_) ._. 
</s>
<s>
15_MC health_NN1 factors_NN2 are_VBR included_VVN in_II the_AT HRA_NN1 ,_, for_REX21 example_REX22 alcohol_NN1 use_NN1 ,_, health_NN1 perception_NN1 and_CC physical_JJ inactivity_NN1 ._. 
</s>
<s>
The_AT HRA_NN1 was_VBDZ then_RT used_VVN to_TO define_VVI the_AT health_NN1 status_NN1 of_IO the_AT employees_NN2 ._. 
</s>
<s>
Depending_II21 on_II22 the_AT status_NN1 ,_, the_AT employees_NN2 were_VBDR divided_VVN into_II three_MC risk_NN1 groups_NN2 :_: low_JJ ,_, medium_NN1 and_CC high_JJ risk_NN1 groups_NN2 ._. 
</s>
<s>
(_( Marzec_NN1 et.al._NNU 2011:204_MC )_) The_AT level_NN1 of_IO absenteeism_NN1 was_VBDZ established_VVN by_II summing_VVG the_AT employee_NN1 sick_JJ time_NNT1 ,_, and_CC getting_VVG an_AT1 average_NN1 for_IF each_DD1 three-_JJ month_NNT1 period_NN1 ._. 
</s>
<s>
The_AT time_NNT1 was_VBDZ measured_VVN in_II hours_NNT2 ._. 
</s>
<s>
Time-off_NN1 for_IF family_NN1 care_NN1 ,_, non-industrial_JJ disability_NN1 and_CC compensation_NN1 time_NNT1 were_VBDR also_RR taken_VVN in_II consideration_NN1 ,_, but_CCB not_XX used_VVN as_II the_AT level_NN1 was_VBDZ so_RG low_RR it_PPH1 had_VHD no_AT relevance_NN1 ._. 
</s>
<s>
About_RG 60_MC percent_NNU of_IO the_AT employees_NN2 had_VHD an_AT1 amount_NN1 of_IO sick_JJ leaves_NN2 that_CST was_VBDZ considered_VVN relevant_JJ ._. 
</s>
<s>
However_RR ,_, the_AT employees_NN2 with_IW a_AT1 significantly_RR low_JJ rate_NN1 of_IO sick_JJ leaves_NN2 were_VBDR obviously_RR included_VVN in_II the_AT analysis_NN1 ._. 
</s>
<s>
(_( Marzec_NN1 et.al._NNU 2011:204-205_MCMC )_) Results_NN2 from_II the_AT worksite_NN1 assessment_NN1 showed_VVD that_CST the_AT overall_JJ worksite_NN1 score_NN1 improved_VVN from_II 72_MC points_NN2 to_II 129_MC points_NN2 ._. 
</s>
<s>
The_AT sub-sections_NN2 in_II the_AT assessment_NN1 were_VBDR for_REX21 example_REX22 administrative_JJ support_NN1 ,_, body_NN1 fat_NN1 screening_NN1 and_CC physical_JJ activity_NN1 ._. 
</s>
<s>
All_DB of_IO the_AT sub-sections_NN2 got_VVD better_JJR values_NN2 ,_, except_II21 for_II22 smoking_NN1 ._. 
</s>
<s>
The_AT results_NN2 of_IO the_AT risk_NN1 levels_NN2 showed_VVD that_CST the_AT proportion_NN1 of_IO employees_NN2 belonging_VVG in_II the_AT low_JJ level_JJ risk_NN1 group_NN1 had_VHD slightly_RR increased_VVN ,_, but_CCB the_AT change_NN1 was_VBDZ not_XX statistically_RR significant_JJ ._. 
</s>
<s>
The_AT proportion_NN1 of_IO employees_NN2 in_II the_AT high_JJ level_JJ risk_NN1 group_NN1 had_VHD decreased_VVN ._. 
</s>
<s>
Also_RR ,_, the_AT hours_NNT2 of_IO employee_NN1 sick_JJ time_NNT1 for_IF the_AT selected_JJ period_NN1 decreased_VVD ._. 
</s>
<s>
(_( Marzec_NN1 et.al._NNU 2011:205-207_MCMC )_) Goetzel_NP1 ,_, Ozminkowski_NP1 ,_, Bowen_NP1 and_CC Tabrizi_NP1 have_VH0 written_VVN an_AT1 article_NN1 where_CS they_PPHS2 give_VV0 advice_NN1 on_II how_RRQ to_TO implement_VVI an_AT1 integrated_JJ approach_NN1 that_CST is_VBZ based_VVN on_II worksite_NN1 health_NN1 promotion_NN1 and_CC occupational_JJ safety_NN1 and_CC health_NN1 ._. 
</s>
<s>
They_PPHS2 focus_VV0 on_II physiological_JJ ,_, organizational_JJ and_CC human_JJ capital_NN1 models_NN2 that_CST are_VBR needed_VVN to_TO receive_VVI a_AT1 functioning_JJ health_NN1 and_CC productivity_NN1 management_NN1 ._. 
</s>
<s>
(_( Goetzel_NP1 &;_NULL Ozminkowski_NP1 &;_NULL Bowen_NP1 &;_NULL Tabrizi_NP1 2008:109_MC )_) The_AT authors_NN2 explain_VV0 why_RRQ a_AT1 company_NN1 would_VM be_VBI interested_JJ in_II improving_VVG the_AT health_NN1 of_IO an_AT1 employee_NN1 ._. 
</s>
<s>
A_AT1 healthy_JJ employee_NN1 can_VM work_VVI more_RGR efficiently_RR ,_, and_CC everything_PN1 that_CST increases_VVZ the_AT value_NN1 of_IO a_AT1 worker_NN1 is_VBZ seen_VVN as_II a_AT1 benefit_NN1 for_IF the_AT company_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ also_RR an_AT1 advantage_NN1 for_IF the_AT individual_JJ worker_NN1 to_TO take_VVI part_NN1 of_IO a_AT1 program_NN1 or_CC similar_JJ actions_NN2 to_TO reduce_VVI risks_NN2 and_CC improve_VVI health_NN1 factors_NN2 ._. 
</s>
<s>
Risk_VV0 reducing_VVG and_CC health_NN1 improving_VVG actions_NN2 taken_VVN by_II the_AT management_NN1 will_VM gain_VVI in_II fewer_DAR accidents_NN2 ,_, lower_JJR costs_NN2 ,_, improved_JJ loyalty_NN1 and_CC an_AT1 increase_NN1 in_II the_AT productivity_NN1 of_IO the_AT workers_NN2 ._. 
</s>
<s>
(_( Goetzel_VV0 at.al._NNU 2008:115_MC )_) Goetzel_VV0 et.al_NNU give_VV0 concrete_JJ examples_NN2 on_II how_RRQ to_TO promote_VVI health_NN1 at_II work_NN1 ._. 
</s>
<s>
The_AT senior_JJ management_NN1 can_VM produce_VVI writings_NN2 stating_VVG that_CST it_PPH1 is_VBZ an_AT1 organizational_JJ goal_NN1 to_TO improve_VVI the_AT employee_NN1 health_NN1 ._. 
</s>
<s>
The_AT management_NN1 can_VM also_RR tie_VVI business_NN1 goals_NN2 and_CC management_NN1 bonus_NN1 incentives_NN2 to_II the_AT improvement_NN1 of_IO employee_NN1 health_NN1 ._. 
</s>
<s>
Further_RRR ,_, the_AT management_NN1 can_VM utilize_VVI the_AT meeting_NN1 rooms_NN2 to_TO communicate_VVI messages_NN2 concerning_II health_NN1 improvements_NN2 ._. 
</s>
<s>
(_( Goetzel_VV0 et.al._NNU 2008:115_MC )_) The_AT employee_NN1 health_NN1 and_CC safety_NN1 program_NN1 consists_VVZ of_IO four_MC phases_NN2 ._. 
</s>
<s>
The_AT first_MD phase_NN1 includes_VVZ a_AT1 diagnostic_JJ activity_NN1 ,_, which_DDQ is_VBZ collection_NN1 and_CC analysis_NN1 of_IO relevant_JJ data_NN ._. 
</s>
<s>
The_AT data_NN gives_VVZ information_NN1 on_II where_RRQ the_AT problems_NN2 can_VM be_VBI found_VVN ._. 
</s>
<s>
The_AT second_MD phase_NN1 is_VBZ a_AT1 strategic_JJ and_CC tactical_JJ planning_NN1 phase_NN1 ._. 
</s>
<s>
A_AT1 team_NN1 meets_VVZ to_TO further_RRR analyze_VVI the_AT data_NN ,_, and_CC produces_VVZ an_AT1 implementation_NN1 strategy_NN1 ._. 
</s>
<s>
During_II the_AT third_MD phase_NN1 ,_, the_AT interventions_NN2 are_VBR broadly_RR or_CC narrowly_RR defined_VVN ._. 
</s>
<s>
One_MC1 category_NN1 could_VM be_VBI organizational_JJ climate_NN1 and_CC culture_NN1 ._. 
</s>
<s>
The_AT fourth_MD and_CC last_MD phase_NN1 consists_VVZ of_IO measurement_NN1 and_CC evaluation_NN1 of_IO the_AT intervention_NN1 ._. 
</s>
<s>
During_II this_DD1 phase_NN1 ,_, the_AT working_JJ team_NN1 should_VM try_VVI to_TO understand_VVI why_RRQ the_AT intervention_NN1 succeeded_VVN or_CC failed_VVD ._. 
</s>
<s>
(_( Goetzel_VV0 et.al._NNU 2008:117-118_MCMC )_) Analysis_NN1 of_IO the_AT tasks_NN2 of_IO the_AT management_NN1 When_CS investigating_VVG how_RRQ the_AT health_NN1 of_IO the_AT employees_NN2 can_VM be_VBI improved_VVN ,_, the_AT management_NN1 should_VM focus_VVI on_II both_DB2 the_AT physiological_JJ health_NN1 (_( to_TO prevent_VVI mental_JJ exhaustion_NN1 )_) and_CC the_AT physical_JJ health_NN1 (_( for_REX21 example_REX22 level_NN1 of_IO blood_NN1 pressure_NN1 )_) ._. 
</s>
<s>
The_AT studies_NN2 used_VVN in_II this_DD1 paper_NN1 were_VBDR all_DB mainly_RR focusing_VVG on_II the_AT physical_JJ health_NN1 ,_, but_CCB some_DD advices_NN2 were_VBDR given_VVN on_II how_RRQ to_TO promote_VVI the_AT mental_JJ health_NN1 as_RR21 well_RR22 ._. 
</s>
<s>
The_AT most_RGT obvious_JJ way_NN1 to_TO prevent_VVI mental_JJ exhaustion_NN1 is_VBZ to_TO reduce_VVI stress_NN1 ._. 
</s>
<s>
The_AT management_NN1 might_VM not_XX always_RR be_VBI aware_JJ of_IO the_AT real_JJ work_NN1 burden_NN1 of_IO the_AT employees_NN2 ._. 
</s>
<s>
Continuous_JJ communication_NN1 and_CC discussions_NN2 between_II the_AT workers_NN2 and_CC their_APPGE managers_NN2 can_VM help_VVI the_AT managers_NN2 get_VV0 an_AT1 overall_JJ picture_NN1 ,_, and_CC redistribute_VV0 work_NN1 tasks_NN2 if_CS needed_VVN ._. 
</s>
<s>
The_AT responsibility_NN1 of_IO the_AT welfare_NN1 of_IO the_AT organization_NN1 should_VM be_VBI placed_VVN on_II the_AT managers_NN2 ._. 
</s>
<s>
Depending_II21 on_II22 the_AT size_NN1 of_IO the_AT company_NN1 ,_, the_AT human_JJ resource_NN1 department_NN1 might_VM be_VBI in_II31 charge_II32 of_II33 the_AT personnel_NN2 issues_NN2 ._. 
</s>
<s>
If_CS the_AT company_NN1 is_VBZ too_RG small_JJ to_TO have_VHI a_AT1 specified_JJ human_JJ resource_NN1 department_NN1 ,_, the_AT management_NN1 should_VM appoint_VVI one_MC1 of_IO the_AT managers_NN2 to_TO take_VVI care_NN1 of_IO these_DD2 matters_NN2 ,_, or_CC make_VV0 sure_JJ that_CST health_NN1 issues_NN2 are_VBR discussed_VVN on_II a_AT1 regular_JJ basis_NN1 during_II management_NN1 meetings_NN2 ._. 
</s>
<s>
The_AT costs_NN2 occurring_VVG from_II absenteeism_NN1 can_VM be_VBI of_IO high_JJ amount_NN1 ._. 
</s>
<s>
However_RR ,_, it_PPH1 is_VBZ not_XX an_AT1 easy_JJ task_NN1 to_TO decide_VVI whether_CSW the_AT sick_JJ leave_NN1 is_VBZ legitimated_VVN or_CC not_XX ._. 
</s>
<s>
Different_JJ companies_NN2 have_VH0 different_JJ policies_NN2 concerning_II when_RRQ an_AT1 official_JJ certification_NN1 made_VVN by_II a_AT1 doctor_NN1 is_VBZ needed_VVN ._. 
</s>
<s>
If_CS the_AT company_NN1 suffers_VVZ from_II appreciably_RR high_JJ levels_NN2 of_IO sick_JJ leaves_NN2 ,_, the_AT management_NN1 could_VM even_RR produce_VVI a_AT1 regulation_NN1 stating_VVG that_DD1 official_JJ certifications_NN2 are_VBR needed_VVN for_IF every_AT1 day_NNT1 an_AT1 employee_NN1 stays_VVZ home_RL because_II21 of_II22 sickness_NN1 ._. 
</s>
<s>
The_AT regulation_NN1 could_VM also_RR prevent_VVI situations_NN2 where_RRQ the_AT employee_NN1 plans_VVZ sick_JJ leaves_NN2 in_II advance_NN1 ._. 
</s>
<s>
If_CS a_AT1 part_NN1 of_IO the_AT salary_NN1 is_VBZ based_VVN on_II provision_NN1 ,_, the_AT motivation_NN1 for_IF illegitimated_JJ sick_JJ leaves_NN2 would_VM probably_RR decrease_VVI ._. 
</s>
<s>
Many_DA2 practical_JJ and_CC concrete_JJ advices_NN2 were_VBDR given_VVN in_II the_AT studies_NN2 on_II the_AT topic_NN1 ._. 
</s>
<s>
The_AT management_NN1 would_VM probably_RR appreciate_VVI actions_NN2 that_CST can_VM be_VBI immediately_RR noticed_VVN by_II both_DB2 employees_NN2 and_CC the_AT managers_NN2 themselves_PPX2 ._. 
</s>
<s>
Flyers_NN2 with_IW relevant_JJ information_NN1 ,_, e-mails_NN2 reminding_VVG of_IO stretch_NN1 pauses_NN2 and_CC new_JJ ,_, healthier_JJR snacks_NN2 in_II the_AT vending_JJ machine_NN1 are_VBR examples_NN2 of_IO actions_NN2 that_CST contribute_VV0 to_II a_AT1 health_NN1 promoting_VVG environment_NN1 ._. 
</s>
<s>
Collaborations_NN2 with_IW the_AT nurses_NN2 and_CC doctors_NN2 responsible_JJ for_IF the_AT health_NN1 care_NN1 of_IO the_AT company_NN1 will_VM most_RGT likely_RR help_VVI the_AT management_NN1 in_II their_APPGE endeavor_NN1 to_TO amend_VVI the_AT health_NN1 status_NN1 of_IO the_AT employees_NN2 ._. 
</s>
<s>
The_AT nurses_NN2 could_VM for_REX21 example_REX22 perform_VVI health_NN1 checks_NN2 and_CC other_JJ tests_NN2 on_II a_AT1 regular_JJ basis_NN1 ,_, and_CC the_AT doctors_NN2 can_VM provide_VVI the_AT managers_NN2 with_IW helpful_JJ health_NN1 promoting_VVG advices_NN2 ._. 
</s>
<s>
Conclusion_NN1 The_AT aim_NN1 of_IO this_DD1 paper_NN1 was_VBDZ to_TO provide_VVI a_AT1 literature_NN1 overview_NN1 of_IO studies_NN2 on_II the_AT topic_NN1 of_IO actions_NN2 the_AT management_NN1 can_VM take_VVI in_BCL21 order_BCL22 to_TO reduce_VVI sick_JJ leaves_NN2 ,_, and_CC simultaneously_RR promote_VV0 the_AT health_NN1 of_IO the_AT employees_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ logical_JJ that_CST the_AT managers_NN2 have_VH0 the_AT responsibility_NN1 to_TO take_VVI health_NN1 matters_NN2 into_II consideration_NN1 ,_, as_CSA they_PPHS2 have_VH0 the_AT power_NN1 to_TO make_VVI strategic_JJ decisions_NN2 ._. 
</s>
<s>
Both_RR first-level_JJ managers_NN2 and_CC top_JJ management_NN1 can_VM bear_VVI this_DD1 responsibility_NN1 ._. 
</s>
<s>
Especially_RR smaller_JJR corporations_NN2 without_IW human_JJ resource_NN1 departments_NN2 should_VM make_VVI sure_JJ that_CST someone_PN1 is_VBZ taking_VVG the_AT health_NN1 factors_NN2 in_II consideration_NN1 ._. 
</s>
<s>
Many_DA2 studies_NN2 examined_VVD different_JJ kinds_NN2 of_IO interventions_NN2 and_CC other_JJ health_NN1 promotion_NN1 programs_NN2 ._. 
</s>
<s>
Even_CS21 though_CS22 some_DD studies_NN2 are_VBR made_VVN over_RG ten_MC years_NNT2 ago_RA ,_, the_AT content_NN1 and_CC advices_NN2 in_II them_PPHO2 are_VBR still_RR relevant_JJ ._. 
</s>
<s>
There_EX is_VBZ a_AT1 broad_JJ view_NN1 of_IO literature_NN1 for_IF the_AT managers_NN2 to_TO choose_VVI from_II ._. 
</s>
<s>
Many_DA2 of_IO the_AT studies_NN2 not_XX included_VVN in_II this_DD1 paper_NN1 were_VBDR made_VVN during_II the_AT 1980s_MC2 and_CC 1990s_MC2 ._. 
</s>
<s>
The_AT content_NN1 was_VBDZ very_RG similar_JJ to_II the_AT studies_NN2 made_VVD later_RRR on_RP ._. 
</s>
<s>
It_PPH1 seems_VVZ like_II this_DD1 research_NN1 field_NN1 will_VM be_VBI of_IO great_JJ importance_NN1 in_II the_AT future_NN1 as_RR21 well_RR22 ._. 
</s>
<s>
The_AT studies_NN2 presented_VVN in_II this_DD1 paper_NN1 showed_VVD mainly_RR good_JJ results_NN2 from_II the_AT interventions_NN2 and_CC work_VV0 environment_NN1 changes_NN2 ._. 
</s>
<s>
Even_RR small_JJ changes_NN2 will_VM affect_VVI the_AT workers_NN2 ,_, as_CS31 long_CS32 as_CS33 the_AT changes_NN2 are_VBR noticeable_JJ ._. 
</s>
<s>
Examples_NN2 of_IO small_JJ changes_NN2 discussed_VVN in_II this_DD1 paper_NN1 are_VBR healthier_JJR snacks_NN2 ,_, informative_JJ flyers_NN2 and_CC makeover_VV0 of_IO the_AT stairwell_NN1 ._. 
</s>
<s>
Also_RR follow-up_JJ discussions_NN2 with_IW the_AT mangers_NN2 are_VBR small_JJ changes_NN2 that_CST do_VD0 not_XX need_VVI big_JJ preparations_NN2 ._. 
</s>
<s>
An_AT1 example_NN1 of_IO a_AT1 bigger_JJR change_NN1 would_VM be_VBI if_CSW the_AT company_NN1 checked_VVD important_JJ health_NN1 factors_NN2 on_II the_AT employees_NN2 regularly_RR ,_, such_II21 as_II22 blood_NN1 pressure_NN1 ._. 
</s>
<s>
The_AT managers_NN2 would_VM benefit_VVI from_II focusing_VVG on_II health_NN1 promoting_VVG factors_NN2 ._. 
</s>
<s>
Not_XX only_RR would_VM the_AT company_NN1 save_VVI money_NN1 from_II not_XX having_VHG to_TO hire_VVI extra_JJ personnel_NN2 because_II21 of_II22 a_AT1 high_JJ amount_NN1 of_IO sick_JJ leaves_NN2 ,_, the_AT company_NN1 will_VM also_RR gain_VVI more_DAR value_NN1 from_II employees_NN2 who_PNQS are_VBR healthy_JJ and_CC strong_JJ enough_RR to_TO work_VVI efficiently_RR ._. 
</s>
<s>
Healthy_JJ employees_NN2 can_VM be_VBI seen_VVN as_II a_AT1 means_NN to_II receiving_VVG a_AT1 better_JJR result_NN1 ,_, and_CC producing_VVG more_DAR value_NN1 to_II the_AT owners_NN2 of_IO the_AT company_NN1 ._. 
</s>
<s>
A_AT1 more_RGR comprehensive_JJ literature_NN1 overview_NN1 could_VM include_VVI more_RGR detailed_JJ studies_NN2 on_II background_NN1 reasons_NN2 for_IF the_AT so_JJ21 called_JJ22 suspect_NN1 sickies_NN2 ._. 
</s>
<s>
It_PPH1 would_VM be_VBI interesting_JJ to_TO see_VVI if_CSW the_AT change_NN1 of_IO remuneration_NN1 to_TO be_VBI based_VVN on_II provisions_NN2 would_VM decrease_VVI the_AT amount_NN1 of_IO absences_NN2 from_II work_NN1 ._. 
</s>
<s>
The_AT studies_NN2 could_VM also_RR provide_VVI solutions_NN2 to_II the_AT problem_NN1 of_IO employees_NN2 seeing_VVG the_AT paid_JJ sick_JJ leaves_NN2 as_CSA privileges_NN2 that_CST should_VM be_VBI imposed_VVN ._. 
</s>
