<s>
Impairment_NN1 Testing_NN1 of_IO Goodwill_NN1 Introduction_NN1 There_EX has_VHZ been_VBN a_AT1 lot_NN1 of_IO research_NN1 on_II goodwill_NN1 and_CC how_RRQ goodwill_NN1 is_VBZ handled_VVN in_II the_AT financial_JJ statements_NN2 ,_, with_IW this_DD1 paper_NN1 I_PPIS1 will_VM try_VVI to_TO summarize_VVI the_AT most_RGT important_JJ findings_NN2 ,_, problems_NN2 and_CC possible_JJ solutions_NN2 ._. 
</s>
<s>
In_II 2005_MC when_RRQ IFRS_NN2 (_( International_JJ Financial_JJ Reporting_NN1 Standards_NN2 )_) became_VVD obligatory_JJ for_IF all_DB public_JJ listed_JJ companies_NN2 in_II the_AT European_JJ Union_NN1 there_EX was_VBDZ a_AT1 dramatic_JJ change_NN1 in_II how_RRQ goodwill_NN1 was_VBDZ accounted_VVN for_IF in_II the_AT financial_JJ statements_NN2 ._. 
</s>
<s>
Before_CS IFRS_NN2 ,_, goodwill_NN1 was_VBDZ depreciated_VVN over_II a_AT1 certain_JJ amount_NN1 of_IO time_NNT1 ,_, with_IW IFRS_NP2 goodwill_NN1 is_VBZ kept_VVN on_II the_AT balance_NN1 sheet_NN1 until_CS it_PPH1 becomes_VVZ impaired_JJ and_CC then_RT the_AT impaired_JJ amount_NN1 is_VBZ written_VVN down_RP ._. 
</s>
<s>
Companies_NN2 have_VH0 to_TO do_VDI the_AT impairment_NN1 tests_NN2 on_II their_APPGE goodwill_NN1 once_RR a_AT1 year_NNT1 ._. 
</s>
<s>
This_DD1 causes_VVZ problems_NN2 because_CS new_JJ internally_RR produced_VVN goodwill_NN1 can_VM make_VVI it_PPH1 hard_RR to_TO reliably_RR estimate_VVI the_AT value_NN1 of_IO the_AT bought_VVN goodwill_NN1 and_CC the_AT impairment_NN1 test_NN1 makes_VVZ it_PPH1 easier_JJR for_IF managers_NN2 to_TO manipulate_VVI the_AT financial_JJ statements_NN2 ._. 
</s>
<s>
Despite_II the_AT amount_NN1 of_IO research_NN1 there_EX appears_VVZ not_XX to_TO be_VBI any_DD comprehensive_JJ review_NN1 over_II the_AT problem_NN1 ._. 
</s>
<s>
A_AT1 literature_NN1 overview_NN1 where_CS the_AT most_RGT important_JJ problems_NN2 are_VBR reviewed_VVN and_CC also_RR where_CS the_AT possible_JJ successes_NN2 of_IO the_AT new_JJ accounting_NN1 standards_NN2 are_VBR reviewed_VVN ._. 
</s>
<s>
There_EX are_VBR a_AT1 lot_NN1 of_IO stakeholders_NN2 who_PNQS use_VV0 the_AT financial_JJ statements_NN2 and_CC goodwill_NN1 is_VBZ a_AT1 big_JJ part_NN1 of_IO the_AT balance_NN1 sheet_NN1 in_II the_AT financial_JJ statements_NN2 of_IO a_AT1 lot_NN1 of_IO companies_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ therefore_RR important_JJ that_CST goodwill_NN1 is_VBZ accounted_VVN for_IF in_II a_AT1 way_NN1 that_CST gives_VVZ the_AT best_JJT and_CC most_RGT relevant_JJ information_NN1 to_II the_AT stakeholders_NN2 ._. 
</s>
<s>
How_RRQ can_VM the_AT standard_JJ setters_NN2 improve_VV0 the_AT current_JJ standards_NN2 to_TO better_RRR give_VVI information_NN1 about_II the_AT companys_NN2 financial_JJ position_NN1 to_II stakeholders_NN2 ?_? 
</s>
<s>
In_II the_AT short_JJ term_NN1 it_PPH1 may_VM seem_VVI attractive_JJ to_II companies_NN2 to_TO leave_VVI doubtful_JJ impairments_NN2 undone_VVN ,_, but_CCB in_II the_AT long_JJ run_NN1 ,_, this_DD1 could_VM lead_VVI to_II serious_JJ problems_NN2 ._. 
</s>
<s>
Problems_NN2 will_VM usually_RR appear_VVI when_RRQ it_PPH1 starts_VVZ to_TO get_VVI worse_JJR in_II the_AT economy_NN1 ._. 
</s>
<s>
The_AT decline_NN1 in_II the_AT economy_NN1 that_CST began_VVD in_RP late_RR 2007_MC led_VVD to_II the_AT large_JJ write-downs_NN2 ._. 
</s>
<s>
The_AT study_NN1 "_" Market_NN1 turmoil_NN1 and_CC goodwill_NN1 implications_NN2 "_" by_II Price_NP1 Waterhouse_NP1 Coopers_NP1 (_( 2009_MC )_) Examined_VVD Fortune_NN1 500_MC companies_NN2 and_CC their_APPGE goodwill_NN1 write-downs_NN2 from_II the_AT third_MD quarter_NN1 of_IO 2008_MC to_II March_NPM1 2009_MC ._. 
</s>
<s>
During_II this_DD1 time_NNT1 the_AT companies_NN2 made_VVD total_JJ write-downs_NN2 of_IO $_NN 230_MC billion_NNO ,_, twice_RR as_RG much_DA1 as_CSA companies_NN2 impairment_NN1 of_IO goodwill_NN1 over_II the_AT last_MD three_MC years_NNT2 before_II 2009_MC ._. 
</s>
<s>
Companies_NN2 that_CST do_VD0 not_XX write_VVI down_RP their_APPGE goodwill_NN1 enough_RR in_II a_AT1 good_JJ economy_NN1 have_VH0 major_JJ problems_NN2 in_II a_AT1 bad_JJ economy_NN1 ._. 
</s>
<s>
This_DD1 paper_NN1 will_VM evaluate_VVI the_AT existing_JJ academic_JJ research_NN1 in_II this_DD1 field_NN1 and_CC strive_VV0 to_TO come_VVI up_RP with_IW a_AT1 solution_NN1 as_II21 to_II22 how_RRQ accounting_NN1 for_IF goodwill_NN1 can_VM be_VBI improved_VVN ._. 
</s>
<s>
This_DD1 paper_NN1 is_VBZ organized_VVN the_AT following_JJ way_NN1 :_: one_MC1 chapter_NN1 about_II the_AT theory_NN1 of_IO goodwill_NN1 and_CC how_RRQ it_PPH1 is_VBZ accounted_VVN for_IF today_RT according_II21 to_II22 IFRS_NN2 ,_, the_AT literature_NN1 overview_NN1 and_CC the_AT conclusion_NN1 with_IW the_AT results_NN2 ._. 
</s>
<s>
Goodwill_NN1 According_II21 to_II22 IFRS_NP2 goodwill_NN1 isthe_VV0 future_JJ economic_JJ benefitsthat_NN1 can_VM not_XX beindividuallyidentified_VVN ,_, norto_NN1 report_NN1 theIFRS_NN2 3standard_FO onbusiness_NN1 combinations_NN2 ,_, they_PPHS2 looked_VVD at_II theFASB_NN1 's_GE definition_NN1 ofwhatgoodwill_VV0 is.There_NNU were6_FO they_PPHS2 couldbe_VV0 recognized_JJ asgoodwill_NN1 or_CC not_XX ._. 
</s>
<s>
The_AT first_MD is_VBZ excessofthe_NN1 fair_RR valuesover_VV0 the_AT value_NN1 ofacquiredrecognized_VVD net_JJ assets_NN2 atacquisitiontime_NNT1 ._. 
</s>
<s>
The_AT secondwas_NN2 the_AT fairvalues_NN2 of_IO othernet_NN1 assetsnotpreviously_RR recognized_VVN ._. 
</s>
<s>
The_AT thirdwas_NN2 the_AT fair_JJ valueofthe_NN1 "_" going_VVG concern_NN1 "_" element_NN1 on_II thecurrent_JJ existing_JJ businessoperations_NN2 ._. 
</s>
<s>
The_AT fourthwas_NN2 the_AT fairvalueofsynergies_NN2 andother_VV0 benefits_NN2 fromcombining_VVG the_AT acquirednet_NN1 assets_NN2 andbusiness_NN1 operations_NN2 ._. 
</s>
<s>
The_AT fifthwas_NN2 overvaluation_NN1 ofthecompensationpaid_VVD bytheacquirerbased_JJ onerrorsin_NN1 the_AT valuation._NNU The_AT sixthwas_NN2 over-orunderpaymentby_NN1 the_AT acquirer._NNU Component_NN1 1_MC1 and_CC 2do_FO not_XX belongto_NN1 goodwillon_NN1 1isnotan_FO asset_NN1 and_CC component_NN1 2is_FO notgoodwill_NN1 ,_, butis_NN1 includedunder_VV0 nontangible_JJ assetswhen_NN1 combining_VVG the_AT businesses_NN2 in_II the_AT balance_NN1 sheet.Component5_FO and_CC 6_MC arenotpart_NN1 ofgoodwill_NN1 ,_, they_PPHS2 are_VBR simply_RR overvaluation_NN1 or_CC facteven_JJ anassetsothey_NN1 can_VM not_XX be_VBI includedinthe_NN1 balance_NN1 sheet.Thus_NNU only_RR components3_FO and_CC 4can_FO be_VBI considered_VVN to_TO begoodwill_VVI ._. 
</s>
<s>
Impairment_NN1 of_IO goodwill_NN1 Since_CS the_AT change_NN1 to_II IFRS_NN2 reporting_VVG in_II financial_JJ statements_NN2 the_AT ability_NN1 for_IF companies_NN2 to_TO make_VVI scheduled_JJ amortization_NN1 of_IO goodwill_NN1 has_VHZ been_VBN taken_VVN away_RL ._. 
</s>
<s>
Instead_II21 of_II22 yearly_JJ amortization_NN1 goodwill_NN1 is_VBZ to_TO be_VBI valued_VVN to_II its_APPGE fair_JJ value_NN1 in_II the_AT balance_NN1 sheet_NN1 in_II the_AT financial_JJ statements_NN2 ._. 
</s>
<s>
Companies_NN2 should_VM run_VVI impairment_NN1 tests_NN2 once_RR a_AT1 year_NNT1 to_TO check_VVI that_CST the_AT goodwill_NN1 is_VBZ correctly_RR ._. 
</s>
<s>
If_CS it_PPH1 is_VBZ over-valued_VVN the_AT company_NN1 shall_VM make_VVI a_AT1 write-down_NN1 ._. 
</s>
<s>
Impairment_NN1 testing_NN1 of_IO goodwill_NN1 When_CS testing_VVG if_CSW there_EX is_VBZ an_AT1 impairment_NN1 of_IO an_AT1 asset_NN1 or_CC not_XX one_PN1 checks_VVZ that_CST the_AT asset_NN1 's_GE recoverable_JJ amount_NN1 is_VBZ equal_JJ to_II or_CC greater_JJR than_CSN the_AT asset_NN1 's_GE book_NN1 value_NN1 ._. 
</s>
<s>
If_CS not_XX ,_, the_AT asset_NN1 must_VM be_VBI written_VVN down_RP ._. 
</s>
<s>
Since_CS goodwill_NN1 is_VBZ split_VVN over_II the_AT cash-generating_JJ units_NN2 that_CST it_PPH1 belongs_VVZ to_II the_AT testing_NN1 for_IF impairment_NN1 is_VBZ done_VDN at_II this_DD1 level_NN1 ._. 
</s>
<s>
When_CS examining_VVG possible_JJ impairment_NN1 of_IO goodwill_NN1 according_II IFRS_NN2 there_EX are_VBR three_MC steps_NN2 to_TO follow_VVI ._. 
</s>
<s>
First_MD ,_, estimating_VVG the_AT expected_JJ recoverable_JJ amount_NN1 of_IO cash-generating_JJ unit_NN1 goodwill_NN1 is_VBZ allocated_VVN to_II ._. 
</s>
<s>
The_AT second_MD step_NN1 is_VBZ to_TO calculate_VVI the_AT value_NN1 of_IO a_AT1 cash-generating_JJ unit_NN1 ._. 
</s>
<s>
The_AT value_NN1 of_IO a_AT1 cash-generating_JJ unit_NN1 is_VBZ the_AT higher_JJR of_IO the_AT fair_JJ value_NN1 less_RRR costs_VVZ to_TO sell_VVI or_CC value_NN1 in_II use_NN1 ._. 
</s>
<s>
The_AT fair_JJ value_NN1 less_DAR costs_NN2 is_VBZ the_AT net_JJ price_NN1 that_CST the_AT company_NN1 would_VM get_VVI if_CSW it_PPH1 were_VBDR to_TO sell_VVI the_AT cash-generating_JJ unit_NN1 ._. 
</s>
<s>
The_AT value_NN1 in_II use_NN1 is_VBZ the_AT value_NN1 of_IO the_AT cash-generating_JJ unit_NN1 for_IF the_AT company_NN1 in_II their_APPGE business_NN1 activities_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ not_XX always_RR necessary_JJ to_TO calculate_VVI these_DD2 two_MC values_NN2 ._. 
</s>
<s>
If_CS either_DD1 of_IO these_DD2 values_NN2 ?_? ?_? exceeds_VVZ the_AT cash-generating_JJ unit_NN1 's_VBZ carrying_VVG value_NN1 there_EX is_VBZ no_AT impairment_NN1 ._. 
</s>
<s>
If_CS the_AT recoverable_JJ amount_NN1 is_VBZ less_DAR than_CSN the_AT carrying_NN1 value_NN1 of_IO the_AT cash-generating_JJ unit_NN1 ,_, an_AT1 impairment_NN1 loss_NN1 is_VBZ recorded_VVN ._. 
</s>
<s>
Literature_NN1 overview_NN1 It_PPH1 is_VBZ difficult_JJ to_TO give_VVI an_AT1 exact_JJ definition_NN1 of_IO goodwill_NN1 and_CC how_RRQ it_PPH1 should_VM be_VBI accounted_VVN for_IF ._. 
</s>
<s>
Johnson_NP1 and_CC Petrone_NP1 (_( 1998_MC )_) ,_, ponder_VV0 over_RP the_AT definition_NN1 of_IO goodwill_NN1 in_II their_APPGE article_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ their_APPGE view_NN1 that_CST one_PN1 can_VM examine_VVI goodwill_NN1 from_II two_MC different_JJ perspectives_NN2 either_RR Top-Down_JJ Perspective_NN1 or_CC Bottom-Up_NN1 Perspective_NN1 ._. 
</s>
<s>
In_II the_AT Top-Down_JJ Perspective_NN1 you_PPY treat_VV0 goodwill_NN1 as_II a_AT1 component_NN1 or_CC part_NN1 of_IO a_AT1 larger_JJR unit_NN1 ._. 
</s>
<s>
In_II Bottom-Up_NN1 Perspective_NN1 goodwill_NN1 is_VBZ the_AT sum_NN1 of_IO the_AT components_NN2 forming_VVG it_PPH1 ._. 
</s>
<s>
When_CS considering_VVG goodwill_NN1 in_II general_JJ terms_NN2 ,_, one_PN1 could_VM imagine_VVI that_CST the_AT goodwill_NN1 is_VBZ the_AT portion_NN1 of_IO the_AT price_NN1 paid_VVN in_II31 excess_II32 of_II33 the_AT acquired_JJ asset_NN1 's_GE book_NN1 value_NN1 ._. 
</s>
<s>
The_AT components_NN2 that_CST goodwill_NN1 may_VM consist_VVI of_IO are_VBR according_VVG Johnson_NP1 and_CC Petrone_VV0 the_AT same_DA six_MC components_NN2 that_CST IFRS_VVZ uses_NN2 ._. 
</s>
<s>
As_II the_AT IFRS_NP2 definition_NN1 of_IO goodwill_NN1 Johnson_NP1 &;_NULL Petrone_NP1 also_RR define_VV0 goodwill_NN1 as_CSA components_NN2 3_MC &;_NULL 4_MC ._. 
</s>
<s>
In_II other_JJ words_NN2 going_VVG concern_NN1 and_CC synergies_NN2 are_VBR the_AT only_JJ aspects_NN2 of_IO goodwill_NN1 that_CST are_VBR considered_VVN core_NN1 goodwill_NN1 ._. 
</s>
<s>
The_AT conclusion_NN1 of_IO this_DD1 is_VBZ that_CST IFRS_NN2 has_VHZ defined_VVN goodwill_NN1 very_RG close_JJ to_II the_AT Bottom-Up_NN1 Perspective_NN1 from_II Johnson_NP1 &;_NULL Petrones_NP1 article_NN1 ._. 
</s>
<s>
Henning_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2000_MC )_) did_VDD an_AT1 empirical_JJ study_NN1 published_VVN in_II the_AT Journal_NN1 of_IO Accounting_VVG Research_NN1 where_CS they_PPHS2 examined_VVD how_RRQ the_AT market_NN1 behaved_VVN towards_II the_AT various_JJ identifiable_JJ components_NN2 of_IO goodwill_NN1 ._. 
</s>
<s>
The_AT empirical_JJ study_NN1 was_VBDZ done_VDN by_II studying_VVG 1576_MC acquisitions_NN2 between_II 1990_MC and_CC 1994_MC ._. 
</s>
<s>
The_AT information_NN1 for_IF the_AT survey_NN1 was_VBDZ taken_VVN from_II the_AT Securities_NN2 Data_NN Company_NN1 U.S._NP1 Mergers_NN2 and_CC Acquisitions_NN2 database_NN1 ._. 
</s>
<s>
The_AT acquisitions_NN2 were_VBDR of_IO an_AT1 average_JJ value_NN1 of_IO $_NN 319_MC million_NNO while_CS the_AT acquired_JJ company_NN1 's_GE book_NN1 value_NN1 was_VBDZ an_AT1 average_NN1 of_IO $_NN 100_MC million_NNO ._. 
</s>
<s>
The_AT study_NN1 concluded_VVD that_CST investors_NN2 have_VH0 both_RR positive_JJ and_CC negative_JJ thoughts_NN2 of_IO goodwill_NN1 ._. 
</s>
<s>
The_AT markets_NN2 reacted_VVD positively_RR to_II the_AT goodwill_NN1 components_NN2 of_IO synergies_NN2 from_II the_AT combination_NN1 of_IO business_NN1 activities_NN2 and_CC "_" going_VVG concern_NN1 "_" ._. 
</s>
<s>
While_CS markets_NN2 reacted_VVD negatively_RR to_II the_AT components_NN2 of_IO goodwill_NN1 that_CST can_VM not_XX be_VBI considered_VVN assets_NN2 on_II the_AT company_NN1 's_GE balance_NN1 sheet_NN1 under_II current_JJ reporting_NN1 standards_NN2 ._. 
</s>
<s>
Components_NN2 that_CST the_AT market_NN1 reacted_VVD negatively_RR to_II could_VM lead_VVI to_II adverse_JJ developments_NN2 in_II the_AT company_NN1 's_GE market_NN1 value_NN1 ._. 
</s>
<s>
Based_VVN on_II this_DD1 it_PPH1 can_VM be_VBI argued_VVN that_CST Johnson_NP1 and_CC Petrone_NP1 (_( 1998_MC )_) model_NN1 also_RR works_VVZ in_II the_AT real_JJ world_NN1 ._. 
</s>
<s>
Problems_NN2 with_IW impairment_NN1 testing_VVG According_II21 to_II22 IFRS_NP2 goodwill_NN1 is_VBZ a_AT1 non-wasting_JJ asset_NN1 ._. 
</s>
<s>
A_AT1 big_JJ part_NN1 of_IO goodwill_NN1 may_VM consist_VVI of_IO synergy_NN1 benefits_NN2 that_CST over_II time_NNT1 and_CC due_II21 to_II22 changes_NN2 in_II the_AT environment_NN1 might_VM behave_VVI as_II a_AT1 wasting_VVG asset_NN1 and_CC not_XX as_II a_AT1 non-wasting_JJ asset_NN1 ._. 
</s>
<s>
This_DD1 can_VM lead_VVI to_II problems_NN2 ._. 
</s>
<s>
Schultze_NP1 (_( 2005_MC )_) examines_VVZ this_DD1 in_II his_APPGE article_NN1 ._. 
</s>
<s>
Schultze_NN1 says_VVZ that_CST because_CS goodwill_NN1 can_VM have_VHI both_DB2 properties_NN2 ._. 
</s>
<s>
The_AT impairment_NN1 testing_VVG actually_RR needs_VVZ a_AT1 mixture_NN1 of_IO depreciation_NN1 and_CC amortization_NN1 ._. 
</s>
<s>
Since_CS the_AT losses_NN2 may_VM be_VBI assumed_VVN to_TO be_VBI non-recurring_JJ losses_NN2 while_CS depreciation_NN1 suggests_VVZ that_DD1 depreciation_NN1 of_IO the_AT value_NN1 will_VM be_VBI repeated_VVN during_II the_AT time_NNT1 that_CST the_AT company_NN1 uses_VVZ the_AT asset_NN1 ._. 
</s>
<s>
Shultze_VV0 also_RR writes_VVZ that_CST it_PPH1 is_VBZ only_RR the_AT portion_NN1 of_IO the_AT goodwill_NN1 impairment_NN1 charge_NN1 that_CST is_VBZ in_II31 excess_II32 of_II33 what_DDQ should_VM be_VBI written_VVN off_RP as_RG likely_JJ impairment_NN1 and_CC therefore_RR a_AT1 non-recurring_JJ expenditure_NN1 ._. 
</s>
<s>
This_DD1 part_NN1 should_VM be_VBI investigated_VVN so_CS21 that_CS22 investors_NN2 and_CC the_AT analysts_NN2 can_VM hold_VVI managers_NN2 responsible_JJ for_IF the_AT loss_NN1 ._. 
</s>
<s>
Schultze_VV0 also_RR mentions_VVZ that_CST in_II successful_JJ companies_NN2 ,_, it_PPH1 is_VBZ not_XX always_RR necessary_JJ to_TO write_VVI down_RP the_AT goodwill_NN1 as_CSA it_PPH1 should_VM be_VBI ._. 
</s>
<s>
The_AT reason_NN1 for_IF this_DD1 is_VBZ if_CS management_NN1 is_VBZ able_JK to_TO manufacture_VVI new_JJ internally_RR generated_VVN goodwill_NN1 that_CST replaces_VVZ the_AT impaired_JJ bought_VVD goodwill_NN1 ._. 
</s>
<s>
This_DD1 provides_VVZ a_AT1 misleading_JJ picture_NN1 to_II investors_NN2 because_CS it_PPH1 is_VBZ forbidden_VVN to_TO have_VHI internally_RR generated_VVN goodwill_NN1 as_II an_AT1 asset_NN1 on_II the_AT balance_NN1 sheet_NN1 ._. 
</s>
<s>
Conclusion_NN1 
</s>
