<s>
Discursive_JJ strategies_NN2 used_VVN in_II strategy_NN1 making_VVG for_IF a_AT1 municipality_NN1 INTRODUCTION_NN1 In_II recent_JJ years_NNT2 ,_, the_AT process_NN1 of_IO strategy_NN1 creation_NN1 and_CC decision_NN1 making_NN1 has_VHZ been_VBN examined_VVN from_II several_DA2 viewpoints_NN2 (_( Minzberg_NP1 ,_, Ahlstrand_NP1 and_CC Lampell_NP1 ,_, 2005_MC ,_, more_DAR references_NN2 needed_VVN )_) ._. 
</s>
<s>
How_RRQ strategy_NN1 is_VBZ created_VVN and_CC understood_VVN in_II the_AT organizations_NN2 has_VHZ been_VBN discussed_VVN and_CC studied_VVN from_II different_JJ viewpoints_NN2 (_( ref_NN1 ._. )_) ._. 
</s>
<s>
(_( SOME_DD OF_IO THE_AT DIFFERENT_JJ STRATEGY_NN1 VIEWPOINTS_NN2 HERE_RL )_) The_AT focus_NN1 has_VHZ been_VBN on_II the_AT importance_NN1 of_IO how_RRQ strategy_NN1 is_VBZ understood_VVN in_II organizations_NN2 and_CC how_RGQ organizational_JJ members_NN2 participate_VV0 in_II the_AT creation_NN1 of_IO strategy_NN1 (_( Mantere_NP1 &;_NULL Vaara_NP1 ,_, 2008_MC )_) ._. 
</s>
<s>
Further_RRR ,_, studies_NN2 have_VH0 been_VBN carried_VVN out_RP on_II how_RRQ to_TO bring_VVI the_AT strategy_NN1 creation_NN1 process_NN1 closer_RRR to_II the_AT people_NN in_II organizations_NN2 (_( Whittington_NP1 ,_, XXXX_NP1 )_) ._. 
</s>
<s>
As_CSA studies_NN2 on_II how_RRQ change_NN1 in_II organizations_NN2 have_VH0 come_VVN about_II (_( e.g._REX Gioia_NP1 &;_NULL Chittipeddi_NP1 ,_, 1991_MC )_) ,_, more_DAR focus_NN1 has_VHZ been_VBN put_VVN on_II the_AT role_NN1 of_IO language_NN1 and_CC narrative_JJ constructions_NN2 of_IO language_NN1 in_II organizations_NN2 ,_, and_CC during_II organizational_JJ change_NN1 (_( e.g._REX Barry_NP1 &;_NULL Elmes_NP1 ,_, 1997_MC )_) ._. 
</s>
<s>
Barry_NP1 and_CC Elmes_NP1 (_( 1997_MC :_: 430_MC )_) state_VV0 that_DD1 strategy_NN1 must_VM rank_VVI as_CSA one_MC1 of_IO the_AT most_RGT prominent_JJ ,_, influential_JJ and_CC costly_JJ stories_NN2 told_VVN in_II organizations_NN2 ,_, and_CC thus_RR ,_, studies_NN2 on_II how_RRQ these_DD2 stories_NN2 are_VBR created_VVN ,_, and_CC what_DDQ the_AT role_NN1 of_IO language_NN1 in_II the_AT stories_NN2 told_VVD ,_, have_VH0 become_VVN important_JJ ._. 
</s>
<s>
During_II recent_JJ years_NNT2 much_RR attention_NN1 has_VHZ been_VBN paid_VVN to_II the_AT role_NN1 of_IO language_NN1 and_CC of_IO rhetorics_NN2 in_II the_AT creation_NN1 of_IO strategy_NN1 (_( Suddaby_NP1 &;_NULL Greenwood_NP1 ,_, 2005_MC ;_; Vaara_NP1 ,_, Sorsa_NP1 and_CC Plli_NP1 ,_, 2010_MC ,_, Samara-Friedricks_NN2 ,_, 2003_MC )_) ._. 
</s>
<s>
The_AT importance_NN1 of_IO these_DD2 studies_NN2 is_VBZ well_RR brought_VVN out_RP by_II Samara-Friedericks_NN2 (_( 2003_MC :_: 142_MC )_) when_CS stated_VVN More_RGR recently_RR ,_, though_CS ,_, there_EX has_VHZ been_VBN a_AT1 growing_JJ recognition_NN1 of_IO the_AT need_NN1 to_TO get_VVI beyond_II the_AT narrowness_NN1 of_IO each_DD1 school_NN1 &lsqb;_( referring_VVG to_II Minzbergs_NP2 10_MC schools_NN2 of_IO strategy_NN1 &rsqb;_) :_: we_PPIS2 need_VV0 to_TO know_VVI how_RRQ strategy_NN1 formation_NN1 ,_, which_DDQ combines_VVZ all_DB these_DD2 schools_NN2 and_CC more_RRR ,_, really_RR works_VVZ (_( Minzberg_NP1 and_CC Lampel_NP1 ,_, 1999_MC :_: 29_MC )_) ._MC Still_RR ,_, there_EX are_VBR only_RR a_AT1 few_DA2 studies_NN2 on_II how_RRQ the_AT strategy_NN1 is_VBZ formulated_VVN in_II organizations_NN2 on_II micro-level_NN1 (_( Samara-Fredricks_NN2 ,_, 2003_MC )_) ._. 
</s>
<s>
The_AT micro-level_JJ process_NN1 provides_VVZ us_PPIO2 an_AT1 opportunity_NN1 to_TO look_VVI at_II how_RRQ the_AT strategy_NN1 decisions_NN2 in_II organizations_NN2 are_VBR made_VVN ,_, and_CC how_RRQ the_AT conclusions_NN2 to_II a_AT1 decisions_NN2 is_VBZ made_VVN ._. 
</s>
<s>
Even_CS21 though_CS22 top_JJ managers_NN2 are_VBR said_VVN to_TO create_VVI the_AT strategy_NN1 ,_, by_II examining_VVG the_AT mico-level_JJ processes_NN2 and_CC discussions_NN2 in_II the_AT strategy_NN1 decision_NN1 making_VVG ,_, we_PPIS2 are_VBR able_JK to_TO see_VVI what_DDQ the_AT impact_NN1 of_IO other_JJ members_NN2 in_II the_AT organizations_NN2 actually_RR is_VBZ ._. 
</s>
<s>
Further_RRR we_PPIS2 are_VBR able_JK to_TO examine_VVI how_RGQ different_JJ rhetorical_JJ strategies_NN2 ,_, ways_NN2 of_IO presenting_VVG ,_, and_CC communication_NN1 with_IW each_PPX221 other_PPX222 may_VM lead_VVI to_II different_JJ outcomes_NN2 in_II meetings_NN2 ._. 
</s>
<s>
The_AT aim_NN1 of_IO this_DD1 study_NN1 is_VBZ to_TO look_VVI at_II what_DDQ are_VBR the_AT rhetorical_JJ tools_NN2 used_VVN in_II meetings_NN2 during_II the_AT strategy_NN1 decision_NN1 process_NN1 ._. 
</s>
<s>
The_AT strategies_NN2 used_VVN in_II the_AT meetings_NN2 add_VV0 up_II21 to_II22 different_JJ strategies_NN2 that_CST the_AT members_NN2 in_II the_AT meeting_NN1 uses_VVZ to_TO get_VVI their_APPGE voice_NN1 heard_VVN or_CC their_APPGE ideas_NN2 supported_VVN in_II the_AT organization_NN1 ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO examine_VVI the_AT strategies_NN2 ,_, or_CC discursive_JJ strategies_NN2 used_VVN in_II meetings_NN2 ,_, we_PPIS2 are_VBR studying_VVG strategy_NN1 texts_NN2 from_II strategy_NN1 meetings_NN2 in_II a_AT1 municipality_NN1 in_II Finland_NP1 ._. 
</s>
<s>
It_PPH1 has_VHZ been_VBN noted_VVN that_CST discursive_JJ strategies_NN2 are_VBR used_VVN in_II these_DD2 meetings_NN2 ,_, and_CC therefore_RR ,_, it_PPH1 is_VBZ motivated_VVN to_TO look_VVI at_II these_DD2 texts_NN2 in_BCL21 order_BCL22 to_TO find_VVI different_JJ strategies_NN2 that_CST the_AT participants_NN2 in_II the_AT meetings_NN2 use_VV0 to_TO get_VVI heard_VVN and_CC the_AT determine_VV0 the_AT direction_NN1 of_IO the_AT discussons_NN2 taking_VVG place_NN1 ._. 
</s>
<s>
The_AT idea_NN1 ,_, is_VBZ to_TO carefully_RR look_VVI at_II how_RRQ the_AT discussions_NN2 develop_VV0 and_CC how_RGQ new_JJ ideas_NN2 come_VV0 about_RP ,_, and_CC then_RT from_II there_RL try_VV0 to_TO determine_VVI categories_NN2 that_CST explain_VV0 the_AT strategies_NN2 used_VVN in_II these_DD2 kinds_NN2 of_IO meetings_NN2 in_II order_NN1 to_II impact_NN1 on_II the_AT flow_NN1 of_IO the_AT discussions_NN2 but_CCB also_RR in_BCL21 order_BCL22 to_TO get_VVI your_APPGE voice_NN1 heard_VVN ._. 
</s>
<s>
The_AT strategies_NN2 are_VBR ways_NN2 of_IO legitimating_VVG the_AT ideas_NN2 in_II the_AT meetings_NN2 (_( Suddaby_NP1 &;_NULL Greenwood_NP1 ,_, 2005_MC )_) ._. 
</s>
<s>
By_II studying_VVG meetings_NN2 and_CC searching_VVG for_IF these_DD2 discursive_JJ strategies_NN2 in_BCL21 order_BCL22 to_TO legitimize_VVI ideas_NN2 ,_, we_PPIS2 hope_VV0 to_TO better_RRR understand_VVI how_RRQ strategies_NN2 come_VV0 about_RP and_CC how_RRQ the_AT stories_NN2 told_VVN in_II organizations_NN2 that_CST create_VV0 meaning_VVG for_IF the_AT people_NN in_II the_AT organizations_NN2 come_VV0 about_RP ._. 
</s>
<s>
Here_RL a_AT1 part_NN1 describing_VVG the_AT different_JJ parts_NN2 of_IO the_AT paper_NN1 ,_, as_II31 well_II32 as_II33 what_DDQ they_PPHS2 contain_VV0 ._. 
</s>
<s>
LITTERATURE_NP1 REVIEW_NP1 (_( 0,5-1_MCMC page_NN1 )_) The_AT research_NN1 within_II strategy_NN1 is_VBZ more_RGR and_CC more_RRR moving_VVG towards_II a_AT1 narrative_JJ approach_NN1 on_II strategy_NN1 (_( Barry_NP1 &;_NULL Elmes_NP1 ,_, 1997_MC )_) as_II31 well_II32 as_II33 the_AT participation_NN1 of_IO organizational_JJ members_NN2 in_II the_AT strategy_NN1 creation_NN1 process_NN1 (_( Mantere_NP1 &;_NULL Vaara_NP1 ,_, 2008_MC )_) ._. 
</s>
<s>
Barry_NP1 and_CC Elmes_NP1 (_( 1997_MC )_) focuses_VVZ on_II the_AT narrative_JJ constructions_NN2 of_IO stories_NN2 told_VVN in_II organizations_NN2 ._. 
</s>
<s>
They_PPHS2 are_VBR specially_RR interested_JJ in_II the_AT stories_NN2 on_II strategy_NN1 that_CST are_VBR told_VVN in_II the_AT organizations_NN2 and_CC what_DDQ the_AT impact_NN1 of_IO these_DD2 stories_NN2 are_VBR on_II how_RRQ the_AT strategy_NN1 is_VBZ understood_VVN and_CC realized_VVN in_II the_AT organizations_NN2 (_( Barry_NP1 &;_NULL Elmes_NP1 ,_, 1997_MC )_) ._. 
</s>
<s>
By_II understanding_VVG the_AT narratives_NN2 present_VV0 in_II organizations_NN2 ,_, we_PPIS2 are_VBR able_JK to_TO understand_VVI how_RRQ the_AT strategies_NN2 come_VV0 about_RP ,_, and_CC how_RRQ they_PPHS2 are_VBR created_VVN ._. 
</s>
<s>
As_II the_AT narrative_JJ approach_NN1 is_VBZ a_AT1 part_NN1 of_IO the_AT sensemaking_NN1 and_CC sensegiving_VVG in_II organizations_NN2 (_( Gioia_NP1 &;_NULL Chittipeddi_NP1 ,_, 1991_MC )_) ,_, they_PPHS2 contrite_JJ to_II how_RRQ the_AT strategies_NN2 decided_VVN upon_II are_VBR created_VVN ._. 
</s>
<s>
As_CSA strategy_NN1 decision_NN1 making_NN1 is_VBZ traditionally_RR viewed_VVN as_CSA something_PN1 of_IO the_AT top_JJ management_NN1 to_TO do_VDI (_( Johnson_NP1 ,_, Scholes_NP1 &;_NULL Whittington_NP1 ,_, 2008_MC )_) ,_, it_PPH1 is_VBZ no_AT wonder_NN1 ,_, that_DD1 how_RRQ they_PPHS2 understand_VV0 and_CC make_VV0 sense_NN1 of_IO the_AT organization_NN1 has_VHZ an_AT1 impact_NN1 on_II how_RRQ the_AT strategies_NN2 are_VBR created_VVN ._. 
</s>
<s>
In_II recent_JJ years_NNT2 ,_, researchers_NN2 have_VH0 pointed_VVN out_RP the_AT importance_NN1 of_IO language_NN1 and_CC rhetorics_NN2 in_II the_AT creation_NN1 process_NN1 of_IO strategy_NN1 (_( Vaara_NP1 ,_, 2010_MC ?_? 
</s>
<s>
Taking_VVG the_AT linguistic_JJ turn_NN1 seriously_RR )_) ._. 
</s>
<s>
It_PPH1 has_VHZ also_RR become_VV0 important_JJ important_JJ to_TO understand_VVI how_RRQ strategy_NN1 comes_VVZ about_RP in_II organizations_NN2 (_( Suddaby_NP1 &;_NULL Greenwood_NP1 ,_, 2005_MC ;_; Vaara_NP1 ,_, Sorsa_NP1 &;_NULL Plli_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
In_II Samara_NP1 Fredricks_NP2 (_( 2003_MC )_) it_PPH1 is_VBZ noted_VVN that_CST in_BCL21 order_BCL22 for_IF us_PPIO2 to_TO understand_VVI how_RRQ strategies_NN2 come_VV0 about_RP ,_, and_CC how_RRQ the_AT discussions_NN2 on_II the_AT strategy_NN1 decisions_NN2 develop_VV0 during_II these_DD2 meetings_NN2 ,_, micro-level_JJ analysis_NN1 on_II strategy_NN1 meetings_NN2 are_VBR requires_VVZ ._. 
</s>
<s>
Still_RR ,_, few_DA2 studies_NN2 on_II micro-level_NN1 on_II this_DD1 topic_NN1 has_VHZ so_RG far_RR been_VBN made_VVN (_( Samara-Fredericks_NP2 ,_, 2003_MC )_) ._. 
</s>
<s>
Studies_NN2 made_VVN on_II mico-level_NN1 contribute_VV0 to_II the_AT understanding_NN1 on_II how_RRQ the_AT strategy_NN1 is_VBZ created_VVN ._. 
</s>
<s>
By_II looking_VVG at_II the_AT micro-level_JJ process_NN1 ,_, we_PPIS2 are_VBR able_JK to_TO indentify_VVI different_JJ strategies_NN2 on_II how_RRQ to_TO get_VVI your_APPGE voice_NN1 heard_VVN and_CC how_RRQ to_TO affect_VVI on_II how_RRQ the_AT discussions_NN2 developer_NN1 and_CC the_AT decision_NN1 making_VVG process_NN1 ._. 
</s>
<s>
When_CS identifying_VVG these_DD2 strategies_NN2 ,_, we_PPIS2 are_VBR able_JK to_TO actually_RR see_VVI ,_, what_DDQ is_VBZ going_VVG on_RP ,_, how_RRQ the_AT ones_NN2 involved_JJ in_II the_AT decision_NN1 making_VVG base_NN1 their_APPGE decisions_NN2 one_MC1 and_CC which_DDQ strategies_NN2 that_CST are_VBR present_JJ and_CC used_VVD ._. 
</s>
<s>
By_II indentifying_VVG these_DD2 strategies_NN2 ,_, we_PPIS2 are_VBR able_JK to_TO see_VVI which_DDQ things_NN2 has_VHZ an_AT1 impact_NN1 and_CC an_AT1 role_NN1 in_II legitimating_VVG the_AT decisions_NN2 ._. 
</s>
<s>
By_II understanding_VVG how_RRQ the_AT decisions_NN2 made_VVN are_VBR legitimated_VVN ,_, we_PPIS2 can_VM understand_VVI the_AT role_NN1 of_IO different_JJ actors_NN2 and_CC the_AT importance_NN1 and_CC presence_NN1 of_IO these_DD2 actors_NN2 in_II the_AT meetings_NN2 ._. 
</s>
<s>
If_CS e.g._REX one_MC1 of_IO the_AT participants_NN2 in_II the_AT meetings_NN2 often_RR refer_VV0 to_II discussions_NN2 with_IW middle_JJ managers_NN2 and_CC other_JJ members_NN2 of_IO the_AT organization_NN1 in_BCL21 order_BCL22 to_TO legitimize_VVI his_APPGE or_CC her_APPGE idea_NN1 ,_, it_PPH1 can_VM be_VBI seen_VVN as_II a_AT1 way_NN1 to_TO get_VVI your_APPGE voice_NN1 heard_VVN but_CCB you_PPY can_VM also_RR notice_VVI ,_, that_CST the_AT members_NN2 voices_NN2 are_VBR heard_VVN in_II the_AT meetings_NN2 when_CS making_VVG decisions_NN2 upon_II strategy_NN1 and_CC thus_RR ,_, one_PN1 may_VM also_RR notice_VVI ,_, that_CST the_AT participation_NN1 of_IO members_NN2 is_VBZ an_AT1 important_JJ issue_NN1 in_II the_AT organization_NN1 ,_, as_CSA it_PPH1 provide_VV0 a_AT1 base_NN1 for_IF getting_VVG your_APPGE voice_NN1 heard_VVN in_II meetings_NN2 on_II strategy_NN1 ._. 
</s>
<s>
(_( search_NN1 for_IF references_NN2 )_) The_AT micro-level_JJ studies_NN2 provide_VV0 us_PPIO2 the_AT possibility_NN1 to_TO look_VVI at_II what_DDQ really_RR goes_VVZ on_RP in_II meetings_NN2 where_RRQ decisions_NN2 concerning_II the_AT organizations_NN2 strategies_NN2 are_VBR made_VVN ._. 
</s>
<s>
We_PPIS2 can_VM actually_RR see_VVI the_AT things_NN2 that_CST affect_VV0 on_II how_RRQ the_AT discussions_NN2 develop_VV0 and_CC what_DDQ the_AT impact_NN1 on_II different_JJ discursive_JJ strategies_NN2 in_II these_DD2 meetings_NN2 has_VHZ on_II the_AT outcome_NN1 of_IO the_AT decisions_NN2 made_VVD ._. 
</s>
<s>
Further_RRR ,_, by_II identifying_VVG the_AT different_JJ strategies_NN2 used_VVN in_II these_DD2 meetings_NN2 ,_, we_PPIS2 are_VBR actually_RR able_JK to_TO see_VVI what_DDQ the_AT role_NN1 of_IO the_AT different_JJ parts_NN2 in_II the_AT organizations_NN2 is_VBZ in_II the_AT process_NN1 of_IO deciding_VVG upon_II strategy_NN1 ._. 
</s>
<s>
(_( look_VV0 for_IF references_NN2 )_) Based_VVN on_II this_DD1 ,_, it_PPH1 can_VM be_VBI noted_VVN that_CST the_AT micro-level_JJ studies_NN2 on_II discursive_JJ strategies_NN2 during_II meetings_NN2 deciding_VVG upon_II strategy_NN1 is_VBZ motivated_VVN ._. 
</s>
<s>
By_II looking_VVG deeper_RRR at_II what_DDQ actually_RR goes_VVZ on_RP in_II these_DD2 meetings_NN2 ,_, and_CC comparing_VVG the_AT different_JJ strategies_NN2 that_CST the_AT strategists_NN2 use_VV0 in_II the_AT meetings_NN2 ,_, we_PPIS2 are_VBR able_JK to_TO understand_VVI what_DDQ the_AT impact_NN1 of_IO the_AT different_JJ actors_NN2 in_II the_AT organization_NN1 has_VHZ on_II the_AT creation_NN1 process_NN1 of_IO strategy_NN1 ._. 
</s>
<s>
By_II understanding_NN1 which_DDQ of_IO the_AT discursive_JJ strategies_NN2 that_CST are_VBR used_VVN and_CC how_RRQ they_PPHS2 affect_VV0 the_AT decision_NN1 making_VVG ,_, we_PPIS2 can_VM actually_RR see_VVI how_RGQ different_JJ things_NN2 participate_VV0 in_II the_AT decisions_NN2 made_VVN and_CC also_RR how_RRQ these_DD2 might_VM develop_VVI over_II time_NNT1 ._. 
</s>
<s>
By_II looking_VVG at_II the_AT meetings_NN2 on_II micro_NN1 level_NN1 ,_, we_PPIS2 are_VBR able_JK to_TO contribute_VVI ,_, not_XX only_RR to_II the_AT studies_NN2 mare_VV0 within_II rhetorics_NN2 in_II meetings_NN2 and_CC strategies_NN2 on_II how_RRQ to_TO get_VVI your_APPGE voice_NN1 heard_VVN in_II meeting_NN1 ,_, but_CCB also_RR contribute_VV0 to_II the_AT studies_NN2 on_II how_RGQ much_DA1 the_AT members_NN2 of_IO an_AT1 organization_NN1 actually_RR are_VBR able_JK to_TO participate_VVI in_II the_AT creation_NN1 of_IO strategies_NN2 ,_, as_RG well_RR as_CSA to_II the_AT research_NN1 on_II how_RRQ the_AT strategies_NN2 are_VBR realized_VVN in_II organizations_NN2 ._. 
</s>
<s>
(_( REFERENCES_NN2 )_) Look_VV0 in_II final_JJ version_NN1 that_CST you_PPY answer_VV0 these_DD2 questions_NN2 :_: Look_VV0 through_II the_AT articles_NN2 ,_, what_DDQ has_VHZ been_VBN previously_RR done_VDN ,_, what_DDQ are_VBR you_PPY doing_VDG ,_, why_RRQ ?_? 
</s>
<s>
Are_VBR there_RL strategies_NN2 that_CST you_PPY can_VM use_VVI ?_? are_VBR there_EX meetings_NN2 information_NN1 that_CST you_PPY can_VM use_VVI ?_? how_RRQ will_VM this_DD1 help_VVI the_AT research_NN1 done_VDN so_RG far_RR ?_? why_RRQ does_VDZ Strategy_NN1 formulation_NN1 matter_NN1 ?_? 
</s>
<s>
Why_RRQ how_RRQ to_TO formulate_VVI strategies_NN2 matter_VV0 (_( vaara_NN1 &;_NULL Mantere_NN1 participation_NN1 )_) ._. 
</s>
<s>
strategy_NN1 something_PN1 of_IO the_AT strategists_NN2 or_CC something_PN1 of_IO others_NN2 as_RR21 well_RR22 ?_? 
</s>
<s>
How_RRQ is_VBZ the_AT strategy_NN1 important_JJ ,_, why_RRQ are_VBR these_DD2 meetings_NN2 important_JJ ?_? does_VDZ it_PPH1 matter_VVI how_RRQ the_AT strategy_NN1 discussions_NN2 take_VV0 place_NN1 ?_? they_PPHS2 are_VBR blur_NN1 and_CC they_PPHS2 are_VBR confusing_JJ ,_, so_CS it_PPH1 might_VM actually_RR make_VVI a_AT1 difference_NN1 in_II what_DDQ decisions_NN2 are_VBR made_VVN ,_, depending_II21 on_II22 the_AT effect_NN1 an_AT1 impact_NN1 of_IO the_AT strategies_NN2 used_VVN in_II meetings_NN2 THEORETICAL_JJ FRAMEWORK/METHOD_NN1 return_NN1 to_II this_DD1 ._. 
</s>
<s>
How_RRQ will_VM the_AT meetings_NN2 be_VBI looked_VVN at_II ?_? how_RRQ will_VM you_PPY determine_VVI the_AT strategies_NN2 ?_? how_RRQ will_VM you_PPY measure_VVI which_DDQ strategy_NN1 is_VBZ used_VVN more_RRR and_CC which_DDQ not_XX ._. 
</s>
<s>
how_RRQ will_VM you_PPY compare_VVI 2009_MC and_CC 2010_MC strategies_NN2 used_VVN ?_? why_RRQ these_DD2 meetings_NN2 ?_? 
</s>
<s>
Why_RRQ look_NN1 at_II the_AT ones_NN2 doing_VDG the_AT strategy_NN1 and_CC not_XX the_AT ones_NN2 implementing_VVG and_CC doing_VDG the_AT strategy_NN1 decided_VVN at_II top_NN1 ._. 
</s>
<s>
Now_RT in_II the_AT process_NN1 of_IO going_VVG through_II ways_NN2 of_IO determining_VVG the_AT strategies_NN2 ,_, understanding_VVG the_AT role_NN1 of_IO rhetorics_NN2 ,_, looking_VVG at_II the_AT meetings_NN2 and_CC why_RRQ only_JJ look_NN1 at_II how_RRQ the_AT discussion_NN1 develops_VVZ and_CC not_XX the_AT issues_NN2 as_II such_DA ._. 
</s>
<s>
The_AT idea_NN1 is_VBZ to_TO motivate_VVI why_RRQ it_PPH1 is_VBZ important_JJ to_TO look_VVI at_II the_AT strategies_NN2 not_XX the_AT issues_NN2 discussed_VVD ,_, as_II31 well_II32 as_II33 finding_VVG ways_NN2 to_TO measure_VVI how_RRQ the_AT different_JJ strategies_NN2 are_VBR used_VVN ,_, which_DDQ strategies_NN2 are_VBR used_VVN the_AT most_DAT and_CC which_DDQ strategies_NN2 less_RRR ._. 
</s>
<s>
Also_RR the_AT idea_NN1 is_VBZ to_TO measure_VVI ,_, how_RRQ the_AT usage_NN1 of_IO these_DD2 strategies_NN2 change_VV0 over_II time_NNT1 ,_, if_CS they_PPHS2 change_VV0 ._. 
</s>
<s>
MATERIAL_JJ Lahti_JJ data_NN gathered_VVN from_II meeting_VVG during_II 2005-2011_MCMC ._. 
</s>
<s>
Return_VV0 to_II this_DD1 once_RR the_AT decision_NN1 on_II which_DDQ meetings_NN2 to_TO code_VVI is_VBZ made_VVN ,_, depending_II21 on_II22 the_AT theories_NN2 and_CC measurement_NN1 tools_NN2 that_CST are_VBR used_VVN ._. 
</s>
<s>
At_II this_DD1 point_NN1 ,_, the_AT idea_NN1 is_VBZ to_TO look_VVI at_II approximately_RR 5_MC meetings_NN2 ,_, from_II 2009_MC and_CC 2010_MC that_CST are_VBR within_II the_AT same_DA context_NN1 but_CCB different_JJ time_NNT1 ,_, in_II oder_JJR to_TO look_VVI at_II which_DDQ strategies_NN2 they_PPHS2 involve_VV0 ,_, and_CC if_CS therr_NN1 has_VHZ happened_VVN a_AT1 change_NN1 in_II which_DDQ strategies_NN2 are_VBR most_RGT present_JJ ._. 
</s>
<s>
ANALYSIS_NN1 Whats_NN2 going_VVG on_RP ?_? 
</s>
<s>
What_DDQ can_VM I_PPIS1 find_VVI ?_? 
</s>
<s>
Snipits_NN2 from_II the_AT meeting_NN1 ,_, table_NN1 explaining_VVG and_CC clarifying_VVG the_AT strategies_NN2 I_PPIS1 determine_VV0 and_CC find_VV0 ._. 
</s>
<s>
DISCUSSION_NN1 CONCLUSIONS_NN2 
</s>
