<s>
GREEN_JJ PURCHASING_NN1 Introduction_NN1 Environmental_JJ issues_NN2 have_VH0 received_VVN continuous_JJ attention_NN1 and_CC immediate_JJ interest_NN1 from_II general_JJ public_NN1 recently_RR ._. 
</s>
<s>
These_DD2 issues_NN2 are_VBR discussed_VVN among_II various_JJ fields_NN2 ,_, including_II supply_NN1 chain_NN1 management_NN1 and_CC purchasing_VVG activities_NN2 ._. 
</s>
<s>
Efficient_JJ purchasing_NN1 strategies_NN2 are_VBR relevant_JJ when_CS aiming_VVG for_IF minimized_JJ costs_NN2 and_CC improvements_NN2 in_II quality_NN1 ._. 
</s>
<s>
In_II fact_NN1 ,_, purchasing_NN1 is_VBZ one_MC1 of_IO the_AT most_RGT important_JJ functions_NN2 in_II supply_NN1 chain_NN1 management_NN1 ._. 
</s>
<s>
According_II21 to_II22 Watts_NP1 ,_, Kim_NP1 &;_NULL Khan_NNA (_( 1995:3_MC )_) the_AT purchasing_NN1 function_NN1 has_VHZ not_XX been_VBN seen_VVN as_CSA such_DA an_AT1 important_JJ function_NN1 before_CS ,_, as_CSA managers_NN2 generally_RR have_VH0 considered_VVN it_PPH1 rather_RG a_AT1 low_JJ level_JJ function_NN1 ._. 
</s>
<s>
Looking_VVG at_II the_AT situation_NN1 from_II an_AT1 environmental_JJ or_CC greener_JJR perspective_NN1 has_VHZ attracted_VVN attention_NN1 recently_RR as_CSA it_PPH1 is_VBZ characteristics_NN2 of_IO these_DD2 days_NNT2 to_TO take_VVI environmental_JJ aspects_NN2 into_II account_NN1 beside_II cost_NN1 saving_NN1 and_CC maximizing_VVG revenues_NN2 etc_RA ._. 
</s>
<s>
Trends_NN2 seem_VV0 to_TO show_VVI that_CST companies_NN2 and_CC other_JJ institutions_NN2 focus_VV0 continuously_RR more_RRR on_II these_DD2 kinds_NN2 of_IO questions_NN2 ,_, which_DDQ makes_VVZ research_NN1 in_II the_AT field_NN1 important_JJ ._. 
</s>
<s>
Research_NN1 elucidates_VVZ how_RRQ purchasing_NN1 strategies_NN2 can_VM be_VBI carried_VVN out_RP in_II a_AT1 more_RGR eco-friendly_JJ fashion_NN1 and_CC what_DDQ the_AT effects_NN2 of_IO greener_JJR purchasing_NN1 strategies_NN2 are_VBR ,_, as_II31 well_II32 as_II33 what_DDQ the_AT factual_JJ benefits_NN2 for_IF the_AT companies_NN2 themselves_PPX2 are_VBR ,_, and_CC how_RRQ to_TO overcome_VVI the_AT possible_JJ challenges_NN2 and_CC difficulties_NN2 ._. 
</s>
<s>
There_EX are_VBR few_DA2 studies_NN2 concerning_II green_JJ purchasing_NN1 ,_, even_CS21 though_CS22 it_PPH1 is_VBZ a_AT1 current_JJ topic_NN1 ._. 
</s>
<s>
However_RR ,_, Min_NNU &;_NULL Galle_NP1 (_( 1997_MC )_) have_VH0 taken_VVN up_II such_DA features_NN2 as_CSA reduction_NN1 and_CC elimination_NN1 of_IO waste_NN1 in_II purchasing_NN1 ,_, facts_NN2 that_CST may_VM reshape_VVI supplier_NN1 selection_NN1 ,_, the_AT effects_NN2 of_IO green_JJ purchasing_NN1 as_RG well_RR as_CSA they_PPHS2 have_VH0 stated_VVN some_DD guidelines_NN2 for_IF companies_NN2 ._. 
</s>
<s>
Also_RR Murray_NP1 (_( 2000_MC )_) has_VHZ written_VVN about_II a_AT1 case_NN1 concerning_II effects_NN2 from_II green_JJ purchasing_NN1 and_CC has_VHZ observed_VVN that_CST proactive_JJ emphasis_NN1 on_II environmental_JJ impacts_NN2 may_VM lead_VVI to_II improved_JJ competitiveness_NN1 ._. 
</s>
<s>
Murray_NP1 (_( 2000_MC )_) has_VHZ also_RR stated_VVN that_CST there_EX are_VBR yet_RR few_DA2 cases_NN2 available_JJ in_II this_DD1 area_NN1 ._. 
</s>
<s>
Another_DD1 interesting_JJ article_NN1 by_II Min_NNU &Galle;_NULL (_( 2001_MC )_) concerning_II the_AT topic_NN1 is_VBZ a_AT1 survey_NN1 on_II green_JJ purchasing_NN1 practices_NN2 of_IO US_NP1 companies_NN2 examining_VVG the_AT types_NN2 of_IO companies_NN2 involved_JJ in_II the_AT field_NN1 and_CC the_AT reasons_NN2 for_IF the_AT companies_NN2 '_GE involvement_NN1 ._. 
</s>
<s>
Min_NNU &;_NULL Galle_NP1 (_( 2001_MC )_) states_VVZ that_CST companies_NN2 get_VV0 involved_JJ in_II green_JJ purchasing_NN1 mainly_RR because_II21 of_II22 regulations_NN2 ,_, which_DDQ might_VM have_VHI been_VBN the_AT case_NN1 at_II that_DD1 time_NNT1 but_CCB now_RT it_PPH1 is_VBZ believable_JJ and_CC expected_VVD that_CST there_EX could_VM be_VBI other_JJ relevant_JJ reasons_NN2 found_VVD as_RR21 well_RR22 ._. 
</s>
<s>
It_PPH1 is_VBZ also_RR stated_VVN by_II the_AT same_DA authors_NN2 that_CST green_JJ purchasing_NN1 is_VBZ seen_VVN more_RRR as_II a_AT1 cost_NN1 than_CSN a_AT1 profit_NN1 center_NN1 ,_, which_DDQ needs_VVZ to_TO be_VBI examined_VVN as_CSA it_PPH1 is_VBZ supposed_VVN that_CST green_JJ purchasing_NN1 has_VHZ a_AT1 positive_JJ effect_NN1 on_II the_AT company_NN1 and_CC for_REX21 instance_REX22 provides_VVZ a_AT1 competitive_JJ advantage_NN1 ._. 
</s>
<s>
Many_DA2 articles_NN2 covering_VVG green_JJ purchasing_NN1 provide_VV0 information_NN1 about_II waste_NN1 elimination_NN1 when_CS discussing_VVG this_DD1 topic_NN1 but_CCB normally_RR not_XX much_RR else_RR beyond_II this_DD1 is_VBZ discussed_VVN ._. 
</s>
<s>
There_EX are_VBR probably_RR additional_JJ aspects_NN2 to_TO be_VBI identified_VVN as_RR21 well_RR22 that_CST are_VBR linked_VVN to_II green_JJ purchasing_NN1 except_II waste_NN1 management_NN1 ._. 
</s>
<s>
Aim_VV0 and_CC research_NN1 question_NN1 The_AT aim_NN1 of_IO this_DD1 paper_NN1 is_VBZ to_TO provide_VVI information_NN1 about_II the_AT benefits_NN2 from_II green_JJ purchasing_NN1 and_CC to_TO identify_VVI how_RRQ it_PPH1 is_VBZ done_VDN and_CC the_AT reasons_NN2 why_RRQ companies_NN2 engage_VV0 in_II it_PPH1 ._. 
</s>
<s>
Doing_VDG business_NN1 in_II a_AT1 more_RGR eco-friendly_JJ fashion_NN1 provides_VVZ companies_NN2 with_IW a_AT1 positive_JJ image_NN1 ,_, but_CCB the_AT main_JJ purpose_NN1 with_IW this_DD1 study_NN1 is_VBZ to_TO bring_VVI to_II light_NN1 what_DDQ the_AT real_JJ benefits_NN2 are_VBR for_IF companies_NN2 ._. 
</s>
<s>
This_DD1 means_VVZ for_REX21 instance_REX22 how_RRQ it_PPH1 is_VBZ possible_JJ for_IF companies_NN2 to_TO minimize_VVI costs_NN2 and_CC maximize_VVI revenues_NN2 ,_, efficiency_NN1 and_CC sales_NN ,_, to_TO name_VVI a_AT1 few_DA2 ._. 
</s>
<s>
Although_CS there_EX has_VHZ been_VBN some_DD research_NN1 done_VDN in_II the_AT field_NN1 already_RR there_EX are_VBR still_RR unclear_JJ issues_NN2 ._. 
</s>
<s>
Information_NN1 on_II purchasing_VVG in_RR21 general_RR22 is_VBZ unproblematic_JJ to_TO find_VVI ,_, but_CCB information_NN1 about_II purchasing_VVG strategies_NN2 in_II a_AT1 more_RGR eco-friendly_JJ fashion_NN1 is_VBZ generally_RR still_RR limited_VVN and_CC focusing_VVG mainly_RR on_II small_JJ parts_NN2 and_CC not_XX necessarily_RR providing_VVG sufficiently_RR coverable_JJ information_NN1 ._. 
</s>
<s>
Furthermore_RR ,_, it_PPH1 would_VM be_VBI interesting_JJ to_TO investigate_VVI whether_CSW green_JJ purchasing_NN1 leads_VVZ to_II a_AT1 competitive_JJ advantage_NN1 and_CC to_II what_DDQ extent_NN1 ,_, as_II31 well_II32 as_II33 what_DDQ an_AT1 environmentally_RR friendly_JJ approach_NN1 in_II practice_NN1 contributes_VVZ to_II the_AT companies_NN2 ._. 
</s>
<s>
Structure_NN1 This_DD1 paper_NN1 will_VM have_VHI the_AT following_JJ structure_NN1 :_: first_MD discussed_VVN are_VBR purchasing_VVG strategies_NN2 in_RR21 general_RR22 and_CC linked_JJ facts_NN2 ._. 
</s>
<s>
Afterwards_RT the_AT environmental/green_JJ perspective_NN1 is_VBZ examined_VVN including_II challenges_NN2 ,_, benefits_NN2 ,_, difficulties_NN2 and_CC reasons_NN2 for_IF engagement_NN1 ._. 
</s>
<s>
Examining_VVG these_DD2 features_NN2 should_VM result_VVI in_II a_AT1 representative_JJ presentation_NN1 of_IO those_DD2 aspects_NN2 ._. 
</s>
<s>
Subsequently_RR ,_, companies_NN2 applying_VVG greener_JJR standards_NN2 in_II their_APPGE purchasing_NN1 functions_NN2 will_VM be_VBI discussed_VVN ,_, including_II the_AT types_NN2 of_IO companies_NN2 that_CST actually_RR apply_VV0 these_DD2 standards_NN2 more_RRR than_CSN others_NN2 ._. 
</s>
<s>
By_II discussing_VVG these_DD2 aspects_NN2 ,_, the_AT purpose_NN1 is_VBZ to_TO fill_VVI the_AT gaps_NN2 mentioned_VVN above_RL ,_, and_CC to_TO explain_VVI the_AT linked_JJ issues_NN2 ._. 
</s>
<s>
Background_NN1 of_IO the_AT strategic_JJ purchasing_NN1 function_NN1 The_AT area_NN1 of_IO purchasing_VVG strategies_NN2 has_VHZ received_VVN more_RRR and_CC more_DAR attention_NN1 and_CC interest_NN1 during_II the_AT last_MD decades_NNT2 ._. 
</s>
<s>
Previously_RR this_DD1 function_NN1 within_II companies_NN2 and_CC their_APPGE supply_NN1 chains_NN2 has_VHZ not_XX received_VVN that_RG much_DA1 interest_NN1 ._. 
</s>
<s>
(_( Ellram_NP1 &;_NULL Carr_NP1 ,_, 1994_MC :_: 10_MC )_) ._. 
</s>
<s>
Purchasing_NN1 has_VHZ been_VBN seen_VVN more_RRR as_II a_AT1 low_JJ ranked_JJ function_NN1 far_RR from_II being_VBG counted_VVN in_RP as_II an_AT1 important_JJ function_NN1 in_II the_AT concept_NN1 of_IO competitive_JJ strategy_NN1 ._. 
</s>
<s>
Generally_RR there_EX has_VHZ been_VBN shallow_JJ information_NN1 containing_VVG facts_NN2 primarily_RR about_II basic_JJ aspects_NN2 such_II21 as_II22 the_AT number_NN1 of_IO suppliers_NN2 &lsqb;_( &rsqb;_) pricing_VVG strategies_NN2 &lsqb;_( &rsqb;_) organization_NN1 structure_NN1 &lsqb;_( &rsqb;_) and_CC other_JJ operating_NN1 level_NN1 policies_NN2 ._. 
</s>
<s>
(_( Watts_NP1 ,_, Kim_NP1 &;_NULL Khan_NNA ,_, 1995_MC :_: 3-4_MCMC )_) ._. 
</s>
<s>
A_AT1 short_JJ historical_JJ review_NN1 supports_VVZ the_AT statement_NN1 above_RL ._. 
</s>
<s>
In_II the_AT beginning_NN1 of_IO the_AT 1970s_MC2 it_PPH1 was_VBDZ recognized_VVN that_DD1 purchasing_NN1 was_VBDZ more_DAR of_IO a_AT1 passive_JJ function_NN1 ._. 
</s>
<s>
At_II that_DD1 time_NNT1 it_PPH1 was_VBDZ asserted_VVN that_DD1 purchasing_NN1 was_VBDZ more_DAR of_IO an_AT1 administrative_JJ function_NN1 than_CSN a_AT1 strategic_JJ one_PN1 ._. 
</s>
<s>
Some_DD years_NNT2 later_RRR Porter_NP1 identified_VVD that_CST buyers_NN2 and_CC suppliers_NN2 do_VD0 have_VHI an_AT1 effect_NN1 on_II companies_NN2 competitiveness_NN1 ._. 
</s>
<s>
Eventually_RR this_DD1 led_VVD to_II increased_JJ interest_NN1 for_IF purchasing_VVG as_II a_AT1 strategic_JJ function_NN1 ,_, even_CS21 though_CS22 the_AT development_NN1 was_VBDZ still_RR quite_RG slow_JJ ._. 
</s>
<s>
It_PPH1 took_VVD as_RG late_RR as_CSA until_CS the_AT 1990s_MC2 before_CS the_AT purchasing_NN1 function_NN1 was_VBDZ integrated_VVN as_II a_AT1 considerable_JJ function_NN1 with_IW remarkable_JJ influence_NN1 on_II the_AT companies_NN2 result_VV0 ._. 
</s>
<s>
(_( Ellram_NP1 &;_NULL Carr_NP1 ,_, 1994_MC :_: 11_MC )_) Purchasing_VVG as_II a_AT1 competitive_JJ strategy_NN1 When_CS discussing_VVG supply_NN1 chains_NN2 and_CC analyzing_VVG a_AT1 companys_NN2 performance_NN1 and_CC success_NN1 ,_, it_PPH1 is_VBZ essential_JJ to_TO include_VVI the_AT purchasing_NN1 function_NN1 ._. 
</s>
<s>
According_II21 to_II22 Watts_NP1 ,_, Kim_NP1 &;_NULL Hahn_NP1 (_( 1995:3_MC )_) 55_MC %_NNU of_IO the_AT total_JJ cost_NN1 of_IO production_NN1 originates_VVZ from_II the_AT purchasing_NN1 function_NN1 ._. 
</s>
<s>
This_DD1 indicates_VVZ the_AT importance_NN1 of_IO having_VHG efficient_JJ purchasing_NN1 strategies_NN2 ._. 
</s>
<s>
The_AT importance_NN1 of_IO sourcing_VVG and_CC supplier_NN1 selection_NN1 is_VBZ relevant_JJ and_CC the_AT suppliers_NN2 have_VH0 a_AT1 wide_JJ impact_NN1 on_II aspects_NN2 such_II21 as_II22 delivery_NN1 and_CC quality_NN1 ._. 
</s>
<s>
A_ZZ1 companys_NN2 performance_NN1 ,_, profitability_NN1 and_CC success_NN1 are_VBR directly_RR linked_VVN to_II purchasing_NN1 ._. 
</s>
<s>
(_( Watts_NP1 ,_, Kim_NP1 &;_NULL Hahn_NP1 ,_, 1995:3-4_MCMC )_) Purchasing_VVG activities_NN2 Aspects_NN2 influencing_VVG the_AT purchasing_NN1 activity_NN1 are_VBR reviewed_VVN and_CC explained_VVN briefly_RR below_RL in_BCL21 order_BCL22 to_TO clarify_VVI what_DDQ green_JJ purchasing_NN1 is_VBZ based_VVN on_II ._. 
</s>
<s>
The_AT same_DA aspects_NN2 are_VBR considered_VVN in_II green_JJ purchasing_NN1 but_CCB they_PPHS2 are_VBR carried_VVN out_RP in_II a_AT1 more_RGR eco-friendly_JJ manner_NN1 ,_, paying_VVG attention_NN1 and_CC aiming_VVG for_IF more_RGR environmentally_RR conscious_JJ activities_NN2 ._. 
</s>
<s>
Supplier_NN1 identification_NN1 ,_, evaluation_NN1 and_CC selection_NN1 are_VBR significant_JJ matters_NN2 when_CS planning_VVG the_AT purchasing_NN1 strategy_NN1 ._. 
</s>
<s>
Supplier_NN1 relationships_NN2 must_VM be_VBI created_VVN and_CC when_CS good_JJ suppliers_NN2 are_VBR found_VVN the_AT relationship_NN1 must_VM be_VBI maintained_VVN ._. 
</s>
<s>
Relevant_JJ issues_NN2 to_TO consider_VVI when_CS selecting_VVG suppliers_NN2 are_VBR lead-time_JJ ,_, delivery_NN1 performance_NN1 ,_, possibility_NN1 to_TO react_VVI quickly_RR and_CC price_NN1 etc_RA ._. 
</s>
<s>
There_EX are_VBR often_RR partnerships_NN2 of_IO various_JJ degrees_NN2 to_II the_AT suppliers_NN2 ._. 
</s>
<s>
Some_DD suppliers_NN2 are_VBR more_RGR important_JJ than_CSN others_NN2 and_CC therefore_RR some_DD partnerships_NN2 are_VBR deeper_JJR and_CC the_AT cooperation_NN1 and_CC collaboration_NN1 are_VBR further_RRR developed_VVN ._. 
</s>
<s>
The_AT purchasing_NN1 strategy_NN1 varies_VVZ depending_II21 on_II22 the_AT items_NN2 that_CST are_VBR to_TO be_VBI purchased_VVN ._. 
</s>
<s>
It_PPH1 might_VM concern_VVI raw_JJ material_NN1 ,_, different_JJ components_NN2 ,_, equipment_NN1 for_IF various_JJ purposes_NN2 or_CC services_NN2 ,_, to_TO name_VVI a_AT1 few_DA2 ._. 
</s>
<s>
(_( Grant_NP1 et_RA21 al._RA22 ,_, 2006_MC :_: 100-103_MCMC )_) Green_JJ purchasing_NN1 Environmental_JJ issues_NN2 have_VH0 during_II recent_JJ years_NNT2 gained_VVD wide_JJ attention_NN1 and_CC concern_NN1 ._. 
</s>
<s>
This_DD1 phenomenon_NN1 is_VBZ reflected_VVN all_RR over_II our_APPGE society_NN1 from_II different_JJ angles_NN2 ._. 
</s>
<s>
The_AT concern_NN1 is_VBZ not_XX merely_RR a_AT1 concern_NN1 among_II individuals_NN2 but_CCB also_RR an_AT1 issue_NN1 for_IF governments_NN2 ,_, companies_NN2 ,_, industries_NN2 and_CC the_AT society_NN1 in_RR21 general_RR22 ._. 
</s>
<s>
Green_JJ purchasing_NN1 vs._II green_JJ supply_NN1 chain_NN1 management_NN1 Green_JJ supply_NN1 chain_NN1 management_NN1 (_( GSCM_NP1 )_) is_VBZ more_RGR commonly_RR occurring_VVG and_CC a_AT1 broader_JJR concept_NN1 than_CSN green_JJ purchasing_NN1 ._. 
</s>
<s>
GSCM_NP1 takes_VVZ the_AT whole_JJ supply_NN1 chain_NN1 including_II all_DB its_APPGE functions_NN2 into_II account_NN1 ._. 
</s>
<s>
Green_JJ purchasing_NN1 on_II the_AT other_JJ hand_NN1 is_VBZ one_MC1 of_IO the_AT separate_JJ functions_NN2 in_II the_AT supply_NN1 chain_NN1 ._. 
</s>
<s>
This_DD1 paper_NN1 concentrates_VVZ on_II the_AT purchasing_NN1 function_NN1 and_CC therefore_RR the_AT green_JJ supply_NN1 chain_NN1 management_NN1 concept_NN1 will_VM not_XX be_VBI covered_VVN ._. 
</s>
<s>
GSCM_NP1 is_VBZ defined_VVN below_RL in_BCL21 order_BCL22 to_TO clarify_VVI the_AT differences_NN2 between_II the_AT terms_NN2 ._. 
</s>
<s>
The_AT definition_NN1 of_IO green_JJ supply_NN1 chain_NN1 management_NN1 is_VBZ the_AT following_JJ :_: "_" integrating_VVG environmental_JJ thinking_NN1 into_II supply-chain_JJ management_NN1 ,_, including_II product_NN1 design_NN1 ,_, material_NN1 sourcing_VVG and_CC selection_NN1 ,_, manufacturing_NN1 processes_NN2 ,_, delivery_NN1 of_IO the_AT final_JJ product_NN1 to_II the_AT consumers_NN2 as_II31 well_II32 as_II33 end-of-life_JJ management_NN1 of_IO the_AT product_NN1 after_II its_APPGE useful_JJ life_NN1 "_" (_( Srivastara_NP1 ,_, 2007:3_MC )_) The_AT definition_NN1 presents_VVZ the_AT entire_JJ supply_NN1 chain_NN1 and_CC points_VVZ out_RP that_CST it_PPH1 includes_VVZ material_NN1 sourcing_VVG and_CC selection_NN1 ,_, which_DDQ indicates_VVZ that_DD1 purchasing_NN1 is_VBZ one_MC1 part_NN1 of_IO green_JJ supply_NN1 chain_NN1 management_NN1 ._. 
</s>
<s>
While_CS the_AT entire_JJ supply_NN1 chain_NN1 is_VBZ involved_VVN and_CC explained_VVN as_II a_AT1 process_NN1 with_IW many_DA2 functions_NN2 linked_VVN to_II each_PPX221 other_PPX222 ,_, green_JJ purchasing_NN1 is_VBZ instead_RR delimited_VVN and_CC concentrates_VVZ on_II the_AT purchasing_NN1 function_NN1 and_CC its_APPGE features_NN2 ._. 
</s>
<s>
A_AT1 general_JJ definition_NN1 for_IF green_JJ purchasing_NN1 is_VBZ provided_VVN by_II Min_NNU &;_NULL Galle_NP1 (_( 2001_MC )_) :_: "_" an_AT1 purchasing_NN1 practice_NN1 that_CST reduces_VVZ sources_NN2 of_IO waste_NN1 and_CC promotes_VVZ recycling_NN1 and_CC reclamation_NN1 of_IO purchased_JJ materials_NN2 without_IW adversely_RR affecting_VVG performance_NN1 requirements_NN2 of_IO such_DA materials_NN2 ._. "_" 
</s>
<s>
(_( Min_NNU &;_NULL Galle_NP1 2001_MC :_: 1223_MC )_) Green_JJ purchasing_NN1 activities_NN2 Aspects_NN2 that_CST are_VBR taken_VVN into_II consideration_NN1 when_CS striving_VVG for_IF greener_JJR purchasing_NN1 are_VBR the_AT aim_NN1 for_IF generating_VVG less_DAR waste_NN1 and_CC purchasing_VVG as_II31 well_II32 as_II33 usage_NN1 of_IO material_NN1 that_CST is_VBZ produced_VVN from_II raw_JJ materials_NN2 that_CST are_VBR more_RGR environmentally_RR friendly_JJ compared_VVN to_II other_JJ alternatives_NN2 ._. 
</s>
<s>
Another_DD1 remarkable_JJ activity_NN1 is_VBZ to_TO avoid_VVI hazardous_JJ materials_NN2 as_RG much_DA1 as_CSA possible_JJ in_BCL21 order_BCL22 to_TO avoid_VVI hazardous_JJ waste_NN1 ._. 
</s>
<s>
Succeeding_VVG in_II those_DD2 activities_NN2 requires_VVZ contribution_NN1 and_CC cooperation_NN1 with_IW suppliers_NN2 ._. 
</s>
<s>
(_( Rao_NP1 &;_NULL Hult_NP1 ,_, 2005:3_MC )_) The_AT main_JJ activities_NN2 in_II green_JJ purchasing_NN1 are_VBR careful_JJ supplier_NN1 selection_NN1 ,_, source_NN1 reduction_NN1 ,_, waste_VV0 elimination_NN1 and_CC green_JJ packaging_NN1 ._. 
</s>
<s>
Supplier_NN1 selection_NN1 is_VBZ one_MC1 major_JJ issue_NN1 for_IF facilitating_VVG green_JJ purchasing_NN1 ._. 
</s>
<s>
Factors_NN2 having_VHG an_AT1 effect_NN1 on_II supplier_NN1 choice_NN1 are_VBR liability_NN1 ,_, cost_VV0 in_II31 terms_II32 of_II33 disposal_NN1 of_IO dangerous_JJ material_NN1 ,_, and_CC fulfillment_NN1 of_IO valid_JJ regulations_NN2 ._. 
</s>
<s>
Also_RR the_AT suppliers_NN2 overall_RR environmental_JJ dedication_NN1 plays_VVZ an_AT1 important_JJ role_NN1 ._. 
</s>
<s>
(_( Min_NNU &;_NULL Galle_NP1 ,_, 1997_MC :_: 12-13_MCMC )_) ._. 
</s>
<s>
Source_NN1 reduction_NN1 can_VM be_VBI achieved_VVN for_REX21 instance_REX22 by_II putting_VVG recycling_NN1 and_CC reuse_VV0 into_II practice_NN1 ._. 
</s>
<s>
By_II purchasing_VVG smaller_JJR volumes_NN2 of_IO materials_NN2 that_CST are_VBR damaging_VVG to_II the_AT environment_NN1 or_CC cutting_VVG down_RP the_AT overall_JJ use_NN1 of_IO dangerous_JJ raw_JJ material_NN1 ,_, a_AT1 company_NN1 can_VM achieve_VVI source_NN1 reduction_NN1 ._. 
</s>
<s>
This_DD1 can_VM also_RR be_VBI achieved_VVN if_CS suppliers_NN2 are_VBR asked_VVN to_TO use_VVI as_RG little_DA1 packaging_NN1 materials_NN2 as_CSA possible_JJ and_CC preferably_RR use_VV0 only_RR returnable_JJ packages_NN2 ._. 
</s>
<s>
Reuse_VV0 might_VM appear_VVI to_TO be_VBI somewhat_RR problematic_JJ ,_, as_CSA the_AT reusable_JJ item_NN1 must_VM be_VBI robust_JJ and_CC lasting_JJ and_CC therefore_RR is_VBZ not_XX applicable_JJ to_II all_DB items_NN2 ._. 
</s>
<s>
Examples_NN2 on_II reusable_JJ items_NN2 are_VBR pallets_NN2 ,_, cardboards_NN2 and_CC paper_NN1 ,_, to_TO name_VVI a_AT1 few_DA2 ._. 
</s>
<s>
(_( Min_NNU &;_NULL Galle_NP1 ,_, 1997_MC :_: 13_MC )_) ._. 
</s>
<s>
Waste_VV0 elimination_NN1 is_VBZ carried_VVN out_RP by_II scrapping_VVG and_CC dumping_VVG ,_, sorting_VVG nontoxic_JJ incineration_NN1 and_CC recyclable_JJ packaging_NN1 ._. 
</s>
<s>
Waste_VV0 elimination_NN1 is_VBZ though_RR rarely_RR used_VVN compared_VVN to_II source_NN1 reduction_NN1 ._. 
</s>
<s>
Green_JJ packaging_NN1 is_VBZ absolutely_RR a_AT1 preferable_JJ activity_NN1 but_CCB it_PPH1 might_VM also_RR be_VBI a_AT1 remarkable_JJ challenge_NN1 ._. 
</s>
<s>
It_PPH1 might_VM be_VBI hard_JJ to_TO use_VVI as_RG little_DA1 packaging_NN1 material_NN1 as_CSA possible_JJ while_CS the_AT shipped_JJ products_NN2 need_VV0 to_TO be_VBI protected_VVN from_II damages_NN2 during_II transportation_NN1 ._. 
</s>
<s>
(_( Min_NNU &;_NULL Galle_NP1 ,_, 1997_MC :_: 13-14_MCMC )_) ._. 
</s>
<s>
Commitment_NN1 to_II green_JJ purchasing_NN1 Incorporation_NN1 of_IO purchasing_VVG guidelines_NN2 into_II the_AT ISO_NP1 14000_MC standard_JJ ISO_NP1 14000_MC is_VBZ a_AT1 standard_JJ series_NN providing_VVG guidelines_NN2 for_IF environmental_JJ management_NN1 systems_NN2 ._. 
</s>
<s>
The_AT guidelines_NN2 provide_VV0 information_NN1 on_II how_RRQ to_TO achieve_VVI reduced_JJ costs_NN2 and_CC inspiration_NN1 for_IF developing_VVG sustainable_JJ solutions_NN2 when_CS designing_VVG green_JJ and_CC clean_JJ solutions_NN2 ._. 
</s>
<s>
By_II applying_VVG this_DD1 standard_NN1 ,_, a_AT1 company_NN1 may_VM gain_VVI competitive_JJ advantage_NN1 ,_, which_DDQ pleases_VVZ both_RR the_AT company_NN1 (_( and_CC shareholders_NN2 )_) as_II31 well_II32 as_II33 other_JJ stakeholders_NN2 ._. 
</s>
<s>
(_( Chen_NP1 ,_, 2004_MC :_: 927_MC )_) This_DD1 standard_NN1 does_VDZ not_XX include_VVI guidelines_NN2 for_IF purchasing_VVG strategies_NN2 ,_, but_CCB Chen_NP1 (_( 2004_MC )_) emphasizes_VVZ the_AT importance_NN1 of_IO including_VVG green_JJ purchasing_NN1 into_II the_AT standard_NN1 ._. 
</s>
<s>
Incorporation_NN1 of_IO green_JJ purchasing_NN1 into_II the_AT standard_NN1 would_VM result_VVI in_II improvements_NN2 in_II environmentally_RR friendly_JJ production_NN1 including_II purchased_JJ materials_NN2 and_CC waste_VV0 management_NN1 ._. 
</s>
<s>
An_AT1 increasing_JJ number_NN1 of_IO firms_NN2 are_VBR adopting_VVG the_AT ISO_NP1 14001_MC standard_JJ and_CC have_VH0 decided_VVN to_TO use_VVI the_AT standard_NN1 as_II a_AT1 requirement_NN1 when_RRQ choosing_VVG suppliers_NN2 ._. 
</s>
<s>
This_DD1 external_JJ pressure_NN1 both_RR encourages_VVZ and_CC forces_VVZ the_AT suppliers_NN2 to_TO adopt_VVI the_AT standard_NN1 ._. 
</s>
<s>
(_( Chen_NP1 ,_, 2004:927-928_MCMC )_) Incorporation_NN1 of_IO purchasing_VVG into_II this_DD1 standard_NN1 would_VM result_VVI in_II improved_JJ green_JJ purchasing_NN1 strategies_NN2 within_II all_DB these_DD2 companies_NN2 (_( and_CC their_APPGE suppliers_NN2 )_) adopting_VVG ISO_NP1 14000_MC ._. 
</s>
<s>
(_( Chen_NP1 ,_, 2004_MC :_: 932_MC )_) Commonly_RR addressed_VVN obstacles_NN2 and_CC benefits_NN2 Min_NNU and_CC Galle_NP1 (_( 1997_MC )_) states_VVZ that_CST the_AT most_RGT common_JJ obstacles_NN2 to_II green_JJ purchasing_NN1 are_VBR first_MD of_IO all_DB cost_VV0 issues_NN2 and_CC issues_NN2 related_VVN to_II revenues_NN2 ._. 
</s>
<s>
Implementation_NN1 of_IO environmental_JJ programs_NN2 is_VBZ usually_RR experienced_VVN as_CSA very_RG costly_JJ ._. 
</s>
<s>
Further_RRR the_AT recycling_NN1 systems_NN2 and_CC reuse_VV0 are_VBR experienced_VVN as_CSA unprofitable_JJ ,_, which_DDQ makes_VVZ it_PPH1 difficult_JJ to_TO identify_VVI essential_JJ economic_JJ benefits_NN2 and_CC genuinely_RR believe_VV0 that_CST green_JJ purchasing_NN1 is_VBZ profitable_JJ for_IF the_AT company_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ also_RR difficult_JJ to_TO measure_VVI the_AT benefits_NN2 and_CC costs_NN2 related_VVN to_II green_JJ purchasing_NN1 ._. 
</s>
<s>
(_( Min_NNU &;_NULL Galle_NP1 ,_, 1997_MC :_: 15-16_MCMC )_) Despite_II these_DD2 obstacles_NN2 and_CC difficulties_NN2 connected_VVN with_IW green_JJ purchasing_NN1 there_EX are_VBR positive_JJ aspects_NN2 as_RR21 well_RR22 ._. 
</s>
<s>
The_AT positive_JJ aspects_NN2 recognized_VVN are_VBR decreased_VVN costs_NN2 associated_VVN with_IW reduction_NN1 in_II the_AT amount_NN1 of_IO disposal_NN1 and_CC liability_NN1 costs_NN2 ._. 
</s>
<s>
Additional_JJ drivers_NN2 for_IF green_JJ purchasing_NN1 are_VBR the_AT possibility_NN1 for_IF preservation_NN1 of_IO resources_NN2 and_CC the_AT positive_JJ image_NN1 a_AT1 company_NN1 gain_NN1 from_II applying_VVG greener_JJR activities_NN2 ._. 
</s>
<s>
(_( Min_NNU &;_NULL Galle_NP1 ,_, 1997:15_MC )_) Environmental_JJ purchasing_NN1 contributes_VVZ to_II a_AT1 competitive_JJ advantage_NN1 ?_? 
</s>
<s>
According_II21 to_II22 Carter_NP1 ,_, Kale_NP1 &;_NULL Grimm_NP1 (_( 2000_MC )_) ,_, environmental_JJ regulations_NN2 on_II purchasing_NN1 is_VBZ the_AT second_MD largest_JJT concern_NN1 for_IF purchasing_VVG managers_NN2 ._. 
</s>
<s>
There_EX are_VBR disagreements_NN2 whether_CSW green_JJ purchasing_NN1 activities_NN2 have_VH0 a_AT1 positive_JJ impact_NN1 on_II a_AT1 companys_NN2 performance_NN1 or_CC not_XX ,_, i.e._REX does_VDZ it_PPH1 result_VVI in_II improved_JJ economic_JJ performance_NN1 or_CC is_VBZ it_PPH1 a_AT1 matter_NN1 resulting_VVG only_RR in_II larger_JJR costs_NN2 ._. 
</s>
<s>
Carter_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2000_MC )_) states_VVZ that_CST green_JJ purchasing_NN1 might_VM result_VVI in_II a_AT1 positive_JJ impact_NN1 on_II firm_JJ performance_NN1 and_CC therefore_RR managers_NN2 should_VM emphasize_VVI these_DD2 matters_NN2 more_RRR ._. 
</s>
<s>
(_( Carter_NP1 ,_, Kale_NP1 &;_NULL Grimm_NP1 ,_, 2000_MC :_: 2_MC ,_, 7_MC )_) Positive_JJ effects_NN2 on_II firm_JJ performance_NN1 can_VM be_VBI achieved_VVN for_REX21 instance_REX22 by_II usage_NN1 of_IO recycled_JJ packaging_NN1 ._. 
</s>
<s>
Recycled_JJ materials_NN2 are_VBR offered_VVN to_II a_AT1 low_JJ price_NN1 ,_, as_CSA there_EX have_VH0 been_VBN remarkable_JJ improvements_NN2 in_II reverse_JJ logistics_NN1 during_II the_AT last_MD few_DA2 years_NNT2 ._. 
</s>
<s>
Light_JJ packaging_NN1 is_VBZ another_DD1 aspect_NN1 that_CST may_VM contribute_VVI to_II decreased_JJ costs_NN2 ,_, both_RR when_CS it_PPH1 comes_VVZ to_II packaging_NN1 and_CC transportation_NN1 costs_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ still_RR essential_JJ to_TO ensure_VVI that_CST the_AT packaging_NN1 accomplishes_VVZ its_APPGE purpose_NN1 ,_, as_CSA insufficient_JJ packaging_NN1 might_VM result_VVI in_II damaged_JJ items_NN2 during_II transportation_NN1 ._. 
</s>
<s>
Involvement_NN1 in_II product_NN1 design_NN1 enables_VVZ efficient_JJ recycling_NN1 ,_, reuse_VV0 and_CC disassembly_RR ._. 
</s>
<s>
Further_JJR aspects_NN2 to_TO consider_VVI are_VBR life-cycle_NN1 analysis_NN1 as_II31 well_II32 as_II33 committing_VVG the_AT suppliers_NN2 in_II environmental_JJ activities_NN2 ._. 
</s>
<s>
(_( Carter_NP1 ,_, Kale_NP1 &;_NULL Grimm_NP1 ,_, 2000:7_MC )_) Rao_NP1 &;_NULL Holt_NP1 (_( 2005_MC )_) supports_VVZ the_AT statement_NN1 concerning_II the_AT fact_NN1 that_CST green_JJ activities_NN2 enable_VV0 reductions_NN2 in_II costs_NN2 ,_, improved_JJ sales_NN and_CC larger_JJR market_NN1 shares_NN2 ._. 
</s>
<s>
Accomplishing_VVG these_DD2 benefits_NN2 supports_VVZ better_JJR profits_NN2 and_CC therefore_RR better_JJR economic_JJ performance_NN1 for_IF the_AT company_NN1 ._. 
</s>
<s>
When_CS waste_NN1 is_VBZ eliminated_VVN and_CC resources_NN2 utilized_VVD as_RG much_DA1 as_CSA possible_JJ ,_, also_RR the_AT costs_NN2 for_IF disposal_NN1 are_VBR minimized_VVN resulting_VVG in_II improvements_NN2 in_II the_AT economic_JJ performance_NN1 ._. 
</s>
<s>
This_DD1 means_VVZ that_CST reuse_VV0 and_CC recycling_NN1 of_IO material_NN1 is_VBZ the_AT key_NN1 to_II competitive_JJ advantage_NN1 and_CC improvements_NN2 in_II performance_NN1 ._. 
</s>
<s>
Rao_NP1 &;_NULL Holt_NP1 (_( 2005_MC ,_, 910-912_MCMC )_) According_II21 to_II22 Hamner_NP1 (_( 2006_MC )_) green_JJ purchasing_NN1 has_VHZ already_RR become_VV0 fairly_RR common_JJ when_CS speaking_VVG of_IO larger_JJR companies_NN2 ._. 
</s>
<s>
In_II these_DD2 companies_NN2 ,_, the_AT activity_NN1 has_VHZ gained_VVN status_NN1 of_IO being_VBG included_VVN in_II the_AT companys_NN2 fundamental_JJ strategy_NN1 ._. 
</s>
<s>
(_( Hamner_NN1 ,_, 2006:25_MC )_) Experiences_NN2 from_II green_JJ purchasing_NN1 Experiences_NN2 from_II US_NP1 firms_NN2 A_ZZ1 survey_NN1 conducted_VVN on_II US_NP1 firms_NN2 concerning_II their_APPGE green_JJ purchasing_NN1 experiences_NN2 provides_VVZ information_NN1 about_II aspects_NN2 having_VHG an_AT1 impact_NN1 on_II the_AT firms_NN2 behavior_NN1 and_CC commitment_NN1 to_II green_JJ purchasing_NN1 ._. 
</s>
<s>
Variables_NN2 that_CST impact_NN1 green_JJ purchasing_NN1 implementation_NN1 are_VBR presented_VVN as_II31 well_II32 as_II33 how_RRQ the_AT strategies_NN2 are_VBR linked_VVN to_II supplier_NN1 selection_NN1 ,_, waste_VV0 management_NN1 and_CC packaging_NN1 ._. 
</s>
<s>
(_( Min_NNU &;_NULL Galle_NP1 ,_, 2001_MC :_: 1222_MC )_) According_II21 to_II22 the_AT survey_NN1 ,_, the_AT pattern_NN1 is_VBZ that_CST companies_NN2 purchasing_VVG large_JJ quantities_NN2 are_VBR more_RGR involved_JJ in_II green_JJ purchasing_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ also_RR assumed_VVN that_CST these_DD2 firms_NN2 inspect_VV0 their_APPGE potential_JJ suppliers_NN2 dedication_NN1 to_II environmental_JJ issues_NN2 ._. 
</s>
<s>
This_DD1 is_VBZ possible_JJ as_CSA large_JJ firms_NN2 have_VH0 great_JJ opportunities_NN2 to_TO get_VVI competitive_JJ deals_NN2 in_II any_DD case_NN1 ._. 
</s>
<s>
It_PPH1 was_VBDZ also_RR shown_VVN that_CST firms_NN2 taking_VVG environmental_JJ regulations_NN2 more_RGR seriously_RR are_VBR more_RGR active_JJ in_II environmental_JJ issues_NN2 than_CSN other_JJ firms_NN2 ._. 
</s>
<s>
This_DD1 fact_NN1 speaks_VVZ for_IF the_AT argument_NN1 that_CST regulations_NN2 and_CC laws_NN2 are_VBR the_AT main_JJ reasons_NN2 for_IF companies_NN2 to_TO involve_VVI in_II environmental_JJ issues_NN2 and_CC implementing_VVG greener_JJR strategies_NN2 in_II their_APPGE operations_NN2 ._. 
</s>
<s>
Consequently_RR the_AT main_JJ reason_NN1 for_IF greener_JJR activities_NN2 is_VBZ not_XX generally_RR long-term_JJ goals_NN2 ;_; these_DD2 activities_NN2 are_VBR rather_RG more_RRR as_II a_AT1 cost_NN1 than_CSN something_PN1 you_PPY possibly_RR gain_VV0 from_II ._. 
</s>
<s>
(_( Min_NNU &;_NULL Galle_NP1 ,_, 2001_MC :_: 1231_MC ,_, 1233_MC )_) It_PPH1 was_VBDZ also_RR identified_VVN that_CST companies_NN2 that_CST are_VBR convinced_VVN that_DD1 recycling_NN1 contributes_VVZ to_II savings_NN2 ,_, involve_VV0 and_CC educate_VV0 their_APPGE employees_NN2 in_BCL21 order_BCL22 to_TO make_VVI the_AT recycling_NN1 and_CC reusing_VVG process_NN1 more_RGR efficient_JJ ._. 
</s>
<s>
This_DD1 involves_VVZ providing_VVG information_NN1 about_II what_DDQ kind_NN1 of_IO items_NN2 are_VBR recyclable_JJ or_CC reusable_JJ and_CC how_RRQ these_DD2 items_NN2 should_VM be_VBI treated_VVN ._. 
</s>
<s>
Information_NN1 and_CC education_NN1 are_VBR prerequisites_NN2 for_IF potential_JJ savings_NN2 from_II green_JJ purchasing_NN1 ._. 
</s>
<s>
If_CS the_AT system_NN1 is_VBZ not_XX efficient_JJ enough_RR ,_, it_PPH1 would_VM probably_RR result_VVI in_II costs_NN2 rather_II21 than_II22 savings_NN2 ._. 
</s>
<s>
(_( Min_NNU &;_NULL Galle_NP1 ,_, 2001_MC :_: 1233_MC )_) The_AT most_RGT prevalent_JJ hindrance_NN1 to_II green_JJ purchasing_NN1 is_VBZ costs_NN2 originating_VVG from_II investments_NN2 in_II environmental_JJ programs_NN2 ,_, uneconomic_JJ recycling_NN1 ,_, and_CC uneconomic_JJ reusing_NN1 (_( Min_NNU &;_NULL Galle_NP1 ,_, 2001:1235_MC )_) ._. 
</s>
<s>
Especially_RR for_IF smaller_JJR firms_NN2 it_PPH1 is_VBZ more_RGR or_CC less_RGR impossible_JJ to_TO afford_VVI such_DA investments_NN2 ._. 
</s>
<s>
The_AT survey_NN1 proves_VVZ that_DD1 involvement_NN1 in_II green_JJ purchasing_NN1 is_VBZ rarer_JJR for_IF smaller_JJR firms_NN2 ._. 
</s>
<s>
Finally_RR ,_, it_PPH1 is_VBZ stated_VVN that_CST support_VV0 from_II top_JJ management_NN1 is_VBZ a_AT1 prerequisite_NN1 for_IF the_AT implementation_NN1 of_IO green_JJ purchasing_NN1 programs_NN2 ._. 
</s>
<s>
There_EX is_VBZ still_JJ lack_NN1 of_IO tools_NN2 for_IF the_AT measurement_NN1 of_IO environmental_JJ costs_NN2 ,_, which_DDQ makes_VVZ it_PPH1 difficult_JJ to_TO estimate_VVI what_DDQ the_AT effects_NN2 are_VBR ._. 
</s>
<s>
Estimations_NN2 and_CC planning_NN1 are_VBR often_RR the_AT first_MD step_NN1 before_II incorporating_VVG new_JJ strategies_NN2 ._. 
</s>
<s>
According_II21 to_II22 the_AT survey_NN1 factors_NN2 such_II21 as_II22 lack_NN1 of_IO environmental_JJ consciousness_NN1 ,_, economic_JJ issues_NN2 ,_, investments_NN2 as_II31 well_II32 as_II33 insufficient_JJ environmental_JJ regulations_NN2 have_VH0 remarkable_JJ impact_NN1 on_II firms_NN2 involvement_NN1 in_II green_JJ purchasing_NN1 activities_NN2 ._. 
</s>
<s>
(_( Min_NNU &;_NULL Galle_NP1 ,_, 2001:1235_MC )_) ._. 
</s>
<s>
The_AT Belfast_NP1 example_NN1 of_IO improved_JJ supplier_NN1 involvement_NN1 Purchasing_NN1 strategies_NN2 and_CC green_JJ purchasing_NN1 are_VBR functions_NN2 that_CST are_VBR often_RR related_VVN to_II business_NN1 and_CC companies_NN2 ._. 
</s>
<s>
Therefore_RR it_PPH1 is_VBZ important_JJ to_TO remember_VVI that_CST also_RR governments_NN2 and_CC governmental_JJ organizations_NN2 are_VBR involved_VVN and_CC have_VH0 these_DD2 kinds_NN2 of_IO issues_NN2 on_II their_APPGE agenda_NN1 as_RR21 well_RR22 ._. 
</s>
<s>
The_AT Belfast_NP1 City_NN1 Council_NN1 for_REX21 instance_REX22 decided_JJ to_TO implement_VVI greener_JJR purchasing_NN1 strategies_NN2 for_IF gaining_VVG improved_JJ environmental_JJ performance_NN1 but_CCB also_RR to_TO encourage_VVI local_JJ competitiveness_NN1 ._. 
</s>
<s>
(_( Murray_NP1 ,_, 2000:38_MC )_) Potential_JJ suppliers_NN2 were_VBDR first_MD of_IO all_DB compared_VVN and_CC screened_VVN ._. 
</s>
<s>
By_II arranging_VVG the_AT supply_NN1 chain_NN1 challenge_NN1 and_CC workshops_NN2 ,_, suppliers_NN2 were_VBDR informed_VVN about_II green_JJ strategies_NN2 ._. 
</s>
<s>
They_PPHS2 were_VBDR encouraged_VVN to_TO operate_VVI in_II a_AT1 more_RGR eco-_JJ friendly_JJ manner_NN1 by_II using_VVG only_RR recycled_JJ print_NN1 paper_NN1 etc_RA ._. 
</s>
<s>
The_AT participating_JJ suppliers_NN2 progresses_VVZ were_VBDR followed_VVN up_RP and_CC audits_NN2 were_VBDR conducted_VVN ._. 
</s>
<s>
This_DD1 resulted_VVD in_II involvement_NN1 and_CC improved_JJ consciousness_NN1 among_II all_DB participators_NN2 in_II these_DD2 kinds_NN2 of_IO issues_NN2 ._. 
</s>
<s>
Several_DA2 suppliers_NN2 made_VVD remarkable_JJ improvements_NN2 as_CSA they_PPHS2 became_VVD aware_JJ of_IO how_RRQ to_TO operate_VVI in_II an_AT1 environmentally_RR friendly_JJ manner_NN1 ._. 
</s>
<s>
(_( Murray_NP1 ,_, 2000:41_MC )_) This_DD1 case_NN1 shows_VVZ that_CST taking_VVG responsibility_NN1 for_IF proper_JJ education_NN1 for_IF the_AT suppliers_NN2 and_CC continuous_JJ commitment_NN1 gives_VVZ positive_JJ results_NN2 ,_, no_AT matter_NN1 if_CS it_PPH1 is_VBZ a_AT1 company_NN1 or_CC a_AT1 governmental_JJ organization_NN1 taking_VVG these_DD2 actions_NN2 ._. 
</s>
<s>
Discussion_NN1 Conclusions_NN2 
</s>
