<s>
The_AT firm_JJ internationalization_NN1 process-_NN1 proceeding_VVG from_II a_AT1 stage_NN1 approach_NN1 towards_II a_AT1 global_JJ approach_NN1 ?_? 1_MC1 ._. 
</s>
<s>
Introduction_NN1 In_II todays_NN2 globalized_VVD world_NN1 ,_, numerous_JJ products_NN2 sold_VVN at_II the_AT local_JJ grocery_NN1 store_NN1 originate_VV0 from_II outside_RL our_APPGE national_JJ borders_NN2 ._. 
</s>
<s>
For_REX21 example_REX22 the_AT bestselling_JJ peanut_NN1 butter_NN1 on_II the_AT top_JJ shelf_NN1 comes_VVZ from_II the_AT US_NP1 but_CCB is_VBZ produced_VVN in_II Estonia_NP1 where_RRQ as_II the_AT trendy_JJ garden_NN1 tools_NN2 are_VBR Japanese_JJ but_CCB manufactured_VVN in_II South_ND1 Korea_NP1 ._. 
</s>
<s>
How_RRQ did_VDD the_AT peanut_NN1 butter_NN1 respectively_RR trendy_JJ garden_NN1 tools_NN2 end_VV0 up_RP for_IF sale_NN1 at_II your_APPGE local_JJ grocery_NN1 store_NN1 ?_? 
</s>
<s>
Due_II21 to_II22 external_JJ factors_NN2 such_II21 as_II22 globalization_NN1 ,_, outsourcing_VVG and_CC virtual_JJ economy_NN1 ,_, among_II others_NN2 ,_, companies_NN2 are_VBR pushed_VVN and_CC motivated_VVN to_TO approach_VVI global_JJ markets_NN2 in_II ways_NN2 differing_VVG from_II the_AT more_RGR traditional_JJ stage_NN1 model_NN1 (_( Oviatt_NP1 &;_NULL McDougall_NP1 ,_, 1994_MC )_) ._. 
</s>
<s>
The_AT stage_NN1 approach_NN1 of_IO firm_JJ internationalization_NN1 states_VVZ that_CST companys_NN2 start_VV0 selling_VVG their_APPGE product_NN1 in_II their_APPGE home_NN1 market_NN1 ,_, in_BCL21 order_BCL22 to_TO minimize_VVI risk_NN1 and_CC uncertainty_NN1 ,_, from_II where_RRQ they_PPHS2 then_RT go_VV0 abroad_RL when_CS the_AT product_NN1 has_VHZ matured_VVN ._. 
</s>
<s>
Raymond_NP1 Vernons_NP2 Product_NN1 life_NN1 Cycle_NN1 theory_NN1 (_( 1966_MC )_) first_MD introduced_VVN in_II 1966_MC has_VHZ been_VBN crucial_JJ in_II describing_VVG the_AT stage_NN1 approach_NN1 ._. 
</s>
<s>
The_AT other_JJ possible_JJ approach_NN1 for_IF firms_NN2 internationalizing_VVG is_VBZ doing_VDG so_RG right_RR from_II the_AT beginning_NN1 ,_, a_AT1 global_JJ approach_NN1 in_II other_JJ words_NN2 ._. 
</s>
<s>
In_II this_DD1 case_NN1 foreign_JJ markets_NN2 are_VBR entered_VVN at_RR21 once_RR22 for_IF both_DB2 sourcing_VVG and_CC exporting_NN1 (_( Anderson_NP1 et_RA21 al._RA22 ,_, 2004_MC )_) ._. 
</s>
<s>
The_AT aim_NN1 of_IO this_DD1 study_NN1 is_VBZ to_TO analyze_VVI and_CC discuss_VVI whether_CSW there_EX is_VBZ a_AT1 model_NN1 for_IF internalization_NN1 processes_VVZ that_CST firms_NN2 follow_VV0 ._. 
</s>
<s>
Emphasis_NN1 will_VM be_VBI placed_VVN on_II both_DB2 the_AT stage_NN1 approach_NN1 and_CC global_JJ approach_NN1 to_II internationalization_NN1 with_IW focus_NN1 to_II seven_MC factors_NN2 presented_VVN by_II Baronchelli_NP1 and_CC Cassia_NP1 (_( 2008_MC )_) ,_, which_DDQ compel_VV0 companies_NN2 in_II todays_NN2 world_NN1 to_TO conform_VVI to_II the_AT global_JJ approach_NN1 ._. 
</s>
<s>
The_AT remainder_NN1 of_IO the_AT paper_NN1 is_VBZ structured_VVN as_CSA follows_VVZ :_: first_MD the_AT main_JJ concepts_NN2 ,_, stage_NN1 approach_NN1 with_IW a_AT1 focus_NN1 on_II Vernons_NP2 product_NN1 life_NN1 cycle_NN1 theory_NN1 and_CC the_AT global_JJ approach_NN1 focusing_VVG on_II the_AT phenomena_NN2 born_VVN global_JJ are_VBR presented_VVN ._. 
</s>
<s>
Next_MD ,_, the_AT applicability_NN1 of_IO Vernons_NP2 theory_NN1 today_RT is_VBZ discussed_VVN ._. 
</s>
<s>
This_DD1 is_VBZ followed_VVN by_II presenting_VVG Baronchellis_NP1 and_CC Cassias_NP2 (_( 2008_MC )_) analysis_NN1 of_IO the_AT main_JJ factors_NN2 driving_VVG start_VV0 up_RP companies_NN2 to_TO enter_VVI global_JJ markets_NN2 ._. 
</s>
<s>
A_AT1 comparison_NN1 of_IO the_AT two_MC approaches_NN2 will_VM then_RT presented_VVD ._. 
</s>
<s>
Finally_RR ,_, a_AT1 conclusion_NN1 and_CC implications_NN2 of_IO the_AT study_NN1 will_VM be_VBI presented_VVN ._. 
</s>
<s>
2_MC ._. 
</s>
<s>
The_AT Stage_NN1 approach_NN1 The_AT stage_NN1 approach_NN1 refers_VVZ to_II firms_NN2 proceeding_VVG from_II selling_VVG a_AT1 new_JJ product_NN1 in_II the_AT home_NN1 market_NN1 to_TO enter_VVI new_JJ markets_NN2 one_PN1 at_II a_AT1 time_NNT1 when_RRQ the_AT product_NN1 matures_VVZ ._. 
</s>
<s>
A_AT1 primary_JJ stage_NN1 approach_NN1 model_NN1 is_VBZ the_AT Product_NN1 Life_NN1 Cycle_NN1 Theory_NN1 by_II Raymond_NP1 Vernon_NP1 (_( 1966_MC )_) ,_, which_DDQ explains_VVZ the_AT internationalization_NN1 patterns_NN2 of_IO firms_NN2 ._. 
</s>
<s>
According_II21 to_II22 the_AT theory_NN1 a_AT1 new_JJ technologically_RR advanced_JJ product_NN1 is_VBZ introduced_VVN and_CC manufactured_VVN for_IF high-income_JJ takers_NN2 in_II the_AT home_NN1 market_NN1 ._. 
</s>
<s>
As_II the_AT product_NN1 matures_VVZ and_CC consumer_NN1 demand_NN1 rises_VVZ from_II other_JJ advanced_JJ countries_NN2 ,_, manufacturing_VVG gradually_RR shifts_VVZ abroad_RL ._. 
</s>
<s>
When_CS the_AT product_NN1 has_VHZ turned_VVN in_RP to_II a_AT1 commodity_NN1 ,_, production_NN1 shifts_VVZ to_II less_RGR developed_JJ countries_NN2 ,_, from_II where_RRQ the_AT product_NN1 then_RT is_VBZ imported_VVN to_II more_RGR advanced_JJ countries_NN2 ._. 
</s>
<s>
Raymond_NP1 Vernons_NP2 (_( 1966_MC )_) Product_NN1 Life_NN1 Cycle_NN1 Theory_NN1 consists_VVZ of_IO three_MC stages_NN2 :_: 1_MC1 ._. 
</s>
<s>
NEW_JJ PRODUCT_NN1 According_II21 to_II22 Vernon_NP1 (_( 1966_MC )_) US_NP1 producers_NN2 are_VBR most_RGT likely_JJ to_TO be_VBI the_AT first_MD ones_NN2 to_TO introduce_VVI a_AT1 new_JJ ,_, innovative_JJ ,_, and_CC technologically_RR advanced_JJ product_NN1 for_IF high-income_JJ consumers_NN2 in_II the_AT home_NN1 market_NN1 ._. 
</s>
<s>
The_AT US_NP1 high-income_JJ consumers_NN2 are_VBR characterized_VVN by_II low_JJ price_NN1 elasticity_NN1 and_CC are_VBR willing_JJ to_TO experiment_VVI with_IW new_JJ ,_, expensive_JJ products_NN2 ._. 
</s>
<s>
Although_CS manufacturing_NN1 of_IO a_AT1 new_JJ product_NN1 would_VM be_VBI more_RGR cost-effective_JJ abroad_RL ,_, production_NN1 facilities_NN2 are_VBR located_VVN in_II the_AT home_NN1 market_NN1 in_BCL21 order_BCL22 to_TO minimize_VVI risk_NN1 and_CC uncertainty_NN1 ._. 
</s>
<s>
Another_DD1 determining_JJ localization_NN1 factor_NN1 is_VBZ flexibility_NN1 ,_, which_DDQ is_VBZ needed_VVN when_CS experimenting_VVG with_IW optimal_JJ methods_NN2 of_IO manufacturing_NN1 ._. 
</s>
<s>
During_II the_AT introduction_NN1 face_VV0 the_AT need_NN1 for_IF flexibility_NN1 and_CC geographical_JJ proximity_NN1 weighs_VVZ in_II heavier_JJR than_CSN small_JJ cost_NN1 advantages_NN2 ,_, given_CS21 that_CS22 the_AT product_NN1 is_VBZ not_XX yet_RR standardized_VVN ._. 
</s>
<s>
(_( Vernon_NP1 1979_MC )_) 2_MC ._. 
</s>
<s>
MATURING_JJ PRODUCT_NN1 Exports_VVZ to_II markets_NN2 in_II advanced_JJ countries_NN2 further_RRR increase_VV0 through_II time_NNT1 and_CC the_AT need_NN1 for_IF flexibility_NN1 is_VBZ reduced_VVN ,_, when_CS the_AT increased_JJ demand_NN1 makes_VVZ the_AT production_NN1 process_NN1 more_RGR stable_JJ ._. 
</s>
<s>
This_DD1 makes_VVZ it_PPH1 economically_RR possible_JJ to_TO start_VVI local_JJ production_NN1 in_II the_AT advanced_JJ countries_NN2 ._. 
</s>
<s>
Foreign_JJ investments_NN2 in_II production_NN1 plants_NN2 drive_VV0 down_RP the_AT unit_NN1 costs_NN2 ,_, since_CS labor_NN1 and_CC transportation_NN1 costs_VVZ decrease_NN1 ._. 
</s>
<s>
These_DD2 production_NN1 facilities_NN2 are_VBR meant_VVN to_TO serve_VVI local_JJ markets_NN2 ,_, which_DDQ substitutes_NN2 exports_VVZ from_II the_AT firms_NN2 home_RL market_VV0 ._. 
</s>
<s>
At_II this_DD1 stage_NN1 ,_, production_NN1 still_RR needs_VVZ high_JJ skilled_JJ and_CC high_JJ paid_JJ employees_NN2 ._. 
</s>
<s>
When_CS the_AT product_NN1 matures_VVZ ,_, lower_JJR income_NN1 countries_NN2 will_VM start_VVI placing_VVG export_NN1 orders_NN2 ._. 
</s>
<s>
(_( Vernon_NP1 1979_MC )_) 3_MC ._. 
</s>
<s>
STANDARDIZED_JJ PRODUCT_NN1 During_II the_AT product_NN1 standardization_NN1 phase_NN1 ,_, production_NN1 facilities_NN2 will_VM start_VVI relocating_VVG to_II countries_NN2 with_IW lower_JJR incomes_NN2 ,_, allowing_VVG cost_NN1 savings_NN2 ._. 
</s>
<s>
Relocating_VVG to_II countries_NN2 with_IW lower_JJR incomes_NN2 is_VBZ usually_RR to_TO counter_VVI price_NN1 competition_NN1 or_CC to_TO meet_VVI increased_JJ local_JJ demand_NN1 ._. 
</s>
<s>
At_II this_DD1 stage_NN1 the_AT new_JJ production_NN1 facilities_NN2 also_RR serve_VV0 the_AT demand_NN1 from_II foreign_JJ markets_NN2 ,_, including_II the_AT initial_JJ production_NN1 market_NN1 ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, firms_NN2 will_VM maximize_VVI production_NN1 to_II low-wage_JJ countries_NN2 since_CS capital_NN1 and_CC labor_NN1 can_VM be_VBI moved_VVN around_RP ,_, but_CCB labor_NN1 can_VM not_XX ._. 
</s>
<s>
(_( Vernon_NP1 1979_MC )_) In_II 1979_MC Vernon_NP1 reconsidered_VVD his_APPGE product_NN1 life_NN1 cycle_NN1 theory_NN1 by_II stating_VVG that_CST many_DA2 of_IO the_AT critical_JJ assumptions_NN2 of_IO the_AT theory_NN1 were_VBDR weakened_VVN or_CC did_VDD not_XX hold_VVI any_DD more_DAR ,_, the_AT economical_JJ differences_NN2 between_II advanced_JJ countries_NN2 had_VHD significantly_RR reduced_VVN with_IW time_NNT1 and_CC the_AT geographical_JJ reach_NN1 of_IO firms_NN2 had_VHD increased_VVN ._. 
</s>
<s>
However_RR ,_, Vernon_NP1 pointed_VVD out_RP that_CST the_AT theory_NN1 continued_VVD to_TO explain_VVI and_CC predict_VVI a_AT1 certain_JJ category_NN1 of_IO foreign_JJ direct_JJ investments_NN2 (_( Vernon_NP1 1979_MC )_) ._. 
</s>
<s>
3_MC ._. 
</s>
<s>
The_AT Global_JJ Approach_NN1 The_AT global_JJ approach_NN1 is_VBZ another_DD1 model_NN1 used_VMK to_TO explain_VVI the_AT internationalization_NN1 process_NN1 of_IO firms_NN2 ._. 
</s>
<s>
The_AT phenomena_NN2 of_IO starting_VVG international_JJ activities_NN2 from_II the_AT start_NN1 ,_, by_II entering_VVG multiple_JJ countries_NN2 at_RR21 once_RR22 and_CC approaching_VVG new_JJ markets_NN2 for_IF both_DB2 export_VV0 and_CC sourcing_VVG ,_, is_VBZ due_II21 to_II22 new_JJ external_JJ conditions_NN2 ,_, such_II21 as_II22 market_NN1 conditions_NN2 becoming_VVG more_RGR global_JJ ,_, new_JJ developments_NN2 in_II transportation_NN1 and_CC communication_NN1 technologies_NN2 ,_, and_CC the_AT increasing_JJ amount_NN1 of_IO people_NN with_IW international_JJ experience_NN1 (_( Madsen_NP1 &;_NULL Servais_NP1 ,_, 1997_MC )_) ._. 
</s>
<s>
The_AT Mckinsely_NP1 consultants_NN2 introduced_VVD the_AT concept_NN1 of_IO born_JJ global_JJ firms_NN2 in_II 1993_MC in_II a_AT1 survey_NN1 for_IF the_AT Australian_JJ Manufacturing_NN1 Council_NN1 ._. 
</s>
<s>
For_IF the_AT survey_NN1 310_MC emerging_JJ exporters_NN2 answered_VVD a_AT1 questionnaire_NN1 from_II which_DDQ 56_MC were_VBDR interviewed_VVN ._. 
</s>
<s>
The_AT survey_NN1 distinguished_VVD two_MC types_NN2 of_IO exporters_NN2 ,_, the_AT domestic-based_JJ firms_NN2 and_CC the_AT born_JJ global_JJ firms_NN2 ._. 
</s>
<s>
The_AT domestic_NN1 based_VVN firms_NN2 ,_, including_II 75_MC %_NNU of_IO the_AT companies_NN2 ,_, were_VBDR well_RR established_VVN in_II the_AT home_NN1 market_NN1 with_IW fair_JJ market_NN1 share_NN1 and_CC stable_JJ finances_NN2 ._. 
</s>
<s>
These_DD2 firms_NN2 primary_NN1 focused_VVN on_II the_AT home_NN1 market_NN1 and_CC had_VHD many_DA2 years_NNT2 of_IO experience_NN1 ,_, but_CCB saw_VVD exporting_VVG as_CSA their_APPGE best_JJT chance_NN1 to_TO expand_VVI (_( Rasmussen_NP1 &;_NULL Madsen_NP1 2002_MC )_) ._. 
</s>
<s>
On_II average_NN1 the_AT firms_NN2 had_VHD been_VBN in_II business_NN1 for_IF 27_MC years_NNT2 before_II starting_VVG to_TO export_VVI ,_, which_DDQ counted_VVD for_IF 20_MC %_NNU of_IO their_APPGE sales_NN (_( Branochelli_NP1 &;_NULL Cassia_NP1 2008_MC )_) ._. 
</s>
<s>
The_AT Global_JJ firms_NN2 -_- 25%_NNU of_IO the_AT group_NN1 typically_RR started_VVD exporting_VVG 2_MC years_NNT2 after_CS they_PPHS2 were_VBDR founded_VVN ._. 
</s>
<s>
In_II this_DD1 case_NN1 exports_NN2 counted_VVN for_IF 76_MC %_NNU of_IO sales_NN ._. 
</s>
<s>
Although_CS the_AT firms_NN2 were_VBDR young_JJ they_PPHS2 successfully_RR competed_VVD with_IW larger_JJR multinational_JJ companies_NN2 ,_, having_VHG a_AT1 total_JJ exports_NN2 accounting_VVG to_II approximately_RR 20_MC %_NNU ._. 
</s>
<s>
The_AT born_JJ global_JJ firms_NN2 normally_RR compete_VV0 in_II niche_NN1 markets_NN2 ,_, are_VBR both_RR flexible_JJ ,_, adaptable_JJ ,_, move_VV0 fast_RR ,_, and_CC have_VH0 innovative_JJ technology_NN1 and_CC product_NN1 design_NN1 ._. 
</s>
<s>
(_( Branochelli_NP1 &;_NULL Cassia_NP1 2008_MC )_) Rasmussen_NP1 and_CC Madsen_NP1 (_( 2002_MC )_) conclude_VV0 that_CST a_AT1 major_JJ factor_NN1 for_IF the_AT success_NN1 of_IO born_JJ global_JJ firms_NN2 is_VBZ not_XX because_CS they_PPHS2 manage_VV0 to_TO develop_VVI standardized_JJ products_NN2 but_CCB the_AT firms_NN2 ability_NN1 to_TO standardize_VVI marketing_NN1 ,_, production_NN1 etc._RA in_II a_AT1 global_JJ niche_NN1 ._. 
</s>
<s>
Another_DD1 possible_JJ reason_NN1 to_II the_AT success_NN1 of_IO these_DD2 firms_NN2 is_VBZ the_AT commitment_NN1 managers_NN2 have_VH0 to_TO internationalization_NN1 (_( McKinsey_NP1 &;_NULL Co._NP1 ,_, 1993_MC )_) ._. 
</s>
<s>
4_MC ._. 
</s>
<s>
The_AT Product_NN1 Life_NN1 Cycle_NN1 in_II a_AT1 new_JJ global_JJ context_NN1 Raymond_NP1 Vernon_NP1 (_( 1979_MC )_) stated_VVD 23_MC years_NNT2 after_CS he_PPHS1 first_MD introduced_VVD the_AT Product_NN1 life_NN1 cycle_NN1 that_CST some_DD of_IO the_AT crucial_JJ assumptions_NN2 may_VM not_XX hold_VVI any_DD more_DAR because_CS income_NN1 differences_NN2 between_II advanced_JJ nations_NN2 had_VHD dropped_VVN significantly_RR ,_, the_AT geographical_JJ reach_NN1 of_IO many_DA2 firms_NN2 had_VHD increased_VVN fundamentally_RR ,_, and_CC competitors_NN2 had_VHD become_VVN able_JK to_TO imitate_VVI products_NN2 quicker_RRR than_CSN previously_RR envisioned_VVD ._. 
</s>
<s>
However_RR ,_, Vernon_NP1 states_VVZ that_CST the_AT model_NN1 is_VBZ still_RR valid_JJ as_II a_AT1 guide_NN1 to_II behavior_NN1 for_IF companies_NN2 intending_VVG to_TO internationalize_VVI ._. 
</s>
<s>
Furthermore_RR ,_, according_II21 to_II22 Vernon_NP1 ,_, the_AT model_NN1 can_VM still_RR be_VBI applicable_JJ to_II smaller_JJR firms_NN2 ,_, which_DDQ are_VBR yet_RR to_TO create_VVI an_AT1 international_JJ network_NN1 of_IO manufacturing_NN1 subsidies_NN2 ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, the_AT model_NN1 helps_VVZ companies_NN2 at_II the_AT beginning_NN1 of_IO their_APPGE international_JJ expansion_NN1 or_CC companies_NN2 with_IW products_NN2 that_CST require_VV0 experimentation_NN1 in_BCL21 order_BCL22 to_TO understand_VVI how_RRQ the_AT competitive_JJ surroundings_NN2 change_VV0 over_II time_NNT1 ._. 
</s>
<s>
The_AT model_NN1 is_VBZ suggested_VVN to_TO be_VBI used_VVN in_II international_JJ marketing_NN1 for_IF product_NN1 planning_NN1 purposes_NN2 ._. 
</s>
<s>
(_( ProvenModels_VVZ 2011_MC )_) Another_DD1 factor_NN1 that_CST speaks_VVZ on_II31 behalf_II32 of_II33 Vernons_NP2 model_NN1 is_VBZ that_CST for_IF a_AT1 new_JJ product_NN1 to_TO succeed_VVI there_RL has_VHZ to_TO be_VBI a_AT1 market_NN1 ready_JJ ,_, a_AT1 capable_JJ industry_NN1 ,_, and_CC capital_NN1 or_CC labor_VV0 available_JJ to_TO make_VVI a_AT1 new_JJ product_NN1 succeed_VV0 ._. 
</s>
<s>
Thus_RR ,_, newly_RR invented_VVN products_NN2 foster_VV0 in_II advanced_JJ countries_NN2 where_RRQ as_RG less_RGR advanced_JJ countries_NN2 focus_VV0 on_II adapting_VVG existing_JJ products_NN2 in_BCL21 order_BCL22 to_TO create_VVI the_AT product_NN1 for_IF a_AT1 lower_JJR price_NN1 ._. 
</s>
<s>
However_RR ,_, this_DD1 argument_NN1 does_VDZ not_XX take_VVI in_RP to_TO account_VVI the_AT products_NN2 production_NN1 path_NN1 ,_, from_II introduction_NN1 to_II maturity_NN1 ._. 
</s>
<s>
Due_II21 to_II22 the_AT simplicity_NN1 of_IO the_AT model_NN1 it_PPH1 is_VBZ also_RR difficult_JJ to_TO determine_VVI in_II what_DDQ phase_VV0 a_AT1 product_NN1 is_VBZ in_II the_AT life_NN1 cycle_NN1 ,_, and_CC thus_RR it_PPH1 is_VBZ hard_JJ to_TO use_VVI as_II a_AT1 predictive_JJ model_NN1 ,_, which_DDQ could_VM help_VVI anticipate_VVI change_NN1 ._. 
</s>
<s>
(_( ProvenModels_VVZ 2011_MC )_) 5_MC ._. 
</s>
<s>
Factors_NN2 affecting_VVG the_AT choice_NN1 of_IO a_AT1 Global_JJ approach_NN1 There_EX are_VBR multiple_JJ factors_NN2 that_CST affect_VV0 start_VV0 up_RP companies_NN2 to_TO choose_VVI a_AT1 global_JJ approach_NN1 from_II the_AT beginning_NN1 ._. 
</s>
<s>
Branochelli_NN2 and_CC Cassia_NP1 (_( 2008_MC )_) state_VV0 that_CST start_VV0 up_RP companies_NN2 are_VBR compelled_VVN from_II their_APPGE inception_NN1 to_TO enter_VVI foreign_JJ markets_NN2 ,_, due_II21 to_II22 globalization_NN1 of_IO demand_NN1 and_CC supply_NN1 ._. 
</s>
<s>
Branochelli_NN2 and_CC Cassia_NP1 have_VH0 identified_VVN the_AT following_JJ 7_MC factors_NN2 as_II the_AT main_JJ reasons_NN2 driving_VVG companies_NN2 to_TO become_VVI born_JJ global_JJ ._. 
</s>
<s>
5.1_MC ._. 
</s>
<s>
Uncertainty_NN1 and_CC dynamism_NN1 in_II the_AT firms_NN2 environment_NN1 Due_II21 to_II22 the_AT changes_NN2 in_II the_AT external_JJ environment_NN1 ,_, the_AT conditions_NN2 for_IF born-global_JJ companies_NN2 have_VH0 become_VVN favorable_JJ during_II the_AT past_JJ couple_NN1 of_IO decades_NNT2 (_( Rasmussen_NP1 &;_NULL Madssen_NP1 2002_MC )_) ._. 
</s>
<s>
Madsen_NP1 and_CC Servais_NP1 (_( 1997_MC )_) have_VH0 identified_VVN three_MC main_JJ changes_NN2 in_II31 favor_II32 of_II33 born_JJ global_JJ firms_NN2 ;_; internationalization_NN1 of_IO financial_JJ markets_NN2 ,_, increased_VVD global_JJ sourcing_NN1 and_CC diffusion_NN1 of_IO more_DAR niche_NN1 markets_NN2 due_II21 to_II22 larger_JJR magnitude_NN1 of_IO specialization_NN1 in_II the_AT final_JJ markets_NN2 ._. 
</s>
<s>
Other_JJ changes_NN2 leading_VVG to_II better_JJR conditions_NN2 for_IF born_JJ globals_NN2 suggested_VVN by_II Rasmussen_NP1 and_CC Madsen_NP1 (_( 2002_MC )_) are_VBR deregulations_NN2 and_CC privatizations_NN2 ,_, faster_JJR information_NN1 flows_NN2 ,_, improved_JJ communication_NN1 and_CC transportation_NN1 networks_NN2 ,_, free_JJ movement_NN1 of_IO capital_NN1 goods_NN2 ,_, services_NN2 etc._RA 5.2_MC ._. 
</s>
<s>
The_AT home_NN1 market_VV0 The_AT size_NN1 of_IO the_AT home_NN1 market_NN1 plays_VVZ an_AT1 important_JJ role_NN1 in_II a_AT1 companys_NN2 decision_NN1 to_TO go_VVI for_IF the_AT born_JJ global_JJ approach_NN1 ._. 
</s>
<s>
The_AT domestic_JJ demand_NN1 being_VBG too_RG small_JJ is_VBZ one_MC1 of_IO the_AT most_RGT crucial_JJ factors_NN2 leading_VVG to_II rapid_JJ internationalization_NN1 of_IO firms_NN2 (_( Freeman_NN1 et_RA21 al._RA22 ,_, 2006_MC )_) ._. 
</s>
<s>
This_DD1 can_VM be_VBI related_VVN to_II the_AT stage_NN1 approach_NN1 described_VVN by_II Vernon_NP1 (_( 1966_MC )_) where_RRQ companies_NN2 expand_VV0 abroad_RL as_II a_AT1 result_NN1 of_IO the_AT home_NN1 markets_NN2 demands_NN2 being_VBG statured_VVN ._. 
</s>
<s>
Madsen_NP1 and_CC Servais_NP1 (_( 1997_MC )_) also_RR state_VV0 that_CST countries_NN2 with_IW smaller_JJR domestic_JJ markets_NN2 are_VBR more_RGR likely_JJ to_TO be_VBI born_VVN global_JJ ,_, than_CSN countries_NN2 with_IW greater_JJR domestic_JJ markets_NN2 ._. 
</s>
<s>
According_II21 to_II22 Vernon_NP1 (_( 1966_MC )_) there_EX has_VHZ to_TO be_VBI a_AT1 trigger_NN1 for_IF companies_NN2 to_TO expand_VVI abroad_RL ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 ,_, for_IF born_JJ global_JJ firms_NN2 the_AT domestic_JJ market_NN1 is_VBZ not_XX as_RG important_JJ as_CSA in_II the_AT stage_NN1 approach_NN1 ,_, since_CS the_AT born_JJ globals_NN2 are_VBR not_XX limited_VVN to_II their_APPGE domestic_JJ market_NN1 but_CCB instead_RR consider_VV0 the_AT world_NN1 as_CSA one_MC1 market_NN1 (_( Chetty_NP1 &;_NULL Cambell-Hunt_NP1 ,_, 2004_MC )_) 5.3_MC ._. 
</s>
<s>
Industry_NN1 and_CC segment_NN1 Industry_NN1 characteristics_NN2 ,_, especially_RR the_AT industry_NN1 structure_NN1 can_VM be_VBI a_AT1 determining_JJ factor_NN1 for_IF start-up_JJ companies_NN2 to_TO become_VVI born_JJ global_JJ (_( Fernhaber_NP1 et_RA21 al._RA22 ,_, 2007_MC )_) Especially_RR start-ups_NN2 in_II the_AT high-technology_JJ industry_NN1 and_CC their_APPGE internationalization_NN1 behavior_NN1 has_VHZ been_VBN the_AT focus_NN1 of_IO many_DA2 studies_NN2 (_( Branochelli_NP1 &;_NULL Cassia_NP1 ,_, 2008_MC )_) ._. 
</s>
<s>
It_PPH1 is_VBZ considered_VVN that_CST the_AT reason_NN1 behind_II the_AT rapid_JJ internalization_NN1 of_IO firms_NN2 operating_VVG in_II high-technology_NN1 based_VVN industries_NN2 is_VBZ that_CST they_PPHS2 are_VBR compelled_VVN to_TO do_VDI so_RR before_II the_AT technology_NN1 is_VBZ obsolescence_NN1 or_CC imitated_VVN (_( Andersson_NP1 et_RA21 al._RA22 ,_, 2004_MC )_) ._. 
</s>
<s>
An_AT1 alternative_JJ way_NN1 to_TO look_VVI at_II it_PPH1 is_VBZ that_CST firms_NN2 owning_VVG unique_JJ technology_NN1 create_VV0 a_AT1 competitive_JJ advantage_NN1 and_CC are_VBR thus_RR driven_VVN to_II rapid_JJ internationalization_NN1 ._. 
</s>
<s>
Fernhaber_NP1 et_RA21 al_RA22 (_( 2007_MC )_) have_VH0 concluded_VVN that_CST a_AT1 firm_JJ operating_NN1 in_II an_AT1 industry_NN1 going_VVG through_II a_AT1 growth_NN1 stage_NN1 ,_, exhibits_VVZ a_AT1 medium-level_NN1 of_IO concentration_NN1 ,_, attracts_VVZ a_AT1 higher_JJR level_NN1 of_IO venture_NN1 capital_NN1 ,_, is_VBZ knowledge_NN1 intensive_JJ and_CC is_VBZ integrated_VVN at_II a_AT1 global_JJ level_NN1 is_VBZ more_RGR likely_JJ to_TO internationalize_VVI ,_, regardless_RR of_IO the_AT firm_JJ technological_JJ level_NN1 ._. 
</s>
<s>
5.4_MC ._. 
</s>
<s>
Knowledge_NN1 availability_NN1 Both_RR in_II the_AT stage_NN1 approach_NN1 and_CC global_JJ approach_NN1 ,_, the_AT importance_NN1 of_IO knowledge_NN1 and_CC experience_NN1 is_VBZ crucial_JJ when_CS it_PPH1 comes_VVZ to_II firm_JJ internalization_NN1 ._. 
</s>
<s>
Firms_NN2 need_VV0 to_TO increase_VVI their_APPGE knowledge_NN1 concerning_II foreign_JJ markets_NN2 before_II expanding_VVG abroad_RL ,_, this_DD1 by_II having_VHG previous_JJ experimental_JJ experience_NN1 of_IO expanding_VVG to_II foreign_JJ market_NN1 (_( Johanson_NP1 &;_NULL Vahlne_NP1 1977_MC )_) ._. 
</s>
<s>
Gaining_VVG experience_NN1 and_CC experimental_JJ knowledge_NN1 takes_VVZ time_NNT1 ,_, and_CC firms_NN2 born_VVN global_JJ do_VD0 not_XX follow_VVI this_DD1 pattern_NN1 ._. 
</s>
<s>
However_RR ,_, Laanti_NP1 et_RA21 al_RA22 (_( 2007_MC )_) state_VV0 that_DD1 experience_NN1 and_CC experimental_JJ knowledge_NN1 can_VM be_VBI acquired_VVN through_II the_AT founders_NN2 and_CC managers_NN2 personal_JJ knowledge_NN1 or_CC alternatively_RR through_II interaction_NN1 and_CC sharing_VVG knowledge_NN1 with_IW local_JJ and_CC international_JJ networks_NN2 ._. 
</s>
<s>
5.5_MC ._. 
</s>
<s>
Entrepreneur_NN1 and_CC management_NN1 previous_JJ experience_NN1 Chetty_NN1 and_CC Cambell-Hunt_NP1 (_( 2004_MC )_) argue_VV0 that_CST a_AT1 reason_NN1 for_IF firms_NN2 going_VVG for_IF the_AT global_JJ approach_NN1 over_II the_AT stage_NN1 approach_NN1 is_VBZ the_AT founders_NN2 level_NN1 of_IO education_NN1 ,_, work_VV0 experience_NN1 ,_, and_CC experience_NN1 from_II living_VVG abroad_RL ._. 
</s>
<s>
It_PPH1 is_VBZ also_RR pointed_VVN out_RP that_CST managers_NN2 today_RT are_VBR more_RGR educated_JJ and_CC have_VH0 more_RGR international_JJ experience_NN1 than_CSN in_II the_AT 1970s_MC2 when_CS the_AT stage_NN1 approach_NN1 was_VBDZ first_MD developed_VVN (_( Andersson_NP1 et_RA21 al._RA22 ,_, 2004_MC )_) ._. 
</s>
<s>
People_NN with_IW prior_JJ international_JJ experience_NN1 ,_, business_NN1 networks_NN2 and_CC a_AT1 large_JJ group_NN1 of_IO international_JJ employees_NN2 are_VBR more_RGR likely_JJ to_TO create_VVI born_JJ globals_NN2 firms_NN2 (_( Madsen_NP1 &;_NULL Servais_NP1 1997_MC )_) ._. 
</s>
<s>
5.6_MC ._. 
</s>
<s>
Firms_NN2 innovativeness_NN1 and_CC innovation_NN1 skills_NN2 Innovativeness_NN1 refers_VVZ to_II the_AT firms_NN2 capacity_NN1 to_TO generate_VVI new_JJ ideas_NN2 ,_, products_NN2 and_CC services_NN2 for_IF foreign_JJ markets_NN2 and_CC its_APPGE determination_NN1 to_TO develop_VVI creative_JJ solution_NN1 to_II challenges_NN2 it_PPH1 faces._NNU (_( Branochelli_NP1 and_CC Cassia_NP1 ,_, 2008_MC )_) ._. 
</s>
<s>
The_AT relation_NN1 between_II born_JJ global_JJ start-ups_NN2 and_CC innovation_NN1 has_VHZ been_VBN analyzed_VVN broadly_RR ._. 
</s>
<s>
According_II21 to_II22 Freeman_NN1 et_RA21 al_RA22 (_( 2006_MC )_) innovativeness_NN1 ,_, proactive_JJ and_CC risk_NN1 taking_NN1 ,_, which_DDQ are_VBR part_NN1 of_IO the_AT organizational_JJ culture_NN1 ,_, make_VV0 successful_JJ born_JJ global_JJ firms_NN2 ._. 
</s>
<s>
Laanti_NP1 et_RA21 al_RA22 (_( 2006_MC )_) on_II the_AT other_JJ hand_NN1 state_VV0 that_CST the_AT reason_NN1 for_IF creating_VVG a_AT1 born_JJ global_JJ is_VBZ the_AT main_JJ innovation_NN1 ,_, which_DDQ is_VBZ often_RR developed_VVN before_II the_AT firm_NN1 is_VBZ established_VVN ._. 
</s>
<s>
Founders_NN2 experience_VV0 and_CC entrepreneurial_JJ spirit_NN1 are_VBR strongly_RR related_VVN with_IW the_AT firm_JJ innovativeness._NNU 5.7_MC ._. 
</s>
<s>
Network_NN1 links_VVZ Crucial_JJ resources_NN2 for_IF start-ups_NN2 to_TO become_VVI internationally_RR successful_JJ are_VBR networks_NN2 and_CC partnerships_NN2 (_( Chetty_NP1 &;_NULL Cumpbell-Hunt_NP1 2004_MC )_) ._. 
</s>
<s>
Madsen_NP1 and_CC Servais_NP1 (_( 1997_MC )_) argue_VV0 that_CST an_AT1 internationalization_NN1 process_NN1 can_VM not_XX be_VBI built_VVN in_II isolation_NN1 ,_, but_CCB instead_RR the_AT environmental_JJ conditions_NN2 and_CC networks_NN2 in_II which_DDQ the_AT firm_NN1 is_VBZ active_JJ ,_, need_VV0 to_TO be_VBI analysed_VVN ._. 
</s>
<s>
Laanti_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2007_MC )_) stress_VV0 the_AT need_NN1 for_IF networks_NN2 for_IF born_JJ global_JJ firms_NN2 and_CC further_RRR state_VV0 that_DD1 activity_NN1 links_NN2 and_CC resource_VV0 ties_NN2 have_VH0 a_AT1 large_JJ impact_NN1 on_II start_NN1 up_II firms_NN2 rapid_JJ expansion_NN1 ._. 
</s>
<s>
Broad_JJ networks_NN2 allow_VV0 firms_NN2 to_TO access_VVI complementary_JJ social_JJ ,_, technical_JJ and_CC commercial_JJ resources_NN2 in_II R_ZZ1 &D,;_NULL technology_NN1 ,_, production_NN1 ,_, marketing_NN1 and_CC distribution_NN1 areas_NN2 that_CST would_VM take_VVI individual_JJ companies_NN2 years_NNT2 to_TO accumulate_VVI on_II their_APPGE own_DA (_( Laanti_NP1 et_RA21 al._RA22 ,_, 2007_MC )_) ._. 
</s>
<s>
6_MC ._. 
</s>
<s>
Stage_NN1 Approach_NN1 vs_II ._. 
</s>
<s>
Global_JJ Approach_NN1 Chetty_NP1 et_RA21 al_RA22 (_( 2004_MC )_) conducted_VVD a_AT1 case_NN1 research_NN1 of_IO 16_MC successfully_RR internationalized_VVN New_NP1 Zealand_NP1 firms_NN2 ._. 
</s>
<s>
The_AT research_NN1 was_VBDZ conducted_VVN in_II the_AT mid-1980s_NN2 both_RR before_CS and_CC after_CS forces_NN2 of_IO globalization_NN1 became_VVD in_II evident_JJ in_II the_AT country_NN1 ._. 
</s>
<s>
The_AT study_NN1 results_NN2 suggest_VV0 that_CST many_DA2 of_IO the_AT factors_NN2 distinguishing_VVG the_AT born_JJ global_JJ internationalization_NN1 path_NN1 also_RR characterize_VV0 the_AT stage_NN1 approach_NN1 to_II internationalization_NN1 ,_, by_II entering_VVG Australia_NP1 ,_, an_AT1 advanced_JJ nation_NN1 ,_, which_DDQ is_VBZ also_RR the_AT closest_JJT neighboring_JJ country_NN1 ._. 
</s>
<s>
From_II there_RL on_II out_RP further_JJR internationalization_NN1 ,_, however_RR ,_, occurred_VVD according_II21 to_II22 the_AT born_JJ global_JJ model_NN1 :_: to_TO capitalize_VVI on_II the_AT potential_NN1 of_IO an_AT1 innovative_JJ product_NN1 firms_NN2 rapidly_RR entered_VVN multiple_JJ markets_NN2 using_VVG extensive_JJ network_NN1 links_NN2 ._. 
</s>
<s>
(_( Chetty_NP1 et_RA21 al._RA22 ,_, 2004_MC )_) The_AT results_NN2 imply_VV0 that_CST the_AT stage_NN1 approach_NN1 and_CC the_AT global_JJ approach_NN1 do_VD0 not_XX automatically_RR disclose_VVI each_PPX221 other_PPX222 but_CCB instead_RR the_AT study_NN1 provides_VVZ mixed_JJ support_NN1 for_IF both_DB2 approaches_NN2 ._. 
</s>
<s>
The_AT earlier_JJR phases_NN2 in_II firm_JJ internationalization_NN1 ,_, the_AT regional_JJ localization_NN1 ,_, conforms_VVZ to_II the_AT stage_NN1 approach_NN1 ,_, where_CS as_II the_AT later_JJR stages_NN2 and_CC processes_NN2 are_VBR characteristic_JJ of_IO born_JJ global_JJ firms_NN2 (_( Chetty_NP1 et_RA21 al._RA22 ,_, 2004_MC )_) ._. 
</s>
<s>
It_PPH1 is_VBZ also_RR to_TO be_VBI noted_VVN that_CST both_DB2 of_IO the_AT models_NN2 stress_VV0 many_DA2 of_IO the_AT same_DA internal_JJ and_CC external_JJ factors_NN2 ,_, crucial_JJ for_IF firm_JJ internationalization_NN1 ._. 
</s>
<s>
Factors_NN2 such_II21 as_II22 home_NN1 market_NN1 ,_, knowledge_NN1 availability_NN1 ,_, management_NN1 experience_NN1 ,_, and_CC innovation_NN1 are_VBR highly_RR important_JJ for_IF firms_NN2 wanting_VVG to_TO internationalize_VVI ._. 
</s>
<s>
Vernon_NP1 stated_VVD already_RR in_II 1979_MC that_CST some_DD of_IO the_AT critical_JJ assumptions_NN2 of_IO the_AT product_NN1 life_NN1 cycle_NN1 might_VM no_RR21 longer_RR22 hold_VVI because_II21 of_II22 changes_NN2 in_II the_AT external_JJ environment_NN1 changes_NN2 ._. 
</s>
<s>
However_RR ,_, the_AT stage_NN1 approach_NN1 is_VBZ still_RR valid_JJ ,_, according_II21 to_II22 Vernon_NP1 ,_, as_CSA a_AT1 guide_NN1 for_IF firms_NN2 wanting_VVG to_TO internationalize_VVI ._. 
</s>
<s>
Globalization_NN1 of_IO demand_NN1 and_CC supply_VV0 surely_RR has_VHZ lead_VVN start-up_JJ companies_NN2 to_TO expand_VVI in_RP to_II foreign_JJ markets_NN2 more_RGR rapidly_RR ,_, however_RRQV this_DD1 is_VBZ not_XX always_RR the_AT case_NN1 ._. 
</s>
<s>
In_II the_AT McKinsely_NP1 survey_NN1 for_IF the_AT Australian_JJ Manufacturing_NN1 Council_NN1 75_MC %_NNU were_VBDR so_JJ21 called_JJ22 domestic_NN1 based_VVN firms_NN2 that_CST had_VHD on_II average_NN1 been_VBN 27_MC years_NNT2 in_II business_NN1 before_II starting_VVG to_TO export_VVI ._. 
</s>
<s>
These_DD2 firms_NN2 did_VDD not_XX follow_VVI the_AT global_JJ approach_NN1 of_IO born_JJ globals_NN2 ,_, but_CCB instead_RR had_VHN common_JJ characteristics_NN2 of_IO both_DB2 the_AT stage_NN1 approach_NN1 and_CC the_AT global_JJ approach_NN1 ._. 
</s>
<s>
7_MC ._. 
</s>
<s>
Conclusions_NN2 and_CC further_RRR research_VV0 Yet_RR to_TO be_VBI written_VVN -There_RL is_VBZ no_AT clear_JJ model_NN1 that_CST firms_NN2 follow_VV0 ,_, the_AT stage_NN1 approach_NN1 has_VHZ explainatory_JJ power_NN1 and_CC can_VM be_VBI used_VVN as_II a_AT1 guide_NN1 but_CCB the_AT global_JJ approach_NN1 more_RGR up-to_JJ date_NN1 -External_JJ and_CC internal_JJ factors_NN2 leading_VVG to_II internationalization_NN1 (_( the_AT 7_MC factors_NN2 )_) -Recall_JJ for_IF further_RRR empirical_JJ testing_NN1 focusing_VVG on_II firm_JJ internationalization_NN1 paths_NN2 in_II industries_NN2 that_CST are_VBR more_RGR or_CC less_RGR exposed_JJ to_II the_AT competitive_JJ pressure_NN1 of_IO globalization_NN1 ._. 
</s>
