<s>
THE_AT EFFECT_NN1 OF_IO DIFFERENT_JJ PRODUCT_NN1 RANGES_VVZ ON_II CONSUMER_NN1 BEHAVIOR_NN1 Introduction_NN1 Consumer_NN1 behavior_NN1 has_VHZ been_VBN a_AT1 central_JJ topic_NN1 for_IF researchers_NN2 during_II the_AT last_MD decades_NNT2 ._. 
</s>
<s>
An_AT1 industry_NN1 where_CS research_NN1 on_II this_DD1 topic_NN1 is_VBZ very_RG relevant_JJ is_VBZ grocery_NN1 shopping_NN1 ,_, a_AT1 daily_JJ activity_NN1 nearly_RR every_AT1 adult_NN1 can_VM relate_VVI to_II ._. 
</s>
<s>
With_IW an_AT1 increasing_JJ amount_NN1 of_IO products_NN2 and_CC locations_NN2 this_DD1 previously_RR simple_JJ routine_NN1 has_VHZ presented_VVN itself_PPX1 with_IW immense_JJ variations_NN2 ._. 
</s>
<s>
Flour_NN1 ,_, milk_NN1 ,_, and_CC other_JJ necessities_NN2 can_VM today_RT be_VBI found_VVN in_II various_JJ packages_NN2 with_IW different_JJ attributes_NN2 in_II different_JJ locations_NN2 ._. 
</s>
<s>
Simultaneously_RR prices_NN2 can_VM vary_VVI from_II store_NN1 to_II store_NN1 ._. 
</s>
<s>
A_AT1 key-character_NN1 for_IF the_AT firms_NN2 to_TO maintain_VVI competitiveness_NN1 presented_VVN in_II previous_JJ research_NN1 is_VBZ product_NN1 differentiation_NN1 (_( Piana_NP1 ,_, 2003_MC )_) ._. 
</s>
<s>
The_AT concept_NN1 of_IO differentiation_NN1 can_VM be_VBI related_VVN to_II product_NN1 ranges_VVZ since_CS it_PPH1 is_VBZ a_AT1 way_NN1 for_IF stores_NN2 to_TO differentiate_VVI themselves_PPX2 from_II competition_NN1 ._. 
</s>
<s>
Large_JJ supermarkets_NN2 have_VH0 clearly_RR different_JJ product_NN1 ranges_NN2 than_CSN small_JJ local_JJ grocery_NN1 stores_NN2 ._. 
</s>
<s>
This_DD1 paper_NN1 contributes_VVZ to_II the_AT understanding_NN1 of_IO consumer_NN1 behavior_NN1 in_II31 relation_II32 to_II33 different_JJ product_NN1 ranges_NN2 ._. 
</s>
<s>
As_CSA competition_NN1 emerges_VVZ with_IW rapid_JJ pace_NN1 ,_, firms_NN2 become_VV0 increasingly_RR dependent_JJ on_II consumer_NN1 behavior_NN1 research_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ evident_JJ in_II the_AT grocery_NN1 market_NN1 ._. 
</s>
<s>
Many_DA2 cities_NN2 and_CC even_RR small_JJ towns_NN2 have_VH0 large_JJ numbers_NN2 of_IO grocery_NN1 stores_NN2 and_CC supermarkets_NN2 ._. 
</s>
<s>
The_AT apparent_JJ difference_NN1 between_II the_AT two_MC might_VM be_VBI related_VVN to_II areal_JJ size_NN1 but_CCB an_AT1 even_RR more_RGR important_JJ one_PN1 is_VBZ the_AT difference_NN1 in_II the_AT respective_JJ product_NN1 ranges_NN2 ._. 
</s>
<s>
Needless_JJ to_TO say_VVI ,_, consumers_NN2 would_VM not_XX frequent_VVI in_II both_DB2 kinds_NN2 of_IO stores_NN2 with_IW the_AT same_DA product_NN1 range_NN1 ._. 
</s>
<s>
Consequently_RR there_EX has_VHZ been_VBN a_AT1 wave_NN1 of_IO emerging_JJ grocery_NN1 stores_NN2 specialized_VVD in_RP ,_, for_REX21 example_REX22 ,_, organic_JJ products_NN2 ._. 
</s>
<s>
In_II the_AT meantime_NNT1 certain_JJ grocery_NN1 stores_NN2 acquire_VV0 larger_JJR spaces_NN2 for_IF their_APPGE operation_NN1 and_CC as_II a_AT1 result_NN1 they_PPHS2 are_VBR able_JK to_TO offer_VVI an_AT1 even_RR larger_JJR product_NN1 ranges_NN2 ._. 
</s>
<s>
A_AT1 significant_JJ research_NN1 effort_NN1 has_VHZ been_VBN directed_VVN towards_II comparing_VVG traditional_JJ purchase_NN1 behavior_NN1 with_IW e-commerce_NN1 ._. 
</s>
<s>
(_( Degeratu_NN1 ,_, Rangaswamy_NP1 ,_, &;_NULL Wu_NP1 ,_, 1998_MC )_) Thus_RR ,_, a_AT1 research_NN1 focusing_VVG on_II buyer_NN1 behavior_NN1 in_II the_AT context_NN1 of_IO different_JJ product_NN1 ranges_NN2 is_VBZ very_RG relevant_JJ ._. 
</s>
<s>
This_DD1 paper_NN1 focuses_VVZ on_II consumer_NN1 behavior_NN1 in_II different_JJ contexts_NN2 ._. 
</s>
<s>
The_AT first_MD context_NN1 is_VBZ a_AT1 small_JJ grocery_NN1 store_NN1 ._. 
</s>
<s>
The_AT second_MD one_PN1 is_VBZ a_AT1 large_JJ supermarket_NN1 ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO establish_VVI a_AT1 clear_JJ view_NN1 of_IO certain_JJ patterns_NN2 the_AT same_DA one_MC1 consumer_NN1 will_VM be_VBI observed_VVN at_II both_DB2 locations_NN2 ._. 
</s>
<s>
After_CS the_AT observations_NN2 are_VBR recorded_VVN a_AT1 brief_JJ interview_NN1 will_VM be_VBI conducted_VVN to_TO thoroughly_RR understand_VVI identified_JJ patterns_NN2 ._. 
</s>
<s>
First_MD ,_, the_AT purpose_NN1 of_IO the_AT study_NN1 is_VBZ presented_VVN ,_, followed_VVN by_II a_AT1 brief_JJ description_NN1 of_IO available_JJ literature_NN1 ._. 
</s>
<s>
The_AT third_MD section_NN1 focuses_VVZ on_II the_AT methodology_NN1 used_VVN in_II this_DD1 study_NN1 ._. 
</s>
<s>
In_II the_AT fourth_MD section_NN1 the_AT data_NN collected_VVN is_VBZ analyzed_VVN and_CC the_AT first_MD results_NN2 are_VBR presented_VVN ._. 
</s>
<s>
These_DD2 results_NN2 are_VBR then_RT summarized_VVN together_RL with_IW concluding_JJ comments_NN2 in_II the_AT fifth_MD section_NN1 ._. 
</s>
<s>
Purpose_NN1 Consumers_NN2 are_VBR regularly_RR facing_VVG situations_NN2 where_RRQ they_PPHS2 have_VH0 to_TO choose_VVI between_II certain_JJ products_NN2 everyday_JJ ._. 
</s>
<s>
This_DD1 is_VBZ the_AT case_NN1 especially_RR in_II the_AT grocery_NN1 market_NN1 ._. 
</s>
<s>
The_AT availability_NN1 of_IO products_NN2 can_VM therefore_RR be_VBI assumed_VVN to_TO influence_VVI consumer_NN1 behavior_NN1 ._. 
</s>
<s>
Consequently_RR the_AT research_NN1 question_NN1 for_IF this_DD1 qualitative_JJ study_NN1 is_VBZ formulated_VVN as_II :_: How_RRQ does_VDZ different_JJ product_NN1 ranges_NN2 affect_VV0 the_AT consumer_NN1 behavior_NN1 in_II grocery_NN1 stores_NN2 ?_? 
</s>
<s>
The_AT research_NN1 aims_VVZ to_TO find_VVI out_RP and_CC gather_VVI a_AT1 deeper_JJR understanding_NN1 of_IO why_RRQ people_NN use_VV0 two_MC or_CC more_DAR grocery_NN1 stores_NN2 ._. 
</s>
<s>
This_DD1 is_VBZ interesting_JJ to_TO know_VVI since_CS each_DD1 store_NN1 attempts_NN2 to_TO develop_VVI a_AT1 competitive_JJ advantage_NN1 ._. 
</s>
<s>
Therefore_RR ,_, this_DD1 study_NN1 will_VM look_VVI at_II how_RRQ the_AT use_NN1 of_IO different_JJ product_NN1 ranges_NN2 affects_VVZ the_AT consumer_NN1 behavior_NN1 ._. 
</s>
<s>
The_AT core_NN1 of_IO the_AT study_NN1 will_VM be_VBI to_TO identify_VVI the_AT patterns_NN2 of_IO consumer_NN1 behavior_NN1 in_II the_AT context_NN1 of_IO different_JJ product_NN1 ranges_NN2 and_CC to_TO look_VVI at_II what_DDQ type_NN1 of_IO products_NN2 the_AT consumer_NN1 buys_VVZ from_II the_AT two_MC ,_, significantly_RR different_JJ ,_, grocery_NN1 stores_NN2 ._. 
</s>
<s>
This_DD1 study_NN1 will_VM focus_VVI on_II identifying_VVG different_JJ patterns_NN2 in_II consumer_NN1 behavior_NN1 in_II a_AT1 context_NN1 of_IO different_JJ product_NN1 ranges_NN2 ._. 
</s>
<s>
The_AT study_NN1 will_VM focus_VVI on_II one_MC1 consumer_NN1 aged_VVN above_II 20_MC years_NNT2 old_JJ and_CC who_PNQS lives_VVZ alone_RR ._. 
</s>
<s>
The_AT person_NN1 chosen_VVN for_IF the_AT study_NN1 will_VM frequently_RR visit_VVI two_MC different_JJ grocery_NN1 stores_NN2 ._. 
</s>
<s>
The_AT stores_NN2 chosen_VVN for_IF the_AT study_NN1 are_VBR of_IO different_JJ character_NN1 ._. 
</s>
<s>
One_PN1 is_VBZ a_AT1 small_JJ convenience_NN1 store_NN1 (_( K-Market_NP1 Pietarinkatu_NP1 )_) and_CC the_AT other_NN1 is_VBZ a_AT1 large_JJ S-Market_NP1 (_( Kasarminkatu_NP1 )_) ._. 
</s>
<s>
The_AT choice_NN1 of_IO stores_NN2 can_VM be_VBI related_VVN to_II convenience_NN1 sampling_NN1 presented_VVN by_II Patton_NP1 (_( 2002_MC )_) ._. 
</s>
<s>
The_AT research_NN1 object_NN1 is_VBZ chosen_VVN through_II criterion_NN1 sampling_NN1 described_VVN by_II Patton_NP1 (_( 2002_MC )_) as_CSA samples_NN2 chosen_VVN based_VVN on_II a_AT1 certain_JJ criterion_NN1 ._. 
</s>
<s>
In_II this_DD1 case_NN1 the_AT criterion_NN1 is_VBZ that_CST both_DB2 study_VV0 objects_NN2 are_VBR of_IO same_DA gender_NN1 ,_, age_NN1 and_CC purchase_VV0 food_NN1 and_CC beverages_NN2 at_II the_AT same_DA two_MC locations_NN2 mentioned_VVN above_RL ._. 
</s>
<s>
(_( Patton_NN1 ,_, 2002_MC )_) The_AT methods_NN2 used_VVN will_VM be_VBI both_RR interviews_NN2 and_CC observations_NN2 ._. 
</s>
<s>
This_DD1 is_VBZ because_CS Eisenhardt_NP1 (_( 1989_MC )_) claims_VVZ that_CST it_PPH1 is_VBZ possible_JJ and_CC encouraged_VVD to_TO use_VVI two_MC or_CC more_DAR methods_NN2 (_( Eisenhardt_NP1 ,_, 1989_MC )_) ._. 
</s>
<s>
The_AT research_NN1 will_VM take_VVI place_NN1 during_II week_NNT1 7_MC in_BCL21 order_BCL22 to_TO get_VVI a_AT1 comprehensive_JJ yet_RR compatible_JJ result_NN1 ._. 
</s>
<s>
Studying_VVG the_AT purchase_NN1 behavior_NN1 of_IO the_AT two_MC consumers_NN2 during_II the_AT same_DA week_NNT1 will_VM allow_VVI more_DAR conclusions_NN2 to_TO be_VBI made_VVN since_CS each_DD1 purchase_NN1 influences_VVZ the_AT other_JJ ._. 
</s>
<s>
Even_CS21 if_CS22 no_AT general_JJ conclusions_NN2 can_VM be_VBI made_VVN after_II this_DD1 study_NN1 there_EX will_VM be_VBI certain_JJ elements_NN2 that_CST can_VM be_VBI used_VVN for_IF future_JJ research_NN1 ._. 
</s>
<s>
The_AT analysis_NN1 of_IO the_AT gathered_JJ data_NN will_VM be_VBI conducted_VVN in_II an_AT1 inductive_JJ manner_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ because_CS there_EX is_VBZ no_AT predetermined_JJ hypothesis_NN1 for_IF the_AT study_NN1 ._. 
</s>
<s>
Instead_RR ,_, all_DB knowledge_NN1 generated_VVN by_II the_AT study_NN1 will_VM be_VBI considered_VVN new_JJ ._. 
</s>
<s>
The_AT analysis_NN1 will_VM focus_VVI on_II finding_VVG certain_JJ patterns_NN2 in_II the_AT consumer_NN1 behavior_NN1 in_BCL21 order_BCL22 to_TO understand_VVI how_RRQ the_AT product_NN1 range_NN1 may_VM affect_VVI purchasing_VVG decisions_NN2 ._. 
</s>
<s>
Theory_NN1 Theory_NN1 about_II consumer_NN1 behavior_NN1 can_VM be_VBI very_RG general_JJ ._. 
</s>
<s>
It_PPH1 is_VBZ normal_JJ that_CST the_AT research_NN1 focuses_VVZ on_II general_JJ patterns_NN2 that_CST can_VM be_VBI related_VVN to_II ,_, for_REX21 example_REX22 ,_, cultural_JJ factors_NN2 ._. 
</s>
<s>
(_( Bhasin_NN1 ,_, 2010_MC )_) While_CS these_DD2 general_JJ guidelines_NN2 can_VM be_VBI of_IO tremendous_JJ help_NN1 ,_, they_PPHS2 do_VD0 not_XX present_VVI specific_JJ buying_NN1 behavior_NN1 patterns_NN2 that_CST can_VM be_VBI related_VVN to_II e.g._REX personal_JJ experiences_NN2 ._. 
</s>
<s>
This_DD1 section_NN1 will_VM present_VVI some_DD of_IO the_AT central_JJ consumer_NN1 behavior_NN1 literature_NN1 and_CC develop_VV0 a_AT1 framework_NN1 for_IF this_DD1 study_NN1 ._. 
</s>
<s>
Based_VVN on_II this_DD1 framework_NN1 an_AT1 analysis_NN1 will_VM be_VBI conducted_VVN at_II the_AT final_JJ stages_NN2 of_IO this_DD1 study_NN1 to_TO potentially_RR create_VVI new_JJ influencing_JJ factors_NN2 or_CC other_JJ interesting_JJ patterns_NN2 ._. 
</s>
<s>
Shah_NP1 (_( 2010_MC )_) presents_VVZ an_AT1 interesting_JJ aspect_NN1 of_IO factors_NN2 that_CST influence_VV0 consumer_NN1 behavior_NN1 ;_; personal_JJ factors_NN2 ._. 
</s>
<s>
There_EX are_VBR mainly_RR four_MC personal_JJ factors_NN2 that_CST can_VM be_VBI seen_VVN to_TO affect_VVI the_AT behavior_NN1 of_IO a_AT1 consumer_NN1 ._. 
</s>
<s>
These_DD2 factors_NN2 are_VBR :_: lifestyle_NN1 ,_, economic_JJ situation_NN1 ,_, occupation_NN1 and_CC age_NN1 ._. 
</s>
<s>
(_( Shah_NP1 ,_, 2010_MC )_) Lifestyle_NN1 is_VBZ the_AT concept_NN1 of_IO the_AT person_NN1 's_GE surroundings_NN2 ,_, opinions_NN2 ,_, activities_NN2 and_CC interest_NN1 ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO gain_VVI an_AT1 understanding_NN1 of_IO the_AT influence_NN1 of_IO the_AT lifestyle_NN1 factor_NN1 the_AT methodology_NN1 needs_VVZ to_TO be_VBI well_RR formulated_VVN and_CC adapted_VVN to_II a_AT1 suitable_JJ context_NN1 ._. 
</s>
<s>
The_AT economic_JJ situation_NN1 of_IO the_AT customer_NN1 basically_RR depends_VVZ on_II the_AT monthly_JJ income_NN1 ._. 
</s>
<s>
These_DD2 factors_NN2 can_VM be_VBI very_RG decisive_JJ with_II31 regard_II32 to_II33 the_AT product_NN1 choices_NN2 ._. 
</s>
<s>
If_CS the_AT consumer_NN1 has_VHZ a_AT1 high_JJ income_NN1 or_CC a_AT1 large_JJ amount_NN1 of_IO available_JJ funds_NN2 then_RT the_AT choice_NN1 of_IO products_NN2 will_VM be_VBI directed_VVN to_II more_RGR expensive_JJ products_NN2 ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 ,_, if_CS the_AT consumer_NN1 has_VHZ a_AT1 low_JJ monthly_JJ income_NN1 or_CC a_AT1 small_JJ amount_NN1 of_IO available_JJ funds_NN2 ,_, then_RT the_AT choice_NN1 of_IO products_NN2 will_VM be_VBI directed_VVN towards_II more_RGR inexpensive_JJ products_NN2 ._. 
</s>
<s>
(_( Shah_NP1 ,_, 2010_MC )_) According_II21 to_II22 Shah_NP1 (_( 2010_MC )_) the_AT consumer_NN1 's_GE occupation_NN1 can_VM affect_VVI the_AT consumer_NN1 behavior_NN1 ._. 
</s>
<s>
The_AT justification_NN1 for_IF this_DD1 statement_NN1 is_VBZ that_CST "_" a_AT1 marketing_NN1 manager_NN1 of_IO an_AT1 organization_NN1 will_VM try_VVI to_TO purchase_VVI business_NN1 suits_NN2 ,_, whereas_CS a_AT1 low_JJ level_JJ worker_NN1 in_II the_AT same_DA organization_NN1 will_VM purchase_VVI rugged_JJ working_JJ clothes_NN2 ._. "_" 
</s>
<s>
(_( Shah_NP1 ,_, 2010_MC )_) It_PPH1 can_VM be_VBI expected_VVN that_CST the_AT occupation_NN1 of_IO the_AT consumer_NN1 might_VM have_VHI an_AT1 influence_NN1 on_II the_AT behavior_NN1 of_IO a_AT1 consumer_NN1 since_CS this_DD1 factor_NN1 can_VM also_RR be_VBI strongly_RR related_VVN to_II the_AT lifestyle_NN1 and_CC economic_JJ situation_NN1 ._. 
</s>
<s>
The_AT last_MD factor_NN1 presented_VVN in_II Shah_NP1 (_( 2010_MC )_) is_VBZ the_AT age_NN1 of_IO the_AT consumer_NN1 ._. 
</s>
<s>
The_AT age_NN1 of_IO the_AT consumer_NN1 is_VBZ related_VVN to_II his_APPGE or_CC her_APPGE stage_NN1 of_IO the_AT lifecycle_NN1 ._. 
</s>
<s>
Between_II these_DD2 stages_NN2 the_AT behavior_NN1 can_VM change_VVI drastically_RR ,_, thus_RR impacting_VVG the_AT behavior_NN1 significantly_RR ._. 
</s>
<s>
(_( Shah_NP1 ,_, 2010_MC )_) This_DD1 research_NN1 will_VM focus_VVI on_RP ,_, what_DDQ can_VM be_VBI regarded_VVN as_II ,_, the_AT first_MD stage_NN1 of_IO the_AT consumer_NN1 behavior_NN1 lifecycle_NN1 ;_; an_AT1 unmarried_JJ ,_, single_JJ household_NN1 consumer_NN1 ._. 
</s>
<s>
The_AT data_NN collected_VVN in_II this_DD1 study_NN1 can_VM be_VBI categorized_VVN according_II21 to_II22 the_AT factors_NN2 presented_VVN above_RL ._. 
</s>
<s>
The_AT impact_NN1 of_IO each_DD1 factor_NN1 will_VM be_VBI assessed_VVN in_II different_JJ contexts_NN2 of_IO different_JJ product_NN1 ranges_NN2 ._. 
</s>
<s>
Method_NN1 description_NN1 and_CC justification_NN1 In_II this_DD1 study_NN1 methodology_NN1 can_VM relate_VVI to_II three_MC different_JJ phases_NN2 ._. 
</s>
<s>
Firstly_RR ,_, certain_JJ methods_NN2 will_VM be_VBI used_VVN in_BCL21 order_BCL22 to_TO justify_VVI the_AT sampling_NN1 ._. 
</s>
<s>
Secondly_RR ,_, methods_NN2 will_VM be_VBI used_VVN for_IF data_NN collection_NN1 ._. 
</s>
<s>
Thirdly_RR ,_, the_AT data_NN collected_VVN will_VM be_VBI analyzed_VVN through_II methods_NN2 specified_VVN in_II this_DD1 section_NN1 ._. 
</s>
<s>
Prior_II21 to_II22 presenting_VVG and_CC justifying_VVG each_DD1 method_NN1 chosen_VVN for_IF this_DD1 study_NN1 a_AT1 short_JJ discussion_NN1 regarding_II general_JJ guidelines_NN2 for_IF method_NN1 usage_NN1 is_VBZ presented_VVN ._. 
</s>
<s>
There_EX are_VBR various_JJ scholars_NN2 that_CST have_VH0 focused_VVN their_APPGE research_NN1 on_II research_NN1 methods_NN2 ._. 
</s>
<s>
Consequently_RR there_EX is_VBZ a_AT1 great_JJ deal_NN1 of_IO available_JJ literature_NN1 ._. 
</s>
<s>
Silverman_NP1 (_( 2006_MC )_) discusses_VVZ methodology_NN1 from_II a_AT1 quality_NN1 point_NN1 of_IO view_NN1 ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO achieve_VVI high_JJ quality_NN1 research_NN1 and_CC consequent_JJ results_NN2 ,_, scholars_NN2 should_VM strive_VVI to_TO use_VVI various_JJ different_JJ methods_NN2 (_( Silverman_NP1 ,_, 2006_MC ;_; Wallendorf_NP1 &;_NULL Belk_NP1 ,_, 1989_MC )_) ._. 
</s>
<s>
By_II using_VVG different_JJ methods_NN2 throughout_II the_AT research_NN1 ,_, the_AT researcher_NN1 manages_VVZ to_TO increase_VVI the_AT overall_JJ quality_NN1 and_CC eliminates_VVZ the_AT effect_NN1 of_IO errors_NN2 ._. 
</s>
<s>
The_AT use_NN1 of_IO different_JJ methods_NN2 is_VBZ called_VVN triangulation_NN1 and_CC means_VVZ that_CST different_JJ approaches_NN2 are_VBR used_VVN in_BCL21 order_BCL22 to_TO reach_VVI the_AT final_JJ outcome_NN1 of_IO a_AT1 research_NN1 (_( Silverman_NP1 ,_, 2006_MC ;_; Wallendorf_NP1 &;_NULL Belk_NP1 ,_, 1989_MC )_) ._. 
</s>
<s>
Sampling_VVG method_NN1 This_DD1 study_NN1 will_VM increase_VVI the_AT overall_JJ quality_NN1 through_II the_AT evaluation_NN1 and_CC choice_NN1 of_IO different_JJ methods_NN2 at_II various_JJ stages_NN2 ._. 
</s>
<s>
Next_MD ,_, the_AT choice_NN1 of_IO methods_NN2 will_VM be_VBI justified_VVN with_II31 regard_II32 to_II33 each_DD1 phase_NN1 of_IO this_DD1 study_NN1 ._. 
</s>
<s>
The_AT first_MD method_NN1 that_CST needs_VVZ to_TO be_VBI evaluated_VVN are_VBR related_VVN to_II sampling_NN1 ._. 
</s>
<s>
The_AT choice_NN1 of_IO the_AT samples_NN2 included_VVN in_II the_AT study_NN1 will_VM have_VHI an_AT1 influence_NN1 on_II the_AT results_NN2 presented_VVN in_II this_DD1 study_NN1 ._. 
</s>
<s>
Therefore_RR ,_, the_AT choice_NN1 of_IO sampling_VVG method_NN1 is_VBZ essential_JJ ._. 
</s>
<s>
Several_DA2 sampling_NN1 methods_NN2 seem_VV0 to_TO be_VBI appropriate_JJ in_II this_DD1 study_NN1 ._. 
</s>
<s>
However_RR ,_, in_BCL21 order_BCL22 to_TO remain_VVI realistic_JJ and_CC not_XX to_TO create_VVI challenges_NN2 for_IF the_AT study_NN1 the_AT sampling_NN1 in_II this_DD1 case_NN1 will_VM be_VBI based_VVN on_II convenience_NN1 ._. 
</s>
<s>
Convenience_NN1 sampling_NN1 is_VBZ described_VVN in_II Eisenhardt_NP1 (_( 1989_MC )_) as_II a_AT1 sampling_NN1 strategy_NN1 where_CS the_AT samples_NN2 are_VBR chosen_VVN based_VVN on_II the_AT convenience_NN1 and_CC availability_NN1 to_II the_AT researcher_NN1 (_( Eisenhardt_NP1 ,_, 1989_MC )_) ._. 
</s>
<s>
Since_CS this_DD1 study_NN1 concerns_VVZ a_AT1 consumer_NN1 there_EX is_VBZ no_AT point_NN1 in_II choosing_VVG the_AT sample_NN1 through_II any_DD other_JJ method_NN1 ._. 
</s>
<s>
Simply_RR ,_, there_EX would_VM be_VBI no_AT additional_JJ value_NN1 in_II choosing_VVG another_DD1 strategy_NN1 ._. 
</s>
<s>
By_II using_VVG convenience_NN1 sampling_NN1 resources_NN2 are_VBR saved_VVN and_CC can_VM be_VBI allocated_VVN to_II other_JJ areas_NN2 of_IO this_DD1 study_NN1 where_CS they_PPHS2 are_VBR needed_VVN ._. 
</s>
<s>
The_AT person_NN1 chosen_VVN for_IF this_DD1 study_NN1 is_VBZ a_AT1 24-year_JJ old_JJ female_NN1 who_PNQS lives_VVZ in_II a_AT1 single_JJ household_NN1 ._. 
</s>
<s>
She_PPHS1 is_VBZ a_AT1 student_NN1 in_II Economics_NN1 and_CC a_AT1 full-time_JJ worker_NN1 ._. 
</s>
<s>
She_PPHS1 was_VBDZ chosen_VVN to_II this_DD1 study_NN1 based_VVN on_II her_APPGE grocery_NN1 buying_NN1 behavior_NN1 ._. 
</s>
<s>
Data_NN collection_NN1 methods_NN2 In_II31 accordance_II32 with_II33 the_AT term_NN1 triangulation_NN1 ,_, the_AT data_NN will_VM be_VBI collected_VVN for_IF this_DD1 study_NN1 through_II two_MC methods_NN2 (_( Wallendorf_NP1 &;_NULL Belk_NP1 ,_, 1989_MC ;_; Silverman_NP1 ,_, 2006_MC )_) ._. 
</s>
<s>
The_AT data_NN will_VM be_VBI collected_VVN first_MD through_II observations_NN2 and_CC secondly_RR through_II an_AT1 interview_NN1 ._. 
</s>
<s>
This_DD1 will_VM allow_VVI for_IF general_JJ data_NN to_TO be_VBI collected_VVN during_II the_AT observation_NN1 and_CC then_RT complemented_VVN through_II a_AT1 more_RGR in-depth_JJ interview_NN1 ._. 
</s>
<s>
Observations_NN2 in_II a_AT1 research_NN1 require_VV0 a_AT1 more_RGR professional_JJ approach_NN1 than_CSN the_AT daily_JJ observations_NN2 we_PPIS2 make_VV0 ._. 
</s>
<s>
The_AT observations_NN2 in_II this_DD1 research_NN1 will_VM have_VHI to_TO extend_VVI beyond_II our_APPGE usual_JJ observations_NN2 ._. 
</s>
<s>
The_AT data_NN collected_VVN through_II the_AT observations_NN2 will_VM play_VVI a_AT1 large_JJ part_NN1 of_IO the_AT results_NN2 and_CC therefore_RR the_AT impact_NN1 will_VM be_VBI great_JJ on_II the_AT research_NN1 ._. 
</s>
<s>
(_( Silverman_NN1 ,_, 2006_MC )_) The_AT role_NN1 of_IO the_AT researcher_NN1 is_VBZ also_RR important_JJ ._. 
</s>
<s>
The_AT distinction_NN1 can_VM be_VBI made_VVN between_II perspectives-in-action_NN2 and_CC perspectives-of-action_NN2 (_( Eisenhardt_NP1 ,_, 1989_MC )_) ._. 
</s>
<s>
Perspectives-in-_NN2 action_NN1 means_VVZ that_CST the_AT researcher_NN1 takes_VVZ an_AT1 active_JJ role_NN1 and_CC actually_RR tries_VVZ to_TO observe_VVI everything_PN1 the_AT study_NN1 object_NN1 performs_VVZ during_II the_AT observation_NN1 ._. 
</s>
<s>
Perspectives-of-action_NN2 means_VVZ that_CST the_AT researcher_NN1 takes_VVZ no_AT active_JJ role_NN1 ,_, instead_RR he_PPHS1 or_CC she_PPHS1 relies_VVZ on_II the_AT information_NN1 provided_VVN by_II the_AT observed_JJ ._. 
</s>
<s>
(_( Belk_NP1 &;_NULL Kozinets_NP1 ,_, 2005_MC )_) This_DD1 study_NN1 will_VM be_VBI performed_VVN as_II a_AT1 perspectives-in-action_NN2 study_VV0 where_RRQ the_AT researcher_NN1 will_VM take_VVI an_AT1 active_JJ role_NN1 in_II observing_VVG the_AT behavior_NN1 patterns_NN2 of_IO the_AT person_NN1 being_VBG observed_VVN ._. 
</s>
<s>
This_DD1 agrees_VVZ with_IW Arnould_NP1 &;_NULL Wallendorf_NP1 (_( 1994_MC )_) where_RRQ the_AT perspectives-in-action_NN2 is_VBZ described_VVN as_II a_AT1 strategy_NN1 that_CST allows_VVZ more_RGR complete_JJ comprehensions_NN2 are_VBR possible_JJ to_TO be_VBI made_VVN (_( Arnould_NP1 &;_NULL Wallendorf_NP1 ,_, 1994_MC )_) ._. 
</s>
<s>
This_DD1 means_VVZ that_CST the_AT buying_NN1 behavior_NN1 in_II this_DD1 research_NN1 will_VM be_VBI observed_VVN during_II both_DB2 occasions_NN2 by_II the_AT researcher_NN1 ._. 
</s>
<s>
However_RR ,_, there_EX will_VM be_VBI no_AT interaction_NN1 with_IW the_AT person_NN1 observed_VVN during_II the_AT process_NN1 ._. 
</s>
<s>
The_AT second_MD data_NN collection_NN1 method_NN1 used_VVN in_II this_DD1 study_NN1 is_VBZ an_AT1 interview_NN1 ._. 
</s>
<s>
The_AT interview_NN1 will_VM be_VBI conducted_VVN based_VVN on_II an_AT1 interview_NN1 guide_VV0 that_CST will_VM be_VBI prepared_VVN in_II31 accordance_II32 with_II33 the_AT data_NN collected_VVN during_II the_AT observations_NN2 ._. 
</s>
<s>
The_AT reason_NN1 why_RRQ the_AT use_NN1 of_IO an_AT1 interview_NN1 is_VBZ justified_VVN is_VBZ because_CS observations_NN2 can_VM not_XX record_VVI emotions_NN2 ,_, values_NN2 or_CC expectations_NN2 (_( Arnould_NP1 &;_NULL Wallendorf_NP1 ,_, 1994_MC )_) ._. 
</s>
<s>
Therefore_RR the_AT aim_NN1 with_IW the_AT interview_NN1 is_VBZ to_TO gain_VVI additional_JJ knowledge_NN1 about_II these_DD2 factors_NN2 that_CST could_VM not_XX be_VBI gained_VVN from_II the_AT two_MC observation_NN1 occasions_NN2 ._. 
</s>
<s>
The_AT interview_NN1 method_NN1 used_VVN in_II this_DD1 study_NN1 is_VBZ a_AT1 semi-structured_JJ interview_NN1 that_CST has_VHZ certain_JJ predetermined_JJ elements_NN2 but_CCB is_VBZ also_RR open_JJ for_IF additional_JJ ,_, possibly_RR interesting_JJ themes_NN2 for_IF the_AT research_NN1 ._. 
</s>
<s>
(_( Patton_NN1 ,_, 2002_MC )_) The_AT reason_NN1 behind_II the_AT choice_NN1 of_IO a_AT1 semi-structured_JJ interview_NN1 is_VBZ that_CST it_PPH1 is_VBZ the_AT most_RGT appropriate_JJ fit_JJ for_IF the_AT purpose_NN1 of_IO the_AT study_NN1 ._. 
</s>
<s>
In_II this_DD1 case_NN1 an_AT1 unstructured_JJ interview_NN1 would_VM be_VBI too_RG liberal_JJ possibly_RR risking_VVG that_CST the_AT necessary_JJ information_NN1 will_VM not_XX be_VBI gathered_VVN ._. 
</s>
<s>
Since_CS this_DD1 interview_NN1 only_RR concerns_VVZ one_MC1 person_NN1 a_AT1 standardized_JJ interview_NN1 would_VM serve_VVI no_AT purpose_NN1 since_CS there_EX is_VBZ the_AT possibility_NN1 of_IO making_VVG a_AT1 customized_JJ ,_, targeted_VVN and_CC purposeful_JJ interview_NN1 ._. 
</s>
<s>
(_( Patton_NN1 ,_, 2002_MC )_) Methods_NN2 for_IF analysis_NN1 The_AT results_NN2 in_II this_DD1 study_NN1 will_VM be_VBI derived_VVN from_II data_NN analysis_NN1 ._. 
</s>
<s>
This_DD1 section_NN1 presents_VVZ the_AT methods_NN2 that_CST will_VM be_VBI used_VVN for_IF analyzing_VVG the_AT data_NN collected_VVN through_II the_AT already_RR discussed_VVN methods_NN2 ._. 
</s>
<s>
The_AT methods_NN2 used_VVN for_IF analysis_NN1 are_VBR presented_VVN in_II Spiggle_NP1 (_( 1994_MC )_) ._. 
</s>
<s>
Once_RR21 more_RR22 ,_, in_II31 accordance_II32 with_II33 term_NN1 triangulation_NN1 presented_VVN by_II Silverman_NP1 (_( 2006_MC )_) and_CC Wallendorf_NP1 &;_NULL Belk_NP1 (_( 1989_MC )_) ,_, more_DAR than_CSN one_MC1 method_NN1 will_VM be_VBI used_VVN in_BCL21 order_BCL22 to_TO increase_VVI the_AT overall_JJ quality_NN1 of_IO this_DD1 study_NN1 ._. 
</s>
<s>
Spiggle_NP1 (_( 1994_MC )_) presents_VVZ the_AT method_NN1 of_IO categorization_NN1 as_CSA one_MC1 of_IO the_AT most_RGT common_JJ and_CC efficient_JJ analysis_NN1 methods_NN2 ._. 
</s>
<s>
This_DD1 method_NN1 basically_RR requires_VVZ the_AT researcher_NN1 to_TO organize_VVI categories_NN2 into_II which_DDQ the_AT data_NN can_VM be_VBI associated_VVN ._. 
</s>
<s>
This_DD1 way_NN1 the_AT data_NN can_VM be_VBI well_RR distinguished_JJ and_CC purposefully_RR analyzed_VVD ._. 
</s>
<s>
(_( Spiggle_VV0 ,_, 1994_MC )_) The_AT theoretical_JJ framework_NN1 in_II this_DD1 study_NN1 serves_VVZ as_II an_AT1 excellent_JJ base_NN1 for_IF categorizing_VVG the_AT data_NN collected_VVD ._. 
</s>
<s>
Therefore_RR ,_, categorization_NN1 will_VM be_VBI used_VVN as_II the_AT fundamental_JJ method_NN1 of_IO analysis_NN1 in_II this_DD1 study_NN1 ._. 
</s>
<s>
Since_CS this_DD1 study_NN1 involves_VVZ observations_NN2 at_II two_MC different_JJ occasions_NN2 a_AT1 method_NN1 called_VVN comparison_NN1 can_VM be_VBI used_VVN ._. 
</s>
<s>
This_DD1 method_NN1 is_VBZ an_AT1 analytical_JJ approach_NN1 to_II a_AT1 situation_NN1 where_RRQ data_NN from_II two_MC or_CC more_DAR contexts_NN2 have_VH0 been_VBN gathered_VVN ._. 
</s>
<s>
Also_RR in_II this_DD1 method_NN1 ,_, it_PPH1 is_VBZ required_VVN to_TO first_MD categorize_VVI the_AT data_NN and_CC then_RT perform_VV0 a_AT1 deeper_JJR analysis_NN1 ._. 
</s>
<s>
(_( Spiggle_VV0 ,_, 1994_MC )_) This_DD1 method_NN1 is_VBZ suitable_JJ for_IF this_DD1 study_NN1 since_CS it_PPH1 aims_VVZ at_II discovering_VVG similarities_NN2 and_CC differences_NN2 in_II the_AT data_NN collected_VVD ._. 
</s>
<s>
This_DD1 aim_NN1 is_VBZ strongly_RR in_II31 accordance_II32 with_II33 the_AT purpose_NN1 of_IO this_DD1 study_NN1 ;_; to_TO discover_VVI consumer_NN1 behavior_NN1 patterns_NN2 in_II contexts_NN2 of_IO different_JJ product_NN1 ranges_NN2 ._. 
</s>
<s>
The_AT last_MD methods_NN2 for_IF analysis_NN1 will_VM ,_, unlike_JJ categorization_NN1 and_CC comparison_NN1 ,_, focus_VV0 on_II analyzing_VVG the_AT data_NN collected_VVN through_II the_AT conducted_VVN interview_NN1 ._. 
</s>
<s>
The_AT purpose_NN1 of_IO the_AT interview_NN1 is_VBZ to_TO gain_VVI a_AT1 deeper_JJR knowledge_NN1 of_IO the_AT patterns_NN2 discovered_VVD during_II the_AT observations_NN2 ._. 
</s>
<s>
(_( Patton_NN1 ,_, 2002_MC )_) The_AT method_NN1 that_CST will_VM be_VBI used_VVN to_TO analyze_VVI the_AT results_NN2 from_II the_AT interview_NN1 is_VBZ called_VVN dimensionalization_NN1 and_CC is_VBZ described_VVN by_II Spiggle_NP1 (_( 1994_MC )_) as_CSA relating_VVG concepts_NN2 to_II each_PPX221 other_PPX222 by_II using_VVG degrees_NN2 of_IO ,_, for_REX21 example_REX22 ,_, importance_NN1 (_( Spiggle_NP1 ,_, 1994_MC )_) ._. 
</s>
<s>
In_II this_DD1 study_NN1 the_AT importance_NN1 of_IO each_DD1 category_NN1 will_VM be_VBI assessed_VVN through_II dimensionalization_NN1 ._. 
</s>
<s>
This_DD1 way_NN1 it_PPH1 will_VM be_VBI possible_JJ to_TO relate_VVI certain_JJ patterns_NN2 to_II the_AT larger_JJR grocery_NN1 store_NN1 and_CC others_NN2 to_II the_AT smaller_JJR one_PN1 ._. 
</s>
<s>
In_II the_AT meantime_NNT1 ,_, the_AT differences_NN2 will_VM be_VBI promoted_VVN since_CS the_AT interview_NN1 will_VM provide_VVI a_AT1 justification_NN1 to_II why_RRQ a_AT1 certain_JJ pattern_NN1 is_VBZ present_JJ in_II one_MC1 store_NN1 and_CC not_XX in_II another_DD1 ._. 
</s>
<s>
Information_NN1 about_II the_AT informant_NN1 This_DD1 short_JJ section_NN1 presents_VVZ the_AT person_NN1 used_VVN as_II an_AT1 informant_NN1 in_II this_DD1 study_NN1 ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) Analysis_NN1 This_DD1 section_NN1 will_VM analyze_VVI the_AT data_NN collected_VVN through_II both_DB2 the_AT two_MC observations_NN2 and_CC the_AT interview_NN1 ._. 
</s>
<s>
First_MD the_AT data_NN from_II the_AT observations_NN2 will_VM be_VBI analyzed_VVN followed_VVN by_II an_AT1 analysis_NN1 of_IO the_AT data_NN from_II the_AT interview_NN1 ._. 
</s>
<s>
Finally_RR ,_, the_AT analysis_NN1 from_II both_DB2 methods_NN2 will_VM be_VBI united_VVN in_BCL21 order_BCL22 to_TO identify_VVI patterns_NN2 for_IF the_AT study_NN1 as_II a_AT1 whole_NN1 ._. 
</s>
<s>
Analysis_NN1 of_IO the_AT data_NN collected_VVN through_II observations_NN2 For_IF the_AT sake_NN1 of_IO simplicity_NN1 the_AT analysis_NN1 and_CC related_JJ results_NN2 are_VBR presented_VVN in_II the_AT following_JJ table_NN1 ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) Certain_JJ differences_NN2 and_CC similarities_NN2 can_VM be_VBI identified_VVN from_II the_AT analysis_NN1 presented_VVN in_II table_NN1 1_MC1 ._. 
</s>
<s>
The_AT most_RGT notable_JJ differences_NN2 are_VBR that_RG large_JJ packages_NN2 were_VBDR purchased_VVN from_II S-Market_NP1 ,_, which_DDQ is_VBZ not_XX only_RR located_VVN further_RRR away_RL but_CCB also_RR has_VHZ a_AT1 hill_NN1 in_RL21 between_RL22 ._. 
</s>
<s>
In_II the_AT meantime_NNT1 ,_, heavy_JJ packages_NN2 ,_, like_II milk_NN1 ,_, were_VBDR purchased_VVN from_II the_AT store_NN1 that_CST was_VBDZ located_VVN closer_RRR the_AT observed_JJ 's_GE residence_NN1 ._. 
</s>
<s>
This_DD1 distinction_NN1 can_VM be_VBI related_VVN to_II the_AT distance_NN1 between_II the_AT residence_NN1 and_CC each_DD1 store_NN1 ._. 
</s>
<s>
At_II this_DD1 point_NN1 of_IO the_AT research_NN1 a_AT1 new_JJ category_NN1 that_CST can_VM be_VBI related_VVN to_II personal_JJ factors_NN2 influencing_VVG consumer_NN1 behavior_NN1 ,_, discussed_VVN in_II the_AT theory_NN1 chapter_NN1 ,_, can_VM be_VBI proposed_VVN ._. 
</s>
<s>
This_DD1 category_NN1 can_VM be_VBI named_VVN physical_JJ constraints_NN2 that_CST seem_VV0 to_TO be_VBI relevant_JJ in_II this_DD1 case_NN1 ._. 
</s>
<s>
However_RR ,_, the_AT validity_NN1 of_IO this_DD1 category_NN1 has_VHZ to_TO be_VBI verified_VVN in_II the_AT interview_NN1 ._. 
</s>
<s>
Other_JJ interesting_JJ observations_NN2 were_VBDR that_CST the_AT visit_NN1 to_II the_AT larger_JJR store_NN1 seemed_VVD more_RRR planned_VVN than_CSN the_AT visit_NN1 to_II the_AT smaller_JJR one_PN1 ._. 
</s>
<s>
This_DD1 factor_NN1 can_VM be_VBI related_VVN to_II both_DB2 lifestyle_NN1 and_CC economical_JJ situation_NN1 of_IO the_AT observed_JJ ._. 
</s>
<s>
Planning_VVG a_AT1 visit_NN1 to_II one_MC1 store_NN1 signals_VVZ that_CST there_EX is_VBZ some_DD underlying_JJ purpose_NN1 behind_II the_AT visit_NN1 ._. 
</s>
<s>
This_DD1 can_VM be_VBI related_VVN to_II that_DD1 one_MC1 store_NN1 is_VBZ either_RR more_RGR inexpensive_JJ or_CC that_CST it_PPH1 is_VBZ some_DD sort_NN1 of_IO a_AT1 factor_NN1 related_VVN to_II the_AT lifestyle_NN1 ._. 
</s>
<s>
Certain_JJ products_NN2 that_CST fit_VV0 the_AT lifestyle_NN1 of_IO the_AT person_NN1 observed_VVN might_VM not_XX be_VBI available_JJ in_II smaller_JJR store_NN1 ._. 
</s>
<s>
Therefore_RR the_AT study_NN1 object_NN1 is_VBZ forced_VVN to_TO visit_VVI a_AT1 store_NN1 with_IW a_AT1 more_RGR complete_JJ product_NN1 range_NN1 in_BCL21 order_BCL22 to_TO follow_VVI her_APPGE lifestyle_NN1 ._. 
</s>
<s>
Again_RT ,_, this_DD1 assumption_NN1 needs_VVZ more_DAR verification_NN1 during_II the_AT interview_NN1 ._. 
</s>
<s>
Analysis_NN1 of_IO the_AT data_NN collected_VVN through_II the_AT interview_NN1 The_AT purpose_NN1 of_IO the_AT interview_NN1 is_VBZ to_TO gain_VVI a_AT1 deeper_JJR understanding_NN1 of_IO certain_JJ patterns_NN2 that_CST were_VBDR observed_VVN ._. 
</s>
<s>
The_AT data_NN will_VM be_VBI analyzed_VVN based_VVN on_II the_AT categorization_NN1 presented_VVN in_II the_AT theory-chapter_NN1 with_IW an_AT1 addition_NN1 of_IO the_AT physical_JJ constraint_NN1 category_NN1 presented_VVN in_II the_AT previous_JJ section_NN1 ._. 
</s>
<s>
The_AT following_JJ table_NN1 presents_VVZ the_AT findings_NN2 from_II the_AT interview_NN1 ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) The_AT analysis_NN1 of_IO the_AT data_NN from_II the_AT interview_NN1 supports_VVZ the_AT assumptions_NN2 raised_VVN in_II the_AT previous_JJ section_NN1 ._. 
</s>
<s>
First_MD ,_, the_AT visit_NN1 to_II the_AT store_NN1 with_IW a_AT1 larger_JJR product_NN1 range_NN1 was_VBDZ well_RR planned_VVN ._. 
</s>
<s>
The_AT visit_NN1 to_II this_DD1 specific_JJ store_NN1 only_RR occurs_VVZ once_RR a_AT1 week_NNT1 ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 ,_, the_AT respondent_NN1 frequently_RR visits_VVZ the_AT smaller_JJR store_NN1 ._. 
</s>
<s>
This_DD1 pattern_NN1 relates_VVZ to_II all_DB categories_NN2 presented_VVD ._. 
</s>
<s>
Due_II21 to_II22 the_AT person_NN1 's_GE busy_JJ lifestyle_NN1 she_PPHS1 has_VHZ a_AT1 limited_JJ amount_NN1 of_IO time_NNT1 to_TO do_VDI groceries_NN2 ._. 
</s>
<s>
Her_APPGE economic_JJ situation_NN1 promotes_VVZ economical_JJ solutions_NN2 for_IF her_APPGE grocery_NN1 purchases_NN2 but_CCB that_DD1 can_VM interfere_VVI with_IW the_AT time_NNT1 constraint_NN1 ._. 
</s>
<s>
As_CSA it_PPH1 appears_VVZ ,_, both_DB2 factors_NN2 are_VBR critical_JJ for_IF the_AT respondent_NN1 but_CCB the_AT time_NNT1 constraint_NN1 is_VBZ more_RGR difficult_JJ to_TO manage_VVI since_CS the_AT condition_NN1 depends_VVZ on_II a_AT1 number_NN1 of_IO external_JJ factors_NN2 like_II employers_NN2 ._. 
</s>
<s>
The_AT proposed_JJ category_NN1 "_" physical_JJ constraints_NN2 "_" ,_, proved_VVD to_TO be_VBI relevant_JJ in_II this_DD1 research_NN1 ._. 
</s>
<s>
Items_NN2 of_IO large_JJ size_NN1 could_VM be_VBI purchased_VVN from_II either_DD1 store_NN1 ;_; the_AT decisive_JJ factor_NN1 was_VBDZ the_AT price_NN1 ._. 
</s>
<s>
However_RR ,_, milk_NN1 for_REX21 example_REX22 ,_, was_VBDZ only_RR purchased_VVN from_II the_AT store_NN1 located_VVD closer_RRR to_II the_AT respondent_NN1 because_II21 of_II22 the_AT weight_NN1 ._. 
</s>
<s>
Conclusive_JJ results_NN2 This_DD1 research_NN1 has_VHZ generated_VVN a_AT1 number_NN1 of_IO interesting_JJ results_NN2 ._. 
</s>
<s>
The_AT purpose_NN1 of_IO the_AT study_NN1 was_VBDZ fulfilled_VVN since_CS certain_JJ patterns_NN2 were_VBDR discovered_VVN that_CST clearly_RR could_VM be_VBI related_VVN to_II the_AT size_NN1 of_IO the_AT product_NN1 range_NN1 ._. 
</s>
<s>
A_AT1 store_NN1 with_IW a_AT1 large_JJ product_NN1 range_NN1 can_VM offer_VVI products_NN2 in_II different_JJ packages_NN2 according_II21 to_II22 size_NN1 ._. 
</s>
<s>
This_DD1 study_NN1 shows_VVZ that_CST even_RR single_JJ people_NN purchase_VV0 large_JJ package_NN1 in_BCL21 order_BCL22 to_TO save_VVI money_NN1 and_CC time_NNT1 ._. 
</s>
<s>
A_AT1 possible_JJ assumption_NN1 from_II this_DD1 study_NN1 is_VBZ that_CST the_AT larger_JJR packages_NN2 can_VM rarely_RR be_VBI located_VVN in_II smaller_JJR stores_NN2 ._. 
</s>
<s>
Therefore_RR ,_, consumers_NN2 possibly_RR have_VH0 to_TO find_VVI these_DD2 economical_JJ items_NN2 in_II stores_NN2 that_CST might_VM be_VBI located_VVN further_RRR away_II21 from_II22 their_APPGE home_NN1 ._. 
</s>
<s>
Another_DD1 notable_JJ pattern_NN1 was_VBDZ that_DD1 certain_JJ values_NN2 could_VM be_VBI pushed_VVN aside_RL when_CS factors_NN2 like_II time_NNT1 constraints_NN2 and_CC limited_JJ budgets_NN2 appear_VV0 ._. 
</s>
<s>
A_AT1 person_NN1 might_VM save_VVI time_NNT1 through_II spending_VVG more_DAR money_NN1 on_II a_AT1 certain_JJ item_NN1 ._. 
</s>
<s>
This_DD1 study_NN1 shows_VVZ that_DD1 planning_NN1 of_IO buying_VVG behavior_NN1 can_VM have_VHI a_AT1 large_JJ impact_NN1 on_II the_AT overall_JJ consumer_NN1 behavior_NN1 ._. 
</s>
<s>
Quality_NN1 recognition_NN1 Quality_NN1 has_VHZ been_VBN promoted_VVN throughout_II this_DD1 study_NN1 through_II the_AT use_NN1 of_IO triangulation_NN1 ._. 
</s>
<s>
By_II using_VVG triangulation_NN1 ,_, small_JJ errors_NN2 and_CC misinterpretations_NN2 can_VM be_VBI avoided_VVN ._. 
</s>
<s>
This_DD1 can_VM be_VBI witnessed_VVN in_II the_AT diverse_JJ selection_NN1 of_IO methods_NN2 for_IF this_DD1 study_NN1 ._. 
</s>
<s>
The_AT usage_NN1 of_IO several_DA2 methods_NN2 opens_VVZ up_RP for_IF greater_JJR interpretation_NN1 possibilities_NN2 ._. 
</s>
<s>
(_( Wallendorf_NP1 &;_NULL Belk_NP1 ,_, 1989_MC ;_; Silverman_NP1 ,_, 2006_MC )_) 
</s>
