<s>
The_AT Eco-Friendliness_NP1 of_IO Luxury_JJ Brands_NN2 :_: the_AT viewpoint_NN1 of_IO consumers_NN2 1_MC1 Introduction_NN1 Recently_RR ,_, there_EX has_VHZ been_VBN a_AT1 wide_JJ interest_NN1 in_II luxury_JJ brands_NN2 ._. 
</s>
<s>
The_AT luxury_JJ industry_NN1 is_VBZ considered_VVN relatively_RR small_JJ in_II31 terms_II32 of_II33 companies_NN2 operating_VVG on_II the_AT market_NN1 ,_, but_CCB generates_VVZ a_AT1 vast_JJ sum_NN1 of_IO money_NN1 (_( Okonkwo_NP1 2007_MC :_: foreword_NN1 )_) ._. 
</s>
<s>
The_AT value_NN1 of_IO the_AT luxury_JJ market_NN1 was_VBDZ estimated_VVN in_II 2005_MC and_CC reached_VVN a_AT1 tremendous_JJ $840_NNU billion_NNO (_( Truong_NP1 ,_, Simmons_NP1 ,_, McColl_NP1 &;_NULL Kitchen_NN1 2008:189_MC )_) ._. 
</s>
<s>
Luxury_JJ branding_NN1 has_VHZ received_VVN considerable_JJ attention_NN1 ,_, since_CS the_AT classical_JJ rules_NN2 of_IO marketing_NN1 that_CST applies_VVZ to_II non-luxury_JJ brands_NN2 need_VV0 to_TO be_VBI turned_VVN upside_RL21 down_RL22 in_II order_NN1 to_TO work_VVI for_IF luxury_JJ brands_NN2 (_( Kapferer_NP1 &;_NULL Bastien_NP1 2009_MC )_) ._. 
</s>
<s>
This_DD1 implies_VVZ resisting_VVG clients_NN2 demands_NN2 ,_, making_VVG it_PPH1 difficult_JJ for_IF clients_NN2 to_TO buy_VVI and_CC raising_VVG your_APPGE prices_NN2 continuously_RR in_BCL21 order_BCL22 to_TO increase_VVI demand_NN1 (_( ibid_RR ._. )_) ._. 
</s>
<s>
Luxury_JJ brands_NN2 are_VBR considered_VVN the_AT most_RGT influential_JJ brands_NN2 ,_, since_CS they_PPHS2 set_VV0 the_AT trends_NN2 that_CST non-luxury_JJ brands_NN2 follow_VV0 and_CC imitate_VV0 (_( Okonkwo_NP1 2007_MC :_: foreword_NN1 )_) ._. 
</s>
<s>
Moreover_RR ,_, luxury_JJ brands_NN2 have_VH0 the_AT capacity_NN1 to_TO shape_VVI consumers_NN2 preferences_NN2 ._. 
</s>
<s>
Luxury_JJ brands_NN2 are_VBR believed_VVN to_TO be_VBI of_IO high_JJ quality_NN1 ,_, exclusive_JJ ,_, unique_JJ and_CC timeless_JJ (_( Kapferer_NP1 &;_NULL Bastien_NP1 2009_MC ;_; Okonkwo_NP1 2007_MC )_) ._. 
</s>
<s>
A_AT1 heritage_NN1 of_IO craftsmanship_NN1 and_CC country_NN1 of_IO origin_NN1 are_VBR other_JJ defining_JJ characteristics_NN2 of_IO a_AT1 luxury_JJ brand_NN1 (_( Jackson_NP1 &;_NULL Shaw_NP1 2009_MC ;_; Okonkwo_NP1 2007_MC )_) ._. 
</s>
<s>
Luxury_JJ consumers_NN2 are_VBR believed_VVN to_TO be_VBI smart_JJ and_CC intelligent_JJ ,_, powerful_JJ ,_, individualistic_JJ and_CC highly_RR demanding_VVG ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, a_AT1 luxury_JJ consumer_NN1 has_VHZ high_JJ expectations_NN2 as_II31 well_II32 as_II33 strong_JJ values_NN2 and_CC principles_NN2 ._. 
</s>
<s>
Luxury_JJ consumers_NN2 are_VBR more_RGR likely_JJ to_TO be_VBI associated_VVN with_IW those_DD2 luxury_JJ companies_NN2 that_CST share_VV0 their_APPGE moral_JJ value_NN1 ._. 
</s>
<s>
(_( Okonkwo_NN1 2007:243_MC )_) Although_CS luxury_JJ brands_NN2 have_VH0 been_VBN extensively_RR studied_VVN ,_, less_DAR attention_NN1 has_VHZ been_VBN given_VVN to_II the_AT green_JJ side_NN1 of_IO luxury_JJ brands_NN2 ._. 
</s>
<s>
According_II21 to_II22 Orange_NN1 (_( 2010:29_MC )_) ,_, the_AT interest_NN1 in_II being_VBG green_JJ and_CC purchasing_VVG eco-friendly_JJ products_NN2 continues_VVZ to_TO grow_VVI among_II consumers_NN2 ._. 
</s>
<s>
The_AT characteristics_NN2 that_CST distinguish_VV0 luxury_JJ brands_NN2 from_II mass-market_JJ brands_NN2 could_VM label_VVI luxury_JJ brands_NN2 as_CSA being_VBG more_RGR eco-friendly_JJ than_CSN non-luxury_JJ brands_NN2 ._. 
</s>
<s>
Luxury_JJ companies_NN2 are_VBR getting_VVG increasingly_RR involved_JJ in_II environmental_JJ issues_NN2 as_II31 well_II32 as_II33 ethical_JJ concerns_NN2 ._. 
</s>
<s>
The_AT Gucci_NP1 Group_NN1 has_VHZ said_VVN that_CST it_PPH1 will_VM sponsor_VVI a_AT1 new_JJ Ph.D_NP1 ._. 
</s>
<s>
scholarship_NN1 devoted_VVD to_II innovations_NN2 in_II sustainable_JJ fashion_NN1 and_CC textiles_NN2 in_II31 cooperation_II32 with_II33 two_MC London_NP1 universities_NN2 ,_, which_DDQ is_VBZ just_RR one_MC1 example_NN1 of_IO what_DDQ luxury_JJ brands_NN2 are_VBR doing_VDG for_IF the_AT environment_NN1 (_( Socha_NP1 2009:3_MC )_) ._. 
</s>
<s>
Despite_II the_AT efforts_NN2 of_IO luxury_JJ brands_NN2 to_TO save_VVI the_AT planet_NN1 ,_, a_AT1 recent_JJ report_NN1 by_II WWF_NP1 in_II the_AT UK_NP1 proves_VVZ that_CST none_PN of_IO the_AT top_JJ luxury_JJ brands_NN2 score_VV0 highly_RR on_II being_VBG environmentally_RR friendly_JJ ._. 
</s>
<s>
It_PPH1 is_VBZ of_IO interest_NN1 to_TO further_RRR investigate_VVI whether_CSW luxury_JJ brands_NN2 are_VBR eco-friendly_JJ or_CC not_XX ._. 
</s>
<s>
The_AT opinions_NN2 of_IO consumers_NN2 could_VM give_VVI insight_NN1 into_II this_DD1 topic_NN1 ,_, since_CS the_AT consumer_NN1 society_NN1 is_VBZ placing_VVG more_RRR and_CC more_DAR value_NN1 on_II ethical_JJ and_CC moral_JJ issues_NN2 including_II environmental_JJ protecting_JJ concerns_NN2 (_( Okonkwo_NP1 2007:243_MC )_) ._. 
</s>
<s>
1.2_MC The_AT aim_NN1 of_IO the_AT paper_NN1 The_AT purpose_NN1 of_IO this_DD1 paper_NN1 is_VBZ to_TO investigate_VVI whether_CSW consumers_NN2 perceive_VV0 luxury_JJ brands_NN2 as_CSA environmentally_RR friendly_JJ or_CC not_XX ._. 
</s>
<s>
This_DD1 will_VM be_VBI done_VDN by_II seeking_VVG answers_NN2 to_II the_AT following_JJ research_NN1 questions_NN2 :_: 1_MC1 ._. 
</s>
<s>
Can_VV0 the_AT consumption_NN1 of_IO luxury_JJ goods_NN2 be_VBI considered_VVN a_AT1 green_JJ act_NN1 ?_? 2_MC ._. 
</s>
<s>
Do_VD0 consumers_NN2 think_VVI that_DD1 luxury_JJ brands_NN2 are_VBR more_RGR environmentally_RR friendly_JJ than_CSN non-luxury_JJ brands_NN2 ?_? 
</s>
<s>
If_CS so_RR ,_, in_II which_DDQ ways_NN2 ?_? 
</s>
<s>
The_AT research_NN1 questions_NN2 will_VM be_VBI answered_VVN by_II interviewing_VVG consumers_NN2 on_II their_APPGE opinions_NN2 about_II the_AT eco-friendliness_NN1 of_IO luxury_JJ brands_NN2 ._. 
</s>
<s>
1.3_MC The_AT structure_NN1 of_IO the_AT paper_NN1 The_AT remainder_NN1 of_IO the_AT paper_NN1 is_VBZ divided_VVN into_II four_MC chapters_NN2 ._. 
</s>
<s>
Chapter_NN1 2_MC discusses_VVZ relevant_JJ literature_NN1 on_II the_AT subject_NN1 ._. 
</s>
<s>
Chapter_NN1 3_MC defines_VVZ the_AT methodology_NN1 used_VVN for_IF the_AT paper_NN1 ._. 
</s>
<s>
Chapter_NN1 4_MC presents_VVZ the_AT results_NN2 and_CC chapter_NN1 5_MC discusses_VVZ the_AT results_NN2 with_II31 reference_II32 to_II33 theory_NN1 ._. 
</s>
<s>
2_MC Luxury_JJ and_CC green_JJ marketing_NN1 In_II this_DD1 chapter_NN1 the_AT term_NN1 luxury_NN1 is_VBZ explained_VVN ._. 
</s>
<s>
The_AT green_JJ movement_NN1 and_CC how_RRQ it_PPH1 is_VBZ affecting_VVG companies_NN2 and_CC brands_NN2 is_VBZ also_RR discussed_VVN ._. 
</s>
<s>
The_AT chapter_NN1 gives_VVZ an_AT1 outline_NN1 of_IO the_AT consumers_NN2 of_IO luxury_JJ products_NN2 ,_, as_II31 well_II32 as_II33 green_JJ products_NN2 ._. 
</s>
<s>
A_AT1 figure_NN1 concludes_VVZ the_AT characteristics_NN2 of_IO the_AT two_MC types_NN2 of_IO consumers_NN2 ._. 
</s>
<s>
2.1_MC What_DDQ is_VBZ luxury_JJ ?_? 
</s>
<s>
Phau_NP1 &;_NULL Prendergast_NP1 (_( 2000:123_MC )_) claim_VV0 that_CST it_PPH1 is_VBZ difficult_JJ to_TO define_VVI luxury_JJ since_CS it_PPH1 is_VBZ so_RG subjective_JJ and_CC personal_JJ ._. 
</s>
<s>
What_DDQ one_MC1 person_NN1 regards_VVZ as_CSA luxury_NN1 does_VDZ not_XX have_VHI to_TO be_VBI luxurious_JJ to_II another_DD1 :_: one_PN1 may_VM find_VVI champagne_NN1 and_CC caviar_VVI luxurious_JJ ,_, while_CS another_DD1 thinks_VVZ that_CST sleeping_VVG in_RP is_VBZ the_AT height_NN1 of_IO luxury_NN1 ._. 
</s>
<s>
Okonkwo_NP1 (_( 2007:11_MC )_) lists_VVZ some_DD components_NN2 that_CST characterize_VV0 a_AT1 luxury_JJ brand_NN1 ._. 
</s>
<s>
These_DD2 include_VV0 brand_NN1 strength_NN1 ,_, differentiation_NN1 ,_, exclusivity_NN1 ,_, innovation_NN1 ,_, craftsmanship_NN1 and_CC precision_NN1 ,_, premium_JJ pricing_NN1 as_II31 well_II32 as_II33 high_JJ quality_NN1 ._. 
</s>
<s>
Creativity_NN1 ,_, a_AT1 distinct_JJ brand_NN1 identity_NN1 ,_, a_AT1 global_JJ reputation_NN1 and_CC high_JJ visibility_NN1 are_VBR also_RR included_VVN in_II the_AT definition_NN1 of_IO a_AT1 luxury_JJ brand_NN1 (_( Okonkwo_NP1 2007:105_MC )_) ._. 
</s>
<s>
Jackson_NP1 &;_NULL Shaw_NP1 (_( 2009:122123,270_MC )_) add_VV0 country_NN1 of_IO origin_NN1 and_CC product_NN1 integrity_NN1 to_II the_AT defining_JJ characteristics_NN2 ._. 
</s>
<s>
Furthermore_RR ,_, Fionda_NP1 &;_NULL Moore_NP1 (_( 2009:359_MC )_) include_VV0 marketing_NN1 communication_NN1 ,_, design_NN1 signature_NN1 ,_, culture_NN1 and_CC environment_NN1 along_II21 with_II22 service_NN1 ._. 
</s>
<s>
The_AT higher_JJR prices_NN2 of_IO luxury_JJ goods_NN2 depend_VV0 on_II the_AT higher_JJR quality_NN1 of_IO the_AT products_NN2 ,_, fancy_JJ packaging_NN1 ,_, exclusive_JJ store_NN1 locations_NN2 ,_, higher_JJR retail_JJ margins_NN2 ,_, expensive_JJ promotions_NN2 ,_, advertising_NN1 campaigns_NN2 as_II31 well_II32 as_II33 brand_NN1 names_NN2 ._. 
</s>
<s>
(_( Husic_JJ &;_NULL Cicic_NN1 2009:235_MC )_) 2.2_MC Green_JJ marketing_NN1 The_AT green_JJ movement_NN1 is_VBZ increasingly_RR gaining_VVG supporters_NN2 ,_, and_CC the_AT eco-friendly_JJ initiatives_NN2 of_IO companies_NN2 are_VBR becoming_VVG more_RRR and_CC more_RGR important_JJ to_II consumers_NN2 ._. 
</s>
<s>
The_AT green_JJ movement_NN1 has_VHZ transformed_VVN in_II the_AT last_MD decades_NNT2 ._. 
</s>
<s>
In_II the_AT 70s_MC2 it_PPH1 was_VBDZ primarily_RR considered_VVN an_AT1 activist_NN1 movement_NN1 but_CCB has_VHZ now_RT become_VV0 a_AT1 notable_JJ part_NN1 of_IO many_DA2 nations_NN2 economies_NN2 ._. 
</s>
<s>
(_( Washington_NP1 &;_NULL Miller_NP1 2010:82_MC )_) Adopting_VVG an_AT1 environmentally_RR friendly_JJ way_NN1 of_IO thinking_NN1 can_VM include_VVI recycling_NN1 ,_, conserving_VVG energy_NN1 ,_, reducing_VVG product_NN1 consumption_NN1 and_CC buying_VVG eco-friendly_JJ products_NN2 among_II other_JJ things_NN2 ._. 
</s>
<s>
Abelitotis_NN1 ,_, Koniari_NP1 &;_NULL Sardianou_NP1 (_( 2010:153-154_MCMC )_) refer_VV0 to_II the_AT 3R-concept_NN1 ,_, which_DDQ involves_VVZ reducing_VVG ,_, reusing_VVG and_CC recycling_NN1 ._. 
</s>
<s>
Reducing_VVG means_VVZ any_DD effort_NN1 at_II consumption_NN1 points_VVZ to_TO reduce_VVI the_AT amount_NN1 of_IO waste_NN1 generated_VVD directly_RR or_CC indirectly_RR ._. 
</s>
<s>
Reusing_NP1 is_VBZ described_VVN as_II the_AT use_NN1 of_IO material_NN1 things_NN2 repeatedly_RR ,_, which_DDQ extends_VVZ their_APPGE lifespan_NN1 ._. 
</s>
<s>
Recycling_NN1 indicates_VVZ the_AT conversion_NN1 of_IO post_NN1 consumption_NN1 waste_NN1 to_II either_RR material_JJ resources_NN2 or_CC energy_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ emphasized_VVN that_CST the_AT primary_JJ focus_NN1 should_VM always_RR be_VBI placed_VVN firstly_RR on_II reducing_VVG ,_, then_RT reusing_VVG and_CC then_RT recycling_VVG (_( ibid_RR ._. )_) ._. 
</s>
<s>
Grant_NP1 (_( 2010:25_MC )_) defines_VVZ a_AT1 green_JJ brand_NN1 as_CSA one_PN1 that_CST offers_VVZ a_AT1 significant_JJ eco-advantage_NN1 over_II the_AT incumbents_NN2 and_CC which_DDQ hence_RR appeals_VVZ to_II those_DD2 who_PNQS are_VBR willing_JJ to_II making_VVG green_JJ a_AT1 high_JJ priority_NN1 ._. 
</s>
<s>
According_II21 to_II22 Hartmann_NP1 ,_, Ibes_VVZ &;_NULL Sainz_NP1 ,_, (_( 2005:10_MC )_) ,_, a_AT1 green_JJ brand_NN1 identity_NN1 is_VBZ defined_VVN by_II a_AT1 specific_JJ set_NN1 of_IO brand_NN1 attributes_NN2 and_CC benefits_NN2 related_VVN to_II the_AT reduced_JJ environmental_JJ impact_NN1 of_IO the_AT brand_NN1 and_CC its_APPGE perception_NN1 as_CSA being_VBG environmentally_RR sound_JJ ._. 
</s>
<s>
Hartmann_VV0 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2005:10_MC )_) adds_VVZ that_CST a_AT1 well-implemented_JJ green_JJ brand_NN1 identity_NN1 should_VM provide_VVI benefits_NN2 to_II the_AT consumers_NN2 that_CST are_VBR environmentally_RR conscious_JJ ._. 
</s>
<s>
Promoting_VVG the_AT green_JJ initiatives_NN2 of_IO companies_NN2 is_VBZ not_XX just_RR to_TO inform_VVI consumers_NN2 about_II green_JJ products_NN2 and_CC services_NN2 ,_, but_CCB also_RR about_II their_APPGE operations_NN2 ._. 
</s>
<s>
This_DD1 includes_VVZ the_AT hiring_NN1 practices_NN2 ,_, the_AT production_NN1 ,_, energy_NN1 usage_NN1 and_CC more_RRR ._. 
</s>
<s>
(_( Washington_NP1 &;_NULL Miller_NP1 2010:83_MC )_) Some_DD companies_NN2 do_VD0 not_XX promote_VVI their_APPGE green_JJ initiatives_NN2 in_II the_AT fear_NN1 of_IO repelling_VVG skeptical_JJ consumers_NN2 ._. 
</s>
<s>
Paradoxically_RR ,_, this_DD1 equals_VVZ missed_JJ opportunities_NN2 in_II attracting_VVG green_JJ consumers_NN2 (_( Washington_NP1 &;_NULL Miller_NP1 2010:84_MC )_) ._. 
</s>
<s>
The_AT findings_NN2 of_IO a_AT1 study_NN1 conducted_VVN by_II Hartmann_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2005_MC )_) show_VV0 that_CST a_AT1 well-implemented_JJ green_JJ positioning_NN1 strategy_NN1 may_VM create_VVI a_AT1 more_RGR favorable_JJ perception_NN1 of_IO a_AT1 brand_NN1 ,_, which_DDQ give_VV0 support_NN1 to_II the_AT green_JJ marketing_NN1 approach_NN1 in_RR21 general_RR22 ._. 
</s>
<s>
Banyte_NN1 ,_, Brazioniene_NP1 &;_NULL Gadeikiene_NP1 (_( 2010:374_MC )_) are_VBR of_IO the_AT opinion_NN1 that_CST green_JJ marketing_NN1 may_VM become_VVI an_AT1 effective_JJ tool_NN1 for_IF acquiring_VVG company_NN1 competitive_JJ advantage_NN1 and_CC for_IF strengthening_VVG the_AT image_NN1 ._. 
</s>
<s>
According_II21 to_II22 Chamorro_NP1 &;_NULL Baegil_NP1 (_( 2006:12_MC )_) ,_, green_JJ marketing_NN1 should_VM not_XX just_RR be_VBI limited_VVN to_II communication_NN1 policies_NN2 :_: ecological_JJ aspects_NN2 must_VM be_VBI incorporated_VVN into_II all_DB the_AT functional_JJ areas_NN2 of_IO marketing_NN1 ._. 
</s>
<s>
They_PPHS2 add_VV0 that_CST green_JJ marketing_NN1 is_VBZ not_XX just_RR procedures_NN2 and_CC activities_NN2 of_IO designing_VVG and_CC commercializing_VVG green_JJ products_NN2 ,_, but_CCB it_PPH1 is_VBZ a_AT1 philosophy_NN1 that_CST guides_NN2 the_AT behavior_NN1 of_IO the_AT entire_JJ organization_NN1 (_( ibid._RR )_) ._. 2.3_MC The_AT eco-friendliness_NN1 of_IO luxury_JJ brands_NN2 Over_II the_AT past_JJ few_DA2 years_NNT2 ,_, many_DA2 of_IO the_AT world_NN1 's_GE best-known_JJ luxury_JJ labels_NN2 have_VH0 started_VVN to_TO introduce_VVI eco-friendly_JJ products_NN2 and_CC include_VVI environmental_JJ themes_NN2 in_II their_APPGE advertising_NN1 and_CC marketing_NN1 ._. 
</s>
<s>
French_JJ luxury_JJ conglomerate_NN1 LVMH_NP1 administered_VVD a_AT1 carbon_NN1 inventory_NN1 to_TO assess_VVI its_APPGE impact_NN1 on_II greenhouse_NN1 gas_NN1 emissions_NN2 ,_, which_DDQ led_VVD to_II a_AT1 reduction_NN1 of_IO corporate_JJ travel_NN1 and_CC air_NN1 shipment_NN1 of_IO goods_NN2 ._. 
</s>
<s>
It_PPH1 has_VHZ also_RR taken_VVN a_AT1 stake_NN1 to_II Edun_NP1 ,_, an_AT1 organic_JJ clothing_NN1 company_NN1 founded_VVN by_II the_AT singer_NN1 Bono_NP1 and_CC his_APPGE wife_NN1 ._. 
</s>
<s>
Louis_NP1 Vuitton_NP1 also_RR launched_VVN a_AT1 "_" Core_NN1 Values_NN2 "_" advertising_NN1 campaign_NN1 that_CST has_VHZ featured_VVN many_DA2 celebrities_NN2 ._. 
</s>
<s>
The_AT celebrities_NN2 have_VH0 donated_VVN part_NN1 of_IO their_APPGE modeling_NN1 rewards_NN2 for_IF the_AT Climate_NN1 Project_NN1 :_: a_AT1 nonprofit_JJ group_NN1 founded_VVN by_II Al_NP1 Gore_NP1 and_CC supported_VVN by_II Louis_NP1 Vuitton_NP1 ._. 
</s>
<s>
(_( Dodes_NP1 &;_NULL Schechner_NP1 2009:8_MC )_) At_II LVMHs_NP2 rival_VV0 PPR_NP1 ,_, a_AT1 social_JJ and_CC environmental_JJ responsibility_NN1 department_NN1 has_VHZ been_VBN created_VVN ._. 
</s>
<s>
A_AT1 part_NN1 of_IO the_AT executives_NN2 bonuses_NN2 provides_VVZ capital_NN1 for_IF reaching_VVG targets_NN2 in_II seven_MC different_JJ areas_NN2 -_- from_II reducing_VVG carbon_NN1 emissions_NN2 to_II promoting_VVG diversity_NN1 ._. 
</s>
<s>
The_AT conglomerate_NN1 has_VHZ also_RR sponsored_VVN a_AT1 feature-length_JJ documentary_NN1 film_NN1 that_CST concerns_VVZ environmental_JJ abuse_NN1 ._. 
</s>
<s>
(_( Dodes_NP1 &;_NULL Schechner_NP1 2009:8_MC )_) Despite_II the_AT efforts_NN2 of_IO the_AT luxury_JJ conglomerates_NN2 ,_, they_PPHS2 score_VV0 low_JJ on_II being_VBG eco-friendly_JJ in_II the_AT WWF_NP1 report_NN1 Deeper_JJR Luxury_NN1 from_II 2007_MC ._. 
</s>
<s>
LVMH_NP1 is_VBZ among_II the_AT top_JJ scoring_NN1 companies_NN2 and_CC received_VVD no_AT more_DAR than_CSN C+_FO ._. 
</s>
<s>
PPR_NP1 received_VVD a_AT1 D_ZZ1 for_IF their_APPGE efforts_NN2 ._. 
</s>
<s>
Bendell_NP1 &;_NULL Kleanthous_NP1 (_( 2003:2-3_MCMC )_) justify_VV0 the_AT importance_NN1 for_IF luxury_JJ brands_NN2 to_TO be_VBI eco-friendly_JJ :_: Luxury_JJ brands_NN2 have_VH0 the_AT power_NN1 to_TO influence_VVI consumer_NN1 aspiration_NN1 and_CC behavior_NN1 by_II editing_VVG consumer_NN1 choices_NN2 through_II product_NN1 design_NN1 ,_, distribution_NN1 and_CC marketing_NN1 and_CC by_II influencing_VVG how_RRQ ,_, when_RRQ and_CC for_IF how_RGQ long_JJ consumers_NN2 use_VV0 their_APPGE products_NN2 ._. 
</s>
<s>
They_PPHS2 have_VH0 both_RR the_AT opportunity_NN1 and_CC the_AT responsibility_NN1 to_TO promote_VVI sustainable_JJ consumption_NN1 ._. 
</s>
<s>
Dodes_NP1 &;_NULL Schechner_NP1 (_( 2009:8_MC )_) cite_VV0 Anthony_NP1 Kleanthous_NP1 ,_, senior_JJ policy_NN1 adviser_NN1 for_IF the_AT WWF_NP1 and_CC co-author_NN1 of_IO the_AT report_NN1 on_II the_AT reactions_NN2 regarding_II the_AT report_NN1 ._. 
</s>
<s>
According_II21 to_II22 Kleanthous_NP1 ,_, the_AT companies_NN2 were_VBDR quite_RG defensive_JJ initially_RR ,_, but_CCB they_PPHS2 are_VBR now_RT pushing_VVG environmental_JJ and_CC social_JJ responsibility_NN1 as_II a_AT1 positive_JJ driver_NN1 of_IO brand_NN1 value_NN1 ._. 
</s>
<s>
According_II21 to_II22 Okonkwo_NP1 (_( 2007:64_MC )_) ,_, luxury_JJ goods_NN2 traditionally_RR last_VV0 a_AT1 lifetime_NNT1 and_CC are_VBR rarely_RR disposed_VVN of_IO ._. 
</s>
<s>
In_II an_AT1 article_NN1 by_II Ilett_NP1 (_( 2010_MC )_) it_PPH1 is_VBZ proposed_VVN that_CST many_DA2 of_IO the_AT elements_NN2 that_CST define_VV0 luxury_NN1 can_VM support_VVI a_AT1 more_RGR sustainable_JJ approach_NN1 to_II consumption_NN1 ._. 
</s>
<s>
The_AT tailoring_NN1 and_CC craftsmanship_NN1 that_CST characterize_VV0 luxury_JJ brands_NN2 equal_VV0 an_AT1 appraisal_NN1 of_IO the_AT valuable_JJ materials_NN2 and_CC the_AT skillfulness_NN1 in_II both_RR design_VV0 and_CC creation_NN1 ,_, which_DDQ kindles_VVZ the_AT desire_NN1 to_TO use_VVI luxury_JJ products_NN2 time_VV0 after_II time_NNT1 ._. 
</s>
<s>
Luxury_NN1 needs_VVZ to_TO be_VBI perceived_VVN as_CSA more_DAR than_CSN just_RR high-priced_JJ and_CC premium_NN1 ._. 
</s>
<s>
Luxury_JJ brands_NN2 can_VM be_VBI considered_VVN role_NN1 models_NN2 for_IF a_AT1 more_RGR sustainable_JJ consumption_NN1 by_II emphasizing_VVG the_AT features_NN2 and_CC values_NN2 that_CST give_VV0 luxury_JJ products_NN2 a_AT1 longer_JJR lifetime_NNT1 than_CSN the_AT non-luxury_JJ alternatives_NN2 ._. 
</s>
<s>
(_( ibid_RR )_) By_II aiming_VVG to_TO reduce_VVI the_AT amount_NN1 of_IO waste_NN1 ,_, legislators_NN2 across_II the_AT world_NN1 are_VBR beginning_VVG to_TO implement_VVI laws_NN2 on_II packaging_NN1 (_( Hildebrandt_NP1 2009:18_MC )_) ._. 
</s>
<s>
This_DD1 has_VHZ been_VBN one_MC1 of_IO the_AT main_JJ worries_NN2 in_II the_AT luxury_JJ industry_NN1 since_CS the_AT packaging_NN1 adds_VVZ to_II the_AT brand_NN1 experience_NN1 and_CC consumers_NN2 have_VH0 come_VVN to_TO expect_VVI a_RR21 little_RR22 extra_JJ when_CS buying_VVG luxury_JJ goods_NN2 (_( ibid_RR ._. )_) ._. 
</s>
<s>
Hildebrandt_NP1 (_( 2009:20-22_MCMC )_) substantiates_VVZ that_DD1 sustainability_NN1 is_VBZ becoming_VVG just_RR another_DD1 variable_NN1 for_IF designers_NN2 to_TO work_VVI with_IW and_CC that_CST there_EX are_VBR many_DA2 alternatives_NN2 to_II making_VVG packaging_NN1 eco-friendlier_JJR :_: make_VV0 it_PPH1 refillable_JJ ,_, keep_VV0 it_PPH1 light_JJ ,_, use_VV0 recycled_JJ materials_NN2 or_CC materials_NN2 that_CST can_VM be_VBI recycled_VVN and_CC make_VV0 it_PPH1 biodegradable_JJ ._. 
</s>
<s>
2.4_MC Luxury_JJ consumers_NN2 versus_II green_JJ consumers_NN2 Abeliotis_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2010:153_MC )_) discuss_VV0 the_AT paradox_NN1 of_IO consumption_NN1 in_II their_APPGE article_NN1 ._. 
</s>
<s>
They_PPHS2 conclude_VV0 that_DD1 consumption_NN1 burdens_NN2 the_AT environment_NN1 in_II two_MC different_JJ ways_NN2 :_: first_MD by_II depleting_VVG non-renewable_JJ natural_JJ resources_NN2 ,_, and_CC secondly_RR by_II polluting_VVG the_AT environment_NN1 ._. 
</s>
<s>
Nevertheless_RR ,_, consumption_NN1 is_VBZ vital_JJ for_IF economic_JJ growth_NN1 ._. 
</s>
<s>
(_( ibid_RR )_) Next_MD ,_, two_MC types_NN2 of_IO consumers_NN2 are_VBR discussed_VVN ._. 
</s>
<s>
2.4.1_MC Luxury_JJ consumers_NN2 According_II21 to_II22 Okonkwo_NP1 (_( 2007:60_MC )_) there_EX are_VBR two_MC types_NN2 of_IO luxury_JJ consumers_NN2 :_: the_AT traditional_JJ luxury_JJ consumers_NN2 ,_, who_PNQS seek_VV0 well-established_JJ brands_NN2 ,_, and_CC the_AT new_JJ luxury_JJ consumers_NN2 ,_, who_PNQS are_VBR no_RR21 longer_RR22 attracted_VVN by_II brand_NN1 names_NN2 only_RR ,_, but_CCB who_PNQS cherish_VV0 a_AT1 complete_JJ package_NN1 of_IO products_NN2 and_CC services_NN2 ._. 
</s>
<s>
They_PPHS2 pursue_VV0 the_AT experience_NN1 connected_VVN to_II luxury_JJ products_NN2 (_( ibid_RR ._. )_) ._. 
</s>
<s>
The_AT luxury_JJ consumer_NN1 is_VBZ constantly_RR changing_VVG ,_, but_CCB there_EX are_VBR a_AT1 few_DA2 characteristics_NN2 that_CST define_VV0 them_PPHO2 ._. 
</s>
<s>
They_PPHS2 are_VBR smart_JJ and_CC intelligent_JJ ,_, powerful_JJ ,_, sophisticated_JJ and_CC brand_NN1 literate_NN1 ,_, individualistic_JJ ,_, highly_RR demanding_VVG ,_, have_VH0 high_JJ expectations_NN2 and_CC strong_JJ values_NN2 and_CC principles_NN2 ._. 
</s>
<s>
Four_MC out_II21 of_II22 five_MC luxury_JJ consumers_NN2 are_VBR women_NN2 ._. 
</s>
<s>
The_AT reason_NN1 for_IF why_RRQ women_NN2 have_VH0 become_VVN the_AT major_JJ consumers_NN2 of_IO luxury_JJ goods_NN2 is_VBZ that_CST they_PPHS2 possess_VV0 more_DAR money_NN1 due_II21 to_II22 increased_JJ education_NN1 and_CC career_NN1 orientation_NN1 ._. 
</s>
<s>
Women_NN2 of_IO today_RT marry_VV0 later_RRR and_CC have_VH0 fewer_DAR children_NN2 ,_, which_DDQ has_VHZ led_VVN to_II an_AT1 increase_NN1 in_II their_APPGE disposable_JJ income_NN1 ._. 
</s>
<s>
They_PPHS2 are_VBR also_RR influential_JJ in_II the_AT luxury_JJ purchase_NN1 decisions_NN2 of_IO men_NN2 ._. 
</s>
<s>
(_( Okonkwo_NP1 2007:65-69_MCMC )_) When_CS talking_VVG about_II the_AT future_NN1 of_IO luxury_JJ brands_NN2 and_CC luxury_JJ consumers_NN2 ,_, Okonkwo_NP1 (_( 2007:243_MC )_) asserts_VVZ that_CST environmental_JJ awareness_NN1 will_VM drive_VVI consumers_NN2 to_TO seek_VVI information_NN1 on_II the_AT materials_NN2 used_VVN for_IF their_APPGE products_NN2 and_CC to_TO support_VVI companies_NN2 with_IW visible_JJ ethical_JJ practices_NN2 ._. 
</s>
<s>
The_AT temporary_JJ ownership_NN1 culture_NN1 will_VM become_VVI increasingly_RR important_JJ and_CC second-hand_JJ luxury_JJ goods_NN2 will_VM become_VVI more_RGR fashionable_JJ and_CC more_RGR frequently_RR purchased_VVN ._. 
</s>
<s>
Luxury_JJ consumers_NN2 do_VD0 not_XX want_VVI to_TO dispose_VVI of_IO products_NN2 that_CST cost_VV0 up_RG21 to_RG22 600_MC %_NNU more_DAR than_CSN similar_JJ products_NN2 in_II other_JJ categories_NN2 reselling_VVG or_CC exchanging_VVG them_PPHO2 is_VBZ the_AT alternative_NN1 ._. 
</s>
<s>
(_( Okonkwo_NN1 2007:76,244_MC )_) In_II a_AT1 study_NN1 administered_VVN by_II Han_NP1 ,_, Nunes_NP2 &;_NULL Drze_VV0 in_II 2010_MC ,_, the_AT findings_NN2 show_VV0 that_CST those_DD2 with_IW a_AT1 higher_JJR income_NN1 are_VBR the_AT consumers_NN2 of_IO luxury_JJ goods_NN2 ._. 
</s>
<s>
Those_DD2 with_IW a_AT1 lower_JJR income_NN1 ,_, but_CCB who_PNQS still_RR seek_VV0 status_NN1 tend_VV0 to_TO buy_VVI counterfeits_NN2 ._. 
</s>
<s>
Premium_JJ pricing_NN1 ,_, one_MC1 of_IO the_AT characteristics_NN2 of_IO luxury_JJ brands_NN2 ,_, would_VM equal_VVI a_AT1 higher_JJR income_NN1 amongst_II the_AT consumers_NN2 who_PNQS buy_VV0 luxury_JJ goods_NN2 ,_, but_CCB income_NN1 does_VDZ not_XX necessarily_RR have_VHI to_TO be_VBI a_AT1 defining_JJ variable_NN1 for_IF the_AT consumers_NN2 of_IO luxury_JJ goods_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ possible_JJ to_TO buy_VVI fairly_RR new_JJ luxury_JJ bags_NN2 e.g._REX ,_, at_II second_MD hand_NN1 stores_NN2 and_CC flee_VV0 markets_NN2 ._. 
</s>
<s>
A_AT1 counterfeit_JJ product_NN1 is_VBZ not_XX the_AT only_JJ alternative_NN1 to_II luxury_JJ goods_NN2 when_RRQ the_AT income_NN1 is_VBZ lower_JJR ._. 
</s>
<s>
Husic_JJ &;_NULL Cisic_NN1 (_( 2009:231_MC )_) refer_VV0 to_II luxury_JJ goods_NN2 as_CSA status_NN1 goods_NN2 ._. 
</s>
<s>
Their_APPGE results_NN2 show_VV0 that_DD1 patron_NN1 status_NN1 is_VBZ on_RP of_IO the_AT factors_NN2 that_CST influence_VV0 luxury_JJ consumption_NN1 ._. 
</s>
<s>
Individuals_NN2 can_VM communicate_VVI meaning_VVG about_II themselves_PPX2 to_II their_APPGE reference_NN1 groups_NN2 by_II using_VVG status_NN1 goods_NN2 as_CSA symbols_NN2 and_CC many_DA2 luxury_JJ consumers_NN2 buy_VV0 luxury_JJ goods_NN2 primarily_RR to_TO satisfy_VVI their_APPGE appetite_NN1 for_IF symbols_NN2 (_( Husic_JJ &;_NULL Cicic_NN1 2009:234_MC )_) ._. 
</s>
<s>
2.4.2_MC Green_JJ consumers_NN2 Green_JJ consumers_NN2 are_VBR active_JJ in_II promoting_VVG the_AT benefits_NN2 of_IO environmental_JJ conservation_NN1 and_CC they_PPHS2 tend_VV0 to_TO ignore_VVI the_AT producers_NN2 of_IO goods_NN2 which_DDQ are_VBR not_XX eco-friendly_JJ (_( Banyte_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2010:375_MC )_) ._. 
</s>
<s>
Consumers_NN2 have_VH0 started_VVN to_TO perceive_VVI care_NN1 for_IF the_AT environment_NN1 as_CSA care_NN1 for_IF themselves_PPX2 (_( ibid_RR ._. )_) ._. 
</s>
<s>
The_AT results_NN2 of_IO a_AT1 study_NN1 conducted_VVN by_II Banyte_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
in_II 2010_MC reveal_VV0 that_CST more_DAR educated_JJ consumers_NN2 are_VBR more_RGR sensitive_JJ to_II environmental_JJ issues_NN2 ._. 
</s>
<s>
Moreover_RR ,_, the_AT female_JJ consumers_NN2 who_PNQS want_VV0 to_TO contribute_VVI to_II environmental_JJ conservation_NN1 and_CC who_PNQS are_VBR sensitive_JJ to_II ecological_JJ problems_NN2 tend_VV0 to_TO pay_VVI more_RRR for_IF eco-friendly_JJ products_NN2 (_( Banyte_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2010:382_MC )_) ._. 
</s>
<s>
According_II21 to_II22 Banyte_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 210:376_MC )_) ,_, well-educated_JJ women_NN2 ,_, who_PNQS belong_VV0 to_II the_AT age_NN1 group_NN1 of_IO 30_MC to_II 44_MC ,_, and_CC whose_DDQGE annual_JJ household_NN1 income_NN1 is_VBZ higher_JJR than_CSN average_NN1 may_VM be_VBI considered_VVN consumers_NN2 who_PNQS will_VM possibly_RR be_VBI involved_JJ in_II eco-friendly_JJ product_NN1 purchase_NN1 behavior_NN1 ._. 
</s>
<s>
The_AT results_NN2 from_II a_AT1 survey_NN1 by_II Unity_NN1 Marketing_NN1 show_VV0 that_CST the_AT typical_JJ green_JJ consumer_NN1 is_VBZ no_RR21 longer_RR22 the_AT fashion-challenged_NN1 ,_, granola-crunching_JJ wearer_NN1 of_IO Birkenstocks_NP1 (_( Stevens_NP1 2008_MC )_) ._. 
</s>
<s>
The_AT green_JJ consumer_NN1 of_IO today_RT is_VBZ increasingly_RR likely_JJ to_TO be_VBI an_AT1 affluent_JJ professional_JJ woman_NN1 wearing_VVG an_AT1 eco-friendly_JJ and_CC animal-free_JJ Stella_NP1 McCartney_NP1 suit_NN1 and_CC satin_NN1 shoes_NN2 (_( ibid_RR ._. )_) ._. 
</s>
<s>
The_AT results_NN2 from_II the_AT survey_NN1 agree_VV0 with_IW those_DD2 of_IO Banyte_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
in_CS21 that_CS22 women_NN2 are_VBR much_RR more_RGR concerned_JJ about_II environmental_JJ issues_NN2 than_CSN men_NN2 ._. 
</s>
<s>
This_DD1 is_VBZ important_JJ as_CSA women_NN2 are_VBR often_RR the_AT ones_NN2 who_PNQS shop_VV0 for_IF the_AT family_NN1 and_CC make_VV0 the_AT decisions_NN2 about_II which_DDQ products_NN2 and_CC services_NN2 the_AT family_NN1 will_VM purchase_VVI ._. 
</s>
<s>
(_( ibid_RR )_) Finisterra_NP1 do_VD0 Pao_NP1 &;_NULL Raposo_NP1 (_( 2010:434-435_MCMC )_) found_VVD three_MC segments_NN2 of_IO consumers_NN2 ,_, based_VVN on_II their_APPGE preferences_NN2 for_IF eco-friendliness_NN1 ._. 
</s>
<s>
The_AT uncommitted_JJ have_VH0 knowledge_NN1 about_II environmental_JJ issues_NN2 ,_, but_CCB do_VD0 not_XX engage_VVI in_II any_DD environmentally_RR friendly_JJ behavior_NN1 ._. 
</s>
<s>
The_AT green_JJ activists_NN2 are_VBR individuals_NN2 in_II the_AT ages_NN2 between_II 25_MC and_CC 34_MC and_CC between_II 45_MC and_CC 54_MC ._. 
</s>
<s>
The_AT individuals_NN2 with_IW the_AT highest_JJT education_NN1 levels_NN2 ,_, working_VVG in_II more_RGR qualified_JJ jobs_NN2 and_CC earning_VVG higher_JJR incomes_NN2 can_VM be_VBI found_VVN in_II this_DD1 segment_NN1 ._. 
</s>
<s>
They_PPHS2 feel_VV0 strongly_RR about_II all_DB environmental_JJ aspects_NN2 ,_, particularly_RR towards_II perceived_JJ efficiency_NN1 ,_, environmentally_RR friendly_JJ buying_NN1 behavior_NN1 ,_, recycling_VVG ,_, sensitivity_NN1 to_II the_AT economic_JJ factor_NN1 and_CC resource_VV0 saving_NN1 ._. 
</s>
<s>
The_AT undefined_JJ have_VH0 a_AT1 positive_JJ attitude_NN1 towards_II recycling_NN1 but_CCB are_VBR highly_RR skeptical_JJ about_II the_AT promotional_JJ and_CC advertising_NN1 claims_NN2 made_VVN by_II firms_NN2 ._. 
</s>
<s>
This_DD1 group_NN1 thinks_VVZ that_CST their_APPGE individual_JJ actions_NN2 can_VM not_XX contribute_VVI to_II saving_VVG the_AT environment_NN1 and_CC environmental_JJ issues_NN2 do_VD0 not_XX concern_VVI them_PPHO2 much_RR ._. 
</s>
<s>
(_( ibid_RR )_) Chen_NP1 (_( 2009:12_MC )_) declares_VVZ that_CST once_CS status_NN1 becomes_VVZ a_AT1 concern_NN1 people_NN become_VV0 more_RGR likely_JJ to_TO go_VVI green_JJ ._. 
</s>
<s>
Wealth_NN1 and_CC self-sacrifice_NN1 boost_VV0 social_JJ status_NN1 ,_, and_CC going_VVG green_NN1 proclaims_VVZ that_CST the_AT buyer_NN1 not_XX only_RR has_VHZ the_AT wealth_NN1 to_TO buy_VVI a_AT1 (_( sometimes_RT )_) pricier_JJR product_NN1 ,_, but_CCB is_VBZ also_RR willing_JJ to_TO sacrifice_VVI personal_JJ comfort_NN1 for_IF the_AT greater_JJR good_JJ ._. 
</s>
<s>
(_( ibid_RR )_) Figure_NN1 1_MC1 summarizes_VVZ the_AT different_JJ characteristics_NN2 of_IO luxury_JJ consumers_NN2 and_CC green_JJ consumers_NN2 ._. 
</s>
<s>
The_AT figure_NN1 shows_VVZ that_DD1 luxury_NN1 and_CC green_JJ consumers_NN2 are_VBR very_RG much_DA1 alike_RR ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) 3_MC Methodology_NN1 This_DD1 chapter_NN1 discusses_VVZ the_AT methodology_NN1 used_VVN in_II the_AT paper_NN1 ._. 
</s>
<s>
The_AT method_NN1 ,_, the_AT sample_NN1 and_CC the_AT collection_NN1 of_IO data_NN are_VBR explained_VVN ._. 
</s>
<s>
3.1_MC Method_NN1 The_AT aim_NN1 of_IO this_DD1 study_NN1 is_VBZ to_TO investigate_VVI whether_CSW consumers_NN2 perceive_VV0 luxury_JJ brands_NN2 as_CSA environmentally_RR friendly_JJ or_CC not_XX ._. 
</s>
<s>
The_AT aim_NN1 will_VM be_VBI achieved_VVN by_II explorative_JJ research_NN1 and_CC qualitative_JJ methods_NN2 ._. 
</s>
<s>
Saunders_NP1 ,_, Lewis_NP1 &;_NULL Thornhill_NP1 (_( 2003:96_MC )_) cite_VV0 Robson_NP1 (_( 2002:59_MC )_) and_CC describe_VV0 explorative_JJ research_NN1 as_II a_AT1 valuable_JJ means_NN of_IO finding_VVG out_RP what_DDQ is_VBZ happening_VVG ;_; to_TO seek_VVI new_JJ insights_NN2 ;_; to_TO ask_VVI questions_NN2 and_CC to_TO assess_VVI phenomena_NN2 in_II a_AT1 new_JJ light_NN1 ._. 
</s>
<s>
Qualitative_JJ data_NN is_VBZ based_VVN on_II meanings_NN2 expressed_VVN through_II words_NN2 ._. 
</s>
<s>
The_AT collection_NN1 of_IO qualitative_JJ data_NN results_NN2 in_II non-standardized_JJ data_NN that_CST requires_VVZ classification_NN1 into_II categories_NN2 ._. 
</s>
<s>
(_( Saunders_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2003:378_MC )_) It_PPH1 is_VBZ common_JJ to_TO use_VVI interviews_NN2 when_CS performing_VVG explorative_JJ research_NN1 (_( Saunders_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2003:250_MC )_) ._. 
</s>
<s>
Saunders_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2003:246_MC )_) distinguish_VV0 between_II three_MC types_NN2 of_IO interviews_NN2 :_: structured_JJ ,_, semi-structured_JJ and_CC unstructured_JJ ._. 
</s>
<s>
Semi-structured_JJ interviews_NN2 will_VM be_VBI used_VVN in_II this_DD1 paper_NN1 ._. 
</s>
<s>
In_II semi-structured_JJ interviews_NN2 ,_, the_AT researcher_NN1 has_VHZ a_AT1 list_NN1 of_IO themes_NN2 and_CC questions_NN2 to_TO be_VBI covered_VVN ,_, but_CCB these_DD2 can_VM vary_VVI between_II interviews_NN2 ._. 
</s>
<s>
The_AT order_NN1 of_IO the_AT questions_NN2 may_VM vary_VVI ,_, some_DD may_VM be_VBI omitted_VVN and_CC additional_JJ questions_NN2 may_VM be_VBI needed_VVN depending_II21 on_II22 the_AT flow_NN1 of_IO the_AT discussion_NN1 ._. 
</s>
<s>
(_( Saunders_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2003:246-247_MCMC )_) The_AT chosen_JJ method_NN1 is_VBZ justified_VVN because_II21 of_II22 the_AT nature_NN1 of_IO the_AT research_NN1 questions_NN2 ._. 
</s>
<s>
Deeper_JJR responses_NN2 (_( compared_VVN with_IW simple_JJ yes/no-answers_FU )_) are_VBR needed_VVN to_TO reach_VVI the_AT aim_NN1 of_IO the_AT paper_NN1 and_CC understand_VV0 how_RRQ consumers_NN2 feel_VV0 about_II the_AT eco-friendliness_NN1 of_IO luxury_JJ brands_NN2 ._. 
</s>
<s>
3.2_MC Sample_VV0 The_AT respondents_NN2 were_VBDR chosen_VVN through_II non-probability_JJ sampling_NN1 ,_, which_DDQ implies_VVZ that_CST the_AT probability_NN1 of_IO each_DD1 case_NN1 being_VBG selected_VVN from_II the_AT total_JJ population_NN1 is_VBZ not_XX known_VVN (_( Saunders_NP1 et_RA21 al_RA22 2003:152_MC )_) ,_, and_CC more_RGR specifically_RR through_II convenience_NN1 sampling_NN1 ,_, which_DDQ involves_VVZ selecting_VVG those_DD2 cases_NN2 that_CST are_VBR easiest_JJT to_TO obtain_VVI for_IF the_AT sample_NN1 (_( Saunders_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2003:177_MC )_) ._. 
</s>
<s>
Because_CS women_NN2 are_VBR the_AT primary_JJ consumers_NN2 of_IO luxury_NN1 and_CC eco-friendly_JJ products_NN2 ,_, the_AT respondents_NN2 consist_VV0 of_IO women_NN2 between_II the_AT ages_NN2 of_IO 20-32_MCMC ._. 
</s>
<s>
The_AT women_NN2 are_VBR the_AT same_DA interviewed_VVD for_IF my_APPGE bachelors_NN2 thesis_NN1 ._. 
</s>
<s>
3.3_MC Collection_NN1 of_IO data_NN The_AT interviews_NN2 were_VBDR based_VVN on_II an_AT1 interview_NN1 guide_NN1 (_( see_VV0 Appendix_NN1 1_MC1 )_) ._. 
</s>
<s>
The_AT questions_NN2 were_VBDR developed_VVN from_II the_AT research_NN1 questions_NN2 in_II the_AT introduction_NN1 and_CC can_VM be_VBI considered_VVN more_RGR general_JJ and_CC open_JJ than_CSN the_AT specific_JJ research_NN1 questions_NN2 ._. 
</s>
<s>
This_DD1 section_NN1 will_VM further_RRR explain_VVI how_RRQ the_AT data_NN was_VBDZ collected_VVN ._. 
</s>
<s>
4_MC Results_NN2 This_DD1 chapter_NN1 will_VM include_VVI the_AT results_NN2 from_II the_AT interviews_NN2 ._. 
</s>
<s>
5_MC Discussion_NN1 This_DD1 chapter_NN1 will_VM discuss_VVI the_AT results_NN2 related_VVN to_II the_AT theory_NN1 presented_VVN in_II chapter_NN1 2_MC ._. 
</s>
<s>
Managerial_JJ implications_NN2 and_CC tips_NN2 for_IF further_JJR research_NN1 will_VM also_RR be_VBI presented_VVN ._. 
</s>
<s>
5.1_MC Discussion_NN1 of_IO results_NN2 5.2_MC Managerial_JJ implications_NN2 This_DD1 section_NN1 presents_NN2 what_DDQ the_AT results_NN2 implicate_VV0 for_IF managers_NN2 ._. 
</s>
<s>
5.3_MC Further_JJR research_NN1 The_AT ethics_NN of_IO luxury_JJ brands_NN2 could_VM be_VBI an_AT1 interesting_JJ field_NN1 of_IO research_NN1 ._. 
</s>
<s>
Buyers_NN2 of_IO luxury_JJ goods_NN2 do_VD0 not_XX by_II counterfeits_NN2 that_CST fund_NN1 terrorism_NN1 ._. 
</s>
<s>
Country-of-origin_NN1 ;_; Italy_NP1 or_CC France_NP1 ,_, probably_RR means_VVZ that_CST no_AT child_NN1 labor_NN1 is_VBZ involved_VVN ._. 
</s>
