<s>
INTRODUCTION_NN1 In_II todays_NN2 competitive_JJ environment_NN1 ,_, marketing_NN1 and_CC advertising_NN1 are_VBR vital_JJ strategic_JJ activities_NN2 for_IF every_AT1 company_NN1 ._. 
</s>
<s>
Especially_RR food_NN1 marketers_NN2 face_VV0 a_AT1 huge_JJ competition_NN1 in_II markets_NN2 and_CC therefore_RR ,_, advertising_NN1 is_VBZ particularly_RR crucial_JJ for_IF them_PPHO2 ._. 
</s>
<s>
The_AT motivator_NN1 for_IF this_DD1 intense_JJ food_NN1 market_NN1 is_VBZ realistic_JJ ;_; food_NN1 is_VBZ a_AT1 necessity_NN1 for_IF all_DB consumers_NN2 and_CC thus_RR captures_VVZ a_AT1 main_JJ portion_NN1 of_IO consumers_NN2 lifelong_JJ spending_NN1 ;_; food_NN1 is_VBZ a_AT1 repeat-purchase_JJ item_NN1 and_CC consumers_NN2 may_VM switch_VVI their_APPGE purchasing_NN1 habits_NN2 quickly_RR and_CC ;_; food_NN1 products_NN2 are_VBR one_MC1 of_IO the_AT most_RGT branded_JJ items_NN2 which_DDQ require_VV0 significant_JJ advertising_NN1 (_( Story_NN1 et_RA21 al_RA22 ._. 
</s>
<s>
2004:2_MC )_) ._. 
</s>
<s>
In_II the_AT past_JJ forty_MC years_NNT2 marketers_NN2 have_VH0 realized_VVN that_CST there_EX is_VBZ a_AT1 huge_JJ market_NN1 among_II children_NN2 ._. 
</s>
<s>
Nearly_RR two_MC billion_NNO dollars_NNU2 was_VBDZ spent_VVN on_II advertising_NN1 for_IF children_NN2 only_RR in_II the_AT United_NP1 States_NP1 in_II 2007_MC (_( Smith_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
Advertisers_NN2 target_VV0 children_NN2 not_XX only_RR because_II21 of_II22 their_APPGE own_DA spending_NN1 power_NN1 but_CCB also_RR because_II21 of_II22 their_APPGE influence_NN1 on_II their_APPGE parents_NN2 purchasing_VVG behavior_NN1 and_CC because_II21 of_II22 their_APPGE future_NN1 as_CSA potential_JJ adult_NN1 consumers_NN2 (_( Story_NN1 et_RA21 al_RA22 ._. 
</s>
<s>
2004_MC )_) ._. 
</s>
<s>
Although_CS marketers_NN2 see_VV0 children_NN2 as_II an_AT1 important_JJ target_NN1 group_NN1 ,_, the_AT question_NN1 of_IO ethicalness_NN1 arises_VVZ particularly_RR when_CS children_NN2 are_VBR involved_VVN ._. 
</s>
<s>
But_CCB is_VBZ it_PPH1 really_RR needed_VVN to_TO advertise_VVI for_IF children_NN2 ?_? 
</s>
<s>
If_CS so_RR ,_, is_VBZ it_PPH1 ethical_JJ to_TO advertise_VVI to_II them_PPHO2 and_CC should_VM there_EX be_VBI some_DD restrictions_NN2 for_IF it_PPH1 ?_? 
</s>
<s>
Not_XX only_RR are_VBR there_RL ethical_JJ issues_NN2 with_IW advertising_NN1 for_IF children_NN2 but_CCB also_RR in_RR21 addition_RR22 ,_, there_EX are_VBR real_JJ health_NN1 related_JJ concerns_NN2 with_IW childrens_NN2 food_NN1 advertising_NN1 ._. 
</s>
<s>
There_EX have_VH0 been_VBN discussions_NN2 about_II the_AT relationship_NN1 of_IO food_NN1 advertising_NN1 and_CC childhood_NN1 obesity_NN1 that_CST is_VBZ increasing_JJ ,_, especially_RR in_II the_AT United_NP1 States_NP1 ._. 
</s>
<s>
Many_DA2 scholars_NN2 think_VV0 that_CST even_CS21 if_CS22 there_EX are_VBR many_DA2 contributing_JJ factors_NN2 to_II overweight_JJ children_NN2 ,_, the_AT activities_NN2 of_IO food_NN1 marketers_NN2 present_VV0 one_MC1 of_IO the_AT major_JJ reasons_NN2 for_IF childrens_NN2 obesity_NN1 (_( Grimm_NP1 ,_, 2004_MC )_) ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, studies_NN2 show_VV0 that_CST almost_RR 95%_NNU of_IO advertised_JJ foods_NN2 for_IF children_NN2 are_VBR high-fat_JJ ,_, high-sugar_NN1 ,_, or_CC high-salt_NN1 products_NN2 (_( Grimm_NP1 ,_, 2004_MC ;_; Story_NN1 ,_, 2004_MC )_) ._. 
</s>
<s>
This_DD1 paper_NN1 attempts_NN2 to_TO present_VVI the_AT nature_NN1 of_IO advertising_NN1 and_CC some_DD areas_NN2 of_IO concerns_NN2 that_CST are_VBR involved_VVN especially_RR when_CS marketing_VVG for_IF children_NN2 ._. 
</s>
<s>
The_AT later_JJR section_NN1 provides_VVZ some_DD information_NN1 on_II already_RR existing_JJ regulations_NN2 with_IW the_AT marketing_NN1 activities_NN2 towards_II children_NN2 and_CC some_DD possible_JJ shortages_NN2 within_II it_PPH1 ._. 
</s>
<s>
In_II the_AT end_NN1 of_IO the_AT paper_NN1 ethical_JJ questions_NN2 concerning_II childrens_NN2 advertising_VVG in_II food-related_JJ products_NN2 will_VM be_VBI discussed_VVN as_II31 well_II32 as_II33 the_AT problem_NN1 of_IO childrens_NN2 obesity_NN1 ._. 
</s>
<s>
Finally_RR ,_, the_AT paper_NN1 will_VM try_VVI to_TO present_VVI some_DD future_JJ suggestions_NN2 for_IF the_AT area_NN1 of_IO childrens_NN2 marketing_NN1 ._. 
</s>
<s>
NATURE_NN1 OF_IO ADVERTISING_VVG The_AT preliminary_JJ purpose_NN1 of_IO advertising_NN1 is_VBZ to_TO create_VVI brand_NN1 awareness_NN1 and_CC recognition_NN1 ,_, despite_II the_AT target_NN1 group_NN1 in_II question_NN1 ._. 
</s>
<s>
However_RGQV especially_RR for_IF the_AT target_NN1 group_NN1 of_IO children_NN2 ,_, this_DD1 aim_NN1 is_VBZ even_RR further_RRR important_JJ ._. 
</s>
<s>
Children_NN2 have_VH0 a_AT1 huge_JJ potential_NN1 for_IF future_JJ market_NN1 and_CC ,_, therefore_RR ,_, marketers_NN2 think_VV0 that_CST it_PPH1 is_VBZ vital_JJ to_TO build_VVI this_DD1 brand_NN1 awareness_NN1 early_RR in_II their_APPGE life_NN1 (_( Moore_NP1 ,_, 2004_MC )_) ._. 
</s>
<s>
A_AT1 clear_JJ example_NN1 of_IO this_DD1 importance_NN1 of_IO the_AT childrens_NN2 market_VV0 is_VBZ that_DD1 focus_NN1 groups_NN2 in_II marketing_NN1 purposes_NN2 are_VBR arranged_VVN for_IF as_RG young_JJ children_NN2 as_CSA five_MC years_NNT2 old_JJ !_! 
</s>
<s>
(_( CITATION_NN1 needed_VVD ._. 
</s>
<s>
Need_VV0 to_TO find_VVI the_AT article_NN1 ,_, coming_VVG up_RP in_II the_AT second_MD draft_NN1 !_! )_) 
</s>
<s>
The_AT most_RGT advertised_JJ products_NN2 for_IF children_NN2 are_VBR food_NN1 and_CC beverages_NN2 as_II31 well_II32 as_II33 toys_NN2 ._. 
</s>
<s>
Some_DD critics_NN2 have_VH0 been_VBN raised_VVN due_II21 to_II22 the_AT commercialization_NN1 of_IO social_JJ and_CC religious_JJ events_NN2 like_II Christmas_NNT1 ,_, for_REX21 example_REX22 (_( Gunter_NP1 et_RA21 al._RA22 ,_, 2005_MC )_) ._. 
</s>
<s>
Pine_NN1 and_CC Nash_NP1 (_( 2002_MC ,_, cited_VVN in_II Preston_NP1 ,_, 2005_MC )_) discovered_VVD that_CST during_II Christmas_NNT1 time_NNT1 ,_, children_NN2 who_PNQS viewed_VVD television_NN1 and_CC saw_VVD toy_JJ advertisements_NN2 regularly_RR ,_, requested_VVN more_RRR presents_VVZ overall_JJ and_CC also_RR specific_JJ toys_NN2 by_II brand_NN1 name_NN1 -_- compared_VVN to_II children_NN2 who_PNQS were_VBDR not_XX exposed_VVN to_TO toy_VVI advertisements_NN2 ._. 
</s>
<s>
This_DD1 illustrates_VVZ how_RRQ advertisements_NN2 have_VH0 the_AT commercial_JJ effect_NN1 on_II children_NN2 ._. 
</s>
<s>
The_AT main_JJ channel_NN1 to_TO reach_VVI children_NN2 is_VBZ television_NN1 ._. 
</s>
<s>
According_II21 to_II22 Gunter_NP1 et_RA21 al._RA22 ,_, there_EX are_VBR some_DD reasons_NN2 why_RRQ television_NN1 is_VBZ the_AT best_JJT way_NN1 to_TO reach_VVI children_NN2 ._. 
</s>
<s>
First_MD ,_, nearly_RR all_DB families_NN2 have_VH0 a_AT1 TV_NN1 at_II their_APPGE house_NN1 ._. 
</s>
<s>
Additionally_RR ,_, today_RT it_PPH1 is_VBZ quite_RG normal_JJ that_CST children_NN2 have_VH0 a_AT1 TV_NN1 in_II their_APPGE own_DA room_NN1 and_CC thus_RR ,_, it_PPH1 is_VBZ relatively_RR easy_JJ to_TO advertise_VVI for_IF children_NN2 via_II television_NN1 ._. 
</s>
<s>
Kunkel_NP1 (_( 2001_MC ,_, cited_VVN in_II Gunter_NP1 et_RA21 al._RA22 ,_, 2005_MC )_) proposed_VVD that_CST contemporary_JJ children_NN2 may_VM view_VVI as_RG many_DA2 as_CSA 40,000_MC commercials_NN2 each_DD1 year_NNT1 in_II the_AT United_NP1 States_NP1 which_DDQ explains_VVZ how_RRQ TV_NN1 is_VBZ the_AT biggest_JJT marketing_NN1 channel_NN1 for_IF children_NN2 ._. 
</s>
<s>
EUROPE_NP1 STATS_VVZ COMING_VVG !_! 
</s>
<s>
Second_MD ,_, there_EX is_VBZ limited_JJ control_NN1 and_CC regulations_NN2 with_IW television_NN1 advertising_NN1 for_IF children_NN2 ,_, which_DDQ will_VM be_VBI discussed_VVN in_II depth_NN1 later_RRR in_II the_AT paper_NN1 ._. 
</s>
<s>
Furthermore_RR ,_, children_NN2 do_VD0 not_XX only_RR watch_VVI TV_NN1 on_II their_APPGE own_DA but_CCB also_RR with_IW their_APPGE parents_NN2 at_II prime_JJ time_NNT1 which_DDQ exposes_VVZ children_NN2 to_II many_DA2 additional_JJ advertisements_NN2 ._. 
</s>
<s>
(_( Gunter_NP1 et_RA21 al._RA22 ,_, 2005_MC )_) ._. 
</s>
<s>
THE_AT DISCUSSION_NN1 OF_IO THE_AT AGE_NN1 There_EX has_VHZ been_VBN ,_, and_CC still_RR is_VBZ ,_, an_AT1 extensive_JJ discussion_NN1 of_IO what_DDQ is_VBZ the_AT right_JJ age_NN1 to_TO market_VVI towards_II children_NN2 ._. 
</s>
<s>
When_RRQ are_VBR children_NN2 old_JJ enough_RR to_TO understand_VVI the_AT advertisements_NN2 ?_? 
</s>
<s>
And_CC what_DDQ is_VBZ the_AT age_NN1 that_CST children_NN2 are_VBR not_XX thought_VVN to_TO be_VBI too_RG vulnerable_JJ for_IF advertisements_NN2 ?_? 
</s>
<s>
The_AT common_JJ thought_NN1 is_VBZ that_CST children_NN2 are_VBR old_JJ enough_RR to_TO be_VBI marketed_VVN when_CS they_PPHS2 can_VM distinguish_VVI the_AT difference_NN1 between_II TV_NN1 programs_NN2 and_CC commercials_NN2 ._. 
</s>
<s>
Children_NN2 must_VM be_VBI able_JK to_TO separate_VVI when_RRQ an_AT1 advertisement_NN1 starts_VVZ and_CC when_CS it_PPH1 ends_VVZ ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, children_NN2 must_VM understand_VVI the_AT intent_NN1 of_IO advertising_NN1 ;_; the_AT realization_NN1 that_CST advertising_NN1 is_VBZ done_VDN to_TO create_VVI purchasing_NN1 behavior_NN1 (_( Gunter_NP1 et_RA21 al._RA22 ,_, 2005_MC )_) ._. 
</s>
<s>
Many_DA2 theories_NN2 have_VH0 been_VBN used_VVN to_TO interpret_VVI the_AT correct_JJ and_CC more_RGR specifically_RR the_AT ethical_JJ age_NN1 of_IO children_NN2 to_TO be_VBI advertised_VVN for_IF ._. 
</s>
<s>
One_MC1 theory_NN1 that_CST is_VBZ usually_RR referred_VVN to_II is_VBZ Jean_NP1 Piagets_NP2 theory_NN1 of_IO four_MC cognitive_JJ stages_NN2 in_II childrens_NN2 development_NN1 ._. 
</s>
<s>
Piagets_NP2 theory_NN1 focuses_VVZ on_II childrens_NN2 problem_NN1 solving_VVG at_II different_JJ cognitive_JJ levels_NN2 ._. 
</s>
<s>
Therefore_RR in_II this_DD1 theory_NN1 ,_, childrens_NN2 understanding_NN1 of_IO advertisements_NN2 should_VM be_VBI considered_VVN as_CSA problem_NN1 solving_NN1 ._. 
</s>
<s>
In_II reality_NN1 however_RR ,_, implying_VVG Piagets_NP2 theory_NN1 is_VBZ not_XX as_RG straightforward_JJ as_CSA it_PPH1 is_VBZ in_II theory_NN1 ._. 
</s>
<s>
The_AT main_JJ message_NN1 that_CST is_VBZ taken_VVN from_II his_APPGE theory_NN1 is_VBZ that_CST children_NN2 have_VH0 limited_VVN cognitive_JJ abilities_NN2 and_CC thus_RR ,_, they_PPHS2 possess_VV0 limited_JJ understanding_NN1 of_IO advertisements_NN2 at_II different_JJ stages_NN2 ._. 
</s>
<s>
For_REX21 example_REX22 according_II21 to_II22 Piaget_NP1 ,_, children_NN2 at_II preoperational_JJ stage_NN1 (_( 2-7_MCMC years_NNT2 old_JJ )_) have_VH0 a_AT1 huge_JJ egocentrism_NN1 phase_NN1 which_DDQ indicates_VVZ that_CST they_PPHS2 can_VM not_XX understand_VVI ideas_NN2 or_CC thoughts_NN2 from_II anyone_PN1 elses_VVZ point_NN1 of_IO view_NN1 ._. 
</s>
<s>
Therefore_RR ,_, it_PPH1 is_VBZ likely_JJ that_CST they_PPHS2 will_VM have_VHI difficulty_NN1 understanding_VVG the_AT persuasive_JJ nature_NN1 of_IO advertising_NN1 (_( Gunter_NP1 et_RA21 al._RA22 ,_, 2005:65_MC )_) ._. 
</s>
<s>
Overall_RR ,_, it_PPH1 is_VBZ thought_VVN that_CST children_NN2 around_RG eight_MC years_NNT2 old_JJ would_VM understand_VVI the_AT intent_NN1 of_IO advertising_NN1 and_CC the_AT differences_NN2 between_II reality_NN1 and_CC advertisement_NN1 as_II31 well_II32 as_II33 the_AT differences_NN2 between_II TV_NN1 shows_NN2 and_CC advertisements_NN2 ._. 
</s>
<s>
Many_DA2 scholars_NN2 think_VV0 that_CST at_II the_AT age_NN1 of_IO eight_MC children_NN2 will_VM be_VBI developed_VVN enough_RR to_TO be_VBI exposed_VVN to_II advertising_NN1 ;_; children_NN2 below_RG seven_MC or_CC eight_MC are_VBR not_XX so_RR equipped_VVN to_TO deal_VVI with_IW advertising_NN1 (_( Preston_NP1 ,_, 2004:366_MC )_) ._. 
</s>
<s>
Hence_RR ,_, an_AT1 ethical_JJ age_NN1 for_IF children_NN2 who_PNQS are_VBR advertised_VVN for_CS would_VM be_VBI at_RR21 least_RR22 eight_MC years_NNT2 old_JJ ._. 
</s>
<s>
AREAS_NN2 OF_IO CONCERN_NN1 Gunter_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2005_MC )_) identifies_VVZ six_MC different_JJ areas_NN2 of_IO concern_NN1 in_II marketing_NN1 and_CC advertising_NN1 for_IF young_JJ children_NN2 ._. 
</s>
<s>
Due_II21 to_II22 childrens_NN2 vulnerability_NN1 and_CC lack_NN1 of_IO reliable_JJ judgment_NN1 skills_NN2 ,_, these_DD2 concerns_NN2 may_VM mislead_VVI children_NN2 in_II an_AT1 advertisement_NN1 ._. 
</s>
<s>
These_DD2 areas_NN2 of_IO concern_NN1 include_VV0 exaggeration_NN1 ,_, fantasy_NN1 ,_, particular_JJ appeals_NN2 ,_, celebrities_NN2 ,_, use_NN1 of_IO metaphors_NN2 ,_, and_CC special_JJ effects_NN2 (_( Gunter_NP1 et_RA21 al._RA22 ,_, 2005_MC )_) ._. 
</s>
<s>
Exaggeration_NN1 refers_VVZ to_II phrases_NN2 such_II21 as_II22 better_JJR than_CSN and_CC the_AT best_JJT which_DDQ may_VM be_VBI very_RG misleading_JJ and_CC deceptive_JJ for_IF children_NN2 ._. 
</s>
<s>
The_AT idea_NN1 behind_II fantasy_NN1 is_VBZ that_CST advertisements_NN2 are_VBR creating_VVG a_AT1 fantasy_NN1 environment_NN1 and_CC a_AT1 sort_NN1 of_IO magical_JJ picture_NN1 so_CS21 that_CS22 it_PPH1 may_VM be_VBI misleading_JJ to_II a_AT1 child_NN1 who_PNQS does_VDZ not_XX distinguish_VVI the_AT difference_NN1 between_II reality_NN1 and_CC an_AT1 advertisement_NN1 ._. 
</s>
<s>
Appeals_NN2 refer_VV0 to_II certain_JJ pitches_NN2 that_CST are_VBR used_VVN in_II advertising_NN1 for_IF children_NN2 ._. 
</s>
<s>
These_DD2 themes_NN2 that_CST advertisers_NN2 are_VBR trying_VVG to_TO create_VVI in_II advertising_NN1 targeted_VVN to_II children_NN2 are_VBR fun/happiness_NN1 ,_, taste/flavor/smell_VV0 ,_, and_CC product_NN1 performance_NN1 (_( Gunter_NP1 et_RA21 al._RA22 ,_, 2005:21_MC )_) ._. 
</s>
<s>
These_DD2 pitches_NN2 may_VM create_VVI a_AT1 deceiving_JJ picture_NN1 for_IF children_NN2 about_II the_AT true_JJ nature_NN1 of_IO the_AT product_NN1 ._. 
</s>
<s>
Celebrities_NN2 is_VBZ an_AT1 area_NN1 where_CS popular_JJ people_NN and_CC cartoon_NN1 characteristics_NN2 are_VBR used_VVN in_II advertising_NN1 ._. 
</s>
<s>
Using_VVG of_IO celebrities_NN2 may_VM create_VVI confusion_NN1 to_II children_NN2 :_: the_AT use_NN1 of_IO celebrities_NN2 and_CC cartoons_NN2 diminishes_VVZ younger_JJR childrens_NN2 ability_NN1 to_TO distinguish_VVI advertising_NN1 from_II programmed_JJ material_NN1 (_( Preston_NP1 ,_, 2005:63_MC )_) ._. 
</s>
<s>
Metaphors_NN2 are_VBR ways_NN2 of_IO using_VVG the_AT language_NN1 in_II a_AT1 way_NN1 that_CST it_PPH1 attracts_VVZ the_AT children_NN2 ._. 
</s>
<s>
Their_APPGE purpose_NN1 is_VBZ to_TO create_VVI some_DD visual_JJ image_NN1 that_CST children_NN2 can_VM associate_VVI with_IW ._. 
</s>
<s>
The_AT last_MD area_NN1 of_IO concern_NN1 is_VBZ special_JJ effects_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ a_AT1 concern_NN1 because_CS the_AT special_JJ effect_NN1 techniques_NN2 used_VVN in_II advertising_NN1 may_VM mislead_VVI children_NN2 to_TO expect_VVI similar_JJ effects_NN2 if_CS using_VVG the_AT product_NN1 in_II question_NN1 (_( Gunter_NP1 et_RA21 al._RA22 ,_, 2005_MC )_) ._. 
</s>
<s>
In_II31 addition_II32 to_II33 these_DD2 above_JJ areas_NN2 of_IO concern_NN1 ,_, there_EX are_VBR incidental_JJ effects_NN2 that_CST may_VM follow_VVI from_II advertising_NN1 for_IF children_NN2 ._. 
</s>
<s>
These_DD2 incidental_JJ effects_NN2 are_VBR related_VVN to_II childrens_NN2 health_NN1 and_CC social_JJ concerns_NN2 such_II21 as_II22 advertising_NN1 on_II nutrition_NN1 ,_, smoking_VVG ,_, under-age_JJ drinking_NN1 ,_, social_JJ stereotyping_NN1 ,_, and_CC self-image_NN1 (_( Gunter_NP1 et_RA21 al._RA22 ,_, 2005:120_MC )_) ._. 
</s>
<s>
These_DD2 effects_NN2 will_VM not_XX be_VBI further_RRR discussed_VVN but_CCB it_PPH1 is_VBZ important_JJ to_TO realize_VVI that_DD1 advertising_NN1 may_VM be_VBI a_AT1 partial_JJ reason_NN1 why_RRQ children_NN2 face_VV0 with_IW issues_NN2 mentioned_VVN above_RL ._. 
</s>
<s>
REGULATIONS_NN2 The_AT APA_NP1 ,_, American_JJ Psychology_NN1 Association_NN1 ,_, think_VV0 that_CST under_RG eight_MC years_NNT2 old_JJ children_NN2 are_VBR too_RG vulnerable_JJ for_IF advertising_NN1 and_CC thus_RR ,_, it_PPH1 should_VM be_VBI legally_RR restricted_VVN (_( Preston_NP1 ,_, 2004_MC )_) ._. 
</s>
<s>
However_RR ,_, these_DD2 regulations_NN2 for_IF childrens_NN2 advertising_NN1 vary_VV0 a_AT1 lot_NN1 between_II countries_NN2 ._. 
</s>
<s>
There_EX are_VBR different_JJ regulations_NN2 around_II the_AT world_NN1 and_CC for_REX21 example_REX22 EXAMPLES_NN2 OF_IO EUROPEAN_JJ COUNTRIES_NN2 ._. 
</s>
<s>
These_DD2 regulations_NN2 vary_VV0 a_AT1 lot_NN1 between_II the_AT countries_NN2 due_II21 to_II22 diverse_JJ value_NN1 systems_NN2 in_II each_DD1 country_NN1 as_II31 well_II32 as_II33 the_AT differences_NN2 in_II media_NN &;_NULL advertising_NN1 structures_NN2 ._. 
</s>
<s>
Generally_RR ,_, there_EX are_VBR two_MC areas_NN2 of_IO regulations_NN2 that_CST are_VBR common_JJ in_II Europe_NP1 ;_; 1_MC1 )_) scheduling_NN1 of_IO the_AT advertisements_NN2 and_CC 2_MC )_) the_AT content_NN1 of_IO the_AT advertisement_NN1 ._. 
</s>
<s>
EXAMPLES_NN2 !_! 
</s>
<s>
(_( Gunter_NP1 et_RA21 al._RA22 ,_, 2005_MC )_) ._. 
</s>
<s>
This_DD1 section_NN1 will_VM talk_VVI about_II food_NN1 advertising_NN1 and_CC especially_RR about_II the_AT products_NN2 that_CST are_VBR high_JJ in_II fat_NN1 and_CC sugar_NN1 etc_RA ._. 
</s>
<s>
I_PPIS1 want_VV0 to_TO present_VVI the_AT question_NN1 of_IO is_VBZ it_PPH1 wrong_RR from_II marketers_NN2 to_TO advertise_VVI these_DD2 products_NN2 or_CC is_VBZ it_PPH1 actually_RR the_AT producers_NN2 of_IO the_AT products_NN2 that_CST are_VBR to_TO blame_VVI ._. 
</s>
<s>
Is_VBZ it_PPH1 ethical_JJ even_RR to_TO produce_VVI products_NN2 that_CST have_VH0 poor_JJ nutritional_JJ values_NN2 for_IF children_NN2 who_PNQS are_VBR growing_VVG and_CC developing_JJ ._. 
</s>
<s>
(_( Articles_NN2 :_: Preston_NP1 ,_, 2004_MC ;_; Vashishtha_NP1 ,_, 2010_MC ;_; Metha_NP1 et_RA21 al._RA22 ,_, 2010_MC ;_; OSullivan_NP1 ,_, 2005_MC )_) ._. 
</s>
<s>
*online_FO advertising_NN1 CHILHOOD_NN1 OBESITY_NN1 I_PPIS1 would_VM like_VVI to_TO include_VVI this_DD1 chapter_NN1 on_II the_AT paper_NN1 since_CS it_PPH1 is_VBZ an_AT1 increasing_JJ problem_NN1 ._. 
</s>
<s>
Not_XX quite_RG sure_JJ where_RRQ to_TO include_VVI it_PPH1 ._. 
</s>
<s>
(_( Articles_NN2 :_: Metha_NP1 et_RA21 al._RA22 ,_, 2010_MC ;_; OSullivan_NP1 ,_, 2005_MC ._. 
</s>
<s>
Gunter_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
and_CC another_DD1 material_NN1 ?_? )_) 
</s>
<s>
ETHICAL_JJ VS_II ._. 
</s>
<s>
UNETHICAL_NP1 A_ZZ1 discussion_NN1 of_IO whether_CSW childrens_NN2 advertising_NN1 is_VBZ ethical_JJ or_CC unethical_JJ ._. 
</s>
<s>
More_DAR sources_NN2 needed_VVD one_MC1 book_NN1 ;_; Ethical_JJ marketing_NN1 ._. 
</s>
<s>
RECOMMENDATIONS_NN2 ?_? ?_? ?_? 
</s>
<s>
CONCLUSION_NN1 
</s>
