<s>
Is_VBZ it_PPH1 possible_JJ for_IF a_AT1 company_NN1 to_TO measure_VVI the_AT strength_NN1 of_IO their_APPGE own_DA brand_NN1 ?_? 
</s>
<s>
Testing_NN1 of_IO Rank_NN1 of_IO Mind_NN1 in_II practice_NN1 1_MC1 Introduction_NN1 In_II the_AT last_MD 20_MC years_NNT2 there_EX have_VH0 been_VBN many_DA2 papers_NN2 describing_VVG branding_NN1 ,_, brand_NN1 loyalty_NN1 and_CC how_RRQ companies_NN2 with_IW strong_JJ brands_NN2 may_VM have_VHI a_AT1 competitive_JJ advantage_NN1 against_II companies_NN2 with_IW weaker_JJR brands_NN2 (_( Mrtenson_NP1 2009_MC ,_, Hkansson_NP1 2004_MC )_) ._. 
</s>
<s>
According_II21 to_II22 Hkansson_NP1 (_( 2004_MC )_) ,_, there_EX is_VBZ much_DA1 evidence_NN1 to_TO support_VVI the_AT idea_NN1 that_CST companies_NN2 with_IW strong_JJ brands_NN2 find_VV0 it_PPH1 easier_JJR to_TO create_VVI lasting_JJ and_CC tight_JJ customer_NN1 relationships_NN2 ,_, which_DDQ also_RR can_VM be_VBI concretely_RR seen_VVN in_II the_AT revenues_NN2 ._. 
</s>
<s>
Because_CS revenue_NN1 and_CC success_NN1 are_VBR relevant_JJ for_IF a_AT1 company_NN1 to_TO survive_VVI ,_, there_EX is_VBZ a_AT1 huge_JJ interest_NN1 to_TO research_VVI in_II brands_NN2 ,_, and_CC see_VVI which_DDQ aspects_NN2 that_CST may_VM affect_VVI the_AT brand_NN1 and_CC the_AT strength_NN1 of_IO it_PPH1 ._. 
</s>
<s>
When_CS a_AT1 company_NN1 knows_VVZ how_RRQ strong_JJ the_AT own_DA brand_NN1 is_VBZ ,_, and_CC how_RRQ the_AT customers_NN2 evaluate_VV0 the_AT brand_NN1 ,_, is_VBZ it_PPH1 much_RR easier_JJR to_TO do_VDI decisions_NN2 according_II21 to_II22 the_AT development_NN1 of_IO the_AT brand_NN1 ._. 
</s>
<s>
Observation_NN1 by_II Hkansson_NP1 (_( 2004_MC )_) shows_VVZ that_DD1 interest_NN1 for_IF brands_NN2 and_CC branding_NN1 grew_VVD up_RP in_II the_AT end_NN1 of_IO the_AT 80s_MC2 ,_, when_RRQ people_NN realized_VVD that_CST companies_NN2 were_VBDR sold_VVN for_IF prices_NN2 that_CST could_VM correspond_VVI to_II 25_MC years_NNT2 profit_NN1 of_IO the_AT companies_NN2 ._. 
</s>
<s>
Where_CS the_AT money_NN1 is_VBZ ,_, lays_VVZ also_RR peoples_NN2 interest_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ why_RRQ there_EX has_VHZ been_VBN so_RG much_DA1 research_NN1 around_II brands_NN2 and_CC branding_VVG ,_, and_CC this_DD1 is_VBZ also_RR why_RRQ I_PPIS1 am_VBM going_VVGK to_TO focus_VVI this_DD1 research_NN1 paper_NN1 on_II branding_VVG ,_, brand_NN1 strength_NN1 and_CC brand_NN1 loyalty_NN1 of_IO customers_NN2 ._. 
</s>
<s>
But_CCB as_CSA in_II all_DB research_NN1 fields_NN2 ,_, the_AT information_NN1 is_VBZ not_XX complete_JJ ._. 
</s>
<s>
Many_DA2 researchers_NN2 ,_, for_REX21 example_REX22 Hkansson_NP1 (_( 2004_MC )_) and_CC Mrtenson_NP1 (_( 2009_MC )_) have_VH0 come_VVN up_RP with_IW models_NN2 and_CC theories_NN2 to_TO measure_VVI the_AT strength_NN1 of_IO a_AT1 brand_NN1 ,_, but_CCB nobody_PN1 has_VHZ tested_VVN these_DD2 theories_NN2 in_II practice_NN1 to_TO see_VVI if_CSW they_PPHS2 really_RR work_VV0 with_IW real_JJ existing_JJ companies_NN2 ._. 
</s>
<s>
Although_CS all_DB the_AT previous_JJ experiments_NN2 have_VH0 been_VBN done_VDN on_II a_AT1 theoretical_JJ level_NN1 ,_, there_EX is_VBZ a_AT1 gap_NN1 in_II how_RRQ the_AT theories_NN2 work_VV0 in_II practice_NN1 ._. 
</s>
<s>
Because_CS few_DA2 researchers_NN2 have_VH0 studied_VVN this_DD1 area_NN1 ,_, I_PPIS1 see_VV0 a_AT1 possibility_NN1 to_TO create_VVI a_AT1 new_JJ research_NN1 platform_NN1 ,_, which_DDQ in_II the_AT future_NN1 may_VM help_VVI companies_NN2 to_TO focus_VVI on_II the_AT right_NN1 and_CC relevant_JJ aspects_NN2 in_II branding_VVG and_CC brand_NN1 creation_NN1 ._. 
</s>
<s>
The_AT questions_NN2 remain_VV0 :_: Do_VD0 theoretical_JJ frameworks_NN2 that_CST have_VH0 been_VBN made_VVN up_RP for_IF measuring_VVG brand_NN1 strength_NN1 work_NN1 in_II practice_NN1 ?_? 
</s>
<s>
And_CC could_VM it_PPH1 be_VBI possible_JJ for_IF companies_NN2 in_II the_AT future_JJ to_TO use_VVI these_DD2 models_NN2 to_TO build_VVI strong_JJ brands_NN2 ?_? 
</s>
<s>
This_DD1 study_NN1 will_VM focus_VVI on_II answering_VVG these_DD2 questions_NN2 ,_, and_CC the_AT model_NN1 I_PPIS1 have_VH0 chosen_VVN to_TO test_VVI ,_, is_VBZ Hkanssons_NP2 (_( 2004_MC )_) Rank_NN1 of_IO Mind_NN1 that_CST during_II the_AT last_MD ten_MC years_NNT2 has_VHZ become_VVN quite_RG famous_JJ in_II marketing_NN1 divisions_NN2 ._. 
</s>
<s>
In_II this_DD1 paper_NN1 I_PPIS1 hope_VV0 to_TO show_VVI that_DD1 brand_NN1 awareness_NN1 of_IO the_AT company_NN1 is_VBZ important_JJ ,_, and_CC that_CST there_EX should_VM be_VBI a_AT1 model_NN1 for_IF the_AT companies_NN2 to_TO test_VVI their_APPGE brand_NN1 strength_NN1 so_CS21 that_CS22 strong_JJ brands_NN2 would_VM be_VBI developed_VVN in_II the_AT future_NN1 ._. 
</s>
<s>
This_DD1 paper_NN1 is_VBZ divided_VVN in_II five_MC chapters_NN2 and_CC is_VBZ structured_VVN as_CSA follows_VVZ :_: I_PPIS1 start_VV0 by_II presenting_VVG a_AT1 literature_NN1 review_NN1 ,_, where_CS I_PPIS1 bring_VV0 up_RP conclusions_NN2 by_II earlier_JJR researchers_NN2 ._. 
</s>
<s>
This_DD1 means_VVZ that_CST I_ZZ1 in_II the_AT chapter_NN1 will_VM identify_VVI what_DDQ a_AT1 brand_NN1 and_CC branding_VVG concretely_RR means_VVZ ,_, and_CC after_CS that_DD1 present_JJ Hkanssons_NP2 (_( 2004_MC )_) Rank_NN1 of_IO Mind_NN1 model_NN1 ,_, which_DDQ I_PPIS1 am_VBM going_VVGK to_TO use_VVI in_II my_APPGE study_NN1 ._. 
</s>
<s>
With_IW this_DD1 chapter_NN1 I_PPIS1 hope_VV0 to_TO give_VVI the_AT reader_NN1 an_AT1 overview_NN1 of_IO branding_VVG as_II a_AT1 subject_NN1 ,_, so_CS21 that_CS22 it_PPH1 is_VBZ easier_JJR for_IF the_AT reader_NN1 to_TO understand_VVI why_RRQ this_DD1 research_NN1 is_VBZ so_RG important_JJ ,_, and_CC how_RRQ this_DD1 research_NN1 could_VM improve_VVI companies_NN2 branding_VVG strategies_NN2 in_II the_AT future_NN1 ._. 
</s>
<s>
In_II the_AT third_MD chapter_NN1 I_PPIS1 will_VM present_VVI which_DDQ companies_NN2 I_PPIS1 have_VH0 chosen_VVN to_TO test_VVI the_AT Rank_NN1 of_IO Mind_NN1 model_NN1 on_RP ,_, and_CC then_RT how_RRQ I_PPIS1 have_VH0 decided_VVN to_TO do_VDI the_AT study_NN1 ._. 
</s>
<s>
Because_CS this_DD1 is_VBZ a_AT1 study_NN1 made_VVN on_II opinions_NN2 and_CC feelings_NN2 by_II the_AT customers_NN2 ,_, I_PPIS1 see_VV0 it_PPH1 based_VVN on_II (_( Hirsjrvi_NP1 &;_NULL Hurme_NP1 2001_MC )_) relevant_JJ to_TO do_VDI a_AT1 qualitative_JJ study_NN1 to_TO get_VVI as_RG reliable_JJ conclusion_NN1 on_II the_AT questions_NN2 ._. 
</s>
<s>
In_II chapter_NN1 four_MC I_PPIS1 will_VM present_VVI and_CC analyze_VVI the_AT material_NN1 I_PPIS1 have_VH0 collected_VVN in_II the_AT study_NN1 ,_, where_CS after_CS I_PPIS1 in_II chapter_NN1 five_MC will_VM present_VVI my_APPGE conclusions_NN2 and_CC give_VVI practical_JJ advices_NN2 and_CC suggestions_NN2 to_II companies_NN2 ,_, based_VVN on_II my_APPGE study._NNU 2_MC Theory_NN1 To_TO make_VVI this_DD1 research_NN1 relevant_JJ ,_, I_PPIS1 will_VM introduce_VVI this_DD1 paper_NN1 with_IW this_DD1 theory_NN1 chapter_NN1 ._. 
</s>
<s>
After_II reading_VVG this_DD1 chapter_NN1 the_AT reader_NN1 should_VM have_VHI a_AT1 clear_JJ picture_NN1 about_II what_DDQ a_AT1 brand_NN1 is_VBZ ,_, why_RRQ it_PPH1 is_VBZ important_JJ to_II a_AT1 company_NN1 ,_, how_RRQ it_PPH1 the_AT strength_NN1 of_IO it_PPH1 can_VM be_VBI measured_VVN ,_, and_CC how_RRQ the_AT Rank_NN1 of_IO Mind_NN1 model_NN1 can_VM be_VBI used_JJ to_II measure_NN1 the_AT brand_NN1 ._. 
</s>
<s>
The_AT chapter_NN1 i_ZZ1 divided_JJ as_CSA following_VVG :_: First_MD I_PPIS1 will_VM define_VVI what_DDQ a_AT1 brand_NN1 is_VBZ ,_, why_RRQ it_PPH1 is_VBZ important_JJ and_CC how_RRQ a_AT1 company_NN1 can_VM use_VVI it_PPH1 as_II an_AT1 competitive_JJ advantage_NN1 against_II its_APPGE competitors_NN2 ._. 
</s>
<s>
After_CS that_CST I_PPIS1 will_VM present_VVI some_DD background_NN1 information_NN1 to_II why_RRQ branding_NN1 have_VH0 been_VBN so_RG interesting_JJ as_II a_AT1 research_NN1 area_NN1 during_II the_AT last_MD 20_MC years_NNT2 ,_, and_CC finally_RR i_MC1 will_VM present_VVI the_AT Rank_NN1 of_IO Mind_NN1 modell_NN1 by_II Hkansson_NP1 (_( 2004_MC )_) to_TO show_VVI the_AT reader_NN1 in_II practise_NN1 how_RRQ a_AT1 brand_NN1 can_VM be_VBI measured._NNU 2.1_MC A_ZZ1 brand_NN1 -_- What_DDQ is_VBZ it_PPH1 ?_? 
</s>
<s>
According_II21 to_II22 AMA_NP1 (_( American_JJ Marketing_NN1 Association_NN1 )_) a_AT1 brand_NN1 is_VBZ :_: "_" Name_NN1 ,_, term_NN1 ,_, design_NN1 ,_, symbol_NN1 ,_, or_CC any_DD other_JJ feature_NN1 that_CST identifies_VVZ one_MC1 seller_NN1 's_GE good_JJ or_CC service_NN1 as_CSA distinct_JJ from_II those_DD2 of_IO other_JJ sellers_NN2 "_" But_CCB Hkansson_NP1 (_( 2004_MC )_) indicates_VVZ that_CST a_AT1 brand_NN1 is_VBZ also_RR something_PN1 that_CST you_PPY can_VM not_XX recognize_VVI with_IW a_AT1 bare_JJ eye_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ an_AT1 intangible_JJ resource_NN1 ,_, which_DDQ role_NN1 and_CC usage_NN1 for_IF the_AT company_NN1 has_VHZ increased_VVN radically_RR during_II the_AT last_MD 100_MC years_NNT2 ._. 
</s>
<s>
But_CCB the_AT interesting_JJ thing_NN1 is_VBZ that_CST researchers_NN2 has_VHZ started_VVN to_TO pay_VVI attention_NN1 to_II the_AT importance_NN1 and_CC value_NN1 of_IO brand_NN1 during_II the_AT last_MD 20_MC years_NNT2 ._. 
</s>
<s>
This_DD1 is_VBZ according_II21 to_II22 Keller_NP1 (_( 2003_MC )_) because_II21 of_II22 the_AT huge_JJ number_NN1 of_IO new_JJ products_NN2 and_CC services_NN2 that_CST forms_VVZ the_AT market_NN1 today_RT ._. 
</s>
<s>
If_CS a_AT1 company_NN1 wants_VVZ to_TO sell_VVI more_DAR products_NN2 than_CSN it_PPH1 's_VBZ competitors_NN2 it_PPH1 has_VHZ to_TO differentiate_VVI itself_PPX1 from_II other_JJ market_NN1 players_NN2 ,_, and_CC prove_VV0 the_AT to_II the_AT customer_NN1 that_CST the_AT offered_JJ products_NN2 or_CC services_NN2 somehow_RR different_JJ and_CC better_RRR than_CSN other_JJ companies_NN2 offerings_NN2 (_( King_NNB &;_NULL Grace_NP1 2007_MC )_) ._. 
</s>
<s>
2.2_MC How_RRQ do_VD0 you_PPY build_VVI up_RP a_AT1 brand_NN1 ?_? 
</s>
<s>
Because_CS the_AT relevance_NN1 of_IO brands_NN2 ,_, branding_VVG and_CC brand_NN1 measuring_NN1 has_VHZ become_VVN so_RG important_JJ to_II the_AT market_NN1 players_NN2 ,_, it_PPH1 has_VHZ also_RR been_VBN a_AT1 very_RG interesting_JJ research_NN1 area_NN1 for_IF researchers_NN2 ._. 
</s>
<s>
One_MC1 key-_JJ question_NN1 that_CST has_VHZ been_VBN discussed_VVN and_CC criticized_VVN by_II many_DA2 ,_, is_VBZ the_AT question_NN1 about_II who_PNQS is_VBZ the_AT person_NN1 or_CC institution_NN1 who_PNQS forms_VVZ the_AT brand_NN1 and_CC the_AT content_NN1 of_IO it_PPH1 ._. 
</s>
<s>
Is_VBZ it_PPH1 the_AT company_NN1 who_PNQS decides_VVZ what_DDQ the_AT brand_NN1 stands_VVZ for_IF ,_, or_CC is_VBZ it_PPH1 the_AT customers_NN2 ?_? 
</s>
<s>
Hkansson_NP1 (_( 2004_MC )_) ,_, whose_DDQGE theory_NN1 I_PPIS1 also_RR want_VV0 to_TO base_VVI this_DD1 research_NN1 on_RP ,_, indicates_VVZ that_CST the_AT customer_NN1 is_VBZ the_AT part_NN1 who_PNQS make_VV0 the_AT final_JJ decision_NN1 of_IO what_DDQ the_AT brand_NN1 is_VBZ standing_VVG for_IF ,_, and_CC how_RRQ they_PPHS2 evaluate_VV0 and_CC see_VV0 it_PPH1 compared_VVD to_II other_JJ brands_NN2 ._. 
</s>
<s>
This_DD1 also_RR what_DDQ Mrtensen_NP1 (_( 2009_MC )_) thinks_VVZ ,_, but_CCB she_PPHS1 also_RR indicates_VVZ that_CST the_AT company_NN1 has_VHZ the_AT possibility_NN1 to_II impact_NN1 on_II how_RRQ the_AT customer_NN1 do_VD0 the_AT final_JJ evaluation_NN1 ._. 
</s>
<s>
But_CCB how_RRQ is_VBZ this_DD1 done_VDN ?_? 
</s>
<s>
Mrtensen_NP1 (_( 2009_MC )_) ,_, Hkansson_NP1 (_( 2004_MC )_) and_CC many_DA2 other_JJ researchers_NN2 thinks_VVZ this_DD1 is_VBZ done_VDN by_II effective_JJ and_CC relevant_JJ marketing_NN1 methods_NN2 ,_, that_DD1 makes_VVZ the_AT product_NN1 or_CC service_VV0 relevant_JJ for_IF the_AT customer_NN1 ._. 
</s>
<s>
Hkansson_NP1 (_( 2004_MC )_) points_VVZ out_RP that_CST it_PPH1 is_VBZ also_RR the_AT customer_NN1 who_PNQS has_VHZ to_TO be_VBI used_VVN to_TO make_VVI the_AT measurement_NN1 of_IO the_AT strength_NN1 of_IO the_AT brand_NN1 ,_, which_DDQ mean_VV0 that_CST everything_PN1 that_CST has_VHZ to_TO do_VDI with_IW branding_NN1 starts_VVZ and_CC ends_VVZ with_IW the_AT customer_NN1 (_( Hkansson_NP1 2004_MC )_) ._. 
</s>
<s>
If_CS the_AT company_NN1 does_VDZ not_XX succeed_VVI in_II building_VVG up_RP a_AT1 relevant_JJ picture_NN1 of_IO the_AT brand_NN1 in_II the_AT head_NN1 of_IO the_AT customer_NN1 by_II a_AT1 relevant_JJ marketing_NN1 strategy_NN1 ,_, the_AT company_NN1 will_VM never_RR succeed_VVI in_II getting_VVG a_AT1 high_JJ brand_NN1 ranking_VVG from_II the_AT customers_NN2 ._. 
</s>
<s>
Keller_NP1 (_( 2003_MC )_) and_CC King_NN1 and_CC Grace_NP1 (_( 2007_MC )_) indicates_VVZ that_CST one_MC1 important_JJ thing_NN1 that_CST a_AT1 company_NN1 should_VM remember_VVI in_II the_AT branding_JJ process_NN1 ,_, is_VBZ that_DD1 customers_NN2 for_IF the_AT most_RRT want_VV0 to_TO associate_VVI themself_PPX1 with_IW brands_NN2 they_PPHS2 like_VV0 ._. 
</s>
<s>
One_MC1 good_JJ example_NN1 is_VBZ BMW_NP1 ,_, which_DDQ for_IF many_DA2 users_NN2 is_VBZ symbolizing_VVG something_PN1 more_DAR than_CSN just_RR a_AT1 car_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ an_AT1 driving_JJ experience_NN1 ,_, that_CST the_AT consumer_NN1 feel_VV0 that_CST he/she_PPHS1 can_VM not_XX get_VVI by_II driving_VVG another_DD1 car_NN1 ._. 
</s>
<s>
Rank_NN1 of_IO Mind_NN1 -_- A_AT1 model_NN1 to_TO measure_VVI a_AT1 brand_NN1 Rank_NN1 of_IO Mind_NN1 model_NN1 was_VBDZ founded_VVN by_II Hkansson_NP1 (_( 2004_MC )_) ,_, when_CS he_PPHS1 wrote_VVD the_AT book_NN1 `_" 'Det_NN1 missfrstdda_NN1 varumrket''_NN1 ._. 
</s>
<s>
The_AT key-factors_NN2 with_IW the_AT model_NN1 focuses_VVZ on_II question_NN1 that_CST the_AT company_NN1 has_VHZ to_TO ask_VVI it_PPH1 's_VBZ customers_NN2 ._. 
</s>
<s>
The_AT restriction_NN1 with_IW the_AT model_NN1 is_VBZ that_CST companies_NN2 does_VDZ not_XX always_RR have_VHI access_NN1 to_II the_AT information_NN1 that_CST the_AT model_NN1 requires_VVZ ,_, because_CS the_AT pictures_NN2 and_CC feelings_NN2 that_CST customers_NN2 form_VV0 about_II a_AT1 brand_NN1 in_II their_APPGE heads_NN2 ,_, may_VM sometimes_RT be_VBI so_RG deep_RR in_II their_APPGE minds_NN2 ,_, that_CST he_PPHS1 can_VM not_XX explain_VVI even_RR to_II himself_PPX1 ._. 
</s>
<s>
How_RRQ can_VM a_AT1 company_NN1 then_RT understand_VVI something_PN1 ,_, that_CST customers_NN2 can_VM not_XX explain_VVI for_IF himself_PPX1 ?_? 
</s>
<s>
This_DD1 is_VBZ why_RRQ the_AT model_NN1 is_VBZ not_XX used_VVN so_RG much_DA1 in_II practise_NN1 ._. 
</s>
<s>
The_AT Rank_NN1 of_IO Mind_NN1 model_NN1 measures_VVZ the_AT brand_NN1 based_VVN on_II attitudes_NN2 and_CC preferences_NN2 ,_, which_DDQ Hkansson_NP1 (_( 2004_MC )_) indicates_VVZ are_VBR the_AT main_JJ factor_NN1 that_CST a_AT1 brand_NN1 is_VBZ built_VVN up_RP on_II the_AT heads_NN2 of_IO the_AT customers_NN2 ._. 
</s>
<s>
The_AT Rank_NN1 of_IO Mind_NN1 model_NN1 gives_VVZ a_AT1 clear_JJ picture_NN1 to_II the_AT researcher_NN1 of_IO how_RRQ a_AT1 brand_NN1 is_VBZ penetrated_VVN in_II the_AT segment_NN1 group_NN1 who_PNQS uses_VVZ the_AT brand_NN1 ._. 
</s>
<s>
The_AT questions_NN2 asked_VVD from_II the_AT customer_NN1 concerns_VVZ the_AT following_JJ areas_NN2 :_: Question_NN1 of_IO Total_JJ Knowledge_NN1 -_- Which_DDQ mean_VV0 the_AT number/percent_FU of_IO people_NN in_II the_AT segment_NN1 group_NN1 who_PNQS know_VV0 about_II the_AT existence_NN1 of_IO the_AT brand_NN1 ._. 
</s>
<s>
Question_NN1 of_IO Spontaneous_JJ Knowledge_NN1 -_- Which_DDQ mean_VV0 the_AT number/percent_FU of_IO the_AT segment_NN1 group_NN1 who_PNQS mention_VV0 your_APPGE brand_NN1 spontaneously_RR ,_, when_CS you_PPY mention_VV0 the_AT branch_NN1 you_PPY are_VBR active_JJ within_RL ._. 
</s>
<s>
Question_NN1 Top_NN1 of_IO Mind_NN1 -_- Which_DDQ mean_VV0 the_AT number_NN1 of_IO people/percent_FU of_IO segment_NN1 group_NN1 who_PNQS mention_VV0 your_APPGE brand_NN1 first_MD of_IO all_DB the_AT brands_NN2 in_II the_AT same_DA branch_NN1 Question_NN1 of_IO Attitude_NN1 -_- Shows_VVZ the_AT number_NN1 of_IO how_RGQ many_DA2 of_IO the_AT segment_NN1 group_NN1 have_VH0 a_AT1 positive_JJ association_NN1 to_II your_APPGE brand_NN1 ._. 
</s>
<s>
Question_NN1 of_IO Short-list_NN1 -_- Shows_VVZ how_RGQ many_DA2 of_IO the_AT segment_NN1 group_NN1 actively_RR think_VV0 about_II choosing_VVG your_APPGE brand_NN1 Question_NN1 of_IO Preferences_NN2 -_- Shows_VVZ how_RGQ many_DA2 of_IO the_AT segment_NN1 group_NN1 who_PNQS would_VM choose_VVI your_APPGE brand_NN1 as_II the_AT first_MD alternative_NN1 from_II all_DB the_AT other_JJ brands_NN2 in_II the_AT branch_NN1 ._. 
</s>
<s>
Question_NN1 of_IO Loyalty_NN1 -_- How_RGQ many_DA2 of_IO the_AT segment_NN1 group_NN1 buy_VV0 products_NN2 from_II your_APPGE related_JJ to_II your_APPGE brand_NN1 ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) It_PPH1 is_VBZ important_JJ for_IF the_AT company_NN1 to_TO remember_VVI that_CST the_AT Rank_NN1 of_IO Mind_NN1 model_NN1 does_VDZ not_XX give_VVI any_DD information_NN1 about_II the_AT content_NN1 of_IO the_AT brand_NN1 ,_, it_PPH1 just_RR gives_VVZ an_AT1 overview_NN1 of_IO how_RGQ strong_JJ the_AT brand_NN1 is_VBZ ,_, which_DDQ mean_VV0 that_CST the_AT company_NN1 after_II doing_VDG this_DD1 research_NN1 should_VM continue_VVI researching_VVG in_II what_DDQ the_AT customer_NN1 specifically_RR see_VV0 as_RG positive_JJ and_CC negative_JJ aspects_NN2 in_II the_AT brand_NN1 ._. 
</s>
<s>
(_( Hkansson_NN1 2004_MC )_) 3_MC Methods_NN2 4_MC Results_NN2 5_MC Discussion_NN1 
</s>
