<s>
From_II Traditional_JJ Mobile_JJ Marketing_NN1 to_II Offering_VVG Mobile_JJ Services_NN2 a_AT1 Special_JJ Emphasis_NN1 on_II Intelligent_JJ SMS_NP1 1_MC1 ._. 
</s>
<s>
Introduction_NN1 SMS_NP1 (_( short_JJ message_NN1 service_NN1 )_) is_VBZ the_AT most_RGT popular_JJ application_NN1 of_IO mobile_JJ phone_NN1 services_NN2 showing_VVG a_AT1 very_RG high_JJ usage_NN1 with_IW an_AT1 estimated_JJ 5_MC billion_NNO text_NN1 messages_NN2 sent_VVN in_II 2010_MC globally_RR (_( Dickinger_NP1 ,_, Haghirian_JJ ,_, Murphy_NP1 and_CC Scharl_VV0 2004_MC ,_, MMA_NP1 2010_MC ,_, Murphy_NP1 and_CC Scharl_VV0 2004_MC )_) ._. 
</s>
<s>
Text_NN1 messaging_NN1 and_CC MMS_NNU2 (_( multimedia_NN messaging_VVG )_) marketing_NN1 are_VBR growing_VVG rapidly_RR ._. 
</s>
<s>
The_AT continuous_JJ technical_JJ innovations_NN2 ,_, high_JJ penetration_NN1 of_IO mobile_JJ phones_NN2 and_CC the_AT potential_NN1 of_IO this_DD1 marketing_NN1 channel_NN1 engage_VV0 its_APPGE popularity_NN1 (_( Gopal_NP1 and_CC Tripathi_NP1 2006_MC )_) ._. 
</s>
<s>
Mobile_JJ marketing_NN1 has_VHZ become_VVN one_MC1 of_IO the_AT most_RGT topical_JJ phenomena_NN2 in_II the_AT field_NN1 of_IO marketing_NN1 ._. 
</s>
<s>
This_DD1 relatively_RR new_JJ channel_NN1 which_DDQ utilizes_VVZ mobile_JJ phones_NN2 when_RRQ communicating_JJ companys_NN2 messages_NN2 to_TO target_VVI audiences_NN2 has_VHZ the_AT potential_JJ to_TO change_VVI the_AT entire_JJ marketing_NN1 process_NN1 (_( Haig_NP1 2002_MC )_) ._. 
</s>
<s>
Already_RR in_II the_AT early_JJ days_NNT2 of_IO mobile_JJ commerce_NN1 ,_, Kumar_NP1 and_CC Zahn_NP1 (_( 2002_MC )_) predicted_VVD that_CST mobile_JJ phones_NN2 would_VM become_VVI the_AT medium_NN1 for_IF improved_JJ business_NN1 operations_NN2 and_CC enhanced_JJ customer_NN1 satisfaction_NN1 ._. 
</s>
<s>
This_DD1 channel_NN1 is_VBZ said_VVN to_TO have_VHI good_JJ possibilities_NN2 of_IO becoming_VVG the_AT best-targeted_JJT advertising_NN1 channel_NN1 presenting_VVG new_JJ means_NN of_IO communication_NN1 compared_VVN with_IW the_AT traditional_JJ channels_NN2 such_II21 as_II22 television_NN1 or_CC mail_NN1 (_( Leppniemi_NP1 and_CC Karjaluoto_NP1 2005_MC )_) ._. 
</s>
<s>
1.1_MC ._. 
</s>
<s>
Research_NN1 Question_NN1 A_ZZ1 considerable_JJ amount_NN1 of_IO literature_NN1 has_VHZ been_VBN published_VVN about_II mobile_JJ marketing_NN1 and_CC the_AT common_JJ viewpoint_NN1 seems_VVZ to_TO be_VBI supportive_JJ ._. 
</s>
<s>
Several_DA2 scholars_NN2 tout_VV0 the_AT promises_NN2 of_IO this_DD1 ubiquitous_JJ phenomenon_NN1 ._. 
</s>
<s>
Barnes_NP1 and_CC Scornavacca_NP1 (_( 2004_MC )_) even_RR predict_VV0 that_CST in_II the_AT near_JJ future_NN1 ,_, mobile_JJ marketing_NN1 will_VM become_VVI as_RG common_JJ a_AT1 marketing_NN1 medium_NN1 as_II the_AT television_NN1 or_CC the_AT newspaper_NN1 ._. 
</s>
<s>
This_DD1 has_VHZ nevertheless_RR not_XX happened_VVN quite_RR as_CSA predicted_VVN ;_; despite_II the_AT high_JJ penetration_NN1 of_IO mobile_JJ devices_NN2 and_CC the_AT huge_JJ potential_NN1 of_IO this_DD1 channel_NN1 ,_, mobile_JJ marketing_NN1 can_VM not_XX be_VBI said_VVN to_II blossom_NN1 ,_, at_RR21 least_RR22 not_XX today_RT ._. 
</s>
<s>
Due_II21 to_II22 the_AT past_NN1 and_CC ongoing_JJ research_NN1 ,_, plenty_PN of_IO information_NN1 has_VHZ already_RR been_VBN gathered_VVN on_II this_DD1 marketing_NN1 channel_NN1 ._. 
</s>
<s>
Many_DA2 scholars_NN2 highlight_VV0 the_AT mushrooming_NN1 of_IO the_AT phenomenon_NN1 ,_, (_( Barwise_NP1 and_CC Strong_JJ 2002_MC ,_, Gopal_NP1 and_CC Tripathi_NP1 2006_MC ,_, Leppniemi_NP1 and_CC Karjaluoto_NP1 2005_MC )_) ,_, whereas_CS some_DD focus_NN1 on_II the_AT issues_NN2 of_IO permission_NN1 and_CC acceptance_NN1 (_( Barnes_NP1 and_CC Scornavacca_NP1 ,_, 2004_MC ,_, Heinonen_NP1 and_CC Strandvik_NP1 ,_, 2007_MC )_) ._. 
</s>
<s>
Furthermore_RR ,_, there_EX are_VBR some_DD theories_NN2 and_CC conceptual_JJ models_NN2 on_II how_RGQ mobile_JJ marketing_NN1 campaigns_NN2 should_VM be_VBI implemented_VVN (_( Dickinger_NP1 ,_, Haghirian_JJ ,_, Murphy_NP1 and_CC Scharl_VV0 2004_MC ,_, Leppniemi_NP1 and_CC Karjaluoto_NP1 2005_MC )_) ._. 
</s>
<s>
A_AT1 great_JJ proportion_NN1 of_IO studies_NN2 adopts_VVZ a_AT1 company_NN1 perspective_NN1 and_CC concentrates_VVZ on_II the_AT several_DA2 marketer_NN1 benefits_NN2 of_IO mobile_JJ marketing_NN1 ._. 
</s>
<s>
However_RR ,_, there_EX is_VBZ less_DAR research_NN1 adopting_VVG a_AT1 consumer_NN1 perspective_NN1 investigating_VVG the_AT opinions_NN2 of_IO consumers_NN2 towards_II this_DD1 marketing_NN1 medium_NN1 ._. 
</s>
<s>
Therefore_RR ,_, mobile_JJ marketing_NN1 could_VM be_VBI argued_VVN to_TO be_VBI on_II a_AT1 theoretical_JJ ,_, rather_CS21 than_CS22 on_II a_AT1 practical_JJ level_NN1 ._. 
</s>
<s>
(_( Constantiou_NN1 ,_, Damsgaard_NP1 and_CC Knutsen_NP1 2006_MC )_) It_PPH1 is_VBZ however_RR becoming_VVG increasingly_RR significant_JJ to_TO take_VVI the_AT consumer_NN1 viewpoint_NN1 when_CS studying_VVG this_DD1 marketing_NN1 activity_NN1 ,_, consumers_NN2 after_II all_DB have_VH0 the_AT final_JJ word_NN1 on_II whether_CSW this_DD1 marketing_NN1 channel_NN1 will_VM succeed_VVI in_II the_AT long_JJ run_NN1 ._. 
</s>
<s>
This_DD1 paper_NN1 starts_VVZ from_II the_AT premise_NN1 that_CST a_AT1 certain_JJ transition_NN1 is_VBZ occurring_VVG from_II the_AT more_RGR traditional_JJ mobile_JJ marketing_NN1 to_II a_AT1 more_RGR recent_JJ and_CC fresh_JJ approach_NN1 of_IO offering_VVG mobile_JJ services_NN2 ._. 
</s>
<s>
The_AT emerging_JJ transition_NN1 is_VBZ believed_VVN to_TO be_VBI in_II consequence_NN1 of_IO the_AT changing_JJ role_NN1 of_IO todays_NN2 consumers_NN2 ,_, who_PNQS have_VH0 more_DAR information_NN1 ,_, greater_JJR access_NN1 to_II the_AT existing_JJ possibilities_NN2 and_CC a_AT1 bigger_JJR role_NN1 in_II value_NN1 creation_NN1 (_( Prahalad_NP1 and_CC Ramaswamy_NP1 2004_MC )_) ._. 
</s>
<s>
This_DD1 indicates_VVZ that_CST as_II a_AT1 result_NN1 ,_, consumers_NN2 also_RR have_VH0 growing_JJ expectations_NN2 from_II companies_NN2 ,_, which_DDQ further_RRR requires_VVZ these_DD2 companies_NN2 to_TO fulfil_VVI ,_, or_CC even_RR surpass_VVI these_DD2 expectations_NN2 by_II offering_VVG ever_RR more_RGR innovative_JJ solutions_NN2 ._. 
</s>
<s>
With_IW services_NN2 ,_, this_DD1 paper_NN1 refers_VVZ to_II pure_JJ services_NN2 on_II the_AT basis_NN1 of_IO consumers_NN2 needs_VVZ ,_, not_XX merely_RR services_NN2 ,_, such_II21 as_II22 ordering_NN1 and_CC paying_VVG for_IF products_NN2 from_II vending_VVG machines_NN2 via_II mobile_JJ phones_NN2 ._. 
</s>
<s>
Whereas_CS mobile_JJ marketing_NN1 ,_, as_CSA already_RR mentioned_VVN ,_, has_VHZ been_VBN a_AT1 widely_RR researched_VVN field_NN1 ,_, offering_VVG services_NN2 through_II mobile_JJ phones_NN2 on_II the_AT other_JJ hand_NN1 ,_, is_VBZ a_AT1 rather_RR un-researched_VVN field_NN1 as_CSA it_PPH1 is_VBZ a_AT1 relatively_RR new_JJ phenomenon_NN1 ._. 
</s>
<s>
Thus_RR ,_, in_II the_AT absence_NN1 of_IO previous_JJ academic_JJ studies_NN2 ,_, it_PPH1 offers_VVZ a_AT1 niche_NN1 for_IF further_JJR investigation_NN1 ._. 
</s>
<s>
The_AT special_JJ emphasis_NN1 of_IO this_DD1 paper_NN1 lies_VVZ in_II intelligent_JJ SMS_NP1 (_( hereafter_RT referred_VVN to_II as_CSA iSMS_NN2 )_) solution_NN1 created_VVN by_II BookIT_NN1 Oy_UH ,_, a_AT1 software_NN1 and_CC services_NN2 company_NN1 specialized_VVN in_II mobile_JJ business_NN1 services_NN2 and_CC applications_NN2 technologies_NN2 ._. 
</s>
<s>
The_AT iSMS_NN2 is_VBZ an_AT1 interactive_JJ version_NN1 of_IO the_AT standard_JJ SMS_NP1 which_DDQ enhances_VVZ two-way_JJ dialogues_NN2 between_II the_AT sender_NN1 ,_, e.g._REX organization_NN1 or_CC telecom_VV0 service_NN1 provider_NN1 and_CC the_AT end-user_NN1 ,_, e.g._REX consumer_NN1 ._. 
</s>
<s>
(_( BookIT_NP1 )_) The_AT iSMS_NN2 is_VBZ chosen_VVN as_II the_AT target_NN1 of_IO investigation_NN1 since_CS as_II a_AT1 new_JJ and_CC innovative_JJ application_NN1 applying_VVG a_AT1 more_RGR service-oriented_JJ view_NN1 to_II SMS_NP1 marketing_NN1 ,_, it_PPH1 is_VBZ believed_VVN to_TO represent_VVI the_AT more_RGR recent_JJ approach_NN1 of_IO offering_VVG mobile_JJ services_NN2 and_CC embody_VV0 the_AT advantages_NN2 of_IO this_DD1 marketing_NN1 activity_NN1 ._. 
</s>
<s>
1.2_MC ._. 
</s>
<s>
Aim_NN1 of_IO the_AT paper_NN1 This_DD1 paper_NN1 discusses_VVZ a_AT1 somewhat_RR new_JJ phenomenon_NN1 of_IO offering_VVG services_NN2 through_II mobile_JJ phones_NN2 ._. 
</s>
<s>
The_AT purpose_NN1 of_IO this_DD1 paper_NN1 is_VBZ to_TO consider_VVI the_AT end-users_NN2 perceptions_NN2 towards_II mobile_JJ services_NN2 ,_, in_II the_AT form_NN1 of_IO text_NN1 messages_NN2 delivered_VVN to_II their_APPGE mobile_JJ phones_NN2 ._. 
</s>
<s>
The_AT paper_NN1 further_RRR adopts_VVZ a_AT1 pure_JJ and_CC comprehensive_JJ consumer_NN1 standpoint_NN1 and_CC therefore_RR contributes_VVZ to_II the_AT knowledge_NN1 of_IO the_AT end-user_NN1 perceptions_NN2 of_IO the_AT phenomenon_NN1 ,_, which_DDQ this_DD1 paper_NN1 argues_VVZ to_TO be_VBI the_AT most_RGT significant_JJ factor_NN1 in_II the_AT success_NN1 of_IO mobile_JJ marketing_NN1 ._. 
</s>
<s>
1.3_MC ._. 
</s>
<s>
Structure_NN1 of_IO the_AT paper_NN1 The_AT theoretical_JJ discussion_NN1 of_IO this_DD1 paper_NN1 is_VBZ divided_VVN into_II two_MC main_JJ parts_NN2 ;_; the_AT transition_NN1 of_IO the_AT approaches_NN2 and_CC the_AT main_JJ characteristics_NN2 of_IO iSMS_NN2 ._. 
</s>
<s>
The_AT first_MD main_JJ part_NN1 ,_, Chapter_NN1 2_MC consists_VVZ of_IO a_AT1 brief_JJ overview_NN1 of_IO the_AT traditional_JJ mobile_JJ marketing_NN1 which_DDQ is_VBZ followed_VVN by_II a_AT1 discussion_NN1 about_II the_AT more_RGR recent_JJ and_CC fresh_JJ approach_NN1 of_IO offering_VVG mobile_JJ services_NN2 ._. 
</s>
<s>
The_AT second_MD main_JJ part_NN1 ,_, Chapter_NN1 3_MC tackles_VVZ the_AT main_JJ characteristics_NN2 of_IO iSMS_NN2 ,_, which_DDQ this_DD1 paper_NN1 suggests_VVZ to_TO be_VBI interactivity_NN1 ,_, privacy_NN1 &;_NULL relevance_NN1 ,_, convenience_NN1 and_CC value_NN1 perspective_NN1 ._. 
</s>
<s>
Before_II moving_VVG on_RP to_II the_AT theoretical_JJ discussion_NN1 of_IO the_AT paper_NN1 ,_, the_AT Figure_NN1 1_MC1 is_VBZ presented_VVN to_TO capture_VVI and_CC remind_VVI about_II the_AT most_RGT significant_JJ motivations_NN2 and_CC goals_NN2 for_IF this_DD1 paper_NN1 ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) 2_MC ._. 
</s>
<s>
The_AT transition_NN1 of_IO the_AT approaches_NN2 As_CSA already_RR mentioned_VVN ,_, the_AT transition_NN1 is_VBZ believed_VVN to_TO have_VHI taken_VVN place_NN1 due_II21 to_II22 the_AT ever_RR growing_JJ expectations_NN2 of_IO todays_NN2 consumers_NN2 and_CC the_AT resulting_JJ pressure_NN1 for_IF change_NN1 from_II the_AT company_NN1 perspective_NN1 ._. 
</s>
<s>
Furthermore_RR ,_, the_AT transition_NN1 from_II the_AT traditional_JJ mobile_JJ marketing_NN1 to_II offering_VVG mobile_JJ services_NN2 could_VM be_VBI said_VVN to_TO follow_VVI the_AT paradigm_NN1 shift_NN1 taken_VVN place_NN1 in_II the_AT field_NN1 of_IO marketing_NN1 ,_, which_DDQ emphasises_VVZ services_NN2 over_II product-orientation_NN1 (_( Grnroos_NP1 2007_MC ,_, Vargo_NP1 and_CC Lusch_NP1 2004_MC )_) ._. 
</s>
<s>
The_AT following_JJ chapters_NN2 discuss_VV0 first_MD the_AT traditional_JJ view_NN1 and_CC then_RT cover_VV0 the_AT more_RGR recent_JJ approach_NN1 of_IO offering_VVG mobile_JJ services_NN2 ._. 
</s>
<s>
The_AT chapter_NN1 ends_VVZ with_IW a_AT1 more_RGR detailed_JJ description_NN1 of_IO intelligent_JJ SMS_NP1 services_NN2 ._. 
</s>
<s>
2.1_MC ._. 
</s>
<s>
Traditional_JJ mobile_JJ marketing_NN1 Traditional_JJ mobile_JJ marketing_NN1 can_VM be_VBI argued_VVN to_TO be_VBI marketer-oriented_JJ in_II a_AT1 sense_NN1 that_CST it_PPH1 is_VBZ promotional_JJ in_II nature_NN1 (_( Balasubramanian_JJ ,_, Peterson_NP1 and_CC Jrvenp_VV0 2002_MC ,_, Dickinger_NP1 and_CC Haghirian_JJ 2004_MC )_) and_CC offers_NN2 consumers_NN2 monetary_JJ benefits_NN2 in_II the_AT form_NN1 of_IO e.g._REX coupons_NN2 or_CC campaigns_NN2 (_( The_AT Finnish_JJ Direct_JJ Marketing_NN1 Association_NN1 2009_MC )_) ,_, such_II21 as_II22 coupons_NN2 entitling_VVG to_II a_AT1 free_JJ t-shirt_NN1 or_CC a_AT1 campaign_NN1 offering_VVG concessionary_JJ fares_NN2 on_II new_JJ mobile_JJ phone_NN1 models_NN2 ._. 
</s>
<s>
The_AT traditional_JJ mobile_JJ marketing_NN1 can_VM be_VBI claimed_VVN to_II marketer-oriented_JJ also_RR in_II a_AT1 sense_NN1 that_CST the_AT messages_NN2 are_VBR general_JJ as_II31 well_II32 as_II33 offering-oriented_JJ ._. 
</s>
<s>
General_NN1 ,_, since_CS the_AT messages_NN2 are_VBR not_XX directed_VVN to_II a_AT1 specific_JJ consumer_NN1 ,_, but_CCB instead_RR are_VBR typically_RR addressed_VVN to_II a_AT1 wider_JJR audience_NN1 ._. 
</s>
<s>
Offering-oriented_JJ ,_, since_CS the_AT messages_NN2 typically_RR promote_VV0 a_AT1 certain_JJ good_JJ or_CC a_AT1 service_NN1 encouraging_VVG the_AT consumers_NN2 to_TO try_VVI a_AT1 particular_JJ offering_NN1 ._. 
</s>
<s>
These_DD2 general_JJ and_CC offering-oriented_JJ messages_NN2 however_RR might_VM not_XX be_VBI relevant_JJ enough_RR to_II the_AT consumers_NN2 situation_NN1 and_CC may_VM fail_VVI to_TO meet_VVI the_AT consumer_NN1 requirements_NN2 of_IO value_NN1 adding_VVG information_NN1 and_CC high_JJ relevance_NN1 ._. 
</s>
<s>
For_IF these_DD2 reasons_NN2 ,_, the_AT common_JJ reaction_NN1 to_II mobile_JJ marketing_NN1 is_VBZ believed_VVN to_TO remain_VVI one_MC1 of_IO aggravating._NNU 2.2_MC ._. 
</s>
<s>
Offering_VVG mobile_JJ services_NN2 Offering_VVG mobile_JJ services_NN2 ,_, on_II the_AT other_JJ hand_NN1 could_VM be_VBI claimed_VVN to_TO be_VBI consumer-oriented_JJ in_II a_AT1 sense_NN1 that_CST it_PPH1 relates_VVZ to_II consumers_NN2 situations_NN2 through_II messages_NN2 which_DDQ are_VBR consumer-specific_JJ and_CC delivered_VVN to_II them_PPHO2 under_II certain_JJ circumstances_NN2 ._. 
</s>
<s>
As_II an_AT1 example_NN1 of_IO these_DD2 services_NN2 can_VM be_VBI mentioned_VVN the_AT check-in_NN1 service_NN1 through_II mobile_JJ phones_NN2 as_II an_AT1 intelligent_JJ SMS_NP1 (_( iSMS_NN2 )_) offered_VVD by_II Finnair_NP1 (_( a_AT1 Finnish_JJ airline_NN1 )_) ._. 
</s>
<s>
Hence_RR ,_, the_AT service_NN1 in_II the_AT form_NN1 of_IO iSMS_NN2 has_VHZ the_AT potential_NN1 of_IO meeting_VVG the_AT relevance_NN1 requirements_NN2 set_VVN by_II consumers_NN2 ._. 
</s>
<s>
Furthermore_RR ,_, instead_II21 of_II22 offering_VVG monetary_JJ benefits_NN2 ,_, iSMS_NN2 offers_VVZ consumers_NN2 benefits_NN2 in_II another_DD1 form_NN1 ,_, e.g._REX saving_NN1 consumers_NN2 time_NNT1 or_CC effort_NN1 ;_; a_AT1 benefit_NN1 which_DDQ might_VM be_VBI regarded_VVN more_RGR valuable_JJ than_CSN a_AT1 price_NN1 reduction_NN1 ._. 
</s>
<s>
2.3_MC ._. 
</s>
<s>
Intelligent_JJ SMS_NP1 services_NN2 Intelligent_JJ SMS_NP1 ,_, according_II21 to_II22 the_AT developer_NN1 of_IO the_AT application_NN1 BookIT_NN1 Oy_UH ,_, is_VBZ a_AT1 unique_JJ mobile_JJ transaction_NN1 technology_NN1 ,_, which_DDQ provides_VVZ organisations_NN2 with_IW secure_JJ contacts_NN2 with_IW their_APPGE customers_NN2 (_( BookIT_NP1 )_) ._. 
</s>
<s>
Intelligent_JJ SMS_NP1 is_VBZ one_MC1 of_IO the_AT innovative_JJ solutions_NN2 in_II the_AT dynamic_JJ field_NN1 of_IO mobile_JJ marketing_NN1 and_CC it_PPH1 differs_VVZ from_II the_AT traditional_JJ SMS_NP1 in_II various_JJ ways_NN2 ._. 
</s>
<s>
The_AT description_NN1 of_IO the_AT application_NN1 provided_VVN by_II BookIT_NN1 Oy_UH has_VHZ the_AT following_JJ indications_NN2 discussed_VVN in_II the_AT next_MD chapter_NN1 ._. 
</s>
<s>
The_AT first_MD difference_NN1 compared_VVN to_II traditional_JJ SMS_NP1 is_VBZ that_CST iSMS_NN2 is_VBZ consumer-specific_JJ in_II a_AT1 sense_NN1 that_CST it_PPH1 is_VBZ delivered_VVN to_II a_AT1 particular_JJ end-user_NN1 under_II certain_JJ circumstances_NN2 enabled_VVN by_II user_NN1 authentication_NN1 (_( BookIT_NP1 )_) ._. 
</s>
<s>
These_DD2 circumstances_NN2 refer_VV0 to_II consumers_NN2 situation-related_JJ needs_NN2 ._. 
</s>
<s>
This_DD1 has_VHZ several_DA2 implications_NN2 ._. 
</s>
<s>
If_CS a_AT1 company_NN1 is_VBZ not_XX automatically_RR informed_VVN about_II the_AT consumers_NN2 needs_NN2 of_IO certain_JJ services_NN2 (_( as_CSA supposed_JJ to_TO the_AT Finnairs_NP1 check-in_NN1 service_NN1 ,_, where_CS the_AT consumer_NN1 communicates_VVZ the_AT need_NN1 by_II booking_VVG a_AT1 flight_NN1 )_) ,_, applying_VVG the_AT application_NN1 requires_VVZ keeping_VVG and_CC maintaining_VVG a_AT1 customer_NN1 data_NN base_NN1 and_CC using_VVG it_PPH1 to_TO deliver_VVI iSMS_NN2 messages_NN2 to_II consumers_NN2 at_II proper_JJ occasions_NN2 ,_, i.e._REX when_CS the_AT service_NN1 is_VBZ relevant_JJ to_II the_AT consumers_NN2 needs_VVZ ._. 
</s>
<s>
On_II one_MC1 hand_NN1 ,_, when_CS this_DD1 is_VBZ done_VDN correctly_RR the_AT message_NN1 received_VVN by_II the_AT consumer_NN1 is_VBZ highly_RR relevant_JJ to_II his_APPGE situation_NN1 and_CC therefore_RR potentially_RR perceived_VVN favourably_RR ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 ,_, from_II a_AT1 service_NN1 provider-perspective_NN1 ,_, this_DD1 has_VHZ some_DD challenges_NN2 as_RR21 well_RR22 ;_; iSMS_NN2 is_VBZ not_XX applicable_JJ in_II every_AT1 circumstance_NN1 ._. 
</s>
<s>
Intelligent_JJ SMS_NP1 are_VBR not_XX sent_VVN at_II any_DD chosen_JJ moment_NN1 to_II a_AT1 wider_JJR audience_NN1 ._. 
</s>
<s>
Therefore_RR ,_, the_AT use_NN1 of_IO iSMS_NN2 is_VBZ limited_VVN to_II certain_JJ circumstances_NN2 only_RR ._. 
</s>
<s>
The_AT orientation_NN1 to_II the_AT consumers_NN2 situation_NN1 has_VHZ certain_JJ benefits_NN2 contributing_VVG to_II a_AT1 second_MD difference_NN1 ;_; besides_II the_AT fact_NN1 that_CST the_AT message_NN1 might_VM be_VBI perceived_VVN more_RGR relevant_JJ ,_, it_PPH1 also_RR has_VHZ the_AT potential_JJ to_TO be_VBI regarded_VVN more_RGR value-adding_JJ ._. 
</s>
<s>
Different_JJ situations_NN2 faced_VVN by_II consumers_NN2 tend_VV0 to_TO raise_VVI equally_RR differing_JJ needs_NN2 depending_II21 on_II22 the_AT specific_JJ situation_NN1 at_II hand_NN1 and_CC meeting_VVG the_AT consumers_NN2 particular_JJ needs_NN2 adds_VVZ value_NN1 for_IF the_AT consumers_NN2 ._. 
</s>
<s>
(_( Grnroos_NP1 2007_MC :_: 360_MC )_) ._. 
</s>
<s>
A_AT1 third_MD main_JJ difference_NN1 is_VBZ that_CST the_AT characteristics_NN2 of_IO the_AT application_NN1 allow_VV0 answering_VVG the_AT message_NN1 merely_RR by_II responding_VVG to_II the_AT delivered_JJ message_NN1 and_CC thus_RR do_VD0 not_XX expect_VVI any_DD additional_JJ activities_NN2 from_II the_AT respondent_NN1 ._. 
</s>
<s>
This_DD1 and_CC other_JJ characteristics_NN2 are_VBR elaborated_VVN further_JJR later_RRR in_II this_DD1 paper_NN1 ._. 
</s>
<s>
Considering_CS the_AT description_NN1 of_IO the_AT application_NN1 by_II BookIT_NN1 Oy_UH ,_, this_DD1 paper_NN1 suggests_VVZ that_CST for_IF the_AT end-user_NN1 of_IO the_AT solution_NN1 ,_, the_AT main_JJ characteristics_NN2 of_IO iSMS_NN2 are_VBR the_AT following_JJ :_: interactive_JJ feature_NN1 of_IO the_AT message_NN1 in_II a_AT1 way_NN1 that_CST the_AT iSMS_NN2 suggests_VVZ the_AT consumer_NN1 to_TO consider_VVI his_APPGE opinion_NN1 or_CC situation_NN1 and_CC respond_VVI to_II the_AT message_NN1 according_II21 to_II22 the_AT consumers_NN2 wishes_VVZ ._. 
</s>
<s>
private_JJ nature_NN1 combined_VVN with_IW the_AT high_JJ relevance_NN1 of_IO the_AT message_NN1 enabled_VVN by_II the_AT authentication_NN1 technology_NN1 and_CC driven_VVN by_II the_AT consumer-specific_JJ situation_NN1 ._. 
</s>
<s>
the_AT ease_NN1 of_IO use_NN1 when_CS responding_VVG to_II the_AT message_NN1 and_CC finally_RR ,_, and_CC perhaps_RR most_RGT importantly_RR :_: the_AT perceived_JJ benefit_NN1 or_CC value_NN1 of_IO the_AT message_NN1 content_NN1 for_IF the_AT consumer_NN1 considering_CS21 that_CS22 iSMS_NN2 is_VBZ designed_VVN to_TO tackle_VVI particular_JJ situations_NN2 ,_, and_CC these_DD2 situations_NN2 are_VBR directly_RR connected_VVN to_II particular_JJ consumer_NN1 needs_NN2 ._. 
</s>
<s>
In_II the_AT following_JJ chapters_NN2 ,_, the_AT above_JJ mentioned_VVD main_JJ characteristics_NN2 are_VBR covered_VVN more_RRR in_II detail_NN1 ._. 
</s>
<s>
3_MC ._. 
</s>
<s>
Main_JJ characteristics_NN2 of_IO iSMS_NN2 Besides_II the_AT description_NN1 of_IO the_AT application_NN1 provided_VVN by_II BookIT_NN1 Oy_UH ,_, the_AT main_JJ characteristics_NN2 epitomising_VVG this_DD1 application_NN1 for_IF the_AT consumers_NN2 ;_; interactivity_NN1 ,_, privacy_NN1 &;_NULL relevance_NN1 ,_, ease_NN1 of_IO use_NN1 as_II31 well_II32 as_II33 value-in-use_NN1 are_VBR supported_VVN by_II the_AT review_NN1 of_IO previous_JJ studies_NN2 in_II the_AT field_NN1 of_IO mobile_JJ marketing_NN1 ._. 
</s>
<s>
These_DD2 concepts_NN2 are_VBR furthermore_RR chosen_VVN for_IF a_AT1 more_RGR detailed_JJ investigation_NN1 due_II21 to_II22 their_APPGE consumer-oriented_JJ nature_NN1 ._. 
</s>
<s>
In_II the_AT following_JJ sections_NN2 ,_, a_AT1 detailed_JJ discussion_NN1 of_IO each_DD1 of_IO the_AT concepts_NN2 is_VBZ presented_VVN ._. 
</s>
<s>
3.1_MC ._. 
</s>
<s>
Privacy_NN1 and_CC Relevance_NN1 There_EX is_VBZ a_AT1 large_JJ volume_NN1 of_IO published_JJ studies_NN2 describing_VVG the_AT role_NN1 of_IO privacy_NN1 and_CC relevance_NN1 in_II mobile_JJ marketing_NN1 (_( Barnes_NP1 and_CC Scornavacca_NP1 2004_MC ,_, Constantiou_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2006_MC )_) up_II21 to_II22 the_AT extent_NN1 that_CST they_PPHS2 could_VM be_VBI argued_VVN to_TO be_VBI prerequisites_NN2 ,_, rather_II21 than_II22 contributors_NN2 ,_, to_II mobile_JJ marketing_NN1 (_( Anckar_NP1 and_CC Dincau_NP1 2002_MC )_) ._. 
</s>
<s>
For_RR41 the_RR42 most_RR43 part_RR44 ,_, the_AT previous_JJ studies_NN2 discuss_VV0 the_AT issues_NN2 related_VVN to_II these_DD2 concepts_NN2 interchangeably_RR due_II21 to_II22 their_APPGE close_JJ connections_NN2 and_CC similarly_RR this_DD1 paper_NN1 joins_VVZ the_AT concepts_NN2 together_RL and_CC discusses_VVZ them_PPHO2 under_RG one_MC1 heading_NN1 ._. 
</s>
<s>
Both_RR ,_, privacy_NN1 and_CC relevance_NN1 are_VBR claimed_VVN to_TO have_VHI a_AT1 significant_JJ impact_NN1 on_II perceptions_NN2 ,_, effectiveness_NN1 ,_, success_NN1 and_CC acceptance_NN1 of_IO mobile_JJ marketing_NN1 ._. 
</s>
<s>
(_( Barnes_NP1 and_CC Scornavacca_NP1 2004_MC ,_, Barwise_NP1 and_CC Strong_JJ 2002_MC ,_, Constantiou_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2006_MC ,_, Heinonen_NP1 and_CC Strandvik_NP1 2007_MC ,_, Leppniemi_NP1 and_CC Karjaluoto_NP1 2005_MC ,_, among_II others_NN2 )_) The_AT salience_NN1 of_IO these_DD2 constructs_NN2 can_VM be_VBI explained_VVN by_II the_AT very_RG personal_JJ and_CC intimate_JJ nature_NN1 of_IO mobile_JJ phones_NN2 ;_; just_RR as_CSA Heinonen_NP1 and_CC Strandvik_NP1 (_( 2007_MC )_) reminds_VVZ ;_; commercial_JJ messages_NN2 are_VBR benchmarked_VVN against_II private_JJ messages_NN2 ,_, which_DDQ are_VBR naturally_RR both_RR private_JJ and_CC relevant_JJ ._. 
</s>
<s>
Moreover_RR ,_, abundance_NN1 of_IO research_NN1 has_VHZ been_VBN conducted_VVN on_II the_AT topic_NN1 of_IO permission_NN1 (_( Barnes_NP1 and_CC Scornavacca_NP1 2004_MC ,_, Barwise_NP1 and_CC Strong_JJ 2002_MC ,_, Kavassalis_NP1 ,_, Spyropoulou_NP1 ,_, Drossos_NP1 ,_, Mitrokostas_NP2 ,_, Gikas_NP2 and_CC Hatzistamatiou_NP1 2003_MC )_) ._. 
</s>
<s>
On_II one_MC1 hand_NN1 consensus_NN1 seems_VVZ to_TO have_VHI been_VBN reached_VVN on_II the_AT positive_JJ influence_NN1 of_IO clear_JJ instructions_NN2 for_IF opting-in_NN1 ,_, and_CC out_RP from_II a_AT1 service_NN1 ,_, trusting_VVG the_AT sender_NN1 as_II31 well_II32 as_II33 the_AT negative_JJ impact_NN1 of_IO sending_VVG unsolicited_JJ messages_NN2 ,_, i.e._REX spam_NN1 (_( Leppniemi_NP1 and_CC Karjaluoto_NP1 2005_MC ,_, Gopal_NP1 and_CC Tripathi_NP1 2006_MC ,_, Dickinger_NP1 and_CC Haghirian_JJ 2004_MC )_) ,_, on_II the_AT other_JJ hand_NN1 ,_, some_DD difference_NN1 seems_VVZ to_TO have_VHI remained_VVN on_II the_AT impact_NN1 of_IO permission_NN1 ._. 
</s>
<s>
Some_DD scholars_NN2 praise_VV0 permission_NN1 for_IF being_VBG the_AT key_JJ factor_NN1 in_II mobile_JJ marketing_NN1 enabling_VVG acceptance_NN1 and_CC satisfaction_NN1 (_( Barnes_NP1 and_CC Scornavacca_NP1 ,_, 2004_MC ,_, Barwise_NP1 and_CC Strong_JJ ,_, 2002_MC )_) whereas_CS others_NN2 (_( Heinonen_NP1 and_CC Strandvik_NP1 ,_, 2007_MC )_) have_VH0 some_DD reservations_NN2 stating_VVG that_CST although_CS beneficial_JJ ,_, permission_NN1 does_VDZ not_XX guarantee_VVI consumers_NN2 paying_VVG attention_NN1 to_II mobile_JJ marketing_NN1 messages_NN2 ._. 
</s>
<s>
This_DD1 paper_NN1 suggests_VVZ that_DD1 relevance_NN1 as_CSA mobile_JJ service_NN1 element_NN1 is_VBZ even_RR more_RGR pivotal_JJ than_CSN privacy_NN1 ._. 
</s>
<s>
One_MC1 of_IO the_AT biggest_JJT challenges_NN2 faced_VVN by_II marketers_NN2 is_VBZ how_RRQ to_TO ensure_VVI the_AT relevance_NN1 of_IO marketing_NN1 messages_NN2 to_II various_JJ consumers_NN2 (_( Jelassi_NP1 and_CC Enders_NN2 2004_MC )_) ,_, after_II all_DB relevance_NN1 is_VBZ consumer_NN1 specific_JJ ;_; what_DDQ is_VBZ relevant_JJ to_II one_PN1 is_VBZ most_RGT likely_JJ irrelevant_JJ to_II another_DD1 (_( Heinonen_NP1 and_CC Strandvik_NP1 2005_MC )_) ._. 
</s>
<s>
If_CS a_AT1 message_NN1 delivered_VVN to_II a_AT1 mobile_JJ phone_NN1 is_VBZ in_II fact_NN1 not_XX relevant_JJ to_II the_AT consumer_NN1 or_CC his_APPGE situation_NN1 ,_, it_PPH1 will_VM most_RGT likely_RR be_VBI ignored_VVN (_( Godin_NP1 2001_MC )_) ._. 
</s>
<s>
In_II a_AT1 similar_JJ vein_NN1 ,_, privacy_NN1 and_CC relevance_NN1 are_VBR immanent_JJ in_II iSMS_NN2 service_VV0 ;_; privacy_NN1 due_II21 to_II22 the_AT foundational_JJ technology_NN1 enabling_VVG end-user_NN1 recognition_NN1 ,_, i.e._REX DDM_NP1 authentication_NN1 ,_, and_CC relevance_NN1 in_II consequence_NN1 of_IO what_DDQ Anckar_VV0 and_CC DIncau_NP1 (_( 2002_MC )_) refer_VV0 to_II time-critical_JJ needs_NN2 and_CC arrangements_NN2 when_CS identifying_VVG different_JJ settings_NN2 in_II which_DDQ mobile_JJ services_NN2 can_VM provide_VVI value_NN1 for_IF consumers_NN2 ._. 
</s>
<s>
Instead_II21 of_II22 using_VVG the_AT term_NN1 time-critical_JJ needs_NN2 and_CC arrangements_NN2 ,_, this_DD1 paper_NN1 uses_VVZ the_AT expression_NN1 situation-related_NN1 needs_VVZ as_CSA it_PPH1 is_VBZ more_RGR appropriate_JJ in_II the_AT context_NN1 of_IO iSMS_NN2 ,_, where_CS communication_NN1 is_VBZ related_VVN to_II consumers_NN2 situations_NN2 ,_, rather_II21 than_II22 urgency_NN1 or_CC immediacy_NN1 as_CSA in_II time-critical_JJ needs_NN2 ._. 
</s>
<s>
Finnairs_NP1 check-in_NN1 service_NN1 through_II iSMS_NN2 is_VBZ an_AT1 epitome_NN1 of_IO a_AT1 situation-related_JJ need_NN1 ._. 
</s>
<s>
3.2_MC ._. 
</s>
<s>
Interactivity_NN1 Besides_II privacy_NN1 and_CC relevance_NN1 ,_, interactivity_NN1 is_VBZ a_AT1 central_JJ concept_NN1 in_II mobile_JJ marketing_NN1 enabled_VVN by_II special_JJ characteristics_NN2 of_IO mobile_JJ phone_NN1 as_II a_AT1 medium_NN1 in_II mobile_JJ environment_NN1 (_( Barnes_NP1 and_CC Scornavacca_NP1 2004_MC )_) ._. 
</s>
<s>
Plenty_PN of_IO advantages_NN2 support_VV0 Kavassalis_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2003_MC )_) statement_NN1 of_IO interactivity_NN1 being_VBG one_MC1 of_IO the_AT top_JJ advantages_NN2 of_IO SMS_NP1 ;_; it_PPH1 allows_VVZ conversational_JJ one-to-one_JJ marketing_NN1 (_( Barwise_NP1 and_CC Strong_JJ 2002_MC )_) ,_, gives_VVZ consumers_NN2 more_RRR control_VV0 ,_, improves_VVZ customer_NN1 satisfaction_NN1 (_( Kumar_NP1 and_CC Zahn_NP1 2002_MC )_) and_CC relationship_NN1 development_NN1 (_( Ballentyne_NP1 and_CC Varey_NP1 2006_MC )_) ,_, as_RG well_RR as_CSA encourages_VVZ long-term_JJ transactions_NN2 (_( Kavassalis_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2003_MC )_) ._. 
</s>
<s>
The_AT primary_JJ advantage_NN1 however_RR ,_, lies_VVZ in_II its_APPGE contributions_NN2 to_II the_AT success_NN1 of_IO mobile_JJ marketing_NN1 endeavours_NN2 ;_; according_II21 to_II22 several_DA2 studies_NN2 ,_, interactive_JJ messages_NN2 are_VBR more_RGR effective_JJ and_CC lead_VV0 to_II higher_JJR success_NN1 levels_NN2 and_CC better_JJR response_NN1 rates_NN2 ._. 
</s>
<s>
(_( Jelassi_NN2 and_CC Enders_NN2 2005_MC )_) ._. 
</s>
<s>
Some_DD scholars_NN2 have_VH0 even_RR argued_VVN interactivity_NN1 to_TO be_VBI a_AT1 requisite_NN1 for_IF effective_JJ and_CC lucrative_JJ mobile_JJ marketing_NN1 campaigns_NN2 (_( Kavassalis_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2003_MC )_) ._. 
</s>
<s>
Traditionally_RR ,_, SMS_NP1 campaigns_NN2 involve_VV0 sending_VVG queries_NN2 ,_, advertisements_NN2 or_CC information_NN1 to_II consumers_NN2 and_CC usually_RR there_EX is_VBZ only_RR one_MC1 message_NN1 per_II session_NNT1 (_( BookIT_NP1 )_) ._. 
</s>
<s>
In_II iSMS_NN2 ,_, on_II the_AT other_JJ hand_NN1 ,_, the_AT message_NN1 is_VBZ delivered_VVN to_II the_AT end-user_NN1 with_IW the_AT purpose_NN1 of_IO being_VBG interactive_JJ ;_; asking_VVG the_AT end-user_NN1 to_TO consider_VVI the_AT suggestion_NN1 ,_, whether_CSW it_PPH1 is_VBZ a_AT1 check-in_NN1 possibility_NN1 or_CC a_AT1 proposed_JJ time_NNT1 schedule_NN1 and_CC returning_VVG with_IW some_DD of_IO the_AT suggested_JJ alternatives_NN2 ._. 
</s>
<s>
Moreover_RR ,_, the_AT dialogue_NN1 does_VDZ not_XX end_VVI here_RL ,_, but_CCB rather_RR continues_VVZ either_RR in_II the_AT form_NN1 of_IO confirmation_NN1 ,_, further_JJR information_NN1 or_CC personal_JJ contact_NN1 ._. 
</s>
<s>
This_DD1 interaction_NN1 between_II the_AT marketer_NN1 and_CC the_AT consumer_NN1 is_VBZ facilitated_VVN by_II the_AT convenience_NN1 of_IO the_AT solution_NN1 in_II a_AT1 sense_NN1 that_CST the_AT technique_NN1 enables_VVZ the_AT end-user_NN1 to_TO respond_VVI to_II the_AT message_NN1 with_IW a_AT1 one_MC1 button_NN1 principle_NN1 ._. 
</s>
<s>
This_DD1 aspect_NN1 of_IO convenience_NN1 is_VBZ discussed_VVN more_RGR thoroughly_RR in_II the_AT following_JJ chapter_NN1 ._. 
</s>
<s>
3.3_MC ._. 
</s>
<s>
Convenience_NN1 Where_CS servicescape_NN1 in_II relationship_NN1 marketing_NN1 literature_NN1 represent_VV0 interaction_NN1 between_II the_AT consumer_NN1 ,_, the_AT service_NN1 provider_NN1 and_CC the_AT physical_JJ environment_NN1 (_( Gummesson_NP1 2008_MC )_) ,_, messagescape_VV0 in_II this_DD1 paper_NN1 refers_VVZ to_II interaction_NN1 between_II the_AT end-user_NN1 and_CC the_AT service_NN1 provider_NN1 ,_, the_AT elements_NN2 of_IO the_AT message_NN1 content_NN1 as_II31 well_II32 as_II33 the_AT end-users_NN2 situation_NN1 in_II which_DDQ the_AT message_NN1 is_VBZ delivered_VVN ._. 
</s>
<s>
The_AT ubiquitous_JJ phenomenon_NN1 of_IO mobile_JJ phone_NN1 use_NN1 means_VVZ that_CST consumers_NN2 can_VM nowadays_RT be_VBI reached_VVN everywhere_RL and_CC at_II all_DB times_NNT2 ._. 
</s>
<s>
This_DD1 always_RR on_II mode_NN1 has_VHZ certain_JJ implications_NN2 for_IF the_AT requirements_NN2 of_IO ,_, and_CC the_AT consequences_NN2 of_IO acceptable_JJ and_CC poor_JJ adoption_NN1 of_IO mobile_JJ marketing_NN1 respectively_RR ._. 
</s>
<s>
These_DD2 issues_NN2 are_VBR addressed_VVN next_MD ._. 
</s>
<s>
SMS_NP1 marketing_NN1 has_VHZ been_VBN claimed_VVN to_TO be_VBI an_AT1 attractive_JJ alternative_NN1 for_IF marketers_NN2 due_II21 to_II22 the_AT channels_NN2 several_DA2 valuable_JJ features_NN2 ._. 
</s>
<s>
(_( Kavassalis_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2003_MC )_) Using_VVG it_PPH1 wisely_RR could_VM nevertheless_RR be_VBI argued_VVN somewhat_RR challenging_VVG ._. 
</s>
<s>
The_AT existing_JJ literature_NN1 has_VHZ demonstrated_VVN that_CST messagescape_VV0 ,_, should_VM fulfil_VVI e.g._REX some_DD of_IO the_AT following_JJ requirements_NN2 :_: messages_NN2 ought_VMK to_TO be_VBI short_JJ ,_, concise_JJ and_CC straight_RR to_II the_AT point_NN1 ,_, the_AT content_NN1 should_VM be_VBI funny_JJ ,_, entertaining_JJ or_CC informative_JJ ,_, the_AT service_NN1 system_NN1 should_VM be_VBI customer-friendly_JJ and_CC manageable_JJ to_TO avoid_VVI any_DD discomfort_NN1 ,_, furthermore_RR ,_, it_PPH1 should_VM be_VBI relevant_JJ to_II the_AT target_NN1 group_NN1 and_CC delivered_VVN at_II a_AT1 suitable_JJ time_NNT1 and_CC at_II appropriate_JJ frequency_NN1 ._. 
</s>
<s>
(_( Barwise_NP1 and_CC Strong_JJ 2002_MC ,_, Dickinger_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2004_MC ,_, Gummesson_NP1 2008_MC )_) In_II a_AT1 similar_JJ vein_NN1 ,_, these_DD2 requirements_NN2 regarding_II the_AT content_NN1 ,_, the_AT delivery_NN1 of_IO the_AT message_NN1 ,_, the_AT ease_NN1 of_IO use_NN1 interface_NN1 ,_, timeliness_NN1 and_CC frequency_NN1 have_VH0 been_VBN established_VVN to_TO influence_VVI consumer_NN1 perceptions_NN2 of_IO mobile_JJ marketing_NN1 (_( Barwise_NP1 and_CC Strong_JJ 2002_MC )_) of_IO which_DDQ particularly_RR ease_NN1 of_IO use_NN1 has_VHZ been_VBN demonstrated_VVN to_TO further_RRR facilitate_VVI the_AT adoption_NN1 of_IO mobile_JJ services_NN2 (_( Constantiou_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2006_MC )_) ._. 
</s>
<s>
Intelligent_JJ SMS_NP1 contributes_VVZ to_II the_AT convenience_NN1 of_IO the_AT channel_NN1 by_II introducing_VVG one_MC1 button_NN1 principle_NN1 (_( BookIT_NP1 )_) ._. 
</s>
<s>
This_DD1 method_NN1 allows_VVZ the_AT end-user_NN1 to_TO respond_VVI to_II the_AT message_NN1 by_II choosing_VVG from_II the_AT answer_NN1 alternatives_NN2 and_CC then_RT by_II responding_VVG to_II the_AT message_NN1 by_II pressing_VVG that_DD1 particular_JJ alternative_JJ key_NN1 ,_, e.g._REX A_ZZ1 ,_, B_ZZ1 or_CC C_ZZ1 ,_, and_CC sending_VVG the_AT message_NN1 to_II the_AT same_DA address_NN1 the_AT message_NN1 was_VBDZ delivered_VVN from_II ,_, hence_RR making_VVG the_AT solution_NN1 easy_JJ for_IF the_AT consumer_NN1 to_TO use_VVI ._. 
</s>
<s>
During_II the_AT dialogue_NN1 ,_, the_AT end-user_NN1 is_VBZ not_XX required_VVN to_TO register_VVI as_II a_AT1 user_NN1 ,_, remember_VV0 any_DD service_NN1 numbers_NN2 ,_, keywords_NN2 or_CC passwords_NN2 ,_, neither_DD1 is_VBZ the_AT end_NN1 user_NN1 expected_VVD to_TO shift_VVI to_II another_DD1 platform_NN1 to_TO complete_VVI the_AT communication_NN1 ._. 
</s>
<s>
Consistent_JJ with_IW this_DD1 notion_NN1 of_IO convenience_NN1 is_VBZ what_DDQ Barwise_NP1 and_CC Strong_NP1 (_( 2002_MC )_) discovered_VVD when_CS exploring_VVG the_AT effectiveness_NN1 of_IO text_NN1 messaging_NN1 and_CC learning_VVG that_CST if_CS a_AT1 response_NN1 from_II the_AT consumer_NN1 was_VBDZ expected_VVN ,_, it_PPH1 should_VM be_VBI made_VVN as_CSA simple_JJ and_CC effortless_JJ and_CC not_XX involving_VVG another_DD1 platform_NN1 ._. 
</s>
<s>
3.4_MC ._. 
</s>
<s>
Value_NN1 perspective_NN1 Central_JJ to_II the_AT entire_JJ discipline_NN1 of_IO marketing_NN1 is_VBZ the_AT concept_NN1 of_IO value_NN1 ._. 
</s>
<s>
Although_CS central_JJ and_CC largely_RR studied_VVN ,_, value_NN1 is_VBZ a_AT1 challenging_JJ concept_NN1 to_TO define_VVI due_II21 to_II22 its_APPGE personal_JJ and_CC individual_JJ nature_NN1 (_( Grnroos_NP1 2010_MC ,_, Prahalad_NP1 and_CC Ramaswamy_NP1 2004_MC )_) ._. 
</s>
<s>
Since_CS value_NN1 as_II a_AT1 concept_NN1 is_VBZ so_RG elusive_JJ (_( Vargo_NP1 ,_, Maglio_NP1 and_CC Akaka_NP1 2008_MC )_) ,_, it_PPH1 is_VBZ difficult_JJ to_TO determine_VVI what_DDQ precisely_RR adds_VVZ value_NN1 to_II different_JJ consumers_NN2 ;_; for_IF some_DD value_NN1 is_VBZ monetary-related_JJ ,_, for_IF some_DD it_PPH1 might_VM be_VBI entertainment_NN1 whereas_CS for_IF some_DD it_PPH1 might_VM be_VBI saved_VVN time_NNT1 and_CC convenience_NN1 ._. 
</s>
<s>
Zeithaml_VV0 already_RR in_II the_AT late_JJ 1980s_MC2 discussed_VVD the_AT difficulty_NN1 of_IO conceptualizing_VVG the_AT value_NN1 concept_NN1 in_II his_APPGE research_NN1 on_II consumer_NN1 perceptions_NN2 of_IO price_NN1 ,_, quality_NN1 and_CC value_NN1 ._. 
</s>
<s>
He_PPHS1 identified_VVD four_MC differing_JJ consumer_NN1 definitions_NN2 of_IO value_NN1 and_CC synthesised_VVD them_PPHO2 into_II one_MC1 overall_JJ definition_NN1 :_: perceived_JJ value_NN1 is_VBZ the_AT consumers_NN2 overall_JJ assessment_NN1 of_IO the_AT utility_NN1 of_IO a_AT1 product_NN1 based_VVN on_II perceptions_NN2 of_IO what_DDQ is_VBZ received_VVN and_CC what_DDQ is_VBZ given_VVN (_( Zeithaml_NP1 1988_MC ,_, p._NN1 14_MC )_) ._. 
</s>
<s>
Out_II21 of_II22 existing_JJ concepts_NN2 ,_, two_MC general_JJ meanings_NN2 of_IO value_NN1 ;_; value-in-exchange_JJ and_CC value-in-use_NN1 are_VBR stated_VVN to_TO reflect_VVI the_AT nature_NN1 of_IO value_NN1 and_CC value_NN1 creation_NN1 (_( Vargo_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2008_MC )_) of_IO which_DDQ the_AT first_MD could_VM be_VBI argued_VVN to_TO represent_VVI the_AT classic_JJ economic_JJ theory_NN1 and_CC the_AT latter_DA the_AT later_RRR emerged_VVD service_NN1 marketing_NN1 paradigm_NN1 ._. 
</s>
<s>
During_II past_RL several_DA2 decades_NNT2 ,_, the_AT emphasis_NN1 of_IO marketing_NN1 paradigm_NN1 shifted_VVN from_II goods_NN2 to_II services_NN2 ,_, from_II products_NN2 to_II processes_NN2 ,_, from_II transactions_NN2 to_II interactions_NN2 ,_, from_II exchanges_NN2 to_II experiences_NN2 ,_, and_CC finally_RR from_II value_NN1 embedded_VVN in_II products_NN2 into_II value_NN1 co-creation_NN1 and_CC value-in-use_NN1 (_( Prahalad_NP1 and_CC Ramaswamy_NP1 2004_MC ,_, Vargo_NP1 and_CC Lusch_NP1 2004_MC )_) ._. 
</s>
<s>
Briefly_RR ,_, from_II goods_NN2 based_VVN marketing_NN1 into_II service_NN1 marketing_NN1 ._. 
</s>
<s>
In_II the_AT same_DA vein_NN1 ,_, the_AT field_NN1 of_IO mobile_JJ marketing_NN1 could_VM be_VBI said_VVN to_TO follow_VVI the_AT same_DA transition_NN1 ;_; shifting_VVG from_II promoting_VVG offerings_NN2 into_II offering_VVG services_NN2 ._. 
</s>
<s>
In_II the_AT case_NN1 of_IO iSMS_NN2 and_CC Finnairs_NN2 check_VV0 in_II service_NN1 ,_, the_AT consumer_NN1 checks_VVZ himself_PPX1 to_II a_AT1 flight_NN1 simply_RR by_II answering_VVG a_AT1 text_NN1 message_NN1 ,_, thereby_RR managing_VVG to_TO save_VVI time_NNT1 and_CC effort_NN1 since_CS he_PPHS1 escapes_VVZ queuing_VVG at_II the_AT check-in_NN1 counter_NN1 ._. 
</s>
<s>
For_IF frequent_JJ fliers_NN2 especially_RR ,_, this_DD1 benefit_NN1 of_IO saving_VVG time_NNT1 and_CC effort_NN1 is_VBZ significant_JJ ._. 
</s>
<s>
The_AT access_NN1 to_II the_AT service_NN1 has_VHZ therefore_RR been_VBN improved_VVN ._. 
</s>
<s>
Saving_VVG customers_NN2 time_NNT1 and_CC effort_NN1 are_VBR likewise_RR claimed_VVN to_TO be_VBI common_JJ benefits_NN2 of_IO market-creating_JJ innovations_NN2 (_( Berry_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2006_MC )_) ._. 
</s>
<s>
Hereby_RR ,_, this_DD1 paper_NN1 suggests_VVZ that_CST the_AT characteristics_NN2 epitomising_VVG iSMS_NN2 ;_; interactivity_NN1 ,_, privacy_NN1 &;_NULL relevance_NN1 ,_, convenience_NN1 as_II31 well_II32 as_II33 value_NN1 perspective_NN1 ,_, all_DB influence_VV0 the_AT end-user_NN1 perceptions_NN2 towards_II offering_VVG mobile_JJ services_NN2 and_CC hence_RR support_VV0 adopting_VVG this_DD1 new_JJ way_NN1 of_IO approaching_VVG mobile_JJ marketing_NN1 activities_NN2 ._. 
</s>
