<s>
Easiness_NN1 in_II Buying_VVG 1_MC1 Introduction_NN1 Buying_NN1 and_CC consumer_NN1 behavior_NN1 has_VHZ been_VBN studied_VVN extensively_RR ,_, especially_RR the_AT phenomena_NN2 consumer_NN1 convenience_NN1 ._. 
</s>
<s>
Time_NNT1 is_VBZ a_AT1 limited_JJ resource_NN1 for_IF consumers_NN2 ._. 
</s>
<s>
Discussion_NN1 around_II conveniences_NN2 has_VHZ been_VBN revolving_VVG around_II consumer_NN1 's_GE need_NN1 to_TO save_VVI time_NNT1 and_CC effort_NN1 when_CS buying_VVG products_NN2 or_CC services_NN2 (_( Kelley_NP1 1958_MC ;_; Anderson_NP1 and_CC Shugan_NP1 1991_MC ;_; Berry_NP1 ,_, Seiders_NP1 and_CC Grewal_NP1 2002_MC )_) ._. 
</s>
<s>
Convenience_NN1 has_VHZ been_VBN used_VVN also_RR in_II the_AT words_NN2 "_" convenience_NN1 foods_NN2 "_" or_CC "_" convenience_NN1 goods_NN2 "_" Copeland_NP1 (_( 1923:282_MC )_) ._. 
</s>
<s>
Convenience_NN1 products_NN2 or_CC services_NN2 can_VM save_VVI consumer_NN1 's_GE time_NNT1 and_CC effort_NN1 in_II supplier_NN1 's_GE thinking_NN1 ,_, but_CCB in_II practise_NN1 they_PPHS2 might_VM cause_VVI inconvenience_NN1 from_II consumer_NN1 point_NN1 of_IO view_NN1 ._. 
</s>
<s>
For_REX21 example_REX22 self-service_JJ check-in_NN1 at_II airport_NN1 using_VVG machines_NN2 save_VV0 supplier_NN1 's_GE resource_NN1 costs_NN2 and_CC consumer_NN1 's_GE time_NNT1 if_CS the_AT tools_NN2 work_VV0 when_CS needed_VVN ._. 
</s>
<s>
However_RR ,_, when_CS tools_NN2 do_VD0 not_XX work_VVI they_PPHS2 require_VV0 more_DAR time_NNT1 and_CC effort_NN1 from_II consumer_NN1 ._. 
</s>
<s>
Zeithaml_NP1 (_( 1988_MC )_) discusses_VVZ sacrifices_NN2 instead_II21 of_II22 conveniences_NN2 ._. 
</s>
<s>
In_II her_APPGE view_NN1 people_NN sacrifice_VV0 time_NNT1 and_CC non-monetary_JJ resources_NN2 in_II buying_NN1 ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 consumers_NN2 receive_VV0 products_NN2 or_CC services_NN2 in_II exchange_NN1 ._. 
</s>
<s>
According_II21 to_II22 Zeithaml_NP1 (_( 1988_MC )_) when_RRQ consumer_NN1 's_GE sacrifices_NN2 decrease_NN1 increases_VVZ the_AT perceived_JJ value_NN1 of_IO the_AT product_NN1 for_IF the_AT consumer_NN1 ._. 
</s>
<s>
Extensive_JJ research_NN1 on_II what_DDQ makes_VVZ consumer_NN1 's_GE buying_NN1 experience_NN1 easy_JJ from_II consumer_NN1 's_GE point_NN1 of_IO view_NN1 is_VBZ scarce_JJ ._. 
</s>
<s>
Easy_JJ buying_NN1 is_VBZ used_VVN often_RR as_II a_AT1 slogan_NN1 in_II internet_NN1 sales_NN ,_, for_REX21 example_REX22 it_PPH1 is_VBZ written_VVN on_II Amazon_NP1 web_NN1 pages_NN2 :_: "_" Placing_VVG an_AT1 order_NN1 with_IW Amazon.com_NP1 is_VBZ easy_JJ "_" (_( Amazon_NP1 2010_MC )_) ._. 
</s>
<s>
In_II practise_NN1 consumers_NN2 test_VV0 this_DD1 slogan_NN1 and_CC experience_VV0 the_AT buying_NN1 easy_JJ or_CC difficult_JJ ._. 
</s>
<s>
The_AT questions_NN2 arise_VV0 :_: Is_VBZ easiness_NN1 in_II buying_NN1 related_VVN to_II the_AT increased_JJ perceived_JJ value_NN1 or_CC to_II the_AT smaller_JJR amount_NN1 of_IO total_JJ sacrifices_NN2 or_CC something_PN1 else_RR ?_? 
</s>
<s>
Hence_RR ,_, the_AT area_NN1 need_NN1 to_TO be_VBI further_JJR studied._NNU 1.1_MC Research_NN1 problem_NN1 and_CC purpose_NN1 of_IO the_AT study_NN1 Literature_NN1 search_NN1 was_VBDZ performed_VVN to_TO find_VVI theories_NN2 related_VVN to_II consumer_NN1 's_GE easiness_NN1 in_II buying_NN1 ._. 
</s>
<s>
Academic_JJ articles_NN2 were_VBDR searched_VVN through_II search_NN1 tools_NN2 (_( such_II21 as_II22 EBSCO_NP1 )_) ,_, using_VVG several_DA2 keywords_NN2 such_II21 as_II22 "_" buying_NN1 "_" ,_, "_" consumer/s_FU "_" and_CC "_" buying_VVG "_" with_IW its_APPGE synonym_NN1 words_NN2 (_( purchasing_NN1 ,_, shopping_VVG )_) ,_, "_" easiness_NN1 in_II buying/purchasing_NN1 "_" ,_, "_" buying_VVG easy_JJ "_" ,_, "_" purchasing_VVG easy_JJ "_" ._. 
</s>
<s>
The_AT aim_NN1 of_IO the_AT literature_NN1 search_NN1 was_VBDZ to_TO identify_VVI what_DDQ has_VHZ been_VBN written_VVN about_II easiness_NN1 in_II buying_VVG earlier_RRR and_CC what_DDQ aspects_NN2 influence_VV0 consumer_NN1 buying_NN1 behaviour_NN1 ,_, especially_RR what_DDQ makes_VVZ consumer_NN1 's_VBZ buying_VVG easy_JJ ._. 
</s>
<s>
Consumer_NN1 behaviour_NN1 and_CC buying_NN1 has_VHZ been_VBN researched_VVN extensively_RR ,_, however_RGQV academic_JJ papers_NN2 on_II "_" easiness_NN1 in_II buying_NN1 "_" could_VM not_XX be_VBI found_VVN and_CC it_PPH1 is_VBZ assumed_VVN by_II researcher_NN1 that_CST research_NN1 does_VDZ not_XX exist_VVI at_II the_AT moment_NN1 ._. 
</s>
<s>
The_AT purpose_NN1 of_IO this_DD1 paper_NN1 is_VBZ to_TO discuss_VVI using_VVG un-directly_RR related_JJ theories_NN2 theories_NN2 what_DDQ could_VM explain_VVI consumer_NN1 's_GE experience_NN1 on_II easy_JJ buying_NN1 ._. 
</s>
<s>
Consumer_NN1 buying_NN1 has_VHZ been_VBN studied_VVN a_RR21 lot_RR22 ,_, but_CCB it_PPH1 is_VBZ not_XX well_RR understood_VVN what_DDQ makes_VVZ buying_VVG easy_JJ or_CC difficult_JJ to_II consumers_NN2 ._. 
</s>
<s>
This_DD1 discussion_NN1 could_VM help_VVI companies_NN2 to_TO understand_VVI consumers'point_NN1 of_IO view_NN1 better_RRR and_CC as_II a_AT1 consequence_NN1 serve_VV0 them_PPHO2 better_RRR and_CC increase_NN1 company_NN1 's_GE profits._NNU 1.2_MC Research_NN1 Questions_NN2 Purpose_NN1 of_IO this_DD1 study_NN1 to_TO find_VVI answers_NN2 to_II the_AT following_JJ research_NN1 questions_NN2 :_: 1_MC1 )_) What_DDQ is_VBZ easiness_NN1 in_II buying_VVG ?_? 2_MC )_) What_DDQ could_VM explain_VVI easy_JJ buying_NN1 ?_? 
</s>
<s>
Easiness_NN1 in_II buying_NN1 has_VHZ not_XX been_VBN yet_RR defined_VVN ,_, that_DD1 is_VBZ why_RRQ a_AT1 tentative_JJ concept_NN1 is_VBZ provided_VVN according_II21 to_II22 the_AT theoretical_JJ knowledge_NN1 ._. 
</s>
<s>
Second_MD ,_, it_PPH1 is_VBZ discussed_VVN what_DDQ could_VM explain_VVI phenomena_NN2 easy_JJ buying_NN1 ._. 
</s>
<s>
Consumer_NN1 buying_NN1 is_VBZ a_AT1 wide_JJ area_NN1 ._. 
</s>
<s>
In_II this_DD1 discussion_NN1 aim_NN1 is_VBZ to_TO choose_VVI the_AT main_JJ factors_NN2 that_CST could_VM explain_VVI easy_JJ buying_NN1 ._. 
</s>
<s>
Third_MD ,_, the_AT possible_JJ consequences_NN2 of_IO easy_JJ buying_NN1 are_VBR discussed._NNU 1.3_MC Delimitations_NN2 The_AT paper_NN1 focuses_VVZ to_II consumer_NN1 's_GE easy_JJ buying_NN1 ,_, but_CCB not_XX consumer_NN1 's_GE buying_NN1 behaviour_NN1 in_RR21 general_RR22 ._. 
</s>
<s>
The_AT buying_NN1 process_NN1 is_VBZ perceived_VVN holistically_RR what_DDQ happens_VVZ before_II ,_, during_II and_CC after_II buying_NN1 ._. 
</s>
<s>
However_RR ,_, consumer_NN1 's_GE value_NN1 in_II use_NN1 is_VBZ excluded_VVN ._. 
</s>
<s>
In_II this_DD1 study_NN1 "_" consumers_NN2 "_" are_VBR perceived_VVN to_TO be_VBI people_NN who_PNQS buy_VV0 products_NN2 or_CC services_NN2 in_II the_AT business_NN1 to_II consumer_NN1 (_( B2C_FO )_) context_NN1 ._. 
</s>
<s>
"_" Buying_NN1 "_" refers_VVZ in_II this_DD1 paper_NN1 to_II consumer_NN1 buying_NN1 items_NN2 or_CC services_NN2 ._. 
</s>
<s>
Close_VV0 existing_JJ words_NN2 are_VBR "_" purchasing_VVG "_" and_CC "_" shopping_NN1 "_" ._. 
</s>
<s>
Shopping_NN1 refers_VVZ to_II buying_NN1 ,_, but_CCB also_RR to_II items_NN2 bought_VVN in_II shops_NN2 (_( Hornby_NP1 1995_MC )_) ._. 
</s>
<s>
2_MC Easy_JJ -_- Difficult_JJ buying_NN1 Discussion_NN1 on_II what_DDQ is_VBZ "_" easy_JJ "_" and_CC what_DDQ is_VBZ "_" difficult_JJ "_" -_- consumer_NN1 perception_NN1 on_II buying_NN1 Referring_VVG to_II Berry_NP1 etc._RA others_NN2 3_MC Consumer_NN1 Sacrifices_VVZ Convenience_NN1 literature_NN1 has_VHZ concentrated_VVN on_II time_NNT1 ,_, financial_JJ resources_NN2 ,_, endeavour_NN1 and_CC energy_NN1 that_CST people_NN spend_VV0 when_RRQ they_PPHS2 acquire_VV0 products_NN2 or_CC services_NN2 ._. 
</s>
<s>
Zeithaml_NP1 (_( 1988_MC )_) has_VHZ called_VVN consumer_NN1 's_GE time_NNT1 and_CC effort_NN1 as_CSA "_" sacrifices_VVZ "_" instead_II21 of_II22 conveniences_NN2 ._. 
</s>
<s>
People_NN do_VD0 not_XX think_VVI only_RR of_IO monetary_JJ costs_NN2 ,_, but_CCB also_RR other_JJ perceived_JJ sacrifices_NN2 such_II21 as_II22 the_AT time_NNT1 consumer_NN1 spends_VVZ when_CS obtaining_VVG product_NN1 as_RR21 well_RR22 the_AT mental_JJ costs_NN2 and_CC search_NN1 costs_VVZ that_CST occur_VV0 ._. 
</s>
<s>
Consumer_NN1 's_VBZ perceived_VVN sacrifices_NN2 influence_VV0 how_RRQ product_NN1 's_GE value_NN1 is_VBZ perceived_VVN ._. 
</s>
<s>
According_II21 to_II22 Zeithaml_NP1 (_( 1988_MC )_) the_AT perceived_JJ value_NN1 is_VBZ an_AT1 evaluation_NN1 by_II consumer_NN1 about_II the_AT overall_JJ benefits_NN2 of_IO the_AT product_NN1 ._. 
</s>
<s>
The_AT evaluation_NN1 is_VBZ influenced_VVN by_II consumer_NN1 's_GE perception_NN1 what_DDQ is_VBZ given_VVN and_CC what_DDQ is_VBZ received_VVN back_RP ,_, those_DD2 perceptions_NN2 can_VM be_VBI referred_VVN also_RR as_CSA salient_JJ give_VV0 and_CC get_VV0 components_NN2 to_II consumer_NN1 ._. 
</s>
<s>
In_II other_JJ words_NN2 consumer_NN1 sacrifices_VVZ time_NNT1 ,_, effort_NN1 ,_, and_CC other_JJ resources_NN2 when_CS buying_VVG ._. 
</s>
<s>
Then_RT consumer_NN1 evaluates_VVZ the_AT costs_NN2 (_( not_XX only_RR monetary_JJ )_) and_CC creates_VVZ perceived_JJ value_NN1 perception_NN1 ._. 
</s>
<s>
This_DD1 definition_NN1 about_II giving_VVG and_CC receiving_VVG back_RP might_VM appear_VVI that_CST people_NN calculate_VV0 carefully_RR benefits_NN2 and_CC costs_NN2 of_IO the_AT product_NN1 or_CC service_NN1 ._. 
</s>
<s>
In_II31 view_II32 of_II33 Zeithaml_NP1 (_( 1988_MC )_) consumer_NN1 's_GE perception_NN1 of_IO value_NN1 can_VM be_VBI increased_JJ for_REX21 example_REX22 if_CS financial_JJ and_CC non-financial_JJ costs_NN2 decrease_VV0 ._. 
</s>
<s>
In_II other_JJ words_NN2 when_RRQ consumers_NN2 experience_NN1 's_GE perception_NN1 is_VBZ that_CST there_EX are_VBR less_RGR total_JJ sacrifices_NN2 the_AT perceived_JJ value_NN1 increases_VVZ for_IF consumer._NNU 3.1_MC Image_NN1 In_II this_DD1 chapter_NN1 image_NN1 is_VBZ discussed_VVN through_II examples_NN2 of_IO studies_NN2 made_VVN on_II image_NN1 and_CC it_PPH1 's_VBZ influence_NN1 on_II consumers_NN2 ._. 
</s>
<s>
In_II this_DD1 study_NN1 image_NN1 is_VBZ defined_VVN as_CSA perception_NN1 that_CST consumers_NN2 have_VH0 about_II a_AT1 company_NN1 ,_, is_VBZ company_NN1 perceived_VVD positively_RR or_CC negatively_RR ._. 
</s>
<s>
The_AT definition_NN1 is_VBZ close_JJ to_II Keh_NP1 and_CC Zieh_NP1 (_( 2009_MC )_) definition_NN1 of_IO company_NN1 reputation_NN1 ._. 
</s>
<s>
The_AT same_DA authors_NN2 studied_VVD how_RRQ company_NN1 reputation_NN1 affects_VVZ on_II customer_NN1 buying_NN1 behavior_NN1 ._. 
</s>
<s>
The_AT writers_NN2 claim_VV0 that_CST positive_JJ company_NN1 reputation_NN1 affects_VVZ on_II customer_NN1 's_GE trust_NN1 towards_II company_NN1 and_CC how_RGQ ready_JJ they_PPHS2 are_VBR to_TO pay_VVI higher_JJR prices_NN2 ._. 
</s>
<s>
Furthermore_RR ,_, if_CS a_AT1 company_NN1 's_GE reputation_NN1 is_VBZ good_JJ ,_, customers_NN2 perceive_VV0 the_AT company_NN1 positively_RR such_II21 as_II22 reliable_JJ ,_, proficient_JJ and_CC ethical_JJ ._. 
</s>
<s>
In_II real_JJ life_NN1 company_NN1 reputation_NN1 can_VM change_VVI to_II negative_JJ very_RG quickly_RR ;_; Keh_NP1 and_CC Xie_NP1 (_( 2009_MC )_) give_VV0 an_AT1 example_NN1 about_II Enron_NP1 ._. 
</s>
<s>
Another_DD1 example_NN1 could_VM be_VBI case_NN1 of_IO Lehman_NN1 Brothers_NN2 ,_, where_CS company_NN1 's_GE reputation_NN1 was_VBDZ ruined_VVN rapidly_RR ._. 
</s>
<s>
Consumer_NN1 's_GE are_VBR concerned_JJ also_RR about_II company_NN1 's_GE reputation_NN1 ._. 
</s>
<s>
For_IF company_NN1 bad_JJ reputation_NN1 means_VVZ loosing_VVG customers_NN2 and_CC profit_NN1 ._. 
</s>
<s>
In_II this_DD1 study_NN1 consumer_NN1 's_GE share_NN1 their_APPGE buying_NN1 experiences_NN2 ._. 
</s>
<s>
Assumption_NN1 in_II the_AT stories_NN2 company_NN1 's_GE image_NN1 and_CC trust_VV0 towards_II company_NN1 are_VBR also_RR covered_VVN in_II those_DD2 discussions_NN2 ._. 
</s>
<s>
Mall_NN1 image_NN1 was_VBDZ studied_VVN by_II Chebat_NP1 ,_, Sirgy_NP1 and_CC Grzeskowiak_NP1 (_( 2010_MC )_) ._. 
</s>
<s>
According_II21 to_II22 their_APPGE thinking_NN1 ,_, if_CS consumers_NN2 perceive_VV0 a_AT1 mall_NN1 's_GE image_NN1 to_TO be_VBI strong_JJ ,_, it_PPH1 can_VM help_VVI to_TO attract_VVI more_DAR visitors_NN2 to_II the_AT mall_NN1 ._. 
</s>
<s>
Chebat_VV0 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2010_MC )_) suggest_VV0 that_DD1 management_NN1 of_IO a_AT1 mall_NN1 should_VM carry_VVI out_RP marketing_NN1 research_NN1 concerning_II the_AT five_MC "_" mall_NN1 image_NN1 dimensions_NN2 "_" that_CST relate_VV0 to_II customer_NN1 's_GE access_NN1 to_II the_AT mall_NN1 ,_, how_RRQ is_VBZ the_AT atmosphere_NN1 in_II the_AT mall_NN1 and_CC price_NN1 level_NN1 ._. 
</s>
<s>
Access_NN1 has_VHZ to_TO do_VDI with_IW how_RRQ consumers_NN2 perceive_VV0 for_REX21 example_REX22 the_AT availability_NN1 of_IO parking_VVG lots_PN ._. 
</s>
<s>
Further_JJR dimensions_NN2 are_VBR related_VVN to_II how_RRQ consumers_NN2 perceive_VV0 the_AT mall_NN1 's_GE assortments_NN2 (_( such_II21 as_II22 wideness_NN1 of_IO the_AT assortment_NN1 ,_, how_RRQ consumer_NN1 perceives_VVZ the_AT amount_NN1 of_IO services_NN2 and_CC goods_NN2 in_II the_AT mall_NN1 )_) ._. 
</s>
<s>
Furthermore_RR ,_, for_IF consumer_NN1 's_GE convenience_NN1 it_PPH1 is_VBZ important_JJ how_RGQ extensive_JJ they_PPHS2 perceive_VV0 the_AT availability_NN1 of_IO product_NN1 sizes_NN2 ,_, brand_NN1 ,_, and_CC colours_NN2 (_( 736_MC )_) ._. 
</s>
<s>
In_II Chebat_NP1 ,_, Sirgy_NP1 and_CC Csreskowiak_NP1 (_( 2010_MC )_) management_NN1 has_VHZ the_AT responsibility_NN1 to_TO follow_VVI up_RP the_AT consumer_NN1 's_VBZ perceived_VVN mall_NN1 image_NN1 and_CC take_VV0 actions_NN2 accordingly_RR ._. 
</s>
<s>
The_AT question_NN1 is_VBZ how_RRQ the_AT image_NN1 is_VBZ developed_VVN and_CC can_VV0 company_NN1 influence_NN1 image_NN1 (_( Grnroos_NP1 2007_MC :_: 343_MC )_) ._. 
</s>
<s>
For_REX21 example_REX22 companies_NN2 advertise_VV0 towards_II consumers_NN2 and_CC this_DD1 affects_VVZ to_II the_AT image_NN1 that_CST is_VBZ created_VVN in_II consumer_NN1 's_GE mind_NN1 ._. 
</s>
<s>
However_RR ,_, consumer_NN1 can_VM have_VHI an_AT1 image_NN1 about_II company_NN1 already_RR before_II becoming_VVG a_AT1 customer_NN1 for_IF the_AT company._NNU 3.2_MC Accessibility_NN1 It_PPH1 is_VBZ crucial_JJ that_CST consumers_NN2 can_VM access_VVI the_AT service_NN1 and_CC it_PPH1 functions_VVZ ,_, which_DDQ does_VDZ not_XX always_RR happen_VVI regardless_RR of_IO the_AT way_NN1 of_IO accessing_NN1 ._. 
</s>
<s>
According_II21 to_II22 Berry_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2002_MC )_) consumers_NN2 perceive_VV0 that_CST they_PPHS2 use_VV0 effort_NN1 and_CC time_NNT1 when_RRQ accessing_NN1 to_II services_NN2 ._. 
</s>
<s>
That_DD1 is_VBZ defined_VVN as_CSA access_NN1 convenience_NN1 ._. 
</s>
<s>
Consumer_NN1 's_GE access_NN1 can_VM take_VVI place_NN1 in_II many_DA2 ways_NN2 :_: by_II phone_NN1 ,_, online_RR ,_, visiting_JJ service_NN1 or_CC using_VVG self-service_JJ technologies_NN2 ._. 
</s>
<s>
Meuter_NN1 ,_, Bitner_NP1 ,_, Ostrom_NP1 and_CC Brown_NP1 (_( 2005_MC )_) give_VV0 examples_NN2 on_II self-service_JJ technologies_NN2 such_II21 as_II22 possibility_NN1 to_TO pay_VVI at_II the_AT pump_NN1 when_CS tanking_VVG a_AT1 car_NN1 ,_, automatic_JJ banking_NN1 machines_NN2 ,_, electronic_JJ check-out_NN1 from_II hotel_NN1 ,_, banking_VVG through_II the_AT phone_NN1 and_CC transactions_NN2 in_II internet._NNU 3.3_MC Service_NN1 Encounter_NN1 Consumers_NN2 interact_VV0 with_IW suppliers_NN2 during_II buying_NN1 ._. 
</s>
<s>
The_AT interaction_NN1 is_VBZ referred_VVN to_II as_CSA service_NN1 encounter_NN1 ._. 
</s>
<s>
Surprenant_NN1 and_CC Solomon_NP1 (_( 1987_MC )_) interpret_VV0 the_AT term_NN1 "_" service_NN1 encounter_NN1 "_" as_II a_AT1 "_" dyadic_JJ interaction_NN1 between_II a_AT1 customer_NN1 and_CC a_AT1 service_NN1 provider_NN1 ._. "_" 
</s>
<s>
This_DD1 approach_NN1 sees_VVZ interaction_NN1 taking_VVG place_NN1 in_II two_MC ways_NN2 ._. 
</s>
<s>
In_II this_DD1 study_NN1 the_AT service_NN1 encounter_NN1 is_VBZ seen_VVN as_II a_AT1 two_MC way_NN1 interaction_NN1 similar_JJ to_II Suprenant_NP1 and_CC Salomon_NP1 (_( 1987_MC )_) ,_, because_CS both_DB2 parties_NN2 ,_, consumer_NN1 and_CC service_NN1 provider_NN1 need_NN1 to_TO interact_VVI to_TO make_VVI actual_JJ buying_NN1 happen_VV0 ._. 
</s>
<s>
From_II consumer_NN1 's_GE point_NN1 of_IO view_NN1 service_NN1 encounters_NN2 are_VBR critical_JJ ,_, because_CS according_II21 to_II22 service_NN1 encounter_NN1 experiences_NN2 consumer_NN1 creates_VVZ an_AT1 idea_NN1 of_IO the_AT company_NN1 and_CC how_RGQ easy_JJ is_VBZ it_PPH1 to_TO interact_VVI with_IW the_AT company_NN1 ._. 
</s>
<s>
Consumers_NN2 '_GE emotions_NN2 during_II the_AT interactions_NN2 with_IW their_APPGE supplier_NN1 affect_NN1 consumer_NN1 behaviour_NN1 ._. 
</s>
<s>
Ladhari_JJ claims_NN2 (_( 2007_MC )_) that_DD1 consumer_NN1 's_GE emotions_NN2 have_VH0 an_AT1 affect_NN1 on_II consumer_NN1 's_GE behavior_NN1 after_II buying_NN1 ._. 
</s>
<s>
According_II21 to_II22 this_DD1 concept_NN1 feelings_NN2 "_" pleasure_NN1 "_" and_CC "_" arousal_NN1 "_" influence_NN1 significantly_RR to_II word_NN1 of_IO mouth_NN1 communication_NN1 ._. 
</s>
<s>
According_II21 to_II22 this_DD1 author_NN1 ,_, "_" pleasure_NN1 "_" relates_VVZ to_II feelings_NN2 of_IO joyful_JJ ,_, happy_JJ or_CC contented_JJ and_CC "_" arousal_NN1 "_" person_NN1 's_VBZ feeling_VVG awake_JJ ,_, stimulated_VVD ,_, alert_JJ or_CC active_JJ in_II encounter_NN1 (_( 1087_MC )_) ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 service_NN1 personnel_NN2 's_GE behavior_NN1 influences_VVZ the_AT consumer_NN1 ._. 
</s>
<s>
Wang_NP1 (_( 2009_MC )_) claims_VVZ that_CST the_AT positive_JJ emotions_NN2 that_CST service_NN1 personnel_NN2 show_VV0 during_II the_AT service_NN1 encounter_NN1 have_VH0 an_AT1 impact_NN1 on_II consumer_NN1 's_GE positive_JJ view_NN1 towards_II brand_NN1 ,_, satisfaction_NN1 with_IW the_AT employees_NN2 and_CC re-_JJ purchase_NN1 intentions._NNU 3.4_MC Supportiveness_NN1 In_II this_DD1 paper_NN1 supportiveness_NN1 refers_VVZ to_II the_AT perceived_JJ support_NN1 that_CST consumer_NN1 receives_VVZ from_II the_AT service_NN1 provider_NN1 during_II buying_NN1 ._. 
</s>
<s>
Consumers_NN2 need_VV0 to_TO decide_VVI what_DDQ to_TO buy_VVI from_II where_RRQ ._. 
</s>
<s>
Choosing_VVG a_AT1 product_NN1 or_CC service_NN1 selection_NN1 process_NN1 can_VM be_VBI overwhelming_JJ from_II consumer_NN1 's_GE point_NN1 of_IO view_NN1 ._. 
</s>
<s>
Diehl_NP1 and_CC Poynor_NP1 (_( 2010_MC )_) call_VV0 this_DD1 a_AT1 choice_NN1 overload_NN1 ._. 
</s>
<s>
These_DD2 authors_NN2 propose_VV0 that_CST neither_RR big_JJ or_CC small_JJ assortment_NN1 of_IO products_NN2 is_VBZ good_JJ from_II consumers_NN2 point_NN1 of_IO view_NN1 ._. 
</s>
<s>
Reasons_NN2 for_IF this_DD1 perception_NN1 are_VBR that_CST when_CS consumers_NN2 have_VH0 small_JJ choice_NN1 their_APPGE assumption_NN1 is_VBZ that_CST they_PPHS2 can_VM not_XX find_VVI the_AT product_NN1 they_PPHS2 wish_VV0 ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 according_II21 to_II22 Diehl_NP1 and_CC Poynor_NP1 (_( 2010_MC )_) when_RRQ amount_NN1 of_IO expands_VVZ consumers_NN2 view_VV0 that_CST they_PPHS2 can_VM better_RRR select_VVI their_APPGE preferred_JJ product_NN1 and_CC experience_NN1 dissatisfaction_NN1 if_CS they_PPHS2 can_VM not_XX find_VVI what_DDQ they_PPHS2 are_VBR looking_VVG for_IF (_( 312_MC )_) ._. 
</s>
<s>
Service_NN1 providers_NN2 can_VM support_VVI the_AT consumers_NN2 in_II the_AT selection_NN1 ._. 
</s>
<s>
A_AT1 practical_JJ example_NN1 is_VBZ a_AT1 chat_NN1 service_NN1 for_IF consumers_NN2 in_II the_AT company_NN1 web_NN1 pages_NN2 ._. 
</s>
<s>
Ikea_NN1 uses_VVZ on_II their_APPGE local_JJ home_NN1 pages_NN2 "_" online_JJ assistants_NN2 "_" that_CST answer_VV0 consumers_NN2 in_II their_APPGE questions_NN2 related_VVN to_II products_NN2 or_CC services_NN2 (_( http_NNU :_: //www.ikea.com/gb/en/_JJ )_) From_II service_NN1 provider_NN1 's_GE view_NN1 the_AT purpose_NN1 is_VBZ to_TO facilitate_VVI the_AT choice_NN1 of_IO consumer_NN1 ._. 
</s>
<s>
The_AT general_JJ question_NN1 is_VBZ how_RRQ consumers_NN2 perceive_VV0 support_NN1 ._. 
</s>
<s>
Does_VDZ it_PPH1 help_VVI them_PPHO2 to_TO make_VVI choices_NN2 ?_? 
</s>
<s>
Would_VM consumer_NN1 perceive_VV0 buying_VVG easier_RRR or_CC even_RR more_RGR difficult_JJ ?_? 4_MC Tentative_JJ Framework_NN1 for_IF Easiness_NN1 in_II Buying_VVG One_MC1 objective_NN1 in_II this_DD1 study_NN1 is_VBZ conceptualise_NN1 "_" easiness_NN1 in_II buying_VVG "_" and_CC build_VV0 a_AT1 model_NN1 ,_, which_DDQ shows_VVZ what_DDQ factors_NN2 could_VM influence_VVI consumer_NN1 's_GE buying_NN1 experience_NN1 ._. 
</s>
<s>
The_AT Figure_NN1 X_MC ,_, tentative_JJ framework_NN1 for_IF "_" Easiness_NN1 in_II Buying_NN1 "_" is_VBZ put_VVN forward_RL in_II Figure_NN1 1_MC1 ._. 
</s>
<s>
It_PPH1 displays_VVZ what_DDQ factors_NN2 can_VM explain_VVI how_RRQ consumers_NN2 perceive_VV0 easiness_NN1 in_II buying_NN1 ._. 
</s>
<s>
Explaining_VVG factors_NN2 chosen_VVN from_II literature_NN1 discussed_VVD earlier_RRR in_II this_DD1 paper_NN1 :_: Image_NN1 ,_, Sacrifices_NN2 ,_, Accessibility_NN1 ,_, Service_NN1 Encounter_NN1 and_CC Supportiveness_NP1 ._. 
</s>
<s>
The_AT factors_NN2 as_RG important_JJ as_CSA the_AT others_NN2 ,_, i.e._REX none_PN is_VBZ more_RGR important_JJ than_CSN the_AT other_JJ ._. 
</s>
<s>
It_PPH1 is_VBZ also_RR important_JJ to_TO note_VVI that_CST this_DD1 model_NN1 does_VDZ not_XX include_VVI all_DB the_AT factors_NN2 that_CST explain_VV0 easy_JJ buying_NN1 ,_, but_CCB the_AT ones_NN2 that_CST are_VBR selected_VVN according_II21 to_II22 literature_NN1 ._. 
</s>
<s>
Summarise_VV0 here_RL the_AT theories_NN2 +_FO Easy_JJ buying_NN1 is_VBZ =_FO ?_? 4_MC Discussion_NN1 Consequences_NN2 of_IO Easy_JJ buying_NN1 Consumer_NN1 's_GE experience_NN1 on_II easy_JJ buying_NN1 can_VM affect_VVI on_II relationship_NN1 between_II consumer_NN1 and_CC company_NN1 ._. 
</s>
<s>
According_II21 to_II22 Ravald_NP1 and_CC Grnroos_NP1 (_( 1996_MC )_) ._. 
</s>
<s>
Write_VV0 here_RL about_II the_AT customer-perceive_VV0 value_NN1 /_FO episode_NN1 /_FO benefits_NN2 /_FO sacrifices_VVZ 
</s>
