<s>
Building_VVG an_AT1 underground_JJ brand_NN1 Introduction_NN1 Established_VVD markets_NN2 are_VBR often_RR controlled_VVN by_II a_AT1 small_JJ amount_NN1 of_IO big_JJ brands_NN2 ,_, which_DDQ newfound_JJ brands_NN2 may_VM find_VVI hard_JJ to_TO compete_VVI with_IW directly_RR ._. 
</s>
<s>
Big_JJ brands_NN2 have_VH0 a_AT1 tendency_NN1 to_TO please_VVI a_AT1 large_JJ amount_NN1 of_IO the_AT market_NN1 with_IW their_APPGE product_NN1 ,_, however_RRQV this_DD1 leaves_VVZ smaller_JJR customer_NN1 segments_NN2 out_II21 of_II22 the_AT target_NN1 group_NN1 ._. 
</s>
<s>
By_II targeting_VVG a_AT1 niche_NN1 market_NN1 ,_, created_VVN in_II the_AT spaces_NN2 created_VVN in_II21 between_II22 the_AT big_JJ brands_NN2 ruling_VVG the_AT market_NN1 ,_, newfound_JJ brands_NN2 or_CC smaller_JJR divisions_NN2 in_II larger_JJR companies_NN2 are_VBR able_JK to_TO avoid_VVI competing_VVG directly_RR with_IW the_AT bigger_JJR brands_NN2 (_( Kahn_NP1 ;_; Kalwani_NP1 ;_; &;_NULL Morrison_NP1 ,_, 1988_MC )_) (_( Doyle_NP1 ,_, 2012_MC )_) ._. 
</s>
<s>
This_DD1 way_NN1 new_JJ brands_NN2 or_CC products_NN2 have_VH0 the_AT opportunity_NN1 to_TO control_VVI a_AT1 whole_JJ segment_NN1 within_II the_AT market_NN1 (_( Doyle_NP1 ,_, 2012_MC )_) ._. 
</s>
<s>
Brands_NN2 concurring_VVG these_DD2 niches_NN2 may_VM be_VBI called_VVN niche_NN1 brands_NN2 ,_, lifestyle_NN1 brands_NN2 or_CC underground_JJ brands_NN2 (_( Kahn_NP1 ;_; Kalwani_NP1 ;_; &;_NULL Morrison_NP1 ,_, 1988_MC )_) ._. 
</s>
<s>
Modern_JJ communication_NN1 platforms_NN2 have_VH0 altered_VVN the_AT composition_NN1 of_IO markets_NN2 ,_, creating_VVG a_AT1 global_JJ marketplace_NN1 ._. 
</s>
<s>
The_AT same_DA characteristics_NN2 still_RR apply_VV0 ,_, but_CCB in_II a_AT1 greater_JJR scale_NN1 ._. 
</s>
<s>
This_DD1 switch_NN1 in_II scale_NN1 has_VHZ revolutionized_VVN the_AT settings_NN2 in_II niche_NN1 markets_NN2 ._. 
</s>
<s>
The_AT formerly_RR small_JJ markets_NN2 now_RT have_VH0 large_JJ global_JJ audiences_NN2 ._. 
</s>
<s>
Small_JJ segment_NN1 products_NN2 now_RT have_VH0 the_AT possibility_NN1 reach_VV0 out_RP for_IF a_AT1 big_JJ customer_NN1 volume_NN1 and_CC gain_VV0 control_NN1 of_IO this_DD1 segment_NN1 of_IO the_AT market_NN1 ,_, thus_RR making_VVG niche_NN1 markets_NN2 more_RGR attractive_JJ ._. 
</s>
<s>
Underground_JJ brands_NN2 controlling_VVG niche_NN1 markets_NN2 are_VBR closely_RR related_VVN to_II lifestyle_NN1 brands_NN2 ,_, which_DDQ have_VH0 their_APPGE roots_NN2 in_II lifestyle_NN1 movements_NN2 and_CC communities_NN2 and_CC tribal_JJ behavior_NN1 (_( e.g._REX snowboarding_VVG ,_, skateboarding_VVG and_CC music_NN1 styles_NN2 )_) ._. 
</s>
<s>
The_AT build_VV0 up_RP of_IO lifestyle_NN1 brands_NN2 and_CC underground_JJ brands_NN2 has_VHZ lately_RR been_VBN topics_NN2 of_IO discussion_NN1 ;_; still_RR only_RR few_DA2 studies_NN2 have_VH0 been_VBN conducted_VVN in_II this_DD1 area_NN1 ._. 
</s>
<s>
Thus_RR ,_, there_EX is_VBZ a_AT1 lack_NN1 of_IO relevant_JJ research_NN1 examining_VVG the_AT building_NN1 processes_NN2 and_CC characteristics_NN2 of_IO underground_JJ brands_NN2 ._. 
</s>
<s>
The_AT switch_NN1 in_II market_NN1 size_NN1 within_II the_AT segments_NN2 these_DD2 underground_JJ brands_NN2 act_VV0 in_RP ,_, creating_VVG global_JJ niche_NN1 markets_NN2 underlines_VVZ that_CST further_JJR research_NN1 in_II this_DD1 field_NN1 is_VBZ well_RR motivated_VVN ._. 
</s>
<s>
Research_NN1 question_NN1 and_CC limitations_NN2 This_DD1 research_NN1 will_VM aim_VVI to_TO study_VVI the_AT underlying_JJ processes_NN2 driving_VVG the_AT creation_NN1 of_IO underground_JJ brands_NN2 and_CC examine_VV0 if_CSW there_EX are_VBR some_DD characteristics_NN2 stigmatizing_VVG the_AT underground_JJ brands_NN2 and_CC the_AT surroundings_NN2 they_PPHS2 act_VV0 in_RP ._. 
</s>
<s>
Due_II21 to_II22 the_AT limited_JJ time_NNT1 reserved_VVN for_IF the_AT research_NN1 ,_, there_EX are_VBR some_DD limits_NN2 regarding_II the_AT depth_NN1 and_CC scope_NN1 of_IO the_AT research_NN1 ._. 
</s>
<s>
The_AT research_NN1 will_VM be_VBI limited_VVN to_II Finish_NN1 brands_NN2 acting_VVG in_II the_AT clothing_NN1 industry_NN1 ._. 
</s>
<s>
The_AT clothing_NN1 industry_NN1 is_VBZ a_AT1 context_NN1 where_CS tribal_JJ behavior_NN1 plays_VVZ a_AT1 central_JJ role_NN1 ,_, thus_RR being_VBG a_AT1 well-motivated_JJ segment_NN1 of_IO research_NN1 ._. 
</s>
<s>
Method_NN1 The_AT study_NN1 will_VM be_VBI conducted_VVN through_II open_JJ interviews_NN2 made_VVN with_IW local_JJ underground_JJ brands_NN2 acting_VVG in_II the_AT clothing_NN1 industry_NN1 ._. 
</s>
<s>
The_AT data_NN gathered_VVN will_VM be_VBI analyzed_VVN through_II a_AT1 theoretical_JJ framework_NN1 consisting_VVG of_IO studies_NN2 conducted_VVN in_II the_AT fields_NN2 of_IO brand_NN1 building_NN1 and_CC underground/lifestyle_NN1 brands_NN2 ._. 
</s>
<s>
Theoretical_JJ framework_NN1 In_II this_DD1 part_NN1 of_IO the_AT study_NN1 a_AT1 theoretical_JJ framework_NN1 for_IF the_AT study_NN1 will_VM be_VBI created_VVN ._. 
</s>
<s>
The_AT theoretical_JJ framework_NN1 is_VBZ based_VVN in_II literature_NN1 and_CC studies_NN2 conducted_VVN in_II the_AT field_NN1 of_IO underground_JJ brands_NN2 ,_, brand_NN1 building_NN1 theory_NN1 ,_, lifestyle_NN1 brands_NN2 and_CC tribal_JJ behavior_NN1 ._. 
</s>
<s>
The_AT brand_NN1 This_DD1 part_NN1 of_IO the_AT theoretical_JJ framework_NN1 will_VM explain_VVI what_DDQ a_AT1 brand_NN1 is_VBZ ,_, how_RRQ it_PPH1 is_VBZ created_VVN and_CC managed_VVN ._. 
</s>
<s>
Niche_NN1 brands_VVZ A_AT1 niche_NN1 is_VBZ a_AT1 part_NN1 of_IO the_AT market_NN1 which_DDQ is_VBZ the_AT domain_NN1 of_IO specialists_NN2 (_( Peter_NP1 Moles_NN2 ,_, 2012_MC )_) ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, a_AT1 delimited_JJ space_NN1 on_II the_AT market_NN1 where_CS competition_NN1 is_VBZ not_XX as_RG strong_JJ as_CSA in_II the_AT market_NN1 segment_NN1 generally_RR (_( Doyle_NP1 ,_, 2012_MC )_) ._. 
</s>
<s>
By_II targeting_VVG and_CC specializing_VVG in_II a_AT1 niche_NN1 market_VV0 a_AT1 brand_NN1 may_VM be_VBI able_JK to_TO control_VVI a_AT1 large_JJ share_NN1 of_IO the_AT specific_JJ market_NN1 (_( Doyle_NP1 ,_, 2012_MC )_) ._. 
</s>
<s>
According_II21 to_II22 Kahn_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( Kahn_NP1 ;_; Kalwani_NP1 ;_; &;_NULL Morrison_NP1 ,_, 1988_MC )_) niche_NN1 brands_NN2 can_VM be_VBI seen_VVN as_CSA brands_NN2 with_IW a_AT1 lower_JJR level_NN1 of_IO penetration_NN1 and_CC a_AT1 higher_JJR level_NN1 of_IO loyalty_NN1 than_CSN expected_VVN for_IF its_APPGE market_NN1 share_NN1 in_II the_AT segment_NN1 ._. 
</s>
<s>
Suggesting_VVG underground_JJ brands_NN2 or_CC niche_NN1 brands_NN2 have_VH0 a_AT1 strong_JJ and_CC loyal_JJ customer_NN1 base_NN1 ,_, but_CCB are_VBR not_XX familiar_JJ to_II the_AT larger_JJR audience_NN1 ._. 
</s>
<s>
Tribalism_NN1 The_AT postmodern_JJ society_NN1 is_VBZ labeled_VVN by_II increased_JJ individualism_NN1 in_II western_JJ countries_NN2 ._. 
</s>
<s>
Traditional_JJ social_JJ and_CC cultural_JJ groups_NN2 have_VH0 become_VVN less_RGR important_JJ to_II people_NN in_II western_JJ countries_NN2 ._. 
</s>
<s>
The_AT development_NN1 of_IO communication_NN1 platforms_NN2 ,_, commerce_NN1 and_CC industry_NN1 has_VHZ nurtured_VVN a_AT1 fragmentation_NN1 of_IO society_NN1 ._. 
</s>
<s>
(_( Cova_NP1 &;_NULL Cova_NP1 ,_, 2002_MC )_) This_DD1 has_VHZ led_VVN to_II the_AT formation_NN1 of_IO other_JJ social_JJ communities_NN2 through_II which_DDQ individuals_NN2 are_VBR able_JK to_TO identify_VVI themselves_PPX2 and_CC satisfy_VVI their_APPGE need_NN1 of_IO belonging_VVG to_II a_AT1 community_NN1 ._. 
</s>
<s>
Tribes_NN2 are_VBR communities_NN2 ,_, which_DDQ consist_VV0 of_IO individuals_NN2 that_CST share_VV0 not_XX only_RR interests_NN2 ,_, but_CCB also_RR strong_JJ emotional_JJ links_NN2 and_CC a_AT1 common_JJ sub-culture_NN1 ._. 
</s>
<s>
(_( Cova_NP1 &;_NULL Cova_NP1 ,_, 2002_MC )_) (_( Moutinho_NP1 ;_; Dionisio_NP1 ;_; &;_NULL Leal_NP1 ,_, 2007_MC )_) The_AT influence_NN1 of_IO modern_JJ communication_NN1 Interviews_NN2 Discussion_NN1 Conclustion_NN1 Further_JJR research_NN1 
</s>
