<s>
One-to-one_JJ marketing_NN1 :_: Counterattacking_VVG the_AT problems_NN2 1_MC1 Introduction_NN1 The_AT world_NN1 of_IO marketing_NN1 has_VHZ undergone_VVN a_AT1 huge_JJ transformation_NN1 in_II the_AT past_JJ decades_NNT2 ._. 
</s>
<s>
The_AT discipline_NN1 started_VVD off_RP transactional_JJ and_CC has_VHZ now_RT moved_VVN to_TO become_VVI relational_JJ ._. 
</s>
<s>
In_II the_AT transactional_JJ period_NN1 ,_, the_AT competition_NN1 was_VBDZ scarce_JJ and_CC companies_NN2 had_VHD the_AT power_NN1 to_TO decide_VVI on_II what_DDQ was_VBDZ produced_VVN and_CC the_AT customers_NN2 had_VHD no_AT means_NN in_II influencing_VVG the_AT production_NN1 ._. 
</s>
<s>
Nowadays_RT ,_, the_AT tables_NN2 have_VH0 turned_VVN ;_; information_NN1 is_VBZ easily_RR available_JJ and_CC therefore_RR customers_NN2 have_VH0 no_AT problem_NN1 in_II comparing_VVG different_JJ alternatives_NN2 and_CC finding_VVG exactly_RR what_DDQ they_PPHS2 want_VV0 ._. 
</s>
<s>
Hence_RR ,_, mass_JJ marketing_NN1 becomes_VVZ ineffective_JJ and_CC customers_NN2 may_VM and_CC will_VM give_VVI feedback_NN1 to_II companies_NN2 ._. 
</s>
<s>
Competition_NN1 is_VBZ fierce_JJ and_CC in_BCL21 order_BCL22 to_TO succeed_VVI a_AT1 company_NN1 needs_VVZ to_TO put_VVI the_AT customers_NN2 in_II focus_NN1 and_CC meet_VVI their_APPGE demands_NN2 ._. 
</s>
<s>
One-to-one_JJ marketing_NN1 ;_; personalization_NN1 and_CC customization_NN1 have_VH0 become_VVN relevant_JJ ._. 
</s>
<s>
There_EX have_VH0 been_VBN several_DA2 studies_NN2 on_II one-to-one_JJ marketing_NN1 and_CC it_PPH1 is_VBZ generally_RR accepted_VVN that_CST it_PPH1 brings_VVZ upon_II many_DA2 opportunities_NN2 for_IF a_AT1 company_NN1 ._. 
</s>
<s>
Jamie_NP1 Fiorda_NP1 (_( Karr_NP1 2001_MC )_) claims_VVZ that_CST such_DA opportunities_NN2 are_VBR e.g._REX increased_JJ sales_NN and_CC customer_NN1 loyalty_NN1 ._. 
</s>
<s>
However_RR ,_, where_CS there_EX are_VBR opportunities_NN2 ,_, there_RL also_RR lie_VV0 problems_NN2 ._. 
</s>
<s>
There_EX are_VBR some_DD studies_NN2 on_II the_AT issues_NN2 but_CCB no_AT comprehensive_JJ study_NN1 seems_VVZ to_TO exist_VVI and_CC many_DA2 companies_NN2 are_VBR struggling_VVG with_IW the_AT issues_NN2 regarding_II one-to-one_JJ marketing_NN1 ._. 
</s>
<s>
This_DD1 study_NN1 aims_VVZ at_II mapping_VVG out_RP the_AT problems_NN2 in_II one-to-one_JJ marketing_NN1 from_II both_RR a_AT1 companys_NN2 and_CC a_AT1 customers_NN2 perspective_NN1 ._. 
</s>
<s>
The_AT secondary_JJ aim_NN1 is_VBZ to_TO look_VVI at_II the_AT managerial_JJ implications_NN2 and_CC arrive_VVI at_II a_AT1 conclusion_NN1 on_II what_DDQ a_AT1 company_NN1 can_VM do_VDI to_TO address_VVI these_DD2 issues_NN2 ._. 
</s>
<s>
The_AT paper_NN1 is_VBZ divided_VVN into_II three_MC sections_NN2 ._. 
</s>
<s>
In_II the_AT first_MD section_NN1 ,_, previous_JJ literature_NN1 on_II one-to-one_JJ marketing_NN1 will_VM be_VBI examined_VVN ._. 
</s>
<s>
A_AT1 special_JJ interest_NN1 will_VM be_VBI put_VVN on_II the_AT problems_NN2 encountered_VVN in_II one-to-one_JJ marketing_NN1 ._. 
</s>
<s>
The_AT second_MD section_NN1 will_VM contain_VVI managerial_JJ implications_NN2 ,_, i.e._REX what_DDQ managers_NN2 can_VM do_VDI to_TO deal_VVI with_IW these_DD2 issues_NN2 of_IO one-to-one_JJ marketing_NN1 ._. 
</s>
<s>
The_AT last_MD section_NN1 will_VM contain_VVI a_AT1 discussion_NN1 and_CC conclusions_NN2 of_IO the_AT study_NN1 ._. 
</s>
<s>
2_MC One-to-one_JJ marketing_NN1 Definition_NN1 of_IO one-to-one_JJ marketing_NN1 ._. 
</s>
<s>
Difference_NN1 between_II personalization_NN1 and_CC customization_NN1 ;_; Personalization_NN1 is_VBZ Internet_NN1 based_VVN (_( personalizing_VVG web-pages_NN2 according_II21 to_II22 the_AT users_NN2 movement_NN1 on_II the_AT web_NN1 )_) and_CC customization_NN1 is_VBZ product_NN1 based_VVN (_( designing_VVG your_APPGE own_DA Nike_NN1 shoes_NN2 )_) (_( Arora_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2008_MC )_) ._. 
</s>
<s>
2.1_MC Personalization_NN1 Benefits_NN2 Problems_NN2 e.g._REX privacy_NN1 (_( Smyth_NP1 2007_MC )_) and_CC legal_JJ (_( Schubert_NP1 ,_, Kummer_NP1 &;_NULL Leimstoll_NP1 2006_MC )_) issues_NN2 ;_; how_RRQ and_CC what_DDQ information_NN1 can_VM a_AT1 company_NN1 gather_VVI about_II a_AT1 customer_NN1 without_IW crossing_VVG the_AT laws_NN2 and_CC invading_JJ customer_NN1 privacy_NN1 ._. 
</s>
<s>
Personalizing_NP1 might_VM also_RR be_VBI difficult_JJ ;_; it_PPH1 is_VBZ not_XX an_AT1 easy_JJ task_NN1 to_TO create_VVI a_AT1 system_NN1 that_CST gathers_VVZ the_AT right_JJ information_NN1 and_CC does_VDZ so_RR effectively_RR ._. 
</s>
<s>
2.2_MC Customization_NN1 Benefits_NN2 Problems_NN2 e.g._REX humans_NN2 are_VBR lazy_JJ ;_; do_VD0 they_PPHS2 really_RR care_VVI enough_DD to_TO put_VVI the_AT time_NNT1 and_CC effort_NN1 into_II designing_VVG their_APPGE own_DA products_NN2 ?_? 
</s>
<s>
Customers_NN2 have_VH0 fuzzy_JJ expectations_NN2 (_( Ojasalo_NP1 2001_MC )_) i.e._REX they_PPHS2 do_VD0 not_XX always_RR know_VVI what_DDQ they_PPHS2 want_VV0 and_CC therefore_RR need_VV0 the_AT company_NN1 to_TO put_VVI it_PPH1 in_II31 front_II32 of_II33 them_PPHO2 ._. 
</s>
<s>
Costs_NN2 ;_; it_PPH1 can_VM be_VBI expensive_JJ to_TO create_VVI a_AT1 system_NN1 that_CST supports_VVZ customization_NN1 (_( technical_JJ ,_, functional_JJ )_) ._. 
</s>
<s>
Risk_VV0 ;_; the_AT company_NN1 might_VM invest_VVI huge_JJ sums_NN2 of_IO money_NN1 and_CC fail_VVI to_TO make_VVI the_AT customizing_JJ offer_NN1 successful_JJ ._. 
</s>
<s>
Brands_NN2 ;_; brands_NN2 are_VBR very_RG powerful_JJ in_II some_DD industries_NN2 ._. 
</s>
<s>
The_AT customer_NN1 might_VM specifically_RR want_VVI a_AT1 designed_JJ product_NN1 ,_, not_XX their_APPGE own_DA creation_NN1 ._. 
</s>
<s>
3_MC Managerial_JJ implications_NN2 What_DDQ can_VM a_AT1 company_NN1 do_VDI to_TO counterattack_VVI the_AT problems_NN2 ?_? 4_MC Conclusions_NN2 
</s>
