<s>
How_RRQ Does_VDZ Insider_NN1 Trading_NN1 Affect_NN1 Shareholder_NN1 Value_NN1 in_II Finland_NP1 ?_? 
</s>
<s>
Introduction_NN1 The_AT trade_NN1 of_IO financial_JJ instruments_NN2 using_VVG inside_RL or_CC non-public_JJ information_NN1 has_VHZ since_RR the_AT aftermath_NN1 of_IO the_AT Great_JJ Depression_NN1 been_VBN forbidden_VVN in_II the_AT United_NP1 States_NP1 ._. 
</s>
<s>
The_AT Securities_NN2 Exchange_NN1 Act_NN1 of_IO 1934_MC that_CST specifies_VVZ the_AT insider_NN1 trading_NN1 regulations_NN2 still_RR applies_VVZ ,_, and_CC it_PPH1 has_VHZ not_XX changed_VVN much_DA1 since_RR ._. 
</s>
<s>
However_RR ,_, questions_NN2 regarding_II the_AT sanity_NN1 of_IO the_AT strict_JJ regulation_NN1 have_VH0 arisen_VVN ,_, with_IW Manne_NP1 (_( 1966_MC )_) publishing_VVG the_AT paper_NN1 :_: In_II31 Defence_II32 of_II33 Insider_NN1 Trading_NN1 ,_, where_CS the_AT Securities_NN2 Exchange_NN1 Commissions_NN2 (_( SEC_NNU )_) regulatory_JJ actions_NN2 are_VBR viewed_VVN as_II a_AT1 real_JJ disservice_NN1 to_II the_AT American_JJ shareholder_NN1 (_( p._NNU 122_MC )_) ._. 
</s>
<s>
Moreover_RR ,_, Milton_NP1 Friedman_NP1 later_RRR noted_VVD :_: You_PPY want_VV0 more_DAR insider_NN1 trading_NN1 ,_, not_XX less._NNU (_( http_NNU :_: //www.pbs.org/_JJ )_) Even_CS21 though_CS22 the_AT financial_JJ crisis_NN1 of_IO 2008_MC dampened_VVD the_AT discussion_NN1 ,_, the_AT debate_NN1 between_II regulators_NN2 and_CC critics_NN2 of_IO the_AT strict_JJ legislation_NN1 is_VBZ still_RR ongoing_JJ ._. 
</s>
<s>
The_AT monetary_JJ nature_NN1 of_IO the_AT market_NN1 in_II the_AT US_NP1 makes_VVZ for_IF a_AT1 more_RGR lively_JJ discussion_NN1 than_CSN in_II the_AT fiscal_JJ markets_NN2 of_IO northern_JJ Europe_NP1 ,_, and_CC as_CSA such_DA the_AT opposition_NN1 against_II the_AT regulators_NN2 in_II Finland_NP1 is_VBZ not_XX as_RG strong_JJ ._. 
</s>
<s>
However_RR ,_, the_AT relatively_RR loose_JJ control_NN1 poses_VVZ the_AT question_NN1 whether_CSW the_AT system_NN1 works_VVZ as_CSA it_PPH1 is_VBZ or_CC not_XX ._. 
</s>
<s>
Since_CS the_AT adoption_NN1 of_IO insider_NN1 trading_NN1 regulations_NN2 in_II Finland_NP1 in_II 1989_MC ,_, there_EX have_VH0 been_VBN a_AT1 few_DA2 court_NN1 rulings_NN2 on_II the_AT issue_NN1 ,_, which_DDQ will_VM be_VBI discussed_VVN in_II greater_JJR detail_NN1 in_II the_AT following_JJ sections_NN2 ._. 
</s>
<s>
Differences_NN2 in_II legislative_JJ systems_NN2 ,_, especially_RR compared_VVN to_II the_AT US_NP1 common_JJ law_NN1 ,_, will_VM be_VBI in_II focus_NN1 ,_, and_CC combined_VVN with_IW the_AT previous_JJ research_NN1 in_II the_AT area_NN1 ,_, the_AT effects_NN2 of_IO informed_JJ trading_NN1 on_II the_AT Finnish_JJ stock_NN1 market_NN1 can_VM be_VBI analyzed_VVN ._. 
</s>
<s>
Aim_VV0 The_AT aim_NN1 of_IO this_DD1 paper_NN1 is_VBZ to_TO analyze_VVI insider_NN1 trading_NN1 regulations_NN2 in_II Finland_NP1 ,_, and_CC to_TO determine_VVI how_RGQ potential_JJ insider_NN1 trades_NN2 affect_VV0 minority_NN1 shareholder_NN1 value_NN1 and_CC the_AT market_NN1 as_II a_AT1 whole_NN1 ._. 
</s>
<s>
Structure_NN1 of_IO the_AT paper_NN1 After_II an_AT1 introduction_NN1 to_II the_AT insider_NN1 trading_NN1 debate_NN1 in_II sections_NN2 1_MC1 and_CC 2_MC ,_, important_JJ pieces_NN2 of_IO previous_JJ research_NN1 will_VM be_VBI reviewed_VVN in_II section_NN1 3_MC ._. 
</s>
<s>
Sections_NN2 4_MC and_CC 5_MC focus_VV0 on_II the_AT legal_JJ system_NN1 and_CC previous_JJ court_NN1 rulings_NN2 in_II Finland_NP1 ,_, where_RRQ after_II a_AT1 summarizing_JJ discussion_NN1 follows_VVZ in_II section_NN1 6_MC ._. 
</s>
<s>
The_AT insider_NN1 trading_NN1 debate_NN1 The_AT debate_NN1 between_II regulatory_JJ authorities_NN2 and_CC liberals_NN2 striving_VVG for_IF loosened_JJ regulation_NN1 is_VBZ more_RGR commonly_RR referred_VVN to_II as_II the_AT insider_NN1 trading_NN1 debate_NN1 (_( Hu_NP1 &;_NULL Noe_NP1 (_( 1997_MC )_) )_) ._. 
</s>
<s>
The_AT government_NN1 enforcing_VVG the_AT regulation_NN1 is_VBZ protecting_VVG outside_JJ shareholders_NN2 and_CC the_AT overall_JJ stability_NN1 of_IO the_AT market_NN1 ,_, whereas_CS corporate_JJ lobbyists_NN2 and_CC a_AT1 portion_NN1 of_IO the_AT academic_JJ community_NN1 argue_VV0 that_CST legalized_VVD insider_NN1 trading_NN1 would_VM increase_VVI overall_JJ market_NN1 efficiency_NN1 by_II sooner_RRR reflecting_VVG new_JJ information_NN1 in_II asset_NN1 prices_NN2 ._. 
</s>
<s>
On_II the_AT modern_JJ financial_JJ markets_NN2 of_IO today_RT though_CS ,_, information_NN1 is_VBZ king_NN1 ,_, and_CC any_DD market_NN1 participant_NN1 acting_VVG based_VVN on_II inferior_JJ information_NN1 has_VHZ a_AT1 considerable_JJ disadvantage_NN1 ._. 
</s>
<s>
Arguments_NN2 for_IF deregulation_NN1 The_AT paper_NN1 :_: In_II31 Defence_II32 of_II33 Insider_NN1 Trading_NN1 ,_, by_II Manne_NP1 in_II 1966_MC ,_, is_VBZ one_MC1 of_IO the_AT first_MD papers_NN2 questioning_VVG the_AT logic_NN1 behind_II the_AT SECs_NNU2 strict_JJ regulation_NN1 in_II the_AT USA_NP1 ,_, and_CC though_CS the_AT markets_NN2 have_VH0 developed_VVN vastly_RR in_II the_AT decades_NNT2 since_CS the_AT time_NNT1 of_IO publishing_NN1 ,_, the_AT same_DA points_NN2 still_RR apply_VV0 ._. 
</s>
<s>
He_PPHS1 argued_VVD that_DD1 regulation_NN1 creates_VVZ inefficiency_NN1 as_CSA new_JJ information_NN1 is_VBZ published_VVN with_IW a_AT1 considerable_JJ delay_NN1 ,_, whereby_RRQ the_AT markets_NN2 do_VD0 not_XX act_VVI quickly_RR enough_RR ._. 
</s>
<s>
Legalized_JJ insider_NN1 trading_NN1 ,_, however_RR ,_, would_VM cure_VVI the_AT problem_NN1 as_CSA any_DD employee_NN1 or_CC manager_NN1 with_IW unpublished_JJ information_NN1 could_VM make_VVI arbitrage_NN1 gains_NN2 until_CS markets_NN2 reach_VV0 the_AT equilibrium_NN1 price_NN1 ,_, thereby_RR increasing_JJ efficiency_NN1 ._. 
</s>
<s>
Moreover_RR ,_, as_CSA the_AT access_NN1 to_II inside_JJ information_NN1 is_VBZ economically_RR beneficial_JJ for_IF the_AT managers_NN2 ,_, it_PPH1 would_VM become_VVI part_NN1 of_IO their_APPGE normal_JJ compensation_NN1 ._. 
</s>
<s>
As_CSA such_DA corporations_NN2 could_VM utilize_VVI a_AT1 greater_JJR portion_NN1 of_IO their_APPGE wealth_NN1 on_II positive_JJ NPV_NP1 projects_NN2 ._. 
</s>
<s>
Additionally_RR ,_, it_PPH1 is_VBZ argued_VVN that_DD1 compensation_NN1 for_IF entrepreneurial_JJ managers_NN2 does_VDZ not_XX function_VVI as_CSA it_PPH1 is_VBZ ,_, because_CS taking_VVG risks_NN2 and_CC inventing_VVG something_PN1 brilliant_JJ would_VM not_XX benefit_VVI the_AT decision_NN1 makers_NN2 personally_RR ._. 
</s>
<s>
Gains_NN2 from_II inside_JJ information_NN1 ,_, however_RR ,_, would_VM give_VVI managers_NN2 an_AT1 incentive_NN1 to_TO take_VVI risks_NN2 from_II which_DDQ positive_JJ stock_NN1 market_NN1 reactions_NN2 occur_VV0 ._. 
</s>
<s>
As_II a_AT1 result_NN1 it_PPH1 can_VM be_VBI concluded_VVN that_CST there_EX are_VBR apparent_JJ benefits_NN2 of_IO legalized_JJ insider_NN1 trading_NN1 that_CST keep_VV0 the_AT debate_NN1 going_VVG ,_, and_CC one_MC1 of_IO the_AT main_JJ points_NN2 of_IO Mannes_NP2 paper_NN1 was_VBDZ to_TO make_VVI the_AT public_JJ aware_JJ of_IO that_DD1 there_EX are_VBR alternative_JJ views_NN2 to_II those_DD2 put_VVN forth_RR by_II the_AT regulators_NN2 ._. 
</s>
<s>
Arguments_NN2 for_IF continued_JJ regulation_NN1 In_II most_DAT developed_JJ financial_JJ markets_NN2 the_AT trade_NN1 of_IO financial_JJ instruments_NN2 using_VVG inside_RL or_CC non-public_JJ information_NN1 is_VBZ illegal_JJ ,_, and_CC this_DD1 section_NN1 of_IO the_AT paper_NN1 presents_VVZ the_AT main_JJ points_NN2 behind_II the_AT rationale_NN1 of_IO the_AT strict_JJ legislation_NN1 ._. 
</s>
<s>
If_CS some_DD market_NN1 participants_NN2 had_VHD access_NN1 to_II information_NN1 that_CST was_VBDZ not_XX available_JJ to_II everyone_PN1 ,_, the_AT ones_NN2 acting_VVG based_VVN on_II inferior_JJ information_NN1 would_VM eventually_RR be_VBI driven_VVN out_II21 of_II22 the_AT market_NN1 ._. 
</s>
<s>
As_II such_DA ,_, even_RR on_II the_AT simple_JJ ethical_JJ grounds_NN2 of_IO fairness_NN1 ,_, utilizing_VVG inside_II information_NN1 for_IF ones_NN2 economic_JJ benefit_NN1 is_VBZ wrong_JJ ._. 
</s>
<s>
Additionally_RR ,_, based_VVN on_II the_AT fact_NN1 that_CST a_AT1 large_JJ portion_NN1 of_IO liquidity_NN1 traders_NN2 and_CC market_VV0 professionals_NN2 would_VM be_VBI driven_VVN out_II21 of_II22 the_AT market_NN1 (_( Hu_NP1 &;_NULL Noe_NP1 (_( 1997_MC )_) )_) ,_, the_AT overall_JJ amount_NN1 of_IO traders_NN2 would_VM decline_VVI ;_; resulting_VVG in_II widened_JJ bid-ask_VV0 spreads_NN2 and_CC reduced_JJ liquidity_NN1 on_II the_AT market_NN1 ._. 
</s>
<s>
The_AT reduced_JJ quality_NN1 of_IO minority_NN1 shareholder_NN1 protection_NN1 ,_, however_RR ,_, would_VM have_VHI additional_JJ consequences_NN2 ,_, including_II difficulties_NN2 in_II raising_VVG capital_NN1 for_IF corporations_NN2 ._. 
</s>
<s>
If_CS investors_NN2 felt_VVD that_CST they_PPHS2 are_VBR unprotected_JJ by_II the_AT law_NN1 ,_, they_PPHS2 were_VBDR to_TO require_VVI a_AT1 premium_NN1 for_IF the_AT additional_JJ risk_NN1 ,_, making_VVG equity_NN1 capital_NN1 more_RGR expensive_JJ for_IF corporations_NN2 :_: the_AT consequences_NN2 of_IO which_DDQ would_VM be_VBI felt_VVN on_II a_AT1 macroeconomic_JJ level_NN1 ._. 
</s>
<s>
Previous_JJ research_NN1 Maug_NN1 ,_, Ernst_NP1 (_( 2002_MC )_) In_II the_AT paper_NN1 :_: Insider_NN1 Trading_NN1 Legislation_NN1 and_CC Corporate_JJ Governance_NN1 ,_, from_II 2002_MC ,_, Maug_NP1 creates_VVZ a_AT1 model_NN1 on_II how_RRQ insider_NN1 trading_NN1 legislation_NN1 affects_VVZ corporate_JJ governance_NN1 as_II a_AT1 whole_NN1 ._. 
</s>
<s>
The_AT aim_NN1 of_IO the_AT paper_NN1 is_VBZ to_TO determine_VVI how_RRQ changes_NN2 in_II the_AT legislation_NN1 would_VM affect_VVI corporate_JJ policies_NN2 and_CC practices_NN2 in_II the_AT top_JJ management_NN1 ,_, and_CC how_RGQ different_JJ shareholder_NN1 clienteles_NN2 would_VM utilize_VVI potential_NN1 inside_II information_NN1 that_CST more_RGR or_CC less_RGR directly_RR would_VM be_VBI conveyed_VVN from_II the_AT managers_NN2 ._. 
</s>
<s>
The_AT paper_NN1 focuses_VVZ on_II economies_NN2 using_VVG a_AT1 civil-law_NN1 system_NN1 ,_, and_CC as_CSA such_DA considerable_JJ similarities_NN2 with_IW the_AT Nordic_JJ countries_NN2 and_CC more_RGR specifically_RR Finlands_NP2 investor_NN1 behavior_NN1 are_VBR expected_VVN ._. 
</s>
<s>
A_AT1 major_JJ difference_NN1 between_II EU_NP1 and_CC US_NP1 legislative_JJ systems_NN2 that_CST Maug_NP1 finds_VVZ ,_, is_VBZ that_DD1 whereas_CS the_AT SEC_NP1 rules_NN2 in_II the_AT US_NP1 do_VD0 not_XX clearly_RR define_VVI shareholders_NN2 as_CSA potential_JJ tippees_NN2 utilizing_VVG indirect_JJ information_NN1 ,_, the_AT European_JJ legislation_NN1 is_VBZ more_RGR comprehensive_JJ by_II including_VVG dominant_JJ shareholders_NN2 in_II the_AT insider_NN1 register_NN1 ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 ,_, EU_NP1 legislation_NN1 is_VBZ not_XX as_RG specific_JJ when_CS it_PPH1 comes_VVZ to_II defining_VVG what_DDQ is_VBZ inside_JJ information_NN1 as_II the_AT US_NP1 ._. 
</s>
<s>
The_AT results_NN2 of_IO the_AT paper_NN1 clearly_RR indicate_VV0 that_DD1 given_VVN a_AT1 scenario_NN1 of_IO lacking_VVG statutory_JJ intervention_NN1 ,_, the_AT managers_NN2 will_VM together_RL with_IW the_AT major_JJ dominant_JJ shareholders_NN2 form_VV0 what_DDQ Maug_NP1 refers_VVZ to_II as_II a_AT1 cozy_JJ cartel_NN1 :_: an_AT1 agreement_NN1 from_II which_DDQ both_RR involved_VVN parties_NN2 benefit_VV0 at_II the_AT expense_NN1 of_IO minor_JJ shareholders_NN2 ._. 
</s>
<s>
The_AT argument_NN1 ,_, Maug_NP1 claims_VVZ ,_, relies_VVZ on_II the_AT liquidity_NN1 of_IO the_AT markets_NN2 ,_, and_CC on_II the_AT shareholder_NN1 with_IW access_NN1 to_II inside_JJ information_NN1 being_VBG more_RGR concerned_JJ about_II the_AT trading_NN1 profits_NN2 than_CSN on_II a_AT1 long-run_JJ return_NN1 on_II the_AT initial_JJ investment_NN1 ._. 
</s>
<s>
The_AT management_NN1 of_IO the_AT corporation_NN1 would_VM in_II turn_VVI get_VV0 their_APPGE gains_NN2 in_II the_AT shape_NN1 of_IO freedom_NN1 to_TO act_VVI :_: if_CS the_AT dominant_JJ shareholders_NN2 are_VBR after_II trading_VVG profits_NN2 ,_, the_AT executives_NN2 are_VBR free_JJ to_TO do_VDI whatever_DDQV they_PPHS2 like_VV0 ._. 
</s>
<s>
Moreover_RR ,_, the_AT author_NN1 claims_VVZ that_CST if_CS inside_II trading_NN1 was_VBDZ to_TO be_VBI legalized_VVN ,_, a_AT1 way_NN1 to_TO reduce_VVI the_AT harmful_JJ effects_NN2 could_VM be_VBI increased_JJ transparency_NN1 of_IO larger_JJR individual_JJ trades_NN2 ._. 
</s>
<s>
The_AT problem_NN1 is_VBZ ,_, however_RR ,_, that_CST the_AT major_JJ shareholders_NN2 interest_NN1 in_II monitoring_NN1 would_VM still_RR be_VBI reduced_VVN at_II the_AT expense_NN1 of_IO smaller_JJR investors_NN2 ._. 
</s>
<s>
To_TO sum_VVI up_RP Maugs_NP1 findings_NN2 it_PPH1 can_VM be_VBI noted_VVN that_CST in_II a_AT1 civil-law_NN1 country_NN1 like_II Finland_NP1 ,_, average_JJ shareholders_NN2 will_VM suffer_VVI from_II legalized_JJ insider_NN1 trading_NN1 ._. 
</s>
<s>
In_II a_AT1 sense_NN1 efficiency_NN1 on_II the_AT market_NN1 increases_VVZ as_CSA information_NN1 sooner_RRR is_VBZ reflected_VVN in_II the_AT share_NN1 price_NN1 ,_, but_CCB simultaneously_RR the_AT lack_NN1 of_IO monitoring_NN1 would_VM reduce_VVI the_AT overall_JJ operational_JJ efficiency_NN1 of_IO corporations_NN2 ._. 
</s>
<s>
As_II a_AT1 result_NN1 then_RT ,_, not_XX only_RR uninformed_JJ shareholders_NN2 suffer_VV0 ,_, but_CCB even_RR employees_NN2 of_IO the_AT corporation_NN1 and_CC other_JJ stakeholders_NN2 are_VBR put_VVN in_II a_AT1 disadvantageous_JJ position_NN1 whereby_RRQ the_AT society_NN1 as_II a_AT1 whole_NN1 suffers_VVZ ._. 
</s>
<s>
Insider_NN1 Trading_VVG The_AT Finnish_JJ legislative_JJ system_NN1 Insider_NN1 trading_NN1 has_VHZ in_II Finland_NP1 been_VBN regulated_VVN since_II 1989_MC by_II both_DB2 the_AT Finnish_JJ law_NN1 and_CC the_AT rules_NN2 and_CC regulations_NN2 of_IO the_AT OMXH_NN1 stock_NN1 exchange_NN1 ._. 
</s>
<s>
(_( finlex.fi_NNU )_) In_II this_DD1 section_NN1 of_IO the_AT paper_NN1 ,_, the_AT nature_NN1 of_IO these_DD2 regulations_NN2 is_VBZ discussed_VVN in_II detail_NN1 ,_, additionally_RR focusing_VVG on_II differences_NN2 in_II legislative_JJ systems_NN2 such_II21 as_II22 civil-_NN1 vs._II common_JJ law_NN1 ._. 
</s>
<s>
Who_PNQS is_VBZ an_AT1 insider_NN1 ?_? 
</s>
<s>
Any_DD person_NN1 holding_VVG unpublished_JJ information_NN1 that_CST can_VM be_VBI assumed_VVN to_TO have_VHI a_AT1 significant_JJ effect_NN1 on_II a_AT1 companys_NN2 share_NN1 price_NN1 is_VBZ considered_VVN an_AT1 insider_NN1 ,_, to_II which_DDQ the_AT insider_NN1 trading_NN1 regulations_NN2 apply_VV0 ._. 
</s>
<s>
Additionally_RR ,_, persons_NN2 in_II the_AT following_JJ positions_NN2 are_VBR permanent_JJ insiders_NN2 :_: -The_AT managing_JJ director_NN1 and_CC his/her_APPGE deputy_NN1 -Members_NN2 of_IO the_AT supervisory_JJ board_NN1 -Persons_NN2 in_II the_AT management_NN1 with_IW regular_JJ access_NN1 to_II inside_JJ information_NN1 -The_AT companys_NN2 auditor_NN1 ,_, deputy_NN1 auditor_NN1 ,_, and_CC audit_NN1 company_NN1 manager_NN1 In_RR21 addition_RR22 ,_, persons_NN2 within_II the_AT organization_NN1 that_CST through_II their_APPGE work_NN1 receive_VV0 sensitive_JJ information_NN1 are_VBR insiders_NN2 ._. 
</s>
<s>
This_DD1 even_RR includes_VVZ hired_JJ personnel_NN2 working_VVG on_II temporary_JJ projects_NN2 ,_, e.g._REX consultants_NN2 or_CC attorneys_NN2 ._. 
</s>
<s>
(_( OMXH_NP1 guidelines_NN2 for_IF insiders_NN2 )_) Known_JJ cases_NN2 of_IO illegal_JJ insider_NN1 trading_NN1 in_II Finland_NP1 In_II this_DD1 section_NN1 of_IO the_AT paper_NN1 court_NN1 rulings_NN2 on_II abused_JJ inside_II information_NN1 are_VBR presented_VVN ._. 
</s>
<s>
These_DD2 include_VV0 :_: Jouko_NP1 K_NP1 Leskinen_NP1 2003_MC Timo_NP1 Jouhki_NP1 2006_MC TJ_NP1 Group_NN1 2009_MC LSO_NP1 Osuuskunta_NP1 2010_MC Discussion_NN1 Based_VVN on_II previous_JJ research_NN1 and_CC the_AT value_NN1 destruction_NN1 done_VDN to_II minority_NN1 investors_NN2 by_II corporate_JJ insiders_NN2 ,_, it_PPH1 is_VBZ hard_JJ to_TO find_VVI real_JJ motivations_NN2 for_IF legalizing_VVG insider_NN1 trading_NN1 ._. 
</s>
<s>
Moreover_RR ,_, investors_NN2 are_VBR not_XX the_AT only_JJ stakeholders_NN2 that_CST were_VBDR to_TO suffer_VVI as_RG capital_JJ markets_NN2 lose_VV0 liquidity_NN1 ;_; employees_NN2 would_VM become_VVI worse_RRR off_RP ,_, eventually_RR harming_VVG the_AT whole_JJ society_NN1 ._. 
</s>
