<s>
Corporate_JJ governance_NN1 and_CC takeovers_NN2 :_: Is_VBZ corporate_JJ governance_NN1 value_NN1 destructive_JJ in_II the_AT bidder_NN1 company_NN1 ?_? 1_MC1 ._. 
</s>
<s>
Introduction_NN1 Despite_II the_AT short-term_JJ decrease_NN1 in_II mergers_NN2 &;_NULL acquisitions_NN2 ,_, this_DD1 market_NN1 is_VBZ on_II a_AT1 long-term_JJ growth_NN1 trend_NN1 ._. 
</s>
<s>
When_CS organic_JJ growth_NN1 is_VBZ foreseen_VVN ,_, M_ZZ1 &A;_NULL activity_NN1 is_VBZ the_AT most_RGT relevant_JJ growth_NN1 path_NN1 for_IF growing_JJ companies_NN2 ._. 
</s>
<s>
This_DD1 ,_, among_II other_JJ things_NN2 ,_, builds_VVZ interest_NN1 towards_II M_MC &A;_NULL studies_NN2 ._. 
</s>
<s>
Empirical_JJ evidence_NN1 show_NN1 ,_, that_CST even_CS21 though_CS22 takeovers_NN2 are_VBR value-creating_JJ ,_, the_AT stock-performance_NN1 for_IF takeover_NN1 bidders_NN2 ,_, and_CC in_II many_DA2 case_NN1 takeover_NN1 target_NN1 ,_, is_VBZ negative_JJ ._. 
</s>
<s>
One_MC1 reason_NN1 for_IF this_DD1 might_VM be_VBI that_CST the_AT stock-performance_NN1 of_IO the_AT involved_JJ companies_NN2 are_VBR affected_VVN by_II external_JJ factors_NN2 ._. 
</s>
<s>
Barik_NP1 (_( 2012_MC )_) show_VV0 that_CST for_REX21 instance_REX22 takeover_NN1 defenses_NN2 impacts_NN2 the_AT value-creation_NN1 in_II the_AT takeover_NN1 event_NN1 ._. 
</s>
<s>
What_DDQ is_VBZ destroying_VVG the_AT value_NN1 in_II M_ZZ1 &A?;_NULL Meanwhile_RR ,_, there_EX has_VHZ been_VBN a_AT1 wide_JJ interest_NN1 towards_II the_AT corporate_JJ governance_NN1 mechanism_NN1 in_II companies_NN2 ,_, due_II21 to_II22 the_AT value_NN1 creating_VVG effect_NN1 of_IO it_PPH1 ._. 
</s>
<s>
Corporate_JJ governance_NN1 can_VM be_VBI seen_VVN as_II a_AT1 hot_JJ topic_NN1 in_II todays_NN2 academic_JJ research_NN1 ._. 
</s>
<s>
Previous_JJ research_NN1 focuses_VVZ on_II the_AT impact_NN1 of_IO external_JJ factor_NN1 on_II the_AT value-_NN1 creating_VVG process_NN1 of_IO takeovers_NN2 ,_, but_CCB few_DA2 studies_NN2 focuses_VVZ on_II the_AT corporate_JJ governance_NN1 aspect_NN1 of_IO the_AT deal_NN1 ._. 
</s>
<s>
There_EX are_VBR many_DA2 different_JJ fields_NN2 of_IO studies_NN2 within_II takeover_NN1 studies_NN2 ;_; many_DA2 studies_NN2 focus_VV0 on_II the_AT stock-_JJ performance_NN1 of_IO the_AT bidder_NN1 and/or_CC the_AT target_NN1 company_NN1 (_( (_( Servaes_NP2 ,_, 2012_MC )_) (_( McConnell_NP1 ,_, 2012_MC )_) )_) ,_, while_CS others_NN2 on_II the_AT tax_NN1 implications_NN2 of_IO acquisition_NN1 (_( Ryngaert_NP1 ,_, 2012_MC )_) and_CC the_AT rest_NN1 on_II optimal_JJ financing_NN1 structure_NN1 of_IO the_AT takeover_NN1 (_( Morellec_NP1 &;_NULL Zhdanov_NP1 ,_, 2008_MC )_) As_II a_AT1 result_NN1 ,_, no_AT comprehensive_JJ theory_NN1 appears_VVZ to_TO exist_VVI on_RP how_RGQ corporate_JJ governance_NN1 affects_VVZ the_AT value-creation_NN1 at_II the_AT event_NN1 of_IO takeovers_NN2 ._. 
</s>
<s>
The_AT question_NN1 remains_VVZ ,_, has_VHZ previous_JJ studies_NN2 focused_VVD too_RG much_DA1 on_II the_AT external_JJ factor_NN1 implications_NN2 in_II takeover_NN1 events_NN2 ,_, and_CC foreseen_VVN the_AT internal_JJ factor_NN1 implications_NN2 at_II these_DD2 events_NN2 ?_? 
</s>
<s>
This_DD1 study_NN1 focuses_VVZ on_II the_AT bidder_NN1 in_II takeovers_NN2 ,_, and_CC classifying_VVG them_PPHO2 in_II successful_JJ and_CC unsuccessful_JJ ,_, based_VVN on_II the_AT bidders_NN2 '_GE stock-performance_NN1 ._. 
</s>
<s>
There_RL after_II the_AT paper_NN1 will_VM try_VVI to_TO study_VVI if_CSW differences_NN2 in_II corporate_JJ governance_NN1 principals_NN2 have_VH0 had_VHN a_AT1 significant_JJ impact_NN1 on_II the_AT stock-performance_NN1 ._. 
</s>
<s>
I.e._REX this_DD1 paper_NN1 hopes_VVZ to_TO show_VVI that_CST there_RL ,_, in_II fact_NN1 ,_, is_VBZ a_AT1 correlation_NN1 between_II the_AT stock-performance_NN1 of_IO the_AT bidder_NN1 after_II the_AT initial_JJ announcement_NN1 of_IO a_AT1 takeover_NN1 and_CC some_DD specific_JJ corporate_JJ governance_NN1 principles_NN2 in_II the_AT same_DA company_NN1 ._. 
</s>
<s>
The_AT reminder_NN1 of_IO this_DD1 paper_NN1 is_VBZ divided_VVN into_II six_MC sections_NN2 ._. 
</s>
<s>
First_MD ,_, the_AT paper_NN1 introduces_VVZ key_JJ concepts_NN2 and_CC theories_NN2 of_IO corporate_JJ governance_NN1 and_CC takeover_NN1 theory_NN1 ._. 
</s>
<s>
Secondly_RR ,_, a_AT1 literature_NN1 review_NN1 is_VBZ conducted_VVN to_TO create_VVI an_AT1 academic_JJ background_NN1 for_IF this_DD1 study_NN1 ._. 
</s>
<s>
After_CS this_DD1 ,_, a_AT1 description_NN1 of_IO the_AT data_NN in_II the_AT study_NN1 is_VBZ presented_VVN ._. 
</s>
<s>
Then_RT the_AT method_NN1 and_CC the_AT results_NN2 are_VBR presented_VVN ._. 
</s>
<s>
The_AT paper_NN1 ends_VVZ with_IW a_AT1 discussion_NN1 around_II the_AT main_JJ findings_NN2 and_CC how_RRQ these_DD2 relate_VV0 to_II previous_JJ research._NNU 2_MC ._. 
</s>
<s>
Theoretical_JJ framework_NN1 2.1_MC ._. 
</s>
<s>
Corporate_JJ governance_NN1 Corporate_JJ governance_NN1 is_VBZ one_MC1 of_IO the_AT cornerstones_NN2 of_IO corporate_JJ finance_NN1 and_CC the_AT theory_NN1 have_VH0 been_VBN studied_VVN thoroughly_RR (_( Cadbury_NP1 ,_, 1992_MC ;_; Claessens_NN2 ;_; Djankov_NP1 ;_; &;_NULL Lang_NP1 ;_; Clarke_NP1 ,_, 2007_MC ;_; Khalid_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
The_AT main_JJ reason_NN1 why_RRQ companies_NN2 need_VV0 to_TO think_VVI about_II corporate_JJ governance_NN1 is_VBZ agency_NN1 theory_NN1 ._. 
</s>
<s>
Basically_RR ,_, the_AT theory_NN1 assumes_VVZ that_CST managers_NN2 with_IW substantial_JJ freedom_NN1 act_NN1 more_RGR likely_JJ in_II ways_NN2 that_CST improves_VVZ their_APPGE own_DA interest_NN1 instead_II21 of_II22 the_AT shareholders_NN2 interest_NN1 ._. 
</s>
<s>
Therefore_RR ,_, without_IW appropriate_JJ corporate_JJ governance_NN1 mechanism_NN1 the_AT company_NN1 is_VBZ lead_VVN inefficiently_RR and_CC firm_JJ value_NN1 is_VBZ destroyed_VVN ._. 
</s>
<s>
(_( Sheraz_VV0 ,_, 2009_MC )_) 2.1.1_MC ._. 
</s>
<s>
Agency_NN1 Theory_NN1 Agency_NN1 theory_NN1 ,_, introduced_VVN by_II Jensen_NP1 and_CC Meckling_VVG in_II 1976_MC in_II their_APPGE article_NN1 "_" Theory_NN1 of_IO the_AT Firm_NN1 :_: managerial_JJ Behavior_NN1 ,_, Agency_NN1 Costs_NN2 and_CC Ownership_NN1 Structure_NN1 "_" ,_, sees_VVZ a_AT1 firms_NN2 as_II a_AT1 legal_JJ entity_NN1 that_CST serves_VVZ as_II a_AT1 connection_NN1 point_NN1 between_II different_JJ individuals_NN2 ._. 
</s>
<s>
A_AT1 contract_NN1 combines_VVZ these_DD2 individuals_NN2 ,_, under_II which_DDQ individual_NN1 (_( principal_NN1 )_) engages_VVZ another_DD1 individual_NN1 (_( agent_NN1 )_) take_VV0 decisions_NN2 on_II31 behalf_II32 of_II33 him_PPHO1 ._. 
</s>
<s>
Therefore_RR ,_, the_AT principal_NN1 must_VM align_VVI the_AT agents_NN2 '_GE incentives_NN2 to_II those_DD2 of_IO himself_PPX1 ,_, so_CS21 that_CS22 resources_NN2 are_VBR not_XX wasted_VVN on_II unattractive_JJ projects_NN2 ._. 
</s>
<s>
This_DD1 issue_NN1 is_VBZ called_VVN "_" the_AT agency_NN1 problem_NN1 "_" ._. 
</s>
<s>
Agency_NN1 theory_NN1 can_VM also_RR be_VBI defined_VVN as_II the_AT problem_NN1 arising_VVG when_RRQ management_NN1 and_CC finance_NN1 is_VBZ separated_VVN ,_, or_CC ownership_NN1 and_CC control_NN1 as_CSA it_PPH1 can_VM also_RR be_VBI referred_VVN ._. 
</s>
<s>
The_AT problem_NN1 is_VBZ created_VVN when_CS ownership_NN1 and_CC control_NN1 is_VBZ not_XX aligned_VVN and_CC there_EX is_VBZ conflict_NN1 of_IO interest_NN1 ._. 
</s>
<s>
These_DD2 conflicts_NN2 of_IO interest_NN1 ,_, together_RL with_IW imperfect_JJ contracts_NN2 and_CC inefficient_JJ monitoring_NN1 of_IO controllers_NN2 ,_, eventually_RR cause_VV0 a_AT1 decrease_NN1 in_II firm_JJ value_NN1 ._. 
</s>
<s>
Furthermore_RR ,_, lots_PN of_IO small_JJ stakeholders_NN2 with_IW limited_JJ negotiation_NN1 or_CC monitoring_VVG resources_NN2 increases_VVZ conflict_NN1 of_IO interest_NN1 ._. 
</s>
<s>
Agency_NN1 theory_NN1 can_VM further_RRR be_VBI divided_VVN in_II two_MC parts_NN2 ;_; moral_JJ hazard_NN1 and_CC adverse_JJ selection_NN1 ._. 
</s>
<s>
(_( Sheraz_VV0 ,_, 2009_MC )_) In_II moral_JJ hazard_NN1 the_AT company_NN1 management_NN1 uses_VVZ its_APPGE position_NN1 to_TO secure_VVI personal_JJ benefit_NN1 in_II cost_NN1 of_IO the_AT principals_NN2 ._. 
</s>
<s>
Moral_JJ hazard_NN1 is_VBZ prevented_VVN by_II eliminating_VVG information_NN1 symmetry_NN1 and_CC increasing_JJ external_JJ monitoring_NN1 mechanism_NN1 ._. 
</s>
<s>
(_( Arrow_NN1 ,_, 1965_MC )_) Adverse_JJ selection_NN1 is_VBZ a_AT1 problem_NN1 when_RRQ people_NN utilize_VV0 their_APPGE person_NN1 information_NN1 to_TO achieve_VVI personal_JJ benefits_NN2 ._. 
</s>
<s>
Risk_VV0 sharing_VVG ,_, which_DDQ minimized_VVD benefits_NN2 from_II cheating_VVG ,_, and_CC information_NN1 sharing_VVG ,_, which_DDQ reveals_VVZ information_NN1 now_RT public_JJ ,_, decreases_VVZ the_AT risk_NN1 of_IO adverse_JJ selection_NN1 ._. 
</s>
<s>
(_( Akerlof_VV0 ,_, 1970_MC )_) In_II this_DD1 study_NN1 ,_, agency_NN1 problem_NN1 arises_VVZ at_II the_AT merger_NN1 or_CC acquisition_NN1 situation_NN1 ._. 
</s>
<s>
Management_NN1 influences_NN2 highly_RR on_II the_AT probability_NN1 of_IO success_NN1 for_IF a_AT1 merger_NN1 or_CC acquisition._NNU 2.1.2_MC ._. 
</s>
<s>
Corporate_JJ governance_NN1 mechanisms_NN2 Corporate_JJ governance_NN1 mechanisms_NN2 limit_VV0 the_AT value_NN1 destruction_NN1 of_IO agency_NN1 problem_NN1 ._. 
</s>
<s>
The_AT mechanism_NN1 can_VM further_RRR divide_VVI in_II two_MC main_JJ groups_NN2 ;_; internal_JJ control_NN1 mechanism_NN1 and_CC external_JJ control_NN1 mechanism_NN1 ._. 
</s>
<s>
(_( Sheraz_VV0 ,_, 2009_MC )_) 2.1.2.1_MC ._. 
</s>
<s>
Internal_JJ control_NN1 mechanism_NN1 Internal_JJ control_NN1 mechanism_NN1 can_VM further_RRR be_VBI divided_VVN in_II several_DA2 sub-categories_NN2 ;_; Monitoring_NN1 by_II the_AT board_NN1 ,_, Internal_JJ control_NN1 procedures_NN2 and_CC internal_JJ auditors_NN2 ,_, entrenchment_NN1 and_CC incentive_NN1 alignment_NN1 ,_, and_CC ownership_NN1 structure_NN1 ._. 
</s>
<s>
(_( Sheraz_VV0 ,_, 2009_MC )_) Because_CS the_AT focus_NN1 of_IO this_DD1 paper_NN1 is_VBZ on_II the_AT external_JJ control_NN1 mechanism_NN1 ,_, the_AT paper_NN1 only_RR focuses_VVZ on_II two_MC sub-categories_NN2 in_II the_AT following_JJ to_TO give_VVI an_AT1 overview_NN1 of_IO the_AT internal_JJ control_NN1 mechanism_NN1 ._. 
</s>
<s>
These_DD2 are_VBR the_AT monitoring_NN1 by_II the_AT board_NN1 and_CC ownership_NN1 structure_NN1 ._. 
</s>
<s>
The_AT internal_JJ control_NN1 mechanism_NN1 the_AT board_NN1 of_IO directors_NN2 beholds_VVZ has_VHZ been_VBN studied_VVN widely_RR (_( Baysinger_NP1 &;_NULL Butler_NP1 ,_, 1985_MC ;_; Beasley_NP1 ,_, 1996_MC ;_; Hopt_NP1 &;_NULL Leyens_NP1 ,_, 2004_MC ;_; Bhagat_NP1 &;_NULL Black_NP1 ,_, 1999_MC )_) ._. 
</s>
<s>
The_AT board_NN1 of_IO directors_NN2 '_GE main_JJ task_NN1 is_VBZ to_TO supervise_VVI the_AT top_JJ management_NN1 ._. 
</s>
<s>
The_AT board_NN1 of_IO directors_NN2 create_VV0 and_CC incentive_NN1 to_II the_AT top_JJ management_NN1 to_TO perform_VVI well_RR ,_, because_CS otherwise_RR they_PPHS2 are_VBR able_JK to_TO fire_VVI the_AT current_JJ management_NN1 and_CC hire_VVI new_JJ management_NN1 instead_RR ._. 
</s>
<s>
The_AT board_NN1 of_IO directors_NN2 has_VHZ access_NN1 to_II all_DB company_NN1 related_JJ information_NN1 and_CC can_VM therefor_RR act_VVI efficiently_RR ._. 
</s>
<s>
(_( Bhagat_VV0 &;_NULL Black_JJ ,_, 1999_MC )_) Ownership_NN1 structure_NN1 is_VBZ another_DD1 internal_JJ control_NN1 mechanism_NN1 and_CC has_VHZ been_VBN studied_VVN thoroughly_RR (_( Xu_NP1 &;_NULL Wang_NP1 ,_, 1999_MC ;_; Shivdasani_NP1 ,_, 1993_MC ;_; Singh_NP1 &;_NULL Davidson_NP1 ,_, 2003_MC )_) ._. 
</s>
<s>
Shareholder_NN1 that_CST own_DA a_AT1 5_MC %_NNU or_CC more_RRR in_II the_AT company_NN1 are_VBR major_JJ shareholders_NN2 ._. 
</s>
<s>
For_REX21 instance_REX22 ,_, In_II Finland_NP1 ,_, public_JJ companies_NN2 are_VBR forced_VVN to_TO inform_VVI the_AT public_NN1 if_CS their_APPGE shareholding_NN1 exceeds_VVZ this_DD1 percent_NNU (_( Finanssivalvonta_NP1 ,_, 2007_MC )_) ._. 
</s>
<s>
An_AT1 individual_JJ shareholder_NN1 that_CST owns_VVZ large_JJ percent_NNU of_IO company_NN1 is_VBZ able_JK to_TO misuse_VVI its_APPGE ownership_NN1 power_NN1 to_TO benefit_VVI on_II the_AT cost_NN1 of_IO others_NN2 ._. 
</s>
<s>
Furthermore_RR ,_, the_AT ownership_NN1 structure_NN1 impact_NN1 on_II the_AT monitoring_NN1 of_IO the_AT company_NN1 a_AT1 wide_JJ range_NN1 of_IO owners_NN2 ,_, not_XX too_RG many_DA2 and_CC not_XX too_RG few_DA2 ,_, is_VBZ the_AT desirable_JJ structure_NN1 ._. 
</s>
<s>
This_DD1 structure_NN1 enhances_VVZ the_AT monitoring_NN1 of_IO corporate_JJ action_NN1 and_CC increase_VV0 firm_JJ value_NN1 ._. 
</s>
<s>
(_( Shleifer_NP1 &;_NULL Vishny_NP1 ,_, 1997_MC )_) 2.1.2.2_MC ._. 
</s>
<s>
External_JJ control_NN1 mechanism_NN1 The_AT external_JJ control_NN1 mechanism_NN1 can_VM be_VBI divided_VVN in_II three_MC different_JJ categories_NN2 ;_; the_AT takeover_NN1 market_NN1 ,_, product_NN1 market_NN1 competition_NN1 and_CC legal_JJ and_CC regulatory_JJ framework_NN1 ._. 
</s>
<s>
(_( Sheraz_VV0 ,_, 2009_MC )_) In_II this_DD1 study_NN1 ,_, the_AT main_JJ focus_NN1 is_VBZ on_II the_AT takeover_NN1 mechanism_NN1 and_CC therefor_RR this_DD1 part_NN1 gets_VVZ special_JJ attention_NN1 ._. 
</s>
<s>
Product_NN1 market_NN1 competition_NN1 is_VBZ not_XX discussed_VVN ._. 
</s>
<s>
The_AT legal_JJ and_CC regulatory_JJ framework_NN1 of_IO a_AT1 country_NN1 builds_VVZ the_AT basic_JJ pillars_NN2 of_IO corporate_JJ governance_NN1 ._. 
</s>
<s>
Without_IW a_AT1 working_JJ legal_JJ and_CC regulatory_JJ system_NN1 corporations_NN2 can_VM not_XX operate_VVI efficiently_RR ._. 
</s>
<s>
Corporate_JJ governance_NN1 is_VBZ determined_VVN basically_RR by_II the_AT level_NN1 the_AT country_NN1 monitor_NN1 investor_NN1 rights_NN2 and_CC enforces_VVZ those_DD2 laws_NN2 ._. 
</s>
<s>
(_( (_( La_NP1 Porta_NP1 ;_; Lopez-De-Silanes_NP1 ;_; &;_NULL Schelifer_NP1 ,_, 2002_MC )_) ._. 
</s>
<s>
La_NP1 Porta_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
also_RR show_VV0 that_CST a_AT1 better_JJR legal_JJ protection_NN1 leads_VVZ investors_NN2 to_TO demand_VVI lower_JJR expected_JJ rate_NN1 of_IO returns_NN2 ,_, resulting_VVG in_II more_RGR efficient_JJ capital_NN1 markets._NNU 2.1.2.2.1_MC ._. 
</s>
<s>
Hostile_JJ takeovers_NN2 A_ZZ1 vast_JJ amount_NN1 of_IO theory_NN1 and_CC evidence_NN1 support_VV0 the_AT idea_NN1 of_IO takeovers_NN2 as_CSA control_NN1 mechanism_NN1 (_( (_( Holmstrm_NP1 &;_NULL Kaplan_NP1 ,_, 2001_MC ;_; Shleifer_NP1 &;_NULL Vishny_NP1 ,_, 1997_MC ;_; Manne_NP1 ,_, 1965_MC ;_; Cyert_NP1 &;_NULL Kang_NP1 ,_, 2002_MC )_) ._. 
</s>
<s>
Jensen_NP1 and_CC Ruback_NP1 (_( 1984_MC )_) points_VVZ out_RP the_AT most_RGT important_JJ point_NN1 in_II takeovers_NN2 :_: "_" takeovers_NN2 typically_RR increase_VV0 the_AT combined_JJ value_NN1 of_IO the_AT target_NN1 and_CC acquiring_VVG firm_NN1 ,_, indicating_VVG that_CST profits_NN2 are_VBR expected_VVN to_TO increase_VVI afterwards_RT "_" ._. 
</s>
<s>
Jensen_NP1 (_( 1986_MC )_) further_RRR claims_VVZ that_CST takeovers_NN2 solve_VV0 the_AT free_JJ cash_NN1 flow_NN1 problem_NN1 in_II target_NN1 companies_NN2 ,_, because_CS takeovers_NN2 usually_RR lead_VV0 to_II distribution_NN1 of_IO the_AT firm_NN1 's_GE profits_NN2 to_II investors_NN2 over_II time_NNT1 ._. 
</s>
<s>
Usually_RR ,_, the_AT target_NN1 is_VBZ performing_VVG poorly_JJ and_CC the_AT management_NN1 is_VBZ often_RR removed_VVN after_II the_AT takeover_NN1 ._. 
</s>
<s>
(_( Shleifer_NP1 &;_NULL Vishny_NP1 ,_, 1997_MC )_) All-in-all_DB ,_, takeovers_NN2 are_VBR seen_VVN as_II a_AT1 crucial_JJ corporate_JJ governance_NN1 mechanism_NN1 to_TO control_VVI managerial_JJ discretion_NN1 ._. 
</s>
<s>
(_( Easterbrook_NP1 &;_NULL Fischel_NP1 ,_, 1991_MC )_) Generally_RR ,_, takeovers_NN2 are_VBR seen_VVN as_II an_AT1 efficient_JJ external_JJ control_NN1 mechanism_NN1 ,_, but_CCB some_DD specific_JJ questions_NN2 should_VM be_VBI remembered_VVN when_RRQ takeovers_NN2 are_VBR considered_VVN as_CSA control_NN1 mechanisms_NN2 ._. 
</s>
<s>
First_MD ,_, acquisitions_NN2 are_VBR expensive_JJ and_CC therefore_RR only_JJ mayor_NN1 failures_NN2 are_VBR likely_JJ to_TO be_VBI addressed_VVN ._. 
</s>
<s>
Secondly_RR ,_, acquisition_NN1 might_VM unbalance_VVI the_AT ownership_NN1 structure_NN1 and_CC increase_NN1 agency_NN1 costs_NN2 ._. 
</s>
<s>
Thirdly_RR ,_, acquisitions_NN2 require_VV0 liquid_JJ capital_NN1 markets_NN2 that_CST are_VBR not_XX given_VVN ._. 
</s>
<s>
Without_IW liquid_JJ capital_NN1 markets_NN2 the_AT acquirer_NN1 is_VBZ unable_JK to_TO gather_VVI necessary_JJ capital_NN1 ._. 
</s>
<s>
Finally_RR ,_, acquisitions_NN2 are_VBR influenced_VVN by_II political_JJ mechanism_NN1 ,_, which_DDQ can_VM hinder_VVI an_AT1 acquisition_NN1 process_NN1 ._. 
</s>
<s>
Connection_NN1 with_IW our_APPGE research_NN1 2.2_MC ._. 
</s>
<s>
Mergers_NN2 and_CC acquisitions_NN2 Its_APPGE evident_JJ from_II the_AT wide_JJ range_NN1 of_IO current_JJ research_NN1 (_( Schmid_NP1 ;_; Carol_NP1 ;_; &;_NULL Sanchez_NP1 ,_, 2012_MC ;_; Caiazza_NP1 ;_; Clare_NP1 ;_; &;_NULL Alberto_NP1 ,_, 2012_MC ;_; Sumon_NP1 &;_NULL Ekta_NP1 ,_, 2012_MC )_) that_CST mergers_NN2 and_CC acquisition_NN1 is_VBZ a_AT1 hot_JJ topic_NN1 in_II corporate_JJ finance_NN1 these_DD2 days._NNU 2.2.1_MC ._. 
</s>
<s>
Motives_NN2 behind_II acquisition_NN1 Muller_NP1 &;_NULL Sirower_NP1 (_( 2003_MC )_) researched_VVN extensively_RR different_JJ reasons_NN2 for_IF acquisitions_NN2 ._. 
</s>
<s>
Their_APPGE main_JJ findings_NN2 can_VM be_VBI divided_VVN in_II four_MC categories_NN2 ;_; market_VV0 for_IF corporate_JJ control_NN1 hypothesis_NN1 ,_, managerial_JJ discretion_NN1 hypothesis_NN1 ,_, synergy_NN1 hypothesis_NN1 and_CC hubris_NN1 hypothesis_NN1 ._. 
</s>
<s>
In_II following_VVG the_AT paper_NN1 address_NN1 the_AT corporate_JJ control-_NN1 ,_, synergy-_JJ and_CC hubris_NN1 hypothesis_NN1 ._. 
</s>
<s>
Manne_NP1 (_( 1965_MC )_) invented_VVD the_AT term_NN1 "_" market_NN1 for_IF corporate_JJ control_NN1 "_" that_CST created_VVD the_AT hypothesis_NN1 that_CST markets_NN2 operated_VVN efficiently_RR to_TO eliminate_VVI managers_NN2 who_PNQS wanted_VVD to_TO achieve_VVI goals_NN2 that_CST conflicted_VVD shareholder_NN1 interest_NN1 or_CC were_VBDR incompetent_JJ to_II the_AT task_NN1 ._. 
</s>
<s>
The_AT basic_JJ assumption_NN1 for_IF the_AT hypothesis_NN1 is_VBZ that_CST any_DD firm_NN1 can_VM capture_VVI the_AT potential_JJ gain_NN1 by_II reversing_VVG the_AT inefficient_JJ policies_NN2 of_IO the_AT target_NN1 company_NN1 ._. 
</s>
<s>
Another_DD1 reason_NN1 for_IF acquisition_NN1 is_VBZ synergies_NN2 ._. 
</s>
<s>
Berkovitch_VV0 &;_NULL Narayanan_NP1 (_( 1993_MC )_) identify_VV0 synergies_NN2 to_TO be_VBI the_AT reasoning_NN1 behind_II acquisition_NN1 when_CS two_MC companies_NN2 combined_VVN generate_VV0 efficiencies_NN2 due_II21 to_II22 some_DD sort_NN1 of_IO market_NN1 power_NN1 increase_NN1 or_CC cost_NN1 reduction_NN1 ._. 
</s>
<s>
Under_II this_DD1 assumption_NN1 both_DB2 companies_NN2 realizes_VVZ some_DD of_IO the_AT benefits_NN2 associated_VVN in_II the_AT acquisition_NN1 ._. 
</s>
<s>
Finally_RR ,_, the_AT hubris_NN1 hypothesis_NN1 bases_NN2 on_II irrational_JJ behavior_NN1 ._. 
</s>
<s>
A_AT1 "_" winner_NN1 's_GE course_NN1 "_" arises_VVZ in_II auction_NN1 because_CS the_AT person_NN1 with_IW the_AT largest_JJT error_NN1 in_II its_APPGE assumptions_NN2 will_VM win_VVI the_AT auction_NN1 ._. 
</s>
<s>
I.e._REX the_AT bidder_NN1 company_NN1 might_VM be_VBI incompetent_JJ in_II evaluating_VVG acquisition_NN1 benefits_NN2 and_CC therefor_RR engaging_VVG in_II unattractive_JJ M_NN1 &A;_NULL activity_NN1 ._. 
</s>
<s>
(_( Roll_VV0 ,_, 1986_MC )_) Connection_NN1 with_IW our_APPGE research_NN1 3_MC ._. 
</s>
<s>
Previous_JJ research_NN1 3.1_MC Brewer_NP1 &;_NULL al_NP1 ._. 
</s>
<s>
(_( 2007_MC )_) In_II their_APPGE article_NN1 "_" Target_NN1 's_GE Corporate_JJ Governance_NN1 and_CC Bank_NN1 Merger_NN1 Payoffs_VVZ "_" the_AT authors_NN2 investigate_VV0 if_CS certain_JJ corporate_JJ governance_NN1 characteristics_NN2 of_IO the_AT target_NN1 firm_NN1 have_VH0 an_AT1 impact_NN1 on_II the_AT takeover_NN1 premium_NN1 paid_VVN by_II the_AT acquirer_NN1 ._. 
</s>
<s>
They_PPHS2 use_VV0 three_MC corporate_JJ governance_NN1 determinants_NN2 in_II their_APPGE analysis_NN1 ,_, namely_REX the_AT share_NN1 of_IO independent_JJ directors_NN2 on_II the_AT board_NN1 of_IO directors_NN2 ,_, managerial_JJ share_NN1 ownership_NN1 ,_, and_CC the_AT presence_NN1 of_IO independent_JJ large_JJ block_NN1 holders_NN2 ._. 
</s>
<s>
The_AT data_NN used_VMK to_TO estimate_VVI if_CSW corporate_JJ governance_NN1 factors_NN2 affect_VV0 target_NN1 premiums_NN2 was_VBDZ collected_VVN from_II a_AT1 sample_NN1 of_IO bank_NN1 merger_NN1 and_CC acquisition_NN1 transactions_NN2 between_II 1990_MC and_CC 2004_MC ._. 
</s>
<s>
The_AT material_NN1 consisted_VVD initially_RR of_IO 11,252_MC transactions_NN2 ,_, but_CCB the_AT authors_NN2 narrowed_VVD it_PPH1 down_RP to_II 392_MC mergers_NN2 ._. 
</s>
<s>
To_TO compute_VVI the_AT premium_NN1 they_PPHS2 used_VVD the_AT model_NN1 specification_NN1 in_II Benston_NP1 ,_, Hunter_NP1 ,_, and_CC Wall_NN1 (_( 1995_MC )_) ._. 
</s>
<s>
According_II21 to_II22 this_DD1 model_NN1 the_AT premium_NN1 is_VBZ the_AT difference_NN1 between_II the_AT announced_JJ offer_NN1 price_NN1 for_IF a_AT1 target_NN1 organization_NN1 and_CC the_AT market_NN1 price_NN1 of_IO the_AT target_NN1 's_GE common_JJ stock_NN1 20_MC business_NN1 days_NNT2 prior_II21 to_II22 the_AT merger_NN1 announcement_NN1 date_NN1 ,_, multiplied_VVN by_II the_AT number_NN1 of_IO common_JJ shares_NN2 outstanding_JJ ._. 
</s>
<s>
To_TO test_VVI if_CSW corporate_JJ governance_NN1 determinants_NN2 have_VH0 an_AT1 impact_NN1 on_II the_AT premium_NN1 the_AT authors_NN2 conduct_VV0 a_AT1 multiple_JJ regression_NN1 ._. 
</s>
<s>
As_CSA independent_JJ variable_NN1 they_PPHS2 use_VV0 the_AT premium_NN1 and_CC as_RG dependent_JJ variables_NN2 they_PPHS2 use_VV0 (_( among_II others_NN2 )_) board_NN1 composition_NN1 ,_, Target_NN1 's_GE Managerial_JJ Share_NN1 Ownership_NN1 ,_, Independent_JJ Large_JJ Block_NN1 holders_NN2 ,_, market_VV0 to_II book_NN1 value_NN1 ,_, and_CC variance_NN1 and_CC covariance_NN1 of_IO the_AT acquirers_NN2 '_GE and_CC targets_NN2 '_GE return_NN1 on_II assets_NN2 ._. 
</s>
<s>
The_AT study_NN1 finds_VVZ a_AT1 significant_JJ positive_JJ relationship_NN1 between_II independence_NN1 of_IO the_AT target_NN1 's_GE board_NN1 and_CC the_AT size_NN1 of_IO merger_NN1 purchase_NN1 premiums_NN2 received_VVN by_II the_AT target_NN1 ._. 
</s>
<s>
Further_RRR they_PPHS2 find_VV0 that_CST the_AT target_NN1 company_NN1 's_GE managerial_JJ share_NN1 ownership_NN1 and_CC magnitude_NN1 of_IO independent_JJ block_NN1 holders_NN2 have_VH0 a_AT1 negative_JJ impact_NN1 on_II the_AT merger_NN1 purchase_NN1 premiums_NN2 received_VVN by_II the_AT target_NN1 bank._NNU 3.2_MC ._. 
</s>
<s>
Bebchuk_VV0 ,_, Cohen_NP1 &;_NULL Ferrel_NP1 (_( 2008_MC )_) In_II their_APPGE article_NN1 "_" What_DDQ matters_VVZ in_II corporate_JJ governance_NN1 ?_? "_" the_AT article_NN1 introduce_VV0 an_AT1 entrenchment_NN1 index_NN1 which_DDQ is_VBZ used_VVN to_II determinate_JJ the_AT excellence_NN1 of_IO corporate_JJ governance._NNU 4_MC ._. 
</s>
<s>
Data_NN The_AT data_NN source_NN1 used_VMK to_TO develop_VVI the_AT acquisition_NN1 sample_NN1 was_VBDZ Thomson_NP1 One_MC1 Banker_NN1 ._. 
</s>
<s>
Thereafter_RT Thomson_NP1 Data_NN stream_NN1 is_VBZ used_VVN to_TO gather_VVI the_AT financial_JJ information_NN1 needed_VVN for_IF regression_NN1 analysis_NN1 ._. 
</s>
<s>
The_AT preliminary_JJ target_NN1 sample_NN1 included_VVD only_JJ acquisitions_NN2 of_IO European_JJ companies_NN2 on_II the_AT financial_JJ ,_, manufacturing_NN1 and_CC construction_NN1 industry_NN1 during_II the_AT period_NN1 2000_MC -_- 2006_MC ._. 
</s>
<s>
The_AT industries_NN2 were_VBDR chosen_VVN to_TO make_VVI an_AT1 industry_NN1 comparison_NN1 possible_JJ and_CC the_AT period_NN1 is_VBZ limited_VVN to_II 2006_MC because_CS corporate_JJ governance_NN1 index_NN1 used_VVN in_II our_APPGE regression_NN1 is_VBZ limited_VVN to_II this_DD1 date_NN1 ._. 
</s>
<s>
To_TO facilitate_VVI the_AT information_NN1 gathering_NN1 process_NN1 ,_, only_RR public_JJ companies_NN2 with_IW a_AT1 market_NN1 capitalization_NN1 of_IO above_II 100_MC million_NNO was_VBDZ included_VVN ._. 
</s>
<s>
Table_NN1 1_MC1 reports_VVZ the_AT summary_NN1 statistics_NN for_IF the_AT data_NN set_VV0 ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) Missing_VVG 5_MC ._. 
</s>
<s>
Method_NN1 To_II determinate_JJ the_AT impact_NN1 of_IO company_NN1 corporate_JJ governance_NN1 in_II target_NN1 company_NN1 on_II the_AT premium_NN1 of_IO bidder_NN1 we_PPIS2 first_MD cluster_VV0 the_AT takeover_NN1 targets_NN2 accordingly_RR to_II their_APPGE corporate_JJ governance_NN1 level_NN1 and_CC then_RT analyze_VV0 the_AT different_JJ clusters_NN2 with_IW a_AT1 multiple_JJ regression_NN1 analysis._NNU 5.1_MC ._. 
</s>
<s>
Clustering_NN1 takeover_NN1 targets_NN2 The_AT takeover_NN1 targets_NN2 are_VBR clustered_VVN 4_MC tiers_NN2 ,_, clustered_VVD with_IW the_AT Bebhuck_NN1 index_NN1 ,_, 1-4_MCMC ._. 
</s>
<s>
Takeovers_NN2 200-_NN1 2006_MC index_NN1 2006_MC 5.2_MC ._. 
</s>
<s>
Multiple_JJ regressions_NN2 analysis_NN1 The_AT variables_NN2 applied_VVD to_TO explain_VVI the_AT risk_NN1 premium_NN1 (_( rp_NNU )_) associated_VVN in_II the_AT acquisition_NN1 are_VBR :_: (_( 1_MC1 )_) CGIND_NP1 :_: the_AT Bebchuk_NN1 entrenchment_NN1 index_NN1 ;_; (_( 2_MC )_) OWNS_VVZ :_: the_AT ownership_NN1 structure_NN1 of_IO the_AT target_NN1 company_NN1 ;_; (_( 3_MC )_) DIREC_NP1 :_: The_AT composition_NN1 of_IO board_NN1 of_IO directors_NN2 ;_; (_( 4_MC )_) SIZE_NN1 :_: revenue_NN1 to_TO control_VVI for_IF size_NN1 ;_; (_( 5_MC )_) INDUS_NP1 :_: industry_NN1 to_TO control_VVI for_IF industry_NN1 ;_; (_( 6_MC )_) MULTI_JJ :_: EV/EBITDA_NN1 multiple_NN1 to_TO control_VVI for_IF profitability_NN1 ._. 
</s>
<s>
The_AT multiple_JJ regression_NN1 analysis_NN1 applied_VVN in_II the_AT study_NN1 is_VBZ as_RG following_JJ :_: Figure_NN1 1_MC1 multiple_JJ regression_NN1 analysis_NN1 &lsqb;_( Formula_NN1 &rsqb;_) 5.2.1_MC ._. 
</s>
<s>
Bebchuk_VV0 entrenchment_NN1 index_NN1 In_II analyzing_VVG the_AT corporate_JJ governance_NN1 we_PPIS2 apply_VV0 bebchuk_NN1 entrenchment_NN1 index_NN1 as_CSA benchmark_NN1 for_IF corporate_JJ governance_NN1 excellence_NN1 ._. 
</s>
<s>
In_II their_APPGE article_NN1 "_" What_DDQ matters_VVZ in_II Corporate_JJ Governance_NN1 ?_? "_" 
</s>
<s>
Bebhuck_VV0 et_RA21 al_RA22 ._. 
</s>
<s>
introduced_VVN an_AT1 entrenchment_NN1 index_NN1 based_VVN on_II six_MC provisions_NN2 :_: staggered_JJ boards_NN2 ,_, limits_VVZ to_II shareholder_NN1 bylaw_NN1 amendments_NN2 ,_, poison_NN1 pills_NN2 ,_, golden_JJ parachutes_NN2 ,_, and_CC supermajority_NN1 requirements_NN2 for_IF mergers_NN2 and_CC charter_NN1 amendments_NN2 ._. 
</s>
<s>
(_( Bebchuk_VV0 ;_; Cohen_NP1 ;_; &;_NULL Ferrell_NP1 ,_, 2008_MC )_) 5.2.2_MC ._. 
</s>
<s>
Corporate_JJ governance_NN1 and_CC control_NN1 variables_NN2 Bebchuk_VV0 entrenchment_NN1 index_NN1 is_VBZ a_AT1 good_JJ corporate_JJ governance_NN1 measurement_NN1 ,_, but_CCB to_TO make_VVI the_AT measurement_NN1 even_RR more_RGR appropriate_JJ the_AT study_NN1 adds_VVZ two_MC additional_JJ variables_NN2 ;_; ownership_NN1 structure_NN1 and_CC board_NN1 of_IO directors_NN2 ._. 
</s>
<s>
In_II the_AT multiple_JJ regressions_NN2 analysis_NN1 the_AT premium_NN1 is_VBZ explained_VVN with_IW the_AT variables_NN2 mentioned_VVN above_RL ._. 
</s>
<s>
Though_CS ,_, as_CSA Slusky_NP1 &;_NULL Caves_NN2 (_( 1991_MC )_) shows_VVZ ,_, the_AT excess_JJ premium_NN1 is_VBZ caused_VVN by_II profitability_NN1 level_NN1 ,_, target_NN1 size_NN1 and_CC industry_NN1 ._. 
</s>
<s>
This_DD1 study_NN1 addresses_VVZ these_DD2 causes_NN2 by_II using_VVG three_MC control_NN1 variables_NN2 ;_; Size_NN1 ,_, industry_NN1 and_CC EV/EBITDA_NN1 multiple._NNU 6_MC ._. 
</s>
<s>
Results_NN2 The_AT empirical_JJ part_NN1 of_IO the_AT study_NN1 is_VBZ not_XX yet_RR completed._NNU 6.2_MC ._. 
</s>
<s>
Clustering_NN1 takeover_NN1 targets_NN2 Applying_VVG the_AT clustering_NN1 techniques_NN2 represented_VVN in_II methodology_NN1 part_NN1 6.3_MC ._. 
</s>
<s>
Analyzing_VVG takeover_NN1 targets_NN2 Analyzing_VVG the_AT target_NN1 companies_NN2 with_IW techniques_NN2 represented_VVN in_II methodology_NN1 part_NN1 6.4_MC ._. 
</s>
<s>
Model_NN1 diagnostics_NN1 Study_NN1 the_AT econometrics_NN1 behind_II the_AT methodology_NN1 to_TO check_VVI that_DD1 statistical_JJ properties_NN2 are_VBR acceptable._NNU 7_MC ._. 
</s>
<s>
Discussion_NN1 The_AT main_JJ findings_NN2 from_II the_AT study_NN1 is_VBZ presented_VVN and_CC then_RT compared_VVN with_IW previous_JJ studies._NNU 8_MC ._. 
</s>
<s>
Conclusion_NN1 
</s>
