<s>
EMPLOYER_NN1 BRANDING_VVG IN_II A_AT1 DOWNSIZING_JJ ENVIRONMENT_NN1 AN_AT1 HR_NNU PERSPECTIVE_NN1 A_ZZ1 CASE_NP1 study_NN1 of_IO FINNISH_JJ INVESTMENT_NN1 BANK_NN1 1_MC1 Introduction_NN1 The_AT recent_JJ economical_JJ recession_NN1 forced_VVD numerous_JJ organisations_NN2 round_II the_AT world_NN1 to_TO fight_VVI for_IF their_APPGE existence_NN1 and_CC react_VVI to_II the_AT changed_JJ market_NN1 conditions_NN2 in_II a_AT1 short_JJ time_NNT1 frame_NN1 ._. 
</s>
<s>
The_AT most_RGT common_JJ way_NN1 to_TO cure_VVI the_AT situation_NN1 was_VBDZ by_II organisational_JJ decline_NN1 ._. 
</s>
<s>
Usually_RR organisational_JJ decline_NN1 is_VBZ performed_VVN in_II every_AT1 level_NN1 of_IO an_AT1 organisation_NN1 and_CC the_AT aim_NN1 is_VBZ to_TO cut_VVI costs_NN2 ,_, even_RR by_II cutting_VVG wages_NN2 or_CC by_II laying-off_JJ employees_NN2 (_( De_NP1 Meuse_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2004_MC )_) ._. 
</s>
<s>
Interesting_JJ in_II this_DD1 case_NN1 was_VBDZ the_AT fact_NN1 that_CST some_DD organisations_NN2 choose_VV0 not_XX to_TO loose_VVI a_AT1 single_JJ employee_NN1 ;_; this_DD1 raised_VVD the_AT question_NN1 why_RRQ these_DD2 companies_NN2 proceeded_VVD in_II this_DD1 way_NN1 a_AT1 different_JJ way_NN1 and_CC could_VM they_PPHS2 afford_VVI it_PPH1 ?_? 
</s>
<s>
Some_DD researchers_NN2 stated_VVD that_CST these_DD2 companies_NN2 had_VHD invested_VVN in_II total_JJ quality_NN1 management_NN1 (_( which_DDQ forces_VVZ the_AT companies_NN2 in_RP continues_VVZ control_NN1 of_IO required_JJ workforce_NN1 with_IW core_NN1 competence_NN1 ,_, but_CCB works_VVZ only_RR if_CS implemented_VVN several_DA2 years_NNT2 before_II the_AT economical_JJ crises_NN2 )_) (_( Kinnie_NP1 et_RA21 al_RA22 1997_MC )_) ._. 
</s>
<s>
Another_DD1 explanation_NN1 was_VBDZ that_CST these_DD2 companies_NN2 were_VBDR afraid_JJ of_IO loosing_VVG key_JJ competences_NN2 ._. 
</s>
<s>
Hasty_JJ decisions_NN2 ,_, forced_VVN by_II market_NN1 decline_NN1 ,_, can_VM cause_VVI firms_NN2 to_TO loose_VVI not_XX only_RR the_AT competitive_JJ edge_NN1 but_CCB also_RR the_AT most_RGT valuable_JJ human_JJ capital_NN1 (_( Chadwick_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2004_MC )_) ._. 
</s>
<s>
The_AT problem_NN1 when_CS downsizing_VVG workforce_NN1 is_VBZ that_CST organisations_NN2 may_VM let_VVI go_NN1 of_IO the_AT wrong_JJ people_NN (_( Osborne_NP1 Kilpatrick_NP1 1999:212_MC )_) ._. 
</s>
<s>
The_AT ultimate_JJ question_NN1 then_RT is_VBZ :_: how_RRQ do_VD0 firms_NN2 manage_VVI their_APPGE human_JJ resources_NN2 ,_, human_JJ capital_NN1 and_CC key_JJ talents_NN2 in_II an_AT1 environment_NN1 were_VBDR nothing_PN1 is_VBZ secure_JJ and_CC rapid_JJ changes_NN2 are_VBR required_VVN ?_? 
</s>
<s>
Companies_NN2 that_CST are_VBR not_XX prepared_VVN in_II advance_NN1 for_IF fast_JJ changes_NN2 needs_VVZ to_TO think_VVI about_II their_APPGE organisational_JJ image_NN1 as_II an_AT1 employer_NN1 both_RR internally_RR and_CC externally_RR and_CC how_RRQ they_PPHS2 intend_VV0 to_TO retain_VVI their_APPGE most_RGT valuable_JJ asset_NN1 ,_, the_AT human_JJ capital_NN1 (_( Tomasko_NP1 1991_MC )_) ._. 
</s>
<s>
From_II human_JJ resource_NN1 management_NN1 (_( HRM_NP1 )_) perspective_NN1 ,_, companies_NN2 needs_VVZ to_TO concentrate_VVI on_II retaining_VVG and_CC recruiting_VVG workforce_NN1 that_CST has_VHZ the_AT vital_JJ knowledge_NN1 inline_NN1 with_IW for_CS the_AT companys_NN2 core_NN1 business_NN1 activity_NN1 (_( Torrington_NP1 et_NP1 al.2005_FO )_) 1.2_MC Research_NN1 problem_NN1 The_AT previous_JJ research_NN1 around_II employer_NN1 branding_NN1 has_VHZ mainly_RR concentrated_VVN on_II employer_NN1 attractiveness_NN1 and_CC recruitment_NN1 effectiveness_NN1 (_( Backhaus_NP1 et_RA21 al_RA22 2004_MC )_) ._. 
</s>
<s>
Despite_II the_AT importance_NN1 of_IO the_AT previous_JJ studies_NN2 around_II employer_NN1 branding_VVG ,_, few_DA2 studies_NN2 have_VH0 specifically_RR focused_VVN on_II the_AT correlation_NN1 of_IO negative_JJ organisational_JJ publicity_NN1 and_CC employer_NN1 branding_VVG ._. 
</s>
<s>
Therefore_RR the_AT question_NN1 remains_VVZ can_VM a_AT1 strong_JJ employer_NN1 brand_NN1 help_NN1 to_TO retain_VVI and_CC recruit_VVI key_JJ talents_NN2 after_II the_AT bad_JJ news_NN1 is_VBZ reviled_VVN ?_? 
</s>
<s>
Particularly_RR does_VDZ investments_NN2 in_II employer_NN1 branding_VVG bring_VV0 companies_NN2 security_NN1 in_II uncertain_JJ times_NNT2 ?_? 
</s>
<s>
Especially_RR when_CS organisations_NN2 have_VH0 chosen_VVN to_TO perform_VVI a_AT1 downsizing_JJ program_NN1 ._. 
</s>
<s>
Can_VV0 employer_NN1 branding_NN1 be_VBI used_VVN for_IF other_JJ purposes_NN2 than_CSN simply_RR to_TO attract_VVI external_JJ and_CC internal_JJ vacancies_NN2 when_RRQ the_AT position_NN1 is_VBZ opened_VVN ?_? 1.3_MC Previous_JJ research_NN1 Recently_RR ,_, there_EX has_VHZ been_VBN wide_JJ interest_NN1 toward_II the_AT idea_NN1 that_CST employers_NN2 can_VM brand_VVI them_PPHO2 selves_NN2 to_TO strengthen_VVI their_APPGE position_NN1 in_II labour_NN1 markets_NN2 ._. 
</s>
<s>
Employer_NN1 branding_NN1 is_VBZ a_AT1 quite_RG new_JJ concept_NN1 within_II the_AT human_JJ resource_NN1 management_NN1 literature_NN1 but_CCB is_VBZ seen_VVN as_II an_AT1 important_JJ tool_NN1 for_IF companies_NN2 long-term_JJ strategy_NN1 to_TO gain_VVI competitive_JJ edge_NN1 and_CC to_TO attract_VVI the_AT right_JJ kind_NN1 of_IO employees_NN2 to_TO fill_VVI vacancies_NN2 (_( Backhaus_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2004_MC )_) ._. 
</s>
<s>
Its_APPGE been_VBN studied_VVN as_II a_AT1 tool_NN1 for_IF employer_NN1 attractiveness_NN1 in_II the_AT area_NN1 of_IO marketing_NN1 and_CC recently_RR in_II human_JJ resource_NN1 management_NN1 (_( Berthon_NP1 et_RA21 al_RA22 2008_MC )_) ._. 
</s>
<s>
Branding_NN1 has_VHZ its_APPGE roots_NN2 originally_RR in_II marketing_NN1 were_VBDR the_AT aim_NN1 is_VBZ to_TO make_VVI products_NN2 and_CC services_NN2 more_RGR attractive_JJ ._. 
</s>
<s>
Therefore_RR the_AT research_NN1 around_II employer_NN1 branding_NN1 has_VHZ been_VBN previously_RR researched_VVN in_II the_AT marketing_NN1 literature_NN1 and_CC just_RR recently_RR entered_VVD the_AT HR-literature_NN1 ._. 
</s>
<s>
There_EX are_VBR some_DD explanations_NN2 why_RRQ employer_NN1 branding_NN1 has_VHZ risen_VVN to_II business_NN1 articles_NN2 within_II a_AT1 few_DA2 years_NNT2 time_NNT1 and_CC especially_RR attached_VVN to_II the_AT HRM_NP1 territory_NN1 ._. 
</s>
<s>
According_CS Backhaus_NP1 and_CC Tikoo_NP1 (_( 2004_MC )_) there_EX is_VBZ some_DD evidence_NN1 that_CST employer_NN1 branding_NN1 improves_VVZ recruitment_NN1 outcomes_NN2 and_CC minimizes_VVZ the_AT recruitment_NN1 selection_NN1 costs_NN2 ._. 
</s>
<s>
Other_JJ reason_NN1 to_II the_AT intensified_JJ interest_NN1 toward_II employer_NN1 branding_NN1 is_VBZ according_II21 to_II22 Rosenblatt_NP1 (_( 2001_MC )_) the_AT so-called_JJ brain_NN1 drain_NN1 effect_NN1 ._. 
</s>
<s>
Initially_RR the_AT term_NN1 was_VBDZ used_VVN to_TO describe_VVI a_AT1 phenomenon_NN1 were_VBDR the_AT most_RGT intelligent_JJ and_CC educated_JJ workforce_NN1 leaves_VVZ their_APPGE home_NN1 countries_NN2 for_IF higher_JJR wages_NN2 overseas_RL ._. 
</s>
<s>
In_II business_NN1 studies_NN2 ,_, the_AT brain_NN1 drain_NN1 phenomenon_NN1 is_VBZ used_VVN to_TO illustrate_VVI shortages_NN2 in_II certain_JJ kind_NN1 of_IO knowledge-workers_NN2 in_II the_AT employment_NN1 market_NN1 ._. 
</s>
<s>
1.3.1_MC Previous_JJ research_NN1 :_: employer_NN1 branding_VVG According_II21 to_II22 Tikoo_NP1 et_NP1 ._. 
</s>
<s>
al_NP1 (_( 2004_MC )_) the_AT term_NN1 employer_NN1 branding_NN1 can_VM shortly_RR been_VBN defined_VVN as_II :_: the_AT application_NN1 of_IO branding_VVG principles_NN2 to_II human_JJ resource_NN1 management_NN1 (_( Tikoo_NP1 et_RA21 al_RA22 2004:501_MC )_) ._. 
</s>
<s>
This_DD1 definition_NN1 in_II31 addition_II32 to_II33 several_DA2 other_JJ similar_JJ definitions_NN2 ,_, see_VV0 figure_NN1 1_MC1 ,_, indicates_VVZ the_AT importance_NN1 to_TO understand_VVI the_AT underlying_JJ foundation_NN1 of_IO marketing_NN1 concepts_NN2 ,_, branding_VVG principles_NN2 ._. 
</s>
<s>
Furthermore_RR ,_, it_PPH1 seems_VVZ that_CST the_AT two_MC schools_NN2 i.e._REX the_AT human_JJ resource_NN1 school_NN1 and_CC the_AT marketing_NN1 school_NN1 ,_, are_VBR still_RR competing_VVG over_II the_AT territory_NN1 ._. 
</s>
<s>
Since_CS the_AT term_NN1 employer_NN1 branding_NN1 was_VBDZ initially_RR found_VVN in_II 1990s_MC2 within_II the_AT field_NN1 of_IO Marketing_NN1 by_II Barrow_NP1 (_( source_NN1 )_) ._. 
</s>
<s>
For_REX21 instance_REX22 Michell_NP1 (_( 2002_MC )_) argues_VVZ that_CST the_AT field_NN1 of_IO employer_NN1 branding_NN1 should_VM be_VBI left_VVN to_II marketing_NN1 people_NN since_CS :_: HR_NNU professionals_NN2 ,_, typically-dont_NN1 have_VH0 the_AT marketing_NN1 skills_NN2 to_TO communicate_VVI successfully_RR (_( Michell_NP1 2002:99_MC )_) ._. 
</s>
<s>
The_AT author_NN1 explains_VVZ the_AT statement_NN1 by_II the_AT lack_NN1 of_IO intercommunicative_JJ skills_NN2 that_CST usually_RR are_VBR addressed_VVN to_II the_AT human_JJ resource_NN1 people_NN ._. 
</s>
<s>
Before_II going_VVG any_DD further_JJR it_PPH1 is_VBZ important_JJ to_TO investigate_VVI the_AT fundamentals_NN2 of_IO each_DD1 perspective_NN1 ._. 
</s>
<s>
From_II a_AT1 marketing_NN1 point_NN1 of_IO view_NN1 employer_NN1 branding_NN1 is_VBZ used_VVN to_TO describe_VVI ._. 
</s>
<s>
Human_JJ resource_NN1 perspective_NN1 has_VHZ a_AT1 total_JJ different_JJ goal_NN1 ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) 1.3.2_MC Previous_JJ Research_NN1 :_: Downsizing_NP1 Environment_NN1 &;_NULL Employer_NN1 Branding_VVG Since_II the_AT nature_NN1 of_IO this_DD1 study_NN1 is_VBZ to_TO find_VVI correlations_NN2 between_II human_JJ resource_NN1 practices_NN2 such_II21 as_II22 employer_NN1 branding_VVG ,_, has_VHZ on_II workforce_NN1 recruitment_NN1 and_CC retention_NN1 during_II organisational_JJ decline_NN1 it_PPH1 is_VBZ central_JJ to_TO explore_VVI previous_JJ research_NN1 around_II a_AT1 certain_JJ environmental_JJ condition_NN1 such_II21 as_II22 economical_JJ downturn_NN1 ._. 
</s>
<s>
When_CS the_AT settings_NN2 are_VBR changed_VVN also_RR the_AT sources_NN2 changes_NN2 towards_II economics_NN1 ,_, finance_NN1 and_CC human_JJ resource_NN1 management_NN1 ._. 
</s>
<s>
In_II this_DD1 paper_NN1 downsizing_NN1 is_VBZ defined_VVN as_II :_: a_AT1 choice_NN1 made_VVD to_TO reduce_VVI the_AT workforce_NN1 ,_, which_DDQ is_VBZ intended_VVN to_TO improve_VVI organizational_JJ performance_NN1 (_( Rollinson_NP1 2005:480_MC )_) ._. 
</s>
<s>
When_CS screening_VVG the_AT research_NN1 around_II organisational_JJ decline_NN1 it_PPH1 can_VM be_VBI stated_VVN that_DD1 researcher_NN1 from_II the_AT human_JJ resource_NN1 school_NN1 has_VHZ been_VBN concentrating_VVG more_RRR on_II employee_NN1 relations_NN2 and_CC payment_NN1 issues_NN2 ._. 
</s>
<s>
The_AT finance_NN1 and_CC economic_JJ schools_NN2 on_II the_AT other_JJ hand_NN1 ,_, has_VHZ addressed_VVN the_AT questions_NN2 about_II the_AT effects_NN2 of_IO short-_JJ and_CC long_JJ term_NN1 investments_NN2 and_CC the_AT effects_NN2 of_IO cost_NN1 reduction_NN1 ._. 
</s>
<s>
Interestingly_RR ,_, the_AT question_NN1 about_II organisational_JJ image_NN1 during_II a_AT1 downsizing_JJ period_NN1 seemed_VVD to_TO be_VBI out_II21 of_II22 mutual_JJ concern_NN1 ._. 
</s>
<s>
However_RR ,_, it_PPH1 appeared_VVD that_CST the_AT question_NN1 of_IO organisational_JJ image_NN1 was_VBDZ a_AT1 side_NN1 product_NN1 to_II each_DD1 school_NN1 of_IO economics_NN1 ._. 
</s>
<s>
Consequently_RR ,_, employer_NN1 branding_VVG in_II a_AT1 downsizing_JJ environment_NN1 has_VHZ so_RG far_RR researched_VVN less_RRR ._. 
</s>
<s>
1.4_MC Purpose_NN1 of_IO the_AT study_NN1 This_DD1 paper_NN1 aims_VVZ to_TO investigate_VVI one_MC1 of_IO the_AT most_RGT recent_JJ ways_NN2 organisations_NN2 intend_VV0 to_TO retain_VVI and_CC recruit_VVI key_JJ talent_NN1 during_II organisational_JJ downsizing_NN1 ._. 
</s>
<s>
Emphasis_NN1 of_IO this_DD1 paper_NN1 will_VM be_VBI on_II the_AT HRM_NP1 practices_NN2 focusing_VVG on_II employer_NN1 branding_VVG 1.5_MC Limitations_NN2 This_DD1 study_NN1 aims_VVZ to_TO explain_VVI ,_, analyse_VV0 and_CC research_NN1 through_II the_AT human_JJ resource_NN1 perspective_NN1 ._. 
</s>
<s>
This_DD1 paper_NN1 tends_VVZ to_TO explain_VVI the_AT phenomena_NN2 using_VVG large_JJ and_CC medium_JJ sized_JJ organisations_NN2 ._. 
</s>
<s>
Employees_NN2 are_VBR studied_VVN as_CSA objects_VVZ therefore_RR any_DD personal_JJ or_CC individual_JJ aspects_NN2 to_II downsizing_VVG are_VBR not_XX taken_VVN into_II a_AT1 count_NN1 ._. 
</s>
<s>
1.6_MC Methodological_JJ and_CC empirical_JJ considerations_NN2 The_AT method_NN1 used_VVN in_II this_DD1 paper_NN1 will_VM an_AT1 explorative_JJ case_NN1 study_NN1 ._. 
</s>
<s>
The_AT theoretical_JJ framework_NN1 will_VM consist_VVI of_IO previous_JJ research_NN1 around_II the_AT topic_NN1 ._. 
</s>
<s>
Since_CS I_PPIS1 do_VD0 not_XX aim_VVI to_TO test_VVI an_AT1 existent_JJ theory_NN1 I_PPIS1 hope_VV0 to_TO finalize_VVI the_AT thesis_NN1 by_II creating_VVG a_AT1 link_NN1 between_II downsizing_VVG and_CC employer_NN1 branding_VVG ._. 
</s>
<s>
1.7_MC Structure_NN1 of_IO this_DD1 paper_NN1 The_AT author_NN1 hopes_VVZ to_TO find_VVI understanding_NN1 through_II defining_VVG first_MD the_AT most_RGT central_JJ concepts_NN2 and_CC definitions_NN2 :_: employer_NN1 branding_VVG ,_, organisational_JJ downsizing_NN1 ,_, HRM_NP1 practices_NN2 ,_, recruitment_NN1 and_CC organizational_JJ image_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ followed_VVN by_II the_AT core_NN1 theory_NN1 about_II employer_NN1 branding_NN1 conceptualized_VVD by_II Backhaus_NP1 and_CC Tikoo_NP1 (_( 2004_MC )_) ._. 
</s>
<s>
In_II search_NN1 for_IF more_DAR insights_NN2 to_II the_AT research_NN1 topic_NN1 ,_, a_AT1 case_NN1 study_NN1 of_IO a_AT1 Finnish_JJ investment_NN1 bank_NN1 will_VM be_VBI presented_VVN ._. 
</s>
<s>
Finally_RR the_AT paper_NN1 discusses_VVZ findings_NN2 and_CC suggestions_NN2 for_IF further_JJR research_NN1 ._. 
</s>
<s>
2_MC CONSEPTUAL_JJ OVERVIEW_NN1 OF_IO KEY_JJ TERMS_NN2 2.1_MC HRM_NP1 2.2_MC HR_NNU Practices_NN2 2.2.1_MC Recruitment_NN1 2.3_MC Organizational_JJ image_NN1 3_MC Employer_NN1 Branding_VVG in_II a_AT1 downsizing_JJ environment_NN1 In_II this_DD1 section_NN1 the_AT theoretical_JJ foundation_NN1 for_IF the_AT research_NN1 and_CC analysis_NN1 is_VBZ presented_VVN ._. 
</s>
<s>
The_AT discussion_NN1 will_VM shift_VVI from_II a_AT1 downsizing_JJ environment_NN1 towards_II employer_NN1 branding_VVG ._. 
</s>
<s>
The_AT essential_JJ terms_NN2 such_II21 as_II22 HRM_NP1 and_CC HR-practices_NN2 are_VBR presented_VVN earlier_RRR in_II the_AT introduction_NN1 chapter_NN1 ._. 
</s>
<s>
3.1_MC Organization_NN1 in_II a_AT1 downsizing_JJ environment_NN1 3.2_MC The_AT effects_NN2 of_IO downsizing_VVG 3.1.1_MC Organisation_NN1 external_JJ and_CC internal_JJ issues_NN2 3.2.2_MC Employer_NN1 3.2.3_MC Employee_NN1 3.3_MC The_AT essence_NN1 of_IO employer_NN1 branding_VVG an_AT1 HRM_NP1 perspective_NN1 3.3.1_MC The_AT Backhaus_NP1 and_CC Tikoo_NP1 framework_NN1 for_IF employer_NN1 branding_VVG 3.4_MC Summary_NN1 of_IO theory_NN1 4_MC METHOD_NN1 5_MC EXPLORATIV_NP1 CASE_NP1 STUDY_NN1 6_MC DISCUSSION_NN1 &;_NULL CONCLUSION_NN1 
</s>
