<s>
Virtual_JJ Teams_NN2 :_: -_- a_AT1 career_NN1 trap_NN1 ?_? 
</s>
<s>
INTRODUCTION_NN1 Recently_RR organizations_NN2 have_VH0 showed_VVN a_AT1 wide_JJ interest_NN1 in_II virtual_JJ teams_NN2 ._. 
</s>
<s>
Virtual_JJ teams_NN2 create_VV0 flexibility_NN1 and_CC efficiency_NN1 cross_NN1 organization_NN1 ,_, which_DDQ allows_VVZ organizations_NN2 to_TO react_VVI faster_RRR to_II the_AT changing_JJ market_NN1 environment_NN1 and_CC customer_NN1 needs_NN2 (_( Nokia_NP1 ,_, 2008_MC )_) ._. 
</s>
<s>
According_II21 to_II22 Powell_NP1 et_RA21 al._RA22 ,_, (_( 2004_MC )_) the_AT most_RGT successful_JJ companies_NN2 today_RT create_VV0 competitive_JJ advantage_NN1 by_II responding_VVG to_II customer_NN1 needs_NN2 (_( new_JJ products_NN2 and_CC services_NN2 )_) more_RGR rapidly_RR then_RT competitors_NN2 ._. 
</s>
<s>
What_DDQ makes_VVZ virtual_JJ teams_NN2 so_RG effective_JJ and_CC flexible_JJ is_VBZ the_AT fact_NN1 that_CST knowledge_NN1 can_VM be_VBI transferred_VVN across_II organization_NN1 without_IW geographical_JJ restrictions_NN2 ._. 
</s>
<s>
Virtual_JJ teams_NN2 have_VH0 also_RR been_VBN seen_VVN cost_VV0 effective_JJ compared_VVN to_II traditional_JJ teams_NN2 ._. 
</s>
<s>
According_II21 to_II22 Sanford_NP1 Business_NN1 University_NN1 (_( 2003_MC )_) organizations_NN2 can_VM save_VVI up_RG21 to_RG22 million_NNO dollars_NNU2 in_II compliance_NN1 cost_NN1 yearly_RR ._. 
</s>
<s>
1.1_MC Research_NN1 problem_NN1 However_RR ,_, recent_JJ data_NN have_VH0 shown_VVN that_CST many_DA2 organizations_NN2 create_VV0 virtual_JJ teams_NN2 without_IW necessary_JJ policies_NN2 or_CC knowledge_NN1 how_RRQ to_TO manage_VVI or_CC train_VVI these_DD2 diversified_JJ teams_NN2 ._. 
</s>
<s>
Poor_JJ management_NN1 of_IO virtual_JJ teams_NN2 shows_VVZ up_RP in_II human_JJ resource_NN1 indicators_NN2 ,_, such_II21 as_II22 low_JJ confidence_NN1 and_CC retention_NN1 of_IO employees_NN2 ._. 
</s>
<s>
Virtual_JJ team_NN1 members_NN2 experience_NN1 having_VHG less_DAR possibilities_NN2 to_TO develop_VVI in_II their_APPGE careers_NN2 then_RT traditional_JJ team_NN1 members_NN2 ,_, which_DDQ has_VHZ been_VBN seen_VVN as_CSA one_MC1 of_IO the_AT main_JJ causes_NN2 to_II employee_NN1 retention_NN1 ._. 
</s>
<s>
Retaining_VVG virtual_JJ knowledge_NN1 workers_NN2 is_VBZ vital_JJ to_II companies_NN2 because_CS finding_VVG a_AT1 new_JJ team_NN1 member_NN1 is_VBZ not_XX easy_JJ ._. 
</s>
<s>
According_II21 to_II22 Time_NNT1 Management_NN1 (_( 2010_MC )_) ,_, not_XX everyone_PN1 is_VBZ suitable_JJ for_IF working_VVG in_II virtual_JJ teams_NN2 ._. 
</s>
<s>
Working_VVG in_II virtual_JJ teams_NN2 requires_VVZ self-motivation_NN1 on_II strong_JJ result_NN1 orientation_NN1 because_CS employees_NN2 work_VV0 without_IW clear_JJ structure_NN1 and_CC control_NN1 ._. 
</s>
<s>
Virtual_JJ teams_NN2 members_NN2 are_VBR required_VVN to_TO communicate_VVI in_II fast_JJ speed_NN1 and_CC still_RR keep_VV0 the_AT communication_NN1 positive_JJ and_CC constructive_JJ without_IW face-to-face_JJ communication_NN1 ._. 
</s>
<s>
1.2_MC Purpose_NN1 of_IO Study_NN1 The_AT purpose_NN1 of_IO this_DD1 study_NN1 is_VBZ to_TO find_VVI ways_NN2 for_IF human_JJ resource_NN1 management_NN1 to_TO design_VVI successful_JJ development_NN1 programs_NN2 for_IF virtual_JJ teams_NN2 ._. 
</s>
<s>
1.3_MC Method_NN1 1.4_MC Structure_NN1 This_DD1 paper_NN1 is_VBZ structured_VVN as_CSA follows_VVZ ._. 
</s>
<s>
The_AT first_MD section_NN1 presents_VVZ the_AT research_NN1 problem_NN1 and_CC the_AT purpose_NN1 of_IO the_AT study_NN1 ._. 
</s>
<s>
The_AT second_MD section_NN1 presents_VVZ the_AT pre-knowledge_NN1 and_CC key_JJ concepts_NN2 ,_, which_DDQ clarifies_VVZ not_XX only_RR the_AT key_JJ definitions_NN2 but_CCB also_RR the_AT important_JJ functions_NN2 necessary_JJ in_II virtual_JJ team_NN1 management_NN1 ._. 
</s>
<s>
Previous_JJ research_NN1 will_VM be_VBI presented_VVN in_II the_AT second_MD section_NN1 to_TO draw_VVI a_AT1 line_NN1 between_II human_JJ recourse_NN1 practices_NN2 and_CC current_JJ studies_NN2 ._. 
</s>
<s>
Therefore_RR it_PPH1 seems_VVZ logical_JJ to_TO present_VVI the_AT research_NN1 limitation_NN1 under_II the_AT second_MD section_NN1 ._. 
</s>
<s>
The_AT third_MD section_NN1 presents_VVZ the_AT theoretical_JJ framework_NN1 on_II virtual_JJ team_NN1 development_NN1 practices_NN2 and_CC the_AT final_JJ section_NN1 presents_VVZ conclusions_NN2 and_CC recommendations_NN2 to_II further_JJR studies_NN2 ._. 
</s>
<s>
2_MC Conceptual_JJ overview_NN1 of_IO key_JJ concepts_NN2 and_CC pre-_JJ knowledge_NN1 2.1_MC Virtual_JJ teams_NN2 Virtual_JJ teams_NN2 also_RR know_VV0 as_RG geographically_RR dispersed_JJ teams_NN2 (_( GDT_NP1 )_) ,_, was_VBDZ established_VVN to_TO maximize_VVI company_NN1 productivity_NN1 and_CC to_TO reduce_VVI meeting_NN1 and_CC traveling_VVG cost_NN1 between_II company_NN1 subsidiaries_NN2 and_CC customers_NN2 ._. 
</s>
<s>
The_AT primary_JJ idea_NN1 of_IO these_DD2 teams_NN2 is_VBZ to_TO be_VBI able_JK to_TO work_VVI together_RL despite_II of_IO the_AT different_JJ geographical_JJ location_NN1 and_CC different_JJ time_NNT1 zones_NN2 ._. 
</s>
<s>
2.2_MC Traditional_JJ teams_NN2 versus_II Virtual_JJ teams_NN2 2.3_MC Human_JJ resource_NN1 management_NN1 practices_NN2 for_IF virtual_JJ teams_NN2 2.4_MC Previous_JJ research_NN1 on_II virtual_JJ teams_NN2 2.5_MC Limitations_NN2 2.6_MC Summary_NN1 of_IO key_JJ concepts_NN2 and_CC pre-knowledge_NN1 3_MC Theoretical_JJ Framework_NN1 for_IF development_NN1 of_IO virtual_JJ teams_NN2 3.1_MC Competencies_NN2 3.2_MC Learning_NN1 and_CC development_NN1 of_IO virtual_JJ teams_NN2 3.3_MC Career_NN1 development_NN1 of_IO virtual_JJ teams_NN2 3.4_MC Summary_NN1 of_IO Theory_NN1 4_MC Discussions_NN2 4.1_MC Discussion_NN1 of_IO the_AT theory_NN1 and_CC findings_NN2 4.2_MC Further_JJR Reading_NN1 4.3_MC Summary_NN1 of_IO Discussion_NN1 
</s>
