<s>
The_AT relationship_NN1 between_II economic_JJ growth_NN1 and_CC poverty_NN1 reduction_NN1 Introduction_NN1 Economic_JJ growth_NN1 and_CC poverty_NN1 are_VBR often_RR seen_VVN to_TO be_VBI linked_VVN to_II each_PPX221 other_PPX222 ,_, as_CSA an_AT1 increasing_JJ GDP_NN1 per_JJ21 capita_JJ22 ratio_NN1 implies_VVZ that_CST people_NN in_II a_AT1 growing_JJ economy_NN1 will_VM be_VBI better_JJR off_RP ._. 
</s>
<s>
However_RR ,_, it_PPH1 is_VBZ generally_RR acknowledged_VVN that_CST the_AT gains_NN2 from_II economic_JJ growth_NN1 do_VD0 not_XX necessarily_RR trickle_VVI down_RP to_II the_AT poorest_JJT share_NN1 of_IO the_AT population_NN1 in_II a_AT1 straightforward_JJ manner_NN1 ._. 
</s>
<s>
Even_CS21 though_CS22 an_AT1 increasing_JJ GDP_NN1 per_JJ21 capita_JJ22 ratio_NN1 implies_VVZ an_AT1 increase_NN1 in_II the_AT average_JJ income_NN1 level_NN1 ,_, it_PPH1 might_VM not_XX reach_VVI the_AT whole_JJ population_NN1 ,_, and_CC hence_RR even_RR a_AT1 large_JJ increase_NN1 in_II the_AT average_JJ measure_NN1 might_VM not_XX decrease_VVI the_AT number_NN1 of_IO people_NN living_VVG in_II absolute_JJ poverty_NN1 in_II the_AT country_NN1 ._. 
</s>
<s>
In_II the_AT latter_DA half_NN1 of_IO the_AT 19th_MD century_NNT1 ,_, there_EX has_VHZ been_VBN wide_JJ interest_NN1 in_II understanding_VVG aspects_NN2 of_IO poverty_NN1 reduction_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ because_CS knowledge_NN1 of_IO the_AT link_NN1 between_II economic_JJ growth_NN1 and_CC poverty_NN1 helps_VVZ when_CS planning_VVG development_NN1 strategies_NN2 and_CC understanding_VVG their_APPGE implications_NN2 on_II the_AT population_NN1 ,_, but_CCB also_RR when_CS assessing_VVG the_AT prospects_NN2 and_CC limitations_NN2 for_IF investment_NN1 projects_NN2 into_II developing_JJ countries_NN2 ._. 
</s>
<s>
The_AT question_NN1 of_IO inequality_NN1 is_VBZ also_RR of_IO great_JJ importance_NN1 when_CS analysing_VVG these_DD2 problems_NN2 ._. 
</s>
<s>
The_AT link_NN1 between_II growth_NN1 and_CC poverty_NN1 has_VHZ been_VBN studied_VVN especially_RR by_II researchers_NN2 such_II21 as_II22 Ravallion_NP1 ,_, Kuznets_NP1 ,_, as_II31 well_II32 as_II33 Anand_NP1 and_CC Kanbur_NP1 ._. 
</s>
<s>
However_RR ,_, despite_II research_NN1 ,_, there_EX is_VBZ no_AT comprehensive_JJ theory_NN1 in_II the_AT matter_NN1 ._. 
</s>
<s>
The_AT aim_NN1 of_IO this_DD1 essay_NN1 is_VBZ therefore_RR to_TO answer_VVI the_AT question_NN1 of_IO whether_CSW31 or_CSW32 not_CSW33 economic_JJ growth_NN1 results_NN2 in_II poverty_NN1 reduction_NN1 in_II developing_JJ countries_NN2 ._. 
</s>
<s>
First_MD relevant_JJ concepts_NN2 ,_, i.e._REX poverty_NN1 ,_, economic_JJ growth_NN1 and_CC pro-poor_JJ growth_NN1 are_VBR defined_VVN ._. 
</s>
<s>
This_DD1 is_VBZ followed_VVN by_II a_AT1 discussion_NN1 of_IO the_AT relationship_NN1 between_II growth_NN1 and_CC poverty_NN1 reduction_NN1 ,_, which_DDQ is_VBZ based_VVN especially_RR on_II the_AT question_NN1 of_IO inequality_NN1 ,_, as_II31 well_II32 as_II33 initial_JJ conditions_NN2 and_CC the_AT importance_NN1 of_IO development_NN1 ._. 
</s>
<s>
All_DB of_IO these_DD2 factors_NN2 play_VV0 a_AT1 key_JJ role_NN1 in_II evaluating_VVG whether_CSW time_NNT1 periods_NN2 or_CC implemented_JJ policies_NN2 show_VV0 signs_NN2 of_IO the_AT existence_NN1 of_IO pro-poor_JJ growth_NN1 ._. 
</s>
<s>
Two_MC examples_NN2 are_VBR also_RR given_VVN in_II this_DD1 research_NN1 ,_, namely_REX the_AT historical_JJ evidence_NN1 of_IO the_AT relationship_NN1 between_II economic_JJ development_NN1 and_CC poverty_NN1 reduction_NN1 in_II Brazil_NP1 and_CC Uganda_NP1 respectively_RR ._. 
</s>
<s>
Describe_VV0 content_NN1 in_II each_DD1 section_NN1 ?_? 
</s>
<s>
Literature_NN1 review_NN1 Method/material_NN1 This_DD1 text_NN1 will_VM be_VBI based_VVN on_II an_AT1 assessment_NN1 of_IO the_AT relevant_JJ theories_NN2 that_CST underline_VV0 the_AT link_NN1 between_II economic_JJ growth_NN1 and_CC poverty_NN1 reduction_NN1 ._. 
</s>
<s>
Definitions/results_NN2 ?_? 
</s>
<s>
Economic_JJ growth_NN1 Economic_JJ growth_NN1 is_VBZ ,_, as_CSA defined_VVN by_II the_AT World_NN1 Bank_NN1 ,_, the_AT change_NN1 or_CC expansion_NN1 of_IO a_AT1 country_NN1 's_GE economy_NN1 in_II the_AT period_NN1 of_IO a_AT1 year_NNT1 ._. 
</s>
<s>
It_PPH1 is_VBZ the_AT percentage_NN1 increase_NN1 or_CC decrease_NN1 of_IO the_AT country_NN1 's_GE gross_JJ domestic_JJ product_NN1 (_( GDP_NN1 )_) or_CC the_AT gross_JJ national_JJ product_NN1 (_( GNP_NN1 )_) ._. 
</s>
<s>
Economic_JJ growth_NN1 can_VM be_VBI achieved_VVN either_RR by_II using_VVG a_AT1 greater_JJR amount_NN1 of_IO resources_NN2 ,_, e.g._REX land_NN1 ,_, labour_NN1 or_CC capital_NN1 ,_, or_CC by_II becoming_VVG more_RGR efficient_JJ in_II using_VVG these_DD2 resources_NN2 ._. 
</s>
<s>
Only_RR the_AT latter_DA leads_NN2 to_II higher_JJR income_NN1 per_RR21 capita_RR22 ,_, and_CC economic_JJ efficiency_NN1 is_VBZ therefore_RR often_RR a_AT1 requirement_NN1 for_IF poverty_NN1 reduction_NN1 and_CC the_AT improvement_NN1 in_II the_AT average_JJ standard_NN1 of_IO living_NN1 ._. 
</s>
<s>
As_II the_AT increase_NN1 in_II GDP_NN1 is_VBZ an_AT1 average_NN1 of_IO the_AT country_NN1 as_II a_AT1 whole_NN1 ,_, it_PPH1 does_VDZ not_XX reveal_VVI how_RRQ the_AT different_JJ parts_NN2 of_IO a_AT1 country_NN1 are_VBR developing_VVG ._. 
</s>
<s>
It_PPH1 is_VBZ ,_, however_RR ,_, a_AT1 relatively_RR good_JJ measure_NN1 when_CS it_PPH1 comes_VVZ to_TO cross_VVI country_NN1 comparison_NN1 ,_, and_CC seeing_VVG how_RRQ a_AT1 country_NN1 's_GE economy_NN1 change_NN1 from_II one_MC1 year_NNT1 to_II the_AT other_JJ ._. 
</s>
<s>
Pro-poor_JJ growth_NN1 There_EX is_VBZ no_AT exact_JJ definition_NN1 of_IO pro-poor_JJ growth_NN1 ,_, or_CC rather_RR it_PPH1 varies_VVZ depending_II21 on_II22 who_PNQS one_PN1 asks_VVZ ,_, but_CCB it_PPH1 is_VBZ generally_RR thought_VVN of_IO as_RG economic_JJ growth_NN1 that_CST is_VBZ more_RGR favourable_JJ to_II the_AT poor_JJ than_CSN to_II the_AT rich_JJ ,_, thus_RR narrowing_VVG the_AT differences_NN2 in_II the_AT distribution_NN1 of_IO income_NN1 ._. 
</s>
<s>
Pro-poor_JJ growth_NN1 could_VM be_VBI seen_VVN as_II a_AT1 benchmark_NN1 measure_NN1 from_II a_AT1 country_NN1 's_GE own_DA historical_JJ perspective_NN1 ._. 
</s>
<s>
This_DD1 means_VVZ that_CST any_DD periods_NN2 of_IO growth_NN1 could_VM be_VBI compared_VVN to_II a_AT1 specific_JJ historical_JJ period_NN1 of_IO time_NNT1 where_RRQ growth_NN1 was_VBDZ not_XX seen_VVN as_CSA pro-poor_JJ ,_, and_CC thereby_RR analyse_VV0 whether_CSW the_AT new_JJ period_NN1 of_IO growth_NN1 has_VHZ ,_, or_CC will_NN1 ,_, benefit_VV0 the_AT poor_JJ more_RRR than_CSN the_AT rich_JJ ._. 
</s>
<s>
However_RR ,_, for_IF the_AT sake_NN1 of_IO simplicity_NN1 and_CC allowing_VVG for_IF comparison_NN1 ,_, pro-poor_JJ growth_NN1 is_VBZ often_RR seen_VVN as_CSA just_RR a_AT1 period_NN1 of_IO growth_NN1 that_CST favours_VVZ the_AT poor_JJ more_RRR than_CSN the_AT rich_JJ ._. 
</s>
<s>
Poverty_NN1 Poverty_NN1 can_VM be_VBI measured_VVN in_II different_JJ ways_NN2 ,_, but_CCB according_II21 to_II22 the_AT World_NN1 Bank_NN1 ,_, the_AT poverty_NN1 line_NN1 is_VBZ the_AT level_NN1 of_IO income_NN1 below_II which_DDQ people_NN are_VBR considered_VVN poor_JJ ._. 
</s>
<s>
The_AT income_NN1 level_NN1 shows_VVZ on_II average_JJ how_RGQ much_DA1 income_NN1 is_VBZ required_VVN in_BCL21 order_BCL22 to_TO buy_VVI basic_JJ necessities_NN2 such_II21 as_II22 food_NN1 ,_, clothes_NN2 and_CC shelter_NN1 ._. 
</s>
<s>
Country_NN1 specific_JJ ,_, or_CC national_JJ poverty_NN1 lines_NN2 ,_, change_VV0 over_II time_NNT1 and_CC are_VBR different_JJ in_II all_DB regions_NN2 ._. 
</s>
<s>
The_AT international_JJ poverty_NN1 line_NN1 is_VBZ often_RR defined_VVN at_II $1_NNU per_II day_NNT1 (_( PPP_NP1 )_) ,_, i.e._REX a_AT1 person_NN1 whose_DDQGE average_JJ income_NN1 or_CC consumption_NN1 is_VBZ less_DAR than_CSN one_MC1 dollar_NNU1 per_II day_NNT1 is_VBZ considered_VVN to_TO be_VBI poor_JJ ._. 
</s>
<s>
International_JJ poverty_NN1 lines_NN2 have_VH0 also_RR been_VBN set_VVN at_II $2_NNU ,_, $4_NNU or_CC $11_NNU ,_, as_CSA the_AT income_NN1 required_VVN for_IF a_AT1 sufficient_JJ standard_NN1 of_IO living_NN1 is_VBZ often_RR higher_JJR in_II middle-_NN1 or_CC high-income_JJ countries_NN2 ._. 
</s>
<s>
These_DD2 days_NNT2 a_AT1 measure_NN1 of_IO $1.25_NNU is_VBZ ,_, however_RR ,_, often_RR used_VVN ._. 
</s>
<s>
The_AT poverty_NN1 line_NN1 measures_VVZ absolute_JJ poverty_NN1 ,_, in_II contrast_NN1 to_II measures_NN2 of_IO relative_JJ poverty_NN1 ._. 
</s>
<s>
Absolute_JJ poverty_NN1 is_VBZ seen_VVN as_II a_AT1 globally_RR comparable_JJ measure_NN1 ,_, in_II contrast_NN1 to_II relative_JJ poverty_NN1 measures_VVZ that_CST are_VBR often_RR seen_VVN as_II the_AT income_NN1 level_NN1 below_II a_AT1 median_JJ income_NN1 that_CST is_VBZ specific_JJ for_IF a_AT1 country_NN1 and_CC a_AT1 period_NN1 of_IO time_NNT1 ._. 
</s>
<s>
Poverty_NN1 is_VBZ often_RR calculated_VVN both_RR as_CSA the_AT number_NN1 of_IO poor_JJ people_NN in_II a_AT1 country_NN1 as_II31 well_II32 as_II33 so_JJ21 called_JJ22 poverty_NN1 headcount_NN1 ratio_NN1 ,_, i.e._REX the_AT percentage_NN1 of_IO poor_JJ people_NN in_II a_AT1 country_NN1 in_II31 relation_II32 to_II33 the_AT total_JJ population_NN1 ._. 
</s>
<s>
This_DD1 often_RR leads_VVZ to_II problems_NN2 when_CS measuring_VVG poverty_NN1 changes_NN2 over_II time_NNT1 ,_, due_II21 to_II22 the_AT often_RR rapid_JJ population_NN1 growth_NN1 in_II developing_JJ countries_NN2 ._. 
</s>
<s>
For_REX21 example_REX22 ,_, the_AT number_NN1 of_IO poor_JJ can_VM increase_VVI due_II21 to_II22 rapid_JJ population_NN1 growth_NN1 ,_, while_CS the_AT percentage_NN1 of_IO the_AT poor_JJ people_NN in_II a_AT1 country_NN1 stays_VVZ constant_JJ ._. 
</s>
<s>
Chronic_JJ poverty_NN1 is_VBZ often_RR defined_VVN as_CSA constant_JJ poverty_NN1 ,_, i.e._REX a_AT1 person_NN1 is_VBZ living_VVG in_II absolute_JJ poverty_NN1 for_IF longer_JJR periods_NN2 of_IO time_NNT1 ,_, in_II contrast_NN1 to_II people_NN who_PNQS move_VV0 in_RP and_CC out_II21 of_II22 poverty_NN1 repeatedly_RR ._. 
</s>
<s>
Poverty_NN1 can_VM also_RR be_VBI defined_VVN by_II other_JJ measures_NN2 ,_, e.g._REX by_II an_AT1 asset-based_JJ model_NN1 or_CC in_II non-monetary_JJ terms_NN2 ._. 
</s>
<s>
Non-monetary_JJ based_VVN poverty_NN1 measures_NN2 include_VV0 for_REX21 example_REX22 calculating_VVG the_AT improvements_NN2 in_II healthcare_NN1 ,_, education_NN1 ,_, nutrition_NN1 ,_, various_JJ types_NN2 of_IO security_NN1 and_CC life_NN1 expectancy_NN1 ._. 
</s>
<s>
Poverty_NN1 can_VM also_RR be_VBI viewed_VVN upon_II from_II a_AT1 capability_NN1 perspective_NN1 ,_, where_CS an_AT1 individuals_NN2 poverty_NN1 not_XX only_RR takes_VVZ into_II consideration_NN1 her_APPGE wealth_NN1 ,_, but_CCB also_RR her_APPGE abilities_NN2 and_CC possibilities_NN2 to_TO make_VVI use_NN1 of_IO this_DD1 wealth_NN1 in_II the_AT best_JJT possible_JJ way_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ an_AT1 important_JJ broadening_NN1 of_IO the_AT simple_JJ poverty_NN1 line_NN1 measure_NN1 ,_, as_CSA this_DD1 takes_VVZ into_II account_NN1 many_DA2 other_JJ imminent_JJ factors_NN2 of_IO poverty_NN1 as_RR21 well_RR22 ,_, such_II21 as_II22 ill_JJ health_NN1 or_CC lack_NN1 of_IO education_NN1 ,_, that_DD1 undoubtedly_RR are_VBR very_RG closely_RR linked_VVN to_II poverty_NN1 ._. 
</s>
<s>
This_DD1 requires_VVZ of_RR21 course_RR22 intimate_JJ knowledge_NN1 of_IO an_AT1 individuals_NN2 possibilities_NN2 and_CC capabilities_NN2 ,_, which_DDQ makes_VVZ data_NN collection_NN1 and_CC comparisons_NN2 very_RG difficult_JJ to_TO make_VVI ._. 
</s>
<s>
The_AT monetary_JJ poverty_NN1 measures_NN2 are_VBR often_RR critiqued_VVN for_IF being_VBG arbitrary_JJ ;_; if_CS one_PN1 earns_VVZ ,_, or_CC consumes_VVZ ,_, less_DAR than_CSN $0.99_NNU per_II day_NNT1 one_PN1 is_VBZ poor_JJ ,_, whereas_CS living_VVG on_II $1.01_NNU per_II day_NNT1 makes_VVZ one_PN1 not_XX poor_JJ ._. 
</s>
<s>
The_AT difference_NN1 of_IO two_MC cents_NNU2 can_VM therefore_RR be_VBI of_IO huge_JJ importance_NN1 in_II poverty_NN1 calculations_NN2 ._. 
</s>
<s>
Monetary_JJ poverty_NN1 measures_NN2 also_RR exclude_VV0 many_DA2 important_JJ factors_NN2 of_IO poverty_NN1 ,_, as_CSA poverty_NN1 is_VBZ not_XX only_RR about_II consumption_NN1 or_CC income_NN1 ,_, but_CCB also_RR more_RGR intangible_JJ things_NN2 such_II21 as_II22 education_NN1 or_CC life_NN1 expectancy_NN1 that_CST are_VBR not_XX always_RR directly_RR linked_VVN to_II the_AT amount_NN1 of_IO money_NN1 an_AT1 individual_NN1 can_VM spend_VVI ._. 
</s>
<s>
Household_NN1 surveys_NN2 ,_, which_DDQ are_VBR used_VVN for_IF collecting_VVG data_NN about_II poverty_NN1 ,_, are_VBR also_RR slightly_RR problematic_JJ ._. 
</s>
<s>
Measuring_VVG income_NN1 or_CC consumption_NN1 can_VM be_VBI difficult_JJ for_IF many_DA2 reasons_NN2 ,_, for_REX21 example_REX22 due_II21 to_II22 intra-household_JJ distribution_NN1 ._. 
</s>
<s>
Income_NN1 and/or_CC consumption_NN1 do_VD0 not_XX always_RR tell_VVI all_DB the_AT relevant_JJ facts_NN2 about_II a_AT1 persons_NN2 wealth_NN1 ,_, because_CS assets_NN2 are_VBR not_XX included_VVN in_II these_DD2 measurements_NN2 ._. 
</s>
<s>
Therefore_RR it_PPH1 could_VM be_VBI useful_JJ to_TO combine_VVI both_RR monetary_JJ ,_, asset-based_JJ and_CC non-monetary_JJ aspects_NN2 when_CS measuring_VVG poverty_NN1 ._. 
</s>
<s>
The_AT relationship_NN1 between_II economic_JJ growth_NN1 and_CC poverty/discussion_NN1 The_AT relationship_NN1 between_II growth_NN1 and_CC poverty_NN1 works_VVZ both_RR ways_NN2 ;_; when_RRQ GDP_NN1 per_RR21 capita_RR22 increases_VVZ as_II a_AT1 result_NN1 of_IO economic_JJ growth_NN1 ,_, the_AT proportion_NN1 of_IO poor_JJ people_NN in_II a_AT1 country_NN1 tends_VVZ to_TO become_VVI smaller_JJR as_II a_AT1 well_NN1 ._. 
</s>
<s>
It_PPH1 has_VHZ however_RR ,_, been_VBN observed_VVN ,_, that_CST the_AT greater_JJR the_AT absolute_JJ poverty_NN1 number_NN1 in_II a_AT1 country_NN1 is_VBZ ,_, the_AT lower_JJR the_AT growth_NN1 ratio_NN1 will_VM be_VBI ._. 
</s>
<s>
The_AT question_NN1 of_IO inequality_NN1 of_IO the_AT distribution_NN1 of_IO income_NN1 is_VBZ very_RG important_JJ when_CS discussing_VVG pro-poor_JJ growth_NN1 and_CC the_AT relationship_NN1 between_II growth_NN1 and_CC poverty_NN1 ._. 
</s>
<s>
There_EX seems_VVZ ,_, however_RR ,_, not_XX to_TO be_VBI a_AT1 definite_JJ relationship_NN1 between_II growth_NN1 and_CC inequality_NN1 in_II either_DD1 direction_NN1 ._. 
</s>
<s>
Anand_NP1 and_CC Kanbur_NP1 proved_VVD in_II 1993_MC ,_, based_VVN on_II a_AT1 theory_NN1 presented_VVD first_MD by_II Kuznets_NP1 in_II 1955_MC ,_, that_CST a_AT1 link_NN1 exists_VVZ between_II economic_JJ growth_NN1 ,_, urbanisation_NN1 (_( i.e._REX development_NN1 )_) and_CC the_AT distribution_NN1 of_IO income_NN1 per_RR21 capita_RR22 ._. 
</s>
<s>
It_PPH1 is_VBZ suggested_VVN that_CST economic_JJ growth_NN1 leads_VVZ to_II urbanisation_NN1 ,_, as_CSA people_NN move_VV0 into_II the_AT cities_NN2 for_IF new_JJ jobs_NN2 ._. 
</s>
<s>
The_AT average_JJ income_NN1 level_NN1 is_VBZ ,_, however_RR ,_, lower_JJR in_II rural_JJ areas_NN2 than_CSN in_II urban_JJ areas_NN2 ._. 
</s>
<s>
Economic_JJ growth_NN1 most_RGT often_RR benefits_NN2 urban_JJ areas_NN2 first_MD because_II21 of_II22 the_AT need_NN1 for_IF development_NN1 in_II key_JJ regions_NN2 ,_, which_DDQ leads_VVZ to_II an_AT1 even_RR wider_JJR gap_NN1 in_II the_AT distribution_NN1 of_IO income_NN1 between_II rural_JJ and_CC urban_JJ areas_NN2 ._. 
</s>
<s>
Newer_JJR studies_NN2 show_VV0 that_CST policies_NN2 aimed_VVN at_II reducing_VVG inequality_NN1 do_VD0 not_XX necessarily_RR have_VHI an_AT1 impact_NN1 on_II economic_JJ growth_NN1 ._. 
</s>
<s>
The_AT results_NN2 can_VM be_VBI very_RG much_DA1 negative_JJ in_II the_AT long_JJ run_NN1 ,_, especially_RR if_CS this_DD1 done_VDN by_II distorting_VVG foreign_JJ trade_NN1 or_CC the_AT market_NN1 mechanism_NN1 on_II the_AT domestic_JJ markets_NN2 ._. 
</s>
<s>
The_AT graph_NN1 below_RL ,_, Graph_NN1 1_MC1 GDP_NN1 per_RR21 capita_RR22 and_CC absolute_JJ poverty_NN1 in_II Brazil_NP1 1978-2004_MCMC ,_, shows_VVZ the_AT annual_JJ growth_NN1 rate_NN1 of_IO GDP_NN1 as_II a_AT1 percentage_NN1 and_CC absolute_JJ poverty_NN1 as_II a_AT1 percentage_NN1 of_IO the_AT total_JJ population_NN1 in_II Brazil_NP1 between_II 1978_MC and_CC 2004_MC ._. 
</s>
<s>
The_AT case_NN1 of_IO Brazil_NP1 is_VBZ a_AT1 good_JJ example_NN1 of_IO the_AT result_NN1 of_IO inequality_NN1 ,_, growth_NN1 and_CC poverty_NN1 ._. 
</s>
<s>
The_AT graph_NN1 shows_VVZ a_AT1 quite_RG strong_JJ linkage_NN1 between_II the_AT increase_NN1 in_II both_DB2 GPD_NP1 per_RR21 capita_RR22 and_CC the_AT absolute_JJ headcount_NN1 poverty_NN1 ,_, which_DDQ suggests_VVZ that_CST the_AT distribution_NN1 of_IO income_NN1 is_VBZ very_RG broad_JJ in_II Brazil_NP1 and_CC inequality_NN1 can_VM therefore_RR be_VBI seen_VVN as_II a_AT1 problem_NN1 ._. 
</s>
<s>
Uganda_NP1 ,_, in_II contrast_NN1 to_II Brazil_NP1 ,_, showed_VVD both_RR a_AT1 period_NN1 of_IO pro-poor_JJ growth_NN1 as_II31 well_II32 as_II33 a_AT1 period_NN1 of_IO growth_NN1 that_CST was_VBDZ not_XX pro-poor_JJ between_II 1992_MC and_CC 2003_MC ._. 
</s>
<s>
GDP_NN1 per_RR21 capita_RR22 grew_VVD by_II 4,3_MC %_NNU between_II 1993_MC and_CC 2000_MC ,_, and_CC by_II 2,9_MC %_NNU between_II 2000_MC and_CC 2002_MC ._. 
</s>
<s>
In_II the_AT same_DA time_NNT1 periods_NN2 poverty_NN1 first_MD decreased_VVN from_II 56_MC %_NNU to_II 34_MC %_NNU and_CC then_RT increased_VVD back_RP to_II 38_MC %_NNU ._. 
</s>
<s>
In_II this_DD1 example_NN1 the_AT shift_NN1 from_II pro-poor_JJ growth_NN1 to_II growth_NN1 that_CST was_VBDZ not_XX pro-poor_JJ ,_, can_VM be_VBI explained_VVN by_II changes_NN2 in_II the_AT international_JJ demand_NN1 for_IF the_AT country_NN1 's_GE agricultural_JJ products_NN2 ._. 
</s>
<s>
In_II the_AT late_JJ 1990_MC221 's_MC222 ,_, the_AT demand_NN1 ,_, and_CC therefore_RR the_AT prices_NN2 as_RR21 well_RR22 ,_, for_IF Uganda_NP1 's_GE agricultural_JJ products_NN2 increased_VVN ._. 
</s>
<s>
However_RR ,_, in_II 2001_MC coffee_NN1 ,_, tea_NN1 ,_, tobacco_NN1 and_CC cotton_NN1 prices_NN2 dropped_VVD internationally_RR ,_, and_CC the_AT Ugandan_JJ economy_NN1 staggered_VVD ,_, forcing_VVG most_DAT of_IO the_AT poor_JJ farmers_NN2 into_II poverty_NN1 ._. 
</s>
<s>
The_AT processes_NN2 observed_VVN in_II Uganda_NP1 are_VBR very_RG normal_JJ scenarios_NN2 in_II the_AT developing_JJ world_NN1 ._. 
</s>
<s>
When_CS the_AT changes_NN2 in_II GDP_NN1 ,_, both_RR increases_VVZ and_CC decreases_VVZ ,_, are_VBR observed_VVN over_II a_AT1 longer_JJR period_NN1 of_IO time_NNT1 ,_, inequality_NN1 will_VM both_RR rise_VVI and_CC fall_VVI ,_, regardless_RR of_IO the_AT changes_NN2 in_II GDP_NN1 ._. 
</s>
<s>
As_II a_AT1 result_NN1 ,_, poverty_NN1 can_VM either_RR increase_VVI or_CC decrease_VVI during_II economic_JJ growth_NN1 ,_, depending_II21 on_II22 how_RRQ the_AT level_NN1 of_IO inequality_NN1 in_II the_AT same_DA time_NNT1 period_NN1 ._. 
</s>
<s>
Rising_VVG inequality_NN1 during_II economic_JJ growth_NN1 does_VDZ ,_, however_RR ,_, not_XX necessarily_RR decrease_VV0 the_AT rate_NN1 of_IO poverty_NN1 reduction_NN1 ,_, i.e._REX it_PPH1 can_VM not_XX be_VBI concluded_VVN that_CST a_AT1 higher_JJR level_NN1 of_IO poverty_NN1 reduction_NN1 would_VM be_VBI achieved_VVN if_CS only_RR the_AT level_NN1 of_IO inequality_NN1 was_VBDZ lower_JJR ._. 
</s>
<s>
This_DD1 would_VM require_VVI the_AT dubious_JJ assumption_NN1 that_CST growth_NN1 would_VM remain_VVI constant_JJ despite_II a_AT1 lower_JJR level_NN1 of_IO inequality_NN1 ,_, which_DDQ can_VM not_XX be_VBI done_VDN without_IW reservation_NN1 ._. 
</s>
<s>
The_AT initial_JJ conditions_NN2 are_VBR also_RR of_IO importance_NN1 when_CS analysing_VVG changes_NN2 in_II poverty_NN1 ._. 
</s>
<s>
If_CS inequality_NN1 is_VBZ high_JJ to_TO begin_VVI with_IW ,_, it_PPH1 is_VBZ likely_JJ that_CST growth_NN1 will_VM not_XX be_VBI very_RG much_DA1 pro-poor_JJ ,_, whereas_CS a_AT1 low_JJ initial_JJ level_NN1 of_IO inequality_NN1 is_VBZ more_RGR likely_JJ to_TO gain_VVI proportionally_RR more_RRR from_II the_AT growth_NN1 than_CSN the_AT rich_JJ ._. 
</s>
<s>
The_AT distribution-corrected_JJ rate_NN1 of_IO growth_NN1 is_VBZ therefore_RR the_AT one_PN1 needs_VVZ to_TO take_VVI into_II account_NN1 when_CS calculating_VVG poverty_NN1 reduction_NN1 ._. 
</s>
<s>
The_AT initial_JJ conditions_NN2 are_VBR not_XX only_RR important_JJ regarding_II inequality_NN1 ,_, but_CCB also_RR when_CS assessing_VVG other_JJ aspects_NN2 of_IO pro-poor_JJ growth_NN1 ._. 
</s>
<s>
For_REX21 example_REX22 low_JJ living_NN1 standards_NN2 and_CC high_JJ proportion_NN1 of_IO the_AT population_NN1 working_VVG in_II the_AT agricultural_JJ sector_NN1 often_RR lead_VV0 to_TO lower_VVI poverty_NN1 reduction_NN1 ._. 
</s>
<s>
Initial_JJ conditions_NN2 often_RR also_RR mean_VV0 that_CST chronically_RR poor_JJ people_NN do_VD0 not_XX even_RR have_VHI the_AT possibility_NN1 to_TO take_VVI advantage_NN1 of_IO growth_NN1 ._. 
</s>
<s>
If_CS for_REX21 example_REX22 new_JJ jobs_NN2 are_VBR not_XX accessible_JJ due_JJ to_TO lack_VVI of_IO transportation_NN1 infrastructure_NN1 ,_, education_NN1 or_CC ill_JJ health_NN1 ,_, the_AT chronically_RR poor_JJ will_VM remain_VVI poor_JJ because_CS they_PPHS2 lack_VV0 the_AT opportunities_NN2 to_TO change_VVI their_APPGE situation_NN1 ._. 
</s>
<s>
Chronic_JJ poverty_NN1 is_VBZ therefore_RR as_CSA such_DA a_AT1 major_JJ issue_NN1 ,_, as_CSA many_DA2 chronically_RR poor_JJ people_NN lack_VV0 the_AT possibilities_NN2 to_TO influence_VVI their_APPGE own_DA situation_NN1 ._. 
</s>
<s>
If_CS poverty_NN1 is_VBZ measured_VVN based_VVN on_II non-monetary_JJ aspects_NN2 ,_, the_AT link_NN1 between_II pro-poor_JJ and_CC not_XX pro-poor_JJ growth_NN1 is_VBZ bound_VVNK to_TO be_VBI less_RGR obvious_JJ ,_, because_CS this_DD1 would_VM also_RR require_VVI changes_NN2 in_II government_NN1 policy_NN1 and_CC the_AT development_NN1 strategies_NN2 that_CST are_VBR chosen_VVN to_TO be_VBI implemented_VVN ._. 
</s>
<s>
If_CS there_EX is_VBZ a_AT1 functioning_JJ taxation_NN1 system_NN1 ,_, the_AT gains_NN2 from_II a_AT1 growing_JJ economy_NN1 can_VM partially_RR be_VBI used_VVN for_IF development_NN1 purposes_NN2 ,_, for_REX21 example_REX22 increasing_JJ healthcare_NN1 and_CC education_NN1 possibilities_NN2 for_IF everyone_PN1 ._. 
</s>
<s>
Economic_JJ growth_NN1 can_VM therefore_RR over_II time_NNT1 lead_NN1 to_II a_AT1 narrower_JJR distribution_NN1 of_IO income_NN1 and_CC decrease_VV0 in_II poverty_NN1 ,_, as_CSA the_AT public_JJ sector_NN1 grows_VVZ through_II development_NN1 ._. 
</s>
<s>
This_DD1 will_VM most_RGT likely_RR decrease_VVI absolute_JJ poverty_NN1 regardless_RR of_IO which_DDQ measurement_NN1 ,_, monetary_JJ or_CC non-monetary_JJ ,_, is_VBZ used_VVN ._. 
</s>
<s>
However_RR ,_, if_CS the_AT gains_NN2 of_IO economic_JJ growth_NN1 are_VBR not_XX taxed_VVN ,_, or_CC the_AT money_NN1 is_VBZ spent_VVN on_II things_NN2 other_II21 than_II22 development_NN1 of_IO the_AT public_JJ sector_NN1 ,_, the_AT poor_JJ will_VM not_XX be_VBI better_JJR off_RP and_CC remain_VV0 chronically_RR poor_JJ ._. 
</s>
<s>
Inequality_NN1 can_VM grow_VVI in_II these_DD2 cases_NN2 as_RR21 well_RR22 ._. 
</s>
<s>
Accurate_JJ and_CC effective_JJ development_NN1 strategies_NN2 are_VBR therefore_RR of_IO utmost_JJ importance_NN1 in_II a_AT1 country_NN1 if_CS the_AT government_NN1 wishes_VVZ to_TO reduce_VVI chronic_JJ poverty_NN1 in_II a_AT1 country_NN1 ._. 
</s>
<s>
Conclusion_NN1 Researchers_NN2 have_VH0 found_VVN a_AT1 link_NN1 between_II economic_JJ growth_NN1 and_CC poverty_NN1 reduction_NN1 ._. 
</s>
<s>
This_DD1 link_NN1 is_VBZ not_XX always_RR as_RG obvious_JJ as_CSA it_PPH1 could_VM seem_VVI ;_; a_AT1 country_NN1 produces_VVZ more_DAR and_CC therefore_RR incomes_NN2 on_II a_AT1 national_JJ level_JJ increase_NN1 ,_, and_CC people_NN should_VM be_VBI better_JJR off_RP as_II a_AT1 result_NN1 ._. 
</s>
<s>
However_RR ,_, as_CSA the_AT GDP_NN1 per_JJ21 capita_JJ22 ratio_NN1 is_VBZ only_RR a_AT1 national_JJ average_NN1 ,_, problems_NN2 arise_VV0 ._. 
</s>
<s>
Inequality_NN1 ,_, for_REX21 example_REX22 ,_, is_VBZ a_AT1 major_JJ issue_NN1 when_CS discussing_VVG growth_NN1 and_CC poverty_NN1 ;_; how_RRQ does_VDZ inequality_NN1 alter_VV0 the_AT distribution_NN1 of_IO income_NN1 and_CC especially_RR ,_, will_VM the_AT people_NN living_VVG in_II absolute_JJ poverty_NN1 gain_NN1 at_II all_DB from_II the_AT growing_JJ economy_NN1 ?_? 
</s>
<s>
These_DD2 questions_NN2 can_VM only_RR be_VBI answered_VVN with_IW intimate_JJ knowledge_NN1 of_IO the_AT existing_JJ conditions_NN2 in_II each_DD1 specific_JJ case_NN1 ,_, even_CS21 though_CS22 a_AT1 country_NN1 's_GE initial_JJ conditions_NN2 can_VM give_VVI a_AT1 hint_NN1 as_II21 to_II22 how_RRQ the_AT situation_NN1 might_VM develop_VVI ._. 
</s>
<s>
In_II Brazil_NP1 ,_, inequality_NN1 lead_NN1 to_II a_AT1 worsening_JJ situation_NN1 for_IF the_AT poor_JJ when_CS the_AT economy_NN1 grew_VVD ,_, and_CC more_DAR people_NN fell_VVD into_II poverty_NN1 despite_II economic_JJ growth_NN1 ._. 
</s>
<s>
Pro-poor_JJ growth_NN1 ,_, growth_NN1 that_CST benefits_NN2 the_AT poor_JJ proportionally_RR more_DAR than_CSN the_AT rich_JJ ,_, can_VM only_RR occur_VVI when_RRQ inequality_NN1 is_VBZ low_JJ and_CC the_AT distribution_NN1 of_IO income_NN1 not_XX too_RG wide_JJ ._. 
</s>
<s>
Changes_NN2 in_II inequality_NN1 are_VBR as_RG such_DA not_XX linked_VVN to_II growth_NN1 ,_, and_CC during_II periods_NN2 of_IO economic_JJ growth_NN1 ,_, poverty_NN1 can_VM therefore_RR either_RR increase_VVI or_CC decrease_VVI ._. 
</s>
<s>
Uganda_NP1 has_VHZ shown_VVN examples_NN2 of_IO both_DB2 situations_NN2 ._. 
</s>
<s>
As_CSA poverty_NN1 can_VM be_VBI measured_VVN in_II different_JJ ways_NN2 ,_, based_VVN on_II income_NN1 and/or_CC consumption_NN1 ,_, assets_NN2 ,_, or_CC non-monetary_JJ measures_NN2 such_II21 as_II22 education_NN1 and_CC healthcare_NN1 ,_, even_RR high_JJ initial_JJ inequality_NN1 can_VM theoretically_RR lead_VVI to_II poverty_NN1 reduction_NN1 ,_, if_CS the_AT government_NN1 has_VHZ possibilities_NN2 to_II narrow_JJ the_AT distribution_NN1 of_IO income_NN1 through_II for_REX21 example_REX22 taxation_NN1 and_CC thereby_RR increase_VV0 government_NN1 spending_VVG on_II healthcare_NN1 and_CC education_NN1 ._. 
</s>
<s>
Decreasing_JJ non-monetary_JJ poverty_NN1 does_VDZ ,_, however_RR ,_, demand_VVI a_AT1 functioning_NN1 and_CC development-oriented_JJ government_NN1 ,_, that_DD1 has_VHZ the_AT desire_NN1 to_TO increase_VVI possibilities_NN2 for_IF the_AT chronically_RR poor_JJ ._. 
</s>
<s>
Initial_JJ inequality_NN1 in_II opportunities_NN2 can_VM easily_RR lead_VVI to_II less_RGR pro-poor_JJ growth_NN1 in_II developing_JJ countries_NN2 ,_, as_CSA chronically_RR poor_JJ people_NN often_RR have_VH0 inferior_JJ chances_NN2 to_TO for_REX21 example_REX22 get_VVI a_AT1 job_NN1 due_II21 to_II22 the_AT lack_NN1 of_IO education_NN1 or_CC ill_JJ health_NN1 ,_, and_CC they_PPHS2 therefore_RR have_VH0 a_AT1 smaller_JJR possibility_NN1 to_TO take_VVI part_NN1 of_IO economic_JJ growth_NN1 ,_, through_II which_DDQ they_PPHS2 could_VM influence_VVI their_APPGE situation_NN1 and_CC move_VVI out_II21 of_II22 chronic_JJ poverty_NN1 ._. 
</s>
