<s>
What_DDQ type_NN1 of_IO perceived_JJ value_NN1 do_VD0 young_JJ consumers_NN2 find_VV0 important_JJ in_II smartphones_NN2 ?_? 1_MC1 ._. 
</s>
<s>
Introduction_NN1 One_MC1 only_JJ needs_NN2 to_TO open_VVI the_AT newspaper_NN1 of_IO the_AT day_NNT1 to_TO be_VBI able_JK to_TO get_VVI an_AT1 overview_NN1 of_IO the_AT on-going_JJ fight_NN1 over_II market_NN1 shares_NN2 in_II the_AT mobile_JJ phone_NN1 industry_NN1 (_( Kauppalehti_NP1 26.09.2012_MC ,_, Koskinen_NP1 )_) ._. 
</s>
<s>
For_IF Finns_NN2 ,_, as_CSA I_PPIS1 am_VBM ,_, Nokia_NP1 has_VHZ been_VBN of_IO high_JJ importance_NN1 for_IF the_AT economy_NN1 in_II the_AT past_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ one_MC1 of_IO the_AT reasons_NN2 I_PPIS1 think_VV0 the_AT Finnish_JJ media_NN takes_VVZ such_DA a_AT1 high_JJ interest_NN1 in_II the_AT questions_NN2 concerning_II the_AT mobile_JJ phone_NN1 business_NN1 ._. 
</s>
<s>
But_CCB the_AT mobile_JJ phone_NN1 market_NN1 is_VBZ for_RR21 sure_RR22 in_II an_AT1 interesting_JJ phase_NN1 ,_, which_DDQ can_VM be_VBI seen_VVN in_II table_NN1 1_MC1 below_RL ,_, with_IW Nokia_NP1 having_VHG to_TO hand_VVI the_AT market_NN1 share_NN1 leader_NN1 position_NN1 to_II Samsung_NP1 and_CC with_IW Apple_NN1 also_RR steadily_RR covering_VVG more_DAR ground.In_NNU Epsteins_NN2 (_( 2012_MC )_) article_NN1 it_PPH1 is_VBZ indicated_VVN that_CST specifically_RR on_II the_AT smartphone_NN1 market_NN1 ,_, Nokia_NP1 has_VHZ lost_VVN a_AT1 lot_NN1 of_IO ground_NN1 and_CC thus_RR ,_, worsened_VVD its_APPGE situation_NN1 ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) When_CS we_PPIS2 are_VBR talking_VVG about_II the_AT mobile_JJ phone_NN1 industry_NN1 ,_, we_PPIS2 are_VBR in_II other_JJ words_NN2 talking_VVG about_II a_AT1 highly_RR dynamic_JJ and_CC changing_JJ market_NN1 ._. 
</s>
<s>
Today_RT ,_, the_AT development_NN1 of_IO smartphones_NN2 is_VBZ crucial_JJ for_IF the_AT success_NN1 of_IO the_AT mobile_JJ phone_NN1 companies_NN2 and_CC the_AT competition_NN1 is_VBZ therefore_RR hard_JJ ._. 
</s>
<s>
A_AT1 big_JJ difference_NN1 among_II the_AT largest_JJT players_NN2 on_II the_AT market_NN1 ,_, Samsung_NP1 ,_, Nokia_NP1 and_CC Apple_NN1 is_VBZ that_CST they_PPHS2 are_VBR all_DB using_VVG different_JJ operating_NN1 systems_NN2 ._. 
</s>
<s>
Samsung_NP1 is_VBZ using_VVG Android_NN1 ,_, developed_VVN by_II Google_NP1 ,_, Nokia_NP1 has_VHZ used_VVN Symbian_JJ but_CCB is_VBZ changing_VVG to_II Windows_NP1 operating_NN1 system_NN1 and_CC finally_RR Apple_NN1 is_VBZ using_VVG its_APPGE own_DA developed_JJ IOS_NN2 system_NN1 ._. 
</s>
<s>
Anoverview_NN1 of_IO the_AT situation_NN1 of_IO the_AT operating_NN1 systems_NN2 in_II shipped_JJ smartphones_NN2 can_VM be_VBI seen_VVN in_II table_NN1 2_MC below_RL ._. 
</s>
<s>
When_CS watching_VVG the_AT table_NN1 it_PPH1 becomes_VVZ quite_RG clear_JJ what_DDQ the_AT trends_NN2 look_VV0 like_II in_II the_AT smartphone_NN1 business_NN1 ._. 
</s>
<s>
Android_NN1 is_VBZ clearly_RR the_AT leading_JJ operating_NN1 system_NN1 followed_VVN by_II Apples_NN2 IOS_NN2 ._. 
</s>
<s>
The_AT most_RGT interesting_JJ question_NN1 is_VBZ what_DDQ has_VHZ happened_VVN to_II Nokia_NP1 ?_? 
</s>
<s>
It_PPH1 has_VHZ the_AT second_MD largest_JJT overall_JJ market_NN1 shares_NN2 in_II the_AT mobile_JJ phone_NN1 industry_NN1 but_CCB has_VHZ lost_VVN a_AT1 lot_NN1 of_IO ground_NN1 to_II other_JJ players_NN2 on_II smartphones_NN2 ._. 
</s>
<s>
This_DD1 is_VBZ a_AT1 bad_JJ sign_NN1 for_IF Nokia_NP1 and_CC the_AT company_NN1 itself_PPX1 took_VVD to_II drastic_JJ marketing_NN1 campaigns_NN2 by_II hanging_VVG a_AT1 sign_NN1 in_II31 front_II32 of_II33 their_APPGE main_JJ shop_NN1 in_II Helsinki_NP1 ,_, promising_VVG that_CST something_PN1 amazing_JJ is_VBZ coming_VVG September_NPM1 7th_MD (_( see_VV0 iltalehti.fi:Nokialta_FO tulossa_NN1 jotain_NN1 mullistavaa_NN1 syyskuussa_NN1 ?_? )_) ._. 
</s>
<s>
That_DD1 day_NNT1 they_PPHS2 revealed_VVD their_APPGE new_JJ flagship_NN1 product_NN1 ,_, the_AT Lumia_NP1 920_MC and_CC Lumia_NP1 820_MC ._. 
</s>
<s>
When_CS the_AT first_MD advertising_NN1 movie_NN1 clips_NN2 became_VVD available_JJ huge_JJ protests_NN2 against_II Nokia_NP1 rose_VVD ,_, because_II21 of_II22 flaws_NN2 in_II one_MC1 of_IO the_AT clips_NN2 (_( see_VV0 HS.fi_NP1 :_: Nokia_NP1 :_: Harkinta_NP1 petti_NN2 mainosvideon_NN1 kytssand_NN1 appendix_NN1 1_MC1 :_: link_VV0 to_II Youtube_NP1 where_CS the_AT clip_NN1 can_VM be_VBI seen_VVN )_) ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) At_II Apple_NN1 and_CC Samsung_VVN on_II the_AT other_JJ hand_NN1 ,_, the_AT pressure_NN1 on_II the_AT market_NN1 can_VM be_VBI seen_VVN through_II lawsuits_NN2 against_II each_PPX221 other_PPX222 (_( see_VV0 HS.fi_NP1 :_: Applelle_NP1 taas_NN2 voitto_NN1 patenttikiistassa_NN1 ;_; HS.fi_NP1 :_: Patenttikiista_NP1 si_FW lhes_VVZ 10_MC miljardia_NN1 Samsungin_NN1 markkina-arvosta_NN1 )_) ._. 
</s>
<s>
This_DD1 all_DB goes_VVZ to_TO show_VVI that_CST there_EX is_VBZ a_RR21 lot_RR22 happening_VVG within_II the_AT business_NN1 and_CC that_DD1 is_VBZ why_RRQ I_PPIS1 believe_VV0 it_PPH1 is_VBZ worth_II making_VVG a_AT1 study_NN1 on_II the_AT sector_NN1 ._. 
</s>
<s>
Previous_JJ research_NN1 done_VDN about_II perceived_JJ value_NN1 whichconsumers_NN2 experience_VV0 when_CS using_VVG smartphones_NN2 is_VBZ hard_JJ to_TO find_VVI ._. 
</s>
<s>
For_REX21 example_REX22 Helkkula_NP1 and_CC Kelleher_NP1 (_( 2010_MC )_) have_VH0 done_VDN research_NN1 about_II perceived_JJ value_NN1 related_VVN to_II iPhones_NN2 service_VV0 experience_NN1 ,_, but_CCB as_CSA the_AT market_NN1 is_VBZ quickly_RR changing_VVG I_PPIS1 believe_VV0 it_PPH1 to_TO be_VBI highly_RR relevant_JJ with_IW an_AT1 overview_NN1 of_IO what_DDQ type_NN1 of_IO perceived_JJ value_NN1 people_NN experience_VV0 today.The_NNU model_NN1 I_PPIS1 have_VH0 chosen_VVN ,_, A_ZZ1 Theory_NN1 of_IO Consumption_NN1 Values_NN2 (_( TCV-model_NN1 )_) by_II Sheth_NP1 ,_, Newman_NP1 and_CC Gross_NP1 (_( 1991_MC )_) ,_, for_IF conducting_VVG the_AT study_NN1 is_VBZ a_AT1 well-established_JJ model_NN1 about_II customer_NN1 perceived_VVD value_NN1 and_CC will_VM be_VBI presented_VVN later_RRR on_RP in_II the_AT literature_NN1 review_NN1 section_NN1 of_IO the_AT paper_NN1 ._. 
</s>
<s>
1.1_MC Purpose_NN1 with_IW the_AT study_NN1 The_AT purpose_NN1 of_IO the_AT study_NN1 is_VBZ to_TO find_VVI out_RP what_DDQ type_NN1 of_IO perceived_JJ value_NN1 consumers_NN2 find_VV0 important_JJ in_II smartphones_NN2 today_RT ._. 
</s>
<s>
This_DD1 I_PPIS1 believe_VV0 to_TO be_VBI highly_RR relevant_JJ because_II21 of_II22 the_AT situation_NN1 on_II the_AT smartphone_NN1 market_NN1 ,_, explained_VVD above_RL ._. 
</s>
<s>
As_CSA also_RR explained_VVN earlier_RRR ,_, Nokia_NP1 ,_, which_DDQ has_VHZ been_VBN the_AT market_NN1 leader_NN1 for_IF many_DA2 years_NNT2 has_VHZ suddenly_RR dropped_VVN to_II second_MD place_NN1 and_CC people_NN are_VBR talking_VVG negatively_RR about_II the_AT companys_NN2 future_NN1 ._. 
</s>
<s>
The_AT Christmas_NNT1 market_NN1 will_VM be_VBI crucial_JJ ,_, as_CSA new_JJ releases_NN2 from_II Apple_NN1 (_( iPhone_VV0 5_MC )_) ,_, Nokia_NP1 (_( Lumia_NP1 920_MC and_CC 820_MC )_) and_CC also_RR from_II Samsung_NP1 (_( Galaxy_NN1 Note_NN1 2_MC )_) will_VM be_VBI seen_VVN ._. 
</s>
<s>
By_II making_VVG an_AT1 in_II depth_NN1 qualitative_JJ study_NN1 ,_, based_VVN on_II Sheth_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 1991_MC )_) TCV-model_NN1 ,_, I_PPIS1 hope_VV0 to_TO be_VBI able_JK to_TO answer_VVI the_AT research_NN1 question_NN1 of_IO my_APPGE paper_NN1 and_CC thus_RR being_VBG able_JK to_TO point_VVI out_RP what_DDQ general_JJ customers_NN2 are_VBR looking_VVG for_IF in_II a_AT1 smartphone_NN1 today_RT ._. 
</s>
<s>
The_AT research_NN1 question_NN1 is_VBZ :_: Which_DDQ types_NN2 of_IO perceived_JJ value_NN1 do_VD0 young_JJ consumers_NN2 look_VV0 for_IF when_CS buying_VVG a_AT1 smartphone_NN1 ?_? 1.2_MC Target_NN1 group_NN1 of_IO the_AT study_NN1 and_CC structure_NN1 of_IO the_AT paper_NN1 I_PPIS1 have_VH0 decided_VVN to_TO delimitate_VVI my_APPGE study_NN1 to_II young_JJ consumers_NN2 (_( under_RG 30_MC years_NNT2 old_JJ )_) ,_, firstly_RR because_CS it_PPH1 would_VM be_VBI too_RG much_DA1 to_TO cover_VVI all_DB age_NN1 groups_NN2 for_IF this_DD1 paper_NN1 and_CC secondly_RR because_CS I_PPIS1 believe_VV0 it_PPH1 is_VBZ the_AT most_RGT interesting_JJ segment_NN1 to_TO look_VVI at_II ._. 
</s>
<s>
Young_JJ consumers_NN2 are_VBR familiarized_VVN with_IW the_AT products_NN2 and_CC I_PPIS1 presume_VV0 they_PPHS2 demand_VV0 a_RR21 lot_RR22 more_RRR from_II the_AT products_NN2 than_CSN elderly_JJ consumers_NN2 would_VM do_VDI ._. 
</s>
<s>
By_II doing_VDG this_DD1 delimitation_NN1 I_PPIS1 am_VBM aware_JJ that_CST I_MC1 cant_NN1 generalize_VV0 my_APPGE results_NN2 for_IF consumers_NN2 in_RR21 general_RR22 but_CCB I_PPIS1 believe_VV0 that_DD1 is_VBZ not_XX either_RR the_AT point_NN1 when_CS doing_VDG a_AT1 qualitative_JJ study_NN1 ._. 
</s>
<s>
The_AT structure_NN1 of_IO the_AT paper_NN1 is_VBZ as_CSA follows_VVZ ._. 
</s>
<s>
Firstly_RR ,_, I_PPIS1 will_VM present_VVI the_AT theory_NN1 ,_, which_DDQ I_PPIS1 will_VM base_VVI my_APPGE empirical_JJ part_NN1 on_RP ,_, in_II the_AT literature_NN1 overview_NN1 section_NN1 ._. 
</s>
<s>
Secondly_RR ,_, I_PPIS1 will_VM briefly_RR go_VVI through_II the_AT methods_NN2 I_PPIS1 have_VH0 used_VVN in_II my_APPGE study_NN1 in_II the_AT methodology_NN1 section.Thirdly_NNU ,_, I_PPIS1 will_VM present_VVI the_AT results_NN2 and_CC analyze_VVI them_PPHO2 in_II the_AT results_NN2 and_CC analysis_NN1 section_NN1 and_CC finally_RR ,_, I_PPIS1 will_VM end_VVI the_AT paper_NN1 by_II the_AT discussion_NN1 and_CC conclusions_NN2 section_NN1 ._. 
</s>
<s>
1.3_MC Definition_NN1 of_IO terms_NN2 Will_VM do_VDI this_DD1 later_JJR 2_MC ._. 
</s>
<s>
Literature_NN1 overview_NN1 Due_II21 to_II22 the_AT limited_JJ space_NN1 ,_, I_PPIS1 will_VM narrow_VVI the_AT literature_NN1 review_NN1 to_TO focus_VVI on_II the_AT TCV-model_NN1 by_II Sheth_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 1991_MC )_) ._. 
</s>
<s>
For_IF a_AT1 more_RGR thorough_JJ overview_NN1 of_IO the_AT concept_NN1 perceived_VVD value_NN1 ,_, view_VV0 my_APPGE bachelor_NN1 thesis_NN1 (_( Lindholm_NP1 2012_MC :_: 5-15_MCMC )_) ,_, which_DDQ dealt_VVD with_IW the_AT concept_NN1 perceived_VVD value_NN1 in_II depth_NN1 ._. 
</s>
<s>
So_RR much_RR can_VM be_VBI said_VVN ,_, that_CST a_AT1 lot_NN1 of_IO information_NN1 about_II the_AT concept_NN1 can_VM be_VBI found_VVN in_II Snchez-Fernndez_NP1 &;_NULL Iniesta-Bonillos_NN2 (_( 2007_MC )_) articleThe_VV0 concept_NN1 of_IO perceived_JJ value_NN1 :_: a_AT1 systematic_JJ review_NN1 of_IO the_AT research_NN1 ._. 
</s>
<s>
To_TO jump_VVI straight_RR at_II it_PPH1 ,_, I_PPIS1 have_VH0 chosen_VVN to_TO use_VVI Sheth_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 1991_MC )_) TCV-model_NN1 as_II a_AT1 tool_NN1 ,_, on_II which_DDQ I_PPIS1 will_VM support_VVI my_APPGE interview_NN1 guide_NN1 ,_, and_CC in_II the_AT end_NN1 answer_VV0 my_APPGE research_NN1 question_NN1 with_IW ._. 
</s>
<s>
This_DD1 model_NN1 is_VBZ praised_VVN by_II researchers_NN2 as_CSA one_MC1 of_IO the_AT most_RRT worked_VVN out_RP models_NN2 on_II the_AT concept_NN1 perceived_VVD value_NN1 (_( e.g._REX Pura_NP1 2005_MC :_: 515_MC ;_; Pope_NP1 1998_MC :_: 126_MC ;_; Snchez-Fernndez_NP1 &;_NULL Iniesta-Bonillo_NP1 2007_MC :_: 442_MC )_) ._. 
</s>
<s>
When_CS I_ZZ1 in_II my_APPGE bachelor_NN1 thesis_NN1 applied_VVD the_AT TCV-model_NN1 on_II my_APPGE research_NN1 question_NN1 about_II tablets_NN2 (_( iPad_NN1 etc._RA )_) ,_, it_PPH1 turned_VVD out_RP providing_VVG good_JJ results_NN2 ._. 
</s>
<s>
This_DD1 is_VBZ why_RRQ I_PPIS1 strongly_RR believe_VV0 it_PPH1 will_VM serve_VVI as_II a_AT1 good_JJ theoretical_JJ model_NN1 for_IF this_DD1 product_NN1 segment_NN1 as_RR21 well_RR22 ._. 
</s>
<s>
2.1_MC TCV-model_NN1 by_II Sheth_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 1991_MC )_) The_AT theory_NN1 of_IO consumption_NN1 values_NN2 model_NN1 (_( TCV-model_NN1 )_) ,_, is_VBZ a_AT1 model_NN1 which_DDQ explains_VVZ why_RRQ consumers_NN2 do_VD0 the_AT choices_NN2 they_PPHS2 do_VD0 in_II a_AT1 consumption_NN1 situation_NN1 (_( Sheth_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
1991_MC )_) ._. 
</s>
<s>
The_AT model_NN1 ,_, developed_VVN by_II Sheth_NP1 ,_, Newman_NP1 and_CC Gross_NP1 provides_VVZ five_MC different_JJ types_NN2 of_IO categories_NN2 of_IO perceived_JJ value_NN1 which_DDQ can_VM influence_VVI a_AT1 consumer_NN1 during_II consumption_NN1 ._. 
</s>
<s>
The_AT TCV-model_NN1 and_CC its_APPGE categories_NN2 of_IO perceived_JJ value_NN1 can_VM be_VBI seen_VVN in_II figure_NN1 1_MC1 below_RL and_CC are_VBR as_CSA follows_VVZ :_: functional_JJ value_NN1 ,_, conditional_JJ value_NN1 ,_, social_JJ value_NN1 ,_, emotional_JJ value_NN1 and_CC epistemic_JJ value_NN1 ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) Functional_JJ value_NN1 Sheth_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 1991_MC )_) describe_VV0 that_CST an_AT1 alternative_NN1 (_( product_NN1 or_CC service_NN1 )_) acquires_VVZ functional_JJ value_NN1 for_IF the_AT consumer_NN1 if_CS the_AT alternative_NN1 has_VHZ extraordinary_JJ functional_JJ or_CC material_NN1 attributes_NN2 ._. 
</s>
<s>
Further_RRR the_AT authors_NN2 point_VV0 out_RP that_CST this_DD1 category_NN1 of_IO perceived_JJ value_NN1 is_VBZ traditionally_RR seen_VVN as_II the_AT category_NN1 giving_VVG most_DAT influence_VV0 on_II a_AT1 consumers_NN2 decision_NN1 to_TO buy_VVI or_CC not_XX to_TO buy_VVI an_AT1 alternative_NN1 ._. 
</s>
<s>
To_TO lift_VVI up_RP a_AT1 couple_NN1 examples_NN2 of_IO what_DDQ it_PPH1 concretely_RR can_VM mean_VVI I_PPIS1 would_VM like_VVI to_TO give_VVI a_AT1 couple_NN1 of_IO examples_NN2 of_IO the_AT results_NN2 from_II my_APPGE bachelor_NN1 thesis_NN1 ._. 
</s>
<s>
The_AT respondents_NN2 I_PPIS1 interviewed_VVD for_IF my_APPGE thesis_NN1 ,_, about_II perceived_JJ value_NN1 of_IO tablets_NN2 ,_, were_VBDR clearly_RR most_RRT influenced_VVN by_II this_DD1 category_NN1 ._. 
</s>
<s>
The_AT respondents_NN2 mentioned_VVD attributes_NN2 such_II21 as_II22 the_AT mobility_NN1 of_IO a_AT1 tablet_NN1 ,_, itsdurability_NN1 ,_, its_APPGE camera_NN1 ,_, its_APPGE weight_NN1 and_CC its_APPGE size_NN1 as_CSA important_JJ functional_JJ values_NN2 influencing_VVG their_APPGE perceived_JJ value_NN1 of_IO the_AT tablets_NN2 ._. 
</s>
<s>
(_( Lindholm_NP1 2012_MC :_: 36_MC )_) 2.1.1_MC Conditional_JJ value_NN1 The_AT second_MD category_NN1 ,_, in_II figure_NN1 1_MC1 ,_, is_VBZ conditional_JJ value_NN1 ._. 
</s>
<s>
This_DD1 category_NN1 of_IO perceived_JJ value_NN1 Sheth_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 1991_MC )_) describe_VV0 that_CST consumers_NN2 perceive_VV0 if_CSW something_PN1 changes_VVZ in_II their_APPGE life_NN1 ,_, or_CC in_II their_APPGE environment_NN1 and_CC that_CST they_PPHS2 because_II21 of_II22 this_DD1 feel_NN1 value_NN1 of_IO the_AT product_NN1 or_CC service_NN1 ._. 
</s>
<s>
There_EX are_VBR plenty_PN of_IO examples_NN2 to_TO give_VVI for_IF this_DD1 type_NN1 of_IO perceived_JJ value_NN1 ._. 
</s>
<s>
If_CS you_PPY get_VV0 sick_JJ ,_, you_PPY will_VM perceive_VVI conditional_JJ value_NN1 from_II the_AT service_NN1 of_IO a_AT1 doctor_NN1 or_CC nurse_NN1 ._. 
</s>
<s>
If_CS you_PPY begin_VV0 studying_VVG you_PPY might_VM need_VVI a_AT1 laptop_NN1 and_CC therefore_RR perceive_VV0 conditional_JJ value_NN1 for_IF the_AT laptop_NN1 and_RR31 so_RR32 on_RR33 ._. 
</s>
<s>
In_II my_APPGE bachelor_NN1 thesis_NN1 my_APPGE respondents_NN2 lifted_VVD up_RP perceived_JJ conditional_JJ value_NN1 of_IO a_AT1 tablet_NN1 because_II21 of_II22 studies_NN2 ,_, work_NN1 and_CC also_RR because_II21 of_II22 travelling_NN1 (_( Lindholm_NP1 2012_MC :_: 36_MC )_) ._. 
</s>
<s>
2.1.2_MC Social_JJ value_NN1 The_AT third_MD category_NN1 ,_, social_JJ value_NN1 ,_, quite_RG far_RR describes_VVZ itself_PPX1 what_DDQ type_NN1 of_IO perceived_JJ value_NN1 it_PPH1 contains_VVZ of_IO ._. 
</s>
<s>
Sheth_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 1991_MC )_) describe_VV0 that_CST social_JJ value_NN1 can_VM only_RR be_VBI perceived_VVN if_CS products_NN2 ,_, which_DDQ others_NN2 can_VM see_VVI ,_, for_REX21 example_REX22 cars_NN2 or_CC clothes_NN2 ,_, are_VBR consumed_VVN ,_, or_CC if_CS service_NN1 experiences_NN2 meant_VVD to_TO be_VBI shared_VVN are_VBR consumed_VVN ._. 
</s>
<s>
The_AT authors_NN2 also_RR mention_VV0 that_CST things_NN2 like_II status_NN1 and_CC communities_NN2 belong_VV0 to_II this_DD1 category_NN1 ._. 
</s>
<s>
This_DD1 means_VVZ that_CST if_CS you_PPY feel_VV0 added/degraded_JJ status_NN1 or_CC if_CS you_PPY feel_VV0 that_CST you_PPY belong_VV0 to_II some_DD community_NN1 through_II the_AT product_NN1 or_CC service_NN1 ,_, you_PPY are_VBR experiencing_VVG perceived_JJ social_JJ value_NN1 ._. 
</s>
<s>
The_AT respondents_NN2 in_II my_APPGE bachelor_NN1 thesis_NN1 mentioned_VVD added_JJ status_NN1 ,_, respect_NN1 and_CC feeling_VVG that_CST they_PPHS2 belong_VV0 to_II a_AT1 community_NN1 (_( especially_RR Apples_NN2 community_NN1 )_) as_CSA perceived_VVN value_NN1 that_CST they_PPHS2 received_VVD of_IO a_AT1 tablet_NN1 ._. 
</s>
<s>
2.1.3_MC Emotional_JJ value_NN1 Sheth_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 1991_MC )_) describe_VV0 that_CST an_AT1 alternative_NN1 acquires_VVZ emotional_JJ value_NN1 if_CS you_PPY through_II the_AT product_NN1 or_CC service_NN1 get_VV0 some_DD kind_NN1 of_IO specific_JJ feeling_NN1 ._. 
</s>
<s>
Also_RR if_CS you_PPY manage_VV0 to_TO keep_VVI or_CC preserve_VVI a_AT1 specific_JJ feeling_NN1 by_II a_AT1 product_NN1 or_CC service_VV0 you_PPY perceive_VV0 emotional_JJ value_NN1 ._. 
</s>
<s>
Sheth_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 1991_MC )_) gives_VVZ an_AT1 example_NN1 by_II mentioning_VVG that_CST you_PPY for_REX21 example_REX22 can_VM have_VHI a_AT1 love_NN1 affair_NN1 with_IW a_AT1 car_NN1 and_CC therefore_RR get_VV0 perceived_JJ emotional_JJ value_NN1 from_II the_AT car_NN1 ._. 
</s>
<s>
The_AT respondents_NN2 in_II my_APPGE bachelor_NN1 thesis_NN1 downplayed_VVD the_AT category_NN1 of_IO perceived_JJ value_NN1 ,_, but_CCB still_RR some_DD mentioned_VVD that_CST they_PPHS2 felt_VVD safe_JJ by_II choosing_VVG Apples_NN2 iPad_NN1 tablet_NN1 ._. 
</s>
<s>
This_DD1 they_PPHS2 felt_VVD because_CS it_PPH1 is_VBZ the_AT market_NN1 leader_NN1 and_CC because_CS so_RG many_DA2 are_VBR talking_VVG about_II the_AT iPad_NN1 ._. 
</s>
<s>
Some_DD also_RR mentioned_VVD they_PPHS2 felt_VVD fresh_JJ and_CC modern_JJ by_II having_VHG a_AT1 tablet_NN1 ._. 
</s>
<s>
(_( Lindholm_NP1 2012_MC :_: 36_MC )_) 2.1.4_MC Epistemic_JJ value_NN1 The_AT last_MD category_NN1 of_IO the_AT TCV-model_NN1 is_VBZ epistemic_JJ value_NN1 ._. 
</s>
<s>
Sheth_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 1991_MC )_) describe_VV0 that_CST an_AT1 alternative_NN1 (_( product/service_NN1 )_) gets_VVZ epistemic_JJ value_NN1 if_CS it_PPH1 leads_VVZ to_II something_PN1 new_JJ ._. 
</s>
<s>
Also_RR if_CS it_PPH1 leads_VVZ to_II curiosity_NN1 and_CC the_AT need_NN1 ,_, or_CC longing_VVG for_IF knowledge_NN1 ,_, it_PPH1 gets_VVZ epistemic_JJ value_NN1 ._. 
</s>
<s>
The_AT authors_NN2 mean_VV0 that_CST if_CS a_AT1 consumer_NN1 is_VBZ bored_VVN at_II a_AT1 specific_JJ trademark_NN1 ,_, simply_RR a_AT1 change_NN1 to_II a_AT1 new_JJ trademark_NN1 can_VM lead_VVI to_II epistemic_JJ value_NN1 ._. 
</s>
<s>
The_AT respondents_NN2 in_II my_APPGE bachelor_NN1 thesis_NN1 mentioned_VVD that_CST tablets_NN2 gave_VVD them_PPHO2 epistemic_JJ value_NN1 in_II that_DD1 it_PPH1 wakes_VVZ curiosity_NN1 and_CC most_RGT importantly_RR for_IF some_DD of_IO my_APPGE respondents_NN2 it_PPH1 offers_VVZ a_AT1 totally_RR new_JJ platform_NN1 for_IF reading_VVG ._. 
</s>
<s>
(_( Lindholm_NP1 2012_MC :_: 36_MC )_) 2.2_MC Conclusion_NN1 of_IO the_AT literature_NN1 overview_NN1 In_II this_DD1 short_JJ paper_NN1 I_PPIS1 do_VD0 not_XX have_VHI the_AT space_NN1 to_TO go_VVI through_II what_DDQ has_VHZ been_VBN studied_VVN about_II the_AT concept_NN1 perceived_VVD value_NN1 ._. 
</s>
<s>
I_PPIS1 have_VH0 therefore_RR added_VVN some_DD sources_NN2 in_II the_AT beginning_NN1 of_IO this_DD1 chapter_NN1 for_IF a_AT1 more_RGR detailed_JJ picture_NN1 over_II this_DD1 concept_NN1 ._. 
</s>
<s>
Instead_RR I_PPIS1 have_VH0 jumped_VVN straight_RR at_II the_AT TCV-model_NN1 by_II Sheth_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 1991_MC )_) ,_, by_II presenting_VVG its_APPGE categories_NN2 one_MC1 by_II one_MC1 ._. 
</s>
<s>
I_PPIS1 have_VH0 also_RR provided_VVN examples_NN2 both_RR from_II the_AT creators_NN2 of_IO the_AT model_NN1 and_CC from_II my_APPGE bachelor_NN1 thesis_NN1 which_DDQ was_VBDZ based_VVN on_II the_AT model_NN1 ._. 
</s>
<s>
It_PPH1 should_VM be_VBI clear_JJ by_II know_VV0 that_CST this_DD1 study_NN1 will_VM also_RR be_VBI based_VVN on_II the_AT same_DA model_NN1 and_CC therefore_RR ,_, I_PPIS1 will_VM now_RT go_VVI on_RP ,_, to_TO describe_VVI the_AT methodology_NN1 I_PPIS1 have_VH0 chosen_VVN to_TO use_VVI in_II this_DD1 study_NN1 to_TO answer_VVI my_APPGE research_NN1 question_NN1 ._. 
</s>
<s>
3_MC ._. 
</s>
<s>
Methodology_NN1 I_PPIS1 have_VH0 decided_VVN to_TO choose_VVI in_II depth_NN1 semi_JJ structured_JJ interviews_NN2 as_CSA my_APPGE method_NN1 and_CC base_VV0 the_AT interview_NN1 guide_NN1 on_II the_AT TCV-model_NN1 by_II Sheth_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 1991_MC )_) ._. 
</s>
<s>
This_DD1 means_VVZ I_PPIS1 will_VM be_VBI doing_VDG a_AT1 qualitative_JJ study_NN1 and_CC I_PPIS1 will_VM interview_VVI 4-8_MCMC persons_NN2 ._. 
</s>
<s>
For_IF the_AT draft_NN1 I_PPIS1 have_VH0 decided_VVN not_XX to_TO go_VVI further_RRR because_CS I_PPIS1 will_VM need_VVI space_NN1 for_IF the_AT results_NN2 and_CC analysis_NN1 section_NN1 and_CC wonder_VV0 how_RGQ important_JJ the_AT methodology_NN1 part_NN1 is_VBZ for_IF the_AT final_JJ paper_NN1 ?_? 
</s>
<s>
Do_VD0 we_PPIS2 need_VVI to_TO go_VVI through_II all_DB the_AT steps_NN2 below_RL ,_, as_CSA I_PPIS1 did_VDD in_II my_APPGE bachelor_NN1 thesis_NN1 or_CC is_VBZ it_PPH1 enough_RR to_II just_RR briefly_RR present_VV0 what_DDQ method_NN1 we_PPIS2 will_VM use_VVI and_CC shortly_RR explain_VVI why_RRQ ?_? ...._... 3.1_MC The_AT chosen_JJ method_NN1 3.2_MC Discussion_NN1 about_II the_AT sample_NN1 3.3_MC Gathering_NN1 of_IO the_AT data_NN 3.4_MC The_AT interview_NN1 guide_NN1 3.5_MC The_AT validity_NN1 and_CC reliability_NN1 of_IO the_AT study_NN1 3.6_MC Conclusion_NN1 of_IO the_AT methodology_NN1 4_MC ._. 
</s>
<s>
Results_NN2 and_CC analysis_NN1 Will_VM do_VDI this_DD1 part_NN1 later_JJR 4.1_MC Results_NN2 and_CC analysis_NN1 related_VVN to_II functional_JJ value_NN1 4.2_MC Results_NN2 and_CC analysis_NN1 related_VVN to_II conditional_JJ value_NN1 4.3_MC Results_NN2 and_CC analysis_NN1 related_VVN to_II social_JJ value_NN1 4.4_MC Results_NN2 and_CC analysis_NN1 related_VVN to_II emotional_JJ value_NN1 4.5_MC Results_NN2 and_CC analysis_NN1 related_VVN to_II epistemic_JJ value_NN1 5_MC ._. 
</s>
<s>
Discussion_NN1 and_CC conclusions_NN2 Will_VM be_VBI done_VDN after_II results_NN2 and_CC analysis_NN1 part_NN1 is_VBZ finished_VVN 
</s>
