<s>
Factors_NN2 influencing_VVG the_AT college_NN1 student_NN1 choice_NN1 of_IO school_NN1 souvenir-cloth_NN1 in_II University_NN1 of_IO Helsinki_NP1 :_: A_AT1 conjoint_NN1 study_NN1 1_MC1 Introduction_NN1 ._. 
</s>
<s>
The_AT aim_NN1 of_IO this_DD1 paper_NN1 is_VBZ to_TO report_VVI a_AT1 study_NN1 that_CST deal_VV0 with_IW the_AT choice_NN1 of_IO school_NN1 souvenir_NN1 ,_, which_DDQ is_VBZ especially_RR on_II cloth_NN1 with_IW UH_UH logo_NN1 ._. 
</s>
<s>
To_TO evaluate_VVI the_AT factors_NN2 affect_VV0 the_AT result_NN1 ,_, conjoint_VV0 analysis_NN1 :_: a_AT1 multivariate_JJ technique_NN1 developed_VVD specifically_RR to_TO understand_VVI how_RRQ respondents_NN2 develop_VV0 preferences_NN2 for_IF any_DD type_NN1 of_IO object_NN1 (_( products_NN2 services_NN2 ,_, or_CC ideas_NN2 )_) (_( Hair_NN1 et_RA21 al_RA22 409._MC ,_, 2010_MC )_) is_VBZ being_VBG used_VVN ,_, and_CC make_VV0 a_AT1 contribute_VV0 to_II analyses_NN2 product_NN1 choice_NN1 by_II students_NN2 ._. 
</s>
<s>
The_AT first_MD objective_NN1 of_IO this_DD1 paper_NN1 is_VBZ to_TO find_VVI important_JJ attributes_NN2 of_IO school_NN1 cloth_NN1 from_II the_AT students_NN2 perspective_NN1 ._. 
</s>
<s>
Second_MD ,_, explore_VV0 group_NN1 differences_NN2 between_II man_NN1 and_CC woman_NN1 depends_VVZ on_II their_APPGE own_DA willingness_NN1 of_IO the_AT differentiate_VV0 aspects_NN2 ._. 
</s>
<s>
At_RR21 last_RR22 ,_, the_AT interest_NN1 gap_NN1 between_II four_MC different_JJ campuses_NN2 of_IO university_NN1 of_IO Helsinki_NP1 ._. 
</s>
<s>
The_AT next_MD section_NN1 provides_VVZ a_AT1 brief_JJ introduction_NN1 of_IO the_AT market_NN1 ._. 
</s>
<s>
According_II21 to_II22 the_AT University_NN1 of_IO Helsinki_NP1 annual_JJ report_NN1 2010_NN1 (_( Table_NN1 1.1_MC )_) ,_, there_EX are_VBR 36609_MC students_NN2 including_II undergraduate_NN1 ,_, master_NN1 and_CC PHD_NN1 students_NN2 in_II four_MC school_NN1 campus-_NN1 City_NN1 Centre_NN1 Campus_NN1 ,_, Kumpula_JJ Science_NN1 Campus_NN1 ,_, Meilahti_JJ Campus_NN1 for_IF Medicine_NN1 and_CC Viikki_JJ Campus_NN1 ._. 
</s>
<s>
University_NN1 of_IO Helsinki_NP1 has_VHZ approximately_RR 4,000_MC researchers_NN2 and_CC teachers_NN2 ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) It_PPH1 is_VBZ no_AT wonder_NN1 that_CST college_NN1 life_NN1 is_VBZ one_MC1 of_IO the_AT most_RGT important_JJ periods_NN2 through_II the_AT majority_NN1 of_IO people_NN 's_GE whole_JJ life_NN1 ._. 
</s>
<s>
To_TO be_VBI a_AT1 current_JJ student_NN1 especially_RR an_AT1 alumni_NN2 willing_JJ to_TO have_VHI something_PN1 remind_VV0 his/her_APPGE memory_NN1 in_II college_NN1 ._. 
</s>
<s>
Nowadays_RT ,_, school_NN1 uniform_NN1 is_VBZ not_XX that_DD1 popular_JJ among_II college_NN1 students_NN2 who_PNQS do_VD0 not_XX prefer_VVI wearing_VVG the_AT same_DA cloth_NN1 every_AT1 day_NNT1 and_CC no_UH their_APPGE own_DA style_NN1 ._. 
</s>
<s>
However_RR ,_, student_NN1 union_NN1 of_IO each_DD1 school_NN1 produces_VVZ hoodie_NN1 ,_, T-shirts_NN2 ,_, and_CC Thermal_JJ shirts_NN2 within_II its_APPGE own_DA school_NN1 logo_NN1 ,_, which_DDQ is_VBZ popular_JJ in_II American_JJ and_CC west_ND1 European_NN1 ._. 
</s>
<s>
In_II the_AT Nordic_JJ countries_NN2 universities_NN2 ,_, such_II21 as_II22 University_NN1 of_IO Helsinki_NP1 ,_, it_PPH1 is_VBZ hard_JJ to_TO find_VVI a_AT1 shirt_NN1 of_IO hoodie_NN1 with_IW UH_UH logo.Thus_NNU ,_, it_PPH1 has_VHZ become_VVN very_RG important_JJ for_IF school_NN1 union_NN1 managers_NN2 to_TO understand_VVI more_RRR about_II the_AT consumer_NN1 behavior_NN1 of_IO students_NN2 and_CC alumnus_NN1 ,_, especially_RR about_II what_DDQ influences_VVZ students_NN2 decisions_NN2 when_CS choosing_VVG a_AT1 school_NN1 logo_NN1 cloth_NN1 ._. 
</s>
<s>
2_MC Methods_NN2 ._. 
</s>
<s>
From_II the_AT book_NN1 (_( Hair_NN1 et_RA21 al_RA22 ,_, 2010_MC )_) list_VV0 the_AT steps_NN2 to_TO do_VDI conjoint_NN1 analysis_NN1 :_: a_ZZ1 )_) Define_VV0 the_AT attributes_NN2 (_( utility_NN1 ,_, factors_NN2 ,_, levels_NN2 and_CC profiles_NN2 )_) ._. 
</s>
<s>
b_ZZ1 )_) Gathering_VVG preferences_NN2 evaluation_NN1 from_II respondents_NN2 ._. 
</s>
<s>
c_ZZ1 )_) Using_VVG multiple_JJ regressions_NN2 to_TO estimate_VVI par-worths._JJ d_ZZ1 )_) Compute_VV0 the_AT importance_NN1 of_IO each_DD1 factor_NN1 ._. 
</s>
<s>
e_ZZ1 )_) Assessing_VVG predictive_JJ accuracy_NN1 ._. 
</s>
<s>
Full-profile_JJ method_NN1 ,_, pairwise_RR comparison_NN1 method_NN1 ,_, and_CC trade-off_NN1 approach_NN1 had_VHD been_VBN widely_RR present_JJ in_II the_AT research_NN1 paper_NN1 ._. 
</s>
<s>
Full-profile_NN1 is_VBZ concluding_VVG the_AT factors_NN2 and_CC number_NN1 of_IO factors_NN2 is_VBZ fewer_DAR than_CSN 6_MC ._. 
</s>
<s>
Pairwise_RR comparison_NN1 method_NN1 lists_VVZ a_AT1 rating_NN1 scale_NN1 to_TO show_VVI the_AT strength_NN1 of_IO each_DD1 factor_NN1 ,_, and_CC applicants_NN2 mark_VV0 the_AT score_NN1 individual_NN1 ._. 
</s>
<s>
Trade-off_NN1 approach_NN1 is_VBZ mainly_RR compares_VVZ two_MC choices_NN2 by_II ranking_VVG all_DB combinations_NN2 of_IO levels_NN2 ._. 
</s>
<s>
In_II academic_JJ literature_NN1 ,_, the_AT full_JJ profile_NN1 method_NN1 has_VHZ been_VBN the_AT most_RGT used_JJ approach_NN1 to_TO conjoint_VVI analysis_NN1 ._. 
</s>
<s>
However_RR ,_, this_DD1 method_NN1 has_VHZ few_DA2 limitations_NN2 only_RR suit_VV0 small_JJ numbers_NN2 of_IO attributes_NN2 and_CC has_VHZ technique_NN1 problems_NN2 of_IO the_AT conclusion_NN1 when_CS concerning_VVG larger_JJR numbers_NN2 of_IO attributes_NN2 ._. 
</s>
<s>
3_MC Conjoint_NN1 studies_NN2 with_IW SPSS_NP1 ._. 
</s>
<s>
To_TO identify_VVI the_AT factors_NN2 influence_VV0 the_AT willingness_NN1 of_IO purchase_NN1 school_NN1 souvenir-cloth_NN1 ,_, relevant_JJ products_NN2 attributes_VVZ list_NN1 below_RL ._. 
</s>
<s>
Color_NN1 (_( Black_NP1 ,_, Red_JJ ,_, and_CC Yellow_JJ )_) ._. 
</s>
<s>
Pattern_NN1 (_( T-shirt_NN1 ,_, Hoodies_NP1 )_) ._. 
</s>
<s>
Material_NN1 (_( Cotton_NP1 ,_, Lycra_NP1 )_) ._. 
</s>
<s>
Sample_NN1 Twelve_MC students_NN2 of_IO the_AT University_NN1 of_IO Helsinkitaking_VVG the_AT questionnaires_NN2 and_CC four_MC of_IO them_PPHO2 do_VD0 not_XX need_VVI those_DD2 products_NN2 ._. 
</s>
<s>
Other_JJ eight_MC students_NN2 are_VBR coming_VVG from_II four_MC different_JJ campuses_NN2 of_IO University_NN1 of_IO Helsinki_NP1 ,_, and_CC ranked_VVN 8_MC hypothetical_JJ combinations_NN2 to_TO show_VVI their_APPGE choice_NN1 preference_NN1 ._. 
</s>
<s>
There_EX are_VBR four_MC men_NN2 and_CC four_MC women_NN2 participle_VV0 in_II questionnaires_NN2 ,_, and_CC all_DB of_IO them_PPHO2 are_VBR current_JJ students_NN2 of_IO University_NN1 of_IO Helsinki_NP1 ._. 
</s>
<s>
Result_VV0 1_MC1 )_) Part-worths_NN2 and_CC important_JJ of_IO attributes_NN2 Table_NN1 3.1shows_FO the_AT part-worth_JJ utility_NN1 scores_NN2 for_IF each_DD1 level_NN1 of_IO those_DD2 attributes_NN2 ._. 
</s>
<s>
Among_II three_MC attributes_NN2 ,_, Color_NN1 is_VBZ the_AT most_RGT essential_JJ factor_NN1 (_( 70.051%_FO )_) ,_, which_DDQ illustrates_VVZ the_AT color_NN1 of_IO the_AT cloth_NN1 lead_VV0 the_AT choice_NN1 of_IO students_NN2 ._. 
</s>
<s>
Compare_VV0 with_IW type_NN1 of_IO materials_NN2 ,_, Pattern_NN1 seems_VVZ a_AT1 bit_NN1 of_IO important_JJ than_CSN material_NN1 when_RRQ students_NN2 consider_VV0 buying_VVG a_AT1 school_NN1 souvenir-cloth_NN1 ,_, but_CCB not_XX much_DA1 more_DAR difference_NN1 ._. 
</s>
<s>
The_AT value_NN1 of_IO Pearsons_NP2 R=0.787_FO and_CC Kendalls_NP2 tau=.837_FO contribute_VV0 the_AT stability_NN1 of_IO the_AT result_NN1 of_IO SPSS_NP1 ._. 
</s>
<s>
Furthermore_RR ,_, the_AT utility_NN1 of_IO each_DD1 level_NN1 should_VM also_RR be_VBI taken_VVN into_II consideration_NN1 ._. 
</s>
<s>
With_IW color_NN1 ,_, the_AT most_DAT utility_NN1 was_VBDZ picking_VVG up_RP yellow_JJ (_( U=_FO ,_, 844_MC )_) ._. 
</s>
<s>
Meanwhile_RR the_AT utility_NN1 of_IO Black_NP1 (_( U=-_FO ,_, 625_MC )_) ,_, and_CC the_AT utility_NN1 of_IO Red_JJ (_( U=-_FO ,_, 219_MC )_) ._. 
</s>
<s>
It_PPH1 means_VVZ students_NN2 are_VBR more_RGR likely_JJ to_TO purchase_VVI school_NN1 souvenir-cloth_NN1 with_IW the_AT color_NN1 of_IO red_NN1 ._. 
</s>
<s>
From_II the_AT Chart_NN1 3.2_MC Summary_NN1 utilities_NN2 of_IO Pattern_NN1 ,_, the_AT material_NN1 of_IO Hoodies_NP1 is_VBZ more_RGR popular_JJ and_CC supported_VVN by_II students_NN2 than_CSN T-shirt_NN1 ._. 
</s>
<s>
Through_II the_AT analysis_NN1 of_IO Chart_NN1 3.3_MC Summary_NN1 utilities_NN2 of_IO Material_NN1 ,_, it_PPH1 is_VBZ no_AT wonder_NN1 that_CST students_NN2 prefer_VV0 the_AT more_DAR comfort_NN1 and_CC quality_NN1 material_NN1 cotton_NN1 than_CSN Lycra_NP1 ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) &lsqb;_( Figure_NN1 &rsqb;_) &lsqb;_( Figure_NN1 &rsqb;_) &lsqb;_( Figure_NN1 &rsqb;_) 2_MC )_) Group_NN1 difference_NN1 for_IF four_MC different_JJ campuses_NN2 ._. 
</s>
<s>
Students_NN2 in_II four_MC school_NN1 campus-_NN1 City_NN1 Centre_NN1 Campus_NN1 ,_, Kumpula_JJ Science_NN1 Campus_NN1 ,_, Meilahti_JJ Campus_NN1 for_IF Medicine_NN1 and_CC Viikki_JJ Campus_NN1 are_VBR being_VBG distinguished_VVN with_IW majors_NN2 and_CC subjects_NN2 ._. 
</s>
<s>
Table_NN1 3.2_MC shows_VVZ students_NN2 in_II City_NN1 Centre_NN1 campus_NN1 prefer_VV0 red_JJ than_CSN other_JJ two_MC colors_NN2 ,_, and_CC Color_NN1 looks_VVZ less_RGR important_JJ than_CSN three_MC others_NN2 campuses_NN2 (_( 55.128_MC )_) ._. 
</s>
<s>
The_AT reason_NN1 might_VM be_VBI in_II City_NN1 Centre_NN1 campus_NN1 ,_, majors_NN2 are_VBR more_DAR focus_NN1 on_II Arts_NN2 ,_, which_DDQ induce_VV0 students_NN2 have_VH0 partiality_NN1 for_IF bright_JJ colors_NN2 such_II21 as_II22 Red_JJ (_( U=1.833_FO )_) and_CC yellow_JJ (_( U=-0.167_FO )_) ._. 
</s>
<s>
For_IF the_AT students_NN2 in_II Kumpula_JJ Science_NN1 Campus_NN1 ,_, Meilahti_JJ Campus_NN1 for_IF Medicine_NN1 and_CC Vicki_NP1 Campus_NN1 ,_, three_MC tables_NN2 do_VD0 not_XX have_VHI show_NN1 significance_NN1 difference_NN1 among_II each_PPX221 other_PPX222 ._. 
</s>
<s>
It_PPH1 is_VBZ because_CS all_DB of_IO three_MC campuses_NN2 ,_, students_NN2 are_VBR subject_II21 to_II22 Science_NN1 ._. 
</s>
<s>
However_RR ,_, the_AT utility_NN1 of_IO Lycra_NP1 (_( U=0.125_FO )_) students_NN2 in_II Viikki_JJ campus_NN1 is_VBZ higher_JJR than_CSN the_AT utility_NN1 of_IO cotton_NN1 (_( -.125_MC )_) ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) &lsqb;_( Table_NN1 &rsqb;_) &lsqb;_( Table_NN1 &rsqb;_) &lsqb;_( Table_NN1 &rsqb;_) &lsqb;_( Table_NN1 &rsqb;_) 3_MC )_) Group_NN1 difference_NN1 forman_NN1 and_CC woman_NN1 Its_APPGE obvious_JJ that_CST men_NN2 and_CC women_NN2 have_VH0 significant_JJ different_JJ preference_NN1 toward_II the_AT color_NN1 of_IO the_AT cloth_NN1 ._. 
</s>
<s>
From_II the_AT table_NN1 3.6_MC ,_, the_AT utility_NN1 of_IO red(U=1,229)and_FO yellow_JJ (_( U=0,854_FO )_) are_VBR higher_JJR than_CSN the_AT utility_NN1 of_IO black_JJ (_( U=-2,083_FO )_) ._. 
</s>
<s>
Both_DB2 of_IO men_NN2 and_CC women_NN2 are_VBR in_II31 favor_II32 of_II33 Hoddies_NP1 and_CC cotton_NN1 ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) 4_MC Discussion_NN1 and_CC Conclusions_NN2 In_II conclusion_NN1 ,_, conjoint_VV0 analysis_NN1 found_VVD that_CST the_AT ideal_JJ school_NN1 souvenir-cloth_NN1 is_VBZ the_AT color_NN1 of_IO yellow_JJ ,_, 100%_NNU cotton_NN1 of_IO Hoodies_NP1 ._. 
</s>
<s>
School_NN1 union_NN1 managers_NN2 who_PNQS in_II31 charge_II32 of_II33 design_NN1 and_CC sell_VV0 school_NN1 souvenir-cloth_NN1 can_VM evaluate_VVI the_AT results_NN2 of_IO each_DD1 factorthrough_NN1 conjoint_NN1 analysis_NN1 to_TO identify_VVI how_RRQ and_CC in_II which_DDQ parts_NN2 can_VM increase_VVI the_AT students_NN2 utility_NN1 ,_, and_CC at_RR21 last_RR22 improve_VV0 the_AT market_NN1 performance_NN1 in_II the_AT field_NN1 of_IO school_NN1 souvenir-cloth.In_JJ Finland_NP1 ,_, there_EX are_VBR 16_MC universities_NN2 and_CC more_DAR than_CSN 27_MC universities_NN2 of_IO applied_JJ sciences_NN2 ._. 
</s>
<s>
Such_DA a_AT1 potential_JJ market_NN1 encourages_VVZ school_NN1 union_NN1 managers_NN2 to_TO focus_VVI on_II the_AT school_NN1 souvenir_NN1 ._. 
</s>
<s>
However_RR ,_, due_II21 to_II22 the_AT limitation_NN1 of_IO conjoint_NN1 analysis_NN1 still_RR some_DD key_JJ factors_NN2 havent_NN1 been_VBN list_NN1 in_II this_DD1 research_NN1 ,_, such_II21 as_II22 price_NN1 ,_, size_NN1 ,_, and_CC brand_NN1 of_IO the_AT cloth_NN1 ._. 
</s>
<s>
The_AT reason_NN1 why_RRQ this_DD1 paper_NN1 choose_VV0 the_AT other_JJ three_MC attributes_NN2 ,_, pattern_NN1 and_CC material_NN1 determine_VV0 price_NN1 ._. 
</s>
<s>
Its_APPGE hard_JJ to_TO say_VVI which_DDQ would_VM be_VBI an_AT1 ideal_JJ price_NN1 for_IF all_DB students_NN2 ._. 
</s>
<s>
Whats_NN2 more_RRR ,_, only_RR eight_MC students_NN2 participle_VV0 in_II this_DD1 market_NN1 research_NN1 can_VM not_XX represent_VVI the_AT real_JJ needs_NN2 of_IO all_DB students_NN2 ._. 
</s>
<s>
Thats_NN2 to_TO say_VVI ,_, the_AT result_NN1 of_IO this_DD1 researchcan_NN1 only_RR be_VBI a_AT1 small_JJ index_NN1 when_CS school_NN1 union_NN1 managers_NN2 make_VV0 decision_NN1 ._. 
</s>
