<s>
Green_JJ Supply_NN1 Chain_NN1 Management_NN1 1_MC1 INTRODUCTION_NN1 As_CSA there_EX have_VH0 been_VBN more_RGR and_CC more_DAR evidence_NN1 of_IO climate-changes_NN2 ,_, the_AT humankind_NN1 has_VHZ opened_VVN their_APPGE eyes_NN2 for_IF the_AT reasons_NN2 behind_II the_AT phenomenon_NN1 ._. 
</s>
<s>
The_AT current_JJ ,_, general_JJ view_NN1 is_VBZ that_CST there_EX are_VBR several_DA2 contributing_JJ issues_NN2 and_CC not_XX all_DB are_VBR caused_VVN or_CC controllable_JJ by_II humans_NN2 ._. 
</s>
<s>
Meanwhile_RR companies_NN2 sales_NN and_CC production_NN1 strategies_NN2 have_VH0 changed_VVN dramatically_RR over_II last_MD 10_MC 20_MC years_NNT2 ,_, going_VVG from_II local_JJ vendors_NN2 to_II huge_JJ global_JJ companies_NN2 ,_, with_IW centralized_JJ productions_NN2 in_II low-cost-countries_NN2 and_CC worldwide_JJ distribution_NN1 networks_NN2 ._. 
</s>
<s>
This_DD1 has_VHZ lead_VVN to_II an_AT1 exploded_JJ transport_NN1 and_CC logistics_NN1 scene_NN1 ,_, with_IW more_DAR goods_NN2 being_VBG produced_VVN in_RP and_CC shipped_VVN from_II low-cost_JJ countries_NN2 to_II the_AT rest_NN1 of_IO the_AT world_NN1 &lsqb;_( source_NN1 ?_? &rsqb;_) ._. 
</s>
<s>
Add_VV0 to_II these_DD2 the_AT gentle_JJ local_JJ pollution_NN1 regulations_NN2 for_IF industries_NN2 and_CC the_AT warning_NN1 signs_NN2 can_VM be_VBI seen_VVN ._. 
</s>
<s>
Together_RL these_DD2 relate_VV0 to_II two_MC major_JJ environmental_JJ issues_NN2 caused_VVN by_II humans_NN2 ,_, pollution_NN1 and_CC energy-consumption_NN1 ._. 
</s>
<s>
Obviously_RR the_AT logistics_NN1 branch_NN1 is_VBZ not_XX the_AT sole_JJ reason_NN1 for_IF global_JJ warming_NN1 ,_, but_CCB the_AT entire_JJ field_NN1 of_IO business_NN1 and_CC industry_NN1 could_VM do_VDI a_RR21 lot_RR22 to_TO improve_VVI their_APPGE environmental_JJ contribution_NN1 ._. 
</s>
<s>
There_EX have_VH0 been_VBN claims_NN2 that_CST transport_VV0 only_RR account_VV0 for_IF a_AT1 small_JJ portion_NN1 of_IO the_AT worlds_NN2 pollution_NN1 ,_, however_RRQV my_APPGE view_NN1 is_VBZ that_CST scanning_VVG through_II entire_JJ complex_JJ supply_NN1 chains_NN2 with_IW all_DB its_APPGE different_JJ steps_NN2 the_AT share_NN1 will_VM be_VBI bigger_JJR ._. 
</s>
<s>
This_DD1 is_VBZ what_DDQ this_DD1 paper_NN1 aims_VVZ to_TO study_VVI :_: how_RRQ can_VM the_AT environmental_JJ impact_NN1 of_IO supply_NN1 chains_NN2 be_VBI changed_VVN and_CC with_IW what_DDQ consequences_NN2 ?_? 
</s>
<s>
The_AT subject_NN1 of_IO this_DD1 paper_NN1 will_VM be_VBI green_JJ supply_NN1 chain_NN1 management_NN1 ._. 
</s>
<s>
It_PPH1 will_VM discuss_VVI the_AT environmental_JJ aspects_NN2 within_II the_AT different_JJ fields_NN2 of_IO logistics_NN1 and_CC transports_VVZ ._. 
</s>
<s>
The_AT first_MD aim_NN1 is_VBZ to_TO conclude_VVI the_AT present_JJ situation_NN1 :_: What_DDQ is_VBZ the_AT situation_NN1 of_IO supply_NN1 chains_NN2 now_RT ,_, how_RRQ has_VHZ the_AT industry_NN1 arrived_VVN to_II this_DD1 situation_NN1 ,_, what_DDQ is_VBZ being_VBG done_VDN well_RR ,_, what_DDQ can_VM still_RR be_VBI improved_VVN ?_? 
</s>
<s>
The_AT second_MD aim_NN1 is_VBZ to_TO look_VVI into_II the_AT future_NN1 :_: What_DDQ is_VBZ the_AT next_MD step_NN1 towards_II greener_JJR supply_NN1 chains_NN2 ,_, are_VBR there_EX any_DD new_JJ technologies_NN2 ,_, strategies_NN2 ,_, or_CC inventions_NN2 that_CST will_VM change_VVI the_AT scene_NN1 ?_? 
</s>
<s>
Is_VBZ there_EX a_AT1 genuine_JJ will_NN1 to_II 'go_NN1 green'_NN1 ,_, or_CC is_VBZ company_NN1 profit_NN1 the_AT only_JJ thing_NN1 that_CST matters_NN2 ?_? 
</s>
<s>
How_RRQ is_VBZ the_AT political_JJ and_CC legal_JJ situation_NN1 developing_VVG ?_? 
</s>
<s>
There_EX are_VBR many_DA2 points_NN2 of_IO view_NN1 to_TO consider_VVI and_CC many_DA2 questions_NN2 to_TO answer_VVI ._. 
</s>
<s>
1.1_MC What_DDQ is_VBZ Green_JJ Supply_NN1 Chain_NN1 Management_NN1 The_AT natural_JJ function_NN1 of_IO the_AT world_NN1 is_VBZ often_RR described_VVN as_II a_AT1 Ecosystem_NN1 ,_, a_AT1 symbiosis_NN1 of_IO air_NN1 ,_, water_NN1 and_CC other_JJ natural_JJ resources_NN2 ._. 
</s>
<s>
Pekka_NP1 Stenholm_NP1 (_( 2004_MC )_) defines_VVZ the_AT system_NN1 further_RRR ,_, explaining_VVG there_EX are_VBR several_DA2 sub-systems_NN2 within_II the_AT Ecosystem_NN1 ,_, one_MC1 of_IO which_DDQ is_VBZ created_VVN by_II human_JJ beings_NN2 ._. 
</s>
<s>
The_AT humans_NN2 system_NN1 consists_VVZ of_IO a_AT1 physical_JJ ,_, psychological_JJ and_CC social_JJ system_NN1 ,_, that_DD1 again_RT has_VHZ own_DA subcategories_NN2 ._. 
</s>
<s>
One_MC1 of_IO these_DD2 is_VBZ entrepreneurship_NN1 ,_, which_DDQ belongs_VVZ to_II the_AT category_NN1 of_IO business_NN1 environment_NN1 and_CC society_NN1 ._. 
</s>
<s>
Considering_VVG through_II this_DD1 chain_NN1 of_IO categories_NN2 ,_, one_PN1 can_VM see_VVI that_DD1 entrepreneurship_NN1 is_VBZ dependent_JJ on_II its_APPGE business_NN1 environment_NN1 ,_, which_DDQ depends_VVZ on_II the_AT society_NN1 ,_, which_DDQ depends_VVZ human_JJ beings_NN2 ecosystem_VV0 ,_, which_DDQ again_RT relies_VVZ on_II the_AT entire_JJ Ecosystem_NN1 of_IO planet_NN1 Earth_NN1 ._. 
</s>
<s>
Although_CS long-winded_JJ ,_, the_AT hierarchy_NN1 is_VBZ clear_JJ ;_; one_PN1 can_VM claim_VVI that_DD1 entrepreneurship_NN1 is_VBZ dependent_JJ on_II nature_NN1 ._. 
</s>
<s>
But_CCB turning_VVG tables_NN2 ,_, can_VM one_PN1 claim_VVI that_CST the_AT Ecosystem_NN1 is_VBZ dependent_JJ on_II humans_NN2 entrepreneurship_NN1 or_CC even_RR human_JJ beings_NN2 ?_? 
</s>
<s>
Not_XX really_RR ,_, as_CSA there_EX are_VBR evidence_NN1 of_IO life_NN1 on_II this_DD1 planet_NN1 before_II human_JJ beings_NN2 ._. 
</s>
<s>
(_( Stenholm_NP1 ,_, 2004_MC ._. )_) 
</s>
<s>
However_RR ,_, due_II21 to_II22 action_NN1 by_II humans_NN2 ,_, we_PPIS2 have_VH0 seen_VVN recent_JJ changes_NN2 in_II the_AT nature_NN1 ._. 
</s>
<s>
While_CS there_EX have_VH0 been_VBN several_DA2 theories_NN2 about_II reasons_NN2 behind_RL ,_, pollution_NN1 and_CC energy-consumptions_NN2 are_VBR often_RR mentioned_VVN as_CSA reasons_NN2 behind_II the_AT phenomenon_NN1 ._. 
</s>
<s>
Much_DA1 of_IO this_DD1 relates_VVZ to_II the_AT industries_NN2 set_VVN up_RP by_II human_NN1 ,_, the_AT factories_NN2 we_PPIS2 use_VV0 to_TO produce_VVI our_APPGE things_NN2 and_CC the_AT vehicles_NN2 we_PPIS2 use_VV0 to_TO transport_VVI them_PPHO2 ._. 
</s>
<s>
Because_II21 of_II22 the_AT environmental_JJ changes_NN2 as_CSA become_VVN a_AT1 hot_JJ topic_NN1 ,_, we_PPIS2 have_VH0 seen_VVN more_RRR and_CC more_DAR attempts_NN2 from_II companies_NN2 to_II me_PPIO1 more_RRR ecologic_JJ ._. 
</s>
<s>
One_MC1 of_IO the_AT biggest_JJT trends_NN2 for_IF now_RT is_VBZ Green_JJ Supply_NN1 Chain_NN1 Management_NN1 (_( GSCM_NP1 )_) ,_, which_DDQ can_VM be_VBI described_VVN as_CSA industrial_JJ ecology_NN1 ._. 
</s>
<s>
It_PPH1 strives_VVZ to_TO look_VVI into_II the_AT entire_JJ activity-chains_NN2 of_IO companies_NN2 and_CC see_VV0 what_DDQ parts_NN2 could_VM be_VBI done_VDN greener_JJR ,_, more_RGR environmental_JJ friendly_JJ ._. 
</s>
<s>
(_( Sarkis_NN1 ,_, 2002:398_MC )_) 1.2_MC Theoretical_JJ framework_NN1 This_DD1 paper_NN1 will_VM be_VBI based_VVN on_II the_AT course_NN1 Green_JJ Supply_NN1 Chain_NN1 Management_NN1 by_II Joseph_NP1 Sarkis_NP1 at_II Hanken_NP1 (_( 3891_MC ,_, period_NN1 2_MC )_) and_CC a_AT1 review_NN1 of_IO the_AT related_JJ literature_NN1 ._. 
</s>
<s>
It_PPH1 will_VM not_XX summarize_VVI the_AT course_NN1 ,_, but_CCB rather_RG elaborate_JJ on_II some_DD of_IO the_AT key_JJ points_NN2 and_CC simultaneously_RR work_VV0 as_II a_AT1 learning_NN1 tool_NN1 for_IF the_AT author_NN1 and_CC the_AT audience_NN1 as_RR21 well_RR22 ._. 
</s>
<s>
More_DAR literature_NN1 within_II the_AT field_NN1 will_VM be_VBI used_VVN ,_, as_II31 well_II32 as_II33 the_AT author_NN1 's_GE own_DA working_JJ experience_NN1 in_II the_AT branch_NN1 and_CC material_NN1 from_II earlier_JJR studies_NN2 and_CC courses_NN2 ._. 
</s>
<s>
2_MC THE_AT ENVIRONMENTAL_JJ IMPACT_NN1 OF_IO SUPPLY_NN1 CHAINS_NN2 As_CSA Supply_NN1 Chains_NN2 consist_VV0 of_IO so_RG many_DA2 different_JJ phases_NN2 ,_, it_PPH1 is_VBZ challenging_VVG to_TO label_VVI which_DDQ part_NN1 is_VBZ the_AT most_RGT harmful_JJ for_IF the_AT environment_NN1 ._. 
</s>
<s>
A_AT1 Finnish_JJ study_NN1 by_II Pekka_NP1 Stenholm_NP1 (_( 2004_MC )_) has_VHZ made_VVN an_AT1 attempt_NN1 to_TO clarify_VVI the_AT proportions_NN2 within_II the_AT logistical_JJ part_NN1 for_IF road-transports_NN2 ._. 
</s>
<s>
He_PPHS1 divided_VVD the_AT logistics_NN1 to_II purchasing_NN1 ,_, transports_VVZ ,_, warehousing_NN1 ,_, recycling_VVG and_CC packing_NN1 ._. 
</s>
<s>
The_AT one_PN1 with_IW biggest_JJT environmental_JJ impact_NN1 was_VBDZ transports_NN2 ,_, counting_VVG for_IF a_AT1 share_NN1 beyond_II 50%_NNU and_CC consisting_VVG of_IO pollutions_NN2 ,_, noise_NN1 ,_, jitter_VV0 ,_, accidents_NN2 and_CC other_JJ traffic_NN1 related_JJ problems_NN2 ._. 
</s>
<s>
Warehousing_NN1 was_VBDZ claimed_VVN to_TO cause_VVI 15%_NNU of_IO the_AT environmental_JJ effect_NN1 ,_, mainly_RR because_II21 of_II22 ineffectiveness_NN1 within_II processes_NN2 and_CC waste_NN1 of_IO resources_NN2 ._. 
</s>
<s>
The_AT later_JJR was_VBDZ also_RR mentioned_VVN as_II the_AT impacts_NN2 of_IO purchasing_NN1 ,_, recycling_VVG and_CC packaging_NN1 ._. 
</s>
<s>
Stenholm_NP1 could_VM not_XX give_VVI an_AT1 exact_JJ percentage_NN1 regarding_II these_DD2 ,_, as_II they_PPHS2 mainly_RR have_VH0 an_AT1 indirect_JJ impact_NN1 through_II other_JJ logistical_JJ functions_NN2 ._. 
</s>
<s>
(_( Stenholm._NP1 2004:19_MC )_) While_CS the_AT study_NN1 mentioned_VVN is_VBZ interesting_JJ and_CC relevant_JJ ,_, it_PPH1 has_VHZ to_TO be_VBI noticed_VVN that_CST it_PPH1 only_RR covers_VVZ road-transportation_JJ and_CC the_AT logistical_JJ part_NN1 of_IO supply_NN1 chains_NN2 ._. 
</s>
<s>
Whilst_CS supply-chains_NN2 are_VBR always_RR unique_JJ phenomenon_NN1 ,_, they_PPHS2 should_VM include_VVI the_AT industrial_JJ part_NN1 ;_; mainly_RR raw-material_JJ acquisition_NN1 and_CC production_NN1 ._. 
</s>
<s>
In_II the_AT other_JJ end_NN1 of_IO supply_NN1 chains_NN2 there_EX is_VBZ the_AT selling_NN1 part_NN1 ,_, one_PN1 could_VM even_RR argue_VVI that_CST the_AT end-consumers_NN2 usage_NN1 and_CC disposal_NN1 of_IO the_AT product_NN1 could_VM be_VBI included_VVN ._. 
</s>
<s>
These_DD2 two_MC parts_NN2 adds_VVZ to_II the_AT overall_JJ environmental_JJ impact_NN1 and_CC reduces_VVZ the_AT proportional_JJ impact_NN1 of_IO transports_NN2 and_CC other_JJ logistical_JJ functions_NN2 ._. 
</s>
<s>
The_AT past_NN1 what_DDQ has_VHZ been_VBN done_VDN ,_, what_DDQ has_VHZ changed_VVN ,_, The_AT present_JJ products_NN2 lifetime_NNT1 ?_? ,_, marketing_NN1 ,_, technological_JJ revolution_NN1 Laws_NN2 and_CC regulations_NN2 ,_, EU_NP1 &;_NULL Global_JJ ,_, Governments_NN2 Taxes_NN2 Vehicles_NN2 ,_, machinery_NN1 and_CC fuels_NN2 Companies_NN2 social_JJ responsibility_NN1 an_AT1 option_NN1 or_CC a_AT1 necessity_NN1 ?_? 
</s>
<s>
The_AT effect_NN1 3_MC THE_AT FUTURE_NN1 What_DDQ can_VM be_VBI done_VDN ?_? 
</s>
<s>
Theories_NN2 ,_, strategies_NN2 ,_, visions_NN2 Companies_NN2 willingness_NN1 /_FO through_II sanctions_NN2 ?_? 4_MC CONCLUSIONS_NN2 AND_CC SUMMARY_NN1 
</s>
