<s>
CORPORATE_JJ SOCIAL_JJ RESPONSIBILITY_NN1 IN_II PHARMACEUTICAL_JJ INDUSTRY_NN1 :_: In_II sight_NN1 or_CC not_XX ?_? 1_MC1 INTRODUCTION_NN1 Business_NN1 has_VHZ originally_RR been_VBN though_RR to_TO be_VBI based_VVN on_II hard_JJ values_NN2 according_II21 to_II22 old_JJ articles_NN2 ._. 
</s>
<s>
Maximizing_VVG profits_NN2 and_CC shareholder_NN1 value_NN1 have_VH0 been_VBN in_II the_AT centre_NN1 of_IO the_AT business_NN1 ._. 
</s>
<s>
Today_RT ,_, the_AT business_NN1 settingsconsist_VV0 of_IO relationships_NN2 between_II companies_NN2 different_JJ actors_NN2 ._. 
</s>
<s>
The_AT actors_NN2 also_RR have_VH0 humane_JJ side_NN1 ,_, furthermore_RR trust_VV0 between_II different_JJ actors_NN2 claims_VVZ softer_JJR values_NN2 ._. 
</s>
<s>
Therefore_RR ,_, it_PPH1 is_VBZ important_JJ to_TO consider_VVI ethical_JJ aspects_NN2 of_IO the_AT business_NN1 as_RR21 well_RR22 ._. 
</s>
<s>
Evidence_NN1 of_IO ethicalness_NN1 in_II business_NN1 is_VBZ presented_VVN in_II many_DA2 current_JJ articles_NN2 ._. 
</s>
<s>
Pharmaceutical_JJ companies_NN2 have_VH0 been_VBN seen_VVN as_CSA exploiters_NN2 of_IO the_AT sick_JJ people_NN ._. 
</s>
<s>
The_AT companies_NN2 have_VH0 been_VBN considered_VVN as_CSA companies_NN2 ,_, which_DDQ just_RR want_VV0 to_TO gain_VVI as_RG big_JJ profits_NN2 as_CSA possible_JJ no_AT matter_NN1 of_IO means_NN ._. 
</s>
<s>
This_DD1 has_VHZ led_VVN to_II more_RGR careful_JJ consideration_NN1 of_IO ethical_JJ issues_NN2 ,_, which_DDQ are_VBR indeed_RR gaining_VVG more_DAR importance_NN1 inthe_VV0 business.Pharmaceutical_NNU companies_NN2 are_VBR not_XX just_RR developingnew_VV0 medicines_NN2 to_TO cure_VVI people_NN ._. 
</s>
<s>
Pharmaceutical_JJ companiesare_NN1 also_RR able_JK to_TO offer_VVI better_JJR quality_NN1 of_IO life_NN1 for_IF healthy_JJ people_NN in_II countriesin_NN1 whichthey_NN1 operate.However_NNU ,_, the_AT corporate_JJ social_JJ responsibility_NN1 (_( CSR_NP1 )_) and_CC the_AT pharmaceutical_JJ industry_NN1 have_VH0 been_VBN seen_VVN as_II enemies.Therefore_NNU the_AT research_NN1 question_NN1 is_VBZ the_AT following_JJ :_: are_VBR pharmaceutical_JJ companies_NN2 acting_VVG in_II a_AT1 socially_RR responsible_JJ way_NN1 ?_? 
</s>
<s>
Furthermore_RR ,_, if_CS they_PPHS2 are_VBR ,_, how_RRQ can_VM this_DD1 value_NN1 be_VBI seen_VVN and_CC is_VBZ transmitted_VVN ?_? 
</s>
<s>
This_DD1 paper_NN1 examines_VVZ the_AT change_NN1 in_II the_AT values_NN2 of_IO pharmaceutical_JJ companies_NN2 and_CC where_CS this_DD1 has_VHZ concluded_VVN ._. 
</s>
<s>
The_AT corporate_JJ social_JJ responsibility_NN1 demands_VVZ organizational_JJ culture_NN1 ,_, which_DDQ has_VHZ suitable_JJ attitudes_NN2 and_CC values_NN2 against_II ethical_JJ behaviour_NN1 ._. 
</s>
<s>
Management_NN1 has_VHZ a_AT1 great_JJ effect_NN1 on_II the_AT formulation_NN1 ofthe_NN1 culture_NN1 ._. 
</s>
<s>
CSR_NP1 can_VM offer_VVI a_AT1 valuable_JJ channel_NN1 to_TO market_VVI the_AT company_NN1 ._. 
</s>
<s>
Pharmaceutical_JJ business_NN1 is_VBZ not_XX only_RR based_VVN on_II hard_JJ values_NN2 ,_, such_II21 as_II22 money_NN1 and_CC profit_NN1 ,_, but_CCB more_RRR on_II softer_JJR and_CC humane_JJ values.Acting_NNU in_II a_AT1 social_JJ responsible_JJ way_NN1 helps_VVZ the_AT company_NN1 to_TO gain_VVI better_JJR acceptance_NN1 among_II consumers_NN2 and_CC other_JJ parties_NN2 involved_JJ in_II the_AT business_NN1 ._. 
</s>
<s>
It_PPH1 offers_VVZ a_AT1 tool_NN1 for_IF companies_NN2 to_TO position_VVI themselves_PPX2 among_II other_JJ companies_NN2 within_II the_AT same_DA branch_NN1 ._. 
</s>
<s>
This_DD1 paper_NN1 is_VBZ organised_VVN as_CSA follows_VVZ :_: The_AT first_MD section_NN1 consists_VVZ of_IO introduction_NN1 ,_, which_DDQ gives_VVZ background_NN1 information_NN1 and_CC presents_VVZ research_NN1 question_NN1 ._. 
</s>
<s>
Second_MD section_NN1 offers_NN2 literature_NN1 review_NN1 ,_, which_DDQ forms_VVZ the_AT theoretical_JJ basis_NN1 of_IO the_AT paper_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ followed_VVN by_II third_MD section_NN1 ,_, methods_NN2 ,_, which_DDQ define_VV0 methodology_NN1 and_CC data_NN used_VVD ._. 
</s>
<s>
In_II section_NN1 four_MC ,_, results_NN2 ,_, is_VBZ presented_VVN the_AT findings_NN2 based_VVN on_II data_NN analysis_NN1 ._. 
</s>
<s>
This_DD1 section_NN1 is_VBZ followed_VVN by_II discussion_NN1 ,_, section_NN1 five_MC ,_, which_DDQ portrays_VVZ major_JJ findings_NN2 with_IW commentary_NN1 ._. 
</s>
<s>
Last_MD section_NN1 is_VBZ conclusion_NN1 ,_, which_DDQ is_VBZ a_AT1 summary_NN1 of_IO the_AT findings_NN2 and_CC results_NN2 for_IF scholars_NN2 ._. 
</s>
<s>
2_MC LITERATURE_NN1 REVIEW_VV0 Corporate_JJ social_JJ responsibility_NN1 (_( CSR_NP1 )_) has_VHZ many_DA2 definitions_NN2 in_II the_AT literature_NN1 ._. 
</s>
<s>
The_AT present_JJ articles_NN2 share_VV0 a_AT1 common_JJ stance_NN1 :_: corporate_JJ social_JJ responsibility_NN1 consists_VVZ of_IO legal_JJ responsibilities_NN2 ,_, economicresponsibilities_NN2 ,_, ethical_JJ responsibilities_NN2 and_CC discretionary_JJ responsibilities_NN2 (_( Duarte_NP1 ,_, Mouro_NP1 and_CC das_FW Neves_NP1 2010:104_MC )_) ._. 
</s>
<s>
In_II this_DD1 paper_NN1 the_AT focus_NN1 is_VBZ set_VVN to_II voluntary_JJ activities_NN2 ,_, which_DDQ enhances_VVZ the_AT wellbeing_NN1 of_IO society_NN1 (_( see_VV0 Table_NN1 1_MC1 )_) ._. 
</s>
<s>
This_DD1 view_NN1 is_VBZ taken_VVN ,_, because_CS it_PPH1 describes_VVZ the_AT willingness_NN1 to_TO participate_VVI without_IW obligations_NN2 ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) Corporate_JJ social_JJ responsibility_NN1 is_VBZ also_RR separated_VVN from_II the_AT term_NN1 corporate_JJ social_JJ performance_NN1 in_II this_DD1 paper_NN1 ._. 
</s>
<s>
Corporate_JJ social_JJ performance_NN1 is_VBZ more_RGR strategic_JJ term_NN1 and_CC serves_VVZ for_IF the_AT purposes_NN2 of_IO management_NN1 to_TO measure_VVI factual_JJ CSR_NP1 (_( Clarkson_NP1 1995:98_MC )_) ._. 
</s>
<s>
3_MC METHODS_NN2 The_AT methodology_NN1 used_VVN in_II this_DD1 paper_NN1 is_VBZ a_AT1 descriptive-analytic_JJ research_NN1 (_( I_PPIS1 will_VM seek_VVI a_AT1 source_NN1 for_IF this_DD1 and_CC open_VVI the_AT concept_NN1 more_RRR )_) ._. 
</s>
<s>
Data_NN for_IF the_AT research_NN1 is_VBZ gathered_VVN from_II corporate_JJ social_JJ responsibility_NN1 reports_NN2 of_IO the_AT major_JJ pharmaceutical_JJ companies_NN2 and_CC from_II scientific_JJ articles_NN2 that_CST concern_VV0 the_AT topic_NN1 ._. 
</s>
<s>
Finland_NP1 is_VBZ too_RG narrow_JJ area_NN1 to_TO concentrate_VVI therefore_RR the_AT aspect_NN1 is_VBZ worldwide_RL ._. 
</s>
<s>
Collected_JJ data_NN is_VBZ analysed_VVN with_IW the_AT RDAP_NN1 scale_NN1 presented_VVN in_II Clarksons_NP2 article_NN1 (_( 1995:109_MC )_) A_ZZ1 stakeholder_VV0 framework_NN1 for_IF analyzing_VVG and_CC evaluating_VVG corporate_JJ social_JJ responsibility_NN1 ._. 
</s>
<s>
The_AT scale_NN1 consists_VVZ of_IO concepts:reactiveness_FO ,_, defensiveness_NN1 ,_, accommodativeness_NN1 and_CC proactiveness_NN1 (_( see_VV0 Table_NN1 2_MC )_) ._. 
</s>
<s>
Using_VVG the_AT RDAP_NN1 scale_NN1 it_PPH1 is_VBZ possible_JJ to_TO measure_VVI the_AT posture_NN1 the_AT company_NN1 has_VHZ towards_II social_JJ responsibility_NN1 (_( see_VV0 Table_NN1 3_MC )_) ._. 
</s>
<s>
The_AT posture_NN1 is_VBZ determined_VVN by_II the_AT data_NN available_JJ of_IO the_AT philanthropic_JJ acts_NN2 (_( see_VV0 Table_NN1 4_MC )_) ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) &lsqb;_( Table_NN1 &rsqb;_) &lsqb;_( Table_NN1 &rsqb;_) 4_MC RESULTS_NN2 5_MC DISCUSSION_NN1 6_MC CONCLUSIONS_NN2 
</s>
