<s>
The_AT Relationship_NN1 between_II reverse_JJ logistical_JJ capabilities_NN2 and_CC firm_JJ performance_NN1 in_II e-commerce_NN1 1_MC1 ._. 
</s>
<s>
Introduction_NN1 E-commerce_NN1 is_VBZ becoming_VVG a_AT1 more_RGR common_JJ way_NN1 of_IO consuming_VVG for_IF households_NN2 ._. 
</s>
<s>
Especially_RR improvements_NN2 in_II security_NN1 ,_, graphics_NN ,_, and_CC speed_NN1 have_VH0 aided_VVN this_DD1 rapid_JJ rise_NN1 of_IO consuming_VVG on_II the_AT Internet_NN1 ._. 
</s>
<s>
Safe_JJ transactions_NN2 ,_, price_NN1 ,_, buying_VVG experience_NN1 ,_, and_CC retailer_NN1 quality_NN1 are_VBR some_DD factors_NN2 that_CST influence_VV0 consumers_NN2 decisions_NN2 to_TO choose_VVI Internet_NN1 shopping_VVG over_RP traditional_JJ shopping_NN1 (_( Liao_NP1 and_CC Cheung_VVD 2001_MC )_) ._. 
</s>
<s>
Approximately_RR 37_MC %_NNU of_IO Finnish_JJ consumers_NN2 shop_VV0 on_II the_AT Internet_NP1 (_( Tilastokeskus_NP1 2009_MC )_) ._. 
</s>
<s>
Buying_VVG on_II the_AT Internet_NN1 removes_VVZ many_DA2 complex_JJ steps_NN2 that_CST are_VBR included_VVN in_II traditional_JJ shopping_NN1 ._. 
</s>
<s>
The_AT consumer_NN1 can_VM therefore_RR be_VBI expected_VVN to_TO buy_VVI more_RGR frequently_RR and_CC perhaps_RR larger_JJR quantities_NN2 ._. 
</s>
<s>
E-commerce_NN1 is_VBZ expected_VVN to_TO grow_VVI on_II a_AT1 global_JJ scale_NN1 (_( Brashear_NP1 ,_, Vishal_NP1 ,_, Musante_NP1 ,_, and_CC Donthu_NP1 2009_MC )_) ._. 
</s>
<s>
In_II the_AT future_JJ e-commerce_NN1 might_VM even_RR be_VBI the_AT primary_JJ method_NN1 of_IO purchasing_VVG for_IF consumers_NN2 ._. 
</s>
<s>
There_EX are_VBR however_RR some_DD issues_NN2 that_CST have_VH0 to_TO be_VBI dealt_VVN with_IW first_MD ,_, in_BCL21 order_BCL22 for_IF this_DD1 to_TO happen_VVI ._. 
</s>
<s>
One_MC1 such_DA issue_NN1 is_VBZ the_AT return_NN1 of_IO products_NN2 that_CST have_VH0 been_VBN bought_VVN on_II the_AT Internet_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ the_AT most_RGT common_JJ reason_NN1 why_RRQ consumers_NN2 choose_VV0 traditional_JJ commerce_NN1 over_II e-commerce_NN1 (_( Trebilcock_NP1 2001_MC )_) ._. 
</s>
<s>
Logistics_NN1 is_VBZ a_AT1 vital_JJ element_NN1 of_IO e-commerce_NN1 ._. 
</s>
<s>
Consumers_NN2 expect_VV0 companies_NN2 to_TO be_VBI responsible_JJ for_IF the_AT all_DB the_AT logistical_JJ aspects_NN2 that_CST are_VBR included_VVN in_II e-commerce_NN1 ._. 
</s>
<s>
In_II traditional_JJ consumption_NN1 it_PPH1 is_VBZ the_AT consumer_NN1 that_CST is_VBZ responsible_JJ for_IF transportation_NN1 between_II themselves_PPX2 and_CC the_AT company_NN1 ._. 
</s>
<s>
For_IF a_AT1 company_NN1 that_CST is_VBZ active_JJ within_II e-commerce_NN1 ,_, as_RG much_DA1 as_CSA 40_MC %_NNU of_IO total_JJ costs_NN2 are_VBR due_II21 to_II22 logistics_NN1 (_( Bayles_NN2 2001_MC )_) ._. 
</s>
<s>
The_AT concept_NN1 of_IO reverse_JJ logistics_NN1 has_VHZ been_VBN around_RP for_IF as_CS31 long_CS32 as_CS33 the_AT concept_NN1 of_IO forward_JJ streaming_JJ logistics_NN1 ._. 
</s>
<s>
However_RR ,_, companies_NN2 have_VH0 only_RR realized_VVN the_AT opportunities_NN2 lowering_VVG costs_NN2 by_II investing_VVG in_II reverse_JJ logistics_NN1 ,_, during_II the_AT last_MD decades_NNT2 (_( Andel_NP1 2004_MC )_) ._. 
</s>
<s>
Forward_RL flowing_JJ logistics_NN1 is_VBZ relatively_RR easily_RR planned_VVN ,_, however_RRQV the_AT same_DA can_VM not_XX be_VBI said_VVN for_IF reverse_JJ logistics_NN1 ._. 
</s>
<s>
Every_AT1 single_JJ case_NN1 is_VBZ unique_JJ and_CC therefore_RR has_VHZ to_TO be_VBI handled_VVN in_II that_DD1 manner_NN1 (_( Hughes_NP1 2003_MC ;_; Biederman_NP1 2006_MC )_) ._. 
</s>
<s>
Reverse_VV0 logistical_JJ costs_NN2 may_VM be_VBI two_MC or_CC three_MC times_NNT2 than_CSN of_IO the_AT original_JJ logistical_JJ costs_NN2 (_( Kuzeljevich_NP1 2004_MC )_) ._. 
</s>
<s>
Reverse_JJ logistics_NN1 has_VHZ become_VVN a_AT1 competitive_JJ advantage_NN1 for_IF companies_NN2 (_( Meyer_NP1 1999_MC )_) ._. 
</s>
<s>
Companies_NN2 even_RR offer_VV0 longer_JJR return_NN1 times_NNT2 for_IF products_NN2 ,_, in_BCL21 order_BCL22 to_TO attract_VVI consumers_NN2 ._. 
</s>
<s>
Companies_NN2 have_VH0 started_VVN competing_VVG in_II offering_VVG consumers_NN2 more_RGR attractive_JJ return_NN1 policies_NN2 (_( Bayles_NN2 2001_MC )_) ._. 
</s>
<s>
Product_NN1 return_NN1 policies_NN2 can_VM therefore_RR play_VVI a_AT1 large_JJ role_NN1 in_II how_RGQ successful_JJ companies_NN2 are_VBR within_II their_APPGE respective_JJ markets_NN2 ._. 
</s>
<s>
In_II Finland_NP1 ,_, laws_NN2 that_CST protect_VV0 consumers_NN2 also_RR play_VV0 a_AT1 role_NN1 in_II influencing_VVG companies_NN2 return_VV0 policies_NN2 ._. 
</s>
<s>
Cho_NN1 ,_, Ozment_NP1 ,_, and_CC Sink_NN1 (_( 2008_MC )_) claim_VV0 that_CST strong_JJ logistical_JJ capabilities_NN2 ,_, in_II companies_NN2 that_CST are_VBR active_JJ within_II e-commerce_NN1 ,_, have_VH0 a_AT1 positive_JJ relationship_NN1 with_IW firm_JJ performance_NN1 ._. 
</s>
<s>
There_EX is_VBZ however_RR no_AT evidence_NN1 to_TO show_VVI that_CST the_AT same_DA holds_NN2 for_IF reverse_JJ logistical_JJ capabilities_NN2 ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, it_PPH1 is_VBZ unclear_JJ if_CS companies_NN2 that_CST handle_VV0 their_APPGE product_NN1 returns_NN2 better_VV0 are_VBR more_RGR successful_JJ ._. 
</s>
<s>
The_AT purpose_NN1 of_IO this_DD1 paper_NN1 is_VBZ to_TO investigate_VVI the_AT relationship_NN1 between_II e-commerce_JJ companies_NN2 reverse_VV0 logistical_JJ capabilities_NN2 and_CC their_APPGE firm_JJ performance_NN1 ._. 
</s>
<s>
Based_VVN on_II previous_JJ research_NN1 a_AT1 framework_NN1 for_IF reverse_JJ logistical_JJ capabilities_NN2 ,_, of_IO companies_NN2 operating_VVG in_II e-commerce_NN1 ,_, is_VBZ constructed_VVN ._. 
</s>
<s>
This_DD1 framework_NN1 is_VBZ then_RT tested_VVN to_TO evaluate_VVI the_AT relationship_NN1 between_II reverse_JJ logistical_JJ capabilities_NN2 and_CC firm_JJ performance_NN1 ._. 
</s>
<s>
The_AT focal_JJ group_NN1 of_IO the_AT empirical_JJ study_NN1 is_VBZ Finnish_JJ companies_NN2 that_CST sell_VV0 products_NN2 to_II consumers_NN2 on_II the_AT Internet_NN1 ._. 
</s>
<s>
Reverse_JJ logistics_NN1 is_VBZ a_AT1 broad_JJ subject_NN1 area_NN1 and_CC this_DD1 paper_NN1 will_VM therefore_RR focus_VVI on_II product_NN1 returns_VVZ flow_NN1 between_II consumers_NN2 and_CC companies_NN2 ._. 
</s>
<s>
The_AT next_MD chapter_NN1 will_VM include_VVI a_AT1 literary_JJ review_NN1 of_IO reverse_JJ logistics_NN1 in_II e-commerce_NN1 ._. 
</s>
<s>
In_II the_AT third_MD chapter_NN1 the_AT research_NN1 hypothesis_NN1 sill_NN1 be_VBI stated_VVN and_CC discussed_VVN ._. 
</s>
<s>
Thereafter_RT the_AT empirical_JJ study_NN1 will_VM be_VBI discussed_VVN and_CC the_AT results_NN2 will_VM then_RT be_VBI presented_VVN in_II the_AT fifth_MD chapter_NN1 ._. 
</s>
<s>
The_AT final_JJ chapter_NN1 discusses_VVZ and_CC concludes_VVZ the_AT findings_NN2 ._. 
</s>
<s>
2_MC ._. 
</s>
<s>
Literary_JJ rieview_NN1 :_: Rogers_NP1 and_CC Tibben-Lembke_NP1 (_( 2001_MC )_) define_VV0 reverse_JJ logistics_NN1 as_II :_: The_AT process_NN1 of_IO planning_NN1 ,_, implementing_VVG ,_, and_CC controlling_VVG the_AT efficient_JJ ,_, cost_VV0 effective_JJ flow_NN1 of_IO raw_JJ materials_NN2 ,_, in-process_JJ inventory_NN1 ,_, finished_VVD goods_NN2 ,_, and_CC related_JJ information_NN1 from_II the_AT point_NN1 of_IO consumption_NN1 to_II the_AT point_NN1 of_IO origin_NN1 for_IF the_AT purpose_NN1 of_IO recapturing_VVG or_CC creating_VVG value_NN1 or_CC proper_JJ disposal_NN1 (_( Rogers_NP1 and_CC Tibben-Lembke_NP1 2001_MC :_: 130_MC )_) ._. 
</s>
<s>
There_EX are_VBR four_MC types_NN2 of_IO reverse_JJ logistics_NN1 ,_, these_DD2 are_VBR commercial_JJ returns_NN2 ,_, end-of-life_JJ returns_NN2 ,_, return_NN1 of_IO products_NN2 that_CST are_VBR no_RR21 longer_RR22 in_II use_NN1 ,_, and_CC the_AT recycling_NN1 of_IO products_NN2 (_( Krikke_NP1 ,_, Le_NP1 Blanc_NP1 ,_, and_CC Van_NP1 De_NP1 Velde_NP1 2004_MC )_) ._. 
</s>
<s>
Commercial_JJ returns_NN2 are_VBR returns_NN2 between_II consumers_NN2 and_CC companies_NN2 ._. 
</s>
<s>
Reverse_JJ logistics_NN1 always_RR leads_VVZ to_II costs_NN2 for_IF companies_NN2 ._. 
</s>
<s>
The_AT only_JJ way_NN1 to_TO lower_VVI these_DD2 costs_NN2 is_VBZ by_II minimizing_VVG the_AT number_NN1 of_IO commercial_JJ returns_NN2 ._. 
</s>
<s>
Stock_NN1 ,_, Speh_NP1 and_CC Shear_VV0 (_( 2006_MC )_) claim_VV0 that_CST there_EX are_VBR two_MC types_NN2 of_IO commercial_JJ returns_NN2 ,_, these_DD2 are_VBR controlled_VVN and_CC uncontrolled_JJ returns_NN2 ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO lower_VVI reverse_JJ logistical_JJ costs_NN2 companies_NN2 have_VH0 to_TO try_VVI and_CC minimize_VVI the_AT controlled_JJ returns_NN2 ._. 
</s>
<s>
There_EX are_VBR different_JJ ways_NN2 of_IO minimizing_VVG the_AT controlled_JJ returns_NN2 ._. 
</s>
<s>
Rogers_NP1 and_CC Tibben-Lembke_NP1 (_( 1998_MC )_) suggest_VV0 that_CST efficient_JJ customer_NN1 service_NN1 ,_, to_TO better_RRR inform_VVI the_AT consumer_NN1 about_II products_NN2 ,_, might_VM be_VBI a_AT1 method_NN1 of_IO reducing_VVG returns_NN2 ._. 
</s>
<s>
Customer_NN1 service_NN1 is_VBZ needed_VVN both_RR before_CS and_CC after_CS the_AT purchase_NN1 ._. 
</s>
<s>
Meyer_NP1 (_( 1999_MC )_) suggest_VV0 that_CST companies_NN2 should_VM optimize_VVI their_APPGE websites_NN2 to_TO reduce_VVI commercial_JJ returns_NN2 ._. 
</s>
<s>
Stock_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2006_MC )_) also_RR claim_VV0 that_CST complicated_JJ instructions_NN2 and_CC manuals_NN2 might_VM lead_VVI to_II consumers_NN2 misunderstanding_VVG the_AT product_NN1 and_CC returning_VVG it_PPH1 ._. 
</s>
<s>
Improving_JJ instruction_NN1 manuals_NN2 can_VM therefore_RR lead_VVI to_II a_AT1 reduction_NN1 in_II the_AT controlled_JJ returns_NN2 ._. 
</s>
<s>
Making_VVG sure_JJ all_DB divisions_NN2 of_IO the_AT company_NN1 are_VBR aligned_VVN is_VBZ also_RR important_JJ ._. 
</s>
<s>
Bayles_NN2 (_( 2001_MC )_) states_VVZ that_CST some_DD marketing_NN1 campaigns_NN2 might_VM lead_VVI to_II impulsive_JJ consumption_NN1 ._. 
</s>
<s>
Brashear_VV0 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2009_MC )_) continues_VVZ on_II the_AT same_DA point_NN1 by_II stating_VVG that_CST such_DA campaigns_NN2 are_VBR frequent_JJ within_II e-commerce_NN1 and_CC focus_VV0 specifically_RR on_II increasing_JJ sales_NN ._. 
</s>
<s>
Impulsive_JJ consumption_NN1 can_VM however_RR lead_VVI to_II an_AT1 increase_NN1 in_II commercial_JJ returns_NN2 ._. 
</s>
<s>
Many_DA2 companies_NN2 do_VD0 not_XX identify_VVI what_DDQ amount_NN1 of_IO their_APPGE total_JJ costs_NN2 can_VM be_VBI specified_VVN as_CSA reverse_JJ logistical_JJ costs_NN2 ._. 
</s>
<s>
Zieger_NP1 (_( 2003_MC )_) states_VVZ the_AT importance_NN1 of_IO identifying_VVG reverse_JJ logistical_JJ cost_NN1 ._. 
</s>
<s>
Another_DD1 important_JJ factor_NN1 of_IO the_AT reverse_JJ flow_NN1 of_IO products_NN2 is_VBZ time_NNT1 ._. 
</s>
<s>
According_II21 to_II22 Fisher_NP1 (_( 1997_MC )_) the_AT importance_NN1 of_IO time_NNT1 in_II a_AT1 supply_NN1 chain_NN1 depends_VVZ on_II the_AT type_NN1 of_IO product_NN1 ._. 
</s>
<s>
Fisher_NP1 identifies_VVZ two_MC types_NN2 of_IO products_NN2 and_CC two_MC types_NN2 of_IO supply_NN1 chains_NN2 to_TO manage_VVI the_AT respective_JJ products_NN2 ._. 
</s>
<s>
Functional_JJ products_NN2 have_VH0 stable_JJ demand_NN1 and_CC long_JJ lifecycles_NN2 ._. 
</s>
<s>
These_DD2 kinds_NN2 of_IO products_NN2 need_VV0 efficient_JJ supply_NN1 chains_NN2 ._. 
</s>
<s>
Innovative_JJ products_NN2 have_VH0 unstable_JJ demand_NN1 and_CC short_JJ lifecycles_NN2 ._. 
</s>
<s>
These_DD2 products_NN2 need_VV0 responsive_JJ supply_NN1 chains_NN2 (_( Fisher_NP1 1997_MC )_) ._. 
</s>
<s>
Guide_VV0 ,_, Souza_NP1 ,_, van_NP1 Wassenhove_NP1 ,_, and_CC Blackburn_NP1 (_( 2006_MC )_) build_VV0 on_II Fishers_NN2 (_( 1997_MC )_) article_NN1 by_II using_VVG the_AT same_DA concept_NN1 in_II reverse_JJ logistics_NN1 ._. 
</s>
<s>
According_II21 to_II22 Meyer_NP1 (_( 1999_MC )_) companies_NN2 can_VM have_VHI a_AT1 competitive_JJ advantage_NN1 over_II their_APPGE competitor_NN1 by_II effectively_RR managing_VVG their_APPGE reverse_JJ logistics_NN1 ._. 
</s>
<s>
Jack_NP1 ,_, Powers_NP1 ,_, and_CC Skinner_NP1 (_( 2010_MC )_) state_VV0 that_CST companies_NN2 that_CST commit_VV0 resources_NN2 to_TO positively_RR influence_VVI their_APPGE reverse_JJ logistics_NN1 capabilities_NN2 ,_, lower_VV0 their_APPGE overall_JJ costs_NN2 ._. 
</s>
<s>
Cho_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2008_MC )_) identifies_VVZ 11_MC logistical_JJ capabilities_NN2 that_CST ,_, if_CS managed_VVN effectively_RR ,_, increase_VV0 firm_JJ performance_NN1 for_IF e-commerce_JJ companies_NN2 ._. 
</s>
<s>
These_DD2 11_MC capabilities_NN2 ,_, proposed_VVN by_II Cho_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2008_MC )_) ,_, are_VBR :_: 1_MC1 ._. 
</s>
<s>
Pre-sale_JJ customer_NN1 service_NN1 2_MC ._. 
</s>
<s>
Post-sale_JJ customer_NN1 service_NN1 3_MC ._. 
</s>
<s>
Delivery_NN1 speed_NN1 4_MC ._. 
</s>
<s>
Delivery_NN1 reliability_NN1 5_MC ._. 
</s>
<s>
Responsiveness_NN1 to_TO target_VVI market(s)_NN2 6_MC ._. 
</s>
<s>
Delivery_NN1 information_NN1 communication_NN1 7_MC ._. 
</s>
<s>
Web-based_JJ order_NN1 handling_NN1 8_MC ._. 
</s>
<s>
Widespread_JJ distribution_NN1 coverage_NN1 9_MC ._. 
</s>
<s>
Global_JJ distribution_NN1 coverage_NN1 10_MC ._. 
</s>
<s>
Selective_JJ distribution_NN1 coverage_NN1 11_MC ._. 
</s>
<s>
Low_JJ total_JJ cost_NN1 distribution_NN1 3_MC ._. 
</s>
<s>
Research_NN1 Hypotheses_NN2 The_AT purpose_NN1 of_IO this_DD1 paper_NN1 is_VBZ to_TO investigate_VVI the_AT relationship_NN1 between_II e-commerce_JJ companies_NN2 reverse_VV0 logistical_JJ capabilities_NN2 and_CC their_APPGE firm_JJ performance_NN1 ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO fulfill_VVI the_AT purpose_NN1 three_MC hypotheses_NN2 will_VM be_VBI tested_VVN ._. 
</s>
<s>
All_DB three_MC hypotheses_NN2 are_VBR related_VVN to_II the_AT relationship_NN1 reverse_VV0 logistical_JJ capabilities_NN2 and_CC firm_JJ performance_NN1 ._. 
</s>
<s>
The_AT first_MD hypothesis_NN1 tests_NN2 if_CS there_EX is_VBZ a_AT1 significant_JJ correlation_NN1 between_II any_DD of_IO the_AT reverse_JJ logistical_JJ capabilities_NN2 and_CC firm_JJ performance_NN1 :_: 1_MC1 ._. 
</s>
<s>
H1_FO :_: There_EX is_VBZ a_AT1 significant_JJ correlation_NN1 between_II reverse_JJ logistical_JJ capabilities_NN2 and_CC firm_JJ performance_NN1 ._. 
</s>
<s>
The_AT second_MD hypothesis_NN1 divides_VVZ the_AT ranking_NN1 of_IO reverse_JJ logistical_JJ capabilities_NN2 into_II two_MC groups_NN2 :_: over_RP and_CC under_II the_AT mean_JJ ._. 
</s>
<s>
It_PPH1 does_VDZ the_AT same_DA for_IF firm_JJ performance_NN1 ._. 
</s>
<s>
By_II doing_VDG this_DD1 ,_, the_AT paper_NN1 tries_VVZ to_TO identify_VVI if_CSW companies_NN2 that_CST rate_VV0 their_APPGE reverse_JJ logistical_JJ capabilities_NN2 higher_JJR also_RR rate_VV0 their_APPGE firm_JJ performance_NN1 higher_RRR ._. 
</s>
<s>
The_AT second_MD hypothesis_NN1 is_VBZ :_: 2_MC ._. 
</s>
<s>
H2_FO :_: The_AT third_MD hypothesis_NN1 adds_VVZ up_RP the_AT reverse_JJ logistical_JJ capabilities_NN2 and_CC then_RT calculates_VVZ the_AT mean_JJ value_NN1 of_IO this_DD1 ._. 
</s>
<s>
The_AT new_JJ variable_NN1 is_VBZ called_VVN total_JJ logistical_JJ capability_NN1 ._. 
</s>
<s>
This_DD1 new_JJ variable_NN1 will_VM then_RT be_VBI tested_VVN against_II firm_JJ performance_NN1 in_BCL21 order_BCL22 to_TO establish_VVI if_CSW companies_NN2 with_IW an_AT1 over_JJ average_JJ total_JJ reverse_JJ logistical_JJ capability_NN1 value_NN1 have_VH0 perform_VV0 better_RRR ._. 
</s>
<s>
The_AT third_MD hypothesis_NN1 is_VBZ :_: 3_MC ._. 
</s>
<s>
H3_FO :_: 4_MC ._. 
</s>
<s>
Method_NN1 By_II using_VVG some_DD of_IO the_AT logistics_NN1 capabilities_NN2 proposed_VVD Cho_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2008_MC )_) and_CC adding_VVG some_DD that_CST were_VBDR identified_VVN as_CSA issues_NN2 related_VVN to_II commercial_JJ returns_NN2 ,_, this_DD1 paper_NN1 has_VHZ constructed_VVN its_APPGE own_DA reverse_JJ logistical_JJ capabilities_NN2 ._. 
</s>
<s>
Seven_MC reverse_JJ logistical_JJ capabilities_NN2 were_VBDR produced_VVN :_: 1_MC1 ._. 
</s>
<s>
Pre-sale_JJ customer_NN1 service_NN1 2_MC ._. 
</s>
<s>
Post-sale_JJ customer_NN1 service_NN1 3_MC ._. 
</s>
<s>
Return_VV0 delivery_NN1 speed_NN1 4_MC ._. 
</s>
<s>
Return_VV0 delivery_NN1 reliability_NN1 5_MC ._. 
</s>
<s>
Product_NN1 reintroduction_NN1 speed_NN1 6_MC ._. 
</s>
<s>
Internal_JJ divisional_JJ communication_NN1 7_MC ._. 
</s>
<s>
Low_JJ total_JJ cost_NN1 for_IF reverse_JJ logistics_NN1 The_AT first_MD two_MC reverse_JJ logistical_JJ capabilities_NN2 are_VBR directly_RR borrowed_VVN from_II Cho_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2008_MC )_) ._. 
</s>
<s>
Capabilities_NN2 3,4_MC ,_, and_CC 7_MC are_VBR modified_JJ versions_NN2 of_IO the_AT capabilities_NN2 proposed_VVN by_II Cho_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2008_MC )_) ._. 
</s>
<s>
The_AT two_MC new_JJ reverse_JJ logistical_JJ capabilities_NN2 are_VBR numbers_NN2 5_MC and_CC 6._MC 5_MC ._. 
</s>
<s>
Analysis_NN1 6_MC ._. 
</s>
<s>
Discussion_NN1 and_CC conclusion_NN1 
</s>
