<s>
Localization_NN1 of_IO Industries_NN2 :_: Decisions_NN2 Today_RT and_CC Challenges_NN2 in_II the_AT Future_NN1 1_MC1 Introduction_NN1 The_AT concept_NN1 of_IO location_NN1 theory_NN1 rose_VVD during_II the_AT 19th_MD century_NNT1 (_( e.g._REX Weber_NP1 ,_, 1929_MC )_) along_II21 with_II22 the_AT era_NN1 of_IO industrialization_NN1 ,_, and_CC continued_VVD to_TO develop_VVI throughout_II the_AT 20th_MD century_NNT1 ._. 
</s>
<s>
The_AT usability_NN1 of_IO such_DA theories_NN2 is_VBZ of_IO even_RR greater_JJR importance_NN1 in_II the_AT internationalized_JJ world_NN1 of_IO today_RT :_: as_CSA goods_NN2 and_CC production_NN1 factors_NN2 are_VBR enabled_VVN to_TO move_VVI freely_RR ,_, incentives_NN2 for_IF companies_NN2 to_TO reconsider_VVI the_AT localization_NN1 of_IO their_APPGE sources_NN2 grow_VV0 even_RR bigger_JJR ._. 
</s>
<s>
Although_CS some_DD research_NN1 has_VHZ been_VBN conducted_VVN on_II the_AT subject_NN1 ,_, many_DA2 are_VBR made_VVN as_CSA case_NN1 studies_NN2 for_IF production_NN1 of_IO specific_JJ products_NN2 in_II specific_JJ countries_NN2 ._. 
</s>
<s>
Likewise_RR ,_, this_DD1 paper_NN1 will_VM also_RR focus_VVI on_II studying_VVG the_AT case_NN1 company_NN1 in_BCL21 order_BCL22 to_TO acknowledge_VVI and_CC address_VVI specific_JJ issues_NN2 for_IF thisparticular_JJ company_NN1 ,_, as_CSA initial_JJ research_NN1 indicates_VVZ that_CST little_JJ generalizations_NN2 can_VM be_VBI made_VVN ._. 
</s>
<s>
Furthermore_RR ,_, the_AT playing_JJ field_NN1 is_VBZ constantly_RR changing_VVG with_IW new_JJ regulations_NN2 ,_, political_JJ actions_NN2 ,_, availability_NN1 of_IO production_NN1 factors_NN2 ,_, and_CC the_AT distribution_NN1 of_IO welfare_NN1 globally_RR ._. 
</s>
<s>
Because_II21 of_II22 this_DD1 ,_, research_NN1 and_CC evaluation_NN1 must_VM be_VBI done_VDN quite_RG frequently_RR ._. 
</s>
<s>
This_DD1 paper_NN1 will_VM therefore_RR start_VVI by_II giving_VVG an_AT1 introduction_NN1 and_CC overview_NN1 of_IO the_AT current_JJ factors_NN2 that_CST affect_VV0 the_AT localization_NN1 decisions_NN2 made_VVN within_II corporations_NN2 ._. 
</s>
<s>
The_AT main_JJ part_NN1 of_IO the_AT paper_NN1 will_VM however_RR focus_VVI on_II the_AT case_NN1 company_NN1 and_CC the_AT factors_NN2 that_CST according_II21 to_II22 them_PPHO2 are_VBR of_IO relevance_NN1 today_RT ._. 
</s>
<s>
The_AT discussion_NN1 that_CST follows_VVZ builds_VVZ upon_II the_AT current_JJ state_NN1 ,_, and_CC aims_VVZ at_II identifying_VVG possible_JJ threats_NN2 and_CC scenarios_NN2 for_IF the_AT future_NN1 ._. 
</s>
<s>
As_CSA freight_NN1 volumes_NN2 for_IF containerized_JJ cargoincrease_NN1 year_NNT1 by_II year_NNT1 (_( World_NN1 Shipping_NN1 Council_NN1 ,_, 2012_MC )_) ,_, it_PPH1 is_VBZ obvious_JJ that_CST production_NN1 factors_NN2 are_VBR found_VVN to_TO be_VBI more_RGR economically_RR viable_JJ on_II one_MC1 continent_NN1 then_RT another_DD1 ._. 
</s>
<s>
But_CCB at_II the_AT same_DA time_NNT1 the_AT fear_NN1 of_IO shortage_NN1 of_IO fossil_NN1 fuels_NN2 will_VM eventually_RR lead_VVI actors_NN2 into_II investigating_VVG solutions_NN2 that_CST require_VV0 fewer_DAR and_CC shorter_JJR transportations.Ever_NNU growing_JJ restrictions_NN2 on_II emissions_NN2 will_VM have_VHI the_AT same_DA effect_NN1 ,_, as_CSA the_AT investments_NN2 in_II cleaner_JJR technology_NN1 will_NN1 in_II the_AT end_NN1 be_VBI paid_VVN for_IF by_II the_AT end-user_NN1 ._. 
</s>
<s>
Also_RR ,_, as_CSA the_AT bigger_JJR part_NN1 of_IO the_AT world_NN1 is_VBZ made_VVN up_RP of_IO emerging_JJ markets_NN2 with_IW the_AT BRICS_NN1 countries_NN2 ,_, and_CC it_PPH1 is_VBZ said_VVN (_( Baldwin_NP1 &;_NULL Martin_NP1 1999_MC )_) that_CST we_PPIS2 are_VBR in_II the_AT middle_NN1 of_IO a_AT1 second_MD wave_NN1 of_IO the_AT industrial_JJ revolution_NN1 ._. 
</s>
<s>
This_DD1 will_VM perhaps_RR not_XX change_VVI the_AT fundamentals_NN2 of_IO localization_NN1 theory_NN1 ,_, but_CCB it_PPH1 will_VM arguably_RR greatly_RR change_VVI the_AT setup_NN1 of_IO today_RT ._. 
</s>
<s>
Previous_JJ studies_NN2 ,_, such_II21 as_II22 Baldwin_NP1 (_( 2011_MC )_) suggest_VV0 that_CST producers_NN2 located_VVN in_II these_DD2 countries_NN2 riding_VVG on_II the_AT 2nd_MD wave_NN1 of_IO industrialization_NN1 do_VD0 not_XX need_VVI to_TO have_VHI a_AT1 deep_JJ knowledge_NN1 of_IO the_AT production_NN1 ._. 
</s>
<s>
They_PPHS2 only_RR have_VH0 to_TO be_VBI strategically_RR located_VVN with_IW regards_VVZ to_II the_AT supply_NN1 chain_NN1 of_IO international_JJ companies_NN2 ._. 
</s>
<s>
This_DD1 implies_VVZ that_CST the_AT step_NN1 to_II becoming_VVG an_AT1 exporter_NN1 is_VBZ small_JJ ._. 
</s>
<s>
However_RR ,_, the_AT recent_JJ economic_JJ instabilities_NN2 justify_VV0 a_AT1 deeper_JJR analysis_NN1 of_IO the_AT subject_NN1 ._. 
</s>
<s>
The_AT company_NN1 studied_VVN for_IF this_DD1 paper_NN1 operates_VVZ in_II a_AT1 global_JJ ,_, constantly_RR changing_VVG ,_, environment_NN1 ,_, where_CS their_APPGE decisions_NN2 regarding_II localization_NN1 is_VBZ crucial_JJ for_IF the_AT profitability_NN1 ._. 
</s>
<s>
As_RG many_DA2 studies_NN2 regarding_II the_AT subject_NN1 focuses_VVZ on_II traditional_JJ outsourcing_JJ industries_NN2 such_II21 as_II22 electronics_NN1 ,_, automobiles_NN2 and_CC clothing_NN1 ,_, I_PPIS1 believe_VV0 that_CST there_EX is_VBZ a_AT1 need_NN1 for_IF more_RGR thorough_JJ research_NN1 offering_NN1 insights_NN2 to_II another_DD1 type_NN1 of_IO industry_NN1 ._. 
</s>
<s>
&lsqb;_( Research_NN1 question_NN1 ?_? 
</s>
<s>
Purpose_NN1 of_IO the_AT paper_NN1 ?_? 
</s>
<s>
Paper_NN1 structure_NN1 ?_? &rsqb;_) 2_MC Literature_NN1 review_NN1 3_MC Method_NN1 /_FO Material_NN1 Decribes_VVZ the_AT methodology_NN1 ,_, materials_NN2 ,_, and_CC procedures_NN2 The_AT subject_NN1 was_VBDZ studied_VVN mostly_RR by_II qualitative_JJ means_NN ,_, consisting_VVG of_IO reviews_NN2 of_IO scientific_JJ articles_NN2 ,_, and_CC more_RGR importantly_RR by_II discussing_VVG with_IW a_AT1 corporation_NN1 that_CST manufactures_VVZ goods_NN2 globally_RR ._. 
</s>
<s>
Additionally_RR ,_, quantitative_JJ material_NN1 was_VBDZ obtained_VVN in_II the_AT form_NN1 of_IO data_NN regarding_II the_AT transportation_NN1 of_IO goods_NN2 worldwide_RL ._. 
</s>
<s>
4_MC Results_NN2 /_FO Analysis_NN1 Findings_NN2 described_VVN ,_, with_IW commentary_NN1 The_AT information_NN1 acquired_VVN through_II the_AT literature_NN1 and_CC the_AT interviews_NN2 have_VH0 been_VBN divided_VVN into_II groups_NN2 based_VVN on_II their_APPGE main_JJ characteristics_NN2 ._. 
</s>
<s>
In_II the_AT following_JJ chapters_NN2 these_DD2 will_VM be_VBI presented_VVN ._. 
</s>
<s>
4.1_MC Laborcosts_NN2 Labor_VV0 costs_NN2 are_VBR usually_RR one_MC1 of_IO the_AT main_JJ reasons_NN2 why_RRQ production_NN1 is_VBZ moved_VVN abroad_RL ._. 
</s>
<s>
Depending_II21 on_II22 the_AT technical_JJ specifications_NN2 of_IO the_AT product_NN1 ,_, it_PPH1 is_VBZ decided_VVN if_CS the_AT product_NN1 can_VM be_VBI manufactured_VVN with_IW automated_JJ processes_NN2 such_II21 as_II22 welding_NN1 robots_NN2 ,_, or_CC if_CS the_AT production_NN1 requires_VVZ a_AT1 great_JJ amount_NN1 of_IO manual_JJ labor_NN1 ._. 
</s>
<s>
If_CS automation_NN1 is_VBZ possible_JJ ,_, production_NN1 abroad_RL will_VM not_XX likely_RR give_VVI an_AT1 economical_JJ advantage_NN1 ,_, as_CSA the_AT cost_NN1 of_IO equipment_NN1 is_VBZ likely_RR the_AT same_DA regardless_RR of_IO localization_NN1 ._. 
</s>
<s>
If_CS on_II the_AT other_JJ hand_NN1 production_NN1 is_VBZ labor_NN1 intense_JJ ,_, the_AT production_NN1 price_NN1 will_VM largely_RR be_VBI dependent_JJ on_II labor_NN1 wages_NN2 ._. 
</s>
<s>
4.2_MC Economies_NN2 of_IO scale_NN1 The_AT batch_NN1 sizes_NN2 of_IO the_AT order_NN1 ,_, and_CC the_AT amount_NN1 of_IO products_NN2 that_CST can_VM be_VBI stuffed_VVN into_II transportation_NN1 units_NN2 such_II21 as_II22 sea-containers_NN2 ,_, will_VM affect_VVI the_AT costs_NN2 linked_VVN to_II transportation_NN1 ._. 
</s>
<s>
4.3_MC Fluctuations_NN2 in_II the_AT global_JJ market_NN1 Whether_CSW the_AT production_NN1 is_VBZ carried_VVN out_RP in_II own_DA facilities_NN2 or_CC the_AT products_NN2 are_VBR bought_VVN from_II contract_NN1 manufacturers_NN2 ,_, they_PPHS2 are_VBR always_RR subject_II21 to_II22 fluctuations_NN2 in_II prices_NN2 of_IO raw_JJ materials_NN2 and_CC local_JJ currencies_NN2 ._. 
</s>
<s>
The_AT recent_JJ recession_NN1 has_VHZ led_VVN to_II a_AT1 decrease_NN1 in_II demand_NN1 throughout_II the_AT world_NN1 ._. 
</s>
<s>
This_DD1 in_II turn_NN1 has_VHZ led_VVN to_II changes_NN2 throughout_II the_AT supply_NN1 chain_NN1 ._. 
</s>
<s>
4.4_MC Lead_VV0 times_II Time_NNT1 can_VM be_VBI a_AT1 crucial_JJ factor_NN1 ,_, meaning_VVG that_CST the_AT price_NN1 will_VM play_VVI a_AT1 smaller_JJR role_NN1 in_II the_AT localization_NN1 decision_NN1 ._. 
</s>
<s>
4.5_MC Environmental_JJ issues_NN2 Maersk_VV0 Line_NN1 ,_, the_AT worlds_NN2 largest_JJT shipping_NN1 company_NN1 has_VHZ made_VVN orders_NN2 on_II container_NN1 ships_VVZ that_CST will_VM ,_, when_CS finished_VVN ,_, be_VBI the_AT largest_JJT ships_NN2 in_II traffic_NN1 ._. 
</s>
<s>
Thies_NP1 5_MC Discussion_NN1 An_AT1 account_NN1 of_IO what_DDQ has_VHZ been_VBN learned_VVN Moving_VVG from_II specific_JJ findings_NN2 to_II generalisations_NN2 Explanation_NN1 of_IO the_AT results_NN2 with_II31 respect_II32 to_II33 the_AT theoretical_JJ framework_NN1 applied_VVD Why_RRQ is_VBZ it_PPH1 necessary_JJ to_TO have_VHI a_AT1 discussion_NN1 section_NN1 separate_VV0 from_II the_AT results_NN2 section_NN1 ?_? 6_MC Conclusion_NN1 Appendix_NN1 1_MC1 :_: Test_VV0 1_MC1 
</s>
