<s>
Using_VVG repertory_NN1 grid_NN1 techniques_NN2 to_TO explore_VVI factors_NN2 affecting_VVG customers_NN2 choice_NN1 of_IO mobile_JJ phone_NN1 1_MC1 ._. 
</s>
<s>
Introduction_NN1 With_IW the_AT fast_JJ development_NN1 of_IO technology_NN1 ,_, customers_NN2 requirements_NN2 to_II communications_NN2 devices_NN2 such_II21 as_II22 mobile_JJ phones_NN2 or_CC computers_NN2 have_VH0 increased_VVN a_AT1 lot_NN1 ._. 
</s>
<s>
Take_VV0 mobile_JJ phone_NN1 as_II an_AT1 example_NN1 ,_, when_CS this_DD1 product_NN1 was_VBDZ invented_VVN ,_, it_PPH1 can_VM only_RR provide_VVI basic_JJ services_NN2 such_II21 as_II22 making_VVG and_CC receiving_VVG call_NN1 from_II long_JJ distance_NN1 ,_, sending_VVG SMS_NP1 messages_NN2 ._. 
</s>
<s>
Nowadays_RT ,_, almost_RR all_DB the_AT mobile_JJ phones_NN2 support_VV0 other_JJ additional_JJ services_NN2 such_II21 as_II22 internet_NN1 access_NN1 ,_, camera_NN1 ,_, MP3_FO player_NN1 and_CC GPS_NN2 ._. 
</s>
<s>
Apart_II21 from_II22 these_DD2 functional_JJ features_NN2 ,_, customers_NN2 also_RR make_VV0 trade-off_NN1 among_II different_JJ prices_NN2 ,_, brands_NN2 or_CC other_JJ selective_JJ factors_NN2 when_CS making_VVG purchase_NN1 decisions_NN2 ._. 
</s>
<s>
At_RR21 present_RR22 ,_, mobile_JJ phone_NN1 dealers_NN2 are_VBR facing_VVG with_IW fierce_JJ challenges_NN2 from_II both_DB2 their_APPGE competitors_NN2 and_CC high-demanding_JJ customers_NN2 ._. 
</s>
<s>
In_II the_AT mobile_JJ phone_NN1 market_NN1 ,_, there_EX are_VBR mainly_RR twenty-seven_MC brands_NN2 of_IO mobile_JJ phone_NN1 ._. 
</s>
<s>
All_DB the_AT mobile_JJ phone_NN1 dealers_NN2 are_VBR constantly_RR changing_VVG their_APPGE mobile_JJ phones_NN2 features_NN2 and_CC lowering_VVG their_APPGE prices_NN2 to_TO attract_VVI more_DAR customers_NN2 ._. 
</s>
<s>
Nokia_NP1 CEO_NN1 Stephen_NP1 Elop_NP1 recently_RR said_VVD that_CST faced_VVD with_IW growing_JJ competition_NN1 and_CC a_AT1 changed_JJ business_NN1 environment_NN1 ,_, the_AT company_NN1 will_VM have_VHI to_TO adjust_VVI itself_PPX1 faster_RRR (_( http_NNU :_: )_) ._. 
</s>
<s>
This_DD1 announcement_NN1 indicates_VVZ that_CST the_AT fierce_JJ competition_NN1 and_CC changed_JJ business_NN1 environment_NN1 call_NN1 for_IF more_DAR attention_NN1 on_II customers_NN2 real_JJ needs_NN2 and_CC require_VV0 mobile_JJ phone_NN1 dealers_NN2 to_TO learn_VVI more_RRR about_II customers_NN2 decision-making_JJ processes_NN2 ._. 
</s>
<s>
Doing_VDG so_RR ,_, mobile_JJ phone_NN1 dealers_NN2 can_VM better_RRR meet_VVI their_APPGE customers_NN2 needs_NN2 and_CC therefore_RR increase_VV0 customer_NN1 satisfaction_NN1 ._. 
</s>
<s>
The_AT objective_NN1 of_IO this_DD1 study_NN1 is_VBZ to_TO take_VVI a_AT1 mobile_JJ phone_NN1 dealers_NN2 point_NN1 of_IO view_NN1 to_TO find_VVI out_RP factors_NN2 that_CST affect_VV0 customers_NN2 buying_VVG decisions_NN2 on_II mobile_JJ phones_NN2 ._. 
</s>
<s>
When_CS one_PN1 plans_VVZ to_TO buy_VVI a_AT1 mobile_JJ phone_NN1 ,_, he_PPHS1 or_CC she_PPHS1 is_VBZ likely_JJ to_TO analyze_VVI every_AT1 aspect_NN1 of_IO a_AT1 mobile_JJ phone_NN1 before_II making_VVG decisions_NN2 ._. 
</s>
<s>
For_REX21 example_REX22 ,_, he_PPHS1 or_CC she_PPHS1 may_VM consider_VVI different_JJ functions_NN2 such_II21 as_II22 internet_NN1 access_NN1 ,_, gaming_VVG or_CC camera_NN1 ._. 
</s>
<s>
He_PPHS1 or_CC she_PPHS1 may_VM also_RR think_VVI about_II other_JJ factors_NN2 such_II21 as_II22 price_NN1 ,_, handset_NN1 or_CC multimedia_NN capabilities_NN2 ._. 
</s>
<s>
This_DD1 paper_NN1 expands_VVZ individual_JJ customers_NN2 own_DA understandings_NN2 and_CC judgments_NN2 on_II different_JJ brands_NN2 of_IO mobile_JJ phone_NN1 to_TO reach_VVI his_APPGE or_CC her_APPGE unique_JJ set_NN1 of_IO constructs_NN2 ,_, which_DDQ lead_VV0 to_II the_AT final_JJ decision_NN1 making_VVG ._. 
</s>
<s>
Thus_RR ,_, the_AT real_JJ factors_NN2 that_CST affect_VV0 their_APPGE buying_NN1 behavior_NN1 will_VM be_VBI explored_VVN ._. 
</s>
<s>
This_DD1 paper_NN1 starts_VVZ with_IW reviewing_VVG the_AT previous_JJ study_NN1 in_II customers_NN2 choice_NN1 of_IO mobile_JJ phone_NN1 and_CC how_RGQ other_JJ researchers_NN2 conducted_VVD their_APPGE study_NN1 on_II this_DD1 topic_NN1 ._. 
</s>
<s>
Then_RT ,_, the_AT paper_NN1 explores_VVZ the_AT repertory_NN1 grid_NN1 method_NN1 ._. 
</s>
<s>
Specially_RR ,_, the_AT use_NN1 of_IO repertory_NN1 grid_NN1 in_II marketing_NN1 study_NN1 and_CC how_RRQ this_DD1 method_NN1 contributes_VVZ to_II reaching_VVG the_AT aim_NN1 of_IO the_AT study_NN1 are_VBR discussed_VVN ._. 
</s>
<s>
Personal_JJ Construct_VV0 Theory_NN1 which_DDQ is_VBZ the_AT basis_NN1 for_IF repertory_NN1 grid_NN1 technique_NN1 will_VM also_RR be_VBI presented_VVN ._. 
</s>
<s>
Thereafter_RT ,_, in_II the_AT empirical_JJ study_NN1 part_NN1 ,_, nine_MC customers_NN2 will_VM be_VBI interviewed_VVN and_CC the_AT results_NN2 of_IO the_AT empirical_JJ study_NN1 will_VM be_VBI analyzed_VVN ._. 
</s>
<s>
And_CC finally_RR ,_, the_AT managerial_JJ implication_NN1 and_CC limitations_NN2 of_IO this_DD1 study_NN1 will_VM be_VBI discussed_VVN ._. 
</s>
<s>
2_MC ._. 
</s>
<s>
Literature_NN1 Review_NN1 From_II a_AT1 marketing_NN1 perspective_NN1 ,_, customers_NN2 choice_NN1 behavior_NN1 can_VM be_VBI divided_VVN into_II five_MC steps_NN2 ,_, including_II need_NN1 ,_, information_NN1 search_NN1 ,_, evaluation_NN1 of_IO alternatives_NN2 ,_, purchase_NN1 and_CC post-purchase_JJ evaluation_NN1 (_( Dorsch_NP1 ,_, Grave_NN1 ,_, and_CC Darden_NP1 ,_, 2000_MC )_) ._. 
</s>
<s>
Heikki_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
states_NN2 that_CST the_AT five-step_JJ model_NN1 is_VBZ usually_RR suitable_JJ for_IF making_VVG decisions_NN2 in_II a_AT1 rational_JJ purchase_NN1 behavior_NN1 (_( 2005_MC )_) ._. 
</s>
<s>
However_RR ,_, in_II many_DA2 situations_NN2 ,_, customers_NN2 may_VM not_XX know_VVI exactly_RR what_DDQ they_PPHS2 need_VV0 and_CC have_VH0 limited_VVN information_NN1 to_TO evaluate_VVI all_DB the_AT alternatives_NN2 ._. 
</s>
<s>
Just_RR as_CSA Newell_NP1 and_CC Simon_NP1 (_( 1972_MC ,_, as_CSA cited_VVN in_II Riquelme_NP1 2001_MC )_) pointed_VVD that_DD1 decision_NN1 maker_NN1 are_VBR not_XX always_RR rational_JJ ,_, but_CCB they_PPHS2 are_VBR rationally_RR bounded_VVN ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, it_PPH1 is_VBZ impossible_JJ for_IF mobile_JJ phone_NN1 buyers_NN2 to_TO assess_VVI all_DB information_NN1 available_JJ ._. 
</s>
<s>
Therefore_RR ,_, certain_JJ methods_NN2 should_VM be_VBI used_VVN obtain_VV0 insight_NN1 into_II customers_NN2 motivation_NN1 ._. 
</s>
<s>
In_II previous_JJ studies_NN2 ,_, there_EX is_VBZ few_DA2 literature_NN1 discussing_VVG factors_NN2 that_CST affect_VV0 customers_NN2 choice_NN1 of_IO mobile_JJ phones_NN2 ._. 
</s>
<s>
Keikki_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2005_MC )_) use_VV0 group_NN1 interviews_NN2 among_II graduate_NN1 students_NN2 in_II Finland_NP1 to_TO study_VVI how_RRQ Finns_NN2 make_VV0 their_APPGE choice_NN1 on_II mobile_JJ phones_NN2 ._. 
</s>
<s>
The_AT study_NN1 has_VHZ found_VVN that_CST Nokia_NP1 is_VBZ the_AT most_RGT popular_JJ mobile_JJ phone_NN1 brand_NN1 in_II their_APPGE interviewees_NN2 mind_VV0 ._. 
</s>
<s>
Moreover_RR ,_, they_PPHS2 also_RR found_VVD out_RP that_DD1 price_NN1 ,_, new_JJ features_NN2 ,_, size_NN1 of_IO the_AT mobile_JJ phone_NN1 and_CC brand_NN1 are_VBR regarded_VVN as_II the_AT most_RGT important_JJ factors_NN2 that_CST affect_VV0 Finnish_JJ students_NN2 choices_NN2 of_IO mobile_JJ phones_NN2 ._. 
</s>
<s>
Liu_NP1 (_( 2002_MC )_) did_VDD her_APPGE study_VVI in_II Philippines_NP2 and_CC she_PPHS1 mainly_RR focused_VVN on_II how_RGQ different_JJ activities_NN2 such_II21 as_II22 advertising_NN1 affect_NN1 consumers_NN2 choice_NN1 of_IO mobile_JJ phones_NN2 ._. 
</s>
<s>
In_II her_APPGE study_NN1 ,_, she_PPHS1 used_VVD regression_NN1 analysis_NN1 ,_, which_DDQ focuses_VVZ on_II the_AT relationship_NN1 between_II a_AT1 dependent_JJ variable_NN1 and_CC one_MC1 or_CC more_DAR independent_JJ variables_NN2 ._. 
</s>
<s>
Her_APPGE study_NN1 indicated_VVD that_DD1 size_NN1 and_CC brand_NN1 of_IO a_AT1 phone_NN1 can_VM affect_VVI consumers_NN2 choice_NN1 of_IO mobile_JJ phones_NN2 ._. 
</s>
<s>
Riquelmes_NN2 (_( 2001_MC )_) study_NN1 suggested_VVD that_CST prior_JJ experience_NN1 of_IO mobile_JJ phone_NN1 choice_NN1 can_VM affect_VVI consumers_NN2 future_JJ choices_NN2 ._. 
</s>
<s>
In_II this_DD1 paper_NN1 ,_, Repertory_NN1 Grid_NN1 Technique_NN1 is_VBZ used_VVN in_BCL21 order_BCL22 to_TO know_VVI how_RGQ individual_JJ develop_VV0 their_APPGE own_DA rules_NN2 to_TO guide_VVI their_APPGE buying_NN1 behavior_NN1 and_CC how_RRQ they_PPHS2 make_VV0 choices_NN2 when_CS buying_VVG mobile_JJ phone_NN1 ._. 
</s>
<s>
The_AT following_JJ text_NN1 will_VM focus_VVI on_II the_AT origin_NN1 of_IO this_DD1 method_NN1 and_CC how_RRQ it_PPH1 works_VVZ ._. 
</s>
<s>
3_MC ._. 
</s>
<s>
Repertory_NN1 Grid_NN1 Technique_NN1 3.1_MC What_DDQ is_VBZ repertory_NN1 grid_NN1 ?_? 
</s>
<s>
Repertory_NN1 grid_NN1 has_VHZ become_VVN a_AT1 widely_RR used_JJ technique_NN1 in_II various_JJ fields_NN2 ,_, ranging_VVG from_II the_AT original_JJ application_NN1 in_II psychoanalysis_NN1 to_II social_JJ and_CC business_NN1 research_NN1 area_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ a_AT1 data_NN extraction_NN1 and_CC analysis_NN1 technique_NN1 rooted_VVN in_II Personal_JJ Construct_VV0 Theory_NN1 ,_, which_DDQ was_VBDZ developed_VVN by_II George_NP1 Kelly_NP1 in_II 1950s_MC2 ._. 
</s>
<s>
According_II21 to_II22 Kellys_NP2 Personal_JJ Construct_VV0 Theory_NN1 ,_, people_NN construct_VV0 their_APPGE concepts_NN2 with_IW their_APPGE experiences_NN2 ._. 
</s>
<s>
This_DD1 means_VVZ that_CST people_NN perceive_VV0 the_AT world_NN1 with_IW their_APPGE own_DA understandings_NN2 and_CC have_VH0 the_AT freedom_NN1 to_TO choose_VVI a_AT1 different_JJ understanding_NN1 of_IO what_DDQ he_PPHS1 or_CC she_PPHS1 experienced_VVD or_CC thought_VVD ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, each_DD1 individual_NN1 builds_VVZ a_AT1 system_NN1 of_IO constructs_NN2 to_TO interpret_VVI everything_PN1 around_RP ._. 
</s>
<s>
Therefore_RR ,_, if_CS we_PPIS2 go_VV0 in-depth_JJ of_IO how_RRQ these_DD2 constructs_NN2 are_VBR built_VVN ,_, we_PPIS2 can_VM find_VVI that_CST these_DD2 constructs_NN2 have_VH0 bipolar_JJ dimensions_NN2 ._. 
</s>
<s>
For_REX21 instance_REX22 ,_, we_PPIS2 know_VV0 that_CST ,_, based_VVN on_II our_APPGE experience_NN1 ,_, some_DD people_NN are_VBR easy-going_JJ while_CS others_NN2 are_VBR not_XX ._. 
</s>
<s>
When_CS we_PPIS2 meet_VV0 a_AT1 person_NN1 for_IF the_AT first_MD time_NNT1 ,_, we_PPIS2 may_VM consciously_RR or_CC subconsciously_RR categorize_VV0 him_PPHO1 or_CC her_PPHO1 according_II21 to_II22 that_DD1 construct_NN1 ._. 
</s>
<s>
Another_DD1 important_JJ point_NN1 of_IO the_AT Personal_JJ Construct_VV0 Theory_NN1 is_VBZ that_CST each_DD1 individual_NN1 has_VHZ his_APPGE or_CC her_APPGE own_DA unique_JJ set_NN1 of_IO constructs_NN2 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, differences_NN2 in_II peoples_NN2 construct_VV0 systems_NN2 contribute_VV0 to_II their_APPGE different_JJ perceptions_NN2 of_IO the_AT world_NN1 and_CC their_APPGE behavior_NN1 in_II it_PPH1 ._. 
</s>
<s>
In_II fact_NN1 ,_, it_PPH1 is_VBZ this_DD1 inherent_JJ difference_NN1 in_II construct_NN1 systems_NN2 between_II people_NN that_CST results_NN2 bias_VV0 in_II research_NN1 ._. 
</s>
<s>
Repertory_NN1 grid_NN1 was_VBDZ developed_VVN in_II an_AT1 attempt_NN1 to_TO minimize_VVI the_AT construct_NN1 bias_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ a_AT1 way_NN1 to_TO understand_VVI what_DDQ theories_NN2 people_NN are_VBR using_VVG to_TO make_VVI sense_NN1 of_IO something_PN1 ._. 
</s>
<s>
Roger_NP1 &;_NULL Ryals_NP1 (_( 2007:596-597_MCMC )_) defined_VVD repertory_NN1 grid_NN1 as_II a_AT1 research_NN1 tool_NN1 that_CST elicits_VVZ the_AT underlying_JJ constructs_NN2 that_CST people_NN use_VV0 to_TO interpret_VVI what_DDQ is_VBZ going_VVG on_RP around_II them_PPHO2 and_CC that_CST inform_VV0 their_APPGE decision-making_NN1 ._. 
</s>
<s>
Jankowicz_NP1 (_( 2003:14_MC )_) interpreted_VVD repertory_NN1 grid_NN1 as_II a_AT1 form_NN1 of_IO structured_JJ interviewing_NN1 ,_, with_IW ratings_NN2 or_CC without_RR ,_, which_DDQ arrives_VVZ at_II a_AT1 precise_JJ description_NN1 uncontaminated_JJ by_II the_AT interviewers_NN2 own_DA viewpoint_NN1 ._. 
</s>
<s>
3.2_MC Four_MC research_NN1 stages_NN2 of_IO repertory_NN1 grid_NN1 technique_NN1 3.2.1_MC Element_NN1 selection_NN1 When_CS we_PPIS2 do_VD0 repertory_NN1 grid_NN1 analysis_NN1 ,_, the_AT first_MD step_NN1 is_VBZ to_TO choose_VVI a_AT1 set_NN1 of_IO elements_NN2 ._. 
</s>
<s>
The_AT elements_NN2 are_VBR the_AT things_NN2 that_CST we_PPIS2 are_VBR going_VVGK to_TO examine_VVI and_CC should_VM be_VBI consistent_JJ with_IW the_AT objectives_NN2 of_IO a_AT1 study_NN1 ._. 
</s>
<s>
For_REX21 example_REX22 ,_, elements_NN2 can_VM be_VBI companies_NN2 ,_, cities_NN2 ,_, events_NN2 or_CC products_NN2 ._. 
</s>
<s>
Usually_RR ,_, the_AT elements_NN2 are_VBR decided_VVN by_II the_AT researcher_NN1 or_CC elicited_VVN through_II discussion_NN1 ._. 
</s>
<s>
3.2.2_MC Construct_VV0 elicitation_NN1 The_AT second_MD stage_NN1 of_IO using_VVG the_AT repertory_NN1 grid_NN1 technique_NN1 is_VBZ to_TO conduct_VVI personal_JJ interviews_NN2 with_IW consumers_NN2 in_BCL21 order_BCL22 to_TO elicit_VVI the_AT content_NN1 and_CC hierarchical_JJ structure_NN1 of_IO the_AT subjective_JJ meanings_NN2 ,_, in_II the_AT form_NN1 of_IO bipolar_JJ constructs_NN2 that_CST they_PPHS2 attach_VV0 to_II the_AT set_NN1 of_IO elements_NN2 (_( Dalton_NP1 and_CC Dunnett_NP1 ,_, 1992_MC )_) ._. 
</s>
<s>
In_II this_DD1 stage_NN1 ,_, each_DD1 element_NN1 will_VM be_VBI related_VVN to_II one_MC1 pole_NN1 or_CC the_AT other_NN1 of_IO the_AT construct_NN1 ._. 
</s>
<s>
Basically_RR ,_, there_EX are_VBR three_MC interviewing_JJ methods_NN2 in_II repertory_NN1 grid_NN1 analysis_NN1 :_: triading_VVG ,_, laddering_NN1 and_CC pyramiding_VVG ._. 
</s>
<s>
Triading_NP1 is_VBZ a_AT1 method_NN1 used_VMK to_TO ask_VVI the_AT interviewee_NN1 to_TO compare_VVI three_MC elements_NN2 chosen_VVN at_RR21 random_RR22 and_CC describe_VV0 how_RRQ two_MC of_IO them_PPHO2 are_VBR similar_JJ and_CC different_JJ from_II the_AT third_MD (_( Kelly_NP1 ,_, 1955_MC )_) ._. 
</s>
<s>
If_CS you_PPY want_VV0 to_TO elicit_VVI the_AT more_RGR abstract_JJ values_NN2 of_IO the_AT constructs_NN2 ,_, the_AT laddering_NN1 method_NN1 is_VBZ suggested_VVN ._. 
</s>
<s>
It_PPH1 is_VBZ method_NN1 used_VMK to_TO ask_VVI interviewee_NN1 which_DDQ pole_NN1 of_IO the_AT construct_VV0 they_PPHS2 prefer_VV0 and_CC why_RRQ it_PPH1 is_VBZ important_JJ to_II them_PPHO2 (_( Hinkle_NP1 ,_, 1965_MC )_) ._. 
</s>
<s>
Further_JJR more_RRR ,_, if_CS you_PPY want_VV0 to_TO elicit_VVI the_AT concrete_JJ benefits_NN2 of_IO each_DD1 construct_NN1 ,_, you_PPY are_VBR suggested_VVN to_TO use_VVI the_AT pyramiding_JJ method_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ usually_RR ask_VV0 the_AT interviewee_NN1 what_DDQ defined_VVD their_APPGE preferred_JJ construct_NN1 pole_NN1 (_( Landfield_NP1 ,_, 1971_MC )_) ._. 
</s>
<s>
3.2.3_MC Element_NN1 comparison_NN1 After_II each_DD1 interviewee_NN1 completing_VVG a_AT1 repertory_NN1 grid_NN1 questionnaire_NN1 ,_, it_PPH1 is_VBZ time_NNT1 to_TO examine_VVI the_AT relationships_NN2 between_II their_APPGE bipolar_JJ constructs_NN2 and_CC the_AT set_NN1 of_IO elements_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ an_AT1 important_JJ stage_NN1 because_CS the_AT structural_JJ similarities_NN2 ,_, structural_JJ differences_NN2 and_CC the_AT content_NN1 of_IO interviewees_NN2 construct_VV0 system_NN1 will_VM provide_VVI critical_JJ information_NN1 for_IF researchers_NN2 ._. 
</s>
<s>
In_II this_DD1 procedure_NN1 ,_, grids_NN2 are_VBR used_VVN to_TO describe_VVI the_AT elements_NN2 and_CC constructs_NN2 ._. 
</s>
<s>
Construct_VV0 poles_NN2 are_VBR recorded_VVN to_TO explain_VVI the_AT importance_NN1 of_IO the_AT construct_NN1 and_CC its_APPGE meaning_NN1 ._. 
</s>
<s>
Then_RT interviewees_NN2 are_VBR asked_VVN to_II rate_NN1 each_DD1 of_IO the_AT element_NN1 according_II21 to_II22 the_AT construct_NN1 poles_NN2 created_VVN ._. 
</s>
<s>
At_RR21 last_RR22 ,_, the_AT researcher_NN1 will_VM get_VVI a_AT1 richer_JJR picture_NN1 of_IO the_AT overall_JJ structure_NN1 of_IO interviewees_NN2 construct_VV0 system_NN1 ._. 
</s>
<s>
3.2.4_MC Data_NN analysis_NN1 In_II this_DD1 stage_NN1 ,_, you_PPY can_VM not_XX only_RR use_VVI quantitative_JJ method_NN1 to_TO interpret_VVI the_AT nature_NN1 of_IO the_AT grid_NN1 but_CCB also_RR use_VV0 the_AT qualitative_JJ method_NN1 to_TO maximize_VVI the_AT richness_NN1 of_IO results_NN2 and_CC understanding_NN1 of_IO individual_JJ interviewee_NN1 ._. 
</s>
<s>
In_II quantitative_JJ analysis_NN1 of_IO repertory_NN1 grid_NN1 ,_, the_AT output_NN1 of_IO which_DDQ represents_VVZ the_AT elements_NN2 as_CSA they_PPHS2 are_VBR categorized_VVN by_II the_AT group_NN1 as_II a_AT1 whole_NN1 while_CS the_AT constructs_NN2 with_IW the_AT highest_JJT variance_NN1 can_VM be_VBI identified_VVN ,_, grouped_VVN into_II similar_JJ themes_NN2 and_CC used_VVN to_TO define_VVI each_DD1 of_IO the_AT components_NN2 (_( Metzler_NP1 and_CC Neimeyer_NP1 ,_, 1988_MC )_) ._. 
</s>
<s>
Burr_NN1 and_CC Butt_NN1 (_( 1992_MC )_) stated_VVD this_DD1 quantitative_JJ technique_NN1 as_II a_AT1 good_JJ way_NN1 to_TO organize_VVI the_AT information_NN1 collected_VVN from_II each_DD1 participant_NN1 in_II the_AT personal_JJ interview_NN1 ._. 
</s>
<s>
However_RR ,_, qualitative_JJ analysis_NN1 of_IO repertory_NN1 grid_NN1 focuses_VVZ on_II coding_VVG the_AT qualitative_JJ data_NN taken_VVN from_II the_AT grid_NN1 and_CC the_AT constructs_NN2 themselves_PPX2 as_II31 well_II32 as_II33 interviewees_NN2 explanations_NN2 ._. 
</s>
<s>
3.3_MC Why_RRQ repertory_NN1 grid_NN1 technique_NN1 is_VBZ used_VVN in_II this_DD1 study_NN1 ?_? 
</s>
<s>
As_CSA mentioned_VVN before_RT ,_, this_DD1 paper_NN1 aims_VVZ to_TO figure_VVI out_RP the_AT factors_NN2 affecting_VVG customers_NN2 choice_NN1 making_NN1 of_IO mobile_JJ phones_NN2 ,_, it_PPH1 is_VBZ crucial_JJ to_TO know_VVI how_RRQ customers_NN2 making_VVG their_APPGE purchase_NN1 decision_NN1 ._. 
</s>
<s>
According_II21 to_II22 Roger_NP1 &;_NULL Ryals_NP1 (_( 2007_VV0 :_: 596-597_MCMC )_) ,_, the_AT constructs_NN2 that_CST people_NN use_VV0 to_TO explain_VVI what_DDQ happens_VVZ around_II them_PPHO2 can_VM inform_VVI their_APPGE decision_NN1 making_VVG and_CC repertory_NN1 grid_NN1 is_VBZ such_DA a_AT1 research_NN1 tool_NN1 that_CST can_NN1 elicits_VVZ peoples_NN2 underlying_VVG constructs_NN2 ._. 
</s>
<s>
Kelly_NP1 (_( 1955_MC )_) also_RR indicates_VVZ that_CST peoples_NN2 construct_VV0 systems_NN2 contribute_VV0 to_II their_APPGE different_JJ perceptions_NN2 of_IO the_AT world_NN1 and_CC their_APPGE behavior_NN1 in_II it_PPH1 ._. 
</s>
<s>
Therefore_RR ,_, I_PPIS1 believe_VV0 using_VVG this_DD1 method_NN1 could_VM explore_VVI the_AT real_JJ factors_NN2 that_CST affect_VV0 customers_NN2 choices_NN2 between_II different_JJ mobile_JJ phone_NN1 brands_NN2 ._. 
</s>
<s>
Previous_JJ studies_NN2 (_( Wilska_NP1 2003_MC ;_; Riquelme_NP1 ;_; 2001_MC ;_; Jone_NP1 ;_; 2002_MC ;_; Liu_NP1 2002_MC )_) on_II this_DD1 topic_NN1 all_DB used_JJ questionnaires_NN2 to_TO collect_VVI data_NN for_IF studies_NN2 ._. 
</s>
<s>
As_CSA all_DB these_DD2 questionnaires_NN2 are_VBR designed_VVN by_II the_AT researchers_NN2 before_II hand_NN1 ,_, therefore_RR researchers_NN2 personal_JJ opinions_NN2 about_II mobile_JJ phone_NN1 choice_NN1 may_VM somewhat_RR affect_VVI interviewees_NN2 choice_NN1 ._. 
</s>
<s>
Sometimes_RT they_PPHS2 are_VBR forced_VVN to_TO make_VVI choices_NN2 between_II different_JJ answers_NN2 which_DDQ probably_RR could_VM not_XX reflect_VVI what_DDQ customers_NN2 real_JJ thoughts_NN2 ._. 
</s>
<s>
Using_VVG repertory_NN1 grid_NN1 as_II a_AT1 tool_NN1 can_VM avoid_VVI this_DD1 problem_NN1 and_CC stimulate_VVI the_AT underlying_JJ factors_NN2 that_CST affect_VV0 customers_NN2 choice_NN1 of_IO mobile_JJ phones_NN2 ._. 
</s>
<s>
Rogers_NP1 and_CC Ryals_NP1 (_( 2007_VV0 :_: 601_MC )_) state_VV0 that_CST researchers_NN2 can_VM capture_VVI interviewees_NN2 perceptions_NN2 of_IO nebulous_JJ concepts_NN2 and_CC probe_VV0 below_II the_AT surface_NN1 into_II areas_NN2 of_IO unawareness_NN1 and_CC get_VV0 a_AT1 clear_JJ understanding_NN1 of_IO how_RRQ they_PPHS2 use_VV0 their_APPGE past_JJ experience_NN1 to_TO make_VVI judgments_NN2 ._. 
</s>
<s>
Except_CS advantages_NN2 mentioned_VVD before_RT ,_, there_EX are_VBR three_MC other_JJ advantages_NN2 listed_VVN by_II Roger_NP1 and_CC Ryals_NP1 (_( 2007:611_MC )_) ._. 
</s>
<s>
The_AT first_MD advantage_NN1 of_IO repertory_NN1 grid_NN1 technique_NN1 is_VBZ that_CST it_PPH1 can_VM minimize_VVI the_AT influence_NN1 of_IO the_AT interviewer_NN1 ._. 
</s>
<s>
Beside_II this_DD1 ,_, repertory_NN1 grid_NN1 can_VM also_RR help_VVI researchers_NN2 to_TO explore_VVI the_AT unarticulated_JJ concepts_NN2 and_CC constructs_NN2 that_CST underlie_VV0 peoples_NN2 responses_NN2 to_II the_AT world_NN1 ._. 
</s>
<s>
More_RRR over_RP ,_, repertory_NN1 grid_NN1 technique_NN1 can_VM also_RR help_VVI researchers_NN2 to_TO assess_VVI the_AT underlying_JJ realities_NN2 in_II situations_NN2 where_RRQ the_AT cultural_JJ or_CC people_NN issues_NN2 are_VBR particularly_RR strong_JJ ,_, and_CC where_RRQ interviewees_NN2 might_VM hard_RR to_TO express_VVI their_APPGE true_JJ minds_NN2 ._. 
</s>
<s>
4_MC ._. 
</s>
<s>
Methodology_NN1 As_II the_AT aim_NN1 of_IO the_AT study_NN1 is_VBZ to_TO find_VVI out_RP factors_NN2 that_CST affects_VVZ customers_NN2 choice_NN1 of_IO mobile_JJ phone_NN1 ._. 
</s>
<s>
I_PPIS1 firstly_RR select_VV0 six_MC known_JJ mobile_JJ phone_NN1 brand_NN1 which_DDQ are_VBR Nokia_NP1 ,_, Apple_NN1 ,_, Samsung_NP1 ,_, Motorola_NP1 ,_, Sony_NP1 Ericsson_NP1 ,_, LG_NP1 ._. 
</s>
<s>
And_CC then_RT add_VV0 the_AT ideal_JJ one_PN1 as_II a_AT1 brand_NN1 to_TO help_VVI marketers_NN2 to_TO know_VVI exactly_RR what_DDQ kind_NN1 of_IO mobile_JJ phone_NN1 customers_NN2 really_RR need_VV0 ._. 
</s>
<s>
The_AT data_NN was_VBDZ collected_VVN from_II nine_MC interviewees_NN2 aged_VVN from_II 20_MC years_NNT2 old_JJ to_II 30_MC years_NNT2 old_JJ ._. 
</s>
<s>
All_DB the_AT interviews_NN2 were_VBDR done_VDN with_IW assistance_NN1 of_IO computers_NN2 ._. 
</s>
<s>
Before_II doing_VDG the_AT interviews_NN2 ,_, all_DB the_AT interviewees_NN2 are_VBR given_VVN detailed_JJ tips_NN2 on_II how_RRQ to_TO use_VVI the_AT repertory_NN1 grid_NN1 software_NN1 with_IW the_AT help_NN1 of_IO computer_NN1 to_TO ensure_VVI the_AT validity_NN1 of_IO the_AT data_NN being_VBG collected_VVN ._. 
</s>
<s>
The_AT research_NN1 used_VVD four_MC processes_NN2 to_TO complete_VVI the_AT repertory_NN1 grid_NN1 (_( see_VV0 Table_NN1 1_MC1 )_) ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) 5_MC ._. 
</s>
<s>
Results_NN2 and_CC analysis_NN1 As_CSA mentioned_VVN before_RT ,_, the_AT repertory_NN1 grid_NN1 interviews_NN2 were_VBDR conducted_VVN with_IW nine_MC customers_NN2 aged_VVN from_II 20_MC years_NNT2 old_JJ to_II 30_MC years_NNT2 old_JJ ._. 
</s>
<s>
A_AT1 total_NN1 of_IO 45_MC constructs_NN2 were_VBDR obtained_VVN from_II the_AT nine_MC interviewees_NN2 ._. 
</s>
<s>
Then_RT I_PPIS1 combined_VVD the_AT same_DA constructs_NN2 and_CC very_RG some_DD similar_JJ ones_NN2 ,_, for_REX21 instance_REX22 ,_, I_PPIS1 contribute_VV0 fashion_NN1 and_CC up-to-date_JJ to_II novel_NN1 ,_, thin_JJ to_II portable_JJ ,_, and_CC attractive_JJ and_CC smart_JJ to_II better_JJR design_NN1 ._. 
</s>
<s>
After_CS this_DD1 process_NN1 was_VBDZ conducted_VVN there_EX were_VBDR 16_MC constructs_NN2 left_VVD ._. 
</s>
<s>
Among_II these_DD2 16_MC constructs_NN2 ,_, 5_MC constructs_NN2 were_VBDR mentioned_VVN by_II four_MC or_CC more_DAR interviewees_NN2 and_CC the_AT rest_NN1 constructs_NN2 were_VBDR mentioned_VVN once_RR or_CC twice_RR ._. 
</s>
<s>
Table_NN1 2_MC shows_VVZ all_DB the_AT 16_MC constructs_NN2 and_CC their_APPGE numbers_NN2 ,_, while_CS Table_NN1 3_MC presents_VVZ the_AT frequency_NN1 count_NN1 of_IO constructs_NN2 ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) &lsqb;_( Table_NN1 &rsqb;_) Of_IO all_DB the_AT constructs_NN2 ,_, 11_MC constructs_NN2 (_( 69%_NNU )_) were_VBDR mentioned_VVN by_II more_DAR than_CSN one_MC1 interviewee_NN1 ._. 
</s>
<s>
One_MC1 construct_VV0 (_( Novel_NN1 )_) was_VBDZ mentioned_VVN by_II six_MC interviewees_NN2 ,_, two_MC other_JJ constructs_NN2 (_( Keypad_NP1 Nationality_NN1 )_) were_VBDR mentioned_VVN by_II five_MC interviewees_NN2 ,_, Price_NP1 and_CC Function_NN1 were_VBDR mentioned_VVN by_II four_MC interviewees_NN2 ,_, and_CC better_JJR design_NN1 was_VBDZ mentioned_VVN three_MC by_II interviewees_NN2 ._. 
</s>
<s>
Therefore_RR ,_, I_PPIS1 think_VV0 these_DD2 constructs_NN2 which_DDQ were_VBDR mentioned_VVN more_RRR than_CSN or_CC equal_JJ to_II three_MC times_NNT2 should_VM be_VBI very_RG important_JJ in_II the_AT interviewees_NN2 perceptions_NN2 of_IO these_DD2 brands_NN2 ._. 
</s>
<s>
From_II the_AT overall_JJ results_NN2 ,_, Apple_NN1 and_CC Nokia_NP1 are_VBR regarded_VVN to_TO be_VBI the_AT top_NN1 two_MC brands_NN2 when_CS considering_VVG novel_JJ and_CC price_NN1 ._. 
</s>
<s>
The_AT two_MC brands_NN2 are_VBR also_RR regarded_VVN to_TO have_VHI good_JJ performance_NN1 in_II function_NN1 and_CC entertaining_JJ ._. 
</s>
<s>
In_II a_AT1 matter_JJ31 of_JJ32 fact_JJ33 ,_, all_DB of_IO my_APPGE interviewees_NN2 describe_VV0 Apple_NN1 in_II a_AT1 quite_RG similar_JJ way_NN1 :_: fashionable_JJ ,_, entertaining_JJ ,_, touch_VV0 screen_NN1 ,_, expensive_JJ ,_, novel_JJ and_CC multiple_JJ functions_NN2 ._. 
</s>
<s>
Nokia_NP1 ,_, on_II the_AT other_JJ hand_NN1 ,_, holds_VVZ the_AT second_MD or_CC third_MD place_NN1 on_II all_DB these_DD2 aspects_NN2 mentioned_VVD before_RT ._. 
</s>
<s>
From_II the_AT results_NN2 ,_, we_PPIS2 can_VM also_RR see_VVI that_CST Samsung_NP1 is_VBZ considered_VVN to_TO have_VHI a_AT1 moderate_JJ performance_NN1 ._. 
</s>
<s>
While_CS at_II the_AT same_DA time_NNT1 ,_, interviewees_NN2 perceptions_NN2 about_II LG_NP1 ,_, Sony_NP1 Ericsson_NP1 and_CC Motorola_NP1 changed_VVD greatly_RR ._. 
</s>
<s>
Some_DD interviewees_NN2 consider_VV0 Sony_NP1 Ericsson_NP1 as_II a_AT1 brand_NN1 suitable_JJ for_IF young_JJ people_NN ,_, fashion_NN1 looking_VVG and_CC with_IW big_JJ population_NN1 of_IO usage_NN1 and_CC Motorola_NP1 as_II a_AT1 brand_NN1 for_IF older_JJR people_NN ,_, lack_NN1 of_IO multiple-function_NN1 and_CC with_IW small_JJ population_NN1 of_IO usage_NN1 ._. 
</s>
<s>
While_CS some_DD regard_NN1 Motorola_NP1 as_II a_AT1 brand_NN1 to_TO be_VBI practical_JJ ,_, multiple-function_JJ and_CC better_JJR design_NN1 and_CC LG_NP1 as_II a_AT1 brand_NN1 to_TO be_VBI Asian_JJ ,_, non-practical_JJ and_CC ordinary_JJ design_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ interesting_JJ to_TO find_VVI out_RP that_DD1 quality_NN1 which_DDQ seems_VVZ to_TO be_VBI an_AT1 very_RG important_JJ factor_NN1 that_CST affects_VVZ customers_NN2 choice_NN1 of_IO mobile_JJ phone_NN1 mentioned_VVD only_RR once_RR of_IO all_DB the_AT nine_MC interviewees_NN2 ._. 
</s>
<s>
This_DD1 is_VBZ probably_RR because_CS quality_NN1 is_VBZ a_AT1 relatively_RR abstract_JJ word_NN1 to_TO differentiate_VVI different_JJ brands_NN2 of_IO mobile_JJ phones_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ also_RR interesting_JJ to_TO know_VVI that_CST one_MC1 interviewee_NN1 differentiate_VV0 these_DD2 brands_NN2 by_II whether_CSW31 or_CSW32 not_CSW33 the_AT company_NN1 produces_VVZ other_JJ electronic_JJ products_NN2 and_CC s/he_PPHS1 indicates_VVZ that_CST the_AT ideal_JJ mobile_JJ phone_NN1 should_VM be_VBI produced_VVN by_II companies_NN2 like_II Nokia_NP1 that_CST only_RR produce_VV0 mobile_JJ phones_NN2 ._. 
</s>
<s>
To_TO sum_VVI up_RP ,_, novel_NN1 ,_, price_NN1 ,_, function_NN1 ,_, nationality_NN1 and_CC keypad_NN1 are_VBR the_AT five_MC constructs_NN2 that_CST are_VBR believed_VVN to_TO be_VBI the_AT most_RGT important_JJ in_II interviewees_NN2 point_NN1 of_IO view_NN1 ._. 
</s>
<s>
The_AT results_NN2 obviously_RR show_VV0 that_CST seven_MC out_II21 of_II22 nine_MC interviewees_NN2 think_VV0 Apple_NN1 is_VBZ a_AT1 brand_NN1 that_CST is_VBZ much_RR closer_JJR to_II their_APPGE ideal_JJ mobile_JJ phones_NN2 and_CC Nokia_NP1 is_VBZ a_AT1 brand_NN1 that_CST ranks_NN2 after_II Apple_NN1 ._. 
</s>
<s>
Meanwhile_RR ,_, two_MC out_II21 of_II22 nine_MC interviewees_NN2 believe_VV0 that_CST Nokia_NP1 is_VBZ a_AT1 brand_NN1 that_CST is_VBZ much_RR closer_JJR to_II their_APPGE ideal_JJ mobile_JJ phones_NN2 and_CC Apple_NN1 is_VBZ a_AT1 brand_NN1 that_CST ranks_NN2 after_II Nokia_NP1 ._. 
</s>
<s>
As_II21 to_II22 other_JJ brands_NN2 such_II21 as_II22 Samsung_NP1 ,_, Sony_NP1 Ericsson_NP1 ,_, LG_NP1 and_CC Motorola_NP1 ,_, their_APPGE positions_NN2 in_II interviewees_NN2 mind_VV0 are_VBR changing_VVG greatly_RR ._. 
</s>
<s>
6_MC ._. 
</s>
<s>
Managerial_JJ implication_NN1 From_II the_AT empirical_JJ study_NN1 ,_, we_PPIS2 know_VV0 that_DD1 novel_NN1 ,_, price_NN1 and_CC function_NN1 are_VBR considered_VVN to_TO be_VBI very_RG important_JJ factors_NN2 that_CST affect_VV0 customers_NN2 choice_NN1 of_IO mobile_JJ phone_NN1 ._. 
</s>
<s>
In_II this_DD1 sense_NN1 ,_, from_II the_AT product_NN1 perspective_NN1 ,_, managers_NN2 should_VM lay_VVI much_DA1 attention_NN1 on_II the_AT mobile_JJ phones_NN2 novel_NN1 and_CC functions_NN2 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, most_DAT customers_NN2 consider_VV0 their_APPGE ideal_JJ mobile_JJ phone_NN1 should_VM be_VBI fashionable_JJ and_CC multifunctional_JJ ._. 
</s>
<s>
Therefore_RR ,_, it_PPH1 is_VBZ wise_JJ for_IF managers_NN2 to_TO improve_VVI the_AT design_NN1 and_CC the_AT functions_NN2 of_IO their_APPGE mobile_JJ phones_NN2 ._. 
</s>
<s>
From_II the_AT results_NN2 obtained_VVN ,_, keypad_NN1 is_VBZ also_RR regarded_VVN as_II an_AT1 important_JJ feature_NN1 that_CST consumers_NN2 tend_VV0 to_TO take_VVI into_II consideration_NN1 while_CS buying_VVG a_AT1 mobile_JJ phone_NN1 ._. 
</s>
<s>
In_II a_AT1 matter_JJ31 of_JJ32 fact_JJ33 ,_, most_DAT people_NN prefer_VV0 a_AT1 mobile_JJ phone_NN1 with_IW touch_NN1 screen_NN1 or_CC with_IW both_DB2 touch_VV0 screen_NN1 and_CC keyboard_NN1 ._. 
</s>
<s>
This_DD1 trend_NN1 indicates_VVZ that_CST managers_NN2 should_VM keep_VVI up_RP with_IW customers_NN2 real_JJ needs_NN2 ._. 
</s>
<s>
Apart_II21 from_II22 this_DD1 ,_, entertaining_JJ ,_, portability_NN1 and_CC popularity_NN1 are_VBR also_RR import_VV0 factors_NN2 that_CST can_VM affect_VVI some_DD customers_NN2 choice_NN1 of_IO mobile_JJ phones_NN2 ._. 
</s>
<s>
We_PPIS2 can_VM also_RR find_VVI out_RP from_II the_AT empirical_JJ study_NN1 that_CST nationality_NN1 is_VBZ one_MC1 of_IO the_AT most_RGT important_JJ factors_NN2 that_CST affect_VV0 customers_NN2 choice_NN1 of_IO mobile_JJ phone_NN1 ._. 
</s>
<s>
This_DD1 fact_NN1 indicates_VVZ that_DD1 brand_NN1 building_NN1 is_VBZ very_RG important_JJ for_IF mobile_JJ phones_NN2 ._. 
</s>
<s>
In_II the_AT interviews_NN2 ,_, mobile_JJ phones_NN2 such_II21 as_II22 Apple_NN1 and_CC Nokia_NP1 which_DDQ have_VH0 a_AT1 clear_JJ brand_NN1 image_NN1 and_CC mobile_JJ phones_NN2 such_II21 as_II22 LG_NP1 ,_, Samsung_NP1 ,_, Sony_NP1 Ericsson_NP1 ,_, and_CC Motorola_NP1 have_VH0 a_AT1 relatively_RR vague_JJ brand_NN1 image_NN1 in_II customers_NN2 minds_NN2 ._. 
</s>
<s>
Therefore_RR ,_, from_II a_AT1 brand_NN1 building_NN1 perspective_NN1 ,_, managers_NN2 should_VM try_VVI to_TO build_VVI a_AT1 clear_JJ brand_NN1 image_NN1 for_IF their_APPGE mobile_JJ phones_NN2 through_II marketing_NN1 strategies_NN2 ._. 
</s>
<s>
Besides_RR ,_, when_RRQ price_VV0 the_AT mobile_JJ phones_NN2 ,_, managers_NN2 should_VM also_RR be_VBI careful_JJ ._. 
</s>
<s>
All_DB the_AT interviewees_NN2 in_II my_APPGE study_NN1 said_VVD that_CST the_AT price_NN1 of_IO their_APPGE ideal_JJ mobile_JJ phone_NN1 should_VM not_XX be_VBI too_RG low_JJ ._. 
</s>
<s>
As_II the_AT ideal_JJ mobile_JJ phone_NN1 for_IF most_DAT interviewees_NN2 should_VM be_VBI well-designed_JJ ,_, multifunctional_JJ ,_, novel_NN1 ,_, good_JJ brand_NN1 image_NN1 and_CC portable_JJ ,_, most_DAT interviewees_NN2 think_VV0 the_AT price_NN1 for_IF such_DA a_AT1 great_JJ mobile_JJ phone_NN1 should_VM be_VBI a_RR21 bit_RR22 high_JJ but_CCB not_XX too_RG high_JJ ._. 
</s>
<s>
7_MC ._. 
</s>
<s>
Limitations_NN2 of_IO the_AT study_NN1 In_II this_DD1 study_NN1 ,_, I_PPIS1 think_VV0 there_EX are_VBR some_DD limitations_NN2 of_IO both_DB2 the_AT methods_NN2 and_CC the_AT findings_NN2 ._. 
</s>
<s>
First_MD ,_, as_CSA there_EX is_VBZ limited_JJ time_NNT1 to_TO collect_VVI large_JJ amount_NN1 of_IO data_NN ,_, only_RR nine_MC interviews_NN2 are_VBR conducted_VVN in_II this_DD1 study_NN1 ._. 
</s>
<s>
This_DD1 may_VM somewhat_RR affect_VVI the_AT reliability_NN1 of_IO this_DD1 study_NN1 ._. 
</s>
<s>
If_CS more_DAR data_NN are_VBR collected_VVN ,_, new_JJ factors_NN2 that_CST affect_VV0 customers_NN2 choice_NN1 of_IO mobile_JJ phones_NN2 may_VM be_VBI generated_VVN ._. 
</s>
<s>
The_AT second_MD limitation_NN1 of_IO this_DD1 study_NN1 is_VBZ that_CST the_AT bipolar_JJ constructs_NN2 of_IO repertory_NN1 grid_NN1 may_VM not_XX helpful_JJ because_CS meaning_NN1 can_VM be_VBI contested_VVN ._. 
</s>
<s>
As_CSA Marsden_NP1 and_CC Litter_NN1 (_( 1998_MC )_) stated_VVD that_CST words_NN2 in_II different_JJ contexts_NN2 may_VM have_VHI different_JJ meanings_NN2 which_DDQ may_VM results_NN2 problem_NN1 when_CS interviewing_VVG people_NN from_II different_JJ field_NN1 of_IO work_NN1 ._. 
</s>
<s>
Concerning_II the_AT limitations_NN2 of_IO the_AT findings_NN2 ,_, limited_JJ data_NN may_VM restrict_VVI the_AT interpretation_NN1 of_IO the_AT findings_NN2 ._. 
</s>
<s>
When_RRQ interpret_VV0 the_AT finding_NN1 ,_, some_DD constructs_NN2 are_VBR combined_VVN based_VVN on_II the_AT interviewers_NN2 own_DA knowledge_NN1 ,_, so_CS this_DD1 process_NN1 may_VM affect_VVI the_AT results_NN2 of_IO the_AT findings_NN2 ._. 
</s>
<s>
8_MC ._. 
</s>
<s>
Conclusions_NN2 This_DD1 paper_NN1 aims_VVZ to_TO explore_VVI the_AT real_JJ factors_NN2 that_CST affect_VV0 customers_NN2 choice_NN1 of_IO mobile_JJ phones_NN2 ._. 
</s>
<s>
In_II the_AT study_NN1 ,_, repertory_NN1 grid_NN1 technique_NN1 is_VBZ discussed_VVN ._. 
</s>
<s>
The_AT study_NN1 shows_VVZ that_CST this_DD1 approach_NN1 offers_VVZ managers_NN2 a_AT1 great_JJ alternative_NN1 to_TO explore_VVI customers_NN2 underlying_VVG factors_NN2 that_CST affect_VV0 their_APPGE choices_NN2 of_IO mobile_JJ phones_NN2 ._. 
</s>
<s>
The_AT results_NN2 of_IO the_AT study_NN1 show_VV0 that_DD1 novel_NN1 ,_, price_NN1 ,_, function_NN1 ,_, nationality_NN1 and_CC keypad_NN1 are_VBR the_AT most_RGT important_JJ factors_NN2 that_CST affect_VV0 customers_NN2 choice_NN1 of_IO mobile_JJ phone_NN1 ._. 
</s>
<s>
However_RR ,_, as_CSA there_EX are_VBR limited_JJ data_NN ,_, I_PPIS1 think_VV0 other_JJ factors_NN2 generated_VVN in_II this_DD1 study_NN1 should_VM not_XX be_VBI ignored_VVN by_II managers_NN2 when_CS they_PPHS2 produce_VV0 and_CC market_VV0 their_APPGE products_NN2 ._. 
</s>
<s>
In_II the_AT end_NN1 of_IO this_DD1 paper_NN1 ,_, managerial_JJ implication_NN1 and_CC limitation_NN1 of_IO this_DD1 study_NN1 are_VBR discussed_VVN ._. 
</s>
