<s>
Inequality_NN1 in_II Finland_NP1 -_- is_VBZ the_AT "_" Europe_NP1 2020_MC "_" -Strategy_NN1 Focusing_VVG on_II the_AT Right_JJ Things_NN2 ?_? 1_MC1 Introduction_NN1 Income_NN1 inequality_NN1 has_VHZ been_VBN on_II the_AT rise_NN1 in_II Finland_NP1 during_II the_AT past_JJ decades_NNT2 ._. 
</s>
<s>
Firstly_RR ,_, the_AT functional_JJ income_NN1 distribution_NN1 has_VHZ shifted_VVN away_II21 from_II22 labour_NN1 income_NN1 to_II ,_, increasingly_RR ,_, favour_VV0 capital_NN1 income_NN1 ._. 
</s>
<s>
While_CS labour_NN1 's_GE share_NN1 of_IO the_AT national_JJ income_NN1 was_VBDZ 69.4_MC per_NNU21 cent_NNU22 in_II 1993_MC ,_, its_APPGE share_NN1 in_II 2007_MC had_VHD shrunk_VVN to_II about_RG 56.3_MC per_NNU21 cent_NNU22 according_II21 to_II22 official_JJ statistics_NN ._. 
</s>
<s>
On_II the_AT contrary_NN1 ,_, capital_NN1 's_GE share_NN1 grew_VVD from_II 15.6_MC to_II 29.8_MC per_NNU21 cent_NNU22 in_II the_AT same_DA period_NN1 ._. 
</s>
<s>
Secondly_RR ,_, the_AT change_NN1 in_II the_AT functional_JJ income_NN1 distribution_NN1 has_VHZ also_RR affected_VVN the_AT relative_JJ income_NN1 distribution_NN1 between_II households_NN2 ._. 
</s>
<s>
For_REX21 instance_REX22 ,_, the_AT income_NN1 share_NN1 of_IO the_AT lowest_JJT income_NN1 decile_NN1 shrunk_VVN from_II 4.9_MC per_NNU21 cent_NNU22 in_II 1993_MC to_II 3.9_MC per_NNU21 cent_NNU22 in_II 2007_MC while_CS the_AT share_NN1 of_IO the_AT highest_JJT income_NN1 decile_NN1 grew_VVD from_II 19.2_MC to_II 23.9_MC per_NNU21 cent_NNU22 respectively_RR ._. 
</s>
<s>
In_II fact_NN1 ,_, during_II the_AT period_NN1 1993_MC to_II 2007_MC income_NN1 shares_NN2 shifted_VVN from_II the_AT eight_MC lowest_JJT deciles_NN2 ,_, which_DDQ all_DB saw_VVD their_APPGE shares_NN2 shrink_VVI ,_, to_II the_AT top_NN1 two_MC ,_, who_PNQS consequently_RR grew_VVD their_APPGE shares_NN2 on_II the_AT expense_NN1 of_IO the_AT former_DA ._. 
</s>
<s>
One_MC1 of_IO the_AT reasons_NN2 for_IF this_DD1 development_NN1 can_VM be_VBI traced_VVN back_RP to_II the_AT tax_NN1 reform_NN1 in_II 1993_MC where_RRQ the_AT separation_NN1 of_IO capital_NN1 and_CC labour_NN1 income_NN1 taxation_NN1 tilted_VVD the_AT income_NN1 distribution_NN1 in_II31 favour_II32 of_II33 ,_, often_RR capital_JJ rich_JJ ,_, high_JJ income_NN1 earners_NN2 (_( Ruotsalainen_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
Another_DD1 reason_NN1 is_VBZ that_DD1 social_JJ benefit_NN1 payments_NN2 ,_, which_DDQ are_VBR predominantly_RR directed_VVN at_II the_AT lower_JJR income_NN1 groups_NN2 ,_, have_VH0 not_XX kept_VVN up_RP with_IW the_AT rise_NN1 in_II living_JJ expenditures_NN2 (_( Savela_NP1 ,_, 2008_MC )_) ._. 
</s>
<s>
With_IW this_DD1 in_II mind_NN1 the_AT Finnish_JJ Government_NN1 of_IO Prime_JJ Minister_NN1 Jyrki_NP1 Katainen_NP1 adopted_VVD a_AT1 new_JJ growth_NN1 strategy_NN1 in_II June_NPM1 2011_MC ,_, called_VVD "_" Europe_NP1 2020_MC "_" ,_, which_DDQ specifically_RR emphasizes_VVZ the_AT impor-_JJ tance_NN1 of_IO reducing_VVG poverty_NN1 ._. 
</s>
<s>
Namely_REX ,_, one_MC1 of_IO the_AT key_JJ objectives_NN2 in_II the_AT strategy_NN1 is_VBZ to_TO reduce_VVI the_AT number_NN1 of_IO people_NN at_II risk_NN1 of_IO poverty_NN1 in_II Finland_NP1 from_II 920_MC 000_MC to_II 770_MC 000_MC by_II the_AT year_NNT1 2020_MC ._. 
</s>
<s>
This_DD1 is_VBZ to_TO be_VBI achieved_VVN mainly_RR by_II countering_VVG social_JJ and_CC economic_JJ deprivation_NN1 through_II various_JJ support_NN1 programmes_NN2 and_CC increased_JJ so-_JJ cial_JJ benefits_NN2 ,_, but_CCB also_RR by_II increasing_JJ employment_NN1 rates_NN2 and_CC promoting_VVG economic_JJ growth_NN1 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, in_II a_AT1 bid_NN1 to_TO balance_VVI public_JJ finances_NN2 ,_, the_AT Government_NN1 has_VHZ also_RR announced_VVN changes_NN2 in_II the_AT taxation_NN1 of_IO income_NN1 ._. 
</s>
<s>
Although_CS some_DD level_NN1 of_IO inequality_NN1 is_VBZ an_AT1 inherent_JJ ,_, and_CC necessary_JJ ,_, by-product_NN1 of_IO economic_JJ growth_NN1 ,_, many_DA2 argue_VV0 that_CST excessive_JJ inequality_NN1 is_VBZ not_XX only_RR socially_RR detrimental_JJ ,_, but_CCB could_VM potentially_RR also_RR have_VHI negative_JJ effects_NN2 on_II economic_JJ growth_NN1 itself_PPX1 ._. 
</s>
<s>
Higher_JJR levels_NN2 of_IO inequality_NN1 might_VM ,_, for_REX21 instance_REX22 ,_, lower_JJR domestic_JJ demand_NN1 and_CC affect_VV0 investments_NN2 through_II changes_NN2 in_II the_AT way_NN1 capital_NN1 is_VBZ accumulated_VVN and_CC used_JJ (_( Ehrhart_NP1 ,_, 2009_MC )_) ._. 
</s>
<s>
It_PPH1 might_VM also_RR give_VVI rise_NN1 to_II increased_JJ social_JJ instability_NN1 and_CC criminality_NN1 ,_, and_CC ,_, in_II the_AT presence_NN1 of_IO a_AT1 welfare_NN1 state_NN1 ,_, higher_JJR taxes_NN2 and_CC rent_VV0 seeking_VVG behaviour_NN1 by_II those_DD2 enjoying_VVG social_JJ benefits_NN2 (_( Alesina_NP1 and_CC Perotti_NP1 ,_, 1994_MC )_) ._. 
</s>
<s>
The_AT peculiarity_NN1 is_VBZ that_CST these_DD2 effects_NN2 are_VBR not_XX merely_RR a_AT1 product_NN1 of_IO some_DD level_NN1 of_IO absolute_JJ poverty_NN1 ,_, although_CS they_PPHS2 are_VBR highly_RR interrelated_JJ ,_, it_PPH1 is_VBZ the_AT relative_JJ poverty_NN1 within_II a_AT1 community_NN1 that_CST can_VM cause_VVI these_DD2 detrimental_JJ effects_NN2 ._. 
</s>
<s>
Thus_RR ,_, the_AT "_" Europe_NP1 2020_MC "_" -strategy_NN1 raises_VVZ a_AT1 few_DA2 questions_NN2 which_DDQ this_DD1 paper_NN1 hopes_VVZ to_TO answer_VVI ._. 
</s>
<s>
Firstly_RR ,_, is_VBZ focusing_VVG simply_RR on_II the_AT reduction_NN1 of_IO the_AT number_NN1 of_IO those_DD2 at_II risk_NN1 of_IO poverty_NN1 the_AT most_RGT efficient_JJ way_NN1 to_TO proceed_VVI ?_? 
</s>
<s>
Surely_RR ,_, there_EX is_VBZ nothing_PN1 wrong_JJ in_II helping_VVG the_AT poor_JJ ,_, but_CCB if_CS the_AT reduction_NN1 in_II poverty_NN1 among_II the_AT poor_JJ is_VBZ not_XX equal_JJ to_TO ,_, or_CC greater_JJR than_CSN ,_, the_AT increase_NN1 in_II prosperity_NN1 among_II the_AT rich_JJ ,_, the_AT net_JJ effect_NN1 would_VM still_RR be_VBI more_DAR inequality_NN1 ._. 
</s>
<s>
Secondly_RR ,_, are_VBR the_AT proposed_JJ measures_NN2 going_VVGK to_TO reduce_VVI inequality_NN1 ?_? 
</s>
<s>
It_PPH1 should_VM be_VBI obvious_JJ that_CST if_CS the_AT Government_NN1 were_VBDR to_TO combat_VVI inequality_NN1 ,_, it_PPH1 should_VM focus_VVI on_II the_AT causes_NN2 of_IO the_AT problems_NN2 rather_II21 than_II22 merely_RR alleviating_VVG the_AT symptoms_NN2 ._. 
</s>
<s>
Lastly_RR ,_, inequality_NN1 is_VBZ more_DAR than_CSN just_RR an_AT1 economic_JJ question_NN1 ,_, it_PPH1 is_VBZ above_II all_DB a_AT1 social_JJ and_CC moral_JJ dilemma_NN1 and_CC what_DDQ we_PPIS2 ought_VMK to_TO ask_VVI ourselves_PPX2 is_VBZ :_: what_DDQ kind_NN1 of_IO a_AT1 society_NN1 do_VD0 we_PPIS2 really_RR want_VVI to_TO live_VVI in_RP ?_? 
</s>
<s>
The_AT answer_NN1 to_II this_DD1 question_NN1 may_VM have_VHI deeply_RR rooted_JJ implications_NN2 for_IF the_AT welfare_NN1 state_NN1 model_NN1 we_PPIS2 so_RR highly_RR regard_VV0 ._. 
</s>
<s>
The_AT paper_NN1 continues_VVZ with_IW a_AT1 general_JJ review_NN1 of_IO the_AT economic_JJ literature_NN1 on_II in-_JJ equality_NN1 in_II Section_NN1 2_MC ._. 
</s>
<s>
The_AT following_JJ section_NN1 ,_, Section_NN1 3_MC ,_, gives_VVZ a_AT1 historical_JJ account_NN1 for_IF the_AT recent_JJ evolution_NN1 and_CC causes_NN2 of_IO inequality_NN1 in_II Finland_NP1 ._. 
</s>
<s>
Section_NN1 4_MC discusses_VVZ the_AT proposed_JJ measures_NN2 of_IO the_AT "_" Europe_NP1 2020_MC "_" -strategy_JJ ,_, its_APPGE appropriateness_NN1 and_CC implications_NN2 for_IF the_AT future_JJ development_NN1 of_IO inequality_NN1 in_II Finland_NP1 ._. 
</s>
<s>
Section_NN1 5_MC concludes._NNU 2_MC Income_NN1 Inequality_NN1 and_CC Growth_NN1 One_MC1 of_IO the_AT first_MD attempts_NN2 to_TO model_VVI the_AT relation_NN1 between_II income_NN1 inequality_NN1 and_CC economic_JJ growth_NN1 was_VBDZ done_VDN by_II Kuznets_NP1 (_( 1955_MC )_) who_PNQS examined_VVD the_AT long_JJ run_NN1 ef-_NN1 fects_NN2 of_IO economic_JJ development_NN1 on_II inequality_NN1 ._. 
</s>
<s>
The_AT study_NN1 found_VVD that_CST the_AT long_JJ run_NN1 relation_NN1 between_II economic_JJ development_NN1 and_CC inequality_NN1 tend_VV0 to_TO follow_VVI an_AT1 inverted_JJ U-shaped_JJ curve_NN1 ,_, where_CS countries_NN2 in_II the_AT early_JJ stages_NN2 of_IO development_NN1 experience_NN1 increasing_JJ inequality_NN1 ,_, while_CS countries_NN2 in_II latter_DA stages_NN2 ,_, developed_JJ be-_NN1 yond_VV0 some_DD threshold_NN1 value_NN1 ,_, will_VM see_VVI decreasing_JJ levels_NN2 of_IO inequality_NN1 ._. 
</s>
<s>
Intuitively_RR ,_, structural_JJ changes_NN2 due_II21 to_II22 the_AT industrialization_NN1 of_IO developing_JJ countries_NN2 will_VM in-_NN1 creasingly_RR favour_VV0 firm_JJ owners_NN2 as_CSA workers_NN2 are_VBR trapped_VVN in_II lagging_NN1 (_( agricultural_JJ )_) industries_NN2 ._. 
</s>
<s>
However_RR ,_, once_RR a_AT1 certain_JJ level_NN1 of_IO economic_JJ wealth_NN1 has_VHZ been_VBN achieved_VVN and_CC the_AT transitional_JJ effects_NN2 have_VH0 started_VVN to_TO level_VVI out_RP ,_, the_AT gains_NN2 from_II the_AT in-_JJ creased_JJ overall_JJ wealth_NN1 will_VM increasingly_RR be_VBI more_RGR evenly_RR distributed_VVN due_II21 to_II22 the_AT so_JJ21 called_JJ22 "_" trickle-down_JJ "_" effect_NN1 ._. 
</s>
<s>
Although_CS the_AT Kuznets_NP1 curve_NN1 might_VM provide_VVI a_AT1 rough_JJ guidance_NN1 on_II the_AT long_JJ term_NN1 dynamics_NN of_IO the_AT inequality_NN1 and_CC growth_NN1 relation_NN1 ,_, it_PPH1 has_VHZ been_VBN criticized_VVN for_IF not_XX adequately_RR accounting_VVG for_IF cross_NN1 country_NN1 differences_NN2 ._. 
</s>
<s>
For_REX21 instance_REX22 ,_, one_MC1 of_IO its_APPGE critics_NN2 ,_, Fields_NN2 (_( 1980_MC ,_, p._NN1 94_MC )_) argue_VV0 that_CST the_AT level_NN1 of_IO de-_JJ velopment_NN1 alone_RR can_VM not_XX explain_VVI the_AT between_II countries_NN2 differences_NN2 in_II inequality_NN1 ,_, rather_RR the_AT determining_JJ factor_NN1 is_VBZ the_AT interplay_NN1 between_II the_AT political_JJ environment_NN1 and_CC the_AT type_NN1 of_IO development_NN1 ._. 
</s>
<s>
Building_NN1 upon_II this_DD1 notion_NN1 the_AT reminder_NN1 of_IO this_DD1 section_NN1 examines_VVZ this_DD1 interplay_NN1 more_RGR closely_RR and_CC in_II the_AT spirit_NN1 of_IO this_DD1 paper_NN1 I_PPIS1 specifically_RR focus_VV0 on_II the_AT causation_NN1 going_VVG from_II inequality_NN1 to_II growth_NN1 instead_II21 of_II22 a_AT1 more_RGR general_JJ review_NN1 of_IO the_AT two_MC way_NN1 relation._NNU 2.1_MC The_AT Economic_JJ Channels_NN2 The_AT channels_NN2 through_II which_DDQ inequality_NN1 may_VM affect_VVI growth_NN1 may_VM be_VBI divided_VVN into_II two_MC sections_NN2 ;_; the_AT purely_RR economical_JJ channels_NN2 and_CC the_AT politico-economic_JJ channels_NN2 ._. 
</s>
<s>
I_PPIS1 start_VV0 with_IW the_AT former_DA ._. 
</s>
<s>
Increased_JJ inequality_NN1 may_VM affect_VVI growth_NN1 through_II its_APPGE impact_NN1 on_II the_AT accumulation_NN1 of_IO physical_JJ ,_, and_CC human_NN1 ,_, capital_NN1 and_CC aggregate_JJ demand_NN1 (_( Ehrhart_NP1 ,_, 2009_MC )_) ._. 
</s>
<s>
First_MD ,_, in_II the_AT presence_NN1 of_IO imperfect_JJ capital_NN1 markets_NN2 the_AT poor_JJ may_VM not_XX have_VHI access_NN1 to_II capital_NN1 which_DDQ they_PPHS2 could_VM invest_VVI productively_RR in_II production_NN1 or_CC education_NN1 ._. 
</s>
<s>
If_CS the_AT relative_JJ amount_NN1 of_IO poor_JJ people_NN is_VBZ high_JJ and_CC capital_NN1 is_VBZ predominantly_RR allocated_VVN among_II the_AT rich_JJ ,_, the_AT lack_NN1 of_IO adequate_JJ collateral_NN1 among_II the_AT poor_JJ creates_VVZ a_AT1 situation_NN1 where_RRQ lending_NN1 across_II the_AT income_NN1 groups_NN2 is_VBZ scarce_JJ (_( Piketty_NP1 ,_, 1997_MC )_) ._. 
</s>
<s>
Suppose_VV0 that_CST the_AT initial_JJ wealth_NN1 of_IO the_AT borrower_NN1 is_VBZ low_JJ ,_, in_II this_DD1 case_NN1 the_AT borrower_NN1 has_VHZ less_DAR to_TO lose_VVI if_CSW his_APPGE or_CC her_APPGE investment_NN1 goes_VVZ bust_JJ ._. 
</s>
<s>
Thus_RR ,_, when_CS the_AT personal_JJ risk_NN1 is_VBZ low_JJ ,_, the_AT borrower_NN1 has_VHZ an_AT1 incentive_NN1 to_TO borrow_VVI more_RRR ,_, in_II relation_NN1 his_APPGE or_CC her_APPGE wealth_NN1 ,_, and_CC to_TO be_VBI less_RGR cautious_JJ with_IW his_APPGE or_CC her_APPGE investment_NN1 ._. 
</s>
<s>
This_DD1 implies_VVZ that_CST the_AT flow_NN1 of_IO capital_NN1 from_II rich_JJ to_II poor_JJ would_VM be_VBI scarce_JJ and_CC ,_, due_II21 to_II22 high_JJ demand_NN1 ,_, high_JJ interest_NN1 rates_NN2 would_VM further_RRR decrease_VVI the_AT access_NN1 to_II capital_NN1 for_IF the_AT poor_JJ ._. 
</s>
<s>
This_DD1 lack_NN1 of_IO capital_NN1 may_VM even_RR become_VVI persistent_JJ ,_, stretching_VVG over_RP generations_NN2 (_( Piketty_NP1 ,_, 1994_MC )_) ._. 
</s>
<s>
If_CS current_JJ generations_NN2 of_IO poor_JJ people_NN can_VM not_XX adequately_RR access_VVI capital_NN1 ,_, and_CC thus_RR climb_VV0 the_AT income_NN1 ladder_NN1 ,_, future_JJ generations_NN2 are_VBR also_RR in_II risk_NN1 of_IO being_VBG trapped_VVN in_II the_AT same_DA situation_NN1 ._. 
</s>
<s>
Moreover_RR ,_, this_DD1 persistency_NN1 problem_NN1 is_VBZ aggravated_VVN if_CS a_AT1 person_NN1 's_GE functional_JJ status_NN1 ,_, whether_CSW a_AT1 person_NN1 is_VBZ an_AT1 employee_NN1 or_CC an_AT1 employer_NN1 ,_, depend_VV0 on_II his_APPGE or_CC her_APPGE initial_JJ wealth_NN1 ._. 
</s>
<s>
Indeed_RR ,_, Banerjee_NP1 and_CC Newman_NP1 (_( 1993_MC )_) find_VV0 that_CST poorer_JJR people_NN tend_VV0 to_TO become_VVI (_( low_JJ income_NN1 )_) wage_NN1 earners_NN2 while_CS richer_JJR people_NN become_VV0 (_( high_JJ income_NN1 )_) employers_NN2 ._. 
</s>
<s>
Second_MD ,_, growth_NN1 might_VM also_RR be_VBI affected_VVN by_II inequality_NN1 through_II changes_NN2 in_II aggregate_JJ demand_NN1 ._. 
</s>
<s>
More_RGR specifically_RR ,_, the_AT different_JJ consumption_NN1 patterns_NN2 of_IO poor_JJ ,_, middle_JJ class_NN1 ,_, and_CC rich_JJ people_NN ,_, respectively_RR ,_, will_VM determine_VVI not_XX only_RR the_AT size_NN1 of_IO a_AT1 country_NN1 's_GE economy_NN1 but_CCB also_RR its_APPGE composition_NN1 (_( Murphy_NP1 et_RA21 al._RA22 ,_, 1989_MC )_) ._. 
</s>
<s>
For_IF the_AT sake_NN1 of_IO argument_NN1 ,_, assume_VV0 that_CST poor_JJ people_NN mainly_RR consume_VV0 necessities_NN2 (_( food_NN1 ,_, clothes_NN2 ,_, etc._RA )_) ,_, middle_JJ class_NN1 people_NN consume_VV0 ,_, apart_II21 from_II22 necessities_NN2 ,_, also_RR increasingly_RR manufactures_VVZ (_( cars_NN2 ,_, mobile_JJ phones_NN2 ,_, etc._RA )_) ,_, and_CC rich_JJ people_NN consume_VV0 all_DB goods_NN2 available_JJ ,_, including_II luxury_JJ goods_NN2 ._. 
</s>
<s>
Additionally_RR ,_, when_CS the_AT level_NN1 of_IO income_NN1 of_IO a_AT1 person_NN1 increases_VVZ he_PPHS1 or_CC she_PPHS1 ,_, rather_II21 than_II22 consumes_VVZ more_DAR of_IO one_MC1 good_JJ ,_, expands_VVZ the_AT range_NN1 of_IO goods_NN2 consumed_VVD ._. 
</s>
<s>
Thus_RR ,_, in_II the_AT case_NN1 of_IO extreme_JJ inequality_NN1 ,_, and_CC consequently_RR no_AT middle_JJ class_NN1 ,_, demand_VV0 for_IF manufactures_VVZ would_VM be_VBI little_JJ or_CC non-existing_NN1 ._. 
</s>
<s>
This_DD1 lack_NN1 of_IO demand_NN1 would_VM lead_VVI to_II a_AT1 state_NN1 where_RRQ no_AT modern_JJ technology_NN1 would_VM be_VBI developed_VVN and_CC the_AT economy_NN1 would_VM not_XX grow_VVI ._. 
</s>
<s>
The_AT same_DA is_VBZ true_JJ for_IF the_AT opposite_JJ scenario_NN1 of_IO extreme_JJ equality_NN1 ._. 
</s>
<s>
In_II this_DD1 case_NN1 everyone_PN1 would_VM only_RR demand_VVI necessities_NN2 and_CC the_AT outcome_NN1 would_VM again_RT be_VBI that_CST no_AT modern_JJ technologies_NN2 were_VBDR developed_VVN ._. 
</s>
<s>
Building_NN1 on_II this_DD1 argument_NN1 Jaramillo_NP1 (_( 1995_MC )_) shows_VVZ that_CST less_DAR inequality_NN1 also_RR affects_VVZ the_AT size_NN1 of_IO the_AT economy_NN1 through_II employment_NN1 and_CC income_NN1 effects_NN2 ._. 
</s>
<s>
A_AT1 less_RGR unequal_JJ income_NN1 distribution_NN1 would_VM see_VVI a_AT1 rise_NN1 in_II the_AT demand_NN1 for_IF manufactures_VVZ ._. 
</s>
<s>
To_TO meet_VVI the_AT increased_JJ demand_NN1 firms_NN2 would_VM hire_VVI more_DAR workers_NN2 and_CC the_AT sector_NN1 would_VM start_VVI developing_JJ ._. 
</s>
<s>
With_IW the_AT new_JJ technologies_NN2 labour_VV0 productivity_NN1 is_VBZ driven_VVN up_RP which_DDQ lowers_VVZ prices_NN2 and_CC increases_NN2 demand_VV0 even_RR further_RRR ._. 
</s>
<s>
Thus_RR ,_, less_DAR inequality_NN1 can_VM stimulate_VVI growth_NN1 through_II its_APPGE positive_JJ employment_NN1 effects_NN2 on_II modern_JJ sectors._NNU 2.2_MC The_AT Politico-economic_JJ Channels_NN2 Inequality_NN1 does_VDZ not_XX only_RR have_VHI direct_JJ effects_NN2 on_II growth_NN1 ,_, rather_RR ,_, political_JJ ,_, social_JJ ,_, and_CC economic_JJ factors_NN2 jointly_RR determine_VV0 the_AT outcome_NN1 of_IO inequality_NN1 ._. 
</s>
<s>
First_MD ,_, an_AT1 unequal_JJ distribution_NN1 of_IO wealth_NN1 may_VM cause_VVI rent-seeking_JJ behaviour_NN1 and_CC increased_JJ rates_NN2 of_IO criminality_NN1 among_II the_AT poor_JJ (_( Alesina_NP1 and_CC Perotti_NP1 ,_, 1994_MC )_) ._. 
</s>
<s>
This_DD1 combined_VVN with_IW increased_JJ social_JJ and_CC political_JJ instability_NN1 may_VM effectively_RR restrain_VVI the_AT growth_NN1 of_IO the_AT local_JJ economy_NN1 and_CC deter_VV0 foreign_JJ investments_NN2 ._. 
</s>
<s>
Second_MD ,_, and_CC perhaps_RR more_RGR importantly_RR for_IF developed_JJ countries_NN2 ,_, fiscal_JJ policy_NN1 ,_, determined_VVN by_II a_AT1 democratic_JJ voting_NN1 process_NN1 ,_, is_VBZ likely_JJ to_TO affect_VVI the_AT returns_NN2 on_II investments_NN2 and_CC ,_, thus_RR ,_, growth_NN1 ._. 
</s>
<s>
The_AT basic_JJ reasoning_NN1 is_VBZ that_CST the_AT more_RGR unequal_JJ a_AT1 country_NN1 is_VBZ ,_, the_AT more_DAR voters_NN2 will_VM favour_VVI candidates_NN2 who_PNQS advocate_VV0 redistributive_JJ fiscal_JJ policies_NN2 ._. 
</s>
<s>
Since_CS these_DD2 policies_NN2 often_RR target_VV0 the_AT rich_JJ capital_NN1 income_NN1 earn-_NN1 ers_NN2 ,_, higher_JJR taxes_NN2 will_VM decrease_VVI the_AT returns_NN2 on_II investments_NN2 ,_, investments_NN2 fall_VV0 ,_, and_CC so_RR does_VDZ growth_NN1 (_( Alesina_NP1 and_CC Perotti_NP1 ,_, 1994_MC )_) ._. 
</s>
<s>
Thus_RR ,_, the_AT effects_NN2 of_IO inequality_NN1 on_II growth_NN1 are_VBR two_MC dimensional_JJ ;_; where_CS the_AT former_DA is_VBZ an_AT1 example_NN1 of_IO the_AT political_JJ and_CC the_AT latter_DA of_IO the_AT economic_JJ dimension_NN1 ._. 
</s>
<s>
However_RR ,_, developing_VVG the_AT argument_NN1 fur-_NN1 ther_NN1 ,_, including_II different_JJ types_NN2 of_IO inequality_NN1 and_CC redistributive_JJ policies_NN2 ,_, reveals_VVZ a_AT1 more_RGR complex_JJ structure_NN1 ._. 
</s>
<s>
When_CS considering_VVG the_AT functional_JJ distribution_NN1 of_IO in-_NN1 come_VV0 ,_, that_CST between_II employees_NN2 (_( wage_NN1 earners_NN2 )_) and_CC employers_NN2 (_( capital_NN1 earners_NN2 )_) ,_, one_PN1 would_VM expect_VVI that_CST when_CS the_AT share_NN1 of_IO capital_NN1 income_NN1 of_IO the_AT median_JJ voter_NN1 increases_NN2 ,_, the_AT following_JJ capital_NN1 tax_NN1 rates_NN2 (_( assumed_VVN to_TO be_VBI proportional_JJ )_) are_VBR ex-_JJ pected_JJ to_TO fall_VVI (_( Bertola_NP1 ,_, 1993_MC )_) ._. 
</s>
<s>
Conversely_RR ,_, the_AT lower_JJR the_AT income_NN1 of_IO the_AT median_JJ voter_NN1 in_II31 relation_II32 to_II33 the_AT average_JJ voter_NN1 ,_, the_AT higher_JJR the_AT taxes_NN2 are_VBR expected_VVN to_TO be_VBI (_( Alesina_NP1 and_CC Rodrik_NP1 ,_, 1994_MC )_) ._. 
</s>
<s>
Arguably_RR ,_, the_AT effects_NN2 of_IO higher_JJR capital_NN1 taxation_NN1 also_RR depend_VV0 on_II the_AT form_NN1 of_IO the_AT redistributive_JJ measures_NN2 ._. 
</s>
<s>
For_REX21 instance_REX22 ,_, if_CS the_AT tax_NN1 proceeds_NN2 are_VBR used_VVN to_TO finance_VVI public_JJ investments_NN2 ,_, some_DD of_IO the_AT lost_JJ returns_NN2 on_II private_JJ investments_NN2 can_VM be_VBI recouped_VVN if_CS the_AT public_JJ investments_NN2 are_VBR used_VVN promote_VV0 growth_NN1 ._. 
</s>
<s>
Such_DA measures_NN2 include_VV0 e.g._REX investments_NN2 in_II infrastructure_NN1 ,_, education_NN1 ,_, and_CC the_AT business_NN1 environment_NN1 ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 ,_, if_CS the_AT taxes_NN2 are_VBR used_VVN to_II sim-_JJ ply_NN1 redistribute_VV0 income_NN1 from_II the_AT rich_JJ to_II the_AT poor_JJ ,_, all_DB the_AT gains_NN2 of_IO redistribution_NN1 are_VBR accrued_VVN by_II the_AT poor_JJ and_CC ,_, consequently_RR ,_, the_AT returns_NN2 on_II investments_NN2 are_VBR lower_JJR than_CSN in_II the_AT former_DA case_NN1 ._. 
</s>
<s>
The_AT same_DA conclusions_NN2 can_VM also_RR be_VBI drawn_VVN in_II the_AT case_NN1 of_IO proportional_JJ income_NN1 taxation_NN1 ._. 
</s>
<s>
This_DD1 scenario_NN1 differs_VVZ from_II the_AT functional_JJ approach_NN1 in_II that_DD1 it_PPH1 does_VDZ not_XX distinguish_VVI between_II labour_NN1 and_CC capital_NN1 income_NN1 ,_, rather_RR it_PPH1 focuses_VVZ on_II the_AT differ-_JJ ence_NN1 in_II income_NN1 between_II (_( presumably_RR working_VVG )_) individuals_NN2 ._. 
</s>
<s>
Again_RT ,_, if_CS the_AT income_NN1 of_IO the_AT median_JJ voter_NN1 is_VBZ lower_JJR than_CSN that_DD1 of_IO the_AT average_JJ voter_NN1 ,_, one_PN1 would_VM expect_VVI the_AT voting_NN1 process_NN1 to_TO render_VVI higher_JJR taxes_NN2 (_( Persson_NP1 and_CC Tabellini_NP1 ,_, 1994_MC )_) ._. 
</s>
<s>
In_II sum_NN1 ,_, more_DAR inequality_NN1 is_VBZ expected_VVN to_TO raise_VVI taxes_NN2 through_II an_AT1 election_NN1 process_NN1 where_CS can-_JJ didates_NN2 who_PNQS favour_VV0 redistributive_JJ income_NN1 policies_NN2 are_VBR elected_VVN by_II the_AT relatively_RR poor_JJ ._. 
</s>
<s>
Higher_JJR taxes_NN2 will_VM in_II turn_VVI lower_JJR the_AT marginal_JJ return_NN1 on_II private_JJ investments_NN2 ,_, which_DDQ decreases_VVZ capital_NN1 accumulation_NN1 and_CC ,_, thus_RR ,_, growth_NN1 ._. 
</s>
<s>
However_RR ,_, the_AT above_JJ presented_JJ is_VBZ indeed_RR sensitive_JJ to_II its_APPGE underlying_JJ assumptions_NN2 ._. 
</s>
<s>
As_CSA Saint_NP1 Paul_NP1 and_CC Verdier_NP1 (_( 1996_MC )_) point_VV0 out_RP ,_, the_AT effects_NN2 could_VM even_RR be_VBI the_AT reverse_NN1 if_CS the_AT assump-_JJ tions_NN2 are_VBR changed_VVN ._. 
</s>
<s>
First_MD ,_, if_CS e.g._REX inequality_NN1 is_VBZ concentrated_VVN among_II the_AT poor_JJ ,_, an_AT1 increase_NN1 in_II inequality_NN1 may_VM not_XX necessarily_RR worsen_VVI the_AT relative_JJ position_NN1 of_IO the_AT median_JJ voter_NN1 in_II31 relation_II32 to_II33 the_AT average_JJ voter_NN1 ._. 
</s>
<s>
Second_MD ,_, different_JJ voter_NN1 groups_NN2 may_VM hold_VVI different_JJ weights_NN2 in_II the_AT political_JJ election_NN1 process_NN1 ._. 
</s>
<s>
Thus_RR ,_, taxation_NN1 could_VM be_VBI more_RGR dependent_JJ on_II the_AT political_JJ power_NN1 balance_NN1 than_CSN on_II the_AT relative_JJ wealth_NN1 of_IO the_AT median_JJ voter_NN1 ._. 
</s>
<s>
Third_MD ,_, the_AT framework_NN1 is_VBZ not_XX able_JK to_TO capture_VVI the_AT effects_NN2 of_IO progressive_JJ taxation_NN1 and_CC following_VVG redistribution_NN1 of_IO income_NN1 ._. 
</s>
<s>
Fourth_MD ,_, taxes_NN2 may_VM affect_VVI rich_JJ and_CC poor_JJ people_NN differently_RR ._. 
</s>
<s>
For_REX21 instance_REX22 ,_, because_CS rich_JJ people_NN have_VH0 more_DAR possibilities_NN2 to_TO evade_VVI taxes_NN2 ,_, the_AT marginal_JJ tax_NN1 might_VM actually_RR be_VBI higher_JJR for_IF poor_JJ people_NN ._. 
</s>
<s>
Thus_RR ,_, according_II21 to_II22 Saint_NP1 Paul_NP1 and_CC Verdier_NP1 (_( 1996_MC )_) the_AT preferred_JJ tax_NN1 rate_NN1 may_VM actually_RR drop_VVI when_RRQ inequality_NN1 increases_NN2 ._. 
</s>
<s>
With_IW this_DD1 in_II mind_NN1 ,_, the_AT question_NN1 one_MC1 should_VM ask_VVI oneself_PNX1 is_VBZ :_: what_DDQ are_VBR the_AT im-_JJ plications_NN2 of_IO these_DD2 findings_NN2 on_II public_JJ policy_NN1 ?_? 
</s>
<s>
Since_CS capital_NN1 ,_, physical_JJ and_CC human_NN1 ,_, plays_VVZ a_AT1 big_JJ part_NN1 in_II the_AT inequality/growth_NN1 debate_NN1 ,_, it_PPH1 seems_VVZ logical_JJ to_TO start_VVI here_RL ._. 
</s>
<s>
The_AT prevailing_JJ consensus_NN1 seems_VVZ to_TO be_VBI that_CST investments_NN2 in_II human_JJ capital_NN1 could_VM provide_VVI a_AT1 key_NN1 in_II promoting_VVG both_RR more_RGR equal_JJ societies_NN2 and_CC increased_JJ growth_NN1 ._. 
</s>
<s>
The_AT reasoning_NN1 starts_VVZ off_RP with_IW the_AT assumption_NN1 that_CST capital_NN1 exhibits_VVZ decreasing_JJ returns_NN2 to_TO scale_VVI ,_, implying_VVG that_CST those_DD2 who_PNQS lack_VV0 capital_NN1 (_( i.e._REX the_AT poor_JJ )_) have_VH0 higher_JJR marginal_JJ returns_NN2 than_CSN those_DD2 who_PNQS are_VBR capital_JJ intensive_JJ (_( i.e._REX the_AT rich_JJ )_) ._. 
</s>
<s>
Thus_RR ,_, the_AT gains_NN2 from_II redistributing_VVG wealth_NN1 to_TO be_VBI spent_VVN on_II productive_JJ investments_NN2 and_CC ed-_JJ ucation_NN1 among_II the_AT poor_JJ could_VM very_RG well_RR be_VBI large_JJ enough_RR to_TO outweigh_VVI the_AT losses_NN2 incurred_VVN by_II the_AT rich_JJ (_( Bnabou_NP1 ,_, 1996_MC )_) ._. 
</s>
<s>
Of_RR21 course_RR22 ,_, this_DD1 assumption_NN1 requires_VVZ that_CST the_AT redistributed_JJ wealth_NN1 is_VBZ indeed_RR used_VVN on_II productive_JJ investments_NN2 ._. 
</s>
<s>
One_PN1 has_VHZ also_RR to_TO keep_VVI in_II mind_NN1 that_CST the_AT effects_NN2 of_IO the_AT policy_NN1 heavily_RR rely_VV0 on_II the_AT population_NN1 's_GE marginal_JJ propensity_NN1 to_TO invest_VVI (_( Lee_NP1 and_CC Roemer_NP1 ,_, 1998_MC )_) ._. 
</s>
<s>
Further_RRR ,_, investments_NN2 in_II education_NN1 have_VH0 sizable_JJ feedback_NN1 effects_NN2 on_II inequality_NN1 and_CC growth_NN1 ._. 
</s>
<s>
Namely_REX ,_, in-_JJ vestments_NN2 in_II education_NN1 will_VM ,_, in_II31 addition_II32 to_II33 promote_VV0 growth_NN1 ,_, reduce_VV0 inequality_NN1 as_CSA wages_NN2 increase_VV0 (_( Saint_NP1 Paul_NP1 and_CC Verdier_NP1 ,_, 1993_MC )_) ._. 
</s>
<s>
Reduced_JJ inequality_NN1 in_II turn_NN1 raises_VVZ education_NN1 levels_NN2 and_CC ,_, thus_RR ,_, growth_NN1 (_( Perotti_NP1 ,_, 1993_MC )_) ._. 
</s>
<s>
For_IF these_DD2 reasons_NN2 Bour-_JJ guignon_NN1 (_( 2000_MC )_) suggests_VVZ that_CST rather_II21 than_II22 redistributing_VVG income_NN1 ,_, which_DDQ would_VM have_VHI negative_JJ effects_NN2 on_II capital_NN1 accumulation_NN1 ,_, redistributive_JJ policies_NN2 should_VM fo-_JJ cus_NN1 on_II distributing_VVG wealth_NN1 more_RGR evenly_RR ,_, where_CS the_AT benefits_NN2 would_VM outweigh_VVI the_AT losses_NN2 ._. 
</s>
<s>
Lastly_RR ,_, it_PPH1 seems_VVZ that_CST the_AT goal_NN1 of_IO any_DD public_JJ policy_NN1 should_VM be_VBI to_TO avoid_VVI both_RR extreme_JJ inequality_NN1 and_CC extreme_JJ equality_NN1 and_CC to_TO ensure_VVI adequate_JJ demand_NN1 by_II maintaining_VVG an_AT1 economically_RR healthy_JJ middle_JJ class_NN1 (_( Matsuyama_NP1 ,_, 2002_MC )_) ._. 
</s>
<s>
3_MC Inequality_NN1 in_II Finland_NP1 -_- a_AT1 Historical_JJ Review_NN1 The_AT increase_NN1 in_II inequality_NN1 in_II Finland_NP1 during_II the_AT last_MD couple_NN1 of_IO decades_NNT2 can_VM be_VBI largely_RR attributed_VVN to_II the_AT tax_NN1 reform_NN1 of_IO 1993_MC ,_, where_CS the_AT taxation_NN1 of_IO capital_NN1 income_NN1 was_VBDZ separated_VVN from_II labour_NN1 income_NN1 taxation_NN1 (_( Ruotsalainen_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
More_RGR precisely_RR ,_, after_CS the_AT reform_NN1 labour_NN1 income_NN1 was_VBDZ still_RR progressively_RR taxed_VVN while_CS a_AT1 fixed_JJ tax_NN1 was_VBDZ imposed_VVN on_II capital_NN1 income_NN1 ._. 
</s>
<s>
As_II the_AT fixed_JJ tax_NN1 rate_NN1 was_VBDZ lower_JJR than_CSN the_AT progressive_JJ rate_NN1 for_IF high_JJ income_NN1 earners_NN2 ,_, this_DD1 meant_VVD that_CST they_PPHS2 could_VM minimize_VVI their_APPGE tax_NN1 burden_NN1 by_II converting_VVG their_APPGE labour_NN1 income_NN1 to_II capital_NN1 income_NN1 ._. 
</s>
<s>
This_DD1 development_NN1 has_VHZ lead_VVN to_II two_MC outcomes_NN2 ._. 
</s>
<s>
First_MD ,_, the_AT functional_JJ income_NN1 distribution_NN1 has_VHZ shifted_VVN in_II favour_NN1 for_IF capital_NN1 income_NN1 earners_NN2 ._. 
</s>
<s>
Figure_VV0 1_MC1 shows_VVZ the_AT development_NN1 of_IO the_AT functional_JJ groups_NN2 '_GE shares_NN2 of_IO national_JJ income_NN1 in_II Finland_NP1 during_II the_AT time_NNT1 period_NN1 from_II 1975_MC to_II 2010_MC ._. 
</s>
<s>
Here_RL labour_NN1 's_GE share_NN1 is_VBZ measured_VVN as_II all_DB compensation_NN1 paid_VVN to_II employees_NN2 and_CC capital_NN1 's_GE share_NN1 as_II the_AT net_JJ asset_NN1 and_CC firm_JJ income_NN1 ._. 
</s>
<s>
The_AT share_NN1 of_IO taxes_NN2 on_II production_NN1 and_CC imports_NN2 is_VBZ also_RR included_VVN ._. 
</s>
<s>
During_II the_AT period_NN1 1975_MC to_II 1990_MC two_MC patterns_NN2 arise_VV0 ._. 
</s>
<s>
First_MD ,_, the_AT functional_JJ distribution_NN1 is_VBZ somewhat_RR constant_JJ during_II the_AT entire_JJ period_NN1 ;_; labour_NN1 's_GE share_NN1 fluctuates_VVZ around_RG 65_MC per_NNU21 cent_NNU22 of_IO national_JJ income_NN1 ,_, while_CS capital_NN1 's_GE share_NN1 is_VBZ fairly_RR stable_JJ around_RG 20_MC per_NNU21 cent_NNU22 ._. 
</s>
<s>
Second_MD ,_, taxes_NN2 '_GE share_NN1 of_IO national_JJ income_NN1 grew_VVD steadily_RR from_II about_RG 10_MC to_II 15_MC per_NNU21 cent_NNU22 ,_, contributing_VVG to_II decreasing_JJ income_NN1 disparities_NN2 during_II the_AT pre-1990_JJ 's_GE period_NN1 ._. 
</s>
<s>
After_II 1990_MC these_DD2 patterns_NN2 break_VV0 down_RP ,_, however_RR ._. 
</s>
<s>
First_MD ,_, during_II the_AT crisis_NN1 of_IO the_AT early_JJ 1990_MC221 's_MC222 firms_NN2 '_GE profits_NN2 dropped_VVD remarkable_JJ which_DDQ increased_JJ labour_NN1 's_GE share_NN1 ,_, reaching_VVG a_AT1 high_JJ in_II 1991_MC of_IO almost_RR 75_MC per_NNU21 cent_NNU22 ._. 
</s>
<s>
The_AT more_RGR recent_JJ crisis_NN1 that_CST started_VVD in_II 2007_MC show_VV0 a_AT1 similar_JJ pattern_NN1 ,_, though_CS the_AT effects_NN2 do_VD0 not_XX quite_RR match_VVI that_DD1 of_IO the_AT previous_JJ one_PN1 ._. 
</s>
<s>
Second_MD ,_, during_II the_AT entire_JJ post-1993_JJ period_NN1 ,_, except_II21 for_II22 the_AT crisis_NN1 years_NNT2 ,_, labour_NN1 's_GE share_NN1 decreased_VVN to_II below_RG 60_MC per_NNU21 cent_NNU22 ,_, while_CS capital_NN1 's_GE share_NN1 increased_VVN by_II a_AT1 third_MD ,_, almost_RR reaching_VVG 30_MC per_NNU21 cent_NNU22 in_II 2007_MC ._. 
</s>
<s>
Meanwhile_RR ,_, taxes_NN2 '_GE share_NN1 stopped_VVD growing_JJ and_CC has_VHZ been_VBN quite_RG stable_JJ at_II around_RG 15_MC per_NNU21 cent_NNU22 ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) Second_MD ,_, high_JJ income_NN1 earners_NN2 have_VH0 benefited_VVN most_DAT out_II21 of_II22 the_AT development_NN1 in_II functional_JJ income_NN1 distribution_NN1 ._. 
</s>
<s>
Figure_NN1 2_MC shows_VVZ the_AT evolution_NN1 of_IO the_AT percentage_NN1 shares_NN2 of_IO disposable_JJ income_NN1 according_II21 to_II22 wealth_NN1 deciles_NN2 during_II the_AT period_NN1 1976_MC to_II 2010_MC ._. 
</s>
<s>
The_AT increase_NN1 in_II taxation_NN1 during_II the_AT pre-1990_JJ period_NN1 seems_VVZ to_TO have_VHI helped_VVN close_VVI the_AT income_NN1 distribution_NN1 gap_NN1 ._. 
</s>
<s>
In_II fact_NN1 ,_, the_AT income_NN1 dispersion_NN1 was_VBDZ at_II its_APPGE lowest_JJT in_II 1987_MC when_RRQ the_AT difference_NN1 in_II shares_NN2 between_II the_AT richest_JJT and_CC the_AT poorest_JJT was_VBDZ merely_RR about_RG 13_MC percentage_NN1 points_NN2 ,_, 7_MC percentage_NN1 points_NN2 lower_JJR than_CSN it_PPH1 was_VBDZ in_II 2007_MC ._. 
</s>
<s>
More_RGR generally_RR ,_, income_NN1 shares_NN2 were_VBDR quite_RG stable_JJ up_II21 until_II22 the_AT tax_NN1 reform_NN1 in_II 1993_MC ,_, the_AT effects_NN2 of_IO which_DDQ were_VBDR immediate_JJ ;_; between_II 1992_MC and_CC 1993_MC the_AT bottom_NN1 seven_MC deciles_NN2 lost_VVN on_II average_NN1 0.15_MC percentage_NN1 points_NN2 of_IO their_APPGE respective_JJ shares_NN2 ,_, while_CS the_AT top_NN1 three_MC either_RR maintained_VVN or_CC grew_VVD their_APPGE shares_NN2 ._. 
</s>
<s>
The_AT biggest_JJT winner_NN1 of_IO the_AT reform_NN1 was_VBDZ undoubtedly_RR the_AT top_NN1 10_MC per_NNU21 cent_NNU22 who_PNQS grew_VVD their_APPGE share_NN1 with_IW almost_RR 1_MC1 percentage_NN1 point_NN1 ._. 
</s>
<s>
This_DD1 development_NN1 continued_VVD all_DB through_II the_AT 90_MC 's_GE and_CC the_AT beginning_NN1 of_IO the_AT first_MD decade_NNT1 of_IO the_AT 21th_MD century_NNT1 ._. 
</s>
<s>
In_II fact_NN1 ,_, by_II 2007_MC the_AT top_JJ income_NN1 decile_NN1 had_VHD grown_VVN its_APPGE share_NN1 by_II 5.7_MC percentage_NN1 points_NN2 ,_, the_AT second_MD highest_JJT decile_NN1 with_IW 0.4_MC percentage_NN1 points_NN2 and_CC the_AT bottom_NN1 eight_MC lost_VVD on_II average_NN1 0.76_MC percentage_NN1 points_NN2 off_II their_APPGE shares_NN2 ._. 
</s>
<s>
While_CS the_AT biggest_JJT winner_NN1 in_II this_DD1 comparison_NN1 is_VBZ beyond_II doubt_NN1 ,_, worryingly_RR enough_RR ,_, the_AT biggest_JJT losers_NN2 are_VBR found_VVN in_II the_AT bottom_NN1 three_MC income_NN1 deciles_NN2 who_PNQS lost_VVD on_II average_NN1 1.1_MC percentage_NN1 points_NN2 each_DD1 ._. 
</s>
<s>
Although_CS the_AT main_JJ cause_NN1 of_IO this_DD1 development_NN1 can_VM be_VBI attributed_VVN to_II the_AT change_NN1 in_II the_AT functional_JJ distribution_NN1 of_IO income_NN1 ,_, the_AT situation_NN1 of_IO the_AT poorest_JJT have_VH0 been_VBN aggravated_VVN further_RRR by_II the_AT real_JJ decline_NN1 in_II benefit_NN1 payments_NN2 (_( Savela_NP1 ,_, 2008_MC )_) ._. 
</s>
<s>
Figure_NN1 3_MC shows_VVZ the_AT nominal_JJ and_CC real_JJ change_NN1 between_II 1994_MC and_CC 2008_MC in_II some_DD benefit_NN1 payments_NN2 which_DDQ specifically_RR target_VV0 the_AT lower_JJR income_NN1 groups_NN2 ._. 
</s>
<s>
Although_CS real_JJ wages_NN2 increased_VVN during_II the_AT 14_MC year_NNT1 period_NN1 ,_, thus_RR mitigating_VVG the_AT negative_JJ effects_NN2 on_II the_AT middle_JJ class_NN1 ,_, all_RR21 but_RR22 pensioners_NN2 of_IO the_AT most_RGT vulnerable_JJ societal_JJ groups_NN2 NB_FO :_: The_AT first_MD two_MC entries_NN2 are_VBR for_IF the_AT years_NNT2 1976_MC and_CC 1981_MC ,_, respectively_RR ._. 
</s>
<s>
Yearly_JJ comparisons_NN2 only_RR start_VV0 from_II the_AT third_MD entry_NN1 at_II 1987_MC ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) (_( low_JJ income_NN1 earners_NN2 ,_, the_AT unemployed_JJ ,_, young_JJ families_NN2 ,_, and_CC students_NN2 )_) saw_VVD their_APPGE benefits_NN2 shrink_VVI or_CC barely_RR increase_VV0 ._. 
</s>
<s>
Thus_RR ,_, the_AT change_NN1 in_II the_AT income_NN1 distribution_NN1 in_II Finland_NP1 during_II the_AT past_JJ two_MC decades_NNT2 is_VBZ the_AT result_NN1 of_IO three_MC developments_NN2 ._. 
</s>
<s>
First_MD ,_, tax_NN1 policies_NN2 have_VH0 increasingly_RR favoured_VVN the_AT rich_JJ ._. 
</s>
<s>
Second_MD ,_, though_CS losing_VVG out_RP on_II the_AT functional_JJ distribution_NN1 of_IO income_NN1 ,_, the_AT increase_NN1 in_II real_JJ wages_NN2 have_VH0 helped_VVN mitigate_VVI the_AT losses_NN2 among_II the_AT middle_JJ class_NN1 ._. 
</s>
<s>
Third_MD ,_, the_AT decrease_NN1 in_II real_JJ benefit_NN1 payments_NN2 has_VHZ made_VVN the_AT situation_NN1 of_IO the_AT most_RGT vulnerable_JJ classes_NN2 of_IO society_NN1 worse_JJR off_JJ than_CSN anyone_PN1 else_RR ._. 
</s>
<s>
Conclusively_RR ,_, if_CS the_AT "_" Europe_NP1 2020_MC "_" is_VBZ to_TO have_VHI a_AT1 real_JJ impact_NN1 on_II poverty_NN1 in_II Finland_NP1 it_PPH1 needs_VVZ to_TO address_VVI these_DD2 fundamental_JJ issues_NN2 and_CC not_XX merely_RR try_VV0 to_TO alleviate_VVI the_AT symptoms._NNU 4_MC Inequality_NN1 and_CC "_" Europe_NP1 2020_MC "_" 
</s>
