<s>
The_AT future_NN1 of_IO video_NN1 game_NN1 retailers_NN2 in_II Finland_NP1 :_: Will_VM video_VVI game_NN1 distribution_NN1 become_VV0 digital_JJ ?_? 
</s>
<s>
Introduction_NN1 Recently_RR ,_, there_EX has_VHZ been_VBN much_DA1 discussion_NN1 concerning_II the_AT future_NN1 of_IO distribution_NN1 of_IO video_NN1 game_NN1 software_NN1 (_( henceforth_RT referred_VVN to_II as_CSA video_NN1 games_NN2 )_) ._. 
</s>
<s>
The_AT changes_NN2 can_VM concerning_II this_DD1 industry_NN1 perhaps_RR best_RRT be_VBI seen_VVN in_II the_AT drastic_JJ increases_NN2 in_II digital_JJ sales_NN in_II recent_JJ years_NNT2 ,_, and_CC decreases_VVZ ,_, or_CC very_RG small_JJ increases_NN2 in_II physical_JJ retail_JJ sales_NN of_IO video_NN1 games_NN2 (_( Makuch_NP1 ,_, 2012_MC )_) ,_, (_( Willingham_NP1 ,_, 2012_MC )_) ._. 
</s>
<s>
Historically_RR video_VV0 game_NN1 software_NN1 distribution_NN1 has_VHZ followed_VVN similar_JJ patterns_NN2 to_II the_AT distribution_NN1 of_IO music_NN1 records_NN2 and_CC motion_NN1 pictures_NN2 (_( Williams_NP1 ,_, 2002_MC )_) ._. 
</s>
<s>
There_EX are_VBR several_DA2 similarities_NN2 between_II the_AT products_NN2 ;_; notable_JJ exceptions_NN2 being_VBG the_AT higher_JJR price_NN1 and_CC digital_JJ size_NN1 of_IO video_NN1 games_NN2 ._. 
</s>
<s>
The_AT digital_JJ sale_NN1 of_IO music_NN1 is_VBZ predicted_VVN to_TO exceed_VVI physical_JJ sales_NN globally_RR in_II 2015_MC (_( Barton_NP1 ,_, 2012_MC )_) ._. 
</s>
<s>
Similarly_RR publishers_NN2 also_RR predict_VV0 that_CST digital_JJ sales_NN will_VM exceed_VVI physical_JJ sales_NN in_II video_NN1 games_NN2 as_RR21 well_RR22 (_( Prescott_NP1 ,_, 2012_MC )_) ._. 
</s>
<s>
It_PPH1 is_VBZ commonly_RR accepted_VVN that_CST ,_, at_II the_AT moment_NN1 ,_, the_AT video_NN1 game_NN1 retail_JJ industry_NN1 consists_VVZ of_IO :_: specialist_JJ retailers_NN2 ,_, super-stores_NN2 ,_, and_CC digital_JJ retailers_NN2 ._. 
</s>
<s>
Most_DAT companies_NN2 have_VH0 both_RR digital_JJ and_CC physical_JJ distribution_NN1 ,_, though_CS there_EX are_VBR some_DD that_CST focus_VV0 exclusively_RR on_II digital_JJ sales_NN ._. 
</s>
<s>
As_II a_AT1 relatively_RR new_JJ phenomenon_NN1 the_AT impact_NN1 of_IO digital_JJ sales_NN has_VHZ been_VBN noted_VVN ,_, but_CCB little_DA1 research_NN1 has_VHZ been_VBN done_VDN to_TO study_VVI what_DDQ impact_VV0 it_PPH1 will_VM have_VHI on_II the_AT market_NN1 ._. 
</s>
<s>
Much_DA1 research_NN1 has_VHZ been_VBN done_VDN concerning_II changes_NN2 in_II the_AT music_NN1 industry_NN1 due_II21 to_II22 digital_JJ sales_NN ,_, such_II21 as_II22 Bockstedt_NP1 ,_, Kaufman_NP1 and_CC Riggins_NP1 (_( 2005_MC )_) on_II artists_NN2 becoming_VVG distributors_NN2 with_IW digital_JJ content_NN1 ,_, bypassing_VVG traditional_JJ retailers_NN2 and_CC distributors_NN2 ,_, Leyshon_NP1 (_( 2001_MC )_) on_II changes_NN2 in_II the_AT music_NN1 industry_NN1 ,_, as_II31 well_II32 as_II33 Zhu_NP1 (_( 2001_MC )_) on_II distribution_NN1 of_IO digital_JJ videos_NN2 ._. 
</s>
<s>
However_RR ,_, little_RR to_II no_AT research_NN1 has_VHZ been_VBN done_VDN on_II the_AT similar_JJ process_NN1 that_CST is_VBZ currently_RR in_II progress_NN1 with_IW video_NN1 game_NN1 retailing_NN1 ._. 
</s>
<s>
The_AT question_NN1 is_VBZ whether_CSW research_NN1 done_VDN on_II the_AT music_NN1 industry_NN1 can_VM be_VBI applied_VVN to_II the_AT video_NN1 game_NN1 retail_JJ industry_NN1 ?_? 
</s>
<s>
The_AT impact_NN1 of_IO decreased_JJ retail_JJ sales_NN has_VHZ been_VBN the_AT closing_NN1 or_CC bankruptcy_NN1 of_IO specialist_NN1 retailers_NN2 in_II several_DA2 markets_NN2 ._. 
</s>
<s>
This_DD1 paper_NN1 hopes_VVZ to_TO show_VVI that_CST the_AT trend_NN1 will_VM continue_VVI and_CC digital_JJ sales_NN of_IO games_NN2 will_VM exceed_VVI physical_JJ sales_NN in_II the_AT foreseeable_JJ future_NN1 ._. 
</s>
<s>
Based_VVN on_II previous_JJ research_NN1 into_II the_AT music_NN1 industry_NN1 and_CC a_AT1 survey_NN1 ,_, this_DD1 paper_NN1 will_VM attempt_VVI to_TO predict_VVI the_AT future_JJ market_NN1 of_IO video_NN1 game_NN1 retail_JJ ._. 
</s>
<s>
However_RRQV it_PPH1 is_VBZ also_RR likely_JJ that_CST while_CS physical_JJ retail_JJ will_VM decrease_VVI in_II importance_NN1 it_PPH1 will_VM most_RGT likely_JJ not_XX entirely_RR disappear_VVI ,_, due_II21 to_II22 sales_NN of_IO used_JJ games_NN2 ._. 
</s>
<s>
The_AT remainder_NN1 of_IO this_DD1 paper_NN1 will_VM be_VBI structured_VVN as_CSA follows_VVZ :_: An_AT1 empirical_JJ part_NN1 consisting_VVG of_IO a_AT1 survey_NN1 of_IO customers_NN2 who_PNQS buy_VV0 video_NN1 games_NN2 ,_, results_NN2 of_IO the_AT survey_NN1 will_VM be_VBI applied_VVN to_II existing_JJ theory_NN1 ._. 
</s>
<s>
Based_VVN on_II the_AT empirical_JJ and_CC theory_NN1 part_NN1 discussion_NN1 concerning_II the_AT implications_NN2 of_IO the_AT results_NN2 ._. 
</s>
<s>
Finally_RR conclusions_NN2 concerning_II the_AT future_NN1 of_IO the_AT video_NN1 game_NN1 retail_JJ market_NN1 in_II Finland_NP1 ._. 
</s>
<s>
Theoretical_JJ framework_NN1 Distribution_NN1 of_IO video_NN1 game_NN1 software_NN1 and_CC the_AT development_NN1 of_IO it_PPH1 can_VM in_II many_DA2 ways_NN2 be_VBI compared_VVN to_II the_AT music_NN1 industry_NN1 as_II31 well_II32 as_II33 the_AT motion_NN1 picture_NN1 industry_NN1 ._. 
</s>
<s>
Similar_JJ developments_NN2 are_VBR evident_JJ in_CS21 that_CS22 both_DB2 are_VBR moving_VVG toward_II a_AT1 digital_JJ distribution_NN1 model_NN1 of_IO software_NN1 ._. 
</s>
<s>
The_AT music_NN1 industry_NN1 ,_, with_IW smaller_JJR file_NN1 sizes_NN2 and_CC widespread_JJ use_NN1 of_IO Mp3_FO players_NN2 ,_, such_II21 as_II22 the_AT IPod_NP1 ;_; with_IW its_APPGE own_DA online_JJ store_NN1 ;_; is_VBZ far_RR ahead_RL in_II this_DD1 development_NN1 and_CC should_VM therefore_RR provide_VVI a_AT1 suitable_JJ model_NN1 to_TO predict_VVI the_AT development_NN1 of_IO video_NN1 game_NN1 distribution_NN1 ._. 
</s>
<s>
Before_CS the_AT early_JJ 2000s_MC2 the_AT average_JJ speed_NN1 of_IO internet_NN1 connections_NN2 was_VBDZ too_RG low_JJ to_TO allow_VVI for_IF distribution_NN1 of_IO music_NN1 over_II the_AT internet_NN1 (_( Lam_NP1 &;_NULL Tan_NN1 ,_, 2001_MC )_) ._. 
</s>
<s>
Much_RR the_AT same_DA could_VM be_VBI said_VVN of_IO video_NN1 game_NN1 distribution_NN1 ,_, perhaps_RR much_RR more_RGR so_RR as_II a_AT1 typical_JJ game_NN1 can_VM range_VVI from_II a_AT1 few_DA2 megabytes_NNU2 (_( MB_NNU )_) to_II over_RG ten_MC gigabytes_NN2 (_( GB_NP1 )_) for_IF larger_JJR games_NN2 ._. 
</s>
<s>
Hence_RR the_AT emergence_NN1 of_IO digital_JJ distribution_NN1 of_IO video_NN1 games_NN2 has_VHZ been_VBN far_RR slower_JJR for_IF video_NN1 games_NN2 than_CSN for_IF music_NN1 ._. 
</s>
<s>
Lam_NP1 and_CC Tan_NN1 (_( 2001_MC )_) predict_VV0 that_CST better_JJR networking_NN1 technology_NN1 will_VM lead_VVI to_II the_AT rise_NN1 of_IO the_AT Internet_NN1 as_II an_AT1 infotainment_NN1 hub_NN1 ,_, which_DDQ will_VM be_VBI the_AT main_JJ source_NN1 of_IO information_NN1 and_CC entertainment_NN1 ._. 
</s>
<s>
In_II Finland_NP1 this_DD1 is_VBZ well_RR exemplified_VVN in_II households_NN2 with_IW broadband_JJ where_CS the_AT service_NN1 provider_NN1 can_VM offer_VVI a_AT1 TV_NN1 and_CC motion_NN1 picture_NN1 service_NN1 ,_, for_REX21 example_REX22 Sonera_NP1 Viihdepaketti_NP1 (_( Sonera_NP1 ,_, 2012_MC )_) ,_, whereby_RRQ the_AT customer_NN1 can_VM rent_VVI movies_NN2 digitally_RR and_CC in_II fact_NN1 gets_VVZ their_APPGE TV_NN1 channels_NN2 through_II high-speed_JJ internet_NN1 ,_, as_II31 opposed_II32 to_II33 traditional_JJ broadcasting_NN1 methods_NN2 ._. 
</s>
<s>
In_II the_AT USA_NP1 services_NN2 utilizing_VVG high-speed_JJ internet_NN1 for_IF video_NN1 game_NN1 distribution_NN1 in_II the_AT form_NN1 of_IO cloud_NN1 gaming_NN1 ,_, where_CS the_AT games_NN2 are_VBR streamed_VVN directly_RR to_II the_AT end_NN1 user_NN1 from_II the_AT provider_NN1 ,_, are_VBR common_JJ with_IW companies_NN2 such_II21 as_II22 OnLive_NP1 and_CC Gaikai_NN1 providing_VVG cloud_NN1 gaming_NN1 services_NN2 ._. 
</s>
<s>
Lam_NP1 &;_NULL Tan_NN1 (_( 2001_MC )_) identify_VV0 a_AT1 number_NN1 of_IO steps_NN2 that_CST traditionally_RR were_VBDR part_NN1 of_IO music_NN1 distribution_NN1 ._. 
</s>
<s>
Those_DD2 are_VBR :_: 1_MC1 ._. 
</s>
<s>
The_AT artist_NN1 signs_VVZ a_AT1 contract_NN1 with_IW the_AT record_NN1 label_NN1 to_II leverage_NN1 on_II the_AT core_NN1 competency_NN1 of_IO the_AT latter_DA ,_, such_II21 as_II22 marketing_NN1 and_CC distribution_NN1 2_MC ._. 
</s>
<s>
The_AT artist_NN1 records_VVZ the_AT album_NN1 and_CC the_AT record_NN1 label_NN1 produces_VVZ the_AT album_NN1 in_II some_DD media_NN such_II21 as_II22 CDs_NN2 ._. 
</s>
<s>
3_MC ._. 
</s>
<s>
The_AT retailers_NN2 buy_VV0 the_AT CDs_NN2 and_CC other_JJ media_NN from_II the_AT record_NN1 label_NN1 ._. 
</s>
<s>
4_MC ._. 
</s>
<s>
The_AT consumers_NN2 buy_VV0 the_AT CDs_NN2 and_CC other_JJ media_NN from_II the_AT retailers_NN2 ._. 
</s>
<s>
(_( Lam_NP1 &;_NULL Tan_NN1 ,_, 2001_MC )_) The_AT video_NN1 game_NN1 industry_NN1 is_VBZ very_RG similar_JJ in_II that_DD1 singular_JJ video_NN1 games_NN2 are_VBR usually_RR developed_VVN by_II a_AT1 certain_JJ video_NN1 game_NN1 developer_NN1 that_CST specializes_VVZ in_II the_AT creation_NN1 of_IO games_NN2 ._. 
</s>
<s>
Acclaimed_JJ developers_NN2 include_VV0 Blizzard_NN1 ,_, Bioware_NP1 ,_, Epic_JJ Games_NN2 ,_, etc_RA ._. 
</s>
<s>
Generally_RR the_AT developer_NN1 is_VBZ only_RR responsible_JJ for_IF the_AT game_NN1 software_NN1 itself_PPX1 ._. 
</s>
<s>
Publishers_NN2 perform_VV0 much_RR the_AT same_DA functions_NN2 as_CSA record_NN1 labels_NN2 ;_; marketing_NN1 and_CC distribution_NN1 ,_, as_II31 well_II32 as_II33 making_VVG the_AT software_NN1 into_II a_AT1 physical_JJ product_NN1 ,_, such_II21 as_II22 game_NN1 boxes_NN2 with_IW DVDs_NP1 ._. 
</s>
<s>
Publishers_NN2 often_RR also_RR finance_VV0 the_AT development_NN1 of_IO the_AT video_NN1 games_NN2 they_PPHS2 distribute_VV0 ,_, oftentimes_RR owning_VVG the_AT developer_NN1 ._. 
</s>
<s>
The_AT publishers_NN2 sell_VV0 to_II retailers_NN2 ,_, who_PNQS sell_VV0 to_II customers_NN2 ._. 
</s>
<s>
Well_RR known_VVN publishers_NN2 include_VV0 Sony_NP1 ,_, Nintendo_NP1 ,_, Microsoft_NP1 and_CC Electronic_JJ Arts_NN2 ._. 
</s>
<s>
Electronic_JJ markets_NN2 also_RR have_VH0 the_AT potential_JJ to_TO reconfigure_VVI fundamentally_RR the_AT competitive_JJ bases_NN2 and_CC contestability_NN1 of_IO markets_NN2 ._. 
</s>
<s>
Thus_RR not_XX only_RR do_VD0 electronic_JJ markets_NN2 have_VH0 the_AT potential_JJ to_TO break_VVI down_RP established_JJ market_NN1 hierarchies_NN2 through_II disintermediation_NN1 ,_, but_CCB established_VVD firms_NN2 may_VM well_RR be_VBI disadvantaged_JJ as_CSA markets_NN2 are_VBR reintermediated_VVN through_II electronic_JJ channels_NN2 ._. 
</s>
<s>
Established_JJ firms_NN2 tend_VV0 to_TO have_VHI significant_JJ sunk_JJ costs_NN2 within_II physical_JJ infrastructures_NN2 ,_, and_CC it_PPH1 is_VBZ for_IF this_DD1 reason_NN1 that_CST electronic_JJ markets_NN2 offer_VV0 significant_JJ competitive_JJ opportunities_NN2 for_IF new_JJ or_CC marginal_JJ competitors_NN2 within_II existing_JJ industries_NN2 (_( Leyshon_NP1 ,_, 2001_MC )_) ._. 
</s>
<s>
Though_CS many_DA2 traditional_JJ video_NN1 game_NN1 retailers_NN2 have_VH0 made_VVN investments_NN2 into_II digital_JJ retail_JJ they_PPHS2 have_VH0 much_RR smaller_JJR market_NN1 shares_NN2 than_CSN in_II traditional_JJ retail_JJ ._. 
</s>
<s>
A_AT1 matter_NN1 that_CST is_VBZ further_RRR complicated_VVN by_II the_AT fact_NN1 that_CST for_IF certain_JJ platforms_NN2 they_PPHS2 are_VBR essentially_RR locked_VVN out_RP from_II distribution_NN1 ._. 
</s>
<s>
For_REX21 example_REX22 the_AT various_JJ consoles_NN2 have_VH0 their_APPGE own_DA exclusive_JJ digital_JJ stores_NN2 ,_, such_II21 as_II22 Xbox_NP1 Live_JJ and_CC Playstation_NN1 Network_NN1 ._. 
</s>
<s>
The_AT same_DA applies_VVZ to_II the_AT ever_RR growing_JJ market_NN1 of_IO smart_JJ phone_NN1 games_NN2 where_RRQ the_AT most_RGT popular_JJ operating_NN1 systems_NN2 ,_, Apples_NN2 iOS_NN2 and_CC Googles_NP1 Android_NN1 have_VH0 their_APPGE own_DA App_NN1 stores_NN2 from_II which_DDQ games_NN2 can_VM be_VBI bought_VVN ._. 
</s>
<s>
While_CS it_PPH1 is_VBZ difficult_JJ to_TO estimate_VVI how_RRQ the_AT digital_JJ market_NN1 is_VBZ divided_VVN ,_, as_CSA the_AT major_JJ retailers_NN2 do_VD0 not_XX share_VVI such_DA information_NN1 ,_, certain_JJ estimates_NN2 can_VM be_VBI made_VVN ._. 
</s>
<s>
Concerning_II the_AT PC_NN1 market_NN1 ,_, in_II 2009_MC Impulse_NN1 ,_, one_MC1 of_IO the_AT competitors_NN2 of_IO the_AT market_NN1 leader_NN1 Steam_NN1 ,_, estimated_VVD the_AT market_NN1 share_NN1 of_IO Steam_NN1 to_TO be_VBI 70_MC %_NNU of_IO PC_NN1 digital_JJ video_NN1 game_NN1 distribution_NN1 (_( Graft_VV0 ,_, 2009_MC )_) ._. 
</s>
<s>
Though_CS it_PPH1 is_VBZ important_JJ to_TO note_VVI that_DD1 Steam_NN1 is_VBZ exclusively_RR on_II the_AT PC_NN1 and_CC consoles_VVZ generally_RR have_VH0 their_APPGE own_DA digital_JJ distribution_NN1 operated_VVN by_II the_AT manufacturer_NN1 of_IO the_AT console_NN1 ,_, such_II21 as_II22 Playstation_NN1 Network_NN1 for_IF Playstation_NN1 3_MC ,_, and_CC Xbox_NP1 Live_VV0 for_IF Xbox_NP1 360_MC ._. 
</s>
<s>
Thus_RR complicating_VVG digital_JJ distribution_NN1 on_II consoles_NN2 since_CS distribution_NN1 requires_VVZ approval_NN1 from_II the_AT manufacturer_NN1 ._. 
</s>
<s>
An_AT1 important_JJ edge_NN1 that_CST can_VM be_VBI attributed_VVN to_II physical_JJ stores_NN2 ,_, over_II digital_JJ retail_JJ ,_, is_VBZ the_AT sociopsychological_JJ aspect_NN1 of_IO physical_JJ stores_NN2 (_( Lam_NP1 &;_NULL Tan_NN1 ,_, 2001_MC )_) ._. 
</s>
<s>
Lam_NP1 and_CC Tan_NN1 (_( 2001_MC )_) contend_VV0 that_CST stores_NN2 are_VBR social_JJ gathering_NN1 places_NN2 for_IF listeners_NN2 of_IO music_NN1 ,_, which_DDQ the_AT internet_NN1 can_VM not_XX provide_VVI ._. 
</s>
<s>
Stores_NN2 also_RR provide_VV0 various_JJ music-related_JJ commodities_NN2 ._. 
</s>
<s>
They_PPHS2 suggest_VV0 consumers_NN2 can_VM be_VBI enticed_VVN to_TO return_VVI to_II stores_NN2 by_II31 means_II32 of_II33 engaging_VVG and_CC meaningful_JJ experiences_NN2 ._. 
</s>
<s>
When_CS it_PPH1 comes_VVZ to_TO video_VVI game_NN1 retailers_NN2 ,_, specialist_NN1 retailers_NN2 are_VBR the_AT most_RGT apt_JJ comparison_NN1 ._. 
</s>
<s>
In_II Finland_NP1 the_AT only_JJ truly_RR large_JJ scale_NN1 specialist_NN1 retailer_NN1 of_IO video_NN1 games_NN2 is_VBZ Gamestop_NP1 ._. 
</s>
<s>
Most_DAT other_JJ retailers_NN2 only_RR have_VH0 a_AT1 click-and-mortar_JJ presence_NN1 or_CC video_NN1 games_NN2 are_VBR only_JJ part_NN1 of_IO their_APPGE inventory_NN1 ,_, such_II21 as_II22 Verkkokauppa.com_NP1 ,_, CDON.fi_NP1 ,_, etc_RA ._. 
</s>
<s>
However_RGQV at_RR21 least_RR22 internationally_RR Gamestop_NP1 has_VHZ received_VVN a_AT1 lot_NN1 of_IO critique_NN1 from_II casual_JJ customers_NN2 ,_, who_PNQS sometimes_RT find_VV0 that_CST they_PPHS2 are_VBR treated_VVN badly_RR for_IF perceived_JJ ignorance_NN1 (_( Customer_NN1 Service_NN1 Scoreboard_NN1 ,_, 2012_MC )_) ._. 
</s>
<s>
Another_DD1 advantage_NN1 online_JJ distribution_NN1 has_VHZ over_II traditional_JJ retail_JJ is_VBZ the_AT minimal_JJ cost_NN1 and_CC online_JJ distributors_NN2 can_VM therefore_RR use_VVI competitive_JJ pricing_NN1 strategies_NN2 (_( Lam_NP1 &;_NULL Tan_NN1 ,_, 2001_MC )_) ._. 
</s>
<s>
While_CS physical_JJ stores_NN2 can_VM serve_VVI an_AT1 important_JJ role_NN1 as_CSA platforms_NN2 for_IF marketing_NN1 ,_, an_AT1 online_JJ presence_NN1 offers_NN2 much_RR greater_JJR control_NN1 over_II the_AT expenditure_NN1 and_CC tracking_NN1 of_IO marketing_NN1 ._. 
</s>
<s>
Digital_JJ retailers_NN2 also_RR work_VV0 quite_RG well_RR as_CSA marketing_NN1 platforms_NN2 ._. 
</s>
<s>
Digital_JJ retailers_NN2 may_VM easily_RR gather_VVI extensive_JJ databases_NN2 of_IO their_APPGE customers_NN2 buying_VVG preferences_NN2 as_II31 well_II32 as_II33 behavior_NN1 ,_, allowing_VVG focused_JJ marketing_NN1 and_CC special_JJ offers_NN2 (_( Lam_NP1 &;_NULL Tan_NN1 ,_, 2001_MC )_) ._. 
</s>
<s>
Data_NN Collection_NN1 (_( Survey_NN1 still_RR incomplete_JJ due_JJ to_TO lack_VVI of_IO webropol_NN1 access_NN1 ,_, therefore_RR no_AT actual_JJ data_NN represented_VVD yet_RR ._. 
</s>
<s>
See_VV0 appendix_NN1 1_MC1 for_IF questions_NN2 potentially_RR used_VVN in_II the_AT survey_NN1 )_) Data_NN collection_NN1 will_VM be_VBI an_AT1 online_JJ survey_NN1 ,_, done_VDN via_II webropol_NN1 ,_, due_II21 to_II22 time_NNT1 efficiency_NN1 as_II31 well_II32 as_II33 that_CST those_DD2 who_PNQS already_RR use_VV0 the_AT internet_NN1 will_VM be_VBI more_RGR likely_JJ to_TO represent_VVI those_DD2 who_PNQS are_VBR more_RGR likely_JJ to_TO use_VVI digital_JJ retailers_NN2 ._. 
</s>
<s>
There_EX will_VM be_VBI selection_NN1 bias_NN1 as_CSA respondents_NN2 will_VM be_VBI chosen_VVN on_II a_AT1 self-selection_JJ basis_NN1 ._. 
</s>
<s>
I.e._REX Those_DD2 who_PNQS respond_VV0 ._. 
</s>
<s>
Naturally_RR this_DD1 will_VM lead_VVI to_II the_AT target_NN1 population_NN1 being_VBG mainly_RR students_NN2 with_IW an_AT1 age_NN1 range_NN1 of_IO 18-30_MCMC ,_, however_RR as_CSA this_DD1 represents_VVZ a_AT1 significant_JJ amount_NN1 of_IO the_AT spending_NN1 power_NN1 it_PPH1 can_VM be_VBI of_IO use_NN1 ._. 
</s>
<s>
The_AT average_JJ game_NN1 player_NN1 is_VBZ 30_MC years_NNT2 of_IO age_NN1 in_II the_AT USA_NP1 (_( Entertainment_NN1 Software_NN1 Association_NN1 ,_, 2012_MC )_) ._. 
</s>
<s>
Discussion_NN1 Like_II the_AT newspaper_NN1 ,_, the_AT hardcover_NN1 book_NN1 ,_, and_CC the_AT compact_JJ disk_NN1 ,_, the_AT expensive_JJ disc-based_JJ method_NN1 of_IO video_NN1 game_NN1 distribution_NN1 is_VBZ on_II its_APPGE way_NN1 out_RP ,_, a_AT1 process_NN1 that_CST 's_VBZ only_RR accelerating_VVG as_RG more_DAR developers_NN2 and_CC publishers_NN2 test_VV0 out_RP alternative_JJ pricing_NN1 models_NN2 both_RR on_II PC_NN1 and_CC console_VV0 platforms._NNU (_( Onyett_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
Many_DA2 prefer_VV0 the_AT convenience_NN1 of_IO digital_JJ downloads_NN2 ,_, not_XX having_VHG to_TO leave_VVI their_APPGE home_NN1 to_TO go_VVI to_II a_AT1 specialist_NN1 retailer_NN1 ._. 
</s>
<s>
For_REX21 example_REX22 among_II hardcore_NN1 gamers_NN2 launch_NN1 days_NNT2 of_IO popular_JJ products_NN2 usually_RR lead_VV0 to_II cues_NN2 outside_II retailers_NN2 ._. 
</s>
<s>
This_DD1 is_VBZ especially_RR the_AT case_NN1 with_IW midnight_NNT1 or_CC early_JJ launches_NN2 ,_, where_CS retailers_NN2 will_VM open_VVI their_APPGE stores_NN2 or_CC keep_VV0 them_PPHO2 open_JJ for_IF longer_JJR for_IF the_AT launch_NN1 of_IO a_AT1 popular_JJ game_NN1 ._. 
</s>
<s>
This_DD1 often_RR leads_VVZ to_TO long_JJ queues_NN2 to_TO even_RR get_VVI the_AT game_NN1 or_CC in_II the_AT worst_JJT case_NN1 the_AT product_NN1 selling_VVG out_RP thereby_RR leaving_VVG customers_NN2 without_IW a_AT1 copy_NN1 ._. 
</s>
<s>
For_REX21 example_REX22 the_AT launch_NN1 the_AT Elder_JJR Scroll_NN1 V_ZZ1 :_: Skyrim_NP1 caused_VVD massive_JJ queues_NN2 to_TO form_VVI in_II Helsinki_NP1 (_( Bethesda_NP1 Softworks_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
As_CSA mentioned_VVN earlier_JJR developers_NN2 have_VH0 traditionally_RR been_VBN forced_VVN to_TO rely_VVI upon_II publishers_NN2 for_IF marketing_NN1 and_CC distribution_NN1 as_II31 well_II32 as_II33 financing_VVG for_IF projects_NN2 ._. 
</s>
<s>
However_RGQV digital_JJ distribution_NN1 may_VM cause_VVI this_DD1 whole_JJ dynamic_JJ to_TO change_VVI ,_, as_CSA it_PPH1 gives_VVZ the_AT possibility_NN1 for_IF developers_NN2 to_TO gather_VVI financing_NN1 ,_, market_NN1 and_CC distribute_VVI on_II their_APPGE own_DA ._. 
</s>
<s>
For_REX21 example_REX22 the_AT crowd_NN1 funding_NN1 website_NN1 Kickstarter_NN1 ,_, has_VHZ become_VVN a_AT1 source_NN1 of_IO financing_VVG for_IF many_DA2 developers_NN2 ,_, allowing_VVG them_PPHO2 to_TO gather_VVI financing_NN1 and_CC market_VVI their_APPGE projects_NN2 without_IW publishers_NN2 ._. 
</s>
<s>
Video_NN1 games_NN2 such_II21 as_II22 Minecraft_NP1 have_VH0 been_VBN successful_JJ in_II distribution_NN1 on_II their_APPGE own_DA through_II the_AT developers_NN2 website_NN1 ,_, being_VBG distributed_VVN exclusively_RR digitally_RR ,_, as_II31 well_II32 as_II33 being_VBG marketed_VVN mainly_RR through_II word-of-mouth_NN1 ._. 
</s>
<s>
There_EX is_VBZ an_AT1 opportunity_NN1 for_IF new_JJ players_NN2 to_TO enter_VVI the_AT market_NN1 due_II21 to_II22 digital_JJ distribution_NN1 ._. 
</s>
<s>
Even_RR with_IW the_AT possibility_NN1 for_IF this_DD1 created_VVN by_II electronic_JJ channels_NN2 as_CSA Leyshon_NP1 (_( 2001_MC )_) points_VVZ out_RP ,_, will_VM most_RGT likely_JJ not_XX happen_VVI on_II a_AT1 large_JJ scale_NN1 ._. 
</s>
<s>
This_DD1 would_VM be_VBI due_II21 to_II22 several_DA2 factors_NN2 ._. 
</s>
<s>
As_CSA mentioned_VVN earlier_RRR consoles_VVZ and_CC handhelds_NN2 are_VBR largely_RR locked_VVN to_II the_AT manufacturers_NN2 distribution_NN1 platforms_NN2 ,_, and_CC PC_NN1 is_VBZ mostly_RR dominated_VVN by_II Steam_NN1 ._. 
</s>
<s>
The_AT possibility_NN1 of_IO multiple_JJ distributors_NN2 does_VDZ exist_VVI ,_, but_CCB is_VBZ unlikely_JJ ._. 
</s>
<s>
The_AT switching_JJ cost_NN1 and_CC convenience_NN1 of_IO using_VVG one_MC1 platform_NN1 may_VM be_VBI a_AT1 major_JJ factor_NN1 ._. 
</s>
<s>
While_CS many_DA2 developers_NN2 may_VM use_VVI several_DA2 distributors_NN2 for_IF digital_JJ products_NN2 ,_, consumers_NN2 tend_VV0 to_TO prefer_VVI one_MC1 platform_NN1 ._. 
</s>
<s>
One_MC1 advantage_NN1 of_IO physical_JJ retailers_NN2 is_VBZ the_AT used_JJ games_NN2 market_VV0 and_CC older_JJR games_NN2 ._. 
</s>
<s>
Many_DA2 older_JJR games_NN2 do_VD0 not_XX exist_VVI as_RG digital_JJ copies_NN2 and_CC never_RR will_VM ._. 
</s>
<s>
However_RR as_CSA Onyett_NP1 (_( 2011_MC )_) points_VVZ out_RP in_II the_AT future_NN1 it_PPH1 is_VBZ in_II the_AT best_JJT interest_NN1 of_IO developers_NN2 and_CC publishers_NN2 to_TO be_VBI digital_JJ only_RR ,_, since_CS used_JJ games_NN2 that_CST change_VV0 hands_NN2 through_II a_AT1 third_MD party_NN1 ,_, such_II21 as_II22 Gamestop_NP1 ,_, generally_RR do_VD0 not_XX generate_VVI any_DD income_NN1 for_IF the_AT publisher_NN1 or_CC developer_NN1 ._. 
</s>
<s>
A_AT1 certain_JJ segment_NN1 of_IO the_AT market_NN1 will_VM still_RR of_RR21 course_RR22 want_VVI physical_JJ copies_NN2 ,_, but_CCB major_JJ publishers_NN2 are_VBR moving_VVG toward_II digital_JJ only_RR ,_, such_II21 as_II22 Electronic_JJ arts_NN2 ,_, with_IW its_APPGE Origin_NN1 digital_JJ service_NN1 and_CC developers_NN2 ,_, like_II Blizzard_NN1 ,_, with_IW attempts_NN2 to_TO create_VVI a_AT1 Blizzard-only_JJ social_JJ network_NN1 (_( Onyett_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
Old_JJ games_NN2 are_VBR also_RR being_VBG converted_VVN for_IF newer_JJR systems_NN2 and_CC released_VVN in_II digital_JJ format_NN1 exclusively_RR ._. 
</s>
<s>
For_REX21 example_REX22 many_DA2 older_JJR games_NN2 released_VVN for_IF the_AT Nintendo_NP1 Entertainment_NN1 System_NN1 ,_, console_VV0 from_II the_AT 1980s_MC2 ,_, are_VBR re-released_VVN as_CSA digital-only_JJ products_NN2 on_II current_JJ Nintendo_NP1 consoles_VVZ ._. 
</s>
<s>
So_RG far_RR it_PPH1 is_VBZ mostly_RR the_AT PC_NN1 market_VV0 that_CST has_VHZ embraced_VVN digital_JJ distribution_NN1 ._. 
</s>
<s>
This_DD1 kind_NN1 of_IO flexibility_NN1 is_VBZ possible_JJ in_II the_AT PC_NN1 market_NN1 because_CS there_EX 's_VBZ no_AT official_JJ oversight_NN1 ._. 
</s>
<s>
There_EX 's_VBZ no_AT Nintendo_NP1 ,_, Microsoft_NP1 or_CC Sony_NP1 to_TO give_VVI the_AT ultimate_JJ 'yes_NN2 '_GE or_CC 'no'_VV0 as_II21 to_II22 whether_CSW something_PN1 's_VBZ viable._NNU (_( Onyett_NP1 ,_, 2011_MC )_) The_AT Steam_NN1 platform_NN1 ,_, for_IF the_AT PC_NN1 ,_, is_VBZ a_AT1 great_JJ example_NN1 of_IO the_AT convenience_NN1 and_CC aggressive_JJ pricing_NN1 available_JJ for_IF digital_JJ retailers_NN2 ._. 
</s>
<s>
Steam_NN1 has_VHZ sales_NN every_AT1 weekend_NNT1 and_CC daily_JJ sales_NN that_CST last_MD 24_MC hours_NNT2 ,_, where_CS a_AT1 product_NN1 may_VM be_VBI discounted_VVN with_IW up_RG21 to_RG22 75_MC %_NNU Such_DA discounts_NN2 are_VBR only_RR possible_JJ because_CS the_AT product_NN1 is_VBZ digital_JJ and_CC the_AT cost_NN1 of_IO producing_VVG an_AT1 additionally_RR product_NN1 is_VBZ virtually_RR zero_MC ._. 
</s>
<s>
This_DD1 encourages_VVZ buyers_NN2 to_TO check_VVI the_AT service_NN1 on_II a_AT1 daily_JJ basis_NN1 ._. 
</s>
<s>
From_II a_AT1 developer_NN1 perspective_NN1 there_EX are_VBR many_DA2 advantages_NN2 in_II digital_JJ distribution_NN1 ._. 
</s>
<s>
1_MC1 ._. 
</s>
<s>
Bypassing_VVG publishers_NN2 ,_, mean_VV0 higher_JJR profits_NN2 2_MC ._. 
</s>
<s>
Lower_JJR costs_NN2 3_MC ._. 
</s>
<s>
Reduced_VVN second_MD hand_NN1 sales_NN 4_MC ._. 
</s>
<s>
Products_NN2 may_VM generate_VVI sales_NN long_RR after_II traditional_JJ life_NN1 cycle_NN1 is_VBZ over_II Many_DA2 smaller_JJR ,_, so_JJ21 called_JJ22 indie_NN1 developers_NN2 now_RT choose_VV0 to_TO publish_VVI exclusively_RR digitally_RR ,_, with_IW physical_JJ copies_NN2 being_VBG sold_VVN as_II a_AT1 premium_JJ product_NN1 ,_, if_CS sold_VVN at_RR21 all_RR22 ._. 
</s>
<s>
Especially_RR Smartphones_NN2 are_VBR well_RR suited_VVN to_II digital_JJ sales_NN ,_, given_CS21 that_CS22 most_DAT smartphones_NN2 owners_NN2 have_VH0 online_JJ capability_NN1 for_IF their_APPGE phones_NN2 ,_, and_CC will_VM likely_RR represent_VVI a_AT1 significant_JJ amount_NN1 of_IO digital_JJ sales_NN in_II the_AT future_NN1 ._. 
</s>
<s>
The_AT rise_NN1 of_IO so_JJ21 called_JJ22 free-to-play_JJ games_NN2 may_VM also_RR spell_VVI the_AT death_NN1 ,_, or_CC at_RR21 least_RR22 decline_VV0 ,_, of_IO traditional_JJ disc-based_JJ games_NN2 ,_, and_CC with_IW them_PPHO2 physical_JJ retail_JJ ._. 
</s>
<s>
Free-to-play_NN1 being_VBG a_AT1 business_NN1 model_NN1 where_CS the_AT game_NN1 itself_PPX1 is_VBZ given_VVN away_RL for_IF free_JJ and_CC revenue_NN1 is_VBZ generated_VVN either_RR through_RP in_II game_NN1 transactions_NN2 or_CC advertisements_NN2 ._. 
</s>
<s>
At_RR21 least_RR22 in_II mobile_NN1 gaming_VVG the_AT trend_NN1 is_VBZ towards_II free_JJ games_NN2 ,_, with_IW 65_MC %_NNU of_IO the_AT top_NN1 100_MC grossing_JJ games_NN2 in_II June_NPM1 2011_MC the_AT revenue_NN1 generated_VVN from_II free_JJ games_NN2 on_II the_AT Apple_NN1 IPhone_NN1 ,_, compared_VVN to_II 39%_NNU in_II January_NPM1 2011_MC (_( see_VV0 figure_NN1 2_MC )_) ._. 
</s>
<s>
Since_CS the_AT game_NN1 is_VBZ given_VVN away_RL for_IF free_JJ a_AT1 cost_NN1 of_IO a_AT1 digital_JJ product_NN1 is_VBZ generally_RR out_II21 of_II22 the_AT question_NN1 ._. 
</s>
<s>
If_CS the_AT future_NN1 of_IO gaming_NN1 is_VBZ in_II free_JJ games_NN2 the_AT future_NN1 of_IO gaming_NN1 will_VM also_RR mostly_RR be_VBI digital_JJ ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) &lsqb;_( Figure_NN1 &rsqb;_) Cloud_NN1 gaming_NN1 is_VBZ a_AT1 possibility_NN1 that_CST would_VM take_VVI the_AT video_NN1 gaming_NN1 experience_NN1 completely_RR digital_JJ ,_, as_CSA users_NN2 would_VM not_XX even_RR need_VVI a_AT1 console_NN1 or_CC any_DD other_JJ form_NN1 of_IO gaming_VVG device_NN1 ,_, but_CCB rather_RR everything_PN1 would_VM be_VBI handled_VVN digitally_RR over_II the_AT internet_NN1 ._. 
</s>
<s>
This_DD1 would_VM effectively_RR kill_VVI video_NN1 games_NN2 as_II a_AT1 physical_JJ product_NN1 as_CSA there_EX would_VM be_VBI no_AT use_NN1 for_IF it_PPH1 ._. 
</s>
<s>
Conclusions_NN2 The_AT trend_NN1 in_II video_NN1 game_NN1 retail_NN1 is_VBZ moving_VVG towards_II digital_JJ distribution_NN1 at_II the_AT cost_NN1 of_IO traditional_JJ retail_JJ ._. 
</s>
<s>
This_DD1 is_VBZ of_IO benefit_NN1 for_IF both_DB2 the_AT customers_NN2 and_CC developers_NN2 ,_, but_CCB will_VM most_RGT likely_RR spell_VVI the_AT doom_NN1 for_IF video_NN1 game_NN1 retail_JJ as_CSA it_PPH1 is_VBZ today_RT ._. 
</s>
<s>
This_DD1 may_VM be_VBI a_AT1 slow_JJ process_NN1 as_CSA there_EX are_VBR still_RR vast_JJ markets_NN2 without_IW access_NN1 to_II high_JJ speed_NN1 internet_NN1 ,_, which_DDQ in_II large_JJ parts_NN2 is_VBZ a_AT1 prerequisite_NN1 for_IF this_DD1 change_NN1 ._. 
</s>
<s>
There_EX will_VM also_RR always_RR be_VBI those_DD2 who_PNQS want_VV0 a_AT1 physical_JJ product_NN1 ._. 
</s>
<s>
Those_DD2 are_VBR the_AT same_DA people_NN who_PNQS want_VV0 to_TO hold_VVI their_APPGE morning_NNT1 newspaper_NN1 in_II their_APPGE hand_NN1 as_II31 opposed_II32 to_II33 reading_VVG the_AT same_DA news_NN1 from_II a_AT1 screen_NN1 ._. 
</s>
<s>
However_RRQV they_PPHS2 will_VM have_VHI to_TO pay_VVI a_AT1 premium_NN1 for_IF this_DD1 luxury_NN1 in_II the_AT future_NN1 ,_, and_CC they_PPHS2 will_VM likely_RR not_XX be_VBI picking_VVG it_PPH1 up_RP from_II a_AT1 store_NN1 ,_, but_CCB rather_RR have_VH0 it_PPH1 delivered_VVN to_II them_PPHO2 ._. 
</s>
<s>
What_DDQ will_VM remain_VVI of_IO the_AT physical_JJ products_NN2 for_IF video_NN1 games_NN2 will_VM in_II the_AT future_JJ most_RGT likely_RR take_VV0 the_AT form_NN1 of_IO collectors_NN2 editions_NN2 and_CC other_JJ such_DA premium_JJ packages_NN2 ,_, and_CC be_VBI significantly_RR more_RGR expensive_JJ than_CSN the_AT digital_JJ product_NN1 ,_, where_CS the_AT product_NN1 paid_VVN for_IF is_VBZ not_XX so_RG much_RR the_AT game_NN1 itself_PPX1 ,_, but_CCB rather_RG extra_JJ content_NN1 to_TO complement_VVI it_PPH1 ._. 
</s>
<s>
In_II conclusion_NN1 it_PPH1 is_VBZ likely_JJ that_CST the_AT video_NN1 game_NN1 market_NN1 will_VM follow_VVI the_AT music_NN1 distribution_NN1 industry_NN1 and_CC move_VVI to_II a_AT1 mostly_RR digital_JJ presence_NN1 ,_, with_IW some_DD physical_JJ presence_NN1 ._. 
</s>
<s>
Physical_JJ stores_NN2 will_VM be_VBI around_RP for_IF now_RT ,_, but_CCB will_VM mostly_RR disappear_VVI as_CSA they_PPHS2 can_VM not_XX compete_VVI with_IW digital_JJ and_CC mail_NN1 order_NN1 prices_NN2 due_II21 to_II22 higher_JJR costs_NN2 of_IO maintaining_VVG a_AT1 physical_JJ store_NN1 ._. 
</s>
