<s>
Introduction_NN1 Analysts_NN2 and_CC investors_NN2 use_VV0 a_AT1 lot_NN1 of_IO different_JJ information_NN1 to_TO analyze_VVI and_CC valuate_JJ companies_NN2 and_CC determine_VVI trade_NN1 prices_NN2 within_II stock_NN1 markets_NN2 ._. 
</s>
<s>
This_DD1 information_NN1 could_VM include_VVI anything_PN1 from_II earnings_NN2 announcements_NN2 and_CC press_VVI releases_NN2 ,_, to_II authority_NN1 warnings_NN2 ._. 
</s>
<s>
Efficient_JJ market_NN1 theories_NN2 suggest_VV0 that_CST investors_NN2 are_VBR rational_JJ and_CC thus_RR security_NN1 prices_NN2 reflect_VV0 all_DB publicly_RR available_JJ information_NN1 of_IO that_DD1 specific_JJ security_NN1 (_( Scott_NP1 2003:92_MC )_) ._. 
</s>
<s>
From_II an_AT1 accounting_NN1 point_NN1 of_IO view_NN1 ,_, it_PPH1 is_VBZ the_AT accounting_NN1 information_NN1 that_CST is_VBZ of_IO interest_NN1 ,_, and_CC whether_CSW the_AT accounting_NN1 information_NN1 affects_VVZ security_NN1 prices_NN2 ._. 
</s>
<s>
And_CC indeed_RR early_JJ studies_NN2 show_VV0 that_CST this_DD1 is_VBZ the_AT case_NN1 ,_, e.g._REX Ball_NN1 and_CC Brown_NP1 (_( 1968_MC )_) ,_, and_CC Easton_NP1 and_CC Zmijewski_NP1 (_( 1989_MC )_) to_TO point_VVI out_RP a_AT1 few_DA2 ._. 
</s>
<s>
Efficient_JJ market_NN1 theories_NN2 thus_RR suggest_VV0 that_CST investors_NN2 quickly_RR adjusts_VVZ security_NN1 prices_NN2 after_II publication_NN1 of_IO different_JJ information_NN1 ._. 
</s>
<s>
But_CCB are_VBR markets_NN2 fully_RR efficient_JJ ?_? 
</s>
<s>
Several_DA2 anomalies_NN2 exist_VV0 about_II market_NN1 efficiency_NN1 ,_, and_CC two_MC early_JJ studies_NN2 were_VBDR made_VVN by_II Foster_NP1 ,_, Olsen_NP1 &;_NULL Shevlin_NP1 (_( 1984_MC )_) and_CC Sloan_NP1 (_( 1996_MC )_) ._. 
</s>
<s>
Foster_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 1984_MC )_) studied_VVD a_AT1 so_JJ21 called_JJ22 post-announcement_JJ drift_NN1 of_IO the_AT stock_NN1 prices_NN2 and_CC they_PPHS2 found_VVD out_RP that_CST the_AT market_NN1 did_VDD not_XX adjust_VVI security_NN1 prices_NN2 after_CS announced_VVN unexpected_JJ earnings_NN2 ,_, but_CCB the_AT price_NN1 tended_VVD to_TO slowly_RR drift_VVI towards_II the_AT efficient_JJ price_NN1 ._. 
</s>
<s>
Sloan_NP1 (_( 1996_MC )_) investigated_VVD the_AT effect_NN1 of_IO accruals_NN2 and_CC cash_NN1 flow_NN1 components_NN2 on_II earnings_NN2 ._. 
</s>
<s>
His_APPGE study_NN1 showed_VVD that_CST the_AT cash_NN1 flow_NN1 component_NN1 of_IO earnings_NN2 is_VBZ more_RGR persistent_JJ than_CSN the_AT accrual_NN1 component_NN1 ,_, and_CC in_II an_AT1 efficient_JJ market_NN1 investors_NN2 would_VM take_VVI this_DD1 into_II consideration_NN1 when_CS making_VVG investment_NN1 decisions_NN2 ._. 
</s>
<s>
Sloan_NP1 found_VVD out_RP that_CST this_DD1 was_VBDZ not_XX the_AT case_NN1 ._. 
</s>
<s>
Investors_NN2 seemed_VVD to_TO fixate_VVI on_II the_AT earnings_NN2 number_NN1 only_RR ,_, instead_II21 of_II22 decomposing_VVG it_PPH1 into_II cash_NN1 flows_NN2 and_CC accruals_NN2 ,_, and_CC therefore_RR securities_NN2 were_VBDR mispriced_VVN ._. 
</s>
<s>
In_II the_AT field_NN1 of_IO accounting_NN1 and_CC finance_VV0 it_PPH1 is_VBZ common_JJ knowledge_NN1 that_CST the_AT balance_NN1 between_II relevance_NN1 and_CC reliability_NN1 determines_VVZ the_AT decision_NN1 usefulness_NN1 of_IO the_AT accounting_NN1 information_NN1 to_II analysts_NN2 and_CC investors_NN2 ._. 
</s>
<s>
The_AT more_RGR relevant_JJ the_AT information_NN1 is_VBZ ,_, the_AT more_DAR decision_NN1 useful_JJ it_PPH1 is_VBZ ._. 
</s>
<s>
Relevance_NN1 here_RL means_VVZ more_RGR forward-looking_JJ information_NN1 and_CC this_DD1 is_VBZ useful_JJ for_IF investors_NN2 in_II the_AT sense_NN1 that_CST they_PPHS2 will_VM better_RRR know_VVI how_RRQ the_AT company_NN1 will_VM perform_VVI in_II the_AT future_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ then_RT the_AT company_NN1 executives_NN2 who_PNQS decide_VV0 which_DDQ accounting_NN1 methods_NN2 and_CC policies_NN2 are_VBR used_VVN to_TO produce_VVI this_DD1 relevant_JJ information_NN1 for_IF investors_NN2 (_( Scott_NP1 2003_MC )_) ._. 
</s>
<s>
This_DD1 raises_VVZ the_AT question_NN1 whether_CSW the_AT executives_NN2 chooses_VVZ accounting_VVG methods_NN2 that_CST truly_RR reflects_VVZ the_AT underlying_JJ economic_JJ situation_NN1 of_IO the_AT company_NN1 ._. 
</s>
<s>
Is_VBZ the_AT accounting_NN1 information_NN1 reliable_JJ ?_? 
</s>
<s>
The_AT accounting_NN1 standards_NN2 today_RT leave_VV0 some_DD room_NN1 for_IF executives_NN2 to_TO use_VVI their_APPGE own_DA judgment_NN1 in_II choosing_VVG accounting_NN1 policies_NN2 to_TO keep_VVI relevance_NN1 in_II the_AT accounting_NN1 information_NN1 ._. 
</s>
<s>
If_CS that_DD1 information_NN1 were_VBDR made_VVN fully_RR reliable_JJ ,_, in_II form_NN1 of_IO setting_VVG rigid_JJ accounting_NN1 standards_NN2 that_CST leave_VV0 no_AT room_NN1 for_IF forecasting_VVG the_AT future_NN1 ,_, it_PPH1 would_VM be_VBI of_IO no_AT use_NN1 for_IF investors_NN2 ._. 
</s>
<s>
The_AT numbers_NN2 would_VM tell_VVI nothing_PN1 about_II future_JJ performance_NN1 and_CC thus_RR investors_NN2 would_VM have_VHI to_TO determine_VVI the_AT value_NN1 on_II basis_NN1 of_IO other_JJ information_NN1 (_( Scott_NP1 2003_MC )_) ._. 
</s>
<s>
If_CS company_NN1 executives_NN2 use_VV0 their_APPGE own_DA discretion_NN1 in_II choosing_VVG accounting_NN1 methods_NN2 and_CC policies_NN2 ,_, could_VM they_PPHS2 use_VVI this_DD1 power_NN1 to_TO manipulate_VVI the_AT accounting_NN1 numbers_NN2 ?_? 
</s>
<s>
Could_VM this_DD1 have_VHI an_AT1 effect_NN1 on_II the_AT security_NN1 price_NN1 ,_, and_CC how_RRQ would_VM they_PPHS2 manipulate_VVI the_AT accounting_NN1 information_NN1 in_II such_DA a_AT1 case_NN1 ?_? 
</s>
<s>
This_DD1 type_NN1 of_IO manipulation_NN1 of_IO accounting_VVG number_NN1 is_VBZ called_VVN earnings_NN2 management_NN1 ._. 
</s>
<s>
A_AT1 commonly_RR known_VVN method_NN1 of_IO doing_VDG this_DD1 is_VBZ through_II accruals_NN2 (_( Scott_NP1 2003:371_MC )_) ._. 
</s>
<s>
And_CC as_II the_AT Sloan_JJ study_NN1 has_VHZ shown_VVN ,_, accruals_NN2 does_VDZ have_VHI an_AT1 effect_NN1 on_II security_NN1 prices_NN2 ._. 
</s>
<s>
Or_CC in_II other_JJ words_NN2 ,_, through_II high_JJ accruals_NN2 the_AT value_NN1 of_IO a_AT1 security_NN1 could_VM be_VBI mispriced_VVN ._. 
</s>
<s>
This_DD1 raises_VVZ the_AT question_NN1 whether_CSW company_NN1 managers_NN2 can_VM affect_VVI the_AT market_NN1 value_NN1 of_IO the_AT company_NN1 through_II manipulation_NN1 of_IO accruals_NN2 ?_? 
</s>
<s>
Several_DA2 studies_NN2 ,_, e.g._REX Teoh_NP1 ,_, Wong_NP1 &;_NULL Rao_NP1 (_( 1998_MC )_) and_CC Richardson_NP1 ,_, Sloan_NP1 ,_, Soliman_NP1 &;_NULL Tuna_NN (_( 2005_MC )_) ,_, have_VH0 shown_VVN that_CST companies_NN2 in_II different_JJ circumstances_NN2 ,_, that_CST have_VH0 high_RR unexpected_JJ accruals_NN2 ,_, do_VD0 lead_VVI to_II security_NN1 mispricing_VVG ._. 
</s>
<s>
And_CC as_CSA mentioned_VVN these_DD2 high_JJ unexpected_JJ accruals_NN2 are_VBR considered_VVN an_AT1 indication_NN1 of_IO earnings_NN2 management_NN1 ._. 
</s>
<s>
In_II financial_JJ theories_NN2 this_DD1 type_NN1 of_IO evidence_NN1 seems_VVZ to_II more_RGR common_JJ than_CSN evidence_NN1 that_CST securities_NN2 are_VBR not_XX mispriced_VVN due_II21 to_II22 high_JJ accruals_NN2 ._. 
</s>
<s>
Why_RRQ do_VD0 not_XX investors_NN2 see_VVI the_AT earnings_NN2 management_NN1 in_II form_NN1 of_IO high_JJ unexpected_JJ accruals_NN2 ?_? 
</s>
<s>
Accounting_VVG information_NN1 is_VBZ publicly_RR available_JJ and_CC due_II21 to_II22 all_DB studies_NN2 made_VVN on_II the_AT effect_NN1 of_IO accruals_NN2 ,_, one_PN1 would_VM think_VVI that_DD1 investor_NN1 would_VM have_VHI learned_VVN to_TO take_VVI these_DD2 into_II account_NN1 when_CS making_VVG investment_NN1 decisions_NN2 ._. 
</s>
<s>
This_DD1 paper_NN1 tries_VVZ to_TO find_VVI evidence_NN1 of_IO investor_NN1 rationality_NN1 in_II form_NN1 of_IO investors_NN2 considering_II high_JJ accruals_NN2 in_II their_APPGE investment_NN1 decisions_NN2 ._. 
</s>
<s>
The_AT research_NN1 question_NN1 therefore_RR is_VBZ :_: due_II21 to_II22 prior_JJ evidence_NN1 of_IO the_AT effect_NN1 of_IO high_JJ unexpected_JJ accruals_NN2 on_II company_NN1 value_NN1 ,_, have_VH0 investors_NN2 learned_VVN to_TO detect_VVI earnings_NN2 management_NN1 and_CC reflect_VVI this_DD1 in_II the_AT security_NN1 price_NN1 ?_? 
</s>
<s>
First_MD ,_, theory_NN1 about_II earnings_NN2 management_NN1 will_VM be_VBI introduced_VVN ._. 
</s>
<s>
Second_MD ,_, studies_NN2 that_CST speak_VV0 for_IF market_NN1 inefficiency_NN1 will_VM be_VBI presented_VVN ._. 
</s>
<s>
Third_MD ,_, studies_NN2 that_CST speak_VV0 for_IF market_NN1 efficiency_NN1 will_VM be_VBI shown_VVN ._. 
</s>
<s>
The_AT last_MD part_NN1 will_VM summarize_VVI and_CC conclude_VVI the_AT findings_NN2 ._. 
</s>
<s>
Earnings_NN2 management_NN1 Scott_NP1 (_( 2003:369_MC )_) defines_VVZ earnings_NN2 management_NN1 as_CSA .._... the_AT choice_NN1 by_II a_AT1 manager_NN1 of_IO accounting_NN1 policies_NN2 so_BCL21 as_BCL22 to_TO achieve_VVI some_DD specific_JJ objective._NNU Questions_NN2 of_IO interest_NN1 here_RL are_VBR which_DDQ the_AT objectives_NN2 are_VBR for_IF the_AT managers_NN2 to_TO achieve_VVI ,_, and_CC what_DDQ the_AT incentives_NN2 for_IF these_DD2 objectives_NN2 are_VBR ._. 
</s>
<s>
This_DD1 chapter_NN1 will_VM focus_VVI these_DD2 incentives_NN2 ,_, rather_II21 than_II22 earnings_NN2 management_NN1 techniques_NN2 ._. 
</s>
<s>
Earnings_NN2 management_NN1 can_VM be_VBI good_JJ in_II the_AT way_NN1 that_CST managers_NN2 manipulate_VV0 earnings_NN2 to_TO communicate_VVI inside_II information_NN1 to_II investor_NN1 ,_, e.g._REX by_II smoothing_VVG the_AT company_NN1 performance_NN1 ,_, and_CC thus_RR giving_VVG investors_NN2 more_RGR persistent_JJ stock_NN1 earnings_NN2 ._. 
</s>
<s>
However_RRQV managers_NN2 can_VM manipulate_VVI earnings_NN2 opportunistically_RR for_IF their_APPGE own_DA benefit_NN1 ,_, at_II the_AT cost_NN1 of_IO other_JJ company_NN1 stakeholders_NN2 ._. 
</s>
<s>
This_DD1 type_NN1 of_IO earnings_NN2 management_NN1 reduces_VVZ the_AT reliability_NN1 of_IO income_NN1 numbers_NN2 ._. 
</s>
<s>
This_DD1 is_VBZ because_II21 of_II22 the_AT income_NN1 decreasing_JJ effect_NN1 of_IO managing_JJ earnings_NN2 through_II the_AT common_JJ identifiable_JJ technique_NN1 ,_, which_DDQ is_VBZ high_JJ discretionary_JJ accruals_NN2 (_( Scott_NP1 2003:368-369_MCMC )_) ._. 
</s>
<s>
The_AT remainder_NN1 of_IO this_DD1 chapter_NN1 will_VM have_VHI the_AT focus_NN1 on_II the_AT bad_JJ side_NN1 of_IO earnings_NN2 management_NN1 ._. 
</s>
<s>
Thus_RR by_II the_AT term_NN1 earnings_NN2 management_NN1 I_PPIS1 refer_VV0 to_II the_AT actions_NN2 of_IO managers_NN2 ,_, driven_VVN by_II different_JJ incentives_NN2 ,_, to_TO mislead_VVI other_JJ company_NN1 stakeholders_NN2 ._. 
</s>
<s>
And_CC more_RGR specifically_RR mislead_VV0 analysts_NN2 and_CC investors_NN2 ._. 
</s>
<s>
Stock_NN1 market_NN1 purpose_NN1 Managers_NN2 may_VM have_VHI incentives_NN2 to_TO affect_VVI the_AT stock_NN1 price_NN1 of_IO the_AT company_NN1 ._. 
</s>
<s>
E.g._REX unlisted_JJ companies_NN2 do_VD0 not_XX have_VHI a_AT1 publicly_RR recognized_VVN market_NN1 value_NN1 ._. 
</s>
<s>
If_CS the_AT company_NN1 is_VBZ about_RPK to_TO go_VVI public_NN1 ,_, an_AT1 incentive_NN1 for_IF earnings_NN2 management_NN1 occurs_VVZ ._. 
</s>
<s>
Since_CS it_PPH1 is_VBZ shown_VVN that_CST analysts_NN2 and_CC investors_NN2 do_VD0 use_VVI income_NN1 numbers_NN2 to_II value_NN1 companies_NN2 ,_, managers_NN2 try_VV0 to_TO achieve_VVI as_RG high_JJ income_NN1 numbers_NN2 as_CSA possible_JJ before_II an_AT1 initial_JJ public_JJ offering_NN1 ,_, IPO_NP1 ._. 
</s>
<s>
The_AT connection_NN1 here_RL is_VBZ that_CST the_AT higher_JJR the_AT income_NN1 numbers_NN2 are_VBR ,_, the_AT higher_JJR the_AT first_MD public_JJ stock_NN1 price_NN1 for_IF the_AT company_NN1 is_VBZ (_( Scott_NP1 2003:382_MC )_) ._. 
</s>
<s>
As_CSA evidence_NN1 will_VM show_VVI ,_, earnings_NN2 management_NN1 for_IF stock_NN1 market_NN1 purposes_NN2 does_VDZ not_XX occur_VVI only_RR surrounding_JJ IPOs_NN2 ._. 
</s>
<s>
There_EX are_VBR different_JJ types_NN2 of_IO situations_NN2 ,_, such_II21 as_II22 meeting_VVG investor_NN1 expectations_NN2 ,_, where_CS earnings_NN2 management_NN1 occurs_VVZ ._. 
</s>
<s>
There_EX are_VBR also_RR additional_JJ incentives_NN2 for_IF earnings_NN2 management_NN1 ,_, such_II21 as_II22 contractual_JJ motivations_NN2 ,_, government_NN1 regulation_NN1 ,_, taxation_NN1 motivations_NN2 ,_, changes_NN2 of_IO the_AT CEO_NN1 and_CC communication_NN1 to_II investors_NN2 (_( Scott_NP1 2003_MC )_) ._. 
</s>
<s>
However_RR ,_, these_DD2 incentives_NN2 falls_VVZ outside_II the_AT scope_NN1 of_IO this_DD1 paper_NN1 and_CC thus_RR the_AT concentration_NN1 will_VM be_VBI on_II earnings_NN2 management_NN1 for_IF stock_NN1 market_NN1 purposes_NN2 ._. 
</s>
<s>
Remainder_NN1 From_II this_DD1 point_NN1 forward_RL I_PPIS1 will_VM present_VVI researches_NN2 that_CST support_VV0 market_NN1 inefficiency_NN1 and_CC that_DD1 suggests_VVZ that_CST investors_NN2 do_VD0 not_XX detect_VVI earnings_NN2 management_NN1 in_II form_NN1 of_IO high_JJ unexpected_JJ accruals_NN2 ._. 
</s>
<s>
I_PPIS1 will_VM also_RR try_VVI to_TO find_VVI evidence_NN1 that_CST investors_NN2 do_VD0 detect_VVI earnings_NN2 management_NN1 in_II form_NN1 of_IO high_JJ unexpected_JJ accruals_NN2 and_CC embed_VV0 this_DD1 discovery_NN1 in_II the_AT stock_NN1 price_NN1 ._. 
</s>
