<s>
Introduction_NN1 Refined_JJ research_NN1 question_NN1 How_RRQ are_VBR good_JJ customer_NN1 oriented_VVD strategies_NN2 built_VVN ?_? 
</s>
<s>
Introduction_NN1 We_PPIS2 are_VBR living_VVG in_II an_AT1 increasingly_RR global_JJ and_CC technologically_RR advanced_JJ world_NN1 ,_, where_CS competition_NN1 amongst_II companies_NN2 is_VBZ intensifying_VVG and_CC increasing_VVG faster_RRR and_CC faster_RRR ._. 
</s>
<s>
When_CS the_AT company_NN1 receives_VVZ new_JJ equipment_NN1 ,_, it_PPH1 is_VBZ already_RR old_JJ ,_, and_CC when_CS they_PPHS2 have_VH0 come_VVN up_RP with_IW a_AT1 new_JJ product_NN1 or_CC developed_VVD a_AT1 new_JJ service_NN1 ,_, it_PPH1 does_VDZ not_XX take_VVI long_RR until_CS other_JJ companies_NN2 also_RR produce_VV0 the_AT same_DA product_NN1 or_CC offer_VV0 the_AT same_DA service_NN1 ._. 
</s>
<s>
It_PPH1 can_VM thus_RR be_VBI difficult_JJ for_IF companies_NN2 to_TO find_VVI a_AT1 lasting_JJ competitive_JJ advantage_NN1 ,_, especially_RR in_II their_APPGE operations_NN2 and_CC offerings_NN2 ._. 
</s>
<s>
(_( Thomson_NP1 &;_NULL Hecker_NP1 2000_MC ;_; Wright_NP1 &;_NULL Snell_NP1 ,_, 2005_MC )_) It_PPH1 has_VHZ thus_RR become_VV0 very_RG important_JJ and_CC relevant_JJ for_IF companies_NN2 to_TO look_VVI within_II themselves_PPX2 and_CC try_VVI to_TO find_VVI what_DDQ differentiates_VVZ their_APPGE business_NN1 from_II other_JJ businesses_NN2 ._. 
</s>
<s>
The_AT difference_NN1 between_II great_JJ success_NN1 stories_NN2 and_CC tragic_JJ failures_NN2 is_VBZ hair_NN1 thin_JJ and_CC it_PPH1 is_VBZ thus_RR critical_JJ for_IF companies_NN2 to_TO understand_VVI the_AT importance_NN1 of_IO a_AT1 good_JJ customer_NN1 oriented_VVD strategy_NN1 -_- or_CC rather_RG a_AT1 fitting_JJ customer_NN1 oriented_VVD strategy_NN1 ,_, to_TO make_VVI them_PPHO2 stand_VVI out_RP from_II the_AT crowd_NN1 ._. 
</s>
<s>
In_II recent_JJ years_NNT2 we_PPIS2 have_VH0 seen_VVN examples_NN2 of_IO both_DB2 success_NN1 stories_NN2 (_( such_II21 as_II22 Apple_NN1 ,_, Spotify_NP1 ,_, and_CC Kone_VV0 -_- who_PNQS all_RR have_VH0 very_JJ customer_NN1 oriented_VVD strategies_NN2 )_) and_CC tragic_JJ failures_NN2 (_( such_II21 as_II22 Nokia_NP1 and_CC Myllykoski_NP1 -_- who_PNQS have_VH0 not_XX had_VHN fitting_JJ customer_NN1 oriented_VVD strategies_NN2 )_) In_II the_AT academic_JJ world_NN1 it_PPH1 is_VBZ becoming_VVG more_RRR and_CC more_RGR clear_JJ that_CST customer_NN1 oriented_VVD companies_NN2 are_VBR the_AT ones_NN2 prevailing_JJ ._. 
</s>
<s>
A_AT1 good_JJ customer_NN1 oriented_VVD strategy_NN1 can_VM make_VVI a_AT1 company_NN1 and_CC just_RR as_RG easily_RR a_AT1 bad_JJ strategy_NN1 can_VM break_VVI it_PPH1 ,_, yet_RR few_DA2 companies_NN2 have_VH0 truly_RR customer_NN1 oriented_VVD strategies_NN2 (_( Grnroos_NP1 2012_MC )_) ._. 
</s>
<s>
This_DD1 might_VM partially_RR be_VBI because_CS building_VVG a_AT1 fitting_NN1 ,_, truly_RR customer_NN1 oriented_VVD strategy_NN1 ,_, is_VBZ not_XX easy_JJ ._. 
</s>
<s>
On_II one_MC1 hand_NN1 ,_, they_PPHS2 must_VM be_VBI planned_VVN ,_, but_CCB on_II the_AT other_JJ hand_NN1 ,_, they_PPHS2 need_VV0 to_TO be_VBI flexible_JJ as_CSA they_PPHS2 are_VBR constantly_RR changing_VVG and_CC evolving_VVG ._. 
</s>
<s>
Another_DD1 reason_NN1 might_VM be_VBI the_AT blatant_JJ fact_NN1 that_CST companies_NN2 just_RR have_VH0 not_XX realised_VVN the_AT advantages_NN2 a_AT1 customer_NN1 oriented_VVD strategy_NN1 brings_VVZ ,_, or_CC that_CST they_PPHS2 just_RR do_VD0 not_XX know_VVI how_RRQ a_AT1 customer_NN1 oriented_VVD strategy_NN1 is_VBZ built_VVN ._. 
</s>
<s>
Scholars_NN2 from_II the_AT Nordic_JJ School_NN1 ,_, with_IW leading_JJ member_NN1 Christian_JJ Grnroos_NN2 at_II the_AT top_NN1 ,_, have_VH0 published_VVN many_DA2 articles_NN2 on_II how_RRQ companies_NN2 should_VM become_VVI more_DAR customer_NN1 oriented_VVD ,_, unfortunately_RR the_AT amount_NN1 of_IO customer_NN1 oriented_VVD articles_NN2 being_VBG published_VVN in_II other_JJ countries_NN2 is_VBZ very_RG low_JJ ._. 
</s>
<s>
Also_RR ,_, few_DA2 of_IO these_DD2 articles_NN2 offer_VV0 companies_NN2 practical_JJ advice_NN1 on_II how_RRQ to_TO do_VDI this_DD1 ,_, especially_RR when_CS it_PPH1 comes_VVZ to_II building_VVG a_AT1 customer_NN1 oriented_VVD strategy_NN1 ._. 
</s>
<s>
So_RR the_AT question_NN1 still_RR remains_VVZ :_: How_RRQ are_VBR good_JJ customer_NN1 oriented_VVD strategies_NN2 built_VVN ?_? 
</s>
<s>
This_DD1 paper_NN1 will_VM focus_VVI on_II answering_VVG this_DD1 question_NN1 thus_RR giving_VVG companies_NN2 insight_NN1 into_II what_DDQ they_PPHS2 can_VM do_VDI to_TO make_VVI their_APPGE strategy_NN1 more_DAR customer_NN1 oriented_VVD ,_, or_CC build_VV0 a_AT1 completely_RR new_JJ customer_NN1 oriented_VVD strategy_NN1 ._. 
</s>
<s>
The_AT paper_NN1 will_VM be_VBI divided_VVN into_II four_MC sections_NN2 :_: literature_NN1 review_NN1 ,_, methods_NN2 ,_, results_NN2 ,_, and_CC discussion_NN1 ,_, with_IW the_AT focal_JJ point_NN1 on_II the_AT literature_NN1 review_NN1 and_CC discussion_NN1 ._. 
</s>
<s>
Litterature_VV0 review_NN1 According_II21 to_II22 Collis_NP1 and_CC Rukstad_NP1 a_AT1 strategy_NN1 is_VBZ a_AT1 company_NN1 's_GE game_NN1 plan_NN1 on_II how_RRQ they_PPHS2 are_VBR going_VVGK to_TO come_VVI closer_RRR to_II their_APPGE vision_NN1 ._. 
</s>
<s>
Th_NP1 core_NN1 of_IO a_AT1 company_NN1 's_GE strategy_NN1 is_VBZ made_VVN up_RP of_IO three_MC factors_NN2 ;_; Objective_NN1 ,_, scope_NN1 and_CC advantage_NN1 ._. 
</s>
<s>
The_AT company_NN1 's_GE objective_NN1 is_VBZ a_AT1 certain_JJ goal_NN1 ,_, or_CC many_DA2 goals_NN2 ,_, that_CST they_PPHS2 set_VV0 out_RP to_TO achieve_VVI ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO have_VHI a_AT1 truly_RR customer_NN1 oriented_VVD strategy_NN1 ,_, this_DD1 objective_NN1 needs_VVZ to_TO be_VBI customer_NN1 oriented_VVD ._. 
</s>
<s>
A_AT1 customer_NN1 oriented_VVD objective_NN1 could_VM be_VBI getting_VVG rid_VVN of_IO a_AT1 problem_NN1 the_AT customer_NN1 has_VHZ ,_, making_VVG something_PN1 easier_JJR or_CC providing_VVG her_PPHO1 with_IW a_AT1 totally_RR new_JJ solution_NN1 ._. 
</s>
<s>
What_DDQ ever_RR the_AT objective_NN1 ,_, it_PPH1 has_VHZ to_TO be_VBI precise_JJ and_CC clear_JJ ._. 
</s>
<s>
A_AT1 time_NNT1 frame_NN1 for_IF reaching_VVG the_AT objective_NN1 must_VM also_RR be_VBI set_VVN to_TO give_VVI it_PPH1 such_DA clarity_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ also_RR important_JJ from_II a_AT1 measuring_JJ perspective_NN1 (_( Collis_NP1 &;_NULL Rukstad_NP1 2010_MC )_) The_AT scope_NN1 frames_VVZ the_AT climate_NN1 where_CS the_AT firm_NN1 is_VBZ active_JJ ,_, or_CC more_RGR importantly_RR sets_VVZ limits_NN2 and_CC boundaries_NN2 for_IF where_RRQ it_PPH1 will_VM not_XX be_VBI active_JJ ._. 
</s>
<s>
It_PPH1 is_VBZ very_RG important_JJ for_IF company_NN1 's_VBZ to_TO clearly_RR specify_VVI their_APPGE scope_NN1 ,_, since_CS many_DA2 have_VH0 the_AT problem_NN1 of_IO trying_VVG to_TO do_VDI to_II much_RR instead_II21 of_II22 focusing_VVG on_II their_APPGE core_NN1 competence_NN1 and_CC capabilities_NN2 ._. 
</s>
<s>
Setting_VVG boundaries_NN2 with_IW the_AT customer_NN1 as_CSA focal_JJ point_NN1 will_VM lead_VVI the_AT firm_JJ to_TO orient_VVI according_II21 to_II22 the_AT customer_NN1 and_CC set_VV0 limits_NN2 and_CC boundaries_NN2 accordingly_RR ._. 
</s>
<s>
(_( Collis_NP1 &;_NULL Rukstad_NP1 2010_MC )_) For_IF company_NN1 's_VBZ to_TO obtain_VVI their_APPGE given_JJ objectives_NN2 within_II their_APPGE specified_JJ scope_NN1 ,_, they_PPHS2 need_VV0 to_TO understand_VVI their_APPGE advantages_NN2 over_II other_JJ company_NN1 's_GE ._. 
</s>
<s>
What_DDQ makes_VVZ them_PPHO2 more_RGR innovative_JJ and_CC better_RRR than_CSN their_APPGE competitors_NN2 ._. 
</s>
<s>
This_DD1 is_VBZ crucial_JJ for_IF companies_NN2 to_TO know_VVI since_CS it_PPH1 is_VBZ what_DDQ will_VM help_VVI them_PPHO2 achieve_VVI their_APPGE scope_NN1 ._. 
</s>
<s>
This_DD1 can_VM also_RR be_VBI seen_VVN from_II a_AT1 customer_NN1 perspective_NN1 ._. 
</s>
<s>
What_DDQ is_VBZ it_PPH1 that_CST makes_VVZ customers_NN2 choose_VVI one_MC1 firm_NN1 over_II another_DD1 ?_? 
</s>
<s>
(_( Collis_NP1 &;_NULL Rukstad_NP1 2010_MC )_) There_EX are_VBR also_RR many_DA2 other_JJ parts_NN2 of_IO a_AT1 company_NN1 statement_NN1 that_CST effect_VV0 the_AT strategy_NN1 thou_PPY they_PPHS2 are_VBR not_XX a_AT1 part_NN1 of_IO the_AT actual_JJ strategy_NN1 ._. 
</s>
<s>
These_DD2 factors_NN2 must_VM also_RR be_VBI taken_VVN into_II consideration_NN1 since_CS they_PPHS2 are_VBR deeply_RR intertwined_VVN with_IW the_AT a_AT1 company_NN1 's_GE strategy_NN1 ._. 
</s>
<s>
First_MD there_EX is_VBZ the_AT company_NN1 's_GE mission_NN1 i.e._REX why_RRQ they_PPHS2 exist_VV0 ._. 
</s>
<s>
Why_RRQ is_VBZ it_PPH1 they_PPHS2 are_VBR here_RL ?_? 
</s>
<s>
An_AT1 example_NN1 of_IO a_AT1 customer_NN1 oriented_VVD mission_NN1 is_VBZ Spotify_NP1 's_GE "_" We_PPIS2 want_VV0 to_TO connect_VVI millions_NNO2 of_IO people_NN with_IW their_APPGE favourite_JJ songs_NN2 and_CC create_VV0 a_AT1 service_NN1 that_CST people_NN love_VV0 to_TO use_VVI ._. 
</s>
<s>
We_PPIS2 believe_VV0 music_NN1 should_VM be_VBI easily_RR accessible_JJ and_CC that_DD1 listening_NN1 to_II music_NN1 will_VM make_VVI people_NN live_VVI richer_JJR lives_NN2 ._. 
</s>
<s>
We_PPIS2 want_VV0 to_TO create_VVI a_AT1 win_NN1 win_VV0 situation_NN1 for_IF people_NN who_PNQS love_VV0 listening_VVG to_II music_NN1 and_CC people_NN who_PNQS love_VV0 creating_VVG music_NN1 ._. "_" 
</s>
<s>
(_( Spotify_VV0 2012_MC )_) Second_MD are_VBR values_NN2 and_CC operating_VVG principles_NN2 ._. 
</s>
<s>
These_DD2 act_VV0 as_CSA guidelines_NN2 and_CC rules_NN2 inside_II the_AT company_NN1 ,_, but_CCB at_II the_AT same_DA time_NNT1 they_PPHS2 also_RR gives_VVZ the_AT outside_JJ world_NN1 an_AT1 understanding_NN1 of_IO how_RRQ the_AT company_NN1 thinks_VVZ and_CC acts_NN2 ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, this_DD1 gives_VVZ both_RR customers_NN2 and_CC employees_NN2 value_NN1 ._. 
</s>
<s>
Having_VHG customer_NN1 oriented_VVN operating_VVG principles_NN2 acts_VVZ as_II a_AT1 way_NN1 for_IF signalling_VVG to_II customers_NN2 that_CST they_PPHS2 are_VBR important_JJ to_II the_AT company_NN1 ._. 
</s>
<s>
It_PPH1 makes_VVZ the_AT company_NN1 not_XX only_RR think_VV0 with_IW the_AT customer_NN1 in_II focus_NN1 ,_, but_CCB also_RR act_VV0 with_IW the_AT customer_NN1 in_II focus_NN1 ._. 
</s>
<s>
(_( Collis_NP1 &;_NULL Rukstad_NP1 2010_MC )_) Third_MD is_VBZ vision_NN1 ._. 
</s>
<s>
A_AT1 company_NN1 's_GE vision_NN1 is_VBZ what_DDQ they_PPHS2 strive_VV0 to_TO be_VBI and_CC how_RRQ they_PPHS2 want_VV0 to_TO be_VBI perceived_VVN ._. 
</s>
<s>
As_CSA Marketing_NN1 Director_NN1 and_CC Innovator_NN1 for_IF Aktia_NP1 Abp_NP1 ,_, Marc_NP1 Hinnenberg_NP1 put_VVD it_PPH1 :_: A_AT1 company_NN1 's_GE vision_NN1 is_VBZ like_II the_AT sun_NN1 on_II the_AT company_NN1 's_GE horizon_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ something_PN1 that_CST is_VBZ clear_JJ and_CC constant_JJ but_CCB distant_JJ in_II the_AT future_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ the_AT goal_NN1 that_CST a_AT1 company_NN1 aligns_VVZ everything_PN1 else_RR to_II ._. 
</s>
<s>
(_( Hinnenberg_NP1 2012_MC )_) Finally_RR the_AT business_NN1 model_NN1 determines_VVZ how_RRQ value_NN1 is_VBZ created_VVN and_CC how_RRQ it_PPH1 is_VBZ delivered_VVN to_II the_AT consumer_NN1 (_( Teece_NP1 2010_MC )_) ._. 
</s>
<s>
The_AT business_NN1 model_NN1 is_VBZ thus_RR more_RRR about_II the_AT practical_JJ things_NN2 such_II21 as_II22 cost_NN1 structure_NN1 and_CC processes_NN2 both_RR within_RL and_CC outside_II the_AT company_NN1 ._. 
</s>
<s>
These_DD2 processes_NN2 constitute_VV0 a_AT1 large_JJ part_NN1 of_IO what_DDQ kind_NN1 of_IO strategy_NN1 the_AT company_NN1 can_VM manage_VVI ._. 
</s>
<s>
For_REX21 example_REX22 if_CS a_AT1 company_NN1 has_VHZ very_JJ product_NN1 oriented_VVD processes_NN2 and_CC a_AT1 non-flexible_JJ cost_NN1 structure_NN1 ,_, then_RT a_AT1 customer_NN1 oriented_VVD strategy_NN1 is_VBZ almost_RR impossible_JJ to_TO incorporate_VVI into_II the_AT company_NN1 's_GE statement_NN1 ._. 
</s>
<s>
Whereas_CS if_CS the_AT processes_NN2 within_II the_AT firm_NN1 are_VBR customer_NN1 oriented_VVD and_CC the_AT cost_NN1 structure_NN1 allows_VVZ for_IF flexibility_NN1 ,_, the_AT company_NN1 might_VM not_XX be_VBI as_RG sensitive_JJ to_II volatility_NN1 in_II the_AT market_NN1 and_CC thus_RR have_VH0 room_NN1 for_IF a_AT1 more_DAR customer_NN1 oriented_VVD strategy_NN1 ._. 
</s>
<s>
(_( Collis_NP1 &;_NULL Rukstad_NP1 2010_MC )_) All_DB of_IO the_AT above_JJ mentioned_VVD statements_NN2 need_VV0 to_TO be_VBI customer_NN1 oriented_VVD and_CC aligned_VVN with_IW one_PPX121 another_PPX122 in_BCL21 order_BCL22 for_IF a_AT1 company_NN1 's_GE strategy_NN1 to_TO truly_RR be_VBI customer_NN1 oriented_VVD ._. 
</s>
<s>
This_DD1 is_VBZ where_RRQ many_DA2 companies_NN2 go_VV0 wrong_RR and_CC try_VV0 to_TO only_RR have_VHI a_AT1 vision_NN1 or_CC mission_NN1 that_CST is_VBZ customer_NN1 oriented_VVD ._. 
</s>
<s>
Whilst_CS a_AT1 company_NN1 doing_VDG so_RR might_VM look_VVI like_II a_AT1 customer_NN1 oriented_VVD company_NN1 with_IW a_AT1 customer_NN1 focused_VVD strategy_NN1 ,_, it_PPH1 does_VDZ not_XX take_VVI long_RR until_CS the_AT layers_NN2 start_VV0 to_TO crack_VVI and_CC the_AT true_JJ orientation_NN1 of_IO the_AT company_NN1 is_VBZ revealed_VVN ._. 
</s>
<s>
Method_NN1 The_AT sampling_NN1 method_NN1 used_VVN in_II this_DD1 paper_NN1 is_VBZ criterion_NN1 sampling_NN1 ._. 
</s>
<s>
Criterion_NN1 sampling_NN1 is_VBZ when_RRQ respondents_NN2 or_CC interviewees_NN2 are_VBR chosen_VVN based_VVN on_II a_AT1 certain_JJ set_NN1 of_IO criterions_NN2 that_CST are_VBR important_JJ in_BCL21 order_BCL22 to_TO obtain_VVI the_AT right_JJ kind_NN1 of_IO data_NN (_( Patton_NP1 2002_MC :_: 243-344_MCMC )_) ._. 
</s>
<s>
In_II this_DD1 paper_NN1 the_AT criterions_NN2 where_CS 1_MC1 ._. 
</s>
<s>
the_AT respondents_NN2 had_VHD to_TO be_VBI experts_NN2 working_VVG with_IW strategic_JJ responsibilities_NN2 ,_, 2._MC have_VH0 founded_VVN their_APPGE own_DA companies_NN2 and_CC 3._MC be_VBI willing_JJ to_TO give_VVI an_AT1 in-depth_JJ interview_NN1 about_II strategy_NN1 both_RR on_II an_AT1 academic_JJ level_NN1 and_CC on_II a_AT1 everyday_JJ business_NN1 level_NN1 ._. 
</s>
<s>
Based_VVN on_II these_DD2 criterions_NN2 two_MC semi-structured_JJ ,_, in-depth_JJ interviews_NN2 were_VBDR conducted_VVN with_IW two_MC respondents_NN2 ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO protect_VVI the_AT identity_NN1 of_IO the_AT respondents_NN2 they_PPHS2 will_VM in_II this_DD1 paper_NN1 only_RR be_VBI mentioned_VVN with_IW their_APPGE initials_NN2 ._. 
</s>
<s>
The_AT first_MD respondent_NN1 ,_, K._NP1 S._NP1 ,_, founded_VVD a_AT1 management_NN1 consultancy_NN1 company_NN1 in_II 1994_MC as_CSA has_VHZ been_VBN the_AT partner_NN1 responsible_JJ for_IF the_AT strategic_JJ process_NN1 ._. 
</s>
<s>
He_PPHS1 has_VHZ been_VBN active_JJ in_II the_AT academic_JJ world_NN1 for_IF almost_RR 20_MC years_NNT2 and_CC is_VBZ currently_RR a_AT1 professor_NN1 at_II three_MC different_JJ universities_NN2 all_DB around_II the_AT world_NN1 ._. 
</s>
<s>
The_AT second_MD respondent_NN1 is_VBZ A._NP1 S._NP1 She_PPHS1 founded_VVD a_AT1 training_NN1 and_CC coaching_VVG company_NN1 in_II 1997_MC and_CC written_VVN three_MC books_NN2 on_II the_AT relation_NN1 between_II strategy_NN1 and_CC business_NN1 models_NN2 ._. 
</s>
<s>
The_AT data_NN collected_VVN in_II these_DD2 interviews_NN2 has_VHZ been_VBN transcribed_VVN and_CC categorised_VVN so_BCL21 as_BCL22 to_TO be_VBI easier_JJR to_TO analyse_VVI ._. 
</s>
<s>
The_AT data_NN will_VM be_VBI presented_VVN in_II the_AT following_JJ section_NN1 ._. 
</s>
<s>
Results_NN2 "_" It_PPH1 is_VBZ customary_JJ to_TO define_VVI both_RR a_AT1 mission_NN1 and_CC a_AT1 vision_NN1 ._. 
</s>
<s>
In_II our_APPGE case_NN1 it_PPH1 was_VBDZ to_TO act_VVI as_II a_AT1 platform_NN1 for_IF people_NN to_TO learn_VVI and_CC become_VVI experts_NN2 ._. 
</s>
<s>
We_PPIS2 thus_RR had_VHD a_AT1 mission_NN1 directed_VVN at_II staff_NN ._. 
</s>
<s>
our_APPGE vision_NN1 was_VBDZ that_CST we_PPIS2 wanted_VVD to_TO create_VVI a_AT1 situation_NN1 where_RRQ we_PPIS2 were_VBDR respected_VVN and_CC considered_VVN the_AT best_JJT experts_NN2 in_II our_APPGE field_NN1 "_" Discussion_NN1 
</s>
