<s>
Credit_NN1 spreads_VVZ vs._II credit_NN1 ratings_NN2 which_DDQ one_PN1 is_VBZ the_AT better_JJR credit_NN1 rating_NN1 Introduction_NN1 The_AT financial_JJ crisis_NN1 that_CST started_VVD in_II the_AT fall_NN1 of_IO 2008_MC shocked_VVD the_AT global_JJ financial_JJ system_NN1 ._. 
</s>
<s>
The_AT crisis_NN1 that_CST got_VVD its_APPGE start_NN1 from_II the_AT rotten_JJ American_JJ sub-prime_JJ mortgages_NN2 has_VHZ during_II the_AT recent_JJ years_NNT2 developed_VVN into_II a_AT1 debt_NN1 crisis_NN1 ._. 
</s>
<s>
The_AT economic_JJ growth_NN1 of_IO Europe_NP1 and_CC America_NP1 has_VHZ been_VBN based_VVN on_II public_NN1 and_CC private_JJ spending_NN1 ,_, which_DDQ has_VHZ led_VVN to_II record-high_JJ levels_NN2 of_IO indebtedness_NN1 on_II both_DB2 the_AT private_JJ and_CC public_JJ sector_NN1 ._. 
</s>
<s>
Since_CS the_AT implementation_NN1 of_IO the_AT euro_NN1 in_II the_AT shift_NN1 of_IO the_AT 21st_MD century_NNT1 ,_, many_DA2 countries_NN2 have_VH0 been_VBN able_JK to_TO borrow_VVI money_NN1 from_II the_AT debt_NN1 market_NN1 to_II the_AT lowest_JJT possible_JJ interest_NN1 rate_NN1 ,_, thanks_NN2 to_II their_APPGE highest_JJT possible_JJ credit_NN1 rating_NN1 ._. 
</s>
<s>
The_AT market_NN1 blindly_RR believed_VVN in_II the_AT credit-worthiness_NN1 of_IO all_DB the_AT members_NN2 of_IO the_AT monetary_JJ union_NN1 ,_, because_CS the_AT currency_NN1 was_VBDZ anchored_VVN by_II the_AT large_JJ economic_JJ powers_NN2 like_II Germany_NP1 and_CC France_NP1 ._. 
</s>
<s>
Well_RR as_CSA the_AT recent_JJ years_NNT2 have_VH0 shown_VVN the_AT markets_NN2 were_VBDR wrong_JJ ._. 
</s>
<s>
The_AT so_JJ21 called_JJ22 PIIGS-countries_NN2 or_CC the_AT Mediterranean_JJ club_NN1 i.e._REX Portugal_NP1 ,_, Ireland_NP1 ,_, Italy_NP1 ,_, Greece_NP1 and_CC Spain_NP1 have_VH0 during_II the_AT recent_JJ years_NNT2 shown_VVN alarmingly_RR high_JJ deficits_NN2 in_II their_APPGE balance_NN1 of_IO payments_NN2 and_CC their_APPGE public_JJ spending_NN1 ._. 
</s>
<s>
These_DD2 deficits_NN2 have_VH0 led_VVN to_II historically_RR high_JJ indebtedness_NN1 levels_NN2 ,_, because_CS the_AT deficits_NN2 always_RR have_VH0 to_TO be_VBI financed_VVN with_IW debt_NN1 ._. 
</s>
<s>
The_AT excessive_JJ borrowing_NN1 continued_VVD the_AT major_JJ part_NN1 of_IO the_AT last_MD decade_NNT1 ,_, until_CS 2008_MC when_RRQ the_AT true_JJ state_NN1 of_IO the_AT economy_NN1 was_VBDZ revealed_VVN ._. 
</s>
<s>
One_MC1 of_IO the_AT key_JJ factors_NN2 ,_, that_CST the_AT borrowing_NN1 had_VHD been_VBN allowed_VVN to_TO continue_VVI for_IF as_CS31 long_CS32 as_CS33 it_PPH1 did_VDD was_VBDZ the_AT fact_NN1 ,_, as_CSA I_PPIS1 mentioned_VVD earlier_RRR ,_, that_CST the_AT government_NN1 bonds_NN2 of_IO these_DD2 countries_NN2 had_VHD the_AT highest_JJT possible_JJ credit_NN1 rating_NN1 of_IO triple-A_NN1 ._. 
</s>
<s>
Now_RT many_DA2 years_NNT2 after_CS that_CST the_AT financial_JJ crisis_NN1 has_VHZ begun_VVN ,_, many_DA2 economists_NN2 have_VH0 wondered_VVN how_RRQ these_DD2 countries_NN2 had_VHD maintained_VVN their_APPGE triple-A_JJ rating_NN1 for_IF so_RG long_RR ,_, when_CS the_AT structural_JJ flaws_NN2 of_IO these_DD2 economies_NN2 were_VBDR clearly_RR evident_JJ in_II years_NNT2 ._. 
</s>
<s>
The_AT public_NN1 opinion_NN1 has_VHZ also_RR been_VBN highly_RR critical_JJ towards_II the_AT rating_NN1 agencies_NN2 ._. 
</s>
<s>
The_AT rating_NN1 agencies_NN2 were_VBDR first_MD wrong_JJ with_IW the_AT sub-prime_JJ mortgage_NN1 loans_NN2 and_CC then_RT with_IW government_NN1 bonds_NN2 ._. 
</s>
<s>
Both_DB2 of_IO these_DD2 errors_NN2 have_VH0 cost_VVN billions_NNO2 to_II the_AT ordinary_JJ tax-payers_NN2 ._. 
</s>
<s>
These_DD2 fatal_JJ errors_NN2 have_VH0 started_VVN a_AT1 discussion_NN1 about_II credit_NN1 ratings_NN2 and_CC the_AT big_JJ three_MC rating_NN1 agencies_NN2 in_RR21 general_RR22 ._. 
</s>
<s>
The_AT rating_NN1 agencies_NN2 have_VH0 been_VBN accused_VVN of_IO manipulating_VVG the_AT market_NN1 and_CC politicians_NN2 have_VH0 begun_VVN to_TO search_VVI for_IF ways_NN2 to_TO limit_VVI their_APPGE power_NN1 ._. 
</s>
<s>
Economists_NN2 have_VH0 also_RR researched_VVN alternatives_NN2 to_II the_AT traditional_JJ credit_NN1 rating_NN1 ._. 
</s>
<s>
One_MC1 interesting_JJ option_NN1 would_VM be_VBI to_TO measure_VVI the_AT credit_NN1 spreads_VVZ ._. 
</s>
<s>
The_AT credit_NN1 spread_NN1 is_VBZ the_AT difference_NN1 in_II the_AT yields_NN2 between_II a_AT1 bond_NN1 and_CC a_AT1 bond_NN1 that_CST is_VBZ considered_VVN risk-free_JJ ,_, with_IW the_AT same_DA maturity_NN1 ._. 
</s>
<s>
The_AT risk-free_JJ bond_NN1 ,_, which_DDQ all_DB other_JJ bonds_NN2 are_VBR compared_VVN to_II ,_, is_VBZ in_II practice_NN1 the_AT German_JJ government_NN1 bond_NN1 or_CC the_AT American_JJ government_NN1 bonds_NN2 ._. 
</s>
<s>
It_PPH1 can_VM be_VBI argued_VVN that_CST the_AT credit_NN1 spread_NN1 contains_VVZ all_RR31 the_RR32 same_RR33 essential_JJ information_NN1 as_CSA the_AT credit_NN1 rating_NN1 ,_, but_CCB is_VBZ more_RGR accurate_JJ ._. 
</s>
<s>
The_AT problem_NN1 with_IW credit_NN1 ratings_NN2 is_VBZ that_CST the_AT issuer_NN1 of_IO the_AT asset_NN1 pays_VVZ for_IF the_AT rating_NN1 ;_; this_DD1 gives_VVZ a_AT1 twisted_JJ incentive_NN1 to_II the_AT rating_NN1 agencies_NN2 because_CS they_PPHS2 do_VD0 n't_XX want_VVI to_TO give_VVI a_AT1 bad_JJ rating_NN1 to_II the_AT one_MC1 whos_VVZ paying_VVG the_AT bill_NN1 ._. 
</s>
<s>
Credit_NN1 spreads_VVZ on_II the_AT other_JJ hand_NN1 are_VBR determined_VVN by_II the_AT market_NN1 ,_, which_DDQ makes_VVZ them_PPHO2 more_RGR accurate_JJ because_CS arbitrary_JJ opportunities_NN2 on_II the_AT market_NN1 disappear_VV0 in_II seconds_NNT2 ._. 
</s>
<s>
The_AT aim_NN1 of_IO this_DD1 paper_NN1 is_VBZ to_TO research_VVI the_AT advantages_NN2 of_IO rating_VVG bonds_NN2 with_IW the_AT help_NN1 of_IO a_AT1 credit_NN1 spread_NN1 based_VVN mechanism_NN1 instead_II21 of_II22 credit_NN1 ratings_NN2 ._. 
</s>
<s>
The_AT topic_NN1 is_VBZ now_RT more_RGR current_JJ than_CSN ever_RR and_CC credit_NN1 spreads_VVZ and_CC ratings_NN2 are_VBR followed_VVN daily_RR in_II the_AT media_NN ._. 
</s>
<s>
I_PPIS1 will_VM base_VVI my_APPGE paper_NN1 mainly_RR on_II two_MC articles_NN2 that_CST I_PPIS1 will_VM present_VVI in_II the_AT earlier_JJR research_NN1 section_NN1 ._. 
</s>
<s>
The_AT paper_NN1 will_VM be_VBI structured_VVN in_II the_AT following_JJ way_NN1 ._. 
</s>
<s>
The_AT first_MD part_NN1 will_VM include_VVI the_AT abstract_JJ ,_, a_AT1 introduction_NN1 and_CC a_AT1 review_NN1 of_IO the_AT earlier_JJR literature_NN1 ._. 
</s>
<s>
The_AT second_MD part_NN1 will_VM include_VVI the_AT theory_NN1 ,_, a_AT1 discussion_NN1 of_IO the_AT pros_NN2 and_CC cons_NN2 of_IO both_DB2 credit_VV0 ratings_NN2 and_CC credit_NN1 spreads_VVZ ._. 
</s>
<s>
The_AT third_MD part_NN1 will_VM include_VVI a_AT1 discussion_NN1 and_CC the_AT conclusions_NN2 ._. 
</s>
<s>
Earlier_JJR research_NN1 In_II this_DD1 chapter_NN1 I_PPIS1 will_VM present_VVI some_DD of_IO the_AT earlier_JJR research_NN1 that_CST has_VHZ been_VBN done_VDN in_II this_DD1 field_NN1 of_IO study_NN1 ._. 
</s>
<s>
The_AT topic_NN1 has_VHZ been_VBN much_RR discussed_VVN in_II the_AT media_NN recently_RR ,_, so_CS it_PPH1 has_VHZ also_RR naturally_RR caught_VVN the_AT attention_NN1 of_IO the_AT economic_JJ community_NN1 ._. 
</s>
<s>
(_( Flannery_NN1 ,_, Houston_NP1 ,_, &;_NULL Partnoy_NP1 ,_, 2010_MC )_) (_( Flannery_NP1 ,_, Houston_NP1 ,_, &;_NULL Partnoy_NP1 ,_, 2010_MC )_) study_VV0 the_AT spreads_NN2 in_II credit_NN1 default_NN1 swaps_VVZ as_II an_AT1 alternate_JJ for_IF credit_NN1 ratings_NN2 ._. 
</s>
<s>
Credit_NN1 default_NN1 swaps_NN2 (_( CDS_NN2 )_) are_VBR insurance_NN1 contracts_VVZ that_CST an_AT1 investor_NN1 can_VM purchase_VVI to_TO hedge_VVI the_AT taken_JJ position_NN1 ._. 
</s>
<s>
For_REX21 example_REX22 ,_, if_CS an_AT1 investor_NN1 buys_VVZ a_AT1 Finnish_JJ government_NN1 bond_NN1 with_IW the_AT maturity_NN1 of_IO 5_MC years_NNT2 ,_, he/she_PPHS1 exposes_VVZ himself_PPX1 to_II the_AT risk_NN1 that_CST Finland_NP1 will_VM default_VVI and_CC will_VM be_VBI unable_JK to_TO pay_VVI its_APPGE debts_NN2 ._. 
</s>
<s>
But_CCB if_CS the_AT investor_NN1 has_VHZ purchased_VVN a_AT1 CDS_NN2 he/she_PPHS1 will_VM not_XX lose_VVI it_PPH1 all_DB ,_, because_CS in_II the_AT case_NN1 of_IO a_AT1 Finnish_JJ default_NN1 the_AT issuer_NN1 of_IO the_AT CDS_NN2 is_VBZ obliged_VVN to_TO pay_VVI to_II purchaser_NN1 of_IO the_AT CDS_NN2 ._. 
</s>
<s>
In_II other_JJ words_NN2 the_AT CDS_NN2 provides_VVZ an_AT1 insurance_NN1 against_II a_AT1 Finnish_JJ default_NN1 ._. 
</s>
<s>
The_AT paper_NN1 concentrated_VVN on_II the_AT CDS_NN2 spreads_VVZ of_IO the_AT 15_MC most_RGT important_JJ financial_JJ firms_NN2 ._. 
</s>
<s>
The_AT study_NN1 was_VBDZ conducted_VVN on_II data_NN ranging_VVG from_II 2007_MC to_II 2009_MC ,_, which_DDQ included_VVD the_AT most_RGT critical_JJ years_NNT2 of_IO the_AT latest_JJT financial_JJ crisis_NN1 ._. 
</s>
<s>
(_( Flannery_NN1 ,_, Houston_NP1 ,_, &;_NULL Partnoy_NP1 ,_, 2010_MC )_) found_VVD that_CST the_AT credit_NN1 spreads_VVZ of_IO the_AT CDS_NN2 contracts_NN2 failed_VVD to_TO foresee_VVI the_AT financial_JJ crisis_NN1 ,_, as_CSA did_VDD the_AT credit_NN1 ratings_NN2 ,_, but_CCB they_PPHS2 reflected_VVD the_AT new_JJ information_NN1 faster_RRR than_CSN the_AT credit_NN1 ratings_NN2 ._. 
</s>
<s>
The_AT biggest_JJT contribution_NN1 of_IO (_( Flannery_NP1 ,_, Houston_NP1 ,_, &;_NULL Partnoy_NP1 ,_, 2010_MC )_) was_VBDZ the_AT confirmation_NN1 that_CST credit_NN1 spreads_VVZ are_VBR a_AT1 good_JJ market-based_JJ alternative_NN1 to_TO credit_VVI ratings_NN2 ._. 
</s>
<s>
(_( Partnoy_NN1 ,_, 1999_MC )_) (_( Partnoy_NP1 ,_, 1999_MC )_) takes_VVZ a_AT1 critical_JJ view_NN1 on_II credit_NN1 ratings_NN2 ._. 
</s>
<s>
The_AT paper_NN1 even_RR claims_VVZ that_CST the_AT only_JJ superpowers_NN2 left_VVN in_II the_AT world_NN1 are_VBR the_AT United_NP1 States_NP1 of_IO America_NP1 and_CC the_AT credit_NN1 rating_NN1 agencies_NN2 ._. 
</s>
<s>
The_AT paper_NN1 claims_VVZ that_CST the_AT role_NN1 of_IO the_AT credit_NN1 ratings_NN2 has_VHZ been_VBN greatly_RR exaggerated_VVN and_CC the_AT informational_JJ value_NN1 of_IO credit_NN1 ratings_NN2 have_VH0 been_VBN steadily_RR declining_VVG ._. 
</s>
<s>
The_AT paper_NN1 also_RR discusses_VVZ the_AT dilemma_NN1 with_IW financial_JJ regulation_NN1 and_CC the_AT need_NN1 for_IF NRSO-licenses_NN2 to_TO provide_VVI credit_NN1 ratings_NN2 ._. 
</s>
<s>
finds_VVZ that_DD1 credit_NN1 spreads_VVZ are_VBR at_RR21 least_RR22 as_RG accurate_JJ as_CSA credit_NN1 ratings_NN2 and_CC they_PPHS2 would_VM be_VBI a_AT1 potential_JJ substitute_NN1 for_IF credit_NN1 ratings_NN2 ._. 
</s>
<s>
Theory_NN1 In_II this_DD1 chapter_NN1 I_PPIS1 will_VM discuss_VVI the_AT pros_NN2 and_CC cons_NN2 of_IO the_AT traditional_JJ credit_NN1 ratings_NN2 ._. 
</s>
<s>
I_PPIS1 will_VM also_RR discuss_VVI the_AT pros_NN2 and_CC cons_NN2 of_IO using_VVG credit_NN1 spreads_VVZ as_II a_AT1 substitute_NN1 for_IF the_AT traditional_JJ rating_NN1 ._. 
</s>
<s>
Finally_RR I_PPIS1 will_VM make_VVI a_AT1 comparison_NN1 between_II credit_NN1 spreads_VVZ and_CC credit_NN1 ratings_NN2 ._. 
</s>
<s>
Credit_NN1 ratings_NN2 The_AT main_JJ objective_NN1 of_IO credit_NN1 ratings_NN2 is_VBZ to_TO provide_VVI the_AT investor_NN1 a_AT1 grade_NN1 on_II the_AT assets_NN2 credit_VV0 worthiness_NN1 ._. 
</s>
<s>
There_EX are_VBR thousands_NNO2 of_IO financial_JJ assets_NN2 on_II the_AT markets_NN2 nowadays_RT and_CC it_PPH1 is_VBZ impossible_JJ for_IF a_AT1 single_JJ investor_NN1 to_TO analyze_VVI each_DD1 and_CC every_AT1 asset_NN1 ,_, based_VVN on_II this_DD1 fact_NN1 it_PPH1 is_VBZ easy_JJ to_TO realize_VVI why_RRQ credit_NN1 ratings_NN2 would_VM be_VBI needed_VVN ._. 
</s>
<s>
An_AT1 investor_NN1 could_VM choose_VVI based_VVN on_II the_AT credit_NN1 rating_NN1 what_DDQ asset_NN1 to_TO analyze_VVI closer_RRR or_CC what_DDQ to_TO buy_VVI ._. 
</s>
<s>
Credit_NN1 ratings_NN2 help_VV0 also_RR to_TO minimize_VVI the_AT problem_NN1 with_IW adverse_JJ selection_NN1 ._. 
</s>
<s>
Thousands_NNO2 of_IO financial_JJ assets_NN2 are_VBR issued_VVN daily_RR ,_, the_AT quality_NN1 of_IO these_DD2 assets_NN2 range_VV0 from_II junk_NN1 to_II practically_RR risk-free_JJ ._. 
</s>
<s>
A_AT1 credit_NN1 rating_NN1 is_VBZ a_AT1 good_JJ instrument_NN1 for_IF the_AT issuer_NN1 to_TO signal_VVI the_AT quality_NN1 of_IO the_AT asset_NN1 ._. 
</s>
<s>
For_REX21 example_REX22 government_NN1 bonds_NN2 have_VH0 to_TO pay_VVI less_DAR interest_NN1 if_CS they_PPHS2 possess_VV0 a_AT1 high_JJ credit_NN1 rating_NN1 and_CC vice_RR21 versa_RR22 ._. 
</s>
<s>
This_DD1 means_VVZ that_CST a_AT1 credit_NN1 rating_NN1 is_VBZ a_AT1 credible_JJ signal_NN1 ,_, because_CS assets_NN2 that_CST are_VBR not_XX creditworthy_JJ will_VM not_XX acquire_VVI the_AT rating_NN1 ._. 
</s>
<s>
Credit_NN1 rating_NN1 agencies_NN2 have_VH0 also_RR built_VVN a_AT1 reputation_NN1 as_II a_AT1 provider_NN1 of_IO accurate_JJ essential_JJ information_NN1 ,_, even_CS21 though_CS22 this_DD1 image_NN1 has_VHZ been_VBN stained_VVN during_II the_AT recent_JJ years_NNT2 and_CC the_AT latest_JJT financial_JJ crisis_NN1 (_( Partnoy_NP1 ,_, 1999_MC )_) ._. 
</s>
<s>
Credit_NN1 ratings_NN2 are_VBR for_RR41 the_RR42 most_RR43 part_RR44 provided_VVN by_II the_AT big_JJ three_MC i.e._REX Standard_JJ &;_NULL Poors_NN2 ,_, Moody_NP1 's_GE and_CC Fitch_NP1 ._. 
</s>
<s>
These_DD2 three_MC firms_NN2 are_VBR renowned_JJ around_II the_AT world_NN1 and_CC they_PPHS2 all_DB have_VH0 been_VBN licensed_VVN to_TO provide_VVI credit_NN1 ratings_NN2 ._. 
</s>
<s>
Each_DD1 of_IO these_DD2 firms_NN2 possesses_VVZ a_AT1 lot_NN1 of_IO market_NN1 power_NN1 ,_, i.e._REX they_PPHS2 make_VV0 profits_NN2 above_II the_AT perfect_JJ competition-_JJ equilibrium_NN1 ._. 
</s>
<s>
The_AT fact_NN1 that_CST rating_VVG agencies_NN2 have_VH0 to_TO be_VBI licensed_VVN means_VVZ that_CST there_EX will_VM only_RR be_VBI a_AT1 handful_NN1 of_IO agencies_NN2 providing_VVG information_NN1 to_II the_AT markets_NN2 ._. 
</s>
<s>
The_AT exclusivity_NN1 of_IO these_DD2 licenses_NN2 forms_VVZ one_MC1 of_IO the_AT major_JJ problems_NN2 with_IW credit_NN1 ratings_NN2 (_( Flannery_NP1 ,_, Houston_NP1 ,_, &;_NULL Partnoy_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
It_PPH1 is_VBZ a_AT1 well-known_JJ fact_NN1 that_CST competition_NN1 is_VBZ good_JJ for_IF the_AT consumer_NN1 ._. 
</s>
<s>
Competition_NN1 drives_VVZ down_RP the_AT prices_NN2 ,_, accelerates_VVZ the_AT technological_JJ progress_NN1 and_CC creates_VVZ additional_JJ value_NN1 to_II the_AT consumer_NN1 ._. 
</s>
<s>
Same_DA goes_VVZ for_IF credit_NN1 ratings_NN2 ._. 
</s>
<s>
If_CS there_EX were_VBDR more_DAR rating_NN1 agencies_NN2 ,_, one_PN1 could_VM argue_VVI that_CST the_AT ratings_NN2 would_VM be_VBI more_RGR accurate_JJ ,_, they_PPHS2 would_VM reflect_VVI all_DB new_JJ information_NN1 faster_RRR and_CC they_PPHS2 would_VM be_VBI more_RGR foreseeing_JJ ._. 
</s>
<s>
In_II todays_NN2 world_NN1 credit_NN1 ratings_NN2 have_VH0 been_VBN criticized_VVN to_TO be_VBI more_RGR retrospective_JJ than_CSN foreseeing_VVG and_CC they_PPHS2 do_VD0 n't_XX portray_VVI the_AT expected_JJ returns_NN2 of_IO assets_NN2 accurately_RR ._. 
</s>
<s>
It_PPH1 can_VM also_RR be_VBI said_VVN that_CST the_AT informational_JJ value_NN1 of_IO the_AT credit_NN1 ratings_NN2 have_VH0 declined_VVN over_II time_NNT1 since_CS the_AT 1970s_MC2 ,_, thanks_NN2 to_II constantly_RR developing_VVG financial_JJ markets_NN2 (_( Flannery_NP1 ,_, Houston_NP1 ,_, &;_NULL Partnoy_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
Another_DD1 problem_NN1 with_IW credit_NN1 ratings_NN2 lies_VVZ in_II the_AT fact_NN1 that_CST the_AT issuer_NN1 of_IO the_AT asset_NN1 pays_VVZ for_IF the_AT credit_NN1 rating_NN1 ._. 
</s>
<s>
If_CS the_AT issuer_NN1 of_IO an_AT1 asset_NN1 wants_VVZ to_TO get_VVI the_AT asset_NN1 sold_VVN in_RP today_RT 's_GE world_NN1 the_AT asset_NN1 has_VHZ to_TO have_VHI a_AT1 credit_NN1 rating_NN1 ._. 
</s>
<s>
If_CS the_AT issuer_NN1 opts_VVZ to_TO not_XX go_VVI for_IF a_AT1 credit_NN1 rating_VVG the_AT market_NN1 will_VM deem_VVI the_AT asset_NN1 as_CSA junk_NN1 ,_, because_CS why_RRQ would_VM any_DD creditworthy_JJ asset_NN1 not_XX have_VH0 a_AT1 credit_NN1 rating_NN1 ._. 
</s>
<s>
This_DD1 principal-agent_JJ relationship_NN1 creates_VVZ twisted_JJ incentives_NN2 for_IF the_AT rating_NN1 agencies_NN2 ._. 
</s>
<s>
The_AT issuer_NN1 wants_VVZ the_AT best_JJT possible_JJ rating_NN1 for_IF the_AT asset_NN1 and_CC the_AT rating_NN1 agency_NN1 does_VDZ not_XX want_VVI to_TO have_VHI any_DD unhappy_JJ customers_NN2 ._. 
</s>
<s>
So_RR the_AT result_NN1 is_VBZ that_CST the_AT asset_NN1 gets_VVZ a_AT1 higher_JJR rating_NN1 than_CSN it_PPH1 truly_RR would_VM deserve_VVI (_( Flannery_NP1 ,_, Houston_NP1 ,_, &;_NULL Partnoy_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
This_DD1 incentive_NN1 problem_NN1 raises_VVZ the_AT question_NN1 of_IO who_PNQS should_VM provide_VVI the_AT credit_NN1 ratings_NN2 ._. 
</s>
<s>
The_AT existence_NN1 of_IO credit_NN1 rating_NN1 agencies_NN2 is_VBZ well_RR justified_VVN ,_, but_CCB it_PPH1 could_VM be_VBI a_AT1 more_RGR socially_RR optimal_JJ solution_NN1 if_CS the_AT ratings_NN2 would_VM be_VBI provided_VVN by_II a_AT1 unbiased_JJ third_MD party_NN1 ,_, for_REX21 example_REX22 the_AT department_NN1 of_IO finance_NN1 or_CC the_AT central_JJ bank_NN1 (_( Partnoy_NP1 ,_, 1999_MC )_) ._. 
</s>
<s>
Even_CS21 though_CS22 credit_NN1 ratings_NN2 have_VH0 received_VVN a_AT1 lot_NN1 of_IO criticism_NN1 there_EX has_VHZ not_XX been_VBN a_AT1 replacing_VVG mechanism_NN1 ._. 
</s>
<s>
In_II the_AT next_MD chapter_NN1 I_PPIS1 will_VM present_VVI one_MC1 option_NN1 ._. 
</s>
<s>
Credit_NN1 spreads_VVZ In_II the_AT following_JJ part_NN1 I_PPIS1 will_VM concentrate_VVI on_II credit_NN1 spreads_VVZ ._. 
</s>
<s>
Credit_NN1 spreads_VVZ are_VBR an_AT1 option_NN1 for_IF credit_NN1 ratings_NN2 because_CS they_PPHS2 reflect_VV0 the_AT risk_NN1 premium_NN1 that_CST the_AT market_NN1 requires_VVZ to_TO invest_VVI in_II an_AT1 asset_NN1 ._. 
</s>
<s>
The_AT so_JJ21 called_JJ22 credit_NN1 spread_NN1 is_VBZ the_AT difference_NN1 in_II yields_NN2 between_II an_AT1 asset_NN1 and_CC a_AT1 risk-free_JJ asset_NN1 ._. 
</s>
<s>
Credit_NN1 spreads_VVZ could_VM be_VBI measured_VVN from_II either_DD1 government_NN1 bonds_NN2 ,_, municipal_JJ bonds_NN2 or_CC other_JJ debt_NN1 assets_NN2 ._. 
</s>
<s>
One_PN1 could_VM also_RR look_VVI at_II the_AT credit_NN1 spreads_VVZ of_IO CDS_NN2 contracts_VVZ to_TO determine_VVI the_AT riskiness_NN1 of_IO an_AT1 asset_NN1 ._. 
</s>
<s>
The_AT biggest_JJT strength_NN1 of_IO the_AT credit_NN1 spread_VVN as_II a_AT1 rating_NN1 is_VBZ that_CST it_PPH1 is_VBZ determined_VVN by_II the_AT market_NN1 ._. 
</s>
<s>
This_DD1 means_VVZ in_II theory_NN1 that_CST it_PPH1 should_VM reflect_VVI all_DB the_AT information_NN1 that_CST is_VBZ available_JJ and_CC the_AT asset_NN1 should_VM be_VBI correctly_RR priced_VVN ._. 
</s>
<s>
Credit_NN1 spreads_VVZ also_RR react_VV0 faster_RRR to_II new_JJ information_NN1 than_CSN traditional_JJ credit_NN1 ratings_NN2 ;_; this_DD1 on_II the_AT other_JJ hand_NN1 means_VVZ that_CST they_PPHS2 reflect_VV0 the_AT future_NN1 better_RRR than_CSN credit_NN1 ratings_NN2 ._. 
</s>
<s>
These_DD2 findings_NN2 support_VV0 the_AT hypothesis_NN1 that_CST credit_NN1 spreads_VVZ are_VBR more_RGR accurate_JJ measures_NN2 of_IO risk_NN1 than_CSN credit_NN1 ratings_NN2 (_( Flannery_NP1 ,_, Houston_NP1 ,_, &;_NULL Partnoy_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
A_AT1 weakness_NN1 of_IO credit_NN1 spreads_VVZ as_II a_AT1 substitute_NN1 for_IF ratings_NN2 is_VBZ that_CST there_EX are_VBR no_AT actual_JJ grades_NN2 or_CC guidelines_NN2 ._. 
</s>
<s>
For_REX21 example_REX22 ,_, if_CS a_AT1 bond_NN1 is_VBZ graded_VVN AAA_NP1 or_CC BB-_NN1 what_DDQ is_VBZ the_AT corresponding_JJ credit_NN1 spread_NN1 ?_? 
</s>
<s>
When_CS dealing_VVG with_IW credit_NN1 ratings_NN2 ,_, the_AT investor_NN1 can_VM straight_RR21 away_RR22 see_VVI in_II what_DDQ ballpark_VV0 the_AT asset_NN1 is_VBZ by_II looking_VVG at_II the_AT rating_NN1 ,_, the_AT case_NN1 is_VBZ not_XX as_RG clear_JJ with_IW the_AT credit_NN1 spreads_VVZ (_( Flannery_NP1 ,_, Houston_NP1 ,_, &;_NULL Partnoy_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
Credit_NN1 spreads_VVZ compared_VVN to_II credit_NN1 ratings_NN2 In_II this_DD1 chapter_NN1 I_PPIS1 will_VM make_VVI a_AT1 comparison_NN1 between_II credit_NN1 ratings_NN2 and_CC credit_NN1 ratings_NN2 ._. 
</s>
<s>
If_CS we_PPIS2 start_VV0 with_IW a_AT1 comparison_NN1 which_DDQ on_II is_VBZ more_RGR accurate_JJ the_AT winner_NN1 is_VBZ the_AT credit_NN1 spread_NN1 based_VVN method_NN1 ._. 
</s>
<s>
The_AT credit_NN1 ratings_NN2 can_VM be_VBI viewed_VVN as_CSA stale_JJ and_CC they_PPHS2 are_VBR expected_VVN to_TO predict_VVI the_AT performance_NN1 of_IO the_AT bond_NN1 in_II the_AT near_JJ future_NN1 ._. 
</s>
<s>
Credit_NN1 spreads_VVZ on_II the_AT other_JJ hand_NN1 are_VBR determined_VVN daily_RR and_CC they_PPHS2 showcase_NN1 all_DB the_AT latest_JJT information_NN1 and_CC future_JJ views_NN2 (_( Partnoy_NP1 ,_, 1999_MC )_) ._. 
</s>
<s>
The_AT method_NN1 of_IO using_VVG credit_NN1 spreads_VVZ as_CSA ratings_NN2 is_VBZ not_XX very_RG well_RR known_VVN ,_, credit_NN1 rating_NN1 is_VBZ on_II the_AT other_JJ hand_NN1 an_AT1 expression_NN1 that_CST everybody_PN1 are_VBR familiar_JJ with_IW ._. 
</s>
<s>
Credit_NN1 ratings_NN2 are_VBR also_RR more_RGR easily_RR read_VVN compared_VVN to_II the_AT spreads_NN2 ._. 
</s>
<s>
Investors_NN2 that_CST do_VD0 not_XX have_VHI the_AT time_NNT1 or_CC the_AT knowledge_NN1 to_TO examine_VVI and_CC compare_VVI the_AT spreads_NN2 of_IO different_JJ bonds_NN2 and_CC assets_NN2 ,_, can_VM have_VHI a_AT1 hard_JJ time_NNT1 figuring_VVG out_RP the_AT different_JJ investment_NN1 grades_NN2 just_RR by_II looking_VVG at_II the_AT credit_NN1 spread_NN1 ._. 
</s>
<s>
Credit_NN1 ratings_NN2 give_VV0 this_DD1 information_NN1 right_NN1 away_RL ._. 
</s>
<s>
This_DD1 is_VBZ also_RR one_MC1 of_IO the_AT factors_NN2 ,_, which_DDQ have_VH0 helped_VVN the_AT credit_NN1 ratings_NN2 and_CC the_AT rating_NN1 agencies_NN2 to_TO achieve_VVI their_APPGE almost_RR legendary_JJ status_NN1 (_( Flannery_NP1 ,_, Houston_NP1 ,_, &;_NULL Partnoy_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
If_CS we_PPIS2 look_VV0 at_II ratings_NN2 from_II the_AT perspective_NN1 of_IO asymmetric_JJ information_NN1 ,_, we_PPIS2 find_VV0 that_DD1 credit_NN1 spreads_VVZ are_VBR clearly_RR the_AT superior_JJ rating_NN1 method_NN1 compared_VVN to_II the_AT traditional_JJ ratings_NN2 ._. 
</s>
<s>
Asymmetric_JJ information_NN1 means_VVZ that_CST one_MC1 party_NN1 possess_VV0 more_DAR information_NN1 than_CSN another_DD1 party_NN1 ,_, this_DD1 can_VM lead_VVI to_II situations_NN2 where_RRQ the_AT better_JJR informed_JJ party_NN1 takes_VVZ advantage_NN1 of_IO the_AT less_RGR informed_JJ one_PN1 ._. 
</s>
<s>
In_II the_AT case_NN1 of_IO credit_NN1 ratings_NN2 this_DD1 can_VM be_VBI applied_VVN to_II issues_NN2 of_IO new_JJ bonds_NN2 ._. 
</s>
<s>
Nowadays_RT it_PPH1 is_VBZ a_AT1 necessity_NN1 for_IF a_AT1 bond_NN1 to_TO have_VHI some_DD sort_NN1 of_IO credit_NN1 rating_NN1 ,_, if_CS the_AT issuer_NN1 wants_VVZ the_AT bond_NN1 to_TO be_VBI liquid_JJ and_CC attractive_JJ to_II investors_NN2 (_( Partnoy_NP1 ,_, 1999_MC )_) ._. 
</s>
<s>
What_DDQ the_AT issuer_NN1 does_VDZ is_VBZ that_CST they_PPHS2 hire_VV0 a_AT1 rating_NN1 agency_NN1 to_TO provide_VVI a_AT1 rating_NN1 for_IF the_AT bond_NN1 ,_, and_CC because_CS the_AT issuer_NN1 pays_VVZ for_IF the_AT rating_NN1 ,_, they_PPHS2 receive_VV0 a_AT1 higher_JJR rating_NN1 than_CSN they_PPHS2 should_VM ._. 
</s>
<s>
This_DD1 dilemma_NN1 shows_VVZ how_RRQ the_AT principal-agent_JJ relationship_NN1 between_II the_AT issuers_NN2 and_CC the_AT rating_NN1 agencies_NN2 give_VV0 false_JJ information_NN1 to_II the_AT market_NN1 ._. 
</s>
<s>
Credit_NN1 spreads_VVZ on_II the_AT other_JJ do_VD0 not_XX suffer_VVI from_II this_DD1 principal-agent_JJ relationship_NN1 ,_, because_CS the_AT spreads_NN2 are_VBR determined_VVN by_II the_AT markets_NN2 (_( Flannery_NP1 ,_, Houston_NP1 ,_, &;_NULL Partnoy_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
Another_DD1 big_JJ advantage_NN1 that_CST credit_NN1 spreads_NN2 have_VH0 over_II credit_NN1 ratings_NN2 is_VBZ the_AT fact_NN1 they_PPHS2 are_VBR determined_VVN by_II the_AT market_NN1 ,_, which_DDQ means_VVZ that_CST there_EX are_VBR thousands_NNO2 and_CC thousands_NNO2 of_IO investors_NN2 who_PNQS make_VV0 sure_JJ that_CST all_DB information_NN1 is_VBZ reflected_VVN in_II the_AT spreads_NN2 ._. 
</s>
<s>
There_EX are_VBR only_RR three_MC NFSO-licensed_JJ rating_NN1 agencies_NN2 in_II the_AT world_NN1 ,_, which_DDQ give_VV0 all_DB of_IO them_PPHO2 huge_JJ market_NN1 power_NN1 and_CC they_PPHS2 can_VM extract_VVI economic_JJ rents_NN2 without_IW the_AT fear_NN1 that_CST some_DD other_JJ competitor_NN1 steps_VVZ in_RP and_CC starts_VVZ grinding_VVG down_RP on_II the_AT profit_NN1 of_IO the_AT rest_NN1 ._. 
</s>
<s>
This_DD1 lack_NN1 of_IO competition_NN1 does_VDZ not_XX provide_VVI enough_DD incentives_NN2 for_IF rating_VVG agencies_NN2 to_TO constantly_RR monitor_VVI and_CC develop_VVI their_APPGE rating_NN1 methods_NN2 (_( Flannery_NP1 ,_, Houston_NP1 ,_, &;_NULL Partnoy_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
Discussion_NN1 Credit_NN1 ratings_NN2 have_VH0 met_VVN some_DD strong_JJ opposition_NN1 from_II the_AT public_NN1 during_II the_AT recent_JJ financial_JJ crisis_NN1 ._. 
</s>
<s>
The_AT failure_NN1 of_IO recognizing_VVG the_AT underlying_JJ risk_NN1 in_II both_DB2 the_AT sub-prime_JJ mortgages_NN2 and_CC some_DD sovereign_JJ bonds_NN2 has_VHZ raised_VVN the_AT discussion_NN1 ,_, what_DDQ credit_VV0 ratings_NN2 are_VBR actually_RR good_JJ for_IF ._. 
</s>
<s>
If_CS the_AT credit_NN1 rating_NN1 does_VDZ not_XX reflect_VVI the_AT true_JJ expectations_NN2 of_IO the_AT bonds_NN2 performance_NN1 ,_, then_RT why_RRQ do_VD0 they_PPHS2 have_VHI such_DA a_AT1 great_JJ weight_NN1 ?_? 
</s>
<s>
The_AT main_JJ problem_NN1 in_II my_APPGE opinion_NN1 is_VBZ that_CST there_EX are_VBR too_RG few_DA2 rating_NN1 agencies_NN2 ._. 
</s>
<s>
The_AT market_NN1 based_VVN solution_NN1 is_VBZ often_RR the_AT most_RGT efficient_JJ one_PN1 in_II my_APPGE opinion_NN1 ._. 
</s>
<s>
A_AT1 good_JJ example_NN1 for_IF this_DD1 claim_NN1 is_VBZ to_TO look_VVI at_II the_AT failure_NN1 of_IO communism_NN1 ._. 
</s>
<s>
Everything_PN1 was_VBDZ regulated_VVN in_II the_AT Soviet_JJ Union_NN1 ,_, which_DDQ created_VVD twisted_JJ incentives_NN2 ._. 
</s>
<s>
If_CS the_AT ratings_NN2 would_VM be_VBI provided_VVN by_II the_AT credit_NN1 spreads_VVZ ,_, then_RT the_AT markets_NN2 would_VM probably_RR give_VVI the_AT best_JJT solution_NN1 ._. 
</s>
<s>
This_DD1 solution_NN1 is_VBZ not_XX perfect_JJ ,_, because_CS the_AT markets_NN2 are_VBR also_RR wrong_JJ from_RR41 time_RR42 to_RR43 time_RR44 ,_, but_CCB I_PPIS1 think_VV0 they_PPHS2 would_VM still_RR do_VDI a_AT1 better_JJR job_NN1 than_CSN the_AT rating_NN1 agencies_NN2 ._. 
</s>
<s>
Another_DD1 solution_NN1 would_VM also_RR be_VBI to_TO provide_VVI more_DAR licenses_NN2 to_II firms_NN2 ,_, that_CST want_VV0 to_TO get_VVI into_II the_AT rating_NN1 business_NN1 ,_, but_CCB it_PPH1 takes_VVZ time_NNT1 to_TO build_VVI a_AT1 credible_JJ reputation_NN1 ._. 
</s>
<s>
To_TO provide_VVI more_DAR NFSO-licenses_NN2 would_VM also_RR be_VBI pretty_RG tough_JJ ,_, because_CS the_AT financial_JJ regulation_NN1 would_VM have_VHI to_TO change_VVI and_CC the_AT three_MC big_JJ agencies_NN2 would_VM oppose_VVI this_DD1 regulation_NN1 with_IW all_DB their_APPGE might_NN1 (_( Partnoy_NP1 ,_, 1999_MC )_) ._. 
</s>
<s>
The_AT regulation_NN1 of_IO the_AT financial_JJ markets_NN2 has_VHZ been_VBN a_AT1 hot_JJ topic_NN1 after_II the_AT financial_JJ crisis_NN1 ,_, but_CCB there_EX has_VHZ not_XX been_VBN much_DA1 discussion_NN1 of_IO the_AT regulation_NN1 of_IO rating_VVG agencies_NN2 ._. 
</s>
<s>
I_PPIS1 think_VV0 that_CST this_DD1 is_VBZ a_AT1 issue_NN1 that_CST the_AT governments_NN2 have_VH0 to_TO tackle_VVI eventually_RR ._. 
</s>
<s>
The_AT European_JJ Union_NN1 has_VHZ proposed_VVN some_DD reform_NN1 propositions_NN2 ,_, but_CCB they_PPHS2 have_VH0 not_XX been_VBN implemented_VVN yet_RR ._. 
</s>
<s>
This_DD1 reforms_VVZ have_VH0 naturally_RR received_VVN an_AT1 ice_NN1 cold_NN1 welcoming_VVG from_II the_AT rating_NN1 agencies_NN2 ,_, and_CC the_AT big_JJ three_MC will_VM surely_RR object_VVI to_II any_DD regulations_NN2 that_CST will_VM limit_VVI their_APPGE business_NN1 (_( FT.com_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
The_AT inaccuracy_NN1 of_IO the_AT credit_NN1 ratings_NN2 is_VBZ a_AT1 side-product_NN1 of_IO the_AT lack_NN1 of_IO competition_NN1 and_CC the_AT twisted_JJ incentives_NN2 that_CST the_AT rating_NN1 agencies_NN2 have_VH0 ._. 
</s>
<s>
Competition_NN1 forces_NN2 firms_NN2 to_II better_RRR their_APPGE product_NN1 ,_, and_CC I_PPIS1 think_VV0 the_AT case_NN1 would_VM be_VBI the_AT same_DA with_IW credit_NN1 ratings_NN2 ._. 
</s>
<s>
The_AT main_JJ problem_NN1 with_IW using_VVG credit_NN1 spreads_VVZ as_CSA ratings_NN2 is_VBZ determining_VVG the_AT different_JJ grades_NN2 of_IO the_AT assets_NN2 ._. 
</s>
<s>
I_PPIS1 so_RR not_XX see_VV0 this_DD1 as_II a_AT1 problem_NN1 ._. 
</s>
<s>
One_PN1 could_VM use_VVI historical_JJ data_NN to_TO research_VVI how_RGQ different_JJ bonds_NN2 have_VH0 performed_VVN and_CC on_II basis_NN1 of_IO this_DD1 research_NN1 create_VV0 a_AT1 table_NN1 with_IW different_JJ grades_NN2 ._. 
</s>
<s>
For_REX21 example_REX22 ,_, every_AT1 asset_NN1 with_IW a_AT1 spread_NN1 less_DAR than_CSN 25_MC basis_NN1 points_NN2 would_VM be_VBI equivalent_JJ to_II a_AT1 Triple-A_JJ bond_NN1 ,_, and_CC a_AT1 bond_NN1 with_IW a_AT1 spread_NN1 of_IO 25_MC to_II 50_MC basis_NN1 points_NN2 would_VM equal_VVI a_AT1 rating_NN1 of_IO AAA-_NN1 and_CC etc_RA ._. 
</s>
<s>
A_AT1 table_NN1 like_II this_DD1 is_VBZ proposed_VVN by_II (_( Partnoy_NP1 ,_, 1999_MC )_) ._. 
</s>
<s>
Conclusions_NN2 Credit_VV0 ratings_NN2 have_VH0 been_VBN under_RG strong_JJ criticism_NN1 during_II the_AT recent_JJ years_NNT2 ._. 
</s>
<s>
Some_DD of_IO the_AT wrong_JJ and_CC questionable_JJ decisions_NN2 that_CST the_AT rating_NN1 agencies_NN2 made_VVN during_II the_AT latest_JJT financial_JJ crisis_NN1 have_VH0 strongly_RR undermined_VVN the_AT authority_NN1 of_IO these_DD2 firms_NN2 ._. 
</s>
<s>
Even_CS21 though_CS22 the_AT informational_JJ value_NN1 of_IO credit_NN1 ratings_NN2 have_VH0 been_VBN decreasing_VVG since_II the_AT 1970s_MC2 (_( Partnoy_NP1 ,_, 1999_MC )_) ,_, there_EX has_VHZ not_XX really_RR been_VBN any_DD subsitutes_NN2 that_CST would_VM have_VHI challenged_VVN the_AT position_NN1 of_IO the_AT traditional_JJ ratings_NN2 ._. 
</s>
<s>
This_DD1 is_VBZ also_RR a_AT1 sign_NN1 of_IO the_AT market_NN1 power_NN1 that_CST the_AT rating_NN1 agenicies_NN2 possess_VV0 ._. 
</s>
<s>
The_AT rating_NN1 agencies_NN2 have_VH0 succeeded_VVN in_II making_VVG them_PPHO2 unexpendable_JJ ._. 
</s>
<s>
They_PPHS2 have_VH0 also_RR managed_VVN to_TO prevent_VVI the_AT de-regulation_NN1 of_IO the_AT credit_NN1 rating_NN1 market_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ also_RR a_AT1 point_NN1 where_RRQ the_AT governments_NN2 should_VM step_VVI in_RP ._. 
</s>
<s>
There_EX has_VHZ been_VBN musch_NN1 discussion_NN1 after_II the_AT crisis_NN1 of_IO how_RRQ the_AT financial_JJ markets_NN2 should_VM be_VBI regulated_VVN to_TO prevent_VVI catastrophes_NN2 like_II the_AT one_PN1 we_PPIS2 saw_VVD in_II the_AT fall_NN1 of_IO 2008_MC ._. 
</s>
<s>
But_CCB there_EX has_VHZ not_XX been_VBN much_DA1 discussion_NN1 of_IO how_RRQ rating_NN1 agencies_NN2 should_VM be_VBI regulated_VVN ._. 
</s>
<s>
This_DD1 paper_NN1 has_VHZ researched_VVN the_AT possibility_NN1 of_IO using_VVG a_AT1 credit_NN1 spread_NN1 based_VVN mechanism_NN1 to_II rate_NN1 financial_JJ instruments_NN2 ._. 
</s>
<s>
The_AT credit_NN1 spreads_VVZ would_VM provide_VVI a_AT1 market-based_JJ solution_NN1 to_II the_AT rating-dilemma_NN1 ,_, and_CC markets_NN2 have_VH0 historically_RR provided_VVN the_AT most_RGT efficient_JJ solution_NN1 ._. 
</s>
<s>
Credit_NN1 spreads_NN2 have_VH0 been_VBN shown_VVN to_TO react_VVI faster_RRR to_II new_JJ information_NN1 than_CSN credit_NN1 ratings_NN2 ._. 
</s>
<s>
One_MC1 reason_NN1 for_IF this_DD1 is_VBZ that_CST the_AT credit_NN1 spreads_VVZ are_VBR evalueated_VVN daily_RR ,_, when_CS credit_NN1 spreads_NN2 do_VD0 not_XX change_VVI that_CST often_RR ,_, if_CS there_EX are_VBR not_XX any_DD drastic_JJ news_NN1 ._. 
</s>
<s>
Credit_NN1 spreads_NN2 have_VH0 also_RR been_VBN shown_VVN to_TO predict_VVI the_AT future_NN1 better_RRR than_CSN the_AT traditional_JJ ratings_NN2 ._. 
</s>
<s>
I_PPIS1 would_VM propose_VVI for_IF future_JJ research_NN1 ,_, a_AT1 paper_NN1 where_CS the_AT the_AT credit_NN1 spreads_VVZ would_VM be_VBI graded_VVN ._. 
</s>
<s>
What_DDQ I_PPIS1 mean_VV0 by_II this_DD1 is_VBZ that_DD1 credit_NN1 spreads_VVZ of_IO different_JJ sizes_NN2 would_VM receive_VVI their_APPGE own_DA grade_NN1 ,_, this_DD1 would_VM help_VVI the_AT investors_NN2 to_TO easily_RR determine_VVI ,_, which_DDQ bonds_VVZ to_TO buy_VVI or_CC sell_VVI ._. 
</s>
