<s>
Internal_JJ auditing_NN1 within_II municipal_JJ organizations_NN2 :_: From_II the_AT perspective_NN1 of_IO internal_JJ auditors_NN2 Introduction_NN1 Internal_JJ auditing_NN1 has_VHZ ever_RR since_CS World_NN1 War_NN1 II_MC been_VBN a_AT1 part_NN1 of_IO almost_RR every_AT1 larger_JJR business_NN1 ,_, but_CCB recently_RR it_PPH1 has_VHZ become_VVN a_AT1 necessity_NN1 and_CC an_AT1 essential_JJ activity_NN1 in_II different_JJ organizations_NN2 around_II the_AT world_NN1 (_( Burnaby_NP1 ,_, 2009_MC )_) ._. 
</s>
<s>
Internal_JJ auditing_NN1 can_VM be_VBI dated_VVN as_CSA far_JJ back_NN1 as_CSA 4000_MC B.C._RA to_II the_AT Near_JJ East_ND1 ,_, when_CS organized_JJ businesses_NN2 and_CC governments_NN2 started_VVD to_TO implement_VVI formal_JJ record-keeping_NN1 systems_NN2 in_II order_NN1 to_TO correctly_RR account_VVI for_IF collected_JJ taxes_NN2 (_( Ramamoorti_NP1 ,_, 2003_MC )_) ._. 
</s>
<s>
Richard_NP1 Brown_NP1 (_( 1905_MC ,_, quoted_VVN in_II Ramamoorti_NP1 ,_, 2003_MC )_) stated_VVD that_CST the_AT roots_NN2 of_IO auditing_NN1 were_VBDR born_VVN when_CS the_AT advance_NN1 of_IO civilization_NN1 brought_VVD about_RP the_AT necessity_NN1 of_IO one_MC1 man_NN1 being_VBG intrusted_VVN to_II some_DD extent_NN1 with_IW the_AT property_NN1 of_IO another_DD1 ,_, the_AT advisability_NN1 of_IO some_DD kind_NN1 of_IO check_NN1 upon_II the_AT fidelity_NN1 of_IO the_AT former_DA would_VM become_VVI apparent._NNU The_AT internal_JJ auditing_NN1 methods_NN2 of_IO today_RT really_RR started_VVD to_TO evolve_VVI during_II and_CC after_CS the_AT World_NN1 War_NN1 II_MC ,_, when_CS The_AT Institute_NN1 of_IO Internal_JJ Auditors_NN2 (_( IIA_NP1 )_) was_VBDZ founded_VVN in_II 1941_MC (_( Ramamoorti_NP1 ,_, 2003_MC )_) ._. 
</s>
<s>
Internal_JJ auditing_NN1 is_VBZ commonly_RR understood_VVN as_II an_AT1 entity_NN1 within_II a_AT1 business_NN1 ,_, with_IW a_AT1 purpose_NN1 to_TO analyze_VVI the_AT financial_JJ statements_NN2 and_CC give_VVI the_AT management_NN1 detailed_JJ evaluations_NN2 and_CC proposals_NN2 for_IF improvement_NN1 regarding_II risk_NN1 management_NN1 ,_, control_NN1 ,_, and_CC governance_NN1 processes_NN2 ._. 
</s>
<s>
The_AT information_NN1 that_CST internal_JJ auditors_NN2 can_VM produce_VVI can_VM be_VBI of_IO great_JJ importance_NN1 to_II a_AT1 company_NN1 and_CC its_APPGE future_NN1 ,_, as_CS31 long_CS32 as_CS33 the_AT management_NN1 understands_VVZ to_TO take_VVI the_AT information_NN1 under_II consideration_NN1 ._. 
</s>
<s>
However_RR ,_, if_CS the_AT internal_JJ auditing_NN1 isnt_NN1 operated_VVN effectively_RR it_PPH1 might_VM not_XX have_VHI any_DD value_NN1 to_II the_AT organization_NN1 ._. 
</s>
<s>
Studies_NN2 by_II Rainer_NP1 (_( 2012_MC )_) ,_, concerning_VVG the_AT importance_NN1 of_IO the_AT internal_JJ auditors_NN2 ,_, suggest_VV0 that_CST internal_JJ auditing_NN1 ,_, as_CSA a_AT1 profession_NN1 ,_, has_VHZ been_VBN wrongfully_RR diminished_VVN when_CS the_AT debate_NN1 regarding_II the_AT financial_JJ crisis_NN1 has_VHZ been_VBN on_RP ._. 
</s>
<s>
Rainer_NP1 also_RR states_VVZ that_CST recently_RR the_AT value_NN1 of_IO the_AT internal_JJ auditing_NN1 has_VHZ started_VVN to_TO be_VBI questioned_VVN ._. 
</s>
<s>
Kapoor_NP1 (_( 2012_MC )_) is_VBZ in_II the_AT other_JJ hand_NN1 stating_VVG that_CST the_AT profession_NN1 of_IO internal_JJ auditing_NN1 is_VBZ under_II transformation_NN1 ._. 
</s>
<s>
This_DD1 development_NN1 of_IO internal_JJ auditing_NN1 has_VHZ been_VBN caused_VVN by_II the_AT increased_JJ complexity_NN1 of_IO a_AT1 global_JJ market_NN1 ,_, corruption_NN1 ,_, fraud_NN1 ,_, and_CC new_JJ laws_NN2 and_CC regulations_NN2 ._. 
</s>
<s>
Even_CS21 if_CS22 there_EX have_VH0 been_VBN several_DA2 studies_NN2 made_VVN about_II the_AT internal_JJ auditing_NN1 as_II a_AT1 profession_NN1 and_CC its_APPGE importance_NN1 ,_, few_DA2 of_IO these_DD2 studies_NN2 have_VH0 been_VBN made_VVN as_II a_AT1 case_NN1 study_NN1 from_II the_AT perspective_NN1 of_IO an_AT1 internal_JJ auditor_NN1 and_CC about_II internal_JJ auditing_NN1 in_II a_AT1 municipal_JJ organization_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ why_RRQ the_AT question_NN1 still_RR stands_VVZ concerning_II how_RGQ internal_JJ auditing_NN1 is_VBZ viewed_VVN at_II by_II those_DD2 working_VVG with_IW the_AT profession_NN1 ._. 
</s>
<s>
This_DD1 study_NN1 focuses_VVZ on_II presenting_VVG the_AT profession_NN1 of_IO internal_JJ auditors_NN2 and_CC the_AT internal_JJ auditing_NN1 process_NN1 ._. 
</s>
<s>
The_AT empirical_JJ part_NN1 of_IO this_DD1 study_NN1 concentrates_VVZ on_II presenting_VVG how_RGQ internal_JJ auditing_NN1 is_VBZ viewed_VVN at_II by_II the_AT internal_JJ auditors_NN2 ,_, and_CC to_TO be_VBI precise_JJ ,_, by_II the_AT chief_JJ auditing_NN1 executives_NN2 in_II municipal_JJ organizations_NN2 ._. 
</s>
<s>
The_AT theoretical_JJ part_NN1 of_IO this_DD1 study_NN1 presents_VVZ internal_JJ auditing_NN1 ,_, what_DDQ it_PPH1 exactly_RR is_VBZ ,_, what_DDQ benefits_NN2 it_PPH1 can_VM have_VHI ,_, what_DDQ risks_VVZ that_CST might_VM interfere_VVI with_IW the_AT auditing_NN1 process_NN1 ,_, and_CC what_DDQ kind_NN1 of_IO characteristics_NN2 an_AT1 internal_JJ auditor_NN1 should_VM or_CC might_VM possess_VVI ._. 
</s>
<s>
The_AT aim_NN1 of_IO this_DD1 study_NN1 is_VBZ to_TO examine_VVI whether_CSW31 or_CSW32 not_CSW33 there_EX is_VBZ a_AT1 difference_NN1 between_II the_AT internal_JJ auditing_NN1 process_NN1 within_II municipal_JJ organizations_NN2 and_CC what_DDQ have_VH0 been_VBN presented_VVN in_II the_AT theoretical_JJ part_NN1 regarding_II internal_JJ auditing_NN1 ._. 
</s>
<s>
This_DD1 paper_NN1 is_VBZ structured_VVN into_II five_MC sections_NN2 of_IO which_DDQ the_AT introduction_NN1 is_VBZ the_AT first_MD ._. 
</s>
<s>
The_AT second_MD section_NN1 will_VM present_VVI the_AT theoretical_JJ aspects_NN2 concerning_II internal_JJ auditing_NN1 ,_, how_RRQ it_PPH1 is_VBZ performed_VVN ,_, what_DDQ the_AT benefits_NN2 and_CC risks_NN2 are_VBR ,_, and_CC what_DDQ describes_VVZ a_AT1 good_JJ internal_JJ auditor_NN1 ._. 
</s>
<s>
The_AT third_MD section_NN1 will_VM present_VVI the_AT data_NN collection_NN1 method_NN1 ._. 
</s>
<s>
This_DD1 section_NN1 will_VM give_VVI information_NN1 on_II the_AT used_JJ research_NN1 methods_NN2 and_CC why_RRQ these_DD2 methods_NN2 have_VH0 been_VBN chosen_VVN ._. 
</s>
<s>
The_AT fourth_MD section_NN1 will_VM introduce_VVI the_AT results_NN2 of_IO the_AT research_NN1 ._. 
</s>
<s>
The_AT last_MD section_NN1 will_VM discuss_VVI the_AT conclusions_NN2 of_IO the_AT results_NN2 and_CC present_JJ possible_JJ need_NN1 for_IF future_JJ researches_NN2 ._. 
</s>
<s>
Literature_NN1 review_NN1 1.1_MC ._. 
</s>
<s>
Internal_JJ auditing_NN1 The_AT Institute_NN1 of_IO Internal_JJ Auditors_NN2 (_( 2004_MC )_) defines_VVZ internal_JJ auditing_NN1 as_CSA following_VVG :_: Internal_JJ Auditing_NN1 is_VBZ an_AT1 independent_JJ ,_, objective_JJ assurance_NN1 and_CC consulting_JJ activity_NN1 designed_VVN to_TO add_VVI value_NN1 and_CC improve_VVI an_AT1 organizations_NN2 operations_NN2 ._. 
</s>
<s>
It_PPH1 helps_VVZ an_AT1 organization_NN1 accomplish_VVI its_APPGE objectives_NN2 by_II bringing_VVG in_II a_AT1 systematic_JJ ,_, disciplined_JJ approach_NN1 to_TO evaluate_VVI and_CC improve_VVI the_AT effectiveness_NN1 of_IO risk_NN1 management_NN1 ,_, control_NN1 ,_, and_CC governance_NN1 processes_NN2 ._. 
</s>
<s>
The_AT Institute_NN1 of_IO Internal_JJ Auditors_NN2 provide_VV0 information_NN1 regarding_II the_AT internal_JJ audition_NN1 profession_NN1 and_CC how_RRQ it_PPH1 should_VM be_VBI performed_VVN ._. 
</s>
<s>
They_PPHS2 also_RR provide_VV0 educational_JJ and_CC development_NN1 opportunities_NN2 to_II organizations_NN2 ,_, and_CC place_VV0 standards_NN2 and_CC regulations_NN2 over_II how_RGQ internal_JJ auditing_NN1 can_VM be_VBI implemented_VVN ._. 
</s>
<s>
(_( IIA_NP1 2012_MC )_) To_TO break_VVI down_RP the_AT definition_NN1 of_IO internal_JJ auditing_NN1 we_PPIS2 need_VV0 to_TO look_VVI into_II the_AT different_JJ aspects_NN2 of_IO internal_JJ auditing_NN1 ._. 
</s>
<s>
The_AT organizational_JJ independence_NN1 of_IO internal_JJ auditing_NN1 is_VBZ essential_JJ for_IF it_PPH1 to_TO work_VVI as_RG effectively_RR as_CSA possible_JJ ,_, and_CC it_PPH1 should_VM be_VBI established_VVN by_II the_AT reporting_NN1 structure_NN1 ._. 
</s>
<s>
The_AT objectivity_NN1 of_IO internal_JJ auditing_NN1 is_VBZ accomplished_VVN with_IW a_AT1 suitable_JJ mentality_NN1 ._. 
</s>
<s>
Internal_JJ auditing_NN1 focuses_VVZ on_II analyzing_VVG risk_NN1 management_NN1 ,_, control_NN1 ,_, and_CC organizations_NN2 governance_NN1 by_II evaluating_VVG their_APPGE effectiveness_NN1 ,_, protection_NN1 of_IO assets_NN2 ,_, that_CST laws_NN2 and_CC regulations_NN2 are_VBR followed_VVN ,_, and_CC reliability_NN1 of_IO financial_JJ information_NN1 ._. 
</s>
<s>
Internal_JJ auditors_NN2 draw_VV0 conclusions_NN2 from_II the_AT obtained_VVN results_NN2 and_CC try_VV0 to_TO assess_VVI how_RRQ these_DD2 are_VBR managed_VVN in_II the_AT different_JJ areas_NN2 ._. 
</s>
<s>
In_II31 addition_II32 to_II33 the_AT above_JJ mentioned_VVD tasks_NN2 ,_, internal_JJ auditors_NN2 also_RR evaluate_VV0 values_NN2 and_CC ethics_NN inside_II the_AT organization_NN1 ,_, performance_NN1 management_NN1 ,_, and_CC how_RRQ information_NN1 regarding_II control_NN1 and_CC risks_NN2 are_VBR communicated_VVN within_II the_AT organization_NN1 ._. 
</s>
<s>
If_CS flaws_NN2 or_CC opportunities_NN2 for_IF improvement_NN1 are_VBR detected_VVN ,_, internal_JJ auditors_NN2 provide_VV0 recommendations_NN2 in_II how_RRQ to_TO materialize_VVI the_AT changes_NN2 ._. 
</s>
<s>
(_( IIA_NP1 2004_MC )_) The_AT chief_JJ audit_NN1 executive_NN1 (_( CAE_NP1 )_) is_VBZ the_AT supervisor_NN1 of_IO the_AT internal_JJ auditing_NN1 activity_NN1 ._. 
</s>
<s>
The_AT CAE_NP1 describes_VVZ the_AT range_NN1 of_IO the_AT internal_JJ auditing_NN1 activity_NN1 ,_, authority_NN1 ,_, and_CC the_AT importance_NN1 of_IO independence_NN1 for_IF the_AT audit_NN1 committee_NN1 ,_, which_DDQ either_RR approves_VVZ or_CC rejects_VVZ the_AT proposition_NN1 ._. 
</s>
<s>
(_( IIA_NP1 2004_MC )_) Internal_JJ auditing_NN1 can_VM be_VBI divided_VVN into_II two_MC levels_NN2 :_: continuous_JJ auditing_NN1 ,_, and_CC separate_JJ auditing_NN1 evaluations_NN2 ._. 
</s>
<s>
(_( Ahokas_NP1 2012_MC :_: 42_MC )_) Continuous_JJ auditing_NN1 materializes_VVZ as_II a_AT1 part_NN1 of_IO the_AT daily_JJ activities_NN2 of_IO directors_NN2 ,_, the_AT management_NN1 ,_, and_CC the_AT rest_NN1 of_IO the_AT employees_NN2 as_CSA they_PPHS2 perform_VV0 their_APPGE assignments_NN2 ._. 
</s>
<s>
Internal_JJ auditing_NN1 is_VBZ usually_RR designed_VVN to_TO include_VVI continuous_JJ auditing_NN1 operations_NN2 ,_, and_CC when_CS these_DD2 operations_NN2 are_VBR performed_VVN efficiently_RR and_CC broadly_RR the_AT need_NN1 of_IO separate_JJ evaluations_NN2 is_VBZ reduced_VVN ._. 
</s>
<s>
Continuous_JJ auditing_NN1 includes_VVZ regular_JJ guidance_NN1 measurements_NN2 ,_, comparisons_NN2 ,_, and_CC evaluations_NN2 ._. 
</s>
<s>
When_CS continuous_JJ auditing_NN1 is_VBZ included_VVN in_II the_AT recurrent_JJ operational_JJ routines_NN2 ,_, it_PPH1 will_VM perform_VVI in_II real_JJ time_NNT1 ,_, react_VV0 to_II changing_JJ circumstances_NN2 ,_, and_CC become_VV0 firmly_RR established_VVN as_II a_AT1 part_NN1 of_IO the_AT company_NN1 ._. 
</s>
<s>
(_( Ahokas_NP1 2012_MC :_: 42_MC )_) Continuous_JJ auditing_NN1 has_VHZ become_VVN a_AT1 necessity_NN1 for_IF organizations_NN2 in_BCL21 order_BCL22 to_TO improve_VVI efficiency_NN1 and_CC effectiveness_NN1 of_IO internal_JJ auditing_NN1 ._. 
</s>
<s>
This_DD1 has_VHZ been_VBN caused_VVN by_II the_AT increased_JJ organizational_JJ accountability_NN1 and_CC pressure_NN1 from_II the_AT regulatory_JJ instances_NN2 ._. 
</s>
<s>
Also_RR according_II21 to_II22 a_AT1 survey_NN1 ,_, which_DDQ was_VBDZ performed_VVN in_II 2006_MC ,_, there_EX were_VBDR experiences_NN2 of_IO fraud_NN1 in_II 75_MC %_NNU of_IO the_AT researched_VVN organizations_NN2 ._. 
</s>
<s>
These_DD2 organizations_NN2 were_VBDR either_RR large_JJ public_JJ companies_NN2 ,_, with_IW a_AT1 revenue_NN1 of_IO $250_NNU million_NNO ,_, or_CC state_NN1 and_CC federal_JJ government_NN1 agencies_NN2 ._. 
</s>
<s>
Because_II21 of_II22 increased_JJ fraud_NN1 and_CC corruption_NN1 ,_, organizations_NN2 have_VH0 started_VVN to_TO implement_VVI continuous_JJ auditing_NN1 ._. 
</s>
<s>
(_( Smith_NP1 &;_NULL Warren_NP1 2006_MC )_) Separate_JJ evaluations_NN2 are_VBR performed_VVN on_II important_JJ processes_NN2 that_CST have_VH0 been_VBN chosen_VVN in_II beforehand_RR ._. 
</s>
<s>
Usually_RR a_AT1 process_NN1 will_VM be_VBI evaluated_VVN when_CS there_EX has_VHZ been_VBN a_AT1 change_NN1 within_II its_APPGE operational_JJ environment_NN1 or_CC if_CS there_EX is_VBZ a_AT1 higher_JJR risk_NN1 focused_VVN on_II the_AT process_NN1 ,_, relatively_RR ._. 
</s>
<s>
These_DD2 evaluations_NN2 can_VM be_VBI performed_VVN on_II separate_JJ surveillance_NN1 positions_NN2 or_CC on_II the_AT whole_JJ control_NN1 system_NN1 ._. 
</s>
<s>
The_AT latter_DA is_VBZ evaluated_VVN if_CS a_AT1 significant_JJ alteration_NN1 in_II strategy_NN1 or_CC management_NN1 is_VBZ prepared_VVN ,_, or_CC if_CS a_AT1 large_JJ acquisition_NN1 is_VBZ taking_VVG place_NN1 ._. 
</s>
<s>
When_CS evaluating_VVG separate_JJ processes_NN2 ,_, weight_NN1 is_VBZ usually_RR put_VVN on_II evaluating_VVG sporadic_JJ controls_NN2 and_CC parts_NN2 of_IO the_AT process_NN1 ._. 
</s>
<s>
Evaluations_NN2 are_VBR generally_RR performed_VVN according_II21 to_II22 a_AT1 scheduled_JJ auditing_NN1 plan_NN1 ,_, but_CCB if_CS a_AT1 need_NN1 for_IF an_AT1 evaluation_NN1 arises_VVZ ,_, it_PPH1 can_VM be_VBI performed_VVN diverting_VVG from_II the_AT schedule_NN1 ._. 
</s>
<s>
(_( Ahokas_NP1 2012_MC :_: 43_MC )_) 1.2_MC ._. 
</s>
<s>
Risks_NN2 restraining_VVG internal_JJ auditing_NN1 Cronyism_NN1 and_CC favoritism_NN1 are_VBR factors_NN2 that_CST can_VM place_VVI a_AT1 risk_NN1 on_II the_AT reliability_NN1 of_IO the_AT internal_JJ auditing_NN1 reports_NN2 ,_, but_CCB also_RR on_II implementation_NN1 of_IO these_DD2 reports_NN2 ._. 
</s>
<s>
This_DD1 is_VBZ a_AT1 problem_NN1 that_CST is_VBZ more_RGR or_CC less_RRR encountered_VVN within_II family_NN1 firms_NN2 ,_, but_CCB can_VM also_RR be_VBI seen_VVN in_II other_JJ organizations_NN2 ._. 
</s>
<s>
The_AT effect_NN1 of_IO internal_JJ auditing_NN1 is_VBZ dependent_JJ on_II the_AT managements_NN2 and_CC directors_NN2 ability_NN1 to_TO implement_VVI the_AT results_NN2 that_CST internal_JJ auditors_NN2 present_NN1 ._. 
</s>
<s>
Therefore_RR favoritism_NN1 and_CC cronyism_NN1 can_VM have_VHI a_AT1 negative_JJ effect_NN1 on_II establishing_VVG of_IO businesses_NN2 and_CC managements_NN2 ability_NN1 to_TO implement_VVI internal_JJ auditing_NN1 reports_NN2 ._. 
</s>
<s>
(_( Bezirci_NP1 ,_, Keles_NP1 &;_NULL zkan_NN1 2011_MC )_) Favoritism_NN1 and_CC cronyism_NN1 ,_, caused_VVN by_II social-connections_NN2 or_CC family_NN1 ties_NN2 ,_, can_VM lead_VVI to_II recruitment_NN1 of_IO less-skilled_JJ employees_NN2 in_II wrong_JJ positions_NN2 ._. 
</s>
<s>
This_DD1 will_VM most_RGT likely_RR affect_VVI the_AT performance_NN1 of_IO the_AT firm_NN1 ,_, and_CC therefore_RR negatively_RR affect_VV0 the_AT internal_JJ auditing_NN1 ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO hide_VVI the_AT poor_JJ performance_NN1 from_II the_AT general_JJ knowledge_NN1 ,_, the_AT internal_JJ auditing_NN1 reports_NN2 might_VM be_VBI left_VVN acknowledged_JJ completely_RR ._. 
</s>
<s>
(_( Bezirci_NP1 ,_, Keles_NP1 &;_NULL zkan_NN1 2011_MC )_) According_II21 to_II22 an_AT1 interview_NN1 in_II Joris_NP1 Luyendijks_NP1 (_( 2012_MC )_) blog_NN1 can_VM internal_JJ auditing_NN1 also_RR be_VBI affected_VVN by_II uncooperation_NN1 of_IO employees_NN2 when_CS investigating_VVG errors_NN2 or_CC suspicions_NN2 of_IO fraud_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ can_VM be_VBI a_AT1 difficult_JJ problem_NN1 because_CS employees_NN2 can_VM be_VBI afraid_JJ of_IO losing_VVG their_APPGE positions_NN2 in_II the_AT company_NN1 ,_, and_CC therefore_RR try_VV0 to_TO obstruct_VVI the_AT internal_JJ auditing_NN1 by_II leaving_VVG vital_JJ information_NN1 untold_JJ ._. 
</s>
<s>
Interpersonal_JJ relations_NN2 are_VBR one_MC1 of_IO the_AT features_NN2 that_CST differentiate_VV0 internal_JJ auditing_NN1 from_II public_JJ auditing_NN1 ._. 
</s>
<s>
Internal_JJ auditing_NN1 assesses_VVZ the_AT operations_NN2 of_IO people_NN ,_, and_CC therefore_RR a_AT1 relationship_NN1 is_VBZ established_VVN between_II the_AT auditor_NN1 and_CC the_AT auditees_NN2 ._. 
</s>
<s>
This_DD1 relationship_NN1 may_VM cause_VVI conflict_NN1 between_II the_AT two_MC groups_NN2 and_CC can_VM therefore_RR be_VBI a_AT1 risk_NN1 for_IF internal_JJ auditing_NN1 ._. 
</s>
<s>
(_( Dittenhofer_VV0 1997_MC )_) Internal_JJ auditors_NN2 may_VM encounter_VVI problems_NN2 when_CS presenting_VVG the_AT results_NN2 of_IO the_AT auditing_NN1 process_NN1 to_II the_AT management_NN1 ._. 
</s>
<s>
The_AT changes_NN2 that_CST the_AT implementation_NN1 will_VM bring_VVI can_VM cause_VVI resist_VV0 within_II the_AT management_NN1 ._. 
</s>
<s>
The_AT uncertainty_NN1 is_VBZ usually_RR caused_VVN by_II fear_NN1 of_IO what_DDQ the_AT changes_NN2 might_VM bring_VVI ,_, how_RRQ the_AT changes_NN2 will_VM affect_VVI the_AT bureaucratic_JJ aspects_NN2 of_IO the_AT company_NN1 ,_, and_CC by_II the_AT ego_NN1 of_IO the_AT management_NN1 ._. 
</s>
<s>
The_AT management_NN1 might_VM not_XX be_VBI willing_JJ to_TO implement_VVI the_AT changes_NN2 because_II21 of_II22 their_APPGE egos_NN2 ._. 
</s>
<s>
(_( Dittenhofer_VV0 1997_MC )_) Benefits_NN2 of_IO internal_JJ auditing_NN1 Internal_JJ auditing_NN1 provides_VVZ the_AT management_NN1 an_AT1 understanding_NN1 of_IO the_AT organization_NN1 ,_, its_APPGE culture_NN1 ,_, operations_NN2 ,_, and_CC risk_NN1 profile_NN1 ._. 
</s>
<s>
It_PPH1 provides_VVZ objectivity_NN1 ,_, skills_NN2 ,_, and_CC knowledge_NN1 in_BCL21 order_BCL22 to_TO add_VVI value_NN1 to_II the_AT internal_JJ control_NN1 of_IO an_AT1 organization_NN1 ,_, but_CCB it_PPH1 can_VM also_RR help_VVI convince_VVI other_JJ stakeholders_NN2 such_II21 as_II22 employees_NN2 ,_, authorized_JJ representatives_NN2 ,_, investors_NN2 ,_, and_CC shareholders_NN2 ._. 
</s>
<s>
The_AT benefits_NN2 mentioned_VVN above_RL make_VV0 internal_JJ auditing_NN1 into_II a_AT1 valuable_JJ resource_NN1 for_IF the_AT organization_NN1 ._. 
</s>
<s>
(_( IIA_NP1 2004_MC )_) Managers_NN2 in_II large_JJ companies_NN2 very_RG rarely_RR know_VV0 exactly_RR what_DDQ is_VBZ happening_VVG in_II the_AT different_JJ departments_NN2 of_IO the_AT organization_NN1 ,_, and_CC are_VBR therefore_RR in_II desperate_JJ need_NN1 of_IO information_NN1 regarding_II their_APPGE company_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ where_RRQ internal_JJ auditors_NN2 step_VV0 in_RP ._. 
</s>
<s>
Internal_JJ auditors_NN2 can_VM give_VVI the_AT organization_NN1 an_AT1 understanding_NN1 of_IO the_AT different_JJ processes_NN2 and_CC the_AT people_NN who_PNQS run_VV0 these_DD2 processes_NN2 ._. 
</s>
<s>
They_PPHS2 are_VBR also_RR in_II31 possession_II32 of_II33 knowledge_NN1 concerning_II the_AT principles_NN2 of_IO good_JJ management_NN1 and_CC how_RRQ to_TO apply_VVI these_DD2 principles_NN2 ._. 
</s>
<s>
Internal_JJ auditing_NN1 functions_NN2 as_II a_AT1 counsel_NN1 for_IF the_AT management_NN1 ._. 
</s>
<s>
It_PPH1 provides_VVZ objective_JJ views_NN2 on_II processes_NN2 ,_, evaluations_NN2 on_II potential_JJ success_NN1 or_CC problems_NN2 with_IW ongoing_JJ operations_NN2 ,_, and_CC it_PPH1 can_VM also_RR provide_VVI education_NN1 to_II the_AT management_NN1 ,_, if_CS necessary_JJ ._. 
</s>
<s>
(_( Sawyer_NP1 1993_MC )_) Businesses_NN2 are_VBR rarely_RR passive_JJ and_CC at_II a_AT1 standstill_NN1 ._. 
</s>
<s>
Also_RR because_II21 of_II22 the_AT constant_JJ development_NN1 of_IO technologies_NN2 organizations_NN2 are_VBR pushed_VVN to_TO constantly_RR develop_VVI new_JJ working_JJ methods_NN2 in_BCL21 order_BCL22 to_TO improve_VVI their_APPGE business_NN1 processes_NN2 ._. 
</s>
<s>
When_CS the_AT information_NN1 systems_NN2 and_CC the_AT processes_NN2 within_II organizations_NN2 start_VV0 to_TO become_VVI more_DAR and_CC more_RGR complicated_JJ ,_, the_AT need_NN1 for_IF an_AT1 up_JJ31 to_JJ32 date_JJ33 internal_JJ auditing_NN1 process_NN1 start_NN1 to_TO become_VVI more_RGR apparent_JJ ._. 
</s>
<s>
Continuous_JJ auditing_NN1 gives_VVZ internal_JJ auditors_NN2 a_AT1 way_NN1 to_TO keep_VVI up_RP with_IW the_AT development_NN1 and_CC secure_VVI the_AT validity_NN1 and_CC reliability_NN1 of_IO the_AT internal_JJ auditing_NN1 reports_NN2 ._. 
</s>
<s>
(_( Smith_NP1 &;_NULL Warren_NP1 2006_MC )_) Characteristics_NN2 and_CC skills_NN2 The_AT position_NN1 of_IO an_AT1 internal_JJ auditor_NN1 is_VBZ a_AT1 demanding_JJ task_NN1 ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO keep_VVI up_RP with_IW the_AT constantly_RR changing_JJ nature_NN1 of_IO their_APPGE profession_NN1 ,_, they_PPHS2 need_VV0 to_II posses_NN2 technical_JJ skills_NN2 ,_, competencies_NN2 ,_, and_CC behavioral_JJ characteristics_NN2 ._. 
</s>
<s>
Internal_JJ auditors_NN2 must_VM be_VBI able_JK to_TO fuse_VVI together_RL their_APPGE skills_NN2 in_II statistics_NN ,_, negotiation_NN1 ,_, investigation_NN1 ,_, computer_NN1 programming_NN1 ,_, and_CC politics_NN1 ._. 
</s>
<s>
(_( Jackson_NP1 2007_MC )_) Soft_JJ skills_NN2 ,_, or_CC to_TO be_VBI precise_JJ ,_, different_JJ personality_NN1 traits_NN2 are_VBR what_DDQ separate_VV0 an_AT1 exceptional_JJ internal_JJ auditor_NN1 from_II an_AT1 average_JJ one_PN1 ._. 
</s>
<s>
These_DD2 soft_JJ skills_NN2 feature_VV0 social_JJ dignity_NN1 ,_, communication_NN1 ,_, language_NN1 ,_, friendliness_NN1 ,_, personal_JJ habits_NN2 ,_, and_CC optimism_NN1 ._. 
</s>
<s>
(_( Karan_NP1 2011_MC )_) Communication_NN1 skills_NN2 are_VBR essential_JJ for_IF an_AT1 internal_JJ auditor_NN1 to_TO master_VVI ,_, since_CS they_PPHS2 are_VBR constantly_RR in_II31 touch_II32 with_II33 the_AT management_NN1 ,_, auditees_NN2 ,_, and_CC co-workers_NN2 ._. 
</s>
<s>
The_AT continuous_JJ task_NN1 of_IO collecting_VVG ,_, sorting_VVG ,_, analyzing_VVG ,_, and_CC explaining_NN1 of_IO information_NN1 to_II the_AT management_NN1 and_CC the_AT auditees_NN2 requires_VVZ that_CST the_AT internal_JJ auditors_NN2 posses_VVZ extensive_JJ skills_NN2 in_II listening_NN1 ,_, interpersonal_JJ ,_, written_VVN ,_, and_CC oral_JJ communication_NN1 ._. 
</s>
<s>
These_DD2 skills_NN2 are_VBR then_RT used_VVN to_TO deliver_VVI clear_JJ and_CC precise_JJ information_NN1 ,_, either_RR in_II a_AT1 written_JJ or_CC oral_JJ form_NN1 ,_, to_II the_AT management_NN1 and_CC the_AT auditees_NN2 ._. 
</s>
<s>
Its_APPGE important_JJ that_CST these_DD2 individuals_NN2 understand_VV0 concisely_RR what_DDQ the_AT internal_JJ auditor_NN1 is_VBZ presenting_VVG ._. 
</s>
<s>
Also_RR because_II21 of_II22 the_AT fact_NN1 that_CST these_DD2 individuals_NN2 are_VBR located_VVN on_II various_JJ positions_NN2 in_II the_AT organization_NN1 the_AT requirement_NN1 of_IO good_JJ interpersonal_JJ skills_NN2 is_VBZ valuable_JJ ._. 
</s>
<s>
(_( Smith_NP1 2005_MC )_) Methodology_NN1 The_AT empirical_JJ part_NN1 of_IO this_DD1 study_NN1 is_VBZ performed_VVN by_II the_AT usage_NN1 of_IO a_AT1 qualitative_JJ research_NN1 method_NN1 in_II the_AT form_NN1 of_IO enquiries_NN2 sent_VVN to_II the_AT participants_NN2 ._. 
</s>
<s>
The_AT reason_NN1 for_IF using_VVG a_AT1 qualitative_JJ research_NN1 method_NN1 was_VBDZ influenced_VVN by_II the_AT theme_NN1 of_IO the_AT research_NN1 ._. 
</s>
<s>
The_AT purpose_NN1 was_VBDZ to_TO study_VVI how_RGQ internal_JJ auditors_NN2 within_II municipal_JJ organizations_NN2 view_VV0 their_APPGE line_NN1 of_IO work_NN1 and_CC what_DDQ they_PPHS2 think_VV0 the_AT role_NN1 of_IO internal_JJ auditing_NN1 is_VBZ to_II a_AT1 municipal_JJ organization_NN1 ._. 
</s>
<s>
The_AT strength_NN1 of_IO qualitative_JJ research_NN1 methods_NN2 is_VBZ the_AT in_II debt_NN1 information_NN1 they_PPHS2 can_VM produce_VVI ._. 
</s>
<s>
The_AT intention_NN1 of_IO a_AT1 qualitative_JJ interview_NN1 or_CC enquiry_NN1 is_VBZ to_TO generate_VVI information_NN1 that_CST show_VV0 more_DAR than_CSN what_DDQ meets_VVZ the_AT eye_NN1 ,_, in_II other_JJ words_NN2 the_AT purpose_NN1 is_VBZ to_TO build_VVI a_AT1 relationship_NN1 between_II the_AT researcher_NN1 and_CC the_AT respondent_NN1 ._. 
</s>
<s>
This_DD1 relationship_NN1 enables_VVZ the_AT possibility_NN1 to_TO create_VVI a_AT1 deeper_JJR understanding_NN1 concerning_II the_AT problem_NN1 and_CC to_TO gain_VVI a_AT1 comprehensive_JJ picture_NN1 of_IO the_AT situation_NN1 ._. 
</s>
<s>
(_( Holme_NP1 &;_NULL Solvang_NP1 1997_MC :_: 92_MC ,_, 99_MC )_) The_AT purpose_NN1 of_IO a_AT1 qualitative_JJ interview_NN1 and_CC enquiry_NN1 is_VBZ also_RR to_TO bring_VVI forward_RL adequate_JJ and_CC descriptive_JJ information_NN1 about_II peoples_NN2 experience_VV0 regarding_II the_AT theme_NN1 of_IO the_AT research_NN1 ._. 
</s>
<s>
Because_II21 of_II22 the_AT theme_NN1 of_IO this_DD1 research_NN1 a_AT1 quantitative_JJ research_NN1 method_NN1 wouldnt_NN1 have_VH0 produced_VVN same_DA in_II debt_NN1 information_NN1 as_CSA a_AT1 qualitative_JJ research_NN1 method_NN1 ._. 
</s>
<s>
A_AT1 quantitative_JJ research_NN1 method_NN1 attempts_NN2 to_TO collect_VVI statistical_JJ information_NN1 over_II the_AT research_NN1 problem_NN1 ._. 
</s>
<s>
(_( Dalen_NN1 2008_MC :_: 9_MC )_) There_EX are_VBR several_DA2 aspects_NN2 that_CST need_VV0 to_TO be_VBI considered_VVN when_CS there_EX is_VBZ an_AT1 intention_NN1 of_IO using_VVG a_AT1 qualitative_JJ method_NN1 ._. 
</s>
<s>
First_MD of_IO all_DB ,_, the_AT choice_NN1 of_IO the_AT respondents_NN2 has_VHZ a_AT1 great_JJ influence_NN1 whether_CSW31 or_CSW32 not_CSW33 the_AT research_NN1 will_VM be_VBI successful_JJ ._. 
</s>
<s>
If_CS wrong_JJ respondents_NN2 are_VBR chosen_VVN ,_, it_PPH1 might_VM lead_VVI to_II valueless_JJ research_NN1 results_NN2 ._. 
</s>
<s>
Furthermore_RR should_VM the_AT choices_NN2 be_VBI made_VVN according_II21 to_II22 criterias_NN2 ,_, which_DDQ are_VBR defined_VVN from_II what_DDQ the_AT interview_NN1 or_CC enquiry_NN1 should_VM produce_VVI ._. 
</s>
<s>
(_( Holme_NP1 &;_NULL Solvang_NP1 1997_MC :_: 101_MC )_) The_AT data_NN acquisition_NN1 is_VBZ performed_VVN through_II enquiries_NN2 sent_VVN to_II chief_JJ auditing_NN1 executives_NN2 of_IO various_JJ municipal_JJ organizations_NN2 ._. 
</s>
<s>
Of_IO the_AT eight_MC sent_VVD enquiries_NN2 ,_, two_MC enquiries_NN2 were_VBDR responded_VVN to_II ._. 
</s>
<s>
Both_DB2 of_IO the_AT respondents_NN2 wished_VVD to_TO be_VBI presented_VVN anonymously_RR ,_, therefore_RR they_PPHS2 are_VBR going_VVGK to_TO be_VBI called_VVN Respondent_NN1 1_MC1 and_CC Respondent_NN1 2_MC ._. 
</s>
<s>
The_AT enquiries_NN2 were_VBDR sent_VVN to_II the_AT respondents_NN2 by_II e-mail_NN1 to_TO ease_VVI the_AT round_NN1 up_RP of_IO the_AT information_NN1 and_CC to_TO give_VVI the_AT respondents_NN2 time_VV0 to_TO think_VVI through_RP their_APPGE answers_NN2 ._. 
</s>
<s>
The_AT enquiry_NN1 contained_VVD five_MC questions_NN2 ,_, of_IO which_DDQ all_DB were_VBDR formed_VVN to_TO give_VVI the_AT participants_NN2 a_AT1 possibility_NN1 to_TO explain_VVI ,_, in_II their_APPGE own_DA words_NN2 ,_, what_DDQ they_PPHS2 thought_VVD about_II the_AT subject_NN1 in_II question_NN1 ._. 
</s>
<s>
The_AT first_MD question_NN1 deals_VVZ with_IW the_AT participants_NN2 opinion_NN1 concerning_II what_DDQ the_AT most_RGT important_JJ section_NN1 is_VBZ in_II internal_JJ auditing_NN1 and_CC why_RRQ ._. 
</s>
<s>
Questions_NN2 two_MC and_CC three_MC deal_NN1 with_IW how_RRQ important_JJ internal_JJ auditing_NN1 is_VBZ for_IF a_AT1 municipal_JJ organization_NN1 and_CC how_RGQ big_JJ of_IO a_AT1 role_NN1 the_AT internal_JJ auditing_NN1 reports_NN2 have_VH0 in_II the_AT decision_NN1 making_VVG ._. 
</s>
<s>
Question_NN1 four_MC deals_NN2 with_IW what_DDQ kind_NN1 of_IO risks_NN2 can_VM restrain_VVI internal_JJ auditing_NN1 ._. 
</s>
<s>
The_AT last_MD question_NN1 asks_VVZ about_II the_AT participants_NN2 opinion_NN1 regarding_II the_AT most_RGT important_JJ characteristics_NN2 and_CC skills_NN2 of_IO an_AT1 internal_JJ auditor_NN1 ._. 
</s>
<s>
Results_NN2 The_AT results_NN2 are_VBR presented_VVN question_NN1 by_II question_NN1 in_BCL21 order_BCL22 to_TO make_VVI it_PPH1 easier_JJR to_TO keep_VVI up_RP with_IW the_AT answers_NN2 of_IO both_DB2 of_IO the_AT respondents_NN2 ._. 
</s>
<s>
Question_VV0 1_MC1 Respondent_NN1 1_MC1 is_VBZ of_IO an_AT1 opinion_NN1 that_CST the_AT most_RGT important_JJ section_NN1 of_IO internal_JJ auditing_NN1 is_VBZ to_TO confirm_VVI that_DD1 internal_JJ control_NN1 ,_, risk_NN1 management_NN1 ,_, and_CC leading_JJ and_CC administrative_JJ procedures_NN2 accomplish_VV0 its_APPGE objectives_NN2 ._. 
</s>
<s>
The_AT reason_NN1 for_IF this_DD1 is_VBZ that_CST a_AT1 public_JJ organization_NN1 can_VM be_VBI regarded_VVN as_II a_AT1 multi-objective_JJ organization_NN1 ,_, whichs_VVZ various_JJ sections_NN2 have_VH0 different_JJ logics_NN2 of_IO operation_NN1 ._. 
</s>
<s>
Respondent_NN1 1_MC1 also_RR stated_VVN that_CST the_AT basic_JJ task_NN1 of_IO the_AT operation_NN1 can_VM go_VVI missing_JJ if_CS the_AT leadership_NN1 and_CC the_AT managements_NN2 tasks_NN2 are_VBR not_XX well-maintained_JJ ._. 
</s>
<s>
The_AT most_RGT important_JJ section_NN1 of_IO internal_JJ auditing_NN1 is_VBZ ,_, according_II21 to_II22 Respondent_NN1 2_MC ,_, to_TO function_VVI as_II a_AT1 tool_NN1 for_IF the_AT group_NN1 executive_NN1 board_NN1 to_TO implement_VVI internal_JJ control_NN1 in_II a_AT1 diversified_JJ municipal_JJ organization_NN1 ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, carry_VV0 out_RP their_APPGE responsibilities_NN2 to_TO monitor_VVI the_AT profitability_NN1 of_IO the_AT organization_NN1 ._. 
</s>
<s>
Additionally_RR the_AT own_DA aspiration_NN1 of_IO the_AT management_NN1 is_VBZ to_TO work_VVI as_II support_NN1 for_IF the_AT development_NN1 and_CC reflect_VV0 on_II how_RRQ to_TO perform_VVI even_RR better_RRR and_CC more_RGR efficiently_RR ,_, that_REX21 is_REX22 ,_, to_TO provide_VVI alternatives_NN2 to_TO perform_VVI better_RRR ._. 
</s>
<s>
This_DD1 is_VBZ required_VVN in_BCL21 order_BCL22 to_TO prevent_VVI external_JJ and_CC internal_JJ risks_NN2 ,_, which_DDQ can_VM threaten_VVI the_AT present_JJ operations_NN2 of_IO the_AT municipal_JJ organization_NN1 ._. 
</s>
<s>
Also_RR the_AT currently_RR ongoing_JJ consolidation_NN1 of_IO municipalities_NN2 introduces_VVZ big_JJ changes_NN2 ._. 
</s>
<s>
In_II order_NN1 to_TO not_XX waste_VVI the_AT opportunities_NN2 that_CST the_AT consolidation_NN1 of_IO municipalities_NN2 can_VM bring_VVI ,_, it_PPH1 is_VBZ important_JJ that_CST the_AT changes_NN2 are_VBR controlled_VVN by_II production_NN1 of_IO assessment_NN1 data_NN ._. 
</s>
<s>
Question_NN1 2_MC Respondent_NN1 1_MC1 states_VVZ ,_, that_CST the_AT importance_NN1 of_IO internal_JJ auditing_NN1 for_IF the_AT municipal_JJ organization_NN1 grows_VVZ as_II the_AT organization_NN1 grows_VVZ ._. 
</s>
<s>
The_AT larger_JJR the_AT municipal_JJ organization_NN1 is_VBZ ,_, the_AT more_RGR important_JJ the_AT internal_JJ auditing_NN1 will_VM get_VVI ._. 
</s>
<s>
Internal_JJ auditing_NN1 is_VBZ a_AT1 significant_JJ interlocutor_NN1 ,_, which_DDQ produces_VVZ information_NN1 in_II31 relation_II32 to_II33 the_AT functionality_NN1 of_IO processes_NN2 and_CC which_DDQ objects_NN2 should_VM be_VBI developed_VVN further_RRR ._. 
</s>
<s>
According_II21 to_II22 Respondent_NN1 2_MC ,_, the_AT internal_JJ auditing_NN1 process_NN1 is_VBZ an_AT1 important_JJ source_NN1 to_TO obtain_VVI feedback_NN1 and_CC factual_JJ information_NN1 regarding_II process_NN1 activities_NN2 ,_, functionality_NN1 and_CC level_NN1 of_IO leadership_NN1 ,_, and_CC realization_NN1 of_IO placed_VVN objectives_NN2 ._. 
</s>
<s>
For_REX21 example_REX22 :_: how_RRQ the_AT new_JJ management_NN1 system_NN1 is_VBZ working_VVG ,_, how_RRQ objective_JJ and_CC indicator_NN1 hierarchy_NN1 is_VBZ founded_VVN in_II a_AT1 new_JJ organization_NN1 ,_, and_RR31 so_RR32 on_RR33 ._. 
</s>
<s>
Additionally_RR ,_, the_AT management_NN1 and_CC other_JJ persons_NN2 elected_VVN to_II a_AT1 position_NN1 of_IO trust_NN1 ,_, expect_VV0 options_NN2 and_CC their_APPGE cost_NN1 effects_NN2 to_TO support_VVI their_APPGE own_DA decision_NN1 making_VVG ,_, so_CS21 that_CS22 the_AT decisions_NN2 would_VM as_RG impressive_JJ and_CC economical_JJ as_CSA possible_JJ ._. 
</s>
<s>
Question_NN1 3_MC According_II21 to_II22 Respondent_NN1 1_MC1 ,_, the_AT internal_JJ auditing_NN1 reports_NN2 have_VH0 more_DAR importance_NN1 for_IF the_AT functional_JJ leadership_NN1 of_IO the_AT incumbent_JJ management_NN1 ._. 
</s>
<s>
Respondent_NN1 1_MC1 also_RR mentions_VVZ that_CST the_AT outcome_NN1 of_IO the_AT results_NN2 can_VM also_RR reflect_VVI on_II the_AT institutions_NN2 decision-making_NN1 ,_, but_CCB more_RGR rarely_RR ._. 
</s>
<s>
Respondent_NN1 2_MC states_VVZ that_CST the_AT role_NN1 of_IO the_AT internal_JJ auditing_NN1 reports_VVZ in_II the_AT managements_NN2 decision-making_NN1 depends_VVZ completely_RR on_II the_AT audited_JJ issue_NN1 ,_, how_RRQ important_JJ it_PPH1 is_VBZ ,_, and_CC what_DDQ the_AT management_NN1 are_VBR prioritizing_VVG ._. 
</s>
<s>
The_AT key_NN1 is_VBZ to_TO get_VVI the_AT operation_NN1 management_NN1 commit_VV0 themselves_PPX2 to_II potential_JJ development_NN1 measures_NN2 and_CC the_AT decision-making_NN1 it_PPH1 demands_VVZ ._. 
</s>
<s>
Internal_JJ auditors_NN2 report_VV0 to_TO top_VVI management_NN1 and_CC to_II the_AT committee_NN1 ._. 
</s>
<s>
The_AT top_JJ management_NN1 evaluates_VVZ and_CC aligns_VVZ which_DDQ quarters_NN2 take_VV0 measures_NN2 in_II the_AT matter_NN1 and_CC then_RT informs_VVZ the_AT appropriate_JJ management_NN1 through_II internal_JJ auditing_NN1 ._. 
</s>
<s>
The_AT more_RGR extensive_JJ the_AT commitments_NN2 by_II the_AT management_NN1 are_VBR for_IF the_AT needed_VVN measures_NN2 ,_, the_AT more_RRR the_AT importances_NN2 of_IO the_AT reports_NN2 are_VBR emphasized_VVN ._. 
</s>
<s>
The_AT measures_NN2 and_CC the_AT appointed_JJ follow-up_JJ actions_NN2 registered_VVN in_II the_AT report_NN1 assist_VV0 also_RR the_AT decision-making_NN1 ._. 
</s>
<s>
Question_NN1 4_MC The_AT greatest_JJT risk_NN1 is_VBZ according_II21 to_II22 Respondent_NN1 1_MC1 that_CST the_AT correct_JJ objects_NN2 are_VBR not_XX selected_VVN for_IF evaluation_NN1 according_II21 to_II22 the_AT risk_NN1 factor_NN1 ,_, which_DDQ can_VM result_VVI that_CST the_AT most_RGT essential_JJ parts_NN2 are_VBR not_XX evaluated_VVN ._. 
</s>
<s>
This_DD1 could_VM be_VBI influenced_VVN by_II a_AT1 lack_NN1 of_IO a_AT1 confidential_JJ and_CC open_JJ interaction_NN1 and_CC a_AT1 dialogical_JJ connection_NN1 between_II the_AT internal_JJ auditors_NN2 and_CC the_AT management_NN1 ._. 
</s>
<s>
Respondent_NN1 2_MC mentions_VVZ that_CST the_AT greatest_JJT risk_NN1 is_VBZ simply_RR internal_JJ auditors_NN2 lack_NN1 of_IO know-how_NN1 and_CC that_CST this_DD1 has_VHZ not_XX been_VBN verified_VVN and_CC secured_VVN ._. 
</s>
<s>
Question_NN1 5_MC The_AT most_RGT important_JJ characteristics_NN2 of_IO an_AT1 internal_JJ auditor_NN1 are_VBR ,_, according_II21 to_II22 Respondent_NN1 1_MC1 ,_, openness_NN1 ,_, honesty_NN1 ,_, independence_NN1 ,_, confidentiality_NN1 ,_, and_CC competencies_NN2 in_II interaction_NN1 and_CC cooperation_NN1 ._. 
</s>
<s>
Respondent_NN1 2_MC states_VVZ that_CST the_AT most_RGT important_JJ characteristics_NN2 and_CC skills_NN2 are_VBR a_AT1 strong_JJ basic_JJ know-how_NN1 and_CC possible_JJ special_JJ know-how_NN1 (_( to_TO create_VVI trust_NN1 )_) ,_, cooperation_NN1 and_CC social_JJ skills_NN2 ,_, analyticity_NN1 and_CC an_AT1 ability_NN1 to_TO find_VVI and_CC report_VVI the_AT essential_JJ issues_NN2 ,_, and_CC an_AT1 ability_NN1 to_TO see_VVI entities_NN2 and_CC how_RRQ things_NN2 are_VBR connected_VVN ._. 
</s>
<s>
Discussion_NN1 The_AT results_NN2 of_IO the_AT study_NN1 indicate_VV0 that_CST municipal_JJ organizations_NN2 utilize_VV0 internal_JJ auditing_NN1 in_II a_AT1 way_NN1 that_CST resembles_VVZ those_DD2 aspects_NN2 of_IO internal_JJ auditing_NN1 that_CST were_VBDR presented_VVN in_II the_AT theoretical_JJ review_NN1 ._. 
</s>
<s>
This_DD1 can_VM though_RR be_VBI caused_VVN by_II the_AT fact_NN1 that_CST The_AT Institute_NN1 of_IO Internal_JJ Auditors_NN2 (_( IIA_NP1 )_) have_VH0 placed_VVN standards_NN2 on_II how_RGQ internal_JJ auditing_NN1 should_VM be_VBI performed_VVN and_CC what_DDQ it_PPH1 should_VM try_VVI to_TO achieve_VVI ._. 
</s>
<s>
Even_CS21 if_CS22 these_DD2 standards_NN2 do_VD0 nt_XX need_VVI to_TO be_VBI followed_VVN ,_, they_PPHS2 give_VV0 an_AT1 approximate_JJ picture_NN1 over_II the_AT most_RGT efficient_JJ way_NN1 to_TO implement_VVI and_CC perform_VVI internal_JJ auditing_NN1 ._. 
</s>
<s>
Both_DB2 of_IO the_AT respondents_NN2 mentioned_VVD that_CST the_AT most_RGT important_JJ aspect_NN1 of_IO internal_JJ auditing_NN1 is_VBZ to_TO provide_VVI information_NN1 regarding_II the_AT profitability_NN1 of_IO the_AT organization_NN1 ._. 
</s>
<s>
They_PPHS2 also_RR mentioned_VVD that_CST internal_JJ auditing_NN1 provide_VV0 information_NN1 to_II the_AT management_NN1 over_II how_RGQ different_JJ processes_NN2 are_VBR accomplished_VVN and_CC what_DDQ could_VM be_VBI developed_VVN further_RRR ._. 
</s>
<s>
This_DD1 highlights_VVZ the_AT fact_NN1 that_CST the_AT process_NN1 of_IO internal_JJ auditing_NN1 is_VBZ highly_RR recognizable_JJ in_II both_DB2 of_IO the_AT organizations_NN2 ._. 
</s>
<s>
The_AT respondents_NN2 had_VHD dissenting_JJ opinions_NN2 over_II the_AT greatest_JJT risk_NN1 that_CST might_VM restrain_VVI the_AT internal_JJ auditing_NN1 process_NN1 ._. 
</s>
<s>
One_MC1 of_IO the_AT respondents_NN2 stated_VVD that_CST the_AT greatest_JJT risk_NN1 was_VBDZ that_CST the_AT correct_JJ objects_NN2 are_VBR not_XX picked_VVN for_IF evaluation_NN1 ,_, while_CS the_AT other_NN1 stated_VVD that_CST the_AT greatest_JJT risk_NN1 had_VHD to_TO do_VDI with_IW the_AT internal_JJ auditors_NN2 lack_NN1 of_IO skill_NN1 ._. 
</s>
<s>
None_PN of_IO the_AT respondents_NN2 mentioned_VVD risks_NN2 caused_VVN by_II external_JJ factors_NN2 ,_, as_II21 for_II22 example_NN1 uncooperation_NN1 or_CC that_CST the_AT auditing_NN1 reports_NN2 might_VM be_VBI unheeded_JJ completely_RR by_II the_AT management_NN1 ._. 
</s>
<s>
They_PPHS2 might_VM not_XX have_VHI encountered_VVN this_DD1 kind_NN1 of_IO risks_NN2 and_CC have_VH0 therefore_RR left_VVN them_PPHO2 unmentioned_JJ ._. 
</s>
<s>
When_CS asked_VVN about_II the_AT characteristics_NN2 of_IO a_AT1 good_JJ internal_JJ auditor_NN1 ,_, both_DB2 of_IO the_AT respondents_NN2 mentioned_VVD the_AT importance_NN1 of_IO the_AT soft_JJ skills_NN2 ,_, as_CSA mentioned_VVN in_II the_AT theoretical_JJ part_NN1 about_II the_AT characteristics_NN2 of_IO a_AT1 good_JJ internal_JJ auditor_NN1 ._. 
</s>
<s>
Both_DB2 highlighted_VVD the_AT importance_NN1 of_IO the_AT ability_NN1 to_TO cooperate_VVI and_CC to_TO have_VHI good_JJ skills_NN2 in_II interaction_NN1 ._. 
</s>
<s>
They_PPHS2 also_RR mentioned_VVD openness_NN1 as_II an_AT1 important_JJ characteristic_NN1 ,_, which_DDQ might_VM not_XX be_VBI such_DA a_AT1 common_JJ trait_NN1 in_II a_AT1 Finnish_JJ employee_NN1 ._. 
</s>
<s>
Both_DB2 of_IO the_AT respondents_NN2 have_VH0 a_AT1 similar_JJ view_NN1 ,_, over_II the_AT characteristics_NN2 of_IO a_AT1 good_JJ internal_JJ auditor_NN1 ,_, with_IW the_AT theoretical_JJ part_NN1 presented_VVN in_II chapter_NN1 2.4_MC ._. 
</s>
<s>
These_DD2 findings_NN2 ,_, and_CC also_RR the_AT findings_NN2 mentioned_VVN in_II the_AT previous_JJ paragraphs_NN2 ,_, confirm_VV0 that_CST internal_JJ auditing_NN1 in_II municipal_JJ organizations_NN2 is_VBZ performed_VVN similarly_RR to_II what_DDQ were_VBDR highlighted_VVN in_II the_AT literature_NN1 review_NN1 ._. 
</s>
