<s>
Risks_NN2 ,_, Benefits_NN2 and_CC Disadvantages_NN2 of_IO Real_JJ Estates_NN2 1_MC1 Introduction_NN1 Real_JJ estate_NN1 investment_NN1 has_VHZ always_RR been_VBN a_AT1 valued_JJ form_NN1 of_IO investment_NN1 ._. 
</s>
<s>
Since_II 2006_MC ,_, real_JJ estate_NN1 investment_NN1 had_VHD strong_JJ growth_NN1 and_CC became_VVD a_AT1 valued_JJ form_NN1 of_IO investment_NN1 by_II professional_JJ investors_NN2 ._. 
</s>
<s>
The_AT users_NN2 of_IO the_AT real_JJ estate_NN1 ,_, or_CC the_AT tenants_NN2 ,_, provide_VV0 long-term_JJ cash_NN1 flow_NN1 ,_, which_DDQ was_VBDZ tied_VVN to_II indexes_NN2 ._. 
</s>
<s>
Index_VV0 therefore_RR provided_VVN smoother_JJR changes_NN2 when_CS compared_VVN to_II many_DA2 other_JJ investment_NN1 opportunities_NN2 ._. 
</s>
<s>
In_II recent_JJ years_NNT2 ,_, cash_NN1 flows_NN2 have_VH0 been_VBN effortless_JJ to_TO finance_VVI with_IW very_RG loose_JJ money_NN1 market_NN1 ._. 
</s>
<s>
In_RR21 particular_RR22 ,_, the_AT private_JJ equity_NN1 investors_NN2 found_VVD real_JJ estates_NN2 and_CC the_AT cash_NN1 flow_NN1 ._. 
</s>
<s>
This_DD1 brought_VVD the_AT corporate_JJ investment_NN1 strategies_NN2 to_II the_AT real_JJ estate_NN1 sector_NN1 ._. 
</s>
<s>
During_II 2009_MC ,_, when_CS the_AT financial_JJ markets_NN2 were_VBDR not_XX functioning_VVG properly_RR ,_, the_AT transactions_NN2 involving_VVG real_JJ estates_NN2 decreased_VVD ._. 
</s>
<s>
As_II a_AT1 result_NN1 of_IO the_AT development_NN1 during_II the_AT past_JJ few_DA2 years_NNT2 ,_, real_JJ estate_NN1 investment_NN1 is_VBZ now_RT as_CSA prevalent_JJ and_CC prestigious_JJ form_NN1 of_IO investment_NN1 than_CSN derivatives_NN2 ,_, equities_NN2 ,_, or_CC even_RR corporate_JJ bonds_NN2 ._. 
</s>
<s>
The_AT KTI_JJ Property_NN1 Information_NN1 Ltd_JJ states_NN2 that_CST real_JJ estate_NN1 investment_NN1 has_VHZ been_VBN very_RG profitable_JJ ,_, and_CC they_PPHS2 performed_VVD well_RR when_CS compared_VVN to_II different_JJ types_NN2 of_IO investment_NN1 opportunities_NN2 ._. 
</s>
<s>
In_II 2007_MC ,_, for_IF the_AT first_MD time_NNT1 in_II seven_MC years_NNT2 ,_, real_JJ estate_NN1 revenue_NN1 increased_VVN to_II a_AT1 higher_JJR level_NN1 than_CSN the_AT stock_NN1 market_NN1 and_CC that_CST the_AT bond_NN1 market_NN1 ._. 
</s>
<s>
The_AT sub-prime_JJ crisis_NN1 started_VVD a_AT1 financial_JJ crisis_NN1 worldwide_RL and_CC the_AT worlds_NN2 economy_NN1 suffered_VVD a_AT1 recession_NN1 in_II 2009_MC ._. 
</s>
<s>
This_DD1 had_VHD a_AT1 major_JJ impact_NN1 in_II the_AT real_JJ estate_NN1 investment_NN1 sector_NN1 ._. 
</s>
<s>
The_AT sub-prime_JJ crisis_NN1 started_VVD in_II the_AT United_NP1 States_NP1 in_II 2007_MC and_CC it_PPH1 began_VVD when_RRQ the_AT American_JJ banks_NN2 granted_VVD loans_NN2 to_II people_NN who_PNQS default_VV0 on_II those_DD2 loans_NN2 ._. 
</s>
<s>
These_DD2 loans_NN2 were_VBDR then_RT collected_VVN to_TO form_VVI a_AT1 group_NN1 ,_, or_CC a_AT1 portfolio_NN1 in_BCL21 order_BCL22 to_TO achieve_VVI the_AT highest_JJT possible_JJ credit_NN1 rating_VVG from_II a_AT1 rating-house_NN1 ,_, because_CS the_AT loans_NN2 were_VBDR distributed_VVN through_II a_AT1 large_JJ number_NN1 of_IO the_AT borrowers_NN2 and_CC the_AT loans_NN2 were_VBDR secured_VVN by_II a_AT1 house_NN1 or_CC property_NN1 ._. 
</s>
<s>
The_AT good_JJ credit_NN1 ratings_NN2 enabled_VVD the_AT loans_NN2 to_TO be_VBI sold_VVN to_II investors_NN2 such_II21 as_II22 pension_NN1 trustees_NN2 for_IF a_AT1 good_JJ price_NN1 ._. 
</s>
<s>
When_CS it_PPH1 subsequently_RR transpired_VVN that_CST the_AT borrower_NN1 groups_NN2 were_VBDR not_XX able_JK to_TO pay_VVI for_IF their_APPGE existing_JJ and_CC future_JJ obligations_NN2 ,_, these_DD2 investment_NN1 products_NN2 lost_VVD their_APPGE value_NN1 dramatically_RR ._. 
</s>
<s>
This_DD1 ultimately_RR led_VVN to_II the_AT situation_NN1 where_RRQ the_AT European_JJ countries_NN2 were_VBDR in_II recession_NN1 and_CC a_AT1 number_NN1 of_IO investment_NN1 targets_NN2 value_NN1 decreased_VVD significantly_RR ._. 
</s>
<s>
2_MC The_AT Risks_NN2 Involved_VVD The_AT first_MD ,_, and_CC foremost_JJT important_JJ element_NN1 in_II investment_NN1 activities_NN2 is_VBZ to_TO identify_VVI potential_JJ risks_NN2 that_CST are_VBR related_VVN to_II an_AT1 investment_NN1 opportunity_NN1 ._. 
</s>
<s>
Risk_NN1 refers_VVZ to_II all_DB the_AT potential_JJ risks_NN2 that_CST an_AT1 investor_NN1 may_VM face_VVI ._. 
</s>
<s>
What_DDQ are_VBR the_AT risks_NN2 affecting_VVG the_AT real_JJ estate_NN1 investment_NN1 ?_? 
</s>
<s>
Is_VBZ it_PPH1 worth_II investing_VVG in_RP to_II government_NN1 bonds_NN2 than_CSN investment_NN1 than_CSN real_JJ estate_NN1 ?_? 
</s>
<s>
How_RGQ real_JJ estate_NN1 investment_NN1 risks_NN2 differ_VV0 from_II leasing_VVG risks_NN2 ?_? 2.1_MC Defining_JJ Risk_NN1 Before_II the_AT various_JJ risks_NN2 are_VBR discussed_VVN ,_, it_PPH1 is_VBZ important_JJ to_TO understand_VVI what_DDQ is_VBZ meant_VVN by_II risk_NN1 ._. 
</s>
<s>
Risk_NN1 implies_VVZ the_AT event_NN1 ,_, which_DDQ can_VM not_XX be_VBI predicted_VVN in_II the_AT future_NN1 ._. 
</s>
<s>
Risk_VV0 management_NN1 is_VBZ a_AT1 set_NN1 of_IO procedures_NN2 that_CST minimizes_VVZ risks_NN2 and_CC costs_VVZ to_II the_AT investor_NN1 or_CC business_NN1 ._. 
</s>
<s>
If_CS the_AT investor_NN1 were_VBDR able_JK to_TO foresee_VVI risks_NN2 ,_, the_AT definition_NN1 would_VM not_XX be_VBI applicable_JJ ._. 
</s>
<s>
If_CS an_AT1 investor_NN1 were_VBDR able_JK to_TO make_VVI the_AT correct_JJ prediction_NN1 of_IO future_JJ investment_NN1 returns_NN2 ,_, he_PPHS1 never_RR would_VM make_VVI the_AT investment_NN1 ,_, which_DDQ is_VBZ below_II the_AT expected_JJ yield_NN1 rate_NN1 ._. 
</s>
<s>
(_( Kaleva_NN1 and_CC Land_NP1 and_CC Olkkonen_NP1 ,_, 1997_MC ,_, 87_MC ._. )_) 
</s>
<s>
Real_JJ estate_NN1 investment_NN1 risks_NN2 can_VM be_VBI divided_VVN into_II two_MC different_JJ parts_NN2 ._. 
</s>
<s>
The_AT first_MD part_NN1 distinguishes_VVZ the_AT risk_NN1 between_II the_AT individual_JJ investment_NN1 risks_NN2 ._. 
</s>
<s>
The_AT second_MD part_NN1 distinguishes_VVZ the_AT possible_JJ risks_NN2 that_CST have_VH0 an_AT1 impact_NN1 on_II the_AT investments_NN2 portfolio_NN1 risk_NN1 ._. 
</s>
<s>
An_AT1 investor_NN1 may_VM consciously_RR define_VVI themselves_PPX2 according_II21 to_II22 three_MC types_NN2 of_IO risk_NN1 attitudes_NN2 ._. 
</s>
<s>
The_AT three_MC different_JJ are_VBR :_: neutral_JJ ,_, risk_VV0 averse_JJ ,_, and_CC risk_NN1 lover_NN1 ._. 
</s>
<s>
(_( Kaleva_NN1 and_CC Land_NP1 and_CC Olkkonen_NP1 ,_, 1997_MC ,_, 87._MC )_) 2.2_MC Corporate_JJ risk_NN1 The_AT corporate_JJ risk_NN1 refers_VVZ to_II the_AT liabilities_NN2 and_CC dangers_NN2 that_CST the_AT investor_NN1 or_CC business_NN1 may_VM face_VVI ._. 
</s>
<s>
More_RGR importantly_RR ,_, the_AT economic_JJ success_NN1 and_CC its_APPGE impact_NN1 on_II the_AT share_NN1 value_NN1 is_VBZ a_AT1 crucial_JJ factor_NN1 in_II corporate_JJ risk_NN1 ._. 
</s>
<s>
The_AT proper_JJ way_NN1 to_II for_IF an_AT1 investor_NN1 to_TO avoid_VVI the_AT corporate_JJ risk_NN1 is_VBZ to_TO diversify_VVI the_AT contents_NN2 of_IO their_APPGE investment_NN1 portfolio_NN1 ._. 
</s>
<s>
By_II diversification_NN1 an_AT1 investor_NN1 ensures_VVZ greater_JJR return_NN1 with_IW the_AT lowest_JJT possible_JJ risk_NN1 ._. 
</s>
<s>
(_( Brueggeman_NN1 and_CC Fisher_NP1 2008_MC ,_, 385_MC -_- 386_MC ._. )_) 
</s>
<s>
Real_JJ estate_NN1 investors_NN2 cash_VV0 flows_NN2 and_CC return_NN1 are_VBR generated_VVN through_II rent_NN1 ._. 
</s>
<s>
Investors_NN2 face_VV0 the_AT corporate_JJ risk_NN1 ,_, so_CS21 that_CS22 an_AT1 economic_JJ activity_NN1 ,_, such_II21 as_II22 recession_NN1 ,_, decreases_VVZ and_CC leads_VVZ to_II a_AT1 decrease_NN1 in_II rental_NN1 income_NN1 cash_NN1 flows_NN2 and_CC ultimately_RR ,_, affect_VV0 the_AT return_NN1 ._. 
</s>
<s>
Fluctuations_NN2 in_II the_AT societys_NN2 purchasing_NN1 power_NN1 due_II21 to_II22 recession_NN1 can_VM influence_VVI the_AT value_NN1 and_CC the_AT rent_NN1 of_IO a_AT1 real_JJ estate_NN1 ._. 
</s>
<s>
However_RR ,_, this_DD1 depends_VVZ solely_RR on_II the_AT type_NN1 of_IO real_JJ estate_NN1 and_CC the_AT lease_NN1 agreement_NN1 ._. 
</s>
<s>
(_( Brueggeman_NN1 and_CC Fisher_NP1 2008_MC ,_, 385_MC -_- 386._MC )_) 2.3_MC Financial_JJ risk_NN1 If_CS the_AT investor_NN1 chooses_VVZ to_TO use_VVI debt_NN1 in_BCL21 order_BCL22 to_TO finance_VVI the_AT investment_NN1 ,_, financial_JJ risk_NN1 increases_NN2 ._. 
</s>
<s>
As_II the_AT debt_NN1 in_II financing_VVG increases_NN2 ,_, the_AT financial_JJ risk_NN1 increases_VVZ accordingly_RR ._. 
</s>
<s>
Financial_JJ risk_NN1 is_VBZ closely_RR tied_VVN to_II the_AT terms_NN2 of_IO debt_NN1 financing_NN1 which_DDQ the_AT investor_NN1 is_VBZ able_JJ receive_VV0 from_II the_AT financial_JJ institution_NN1 ._. 
</s>
<s>
(_( Brueggeman_NN1 and_CC Fisher_NP1 2008_MC ,_, 386_MC ._. )_) 
</s>
<s>
Financial_JJ risk_NN1 ,_, therefore_RR ,_, consists_VVZ of_IO fixed_JJ charges_NN2 related_VVN to_II equity_NN1 ._. 
</s>
<s>
These_DD2 different_JJ fixed_JJ charges_NN2 include_VV0 interest_NN1 and_CC amortization_NN1 payments_NN2 that_CST are_VBR tied_VVN to_II a_AT1 specific_JJ point_NN1 in_II time_NNT1 ._. 
</s>
<s>
Financial_JJ risk_NN1 and_CC business_NN1 risk_NN1 are_VBR very_RG close_JJ to_II each_PPX221 other_PPX222 as_II the_AT higher_JJR the_AT investor_NN1 's_GE financial_JJ risk_NN1 is_VBZ ,_, the_AT smaller_JJR the_AT operational_JJ risks_NN2 the_AT investor_NN1 may_VM carry_VVI ._. 
</s>
<s>
(_( Leppiniemi_NP1 2002_MC ,_, 52_MC ._. )_) 
</s>
<s>
In_RR21 addition_RR22 ,_, a_AT1 high_JJ proportion_NN1 of_IO equity_NN1 used_VVN in_II the_AT investment_NN1 ,_, implies_VVZ that_CST the_AT financial_JJ risk_NN1 is_VBZ relatively_RR low_JJ ._. 
</s>
<s>
Similarly_RR ,_, a_AT1 high_JJ proportion_NN1 of_IO foreign_JJ capital_NN1 leads_VVZ to_II the_AT increase_NN1 in_II financial_JJ risk_NN1 ._. 
</s>
<s>
Debt_NN1 leverage_NN1 is_VBZ a_AT1 way_NN1 in_II which_DDQ the_AT investor_NN1 may_VM raise_VVI capital_NN1 ._. 
</s>
<s>
Debt_NN1 leverage_NN1 means_VVZ that_CST the_AT investor_NN1 aims_VVZ to_TO increase_VVI the_AT equity_NN1 a_AT1 way_NN1 that_CST increases_VVZ the_AT relative_JJ proportion_NN1 of_IO foreign_JJ capital_NN1 ._. 
</s>
<s>
The_AT basis_NN1 is_VBZ that_CST the_AT foreign_JJ capital_NN1 will_VM be_VBI paid_VVN a_AT1 fixed_JJ compensation_NN1 ._. 
</s>
<s>
Therefore_RR ,_, in_BCL21 order_BCL22 for_IF the_AT leverage_NN1 to_TO be_VBI positive_JJ ,_, all_DB the_AT earnings_NN2 through_II the_AT foreign_JJ capital_NN1 must_VM exceed_VVI the_AT fixed_JJ cost_NN1 ._. 
</s>
<s>
Ultimately_RR ,_, this_DD1 increases_VVZ the_AT returns_NN2 ,_, as_CSA the_AT investor_NN1 is_VBZ able_JK to_TO compensate_VVI the_AT fixed_JJ cost_NN1 by_II reinvestment_NN1 ._. 
</s>
<s>
Henceforth_RT ,_, for_IF the_AT leverage_NN1 to_TO work_VVI effectively_RR ,_, the_AT return_NN1 on_II assets_NN2 must_VM exceed_VVI the_AT fixed_JJ costs_NN2 of_IO borrowing_NN1 ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 ,_, if_CS the_AT return_NN1 falls_VVZ below_II the_AT fixed_JJ costs_NN2 of_IO borrowing_NN1 ,_, the_AT result_NN1 is_VBZ negative_JJ ,_, and_CC the_AT leverage_NN1 is_VBZ not_XX successful_JJ ._. 
</s>
<s>
In_II this_DD1 case_NN1 ,_, the_AT investor_NN1 has_VHZ to_TO pay_VVI the_AT borrowing_NN1 cost_NN1 from_II equity_NN1 ._. 
</s>
<s>
(_( Kinnunen_NN1 ,_, Leppiniemi_NP1 ,_, Puttonen_NP1 and_CC Virtanen_NP1 ,_, 2002_MC ,_, 241_MC ._. )_) 
</s>
<s>
Normally_RR professional_JJ real_JJ estate_NN1 investors_NN2 use_VV0 foreign_JJ capital_NN1 to_TO finance_VVI the_AT investment_NN1 ._. 
</s>
<s>
When_CS the_AT price_NN1 of_IO the_AT foreign_JJ capital_NN1 is_VBZ less_RRR that_CST the_AT price_NN1 to_TO use_VVI equity_NN1 ,_, then_RT the_AT use_NN1 of_IO foreign_JJ capital_NN1 is_VBZ favorable_JJ ._. 
</s>
<s>
The_AT formula_NN1 below_RL (_( equation_NN1 2_MC )_) illustrates_VVZ how_RRQ the_AT investor_NN1 is_VBZ able_JK to_TO calculate_VVI the_AT leverage_NN1 effect_NN1 :_: &lsqb;_( Formula_NN1 &rsqb;_) 2.4_MC Covenant_NN1 risk_VV0 The_AT covenant_NN1 risks_NN2 are_VBR understood_VVN as_CSA contractual_JJ guarantees_NN2 and_CC are_VBR subject_II21 to_II22 special_JJ conditions_NN2 attached_VVN to_II loans_NN2 ._. 
</s>
<s>
With_IW these_DD2 special_JJ terms_NN2 to_II the_AT borrower_NN1 ,_, the_AT financial_JJ institution_NN1 is_VBZ able_JK to_TO enforce_VVI functional_JJ limitations_NN2 and_CC increase_VVI the_AT lender_NN1 's_GE option_NN1 to_TO receive_VVI more_DAR information_NN1 from_II the_AT borrower_NN1 ,_, investor_NN1 or_CC company_NN1 ._. 
</s>
<s>
Covenants_NN2 enable_VV0 the_AT fulfillment_NN1 of_IO real_JJ securities_NN2 or_CC to_TO supplement_VVI or_CC replace_VVI them_PPHO2 altogether_RR ._. 
</s>
<s>
Therefore_RR ,_, covenants_NN2 can_VM be_VBI used_VVN to_TO reduce_VVI the_AT lender_NN1 's_GE credit_NN1 risk_NN1 ._. 
</s>
<s>
(_( Leppiniemi_NP1 2002_MC ,_, 96_MC ._. )_) 
</s>
<s>
The_AT covenant_NN1 risk_NN1 is_VBZ also_RR known_VVN as_II Loan-to-Value_NP1 Ratio_NN1 ,_, or_CC (_( L/V_ZZ1 )_) ._. 
</s>
<s>
In_II this_DD1 case_NN1 ,_, the_AT financial_JJ institution_NN1 approves_VVZ 90%_NNU in_II value_NN1 of_IO the_AT security_NN1 for_IF the_AT foreign_JJ capital_NN1 ._. 
</s>
<s>
In_RR21 general_RR22 ,_, banks_NN2 do_VD0 not_XX accept_VVI collateral_NN1 more_RRR than_CSN 75%_NNU -80%_FO of_IO the_AT value_NN1 of_IO the_AT property_NN1 ._. 
</s>
<s>
Assume_VV0 that_CST the_AT value_NN1 of_IO the_AT real_JJ estate_NN1 decreases_VVZ ,_, but_CCB the_AT cash_NN1 flow_NN1 does_VDZ not_XX change_VVI ._. 
</s>
<s>
The_AT value_NN1 of_IO the_AT real_JJ estate_NN1 is_VBZ not_XX enough_RR to_TO cover_VVI the_AT collateral_NN1 ,_, because_CS the_AT Loan-to-Value_NP1 has_VHZ increased_VVN by_II 98_MC percent_NNU ,_, for_REX21 example_REX22 ._. 
</s>
<s>
In_II this_DD1 case_NN1 ,_, a_AT1 bank_NN1 usually_RR requires_VVZ for_IF the_AT investor_NN1 to_TO increase_VVI its_APPGE amortization_NN1 or_CC a_AT1 larger_JJR share_NN1 of_IO equity_NN1 ._. 
</s>
<s>
(_( Brueggeman_NN1 and_CC Fisher_NP1 2008_MC ,_, 386._MC )_) 2.5_MC Maturity_NN1 risk_NN1 Maturity_NN1 risk_NN1 is_VBZ closely_RR linked_VVN to_II the_AT interest_NN1 rate_NN1 risk_NN1 (_( see_VV0 chapter_NN1 4.3.9_MC )_) ._. 
</s>
<s>
Maturity_NN1 means_VVZ the_AT length_NN1 of_IO the_AT loan_NN1 period_NN1 ,_, which_DDQ it_PPH1 is_VBZ amortized_VVN ._. 
</s>
<s>
The_AT maturity_NN1 risk_NN1 occurs_VVZ when_RRQ interest_NN1 increase_NN1 for_REX21 instance_REX22 ._. 
</s>
<s>
Ultimately_RR ,_, this_DD1 means_VVZ that_CST the_AT length_NN1 of_IO the_AT loan_NN1 period_NN1 increases_NN2 and_CC causes_VVZ more_DAR interest_NN1 payments_NN2 to_II the_AT investor_NN1 ._. 
</s>
<s>
(_( Niskanen_NP1 and_CC Niskanen_NP1 2007_MC ,_, 32_MC ._. )_) 
</s>
<s>
Maturity_NN1 risk_NN1 is_VBZ highly_RR dependent_JJ on_II the_AT current_JJ economic_JJ welfare_NN1 ._. 
</s>
<s>
If_CS an_AT1 economy_NN1 fell_VVD into_II recession_NN1 like_II the_AT Finnish_JJ economy_NN1 has_VHZ during_II the_AT years_NNT2 of_IO 2009_MC 2010_MC ,_, it_PPH1 does_VDZ not_XX necessarily_RR mean_VVI that_CST the_AT investors_NN2 are_VBR facing_VVG a_AT1 risk_NN1 ._. 
</s>
<s>
For_REX21 instance_REX22 ,_, the_AT current_JJ trend_NN1 seemed_VVD to_TO be_VBI a_AT1 decrease_NN1 in_II interest_NN1 rates_NN2 in_BCL21 order_BCL22 to_TO increase_VVI spending_NN1 ._. 
</s>
<s>
This_DD1 resulted_VVD in_II an_AT1 increase_NN1 in_II demand_NN1 for_IF private_JJ housing_NN1 ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 ,_, banks_NN2 were_VBDR less_RGR keen_JJ to_TO provide_VVI financing_VVG to_II institutional_JJ investors_NN2 ,_, as_CSA there_EX was_VBDZ much_DA1 uncertainty_NN1 ._. 
</s>
<s>
2.6_MC Liquidity_NN1 risk_NN1 Liquidity_NN1 risk_NN1 refers_VVZ to_II a_AT1 risk_NN1 arising_VVG from_II the_AT challenges_NN2 to_TO transform_VVI a_AT1 real_JJ estate_NN1 quickly_RR into_II capital_NN1 ._. 
</s>
<s>
The_AT presence_NN1 of_IO liquidity_NN1 risk_NN1 is_VBZ continuous_JJ in_II a_AT1 market_NN1 ,_, where_CS there_EX are_VBR many_DA2 buyers_NN2 and_CC sellers_NN2 but_CCB few_DA2 actual_JJ transactions_NN2 ._. 
</s>
<s>
The_AT harder_JJR it_PPH1 is_VBZ to_TO transform_VVI an_AT1 investment_NN1 into_II capital_NN1 ,_, the_AT greater_JJR the_AT risk_NN1 that_CST the_AT price_NN1 concessions_NN2 may_VM be_VBI given_VVN to_II another_DD1 investor_NN1 ._. 
</s>
<s>
This_DD1 may_VM occur_VVI when_RRQ the_AT investor_NN1 needs_VVZ to_TO sell_VVI the_AT real_JJ estate_NN1 quickly_RR ._. 
</s>
<s>
In_II general_JJ terms_NN2 ,_, real_JJ estates_NN2 tend_VV0 to_TO have_VHI a_AT1 higher_JJR liquidity_NN1 risk_NN1 than_CSN other_JJ investment_NN1 opportunities_NN2 ,_, since_CS properties_NN2 are_VBR harder_JJR to_TO sell_VVI ._. 
</s>
<s>
(_( Brueggeman_NN1 and_CC Fisher_NP1 2008_MC ,_, 386._MC )_) 2.7_MC Inflation_NN1 risk_NN1 Inflation_NN1 is_VBZ defined_VVN as_II the_AT decrease_NN1 in_II the_AT value_NN1 of_IO money_NN1 ._. 
</s>
<s>
The_AT rapid_JJ growth_NN1 in_II inflation_NN1 may_VM reduce_VVI the_AT investors_NN2 expected_JJ yield_NN1 ._. 
</s>
<s>
If_CS the_AT return_NN1 on_II investment_NN1 does_VDZ not_XX increase_VVI at_II the_AT same_DA pace_NN1 as_CSA inflation_NN1 does_VDZ ,_, then_RT it_PPH1 is_VBZ not_XX enough_RR to_TO offset_VVI inflation_NN1 and_CC the_AT value_NN1 of_IO the_AT real_JJ estate_NN1 decreases_VVZ ._. 
</s>
<s>
The_AT impact_NN1 of_IO inflation_NN1 for_IF different_JJ types_NN2 of_IO investment_NN1 opportunities_NN2 has_VHZ alternative_JJ effects_NN2 ._. 
</s>
<s>
Some_DD investments_NN2 tend_VV0 to_TO have_VHI a_AT1 positive_JJ correlation_NN1 to_II inflation_NN1 ,_, some_DD negative_JJ ._. 
</s>
<s>
Looking_VVG at_II historical_JJ data_NN ,_, it_PPH1 is_VBZ clear_JJ that_CST real_JJ estates_NN2 have_VH0 generally_RR performed_VVN well_RR during_II high_JJ inflation_NN1 ._. 
</s>
<s>
(_( Brueggeman_NN1 and_CC Fisher_NP1 2008_MC ,_, 386._MC )_) 2.8_MC Administrative_JJ risk_NN1 A_ZZ1 real_JJ estate_NN1 ,_, like_II any_DD other_JJ ,_, has_VHZ the_AT need_NN1 for_IF maintenance_NN1 and_CC management_NN1 in_BCL21 order_BCL22 to_TO maintain_VVI its_APPGE condition_NN1 and_CC its_APPGE value_NN1 ._. 
</s>
<s>
The_AT return_NN1 ,_, which_DDQ the_AT investor_NN1 earns_VVZ ,_, is_VBZ very_RG closely_RR dependent_JJ on_II the_AT qualifications_NN2 of_IO the_AT property_NN1 manager_NN1 ._. 
</s>
<s>
Administrative_JJ risk_NN1 therefore_RR occurs_VVZ when_RRQ the_AT property_NN1 manager_NN1 lacks_VVZ the_AT necessary_JJ skills_NN2 to_TO maintain_VVI the_AT real_JJ estate_NN1 ._. 
</s>
<s>
As_II a_AT1 result_NN1 of_IO this_DD1 ,_, the_AT value_NN1 of_IO the_AT real_JJ estate_NN1 decreases_VVZ ._. 
</s>
<s>
This_DD1 risk_NN1 is_VBZ based_VVN on_II how_RRQ facility_NN1 management_NN1 can_VM be_VBI more_RGR innovative_JJ ,_, to_TO compete_VVI in_II the_AT best_JJT possible_JJ way_NN1 and_CC practice_NN1 business_NN1 operations_NN2 effectively_RR ._. 
</s>
<s>
(_( Brueggeman_NN1 and_CC Fisher_NP1 2008_MC ,_, 386_MC ._. )_) 
</s>
<s>
Cost_VV0 Benchmarking_NN1 is_VBZ also_RR an_AT1 important_JJ part_NN1 of_IO managing_VVG the_AT administrative_JJ risk_NN1 ._. 
</s>
<s>
By_II cost_NN1 benchmarking_NN1 it_PPH1 is_VBZ meant_VVN that_CST how_RRQ the_AT investor_NN1 is_VBZ able_JK to_TO optimally_RR manage_VVI the_AT building_NN1 's_GE maintenance_NN1 costs_NN2 ._. 
</s>
<s>
Such_DA action_NN1 ,_, from_II the_AT investment_NN1 perspective_NN1 ,_, is_VBZ effective_JJ use_NN1 of_IO capital_NN1 in_II real_JJ estate_NN1 ,_, because_CS then_RT the_AT investor_NN1 eliminates_VVZ unnecessary_JJ costs_NN2 ._. 
</s>
<s>
Costs_NN2 incurred_VVN through_II facility_NN1 maintenance_NN1 in_II a_AT1 long-term_JJ serve_VV0 to_TO minimize_VVI unnecessary_JJ costs_NN2 ._. 
</s>
<s>
This_DD1 is_VBZ an_AT1 effective_JJ way_NN1 to_TO improve_VVI the_AT profitability_NN1 of_IO capital_NN1 invested_VVN in_II the_AT real_JJ estate_NN1 and_CC its_APPGE productivity_NN1 ._. 
</s>
<s>
(_( Cost_VV0 Benchmarking_NN1 2010_MC ._. )_) 
</s>
<s>
Cost_VV0 Benchmarking_NN1 can_VM be_VBI divided_VVN into_II two_MC distinct_JJ parts_NN2 ._. 
</s>
<s>
The_AT first_MD part_NN1 consists_VVZ of_IO the_AT office_NN1 buildings_NN2 ,_, which_DDQ include_VV0 the_AT following_JJ :_: office_NN1 ,_, retail_JJ ,_, industrial_JJ building_NN1 ,_, industrial_JJ warehouse_NN1 ,_, industrial_JJ and_CC small_JJ industrial_JJ estates_NN2 ._. 
</s>
<s>
The_AT second_MD part_NN1 of_IO the_AT cost_NN1 benchmarking_NN1 includes_VVZ the_AT residential_JJ real_JJ estates_NN2 including_II the_AT following_JJ :_: apartment_NN1 ,_, residential_JJ ,_, commercial_JJ and_CC terraced_JJ properties_NN2 ._. 
</s>
<s>
The_AT benefits_NN2 from_II the_AT cost_NN1 comparison_NN1 ,_, include_VV0 such_DA facts_NN2 that_CST it_PPH1 provides_VVZ a_AT1 practical_JJ tool_NN1 that_CST investors_NN2 can_VM use_VVI to_TO compare_VVI the_AT costs_NN2 of_IO the_AT various_JJ buildings_NN2 to_II each_PPX221 other_PPX222 ._. 
</s>
<s>
(_( Cost_VV0 Benchmarking_NN1 2010._MC )_) 2.9_MC Interest_NN1 rate_NN1 risk_NN1 Interest_NN1 rate_NN1 risk_NN1 refers_VVZ to_II activities_NN2 that_CST measure_VV0 the_AT sensitivity_NN1 of_IO the_AT return_NN1 as_II the_AT interest_NN1 rates_NN2 change_VV0 ._. 
</s>
<s>
This_DD1 means_VVZ that_CST the_AT interest_NN1 rate_NN1 changes_NN2 bring_VV0 uncertainty_NN1 about_II the_AT potential_JJ income_NN1 and_CC expenses_NN2 ._. 
</s>
<s>
In_II real_JJ estate_NN1 ,_, as_CSA interest_NN1 rates_NN2 increase_VV0 ,_, the_AT cost_NN1 of_IO investing_JJ increases_NN2 since_CS the_AT foreign_JJ capital_NN1 becomes_VVZ expensive_JJ ._. 
</s>
<s>
Changes_NN2 in_II interest_NN1 rates_NN2 affect_VV0 all_DB securities_NN2 and_CC other_JJ types_NN2 of_IO investment_NN1 opportunities_NN2 ._. 
</s>
<s>
Depending_II21 on_II22 the_AT investments_NN2 maturity_NN1 ,_, whether_CSW it_PPH1 is_VBZ long-term_JJ or_CC short-term_JJ ,_, and_CC the_AT change_NN1 in_II the_AT price_NN1 of_IO the_AT investment_NN1 opportunity_NN1 can_VM greater_JJR than_CSN compared_VVN to_II other_JJ investments_NN2 ._. 
</s>
<s>
Real_JJ estates_NN2 are_VBR very_RG influential_JJ to_II changes_NN2 in_II interest_NN1 rates_NN2 ,_, and_CC therefore_RR the_AT return_NN1 on_II the_AT investment_NN1 to_II investors_NN2 may_VM change_VVI as_II the_AT interest_NN1 rate_NN1 changes_NN2 ._. 
</s>
<s>
(_( Brueggeman_NN1 and_CC Fisher_NP1 2008_MC ,_, 386_MC ._. )_) 
</s>
<s>
Interest_NN1 rates_NN2 may_VM either_RR be_VBI fixed_VVN ,_, floating_VVG or_CC variable_NN1 during_II the_AT whole_JJ maturity_NN1 of_IO the_AT credit_NN1 agreement_NN1 ._. 
</s>
<s>
In_II a_AT1 variable_JJ rate_NN1 ,_, generally_RR a_AT1 reference_NN1 interest_NN1 rate_NN1 and_CC contract-interest_JJ margin_NN1 is_VBZ agreed_VVN upon_II ._. 
</s>
<s>
For_REX21 example_REX22 ,_, if_CS the_AT reference_NN1 rate_NN1 is_VBZ 3%_NNU and_CC interest_NN1 rate_NN1 margin_NN1 of_IO 1.4%_FO ,_, then_RT the_AT interest_NN1 rate_NN1 payable_JJ under_II the_AT contract_NN1 is_VBZ a_AT1 total_NN1 of_IO 4.4%_FO ._. 
</s>
<s>
Credit_NN1 agreements_NN2 always_RR agree_VV0 upon_II what_DDQ reference_NN1 rate_NN1 is_VBZ used_VVN ._. 
</s>
<s>
Different_JJ reference_NN1 rates_NN2 are_VBR the_AT Euribor_NN1 ,_, Libor_NP1 and_CC the_AT prime_JJ rate_NN1 ._. 
</s>
<s>
(_( Leppiniemi_NP1 2002_MC ,_, 90._MC )_) 2.10_MC Legislative_JJ risk_NN1 Real_JJ estates_NN2 are_VBR responsible_JJ for_IF several_DA2 acts_NN2 ,_, which_DDQ affect_VV0 taxes_NN2 ,_, leasing_VVG and_CC planning_NN1 ,_, as_II31 well_II32 as_II33 other_JJ constraints_NN2 imposed_VVN by_II the_AT State_NN1 ._. 
</s>
<s>
Legislative_JJ risk_NN1 is_VBZ current_JJ when_CS the_AT government_NN1 alters_VVZ the_AT legislation_NN1 in_II a_AT1 way_NN1 that_CST may_VM have_VHI a_AT1 negative_JJ impact_NN1 on_II return_NN1 on_II investment_NN1 ._. 
</s>
<s>
(_( Brueggeman_NN1 and_CC Fisher_NP1 2008_MC ,_, 387_MC ._. )_) 
</s>
<s>
Legislative_JJ risk_NN1 is_VBZ essential_JJ when_CS seeking_VVG to_TO determine_VVI the_AT default_NN1 interest_NN1 rate_NN1 margin_NN1 ._. 
</s>
<s>
The_AT law_NN1 for_IF different_JJ types_NN2 of_IO contracts_NN2 provides_VVZ the_AT interest_NN1 rate_NN1 arrears_NN2 margin_NN1 and_CC it_PPH1 is_VBZ an_AT1 essential_JJ form_NN1 of_IO risk_NN1 to_II the_AT investor_NN1 ._. 
</s>
<s>
(_( Leppiniemi_NP1 2002_MC ,_, 91._MC )_) 2.11_MC Environmental_JJ risk_NN1 Environmental_JJ risks_NN2 that_CST relate_VV0 to_II the_AT value_NN1 of_IO the_AT property_NN1 include_VV0 unexpected_JJ environmental_JJ changes_NN2 ,_, or_CC findings_NN2 that_CST could_VM harm_VVI the_AT environment_NN1 and_CC property_NN1 ._. 
</s>
<s>
For_REX21 example_REX22 ,_, before_CS there_EX was_VBDZ a_AT1 tendency_NN1 to_TO use_VVI asbestos_NN1 as_CSA insulation_NN1 for_IF properties_NN2 ,_, but_CCB today_RT asbestos_NN1 is_VBZ considered_VVN highly_RR toxic_JJ and_CC potentially_RR lethal_JJ ._. 
</s>
<s>
Environmental_JJ risk_NN1 compared_VVN to_II other_JJ types_NN2 of_IO risks_NN2 could_VM cause_VVI more_DAR losses_NN2 for_IF investors_NN2 ,_, because_CS the_AT property_NN1 owner_NN1 is_VBZ responsible_JJ for_IF building_NN1 and_CC repairing_VVG and_CC cleaning_VVG the_AT work_NN1 can_VM easily_RR exceed_VVI the_AT value_NN1 of_IO your_APPGE property_NN1 ._. 
</s>
<s>
This_DD1 type_NN1 of_IO risk_NN1 exists_VVZ when_RRQ the_AT property_NN1 is_VBZ located_VVN in_II an_AT1 area_NN1 where_CS there_EX are_VBR earthquakes_NN2 or_CC hurricanes_NN2 ,_, which_DDQ can_VM cause_VVI damage_NN1 to_II the_AT property_NN1 ._. 
</s>
<s>
(_( Brueggeman_NN1 and_CC Fisher_NP1 2008_MC ,_, 387._MC )_) 3_MC Benefits_NN2 and_CC Disadvantages_NN2 There_EX are_VBR several_DA2 benefits_NN2 and_CC disadvantages_NN2 to_TO direct_VVI investment_NN1 to_II real_JJ estate_NN1 as_II31 well_II32 as_II33 leasing_VVG arrangements_NN2 ._. 
</s>
<s>
In_II this_DD1 chapter_NN1 these_DD2 benefits_NN2 and_CC disadvantages_NN2 are_VBR investigated_VVN more_RGR carefully_RR ._. 
</s>
<s>
3.1_MC Lease_NN1 Benefits_NN2 Describing_VVG the_AT benefits_NN2 of_IO leasing_VVG 3.2_MC Lease_NN1 Disadvantages_NN2 Describing_VVG the_AT disadvantages_NN2 of_IO leasing_VVG 3.3_MC Buying_NN1 Benefits_NN2 Benefits_NN2 of_IO ownership_NN1 3.4_MC Buying_NN1 Disadvantages_NN2 Disadvantages_NN2 of_IO ownership_NN1 4_MC Conclusions_NN2 Concluding_VVG remarks_NN2 
</s>
