<s>
Wage_NN1 Equation_NN1 1_MC1 Introduction_NN1 The_AT main_JJ objective_NN1 behind_II this_DD1 paper_NN1 is_VBZ to_TO examine_VVI closely_RR the_AT aggregate_JJ wage_NN1 rate_NN1 (_( also_RR known_VVN as_II real_JJ wage_NN1 rate_NN1 )_) and_CC study_VV0 a_AT1 model_NN1 that_CST examines_VVZ it_PPH1 ._. 
</s>
<s>
Ear-_JJ lier_NN1 studies_NN2 have_VH0 examined_VVN the_AT wage_NN1 equation_NN1 by_II including_VVG measures_NN2 of_IO union_NN1 power_NN1 ,_, unemployment_NN1 benefits_NN2 ,_, tax_NN1 rates_NN2 ,_, structural_JJ mismatch_NN1 and_CC productiv-_JJ ity_NN1 &lsqb;_( Manning_NP1 (_( 1993_MC )_) &rsqb;_) &lsqb;_( Nickell_NP1 and_CC Andrews_NP1 (_( 1983_MC )_) &rsqb;_) ._. 
</s>
<s>
Hall_NN1 (_( 1986_MC )_) studied_VVD the_AT UK_NP1 aggregated_JJ wage_NN1 rate_NN1 instead_RR ,_, using_VVG consumer_NN1 price_NN1 index_NN1 ,_, unemployment_NN1 rate_NN1 ,_, aggregate_JJ productivity_NN1 and_CC average_JJ weekly_JJ hours_NNT2 ._. 
</s>
<s>
Differing_VVG from_II this_DD1 I_PPIS1 have_VH0 chosen_VVN a_AT1 wage_NN1 equation_NN1 where_CS I_PPIS1 will_VM examine_VVI how_RRQ unemployment_NN1 ,_, productivity_NN1 ,_, tax_NN1 wedge_NN1 and_CC inflation_NN1 impacts_NN2 the_AT real_JJ wage_NN1 ._. 
</s>
<s>
The_AT basic_JJ idea_NN1 behind_II this_DD1 is_VBZ to_TO test_VVI if_CSW the_AT mentioned_VVN variables_NN2 are_VBR stationary_JJ in_II their_APPGE second_MD differences_NN2 ,_, since_CS it_PPH1 is_VBZ a_AT1 requirement_NN1 for_IF doing_VDG OLS_NN2 (_( Ordinary_JJ Least_DAT Squares_NN2 )_) regression_NN1 ._. 
</s>
<s>
A_AT1 study_NN1 of_IO this_DD1 is_VBZ interesting_JJ ,_, since_CS recognition_NN1 of_IO the_AT interrelationships_NN2 can_VM help_VVI formatting_VVG policies_NN2 that_CST increases_VVZ benefits_NN2 considering_II society_NN1 and_CC corporations_NN2 ._. 
</s>
<s>
The_AT equation_NN1 studied_VVN is_VBZ given_VVN by_II :_: &lsqb;_( Formula_NN1 &rsqb;_) Logarithms_NN2 are_VBR taken_VVN of_IO the_AT series_NN persumed_VVD to_TO exhibit_VVI growth_NN1 ,_, that_REX21 is_REX22 ,_, all_RR21 but_RR22 unemployment_NN1 ._. 
</s>
<s>
The_AT general_JJ expectations_NN2 of_IO the_AT variables_NN2 and_CC their_APPGE behaviors_NN2 are_VBR that_DD1 unemployment_NN1 and_CC the_AT tax_NN1 wedge_NN1 will_VM decrease_VVI the_AT wage_NN1 ,_, while_CS produc-_JJ tivity_NN1 and_CC inflation_NN1 should_VM increase_VVI the_AT wage_NN1 ._. 
</s>
<s>
The_AT reasoning_NN1 behind_II this_DD1 is_VBZ that_CST higher_JJR employment_NN1 and_CC greater_JJR tax_NN1 wedge_NN1 should_VM lower_VVI the_AT wages_NN2 ,_, whilst_CS higher_JJR productivity_NN1 and_CC inflation_NN1 is_VBZ thought_VVN to_TO increase_VVI the_AT wages_NN2 ._. 
</s>
<s>
The_AT coefficients_NN2 are_VBR expected_VVN to_TO :_: &lsqb;_( Formula_NN1 &rsqb;_) The_AT main_JJ question_NN1 is_VBZ whether_CSW the_AT general_JJ expectations_NN2 of_IO the_AT variables_NN2 and_CC their_APPGE relationships_NN2 to_II the_AT real_JJ wage_NN1 can_VM be_VBI proven_VVN correct_JJ ,_, or_CC if_CS there_EX are_VBR some_DD differences_NN2 between_II general_JJ expectations_NN2 and_CC the_AT data_NN estimations_NN2 ._. 
</s>
<s>
The_AT other_JJ question_NN1 I_PPIS1 will_VM try_VVI to_TO answer_VVI is_VBZ that_CST if_CS there_EX are_VBR differences_NN2 between_II data_NN es-_JJ timations_NN2 and_CC general_JJ expectations_NN2 ,_, why_RRQ it_PPH1 is_VBZ so_RR and_CC are_VBR there_EX some_DD general_JJ explanations_NN2 to_II this_DD1 ._. 
</s>
<s>
The_AT main_JJ focus_NN1 in_II this_DD1 case_NN1 is_VBZ Finland_NP1 and_CC the_AT data_NN used_VVN is_VBZ quarterly_JJ data_NN between_II 1975_MC and_CC 2007_MC ._. 
</s>
<s>
The_AT OECD_NP1 database_NN1 and_CC ETLA_NP1 are_VBR the_AT main_JJ sources_NN2 for_IF the_AT data_NN used_VVN in_II the_AT estimation_NN1 of_IO the_AT wage_NN1 equation_NN1 ._. 
</s>
<s>
The_AT remainder_NN1 of_IO this_DD1 paper_NN1 is_VBZ divided_VVN into_II 5_MC sections_NN2 ._. 
</s>
<s>
Section_NN1 2_MC describes_VVZ the_AT data_NN used_VVN in_II this_DD1 study_NN1 ._. 
</s>
<s>
Section_NN1 3_MC describes_VVZ the_AT unit_NN1 root_NN1 and_CC stationarity_NN1 tests_NN2 ,_, while_CS section_NN1 4_MC looks_VVZ at_II cointegration_NN1 and_CC the_AT error_NN1 correction_NN1 model_NN1 ._. 
</s>
<s>
The_AT final_JJ section_NN1 consists_VVZ of_IO a_AT1 discussion_NN1 conserning_VVG the_AT results._NNU 2_MC The_AT Data_NN The_AT data_NN used_VMK to_TO estimate_VVI the_AT wage_NN1 equation_NN1 is_VBZ Finnish_JJ quarterly_JJ data_NN from_II the_AT time_NNT1 period_NN1 1975-2007_MCMC ._. 
</s>
<s>
The_AT data_NN is_VBZ gathered_VVN from_II the_AT OECD_NP1 's_GE database_NN1 ,_, from_II "_" OECD_NP1 Economic_JJ Outlook_NN1 Data_NN "_" ,_, "_" Main_JJ Economic_JJ Indicators_NN2 "_" and_CC "_" National_JJ Accounts_NN2 Data_NN "_" ,_, and_CC from_II ETLA_NP1 's_GE "_" Kotimaiset_NN1 Aineistot_NN1 "_" -database_NN1 ._. 
</s>
<s>
Before_II doing_VDG a_AT1 OLS_NN2 regression_NN1 and_CC studying_VVG stationarity_NN1 the_AT series_NN used_VVN are_VBR presented_VVN graphically_RR ._. 
</s>
<s>
By_II this_DD1 the_AT possible_JJ trends_NN2 and_CC breaks_NN2 will_VM hopefully_RR be_VBI identified_VVN so_CS21 that_CS22 one_PN1 can_VM improve_VVI the_AT model_NN1 if_CS needed_VVN ._. 
</s>
<s>
In_II the_AT first_MD figure_NN1 1_MC1 the_AT individual_JJ series_NN are_VBR plotted_VVN against_II time_NNT1 ._. 
</s>
<s>
From_II all_DB series_NN except_II21 for_II22 unemployment_NN1 ,_, there_EX can_VM be_VBI seen_VVN a_AT1 trend_NN1 of_IO growth_NN1 over_II time_NNT1 ._. 
</s>
<s>
From_II the_AT graphs_NN2 one_PN1 can_VM also_RR see_VVI a_AT1 very_RG clear_JJ break_NN1 in_II the_AT series_NN in_II the_AT beginning_NN1 of_IO 1990_MC 's_GE ._. 
</s>
<s>
This_DD1 break_NN1 is_VBZ very_RG visible_JJ in_II unemployment_NN1 and_CC total_JJ employment_NN1 ,_, but_CCB one_PN1 can_VM also_RR see_VVI a_AT1 shift_NN1 in_II the_AT gross_JJ domestic_JJ product_NN1 ._. 
</s>
<s>
The_AT reason_NN1 for_IF this_DD1 break_NN1 is_VBZ obviously_RR the_AT early_JJ 1990_MC221 's_MC222 economic_JJ depression_NN1 ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) 5_MC The_AT second_MD figure_NN1 2_MC is_VBZ showing_VVG graphs_NN2 where_RRQ the_AT combined_JJ series_NN are_VBR plot-_JJ ted_NN1 against_II time_NNT1 ._. 
</s>
<s>
From_II these_DD2 one_PN1 can_VM also_RR clearly_RR see_VVI the_AT impact_NN1 of_IO the_AT 1990_MC221 's_MC222 depression_NN1 ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) 3_MC Unit_NN1 Root_NN1 and_CC Stationarity_NP1 Tests_VVZ The_AT important_JJ thing_NN1 before_II estimating_VVG the_AT wage_NN1 equation_NN1 in_II itself_PPX1 ,_, is_VBZ to_TO test_VVI the_AT series_NN ,_, included_VVN in_II the_AT equation_NN1 ,_, for_IF stationarity_NN1 ._. 
</s>
<s>
Stationarity_NN1 implies_VVZ often_RR stability_NN1 and_CC that_CST the_AT series_NN converges_VVZ to_II an_AT1 equilibrium_NN1 ._. 
</s>
<s>
From_II this_DD1 one_PN1 can_VM say_VVI that_CST if_CS non-stationarity_NN1 is_VBZ found_VVN then_RT making_VVG economic_JJ translation_NN1 becomes_VVZ meaningless_JJ ._. 
</s>
<s>
Thus_RR controlling_VVG for_IF stationarity_NN1 is_VBZ a_AT1 necessity_NN1 before_II performing_VVG a_AT1 time_NNT1 series_NN analysis_NN1 ._. 
</s>
<s>
The_AT stationarity_NN1 and_CC its_APPGE "_" strength_NN1 "_" is_VBZ much_DA1 dependent_NN1 of_IO the_AT time_NNT1 series_NN mean_VV0 and_CC auto-covariance_NN1 and_CC how_RRQ it_PPH1 relates_VVZ to_II t_ZZ1 ._. 
</s>
<s>
It_PPH1 can_VM be_VBI said_VVN that_CST a_AT1 time_NNT1 series_NN is_VBZ weakly_RR stationary_JJ if_CS the_AT mean_JJ and_CC auto-covariance_NN1 are_VBR not_XX dependent_JJ of_IO t_ZZ1 and_CC if_CS there_EX is_VBZ no_AT change_NN1 in_II the_AT stationarity_NN1 over_II time_NNT1 ._. 
</s>
<s>
It_PPH1 can_VM be_VBI concluded_VVN that_CST a_AT1 series_NN is_VBZ stationary_JJ and_CC will_VM be_VBI integrated_VVN of_IO order_NN1 0_MC ,_, I(0)_FO ,_, and_CC a_AT1 series_NN is_VBZ integrated_VVN of_IO order_NN1 d_ZZ1 ,_, I(d)_NN1 ,_, if_CS the_AT d_ZZ1 :_: th_NNU difference_NN1 is_VBZ I(0)_FO &lsqb;_( Engle_NP1 and_CC Granger_NP1 (_( 1987_MC )_) &rsqb;_) ._. 
</s>
<s>
One_MC1 way_NN1 to_TO analyze_VVI the_AT stationarity_NN1 process_NN1 is_VBZ by_II using_VVG unit_NN1 root_NN1 processing_NN1 ,_, which_DDQ is_VBZ the_AT one_PN1 used_VVD in_II this_DD1 term_NN1 paper_NN1 ._. 
</s>
<s>
One_MC1 simple_JJ example_NN1 of_IO the_AT unit_NN1 root_NN1 process_NN1 is_VBZ the_AT random_JJ walk_NN1 :_: &lsqb;_( Formula_NN1 &rsqb;_) with_IW the_AT mean_JJ zero_NN1 ._. 
</s>
<s>
The_AT random_JJ walk_NN1 is_VBZ I(1)_FO ,_, which_DDQ implies_VVZ that_CST the_AT first_MD difference_NN1 &lsqb;_( Formula_NN1 &rsqb;_) &lsqb;_( Hendry_NP1 (_( 1986_MC )_) &rsqb;_) ._. 
</s>
<s>
The_AT conclusions_NN2 that_CST can_VM be_VBI drawn_VVN from_II a_AT1 unit_NN1 root_NN1 test_NN1 is_VBZ that_CST if_CS there_EX exists_VVZ a_AT1 unit_NN1 root_NN1 the_AT process_NN1 is_VBZ non-stationary_JJ ._. 
</s>
<s>
One_MC1 way_NN1 of_IO testing_VVG this_DD1 is_VBZ by_II using_VVG a_AT1 Dickey-Fuller_NP1 test_NN1 ,_, where_CS the_AT model_NN1 is_VBZ rewritten_VVN to_II &lsqb;_( Formula_NN1 &rsqb;_) Another_DD1 variant_NN1 of_IO the_AT model_NN1 with_IW a_AT1 more_RGR general_JJ lag_NN1 structure_NN1 is_VBZ the_AT Augmented_VVN Dickey-Fuller_NP1 test_NN1 (_( ADF-test_NN1 )_) and_CC it_PPH1 is_VBZ used_VVN as_CSA follows_VVZ :_: &lsqb;_( Formula_NN1 &rsqb;_) 3.1_MC ADF-test_NN1 of_IO the_AT Individual_JJ Time_NNT1 Series_NN Economic_JJ time_NNT1 series_NN are_VBR at_II their_APPGE most_RGT I(2)_FO ,_, which_DDQ implies_VVZ that_CST their_APPGE second_MD difference_NN1 must_VM be_VBI I(0)_FO ,_, which_DDQ instead_RR implies_VVZ a_AT1 stationary_JJ process_NN1 ._. 
</s>
<s>
Thus_RR if_CS the_AT first_MD differences_NN2 are_VBR I(0)_FO the_AT series_NN would_VM be_VBI I(1)_FO ._. 
</s>
<s>
If_CS there_EX exists_VVZ a_AT1 unit_NN1 root_NN1 and_CC the_AT first_MD difference_NN1 is_VBZ I(1)_FO the_AT series_NN in_II itself_PPX1 is_VBZ I(2)_FO ._. 
</s>
<s>
From_II this_DD1 it_PPH1 becomes_VVZ clear_JJ that_CST the_AT first_MD step_NN1 is_VBZ to_TO test_VVI whether_CSW the_AT individual_JJ series_NN are_VBR I(1)_FO or_CC I(2)_FO ._. 
</s>
<s>
The_AT first_MD differences_NN2 of_IO the_AT individual_JJ time_NNT1 series_NN are_VBR tested_VVN using_VVG the_AT ADF-_JJ test_NN1 under_II the_AT null_JJ hypothesis_NN1 "_" there_EX exists_VVZ a_AT1 unit_NN1 root_NN1 "_" and_CC the_AT results_NN2 are_VBR given_VVN on_II the_AT left_JJ part_NN1 of_IO the_AT table_NN1 1_MC1 ._. 
</s>
<s>
If_CS the_AT null_JJ hypothesis_NN1 can_VM not_XX be_VBI rejected_VVN ,_, it_PPH1 is_VBZ assumed_VVN that_CST the_AT series_NN are_VBR I(2)_FO ._. 
</s>
<s>
If_CS the_AT null_JJ hypothesis_NN1 can_VM be_VBI rejected_VVN ,_, the_AT stationarity_NN1 levels_NN2 needs_VVZ to_TO be_VBI tested_VVN ._. 
</s>
<s>
If_CS that_DD1 null_JJ hypothesis_NN1 can_VM not_XX be_VBI rejected_VVN the_AT variables_NN2 are_VBR assumed_VVN to_TO be_VBI I(0)_FO and_CC stationary_JJ ._. 
</s>
<s>
These_DD2 results_NN2 are_VBR given_VVN on_II the_AT right_JJ side_NN1 of_IO the_AT table_NN1 1_MC1 ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) The_AT t-value_NN1 has_VHZ been_VBN chosen_VVN as_II the_AT lag_NN1 length_NN1 with_IW least_DAT information_NN1 loss_NN1 according_II21 to_II22 the_AT Akaike_NP1 criteria_NN2 ._. 
</s>
<s>
The_AT test_NN1 show_VV0 that_DD1 unemployment_NN1 and_CC producer_NN1 price_NN1 index_NN1 would_VM not_XX be_VBI I(2)_FO ._. 
</s>
<s>
For_IF the_AT other_JJ variables_NN2 the_AT null_JJ hypothesis_NN1 cannott_NN1 be_VBI rejected_VVN which_DDQ would_VM mean_VVI that_CST they_PPHS2 would_VM be_VBI I(2)_FO ._. 
</s>
<s>
The_AT level_NN1 of_IO unemployment_NN1 and_CC producer_NN1 price_NN1 index_NN1 were_VBDR tested_VVN by_II adding_VVG a_AT1 trend_NN1 ,_, since_CS there_EX is_VBZ a_AT1 reason_NN1 to_TO expect_VVI linear_JJ growth_NN1 in_II the_AT measures_NN2 ,_, eg._REX wages_NN2 have_VH0 a_AT1 tendency_NN1 of_IO growing_VVG in_II a_AT1 long-run_JJ ._. 
</s>
<s>
Tests_NN2 indicates_VVZ that_CST both_RR series_NN would_VM be_VBI I(1)._FO 3.2_MC ADF-test_NN1 of_IO the_AT Combined_JJ Time_NNT1 Series_NN After_II testing_VVG the_AT individual_JJ time_NNT1 series_NN ,_, the_AT second_MD step_NN1 is_VBZ to_TO test_VVI the_AT variables_NN2 which_DDQ are_VBR relevant_JJ to_II the_AT wage_NN1 equation_NN1 ._. 
</s>
<s>
In_II other_JJ words_NN2 the_AT real_JJ wage_NN1 is_VBZ ex-_NN1 plained_VVD by_II unemployment_NN1 ,_, productivity_NN1 ,_, tax_NN1 wedge_NN1 and_CC inflation_NN1 ._. 
</s>
<s>
Through_II this_DD1 paper_NN1 following_VVG notation_NN1 of_IO these_DD2 are_VBR used_VVN :_: real_JJ wage_NN1 unemployment_NN1 productivity_NN1 tax_NN1 wedge_NN1 inflation_NN1 The_AT series_NN above_RL are_VBR all_DB constructed_VVN from_II individual_JJ time_NNT1 series_NN ._. 
</s>
<s>
An_AT1 important_JJ thing_NN1 to_TO note_VVI is_VBZ that_CST if_CS individual_JJ series_NN of_IO the_AT same_DA order_NN1 are_VBR integrated_VVN ,_, their_APPGE sum_NN1 is_VBZ most_RGT often_RR of_IO the_AT same_DA order_NN1 or_CC of_IO a_AT1 lower_JJR order_NN1 ._. 
</s>
<s>
If_CS again_RT individual_JJ series_NN of_IO different_JJ orders_NN2 are_VBR integrated_VVN ,_, the_AT sum_NN1 of_IO them_PPHO2 is_VBZ of_IO the_AT higher_JJR order_NN1 &lsqb;_( Engle_NP1 and_CC Granger_NP1 (_( 1987_MC )_) &rsqb;_) ._. 
</s>
<s>
The_AT tests_NN2 done_VDN on_II the_AT individual_JJ time_NNT1 series_NN in_II section_NN1 3.1_MC ,_, indicates_VVZ that_CST the_AT time_NNT1 series_NN would_VM be_VBI integrated_VVN of_IO different_JJ orders_NN2 ._. 
</s>
<s>
Although_CS due_II21 to_II22 the_AT possibility_NN1 of_IO a_AT1 weak_JJ ADF-test_NN1 ,_, the_AT problem_NN1 is_VBZ ignored_VVN for_IF the_AT following_JJ analysis_NN1 ._. 
</s>
<s>
The_AT combined_JJ variables_NN2 are_VBR all_DB tested_VVN in_II the_AT same_DA way_NN1 as_CSA the_AT individual_JJ se-_JJ ries_NN2 in_II the_AT earlier_JJR section_NN1 3.1_MC ,_, using_VVG the_AT null_JJ hypothesis_NN1 "_" there_EX exists_VVZ a_AT1 unit_NN1 root_NN1 "_" ._. 
</s>
<s>
On_II the_AT left_JJ side_NN1 of_IO the_AT table_NN1 2_MC ,_, the_AT results_NN2 of_IO testing_VVG the_AT differences_NN2 are_VBR shown_VVN ,_, and_CC on_II the_AT right_JJ side_NN1 the_AT results_NN2 of_IO testing_VVG the_AT levels_NN2 are_VBR shown_VVN ._. 
</s>
<s>
Unemployment_NN1 was_VBDZ already_RR tested_VVN in_II the_AT earlier_JJR section_NN1 and_CC thus_RR it_PPH1 is_VBZ not_XX tested_VVN here_RL again_RT ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) The_AT t-value_NN1 has_VHZ been_VBN chosen_VVN as_II the_AT lag_NN1 length_NN1 with_IW least_DAT information_NN1 loss_NN1 according_II21 to_II22 the_AT Akaike_NP1 criteria_NN2 ._. 
</s>
<s>
As_II a_AT1 result_NN1 of_IO the_AT tests_NN2 the_AT null_JJ hypothesis_NN1 can_VM be_VBI rejected_VVN for_IF all_DB differences_NN2 ,_, but_CCB not_XX for_IF any_DD of_IO the_AT levels_NN2 ,_, which_DDQ implies_VVZ that_CST all_DB series_NN are_VBR I(1)_FO ._. 
</s>
<s>
From_II this_DD1 we_PPIS2 can_VM conclude_VVI that_CST since_CS &lsqb;_( Formula_NN1 &rsqb;_) and_CC is_VBZ I(1)_FO and_CC when_RRQ is_VBZ I(2)_FO ,_, that_DD1 also_RR is_VBZ I(2)_FO even_CS21 if_CS22 the_AT ADF-test_NN1 could_VM imply_VVI something_PN1 different._NNU 4_MC Co-integration_NN1 and_CC the_AT Error_NN1 Correction_NN1 Model_NN1 The_AT problems_NN2 that_CST occur_VV0 when_CS studying_VVG time_NNT1 series_NN data_NN is_VBZ that_CST the_AT data_NN fluc-_JJ tuates_NN2 and_CC moves_VVZ in_RP and_CC out_RP from_II equilibrium_NN1 ._. 
</s>
<s>
This_DD1 becomes_VVZ a_AT1 problem_NN1 when_CS in_II economic_JJ theory_NN1 and_CC models_NN2 the_AT interests_NN2 rely_VV0 on_II equilibrium_NN1 relations_NN2 ,_, this_DD1 again_RT indicates_VVZ that_CST ordinary_JJ time_NNT1 series_NN '_GE models_NN2 becomes_VVZ useless_JJ when_CS we_PPIS2 want_VV0 to_TO translate_VVI it_PPH1 to_II economic_JJ theory_NN1 ._. 
</s>
<s>
To_TO overcome_VVI this_DD1 problem_NN1 a_AT1 error_NN1 correction_NN1 model_NN1 is_VBZ used_VVN ,_, which_DDQ allows_VVZ the_AT series_NN to_TO show_VVI short-run_JJ fluctuations_NN2 while_CS it_PPH1 still_RR on_II a_AT1 long-run_JJ converges_VVZ to_II a_AT1 equilibrium_NN1 ._. 
</s>
<s>
The_AT condition_NN1 that_CST has_VHZ to_TO be_VBI fulfilled_VVN when_CS using_VVG error_NN1 correction_NN1 models_NN2 is_VBZ to_TO use_VVI co-integrated_JJ time_NNT1 series_NN in_II the_AT models_NN2 &lsqb;_( Engle_NP1 and_CC Granger_NP1 (_( 1987_MC )_) &rsqb;_) ._. 
</s>
<s>
If_CS a_AT1 series_NN are_VBR expected_VVN to_TO co-integrate_VVI they_PPHS2 have_VH0 to_TO individually_RR be_VBI I(1)_FO and_CC non-stationary_JJ ,_, but_CCB the_AT linear_JJ combination_NN1 of_IO them_PPHO2 has_VHZ to_TO be_VBI I(0)_FO and_CC stationary_JJ ._. 
</s>
<s>
An_AT1 example_NN1 of_IO this_DD1 is_VBZ that_CST there_EX is_VBZ a_AT1 vector_NN1 ,_, ,_, of_IO a_AT1 time_NNT1 series_NN that_CST is_VBZ I(1)_FO and_CC the_AT linear_JJ combination_NN1 ,_, where_RRQ is_VBZ a_AT1 co-integrating_JJ vector_NN1 ,_, is_VBZ stationary_JJ ._. 
</s>
<s>
From_II this_DD1 can_VM then_RT be_VBI said_VVN that_CST the_AT &lsqb;_( Formula_NN1 &rsqb;_) is_VBZ the_AT long-run_JJ equilibrium_NN1 of_IO the_AT time_NNT1 series_NN ._. 
</s>
<s>
It_PPH1 can_VM although_CS be_VBI said_VVN that_CST for_IF the_AT most_DAT t_ZZ1 ,_, is_VBZ not_XX a_AT1 equilibrium_NN1 and_CC for_IF this_DD1 reason_NN1 there_EX is_VBZ a_AT1 equilibrium_NN1 error_NN1 &lsqb;_( Formula_NN1 &rsqb;_) ,_, which_DDQ should_VM be_VBI minimized_VVN in_II the_AT models_NN2 &lsqb;_( Engle_NP1 and_CC Granger_NP1 (_( 1987_MC )_) &rsqb;_) ._. 
</s>
<s>
Since_CS it_PPH1 is_VBZ already_RR clear_JJ from_II section_NN1 3_MC that_CST all_DB the_AT time_NNT1 series_NN that_CST are_VBR inter-_JJ esting_NN1 for_IF the_AT wage_NN1 equation_NN1 study_NN1 ,_, are_VBR all_DB I(1)_FO ,_, the_AT next_MD step_NN1 ,_, before_II formulating_VVG the_AT error_NN1 correction_NN1 model_NN1 ,_, is_VBZ to_TO study_VVI co-integration_NN1 ._. 
</s>
<s>
For_IF doing_VDG this_DD1 here_RL the_AT static_JJ long-run_JJ solution_NN1 model_NN1 is_VBZ used._NNU 4.1_MC Lag_NN1 Length_NN1 and_CC Misspecification_NN1 Tests_VVZ The_AT first_MD step_NN1 is_VBZ to_TO specify_VVI the_AT right_JJ model_NN1 and_CC then_RT to_TO find_VVI the_AT right_JJ lag_NN1 length_NN1 that_CST should_VM be_VBI used_VVN ._. 
</s>
<s>
The_AT model_NN1 used_VVN is_VBZ the_AT same_DA as_CSA presented_VVN in_II the_AT introduction_NN1 in_II section_NN1 1_MC1 and_CC the_AT relationship_NN1 between_II the_AT relevant_JJ variables_NN2 is_VBZ presented_VVN in_II section_NN1 3.2_MC ,_, from_II this_DD1 we_PPIS2 get_VV0 the_AT following_JJ relevant_JJ relationship_NN1 (_( corrected_VVN for_IF seasonality_NN1 and_CC including_II lags_NN2 )_) :_: &lsqb;_( Formula_NN1 &rsqb;_) The_AT lag_NN1 length_NN1 that_CST should_VM be_VBI used_VVN is_VBZ determined_VVN by_II doing_VDG a_AT1 F-test_NN1 using_VVG six_MC lags_NN2 as_II a_AT1 beginning_NN1 point_NN1 ._. 
</s>
<s>
(_( The_AT model_NN1 used_VVN is_VBZ also_RR corrected_VVN for_IF seasonality_NN1 ._. )_) 
</s>
<s>
These_DD2 results_NN2 are_VBR shown_VVN in_II table_NN1 3_MC ,_, where_CS on_II the_AT left_JJ side_NN1 each_DD1 lag_NN1 's_GE significance_NN1 is_VBZ tested_VVN under_II the_AT null_JJ hypothesis_NN1 is_VBZ "_" the_AT lag_NN1 tested_VVN is_VBZ significant_JJ "_" ._. 
</s>
<s>
On_II the_AT right_JJ side_NN1 of_IO the_AT table_NN1 it_PPH1 is_VBZ shown_VVN whether_CSW the_AT models_NN2 with_IW fewer_DAR lags_NN2 is_VBZ a_AT1 part_NN1 of_IO the_AT general_JJ model_NN1 ,_, under_II the_AT null_JJ hypothesis_NN1 is_VBZ "_" the_AT model_NN1 is_VBZ a_AT1 part_NN1 of_IO the_AT general_JJ model_NN1 "_" ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) From_II the_AT test_NN1 where_CS each_DD1 lag_NN1 is_VBZ separately_RR tested_VVN ,_, it_PPH1 is_VBZ shown_VVN that_CST only_RR the_AT first_MD lag_NN1 is_VBZ significant_JJ ,_, but_CCB the_AT second_MD test_NN1 on_II the_AT right_JJ side_NN1 shows_VVZ that_CST there_EX might_VM be_VBI significances_NN2 in_II the_AT second_MD and_CC third_MD lag_NN1 ._. 
</s>
<s>
Since_CS this_DD1 ,_, three_MC lags_NN2 are_VBR included_VVN in_II the_AT model_NN1 ._. 
</s>
<s>
The_AT next_MD step_NN1 is_VBZ to_TO re-estimate_VVI the_AT test_NN1 by_II only_RR using_VVG three_MC lags_NN2 and_CC af-_NN1 ter_RR that_CST the_AT misspecification_NN1 is_VBZ tested_VVN ._. 
</s>
<s>
This_DD1 test_NN1 gives_VVZ measures_NN2 for_IF auto-_JJ correlation_NN1 ,_, auto-regressive_JJ conditional_JJ heteroscedasticity_NN1 (_( ARCH_NN1 )_) ,_, normality_NN1 and_CC heteroscedasticity_NN1 ,_, under_II the_AT null_JJ hypothesis_NN1 is_VBZ "_" there_EX is_VBZ no_AT misspecifica-_JJ tion_NN1 "_" ._. 
</s>
<s>
Results_NN2 are_VBR shown_VVN above_RL in_II table_NN1 4_MC ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) From_II the_AT results_NN2 it_PPH1 can_VM be_VBI seen_VVN that_CST none_PN of_IO the_AT tests_NN2 '_GE null_JJ hypothesis_NN1 can_VM be_VBI rejected_VVN ,_, which_DDQ implies_VVZ that_CST the_AT model_NN1 is_VBZ correctly_RR formulated_VVN and_CC that_CST no_AT misspecification_NN1 occurs_VVZ when_CS using_VVG only_RR three_MC lags_NN2 ._. 
</s>
<s>
This_DD1 will_VM then_RT give_VVI us_PPIO2 the_AT following_JJ model_NN1 :_: &lsqb;_( Formula_NN1 &rsqb;_) 4.2_MC Co-integration_NN1 Test_NN1 As_II the_AT correct_JJ model_NN1 is_VBZ determined_VVN ,_, the_AT following_JJ step_NN1 is_VBZ to_TO control_VVI for_IF possible_JJ co-integration_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ done_VDN by_II using_VVG the_AT static_JJ long-run_JJ solution_NN1 ._. 
</s>
<s>
If_CS the_AT model_NN1 for_IF the_AT equilibrium_NN1 model_NN1 (_( ECM_NP1 )_) is_VBZ stationary_JJ ,_, then_RT the_AT series_NN are_VBR co-integrated_VVN ._. 
</s>
<s>
The_AT stationarity_NN1 is_VBZ determined_VVN with_IW the_AT ADF-test_NN1 ,_, where_CS the_AT null_JJ hypothesis_NN1 is_VBZ "_" there_EX exists_VVZ a_AT1 unit_NN1 root_NN1 "_" ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) The_AT t-value_NN1 has_VHZ been_VBN chosen_VVN as_II the_AT lag_NN1 length_NN1 with_IW least_DAT information_NN1 loss_NN1 according_II21 to_II22 the_AT Akaike_NP1 criteria_NN2 ._. 
</s>
<s>
The_AT test_NN1 indicates_VVZ that_CST the_AT null_JJ hypothesis_NN1 can_VM be_VBI rejected_VVN even_RR on_II a_AT1 1_MC1 %_NNU significance_NN1 level_NN1 ,_, which_DDQ means_VVZ that_CST the_AT equilibrium_NN1 model_NN1 is_VBZ stationary_JJ and_CC that_CST the_AT time_NNT1 series_NN are_VBR cointegrated._NNU 4.3_MC The_AT Error_NN1 Correction_NN1 Model_NN1 From_II all_DB the_AT tests_NN2 done_VDN in_II the_AT earlier_JJR sections_NN2 the_AT following_JJ and_CC last_MD step_NN1 is_VBZ to_TO estimate_VVI the_AT final_JJ error_NN1 correction_NN1 model_NN1 ._. 
</s>
<s>
With_IW the_AT help_NN1 of_IO the_AT model_NN1 estimated_VVN in_II section_NN1 4.1_MC the_AT model_NN1 can_VM be_VBI formulated_VVN as_CSA following_VVG :_: &lsqb;_( Formula_NN1 &rsqb;_) This_DD1 model_NN1 is_VBZ then_RT estimated_VVN a_AT1 few_DA2 times_NNT2 ,_, so_CS21 that_CS22 every_AT1 time_NNT1 it_PPH1 is_VBZ re-estimated_VVN ,_, less_RGR significant_JJ lags_NN2 are_VBR removed_VVN &lsqb;_( Flaig_NP1 and_CC Steiner_NP1 (_( 1989_MC )_) &rsqb;_) ._. 
</s>
<s>
These_DD2 removals_NN2 are_VBR then_RT tested_VVN with_IW a_AT1 F-test_JJ to_TO assure_VVI that_CST the_AT new_JJ models_NN2 are_VBR still_RR a_AT1 part_NN1 of_IO the_AT general_JJ model_NN1 ._. 
</s>
<s>
The_AT final_JJ variables_NN2 of_IO the_AT final_JJ error_NN1 correction_NN1 model_NN1 ,_, except_II21 for_II22 seasonal_JJ corrections_NN2 ,_, are_VBR shown_VVN in_II table_NN1 6_MC ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) The_AT final_JJ error_NN1 correction_NN1 model_NN1 is_VBZ then_RT ,_, as_CSA the_AT final_JJ step_NN1 ,_, tested_VVN for_IF misspec-_JJ ification_NN1 as_CSA in_II section_NN1 4.1_MC ,_, with_IW the_AT null_JJ hypothesis_NN1 "_" there_EX is_VBZ no_AT misspecification_NN1 "_" ._. 
</s>
<s>
These_DD2 test_VV0 results_NN2 are_VBR shown_VVN in_II table_NN1 7_MC ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) The_AT results_NN2 of_IO the_AT test_NN1 shows_VVZ that_CST the_AT null_JJ hypothesis_NN1 cannnot_NN1 be_VBI rejected_VVN for_IF any_DD of_IO the_AT tests_NN2 ._. 
</s>
<s>
By_II this_DD1 one_PN1 can_VM conclude_VVI that_CST the_AT final_JJ error_NN1 correction_NN1 model_NN1 is_VBZ valid_JJ and_CC the_AT model_NN1 seems_VVZ to_TO be_VBI correctly_RR stated._NNU 5_MC Discussion_NN1 The_AT equilibrium_NN1 error_NN1 coefficient_NN1 in_II the_AT error_NN1 correction_NN1 model_NN1 ,_, describes_VVZ how_RRQ quickly_RR the_AT equilibrium_NN1 error_NN1 will_VM adjust_VVI to_II the_AT steady_JJ state_NN1 ._. 
</s>
<s>
The_AT tests_NN2 indicate_VV0 that_CST 4,7_MC percent_NNU of_IO the_AT actual_JJ value_NN1 and_CC the_AT equilibrium_NN1 level_NN1 is_VBZ corrected_VVN quar-_JJ terly_JJ ._. 
</s>
<s>
In_II the_AT model_NN1 the_AT equilibrium_NN1 error_NN1 explains_VVZ the_AT long-run_JJ deviation_NN1 ,_, when_CS the_AT other_JJ variables_NN2 explain_VV0 the_AT short-run_JJ dynamics_NN ._. 
</s>
<s>
The_AT static_JJ equilibrium_NN1 long-run_JJ solution_NN1 becomes_VVZ the_AT following_JJ :_: &lsqb;_( Formula_NN1 &rsqb;_) All_DB coefficients_NN2 are_VBR significant_JJ ,_, but_CCB the_AT most_RGT statistically_RR significant_JJ varibles_NN2 are_VBR the_AT differentiated_JJ inflation_NN1 and_CC production_NN1 ,_, which_DDQ both_DB2 are_VBR significant_JJ even_RR on_II a_AT1 1_MC1 %_NNU level_NN1 ._. 
</s>
<s>
Another_DD1 significant_JJ variable_NN1 is_VBZ the_AT differentiated_JJ unemployment_NN1 (_( second_MD lag_NN1 )_) ,_, on_II a_AT1 5_MC %_NNU level_NN1 ._. 
</s>
<s>
From_II the_AT equation_NN1 it_PPH1 can_VM also_RR be_VBI concluded_VVN that_DD1 unemployment_NN1 and_CC tax_NN1 wedge_NN1 have_VH0 both_RR negative_JJ signs_NN2 ,_, which_DDQ is_VBZ expected_VVN since_RR higher_JJR employment_NN1 and_CC greater_JJR tax_NN1 wedge_NN1 should_VM lower_VVI the_AT real_JJ wage_NN1 in_II the_AT end_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ also_RR expected_VVN that_DD1 productivity_NN1 has_VHZ a_AT1 positive_JJ sign_NN1 ,_, since_CS increased_JJ productivity_NN1 should_VM also_RR increase_VVI the_AT wages_NN2 ._. 
</s>
<s>
The_AT only_JJ thing_NN1 in_II the_AT model_NN1 that_CST is_VBZ opposite_JJ from_II what_DDQ was_VBDZ thought_VVN ,_, is_VBZ that_DD1 in_II this_DD1 model_NN1 the_AT inflation_NN1 should_VM affect_VVI the_AT real_JJ wage_NN1 negatively_RR ._. 
</s>
<s>
These_DD2 inflation_NN1 effects_NN2 have_VH0 been_VBN studied_VVN closely_RR and_CC many_DA2 have_VH0 tried_VVN to_TO explain_VVI why_RRQ the_AT models_NN2 have_VH0 poor_JJ forecast_NN1 performance_NN1 ,_, and_CC that_DD1 is_VBZ a_AT1 reason_NN1 for_IF why_RRQ thses_VVZ models_NN2 ca_VM n't_XX be_VBI taken_VVN as_II a_AT1 "_" true_JJ "_" fact_NN1 &lsqb;_( James_NP1 E._NP1 H._NP1 Davidson_NP1 and_CC Yeo_NP1 (_( 1978_MC )_) &rsqb;_) ._. 
</s>
