<s>
1_MC1 Introduction_NN1 1.1_MC Research_NN1 question_NN1 and_CC scope_NN1 The_AT system_NN1 of_IO licensing_VVG music_NN1 in_II the_AT Nordic_JJ countries_NN2 is_VBZ quite_RG developed_JJ and_CC is_VBZ working_VVG fairy_NN1 well_RR ._. 
</s>
<s>
However_RR ,_, the_AT digital_JJ era_NN1 has_VHZ brought_VVN a_AT1 lot_NN1 of_IO changes_NN2 to_II the_AT Nordic_JJ legal_JJ systems_NN2 and_CC has_VHZ also_RR affected_VVN the_AT licensing_NN1 of_IO music_NN1 mostly_RR because_CS many_DA2 new_JJ kinds_NN2 of_IO digital_JJ music_NN1 services_NN2 have_VH0 developed_VVN ._. 
</s>
<s>
The_AT digital_JJ era_NN1 has_VHZ enabled_VVN consumers_NN2 to_TO access_VVI music_NN1 easily_RR ,_, rapidly_RR and_CC at_II a_AT1 low_JJ cost_NN1 ,_, but_CCB it_PPH1 has_VHZ also_RR brought_VVN some_DD negative_JJ aspects_NN2 such_II21 as_II22 Internet_NP1 piracy_NN1 ._. 
</s>
<s>
In_BCL21 order_BCL22 for_IF legal_JJ music_NN1 services_NN2 to_TO be_VBI able_JK to_TO compete_VVI on_II the_AT market_NN1 with_IW these_DD2 pirate_NN1 services_NN2 ,_, it_PPH1 is_VBZ important_JJ that_CST it_PPH1 is_VBZ easy_JJ and_CC cost-efficient_JJ to_TO obtain_VVI the_AT necessary_JJ rights_NN2 from_II rights_NN2 holders_NN2 for_IF the_AT service_NN1 to_TO be_VBI legal_JJ ._. 
</s>
<s>
There_EX are_VBR several_DA2 proposals_NN2 on_II how_RRQ to_TO make_VVI licensing_NN1 of_IO music_NN1 more_RGR efficient_JJ and_CC especially_RR in_II the_AT U.S._NP1 several_DA2 scholars_NN2 and_CC expert_NN1 have_VH0 looked_VVN into_II this_DD1 ._. 
</s>
<s>
Two_MC of_IO them_PPHO2 are_VBR Marybeth_NP1 Peters_VVZ and_CC Bennett_NP1 Lincoff_NP1 ._. 
</s>
<s>
They_PPHS2 have_VH0 each_DD1 come_VVI up_RP with_IW an_AT1 idea_NN1 on_II how_RRQ to_TO change_VVI the_AT licensing_NN1 system_NN1 in_II the_AT U.S._NP1 in_II order_NN1 reduce_VV0 the_AT lengthy_JJ licensing_NN1 negotiations_NN2 and_CC cut_VV0 costs_NN2 ._. 
</s>
<s>
In_II this_DD1 term_NN1 paper_NN1 these_DD2 two_MC ideas_NN2 will_VM be_VBI examined_VVN more_RGR thoroughly_RR and_CC focus_NN1 will_VM be_VBI on_II whether_CSW they_PPHS2 could_VM be_VBI applied_VVN in_II the_AT Nordic_JJ licensing_NN1 system_NN1 and_CC whether_CSW they_PPHS2 would_VM actually_RR contribute_VVI with_IW a_AT1 more_RGR effective_JJ approach_NN1 to_II licensing_NN1 or_CC not_XX ._. 
</s>
<s>
These_DD2 ideas_NN2 will_VM be_VBI discussed_VVN in_II chapter_NN1 X_ZZ1 and_CC the_AT conclusions_NN2 drawn_VVN from_II the_AT discussion_NN1 will_VM be_VBI presented_VVN in_II chapter_NN1 X._NP1 Before_II that_DD1 ,_, however_RR ,_, it_PPH1 is_VBZ important_JJ to_TO take_VVI a_AT1 closer_JJR look_NN1 at_II how_RRQ the_AT licensing_NN1 system_NN1 currently_RR works_VVZ in_II the_AT Nordic_JJ countries_NN2 ,_, what_DDQ rights_NN2 need_VV0 to_TO be_VBI licensed_VVN ,_, is_VBZ there_EX a_AT1 working_JJ collective_JJ administration_NN1 system_NN1 and_RR31 so_RR32 on_RR33 ._. 
</s>
<s>
These_DD2 aspects_NN2 will_VM be_VBI dealt_VVN with_IW in_II chapter_NN1 X._NP1 There_EX are_VBR many_DA2 different_JJ types_NN2 of_IO digital_JJ music_NN1 services_NN2 and_CC the_AT licenses_NN2 needed_VVN and_CC the_AT licensing_NN1 procedure_NN1 differs_VVZ a_RR21 bit_RR22 depending_VVG on_II the_AT service_NN1 ._. 
</s>
<s>
It_PPH1 would_VM be_VBI too_RG extensive_JJ to_TO cover_VVI all_DB possible_JJ services_NN2 and_CC look_VVI at_II the_AT licensing_NN1 connected_VVN to_II all_DB of_IO them_PPHO2 and_CC therefore_RR this_DD1 term_NN1 paper_NN1 will_VM focus_VVI on_II one_MC1 kind_NN1 of_IO services_NN2 only_RR :_: on-demand_JJ music_NN1 streaming_VVG services_NN2 ._. 
</s>
<s>
These_DD2 services_NN2 only_RR offer_VV0 streaming_VVG transmissions_NN2 ,_, meaning_VVG the_AT user_NN1 will_VM not_XX receive_VVI a_AT1 copy_NN1 of_IO the_AT song_NN1 ,_, and_CC they_PPHS2 are_VBR interactive_JJ ,_, meaning_VVG the_AT user_NN1 can_VM select_VVI the_AT music_NN1 he_PPHS1 wants_VVZ to_TO listen_VVI to_II himself_PPX1 upon_II demand_NN1 ._. 
</s>
<s>
1.2_MC Method_NN1 The_AT method_NN1 used_VVN in_II this_DD1 term_NN1 paper_NN1 is_VBZ legal_JJ dogmatics_NN2 ._. 
</s>
<s>
Legal_JJ dogmatics_NN1 is_VBZ the_AT oldest_JJT and_CC most_RGT important_JJ method_NN1 within_II legal_JJ science_NN1 and_CC is_VBZ used_VVN to_TO interpret_VVI and_CC systematize_VVI the_AT rules_NN2 of_IO law_NN1 ._. 
</s>
<s>
The_AT goal_NN1 of_IO legal_JJ dogmatics_NN1 is_VBZ to_TO establish_VVI what_DDQ the_AT current_JJ rules_NN2 of_IO law_NN1 are_VBR (_( de_FW lege_NN1 lata_NN1 )_) ,_, or_CC what_DDQ they_PPHS2 should_VM be_VBI (_( de_FW lege_NN1 ferenda_NN1 )_) ,_, and_CC to_TO specify_VVI how_RRQ these_DD2 rules_NN2 should_VM be_VBI interpreted_VVN and_CC applied_VVN ._. 
</s>
<s>
The_AT interpretation_NN1 of_IO law_NN1 will_NN1 in_II this_DD1 term_NN1 paper_NN1 be_VBI of_IO great_JJ importance_NN1 when_CS determining_VVG the_AT rights_NN2 holders_NN2 rights_NN2 that_CST are_VBR to_TO be_VBI licensed_VVN to_II the_AT services_NN2 ._. 
</s>
<s>
By_II also_RR systemizing_VVG the_AT rules_NN2 of_IO law_NN1 ,_, in_II other_JJ words_NN2 structuring_VVG the_AT current_JJ law_NN1 ,_, legal_JJ dogmatics_NN1 strives_VVZ towards_II creating_VVG and_CC developing_VVG a_AT1 system_NN1 of_IO legal_JJ concepts_NN2 that_CST the_AT interpretation_NN1 of_IO law_NN1 hinges_VVZ on_RP ._. 
</s>
<s>
Systematization_NN1 is_VBZ also_RR important_JJ for_IF obtaining_VVG a_AT1 general_JJ view_NN1 of_IO the_AT legal_JJ system_NN1 ._. 
</s>
<s>
2_MC Rights_NN2 and_CC licenses_VVZ 2.1_MC Necessary_JJ rights_NN2 It_PPH1 is_VBZ the_AT person_NN1 who_PNQS creates_VVZ a_AT1 literary_JJ or_CC artistic_JJ work_NN1 who_PNQS has_VHZ copyright_NN1 therein_RR ._. 
</s>
<s>
The_AT work_NN1 may_VM consist_VVI of_IO a_AT1 piece_NN1 of_IO writing_NN1 or_CC a_AT1 speech_NN1 ,_, a_AT1 musical_JJ or_CC dramatic_JJ work_NN1 etc_RA ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, a_AT1 song_NN1 ,_, for_REX21 example_REX22 ,_, can_VM be_VBI a_AT1 piece_NN1 of_IO work_NN1 protected_VVN by_II copyright_NN1 ,_, and_CC it_PPH1 may_VM have_VHI several_DA2 separate_JJ copyright_NN1 owners_NN2 ,_, as_CSA the_AT lyrics_NN2 and_CC the_AT music_NN1 might_VM have_VHI been_VBN created_VVN by_II different_JJ authors_NN2 ._. 
</s>
<s>
The_AT Nordic_JJ countries_NN2 all_DB have_VH0 quite_RG similar_JJ copyright_NN1 acts_VVZ because_CS they_PPHS2 have_VH0 been_VBN written_VVN in_II close_JJ collaboration_NN1 ._. 
</s>
<s>
Before_II discussing_VVG the_AT rights_NN2 of_IO rights_NN2 holders_NN2 it_PPH1 is_VBZ important_JJ to_TO take_VVI a_AT1 look_NN1 at_II why_RRQ these_DD2 rights_NN2 are_VBR needed_VVN for_IF the_AT music_NN1 service_NN1 to_TO be_VBI legal_JJ ._. 
</s>
<s>
When_CS streaming_VVG music_NN1 on-demand_NN1 from_II a_AT1 service_NN1 on_II the_AT Internet_NN1 ,_, there_EX are_VBR essentially_RR two_MC aspects_NN2 that_CST are_VBR legally_RR interesting_JJ to_II copyright_NN1 holders_NN2 and_CC the_AT music_NN1 industry_NN1 ._. 
</s>
<s>
First_MD of_IO all_DB the_AT result_NN1 of_IO streaming_VVG is_VBZ that_CST the_AT song_NN1 is_VBZ played_VVN audibly_RR ,_, communicated_VVD ,_, and_CC this_DD1 will_VM implicate_VVI certain_JJ rights_NN2 of_IO right_JJ holders_NN2 ._. 
</s>
<s>
Secondly_RR ,_, there_EX are_VBR different_JJ kinds_NN2 of_IO copying_NN1 of_IO the_AT song_NN1 taking_VVG place_NN1 in_II the_AT process_NN1 ._. 
</s>
<s>
A_AT1 copy_NN1 of_IO the_AT song_NN1 is_VBZ put_VVN on_II the_AT server_NN1 of_IO the_AT service_NN1 provider_NN1 so_CS21 that_CS22 the_AT users_NN2 can_VM stream_VVI it_PPH1 from_II there_RL ._. 
</s>
<s>
Furthermore_RR ,_, during_II the_AT streaming_JJ transmission_NN1 of_IO the_AT song_NN1 ,_, the_AT users_NN2 receiving_VVG computer_NN1 temporarily_RR stores_NN2 ,_, buffers_NN2 ,_, parts_NN2 of_IO the_AT recording_NN1 in_II random_JJ access_NN1 memory_NN1 ,_, RAM_NN1 ,_, before_CS it_PPH1 is_VBZ made_VVN audible_JJ in_BCL21 order_BCL22 to_TO secure_VVI that_CST the_AT song_NN1 can_VM be_VBI performed_VVN without_IW interruptions_NN2 caused_VVN by_II a_AT1 slow_JJ network_NN1 ._. 
</s>
<s>
When_CS the_AT recording_NN1 is_VBZ played_VVN ,_, the_AT temporary_JJ buffer_NN1 copies_NN2 are_VBR removed_VVN part_NN1 by_II part_NN1 as_CSA they_PPHS2 are_VBR played_VVN and_CC are_VBR replaced_VVN with_IW the_AT following_JJ part_NN1 ._. 
</s>
<s>
The_AT streaming_JJ software_NN1 may_VM also_RR temporarily_RR cache_VVI the_AT received_JJ data_NN on_II the_AT users_NN2 hard_JJ drive_NN1 and_CC the_AT data_NN will_VM remain_VVI there_RL until_CS it_PPH1 is_VBZ written_VVN over_RP by_II other_JJ data_NN ._. 
</s>
<s>
(_( might_VM not_XX be_VBI relevant_JJ because_II21 of_II22 section_NN1 11a_FO FCA_NN1 .._... )_) 
</s>
<s>
In_II the_AT Finnish_JJ Copyright_NN1 Act_NN1 ,_, FCA_NP1 ,_, section_NN1 2_MC it_PPH1 is_VBZ stated_VVN that_DD1 copyright_NN1 provides_VVZ an_AT1 exclusive_JJ right_NN1 to_TO control_VVI a_AT1 work_NN1 by_II reproducing_VVG it_PPH1 or_CC making_VVG it_PPH1 available_JJ to_II the_AT public_NN1 ._. 
</s>
<s>
Reproduction_NN1 includes_VVZ copies_NN2 of_IO the_AT work_NN1 made_VVN in_II whole_NN1 or_CC in_RR21 part_RR22 ,_, directly_RR and_CC indirectly_RR ,_, temporarily_RR or_CC permanently_RR ._. 
</s>
<s>
The_AT reproduction_NN1 can_VM be_VBI made_VVN by_II any_DD means_NN and_CC in_II any_DD form_NN1 ,_, and_CC also_RR comprises_VVZ the_AT transfer_NN1 of_IO the_AT work_NN1 to_II another_DD1 device_NN1 ,_, by_II which_DDQ it_PPH1 can_VM be_VBI reproduced_VVN or_CC communicated_VVD ._. 
</s>
<s>
The_AT main_JJ features_NN2 of_IO the_AT reproduction_NN1 right_NN1 are_VBR thus_RR technology_NN1 neutrality_NN1 and_CC independence_NN1 from_II time_NNT1 and_CC quantity_NN1 ,_, meaning_VVG that_CST the_AT status_NN1 of_IO copyright_NN1 of_IO the_AT copy_NN1 made_VVN from_II the_AT original_NN1 is_VBZ not_XX bound_VVN by_II how_RGQ durable_JJ it_PPH1 is_VBZ or_CC how_RRQ ,_, or_CC of_IO what_DDQ material_NN1 ,_, it_PPH1 is_VBZ made_VVN ._. 
</s>
<s>
Furthermore_RR ,_, it_PPH1 is_VBZ stated_VVN in_II section_NN1 2_MC FCA_NN1 that_CST a_AT1 work_NN1 is_VBZ made_VVN available_JJ to_II the_AT public_NN1 when_CS it_PPH1 is_VBZ ,_, for_REX21 example_REX22 ,_, communicated_VVN to_II the_AT public_NN1 by_II wire_NN1 or_CC wireless_NN1 means_VVZ ,_, including_II communication_NN1 in_II a_AT1 way_NN1 which_DDQ enables_VVZ members_NN2 of_IO the_AT public_JJ to_TO access_VVI the_AT work_NN1 from_II a_AT1 place_NN1 and_CC at_II a_AT1 time_NNT1 individually_RR chosen_VVN by_II them_PPHO2 ._. 
</s>
<s>
This_DD1 means_VVZ that_CST interactive_JJ communication_NN1 is_VBZ also_RR part_NN1 of_IO the_AT exclusive_JJ right_NN1 of_IO making_VVG a_AT1 work_NN1 available_JJ to_II the_AT public_NN1 ._. 
</s>
<s>
In_II the_AT Swedish_JJ legal_JJ preparatory_JJ works_NN it_PPH1 is_VBZ specified_VVN that_CST typical_JJ examples_NN2 of_IO this_DD1 latter_DA situation_NN1 are_VBR webpages_NN2 where_RRQ a_AT1 selection_NN1 of_IO musical_JJ works_NN are_VBR made_VVN available_JJ to_II the_AT public_JJ to_TO listen_VVI to_II ._. 
</s>
<s>
This_DD1 provision_NN1 on_II communication_NN1 covers_VVZ all_DB distance_NN1 transmissions_NN2 ,_, including_II all_DB communications_NN2 of_IO works_NN on_II the_AT Internet_NN1 ,_, and_CC also_RR every_AT1 possible_JJ as_RR21 yet_RR22 unknown_JJ technique_NN1 of_IO transfer_NN1 ._. 
</s>
<s>
(_( maybe_RR bring_VV0 up_RP 11a_FO FCA_NN1 in_II this_DD1 context_NN1 as_RR21 well_RR22 )_) ._. 
</s>
<s>
It_PPH1 has_VHZ already_RR been_VBN established_VVN who_PNQS has_VHZ the_AT rights_NN2 to_II the_AT musical_JJ works_NN ,_, but_CCB if_CS the_AT musical_JJ work_NN1 is_VBZ recorded_VVN there_RL are_VBR additional_JJ rights_NN2 involved_VVD ._. 
</s>
<s>
Related_JJ rights_NN2 ,_, also_RR called_VVN neighbouring_JJ rights_NN2 ,_, are_VBR not_XX copyrights_NN2 but_CCB rights_NN2 closely_RR related_VVN to_II them_PPHO2 ._. 
</s>
<s>
There_EX are_VBR several_DA2 groups_NN2 of_IO producers_NN2 and_CC artists_NN2 whose_DDQGE rights_NN2 are_VBR protected_VVN through_II this_DD1 scheme_NN1 ,_, two_MC of_IO which_DDQ are_VBR performing_VVG artists_NN2 and_CC producers_NN2 of_IO phonograms_NN2 ._. 
</s>
<s>
When_CS it_PPH1 comes_VVZ to_II the_AT right_NN1 to_II dispositions_NN2 ,_, holders_NN2 of_IO related_JJ rights_NN2 are_VBR today_RT in_II quite_RG a_AT1 similar_JJ position_NN1 as_CSA copyright_NN1 holders_NN2 ._. 
</s>
<s>
According_II21 to_II22 section_NN1 46_MC FCA_NP1 ,_, a_AT1 phonogram_NN1 can_VM not_XX without_IW the_AT consent_NN1 of_IO the_AT producer_NN1 be_VBI transferred_VVN on_II21 to_II22 a_AT1 device_NN1 by_II means_NN through_II which_DDQ it_PPH1 can_VM be_VBI reproduced_VVN nor_CC can_VM it_PPH1 be_VBI communicated_VVN to_II the_AT public_NN1 by_II wire_NN1 or_CC wireless_NN1 means_VVZ ,_, including_II communication_NN1 to_II the_AT public_NN1 in_II a_AT1 manner_NN1 which_DDQ enables_VVZ members_NN2 of_IO the_AT public_JJ to_TO access_VVI the_AT work_NN1 from_II a_AT1 place_NN1 ,_, and_CC at_II a_AT1 time_NNT1 ,_, individually_RR chosen_VVN by_II them_PPHO2 ._. 
</s>
<s>
2.2_MC Necessary_JJ licenses_NN2 The_AT provider_NN1 of_IO an_AT1 on-demand_JJ music_NN1 streaming_VVG service_NN1 must_VM obtain_VVI two_MC kinds_NN2 of_IO licenses_NN2 for_IF both_DB2 the_AT musical_JJ works_NN and_CC the_AT phonogram_NN1 ;_; a_AT1 reproduction_NN1 license_NN1 and_CC a_AT1 license_NN1 for_IF making_VVG the_AT works_NN available_JJ to_II the_AT public_NN1 and_CC the_AT same_DA kinds_NN2 of_IO licenses_NN2 for_IF the_AT phonograms_NN2 ,_, the_AT recordings_NN2 of_IO the_AT works_NN ._. 
</s>
<s>
The_AT view_NN1 in_II the_AT Nordic_JJ countries_NN2 ,_, and_CC in_II Europe_NP1 generally_RR ,_, is_VBZ that_DD1 the_AT music_NN1 streaming_VVG service_NN1 is_VBZ the_AT party_NN1 requiring_VVG the_AT licenses_NN2 ,_, and_CC not_XX the_AT consumer_NN1 ._. 
</s>
<s>
Therefore_RR ,_, although_CS the_AT consumers_NN2 will_VM not_XX get_VVI a_AT1 copy_NN1 of_IO the_AT work/phonogram_NN1 through_II streaming_VVG ,_, the_AT service_NN1 must_VM still_RR obtain_VVI a_AT1 reproduction_NN1 license_NN1 as_II the_AT work/phonogram_NN1 is_VBZ reproduced_VVN when_CS put_VVN on_II the_AT service_NN1 providers_NN2 server_NN1 ,_, from_II where_RRQ the_AT users_NN2 then_RT stream_VV0 the_AT works_NN ._. 
</s>
<s>
Besides_II the_AT copy_NN1 put_VVN on_II the_AT server_NN1 of_IO the_AT service-provider_NN1 ,_, temporary_JJ buffer_NN1 copies_NN2 also_RR emerge_VV0 as_II a_AT1 result_NN1 of_IO the_AT streaming_JJ process_NN1 ._. 
</s>
<s>
In_II the_AT Nordic_JJ countries_NN2 ,_, copies_NN2 that_CST emerge_VV0 due_II21 to_II22 a_AT1 technical_JJ process_NN1 and_CC that_CST do_VD0 nt_XX have_VHI any_DD individual_JJ economic_JJ value_NN1 are_VBR regarded_VVN as_II exemptions_NN2 from_II the_AT rights_NN2 holders_NN2 reproduction_NN1 rights_NN2 in_II31 accordance_II32 with_II33 section_NN1 11a_FO FCA_NN1 ._. 
</s>
<s>
Therefore_RR ,_, no_AT licenses_NN2 are_VBR required_VVN for_IF these_DD2 copies_NN2 ._. 
</s>
<s>
(_( might_VM not_XX mention_VVI this_DD1 part_NN1 as_CSA it_PPH1 is_VBZ technically_RR of_IO no_AT importance_NN1 for_IF the_AT licensing_NN1 )_) Licenses_VVZ for_IF making_VVG works_NN available_JJ to_II the_AT public_NN1 are_VBR necessary_JJ for_IF the_AT making_VVG available_JJ of_IO the_AT works/phonograms_VVZ to_II the_AT public_NN1 ,_, which_DDQ encompasses_VVZ interactive_JJ transmissions_NN2 ._. 
</s>
<s>
Hereinafter_RR ,_, a_AT1 shorter_JJR term_NN1 ,_, performance_NN1 licenses_NN2 ,_, will_VM be_VBI used_VVN when_CS referring_VVG to_II licenses_NN2 for_IF making_VVG works_NN available_JJ to_II the_AT public_NN1 as_CSA this_DD1 is_VBZ the_AT term_NN1 commonly_RR used_VVN ._. 
</s>
<s>
3_MC Collective_JJ administration_NN1 of_IO rights_NN2 3.1_MC The_AT organizations_NN2 In_II theory_NN1 ,_, in_BCL21 order_BCL22 to_TO get_VVI its_APPGE business_NN1 working_VVG ,_, a_AT1 music_NN1 service_NN1 would_VM have_VHI to_TO make_VVI individual_JJ licensing_NN1 agreements_NN2 with_IW all_DB rights_NN2 holders_NN2 for_IF each_DD1 and_CC every_AT1 musical_JJ work_NN1 and_CC phonogram_NN1 ._. 
</s>
<s>
These_DD2 separate_JJ negotiations_NN2 would_VM be_VBI very_RG time-consuming_JJ and_CC expensive_JJ indeed_RR ,_, and_CC it_PPH1 would_VM be_VBI practically_RR impossible_JJ to_TO set_VVI up_RP a_AT1 service_NN1 of_IO any_DD kind_NN1 ._. 
</s>
<s>
In_II practise_NN1 ,_, this_DD1 is_VBZ not_XX the_AT case_NN1 as_CSA many_DA2 rights_NN2 holders_NN2 have_VH0 transferred_VVN their_APPGE rights_NN2 to_II other_JJ entities_NN2 who_PNQS administer_VV0 them_PPHO2 collectively_RR ._. 
</s>
<s>
The_AT Nordic_JJ countries_NN2 have_VH0 in_II the_AT past_NN1 worked_VVD ,_, and_CC are_VBR still_RR working_VVG ,_, closely_RR together_RL when_CS it_PPH1 comes_VVZ to_II copyright_NN1 ,_, and_CC as_II a_AT1 result_NN1 the_AT Nordic_JJ copyright_NN1 laws_NN2 resemble_VV0 each_PPX221 other_PPX222 a_RR31 great_RR32 deal_RR33 ._. 
</s>
<s>
The_AT Nordic_JJ collaboration_NN1 goes_VVZ beyond_II the_AT legislative_JJ level_NN1 and_CC is_VBZ also_RR found_VVN in_II the_AT collective_JJ administration_NN1 of_IO rights_NN2 ._. 
</s>
<s>
For_IF musical_JJ works_NN ,_, each_DD1 Nordic_JJ country_NN1 has_VHZ its_APPGE own_DA collective_JJ administration_NN1 organization_NN1 for_IF issuing_JJ performance_NN1 licenses_NN2 ;_; in_II Finland_NP1 it_PPH1 is_VBZ TEOSTO_NP1 ,_, in_II Sweden_NP1 STIM_NP1 ,_, in_II Norway_NP1 TONO_NP1 and_CC in_II Denmark_NP1 KODA_NP1 ._. 
</s>
<s>
The_AT organizations_NN2 strive_VV0 for_IF that_DD1 anyone_PN1 should_VM be_VBI allowed_VVN non-exclusive_JJ use_NN1 of_IO the_AT works_NN that_CST they_PPHS2 represent_VV0 ,_, as_CS31 long_CS32 as_CS33 they_PPHS2 pay_VV0 ._. 
</s>
<s>
These_DD2 organizations_NN2 represent_VV0 music_NN1 authors_NN2 and_CC publishers_NN2 ,_, and_CC all_DB of_IO these_DD2 organizations_NN2 are_VBR authorized_VVN to_TO handle_VVI performance_NN1 licenses_VVZ for_IF digital_JJ use_NN1 such_II21 as_II22 streaming_VVG ._. 
</s>
<s>
The_AT streaming_JJ services_NN2 are_VBR seen_VVN as_CSA any_DD other_JJ user_NN1 of_IO music_NN1 ,_, and_CC therefore_RR ,_, the_AT collective_JJ administration_NN1 organizations_NN2 are_VBR able_JK to_TO enter_VVI into_II licensing_VVG agreements_NN2 with_IW them_PPHO2 after_II negotiating_VVG the_AT terms_NN2 of_IO the_AT agreement_NN1 ._. 
</s>
<s>
The_AT negotiations_NN2 may_VM take_VVI a_RR21 bit_RR22 longer_RRR than_CSN with_IW traditional_JJ users_NN2 ,_, since_CS Internet_NP1 services_NN2 often_RR represent_VV0 new_JJ kinds_NN2 of_IO business_NN1 models_NN2 on_II the_AT market_NN1 and_CC the_AT organizations_NN2 need_VV0 to_TO analyze_VVI what_DDQ the_AT service_NN1 is_VBZ really_RR offering_VVG ,_, what_DDQ it_PPH1 will_VM cost_VVI and_RR31 so_RR32 on_RR33 ._. 
</s>
<s>
The_AT reproduction_NN1 licenses_NN2 ,_, on_II the_AT other_JJ hand_NN1 ,_, are_VBR issued_VVN by_II a_AT1 common_JJ organization_NN1 called_VVN NCB_NP1 ,_, Nordic_JJ Copyright_NN1 Bureau_NN1 ,_, who_PNQS holds_VVZ the_AT authority_NN1 to_TO issue_VVI reproduction_NN1 licenses_NN2 covering_VVG all_DB the_AT Nordic_JJ countries_NN2 and_CC also_RR the_AT Baltic_NP1 States_NP1 Estonia_NP1 ,_, Latvia_NP1 and_CC Lithuania_NP1 ._. 
</s>
<s>
NCB_NP1 is_VBZ also_RR authorized_VVN to_TO license_VVI music_NN1 for_IF Internet_NN1 use_NN1 ,_, such_II21 as_II22 on-demand_JJ streaming_NN1 ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO simplify_VVI the_AT licensing_NN1 procedure_NN1 even_RR further_RRR in_II the_AT Nordic_JJ countries_NN2 ,_, NCB_NP1 works_VVZ closely_RR together_RL with_IW the_AT performing_NN1 rights_NN2 organizations_NN2 ,_, and_CC in_II practice_NN1 the_AT rights_NN2 holders_NN2 grant_VV0 NCB_NP1 the_AT use_NN1 of_IO their_APPGE reproduction_NN1 rights_NN2 through_II their_APPGE membership_NN1 to_II the_AT performing_NN1 organizations_NN2 ._. 
</s>
<s>
Together_RL the_AT organizations_NN2 offer_VV0 a_AT1 joint_JJ license_NN1 for_IF users_NN2 who_PNQS want_VV0 to_TO offer_VVI on-demand_JJ streaming_NN1 of_IO music_NN1 on_II the_AT Internet_NN1 ._. 
</s>
<s>
If_CS the_AT area_NN1 the_AT music_NN1 provider_NN1 is_VBZ interested_JJ in_II is_VBZ ,_, for_REX21 example_REX22 ,_, Finland_NP1 ,_, both_RR reproduction_NN1 and_CC performance_NN1 licenses_NN2 can_VM be_VBI obtained_VVN by_II contacting_VVG TEOSTO_NN1 ._. 
</s>
<s>
The_AT collective_JJ administration_NN1 of_IO related_JJ rights_NN2 is_VBZ managed_VVN by_II organizations_NN2 other_II21 than_II22 those_DD2 administrating_VVG the_AT rights_NN2 of_IO the_AT musical_JJ works_NN ._. 
</s>
<s>
In_II Finland_NP1 and_CC Denmark_NP1 the_AT organization_NN1 is_VBZ GRAMEX_NP1 ,_, in_II Sweden_NP1 the_AT Swedish_JJ Group_NN1 of_IO IFPI_NN2 and_CC in_II Norway_NP1 GRAMO_NP1 ._. 
</s>
<s>
These_DD2 organizations_NN2 look_VV0 after_II the_AT rights_NN2 that_CST producers_NN2 are_VBR given_VVN by_II law_NN1 ,_, but_CCB when_CS it_PPH1 comes_VVZ to_II licensing_NN1 of_IO on-demand_JJ music_NN1 services_NN2 ,_, the_AT situation_NN1 is_VBZ a_RR21 bit_RR22 different_JJ ._. 
</s>
<s>
GRAMEX_VV0 in_II Finland_NP1 license_VV0 some_DD kinds_NN2 of_IO on-demand_NN1 streaming_VVG services_NN2 ;_; for_REX21 example_REX22 ,_, they_PPHS2 license_VV0 the_AT phonograms_NN2 included_VVN in_II programs_NN2 put_VVN on_II the_AT Yle_NP1 Areena_NP1 ,_, but_CCB when_CS it_PPH1 comes_VVZ to_II licensing_NN1 of_IO services_NN2 that_CST could_VM be_VBI compared_VVN to_II ,_, or_CC even_RR replace_VV0 ,_, record_NN1 sales_NN ,_, record_NN1 companies_NN2 handle_VV0 it_PPH1 themselves_PPX2 ._. 
</s>
<s>
These_DD2 services_NN2 include_VV0 both_RR online_JJ music_NN1 shops_NN2 and_CC music_NN1 streaming_VVG services_NN2 ._. 
</s>
<s>
The_AT situation_NN1 is_VBZ the_AT same_DA in_II all_DB Nordic_JJ countries_NN2 ._. 
</s>
<s>
3.2_MC The_AT extended_JJ collective_JJ license_NN1 In_II the_AT Nordic_JJ countries_NN2 ,_, legislators_NN2 have_VH0 focused_VVN especially_RR on_II the_AT position_NN1 and_CC legal_JJ security_NN1 of_IO users_NN2 and_CC have_VH0 developed_VVN a_AT1 technique_NN1 called_VVN extended_JJ collective_JJ licensing_NN1 in_BCL21 order_BCL22 to_TO resolve_VVI the_AT contradiction_NN1 between_II copyright_NN1 exclusivity_NN1 and_CC mass-use_NN1 ._. 
</s>
<s>
The_AT extended_JJ collective_JJ license_NN1 is_VBZ an_AT1 intermediary_NN1 form_NN1 between_II voluntary_JJ and_CC compulsory_JJ licensing_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ governed_VVN by_II law_NN1 ,_, and_CC both_RR general_JJ and_CC specific_JJ rules_NN2 are_VBR found_VVN in_II the_AT Nordic_JJ copyright_NN1 acts_NN2 ._. 
</s>
<s>
The_AT provisions_NN2 on_II the_AT extended_JJ collective_JJ license_NN1 also_RR apply_VV0 to_II related_JJ rights_NN2 to_II an_AT1 extensive_JJ extent_NN1 ._. 
</s>
<s>
The_AT extended_JJ collective_JJ license_NN1 has_VHZ proved_VVN to_TO be_VBI very_RG useful_JJ in_II mass-use_JJ situations_NN2 ,_, but_CCB it_PPH1 is_VBZ important_JJ that_CST it_PPH1 is_VBZ only_RR used_VVN when_CS there_EX is_VBZ a_AT1 strong_JJ and_CC non-disputable_JJ need_NN1 for_IF it_PPH1 ,_, as_CSA it_PPH1 contains_VVZ a_AT1 compulsory_JJ element_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ also_RR the_AT reason_NN1 for_IF why_RRQ it_PPH1 is_VBZ very_RG important_JJ that_CST it_PPH1 has_VHZ legal_JJ support_NN1 by_II explicit_JJ provisions_NN2 in_II the_AT law_NN1 ._. 
</s>
<s>
The_AT institution_NN1 of_IO an_AT1 extended_JJ collective_JJ license_NN1 builds_VVZ on_II the_AT idea_NN1 that_CST rights_NN2 holders_NN2 could_VM seldom_RR ,_, in_II mass-use_JJ situations_NN2 ,_, get_VV0 the_AT maximum_JJ benefits_NN2 from_II their_APPGE exclusive_JJ rights_NN2 by_II negotiating_VVG alone_RR it_PPH1 is_VBZ better_JJR if_CS a_AT1 collective_JJ administration_NN1 organization_NN1 negotiates_VVZ freely_RR on_II31 behalf_II32 of_II33 all_DB rights_NN2 holders_NN2 ._. 
</s>
<s>
The_AT negotiated_JJ contract_NN1 is_VBZ then_RT legally_RR binding_VVG on_II all_DB rights_NN2 holders_NN2 ,_, also_RR on_II the_AT ones_NN2 that_CST are_VBR not_XX represented_VVN by_II the_AT organization_NN1 ,_, and_CC it_PPH1 constitutes_VVZ a_AT1 fully_RR covering_VVG license_NN1 ._. 
</s>
<s>
The_AT user_NN1 ,_, by_II its_APPGE contract_NN1 with_IW the_AT collective_JJ administration_NN1 organization_NN1 ,_, will_VM easily_RR receive_VVI all_DB necessary_JJ rights_NN2 needed_VVN for_IF its_APPGE activity_NN1 at_II the_AT same_DA time_NNT1 as_CSA all_DB rights_NN2 holders_NN2 are_VBR receiving_VVG fair_JJ compensation_NN1 ._. 
</s>
<s>
These_DD2 kinds_NN2 of_IO general_JJ contracts_NN2 ,_, also_RR involving_VVG non-represented_JJ authors_NN2 ,_, are_VBR characteristic_JJ for_IF the_AT extended_JJ collective_JJ license_NN1 system_NN1 ,_, but_CCB would_VM not_XX be_VBI possible_JJ without_IW the_AT provisions_NN2 in_II the_AT law_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ possible_JJ for_IF the_AT non-represented_JJ to_TO decline_VVI their_APPGE right_NN1 ,_, but_CCB the_AT benefits_NN2 offered_VVN through_II this_DD1 system_NN1 are_VBR considerable_JJ ,_, and_CC therefore_RR resignations_NN2 are_VBR quite_RG rare_JJ ._. 
</s>
<s>
The_AT extended_JJ collective_JJ license_NN1 gives_VVZ users_NN2 the_AT right_NN1 to_TO legally_RR use_VVI all_DB material_NN1 in_II the_AT field_NN1 and_CC the_AT rights_NN2 holders_NN2 in_II turn_NN1 have_VH0 the_AT right_NN1 to_II individual_JJ remuneration_NN1 ._. 
</s>
<s>
A_AT1 condition_NN1 for_IF letting_VVG a_AT1 collective_JJ administration_NN1 organization_NN1 act_NN1 upon_II this_DD1 system_NN1 is_VBZ that_CST it_PPH1 is_VBZ representative_JJ in_II its_APPGE field_NN1 ,_, meaning_VVG that_CST a_AT1 considerable_JJ number_NN1 of_IO rights_NN2 holders_NN2 must_VM be_VBI represented_VVN by_II it_PPH1 ._. 
</s>
<s>
This_DD1 derives_VVZ from_II the_AT idea_NN1 that_CST ,_, in_II that_DD1 situation_NN1 ,_, it_PPH1 is_VBZ unlikely_JJ that_CST a_AT1 rights_NN2 holder_NN1 acting_VVG alone_RR could_VM obtain_VVI a_AT1 better_JJR contract_NN1 ._. 
</s>
<s>
Additional_JJ conditions_NN2 are_VBR also_RR possible_JJ ;_; in_II Finland_NP1 ,_, for_REX21 example_REX22 ,_, the_AT organization_NN1 must_VM be_VBI approved_VVN by_II the_AT Ministry_NN1 of_IO Education_NN1 ._. 
</s>
<s>
The_AT extended_JJ license_NN1 exists_VVZ in_II all_DB Nordic_JJ countries_NN2 with_IW the_AT same_DA basic_JJ structure_NN1 ._. 
</s>
<s>
The_AT system_NN1 was_VBDZ first_MD adopted_VVN to_TO cover_VVI the_AT field_NN1 of_IO broadcasting_NN1 of_IO literary_JJ and_CC musical_JJ works_NN ,_, but_CCB has_VHZ now_RT extended_VVN to_II other_JJ areas_NN2 such_II21 as_II22 off-air_JJ recording_NN1 of_IO radio_NN1 and_CC television_NN1 programs_NN2 for_IF educational_JJ use_NN1 ,_, use_NN1 of_IO works_NN in_II broadcasting_NN1 companies_NN2 archives_NN2 etc_RA ._. 
</s>
<s>
Some_DD Nordic_JJ countries_NN2 have_VH0 also_RR introduced_VVN a_AT1 general_JJ provision_NN1 on_II extended_JJ collective_JJ licensing_NN1 in_II their_APPGE copyright_NN1 acts_NN2 and_CC others_NN2 are_VBR considering_VVG it_PPH1 &lsqb;_( &rsqb;_) find_VV0 more_DAR info_NN1 on_II this_DD1 !_! 4_MC MROs_NP2 and_CC a_AT1 Digital_JJ Transmission_NN1 right_RR 4.1_MC A_ZZ1 digital_JJ transmission_NN1 rights_NN2 Write_VV0 this_DD1 section_NN1 based_VVN on_II articles_NN2 from_II Bennett_NP1 Lincoff_NP1 and_CC possibly_RR get_VV0 some_DD material_NN1 from_II Teosto_NP1 /_FO ipr_NN1 info_NN1 journal_NN1 ._. 
</s>
<s>
Basic_JJ ideas_NN2 :_: create_VV0 one_PN1 right_RR for_IF digital_JJ use_NN1 and_CC let_VV0 the_AT collective_JJ administration_NN1 organization_NN1 license_VV0 it_PPH1 Only_RR digital_JJ use_NN1 Could_VM maybe_RR be_VBI achieved_VVN with_IW contracts_NN2 as_RR21 well_RR22 ?_? 4.2_MC MROs_NP2 Write_VV0 this_DD1 section_NN1 based_VVN on_II Marybeth_NP1 Peters_NP statement_NN1 to_II the_AT subcommittee_NN1 on_II courts_NN2 (_( found_VVN online_RR )_) ._. 
</s>
<s>
Basic_JJ idea_NN1 :_: let_VV0 collective_JJ administration_NN1 organizations_NN2 license_VVI both_RR reproduction_NN1 and_CC performance_NN1 licenses_NN2 Is_VBZ this_DD1 necessary_JJ when_CS NCB_NP1 is_VBZ collaborating_VVG so_RG closely_RR with_IW the_AT other_JJ Nordic_JJ organizations_NN2 ?_? 5_MC Conclusions_NN2 Base_VV0 conclusions_NN2 on_II findings_NN2 in_II chapter_NN1 4_MC ._. 
</s>
<s>
Discuss_VV0 whether_CSW the_AT ideas_NN2 are_VBR working_VVG Is_VBZ the_AT Nordic_JJ system_NN1 in_II31 need_II32 of_II33 a_AT1 change_NN1 ?_? 
</s>
<s>
Would_VM the_AT ideas_NN2 change_VVI anything_PN1 in_II practice_NN1 in_II the_AT Nordic_JJ countries_NN2 ?_? 
</s>
<s>
Which_DDQ of_IO the_AT ideas_NN2 is_VBZ better_JJR ?_? 
</s>
