<s>
CSR_NP1 and_CC Human_JJ Resource_NN1 Management_NN1 -_- is_VBZ there_EX a_AT1 connection_NN1 ?_? 
</s>
<s>
Introduction_NN1 Corporate_JJ Social_JJ responsibility_NN1 (_( CSR_NP1 )_) is_VBZ an_AT1 issue_NN1 that_CST is_VBZ becoming_VVG more_RRR and_CC more_RGR important_JJ for_IF companies_NN2 ._. 
</s>
<s>
According_II21 to_II22 Schaefer_NP1 (_( 2008_MC )_) top_JJ management_NN1 in_II companies_NN2 should_VM be_VBI well_JJ aware_JJ of_IO the_AT social_JJ responsibility_NN1 and_CC how_RRQ the_AT company_NN1 image_NN1 is_VBZ seen_VVN by_II others_NN2 ._. 
</s>
<s>
While_CS companies_NN2 try_VV0 to_TO keep_VVI their_APPGE own_DA business_NN1 in_II order_NN1 ,_, they_PPHS2 also_RR need_VV0 to_TO take_VVI into_II account_NN1 what_DDQ the_AT public_NN1 expect_VV0 from_II the_AT company_NN1 as_II31 well_II32 as_II33 the_AT shareholders_NN2 expectations_NN2 (_( Zadek_NP1 2004_MC )_) ._. 
</s>
<s>
There_EX have_VH0 also_RR been_VBN arguments_NN2 concerning_II CSR_NP1 ,_, and_CC according_II21 to_II22 Friedman_NP1 (_( 1970_MC )_) the_AT only_JJ social_JJ responsibility_NN1 that_CST firms_NN2 have_VH0 is_VBZ to_TO increase_VVI its_APPGE profit_NN1 ._. 
</s>
<s>
It_PPH1 has_VHZ been_VBN argued_VVN that_CST a_AT1 business_NN1 is_VBZ not_XX a_AT1 person_NN1 and_CC therefore_RR it_PPH1 can_VM not_XX have_VHI any_DD responsibilities_NN2 (_( Friedman_NP1 ,_, 1970_MC )_) ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 ,_, research_NN1 has_VHZ shown_VVN that_CST the_AT publics_NN2 view_NN1 of_IO a_AT1 company_NN1 can_VM be_VBI very_RG vital_JJ ,_, so_RR if_CS a_AT1 company_NN1 does_VDZ nt_XX take_VVI into_II account_NN1 their_APPGE social_JJ responsibility_NN1 ,_, there_EX can_VM be_VBI serious_JJ damages_NN2 to_II the_AT companys_NN2 image_NN1 (_( Zadek_NP1 2004_MC )_) ._. 
</s>
<s>
It_PPH1 can_VM be_VBI stated_VVN that_CST CSR_NP1 is_VBZ an_AT1 issue_NN1 that_CST businesses_NN2 tend_VV0 to_TO think_VVI about_II a_RR21 lot_RR22 these_DD2 days_NNT2 ,_, but_CCB whos_NN2 leading_VVG this_DD1 issue_NN1 inside_II an_AT1 organization_NN1 ?_? 
</s>
<s>
According_II21 to_II22 Adrienne_NP1 Fox_NP1 (_( 2008_MC )_) there_EX is_VBZ often_RR no_AT clear_JJ department_NN1 that_CST takes_VVZ care_NN1 if_CS this_DD1 matter_NN1 and_CC often_RR it_PPH1 falls_VVZ upon_II the_AT marketing_NN1 department_NN1 ._. 
</s>
<s>
What_DDQ she_PPHS1 suggests_VVZ is_VBZ that_CST the_AT HR_NNU department_NN1 would_VM take_VVI its_APPGE chance_NN1 and_CC take_VVI this_DD1 issue_NN1 as_CSA their_APPGE responsibility_NN1 ._. 
</s>
<s>
Often_RR it_PPH1 does_VDZ nt_XX work_VVI out_RP this_DD1 way_NN1 but_CCB she_PPHS1 argues_VVZ that_CST the_AT HR_NNU department_NN1 does_VDZ have_VHI the_AT qualities_NN2 and_CC the_AT knowledge_NN1 of_IO the_AT organizations_NN2 procedures_NN2 to_TO take_VVI on_RP this_DD1 kind_NN1 of_IO task_NN1 ._. 
</s>
<s>
The_AT HR_NNU department_NN1 often_RR collaborates_VVZ and_CC discusses_VVZ with_IW every_AT1 department_NN1 in_II an_AT1 organization_NN1 and_CC this_DD1 is_VBZ something_PN1 that_CST CSR_NP1 needs_NN2 in_BCL21 order_BCL22 for_IF it_PPH1 to_TO work_VVI ._. 
</s>
<s>
(_( Fox_NP1 2008_MC )_) This_DD1 paper_NN1 looks_VVZ further_RRR into_II the_AT connections_NN2 between_II CSR_NP1 and_CC different_JJ human_JJ resource_NN1 (_( HR_NNU )_) strategies_NN2 ._. 
</s>
<s>
The_AT purpose_NN1 of_IO the_AT paper_NN1 is_VBZ to_TO get_VVI a_AT1 deeper_JJR understanding_NN1 of_IO the_AT connection_NN1 between_II these_DD2 two_MC and_CC to_TO see_VVI if_CS and_CC why_RRQ HR_NNU can_VM be_VBI responsible_JJ for_IF CSR_NP1 strategies_NN2 ._. 
</s>
<s>
The_AT rest_NN1 of_IO the_AT paper_NN1 is_VBZ divided_VVN into_II three_MC sections_NN2 ._. 
</s>
<s>
The_AT first_MD section_NN1 is_VBZ a_AT1 literature_NN1 review_NN1 of_IO both_RR CSR_NP1 and_CC HR_NNU strategies_NN2 ._. 
</s>
<s>
In_II this_DD1 section_NN1 the_AT connection_NN1 between_II CSR_NP1 and_CC HRM_NP1 will_VM also_RR be_VBI discussed_VVN ._. 
</s>
<s>
The_AT second_MD section_NN1 is_VBZ an_AT1 analysis_NN1 of_IO the_AT literature_NN1 review_NN1 and_CC the_AT final_JJ section_NN1 will_VM include_VVI the_AT conclusion_NN1 Literature_NN1 review_NN1 In_II this_DD1 section_NN1 the_AT theories_NN2 regarding_VVG both_RR CSR_NP1 and_CC HR_NNU will_VM be_VBI discussed_VVN ._. 
</s>
<s>
The_AT latter_DA part_NN1 of_IO this_DD1 will_VM discuss_VVI how_RRQ CSR_NP1 and_CC HR_NNU can_VM work_VVI together_RL and_CC if_CS it_PPH1 is_VBZ possible_JJ to_TO implement_VVI CSR_NP1 strategies_NN2 into_II the_AT HR_NNU functions_NN2 ._. 
</s>
<s>
Corporate_JJ Social_JJ Responsibility_NN1 CSR_NP1 is_VBZ a_AT1 strategy_NN1 that_CST organizations_NN2 can_VM implement_VVI in_BCL21 order_BCL22 to_TO be_VBI add_VV0 value_NN1 to_II the_AT organization_NN1 ._. 
</s>
<s>
CSR_NP1 takes_VVZ into_II account_NN1 society_NN1 ,_, environment_NN1 and_CC the_AT organization_NN1 ._. 
</s>
<s>
One_MC1 of_IO the_AT reasons_NN2 for_IF organizations_NN2 to_TO take_VVI on_RP this_DD1 strategy_NN1 is_VBZ to_TO build_VVI on_II a_AT1 strong_JJ company_NN1 brand_NN1 ._. 
</s>
<s>
Another_DD1 reason_NN1 for_IF implementing_VVG CSR_NP1 into_II the_AT organizational_JJ strategy_NN1 is_VBZ to_TO differentiate_VVI the_AT organization_NN1 from_II other_JJ organizations_NN2 and_CC therefore_RR build_VV0 a_AT1 competitive_JJ advantage_NN1 towards_II other_JJ organizations_NN2 (_( Hillestad_NP1 ,_, Xie_NP1 and_CC Haugland_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
When_CS talking_VVG about_II CSR_NP1 many_DA2 authors_NN2 mention_VV0 the_AT triple_JJ bottom_JJ line_NN1 trend_NN1 ._. 
</s>
<s>
The_AT triple_JJ bottom_JJ line_NN1 concerns_VVZ the_AT society_NN1 ,_, the_AT environment_NN1 and_CC the_AT organization_NN1 ,_, as_CSA already_RR mentioned_VVN above_RL ._. 
</s>
<s>
Organizations_NN2 can_VM choose_VVI to_TO follow_VVI this_DD1 trend_NN1 in_II many_DA2 ways_NN2 ,_, there_EX is_VBZ not_XX only_RR one_MC1 way_NN1 to_TO be_VBI socially_RR responsible_JJ ._. 
</s>
<s>
(_( Mees_NP2 and_CC Bonham_NP1 2004_MC )_) While_CS many_DA2 authors_NN2 emphasize_VV0 the_AT importance_NN1 and_CC value_NN1 of_IO being_VBG socially_RR responsible_JJ there_RL has_VHZ also_RR been_VBN arguments_NN2 about_II whether_CSW an_AT1 organization_NN1 is_VBZ obliged_VVN to_TO act_VVI socially_RR responsible_JJ or_CC not_XX ._. 
</s>
<s>
Milton_NP1 Friedman_NP1 (_( 1970_MC )_) argues_VVZ that_CST the_AT only_JJ responsibility_NN1 an_AT1 organization_NN1 has_VHZ is_VBZ to_TO increase_VVI its_APPGE profit_NN1 ._. 
</s>
<s>
According_II21 to_II22 Friedman_NP1 a_AT1 corporate_JJ executive_NN1 is_VBZ hired_VVN by_II the_AT owners_NN2 of_IO the_AT corporate_JJ and_CC is_VBZ expected_VVN to_TO act_VVI in_II the_AT way_NN1 that_CST the_AT stockholders_NN2 want_VV0 him_PPHO1 to_TO do_VDI ._. 
</s>
<s>
He_PPHS1 does_VDZ not_XX think_VVI that_CST an_AT1 organization_NN1 should_VM take_VVI on_RP CSR_NP1 strategies_NN2 unless_CS the_AT stockholders_NN2 explicitly_RR whishes_VVZ to_TO do_VDI so_RR (_( Friedman_NP1 ,_, 1970_MC )_) ._. 
</s>
<s>
Alan_NP1 D._NP1 Smith_NP1 (_( 2007_MC )_) recognizes_VVZ this_DD1 theory_NN1 in_II his_APPGE article_NN1 Making_VVG the_AT case_NN1 for_IF the_AT competitive_JJ advantage_NN1 of_IO corporate_JJ social_JJ responsibility_NN1 ,_, but_CCB also_RR argues_VVZ that_CST the_AT stockholders_NN2 are_VB0 nt_XX the_AT only_JJ ones_NN2 who_PNQS shares_VVZ an_AT1 interest_NN1 in_II the_AT firms_NN2 actions_NN2 ._. 
</s>
<s>
Smith_NP1 argues_VVZ that_CST taking_VVG into_II consideration_NN1 both_RR the_AT environment_NN1 and_CC the_AT people_NN in_II it_PPH1 are_VBR factors_NN2 that_CST a_AT1 company_NN1 are_VBR obligated_VVN to_TO think_VVI about_II ._. 
</s>
<s>
He_PPHS1 also_RR points_VVZ out_RP that_DD1 being_VBG socially_RR responsible_JJ can_VM lead_VVI to_II gaining_VVG a_AT1 competitive_JJ advantage_NN1 towards_II other_JJ organizations_NN2 ._. 
</s>
<s>
(_( Smith_NP1 2007_MC )_) the_AT triple_JJ bottom_JJ line_NN1 concept_NN1 also_RR indicates_VVZ that_CST it_PPH1 is_VBZ not_XX the_AT stockholders_NN2 opinion_NN1 that_CST matter_VV0 ;_; it_PPH1 is_VBZ instead_RR the_AT stakeholders_NN2 opinion_NN1 ._. 
</s>
<s>
An_AT1 organization_NN1 has_VHZ a_AT1 responsibility_NN1 towards_II the_AT stakeholder_NN1 and_CC the_AT stakeholders_NN2 in_II this_DD1 sense_NN1 are_VBR anyone_PN1 who_PNQS is_VBZ affected_VVN by_II the_AT organization_NN1 ._. 
</s>
<s>
(_( Glade_VV0 2008_MC )_) Simon_NP1 Zadek_NP1 (_( 2004_MC )_) identifies_VVZ five_MC stages_NN2 that_CST an_AT1 organization_NN1 goes_VVZ through_RP when_CS a_AT1 new_JJ demand_NN1 is_VBZ set_VVN upon_II them_PPHO2 ,_, for_REX21 example_REX22 a_AT1 demand_NN1 like_II being_VBG socially_RR responsible_JJ ._. 
</s>
<s>
The_AT first_MD stage_NN1 is_VBZ being_VBG defensive_JJ ,_, thinking_VVG that_CST it_PPH1 is_VBZ not_XX our_APPGE responsibility_NN1 ._. 
</s>
<s>
The_AT second_MD stage_NN1 is_VBZ compliance_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ the_AT stage_NN1 when_CS the_AT organization_NN1 realizes_VVZ that_CST they_PPHS2 have_VH0 to_TO do_VDI something_PN1 about_II the_AT critic_NN1 they_PPHS2 are_VBR given_VVN and_CC defend_VV0 their_APPGE reputation_NN1 ._. 
</s>
<s>
What_DDQ follows_VVZ after_II this_DD1 is_VBZ the_AT managerial_JJ stage_NN1 ,_, when_CS the_AT organization_NN1 recognizes_VVZ that_CST this_DD1 is_VBZ an_AT1 issue_NN1 that_CST will_VM last_VVI over_II time_NNT1 ._. 
</s>
<s>
A_AT1 short_JJ term_NN1 strategy_NN1 to_TO defend_VVI the_AT reputation_NN1 will_VM not_XX work_VVI anymore_RR and_CC they_PPHS2 have_VH0 to_TO come_VVI up_RP with_IW a_AT1 strategy_NN1 that_CST will_VM last_VVI ._. 
</s>
<s>
At_II this_DD1 point_NN1 it_PPH1 is_VBZ time_NNT1 for_IF the_AT strategic_JJ stage_NN1 ._. 
</s>
<s>
The_AT strategic_JJ stage_NN1 is_VBZ the_AT stage_NN1 when_CS the_AT organization_NN1 realizes_VVZ that_CST having_VHG a_AT1 CSR_NP1 strategy_NN1 can_VM be_VBI useful_JJ in_II the_AT competition_NN1 with_IW other_JJ organizations_NN2 ._. 
</s>
<s>
The_AT final_JJ stage_NN1 is_VBZ the_AT civil_JJ stage_NN1 ,_, where_CS the_AT organization_NN1 has_VHZ already_RR built_VVN up_RP a_AT1 CSR_NP1 strategy_NN1 and_CC now_RT wants_VVZ to_TO show_VVI the_AT society_NN1 how_RRQ much_RR they_PPHS2 engage_VV0 in_II this_DD1 matter_NN1 ._. 
</s>
<s>
(_( Zadek_VV0 2004_MC )_) How_RRQ do_VD0 organizations_NN2 then_RT build_VVI these_DD2 CSR_NP1 strategies_NN2 ?_? 
</s>
<s>
According_II21 to_II22 Jeremy_NP1 Galbreath_NP1 (_( 2008_MC )_) there_EX are_VBR many_DA2 organizations_NN2 that_CST do_VD0 nt_XX have_VHI a_AT1 proper_JJ strategy_NN1 for_IF CSR_NP1 ._. 
</s>
<s>
The_AT effort_NN1 that_CST is_VBZ being_VBG made_VVN to_TO act_VVI socially_RR responsible_JJ often_RR includes_VVZ reporting_VVG about_II ethics_NN and_CC creating_VVG public_JJ relations_NN2 campaigns_NN2 ._. 
</s>
<s>
Galbreath_NN1 points_VVZ out_RP that_CST an_AT1 organizations_NN2 mission_NN1 is_VBZ where_RRQ the_AT CSR_NP1 strategy_NN1 has_VHZ its_APPGE beginning_NN1 ._. 
</s>
<s>
The_AT mission_NN1 of_IO an_AT1 organization_NN1 tells_VVZ us_PPIO2 what_DDQ they_PPHS2 want_VV0 to_TO accomplish_VVI with_IW their_APPGE activities_NN2 and_CC what_DDQ they_PPHS2 want_VV0 to_TO promote_VVI ._. 
</s>
<s>
The_AT organization_NN1 should_VM build_VVI the_AT CSR_NP1 strategy_NN1 on_II this_DD1 mission_NN1 and_CC remember_VV0 what_DDQ the_AT original_JJ goal_NN1 of_IO the_AT organization_NN1 is_VBZ ._. 
</s>
<s>
For_IF the_AT CSR_NP1 strategy_NN1 to_TO work_VVI there_RL has_VHZ to_TO be_VBI an_AT1 understanding_NN1 of_IO the_AT environment_NN1 outside_II the_AT organization_NN1 as_RR21 well_RR22 ._. 
</s>
<s>
Another_DD1 aspect_NN1 that_CST is_VBZ good_JJ to_TO have_VHI in_II mind_NN1 when_CS building_VVG up_RP CSR_NP1 strategies_NN2 is_VBZ the_AT market_NN1 ._. 
</s>
<s>
An_AT1 analysis_NN1 of_IO the_AT market_NN1 and_CC of_IO potential_JJ buyers_NN2 is_VBZ vital_JJ if_CS there_EX is_VBZ a_AT1 specific_JJ characteristic_NN1 of_IO the_AT specific_JJ market_NN1 ._. 
</s>
<s>
A_AT1 specific_JJ market_NN1 can_VM have_VHI demands_NN2 on_II how_RRQ the_AT business_NN1 should_VM be_VBI conducted_VVN ,_, for_REX21 example_REX22 demand_VV0 regarding_II social_JJ responsibility_NN1 ._. 
</s>
<s>
The_AT same_DA strategy_NN1 can_VM be_VBI applied_VVN when_CS it_PPH1 comes_VVZ to_II customer_NN1 needs_NN2 ._. 
</s>
<s>
Resources_NN2 are_VBR another_DD1 issue_NN1 that_CST should_VM be_VBI integrated_VVN into_II the_AT CSR_NP1 strategy_NN1 ._. 
</s>
<s>
Resource_VV0 utilization_NN1 is_VBZ something_PN1 that_CST an_AT1 organization_NN1 can_VM benefit_VVI from_II ._. 
</s>
<s>
The_AT benefits_NN2 will_VM occur_VVI if_CSW the_AT organization_NN1 can_VM find_VVI a_AT1 specific_JJ resource_NN1 that_CST can_VM give_VVI them_PPHO2 an_AT1 advantage_NN1 that_CST other_JJ companies_NN2 does_VDZ nt_XX have_VHI ._. 
</s>
<s>
The_AT resource_NN1 utilization_NN1 also_RR has_VHZ to_TO do_VDI with_IW the_AT last_MD part_NN1 of_IO building_VVG up_RP the_AT CSR_NP1 strategy_NN1 ,_, which_DDQ is_VBZ creating_VVG a_AT1 competitive_JJ advantage_NN1 ._. 
</s>
<s>
An_AT1 organization_NN1 can_VM gain_VVI competitive_JJ advantage_NN1 by_II having_VHG a_AT1 resource_NN1 that_CST is_VBZ rare_JJ and_CC that_DD1 gives_VVZ value_NN1 ._. 
</s>
<s>
This_DD1 resource_NN1 also_RR has_VHZ to_TO be_VBI hard_JJ to_TO imitate_VVI by_II other_JJ organizations_NN2 ._. 
</s>
<s>
Human_JJ Resource_NN1 Management_NN1 Human_NN1 resource_NN1 management_NN1 (_( HRM_NP1 )_) is_VBZ a_AT1 term_NN1 that_CST has_VHZ been_VBN debated_VVN over_II time_NNT1 ._. 
</s>
<s>
According_II21 to_II22 Bratton_NP1 and_CC Gold_NN1 (_( 2003_MC )_) HRM_NP1 can_VM be_VBI seen_VVN as_CSA managing_JJ employees_NN2 and_CC their_APPGE relations_NN2 to_TO achieve_VVI competitive_JJ advantage_NN1 ._. 
</s>
<s>
They_PPHS2 see_VV0 employees_NN2 inside_II a_AT1 company_NN1 as_II a_AT1 valuable_JJ resource_NN1 and_CC also_RR believe_VV0 that_CST these_DD2 employees_NN2 are_VBR the_AT ones_NN2 that_CST bring_VV0 the_AT organizational_JJ value_NN1 to_II the_AT company_NN1 ._. 
</s>
<s>
(_( Bratton_NP1 and_CC Gold_NN1 2003_MC )_) Many_DA2 HR_NNU practices_NN2 are_VBR built_VVN on_II the_AT organizational_JJ culture_NN1 ._. 
</s>
<s>
The_AT HR_NNU practices_NN2 then_RT influence_VV0 individual_JJ behavior_NN1 inside_II an_AT1 organization_NN1 as_II the_AT practices_NN2 themselves_PPX2 are_VBR based_VVN on_II the_AT culture_NN1 ._. 
</s>
<s>
(_( Bowen_NP1 and_CC Ostroff_VV0 2004_MC )_) The_AT HR_NNU department_NN1 has_VHZ also_RR been_VBN recognized_VVN as_II an_AT1 important_JJ factor_NN1 when_CS it_PPH1 comes_VVZ to_II organizational_JJ change_NN1 ._. 
</s>
<s>
The_AT HR_NNU managers_NN2 are_VBR the_AT ones_NN2 that_CST ,_, when_CS a_AT1 change_NN1 is_VBZ occurring_VVG ,_, should_VM lead_VVI the_AT individuals_NN2 towards_II the_AT transition_NN1 ._. 
</s>
<s>
As_CSA technical_JJ processes_NN2 are_VBR easy_JJ to_TO learn_VVI ,_, it_PPH1 can_VM be_VBI harder_JJR to_TO understand_VVI the_AT new_JJ mindset_NN1 that_CST has_VHZ to_TO be_VBI approached_VVN when_CS an_AT1 organizational_JJ change_NN1 is_VBZ occurring_VVG ._. 
</s>
<s>
The_AT HR_NNU managers_NN2 role_NN1 is_VBZ not_XX to_TO decide_VVI what_DDQ needs_VVZ to_TO be_VBI changed_VVN but_CCB instead_RR how_RRQ the_AT employees_NN2 will_VM make_VVI the_AT change_NN1 happen_VVI ._. 
</s>
<s>
(_( Court_NN1 2011_MC )_) CSR_NP1 and_CC HRM_NP1 While_CS there_EX has_VHZ been_VBN many_DA2 articles_NN2 written_VVN about_II CSR_NP1 there_EX has_VHZ been_VBN little_RR written_VVN about_II whose_DDQGE role_NN1 it_PPH1 is_VBZ ,_, inside_II an_AT1 organization_NN1 ,_, to_TO take_VVI actions_NN2 on_II this_DD1 matter_NN1 ._. 
</s>
<s>
This_DD1 section_NN1 will_VM discuss_VVI the_AT connection_NN1 between_II CSR_NP1 and_CC HRM_NP1 in_BCL21 order_BCL22 to_TO see_VVI if_CSW the_AT HR_NNU department_NN1 inside_II an_AT1 organization_NN1 can_VM be_VBI in_II charge_NN1 for_IF CSR_NP1 matters_NN2 ._. 
</s>
<s>
Adrianne_NP1 Fox_NP1 (_( 2007_MC )_) noted_VVD that_CST the_AT HR_NNU department_NN1 could_VM be_VBI a_AT1 perfect_JJ component_NN1 in_II bringing_VVG in_II CSR_NP1 strategies_NN2 to_II an_AT1 organization_NN1 ._. 
</s>
<s>
According_II21 to_II22 Fox_NP1 it_PPH1 is_VBZ only_RR a_AT1 matter_NN1 of_IO time_NNT1 before_II HR_NNU recognizes_VVZ the_AT fact_NN1 that_CST CSR_NP1 can_VM be_VBI a_AT1 part_NN1 of_IO their_APPGE work_NN1 task_NN1 ,_, and_CC when_CS they_PPHS2 do_VD0 so_RR the_AT results_NN2 will_VM be_VBI good_JJ ._. 
</s>
<s>
The_AT HR_NNU department_NN1 is_VBZ perfect_JJ for_IF this_DD1 role_NN1 as_CSA they_PPHS2 already_RR know_VV0 the_AT operational_JJ functions_NN2 of_IO an_AT1 organization_NN1 and_CC are_VBR able_JK to_TO tie_VVI them_PPHO2 to_II the_AT business_NN1 ._. 
</s>
<s>
(_( Fox_NP1 ,_, 2007_MC )_) According_II21 to_II22 Lam_NP1 and_CC Khare_NP1 (_( 2010_MC )_) there_EX are_VBR several_DA2 reasons_NN2 why_RRQ the_AT HR_NNU department_NN1 in_II an_AT1 organization_NN1 would_VM take_VVI on_RP the_AT responsibility_NN1 of_IO implementing_VVG the_AT CSR_NP1 strategies_NN2 ._. 
</s>
<s>
The_AT first_MD reason_NN1 would_VM be_VBI that_CST the_AT HR_NNU department_NN1 is_VBZ known_VVN for_IF establishing_VVG and_CC keeping_VVG up_RP the_AT organizational_JJ values_NN2 ._. 
</s>
<s>
The_AT social_JJ responsibility_NN1 of_IO a_AT1 firm_NN1 is_VBZ directly_RR linked_VVN to_II the_AT organizational_JJ values_NN2 of_IO a_AT1 firm_NN1 ._. 
</s>
<s>
Secondly_RR ,_, CSR_NP1 principles_NN2 concerns_VVZ issues_NN2 like_II human_JJ rights_NN2 and_CC justice_NN1 among_II people_NN ,_, and_CC HR_NNU people_NN are_VBR trained_VVN and_CC well_RR aware_JJ of_IO how_RRQ employees_NN2 should_VM be_VBI treated_VVN in_II an_AT1 organization_NN1 ._. 
</s>
<s>
(_( Lame_JJ and_CC Khare_VV0 2010_MC )_) Furthermore_RR ,_, the_AT CSR_NP1 strategies_NN2 should_VM start_VVI from_II inside_RL the_AT company_NN1 ._. 
</s>
<s>
The_AT employees_NN2 are_VBR the_AT ones_NN2 that_CST communicate_VV0 to_II the_AT outside_JJ world_NN1 and_CC they_PPHS2 indirectly_RR reflect_VV0 the_AT company_NN1 culture_NN1 and_CC values_NN2 ._. 
</s>
<s>
The_AT HR_NNU department_NN1 is_VBZ often_RR responsible_JJ of_IO keeping_VVG up_RP this_DD1 culture_NN1 and_CC they_PPHS2 are_VBR also_RR the_AT ones_NN2 who_PNQS can_VM make_VVI a_AT1 change_NN1 in_II the_AT behavior_NN1 of_IO the_AT organization_NN1 and_CC mostly_RR ,_, make_VV0 a_AT1 change_NN1 in_II the_AT behavior_NN1 of_IO the_AT employees_NN2 ._. 
</s>
<s>
(_( Galbreath_NN1 2008_MC )_) Sukserm_VV0 and_CC Takahashi_NP1 (_( 2010_MC )_) also_RR recognize_VV0 the_AT HR_NNU department_NN1 as_II an_AT1 actor_NN1 when_CS it_PPH1 comes_VVZ to_II implementing_VVG CSR_NP1 strategies_NN2 ._. 
</s>
<s>
They_PPHS2 believe_VV0 that_CST the_AT components_NN2 that_CST drive_VV0 CSR_NP1 are_VBR the_AT employees_NN2 in_II the_AT organization_NN1 ._. 
</s>
<s>
This_DD1 argument_NN1 enhances_VVZ the_AT argument_NN1 that_CST HR_NNU workers_NN2 should_VM play_VVI a_AT1 part_NN1 in_II leading_VVG the_AT CSR_NP1 strategies_NN2 ._. 
</s>
<s>
If_CS the_AT HR_NNU department_NN1 would_VM take_VVI the_AT lead_NN1 in_II organizing_VVG the_AT CSR_NP1 strategies_NN2 the_AT employees_NN2 would_VM have_VHI a_AT1 chance_NN1 of_IO learning_VVG about_II ethical_JJ behavior_NN1 ._. 
</s>
<s>
The_AT benefits_NN2 that_CST would_VM arise_VVI from_II these_DD2 strategies_NN2 would_VM ,_, so_RR to_TO say_VVI ,_, not_XX only_RR have_VH0 an_AT1 impact_NN1 on_II the_AT society_NN1 but_CCB also_RR on_II the_AT organization_NN1 itself_PPX1 ._. 
</s>
<s>
(_( Sukserm_NN1 and_CC Takahashi_NP1 2010_MC )_) If_CS the_AT public_JJ relations_NN2 department_NN1 is_VBZ responsible_JJ for_IF CSR_NP1 strategies_NN2 ,_, the_AT result_NN1 might_VM be_VBI that_CST the_AT image_NN1 of_IO the_AT company_NN1 or_CC the_AT brand_NN1 will_VM be_VBI in_II the_AT spotlight_NN1 ._. 
</s>
<s>
This_DD1 can_VM be_VBI a_AT1 positive_JJ topic_NN1 but_CCB it_PPH1 may_VM also_RR result_VVI in_II the_AT way_NN1 that_CST nothing_PN1 actually_RR gets_VVZ done_VDN ._. 
</s>
<s>
The_AT CSR_NP1 matters_NN2 might_VM just_RR be_VBI a_AT1 facade_NN1 to_II the_AT outer_JJ world_NN1 but_CCB no_AT actions_NN2 are_VBR actually_RR taken_VVN ._. 
</s>
<s>
Another_DD1 department_NN1 that_CST could_VM be_VBI in_II charge_NN1 for_IF the_AT CSR_NP1 strategies_NN2 is_VBZ the_AT legal_JJ department_NN1 ._. 
</s>
<s>
By_II having_VHG the_AT legal_JJ department_NN1 taking_VVG care_NN1 of_IO CSR_NP1 matters_VVZ the_AT organization_NN1 can_VM be_VBI sure_JJ that_CST they_PPHS2 will_VM minimize_VVI any_DD potential_JJ risks_NN2 within_II the_AT company_NN1 ._. 
</s>
<s>
The_AT concern_NN1 with_IW this_DD1 though_CS ,_, is_VBZ that_DD1 the_AT legal_JJ department_NN1 might_VM concentrate_VVI solely_RR on_II minimizing_VVG the_AT risks_NN2 which_DDQ would_VM mean_VVI that_DD1 creative_JJ ideas_NN2 could_VM get_VVI left_VVN behind_RL ._. 
</s>
<s>
(_( Mees_NP2 and_CC Bonham_NP1 2004_MC )_) Having_VHG two_MC different_JJ organizational_JJ identities_NN2 can_VM ,_, at_II the_AT end_NN1 ,_, be_VBI very_RG damaging_JJ to_II a_AT1 company_NN1 ._. 
</s>
<s>
Organizational_JJ identities_NN2 in_II this_DD1 context_NN1 means_VVZ the_AT identity_NN1 the_AT organization_NN1 shows_VVZ to_II the_AT public_NN1 and_CC the_AT one_PN1 for_IF the_AT business_NN1 ._. 
</s>
<s>
(_( Ledwidge_VV0 2007_MC )_) The_AT HR_NNU department_NN1 on_II the_AT other_JJ hand_NN1 ,_, has_VHZ a_AT1 unique_JJ position_NN1 in_II an_AT1 organization_NN1 and_CC is_VBZ therefore_RR a_AT1 good_JJ candidate_NN1 to_TO take_VVI care_NN1 of_IO CSR_NP1 matters_NN2 ._. 
</s>
<s>
(_( Mees_NP2 and_CC Bonham_NP1 2004_MC )_) If_CS the_AT HR_NNU department_NN1 is_VBZ the_AT one_PN1 in_II charge_NN1 for_IF CSR_NP1 ,_, it_PPH1 is_VBZ important_JJ for_IF them_PPHO2 to_TO learn_VVI how_RRQ the_AT employees_NN2 ,_, the_AT customers_NN2 and_CC the_AT organization_NN1 itself_PPX1 will_VM be_VBI affected_VVN when_CS establishing_VVG CSR_NP1 strategies_NN2 ._. 
</s>
<s>
When_CS they_PPHS2 decide_VV0 on_II the_AT CSR_NP1 strategy_NN1 the_AT HR_NNU department_NN1 is_VBZ the_AT one_PN1 that_CST has_VHZ to_TO extend_VVI this_DD1 strategy_NN1 over_II the_AT whole_JJ organization_NN1 ._. 
</s>
<s>
The_AT employees_NN2 or_CC actually_RR the_AT whole_JJ organization_NN1 must_VM agree_VVI on_II the_AT beliefs_NN2 and_CC values_NN2 of_IO the_AT CSR_NP1 strategy_NN1 ._. 
</s>
<s>
(_( Ledwidge_VV0 2007_MC )_) Brian_NP1 Glade_NP1 (_( 2008_MC )_) found_VVD that_CST this_DD1 was_VBDZ one_MC1 way_NN1 for_IF the_AT HR_NNU department_NN1 to_TO build_VVI up_RP the_AT strategies_NN2 in_II his_APPGE study_NN1 ._. 
</s>
<s>
He_PPHS1 found_VVD that_DD1 building_NN1 CRS_NP1 strategies_NN2 into_II the_AT organizational_JJ mission_NN1 was_VBDZ a_AT1 way_NN1 to_TO incorporate_VVI CSR_NP1 strategies_NN2 into_II the_AT organizational_JJ culture_NN1 ._. 
</s>
<s>
He_PPHS1 also_RR found_VVD that_CST another_DD1 mayor_NN1 applicator_NN1 of_IO CSR_NP1 strategies_NN2 was_VBDZ the_AT public_JJ relations_NN2 department_NN1 ._. 
</s>
<s>
(_( Glade_VV0 2008_MC )_) Analysis_NN1 In_II the_AT beginning_NN1 of_IO this_DD1 paper_NN1 the_AT importance_NN1 of_IO CSR_NP1 was_VBDZ discussed_VVN ._. 
</s>
<s>
It_PPH1 can_VM be_VBI concluded_VVN that_CST CSR_NP1 is_VBZ something_PN1 that_CST organizations_NN2 nowadays_RT are_VBR implementing_VVG to_II their_APPGE business_NN1 strategy_NN1 as_CSA there_EX are_VBR many_DA2 more_DAR opinions_NN2 to_TO take_VVI into_II consideration_NN1 ._. 
</s>
<s>
The_AT different_JJ reasons_NN2 for_IF implementing_VVG CSR_NP1 strategies_NN2 were_VBDR to_TO improve_VVI the_AT company_NN1 image_NN1 ,_, to_TO build_VVI up_RP a_AT1 stronger_JJR brand_NN1 and_CC to_TO add_VVI value_NN1 to_II the_AT company_NN1 ._. 
</s>
<s>
The_AT problems_NN2 that_CST can_VM occur_VVI with_IW these_DD2 strategies_NN2 are_VBR that_CST they_PPHS2 are_VB0 nt_XX taken_VVN seriously_RR and_CC the_AT organization_NN1 is_VBZ just_RR trying_VVG to_TO fool_VVI the_AT rest_NN1 of_IO the_AT world_NN1 by_II saying_VVG that_CST they_PPHS2 are_VBR acting_VVG socially_RR responsible_JJ ._. 
</s>
<s>
The_AT benefit_NN1 that_CST an_AT1 organization_NN1 can_VM gain_VVI by_II being_VBG socially_RR responsible_JJ comes_VVZ when_RRQ they_PPHS2 recognize_VV0 that_CST CSR_NP1 is_VBZ a_AT1 long-term_JJ investment_NN1 and_CC that_CST they_PPHS2 actually_RR can_VM gain_VVI something_PN1 positive_JJ from_II implementing_VVG these_DD2 strategies_NN2 ._. 
</s>
<s>
One_MC1 of_IO the_AT arguments_NN2 about_II creating_VVG CSR_NP1 strategies_NN2 pointed_VVD out_RP that_CST the_AT strategy_NN1 comes_VVZ from_II the_AT mission_NN1 of_IO the_AT company_NN1 ,_, it_PPH1 is_VBZ there_RL the_AT concept_NN1 begins_VVZ ._. 
</s>
<s>
Another_DD1 concept_NN1 that_CST is_VBZ influenced_VVN on_II the_AT values_NN2 and_CC mission_NN1 of_IO the_AT company_NN1 is_VBZ the_AT HR_NNU function_NN1 ._. 
</s>
<s>
The_AT HR_NNU department_NN1 is_VBZ a_AT1 department_NN1 that_CST not_XX only_RR comes_VVZ from_II the_AT core_NN1 values_NN2 of_IO the_AT company_NN1 but_CCB actually_RR has_VHZ a_AT1 capability_NN1 of_IO teaching_VVG these_DD2 values_NN2 to_II other_JJ employees_NN2 ._. 
</s>
<s>
As_RG many_DA2 authors_NN2 have_VH0 argued_VVN HR_NNU can_VM be_VBI ,_, and_CC would_VM be_VBI ,_, a_AT1 good_JJ candidate_NN1 for_IF taking_VVG on_RP the_AT responsibility_NN1 of_IO CSR_NP1 ._. 
</s>
<s>
The_AT public_JJ relations_NN2 department_NN1 is_VBZ another_DD1 candidate_NN1 that_CST has_VHZ been_VBN brought_VVN up_RP but_CCB there_EX have_VH0 been_VBN some_DD doubts_NN2 about_II this_DD1 too_RR ._. 
</s>
<s>
The_AT concern_NN1 is_VBZ that_CST if_CS the_AT public_JJ relations_NN2 department_NN1 takes_VVZ on_RP this_DD1 responsibility_NN1 ,_, the_AT CSR_NP1 strategies_NN2 might_VM just_RR remain_VVI as_II an_AT1 idea_NN1 and_CC nothing_PN1 will_VM actually_RR get_VVI done_VDN ._. 
</s>
<s>
The_AT main_JJ arguments_NN2 that_CST have_VH0 been_VBN stated_VVN for_IF why_RRQ HR_NNU would_VM be_VBI such_DA a_AT1 good_JJ candidate_NN1 for_IF managing_VVG CSR_NP1 is_VBZ that_CST both_DB2 functions_NN2 are_VBR based_VVN on_II organizational_JJ values_NN2 ._. 
</s>
<s>
As_CSA already_RR stated_VVD the_AT CSR_NP1 values_NN2 should_VM start_VVI from_II inside_RL the_AT company_NN1 and_CC build_VVI on_II the_AT mission_NN1 of_IO the_AT organization_NN1 ._. 
</s>
<s>
The_AT HR_NNU department_NN1 has_VHZ an_AT1 advantage_NN1 here_RL as_CSA they_PPHS2 are_VBR the_AT ones_NN2 who_PNQS can_VM affect_VVI the_AT behavior_NN1 of_IO employees_NN2 in_II an_AT1 organization_NN1 ._. 
</s>
<s>
Conclusion_NN1 The_AT purpose_NN1 of_IO this_DD1 paper_NN1 was_VBDZ to_TO get_VVI a_AT1 deeper_JJR understanding_NN1 of_IO the_AT connection_NN1 between_II HR_NNU and_CC CSR_NP1 and_CC to_TO see_VVI if_CS HR_NNU could_VM be_VBI in_II31 charge_II32 of_II33 this_DD1 matter_NN1 ._. 
</s>
<s>
As_II a_AT1 conclusion_NN1 it_PPH1 can_VM be_VBI said_VVN that_CST there_EX are_VBR many_DA2 different_JJ motives_NN2 why_RRQ HR_NNU in_II fact_NN1 could_VM be_VBI in_II31 charge_II32 of_II33 CSR_NP1 ._. 
</s>
<s>
The_AT connections_NN2 between_II the_AT two_MC areas_NN2 are_VBR clear_JJ and_CC there_EX are_VBR a_AT1 lot_NN1 of_IO implications_NN2 that_CST states_VVZ that_CST HR_NNU could_VM take_VVI on_RP this_DD1 responsibility_NN1 ._. 
</s>
<s>
There_EX is_VBZ still_JJ room_NN1 for_IF future_JJ research_NN1 about_II how_RRQ the_AT HR_NNU department_NN1 in_II practice_NN1 would_VM follow_VVI through_RP with_IW this_DD1 role_NN1 could_VM be_VBI an_AT1 interesting_JJ subject_NN1 ._. 
</s>
