<s>
Business_NN1 Models_NN2 1_MC1 ._. 
</s>
<s>
Introduction_NN1 The_AT rapidly_RR increased_JJ customer_NN1 power_NN1 has_VHZ put_VVN firms_NN2 into_II a_AT1 completely_RR new_JJ situation_NN1 ._. 
</s>
<s>
They_PPHS2 need_VV0 to_TO respond_VVI to_II the_AT evolving_JJ needs_NN2 of_IO customers_NN2 at_II an_AT1 increasing_JJ pace_NN1 ._. 
</s>
<s>
This_DD1 requires_VVZ strategic_JJ agility_NN1 and_CC business_NN1 models_NN2 ,_, which_DDQ are_VBR ready_JJ for_IF continuous_JJ innovation_NN1 and_CC change_NN1 ._. 
</s>
<s>
The_AT ability_NN1 to_TO design_VVI agile_JJ but_CCB sustainable_JJ business_NN1 models_NN2 ,_, which_DDQ fit_VV0 the_AT firm_NN1 and_CC answer_VV0 to_II customers_NN2 needs_VVZ ,_, is_VBZ quickly_RR becoming_VVG the_AT most_RGT critical_JJ competitive_JJ advantage_NN1 a_AT1 firm_NN1 holds_VVZ ._. 
</s>
<s>
1.1_MC Research_NN1 gap_NN1 This_DD1 paper_NN1 participates_VVZ in_II the_AT strategic_JJ marketing_NN1 discussion_NN1 regarding_II business_NN1 models_NN2 ._. 
</s>
<s>
Business_NN1 model_NN1 as_II a_AT1 concept_NN1 has_VHZ a_AT1 fairly_RR short_JJ history_NN1 in_II its_APPGE current_JJ form_NN1 and_CC has_VHZ not_XX received_VVN widespread_JJ attention_NN1 in_II marketing_NN1 literature_NN1 yet_RR ._. 
</s>
<s>
Despite_II this_DD1 ,_, business_NN1 models_NN2 have_VH0 very_RG quickly_RR emerged_VVN to_II management_NN1 vocabulary_NN1 and_CC become_VV0 one_MC1 of_IO the_AT hottest_JJT topics_NN2 among_II practitioners_NN2 ._. 
</s>
<s>
Recent_JJ literature_NN1 suggests_VVZ that_DD1 business_NN1 models_NN2 can_VM have_VHI an_AT1 important_JJ role_NN1 in_II corporate_JJ management_NN1 ,_, and_CC effective_JJ business_NN1 models_NN2 are_VBR seen_VVN as_CSA one_MC1 key_JJ success_NN1 factor_NN1 for_IF firms_NN2 in_II the_AT future_NN1 ._. 
</s>
<s>
(_( Shafer_NP1 ,_, Smith_NP1 &;_NULL Linder_NP1 ,_, 2005_MC )_) According_II21 to_II22 Osterwalders(2009)_FO vision_NN1 firms_NN2 will_VM increasingly_RR enter_VVI into_II networked_JJ operations_NN2 in_II the_AT future_NN1 ,_, and_CC business_NN1 models_NN2 will_VM become_VVI the_AT boundaries_NN2 of_IO competition_NN1 ._. 
</s>
<s>
However_RR ,_, while_CS it_PPH1 is_VBZ quite_RG fashionable_JJ to_TO discuss_VVI business_NN1 models_NN2 ,_, there_EX is_VBZ still_RR much_DA1 confusion_NN1 about_II what_DDQ business_NN1 models_NN2 are_VBR and_CC how_RRQ they_PPHS2 can_VM be_VBI used_VVN (_( Shafer_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2005_MC )_) ._. 
</s>
<s>
With_IW the_AT increased_JJ attention_NN1 from_II management_NN1 ,_, also_RR academia_NN1 has_VHZ taken_VVN more_DAR interest_NN1 towards_II business_NN1 models_NN2 recently_RR ._. 
</s>
<s>
The_AT change_NN1 of_IO decade_NNT1 saw_VVD a_AT1 dramatic_JJ increase_NN1 in_II the_AT amount_NN1 of_IO published_JJ articles_NN2 regarding_II business_NN1 models_NN2 ._. 
</s>
<s>
An_AT1 academic_JJ journal_NN1 Long_JJ Range_NN1 Planning_NN1 published_VVD a_AT1 special_JJ issue_NN1 on_II business_NN1 models_NN2 in_II spring_NN1 2010_MC and_CC more_DAR articles_NN2 on_II the_AT subject_NN1 are_VBR published_VVN with_IW an_AT1 increased_JJ frequency_NN1 in_II various_JJ academic_JJ journals_NN2 ._. 
</s>
<s>
Majority_NN1 of_IO the_AT articles_NN2 are_VBR however_RR conceptual_JJ in_II nature_NN1 ,_, and_CC there_EX are_VBR very_RG few_DA2 researchers_NN2 who_PNQS have_VH0 showed_VVN empirical_JJ evidence_NN1 on_II the_AT efficiency_NN1 of_IO using_VVG business_NN1 models_NN2 as_II a_AT1 tool_NN1 for_IF management_NN1 ._. 
</s>
<s>
Only_RR two_MC studies_NN2 were_VBDR identified_VVN ,_, whichdiscussed_JJ business_NN1 model_NN1 elements_NN2 in_II empirical_JJ context_NN1 ._. 
</s>
<s>
However_RR ,_, the_AT concentration_NN1 on_II these_DD2 was_VBDZ to_TO identify_VVI firm_JJ level_JJ business_NN1 models_NN2 rather_CS21 than_CS22 identify_VVI the_AT elements_NN2 within_II the_AT organization_NN1 ._. 
</s>
<s>
Therefore_RR there_EX is_VBZ a_AT1 clear_JJ research_NN1 gap_NN1 in_II the_AT empirical_JJ evidence_NN1 of_IO the_AT functioning_NN1 of_IO business_NN1 model_NN1 ._. 
</s>
<s>
1.2_MC Research_NN1 problem_NN1 Despite_II the_AT recent_JJ increase_NN1 of_IO interest_NN1 ,_, business_NN1 model_NN1 as_II a_AT1 construct_NN1 is_VBZ still_RR rather_RG unexplored_JJ and_CC lacks_VVZ a_AT1 unified_JJ definition_NN1 and_CC proper_JJ taxonomical_JJ criteria_NN2 ._. 
</s>
<s>
Therefore_RR the_AT purpose_NN1 of_IO this_DD1 paper_NN1 is_VBZ toserve_NN1 as_II an_AT1 exploratory_JJ study_NN1 to_II the_AT subject_NN1 ,_, by_II trying_VVG to_TO merge_VVI existing_JJ knowledge_NN1 and_CC identify_VVI common_JJ threads_NN2 from_II different_JJ academic_JJ papers_NN2 to_TO form_VVI a_AT1 unified_JJ understanding_NN1 of_IO the_AT topic_NN1 ._. 
</s>
<s>
The_AT paper_NN1 aims_VVZ at_II describing_VVG what_DDQ a_AT1 business_NN1 model_NN1 is_VBZ ,_, identifying_VVG the_AT design_NN1 elements_NN2 of_IO an_AT1 effective_JJ business_NN1 model_NN1 ,_, and_CC illustrating_VVG how_RRQ to_TO manage_VVI business_NN1 model(s).Furthermore_NNU ,_, empirical_JJ evidence_NN1 from_II a_AT1 case_NN1 organization_NN1 will_VM be_VBI used_VVN to_TO illustrate_VVI current_JJ situation_NN1 within_II a_AT1 firm_NN1 ._. 
</s>
<s>
1.3_MC Structure_NN1 of_IO the_AT paper_NN1 The_AT paper_NN1 is_VBZ divided_VVN into_II five_MC main_JJ sections_NN2 :_: (_( 1_MC1 )_) Background_NN1 and_CC definition_NN1 ,_, (_( 2_MC )_) contents_NN2 ,_, (_( 3_MC )_) management_NN1 ,_, (_( 4_MC )_) empirical_JJ evidence_NN1 from_II a_AT1 case_NN1 organization_NN1 ,_, and_CC (_( 5_MC )_) conclusions_NN2 and_CC implications_NN2 ._. 
</s>
<s>
After_CS the_AT introduction_NN1 ,_, the_AT background_NN1 chapter_NN1 builds_VVZ a_AT1 ground_NN1 for_IF the_AT study_NN1 by_II briefly_RR going_VVG through_II the_AT history_NN1 of_IO business_NN1 models_NN2 as_II a_AT1 concept_NN1 ,_, followed_VVN with_IW definitions_NN2 ._. 
</s>
<s>
Then_RT the_AT contents_NN2 of_IO an_AT1 effective_JJ business_NN1 model_NN1 are_VBR discussed_VVN ,_, the_AT role_NN1 of_IO business_NN1 model_NN1 in_II an_AT1 organization_NN1 is_VBZ discussed_VVN ,_, and_CC the_AT management_NN1 of_IO business_NN1 models_NN2 is_VBZ touched_VVN upon_II ._. 
</s>
<s>
After_II building_VVG a_AT1 solid_JJ theoretical_JJ understanding_NN1 of_IO the_AT topic_NN1 the_AT previously_RR discussed_VVN issues_NN2 are_VBR compared_VVN to_II the_AT empirical_JJ reality_NN1 within_II a_AT1 case_NN1 organization_NN1 ._. 
</s>
<s>
Finally_RR ,_, conclusions_NN2 are_VBR drawn_VVN and_CC implications_NN2 for_IF managers_NN2 and_CC practitioners_NN2 made_VVD ._. 
</s>
<s>
2_MC ._. 
</s>
<s>
Background_NN1 of_IO business_NN1 models_NN2 The_AT term_NN1 business_NN1 model_NN1 has_VHZ its_APPGE origins_NN2 in_II year_NNT1 1957_MC when_RRQ it_PPH1 was_VBDZ first_MD time_NNT1 used_VVN in_II an_AT1 academic_JJ paper_NN1 (_( Osterwalder_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2005_MC )_) ._. 
</s>
<s>
The_AT term_NN1 started_VVD gaining_VVG wider_JJR popularity_NN1 from_II late_JJ 1990s_MC2 onwards_RL when_CS the_AT concept_NN1 was_VBDZ discussed_VVN mainly_RR in_II Internet_NP1 context_NN1 (_( Osterwalder_NP1 ,_, Pigneur_NP1 &Tucci,2005).;_NULL A_AT1 few_DA2 years_NNT2 after_II the_AT increased_JJ fame_NN1 ,_, several_DA2 researchers_NN2 noticedthat_VV0 despite_II its_APPGE popularity_NN1 the_AT business_NN1 model_NN1 construct_NN1 was_VBDZ theoretically_RR vague_JJ ,_, and_CC lacked_VVD a_AT1 proper_JJ definition_NN1 ._. 
</s>
<s>
(_( E.g._REX Tikkanen_NP1 ,_, Lamberg_NP1 ,_, Parvinen_NP1 &Kallunki,;_NULL 2005_MC ;_; Osterwalder_NP1 ,_, 2004_MC ;_; Osterwalder_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2005_MC )_) Therefore_RR ,_, during_II the_AT past_JJ ten_MC years_NNT2 researchers_NN2 have_VH0 done_VDN extensive_JJ literature_NN1 reviews_NN2 and_CC compared_VVD various_JJ business_NN1 model_NN1 definitions_NN2 in_BCL21 order_BCL22 to_TO merge_VVI the_AT existing_JJ knowledge_NN1 to_TO form_VVI a_AT1 holding_JJ conceptual_JJ framework_NN1 of_IO the_AT construct_NN1 ._. 
</s>
<s>
(_( E.g._REX Osterwalder_NP1 2004_MC ;_; Tikkanen_NP1 et_RA21 al._RA22 ,_, 2005_MC ;_; Nenonen_NP1 &Storbacka,;_NULL 2010_MC )_) However_RR ,_, despite_II these_DD2 attempts_NN2 there_EX are_VBR still_RR no_UH commonly_RR agreed_VVN conceptual_JJ definition_NN1 ,_, scientific_JJ taxonomical_JJ criteria_NN2 or_CC framework_NN1 for_IF business_NN1 models_NN2 (_( Nenonen_NP1 &Storbacka,;_NULL 2010_MC )_) ._. 
</s>
<s>
Researchers_NN2 still_RR criticize_VV0 the_AT poor_JJ conceptualization_NN1 ,_, and_CC it_PPH1 seems_VVZ that_CST work_VV0 in_II the_AT field_NN1 is_VBZ anything_RR21 but_RR22 over_RP yet_RR ._. 
</s>
<s>
Despite_II this_DD1 ,_, some_DD researchers_NN2 have_VH0 already_RR reached_VVN beyond_II the_AT conceptualization_NN1 stage_NN1 in_II an_AT1 attempt_NN1 to_TO form_VVI a_AT1 design_NN1 framework_NN1 of_IO business_NN1 model_NN1 construction_NN1 elements_NN2 ._. 
</s>
<s>
(_( For_REX21 example_REX22 Osterwalder_NP1 2004_MC ;_; Storbacka_NP1 ,_, 2009_MC ;_; Nenonen_NP1 &Storbacka,;_NULL 2010_MC ;_; Teece_NP1 ,_, 2010_MC )_) However_RR ,_, due_II21 to_II22 the_AT lack_NN1 of_IO a_AT1 unified_JJ definition_NN1 ,_, also_RR the_AT frameworks_NN2 differ_VV0 in_II their_APPGE contents_NN2 rather_RG much_DA1 ._. 
</s>
<s>
Therefore_RR there_EX is_VBZ a_AT1 clear_JJ need_NN1 to_TO research_VVI these_DD2 issues_NN2 further_RRR in_II order_NN1 to_II narrow_JJ down_II the_AT variety_NN1 and_CC to_TO form_VVI a_AT1 mutual_JJ understanding_NN1 ._. 
</s>
<s>
2.1_MC ._. 
</s>
<s>
Defining_VVG the_AT business_NN1 model_NN1 concept_NN1 Joan_NP1 Magretta_NP1 wrote_VVD a_AT1 seminal_JJ article_NN1 on_II business_NN1 models_NN2 in_II 2002_MC in_II Harvard_NP1 Business_NN1 Review_NN1 where_CS she_PPHS1 aimed_VVD at_II making_VVG a_AT1 simple_JJ ,_, working_VVG definition_NN1 of_IO the_AT concept_NN1 ._. 
</s>
<s>
She_PPHS1 concluded_VVD that_DD1 business_NN1 models_NN2 are_VBR stories_NN2 ,_, which_DDQ explain_VV0 how_RRQ enterprises_NN2 work_VV0 ._. 
</s>
<s>
On_II same_DA vein_NN1 ,_, Osterwalder_NP1 (_( 2004_MC )_) talks_NN2 about_II the_AT importance_NN1 of_IO clear_JJ communication_NN1 between_II different_JJ business_NN1 operations_NN2 to_TO create_VVI a_AT1 shared_JJ and_CC common_JJ understanding_NN1 of_IO what_DDQ a_AT1 company_NN1 does_VDZ ._. 
</s>
<s>
Furthermore_RR ,_, Osterwalder_NP1 (_( 2004_MC )_) points_VVZ out_RP that_DD1 business_NN1 models_NN2 facilitate_VV0 communication_NN1 between_II people_NN by_II acting_VVG as_II a_AT1 common_JJ language_NN1 between_II stakeholders_NN2 so_CS21 that_CS22 they_PPHS2 are_VBR able_JK to_TO formulate_VVI ideas_NN2 in_II a_AT1 way_NN1 that_CST everybody_PN1 understands_VVZ ._. 
</s>
<s>
Similarly_RR Storbacka_NP1 (_( 2009:26_MC )_) sees_VVZ business_NN1 models_NN2 as_CSA important_JJ communication_NN1 vehicles_NN2 in_II organizations_NN2 they_PPHS2 help_VV0 individuals_NN2 to_TO understand_VVI the_AT firms_NN2 business_NN1 logic_NN1 ._. 
</s>
<s>
Business_NN1 models_NN2 could_VM thus_RR be_VBI described_VVN as_II a_AT1 common_JJ language_NN1 ,_, which_DDQ helps_VVZ to_TO align_VVI the_AT views_NN2 of_IO different_JJ business_NN1 functions_NN2 in_BCL21 order_BCL22 to_TO optimize_VVI the_AT business_NN1 performance_NN1 (_( Magretta_NP1 ,_, 2002_MC )_) ._. 
</s>
<s>
This_DD1 view_NN1 is_VBZ emphasized_VVN in_II these_DD2 definitions_NN2 :_: A_AT1 business_NN1 model_NN1 is_VBZ a_AT1 conceptual_JJ tool_NN1 that_CST contains_VVZ a_AT1 set_NN1 of_IO elements_NN2 and_CC their_APPGE relationships_NN2 and_CC allows_VVZ expressing_VVG the_AT business_NN1 logic_NN1 of_IO a_AT1 specific_JJ firm_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ a_AT1 description_NN1 of_IO the_AT value_NN1 a_AT1 company_NN1 offers_NN2 to_II one_MC1 or_CC several_DA2 segments_NN2 of_IO customers_NN2 and_CC of_IO the_AT architecture_NN1 of_IO the_AT firm_NN1 and_CC its_APPGE network_NN1 of_IO partners_NN2 for_IF creating_VVG ,_, marketing_NN1 ,_, and_CC delivering_VVG this_DD1 value_NN1 and_CC relationship_NN1 capital_NN1 ,_, to_TO generate_VVI profitable_JJ and_CC sustainable_JJ revenue_NN1 streams._NNU Osterwalder_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2005:10_MC )_) We_PPIS2 define_VV0 a_AT1 business_NN1 model_NN1 as_II a_AT1 representation_NN1 of_IO a_AT1 firms_NN2 underlying_VVG core_NN1 logic_NN1 and_CC strategic_JJ choices_NN2 for_IF creating_VVG and_CC capturing_VVG value_NN1 within_II a_AT1 value_NN1 network_NN1 ._. 
</s>
<s>
Shafer_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2005:202_MC )_) For_IF the_AT purpose_NN1 of_IO this_DD1 paper_NN1 ,_, and_CC drawing_VVG from_II the_AT above-mentioned_JJ definitions_NN2 ,_, business_NN1 model_NN1 is_VBZ here_RL defined_VVN as_II the_AT operations_NN2 logic_NN1 of_IO how_RRQ an_AT1 organization_NN1 and_CC its_APPGE functions_NN2 are_VBR arranged_VVN in_BCL21 order_BCL22 to_TO meet_VVI the_AT targets_NN2 set_VVN by_II strategy_NN1 and_CC vision.In_NNU order_NN1 to_TO understand_VVI how_RRQ business_NN1 model_NN1 functions_NN2 in_II enabling_VVG the_AT realization_NN1 of_IO a_AT1 set_NN1 strategy_NN1 it_PPH1 is_VBZ necessary_JJ to_TO understand_VVI its_APPGE relationships_NN2 to_II other_JJ business_NN1 functions_NN2 ._. 
</s>
<s>
Additionally_RR it_PPH1 is_VBZ important_JJ to_TO clarify_VVI howbusiness_NN1 models_NN2 are_VBR constructed_VVN ,_, andthe_VV0 roles_NN2 and_CC management_NN1 of_IO effective_JJ models_NN2 ._. 
</s>
<s>
The_AT following_JJ chapters_NN2 bite_VV0 into_II these_DD2 aspects_NN2 ._. 
</s>
<s>
2_MC ._. 
</s>
<s>
Locus_NN1 and_CC contents_NN2 of_IO business_NN1 model_NN1 This_DD1 chapter_NN1 explains_VVZ the_AT location_NN1 of_IO a_AT1 business_NN1 model_NN1 related_VVN to_II other_JJ functions_NN2 within_II a_AT1 firm_NN1 as_RG well_RR as_CSA discusses_VVZ the_AT design_NN1 elements_NN2 ,_, in_II other_JJ words_NN2 contents_NN2 ,_, of_IO an_AT1 effective_JJ business_NN1 model_NN1 ._. 
</s>
<s>
2.1_MC Locus_NN1 of_IO business_NN1 model_NN1 The_AT lack_NN1 of_IO consensus_NN1 within_II the_AT academia_NN1 regarding_II business_NN1 models_NN2 may_VM be_VBI a_AT1 result_NN1 of_IO an_AT1 interest_NN1 in_II the_AT concept_NN1 from_II a_AT1 wide_JJ range_NN1 of_IO disciplines_NN2 ,_, which_DDQ all_DB have_VH0 found_VVN a_AT1 connection_NN1 to_II the_AT term_NN1 (_( Shafer_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2005_MC )_) ._. 
</s>
<s>
Business_NN1 model_NN1 touches_VVZ all_DB areas_NN2 of_IO business_NN1 and_CC thus_RR it_PPH1 is_VBZ sometimes_RT difficult_JJ to_TO locate_VVI its_APPGE exact_JJ position_NN1 and_CC role_NN1 ._. 
</s>
<s>
One_MC1 of_IO the_AT most_RGT difficult_JJ things_NN2 seems_VVZ to_TO be_VBI to_TO distinguish_VVI it_PPH1 from_II other_JJ business_NN1 practices_NN2 (_( Osterwalder_NP1 ,_, 2004_MC )_) ._. 
</s>
<s>
The_AT definition_NN1 and_CC role_NN1 of_IO business_NN1 model_NN1 is_VBZ closely_RR related_VVN to_II strategy_NN1 ,_, and_CC therefore_RR often_RR confused_VVN with_IW it_PPH1 ._. 
</s>
<s>
Wikstrm_VV0 ,_, Artto_NP1 ,_, Kujala_NP1 &S;_NULL derlund(2010)_FO conclude_VV0 that_CST while_CS strategy_NN1 emphasizes_VVZ competition_NN1 ,_, business_NN1 models_NN2 are_VBR built_VVN more_RRR on_II value_NN1 creation_NN1 for_IF customers_NN2 ._. 
</s>
<s>
Business_NN1 models_NN2 provide_VV0 a_AT1 link_NN1 between_II operations_NN2 and_CC strategy_NN1 and_CC therefore_RR ,_, even_CS21 though_CS22 it_PPH1 is_VBZ important_JJ to_TO distinguish_VVI them_PPHO2 from_II each_PPX221 other_PPX222 ,_, they_PPHS2 still_RR need_VV0 to_TO be_VBI integrated_VVN into_II both_DB2 value_NN1 creation_NN1 and_CC strategy_NN1 processes_NN2 ,_, and_CC aligned_VVN with_IW other_JJ business_NN1 structures_NN2 and_CC operations_NN2 ._. 
</s>
<s>
(_( Mkinen_JJ &Sepp;_NULL nen_NN1 ,_, 2007_MC ;_; Wikstrm_NP1 et_RA21 al._RA22 ,_, 2010_MC )_) Osterwalder_NP1 (_( 2004_MC )_) clarifies_VVZ that_CST while_CS strategy_NN1 ,_, business_NN1 models_NN2 ,_, and_CC process_VV0 models_NN2 all_DB address_VV0 similar_JJ problems_NN2 ,_, they_PPHS2 do_VD0 it_PPH1 in_II different_JJ layers_NN2 ._. 
</s>
<s>
Figure_VV0 1_MC1 shows_VVZ the_AT different_JJ business_NN1 layers_NN2 and_CC the_AT relationship_NN1 of_IO them_PPHO2 to_II each_PPX221 other_PPX222 ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) A_ZZ1 firms_NN2 strategy_NN1 belongs_VVZ to_II the_AT planning_NN1 level_NN1 ,_, while_CS business_NN1 model_NN1 is_VBZ a_AT1 blueprint_NN1 of_IO how_RRQ strategy_NN1 is_VBZ brought_VVN into_II action_NN1 in_II an_AT1 organization_NN1 ,_, and_CC implementation_NN1 is_VBZ done_VDN on_II the_AT third_MD process_NN1 layer_NN1 (_( Osterwalder_NP1 ,_, 2004_MC )_) ._. 
</s>
<s>
Similarly_RR ,_, Tikkanen_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2005_MC )_) conclude_VV0 that_DD1 strategy_NN1 gives_VVZ meaning_NN1 and_CC direction_NN1 to_II business_NN1 model_NN1 design_NN1 ._. 
</s>
<s>
Teece_NP1 (_( 2010_MC )_) clarifies_VVZ the_AT relationship_NN1 further_RRR by_II describing_VVG strategy_NN1 creation_NN1 as_II a_AT1 more_RGR granular_JJ exercise_NN1 ,_, while_CS business_NN1 model_NN1 design_NN1 requires_VVZ more_DAR fine-tuning_NN1 such_II21 as_II22 segmenting_VVG customers_NN2 ,_, creating_VVG value_NN1 propositions_NN2 and_CC organizing_VVG operations_NN2 ._. 
</s>
<s>
Additionally_RR ,_, Teece_NP1 (_( 2010_MC )_) explains_VVZ business_NN1 models_NN2 as_CSA being_VBG more_RGR generic_JJ than_CSN strategy_NN1 ,_, and_CC therefore_RR more_RGR transparent_JJ to_II public_JJ than_CSN strategic_JJ choices_NN2 ._. 
</s>
<s>
2.2_MC Contents_NN2 of_IO a_AT1 business_NN1 model_NN1 Several_DA2 researchers_NN2 have_VH0 attempted_VVN to_TO clarify_VVI the_AT concept_NN1 of_IO business_NN1 model_NN1 through_II creating_VVG frameworks_NN2 of_IO design_NN1 elements_NN2 that_CST the_AT models_NN2 consist_VV0 of_IO ._. 
</s>
<s>
Mkinen_NN1 and_CC Seppnen_NP1 (_( 2007_MC )_) point_VV0 out_RP that_CST when_CS receiving_VVG increased_JJ attention_NN1 from_II the_AT academics_NN2 ,_, business_NN1 models_NN2 have_VH0 been_VBN approached_VVN from_II various_JJ perspectives_NN2 and_CC that_DD1 has_VHZ resulted_VVN in_II formulation_NN1 of_IO several_DA2 alternative_JJ frameworks_NN2 (_( E.g._REX Tikkanen_NP1 et_RA21 al._RA22 ,_, 2005_MC ;_; Storbacka_NP1 ,_, 2009_MC ;_; Teece_NP1 ,_, 2010_MC ;_; )_) ._. 
</s>
<s>
People_NN have_VH0 different_JJ mental_JJ models_NN2 and_CC understand_VV0 business_NN1 models_NN2 in_II different_JJ ways_NN2 ._. 
</s>
<s>
Therefore_RR the_AT frameworks_NN2 serve_VV0 as_CSA necessary_JJ tools_NN2 for_IF sharing_VVG a_AT1 common_JJ agreement_NN1 of_IO what_DDQ elements_NN2 are_VBR included_VVN in_RP within_II the_AT business_NN1 models_NN2 ._. 
</s>
<s>
(_( Osterwalder_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2005_MC )_) Demil_NP1 and_CC Lecocq_NP1 (_( 2010_MC )_) refer_VV0 to_II business_NN1 model_NN1 design_NN1 as_II the_AT articulation_NN1 between_II different_JJ business_NN1 activities_NN2 ._. 
</s>
<s>
There_EX is_VBZ an_AT1 abundance_NN1 of_IO various_JJ frameworks_NN2 ,_, but_CCB no_AT agreement_NN1 within_II the_AT academia_NN1 of_IO the_AT design_NN1 elements_NN2 of_IO a_AT1 superior_JJ business_NN1 model_NN1 (_( Casadesus-Masanell_NP1 &Ricart,;_NULL 2010_MC )_) ._. 
</s>
<s>
The_AT various_JJ frameworks_NN2 differ_VV0 in_II their_APPGE contents_NN2 rather_RG much_DA1 ._. 
</s>
<s>
For_REX21 example_REX22 Shafer_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2005_MC )_) found_VVD 42_MC different_JJ elements_NN2 or_CC building_NN1 blocks_VVZ that_CST different_JJ authors_NN2 mentioned_VVN as_CSA belonging_VVG to_II a_AT1 business_NN1 model_NN1 ._. 
</s>
<s>
However_RR ,_, Nenonen_NP1 &Storbacka;_NULL (_( 2010_MC )_) found_VVD out_RP that_CST there_EX are_VBR five_MC aspects_NN2 that_CST are_VBR present_JJ in_II most_DAT :_: 1_MC1 )_) Explains_VVZ how_RRQ firm_NN1 creates_VVZ value_NN1 for_IF its_APPGE customers_NN2 2_MC )_) Shows_VVZ how_RRQ firm_NN1 yields_VVZ profits_NN2 from_II its_APPGE operations_NN2 3_MC )_) Illuminates_VVZ relationships_NN2 within_II value_NN1 network_NN1 4_MC )_) Illustrates_VVZ firms_NN2 resources_NN2 and_CC capabilities_NN2 5_MC )_) Explicates_VVZ firms_NN2 major_JJ strategic_JJ decisions_NN2 The_AT academia_NN1 is_VBZ however_RR coherent_JJ about_II the_AT dynamic_JJ approach_NN1 towards_II business_NN1 models_NN2 ._. 
</s>
<s>
The_AT elements_NN2 of_IO business_NN1 models_NN2 are_VBR in_II constant_JJ interaction_NN1 and_CC change_NN1 ,_, and_CC a_AT1 shift_NN1 in_II one_MC1 element_NN1 requires_VVZ a_AT1 change_NN1 in_II the_AT entire_JJ configuration_NN1 ._. 
</s>
<s>
The_AT design_NN1 framework-approach_NN1 allows_VVZ firms_NN2 to_TO pro-actively_RR innovate_VVI and_CC design_VVI their_APPGE business_NN1 models_NN2 and_CC to_TO simulate_VVI possibilities_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ also_RR a_AT1 viable_JJ exercise_NN1 to_TO visualize_VVI current_JJ business_NN1 models_NN2 and_CC processes_NN2 involved_VVN to_II it_PPH1 (_( Chesbrough_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
However_RR ,_, since_CS actual_JJ business_NN1 models_NN2 are_VBR usually_RR rather_RG complex_JJ ,_, researchers_NN2 have_VH0 been_VBN obliged_VVN to_TO simplify_VVI the_AT presentation_NN1 (_( Casadesus-Masanell_NP1 &Ricart;_NULL 2010_MC )_) ._. 
</s>
<s>
The_AT frameworks_NN2 are_VBR nevertheless_RR seen_VVN as_CSA important_JJ because_CS they_PPHS2 help_VV0 to_TO communicate_VVI the_AT business_NN1 model_NN1 in_II a_AT1 clear_JJ way_NN1 ._. 
</s>
<s>
Quite_RG pertinently_RR Casadesus-Masanell_NP1 &Ricart;_NULL (_( 2010_MC )_) are_VBR of_IO the_AT opinion_NN1 that_CST business_NN1 model_NN1 design_NN1 is_VBZ closer_JJR to_II being_VBG art_NN1 than_CSN a_AT1 science_NN1 ._. 
</s>
<s>
The_AT frameworks_NN2 have_VH0 been_VBN constructed_VVN to_TO help_VVI managers_NN2 in_II the_AT multifaceted_JJ task_NN1 of_IO designing_VVG and_CC innovating_JJ business_NN1 models_NN2 ._. 
</s>
<s>
However_RR ,_, any_DD model_NN1 is_VBZ only_RR a_AT1 simplification_NN1 of_IO the_AT whole_JJ truth_NN1 ,_, and_CC therefore_RR can_VM not_XX address_VVI all_DB variables_NN2 that_CST the_AT differentiated_JJ processes_NN2 in_II firms_NN2 require_VV0 ._. 
</s>
<s>
Nevertheless_RR ,_, the_AT ultimate_JJ aim_NN1 of_IO using_VVG any_DD kind_NN1 of_IO framework_NN1 is_VBZ that_CST after_CS the_AT modeling_NN1 process_NN1 ,_, a_AT1 firm_NN1 should_VM have_VHI all_DB necessary_JJ aspects_NN2 of_IO business_NN1 planned_VVD to_TO be_VBI able_JK to_TO function_VVI effectively_RR and_CC meet_VVI the_AT needs_NN2 of_IO customers_NN2 ._. 
</s>
<s>
3_MC ._. 
</s>
<s>
Role_NN1 and_CC management_NN1 of_IO business_NN1 models_NN2 This_DD1 chapter_NN1 explains_VVZ the_AT role_NN1 of_IO a_AT1 business_NN1 model_NN1 in_II a_AT1 firm_NN1 as_RG well_RR as_CSA describes_VVZ how_RRQ an_AT1 effective_JJ business_NN1 model_NN1 should_VM be_VBI managed_VVN ._. 
</s>
<s>
3.1_MC Role_NN1 of_IO business_NN1 model_NN1 in_II a_AT1 firm_NN1 Additionally_RR to_II the_AT academic_JJ debate_NN1 regarding_II definitions_NN2 ,_, several_DA2 researchers_NN2 have_VH0 notified_VVN that_CST the_AT business_NN1 model_NN1 concept_NN1 is_VBZ still_RR fairly_RR unknown_JJ and_CC widely_RR misunderstood_VVN among_II practitioners_NN2 ._. 
</s>
<s>
(_( E.g._REX Osterwalder_NP1 et_RA21 al._RA22 ,_, 2005_MC ;_; Shafer_NP1 et_RA21 al._RA22 ,_, 2005_MC ;_; )_) Management_NN1 has_VHZ a_AT1 hard_JJ time_NNT1 identifying_VVG their_APPGE own_DA business_NN1 models_NN2 and_CC understanding_VVG the_AT role_NN1 of_IO a_AT1 business_NN1 model_NN1 :_: what_DDQ does_VDZ it_PPH1 do_VDI and_CC how_RRQ can_VM it_PPH1 be_VBI used_VVN (_( Shafer_NP1 et_RA21 al._RA22 ,_, 2005_MC )_) ._. 
</s>
<s>
This_DD1 chapter_NN1 bites_NN2 into_II this_DD1 problem_NN1 by_II reviewing_VVG the_AT recent_JJ academic_JJ findings_NN2 of_IO the_AT roles_NN2 and_CC uses_NN2 of_IO business_NN1 models_NN2 ._. 
</s>
<s>
Despite_II controversies_NN2 ,_, all_DB researchers_NN2 seem_VV0 to_TO agree_VVI that_CST the_AT effective_JJ design_NN1 and_CC development_NN1 of_IO business_NN1 models_NN2 brings_VVZ competitive_JJ advantage_NN1 ,_, and_CC thus_RR it_PPH1 should_VM receive_VVI increased_JJ attention_NN1 within_II business_NN1 management_NN1 practice_NN1 ._. 
</s>
<s>
(_( E.g._REX Magretta_NP1 ,_, 2002_MC ;_; Nenonen_NP1 &Storbacka,;_NULL 2010_MC )_) The_AT paradox_NN1 with_IW business_NN1 models_NN2 is_VBZ that_CST they_PPHS2 exist_VV0 in_II all_DB firms_NN2 ,_, but_CCB are_VBR not_XX necessarily_RR explicitly_RR discussed_VVN as_II a_AT1 separate_JJ construct_NN1 ._. 
</s>
<s>
Rather_RR ,_, business_NN1 model_NN1 design_NN1 or_CC innovation_NN1 can_VM be_VBI part_NN1 of_IO a_AT1 firms_NN2 inherent_JJ practices_NN2 ,_, which_DDQ are_VBR not_XX given_VVN separate_JJ attention_NN1 ._. 
</s>
<s>
Thus_RR many_DA2 companies_NN2 do_VD0 not_XX have_VHI established_VVN practices_NN2 for_IF business_NN1 model_NN1 design_NN1 ,_, innovation_NN1 or_CC management_NN1 ._. 
</s>
<s>
(_( Magretta_NN1 ,_, 2002_MC )_) The_AT latest_JJT literature_NN1 on_II business_NN1 models_NN2 suggests_VVZ that_CST these_DD2 invisible_JJ practices_NN2 should_VM be_VBI made_VVN visible_JJ in_BCL21 order_BCL22 to_TO start_VVI managing_VVG them_PPHO2 actively_RR and_CC thus_RR increase_VV0 competitive_JJ advantage_NN1 ._. 
</s>
<s>
The_AT idea_NN1 is_VBZ that_CST once_CS the_AT concepts_NN2 are_VBR made_VVN explicit_JJ firms_NN2 can_VM actually_RR start_VVI actively_RR design_VV0 ,_, innovate_VV0 and_CC develop_VVI practices_NN2 involved_JJ in_II them_PPHO2 ._. 
</s>
<s>
(_( Nenonen_NN1 and_CC Storbacka_NP1 ,_, 2010_MC ;_; Osterwalder_NP1 ,_, 2010_MC )_) As_CSA described_VVN earlier_RRR in_II the_AT definition_NN1 context_NN1 ,_, business_NN1 models_NN2 as_CSA constructs_NN2 allow_VV0 for_IF the_AT sharing_NN1 and_CC understanding_NN1 of_IO the_AT business_NN1 logic_NN1 of_IO a_AT1 firm_NN1 ._. 
</s>
<s>
Additionally_RR ,_, an_AT1 effective_JJ business_NN1 model_NN1 can_VM help_VVI management_NN1 in_II the_AT observation_NN1 ,_, measurement_NN1 ,_, comparison_NN1 ,_, and_CC analysis_NN1 of_IO current_JJ business_NN1 practices_NN2 as_II31 well_II32 as_II33 in_II the_AT innovation_NN1 and_CC design_NN1 of_IO new_JJ ,_, prospective_JJ business_NN1 models_NN2 ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, business_NN1 models_NN2 aid_VV0 management_NN1 by_II providing_VVG a_AT1 clear_JJ structure_NN1 through_II which_DDQ operations_NN2 can_VM be_VBI monitored_VVN ,_, analyzed_VVD and_CC designed_VVN ._. 
</s>
<s>
This_DD1 in_II turn_NN1 allows_VVZ for_IF creation_NN1 of_IO sustainable_JJ business_NN1 models_NN2 ,_, which_DDQ are_VBR nevertheless_RR apt_JJ for_IF faster_JJR reactions_NN2 to_II changes_NN2 in_II the_AT business_NN1 environment_NN1 ._. 
</s>
<s>
(_( Osterwalder_VV0 ,_, 2004_MC )_) 3.2_MC Management_NN1 of_IO business_NN1 models_NN2 The_AT previously_RR discussed_VVN locus_NN1 of_IO business_NN1 model_NN1 and_CC design_NN1 frameworks_NN2 are_VBR important_JJ to_TO notify_VVI because_CS a_AT1 strategic_JJ realignment_NN1 ,_, which_DDQ does_VDZ not_XX fit_VVI the_AT business_NN1 model_NN1 components_NN2 ,_, is_VBZ doomed_VVN to_TO fail_VVI ._. 
</s>
<s>
(_( Tikkanen_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2005_MC )_) Thus_RR any_DD change_NN1 within_II strategy_NN1 or_CC business_NN1 model_NN1 needs_VVZ attention_NN1 to_II the_AT other_JJ components_NN2 as_RR21 well_RR22 ._. 
</s>
<s>
This_DD1 chapter_NN1 discusses_VVZ the_AT importance_NN1 of_IO managing_VVG the_AT fit_JJ between_II business_NN1 model_NN1 design_NN1 elements_NN2 and_CC other_JJ operations_NN2 within_II the_AT firm_NN1 ._. 
</s>
<s>
Recent_JJ literature_NN1 suggests_VVZ that_CST a_AT1 firm_NN1 can_VM considerably_RR improve_VVI value_NN1 creation_NN1 by_II business_NN1 models_NN2 that_CST have_VH0 a_AT1 high_JJ degree_NN1 of_IO internal_JJ and_CC external_JJ configurational_JJ fit_NN1 (_( Nenonen_NP1 &Storbacka,;_NULL 2010_MC )_) ._. 
</s>
<s>
By_II this_DD1 is_VBZ meant_VVN the_AT alignment_NN1 of_IO operations_NN2 in_II three_MC fronts_NN2 ._. 
</s>
<s>
First_MD ,_, a_AT1 business_NN1 model_NN1 must_VM be_VBI fit_JJ to_II customers_NN2 needs_VVZ ._. 
</s>
<s>
This_DD1 is_VBZ the_AT most_RGT critical_JJ success_NN1 factor_NN1 for_IF any_DD business_NN1 model_NN1 and_CC in_II some_DD firms_NN2 might_VM bring_VVI in_RP the_AT need_NN1 for_IF managing_VVG several_DA2 ,_, sometimes_RT even_RR conflicting_JJ business_NN1 models_NN2 ._. 
</s>
<s>
If_CS the_AT needs_NN2 of_IO business_NN1 segments_NN2 or_CC customer_NN1 portfolios_NN2 are_VBR very_RG different_JJ then_RT it_PPH1 is_VBZ viable_JJ to_TO have_VHI separate_JJ business_NN1 models_NN2 to_TO meet_VVI those_DD2 needs_NN2 ._. 
</s>
<s>
This_DD1 is_VBZ critical_JJ ,_, because_CS a_AT1 business_NN1 model_NN1 has_VHZ no_AT use_NN1 if_CS it_PPH1 is_VBZ not_XX aligned_VVN according_II21 to_II22 the_AT customers_NN2 needs_VVZ ._. 
</s>
<s>
Secondly_RR ,_, the_AT company_NN1 must_VM ensure_VVI a_AT1 fit_JJ between_II its_APPGE internal_JJ operations_NN2 all_DB the_AT firms_NN2 operations_NN2 should_VM be_VBI aligned_VVN so_RR that_CST processes_NN2 run_VV0 as_RG smoothly_RR and_CC efficiently_RR as_CSA possible_JJ ._. 
</s>
<s>
Additionally_RR ,_, the_AT business_NN1 model_NN1 should_VM be_VBI designed_VVN in_II a_AT1 way_NN1 that_CST there_EX is_VBZ no_AT risk_NN1 for_IF internal_JJ conflicts_NN2 within_II the_AT management_NN1 and_CC implementation_NN1 of_IO it_PPH1 ._. 
</s>
<s>
Third_MD ,_, a_AT1 firm_NN1 must_VM ensure_VVI a_AT1 fit_JJ between_II its_APPGE business_NN1 model_NN1 and_CC the_AT external_JJ environment_NN1 including_II customers_NN2 ,_, partners_NN2 and_CC other_JJ stakeholders_NN2 the_AT firm_NN1 interacts_VVZ with_IW ._. 
</s>
<s>
For_IF the_AT third_MD requirement_NN1 to_TO fulfill_VVI ,_, the_AT two_MC first_MD should_VM be_VBI first_MD secured_VVD :_: external_JJ fit_NN1 requires_VVZ seamless_JJ interplay_NN1 of_IO internal_JJ operations_NN2 ._. 
</s>
<s>
Especially_RR customer_NN1 relationship_NN1 management_NN1 operations_NN2 are_VBR critical_JJ in_II meeting_VVG the_AT customers_NN2 expectations_NN2 ._. 
</s>
<s>
(_( Explore_VV0 ,_, 2010:7_MC )_) The_AT empirical_JJ findings_NN2 of_IO research_NN1 by_II Nenonen_NP1 and_CC Storbacka_NP1 (_( 2010_MC )_) showed_VVD that_CST no_AT business_NN1 model_NN1 design_NN1 is_VBZ superior_JJ per_RR21 se_RR22 ._. 
</s>
<s>
What_DDQ matters_VVZ most_DAT is_VBZ the_AT fit_NN1 of_IO the_AT elements_NN2 to_II each_PPX221 other_PPX222 ,_, to_II the_AT firm_NN1 ,_, and_CC to_II customers_NN2 ._. 
</s>
<s>
Thus_RR they_PPHS2 conclude_VV0 that_DD1 business_NN1 models_NN2 should_VM be_VBI viewed_VVN as_II a_AT1 combination_NN1 of_IO design_NN1 elements_NN2 ,_, which_DDQ are_VBR orchestrated_VVN by_II a_AT1 single_JJ theme_NN1 ._. 
</s>
<s>
The_AT effectiveness_NN1 of_IO the_AT model_NN1 is_VBZ defined_VVN by_II the_AT internal_JJ and_CC external_JJ fit_NN1 of_IO the_AT elements_NN2 ._. 
</s>
<s>
(_( Nenonen_NN1 &Storbacka,;_NULL 2010_MC )_) 4_MC ._. 
</s>
<s>
Empirical_JJ evidence_NN1 from_II a_AT1 case_NN1 organization_NN1 This_DD1 chapter_NN1 reflects_VVZ the_AT theoretical_JJ ground_NN1 and_CC the_AT empirical_JJ evidence_NN1 drawn_VVN from_II a_AT1 case_NN1 firm_NN1 ._. 
</s>
<s>
5_MC ._. 
</s>
<s>
Conclusions_NN2 and_CC implications_NN2 A_ZZ1 conclusion_NN1 of_IO the_AT discussion_NN1 is_VBZ that_CST it_PPH1 is_VBZ not_XX important_JJ which_DDQ framework_NN1 is_VBZ used_VVN or_CC which_DDQ design_VV0 elements_NN2 included_VVN within_II a_AT1 business_NN1 model_NN1 ,_, but_CCB the_AT ability_NN1 of_IO the_AT business_NN1 model_NN1 as_II a_AT1 whole_NN1 to_TO capture_VVI the_AT business_NN1 logic_NN1 and_CC operations_NN2 so_BCL21 as_BCL22 to_TO maximize_VVI the_AT value_NN1 creation_NN1 possibilities_NN2 ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, the_AT design_NN1 elements_NN2 and_CC their_APPGE emphasis_NN1 ,_, on_II the_AT business_NN1 model_NN1 can_VM vary_VVI considerably_RR between_II firms_NN2 ._. 
</s>
<s>
As_CSA mentioned_VVN earlier_RRR ,_, the_AT most_RGT critical_JJ feature_NN1 of_IO a_AT1 functioning_JJ business_NN1 model_NN1 is_VBZ the_AT fit_JJ the_AT model_NN1 must_VM fit_VVI the_AT focal_JJ organization_NN1 and_CC its_APPGE ways_NN2 of_IO conducting_VVG business_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ in_II31 line_II32 with_II33 the_AT argument_NN1 from_II Demil_NP1 &Lecocq;_NULL (_( 2010:243_MC )_) where_CS they_PPHS2 state_VV0 that_CST a_AT1 business_NN1 model_NN1 can_VM only_RR be_VBI said_VVN to_TO be_VBI consistent_JJ when_CS it_PPH1 leads_VVZ to_II sustainable_JJ performance_NN1 and_CC profits_NN2 ._. 
</s>
<s>
A_AT1 well-designed_JJ business_NN1 model_NN1 is_VBZ difficult_JJ to_TO copy_VVI by_II other_JJ firms_NN2 ,_, because_CS it_PPH1 requires_VVZ a_AT1 perfect_JJ fit_NN1 between_II all_DB elements_NN2 and_CC operations_NN2 ._. 
</s>
<s>
Therefore_RR same_DA business_NN1 model_NN1 does_VDZ not_XX suit_VVI several_DA2 firms_NN2 ,_, because_CS it_PPH1 requires_VVZ adjustment_NN1 to_II the_AT current_JJ situation_NN1 and_CC organization.It_NNU can_VM be_VBI concluded_VVN that_CST a_AT1 well-functioning_JJ business_NN1 model_NN1 ,_, i.e._REX one_PN1 that_CST has_VHZ a_AT1 good_JJ fit_NN1 between_II its_APPGE elements_NN2 allows_VVZ a_AT1 firm_NN1 for_IF better_JJR value_NN1 creation_NN1 by_II making_VVG offerings_NN2 that_CST are_VBR appealing_VVG to_II the_AT customer_NN1 and_CC thus_RR securing_VVG revenue_NN1 streams_NN2 ._. 
</s>
<s>
This_DD1 chapter_NN1 is_VBZ finalized_VVN once_RR the_AT empirical_JJ research_NN1 is_VBZ done_VDN and_CC conclusions_NN2 and_CC implications_NN2 from_II can_VM be_VBI drawn_VVN ._. 
</s>
