<s>
ECONOMIC_JJ ANALYSIS_NN1 OF_IO DIGITAL_JJ PIRACY_NN1 :_: A_ZZ1 short_JJ overview_NN1 of_IO the_AT public_JJ good_JJ nature_NN1 of_IO digital_JJ goods_NN2 and_CC DRM_NP1 as_II an_AT1 attempt_NN1 to_TO solve_VVI it_PPH1 1_MC1 Introduction_NN1 The_AT digital_JJ revolution_NN1 and_CC other_JJ technological_JJ breakthroughs_NN2 of_IO the_AT past_JJ several_DA2 decades_NNT2 have_VH0 brought_VVN intellectual_JJ property_NN1 to_II the_AT forefront_NN1 of_IO economic_JJ ,_, social_JJ ,_, and_CC political_JJ interest_NN1 ._. 
</s>
<s>
Digital_JJ technology_NN1 has_VHZ not_XX only_RR permitted_VVN the_AT creation_NN1 of_IO many_DA2 new_JJ goods_NN2 or_CC services_NN2 ,_, but_CCB has_VHZ also_RR dramatically_RR changed_VVN the_AT way_NN1 an_AT1 entire_JJ category_NN1 of_IO goods_NN2 in_II the_AT economy_NN1 are_VBR created_VVN ,_, produced_VVD ,_, distributed_VVN ,_, exchanged_VVN and_CC consumed_VVN ._. 
</s>
<s>
In_RR21 addition_RR22 digital_JJ technology_NN1 has_VHZ allowed_VVN media_NN content_VV0 to_TO be_VBI flawlessly_RR copied_VVN and_CC redistributed_VVN through_RP largely_RR anonymous_JJ peer-to-peer_JJ digital_JJ networks_NN2 ._. 
</s>
<s>
These_DD2 new_JJ challenges_NN2 have_VH0 raised_VVN lots_PN of_IO discussions_NN2 and_CC concerns_VVZ amongst_II different_JJ interest_NN1 groups_NN2 especially_RR amongst_II right_JJ holders_NN2 ._. 
</s>
<s>
Moreover_RR ,_, the_AT growing_JJ importance_NN1 of_IO digital_JJ technology_NN1 has_VHZ spurred_VVN research_NN1 on_II the_AT economic_JJ understandings_NN2 of_IO digital_JJ piracy_NN1 activity_NN1 ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO understand_VVI the_AT economic_JJ analysis_NN1 of_IO digital_JJ piracy_NN1 ,_, one_PN1 must_VM first_MD understand_VVI the_AT nature_NN1 of_IO digital_JJ goods_NN2 ._. 
</s>
<s>
Digital_JJ goods_NN2 are_VBR public_JJ goods_NN2 ;_; the_AT public_JJ good_JJ nature_NN1 of_IO digital_JJ goods_NN2 is_VBZ likely_JJ to_TO lead_VVI to_II a_AT1 free_JJ riding_NN1 behavior_NN1 ,_, i.e._REX digital_JJ piracy_NN1 ,_, of_IO consumers_NN2 ._. 
</s>
<s>
In_II31 response_II32 to_II33 digital_JJ piracy_NN1 ,_, the_AT music_NN1 and_CC movie_NN1 industry_NN1 began_VVD to_TO adopt_VVI technological_JJ measures_NN2 ,_, often_RR referred_VVN as_II21 to_II22 Digital_JJ Rights_NN2 Management_NN1 (_( hereinafter_RR DRM_NP1 )_) ,_, to_TO control_VVI the_AT sale_NN1 and_CC distribution_NN1 of_IO music_NN1 and_CC other_JJ digital_JJ goods_NN2 over_II the_AT internet_NN1 ._. 
</s>
<s>
In_II their_APPGE research_NN1 Rayna_NP1 and_CC Striukova_NP1 suggest_VV0 that_CST DRM_NP1 systems_NN2 based_VVN on_II rivalness_NN1 could_VM be_VBI a_AT1 solution_NN1 for_IF the_AT public_JJ good_JJ problem_NN1 ._. 
</s>
<s>
The_AT basic_JJ problem_NN1 with_IW Rayna_NP1 and_CC Striukova_NP1 's_GE suggestion_NN1 is_VBZ that_CST it_PPH1 is_VBZ practically_RR impossible_JJ to_TO make_VVI digital_JJ goods_NN2 fully_RR or_CC even_RR at_II sufficient_JJ level_JJ rival_NN1 or_CC excludable_JJ ._. 
</s>
<s>
Thus_RR ,_, DRM_NP1 can_VM not_XX entirely_RR or_CC even_RR satisfactorily_RR solve_VV0 the_AT public_JJ good_JJ problem_NN1 of_IO digital_JJ goods_NN2 ,_, which_DDQ means_VVZ that_DD1 alternative_NN1 and_CC more_RGR effective_JJ solutions_NN2 are_VBR needed_VVN in_BCL21 order_BCL22 to_TO suppress_VVI the_AT overall_JJ rate_NN1 of_IO digital_JJ piracy_NN1 ._. 
</s>
<s>
However_RR ,_, the_AT intention_NN1 of_IO this_DD1 paper_NN1 is_VBZ not_XX to_TO propose_VVI any_DD new_JJ ways_NN2 or_CC ideas_NN2 to_TO reduce_VVI the_AT overall_JJ rate_NN1 of_IO digital_JJ piracy_NN1 ,_, but_CCB rather_RR show_VV0 that_CST DRM_NP1 does_VDZ not_XX solve_VVI the_AT public_JJ good_JJ problem_NN1 of_IO digital_JJ goods_NN2 ,_, and_CC the_AT same_DA applies_VVZ to_II the_AT suggestion_NN1 that_CST Rayna_NP1 and_CC Striukova_NP1 presents_VVZ ._. 
</s>
<s>
The_AT progression_NN1 of_IO this_DD1 study_NN1 is_VBZ as_CSA follows_VVZ :_: the_AT introduction_NN1 chapter_NN1 is_VBZ followed_VVN by_II a_AT1 concise_JJ second_MD chapter_NN1 (_( 2_MC Economic_JJ analysis_NN1 of_IO digital_JJ piracy_NN1 )_) where_RRQ the_AT purpose_NN1 is_VBZ to_TO present_VVI shortly_RR a_AT1 relevant_JJ background_NN1 for_IF this_DD1 study_NN1 (_( 2.1_MC Background_NN1 )_) ,_, discuss_VV0 the_AT public_JJ good_JJ characteristics_NN2 of_IO digital_JJ goods_NN2 (_( 2.2_MC Public_JJ good_JJ character_NN1 of_IO digital_JJ goods_NN2 )_) ,_, and_CC DRM_NP1 as_II a_AT1 solution_NN1 to_II this_DD1 problem_NN1 (_( 2.3_MC DRM_NP1 as_II an_AT1 attempt_NN1 to_TO solve_VVI the_AT public_JJ good_JJ problem_NN1 )_) ._. 
</s>
<s>
The_AT last_MD chapter_NN1 (_( 3_MC Conclusion_NN1 )_) contains_VVZ a_AT1 prcis_NN1 of_IO the_AT subject_NN1 matter._NNU 2_MC Economic_JJ analysis_NN1 of_IO digital_JJ piracy_NN1 2.1_MC Background_NN1 Although_CS it_PPH1 is_VBZ true_JJ that_CST piracy_NN1 ,_, in_II the_AT form_NN1 of_IO copies_NN2 of_IO vinyl_NN1 discs_NN2 ,_, audio_JJ and_CC video_NN1 tapes_NN2 ,_, photocopies_NN2 of_IO books_NN2 etc._RA ,_, has_VHZ existed_VVN long_RR before_II the_AT advent_NN1 of_IO digital_JJ goods_NN2 ,_, the_AT piracy_NN1 of_IO the_AT pre-digital_JJ era_NN1 was_VBDZ different_JJ and_CC never_RR reached_VVD the_AT extent_NN1 of_IO digital_JJ piracy_NN1 ._. 
</s>
<s>
Earlier_RRR an_AT1 infringer_NN1 who_PNQS wanted_VVD to_TO distribute_VVI or_CC reproduce_VVI counterfeit_JJ copies_NN2 of_IO movies_NN2 ,_, music_NN1 or_CC computer_NN1 programs_NN2 needed_VVD the_AT same_DA sort_NN1 of_IO production_NN1 and_CC distribution_NN1 facilities_NN2 that_CST the_AT copyright_NN1 owner_NN1 did_VDD ._. 
</s>
<s>
Thus_RR ,_, it_PPH1 is_VBZ clear_JJ that_CST end-user_NN1 copies_NN2 were_VBDR not_XX a_AT1 serious_JJ threat_NN1 to_II a_AT1 copyright_NN1 owner_NN1 's_GE sales_NN during_II the_AT twentieth_MD century_NNT1 ._. 
</s>
<s>
Actually_RR ,_, end-_JJ user_NN1 copies_NN2 were_VBDR often_RR made_VVN for_IF the_AT copier_NN1 's_GE own_DA personal_JJ use_NN1 ,_, but_CCB not_XX to_TO substitute_VVI the_AT lawful_JJ copies_NN2 ._. 
</s>
<s>
Moreover_RR ,_, these_DD2 copies_NN2 did_VDD not_XX usually_RR spread_VVI outside_II the_AT personal_JJ use_NN1 zone_NN1 :_: nowadays_RT just_RR one_MC1 original_JJ digital_JJ unit_NN1 is_VBZ sufficient_JJ to_TO start_VVI an_AT1 infinite_JJ stream_NN1 of_IO absolutely_RR identical_JJ copies_NN2 ._. 
</s>
<s>
These_DD2 changes_NN2 has_VHZ led_VVN to_II a_AT1 situation_NN1 where_RRQ right_JJ holders_NN2 are_VBR genuinely_RR worried_VVN about_II the_AT consequences_NN2 especially_RR economic_JJ consequences_NN2 that_CST digital_JJ piracy_NN1 may_VM cause_VVI ._. 
</s>
<s>
It_PPH1 is_VBZ generally_RR accepted_VVN that_CST counterfeiting_VVG and_CC piracy_NN1 are_VBR global_JJ phenomena_NN2 with_IW serious_JJ economic_JJ and_CC social_JJ consequences_NN2 not_XX only_RR in_II Europe_NP1 but_CCB around_II the_AT world_NN1 ._. 
</s>
<s>
Digital_JJ technology_NN1 has_VHZ caused_VVN a_AT1 drastic_JJ decrease_NN1 in_II reproduction_NN1 costs_NN2 and_CC distribution_NN1 costs_NN2 ._. 
</s>
<s>
This_DD1 again_RT is_VBZ closely_RR linked_VVN to_II end-user_NN1 piracy_NN1 activity_NN1 ._. 
</s>
<s>
Nowadays_RT ,_, end-user_NN1 piracy_NN1 is_VBZ almost_RR entirely_RR related_VVN to_II digital_JJ goods_NN2 ._. 
</s>
<s>
The_AT growing_JJ end-user_NN1 digital_JJ piracy_NN1 activity_NN1 needs_VVZ to_TO be_VBI addressed_VVN in_II the_AT right_JJ way_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ not_XX acceptable_JJ to_TO allow_VVI free-riding_JJ by_II end-users_NN2 ,_, but_CCB on_II the_AT contrary_NN1 not_XX every_AT1 small_JJ infringement_NN1 should_VM be_VBI punishable_JJ either_RR ._. 
</s>
<s>
Trying_VVG to_TO find_VVI the_AT right_JJ balance_NN1 in_II this_DD1 environment_NN1 has_VHZ caused_VVN lots_PN of_IO concerns_NN2 for_IF legislators_NN2 ,_, and_CC there_RL also_RR have_VH0 been_VBN active_JJ discussions_NN2 about_II how_RGQ far_RR the_AT protection_NN1 of_IO copyright_NN1 and_CC related_JJ rights_NN2 can_VM be_VBI extended_VVN ._. 
</s>
<s>
If_CS the_AT copyright_NN1 protection_NN1 is_VBZ not_XX sufficient_JJ or_CC at_II the_AT right_JJ level_NN1 it_PPH1 may_VM lead_VVI to_II the_AT scarcity_NN1 of_IO incentives_NN2 ._. 
</s>
<s>
Incentives_NN2 are_VBR essential_JJ in_II promoting_VVG future_JJ innovation_NN1 ._. 
</s>
<s>
If_CS the_AT protection_NN1 of_IO copyright_NN1 is_VBZ too_RG high_JJ or_CC too_RG strict_JJ ,_, it_PPH1 can_VM cause_VVI problems_NN2 from_II the_AT access_NN1 point_NN1 of_IO view_NN1 ._. 
</s>
<s>
Why_RRQ there_EX has_VHZ to_TO be_VBI public_NN1 access_NN1 to_II innovations_NN2 ?_? 
</s>
<s>
First_MD of_IO all_DB ,_, we_PPIS2 have_VH0 to_TO encourage_VVI future_JJ innovation_NN1 by_II competitors_NN2 and_CC thus_RR promote_VV0 greater_JJR competition_NN1 ,_, and_CC secondly_RR we_PPIS2 have_VH0 to_TO enhance_VVI consumer_NN1 welfare_NN1 ._. 
</s>
<s>
The_AT challenge_NN1 here_RL is_VBZ to_TO find_VVI the_AT right_JJ balance_NN1 between_II incentives_NN2 and_CC access_NN1 ._. 
</s>
<s>
If_CS the_AT balancing_NN1 is_VBZ unsuccessful_JJ it_PPH1 can_VM cause_VVI welfare_NN1 loss_NN1 (_( no_AT innovation_NN1 ,_, no_AT consumer_NN1 welfare_NN1 ,_, and_CC no_AT economic_JJ growth_NN1 )_) ._. 
</s>
<s>
This_DD1 again_RT is_VBZ closely_RR linked_VVN to_II the_AT problem_NN1 of_IO public_JJ goods_NN2 ._. 
</s>
<s>
Public_JJ good_JJ characteristic_NN1 of_IO innovation_NN1 provides_VVZ an_AT1 important_JJ economic_JJ rationale_NN1 for_IF intellectual_JJ property_NN1 rights_NN2 (_( hereinafter_RR IPRs_NN2 )_) ._. 
</s>
<s>
IPRs_NN2 are_VBR seen_VVN as_II a_AT1 solution_NN1 for_IF the_AT public_JJ good_JJ problem_NN1 :_: IPRs_NN2 provides_VVZ legal_JJ control_NN1 over_II reproduction_NN1 which_DDQ again_RT creates_VVZ incentive_NN1 for_IF innovation_NN1 while_CS facilitating_VVG limited_JJ public_NN1 access.13_FO 2.2_MC Public_JJ good_JJ character_NN1 of_IO digital_JJ goods_NN2 Public_JJ goods_NN2 are_VBR defined_VVN as_CSA goods_NN2 that_CST are_VBR both_RR non-rival_JJ in_II consumption_NN1 and_CC non-_JJ excludable_JJ ._. 
</s>
<s>
Non-rivalrous_JJ means_NN that_CST use_VV0 by_II one_MC1 person_NN1 does_VDZ not_XX prevent_VVI others_NN2 from_II using_VVG the_AT same_DA information_NN1 ._. 
</s>
<s>
In_II its_APPGE natural_JJ state_NN1 ,_, knowledge_NN1 is_VBZ also_RR non-excludable_JJ ._. 
</s>
<s>
That_REX21 is_REX22 ,_, even_CS21 if_CS22 someone_PN1 claims_VVZ to_TO own_VVI the_AT knowledge_NN1 ,_, it_PPH1 is_VBZ difficult_JJ to_TO exclude_VVI others_NN2 from_II using_VVG it_PPH1 ._. 
</s>
<s>
The_AT principal_JJ objectives_NN2 of_IO intellectual_JJ property_NN1 law_NN1 are_VBR the_AT promotion_NN1 and_CC protection_NN1 of_IO new_JJ and_CC improved_JJ works_NN ._. 
</s>
<s>
Thus_RR ,_, intellectual_JJ property_NN1 law_NN1 is_VBZ an_AT1 attempt_NN1 to_TO solve_VVI the_AT public_JJ good_JJ problem_NN1 by_II legal_JJ means_NN ;_; it_PPH1 grants_VVZ exclusive_JJ use_NN1 of_IO the_AT protected_JJ knowledge_NN1 or_CC creative_JJ work_NN1 to_II the_AT creator_NN1 ._. 
</s>
<s>
Digital_JJ products_NN2 exhibit_VV0 the_AT fundamental_JJ characteristics_NN2 of_IO a_AT1 public_JJ good_JJ ,_, or_CC actually_RR they_PPHS2 have_VH0 a_AT1 tendency_NN1 to_TO behave_VVI as_RG public_JJ goods_NN2 ._. 
</s>
<s>
Since_CS digital_JJ goods_NN2 are_VBR replicable_JJ they_PPHS2 are_VBR non-rival_JJ (_( consumers_NN2 can_VM make_VVI copies_NN2 of_IO digital_JJ goods_NN2 and_CC thus_RR many_DA2 consumers_NN2 can_VM enjoy_VVI the_AT same_DA unit_NN1 of_IO digital_JJ goods_NN2 at_II the_AT same_DA time_NNT1 )_) and_CC since_CS they_PPHS2 are_VBR non-rival_JJ ,_, they_PPHS2 are_VBR indirectly_RR non-excludable_JJ (_( producers_NN2 are_VBR able_JK to_TO exclude_VVI consumers_NN2 directly_RR but_CCB can_VM not_XX prevent_VVI consumers_NN2 from_II copying_VVG the_AT good_JJ from_II other_JJ consumers_NN2 )_) ._. 
</s>
<s>
As_II a_AT1 consequence_NN1 ,_, as_CSA digital_JJ goods_NN2 spread_VVN among_II the_AT population_NN1 of_IO consumers_NN2 they_PPHS2 virtually_RR become_VV0 fully_RR non-excludable_JJ ,_, thereby_RR giving_VVG them_PPHO2 the_AT same_DA economic_JJ characteristics_NN2 as_CSA public_JJ goods_NN2 ._. 
</s>
<s>
Music_NN1 ,_, games_NN2 ,_, movies_NN2 and_CC other_JJ digital_JJ products_NN2 are_VBR information_NN1 and_CC digital_JJ goods_NN2 ._. 
</s>
<s>
These_DD2 digital_JJ goods_NN2 are_VBR expensive_JJ to_TO produce_VVI for_IF the_AT first_MD copy_NN1 (_( high_JJ fixed_JJ costs_NN2 )_) ,_, and_CC inexpensive_JJ to_TO reproduce_VVI and_CC distribute_VVI for_IF subsequent_JJ copies_NN2 (_( near_II zero_MC variable_JJ costs_NN2 )_) ._. 
</s>
<s>
The_AT digital_JJ nature_NN1 of_IO these_DD2 goods_NN2 means_VVZ that_CST they_PPHS2 are_VBR replicable_JJ and_CC they_PPHS2 can_VM be_VBI infinitely_RR copied_VVN without_IW any_DD loss_NN1 of_IO quality_NN1 or_CC information_NN1 ._. 
</s>
<s>
The_AT public_JJ nature_NN1 of_IO digital_JJ goods_NN2 is_VBZ likely_JJ to_TO lead_VVI to_II a_AT1 free_JJ riding_NN1 behavior_NN1 ,_, i.e._REX piracy_NN1 ,_, of_IO consumers_NN2 :_: an_AT1 individual_NN1 consumes_VVZ a_AT1 public_JJ good_JJ without_IW actually_RR paying_VVG for_IF it_PPH1 ._. 
</s>
<s>
The_AT inability_NN1 of_IO firms_NN2 to_TO exclude_VVI consumers_NN2 leads_VVZ to_II a_AT1 wide_JJ piracy_NN1 phenomenon_NN1 and_CC ,_, thus_RR ,_, undermines_VVZ their_APPGE ability_NN1 to_TO make_VVI profits_NN2 and_CC recover_VVI the_AT initial_JJ fixed_JJ cost_NN1 of_IO production_NN1 ._. 
</s>
<s>
As_II the_AT costs_NN2 of_IO producing_VVG and_CC distributing_VVG copies_NN2 approach_VV0 zero_MC ,_, the_AT public_JJ goods_NN2 problem_NN1 gets_VVZ worse_JJR ,_, because_CS the_AT ratio_NN1 of_IO the_AT cost_NN1 of_IO creation_NN1 to_II the_AT cost_NN1 of_IO imitation_NN1 approaches_VVZ infinity_NN1 ._. 
</s>
<s>
Further_RRR ,_, as_CSA the_AT cost_NN1 of_IO producing_VVG and_CC disseminating_VVG copies_NN2 approaches_VVZ zero_MC ,_, the_AT sharp_JJ division_NN1 between_II professional_JJ counterfeiters_NN2 and_CC end-user_NN1 copiers_NN2 breaks_VVZ down_RP ._. 
</s>
<s>
Anyone_PN1 can_VM give_VVI copies_NN2 of_IO software_NN1 or_CC music_NN1 to_II others_NN2 on_II the_AT Internet_NN1 in_II a_AT1 variety_NN1 of_IO ways_NN2 and_CC it_PPH1 costs_VVZ virtually_RR nothing_PN1 to_TO do_VDI so_RR ._. 
</s>
<s>
Shortly_RR it_PPH1 can_VM be_VBI said_VVN that_CST the_AT fact_NN1 that_CST digital_JJ goods_NN2 are_VBR public_JJ goods_NN2 bears_VVZ important_JJ consequences_NN2 ._. 
</s>
<s>
The_AT considerably_RR large_JJ number_NN1 of_IO these_DD2 goods_NN2 in_II the_AT economy_NN1 ,_, as_II31 well_II32 as_II33 their_APPGE ever_RR growing_JJ importance_NN1 ,_, greatly_RR affects_VVZ the_AT traditional_JJ balance_NN1 between_II public_JJ goods_NN2 and_CC private_JJ goods_NN2 in_II the_AT economy_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ obvious_JJ that_CST right_JJ holders_NN2 and_CC industry_NN1 are_VBR willing_JJ to_TO do_VDI almost_RR anything_PN1 in_BCL21 order_BCL22 to_TO change_VVI the_AT public_JJ good_JJ nature_NN1 of_IO digital_JJ goods_NN2 in_II other_JJ words_NN2 turn_VV0 them_PPHO2 into_II private_JJ goods_NN2 and_CC thus_RR hoping_VVG that_CST the_AT overall_JJ rate_NN1 of_IO digital_JJ piracy_NN1 reduces._NNU 2.3_MC DRM_NP1 as_II an_AT1 attempt_NN1 to_TO solve_VVI the_AT public_JJ good_JJ problem_NN1 (_( approx._RR 2-3_MCMC pages_NN2 )_) DRM_NP1 explaining_VVG How_RRQ DRM_NP1 is_VBZ linked_VVN to_II digital_JJ goods_NN2 and_CC digital_JJ piracy_NN1 ?_? 
</s>
<s>
Will_VM it_PPH1 stop_VVI piracy_NN1 ?_? 
</s>
<s>
Can_VM it_PPH1 change_VVI the_AT nature_NN1 of_IO digital_JJ goods_NN2 (_( from_II public_NN1 to_II private_NN1 )_) Rayna_NP1 and_CC Striukova_NP1 DRM_NP1 systems_NN2 based_VVN on_II rivalness_NN1 could_VM be_VBI a_AT1 solution_NN1 for_IF the_AT public_JJ good_JJ problem_NN1 The_AT problem_NN1 generally_RR (_( main_JJ analysis_NN1 )_) The_AT problem_NN1 with_IW their_APPGE suggestion_NN1 (_( main_JJ analysis_NN1 )_) hacking_NN1 removes_VVZ the_AT private_JJ good_JJ characteristics_NN2 (_( main_JJ analysis_NN1 )_) other_JJ problems_NN2 that_CST have_VH0 been_VBN linked_VVN to_II DRM_NP1 3_MC Conclusion_NN1 (_( approx._RR 1_MC1 page_NN1 )_) 
</s>
