<s>
Organizational_JJ Structure_NN1 change_NN1 with_IW Cloud_NN1 Computing_NN1 SaaS_NP2 I._NP1 INTRODUCTION_NN1 INCE_VV0 the_AT appearance_NN1 of_IO the_AT Internet_NN1 ,_, remote_JJ web_NN1 access_NN1 from_II any_DD place_NN1 and_CC at_II any_DD time_NNT1 has_VHZ given_VVN the_AT possibility_NN1 for_IF organizations_NN2 to_TO use_VVI different_JJ resources_NN2 outside_II its_APPGE premises_NN2 ._. 
</s>
<s>
This_DD1 includes_VVZ storage_NN1 of_IO data_NN in_II remote_JJ infrastructure_NN1 or_CC servers_NN2 ,_, applications_NN2 built_VVN on_II platforms_NN2 supplied_VVN by_II third_MD parties_NN2 ,_, and_CC software_NN1 which_DDQ is_VBZ simply_RR accessible_JJ though_CS a_AT1 web_NN1 browser_NN1 without_IW the_AT need_NN1 to_TO purchase_VVI any_DD licenses_NN2 ._. 
</s>
<s>
These_DD2 remote_JJ resources_NN2 ,_, accessible_JJ through_II the_AT Internet_NN1 ,_, are_VBR called_VVN Cloud_NN1 Computing_NN1 ._. 
</s>
<s>
Cloud_NN1 computing_NN1 enables_VVZ the_AT outsourcing_NN1 of_IO most_DAT of_IO the_AT organizational_JJ IT_NN1 infrastructure_NN1 to_II third_MD parties_NN2 ,_, who_PNQS offer_VV0 Software_NN1 (_( SaaS_NP2 )_) ,_, Platform_NN1 (_( PaaS_NP2 )_) ,_, and_CC Infrastructure_NN1 (_( IaaS_NP2 )_) as_II a_AT1 Service_NN1 ._. 
</s>
<s>
Cloud_NN1 Computing_NN1 provides_VVZ the_AT possibility_NN1 to_TO delegate_VVI the_AT responsibility_NN1 of_IO most_DAT of_IO the_AT IT_NN1 function_NN1 of_IO the_AT organization_NN1 in_II exchange_NN1 of_IO a_AT1 subscription_NN1 or_CC pay_VV0 as_CSA you_PPY go_VV0 fee_NN1 ._. 
</s>
<s>
Thus_RR ,_, Cloud_NN1 computing_NN1 is_VBZ characterized_VVN by_II scalability_NN1 ,_, new_JJ IT_NN1 paradigm_NN1 ,_, measured_VVD service_NN1 ,_, on-demand_JJ self-service_JJ ,_, availability_NN1 ,_, reliability_NN1 and_CC elasticity_NN1 (_( Gartner_NP1 ,_, 2008_MC ;_; Duncan_NP1 D._NP1 ,_, Xingchen_NP1 C._NP1 ,_, Vecchiola_NP1 C._NP1 and_CC Buyya_NP1 R._NP1 ,_, 2009_MC )_) ._. 
</s>
<s>
With_IW this_DD1 possibility_NN1 ,_, organizations_NN2 perceive_VV0 the_AT opportunity_NN1 to_TO decrease_VVI their_APPGE capital_NN1 and_CC human_JJ investment_NN1 in_II IT_NN1 resources_NN2 ._. 
</s>
<s>
The_AT opportunity_NN1 for_IF organizations_NN2 to_TO outsource_VVI most_DAT of_IO their_APPGE IT_NN1 responsibilities_NN2 is_VBZ a_AT1 paradigm_NN1 shift_VV0 in_II the_AT way_NN1 IT_NN1 business_NN1 has_VHZ been_VBN done_VDN ._. 
</s>
<s>
Thus_RR ,_, when_CS adopting_VVG Software_NN1 as_II a_AT1 Service_NN1 in_II the_AT Cloud_NN1 ,_, organizations_NN2 just_RR need_VV0 to_TO ensure_VVI that_CST the_AT cloud_NN1 provider_NN1 delivers_VVZ what_DDQ has_VHZ been_VBN agreed_VVN upon_II in_II the_AT Service_NN1 Level_NN1 Agreement_NN1 (_( SLA_NP1 )_) ._. 
</s>
<s>
Besides_II the_AT mentioned_VVN opportunities_NN2 ,_, organizations_NN2 now_RT face_VV0 the_AT challenge_NN1 of_IO restructuring_VVG their_APPGE IT_NN1 structure_NN1 linked_VVN to_II the_AT business_NN1 strategy_NN1 ._. 
</s>
<s>
Some_DD of_IO the_AT challenges_NN2 are_VBR :_: What_DDQ happens_VVZ to_II the_AT previous_JJ IT_NN1 structure_NN1 in_II the_AT enterprise_NN1 ?_? 
</s>
<s>
How_RRQ do_VD0 Organizations_NN2 evolve_VVI and_CC change_VVI to_TO adapt_VVI to_II this_DD1 new_JJ type_NN1 of_IO IT_NN1 offer_NN1 ?_? 
</s>
<s>
Do_VD0 existing_JJ positions_NN2 disappear_VV0 ?_? 
</s>
<s>
Does_VDZ the_AT Enterprise_NN1 needs_VVZ to_TO restructure_VVI its_APPGE IT_NN1 department_NN1 ?_? 
</s>
<s>
Are_VBR new_JJ positions_NN2 created_VVN to_TO deal_VVI with_IW risk_NN1 assessment_NN1 and_CC management_NN1 of_IO Cloud_NN1 Computing_NN1 solutions_NN2 ?_? 
</s>
<s>
The_AT aim_NN1 of_IO this_DD1 study_NN1 is_VBZ to_TO answer_VVI these_DD2 questions_NN2 ,_, specifically_RR :_: How_RRQ are_VBR enterprises_NN2 changing_VVG their_APPGE structure_NN1 when_CS adopting_JJ SaaS_NP2 in_II the_AT Cloud_NN1 ?_? 
</s>
<s>
Current_JJ research_NN1 lacks_VVZ a_AT1 more_RGR holistic_JJ view_NN1 of_IO cloud_NN1 customers_NN2 IT_NN1 organizational_JJ structure_NN1 and_CC IT_NN1 Governance_NN1 transformation_NN1 ._. 
</s>
<s>
No_AT previous_JJ research_NN1 has_VHZ been_VBN found_VVN when_CS it_PPH1 comes_VVZ to_II human_JJ resources_NN2 and_CC internal_JJ policies_NN2 change_VV0 ._. 
</s>
<s>
This_DD1 is_VBZ supported_VVN by_II Hosseini_NP1 A._NP1 ,_, Sommerville_NP1 I._NP1 and_CC Sriram_NP1 I._NP1 (_( 2010_MC )_) ,_, who_PNQS present_VV0 a_AT1 list_NN1 of_IO Research_NN1 challenges_NN2 for_IF enterprise_NN1 cloud_NN1 computing_NN1 ._. 
</s>
<s>
One_MC1 of_IO the_AT issues_NN2 is_VBZ :_: the_AT authority_NN1 of_IO the_AT IT_NN1 where_CS enterprise_NN1 users_NN2 will_VM have_VHI more_DAR political_JJ influence_NN1 ,_, and_CC the_AT IT_NN1 department_NN1 's_GE role_NN1 will_VM change_VVI from_II provider_NN1 to_II certifier_NN1 ,_, consultant_NN1 and_CC arbitrator_NN1 (_( Hosseini_NP1 A._NP1 et_RA21 al._RA22 ,_, 2010_MC ,_, p.3_FO )_) ._. 
</s>
<s>
Thus_RR ,_, an_AT1 exploratory_JJ study_NN1 is_VBZ proposed_VVN to_TO answer_VVI the_AT questions_NN2 presented_VVD ._. 
</s>
<s>
A_AT1 Case_NN1 study_NN1 ,_, with_IW in-depth_JJ unstructured_JJ interviews_NN2 ,_, is_VBZ considered_VVN the_AT best_JJT method_NN1 to_TO retrieve_VVI information_NN1 about_II the_AT changes_NN2 ._. 
</s>
<s>
The_AT changes_NN2 identified_VVN help_VV0 to_TO observe_VVI the_AT current_JJ evolution_NN1 in_II the_AT case_NN1 company_NN1 and_CC their_APPGE lessons_NN2 learned_VVD ._. 
</s>
<s>
The_AT successful_JJ and_CC unsuccessful_JJ approaches_NN2 identified_VVN help_VV0 to_TO create_VVI an_AT1 understanding_NN1 of_IO different_JJ trends_NN2 ._. 
</s>
<s>
Current_JJ and_CC potential_JJ cloud_NN1 customers_NN2 are_VBR the_AT main_JJ audience_NN1 of_IO this_DD1 study_NN1 ,_, which_DDQ can_VM help_VVI to_TO analyze_VVI the_AT difficulties_NN2 and_CC opportunities_NN2 for_IF IT_NN1 governance_NN1 and_CC IT_NN1 infrastructure_NN1 changes_NN2 in_II organizations_NN2 ._. 
</s>
<s>
Furthermore_RR ,_, it_PPH1 enables_VVZ the_AT development_NN1 of_IO new_JJ tools_NN2 and_CC techniques_NN2 to_TO facilitate_VVI the_AT migration_NN1 to_II Cloud_NN1 Computing_NN1 ._. 
</s>
<s>
Finally_RR ,_, Cloud_NN1 Computing_NN1 is_VBZ constantly_RR evolving_VVG so_RR organizations_NN2 need_VV0 to_TO always_RR keep_VVI themselves_PPX2 up_JJ31 to_JJ32 date_JJ33 about_II the_AT different_JJ variables_NN2 that_CST allow_VV0 for_IF a_AT1 successful_JJ migration_NN1 linked_VVN to_II their_APPGE business_NN1 model_NN1 and_CC strategy_NN1 ._. 
</s>
<s>
The_AT current_JJ paper_NN1 is_VBZ structured_VVN as_CSA follows_VVZ ._. 
</s>
<s>
The_AT next_MD section_NN1 describes_VVZ Cloud_NN1 Computing_NN1 ,_, followed_VVN by_II the_AT current_JJ research_NN1 background_NN1 on_II why_RRQ organizations_NN2 need_VV0 to_TO adapt_VVI internally_RR to_II these_DD2 new_JJ technology_NN1 adoption_NN1 ._. 
</s>
<s>
Then_RT ,_, a_AT1 deep_JJ discussion_NN1 is_VBZ presented_VVN related_VVN to_II what_DDQ kind_NN1 of_IO changes_NN2 are_VBR needed_VVN and_CC why_RRQ ._. 
</s>
<s>
This_DD1 is_VBZ after_CS linked_VVN to_II the_AT proposed_JJ research_NN1 framework_NN1 to_TO use_VVI in_II this_DD1 study_NN1 ._. 
</s>
<s>
Finally_RR ,_, the_AT empirical_JJ methodology_NN1 is_VBZ explained_VVN and_CC presented_VVN ,_, which_DDQ is_VBZ followed_VVN by_II the_AT analysis_NN1 of_IO the_AT main_JJ results_NN2 ._. 
</s>
<s>
Conclusions_NN2 are_VBR then_RT presented_VVN based_VVN on_II the_AT main_JJ findings_NN2 ._. 
</s>
<s>
II_MC ._. 
</s>
<s>
CLOUD_NN1 COMPUTING_NN1 Cloud_NN1 computing_NN1 aims_VVZ at_II providing_VVG users_NN2 and_CC businesses_NN2 a_AT1 whole_JJ package_NN1 of_IO application_NN1 systems_NN2 through_II the_AT web_NN1 ,_, which_DDQ can_VM be_VBI either_RR as_II a_AT1 service_NN1 ,_, a_AT1 platform_NN1 or_CC an_AT1 infrastructure_NN1 ._. 
</s>
<s>
Organizations_NN2 do_VD0 nt_XX have_VHI the_AT need_NN1 to_TO store_VVI their_APPGE data_NN on_II company_NN1 specific_JJ location_NN1 servers_NN2 ,_, nor_CC to_TO manage_VVI it_PPH1 or_CC even_RR to_TO own_VVI software_NN1 applications_NN2 ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, the_AT organizations_NN2 will_VM be_VBI completely_RR dependent_JJ on_II the_AT cloud_NN1 computing_NN1 provider_NN1 for_IF data_NN access_NN1 ,_, data_NN analysis_NN1 and_CC to_TO run_VVI the_AT whole_JJ business_NN1 applications_NN2 ._. 
</s>
<s>
It_PPH1 will_VM ,_, however_RR ,_, provide_VVI access_NN1 anytime_NNT1 anywhere_RL as_CS31 long_CS32 as_CS33 there_EX is_VBZ internet_NN1 connection_NN1 ,_, and_CC a_AT1 service_NN1 agreement_NN1 settled_VVN by_II the_AT organization_NN1 and_CC the_AT cloud_NN1 computing_NN1 service_NN1 provider_NN1 ._. 
</s>
<s>
There_EX are_VBR several_DA2 definitions_NN2 given_VVN to_II Cloud_NN1 Computing_NN1 either_RR from_II technology_NN1 ,_, advisory_JJ and_CC market_VV0 research_NN1 companies_NN2 ,_, to_II IT_NN1 Companies_NN2 ,_, and_CC Regulatory_JJ Institutes_NN2 and_CC National_JJ Organizations_NN2 ._. 
</s>
<s>
Some_DD of_IO the_AT definitions_NN2 are_VBR presented_VVN in_II Table_NN1 1_MC1 :_: &lsqb;_( Table_NN1 &rsqb;_) It_PPH1 can_VM be_VBI observed_VVN that_DD1 Cloud_NN1 Computing_NN1 is_VBZ a_AT1 recent_JJ concept_NN1 in_II development_NN1 ,_, where_CS research_NN1 companies_NN2 were_VBDR the_AT first_MD ones_NN2 approaching_VVG this_DD1 new_JJ phenomenon_NN1 or_CC paradigm_NN1 on_II the_AT way_NN1 IT_NN1 business_NN1 will_VM be_VBI conducted_VVN on_II the_AT future_NN1 ._. 
</s>
<s>
Further_RRR on_RP ,_, regulatory_JJ entities_NN2 found_VVD the_AT need_NN1 to_TO define_VVI this_DD1 concept_NN1 and_CC referrer_NN1 the_AT potential_JJ opportunities_NN2 that_CST it_PPH1 can_VM bring_VVI on_II the_AT markets_NN2 and_CC economy_NN1 ._. 
</s>
<s>
All_DB the_AT definitions_NN2 presented_VVN agree_VV0 on_II common_JJ characteristics_NN2 such_II21 as_II22 :_: scalability_NN1 ,_, new_JJ IT_NN1 paradigm_NN1 ,_, measured_VVD service_NN1 ,_, on-demand_JJ self-service_JJ ,_, availability_NN1 ,_, reliability_NN1 and_CC elasticity_NN1 ._. 
</s>
<s>
Cloud_NN1 computing_NN1 is_VBZ moving_VVG towards_II the_AT stage_NN1 of_IO Rapid_JJ Cloud_NN1 Computing_NN1 Adoption_NN1 ,_, and_CC this_DD1 is_VBZ possible_JJ due_II21 to_II22 several_DA2 Companies_NN2 investment_NN1 in_II IaaS_NP2 that_CST will_VM support_VVI the_AT further_JJR layers_NN2 that_CST will_VM enable_VVI the_AT PaaS_NP2 and_CC SaaS_NP2 ._. 
</s>
<s>
Cloud_NN1 Computing_NN1 Market_NN1 is_VBZ expected_VVN to_TO be_VBI adapted_VVN in_RP to_II marketbased_JJ strategies_NN2 ,_, which_DDQ will_VM shape_VVI the_AT IT_NN1 infrastructure_NN1 of_IO the_AT future_NN1 ,_, especially_RR when_CS the_AT Security_NN1 ,_, control_NN1 and_CC trust_VV0 issues_NN2 are_VBR overcome_VVN (_( Vecchiola_NP1 C._NP1 ,_, Duncan_NP1 D._NP1 ,_, and_CC Buyya_NP1 R._NP1 ,_, 2009_MC )_) ._. 
</s>
<s>
III_MC ._. 
</s>
<s>
WHY_RRQ ORGANIZATIONS_NN2 NEED_VV0 TO_TO ADAPT_VVI INTERNALLY_RR ?_? 
</s>
<s>
Although_CS cloud_NN1 computing_NN1 presents_VVZ many_DA2 benefits_NN2 ,_, it_PPH1 also_RR comes_VVZ with_IW many_DA2 risks_NN2 related_VVN to_II reliability_NN1 ,_, integrity_NN1 ,_, recovery_NN1 ,_, and_CC privacy_NN1 ,_, and_CC an_AT1 evaluation_NN1 of_IO legal_JJ issues_NN2 in_II areas_NN2 such_II21 as_II22 e-discovery_NN1 ,_, regulatory_JJ compliance_NN1 ,_, and_CC auditing_NN1 (_( Brodkin_NP1 J._NP1 ,_, 2008_MC )_) ._. 
</s>
<s>
Of_IO the_AT 3_MC main_JJ categories_NN2 of_IO Cloud_NN1 Computing_NN1 services_NN2 mentioned_VVD :_: SaaS_NP2 ,_, PaaS_NP2 and_CC IaaS_NP2 ,_, SaaS_NP2 is_VBZ considered_VVN the_AT most_RGT risky_JJ ._. 
</s>
<s>
Thus_RR ,_, the_AT focus_NN1 of_IO this_DD1 study_NN1 is_VBZ in_II SaaS_NP2 ._. 
</s>
<s>
With_IW SaaS_NP2 ,_, the_AT Governance_NN1 structure_NN1 of_IO IT_NN1 in_II organizations_NN2 is_VBZ expected_VVN to_TO change_VVI dramatically_RR ._. 
</s>
<s>
The_AT infrastructure_NN1 ,_, platform_NN1 and_CC application_NN1 will_VM no_RR longer_RRR be_VBI hosted_VVN under_II the_AT premises_NN2 and_CC in_II direct_JJ control_NN1 of_IO the_AT Cloud_NN1 Customer_NN1 (_( CC_NNU )_) ._. 
</s>
<s>
CC_NP1 will_VM mainly_RR have_VHI access_NN1 to_II the_AT application_NN1 through_II an_AT1 internet_NN1 browser_NN1 ._. 
</s>
<s>
Thus_RR ,_, Cloud_NN1 Provider_NN1 (_( CP_NP1 )_) increases_VVZ his_APPGE control_NN1 while_CS CC_NP1 needs_VVZ to_TO take_VVI the_AT necessary_JJ steps_NN2 to_TO adapt_VVI its_APPGE organizational_JJ structure_NN1 to_II this_DD1 new_JJ emerging_JJ business_NN1 model_NN1 in_II the_AT software_NN1 industry_NN1 (_( Mather_NP1 T._NP1 ,_, Kumaraswamy_NP1 S._NP1 and_CC Latif_NP1 S._NP1 ,_, 2009_MC )_) ._. 
</s>
<s>
The_AT reasons_NN2 why_RRQ many_DA2 organizations_NN2 choose_VV0 to_TO use_VVI SaaS_NP2 are_VBR related_VVN to_II social_JJ influence_NN1 ,_, attitude_NN1 towards_II SaaS_NP2 -_- adoption_NN1 ,_, adoption_NN1 uncertainty_NN1 ,_, and_CC strategic_JJ value_NN1 (_( Benlian_JJ ,_, A._NP1 ,_, Hess_NP1 ,_, T._NP1 ,_, and_CC Buxmann_NP1 ,_, P._NP1 ,_, 2009_MC ,_, p.1_FO )_) ._. 
</s>
<s>
However_RR ,_, when_CS organizations_NN2 are_VBR considering_II SaaS_NP2 ,_, a_AT1 new_JJ business-IT_JJ alignment_NN1 ,_, skills_NN2 ,_, project_NN1 teams_NN2 ,_, policies_NN2 ,_, risk_NN1 management_NN1 and_CC assessment_NN1 teams_NN2 ,_, and_CC compliance_NN1 are_VBR needed_VVN ._. 
</s>
<s>
The_AT risks_NN2 mentioned_VVN can_VM be_VBI reduced_VVN or_CC prevented_VVD if_CS it_PPH1 is_VBZ established_VVN a_AT1 proactive_JJ program_NN1 management_NN1 office_NN1 to_TO implement_VVI industry_NN1 best_JJT practices_NN2 and_CC government_NN1 policies_NN2 in_II the_AT management_NN1 of_IO any_DD program_NN1 (_( Paquette_NP1 S._NP1 ,_, Jaeger_NP1 P._NP1 T._NP1 ,_, Wilson_NP1 S._NP1 C._NP1 ,_, 2010_MC ,_, p._NN1 4_MC )_) Risk_VV0 Management_NN1 program_NN1 focused_VVN on_II cloud_NN1 computing_NN1 is_VBZ an_AT1 essential_JJ part_NN1 of_IO the_AT government_NN1 IT_NN1 environment_NN1 (_( Paquette_NP1 S._NP1 et_RA21 al._RA22 ,_, 2010_MC ,_, p._NN1 1_MC1 )_) ._. 
</s>
<s>
Furthermore_RR ,_, risks_NN2 concerning_II the_AT implementation_NN1 ,_, management_NN1 ,_, and_CC usage_NN1 of_IO cloud_NN1 computing_NN1 need_VV0 an_AT1 adequate_JJ strategy_NN1 to_TO enable_VVI good_JJ administration_NN1 and_CC soften_VVI potential_JJ risks_NN2 ._. 
</s>
<s>
Identifying_VVG the_AT risks_NN2 should_VM be_VBI the_AT first_MD priority_NN1 in_BCL21 order_BCL22 to_TO find_VVI ways_NN2 of_IO preventing_VVG them_PPHO2 or_CC to_TO assess_VVI them_PPHO2 if_CS they_PPHS2 are_VBR inevitable_JJ (_( Paquette_NP1 S._NP1 et_RA21 al._RA22 ,_, 2010_MC )_) ._. 
</s>
<s>
There_EX are_VBR several_DA2 risks_NN2 identified_VVN 3_MC when_RRQ a_AT1 new_JJ technology_NN1 is_VBZ implemented_VVN ,_, such_II21 as_II22 :_: policy_NN1 changes_NN2 ,_, dynamic_JJ applications_NN2 and_CC securing_VVG the_AT dynamic_JJ environment_NN1 (_( Paquette_NP1 S._NP1 et_RA21 al._RA22 ,_, 2010_MC )_) ._. 
</s>
<s>
They_PPHS2 can_VM be_VBI reduced_VVN or_CC prevented_VVD if_CS it_PPH1 is_VBZ established_VVN a_AT1 proactive_JJ program_NN1 management_NN1 office_NN1 to_TO implement_VVI industry_NN1 best_JJT practices_NN2 and_CC government_NN1 policies_NN2 in_II the_AT management_NN1 of_IO any_DD program_NN1 (_( Paquette_NP1 S._NP1 et_RA21 al._RA22 ,_, 2010_MC ,_, p._NN1 4_MC )_) ._. 
</s>
<s>
IT_NN1 governance_NN1 has_VHZ an_AT1 important_JJ role_NN1 on_II the_AT ability_NN1 to_TO identify_VVI ,_, assess_VVI ,_, and_CC mitigate_VVI the_AT risks_NN2 surrounding_VVG the_AT use_NN1 of_IO cloud_NN1 computing_NN1 ._. 
</s>
<s>
This_DD1 happens_VVZ since_CS it_PPH1 focuses_VVZ on_II internal_JJ and_CC external_JJ compliance_NN1 initiatives_NN2 ._. 
</s>
<s>
Thus_RR ,_, it_PPH1 provides_VVZ decision_NN1 making_VVG process_NN1 to_II all_DB stakeholders_NN2 and_CC assignment_NN1 of_IO accountability_NN1 within_II the_AT IT_NN1 organization_NN1 ._. 
</s>
<s>
An_AT1 appropriate_JJ governance_NN1 structure_NN1 can_VM help_VVI to_TO effectively_RR inspect_VVI the_AT risk_NN1 management_NN1 program_NN1 (_( Paquette_NP1 S._NP1 et_RA21 al._RA22 ,_, 2010_MC )_) ._. 
</s>
<s>
IV_MC ._. 
</s>
<s>
ORGANIZATION_NN1 STRUCTURE_NN1 CHANGE_NN1 :_: BUSINESS-IT_JJ ALIGNMENT_NN1 ,_, POLICIES_NN2 ,_, RISK_VV0 MANAGEMENT_NN1 AND_CC ASSESSMENT_NN1 When_CS moving_VVG into_II the_AT cloud_NN1 ,_, an_AT1 important_JJ aspect_NN1 concerns_VVZ the_AT internal_JJ organizational_JJ structure_NN1 of_IO Cloud_NN1 Customer_NN1 (_( CC_NNU )_) ._. 
</s>
<s>
CC_NP1 can_VM no_RR21 longer_RR22 rely_VVI merely_RR on_II its_APPGE implemented_JJ internal_JJ Security_NN1 infrastructure_NN1 ._. 
</s>
<s>
By_II adopting_VVG services_NN2 on_II the_AT cloud_NN1 ,_, especially_RR in_II the_AT case_NN1 of_IO sensitive_JJ data_NN ,_, CC_NP1 not_XX only_RR needs_VVZ to_TO ensure_VVI the_AT Cloud_NN1 Provider_NN1 (_( CP_NP1 )_) has_VHZ in_II place_NN1 the_AT needed_VVN security_NN1 requirements_NN2 according_II21 to_II22 its_APPGE business_NN1 and_CC internal_JJ policies_NN2 needs_VVZ ._. 
</s>
<s>
CC_NP1 needs_VVZ as_RR21 well_RR22 to_TO adapt_VVI its_APPGE existing_JJ organizational_JJ structure_NN1 to_TO allow_VVI security_NN1 and_CC compliance_NN1 in_II place_NN1 by_II monitoring_VVG all_DB the_AT activity_NN1 of_IO the_AT SaaS_NP2 in_II the_AT Cloud_NN1 ._. 
</s>
<s>
Qualify_VV0 of_IO Service_NN1 (_( QoS_NP1 )_) can_VM only_RR exist_VVI if_CSW CC_NP1 develops_VVZ adequate_JJ parameters_NN2 to_TO be_VBI measured_VVN together_RL with_IW CP_NP1 in_II a_AT1 constant_JJ live_JJ monitoring_NN1 plus_II service_NN1 follow_NN121 up_NN122 meetings_NN2 (_( Rittinghouse_NP1 J._NP1 and_CC Ransome_NP1 J._NP1 ,_, 2009_MC )_) ._. 
</s>
<s>
Information_NN1 Security_NN1 department_NN1 in_II organizations_NN2 will_VM move_VVI to_II a_AT1 more_RGR strategic_JJ role_NN1 where_CS IT_NN1 Governance_NN1 main_JJ focus_NN1 will_VM be_VBI related_JJ decisions_NN2 ,_, implementations_NN2 ,_, monitoring_VVG ,_, risk_NN1 management_NN1 and_CC assessment_NN1 ,_, and_CC IT-business_JJ strategic_JJ alignment_NN1 to_TO explore_VVI potential_JJ opportunities_NN2 with_IW the_AT use_NN1 of_IO Cloud_NN1 Computing_NN1 ._. 
</s>
<s>
This_DD1 includes_VVZ Security_NN1 Governance_NN1 where_CS a_AT1 Security_NN1 steering_NN1 committee_NN1 can_VM provide_VVI guidance_NN1 about_II security_NN1 initiatives_NN2 and_CC alignment_NN1 with_IW business_NN1 and_CC IT_NN1 strategies_NN2 ._. 
</s>
<s>
Such_DA change_NN1 is_VBZ indispensable_JJ when_CS starting_VVG to_TO use_VVI applications_NN2 in_II the_AT cloud_NN1 ._. 
</s>
<s>
Roles_NN2 and_CC responsibilities_NN2 related_VVN to_II information_NN1 security_NN1 need_NN1 to_TO be_VBI set_VVN and_CC explained_VVN for_IF efficient_JJ change_NN1 in_II the_AT organization_NN1 (_( Rittinghouse_NP1 J._NP1 and_CC Ransome_NP1 J._NP1 ,_, 2009_MC ,_, p._NN1 165_MC )_) ._. 
</s>
<s>
Other_JJ roles_NN2 are_VBR related_VVN to_II Risk_NN1 Management_NN1 and_CC Risk_VV0 Assessment_NN1 ._. 
</s>
<s>
Risk_VV0 management_NN1 involves_VVZ identification_NN1 ,_, maintenance_NN1 and_CC accountability_NN1 in_II important_JJ areas_NN2 of_IO the_AT organization_NN1 ,_, like_VV0 :_: technology_NN1 assets_NN2 ;_; data_NN and_CC its_APPGE links_NN2 to_II business_NN1 processes_NN2 ,_, applications_NN2 ,_, and_CC data_NN stores_NN2 and_CC information_NN1 assets_NN2 including_II protection_NN1 requirements_NN2 ,_, and_CC custodians_NN2 implement_VV0 confidentiality_NN1 ,_, integrity_NN1 ,_, availability_NN1 ,_, and_CC privacy_NN1 controls_NN2 (_( Rittinghouse_NP1 J._NP1 and_CC Ransome_NP1 J._NP1 ,_, 2009_MC ,_, p._NN1 165_MC )_) ._. 
</s>
<s>
These_DD2 formal_JJ actions_NN2 are_VBR not_XX completed_VVN until_CS proper_JJ descriptions_NN2 of_IO needed_VVN procedures_NN2 to_TO support_VVI the_AT risk_NN1 management_NN1 are_VBR formed_VVN ._. 
</s>
<s>
Risk_VV0 assessment_NN1 enables_VVZ such_DA descriptions_NN2 ,_, allocation_NN1 of_IO resources_NN2 and_CC prioritization_NN1 of_IO actions_NN2 between_II normal_JJ business_NN1 operations_NN2 and_CC the_AT protection_NN1 of_IO information_NN1 ._. 
</s>
<s>
Moreover_RR ,_, it_PPH1 provides_VVZ the_AT identification_NN1 of_IO proper_JJ controls_NN2 that_CST help_VV0 decrease_NN1 security_NN1 risks_NN2 besides_II reviewing_VVG if_CS those_DD2 are_VBR in_II place_NN1 and_CC working_VVG properly_RR ._. 
</s>
<s>
Information_NN1 security_NN1 can_VM then_RT have_VHI a_AT1 link_NN1 between_II the_AT business_NN1 needs_NN2 and_CC internal_JJ policies_NN2 with_IW the_AT proper_JJ allocation_NN1 of_IO resources_NN2 ,_, controls_NN2 ,_, and_CC maintenance_NN1 (_( Rittinghouse_NP1 J._NP1 and_CC Ransome_NP1 J._NP1 ,_, 2009_MC )_) ._. 
</s>
<s>
However_RR ,_, without_IW training_NN1 individuals_NN2 along_II the_AT organization_NN1 ,_, and_CC in_RR21 particular_RR22 direct_JJ users_NN2 and_CC the_AT people_NN involved_JJ in_II the_AT risk_NN1 management_NN1 and_CC risk_NN1 assessment_NN1 ,_, the_AT exposure_NN1 to_TO risk_VVI can_VM increase_VVI due_II21 to_II22 unaware_JJ security_NN1 vulnerabilities_NN2 ._. 
</s>
<s>
Specific_JJ and_CC general_JJ training_NN1 for_IF using_VVG SaaS_NP2 can_VM help_VVI enhance_VVI the_AT right_JJ behaviors_NN2 towards_II information_NN1 security_NN1 and_CC provide_VV0 updated_JJ training_NN1 in_II a_AT1 developing_JJ and_CC changing_JJ environment_NN1 such_II21 as_II22 the_AT cloud_NN1 computing_NN1 (_( Rittinghouse_NP1 J._NP1 and_CC Ransome_NP1 J._NP1 ,_, 2009_MC )_) ._. 
</s>
<s>
Besides_II training_NN1 ,_, a_AT1 cloud_NN1 computing_NN1 security_NN1 team_NN1 should_VM first_MD identify_VVI the_AT information_NN1 security_NN1 and_CC business_NN1 requirements_NN2 unique_JJ to_TO cloud_VVI computing_NN1 ,_, SaaS_NP2 ,_, and_CC collaborative_JJ software_NN1 application_NN1 security_NN1 (_( Rittinghouse_NP1 J._NP1 and_CC Ransome_NP1 J._NP1 ,_, 2009_MC ,_, p._NN1 167_MC )_) ._. 
</s>
<s>
These_DD2 requirements_NN2 are_VBR met_VVN by_II the_AT deployment_NN1 ,_, execution_NN1 and_CC documentation_NN1 of_IO policies_NN2 ,_, standards_NN2 ,_, and_CC guidelines_NN2 ._. 
</s>
<s>
Again_RT ,_, these_DD2 ones_NN2 need_VV0 to_TO be_VBI updated_VVN according_II21 to_II22 periodic_JJ reviews_NN2 and/or_CC change_VV0 in_II the_AT business_NN1 requirements_NN2 to_TO prevent_VVI disclosure_NN1 of_IO information_NN1 (_( Rittinghouse_NP1 J._NP1 and_CC Ransome_NP1 J._NP1 ,_, 2009_MC )_) ._. 
</s>
<s>
Security_NN1 processes_NN2 related_VVN to_II using_VVG SaaS_NP2 in_II the_AT Cloud_NN1 need_NN1 to_TO be_VBI implemented_VVN having_VHG in_II consideration_NN1 the_AT business_NN1 requirements_NN2 and_CC organization_NN1 internal_JJ policies_NN2 and_CC controls_NN2 ._. 
</s>
<s>
Thus_RR ,_, when_CS designing_VVG the_AT security_NN1 architecture_NN1 the_AT following_JJ security_NN1 processes_NN2 should_VM be_VBI designed_VVN along_II the_AT different_JJ layers_NN2 of_IO the_AT IT_NN1 structure_NN1 of_IO the_AT organization_NN1 :_: authentication_NN1 ,_, authorization_NN1 ,_, availability_NN1 ,_, confidentiality_NN1 ,_, integrity_NN1 ,_, accountability_NN1 and_CC privacy_NN1 (_( Rittinghouse_NP1 J._NP1 and_CC Ransome_NP1 J._NP1 ,_, 2009_MC ,_, p._NN1 172_MC )_) ._. 
</s>
<s>
It_PPH1 will_VM allow_VVI future_JJ reviews_NN2 to_TO be_VBI designed_VVN accordingly_RR making_VVG the_AT whole_JJ process_NN1 easier_RRR ._. 
</s>
<s>
In_II a_AT1 Cloud_NN1 environment_NN1 ,_, data_NN becomes_VVZ more_RGR vulnerable_JJ when_CS stored_VVN outside_II the_AT premises_NN2 of_IO the_AT organization_NN1 ._. 
</s>
<s>
Therefore_RR ,_, when_CS it_PPH1 comes_VVZ to_II whom_PNQO ,_, how_RRQ and_CC what_DDQ actions_NN2 can_VM be_VBI performed_VVN related_VVN to_II information_NN1 data_NN ,_, a_AT1 Data_NN Governance_NN1 framework_NN1 can_VM help_VVI to_TO define_VVI ,_, nominate_JJ responsibilities_NN2 by_II increasing_JJ awareness_NN1 of_IO the_AT areas_NN2 of_IO data_NN Inventory_NN1 ,_, classification_NN1 ,_, analysis_NN1 ,_, protection_NN1 ,_, privacy_NN1 ,_, and_CC destruction_NN1 (_( Rittinghouse_NP1 J._NP1 and_CC Ransome_NP1 J._NP1 ,_, 2009_MC ,_, p._NN1 175_MC )_) ._. 
</s>
<s>
V._II RESEARCH_NN1 FRAMEWORK_NN1 Most_DAT of_IO the_AT findings_NN2 under_II our_APPGE literature_NN1 review_NN1 are_VBR theoretical_JJ frameworks_NN2 and_CC recommendations_NN2 ._. 
</s>
<s>
The_AT majority_NN1 is_VBZ from_II the_AT professional_JJ or_CC market_VV0 side_NN1 ,_, with_IW little_DA1 from_II the_AT academia_NN1 ._. 
</s>
<s>
A_AT1 more_RGR empirical_JJ approach_NN1 is_VBZ needed_VVN through_II a_AT1 Case_NN1 Study_NN1 as_II an_AT1 exploratory_JJ research_NN1 ._. 
</s>
<s>
The_AT goal_NN1 is_VBZ to_TO analyze_VVI how_RRQ and_CC why_RRQ in_II practice_NN1 the_AT change_NN1 occurred_VVD in_II the_AT case_NN1 organization_NN1 ._. 
</s>
<s>
In-depth_JJ interviews_NN2 are_VBR the_AT main_JJ data_NN collection_NN1 ._. 
</s>
<s>
The_AT aim_NN1 is_VBZ to_TO recognize_VVI important_JJ themes_NN2 ,_, patterns_NN2 and_CC relationships_NN2 (_( Sanders_NP1 M._NN1 ,_, Lewis_NP1 P._NP1 and_CC Thornhill_NP1 A._NP1 ,_, 2009_MC ,_, p._NN1 488_MC )_) in_II the_AT changes_NN2 indentified_VVD ._. 
</s>
<s>
Holistic_JJ research_NN1 framework_NN1 presented_VVD here_RL aims_VVZ to_TO analyze_VVI cross_NN1 functionally_RR the_AT organization_NN1 ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) List_NN1 of_IO in-depth_JJ unstructured_JJ interview_NN1 questions_NN2 to_TO put_VVI in_II the_AT appendice_NN1 :_: 1_MC1 ._. 
</s>
<s>
When_RRQ did_VDD the_AT organization_NN1 started_VVD to_II used_JJ SaaS_NP2 in_II the_AT Cloud_NN1 ?_? 2_MC ._. 
</s>
<s>
How_RRQ did_VDD it_PPH1 start_VVI the_AT decision_NN1 to_TO consider_VVI SaaS_NP2 ?_? 3_MC ._. 
</s>
<s>
How_RGQ long_RR did_VDD the_AT process_NN1 take_VVI to_TO decide_VVI to_TO go_VVI into_II SaaS_NP2 ?_? 
</s>
<s>
Why_RRQ ?_? (_( cost_NN1 savings_NN2 ,_, IT_NN1 business_NN1 strategy_NN1 in_II the_AT short_JJ and_CC long_JJ run_NN1 or_CC ..._... ?_? )_) 4_MC ._. 
</s>
<s>
Why_RRQ was_VBDZ SaaS_NP2 chosen_JJ and_CC not_XX other_JJ ?_? 
</s>
<s>
Criteria_NN2 (_( network_NN1 ,_, hosting_VVG ,_, application_NN1 security_NN1 ,_, APIs_NP1 ,_, price_NN1 ,_, any_DD additional_JJ costs_NN2 for_IF enhancement_NN1 of_IO security_NN1 controls_VVZ to_TO handle_VVI sensitive_JJ and_CC regulated_VVD data_NN ?_? )_) 5_MC ._. 
</s>
<s>
With_IW the_AT adoption_NN1 of_IO SaaS_NP2 were_VBDR there_EX any_DD changes_NN2 to_II existing_JJ internal_JJ practices_NN2 ?_? 
</s>
<s>
If_CS so_RR ,_, how_RRQ and_CC why_RRQ has_VHZ it_PPH1 happened_VVN ?_? (_( any_DD risk_NN1 assessment_NN1 ,_, development_NN1 of_IO a_AT1 risk_NN1 treatment_NN1 plan_NN1 ,_, and_CC implementation_NN1 of_IO processes_NN2 for_IF responding_VVG to_II identified_JJ issues_NN2 =_FO all_RR these_DD2 still_RR linked_VVN to_II the_AT business_NN1 strategy_NN1 and_CC needs_NN2 )_) 6_MC ._. 
</s>
<s>
Any_DD changes_NN2 as_RR21 well_RR22 in_II the_AT structure_NN1 of_IO the_AT organization_NN1 ?_? 
</s>
<s>
Why_RRQ ?_? 7_MC ._. 
</s>
<s>
Has_VHZ there_EX been_VBN recruited_VVN new_JJ people_NN with_IW new_JJ skills_NN2 ?_? why_RRQ ?_? 8_MC ._. 
</s>
<s>
Has_VHZ there_EX been_VBN provided_VVN any_DD specific_JJ training_NN1 related_VVN to_II the_AT SaaS_NP2 ?_? who_PNQS and_CC why_RRQ ?_? 9_MC ._. 
</s>
<s>
What_DDQ were_VBDR so_RG far_RR the_AT biggest_JJT challenges_NN2 in_II the_AT organization_NN1 regarding_II the_AT adoption_NN1 of_IO SaaS_NP2 in_II the_AT Cloud_NN1 ?_? 
</s>
<s>
Why_RRQ ?_? 
</s>
<s>
Would_VM you_PPY do_VDI it_PPH1 differently_RR ?_? 10_MC ._. 
</s>
<s>
How_RRQ has_VHZ the_AT continuous_JJ improvement_NN1 been_VBN conducted_VVN to_TO keep_VVI up_RP the_AT cloud_NN1 computing_NN1 developments_NN2 in_II31 terms_II32 of_II33 Information_NN1 Security_NN1 best_RRT practices_VVZ ?_? 11_MC ._. 
</s>
<s>
How_RRQ and_CC how_RGQ long_RR did_VDD it_PPH1 take_VVI for_IF CC_NP1 to_TO decide_VVI how_RRQ the_AT Risk_NN1 management_NN1 would_VM be_VBI structured_VVN and_CC the_AT allocation_NN1 of_IO resources_NN2 for_IF risk_NN1 assessment_NN1 ?_? 12_MC ._. 
</s>
<s>
How_RRQ were_VBDR identified_VVN the_AT different_JJ kind_NN1 of_IO professionals_NN2 to_TO be_VBI included_VVN in_II the_AT risk_NN1 management_NN1 and_CC risk_NN1 assessment_NN1 related_VVN to_II the_AT SaaS_NP2 ?_? 13_MC ._. 
</s>
<s>
How_RRQ have_VH0 the_AT processes_NN2 been_VBN defined_VVN to_TO decide_VVI when_RRQ periodic_JJ review_NN1 meetings_NN2 should_VM take_VVI place_NN1 ?_? 
</s>
<s>
How_RRQ where_CS the_AT parameter_NN1 that_CST are_VBR reviewed_VVN in_II those_DD2 review_VV0 meetings_NN2 defined_VVN ?_? 14_MC ._. 
</s>
<s>
Has_VHZ there_EX been_VBN any_DD training_NN1 provided_VVN to_II users_NN2 related_VVN to_II Security_NN1 issues_NN2 and_CC others_NN2 (_( please_RR describe_VV0 briefly_RR )_) to_TO use_VVI SaaS_NP2 ?_? 
</s>
<s>
How_RRQ and_CC who_PNQS provided_VVD it_PPH1 ?_? 
</s>
<s>
Why_RRQ training_NN1 was_VBDZ provided_VVN ?_? 15_MC ._. 
</s>
<s>
How_RRQ about_II training_NN1 to_II the_AT internal_JJ security_NN1 team_NN1 and_CC (_( link_VV0 this_DD1 to_II fundamental_JJ security_NN1 and_CC risk_NN1 management_NN1 skills_NN2 and_CC knowledge_NN1 inside_II the_AT organization_NN1 )_) ?_? 16_MC ._. 
</s>
<s>
Have_VH0 there_EX been_VBN any_DD policies_NN2 implemented_VVN ?_? 
</s>
<s>
Why_RRQ and_CC how_RRQ has_VHZ it_PPH1 been_VBN developed_VVN ,_, documented_VVN and_CC implemented_VVN ?_? 17_MC ._. 
</s>
<s>
Have_VH0 there_EX been_VBN any_DD changes_NN2 to_II the_AT policies_NN2 ,_, standards_NN2 and_CC guidelines_NN2 related_VVN to_II SaaS_NP2 since_CS the_AT beginning_NN1 ?_? 
</s>
<s>
Why_RRQ have_VH0 they_PPHS2 occurred_VVN ?_? (_( is_VBZ it_PPH1 due_JJ to_TO review_VVI on_II any_DD basis_NN1 or_CC due_II21 to_II22 significant_JJ changes_NN2 in_II the_AT business_NN1 or_CC IT_NN1 environment_NN1 ?_? )_) 
</s>
<s>
VI_MC ._. 
</s>
<s>
EMPIRICAL_JJ RESEARCH_NN1 A._NP1 Research_NN1 Methodology_NN1 The_AT case_NN1 study_NN1 company_NN1 is_VBZ an_AT1 industrial_JJ big_JJ multinational_JJ supplier_NN1 with_IW is_VBZ headquarters_NN in_II Finland_NP1 ._. 
</s>
<s>
This_DD1 company_NN1 has_VHZ adopted_VVN SaaS_NP2 in_II the_AT cloud_NN1 since_II 2006_MC ._. 
</s>
<s>
Therefore_RR ,_, 5_MC years_NNT2 has_VHZ passed_VVN since_CS its_APPGE adoption_NN1 ,_, being_VBG considered_VVN a_AT1 good_JJ subject_NN1 of_IO study_NN1 for_IF the_AT changes_NN2 occurred_VVD ._. 
</s>
<s>
The_AT chosen_JJ interviewees_NN2 are_VBR from_II different_JJ areas_NN2 in_II the_AT organization_NN1 ._. 
</s>
<s>
From_II the_AT top_JJ level_JJ management_NN1 the_AT interviewees_NN2 are_VBR responsible_JJ for_IF the_AT decision_NN1 and_CC implementation_NN1 of_IO the_AT changes_NN2 occurred_VVD ._. 
</s>
<s>
A_AT1 Head_NN1 of_IO Technology_NN1 and_CC global_JJ strategic_JJ and_CC a_AT1 Director_NN1 ,_, head_NN1 of_IO h_ZZ1 process_VV0 solution-customer_NN1 interviewed_VVN for_IF this_DD1 purpose_NN1 ._. 
</s>
<s>
Other_JJ relevant_JJ interviewees_NN2 are_VBR a_AT1 platform_NN1 owner_NN1 ,_, responsible_JJ for_IF in-depth_JJ processes_NN2 changes_NN2 due_II21 to_II22 SaaS_NP2 ;_; a_AT1 representative_NN1 from_II the_AT Legal_JJ department_NN1 due_II21 to_II22 the_AT Service_NN1 Level_NN1 Agreement_NN1 ;_; and_CC an_AT1 Information_NN1 Security_NN1 Officer_NN1 SaaS_NP2 Strategic_JJ decision_NN1 Needed_VVD changes_NN2 identified_VVN Why_RRQ ?_? 
</s>
<s>
How_RRQ implemented_VVN ?_? 
</s>
<s>
Monitoring_NN1 and_CC feedback_NN1 related_VVN to_II training_NN1 ,_, risk_NN1 management_NN1 and_CC assessment_NN1 planning_NN1 ._. 
</s>
