<s>
Service_NN1 Development_NN1 Process_NN1 1_MC1 ._. 
</s>
<s>
Introduction_NN1 and_CC research_NN1 problem_NN1 The_AT service_NN1 sector_NN1 has_VHZ become_VVN increasingly_RR important_JJ in_II world_NN1 economy_NN1 :_: in_II 2008_MC ,_, the_AT value_NN1 added_VVN of_IO service_NN1 industry_NN1 was_VBDZ 69%_NNU of_IO the_AT worlds_NN2 gross_VV0 domestic_JJ product_NN1 (_( The_AT World_NN1 Bank_NN1 ,_, 2010_MC )_) ._. 
</s>
<s>
The_AT growth_NN1 of_IO service_NN1 industry_NN1 creates_VVZ ever_RR competitive_JJ environment_NN1 ,_, and_CC for_IF industry_NN1 or_CC a_AT1 company_NN1 to_TO be_VBI successful_JJ in_II this_DD1 environment_NN1 it_PPH1 needs_VVZ to_TO innovate_VVI continuously_RR and_CC develop_VVI its_APPGE services_NN2 ._. 
</s>
<s>
Due_II21 to_II22 the_AT increasing_JJ importance_NN1 of_IO service_NN1 industry_NN1 ,_, the_AT service_NN1 development_NN1 has_VHZ also_RR become_VV0 an_AT1 important_JJ area_NN1 of_IO research_NN1 (_( Menor_NP1 and_CC Roth_NP1 ,_, 2007_MC )_) ,_, as_CSA innovation_NN1 in_II service_NN1 industry_NN1 has_VHZ proven_VVN to_TO create_VVI greater_JJR revenues_NN2 for_IF companies_NN2 (_( de_NP1 Jong_NP1 and_CC Vermeulen_NP1 ,_, 2003_MC )_) ._. 
</s>
<s>
However_RR ,_, the_AT area_NN1 of_IO service_NN1 development_NN1 is_VBZ relatively_RR new_JJ ,_, as_CSA the_AT recognition_NN1 of_IO service_NN1 industry_NN1 as_CSA its_APPGE own_DA discipline_NN1 has_VHZ only_RR evolved_VVN during_II past_NN1 three_MC decades_NNT2 ._. 
</s>
<s>
This_DD1 is_VBZ also_RR evident_JJ in_II the_AT amount_NN1 of_IO studies_NN2 made_VVN in_II service_NN1 development_NN1 as_CSA there_EX were_VBDR very_RG few_DA2 published_JJ articles_NN2 in_II the_AT 1980s_MC2 but_CCB more_DAR than_CSN 20_MC every_AT1 year_NNT1 during_II the_AT 21st_MD century_NNT1 (_( de_NP1 Jong_NP1 and_CC Vermeulen_NP1 ,_, 2003_MC )_) ._. 
</s>
<s>
New_JJ services_NN2 come_VV0 to_TO market_VVI and_CC the_AT question_NN1 is_VBZ How_RRQ ?_? 
</s>
<s>
Based_VVN on_II the_AT previous_JJ studies_NN2 service_VV0 development_NN1 is_VBZ mostly_RR considered_VVN as_CSA ad_RR21 hoc_RR22 ,_, a_AT1 process_NN1 that_CST just_RR happens_VVZ (_( Kelly_NP1 &;_NULL Storey_NP1 ,_, 2000_MC )_) with_IW non_FU detailed_JJ process_NN1 (_( de_NP1 Brentani_NP1 ,_, 1991_MC )_) ._. 
</s>
<s>
However_RR ,_, the_AT process_NN1 of_IO organising_VVG the_AT service_NN1 development_NN1 is_VBZ important_JJ in_II service_NN1 development_NN1 ._. 
</s>
<s>
De_NP1 Brentani_NP1 concludes_VVZ about_II success_NN1 factors_NN2 for_IF service_NN1 development_NN1 that_CST ..._... companies_NN2 need_VV0 to_TO be_VBI proficient_JJ in_II how_RRQ they_PPHS2 go_VV0 about_II developing_VVG new_JJ services_NN2 (_( ..._... )_) analysis_NN1 indicate_VV0 that_CST a_AT1 formal_JJ and_CC planned_JJ approach_NN1 to_II new_JJ service_NN1 development_NN1 leads_VVZ to_II better_JJR performance_NN1 (_( 1991:54-55_MCMC )_) ._. 
</s>
<s>
The_AT formal_JJ process_NN1 gives_VVZ systematic_JJ means_NN to_TO transfer_VVI idea_NN1 into_II offering_NN1 ._. 
</s>
<s>
The_AT more_RGR successful_JJ service_NN1 firms_NN2 tend_VV0 to_TO have_VHI more_DAR formal_JJ service_NN1 development_NN1 process_NN1 ._. 
</s>
<s>
Griffin_NP1 (_( 1997_MC ,_, as_CSA cited_VVN in_II Menor_NP1 and_CC Roth_NP1 ,_, 2007_MC )_) identified_VVD that_CST the_AT best_JJT service_NN1 firms_NN2 are_VBR using_VVG more_RGR formal_JJ process_NN1 for_IF service_NN1 development_NN1 than_CSN the_AT less_RGR innovative_JJ and_CC Roth_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 1997_MC ,_, as_CSA cited_VVN in_II Menor_NP1 and_CC Roth_NP1 ,_, 2007_MC )_) referred_VVD that_DD1 world_NN1 class_NN1 services_NN2 are_VBR born_VVN in_II companies_NN2 with_IW formal_JJ service_NN1 development_NN1 process_NN1 ._. 
</s>
<s>
This_DD1 indicates_VVZ that_CST a_AT1 process_NN1 is_VBZ an_AT1 important_JJ part_NN1 of_IO the_AT service_NN1 development_NN1 and_CC that_DD1 special_JJ emphasis_NN1 should_VM be_VBI put_VVN on_II it_PPH1 when_CS managing_VVG a_AT1 service_NN1 development_NN1 ._. 
</s>
<s>
2_MC ._. 
</s>
<s>
Purpose_NN1 and_CC structure_NN1 of_IO the_AT study_NN1 The_AT aim_NN1 of_IO the_AT paper_NN1 is_VBZ to_TO study_VVI service_NN1 development_NN1 process_NN1 based_VVN on_II the_AT previous_JJ studies_NN2 ._. 
</s>
<s>
In_RR21 particular_RR22 ,_, the_AT purpose_NN1 is_VBZ to_TO identify_VVI different_JJ types_NN2 of_IO service_NN1 development_NN1 process_NN1 models_NN2 and_CC the_AT steps_NN2 of_IO the_AT process_NN1 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, the_AT aim_NN1 is_VBZ to_TO highlight_VVI future_JJ research_NN1 ideas_NN2 related_VVD to_TO service_VVI development_NN1 process_NN1 ._. 
</s>
<s>
The_AT structure_NN1 of_IO the_AT paper_NN1 is_VBZ following_VVG :_: firstly_RR ,_, the_AT service_NN1 and_CC service_NN1 development_NN1 concepts_NN2 are_VBR explained_VVN ;_; secondly_RR ,_, the_AT currently_RR known_VVN service_NN1 development_NN1 processes_NN2 are_VBR looked_VVN into_II ;_; and_CC lastly_RR ,_, conclusions_NN2 of_IO the_AT findings_NN2 are_VBR drawn_VVN ._. 
</s>
<s>
3_MC ._. 
</s>
<s>
Service_NN1 development_NN1 This_DD1 chapter_NN1 reviews_VVZ previous_JJ studies_NN2 related_VVD to_TO service_VVI development_NN1 process_NN1 ._. 
</s>
<s>
It_PPH1 starts_VVZ by_II outlining_VVG the_AT concept_NN1 of_IO service_NN1 and_CC definitions_NN2 used_VVN in_II the_AT field_NN1 of_IO service_NN1 development_NN1 ._. 
</s>
<s>
Then_RT service_VV0 development_NN1 concept_NN1 and_CC different_JJ models_NN2 for_IF service_NN1 development_NN1 process_NN1 are_VBR looked_VVN into_II ._. 
</s>
<s>
3.1_MC ._. 
</s>
<s>
Service_NN1 and_CC service_NN1 development_NN1 concepts_NN2 This_DD1 chapter_NN1 will_VM first_MD look_VVI into_II the_AT definition_NN1 of_IO service_NN1 and_CC then_RT ,_, the_AT various_JJ service_NN1 development_NN1 terminologies_NN2 and_CC concepts_NN2 are_VBR outlined_VVN ._. 
</s>
<s>
3.1.1_MC ._. 
</s>
<s>
Definition_NN1 of_IO service_NN1 Service_NN1 is_VBZ defined_VVN to_TO be_VBI heterogeneous_JJ ,_, intangible_JJ ,_, and_CC simultaneously_RR consumed_VVN and_CC produced_VVN (_( Kelly_NP1 and_CC Storey_NP1 2000_MC ;_; de_NP1 Jong_NP1 and_CC Vermeulen_NP1 2003_MC ;_; Alam_NP1 and_CC Perry_NP1 2002_MC ;_; Menor_NP1 ,_, Tatikonda_NP1 and_CC Sampson_NP1 ,_, 2002_MC )_) ._. 
</s>
<s>
Grnroos_NN2 (_( 2007:53_MC )_) gives_VVZ three_MC characteristics_NN2 for_IF service_NN1 :_: service_NN1 is_VBZ process_NN1 consisting_VVG of_IO series_NN of_IO activities_NN2 ,_, service_NN1 is_VBZ produced_VVN and_CC consumed_VVN simultaneously_RR ,_, and_CC customer_NN1 acts_VVZ as_II a_AT1 co-producer_NN1 in_II the_AT production_NN1 process_NN1 ._. 
</s>
<s>
Service_NN1 concept_NN1 is_VBZ not_XX only_RR related_VVN to_TO service_VVI industry_NN1 but_CCB many_DA2 companies_NN2 providing_VVG tangible_JJ products_NN2 offer_VV0 some_DD kind_NN1 or_CC some_DD level_NN1 of_IO services_NN2 with_IW the_AT product_NN1 (_( Smith_NP1 et_RA21 al._RA22 ,_, 2007_MC )_) ._. 
</s>
<s>
These_DD2 services_NN2 can_VM be_VBI augmented_VVN offering_VVG to_II the_AT physical_JJ product_NN1 ,_, for_REX21 example_REX22 ,_, after_CS sales_NN ,_, maintenance_NN1 and_CC insurance_NN1 services_NN2 ._. 
</s>
<s>
Because_CS products_NN2 tend_VV0 to_TO become_VVI commodities_NN2 ,_, the_AT service_NN1 offered_VVN with_IW the_AT product_NN1 creates_VVZ additional_JJ benefits_NN2 for_IF the_AT producer_NN1 :_: it_PPH1 differentiates_VVZ the_AT commodity_NN1 from_II the_AT competitors_NN2 ,_, creates_VVZ more_DAR customer_NN1 value_NN1 and_CC hence_RR becomes_VVZ a_AT1 competitive_JJ advantage_NN1 (_( Edvardsson_NP1 ,_, Gustafsson_NP1 ,_, Kristensson_NP1 ,_, Magnusson_NP1 and_CC Mathing_NP1 ,_, 2006_MC )_) ._. 
</s>
<s>
3.1.2_MC ._. 
</s>
<s>
Definition_NN1 of_IO service_NN1 development_NN1 There_EX are_VBR several_DA2 different_JJ concepts_NN2 and_CC definitions_NN2 related_VVD to_TO service_VVI development_NN1 :_: service_NN1 innovation_NN1 ,_, new_JJ service_NN1 development_NN1 (_( NSD_NP1 )_) and_CC service_NN1 development_NN1 ._. 
</s>
<s>
Service_NN1 innovation_NN1 ,_, NDS_NP1 and_CC service_NN1 development_NN1 are_VBR used_VVN interchangeably_RR and_CC the_AT key_JJ characteristic_NN1 in_II all_DB of_IO them_PPHO2 is_VBZ that_CST something_PN1 new_JJ in_II the_AT area_NN1 of_IO service_NN1 is_VBZ developed_VVN and_CC implemented_VVN (_( de_NP1 Jong_NP1 and_CC Vermeulen_NP1 ,_, 2003_MC )_) ._. 
</s>
<s>
Menor_NN1 and_CC Roth_NP1 defines_VVZ new_JJ service_NN1 as_CSA offering_VVG not_XX previously_RR available_JJ to_II the_AT firms_NN2 customers_NN2 that_CST results_NN2 from_II either_DD1 addition_NN1 to_II the_AT current_JJ mix_NN1 of_IO services_NN2 or_CC from_II changes_NN2 made_VVN to_II the_AT service_NN1 delivery_NN1 process_NN1 (_( 2007:826_MC )_) ._. 
</s>
<s>
In_II this_DD1 definition_NN1 it_PPH1 is_VBZ stressed_VVN that_CST new_JJ service_NN1 and_CC service_NN1 development_NN1 is_VBZ related_VVN both_RR to_II the_AT process_NN1 as_II21 to_II22 the_AT service_NN1 concept_NN1 ._. 
</s>
<s>
Johnson_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
states_NN2 that_CST NSD_NP1 refers_VVZ to_II an_AT1 overall_JJ process_NN1 of_IO developing_JJ new_JJ service_NN1 offerings_NN2 (_( 2000:5_MC )_) ._. 
</s>
<s>
Von_NP1 Koskull_NP1 (_( 2009:8_MC )_) uses_VVZ following_VVG definition_NN1 an_AT1 organizational_JJ process_NN1 that_CST aims_VVZ to_TO create_VVI a_AT1 totally_RR new_JJ or_CC a_AT1 revised_JJ service_NN1 ._. 
</s>
<s>
Additionally_RR ,_, von_NP1 Koskull_NP1 (_( 2009:7_MC )_) notes_VVZ that_CST it_PPH1 is_VBZ important_JJ to_TO recognise_VVI that_CST there_EX is_VBZ not_XX one_PN1 agreed_VVD definition_NN1 for_IF the_AT service_NN1 development_NN1 ._. 
</s>
<s>
In_II this_DD1 study_NN1 ,_, the_AT definition_NN1 by_II von_NP1 Koskull_NP1 is_VBZ used_VVN ._. 
</s>
<s>
As_CSA mentioned_VVN earlier_RRR ,_, service_NN1 innovation_NN1 and_CC NSD/service_VV0 development_NN1 can_VM be_VBI interpreted_VVN to_TO encompass_VVI the_AT same_DA factors_NN2 ._. 
</s>
<s>
However_RR ,_, the_AT term_NN1 service_NN1 innovation_NN1 originates_VVZ from_II economics_NN1 and_CC business_NN1 strategy_NN1 ,_, and_CC focuses_VVZ on_II developing_JJ theories_NN2 ._. 
</s>
<s>
Service_NN1 development_NN1 or_CC NSD_NP1 ,_, on_II the_AT other_JJ hand_NN1 ,_, emanates_VVZ from_II the_AT service_NN1 management_NN1 and_CC marketing_NN1 ,_, and_CC focuses_VVZ on_II practises_NN2 in_II service_NN1 development_NN1 ._. 
</s>
<s>
(_( Menor_NP1 et_RA21 al._RA22 ,_, 2002_MC )_) In_II this_DD1 light_NN1 ,_, the_AT term_NN1 NSD_NP1 or_CC service_NN1 development_NN1 is_VBZ more_RGR suitable_JJ for_IF this_DD1 study_NN1 than_CSN service_NN1 innovation_NN1 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, NSD_NP1 and_CC service_NN1 development_NN1 are_VBR used_VVN as_CSA one_MC1 term_NN1 in_II the_AT literature_NN1 but_CCB in_BCL21 order_BCL22 to_TO make_VVI the_AT study_NN1 more_DAR reader_NN1 friendly_JJ only_JJ term_NN1 ,_, service_NN1 development_NN1 ,_, is_VBZ used_VVN from_II this_DD1 on_RP ._. 
</s>
<s>
It_PPH1 is_VBZ also_RR important_JJ to_TO make_VVI distinction_NN1 between_II service_NN1 development_NN1 and_CC developed_JJ service_NN1 :_: service_NN1 development_NN1 is_VBZ the_AT process_NN1 to_TO reach_VVI the_AT outcome_NN1 i.e._REX developed_JJ service_NN1 (_( von_NP1 Koskull_NP1 ,_, 2009:8_MC )_) ._. 
</s>
<s>
3.3_MC ._. 
</s>
<s>
Service_NN1 development_NN1 process_NN1 Cooper_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 1994_MC )_) defined_VVD the_AT service_NN1 development_NN1 process_NN1 to_TO be_VBI set_VVN of_IO stages_NN2 and_CC activities_NN2 ,_, actions_NN2 ,_, or_CC tasks_NN2 that_CST moves_VVZ the_AT project_NN1 from_II the_AT idea_NN1 stage_NN1 to_II final_JJ launch_NN1 (_( as_CSA cited_VVN in_II Johnson_NP1 et_RA21 al._RA22 ,_, 2000:5_MC )_) ._. 
</s>
<s>
As_CSA service_NN1 is_VBZ intangible_JJ in_II nature_NN1 there_EX is_VBZ a_AT1 need_NN1 to_TO tangibilize_VVI the_AT service_NN1 development_NN1 process_NN1 and_CC make_VVI it_PPH1 more_RGR understandable_JJ and_CC concrete_NN1 for_IF all_DB the_AT parties_NN2 within_II the_AT service_NN1 development_NN1 process_NN1 (_( Menor_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2002_MC )_) ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, the_AT service_NN1 development_NN1 process_NN1 includes_VVZ different_JJ tangible_JJ stages_NN2 and_CC steps_NN2 which_DDQ explain_VV0 what_DDQ is_VBZ needed_VVN to_TO be_VBI accomplished_VVN in_BCL21 order_BCL22 to_TO develop_VVI a_AT1 new_JJ service_NN1 ._. 
</s>
<s>
The_AT amount_NN1 and_CC name_NN1 of_IO different_JJ steps_NN2 of_IO the_AT service_NN1 development_NN1 process_NN1 varies_VVZ :_: some_DD have_VH0 identified_VVN more_DAR steps_NN2 (_( e.g._REX Scheuing_NP1 and_CC Johnson_NP1 ,_, 1989_MC ;_; Alam_NP1 and_CC Perry_NP1 ,_, 2002_MC )_) while_CS others_NN2 have_VH0 fewer_DAR steps_NN2 (_( e.g._REX Bowers_NP1 ,_, 1989_MC )_) or_CC have_VH0 incorporated_VVN several_DA2 steps_NN2 under_II fewer_DAR stages_NN2 (_( e.g._REX Lievens_NP1 ,_, Moenaert_NP1 and_CC Jegers_NP1 ,_, 1999_MC )_) ._. 
</s>
<s>
Reasons_NN2 for_IF the_AT differences_NN2 between_II models_NN2 are_VBR related_VVN to_TO research_VVI focus_NN1 :_: for_REX21 example_REX22 ,_, to_II the_AT service_NN1 to_TO be_VBI developed_VVN ,_, the_AT newness_NN1 of_IO the_AT development_NN1 ,_, and_CC to_II the_AT industry_NN1 of_IO the_AT developed_JJ service_NN1 (_( Johnson_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2000_MC ;_; Alam_NP1 and_CC Perry_NP1 2002_MC )_) ._. 
</s>
<s>
Studies_NN2 have_VH0 come_VVN up_RP with_IW conflicting_JJ results_NN2 whether_CSW formal_JJ process_NN1 is_VBZ followed_VVN by_II companies_NN2 or_CC not_XX (_( Alam_NP1 and_CC Perry_NP1 ,_, 2002_MC )_) :_: some_DD research_NN1 have_VH0 identified_VVN that_CST companies_NN2 do_VD0 not_XX follow_VVI a_AT1 formal_JJ process_NN1 (_( Kelly_NP1 and_CC Storey_NP1 ,_, 2000_MC )_) but_CCB others_NN2 have_VH0 come_VVN up_RP with_IW opposite_JJ results_NN2 (_( e.g._REX Edvardsson_NP1 et_RA21 al._RA22 ,_, 1996_MC )_) ._. 
</s>
<s>
One_MC1 of_IO the_AT reasons_NN2 for_IF less_RGR formal_JJ process_NN1 is_VBZ the_AT size_NN1 of_IO the_AT company_NN1 :_: when_RRQ the_AT company_NN1 size_NN1 decreases_VVZ then_RT process_NN1 becomes_VVZ less_RGR formal_JJ ._. 
</s>
<s>
This_DD1 is_VBZ mainly_RR due_II21 to_II22 the_AT fewer_DAR resources_NN2 of_IO the_AT company_NN1 ._. 
</s>
<s>
(_( Alam_NP1 &;_NULL Perry_NP1 ,_, 2002_MC ;_; Gottfridsson_NP1 ,_, 2010_MC )_) No_AT matter_NN1 if_CS a_AT1 formal_JJ process_NN1 is_VBZ followed_VVN or_CC not_XX ,_, there_EX are_VBR evidences_NN2 of_IO benefits_NN2 when_RRQ the_AT more_RGR formalised_JJ process_NN1 is_VBZ used_VVN (_( Menor_NP1 and_CC Roth_NP1 ,_, 2007_MC )_) ._. 
</s>
<s>
There_EX is_VBZ not_XX one_MC1 way_NN1 to_TO categorize_VVI service_NN1 development_NN1 models_NN2 ._. 
</s>
<s>
Johnsson_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2000:10_MC )_) used_VVD following_VVG categorization_NN1 :_: partial_JJ ,_, translational_JJ and_CC comprehensive_JJ ._. 
</s>
<s>
Partial_JJ models_NN2 include_VV0 only_JJ part_NN1 of_IO the_AT service_NN1 development_NN1 model_NN1 ,_, e.g._REX these_DD2 models_NN2 concentrate_VV0 only_RR to_II the_AT beginning_NN1 of_IO the_AT process_NN1 ._. 
</s>
<s>
Translational_JJ models_NN2 are_VBR based_VVN on_II Booz_NP1 ,_, Allen_NP1 and_CC Hamilton_NP1 (_( BAH_UH )_) new_JJ product_NN1 development_NN1 model_NN1 (_( 1968_MC ;_; as_CSA cited_VVN in_II Johnson_NP1 et_RA21 al._RA22 ,_, 2000:9_MC )_) ,_, and_CC the_AT comprehensive_JJ model_NN1 takes_VVZ wider_JJR and_CC more_RGR holistic_JJ view_NN1 to_II the_AT whole_JJ service_NN1 development_NN1 process_NN1 ._. 
</s>
<s>
(_( Johnson_NP1 et_RA21 al._RA22 ,_, 2000:10_MC )_) ._. 
</s>
<s>
However_RR ,_, in_II this_DD1 study_NN1 the_AT previous_JJ categorization_NN1 is_VBZ not_XX feasible_JJ ._. 
</s>
<s>
This_DD1 is_VBZ due_II21 to_II22 the_AT few_DA2 reasons_NN2 ._. 
</s>
<s>
Firstly_RR ,_, this_DD1 study_NN1 focuses_VVZ on_II the_AT whole_JJ process_NN1 and_CC does_VDZ not_XX only_RR look_VVI into_II part_NN1 of_IO the_AT study_NN1 ._. 
</s>
<s>
Secondly_RR ,_, most_DAT of_IO the_AT service_NN1 development_NN1 models_NN2 are_VBR not_XX only_RR based_VVN on_II BAH_UH model_NN1 but_CCB is_VBZ has_VHZ grown_VVN to_TO be_VBI own_DA area_NN1 of_IO research_NN1 ._. 
</s>
<s>
Lastly_RR ,_, the_AT recent_JJ service_NN1 development_NN1 models_NN2 have_VH0 more_RGR holistic_JJ view_NN1 to_II the_AT service_NN1 development_NN1 and_CC do_VD0 not_XX look_VVI it_PPH1 only_RR from_II one_MC1 perspective_NN1 (_( e.g._REX Alam_NP1 and_CC Perry_NP1 ,_, 2002_MC )_) ._. 
</s>
<s>
In_II this_DD1 study_NN1 the_AT service_NN1 development_NN1 process_NN1 models_NN2 are_VBR grouped_VVN based_VVN on_II their_APPGE structure_NN1 to_II linear_JJ and_CC cycle_NN1 models_NN2 ._. 
</s>
<s>
Next_MD chapters_NN2 will_VM look_VVI into_II previously_RR grouped_VVN models_NN2 ._. 
</s>
<s>
3.3.1_MC ._. 
</s>
<s>
Linear_JJ service_NN1 development_NN1 model_NN1 Initial_NN1 service_NN1 development_NN1 models_NN2 were_VBDR based_VVN on_II the_AT product_NN1 development_NN1 studies_NN2 as_II the_AT research_NN1 of_IO product_NN1 development_NN1 started_VVD earlier_RRR (_( Johnson_NP1 et_RA21 al._RA22 ,_, 2000_MC )_) ._. 
</s>
<s>
The_AT product_NN1 development_NN1 process_NN1 model_NN1 was_VBDZ initially_RR linear_JJ and_CC sequential_JJ i.e._REX process_NN1 steps_NN2 are_VBR designed_VVN in_II linear_JJ form_NN1 and_CC all_DB the_AT stages_NN2 are_VBR performed_VVN in_II sequence_NN1 ,_, one_PN1 after_II another_DD1 ._. 
</s>
<s>
A_AT1 good_JJ example_NN1 of_IO this_DD1 is_VBZ Booz_NP1 ,_, Allen_NP1 and_CC Hamilton_NP1 (_( BAH_UH )_) model_VV0 that_DD1 is_VBZ presented_VVN with_IW three_MC different_JJ service_NN1 development_NN1 process_NN1 models_NN2 in_II the_AT Table_NN1 1_MC1 ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) The_AT BAH_UH model_NN1 ,_, initially_RR published_VVN in_II 1968_MC and_CC improved_VVN 1982_MC (_( Booz_NP1 ,_, Allen_NP1 and_CC Hamilton_NP1 ,_, 1968_MC ,_, 1982_MC ,_, as_CSA cited_VVN in_II Johnson_NP1 et_RA21 al._RA22 ,_, 2000:12_MC )_) created_VVD the_AT basis_NN1 of_IO very_RG systematic_JJ and_CC formalized_JJ way_NN1 of_IO conducting_VVG product_NN1 development_NN1 and_CC it_PPH1 was_VBDZ used_VVN as_II a_AT1 basis_NN1 for_IF many_DA2 service_NN1 development_NN1 models_NN2 (_( Johnson_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2000:12_MC )_) ._. 
</s>
<s>
Bowers_NP1 (_( 1989_MC )_) and_CC Sheuing_NP1 and_CC Johnssons_NP2 (_( 1989_MC )_) models_NN2 are_VBR the_AT first_MD empirically_RR tested_VVN service_NN1 development_NN1 models_NN2 ._. 
</s>
<s>
Both_DB2 of_IO them_PPHO2 are_VBR linear_JJ and_CC sequential_JJ and_CC the_AT difference_NN1 is_VBZ in_II steps_NN2 ._. 
</s>
<s>
Scheuing_NP1 &;_NULL Johnssons_NP2 model_NN1 is_VBZ more_RGR exhaustive_JJ compared_VVN to_II Bowers_NP1 model_NN1 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, Scheuing_NP1 and_CC Johnssons_NP2 model_NN1 includes_VVZ pre_II and_CC post_NN1 steps_NN2 as_II31 well_II32 as_II33 personnel_NN2 training_NN1 ._. 
</s>
<s>
Personnel_NN2 training_NN1 is_VBZ an_AT1 important_JJ step_NN1 for_IF implementing_VVG the_AT new_JJ service_NN1 as_CSA new_JJ services_NN2 often_RR fail_VV0 because_CS personnel_NN2 have_VH0 not_XX been_VBN trained_VVN properly_RR (_( Sheuing_NP1 and_CC Johnssons_NP2 ,_, 1989_MC )_) ._. 
</s>
<s>
One_MC1 of_IO the_AT features_NN2 of_IO service_NN1 is_VBZ interactivity_NN1 i.e._REX personnel_NN2 interaction_NN1 with_IW the_AT customer_NN1 and_CC hence_RR ,_, personnel_NN2 need_VV0 to_TO be_VBI trained_VVN properly_RR to_II the_AT new_JJ procedures_NN2 and_CC activities_NN2 ._. 
</s>
<s>
In_II Avlonitis_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
empirical_JJ research_NN1 the_AT stages_NN2 previously_RR identified_VVN by_II other_JJ scholars_NN2 were_VBDR grouped_VVN under_II fewer_DAR stages_NN2 ._. 
</s>
<s>
However_RR ,_, the_AT newer_JJR product_NN1 development_NN1 models_NN2 have_VH0 different_JJ stages_NN2 and_CC the_AT process_NN1 has_VHZ been_VBN identified_VVN to_TO be_VBI parallel_RR rather_II21 than_II22 sequential_JJ (_( Alam_NP1 and_CC Perry_NP1 ,_, 2002_MC )_) ._. 
</s>
<s>
This_DD1 also_RR influenced_VVN Alam_NP1 and_CC Perry_NP1 (_( 2002_MC )_) to_TO look_VVI how_RRQ the_AT service_NN1 development_NN1 process_NN1 is_VBZ conducted_VVN within_II the_AT firms_NN2 :_: is_VBZ it_PPH1 parallel_RR or_CC sequential_JJ ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, due_II21 to_II22 nature_NN1 of_IO the_AT service_NN1 and_CC the_AT interactive_JJ role_NN1 customer_NN1 has_VHZ in_II service_NN1 process_NN1 ,_, Alam_NP1 and_CC Perry_NP1 (_( 2002_MC )_) looked_VVD to_II the_AT service_NN1 development_NN1 process_NN1 by_II identifying_VVG customer_NN1 interaction_NN1 in_II a_AT1 process_NN1 ._. 
</s>
<s>
Customer_NN1 involvement_NN1 is_VBZ identified_VVN to_TO have_VHI bigger_JJR role_NN1 in_II service_NN1 development_NN1 than_CSN in_II product_NN1 development_NN1 due_II21 to_II22 interactivity_NN1 of_IO the_AT service_NN1 (_( Alam_NP1 &;_NULL Perry_NP1 ,_, 2002_MC )_) ._. 
</s>
<s>
In_II the_AT Figure_NN1 1_MC1 the_AT stages_NN2 of_IO sequential_JJ and_CC parallel_JJ models_NN2 are_VBR presented_VVN ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) Alam_VV0 and_CC Perry_NP1 (_( 2002_MC )_) identified_VVN through_II their_APPGE empirical_JJ study_NN1 10_MC step_NN1 model_NN1 ._. 
</s>
<s>
Model_NN1 has_VHZ somewhat_RR same_DA steps_NN2 as_CSA Bowers_NP1 (_( 1989_MC )_) and_CC Scheuing_NP1 and_CC Johnsons_NP2 (_( 1989_MC )_) models_NN2 ._. 
</s>
<s>
However_RR ,_, a_AT1 different_JJ stage_NN1 called_VVN formation_NN1 of_IO cross-functional_JJ team_NN1 was_VBDZ identified_VVN first_MD time_NNT1 ._. 
</s>
<s>
This_DD1 new_JJ step_NN1 is_VBZ already_RR discussed_VVN in_II studies_NN2 of_IO product_NN1 development_NN1 and_CC in_II other_JJ studies_NN2 related_VVD to_TO cross_VVI functionality_NN1 of_IO service_NN1 development_NN1 (_( Alam_NP1 and_CC Perry_NP1 ,_, 2002_MC )_) ._. 
</s>
<s>
However_RR ,_, Alam_NP1 and_CC Perry_NP1 defined_VVD the_AT step_NN1 formation_NN1 of_IO cross-functional_JJ team_NN1 only_RR involving_VVG internal_JJ cross-functional_JJ parties_NN2 and_CC not_XX any_DD external_JJ parties_NN2 ._. 
</s>
<s>
As_CSA mentioned_VVN earlier_RRR ,_, it_PPH1 is_VBZ identified_VVN in_II recent_JJ product_NN1 development_NN1 models_NN2 that_CST the_AT process_NN1 is_VBZ not_XX always_RR sequential_JJ but_CCB it_PPH1 can_VM be_VBI parallel_RR as_CSA well_JJ (_( Johnson_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2000:13_MC ,_, Alam_NP1 and_CC Perry_NP1 ,_, 2002_MC )_) ._. 
</s>
<s>
Alam_VV0 and_CC Perry_NP1 discovered_VVD three_MC phases_NN2 where_RRQ the_AT stages_NN2 can_VM be_VBI performed_VVN parallel_RR as_CSA can_VM be_VBI seen_VVN in_II Figure_NN1 2_MC ._. 
</s>
<s>
However_RR ,_, the_AT results_NN2 are_VBR inconclusive_JJ which_DDQ one_MC1 of_IO the_AT models_NN2 is_VBZ better_JJR as_CSA there_EX is_VBZ still_RR debate_VV0 between_II scholars_NN2 ._. 
</s>
<s>
Other_JJ researchers_NN2 have_VH0 identified_VVN linear_JJ to_TO be_VBI most_RGT successful_JJ and_CC the_AT others_NN2 have_VH0 emphasised_VVN the_AT importance_NN1 of_IO parallel_JJ model_NN1 ._. 
</s>
<s>
Nonetheless_RR ,_, speed_NN1 of_IO the_AT development_NN1 process_NN1 is_VBZ identified_VVN to_TO be_VBI one_MC1 of_IO the_AT most_RGT important_JJ factor_NN1 for_IF companies_NN2 and_CC in_BCL21 order_BCL22 to_TO speed_VVI the_AT process_NN1 some_DD stages_NN2 can_VM be_VBI performed_VVN at_II the_AT same_DA time_NNT1 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, it_PPH1 is_VBZ important_JJ to_TO note_VVI that_CST especially_RR the_AT small_JJ enterprises_NN2 have_VH0 more_RGR parallel_JJ stages_NN2 compared_VVN to_II the_AT bigger_JJR companies_NN2 ._. 
</s>
<s>
(_( Alam_NN1 and_CC Perry_NP1 ,_, 2002_MC )_) Lastly_RR ,_, Alam_NP1 and_CC Perry_NP1 (_( 2002_MC )_) also_RR discovered_VVD what_DDQ kind_NN1 of_IO customer_NN1 input_NN1 can_VM be_VBI obtained_VVN during_II each_DD1 stage_NN1 ._. 
</s>
<s>
However_RR ,_, they_PPHS2 did_VDD not_XX define_VVI if_CS or_CC how_RRQ the_AT companies_NN2 are_VBR collecting_VVG the_AT customer_NN1 input_NN1 or_CC if_CS possibly_RR collected_VVN customer_NN1 input_NN1 is_VBZ really_RR used_VVN for_IF the_AT service_NN1 development_NN1 ._. 
</s>
<s>
As_II a_AT1 conclusion_NN1 it_PPH1 can_VM be_VBI said_VVN that_CST linear_JJ service_NN1 development_NN1 models_NN2 include_VV0 various_JJ amounts_NN2 of_IO stages_NN2 depending_VVG of_IO the_AT detailed_JJ level_NN1 these_DD2 steps_NN2 are_VBR identified_VVN ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, the_AT service_NN1 development_NN1 process_NN1 steps_NN2 can_VM be_VBI parallel_RR instead_II21 of_II22 sequential_JJ ,_, especially_RR if_CS companies_NN2 are_VBR smaller_JJR and_CC resources_NN2 are_VBR fewer_DAR (_( Alam_NP1 and_CC Perry_NP1 ,_, 2002_MC )_) ._. 
</s>
<s>
The_AT same_DA parallel_JJ process_NN1 steps_NN2 were_VBDR also_RR acknowledged_VVN by_II Johnson_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2000:13_MC )_) and_CC they_PPHS2 created_VVD a_AT1 conceptual_JJ model_NN1 called_VVN process_NN1 cycle_NN1 model_NN1 ._. 
</s>
<s>
Next_MD the_AT cyclical_JJ service_NN1 development_NN1 process_NN1 model_NN1 is_VBZ presented_VVN ._. 
</s>
<s>
3.3.2_MC ._. 
</s>
<s>
Process_VV0 cycle_NN1 model_NN1 The_AT service_NN1 development_NN1 process_NN1 cycle_NN1 ,_, presented_VVN in_II the_AT Figure_NN1 2_MC ,_, is_VBZ combining_VVG different_JJ aspects_NN2 influencing_VVG to_II the_AT service_NN1 development_NN1 process_NN1 ._. 
</s>
<s>
The_AT main_JJ idea_NN1 of_IO the_AT model_NN1 is_VBZ that_CST the_AT development_NN1 process_NN1 is_VBZ not_XX linear_JJ but_CCB it_PPH1 is_VBZ cyclical_JJ and_CC the_AT different_JJ phases_NN2 or_CC activities_NN2 can_VM overlap_VVI each_PPX221 other_PPX222 and_CC to_TO be_VBI iterative_JJ ._. 
</s>
<s>
The_AT process_NN1 cycle_NN1 takes_VVZ into_II account_NN1 that_CST the_AT service_NN1 development_NN1 process_NN1 involves_VVZ and_CC is_VBZ revolved_VVN around_II different_JJ enablers_NN2 (_( organizational_JJ context_NN1 ,_, teams_NN2 ,_, and_CC tools_NN2 )_) and_CC resources_NN2 (_( people_NN ,_, product_NN1 ,_, technology_NN1 ,_, and_CC system_NN1 )_) ._. 
</s>
<s>
(_( Johnson_NP1 et_RA21 al._RA22 ,_, 2000:14_MC ;_; Gottfridsson_NP1 ,_, 2010_MC ;_; Menor_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2002_MC )_) &lsqb;_( Figure_NN1 &rsqb;_) The_AT phases_NN2 in_II the_AT model_NN1 evolve_VV0 around_RP planning_VVG and_CC execution_NN1 ._. 
</s>
<s>
Planning_NN1 includes_VVZ design_NN1 and_CC analysis_NN1 and_CC execution_NN1 includes_VVZ development_NN1 and_CC launch_NN1 ._. 
</s>
<s>
In_II all_DB of_IO these_DD2 four_MC phases_NN2 some_DD more_DAR specific_JJ steps_NN2 are_VBR included_VVN ._. 
</s>
<s>
Additionally_RR ,_, the_AT use_NN1 and_CC importance_NN1 of_IO enablers_NN2 during_II these_DD2 two_MC stages_NN2 can_VM be_VBI different_JJ (_( Johnson_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2000_MC )_) ._. 
</s>
<s>
In_RR21 general_RR22 ,_, these_DD2 phases_NN2 do_VD0 not_XX differ_VVI much_RR from_II the_AT linear_JJ stages_NN2 ._. 
</s>
<s>
The_AT non-linear_JJ or_CC cyclical_JJ model_NN1 emphasis_NN1 that_CST different_JJ stages_NN2 overlap_VV0 with_IW each_PPX221 other_PPX222 and_CC that_CST the_AT process_NN1 is_VBZ highly_RR iterative_JJ than_CSN sequential_JJ ._. 
</s>
<s>
This_DD1 also_RR fits_VVZ to_II the_AT empirical_JJ evidence_NN1 that_CST the_AT service_NN1 development_NN1 process_NN1 is_VBZ often_RR informal_JJ (_( Menor_NP1 et_RA21 al._RA22 ,_, 2002_MC )_) and_CC more_RGR flexible_JJ compared_VVN to_II the_AT product_NN1 development_NN1 ._. 
</s>
<s>
The_AT cyclical_JJ model_NN1 is_VBZ also_RR good_JJ in_II a_AT1 sense_NN1 that_CST it_PPH1 takes_VVZ into_II account_NN1 the_AT different_JJ actors_NN2 ;_; for_REX21 example_REX22 ,_, people_NN in_II the_AT service_NN1 development_NN1 process_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ important_JJ because_CS service_NN1 often_RR is_VBZ interactive_JJ and_CC the_AT role_NN1 of_IO human_JJ interaction_NN1 is_VBZ big_JJ in_II service_NN1 delivery_NN1 ,_, and_CC hence_RR it_PPH1 can_VM also_RR have_VHI big_JJ impact_NN1 in_II service_NN1 development_NN1 ._. 
</s>
<s>
4_MC ._. 
</s>
<s>
Conclusions_NN2 In_II overall_NN1 ,_, the_AT literature_NN1 review_NN1 identified_VVN different_JJ models_NN2 for_IF service_NN1 development_NN1 process_NN1 ._. 
</s>
<s>
The_AT form_NN1 and_CC different_JJ stages_NN2 varied_VVD based_VVN on_II the_AT studies_NN2 ._. 
</s>
<s>
Many_DA2 researchers_NN2 have_VH0 agreed_VVN that_CST the_AT service_NN1 development_NN1 model_NN1 rarely_RR happens_VVZ sequentially_RR but_CCB many_DA2 of_IO the_AT process_NN1 steps_NN2 are_VBR parallel_RR ._. 
</s>
<s>
However_RR ,_, there_EX is_VBZ still_RR debate_VV0 how_RRQ the_AT process_NN1 is_VBZ formed_VVN :_: should_VM it_PPH1 be_VBI cyclical_JJ or_CC linear_JJ and_CC parallel_JJ or_CC sequential_JJ ._. 
</s>
<s>
Additionally_RR ,_, it_PPH1 has_VHZ been_VBN stated_VVN that_CST a_AT1 one_MC1 specific_JJ model_NN1 can_VM not_XX encompass_VVI how_RRQ all_DB services_NN2 are_VBR developed_VVN ._. 
</s>
<s>
The_AT development_NN1 process_NN1 is_VBZ strongly_RR dependent_JJ in_II many_DA2 various_JJ aspects_NN2 such_II21 as_II22 the_AT newness_NN1 of_IO the_AT service_NN1 ,_, the_AT size_NN1 of_IO the_AT business_NN1 ,_, type_NN1 of_IO the_AT industry_NN1 ,_, country_NN1 in_II question_NN1 etc_RA ._. 
</s>
<s>
(_( Alam_VV0 ,_, 2006b_FO )_) Even_CS21 though_CS22 the_AT cyclical_JJ model_NN1 encompasses_VVZ several_DA2 aspects_NN2 influencing_VVG to_II the_AT service_NN1 development_NN1 it_PPH1 is_VBZ missing_VVG one_MC1 feature_NN1 :_: the_AT importance_NN1 of_IO the_AT customer_NN1 in_II service_NN1 development_NN1 process_NN1 ._. 
</s>
<s>
Even_CS21 though_CS22 many_DA2 scholars_NN2 have_VH0 emphasised_VVN the_AT importance_NN1 of_IO customer_NN1 the_AT actual_JJ customer_NN1 interaction_NN1 and_CC the_AT ways_NN2 customers_NN2 are_VBR present_JJ in_II the_AT process_NN1 is_VBZ missing_VVG from_II the_AT cyclical_JJ as_II31 well_II32 as_II33 from_II the_AT linear_JJ models_NN2 ._. 
</s>
