<s>
Tobashi_JJ Scheme_NN1 ,_, The_AT Failure_NN1 of_IO Japanese_JJ Corporate_JJ Governance_NN1 ?_? 
</s>
<s>
Case_NN1 Olympus_NN1 1_MC1 ._. 
</s>
<s>
Introduction_NN1 In_II recent_JJ years_NNT2 ,_, there_EX has_VHZ been_VBN wide_JJ interest_NN1 in_II controlling_VVG managers_NN2 ._. 
</s>
<s>
Agency_NN1 problems_NN2 have_VH0 been_VBN important_JJ contributors_NN2 to_II financial_JJ crises_NN2 ._. 
</s>
<s>
Considering_CS agency_NN1 relationships_NN2 ,_, the_AT central_JJ corporate_JJ governance_NN1 problem_NN1 is_VBZ how_RRQ managers_NN2 are_VBR controlled_VVN ._. 
</s>
<s>
There_EX are_VBR several_DA2 mechanisms_NN2 of_IO corporate_JJ governance_NN1 ,_, such_II21 as_II22 legal_JJ protection_NN1 ,_, boards_NN2 ,_, codes_NN2 ,_, and_CC auditors_NN2 ,_, all_DB of_IO which_DDQ serve_VV0 to_TO reduce_VVI agency_NN1 problems_NN2 ._. 
</s>
<s>
Because_II21 of_II22 a_AT1 number_NN1 of_IO special_JJ characteristics_NN2 ,_, the_AT corporate_JJ governance_NN1 mechanisms_NN2 are_VBR used_JJ to_II varying_JJ degrees_NN2 in_II different_JJ countries_NN2 ._. 
</s>
<s>
For_REX21 example_REX22 Keiretsu_NP1 (_( i.e._REX cross-_JJ ownership_NN1 )_) is_VBZ common_JJ in_II Japan_NP1 ._. 
</s>
<s>
The_AT corporate_JJ governance_NN1 mechanisms_NN2 are_VBR created_VVN to_TO add_VVI value_NN1 to_II shareholders_NN2 ._. 
</s>
<s>
Nevertheless_RR ,_, the_AT lack_NN1 or_CC failure_NN1 of_IO corporate_JJ governance_NN1 mechanisms_NN2 will_VM destroy_VVI shareholders_NN2 wealth_NN1 ._. 
</s>
<s>
(_( Thomsen_NN1 2009_MC ,_, 41-42_MCMC ._. )_) 
</s>
<s>
The_AT separation_NN1 of_IO ownership_NN1 and_CC control_NN1 gives_VVZ rise_NN1 to_II agency_NN1 problems_NN2 between_II the_AT agents_NN2 and_CC the_AT principals_NN2 ,_, as_CSA stated_VVN by_II Fama_NP1 and_CC Jensen_NP1 (_( 1983_MC )_) ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO control_VVI resulting_JJ agency_NN1 problems_NN2 ,_, corporations_NN2 separate_VV0 management_NN1 and_CC control_NN1 ._. 
</s>
<s>
Despite_II the_AT separation_NN1 ,_, the_AT questions_NN2 remains_VVZ why_RRQ financial_JJ scandals_NN2 still_RR take_VV0 place_NN1 one_MC1 after_II another_DD1 ._. 
</s>
<s>
The_AT corporate_JJ governance_NN1 mechanisms_NN2 are_VBR needed_VVN to_TO reduce_VVI agency_NN1 problems_NN2 ._. 
</s>
<s>
Fundamentally_RR good_JJ corporate_JJ governance_NN1 consists_VVZ of_IO tailoring_VVG these_DD2 mechanisms_NN2 to_II the_AT individual_JJ firm_NN1 ._. 
</s>
<s>
It_PPH1 enhances_VVZ and_CC creates_VVZ value_NN1 (_( Thomsen_NP1 2009_MC ,_, 41_MC ,_, 240_MC )_) ._. 
</s>
<s>
It_PPH1 is_VBZ vital_JJ to_TO answer_VVI questions_NN2 :_: which_DDQ CG_NP1 mechanisms_NN2 have_VH0 failed_VVN in_II the_AT most_RGT recent_JJ financial_JJ scandal_NN1 and_CC what_DDQ could_VM have_VHI been_VBN done_VDN to_TO prevent_VVI it_PPH1 ?_? 
</s>
<s>
The_AT method_NN1 being_VBG used_VVN is_VBZ a_AT1 descriptive_JJ case_NN1 study_NN1 ._. 
</s>
<s>
The_AT research_NN1 comprises_VVZ an_AT1 intensive_JJ analysis_NN1 of_IO the_AT most_RGT recent_JJ accounting_NN1 scandal_NN1 ,_, Olympus_NP1 ._. 
</s>
<s>
The_AT data_NN consists_VVZ of_IO Olympus_NP1 's_GE interim_NN1 and_CC year-end_JJ reports_NN2 ,_, newspaper_NN1 articles_NN2 and_CC interviews_NN2 ._. 
</s>
<s>
The_AT news_NN1 paper_NN1 articles_NN2 are_VBR collected_VVN from_II financial_JJ papers_NN2 ,_, such_II21 as_II22 Reuters_NP1 ,_, New_NP1 York_NP1 Times_NNT2 ,_, Bloomberg_NP1 and_CC Financial_JJ Times_NNT2 ._. 
</s>
<s>
The_AT articles_NN2 contain_VV0 straight_JJ quotations_NN2 from_II Olympus_NP1 's_GE management_NN1 considering_II the_AT events_NN2 taken_VVN palace_NN1 during_II the_AT accounting_NN1 fraud_NN1 ._. 
</s>
<s>
All_DB the_AT interviewees_NN2 were_VBDR working_VVG for_IF or_CC otherwise_RR linked_VVN to_II Olympus_NP1 at_II the_AT time_NNT1 of_IO the_AT scandal_NN1 ._. 
</s>
<s>
The_AT paper_NN1 aims_VVZ to_TO produce_VVI conservative_JJ generalizations_NN2 from_II the_AT case_NN1 study_NN1 ,_, for_REX21 example_REX22 "_" if_CS it_PPH1 is_VBZ valid_JJ for_IF this_DD1 case_NN1 ,_, it_PPH1 is_VBZ valid_JJ for_IF all_RR (_( or_CC many_DA2 )_) cases_NN2 "_" or_CC in_II negative_JJ form_NN1 "_" if_CS it_PPH1 is_VBZ not_XX valid_JJ for_IF this_DD1 case_NN1 ,_, then_RT it_PPH1 is_VBZ not_XX valid_JJ for_IF any_RR (_( or_CC only_RR few_DA2 )_) cases_NN2 ._. "_" 
</s>
<s>
Accounting_VVG scandals_NN2 have_VH0 shaken_VVN the_AT world_NN1 in_II the_AT early_JJ 21st_MD century_NNT1 ._. 
</s>
<s>
They_PPHS2 arise_VV0 with_IW the_AT disclosure_NN1 of_IO misdeeds_NN2 by_II trusted_JJ executives_NN2 ._. 
</s>
<s>
The_AT scandals_NN2 indicate_VV0 that_CST some_DD corporate_JJ governance_NN1 mechanisms_NN2 have_VH0 failed_VVN ._. 
</s>
<s>
The_AT purpose_NN1 of_IO this_DD1 paper_NN1 is_VBZ to_TO explore_VVI which_DDQ corporate_JJ governance_NN1 mechanisms_NN2 tend_VV0 to_TO fail_VVI in_II accounting_VVG scandals_NN2 and_CC how_RRQ to_TO prevent_VVI these_DD2 scandals_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ important_JJ to_TO point_VVI out_RP which_DDQ factors_NN2 led_VVN to_II accounting_VVG scandals_NN2 and_CC how_RRQ to_TO prevent_VVI them_PPHO2 ,_, since_CS the_AT abuse_NN1 ,_, for_REX21 example_REX22 earnings_NN2 management_NN1 ,_, can_VM be_VBI completely_RR legal_JJ or_CC quasi_RG legal_JJ ._. 
</s>
<s>
The_AT structure_NN1 of_IO this_DD1 paper_NN1 is_VBZ as_CSA follows_VVZ ._. 
</s>
<s>
Chapter_NN1 2_MC defines_VVZ corporate_JJ governance_NN1 in_II this_DD1 particular_JJ context_NN1 and_CC presents_VVZ the_AT most_RGT widely-used_JJ corporate_JJ governance_NN1 theory_NN1 ,_, agency_NN1 theory_NN1 ._. 
</s>
<s>
Chapter_NN1 3_MC lists_VVZ the_AT mechanisms_NN2 of_IO corporate_JJ governance_NN1 ,_, which_DDQ all_DB serve_VV0 to_TO mitigate_VVI agency_NN1 problems_NN2 ._. 
</s>
<s>
Chapter_NN1 4_MC focuses_VVZ on_II Japanese_JJ corporate_JJ governance_NN1 and_CC its_APPGE special_JJ characteristics_NN2 ._. 
</s>
<s>
Chapter_NN1 5_MC provides_VVZ background_NN1 information_NN1 about_II a_AT1 financial_JJ scheme_NN1 designed_VVN for_IF privileged_JJ customers_NN2 ._. 
</s>
<s>
Chapter_NN1 6_MC highlights_VVZ issues_NN2 of_IO Japanese_JJ corporate_JJ governance_NN1 through_II the_AT case_NN1 Olympus_NN1 ._. 
</s>
<s>
Chapter_NN1 7_MC analyzes_VVZ the_AT issues_NN2 and_CC provides_VVZ solutions_NN2 ._. 
</s>
<s>
Chapter_NN1 8_MC draws_VVZ conclusions_NN2 and_CC suggestions_NN2 for_IF further_JJR research._NNU 2_MC ._. 
</s>
<s>
Agency_NN1 Problems_NN2 and_CC Corporate_JJ Governance_NN1 2.1_MC Defining_VVG Corporate_JJ Governance_NN1 There_EX are_VBR many_DA2 different_JJ definitions_NN2 of_IO corporate_JJ governance_NN1 ._. 
</s>
<s>
This_DD1 paper_NN1 follows_VVZ the_AT generally_RR accepted_JJ definition_NN1 by_II Cadbury_NP1 (_( 1992_MC )_) ._. 
</s>
<s>
Corporate_JJ governance_NN1 is_VBZ `_" the_AT system_NN1 by_II which_DDQ companies_NN2 are_VBR directed_VVN and_CC controlled'_NN1 ._. 
</s>
<s>
The_AT reason_NN1 behind_II this_DD1 system_NN1 is_VBZ to_TO ensure_VVI value_NN1 creation_NN1 (_( Thomsen_NP1 2008_MC ,_, 240_MC )_) ._. 
</s>
<s>
2.2_MC ._. 
</s>
<s>
Agency_NN1 Theory_NN1 The_AT theory_NN1 of_IO the_AT firms_NN2 suggests_VVZ that_DD1 firm_NN1 exist_VV0 and_CC make_VV0 decisions_NN2 in_BCL21 order_BCL22 to_TO maximize_VVI their_APPGE profits_NN2 ._. 
</s>
<s>
Good_JJ management_NN1 is_VBZ vital_JJ to_II economic_JJ efficiency_NN1 ,_, productivity_NN1 ,_, firm_JJ performance_NN1 ,_, and_CC social_JJ welfare_NN1 ._. 
</s>
<s>
(_( Thomsen_NN1 2008_MC ,_, 21_MC )_) ._. 
</s>
<s>
Therefore_RR owners_NN2 (_( shareholders_NN2 )_) hire_VV0 executives_NN2 to_TO manage_VVI companies_NN2 on_II their_APPGE behalf_NN1 (_( Thomsen_NP1 2008_MC ,_, 17_MC )_) ._. 
</s>
<s>
According_II21 to_II22 Ross_NP1 (_( 1973_MC )_) "_" an_AT1 agency_NN1 relationship_NN1 has_VHZ arisen_VVN between_II two_MC (_( or_CC more_RRR )_) parties_NN2 when_RRQ one_PN1 ,_, designated_VVN as_II the_AT agent_NN1 ,_, acts_VVZ for_IF ,_, or_CC on_II31 behalf_II32 of_II33 ,_, or_CC as_II a_AT1 representative_NN1 for_IF the_AT other_JJ ,_, designated_VVD the_AT principal_NN1 ,_, in_II a_AT1 particular_JJ domain_NN1 of_IO decision_NN1 problems_NN2 "_" ._. 
</s>
<s>
Agency_NN1 problems_NN2 arise_VV0 because_CS the_AT agents_NN2 (_( managers_NN2 )_) do_VD0 not_XX always_RR act_VVI in_II the_AT interests_NN2 of_IO the_AT principal_NN1 (_( shareholders_NN2 )_) (_( Thomsen_NP1 2008_MC ,_, 31_MC )_) ._. 
</s>
<s>
2.3_MC ._. 
</s>
<s>
Moral_JJ Hazard_NN1 and_CC Adverse_JJ Selection_NN1 According_II21 to_II22 Holmstrm_NP1 a_AT1 problem_NN1 of_IO moral_JJ hazard_NN1 may_VM arise_VVI when_RRQ individuals_NN2 engage_VV0 in_II risk_NN1 sharing_VVG under_II conditions_NN2 such_CS21 that_CS22 their_APPGE privately_RR taken_VVN actions_NN2 affect_VV0 the_AT probability_NN1 distribution_NN1 of_IO the_AT outcome_NN1 ._. 
</s>
<s>
The_AT source_NN1 of_IO this_DD1 moral_JJ hazard_NN1 is_VBZ an_AT1 asymmetry_NN1 of_IO information_NN1 among_II individuals_NN2 that_CST results_NN2 because_CS individual_JJ actions_NN2 can_VM not_XX be_VBI observed_VVN and_CC hence_RR contracted_VVN upon_II by_II the_AT principal_NN1 (_( Holmstrm_NP1 1979,2_MC )_) ._. 
</s>
<s>
Hidden_JJ knowledge_NN1 adverse_JJ selection_NN1 occurs_VVZ when_RRQ there_EX is_VBZ some_DD element_NN1 in_II the_AT situation_NN1 which_DDQ is_VBZ known_VVN to_II the_AT agent_NN1 but_CCB not_XX to_II the_AT principal_NN1 ._. 
</s>
<s>
(_( Thomsen_NN1 2008_MC ,_, 34_MC )_) ._. 
</s>
<s>
A_AT1 timeline_NN1 can_VM be_VBI drawn_VVN to_TO distinguish_VVI between_II these_DD2 information_NN1 problems_NN2 ._. 
</s>
<s>
Adverse_JJ selection_NN1 problems_NN2 tend_VV0 to_TO occur_VVI before_II the_AT principal_NN1 is_VBZ to_TO make_VVI a_AT1 decision_NN1 and_CC moral_JJ hazard_NN1 problems_NN2 tend_VV0 to_TO occur_VVI after_II the_AT decision_NN1 ._. 
</s>
<s>
(_( Thomsen_NN1 2008_MC ,_, 32_MC ._. )_) 
</s>
<s>
According_II21 to_II22 Thomsen_NP1 (_( 2008_MC )_) two_MC important_JJ tasks_NN2 are_VBR needed_VVN to_TO complete_VVI in_BCL21 order_BCL22 to_TO ensure_VVI good_JJ management_NN1 of_IO the_AT company_NN1 ,_, the_AT most_RGT important_JJ task_NN1 in_II corporate_JJ governance_NN1 ._. 
</s>
<s>
Selection_NN1 includes_VVZ hiring_VVG the_AT right_JJ managers_NN2 and_CC replacing_VVG bad_JJ ones_NN2 ,_, if_CS necessary_JJ ._. 
</s>
<s>
The_AT problem_NN1 behind_II selection_NN1 is_VBZ adverse_JJ selection_NN1 ._. 
</s>
<s>
The_AT second_MD task_NN1 is_VBZ motivation_NN1 ._. 
</s>
<s>
Management_NN1 should_VM be_VBI encouraged_VVN to_TO do_VDI their_APPGE best_JJT through_II incentives_NN2 and_CC monitoring_NN1 ._. 
</s>
<s>
The_AT key_JJ problem_NN1 here_RL is_VBZ moral_JJ hazard._NNU 3_MC ._. 
</s>
<s>
The_AT Mechanisms_NN2 of_IO Corporate_JJ Governance_NN1 Considering_II agency_NN1 relationships_NN2 ,_, the_AT central_JJ corporate_JJ governance_NN1 problem_NN1 is_VBZ how_RRQ managers_NN2 are_VBR controlled_VVN ._. 
</s>
<s>
Thomsen_NP1 (_( 2008_MC )_) has_VHZ listed_VVN the_AT most_RGT important_JJ corporate_JJ governance_NN1 mechanisms_NN2 :_: moral_JJ standards_NN2 ,_, reputation_NN1 and_CC trust_NN1 ,_, legal_JJ protection_NN1 ,_, large_JJ owners_NN2 ,_, shareholder_NN1 pressure_NN1 ,_, boards_NN2 ,_, creditor_NN1 monitoring_NN1 incentive_NN1 systems_NN2 ,_, auditors_NN2 ,_, analysts_NN2 ,_, takeovers_NN2 ,_, competition_NN1 ,_, managerial_JJ labour_NN1 market_NN1 ,_, codes_NN2 ,_, and_CC media_NN pressure_NN1 ._. 
</s>
<s>
They_PPHS2 all_DB serve_VV0 to_TO mitigate_VVI agency_NN1 problems_NN2 and_CC ensure_VVI that_CST managers_NN2 manage_VV0 the_AT company_NN1 in_II shareholders_NN2 best_RRT interest_VV0 ._. 
</s>
<s>
Thomsen_NP1 (_( 2008_MC )_) argues_VVZ that_CST "_" good_JJ corporate_JJ governance_NN1 essentially_RR consists_VVZ of_IO tailoring_VVG these_DD2 mechanisms_NN2 to_II the_AT individual_JJ firm_NN1 ._. "_" 
</s>
<s>
4.1_MC ._. 
</s>
<s>
Ethics_NN as_II a_AT1 Corporate_JJ Governance_NN1 Mechanism_NN1 Thomsen_NP1 (_( 2008_MC )_) defines_VVZ ethical_JJ codes_NN2 as_II a_AT1 set_NN1 of_IO principles_NN2 which_DDQ govern_VV0 economic_JJ behavior_NN1 and_CC which_DDQ may_VM function_VVI as_II a_AT1 correction_NN1 to_TO market_VVI and_CC policy_NN1 failures_NN2 as_II31 well_II32 as_II33 failure_NN1 of_IO the_AT prevailing_JJ social_JJ ethic_NN1 to_TO achieve_VVI socially_RR optimal_JJ outcomes_NN2 and_CC distinguishes_VVZ ethical_JJ business_NN1 codes_NN2 adopted_VVN by_II an_AT1 individual_JJ corporation_NN1 from_II general_JJ ethical_JJ codes_NN2 expressed_VVN in_II the_AT prevailing_JJ social_JJ ethic_NN1 ._. 
</s>
<s>
Ethical_JJ business_NN1 codes_NN2 should_VM be_VBI consisted_VVN with_IW profit_NN1 maximization_NN1 ._. 
</s>
<s>
However_RRQV the_AT codes_NN2 can_VM limit_VVI the_AT range_NN1 of_IO acceptable_JJ activities_NN2 ,_, and_CC be_VBI considered_VVN to_TO be_VBI inconsistent_JJ with_IW profit_NN1 maximization_NN1 since_CS a_AT1 profit_NN1 maximizing_VVG firm_NN1 will_VM offer_VVI the_AT same_DA opportunities_NN2 for_IF profit_NN1 as_CSA an_AT1 ethically-_JJ constrained_JJ firm_NN1 ._. 
</s>
<s>
Moreover_RR the_AT additional_JJ opportunities_NN2 may_VM arise_VVI from_II the_AT option_NN1 to_TO be_VBI unethical_JJ ._. 
</s>
<s>
An_AT1 implication_NN1 is_VBZ that_DD1 business_NN1 managers_NN2 may_VM find_VVI it_PPH1 in_II their_APPGE interest_NN1 to_TO mimic_VVI ethical_JJ behavior_NN1 to_II the_AT extent_NN1 that_CST the_AT public_NN1 can_VM not_XX distinguish_VVI between_II honesty_NN1 and_CC dishonesty_NN1 ._. 
</s>
<s>
Harrington_NP1 (_( 1989_MC )_) and_CC Frank_NP1 (_( 1989_MC )_) state_VV0 that_CST it_PPH1 will_VM be_VBI interest_NN1 of_IO the_AT profit_NN1 maximizing_VVG firm_JJ to_TO signal_VVI a_AT1 commitment_NN1 to_II ethical_JJ values_NN2 if_CS signaling_VVG costs_NN2 are_VBR small_JJ and_CC if_CS this_DD1 is_VBZ perceived_VVN to_TO have_VHI a_AT1 positive_JJ financial_JJ effect_NN1 ._. 
</s>
<s>
By_II preventing_VVG illegal_JJ activities_NN2 ethical_JJ business_NN1 codes_NN2 can_VM add_VVI value_NN1 and_CC improve_VVI social_JJ well_JJ being_NN1 if_CS they_PPHS2 concentrate_VV0 on_II issues_NN2 which_DDQ are_VBR specific_JJ to_II individual_JJ firm._NNU 4_MC ._. 
</s>
<s>
Corporate_JJ Governance_NN1 in_II Japan_NP1 Charkham_NP1 (_( 1995_MC )_) argues_VVZ that_CST Japanese_JJ corporate_JJ governance_NN1 is_VBZ shaped_VVN by_II mutual_JJ obligations_NN2 between_II the_AT company_NN1 and_CC its_APPGE employee_NN1 ,_, a_AT1 strong_JJ corporate_JJ family_NN1 feeling_NN1 ,_, and_CC decision_NN1 based_VVN on_II consensus_NN1 and_CC social_JJ responsibility_NN1 ._. 
</s>
<s>
Japanese_JJ corporate_JJ governance_NN1 differs_VVZ from_II continental_JJ Europe_NP1 ,_, UK_NP1 and_CC US_NP1 ._. 
</s>
<s>
Special_JJ characteristics_NN2 include_VV0 Keiretsus_NP1 (_( company_NN1 groups_NN2 )_) ,_, bank_NN1 finance_NN1 ,_, the_AT board_NN1 system_NN1 ,_, employee_NN1 relations_NN2 ,_, government_NN1 intervention_NN1 ,_, incentive_NN1 pay_NN1 ,_, and_CC company_NN1 law_NN1 ._. 
</s>
<s>
Keiretsus_NN1 are_VBR the_AT dominant_JJ ownership_NN1 mode_NN1 ,_, especially_RR for_IF large_JJ listed_JJ companies_NN2 ._. 
</s>
<s>
Companies_NN2 form_VV0 a_AT1 large_JJ company_NN1 group_NN1 ._. 
</s>
<s>
The_AT companies_NN2 hold_VV0 plenty_PN of_IO shares_NN2 in_II each_PPX221 other_PPX222 to_TO prevent_VVI hostile_JJ takeovers_NN2 ._. 
</s>
<s>
Japanese_JJ companies_NN2 use_VV0 rather_RG bank_NN1 finance_NN1 than_CSN equity_NN1 finance_NN1 ._. 
</s>
<s>
The_AT main_JJ banks_NN2 are_VBR reported_VVN to_TO play_VVI a_AT1 leading_JJ role_NN1 in_II many_DA2 Keiretsus_NN1 ._. 
</s>
<s>
The_AT board_NN1 system_NN1 is_VBZ one_MC1 tier_NN1 ._. 
</s>
<s>
(_( Thomsen_NN1 2008_MC ,_, 200-201_MCMC ._. )_) 
</s>
<s>
Shareholders_NN2 elect_VV0 the_AT board_NN1 ,_, which_DDQ appoints_VVZ the_AT executives_NN2 ._. 
</s>
<s>
The_AT difference_NN1 to_II two_MC tier_NN1 board_NN1 system_NN1 is_VBZ that_CST there_EX is_VBZ no_AT supervisory_JJ board_NN1 which_DDQ evaluates_VVZ company_NN1 performance_NN1 ._. 
</s>
<s>
One_MC1 tier_NN1 boards_NN2 can_VM run_VVI the_AT company_NN1 on_II their_APPGE own_DA ._. 
</s>
<s>
(_( Thomsen_NN1 2008_MC ,_, 67_MC ._. )_) 
</s>
<s>
However_RR ,_, according_II21 to_II22 Aoki_NP1 (_( 1988_MC )_) the_AT banks_NN2 step_VV0 in_RP and_CC lead_VV0 rescue_NN1 operation_NN1 in_II times_NNT2 of_IO crises_NN2 ._. 
</s>
<s>
Labor_NN1 markets_NN2 are_VBR inflexible_JJ and_CC employee_NN1 relations_NN2 are_VBR characterized_VVN by_II long-term_JJ ,_, often_RR lifetime_NNT1 employment_NN1 ._. 
</s>
<s>
Japanese_JJ managers_NN2 tend_VV0 to_TO work_VVI in_II the_AT same_DA company_NN1 throughout_II their_APPGE entire_JJ careers_NN2 ._. 
</s>
<s>
Employees_NN2 in_II the_AT same_DA company_NN1 are_VBR usually_RR members_NN2 of_IO the_AT same_DA enterprise_NN1 union_NN1 ,_, not_XX trade_NN1 unions_NN2 ._. 
</s>
<s>
Incentive_NN1 pay_NN1 level_NN1 is_VBZ lower_JJR than_CSN in_II the_AT US_NP1 and_CC it_PPH1 is_VBZ seems_VVZ to_TO be_VBI determined_VVN more_RRR by_II seniority_NN1 than_CSN performance_NN1 ._. 
</s>
<s>
However_RR ,_, company-wide_JJ bonus_NN1 systems_NN2 for_IF all_DB employees_NN2 provide_VV0 incentives_NN2 ._. 
</s>
<s>
Government_NN1 intervention_NN1 plays_VVZ a_AT1 key_JJ role_NN1 in_II Japanese_JJ society_NN1 ._. 
</s>
<s>
For_REX21 example_REX22 large_JJ parts_NN2 of_IO Japanese_JJ businesses_NN2 are_VBR protected_VVN from_II international_JJ competition_NN1 by_II tariffs_NN2 ._. 
</s>
<s>
Company_NN1 law_NN1 is_VBZ in_II the_AT civil_JJ law_NN1 tradition_NN1 ._. 
</s>
<s>
Japan_NP1 scores_VVZ highly_RR on_II formal_JJ measures_NN2 of_IO investor_NN1 protection_NN1 ,_, but_CCB lacks_VVZ on_II level_NN1 of_IO shareholder_NN1 influence_NN1 ._. 
</s>
<s>
For_REX21 example_REX22 Japanese_JJ companies_NN2 are_VBR famous_JJ for_IF holding_VVG their_APPGE annual_JJ meetings_NN2 on_II the_AT same_DA day_NNT1 and_CC keeping_VVG them_PPHO2 short_JJ which_DDQ effectively_RR prevent_VV0 small_JJ shareholders_NN2 from_II attending_VVG to_II most_DAT of_IO them_PPHO2 ._. 
</s>
<s>
(_( Thomsen_NN1 2008_MC ,_, 201._MC )_) 5_MC ._. 
</s>
<s>
Tobashi_JJ Scheme_NN1 In_II April_NPM1 1992_MC The_AT New_NP1 York_NP1 Times_NNT2 published_VVD a_AT1 story_NN1 about_II a_AT1 financial_JJ scheme_NN1 designed_VVN for_IF privileged_JJ customers_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ so_RG well_RR known_VVN in_II the_AT Japanese_JJ stock_NN1 market_NN1 that_CST it_PPH1 has_VHZ a_AT1 nickname_NN1 ,_, Tobashi_NP1 ,_, or_CC "_" flying_NN1 "_" ._. 
</s>
<s>
"_" An_AT1 official_NN1 of_IO the_AT Daiwa_NP1 Securities_NN2 Company_NN1 ,_, Japan_NP1 's_GE second-largest_JJT brokerage_NN1 house_NN1 ,_, had_VHD approached_VVN a_AT1 prominent_JJ corporation_NN1 ,_, Tokyu_NP1 Department_NN1 Store_NN1 ,_, and_CC proposed_VVD that_CST Tokyu_NP1 pay_NN1 90.5_MC billion_NNO yen_NN (_( about_RG $675_NNU million_NNO )_) for_IF securities_NN2 whose_DDQGE market_NN1 value_NN1 was_VBDZ only_RR 30_MC billion_NNO yen_NN ._. 
</s>
<s>
According_II21 to_II22 Tokyu_NP1 ,_, Daiwa_NP1 promised_VVD it_PPH1 would_VM repurchase_NN1 the_AT securities_NN2 later_RRR ,_, at_II a_AT1 price_NN1 that_CST would_VM guarantee_VVI Tokyu_NN1 a_AT1 small_JJ profit_NN1 ._. "_" 
</s>
<s>
In_II other_JJ words_NN2 a_AT1 broker_NN1 spares_VVZ a_AT1 customer_NN1 ,_, whose_DDQGE securities_NN2 have_VH0 dropped_VVN in_II value_NN1 ,_, from_II having_VHG to_TO show_VVI the_AT losses_NN2 in_II its_APPGE balance_NN1 sheet_NN1 by_II arranging_VVG another_DD1 customer_NN1 to_TO purchase_VVI these_DD2 securities_NN2 at_II an_AT1 unrealistically_RR high_JJ price_NN1 ._. 
</s>
<s>
When_CS the_AT accounting_NN1 period_NN1 is_VBZ about_RPK to_TO end_VVI ,_, a_AT1 new_JJ purchaser_NN1 is_VBZ persuaded_VVN to_TO go_VVI along_II21 with_II22 an_AT1 increasingly_RR inflated_JJ price_NN1 ._. 
</s>
<s>
The_AT broker_NN1 guarantees_VVZ a_AT1 profit_NN1 no_DDQV31 matter_DDQV32 what_DDQV33 happen_VV0 to_II the_AT market_NN1 value_NN1 of_IO the_AT securities_NN2 ._. 
</s>
<s>
In_II the_AT ideal_JJ world_NN1 the_AT stocks_NN2 "_" fly_VV0 "_" from_II account_NN1 to_II account_NN1 until_CS the_AT market_NN1 rises_VVZ enough_RR and_CC the_AT market_NN1 value_NN1 of_IO the_AT securities_NN2 is_VBZ finally_RR the_AT same_DA as_CSA the_AT last_MD rigged_VVD trade_NN1 ._. 
</s>
<s>
However_RRQV this_DD1 was_VBDZ not_XX the_AT case_NN1 ._. 
</s>
<s>
In_II April_NPM1 1992_MC the_AT New_NP1 York_NP1 Times_NNT2 wrote_VVD :_: `_" ..._... 
</s>
<s>
Daiwa_NP1 refused_VVD to_II repurchase_NN1 the_AT securities_NN2 at_II the_AT promised_JJ value_NN1 ._. '_" 
</s>
<s>
The_AT Tokyo_NP1 stock_NN1 market_NN1 crashed_VVD when_RRQ the_AT largest_JJT investors_NN2 pulled_VVD their_APPGE investments_NN2 back_RP ._. 
</s>
<s>
The_AT New_NP1 York_NP1 Times_NNT2 had_VHD doubts_NN2 about_II the_AT Tokyo_NP1 stock_NN1 market_NN1 :_: "_" No_PN121 one_PN122 knows_VVZ if_CS the_AT Tokyo_NP1 Stock_NN1 Exchange_NN1 will_VM return_VVI to_II what_DDQ it_PPH1 was_VBDZ before_II its_APPGE slow-_JJ motion_NN1 collapse_NN1 ._. "_" 
</s>
<s>
5.1_MC ._. 
</s>
<s>
"_" Bing_VVG Bang_NN1 Reforms_NN2 of_IO Accounting_VVG Standards_NN2 "_" Japanese_JJ Accounting_NN1 Standards_NN2 have_VH0 been_VBN greatly_RR changed_VVN ._. 
</s>
<s>
Japan_NP1 's_GE financial_JJ regulator_NN1 finally_RR outlawed_VVN Tobashi_JJ schemes_NN2 in_II 2000_MC ._. 
</s>
<s>
New_JJ market-to-market_JJ accounting_NN1 rules_NN2 were_VBDR introduced_VVN ,_, requiring_VVG companies_NN2 to_TO account_VVI for_IF securities_NN2 at_II market_NN1 value_NN1 instead_II21 of_II22 at_II their_APPGE purchase_NN1 price_NN1 ._. 
</s>
<s>
(_( Layne_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2011_MC ,_, 4_MC )_) Large_JJ companies_NN2 have_VH0 also_RR been_VBN supposed_JJ to_TO disclose_VVI consolidated_JJ financial_JJ statements_NN2 as_CSA formal_JJ documents_NN2 and_CC introduce_VV0 consolidated_JJ statements_NN2 of_IO cash_NN1 flow_NN1 and_CC tax_NN1 consequences_NN2 accounting_VVG ._. 
</s>
<s>
The_AT purpose_NN1 of_IO these_DD2 changes_NN2 was_VBDZ to_TO push_VVI the_AT management_NN1 of_IO Japanese_JJ enterprise_NN1 to_TO shift_VVI their_APPGE focus_NN1 from_II unrealized_JJ profits/losses_NN2 to_II cash_NN1 flow_NN1 generated_VVN by_II their_APPGE assets_NN2 and_CC improve_VV0 efficiency_NN1 of_IO capital_NN1 ._. 
</s>
<s>
The_AT chances_NN2 were_VBDR also_RR expected_VVN to_TO attract_VVI foreign_JJ enterprises_NN2 and_CC investors_NN2 to_TO make_VVI transactions_NN2 in_II capital_NN1 markets_NN2 in_II Japan_NP1 ._. 
</s>
<s>
(_( Asaki_NP1 2006_MC ,_, 235._MC )_) 6_MC ._. 
</s>
<s>
The_AT Decades-long_JJ Cover-up_NN1 of_IO Losses_NN2 at_II Olympus_NP1 Corporation_NN1 In_II November_NPM1 2011_MC The_AT Financial_JJ Times_NNT2 published_VVD a_AT1 story_NN1 which_DDQ shone_VVD a_AT1 harsh_JJ light_NN1 on_II Japanese_JJ corporate_JJ governance_NN1 ._. 
</s>
<s>
Olympus_NN1 ,_, established_VVD 1919_MC ,_, the_AT world_NN1 's_GE biggest_JJT maker_NN1 of_IO endoscopes_NN2 and_CC a_AT1 top_JJ producer_NN1 of_IO cameras_NN2 ,_, admitted_VVD wrongdoing_NN1 for_IF the_AT first_MD time_NNT1 in_II a_AT1 scandal_NN1 involving_VVG more_DAR than_CSN $1.7_NNU billion_NNO in_II acquisition-related_JJ payments_NN2 and_CC advisory_JJ fees_NN2 ._. 
</s>
<s>
The_AT money_NN1 was_VBDZ used_VVN secretly_RR to_TO cover_VVI losses_NN2 on_II investments_NN2 dating_VVG back_RP to_II the_AT early_JJ 1990s_MC2 ._. 
</s>
<s>
According_II21 to_II22 the_AT Wall_NP1 Street_NNL1 Journal_NN1 the_AT scandal_NN1 was_VBDZ "_" one_MC1 of_IO the_AT biggest_JJT and_CC longest-running_JJT loss-hiding_JJ arrangements_NN2 in_II Japanese_JJ corporate_JJ history_NN1 ._. "_" 
</s>
<s>
At_II its_APPGE center_NN1 were_VBDR an_AT1 inner_JJ circle_NN1 of_IO Olympus_NN1 executives_NN2 ,_, who_PNQS sought_VVD to_TO delay_VVI the_AT reckoning_NN1 of_IO the_AT losses_NN2 ._. 
</s>
<s>
Olympus_NP1 practiced_VVD the_AT art_NN1 of_IO "_" tobashi_NN2 "_" ,_, accounting_NN1 maneuvers_VVZ that_CST would_VM make_VVI problems_NN2 "_" fly_VV0 away_RL "_" of_IO balance_NN1 sheets._NNU 6.1_MC ._. 
</s>
<s>
Financial_JJ Engineering_NN1 In_II the_AT 1980s_MC2 investment_NN1 bankers_NN2 gained_VVD riches_NN2 and_CC new_JJ respect_NN1 in_II Japanese_JJ society_NN1 as_II the_AT Nikkei_NP1 stock_NN1 average_NN1 roared_VVD to_II new_JJ heights_NN2 ._. 
</s>
<s>
However_RRQV manufacturer_NN1 exporters_NN2 ,_, the_AT engine_NN1 of_IO the_AT Japanese_JJ economic_JJ miracle_NN1 ,_, did_VDD not_XX want_VVI to_TO tie_VVI their_APPGE fate_NN1 to_II the_AT mercurial_JJ financial_JJ markets_NN2 ._. 
</s>
<s>
That_DD1 mindset_NN1 changed_VVN in_II September_NPM1 1985_MC ,_, when_CS major_JJ industrial_JJ powers_NN2 agreed_VVD to_TO devaluate_VVI the_AT dollar_NNU1 ._. 
</s>
<s>
The_AT yen_NN sharply_RR appreciated_VVN ,_, cutting_VVG Olympus_NN1 operating_NN1 profits_NN2 in_II half_DB ._. 
</s>
<s>
Suddenly_RR the_AT idea_NN1 of_IO using_VVG financial_JJ engineering_NN1 ,_, called_VVN zaitech_NN1 ,_, to_TO pad_VVI earnings_NN2 by_II non-operating_JJ income_NN1 made_VVD sense_NN1 to_II Toshiro_NP1 Shimoyama_NP1 ,_, Olympus_NP1 president_NN1 ,_, 1984-1993_MCMC ._. 
</s>
<s>
"_" Until_CS last_MD year_NNT1 I_PPIS1 was_VBDZ against_II zaitech_NN1 ,_, but_CCB conditions_NN2 are_VBR changed_VVN "_" ,_, he_PPHS1 told_VVD Nikkei_NP1 Industrial_JJ Daily_NN1 in_II November_NPM1 1986_MC ._. 
</s>
<s>
In_II consequence_NN1 Hideo_NP1 Yamada_NP1 and_CC Hisashi_NP1 Mori_NP1 ,_, managers_NN2 in_II Olympus_NP1 finance_NN1 department_NN1 ,_, started_VVD pouring_JJ money_NN1 in_RP to_II riskier_JJR securities_NN2 through_II Akio_NP1 Nakagawa_NP1 ,_, famous_JJ Japanese_JJ banker_NN1 ._. 
</s>
<s>
"_" Nagasawa_NN1 was_VBDZ a_AT1 genious_JJ when_CS it_PPH1 came_VVD to_II persuading_VVG people_NN in_II the_AT finance_NN1 department_NN1 ._. "_" 
</s>
<s>
Said_VVD an_AT1 ex-colleque_NN1 ._. 
</s>
<s>
"_" He_PPHS1 convinced_VVD them_PPHO2 it_PPH1 was_VBDZ the_AT job_NN1 of_IO finance_NN1 department_NN1 to_TO create_VVI more_DAR money_NN1 by_II investing_VVG the_AT company_NN1 's_GE funds_NN2 ,_, and_CC told_VVD them_PPHO2 they_PPHS2 should_VM do_VDI that_DD1 aggressively_RR because_CS it_PPH1 was_VBDZ their_APPGE core_NN1 business_NN1 ._. "_" 
</s>
<s>
On_II the_AT final_JJ trading_NN1 day_NNT1 of_IO 1989_MC the_AT Nikkei_NP1 average_NN1 peaked_VVN and_CC went_VVN to_II a_AT1 tail_NN1 spin_NN1 ,_, losing_VVG nearly_RR 40_MC percent_NNU the_AT following_JJ ._. 
</s>
<s>
Stock_NN1 portfolios_NN2 across_II the_AT corporate_JJ sector_NN1 were_VBDR crushed_VVN ._. 
</s>
<s>
By_II the_AT mid-1990s_MC2 the_AT losses_NN2 had_VHD grown_VVN to_II tens_MC2 of_IO billions_NNO2 yen_VV0 ._. 
</s>
<s>
The_AT financial_JJ health_NN1 of_IO the_AT company_NN1 was_VBDZ threatened_VVN ._. 
</s>
<s>
To_TO hide_VVI the_AT deficit_NN1 ,_, Olympus_NP1 signed_VVD a_AT1 contract_NN1 with_IW Credit_NN1 Suisse_NP1 First_MD Boston_NP1 for_IF tobashi_NN2 scheme_VV0 to_TO cover_VVI up_RP securities_NN2 losses_NN2 in_II 1992_MC ._. 
</s>
<s>
Bad_JJ securities_NN2 were_VBDR sold_VVN by_II book_NN1 value_NN1 to_TO trust_VVI of_IO Olympus_NP1 's_GE balance_NN1 sheet_NN1 ._. 
</s>
<s>
(_( Layne_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2011_MC ,_, 3_MC ._. )_) 
</s>
