<s>
Finnish_JJ Film_NN1 Director_NN1 Agreements_NN2 I_MC1 INTRODUCTION_NN1 The_AT director_NN1 of_IO a_AT1 film_NN1 ,_, documentary_NN1 or_CC fiction_NN1 ,_, is_VBZ an_AT1 author_NN1 in_II the_AT meaning_NN1 of_IO the_AT Finnish_JJ Copyright_NN1 Act_NN1 and_CC has_VHZ in_II31 accordance_II32 with_II33 the_AT said_JJ act_NN1 copyright_NN1 to_II his/her_APPGE artistic_JJ work_NN1 ._. 
</s>
<s>
A_AT1 film_NN1 is_VBZ an_AT1 artistic_JJ vision_NN1 of_IO its_APPGE director_NN1 ._. 
</s>
<s>
With_IW a_AT1 film_NN1 director_NN1 agreement_NN1 ,_, the_AT director_NN1 assigns_VVZ the_AT economical_JJ rights_NN2 to_II such_DA artistic_JJ work_NN1 to_II a_AT1 producer_NN1 against_II compensation_NN1 ._. 
</s>
<s>
Pursuant_II21 to_II22 the_AT principle_NN1 of_IO contractual_JJ freedom_NN1 ,_, the_AT parties_NN2 are_VBR free_JJ to_TO agree_VVI on_II the_AT terms_NN2 of_IO such_DA agreement_NN1 (_( unless_CS compulsory_JJ terms_NN2 are_VBR deriving_VVG from_II the_AT law_NN1 )_) ._. 
</s>
<s>
The_AT recent_JJ development_NN1 in_II the_AT film_NN1 industry_NN1 has_VHZ been_VBN rapid_JJ and_CC the_AT importance_NN1 of_IO the_AT industry_NN1 has_VHZ grown_VVN during_II the_AT past_JJ years_NNT2 ._. 
</s>
<s>
This_DD1 applies_VVZ also_RR to_II the_AT contract_NN1 praxis_NN1 ._. 
</s>
<s>
Therefore_RR more_RRR and_CC more_RGR legal_JJ aid_NN1 is_VBZ needed_VVN by_II the_AT contract_NN1 parties_NN2 when_CS negotiating_VVG on_II the_AT making_NN1 of_IO a_AT1 new_JJ film_NN1 ._. 
</s>
<s>
The_AT Association_NN1 of_IO Finnish_JJ Film_NN1 Directors_NN2 (_( in_II Finnish_JJ :_: Suomen_NP1 elokuvaohjaajaliitto_NN1 SELO_NN1 ry._NNU )_) acts_VVZ in_II Finland_NP1 as_II a_AT1 promoter_NN1 of_IO the_AT interests_NN2 of_IO Finnish_JJ film_NN1 directors_NN2 and_CC provides_VVZ support_NN1 to_II its_APPGE members_NN2 in_II agreement_NN1 negotiations_NN2 ._. 
</s>
<s>
An_AT1 important_JJ part_NN1 of_IO the_AT legal_JJ consultation_NN1 consists_VVZ of_IO the_AT film_NN1 director_NN1 model_NN1 agreements_NN2 for_IF fiction_NN1 ,_, television_NN1 and_CC short_JJ films_NN2 as_RG well_RR as_CSA for_IF documentaries_NN2 providing_VVG a_AT1 starting_NN1 point_NN1 for_IF the_AT agreement_NN1 negotiations_NN2 ._. 
</s>
<s>
Secondly_RR ,_, the_AT model_NN1 agreement_NN1 serves_VVZ as_II a_AT1 director_NN1 's_GE check_NN1 list_NN1 of_IO things_NN2 to_TO be_VBI carefully_RR considered_VVN ,_, when_CS agreeing_VVG on_II the_AT assignment_NN1 of_IO copyright_NN1 ._. 
</s>
<s>
Thus_RR ,_, model_NN1 agreements_NN2 are_VBR intended_VVN to_TO serve_VVI as_RG practical_JJ tools_NN2 for_IF the_AT members_NN2 of_IO SELO_NN1 in_II their_APPGE agreement_NN1 negotiations_NN2 ._. 
</s>
<s>
The_AT models_NN2 have_VH0 been_VBN continuously_RR updated_VVN to_TO better_RRR reflect_VVI changes_NN2 in_II both_DB2 legal_JJ framework_NN1 as_II31 well_II32 as_II33 market_NN1 practices_NN2 ._. 
</s>
<s>
Due_II21 to_II22 the_AT limited_JJ financial_JJ means_NN of_IO SELO_NP1 ,_, it_PPH1 has_VHZ proven_VVN difficult_JJ to_TO employ_VVI required_JJ resources_NN2 in_II active_JJ monitoring_NN1 of_IO the_AT development_NN1 in_II the_AT field_NN1 of_IO copyright_NN1 and_CC contract_NN1 law_NN1 at_II the_AT national_JJ and_CC particularly_RR at_II the_AT international_JJ level_NN1 ._. 
</s>
<s>
Furthermore_RR ,_, no_AT academic_JJ analysis_NN1 of_IO the_AT content_NN1 of_IO the_AT model_NN1 agreements_NN2 has_VHZ been_VBN carried_VVN out_RP ._. 
</s>
<s>
This_DD1 paper_NN1 analyses_VVZ one_MC1 of_IO the_AT film_NN1 director_NN1 model_NN1 agreements_NN2 and_CC its_APPGE clauses_NN2 relating_VVG to_II the_AT assignment_NN1 of_IO copyright_NN1 ._. 
</s>
<s>
Moreover_RR ,_, the_AT paper_NN1 identifies_VVZ the_AT actual_JJ legal_JJ framework_NN1 (_( the_AT Finnish_JJ Copyright_NN1 Act_NN1 ,_, in_II specific_JJ )_) behind_II those_DD2 agreement_NN1 clauses_NN2 ,_, and_CC also_RR clarifies_VVZ the_AT current_JJ praxis_NN1 in_II the_AT field_NN1 ,_, which_DDQ has_VHZ undoubtedly_RR influenced_VVN the_AT formulation_NN1 of_IO the_AT model_NN1 agreement_NN1 ._. 
</s>
<s>
Furthermore_RR ,_, this_DD1 paper_NN1 is_VBZ also_RR intended_VVN to_TO serve_VVI a_AT1 more_RGR extensive_JJ study_NN1 of_IO the_AT European_JJ film_NN1 director_NN1 agreement_NN1 models_NN2 to_TO be_VBI carried_VVN out_RP as_II a_AT1 comparative_JJ study_NN1 of_IO different_JJ agreement_NN1 clauses_NN2 and_CC practices_NN2 ._. 
</s>
<s>
Hence_RR ,_, this_DD1 paper_NN1 also_RR contributes_VVZ to_II understanding_VVG how_RRQ the_AT current_JJ Finnish_JJ model_NN1 agreement_NN1 is_VBZ structured_VVN creating_VVG a_AT1 base_NN1 to_II the_AT such_DA subsequent_JJ study_NN1 ._. 
</s>
<s>
The_AT findings_NN2 are_VBR assumed_VVN to_TO suggest_VVI that_CST the_AT clauses_NN2 in_II the_AT model_NN1 agreement_NN1 derive_VV0 largely_RR from_II the_AT law_NN1 but_CCB are_VBR also_RR motivated_VVN by_II political_JJ goals_NN2 and_CC trade-union-like_JJ recommendations_NN2 for_IF the_AT members_NN2 of_IO SELO_NP1 ,_, financial_JJ circumstances_NN2 ,_, as_II31 well_II32 as_II33 the_AT market_NN1 practices_NN2 ._. 
</s>
<s>
The_AT paper_NN1 is_VBZ organised_VVN into_II seven_MC sections_NN2 ._. 
</s>
<s>
The_AT introductory_JJ section_NN1 is_VBZ followed_VVN by_II a_AT1 literature_NN1 review_NN1 in_II section_NN1 II_MC ._. 
</s>
<s>
The_AT theoretical_JJ framework_NN1 is_VBZ presented_VVN in_II section_NN1 III_MC and_CC the_AT material_NN1 used_VVN as_II a_AT1 basis_NN1 for_IF this_DD1 term_NN1 paper_NN1 is_VBZ described_VVN in_II section_NN1 IV_MC ._. 
</s>
<s>
The_AT analysis_NN1 part_NN1 in_II section_NN1 V_ZZ1 consists_VVZ of_IO the_AT overview_NN1 of_IO the_AT Finnish_JJ film_NN1 director_NN1 model_NN1 agreement_NN1 as_RG well_RR as_CSA takes_VVZ a_AT1 closer_JJR look_NN1 to_II the_AT individual_JJ clauses_NN2 of_IO the_AT model_NN1 agreement_NN1 ._. 
</s>
<s>
Discussion_NN1 is_VBZ opened_VVN and_CC proposal_NN1 for_IF later_JJR study_NN1 is_VBZ presented_VVN in_II section_NN1 VI_MC ._. 
</s>
<s>
The_AT concluding_JJ section_NN1 VII_MC summarises_VVZ the_AT findings_NN2 and_CC defines_VVZ the_AT paper_NN1 's_GE contributions_NN2 to_II the_AT above-mentioned_JJ later_JJR study_NN1 ._. 
</s>
<s>
II_MC LITERATURE_NN1 REVIEW_NN1 Assignment_NN1 of_IO copyright_NN1 is_VBZ included_VVN as_II a_AT1 standard_JJ chapter_NN1 in_II every_AT1 general_JJ academic_JJ book_NN1 on_II intellectual_JJ property_NN1 rights1_FO ._. 
</s>
<s>
The_AT legal_JJ issues_NN2 relating_VVG to_II copyright_NN1 assignments_NN2 are_VBR not_XX that_DD1 complex_NN1 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, there_RL exist_VV0 some_DD legal_JJ praxis_NN1 that_CST define_VV0 the_AT director_NN1 as_II a_AT1 primary_JJ author_NN1 of_IO a_AT1 cinematographic_JJ work2_FO ._. 
</s>
<s>
The_AT interpretation_NN1 of_IO contracts_NN2 may_VM ,_, however_RR ,_, be_VBI subject_II21 to_II22 disputes_NN2 ._. 
</s>
<s>
The_AT contract_NN1 law_NN1 derives_VVZ its_APPGE norms_NN2 from_II 1_MC1 ._. 
</s>
<s>
mandatory_JJ legislation_NN1 ,_, 2._MC contract_NN1 terms_NN2 and_CC related_JJ material_NN1 ,_, 3._MC non-mandatory_JJ legislation_NN1 and_CC comparative_JJ contractual_JJ principles_NN2 ,_, and_CC 4._MC market_NN1 practices_NN2 ._. 
</s>
<s>
Although_CS no_AT binding_JJ norms_NN2 on_II the_AT interpretation_NN1 of_IO contracts_NN2 exist_VV0 ,_, the_AT academic_JJ literature_NN1 provides_VVZ some_DD rules_NN2 for_IF this_DD1 ._. 
</s>
<s>
The_AT interpretation_NN1 of_IO contracts_NN2 may_VM base_VVI on_II the_AT material_NN1 produced_VVN by_II the_AT parties_NN2 as_II31 well_II32 as_II33 their_APPGE actions_NN2 and_CC their_APPGE common_JJ purpose_NN1 ._. 
</s>
<s>
The_AT interpretation_NN1 can_VM also_RR base_VVI on_II the_AT actual_JJ wording_NN1 of_IO the_AT agreement_NN1 ._. 
</s>
<s>
The_AT normative_JJ interpretation_NN1 derives_VVZ from_II the_AT wording_NN1 of_IO the_AT acts_NN2 ._. 
</s>
<s>
A_AT1 film_NN1 director_NN1 agreement_NN1 can_VM be_VBI analysed_VVN by_II using_VVG such_DA academic_JJ literature_NN1 on_II intellectual_JJ property_NN1 assignments_NN2 as_CSA well_RR as_CSA general_JJ contract_NN1 law_NN1 ._. 
</s>
<s>
However_RR ,_, it_PPH1 should_VM be_VBI kept_VVN in_II mind_NN1 that_CST the_AT film_NN1 director_NN1 agreement_NN1 is_VBZ not_XX only_RR a_AT1 contract_NN1 on_II copyright_NN1 assignment_NN1 but_CCB also_RR it_PPH1 is_VBZ an_AT1 employment_NN1 contract_NN1 (_( see_VV0 section_NN1 V._NNU on_II compensation_NN1 structure_NN1 )_) ._. 
</s>
<s>
Thirdly_RR ,_, a_AT1 relevant_JJ employment_NN1 legislation_NN1 and_CC literature_NN1 may_VM thus_RR have_VHI relevance_NN1 ._. 
</s>
<s>
In_II31 addition_II32 to_II33 academic_JJ literature_NN1 ,_, the_AT material_NN1 produced_VVN in_II the_AT field_NN1 (_( e.g._REX SELO_NP1 's_GE different_JJ reports_NN2 and_CC statements_NN2 to_II legislative_JJ reforms_NN2 )_) plays_VVZ an_AT1 important_JJ role_NN1 in_II analysing_VVG the_AT agreement_NN1 model_NN1 ._. 
</s>
<s>
As_II the_AT term_NN1 paper_NN1 analyses_VVZ a_AT1 specific_JJ agreement_NN1 ,_, the_AT aforementioned_JJ existing_JJ literature_NN1 serves_VVZ only_RR as_CSA theoretical_JJ framework_NN1 ._. 
</s>
<s>
However_RR ,_, the_AT emphasis_NN1 of_IO this_DD1 term_NN1 paper_NN1 is_VBZ on_II intellectual_JJ property_NN1 issues_NN2 ,_, the_AT general_JJ contract_NN1 law_NN1 issues_NN2 and_CC the_AT theoretical_JJ rules_NN2 on_II interpretation_NN1 of_IO contracts_NN2 are_VBR not_XX presented_VVN in_II more_RGR detailed_JJ level_NN1 ._. 
</s>
<s>
The_AT theoretical_JJ framework_NN1 on_II41 the_II42 part_II43 of_II44 the_AT copyright_NN1 is_VBZ presented_VVN more_DAR detail_NN1 in_II the_AT following_JJ section_NN1 ._. 
</s>
<s>
III_MC THEORETICAL_JJ FRAMEWORK_NN1 III.1_FO Protection_NN1 of_IO the_AT Film_NN1 Director_NN1 's_GE Right_JJ to_TO the_AT Work_NN1 by_II Copyright_NN1 The_AT director_NN1 of_IO a_AT1 film_NN1 is_VBZ an_AT1 author_NN1 of_IO the_AT final_JJ artistic_JJ work_NN1 and_CC his/her_APPGE right_NN1 to_TO get_VVI compensated_VVN for_IF the_AT exploitation_NN1 of_IO such_DA work_NN1 is_VBZ protected_VVN by_II copyright_NN1 ._. 
</s>
<s>
In_II fact_NN1 ,_, copyright_NN1 was_VBDZ originally_RR intended_VVN for_IF the_AT protection_NN1 of_IO authors_NN2 ,_, artists_NN2 and_CC composers_NN2 and_CC the_AT primarily_RR functions_NN2 of_IO copyright_NN1 laws_NN2 even_RR today_RT is_VBZ "_" to_TO protect_VVI from_II exploitation_NN1 by_II other_JJ people_NN the_AT fruits_NN2 of_IO a_AT1 someone_PN1 's_GE work_NN1 ,_, labour_NN1 ,_, skill_NN1 or_CC taste_NN1 "_" ._. 
</s>
<s>
As_CSA other_JJ IP_NN1 rights_NN2 ,_, a_AT1 copyright_NN1 is_VBZ thus_RR an_AT1 exclusive_JJ right_NN1 giving_VVG the_AT holder_NN1 of_IO a_AT1 copyright_NN1 right_NN1 to_TO prevent_VVI others_NN2 from_II using_VVG his/her_APPGE work_NN1 without_IW an_AT1 adequate_JJ consent_NN1 ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, the_AT copyright_NN1 protection_NN1 is_VBZ "_" given_VVN by_II making_VVG it_PPH1 unlawful_JJ ,_, as_CSA an_AT1 "_" infringement_NN1 of_IO a_AT1 copyright_NN1 ,_, "_" to_TO reproduce_VVI or_CC copy_NN1 ,_, for_REX21 example_REX22 ,_, any_DD "_" literary_JJ ,_, dramatic_JJ ,_, musical_JJ or_CC artistic_JJ work_NN1 "_" without_IW permission_NN1 of_IO the_AT author_NN1 ._. 
</s>
<s>
In_RR21 short_RR22 ,_, copyright_NN1 protection_NN1 provides_VVZ that_CST the_AT author_NN1 has_VHZ a_AT1 right_NN1 to_TO get_VVI paid_VVN for_IF his/her_APPGE work_NN1 ._. 
</s>
<s>
In_II Finland_NP1 ,_, an_AT1 author_NN1 is_VBZ granted_VVN the_AT exclusivity_NN1 to_II the_AT work_NN1 by_II the_AT virtue_NN1 of_IO Section_NN1 2_MC of_IO the_AT Copyright_NN1 Act_NN1 ._. 
</s>
<s>
The_AT copyright_NN1 is_VBZ granted_VVN to_II the_AT author_NN1 of_IO an_AT1 artistic_JJ work_NN1 ._. 
</s>
<s>
This_DD1 means_VVZ that_CST the_AT copyright_NN1 is_VBZ always_RR originally_RR granted_VVN to_II a_AT1 natural_JJ person_NN1 at_II the_AT moment_NN1 the_AT work_NN1 is_VBZ created_VVN ._. 
</s>
<s>
The_AT copyright_NN1 ,_, in_II contrast_NN1 to_II the_AT industrial_JJ rights_NN2 ,_, does_VDZ not_XX require_VVI registration_NN1 in_BCL21 order_BCL22 to_TO be_VBI effective_JJ toward_II others_NN2 ._. 
</s>
<s>
Copyright_NN1 may_VM also_RR be_VBI granted_VVN simultaneously_RR to_II many_DA2 people_NN ._. 
</s>
<s>
A_AT1 "_" cinematographic_JJ work_NN1 "_" is_VBZ the_AT most_RGT common_JJ example_NN1 of_IO a_AT1 work_NN1 that_CST has_VHZ been_VBN created_VVN by_II multiple_JJ individuals_NN2 ,_, namely_REX a_AT1 director_NN1 ,_, scriptwriter_NN1 ,_, composer_NN1 of_IO the_AT music_NN1 ,_, photographer_NN1 ,_, scenographer_NN1 etc_RA ._. 
</s>
<s>
It_PPH1 is_VBZ controversial_JJ ,_, whom_PNQO of_IO these_DD2 are_VBR to_TO be_VBI considered_VVN as_CSA "_" authors_NN2 "_" ._. 
</s>
<s>
Consequently_RR ,_, it_PPH1 is_VBZ not_XX clear_JJ ,_, whether_CSW a_AT1 cinematographic_JJ work_NN1 is_VBZ a_AT1 joint_JJ work_NN1 (_( as_CSA defined_VVN in_II Section_NN1 6_MC )_) or_CC compilation_NN1 work_NN1 (_( Section_NN1 5_MC )_) ._. 
</s>
<s>
However_RR ,_, as_CSA a_AT1 copyright_NN1 is_VBZ a_AT1 transferable_JJ right10_FO ,_, defining_VVG the_AT authors_NN2 of_IO a_AT1 film_NN1 is_VBZ not_XX that_DD1 big_JJ problem_NN1 in_II practice_NN1 as_CSA ,_, based_VVN on_II the_AT aforedescribed_JJ ,_, one_PN1 could_VM think_VVI ._. 
</s>
<s>
This_DD1 is_VBZ because_CS the_AT individuals_NN2 participating_VVG in_II the_AT film_NN1 making_VVG transfer_VVI their_APPGE rights_NN2 for_IF the_AT normal_JJ exploitation_NN1 of_IO the_AT film_NN1 to_II a_AT1 producer_NN1 ._. 
</s>
<s>
Copyright_NN1 consists_VVZ of_IO group_NN1 of_IO rights_NN2 that_CST can_VM be_VBI divided_VVN into_II economic_JJ rights_NN2 and_CC moral_JJ rights_NN2 ._. 
</s>
<s>
Economic_JJ rights_NN2 include_VV0 1_MC1 )_) making_VVG copies_NN2 of_IO the_AT work_NN1 ,_, and_CC 2_MC )_) making_VVG it_PPH1 available_JJ to_II the_AT public_NN1 ._. 
</s>
<s>
Moral_JJ rights_NN2 aim_VV0 to_TO protect_VVI the_AT author_NN1 's_GE person_NN1 ._. 
</s>
<s>
Those_DD2 include_VV0 1_MC1 )_) the_AT right_NN1 of_IO paternity_NN1 and_CC 2_MC )_) the_AT right_NN1 to_II the_AT integrity_NN1 of_IO the_AT work_NN1 ._. 
</s>
<s>
The_AT term_NN1 for_IF the_AT copyright_NN1 protection_NN1 of_IO "_" ..._... a_AT1 cinematographic_JJ work_NN1 shall_VM subsist_VVI until_II seventy_MC years_NNT2 have_VH0 elapsed_VVN from_II the_AT year_NNT1 of_IO the_AT death_NN1 of_IO the_AT last_MD of_IO the_AT following_JJ to_TO survive_VVI :_: the_AT principal_JJ director_NN1 ,_, the_AT author_NN1 of_IO the_AT screenplay_NN1 ,_, the_AT author_NN1 of_IO the_AT dialogue_NN1 and_CC the_AT composer_NN1 of_IO music_NN1 specifically_RR created_VVN for_IF use_NN1 in_II the_AT cinematographic_JJ work_NN1 ._. "_" 
</s>
<s>
IV_MC MATERIAL_NN1 The_AT qualitative_JJ data_NN consists_VVZ of_IO SELO_NP1 's_GE model_NN1 agreement14_FO as_II31 well_II32 as_II33 legislation_NN1 (_( acts_NN2 and_CC preparatory_JJ works_NN )_) ,_, and_CC related_JJ academic_JJ literature_NN1 (_( see_VV0 section_NN1 II_MC )_) ._. 
</s>
<s>
This_DD1 data_NN is_VBZ supplemented_VVN by_II information_NN1 obtained_VVN from_II the_AT interviews_NN2 on_II the_AT market_NN1 practices_NN2 with_IW SELO_NP1 's_GE executive_NN1 director_NN1 and_CC lawyer_NN1 ._. 
</s>
<s>
V_ZZ1 ANALYSIS_NN1 V.1_FO The_AT General_JJ Structure_NN1 of_IO the_AT Finnish_JJ Film_NN1 Director_NN1 Model_NN1 Agreement_NN1 As_CSA copyright_NN1 is_VBZ intangible_JJ right_NN1 i.e._REX there_EX is_VBZ nothing_PN1 tangible_JJ assets_NN2 that_CST a_AT1 film_NN1 director_NN1 could_VM sell_VVI ,_, transactions_NN2 concerning_II copyright_NN1 are_VBR entirely_RR contractual_JJ matters_NN2 ._. 
</s>
<s>
The_AT contract_NN1 parties_NN2 have_VH0 therefore_RR an_AT1 extensive_JJ freedom_NN1 to_TO agree_VVI on_II the_AT terms_NN2 of_IO the_AT assignment_NN1 of_IO the_AT film_NN1 director_NN1 's_GE prevention_NN1 right_NN1 ._. 
</s>
<s>
The_AT contract_NN1 clauses_NN2 of_IO an_AT1 IP_NN1 related_JJ contract_NN1 can_VM be_VBI divided_VVN roughly_RR to_II those_DD2 relating_VVG to_II intellectual_JJ property_NN1 law_NN1 (_( e.g._REX copyright_NN1 )_) ,_, civil_JJ law_NN1 (_( the_AT rights_NN2 and_CC obligations_NN2 of_IO the_AT contract_NN1 parties_NN2 )_) ,_, and_CC procedure_NN1 (_( i.e._REX dispute_NN1 resolution_NN1 )_) as_II31 well_II32 as_II33 international_JJ private_JJ law_NN1 (_( when_CS contract_NN1 has_VHZ an_AT1 international_JJ dimension_NN1 )_) ._. 
</s>
<s>
The_AT Finnish_JJ film_NN1 director_NN1 model_NN1 agreement_NN1 consist_VV0 of_IO the_AT following_JJ sections_NN2 :_: 1_MC1 )_) The_AT object_NN1 of_IO the_AT agreement_NN1 ,_, 2_MC )_) the_AT rights_NN2 and_CC obligations_NN2 of_IO the_AT director_NN1 ,_, 3_MC )_) assigned_VVD rights_NN2 ,_, 4_MC )_) compensations_NN2 ,_, 5_MC )_) the_AT moral_JJ rights_NN2 of_IO the_AT director_NN1 ,_, 6_MC )_) the_AT obligations_NN2 of_IO the_AT producer_NN1 ,_, 7_MC )_) marketing_NN1 of_IO the_AT film_NN1 ,_, 8_MC )_) termination_NN1 of_IO the_AT agreement_NN1 ,_, 9_MC )_) jurisdiction_NN1 and_CC applicable_JJ law_NN1 ,_, and_CC 10_MC )_) signatures_NN2 ._. 
</s>
<s>
The_AT general_JJ terms_NN2 relating_VVG to_II the_AT contract_NN1 technique_NN1 in_II the_AT film_NN1 director_NN1 model_NN1 agreement_NN1 are_VBR the_AT defining_JJ of_IO the_AT contract_NN1 parties_NN2 (_( i.e._REX the_AT film_NN1 director_NN1 as_CSA assignor_NN1 and_CC the_AT producer_NN1 as_CSA assignee_NN1 )_) as_II31 well_II32 as_II33 the_AT signatures_NN2 part_NN1 including_II the_AT number_NN1 of_IO the_AT contract_NN1 copies_NN2 ,_, date_NN1 and_CC place_NN1 ._. 
</s>
<s>
Other_JJ information_NN1 of_IO technical_JJ nature_NN1 is_VBZ included_VVN e.g._REX in_II defining_VVG the_AT object_NN1 of_IO the_AT agreement_NN1 (_( e.g._REX the_AT material_NN1 the_AT film_NN1 shall_VM be_VBI filmed_VVN on_RP )_) ._. 
</s>
<s>
Clauses_NN2 under_II section_NN1 "_" jurisdiction_NN1 and_CC applicable_JJ law_NN1 "_" represent_VV0 procedural_JJ aspects_NN2 of_IO the_AT agreement_NN1 ._. 
</s>
<s>
More_RGR profound_JJ analysis_NN1 of_IO such_DA technical_JJ or_CC standard_JJ clauses_NN2 is_VBZ not_XX necessary_JJ in_II this_DD1 context_NN1 ._. 
</s>
<s>
V.2_FO Assigned_VVN Economic_JJ Rights_NN2 The_AT most_RGT essential_JJ clauses_NN2 in_II the_AT model_NN1 agreement_NN1 relate_VV0 to_II the_AT assigning_NN1 of_IO the_AT economic_JJ rights_NN2 ._. 
</s>
<s>
As_II the_AT contract_NN1 parties_NN2 can_VM freely_RR agree_VVI on_RP to_II what_DDQ extent_NN1 the_AT economic_JJ rights_NN2 are_VBR assigned_VVN to_II the_AT producer_NN1 ,_, the_AT rights_NN2 that_CST are_VBR not_XX expressly_RR mentioned_VVN in_II the_AT agreement_NN1 will_VM not_XX efficiently_RR assign_VVI to_II the_AT producer_NN1 but_CCB remain_VV0 with_IW the_AT original_JJ copyright_NN1 holder_NN1 i.e._REX the_AT director_NN1 ._. 
</s>
<s>
Pursuant_II21 to_II22 clause_NN1 3.1_MC of_IO the_AT model_NN1 agreement_NN1 "_" &lsqb;_( t_ZZ1 &rsqb;_) he_PPHS1 Director_NN1 assigns_VVZ to_II the_AT Producer_NN1 against_II compensation_NN1 agreed_VVN in_II this_DD1 agreement_NN1 the_AT economic_JJ rights_NN2 specified_VVN below_RL ._. "_" 
</s>
<s>
Pursuant_II21 to_II22 clause_NN1 3.2_MC "_" &lsqb;_( t_ZZ1 &rsqb;_) he_PPHS1 Producer_NN1 has_VHZ a_AT1 right_NN1 to_TO record_VVI the_AT Film_NN1 on_II film_NN1 or_CC on_II any_DD other_JJ material_NN1 ,_, show_NN1 and_CC distribute_VV0 the_AT Film_NN1 to_II the_AT public_NN1 ,_, make_VV0 copies_NN2 of_IO it_PPH1 and_CC transfer_VV0 it_PPH1 on_II another_DD1 record_NN1 ._. 
</s>
<s>
&lsqb;_( ....._... &rsqb;_) The_AT producer_NN1 will_VM have_VHI by_II virtue_NN1 of_IO this_DD1 agreement_NN1 rental_NN1 ,_, lending_VVG ,_, and_CC selling_VVG rights_NN2 to_II the_AT Film_NN1 ._. "_" 
</s>
<s>
Furthermore_RR ,_, "_" &lsqb;_( t_ZZ1 &rsqb;_) he_PPHS1 production_NN1 company_NN1 will_VM have_VHI a_AT1 right_NN1 to_TO make_VVI trailers_NN2 of_IO the_AT Film_NN1 ,_, advertisements_NN2 as_II31 well_II32 as_II33 corresponding_JJ marketing_NN1 and_CC press_VV0 materials_NN2 which_DDQ shall_VM be_VBI approved_VVN by_II the_AT Director_NN1 ._. "_" 
</s>
<s>
The_AT assignment_NN1 of_IO copyright_NN1 could_VM also_RR be_VBI formulated_VVN as_II an_AT1 "_" total_JJ assignment_NN1 "_" meaning_NN1 that_CST the_AT author_NN1 assigns_VVZ all_DB economic_JJ rights_NN2 to_II the_AT work_NN1 to_II the_AT assignee_NN1 covering_VVG all_DB forms_NN2 of_IO usage_NN1 ,_, even_RR the_AT future_JJ ones_NN2 ._. 
</s>
<s>
However_RR ,_, when_CS assigning_VVG all_DB economic_JJ rights_NN2 the_AT author_NN1 can_VM not_XX be_VBI aware_JJ of_IO all_DB rights_NN2 he/she_PPHS1 waives_VVZ and_CC what_DDQ the_AT agreement_NN1 really_RR means_VVZ to_II him/her_PPHO1 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, in_II the_AT situation_NN1 of_IO total_JJ assignment_NN1 the_AT author_NN1 will_VM loose_VVI the_AT right_NN1 to_II later_JJR compensation_NN1 on_II possible_JJ new_JJ forms_NN2 of_IO usage_NN1 by_II the_AT producer_NN1 ._. 
</s>
<s>
Consequently_RR ,_, the_AT model_NN1 agreement_NN1 lists_VVZ exclusively_RR the_AT permitted_JJ forms_NN2 of_IO usage_NN1 so_RR all_DB other_JJ ways_NN2 economically_RR benefit_VV0 from_II the_AT film_NN1 are_VBR left_VVN with_IW the_AT director_NN1 and_CC subject_II21 to_II22 further_JJR negotiations_NN2 ._. 
</s>
<s>
To_TO be_VBI on_II the_AT safe_JJ side_NN1 ,_, it_PPH1 is_VBZ stated_VVN in_II clause_NN1 3.5_MC of_IO the_AT model_NN1 agreement_NN1 that_CST "_" &lsqb;_( s_ZZ1 &rsqb;_) uch_VV0 rights_NN2 ,_, that_CST are_VBR not_XX expressly_RR assigned_VVN with_IW this_DD1 agreement_NN1 ,_, shall_VM remain_VVI with_IW the_AT Director_NN1 ._. "_" 
</s>
<s>
Also_RR ,_, "_" &lsqb;_( t_ZZ1 &rsqb;_) he_PPHS1 remake_VV0 rights_NN2 and_CC by-products_NN2 will_VM be_VBI agreed_VVN separately_RR ._. "_" 
</s>
<s>
The_AT door_NN1 is_VBZ left_JJ open_JJ for_IF the_AT director_NN1 to_TO get_VVI additional_JJ compensation_NN1 for_IF later_JJR usage_NN1 ._. 
</s>
<s>
The_AT producer_NN1 is_VBZ entitled_VVN to_TO further_RRR assign_VVI the_AT rights_NN2 and_CC obligations_NN2 that_CST are_VBR transferred_VVN to_II it_PPH1 provided_CS21 that_CS22 the_AT terms_NN2 of_IO the_AT agreement_NN1 shall_VM be_VBI complied_VVN and_CC the_AT director_NN1 will_VM be_VBI informed_VVN of_IO such_DA re-assignment_NN1 (_( clause_NN1 3.7_MC of_IO the_AT model_NN1 agreement_NN1 )_) ._. 
</s>
<s>
The_AT producer_NN1 's_GE right_JJ to_TO re-transfer_VVI the_AT copyright_NN1 is_VBZ subject_II21 to_II22 such_DA express_JJ agreement_NN1 as_CSA it_PPH1 is_VBZ otherwise_RR prohibited_VVN by_II the_AT Copyright_NN1 Act_NN1 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, the_AT producer_NN1 may_VM not_XX alter_VVI the_AT work_NN1 without_IW the_AT director_NN1 's_GE consent_NN1 ._. 
</s>
<s>
Therefore_RR it_PPH1 is_VBZ agreed_VVN in_II the_AT model_NN1 agreement_NN1 ,_, that_CST the_AT director_NN1 shall_VM approve_VVI the_AT new_JJ version_NN1 of_IO the_AT work_NN1 ,_, which_DDQ is_VBZ created_VVN upon_II transferring_VVG the_AT film_NN1 on_II other_JJ material23_FO ._. 
</s>
<s>
However_RR ,_, this_DD1 does_VDZ not_XX mean_VVI right_JJ to_TO alter_VVI the_AT work_NN1 in_II such_DA way_NN1 that_CST is_VBZ protected_VVN by_II the_AT director_NN1 's_GE moral_JJ rights_NN2 (_( see_VV0 below_RL )_) ._. 
</s>
<s>
V.2_FO The_AT Moral_JJ Rights_NN2 of_IO the_AT Director_NN1 The_AT moral_JJ rights_NN2 can_VM not_XX be_VBI efficiently_RR fully_RR assigned_VVN ._. 
</s>
<s>
This_DD1 means_VVZ that_CST even_RR the_AT copyright_NN1 has_VHZ been_VBN transferred_VVN ,_, the_AT transferee_NN1 will_VM still_RR have_VHI to_TO respect_VVI the_AT author_NN1 's_VBZ right_JJ of_IO paternity_NN1 and_CC the_AT right_NN1 to_II the_AT integrity_NN1 of_IO the_AT work.24_FO The_AT right_NN1 of_IO paternity_NN1 means_VVZ that_CST general_JJ adjustment_NN1 provision_NN1 is_VBZ added_VVN in_II the_AT Copyright_NN1 Act_NN1 in_BCL21 order_BCL22 to_TO protect_VVI an_AT1 author_NN1 from_II grossly_RR unfair_JJ contract_NN1 terms_NN2 ._. 
</s>
<s>
See_VV0 e.g._REX Haarman_NP1 (_( 1994_MC )_) ,_, p._NN1 71._MC the_AT name_NN1 of_IO the_AT author_NN1 shall_VM be_VBI stated_VVN when_CS copies_NN2 of_IO a_AT1 work_NN1 are_VBR made_VVN or_CC when_CS the_AT work_NN1 is_VBZ made_VVN available_JJ to_II the_AT public_NN1 ._. 
</s>
<s>
The_AT right_NN1 to_II the_AT integrity_NN1 of_IO the_AT work_NN1 bears_VVZ that_CST "_" &lsqb;_( a_ZZ1 &rsqb;_) work_NN1 may_VM not_XX be_VBI altered_VVN in_II a_AT1 manner_NN1 which_DDQ is_VBZ prejudicial_JJ to_II the_AT author_NN1 's_GE literary_JJ or_CC artistic_JJ reputation_NN1 ,_, or_CC to_II his_APPGE individuality_NN1 ;_; nor_CC may_VM it_PPH1 be_VBI made_VVN available_JJ to_II the_AT public_NN1 in_II such_DA a_AT1 form_NN1 or_CC context_NN1 as_CSA to_TO prejudice_VVI the_AT author_NN1 in_II the_AT manner_NN1 stated_VVD ._. "_" 
</s>
<s>
Although_CS the_AT moral_JJ rights_NN2 are_VBR directly_RR provided_VVN by_II the_AT virtue_NN1 of_IO the_AT law_NN1 and_CC as_CSA stated_VVN above_RL those_DD2 can_VM not_XX be_VBI fully_RR assigned_VVN ,_, the_AT moral_JJ rights_NN2 of_IO the_AT director_NN1 are_VBR also_RR written_VVN down_RP in_II the_AT model_NN1 agreement_NN1 ._. 
</s>
<s>
Clause_NN1 5.1_MC provides_VVZ that_CST "_" &lsqb;_( t_ZZ1 &rsqb;_) he_PPHS1 name_NN1 of_IO the_AT Director_NN1 shall_VM be_VBI stated_VVN when_CS showing_VVG the_AT to_II the_AT public_NN1 or_CC distributing_VVG the_AT Film_NN1 ,_, unless_CS otherwise_RR wanted_VVN by_II the_AT Director_NN1 ._. "_" 
</s>
<s>
The_AT later_JJR part_NN1 refers_VVZ to_II the_AT fact_NN1 that_CST the_AT right_NN1 of_IO paternity_NN1 include_VV0 also_RR the_AT right_NN1 to_TO have_VHI a_AT1 work_NN1 published_VVN anonymously_RR or_CC pseudonymously_RR ._. 
</s>
<s>
The_AT right_NN1 to_II the_AT integrity_NN1 of_IO the_AT work_NN1 is_VBZ stated_VVN in_II the_AT model_NN1 agreement_NN1 in_II the_AT form_NN1 that_CST "_" &lsqb;_( t_ZZ1 &rsqb;_) he_PPHS1 final_JJ form_NN1 of_IO the_AT Film_NN1 may_VM not_XX be_VBI altered_VVN nor_CC it_PPH1 may_VM be_VBI cut_VVN up_RP or_CC showed_VVD in_II parts_NN2 ,_, unless_CS otherwise_RR agreed_VVN ,_, without_IW the_AT Director_NN1 's_VBZ prior_RR written_VVN consent_NN1 ._. "_" 
</s>
<s>
In_RR21 addition_RR22 ,_, "_" &lsqb;_( t_ZZ1 &rsqb;_) he_PPHS1 Film_NN1 may_VM not_XX be_VBI showed_VVN or_CC distributed_VVN in_II such_DA contexts_NN2 which_DDQ can_VM be_VBI prejudicial_JJ to_II the_AT Director_NN1 's_GE artistic_JJ or_CC professional_JJ merits_NN2 or_CC reputation_NN1 ._. 
</s>
<s>
Thus_RR ,_, the_AT wording_NN1 of_IO the_AT latter_DA clause_NN1 derives_VVZ almost_RR identically_RR from_II the_AT law_NN1 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, the_AT interpretation_NN1 that_CST a_AT1 film_NN1 is_VBZ characteristically_RR an_AT1 artistic_JJ work_NN1 of_IO its_APPGE director_NN1 and_CC thus_RR relating_VVG strongly_RR to_II the_AT director_NN1 's_GE person_NN1 is_VBZ supported_VVN by_II the_AT wording_NN1 of_IO the_AT model_NN1 agreement_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ expressly_RR included_VVN in_II the_AT model_NN1 agreement_NN1 that_CST the_AT director_NN1 shall_VM have_VHI the_AT right_NN1 to_TO show_VVI the_AT film_NN1 to_II the_AT public_NN1 at_II festivals_NN2 and_CC corresponding_JJ non-_JJ commercial_JJ events_NN2 for_IF the_AT purpose_NN1 of_IO promoting_VVG his/_FU her_APPGE artistic_JJ career_NN1 ._. 
</s>
<s>
V.3_FO Compensation_NN1 It_PPH1 is_VBZ not_XX stipulated_VVN in_II the_AT Copyright_NN1 Act_NN1 that_CST what_DDQ kind_NN1 of_IO compensation_NN1 the_AT author_NN1 should_VM get_VVI against_II the_AT assignment_NN1 of_IO copyright_NN1 ._. 
</s>
<s>
Therefore_RR ,_, the_AT clauses_NN2 of_IO the_AT film_NN1 director_NN1 agreement_NN1 that_CST are_VBR most_RRT subject_II21 to_II22 the_AT outcome_NN1 of_IO the_AT negotiations_NN2 ,_, the_AT different_JJ goals_NN2 of_IO the_AT contract_NN1 parties_NN2 ,_, and_CC the_AT market_NN1 practices_NN2 are_VBR those_DD2 relating_VVG to_II the_AT compensation_NN1 ._. 
</s>
<s>
Should_VM the_AT producer_NN1 fail_VVI to_TO pay_VVI all_DB the_AT agreed_JJ compensations_NN2 ,_, the_AT assigned_JJ rights_NN2 shall_VM transfer_VVI back_RP to_II the_AT director_NN1 ._. 
</s>
<s>
The_AT recommendation_NN1 by_II SELO_NP1 included_VVD in_II the_AT model_NN1 agreement_NN1 for_IF the_AT film_NN1 director_NN1 's_GE total_JJ compensation_NN1 consists_VVZ of_IO 1_MC1 )_) salary_NN1 and_CC 2_MC )_) compensation_NN1 for_IF the_AT assignment_NN1 of_IO the_AT copyright_NN1 (_( royalties_NN2 )_) ._. 
</s>
<s>
The_AT third_MD part_NN1 of_IO the_AT compensation_NN1 consist_VV0 of_IO compensating_VVG the_AT travelling_NN1 and_CC mobile_JJ phone_NN1 expenses_NN2 that_CST occur_VV0 for_IF the_AT making_VVG the_AT film_NN1 ._. 
</s>
<s>
Furthermore_RR ,_, the_AT prices_NN2 granted_VVN for_IF the_AT film_NN1 shall_VM belong_VVI to_II the_AT director_NN1 ._. 
</s>
<s>
Film_NN1 contracts_NN2 are_VBR governed_VVN by_II Section_NN1 39_MC of_IO the_AT Copyright_NN1 Act_NN1 ._. 
</s>
<s>
Pursuant_II21 to_II22 the_AT said_JJ section_NN1 "_" transfer_NN1 of_IO the_AT right_NN1 to_TO make_VVI a_AT1 film_NN1 on_II the_AT basis_NN1 of_IO &lsqb;_( ..._... &rsqb;_) artistic_JJ work_NN1 shall_VM comprise_VVI the_AT right_NN1 to_TO make_VVI the_AT work_NN1 available_JJ to_II the_AT public_NN1 by_II showing_VVG the_AT film_NN1 in_II cinemas_NN2 ,_, on_II television_NN1 or_CC by_II any_DD other_JJ means_NN ,_, and_CC the_AT right_NN1 to_TO provide_VVI the_AT film_NN1 with_IW subtitles_NN2 and_CC to_TO dub_VVI the_AT film_NN1 in_II another_DD1 language_NN1 ._. "_" 
</s>
<s>
This_DD1 "_" filming_VVG right_RR "_" deriving_VVG directly_RR from_II the_AT law_NN1 has_VHZ been_VBN interpreted_VVN as_II a_AT1 minimum_JJ level_NN1 of_IO the_AT rights_NN2 to_TO be_VBI assigned_VVN to_II the_AT producer_NN1 and_CC it_PPH1 is_VBZ compensated_VVN with_IW the_AT salary_NN1 ._. 
</s>
<s>
The_AT salary_NN1 part_NN1 covers_VVZ also_RR the_AT director_NN1 's_GE work_NN1 related_VVN to_II prearrangements_NN2 ,_, filming_VVG period_NN1 ,_, afterworks_NN2 and_CC participation_NN1 in_II the_AT marketing_NN1 ._. 
</s>
<s>
The_AT amount_NN1 of_IO the_AT salary_NN1 is_VBZ subject_II21 to_II22 the_AT negotiations_NN2 and_CC therefore_RR left_JJ blanc_NN1 in_II the_AT model_NN1 agreement_NN1 ._. 
</s>
<s>
The_AT film_NN1 director_NN1 agreement_NN1 is_VBZ also_RR an_AT1 employment_NN1 contract_NN1 as_CSA there_EX is_VBZ an_AT1 employment_NN1 relationship_NN1 between_II the_AT director_NN1 and_CC the_AT producer_NN1 ._. 
</s>
<s>
Assigned_VVN rights_NN2 exceeding_VVG such_DA minimum_JJ level_NN1 shall_VM be_VBI subject_II21 to_II22 separate_JJ copyright_NN1 compensation_NN1 in_II a_AT1 form_NN1 of_IO e.g._REX royalties_NN2 ._. 
</s>
<s>
In_II31 accordance_II32 with_II33 the_AT model_NN1 agreement_NN1 ,_, the_AT producer_NN1 will_VM have_VHI to_TO pay_VVI royalties_NN2 on_II :_: distribution_NN1 to_II cinemas_NN2 eur_NN1 0.20_MC per_II viewer_NN1 after_II &lsqb;_( number_NN1 to_TO be_VBI agreed_VVN &rsqb;_) viewers_NN2 ,_, DVD_NP1 ,_, Blueray_NP1 ,_, VHS_NP1 or_CC other_JJ copy_NN1 sale_NN1 eur_NN1 0.60_MC per_II copy_NN1 ,_, foreign_JJ sale_NN1 5%_NNU of_IO the_AT gross_JJ income_NN1 gained_VVN by_II the_AT producer_NN1 ,_, and_CC other_JJ domestic_JJ sale_NN1 5%_NNU of_IO the_AT gross_JJ income_NN1 gained_VVN by_II the_AT producer_NN1 ._. 
</s>
<s>
In_RR21 short_RR22 ,_, distribution_NN1 right_NN1 is_VBZ not_XX included_VVN in_II the_AT minimum_JJ level_NN1 and_CC has_VHZ to_TO be_VBI separately_RR compensated_VVN for_IF the_AT director_NN1 ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO monitor_VVI the_AT right_JJ amount_NN1 of_IO royalties_NN2 ,_, the_AT director_NN1 should_VM always_RR be_VBI entitled_VVN to_TO receive_VVI a_AT1 copy_NN1 of_IO bookkeeping_NN1 materials_NN2 and_CC auditor_NN1 's_GE statement_NN1 concerning_II the_AT film_NN1 and_CC get_VV0 information_NN1 on_II agreements_NN2 relating_VVG to_II the_AT use_NN1 of_IO the_AT film_NN1 ._. 
</s>
<s>
This_DD1 right_NN1 is_VBZ covered_VVN by_II the_AT clause_NN1 4.3_MC of_IO the_AT model_NN1 agreement_NN1 ._. 
</s>
<s>
Against_II the_AT aforedescribed_JJ compensation_NN1 structure_NN1 it_PPH1 is_VBZ understandable_JJ ,_, that_DD1 SELO_NN1 has_VHZ objected_VVN the_AT legislative_JJ reform_NN1 of_IO taking_VVG employment_NN1 assumption37_FO in_II the_AT Copyright_NN1 Act_NN1 ._. 
</s>
<s>
The_AT royalties_NN2 make_VV0 an_AT1 important_JJ part_NN1 of_IO the_AT total_JJ compensation_NN1 and_CC as_II the_AT employment_NN1 relationship_NN1 with_IW the_AT producer_NN1 lasts_VVZ only_RR for_IF a_AT1 short_JJ term_NN1 ,_, the_AT royalties_NN2 provide_VV0 the_AT director_NN1 with_IW income_NN1 for_IF several_DA2 years_NNT2 (_( depending_II21 on_II22 the_AT economic_JJ success_NN1 of_IO that_DD1 film_NN1 )_) after_II the_AT termination_NN1 of_IO the_AT employment_NN1 ._. 
</s>
<s>
The_AT employment_NN1 assumption_NN1 would_VM deteriorate_VVI the_AT negotiation_NN1 position_NN1 of_IO a_AT1 film_NN1 director_NN1 by_II reducing_VVG the_AT produce_NN1 's_GE willingness_NN1 to_TO negotiate_VVI on_II separate_JJ compensations_NN2 for_IF the_AT transfer_NN1 of_IO copyright_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ also_RR important_JJ to_TO secure_VVI the_AT director_NN1 's_GE copyright_NN1 to_II the_AT work_NN1 in_II situations_NN2 where_RRQ the_AT agreement_NN1 is_VBZ ambiguous_JJ or_CC remains_VVZ silent_JJ ._. 
</s>
<s>
VI_MC DISCUSSION_NN1 The_AT trend_NN1 in_II the_AT film_NN1 director_NN1 agreement_NN1 negotiations_NN2 has_VHZ been_VBN that_CST the_AT agreement_NN1 models_NN2 introduced_VVN by_II the_AT producers_NN2 derives_VVZ from_II the_AT Anglo-Saxon_JJ contract_NN1 tradition_NN1 ._. 
</s>
<s>
When_CS a_AT1 Finnish_JJ film_NN1 director_NN1 agreement_NN1 is_VBZ build_NN1 on_II such_DA grounds_NN2 by_II translating_VVG a_AT1 foreign_JJ contract_NN1 into_II Finnish_JJ ,_, it_PPH1 is_VBZ possible_JJ that_CST the_AT final_JJ agreement_NN1 contains_VVZ provisions_NN2 that_CST are_VBR not_XX suitable_JJ to_II Finnish_JJ legal_JJ environment_NN1 ._. 
</s>
<s>
This_DD1 comes_VVZ up_RP especially_RR with_II31 regard_II32 to_II33 terminology_NN1 used_VVN in_II the_AT Anglo-Saxon_NN1 based_VVN contract_NN1 that_CST do_VD0 n't_XX necessarily_RR have_VHI counterwords_NN2 when_CS translated_VVN into_II Finnish_JJ ._. 
</s>
<s>
More_DAR alerting_NN1 is_VBZ that_CST also_RR the_AT legal_JJ concepts_NN2 included_VVN in_II such_DA contracts_NN2 may_VM be_VBI "_" legal_JJ aliens_NN2 "_" in_II domestic_JJ legal_JJ praxis_NN1 Consequently_RR ,_, the_AT risk_NN1 for_IF misunderstandings_NN2 and_CC disputes_NN2 increases_VVZ ._. 
</s>
<s>
SELO_NP1 's_GE model_NN1 agreement_NN1 can_VM be_VBI therefore_RR a_AT1 very_RG useful_JJ alternative_NN1 for_IF the_AT director_NN1 ,_, usually_RR representing_VVG the_AT weaker_JJR party_NN1 in_II agreement_NN1 negotiations_NN2 ,_, to_TO counteroffer_VVI for_IF the_AT producer_NN1 as_II a_AT1 starting_NN1 point_NN1 ._. 
</s>
<s>
And_CC although_CS this_DD1 would_VM not_XX be_VBI successful_JJ ,_, it_PPH1 could_VM be_VBI wise_JJ at_RR21 least_RR22 to_TO compare_VVI the_AT producer_NN1 's_GE suggestion_NN1 for_IF the_AT terms_NN2 to_II those_DD2 of_IO the_AT model_NN1 agreement_NN1 ._. 
</s>
<s>
The_AT European_JJ roof_NN1 organisation_NN1 for_IF the_AT film_NN1 director_NN1 associations_NN2 (_( FERA_NP1 )_) has_VHZ planned_VVN to_TO draft_VVI an_AT1 agreement_NN1 check_NN1 list_NN1 which_DDQ has_VHZ intended_VVN to_TO serve_VVI as_II a_AT1 general_JJ starting_NN1 level_NN1 for_IF film_NN1 director_NN1 agreements_NN2 in_II whole_NN1 of_IO Europe_NP1 ._. 
</s>
<s>
Thus_RR ,_, new_JJ material_NN1 for_IF a_AT1 comparative_JJ study_NN1 on_II European_NN1 copyright40_FO and_CC contract_NN1 culture_NN1 will_VM be_VBI available_JJ and_CC niche_NN1 for_IF a_AT1 later_JJR study_NN1 exists.41_FO At_II the_AT more_RGR practical_JJ level_NN1 ,_, a_AT1 harmonised_JJ European_JJ recommendation_NN1 strengthens_VVZ further_RRR the_AT director_NN1 's_GE negotiation_NN1 position_NN1 ._. 
</s>
<s>
VII_MC CONCLUSION_NN1 It_PPH1 has_VHZ been_VBN said_VVN ,_, that_CST a_AT1 good_JJ contract_NN1 is_VBZ one_PN1 that_CST neither_DD1 party_NN1 is_VBZ fully_RR content_JJ but_CCB both_RR parties_NN2 can_VM live_VVI with_IW ._. 
</s>
<s>
Thus_RR ,_, it_PPH1 should_VM be_VBI kept_VVN in_II mind_NN1 that_CST the_AT model_NN1 agreement_NN1 provided_VVN for_IF its_APPGE members_NN2 by_II the_AT Association_NN1 of_IO Finnish_JJ Film_NN1 Directors_NN2 (_( SELO_NP1 )_) is_VBZ just_RR a_AT1 recommendation_NN1 and_CC has_VHZ no_AT binding_JJ effect_NN1 in_II the_AT "_" inter_JJ partes_NN2 "_" negotiations_NN2 ._. 
</s>
<s>
Therefore_RR ,_, the_AT final_JJ film_NN1 director_NN1 agreement_NN1 may_VM be_VBI quite_RG different_JJ from_II the_AT model_NN1 agreement_NN1 and_CC at_RR21 least_RR22 partly_RR depend_VV0 on_II the_AT negotiation_NN1 positions_NN2 of_IO the_AT parties_NN2 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, the_AT model_NN1 agreement_NN1 represents_VVZ the_AT interest_NN1 of_IO the_AT directors_NN2 and_CC the_AT producer_NN1 's_GE interests_NN2 are_VBR not_XX included_VVN in_II this_DD1 starting_NN1 point_NN1 ._. 
</s>
<s>
The_AT director_NN1 can_VM therefore_RR be_VBI content_JJ if_CS the_AT terms_NN2 of_IO the_AT final_JJ agreement_NN1 come_VV0 close_RR to_II the_AT model_NN1 agreement_NN1 's_GE terms_NN2 ._. 
</s>
<s>
As_CSA it_PPH1 has_VHZ been_VBN presented_VVN in_II this_DD1 term_NN1 paper_NN1 that_CST most_DAT of_IO SELO_NP1 's_GE model_NN1 agreement_NN1 's_GE clauses_NN2 relating_VVG to_II the_AT assignment_NN1 of_IO the_AT copyright_NN1 and_CC the_AT moral_JJ rights_NN2 of_IO the_AT director_NN1 derive_VV0 directly_RR from_II the_AT law_NN1 or_CC have_VH0 a_AT1 legal_JJ background_NN1 in_II the_AT Copyright_NN1 Act_NN1 ._. 
</s>
<s>
The_AT Copyright_NN1 Act_NN1 represents_VVZ mostly_RR non-mandatory_JJ legislation_NN1 and_CC its_APPGE provisions_NN2 shall_VM prevail_VVI only_RR if_CS not_XX otherwise_RR agreed_VVN ._. 
</s>
<s>
Therefore_RR the_AT also_RR the_AT clauses_NN2 having_VHG a_AT1 legal_JJ background_NN1 in_II the_AT Copyright_NN1 Act_NN1 are_VBR subject_II21 to_II22 the_AT negotiation_NN1 outcome_NN1 ._. 
</s>
<s>
The_AT clauses_NN2 that_CST have_VH0 most_DAT variation_NN1 in_II different_JJ final_JJ agreements_NN2 are_VBR the_AT compensation_NN1 clauses_NN2 ._. 
</s>
<s>
It_PPH1 would_VM therefore_RR prove_VVI to_TO be_VBI interesting_JJ to_TO compare_VVI the_AT compensation_NN1 structures_NN2 and_CC levels_NN2 in_II different_JJ European_JJ countries_NN2 as_II the_AT praxis_NN1 relating_VVG to_II compensation_NN1 is_VBZ not_XX deriving_VVG directly_RR from_II the_AT law_NN1 but_CCB variation_NN1 between_II the_AT countries_NN2 is_VBZ expected_VVN ._. 
</s>
<s>
The_AT compensation_NN1 issues_NN2 are_VBR also_RR outside_II the_AT scope_NN1 of_IO EU-level_JJ harmonisation_NN1 ._. 
</s>
