<s>
Exploring_VVG the_AT Opportunities_NN2 of_IO an_AT1 Aging_JJ Workforce_NN1 :_: Motivating_VVG Older_JJR Employees_NN2 to_II a_AT1 Longer_JJR Working_NN1 Life_NN1 1_MC1 Introduction_NN1 In_II recent_JJ years_NNT2 ,_, there_EX has_VHZ been_VBN a_AT1 growing_JJ interest_NN1 in_II the_AT possibilities_NN2 of_IO HR_NNU practises_VVZ with_IW which_DDQ to_TO promote_VVI the_AT work_NN1 of_IO older_JJR employees_NN2 in_II organizations_NN2 ._. 
</s>
<s>
The_AT well-known_JJ phenomena_NN2 of_IO demographical_JJ change_NN1 and_CC its_APPGE impact_NN1 on_II the_AT labour_NN1 force_NN1 have_VH0 centred_VVN the_AT attention_NN1 of_IO many_DA2 researchers_NN2 to_II the_AT questions_NN2 regarding_II employee_NN1 well-being_NN1 ,_, motivation_NN1 and_CC retention_NN1 ._. 
</s>
<s>
Knowledge_NN1 of_IO ways_NN2 to_TO enhance_VVI the_AT well-being_NN1 of_IO older_JJR employees_NN2 and_CC motivational_JJ issues_NN2 regarding_II the_AT retention_NN1 of_IO key_JJ personell_NN1 has_VHZ great_JJ importance_NN1 for_IF HR_NNU professionals_NN2 and_CC also_RR companies_NN2 in_RR21 general_RR22 ._. 
</s>
<s>
The_AT common_JJ assumption_NN1 among_II many_DA2 organizations_NN2 has_VHZ until_II recent_JJ years_NNT2 been_VBN that_CST older_JJR workers_NN2 are_VBR easily_RR dispensable_JJ ,_, much_RR more_RGR expensive_JJ ,_, and_CC add_VV0 less_DAR value_NN1 to_II the_AT organization_NN1 than_CSN their_APPGE younger_JJR co-workers_NN2 ._. 
</s>
<s>
With_IW the_AT prospective_JJ and_CC perhaps_RR already_RR prevailing_JJ skill-shortage_NN1 ,_, many_DA2 organizations_NN2 have_VH0 been_VBN forced_VVN to_TO reconsider_VVI their_APPGE attitudes_NN2 towards_II aging_JJ employees_NN2 ._. 
</s>
<s>
According_II21 to_II22 Peeters_VVZ and_CC van_NP1 Emmerik_NP1 (_( 2008_MC )_) the_AT current_JJ literature_NN1 suggests_VVZ that_CST the_AT age_NN1 related_JJ changes_NN2 in_II well-being_NN1 of_IO older_JJR workers_NN2 is_VBZ not_XX as_RG negative_JJ as_CSA was_VBDZ thought_VVN in_II earlier_JJR research_NN1 on_II the_AT topic_NN1 ._. 
</s>
<s>
There_EX is_VBZ now_RT much_DA1 evidence_NN1 that_CST supports_VVZ a_AT1 more_RGR positive_JJ view_NN1 of_IO the_AT older_JJR worker_NN1 and_CC encourages_VVZ both_RR researchers_NN2 and_CC practitioners_NN2 to_TO shift_VVI the_AT focus_NN1 from_II managing_JJ threats_NN2 to_II creating_VVG opportunities_NN2 ._. 
</s>
<s>
(_( Peeters_VVZ and_CC van_NP1 Emmerik_NP1 :_: 2008_MC )_) Kanfer_VV0 and_CC Ackerman_NP1 (_( 2004_MC )_) concluded_VVD based_VVN on_II their_APPGE research_NN1 that_CST there_EX is_VBZ neither_RR theoretical_JJ justification_NN1 nor_CC empirical_JJ evidence_NN1 supporting_VVG an_AT1 unavoidable_JJ decline_NN1 in_II work_NN1 motivation_NN1 with_IW growing_JJ age_NN1 ._. 
</s>
<s>
Instead_RR they_PPHS2 suggest_VV0 that_CST the_AT same_DA basic_JJ principles_NN2 of_IO work_NN1 motivation_NN1 are_VBR valid_JJ for_IF both_DB2 employees_NN2 in_II mid-life/later_FU years_NNT2 as_CSA in_II young_JJ adulthood_NN1 ._. 
</s>
<s>
According_II21 to_II22 them_PPHO2 ,_, the_AT key_NN1 to_II motivation_NN1 is_VBZ the_AT allocation_NN1 of_IO an_AT1 individuals_NN2 resources_NN2 to_II such_DA work_NN1 behaviours_NN2 that_CST promote_VV0 the_AT personal_JJ competencies_NN2 ,_, sense_NN1 of_IO self-efficacy_NN1 and_CC self-concept_NN1 with_IW which_DDQ to_TO attain_VVI desired_JJ work_NN1 outcomes_NN2 ._. 
</s>
<s>
Furthermore_RR Kanfer_VV0 and_CC Ackerman_NP1 (_( 2004_MC )_) argue_VV0 that_CST the_AT effect_NN1 of_IO aging_VVG on_II motivation_NN1 is_VBZ mostly_RR dependant_JJ on_II work_NN1 circumstances_NN2 ._. 
</s>
<s>
Therefore_RR it_PPH1 is_VBZ of_IO interest_NN1 to_TO further_RRR explore_VVI the_AT ways_NN2 in_II which_DDQ the_AT motivation_NN1 of_IO older_JJR employees_NN2 can_VM be_VBI enhanced_VVN through_II different_JJ organizational_JJ strategies_NN2 and_CC managerial_JJ practises_NN2 as_CSA also_RR Kanfer_VV0 and_CC Ackerman_NP1 (_( 2008_MC )_) suggest_VV0 ._. 
</s>
<s>
1.1_MC Practical_JJ relevance_NN1 Companies_NN2 in_RR21 general_RR22 know_VV0 very_RG well_RR how_RGQ important_JJ it_PPH1 is_VBZ to_TO invest_VVI in_II the_AT well-being_NN1 of_IO the_AT employees_NN2 and_CC that_CST these_DD2 investments_NN2 according_II21 to_II22 research_NN1 pay_VV0 off_RP also_RR in_II economic_JJ terms_NN2 ._. 
</s>
<s>
Furthermore_RR ,_, a_AT1 whole_JJ new_JJ market_NN1 has_VHZ been_VBN established_VVN for_IF firms_NN2 that_CST provide_VV0 services_NN2 within_II the_AT work_NN1 well-being_NN1 sector_NN1 ._. 
</s>
<s>
One_MC1 critical_JJ point_NN1 for_IF managers_NN2 and_CC hrm_NNU professionals_NN2 is_VBZ therefore_RR to_TO have_VHI knowledge_NN1 of_IO what_DDQ actually_RR works_VVZ and_CC which_DDQ are_VBR the_AT concrete_JJ measures_NN2 that_CST are_VBR needed_VVN in_BCL21 order_BCL22 to_TO support_VVI aging_JJ workers_NN2 in_II their_APPGE work_NN1 life_NN1 ._. 
</s>
<s>
Because_II21 of_II22 this_DD1 lack_NN1 of_IO knowledge_NN1 it_PPH1 is_VBZ of_IO practical_JJ relevance_NN1 that_CST also_RR researchers_NN2 give_VV0 their_APPGE attention_NN1 to_II the_AT issue_NN1 and_CC form_VV0 a_AT1 clear_JJ theoretical_JJ framework_NN1 for_IF discussing_VVG the_AT influence_NN1 of_IO motivational_JJ factors_NN2 on_II the_AT retention_NN1 of_IO older_JJR employees_NN2 ._. 
</s>
<s>
1.2_MC Purpose_NN1 The_AT purpose_NN1 of_IO this_DD1 paper_NN1 is_VBZ to_TO examine_VVI the_AT most_RGT important_JJ motivational_JJ factors_NN2 that_CST affect_VV0 the_AT retention_NN1 of_IO aging_JJ workers_NN2 ._. 
</s>
<s>
Furthermore_RR it_PPH1 seeks_VVZ to_TO summarize_VVI the_AT surveyed_JJ literature_NN1 in_BCL21 order_BCL22 to_TO create_VVI an_AT1 organizing_JJ framework_NN1 that_CST would_VM help_VVI to_II guideline_NN1 future_JJ empirical_JJ research_NN1 on_II the_AT topic_NN1 ._. 
</s>
<s>
1.3_MC Definitions_NN2 This_DD1 paper_NN1 focuses_VVZ specifically_RR on_II the_AT motivation_NN1 of_IO older_JJR employees_NN2 ._. 
</s>
<s>
There_EX is_VBZ a_AT1 vast_JJ amount_NN1 of_IO literature_NN1 discussing_VVG the_AT various_JJ different_JJ aspects_NN2 of_IO age_NN1 ,_, work_VV0 ,_, and_CC well-being_NN1 and_CC their_APPGE effect_NN1 on_II employee_NN1 retention_NN1 ,_, but_CCB to_II narrow_JJ down_II the_AT research_NN1 topic_NN1 I_PPIS1 have_VH0 chosen_VVN to_TO consentrate_VVI on_II the_AT motivational_JJ factors_NN2 that_CST influence_VV0 employee_NN1 retention_NN1 ._. 
</s>
<s>
Belove_VV0 the_AT most_RGT important_JJ terms_NN2 for_IF the_AT paper_NN1 will_VM be_VBI defined_VVN ._. 
</s>
<s>
Older_JJR employee_NN1 (_( older_JJR worker_NN1 ,_, aging_JJ employee_NN1 )_) :_: 1.4_MC Structure_NN1 and_CC approach_VV0 The_AT paper_NN1 is_VBZ divided_VVN into_II three_MC parts_NN2 according_II21 to_II22 the_AT main_JJ themes_NN2 of_IO current_JJ research_NN1 literature_NN1 in_II the_AT field_NN1 ._. 
</s>
<s>
It_PPH1 starts_VVZ with_IW a_AT1 conzeptualization_NN1 of_IO what_DDQ work_VV0 motivation_NN1 is_VBZ and_CC what_DDQ the_AT different_JJ aspects_NN2 of_IO work_NN1 motivation_NN1 are_VBR that_DD1 should_VM be_VBI considered_VVN when_CS discussing_VVG its_APPGE cosnsequences_NN2 on_II work_NN1 ._. 
</s>
<s>
The_AT second_MD part_NN1 deals_VVZ more_RGR specifically_RR with_IW the_AT effect_NN1 of_IO aging_VVG on_II motivation_NN1 ._. 
</s>
<s>
The_AT last_MD part_NN1 of_IO the_AT literature_NN1 survey_NN1 focuses_VVZ on_II the_AT practical_JJ implications_NN2 of_IO the_AT theories_NN2 of_IO aging_NN1 and_CC motivation_NN1 on_II the_AT daily_JJ work_NN1 of_IO HR_NNU professionals_NN2 ,_, providing_VVG concrete_JJ measures_NN2 for_IF motivating_VVG older_JJR employees_NN2 to_TO work_VVI longer_RRR and_CC retire_VVI later_RRR ._. 
</s>
<s>
This_DD1 is_VBZ done_VDN by_II a_AT1 literature_NN1 survey_NN1 of_IO the_AT recent_JJ and_CC central_JJ literature_NN1 in_II the_AT field_NN1 ._. 
</s>
<s>
2_MC Motivating_VVG older_JJR employees_NN2 introduction_NN1 into_II the_AT topic_NN1 more_RGR specificly_RR (_( metatext_NN1 )_) 2.1_MC Conzeptualizing_JJ work_NN1 motivation_NN1 idependent_NN1 and_CC dependant_JJ variable_NN1 2.2_MC The_AT effect_NN1 of_IO aging_VVG on_II motivation_NN1 pulling_VVG and_CC pushing_VVG factors_NN2 2.3_MC Practical_JJ implications_NN2 for_IF HR_NNU professionals_NN2 flexibility_NN1 in_II HR_NNU policies_NN2 attitude_NN1 change_NN1 knowlege_NN1 transfer_NN1 programs_NN2 3_MC Discussion_NN1 and_CC Conclusions_NN2 
</s>
