<s>
Family_NN1 business_NN1 in_II the_AT third_MD generation_NN1 :_: factors_NN2 of_IO the_AT survival_NN1 Introduction_NN1 Family_NN1 business_NN1 is_VBZ rather_RG old_JJ and_CC widespread_JJ form_NN1 of_IO business_NN1 ._. 
</s>
<s>
As_II every_AT1 other_JJ type_NN1 of_IO companies_NN2 private_JJ owned_JJ firms_NN2 have_VH0 their_APPGE lifecycle_NN1 ._. 
</s>
<s>
However_RRQV particularity_NN1 of_IO occurrence_NN1 of_IO such_DA companies_NN2 and_CC their_APPGE governance_NN1 that_CST carried_VVN out_RP by_II founders_NN2 and_CC their_APPGE family_NN1 members_NN2 makes_VVZ the_AT approach_NN1 of_IO running_VVG these_DD2 companies_NN2 to_TO be_VBI different_JJ from_II the_AT classic_JJ theory_NN1 of_IO corporate_JJ governance_NN1 ._. 
</s>
<s>
The_AT critical_JJ point_NN1 for_IF a_AT1 family_NN1 company_NN1 comes_VVZ when_RRQ the_AT third_MD generation_NN1 of_IO the_AT family_NN1 replaces_VVZ the_AT companys_NN2 previous_JJ governance_NN1 ._. 
</s>
<s>
At_II this_DD1 stage_NN1 of_IO a_AT1 family_NN1 companys_NN2 lifecycle_NN1 the_AT death_NN1 rate_NN1 for_IF companies_NN2 is_VBZ very_RG high_JJ ._. 
</s>
<s>
Only_RR 30_MC percent_NNU of_IO family_NN1 owned_VVD companies_NN2 survive_VV0 to_II the_AT second_MD generation_NN1 and_CC only_RR 12_MC percent_NNU survive_VV0 to_II the_AT third_MD generation_NN1 (_( Adamson_NP1 ,_, 2005_MC )_) ._. 
</s>
<s>
In_II European_JJ business_NN1 society_NN1 there_EX is_VBZ even_RR a_AT1 saying_NN1 for_IF this_DD1 case_NN1 :_: The_AT first_MD generation_NN1 creates_VVZ ,_, the_AT second_MD inherits_VVZ ,_, and_CC the_AT third_MD destroys_VVZ (_( Magretta_NP1 1998_MC )_) ._. 
</s>
<s>
The_AT main_JJ reason_NN1 for_IF failure_NN1 in_II the_AT third_MD generation_NN1 is_VBZ a_AT1 lack_NN1 of_IO understanding_NN1 of_IO a_AT1 firms_NN2 business_NN1 by_II new_JJ governance_NN1 and_CC management_NN1 teams_NN2 along_II21 with_II22 different_JJ incentives_NN2 for_IF running_VVG this_DD1 business_NN1 ._. 
</s>
<s>
There_EX are_VBR a_AT1 lot_NN1 of_IO case_NN1 studies_NN2 devoted_VVD to_II successful_JJ and_CC failed_VVD strategies_NN2 of_IO family_NN1 owned_VVD companies_NN2 being_VBG analyzed_VVN and_CC discussed_VVN in_II academic_JJ journals_NN2 ,_, management_NN1 magazines_NN2 ,_, and_CC other_JJ strategic_JJ management_NN1 issues_NN2 ._. 
</s>
<s>
Mostly_RR these_DD2 articles_NN2 discuss_VV0 family_NN1 companies_NN2 structure_NN1 ,_, decision_NN1 making_VVG process_NN1 ,_, the_AT succession_NN1 process_NN1 ,_, and_CC process_NN1 of_IO planning_NN1 of_IO the_AT succession_NN1 ._. 
</s>
<s>
The_AT process_NN1 of_IO transferring_VVG a_AT1 family_NN1 business_NN1 from_II the_AT founder_NN1 to_II the_AT second_MD generation_NN1 is_VBZ one_MC1 of_IO the_AT subjects_NN2 that_CST get_VV0 much_DA1 attention_NN1 from_II researchers_NN2 due_II21 to_II22 the_AT critical_JJ moment_NN1 of_IO the_AT founders_NN2 retirement_NN1 and_CC giving_VVG up_RP the_AT business_NN1 to_II the_AT next_MD generation_NN1 ._. 
</s>
<s>
However_RRQV the_AT succession_NN1 process_NN1 towards_II the_AT third_MD generation_NN1 is_VBZ studied_VVN only_RR within_II the_AT bounds_NN2 of_IO investigation_NN1 of_IO the_AT succession_NN1 process_NN1 as_II a_AT1 whole_NN1 ._. 
</s>
<s>
Nevertheless_RR percent_NNU of_IO companies_NN2 that_CST survive_VV0 after_II the_AT second_MD generation_NN1 still_RR decreases_VVZ ._. 
</s>
<s>
Obviously_RR ,_, much_DA1 of_IO a_AT1 companys_NN2 performance_NN1 in_II the_AT third_MD generation_NN1 depends_VVZ on_II what_DDQ is_VBZ being_VBG done_VDN by_II previous_JJ generations_NN2 and_CC how_RRQ it_PPH1 is_VBZ being_VBG transferred_VVN to_II the_AT third_MD generation_NN1 team_NN1 ._. 
</s>
<s>
Therefore_RR ,_, in_BCL21 order_BCL22 to_TO investigate_VVI conditions_NN2 which_DDQ provide_VV0 success_NN1 for_IF a_AT1 family_NN1 company_NN1 in_II the_AT long_JJ run_NN1 ,_, factors_NN2 that_CST affect_VV0 family_NN1 business_NN1 during_II the_AT third_MD generation_NN1 must_VM be_VBI examined_VVN ._. 
</s>
<s>
For_IF the_AT purpose_NN1 of_IO this_DD1 term_NN1 paper_NN1 overview_NN1 of_IO previous_JJ investigations_NN2 on_II family_NN1 business_NN1 companies_NN2 experience_VV0 ,_, their_APPGE succession_NN1 process_NN1 ,_, and_CC roles_NN2 of_IO family_NN1 business_NN1 members_NN2 are_VBR used_VVN ._. 
</s>
<s>
Due_II21 to_II22 other_JJ initial_JJ purposes_NN2 of_IO used_JJ books_NN2 and_CC articles_NN2 rather_II21 than_II22 examining_VVG the_AT family_NN1 business_NN1 at_II its_APPGE third_MD generation_NN1 ,_, an_AT1 attempt_NN1 to_II structure_NN1 main_JJ factors_NN2 which_DDQ affected_VVD the_AT business_NN1 at_II this_DD1 stage_NN1 will_VM be_VBI made_VVN ._. 
</s>
<s>
The_AT results_NN2 of_IO the_AT current_JJ paper_NN1 may_VM be_VBI used_VVN for_IF holding_VVG further_RRR empirical_JJ research_NN1 by_II formulating_VVG hypotheses_NN2 ,_, interviewing_VVG family_NN1 businesses_NN2 ,_, and_CC carrying_VVG statistical_JJ analysis_NN1 of_IO the_AT gathered_JJ data_NN ._. 
</s>
<s>
The_AT paper_NN1 is_VBZ structured_VVN as_CSA follows_VVZ :_: the_AT first_MD part_NN1 is_VBZ devoted_JJ to_II overview_NN1 of_IO the_AT theoretical_JJ framework_NN1 related_VVN to_II family_NN1 business_NN1 ._. 
</s>
<s>
Then_RT research_VV0 articles_NN2 on_II different_JJ aspects_NN2 of_IO family_NN1 business_NN1 and_CC its_APPGE succession_NN1 process_NN1 are_VBR considered_VVN in_BCL21 order_BCL22 to_TO define_VVI factors_NN2 which_DDQ may_VM affects_VVZ family_NN1 business_NN1 in_II the_AT third_MD generation_NN1 ._. 
</s>
<s>
In_II the_AT remainder_NN1 of_IO the_AT paper_NN1 an_AT1 attempt_NN1 to_II structure_NN1 factors_NN2 that_CST affected_VVD the_AT companies_NN2 performance_NN1 is_VBZ made_VVN along_II21 with_II22 discussions_NN2 and_CC proposals_NN2 for_IF further_JJR research_NN1 ._. 
</s>
<s>
Governance_NN1 of_IO family_NN1 business_NN1 and_CC its_APPGE development_NN1 :_: theoretical_JJ overview_NN1 The_AT main_JJ reason_NN1 why_RRQ family_NN1 business_NN1 is_VBZ discussed_VVN and_CC researched_VVN is_VBZ its_APPGE complex_NN1 and_CC specific_JJ scheme_NN1 of_IO relationships_NN2 between_II family_NN1 business_NN1 members_NN2 ._. 
</s>
<s>
The_AT three-circle_JJ model_NN1 of_IO family_NN1 business_NN1 was_VBDZ developed_VVN in_BCL21 order_BCL22 to_TO understand_VVI these_DD2 relationships_NN2 and_CC define_VVI origins_NN2 of_IO interpersonal_JJ and_CC role_NN1 problems_NN2 emerging_VVG during_II running_JJ family_NN1 business_NN1 (_( Figure_NN1 1_MC1 )_) ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) From_II the_AT model_NN1 it_PPH1 can_VM be_VBI seen_VVN that_DD1 family_NN1 business_NN1 system_NN1 has_VHZ three_MC main_JJ subsystems_NN2 which_DDQ are_VBR independent_JJ but_CCB overlap_VV0 all_RR each_PPX221 other_PPX222 ._. 
</s>
<s>
Thus_RR all_DB actors_NN2 who_PNQS are_VBR related_VVN to_II the_AT family_NN1 business_NN1 can_VM be_VBI divided_VVN into_II seven_MC groups_NN2 ._. 
</s>
<s>
Different_JJ roles_NN2 and_CC behavior_NN1 correspond_VV0 to_II every_AT1 particular_JJ group_NN1 ._. 
</s>
<s>
Defining_VVG a_AT1 place_NN1 to_II which_DDQ an_AT1 individual_NN1 belongs_VVZ will_VM help_VVI to_TO understand_VVI his_APPGE or_CC her_APPGE incentives_NN2 to_TO behave_VVI in_II particular_JJ way_NN1 and_CC to_TO make_VVI decisions_NN2 ._. 
</s>
<s>
Obviously_RR ,_, more_RGR complicated_JJ problems_NN2 occur_VV0 ,_, when_CS an_AT1 individual_NN1 corresponds_VVZ not_XX to_II a_AT1 single_JJ group_NN1 but_CCB to_II two_MC or_CC even_RR three_MC groups_NN2 ._. 
</s>
<s>
This_DD1 is_VBZ also_RR one_MC1 of_IO the_AT reasons_NN2 why_RRQ family_NN1 business_NN1 attracts_VVZ attention_NN1 from_II psychologists_NN2 and_CC sociologists_NN2 (_( Gersick_NP1 et_RA21 al._RA22 ,_, 1997_MC )_) :_: the_AT person_NN1 who_PNQS is_VBZ a_AT1 family_NN1 member_NN1 and_CC an_AT1 owner_NN1 or_CC especially_RR a_AT1 management_NN1 member_NN1 faces_VVZ the_AT dilemma_NN1 of_IO making_NN1 best_JJT decisions_NN2 for_IF his/her_APPGE family_NN1 and_CC for_IF the_AT business_NN1 ._. 
</s>
<s>
While_CS developing_VVG a_AT1 family_NN1 business_NN1 changes_VVZ all_DB the_AT time_NNT1 in_II31 terms_II32 of_II33 changes_NN2 in_II the_AT family_NN1 ,_, the_AT ownership_NN1 structure_NN1 ,_, and_CC the_AT management_NN1 ._. 
</s>
<s>
Consequently_RR ,_, the_AT three-cycle_JJ model_NN1 should_VM be_VBI used_VVN taking_VVG into_II account_NN1 these_DD2 characteristics_NN2 of_IO the_AT family_NN1 business_NN1 at_II a_AT1 specific_JJ stage_NN1 of_IO its_APPGE development_NN1 ._. 
</s>
<s>
From_II this_DD1 perspective_NN1 ,_, by_II the_AT third_MD generation_NN1 family_NN1 business_NN1 represents_VVZ much_DA1 more_DAR complex_JJ system_NN1 than_CSN it_PPH1 does_VDZ at_II the_AT moment_NN1 of_IO its_APPGE creation_NN1 ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO understand_VVI how_RRQ every_AT1 subsystem_NN1 changes_VVZ the_AT three-dimensional_JJ developmental_JJ model_NN1 was_VBDZ built_VVN (_( Figure_NN1 2_MC )_) ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) The_AT three-dimensional_JJ developmental_JJ model_NN1 shows_VVZ stages_NN2 through_II which_DDQ every_AT1 circle_NN1 moves_VVZ during_II the_AT family_NN1 business_NN1 development_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ not_XX necessary_JJ that_CST a_AT1 circle_NN1 starts_VVZ its_APPGE moving_NN1 from_II the_AT first_MD stage_NN1 indicated_VVN in_II this_DD1 model_NN1 :_: with_IW all_DB variations_NN2 of_IO forms_NN2 and_CC structures_VVZ a_AT1 family_NN1 business_NN1 can_VM begin_VVI its_APPGE development_NN1 from_II different_JJ points_NN2 of_IO every_AT1 dimension_NN1 ._. 
</s>
<s>
Therefore_RR ,_, evaluating_VVG and_CC analysis_NN1 of_IO a_AT1 family_NN1 business_NN1 should_VM be_VBI started_VVN from_II defining_VVG on_II which_DDQ stage_VV0 the_AT family_NN1 business_NN1 is_VBZ from_II every_AT1 of_IO the_AT three_MC dimensions_NN2 perspectives_NN2 ._. 
</s>
<s>
It_PPH1 may_VM seem_VVI that_CST a_AT1 family_NN1 owned_VVD firm_NN1 reached_VVD the_AT third_MD generation_NN1 can_VM not_XX be_VBI placed_VVN on_II a_AT1 first_MD stage_NN1 of_IO some_DD dimensions_NN2 ._. 
</s>
<s>
However_RR ,_, deeper_JJR analysis_NN1 of_IO the_AT business_NN1 may_VM prove_VVI this_DD1 conclusion_NN1 is_VBZ not_XX well-grounded_JJ ._. 
</s>
<s>
For_REX21 example_REX22 ,_, the_AT first_MD stage_NN1 of_IO the_AT family_NN1 circle_NN1 Young_JJ Business_NN1 Family_NN1 refers_VVZ to_II the_AT period_NN1 when_RRQ a_AT1 generation_NN1 is_VBZ on_II its_APPGE initial_JJ phase_NN1 of_IO development_NN1 :_: decisions_NN2 about_II relationship_NN1 between_II work_NN1 and_CC family_NN1 and_CC about_II working_VVG relationship_NN1 with_IW the_AT extended_JJ family_NN1 are_VBR taken_VVN (_( Gersick_NP1 ,_, 1997_MC )_) ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, this_DD1 stage_NN1 is_VBZ typical_JJ as_II21 for_II22 the_AT first_MD generation_NN1 when_CS a_AT1 family_NN1 business_NN1 emerges_VVZ as_II21 for_II22 the_AT third_MD generation_NN1 when_CS younger_JJR family_NN1 members_NN2 come_VV0 to_II the_AT business_NN1 ._. 
</s>
<s>
In_II fact_NN1 ,_, by_II the_AT third_MD generation_NN1 ,_, when_CS a_AT1 family_NN1 reproduces_VVZ itself_PPX1 continually_RR ,_, there_EX may_VM be_VBI complex_JJ relationships_NN2 between_II different_JJ generations_NN2 at_II their_APPGE different_JJ stages_NN2 of_IO lifecycle_NN1 ._. 
</s>
<s>
The_AT first_MD stage_NN1 of_IO the_AT business_NN1 dimension_NN1 Start-Up_NN1 may_VM take_VVI place_NN1 in_II the_AT third_MD generation_NN1 when_CS the_AT family_NN1 businesss_NN1 core_NN1 activity_NN1 is_VBZ reconsidered_VVN due_II21 to_II22 changed_JJ market_NN1 demand_NN1 or_CC some_DD sudden_JJ events_NN2 ._. 
</s>
<s>
At_II the_AT first_MD stage_NN1 of_IO ownership_NN1 Controlling_VVG Owner_NN1 ,_, when_CS ownership_NN1 is_VBZ controlled_VVN by_II an_AT1 individual_JJ or_CC a_AT1 couple_NN1 ,_, family_NN1 business_NN1 may_VM stay_VVI for_IF a_AT1 long_JJ time_NNT1 due_II21 to_II22 family_NN1 objectives_NN2 and_CC values_NN2 ._. 
</s>
<s>
Some_DD statistical_JJ data_NN and_CC experience_NN1 demonstrate_VV0 that_DD1 family_NN1 businesses_NN2 at_II this_DD1 ownership_NN1 structure_NN1 perform_VV0 better_RRR in_II the_AT long_JJ run_NN1 (_( Gersick_NP1 ,_, 1997_MC ;_; Magretta_NP1 ,_, 1998_MC )_) ._. 
</s>
<s>
Therefore_RR ,_, analyzing_VVG a_AT1 family_NN1 business_NN1 being_VBG in_II its_APPGE third_MD generation_NN1 every_AT1 stage_NN1 of_IO every_AT1 dimension_NN1 should_VM be_VBI taken_VVN into_II account_NN1 ._. 
</s>
<s>
Multi-entity_JJ roles_NN2 of_IO family_NN1 business_NN1 members_NN2 and_CC the_AT succession_NN1 process_NN1 as_CSA main_JJ factors_NN2 of_IO success_NN1 in_II the_AT third_MD generation_NN1 Succession_NN1 process_NN1 is_VBZ considered_VVN as_CSA one_MC1 of_IO the_AT biggest_JJT obstacle_NN1 in_II development_NN1 of_IO a_AT1 family_NN1 business_NN1 and_CC ,_, as_II a_AT1 result_NN1 ,_, the_AT most_RGT frequent_JJ reason_NN1 of_IO family_NN1 companies_NN2 death_NN1 (_( Gersick_NP1 et_RA21 al_RA22 ,_, 1997_MC ;_; Carlock_NP1 and_CC Ward_NP1 ,_, 2001_MC ;_; Adamson_NP1 ,_, 2005_MC ;_; Laakkonen_NP1 and_CC Kansikas_NP2 ,_, 2011_MC ;_; Lam_NP1 ,_, 2011_MC ;_; Van_NP1 der_NP1 Merwe_NP1 et_RA21 al._RA22 ,_, 2009_MC )_) ._. 
</s>
<s>
As_CSA Van_NP1 der_NP1 Merwe_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2009_MC )_) indicate_VV0 in_II their_APPGE article_NN1 :_: The_AT easier_JJR and_CC more_RGR successful_JJ the_AT transition_NN1 is_VBZ ,_, the_AT better_JJR the_AT chances_NN2 of_IO survival_NN1 and_CC long-term_JJ profitability._NNU Consequently_RR ,_, great_JJ amount_NN1 of_IO studies_NN2 and_CC researches_NN2 is_VBZ devoted_JJ to_II investigation_NN1 of_IO this_DD1 process_NN1 ,_, but_CCB mostly_RR the_AT process_NN1 of_IO transferring_VVG of_IO a_AT1 family_NN1 business_NN1 from_II the_AT first_MD generation_NN1 to_II the_AT second_NNT1 is_VBZ considered_VVN because_CS at_II this_DD1 stage_NN1 the_AT governance_NN1 of_IO the_AT business_NN1 goes_VVZ from_II the_AT founder_NN1 to_II another_DD1 family_NN1 or_CC non-family_JJ member_NN1 ._. 
</s>
<s>
The_AT succession_NN1 process_NN1 as_II every_AT1 process_NN1 in_II business_NN1 should_VM be_VBI planned_VVN in_BCL21 order_BCL22 to_TO be_VBI successfully_RR completed_VVN :_: One_MC1 of_IO the_AT most_RGT significant_JJ factors_NN2 determining_VVG the_AT continuity_NN1 prospects_NN2 of_IO the_AT family_NN1 business_NN1 from_II one_MC1 generation_NN1 to_II the_AT next_MD is_VBZ whether_CSW the_AT succession_NN1 process_NN1 is_VBZ properly_RR planned_VVN (_( Van_NP1 der_NP1 Merwe_NP1 et_RA21 al._RA22 ,_, 2009_MC )_) ._. 
</s>
<s>
Therefore_RR ,_, this_DD1 process_NN1 should_VM take_VVI place_NN1 in_II strategic_JJ planning_NN1 of_IO a_AT1 company_NN1 (_( Carlock_NP1 and_CC Ward_NP1 ,_, 2001_MC )_) ._. 
</s>
<s>
Results_NN2 of_IO some_DD investigations_NN2 showed_VVD that_CST many_DA2 family-owned_JJ companies_NN2 do_VD0 not_XX have_VHI the_AT succession_NN1 process_NN1 plan_NN1 but_CCB only_RR have_VH0 some_DD thoughts_NN2 about_II how_RRQ they_PPHS2 will_VM transfer_VVI the_AT business_NN1 to_II the_AT next_MD generation_NN1 (_( Van_NP1 der_NP1 Merwe_NP1 et_RA21 al_RA22 ,_, 2009_MC ;_; Laakkonen_NP1 and_CC Kansikas_NP2 ,_, 2011_MC )_) ._. 
</s>
<s>
Moreover_RR ,_, some_DD researchers_NN2 experience_NN1 showed_VVD that_CST the_AT term_NN1 of_IO succession_NN1 was_VBDZ not_XX a_AT1 topic_NN1 that_CST the_AT informants_NN2 liked_VVD to_TO discuss_VVI ,_, which_DDQ confirms_VVZ findings_NN2 that_CST succession_NN1 is_VBZ a_AT1 taboo_JJ subject_NN1 in_II family_NN1 business_NN1 (_( Lam_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
These_DD2 facts_NN2 indicate_VV0 that_CST in_BCL21 order_BCL22 to_TO complete_VVI the_AT succession_NN1 process_VV0 the_AT plan_NN1 of_IO the_AT succession_NN1 not_XX only_RR should_VM exist_VVI but_CCB must_VM be_VBI written_VVN and_CC accessible_JJ for_IF key_JJ stakeholders_NN2 of_IO the_AT family_NN1 company_NN1 (_( Van_NP1 der_NP1 Merwe_NP1 et_RA21 al._RA22 ,_, 2009_MC )_) ._. 
</s>
<s>
The_AT properly_RR planned_VVN succession_NN1 should_VM clarify_VVI a_AT1 proper_JJ person_NN1 for_IF the_AT succession_NN1 a_AT1 successor_NN1 ._. 
</s>
<s>
The_AT succession_NN1 plan_NN1 should_VM identify_VVI criteria_NN2 of_IO selection_NN1 of_IO a_AT1 successor_NN1 with_IW indicating_VVG main_JJ competences_NN2 which_DDQ a_AT1 new_JJ leader_NN1 needs_VVZ to_TO have_VHI in_BCL21 order_BCL22 to_TO provide_VVI a_AT1 smooth_JJ transition_NN1 of_IO leadership_NN1 between_II generations._NNU (_( Van_NP1 der_NP1 Merwe_NP1 et_RA21 al._RA22 ,_, 2009_MC )_) ._. 
</s>
<s>
The_AT research_NN1 held_VVN by_II Van_NP1 der_NP1 Merwe_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2009_MC )_) confirms_VVZ the_AT positive_JJ influence_NN1 of_IO management_NN1 succession_NN1 planning_NN1 ,_, suitability_NN1 of_IO prospective_JJ successor_NN1 and_CC positive_JJ view_NN1 of_IO the_AT expected_JJ outcome_NN1 of_IO succession_NN1 on_II family_NN1 businesses_NN2 performance_NN1 during_II the_AT succession_NN1 process_NN1 :_: the_AT more_DAR succession_NN1 planning_NN1 takes_VVZ place_NN1 and_CC the_AT better_JJR the_AT perceived_JJ suitability_NN1 of_IO the_AT successor_NN1 ,_, the_AT better_JJR the_AT expected_JJ outcome_NN1 of_IO the_AT succession_NN1 will_NN1 be._NNU What_DDQ is_VBZ interesting_JJ for_IF the_AT purpose_NN1 of_IO this_DD1 research_NN1 is_VBZ that_CST no_AT significant_JJ relationship_NN1 between_II these_DD2 variables_NN2 and_CC generation_NN1 of_IO family_NN1 employees_NN2 was_VBDZ found_VVN ._. 
</s>
<s>
This_DD1 means_VVZ that_DD1 succession_NN1 planning_NN1 is_VBZ important_JJ issue_NN1 at_II every_AT1 stage_NN1 of_IO the_AT family_NN1 business_NN1 development_NN1 regardless_RR of_IO the_AT generation_NN1 it_PPH1 is_VBZ governed_VVN by_II ._. 
</s>
<s>
At_II the_AT same_DA time_NNT1 practice_NN1 shows_VVZ that_CST the_AT second-_JJ and_CC the_AT third-generation_JJ family_NN1 companies_NN2 make_VV0 succession_NN1 plans_VVZ much_RR more_RGR often_RR and_CC properly_RR than_CSN the_AT first_MD generation_NN1 businesses_NN2 (_( Laakkonen_NP1 and_CC Kansikas_NP2 ,_, 2011_MC )_) ._. 
</s>
<s>
Recommendations_NN2 following_VVG from_II the_AT results_NN2 of_IO the_AT research_NN1 mentioned_VVN above_RL are_VBR to_TO start_VVI planning_VVG as_RG early_RR as_CSA possible_JJ ,_, to_TO create_VVI a_AT1 team_NN1 for_IF planning_NN1 of_IO the_AT management_NN1 succession_NN1 ,_, and_CC to_TO discuss_VVI these_DD2 issues_NN2 regularly_RR during_II family_NN1 business_NN1 meetings_NN2 (_( Van_NP1 der_NP1 Merwe_NP1 ,_, 2009_MC )_) ._. 
</s>
<s>
These_DD2 recommendations_NN2 may_VM be_VBI confidently_RR considered_VVN as_CSA factors_NN2 for_IF the_AT succession_NN1 from_II the_AT second_NNT1 to_II the_AT third_MD generation_NN1 ._. 
</s>
<s>
Along_II21 with_II22 strategic_JJ planning_NN1 of_IO the_AT succession_NN1 process_VV0 evolutionary_JJ process_NN1 of_IO changes_NN2 in_II ownership_NN1 and_CC management_NN1 should_VM be_VBI considered_VVN for_IF better_JJR understanding_NN1 of_IO some_DD aspects_NN2 of_IO this_DD1 process_NN1 and_CC ,_, as_II a_AT1 consequence_NN1 ,_, for_IF better_JJR planning_NN1 ._. 
</s>
<s>
Laakkonen_NN1 and_CC Kansikas_NP2 (_( 2011_MC )_) in_II their_APPGE article_NN1 indicate_VV0 evolutionary_JJ forces_NN2 which_DDQ influence_VV0 family_NN1 business_NN1 ._. 
</s>
<s>
The_AT major_JJ forces_NN2 they_PPHS2 define_VV0 are_VBR selection_NN1 and_CC variation_NN1 ._. 
</s>
<s>
Evolutionary_JJ variation_NN1 includes_VVZ such_DA changes_NN2 in_II the_AT business_NN1 as_CSA modifications_NN2 in_II production_NN1 ,_, working_VVG styles_NN2 ,_, and_CC customer_NN1 relationships_NN2 ._. 
</s>
<s>
Evolutionary_JJ selection_NN1 relates_VVZ to_II what_DDQ a_AT1 family_NN1 business_NN1 selects_VVZ ,_, in_II other_JJ words_NN2 it_PPH1 is_VBZ about_II human_JJ decision_NN1 making_VVG ._. 
</s>
<s>
Both_DB2 these_DD2 forces_NN2 cause_VV0 variation_NN1 that_CST can_VM be_VBI a_AT1 crucial_JJ factor_NN1 for_IF a_AT1 family_NN1 businesss_NN1 success_NN1 ._. 
</s>
<s>
Although_CS the_AT research_NN1 of_IO Laakkonen_NP1 and_CC Kansikas_NP2 (_( 2011_MC )_) is_VBZ mostly_RR devoted_JJ to_II the_AT transition_NN1 from_II the_AT founder_NN1 to_II the_AT younger_JJR generation_NN1 ,_, what_DDQ is_VBZ typical_JJ for_IF transition_NN1 from_II the_AT first_MD generation_NN1 to_II the_AT second_NNT1 ,_, it_PPH1 also_RR makes_VVZ some_DD implications_NN2 for_IF analysis_NN1 of_IO the_AT transition_NN1 process_NN1 from_II the_AT second_MD generation_NN1 to_II the_AT third_MD ._. 
</s>
<s>
Evolutionary_JJ forces_NN2 are_VBR unique_JJ for_IF every_AT1 family_NN1 business_NN1 and_CC they_PPHS2 may_VM be_VBI influenced_VVN by_II both_DB2 the_AT founder_NN1 and_CC the_AT next_MD generations_NN2 ._. 
</s>
<s>
During_II the_AT succession_NN1 knowledge_NN1 and_CC generational_JJ expertise_NN1 are_VBR transferred_VVN ,_, but_CCB new_JJ evolutionary_JJ routines_NN2 have_VH0 to_TO be_VBI developed_VVN by_II the_AT new_JJ generation_NN1 in_BCL21 order_BCL22 to_TO create_VVI variation_NN1 and_CC sustain_VVI competiveness_NN1 of_IO the_AT family_NN1 business_NN1 (_( Laakkonen_NP1 and_CC Kansikas_NP2 ,_, 2011_MC )_) ._. 
</s>
<s>
For_IF the_AT successful_JJ transferring_VVG a_AT1 family_NN1 business_NN1 to_II the_AT next_MD generation_NN1 ,_, self-motivation_JJ and_CC commitment_NN1 to_TO take_VVI responsibility_NN1 from_II a_AT1 successor_NN1 are_VBR needed_VVN :_: When_RRQ the_AT next_MD generation_NN1 is_VBZ not_XX committed_VVN to_II taking_VVG charge_NN1 over_II the_AT business_NN1 the_AT likelihood_NN1 of_IO succession_NN1 failure_NN1 increases._NNU The_AT research_NN1 of_IO Laakkonen_NP1 and_CC Kansikas_NP2 showed_VVD that_DD1 lack_NN1 of_IO resources_NN2 as_II31 well_II32 as_II33 lack_NN1 of_IO external_JJ expertise_NN1 can_VM constitute_VVI a_AT1 drawback_NN1 to_II evolution_NN1 as_CSA outside_JJ expertise_NN1 can_VM increase_VVI variation_NN1 and_CC selection_NN1 in_II the_AT business_NN1 ._. 
</s>
<s>
The_AT founder_NN1 management_NN1 may_VM demonstrate_VVI a_AT1 high_JJ level_NN1 of_IO influence_NN1 what_DDQ increases_VVZ the_AT risk_NN1 for_IF failure_NN1 for_IF the_AT next_MD generation_NN1 ._. 
</s>
<s>
For_IF the_AT purpose_NN1 of_IO this_DD1 paper_NN1 this_DD1 influence_NN1 is_VBZ also_RR significant_JJ ,_, because_CS if_CS it_PPH1 takes_VVZ place_NN1 in_II the_AT succession_NN1 to_II the_AT second_MD generation_NN1 ,_, then_RT the_AT risk_NN1 of_IO transferring_VVG old_JJ routines_NN2 to_II the_AT third_MD generation_NN1 is_VBZ high_JJ ._. 
</s>
<s>
As_II a_AT1 result_NN1 ,_, failures_NN2 in_II variation_NN1 and_CC selection_NN1 can_VM cause_VVI failure_NN1 in_II the_AT succession_NN1 process_NN1 ._. 
</s>
<s>
It_PPH1 also_RR should_VM be_VBI mentioned_VVN that_CST the_AT founders_NN2 presence_NN1 still_RR can_VM take_VVI place_NN1 in_II the_AT third_MD generation_NN1 (_( in_II31 case_II32 of_II33 multigenerational_JJ governance_NN1 )_) ;_; therefore_RR ,_, level_NN1 of_IO influence_NN1 of_IO the_AT founder_NN1 and_CC evolutionary_JJ routines_NN2 should_VM be_VBI properly_RR analyzed_VVN ._. 
</s>
<s>
As_CSA it_PPH1 was_VBDZ mentioned_VVN above_RL ,_, different_JJ roles_NN2 of_IO individuals_NN2 who_PNQS are_VBR related_VVN to_II the_AT family_NN1 business_NN1 play_VV0 crucial_JJ role_NN1 in_II the_AT whole_JJ process_NN1 of_IO running_VVG the_AT business_NN1 ._. 
</s>
<s>
Likewise_RR family_NN1 business_NN1 members_NN2 play_VV0 different_JJ roles_NN2 in_II the_AT succession_NN1 process_NN1 ,_, that_DD1 can_VM be_VBI characterized_VVN as_II a_AT1 complex_JJ ,_, dynamic_JJ process_NN1 which_DDQ may_VM take_VVI place_NN1 over_II several_DA2 years._NNU (_( Lam_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
Lam_NP1 in_II his_APPGE article_NN1 (_( 2011_MC )_) reviews_VVZ different_JJ approaches_NN2 that_CST describe_VV0 a_AT1 role_NN1 of_IO a_AT1 successor_NN1 ,_, self-identification_NN1 of_IO the_AT person_NN1 ,_, forces_NN2 that_CST influence_VV0 this_DD1 role_NN1 ,_, and_CC stages_NN2 of_IO the_AT persons_NN2 changing_VVG sense_NN1 of_IO self_NN1 ._. 
</s>
<s>
His_APPGE research_NN1 based_VVN on_II long-term_JJ contacts_NN2 with_IW a_AT1 number_NN1 of_IO Chinese_JJ family_NN1 companies_NN2 demonstrated_VVD that_CST the_AT main_JJ issue_NN1 giving_VVG rise_NN1 to_II the_AT failure_NN1 of_IO succession_NN1 is_VBZ family_NN1 business_NN1 members_NN2 collective_JJ lack_NN1 of_IO a_AT1 shared_JJ understanding_NN1 about_II succession_NN1 process_NN1 ._. 
</s>
<s>
It_PPH1 can_VM be_VBI seen_VVN from_II his_APPGE research_NN1 that_CST there_EX is_VBZ discrepancy_NN1 between_II what_DDQ the_AT founders_NN2 and_CC the_AT successors_NN2 say_VV0 and_CC what_DDQ they_PPHS2 actually_RR do_VD0 ._. 
</s>
<s>
It_PPH1 is_VBZ argued_VVN by_II the_AT researcher_NN1 that_CST the_AT reason_NN1 of_IO that_DD1 lies_VVZ in_II individuals_NN2 multi-entity_JJ roles_NN2 which_DDQ they_PPHS2 are_VBR playing_VVG simultaneously_RR ._. 
</s>
<s>
It_PPH1 may_VM cause_VVI serious_JJ problems_NN2 for_IF the_AT succession_NN1 process_NN1 ,_, because_CS while_CS conflicts_NN2 between_II individuals_NN2 seem_VV0 to_TO be_VBI relatively_RR salient_JJ ,_, the_AT conflicts_NN2 within_II the_AT individual-self_NN1 are_VBR unspoken_JJ and_CC sometimes_RT unnoticed._NNU (_( Lam_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
Therefore_RR ,_, the_AT critical_JJ issue_NN1 for_IF a_AT1 successor_NN1 is_VBZ to_TO realize_VVI his_APPGE or_CC her_APPGE different_JJ roles_NN2 in_BCL21 order_BCL22 to_TO avoid_VVI some_DD conflicts_NN2 that_CST may_VM take_VVI place_NN1 in_II the_AT succession_NN1 process_NN1 and_CC after_CS it_PPH1 ._. 
</s>
<s>
Lussier_NN1 and_CC Sonfield_NP1 (_( 2010_MC )_) held_VVD a_AT1 research_NN1 that_CST from_II some_DD perspectives_NN2 is_VBZ closely_RR related_VVN to_II the_AT current_JJ paper_NN1 ._. 
</s>
<s>
They_PPHS2 tested_VVD eleven_MC hypotheses_NN2 concerning_II family_NN1 businesss_NN1 characteristics_NN2 at_II different_JJ stages_NN2 of_IO its_APPGE development_NN1 in_BCL21 order_BCL22 to_TO define_VVI similarities_NN2 and_CC differences_NN2 between_II the_AT three_MC generations_NN2 ._. 
</s>
<s>
The_AT sample_NN1 included_VVD six_MC countries_NN2 in_BCL21 order_BCL22 to_TO investigate_VVI family_NN1 businesses_NN2 from_II significantly_RR different_JJ cultures_NN2 ._. 
</s>
<s>
The_AT results_NN2 of_IO the_AT research_NN1 along_II21 with_II22 implications_NN2 to_II the_AT current_JJ study_NN1 are_VBR given_VVN below_RL (_( Table_NN1 1_MC1 )_) ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) Factors_NN2 of_IO survival_NN1 in_II the_AT third_MD generation_NN1 An_AT1 attempt_NN1 to_II structure_NN1 factors_NN2 that_CST affected_VVD the_AT companies_NN2 performance_NN1 in_II the_AT third_MD generation_NN1 will_VM be_VBI made_VVN Conclusion_NN1 The_AT results_NN2 will_VM be_VBI discussed_VVN ,_, implementation_NN1 and_CC proposals_NN2 for_IF further_JJR research_NN1 
</s>
