<s>
Importance_NN1 of_IO industry_NN1 cluster_VV0 German_JJ Automotive_JJ Locations_NN2 Innovation_NN1 and_CC Production_NN1 1_MC1 Introduction_NN1 Germany_NP1 is_VBZ the_AT largest_JJT country_NN1 of_IO automobile_NN1 production_NN1 in_II Europe_NP1 ,_, and_CC ranks_NN2 third_MD in_II the_AT world_NN1 after_II the_AT United_NP1 States_NP1 and_CC Japan_NP1 (_( Pfaffman_NP1 &;_NULL Stephan_NP1 ,_, 2001_MC )_) ._. 
</s>
<s>
One_MC1 of_IO the_AT leading_JJ German_JJ automotive_JJ clusters_NN2 is_VBZ in_II the_AT region_NN1 around_II Stuttgart_NP1 ._. 
</s>
<s>
Besides_II Daimler_NP1 and_CC Porsche_NP1 ,_, approximately_RR four_MC hundred_NNO suppliers_NN2 are_VBR located_VVN in_II this_DD1 region_NN1 ._. 
</s>
<s>
The_AT Stuttgart_NP1 region_NN1 is_VBZ a_AT1 leader_NN1 in_II technological_JJ innovation_NN1 (_( Reiner_NP1 R._NP1 ,_, 2006_MC )_) ._. 
</s>
<s>
Increased_JJ global_JJ trade_NN1 has_VHZ forced_VVN many_DA2 auto-giants_NN2 such_II21 as_II22 General_JJ Motors_NN2 ,_, Volkswagen_NP1 and_CC Daimler_NP1 Chrysler_NP1 to_TO shift_VVI their_APPGE production_NN1 bases_NN2 to_II developing_JJ countries_NN2 in_BCL21 order_BCL22 to_TO gain_VVI operational_JJ efficiency_NN1 ,_, in_II an_AT1 increasingly_RR competitive_JJ global_JJ marketplace_NN1 (_( Biswajit_NP1 ,_, Banerjee_NP1 ,_, &;_NULL Chatterjee_NP1 ,_, 2007_MC )_) ._. 
</s>
<s>
The_AT BRIC-countries_NN2 (_( Brazil_NP1 ,_, Russia_NP1 ,_, India_NP1 and_CC China_NP1 )_) have_VH0 played_VVN an_AT1 important_JJ role_NN1 as_CSA areas_NN2 for_IF relocation_NN1 ._. 
</s>
<s>
With_IW growing_JJ domestic_JJ car_NN1 markets_NN2 these_DD2 countries_NN2 are_VBR also_RR vital_JJ for_IF strategic_JJ repositioning_NN1 (_( BBC_NP1 )_) ._. 
</s>
<s>
Previous_JJ research_NN1 conducted_VVN by_II e.g._REX Biswajit_NP1 et_RA21 al_RA22 has_VHZ concentrated_VVN on_II the_AT benefits_NN2 of_IO relocating_VVG business_NN1 functions_NN2 to_II low-cost_JJ countries_NN2 ,_, such_II21 as_II22 cost-savings_NN2 and_CC strategic_JJ positioning_NN1 ,_, to_TO name_VVI but_CCB a_AT1 few_DA2 ._. 
</s>
<s>
The_AT implications_NN2 of_IO partially_RR relocating_VVG business_NN1 activities_NN2 results_NN2 in_II less_DAR synergies_NN2 between_II different_JJ departments_NN2 ._. 
</s>
<s>
Consequently_RR ,_, there_EX is_VBZ a_AT1 need_NN1 for_IF careful_JJ analysis_NN1 of_IO the_AT potential_JJ benefits_NN2 of_IO relocation_NN1 compared_VVN with_IW the_AT gains_NN2 attained_VVN from_II smaller_JJR ,_, concentrated_JJ and_CC interconnected_JJ business_NN1 units_NN2 ,_, namely_REX clusters._NNU 1.1_MC Problem_NN1 Definition_NN1 Growth_NN1 management_NN1 theory_NN1 suggests_VVZ that_CST extensive_JJ benefits_NN2 are_VBR received_VVN from_II concentrated_JJ business_NN1 units_NN2 ._. 
</s>
<s>
My_APPGE objective_NN1 is_VBZ therefore_RR to_TO analyze_VVI the_AT benefits_NN2 received_VVN from_II clusters_NN2 ,_, where_CS manufacturing_NN1 and_CC research_NN1 facilities_NN2 are_VBR located_VVN physically_RR close_VV0 ._. 
</s>
<s>
Specifically_RR concentrating_VVG on_II gains_NN2 for_IF production_NN1 and_CC innovation_NN1 ._. 
</s>
<s>
The_AT theoretical_JJ foundations_NN2 will_VM be_VBI applied_VVN to_II the_AT German_JJ automotive_JJ cluster_NN1 in_II the_AT surrounding_JJ region_NN1 of_IO Stuttgart_NP1 ._. 
</s>
<s>
Dyer_NP1 (_( 1996_MC )_) explored_VVD the_AT effect_NN1 of_IO clustering_NN1 on_II quality_NN1 and_CC innovation_NN1 by_II comparing_VVG the_AT US_NP1 automobile_NN1 industry_NN1 with_IW its_APPGE Japanese_JJ competitors_NN2 ._. 
</s>
<s>
He_PPHS1 measured_VVD the_AT quality_NN1 of_IO clustering_NN1 by_II the_AT degree_NN1 of_IO inter-firm_JJ specialization_NN1 (_( i.e._REX ,_, automaker-supplier_JJ relationship_NN1 )_) and_CC assessed_VVD the_AT correlation_NN1 of_IO inter-firm_JJ specialization_NN1 and_CC performance_NN1 ._. 
</s>
<s>
His_APPGE findings_NN2 indicate_VV0 that_CST a_AT1 high_JJ human_JJ asset_NN1 specialization_NN1 can_VM be_VBI associated_VVN with_IW a_AT1 high_JJ level_NN1 of_IO quality_NN1 and_CC faster_JJR product_NN1 development_NN1 cycles_NN2 (_( Dyer_NP1 ,_, 1996_MC ,_, pp._NNU2 279-289_MCMC )_) ,_, whereby_RRQ human_JJ asset_NN1 specialization_NN1 refers_VVZ to_II the_AT number_NN1 of_IO face-to-face_JJ contacts_NN2 between_II supplier_NN1 and_CC automaker_NN1 ,_, the_AT number_NN1 of_IO guest_NN1 engineers_NN2 ,_, and_CC the_AT degree_NN1 of_IO information_NN1 sharing_VVG (_( pp._NNU2 277-278_MCMC )_) ._. 
</s>
<s>
In_II contrast_NN1 to_II Dyers_NP2 study_VV0 this_DD1 paper_NN1 focuses_VVZ on_II the_AT benefits_NN2 for_IF production_NN1 in_II31 addition_II32 to_II33 innovation_NN1 ._. 
</s>
<s>
It_PPH1 seems_VVZ as_CS21 if_CS22 production_NN1 fosters_VVZ innovation_NN1 ,_, and_CC vice-versa_RR ,_, so_RR analyzing_VVG the_AT benefits_NN2 with_II31 respect_II32 to_II33 both_DB2 aspects_NN2 displays_VVZ the_AT effects_NN2 more_RGR truthfully_RR ._. 
</s>
<s>
Furthermore_RR the_AT investigation_NN1 will_VM be_VBI applied_VVN to_II just_RR one_MC1 cluster._NNU 1.2_MC Course_NN1 of_IO the_AT Investigation_NN1 The_AT analysis_NN1 will_VM be_VBI divided_VVN into_II a_AT1 theoretical_JJ and_CC a_AT1 case_NN1 study_NN1 part_NN1 ._. 
</s>
<s>
To_TO begin_VVI ,_, the_AT conceptual_JJ framework_NN1 of_IO the_AT analysis_NN1 is_VBZ presented_VVN ._. 
</s>
<s>
Porter_NP1 's_GE diamond_NN1 model_NN1 is_VBZ referred_VVN to_II as_II a_AT1 theory_NN1 to_TO describe_VVI the_AT competitiveness_NN1 of_IO national_JJ economies_NN2 ._. 
</s>
<s>
Subsequently_RR ,_, models_NN2 and_CC research_NN1 on_II the_AT competitiveness_NN1 of_IO smaller_JJR economic_JJ units_NN2 ,_, namely_REX industry_NN1 clusters_NN2 ,_, are_VBR presented_VVN ._. 
</s>
<s>
Furthermore_RR ,_, the_AT nature_NN1 and_CC the_AT benefits_NN2 of_IO clustering_NN1 will_VM be_VBI assessed_VVN ._. 
</s>
<s>
In_RR21 particular_RR22 ,_, the_AT benefits_NN2 for_IF production_NN1 and_CC innovation_NN1 are_VBR examined_VVN ._. 
</s>
<s>
The_AT case_NN1 study_NN1 will_VM apply_VVI the_AT theoretical_JJ concepts_NN2 to_II the_AT German_JJ automotive_JJ industry_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ hypothesized_VVN that_CST the_AT theoretical_JJ effects_NN2 of_IO industry_NN1 clusters_NN2 should_VM also_RR apply_VVI to_II the_AT firms_NN2 within_II the_AT Stuttgart_NP1 region_NN1 if_CS evidence_NN1 of_IO clustering_NN1 can_VM be_VBI found_VVN ._. 
</s>
<s>
Subsequently_RR ,_, the_AT benefits_NN2 of_IO clustering_NN1 for_IF production_NN1 and_CC innovation_NN1 are_VBR presented_VVN in_II more_DAR detail_NN1 ._. 
</s>
<s>
Finally_RR ,_, conclusions_NN2 of_IO the_AT findings_NN2 are_VBR summarized_VVN with_II31 respect_II32 to_II33 the_AT objective._NNU 2_MC Theoretical_JJ and_CC Conceptual_JJ Background_NN1 2.1_MC The_AT Competitive_JJ Advantage_NN1 of_IO Nations_NN2 A_ZZ1 common_JJ aspect_NN1 among_II the_AT prosperity_NN1 of_IO the_AT world_NN1 's_GE most_RGT advanced_JJ nations_NN2 is_VBZ that_CST they_PPHS2 are_VBR all_DB in_II31 possession_II32 of_II33 a_AT1 competitive_JJ advantage_NN1 ._. 
</s>
<s>
This_DD1 advantage_NN1 is_VBZ created_VVN through_RP ,_, and_CC rests_VVZ upon_II improving_VVG the_AT usefulness_NN1 and_CC productivity_NN1 of_IO inputs_NN2 ._. 
</s>
<s>
A_AT1 nation_NN1 can_VM gain_VVI competitive_JJ advantages_NN2 by_II creating_VVG strategic_JJ assets_NN2 (_( Amit_NP1 &;_NULL Schoemaker_NP1 ,_, 1993_MC )_) ._. 
</s>
<s>
Companies_NN2 ,_, and_CC therewith_RR nations_NN2 ,_, create_VV0 and_CC sustain_VV0 competitive_JJ advantages_NN2 by_II exposing_VVG themselves_PPX2 to_II pressure_NN1 and_CC challenge_NN1 ._. 
</s>
<s>
The_AT most_RGT valuable_JJ factors_NN2 require_VV0 heavy_JJ investments_NN2 and_CC specialization_NN1 ,_, in_II order_NN1 to_TO best_RRT serve_VVI the_AT particular_JJ needs_NN2 of_IO a_AT1 country_NN1 's_GE industry_NN1 (_( Porter_NP1 ,_, 1990_MC )_) ._. 
</s>
<s>
The_AT national_JJ environment_NN1 helps_VVZ companies_NN2 gain_VVI competitive_JJ advantages_NN2 by_II :_: supporting_JJ and_CC allowing_VVG fast_JJ accumulation_NN1 of_IO specialized_JJ assets_NN2 and_CC skills_NN2 ;_; affording_VVG better_RRR and_CC ongoing_JJ information_NN1 and_CC insights_NN2 into_II product_NN1 and_CC process_VV0 needs_NN2 ;_; and_CC finally_RR by_II creating_VVG an_AT1 environment_NN1 that_CST pressures_NN2 companies_NN2 to_TO innovate_VVI and_CC invest_VVI ._. 
</s>
<s>
This_DD1 leaves_VVZ companies_NN2 no_AT other_JJ choice_NN1 than_CSN to_TO gain_VVI and_CC upgrade_VVI competitive_JJ advantages_NN2 (_( Porter_NP1 ,_, 1990_MC )_) ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) Porter_NP1 describes_VVZ the_AT primary_JJ nature_NN1 in_II which_DDQ competitive_JJ advantages_NN2 emerge_VV0 with_IW his_APPGE theory_NN1 of_IO the_AT diamond_NN1 ,_, which_DDQ consists_VVZ of_IO four_MC attributes_NN2 :_: factor_NN1 conditions_NN2 ;_; demand_VV0 conditions_NN2 ;_; related_JJ and_CC supporting_JJ industries_NN2 ;_; firm_JJ strategy_NN1 ,_, structure_NN1 and_CC rivalry_NN1 (_( Porter_NP1 ,_, 1990_MC ,_, p._NN1 77_MC )_) (_( Porter_NP1 M._NN1 E._NP1 ,_, 1990_MC ,_, p._NN1 77_MC )_) ._. 
</s>
<s>
High_JJ quality_NN1 factors_NN2 contribute_VV0 to_II it_PPH1 with_IW supporting_JJ elements_NN2 such_II21 as_II22 skilled_JJ workers_NN2 ,_, infrastructure_NN1 and_CC capital_NN1 resources_NN2 ._. 
</s>
<s>
The_AT context_NN1 for_IF a_AT1 firm_NN1 's_GE strategy_NN1 and_CC rivalry_NN1 consist_VV0 of_IO the_AT local_JJ structure_NN1 and_CC rules_NN2 ,_, which_DDQ encourages_VVZ investment_NN1 and_CC sustained_JJ upgrading_NN1 ._. 
</s>
<s>
The_AT proximity_NN1 of_IO sophisticated_JJ and_CC demanding_VVG customers_NN2 enhances_VVZ dynamic_JJ competition_NN1 and_CC can_VM help_VVI to_TO anticipate_VVI global_JJ trends_NN2 ._. 
</s>
<s>
Related_JJ and_CC supporting_JJ industries_NN2 ,_, offer_VV0 firms_NN2 access_VV0 to_II capable_JJ ,_, locally_RR based_VVN suppliers_NN2 as_II31 well_II32 as_II33 firms_NN2 in_II related_JJ fields_NN2 ._. 
</s>
<s>
The_AT relationship_NN1 to_II the_AT supporting_JJ industries_NN2 is_VBZ a_AT1 reinforcing_JJ process_NN1 and_CC most_RGT advantageous_JJ when_CS the_AT surrounding_JJ industries_NN2 themselves_PPX2 are_VBR globally_RR competitive_JJ (_( Porter_NP1 ,_, 1990_MC )_) ._. 
</s>
<s>
2.2_MC The_AT Nature_NN1 of_IO Industry_NN1 Clusters_NN2 Industry_NN1 clusters_NN2 can_VM be_VBI seen_VVN as_CSA regional_JJ agglomerations_NN2 of_IO interconnected_JJ institutions_NN2 that_CST have_VH0 unusual_JJ success_NN1 in_II particular_JJ fields_NN2 (_( Porter_NP1 ,_, 1998_MC ,_, p._NN1 78_MC )_) ._. 
</s>
<s>
The_AT geographic_JJ scope_NN1 of_IO clusters_NN2 can_VM range_VVI from_II a_AT1 single_JJ city_NN1 to_II crossing_VVG natural_JJ borders_NN2 ._. 
</s>
<s>
Furthermore_RR ,_, a_AT1 cluster_NN1 can_VM comprehend_VVI several_DA2 types_NN2 of_IO economic_JJ agents_NN2 ,_, that_REX21 is_REX22 ,_, it_PPH1 is_VBZ not_XX limited_VVN to_II the_AT profit-making_JJ firm_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ further_RRR noted_VVN that_CST a_AT1 cluster_NN1 can_VM extend_VVI downstream_RL to_II channels_NN2 and_CC customers_NN2 ,_, and_CC laterally_RR to_II manufacturers_NN2 of_IO complementary_JJ products_NN2 and_CC to_II companies_NN2 in_II industries_NN2 related_VVN to_II skills_NN2 ,_, technologies_NN2 ,_, or_CC common_JJ inputs_NN2 (_( Porter_NP1 ,_, 1998_MC ,_, p._NN1 78_MC )_) ._. 
</s>
<s>
It_PPH1 should_VM be_VBI noted_VVN that_CST externalities_NN2 are_VBR part_NN1 of_IO the_AT definition_NN1 of_IO clusters_NN2 and_CC that_CST the_AT character_NN1 of_IO those_DD2 is_VBZ usually_RR assumed_VVN to_TO be_VBI positive_JJ (_( c.f._VV0 ,_, Porter_NP1 ,_, 2003_MC ,_, p._NN1 562_MC )_) ._. 
</s>
<s>
The_AT development_NN1 of_IO clusters_NN2 is_VBZ a_AT1 long_JJ and_CC progressive_JJ learning_NN1 process_NN1 ._. 
</s>
<s>
Studies_NN2 regarding_II clusters_NN2 do_VD0 not_XX have_VHI a_AT1 clear_JJ consensus_NN1 about_II what_DDQ the_AT origins_NN2 are_VBR ._. 
</s>
<s>
The_AT roots_NN2 of_IO a_AT1 cluster_NN1 can_VM often_RR be_VBI traced_VVN back_RP to_II historical_JJ circumstances_NN2 ,_, but_CCB they_PPHS2 also_RR arise_VV0 from_II unusual_JJ ,_, sophisticated_JJ or_CC stringent_JJ local_JJ demands_NN2 ._. 
</s>
<s>
Some_DD authors_NN2 address_VV0 the_AT importance_NN1 of_IO materials_NN2 ,_, climate_NN1 ,_, university_NN1 research_NN1 and_CC typical_JJ location_NN1 factors_NN2 (_( Scott_NP1 ,_, 2000_MC )_) ._. 
</s>
<s>
Other_JJ theoretical_JJ approaches_NN2 explain_VV0 clusters_NN2 by_II the_AT initial_JJ presence_NN1 of_IO two_MC important_JJ firms_NN2 ,_, which_DDQ lead_VV0 to_II the_AT emergence_NN1 of_IO an_AT1 industry_NN1 (_( e.g._REX Silicon_NN1 Valley_NN1 )_) or_CC by_II public_JJ sector_NN1 investment_NN1 activities_NN2 (_( e.g._REX Massachusetts_NP1 Institute_NN1 of_IO Technology_NN1 and_CC Harvard_NP1 University_NN1 for_IF biotechnology_NN1 sector_NN1 in_II the_AT Boston_NP1 area_NN1 )_) (_( Porter_NP1 M._NN1 ,_, 1998_MC )_) ._. 
</s>
<s>
Innovation_NN1 and_CC location_NN1 are_VBR the_AT main_JJ drivers_NN2 in_II the_AT creation_NN1 process_NN1 ._. 
</s>
<s>
A_AT1 massive_JJ wave_NN1 of_IO outsourcing_VVG production_NN1 and_CC service_NN1 has_VHZ taken_VVN place_NN1 and_CC tends_VVZ to_TO happen_VVI in_II big_JJ networks_NN2 of_IO suppliers_NN2 and_CC distributors_NN2 ._. 
</s>
<s>
Clusters_NN2 affect_VV0 the_AT competitiveness_NN1 of_IO nations_NN2 within_RL and_CC across_II countries_NN2 in_II three_MC distinguished_JJ ways_NN2 :_: they_PPHS2 lead_VV0 to_II increased_JJ productivity_NN1 of_IO companies_NN2 based_VVN in_II the_AT cluster_NN1 ;_; they_PPHS2 drive_VV0 the_AT direction_NN1 and_CC pace_NN1 of_IO innovation_NN1 ;_; and_CC stimulate_VV0 the_AT formation_NN1 of_IO new_JJ businesses_NN2 which_DDQ expands_VVZ and_CC strengthens_VVZ the_AT cluster_NN1 in_II itself_PPX1 (_( Porter_NP1 ,_, 1998_MC ,_, p._NN1 80_MC )_) ._. 
</s>
<s>
They_PPHS2 both_DB2 promote_VV0 competition_NN1 and_CC cooperation_NN1 ._. 
</s>
<s>
In_II his_APPGE famous_JJ book_NN1 "_" The_AT Competitive_JJ Advantages_NN2 of_IO Nations_NN2 "_" (_( 1990_MC )_) ,_, Porter_NP1 promotes_VVZ industry_NN1 clusters_NN2 rather_II21 than_II22 just_RR one_MC1 competitive_JJ industry_NN1 ._. 
</s>
<s>
Looking_VVG at_II single_JJ products_NN2 from_II the_AT "_" cluster_NN1 lens_NN1 "_" suggests_VVZ that_CST they_PPHS2 need_VV0 their_APPGE own_DA home_NN1 base_NN1 ,_, that_DD1 should_VM be_VBI located_VVN in_II the_AT respectively_RR most_RGT vibrant_JJ area_NN1 ,_, and_CC it_PPH1 is_VBZ most_RGT beneficial_JJ to_TO move_VVI linked_JJ activities_NN2 to_II concentrated_JJ geographic_JJ areas_NN2 ._. 
</s>
<s>
Companies_NN2 should_VM foster_VVI personal_JJ relationships_NN2 within_II the_AT cluster_NN1 ,_, and_CC make_VV0 investments_NN2 to_TO engage_VVI themselves_PPX2 locally_RR ._. 
</s>
<s>
By_II getting_VVG involved_JJ in_II upgrading_VVG the_AT cluster_NN1 and_CC working_VVG collectively_RR ,_, growth_NN1 can_VM be_VBI promoted_VVN and_CC can_VM offer_VVI at_II the_AT same_DA time_NNT1 a_AT1 way_NN1 to_TO link_VVI the_AT public_NN1 and_CC private_JJ sectors_NN2 (_( Porter_NP1 ,_, 1998_MC )_) ._. 
</s>
<s>
2.3_MC Benefit_NN1 of_IO Clusters_NN2 for_IF Production_NN1 Due_II21 to_II22 the_AT evolvement_NN1 of_IO clusters_NN2 in_II a_AT1 reinforcing_JJ and_CC supporting_JJ environment_NN1 ,_, they_PPHS2 are_VBR associated_VVN with_IW increased_JJ productivity_NN1 ._. 
</s>
<s>
They_PPHS2 give_VV0 rise_NN1 to_II external_JJ economies_NN2 of_IO scale_NN1 (_( Marshall_NP1 ,_, 1920_MC )_) by_II facilitating_VVG the_AT access_NN1 to_II various_JJ types_NN2 of_IO inputs_NN2 ;_; accessing_VVG information_NN1 ,_, technology_NN1 and_CC needed_VVD institutions_NN2 ;_; coordination_NN1 with_IW related_JJ companies_NN2 ;_; and_CC measuring_VVG motivation_NN1 and_CC improvement_NN1 (_( Porter_NP1 ,_, 1998_MC ,_, p._NN1 81_MC )_) ._. 
</s>
<s>
A_AT1 cluster_NN1 allows_VVZ a_AT1 member_NN1 company_NN1 to_TO benefit_VVI as_CS21 if_CS22 it_PPH1 had_VHD greater_JJR scale_NN1 or_CC as_CS21 if_CS22 it_PPH1 had_VHD joined_VVN with_IW others_NN2 without_IW having_VHG to_TO give_VVI up_RP its_APPGE flexibility_NN1 (_( Porter_NP1 ,_, 1998_MC ,_, p._NN1 81_MC )_) ._. 
</s>
<s>
General_JJ access_NN1 to_II capital_NN1 assets_NN2 is_VBZ facilitated_VVN (_( Cuervo-Garca_NP1 et_RA21 al._RA22 ,_, 2009_MC )_) and_CC the_AT bargaining_NN1 power_NN1 of_IO firms_NN2 is_VBZ enhanced_VVN ,_, which_DDQ leads_VVZ to_TO lower_VVI purchasing_VVG costs_NN2 (_( Porter_NP1 ,_, 2003_MC ;_; Prevenzer_NP1 ,_, 1997_MC )_) ._. 
</s>
<s>
In_II the_AT case_NN1 of_IO a_AT1 densely_RR geographically_RR concentrated_JJ supplier_NN1 network_NN1 ,_, business_NN1 customers_NN2 may_VM enjoy_VVI cost_NN1 benefits_NN2 through_II local_JJ sourcing_NN1 (_( Porter_NP1 ,_, 2003_MC )_) ._. 
</s>
<s>
This_DD1 lowers_VVZ the_AT transaction_NN1 costs_NN2 ,_, and_CC the_AT creation_NN1 of_IO close_JJ and_CC informal_JJ relationships_NN2 are_VBR a_AT1 superior_JJ arrangement_NN1 for_IF all_DB parties_NN2 (_( Porter_NP1 ,_, 1998_MC )_) ._. 
</s>
<s>
Clusters_NN2 allow_VV0 access_NN1 to_II a_AT1 specialized_JJ and_CC skilled_JJ workforce_NN1 ,_, which_DDQ is_VBZ described_VVN by_II various_JJ researchers_NN2 (_( Almazan_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2006_MC ;_; Costa_NP1 &;_NULL Kahn_NP1 ,_, 2001_MC ;_; Diamond_NN1 &;_NULL Simon_NP1 ,_, 1990_MC )_) ._. 
</s>
<s>
Companies_NN2 get_VV0 a_AT1 chance_NN1 to_TO tap_VVI into_II already_RR existing_JJ pools_NN2 of_IO experienced_JJ employees_NN2 ._. 
</s>
<s>
Within_II a_AT1 cluster_NN1 companies_NN2 get_VV0 the_AT chance_NN1 to_TO tie_VVI relationships_NN2 and_CC get_VVI access_NN1 to_II specialized_JJ information_NN1 ._. 
</s>
<s>
More_RGR intense_JJ cooperation_NN1 and_CC competition_NN1 appear_VV0 simultaneously_RR ,_, and_CC are_VBR perceived_VVN to_TO benefit_VVI productivity_NN1 (_( Cuervo-Garca_NP1 et_RA21 al._RA22 ,_, 2009_MC ;_; Porter_NP1 ,_, 2003_MC )_) ._. 
</s>
<s>
Both_DB2 phenomena_NN2 can_VM coexist_VVI because_CS they_PPHS2 occur_VV0 on_II different_JJ dimensions_NN2 and_CC among_II different_JJ players_NN2 (_( Porter_NP1 ,_, 1998_MC )_) ._. 
</s>
<s>
Khan_NP1 and_CC Ghani_NP1 (_( 2004_MC )_) emphasize_VV0 the_AT emergence_NN1 of_IO trust_NN1 in_II clusters_NN2 as_II a_AT1 concept_NN1 related_VVN to_II social_JJ capital_NN1 ._. 
</s>
<s>
Adler_NN1 and_CC Kwon_NP1 (_( 2002_MC )_) summarize_VV0 various_JJ studies_NN2 indicating_VVG that_DD1 social_JJ capital_NN1 facilitates_VVZ resource_NN1 exchange_NN1 ,_, supplier_NN1 relationships_NN2 ,_, and_CC regional_JJ production_NN1 networks_NN2 ._. 
</s>
<s>
Rousseau_NP1 et_RA21 al._RA22 (_( 1998_MC )_) show_VV0 the_AT relation_NN1 between_II trust_NN1 and_CC decreased_JJ transaction_NN1 costs_VVZ as_II31 well_II32 as_II33 increased_JJ effectiveness_NN1 in_II responding_VVG to_II crises_NN2 ._. 
</s>
<s>
The_AT provision_NN1 of_IO public_NN1 and_CC quasi-public_JJ goods_NN2 is_VBZ enhanced_VVN by_II government_NN1 but_CCB also_RR by_II the_AT aggregation_NN1 of_IO firms_NN2 and_CC other_JJ institutions_NN2 ,_, so_CS21 that_CS22 mutual_JJ benefits_NN2 arise_VV0 while_CS costs_NN2 are_VBR shared_VVN between_II members_NN2 of_IO the_AT cluster_NN1 (_( Porter_NP1 ,_, 2003_MC )_) ._. 
</s>
<s>
Public_JJ goods_NN2 in_II clusters_NN2 often_RR comprise_VV0 infrastructure_NN1 and_CC administration_NN1 ,_, training_NN1 programs_NN2 and_CC laboratories_NN2 (_( Cuervo-_JJ Garca_NP1 et_RA21 al._RA22 ,_, 2009_MC )_) ._. 
</s>
<s>
The_AT linkages_NN2 within_II clusters_NN2 result_VV0 in_II synergies_NN2 ,_, and_CC the_AT joint_JJ forces_NN2 as_II a_AT1 whole_NN1 become_VV0 bigger_JJR than_CSN the_AT sum_NN1 of_IO its_APPGE parts_NN2 ._. 
</s>
<s>
Companies_NN2 are_VBR mutually_RR dependent_JJ ,_, good_JJ performance_NN1 by_II one_MC1 individual_NN1 boosts_VVZ the_AT success_NN1 of_IO others_NN2 ._. 
</s>
<s>
Since_CS the_AT products_NN2 complement_VV0 each_PPX221 other_PPX222 ,_, members_NN2 of_IO a_AT1 cluster_NN1 manage_VV0 to_II better_JJR meet_NN1 of_IO customer_NN1 needs_NN2 ._. 
</s>
<s>
Members_NN2 profit_VV0 from_II the_AT other_JJ entities_NN2 '_GE reputation_NN1 and_CC the_AT joint_JJ marketing_NN1 mechanisms_NN2 ._. 
</s>
<s>
Lastly_RR ,_, complementarities_NN2 result_VV0 in_II making_VVG buying_VVG more_RGR attractive_JJ for_IF customers_NN2 (_( Porter_NP1 ,_, 1998_MC )_) ._. 
</s>
<s>
Since_CS cluster_NN1 members_NN2 are_VBR exposed_VVN to_II higher_JJR competition_NN1 ,_, the_AT local_JJ rivalry_NN1 puts_VVZ more_DAR pressure_NN1 on_II the_AT various_JJ members_NN2 and_CC is_VBZ highly_RR motivating_VVG ._. 
</s>
<s>
Pride_NN1 and_CC the_AT desire_NN1 to_TO look_VVI good_JJ in_II a_AT1 community_NN1 spur_NN1 executives_NN2 to_TO attempt_VVI to_TO outdo_VVI one_PPX121 another_PPX122 (_( Porter_NP1 ,_, 1998_MC )_) ._. 
</s>
<s>
2.4_MC Benefit_NN1 of_IO Clusters_NN2 for_IF Innovation_NN1 Clusters_NN2 play_VV0 a_AT1 vital_JJ role_NN1 in_II a_AT1 company_NN1 's_GE ongoing_JJ ability_NN1 to_TO innovate_VVI ._. 
</s>
<s>
Many_DA2 of_IO the_AT above_JJ stated_JJ factors_NN2 that_CST improve_VV0 productivity_NN1 have_VH0 an_AT1 even_RR more_RGR dramatic_JJ effect_NN1 on_II innovation_NN1 ._. 
</s>
<s>
The_AT opportunities_NN2 for_IF innovation_NN1 are_VBR more_RGR visible_JJ ,_, and_CC the_AT environment_NN1 provides_VVZ the_AT capacity_NN1 and_CC flexibility_NN1 to_TO act_VVI rapidly_RR ._. 
</s>
<s>
Companies_NN2 manage_VV0 to_TO implement_VVI innovations_NN2 more_RGR quickly_RR ,_, and_CC since_CS local_JJ suppliers_NN2 and_CC partners_NN2 are_VBR involved_JJ in_II the_AT innovation_NN1 process_NN1 ,_, the_AT outcome_NN1 is_VBZ ensured_VVN to_II better_JJR match_NN1 customers_NN2 '_GE requirements_NN2 (_( Porter_NP1 ,_, 1998_MC )_) ._. 
</s>
<s>
It_PPH1 has_VHZ been_VBN found_VVN and_CC investigated_VVN by_II various_JJ researchers_NN2 that_CST investment_NN1 in_II research_NN1 and_CC development_NN1 (_( R_ZZ1 &D);_NULL of_IO private_JJ firms_NN2 and_CC universities_NN2 spills_VVZ over_RP for_IF third-party_JJ economic_JJ agents_NN2 (_( Jaffe_NP1 ,_, 1989_MC ;_; Acs_NN2 et_RA21 al._RA22 ,_, 1992_MC ,_, 1994_MC ;_; Feldmann_NP1 ,_, 1994a_FO ,_, b_ZZ1 )_) ._. 
</s>
<s>
At_II the_AT same_DA time_NNT1 ,_, it_PPH1 has_VHZ been_VBN argued_VVN that_DD1 knowledge_NN1 spillovers_NN2 are_VBR limited_VVN to_II certain_JJ geographic_JJ boundaries_NN2 (_( Marshall_NP1 ,_, 1920_MC ;_; Krugman_NP1 ,_, 1991b_FO )_) ._. 
</s>
<s>
The_AT fact_NN1 that_CST the_AT extent_NN1 of_IO knowledge_NN1 spillovers_NN2 depends_VVZ on_II distance_NN1 is_VBZ referred_VVN to_II as_RG "_" specially-mediated_JJ knowledge_NN1 spillovers_NN2 "_" (_( Audretsch_NP1 &;_NULL Feldmann_NP1 ,_, 1996_MC ,_, p._NN1 630_MC )_) ._. 
</s>
<s>
Porter_NP1 (_( 2003_MC )_) argues_VVZ that_CST customers_NN2 near_II clusters_NN2 are_VBR more_RGR informed_JJ and_CC demanding_VVG ,_, thus_RR challenging_JJ firms_NN2 more_RGR heavily_RR ._. 
</s>
<s>
Due_II21 to_II22 the_AT more_RGR sophisticated_JJ buyers_NN2 ,_, firms_NN2 within_II a_AT1 cluster_NN1 have_VH0 a_AT1 better_JJR view_NN1 of_IO the_AT market_NN1 compared_VVN to_II isolated_JJ competitors_NN2 ._. 
</s>
<s>
The_AT ongoing_JJ relationships_NN2 between_II entities_NN2 help_VV0 companies_NN2 to_TO learn_VVI early_RR about_II new_JJ technology_NN1 ,_, service_NN1 and_CC marketing_NN1 concepts_NN2 ,_, to_TO give_VVI a_AT1 few_DA2 examples_NN2 ._. 
</s>
<s>
Companies_NN2 get_VV0 the_AT chance_NN1 to_TO experiment_VVI at_II a_AT1 lower_JJR cost_NN1 and_CC can_VM delay_VVI large_JJ commitments_NN2 until_CS they_PPHS2 are_VBR assured_VVN that_CST a_AT1 given_JJ innovation_NN1 will_VM pan_VVI out_RP ._. 
</s>
<s>
Reinforcing_VVG all_DB other_JJ advantages_NN2 for_IF innovation_NN1 is_VBZ the_AT sheer_JJ pressure_NN1 that_CST occurs_VVZ within_II a_AT1 cluster_NN1 ._. 
</s>
<s>
Accordingly_RR ,_, clusters_NN2 can_VM remain_VVI centers_NN2 of_IO innovation_NN1 for_IF decades_NNT2 (_( Porter_NP1 ,_, 1998_MC ,_, pp._NNU2 83-84_MCMC )_) ._. 
</s>
<s>
3_MC Case_NN1 Study_NN1 -_- Analysis_NN1 of_IO the_AT Stuttgart_NP1 Cluster_NN1 3.1_MC Description_NN1 of_IO the_AT Cluster_NN1 Some_DD of_IO the_AT most_RGT well_JJ known_JJ German_JJ automotive_JJ clusters_NN2 are_VBR located_VVN in_II Ingolstadt_NP1 ,_, Munich_NP1 ,_, and_CC Stuttgart_NP1 ._. 
</s>
<s>
The_AT GDP_NN1 of_IO Stuttgart_NP1 is_VBZ approximately_RR to_II 95_MC billion_NNO euro_NN1 ,_, corresponding_VVG to_II that_DD1 of_IO Hungary_NP1 or_CC the_AT Czech_JJ Republic_NN1 ._. 
</s>
<s>
Furthermore_RR ,_, the_AT region_NN1 is_VBZ the_AT second_MD largest_JJT contributor_NN1 to_II German_JJ exports_NN2 ,_, following_VVG Munich_NP1 (_( Verband_NP1 Region_NN1 Stuttgart_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
Other_JJ car_NN1 manufacturing_NN1 clusters_NN2 such_II21 as_II22 Nagoya_NP1 in_II Japan_NP1 consists_VVZ of_IO only_RR one_MC1 main_JJ car_NN1 manufacturer_NN1 and_CC its_APPGE suppliers_NN2 ._. 
</s>
<s>
Stuttgart_NP1 differs_VVZ with_IW two_MC premium_JJ car_NN1 manufacturers_NN2 ,_, and_CC hosts_NN2 the_AT headquarters_NN of_IO suppliers_NN2 for_IF more_DAR than_CSN four_MC hundred_NNO small-_JJ and_CC medium-_JJ sized_JJ suppliers_NN2 ._. 
</s>
<s>
The_AT small-_NN1 and_CC medium-sized_JJ businesses_NN2 encompass_VV0 car_NN1 manufacturing_NN1 per_RR21 se_RR22 but_CCB also_RR other_JJ manufacturing_NN1 industries_NN2 ,_, equipment_NN1 suppliers_NN2 ,_, service_NN1 companies_NN2 ,_, auto-shops_NN2 and_CC trade_NN1 ._. 
</s>
<s>
The_AT Robert_NP1 Bosch_NP1 GmbH_NP1 ,_, which_DDQ is_VBZ headquartered_VVN in_II Stuttgart_NP1 ,_, has_VHZ the_AT highest_JJT number_NN1 of_IO patent_NN1 applications_NN2 in_II Germany_NP1 ;_; in_II 2007_MC the_AT patent_NN1 applications_NN2 by_II the_AT company_NN1 amounted_VVD to_II 2,509_MC ._. 
</s>
<s>
Partially_RR indicating_VVG the_AT importance_NN1 of_IO Stuttgart_NP1 for_IF innovation_NN1 (_( Welt_VV0 Online_RR ,_, 2008_MC )_) ._. 
</s>
<s>
3.1.1_MC Daimler_NP1 AG_FO and_CC Porsche_NP1 AG_FO Daimler_NP1 was_VBDZ founded_VVN in_II 1926_MC and_CC is_VBZ located_VVN in_II 23_MC places_NN2 in_II Germany_NP1 ;_; six_MC of_IO these_DD2 are_VBR within_II the_AT Stuttgart_NP1 region_NN1 ._. 
</s>
<s>
In_II Sindelfingen_NP1 ,_, the_AT world_NN1 's_GE largest_JJT Daimler_NP1 manufacturing_NN1 site_NN1 employs_VVZ (_( 2,901,520_MC km_NNU )_) 28,809_MC workers_NN2 ._. 
</s>
<s>
The_AT Daimler_NP1 group_NN1 's_GE headquarters_NN '_GE and_CC the_AT engine_NN1 manufacturing_NN1 are_VBR also_RR located_VVN here_RL (_( Daimler_NP1 AG_FO )_) ._. 
</s>
<s>
Porsche_NP1 is_VBZ a_AT1 part_NN1 of_IO the_AT Porsche_NP1 Automobil_NP1 Holding_NP1 SE_NP1 ,_, which_DDQ also_RR manages_VVZ the_AT Volkswagen_NP1 affiliation_NN1 ._. 
</s>
<s>
Porsche_NP1 was_VBDZ founded_VVN in_II 1931_MC ,_, and_CC currently_RR employs_VVZ around_RG 800_MC workers_NN2 ._. 
</s>
<s>
The_AT company_NN1 's_GE four_MC production_NN1 locations_NN2 are_VBR all_DB in_II Germany_NP1 ,_, of_IO which_DDQ three_MC around_II Stuttgart_NP1 (_( Dr._NNB Ing._NP1 h.c_NNU ._. 
</s>
<s>
F._NP1 Porsche_NP1 AG_FO ,_, 2010_MC )_) ._. 
</s>
<s>
3.1.2_MC Suppliers_NN2 Suppliers_NN2 can_VM be_VBI classified_VVN into_II three_MC tiers_NN2 ._. 
</s>
<s>
Tier_NN1 one_MC1 suppliers_VVZ are_VBR the_AT main_JJ suppliers_NN2 for_IF the_AT original_JJ equipment_NN1 manufacturers_NN2 (_( OEMs_NP2 )_) and_CC directly_RR provide_VV0 whole_JJ systems_NN2 and_CC modules_NN2 ._. 
</s>
<s>
Tier_NN1 two_MC suppliers_NN2 are_VBR responsible_JJ for_IF the_AT delivery_NN1 of_IO components_NN2 ,_, while_CS tier_NN1 three_MC suppliers_NN2 only_RR deliver_VV0 individual_JJ parts_NN2 ._. 
</s>
<s>
Each_DD1 sub_JJ supplier_NN1 ,_, tier_NN1 two_MC and_CC three_MC ,_, provide_VV0 the_AT next_MD higher_JJR level_NN1 with_IW their_APPGE parts_NN2 where_CS they_PPHS2 get_VV0 assembled_VVN into_II bigger_JJR parts_NN2 of_IO the_AT cars_NN2 ._. 
</s>
<s>
This_DD1 paper_NN1 concentrates_VVZ in_II its_APPGE descriptions_NN2 on_II tier_NN1 one_MC1 and_CC two_MC suppliers_NN2 ._. 
</s>
<s>
Supplier_NN1 parks_NN2 have_VH0 emerged_VVN around_II the_AT main_JJ manufacturing_NN1 sites_NN2 of_IO Daimler_NP1 and_CC Porsche_NP1 ._. 
</s>
<s>
These_DD2 parks_NN2 facilitate_VV0 potential_JJ cooperation_NN1 and_CC coordination_NN1 ,_, promote_VV0 innovation_NN1 and_CC growth_NN1 ,_, and_CC attract_VV0 new_JJ firms_NN2 building_VVG smaller_JJR clusters_NN2 within_II a_AT1 bigger_JJR cluster_NN1 ._. 
</s>
<s>
Table_NN1 1_MC1 ,_, in_II the_AT appendix_NN1 ,_, lists_VVZ a_AT1 few_DA2 main_JJ suppliers_NN2 ._. 
</s>
<s>
Figure_NN1 3_MC illustrates_VVZ the_AT regional_JJ proximity_NN1 of_IO suppliers_NN2 and_CC OEMs_NP2 ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) 3.2_MC Impact_NN1 on_II the_AT region_NN1 The_AT automobile_NN1 industry_NN1 is_VBZ the_AT main_JJ employer_NN1 for_IF citizens_NN2 in_II the_AT region_NN1 of_IO Stuttgart_NP1 ._. 
</s>
<s>
Thus_RR many_DA2 in_II the_AT region_NN1 are_VBR dependent_JJ on_II the_AT health_NN1 and_CC economic_JJ condition_NN1 of_IO this_DD1 industry_NN1 ._. 
</s>
<s>
Clear_JJ indicators_NN2 for_IF clusters_NN2 are_VBR :_: close_JJ relations_NN2 between_II OEMs_NP2 and_CC suppliers_NN2 ,_, and_CC their_APPGE dependence_NN1 on_II each_PPX221 other_PPX222 ._. 
</s>
<s>
In_II the_AT Stuttgart_NP1 cluster_NN1 ,_, close_JJ coordination_NN1 and_CC regional_JJ proximity_NN1 imply_VV0 not_XX only_RR a_AT1 greater_JJR dependency_NN1 of_IO suppliers_NN2 ,_, but_CCB also_RR of_IO the_AT OEMs_NP2 ,_, leading_VVG to_II a_AT1 high_JJ dependency_NN1 of_IO the_AT population_NN1 ,_, on_II the_AT working_JJ opportunities_NN2 created_VVN by_II the_AT industry_NN1 ._. 
</s>
<s>
Organizations_NN2 ,_, such_II21 as_II22 the_AT Cluster_NN1 Initiative_NN1 Region_NN1 Stuttgart_NP1 (_( CARS_NN2 )_) ,_, have_VH0 been_VBN established_VVN to_TO promote_VVI the_AT automotive_JJ business_NN1 ,_, enhance_VV0 the_AT cluster_NN1 and_CC innovation_NN1 ._. 
</s>
<s>
Education_NN1 and_CC qualified_JJ workers_NN2 are_VBR widely_RR available_JJ ,_, reaching_VVG from_II line_NN1 workers_NN2 to_II academic_JJ researchers_NN2 ,_, both_RR provided_VVN by_II special_JJ schools_NN2 and_CC university_NN1 co-operations_NN2 ._. 
</s>
<s>
The_AT cluster_NN1 surrounding_VVG Stuttgart_NP1 has_VHZ had_VHN the_AT opportunity_NN1 to_TO grow_VVI slowly_RR and_CC expand_VVI at_II a_AT1 reasonable_JJ rate_NN1 ,_, starting_VVG in_II the_AT year_NNT1 of_IO 1926_MC when_RRQ Daimler_NP1 was_VBDZ founded_VVN (_( Daimler_NP1 AG_FO )_) ._. 
</s>
<s>
Material_NN1 resources_NN2 have_VH0 not_XX as_RG much_RR contributed_VVN to_II the_AT growth_NN1 of_IO the_AT cluster_NN1 as_CSA innovation_NN1 and_CC research_NN1 ._. 
</s>
<s>
The_AT description_NN1 of_IO the_AT Stuttgart_NP1 region_NN1 displays_VVZ that_CST many_DA2 of_IO the_AT features_NN2 of_IO clusters_NN2 are_VBR in_II fact_NN1 found_VVN in_II this_DD1 region_NN1 ._. 
</s>
<s>
In_RR21 particular_RR22 it_PPH1 holds_VVZ that_CST the_AT Stuttgart_NP1 region_NN1 is_VBZ characterized_VVN by_II a_AT1 geographical_JJ agglomeration_NN1 of_IO interconnected_JJ institutions_NN2 that_CST have_VH0 unusual_JJ success_NN1 in_II a_AT1 particular_JJ field_NN1 ,_, namely_REX the_AT automobile_NN1 industry_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ just_RR the_AT definition_NN1 of_IO Porter_NP1 (_( 1998_MC )_) ,_, which_DDQ is_VBZ used_VVN for_IF this_DD1 paper_NN1 's_GE analysis_NN1 (_( p._NNU 78_MC )_) ._. 
</s>
<s>
It_PPH1 is_VBZ therefore_RR assumed_VVN that_CST the_AT benefits_NN2 that_CST apply_VV0 for_IF clusters_NN2 in_RR21 general_RR22 also_RR apply_VV0 for_IF the_AT cluster_NN1 around_II Stuttgart_NP1 ._. 
</s>
<s>
In_II the_AT following_JJ ,_, the_AT benefits_NN2 for_IF the_AT sectors_NN2 of_IO production_NN1 and_CC innovation_NN1 are_VBR examined_VVN in_II more_DAR detail._NNU 3.3_MC Analysis_NN1 of_IO Benefits_NN2 for_IF Innovation_NN1 As_CSA stated_VVN above_RL ,_, material_NN1 resources_NN2 have_VH0 not_XX contributed_VVN to_II the_AT growth_NN1 of_IO the_AT cluster_NN1 as_RG much_DA1 as_CSA innovation_NN1 and_CC research_NN1 ._. 
</s>
<s>
Research_NN1 and_CC innovation_NN1 by_II the_AT main_JJ players_NN2 show_VV0 a_AT1 clear_JJ profession_NN1 towards_II the_AT Stuttgart_NP1 region_NN1 ._. 
</s>
<s>
Daimler_NP1 for_REX21 example_REX22 is_VBZ currently_RR changing_VVG its_APPGE R_ZZ1 &D;_NULL structure_NN1 away_II21 from_II22 free_JJ studies_NN2 toward_II a_AT1 centered_JJ approach_NN1 in_II close_JJ relation_NN1 with_IW products_NN2 and_CC production_NN1 ._. 
</s>
<s>
This_DD1 new_JJ center_NN1 is_VBZ located_VVN in_II Sindelfingen_NP1 ,_, which_DDQ is_VBZ now_RT the_AT main_JJ research_NN1 location_NN1 for_IF Daimler_NP1 (_( Haake_NP1 ,_, 2009_MC )_) ._. 
</s>
<s>
Cooperation_NN1 with_IW universities_NN2 allows_VVZ companies_NN2 to_TO harvest_VVI knowledge_NN1 spillovers_NN2 and_CC facilitates_VVZ the_AT recruiting_NN1 of_IO highly_RR qualified_JJ employees_NN2 ._. 
</s>
<s>
One_MC1 example_NN1 for_IF this_DD1 development_NN1 in_II Stuttgart_NP1 is_VBZ the_AT "_" exhaust_NN1 researching_VVG "_" center_NN1 in_II Weissach_NP1 ,_, founded_VVN by_II Audi_NP1 ,_, BMW_NP1 ,_, Daimler_NP1 ,_, Porsche_NP1 ,_, and_CC Volkswagen_NP1 ._. 
</s>
<s>
Highly_RR complex_JJ research_NN1 projects_NN2 are_VBR more_RGR likely_JJ to_TO get_VVI outsourced_VVN to_II specialized_JJ service_NN1 contractors_NN2 or_CC classical_JJ suppliers_NN2 ._. 
</s>
<s>
In_II the_AT region_NN1 of_IO Stuttgart_NP1 15_MC main_JJ research_NN1 contractors_NN2 can_VM be_VBI identified_VVN ;_; ten_MC with_IW more_DAR than_CSN 200_MC employees_NN2 and_CC internationalized_JJ operations_NN2 ._. 
</s>
<s>
Examples_NN2 include_VV0 Bertrandt_NP1 AG_FO in_II Ehningen_NN1 with_IW around_RG 8000_MC employees_NN2 worldwide_RL and_CC the_AT MBtech_NN1 Group_NN1 in_II Sindelfingen_NN1 with_IW approximately_RR 2600_MC employees._NNU 3.4_MC Analysis_NN1 of_IO Benefits_NN2 for_IF Production_NN1 As_CSA described_VVN in_II the_AT theoretical_JJ part_NN1 ,_, employees_NN2 are_VBR crucial_JJ agents_NN2 for_IF the_AT presence_NN1 of_IO a_AT1 successful_JJ cluster_NN1 ._. 
</s>
<s>
Obtaining_VVG skilled_JJ and_CC experienced_JJ workers_NN2 is_VBZ made_VVN relatively_RR easy_JJ by_II the_AT local_JJ government_NN1 of_IO Stuttgart_NP1 ._. 
</s>
<s>
Workers_NN2 can_VM be_VBI recruited_VVN from_II different_JJ sources_NN2 ,_, such_II21 as_II22 specialized_JJ schools_NN2 and_CC universities_NN2 Local_NN1 outsourcing_NN1 is_VBZ deemed_VVN as_RG more_RGR efficient_JJ and_CC effective_JJ compared_VVN to_II distant_JJ outsourcing_NN1 ._. 
</s>
<s>
In_II the_AT region_NN1 numerous_JJ specialized_JJ suppliers_NN2 make_VV0 this_DD1 possible_JJ ._. 
</s>
<s>
The_AT proximity_NN1 of_IO locations_NN2 is_VBZ time_NNT1 and_CC cost-saving_NN1 ;_; in_RR21 addition_RR22 shorter_JJR and_CC more_RGR developed_JJ routes_NN2 reduce_VV0 transportation_NN1 costs_NN2 ._. 
</s>
<s>
Some_DD roads_NN2 have_VH0 been_VBN specifically_RR adapted_VVN to_TO suit_VVI the_AT needs_NN2 of_IO frequent_JJ heavy_JJ haulage_NN1 ._. 
</s>
<s>
Railroad_NN1 systems_NN2 leading_VVG into_II the_AT manufacturing_NN1 sites_NN2 and_CC direct_JJ connection_NN1 to_II the_AT German_JJ railways_NN2 facilitate_VV0 the_AT transportation_NN1 as_RR21 well_RR22 ._. 
</s>
<s>
To_TO illustrate_VVI the_AT closeness_NN1 of_IO locations_NN2 ,_, one_PN1 can_VM take_VVI the_AT distance_NN1 from_II the_AT Bosch_NP1 Headquarters_NN in_II Gerlingen_NP1 to_II the_AT Porsche_NP1 headquarters_NN in_II Zuffenhausen_NP1 ,_, which_DDQ is_VBZ 10_MC km_NNU ._. 
</s>
<s>
This_DD1 makes_VVZ just-in-time_JJ delivery_NN1 possible_JJ and_CC the_AT highly_RR developed_JJ railways_NN2 enhance_VV0 it_PPH1 ._. 
</s>
<s>
Many_DA2 locally_RR headquartered_VVD firms_NN2 ,_, e.g._REX Eisenmann_NP1 who_PNQS provides_VVZ varnishing_VVG and_CC other_JJ facilities_NN2 ,_, as_II31 well_II32 as_II33 resources_NN2 and_CC suppliers_NN2 are_VBR readily_RR available_JJ ._. 
</s>
<s>
Companies_NN2 are_VBR mutually_RR dependent_JJ ,_, due_II21 to_II22 interconnectedness_NN1 ,_, supply_NN1 and_CC demand_NN1 of_IO labor_NN1 ._. 
</s>
<s>
Complementing_VVG products_NN2 in_II clusters_NN2 benefit_VV0 production_NN1 since_CS they_PPHS2 do_VD0 increase_VVI the_AT possibilities_NN2 available_JJ to_II the_AT customers_NN2 ._. 
</s>
<s>
For_REX21 instance_REX22 ,_, Mercedes_NP manufacturing_NN1 in_II Stuttgart_NP1 is_VBZ complemented_VVN by_II AMG_NP1 ,_, which_DDQ enhances_VVZ the_AT standard_JJ cars_NN2 (_( Daimler_NP1 AG_FO )_) ._. 
</s>
<s>
Local_JJ rivalry_NN1 between_II Daimler_NP1 and_CC Porsche_NP1 benefits_NN2 the_AT development_NN1 of_IO more_RGR efficient_JJ luxury_JJ vehicles_NN2 such_II21 as_II22 the_AT new_JJ electronic_JJ engines_NN2 for_IF Porsche_NP1 or_CC hybrid_JJ Mercedes_NP S_NP1 400_MC ._. 
</s>
<s>
It_PPH1 drives_VVZ both_RR companies_NN2 to_TO innovate_VVI more_RGR rapidly_RR and_CC produce_VVI products_NN2 that_CST better_JJR meet_NN1 customer_NN1 needs_NN2 ._. 
</s>
<s>
The_AT local_JJ infrastructure_NN1 corresponds_VVZ to_II the_AT needs_NN2 of_IO the_AT companies_NN2 and_CC employees_NN2 ._. 
</s>
<s>
For_REX21 example_REX22 the_AT city_NN1 of_IO Sindelfingen_NP1 re-planned_VVD roads_NN2 so_CS Daimler_NP1 can_VM build_VVI a_AT1 new_JJ R_ZZ1 &D;_NULL center_NN1 ,_, bus_NN1 timetables_NN2 and_CC traffic_NN1 lights_NN2 are_VBR adjusted_VVN to_II when_RRQ manufacturing_NN1 shifts_NN2 begin_VV0 and_CC end._NNU 4_MC Conclusion_NN1 This_DD1 Seminar_NN1 Paper_NN1 has_VHZ shown_VVN that_DD1 clustering_NN1 benefits_NN2 cities_NN2 ,_, regions_NN2 ,_, and_CC the_AT overall_JJ economy_NN1 and_CC ultimately_RR fosters_VVZ growth_NN1 ._. 
</s>
<s>
Clusters_NN2 benefit_VV0 production_NN1 by_II saving_VVG costs_NN2 and_CC time_NNT1 ,_, by_II making_VVG available_JJ resources_NN2 in_II proximity_NN1 and_CC by_II providing_VVG an_AT1 adequate_JJ infrastructure_NN1 ._. 
</s>
<s>
It_PPH1 fosters_VVZ innovation_NN1 by_II creating_VVG knowledge-spillovers_NN2 ,_, enabling_VVG access_NN1 to_II financial_JJ capital_NN1 for_IF investments_NN2 ,_, and_CC enhancing_VVG the_AT creation_NN1 of_IO start-ups_NN2 ._. 
</s>
<s>
Furthermore_RR ,_, demanding_VVG customers_NN2 of_IO the_AT cluster_NN1 can_VM help_VVI to_TO enhance_VVI certain_JJ trends_NN2 ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO answer_VVI the_AT question_NN1 about_II the_AT role_NN1 of_IO the_AT German_JJ automotive_JJ cluster_NN1 with_II31 respect_II32 to_II33 innovation_NN1 and_CC production_NN1 ,_, the_AT most_RGT likely_JJ scenario_NN1 is_VBZ that_DD1 production_NN1 fosters_VVZ innovation_NN1 and_CC vice-versa_RR ._. 
</s>
<s>
When_CS evidence_NN1 of_IO clusters_NN2 can_VM be_VBI found_VVN ,_, it_PPH1 indicates_VVZ higher_JJR productivity_NN1 ,_, but_CCB the_AT exact_JJ impact_NN1 of_IO production_NN1 is_VBZ difficult_JJ to_TO measure_VVI ._. 
</s>
<s>
However_RR ,_, the_AT location_NN1 advantage_NN1 of_IO production_NN1 is_VBZ not_XX solely_RR determined_VVN by_II productivity_NN1 ._. 
</s>
<s>
The_AT highly_RR specialized_JJ parts_NN2 ,_, in_II which_DDQ extensive_JJ knowledge_NN1 is_VBZ required_VVN ,_, are_VBR likely_JJ to_TO be_VBI sustained_VVN and_CC kept_VVN in_II Germany_NP1 ._. 
</s>
<s>
It_PPH1 can_VM be_VBI said_VVN that_CST in_II the_AT future_NN1 ,_, innovation_NN1 will_VM continue_VVI to_TO play_VVI a_AT1 major_JJ role_NN1 in_II the_AT German_JJ automotive_JJ industry_NN1 cluster_NN1 and_CC that_CST this_DD1 trend_NN1 is_VBZ more_RGR evident_JJ than_CSN the_AT future_NN1 of_IO the_AT production_NN1 location_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ very_RG likely_JJ that_CST especially_RR the_AT production_NN1 of_IO the_AT more_RGR expensive_JJ models_NN2 will_VM be_VBI kept_VVN in_II Germany_NP1 in_II order_NN1 sustain_VV0 a_AT1 high-profile_JJ image_NN1 of_IO certain_JJ OEMs_NP2 ._. 
</s>
<s>
It_PPH1 can_VM be_VBI concluded_VVN that_CST scientific_JJ research_NN1 strongly_RR indicates_VVZ several_DA2 benefits_NN2 of_IO clustering_NN1 for_IF productivity_NN1 ._. 
</s>
<s>
The_AT only_JJ main_JJ disadvantages_NN2 of_IO the_AT Stuttgart_NP1 cluster_NN1 and_CC the_AT German_JJ automotive_JJ location_NN1 as_II a_AT1 whole_NN1 are_VBR high_JJ costs_NN2 for_IF labor_NN1 ,_, manufacturing_NN1 and_CC taxes_NN2 ._. 
</s>
<s>
The_AT main_JJ advantages_NN2 are_VBR the_AT availability_NN1 of_IO high_JJ quality_NN1 specialized_JJ workers_NN2 and_CC the_AT presence_NN1 of_IO research_NN1 competence_NN1 ,_, innovation_NN1 and_CC technological_JJ advance_NN1 ._. 
</s>
<s>
Furthermore_RR ,_, the_AT availability_NN1 of_IO specialized_JJ production_NN1 inputs_NN2 and_CC equipment_NN1 ,_, high-skilled_JJ suppliers_NN2 with_IW close_JJ cooperation_NN1 represents_VVZ a_AT1 main_JJ advantage_NN1 ._. 
</s>
<s>
Another_DD1 advantage_NN1 is_VBZ the_AT presence_NN1 of_IO infrastructure_NN1 ,_, political_JJ and_CC social_JJ stability_NN1 ,_, institutional_JJ certainty_NN1 and_CC property_NN1 rights_NN2 ._. 
</s>
<s>
Whether_CSW production_NN1 will_VM remain_VVI in_II Germany_NP1 primarily_RR depends_VVZ on_II the_AT ability_NN1 to_TO compensate_VVI high_JJ wages_NN2 with_IW high_JJ productivity_NN1 ._. 
</s>
<s>
Recent_JJ developments_NN2 have_VH0 been_VBN beneficial_JJ in_II that_DD1 respect_NN1 :_: From_II 2000_MC to_II 2008_MC ,_, productivity_NN1 gains_NN2 in_II the_AT German_JJ automobile_NN1 industry_NN1 have_VH0 outpaced_VVN real_JJ wage_NN1 rises_NN2 (_( Economist_NN1 ,_, 2010_MC ,_, p._NN1 6_MC )_) ._. 
</s>
<s>
If_CS (_( BBC_NP1 ,_, 2010_MC )_) this_DD1 development_NN1 continues_VVZ in_II the_AT future_NN1 ,_, Germany_NP1 as_II a_AT1 location_NN1 for_IF production_NN1 and_CC innovation_NN1 will_VM be_VBI able_JK to_TO compete_VVI against_II advantages_NN2 of_IO low-cost_JJ countries_NN2 ._. 
</s>
