<s>
Logistical_JJ solutions_NN2 on_II negative_JJ environmental_JJ impact-theory_NN1 vs._II practice_NN1 1_MC1 ._. 
</s>
<s>
Introduction_NN1 Environmental_JJ awareness_NN1 ,_, as_II31 well_II32 as_II33 the_AT importance_NN1 of_IO environmental_JJ sustainability_NN1 ,_, is_VBZ increasing_VVG ._. 
</s>
<s>
This_DD1 has_VHZ led_VVN to_II developments_NN2 and_CC improvements_NN2 in_II logistics_NN1 ,_, since_CS companies_NN2 '_GE negative_JJ environmental_JJ impact_NN1 usually_RR comes_VVZ from_II logistical_JJ conditions_NN2 ,_, e.g._REX transporting_VVG and_CC warehousing_NN1 ._. 
</s>
<s>
Effective_JJ logistical_JJ systems_NN2 are_VBR a_AT1 necessity_NN1 for_IF well-functioning_JJ societies_NN2 and_CC companies_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ also_RR generally_RR accepted_VVN that_CST the_AT rate_NN1 at_II which_DDQ we_PPIS2 use_VV0 our_APPGE natural_JJ resources_NN2 is_VBZ not_XX sustainable_JJ ,_, other_JJ solutions_NN2 must_VM be_VBI found_VVN ._. 
</s>
<s>
With_IW ever_RR increasing_JJ transports_NN2 of_IO goods_NN2 ,_, logistics_NN1 is_VBZ considered_VVN one_MC1 of_IO the_AT bigger_JJR environmental_JJ threats_NN2 ._. 
</s>
<s>
At_II the_AT same_DA time_NNT1 ,_, logistical_JJ systems_NN2 give_VV0 opportunities_NN2 to_TO improve_VVI the_AT environmental_JJ impact_NN1 (_( Storhagen_NP1 2003_MC )_) ._. 
</s>
<s>
Even_CS21 though_CS22 technology_NN1 has_VHZ improved_VVN ,_, cars_NN2 and_CC trucks_NN2 pollute_VV0 less_RRR ,_, the_AT increased_JJ amounts_NN2 of_IO goods_NN2 being_VBG transported_VVN has_VHZ led_VVN to_II an_AT1 overall_JJ increase_NN1 of_IO emissions_NN2 (_( Aronsson_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2006_MC )_) ._. 
</s>
<s>
Research_NN1 on_II how_RRQ to_TO improve_VVI the_AT negative_JJ impact_NN1 on_II the_AT environment_NN1 through_II logistical_JJ structures_NN2 is_VBZ insufficient_JJ ._. 
</s>
<s>
There_EX are_VBR not_XX enough_DD case_NN1 studies_NN2 on_II ways_NN2 companies_NN2 actually_RR handle_VV0 these_DD2 environmental_JJ issues_NN2 or_CC create_VV0 new_JJ possibilities_NN2 ._. 
</s>
<s>
The_AT world_NN1 is_VBZ changing_VVG ,_, there_EX are_VBR new_JJ demands_NN2 with_IW new_JJ threats_NN2 on_II the_AT environment_NN1 ,_, which_DDQ means_VVZ that_CST new_JJ solutions_NN2 for_IF improvements_NN2 are_VBR needed_VVN ._. 
</s>
<s>
While_CS the_AT bulk_NN1 of_IO modern_JJ transportation_NN1 of_IO wares_NN2 is_VBZ done_VDN using_VVG fossil_NN1 fuel_NN1 based_VVN vehicles_NN2 ,_, the_AT question_NN1 of_IO carbon_NN1 and_CC other_JJ dangerous_JJ emissions_NN2 will_VM always_RR be_VBI on_II31 top_II32 of_II33 the_AT agenda_NN1 ._. 
</s>
<s>
The_AT purpose_NN1 of_IO this_DD1 paper_NN1 is_VBZ to_TO gather_VVI and_CC compare_VVI theoretical_JJ and_CC practical_JJ information_NN1 on_II improving_VVG environmental_JJ impact_NN1 through_II logistical_JJ solutions_NN2 ,_, to_TO answer_VVI the_AT question_NN1 ;_; how_RRQ does_VDZ theory_NN1 and_CC practice_NN1 differ_VV0 ?_? 
</s>
<s>
The_AT paper_NN1 will_VM be_VBI delimited_VVN to_II what_DDQ logistical_JJ solutions_NN2 are_VBR Itella_NP1 Oyj_NP1 using_VVG ._. 
</s>
<s>
This_DD1 paper_NN1 is_VBZ arranged_VVN in_II four_MC different_JJ sections_NN2 ._. 
</s>
<s>
The_AT first_MD section_NN1 will_VM be_VBI a_AT1 short_JJ review_NN1 of_IO the_AT negative_JJ impact_NN1 transporting_VVG goods_NN2 has_VHZ on_II the_AT environment_NN1 ._. 
</s>
<s>
The_AT second_MD part_NN1 will_VM be_VBI a_AT1 theoretical_JJ overview_NN1 on_II different_JJ logistical_JJ solutions_NN2 on_II minimizing_VVG the_AT environmental_JJ impact_NN1 of_IO transportation_NN1 and_CC warehousing_NN1 (_( Storhagen_NP1 2003_MC )_) and_CC (_( Aronsson_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2006_MC )_) ._. 
</s>
<s>
The_AT third_MD section_NN1 will_VM examine_VVI what_DDQ logistical_JJ solutions_NN2 Itella_NP1 Oyj_NP1 have_VH0 used_VVN to_TO minimize_VVI the_AT negative_JJ impacts_NN2 on_II the_AT environment_NN1 ._. 
</s>
<s>
The_AT last_MD part_NN1 will_VM be_VBI a_AT1 discussion_NN1 and_CC a_AT1 conclusion_NN1 about_II the_AT solutions_NN2 made_VVD ._. 
</s>
<s>
2_MC ._. 
</s>
<s>
Environmental_JJ impact_NN1 Logistics_NN1 is_VBZ the_AT management_NN1 of_IO physical_JJ ,_, informational_JJ ,_, cash_NN1 and_CC reverse_JJ flow_NN1 ,_, within_II as_RG well_RR as_CSA between_II different_JJ stations_NN2 and_CC stakeholders_NN2 ,_, (_( e.g._REX managing_VVG the_AT flow_NN1 from_II raw-material_NN1 to_II a_AT1 finished_JJ product_NN1 to_II delivery_NN1 to_II the_AT customer_NN1 )_) ._. 
</s>
<s>
The_AT purpose_NN1 of_IO logistics_NN1 is_VBZ to_TO maximize_VVI flow_NN1 efficiencies_NN2 (_( Storhagen_NP1 ,_, 2003_MC p._NNU 32_MC )_) ._. 
</s>
<s>
Different_JJ areas_NN2 of_IO logistics_NN1 are_VBR transportation_NN1 ,_, inventory_NN1 ,_, warehousing_NN1 ,_, material_NN1 handling_NN1 and_CC packaging_NN1 (_( Wikipedia_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
These_DD2 all_RR affect_VV0 the_AT environment_NN1 ,_, especially_RR transportation_NN1 of_IO goods_NN2 with_IW its_APPGE emissions_NN2 ._. 
</s>
<s>
Pollution_NN1 can_VM come_VVI in_II a_AT1 lot_NN1 of_IO different_JJ forms_NN2 and_CC have_VH0 a_AT1 local_JJ ,_, regional_JJ and_CC global_JJ impact_NN1 ._. 
</s>
<s>
Emissions_NN2 of_IO greenhouse_NN1 gases_NN2 ,_, like_II e.g._REX carbon_NN1 dioxide_NN1 (_( CO2_FO )_) ,_, and_CC nitric_JJ oxide_NN1 (_( NO_UH )_) cause_VV0 climate_NN1 change_NN1 ,_, and_CC pollution_NN1 in_II the_AT air_NN1 ,_, ground_NN1 and_CC water_NN1 ._. 
</s>
<s>
Also_RR waste_VV0 ,_, noise_NN1 and_CC bad_JJ smells_NN2 are_VBR considered_VVN as_CSA pollution_NN1 ._. 
</s>
<s>
Infrastructure_NN1 also_RR has_VHZ environmental_JJ impacts_NN2 due_II21 to_II22 the_AT need_NN1 for_IF building_NN1 roads_NN2 ,_, railways_NN2 and_CC the_AT companies_NN2 different_JJ premises_NN2 (_( Storhagen_NP1 ,_, 2003_MC p.272-273_MC )_) ._. 
</s>
<s>
This_DD1 in_II turn_NN1 leads_VVZ to_II destruction_NN1 or_CC loss_NN1 of_IO biodiversity_NN1 and_CC different_JJ kinds_NN2 of_IO ecosystems_NN2 (_( Erlandsson_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2008_MC )_) ._. 
</s>
<s>
In_II the_AT year_NNT1 of_IO 2009_MC ,_, the_AT emissions_NN2 of_IO greenhouse_NN1 gases_NN2 were_VBDR 66.3_MC million_NNO Carbon_NN1 dioxide_NN1 equivalents_NN2 (_( CO2e_FO ,_, a_AT1 measurement_NN1 for_IF the_AT emissions_NN2 of_IO greenhouse_NN1 gases_NN2 )_) in_II Finland_NP1 ._. 
</s>
<s>
This_DD1 was_VBDZ a_AT1 decrease_NN1 of_IO 5.8_MC per_NNU21 cent_NNU22 from_II the_AT year_NNT1 before_CS and_CC could_VM ,_, according_II21 to_II22 Pipatti_NP1 ,_, be_VBI an_AT1 effect_NN1 from_II the_AT economic_JJ recession_NN1 during_II that_DD1 time_NNT1 ._. 
</s>
<s>
It_PPH1 was_VBDZ also_RR about_RG 7_MC per_NNU21 cent_NNU22 below_II the_AT Kyoto_NP1 protocol_NN1 goal_NN1 ._. 
</s>
<s>
Energy_NN1 consumption_NN1 within_II the_AT industry_NN1 accounts_VVZ for_IF the_AT largest_JJT decrease_NN1 of_IO emissions_NN2 by_II 23_MC per_NNU21 cent_NNU22 ._. 
</s>
<s>
The_AT decrease_NN1 in_II emissions_NN2 caused_VVN by_II transportation_NN1 was_VBDZ 5_MC per_NNU21 cent_NNU22 ,_, which_DDQ partly_RR can_VM be_VBI explained_VVN by_II the_AT recession_NN1 and_CC partly_RR by_II using_VVG biofuels_NN2 ._. 
</s>
<s>
Emissions_NN2 caused_VVN by_II waste_NN1 decreased_VVN by_II 4_MC percent_NNU while_CS the_AT emissions_NN2 caused_VVN by_II the_AT usage_NN1 of_IO electricity_NN1 and_CC heating_NN1 had_VHD increased_VVN by_II 5_MC (_( Pipatti_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
3_MC ._. 
</s>
<s>
Logistical_JJ solutions_NN2 The_AT different_JJ literatures_NN2 suggests_VVZ quite_RG similar_JJ logistical_JJ systems_NN2 as_CSA solutions_NN2 on_II minimizing_VVG environmental_JJ impact_NN1 ,_, but_CCB also_RR mention_VV0 that_CST one_PN1 needs_VVZ to_TO put_VVI it_PPH1 into_II a_AT1 broader_JJR perspective_NN1 ,_, that_DD1 different_JJ organizational_JJ levels_NN2 have_VH0 different_JJ impact_NN1 ._. 
</s>
<s>
According_II21 to_II22 Aronsson_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
the_AT relationship_NN1 between_II operational_JJ effectiveness_NN1 and_CC environmental_JJ aspects_NN2 is_VBZ very_RG important_JJ to_TO understand_VVI ,_, since_CS the_AT decisions_NN2 made_VVN on_II different_JJ levels_NN2 affect_VV0 both_DB2 ._. 
</s>
<s>
(_( Aronsson_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2006_MC )_) There_EX is_VBZ no_AT question_NN1 that_CST transportation_NN1 of_IO goods_NN2 has_VHZ a_AT1 negative_JJ impact_NN1 on_II the_AT environment_NN1 but_CCB according_II21 to_II22 Storhagen_NP1 there_EX are_VBR many_DA2 things_NN2 one_PN1 can_VM do_VDI to_TO improve_VVI the_AT situation_NN1 ._. 
</s>
<s>
A_AT1 simple_JJ thing_NN1 is_VBZ to_TO consider_VVI more_RGR environmentally_RR friendly_JJ options_NN2 like_II using_VVG trains_NN2 instead_II21 of_II22 trucks_NN2 ,_, or_CC combining_VVG them_PPHO2 when_RRQ possible_JJ ._. 
</s>
<s>
Also_RR choosing_VVG vehicles_NN2 using_VVG biofuels_NN2 instead_II21 of_II22 fossil-fuels_NN2 is_VBZ a_AT1 way_NN1 (_( Storhagen_NP1 ,_, 2003_MC p._NNU 273-274_MCMC )_) ._. 
</s>
<s>
Using_VVG rail_NN1 transportation_NN1 also_RR enables_VVZ the_AT company_NN1 to_TO transport_VVI a_AT1 larger_JJR amount_NN1 of_IO goods_NN2 ._. 
</s>
<s>
(_( Aronsson_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2006_MC )_) Technical_JJ developments_NN2 of_IO the_AT vehicles_NN2 have_VH0 made_VVN them_PPHO2 better_RRR and_CC the_AT choice_NN1 of_IO vehicle_NN1 can_VM make_VVI quite_RG a_AT1 difference_NN1 ._. 
</s>
<s>
Things_NN2 like_II the_AT vehicle_NN1 's_GE motor_NN1 ,_, weight_NN1 and_CC its_APPGE air_NN1 resistance_NN1 can_VM have_VHI an_AT1 impact_NN1 on_II how_RGQ much_DA1 fuel_NN1 it_PPH1 consumes_VVZ and_CC how_RGQ much_DA1 emissions_NN2 it_PPH1 emits_VVZ ._. 
</s>
<s>
Another_DD1 thing_NN1 to_TO think_VVI about_II is_VBZ how_RGQ much_DA1 of_IO the_AT vehicle_NN1 is_VBZ recyclable_JJ and_CC of_RR21 course_RR22 the_AT way_NN1 it_PPH1 is_VBZ used_VVN ._. 
</s>
<s>
With_IW capable_JJ drivers_NN2 and_CC route_NN1 planning_NN1 ,_, a_AT1 lot_NN1 of_IO fuel_NN1 can_VM be_VBI saved_VVN and_CC damages_NN2 can_VM be_VBI kept_VVN to_II a_AT1 minimum_NN1 (_( Storhagen_NP1 ,_, 2003_MC p._NNU 273-274_MCMC )_) ._. 
</s>
<s>
Physical_JJ standardizations_NN2 of_IO transport_NN1 vehicles_NN2 and_CC load_VV0 carriers_NN2 makes_VVZ the_AT whole_JJ delivery-process_NN1 easier_RRR since_CS they_PPHS2 can_VM be_VBI reused_VVN and_CC no_AT extra_JJ time_NNT1 has_VHZ to_TO be_VBI spent_VVN on_II finding_VVG the_AT right_JJ vehicle_NN1 for_IF the_AT right_JJ load_NN1 carrier_NN1 ._. 
</s>
<s>
Standardization_NN1 of_IO these_DD2 would_VM also_RR mean_VVI that_CST one_PN1 can_VM standardize_VVI the_AT loading_NN1 and_CC handling_VVG equipment_NN1 as_RR21 well_RR22 ._. 
</s>
<s>
This_DD1 also_RR leads_VVZ to_II increased_JJ fill_NN1 rates_NN2 ,_, which_DDQ leads_VVZ to_II fewer_DAR deliveries_NN2 and_CC a_AT1 reduced_JJ environmental_JJ impact_NN1 (_( Aronsson_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2006_MC )_) ._. 
</s>
<s>
Increase_VV0 fill_VV0 rate_NN1 or_CC consolidation_NN1 is_VBZ good_JJ solution_NN1 since_CS that_DD1 would_VM decrease_VVI the_AT number_NN1 of_IO vehicles_NN2 driving_VVG only_RR half-full_JJ ._. 
</s>
<s>
Aronsson_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
give_VV0 different_JJ examples_NN2 on_II how_RRQ to_TO increase_VVI the_AT fill_NN1 rate_NN1 through_II changes_NN2 to_II the_AT logistics_NN1 infrastructure_NN1 ,_, e.g._REX increasing_VVG the_AT size_NN1 of_IO warehouses_NN2 and_CC at_II the_AT same_DA time_NNT1 reduce_VV0 the_AT number_NN1 of_IO them_PPHO2 ._. 
</s>
<s>
Changing_VVG the_AT location_NN1 of_IO a_AT1 warehouse_NN1 ,_, to_TO centralize_VVI the_AT whole_JJ distribution_NN1 to_TO reduce_VVI the_AT amounts_NN2 of_IO deliveries_NN2 made_VVN to_II fewer_DAR but_CCB full_JJ (_( Aronsson_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2006_MC )_) ._. 
</s>
<s>
Other_JJ ways_NN2 of_IO increasing_JJ fill_NN1 rates_NN2 are_VBR careful_JJ route_NN1 planning_NN1 and_CC having_VHG longer_JJR lead_VVN times_NNT2 ,_, so_CS that_DD1 transports_VVZ will_VM be_VBI made_VVN first_MD when_CS vehicles_NN2 can_VM be_VBI fully_RR loaded_VVN ._. 
</s>
<s>
Consolidation_NN1 ,_, (_( carpooling_VVG for_IF products_NN2 )_) ,_, between_II companies_NN2 with_IW similar_JJ products_NN2 and_CC delivery_NN1 routes_NN2 will_VM again_RT reduce_VVI the_AT amounts_NN2 of_IO deliveries_NN2 made_VVD ._. 
</s>
<s>
Consolidation_NN1 also_RR saves_VVZ companies_NN2 money_NN1 since_CS they_PPHS2 can_VM split_VVI the_AT cost_NN1 and_CC there_EX is_VBZ no_AT need_NN1 for_IF driving_VVG every_AT1 day_NNT1 ._. 
</s>
<s>
Repacking_VVG the_AT goods_NN2 so_RG more_DAR of_IO them_PPHO2 fit_VV0 in_II a_AT1 vehicle_NN1 also_RR increases_VVZ the_AT fill_NN1 rate_NN1 (_( Aronsson_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2006_MC )_) ._. 
</s>
<s>
It_PPH1 is_VBZ also_RR very_RG important_JJ to_TO use_VVI different_JJ IT_NN1 technologies_NN2 ,_, since_CS they_PPHS2 help_VV0 to_TO collect_VVI information_NN1 ,_, e.g._REX updates_NN2 on_II supply_NN1 and_CC demand_NN1 ,_, which_DDQ leads_VVZ to_II more_RGR efficient_JJ planning_NN1 ._. 
</s>
<s>
Route_NN1 planning_NN1 and_CC leads_VVZ to_II less_DAR back_NN1 and_CC forth_RR driving_JJ and_CC that_CST traffic-jams_NN2 or_CC other_JJ disturbances_NN2 can_VM better_RRR be_VBI avoided_VVN (_( Storhagen_NP1 ,_, 2003_MC ,_, p._NN1 274_MC )_) ._. 
</s>
<s>
Product_NN1 management_NN1 and_CC a_AT1 larger_JJR control_NN1 over_II the_AT flows_NN2 make_VV0 it_PPH1 easier_JJR to_TO plan_VVI earlier_RRR which_DDQ products_NN2 have_VH0 to_TO be_VBI delivered_VVN where_RRQ ,_, which_DDQ leads_VVZ to_II fewer_DAR transports_NN2 ._. 
</s>
<s>
Using_VVG technology_NN1 to_TO follow_VVI the_AT deliveries_NN2 makes_VVZ increases_NN2 safety_NN1 and_CC also_RR makes_VVZ it_PPH1 easier_JJR to_TO make_VVI changes_NN2 mid_JJ delivery_NN1 (_( Aronsson_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2006_MC )_) ._. 
</s>
<s>
Different_JJ measures_NN2 taken_VVN by_II the_AT government_NN1 can_VM also_RR help_VVI ._. 
</s>
<s>
Building_VVG better_JJR infrastructure_NN1 (_( e.g._REX roads_NN2 ,_, tunnels_NN2 ,_, bridges_NN2 ,_, railways_NN2 and_CC ports_NN2 )_) can_VM for_REX21 instance_REX22 decrease_VVI traffic-jams_NN2 ,_, which_DDQ has_VHZ a_AT1 negative_JJ impact_NN1 on_II the_AT environment_NN1 because_II21 of_II22 more_DAR emissions_NN2 ._. 
</s>
<s>
Regulations_NN2 and_CC fees_NN2 are_VBR also_RR a_AT1 way_NN1 for_IF the_AT government_NN1 to_TO control_VVI the_AT amount_NN1 of_IO transportation_NN1 ._. 
</s>
<s>
Laws_NN2 to_TO regulate_VVI which_DDQ vehicles_NN2 must_VM be_VBI used_VVN in_II transporting_VVG different_JJ kinds_NN2 of_IO goods_NN2 and_CC fees_NN2 to_TO regulate_VVI the_AT amount_NN1 of_IO traffic_NN1 in_II e.g._REX cities_NN2 (_( Storhagen_NP1 ,_, 2003_MC p._NNU 274_MC )_) ._. 
</s>
<s>
In_II Finland_NP1 ,_, the_AT Environmental_JJ Protection_NN1 Act_NN1 (_( Miljskyddslag_VV0 4.2.2000/86_MF )_) was_VBDZ stipulated_VVN to_TO prevent_VVI the_AT pollution_NN1 of_IO the_AT environment_NN1 and_CC reduce_VV0 the_AT damage_NN1 caused_VVN by_II pollution_NN1 for_IF a_AT1 sustainable_JJ development_NN1 (_( Finlex._NP1 2011_MC )_) ._. 
</s>
<s>
Revers_NP1 logistics_NN1 has_VHZ become_VVN a_AT1 more_RGR important_JJ part_NN1 of_IO the_AT flow_NN1 chain_NN1 ,_, since_CS it_PPH1 brings_VVZ the_AT chain_NN1 back_RP to_II the_AT beginning_NN1 though_CS recycling_VVG and_CC reuse_VV0 (_( Storhagen_NP1 ,_, 2003_MC p._NNU 275_MC )_) ._. 
</s>
<s>
The_AT waste_NN1 law_NN1 (_( Afallslag_VV0 646/2011_MF )_) was_VBDZ stipulated_VVN to_TO prevent_VVI danger_NN1 and_CC harm_VVI to_II health_NN1 and_CC the_AT environment_NN1 due_JJ waste_NN1 ,_, through_II reducing_VVG the_AT quantity_NN1 of_IO waste_NN1 and_CC promoting_VVG sustainable_JJ use_NN1 of_IO natural_JJ resources_NN2 ._. 
</s>
<s>
The_AT waste_NN1 law_NN1 also_RR stipulates_VVZ that_CST the_AT producers_NN2 of_IO products_NN2 which_DDQ cause_VV0 waste_NN1 have_VH0 to_TO make_VVI sure_JJ that_CST the_AT product_NN1 and_CC the_AT way_NN1 it_PPH1 is_VBZ produced_VVN not_XX harmful_JJ ._. 
</s>
<s>
Nor_CC should_VM the_AT producers_NN2 use_VVI excessive_JJ packaging_NN1 ,_, they_PPHS2 should_VM recycle_VVI and_CC make_VVI sure_JJ to_TO inform_VVI their_APPGE customers_NN2 ow_VV0 how_RRQ to_TO recycle_VVI their_APPGE product_NN1 (_( Finlex_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
Transportation_NN1 carriers_NN2 which_DDQ can_VM be_VBI used_VVN again_RT is_VBZ an_AT1 easy_JJ way_NN1 to_TO start_VVI (_( Storhagen_NP1 ,_, 2003_MC p._NNU 277_MC )_) ._. 
</s>
<s>
4_MC ._. 
</s>
<s>
Itella_NP1 Oyj_NP1 's_GE solutions_NN2 Itella_NP1 Oyj_NP1 manages_VVZ the_AT flow_NN1 of_IO information_NN1 and_CC products_NN2 ._. 
</s>
<s>
Itella_NN1 consists_VVZ of_IO three_MC business_NN1 groups_NN2 ;_; Itella_NP1 Mail_NN1 Communications_NN2 ,_, Itella_NP1 Information_NN1 ,_, and_CC Itella_NP1 Logistics_NN1 ._. 
</s>
<s>
Itella_NN1 Mail_NN1 Communications_NN2 maintains_VVZ the_AT daily_JJ postal_JJ services_NN2 in_II Finland_NP1 ,_, which_DDQ is_VBZ their_APPGE primary_JJ role_NN1 ._. 
</s>
<s>
They_PPHS2 also_RR provide_VV0 companies_NN2 in_II Finland_NP1 and_CC Russia_NP1 with_IW marketing_NN1 solutions_NN2 to_TO help_VVI them_PPHO2 better_RRR reach_VVI their_APPGE customers_NN2 ._. 
</s>
<s>
Itella_NN1 information_NN1 helps_VVZ companies_NN2 develop_VVI their_APPGE financial_JJ management_NN1 processes_NN2 ._. 
</s>
<s>
Itella_NN1 Logistics_NN1 operates_VVZ in_II eight_MC different_JJ countries_NN2 and_CC provides_VVZ companies_NN2 logistics_NN1 services_NN2 with_IW different_JJ transportation_NN1 vehicles_NN2 as_II31 well_II32 as_II33 warehousing_NN1 ._. 
</s>
<s>
Itella_NN1 provides_VVZ work_NN1 for_IF 29_MC 000_MC people_NN and_CC their_APPGE turnover_NN1 in_II 2010_MC was_VBDZ 1842_MC million_NNO euro_NN1 (_( Itella_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
Itellas_NP1 solutions_NN2 to_II reducing_VVG are_VBR mainly_RR focused_VVN on_II measures_NN2 taken_VVN in_II Finland_NP1 but_CCB partially_RR also_RR through_II climate_NN1 projects_NN2 abroad_RL ._. 
</s>
<s>
These_DD2 projects_NN2 are_VBR made_VVN in_II countries_NN2 which_DDQ are_VBR not_XX a_AT1 part_NN1 of_IO the_AT Kyoto_NP1 Protocol_NN1 ,_, since_CS these_DD2 countries_NN2 already_RR are_VBR bound_VVNK to_TO reduce_VVI their_APPGE emissions_NN2 ._. 
</s>
<s>
One_MC1 of_IO the_AT projects_NN2 is_VBZ to_TO help_VVI building_NN1 wind_NN1 turbines_NN2 in_II Turkey_NP1 and_CC another_DD1 is_VBZ to_TO build_VVI an_AT1 anaerobic_JJ treatment_NN1 plant_NN1 in_II Thailand_NP1 for_IF recycling_VVG biogas_NN2 ._. 
</s>
<s>
The_AT purpose_NN1 of_IO these_DD2 climate_NN1 projects_NN2 is_VBZ to_TO reduce_VVI the_AT same_DA amount_NN1 of_IO emissions_NN2 ,_, in_II another_DD1 part_NN1 of_IO the_AT world_NN1 ,_, as_CSA Itella_NP1 are_VBR emitting_VVG in_II Finland_NP1 ._. 
</s>
<s>
These_DD2 emissions_NN2 amount_NN1 to_II about_RG 22_MC gram_NNU1 per_II letter_NN1 (_( Itella_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
Minimizing_VVG the_AT negative_JJ impact_NN1 of_IO transporting_VVG all_DB of_IO the_AT letters_NN2 and_CC packages_NN2 Itella_NP1 states_VVZ is_VBZ done_VDN by_II economical_JJ driving_JJ ,_, by_II optimizing_VVG delivery_NN1 routes_NN2 and_CC consolidation_NN1 ._. 
</s>
<s>
They_PPHS2 have_VH0 also_RR participated_VVN in_II the_AT usage_NN1 of_IO new_JJ technical_JJ solutions_NN2 ._. 
</s>
<s>
As_II the_AT first_MD company_NN1 in_II Finland_NP1 ,_, they_PPHS2 stated_VVD using_VVG natural_JJ gas_NN1 vehicles_NN2 already_RR in_II 2006_MC ._. 
</s>
<s>
Natural_JJ gas_NN1 vehicles_NN2 are_VBR a_AT1 cleaner_JJR alternative_NN1 ,_, since_CS they_PPHS2 create_VV0 almost_RR no_AT harmful_JJ micro_NN1 particles_NN2 ,_, and_CC the_AT CO2_FO emissions_NN2 are_VBR about_RG 10_MC percent_NNU lower_JJR ._. 
</s>
<s>
Their_APPGE goal_NN1 is_VBZ to_TO lower_VVI their_APPGE total_NN1 CO2_FO emission_NN1 by_II 30_MC percent_NNU by_II the_AT year_NNT1 2020_MC (_( Itella_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
During_II 2008-2011_MCMC Itella_NP1 has_VHZ also_RR bought_VVN electrical_JJ scooters_NN2 ,_, to_TO try_VVI how_RGQ well_RR these_DD2 can_VM be_VBI used_VVN in_II Finland_NP1 ._. 
</s>
<s>
These_DD2 scooters_NN2 were_VBDR specially_RR designed_VVN for_IF delivering_VVG mail_NN1 and_CC emit_VV0 only_RR 30_MC percent_NNU of_IO what_DDQ a_AT1 normal_JJ scooter_NN1 using_VVG fossil_NN1 fuels_NN2 emits_VVZ ._. 
</s>
<s>
Electrical_JJ scooters_NN2 are_VBR also_RR very_RG quiet_JJ ,_, which_DDQ is_VBZ a_AT1 decrease_NN1 in_II sound_NN1 pollution_NN1 ,_, and_CC nice_JJ for_IF the_AT workers_NN2 as_II31 well_II32 as_II33 the_AT surroundings_NN2 ._. 
</s>
<s>
Itellas_NP1 goal_NN1 is_VBZ that_CST by_II the_AT year_NNT1 2012_MC ,_, 50_MC percent_NNU of_IO all_DB their_APPGE scooters_NN2 should_VM be_VBI electrical_JJ ones_NN2 (_( Itella_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
When_CS using_VVG subcontractors_NN2 ,_, Itella_NP1 uses_VVZ an_AT1 environmental_JJ points-system_NN1 ,_, where_CS the_AT European_JJ emission_NN1 standards_NN2 are_VBR used_VVN for_IF evaluating_VVG the_AT vehicles_NN2 ._. 
</s>
<s>
All_DB of_IO their_APPGE subcontractors_NN2 are_VBR expected_VVN to_TO use_VVI vehicles_NN2 which_DDQ are_VBR of_IO Euro_JJ 3_MC or_CC Euro_JJ 4_MC standard_JJ ._. 
</s>
<s>
The_AT European_JJ emission_NN1 standards_NN2 are_VBR used_VVN to_TO set_VVI exhaust_NN1 limits_VVZ to_II vehicles_NN2 sold_VVN in_II the_AT European_JJ Union_NN1 ._. 
</s>
<s>
There_EX are_VBR different_JJ standards_NN2 depending_VVG partially_RR on_II the_AT type_NN1 of_IO vehicle_NN1 and_CC technological_JJ advancements_NN2 ._. 
</s>
<s>
Due_II21 to_II22 European_JJ Union_NN1 directives_NN2 ,_, standards_NN2 are_VBR increasingly_RR stringent_JJ ._. 
</s>
<s>
Vehicles_NN2 which_DDQ do_VD0 not_XX meet_VVI the_AT standards_NN2 can_VM not_XX be_VBI sold_VVN in_II the_AT EU_NP1 member_NN1 states_NN2 (_( Wikipedia._NP1 2011_MC )_) ._. 
</s>
<s>
As_II a_AT1 buyer_NN1 of_IO transporting_VVG services_NN2 Itella_NP1 favors_VVZ companies_NN2 which_DDQ are_VBR members_NN2 of_IO ,_, and_CC follow_VV0 the_AT guidelines_NN2 of_IO ,_, the_AT energy_NN1 efficiency_NN1 agreement_NN1 for_IF the_AT transportation_NN1 industry_NN1 (_( Itella_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
When_CS new_JJ transportation_NN1 vehicles_NN2 are_VBR bought_VVN ,_, the_AT maximum_NN1 allowed_VVN CO2_FO emission_NN1 is_VBZ 180_MC g_ZZ1 CO2/km_FU ._. 
</s>
<s>
If_CS the_AT emissions_NN2 do_VD0 not_XX exceed_VVI 120_MC g_ZZ1 CO2/km_FU ,_, Itella_NP1 is_VBZ granted_VVN a_AT1 compensation_NN1 of_IO 50_MC euro_NN1 per_II month_NNT1 on_II the_AT vehicles_NN2 taxation-value_NN1 ._. 
</s>
<s>
Currently_RR more_DAR than_CSN one_MC1 third_MD of_IO the_AT vehicles_NN2 bought_VVN in_II 2009_MC and_CC 2010_MC meet_VV0 these_DD2 requirements_NN2 (_( Itella_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
Itella_NN1 also_RR wants_VVZ to_TO reduce_VVI the_AT CO2_FO emissions_NN2 in_II other_JJ parts_NN2 of_IO their_APPGE business_NN1 operations_NN2 ._. 
</s>
<s>
The_AT energy_NN1 consumption_NN1 in_II their_APPGE premises_NN2 is_VBZ quite_RG high_JJ ,_, especially_RR in_II the_AT sorting_NN1 centers_NN2 ._. 
</s>
<s>
Since_CS the_AT beginning_NN1 of_IO 2011_MC ,_, 100_MC per_NNU21 cent_NNU22 of_IO their_APPGE electricity_NN1 consumption_NN1 in_II Finland_NP1 is_VBZ electricity_NN1 which_DDQ is_VBZ produced_VVN from_II renewable_JJ energy_NN1 sources_NN2 ,_, e.g._REX wind_NN1 and_CC water_NN1 ._. 
</s>
<s>
Doing_VDG this_DD1 Itella_NN1 has_VHZ managed_VVN to_TO reduce_VVI their_APPGE CO2_FO emissions_NN2 with_IW 15_MC percent_NNU (_( Itella_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
Improvements_NN2 on_II their_APPGE reverse_JJ logistics_NN1 at_II their_APPGE premises_NN2 have_VH0 also_RR been_VBN made_VVN ._. 
</s>
<s>
A_AT1 new_JJ plan_NN1 for_IF how_RRQ waste_NN1 will_VM be_VBI recycled_VVN has_VHZ been_VBN stated_VVN ,_, where_CS there_EX also_RR are_VBR calculations_NN2 of_IO the_AT amount_NN1 of_IO waste_NN1 ._. 
</s>
<s>
The_AT purpose_NN1 of_IO this_DD1 plan_NN1 has_VHZ been_VBN to_TO prevent_VVI the_AT occurrence_NN1 of_IO waste_NN1 as_RG well_RR as_CSA to_TO reuse_VVI ,_, and_CC recycle_VVI materials_NN2 ._. 
</s>
<s>
Also_RR the_AT option_NN1 of_IO providing_VVG customers_NN2 with_IW electronic_JJ mail_NN1 and_CC invoices_NN2 reduces_VVZ the_AT usage_NN1 of_IO paper_NN1 (_( Itella_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
Educating_VVG the_AT employees_NN2 about_II recycling_NN1 and_CC sorting_NN1 has_VHZ together_RL with_IW this_DD1 new_JJ plan_NN1 ,_, now_RT led_VVN to_II an_AT1 almost_RR non_FU existing_JJ production_NN1 of_IO mixed_JJ waste_NN1 ._. 
</s>
<s>
Also_RR the_AT amount_NN1 of_IO waste_NN1 being_VBG deposited_VVN at_II some_DD places_NN2 has_VHZ decreased_VVN up_RG21 to_RG22 70_MC percent_NNU ._. 
</s>
<s>
This_DD1 has_VHZ overall_RR led_VVN to_II cleaner_NN1 and_CC safer_RRR working_VVG environment_NN1 ._. 
</s>
<s>
Itellas_NP1 logistics_NN1 center_NN1 in_II Vantaa_NP1 ,_, which_DDQ is_VBZ the_AT largest_JJT sorting_NN1 center_NN1 ,_, has_VHZ even_RR been_VBN approved_VVN for_IF the_AT ISO_NP1 14001_MC environmental_JJ certificate_NN1 (_( Itella_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
The_AT stores_NN2 have_VH0 been_VBN renewed_VVN so_CS21 that_CS22 the_AT premises_NN2 correspond_VV0 to_II todays_NN2 service_VV0 demands_NN2 ._. 
</s>
<s>
They_PPHS2 have_VH0 tried_VVN to_TO recycle_VVI large_JJ amounts_NN2 of_IO the_AT furniture_NN1 after_II the_AT renovations_NN2 and_CC this_DD1 is_VBZ now_RT a_AT1 part_NN1 of_IO their_APPGE service_NN1 image_NN1 ._. 
</s>
<s>
Lighting_NN1 will_VM be_VBI changed_VVN entirely_RR to_II LED-lamps_NN2 since_CS they_PPHS2 do_VD0 not_XX use_VVI as_RG much_DA1 electricity_NN1 or_CC service_NN1 upkeep_NN1 ._. 
</s>
<s>
Yet_RR they_PPHS2 admit_VV0 that_CST they_PPHS2 are_VBR still_RR looking_VVG for_IF better_JJR lighting_NN1 solutions_NN2 (_( Itella_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
As_II a_AT1 new_JJ logistical_JJ solution_NN1 to_II getting_VVG the_AT employees_NN2 to_TO work_VVI Itella_NP1 had_VHD a_AT1 month_NNT1 long_JJ campaign_NN1 for_IF bicycling_VVG during_II the_AT nationwide_JJ cycling_NN1 week_NNT1 ._. 
</s>
<s>
This_DD1 campaign_NN1 encouraged_VVD the_AT employees_NN2 to_TO come_VVI to_TO work_VVI by_II bicycle_NN1 and_CC over_RG 400_MC people_NN participated_VVD ._. 
</s>
<s>
Not_XX only_RR was_VBDZ it_PPH1 good_JJ for_IF the_AT environment_NN1 ,_, but_CCB also_RR for_IF their_APPGE health_NN1 ._. 
</s>
<s>
Together_RL they_PPHS2 bicycled_VVD over_II 50_MC 000_MC km_NNU ,_, which_DDQ was_VBDZ a_AT1 CO2_FO decrease_NN1 of_IO 9000_MC kg_NNU (_( Itella_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
5_MC ._. 
</s>
<s>
Discussion_NN1 and_CC conclusion_NN1 Itella_NP1 has_VHZ a_AT1 lot_NN1 of_IO different_JJ solutions_NN2 on_II minimizing_VVG their_APPGE negative_JJ environmental_JJ impact_NN1 ,_, mostly_RR technological_JJ improvements_NN2 ._. 
</s>
<s>
Just_RR like_II the_AT solution_NN1 presented_VVN in_II the_AT theory_NN1 ,_, Itella_NP1 has_VHZ reduced_VVN their_APPGE emissions_NN2 from_II transport_NN1 by_II economical_JJ driving_JJ ,_, optimizing_VVG delivery_NN1 routes_NN2 and_CC consolidation_NN1 ._. 
</s>
<s>
They_PPHS2 have_VH0 also_RR started_VVN using_VVG optional_JJ fuels_NN2 like_II natural_JJ gas_NN1 and_CC electricity_NN1 ._. 
</s>
<s>
Overall_RR they_PPHS2 have_VH0 in_II some_DD form_NN1 incorporated_VVN all_DB of_IO the_AT different_JJ logistical_JJ solutions_NN2 mentioned_VVN in_II the_AT theory_NN1 and_CC more_RRR ._. 
</s>
<s>
When_CS it_PPH1 comes_VVZ to_II companies_NN2 environment_NN1 polices_VVZ or_CC corporate_JJ social_JJ responsibility_NN1 (_( CSR_NP1 )_) reports_VVZ ,_, the_AT question_NN1 of_IO authenticity_NN1 and_CC suspicion_NN1 often_RR arise_VV0 ._. 
</s>
<s>
According_II21 to_II22 a_AT1 study_NN1 made_VVN by_II Susanne_NP1 Arvidsson_NP1 on_II the_AT Views_NN2 of_IO Management_NN1 Teams_NN2 in_II Large_JJ Companies_NN2 ,_, when_CS making_VVG reports_NN2 on_II CSR_NP1 or_CC environmental_JJ impact_NN1 companies_NN2 only_RR strive_VV0 for_IF not_XX being_VBG last_NN1 on_II the_AT list_NN1 ._. 
</s>
<s>
This_DD1 means_VVZ that_CST they_PPHS2 just_RR do_VD0 not_XX strive_VVI to_TO do_VDI very_RG much_DA1 more_DAR than_CSN what_DDQ is_VBZ needed_VVN ;_; this_DD1 can_VM make_VVI their_APPGE procedures_NN2 questionable_JJ ._. 
</s>
<s>
The_AT information_NN1 is_VBZ also_RR not_XX always_RR so_RG transparent_JJ ,_, so_CS it_PPH1 is_VBZ not_XX so_RG easy_JJ to_TO check_VVI whether_CSW it_PPH1 is_VBZ true_JJ (_( Arvidsson_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
I_PPIS1 do_VD0 not_XX know_VVI what_DDQ the_AT case_NN1 of_IO Itellas_NP2 measures_NN2 are_VBR ,_, but_CCB I_PPIS1 believe_VV0 that_CST what_DDQ they_PPHS2 claim_VV0 to_TO have_VHI done_VDN is_VBZ true_JJ ,_, since_CS the_AT negative_JJ impact_NN1 of_IO fraud_NN1 and_CC other_JJ indecencies_NN2 on_II a_AT1 company_NN1 's_GE reputation_NN1 are_VBR quite_RG severe_JJ ._. 
</s>
<s>
What_DDQ is_VBZ more_RGR difficult_JJ to_TO say_VVI is_VBZ wether_VV0 effects_NN2 of_IO their_APPGE measures_NN2 have_VH0 the_AT positive_JJ impact_NN1 they_PPHS2 claim_VV0 ._. 
</s>
<s>
Accordign_VV0 to_II Wu_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
it_PPH1 is_VBZ not_XX easy_JJ to_TO include_VVI environmental_JJ management_NN1 principles_NN2 in_II the_AT daily_JJ decision_NN1 making_VVG (_( Wu_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
1995_MC )_) ._. 
</s>
<s>
Itella_NN1 seems_VVZ to_TO have_VHI overcome_VVN this_DD1 obstacle_NN1 and_CC done_VDN a_RR31 great_RR32 deal_RR33 to_TO improve_VVI their_APPGE environmental_JJ impact_NN1 ,_, solutions_NN2 like_II their_APPGE climate_NN1 projects_NN2 abroad_RL and_CC encouraging_VVG their_APPGE employees_NN2 to_TO come_VVI to_TO work_VVI by_II bicycle_NN1 ._. 
</s>
<s>
These_DD2 solutions_NN2 are_VBR not_XX really_RR connected_VVN to_II their_APPGE logistical_JJ operations_NN2 but_CCB as_RG earlier_RRR stated_VVD a_AT1 broader_JJR perspective_NN1 is_VBZ needed_VVN as_II31 well_II32 as_II33 innovation_NN1 like_II this_DD1 ._. 
</s>
<s>
The_AT question_NN1 is_VBZ ;_; are_VBR they_PPHS2 sustainable_JJ ,_, which_DDQ is_VBZ difficult_JJ to_TO say_VVI before_II trying_VVG ._. 
</s>
<s>
Overall_JJ theories_NN2 are_VBR more_RGR general_JJ ,_, which_DDQ leads_VVZ to_II that_CST a_AT1 lot_NN1 of_IO companies_NN2 have_VH0 to_TO make_VVI their_APPGE own_DA versions_NN2 to_TO fit_VVI their_APPGE company_NN1 ._. 
</s>
<s>
It_PPH1 also_RR takes_VVZ longer_JJR time_NNT1 to_TO implement_VVI new_JJ theories_NN2 and_CC for_IF old_JJ ones_NN2 to_TO change_VVI ._. 
</s>
<s>
Itella_NN1 being_VBG a_AT1 logistics_NN1 company_NN1 could_VM be_VBI a_AT1 reason_NN1 for_IF the_AT amount_NN1 of_IO innovation_NN1 and_CC general_JJ knowledge_NN1 on_II logistical_JJ solutions_NN2 ._. 
</s>
<s>
There_EX should_VM be_VBI more_DAR case_NN1 studies_NN2 made_VVN on_II what_DDQ companies_NN2 are_VBR doing_VDG in_II practice_NN1 and_CC the_AT effects_NN2 of_IO these_DD2 actions_NN2 ._. 
</s>
