<s>
The_AT introduction_NN1 of_IO self-management_NN1 to_II an_AT1 organization_NN1 through_II management_NN1 1_MC1 Introduction_NN1 The_AT topic_NN1 self-management_NN1 focuses_VVZ often_RR on_II how_RRQ to_TO work_VVI more_RGR efficient_JJ and_CC perform_VVI better_RRR through_II that_DD1 (_( Rytikangas_NP2 ,_, 2008_MC )_) ._. 
</s>
<s>
Todays_NP1 businesses_NN2 emphasize_VV0 much_RR on_II high-performance_NN1 ,_, results_NN2 ,_, hard-working_JJ environment_NN1 ,_, and_CC a_AT1 business_NN1 minded_VVD attitude_NN1 ._. 
</s>
<s>
Therefore_RR there_EX have_VH0 been_VBN many_DA2 articles_NN2 and_CC studies_NN2 describing_VVG how_RRQ this_DD1 influences_VVZ workers_NN2 and_CC how_RRQ they_PPHS2 have_VH0 enough_DD strength_NN1 to_TO cope_VVI with_IW the_AT upbeat_JJ business_NN1 life_NN1 ._. 
</s>
<s>
The_AT subject_NN1 is_VBZ concerned_JJ with_IW questions_NN2 on_II how_RRQ to_TO organize_VVI our_APPGE tasks_NN2 ,_, to_TO do_VDI better_RRR plans_VVZ ,_, to_TO focus_VVI on_II our_APPGE jobs_NN2 ,_, to_TO delegate_VVI tasks_NN2 ,_, to_TO be_VBI more_RGR efficient_JJ ,_, how_RRQ to_TO be_VBI better_RRR at_II decision-making_NN1 and_CC how_RRQ to_TO take_VVI care_NN1 of_IO our_APPGE own_DA development_NN1 so_CS21 that_CS22 we_PPIS2 can_VM manage_VVI our_APPGE own_DA job_NN1 tasks_NN2 ._. 
</s>
<s>
There_RL arefewer_VV0 studies_NN2 on_II how_RRQ the_AT leaders_NN2 and_CC managers_NN2 in_II an_AT1 organization_NN1 could_VM improve_VVI the_AT know-how_NN1 and_CC skills_NN2 of_IO the_AT entire_JJ organization_NN1 by_II first_MD learning_NN1 and_CC adapting_VVG the_AT skills_NN2 through_II self-management_NN1 for_IF themselves_PPX2 ._. 
</s>
<s>
In_II this_DD1 paper_NN1 ,_, I_PPIS1 will_VM therefore_RR focus_VVI on_II this_DD1 part_NN1 of_IO self-management_NN1 ;_; how_RRQ it_PPH1 can_VM be_VBI tapped_VVN by_II organizations_NN2 through_II their_APPGE managers_NN2 ._. 
</s>
<s>
Gary_NP1 Hamel_NP1 (_( 2011_MC )_) mentions_VVZ in_II one_MC1 of_IO his_APPGE articles_NN2 that_CST management_NN1 is_VBZ the_AT least_RGT efficient_JJ activity_NN1 in_II your_APPGE organization_NN1 ._. 
</s>
<s>
He_PPHS1 continues_VVZ that_CST this_DD1 is_VBZ because_CS it_PPH1 is_VBZ costly_JJ ,_, there_RL tend_VV0 to_TO be_VBI too_RG much_DA1 decision_NN1 layers_NN2 and_CC it_PPH1 takes_VVZ time_NNT1 to_TO do_VDI different_JJ responses_NN2 to_II decisions_NN2 ._. 
</s>
<s>
However_RR ,_, Glenn_NP1 Gutek_NP1 (_( 2011_MC )_) and_CC Stephen_NP1 Long_JJ (_( 2011_MC )_) have_VH0 both_DB2 written_VVN articles_NN2 on_II how_RRQ a_AT1 manager_NN1 can_VM be_VBI more_RGR efficient_JJ attheir_NN1 job_NN1 through_II self-management_NN1 and_CC how_RRQ they_PPHS2 can_VM transfer_VVI this_DD1 forward_NN1 through_RP to_II the_AT organization_NN1 ._. 
</s>
<s>
Long_RR also_RR continues_VVZ that_CST managers_NN2 need_VV0 to_TO learn_VVI first_MD to_TO manage_VVI and_CC lead_VVI themselves_PPX2 ,_, before_CS he_PPHS1 can_VM start_VVI to_TO try_VVI to_TO manage_VVI and_CC lead_VVI others.In_NNU this_DD1 paper_NN1 ,_, I_PPIS1 will_VM focus_VVI on_II this_DD1 later_JJR part_NN1 ;_; how_RRQ the_AT organizations_NN2 can_VM be_VBI more_RGR efficient_JJ with_IW the_AT help_NN1 of_IO self-management_NN1 through_II their_APPGE managers_NN2 ._. 
</s>
<s>
This_DD1 paper_NN1 hope_VV0 to_TO show_VVI that_DD1 self-management_NN1 can_VM be_VBI adapted_VVN to_II the_AT entire_JJ organization_NN1 with_IW the_AT help_NN1 of_IO the_AT manager_NN1 ._. 
</s>
<s>
If_CS the_AT manager_NN1 first_MD adapts_VVZ the_AT self-management_NN1 teachings_NN2 himself_PPX1 ,_, he_PPHS1 can_VM show_VVI a_AT1 good_JJ example_NN1 to_II the_AT other_JJ workers_NN2 and_CC help_VV0 them_PPHO2 to_TO adapt_VVI the_AT teachings_NN2 through_RP to_II the_AT entire_JJ organization_NN1 ._. 
</s>
<s>
I_PPIS1 have_VH0 organized_VVN the_AT rest_NN1 of_IO this_DD1 paperinto_NN1 four_MC sections_NN2 ._. 
</s>
<s>
The_AT following_JJ section_NN1 will_VM introduce_VVI self-management_NN1 and_CC its_APPGE field_NN1 of_IO study_NN1 ._. 
</s>
<s>
It_PPH1 helps_VVZ to_TO understand_VVI what_DDQ questions_NN2 and_CC topics_NN2 the_AT subject_NN1 concerns_NN2 ._. 
</s>
<s>
After_CS this_DD1 ,_, we_PPIS2 can_VM dig_VVI further_RRR into_II our_APPGE paper_NN1 topic_NN1 on_II how_RRQ managers_NN2 can_VM help_VVI the_AT entire_JJ organization_NN1 adapt_VV0 and_CC learn_VVI these_DD2 teachings_NN2 by_II learning_VVG them_PPHO2 first_MD for_IF themselves_PPX2 ._. 
</s>
<s>
Hamel_NP1 (_( 2011_MC )_) ,_, Rytikangas_NP2 (_( 2008_MC )_) ,_, Gutek_NP1 (_( 2011_MC )_) ,_, Long_RR (_( 2011_MC )_) and_CC a_AT1 few_DA2 more_DAR will_VM be_VBI used_VVN as_CSA sources_NN2 to_TO present_VVI the_AT background_NN1 and_CC ideas_NN2 for_IF this_DD1 paper_NN1 ._. 
</s>
<s>
After_CS this_DD1 there_EX will_VM be_VBI some_DD discussion_NN1 about_II the_AT findings_NN2 and_CC what_DDQ have_VH0 been_VBN learned_VVN ._. 
</s>
<s>
Finally_RR ,_, there_EX will_VM be_VBI a_AT1 literature_NN1 review_NN1 before_II the_AT conclusion_NN1 ._. 
</s>
<s>
2_MC Literature_NN1 review_NN1 Self-management_NN1 as_II a_AT1 topic_NN1 has_VHZ interested_VVN me_PPIO1 for_IF a_AT1 long_JJ time_NNT1 ._. 
</s>
<s>
The_AT subject_NN1 includes_VVZ many_DA2 interesting_JJ points_NN2 and_CC also_RR contains_VVZ many_DA2 practices_NN2 that_CST could_VM be_VBI used_VVN in_II todays_NN2 fast_RR paced_VVN business_NN1 life_NN1 that_CST stresses_VVZ hard-work_JJ environment_NN1 ,_, high-performance_NN1 ,_, results_NN2 ,_, and_CC a_AT1 business_NN1 minded_VVD attitude_NN1 ._. 
</s>
<s>
Self-management_NN1 itself_PPX1 contains_VVZ topics_NN2 like_II how_RRQ to_TO cope_VVI with_IW stress_NN1 ,_, how_RRQ to_TO manage_VVI time_NNT1 more_RRR efficient_JJ ,_, and_CC how_RRQ to_TO be_VBI more_RGR effective_JJ during_II the_AT working_NN1 hours_NNT2 ._. 
</s>
<s>
Leadership_NN1 is_VBZ also_RR a_AT1 subject_NN1 that_CST has_VHZ been_VBN covered_VVN broadly_RR ._. 
</s>
<s>
By_II reading_VVG the_AT material_NN1 found_VVD out_RP that_CST there_EX is_VBZ written_VVN commonly_RR about_II self-management_NN1 and_CC about_II leadership_NN1 ;_; however_RR ,_, these_DD2 subjects_NN2 havent_NN1 been_VBN combined_VVN in_II many_DA2 ways_NN2 ._. 
</s>
<s>
This_DD1 gave_VVD me_PPIO1 the_AT idea_NN1 of_IO what_DDQ if_CS ;_; self-management_NN1 could_VM be_VBI taken_VVN better_RRR into_II consideration_NN1 in_II organizations_NN2 through_II leadership.Perhaps_NNU it_PPH1 couldalso_NN1 be_VBI better_RRR adopted_VVN into_II practice_NN1 this_DD1 way_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ why_RRQ I_PPIS1 wanted_VVD to_TO review_VVI literature_NN1 on_II self-management_NN1 and_CC on_II how_RRQ managers_NN2 can_VM help_VVI the_AT organization_NN1 learn_VV0 by_II their_APPGE actions_NN2 ._. 
</s>
<s>
3_MC Methods_NN2 Todays_NP1 businesses_NN2 emphasize_VV0 much_RR on_II high-performance_NN1 ,_, result_VV0 ,_, hard-working_JJ environment_NN1 ,_, and_CC a_AT1 business_NN1 minded_VVD attitude_NN1 ._. 
</s>
<s>
Organizations_NN2 are_VBR focused_VVN widely_RR on_II business_NN1 and_CC want_VV0 to_TO see_VVI results_NN2 ._. 
</s>
<s>
This_DD1 is_VBZ also_RR the_AT reason_NN1 why_RRQ we_PPIS2 are_VBR looking_VVG for_IF explanations_NN2 if_CS business_NN1 is_VBZ not_XX flourishing_VVG or_CC going_VVG the_AT way_NN1 planned_VVD ._. 
</s>
<s>
In_II the_AT 1910s_MC2 there_EX were_VBDR a_AT1 form_NN1 of_IO scientific_JJ management_NN1 called_VVN taylorism_NN1 ._. 
</s>
<s>
Workers_NN2 were_VBDR only_RR seen_VVN as_CSA performers_NN2 and_CC all_DB planning_NN1 and_CC policy_NN1 making_NN1 was_VBDZ done_VDN by_II the_AT top_JJ management_NN1 ._. 
</s>
<s>
Henry_NP1 Ford_NP1 took_VVD this_DD1 even_RR further_RRR and_CC introduced_VVD an_AT1 assembly_NN1 line_NN1 working_VVG method_NN1 ._. 
</s>
<s>
Here_RL the_AT work_NN1 could_VM be_VBI split_VVN up_RP into_II small_JJ pieces_NN2 to_TO gain_VVI the_AT maximum_JJ power_NN1 ._. 
</s>
<s>
This_DD1 way_NN1 everyone_PN1 just_RR needed_VVN to_TO focus_VVI on_II their_APPGE own_DA tasks_NN2 and_CC make_VVI it_PPH1 more_RGR effective_JJ ._. 
</s>
<s>
The_AT workers_NN2 were_VBDR seen_VVN in_II a_AT1 very_RG mechanical_JJ and_CC negative_JJ way_NN1 ._. 
</s>
<s>
This_DD1 form_NN1 of_IO working_NN1 did_VDD not_XX enhance_VVI the_AT workers_NN2 motivation_NN1 and_CC commitment_NN1 for_IF work_NN1 ._. 
</s>
<s>
(_( Kehusmaa_NN1 2010_MC :_: 137_MC ._. )_) 
</s>
<s>
Later_RRR during_II the_AT 20th_MD century_NNT1 relationship_NN1 management_NN1 gained_VVD ground_NN1 and_CC managers_NN2 started_VVD building_NN1 relationships_NN2 with_IW their_APPGE employees_NN2 ._. 
</s>
<s>
Managers_NN2 also_RR started_VVD to_TO spend_VVI time_NNT1 with_IW the_AT employees_NN2 and_CC give_VVI the_AT employees_NN2 a_AT1 picture_NN1 that_CST they_PPHS2 had_VHD the_AT possibility_NN1 to_TO take_VVI part_NN1 in_II the_AT decision_NN1 making_VVG ._. 
</s>
<s>
This_DD1 way_NN1 of_IO management_NN1 committed_JJ workers_NN2 better_RRR to_II their_APPGE employers_NN2 ._. 
</s>
<s>
(_( Kehusmaa_NN1 2010_MC :_: 140-143_MCMC ._. )_) 
</s>
<s>
The_AT role_NN1 of_IO management_NN1 and_CC their_APPGE efficiency_NN1 is_VBZ seen_VVN in_II various_JJ ways_NN2 still_RR today_RT ._. 
</s>
<s>
Poor_JJ management_NN1 skills_NN2 are_VBR the_AT reason_NN1 for_IF keeping_VVG back_RP growth_NN1 (_( Poor_JJ management_NN1 skills_NN2 1996_MC )_) ._. 
</s>
<s>
Management_NN1 is_VBZ ineffective_JJ ,_, costly_JJ and_CC makes_VVZ the_AT organization_NN1 slower_RRR because_II21 of_II22 approval_NN1 layers_NN2 (_( Hamel_NP1 2011_MC )_) ._. 
</s>
<s>
Today_RT still_RR many_DA2 people_NN ,_, both_RR managers_NN2 and_CC employees_NN2 ,_, think_VV0 that_CST all_DB the_AT strategic_JJ decisions_NN2 are_VBR only_RR made_VVN by_II the_AT management_NN1 team_NN1 and_CC that_CST the_AT rest_NN1 of_IO the_AT employees_NN2 are_VBR left_VVN outside_II strategic_JJ planning_NN1 (_( Kehusmaa_NP1 2010_MC :_: 138_MC )_) ._. 
</s>
<s>
In_II todays_NN2 organizations_NN2 the_AT character_NN1 of_IO our_APPGE jobs_NN2 has_VHZ changed_VVN in_II a_AT1 fast_JJ pace_NN1 and_CC in_II considerable_JJ ways_NN2 compared_VVN with_IW the_AT amount_NN1 of_IO training_NN1 we_PPIS2 are_VBR getting_VVG for_IF our_APPGE jobs_NN2 and_CC also_RR the_AT ability_NN1 to_TO handle_VVI all_DB the_AT work_NN1 tasks_NN2 (_( Allen_NP1 2003_MC )_) ._. 
</s>
<s>
These_DD2 factors_NN2 result_VV0 in_II that_DD1 workers_NN2 feel_VV0 very_RG busy_JJ ,_, get_VV0 stressed_JJ and_CC the_AT feeling_NN1 that_CST they_PPHS2 can_VM not_XX handle_VVI their_APPGE work_NN1 ._. 
</s>
<s>
The_AT feeling_NN1 of_IO being_VBG busy_JJ and_CC stressed_JJ result_NN1 from_II the_AT illusion_NN1 that_CST we_PPIS2 think_VV0 that_CST we_PPIS2 need_VV0 to_TO be_VBI available_JJ at_II any_DD moment_NN1 ,_, the_AT increased_JJ use_NN1 of_IO e-mails_NN2 ,_, the_AT increased_JJ competition_NN1 ,_, ambition_NN1 and_CC seeking_VVG of_IO success_NN1 ,_, seeking_VVG of_IO perfection_NN1 ,_, and_CC the_AT fear_NN1 of_IO losing_VVG a_AT1 job_NN1 or_CC income_NN1 ._. 
</s>
<s>
All_DB these_DD2 result_VV0 in_II that_DD1 the_AT outcome_NN1 of_IO work_NN1 suffers_VVZ ,_, the_AT quality_NN1 declines_VVZ ,_, it_PPH1 leads_VVZ into_II splurge_NN1 ,_, delays_NN2 ,_, stress_NN1 ,_, exhaustion_NN1 ,_, sick_JJ days_NNT2 and_CC absences_NN2 occur_VV0 ,_, collaboration_NN1 and_CC communication_NN1 suffers_VVZ ,_, creativity_NN1 suffers_VVZ and_CC innovation_NN1 will_VM be_VBI on_II hold_NN1 ,_, learning_NN1 declines_VVZ ,_, and_CC delegation_NN1 slips_VVZ out_II21 of_II22 mind_NN1 ._. 
</s>
<s>
(_( Rytikangas_NP1 2008_MC ._. )_) 
</s>
<s>
By_II learning_VVG self-management_NN1 it_PPH1 could_VM help_VVI in_II all_DB these_DD2 situations_NN2 ._. 
</s>
<s>
But_CCB the_AT biggest_JJT issue_NN1 here_RL is_VBZ to_TO get_VVI the_AT self-management_NN1 practices_NN2 into_II the_AT organizations_NN2 ._. 
</s>
<s>
In_II my_APPGE opinion_NN1 the_AT managers_NN2 could_VM first_MD take_VVI the_AT practices_NN2 in_II use_NN1 for_IF themselves_PPX2 ,_, and_CC in_II this_DD1 way_NN1 show_VV0 the_AT way_NN1 for_IF the_AT rest_NN1 of_IO the_AT employees_NN2 so_CS21 that_CS22 they_PPHS2 would_VM not_XX fear_VVI for_IF the_AT change_NN1 ._. 
</s>
<s>
Self-management_NN1 is_VBZ really_RR about_II getting_VVG all_DB the_AT efficiency_NN1 out_II21 of_II22 the_AT working_JJ time_NNT1 ,_, mastering_VVG the_AT use_NN1 of_IO time_NNT1 ,_, and_CC pre-empting_JJ stress_NN1 ._. 
</s>
<s>
To_TO control_VVI the_AT time_NNT1 is_VBZ all_DB about_II focusing_VVG and_CC prioritizing_VVG tasks_NN2 ._. 
</s>
<s>
This_DD1 includes_VVZ making_VVG conscious_JJ choices_NN2 ,_, focusing_VVG on_II the_AT essential_JJ ,_, learning_VVG to_TO tolerate_VVI incompleteness_NN1 ,_, change_NN1 and_CC disorder_NN1 ,_, to_TO develop_VVI oneself_PNX1 ,_, taking_VVG care_NN1 of_IO oneself_PNX1 and_CC his_APPGE resources_NN2 ,_, and_CC being_VBG merciful_JJ to_TO oneself_PNX1 ._. 
</s>
<s>
Self-management_NN1 can_VM be_VBI learned_VVN by_II exploring_VVG openly_RR and_CC honestly_RR our_APPGE activity_NN1 ,_, identifying_VVG our_APPGE work_NN1 habits_NN2 ,_, becoming_VVG conscious_JJ of_IO our_APPGE strengths_NN2 and_CC weaknesses_NN2 ,_, and_CC deliberately_RR changing_VVG the_AT methods.This_NNU means_VVZ that_CST we_PPIS2 should_VM be_VBI able_JK to_TO identify_VVI if_CSW tasks_NN2 are_VBR relevant_JJ or_CC not_XX ,_, remembering_VVG that_CST multitasking_VVG often_RR means_VVZ more_DAR mistakes_NN2 ,_, and_CC more_DAR costs_NN2 while_CS we_PPIS2 do_VD0 not_XX have_VHI time_NNT1 for_IF asking_VVG many_DA2 bids_NN2 ,_, we_PPIS2 might_VM get_VVI fines_NN2 for_IF being_VBG late_JJ ,_, and_CC e.g._REX flights_NN2 are_VBR more_RGR expensive_JJ closer_JJR to_II departure_NN1 ._. 
</s>
<s>
In_II self-management_NN1 we_PPIS2 should_VM also_RR be_VBI aware_JJ of_IO our_APPGE professional_JJ ,_, physical_JJ ,_, social_JJ ,_, mental_JJ ,_, spiritual_JJ ,_, and_CC renewal_NN1 condition_NN1 ._. 
</s>
<s>
All_DB these_DD2 affect_VV0 our_APPGE general_JJ condition_NN1 and_CC who_PNQS we_PPIS2 are_VBR as_II a_AT1 person_NN1 ._. 
</s>
<s>
(_( Rytikangas_NP1 2008_MC ._. )_) 
</s>
<s>
Long_RR Stephen_NP1 (_( 2011_MC )_) wrote_VVD that_CST until_CS executives_NN2 can_VM lead_VVI and_CC manage_VVI themselves_PPX2 ,_, they_PPHS2 cant_JJ manage_VVI and_CC lead_VVI others_NN2 Long_RR (_( 2011_MC )_) also_RR continues_VVZ that_CST if_CS managers_NN2 do_VD0 not_XX have_VHI skills_NN2 in_II self-management_NN1 they_PPHS2 will_VM not_XX have_VHI skills_NN2 in_II risk_NN1 analysis_NN1 either_RR ._. 
</s>
<s>
Managers_NN2 should_VM be_VBI able_JK to_TO create_VVI a_AT1 vision_NN1 and_CC set_VVI the_AT direction_NN1 to_TO achieve_VVI it_PPH1 ._. 
</s>
<s>
A_AT1 good_JJ manager_NN1 is_VBZ also_RR able_JK to_TO simplify_VVI things_NN2 ,_, so_CS21 that_CS22 the_AT employees_NN2 understand_VV0 the_AT case_NN1 in_II question_NN1 better_RRR ,_, without_IW losing_VVG the_AT thread_NN1 ._. 
</s>
<s>
(_( Long_RR 2011_MC ;_; Kehusmaa_NP1 2010_MC ._. )_) 
</s>
<s>
Some_DD managers_NN2 are_VBR just_RR thought_VVN to_TO be_VBI good_JJ at_II self-management_NN1 ._. 
</s>
<s>
Gutek_VV0 Glenn_NP1 (_( 2011_MC )_) wrote_VVD in_II his_APPGE article_NN1 about_II a_AT1 manager_NN1 that_CST had_VHD an_AT1 incredible_JJ ability_NN1 to_TO do_VDI what_DDQ needs_VVZ to_TO be_VBI done_VDN ,_, when_CS it_PPH1 needs_VVZ to_TO be_VBI done_VDN ._. 
</s>
<s>
Changes_NN2 is_VBZ often_RR something_PN1 that_CST is_VBZ feared_VVN in_II organizations_NN2 because_CS it_PPH1 is_VBZ being_VBG seen_VVN as_II a_AT1 threat_NN1 to_II one_MC1 selves_VVZ rank_VV0 ,_, work_VV0 ,_, know-how_NN1 ,_, feeling_NN1 of_IO value_NN1 or_CC ability_NN1 to_TO cope_VVI with_IW it_PPH1 (_( Kehusmaa_NP1 2010_MC :_: 153_MC )_) ._. 
</s>
<s>
In_II a_AT1 learning_NN1 organization_NN1 the_AT manageris_NN1 demanded_VVN for_IF creating_VVG a_AT1 shared_JJ vision_NN1 ,_, coordinating_VVG the_AT teams_NN2 activity_NN1 ,_, spreading_VVG the_AT systematic_JJ thinking_NN1 ,_, promoting_VVG creativeness_NN1 ,_, risk-taking_JJ and_CC innovation_NN1 ,_, and_CC inspiring_VVG to_TO learn_VVI and_CC act_NN1 ._. 
</s>
<s>
This_DD1 way_NN1 highlights_VVZ a_AT1 shared_JJ making_NN1 ,_, participating_VVG ,_, gives_VVZ everyone_PN1 ability_NN1 to_II impact_NN1 ,_, and_CC creates_VVZ an_AT1 organization_NN1 that_CST shares_NN2 and_CC makes_VVZ the_AT most_DAT of_IO the_AT knowledge_NN1 they_PPHS2 have_VH0 ._. 
</s>
<s>
This_DD1 way_NN1 the_AT organization_NN1 moves_VVZ as_CSA one_PN1 towards_II the_AT objectives_NN2 ._. 
</s>
<s>
In_II a_AT1 learning_NN1 organization_NN1 the_AT individual_NN1 have_VH0 the_AT opportunity_NN1 to_TO improve_VVI ,_, there_EX is_VBZ a_AT1 shared_JJ and_CC common_JJ vision_NN1 ,_, and_CC team_NN1 learning_NN1 is_VBZ a_AT1 part_NN1 of_IO the_AT culture_NN1 ._. 
</s>
<s>
The_AT employee_NN1 satisfaction_NN1 ,_, work_VV0 capability_NN1 ,_, ability_NN1 to_TO learn_VVI ,_, customer_NN1 satisfaction_NN1 ,_, and_CC the_AT impacts_NN2 on_II society_NN1 are_VBR all_DB outcomes_NN2 form_VV0 a_AT1 learning_NN1 organization_NN1 ._. 
</s>
<s>
(_( Kehusmaa_NN1 2010_MC :_: 145-148._MCMC )_) 4_MC Results_NN2 By_II adapting_VVG self-management_NN1 working_VVG methods_NN2 the_AT organization_NN1 can_VM minimize_VVI dead_JJ time_NNT1 and_CC utilizes_VVZ it_PPH1 ._. 
</s>
<s>
Leaving_VVG things_NN2 to_II the_AT last_MD minute_NNT1 can_VM often_RR mean_VVI that_CST we_PPIS2 cause_VV0 stress_NN1 to_II someone_PN1 else_RR ._. 
</s>
<s>
By_II doing_VDG things_NN2 in_II hurry_NN1 ,_, and_CC afterwards_RT correcting_VVG mistakes_NN2 ,_, means_VVZ that_CST we_PPIS2 are_VBR doing_VDG it_PPH1 twice_RR in_II a_AT1 way_NN1 ._. 
</s>
<s>
Perfectionism_NN1 can_VM also_RR be_VBI a_AT1 way_NN1 of_IO wasting_VVG time_NNT1 ._. 
</s>
<s>
Archiving_VVG should_VM be_VBI done_VDN in_II a_AT1 practical_JJ way_NN1 ,_, so_CS21 that_CS22 information_NN1 can_VM quickly_RR be_VBI found_VVN when_CS needed_VVN ._. 
</s>
<s>
This_DD1 saves_VVZ time_NNT1 for_IF not_XX have_VH0 to_TO go_VVI through_II unnecessary_JJ papers_NN2 ._. 
</s>
<s>
(_( Rytikangas_NP1 2008:83_MC ._. )_) 
</s>
<s>
These_DD2 are_VBR all_DB methods_NN2 to_TO help_VVI us_PPIO2 make_VVI the_AT most_RRT out_II21 of_II22 our_APPGE working_JJ time_NNT1 and_CC get_VV0 rid_VVN of_IO the_AT dead_JJ time_NNT1 ._. 
</s>
<s>
There_EX are_VBR a_AT1 few_DA2 methods_NN2 how_RRQ self-management_NN1 can_VM be_VBI adapted_VVN to_TO work_VVI habits_NN2 ._. 
</s>
<s>
The_AT first_MD one_PN1 is_VBZ called_VVN the_AT Pareto_NP1 principal_NN1 ,_, which_DDQ is_VBZ also_RR known_VVN as_II the_AT 80/20_MF rule_NN1 ._. 
</s>
<s>
This_DD1 can_VM be_VBI applied_VVN in_II many_DA2 ways_NN2 ._. 
</s>
<s>
We_PPIS2 should_VM remember_VVI that_CST 20%_NNU of_IO our_APPGE customers_NN2 bring_VV0 in_RP 80%_NNU of_IO our_APPGE income_NN1 ._. 
</s>
<s>
20%_NNU of_IO our_APPGE products_NN2 bring_VV0 in_RP 80%_NNU of_IO our_APPGE contribution_NN1 margin_NN1 ._. 
</s>
<s>
Furthermore_RR we_PPIS2 should_VM remember_VVI that_CST this_DD1 can_VM also_RR be_VBI applied_VVN to_II our_APPGE own_DA work_NN1 tasks_NN2 ;_; 20%_NNU of_IO our_APPGE work_NN1 tasks_NN2 are_VBR important_JJ and_CC 80%_NNU less_DAR important_JJ ._. 
</s>
<s>
Another_DD1 method_NN1 is_VBZ to_TO divide_VVI your_APPGE work_NN1 tasks_NN2 according_II21 to_II22 the_AT ABC-work_JJ tasks_NN2 ._. 
</s>
<s>
Firstly_RR ,_, there_EX are_VBR the_AT most_DAT importantA-tasks_NN2 ,_, which_DDQ affect_VV0 the_AT result_NN1 or_CC the_AT availability_NN1 of_IO the_AT goods_NN2 ._. 
</s>
<s>
Secondly_RR ,_, there_EX are_VBR B-tasks_NN2 ._. 
</s>
<s>
These_DD2 are_VBR not_XX as_RG important_JJ as_CSA A-tasks_NN2 ._. 
</s>
<s>
You_PPY should_VM use_VVI moderately_RR time_NNT1 and_CC energy_NN1 for_IF these_DD2 tasks_NN2 ._. 
</s>
<s>
Thirdly_RR ,_, there_EX are_VBR the_AT C-tasks_NN2 ._. 
</s>
<s>
These_DD2 are_VBR tasks_NN2 that_CST are_VBR insignificant_JJ and_CC do_VD0 not_XX perhaps_RR need_VVI to_TO be_VBI done_VDN at_RR21 all_RR22 or_CC perhaps_RR they_PPHS2 can_VM be_VBI delegated_VVN to_II someone_PN1 else_RR ._. 
</s>
<s>
(_( Rytikangas_NP2 2008:53-55_MCMC ._. )_) 
</s>
<s>
The_AT most_RGT important_JJ method_NN1 in_II self-management_NN1 is_VBZ ,_, however_RR ,_, to_TO write_VVI things_NN2 or_CC tasks_NN2 down_RP ,_, that_CST need_VVI to_TO be_VBI remembered_VVN ._. 
</s>
<s>
They_PPHS2 might_VM have_VHI to_TO be_VBI done_VDN now_RT ,_, later_RRR or_CC someday_RT ._. 
</s>
<s>
They_PPHS2 also_RR might_VM be_VBI big_JJ or_CC small_JJ or_CC anything_PN1 in_RL21 between_RL22 ,_, but_CCB when_CS these_DD2 are_VBR somewhere_RL in_II a_AT1 reliable_JJ memory_NN1 our_APPGE own_DA memory_NN1 capacity_NN1 and_CC energy_NN1 can_VM take_VVI a_AT1 break_NN1 ._. 
</s>
<s>
(_( Allen_NP1 2003_MC )_) ._. 
</s>
<s>
There_EX are_VBR also_RR other_JJ methods_NN2 for_IF internalize_VV0 the_AT self-management_NN1 principles_NN2 ,_, but_CCB here_RL is_VBZ a_AT1 few_DA2 of_IO them_PPHO2 ._. 
</s>
<s>
These_DD2 should_VM be_VBI kept_VVN in_II mind_NN1 ,_, when_CS self-management_NN1 principles_NN2 are_VBR being_VBG taken_VVN as_CSA practices_NN2 into_II an_AT1 organization_NN1 ._. 
</s>
<s>
If_CS the_AT top_JJ management_NN1 or_CC the_AT manager_NN1 wants_VVZ to_TO promote_VVI the_AT self-management_NN1 practices_NN2 he_PPHS1 needs_VVZ to_TO first_MD comply_VVI the_AT practices_NN2 in_II his_APPGE own_DA methods_NN2 ._. 
</s>
<s>
This_DD1 way_NN1 he_PPHS1 can_VM promote_VVI the_AT practices_NN2 in_II the_AT entire_JJ organization_NN1 by_II talking_VVG about_II them_PPHO2 ,_, making_VVG them_PPHO2 understandable_JJ ,_, increasing_VVG the_AT knowledge_NN1 about_II them_PPHO2 ,_, enrolling_VVG them_PPHO2 as_II a_AT1 part_NN1 of_IO the_AT vision_NN1 ,_, and_CC making_VVG them_PPHO2 a_AT1 part_NN1 of_IO the_AT working_JJ habits_NN2 that_CST are_VBR being_VBG emphasized_VVN ._. 
</s>
<s>
This_DD1 way_NN1 self-management_NN1 practices_NN2 will_VM not_XX face_VVI resistance_NN1 from_II the_AT employees_NN2 and_CC will_VM be_VBI adapted_VVN to_II the_AT working_JJ manners_NN2 ._. 
</s>
<s>
5_MC Discussion_NN1 I_PPIS1 think_VV0 that_CST todays_NN2 businesses_NN2 emphasize_VV0 much_RR on_II high-performance_NN1 ,_, results_NN2 ,_, hard-working_JJ environment_NN1 ,_, and_CC business_NN1 minded_VVD attitudes_NN2 ._. 
</s>
<s>
Therefore_RR there_EX have_VH0 also_RR been_VBN many_DA2 articles_NN2 and_CC studies_NN2 describing_VVG how_RRQ this_DD1 influences_VVZ workers_NN2 and_CC how_RRQ they_PPHS2 have_VH0 enough_DD strength_NN1 to_TO cope_VVI with_IW the_AT upbeat_JJ business_NN1 life_NN1 ._. 
</s>
<s>
Self-management_NN1 is_VBZ concerned_JJ with_IW questions_NN2 on_II how_RRQ to_TO organize_VVI our_APPGE tasks_NN2 ,_, to_TO do_VDI better_RRR plans_VVZ ,_, to_TO focus_VVI on_II our_APPGE jobs_NN2 ,_, to_TO delegate_VVI tasks_NN2 ,_, to_TO be_VBI more_RGR efficient_JJ ,_, how_RRQ to_TO be_VBI better_RRR at_II decision-making_NN1 and_CC how_RRQ to_TO take_VVI care_NN1 of_IO our_APPGE own_DA development_NN1 so_CS21 that_CS22 we_PPIS2 can_VM manage_VVI our_APPGE own_DA job_NN1 tasks_NN2 ._. 
</s>
<s>
If_CS an_AT1 organization_NN1 could_VM adapt_VVI these_DD2 practices_NN2 in_RP to_II their_APPGE entire_JJ organization_NN1 and_CC its_APPGE methods_NN2 I_PPIS1 think_VV0 that_CST they_PPHS2 could_VM achieve_VVI such_DA an_AT1 environment_NN1 ,_, where_CS high-performance_JJ ,_, hard-work_NN1 ,_, results_NN2 ,_, and_CC business_NN1 minded_VVD attitudes_NN2 are_VBR part_NN1 of_IO the_AT operations_NN2 ._. 
</s>
<s>
This_DD1 is_VBZ why_RRQ I_PPIS1 think_VV0 that_CST it_PPH1 would_VM be_VBI important_JJ for_IF organizations_NN2 to_TO learn_VVI about_II self-management_NN1 and_CC take_VVI themes_NN2 from_II it_PPH1 to_II practice_NN1 ._. 
</s>
<s>
A_AT1 good_JJ manager_NN1 is_VBZ also_RR able_JK to_TO simplify_VVI things_NN2 ,_, so_CS21 that_CS22 the_AT employees_NN2 understand_VV0 the_AT matter_NN1 in_II question_NN1 better_RRR ,_, without_IW losing_VVG the_AT thread_NN1 ._. 
</s>
<s>
(_( Long_RR 2011_MC ;_; Kehusmaa_NP1 2010_MC ._. )_) 
</s>
<s>
At_II the_AT same_DA time_NNT1 changes_NN2 is_VBZ often_RR something_PN1 that_CST is_VBZ feared_VVN in_II organizations_NN2 because_CS it_PPH1 is_VBZ being_VBG seen_VVN as_II a_AT1 threat_NN1 to_II one_MC1 selves_VVZ rank_VV0 ,_, work_VV0 ,_, know-how_NN1 ,_, feeling_NN1 of_IO value_NN1 or_CC ability_NN1 to_TO cope_VVI with_IW it_PPH1 (_( Kehusmaa_NP1 2010_MC :_: 153_MC )_) ._. 
</s>
<s>
By_II first_MD taking_VVG the_AT matters_NN2 into_II practice_NN1 for_IF the_AT managers_NN2 could_VM in_II this_DD1 way_NN1 help_VV0 the_AT entire_JJ organization_NN1 to_TO accept_VVI these_DD2 issues_NN2 better_RRR with_IW less_DAR resistance_NN1 ._. 
</s>
<s>
It_PPH1 could_VM also_RR help_VVI the_AT workers_NN2 to_TO understand_VVI the_AT matters_NN2 in_II question_NN1 better_RRR and_CC in_II that_DD1 way_NN1 make_VV0 it_PPH1 easier_JJR for_IF them_PPHO2 to_TO accept_VVI the_AT changes_NN2 ._. 
</s>
<s>
By_II showing_VVG an_AT1 example_NN1 as_CSA manager_NN1 the_AT employees_NN2 could_VM also_RR see_VVI how_RRQ the_AT matters_NN2 in_II question_NN1 are_VBR really_RR meant_VVN in_II practice_NN1 to_TO be_VBI performed_VVN or_CC used_VVD ._. 
</s>
<s>
I_PPIS1 think_VV0 that_CST these_DD2 methods_NN2 should_VM therefore_RR be_VBI first_MD put_VVN into_II operation_NN1 through_II the_AT management_NN1 to_TO help_VVI the_AT implementation_NN1 to_II the_AT entire_JJ organization_NN1 ._. 
</s>
<s>
In_II a_AT1 learning_NN1 organization_NN1 the_AT individual_NN1 have_VH0 the_AT opportunity_NN1 to_TO improve_VVI ,_, there_EX is_VBZ a_AT1 shared_JJ and_CC common_JJ vision_NN1 ,_, and_CC team_NN1 learning_NN1 is_VBZ a_AT1 part_NN1 of_IO the_AT culture_NN1 ._. 
</s>
<s>
The_AT employee_NN1 satisfaction_NN1 ,_, work_VV0 capability_NN1 ,_, ability_NN1 to_TO learn_VVI ,_, customer_NN1 satisfaction_NN1 ,_, and_CC the_AT impacts_NN2 on_II society_NN1 are_VBR all_DB outcomes_NN2 form_VV0 a_AT1 learning_NN1 organization_NN1 ._. 
</s>
<s>
(_( Kehusmaa_NN1 2010_MC :_: 145-148_MCMC ._. )_) 
</s>
<s>
By_II taking_VVG the_AT practices_NN2 from_II self-management_NN1 in_II use_NN1 this_DD1 is_VBZ what_DDQ could_VM be_VBI achieved_VVN ._. 
</s>
<s>
When_CS an_AT1 organization_NN1 could_VM achieve_VVI this_DD1 ,_, they_PPHS2 will_VM also_RR achieve_VVI a_AT1 hard-working_JJ environment_NN1 ,_, where_CS results_NN2 ,_, business_NN1 minded_VVD attitude_NN1 ,_, and_CC high-performance_NN1 will_VM be_VBI a_AT1 part_NN1 of_IO the_AT organizations_NN2 culture_NN1 ._. 
</s>
<s>
When_CS the_AT employees_NN2 are_VBR happier_JJR with_IW their_APPGE work_NN1 ,_, through_II self-management_NN1 practices_NN2 ,_, they_PPHS2 will_VM also_RR perform_VVI better_RRR ,_, which_DDQ in_II turn_NN1 will_VM lead_VVI to_II a_AT1 better_JJR performing_NN1 ,_, effective_JJ and_CC productive_JJ organization_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ what_DDQ organizations_NN2 are_VBR trying_VVG to_TO achieve_VVI continuously_RR and_CC this_DD1 is_VBZ how_RRQ I_PPIS1 think_VV0 that_CST they_PPHS2 could_VM achieve_VVI it_PPH1 ._. 
</s>
<s>
To_TO encounter_VVI less_DAR resistance_NN1 for_IF the_AT changes_NN2 and_CC get_VV0 the_AT new_JJ methods_NN2 easier_RRR in_II use_NN1 I_PPIS1 think_VV0 that_CST the_AT self-management_NN1 practices_NN2 should_VM be_VBI taken_VVN into_II operation_NN1 through_II the_AT management_NN1 ._. 
</s>
<s>
By_II showing_VVG a_AT1 good_JJ example_NN1 the_AT manager_NN1 can_VM also_RR show_VVI how_RRQ it_PPH1 is_VBZ meant_VVN to_TO be_VBI done_VDN on_II practice_NN1 or_CC how_RRQ we_PPIS2 are_VBR supposed_JJ to_TO perform_VVI ._. 
</s>
<s>
This_DD1 makes_VVZ it_PPH1 also_RR easier_JJR for_IF the_AT employees_NN2 to_TO understand_VVI the_AT matters_NN2 more_RGR clearly_RR ._. 
</s>
<s>
6_MC Conclusion_NN1 Self-management_NN1 as_II a_AT1 topic_NN1 is_VBZ widely_RR discussed_VVN ,_, but_CCB in_II my_APPGE opinion_NN1 bringing_VVG the_AT practices_NN2 into_II use_NN1 has_VHZ gotten_VVN less_DAR attention_NN1 ._. 
</s>
<s>
That_DD1 is_VBZ why_RRQ I_PPIS1 wanted_VVD to_TO consider_VVI the_AT alternative_NN1 to_II takes_NN2 these_DD2 practices_NN2 into_II use_NN1 through_II the_AT help_NN1 of_IO management_NN1 ._. 
</s>
<s>
I_PPIS1 think_VV0 that_CST we_PPIS2 have_VH0 seen_VVN through_II different_JJ literature_NN1 references_VVZ that_CST this_DD1 could_VM be_VBI a_AT1 good_JJ option_NN1 ,_, how_RRQ to_TO introduce_VVI self-management_NN1 into_II organizations_NN2 and_CC take_VVI these_DD2 practices_NN2 into_II action_NN1 ._. 
</s>
<s>
The_AT reasons_NN2 why_RRQ self-management_NN1 should_VM be_VBI introduced_VVN to_II organizations_NN2 have_VH0 also_RR been_VBN presented_VVN ._. 
</s>
<s>
The_AT organization_NN1 will_VM most_RGT likelyachieveshared_JJ making_NN1 ,_, participating_VVG ,_, and_CC gives_VVZ everyone_PN1 ability_NN1 to_II impact_NN1 ._. 
</s>
<s>
This_DD1 way_NN1 the_AT employees_NN2 will_VM be_VBI more_RGR satisfied_JJ and_CC to_II their_APPGE jobs_NN2 better_RRR and_CC more_RGR effective_JJ ._. 
</s>
<s>
This_DD1 ,_, in_II turn_NN1 ,_, will_VM result_VVI in_II a_AT1 more_RGR hard-working_JJ environment_NN1 ,_, where_CS results_NN2 ,_, high-performance_NN1 ,_, and_CC business_NN1 minded_VVD thinking_NN1 will_VM be_VBI preferred_VVN ._. 
</s>
<s>
This_DD1 again_RT is_VBZ what_DDQ all_DB businesses_NN2 are_VBR trying_VVG to_TO accomplish_VVI in_II the_AT hard-working_JJ environment_NN1 that_CST has_VHZ the_AT power_NN1 in_II the_AT exciting_JJ business_NN1 world_NN1 ._. 
</s>
