<s>
Leading_VVG in_II an_AT1 era_NN1 of_IO uncertainty_NN1 INTRODUCTION_NN1 These_DD2 are_VBR scary_JJ times_NNT2 for_IF managers_NN2 in_II big_JJ companies_NN2 ._. 
</s>
<s>
Even_RR before_II the_AT Internet_NN1 and_CC globalization_NN1 ,_, their_APPGE track_NN1 record_NN1 for_IF dealing_VVG with_IW major_JJ ,_, disruptive_JJ change_NN1 was_VBDZ not_XX good._NNU Christensen_NP1 &Overdorf;_NULL (_( 2000:1_MC )_) During_II the_AT last_MD decades_NNT2 ,_, the_AT business_NN1 environment_NN1 has_VHZ changedsignificantly_RR ._. 
</s>
<s>
Organizations_NN2 are_VBR continuously_RR facing_VVG changes_NN2 due_II21 to_II22 the_AT increased_JJ competitive_JJ environment_NN1 ,_, technological_JJ development_NN1 ,_, and_CC changes_NN2 in_II the_AT internal_JJ and_CC the_AT external_JJ circumstances_NN2 ._. 
</s>
<s>
Although_CS ,_, this_DD1 has_VHZ provided_VVN a_AT1 new_JJ set_NN1 of_IO opportunities_NN2 and_CC tools_NN2 for_IF companies_NN2 to_TO work_VVI with_IW ,_, this_DD1 also_RR means_VVZ complexity_NN1 and_CC uncertaintyas_NN2 it_PPH1 creates_VVZ challenges_NN2 for_IF todays_NN2 organizations_NN2 ._. 
</s>
<s>
Christensen_NP1 &;_NULL Overdorf_NP1 (_( 2000:1_MC )_) argue_VV0 that_CST it_PPH1 is_VBZ not_XX about_II that_DD1 leaders_NN2 do_VD0 nt_XX see_VVI the_AT changes_NN2 coming_VVG ;_; instead_RR they_PPHS2 believe_VV0 that_CST the_AT problem_NN1 lies_VVZ in_II the_AT leaders_NN2 way_NN1 of_IO thinking_VVG about_II the_AT companys_NN2 capabilities_NN2 ._. 
</s>
<s>
As_II the_AT opening_NN1 sentence_NN1 pointed_VVD out_RP ,_, even_RR the_AT most_RGT stable_JJ organizations_NN2 are_VBR constantly_RR facing_VVG new_JJ challenges_NN2 as_CSA they_PPHS2 are_VBR criticized_VVN for_IF being_VBG too_RG inflexible_JJ to_TO react_VVI to_II the_AT fast-paced_NN1 and_CC competitive_JJ global_JJ market_NN1 ._. 
</s>
<s>
In_II fact_NN1 ,_, todays_NN2 organizations_NN2 can_VM be_VBI replaced_VVN any_DD minute_NNT1 ,_, and_CC according_II21 to_II22 Montgomery_NP1 (_( 2012_MC )_) the_AT most_RGT important_JJ question_NN1 every_AT1 business_NN1 leader_NN1 should_VM answer_VVI is_VBZ :_: Does_VDZ your_APPGE company_NN1 matter_VVI ?_? 
</s>
<s>
Success_NN1 does_VDZ not_XX depend_VVI on_II one_MC1 person_NN1 ,_, however_RR ,_, when_CS operating_VVG in_II todays_NN2 complex_JJ world_NN1 the_AT importance_NN1 of_IO good_JJ leadership_NN1 becomes_VVZ critical_JJ ._. 
</s>
<s>
The_AT perception_NN1 ofthat_NN1 theconcept_NN1 of_IO a_AT1 winner_NN1 leadershipistimeless_JJ is_VBZ starting_VVG to_TO diminish_VVI as_CSA we_PPIS2 are_VBR moving_VVG away_II21 from_II22 the_AT individualistic_JJ view_NN1 ._. 
</s>
<s>
Therefore_RR ,_, instead_II21 of_II22 imagining_VVG todays_NN2 leaders_NN2 as_II the_AT hero_NN1 who_PNQS is_VBZ front_JJ commanding_JJ the_AT troops_NN2 we_PPIS2 are_VBR taking_VVG an_AT1 approach_NN1 ,_, where_CS todays_NN2 complexity_NN1 and_CC challenges_NN2 are_VBR receiving_VVG a_AT1 bigger_JJR focus.Kotter_NNU (_( 2001_MC )_) agrees_VVZ ,_, and_CC suggests_VVZ that_CST a_AT1 leader_NN1 can_VM be_VBI defined_VVN following_VVG :_: They_PPHS2 &lsqb;_( leaders_NN2 &rsqb;_) do_VD0 n't_XX make_VVI plans_NN2 ;_; they_PPHS2 do_VD0 n't_XX solve_VVI problems_NN2 ;_; they_PPHS2 do_VD0 n't_XX even_RR organize_VVI people_NN ._. 
</s>
<s>
What_DDQ leaders_NN2 really_RR do_VD0 is_VBZ prepare_VVI organizations_NN2 for_IF change_NN1 and_CC help_VV0 them_PPHO2 cope_VVI as_CSA they_PPHS2 struggle_VV0 through_II it._NNU Pree_NN1 speaks_VVZ in_II the_AT same_DA token_NN1 and_CC emphasizes_VVZ that_DD1 leadership_NN1 is_VBZ much_DA1 more_DAR of_IO an_AT1 art_NN1 ,_, a_AT1 belief_NN1 ,_, a_AT1 condition_NN1 of_IO the_AT heart_NN1 ,_, than_CSN a_AT1 set_NN1 of_IO things_NN2 to_II do.Thereforeit_NNU is_VBZ important_JJ to_TO distinctthe_VVI most_DAT significant_JJ changes_NN2 that_CST have_VH0 occurred_VVN during_II the_AT recent_JJ decades_NNT2 and_CC analyze_VV0 how_RRQ they_PPHS2 have_VH0 and_CC will_VM effect_VVI leadership_NN1 ?_? 
</s>
<s>
As_CSA Webber_NP1 (_( 2003_MC )_) emphasizes_VVZ other_JJ challenges_NN2 are_VBR ours_PPGE to_TO change_VVI ._. 
</s>
<s>
The_AT purpose_NN1 with_IW this_DD1 paper_NN1 is_VBZ to_TO expand_VVI current_JJ research_NN1 on_II investigating_VVG how_RRQ the_AT complexity_NN1 and_CC challenges_NN2 of_IO the_AT changing_JJ business_NN1 environment_NN1 hasaffected_VVD todays_NN2 leadership_NN1 landscape_NN1 ._. 
</s>
<s>
As_CSA Tirozzi_NP1 (_( 2001_MC )_) notes_NN2 ,_, changing_VVG landscape_NN1 requires_VVZ new_JJ skills_NN2 ._. 
</s>
<s>
Tirozzi_NN2 (_( 2001_MC )_) underlines_VVZ the_AT importance_NN1 of_IO understanding_NN1 and_CC assessing_VVG the_AT demographic_JJ ,_, technological_JJ ,_, social_JJ and_CC economic_JJ trends_NN2 in_II the_AT horizon_NN1 ._. 
</s>
<s>
Furthermore_RR ,_, this_DD1 paper_NN1 contributes_VVZ to_II understanding_NN1 of_IO how_RRQ the_AT external_JJ factors_NN2 are_VBR changing_VVG and_CC will_VM change_VVI the_AT leadership_NN1 role_NN1 ._. 
</s>
<s>
Doing_VDG so_RR ,_, various_JJ events_NN2 and_CC changes_NN2 are_VBR discussed_VVN ._. 
</s>
<s>
Despite_II the_AT importance_NN1 the_AT external_JJ changes_NN2 that_CST has_VHZ occurred_VVN during_II the_AT recent_JJ decades_NNT2 ,_, there_EX are_VBR relatively_RR few_DA2 literature_NN1 papers_NN2 describing_VVG the_AT relationship_NN1 between_II change_NN1 and_CC leadership_NN1 ._. 
</s>
<s>
Therefore_RR ,_, thispaper_NN1 hopes_VVZ to_TO contribute_VVI to_II the_AT discussion_NN1 about_II the_AT main_JJ challenges_NN2 that_CST leaders_NN2 face_VV0 resulted_VVN from_II the_AT changes_NN2 inenvironment._NNU 1.2_MC Aim_NN1 and_CC contribution_NN1 This_DD1 study_NN1 aims_VVZ at_II finding_VVG in-depth_JJ information_NN1 about_II the_AT current_JJ external_JJ factors_NN2 and_CC analyzes_VVZ their_APPGE effect_NN1 on_II the_AT leadership_NN1 role.The_NNU reason_NN1 to_II that_CST this_DD1 topic_NN1 is_VBZ analyzed_VVN is_VBZ to_TO gain_VVI a_AT1 better_JJR understanding_NN1 the_AT impacts_NN2 the_AT current_JJ changes_NN2 in_II the_AT business_NN1 environment_NN1 and_CC what_DDQ impact_NN1 they_PPHS2 have_VH0 on_II the_AT leadership_NN1 role_NN1 ._. 
</s>
<s>
(_( M3:S1_FO )_) I_PPIS1 hope_VV0 to_TO provide_VVI some_DD recommendations_NN2 to_II future_JJ leaders_NN2 to_TO consider_VVI while_CS making_VVG choices_NN2 and_CC doing_VDG business_NN1 in_II todays_NN2 shifting_VVG and_CC complex_JJ business_NN1 environment_NN1 ._. 
</s>
<s>
The_AT aim_NN1 of_IO this_DD1 paper_NN1 is_VBZ to_TO contribute_VVI to_II the_AT current_JJ debate_NN1 with_IW existing_JJ literature_NN1 supported_VVN by_II apersonal_JJ interview_NN1 and_CC quest-lecture_JJ notes_NN2 ._. 
</s>
<s>
1.3_MC Method_NN1 In_BCL21 order_BCL22 to_TO answer_VVI the_AT research_NN1 question_NN1 a_AT1 personal_JJ interview_NN1 is_VBZ conducted_VVN ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, guest-lecture_JJ notes_NN2 and_CC a_AT1 literature_NN1 review_NN1 are_VBR also_RR presented_VVN ._. 
</s>
