<s>
Smoking_JJ ban_NN1 :_: social_JJ effects_NN2 ._. 
</s>
<s>
Abstract_JJ Introduction_NN1 Recently_RR ,_, enormous_JJ change_NN1 in_II the_AT treatment_NN1 of_IO smoking_VVG by_II both_DB2 the_AT public_NN1 and_CC policy_NN1 makers_NN2 took_VVD place_NN1 ._. 
</s>
<s>
Smoking_NN1 has_VHZ become_VVN increasingly_RR taboo_JJ in_II our_APPGE society_NN1 ,_, and_CC the_AT discrimination_NN1 against_II it_PPH1 keeps_VVZ getting_VVG worse_JJR with_IW more_DAR bans_NN2 ._. 
</s>
<s>
Main_JJ attention_NN1 is_VBZ deserved_VVN by_II smoke-free_JJ workplaces_NN2 approach_VV0 in_II companies_NN2 ;_; however_RR there_EX has_VHZ been_VBN wide_JJ interest_NN1 in_II smoker-free_JJ workplaces_NN2 as_RR21 well_RR22 ._. 
</s>
<s>
This_DD1 requirement_NN1 is_VBZ becoming_VVG more_RRR and_CC more_RGR widespread_JJ and_CC raises_VVZ questions_NN2 of_IO its_APPGE appropriateness_NN1 and_CC future_JJ results_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ generally_RR accepted_VVN that_DD1 smoking_NN1 by_II all_DB means_NN has_VHZ only_RR negative_JJ sides_NN2 ._. 
</s>
<s>
Policy_NN1 against_II smoking_NN1 seems_VVZ to_TO be_VBI very_RG aggressive_JJ and_CC focused_VVD on_II achieving_VVG results_NN2 already_RR in_RR21 short_RR22 term_VV0 period_NN1 ._. 
</s>
<s>
But_CCB are_VBR these_DD2 directive_NN1 methods_NN2 could_VM not_XX lead_VVI to_II unemployment_NN1 of_IO great_JJ minds_NN2 that_CST are_VBR addicted_VVN ?_? 
</s>
<s>
Will_VM the_AT economy_NN1 be_VBI caused_VVN less_RRR from_II it_PPH1 rather_II21 than_II22 by_II employment_NN1 of_IO non-addicted_NN1 ?_? 
</s>
<s>
The_AT most_RGT active_JJ position_NN1 in_II discovering_VVG smoking_JJ policy_NN1 issues_NN2 is_VBZ taken_VVN by_II National_JJ Health_NN1 authorities_NN2 in_II different_JJ countries_NN2 which_DDQ issue_VV0 rules_NN2 that_CST many_DA2 companies_NN2 take_VV0 as_CSA obligations_NN2 ._. 
</s>
<s>
However_RR ,_, lots_PN of_IO researches_NN2 also_RR active_JJ in_II discovering_VVG this_DD1 topic_NN1 ._. 
</s>
<s>
Observations_NN2 by_II Milton_NP1 (_( 1998_MC )_) are_VBR focused_VVN of_IO smokers_NN2 costs_VVZ for_IF companies_NN2 ._. 
</s>
<s>
James_NP1 (_( 2007_MC )_) suggests_VVZ that_CST smokers_NN2 influence_VV0 on_II company_NN1 performance_NN1 to_II a_AT1 large_JJ extend_VV0 ._. 
</s>
<s>
Several_DA2 researches_NN2 focused_VVN on_II economic_JJ impact_NN1 of_IO smoking_JJ bans_NN2 and_CC found_VVD out_RP both_RR positive_JJ and_CC negative_JJ results_NN2 (_( Jonathan_NP1 ,_, Tomlin_NP1 ,_, 2009_MC )_) ._. 
</s>
<s>
Moreover_RR ,_, special_JJ attention_NN1 is_VBZ devoted_JJ to_II particular_JJ economic_JJ benefits_NN2 of_IO smoking_NN1 (_( Richards_NP1 ,_, 2004_MC )_) ._. 
</s>
<s>
Seigel_NP1 (_( 2009_MC )_) in_II his_APPGE studies_NN2 takes_VVZ strong_JJ opposition_NN1 to_II smoker-free_JJ issue_NN1 claiming_VVG that_DD1 unemployment_NN1 is_VBZ also_RR bad_JJ for_IF health_NN1 ._. 
</s>
<s>
As_II a_AT1 result_NN1 ,_, views_NN2 on_II this_DD1 topic_NN1 are_VBR diversified_VVN ._. 
</s>
<s>
However_RR ,_, opposition_NN1 side_NN1 is_VBZ usually_RR omitted_VVN due_II the_AT privilege_NN1 of_IO main_JJ authority_NN1 who_PNQS dictates_VVZ the_AT rules_NN2 ._. 
</s>
<s>
This_DD1 paper_NN1 tries_VVZ to_TO throw_VVI light_NN1 on_II the_AT shadowed_JJ side_NN1 of_IO the_AT problem_NN1 ._. 
</s>
<s>
Our_APPGE idea_NN1 is_VBZ that_DD1 economy_NN1 of_IO smoking_NN1 is_VBZ able_JK to_TO weaken_VVI the_AT tension_NN1 in_II society_NN1 that_CST now_RT exists_VVZ and_CC to_TO demonstrate_VVI social_JJ cost_NN1 of_IO smoking_VVG from_II different_JJ point_NN1 of_IO view_NN1 ._. 
</s>
<s>
This_DD1 paper_NN1 is_VBZ structured_VVN as_CSA follows_VVZ :_: first_MD of_IO all_DB current_JJ smoking_JJ policy_NN1 trends_NN2 are_VBR discussed_VVN ;_; then_RT basics_NN2 of_IO economy_NN1 of_IO smoking_NN1 is_VBZ under_II consideration_NN1 ;_; and_CC finally_RR some_DD benefits_NN2 of_IO smoking_VVG in_II different_JJ prospective_JJ are_VBR highlighted_VVN ._. 
</s>
<s>
Literature_NN1 review_VV0 How_RGQ much_DA1 smoking_NN1 costs_VVZ ?_? 
</s>
<s>
Problems_NN2 caused_VVN by_II smoking_NN1 are_VBR usually_RR looked_VVN under_II the_AT smoking_JJ costs_NN2 ._. 
</s>
<s>
There_RL several_DA2 classification_NN1 of_IO smoking_JJ costs_NN2 ._. 
</s>
<s>
National_JJ Institute_NN1 for_IF Health_NN1 and_CC Clinical_JJ Excellence_NN1 (_( NICE_JJ )_) defines_VVZ smoking_JJ costs_NN2 as_CSA direct_JJ and_CC indirect_JJ ._. 
</s>
<s>
However_RR ,_, to_II our_APPGE mind_NN1 the_AT extended_JJ classification_NN1 should_VM took_VVD place_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ how_RRQ National_JJ Business_NN1 Group_NN1 on_II Health_NN1 points_VVZ out_RP these_DD2 kinds_NN2 of_IO smoking_JJ costs_NN2 :_: direct_JJ ,_, indirect_JJ ,_, societal_JJ and_CC workplace_NN1 Direct_JJ costs_NN2 are_VBR money_NN1 spent_VVN on_II health_NN1 services_NN2 ._. 
</s>
<s>
Direct_JJ costs_NN2 include_VV0 payments_NN2 on_II healthcare_NN1 benefits_NN2 ,_, disability_NN1 ,_, and_CC compensation_NN1 of_IO an_AT1 employee_NN1 ._. 
</s>
<s>
Indirect_JJ costs_NN2 are_VBR spending_VVG related_JJ to_II not_XX immediate_JJ treatment_NN1 of_IO disease_NN1 ._. 
</s>
<s>
These_DD2 costs_NN2 cover_VV0 lost_JJ wages_NN2 ,_, lost_VVD workdays_NN2 ,_, overtime_NN1 premiums_NN2 ,_, costs_NN2 related_VVN to_II using_VVG replacement_NN1 workers_NN2 ,_, productivity_NN1 losses_NN2 related_VVN to_II unscheduled_JJ absences_NN2 ,_, and_CC productivity_NN1 losses_NN2 of_IO workers_NN2 on_II the_AT job_NN1 ._. 
</s>
<s>
However_RR ,_, these_DD2 costs_NN2 not_XX only_RR related_VVN to_II employers_NN2 ,_, it_PPH1 also_RR affect_VV0 society_NN1 what_DDQ brings_VVZ societal_JJ costs_NN2 in_II a_AT1 form_NN1 of_IO poor_JJ health_NN1 ,_, injuries_NN2 ,_, and_CC deaths_NN2 that_CST are_VBR a_AT1 burden_NN1 to_II society_NN1 as_II a_AT1 whole_NN1 ._. 
</s>
<s>
Societal_JJ costs_NN2 of_IO smoking_VVG also_RR include_VV0 poor_JJ health_NN1 related_VVN to_II secondhand_JJ smoke_NN1 issue_NN1 ._. 
</s>
<s>
Another_DD1 type_NN1 of_IO tobacco_NN1 use_NN1 costs_NN2 is_VBZ workplace_NN1 costs_VVZ that_CST usually_RR considered_VVN as_CSA employer_NN1 direct_JJ and_CC indirect_JJ costs_NN2 and_CC it_PPH1 is_VBZ presented_VVN in_II details_NN2 in_II table_NN1 1_MC1 ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) Business_NN1 opportunity_NN1 costs_NN2 allow_VV0 us_PPIO2 to_TO see_VVI to_II what_DDQ extend_VV0 smokers_NN2 affect_VV0 employers_NN2 ._. 
</s>
<s>
Table_NN1 2_MC shows_VVZ that_CST according_II21 to_II22 NICE_JJ smokers_NN2 bring_VV0 to_II their_APPGE employers_NN2 costs_VVZ that_CST are_VBR equal_JJ to_II 7774_MC annually_RR through_II wasting_VVG time_NNT1 on_II smoking_NN1 ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) According_II21 to_II22 BBC_NP1 :_: Smokers_NN2 take_VV0 on_RP average_JJ half_DB an_AT1 hour_NNT1 from_II their_APPGE working_JJ day_NNT1 to_TO enjoy_VVI a_AT1 cigarette_NN1 ,_, a_AT1 survey_NN1 suggests._NNU The_AT study_NN1 of_IO 1,000_MC adults_NN2 found_VVD that_CST the_AT average_JJ smoker_NN1 took_VVD about_RG three_MC 10_MC minute_NNT1 breaks_VVZ while_CS at_II work_NN1 to_TO smoke_VVI ._. 
</s>
<s>
The_AT Benenden_NN1 Healthcare_NN1 Society_NN1 estimated_VVD that_CST 290,000_MC working_JJ days_NNT2 were_VBDR lost_VVN in_II the_AT UK_NP1 each_DD1 year_NNT1 by_II smokers_NN2 leaving_VVG the_AT office_NN1 ._. 
</s>
<s>
Many_DA2 employers_NN2 cite_VV0 the_AT lost_JJ productivity_NN1 caused_VVN by_II constant_JJ cigarette_NN1 breaks_VVZ for_IF smokers_NN2 and_CC constant_JJ fresh-air_JJ breaks_NN2 for_IF non-smokers_NN2 ._. 
</s>
<s>
I_PPIS1 do_VD0 nt_XX care_VVI what_DDQ it_PPH1 is_VBZ ,_, says_VVZ a_AT1 human_JJ resources_NN2 director_NN1 at_II a_AT1 Fortune_NN1 500_MC company_NN1 who_PNQS requested_VVD that_CST HyperVocal_NP1 not_XX publish_VV0 her_APPGE name_NN1 ._. 
</s>
<s>
I_PPIS1 once_RR fired_VVD someone_PN1 because_CS he_PPHS1 left_VVD the_AT office_NN1 every_AT1 hour_NNT1 for_IF a_AT1 pudding_NN1 break_NN1 ._. 
</s>
<s>
He_PPHS1 said_VVD that_CST without_IW pudding_NN1 ,_, hed_VVD get_VV0 a_AT1 terrible_JJ headache_NN1 ,_, have_VH0 trouble_NN1 concentrating_VVG ,_, and_CC that_CST hed_VVD become_VV0 uncontrollably_RR lascivious_JJ ._. 
</s>
<s>
But_CCB seriously_RR ,_, he_PPHS1 was_VBDZ doing_VDG like_II three_MC cartons_NN2 of_IO Snack_NN1 Packs_NN2 a_AT1 day_NNT1 on_II company_NN1 time_NNT1 ._. 
</s>
<s>
It_PPH1 was_VBDZ a_AT1 real_JJ problem._NNU The_AT group_NN1 said_VVD that_CST smoking_JJ breaks_NN2 were_VBDR a_AT1 "_" bone_NN1 of_IO contention_NN1 "_" in_II workplaces_NN2 ._. 
</s>
<s>
Many_DA2 commentators_NN2 have_VH0 argued_VVN that_CST this_DD1 puts_VVZ non-smokers_NN2 at_II a_AT1 disadvantage_NN1 and_CC is_VBZ unfair_JJ because_CS smokers_NN2 choose_VV0 to_TO smoke_VVI ._. 
</s>
<s>
With_IW regards_VVZ to_II world_NN1 database_NN1 of_IO smoking_JJ statistics_NN the_AT percentage_NN1 of_IO smokers_NN2 by_II job_NN1 type_NN1 looks_VVZ as_CSA follows_VVZ :_: 16%_NNU of_IO professionals_NN2 ,_, 20%_NNU of_IO managers_NN2 ,_, 26%_NNU of_IO supervisor_NN1 ,_, 32%_NNU of_IO manual_JJ workers_NN2 ._. 
</s>
<s>
Smoke-free_JJ zone_NN1 Smoking_NN1 ban_NN1 issue_NN1 is_VBZ not_XX a_AT1 new_JJ one_PN1 and_CC it_PPH1 takes_VVZ it_PPH1 root_VV0 back_RP to_II 1590_MC when_RRQ Pope_NNB Urban_NP1 VII_MC during_II his_APPGE short_JJ reign_NN1 as_CSA pope_NN1 declared_VVD that_CST anyone_PN1 "_" took_VVD tobacco_NN1 in_II the_AT porchway_NN1 of_IO or_CC inside_II a_AT1 church_NN1 ,_, whether_CSW it_PPH1 be_VBI by_II chewing_VVG it_PPH1 ,_, smoking_VVG it_PPH1 with_IW a_AT1 pipe_NN1 or_CC sniffing_VVG it_PPH1 in_II powdered_JJ form_NN1 through_II the_AT nose_NN1 "_" The_AT first_MD building_NN1 in_II the_AT world_NN1 to_TO have_VHI a_AT1 smoke-free_JJ policy_NN1 was_VBDZ the_AT Old_JJ Government_NN1 Building_NN1 in_II Wellington_NP1 ,_, New_NP1 Zealand_NP1 in_II 1876_MC ._. 
</s>
<s>
However_RR ,_, this_DD1 was_VBDZ over_II concerns_NN2 about_II the_AT threat_NN1 of_IO fire_NN1 ,_, as_CSA it_PPH1 is_VBZ the_AT second_MD largest_JJT wooden_JJ building_NN1 in_II the_AT world_NN1 ._. 
</s>
<s>
The_AT smoking_NN1 bans_VVZ rational_JJ lies_NN2 in_II the_AT fact_NN1 that_CST smoking_NN1 is_VBZ optional_JJ and_CC breathing_NN1 is_VBZ not_XX ._. 
</s>
<s>
Therefore_RR ,_, smoke-free_JJ laws_NN2 protect_VV0 non-smokers_NN2 from_II second-hand_JJ smoke_NN1 effect_NN1 ._. 
</s>
<s>
Laws_NN2 on_II smoking_JJ bans_NN2 have_VH0 been_VBN introduced_VVN in_II many_DA2 countries_NN2 in_II different_JJ ways_NN2 over_II last_MD years_NNT2 ._. 
</s>
<s>
What_DDQ is_VBZ more_RRR ,_, such_DA laws_NN2 may_VM decrease_VVI the_AT healthcare_NN1 costs_NN2 ,_, improve_VV0 work_NN1 productivity_NN1 and_CC lower_JJR business_NN1 cost_NN1 of_IO labor_NN1 that_CST could_VM lead_VVI to_II creating_VVG community_NN1 that_CST is_VBZ more_RGR attractive_JJ for_IF employers_NN2 ._. 
</s>
<s>
Moreover_RR ,_, smoking_JJ cessation_NN1 reduce_VV0 risk_NN1 of_IO fire_NN1 in_II areas_NN2 with_IW explosive_JJ hazard_NN1 ,_, decrease_NN1 costs_VVZ on_II ventilation_NN1 ,_, make_VV0 food_NN1 ,_, pharmaceutical_JJ and_CC other_JJ this_DD1 kind_NN1 of_IO places_NN2 cleaner_NN1 ,_, and_CC in_RR21 general_RR22 can_VV0 healthier_JJR environment_NN1 ._. 
</s>
<s>
Active_JJ position_NN1 is_VBZ taken_VVN by_II the_AT World_NN1 Health_NN1 Organization_NN1 which_DDQ activity_NN1 aimed_VVN in_II creating_VVG an_AT1 environment_NN1 where_CS smoking_NN1 is_VBZ more_RGR difficult_JJ and_CC acceptance_NN1 of_IO smoking_VVG by_II society_NN1 itself_PPX1 is_VBZ eliminated_VVN in_II everyday_JJ life_NN1 ._. 
</s>
<s>
However_RR ,_, smoking_JJ ban_NN1 is_VBZ a_AT1 controversial_JJ issue_NN1 ._. 
</s>
<s>
Most_DAT popular_JJ point_NN1 of_IO criticism_NN1 of_IO smoking_JJ ban_NN1 is_VBZ the_AT violation_NN1 of_IO personal_JJ rights_NN2 ._. 
</s>
<s>
Others_NN2 say_VV0 it_PPH1 is_VBZ hypocritical_JJ to_TO ban_VVI cigarettes_NN2 and_CC then_RT continue_VVI to_TO tax_VVI these_DD2 harmful_JJ products_NN2 ._. 
</s>
<s>
This_DD1 is_VBZ a_AT1 major_JJ argument_NN1 ,_, because_CS many_DA2 countries_NN2 receive_VV0 high_JJ amounts_NN2 of_IO revenue_NN1 from_II the_AT tax_NN1 on_II cigarettes_NN2 ._. 
</s>
<s>
Also_RR smoking_VVG adversely_RR affects_VVZ certain_JJ types_NN2 of_IO businesses_NN2 ,_, for_REX21 instance_REX22 bars_NN2 or_CC restaurants_NN2 ._. 
</s>
<s>
Though_CS ,_, another_DD1 side_NN1 of_IO a_AT1 coin_NN1 is_VBZ also_RR important_JJ ._. 
</s>
<s>
Of_RR21 course_RR22 ,_, businesses_NN2 that_CST are_VBR under_RG smoking_JJ ban_NN1 must_VM provide_VVI outdoor_JJ smoking_JJ areas_NN2 ,_, but_CCB many_DA2 businesses_NN2 found_VVD out_RP that_CST their_APPGE performance_NN1 increases_VVZ because_CS non-smokers_NN2 fells_NN2 more_RGR comfortable_JJ in_II the_AT environment_NN1 than_CSN they_PPHS2 were_VBDR when_RRQ smoking_NN1 was_VBDZ allowed_VVN ._. 
</s>
<s>
In_II restaurants_NN2 ,_, smokers_NN2 are_VBR no_RR21 longer_RR22 lingering_JJ over_II cigarettes_NN2 over_II conversation_NN1 and_CC taking_VVG up_RP a_AT1 table_NN1 that_CST a_AT1 new_JJ customer_NN1 who_PNQS will_VM have_VHI a_AT1 new_JJ bill_NN1 could_VM be_VBI using_VVG ._. 
</s>
<s>
When_RRQ smokers_NN2 pay_VV0 their_APPGE bill_NN1 and_CC leave_VV0 to_TO smoke_VVI ,_, then_RT a_AT1 new_JJ customer_NN1 can_VM use_VVI the_AT table_NN1 ,_, bringing_VVG in_II more_DAR income_NN1 to_II the_AT restaurant_NN1 or_CC bar_NN1 ._. 
</s>
<s>
Referring_VVG to_II the_AT effect_NN1 of_IO smoking_JJ bans_NN2 ,_, Dan_NP1 Plonka_NP1 of_IO Bingo_NN1 Caller_NN1 Magazine_NN1 said_VVD ,_, "_" Some_DD organizations_NN2 have_VH0 completely_RR lost_VVN every_AT1 single_JJ penny_NNU1 of_IO profit_NN1 their_APPGE losses_NN2 have_VH0 been_VBN over_RG 100_MC percent_NNU ._. 
</s>
<s>
Other_JJ organizations_NN2 are_VBR down_RP about_RG 10_MC to_II 15_MC percent_NNU ;_; most_DAT are_VBR down_RP about_RG 50_MC percent_NNU of_IO the_AT profits_NN2 ._. "_" 
</s>
<s>
Bowling_NN1 business_NN1 faces_VVZ another_DD1 unique_JJ problem_NN1 shoes_NN2 ._. 
</s>
<s>
A_AT1 smoker_NN1 is_VBZ not_XX allowed_VVN to_TO step_VVI outside_RL for_IF a_AT1 smoke_NN1 while_CS wearing_VVG bowling_NN1 shoes_NN2 ._. 
</s>
<s>
They_PPHS2 'd_VM have_VHI to_TO change_VVI their_APPGE shoes_NN2 twice_RR each_DD1 time_NNT1 they_PPHS2 wanted_VVD to_TO smoke_VVI ._. 
</s>
<s>
Most_DAT of_IO them_PPHO2 wo_VM n't_XX bother_VVI ._. 
</s>
<s>
Laurel_NP1 Bowl_NN1 had_VHD been_VBN successful_JJ bowling_NN1 club_NN1 for_IF thirty-four_MC years_NNT2 before_II California_NP1 's_GE statewide_JJ ban_NN1 ._. 
</s>
<s>
Three_MC hundred_NNO and_CC eighty-five_MC league_NN1 bowlers_NN2 quit_VVN because_II21 of_II22 the_AT ban_NN1 ,_, which_DDQ cost_VV0 the_AT business_NN1 $200,000_NNU in_II annual_JJ revenues_NN2 ._. 
</s>
<s>
Business_NN1 that_CST sell_VV0 and_CC service_NN1 air_NN1 cleaning_NN1 units_NN2 are_VBR affected_VVN as_RR21 well_RR22 ._. 
</s>
<s>
If_CS there_EX are_VBR no_AT smokers_NN2 ,_, there_EX 's_VBZ no_AT reason_NN1 to_TO buy_VVI an_AT1 air_NN1 cleaner_NN1 ._. 
</s>
<s>
If_CS one_PN1 was_VBDZ purchased_VVN ,_, there_EX 's_VBZ no_AT need_NN1 to_TO use_VVI it_PPH1 ,_, so_CS no_AT service_NN1 is_VBZ meant_VVN ._. 
</s>
<s>
In_II 2004_MC The_AT Empire_NP1 State_NP1 Restaurant_NN1 and_CC Tavern_NP1 Association_NN1 funded_VVN a_AT1 study_NN1 that_CST was_VBDZ conducted_VVN by_II Ridgewood_NP1 Economic_JJ Associates_NN2 ._. 
</s>
<s>
It_PPH1 concentrated_VVD on_II small_JJ ,_, independent_JJ taverns_NN2 ._. 
</s>
<s>
They_PPHS2 found_VVD that_CST bars_NN2 and_CC taverns_NN2 in_II the_AT state_NN1 have_VH0 lost_VVN about_RG 2,000_MC jobs_NN2 ,_, $28.5_NNU million_NNO in_II salary_NN1 payments_NN2 and_CC $37_NNU million_NNO in_II gross_JJ state_NN1 product_NN1 ._. 
</s>
<s>
Smoker-free_JJ policy_NN1 Recently_RR ,_, a_AT1 new_JJ trend_NN1 in_II smoking_JJ policies_NN2 on_II workplace_NN1 has_VHZ emerged_VVN :_: a_AT1 shift_NN1 from_II smoke-free_JJ to_II smoker-free_JJ workplace_NN1 policies_NN2 ._. 
</s>
<s>
These_DD2 policies_NN2 ,_, instituted_VVN by_II employers_NN2 but_CCB often_RR promoted_VVN by_II public_JJ health_NN1 or_CC tobacco_NN1 control_NN1 organizations_NN2 ,_, refuse_VV0 employment_NN1 to_II smokers_NN2 ;_; some_DD companies_NN2 even_RR dismiss_VV0 already_RR employed_VVN employees_NN2 if_CS they_PPHS2 do_VD0 not_XX quit_VVI in_II a_AT1 prescribed_JJ time_NNT1 period_NN1 ._. 
</s>
<s>
Nuffield_NP1 Proactive_JJ Health_NN1 surveyed_VVD managerial_JJ level_JJ employers_NN2 ,_, with_IW 73%_NNU saying_VVG they_PPHS2 would_VM choose_VVI a_AT1 non-smoking_JJ candidate_NN1 over_II a_AT1 smoker_NN1 ._. 
</s>
<s>
Employers_NN2 only_RR follow_VV0 new_JJ streams_NN2 of_IO policy_NN1 ,_, while_CS tobacco_NN1 control_NN1 movement_NN1 has_VHZ played_VVN huge_JJ role_NN1 in_II promoting_VVG it_PPH1 ._. 
</s>
<s>
For_REX21 example_REX22 ,_, the_AT National_JJ Cancer_NN1 Institutes_NN2 (_( NCI_NP1 )_) ASSIST_VV0 manual_NN1 (_( Strategies_NN2 to_II Control_NN1 Tobacco_NN1 Use_NN1 In_II the_AT United_NP1 States_NP1 :_: A_AT1 Blueprint_NN1 for_IF Public_JJ Health_NN1 Action_NN1 in_II the_AT 1990s_MC2 )_) suggests_VVZ hiring_NN1 of_IO nonsmokers_NN2 on_II preferential_JJ basis_NN1 what_DDQ is_VBZ aimed_VVN in_II decreasing_JJ cigarette_NN1 consumption_NN1 :_: Economic_JJ incentives_NN2 serve_VV0 to_TO reduce_VVI consumption_NN1 of_IO tobacco_NN1 products_NN2 by_II increasing_VVG ,_, either_RR directly_RR or_CC indirectly_RR ,_, the_AT costs_NN2 of_IO using_VVG these_DD2 products_NN2 ._. 
</s>
<s>
In_II this_DD1 section_NN1 ,_, three_MC economic_JJ incentive_NN1 policies_NN2 are_VBR examined_VVN :_: (_( 1_MC1 )_) higher_JJR excise_NN1 taxes_NN2 on_II cigarettes_NN2 ,_, (_( 2_MC )_) preferential_JJ hiring_NN1 and_CC promotion_NN1 of_IO nonsmokers_NN2 ,_, and_CC (_( 3_MC )_) insurance_NN1 premium_NN1 differentials_NN2 for_IF smokers_NN2 and_CC nonsmokers._NNU However_RR ,_, smoker-free_JJ policies_NN2 are_VBR still_RR highly_RR criticized_VVN ._. 
</s>
<s>
Smoking_NN1 is_VBZ treated_VVN as_CSA dangerous_JJ for_IF peoples_NN2 life_NN1 ,_, though_CS there_EX is_VBZ no_AT policy_NN1 that_CST will_VM ban_VVI skiing_NN1 or_CC doing_VDG kayak_NN1 shark_NN1 rafting_NN1 ,_, which_DDQ is_VBZ much_RR riskier_JJR ._. 
</s>
<s>
All_DB human_JJ activities_NN2 carry_VV0 costs_NN2 that_CST have_VH0 to_TO be_VBI weighed_VVN against_II their_APPGE benefits_NN2 ._. 
</s>
<s>
Economist_NN1 Kip_NN1 Viscusi_NN1 reports_VVZ that_CST ,_, in_II the_AT U.S._NP1 ,_, the_AT annual_JJ death_NN1 risk_NN1 from_II motor_NN1 vehicle_NN1 accidents_NN2 is_VBZ 1/5,000_MF ._. 
</s>
<s>
In_II France_NP1 ,_, 115,000_MC skiers_NN2 are_VBR injured_VVN every_AT1 year_NNT1 ,_, and_CC more_DAR than_CSN 50_MC killed_VVD ._. 
</s>
<s>
Usually_RR ,_, 390_MC Canadians_NN2 drown_VV0 ,_, and_CC 5_MC are_VBR killed_VVN by_II lightning_NN1 ._. 
</s>
<s>
People_NN take_VV0 risks_NN2 into_II account_NN1 while_CS making_VVG choices_NN2 supposedly_RR ._. 
</s>
<s>
So_RR the_AT question_NN1 is_VBZ why_RRQ does_VDZ the_AT state_NN1 try_VVI and_CC persuade_VVI individuals_NN2 to_TO quit_VVI smoking_NN1 ,_, but_CCB not_XX skiing_VVG ?_? 
</s>
