<s>
Online_JJ shopping_NN1 :_: The_AT Role_NN1 of_IO Shopping_NN1 Motives_NN2 INTRODUCTION_NN1 Since_CS the_AT late_JJ 1990s_MC2 ,_, the_AT number_NN1 of_IO consumers_NN2 using_VVG the_AT internet_NN1 for_IF shopping_NN1 has_VHZ been_VBN growing_VVG rapidly_RR (_( Childers_NP1 ,_, Carr_NP1 ,_, Peck_NP1 &;_NULL Parsons_NP1 ,_, 2001_MC )_) ._. 
</s>
<s>
Some_DD researchers_NN2 explain_VV0 this_DD1 growth_NN1 by_II the_AT Internets_NP1 ability_NN1 to_TO provide_VVI consumers_NN2 with_IW more_DAR products_NN2 and_CC services_NN2 to_TO choose_VVI from_II ,_, more_DAR information_NN1 about_II availability_NN1 ,_, and_CC often_RR at_II more_RGR affordable_JJ prices_NN2 than_CSN in_II traditional_JJ brick_NN1 and_CC mortar_VV0 stores_NN2 (_( Rajamma_NP1 ,_, Paswan_NP1 &;_NULL Ganesh_NP1 ,_, 2007_MC )_) ._. 
</s>
<s>
Furthermore_RR ,_, the_AT Internet_NN1 enables_VVZ one_PN1 to_TO buy_VVI from_II any_DD location_NN1 ,_, 24_MC hours_NNT2 a_AT1 day_NNT1 ,_, 7_MC days_NNT2 a_AT1 week_NNT1 (_( Mathwick_NP1 ,_, Malhotra_NP1 &;_NULL Rigdon_NP1 ,_, 2001_MC )_) ._. 
</s>
<s>
Indeed_RR ,_, convenience_NN1 and_CC efficiency_NN1 have_VH0 been_VBN identified_VVN as_CSA important_JJ motives_NN2 for_IF online_JJ shopping_NN1 (_( Childers_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2001_MC )_) ._. 
</s>
<s>
However_RR ,_, studies_NN2 that_CST shows_VVZ that_CST many_DA2 consumers_NN2 engage_VV0 in_II online_JJ shopping_NN1 activities_NN2 without_IW any_DD concrete_JJ intention_NN1 of_IO making_VVG purchases_NN2 have_VHI started_VVN to_TO emerge_VVI ._. 
</s>
<s>
While_CS some_DD consumers_NN2 engage_VV0 in_RP online_RR shopping_VVG to_TO maximize_VVI utility_NN1 ,_, others_NN2 tend_VV0 to_TO shop_VVI for_IF freedom_NN1 ,_, fun_NN1 ,_, sensory_JJ stimulation_NN1 ,_, and_CC enjoyment_NN1 (_( Holbrook_NP1 &;_NULL Hirschman_NP1 ,_, 1982_MC ;_; Overby_NP1 &;_NULL Lee_NP1 ,_, 2006_MC )_) ._. 
</s>
<s>
Indeed_RR ,_, consumers_NN2 shop_VV0 online_RR for_IF both_DB2 utilitarian_JJ and_CC hedonic_JJ purposes_NN2 (_( Bridges_NP1 &;_NULL Florsheim_NP1 ,_, 2007_MC )_) ._. 
</s>
<s>
Although_CS research_NN1 into_II online_JJ shopping_NN1 motives_NN2 has_VHZ expanded_VVN substantially_RR in_II recent_JJ years_NNT2 ,_, relatively_RR few_DA2 studies_NN2 have_VH0 considered_VVN hedonic_JJ factors_NN2 associated_VVN with_IW online_JJ shopping_NN1 (_( Overby_NP1 &;_NULL lee_NN1 ,_, 2006_MC ;_; Wolfinbarger_NP1 &;_NULL Gilly_NP1 ,_, 2001_MC )_) ._. 
</s>
<s>
The_AT purpose_NN1 of_IO this_DD1 study_NN1 is_VBZ to_TO examine_VVI the_AT influence_NN1 of_IO different_JJ motives_NN2 affecting_VVG online_RR shopping_VVG from_II utilitarian_JJ and_CC hedonic_JJ points_NN2 of_IO view_NN1 and_CC extend_VV0 the_AT current_JJ knowledge_NN1 of_IO online_JJ shopping_NN1 behavior_NN1 ._. 
</s>
<s>
The_AT paper_NN1 is_VBZ organized_VVN as_CSA follows_VVZ ._. 
</s>
<s>
Following_VVG this_DD1 introduction_NN1 ,_, section_NN1 2_MC presents_VVZ an_AT1 overview_NN1 of_IO the_AT internet_NN1 as_II a_AT1 contemporary_JJ buying_NN1 environment_NN1 ._. 
</s>
<s>
Second_MD ,_, drawing_VVG on_II relevant_JJ literature_NN1 ,_, a_AT1 number_NN1 of_IO motives_NN2 for_IF shopping_VVG online_RR are_VBR presented_VVN and_CC formed_VVN into_II a_AT1 conceptual_JJ model_NN1 ._. 
</s>
<s>
Next_MD ,_, the_AT findings_NN2 of_IO the_AT study_NN1 are_VBR presented_VVN ._. 
</s>
<s>
Finally_RR ,_, implications_NN2 and_CC directions_NN2 for_IF future_JJ research_NN1 are_VBR discussed_VVN ._. 
</s>
<s>
LITERATURE_NN1 REVIEW_NN1 Background_NN1 on_II shopping_NN1 motives_NN2 Beginning_VVG with_IW Taubers_NP1 (_( 1972_MC )_) seminal_JJ work_NN1 onwhy_NN1 do_VD0 people_NN shop_NN1 ,_, numerous_JJ studies_NN2 have_VH0 been_VBN conducted_VVN to_TO investigate_VVI consumers_NN2 underlying_VVG reasons_NN2 for_IF shopping_NN1 ,_, both_RR in_II traditional_JJ brick-and-mortar_JJ settings_NN2 (_( e.g._REX Babin_NP1 ,_, Darden_NP1 &;_NULL Griffin_NP1 1994_MC )_) as_II31 well_II32 as_II33 online_JJ (_( e.g._REX Childers_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2001_MC ;_; Menon_NP1 &;_NULL Kahn_NP1 2002_MC )_) ._. 
</s>
<s>
Shopping_NN1 motives_NN2 have_VH0 been_VBN defined_VVN as_II the_AT drivers_NN2 of_IO behavior_NN1 that_CST consumers_NN2 to_II the_AT marketplace_NN1 to_TO satisfy_VVI their_APPGE internal_JJ needs_NN2 (_( Jin_NP1 &;_NULL Kim_NP1 2003:399_MC )_) ._. 
</s>
<s>
Although_CS research_NN1 has_VHZ identified_VVN a_AT1 plethora_NN1 of_IO shopping_NN1 motives_NN2 ,_, most_DAT researchers_NN2 tend_VV0 to_TO dichotomize_VVI them_PPHO2 into_II utilitarian_JJ and_CC hedonic_JJ values_NN2 and_CC motives_NN2 (_( Batra_NP1 &;_NULL Ahtola_NP1 1991_MC ;_; Babin_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
1994_MC ;_; Childers_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2001_MC )_) ._. 
</s>
<s>
Utilitarian_JJ values_NN2 reflect_VV0 shopping_VVG with_IW a_AT1 work_NN1 mentality_NN1 (_( Babin_NP1 ,_, Darden_NP1 &;_NULL Griffin_NP1 1994_MC )_) where_RRQ the_AT shopping_NN1 activity_NN1 is_VBZ understood_VVN as_II a_AT1 means_NN to_TO accomplish_VVI some_DD predefined_JJ end_NN1 (_( Holbrook_NP1 &;_NULL Hirschman_NP1 1982_MC )_) ._. 
</s>
<s>
Childers_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2001:513_MC )_) add_VV0 that_CST in_II the_AT utilitarian_JJ view_NN1 ,_, consumers_NN2 are_VBR concerned_JJ with_IW purchasing_VVG products_NN2 in_II an_AT1 efficient_JJ and_CC timely_JJ manner_NN1 to_TO achieve_VVI their_APPGE goals_NN2 with_IW a_AT1 minimum_NN1 of_IO irritation_NN1 ._. 
</s>
<s>
In_II contrast_NN1 to_II utilitarian_JJ value_NN1 ,_, hedonic_JJ value_NN1 is_VBZ more_RGR subjective_JJ ,_, in_II which_DDQ consumers_NN2 seek_VV0 fantasies_NN2 ,_, fun_JJ and_CC sensory_JJ stimulation_NN1 rather_II21 than_II22 a_AT1 means_NN to_TO obtain_VVI a_AT1 desired_JJ product_NN1 or_CC service_NN1 (_( Holbrook_NP1 &;_NULL Hirschman_NP1 1982_MC )_) ._. 
</s>
<s>
Similarly_RR ,_, Babin_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 1994_MC )_) define_VV0 hedonic_JJ as_CSA being_VBG more_RGR subjective_JJ and_CC personal_JJ than_CSN its_APPGE utilitarian_JJ counterpart_NN1 ,_, and_CC resulting_VVG more_RRR from_II fun_NN1 and_CC playfulness_NN1 than_CSN from_II task_NN1 completion_NN1 (_( p.646_FO )_) ._. 
</s>
<s>
Childers_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2001_MC )_) argue_VV0 that_CST both_DB2 value_NN1 dimensions_NN2 play_VV0 an_AT1 important_JJ role_NN1 in_II online_JJ shopping_NN1 ._. 
</s>
<s>
Scholars_NN2 have_VH0 also_RR noted_VVN that_CST utilitarian_JJ and_CC hedonic_JJ values_NN2 are_VBR often_RR intertwined_VVN with_IW one_PPX121 another_PPX122 (_( Babin_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
1994_MC )_) and_CC that_CST consumers_NN2 may_VM seek_VVI both_RR simultaneously_RR when_CS shopping_VVG online_JJ (_( Wolfinbarger_NP1 &;_NULL Gilly_NP1 2001_MC )_) ._. 
</s>
<s>
Utilitarian_JJ shopping_NN1 motives_NN2 online_RR Most_RGT prior_JJ research_NN1 on_II online_JJ shopping_NN1 has_VHZ assumed_VVN that_CST the_AT primary_JJ motives_NN2 underlying_VVG online_JJ shopping_NN1 are_VBR utilitarian_JJ motives_NN2 such_II21 as_II22 convenience_NN1 (_( Childers_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2001_MC )_) ,_, product_NN1 selection_NN1 (_( Wolfinbarger_NP1 &;_NULL Gilly_NP1 2001_MC )_) and_CC accessibility_NN1 (_( Alba_FW ,_, Lynch_NP1 ,_, Weitz_NP1 ,_, Janiszewski_NP1 ,_, Lutz_NP1 &;_NULL Wood_NP1 1997_MC )_) ._. 
</s>
<s>
For_REX21 instance_REX22 ,_, convenience_NN1 is_VBZ manifested_VVN in_II the_AT fact_NN1 that_CST online_JJ stores_NN2 offer_VV0 the_AT consumer_NN1 limited_VVN 24_MC hour_NNT1 access_NN1 and_CC the_AT opportunity_NN1 to_TO shop_VVI at_II multiple_JJ locations_NN2 at_II the_AT same_DA time_NNT1 (_( Wolfinbarger_NP1 &;_NULL Gilly_NP1 2001_MC )_) ._. 
</s>
<s>
Furthermore_RR ,_, the_AT internet_NN1 offers_VVZ an_AT1 infrastructure_NN1 that_CST enables_VVZ the_AT consumer_NN1 to_TO locate_VVI merchants_NN2 and_CC items_NN2 much_RR more_RGR efficiently_RR than_CSN in_II traditional_JJ retail_JJ outlets_NN2 (_( Alba_FW ,_, Lynch_NP1 ,_, Weitz_NP1 ,_, Janiszewski_NP1 ,_, Lutz_NP1 &;_NULL Wood_NP1 1997_MC )_) ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, Wolfinbarger_NP1 &;_NULL Gilly_NP1 (_( 2001_MC )_) found_VVD that_DD1 lack_NN1 of_IO sociality_NN1 and_CC social_JJ interaction_NN1 was_VBDZ a_AT1 dominant_JJ motive_NN1 among_II utilitarian_JJ shoppers_NN2 ._. 
</s>
<s>
The_AT self-service_JJ nature_NN1 of_IO online_JJ stores_NN2 allows_VVZ consumers_NN2 to_TO avoid_VVI crowding_VVG and_CC intrusive_JJ sales_NN clerks_NN2 ,_, thus_RR enabling_VVG more_DAR freedom_NN1 and_CC control_VV0 over_RP the_AT shopping_NN1 process_NN1 ._. 
</s>
<s>
(_( Wolfinbarger_NP1 &;_NULL Gilly_NP1 2001_MC )_) Hedonic_JJ shopping_NN1 motives_NN2 online_RR Despite_II the_AT fact_NN1 that_CST online_JJ shoppers_NN2 are_VBR primarily_RR driven_VVN by_II utilitarian_JJ needs_NN2 (_( Childers_NP1 ,_, et_RA21 al_RA22 ._. 
</s>
<s>
2001_MC )_) ,_, there_EX is_VBZ also_RR ample_JJ evidence_NN1 that_CST suggest_VV0 that_CST hedonic_JJ values_NN2 are_VBR prevalent_JJ motives_NN2 in_II online_JJ shopping_NN1 (_( Bridges_NP1 &;_NULL Florsheim_NP1 2007_MC )_) ._. 
</s>
<s>
For_REX21 instance_REX22 ,_, for_IF some_DD consumers_NN2 ,_, online_JJ shopping_NN1 is_VBZ perceived_VVN primarily_RR as_II a_AT1 leisure-time_JJ activity_NN1 ,_, and_CC for_IF them_PPHO2 the_AT act_NN1 of_IO shopping_NN1 and_CC browsing_VVG around_RP may_VM be_VBI a_AT1 source_NN1 of_IO pleasure_NN1 in_II itself_PPX1 (_( Babin_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
1994_MC ;_; Menon_NP1 &;_NULL Kahn_NP1 2002_MC )_) ._. 
</s>
<s>
In_II this_DD1 view_NN1 ,_, an_AT1 online_JJ shopping_NN1 experience_NN1 is_VBZ not_XX only_RR related_VVN to_II a_AT1 specific_JJ task_NN1 ,_, but_CCB also_RR associated_VVN with_IW seeking_VVG pleasure_NN1 ,_, arousal_NN1 and_CC enjoyment_NN1 (_( Mathwick_NP1 ,_, Rigdon_NP1 &;_NULL Malhotra_NP1 2001_MC ;_; Overby_NP1 &;_NULL Lee_NP1 2006_MC )_) ._. 
</s>
<s>
METHODOLOGY_NN1 FINDINGS_NN2 The_AT findings_NN2 in_II this_DD1 section_NN1 are_VBR presented_VVN according_II21 to_II22 themes_NN2 using_VVG the_AT informants_NN2 own_DA statements_NN2 ._. 
</s>
<s>
The_AT statements_NN2 are_VBR followed_VVN by_II a_AT1 reference_NN1 to_II the_AT respondents_NN2 gender_NN1 (_( F=female_FO ,_, M=male_FO )_) and_CC age_NN1 ._. 
</s>
<s>
DISCUSSION_NN1 
</s>
