<s>
Stock_NN1 Valuation_NN1 :_: Outokumpu_NP1 Oyj_NP1 1_MC1 Introduction_NN1 The_AT theme_NN1 of_IO this_DD1 paper_NN1 is_VBZ company_NN1 valuation_NN1 ._. 
</s>
<s>
As_II the_AT term_NN1 states_NN2 ,_, the_AT aim_NN1 of_IO a_AT1 company_NN1 valuation_NN1 is_VBZ to_TO estimate_VVI the_AT value_NN1 of_IO a_AT1 company_NN1 or_CC business_NN1 ._. 
</s>
<s>
A_AT1 valuation_NN1 can_VM support_VVI financially_RR sound_JJ decision-making_NN1 ._. 
</s>
<s>
Valuation_NN1 is_VBZ involved_JJ in_II nearly_RR every_AT1 business_NN1 decision_NN1 either_RR explicitly_RR or_CC implicitly_RR (_( Palepu_NP1 ,_, Healy_NP1 ,_, Bernard_NP1 ,_, &;_NULL Peek_NP1 ,_, 2007:293_MC )_) ._. 
</s>
<s>
Valuation_NN1 is_VBZ of_IO significance_NN1 in_II acquisitions_NN2 ,_, investments_NN2 decisions_NN2 ,_, restructurings_NN2 ,_, taxation_NN1 ,_, and_CC in_II managing_VVG the_AT value_NN1 of_IO companies_NN2 and_CC in_II estimating_VVG collaterals_NN2 (_( Koller_NP1 ,_, Goedhart_NP1 ,_, &;_NULL Wessels_NP1 ,_, 2005:4_MC ;_; Leppiniemi_NP1 &;_NULL Leppiniemi_NP1 ,_, 2006:310_MC )_) ._. 
</s>
<s>
This_DD1 paper_NN1 will_VM adopt_VVI the_AT equity_NN1 investors_NN2 point_NN1 of_IO view_NN1 ._. 
</s>
<s>
In_II an_AT1 equity_NN1 security_NN1 analysis_NN1 a_AT1 firm_NN1 and_CC its_APPGE prospects_NN2 are_VBR evaluated_VVN from_II the_AT perspective_NN1 of_IO a_AT1 current_JJ or_CC potential_JJ stockholder_NN1 (_( Palepu_NP1 et_RA21 al._RA22 ,_, 2007:373_MC )_) ._. 
</s>
<s>
Security_NN1 analysis_NN1 is_VBZ only_RR one_MC1 step_NN1 in_II an_AT1 investment_NN1 process_NN1 (_( Palepu_NP1 et_RA21 al._RA22 ,_, 2007:373_MC )_) ._. 
</s>
<s>
The_AT investment_NN1 process_NN1 involves_VVZ combining_VVG securities_NN2 into_II portfolios_NN2 in_II31 accordance_II32 with_II33 investment_NN1 objectives_NN2 ._. 
</s>
<s>
A_AT1 typical_JJ goal_NN1 for_IF equity_NN1 security_NN1 analysis_NN1 is_VBZ to_TO find_VVI mispriced_JJ securities_NN2 that_CST would_VM more_RRR than_CSN compensate_VV0 the_AT investor_NN1 for_IF risk_NN1 (_( Palepu_NP1 et_RA21 al._RA22 ,_, 2007:373_MC )_) ._. 
</s>
<s>
Thus_RR ,_, the_AT goal_NN1 is_VBZ to_TO find_VVI shares_NN2 whose_DDQGE value_NN1 is_VBZ greater_JJR than_CSN the_AT price_NN1 ,_, or_CC ,_, whose_DDQGE net_JJ present_JJ value_NN1 (_( NPV_NP1 )_) is_VBZ greater_JJR than_CSN zero_MC ._. 
</s>
<s>
Finance_VV0 theory_NN1 holds_VVZ that_CST the_AT value_NN1 of_IO any_DD financial_JJ claim_NN1 is_VBZ simply_RR the_AT present_JJ value_NN1 of_IO the_AT cash_NN1 payoffs_VVZ that_CST its_APPGE claimholders_NN2 receive_VV0 (_( Palepu_NP1 et_RA21 al._RA22 ,_, 2007:294_MC )_) ._. 
</s>
<s>
Congruent_JJ with_IW that_DD1 ,_, the_AT value_NN1 of_IO a_AT1 stock_NN1 is_VBZ the_AT expected_JJ cash_NN1 flow_NN1 that_CST an_AT1 investor_NN1 will_VM receive_VVI from_II owing_VVG the_AT stock_NN1 discounted_VVN with_IW the_AT appropriate_JJ cost_NN1 of_IO capital_NN1 (_( Berk_NN1 &;_NULL DeMarzo_NN1 ,_, 2007:245_MC )_) ._. 
</s>
<s>
The_AT price_NN1 of_IO a_AT1 stock_NN1 is_VBZ the_AT market_NN1 price_NN1 at_II which_DDQ investors_NN2 buy_VV0 or_CC sell_VV0 a_AT1 share_NN1 at_II a_AT1 given_JJ time_NNT1 ._. 
</s>
<s>
The_AT efficient_JJ market_NN1 hypothesis_NN1 suggests_VVZ that_CST shares_NN2 are_VBR fairly_RR priced_VVN (_( Berk_NN1 &;_NULL DeMarzo_NN1 ,_, 2007:268_MC )_) ._. 
</s>
<s>
If_CS the_AT hypothesis_NN1 held_VVD ,_, it_PPH1 would_VM be_VBI impossible_JJ to_TO find_VVI mispriced_JJ securities_NN2 given_VVN public_JJ information_NN1 only_RR ._. 
</s>
<s>
In_II practice_NN1 ,_, mispricing_NN1 does_VDZ occur_VVI which_DDQ generates_VVZ exploiting_VVG opportunities_NN2 (_( Koller_NP1 et_RA21 al._RA22 ,_, 2005:99_MC )_) and_CC is_VBZ an_AT1 incentive_NN1 to_II equity_NN1 security_NN1 analysis_NN1 ._. 
</s>
<s>
But_CCB mostly_RR ,_, stock_NN1 markets_NN2 reflect_VV0 economic_JJ fundamentals_NN2 (_( Koller_NP1 et_RA21 al._RA22 ,_, 2005:98_MC )_) ,_, and_CC ,_, the_AT market_NN1 price_NN1 of_IO a_AT1 publicly_RR traded_VVN share_NN1 provides_VVZ accurate_JJ information_NN1 regarding_II the_AT true_JJ value_NN1 of_IO the_AT share_NN1 (_( Berk_NN1 &;_NULL DeMarzo_NN1 ,_, 2007:267_MC )_) ._. 
</s>
<s>
Different_JJ valuation_NN1 techniques_NN2 have_VH0 been_VBN presented_VVN (_( Berk_NN1 &;_NULL DeMarzo_NN1 ,_, 2007:245_MC ;_; Koller_NP1 et_RA21 al._RA22 ,_, 2005_MC ;_; Palepu_NP1 et_RA21 al._RA22 ,_, 2007_MC )_) ._. 
</s>
<s>
However_RR ,_, no_AT single_JJ valuation_NN1 technique_NN1 provides_VVZ the_AT true_JJ share_NN1 value_NN1 (_( Berk_NN1 &;_NULL DeMarzo_NN1 ,_, 2007:265_MC )_) ._. 
</s>
<s>
That_DD1 is_VBZ due_II21 to_II22 the_AT impossibility_NN1 of_IO forecasting_VVG the_AT future_NN1 and_CC the_AT uncertain_JJ assumptions_NN2 made_VVN in_II the_AT valuation_NN1 techniques_NN2 (_( Berk_NN1 &;_NULL DeMarzo_NN1 ,_, 2007:265_MC )_) ._. 
</s>
<s>
The_AT favourite_JJ method_NN1 of_IO many_DA2 practitioners_NN2 and_CC academics_NN2 is_VBZ the_AT enterprise_NN1 discounted_VVN cash_NN1 flow_NN1 method_NN1 (_( Koller_NP1 et_RA21 al._RA22 ,_, 2005:103_MC )_) ._. 
</s>
<s>
In_II practice_NN1 ,_, the_AT majority_NN1 use_VV0 a_AT1 combination_NN1 of_IO approaches_NN2 (_( Berk_NN1 &;_NULL DeMarzo_NN1 ,_, 2007:265_MC )_) ._. 
</s>
<s>
The_AT approach_NN1 of_IO this_DD1 paper_NN1 is_VBZ to_TO describe_VVI how_RRQ a_AT1 stock_NN1 valuation_NN1 with_IW enterprise_NN1 discounted_VVD cash_NN1 flow_NN1 method_NN1 is_VBZ conducted_VVN and_CC to_TO evaluate_VVI whether_CSW Outokumpu_NP1 Oyjs_NP1 stock_NN1 is_VBZ mispriced_VVN ._. 
</s>
<s>
The_AT valuation_NN1 was_VBDZ originally_RR conducted_VVN to_II a_AT1 course_NN1 of_IO company_NN1 valuation_NN1 ._. 
</s>
<s>
Accordingly_RR ,_, a_AT1 majority_NN1 of_IO the_AT choices_NN2 arise_VV0 from_II the_AT company_NN1 valuation_NN1 assignment_NN1 or_CC from_II the_AT course_NN1 literature_NN1 in_II the_AT company_NN1 valuation_NN1 course_NN1 (_( Koller_NP1 et_RA21 al._RA22 ,_, 2005_MC )_) ._. 
</s>
<s>
The_AT valuation_NN1 is_VBZ based_VVN on_II public_JJ information_NN1 ._. 
</s>
<s>
The_AT structure_NN1 of_IO this_DD1 paper_NN1 is_VBZ as_CSA follows_VVZ :_: After_II introducing_VVG the_AT company_NN1 and_CC the_AT valuation_NN1 process_NN1 ,_, financial_JJ statement_NN1 accounts_NN2 are_VBR reorganized_VVN ._. 
</s>
<s>
Historical_JJ free_JJ cash_NN1 flow_NN1 and_CC key_JJ ratios_NN2 are_VBR calculated_VVN ._. 
</s>
<s>
Thereafter_RT ,_, Outukumpus_NP1 future_JJ performance_NN1 is_VBZ forecasted_VVN and_CC the_AT weighted_JJ average_JJ cost_NN1 of_IO capital_NN1 is_VBZ estimated_VVN ._. 
</s>
<s>
Finally_RR ,_, the_AT value_NN1 of_IO the_AT share_NN1 is_VBZ calculated_VVN ,_, sensitivity_NN1 analysis_NN1 is_VBZ performed_VVN and_CC the_AT results_NN2 are_VBR discussed_VVN ._. 
</s>
<s>
2_MC Introduction_NN1 of_IO Outokumpu_NP1 Oyj_NP1 Outokumpu_NP1 is_VBZ one_MC1 of_IO the_AT largest_JJT stainless_JJ steel_NN1 producers_NN2 in_II the_AT world_NN1 ._. 
</s>
<s>
Over_RG 90_MC per_NNU21 cent_NNU22 of_IO its_APPGE turnover_NN1 comes_VVZ from_II stainless_JJ steel_NN1 products_NN2 ._. 
</s>
<s>
Outokumpus_NN1 turnover_NN1 was_VBDZ 2_MC 611_MC million_NNO euro_NN1 in_II 2009_MC ,_, market_VV0 capitalization_NN1 is_VBZ about_RG 2_MC 673_MC million_NNO euro_NN1 and_CC Outokumpu_NP1 employs_VVZ approximately_RR 7_MC 600_MC persons_NN2 in_II more_DAR than_CSN 30_MC countries_NN2 ._. 
</s>
<s>
Return_VV0 on_II equity_NN1 was_VBDZ -13_MC per_NNU21 cent_NNU22 in_II 2009_MC ._. 
</s>
<s>
Outokumpu_NN1 is_VBZ listed_VVN on_II the_AT NASDAQ_NP1 OMX_NP1 Helsinki_NP1 ._. 
</s>
<s>
(_( Outokumpu_NN1 ,_, 2010_MC )_) Outokumpu_NN1 is_VBZ a_AT1 cyclical_JJ company_NN1 due_II21 to_II22 its_APPGE industry_NN1 (_( Koller_NP1 et_RA21 al._RA22 ,_, 2005:671_MC )_) ._. 
</s>
<s>
It_PPH1 signifies_VVZ that_CST Outokumpus_NP1 earnings_NN2 demonstrate_VV0 a_AT1 recurrent_JJ pattern_NN1 of_IO significant_JJ increases_NN2 and_CC decreases_VVZ (_( Koller_NP1 et_RA21 al._RA22 ,_, 2005:671_MC )_) ._. 
</s>
<s>
As_CSA stock_NN1 markets_NN2 have_VH0 difficulties_NN2 in_II valuing_VVG cyclical_JJ companies_NN2 (_( Koller_NP1 et_RA21 al._RA22 ,_, 2005:678_MC )_) ,_, Outokumpu_NP1 is_VBZ an_AT1 interesting_JJ object_NN1 of_IO valuation_NN1 ._. 
</s>
<s>
1_MC1 The_AT Process_NN1 of_IO Stock_NP1 Valuation_NN1 With_IW the_AT Enterprise_NN1 Discounted_VVD Cash_NN1 Flow_NN1 Method_NN1 Valuation_NN1 process_NN1 descriptions_NN2 provide_VV0 information_NN1 what_DDQ steps_NN2 are_VBR taken_VVN in_II a_AT1 business_NN1 valuation_NN1 with_IW the_AT enterprise_NN1 discounted_VVD cash_NN1 flow_NN1 method_NN1 ._. 
</s>
<s>
The_AT process_NN1 of_IO financial_JJ statement_NN1 based_VVN valuation_NN1 is_VBZ as_CSA follows_VVZ (_( Palepu_NP1 et_RA21 al._RA22 ,_, 2007:v,11_FO )_) :_: 1_MC1 ._. 
</s>
<s>
Business_NN1 strategy_NN1 analysis_NN1 ._. 
</s>
<s>
This_DD1 involves_VVZ the_AT analysis_NN1 of_IO a_AT1 firms_NN2 industry_NN1 and_CC its_APPGE strategies_NN2 in_II creating_VVG a_AT1 sustainable_JJ competitive_JJ advantage_NN1 ,_, the_AT identification_NN1 of_IO key_JJ profit_NN1 drivers_NN2 and_CC business_NN1 risks_NN2 and_CC the_AT assessment_NN1 of_IO a_AT1 companys_NN2 profit_VV0 potential_NN1 ._. 
</s>
<s>
2_MC ._. 
</s>
<s>
Accounting_VVG analysis_NN1 ._. 
</s>
<s>
The_AT purpose_NN1 is_VBZ to_TO enhance_VVI the_AT reliability_NN1 of_IO the_AT financial_JJ statements_NN2 and_CC the_AT conclusions_NN2 drawn_VVN ._. 
</s>
<s>
The_AT amount_NN1 of_IO distortion_NN1 in_II the_AT financial_JJ statements_NN2 is_VBZ evaluated_VVN and_CC unbiased_JJ financial_JJ statements_NN2 reflecting_VVG the_AT underlying_JJ business_NN1 are_VBR created_VVN ._. 
</s>
<s>
3_MC ._. 
</s>
<s>
Financial_JJ analysis_NN1 ._. 
</s>
<s>
The_AT purpose_NN1 is_VBZ to_TO analyse_VVI a_AT1 firms_NN2 current_JJ and_CC past_JJ performance_NN1 and_CC its_APPGE sustainability_NN1 ._. 
</s>
<s>
The_AT tools_NN2 are_VBR ratio_NN1 analysis_NN1 and_CC cash_NN1 flow_NN1 analysis_NN1 ._. 
</s>
<s>
4_MC ._. 
</s>
<s>
Prospective_JJ analysis_NN1 ._. 
</s>
<s>
The_AT purpose_NN1 is_VBZ to_TO forecast_VVI a_AT1 firms_NN2 future_JJ cash_NN1 flow_NN1 performance_NN1 ,_, estimate_VV0 a_AT1 terminal_JJ value_NN1 ,_, compute_VV0 a_AT1 discount_NN1 rate_NN1 and_CC perform_VV0 the_AT calculations_NN2 ._. 
</s>
<s>
The_AT previous_JJ steps_NN2 provide_VV0 a_AT1 foundation_NN1 for_IF forecasting_VVG a_AT1 firms_NN2 future_JJ performance_NN1 ._. 
</s>
<s>
The_AT calculation_NN1 process_NN1 using_VVG enterprise_NN1 discounted_VVD cash_NN1 flow_NN1 method_NN1 is_VBZ as_CSA follows_VVZ (_( Koller_NP1 et_RA21 al._RA22 ,_, 2005:106_MC )_) :_: 1_MC1 ._. 
</s>
<s>
Valuation_NN1 of_IO companys_NN2 operations_NN2 ._. 
</s>
<s>
Free_JJ cash_NN1 flow_NN1 from_II operations_NN2 is_VBZ discounted_VVN at_II the_AT cost_NN1 of_IO capital_NN1 ,_, or_CC weighted_JJ average_JJ cost_NN1 of_IO capital_NN1 (_( WACC_NP1 )_) ._. 
</s>
<s>
2_MC ._. 
</s>
<s>
Determination_NN1 of_IO enterprise_NN1 value_NN1 ._. 
</s>
<s>
Non-operating_JJ asset_NN1 are_VBR valued_VVN ._. 
</s>
<s>
Enterprise_NN1 value_NN1 is_VBZ equal_JJ to_II the_AT value_NN1 of_IO operations_NN2 and_CC non-operating_JJ assets_NN2 ._. 
</s>
<s>
3_MC ._. 
</s>
<s>
Identification_NN1 and_CC valuation_NN1 of_IO all_DB non-equity_JJ financial_JJ claims_NN2 ._. 
</s>
<s>
4_MC ._. 
</s>
<s>
Determination_NN1 of_IO equity_NN1 value_NN1 and_CC the_AT value_NN1 of_IO the_AT share_NN1 ._. 
</s>
<s>
Non-equity_JJ financial_JJ claims_NN2 are_VBR subtracted_VVN from_II enterprise_NN1 value_NN1 ._. 
</s>
<s>
Equity_NN1 value_NN1 is_VBZ divided_VVN by_II the_AT number_NN1 of_IO shares_NN2 outstanding_JJ ._. 
</s>
<s>
Not_XX every_AT1 step_NN1 in_II the_AT valuation_NN1 process_NN1 is_VBZ reported_VVN in_II detail_NN1 even_CS21 though_CS22 all_DB the_AT steps_NN2 have_VH0 received_VVN attention_NN1 ._. 
</s>
<s>
A_AT1 very_RG detailed_JJ and_CC thorough_JJ execution_NN1 is_VBZ beyond_II the_AT scope_NN1 of_IO this_DD1 paper_NN1 ._. 
</s>
<s>
Accordingly_RR ,_, the_AT emphasis_NN1 is_VBZ on_II the_AT most_RGT relevant_JJ matters_NN2 ._. 
</s>
<s>
2_MC Reorganization_NN1 of_IO Financial_JJ Statement_NN1 Accounts_NN2 Income_NN1 statement_NN1 and_CC balance_NN1 sheet_NN1 accounts_NN2 and_CC items_NN2 are_VBR reorganized_VVN (_( Koller_NP1 et_RA21 al._RA22 ,_, 2005:162_MC )_) ._. 
</s>
<s>
The_AT classification_NN1 is_VBZ exploited_VVN in_II calculating_VVG free_JJ cash_NN1 flow_NN1 and_CC WACC_NP1 ,_, and_CC in_II valuing_VVG operating_NN1 assets_NN2 ,_, non-operating_JJ assets_NN2 and_CC non-equity_JJ financial_JJ claims_NN2 3_MC Historical_JJ Free_JJ Cash_NN1 Flow_NN1 and_CC Key_JJ Ratios_NN2 Historical_JJ free_JJ cash_NN1 flow_NN1 and_CC key_JJ ratios_NN2 are_VBR calculated_VVN to_TO get_VVI an_AT1 idea_NN1 of_IO Outokumpus_NP1 historical_JJ performance_NN1 ._. 
</s>
<s>
The_AT key_JJ ratios_NN2 are_VBR used_VVN in_II forecasting_VVG Outokumpus_NP1 future_JJ performance_NN1 4_MC Forecasting_NN1 Performance_NN1 Expected_VVD future_JJ cash_NN1 flow_NN1 is_VBZ prognosticated_VVN with_IW forecasted_JJ key_JJ ratios_NN2 ._. 
</s>
<s>
The_AT forecast_NN1 is_VBZ founded_VVN on_II business_NN1 strategy_NN1 analysis_NN1 ,_, Outokumpus_NP1 historical_JJ performance_NN1 and_CC future_JJ prospects_NN2 5_MC Estimating_VVG the_AT Weighted_JJ Average_JJ Cost_NN1 of_IO Capital_NN1 With_IW the_AT enterprise_NN1 discounted_VVD cash_NN1 flow_NN1 method_NN1 ,_, free_JJ cash_NN1 flow_NN1 is_VBZ discounted_VVN by_II the_AT WACC_NP1 ._. 
</s>
<s>
WACC_NP1 represents_VVZ the_AT opportunity_NN1 cost_NN1 that_CST investors_NN2 face_VV0 for_IF investing_VVG their_APPGE funds_NN2 in_II one_MC1 particular_JJ business_NN1 instead_II21 of_II22 others_NN2 with_IW similar_JJ risk_NN1 (_( Koller_NP1 et_RA21 al._RA22 ,_, 2005:297_MC )_) ._. 
</s>
<s>
It_PPH1 includes_VVZ the_AT required_JJ return_NN1 of_IO all_DB sources_NN2 of_IO capital_NN1 weighted_VVN by_II their_APPGE target_NN1 market_NN1 based_VVN weights_NN2 ._. 
</s>
<s>
WACC_NP1 is_VBZ calculated_VVN after_II corporate_JJ taxes_NN2 ._. 
</s>
<s>
Required_JJ return_NN1 or_CC the_AT cost_NN1 of_IO capital_NN1 is_VBZ the_AT expected_JJ return_NN1 of_IO an_AT1 investment_NN1 that_CST is_VBZ necessary_JJ to_TO compensate_VVI for_IF the_AT risk_NN1 of_IO undertaking_VVG the_AT investment_NN1 (_( Berk_NN1 &;_NULL DeMarzo_NN1 ,_, 2007:G-14_FO )_) ._. 
</s>
<s>
When_CS a_AT1 companys_NN2 capital_NN1 structure_NN1 is_VBZ composed_VVN of_IO common_JJ stock_NN1 and_CC debt_NN1 ,_, the_AT following_JJ formula_NN1 for_IF WACC_NP1 is_VBZ applicable_JJ :_: &lsqb;_( Formula_NN1 &rsqb;_) Capital_NN1 Asset_NN1 Pricing_VVG Model_NN1 (_( CAPM_NP1 )_) is_VBZ used_VVN for_IF estimating_VVG the_AT required_JJ return_NN1 for_IF equity_NN1 ._. 
</s>
<s>
In_II practise_NN1 ,_, CAPM_NP1 is_VBZ the_AT most_RGT important_JJ method_NN1 for_IF estimating_VVG the_AT cost_NN1 of_IO capital_NN1 (_( Berk_NN1 &;_NULL DeMarzo_NN1 ,_, 2007:312_MC )_) ._. 
</s>
<s>
According_II21 to_II22 the_AT CAPM_NP1 the_AT required_JJ rate_NN1 of_IO return_NN1 for_IF an_AT1 investment_NN1 is_VBZ (_( Berk_NN1 &;_NULL DeMarzo_NN1 ,_, 2007:353_MC )_) :_: &lsqb;_( Formula_NN1 &rsqb;_) The_AT cost_NN1 of_IO capital_NN1 take_VV0 into_II account_NN1 the_AT time_NNT1 value_NN1 of_IO money_NN1 and_CC the_AT systematic_JJ risk_NN1 of_IO a_AT1 security_NN1 as_CSA is_VBZ seen_VVN in_II the_AT CAPM_NP1 (_( Berk_NN1 &;_NULL DeMarzo_NN1 ,_, 2007:310_MC )_) ._. 
</s>
<s>
The_AT systematic_JJ risk_NN1 is_VBZ the_AT risk_NN1 that_CST determines_VVZ the_AT cost_NN1 of_IO capital_NN1 ;_; the_AT firm_JJ specific_JJ risk_NN1 is_VBZ diversifiable_JJ ._. 
</s>
<s>
The_AT systematic_JJ risk_NN1 is_VBZ measured_VVN by_II beta_NN1 (_( Berk_NN1 &;_NULL DeMarzo_NN1 ,_, 2007:380_MC )_) ._. 
</s>
<s>
The_AT beta_NN1 measures_VVZ the_AT sensitivity_NN1 of_IO a_AT1 securitys_NN2 return_VV0 to_TO return_VVI of_IO the_AT overall_JJ market_NN1 ._. 
</s>
<s>
Beta_NN1 of_IO investment_NN1 i_ZZ1 with_IW market_NN1 portfolio_NN1 is_VBZ :_: &lsqb;_( Formula_NN1 &rsqb;_) More_RGR Required_JJ rate_NN1 for_IF debt_NN1 6_MC Results_NN2 6.1_MC The_AT Value_NN1 of_IO the_AT Share_NN1 Finally_RR ,_, the_AT value_NN1 of_IO the_AT share_NN1 is_VBZ calculated_VVN 6.2_MC Sensitivity_NN1 Analysis_NN1 Sensitivity_NN1 analysis_NN1 is_VBZ performed_VVN in_BCL21 order_BCL22 to_TO consider_VVI the_AT uncertainty_NN1 in_II the_AT valuation_NN1 7_MC Discussion_NN1 The_AT process_NN1 and_CC the_AT results_NN2 are_VBR discussed_VVN 
</s>
