<s>
Exceptional_JJ Circumstances_NN2 in_II Compulsory_JJ Licensing_NN1 of_IO IPR_NN1 1_MC1 ._. 
</s>
<s>
Introduction_NN1 Intellectual_NN1 property_NN1 rights_NN2 are_VBR valuable_JJ assets_NN2 to_II companies_NN2 ._. 
</s>
<s>
Particularly_RR licensing_VVG intellectual_JJ property_NN1 rights_NN2 is_VBZ an_AT1 efficient_JJ way_NN1 for_IF companies_NN2 to_TO pursue_VVI profits_NN2 ._. 
</s>
<s>
At_II the_AT same_DA time_NNT1 business_NN1 relations_NN2 in_RR21 general_RR22 are_VBR becoming_VVG more_RGR complex_JJ and_CC competition_NN1 between_II companies_NN2 is_VBZ harsh_JJ ._. 
</s>
<s>
Consequently_RR ,_, there_EX are_VBR multiple_JJ competing_JJ interests_NN2 to_TO be_VBI fulfilled_VVN in_RP today_RT 's_GE market_NN1 ._. 
</s>
<s>
In_II the_AT continuously_RR developing_JJ market_NN1 system_NN1 intellectual_NN1 property_NN1 regulation_NN1 and_CC regulation_NN1 concerning_II competition_NN1 tend_VV0 to_TO collide_VVI ._. 
</s>
<s>
Thus_RR ,_, the_AT legislator_NN1 as_II31 well_II32 as_II33 the_AT authorities_NN2 applying_VVG the_AT law_NN1 should_VM be_VBI able_JK to_TO do_VDI a_AT1 justifiable_JJ evaluation_NN1 between_II the_AT interests_NN2 of_IO competition_NN1 law_NN1 rules_NN2 and_CC the_AT rules_NN2 concerning_II intellectual_JJ property_NN1 rights_NN2 and_CC thus_RR design_VV0 the_AT best_JJT possible_JJ decision_NN1 in_II every_AT1 case_NN1 ._. 
</s>
<s>
This_DD1 paper_NN1 examines_VVZ the_AT possibilities_NN2 of_IO a_AT1 company_NN1 that_CST is_VBZ in_II a_AT1 dominant_JJ market_NN1 position_NN1 ,_, according_II21 to_II22 the_AT EU_NP1 competition_NN1 law_NN1 rules_NN2 ,_, to_TO refuse_VVI to_TO give_VVI a_AT1 competing_JJ company_NN1 a_AT1 right_NN1 to_TO use_VVI its_APPGE intellectual_JJ property_NN1 right_NN1 ._. 
</s>
<s>
Moreover_RR ,_, this_DD1 paper_NN1 studies_NN2 the_AT situations_NN2 under_II which_DDQ an_AT1 intellectual_JJ property_NN1 right_NN1 may_VM be_VBI subject_II21 to_II22 compulsory_JJ licensing_NN1 under_II Article_NN1 102_MC of_IO the_AT Treaty_NN1 on_II the_AT Functioning_NN1 of_IO the_AT European_JJ Union_NN1 (_( TFEU_NP1 )_) ._. 
</s>
<s>
The_AT compulsory_JJ licensing_NN1 is_VBZ considered_VVN possible_JJ under_II certain_JJ exceptional_JJ circumstances_NN2 defined_VVN in_II the_AT case_NN1 law_NN1 of_IO the_AT EU_NP1 ._. 
</s>
<s>
Consequently_RR ,_, this_DD1 paper_NN1 describes_VVZ some_DD parts_NN2 of_IO the_AT legal_JJ praxis_NN1 of_IO the_AT EU_NP1 ._. 
</s>
<s>
Furthermore_RR ,_, the_AT boundaries_NN2 of_IO the_AT exceptional_JJ circumstances_NN2 in_II which_DDQ a_AT1 compulsory_JJ license_NN1 will_VM be_VBI granted_VVN are_VBR still_RR being_VBG tested_VVN ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, most_DAT of_IO the_AT legal_JJ literature_NN1 analyzing_VVG the_AT concept_NN1 of_IO compulsory_JJ licensing_NN1 has_VHZ concentrated_VVN on_II evaluating_VVG either_RR some_DD parts_NN2 of_IO the_AT exceptional_JJ circumstances_NN2 or_CC evaluating_VVG the_AT situation_NN1 mainly_RR from_II a_AT1 legal_JJ viewpoint_NN1 (_( e.g._REX MacQueen_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2008_MC )_) ._. 
</s>
<s>
This_DD1 partial_JJ and_CC merely_RR legal_JJ approach_NN1 is_VBZ not_XX sufficient_JJ as_CSA there_EX are_VBR also_RR economic_JJ aspects_NN2 in_II the_AT cases_NN2 ._. 
</s>
<s>
For_REX21 example_REX22 Korah_NP1 (_( 2006_MC )_) demands_VVZ more_DAR discussion_NN1 on_II economic_JJ theory_NN1 in_II31 relation_II32 to_II33 the_AT decisions_NN2 of_IO EU_NP1 courts_NN2 ._. 
</s>
<s>
There_EX are_VBR only_RR a_AT1 few_DA2 studies_NN2 (_( e.g._REX Mylly_NP1 2009_MC ,_, Vezzoso_NP1 2006_MC ,_, Kanter_NP1 2006_MC )_) that_CST analyze_VV0 the_AT exceptional_JJ circumstances_NN2 from_II an_AT1 economic_JJ point_NN1 of_IO view_NN1 ._. 
</s>
<s>
Therefore_RR this_DD1 paper_NN1 contributes_VVZ to_II understanding_VVG the_AT economic_JJ aspect_NN1 of_IO the_AT evaluation_NN1 of_IO a_AT1 refusal_NN1 to_TO license_VVI ._. 
</s>
<s>
This_DD1 study_NN1 addresses_VVZ three_MC questions_NN2 ._. 
</s>
<s>
Firstly_RR ,_, as_CSA the_AT owner_NN1 of_IO intellectual_JJ property_NN1 right_NN1 has_VHZ an_AT1 exclusive_JJ right_NN1 to_TO exploit_VVI the_AT intellectual_JJ property_NN1 right_NN1 for_REX21 example_REX22 through_II licensing_NN1 ,_, the_AT owner_NN1 can_VM prevent_VVI competition_NN1 in_II31 relation_II32 to_II33 the_AT subject_NN1 matter_NN1 of_IO the_AT right_NN1 ,_, but_CCB when_RRQ can_VM a_AT1 refusal_NN1 of_IO licensing_NN1 be_VBI an_AT1 abuse_NN1 of_IO a_AT1 dominant_JJ market_NN1 position_NN1 ?_? 
</s>
<s>
Secondly_RR ,_, in_II what_DDQ circumstances_NN2 is_VBZ a_AT1 company_NN1 in_II a_AT1 dominant_JJ market_NN1 position_NN1 allowed_VVN to_TO refuse_VVI a_AT1 license_NN1 ?_? 
</s>
<s>
Moreover_RR ,_, are_VBR these_DD2 circumstances_NN2 practical_JJ and_CC reasonable_JJ from_II an_AT1 economic_JJ viewpoint_NN1 ?_? 
</s>
<s>
The_AT remainder_NN1 of_IO this_DD1 paper_NN1 is_VBZ divided_VVN into_II four_MC sections_NN2 ._. 
</s>
<s>
The_AT following_JJ section_NN1 provides_VVZ an_AT1 overview_NN1 of_IO the_AT applicable_JJ EU_NP1 legislation_NN1 and_CC principles_NN2 ._. 
</s>
<s>
The_AT second_MD section_NN1 presents_VVZ some_DD EU_NP1 case_NN1 law_NN1 and_CC the_AT third_MD section_NN1 discusses_VVZ the_AT justifiability_NN1 of_IO compulsory_JJ licensing_NN1 from_II an_AT1 economic_JJ point_NN1 of_IO view_NN1 ._. 
</s>
<s>
The_AT concluding_JJ section_NN1 presents_VVZ a_AT1 summarized_JJ overview_NN1 of_IO the_AT current_JJ situation_NN1 and_CC research_VV0 findings._NNU 2_MC ._. 
</s>
<s>
Applicable_JJ legislation_NN1 2.1_MC Licensing_NN1 Licensing_NN1 is_VBZ a_AT1 central_JJ feature_NN1 of_IO the_AT exploitation_NN1 of_IO intellectual_JJ property_NN1 ._. 
</s>
<s>
Intellectual_JJ property_NN1 right_NN1 can_VM be_VBI exploited_VVN through_II licensing_NN1 ;_; intellectual_JJ property_NN1 licensing_NN1 agreements_NN2 are_VBR simply_RR ordinary_JJ agreements_NN2 between_II the_AT right_JJ holder_NN1 and_CC third_MD parties_NN2 (_( licensees_NN2 )_) to_TO determine_VVI how_RRQ ,_, when_RRQ and_CC where_RRQ and_CC for_IF how_RGQ much_DA1 the_AT third_MD party_NN1 can_VM exploit_VVI the_AT intellectual_JJ property_NN1 of_IO the_AT owner_NN1 ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, the_AT licensor_NN1 takes_VVZ advantage_NN1 of_IO his_APPGE right_NN1 by_II granting_VVG licenses_NN2 ._. 
</s>
<s>
That_REX41 is_REX42 to_REX43 say_REX44 the_AT licensor_NN1 pursues_VVZ financial_JJ benefit_NN1 in_II the_AT form_NN1 of_IO royalties_NN2 and_CC license_VV0 fees_NN2 ._. 
</s>
<s>
Moreover_RR ,_, licensing_NN1 is_VBZ an_AT1 effective_JJ way_NN1 for_IF the_AT licensor_NN1 to_TO make_VVI profit_NN1 especially_RR in_II cases_NN2 where_RRQ the_AT licensor_NN1 himself_PPX1 is_VBZ not_XX able_JK to_TO use_VVI the_AT right_NN1 to_II its_APPGE full_JJ extent_NN1 due_JJ to_TO lack_VVI of_IO resources_NN2 or_CC expertise_NN1 ._. 
</s>
<s>
As_II an_AT1 exception_NN1 to_II the_AT general_JJ rule_NN1 of_IO the_AT freedom_NN1 of_IO contract_NN1 ,_, in_II some_DD situations_NN2 the_AT contents_NN2 of_IO the_AT license_NN1 agreement_NN1 can_VM be_VBI restricted_VVN due_II21 to_II22 some_DD compulsory_JJ provisions_NN2 ._. 
</s>
<s>
In_II these_DD2 situations_NN2 the_AT owner_NN1 of_IO the_AT intellectual_JJ property_NN1 right_NN1 is_VBZ not_XX allowed_VVN to_TO choose_VVI the_AT contracting_JJ party_NN1 freely_RR and_CC he_PPHS1 might_VM not_XX be_VBI able_JK to_TO even_RR choose_VVI whether_CSW to_TO make_VVI the_AT agreement_NN1 or_CC not_XX ._. 
</s>
<s>
Furthermore_RR ,_, such_DA obligation_NN1 to_II compulsory_JJ licensing_NN1 can_VM also_RR arise_VVI in_II individual_JJ cases_NN2 ,_, which_DDQ are_VBR the_AT subject_NN1 of_IO this_DD1 study_NN1 ,_, when_CS a_AT1 company_NN1 is_VBZ considered_VVN abusing_VVG its_APPGE dominant_JJ market_NN1 position._NNU 2.2_MC The_AT common_JJ market_NN1 and_CC the_AT abuse_NN1 of_IO a_AT1 dominant_JJ market_NN1 position_NN1 One_MC1 of_IO the_AT main_JJ objectives_NN2 of_IO the_AT EU_NP1 is_VBZ to_TO guarantee_VVI the_AT functionality_NN1 of_IO the_AT internal_JJ market_NN1 ._. 
</s>
<s>
Therefore_RR there_EX should_VM not_XX be_VBI any_DD trade_NN1 barriers_NN2 between_II the_AT member_NN1 states_NN2 ._. 
</s>
<s>
However_RR ,_, because_CS the_AT intellectual_JJ property_NN1 rights_NN2 as_CSA exclusive_JJ rights_NN2 are_VBR in_II nature_NN1 potential_NN1 to_TO erect_VVI barriers_NN2 to_TO free_VVI trade_NN1 ,_, the_AT free_JJ movement_NN1 of_IO goods_NN2 and_CC creation_NN1 of_IO a_AT1 common_JJ market_NN1 is_VBZ threatened_VVN to_II some_DD extent_NN1 by_II the_AT exercise_NN1 of_IO intellectual_JJ property_NN1 rights_NN2 ._. 
</s>
<s>
Accordingly_RR ,_, it_PPH1 is_VBZ apparent_JJ that_CST as_II31 well_II32 as_II33 the_AT EU_NP1 legislation_NN1 ,_, also_RR the_AT legal_JJ praxis_NN1 of_IO the_AT EU_NP1 plays_VVZ a_AT1 significant_JJ role_NN1 in_II determining_VVG the_AT boundaries_NN2 for_IF competition_NN1 as_RG well_RR as_CSA for_IF intellectual_JJ property_NN1 owner_NN1 's_GE rights_NN2 ._. 
</s>
<s>
Furthermore_RR ,_, the_AT promotion_NN1 of_IO market_NN1 integration_NN1 is_VBZ one_MC1 of_IO the_AT key_JJ objectives_NN2 of_IO EU_NP1 competition_NN1 policy_NN1 ._. 
</s>
<s>
Thus_RR the_AT EU_NP1 is_VBZ trying_VVG to_TO foster_VVI competition_NN1 and_CC accordingly_RR it_PPH1 has_VHZ set_VVN some_DD legislative_JJ boundaries_NN2 for_IF the_AT companies_NN2 that_CST operate_VV0 in_II the_AT common_JJ market_NN1 ._. 
</s>
<s>
The_AT aim_NN1 is_VBZ to_TO ensure_VVI that_DD1 free_JJ trade_NN1 is_VBZ not_XX compromised_VVN by_II unacceptable_JJ ,_, restrictive_JJ or_CC monopolistic_JJ practices_NN2 ._. 
</s>
<s>
Competition_NN1 law_NN1 rules_NN2 applying_VVG to_II companies_NN2 that_CST enjoy_VV0 economic_JJ strength_NN1 and_CC concerning_VVG the_AT abuse_NN1 of_IO a_AT1 dominant_JJ market_NN1 position_NN1 are_VBR in_II article_NN1 102_MC TFEU_NN1 which_DDQ provides_VVZ as_CSA follows_VVZ :_: Any_DD abuse_NN1 by_II one_MC1 or_CC more_DAR undertakings_NN2 of_IO a_AT1 dominant_JJ position_NN1 within_II the_AT internal_JJ market_NN1 or_CC in_II a_AT1 substantial_JJ part_NN1 of_IO it_PPH1 shall_VM be_VBI prohibited_VVN as_CSA incompatible_JJ with_IW the_AT internal_JJ market_NN1 in_CS41 so_CS42 far_CS43 as_CS44 it_PPH1 may_VM affect_VVI trade_NN1 between_II Member_NN1 States_NP1 ._. 
</s>
<s>
Such_DA abuse_NN1 may_VM ,_, in_RR21 particular_RR22 ,_, consist_VV0 in_RP :_: (_( a_ZZ1 )_) directly_RR or_CC indirectly_RR imposing_VVG unfair_JJ purchase_NN1 or_CC selling_NN1 prices_NN2 or_CC other_JJ unfair_JJ trading_NN1 conditions_NN2 ;_; (_( b_ZZ1 )_) limiting_JJ production_NN1 ,_, markets_NN2 or_CC technical_JJ development_NN1 to_II the_AT prejudice_NN1 of_IO consumers_NN2 ;_; (_( c_ZZ1 )_) applying_VVG dissimilar_JJ conditions_NN2 to_II equivalent_JJ transactions_NN2 with_IW other_JJ trading_NN1 parties_NN2 ,_, thereby_RR placing_VVG them_PPHO2 at_II a_AT1 competitive_JJ disadvantage_NN1 ;_; (_( d_ZZ1 )_) making_VVG the_AT conclusion_NN1 of_IO contracts_NN2 subject_II21 to_II22 acceptance_NN1 by_II the_AT other_JJ parties_NN2 of_IO supplementary_JJ obligations_NN2 which_DDQ ,_, by_II their_APPGE nature_NN1 or_CC according_II21 to_II22 commercial_JJ usage_NN1 ,_, have_VH0 no_AT connection_NN1 with_IW the_AT subject_NN1 of_IO such_DA contracts_NN2 ._. 
</s>
<s>
It_PPH1 should_VM be_VBI underlined_VVN that_CST according_II21 to_II22 the_AT article_NN1 102_MC ,_, only_RR the_AT abuse_NN1 of_IO a_AT1 dominant_JJ market_NN1 position_NN1 market_NN1 power_NN1 -_- not_XX the_AT position_NN1 in_II itself_PPX1 ,_, is_VBZ forbidden_VVN ._. 
</s>
<s>
Generally_RR abuse_NN1 has_VHZ been_VBN described_VVN as_II conduct_NN1 by_II a_AT1 dominant_JJ firm_NN1 which_DDQ seriously_RR and_CC unjustifiably_RR distorts_VVZ competition_NN1 or_CC causes_VVZ it_PPH1 further_RRR to_TO weaken_VVI ._. 
</s>
<s>
Abusive_JJ behavior_NN1 can_VM for_REX21 example_REX22 be_VBI price_NN1 discrimination_NN1 ._. 
</s>
<s>
The_AT relevance_NN1 of_IO article_NN1 102_MC for_IF the_AT owners_NN2 of_IO intellectual_JJ property_NN1 rights_NN2 can_VM be_VBI seen_VVN in_II the_AT context_NN1 of_IO licensing_NN1 ._. 
</s>
<s>
Firstly_RR ,_, a_AT1 refusal_NN1 to_TO enter_VVI an_AT1 agreement_NN1 with_IW a_AT1 third_MD party_NN1 does_VDZ not_XX automatically_RR mean_VVI a_AT1 contravention_NN1 with_IW the_AT article_NN1 ._. 
</s>
<s>
However_RR ,_, in_II some_DD circumstances_NN2 it_PPH1 may_VM be_VBI abusing_VVG of_IO a_AT1 dominant_JJ market_NN1 position_NN1 to_TO refuse_VVI to_TO license_VVI ._. 
</s>
<s>
Hence_RR ,_, what_DDQ are_VBR the_AT rules_NN2 concerning_II compulsory_JJ licensing_NN1 ?_? 
</s>
<s>
In_BCL21 order_BCL22 to_TO address_VVI this_DD1 question_NN1 ,_, the_AT European_JJ courts_NN2 have_VH0 sought_VVN to_TO develop_VVI rules_NN2 which_DDQ balance_VV0 the_AT interests_NN2 of_IO the_AT holder_NN1 of_IO the_AT intellectual_JJ property_NN1 right_NN1 with_IW those_DD2 of_IO the_AT creation_NN1 of_IO a_AT1 common_JJ market_NN1 and_CC competition_NN1 law_NN1 ._. 
</s>
<s>
Accordingly_RR ,_, some_DD case_NN1 law_NN1 will_VM be_VBI examined_VVN in_II the_AT following_JJ section._NNU 3_MC ._. 
</s>
<s>
Compulsory_JJ licensing_NN1 case_NN1 law_NN1 of_IO the_AT EU_NP1 In_II one_MC1 of_IO the_AT first_MD cases_NN2 concerning_II the_AT question_NN1 as_II21 to_II22 when_RRQ and_CC if_CS a_AT1 refusal_NN1 to_TO license_VVI a_AT1 third_MD party_NN1 might_VM amount_NN1 to_II an_AT1 abuse_NN1 of_IO a_AT1 dominant_JJ position_NN1 -the_AT case_NN1 Volvo_NP1 v_ZZ1 Veng_NP1 -_- the_AT European_JJ Court_NN1 of_IO Justice_NN1 (_( ECJ_NP1 )_) stated_VVD that_CST the_AT mere_JJ refusal_NN1 to_TO license_VVI a_AT1 third_MD party_NN1 did_VDD not_XX amount_NN1 to_II an_AT1 abuse_NN1 of_IO a_AT1 dominant_JJ position_NN1 ._. 
</s>
<s>
Later_RRR on_RP ECJ_NP1 outlined_VVD in_II the_AT Magill_NP1 case_NN1 (_( Radio_NP1 Telefis_NP1 Eireann_NP1 (_( RTE_NP1 )_) and_CC Independent_JJ Television_NN1 Publications_NN2 Ltd_JJ (_( ITP_NP1 )_) v_ZZ1 Commission_NN1 )_) that_CST the_AT exercise_NN1 of_IO intellectual_JJ property_NN1 right_NN1 and_CC the_AT refusal_NN1 of_IO a_AT1 license_NN1 do_VD0 not_XX automatically_RR pose_VVI an_AT1 infringement_NN1 on_II competition_NN1 rules_NN2 ,_, but_CCB in_II certain_JJ circumstances_NN2 they_PPHS2 can_VM lead_VVI to_II an_AT1 abuse_NN1 of_IO a_AT1 dominant_JJ position_NN1 ._. 
</s>
<s>
ECJ_NP1 defined_VVD those_DD2 exceptional_JJ circumstances_NN2 in_II which_DDQ a_AT1 refusal_NN1 to_TO license_VVI may_VM constitute_VVI an_AT1 instrument_NN1 of_IO abuse_NN1 ._. 
</s>
<s>
These_DD2 are_VBR where_CS there_EX is_VBZ no_AT actual_JJ or_CC potential_JJ substitute_NN1 for_IF the_AT product_NN1 for_IF which_DDQ the_AT license_NN1 is_VBZ sought_VVN and_CC there_EX is_VBZ a_AT1 demand_NN1 for_IF a_AT1 product_NN1 which_DDQ is_VBZ not_XX provided_VVN by_II the_AT rights_NN2 owner_NN1 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, the_AT refusal_NN1 to_TO license_VVI must_VM not_XX be_VBI objectively_RR justified_VVN and_CC interference_NN1 in_II a_AT1 secondary_JJ market_NN1 has_VHZ to_TO occur_VVI ._. 
</s>
<s>
After_CS the_AT Magill_NP1 case_NN1 ,_, the_AT ECJ_NP1 gave_VVD its_APPGE decision_NN1 in_II IMS_NP1 Health_NN1 case_NN1 (_( IMS_NP1 Health_NN1 GmbH_NP1 &;_NULL Co_NP1 ._. 
</s>
<s>
OHG_VV0 v_ZZ1 NDC_NP1 Health_NN1 GmbH_NP1 &;_NULL Co_NP1 ._. 
</s>
<s>
KG_NNU )_) ._. 
</s>
<s>
In_II this_DD1 case_NN1 ,_, after_II referring_VVG to_II Volvo_NP1 v_ZZ1 Veng_NP1 and_CC Magill_NP1 ,_, the_AT court_NN1 underlined_VVD that_CST an_AT1 exclusive_JJ right_NN1 of_IO reproduction_NN1 forms_VVZ a_AT1 part_NN1 of_IO an_AT1 intellectual_JJ property_NN1 owner_NN1 's_GE rights_NN2 ._. 
</s>
<s>
A_AT1 refusal_NN1 to_TO grant_VVI a_AT1 license_NN1 ,_, even_RR by_II a_AT1 dominant_JJ company_NN1 ,_, could_VM not_XX in_II itself_PPX1 constitute_VV0 an_AT1 abuse_NN1 of_IO article_NN1 82_MC EC_NP1 (_( currently_RR 102_MC TFEU_NP1 )_) except_CS in_II exceptional_JJ circumstances_NN2 ._. 
</s>
<s>
The_AT ECJ_NP1 stated_VVD that_CST the_AT refusal_NN1 by_II a_AT1 company_NN1 which_DDQ holds_VVZ a_AT1 dominant_JJ position_NN1 to_TO grant_VVI a_AT1 license_NN1 to_II another_DD1 company_NN1 constitutes_VVZ an_AT1 abuse_NN1 of_IO a_AT1 dominant_JJ position_NN1 where_RRQ the_AT following_JJ conditions_NN2 are_VBR fulfilled_VVN :_: the_AT refusal_NN1 must_VM prevent_VVI the_AT emergence_NN1 of_IO a_AT1 new_JJ product_NN1 for_IF which_DDQ there_EX is_VBZ a_AT1 potential_JJ demand_NN1 ;_; the_AT refusal_NN1 can_VM not_XX be_VBI objectively_RR justified_VVN and_CC the_AT refusal_NN1 must_VM be_VBI such_II21 as_II22 to_TO exclude_VVI competition_NN1 in_II a_AT1 secondary_JJ market_NN1 ._. 
</s>
<s>
With_IW the_AT above_JJ mentioned_VVD IMS_NP1 Health_NN1 decision_NN1 ,_, ECJ_NP1 reinforced_VVD the_AT interpretation_NN1 adopted_VVD before_RT ._. 
</s>
<s>
The_AT court_NN1 also_RR reinforced_VVD the_AT necessity_NN1 of_IO the_AT prerequisites_NN2 the_AT exceptional_JJ circumstances-_NN1 where_CS fulfilling_VVG the_AT undertaking_NN1 in_II a_AT1 dominant_JJ position_NN1 can_VM be_VBI considered_VVN abusing_VVG its_APPGE position_NN1 ._. 
</s>
<s>
Nevertheless_RR ,_, the_AT court_NN1 has_VHZ generally_RR emphasized_VVN the_AT exceptionality_NN1 of_IO compulsory_JJ licensing_NN1 ._. 
</s>
<s>
The_AT most_RGT recent_JJ case_NN1 concerning_II the_AT compulsory_JJ licensing_NN1 of_IO intellectual_JJ property_NN1 rights_NN2 is_VBZ the_AT Microsoft_NP1 case_NN1 ._. 
</s>
<s>
In_II the_AT Microsoft_NP1 case_NN1 ,_, one_MC1 of_IO the_AT most_RGT famous_JJ cases_NN2 ,_, both_DB2 the_AT European_JJ Commission_NN1 and_CC later_RRR on_RP the_AT Court_NN1 of_IO First_MD Instance_NN1 (_( CFI_NP1 )_) concluded_VVD that_CST Microsoft_NP1 had_VHD abused_VVN its_APPGE dominant_JJ position_NN1 in_II the_AT PC_NN1 operating_NN1 system_NN1 market_NN1 by_II refusing_VVG to_TO supply_VVI competitors_NN2 the_AT necessary_JJ interface_NN1 information_NN1 for_IF their_APPGE products_NN2 to_TO interoperate_VVI with_IW Windows_NP1 ,_, and_CC hence_RR to_TO compete_VVI viably_RR in_II the_AT market_NN1 ._. 
</s>
<s>
The_AT CFI_NP1 concluded_VVD that_CST while_CS companies_NN2 are_VBR as_II a_AT1 rule_NN1 free_JJ to_TO choose_VVI business_NN1 partners_NN2 ,_, is_VBZ some_DD circumstances_NN2 a_AT1 refusal_NN1 to_TO supply_VVI by_II a_AT1 dominant_JJ company_NN1 can_VM constitute_VVI an_AT1 abuse_NN1 if_CS a_AT1 dominant_JJ position_NN1 unless_CS it_PPH1 is_VBZ objectively_RR justified_VVN ._. 
</s>
<s>
Moreover_RR ,_, the_AT exercise_NN1 of_IO the_AT exclusive_JJ right_NN1 by_II the_AT owner_NN1 of_IO the_AT intellectual_JJ property_NN1 right_NN1 may_VM give_VVI rise_NN1 to_II such_DA an_AT1 abuse_NN1 only_RR in_II exceptional_JJ circumstances_NN2 ._. 
</s>
<s>
The_AT CFI_NP1 stated_VVD that_CST there_EX were_VBDR three_MC preconditions_NN2 for_IF the_AT exceptional_JJ circumstances_NN2 :_: the_AT refusal_NN1 must_VM relate_VVI to_II a_AT1 product_NN1 or_CC service_VV0 indispensable_JJ to_II the_AT exercise_NN1 of_IO an_AT1 activity_NN1 on_II a_AT1 neighboring_JJ market_NN1 ,_, the_AT refusal_NN1 must_VM be_VBI such_II21 as_II22 to_TO exclude_VVI any_DD effective_JJ competition_NN1 on_II that_DD1 market_NN1 ,_, and_CC the_AT refusal_NN1 must_VM prevent_VVI the_AT appearance_NN1 of_IO a_AT1 new_JJ product_NN1 for_IF which_DDQ there_EX is_VBZ demand_NN1 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, the_AT Commission_NN1 had_VHD concluded_VVN in_II its_APPGE decision_NN1 that_CST it_PPH1 was_VBDZ entitled_VVN to_TO take_VVI account_NN1 of_IO exceptional_JJ circumstances_NN2 other_II21 than_II22 those_DD2 identified_VVN by_II the_AT ECJ_NP1 in_II the_AT Magill-case_NN1 for_REX21 example_REX22 ._. 
</s>
<s>
In_II31 spite_II32 of_II33 this_DD1 Commissions_VVZ statement_NN1 ,_, the_AT CFI_NP1 considered_VVD that_DD1 first_MD of_IO all_DB ,_, should_VM be_VBI decided_VVN whether_CSW the_AT circumstances_NN2 identified_VVN in_II previous_JJ cases_NN2 ,_, Magill_NP1 and_CC IMS_NP1 Health_NN1 ,_, were_VBDR also_RR present_JJ in_II this_DD1 case_NN1 ._. 
</s>
<s>
Only_RR if_CS it_PPH1 would_VM find_VVI that_CST one_MC1 or_CC more_DAR of_IO those_DD2 circumstances_NN2 were_VBDR absent_JJ the_AT Court_NN1 would_VM proceed_VVI to_TO assess_VVI the_AT particular_JJ circumstances_NN2 invoked_VVN by_II the_AT Commission_NN1 that_CST is_VBZ the_AT other_JJ circumstances._NNU 5_MC ._. 
</s>
<s>
Economical_JJ evaluation_NN1 of_IO exceptional_JJ circumstances_NN2 as_II a_AT1 whole_NN1 5.1_MC Competing_JJ interests_NN2 Evidently_RR ,_, the_AT essence_NN1 of_IO an_AT1 intellectual_JJ property_NN1 right_NN1 is_VBZ that_CST it_PPH1 gives_VVZ the_AT owner_NN1 a_AT1 monopoly_NN1 in_II the_AT subject_NN1 matter_NN1 of_IO the_AT right_NN1 for_IF a_AT1 declined_VVN period_NN1 of_IO time_NNT1 ._. 
</s>
<s>
The_AT owner_NN1 strives_VVZ to_TO obtain_VVI economic_JJ return_NN1 with_IW the_AT intellectual_JJ property_NN1 right_NN1 ._. 
</s>
<s>
Generally_RR ,_, in_II Europe_NP1 it_PPH1 is_VBZ considered_VVN pro-competitive_JJ to_TO grant_VVI strong_JJ protection_NN1 to_II intellectual_JJ property_NN1 rights_NN2 ._. 
</s>
<s>
On_II the_AT contrary_NN1 ,_, freedom_NN1 to_TO copy_VVI is_VBZ a_AT1 cornerstone_NN1 of_IO competition_NN1 and_CC it_PPH1 operates_VVZ to_TO minimize_VVI monopoly_NN1 profits_NN2 ._. 
</s>
<s>
What_DDQ is_VBZ right_JJ balance_NN1 in_II the_AT market_NN1 then_RT and_CC what_DDQ is_VBZ the_AT right_JJ amount_NN1 of_IO intellectual_JJ property_NN1 protection_NN1 ?_? 
</s>
<s>
How_RGQ far_RR does_VDZ the_AT requirement_NN1 for_IF a_AT1 free_JJ trade_NN1 go_VV0 ,_, what_DDQ are_VBR the_AT needs_NN2 of_IO customers_NN2 and_CC when_RRQ can_VM compulsory_JJ licensing_NN1 be_VBI justified_VVN ?_? 
</s>
<s>
When_CS assessing_VVG the_AT justifiability_NN1 of_IO compulsory_JJ licensing_NN1 ,_, three_MC kinds_NN2 of_IO interests_NN2 have_VH0 to_TO be_VBI taken_VVN into_II account_NN1 ._. 
</s>
<s>
Such_DA are_VBR those_DD2 of_IO the_AT company_NN1 in_II a_AT1 monopoly_NN1 position_NN1 ,_, competing_VVG companies_NN2 and_CC consumers_NN2 ._. 
</s>
<s>
A_AT1 company_NN1 in_II a_AT1 monopoly_NN1 position_NN1 is_VBZ aiming_VVG at_II reducing_VVG the_AT transaction_NN1 costs_VVZ by_II refusing_VVG to_TO license_VVI ._. 
</s>
<s>
Furthermore_RR ,_, as_CSA a_AT1 sole_JJ manufacturer_NN1 and_CC seller_NN1 of_IO a_AT1 product_NN1 ,_, a_AT1 company_NN1 could_VM define_VVI the_AT price_NN1 of_IO their_APPGE product_NN1 in_II the_AT market_NN1 and_CC maximize_VV0 their_APPGE monopoly_NN1 profits_NN2 ._. 
</s>
<s>
First_MD of_IO all_DB ,_, Motta_NP1 (_( 2007_MC )_) ,_, among_II others_NN2 ,_, has_VHZ argued_VVN that_CST the_AT prospect_NN1 of_IO having_VHG market_NN1 power_NN1 (_( i.e._REX some_DD profit_NN1 )_) represents_VVZ the_AT most_RGT powerful_JJ incentive_NN1 for_IF firms_NN2 to_TO innovate_VVI and_CC invest_VVI ._. 
</s>
<s>
Regulation_NN1 concerning_II competition_NN1 should_VM therefore_RR ensure_VVI that_CST firms_NN2 will_VM be_VBI able_JK to_TO enjoy_VVI the_AT rewards_NN2 for_IF their_APPGE investments_NN2 ._. 
</s>
<s>
On_II this_DD1 account_NN1 ,_, Motta_NP1 (_( 2007_MC )_) further_RRR states_VVZ that_CST "_" as_II a_AT1 consequence_NN1 ,_, drastic_JJ structural_JJ remedies_NN2 must_VM be_VBI carried_VVN out_RP only_RR in_II truly_RR exceptional_JJ circumstances_NN2 ._. "_" 
</s>
<s>
Furthermore_RR ,_, in_II31 addition_II32 to_II33 taking_VVG into_II account_NN1 the_AT encouragement_NN1 of_IO the_AT incentives_NN2 to_TO innovate_VVI of_IO the_AT company_NN1 in_II a_AT1 monopoly_NN1 position_NN1 ,_, also_RR the_AT public_JJ interest_NN1 should_VM be_VBI taken_VVN into_II account_NN1 ._. 
</s>
<s>
The_AT public_JJ interest_NN1 can_VM be_VBI jeopardized_VVN if_CS private_JJ rights_NN2 are_VBR exercised_VVN in_II a_AT1 way_NN1 that_CST means_VVZ that_CST the_AT property_NN1 in_II question_NN1 is_VBZ not_XX used_VVN or_CC exploited_VVN in_II a_AT1 public_JJ setting_NN1 ._. 
</s>
<s>
Compulsory_JJ licensing_NN1 is_VBZ an_AT1 excellent_JJ example_NN1 of_IO a_AT1 situation_NN1 where_RRQ public_JJ and_CC private_JJ interests_NN2 are_VBR competing_VVG ._. 
</s>
<s>
If_CS the_AT competing_JJ companies_NN2 can_VM not_XX enter_VVI the_AT market_NN1 and_CC do_VD0 not_XX have_VHI access_NN1 to_II essential_JJ facilities_NN2 ,_, there_EX is_VBZ no_AT competition_NN1 ._. 
</s>
<s>
Lack_NN1 of_IO competition_NN1 means_VVZ usually_RR higher_JJR prices_NN2 for_IF consumers_NN2 ._. 
</s>
<s>
The_AT aim_NN1 with_IW competition_NN1 law_NN1 would_VM be_VBI to_TO enhance_VVI consumer_NN1 welfare_NN1 ._. 
</s>
<s>
Furthermore_RR ,_, in_II some_DD cases_NN2 compulsory_JJ licensing_NN1 is_VBZ hence_RR justified_VVN in_BCL21 order_BCL22 to_TO protect_VVI consumer_NN1 welfare_NN1 although_CS it_PPH1 restricts_VVZ the_AT actions_NN2 of_IO the_AT company_NN1 that_CST has_VHZ a_AT1 monopoly_NN1 ._. 
</s>
<s>
In_II31 relation_II32 to_II33 balancing_VVG the_AT public_JJ interest_NN1 to_II the_AT interests_NN2 of_IO the_AT company_NN1 in_II a_AT1 dominant_JJ position_NN1 ,_, a_AT1 specific_JJ test_NN1 was_VBDZ used_VVN that_CST focused_VVD on_II innovation_NN1 incentives_NN2 in_II the_AT Microsoft_NP1 case_NN1 ._. 
</s>
<s>
This_DD1 test_NN1 was_VBDZ used_VVN when_CS deciding_VVG whether_CSW the_AT refusal_NN1 to_TO license_VVI could_VM be_VBI objectively_RR justified_VVN ._. 
</s>
<s>
The_AT test_NN1 included_VVD an_AT1 evaluation_NN1 between_II interests_NN2 :_: the_AT company_NN1 's_GE refusal_NN1 to_TO supply_VVI can_VM not_XX be_VBI objectively_RR justified_VVN under_II article_NN1 102_MC TFEU_NN1 if_CS the_AT negative_JJ impacts_NN2 of_IO a_AT1 compulsory_JJ license_NN1 on_II the_AT dominant_JJ company_NN1 's_GE incentives_NN2 to_TO innovate_VVI are_VBR outweighed_VVN by_II its_APPGE positive_JJ impact_NN1 on_II the_AT innovation_NN1 level_NN1 in_II the_AT entire_JJ industry_NN1 ._. 
</s>
<s>
In_II the_AT Microsoft_NP1 case_NN1 ,_, the_AT possible_JJ negative_JJ impact_NN1 of_IO the_AT order_NN1 to_TO supply_VVI interface_NN1 information_NN1 on_II Microsoft_NP1 's_GE incentives_NN2 to_TO innovate_VVI was_VBDZ outweighed_VVN by_II its_APPGE positive_JJ impact_NN1 on_II the_AT level_NN1 of_IO innovation_NN1 of_IO the_AT whole_JJ industry_NN1 ._. 
</s>
<s>
According_II21 to_II22 Vezzoso_NP1 (_( 2006_MC )_) ,_, such_DA a_AT1 refusal_NN1 to_TO deal_VVI could_VM constrain_VVI the_AT consumer_NN1 choice_NN1 ,_, lower_JJR input_NN1 ,_, raise_VV0 prices_NN2 and_CC therefore_RR produce_VV0 allocative_JJ inefficiency_NN1 ._. 
</s>
<s>
Vezzoso_NP1 (_( 2006_MC )_) furthermore_RR concluded_VVN that_CST the_AT test_NN1 however_RR was_VBDZ controversial_JJ from_II both_DB2 economic_JJ as_II31 well_II32 as_II33 legal_JJ point_NN1 of_IO view_NN1 ._. 
</s>
<s>
All_DB in_II all_DB ,_, in_RR21 general_RR22 compulsory_JJ licensing_NN1 is_VBZ justifiable_JJ in_II situations_NN2 where_RRQ a_AT1 company_NN1 in_II a_AT1 dominant_JJ market_NN1 position_NN1 has_VHZ the_AT only_JJ access_NN1 to_II an_AT1 inevitable_JJ facility_NN1 and_CC this_DD1 causes_VVZ a_AT1 restrain_VV0 to_II competition_NN1 ._. 
</s>
<s>
The_AT inevitable_JJ facility_NN1 should_VM be_VBI essential_JJ and_CC inevitable_JJ to_II other_JJ companies_NN2 for_REX21 example_REX22 for_IF entering_VVG the_AT market_NN1 ._. 
</s>
<s>
The_AT fear_NN1 of_IO compulsory_JJ licensing_NN1 might_VM be_VBI a_AT1 hindrance_NN1 of_IO innovation_NN1 to_II the_AT company_NN1 in_II a_AT1 dominant_JJ position_NN1 if_CS it_PPH1 is_VBZ aware_JJ that_CST the_AT innovation_NN1 is_VBZ so_RG essential_JJ to_II others_NN2 that_CST the_AT company_NN1 will_VM be_VBI obliged_VVN to_TO license_VVI it_PPH1 ._. 
</s>
<s>
However_RR ,_, in_II these_DD2 cases_NN2 the_AT company_NN1 might_VM freely_RR draft_VVI licensing_VVG agreements_NN2 and_CC get_VVI the_AT profits_NN2 that_DD1 way_NN1 ._. 
</s>
<s>
According_II21 to_II22 Kanter_NP1 (_( 2006_MC )_) ,_, compulsory_JJ licensing_NN1 may_VM be_VBI used_VVN only_RR in_II cases_NN2 where_RRQ other_JJ less_RGR restrictive_JJ measures_NN2 are_VBR likely_JJ to_TO be_VBI insufficient_JJ in_II addressing_VVG the_AT anti-_JJ competitive_JJ conduct_NN1 ._. 
</s>
<s>
Furthermore_RR ,_, authorities_NN2 should_VM draft_VVI the_AT compulsory_JJ licensing_NN1 as_RG narrowly_RR as_CSA possible_JJ and_CC competition_NN1 authorities_NN2 must_VM not_XX intervene_VVI too_RG rashly_RR and_CC reduce_VVI the_AT incentive_NN1 to_TO innovate_VVI ._. 
</s>
<s>
I_PPIS1 agree_VV0 with_IW Mr._NNB Kanter_NP1 and_CC also_RR other_JJ authorities_NN2 ,_, in_II31 addition_II32 to_II33 competition_NN1 authorities_NN2 ,_, should_VM address_VVI the_AT issue_NN1 similarly._NNU 5.2_MC Exceptional_JJ circumstances_NN2 as_CSA guidelines_NN2 According_II21 to_II22 Kanter_NP1 (_( 2006_MC )_) ,_, economic_JJ reasoning_NN1 and_CC common_JJ sense_NN1 suggest_VV0 that_CST strong_JJ intellectual_JJ property_NN1 rights_NN2 encourage_VV0 productivity_NN1 ,_, investments_NN2 and_CC innovation_NN1 ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 ,_, if_CS a_AT1 firm_NN1 has_VHZ control_NN1 over_II an_AT1 essential_JJ facility_NN1 this_DD1 can_VM undermine_VVI competition_NN1 and_CC reduce_VVI productivity_NN1 and_CC lessen_VV0 the_AT incentive_NN1 to_TO innovate_VVI ._. 
</s>
<s>
Consequently_RR ,_, defining_VVG what_DDQ is_VBZ the_AT right_JJ balance_NN1 between_II these_DD2 interests_NN2 is_VBZ not_XX an_AT1 easy_JJ task_NN1 ._. 
</s>
<s>
Thus_RR ,_, are_VBR the_AT exceptional_JJ circumstances_NN2 defined_VVN in_II the_AT case_NN1 law_NN1 of_IO the_AT EU_NP1 a_AT1 reasonable_JJ way_NN1 of_IO evaluating_VVG situations_NN2 concerning_II the_AT justifiability_NN1 of_IO compulsory_JJ licensing_NN1 ?_? 
</s>
<s>
The_AT conditions_NN2 that_CST the_AT courts_NN2 have_VH0 laid_VVN down_RP for_IF the_AT exceptional_JJ circumstances_NN2 for_IF compulsory_JJ licensing_NN1 in_CS21 case_CS22 law_NN1 can_VM be_VBI considered_VVN as_CSA guidelines_NN2 ._. 
</s>
<s>
The_AT problem_NN1 is_VBZ ,_, however_RR ,_, that_DD1 how_RRQ can_VM a_AT1 company_NN1 that_CST operates_VVZ in_II the_AT marketplace_NN1 be_VBI able_JK to_TO recognize_VVI the_AT conditions_NN2 for_IF abuse_NN1 early_RR enough_RR or_CC at_II all_DB during_II the_AT course_NN1 of_IO business_NN1 ?_? 
</s>
<s>
Are_VBR the_AT conditions_NN2 that_CST the_AT courts_NN2 made_VVN in_II the_AT mentioned_VVN cases_NN2 so_RG flexible_JJ that_CST all_DB relevant_JJ factors_NN2 in_II the_AT market_NN1 can_VM be_VBI taken_VVN into_II account_NN1 ?_? 
</s>
<s>
In_II my_APPGE opinion_NN1 ,_, the_AT rules_NN2 are_VBR reasonable_JJ ,_, but_CCB there_EX should_VM be_VBI some_DD flexibility_NN1 when_CS the_AT circumstances_NN2 are_VBR assessed_VVN by_II the_AT courts_NN2 in_II the_AT future_NN1 ._. 
</s>
<s>
I_PPIS1 also_RR consider_VV0 it_PPH1 to_TO be_VBI possible_JJ that_CST other_JJ circumstances_NN2 could_VM be_VBI taken_VVN into_II account_NN1 as_II the_AT Commission_NN1 has_VHZ suggested_VVN in_II its_APPGE decision_NN1 in_II the_AT Microsoft_NP1 case_NN1 ._. 
</s>
<s>
Moreover_RR ,_, I_PPIS1 agree_VV0 with_IW Korah_NP1 (_( 2006_MC )_) about_II the_AT fact_NN1 that_CST the_AT Commission_NN1 's_GE decision_NN1 in_II the_AT Microsoft_NP1 case_NN1 was_VBDZ controversial_JJ and_CC more_DAR discussion_NN1 on_II economic_JJ theory_NN1 is_VBZ needed_VVN ._. 
</s>
<s>
As_CSA can_VM be_VBI reasoned_VVN on_II the_AT basis_NN1 of_IO legal_JJ praxis_NN1 ,_, compulsory_JJ licensing_NN1 is_VBZ possible_JJ in_II a_AT1 situation_NN1 where_RRQ a_AT1 dominant_JJ firm_NN1 owns_VVZ or_CC controls_VVZ access_NN1 to_II an_AT1 essential_JJ facility_NN1 ._. 
</s>
<s>
It_PPH1 then_RT may_VM be_VBI pro-competitive_JJ to_TO force_VVI the_AT dominant_JJ company_NN1 to_TO grant_VVI access_NN1 to_II the_AT facility_NN1 provided_CS21 that_CS22 a_AT1 refusal_NN1 of_IO access_NN1 would_VM have_VHI significant_JJ anti-competitive_JJ effects_NN2 ._. 
</s>
<s>
The_AT possible_JJ anti-competitive_JJ effects_NN2 are_VBR an_AT1 important_JJ factor_NN1 when_CS the_AT situations_NN2 are_VBR evaluated_VVN ._. 
</s>
<s>
According_II21 to_II22 Mylly_NP1 (_( 2009_MC )_) the_AT Magill_NP1 decision_NN1 marked_VVN the_AT beginning_NN1 of_IO an_AT1 effects-based_JJ argumentation_NN1 model_NN1 ._. 
</s>
<s>
This_DD1 means_VVZ that_CST the_AT court_NN1 based_VVN its_APPGE decision_NN1 on_II considerations_NN2 related_VVN to_II competitive_JJ effects._NNU 6_MC ._. 
</s>
<s>
The_AT conclusions_NN2 This_DD1 study_NN1 investigated_VVD the_AT justifiability_NN1 of_IO compulsory_JJ licensing_NN1 and_CC the_AT definition_NN1 of_IO exceptional_JJ circumstances_NN2 ._. 
</s>
<s>
According_II21 to_II22 the_AT legal_JJ praxis_NN1 of_IO the_AT European_NN1 courts_VVZ the_AT refusal_NN1 by_II a_AT1 company_NN1 holding_VVG a_AT1 dominant_JJ position_NN1 to_TO license_VVI a_AT1 third_MD party_NN1 to_TO use_VVI a_AT1 product_NN1 covered_VVN by_II an_AT1 intellectual_JJ property_NN1 right_NN1 can_VM not_XX in_II itself_PPX1 constitute_VV0 an_AT1 abuse_NN1 of_IO a_AT1 dominant_JJ position_NN1 within_II the_AT meaning_NN1 of_IO article_NN1 102_MC TFEU_NP1 ._. 
</s>
<s>
However_RR ,_, in_II exceptional_JJ circumstances_NN2 the_AT exercise_NN1 of_IO the_AT exclusive_JJ right_NN1 by_II the_AT owner_NN1 of_IO the_AT intellectual_JJ property_NN1 right_NN1 may_VM give_VVI rise_NN1 to_II such_DA an_AT1 abuse_NN1 ._. 
</s>
<s>
Evidently_RR ,_, as_CSA mentioned_VVN ,_, this_DD1 is_VBZ an_AT1 exception_NN1 about_II the_AT general_JJ rules_NN2 and_CC aims_NN2 of_IO intellectual_JJ property_NN1 law_NN1 ._. 
</s>
<s>
Additionally_RR ,_, it_PPH1 is_VBZ an_AT1 exception_NN1 to_II the_AT rule_NN1 that_CST companies_NN2 are_VBR free_JJ to_TO choose_VVI their_APPGE business_NN1 partners_NN2 ._. 
</s>
<s>
By_II giving_VVG guidelines_NN2 on_II compulsory_JJ licensing_NN1 ,_, the_AT EU_NP1 is_VBZ aiming_VVG in_II assuring_VVG effective_JJ competition_NN1 and_CC furthermore_RR the_AT free_JJ movement_NN1 of_IO goods_NN2 ._. 
</s>
<s>
A_AT1 refusal_NN1 of_IO licensing_NN1 is_VBZ considered_VVN an_AT1 abuse_NN1 of_IO a_AT1 dominant_JJ market_NN1 position_NN1 if_CS the_AT exceptional_JJ circumstances_NN2 that_CST have_VH0 been_VBN assessed_VVN by_II the_AT courts_NN2 on_II an_AT1 ad_NN1 hoc-basis_NN1 are_VBR fulfilled_VVN ._. 
</s>
<s>
On_II the_AT basis_NN1 of_IO the_AT case_NN1 law_NN1 ,_, the_AT refusal_NN1 must_VM relate_VVI to_II a_AT1 product_NN1 or_CC service_VV0 that_DD1 is_VBZ indispensable_JJ (_( essential_JJ )_) ,_, the_AT refusal_NN1 excludes_VVZ effective_JJ competition_NN1 on_II the_AT market_NN1 and_CC the_AT refusal_NN1 prevents_VVZ new_JJ products_NN2 from_II entering_VVG the_AT market_NN1 provided_CS21 that_CS22 there_EX is_VBZ a_AT1 demand_NN1 for_IF those_DD2 products_NN2 ._. 
</s>
<s>
If_CS these_DD2 conditions_NN2 are_VBR fulfilled_VVN ,_, it_PPH1 has_VHZ to_TO be_VBI also_RR stated_VVN that_CST the_AT refusal_NN1 can_VM not_XX be_VBI objectively_RR justified_VVN ._. 
</s>
<s>
Moreover_RR ,_, it_PPH1 is_VBZ not_XX considered_VVN at_II the_AT moment_NN1 to_TO be_VBI possible_JJ that_CST other_JJ circumstances_NN2 would_VM be_VBI taken_VVN into_II account_NN1 according_II21 to_II22 the_AT Microsoft_NP1 decision_NN1 ._. 
</s>
<s>
Due_II21 to_II22 the_AT case_NN1 by_II case_NN1 definition_NN1 of_IO these_DD2 exceptional_JJ circumstances_NN2 ,_, the_AT situation_NN1 is_VBZ somewhat_RR unclear_JJ for_IF the_AT companies_NN2 operating_VVG in_II the_AT market_NN1 ._. 
</s>
<s>
On_II one_MC1 hand_NN1 ,_, the_AT companies_NN2 should_VM protect_VVI their_APPGE innovations_NN2 with_IW intellectual_JJ property_NN1 rights_NN2 and_CC use_VV0 those_DD2 for_IF gaining_VVG economic_JJ interest_NN1 ._. 
</s>
<s>
The_AT owner_NN1 of_IO the_AT intellectual_JJ property_NN1 right_NN1 should_VM have_VHI a_AT1 reasonable_JJ scope_NN1 for_IF the_AT right_NN1 ;_; the_AT owner_NN1 should_VM have_VHI an_AT1 advantage_NN1 ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 ,_, the_AT companies_NN2 should_VM be_VBI able_JK to_TO take_VVI into_II account_NN1 the_AT rules_NN2 of_IO competition_NN1 law_NN1 and_CC act_VV0 accordingly_RR ._. 
</s>
<s>
On_II that_DD1 account_NN1 ,_, a_AT1 balance_NN1 between_II these_DD2 interests_NN2 needs_VVZ to_TO be_VBI found_VVN ._. 
</s>
<s>
A_AT1 danger_NN1 is_VBZ that_DD1 competition_NN1 law_NN1 affects_VVZ intellectual_JJ property_NN1 rights_NN2 in_II a_AT1 way_NN1 that_CST might_VM inhibit_VVI innovation_NN1 ._. 
</s>
<s>
Already_RR the_AT rights_NN2 of_IO the_AT owners_NN2 of_IO intellectual_JJ property_NN1 law_NN1 have_VH0 been_VBN shaped_VVN (_( mostly_RR limited_VVN )_) to_II a_AT1 great_JJ degree_NN1 by_II competition_NN1 law_NN1 ._. 
</s>
<s>
By_II fulfilling_VVG the_AT competing_JJ interests_NN2 ,_, the_AT market_NN1 could_VM work_VVI effectively_RR and_CC the_AT incentive_NN1 to_TO innovate_VVI would_VM exist_VVI ._. 
</s>
<s>
Accordingly_RR ,_, currently_RR the_AT courts_NN2 do_VD0 the_AT evaluation_NN1 between_II these_DD2 interests_NN2 ._. 
</s>
<s>
In_II my_APPGE opinion_NN1 ,_, it_PPH1 is_VBZ economically_RR efficient_JJ to_TO do_VDI the_AT evaluation_NN1 in_II these_DD2 matters_NN2 case-by-case_NN1 ,_, taking_VVG into_II account_NN1 the_AT specific_JJ features_NN2 of_IO each_DD1 case_NN1 although_CS this_DD1 causes_VVZ some_DD uncertainty_NN1 in_II the_AT market_NN1 ._. 
</s>
<s>
Strict_JJ rules_NN2 might_VM not_XX be_VBI the_AT right_JJ tool_NN1 for_IF guiding_JJ companies_NN2 in_II their_APPGE market_NN1 behavior_NN1 as_II the_AT markets_NN2 are_VBR constantly_RR changing_VVG and_CC general_JJ technological_JJ development_NN1 goes_VVZ further_RRR and_CC further_RRR ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, as_CSA the_AT decisions_NN2 of_IO the_AT courts_NN2 have_VH0 significant_JJ effects_NN2 on_II the_AT market_NN1 ,_, the_AT efficient_JJ evaluation_NN1 of_IO the_AT facts_NN2 in_II the_AT cases_NN2 by_II courts_NN2 needs_VVZ not_XX only_JJ expertise_NN1 in_II legal_JJ issues_NN2 ,_, but_CCB also_RR in_II economic_JJ issues_NN2 ._. 
</s>
<s>
Idealistically_RR ,_, the_AT decisions_NN2 in_II these_DD2 cases_NN2 should_VM be_VBI legally_RR and_CC economically_RR sustainable_JJ ._. 
</s>
<s>
In_II my_APPGE opinion_NN1 ,_, the_AT economic_JJ aspect_NN1 and_CC especially_RR the_AT economic_JJ effects_NN2 on_II the_AT companies_NN2 in_II the_AT cases_NN2 should_VM be_VBI emphasized_VVN more_RRR ._. 
</s>
