<s>
Drivers_NN2 and_CC Barriers_NN2 for_IF Finnish_JJ businesses_NN2 to_TO go_VVI green_NN1 1_MC1 ._. 
</s>
<s>
Introduction_NN1 Environmental_JJ issues_NN2 are_VBR have_VH0 been_VBN researched_VVN in_II recent_JJ years_NNT2 by_II both_DB2 scholars_NN2 (_( Kovcs_NN2 2008_MC ;_; Walker_NP1 ,_, Di_NP1 Sisto_NP1 &;_NULL McBain_NP1 2008_MC ;_; Mont_NP1 &Leire;_NULL 2009_MC )_) and_CC companies_NN2 (_( BearingPoint_NP1 2008_MC )_) ._. 
</s>
<s>
Companies_NN2 try_VV0 to_TO be_VBI more_RGR socially_RR responsible_JJ ,_, and_CC through_II this_DD1 companies_VVZ also_RR try_VV0 to_TO act_VVI in_II a_AT1 more_RGR environmentally_RR friendly_JJ way_NN1 ._. 
</s>
<s>
Part_NN1 of_IO corporate_JJ social_JJ responsibility_NN1 (_( CSR_NP1 )_) is_VBZ corporate_JJ environmental_JJ responsibility_NN1 (_( CER_NP1 )_) ._. 
</s>
<s>
CER_NP1 includes_VVZ stronger_JJR interaction_NN1 between_II companies_NN2 and_CC their_APPGE environment_NN1 ,_, the_AT media_NN ,_, the_AT industry_NN1 associations_NN2 ,_, the_AT companys_NN2 own_DA supply_NN1 chain_NN1 with_IW all_DB of_IO its_APPGE suppliers_NN2 and_CC customers_NN2 and_CC policy_NN1 makers_NN2 ._. 
</s>
<s>
(_( Kovcs_NP1 2008_MC )_) Consumers_NN2 and_CC customers_NN2 of_IO the_AT company_NN1 are_VBR believed_VVN to_TO have_VHI the_AT greatest_JJT influence_NN1 for_IF companies_NN2 to_TO become_VVI more_RGR environmentally_RR aware_JJ (_( Walker_NP1 ,_, Di_NP1 Sisto_NP1 &;_NULL McBain_NP1 2008_MC )_) ._. 
</s>
<s>
Climate_NN1 change_NN1 is_VBZ seen_VVN as_II a_AT1 real_JJ threat_NN1 and_CC companies_NN2 who_PNQS market_VV0 themselves_PPX2 as_CSA environmentally_RR friendly_JJ tend_VV0 to_TO attract_VVI environmentally_RR aware_JJ consumers_NN2 ._. 
</s>
<s>
One_MC1 way_NN1 of_IO becoming_VVG more_RGR environmentally_RR friendly_JJ is_VBZ to_TO change_VVI the_AT supply_NN1 chain_NN1 to_II a_AT1 green_JJ supply_NN1 chain_NN1 ._. 
</s>
<s>
BearingPoint_NP1 (_( 2008_MC ;_; p._NN1 3_MC )_) defines_VVZ a_AT1 Green_JJ Supply_NN1 Chain_NN1 as_II :_: A_AT1 process_NN1 in_II which_DDQ the_AT total_JJ environmental_JJ impact_NN1 generated_VVN throughout_II the_AT lifecycle_NN1 of_IO a_AT1 product_NN1 or_CC service_NN1 is_VBZ measured_VVN and_CC systematically_RR reviewed_VVN against_II targets_NN2 ,_, with_IW appropriate_JJ actions_NN2 being_VBG taken_VVN to_TO continuously_RR reduce_VVI the_AT environmental_JJ consequences_NN2 ._. 
</s>
<s>
Green_JJ supply_NN1 chains_NN2 tend_VV0 to_TO have_VHI reduced_VVN packaging_NN1 and_CC waste_NN1 and_CC they_PPHS2 also_RR continuously_RR asses_VV0 their_APPGE suppliers_NN2 and_CC vendors_NN2 on_II their_APPGE environmental_JJ performance_NN1 ._. 
</s>
<s>
Green_JJ supply_NN1 chains_NN2 may_VM also_RR include_VVI development_NN1 of_IO more_RGR eco-friendly_JJ products_NN2 which_DDQ reduce_VV0 carbon_NN1 emissions_NN2 ,_, or_CC reduce_VV0 carbon_NN1 emissions_NN2 associated_VVN with_IW transport_NN1 of_IO goods_NN2 ._. 
</s>
<s>
(_( Walker_NP1 ,_, Di_NP1 Sisto_NP1 &;_NULL McBain_NP1 2008_MC )_) It_PPH1 can_VM ,_, however_RR ,_, be_VBI difficult_JJ for_IF companies_NN2 to_TO make_VVI sure_JJ that_CST their_APPGE supply_NN1 chains_NN2 are_VBR green_JJ from_II beginning_NN1 to_II end_NN1 ,_, as_CSA supply_NN1 chains_NN2 in_II the_AT world_NN1 today_RT have_VH0 grown_VVN bigger_JJR than_CSN they_PPHS2 were_VBDR before_II the_AT industrialization_NN1 ._. 
</s>
<s>
Kovcs_NN2 (_( 2008_MC )_) points_VVZ out_RP that_DD1 research_NN1 has_VHZ a_AT1 tendency_NN1 to_TO focus_VVI on_II the_AT focal_JJ company_NN1 and_CC the_AT immediate_JJ suppliers_NN2 and_CC distributors_NN2 ._. 
</s>
<s>
Companies_NN2 have_VH0 to_TO know_VVI all_DB of_IO their_APPGE suppliers_NN2 and_CC the_AT suppliers_NN2 suppliers_NN2 and_CC they_PPHS2 also_RR have_VH0 to_TO know_VVI their_APPGE distributors_NN2 and_CC buyers_NN2 in_BCL21 order_BCL22 to_TO make_VVI sure_JJ that_CST the_AT whole_JJ supply_NN1 chain_NN1 is_VBZ and_CC stays_VVZ green_JJ (_( BearingPoint_NP1 2008_MC )_) ._. 
</s>
<s>
The_AT research_NN1 paper_NN1 will_VM start_VVI with_IW a_AT1 literature_NN1 review_NN1 of_IO green_JJ supply_NN1 chains_NN2 and_CC corporate_JJ environmental_JJ responsibility_NN1 ._. 
</s>
<s>
Drivers_NN2 and_CC barriers_NN2 will_VM be_VBI identified_VVN in_II the_AT green_JJ supply_NN1 chain_NN1 context_NN1 ._. 
</s>
<s>
The_AT methodology_NN1 will_VM be_VBI presented_VVN after_II the_AT identification_NN1 of_IO drivers_NN2 and_CC barriers_NN2 ._. 
</s>
<s>
After_CS that_CST an_AT1 analysis_NN1 is_VBZ made_VVN by_II how_RRQ the_AT drivers_NN2 and_CC barriers_NN2 are_VBR perceived_VVN by_II the_AT Finnish_JJ industry_NN1 ._. 
</s>
<s>
The_AT research_NN1 paper_NN1 will_VM end_VVI in_II a_AT1 conclusion_NN1 about_II the_AT drivers_NN2 and_CC barriers_NN2 ,_, the_AT conclusion_NN1 will_VM include_VVI both_DB2 limitations_NN2 of_IO the_AT research_NN1 and_CC suggestions_NN2 for_IF future_JJ research_NN1 ._. 
</s>
<s>
2_MC ._. 
</s>
<s>
Green_JJ supply_NN1 chain_NN1 A_ZZ1 typical_JJ supply_NN1 chain_NN1 considers_VVZ a_AT1 supply_NN1 chain_NN1 from_II the_AT raw_JJ material_NN1 to_II manufacturing_NN1 and_CC from_II manufacturing_NN1 to_II the_AT distribution_NN1 to_II the_AT consumer_NN1 ._. 
</s>
<s>
A_AT1 green_JJ supply_NN1 chain_NN1 ,_, also_RR called_VVN the_AT extended_JJ supply_NN1 chain_NN1 ,_, includes_VVZ to_II this_DD1 the_AT reverse_JJ chain_NN1 that_CST brings_VVZ the_AT product_NN1 backward_RL in_II the_AT chain_NN1 to_II being_VBG remanufactured_VVN ,_, re-used_JJ or_CC recycled_JJ ._. 
</s>
<s>
The_AT green_JJ supply_NN1 chain_NN1 considers_VVZ a_AT1 products_NN2 whole_JJ life_NN1 cycle_NN1 ._. 
</s>
<s>
(_( Beamon_NN1 1999_MC ;_; Bearing_VVG Point_NN1 2008_MC )_) The_AT green_JJ supply_NN1 chain_NN1 thinking_NN1 has_VHZ grown_VVN first_MD from_II businesses_NN2 changing_VVG their_APPGE supply_NN1 chains_NN2 to_II more_RGR environmentally_RR friendly_JJ because_II21 of_II22 regulations_NN2 or_CC legislation_NN1 ._. 
</s>
<s>
The_AT next_MD step_NN1 for_IF businesses_NN2 was_VBDZ to_TO coordinate_VVI and_CC integrate_VVI the_AT environmental_JJ aspects_NN2 to_II their_APPGE supply_NN1 chains_NN2 ._. 
</s>
<s>
The_AT third_MD step_NN1 for_IF businesses_NN2 has_VHZ been_VBN to_TO make_VVI proactive_JJ plans_NN2 to_TO guard_VVI themselves_PPX2 against_II environmental_JJ liabilities_NN2 ,_, like_II managing_VVG their_APPGE pollution_NN1 on_II a_AT1 level_NN1 that_CST is_VBZ accepted_VVN by_II law_NN1 ._. 
</s>
<s>
The_AT three_MC first_MD steps_NN2 follow_VV0 the_AT first_MD stage_NN1 in_II the_AT evolution_NN1 of_IO environment_NN1 management_NN1 ,_, which_DDQ is_VBZ risk_NN1 management_NN1 and_CC includes_VVZ waste_JJ management_NN1 and_CC pollution_NN1 control_NN1 ._. 
</s>
<s>
This_DD1 first_MD stage_NN1 had_VHD its_APPGE start_NN1 in_II the_AT 1970s_MC2 ._. 
</s>
<s>
The_AT fourth_MD step_NN1 already_RR includes_VVZ that_CST the_AT businesses_NN2 try_VV0 to_TO prevent_VVI pollution_NN1 instead_II21 of_II22 only_RR controlling_VVG it_PPH1 and_CC keeping_VVG it_PPH1 on_II an_AT1 accepted_JJ level_NN1 ._. 
</s>
<s>
The_AT step_NN1 also_RR includes_VVZ waste_JJ minimization_NN1 ,_, which_DDQ follows_VVZ the_AT second_MD stage_NN1 in_II the_AT evolution_NN1 of_IO environment_NN1 management_NN1 ._. 
</s>
<s>
The_AT second_MD stage_NN1 in_II the_AT evolution_NN1 began_VVD in_II the_AT middle_NN1 of_IO the_AT 1980s_MC2 ._. 
</s>
<s>
In_II the_AT last_MD step_NN1 businesses_NN2 have_VH0 a_AT1 global_JJ concern_NN1 about_II the_AT entire_JJ product_NN1 life_NN1 cycle_NN1 and_CC also_RR view_VV0 the_AT environmental_JJ quality_NN1 as_II part_NN1 of_IO the_AT Total_JJ Quality_NN1 Management_NN1 of_IO the_AT business_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ also_RR supported_VVN by_II the_AT last_MD stage_NN1 in_II the_AT evolution_NN1 of_IO environmental_JJ management_NN1 which_DDQ has_VHZ begun_VVN in_II the_AT middle_NN1 of_IO the_AT 1990s_MC2 ._. 
</s>
<s>
(_( Beamon_NN1 1999_MC )_) The_AT green_JJ supply_NN1 chain_NN1 is_VBZ a_AT1 semi-closed_JJ loop_NN1 ,_, where_CS the_AT whole_JJ life_NN1 cycle_NN1 of_IO a_AT1 product_NN1 is_VBZ considered_VVN ._. 
</s>
<s>
The_AT product_NN1 first_MD makes_VVZ its_APPGE way_NN1 through_II production_NN1 and_CC is_VBZ distributed_VVN to_II consumers_NN2 ._. 
</s>
<s>
The_AT consumer_NN1 has_VHZ then_RT a_AT1 responsibility_NN1 to_TO take_VVI the_AT used_JJ product_NN1 to_II collection_NN1 stations_NN2 which_DDQ should_VM be_VBI provided_VVN by_II the_AT businesses_NN2 either_RR as_II part_NN1 of_IO their_APPGE own_DA operations_NN2 or_CC as_II an_AT1 outsourced_JJ part_NN1 of_IO the_AT business_NN1 ._. 
</s>
<s>
From_II the_AT collection_NN1 stations_NN2 the_AT used_JJ products_NN2 are_VBR shipped_VVN back_RP to_II the_AT manufacturer_NN1 who_PNQS then_RT decides_VVZ whether_CSW to_TO remanufacture_VVI ,_, re-use_VV0 or_CC recycle_VV0 the_AT product_NN1 ._. 
</s>
<s>
(_( Beamon_NN1 1999_MC ;_; BearingPoint_NP1 2008_MC ;_; Kovcs_NN2 2008_MC )_) In_BCL21 order_BCL22 for_IF a_AT1 supply_NN1 chain_NN1 to_TO be_VBI green_JJ the_AT suppliers_NN2 need_VV0 to_TO be_VBI assessed_VVN as_RR21 well_RR22 ._. 
</s>
<s>
The_AT suppliers_NN2 need_VV0 to_TO be_VBI environmentally_RR aware_JJ ,_, but_CCB it_PPH1 depends_VVZ on_II how_RGQ critical_JJ the_AT supplier_NN1 is_VBZ for_IF the_AT focal_JJ company_NN1 ,_, how_RRQ the_AT supplier_NN1 is_VBZ assessed_VVN ._. 
</s>
<s>
(_( Hamner_NN1 2006_MC )_) A_ZZ1 critical_JJ supplier_NN1 may_VM be_VBI audited_VVN several_DA2 times_NNT2 in_II a_AT1 year_NNT1 when_RRQ a_AT1 less_RGR critical_JJ supplier_NN1 may_VM only_RR be_VBI assessed_VVN by_II their_APPGE environmental_JJ reputation_NN1 ._. 
</s>
<s>
Some_DD businesses_NN2 collaborate_VV0 with_IW their_APPGE most_RGT critical_JJ suppliers_NN2 in_II finding_VVG new_JJ environmentally_RR friendly_JJ technology_NN1 ._. 
</s>
<s>
(_( Kovcs_NP1 2008_MC )_) 3_MC ._. 
</s>
<s>
Drivers_NN2 and_CC Barriers_NN2 In_II this_DD1 chapter_NN1 the_AT drivers_NN2 and_CC barriers_NN2 for_IF businesses_NN2 to_TO change_VVI their_APPGE supply_NN1 chains_NN2 to_II green_JJ supply_NN1 chains_NN2 will_VM be_VBI identified_VVN ._. 
</s>
<s>
The_AT drivers_NN2 and_CC barriers_NN2 will_VM be_VBI presented_VVN from_II both_RR an_AT1 external_JJ view_NN1 and_CC from_II an_AT1 internal_JJ view_NN1 ._. 
</s>
<s>
The_AT drivers_NN2 will_VM be_VBI presented_VVN first_MD and_CC the_AT barriers_NN2 will_VM follow_VVI after_II that_DD1 ._. 
</s>
<s>
3.1_MC ._. 
</s>
<s>
External_JJ drivers_NN2 External_JJ drivers_NN2 are_VBR in_II some_DD cases_NN2 a_AT1 result_NN1 of_IO stakeholder_NN1 pressure_NN1 and_CC in_II other_JJ cases_NN2 it_PPH1 is_VBZ an_AT1 issue_NN1 of_IO regulations_NN2 (_( Mont_NP1 &;_NULL Leire_NP1 2009_MC )_) ._. 
</s>
<s>
The_AT different_JJ stakeholders_NN2 can_VM be_VBI customers_NN2 ,_, competitors_NN2 ,_, society_NN1 and_CC suppliers_NN2 (_( Walker_NP1 ,_, Di_NP1 Sisto_NP1 &;_NULL McBain_NP1 2008_MC ;_; Mont_NP1 &;_NULL Leire_NP1 2009_MC )_) ._. 
</s>
<s>
State_VV0 legislation_NN1 and_CC regulation_NN1 is_VBZ probably_RR the_AT first_MD driver_NN1 for_IF businesses_NN2 to_TO become_VVI more_RGR environmentally_RR aware_JJ ._. 
</s>
<s>
State_VV0 legislation_NN1 have_VH0 become_VVN in_II recent_JJ years_NNT2 stricter_JJR when_CS it_PPH1 comes_VVZ to_II environmental_JJ issues_NN2 ,_, the_AT latest_JJT in_II the_AT European_JJ union_NN1 is_VBZ the_AT sulfur_NN1 directive_NN1 which_DDQ states_VVZ that_CST the_AT ships_NN2 that_CST sail_VV0 on_II the_AT European_JJ waters_NN2 are_VBR only_RR allowed_VVN to_TO have_VHI a_AT1 0.1_MC percent_NNU sulfur_NN1 content_NN1 in_II fuel_NN1 as_II21 of_II22 2015_MC (_( Council_NN1 of_IO the_AT European_JJ Union_NN1 2012_MC )_) ._. 
</s>
<s>
Regulation_NN1 drives_VVZ companies_NN2 to_TO become_VVI more_RGR environmentally_RR friendly_JJ ,_, but_CCB it_PPH1 is_VBZ only_RR the_AT first_MD step_NN1 ._. 
</s>
<s>
Businesses_NN2 also_RR need_VV0 to_TO be_VBI motivated_VVN to_TO change_VVI their_APPGE supply_NN1 chains_NN2 in_II other_JJ ways_NN2 ,_, such_II21 as_II22 in_II hopes_NN2 of_IO having_VHG monetary_JJ benefits_NN2 from_II it_PPH1 (_( Walker_NP1 ,_, Di_NP1 Sisto_NP1 &;_NULL McBain_NP1 2008_MC )_) ._. 
</s>
<s>
Customers_NN2 can_VM be_VBI very_RG strong_JJ drivers_NN2 for_IF businesses_NN2 to_TO change_VVI their_APPGE supply_NN1 chains_NN2 to_II more_RGR green_JJ ._. 
</s>
<s>
For_REX21 example_REX22 customers_NN2 can_VM chose_VVD not_XX to_TO buy_VVI a_AT1 product_NN1 if_CS they_PPHS2 believe_VV0 that_CST there_EX is_VBZ a_AT1 similar_JJ product_NN1 on_II the_AT market_NN1 that_CST is_VBZ manufactured_VVN in_II a_AT1 greener_JJR way_NN1 ._. 
</s>
<s>
Customers_NN2 can_VM be_VBI driven_VVN by_II the_AT end_NN1 consumers_NN2 who_PNQS demand_VV0 products_NN2 to_TO be_VBI greener_JJR ,_, and_CC when_CS the_AT customers_NN2 see_VV0 that_CST the_AT end_NN1 consumer_NN1 is_VBZ getting_VVG more_RGR environmentally_RR aware_JJ ,_, they_PPHS2 in_II turn_NN1 ask_VV0 businesses_NN2 that_CST provide_VV0 them_PPHO2 with_IW products_NN2 to_TO become_VVI more_RGR environmentally_RR friendly_JJ ._. 
</s>
<s>
(_( Walker_NP1 ,_, Di_NP1 Sisto_NP1 &;_NULL McBain_NP1 2008_MC )_) Competitors_NN2 may_VM drive_VVI businesses_NN2 to_TO become_VVI more_RGR environmentally_RR friendly_JJ by_II setting_VVG new_JJ norms_NN2 in_II an_AT1 industry_NN1 ._. 
</s>
<s>
Competitors_NN2 may_VM also_RR drive_VVI businesses_NN2 to_TO strive_VVI after_II first_MD mover_NN1 advantage_NN1 ,_, and_CC in_II this_DD1 way_NN1 try_VV0 to_TO find_VVI new_JJ more_RGR environmentally_RR friendly_JJ parts_NN2 to_II their_APPGE supply_NN1 chain_NN1 ._. 
</s>
<s>
This_DD1 will_VM also_RR help_VVI businesses_NN2 gain_VVI competitive_JJ advantage_NN1 ._. 
</s>
<s>
By_II being_VBG more_RGR environmentally_RR friendly_JJ businesses_NN2 can_VM reduce_VVI waste_NN1 and_CC be_VBI leaner_JJR ,_, which_DDQ in_II turn_NN1 will_VM show_VVI as_CSA improvements_NN2 in_II a_AT1 business_NN1 performance_NN1 ._. 
</s>
<s>
(_( Walker_NP1 ,_, Di_NP1 Sisto_NP1 &;_NULL McBain_NP1 2008_MC ;_; Mont_NP1 &;_NULL Leire_NP1 2009_MC )_) Media_NN and_CC society_NN1 have_VH0 a_AT1 big_JJ say_VV0 in_II businesses_NN2 attempts_VVZ to_TO become_VVI environmentally_RR friendly_JJ ._. 
</s>
<s>
Media_NN will_VM make_VVI people_NN more_RGR aware_JJ of_IO environmental_JJ and_CC societal_JJ issues_NN2 ,_, and_CC this_DD1 can_VM affect_VVI a_AT1 business_NN1 in_II a_AT1 negative_JJ way_NN1 ._. 
</s>
<s>
Businesses_NN2 are_VBR then_RT driven_VVN by_II society_NN1 to_TO make_VVI environmentally_RR friendly_JJ decisions_NN2 ,_, and_CC gain_VVI a_AT1 reputation_NN1 of_IO being_VBG environmentally_RR friendly_JJ ._. 
</s>
<s>
By_II having_VHG a_AT1 good_JJ reputation_NN1 ,_, people_NN who_PNQS have_VH0 become_VVN more_RGR aware_JJ of_IO environmental_JJ issues_NN2 ,_, will_VM consume_VVI the_AT businesses_NN2 products_NN2 ._. 
</s>
<s>
(_( Walker_NP1 ,_, Di_NP1 Sisto_NP1 &;_NULL McBain_NP1 2008_MC ;_; Mont_NP1 &;_NULL Leire_NP1 2009_MC )_) Suppliers_NN2 rarely_RR act_VV0 as_II a_AT1 driving_JJ force_NN1 ,_, but_CCB as_CSA the_AT environment_NN1 is_VBZ getting_VVG more_DAR attention_NN1 suppliers_NN2 need_VV0 to_TO cooperate_VVI with_IW businesses_NN2 so_CS21 that_CS22 they_PPHS2 both_DB2 become_VV0 more_RGR environmentally_RR friendly_JJ (_( Walker_NP1 ,_, Di_NP1 Sisto_NP1 &;_NULL McBain_NP1 2008_MC )_) ._. 
</s>
<s>
Businesses_NN2 that_CST intend_VV0 to_TO be_VBI greener_JJR should_VM be_VBI driven_VVN to_TO find_VVI suppliers_NN2 that_CST have_VH0 the_AT same_DA agenda_NN1 ._. 
</s>
<s>
3.2_MC ._. 
</s>
<s>
Internal_JJ drivers_NN2 Internal_JJ drivers_NN2 often_RR relate_VV0 to_II employees_NN2 concerns_VVZ about_II the_AT environment_NN1 or_CC the_AT working_JJ conditions_NN2 of_IO the_AT people_NN who_PNQS make_VV0 the_AT businesses_NN2 products_NN2 in_II different_JJ countries_NN2 (_( Mont_NP1 &;_NULL Leire_NP1 2009_MC )_) ._. 
</s>
<s>
Other_JJ internal_JJ drivers_NN2 stem_VV0 from_II other_JJ organizational_JJ factors_NN2 ,_, such_II21 as_II22 investor_NN1 pressure_NN1 and_CC policy_NN1 entrepreneurs_NN2 (_( Walker_NP1 ,_, Di_NP1 Sisto_NP1 &;_NULL McBain_NP1 2008_MC )_) ._. 
</s>
<s>
Investor_NN1 pressure_NN1 can_VM partly_RR be_VBI motivated_VVN with_IW investors_NN2 being_VBG environmentally_RR aware_JJ ._. 
</s>
<s>
Investors_NN2 may_VM also_RR be_VBI aware_JJ that_CST reducing_JJ waste_NN1 will_VM result_VVI in_II reduced_JJ costs_NN2 (_( Walker_NP1 ,_, Di_NP1 Sisto_NP1 &;_NULL McBain_NP1 2008_MC )_) ,_, and_CC by_II showing_VVG that_CST the_AT business_NN1 is_VBZ concerned_JJ about_II the_AT working_JJ conditions_NN2 and_CC actively_RR trying_VVG to_TO improve_VVI them_PPHO2 ,_, consumers_NN2 start_VV0 to_TO demand_VVI products_NN2 from_II this_DD1 company_NN1 (_( Mont_NP1 &;_NULL Leire_NP1 2009_MC )_) ._. 
</s>
<s>
Policy_NN1 entrepreneurs_NN2 are_VBR employees_NN2 of_IO the_AT business_NN1 that_CST make_VV0 it_PPH1 their_APPGE mission_NN1 to_TO get_VVI the_AT business_NN1 more_RGR involved_JJ in_II environmental_JJ and_CC social_JJ issues_NN2 ._. 
</s>
<s>
The_AT policy_NN1 entrepreneur_NN1 can_VM either_RR be_VBI driven_VVN by_II the_AT wish_NN1 to_TO make_VVI the_AT world_NN1 a_AT1 better_JJR place_NN1 but_CCB also_RR by_II the_AT wish_NN1 that_CST they_PPHS2 make_VV0 themselves_PPX2 valuable_JJ to_II the_AT business_NN1 and_CC improve_VV0 their_APPGE position_NN1 in_II this_DD1 way_NN1 in_II the_AT company_NN1 ._. 
</s>
<s>
(_( Walker_NP1 ,_, Di_NP1 Sisto_NP1 &;_NULL McBain_NP1 2008_MC )_) Other_JJ internal_JJ driver_NN1 can_VM be_VBI a_AT1 desire_NN1 to_TO improve_VVI quality_NN1 by_II reducing_VVG waste_NN1 and_CC cost_NN1 ,_, values_NN2 that_CST the_AT founders_NN2 are_VBR instigating_VVG or_CC that_CST the_AT owners_NN2 wish_VV0 to_TO initiate_VVI ._. 
</s>
<s>
By_II improving_JJ quality_NN1 consumers_NN2 get_VV0 a_AT1 better_JJR product_NN1 that_CST is_VBZ also_RR greener_JJR as_II the_AT quality_NN1 improvement_NN1 can_VM be_VBI a_AT1 result_NN1 of_IO reducing_VVG waste_NN1 ._. 
</s>
<s>
As_II the_AT waste_NN1 is_VBZ reduced_VVN the_AT business_NN1 reduces_VVZ costs_NN2 that_CST are_VBR related_VVN to_TO waste_VVI management_NN1 and_CC also_RR material_JJ cost_NN1 ._. 
</s>
<s>
(_( Walker_NP1 ,_, Di_NP1 Sisto_NP1 &;_NULL McBain_NP1 2008_MC )_) 3.3_MC ._. 
</s>
<s>
External_JJ barriers_NN2 Regulation_NN1 may_VM act_VVI as_II a_AT1 barrier_NN1 as_II31 well_II32 as_II33 a_AT1 driver_NN1 ._. 
</s>
<s>
Because_II21 of_II22 regulation_NN1 innovation_NN1 may_VM be_VBI inhibited_VVN ,_, as_CSA legislation_NN1 can_VM state_VVI deadlines_NN2 that_CST can_VM be_VBI unreasonable_JJ for_IF companies_NN2 to_TO reach_VVI or_CC the_AT legislation_NN1 or_CC regulation_NN1 can_VM state_VVI which_DDQ technique_NN1 is_VBZ the_AT best_JJT one_PN1 available_JJ ,_, that_CST companies_NN2 now_RT have_VH0 to_TO use_VVI ._. 
</s>
<s>
This_DD1 means_VVZ that_CST companies_NN2 are_VBR not_XX allowed_VVN to_TO be_VBI innovative_JJ or_CC do_VD0 not_XX have_VHI enough_DD time_NNT1 to_TO invent_VVI new_JJ techniques_NN2 that_CST might_VM be_VBI even_RR better_RRR than_CSN the_AT current_JJ best_JJT technique_NN1 ._. 
</s>
<s>
(_( Walker_NP1 ,_, Di_NP1 Sisto_NP1 &;_NULL McBain_NP1 2008_MC )_) Legislation_NN1 may_VM also_RR be_VBI unclear_JJ in_II how_RRQ it_PPH1 should_VM be_VBI integrated_VVN in_II the_AT supply_NN1 chain_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ a_AT1 barrier_NN1 as_CSA companies_NN2 now_RT are_VBR unsure_JJ of_IO what_DDQ they_PPHS2 should_VM do_VDI ,_, and_CC might_VM not_XX make_VVI deadlines_NN2 or_CC be_VBI unaware_JJ of_IO how_RRQ the_AT legislation_NN1 is_VBZ related_VVN to_II their_APPGE supply_NN1 chain_NN1 ._. 
</s>
<s>
(_( Mont_NP1 &;_NULL Leire_NP1 2009_MC )_) Different_JJ industries_NN2 may_VM have_VHI different_JJ barriers_NN2 ._. 
</s>
<s>
They_PPHS2 can_VM be_VBI related_VVN to_II legislation_NN1 that_CST is_VBZ different_JJ for_IF the_AT businesses_NN2 country_NN1 and_CC the_AT supplier_NN1 country_NN1 (_( Mont_NP1 &;_NULL Leire_NP1 2009_MC )_) ._. 
</s>
<s>
Industries_NN2 may_VM also_RR have_VHI specific_JJ requirements_NN2 or_CC barriers_NN2 that_CST inhibit_VV0 businesses_NN2 to_TO be_VBI environmentally_RR aware_JJ ._. 
</s>
<s>
The_AT industry_NN1 specific_JJ barriers_NN2 can_VM affect_VVI different_JJ sectors_NN2 in_II ether_NN1 being_VBG proactive_JJ of_IO reactive_JJ when_CS it_PPH1 comes_VVZ to_II environmental_JJ issues_NN2 ._. 
</s>
<s>
(_( Walker_NP1 ,_, DiSisto_NP1 &;_NULL MvBain_NN1 2008_MC )_) Another_DD1 external_JJ barrier_NN1 relates_VVZ to_II suppliers_NN2 ._. 
</s>
<s>
Suppliers_NN2 may_VM not_XX be_VBI committed_VVN to_II the_AT environmental_JJ strategy_NN1 that_CST the_AT business_NN1 and_CC supplier_NN1 have_VH0 decided_VVN to_TO follow_VVI ._. 
</s>
<s>
Also_RR different_JJ management_NN1 styles_NN2 between_II supplier_NN1 and_CC the_AT business_NN1 can_VM be_VBI a_AT1 barrier_NN1 as_CSA this_DD1 can_VM result_VVI to_II difficulties_NN2 in_II cooperation_NN1 and_CC lack_NN1 of_IO commitment_NN1 in_II joint_JJ operations_NN2 ._. 
</s>
<s>
(_( Walker_NP1 ,_, Di_NP1 Sisto_NP1 &;_NULL McBain_NP1 2008_MC ;_; Mont_NP1 &;_NULL Leire_NP1 2009_MC )_) Suppliers_NN2 in_II other_JJ countries_NN2 may_VM have_VHI different_JJ legislation_NN1 than_CSN that_DD1 of_IO the_AT focal_JJ business_NN1 ,_, which_DDQ means_VVZ the_AT if_CS the_AT legislation_NN1 is_VBZ less_RGR strict_JJ when_CS it_PPH1 comes_VVZ to_II environmental_JJ issues_NN2 the_AT supplier_NN1 may_VM not_XX be_VBI willing_JJ to_TO commit_VVI to_II the_AT same_DA degree_NN1 as_CSA the_AT focal_JJ business_NN1 ,_, because_CS they_PPHS2 might_VM not_XX see_VVI any_DD cost_NN1 reductions_NN2 or_CC other_JJ positive_JJ drivers_NN2 to_TO be_VBI more_RRR committed_VVN to_II the_AT environmental_JJ strategy_NN1 of_IO the_AT focal_JJ business_NN1 (_( Mont_NP1 &;_NULL Leire_NP1 2009_MC )_) ._. 
</s>
<s>
Suppliers_NN2 also_RR need_VV0 to_TO be_VBI audited_VVN in_BCL21 order_BCL22 for_IF the_AT focal_JJ business_NN1 to_TO be_VBI sure_JJ of_IO the_AT commitment_NN1 ._. 
</s>
<s>
Suppliers_NN2 may_VM be_VBI unwilling_JJ to_TO share_VVI information_NN1 ,_, as_CSA they_PPHS2 may_VM be_VBI afraid_JJ of_IO showing_VVG weaknesses_NN2 or_CC giving_VVG away_RL information_NN1 that_CST will_VM lead_VVI to_II other_JJ companies_NN2 gaining_VVG competitive_JJ advantage_NN1 ._. 
</s>
<s>
Auditing_VVG the_AT suppliers_NN2 may_VM also_RR be_VBI difficult_JJ if_CS the_AT supplier_NN1 is_VBZ cheating_VVG by_II having_VHG double_JJ bookkeeping_NN1 or_CC if_CS the_AT quality_NN1 of_IO the_AT auditing_NN1 is_VBZ poor_JJ ._. 
</s>
<s>
The_AT auditing_NN1 may_VM be_VBI poor_JJ because_II21 of_II22 high_JJ competition_NN1 and_CC the_AT focal_JJ businesses_NN2 wish_VV0 to_TO save_VVI money_NN1 and_CC by_II choosing_VVG a_AT1 auditing_NN1 company_NN1 that_CST has_VHZ the_AT lowest_JJT price_NN1 ._. 
</s>
<s>
(_( Walker_NP1 ,_, Di_NP1 Sisto_NP1 &;_NULL McBain_NP1 2008_MC ;_; Mont_NP1 &;_NULL Leire_NP1 2009_MC )_) 3.4_MC ._. 
</s>
<s>
Internal_JJ barriers_NN2 Costs_NN2 may_VM be_VBI high_JJ in_II the_AT beginning_NN1 of_IO implementing_VVG environmental_JJ supply_NN1 chain_NN1 thinking_VVG in_II a_AT1 business_NN1 ._. 
</s>
<s>
Changing_JJ suppliers_NN2 may_VM be_VBI expensive_JJ ,_, as_CSA there_EX is_VBZ a_AT1 learning_NN1 process_NN1 with_IW new_JJ suppliers_NN2 ,_, and_CC also_RR a_AT1 supplier_NN1 with_IW an_AT1 already_RR existing_JJ environmental_JJ strategy_NN1 might_VM be_VBI more_RGR expensive_JJ than_CSN one_PN1 without_RL ._. 
</s>
<s>
Management_NN1 might_VM only_RR see_VVI the_AT cost_NN1 aspect_NN1 in_II changing_JJ strategy_NN1 to_II a_AT1 more_RGR environmental_JJ friendly_JJ one_PN1 ._. 
</s>
<s>
This_DD1 may_VM be_VBI a_AT1 result_NN1 of_IO a_AT1 lack_NN1 of_IO understanding_NN1 how_RRQ the_AT environment_NN1 can_VM be_VBI incorporated_VVN to_II the_AT businesses_NN2 supply_VV0 chain_NN1 ._. 
</s>
<s>
(_( Walker_NP1 ,_, Di_NP1 Sisto_NP1 &;_NULL McBain_NP1 2008_MC ;_; Mont_NP1 &;_NULL Leire_NP1 2009_MC )_) By_II changing_VVG the_AT supply_NN1 chain_NN1 to_II more_RGR environmentally_RR friendly_JJ it_PPH1 means_VVZ that_CST the_AT business_NN1 will_VM need_VVI to_TO make_VVI organizational_JJ changes_NN2 as_RR21 well_RR22 ._. 
</s>
<s>
Employees_NN2 need_VV0 to_TO be_VBI educated_VVN and_CC management_NN1 also_RR need_VV0 to_TO be_VBI educated_VVN first_MD in_II how_RRQ to_TO incorporate_VVI environmental_JJ aspects_NN2 into_II the_AT supply_NN1 chain_NN1 and_CC after_CS that_DD1 how_RRQ to_TO enhance_VVI and_CC be_VBI proactive_JJ in_II environmental_JJ issues_NN2 ._. 
</s>
<s>
(_( Walker_NP1 ,_, Di_NP1 Sisto_NP1 &;_NULL McBain_NP1 2008_MC ;_; Mont_NP1 &;_NULL Leire_NP1 2009_MC )_) Businesses_NN2 may_VM also_RR only_RR use_VVI environmental_JJ practices_NN2 as_II a_AT1 marketing_NN1 trick_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ called_VVN greenwash_NN1 and_CC is_VBZ a_AT1 result_NN1 of_IO management_NN1 only_JJ advertising_NN1 that_CST they_PPHS2 take_VV0 the_AT environment_NN1 in_II consideration_NN1 ,_, but_CCB in_II reality_NN1 they_PPHS2 have_VH0 not_XX changed_VVN their_APPGE supply_NN1 chain_NN1 or_CC organization_NN1 to_II a_AT1 more_RGR environmental_JJ one_PN1 ._. 
</s>
<s>
(_( Walker_NP1 ,_, DiSisto_NP1 &;_NULL McBain_NP1 2008_MC )_) 4_MC ._. 
</s>
<s>
Critical_JJ factors_NN2 in_II Finland_NP1 5_MC ._. 
</s>
<s>
Conclusions_NN2 
</s>
