<s>
Performance_NN1 of_IO financial_JJ ratios_NN2 in_II forecasting_VVG future_JJ stock_NN1 prices_NN2 1_MC1 ._. 
</s>
<s>
Introduction_NN1 Beating_VVG the_AT market_NN1 is_VBZ something_PN1 most_DAT investors_NN2 want_VV0 to_TO achieve_VVI ._. 
</s>
<s>
However_RR ,_, choosing_VVG the_AT stocks_NN2 to_TO complete_VVI that_DD1 objective_NN1 is_VBZ difficult_JJ ._. 
</s>
<s>
Financial_JJ ratios_NN2 provide_VV0 investors_NN2 with_IW information_NN1 concerning_II profitability_NN1 ,_, financial_JJ leverage_NN1 ,_, liquidity_NN1 and_CC market_NN1 value_NN1 (_( Bodie_NP1 &;_NULL Merton:76-90_FO )_) ._. 
</s>
<s>
The_AT extent_NN1 to_II which_DDQ they_PPHS2 can_VM be_VBI used_VVN in_II predicting_VVG future_JJ stock_NN1 performance_NN1 has_VHZ been_VBN widely_RR debated_VVN ._. 
</s>
<s>
This_DD1 paper_NN1 sets_VVZ out_RP to_TO study_VVI if_CSW it_PPH1 is_VBZ possible_JJ to_TO outperform_VVI the_AT market_NN1 and_CC industry_NN1 index_NN1 by_II the_AT means_NN of_IO analyzing_VVG different_JJ financial_JJ ratios_NN2 ._. 
</s>
<s>
By_II analyzing_VVG key_JJ value_NN1 drivers_NN2 it_PPH1 will_VM be_VBI possible_JJ to_TO see_VVI whether_CSW there_EX exists_VVZ a_AT1 significant_JJ correlation_NN1 between_II exemplary_JJ financial_JJ ratios_NN2 and_CC excess_JJ returns_NN2 between_II stocks_NN2 and_CC their_APPGE industry_NN1 indices_NN2 ._. 
</s>
<s>
The_AT financial_JJ ratios_NN2 have_VH0 been_VBN chosen_VVN for_IF the_AT study_NN1 on_II the_AT basis_NN1 of_IO past_JJ research_NN1 in_II which_DDQ ratios_NN2 seem_VV0 to_TO have_VHI statistical_JJ significance_NN1 in_II predicting_VVG future_JJ stock_NN1 returns_NN2 ._. 
</s>
<s>
The_AT ratios_NN2 chosen_VVN are_VBR the_AT Price-to-Earnings_NP1 ratio_NN1 (_( P/E_NN1 )_) ,_, Price-to-Dividend_NP1 yield_NN1 (_( D/P_ZZ1 )_) and_CC the_AT Price-to-Book_NP1 ratio_NN1 ._. 
</s>
<s>
The_AT research_NN1 on_II the_AT predictive_JJ power_NN1 of_IO these_DD2 financial_JJ ratios_NN2 has_VHZ mostly_RR taken_VVN place_NN1 in_II the_AT U.S_NP1 and_CC to_II some_DD extent_NN1 in_II the_AT European_JJ market_NN1 ,_, but_CCB no_AT significant_JJ data_NN has_VHZ been_VBN gathered_VVN from_II the_AT Finnish_JJ market_NN1 ._. 
</s>
<s>
(_( Ehrnrooth_NN1 2004_MC :_: 3_MC )_) 1.1_MC The_AT purpose_NN1 of_IO the_AT study_NN1 The_AT purpose_NN1 of_IO the_AT study_NN1 is_VBZ to_TO examine_VVI whether_CSW financial_JJ ratios_NN2 can_VM be_VBI used_VVN to_TO forecast_VVI stock_NN1 performance_NN1 ._. 
</s>
<s>
1.2_MC Restrictions_NN2 of_IO the_AT study_NN1 This_DD1 study_NN1 will_VM be_VBI limited_VVN to_II the_AT Finnish_JJ Stock_NN1 Market_NN1 since_CS it_PPH1 is_VBZ an_AT1 uncharted_JJ territory_NN1 and_CC will_VM give_VVI extended_JJ knowledge_NN1 about_II the_AT use_NN1 of_IO the_AT financial_JJ ratios_NN2 in_II the_AT Finnish_JJ market_NN1 ._. 
</s>
<s>
To_TO get_VVI a_AT1 more_RGR comprehensive_JJ picture_NN1 of_IO the_AT use_NN1 of_IO financial_JJ ratios_NN2 ,_, this_DD1 study_NN1 focuses_VVZ on_II an_AT1 industry_NN1 instead_II21 of_II22 just_RR independent_JJ companies_NN2 ._. 
</s>
<s>
Choosing_VVG companies_NN2 operating_VVG in_II the_AT same_DA industry_NN1 enables_VVZ one_PN1 to_TO see_VVI whether_CSW there_EX are_VBR differences_NN2 in_II the_AT performance_NN1 and_CC use_NN1 of_IO financial_JJ ratios_NN2 between_II companies_NN2 ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, it_PPH1 makes_VVZ the_AT companies_NN2 and_CC financial_JJ ratios_NN2 more_RGR comparable_JJ to_II each_PPX221 other_PPX222 ._. 
</s>
<s>
Secondly_RR ,_, this_DD1 study_NN1 will_VM be_VBI limited_VVN to_II backward-looking_JJ key_JJ value_NN1 drivers_NN2 ._. 
</s>
<s>
Evaluation_NN1 of_IO financial_JJ ratios_NN2 based_VVN on_II future_JJ consensus_NN1 estimates_NN2 will_VM not_XX be_VBI considered_VVN ,_, that_DD1 will_VM be_VBI left_VVN for_IF further_JJR studies_NN2 ._. 
</s>
<s>
Finally_RR ,_, there_EX will_VM be_VBI a_AT1 time_NNT1 limit_NN1 for_IF the_AT data_NN ._. 
</s>
<s>
The_AT time_NNT1 period_NN1 used_VVN in_II the_AT empirical_JJ study_NN1 will_VM contain_VVI financial_JJ data_NN from_II a_AT1 time_NNT1 period_NN1 of_IO ten_MC years_NNT2 from_II 2001_MC 2010._MC 1.3_MC ._. 
</s>
<s>
The_AT structure_NN1 of_IO the_AT study_NN1 The_AT structure_NN1 of_IO the_AT study_NN1 is_VBZ as_CSA follows_VVZ :_: section_NN1 2_MC will_VM introduce_VVI the_AT theory_NN1 and_CC background_NN1 ,_, section_NN1 3_MC will_VM concentrate_VVI on_II the_AT earlier_JJR research_NN1 ,_, section_NN1 4_MC will_VM cover_VVI the_AT data_NN and_CC the_AT method_NN1 of_IO the_AT study_NN1 ,_, section_NN1 5_MC will_VM present_VVI the_AT results_NN2 ,_, in_II section_NN1 6_MC will_VM contain_VVI the_AT discussion_NN1 and_CC analysis_NN1 ,_, and_CC section_NN1 7_MC is_VBZ the_AT summary_NN1 and_CC conclusion_NN1 of_IO the_AT paper_NN1 ._. 
</s>
<s>
2_MC ._. 
</s>
<s>
Theory_NN1 and_CC Past_JJ research_NN1 According_II21 to_II22 the_AT random_JJ walk-hypothesis_NN1 ,_, originally_RR constructed_VVN by_II the_AT French_JJ broker_NN1 Jules_NP1 Regnault_NP1 ,_, stock_NN1 markets_NN2 follow_VV0 a_AT1 random_JJ walk_NN1 and_CC can_VM not_XX be_VBI predicted_VVN ._. 
</s>
<s>
The_AT theory_NN1 is_VBZ associated_VVN with_IW the_AT efficient_JJ market_NN1 hypothesis_NN1 as_CSA it_PPH1 assumes_VVZ information_NN1 symmetry_NN1 ,_, that_CST all_DB the_AT information_NN1 that_CST is_VBZ relevant_JJ for_IF a_AT1 specific_JJ stock_NN1 is_VBZ reflected_VVN in_II its_APPGE price_NN1 ._. 
</s>
<s>
This_DD1 would_VM mean_VVI that_CST tomorrows_NN2 price_NN1 change_NN1 will_VM only_RR reflect_VVI tomorrows_NN2 news_NN1 (_( Malkiel_NP1 ,_, 2003:59_MC )_) ._. 
</s>
<s>
However_RR ,_, Campbell_NP1 and_CC Shiller_NP1 argue_VV0 that_DD1 stock_NN1 prices_NN2 are_VBR driven_VVN by_II mean_JJ reversion_NN1 ._. 
</s>
<s>
They_PPHS2 claim_VV0 that_CST financial_JJ ratios_NN2 such_II21 as_II22 P/E_NN1 and_CC D/P_ZZ1 revert_VV0 back_RP to_II their_APPGE historical_JJ averages_NN2 and_CC can_VM thus_RR be_VBI used_VVN in_II predictions_NN2 of_IO stock_NN1 market_NN1 performance_NN1 ._. 
</s>
<s>
(_( Campbell_NP1 &;_NULL Shiller_NP1 ,_, 2001_MC )_) 2.1_MC ._. 
</s>
<s>
The_AT Price-to-Earnings_NP1 ratio_NN1 (_( P/E_NN1 )_) The_AT price_NN1 per_II earnings_NN2 ratio_NN1 is_VBZ calculated_VVN as_CSA following_VVG :_: &lsqb;_( Formula_NN1 &rsqb;_) The_AT numerator_NN1 is_VBZ the_AT stock_NN1 price_NN1 ,_, whereas_CS the_AT denominator_NN1 is_VBZ based_VVN on_II which_DDQ type_NN1 of_IO P/E_NN1 is_VBZ calculated_VVN ._. 
</s>
<s>
The_AT trailing_JJ P/E_NN1 is_VBZ calculated_VVN by_II dividing_VVG the_AT stock_NN1 price_NN1 with_IW the_AT net_JJ income_NN1 from_II the_AT recent_JJ twelve_MC months_NNT2 divided_VVN by_II the_AT number_NN1 of_IO shares_NN2 outstanding_JJ ._. 
</s>
<s>
A_AT1 company_NN1 is_VBZ considered_VVN to_TO have_VHI a_AT1 low_JJ P/E_NN1 ratio_NN1 when_CS the_AT ratio_NN1 is_VBZ between_II 0-10_MCMC ._. 
</s>
<s>
A_AT1 low_JJ P/E_NN1 can_VM either_RR be_VBI a_AT1 sign_NN1 of_IO undervaluation_NN1 (_( low_JJ nominator_NN1 )_) or_CC lower_JJR expectations_NN2 of_IO future_JJ earnings_NN2 (_( high_JJ current_JJ denominator_NN1 )_) ._. 
</s>
<s>
Companies_NN2 with_IW a_AT1 low_JJ P/E_NN1 are_VBR usually_RR referred_VVN to_II as_CSA value_NN1 stocks_NN2 ._. 
</s>
<s>
Stocks_NN2 with_IW a_AT1 P/E_NN1 of_IO 17_MC and_CC over_RP are_VBR considered_VVN to_TO have_VHI a_AT1 high_JJ P/E_NN1 and_CC are_VBR usually_RR referred_VVN to_II as_CSA growth_NN1 stocks_NN2 ._. 
</s>
<s>
A_AT1 company_NN1 can_VM have_VHI a_AT1 high_JJ P/E_NN1 either_RR because_CS it_PPH1 is_VBZ expected_VVN to_TO increase_VVI its_APPGE future_JJ earnings_NN2 (_( low_JJ current_JJ denominator_NN1 )_) or_CC because_II21 of_II22 overvaluation_NN1 (_( high_JJ nominator_NN1 )_) or_CC in_II some_DD cases_NN2 because_CS both_DB2 overvaluation_NN1 and_CC increased_JJ earnings_NN2 expectations_NN2 ._. 
</s>
<s>
A_AT1 normal_JJ P/E_NN1 ratio_NN1 lies_VVZ between_II 10_MC and_CC 17_MC ._. 
</s>
<s>
Companies_NN2 that_CST make_VV0 losses_NN2 have_VHI undefined_JJ P/E_NN1 ratios_NN2 ._. 
</s>
<s>
(_( Staubli_NP1 ,_, 2010_MC :_: 11_MC )_) 2.1.1_MC ._. 
</s>
<s>
Past_JJ research_NN1 on_II the_AT Price-to-Earnings_NP1 ratio_NN1 (_( Anderson_NP1 &;_NULL Brooks_NP1 )_) Anderson_NP1 &;_NULL Brooks_NP1 2006_MC claim_VV0 that_CST investing_VVG in_II value_NN1 stocks_NN2 (_( low_JJ P/E_NN1 )_) gives_VVZ a_AT1 significantly_RR better_JJR return_NN1 than_CSN investing_VVG in_II growth_NN1 stocks_NN2 ._. 
</s>
<s>
The_AT authors_NN2 also_RR point_VV0 out_RP that_DD1 for_IF the_AT P/E_NN1 ratio_NN1 to_TO be_VBI more_RGR accurate_JJ one_PN1 ought_VMK to_TO use_VVI an_AT1 average_NN1 of_IO the_AT past_JJ 8_MC years_NNT2 of_IO company_NN1 earnings_NN2 ._. 
</s>
<s>
(_( Anderson_NP1 &;_NULL Brooks_NP1 ,_, 2006_MC :_: 1063-1086_MCMC )_) 2.2_MC ._. 
</s>
<s>
The_AT Price-to-Book_NP1 ratio_NN1 (_( P/B_ZZ1 )_) The_AT Price-to-Book_NP1 ratio_NN1 is_VBZ calculated_VVN as_CSA following_VVG :_: &lsqb;_( Formula_NN1 &rsqb;_) The_AT price-to-book_JJ value_NN1 gives_VVZ us_PPIO2 the_AT relationship_NN1 between_II the_AT current_JJ stock_NN1 price_NN1 and_CC the_AT most_RGT recent_JJ value_NN1 of_IO company_NN1 equity_NN1 ._. 
</s>
<s>
The_AT value_NN1 of_IO equity_NN1 is_VBZ usually_RR reported_VVN on_II a_AT1 quarterly_JJ basis_NN1 ._. 
</s>
<s>
If_CS a_AT1 company_NN1 has_VHZ a_AT1 P/B_NP1 ratio_NN1 of_IO 1_MC1 ,_, the_AT market_NN1 price_NN1 of_IO its_APPGE assets_NN2 is_VBZ equivalent_JJ to_II the_AT companys_NN2 market_VV0 capitalization_NN1 ._. 
</s>
<s>
A_AT1 low_JJ P/B_ZZ1 could_VM be_VBI a_AT1 sign_NN1 of_IO low_JJ valuation_NN1 as_II the_AT assets_NN2 of_IO the_AT company_NN1 are_VBR valued_VVN just_RR a_RR21 bit_RR22 higher_JJR or_CC even_RR lower_JJR than_CSN their_APPGE actual_JJ current_JJ value_NN1 ._. 
</s>
<s>
In_II this_DD1 sense_NN1 P/B_ZZ1 provides_VVZ an_AT1 investor_NN1 with_IW a_AT1 picture_NN1 of_IO the_AT relation_NN1 between_II market_NN1 capitalization_NN1 and_CC the_AT value_NN1 of_IO company_NN1 assets_NN2 given_CS21 that_CS22 the_AT company_NN1 declared_VVD bankruptcy_NN1 immediately_RR ._. 
</s>
<s>
The_AT P/B_NP1 ratio_NN1 is_VBZ not_XX very_RG reliable_JJ in_II cross-industry_JJ analysis_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ because_CS capital_JJ intensive_JJ industries_NN2 tend_VV0 to_TO have_VHI much_DA1 lower_JJR P/B_ZZ1 ratios_NN2 than_CSN less_II capital_NN1 intensive_JJ industries_NN2 ._. 
</s>
<s>
A_AT1 high_JJ P/B_ZZ1 means_VVZ that_CST investors_NN2 believe_VV0 that_CST a_AT1 company_NN1 can_VM generate_VVI more_DAR value_NN1 from_II its_APPGE assets_NN2 ._. 
</s>
<s>
Another_DD1 reason_NN1 for_IF a_AT1 high_JJ P/B_ZZ1 is_VBZ that_CST a_AT1 companys_NN2 assets_NN2 have_VH0 a_AT1 greater_JJR market_NN1 value_NN1 than_CSN their_APPGE book_NN1 value_NN1 ._. 
</s>
<s>
However_RR ,_, P/B_NP1 has_VHZ been_VBN criticized_VVN because_CS it_PPH1 does_VDZ not_XX measure_VVI the_AT value_NN1 of_IO intangible_JJ assets_NN2 ,_, such_II21 as_II22 goodwill_NN1 ,_, brand_NN1 value_NN1 or_CC intellectual_JJ property_NN1 ._. 
</s>
<s>
This_DD1 means_VVZ that_CST the_AT P/B_NP1 ratio_NN1 for_IF companies_NN2 with_IW substantial_JJ intangible_JJ assets_NN2 is_VBZ misleading_JJ ._. 
</s>
<s>
(_( Staubli_NP1 ,_, 2010:3-4_MCMC )_) 2.2.1_MC ._. 
</s>
<s>
Past_JJ research_NN1 on_II the_AT Price-to-Book_NP1 ratio_NN1 (_( Fama_NP1 &;_NULL French_NP1 ,_, Trecartin_NP1 )_) According_II21 to_II22 the_AT research_NN1 of_IO Fama_NP1 &;_NULL French_NP1 (_( 1992_MC )_) low_JJ P/B_ZZ1 stocks_NN2 ,_, or_CC so_JJ21 called_JJ22 value_NN1 stocks_NN2 ,_, experienced_VVD better_JJR returns_NN2 than_CSN same_DA sized_JJ companies_NN2 with_IW high_JJ P/B_ZZ1 (_( Fama_NP1 &;_NULL French_NP1 ,_, 1992:427-465_MCMC )_) ._. 
</s>
<s>
However_RR ,_, Trecartin_NP1 (_( 2000_MC )_) claims_VVZ that_CST the_AT results_NN2 are_VBR only_RR valid_JJ for_IF long-term_JJ investments_NN2 ,_, which_DDQ he_PPHS1 defines_VVZ as_II an_AT1 investment_NN1 with_IW a_AT1 horizon_NN1 above_II 5_MC years_NNT2 ._. 
</s>
<s>
According_II21 to_II22 Trecartin_NP1 ,_, factors_NN2 such_II21 as_II22 sales_NN growth_NN1 ,_, cash_NN1 flow_NN1 and_CC size_NN1 have_VH0 more_RGR predictive_JJ on_II stock_NN1 returns_NN2 than_CSN the_AT book-to-market_JJ ratio_NN1 (_( Trecartin_NP1 ,_, 2000_MC )_) ._. 
</s>
<s>
2.3_MC ._. 
</s>
<s>
The_AT Dividend-to-Price_JJ ratio_NN1 (_( dividend_NN1 yield_NN1 )_) Is_VBZ calculated_VVN as_CSA following_VVG :_: &lsqb;_( Formula_NN1 &rsqb;_) The_AT dividend_NN1 yield_NN1 informs_VVZ the_AT equity_NN1 holder_NN1 of_IO how_RGQ much_DA1 cash_NN1 flow_NN1 per_II invested_JJ share_NN1 an_AT1 asset_NN1 yields_NN2 ._. 
</s>
<s>
A_AT1 high_JJ dividend_NN1 yield_NN1 can_VM either_RR be_VBI a_AT1 sign_NN1 of_IO undervaluation_NN1 or_CC a_AT1 sign_NN1 of_IO negative_JJ future_JJ prospects_NN2 that_CST have_VH0 been_VBN discounted_VVN in_II the_AT stock_NN1 price_NN1 but_CCB not_XX yet_RR in_II the_AT dividend_NN1 ._. 
</s>
<s>
Furthermore_RR ,_, a_AT1 low_JJ dividend_NN1 yield_NN1 might_VM be_VBI an_AT1 indication_NN1 of_IO overvaluation_NN1 or_CC improved_JJ future_JJ prospects_NN2 which_DDQ are_VBR discounted_VVN in_II the_AT stock_NN1 price_NN1 but_CCB not_XX yet_RR in_II the_AT dividend_NN1 ._. 
</s>
<s>
In_RR21 general_RR22 a_AT1 high_JJ dividend_NN1 yield_NN1 is_VBZ considered_VVN as_II a_AT1 positive_JJ sign_NN1 ,_, as_CSA it_PPH1 indicates_VVZ that_CST the_AT company_NN1 will_VM have_VHI a_AT1 strong_JJ future_JJ cash_NN1 flow_NN1 that_CST enables_VVZ it_PPH1 to_TO pay_VVI a_AT1 high_JJ dividend_NN1 ,_, since_CS companies_NN2 tend_VV0 to_TO be_VBI very_RG reluctant_JJ in_II decreasing_VVG their_APPGE dividend_NN1 ._. 
</s>
<s>
A_AT1 typical_JJ dividend_NN1 yield_NN1 is_VBZ said_VVN to_TO lie_VVI between_II 2-5_MCMC %_NNU ._. 
</s>
<s>
Furthermore_RR ,_, a_AT1 positive_JJ aspect_NN1 of_IO using_VVG the_AT dividend-price_JJ ratio_NN1 is_VBZ that_CST companies_NN2 can_VM not_XX affect_VVI it_PPH1 with_IW accounting_VVG measures_NN2 in_II the_AT same_DA way_NN1 as_CSA for_REX21 example_REX22 depreciations_NN2 and_CC amortizations_NN2 affect_VV0 earnings_NN2 and_CC thus_RR the_AT P/E_NN1 ratio_NN1 ._. 
</s>
<s>
(_( Vanninen_NN1 ,_, 2009:20_MC )_) 2.3.1_MC ._. 
</s>
<s>
Past_JJ research_NN1 on_II the_AT Dividend-to-Price_JJ ratio_NN1 (_( Campbell_NP1 &;_NULL Shiller_NP1 )_) Campbell_NP1 and_CC Shiller_NP1 2001_MC have_VH0 researched_VVN how_RGQ efficient_JJ the_AT dividend-price_JJ ratio_NN1 is_VBZ in_II predicting_VVG stock_NN1 performance_NN1 ._. 
</s>
<s>
According_II21 to_II22 their_APPGE theory_NN1 the_AT dividend-price_JJ ratio_NN1 reverts_VVZ back_RP to_II its_APPGE mean_JJ and_CC can_NN1 based_VVN on_II that_DD1 be_VBI used_VVN in_II predicting_VVG future_JJ trends_NN2 ._. 
</s>
<s>
However_RR ,_, Campbell_NP1 and_CC Shiller_NP1 point_VV0 out_RP that_CST the_AT prediction_NN1 has_VHZ to_TO be_VBI made_VVN on_II a_AT1 long-term_JJ basis_NN1 ,_, since_CS the_AT short-term_NN1 predicting_VVG power_NN1 seems_VVZ to_TO be_VBI insignificant_JJ ._. 
</s>
<s>
(_( Campbell_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2001_MC )_) 3_MC ._. 
</s>
<s>
Data_NN There_EX are_VBR two_MC types_NN2 of_IO main_JJ data_NN :_: closing_JJ prices_NN2 of_IO year-to-year_JJ stock-market_NN1 data_NN and_CC year-to-year_JJ data_NN of_IO financial_JJ ratios_NN2 ._. 
</s>
<s>
3.1_MC ._. 
</s>
<s>
Stock_NN1 Market_NN1 data_NN As_CSA stated_VVN in_II the_AT introduction_NN1 ,_, the_AT study_NN1 will_VM focus_VVI on_II a_AT1 particular_JJ industry_NN1 on_II the_AT Finnish_JJ Stock_NN1 Market_NN1 ,_, namely_REX the_AT Machinery_NN1 industry_NN1 ._. 
</s>
<s>
The_AT companies_NN2 included_VVN in_II the_AT study_NN1 are_VBR KONE_NP1 Oyj_NP1 ,_, Cargotec_NP1 Oyj_NP1 ,_, Konecranes_NP1 Oyj_NP1 ,_, Metso_NP1 Oyj_NP1 and_CC Wrtsil_NP1 Oyj_NP1 Abp_NP1 ._. 
</s>
<s>
These_DD2 companies_NN2 represent_VV0 companies_NN2 that_CST are_VBR both_RR listed_VVN on_II the_AT OMX_NP1 Helsinki_NP1 MachineryGI_NP1 index_NN1 ,_, which_DDQ functions_VVZ as_II the_AT industry_NN1 index_NN1 ,_, as_RG well_RR as_CSA on_II the_AT OMXH_NN1 25_MC index_NN1 ,_, which_DDQ functions_VVZ as_II the_AT market_NN1 index_NN1 in_II this_DD1 study_NN1 (_( nasdaqomxnordic.com_NNU )_) ._. 
</s>
<s>
The_AT OMXH_NN1 25_MC index_NN1 will_VM be_VBI used_VVN as_II the_AT market_NN1 index_NN1 since_CS it_PPH1 consists_VVZ of_IO the_AT 25_MC most_RGT traded_JJ companies_NN2 listed_VVN on_II the_AT Nasdaq_NP1 OMX_NP1 Helsinki_NP1 Stock_NN1 Exchange_NN1 and_CC therefore_RR is_VBZ an_AT1 able_JJ indicator_NN1 of_IO the_AT market_NN1 as_II a_AT1 whole_NN1 ._. 
</s>
<s>
Also_RR ,_, the_AT selected_JJ companies_NN2 are_VBR all_DB listed_VVN on_II the_AT OMXH_NN1 25_MC index_NN1 which_DDQ makes_VVZ an_AT1 adequate_JJ comparison_NN1 of_IO the_AT market_NN1 index_NN1 ,_, the_AT industry_NN1 index_NN1 and_CC the_AT excess_JJ returns_NN2 ._. 
</s>
<s>
The_AT stock-market_NN1 data_NN samples_NN2 are_VBR collected_VVN from_II Kauppalehti.fi_NP1 ,_, Thomson_NP1 One_MC1 Banker_NN1 and_CC Omxnordic.com_NP1 and_CC contain_VV0 financial_JJ data_NN from_II a_AT1 time-period_NN1 from_II 1.1.2001_MC until_II 31.12.2010_MC ._. 
</s>
<s>
The_AT financial_JJ ratio_NN1 data_NN samples_NN2 ,_, which_DDQ include_VV0 the_AT industry_NN1 specific_JJ beta_NN1 and_CC return_NN1 ,_, are_VBR collected_VVN from_II Thomson_NP1 One_MC1 Banker_NN1 ,_, Kauppalehti.fi_NP1 ,_, Markets.fi.com_NP1 and_CC Stern.nyu.edu_NP1 from_II the_AT same_DA time_NNT1 period_NN1 as_CSA the_AT stock-market_NN1 data_NN ._. 
</s>
<s>
Following_VVG the_AT Capital_NN1 Asset_NN1 Pricing_VVG Model_NN1 is_VBZ introduced_VVN in_BCL21 order_BCL22 to_TO define_VVI alpha_NN1 which_DDQ is_VBZ needed_VVN as_II an_AT1 explained_JJ variable_NN1 in_II the_AT study_NN1 ._. 
</s>
<s>
3.2_MC ._. 
</s>
<s>
Capital_NN1 Asset_NN1 Pricing_VVG Model_NN1 The_AT Capital_NN1 Asset_NN1 Pricing_VVG Model_NN1 was_VBDZ developed_VVN by_II William_NP1 Sharpe_NP1 ,_, John_NP1 Lintner_NP1 and_CC Jan_NP1 Mossin_NP1 as_II a_AT1 means_NN of_IO calculating_VVG the_AT expected_JJ return_NN1 on_II the_AT market_NN1 for_IF a_AT1 derivative_NN1 with_IW a_AT1 beta_NN1 differing_VVG from_II 0_MC or_CC 1_MC1 (_( Brealey_NP1 ,_, Myers_NP1 &;_NULL Allen_NP1 ,_, 8thedt:189_FO )_) ._. 
</s>
<s>
The_AT CAPM_NP1 defines_VVZ the_AT expected_JJ return_NN1 of_IO a_AT1 stock_NN1 by_II calculating_VVG the_AT risk_NN1 free_JJ rate_NN1 ,_, beta_NN1 and_CC a_AT1 market_NN1 risk_NN1 premium_NN1 in_II the_AT following_JJ formula_NN1 :_: &lsqb;_( Formula_NN1 &rsqb;_) The_AT CAPM_NP1 defines_VVZ a_AT1 stocks_NN2 risk_VV0 as_CSA its_APPGE sensitivity_NN1 to_II the_AT market_NN1 (_( Koller_NP1 ,_, Goedhart_NP1 &;_NULL Wessels_NP1 ,_, 4thedt:294_FO )_) ._. 
</s>
<s>
The_AT next_MD step_NN1 is_VBZ to_TO extract_VVI alpha_NN1 from_II the_AT Capital_NN1 Asset_NN1 Pricing_VVG Model_NN1 ._. 
</s>
<s>
3.3_MC ._. 
</s>
<s>
Alpha_NN1 Alpha_NN1 is_VBZ defined_VVN as_II the_AT risk-adjusted_JJ performance_NN1 measure_NN1 of_IO an_AT1 investment_NN1 ._. 
</s>
<s>
The_AT excess_JJ return_NN1 of_IO a_AT1 stock_NN1 relative_NN1 with_IW a_AT1 benchmark_NN1 index_NN1 return_NN1 is_VBZ the_AT alpha_NN1 of_IO the_AT stock_NN1 ._. 
</s>
<s>
If_CS an_AT1 alpha_NN1 of_IO a_AT1 stock_NN1 is_VBZ positive_JJ ,_, with_IW say_VV0 1.0_MC ,_, the_AT stock_NN1 has_VHZ outperformed_VVN the_AT benchmarked_JJ index_NN1 by_II 1_MC1 %_NNU ._. 
</s>
<s>
The_AT same_DA rule_NN1 applies_VVZ respectively_RR when_CS a_AT1 stocks_NN2 alpha_NN1 is_VBZ -1_MC %_NNU ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, if_CS an_AT1 alpha_NN1 for_IF a_AT1 stock_NN1 is_VBZ equivalent_JJ to_II 0_MC the_AT investment_NN1 has_VHZ earned_VVN a_AT1 sufficient_JJ return_NN1 for_IF its_APPGE risk_NN1 ._. 
</s>
<s>
Alpha_NN1 is_VBZ also_RR determined_VVN by_II comparing_VVG expected_JJ returns_NN2 with_IW actual_JJ returns_NN2 ._. 
</s>
<s>
Alpha_NN1 is_VBZ derived_VVN from_II the_AT Capital_NN1 Asset_NN1 Pricing_VVG Model_NN1 as_CSA following_VVG :_: &lsqb;_( Formula_NN1 &rsqb;_) Using_VVG the_AT CAPM_NP1 in_II this_DD1 form_NN1 outlines_NN2 a_AT1 regression_NN1 line_NN1 which_DDQ is_VBZ also_RR known_VVN as_II the_AT security_NN1 characteristic_NN1 line_NN1 (_( SCL_NP1 )_) ._. 
</s>
<s>
The_AT security_NN1 characteristic_NN1 line_NN1 varies_VVZ from_II the_AT security_NN1 market_NN1 line_NN1 (_( SML_NP1 )_) by_II the_AT fact_NN1 that_CST it_PPH1 outlines_NN2 the_AT performance_NN1 of_IO a_AT1 derivative_JJ contra_NN1 the_AT market_NN1 portfolio_NN1 and_CC lays_VVZ out_RP the_AT alpha_NN1 of_IO an_AT1 asset_NN1 whereas_CS the_AT security_NN1 market_NN1 line_NN1 represents_VVZ the_AT CAPM_NP1 in_II a_AT1 graphical_JJ form_NN1 and_CC outlines_NN2 the_AT beta_NN1 of_IO an_AT1 asset_NN1 (_( non-diversifiable_JJ risk_NN1 )_) ._. 
</s>
<s>
(_( Bodie_NN1 ,_, Kane_NP1 &;_NULL Marcus_NP1 ,_, 8thedt:288_FO )_) Alpha_NN1 is_VBZ applied_VVN to_II the_AT study_NN1 by_II analyzing_VVG whether_CSW the_AT CAPM_NP1 has_VHZ correctly_RR estimated_VVN the_AT expected_JJ returns_NN2 or_CC if_CS the_AT there_EX exists_VVZ a_AT1 difference_NN1 between_II the_AT expected_JJ and_CC the_AT actual_JJ returns_NN2 ._. 
</s>
<s>
Alternatively_RR ,_, a_AT1 study_NN1 is_VBZ made_VVN to_TO examine_VVI whether_CSW the_AT stock_NN1 has_VHZ outperformed_VVN the_AT market_NN1 index_NN1 or_CC not_XX ._. 
</s>
<s>
The_AT industry_NN1 index_NN1 and_CC the_AT market_NN1 index_NN1 (_( OMXH_NP1 25_MC )_) will_VM be_VBI implemented_VVN into_II two_MC different_JJ models_NN2 ._. 
</s>
<s>
4_MC ._. 
</s>
<s>
Method_NN1 This_DD1 section_NN1 presents_VVZ the_AT quantitative_JJ methods_NN2 of_IO the_AT study_NN1 ._. 
</s>
<s>
The_AT empirical_JJ study_NN1 is_VBZ based_VVN on_II two_MC methods_NN2 ._. 
</s>
<s>
The_AT first_MD method_NN1 will_VM compare_VVI industry_NN1 index_NN1 performance_NN1 with_IW stock_NN1 performance_NN1 ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, the_AT method_NN1 studies_NN2 the_AT stocks_NN2 performance_NN1 to_II the_AT performance_NN1 of_IO its_APPGE benchmarked_JJ index_NN1 ._. 
</s>
<s>
The_AT excess_JJ returns_NN2 will_VM then_RT be_VBI implemented_VVN in_II a_AT1 regression_NN1 model_NN1 as_II a_AT1 y-variable_NN1 ,_, and_CC the_AT financial_JJ ratios_NN2 will_VM be_VBI put_VVN as_CSA x-variables_NN2 and_CC in_II this_DD1 way_NN1 be_VBI examined_VVN whether_CSW the_AT ratios_NN2 can_VM significantly_RR explain_VVI the_AT excess_JJ returns_NN2 ._. 
</s>
<s>
In_II the_AT second_MD method_NN1 the_AT Capital_NN1 Asset_NN1 Pricing_VVG Model_NN1 is_VBZ utilized_VVN to_TO determine_VVI the_AT year-to-year_JJ alpha_NN1 of_IO a_AT1 stock_NN1 ._. 
</s>
<s>
By_II building_VVG up_RP a_AT1 panel_NN1 data_NN consisting_VVG of_IO a_AT1 stocks_NN2 excess_JJ return_NN1 over_II the_AT market_NN1 index_NN1 (_( alpha_NN1 )_) and_CC the_AT financial_JJ ratios_NN2 (_( P/E_NN1 ,_, P/B_ZZ1 ,_, Div-yield_NN1 )_) ,_, the_AT model_NN1 is_VBZ able_JK to_TO examine_VVI whether_CSW the_AT financial_JJ ratios_NN2 can_VM significantly_RR explain_VVI alpha_NN1 ._. 
</s>
<s>
In_II the_AT second_MD method_NN1 alpha_NN1 functions_NN2 as_II the_AT explained_JJ variable_NN1 and_CC the_AT financial_JJ ratios_NN2 as_II the_AT explanatory_JJ variables_NN2 ._. 
</s>
<s>
This_DD1 method_NN1 is_VBZ also_RR known_VVN as_II the_AT market_NN1 model_NN1 regression_NN1 ._. 
</s>
<s>
First_MD of_IO all_DB a_AT1 null-hypothesis_NN1 (_( H0_FO )_) and_CC an_AT1 alternative_JJ hypothesis_NN1 (_( H1_FO )_) have_VH0 to_TO be_VBI stated_VVN for_IF each_DD1 individual_JJ financial_JJ ratio_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ done_VDN in_II order_NN1 to_TO either_RR accept_VVI or_CC reject_VVI the_AT hypothesis_NN1 according_II21 to_II22 the_AT results_NN2 ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, if_CS a_AT1 test_NN1 is_VBZ significant_JJ the_AT null-hypothesis_NN1 will_VM be_VBI rejected_VVN and_CC the_AT alternative_JJ hypothesis_NN1 will_VM be_VBI accepted_VVN ._. 
</s>
<s>
4.1_MC ._. 
</s>
<s>
Determining_VVG the_AT hypotheses_NN2 for_IF the_AT financial_JJ ratios_NN2 4.1.1_MC ._. 
</s>
<s>
Hypothesis_NN1 for_IF the_AT Price-to-Earnings_NP1 ratio_NN1 The_AT individual_JJ hypotheses_NN2 for_IF the_AT P/E_NN1 ratio_NN1 are_VBR :_: H0_FO =_FO The_AT Price-to-Earnings_NP1 ratio_NN1 has_VHZ no_AT significant_JJ power_NN1 in_II predicting_VVG future_JJ stock_NN1 returns_VVZ /_FO excess_NN1 returns_VVZ H1_FO =_FO The_AT Price-to-Earnings_NP1 ratio_NN1 has_VHZ significant_JJ positive_JJ power_NN1 in_II predicting_VVG future_JJ stock_NN1 returns_VVZ /_FO excess_NN1 returns_VVZ The_AT interpretation_NN1 of_IO the_AT hypothesis_NN1 is_VBZ that_CST the_AT null-hypothesis_NN1 will_VM be_VBI accepted_VVN if_CS the_AT Price-to-Earnings_NP1 ratio_NN1 is_VBZ above_II its_APPGE historical_JJ average_NN1 while_CS the_AT future_JJ stock_NN1 performance_NN1 is_VBZ negative_JJ (_( Ehrnrooth_NP1 ,_, 2004:45_MC )_) ._. 
</s>
<s>
4.1.2_MC ._. 
</s>
<s>
Hypothesis_NN1 for_IF the_AT Price-to-Book_NP1 ratio_NN1 The_AT individual_JJ hypotheses_NN2 for_IF the_AT P/B_NP1 ratio_NN1 are_VBR :_: H0_FO =_FO The_AT Price-to-Book_NP1 ratio_NN1 has_VHZ no_AT significant_JJ power_NN1 in_II predicting_VVG future_JJ stock_NN1 returns_VVZ /_FO excess_NN1 returns_VVZ H1_FO =_FO The_AT Price-to-Book_NP1 ratio_NN1 has_VHZ significant_JJ positive_JJ power_NN1 in_II predicting_VVG future_JJ stock_NN1 returns_VVZ /_FO excess_NN1 returns_VVZ The_AT interpretation_NN1 of_IO the_AT hypothesis_NN1 is_VBZ that_CST the_AT null-hypothesis_NN1 will_VM be_VBI accepted_VVN if_CS the_AT Price-to-Book_NP1 ratio_NN1 is_VBZ above_II its_APPGE historical_JJ average_NN1 while_CS the_AT future_JJ stock_NN1 performance_NN1 is_VBZ negative_JJ (_( Ehrnrooth_NP1 ,_, 2004:46_MC )_) ._. 
</s>
<s>
4.1.3_MC ._. 
</s>
<s>
Hypothesis_NN1 for_IF the_AT Dividend-to-Price_JJ ratio_NN1 The_AT individual_JJ hypotheses_NN2 for_IF the_AT Div-yield_JJ ratio_NN1 are_VBR :_: H0_FO =_FO The_AT Dividend-to-Price_JJ ratio_NN1 has_VHZ no_AT significant_JJ power_NN1 in_II predicting_VVG future_JJ stock_NN1 returns_VVZ /_FO excess_NN1 returns_VVZ H1_FO =_FO The_AT Dividend-to-Price_JJ ratio_NN1 has_VHZ significant_JJ negative_JJ power_NN1 in_II predicting_VVG future_JJ stock_NN1 returns_VVZ /_FO excess_NN1 returns_VVZ The_AT null-hypothesis_NN1 is_VBZ accepted_VVN if_CS the_AT level_NN1 of_IO the_AT Dividend-to-Price_JJ ratio_NN1 is_VBZ unable_JK to_TO significantly_RR predict_VVI the_AT future_JJ stock_NN1 price_NN1 ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, the_AT null-hypothesis_NN1 is_VBZ rejected_VVN if_CS the_AT Dividend-to-Price_JJ ratio_NN1 is_VBZ below_II its_APPGE historical_JJ average_NN1 while_CS the_AT future_JJ stock_NN1 returns_NN2 are_VBR positive_JJ ._. 
</s>
<s>
(_( Ehrnrooth_NN1 ,_, 2004:45_MC )_) 4.2_MC ._. 
</s>
<s>
The_AT significance_NN1 of_IO the_AT test_NN1 The_AT t-tests_NN2 will_VM be_VBI one_PN1 sided_VVN since_CS well_RR study_VV0 whether_CSW a_AT1 financial_JJ ratio_NN1 has_VHZ significant_JJ positive_JJ (_( P/E_NN1 ,_, P/B_ZZ1 )_) or_CC negative_JJ (_( Div-to-price_NP1 )_) predicting_VVG power_NN1 ._. 
</s>
<s>
The_AT test_NN1 is_VBZ different_JJ for_IF the_AT Div-yield_JJ ratio_NN1 since_CS the_AT price-factor_NN1 is_VBZ situated_VVN in_II the_AT denominator_NN1 of_IO the_AT ratio_NN1 (_( Ehrnrooth_NP1 ,_, A_ZZ1 2004:44-46_MCMC )_) ._. 
</s>
<s>
For_IF a_AT1 t-probability_JJ value_NN1 to_TO be_VBI significant_JJ ,_, it_PPH1 needs_VVZ to_TO be_VBI below_RG 5_MC %_NNU ,_, even_CS21 though_CS22 10_MC %_NNU significance_NN1 can_VM be_VBI motivated_VVN ._. 
</s>
<s>
4.3_MC ._. 
</s>
<s>
Purpose_NN1 of_IO the_AT OLS_NP2 regression_NN1 function_NN1 OLS_VVZ stands_NN2 for_IF Ordinary_JJ Least_DAT Squares_NN2 and_CC is_VBZ used_VVN in_II multiple_JJ regression_NN1 analysis_NN1 ._. 
</s>
<s>
The_AT purpose_NN1 of_IO the_AT OLS_NP2 is_VBZ to_TO create_VVI a_AT1 function_NN1 by_II reducing_VVG the_AT sum_NN1 of_IO squared_JJ errors_NN2 to_II its_APPGE minimum_NN1 from_II the_AT data_NN ,_, thus_RR estimating_VVG explanatory_JJ variable_NN1 correlation_NN1 with_IW the_AT explained_JJ variable_NN1 ._. 
</s>
<s>
(_( Rosenqvist_NN1 ,_, G_ZZ1 2011:1_MC )_) 4.3.1_MC ._. 
</s>
<s>
Estimation_NN1 of_IO the_AT stocks_NN2 versus_II index_NN1 performance_NN1 regression_NN1 The_AT regression_NN1 model_NN1 (_( simplified_JJ form_NN1 )_) for_IF the_AT stocks_NN2 versus_II index_NN1 performance_NN1 is_VBZ as_RG following_JJ :_: &lsqb;_( Formula_NN1 &rsqb;_) The_AT results_NN2 are_VBR to_TO be_VBI interpreted_VVN as_CSA ,_, for_REX21 example_REX22 ,_, if_CS the_AT variable_JJ P/E_NN1 rises_VVZ by_II 1_MC1 then_JJ excess_JJ return_NN1 will_VM increase/decrease_VVI by_II the_AT same_DA amount_NN1 as_CSA the_AT estimator_NN1 of_IO the_AT P/E_NN1 variable_NN1 ._. 
</s>
<s>
If_CS there_EX exists_VVZ a_AT1 negative_JJ correlation_NN1 between_II the_AT different_JJ variables_NN2 it_PPH1 means_VVZ that_CST ,_, for_REX21 example_REX22 ,_, when_CS P/E_NN1 rises_VVZ then_RT P/B_NP1 decreases_VVZ ._. 
</s>
<s>
If_CS there_EX exists_VVZ a_AT1 positive_JJ correlation_NN1 between_II the_AT variables_NN2 it_PPH1 means_VVZ that_CST ,_, for_REX21 example_REX22 ,_, when_CS P/E_NN1 rises_VVZ then_RT P/B_NP1 also_RR rises_VVZ ._. 
</s>
<s>
4.3.2_MC ._. 
</s>
<s>
Estimation_NN1 of_IO the_AT market_NN1 model_NN1 regression_NN1 The_AT regression_NN1 model_NN1 (_( simplified_JJ form_NN1 )_) for_IF the_AT market_NN1 model_NN1 is_VBZ as_RG following_JJ :_: &lsqb;_( Formula_NN1 &rsqb;_) The_AT market_NN1 model_NN1 regression_NN1 is_VBZ interpreted_VVN in_II the_AT same_DA way_NN1 as_CSA the_AT stocks_NN2 versus_II index_NN1 performance_NN1 regression_NN1 ._. 
</s>
<s>
4.4_MC ._. 
</s>
<s>
Regression_NN1 tests_NN2 for_IF further_JJR study_NN1 To_TO determine_VVI the_AT significance_NN1 of_IO the_AT regression_NN1 a_AT1 series_NN of_IO tests_NN2 are_VBR made_VVN ._. 
</s>
<s>
This_DD1 is_VBZ done_VDN in_BCL21 order_BCL22 to_TO analyze_VVI the_AT regression_NN1 model_NN1 further_RRR and_CC to_TO test_VVI the_AT normal_JJ distribution_NN1 of_IO the_AT regression_NN1 ._. 
</s>
<s>
Tests_NN2 made_VVN are_VBR normality-_JJ ,_, heteroskedasticity-_NN1 ,_, auto-correlation-_VV0 ,_, multicollinearity-_JJ and_CC stationarity_NN1 tests_NN2 (_( Rosenqvist_NN1 ,_, G_ZZ1 2011_MC )_) ._. 
</s>
<s>
These_DD2 tests_NN2 will_VM be_VBI left_VVN for_IF further_JJR study_NN1 ._. 
</s>
<s>
Results_NN2 Discussion_NN1 
</s>
