<s>
Brand_NN1 Avoidance_NN1 :_: A_AT1 study_NN1 of_IO young_JJ consumers_NN2 motives_NN2 behind_II avoiding_VVG a_AT1 certain_JJ brand_NN1 1_MC1 ._. 
</s>
<s>
Introduction_NN1 In_II recent_JJ years_NNT2 ,_, as_II a_AT1 result_NN1 of_IO increasingly_RR turbulent_JJ and_CC competitive_JJ markets_NN2 ,_, the_AT interest_NN1 in_II branding_NN1 has_VHZ increased_VVN ._. 
</s>
<s>
(_( Rindell_NP1 &;_NULL Strandvik_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
Todays_NP1 consumers_NN2 live_VV0 in_II a_AT1 world_NN1 where_RRQ the_AT selection_NN1 of_IO products_NN2 and_CC services_NN2 is_VBZ enormous_JJ -_- and_CC continuously_RR growing_VVG ._. 
</s>
<s>
Brands_NN2 also_RR represent_VV0 an_AT1 important_JJ monetary_JJ asset_NN1 for_IF companies_NN2 (_( Rindell_NP1 ,_, 2007_MC )_) ._. 
</s>
<s>
Actually_RR the_AT whole_JJ structure_NN1 of_IO consumption_NN1 has_VHZ changed_VVN entirely_RR in_II 100_MC years_NNT2 ._. 
</s>
<s>
As_CSA consumption_NN1 on_II necessities_NN2 has_VHZ been_VBN replaced_VVN by_II optional_JJ consumption_NN1 ,_, expenditure_NN1 on_II clothes_NN2 per_II person_NN1 has_VHZ grown_VVN nearly_RR nine_MC fold_NN1 ._. 
</s>
<s>
(_( Statistics_NN Finland_NP1 ,_, 2007_MC )_) Especially_RR young_JJ people_NN seem_VV0 to_TO be_VBI quick_JJ to_TO follow_VVI trends_NN2 that_CST are_VBR in._NNU 1.1_MC ._. 
</s>
<s>
Research_NN1 problem_NN1 Most_DAT of_IO the_AT research_NN1 in_II the_AT area_NN1 of_IO brand_NN1 management_NN1 has_VHZ focused_VVN on_II why_RRQ people_NN prefer_VV0 and_CC consume_VV0 certain_JJ brands_NN2 ,_, where_RRQ as_RG fewer_DAR studies_NN2 examine_VV0 reasons_NN2 behind_II why_RRQ consumers_NN2 reject_VV0 specific_JJ brands_NN2 (_( Lee_NP1 &;_NULL al._NNU ,_, 2009_MC )_) ._. 
</s>
<s>
Despite_II the_AT importance_NN1 of_IO the_AT subject_NN1 ,_, brand_NN1 avoidance_NN1 remains_VVZ relatively_RR unexplored_JJ ._. 
</s>
<s>
Of_RR21 course_RR22 consumers_NN2 often_RR choose_VV0 a_AT1 certain_JJ brand_NN1 because_II21 of_II22 the_AT positive_JJ benefits_NN2 it_PPH1 represents_VVZ ._. 
</s>
<s>
But_CCB in_II order_NN1 to_TO completely_RR understand_VVI consumer_NN1 behavior_NN1 ,_, also_RR the_AT reasons_NN2 behind_II the_AT not-buying_JJ decisions_NN2 should_VM be_VBI untangled_JJ ._. 
</s>
<s>
By_II understanding_NN1 what_DDQ motives_NN2 lay_VVD behind_II brand_NN1 avoidance_NN1 companies_NN2 can_VM make_VVI their_APPGE brands_NN2 stronger_JJR ._. 
</s>
<s>
As_CSA Lee_NP1 &.;_NULL al._NNU ,_, (_( 2009_MC )_) put_VV0 it_PPH1 :_: knowing_VVG what_DDQ consumers_NN2 do_VD0 not_XX want_VVI is_VBZ just_RR as_RG valuable_JJ as_CSA knowing_VVG what_DDQ they_PPHS2 want_VV0 ._. 
</s>
<s>
In_II consumer_NN1 behavior_NN1 research_NN1 the_AT both_RR ends_VVZ of_IO the_AT age_NN1 spectrum_NN1 ,_, namely_REX the_AT older_JJR and_CC the_AT younger_JJR customers_NN2 ,_, are_VBR often_RR ignored_VVN ._. 
</s>
<s>
That_DD1 is_VBZ why_RRQ this_DD1 paper_NN1 takes_VVZ young_JJ consumers_NN2 perspective_NN1 when_CS studying_VVG brand_NN1 avoidance_NN1 ._. 
</s>
<s>
1.2_MC ._. 
</s>
<s>
Purpose_NN1 of_IO the_AT study_NN1 and_CC limitations_NN2 The_AT purpose_NN1 of_IO this_DD1 study_NN1 is_VBZ to_TO understand_VVI the_AT young_JJ consumers_NN2 motives_NN2 behind_II brand_NN1 avoidance_NN1 ._. 
</s>
<s>
This_DD1 paper_NN1 aims_VVZ to_TO fulfill_VVI this_DD1 purpose_NN1 by_II answering_VVG the_AT following_JJ research_NN1 question_NN1 :_: Why_RRQ do_VD0 young_JJ people_NN avoid_VV0 certain_JJ brands_NN2 ?_? 
</s>
<s>
Thus_RR ,_, this_DD1 paper_NN1 will_VM try_VVI to_TO find_VVI out_RP why_RRQ young_JJ people_NN avoid_VV0 ,_, dislike_NN1 or_CC even_RR hate_VV0 certain_JJ brands_NN2 while_CS loving_VVG some_DD other_JJ brands_NN2 ._. 
</s>
<s>
Brand_NN1 avoidance_NN1 refers_VVZ only_RR to_II the_AT active_JJ rejection_NN1 of_IO a_AT1 brand_NN1 ,_, not_XX the_AT situations_NN2 where_RRQ consumers_NN2 have_VH0 no_AT choice_NN1 ._. 
</s>
<s>
Therefore_RR ,_, this_DD1 study_NN1 does_VDZ not_XX look_VVI at_II the_AT incidents_NN2 where_RRQ consumers_NN2 do_VD0 not_XX choose_VVI certain_JJ brands_NN2 because_CS they_PPHS2 are_VBR not_XX available_JJ or_CC too_RG expensive_JJ ._. 
</s>
<s>
(_( Lee_NP1 et_NP1 ._. 
</s>
<s>
al._NNU ,_, 2009_MC )_) The_AT study_NN1 will_VM be_VBI limited_VVN to_II consumers_NN2 thoughts_NN2 and_CC opinions_NN2 related_VVN to_II their_APPGE brand_NN1 avoidance_NN1 ._. 
</s>
<s>
Thus_RR ,_, this_DD1 paper_NN1 do_VD0 not_XX study_VVI the_AT managerial_JJ point_NN1 of_IO view_NN1 ,_, neither_DD1 does_VDZ the_AT study_NN1 focus_VVI on_II how_RRQ companies_NN2 can_VM limit_VVI consumers_NN2 brand_VV0 avoidance_NN1 ,_, but_CCB it_PPH1 is_VBZ an_AT1 interesting_JJ subject_NN1 for_IF further_JJR research_NN1 ._. 
</s>
<s>
Naturally_RR ,_, what_DDQ limits_VVZ brand_NN1 avoidance_NN1 is_VBZ very_RG important_JJ topic_NN1 for_IF getting_VVG a_AT1 holistic_JJ view_NN1 of_IO the_AT brand_NN1 management_NN1 and_CC understanding_VVG concerning_II how_RRQ to_TO prevent_VVI brand_NN1 avoidance_NN1 ,_, but_CCB the_AT limitation_NN1 is_VBZ done_VDN due_II21 to_II22 the_AT exploratory_JJ nature_NN1 of_IO the_AT study_NN1 in_II a_AT1 field_NN1 where_RRQ no_AT previous_JJ research_NN1 exists_VVZ ._. 
</s>
<s>
Therefore_RR this_DD1 study_NN1 mainly_RR focuses_VVZ on_II which_DDQ motives_NN2 for_IF brand_NN1 avoidance_NN1 are_VBR relevant_JJ in_II young_JJ consumers_NN2 world_NN1 ,_, as_II31 well_II32 as_II33 if_CSW there_EX are_VBR any_DD new_JJ findings_NN2 emerging_VVG from_II the_AT data_NN ._. 
</s>
<s>
This_DD1 study_NN1 is_VBZ not_XX focusing_VVG on_II a_AT1 certain_JJ branch_NN1 or_CC specific_JJ products_NN2 ._. 
</s>
<s>
Because_CS it_PPH1 is_VBZ such_DA a_AT1 broad_JJ topic_NN1 ,_, I_PPIS1 want_VV0 to_TO study_VVI thoughts_NN2 and_CC opinions_NN2 around_II brand_NN1 avoidance_NN1 on_II a_AT1 general_JJ level_NN1 ._. 
</s>
<s>
1.3_MC ._. 
</s>
<s>
The_AT structure_NN1 of_IO the_AT paper_NN1 The_AT paper_NN1 is_VBZ organized_VVN into_II five_MC sections_NN2 ._. 
</s>
<s>
First_MD ,_, in_II the_AT literature_NN1 review_NN1 ,_, I_PPIS1 will_VM define_VVI the_AT central_JJ concepts_NN2 and_CC provide_VVI an_AT1 overview_NN1 of_IO brand_NN1 avoidance_NN1 literature_NN1 ._. 
</s>
<s>
On_II the_AT basis_NN1 of_IO the_AT literature_NN1 overview_NN1 I_PPIS1 will_VM create_VVI a_AT1 preliminary_JJ model_NN1 of_IO the_AT reasons_NN2 behind_II brand_NN1 avoidance_NN1 ._. 
</s>
<s>
Then_RT ,_, the_AT second_MD section_NN1 presents_VVZ the_AT research_NN1 data_NN and_CC methodology_NN1 ._. 
</s>
<s>
In_II the_AT analysis_NN1 part_NN1 I_PPIS1 will_VM try_VVI to_TO find_VVI out_RP if_CS these_DD2 dimensions_NN2 of_IO brand_NN1 avoidance_NN1 are_VBR relevant_JJ or_CC irrelevant_JJ in_II young_JJ consumers_NN2 context_NN1 and_CC if_CS there_EX are_VBR any_DD new_JJ findings_NN2 emerging_VVG from_II the_AT data_NN collection_NN1 ._. 
</s>
<s>
The_AT concluding_JJ section_NN1 discusses_VVZ managerial_JJ implications_NN2 and_CC presents_VVZ some_DD suggestions_NN2 for_IF further_JJR research_NN1 ._. 
</s>
<s>
2_MC ._. 
</s>
<s>
Literature_NN1 review_VV0 The_AT structure_NN1 of_IO the_AT literature_NN1 review_NN1 is_VBZ illustrated_VVN in_II Figure_NN1 1_MC1 ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) The_AT literature_NN1 review_NN1 will_VM begin_VVI with_IW discussing_VVG brand_NN1 avoidance_NN1 in_BCL21 order_BCL22 to_TO clarify_VVI the_AT meaning_NN1 and_CC composition_NN1 of_IO the_AT concept_NN1 ._. 
</s>
<s>
Then_RT the_AT paper_NN1 will_VM take_VVI a_AT1 closer_JJR look_NN1 at_II young_JJ consumers_NN2 and_CC their_APPGE consumption_NN1 behavior_NN1 ._. 
</s>
<s>
Finally_RR ,_, the_AT literature_NN1 review_NN1 will_VM study_VVI more_RGR precisely_RR what_DDQ kind_NN1 of_IO reasons_NN2 and_CC motives_NN2 can_VM be_VBI found_VVN behind_II young_JJ consumers_NN2 brand_VV0 avoidance_NN1 ._. 
</s>
<s>
The_AT empirical_JJ part_NN1 of_IO the_AT study_NN1 will_VM then_RT for_IF its_APPGE part_NN1 try_VV0 to_TO clarify_VVI why_RRQ younger_JJR consumers_NN2 avoid_VV0 certain_JJ brands_NN2 ._. 
</s>
<s>
2.1_MC ._. 
</s>
<s>
Brand_NN1 avoidance_NN1 Anti-consumption_NN1 refers_VVZ to_II a_AT1 situation_NN1 where_RRQ a_AT1 consumer_NN1 avoids_VVZ or_CC refuses_VVZ consumption_NN1 for_IF certain_JJ reasons_NN2 (_( Soon-Wha_FU ,_, 2011_MC )_) ._. 
</s>
<s>
Brand_NN1 avoidance_NN1 represents_VVZ one_MC1 particular_JJ form_NN1 of_IO anti-consumption_NN1 ,_, namely_REX the_AT incidents_NN2 in_II which_DDQ consumers_NN2 deliberately_RR choose_VV0 to_TO reject_VVI a_AT1 brand_NN1 ._. 
</s>
<s>
Brand_NN1 avoidance_NN1 refers_VVZ only_RR to_II the_AT active_JJ rejection_NN1 of_IO a_AT1 brand_NN1 ,_, not_XX the_AT situations_NN2 where_RRQ consumers_NN2 have_VH0 no_AT choice_NN1 ._. 
</s>
<s>
Therefore_RR ,_, this_DD1 study_NN1 does_VDZ not_XX look_VVI at_II the_AT incidents_NN2 where_RRQ consumers_NN2 do_VD0 not_XX choose_VVI certain_JJ brands_NN2 because_CS they_PPHS2 are_VBR not_XX available_JJ or_CC too_RG expensive_JJ ._. 
</s>
<s>
(_( Lee_NP1 et_NP1 ._. 
</s>
<s>
al._NNU ,_, 2009_MC )_) Lee_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
divide_VV0 brand_NN1 avoidance_NN1 into_II three_MC classes_NN2 ,_, namely_REX experiential_JJ ,_, identity_NN1 and_CC moral_JJ brand_NN1 avoidance_NN1 ._. 
</s>
<s>
Experiential_JJ brand_NN1 avoidance_NN1 arises_VVZ because_CS consumption_NN1 experiences_NN2 had_VHD led_VVN to_II unmet_JJ expectations_NN2 ._. 
</s>
<s>
Identity_NN1 avoidance_NN1 develops_VVZ when_RRQ the_AT brand_NN1 image_NN1 is_VBZ not_XX symbolically_RR consistent_JJ with_IW the_AT identity_NN1 of_IO the_AT individual_NN1 ._. 
</s>
<s>
Moral_JJ avoidance_NN1 arises_VVZ when_RRQ the_AT consumer_NN1 's_GE ideological_JJ beliefs_NN2 are_VBR not_XX convergent_JJ with_IW brand_NN1 values_NN2 or_CC associations_NN2 ._. 
</s>
<s>
(_( Lee_NP1 et_NP1 ._. 
</s>
<s>
al._NNU ,_, 2009_MC )_) 3_MC ._. 
</s>
<s>
Method_NN1 The_AT aim_NN1 of_IO this_DD1 chapter_NN1 is_VBZ to_TO introduce_VVI the_AT research_NN1 process_NN1 as_II31 well_II32 as_II33 justify_VV0 the_AT chosen_JJ method_NN1 that_CST is_VBZ used_VVN to_TO achieve_VVI the_AT purpose_NN1 of_IO the_AT study_NN1 ._. 
</s>
<s>
3.1_MC ._. 
</s>
<s>
The_AT research_NN1 method_NN1 This_DD1 report_NN1 aims_VVZ to_TO study_VVI the_AT young_JJ consumers_NN2 motives_NN2 behind_II brand_NN1 avoidance_NN1 ._. 
</s>
<s>
The_AT research_NN1 method_NN1 is_VBZ qualitative_JJ as_II the_AT intention_NN1 is_VBZ to_TO find_VVI out_RP what_DDQ consumers_NN2 think_VV0 and_CC feel_VVI about_II particular_JJ things_NN2 ,_, and_CC get_VV0 as_RG extensive_JJ picture_NN1 of_IO the_AT consumers_NN2 motives_NN2 as_CSA possible_JJ ._. 
</s>
<s>
This_DD1 kind_NN1 information_NN1 cant_NN1 be_VBI measured_VVN or_CC observed_VVD ._. 
</s>
<s>
Qualitative_JJ methods_NN2 give_VV0 a_AT1 deeper_JJR understanding_NN1 of_IO the_AT problem_NN1 that_CST is_VBZ studied_VVN (_( Holme_NP1 &;_NULL Solvang_NP1 ,_, 1991:26_MC )_) ._. 
</s>
<s>
Because_CS brand_NN1 avoidance_NN1 is_VBZ a_AT1 complex_JJ and_CC relatively_RR new_JJ topic_NN1 it_PPH1 calls_VVZ for_IF new_JJ insights_NN2 ._. 
</s>
<s>
Therefore_RR qualitative_JJ method_NN1 seems_VVZ reasonable_JJ for_IF this_DD1 study_NN1 ._. 
</s>
<s>
The_AT aim_NN1 of_IO this_DD1 study_NN1 is_VBZ not_XX to_TO create_VVI a_AT1 representative_JJ sample_NN1 ,_, but_CCB only_RR to_TO collect_VVI new_JJ insights_NN2 ._. 
</s>
<s>
3.2_MC ._. 
</s>
<s>
Sample_NN1 and_CC respondents_NN2 The_AT respondents_NN2 are_VBR from_II 14_MC to_II 19_MC years_NNT2 old_JJ ._. 
</s>
<s>
Convenience_NN1 sample_NN1 ._. 
</s>
<s>
3.3_MC ._. 
</s>
<s>
Data_NN collection_NN1 The_AT data_NN for_IF the_AT research_NN1 is_VBZ collected_VVN through_II four_MC (_( ?_? )_) semi-structured_JJ interviews_NN2 of_IO the_AT consumers_NN2 ._. 
</s>
<s>
This_DD1 method_NN1 made_VVD it_PPH1 possible_JJ to_TO ask_VVI further_JJR questions_NN2 in_BCL21 order_BCL22 to_TO understand_VVI the_AT underlying_JJ arguments_NN2 behind_II motives_NN2 and_CC attitudes_NN2 ._. 
</s>
<s>
3.4_MC ._. 
</s>
<s>
Interview_NN1 guide_VV0 This_DD1 chapter_NN1 will_VM present_VVI the_AT interview_NN1 guide_NN1 ._. 
</s>
<s>
3.5_MC ._. 
</s>
<s>
Reliability_NN1 and_CC validity_NN1 of_IO the_AT conducted_VVN study_NN1 This_DD1 chapter_NN1 will_VM evaluate_VVI the_AT reliability_NN1 and_CC validity_NN1 of_IO the_AT conducted_VVN study_NN1 3.6_MC ._. 
</s>
<s>
Data_NN analysis_NN1 In_BCL21 order_BCL22 to_TO clarify_VVI why_RRQ young_JJ consumers_NN2 avoid_VV0 certain_JJ brands_NN2 ,_, the_AT data_NN will_VM be_VBI analyzed_VVN on_II the_AT basis_NN1 of_IO the_AT preliminary_JJ model_NN1 ._. 
</s>
<s>
The_AT answers_NN2 of_IO the_AT respondents_NN2 will_VM be_VBI compared_VVN in_BCL21 order_BCL22 to_TO find_VVI out_RP if_CS a_AT1 certain_JJ dimension_NN1 of_IO brand_NN1 avoidance_NN1 is_VBZ regarded_VVN as_CSA central_JJ in_II young_JJ consumers_NN2 context_NN1 ._. 
</s>
<s>
After_CS the_AT roles_NN2 of_IO the_AT dimensions_NN2 have_VH0 been_VBN evaluated_VVN ,_, they_PPHS2 will_VM be_VBI divided_VVN into_II central_JJ elements_NN2 ,_, indifferent_JJ elements_NN2 and_CC new_JJ findings_NN2 ._. 
</s>
<s>
Aim_NN1 of_IO this_DD1 categorizing_NN1 is_VBZ to_TO discover_VVI the_AT factors_NN2 that_CST are_VBR congruent_JJ with_IW the_AT literature_NN1 ,_, the_AT factors_NN2 that_CST are_VBR less_RGR important_JJ in_II this_DD1 context_NN1 ,_, and_CC if_CS there_EX are_VBR any_DD new_JJ central_JJ elements_NN2 emerging_VVG from_II the_AT data_NN ,_, that_DD1 has_VHZ not_XX been_VBN discovered_VVN in_II previous_JJ research_NN1 ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) Figure_NN1 4_MC depicts_VVZ the_AT analysis_NN1 process_NN1 of_IO the_AT results_NN2 ,_, that_REX41 is_REX42 to_REX43 say_REX44 categorizing_NN1 of_IO the_AT data_NN according_II21 to_II22 those_DD2 dimensions_NN2 that_CST where_CS found_VVN in_II literature_NN1 review_NN1 and_CC further_RRR according_II21 to_II22 their_APPGE importance_NN1 for_IF young_JJ consumers_NN2 ._. 
</s>
<s>
The_AT aim_NN1 is_VBZ to_TO sketch_VVI a_AT1 common_JJ view_NN1 of_IO the_AT importance_NN1 of_IO each_DD1 factor_NN1 ._. 
</s>
<s>
Possible_JJ new_JJ factors_NN2 can_VM emerge_VVI if_CSW the_AT interviewees_NN2 emphasize_VV0 some_DD new_JJ factors_NN2 that_CST have_VH0 not_XX been_VBN taken_VVN up_RP in_II the_AT previous_JJ literature_NN1 ._. 
</s>
<s>
4_MC ._. 
</s>
<s>
Results_NN2 This_DD1 chapter_NN1 will_VM present_VVI the_AT results_NN2 of_IO the_AT empirical_JJ study_NN1 ._. 
</s>
<s>
After_CS each_DD1 dimension_NN1 of_IO brand_NN1 avoidance_NN1 I_PPIS1 will_VM present_VVI the_AT most_RGT central_JJ results_NN2 from_II the_AT interviews_NN2 ._. 
</s>
<s>
5_MC ._. 
</s>
<s>
Discussion_NN1 This_DD1 chapter_NN1 will_VM present_VVI the_AT eventual_JJ outcome_NN1 of_IO the_AT results_NN2 :_: a_AT1 model_NN1 of_IO the_AT different_JJ dimensions_NN2 of_IO brand_NN1 avoidance_NN1 from_II young_JJ consumers_NN2 perspective_NN1 ._. 
</s>
<s>
6_MC ._. 
</s>
<s>
Conclusions_NN2 In_II the_AT concluding_JJ chapter_NN1 ,_, I_PPIS1 will_VM repeat_VVI the_AT most_RGT central_JJ message_NN1 of_IO my_APPGE study_NN1 and_CC offer_VV0 some_DD suggestions_NN2 for_IF future_JJ research_NN1 ._. 
</s>
