<s>
CAN_VM PRIVATE_JJ BLOGGERS_NN2 HELP_VV0 COMPANIES_NN2 SPREAD_VVI WORD_NN1 OF_IO MOUTH_NN1 ?_? 
</s>
<s>
Introduction_NN1 Virtual_JJ co-creation_NN1 by_II customer_NN1 means_VVZ information_NN1 sharing_VVG with_IW multiple_JJ entities_NN2 in_II a_AT1 distributed_JJ innovation_NN1 environment_NN1 ._. 
</s>
<s>
Co-creation_NN1 is_VBZ based_VVN on_II cooperation_NN1 of_IO people_NN with_IW different_JJ IT_NN1 capabilities_NN2 (_( Fller_NP1 et_RA21 al._RA22 ,_, 2010:96_MC )_) During_II the_AT last_MD ten_MC years_NNT2 blogs_NN2 have_VH0 become_VVN popular_JJ forums_NN2 ,_, where_CS bloggers_NN2 express_VV0 themselves_PPX2 freely_RR ,_, interact_VV0 with_IW other_JJ Internet_NN1 users_NN2 and_CC enjoy_VV0 themselves_PPX2 ._. 
</s>
<s>
Blogs_NN2 are_VBR also_RR tools_NN2 ,_, which_DDQ can_VM be_VBI used_VVN at_II low_JJ cost_NN1 (_( or_CC for_IF free_JJ )_) in_BCL21 order_BCL22 to_TO improve_VVI a_AT1 companys_NN2 communication_NN1 strategy_NN1 and_CC as_II a_AT1 means_NN for_IF doing_VDG business_NN1 ._. 
</s>
<s>
(_( Singh_NP1 &;_NULL Singh_NP1 ,_, 2008_MC )_) ._. 
</s>
<s>
Equally_RR ,_, a_AT1 blog_NN1 can_VM develop_VVI into_II a_AT1 business_NN1 in_II itself_PPX1 ,_, run_VVN by_II a_AT1 private_JJ person_NN1 ._. 
</s>
<s>
Blogs_NN2 can_VM also_RR be_VBI used_VVN for_IF building_NN1 goodwill_NN1 and_CC educating_VVG a_AT1 companys_NN2 customers_NN2 ._. 
</s>
<s>
The_AT authors_NN2 praise_VV0 the_AT new_JJ technology_NN1 that_CST enables_VVZ people_NN to_TO blog_VVI and_CC they_PPHS2 also_RR conclude_VVI that_CST blogs_NN2 provide_VV0 a_AT1 new_JJ way_NN1 of_IO targeted_JJ communication_NN1 (_( Singh_NP1 &;_NULL Singh_NP1 ,_, 2008_MC )_) ._. 
</s>
<s>
Hence_RR ,_, the_AT scholars_NN2 predict_VV0 that_DD1 niche_NN1 marketing_NN1 and_CC target_NN1 groups_NN2 will_VM dominate_VVI the_AT future_NN1 in_II a_AT1 saturated_JJ information_NN1 environment_NN1 ._. 
</s>
<s>
Companies_NN2 still_RR target_VV0 the_AT biggest_JJT blogs_NN2 with_IW the_AT highest_JJT visitor_NN1 numbers_NN2 ,_, which_DDQ will_VM not_XX necessarily_RR be_VBI the_AT best_JJT strategy_NN1 in_II the_AT future_NN1 ._. 
</s>
<s>
Especially_RR online_JJ marketing_NN1 is_VBZ becoming_VVG more_RGR niche-oriented_JJ ,_, where_CS the_AT focus_NN1 is_VBZ directed_VVN at_II certain_JJ segments_NN2 ._. 
</s>
<s>
(_( Janson_NN1 ,_, 2008_MC )_) Furthermore_RR ,_, it_PPH1 is_VBZ clear_JJ that_CST bloggers_NN2 have_VH0 power_NN1 ._. 
</s>
<s>
In_II a_AT1 survey_NN1 conducted_VVN by_II a_AT1 Swedish_JJ PR_NN1 company_NN1 ,_, Mahir_NP1 ,_, it_PPH1 was_VBDZ reported_VVN that_CST 58_MC percent_NNU of_IO the_AT respondents_NN2 ,_, who_PNQS had_VHD bought_VVN a_AT1 product_NN1 online_RR ,_, read_VVN about_II it_PPH1 in_II a_AT1 blog_NN1 ._. 
</s>
<s>
It_PPH1 was_VBDZ also_RR stated_VVN that_CST companies_NN2 often_RR completely_RR run_VVN out_II21 of_II22 certain_JJ products_NN2 when_CS they_PPHS2 are_VBR featured_VVN in_II blogs_NN2 ,_, which_DDQ again_RT points_VVZ at_II the_AT tremendous_JJ power_NN1 of_IO bloggers_NN2 ._. 
</s>
<s>
(_( Janson_NN1 ,_, 2008_MC )_) Companies_NN2 aim_VV0 at_II co-operating_VVG with_IW private_JJ bloggers_NN2 ,_, in_BCL21 order_BCL22 to_TO create_VVI word-of-mouth_NN1 in_II the_AT blogosphere_NN1 ._. 
</s>
<s>
The_AT creation_NN1 of_IO mutual_JJ benefits_NN2 or_CC a_AT1 meaningful_JJ synergy_NN1 is_VBZ essential_JJ for_IF continuing_VVG a_AT1 relationship_NN1 and_CC for_IF building_NN1 communities_NN2 (_( Rowley_NP1 ,_, 2004_MC )_) A_ZZ1 dialogue_NN1 is_VBZ created_VVN out_II21 of_II22 interactivity_NN1 and_CC engagement_NN1 ,_, as_RG well_RR as_CSA from_II the_AT ability_NN1 to_TO see_VVI the_AT world_NN1 from_II different_JJ angles_NN2 ._. 
</s>
<s>
(_( Prahalad_NP1 &;_NULL Ramaswamy_NP1 ,_, 2004_MC in_II Desai_NP1 ,_, 2009_MC )_) In_II a_AT1 social_JJ media_NN context_NN1 the_AT dialogue_NN1 is_VBZ essential_JJ for_IF different_JJ parties_NN2 to_TO interact_VVI and_CC understand_VVI each_PPX221 other_PPX222 ._. 
</s>
<s>
(_( Desai_NP1 ,_, 2009_MC )_) A_ZZ1 dialogue_NN1 is_VBZ also_RR created_VVN out_II21 of_II22 engagement_NN1 ,_, as_RG well_RR as_CSA from_II the_AT ability_NN1 to_TO see_VVI the_AT world_NN1 from_II different_JJ angles_NN2 ._. 
</s>
<s>
(_( Prahalad_NP1 &;_NULL Ramaswamy_NP1 ,_, 2004_MC in_II Desai_NP1 ,_, 2009_MC )_) Companies_NN2 need_VV0 to_TO build_VVI relationships_NN2 with_IW private_JJ bloggers_NN2 ,_, who_PNQS are_VBR key_JJ players_NN2 in_II the_AT blogosphere_NN1 ._. 
</s>
<s>
Finne_NN1 &;_NULL Grnroos_NN2 reflect_VV0 on_II relationship_NN1 communication_NN1 and_CC conclude_VV0 that_CST :_: /any_FU type_NN1 of_IO marketing_NN1 communication_NN1 that_CST influences_VVZ the_AT receivers_NN2 long-term_JJ commitment_NN1 to_II the_AT sender_NN1 by_II facilitating_VVG meaning_NN1 creation_NN1 through_II integration_NN1 with_IW the_AT receivers_NN2 time_NNT1 and_CC situational_JJ context_NN1 ._. 
</s>
<s>
The_AT time_NNT1 context_NN1 refers_VVZ to_II the_AT receivers_NN2 perception_NN1 of_IO the_AT history_NN1 and_CC envisioned_JJ future_NN1 of_IO his/her_APPGE relationship_NN1 with_IW the_AT sender_NN1 ._. 
</s>
<s>
The_AT situational_JJ context_NN1 refers_VVZ to_II other_JJ elements_NN2 internal_JJ or_CC external_JJ to_II the_AT receiver._NNU (_( Finne_NP1 &;_NULL Grnroos_NP1 ,_, 2009:180-181_MCMC )_) Furthermore_RR ,_, some_DD scholars_NN2 state_VV0 that_CST a_AT1 companys_NN2 value_NN1 is_VBZ largely_RR determined_VVN by_II the_AT quality_NN1 of_IO the_AT networks_NN2 it_PPH1 is_VBZ engaged_VVN in_II ._. 
</s>
<s>
(_( Woerkum_NP1 &;_NULL Aarts_NP1 ,_, 2007_MC )_) There_EX are_VBR three_MC different_JJ aspects_NN2 of_IO digital_JJ marketing_NN1 communications_NN2 that_CST a_AT1 company_NN1 should_VM work_VVI on_RP ;_; creating_VVG presence_NN1 ,_, creating_VVG relationships_NN2 and_CC creating_VVG mutual_JJ benefits_NN2 (_( Rowley_NP1 ,_, 2004_MC )_) To_II that_DD1 ,_, fostering_NN1 relationships_NN2 is_VBZ also_RR concerned_JJ with_IW the_AT firms_NN2 reputation_NN1 ._. 
</s>
<s>
(_( Fombrun_NP1 et_RA21 al._RA22 ,_, 2000_MC in_II Woerkum_NP1 &;_NULL Aarts_NP1 ,_, 2007_MC )_) The_AT level_NN1 of_IO corporate_JJ communication_NN1 effectiveness_NN1 will_VM also_RR be_VBI reflected_VVN in_II the_AT firms_NN2 perceived_VVD image_NN1 ._. 
</s>
<s>
(_( Malmelin_NN1 ,_, 2007_MC )_) Mangold_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2009_MC )_) point_VV0 out_RP that_CST it_PPH1 is_VBZ impossible_JJ for_IF managers_NN2 to_TO control_VVI the_AT (_( online_RR )_) consumer-to-consumer_JJ conversations_NN2 ._. 
</s>
<s>
However_RR ,_, it_PPH1 is_VBZ possible_JJ to_TO build_VVI relationships_NN2 with_IW key_JJ persons_NN2 ,_, who_PNQS actively_RR spread_VV0 information_NN1 that_CST is_VBZ in_II a_AT1 blog_NN1 context_NN1 read_VVN and_CC followed_VVN by_II thousands_NNO2 of_IO people_NN a_AT1 day_NNT1 ._. 
</s>
<s>
New_JJ media_NN facilitate_VV0 social_JJ marketers_NN2 and_CC customers_NN2 to_TO co-create_VVI value_NN1 ;_; however_RR ,_, it_PPH1 is_VBZ not_XX essential_JJ ._. 
</s>
<s>
Without_IW the_AT use_NN1 of_IO new_JJ media_NN ,_, many_DA2 social_JJ marketers_NN2 are_VBR reciprocating_VVG partners_NN2 and_CC empower_NN1 ,_, encourage_VV0 ,_, and_CC support_VV0 people_NN to_TO make_VVI them_PPHO2 reciprocating_VVG partners_NN2 ._. 
</s>
<s>
For_IF being_VBG an_AT1 active_JJ relationship_NN1 partner_NN1 ,_, the_AT most_RGT important_JJ task_NN1 for_IF a_AT1 social_JJ marketer_NN1 is_VBZ to_TO nourish_VVI reciprocity_NN1 in_II the_AT relationships._NNU (_( Desai_NP1 ,_, 2009:117_MC )_) Next_MD ,_, the_AT core_NN1 theory_NN1 of_IO this_DD1 study_NN1 is_VBZ presented_VVN ._. 
</s>
<s>
The_AT Coproduction_NN1 Model_NN1 In_II this_DD1 chapter_NN1 the_AT aim_NN1 is_VBZ to_TO show_VVI how_RGQ word-of-mouth_JJ theory_NN1 has_VHZ evolved_VVN over_II time_NNT1 and_CC what_DDQ the_AT situation_NN1 is_VBZ like_II today_RT ._. 
</s>
<s>
Kozinets_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2010_MC )_) have_VH0 constructed_VVN their_APPGE own_DA theory_NN1 ,_, using_VVG three_MC different_JJ models_NN2 ._. 
</s>
<s>
The_AT first_MD one_PN1 shows_VVZ the_AT earliest_JJT and_CC today_RT fairly_RR outdated_JJ view_NN1 on_II WOM_NP1 where_RRQ information_NN1 about_II brands_NN2 ,_, products_NN2 and_CC marketing_NN1 messages_NN2 flow_VV0 between_II two_MC customers_NN2 in_II one_MC1 direction_NN1 ._. 
</s>
<s>
The_AT marketer_NN1 influences_VVZ consumers_NN2 only_RR through_II different_JJ Marketing-Mix_NP1 Elements_NN2 and_CC does_VDZ not_XX attempt_VVI to_TO steer_VVI ,_, monitor_NN1 or_CC influence_VV0 the_AT consumer_NN1 in_II any_DD way_NN1 ._. 
</s>
<s>
(_( Arndt_NN1 ,_, 1967_MC ,_, Engel_NP1 ,_, Kegerreis_NP1 &;_NULL Blackwell_NP1 1969_MC ,_, Gatignon_NP1 &;_NULL Robertson_NP1 ,_, 1986_MC in_II Kozinets_NP1 et_RA21 al._RA22 ,_, 2010_MC )_) This_DD1 model_NN1 is_VBZ based_VVN on_II the_AT fact_NN1 that_CST WOM_NP1 will_VM occur_VVI naturally_RR when_CS the_AT marketer_NN1 does_VDZ his_APPGE part_NN1 of_IO the_AT job_NN1 i.e._REX developing_JJ new_JJ products_NN2 and_CC creating_VVG appropriate_JJ marketing_NN1 campaigns_NN2 ._. 
</s>
<s>
(_( Bass_NN1 ,_, 1969_MC ,_, Whyte_NP1 ,_, 1954_MC in_II Kozinets_NP1 et_NP1 el_NN1 ._. 
</s>
<s>
2010_MC )_) The_AT second_MD model_NN1 proposed_VVN by_II Kozinets_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
refers_VVZ to_II the_AT power_NN1 of_IO opinion_NN1 leaders_NN2 ._. 
</s>
<s>
In_II this_DD1 model_NN1 the_AT opinion_NN1 leader_NN1 influences_VVZ several_DA2 consumers_NN2 through_II his_APPGE or_CC her_APPGE experience_NN1 ,_, however_RR ,_, the_AT communication_NN1 still_RR flows_VVZ one_MC1 way_NN1 only_RR ._. 
</s>
<s>
Hence_RR ,_, WOM_NP1 theory_NN1 evolves_VVZ from_II the_AT idea_NN1 of_IO a_AT1 salesman_NN1 trying_VVG to_TO get_VVI rid_VVN of_IO sales_NN items_NN2 to_II a_AT1 friend_NN1 recommending_VVG a_AT1 product_NN1 to_II another_DD1 without_IW any_DD intentions_NN2 or_CC pre-determined_JJ strategies_NN2 ._. 
</s>
<s>
(_( Dichter_NN1 1966_MC in_II Kozinets_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2010_MC )_) This_DD1 can_VM directly_RR be_VBI linked_VVN to_II the_AT role_NN1 of_IO a_AT1 private_JJ blogger_NN1 ._. 
</s>
<s>
The_AT marketer_NN1 reaches_VVZ the_AT consumer_NN1 through_II the_AT Marketing_NN1 Mix_NN1 Elements_NN2 and_CC actively_RR seeks_VVZ to_TO influence_VVI the_AT opinion_NN1 leader_NN1 indirectly_RR through_II advertisements_NN2 and_CC promotions_NN2 ._. 
</s>
<s>
However_RR ,_, this_DD1 model_NN1 is_VBZ not_XX applicable_JJ anymore_RR ,_, as_CSA the_AT idea_NN1 community_NN1 is_VBZ missing_JJ ,_, where_CS consumers_NN2 interact_VV0 with_IW each_PPX221 other_PPX222 ,_, as_RG well_RR as_CSA with_IW the_AT marketer_NN1 and_CC the_AT blogger_NN1 ._. 
</s>
<s>
In_II the_AT third_MD model_NN1 ,_, The_AT Network_NN1 Coproduction_NN1 Model_NN1 ,_, the_AT authors_NN2 recognize_VV0 and_CC integrate_VV0 the_AT Internet_NN1 as_II an_AT1 important_JJ factor_NN1 in_II the_AT communication_NN1 between_II the_AT consumer_NN1 and_CC the_AT marketer_NN1 ._. 
</s>
<s>
This_DD1 model_NN1 represents_VVZ the_AT authors_NN2 view_VV0 on_RP where_CS we_PPIS2 are_VBR today_RT ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) Because_II21 of_II22 the_AT World_NN1 Wide_JJ Web_NN1 companies_NN2 can_VM easily_RR measure_VVI and_CC monitor_VVI who_PNQS their_APPGE clients_NN2 are_VBR (_( e.g._REX in_II a_AT1 blog_NN1 )_) and_CC know_VV0 which_DDQ channels_VVZ their_APPGE marketing_NN1 messages_NN2 pass_VV0 through_RP ._. 
</s>
<s>
This_DD1 can_VM be_VBI done_VDN in_II many_DA2 ways_NN2 ,_, and_CC one_MC1 good_JJ way_NN1 is_VBZ tracking_VVG the_AT links_NN2 and_CC tags_VVZ that_CST 86%_NNU of_IO bloggers_NN2 use_VV0 ._. 
</s>
<s>
(_( Horowitz_VV0 ,_, 2010_MC )_) Also_RR ,_, as_CSA shown_VVN before_RT ,_, marketing_NN1 practices_NN2 have_VH0 become_VVN relationship_NN1 oriented_VVD (_( Vargo_NP1 &;_NULL Lusch_NP1 ,_, 2004_MC in_II Kozinets_NP1 et_RA21 al._RA22 ,_, 2010_MC )_) ,_, which_DDQ in_II turn_NN1 refers_VVZ to_II the_AT importance_NN1 of_IO networks_NN2 and_CC communities_NN2 ._. 
</s>
<s>
In_II The_AT Network_NN1 Coproduction_NN1 Model_NN1 consumers_NN2 interact_VV0 with_IW each_PPX221 other_PPX222 within_II groups_NN2 ,_, but_CCB also_RR with_IW other_JJ consumers_NN2 ,_, co-creating_VVG value_NN1 and_CC meaning_NN1 ._. 
</s>
<s>
Relationship_NN1 ties_NN2 can_VM also_RR be_VBI characterized_VVN as_CSA strong_JJ or_CC weak_JJ ._. 
</s>
<s>
The_AT assumption_NN1 is_VBZ based_VVN on_II the_AT following_JJ linkages_NN2 :_: person_NN1 A_ZZ1 and_CC person_NN1 Bs_NP1 relationship_NN1 is_VBZ strong_JJ ,_, as_II31 well_II32 as_II33 person_NN1 Bs_NP1 and_CC person_NN1 Cs_NP2 bond_VV0 ._. 
</s>
<s>
Based_VVN on_II these_DD2 strong_JJ linkages_NN2 ,_, the_AT theory_NN1 assumes_VVZ that_CST the_AT tie_NN1 between_II person_NN1 A_ZZ1 and_CC C_ZZ1 must_VM also_RR be_VBI strong_JJ (_( Granovetter_NP1 ,_, 1973_MC in_II Godes_NP1 &;_NULL Mayzlin_NP1 ,_, 2004_MC )_) as_CSA they_PPHS2 belong_VV0 to_II a_AT1 community_NN1 with_IW powerful_JJ member_NN1 relationships_NN2 ._. 
</s>
<s>
To_II that_DD1 ,_, community_NN1 members_NN2 are_VBR likely_JJ to_TO learn_VVI from_II each_PPX221 other_PPX222 through_II interaction_NN1 when_CS they_PPHS2 share_VV0 experiences_NN2 ._. 
</s>
<s>
(_( Godes_NP1 &;_NULL Mayzlin_NP1 ,_, 2004_MC )_) That_DD1 is_VBZ why_RRQ blogs_NN2 serve_VV0 as_RG great_JJ mediums_NN2 for_IF co-creation_NN1 and_CC information_NN1 sharing_VVG ._. 
</s>
<s>
These_DD2 customer-to-customer_JJ touch_NN1 points_NN2 should_VM be_VBI thoroughly_RR examined_VVN ,_, as_CSA they_PPHS2 provide_VV0 valuable_JJ information_NN1 for_IF companies_NN2 ._. 
</s>
<s>
(_( Desai_NP1 ,_, 2009_MC )_) Furthermore_RR ,_, there_EX are_VBR two_MC key_JJ elements_NN2 to_TO understand_VVI ._. 
</s>
<s>
First_MD ,_, companies_NN2 use_VV0 different_JJ means_NN to_TO measure_VVI and_CC target_VVI the_AT consumers_NN2 and/or_CC the_AT opinion_NN1 leaders_NN2 ._. 
</s>
<s>
Second_MD ,_, the_AT marketing_NN1 messages_NN2 and_CC meanings_NN2 flow_VV0 in_II two_MC ways_NN2 with_IW a_AT1 clear_JJ direction_NN1 within_II a_AT1 consumer_NN1 network_NN1 ._. 
</s>
<s>
(_( Kozinets_NP1 et_RA21 al._RA22 ,_, 2010_MC )_) Valentini_NP1 introduces_VVZ the_AT term_NN1 personalised_JJ network_NN1 of_IO influence_NN1 ,_, which_DDQ aims_VVZ at_II explaining_VVG the_AT interaction_NN1 between_II PR_NP1 practitioners_NN2 and_CC their_APPGE influential_JJ public_NN1 ._. 
</s>
<s>
It_PPH1 takes_VVZ time_NNT1 and_CC commitment_NN1 to_TO build_VVI up_RP such_DA networks_NN2 ._. 
</s>
<s>
The_AT author_NN1 points_VVZ out_RP that_CST the_AT responsibility_NN1 of_IO building_NN1 networks_NN2 is_VBZ not_XX entirely_RR corporate_JJ ,_, but_CCB rather_RG personal_JJ and_CC up_II21 to_II22 every_AT1 employee_NN1 where_CS each_DD1 and_CC every_AT1 one_PN1 must_VM form_VVI its_APPGE own_DA face-to-face_JJ bonds_NN2 ._. 
</s>
<s>
Trust_NN1 should_VM be_VBI regarded_VVN as_II a_AT1 highly_RR valuable_JJ organizational_JJ asset_NN1 (_( Valentini_NP1 ,_, 2010_MC )_) and_CC Desai_NP1 highlights_VVZ its_APPGE importance_NN1 in_II social_JJ marketing_NN1 where_CS the_AT parties_NN2 are_VBR seldom_RR present_JJ at_II the_AT same_DA location_NN1 and_CC where_CS the_AT client_NN1 has_VHZ to_TO rely_VVI on_II what_DDQ he_PPHS1 or_CC she_PPHS1 is_VBZ promised_VVN (_( about_II a_AT1 product_NN1 or_CC a_AT1 service_NN1 )_) ._. 
</s>
<s>
(_( Desai_NP1 ,_, 2009_MC )_) Also_RR ,_, trust_NN1 is_VBZ important_JJ within_II the_AT organization_NN1 ,_, as_CSA employees_NN2 seem_VV0 to_TO be_VBI more_RGR willing_JJ to_TO pass_VVI information_NN1 upwards_RL when_CS they_PPHS2 are_VBR encouraged_VVN to_TO do_VDI so_RR ._. 
</s>
<s>
(_( Mohr_NP1 &;_NULL Nevin_NP1 ,_, 1990_MC )_) The_AT WOM_NN1 network_NN1 is_VBZ constantly_RR expanding_JJ ,_, changing_VVG and_CC becoming_VVG more_RGR efficient_JJ ,_, which_DDQ in_II turn_NN1 sheds_NN2 light_VV0 on_II the_AT fact_NN1 that_CST marketers_NN2 should_VM be_VBI aware_JJ of_IO this_DD1 radical_JJ development_NN1 ._. 
</s>
<s>
(_( Scott_NP1 ,_, 2009_MC )_) Kozinets_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
note_VV0 that_CST their_APPGE new_JJ WOM_NN1 model_NN1 contributes_VVZ to_II marketers_NN2 awareness_NN1 of_IO the_AT multidimensionality_NN1 of_IO consumer_NN1 networks_NN2 and_CC the_AT communication_NN1 within_II them_PPHO2 ._. 
</s>
<s>
However_RR ,_, it_PPH1 does_VDZ not_XX necessarily_RR mean_VVI that_CST marketers_NN2 know_VV0 how_RRQ to_TO use_VVI the_AT information_NN1 they_PPHS2 have_VH0 and_CC to_TO grasp_VVI the_AT power_NN1 of_IO exchanged_JJ information_NN1 between_II consumers_NN2 ._. 
</s>
<s>
Some_DD marketers_NN2 are_VBR reluctant_JJ to_II this_DD1 idea_NN1 of_IO direct_JJ access_NN1 ,_, where_CS information_NN1 is_VBZ available_JJ for_IF anyone_PN1 ,_, anytime_NNT1 and_CC where_RRQ bloggers_NN2 are_VBR even_RR considered_VVN experts_NN2 in_II their_APPGE field_NN1 ,_, without_IW any_DD real_JJ experience_NN1 or_CC an_AT1 academic_JJ background_NN1 ._. 
</s>
<s>
Others_NN2 ,_, such_II21 as_II22 entrepreneurs_NN2 and_CC nonprofit_JJ executives_NN2 ,_, embrace_VV0 the_AT seemingly_RR unlimited_JJ ways_NN2 of_IO reaching_VVG buyers_NN2 and_CC customers_NN2 (_( Scott_NP1 ,_, 2009_MC )_) ._. 
</s>
<s>
In_II the_AT next_MD chapter_NN1 the_AT method_NN1 for_IF this_DD1 study_NN1 is_VBZ presented_VVN ._. 
</s>
<s>
Method_NN1 This_DD1 study_NN1 is_VBZ based_VVN on_II a_AT1 qualitative_JJ research_NN1 method_NN1 ,_, which_DDQ is_VBZ effective_JJ because_CS it_PPH1 has_VHZ the_AT /ability_NN1 to_TO get_VVI under_II the_AT surface_NN1 in_BCL21 order_BCL22 to_TO understand_VVI peoples_NN2 perceptions_NN2 and_CC experience._NNU (_( Silverman_NP1 ,_, 2006:6_MC )_) Seven_MC interviews_NN2 were_VBDR conducted_VVN over_II a_AT1 period_NN1 of_IO two_MC weeks_NNT2 at_II the_AT head_JJ quarters_NN of_IO the_AT representatives_NN2 offices_NN2 ._. 
</s>
<s>
The_AT respondents_NN2 are_VBR presented_VVN below_RL :_: Alex_NP1 Fager_NP1 ,_, Head_NN1 of_IO Programming_VVG at_II Yleisradio_NP1 Antti_NP1 Pasila_NP1 ,_, CEO_NN1 and_CC Partner_NN1 at_II Kiosked_JJ ,_, a_AT1 Finnish_JJ software_NN1 vendor_NN1 Tobias_NP2 Wacker_NN1 ,_, Strategist_NN1 at_II advertising_NN1 agency_NN1 Hasan_NP1 &;_NULL Partners_NN2 Jussi-Pekka_NP1 Erkkola_NP1 ,_, Digital_JJ Marketing_NN1 Manager_NN1 at_II Nokia_NP1 Christina_NP1 Forsgrd_NP1 ,_, Senior_JJ Consultant_NN1 and_CC Partner_NN1 at_II Netprofile_NP1 Valpuri_NP1 Mkinen_NP1 ,_, PR_NP1 Professional_JJ at_II Canon_NP1 Teija_NP1 Tamminen-Saremaa_NP1 ,_, Corporate_JJ and_CC Marketing_NN1 Communication_NN1 Manager_NN1 at_II Canon_NP1 Jonathan_NP1 Heino_NP1 ,_, Nordic_JJ Brand_NN1 Manager_NN1 at_II Unilever_NP1 The_AT companies_NN2 were_VBDR chosen_VVN from_II different_JJ sectors_NN2 ,_, as_CSA bloggers_NN2 are_VBR not_XX limited_VVN to_II a_AT1 certain_JJ field_NN1 ._. 
</s>
<s>
The_AT interviews_NN2 were_VBDR transcribed_VVN and_CC the_AT citations_NN2 analyzed_VVD in_II the_AT following_JJ way_NN1 :_: The_AT process_NN1 of_IO coding_NN1 can_VM be_VBI divided_VVN into_II three_MC groups_NN2 open_VV0 coding_NN1 ,_, axial_JJ coding_NN1 and_CC selective_JJ coding_NN1 ._. 
</s>
<s>
In_II open_JJ coding_NN1 the_AT collected_JJ data_NN will_VM be_VBI placed_VVN into_II conceptual_JJ units_NN2 ,_, followed_VVN by_II labels_NN2 ._. 
</s>
<s>
This_DD1 is_VBZ done_VDN ,_, as_CSA the_AT researchers_NN2 aim_VV0 is_VBZ to_TO understand_VVI the_AT meaning_NN1 of_IO the_AT content_NN1 ._. 
</s>
<s>
When_CS the_AT open_JJ coding_NN1 is_VBZ done_VDN ,_, the_AT next_MD step_NN1 is_VBZ to_TO recognize_VVI the_AT relationship_NN1 between_II the_AT categories_NN2 of_IO data_NN ,_, also_RR referred_VVN to_II as_RG axial_JJ coding_NN1 ._. 
</s>
<s>
These_DD2 in_II turn_NN1 are_VBR organized_VVN according_II21 to_II22 hierarchy_NN1 and_CC thus_RR ,_, subcategories_NN2 emerge_VV0 ._. 
</s>
<s>
Axial_JJ coding_NN1 is_VBZ used_VVN for_IF explaining_VVG a_AT1 phenomenon_NN1 and_CC for_IF looking_VVG into_II why_RRQ something_PN1 is_VBZ happening_VVG and_CC how_RRQ it_PPH1 evolves_VVZ ._. 
</s>
<s>
Selective_JJ coding_NN1 is_VBZ done_VDN over_II a_AT1 longer_JJR period_NN1 of_IO time_NNT1 ,_, when_RRQ the_AT core_NN1 or_CC main_JJ category_NN1 is_VBZ identified_VVN ._. 
</s>
<s>
Then_RT ,_, the_AT remaining_JJ categories_NN2 are_VBR linked_VVN to_II the_AT principal_JJ category_NN1 ,_, the_AT relationships_NN2 are_VBR studied_VVN and_CC finally_RR grounded_VVN theory_NN1 has_VHZ been_VBN formulated_VVN ._. 
</s>
<s>
(_( Saunders_NP1 et_RA21 al._RA22 ,_, 2007_MC )_) Material_NN1 The_AT respondents_NN2 point_VV0 out_RP how_RRQ time_VV0 consuming_VVG and_CC difficult_JJ it_PPH1 is_VBZ to_TO find_VVI the_AT right_JJ private_JJ bloggers_NN2 to_TO co-operate_VVI with_IW ._. 
</s>
<s>
Corporate_JJ representatives_NN2 need_VV0 to_TO screen_VVI the_AT blogs_NN2 and_CC follow_VVI them_PPHO2 for_IF a_AT1 long_JJ period_NN1 of_IO time_NNT1 ,_, in_BCL21 order_BCL22 to_TO get_VVI a_AT1 thorough_JJ understanding_NN1 of_IO who_PNQS the_AT person_NN1 is_VBZ behind_II the_AT produced_JJ content_NN1 ._. 
</s>
<s>
It_PPH1 requires_VVZ quite_RG a_AT1 lot_NN1 of_IO time_NNT1 to_TO find_VVI the_AT right_JJ blog_NN1 ._. 
</s>
<s>
You_PPY have_VH0 to_TO read_VVI it_PPH1 for_IF some_DD time_NNT1 and_CC skim_VVI through_II it_PPH1 and_CC form_VV0 a_AT1 picture_NN1 of_IO that_DD1 person_NN1 ,_, like_II who_PNQS is_VBZ this_DD1 and_CC what_DDQ could_VM we_PPIS2 ,_, for_IF the_AT readers_NN2 ,_, what_DDQ can_VM we_PPIS2 offer_VVI ,_, what_DDQ kind_NN1 of_IO commenting_VVG and_CC stories_NN2 are_VBR there_RL ._. 
</s>
<s>
People_NN &lsqb;_( private_JJ bloggers_NN2 &rsqb;_) do_VD0 get_VVI in_II31 contact_II32 with_II33 us_PPIO2 too_RR ,_, through_II the_AT web_NN1 site_NN1 or_CC then_RT theyve_VV0 heard_VVN it_PPH1 from_II someone_PN1 else_RR ._. 
</s>
<s>
They_PPHS2 apparently_RR have_VH0 good_JJ internal_JJ relations._NNU (_( Mkinen_NP1 ,_, Canon_NP1 ,_, 17.02.2011_MC )_) Private_JJ bloggers_NN2 actively_RR communicate_VV0 with_IW each_PPX221 other_PPX222 ,_, and_CC Mkinen_JJ sheds_NN2 light_VV0 on_II the_AT networks_NN2 that_CST are_VBR continuously_RR formed_VVN in_II the_AT blogosphere_NN1 ._. 
</s>
<s>
Word-of-mouth_NN1 flows_VVZ actively_RR between_II different_JJ parties_NN2 and_CC reach_VV0 finally_RR reach_VV0 the_AT blog_NN1 readers_NN2 ._. 
</s>
<s>
Quite_RG a_RR21 lot_RR22 is_VBZ about_II forming_VVG a_AT1 relationship_NN1 with_IW the_AT &lsqb;_( blog_NN1 &rsqb;_) reader/we_FU usually_RR call_VV0 it_PPH1 feeling_VVG ,_, information_NN1 and_CC entertainment_NN1 ._. 
</s>
<s>
Which_DDQ means_VVZ that_CST one_PN1 should_VM awaken_VVI some_DD feeling_NN1 ,_, contribute_VV0 with_IW some_DD kind_NN1 of_IO information_NN1 and_CC be_VBI entertaining_JJ ._. 
</s>
<s>
And_CC in_II that_DD1 way_NN1 form_VV0 a_AT1 contact_NN1 to_II the_AT audience_NN1 that_CST makes_VVZ it_PPH1 familiar_JJ with_IW you_PPY ._. 
</s>
<s>
And_CC if_CS it_PPH1 becomes_VVZ familiar_JJ with_IW you_PPY ,_, then_RT it_PPH1 &lsqb;_( the_AT audience_NN1 &rsqb;_) might_VM feel_VVI that_CST it_PPH1 knows_VVZ you_PPY in_II a_AT1 whole_JJ new_JJ way_NN1 and_CC in_II that_DD1 case_NN1 it_PPH1 wishes_VVZ to_TO come_VVI back_RP to_II what_DDQ you_PPY write_VV0 and_CC do_VD0 and_CC speak_VV0 about_II ._. 
</s>
<s>
That_DD1 is_VBZ our_APPGE primary_JJ strategy_NN1 for_IF addressing_VVG things._NNU (_( Fager_NP1 ,_, Yle_NP1 X3M_FO ,_, 07.02.2011_MC )_) Hence_RR ,_, Fager_NP1 stresses_VVZ the_AT importance_NN1 of_IO creating_VVG good_JJ content_NN1 ,_, which_DDQ the_AT blog_NN1 readers_NN2 and_CC private_JJ bloggers_NN2 may_VM have_VHI an_AT1 interest_NN1 in_II and_CC may_VM feel_VVI like_II sharing_VVG with_IW other_JJ community_NN1 members_NN2 ._. 
</s>
<s>
Furthermore_RR ,_, companies_NN2 work_VV0 with_IW private_JJ bloggers_NN2 with_IW the_AT intention_NN1 of_IO creating_VVG some_DD sort_NN1 of_IO marketing_NN1 and_CC spreading_JJ certain_JJ content_NN1 ._. 
</s>
<s>
To_II that_DD1 ,_, Wacker_NP1 speaks_VVZ about_II how_RRQ Hasan_NP1 &;_NULL Partners_NN2 engages_VVZ itself_PPX1 ,_, by_II31 means_II32 of_II33 sparking_VVG interaction_NN1 in_II the_AT blogosphere_NN1 ._. 
</s>
<s>
For_IF us_PPIO2 &lsqb;_( Hasan_NP1 &Partners];_NULL what_DDQ is_VBZ extremely_RR crucial_JJ is_VBZ engagement/For_FU me_PPIO1 WOM_NP1 works_VVZ in_II a_AT1 way_NN1 that_CST we_PPIS2 provide_VV0 communication_NN1 ,_, which_DDQ is_VBZ culturally_RR interesting_JJ for_IF people_NN so_CS21 that_CS22 they_PPHS2 would_VM like_VVI to_TO share_VVI it_PPH1 ._. 
</s>
<s>
So_RR we_PPIS2 have_VH0 to_TO go_VVI away_II21 from_II22 making_VVG advertising_NN1 ,_, which_DDQ is_VBZ talking_VVG about_II the_AT product_NN1 ,_, going_VVG towards_II communication/So_FU we_PPIS2 hope_VV0 that_CST people_NN are_VBR willing_JJ to_TO do_VDI the_AT WOM_NN1 thing_NN1 ._. 
</s>
<s>
Which_DDQ is_VBZ probably_RR today_RT more_RGR important_JJ in_II the_AT web_NN1 ,_, than_CSN just_RR telling_VVG verbally_RR ._. 
</s>
<s>
Because_CS it_PPH1 spreads_VVZ like_II a_AT1 hundred_NNO times_NNT2 faster_RRR and_CC immediately_RR wider._NNU (_( Wacker_NP1 ,_, Hasan_NP1 &Partners,;_NULL 11.02.2011_MC )_) Some_DD companies_NN2 are_VBR less_RRR (_( or_CC not_XX at_RR21 all_RR22 )_) engaged_VVD in_II the_AT creation_NN1 of_IO WOM_NP1 and_CC they_PPHS2 might_VM learn_VVI the_AT hard_JJ way_NN1 ,_, as_CSA personal_JJ recommendations_NN2 are_VBR crucial_JJ online_JJ and_CC in_II real_JJ life_NN1 ._. 
</s>
<s>
Nevertheless_RR ,_, WOM_NP1 can_VM be_VBI taken_VVN into_II consideration_NN1 in_II a_AT1 companys_NN2 communication_NN1 strategy_NN1 ,_, and_CC this_DD1 might_VM have_VHI an_AT1 impact_NN1 on_II the_AT consumers_NN2 ._. 
</s>
<s>
WOM_VV0 online_RR is_VBZ sort_RR21 of_RR22 like_VV0 you_PPY do_VD0 nt_XX pay_VVI attention_NN1 before_II its_APPGE too_RG late_JJ ._. 
</s>
<s>
You_PPY do_VD0 nt_XX get_VVI whats_NN2 going_VVG on_RP before_II its_APPGE in_II your_APPGE face._NNU (_( Heino_NP1 ,_, Unilever_NP1 ,_, 18.02.2011_MC )_) Then_RT it_PPH1 is_VBZ a_AT1 matter_NN1 about_II how_RGQ much_DA1 impact_NN1 private_JJ bloggers_NN2 in_II fact_NN1 have_VH0 over_II other_JJ consumers_NN2 ._. 
</s>
<s>
They_PPHS2 certainly_RR influence_VV0 their_APPGE loyal_JJ blog_NN1 readers_NN2 ,_, who_PNQS check_VV0 in_RP once_RR or_CC several_DA2 times_NNT2 a_AT1 day_NNT1 ._. 
</s>
<s>
But_CCB the_AT rest_NN1 most_RGT likely_RR remain_VV0 untouched_JJ ._. 
</s>
<s>
Although_CS every_AT1 blogger_NN1 would_VM write_VVI something_PN1 negative_JJ about_II Flora_NP1 &lsqb;_( dairy_NN1 brand_NN1 &rsqb;_) I_PPIS1 still_RR do_VD0 nt_XX believe_VVI that_CST we_PPIS2 would_VM lose_VVI much_RR in_II sales_NN ._. 
</s>
<s>
Because_CS its_APPGE only_RR a_AT1 certain_JJ part_NN1 of_IO the_AT consumers_NN2 who_PNQS go_VV0 in_RP and_CC check_NN1 ._. 
</s>
<s>
But_CCB if_CS it_PPH1 would_VM continue_VVI for_IF a_AT1 while_NNT1 ,_, then_RT the_AT sales_NN drop_NN1 would_VM slowly_RR be_VBI visible._NNU (_( Heino_NP1 ,_, Unilever_NP1 ,_, 18.02.2011_MC )_) Furthermore_RR ,_, there_EX are_VBR some_DD private_JJ bloggers_NN2 ,_, who_PNQS become_VV0 public_JJ figures_NN2 and_CC actively_RR join_VV0 different_JJ discussions_NN2 also_RR in_II other_JJ types_NN2 of_IO media_NN than_CSN just_RR blogs_VVZ ._. 
</s>
<s>
Outi_NN2 &lsqb;_( Vainionkulma-Immonen_NN1 ,_, employee_NN1 at_II Netprofile_NP1 &rsqb;_) has_VHZ in_II many_DA2 cases_NN2 been_VBN in_II the_AT media_NN commenting_VVG on_II topics_NN2 she_PPHS1 had_VHD written_VVN about_RP in_II her_APPGE blog_NN1 ,_, media_NN phenomena_NN2 ._. 
</s>
<s>
Discussion_NN1 in_II the_AT blog_NN1 just_RR continues._NNU (_( Forsgrd_NP1 ,_, 15.02.2011_MC )_) Companies_NN2 efforts_NN2 to_TO co-operate_VVI with_IW private_JJ bloggers_NN2 are_VBR grounded_VVN in_II the_AT hope_NN1 of_IO getting_VVG visibility_NN1 in_II blogs_NN2 ,_, where_CS specific_JJ target_NN1 groups_NN2 can_VM be_VBI reached_VVN in_II an_AT1 effective_JJ way_NN1 ._. 
</s>
<s>
There_EX is_VBZ hardly_RR any_DD recipe_NN1 for_IF how_RRQ to_TO communicate_VVI with_IW private_JJ bloggers_NN2 ,_, so_CS companies_NN2 might_VM as_RR21 well_RR22 try_VVI their_APPGE luck_NN1 ._. 
</s>
<s>
Often_RR ,_, the_AT outcome_NN1 can_VM be_VBI very_RG positive_JJ ._. 
</s>
<s>
Many_DA2 companies_NN2 would_VM like_VVI to_TO be_VBI seen_VVN in_II private_JJ blogs/If_FU your_APPGE blog_NN1 is_VBZ about_II German_JJ schlager_NN1 from_II the_AT 1970s_MC2 and_CC you_PPY have_VH0 500_MC readers_NN2 ,_, then_RT you_PPY have_VH0 a_AT1 product_NN1 ._. 
</s>
<s>
Because_CS they_PPHS2 would_VM probably_RR have_VHI 95%_NNU of_IO the_AT customers_NN2 interested_JJ in_II a_AT1 product_NN1 that_CST would_VM fit_VVI in_II there_RL ._. 
</s>
<s>
But_CCB it_PPH1 might_VM be_VBI that_RG only_RR 200_MC of_IO those_DD2 500_MC blog_NN1 readers_NN2 read_VV0 the_AT same_DA article_NN1 published_VVN in_II Helsingin_NP1 Sanomat_NP1 &lsqb;_( a_AT1 Finnish_JJ news_NN1 paper_NN1 &rsqb;_) ._MC (_( Pasila_NP1 ,_, Kiosked_JJ ,_, 10.02.2011_MC )_) Analysis_NN1 According_II21 to_II22 the_AT study_NN1 ,_, it_PPH1 is_VBZ evident_JJ that_CST companies_NN2 are_VBR aware_JJ of_IO the_AT power_NN1 of_IO private_JJ bloggers_NN2 and_CC their_APPGE ability_NN1 to_TO influence_VVI consumers_NN2 ._. 
</s>
<s>
The_AT way_NN1 that_CST marketers_NN2 work_VV0 today_RT is_VBZ very_RG different_JJ from_II ten_MC years_NNT2 ago_RA ,_, when_CS the_AT Internet_NN1 was_VBDZ still_RR quite_RG a_AT1 new_JJ tool_NN1 ._. 
</s>
<s>
Today_RT social_JJ media_NN and_CC blogs_NN2 are_VBR widely_RR used_VVN for_IF different_JJ purposes_NN2 and_CC at_II a_AT1 very_RG low_JJ cost_NN1 ._. 
</s>
<s>
This_DD1 offers_VVZ companies_NN2 great_JJ opportunities_NN2 to_TO reach_VVI blog_NN1 readers_NN2 and_CC specific_JJ target_NN1 groups_NN2 ,_, who_PNQS actively_RR communicate_VV0 with_IW each_PPX221 other_PPX222 and_CC spread_VV0 information_NN1 within_II their_APPGE communities_NN2 ._. 
</s>
<s>
Private_JJ bloggers_NN2 are_VBR considered_VVN highly_RR trustworthy_JJ ,_, as_CSA they_PPHS2 express_VV0 their_APPGE opinions_NN2 in_II their_APPGE own_DA forum_NN1 ._. 
</s>
<s>
Therefore_RR ,_, they_PPHS2 are_VBR not_XX directly_RR paid_VVN to_TO write_VVI in_II a_AT1 certain_JJ way_NN1 and_CC they_PPHS2 can_VM freely_RR choose_VVI their_APPGE topics_NN2 ._. 
</s>
<s>
Therefore_RR ,_, it_PPH1 is_VBZ even_RR more_RGR important_JJ for_IF companies_NN2 to_TO create_VVI really_RR good_JJ content_NN1 and_CC products_NN2 ,_, in_BCL21 order_BCL22 to_TO spark_VVI Internet_NN1 users_NN2 interest_NN1 ._. 
</s>
<s>
In_II contrast_NN1 ,_, bad_JJ content_NN1 might_VM also_RR be_VBI popular_JJ online_JJ ,_, but_CCB the_AT question_NN1 is_VBZ how_RRQ that_DD1 affects_VVZ a_AT1 companys_NN2 image_NN1 ._. 
</s>
<s>
Furthermore_RR ,_, it_PPH1 is_VBZ evident_JJ that_CST companies_NN2 need_VV0 to_TO build_VVI relationships_NN2 with_IW private_JJ bloggers_NN2 ,_, who_PNQS are_VBR individuals_NN2 and_CC like_VV0 to_TO be_VBI treated_VVN as_II such_DA ._. 
</s>
<s>
There_EX is_VBZ hardly_RR any_DD point_NN1 in_II treating_VVG all_DB private_JJ bloggers_NN2 equally_RR ,_, as_CSA they_PPHS2 do_VD0 not_XX share_VVI interests_NN2 or_CC background_NN1 ._. 
</s>
<s>
To_II that_DD1 ,_, the_AT creating_NN1 of_IO WOM_NN1 is_VBZ largely_RR linked_VVN to_II the_AT blog_NN1 readers_NN2 ,_, who_PNQS often_RR stay_VV0 true_JJ to_II their_APPGE favorite_JJ private_JJ bloggers_NN2 ,_, which_DDQ explains_VVZ why_RRQ it_PPH1 is_VBZ so_RG important_JJ for_IF companies_NN2 to_TO relate_VVI to_II them_PPHO2 ._. 
</s>
<s>
Conclusion_NN1 In_II41 the_II42 light_II43 of_II44 this_DD1 study_NN1 it_PPH1 is_VBZ clear_JJ that_CST companies_NN2 should_VM co-operate_VVI with_IW private_JJ bloggers_NN2 ,_, in_BCL21 order_BCL22 to_TO create_VVI word-of-mouth_NN1 ._. 
</s>
<s>
It_PPH1 has_VHZ widely_RR been_VBN agreed_VVN that_CST WOM_NP1 is_VBZ the_AT most_RGT effective_JJ way_NN1 to_TO reach_VVI out_RP to_II consumers_NN2 ,_, often_RR much_RR more_RGR effective_JJ than_CSN any_DD other_JJ type_NN1 of_IO marketing_NN1 ._. 
</s>
<s>
Therefore_RR ,_, it_PPH1 might_VM be_VBI a_AT1 good_JJ idea_NN1 for_IF companies_NN2 to_TO formulate_VVI strategies_NN2 ,_, which_DDQ aim_VV0 at_II fostering_VVG this_DD1 idea_NN1 and_CC finding_VVG new_JJ ways_NN2 of_IO communicating_VVG certain_JJ information_NN1 to_II different_JJ parties_NN2 ._. 
</s>
<s>
The_AT financial_JJ crisis_NN1 has_VHZ also_RR forced_VVN companies_NN2 to_TO lower_VVI their_APPGE costs_NN2 and_CC to_TO cut_VVI down_RP their_APPGE resources_NN2 ._. 
</s>
<s>
Therefore_RR ,_, the_AT importance_NN1 of_IO co-operation_NN1 with_IW private_JJ bloggers_NN2 becomes_VVZ more_RGR important_JJ ,_, due_II21 to_II22 the_AT cost-effective_JJ and_CC diverse_JJ nature_NN1 of_IO the_AT marketing_NN1 ._. 
</s>
<s>
Word-of-mouth_NN1 is_VBZ such_DA a_AT1 simple_JJ concept_NN1 ,_, but_CCB yet_RR so_RG challenging_JJ to_TO create_VVI for_IF the_AT right_JJ object_NN1 ,_, at_II the_AT right_JJ time_NNT1 ._. 
</s>
