<s>
Research_NN1 questions_NN2 :_: Is_VBZ precaution_NN1 needed_VVN ?_? 
</s>
<s>
Is_VBZ precaution_NN1 justified_VVN ?_? 
</s>
<s>
Research_NN1 problem_NN1 :_: Could_VM there_EX be_VBI too_RG much_DA1 precaution_NN1 ?_? 
</s>
<s>
Field_NN1 of_IO study_NN1 :_: Precaution_NN1 in_II humans_NN2 behavior_NN1 explained_VVN form_VV0 the_AT economic_JJ point_NN1 of_IO view_NN1 ._. 
</s>
<s>
Methods_NN2 of_IO research_NN1 :_: Quantative_JJ analysis_NN1 ,_, case_NN1 study_NN1 ,_, historical_JJ logical_JJ method_NN1 ._. 
</s>
<s>
Relevance_NN1 of_IO the_AT study_NN1 :_: The_AT subject_NN1 of_IO the_AT paper_NN1 is_VBZ level_JJ of_IO taking_VVG precaution_NN1 ._. 
</s>
<s>
The_AT research_NN1 focuses_VVZ on_II the_AT importance_NN1 of_IO precaution_NN1 and_CC on_II the_AT issue_NN1 whether_CSW precaution_NN1 could_VM be_VBI over_RP invested_VVN ._. 
</s>
<s>
To_TO be_VBI able_JK to_TO answer_VVI these_DD2 questions_NN2 ,_, the_AT probability_NN1 of_IO an_AT1 accident_NN1 and_CC approximated_VVD loss_NN1 should_VM be_VBI outlined_VVN ._. 
</s>
<s>
Actual_JJ marginal_JJ costs_NN2 of_IO precaution_NN1 could_VM be_VBI counted_VVN by_II multiplying_VVG these_DD2 two_MC indicators_NN2 ,_, then_RT comparing_VVG the_AT result_NN1 with_IW precaution_NN1 costs_NN2 taken_VVN ._. 
</s>
<s>
It_PPH1 is_VBZ crucial_JJ not_XX to_II overestimate_NN1 precaution_NN1 ,_, but_CCB ,_, at_II the_AT same_DA time_NNT1 ,_, to_TO investigate_VVI the_AT proper_JJ degree_NN1 of_IO it_PPH1 ._. 
</s>
<s>
With_IW the_AT help_NN1 of_IO cost_NN1 and_CC benefit_VV0 analysis_NN1 ,_, it_PPH1 is_VBZ possible_JJ to_TO explain_VVI human_JJ behavior_NN1 ,_, both_RR victims_NN2 and_CC injurers_NN2 ,_, and_CC rise_VV0 an_AT1 issues_NN2 of_IO further_RRR reducing_VVG the_AT law_NN1 cases_NN2 in_II courts_NN2 ._. 
</s>
<s>
If_CS the_AT precaution_NN1 is_VBZ overestimated_VVN ,_, victim_NN1 pays_VVZ for_IF the_AT accident_NN1 ,_, if_CS precaution_NN1 is_VBZ underestimated_VVN ;_; it_PPH1 is_VBZ time_NNT1 for_IF the_AT injurer_NN1 to_TO pay_VVI back_RP ._. 
</s>
<s>
Basically_RR ,_, injurer_NN1 underestimates_VVZ precaution_NN1 usually_RR ,_, however_RRQV the_AT more_RRR the_AT injurer_NN1 spends_VVZ on_II precaution_NN1 ,_, the_AT less_RRR remains_VVZ for_IF compensation_NN1 in_II31 case_II32 of_II33 accident_NN1 and_CC the_AT less_RRR the_AT probability_NN1 of_IO an_AT1 accident_NN1 is_VBZ ._. 
</s>
<s>
The_AT research_NN1 touches_VVZ upon_II spheres_NN2 in_II which_DDQ certain_JJ level_NN1 of_IO precaution_NN1 is_VBZ necessary_JJ :_: industrial_JJ ,_, medical_JJ ,_, environmental_JJ and_CC others_NN2 ._. 
</s>
<s>
Introduction_NN1 People_NN face_VV0 risk_VV0 every_AT1 day_NNT1 ._. 
</s>
<s>
While_CS crossing_VVG the_AT road_NN1 ,_, using_VVG electronic_JJ devices_NN2 ,_, undergoing_VVG medical_JJ procedures_NN2 they_PPHS2 become_VV0 potential_JJ victims_NN2 ._. 
</s>
<s>
At_II the_AT same_DA time_NNT1 ,_, drivers_NN2 ,_, electronic_JJ engineers_NN2 and_CC doctors_NN2 are_VBR unintentionally_RR potential_JJ injurers_NN2 ._. 
</s>
<s>
However_RR ,_, such_DA term_NN1 as_CSA precaution_NN1 exists_VVZ ,_, which_DDQ is_VBZ a_AT1 preliminary_JJ measure_NN1 ,_, sort_NN1 of_IO guarantee_NN1 of_IO victims_NN2 safety_NN1 ._. 
</s>
<s>
Basically_RR ,_, taking_VVG precaution_NN1 means_VVZ spending_NN1 money_NN1 on_II it_PPH1 ._. 
</s>
<s>
Here_RL the_AT question_NN1 arises_VVZ whether_CSW to_TO take_VVI precaution_NN1 or_CC not_XX ._. 
</s>
<s>
Here_RL the_AT probability_NN1 of_IO accident_NN1 is_VBZ something_PN1 that_CST makes_VVZ a_AT1 real_JJ difference_NN1 ._. 
</s>
<s>
How_RGQ much_DA1 money_NN1 potential_NN1 injurer_NN1 needs_VVZ to_TO spend_VVI on_II precaution_NN1 if_CS there_EX probability_NN1 of_IO the_AT accident_NN1 is_VBZ miserable_JJ ?_? 
</s>
<s>
Whether_CSW there_EX is_VBZ such_DA thing_NN1 as_CSA too_RG much_DA1 precaution_NN1 ?_? 
</s>
<s>
How_RRQ to_TO balance_VVI costs_NN2 on_II precaution_NN1 and_CC compensation_NN1 ?_? 
</s>
<s>
G._NP1 D._NP1 Mattiacci_NP1 and_CC G._NP1 D._NP1 Geest_NP1 suggest_VV0 that_CST the_AT more_RRR the_AT injurer_NN1 spends_VVZ on_II precaution_NN1 ,_, the_AT less_RRR remains_VVZ available_JJ for_IF compensation_NN1 ._. 
</s>
<s>
But_CCB if_CS the_AT accident_NN1 means_VVZ victims_NN2 death_NN1 ,_, then_RT the_AT price_NN1 of_IO precaution_NN1 is_VBZ closely_RR connected_VVN to_II the_AT value_NN1 of_IO persons_NN2 life_NN1 ._. 
</s>
<s>
The_AT value_NN1 of_IO life_NN1 should_VM be_VBI measured_VVN in_II concrete_JJ sums_NN2 ,_, in_II money_NN1 ._. 
</s>
<s>
S._NP1 E._NP1 Landsburg_NP1 and_CC other_JJ economists_NN2 (_( 2003_MC )_) claim_VV0 that_CST human_JJ life_NN1 costs_VVZ $8_NNU million_NNO ._. 
</s>
<s>
Other_JJ researches_NN2 (_( K._NP1 Viscusi_NP1 ,_, 1970_MC )_) estimates_VVZ life_NN1 value_NN1 at_II $5_NNU million_NNO ._. 
</s>
<s>
So_RR it_PPH1 is_VBZ generally_RR accepted_VVN that_CST the_AT price_NN1 of_IO life_NN1 escalates_VVZ ,_, human_JJ life_NN1 is_VBZ becoming_VVG more_RGR precious_JJ and_CC thus_RR taking_VVG precaution_NN1 makes_VVZ a_AT1 real_JJ difference_NN1 ._. 
</s>
<s>
Consequently_RR ,_, from_II the_AT injurers_NN2 point_NN1 of_IO view_NN1 ,_, it_PPH1 is_VBZ always_RR better_JJR to_TO take_VVI precaution_NN1 than_CSN face_VV0 the_AT necessity_NN1 of_IO compensation_NN1 ._. 
</s>
<s>
However_RR ,_, here_RL this_DD1 view_NN1 is_VBZ challenged_VVN by_II the_AT concept_NN1 of_IO moral_JJ hazard_NN1 ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, when_CS the_AT precaution_NN1 is_VBZ taken_VVN ,_, the_AT potential_JJ victim_NN1 can_VM afford_VVI him/herself_FU more_DAR risk_NN1 ._. 
</s>
<s>
For_REX21 instance_REX22 ,_, if_CS the_AT one_PN1 wears_VVZ seat_NN1 belt_NN1 ,_, he/she_PPHS1 is_VBZ less_RGR attentive_JJ on_II the_AT road_NN1 then_RT when_CS driving_VVG without_IW such_DA precaution_NN1 ._. 
</s>
<s>
There_EX seems_VVZ to_TO be_VBI conflict_NN1 between_II the_AT legislators_NN2 intention_NN1 and_CC the_AT perception_NN1 of_IO drivers_NN2 ._. 
</s>
<s>
The_AT paper_NN1 focuses_VVZ on_II investigating_VVG the_AT consequences_NN2 of_IO seat_NN1 belts_NN2 legislation_NN1 in_II31 terms_II32 of_II33 changes_NN2 in_II death_NN1 rate_NN1 and_CC injury_NN1 rate_NN1 of_IO drivers_NN2 ._. 
</s>
<s>
The_AT question_NN1 is_VBZ ,_, whether_CSW the_AT seat_NN1 belt_NN1 causes_VVZ more_DAR injuries_NN2 ?_? 
</s>
<s>
Here_RL ,_, we_PPIS2 report_VV0 the_AT link_NN1 between_II the_AT cost_NN1 of_IO precaution_NN1 and_CC the_AT consequences_NN2 of_IO it_PPH1 ._. 
</s>
<s>
The_AT paper_NN1 hopes_VVZ to_TO show_VVI that_CST there_EX is_VBZ such_DA thing_NN1 as_CSA too_RG much_DA1 precaution_NN1 which_DDQ in_II fact_NN1 causes_VVZ the_AT issue_NN1 of_IO moral_JJ hazard_NN1 ._. 
</s>
<s>
The_AT paper_NN1 is_VBZ structures_NN2 as_CSA follows_VVZ :_: well_RR start_VV0 with_IW theoretical_JJ overview_NN1 of_IO the_AT terms_NN2 ;_; move_VV0 to_II the_AT practical_JJ examples_NN2 and_CC calculation_NN1 ;_; and_CC finally_RR ,_, analyze_VV0 the_AT results_NN2 and_CC make_VV0 conclusions_NN2 ._. 
</s>
<s>
Literature_NN1 review_NN1 In_II the_AT last_MD decade_NNT1 several_DA2 researches_NN2 concerning_II the_AT issue_NN1 of_IO precaution_NN1 principle_NN1 were_VBDR conducted_VVN in_II different_JJ spheres_NN2 of_IO life_NN1 ._. 
</s>
<s>
The_AT most_RGT common_JJ spheres_NN2 where_RRQ the_AT issue_NN1 of_IO precaution_NN1 is_VBZ implemented_VVN are_VBR medicine_NN1 ,_, agricultural_JJ sector_NN1 ,_, court_NN1 cases_NN2 ,_, road_NN1 accidents_NN2 and_CC others_NN2 ._. 
</s>
<s>
In_II his_APPGE article_NN1 The_AT Price_NN1 of_IO Precaution_NN1 and_CC the_AT Ethics_NN of_IO Risk_NN1 ,_, medical_JJ engineer_NN1 M._NN1 Berstein_NP1 claims_VVZ that_DD1 precaution_NN1 and_CC risk_NN1 are_VBR inseparable_JJ ._. 
</s>
<s>
And_CC states_VVZ that_CST the_AT precaution_NN1 and_CC its_APPGE price_NN1 not_XX only_RR correspond_VV0 ,_, but_CCB in_II some_DD cases_NN2 the_AT price_NN1 becomes_VVZ a_AT1 risk_NN1 ._. 
</s>
<s>
The_AT gold_NN1 scammers_NN2 are_VBR the_AT ones_NN2 who_PNQS should_VM use_VVI the_AT precaution_NN1 principle_NN1 in_BCL21 order_BCL22 to_TO manage_VVI their_APPGE risks_NN2 and_CC profit_NN1 ._. 
</s>
<s>
However_RR ,_, there_EX are_VBR very_RG few_DA2 findings_NN2 concentrated_VVN on_II precaution_NN1 in_II economics_NN1 ._. 
</s>
<s>
The_AT paper_NN1 aims_VVZ to_TO represent_VVI one_PN1 ._. 
</s>
<s>
Framework_NN1 In_II the_AT paper_NN1 the_AT following_JJ methods_NN2 are_VBR represented_VVN :_: analysis_NN1 ,_, comparison_NN1 ,_, graphic_JJ data_NN representation_NN1 ._. 
</s>
<s>
The_AT economic_JJ analysis_NN1 will_VM be_VBI done_VDN ._. 
</s>
<s>
Cost_NN1 of_IO precaution_NN1 :_: economic_JJ perspective_NN1 Nowadays_RT one_MC1 of_IO the_AT most_RGT debatable_JJ issue_NN1 discussed_VVN by_II economists_NN2 is_VBZ Nokia_NP1 case_NN1 ._. 
</s>
<s>
The_AT precaution_NN1 principle_NN1 will_VM be_VBI investigated_VVN from_II economic_JJ perspective_NN1 ._. 
</s>
<s>
Nokias_NP2 CEO_NN1 cancellation_NN1 of_IO Symbian_JJ platform_NN1 could_VM be_VBI looked_VVN at_II under_II the_AT precaution_NN1 point_NN1 of_IO view_NN1 ._. 
</s>
<s>
The_AT data_NN used_VVN for_IF analysis_NN1 :_: the_AT probability_NN1 of_IO Windows_NP1 Phone_NN1 7_MC success_NN1 ,_, the_AT cost_NN1 of_IO market_NN1 research_NN1 ,_, the_AT alternative_JJ costs_NN2 ,_, the_AT potential_JJ loss_NN1 ._. 
</s>
<s>
In_II this_DD1 case_NN1 CEO_NN1 Stephen_NP1 Elop_NP1 is_VBZ considered_VVN to_TO be_VBI injurer_NN1 ,_, because_CS it_PPH1 was_VBDZ his_APPGE personal_JJ initiative_NN1 to_TO scrap_VVI Symbian_JJ platform_NN1 ._. 
</s>
<s>
And_CC Nokia_NP1 Corporation_NN1 will_VM represent_VVI the_AT victim_NN1 side_NN1 ._. 
</s>
<s>
The_AT injurer_NN1 did_VDD not_XX have_VHI intention_NN1 to_TO cause_VVI losses_NN2 for_IF the_AT company_NN1 ,_, so_CS the_AT precaution_NN1 principle_NN1 could_VM be_VBI implemented_VVN ._. 
</s>
<s>
Discussion_NN1 and_CC conclusions_NN2 
</s>
