<s>
Introduction_NN1 Todays_NN2 business_NN1 organization_NN1 is_VBZ a_AT1 competitive_JJ environment_NN1 where_CS only_RR the_AT strongest_JJT survive_VV0 ._. 
</s>
<s>
This_DD1 statement_NN1 applies_VVZ especially_RR to_II the_AT leaders_NN2 ,_, who_PNQS are_VBR accountable_JJ for_IF how_RRQ the_AT organization_NN1 performs_VVZ Therefore_RR ,_, the_AT question_NN1 :_: What_DDQ makes_VVZ a_AT1 good_JJ leader_NN1 ?_? is_VBZ commonly_RR asked_VVN in_RP nearly_RR all_DB of_IO the_AT organizations_NN2 regardless_RR of_IO the_AT purpose_NN1 the_AT organization_NN1 serves_VVZ ._. 
</s>
<s>
Although_CS there_EX is_VBZ a_AT1 lot_NN1 of_IO research_NN1 available_JJ on_II the_AT subject_NN1 ,_, no_AT clear_JJ explanation_NN1 of_IO what_DDQ makes_VVZ an_AT1 effective_JJ leader_NN1 has_VHZ emerged_VVN ,_, which_DDQ would_VM apply_VVI to_II all_DB organizations_NN2 ._. 
</s>
<s>
A_AT1 commonly_RR used_JJ practice_NN1 in_II leadership_NN1 research_NN1 is_VBZ to_TO analyze_VVI successful_JJ organizations_NN2 and_CC particularly_RR their_APPGE leaders_NN2 leadership_NN1 methods_NN2 ._. 
</s>
<s>
One_MC1 of_IO the_AT most_RGT cited_JJ leadership_NN1 researcher_NN1 is_VBZ Daniel_NP1 Goleman_NP1 ,_, an_AT1 American_JJ psychologist_NN1 and_CC science_NN1 journalist_NN1 ,_, who_PNQS studied_VVD some_DD 200_MC large_JJ global_JJ companies_NN2 in_BCL21 order_BCL22 to_TO distinguish_VVI the_AT qualities_NN2 that_CST are_VBR associated_VVN with_IW effective_JJ leadership_NN1 ._. 
</s>
<s>
Goleman_NP1 came_VVD up_RP with_IW an_AT1 insight_NN1 that_CST qualities_NN2 such_II21 as_II22 a_AT1 high_JJ IQ_NN1 ,_, determination_NN1 ,_, toughness_NN1 ,_, and_CC vision_NN1 that_CST are_VBR traditionally_RR linked_VVN with_IW successful_JJ leadership_NN1 are_VBR insufficient_JJ without_IW so_JJ21 called_JJ22 soft_JJ qualities_NN2 of_IO leadership_NN1 ._. 
</s>
<s>
According_II21 to_II22 Goleman_NP1 ,_, the_AT soft_JJ qualities_NN2 include_VV0 self-awareness_NN1 ,_, self-regulation_NN1 ,_, motivation_NN1 ,_, empathy_NN1 ,_, and_CC social_JJ skills_NN2 ._. 
</s>
<s>
Goleman_NP1 published_VVD his_APPGE findings_NN2 in_II a_AT1 book_NN1 called_VVN Emotional_JJ Intelligence_NN1 (_( EI_NP1 )_) in_II 1995_MC ._. 
</s>
<s>
One_MC1 of_IO the_AT most_RGT interesting_JJ and_CC consequently_RR one_MC1 of_IO the_AT most_RGT analyzed_JJ organizations_NN2 is_VBZ Apple_NN1 ._. 
</s>
<s>
The_AT research_NN1 has_VHZ focused_VVN on_II Apples_NN2 previous_JJ chief_JJ executive_NN1 officer_NN1 ,_, Steve_NP1 Jobs_NN2 ,_, who_PNQS passed_VVD away_RL in_II October_NPM1 2011_MC ._. 
</s>
<s>
Jobs_NN2 is_VBZ often_RR considered_VVN as_CSA one_MC1 of_IO the_AT best_JJT leaders_NN2 of_IO this_DD1 century_NNT1 ,_, and_CC as_II a_AT1 result_NN1 ,_, his_APPGE leadership_NN1 skills_NN2 have_VH0 been_VBN under_RG close_JJ scrutiny_NN1 ._. 
</s>
<s>
What_DDQ is_VBZ fascinating_JJ is_VBZ that_CST Steve_NP1 Jobs_NN2 cofounded_VVD Apple_NN1 in_II his_APPGE parents_NN2 garage_NN1 in_II 1976_MC ,_, was_VBDZ expelled_VVN in_II 1985_MC ,_, but_CCB returned_VVD in_II 1997_MC to_TO rescue_VVI Apple_NN1 from_II near_JJ bankruptcy_NN1 ._. 
</s>
<s>
On_II the_AT day_NNT1 Jobs_NN2 passed_VVN away_RL ,_, Apple_NN1 was_VBDZ the_AT worlds_NN2 most_RGT valuable_JJ brand_NN1 and_CC the_AT company_NN1 was_VBDZ ranked_VVN by_II several_DA2 sources_NN2 as_II the_AT number_NN1 one_MC1 company_NN1 in_II the_AT world_NN1 &lsqb;_( Fortune_NN1 Magazines_NN2 List_NN1 of_IO Worlds_NN2 Most_RGT Admired_JJ Companies_NN2 2011_MC ,_, Millward_NP1 Brown_NP1 's_GE Brandz_NP1 100_MC ranking_NN1 ,_, 2011_MC &rsqb;_) ._. 
</s>
<s>
The_AT positive_JJ correlation_NN1 between_II Jobs_NN2 presence_NN1 as_II the_AT CEO_NN1 of_IO Apple_NN1 and_CC Apples_NN2 astonishing_JJ success_NN1 as_II a_AT1 company_NN1 leads_VVZ us_PPIO2 naturally_RR to_II the_AT question_NN1 on_II how_RRQ Jobs_NN2 managed_VVD to_TO do_VDI this_DD1 and_CC what_DDQ made_VVD him_PPHO1 such_DA a_AT1 successful_JJ leader_NN1 ?_? 
</s>
<s>
This_DD1 question_NN1 is_VBZ even_RR more_RGR interesting_JJ because_CS Jobs_NN2 reputation_NN1 as_II a_AT1 manager_NN1 of_IO people_NN was_VBDZ not_XX unusually_RR high_JJ ;_; on_II the_AT contrary_NN1 ,_, he_PPHS1 was_VBDZ perceived_VVN as_CSA being_VBG excessively_RR demanding_VVG or_CC sometimes_RT even_RR tyrannical_JJ ._. 
</s>
<s>
Some_DD even_RR labeled_JJ Apple_NN1 as_CSA one_MC1 of_IO the_AT worst-managed_JJT companies_NN2 in_II the_AT industry_NN1 ._. 
</s>
<s>
Evidently_RR ,_, Golemans_NN2 study_VV0 regarding_II the_AT necessary_JJ soft_JJ leadership_NN1 qualities_NN2 does_VDZ not_XX seem_VVI to_TO fully_RR apply_VVI to_II Steve_NP1 Jobss_NP1 success_NN1 as_II a_AT1 leader_NN1 ._. 
</s>
<s>
Jobs_NN2 obviously_RR did_VDD not_XX possess_VVI all_DB of_IO the_AT soft_JJ qualities_NN2 Goleman_NP1 suggested_VVD ,_, but_CCB still_RR ,_, Jobs_NN2 managed_VVD to_TO lead_VVI Apple_NN1 from_II near_JJ destruction_NN1 to_II the_AT top_NN1 ._. 
</s>
<s>
What_DDQ were_VBDR the_AT soft_JJ qualities_NN2 that_CST Jobs_NN2 possessed_VVD ,_, what_DDQ were_VBDR lacking_VVG ,_, and_CC how_RRQ this_DD1 affected_VVD the_AT Apples_NN2 organization_NN1 and_CC eventually_RR the_AT people_NN who_PNQS worked_VVD for_IF the_AT company_NN1 ?_? 
</s>
<s>
The_AT paper_NN1 is_VBZ structured_VVN as_CSA follows_VVZ ._. 
</s>
<s>
The_AT first_MD section_NN1 describes_VVZ the_AT motivation_NN1 and_CC the_AT objective_NN1 of_IO this_DD1 study_NN1 ,_, including_II the_AT research_NN1 questions_NN2 ._. 
</s>
<s>
The_AT second_MD part_NN1 describes_VVZ the_AT theory_NN1 of_IO Emotional_JJ Intelligence_NN1 and_CC tries_VVZ to_TO identify_VVI how_RRQ it_PPH1 applied_VVD to_II Steve_NP1 Jobs_NN2 leadership_NN1 style_NN1 if_CS at_RR21 all_RR22 ._. 
</s>
<s>
The_AT third_MD section_NN1 summarizes_VVZ the_AT findings_NN2 ._. 
</s>
<s>
Emotional_JJ Intelligence_NN1 In_II this_DD1 chapter_NN1 ,_, I_PPIS1 will_VM explain_VVI the_AT theory_NN1 of_IO emotional_JJ intelligence_NN1 (_( not_XX ready_RR yet_RR )_) ._. 
</s>
<s>
In_II the_AT following_JJ chapter_NN1 I_PPIS1 will_VM describe_VVI Steve_NP1 Jobs_NN2 life_NN1 story_NN1 ._. 
</s>
<s>
Then_RT I_PPIS1 will_VM analyze_VVI what_DDQ kind_NN1 of_IO impact_NN1 Jobs_NN2 personal_JJ life_NN1 had_VHD on_II his_APPGE way_NN1 of_IO leading_JJ people_NN ,_, and_CC how_RGQ emotional_JJ intelligence_NN1 was_VBDZ reflected_VVN in_II Jobs_NN2 leadership_NN1 practices_NN2 if_CS at_RR21 all_RR22 ._. 
</s>
<s>
The_AT last_MD chapter_NN1 summarizes_VVZ my_APPGE findings_NN2 (_( if_CS there_EX are_VBR any_DD ;_; )_) )_) ._. 
</s>
<s>
Emotional_JJ Intelligence_NN1 (_( EI_NP1 )_) is_VBZ a_AT1 relatively_RR recent_JJ behavioral_JJ mode_NN1 ,_, first_MD introduced_VVN by_II Daniel_NP1 Goleman_NP1 in_II 1995_MC ._. 
</s>
<s>
Goleman_NP1 argued_VVD that_CST from_II the_AT leadership_NN1 skills_NN2 perspective_NN1 ,_, the_AT so_JJ21 called_JJ22 conventional_JJ intelligence_NN1 ,_, often_RR measured_VVN by_II an_AT1 intelligence_NN1 quotient_NN1 (_( IQ_NN1 )_) ,_, is_VBZ almost_RR futile_JJ without_IW the_AT qualities_NN2 of_IO Emotional_JJ Intelligence_NN1 ._. 
</s>
<s>
IQ_NN1 ignores_VVZ the_AT essential_JJ behavioral_JJ elements_NN2 of_IO intelligence_NN1 and_CC consequently_RR is_VBZ not_XX a_AT1 suitable_JJ way_NN1 measuring_VVG someones_NN2 leadership_NN1 skills_NN2 ._. 
</s>
<s>
We_PPIS2 have_VH0 all_RR met_VVN people_NN who_PNQS are_VBR extremely_RR intelligent_JJ and_CC yet_RR are_VBR socially_RR and_CC inter-personally_RR inept_JJ ._. 
</s>
<s>
Furthermore_RR ,_, we_PPIS2 know_VV0 that_CST having_VHG a_AT1 high_JJ IQ_NN1 does_VDZ not_XX mean_VVI that_CST you_PPY will_VM have_VHI a_AT1 successful_JJ career_NN1 nor_CC says_VVZ that_CST you_PPY will_VM become_VVI an_AT1 excellent_JJ leader_NN1 ._. 
</s>
<s>
Steve_NP1 Jobs_NN2 life_NN1 Steve_NP1 Jobs_NN2 passed_VVN away_RL on_II October_NPM1 5_MC ,_, 2011_MC ,_, at_II an_AT1 age_NN1 of_IO 56_MC ._. 
</s>
<s>
Although_CS over_RG a_AT1 year_NNT1 has_VHZ gone_VVN by_II ,_, Jobs_NN2 biography_NN1 is_VBZ one_MC1 of_IO the_AT bestselling_JJ biographies_NN2 available_JJ ._. 
</s>
<s>
Steve_NP1 Jobs_NN2 life_NN1 started_VVD on_II February_NPM1 24_MC ,_, 1955_MC ,_, in_II Wisconsin_NP1 ,_, United_NP1 States_NP1 ,_, when_CS he_PPHS1 was_VBDZ born_VVN to_II two_MC University_NN1 of_IO Wisconsin_NP1 graduate_NN1 students_NN2 ,_, Joanne_NP1 Schieble_NP1 and_CC Abdulfattah_NP1 Jandala_NP1 ._. 
</s>
<s>
Joanne_NP1 ended_VVD up_RP giving_VVG Steve_NP1 up_RP for_IF adoption_NN1 because_CS her_APPGE father_NN1 did_VDD not_XX approve_VVI of_IO her_PPHO1 marrying_VVG a_AT1 Syrian_JJ native_JJ ._. 
</s>
<s>
As_II a_AT1 result_NN1 ,_, Steve_NP1 was_VBDZ adopted_VVN by_II Clara_NP1 and_CC Paul_NP1 Jobs_NN2 ,_, who_PNQS lived_VVD in_II Silicon_NN1 Valley_NN1 California_NP1 ._. 
</s>
<s>
From_II a_AT1 very_RG early_JJ age_NN1 ,_, Steve_NP1 was_VBDZ interested_JJ in_II working_VVG with_IW his_APPGE father_NN1 on_II electronics_NN1 in_II their_APPGE family_NN1 garage_NN1 ._. 
</s>
<s>
The_AT family_NN1 garage_NN1 was_VBDZ a_AT1 place_NN1 where_RRQ Steve_NP1 learned_VVD basic_JJ technical_JJ skills_NN2 ,_, such_II21 as_II22 how_RRQ to_TO take_VVI apart_RL and_CC reconstruct_VVI electronic_JJ devices_NN2 ._. 
</s>
<s>
In_II the_AT school_NN1 environment_NN1 ,_, Jobs_NN2 was_VBDZ clearly_RR frustrated_VVN over_II formal_JJ schooling_NN1 since_CS he_PPHS1 could_VM not_XX apply_VVI his_APPGE intelligence_NN1 and_CC innovativeness_NN1 to_II school_NN1 work_NN1 ._. 
</s>
<s>
Consequently_RR ,_, Jobs_NN2 did_VDD not_XX behave_VVI in_II the_AT approved_JJ manner_NN1 and_CC he_PPHS1 was_VBDZ considered_VVN as_II a_AT1 prankster_NN1 among_II the_AT teachers_NN2 ._. 
</s>
<s>
However_RR ,_, he_PPHS1 did_VDD so_RG well_RR on_II examinations_NN2 that_CST the_AT school_NN1 executives_NN2 suggested_VVD him_PPHO1 to_TO skip_VVI straight_RR ahead_RL to_II high_JJ school_NN1 ._. 
</s>
<s>
Nevertheless_RR ,_, Paul_NP1 and_CC Clara_NP1 declined_VVD this_DD1 proposal_NN1 ._. 
</s>
<s>
After_II finishing_VVG elementary_JJ school_NN1 on_II regular_JJ time_NNT1 ,_, Jobs_NN2 enrolled_VVN at_II Homestead_NN1 High_JJ school_NN1 in_II 1971_MC ._. 
</s>
<s>
During_II his_APPGE high_JJ school_NN1 years_NNT2 ,_, Jobs_NN2 met_VVD Steve_NP1 Wozniak_NP1 ,_, a_AT1 student_NN1 from_II University_NN1 of_IO Michigan_NP1 ,_, who_PNQS became_VVD Jobs_NN2 close_JJ friend_NN1 and_CC later_RRR a_AT1 co-founder_NN1 of_IO Apple_NN1 Computer_NN1 ._. 
</s>
<s>
After_CS high_JJ school_NN1 ,_, Jobs_NN2 enrolled_VVN at_II Reed_NP1 College_NN1 in_II Portland_NP1 ,_, Oregon_NP1 ._. 
</s>
<s>
He_PPHS1 quit_VVD the_AT college_NN1 soon_RR after_CS ,_, and_CC enrolled_VVN at_II creative_JJ classes_NN2 for_IF some_DD 18_MC months_NNT2 ._. 
</s>
<s>
Next_MD Jobs_NN2 got_VVD a_AT1 job_NN1 from_II a_AT1 video_NN1 game_NN1 producer_NN1 ,_, Atari_NP1 ._. 
</s>
<s>
Jobs_NN2 spent_VVD only_RR a_AT1 few_DA2 months_NNT2 working_VVG for_IF the_AT company_NN1 ,_, since_CS he_PPHS1 felt_VVD like_CS he_PPHS1 should_VM rather_RR seek_VVI for_IF spiritual_JJ enlightenment_NN1 than_CSN working_VVG from_II nine_MC to_II five_MC ._. 
</s>
<s>
Therefore_RR ,_, he_PPHS1 flew_VVD over_RP to_II India_NP1 with_IW his_APPGE friend_NN1 ,_, Daniel_NP1 Kottke_NP1 ,_, with_IW whom_PNQO he_PPHS1 had_VHD became_VVN friends_NN2 with_IW at_II Reed_NP1 College_NN1 ._. 
</s>
<s>
Steve_NP1 and_CC Daniel_NP1 spent_VVD the_AT next_MD two_MC years_NNT2 seeking_VVG inner_JJ rest_NN1 and_CC getting_VVG away_II21 from_II22 materialism_NN1 ._. 
</s>
<s>
The_AT experience_NN1 changed_VVD the_AT thinking_NN1 of_IO Jobs_NN2 ,_, as_CSA he_PPHS1 returned_VVD back_RP to_II the_AT United_NP1 States_NP1 as_II a_AT1 Buddhist_NN1 with_IW a_AT1 shaved_JJ head_NN1 ._. 
</s>
<s>
After_II moving_VVG back_RP to_II his_APPGE home_NN1 country_NN1 ,_, Jobs_NN2 partnered_VVD up_RP with_IW Steve_NP1 Wozniak_NP1 who_PNQS he_PPHS1 had_VHD became_VVN friends_NN2 with_IW during_II the_AT high_JJ school_NN1 years_NNT2 ._. 
</s>
<s>
In_II 1976_MC ,_, the_AT two_MC Steves_NP2 established_VVD a_AT1 computer_NN1 company_NN1 in_II Jobs_NN2 parents_NN2 garage_NN1 ,_, for_IF which_DDQ they_PPHS2 gave_VVD a_AT1 name_NN1 Apple_NN1 Computer_NN1 ._. 
</s>
<s>
Apple_NN1 Computers_NN2 business_NN1 idea_NN1 was_VBDZ to_TO make_VVI affordable_JJ personal_JJ computers_NN2 for_IF everyday_JJ consumers_NN2 ._. 
</s>
<s>
Wozniak_NP1 was_VBDZ in_II31 charge_II32 of_II33 technical_JJ of_IO whereas_CS Jobs_NN2 was_VBDZ responsible_JJ for_IF marketing_NN1 of_IO Apple_NN1 Computers_NN2 ._. 
</s>
<s>
Job_NN1 approach_NN1 to_II marketing_NN1 of_IO computers_NN2 was_VBDZ somewhat_RR revolutionary_JJ as_CSA he_PPHS1 marketed_VVD the_AT computer_NN1 as_II a_AT1 piece_NN1 of_IO a_AT1 counter_NN1 culture_NN1 lifestyle_NN1 :_: romantic_JJ ,_, youthful_JJ ,_, and_CC creative_JJ ._. 
</s>
<s>
In_II 1980_MC ,_, Apple_NN1 Computers_NN2 sales_NN had_VHD reached_VVN 140_MC million_NNO dollar_NNU1 and_CC during_II the_AT same_DA year_NNT1 Apple_NN1 went_VVD public_NN1 through_II an_AT1 initial_JJ public_JJ offering_NN1 in_II which_DDQ the_AT market_NN1 value_NN1 of_IO the_AT company_NN1 climbed_VVD to_II 1.2_MC billion_NNO USD_NN1 ._. 
</s>
<s>
Regardless_RR of_IO a_AT1 rosy_JJ start_NN1 ,_, Apples_NN2 history_NN1 includes_VVZ some_DD setbacks_NN2 ._. 
</s>
<s>
One_MC1 of_IO the_AT major_JJ difficulties_NN2 was_VBDZ the_AT success_NN1 of_IO Apple_NN1 Computers_NN2 rival_VV0 ,_, IBM_NP1 ,_, and_CC their_APPGE personal_JJ computer_NN1 (_( PC_NNU )_) ,_, which_DDQ suddenly_RR outperformed_VVD Apples_NN2 Machintosh_NP1 ._. 
</s>
<s>
Jobs_NN2 did_VDD not_XX want_VVI to_TO make_VVI Machintosh_NP1 compatible_JJ with_IW IBMs_NP2 PC_NN1 which_DDQ caused_VVD a_AT1 loss_NN1 of_IO sales_NN ._. 
</s>
<s>
Difficulties_NN2 with_IW the_AT computer_NN1 sales_NN and_CC due_II21 to_II22 his_APPGE strong_JJ personal_JJ views_NN2 how_RRQ Apple_NN1 should_VM move_VVI forward_RL ,_, Jobs_NN2 was_VBDZ fired_VVN in_II 1985_MC ._. 
</s>
<s>
Right_RR after_II losing_VVG his_APPGE CEO_NN1 post_NN1 at_II Apple_NN1 ,_, Jobs_NN2 launched_VVD a_AT1 new_JJ software_NN1 company_NN1 called_VVN NeXT_MD and_CC acquired_VVN an_AT1 animation_NN1 company_NN1 from_II George_NP1 Lucas_NP1 ._. 
</s>
<s>
The_AT animation_NN1 company_NN1 ,_, which_DDQ later_RRR was_VBDZ named_VVN as_CSA Pixar_NP1 Animation_NN1 Studios_NN2 ,_, became_VVD extremely_RR successful_JJ ._. 
</s>
<s>
However_RR ,_, NeXT_MD Incorporation_NN1 struggled_VVD to_TO sell_VVI operating_NN1 systems_NN2 to_II customers_NN2 in_II the_AT country_NN1 ._. 
</s>
<s>
The_AT relationship_NN1 between_II Apple_NN1 Computer_NN1 and_CC Steve_NP1 Jobs_NN2 continued_VVN in_II 1997_MC when_RRQ Apple_NN1 acquired_VVD the_AT NeXT_MD for_IF some_DD 430_MC million_NNO USD_NN1 ._. 
</s>
<s>
Shortly_RR after_CS ,_, Steve_NP1 Jobs_NN2 returned_VVN to_II his_APPGE post_NN1 as_CSA Apples_NN2 CEO_NN1 ._. 
</s>
<s>
Jobs_NN2 made_VVD some_DD radical_JJ changes_NN2 in_II the_AT organization_NN1 and_CC revitalized_VVD the_AT companys_NN2 product_NN1 offering_NN1 and_CC brand_NN1 ._. 
</s>
<s>
For_REX21 instance_REX22 ,_, Jobs_NN2 replaced_VVD the_AT management_NN1 team_NN1 ,_, changed_VVD the_AT employee_NN1 stock_NN1 option_NN1 plans_NN2 ,_, and_CC created_VVD the_AT iMac_JJ brand_NN1 ._. 
</s>
<s>
Furthermore_RR ,_, he_PPHS1 did_VDD not_XX want_VVI to_TO receive_VVI more_DAR than_CSN a_AT1 dollar_NNU1 as_II an_AT1 annual_JJ salary_NN1 for_IF his_APPGE work_NN1 to_TO demonstrate_VVI his_APPGE personal_JJ dedication_NN1 for_IF the_AT company_NN1 ._. 
</s>
<s>
Jobs_NN2 underlined_VVD the_AT importance_NN1 of_IO creating_VVG pioneering_JJ product_NN1 lines_NN2 and_CC branding_VVG them_PPHO2 superiorly_RR ._. 
</s>
<s>
Apple_NN1 was_VBDZ again_RT back_RP on_II the_AT track_NN1 with_IW Jobs_NN2 initial_JJ vision_NN1 of_IO creating_VVG counter_JJ cultural_JJ life_NN1 style_NN1 products_NN2 ._. 
</s>
<s>
Between_II 2000_MC and_CC 2010_MC ,_, Apple_NN1 introduced_VVD many_DA2 ground-breaking_JJ products_NN2 such_II21 as_II22 the_AT Macbook_NP1 Air_NN1 ,_, iPod_VV0 ,_, iPhone_VV0 ,_, and_CC iPad_NN1 which_DDQ all_DB have_VH0 had_VHN a_AT1 huge_JJ impact_NN1 on_II the_AT evolution_NN1 of_IO modern_JJ technology_NN1 ._. 
</s>
<s>
Regardless_RR of_IO the_AT cancer_NN1 tumor_NN1 discovered_VVD in_II 2003_MC ,_, Jobs_NN2 continued_VVD to_TO work_VVI for_IF Apple_NN1 until_CS the_AT very_RG last_MD day_NNT1 of_IO his_APPGE life_NN1 ._. 
</s>
<s>
During_II his_APPGE leadership_NN1 Apple_NN1 had_VHD sold_VVN over_RG 320_MC million_NNO iPods_NN2 ,_, 135_MC million_NNO iPhones_NN2 ,_, 35_MC million_NNO iPads_NN2 ,_, and_CC the_AT value_NN1 of_IO Apples_NN2 stock_NN1 had_VHD risen_VVN from_II 10_MC to_II some_DD 400_MC USD_NP1 ._. 
</s>
<s>
In_II summary_NN1 ,_, it_PPH1 is_VBZ fair_JJ to_TO say_VVI that_CST Jobs_NN2 life_NN1 was_VBDZ everything_PN1 but_II predictable_JJ as_CSA he_PPHS1 rather_RR followed_VVD his_APPGE own_DA instinct_NN1 than_CSN pleased_JJ others_NN2 ._. 
</s>
<s>
This_DD1 characteristic_NN1 can_VM also_RR be_VBI easily_RR noticed_VVN in_II his_APPGE way_NN1 of_IO leading_JJ Apple_NN1 ._. 
</s>
<s>
Jobs_NN2 was_VBDZ a_AT1 visionary_JJ and_CC creative_JJ genius_NN1 ,_, who_PNQS left_VVD behind_II a_AT1 company_NN1 that_CST only_RR he_PPHS1 could_VM have_VHI built_VVN ._. 
</s>
<s>
Steve_NP1 Jobs_NN2 as_II a_AT1 leader_NN1 Steve_NP1 Jobs_NN2 leadership_NN1 practices_NN2 have_VH0 been_VBN under_RG close_JJ scrutiny_NN1 due_II21 to_II22 Apples_NN2 ability_NN1 to_TO attract_VVI the_AT best_JJT employees_NN2 in_II the_AT industry_NN1 ,_, to_TO continuously_RR develop_VVI first-class_JJ products_NN2 ,_, and_CC to_TO create_VVI a_AT1 customer_NN1 base_NN1 ,_, which_DDQ is_VBZ almost_RR religiously_RR loyal_JJ to_II the_AT company_NN1 brand_NN1 ._. 
</s>
<s>
Many_DA2 people_NN say_VV0 that_CST Apples_NN2 success_NN1 has_VHZ been_VBN a_AT1 result_NN1 of_IO Steve_NP1 Jobs_NN2 ability_NN1 to_TO steer_VVI the_AT company_NN1 strictly_RR towards_II his_APPGE own_DA vision_NN1 ._. 
</s>
<s>
Jobs_NN2 knew_VVD what_DDQ he_PPHS1 wanted_VVD and_CC he_PPHS1 also_RR knew_VVD what_DDQ was_VBDZ needed_VVN to_TO get_VVI there_RL ._. 
</s>
<s>
Under_II Jobs_NN2 leadership_NN1 ,_, Apple_NN1 turned_VVD Jobs_NN2 innovative_JJ ideas_NN2 into_II spectacular_JJ products_NN2 at_II a_AT1 pace_NN1 that_CST the_AT industry_NN1 rivals_NN2 could_VM only_RR hope_VVI for_IF ._. 
</s>
<s>
Apples_NN2 success_NN1 ,_, however_RR ,_, did_VDD not_XX come_VVI without_IW a_AT1 price_NN1 ._. 
</s>
<s>
Jobs_NN2 was_VBDZ perceived_VVN as_II a_AT1 terrible_JJ manager_NN1 of_IO people_NN ._. 
</s>
<s>
Many_DA2 employees_NN2 at_II Apple_NN1 ,_, NeXT_MD ,_, and_CC Pixar_VV0 studios_NN2 have_VH0 described_VVN Steve_NP1 as_II a_AT1 control_NN1 freak_NN1 who_PNQS was_VBDZ unwilling_JJ to_TO give_VVI credit_NN1 where_CS it_PPH1 was_VBDZ due_JJ ._. 
</s>
<s>
Some_DD have_VH0 even_RR stated_VVN that_CST he_PPHS1 was_VBDZ tyrannical_JJ and_CC lacking_VVG empathy_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ somewhat_RR surprising_JJ that_CST a_AT1 man_NN1 who_PNQS was_VBDZ described_VVN as_II such_DA a_AT1 cold_JJ personality_NN1 could_VM lead_VVI Apple_NN1 to_II such_DA success_NN1 ._. 
</s>
<s>
Yet_RR ,_, Jobs_NN2 had_VHD something_PN1 that_CST many_DA2 other_JJ managers_NN2 did_VDD not_XX have_VHI ._. 
</s>
<s>
He_PPHS1 was_VBDZ confident_JJ enough_RR to_TO take_VVI risky_JJ leaps_NN2 ,_, and_CC charismatic_JJ enough_RR to_TO draw_VVI the_AT most_RGT talented_JJ employees_NN2 in_II the_AT pursuit_NN1 of_IO his_APPGE vision_NN1 ._. 
</s>
<s>
He_PPHS1 was_VBDZ a_AT1 perfectionist_NN1 and_CC he_PPHS1 attracted_VVD like-minded_JJ people_NN who_PNQS were_VBDR never_RR fully_RR satisfied_VVN with_IW their_APPGE work_NN1 ._. 
</s>
<s>
Morover_VV0 ,_, despite_II of_IO his_APPGE arrogance_NN1 ,_, he_PPHS1 was_VBDZ highly_RR respected_VVN by_II Apples_NN2 employees_NN2 ,_, peers_NN2 and_CC the_AT business_NN1 community_NN1 in_RR21 general_RR22 (_( Godell_NP1 ,_, 1996_MC )_) ._. 
</s>
<s>
Jobs_NN2 was_VBDZ able_JK to_TO create_VVI a_AT1 working_JJ atmosphere_NN1 where_CS the_AT employees_NN2 became_VVD motivated_JJ simply_RR by_II the_AT pride_NN1 they_PPHS2 got_VVD from_II meeting_VVG the_AT challenges_NN2 set_VVN by_II their_APPGE CEO_NN1 ._. 
</s>
<s>
In_II a_AT1 nutshell_NN1 ,_, many_DA2 qualities_NN2 Jobs_NN2 possessed_VVN would_VM not_XX be_VBI characterized_VVN as_II the_AT ones_NN2 of_IO a_AT1 good_JJ manager_NN1 of_IO people_NN ._. 
</s>
<s>
Yet_RR ,_, his_APPGE charisma_NN1 ,_, self-confidence_NN1 ,_, passion_NN1 ,_, and_CC vision_NN1 for_IF work_NN1 overshadowed_VVD all_DB his_APPGE negative_JJ characteristics_NN2 ._. 
</s>
<s>
EI_NP1 vs_II ._. 
</s>
<s>
Steve_NP1 Jobs_NN2 leadership_NN1 methods_NN2 analysis_NN1 Findings_NN2 /_FO Summary_NN1 Sources_NN2 
</s>
