<s>
Degrowth_NP1 :_: Can_VM It_PPH1 Be_VBI Sold_VVN To_II The_AT Big_JJ Crowds_NN2 ?_? 1_MC1 Introduction_NN1 Recent_JJ years_NNT2 have_VH0 uncovered_VVN a_AT1 deepening_JJ interest_NN1 for_IF economic_JJ and_CC social_JJ downshifting_NN1 ,_, as_II31 well_II32 as_II33 degrowth_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ becoming_VVG more_RGR popular_JJ to_TO jump_VVI of_IO the_AT treadmill_NN1 of_IO achievement_NN1 and_CC focus_VV0 to_II a_AT1 bigger_JJR extent_NN1 on_II well-being_NN1 and_CC contentment_NN1 ._. 
</s>
<s>
While_CS downshifters_NN2 are_VBR in_II31 favor_II32 of_II33 finding_VVG a_AT1 less_RGR stressful_JJ work-life_JJ balance_NN1 and_CC emphasize_VV0 personal_JJ relations_NN2 ,_, degrowth-_JJ advocators_NN2 strongly_RR object_VV0 the_AT never-_JJ ending_NN1 mania_NN1 for_IF economic_JJ growth_NN1 ._. 
</s>
<s>
They_PPHS2 acknowledge_VV0 that_CST resources_NN2 are_VBR limited_VVN and_CC want_VV0 to_TO decrease_VVI consumption_NN1 and_CC production_NN1 therefore_RR they_PPHS2 want_VV0 to_TO construct_VVI an_AT1 alternative_JJ economic_JJ system_NN1 for_IF modern_JJ societies_NN2 that_CST does_VDZ not_XX rely_VVI on_II growth_NN1 in_II itself_PPX1 ._. 
</s>
<s>
(_( Schneider_VV0 ,_, Kallis_NP1 ,_, &;_NULL Martinez-Alier_NP1 ,_, 2010_MC )_) Researchers_NN2 who_PNQS are_VBR in_II31 favor_II32 of_II33 degrowth_NN1 ,_, like_II Kallis_NP1 (_( 2011_MC )_) ,_, find_VV0 the_AT transition_NN1 to_II a_AT1 degrowth_NN1 based_VVN economic_JJ system_NN1 feasible_JJ ._. 
</s>
<s>
However_RR ,_, the_AT problem_NN1 appears_VVZ to_TO be_VBI that_CST the_AT term_NN1 degrowth_NN1 is_VBZ lacking_VVG a_AT1 realistic_JJ definition_NN1 and_CC convincing_JJ economic_JJ theory_NN1 that_CST would_VM capture_VVI the_AT attention_NN1 of_IO a_AT1 larger_JJR crowd_NN1 ._. 
</s>
<s>
Today_RT ,_, it_PPH1 seems_VVZ that_CST the_AT concept_NN1 of_IO degrowth_NN1 is_VBZ rather_RG confusing_JJ and_CC might_VM not_XX be_VBI approached_VVN seriously_RR nor_CC deemed_VVN credible_JJ by_II policy-makers_NN2 ,_, thereby_RR not_XX being_VBG able_JK to_TO attract_VVI many_DA2 additional_JJ supporters_NN2 than_CSN those_DD2 who_PNQS 've_VH0 already_RR adopted_VVN it_PPH1 (_( Bergh_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
Given_VVN this_DD1 background_NN1 ,_, my_APPGE paper_NN1 wants_VVZ to_TO examine_VVI more_RGR thoroughly_RR the_AT scientific_JJ reliability_NN1 of_IO degrowth_NN1 ._. 
</s>
<s>
A_AT1 valid_JJ theory_NN1 that_CST raises_VVZ more_DAR thoughts_NN2 than_CSN questions_NN2 appears_VVZ to_TO be_VBI missing_VVG within_II degrowth_NN1 studies_NN2 ._. 
</s>
<s>
The_AT question_NN1 is_VBZ thus_RR ,_, whether_CSW degrowth_NN1 will_VM gain_VVI new_JJ terrain_NN1 with_IW the_AT existing_JJ loose_JJ definition_NN1 ._. 
</s>
<s>
After_II reading_VVG studies_NN2 on_II degrowth_NN1 it_PPH1 remains_VVZ unclear_JJ when_CS additional_JJ economic_JJ growth_NN1 stops_VVZ adding_VVG well-being_NN1 ?_? 
</s>
<s>
How_RRQ can_VM the_AT public_NN1 be_VBI convinced_VVN that_CST it_PPH1 should_VM give_VVI up_RP the_AT quest_NN1 for_IF financial_JJ gains_NN2 and_CC economic_JJ success_NN1 ?_? 
</s>
<s>
In_II this_DD1 paper_NN1 I_PPIS1 intend_VV0 to_TO discuss_VVI questions_NN2 that_CST impact_VV0 the_AT credibility_NN1 of_IO degrowth_NN1 and_CC study_VV0 the_AT existing_JJ literature_NN1 on_II degrowth_NN1 from_II a_AT1 critical_JJ perspective_NN1 ._. 
</s>
<s>
With_IW this_DD1 study_NN1 ,_, I_PPIS1 hope_VV0 to_TO suggest_VVI some_DD measures_NN2 that_CST could_VM improve_VVI the_AT future_JJ prospects_NN2 of_IO degrowth._NNU 1.1_MC Outline_VV0 The_AT outline_NN1 of_IO the_AT paper_NN1 will_VM be_VBI structured_VVN as_CSA follows_VVZ ._. 
</s>
<s>
Chapter_NN1 2_MC presents_VVZ some_DD background_NN1 to_II the_AT field_NN1 of_IO study_NN1 of_IO my_APPGE paper_NN1 ,_, while_CS chapter_NN1 3_MC focuses_VVZ on_II earlier_JJR research_NN1 conducted_VVN in_II the_AT field_NN1 of_IO degrowth_NN1 ._. 
</s>
<s>
In_II chapter_NN1 4_MC I_PPIS1 assess_VV0 and_CC discuss_VV0 the_AT loopholes_NN2 within_II current_JJ research_NN1 of_IO the_AT degrowth_NN1 movement_NN1 and_CC some_DD suggestions_NN2 for_IF how_RRQ to_TO improve_VVI the_AT relevance_NN1 and_CC credibility_NN1 of_IO existing_JJ literature_NN1 ._. 
</s>
<s>
Chapter_NN1 4_MC is_VBZ followed_VVN by_II a_AT1 conclusion_NN1 in_II chapter_NN1 5_MC where_RRQ I_PPIS1 summarize_VV0 my_APPGE main_JJ findings._NNU 2_MC Background_NN1 "_" Consumption_NN1 today_RT consists_VVZ of_IO people_NN spending_NN1 money_NN1 they_PPHS2 do_VD0 n't_XX own_VVI ,_, to_TO buy_VVI things_NN2 they_PPHS2 do_VD0 n't_XX need_VVI ,_, to_TO impress_VVI people_NN they_PPHS2 do_VD0 n't_XX like_VVI ._. "_" 
</s>
<s>
(_( Hamilton_NP1 ,_, Money_NN1 ,_, Careers_NN2 and_CC Contentment_NP1 ,_, 2003_MC )_) The_AT degrowth_NN1 movement_NN1 has_VHZ evolved_VVN over_II time_NNT1 ,_, from_II dealing_VVG with_IW the_AT consequences_NN2 of_IO industrial_JJ production_NN1 to_II objecting_VVG the_AT past_JJ years_NNT2 '_GE obsession_NN1 with_IW financial_JJ profits_NN2 ._. 
</s>
<s>
Degrowth_NN1 emphasizes_VVZ sustainability_NN1 by_II voluntary_JJ downsizing_JJ economic_JJ activities_NN2 production_NN1 and_CC consumption_NN1 -_- and_CC the_AT recognition_NN1 of_IO limited_JJ resources_NN2 ._. 
</s>
<s>
Furthermore_RR ,_, the_AT core_NN1 beliefs_NN2 include_VV0 the_AT possibility_NN1 to_TO reach_VVI a_AT1 state_NN1 of_IO welfare_NN1 without_IW depending_II21 on_II22 economic_JJ growth_NN1 ._. 
</s>
<s>
(_( Schneider_VV0 ,_, Kallis_NP1 ,_, &;_NULL Martinez-Alier_NP1 ,_, 2010_MC )_) The_AT degrowth-proponents_NN2 accept_VV0 the_AT notion_NN1 that_CST economic_JJ growth_NN1 ca_VM n't_XX change_VVI the_AT fact_NN1 that_CST resources_NN2 are_VBR finite_JJ nor_CC that_DD1 humanity_NN1 and_CC our_APPGE globe_NN1 will_VM eventually_RR vanish_VVI (_( Kallis_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
Instead_II21 of_II22 surrounding_VVG around_RP economic_JJ growth_NN1 ,_, materialism_NN1 and_CC capitalism_NN1 ,_, degrowth_NN1 acknowledges_VVZ human_JJ well-being_NN1 as_II31 well_II32 as_II33 social_JJ equality_NN1 ._. 
</s>
<s>
(_( Schneider_VV0 ,_, Kallis_NP1 ,_, &;_NULL Martinez-Alier_NP1 ,_, 2010_MC )_) 3_MC Previous_JJ Research_NN1 Pioneers_NN2 like_II Daly_NP1 and_CC Georgescu-Roegen_NP1 ,_, as_II31 well_II32 as_II33 Meadows_NN2 et_RA21 al_RA22 ._. 
</s>
<s>
have_VH0 engaged_VVN in_II developing_JJ studies_NN2 that_CST focus_VV0 on_II the_AT sustainability_NN1 and_CC interaction_NN1 of_IO social_JJ ,_, environmental_JJ and_CC economic_JJ aspects_NN2 ._. 
</s>
<s>
(_( Daly_NP1 ,_, 1996_MC )_) ;_; (_( Georgescu-Roegen_NP1 ,_, 1971_MC )_) ;_; (_( Meadows_NN2 ,_, Meadows_NN2 ,_, Randers_NP1 ,_, &;_NULL Behrens_NP1 III_MC ,_, 1972_MC )_) ._. 
</s>
<s>
The_AT thorough_JJ research_NN1 conducted_VVN by_II these_DD2 innovators_NN2 can_VM be_VBI traced_VVN back_RP to_II views_NN2 presented_VVN by_II Thomas_NP1 Malthus_NP1 in_II the_AT 18th_MD century_NNT1 ,_, who_PNQS acknowledged_VVD the_AT limited_JJ resources_NN2 and_CC earth_NN1 's_GE carrying_NN1 capacity_NN1 ._. 
</s>
<s>
(_( Petersen_NN1 ,_, 1999_MC )_) Aligned_VVD with_IW the_AT philosophy_NN1 of_IO degrowth_NN1 ,_, these_DD2 consumption-critical_JJ thoughts_NN2 have_VH0 inspired_VVN several_DA2 enthusiasts_NN2 to_TO study_VVI the_AT potential_NN1 within_II downscaling_VVG ._. 
</s>
<s>
Nevertheless_RR ,_, the_AT supply_NN1 of_IO relevant_JJ and_CC contributing_VVG literature_NN1 on_II degrowth_NN1 is_VBZ not_XX vast_JJ ._. 
</s>
<s>
(_( Bergh_VV0 ,_, 2011_MC )_) Bergh_NN1 has_VHZ taken_VVN into_II consideration_NN1 the_AT criticism_NN1 directed_VVN towards_II the_AT degrowth-_JJ thought_NN1 ,_, and_CC finds_VVZ the_AT concept_NN1 vague_JJ and_CC ineffective_JJ ,_, which_DDQ is_VBZ why_RRQ he_PPHS1 finds_VVZ zero_NN1 growth_NN1 or_CC indifference_NN1 of_IO growth_NN1 more_RGR realistic_JJ in_II today_RT 's_GE society_NN1 than_CSN negative_JJ growth_NN1 (_( Bergh_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
He_PPHS1 distinguishes_VVZ between_II five_MC types_NN2 of_IO degrowth_NN1 ;_; GDP_NN1 ,_, consumption_NN1 ,_, radical_NN1 ,_, work-time_JJ and_CC physical_JJ and_CC discusses_VVZ the_AT problems_NN2 associated_VVN with_IW each_DD1 of_IO these_DD2 degrowth_NN1 methods_NN2 ._. 
</s>
<s>
He_PPHS1 finds_VVZ firstly_RR ,_, that_DD1 GDP_NN1 degrowth_NN1 ca_VM n't_XX be_VBI ,_, on_II a_AT1 general_JJ level_NN1 ,_, targeted_VVD to_TO address_VVI specifically_RR dirty_JJ industries_NN2 ,_, and_CC secondly_RR ,_, that_DD1 consumption_NN1 degrowth_NN1 would_VM require_VVI consumption_NN1 limits_VVZ on_II an_AT1 individual_JJ that_CST would_VM be_VBI hard_JJ to_TO specify_VVI ._. 
</s>
<s>
Thirdly_RR ,_, Bergh_NP1 sees_VVZ a_AT1 reduction_NN1 of_IO work-time_JJ as_II an_AT1 ineffective_JJ means_NN to_TO achieve_VVI degrowth_NN1 ._. 
</s>
<s>
Fourthly_RR ,_, he_PPHS1 finds_VVZ that_CST a_AT1 radical_JJ degrowth_NN1 approach_NN1 would_VM not_XX take_VVI into_II consideration_NN1 the_AT characteristics_NN2 of_IO the_AT human_JJ being_NN1 ._. 
</s>
<s>
Lastly_RR ,_, Bergh_NP1 does_VDZ not_XX support_VVI the_AT simplicity_NN1 of_IO physical_JJ degrowth_NN1 (_( referring_VVG to_II a_AT1 decrease_NN1 in_II the_AT actual_JJ size_NN1 of_IO the_AT economy_NN1 )_) ,_, since_II finding_VVG a_AT1 good_JJ indicator_NN1 for_IF this_DD1 would_VM imply_VVI problems_NN2 ._. 
</s>
<s>
Bergh_NP1 's_GE overall_JJ conclusion_NN1 is_VBZ that_DD1 degrowth_NN1 as_II a_AT1 concept_NN1 lacks_VVZ in_II credibility_NN1 and_CC will_VM not_XX gain_VVI support_NN1 among_II policy-makers_NN2 nor_CC among_II the_AT public_NN1 ._. 
</s>
<s>
Rather_RR ,_, he_PPHS1 promotes_VVZ the_AT indifference_NN1 of_IO growth_NN1 ._. 
</s>
<s>
(_( Bergh_VV0 ,_, 2011_MC )_) A_ZZ1 study_NN1 with_IW a_AT1 more_RGR positive_JJ outlook_NN1 on_II degrowth_NN1 ,_, opposing_VVG most_DAT of_IO the_AT views_NN2 and_CC statements_NN2 provided_VVN by_II Bergh_NP1 (_( Bergh_NP1 ,_, 2011_MC )_) ,_, is_VBZ presented_VVN by_II Kallis_NP1 ._. 
</s>
<s>
(_( Kallis_NP1 ,_, 2011_MC )_) Bergh_VV0 and_CC Kallis_NP1 agree_VV0 on_II some_DD cures_NN2 for_IF reaching_VVG a_AT1 less_RGR growth-obsessed_JJ society_NN1 ,_, like_II e.g._REX climate_NN1 change_NN1 pacts_NN2 and_CC decreases_VVZ in_II amount_NN1 of_IO time_NNT1 spent_VVN on_II work_NN1 rather_II21 than_II22 leisure_NN1 ,_, yet_RR they_PPHS2 do_VD0 not_XX appear_VVI to_TO share_VVI many_DA2 other_JJ opinions_NN2 ._. 
</s>
<s>
Kallis_NP1 supports_VVZ a_AT1 more_RGR radical_JJ ,_, voluntary_JJ transition_NN1 to_II a_AT1 degrowth-economy_NN1 based_VVN on_II smaller_JJR production_NN1 and_CC fewer_DAR resources_NN2 ,_, rather_II21 than_II22 ending_VVG up_RP in_II the_AT same_DA situation_NN1 anyway_RR without_IW any_DD sustainable_JJ preparation_NN1 ._. 
</s>
<s>
However_RR ,_, Kallis_NP1 does_VDZ n't_XX present_VVI any_DD macroeconomic_JJ theories_NN2 that_CST could_VM enable_VVI this_DD1 transition_NN1 ,_, but_CCB calls_VVZ for_IF more_DAR research_NN1 on_II this_DD1 matter_NN1 ._. 
</s>
<s>
In_II fact_NN1 ,_, he_PPHS1 admits_VVZ that_CST many_DA2 challenges_NN2 lie_VV0 ahead_RL regarding_II degrowth_NN1 -studies_NN2 ,_, particularly_RR the_AT link_NN1 between_II environment_NN1 and_CC economy_NN1 needs_VVZ to_TO be_VBI studied_VVN more_RGR intensively_RR ._. 
</s>
<s>
(_( Kallis_NP1 ,_, 2011_MC )_) Schneider_NP1 et_RA21 al_RA22 on_II the_AT other_JJ hand_NN1 discuss_VV0 the_AT possibilities_NN2 versus_II obstacles_NN2 associated_VVN with_IW degrowth_NN1 ._. 
</s>
<s>
While_CS recognizing_VVG similar_JJ benefits_NN2 in_II downscaling_VVG as_CSA their_APPGE fellow_JJ colleagues_NN2 ,_, they_PPHS2 also_RR accept_VV0 that_CST the_AT degrowth_NN1 philosophy_NN1 is_VBZ somewhat_DD1 of_IO an_AT1 utopia_NN1 and_CC would_VM require_VVI many_DA2 reforms_NN2 at_II practically_RR every_AT1 level_NN1 of_IO the_AT society_NN1 ,_, including_II every_AT1 financial_JJ and_CC social_JJ institution_NN1 ._. 
</s>
<s>
The_AT aim_NN1 for_IF a_AT1 steady-state_JJ economy_NN1 would_VM be_VBI reached_VVN only_RR after_CS these_DD2 reforms_NN2 have_VH0 been_VBN accomplished_VVN ._. 
</s>
<s>
Schneider_VV0 et_RA21 al_RA22 ._. 
</s>
<s>
call_VV0 for_IF an_AT1 acknowledgment_NN1 of_IO which_DDQ future_JJ scenarios_NN2 are_VBR feasible_JJ and_CC which_DDQ ones_NN2 are_VBR simply_RR unrealistic_JJ ,_, considering_CS the_AT modest_JJ progress_NN1 made_VVN up_II21 to_II22 this_DD1 date_NN1 ._. 
</s>
<s>
(_( Schneider_VV0 ,_, Kallis_NP1 ,_, &;_NULL Martinez-Alier_NP1 ,_, 2010_MC )_) Kerschner_NP1 (_( 2010_MC )_) goes_VVZ deeper_RRR into_II the_AT subject_NN1 of_IO steady-state_JJ studies_NN2 ._. 
</s>
<s>
He_PPHS1 explores_VVZ whether_CSW using_VVG steady-state_JJ economy_NN1 (_( SSE_ND1 )_) tools_NN2 to_TO assess_VVI degrowth_NN1 could_VM be_VBI useful_JJ for_IF approximation_NN1 of_IO the_AT global_JJ effects_NN2 of_IO degrowth_NN1 ._. 
</s>
<s>
He_PPHS1 finds_VVZ that_CST there_EX is_VBZ a_AT1 significant_JJ lack_NN1 of_IO concrete_JJ policies_NN2 in_II degrowth_NN1 -_- literature_NN1 ,_, particularly_RR from_II a_AT1 demographic_JJ point_NN1 of_IO view_NN1 ,_, and_CC this_DD1 lack_NN1 could_VM be_VBI complemented_VVN by_II SSE_ND1 related_JJ theories_NN2 ._. 
</s>
<s>
Kerschner_NP1 claims_VVZ that_DD1 SSE_ND1 and_CC degrowth_NN1 complement_VV0 each_PPX221 other_PPX222 :_: by_II following_VVG the_AT degrowth_NN1 philosophy_NN1 in_II the_AT North_ND1 ,_, the_AT South_ND1 would_VM have_VHI some_DD space_NN1 to_TO grow_VVI ,_, and_CC the_AT global_JJ economy_NN1 could_VM achieve_VVI a_AT1 steady_JJ state_NN1 ._. 
</s>
<s>
(_( Kerschner_NP1 ,_, 2010_MC )_) This_DD1 is_VBZ not_XX ,_, however_RR ,_, the_AT opinion_NN1 of_IO Latouche_NP1 ,_, who_PNQS finds_VVZ that_CST developing_JJ countries_NN2 should_VM not_XX engage_VVI in_II growth_NN1 economics_NN1 and_CC instead_RR adopt_VV0 degrowth_NN1 strategies_NN2 as_RR21 well_RR22 ,_, in_BCL21 order_BCL22 to_TO decrease_VVI their_APPGE dependence_NN1 on_II the_AT North_ND1 ._. 
</s>
<s>
Global_JJ growth_NN1 dependency_NN1 leads_VVZ to_II further_JJR dependencies_NN2 that_CST would_VM be_VBI non-existent_JJ without_IW the_AT growth_NN1 mania_NN1 in_II the_AT first_MD place_NN1 ._. 
</s>
<s>
(_( Latouche_NN1 ,_, 2004_MC )_) Also_RR Hamilton_NP1 brings_VVZ up_RP ,_, firstly_RR ,_, the_AT domination_NN1 of_IO economic_JJ growth_NN1 as_II the_AT cause_NN1 for_IF many_DA2 of_IO our_APPGE society_NN1 's_GE problems_NN2 ,_, and_CC secondly_RR ,_, the_AT inability_NN1 to_TO accept_VVI that_CST there_EX might_VM exist_VVI other_JJ means_NN to_TO reach_VVI well-being_NN1 ._. 
</s>
<s>
(_( Hamilton_NP1 ,_, 2003_MC )_) He_PPHS1 proposes_VVZ alternative_JJ policies_NN2 and_CC power_NN1 structures_NN2 to_TO adopt_VVI in_II a_AT1 post-economic_JJ growth_NN1 society_NN1 ._. 
</s>
<s>
Griethuysen_NN1 further_RRR discusses_VVZ the_AT underlying_JJ reasons_NN2 for_IF our_APPGE society_NN1 's_GE obsession_NN1 with_IW growth_NN1 ._. 
</s>
<s>
He_PPHS1 finds_VVZ that_CST there_EX prevails_VVZ a_AT1 lock-in_NN1 effect_NN1 ,_, created_VVN by_II the_AT capitalism_NN1 mentality_NN1 of_IO western_JJ countries_NN2 ._. 
</s>
<s>
His_APPGE conclusion_NN1 is_VBZ that_CST the_AT road_NN1 to_II a_AT1 common_JJ alternative_JJ economic_JJ thinking_NN1 is_VBZ long_JJ ._. 
</s>
<s>
(_( Griethuysen_NN1 ,_, 2009_MC )_) Certainly_RR ,_, Griethuysen_NP1 is_VBZ not_XX the_AT only_JJ one_PN1 stating_VVG this_DD1 opinion_NN1 ,_, nevertheless_RR ,_, not_XX being_VBG able_JK to_TO serve_VVI a_AT1 concrete_NN1 replacing_VVG or_CC complementing_VVG economic_JJ theory_NN1 to_II the_AT prevailing_JJ growth_NN1 theories_NN2 ._. 
</s>
<s>
Latouche_NN1 ,_, like_II many_DA2 other_JJ researchers_NN2 in_II31 favor_II32 of_II33 degrowth_NN1 ,_, admits_VVZ that_CST there_EX is_VBZ a_AT1 lack_NN1 of_IO calculation_NN1 theories_NN2 on_II degrowth_NN1 ._. 
</s>
<s>
(_( Latouche_NN1 ,_, 2004_MC )_) 4_MC Analysis_NN1 &;_NULL discussion_NN1 of_IO the_AT problems_NN2 associated_VVN with_IW degrowth_NN1 Below_RL I_PPIS1 discuss_VV0 some_DD of_IO the_AT economic_JJ problems_NN2 associated_VVN with_IW the_AT currently_RR existing_JJ research_NN1 conducted_VVN on_II degrowth_NN1 ._. 
</s>
<s>
The_AT literature_NN1 reveals_VVZ several_DA2 gaps_NN2 that_CST should_VM be_VBI completed_VVN in_BCL21 order_BCL22 to_TO give_VVI degrowth_NN1 a_AT1 more_RGR precise_JJ meaning_NN1 and_CC a_AT1 possibility_NN1 to_TO reach_VVI out_RP to_II a_AT1 larger_JJR support_NN1 group._NNU 4.1_MC Moral_JJ hazard_NN1 and_CC moral_JJ deficit_NN1 One_MC1 of_IO the_AT economic_JJ problems_NN2 that_CST arise_VV0 from_II a_AT1 transition_NN1 to_II degrowth_NN1 is_VBZ the_AT problem_NN1 of_IO information_NN1 asymmetry_NN1 ._. 
</s>
<s>
This_DD1 particular_JJ aspect_NN1 should_VM receive_VVI more_DAR attention_NN1 than_CSN the_AT current_JJ material_NN1 provides_VVZ ._. 
</s>
<s>
Mostly_RR present_JJ is_VBZ the_AT principal-agent_JJ problem_NN1 ,_, where_CS the_AT principal_NN1 wishes_VVZ that_CST the_AT agent_NN1 acts_VVZ in_II a_AT1 specified_JJ way_NN1 on_II the_AT behalf_NN1 of_IO the_AT principal_NN1 ,_, but_CCB the_AT principal_NN1 ca_VM n't_XX be_VBI sure_JJ that_CST this_DD1 occurs_VVZ ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, there_EX is_VBZ a_AT1 problem_NN1 of_IO moral_JJ hazard_NN1 ,_, that_REX21 is_REX22 ,_, a_AT1 form_NN1 of_IO postcontractual_JJ opportunism_NN1 ,_, where_CS one_MC1 part_NN1 might_VM act_VVI according_II21 to_II22 his/her_APPGE own_DA interest_NN1 at_II the_AT expense_NN1 of_IO the_AT counterpart_NN1 ._. 
</s>
<s>
(_( Milgrom_NP1 &;_NULL Roberts_NP1 ,_, 1992_MC )_) If_CS the_AT concept_NN1 of_IO degrowth_NN1 would_VM be_VBI applied_VVN on_II a_AT1 global_JJ scale_NN1 ,_, appropriate_JJ conduct_NN1 of_IO people_NN and_CC a_AT1 common_JJ moral_NN1 would_VM be_VBI needed_VVN ._. 
</s>
<s>
This_DD1 is_VBZ also_RR recognized_VVN by_II Kerschner_NP1 ,_, who_PNQS states_VVZ that_CST the_AT pursuit_NN1 of_IO degrowth_NN1 is_VBZ an_AT1 overly_RR optimistic_JJ idea_NN1 without_IW "_" moral_JJ growth_NN1 "_" of_IO people_NN as_II a_AT1 whole_NN1 ._. 
</s>
<s>
Applied_VVN to_II the_AT principal-agent_JJ relationship_NN1 ,_, the_AT problem_NN1 would_VM be_VBI as_CSA follows_VVZ ._. 
</s>
<s>
The_AT society_NN1 would_VM be_VBI the_AT principal_NN1 and_CC require_VV0 that_CST the_AT agents_NN2 ,_, i.e._REX the_AT people_NN ,_, would_VM live_VVI according_II21 to_II22 guidelines_NN2 that_CST could_VM enable_VVI a_AT1 state_NN1 of_IO degrowth_NN1 ._. 
</s>
<s>
But_CCB individuals_NN2 would_VM most_RGT likely_RR have_VHI incentives_NN2 to_TO deviate_VVI from_II these_DD2 rules_NN2 ,_, in_BCL21 order_BCL22 to_TO achieve_VVI an_AT1 increased_JJ personal_JJ gain_NN1 ._. 
</s>
<s>
Degrowth_NN1 -policies_NN2 would_VM require_VVI that_CST people_NN give_VV0 up_RP the_AT pursuit_NN1 of_IO maximal_JJ wealth_NN1 ,_, which_DDQ can_VM surely_RR be_VBI considered_VVN as_II a_AT1 very_RG optimistic_JJ prerequisite_NN1 ._. 
</s>
<s>
Therefore_RR ,_, the_AT extent_NN1 to_II which_DDQ individuals_NN2 would_VM attempt_VVI to_TO achieve_VVI the_AT goals_NN2 of_IO degrowth_NN1 ,_, could_VM easily_RR fall_VVI under_II the_AT desired_JJ level_NN1 of_IO engagement_NN1 ._. 
</s>
<s>
Other_JJ moral_JJ hazards_NN2 related_VVN to_II degrowth_NN1 include_VV0 free-riding_JJ ,_, which_DDQ could_VM become_VVI a_AT1 problem_NN1 when_CS degrowth_NN1 as_II a_AT1 movement_NN1 scales_NN2 up_RP ._. 
</s>
<s>
If_CS people_NN lack_NN1 incentives_NN2 to_TO follow_VVI a_AT1 sustainable_JJ lifestyle_NN1 in_II accordance_NN1 to_II degrowth_NN1 ,_, they_PPHS2 might_VM free-ride_NN1 on_II others_NN2 '_GE actions_NN2 instead_II21 of_II22 taking_VVG own_VV0 initiatives._NNU 4.2_MC Quantification_NN1 problem_NN1 Kerschner_NP1 points_VVZ out_RP that_CST many_DA2 existing_JJ economic_JJ theories_NN2 are_VBR irrational_JJ ,_, and_CC thus_RR the_AT degrowth-_JJ theories_NN2 have_VH0 the_AT same_DA possibilities_NN2 to_TO be_VBI formulated_VVN than_CSN any_DD other_JJ economic_JJ theories_NN2 ._. 
</s>
<s>
(_( Kerschner_NP1 ,_, 2010_MC )_) In_II fact_NN1 ,_, economists_NN2 rely_VV0 on_II the_AT human_JJ rationality_NN1 ,_, Homo_NP1 economicus_NN1 ,_, as_CSA an_AT1 underlying_JJ assumption_NN1 for_IF many_DA2 adopted_JJ policies_NN2 and_CC decisions_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ valid_JJ to_TO identify_VVI that_CST the_AT transition_NN1 from_II theory_NN1 to_II practice_NN1 is_VBZ not_XX very_RG functioning_JJ in_II economics_NN1 in_RR21 general_RR22 ._. 
</s>
<s>
Developing_VVG a_AT1 deeper_JJR theoretic_JJ framework_NN1 for_IF unfeasible_JJ objectives_NN2 is_VBZ thus_RR not_XX a_AT1 new_JJ idea_NN1 ,_, and_CC should_VM be_VBI pursued_VVN within_II degrowth-_NN1 and_CC steady-state_JJ -studies_NN2 ._. 
</s>
<s>
(_( Kerschner_NP1 ,_, 2010_MC )_) First_MD of_IO all_DB ,_, the_AT calculus_NN1 behind_II degrowth_NN1 needs_VVZ to_TO be_VBI developed_VVN and_CC made_VVN more_RRR advanced_VVN ._. 
</s>
<s>
If_CS the_AT degrowth_NN1 movement_NN1 fails_VVZ in_II offering_VVG a_AT1 tangible_JJ alternative_NN1 that_CST individuals_NN2 and_CC societies_NN2 in_RR21 general_RR22 can_VM adopt_VVI ,_, it_PPH1 will_VM not_XX survive_VVI when_CS applied_VVN to_II a_AT1 global_JJ scale_NN1 ._. 
</s>
<s>
Concerning_II the_AT literature_NN1 that_CST this_DD1 paper_NN1 has_VHZ comprised_VVN ,_, none_PN of_IO the_AT studies_NN2 have_VH0 succeeded_VVN to_TO serve_VVI an_AT1 economic_JJ framework_NN1 that_CST could_VM be_VBI used_VVN in_II practice_NN1 for_IF the_AT degrowth_NN1 approximation_NN1 ._. 
</s>
<s>
Considering_CS ,_, firstly_RR ,_, that_CST many_DA2 of_IO the_AT sources_NN2 used_VVN is_VBZ very_RG recent_JJ work_NN1 ,_, and_CC secondly_RR ,_, the_AT narrow_JJ supply_NN1 of_IO literature_NN1 on_II the_AT economics_NN1 of_IO degrowth_NN1 in_RR21 general_RR22 ,_, it_PPH1 can_VM be_VBI concluded_VVN that_CST the_AT economics_NN1 of_IO degrowth_NN1 is_VBZ relatively_RR non-existent_JJ ._. 
</s>
<s>
The_AT biggest_JJT questions_NN2 concern_VV0 quantification_NN1 :_: Cutting_VVG in_II current_JJ expenses_NN2 is_VBZ necessary_JJ in_BCL21 order_BCL22 to_TO achieve_VVI a_AT1 state_NN1 of_IO degrowth_NN1 ,_, but_CCB to_II what_DDQ extent_NN1 should_VM this_DD1 downscaling_NN1 occur_VVI ?_? 
</s>
<s>
What_DDQ is_VBZ the_AT contribution_NN1 needed_VVN from_II an_AT1 individual_JJ or_CC a_AT1 company_NN1 ,_, for_REX21 example_REX22 ,_, if_CS we_PPIS2 have_VH0 to_TO define_VVI this_DD1 contribution_NN1 in_II absolute_JJ terms_NN2 ?_? 
</s>
<s>
How_RGQ much_DA1 degrowth_NN1 is_VBZ needed_VVN to_TO produce_VVI a_AT1 sufficient_JJ input_NN1 for_IF reaching_VVG the_AT goals_NN2 of_IO degrowth_NN1 ?_? 
</s>
<s>
The_AT research_NN1 should_VM focus_VVI on_II answering_VVG these_DD2 questions_NN2 ,_, since_CS the_AT public_NN1 will_VM undoubtedly_RR ask_VVI them_PPHO2 ._. 
</s>
<s>
Furthermore_RR ,_, one_PN1 must_VM accept_VVI the_AT earlier_RRR mentioned_VVN notion_NN1 that_CST commitment_NN1 to_II a_AT1 lifestyle_NN1 of_IO degrowth_NN1 requires_VVZ a_AT1 moral_JJ obligation_NN1 from_II the_AT people_NN ._. 
</s>
<s>
Considering_CS21 that_CS22 we_PPIS2 live_VV0 in_II a_AT1 society_NN1 where_RRQ maximization_NN1 of_IO profits_NN2 is_VBZ the_AT mission_NN1 of_IO many_DA2 individuals_NN2 ,_, companies_NN2 and_CC civilizations_NN2 ,_, moral_JJ growth_NN1 of_IO humans_NN2 ca_VM n't_XX be_VBI expected_VVN to_TO occur_VVI over_II night_NNT1 ._. 
</s>
<s>
Thus_RR ,_, the_AT economic_JJ framework_NN1 of_IO degrowth_NN1 will_VM likely_RR be_VBI deficient_JJ at_RR21 least_RR22 to_II some_DD extent_NN1 ,_, should_VM it_PPH1 ever_RR be_VBI developed_VVN in_II the_AT first_MD place._NNU 4.3_MC The_AT definition_NN1 problem_NN1 The_AT degrowth-movement_NN1 's_GE Finnish_JJ web_NN1 site_NN1 defines_VVZ the_AT degrowth-economy_NN1 in_II a_AT1 somewhat_RR vague_JJ manner_NN1 by_II stating_VVG that_CST the_AT movement_NN1 does_VDZ not_XX desire_VVI to_TO replace_VVI the_AT current_JJ economic_JJ framework_NN1 and_CC theories_NN2 ._. 
</s>
<s>
The_AT site_NN1 underlines_VVZ the_AT importance_NN1 of_IO variety_NN1 -_- degrowth_NN1 societies_NN2 can_VM be_VBI organized_VVN in_II various_JJ forms_NN2 and_CC exhibit_VV0 different_JJ customs_NN2 ,_, depending_II21 on_II22 the_AT local_JJ culture_NN1 ._. 
</s>
<s>
(_( Mik_NN1 degrowth_NN1 ?_? )_) 
</s>
<s>
However_RR ,_, this_DD1 is_VBZ the_AT part_NN1 where_RRQ confusions_NN2 might_VM arise_VVI ._. 
</s>
<s>
The_AT allowance_NN1 for_IF interpretations_NN2 to_TO vary_VVI according_II21 to_II22 tradition_NN1 is_VBZ seen_VVN as_II a_AT1 strength_NN1 ,_, nevertheless_RR ,_, it_PPH1 is_VBZ also_RR a_AT1 weakness_NN1 to_TO lack_VVI a_AT1 uniform_JJ definition_NN1 ._. 
</s>
<s>
Furthermore_RR ,_, some_DD of_IO the_AT current_JJ claims_NN2 concerning_II degrowth_NN1 are_VBR contradicting_VVG ._. 
</s>
<s>
For_REX21 example_REX22 ,_, the_AT reduction_NN1 of_IO production_NN1 and_CC consumption_NN1 entails_VVZ an_AT1 underlying_JJ assumption_NN1 that_CST progress_NN1 in_II technology_NN1 is_VBZ negative_JJ for_IF the_AT society_NN1 ._. 
</s>
<s>
However_RR ,_, through_II a_AT1 more_RGR effective_JJ production_NN1 ,_, technological_JJ advancement_NN1 might_VM enable_VVI us_PPIO2 to_TO produce_VVI larger_JJR quantities_NN2 by_II using_VVG fewer_DAR resources_NN2 ._. 
</s>
<s>
Therefore_RR ,_, some_DD of_IO the_AT goals_NN2 set_VVN up_RP by_II degrowth-proponents_NN2 would_VM be_VBI unattainable_JJ without_IW sufficient_JJ usage_NN1 of_IO current_JJ knowledge_NN1 ._. 
</s>
<s>
To_II what_DDQ extent_NN1 should_VM we_PPIS2 depend_VVI on_II the_AT procedures_NN2 we_PPIS2 execute_VV0 and_CC live_VV0 by_RP in_II the_AT current_JJ society_NN1 of_IO economic_JJ growth_NN1 ,_, and_CC at_II which_DDQ point_NN1 should_VM new_JJ policies_NN2 take_VV0 over_RP control_NN1 ?_? 
</s>
<s>
A_AT1 more_RGR distinguished_JJ definition_NN1 would_VM lead_VVI to_II less_RGR informational_JJ difficulties_NN2 and_CC thereby_RR more_DAR proponents_NN2 (_( and_CC surely_RR ,_, more_DAR opponents_NN2 as_RR21 well_RR22 )_) ._. 
</s>
<s>
In_II future_JJ degrowth-_JJ related_JJ research_NN1 it_PPH1 would_VM be_VBI important_JJ to_TO focus_VVI on_II eliminating_VVG confusion._NNU 5_MC Conclusion_NN1 This_DD1 paper_NN1 has_VHZ discussed_VVN the_AT literature_NN1 on_II degrowth_NN1 ,_, a_AT1 movement_NN1 that_CST wishes_VVZ to_TO construct_VVI an_AT1 alternative_JJ economic_JJ system_NN1 for_IF modern_JJ societies_NN2 that_CST does_VDZ not_XX rely_VVI on_II economic_JJ growth_NN1 in_II itself_PPX1 ._. 
</s>
<s>
The_AT intention_NN1 of_IO this_DD1 study_NN1 has_VHZ been_VBN to_TO explore_VVI the_AT gaps_NN2 that_CST currently_RR exist_VV0 in_II this_DD1 literature_NN1 ._. 
</s>
<s>
A_AT1 comprehensive_JJ research_NN1 of_IO the_AT thoughts_NN2 behind_II degrowth_NN1 reveals_VVZ that_CST the_AT aim_NN1 of_IO this_DD1 movement_NN1 needs_VVZ to_TO be_VBI specified_VVN more_RGR clearly_RR in_BCL21 order_BCL22 to_TO catch_VVI the_AT attention_NN1 of_IO new_JJ ,_, more_RGR difficultly_RR convinced_JJ ,_, crowds_NN2 like_II policymakers_NN2 and_CC economists_NN2 ._. 
</s>
<s>
The_AT problems_NN2 this_DD1 paper_NN1 identifies_NN1 include_VV0 the_AT problem_NN1 of_IO definition_NN1 ,_, the_AT quantification_NN1 issue_NN1 as_II31 well_II32 as_II33 problems_NN2 related_VVN to_II asymmetric_JJ information_NN1 ._. 
</s>
<s>
Furthermore_RR ,_, the_AT nature_NN1 of_IO human_JJ beings_NN2 can_VM and_CC will_VM be_VBI a_AT1 problematic_JJ issue_NN1 for_IF the_AT execution_NN1 of_IO degrowth_NN1 ._. 
</s>
<s>
A_AT1 moral_JJ growth_NN1 in_II people_NN would_VM be_VBI demanded_VVN in_BCL21 order_BCL22 to_TO be_VBI able_JK to_TO achieve_VVI desired_JJ commitment_NN1 ._. 
</s>
<s>
However_RR ,_, not_XX all_DB hope_NN1 is_VBZ lost_VVN ,_, due_II21 to_II22 the_AT increasing_JJ appreciation_NN1 of_IO a_AT1 slower_JJR lifestyle_NN1 ,_, which_DDQ can_VM be_VBI seen_VVN as_II a_AT1 response_NN1 to_II the_AT consequences_NN2 associated_VVN with_IW the_AT past_JJ years_NNT2 '_GE financial_JJ crisis_NN1 ._. 
</s>
<s>
Therefore_RR ,_, if_CS the_AT term_NN1 degrowth_NN1 could_VM be_VBI clarified_VVN and_CC quantified_VVN more_RGR precisely_RR ,_, the_AT public_NN1 could_VM have_VHI a_AT1 chance_NN1 to_TO adjust_VVI their_APPGE lives_NN2 accordingly_RR ,_, and_CC thus_RR we_PPIS2 could_VM have_VHI the_AT opportunity_NN1 to_TO move_VVI towards_II a_AT1 future_NN1 with_IW a_AT1 contracted_JJ economy_NN1 ._. 
</s>
