<s>
Money_NN1 as_II a_AT1 motivator_NN1 Introduction_NN1 :_: Since_CS motivation_NN1 of_IO employees_NN2 is_VBZ considered_VVN by_II leadership_NN1 theories_NN2 beginning_VVG with_IW assembly_NN1 line_NN1 production_NN1 of_IO the_AT legendary_JJ Ford-T_NP1 at_II Highland_NP1 Park_NN1 in_II Detroit-_NN1 the_AT impact_NN1 of_IO variation_NN1 in_II salary_NN1 became_VVD a_AT1 central_JJ topic_NN1 of_IO different_JJ leadership_NN1 approaches_NN2 ._. 
</s>
<s>
In_II recent_JJ years_NNT2 ,_, there_EX have_VH0 been_VBN many_DA2 papers_NN2 describing_VVG both_RR positive_JJ and_CC negative_JJ aspects_NN2 of_IO money_NN1 on_II efficiency_NN1 of_IO labor_NN1 and_CC satisfaction_NN1 among_II staff_NN ._. 
</s>
<s>
It_PPH1 is_VBZ generally_RR accepted_VVN that_DD1 money_NN1 can_VM be_VBI counted_VVN as_II a_AT1 strong_JJ motivator_NN1 ,_, especially_RR for_IF lower_JJR and_CC middle_JJ income_NN1 levels_NN2 -_- concerning_VVG higher_JJR salary_NN1 grades_NN2 disagreements_NN2 can_VM be_VBI observed_VVN ._. 
</s>
<s>
Compared_VVN to_II other_JJ impacts_NN2 on_II motivation_NN1 as_CSA work_NN1 atmosphere_NN1 ,_, promotion_NN1 possibilities_NN2 or_CC social_JJ status_NN1 ,_, money_NN1 is_VBZ in_RR21 general_RR22 credited_VVN as_RG less_RGR efficient_JJ ,_, in_RR21 particular_RR22 when_CS a_AT1 certain_JJ level_NN1 of_IO salary_NN1 is_VBZ reached_VVN ._. 
</s>
<s>
Publications_NN2 of_IO common_JJ motivation_NN1 theories_NN2 and_CC leadership_NN1 approaches_NN2 pay_VV0 attention_NN1 to_II money_NN1 as_II a_AT1 motivator_NN1 ,_, but_CCB do_VD0 not_XX attach_VVI great_JJ importance_NN1 to_II money_NN1 as_II the_AT most_RGT effective_JJ way_NN1 of_IO affecting_VVG followers_NN2 in_BCL21 order_BCL22 to_TO raise_VVI their_APPGE outcome_NN1 and_CC satisfaction_NN1 ._. 
</s>
<s>
(_( Northouse_NN1 2010_MC ,_, Rollinson_NP1 2008_MC )_) However_RR ,_, this_DD1 view_NN1 is_VBZ challenged_VVN by_II papers_NN2 showing_VVG that_DD1 money_NN1 is_VBZ more_RGR important_JJ to_II employees_NN2 than_CSN is_VBZ admitted_VVN at_RR21 first_RR22 ._. 
</s>
<s>
(_( Rynes_NP1 2004_MC )_) In_II31 spite_II32 of_II33 these_DD2 observations_NN2 ,_, the_AT common_JJ idea_NN1 of_IO money_NN1 as_II a_AT1 major_JJ but_CCB not_XX as_II the_AT most_RGT important_JJ factor_NN1 remains_VVZ unclear_JJ ._. 
</s>
<s>
Moreover_RR ,_, RSA_NP1 Animate_VV0 with_IW their_APPGE animated_JJ presentation_NN1 Drive_NN1 :_: The_AT surprising_JJ truth_NN1 about_II what_DDQ motivates_VVZ us_PPIO2 clearly_RR figures_VVZ out_RP that_CST the_AT same_DA stimuli_NN2 based_VVN on_II money_NN1 reward_NN1 causes_VVZ different_JJ results_NN2 between_II US_NP1 and_CC Indian_JJ participants_NN2 ._. 
</s>
<s>
This_DD1 supports_VVZ the_AT argument_NN1 that_CST differences_NN2 in_II cultural_JJ values_NN2 and_CC norms_NN2 tend_VV0 to_TO influence_VVI efficient_JJ adaptability_NN1 of_IO money_NN1 as_II a_AT1 motivator_NN1 stronger_JJR than_CSN supposed_VVN in_RR21 general_RR22 ._. 
</s>
<s>
This_DD1 paper_NN1 evaluates_VVZ the_AT significance_NN1 of_IO payment_NN1 for_IF employees_NN2 as_RG well_RR as_CSA for_IF leaders_NN2 by_II showing_VVG that_DD1 money_NN1 is_VBZ -_- against_II common_JJ opinion_NN1 -_- the_AT most_RGT important_JJ motivator_NN1 ,_, independent_JJ from_II social_JJ status_NN1 or_CC financial_JJ situation_NN1 ._. 
</s>
<s>
Furthermore_RR ,_, differences_NN2 between_II individualistic_JJ and_CC collectivistic_JJ societies_NN2 according_II wage_NN1 as_II a_AT1 motivator_NN1 should_VM be_VBI illustrated_VVN ._. 
</s>
<s>
The_AT rest_NN1 of_IO this_DD1 paper_NN1 will_VM be_VBI organized_VVN in_II the_AT following_JJ way_NN1 :_: An_AT1 overview_NN1 on_II the-state-of-the-art_JJ motivation_NN1 theories_NN2 and_CC leadership_NN1 approaches_NN2 should_VM give_VVI basic_JJ background_NN1 in_BCL21 order_BCL22 to_TO highlight_VVI how_RRQ money_NN1 accts_VVZ as_II a_AT1 motivator_NN1 within_II each_DD1 of_IO them_PPHO2 ._. 
</s>
<s>
Based_VVN on_II these_DD2 theories_NN2 money_NN1 as_CSA one_MC1 of_IO the_AT most_RGT effective_JJ motivation_NN1 approaches_NN2 should_VM be_VBI supported_VVN ,_, including_II cultural_JJ aspects_NN2 on_II the_AT effect_NN1 of_IO money_NN1 as_CSA motivator_NN1 ._. 
</s>
<s>
What_DDQ is_VBZ motivation_NN1 ?_? 
</s>
<s>
Motivation_NN1 can_VM be_VBI summarized_VVN as_II an_AT1 interaction_NN1 of_IO internal_JJ (_( intrinsic_JJ motivation_NN1 )_) and_CC external_JJ (_( extrinsic_JJ motivation_NN1 )_) impacts_NN2 or_CC forces_NN2 affecting_VVG an_AT1 individual_JJ to_TO focus_VVI on_II a_AT1 specific_JJ issue_NN1 or_CC task_NN1 leading_VVG to_II a_AT1 satisfying_JJ accomplishment_NN1 ._. 
</s>
<s>
In_II this_DD1 connection_NN1 internal_JJ impacts_NN2 result_VV0 from_II psychological_JJ values_NN2 and_CC personal_JJ achievements_NN2 a_AT1 person_NN1 can_VM gain_VVI directly_RR from_II the_AT given_JJ task_NN1 or_CC action_NN1 ._. 
</s>
<s>
In_II contrast_NN1 ,_, external_JJ ones_NN2 are_VBR provided_VVN from_II the_AT surrounding_JJ organization_NN1 based_VVN on_II ones_NN2 performance_NN1 and_CC criteria_NN2 or_CC norms_NN2 defined_VVN outside_II21 of_II22 the_AT individual_NN1 ._. 
</s>
<s>
As_CSA examples_NN2 satisfaction_NN1 caused_VVN by_II an_AT1 autonomous_JJ and_CC successful_JJ managed_JJ task_NN1 for_IF intrinsic_JJ and_CC salary_NN1 ,_, social_JJ security_NN1 contributions_NN2 or_CC a_AT1 company_NN1 car_NN1 representing_VVG extrinsic_JJ motivation_NN1 can_VM be_VBI mentioned_VVN ._. 
</s>
<s>
As_CSA both_RR strongly_RR depend_VV0 on_II personal_JJ values_NN2 and_CC expectations_NN2 motivational_JJ effect_NN1 of_IO internal_JJ and_CC external_JJ factors_NN2 strongly_RR varies_VVZ in_II orientation_NN1 and_CC amplitude_NN1 among_II individuals_NN2 ._. 
</s>
<s>
What_DDQ significantly_RR raises_VVZ ones_NN2 performance_NN1 might_VM be_VBI totally_RR different_JJ gathered_JJ by_II someone_PN1 else_RR ._. 
</s>
<s>
Furthermore_RR ,_, manner_NN1 of_IO getting_VVG motivated_JJ strongly_RR differs_VVZ between_II individuals_NN2 ,_, whereby_RRQ a_AT1 general_JJ strategy_NN1 for_IF general_JJ motivation_NN1 hardly_RR can_VM be_VBI found_VVN ._. 
</s>
<s>
As_II the_AT level_NN1 of_IO motivation_NN1 varies_VVZ both_RR between_II individuals_NN2 and_CC within_II individuals_NN2 at_II different_JJ times_NNT2 and_CC jobs_NN2 the_AT target_NN1 of_IO motivating_VVG followers_NN2 sadly_RR has_VHZ nothing_PN1 to_TO do_VDI with_IW a_AT1 one_MC1 shot-deal_NN1 gaining_VVG motivation_NN1 among_II employees_NN2 for_IF a_AT1 certain_JJ time_NNT1 period_NN1 ;_; it_PPH1 is_VBZ more_RGR or_CC less_RRR a_AT1 process_NN1 of_IO providing_VVG permanent_JJ stimulation_NN1 based_VVN on_II changing_JJ circumstances_NN2 and_CC individual_JJ expectations_NN2 and_CC needs_NN2 ._. 
</s>
<s>
(_( Rollinson_NP1 2008:195-199_MCMC )_) How_RRQ money_NN1 is_VBZ seen_VVN as_II a_AT1 motivator_NN1 ._. 
</s>
<s>
Based_VVN on_II the_AT fundamental_JJ ideas_NN2 of_IO capitalism_NN1 and_CC free-market_NN1 economy_NN1 ,_, leading_VVG to_II modern_JJ economic_JJ systems_NN2 ,_, efficiency_NN1 of_IO performance_NN1 and_CC continuous_JJ output_NN1 improvement_NN1 play_VV0 a_AT1 major_JJ role_NN1 in_II todays_NN2 business_NN1 live_VV0 ._. 
</s>
<s>
According_II21 to_II22 Vroom_NP1 performance_NN1 (_( P_ZZ1 )_) can_VM be_VBI described_VVN as_II a_AT1 function_NN1 of_IO work_NN1 environment_NN1 or_CC equipment_NN1 provided_VVN to_TO fulfill_VVI a_AT1 certain_JJ task_NN1 (_( Environment_NN1 E_ZZ1 )_) ,_, the_AT traits_NN2 ,_, skills_NN2 ,_, and_CC (_( expertise-_NN1 )_) knowledge_NN1 of_IO an_AT1 individual_NN1 (_( Ability_NN1 A_ZZ1 )_) ,_, and_CC motivation_NN1 to_TO accomplish_VVI the_AT task_NN1 successfully_RR (_( Motivation_NN1 M_ZZ1 )_) ._. 
</s>
<s>
In_RR21 brief_RR22 :_: P=f_NP1 (_( E_ZZ1 ,_, A_ZZ1 ,_, M_ZZ1 )_) (_( Rollinson_NP1 2008:195_MC )_) ._. 
</s>
<s>
Whereas_CS managers_NN2 impact_NN1 on_II first_MD two_MC mentioned_VVD factors_NN2 by_II control_NN1 of_IO resources_NN2 and_CC installation_NN1 of_IO coaching_VVG programs_NN2 is_VBZ generally_RR doubtless_RR accepted_VVN ,_, discussion_NN1 connected_VVN to_II effects_NN2 of_IO different_JJ leadership_NN1 approaches_VVZ on_II follower_NN1 motivation_NN1 is_VBZ still_RR in_II progress_NN1 ._. 
</s>
<s>
Therefore_RR the_AT question_NN1 How_RRQ employees_NN2 can_VM be_VBI motivated_VVN in_II an_AT1 efficient_JJ way_NN1 in_BCL21 order_BCL22 to_TO cause_VVI or_CC raise_VVI their_APPGE inspiration_NN1 for_IF a_AT1 given_JJ task_NN1 resulting_VVG in_II better_JJR performance_NN1 ?_? is_VBZ an_AT1 omnipresent_NN1 and_CC central_JJ topic_NN1 in_II common_JJ leadership_NN1 courses_NN2 and_CC state_NN1 of_IO the_AT art_NN1 management_NN1 education_NN1 programs_NN2 ._. 
</s>
<s>
According_II21 to_II22 Frederic_NP1 W_NP1 Taylor_NP1 (_( 1911_MC )_) who_PNQS is_VBZ considered_VVN as_CSA initiator_NN1 of_IO todays_NN2 motivation_NN1 theories_NN2 Rollinson_NP1 described_VVD core_NN1 values_NN2 of_IO scientific_JJ management_NN1 as_CSA follows_VVZ :_: Most_DAT important_JJ of_IO these_DD2 is_VBZ the_AT assumption_NN1 that_CST the_AT main_JJ (_( and_CC perhaps_RR only_RR )_) thing_NN1 that_CST people_NN seek_VV0 to_TO obtain_VVI from_II work_NN1 is_VBZ high_JJ pay._NNU (_( Rollinson_NP1 2008:201-202_MCMC )_) ._. 
</s>
<s>
The_AT studies_NN2 from_II Ronen_NP1 (_( 1986_MC )_) clearly_RR support_VV0 this_DD1 argument_NN1 by_II pointing_VVG out_RP importance_NN1 of_IO different_JJ functions_NN2 of_IO work_NN1 ._. 
</s>
<s>
Even_CS21 though_CS22 the_AT relative_JJ importance_NN1 among_II analyzed_JJ countries_NN2 alternates_VVZ ,_, the_AT function_NN1 of_IO work_NN1 as_II a_AT1 source_NN1 of_IO income_NN1 compared_VVN to_II source_NN1 of_IO interest_NN1 ,_, status_NN1 ,_, prestige_NN1 or_CC social_JJ satisfaction_NN1 is_VBZ highlighted_VVN ._. 
</s>
<s>
Money_NN1 as_II a_AT1 strong_JJ motivator_NN1 is_VBZ broadly_RR accepted_VVN ,_, but_CCB researches_NN2 figured_VVD out_RP that_DD1 money_NN1 is_VBZ much_RR more_RGR important_JJ to_II individuals_NN2 than_CSN generally_RR announced_VVN ._. 
</s>
<s>
These_DD2 deviations_NN2 result_VV0 in_II the_AT observed_JJ fact_NN1 that_CST HR_NNU managers_NN2 often_RR are_VBR evaluating_VVG money_NN1 not_XX adequately_RR ._. 
</s>
<s>
(_( Rynes_NP1 2004_MC )_) How_RRQ motivation_NN1 theories_NN2 support_VV0 Money_NN1 as_II an_AT1 important_JJ motivator_NN1 ?_? 
</s>
<s>
Based_VVN on_II widely_RR accepted_JJ motivation_NN1 theories_NN2 arguments_NN2 pro_II money_NN1 as_II a_AT1 motivator_NN1 will_VM be_VBI provided_VVN ._. 
</s>
<s>
These_DD2 theories_NN2 of_IO work_NN1 motivation_NN1 are_VBR generally_RR divided_VVN into_II two_MC groups_NN2 :_: Content_JJ and_CC Process_VV0 theories_NN2 ._. 
</s>
<s>
The_AT earlier_RRR presented_VVN Content_JJ theories_NN2 mainly_RR concentrates_VVZ on_II specific_JJ physiological_JJ and_CC psychological_JJ needs_NN2 and_CC demands_NN2 of_IO individuals_NN2 in_BCL21 order_BCL22 to_TO point_VVI out_RP what_DDQ motivates_VVZ and_CC what_DDQ has_VHZ influence_NN1 on_II ones_NN2 behavior_NN1 in_II a_AT1 direct_JJ way_NN1 under_II different_JJ circumstances_NN2 ._. 
</s>
<s>
Second_MD ,_, Process_VV0 theory_NN1 ,_, focuses_VVZ on_II the_AT question_NN1 how_RRQ managers_NN2 can_VM change_VVI behavior_NN1 of_IO their_APPGE followers_NN2 to_TO raise_VVI their_APPGE motivation_NN1 ._. 
</s>
<s>
(_( Rollinson_NN1 2008:202_MC )_) Concerning_II content_JJ approach_NN1 -what_DDQ motives_NN2 and_CC needs_VVZ human_JJ beings_NN2 have-_NN1 a_AT1 short_JJ overview_NN1 of_IO the_AT following_JJ three_MC theories_NN2 will_VM be_VBI given_VVN :_: The_AT Hierarchy_NN1 of_IO Needs_VVZ Theory_NN1 (_( Maslow_NP1 1954_MC )_) ,_, the_AT Two-factor_JJ Theory_NN1 (_( Herzberg_NP1 1959_MC )_) ,_, and_CC the_AT ERG_NN1 Theory_NN1 (_( Alderfer_NP1 1972_MC )_) ._. 
</s>
<s>
Maslows_NP1 Hierarchy_NN1 of_IO Needs_VVZ Theory_NN1 :_: Maslow_NP1 describes_VVZ needs_NN2 of_IO every_AT1 human_JJ individual_NN1 by_II his_APPGE Pyramid_NN1 of_IO Needs_NN2 with_IW five_MC different_JJ levels_NN2 ;_; bottom-up_NN1 :_: Physiological_JJ ,_, Security_NN1 ,_, Affiliation_NN1 ,_, Esteem_NN1 ,_, and_CC Self-actualization_NN1 ._. 
</s>
<s>
Moreover_RR ,_, this_DD1 theory_NN1 argues_VVZ that_CST all_DB these_DD2 levels_NN2 do_VD0 not_XX overlap_VVI or_CC gear_NN1 into_II each_PPX221 other_PPX222 and_CC every_AT1 individual_NN1 is_VBZ striving_VVG beginning_NN1 with_IW Physiological_JJ needs_NN2 to_TO climb_VVI the_AT strict_JJ hierarchically_RR ordered_VVN pyramid_NN1 towards_II to_II above_RL opened_VVD Self-actualization_JJ level_NN1 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, Maslow_NP1 argues_VVZ that_DD1 motivation_NN1 only_RR can_VM be_VBI induced_VVN by_II needs_NN2 of_IO the_AT actual_JJ level_NN1 ,_, and_CC ones_NN2 this_DD1 level_NN1 is_VBZ passed_VVN ,_, no_AT effect_NN1 can_VM be_VBI generated_VVN anymore_RR ._. 
</s>
<s>
(_( This_DD1 is_VBZ also_RR his_APPGE most_RGT criticized_JJ conclusion_NN1 )_) Physiological_JJ needs_VVZ focus_NN1 on_II basic_JJ requirements_NN2 need_VV0 to_TO survive_VVI :_: Food_NN1 ,_, water_NN1 ,_, air_NN1 and_CC adequate_JJ heated_JJ shelter_NN1 ._. 
</s>
<s>
Security_NN1 needs_NN2 are_VBR dealing_VVG with_IW safety_NN1 of_IO ones_NN2 live_VV0 and_CC environment_NN1 ,_, absence_NN1 of_IO violence_NN1 ,_, pain_NN1 and_CC poorness_NN1 ,_, and_CC predictability_NN1 of_IO ones_NN2 surrounding_VVG ._. 
</s>
<s>
Affiliation_NN1 is_VBZ based_VVN on_II human_JJ beings_NN2 social_JJ needs_NN2 of_IO being_VBG loved_VVN ,_, belonging_VVG to_II groups_NN2 and_CC societies_NN2 ,_, and_CC having_VHG friends_NN2 and_CC family_NN1 ._. 
</s>
<s>
The_AT forth_RR level_JJ Esteem_NN1 covers_VVZ the_AT approval_NN1 and_CC support_VV0 from_II family_NN1 ,_, friends_NN2 or_CC peers_NN2 ,_, self-respect_NN1 as_II31 well_II32 as_II33 self-confidence_NN1 ,_, and_CC respect_NN1 respectively_RR status_NN1 among_II ambient_JJ society_NN1 ._. 
</s>
<s>
Self-actualization_NN1 including_II education_NN1 ,_, personal_JJ development_NN1 ,_, hobbies_NN2 ,_, and_CC self-realization_NN1 is_VBZ counted_VVN as_II the_AT most_RGT powerful_JJ motivation_NN1 level_NN1 pushing_VVG human_JJ beings_NN2 to_II new_JJ theories_NN2 ,_, inventions_NN2 ,_, improvements_NN2 and_CC mental_JJ and_CC cultural_JJ top-performing_NN1 ._. 
</s>
<s>
(_( Rollinson_NP1 2008:202-204_MCMC )_) Due_II21 to_II22 the_AT fact_NN1 that_CST especially_RR in_II western_JJ industrialized_JJ countries_NN2 living_VVG standard_NN1 is_VBZ strongly_RR connected_VVN to_II available_JJ budget_NN1 Maslows_VVZ Hierarchy_NN1 of_IO Needs_VVZ Theory_NN1 supplies_VVZ numerous_JJ plausible_JJ perspicuous_JJ arguments_NN2 for_IF money_NN1 as_II a_AT1 motivator_NN1 ._. 
</s>
<s>
Concerning_II basic_JJ physiological_JJ needs_NN2 hardly_RR any_DD doubts_NN2 against_II money_NN1 occur_VV0 as_CSA grocery_NN1 and_CC rent_VV0 for_IF flat_NN1 are_VBR directly_RR connected_VVN to_II successive_JJ expenses_NN2 ._. 
</s>
<s>
Satisfaction_NN1 of_IO Security_NN1 needs_NN2 is_VBZ strongly_RR related_VVN to_II retirement_NN1 arrangement_NN1 and_CC medical_JJ supply_NN1 ._. 
</s>
<s>
Although_CS both_RR indeed_RR are_VBR in_II several_DA2 countries_NN2 nationalized_VVD ,_, private_JJ financial_JJ precaution_NN1 is_VBZ an_AT1 important_JJ and_CC costly_JJ issue_NN1 for_IF most_DAT individuals_NN2 ._. 
</s>
<s>
Apart_II21 from_II22 the_AT assumption_NN1 that_CST wealth_NN1 allures_NN2 friends_NN2 Maslows_VVZ Affiliation_NN1 should_VM be_VBI more_RGR or_CC less_RGR independent_JJ from_II payment_NN1 ._. 
</s>
<s>
In_II contrary_JJ Esteem_NN1 describing_VVG self-confidence_NN1 respect_NN1 and_CC status_NN1 thoroughly_RR can_VM be_VBI linked_VVN to_II money_NN1 and_CC payment_NN1 ;_; especially_RR in_II individualistic_JJ and_CC materialistic_JJ orientated_JJ societies_NN2 ._. 
</s>
<s>
Compared_VVN to_II the_AT pre-stages_NN2 Self-actualization_JJ supports_NN2 above_RL mentioned_VVD argument_NN1 in_II the_AT most_RGT significant_JJ way_NN1 ._. 
</s>
<s>
Hobbies_NN2 as_CSA traveling_VVG ,_, regular_JJ vacation_NN1 ,_, interest_NN1 in_II art_NN1 and_CC culture_NN1 and_CC further_JJR education_NN1 definitely_RR can_VM be_VBI described_VVN as_CSA very_RG expensive_JJ and_CC therefore_RR require_VV0 an_AT1 adequate_JJ salary_NN1 ._. 
</s>
<s>
Herzbergs_NP1 Two-factor_JJ Theory_NN1 :_: Herzberg_NP1 announced_VVD that_CST the_AT presence_NN1 of_IO two_MC different_JJ groups_NN2 of_IO influence_NN1 affecting_VVG on_II each_DD1 individual_NN1 is_VBZ a_AT1 necessarily_RR required_JJ pre-condition_NN1 to_TO gain_VVI satisfaction_NN1 among_II employees_NN2 ._. 
</s>
<s>
The_AT so_JJ21 called_JJ22 hygiene_NN1 factors_NN2 covering_VVG salary_NN1 ,_, relationship_NN1 among_II peers_NN2 ,_, working_VVG conditions_NN2 or_CC company_NN1 policies_NN2 are_VBR necessary_JJ to_TO avoid_VVI dissatisfaction_NN1 and_CC act_VVI more_DAR or_CC less_RRR as_II negative_JJ null_JJ balance_NN1 without_IW having_VHG significant_JJ satisfying_JJ effects_NN2 ._. 
</s>
<s>
Once_RR all_DB negative_JJ influences_NN2 are_VBR removed_VVN by_II these_DD2 hygiene_NN1 factors_NN2 amplitude_NN1 of_IO satisfaction_NN1 is_VBZ only_RR a_AT1 function_NN1 of_IO different_JJ motivators_NN2 like_II achievement_NN1 ,_, career_NN1 expectations_NN2 or_CC responsibility_NN1 ._. 
</s>
<s>
Summing_VVG up_RP ,_, one_MC1 of_IO Herzbergs_NP2 core_NN1 statements_NN2 is_VBZ that_DD1 dissatisfaction_NN1 can_VM not_XX be_VBI counted_VVN as_II the_AT counterpart_NN1 of_IO satisfaction_NN1 and_CC vice_RR21 versa_RR22 ._. 
</s>
<s>
Both_DB2 are_VBR opposing_VVG no_AT but_CCB just_RR in_II other_JJ directions_NN2 ._. 
</s>
<s>
(_( Rollinson_NP1 2008:206-207_MCMC )_) Based_VVN on_II Herzbergs_NP2 work_VV0 salary_NN1 is_VBZ classified_VVN as_CSA hygiene_NN1 factor_NN1 as_II31 well_II32 as_II33 motivator_NN1 ._. 
</s>
<s>
According_II21 to_II22 the_AT function_NN1 as_II a_AT1 hygiene_NN1 factor_NN1 providing_VVG dissatisfaction_NN1 which_DDQ can_VM be_VBI caused_VVN by_II underpayment_NN1 or_CC (_( related_VVN to_II further_RRR down_RP mentioned_VVD Equity_NN1 Theory_NN1 )_) by_II subjective_JJ impression_NN1 of_IO being_VBG under_RG rewarded_VVN the_AT importance_NN1 of_IO payment_NN1 is_VBZ generally_RR accepted_VVN ;_; concerning_II function_NN1 as_CSA motivator_NN1 views_NN2 are_VBR drifting_VVG ._. 
</s>
<s>
While_CS critics_NN2 argue_VV0 that_DD1 money_NN1 loses_VVZ its_APPGE motivational_JJ abilities_NN2 with_IW rising_VVG salary_NN1 ,_, refer_VV0 advocators_NN2 to_II a_AT1 nonlinear_JJ motivational_JJ effect_NN1 of_IO money_NN1 ._. 
</s>
<s>
(_( Rynes_NP1 2004_MC )_) However_RR ,_, concerning_II Forbes_NP1 the_AT number_NN1 of_IO super-rich_JJ ones_NN2 indeed_RR is_VBZ increasing_JJ ;_; compared_VVN to_II average_JJ earners_NN2 their_APPGE number_NN1 is_VBZ still_RR evanescent_JJ and_CC negligible_JJ ._. 
</s>
<s>
Summing_VVG up_RP ,_, referring_VVG to_II the_AT average_JJ employee_NN1 money_NN1 has_VHZ a_AT1 significant_JJ influence_NN1 on_II satisfaction_NN1 both_RR as_CSA hygiene_NN1 and_CC as_CSA motivation_NN1 factor_NN1 ._. 
</s>
<s>
Alderfers_NN2 ERG_VV0 Theory_NN1 :_: Similar_JJ to_II the_AT idea_NN1 of_IO above_RL mentioned_VVD Maslows_NP1 Hierarchy_NN1 of_IO Needs_VVZ Theory_NN1 Aldorfer_NP1 based_VVD his_APPGE theory_NN1 of_IO needs_NN2 on_II three_MC hierarchically_RR ordered_VVN levels_NN2 :_: Existence_NN1 ,_, Relatedness_NP1 ,_, and_CC Growth_NN1 (_( ERG_NP1 )_) ._. 
</s>
<s>
The_AT lowest_JJT step_NN1 (_( Existence_NN1 )_) describing_VVG basic_JJ human_JJ needs_NN2 is_VBZ comparable_JJ to_II Maslows_NP1 Physiological_JJ and_CC Security_NN1 needs_VVZ whereas_CS Relatedness_NP1 needs_VVZ including_II social_JJ needs_NN2 and_CC interaction_NN1 within_II a_AT1 society_NN1 is_VBZ strongly_RR related_VVN to_II Affiliation_NN1 and_CC Esteem_NN1 ._. 
</s>
<s>
The_AT individualistic_JJ part_NN1 of_IO Maslows_NP1 Esteem_NN1 (_( self-respect_NN1 and_CC self-confidence_NN1 )_) and_CC Self-actualization_JJ result_NN1 in_II Aldorfers_NP1 highest_JJT level_NN1 :_: Growth_NN1 needs_NN2 ._. 
</s>
<s>
In_RP contrary_II21 to_II22 Maslow_NP1 the_AT ERG_NN1 Theory_NN1 argues_VVZ that_CST even_CS21 though_CS22 each_DD1 human_JJ being_NN1 bottom-up_NN1 aspires_VVZ to_II Growth_NN1 needs_NN2 ,_, parallel_JJ existence_NN1 of_IO all_DB levels_NN2 is_VBZ quite_RG possible_JJ ._. 
</s>
<s>
Furthermore_RR ,_, Adler_NP1 in_RR21 addition_RR22 pays_VVZ attention_NN1 to_II impacts_NN2 of_IO not_XX fully_RR satisfied_JJ levels_NN2 of_IO needs_NN2 ._. 
</s>
<s>
(_( Rollinson_NP1 2008:204-205_MCMC )_) Linked_VVN to_II overlapping_VVG with_IW Hierarchy_NN1 of_IO needs_VVZ Aldorfes_NP2 basic_JJ and_CC top_JJ level_NN1 (_( Existence_NN1 and_CC Growth_NN1 )_) support_VV0 money_NN1 as_II a_AT1 motivator_NN1 in_II the_AT same_DA way_NN1 as_CSA Maslows_VVZ Physiological-_NN1 ,_, Security-_NN1 ,_, Esteem-_NN1 ,_, and_CC Self-actualization_JJ needs_NN2 do_VD0 ._. 
</s>
<s>
Even_CS21 though_CS22 ,_, as_CSA above_RL already_RR mentioned_VVN ,_, Existence_NN1 and_CC Growth_NN1 needs_NN2 are_VBR strongly_RR connected_VVN to_II norms_NN2 and_CC values_NN2 created_VVN by_II social_JJ surrounding_JJ ,_, average_JJ satisfaction_NN1 is_VBZ related_VVN to_II a_AT1 certain_JJ level_NN1 of_IO wealth_NN1 ._. 
</s>
<s>
Representing_VVG process_NN1 theory_NN1 -how_RRQ to_II motivate-_NN1 two_MC subsequent_JJ theories_NN2 will_VM be_VBI described_VVN :_: The_AT Expectancy_NN1 Theory_NN1 (_( Vroom_NP1 1964_MC )_) and_CC the_AT Equity_NN1 Theory_NN1 (_( Adams_NP1 1965_MC )_) ._. 
</s>
<s>
Vrooms_NP1 Expectancy_NN1 Theory_NN1 :_: Basic_JJ idea_NN1 of_IO this_DD1 theory_NN1 is_VBZ that_CST leaders_NN2 can_VM motivate_VVI their_APPGE followers_NN2 to_TO accomplish_VVI a_AT1 certain_JJ task_NN1 by_II assuring_VVG or_CC promising_VVG a_AT1 positive_JJ reward_NN1 as_II a_AT1 result_NN1 of_IO good_JJ performance_NN1 -similar_JJ to_II positive_JJ reinforcement_NN1 (_( Rollinson_NP1 2008:177_MC )_) ._. 
</s>
<s>
Therefore_RR ,_, Vroom_NP1 ,_, to_TO clarify_VVI that_CST only_RR a_AT1 positive_JJ valued_JJ reward_NN1 can_VM lead_VVI to_II motivation_NN1 ,_, introduced_VVD Valence_NP1 describing_VVG the_AT individuals_NN2 preference_NN1 of_IO announced_JJ benefits_NN2 which_DDQ wildly_RR can_VM vary_VVI among_II followers_NN2 ._. 
</s>
<s>
Furthermore_RR ,_, he_PPHS1 argues_VVZ that_CST employees_NN2 only_RR put_VV0 more_DAR effort_NN1 to_II a_AT1 given_JJ task_NN1 ,_, if_CS they_PPHS2 really_RR expect_VV0 that_CST the_AT promised_JJ benefits_NN2 indeed_RR will_VM result_VVI from_II better_JJR performance_NN1 ._. 
</s>
<s>
If_CS any_DD doubts_NN2 concerning_II reliability_NN1 occur_VV0 ,_, no_AT increase_NN1 in_II performance_NN1 can_VM be_VBI expected_VVN ._. 
</s>
<s>
(_( Rollinson_NP1 2008:229-230_MCMC )_) Not_XX for_IF all_DB individuals_NN2 money_NN1 itself_PPX1 has_VHZ the_AT highest_JJT significance_NN1 in_II their_APPGE lives_NN2 ._. 
</s>
<s>
Preferences_NN2 range_VV0 from_II expensive_JJ houses_NN2 ,_, high_JJ living_JJ standard_NN1 ,_, and_CC education_NN1 for_IF kids_NN2 to_II maximization_NN1 of_IO leisure_NN1 time_NNT1 etc._RA leading_VVG to_II the_AT fact_NN1 that_CST a_AT1 benefit_NN1 or_CC reward_NN1 highly_RR valued_VVN by_II one_MC1 employee_NN1 not_XX necessarily_RR has_VHZ the_AT same_DA effect_NN1 on_II motivation_NN1 to_II others_NN2 ._. 
</s>
<s>
On_II the_AT opposite_JJ ,_, salary_NN1 is_VBZ in_RR21 general_RR22 valued_VVN indirectly_RR by_II creating_VVG its_APPGE stimulus_NN1 acting_VVG as_II a_AT1 coupon_NN1 everyone_PN1 can_VM spend_VVI or_CC invest_VVI individually_RR ._. 
</s>
<s>
Moreover_RR ,_, in_BCL21 order_BCL22 to_TO create_VVI expectancy_NN1 among_II followers_NN2 bonuses_NN2 in_RR21 general_RR22 are_VBR associated_VVN to_II performance_NN1 benchmarks_NN2 requiring_VVG value-continuous_JJ reward_NN1 systems_NN2 where_RRQ payment_NN1 doubtless_RR belongs_VVZ to_II ._. 
</s>
<s>
Summing_VVG up_RP ,_, since_II satisfying_VVG both_DB2 requirements_NN2 (_( Valance_NN1 and_CC Expectancy_NN1 )_) money_NN1 is_VBZ concerning_VVG to_II Vrooms_NP1 Theory_NN1 indeed_RR a_AT1 powerful_JJ and_CC widely_RR accepted_JJ tool_NN1 of_IO motivation_NN1 ._. 
</s>
<s>
Adams_NP1 Equity_NN1 Theory_NN1 :_: Human_JJ beings_NN2 tend_VV0 to_TO compare_VVI themselves_PPX2 to_II people_NN of_IO their_APPGE closer_JJR business_NN1 environment_NN1 and_CC evaluate_VV0 whether_CSW being_VBG treated_VVN adequate_JJ and_CC equally_RR ._. 
</s>
<s>
Therefore_RR someone_PN1 values_VVZ beside_II her_PPHO1 or_CC his_APPGE own_DA input_NN1 ,_, education_NN1 or_CC expertise_NN1 knowledge_NN1 and_CC achieved_VVN output_NN1 (_( salary_NN1 ,_, bonuses_NN2 ,_, privileges_NN2 )_) also_RR those_DD2 from_II their_APPGE closer_JJR surroundings_NN2 working_VVG in_II the_AT same_DA field_NN1 or_CC holding_VVG a_AT1 similar_JJ position_NN1 ._. 
</s>
<s>
If_CS the_AT individual_NN1 comes_VVZ to_II the_AT conclusion_NN1 that_CST their_APPGE peers_NN2 receive_VV0 higher_JJR rewards_NN2 in_II comparison_NN1 to_II their_APPGE input_NN1 tension_NN1 reducing_VVG motivation_NN1 results_NN2 ._. 
</s>
<s>
On_II the_AT opposite_JJ ,_, the_AT feeling_NN1 of_IO being_VBG over_II rewarded_JJ raises_VVZ employees_NN2 motivation_NN1 ._. 
</s>
<s>
Due_II21 to_II22 the_AT fact_NN1 ,_, that_CST individuals_NN2 build_VV0 up_RP their_APPGE conclusions_NN2 mainly_RR on_II subjective_JJ observations_NN2 both_DB2 deviations_NN2 are_VBR not_XX valued_VVN in_II the_AT same_DA way_NN1 causing_VVG that_DD1 decrease_NN1 of_IO motivation_NN1 by_II feeling_VVG under_II rewarded_JJ (_( earning_VVG a_AT1 certain_JJ amount_NN1 less_RRR the_AT average_NN1 )_) is_VBZ higher_JJR than_CSN the_AT increase_NN1 in_II motivation_NN1 gained_VVN by_II being_VBG over_II rewarded_JJ (_( same_DA amount_NN1 over_II the_AT average_NN1 )_) ._. 
</s>
<s>
These_DD2 observations_NN2 are_VBR similar_JJ to_II Perception_NN1 and_CC Attribution_NN1 Theory_NN1 pointing_VVG out_RP that_CST on_II the_AT one_MC1 hand_NN1 human_JJ beings_NN2 tend_VV0 to_TO explain_VVI failures_NN2 and_CC deviations_NN2 of_IO goals_NN2 by_II external_JJ reason_NN1 ,_, but_CCB on_II the_AT other_JJ hand_NN1 gladly_RR explain_VV0 success_NN1 by_II highlighting_VVG their_APPGE own_DA strengths_NN2 ._. 
</s>
<s>
In_RR21 brief_RR22 ,_, we_PPIS2 mostly_RR unwillingly_RR accept_VV0 that_CST certain_JJ inequity_NN1 is_VBZ caused_VVN by_II our_APPGE own_DA behavior_NN1 ,_, when_CS we_PPIS2 feel_VV0 ourselves_PPX2 under_RP rewarded_VVD resulting_VVG in_II lower_JJR motivation_NN1 ._. 
</s>
<s>
(_( Rollinson_NP1 2008:121,233-234_MCMC )_) Employees_NN2 value_VV0 their_APPGE and_CC the_AT input_NN1 of_IO their_APPGE peers_NN2 based_VVN on_II subjective_JJ observation_NN1 and_CC their_APPGE individual_JJ perception_NN1 but_CCB compare_VV0 their_APPGE output_NN1 by_II objective_JJ figures_NN2 of_IO pay_NN1 tickets_NN2 causing_VVG distortion_NN1 in_II their_APPGE conclusions_NN2 ._. 
</s>
<s>
A_AT1 clear_JJ compensation_NN1 system_NN1 helps_VVZ to_TO reduce_VVI subjectivity_NN1 in_BCL21 order_BCL22 to_TO point_VVI out_RP salary_NN1 deviations_NN2 plausible_JJ and_CC understandable_JJ for_IF both_DB2 sides_NN2 :_: employees_NN2 and_CC management_NN1 ._. 
</s>
<s>
Therefore_RR ,_, as_CSA above_RL mentioned_VVN (_( see_VV0 Adams_NP1 Equity_NN1 Theory_NN1 )_) ,_, a_AT1 money_NN1 based_VVN reward_NN1 system_NN1 (_( as_CSA nowadays_RT everywhere_RL introduced_VVN )_) providing_VVG benchmarks_NN2 and_CC performance_NN1 orientated_VVN feedback_NN1 is_VBZ widely_RR accepted_VVN and_CC highlights_VVZ the_AT role_NN1 of_IO salary_NN1 ._. 
</s>
<s>
Effects_NN2 of_IO cultural_JJ differences_NN2 on_II money_NN1 as_II a_AT1 Motivator_NN1 :_: In_II this_DD1 chapter_NN1 I_PPIS1 would_VM like_VVI to_TO point_VVI out_RP cultural_JJ differences_NN2 on_II how_RRQ money_NN1 is_VBZ seen_VVN as_II a_AT1 motivator_NN1 based_VVN on_II Adler_NP1 N._NP1 (_( Orgnizational_NP1 behaviour_NN1 ,_, Chapter1_FO ,_, 2_MC &;_NULL 5_MC )_) ._. 
</s>
<s>
Approximately_RR 700_MC words_NN2 Conclusion_NN1 
</s>
