<s>
Foreign_JJ Direct_JJ Investments_NN2 and_CC Emerging_JJ Markets_NN2 in_II Academic_JJ literature_NN1 Introduction_NN1 Today_RT internationalization_NN1 relates_VVZ in_II one_MC1 way_NN1 or_CC another_DD1 to_II the_AT lives_NN2 of_IO most_DAT people_NN ._. 
</s>
<s>
A_ZZ1 MNC_NP1 (_( Multinational_NP1 Corporation_NN1 )_) that_CST opens_VVZ ,_, e.g._REX a_AT1 new_JJ supermarket_NN1 ,_, will_VM affect_VVI the_AT people_NN in_II its_APPGE vicinity_NN1 ,_, whether_CSW those_DD2 people_NN choose_VV0 to_TO buy_VVI their_APPGE groceries_NN2 there_RL or_CC not_XX ._. 
</s>
<s>
Internationalization_NN1 is_VBZ well_RR covered_VVN in_II academic_JJ literature_NN1 as_RR21 well_RR22 ,_, and_CC has_VHZ been_VBN so_RR since_CS the_AT 1960s_MC2 with_IW the_AT increase_NN1 in_II FDIs_NP1 (_( foreign_JJ direct_JJ investments_NN2 )_) ._. 
</s>
<s>
In_II itself_PPX1 internationalization_NN1 is_VBZ a_AT1 broad_JJ topic_NN1 and_CC involves_VVZ issues_NN2 such_II21 as_II22 cultural_JJ tensions_NN2 ,_, choice_NN1 of_IO entry_NN1 mode_NN1 ,_, financing_VVG ,_, and_CC strategy_NN1 issues_NN2 ._. 
</s>
<s>
Entry_NN1 mode_NN1 refers_VVZ to_II how_RRQ the_AT company_NN1 chooses_VVZ to_TO establish_VVI itself_PPX1 in_II a_AT1 new_JJ market_NN1 (_( make_VV0 its_APPGE own_DA direct_JJ investment_NN1 or_CC enter_VV0 the_AT market_NN1 with/through_FU another_DD1 company_NN1 )_) (_( Dikova_NP1 &;_NULL van_NP1 Witteloostuijn_NP1 :_: 2007:1013_MC )_) ._. 
</s>
<s>
In_II this_DD1 study_NN1 these_DD2 foreign_JJ investments_NN2 are_VBR one_MC1 of_IO the_AT main_JJ object_NN1 of_IO interest_NN1 ._. 
</s>
<s>
Another_DD1 term_NN1 that_CST has_VHZ been_VBN the_AT object_NN1 of_IO wide_JJ discussion_NN1 is_VBZ emerging_JJ markets_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ speculated_VVN that_CST these_DD2 countries_NN2 will_VM have_VHI an_AT1 important_JJ role_NN1 in_II overcoming_VVG the_AT global_JJ economic_JJ crisis_NN1 ._. 
</s>
<s>
However_RR ,_, most_DAT of_IO the_AT literature_NN1 concerning_II foreign_JJ investments_NN2 is_VBZ about_II multinational_JJ corporations_NN2 (_( MNC_NP1 )_) from_II the_AT developed_JJ countries_NN2 (_( Bhaumik_NP1 &Gelb;_NULL 2005:7_MC )_) ._. 
</s>
<s>
Recently_RR also_RR a_AT1 number_NN1 of_IO studies_NN2 have_VH0 been_VBN made_VVN about_II developing_JJ country_NN1 MNCs_NP1 FDIs_NP1 (_( Meyer_NP1 ?_? ?_? )_) ._. 
</s>
<s>
Also_RR C.K_NP1 ._. 
</s>
<s>
Prahalahad_NN1 introduces_VVZ ,_, in_II his_APPGE book_NN1 The_AT Fortune_NN1 at_II the_AT Bottom_NN1 of_IO the_AT Pyramid_NN1 :_: Eradicating_NP1 Poverty_NN1 Through_II Profits_NN2 ,_, a_AT1 new_JJ way_NN1 of_IO viewing_VVG the_AT poor_JJ people_NN in_II developing_JJ countries_NN2 ._. 
</s>
<s>
This_DD1 encouraged_VVD a_AT1 few_DA2 other_JJ researchers_NN2 to_TO take_VVI a_AT1 closer_JJR look_NN1 at_II the_AT potential_NN1 at_II the_AT bottom_NN1 of_IO the_AT pyramid_NN1 ._. 
</s>
<s>
Although_CS there_EX is_VBZ much_DA1 talk_NN1 about_II both_DB2 foreign_JJ investments_NN2 and_CC the_AT emerging_JJ markets_NN2 ,_, they_PPHS2 have_VH0 not_XX received_VVN great_JJ coverage_NN1 in_II the_AT academic_JJ literature_NN1 ._. 
</s>
<s>
Neither_DD1 is_VBZ there_EX a_AT1 specific_JJ framework_NN1 for_IF foreign_JJ investments_NN2 and_CC the_AT emerging_JJ markets_NN2 ._. 
</s>
<s>
Since_CS FDIs_NP1 and_CC emerging_JJ markets_NN2 are_VBR such_DA central_JJ topics_NN2 it_PPH1 is_VBZ important_JJ to_TO have_VHI an_AT1 understanding_NN1 of_IO where_RRQ the_AT literature_NN1 is_VBZ right_RR now_RT ._. 
</s>
<s>
Literature_NN1 reviews_NN2 have_VH0 been_VBN done_VDN ,_, mainly_RR focusing_VVG on_II one_MC1 specific_JJ market_NN1 ,_, e.g._REX China_NP1 ._. 
</s>
<s>
Therefore_RR ,_, in_II this_DD1 study_NN1 I_PPIS1 will_VM map_VVI the_AT articles_NN2 about_II FDIs_NP1 to/from_II emerging_JJ markets_NN2 (_( in_RR21 general_RR22 )_) from_II 2005_MC until_II now_RT in_II five_MC top_JJ academic_JJ journals_NN2 (_( Academy_NN1 of_IO Management_NN1 Journal_NN1 ,_, Academy_NN1 of_IO Management_NN1 Review_NN1 ,_, Administrative_JJ Science_NN1 Quarterly_NN1 ,_, Journal_NN1 of_IO International_JJ Business_NN1 ,_, and_CC Strategic_JJ Management_NN1 Journal_NN1 )_) ._. 
</s>
<s>
Has_VHZ the_AT amount_NN1 of_IO literature_NN1 about_II foreign_JJ investments_NN2 and_CC emerging_JJ markets_NN2 increased_VVN during_II the_AT previous_JJ 10_MC years_NNT2 ?_? 
</s>
<s>
Definitions_NN2 Foreign_JJ investments_NN2 Emerging_VVG markets_NN2 (_( vs._II developing_JJ countries_NN2 )_) Structure_NN1 Next_MD literature_NN1 from_II the_AT studied_JJ time_NNT1 period_NN1 will_VM be_VBI presented_VVN ._. 
</s>
<s>
The_AT structure_NN1 of_IO the_AT study_NN1 will_VM be_VBI the_AT following_JJ :_: First_MD the_AT relevant_JJ literature_NN1 will_VM be_VBI presented_VVN ,_, to_TO be_VBI followed_VVN by_II the_AT methodology_NN1 ._. 
</s>
<s>
Then_RT the_AT results_NN2 will_VM be_VBI presented_VVN and_CC analyzed_VVN ._. 
</s>
<s>
Finally_RR conclusions_NN2 and_CC implications_NN2 will_VM be_VBI discussed_VVN at_II the_AT end_NN1 ._. 
</s>
<s>
Getting_VVG familiar_JJ with_IW what_DDQ has_VHZ been_VBN written_VVN A_AT1 search_NN1 in_II the_AT database_NN1 Web_NN1 of_IO Science_NN1 for_IF article_NN1 written_VVN about_II emerging_JJ markets_NN2 and_CC international*_FO comes_VVZ up_RP with_IW approximately_RR 900_MC hits_NN2 ._. 
</s>
<s>
The_AT most_RGT cited_JJ articles_NN2 are_VBR mainly_RR about_II economic_JJ factors_NN2 which_DDQ affect_VV0 the_AT business_NN1 environment_NN1 ._. 
</s>
<s>
The_AT articles_NN2 tend_VV0 to_TO have_VHI a_AT1 focus_NN1 on_II determining_VVG the_AT stability_NN1 of_IO the_AT market_NN1 ._. 
</s>
<s>
Less_RRR has_VHZ been_VBN written_VVN about_II investments_NN2 to/from_II these_DD2 markets_NN2 from_II a_AT1 strategic_JJ ,_, organizational_JJ perspective_NN1 ._. 
</s>
<s>
&lsqb;_( Next_MD I_PPIS1 will_VM discuss_VVI what_DDQ advancements_NN2 have_VH0 been_VBN made_VVN during_II 2001-2011_MCMC ,_, the_AT time_NNT1 period_NN1 that_CST is_VBZ studied_VVN ._. 
</s>
<s>
This_DD1 part_NN1 will_VM also_RR include_VVI articles_NN2 that_CST have_VH0 been_VBN published_VVN in_II other_JJ journals_NN2 besides_II the_AT one_PN1 studied_VVN &rsqb;_) Material_NN1 This_DD1 study_NN1 is_VBZ based_VVN on_II the_AT articles_NN2 in_II the_AT Journal_NN1 of_IO International_JJ Business_NN1 Studies_NN2 (_( JIBS_NN2 )_) .This_NNU journal_NN1 was_VBDZ chosen_VVN because_CS it_PPH1 is_VBZ the_AT highest_JJT ranked_JJ journal_NN1 in_II the_AT field_NN1 of_IO international_JJ business_NN1 (_( The_AT Association_NN1 of_IO Business_NN1 Schools_NN2 ,_, 2009_MC )_) ._. 
</s>
<s>
The_AT articles_NN2 in_II all_DB issues_NN2 from_II the_AT years_NNT2 2001_MC and_CC 2011_MC will_VM constitute_VVI the_AT material_NN1 of_IO the_AT study_NN1 ._. 
</s>
<s>
The_AT subjects_NN2 of_IO these_DD2 articles_NN2 have_VH0 been_VBN studied_VVN to_TO determine_VVI how_RGQ much_DA1 was_VBDZ written_VVN about_II foreign_JJ investments_NN2 and_CC emerging_JJ markets_NN2 (_( developing_JJ countries_NN2 was_VBDZ not_XX counted_VVN as_II a_AT1 synonym_NN1 for_IF the_AT second_MD term_NN1 )_) ._. 
</s>
<s>
The_AT material_NN1 is_VBZ made_VVN up_RP of_IO 54_MC articles_NN2 from_II the_AT year_NNT1 2001_MC and_CC 48_MC articles_NN2 from_II the_AT year_NNT1 2011_MC ._. 
</s>
<s>
These_DD2 years_NNT2 were_VBDR chosen_VVN for_IF the_AT study_NN1 since_CS neither_DD1 one_PN1 contains_VVZ a_AT1 special_JJ issue_NN1 about_II the_AT topics_NN2 of_IO interest_NN1 ._. 
</s>
<s>
There_EX are_VBR certain_JJ limitations_NN2 to_II the_AT study_NN1 pertaining_II21 to_II22 the_AT material_NN1 ._. 
</s>
<s>
Since_CS the_AT business_NN1 world_NN1 is_VBZ international_JJ ,_, the_AT JIBS_NN2 is_VBZ not_XX the_AT only_JJ academic_JJ journal_NN1 with_IW articles_NN2 about_II either_RR foreign_JJ investments_NN2 or_CC emerging_JJ markets_NN2 ._. 
</s>
<s>
Articles_NN2 about_II the_AT subjects_NN2 have_VH0 been_VBN published_VVN in_II many_DA2 other_JJ journals_NN2 as_RR21 well_RR22 ._. 
</s>
<s>
Second_NNT1 this_DD1 study_NN1 was_VBDZ limited_VVN to_II the_AT content_NN1 of_IO subject_NN1 words_NN2 ._. 
</s>
<s>
Therefore_RR at_RR21 least_RR22 one_MC1 article_NN1 about_II emerging_JJ markets_NN2 was_VBDZ not_XX reported_VVN because_CS emerging_JJ markets_NN2 was_VBDZ not_XX mentioned_VVN in_II the_AT subject_NN1 field_NN1 ._. 
</s>
<s>
Results_NN2 The_AT result_NN1 is_VBZ that_CST from_II the_AT entire_JJ sample_NN1 only_RR two_MC articles_NN2 contained_VVD the_AT term_NN1 emerging_VVG markets_NN2 in_II their_APPGE subject_NN1 field_NN1 (_( see_VV0 EmergingMarket_VV0 below_RL )_) ._. 
</s>
<s>
One_MC1 of_IO these_DD2 articles_NN2 was_VBDZ from_II the_AT year_NNT1 2001_MC and_CC the_AT other_JJ from_II 2011_MC ._. 
</s>
<s>
In_II the_AT case_NN1 of_IO the_AT term_NN1 foreign_JJ investment_NN1 the_AT total_JJ amount_NN1 of_IO articles_NN2 was_VBDZ 10_MC ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) In_II the_AT case_NN1 of_IO articles_NN2 containing_VVG both_DB2 of_IO the_AT terms_NN2 ,_, only_RR one_PN1 was_VBDZ found_VVN ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) Besides_II these_DD2 previous_JJ results_NN2 26_MC articles_NN2 mentioned_VVD a_AT1 country_NN1 in_II the_AT subject_NN1 field_NN1 ._. 
</s>
<s>
These_DD2 countries_NN2 included_VVD also_RR developed_JJ countries_NN2 ._. 
</s>
<s>
&lsqb;_( no_AT significant_JJ increase_NN1 in_II the_AT number_NN1 of_IO articles_NN2 written_VVN about_II the_AT topics_NN2 &rsqb;_) Discussion_NN1 Conclusions_NN2 
</s>
