<s>
Factors_NN2 behind_II customer_NN1 loyalty_NN1 :_: A_AT1 study_NN1 in_II the_AT Finnish_JJ food_NN1 retail_JJ market_NN1 1_MC1 Introduction_NN1 In_II recent_JJ years_NNT2 ,_, there_EX has_VHZ been_VBN wide_JJ interest_NN1 in_II relationship_NN1 marketing_NN1 ._. 
</s>
<s>
The_AT goods_NN2 marketing_NN1 logic_NN1 has_VHZ been_VBN moving_VVG more_RRR and_CC more_RRR towards_II the_AT service_NN1 dominant_JJ logic_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ generally_RR accepted_VVN that_CST companies_NN2 should_VM focus_VVI on_II creating_VVG customer_NN1 relationships_NN2 in_BCL21 order_BCL22 to_TO gain_VVI competitive_JJ advantage_NN1 ._. 
</s>
<s>
To_TO be_VBI profitable_JJ ,_, companies_NN2 should_VM focus_VVI on_II the_AT whole_JJ purchase_NN1 process_NN1 ,_, both_RR before_II the_AT point_NN1 of_IO purchase_NN1 and_CC after_CS the_AT point_NN1 of_IO purchase_NN1 ._. 
</s>
<s>
The_AT dominant_JJ logic_NN1 is_VBZ moving_VVG away_II21 from_II22 the_AT product_NN1 itself_PPX1 ,_, and_CC focusing_VVG more_RRR on_II the_AT process_NN1 the_AT product_NN1 leads_VVZ to_TO ._. 
</s>
<s>
Relationships_NN2 and_CC services_NN2 are_VBR becoming_VVG more_RRR and_CC more_RGR important_JJ in_II value_NN1 creation_NN1 processes_NN2 ._. 
</s>
<s>
It_PPH1 has_VHZ been_VBN claimed_VVN that_CST the_AT costs_NN2 of_IO maintaining_VVG relationships_NN2 with_IW existing_JJ customers_NN2 are_VBR less_RGR expensive_JJ than_CSN the_AT costs_NN2 of_IO getting_VVG new_JJ customers_NN2 ._. 
</s>
<s>
(_( Hill_NP1 &;_NULL Alexander_NP1 ,_, 2006_MC )_) ._. 
</s>
<s>
Grnroos_NN2 (_( 2007_MC )_) customer_NN1 relationship_NN1 lifecycle_NN1 model_NN1 focuses_VVZ on_II three_MC stages_NN2 in_BCL21 order_BCL22 to_TO get_VVI and_CC maintain_VVI customer_NN1 relationships_NN2 ._. 
</s>
<s>
In_II the_AT initial_JJ stage_NN1 the_AT customer_NN1 might_VM not_XX have_VHI used_VVN the_AT company_NN1 before_RT ._. 
</s>
<s>
Through_II different_JJ marketing_NN1 actions_NN2 ,_, the_AT company_NN1 can_VM persuade_VVI the_AT customer_NN1 to_TO come_VVI to_II the_AT company_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ the_AT first_MD step_NN1 in_II creating_VVG a_AT1 relationship_NN1 ._. 
</s>
<s>
In_II the_AT second_MD step_NN1 ,_, the_AT purchasing_NN1 process_NN1 ,_, the_AT companies_NN2 must_VM satisfy_VVI the_AT customer_NN1 in_BCL21 order_BCL22 to_TO be_VBI chosen_VVN ._. 
</s>
<s>
The_AT expectations_NN2 must_VM be_VBI met_VVN by_II the_AT experience_NN1 (_( Parasuraman_NP1 et_NP1 ._. 
</s>
<s>
al_NP1 ,_, 1985_MC ;_; Grnroos_NP1 ,_, 1988_MC )_) ._. 
</s>
<s>
Interactions_NN2 are_VBR important_JJ and_CC all_DB of_IO the_AT employees_NN2 should_VM be_VBI seen_VVN as_CSA part-time_JJ marketers_NN2 ._. 
</s>
<s>
(_( Gummesson_NN1 ,_, 1991_MC )_) The_AT companies_NN2 should_VM give_VVI what_DDQ the_AT customer_NN1 wants_VVZ and_CC make_VVI future_JJ promises_NN2 about_II the_AT product/service_NN1 ._. 
</s>
<s>
The_AT last_MD stage_NN1 ,_, the_AT consumption_NN1 process_NN1 ,_, is_VBZ the_AT most_RGT important_JJ stage_NN1 from_II a_AT1 relationship_NN1 building_NN1 point_NN1 of_IO view_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ in_II this_DD1 stage_NN1 loyalty_NN1 and_CC emotional_JJ bonds_NN2 are_VBR built_VVN and_CC will_VM prevent_VVI the_AT customer_NN1 to_TO leave_VVI the_AT company_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ hence_RR very_RG important_JJ that_CST the_AT relationship_NN1 should_VM be_VBI managed_VVN also_RR after_II the_AT purchase_NN1 ._. 
</s>
<s>
(_( e.g._REX Grnroos_NP1 ,_, 2007_MC )_) Although_CS this_DD1 theory_NN1 makes_VVZ a_AT1 lot_NN1 of_IO sense_NN1 ,_, it_PPH1 does_VDZ not_XX give_VVI any_DD real_JJ life_NN1 data_NN to_TO show_VVI what_DDQ kind_NN1 of_IO actions_NN2 are_VBR actually_RR taking_VVG place_NN1 in_II the_AT last_MD stage_NN1 of_IO the_AT relationship_NN1 cycle_NN1 ._. 
</s>
<s>
Furthermore_RR ,_, it_PPH1 is_VBZ not_XX evident_JJ that_CST other_JJ unknown_JJ and_CC maybe_RR unrelated_JJ factors_NN2 in_II other_JJ stages_NN2 of_IO the_AT consumer_NN1 relationship_NN1 lifecycle_NN1 could_VM not_XX affect_VVI the_AT consumer_NN1 relationships_NN2 ._. 
</s>
<s>
Loyalty_NN1 might_VM not_XX be_VBI built_VVN as_II the_AT customer_NN1 lifecycle_NN1 model_NN1 claims_VVZ in_II all_DB situations_NN2 ._. 
</s>
<s>
Some_DD theories_NN2 claim_VV0 that_CST people_NN are_VBR loyal_JJ to_II companies_NN2 simply_RR because_CS it_PPH1 is_VBZ easier_JJR than_CSN to_TO switch_VVI to_II another_DD1 company_NN1 ._. 
</s>
<s>
Information_NN1 seeking_VVG ,_, analyzing_VVG ,_, testing_NN1 etc._RA take_VV0 a_AT1 lot_NN1 of_IO unnecessary_JJ time_NNT1 from_II the_AT customers_NN2 in_II these_DD2 cases_NN2 ._. 
</s>
<s>
The_AT questions_NN2 hence_RR remains_VVZ ,_, what_DDQ kind_NN1 of_IO actions_NN2 are_VBR taking_VVG place_NN1 in_II the_AT consumption_NN1 process_NN1 ?_? 
</s>
<s>
Are_VBR these_DD2 actions_NN2 actually_RR affecting_VVG the_AT loyalty_NN1 ?_? 
</s>
<s>
Can_VM there_EX be_VBI other_JJ factors_NN2 affecting_VVG the_AT consumer_NN1 loyalty_NN1 unrelated_JJ to_II company_NN1 actions_NN2 made_VVN in_II the_AT consumption_NN1 process_NN1 ?_? 1.1_MC Aim_VV0 This_DD1 paper_NN1 will_VM focus_VVI on_II customer_NN1 loyalty_NN1 and_CC factors_NN2 behind_II the_AT loyalty_NN1 ._. 
</s>
<s>
Because_II21 of_II22 limited_JJ resources_NN2 ,_, this_DD1 paper_NN1 will_VM only_RR focus_VVI on_II customer_NN1 loyalty_NN1 in_II the_AT two_MC biggest_JJT food_NN1 retail_JJ chains_NN2 in_II Finland_NP1 ._. 
</s>
<s>
The_AT research_NN1 questions_NN2 that_CST will_VM be_VBI answered_VVN is_VBZ ;_; -Which_DDQ factors_NN2 can_VM affect_VVI the_AT consumer_NN1 loyalty_NN1 ?_? 
</s>
<s>
By_II answering_VVG this_DD1 question_NN1 ,_, real_JJ life_NN1 actions_NN2 in_II the_AT consumption_NN1 process_NN1 and_CC possible_JJ other_JJ actions_NN2 in_II other_JJ stages_NN2 will_VM be_VBI analyzed_VVN ._. 
</s>
<s>
It_PPH1 is_VBZ important_JJ to_TO realize_VVI that_CST this_DD1 paper_NN1 only_RR aim_VV0 to_TO find_VVI some_DD factors_NN2 that_CST can_VM affect_VVI the_AT customer_NN1 loyalty_NN1 ._. 
</s>
<s>
Not_XX all_DB of_IO the_AT possible_JJ factors_NN2 will_VM be_VBI analyzed_VVN ._. 
</s>
<s>
(_( The_AT result_NN1 showed_VVD many_DA2 interesting_JJ actions_NN2 ,_, some_DD of_IO them_PPHO2 not_XX recognized_VVN before_RT ,_, as_CS31 far_CS32 as_CS33 the_AT author_NN1 knows_VVZ at_II the_AT point_NN1 of_IO writing_NN1 ._. 
</s>
<s>
1.2_MC Structure_NN1 This_DD1 paper_NN1 will_VM start_VVI by_II a_AT1 theory_NN1 overview_NN1 ._. 
</s>
<s>
After_CS this_DD1 the_AT methodology_NN1 ,_, which_DDQ consists_VVZ of_IO four_MC in-_JJ depth_NN1 interviews_NN2 will_VM be_VBI presented_VVN ._. 
</s>
<s>
The_AT methodology_NN1 will_VM be_VBI followed_VVN by_II the_AT results_NN2 and_CC the_AT paper_NN1 will_VM end_VVI with_IW a_AT1 discussion_NN1 section_NN1 ._. 
</s>
<s>
2_MC Theory_NN1 overview_NN1 1.3_MC Introduction_NN1 1.4_MC Relationship_NN1 marketing_NN1 and_CC loyalty_NN1 1.5_MC Customer_NN1 lifecycle_NN1 1.6_MC The_AT Finnish_JJ food_NN1 retail_JJ market_NN1 1.7_MC Summary_NN1 and_CC specifying_VVG the_AT research_NN1 problem_NN1 3_MC Methodology_NN1 The_AT purpose_NN1 of_IO this_DD1 paper_NN1 is_VBZ to_TO research_VVI which_DDQ factors_NN2 can_VM affect_VVI customer_NN1 loyalty_NN1 ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO tackle_VVI this_DD1 research_NN1 problem_NN1 qualitative_JJ research_NN1 methods_NN2 will_VM be_VBI used_VVN ._. 
</s>
<s>
3.1_MC Choice_NN1 of_IO method_NN1 Since_CS the_AT wanted_JJ outcome_NN1 of_IO this_DD1 research_NN1 does_VDZ not_XX include_VVI any_DD numeric_JJ data_NN ,_, qualitative_JJ research_NN1 methods_NN2 are_VBR more_RGR suitable_JJ than_CSN quantitative_JJ research_NN1 methods_NN2 for_IF this_DD1 study_NN1 ._. 
</s>
<s>
(_( Saunders_NP1 ,_, Lewis_NP1 &;_NULL Thornhill_NP1 ,_, 2007_MC )_) Out_II21 of_II22 different_JJ qualitative_JJ research_NN1 method_NN1 options_NN2 in-depth_JJ interviews_NN2 have_VH0 been_VBN chosen_VVN as_II the_AT most_RGT suitable_JJ and_CC efficient_JJ method_NN1 for_IF this_DD1 study_NN1 ._. 
</s>
<s>
A_AT1 semi-structured_JJ interview_NN1 method_NN1 will_VM be_VBI used_VVN ._. 
</s>
<s>
One_MC1 question_NN1 might_VM lead_VVI to_II another_DD1 important_JJ question_NN1 which_DDQ will_VM not_XX be_VBI excluded_VVN only_RR based_VVN on_II the_AT interview_NN1 guide_NN1 ._. 
</s>
<s>
The_AT questions_NN2 are_VBR open_RR ended_VVN in_BCL21 order_BCL22 to_TO get_VVI as_RG much_DA1 information_NN1 as_CSA possible_JJ from_II the_AT respondent_NN1 by_II their_APPGE own_DA words_NN2 ._. 
</s>
<s>
The_AT interviews_NN2 will_VM be_VBI recorded_VVN ._. 
</s>
<s>
The_AT interview_NN1 guide_NN1 can_VM be_VBI found_VVN as_CSA attachment_NN1 1_MC1 ._. 
</s>
<s>
3.2_MC Respondents_NN2 According_II21 to_II22 Saunders_NP1 ,_, Lewis_NP1 &;_NULL Thornhill_NP1 ,_, 2007_MC ,_, there_EX are_VBR no_AT specific_JJ rules_NN2 of_IO how_RGQ many_DA2 the_AT respondents_NN2 should_VM be_VBI when_CS using_VVG in-depth_JJ interviews_NN2 as_II a_AT1 method_NN1 ._. 
</s>
<s>
The_AT researcher_NN1 should_VM in_II these_DD2 cases_NN2 focus_VV0 on_II the_AT aim_NN1 on_II the_AT paper_NN1 and_CC what_DDQ can_VM optimally_RR be_VBI done_VDN with_IW the_AT scarce_JJ resources_NN2 ._. 
</s>
<s>
The_AT scarce_JJ resource_NN1 is_VBZ in_II this_DD1 case_NN1 is_VBZ the_AT limited_JJ time_NNT1 available_JJ ._. 
</s>
<s>
I_PPIS1 have_VH0 chosen_VVN to_TO interview_VVI four_MC persons_NN2 ._. 
</s>
<s>
The_AT persons_NN2 have_VH0 been_VBN unrandomly_RR chosen_VVN based_VVN on_II preinformation_NN1 of_IO their_APPGE food_NN1 retail_JJ chain_NN1 preferences_NN2 ._. 
</s>
<s>
Two_MC people_NN clearly_RR prefer_VV0 the_AT S-chain_NN1 and_CC two_MC people_NN clearly_RR prefer_VV0 the_AT K-chain_NN1 ._. 
</s>
<s>
By_II choosing_VVG loyal_JJ customers_NN2 from_II the_AT two_MC biggest_JJT food_NN1 retail_JJ chains_NN2 in_II Finland_NP1 ,_, the_AT study_NN1 will_VM get_VVI a_AT1 more_RGR diversified_JJ outcome_NN1 about_II which_DDQ factors_NN2 can_VM affect_VVI the_AT customer_NN1 loyalty_NN1 ,_, than_CSN it_PPH1 would_VM have_VHI got_VVN if_CS only_RR one_MC1 food_NN1 retail_JJ chain_NN1 was_VBDZ chosen_VVN ._. 
</s>
<s>
As_CSA stated_VVN in_II the_AT theory_NN1 section_NN1 of_IO this_DD1 paper_NN1 ,_, there_EX are_VBR only_RR two_MC main_JJ actors_NN2 on_II the_AT food_NN1 retail_JJ market_NN1 in_II Finland_NP1 ._. 
</s>
<s>
These_DD2 chains_NN2 were_VBDR chosen_VVN in_II this_DD1 study_NN1 because_II21 of_II22 their_APPGE similarities_NN2 in_II both_RR size_NN1 and_CC pricing_VVG strategy_NN1 ._. 
</s>
<s>
The_AT persons_NN2 chosen_VVN for_IF the_AT interviews_NN2 live_VV0 in_II the_AT capital_NN1 area_NN1 of_IO Finland_NP1 and_CC are_VBR likely_JJ to_TO be_VBI equally_RR targeted_VVN by_II marketing_NN1 actions_NN2 made_VVN by_II the_AT two_MC food_NN1 retail_JJ chains_NN2 ._. 
</s>
<s>
The_AT respondentinformation_NN1 is_VBZ summarized_VVN in_II Table_NN1 1_MC1 ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) 4_MC Results_NN2 5_MC Discussion_NN1 
</s>
