<s>
The_AT affect_NN1 of_IO cell_NN1 phone_NN1 design_NN1 on_II consumer_NN1 purchasing_NN1 behavior_NN1 1_MC1 Introduction_NN1 In_II today_RT 's_GE society_NN1 of_IO Finland_NP1 ,_, it_PPH1 is_VBZ uncommon_JJ to_TO find_VVI a_AT1 person_NN1 who_PNQS does_VDZ not_XX have_VHI a_AT1 cell_NN1 phone_NN1 ._. 
</s>
<s>
Consumers_NN2 have_VH0 a_AT1 cell_NN1 phone_NN1 and_CC they_PPHS2 might_VM even_RR have_VHI two_MC ._. 
</s>
<s>
Cell_NN1 phones_NN2 have_VH0 several_DA2 attributes_NN2 and_CC design_NN1 is_VBZ one_MC1 of_IO those_DD2 attributes_NN2 ._. 
</s>
<s>
Looking_VVG at_II the_AT almost_RR endless_JJ choices_NN2 of_IO cell_NN1 phones_NN2 ,_, there_EX is_VBZ bound_VVNK to_TO be_VBI one_PN1 that_CST matches_VVZ a_AT1 consumer_NN1 's_GE personal_JJ needs_NN2 ._. 
</s>
<s>
The_AT life-span_NN1 of_IO a_AT1 specific_JJ cell_NN1 phone_NN1 model_NN1 offered_VVN is_VBZ getting_VVG shorter_JJR and_CC a_AT1 cell_NN1 phone_NN1 is_VBZ traded_VVN to_II a_AT1 newer_JJR model_NN1 at_II a_AT1 faster_JJR rate_NN1 than_CSN before_RT ._. 
</s>
<s>
It_PPH1 seems_VVZ that_CST consumers_NN2 are_VBR now_RT making_VVG more_RGR purchasing_JJ decisions_NN2 concerning_II cell_NN1 phones_NN2 than_CSN had_VHD been_VBN done_VDN in_II the_AT past_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ therefore_RR relevant_JJ to_TO study_VVI on_II what_DDQ basis_NN1 these_DD2 purchasing_VVG decisions_NN2 are_VBR made_VVN ._. 
</s>
<s>
As_CSA mobile_JJ phone_NN1 companies_NN2 offer_VV0 more_DAR variety_NN1 and_CC choices_NN2 for_IF consumers_NN2 ,_, it_PPH1 is_VBZ worth_II investigating_VVG what_DDQ consumers_NN2 actually_RR value_VV0 highly_RR when_CS purchasing_VVG a_AT1 new_JJ cell_NN1 phone_NN1 in_BCL21 order_BCL22 to_TO improve_VVI the_AT current_JJ offering_NN1 available_JJ to_II consumers_NN2 ._. 
</s>
<s>
Consumer_NN1 behavior_NN1 and_CC purchasing_VVG behavior_NN1 have_VH0 been_VBN studied_VVN widely_RR ,_, and_CC companies_NN2 are_VBR striving_VVG to_TO obtain_VVI an_AT1 understanding_NN1 of_IO how_RRQ consumers_NN2 behave_VV0 and_CC which_DDQ factors_NN2 influence_VV0 their_APPGE behavior_NN1 ._. 
</s>
<s>
The_AT industry_NN1 of_IO mobile_JJ phones_NN2 has_VHZ also_RR been_VBN studied_VVN ;_; however_RR ,_, the_AT combination_NN1 of_IO consumer_NN1 purchasing_NN1 behavior_NN1 in_II31 regard_II32 to_II33 cell_NN1 phones_NN2 has_VHZ yet_RR to_TO be_VBI studied_VVN to_II a_AT1 larger_JJR extent_NN1 ._. 
</s>
<s>
As_CSA cell_NN1 phones_NN2 have_VH0 become_VVN a_AT1 central_JJ part_NN1 of_IO the_AT consumer_NN1 's_GE everyday_JJ life_NN1 ,_, there_EX is_VBZ a_AT1 gap_NN1 in_II research_NN1 that_CST needs_VVZ to_TO be_VBI filled_VVN ._. 
</s>
<s>
By_II combining_VVG previous_JJ research_NN1 with_IW the_AT investigation_NN1 done_VDN in_II this_DD1 paper_NN1 ,_, this_DD1 gap_NN1 can_VM ,_, to_II an_AT1 extent_NN1 ,_, be_VBI filled_VVN ._. 
</s>
<s>
As_CSA cell_NN1 phones_NN2 are_VBR often_RR offered_VVN in_II a_AT1 variety_NN1 of_IO colors_NN2 and_CC the_AT design_NN1 of_IO the_AT phone_NN1 varies_VVZ ,_, the_AT question_NN1 is_VBZ :_: do_VD0 consumers_NN2 value_NN1 design_NN1 highly_RR when_CS purchasing_VVG a_AT1 cell_NN1 phone_NN1 ,_, or_CC do_VD0 the_AT other_JJ attributes_NN2 play_VV0 a_AT1 larger_JJR role_NN1 ?_? 
</s>
<s>
For_IF some_DD consumers_NN2 it_PPH1 might_VM even_RR be_VBI a_AT1 question_NN1 if_CS the_AT design_NN1 of_IO a_AT1 cell_NN1 phone_NN1 has_VHZ any_DD effect_NN1 on_II consumer_NN1 purchasing_NN1 behavior_NN1 at_RR21 all_RR22 ._. 
</s>
<s>
Therefore_RR the_AT main_JJ purpose_NN1 of_IO this_DD1 paper_NN1 is_VBZ to_TO investigate_VVI to_II what_DDQ extent_NN1 the_AT design_NN1 of_IO a_AT1 cell_NN1 phone_NN1 affects_VVZ the_AT purchasing_NN1 behavior_NN1 of_IO consumers._NNU 1.1_MC Aim_NN1 of_IO the_AT study_NN1 The_AT main_JJ purpose_NN1 of_IO this_DD1 paper_NN1 is_VBZ to_TO investigate_VVI to_II what_DDQ extent_NN1 the_AT design_NN1 of_IO a_AT1 cell_NN1 phone_NN1 affects_VVZ the_AT purchasing_NN1 behavior_NN1 of_IO young_JJ consumers._NNU 1.2_MC Structure_NN1 of_IO the_AT paper_NN1 This_DD1 paper_NN1 is_VBZ structured_VVN in_II the_AT following_JJ way_NN1 :_: Section_NN1 two_MC reviews_VVZ the_AT current_JJ literature_NN1 concerning_II consumer_NN1 behavior_NN1 in_RR21 general_RR22 with_IW an_AT1 emphasis_NN1 on_II consumer_NN1 purchasing_NN1 behavior_NN1 and_CC decision_NN1 making_VVG ._. 
</s>
<s>
This_DD1 section_NN1 also_RR discusses_VVZ the_AT different_JJ attributes_NN2 that_CST a_AT1 cell_NN1 phone_NN1 can_VM have_VHI ,_, including_II a_AT1 further_JJR discussion_NN1 on_II cell_NN1 phone_NN1 design_NN1 ._. 
</s>
<s>
Chapter_NN1 three_MC introduces_VVZ the_AT empirical_JJ method_NN1 used_VVN for_IF the_AT investigation_NN1 part_NN1 of_IO the_AT paper_NN1 ._. 
</s>
<s>
This_DD1 section_NN1 includes_VVZ the_AT description_NN1 of_IO the_AT method_NN1 used_VVN in_II the_AT study_NN1 and_CC a_AT1 presentation_NN1 of_IO the_AT data_NN obtained_VVN ._. 
</s>
<s>
Chapter_NN1 four_MC focuses_VVZ on_II analyzing_VVG the_AT data_NN obtained_VVN and_CC what_DDQ can_VM be_VBI seen_VVN from_II the_AT data_NN ._. 
</s>
<s>
The_AT paper_NN1 ends_VVZ with_IW a_AT1 discussion_NN1 about_II the_AT results_NN2 and_CC the_AT managerial_JJ implications_NN2 of_IO these_DD2 results_NN2 ._. 
</s>
<s>
An_AT1 illustration_NN1 of_IO the_AT structure_NN1 of_IO the_AT paper_NN1 is_VBZ presented_VVN below_RL ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) 2_MC Background_NN1 (_( Not_XX complete_JJ !_! 
</s>
<s>
I_PPIS1 will_VM add_VVI some_DD more_DAR theory_NN1 from_II articles_NN2 ,_, when_CS I_PPIS1 find_VV0 good_JJ ones_NN2 )_) This_DD1 section_NN1 of_IO the_AT paper_NN1 discusses_VVZ the_AT background_NN1 and_CC theory_NN1 concerning_II the_AT relevant_JJ literature_NN1 in_RP regards_VVZ to_II the_AT aim_NN1 of_IO this_DD1 study_NN1 ._. 
</s>
<s>
The_AT first_MD section_NN1 strives_VVZ to_TO define_VVI consumer_NN1 behavior_NN1 ,_, with_IW a_AT1 sub-section_NN1 on_II consumer_NN1 purchasing_NN1 behavior_NN1 ._. 
</s>
<s>
The_AT second_MD part_NN1 of_IO this_DD1 chapter_NN1 looks_VVZ into_II cell_NN1 phone_NN1 design_NN1 and_CC discusses_VVZ a_AT1 sample_NN1 of_IO designs_NN2 that_CST are_VBR available_JJ ._. 
</s>
<s>
This_DD1 section_NN1 also_RR includes_VVZ a_AT1 description_NN1 of_IO what_DDQ different_JJ attributes_NN2 cell_NN1 phones_NN2 currently_RR on_II the_AT market_NN1 might_NN1 include._NNU 2.1_MC Consumer_NN1 behavior_NN1 In_II literature_NN1 behavior_NN1 is_VBZ defined_VVN as_CSA "_" the_AT physical_JJ actions_NN2 of_IO consumers_NN2 that_CST can_VM be_VBI directly_RR observed_VVN and_CC measured_VVN by_II others_NN2 "_" ,_, also_RR known_VVN as_II overt_JJ behavior_NN1 ._. 
</s>
<s>
(_( Peter_NP1 &;_NULL Olson_NP1 2008_MC :_: 23_MC )_) In_II other_JJ words_NN2 ,_, the_AT behavior_NN1 of_IO consumers_NN2 is_VBZ something_PN1 that_CST can_VM be_VBI observed_VVN by_II the_AT people_NN around_II them_PPHO2 and_CC data_NN can_VM be_VBI collected_VVN in_II that_DD1 way_NN1 ._. 
</s>
<s>
There_EX is_VBZ however_RR a_AT1 distinction_NN1 between_II behavior_NN1 that_CST can_VM be_VBI observed_VVN ,_, to_II behavior_NN1 that_CST can_VM not_XX be_VBI observed_VVN by_II other_JJ individuals_NN2 ._. 
</s>
<s>
Consumer_NN1 behavior_NN1 on_II the_AT other_JJ hand_NN1 is_VBZ "_" the_AT dynamic_JJ interaction_NN1 of_IO affect_NN1 and_CC cognition_NN1 ,_, behavior_NN1 ,_, and_CC environmental_JJ events_NN2 "_" ._. 
</s>
<s>
By_II affect_NN1 the_AT authors_NN2 refer_VV0 to_II the_AT "_" psychological_JJ response_NN1 that_CST involves_VVZ a_AT1 general_JJ positive/negative_JJ feeling_NN1 and_CC varying_JJ levels_NN2 of_IO activation_NN1 "_" ._. 
</s>
<s>
Cognition_NN1 is_VBZ "_" the_AT mental_JJ process_NN1 of_IO interpretation_NN1 and_CC integration_NN1 and_CC the_AT thoughts_NN2 and_CC meanings_NN2 they_PPHS2 produce_VV0 "_" ._. 
</s>
<s>
(_( Peter_NP1 &;_NULL Olson_NP1 2008_MC :_: 529-531_MCMC )_) For_IF this_DD1 paper_NN1 consumer_NN1 behavior_NN1 is_VBZ not_XX regarded_VVN as_CSA only_JJ something_PN1 that_CST can_VM be_VBI observed_VVN by_II simply_RR observing_VVG consumer_NN1 behavior_NN1 ._. 
</s>
<s>
This_DD1 study_NN1 therefore_RR also_RR considers_VVZ the_AT cognitive_JJ part_NN1 of_IO behavior_NN1 ,_, as_CSA they_PPHS2 are_VBR described_VVN by_II the_AT consumers_NN2 ,_, as_II part_NN1 of_IO what_DDQ is_VBZ meant_VVN by_II consumer_NN1 behavior._NNU 2.1.1_MC Consumer_NN1 purchasing_NN1 behavior_NN1 Purchasing_NN1 behavior_NN1 is_VBZ something_PN1 that_CST involves_VVZ the_AT consumer_NN1 making_VVG a_AT1 decision_NN1 about_II what_DDQ to_TO buy_VVI and_CC what_DDQ the_AT consumer_NN1 looks_VVZ for_IF in_II a_AT1 product_NN1 ._. 
</s>
<s>
Consumer_NN1 decision_NN1 making_NN1 is_VBZ defined_VVN as_CSA "_" the_AT cognitive_JJ processes_NN2 by_II which_DDQ consumers_NN2 interpret_VV0 product_NN1 information_NN1 and_CC integrate_VV0 that_DD1 knowledge_NN1 to_TO make_VVI choices_NN2 among_II alternatives_NN2 "_" ._. 
</s>
<s>
(_( Peter_NP1 &;_NULL Olson_NP1 2008_MC :_: 531_MC )_) What_DDQ the_AT consumer_NN1 then_RT does_VDZ in_II a_AT1 purchase_NN1 situation_NN1 is_VBZ to_II piece_NN1 together_RL the_AT gathered_JJ information_NN1 in_BCL21 order_BCL22 to_TO come_VVI to_II a_AT1 conclusion_NN1 as_II21 to_II22 which_DDQ product_NN1 is_VBZ the_AT most_RGT suited_JJ for_IF the_AT predefined_JJ purpose_NN1 ._. 
</s>
<s>
For_IF this_DD1 study_NN1 purchasing_NN1 behavior_NN1 involves_VVZ every_AT1 action_NN1 taken_VVN to_TO make_VVI the_AT decision_NN1 to_TO purchase_VVI ._. 
</s>
<s>
This_DD1 involves_VVZ the_AT identification_NN1 of_IO a_AT1 certain_JJ need_NN1 that_CST the_AT consumer_NN1 finds_VVZ needs_NN2 to_TO be_VBI filled_VVN ._. 
</s>
<s>
In_II this_DD1 case_NN1 ,_, the_AT identification_NN1 might_VM be_VBI that_CST the_AT consumer_NN1 needs_VVZ a_AT1 new_JJ cell_NN1 phone_NN1 because_CS the_AT old_JJ one_PN1 is_VBZ broken_VVN ,_, perhaps_RR outdated_JJ ,_, or_CC simply_RR that_CST the_AT consumer_NN1 finds_VVZ that_CST a_AT1 particular_JJ phone_NN1 is_VBZ something_PN1 that_CST the_AT consumer_NN1 "_" must_VM have_VHI "_" ._. 
</s>
<s>
The_AT consumer_NN1 might_VM then_RT look_VVI into_II the_AT different_JJ options_NN2 available_JJ on_II the_AT market_NN1 and_CC select_VV0 one_PN1 that_CST has_VHZ the_AT features_NN2 that_CST fulfill_VV0 the_AT requirements_NN2 the_AT consumer_NN1 has_VHZ ._. 
</s>
<s>
In_II this_DD1 paper_NN1 the_AT purchasing_NN1 behavior_NN1 of_IO consumers_NN2 is_VBZ considered_VVN to_TO be_VBI everything_PN1 that_CST leads_VVZ to_II the_AT consumer_NN1 buying_VVG the_AT cell_NN1 phone._NNU 2.2_MC Cell_NN1 phone_NN1 design_NN1 Nokia_NP1 currently_RR (_( 13.10.2010_MC )_) has_VHZ 74_MC different_JJ cell_NN1 phones_NN2 on_II the_AT market_NN1 ._. 
</s>
<s>
A_AT1 consumer_NN1 interested_JJ in_II buying_VVG a_AT1 phone_NN1 can_VM browse_VVI through_II the_AT different_JJ options_NN2 by_II choosing_VVG the_AT particular_JJ shape_NN1 or_CC shapes_NN2 the_AT consumer_NN1 wants_VVZ to_TO look_VVI at_II and_CC then_RT choose_VVI the_AT most_RGT important_JJ features_NN2 the_AT phone_NN1 needs_VVZ to_TO have_VHI ._. 
</s>
<s>
(_( Nokia_NP1 )_) When_CS considering_VVG the_AT various_JJ brands_NN2 that_CST offer_VV0 cell_NN1 phones_NN2 ,_, there_EX is_VBZ bound_VVNK to_TO be_VBI phone_NN1 that_CST matches_VVZ the_AT needs_NN2 of_IO consumers_NN2 ._. 
</s>
<s>
The_AT different_JJ shape_NN1 options_NN2 that_CST Nokia_NP1 offers_NN2 for_IF the_AT cell_NN1 phones_NN2 are_VBR traditional_JJ ,_, foldable_JJ ,_, slide_VV0 and_RR31 so_RR32 on_RR33 ._. 
</s>
<s>
The_AT consumer_NN1 can_VM then_RT rank_VVI the_AT most_RGT important_JJ features_NN2 that_CST the_AT cell_NN1 phone_NN1 has_VHZ to_TO have_VHI ._. 
</s>
<s>
These_DD2 features_NN2 include_VV0 Bluetooth_NP1 ,_, 3G_NNU ,_, internet_NN1 ,_, e-mail_NN1 ,_, radio_NN1 and_CC how_RGQ many_DA2 megapixels_NN2 the_AT camera_NN1 needs_VVZ to_TO at_RR21 least_RR22 be_VBI ._. 
</s>
<s>
After_II finding_VVG the_AT desired_JJ model_NN1 for_IF the_AT cell_NN1 phone_NN1 ,_, the_AT consumer_NN1 can_VM in_II most_DAT cases_NN2 chose_VVD between_II different_JJ colors_NN2 for_IF the_AT phone_NN1 ._. 
</s>
<s>
(_( Nokia_NP1 )_) A_ZZ1 selection_NN1 of_IO the_AT cell_NN1 phones_NN2 that_CST Nokia_NP1 offers_NN2 can_VM be_VBI found_VVN as_CSA Appendix_NN1 1_MC1 at_II the_AT end_NN1 of_IO the_AT paper._NNU 3_MC Empirical_JJ method_NN1 This_DD1 section_NN1 of_IO this_DD1 paper_NN1 begins_VVZ with_IW a_AT1 discussion_NN1 involving_VVG the_AT overall_JJ empirical_JJ method_NN1 chosen_VVN for_IF the_AT investigation_NN1 ._. 
</s>
<s>
After_CS that_DD1 there_EX is_VBZ a_AT1 sub-section_NN1 that_CST goes_VVZ through_II the_AT interview_NN1 questions_NN2 chosen_VVN ._. 
</s>
<s>
The_AT following_JJ two_MC sections_NN2 describe_VV0 the_AT choice_NN1 of_IO informants_NN2 and_CC the_AT data_NN collection_NN1 process_NN1 ._. 
</s>
<s>
The_AT last_MD part_NN1 of_IO this_DD1 chapter_NN1 describes_VVZ the_AT way_NN1 in_II which_DDQ the_AT data_NN is_VBZ analyzed._NNU 3.1_MC The_AT method_NN1 chosen_VVN for_IF this_DD1 study_NN1 In_BCL21 order_BCL22 to_TO answer_VVI the_AT aim_NN1 of_IO the_AT study_NN1 that_CST is_VBZ to_TO investigate_VVI to_II what_DDQ extent_NN1 the_AT design_NN1 of_IO a_AT1 cell_NN1 phone_NN1 affects_VVZ the_AT purchasing_NN1 behavior_NN1 of_IO young_JJ consumers_NN2 ,_, a_AT1 qualitative_JJ research_NN1 study_NN1 is_VBZ performed_VVN ._. 
</s>
<s>
A_AT1 qualitative_JJ research_NN1 method_NN1 was_VBDZ chosen_VVN here_RL because_CS it_PPH1 is_VBZ better_RRR suited_VVN to_II the_AT research_NN1 question_NN1 ._. 
</s>
<s>
As_II the_AT aim_NN1 is_VBZ to_TO investigate_VVI how_RRQ design_NN1 affects_VVZ purchasing_VVG behavior_NN1 and_CC why_RRQ ,_, it_PPH1 is_VBZ more_RGR suitable_JJ to_TO investigate_VVI this_DD1 qualitatively_RR ._. 
</s>
<s>
In_II a_AT1 quantitative_JJ investigation_NN1 ,_, the_AT data_NN is_VBZ numerical_JJ ,_, whereas_CS in_II a_AT1 qualitative_JJ investigation_NN1 the_AT data_NN is_VBZ non-numerical_JJ (_( words_NN2 )_) ._. 
</s>
<s>
When_CS considering_VVG the_AT aim_NN1 of_IO the_AT investigation_NN1 ,_, the_AT more_RGR suitable_JJ option_NN1 for_IF this_DD1 paper_NN1 is_VBZ a_AT1 qualitative_JJ investigation_NN1 ._. 
</s>
<s>
(_( Saunders_NP1 ,_, Lewis_NP1 &;_NULL Thornhill_NP1 2007_MC :_: 145_MC )_) The_AT type_NN1 of_IO qualitative_JJ investigation_NN1 method_NN1 for_IF this_DD1 paper_NN1 is_VBZ interviews_NN2 ._. 
</s>
<s>
Out_II21 of_II22 the_AT three_MC forms_NN2 of_IO interviews_NN2 ;_; structures_NN2 ,_, semi-structured_JJ and_CC open_JJ interviews_NN2 ,_, is_VBZ the_AT chosen_JJ interview_NN1 form_NN1 in_II this_DD1 case_NN1 semi-structured_VVN ._. 
</s>
<s>
This_DD1 is_VBZ because_CS structured_JJ interviews_NN2 are_VBR too_RG much_DA1 like_JJ questioners_NN2 and_CC limits_NN2 what_DDQ the_AT informant_NN1 can_VM contribute_VVI to_II the_AT data_NN ._. 
</s>
<s>
As_II21 for_II22 open_JJ interviews_NN2 ,_, this_DD1 interview_NN1 form_NN1 does_VDZ not_XX limit_VVI the_AT discussion_NN1 enough_RR to_TO make_VVI sure_JJ that_CST the_AT necessary_JJ data_NN is_VBZ obtained_VVN to_TO answer_VVI the_AT aim_NN1 ._. 
</s>
<s>
The_AT semi-structured_JJ interview_NN1 form_NN1 is_VBZ therefore_RR the_AT most_RGT suitable_JJ for_IF this_DD1 investigation_NN1 ,_, as_CSA it_PPH1 limits_VVZ the_AT discussion_NN1 somewhat_RR ,_, but_CCB does_VDZ not_XX exclude_VVI the_AT option_NN1 of_IO asking_VVG follow-up_JJ questions_NN2 regarding_II something_PN1 the_AT informant_NN1 has_VHZ brought_VVN up_RP ._. 
</s>
<s>
(_( Saunders_NP1 et_RA21 al_RA22 2007_MC :_: 312_MC )_) 3.1.1_MC Description_NN1 of_IO interview_NN1 questions_NN2 The_AT interview-guide_NN1 is_VBZ presented_VVN in_II Appendix_NN1 1_MC1 at_II the_AT end_NN1 of_IO this_DD1 paper_NN1 ._. 
</s>
<s>
The_AT interview_NN1 questions_NN2 are_VBR meant_VVN to_TO collect_VVI information_NN1 about_II the_AT informant_NN1 's_GE purchasing_NN1 behavior_NN1 regarding_II cell_NN1 phones_NN2 ._. 
</s>
<s>
The_AT first_MD questions_NN2 aim_VV0 to_TO find_VVI out_RP what_DDQ features_VVZ the_AT informant_NN1 's_GE current_JJ phone_NN1 possesses_VVZ and_CC what_DDQ features_NN2 are_VBR considered_VVN valuable_JJ ._. 
</s>
<s>
This_DD1 is_VBZ in_BCL21 order_BCL22 to_TO find_VVI out_RP what_DDQ the_AT informant_NN1 looks_VVZ at_II when_CS trying_VVG to_TO find_VVI the_AT most_RGT suitable_JJ phone_NN1 for_IF the_AT predefined_JJ purpose_NN1 ._. 
</s>
<s>
The_AT questions_NN2 following_VVG are_VBR there_RL to_TO find_VVI out_RP more_RRR about_II how_RRQ the_AT informant_NN1 acts_VVZ when_CS purchasing_VVG a_AT1 cell_NN1 phone_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ relevant_JJ to_TO know_VVI what_DDQ the_AT informant_NN1 looks_VVZ at_RR21 first_RR22 ,_, in_BCL21 order_BCL22 to_TO find_VVI out_RP if_CS design_NN1 is_VBZ one_MC1 of_IO the_AT main_JJ features_NN2 that_CST the_AT informant_NN1 finds_VVZ important._NNU 3.2_MC Choice_NN1 of_IO informants_NN2 The_AT choice_NN1 of_IO informants_NN2 for_IF this_DD1 investigation_NN1 is_VBZ done_VDN through_II convenience_NN1 sampling_NN1 ._. 
</s>
<s>
(_( Saunders_NP1 et_RA21 al_RA22 2003_MC :_: 234_MC )_) The_AT requirement_NN1 for_IF the_AT informants_NN2 is_VBZ to_TO be_VBI around_II their_APPGE 20_MC 's_GE and_CC had_VHD to_TO own_VVI a_AT1 cell_NN1 phone_NN1 ._. 
</s>
<s>
This_DD1 requirement_NN1 is_VBZ set_VVN in_BCL21 order_BCL22 to_TO define_VVI the_AT group_NN1 investigated_VVN and_CC to_TO get_VVI a_AT1 better_JJR picture_NN1 of_IO this_DD1 group_NN1 as_II a_AT1 whole_NN1 ._. 
</s>
<s>
The_AT number_NN1 of_IO informants_NN2 is_VBZ around_RG 5-10_MCMC individuals_NN2 (_( will_NN1 be_VBI confirmed_VVN later_RRR )_) and_CC this_DD1 is_VBZ seen_VVN as_RG enough_RR as_CSA answers_NN2 tend_VV0 to_TO start_VVI saturating_VVG after_II only_RR a_AT1 few_DA2 interviews_NN2 ._. 
</s>
<s>
As_II the_AT goal_NN1 of_IO a_AT1 qualitative_JJ study_NN1 is_VBZ not_XX to_TO draw_VVI conclusions_NN2 regarding_II the_AT whole_JJ group_NN1 of_IO young_JJ consumers_NN2 and_CC their_APPGE purchasing_NN1 behaviour_NN1 regarding_II cell_NN1 phones_NN2 ,_, it_PPH1 is_VBZ not_XX necessary_JJ to_TO have_VHI a_AT1 large_JJ number_NN1 of_IO informants._NNU 3.2.1_MC Data_NN collection_NN1 (_( Description_NN1 of_IO what_DDQ content_NN1 will_VM be_VBI included_VVN )_) This_DD1 section_NN1 of_IO the_AT paper_NN1 will_VM describe_VVI how_RRQ the_AT data_NN collection_NN1 was_VBDZ done_VDN ._. 
</s>
<s>
This_DD1 will_VM include_VVI the_AT difficulties_NN2 that_CST were_VBDR present_JJ and_CC what_DDQ was_VBDZ successful_JJ in_II the_AT data_NN collection_NN1 ._. 
</s>
<s>
If_CS there_EX were_VBDR any_DD problems_NN2 in_II collecting_VVG the_AT data_NN it_PPH1 will_VM be_VBI discussed_VVN here._NNU 3.3_MC Analysis_NN1 of_IO data_NN The_AT data_NN is_VBZ analyzed_VVN first_MD by_II looking_VVG at_II what_DDQ the_AT informants_NN2 answered_VVD overall_RR to_II the_AT questions_NN2 they_PPHS2 were_VBDR presented_VVN with_IW ._. 
</s>
<s>
After_CS the_AT overall_JJ analysis_NN1 of_IO the_AT data_NN ,_, there_EX will_VM be_VBI a_AT1 further_JJR discussion_NN1 as_II21 to_II22 what_DDQ the_AT informants_NN2 said_VVD in_II31 regard_II32 to_II33 the_AT aim_NN1 of_IO the_AT study_NN1 ._. 
</s>
<s>
This_DD1 will_VM include_VVI a_AT1 comparison_NN1 of_IO the_AT answers_NN2 ._. 
</s>
<s>
The_AT data_NN is_VBZ also_RR compared_VVN with_IW the_AT literature_NN1 regarding_II the_AT subject_NN1 of_IO consumer_NN1 purchasing_VVG behavior._NNU 4_MC Empirical_JJ results_NN2 (_( Description_NN1 of_IO what_DDQ content_NN1 will_VM be_VBI included_VVN )_) This_DD1 section_NN1 analyses_VVZ the_AT gathered_JJ data_NN from_II the_AT interviews_NN2 in_RP regards_VVZ to_II the_AT aim_NN1 of_IO the_AT study_NN1 ._. 
</s>
<s>
The_AT information_NN1 gathered_VVN is_VBZ discussed_VVN as_CSA whole_JJ ,_, with_IW an_AT1 emphasis_NN1 on_II the_AT discussion_NN1 about_II the_AT effects_NN2 of_IO cell_NN1 phone_NN1 design_NN1 on_II purchasing_VVG behavior._NNU 5_MC Conclusions_NN2 and_CC Implications_NN2 (_( Description_NN1 of_IO what_DDQ content_NN1 will_VM be_VBI included_VVN )_) This_DD1 section_NN1 of_IO the_AT paper_NN1 draws_VVZ conclusions_NN2 based_VVN on_II the_AT analysis_NN1 in_II chapter_NN1 four_MC ._. 
</s>
<s>
More_RGR practical_JJ information_NN1 for_IF companies_NN2 is_VBZ given_VVN through_II the_AT discussion_NN1 about_II the_AT implications_NN2 of_IO the_AT results_NN2 of_IO this_DD1 study_NN1 for_IF companies_NN2 ._. 
</s>
