<s>
Introduction_NN1 The_AT public_JJ companies_NN2 board_NN1 and_CC auditing_VVG activities_NN2 have_VH0 been_VBN discussed_VVN in_RR21 public_RR22 and_CC caught_VVD the_AT attention_NN1 both_RR internationally_RR and_CC in_II Finland_NP1 ._. 
</s>
<s>
Auditing_VVG scandals_NN2 in_II the_AT early_JJ 2000s_MC2 such_II21 as_II22 the_AT demise_NN1 of_IO Enron_NP1 and_CC Arthur_NP1 &;_NULL Andersen_NP1 have_VH0 greatly_RR scrutinized_VVN the_AT investors_NN2 confidence_NN1 in_II the_AT capital_NN1 markets_NN2 ._. 
</s>
<s>
The_AT scandals_NN2 caused_VVD investors_NN2 ,_, legislators_NN2 ,_, media_NN and_CC the_AT companies_NN2 themselves_PPX2 to_TO question_VVI their_APPGE board_NN1 and_CC auditing_VVG activities_NN2 ._. 
</s>
<s>
In_II the_AT United_NP1 States_NP1 these_DD2 scandals_NN2 was_VBDZ the_AT origin_NN1 for_IF the_AT Sarbanes-Oxley_NN1 Act_NN1 (_( SOX_NN2 )_) ,_, this_DD1 is_VBZ an_AT1 extensive_JJ document_NN1 with_IW rules_NN2 and_CC regulations_NN2 that_CST all_DB the_AT public_JJ listed_JJ companies_NN2 must_VM comply_VVI with_IW ._. 
</s>
<s>
In_II Finland_NP1 a_AT1 corporate_JJ governance_NN1 recommendation_NN1 was_VBDZ implemented_VVN 1.7.2004_MC and_CC is_VBZ the_AT equivalent_JJ to_II the_AT American_JJ SOX_NN2 ._. 
</s>
<s>
The_AT purpose_NN1 of_IO the_AT recommendation_NN1 is_VBZ to_TO guarantee_VVI that_DD1 listed_JJ companies_NN2 management_NN1 is_VBZ of_IO a_AT1 high_JJ standard_NN1 and_CC that_CST the_AT business_NN1 is_VBZ transparent_JJ ._. 
</s>
<s>
But_CCB the_AT most_RGT notable_JJ issue_NN1 is_VBZ the_AT improvement_NN1 of_IO the_AT information_NN1 flow_NN1 between_II companies_NN2 and_CC its_APPGE parties_NN2 ._. 
</s>
<s>
The_AT new_JJ recommendations_NN2 have_VH0 given_VVN rise_NN1 to_II questions_NN2 such_II21 as_II22 ,_, how_RRQ effective_JJ are_VBR the_AT corporate_JJ governance_NN1 recommendations_NN2 ?_? 
</s>
<s>
Has_VHZ the_AT changes_NN2 effected_VVN the_AT companies_NN2 or_CC not_XX ?_? 
</s>
<s>
Audit_NN1 committees_NN2 have_VH0 played_VVN an_AT1 important_JJ role_NN1 in_II the_AT governance_NN1 of_IO corporations_NN2 since_CS their_APPGE inception_NN1 in_II the_AT early_JJ 1940s_MC2 ,_, and_CC their_APPGE visibility_NN1 and_CC contribution_NN1 have_VH0 greatly_RR increased_VVN in_II the_AT past_JJ few_DA2 years_NNT2 ._. 
</s>
<s>
Audit_NN1 committees_NN2 have_VH0 been_VBN described_VVN as_II organizations_NN2 guardians_NN2 of_IO financial_JJ integrity_NN1 (_( Verschoor_NP1 2008_MC )_) ._. 
</s>
<s>
According_II21 to_II22 the_AT recommendations_NN2 the_AT audit_NN1 committees_NN2 most_RGT important_JJ tasks_NN2 are_VBR to_TO improve_VVI the_AT quality_NN1 of_IO the_AT financial_JJ reporting_NN1 ,_, strengthen_VV0 the_AT internal_JJ audit_NN1 ,_, and_CC work_VV0 closely_RR with_IW the_AT external_JJ auditor_NN1 and_CC the_AT monitoring_NN1 of_IO the_AT financial_JJ reporting_NN1 process_NN1 ._. 
</s>
<s>
Prior_JJ research_NN1 has_VHZ mostly_RR discussed_VVN the_AT audit_NN1 committee_NN1 and_CC its_APPGE characteristics_NN2 ._. 
</s>
<s>
Xie_NN1 ,_, Davidson_NP1 and_CC DaDalt_NP1 (_( 2003_MC )_) and_CC Klein_NP1 (_( 2002_MC )_) analyzed_VVD how_RRQ the_AT audit_NN1 committees_NN2 and_CC board_NN1 members_NN2 financial_JJ expertise_NN1 effects_NN2 the_AT financial_JJ reporting_NN1 ._. 
</s>
<s>
These_DD2 studies_NN2 showed_VVD that_CST earnings_NN2 management_NN1 is_VBZ not_XX usual_JJ for_IF companies_NN2 that_CST have_VH0 an_AT1 audit_NN1 committee_NN1 composed_VVN by_II members_NN2 with_IW a_AT1 strong_JJ financial_JJ knowledge_NN1 and_CC education_NN1 ._. 
</s>
<s>
According_II21 to_II22 Klein_NP1 an_AT1 independent_JJ board_NN1 monitors_VVZ the_AT financial_JJ reporting_NN1 far_RG more_RGR effectively_RR than_CSN a_AT1 non-independent_JJ board_NN1 ._. 
</s>
<s>
Cohen_NP1 ,_, Gaynor_NP1 and_CC Wright_NP1 (_( 2008_MC )_) studied_VVD different_JJ aspects_NN2 that_CST effect_VV0 the_AT composition_NN1 and_CC effectiveness_NN1 of_IO audit_NN1 committees_NN2 ._. 
</s>
<s>
The_AT studied_JJ showed_VVD that_DD1 independence_NN1 ,_, size_NN1 and_CC expertise_NN1 are_VBR the_AT most_RGT important_JJ factors_NN2 when_CS putting_VVG together_RL an_AT1 audit_NN1 committee_NN1 ._. 
</s>
<s>
In_II31 accordance_II32 with_II33 most_DAT of_IO the_AT prior_JJ research_NN1 Cohen_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
also_RR find_VV0 that_CST an_AT1 audit_NN1 committee_NN1 with_IW independent_JJ members_NN2 and_CC a_AT1 high_JJ financial_JJ knowledge_NN1 was_VBDZ associated_VVN with_IW an_AT1 improved_JJ internal_JJ control_NN1 and_CC higher_JJR financial_JJ reporting_NN1 quality_NN1 ._. 
</s>
<s>
As_CSA prior_JJ research_NN1 has_VHZ shown_VVN the_AT audit_NN1 committee_NN1 does_VDZ indeed_RR add_VVI value_NN1 to_II a_AT1 company_NN1 if_CS the_AT companies_NN2 follow_VV0 the_AT recommendations_NN2 regarding_II the_AT members_NN2 and_CC their_APPGE financial_JJ knowledge_NN1 ._. 
</s>
<s>
Though_CS these_DD2 audit_NN1 committees_NN2 are_VBR still_RR quite_RG a_AT1 new_JJ phenomenon_NN1 in_II Finland_NP1 more_RRR and_CC more_DAR companies_NN2 are_VBR trying_VVG to_TO comply_VVI with_IW the_AT corporate_JJ governance_NN1 recommendations_NN2 and_CC especially_RR regarding_II the_AT establishment_NN1 of_IO an_AT1 audit_NN1 committee_NN1 ._. 
</s>
<s>
The_AT purpose_NN1 of_IO this_DD1 paper_NN1 is_VBZ to_TO investigate_VVI if_CSW companies_NN2 do_VD0 comply_VVI with_IW the_AT rule_NN1 and_CC recommendations_NN2 ,_, that_CST state_VV0 that_CST an_AT1 audit_NN1 committee_NN1 member_NN1 should_VM have_VHI sufficient_JJ knowledge_NN1 and_CC education_NN1 regarding_II economics_NN1 and_CC if_CS so_RR does_VDZ it_PPH1 give_VVI the_AT company_NN1 any_DD added_JJ value_NN1 ._. 
</s>
<s>
Prior_RR Research_VV0 Corporate_JJ governance_NN1 has_VHZ been_VBN defined_VVN by_II Monks_NN2 (_( 1995_MC )_) as_II the_AT processes_NN2 ,_, management_NN1 and_CC principles_NN2 that_CST affect_VV0 the_AT way_NN1 a_AT1 company_NN1 is_VBZ governed_VVN ._. 
</s>
<s>
According_II21 to_II22 Zattoni_NP1 and_CC Cuomo_NP1 (_( 2008_MC )_) the_AT separation_NN1 of_IO ownership_NN1 and_CC control_NN1 has_VHZ laid_VVN the_AT foundation_NN1 for_IF corporate_JJ governance_NN1 ._. 
</s>
<s>
According_II21 to_II22 the_AT recommendations_NN2 stated_VVN in_II the_AT Finnish_JJ Corporate_JJ Governance_NN1 Code_NN1 2008_MC ,_, audit_NN1 committees_NN2 should_VM appoint_VVI members_NN2 that_CST are_VBR financially_RR literate_JJ or_CC have_VH0 a_AT1 proven_JJ record_NN1 within_II finance_NN1 and_CC accounting_NN1 ._. 
</s>
<s>
Without_IW these_DD2 traits_NN2 the_AT audit_NN1 committee_NN1 will_VM not_XX be_VBI able_JK to_TO handle_VVI its_APPGE tasks_NN2 and_CC be_VBI effective_JJ ._. 
</s>
<s>
Dezoort_NP1 (_( 1998_MC )_) observes_VVZ in_II his_APPGE study_NN1 that_CST experience_NN1 is_VBZ an_AT1 extremely_RR important_JJ trait_NN1 for_IF audit_NN1 committee_NN1 members_NN2 when_CS it_PPH1 comes_VVZ to_II internal_JJ control_NN1 decisions_NN2 ._. 
</s>
<s>
The_AT results_NN2 show_VV0 that_CST members_NN2 with_IW experience_NN1 tend_VV0 to_TO make_VVI decisions_NN2 like_II auditors_NN2 ._. 
</s>
<s>
Experience_NN1 is_VBZ also_RR important_JJ as_CSA problem_NN1 situations_NN2 in_II finance_NN1 never_RR tend_VV0 to_TO have_VHI a_AT1 yes_UH or_CC no_AT answer_NN1 ,_, and_CC with_IW experience_NN1 it_PPH1 is_VBZ easier_JJR to_TO solve_VVI complex_JJ financial_JJ problems_NN2 ._. 
</s>
<s>
Cohen_NP1 ,_, Gaynor_NP1 ,_, Krishnamoorthy_NP1 och_UH Wright_NP1 (_( 2008_MC )_) investigated_VVD which_DDQ factors_VVZ that_CST is_VBZ of_IO importance_NN1 when_CS establishing_VVG an_AT1 audit_NN1 committee_NN1 and_CC how_RRQ it_PPH1 effects_VVZ the_AT committees_NN2 effectiveness_NN1 ._. 
</s>
<s>
Also_RR in_II this_DD1 study_NN1 the_AT results_NN2 show_VV0 that_CST financial_JJ expertise_NN1 is_VBZ the_AT most_RGT important_JJ quality_NN1 needed_VVN by_II a_AT1 member_NN1 ._. 
</s>
<s>
The_AT authors_NN2 observe_VV0 that_CST members_NN2 that_CST are_VBR independent_JJ and_CC are_VBR financially_RR literate_JJ lead_NN1 to_II better_JJR internal_JJ controls_NN2 and_CC reporting_VVG quality_NN1 ._. 
</s>
<s>
Kam_FW and_CC Li_NP1 (_( 2008_MC )_) investigate_VV0 the_AT relation_NN1 between_II independent_JJ audit_NN1 committees_NN2 and_CC the_AT companies_NN2 value_NN1 ._. 
</s>
<s>
The_AT results_NN2 show_VV0 that_CST when_CS an_AT1 audit_NN1 committee_NN1 consists_VVZ of_IO more_DAR than_CSN 50_MC %_NNU expert_NN1 independent_JJ directors_NN2 it_PPH1 has_VHZ a_AT1 positive_JJ effect_NN1 on_II the_AT companys_NN2 value_NN1 ._. 
</s>
<s>
The_AT results_NN2 also_RR show_VV0 that_CST there_EX is_VBZ no_AT positive_JJ correlation_NN1 between_II company_NN1 value_NN1 and_CC an_AT1 audit_NN1 committee_NN1 without_IW financial_JJ experts_NN2 ._. 
</s>
<s>
Davidson_NP1 ,_, Xie_NN1 och_UH Xu_NP1 (_( 2006_MC )_) studied_VVD the_AT markets_NN2 reaction_NN1 regarding_II the_AT appointment_NN1 of_IO audit_NN1 committee_NN1 members_NN2 ._. 
</s>
<s>
The_AT authors_NN2 claim_VV0 that_CST if_CS the_AT market_NN1 can_VM value_VVI the_AT importance_NN1 of_IO a_AT1 financial_JJ expert_NN1 on_II the_AT committee_NN1 this_DD1 should_VM have_VHI a_AT1 positive_JJ effect_NN1 on_II the_AT companys_NN2 value_NN1 ._. 
</s>
<s>
The_AT authors_NN2 had_VHD a_AT1 total_NN1 of_IO 136_MC observations_NN2 ,_, 87_MC where_RRQ so_JJ21 called_JJ22 financial_JJ experts_NN2 ._. 
</s>
<s>
The_AT authors_NN2 find_VV0 a_AT1 significant_JJ positive_JJ correlation_NN1 between_II an_AT1 audit_NN1 committee_NN1 member_NN1 with_IW financial_JJ expertise_NN1 and_CC the_AT companys_NN2 stock_NN1 price_NN1 ._. 
</s>
<s>
Jengfang_VV0 ,_, Rong-Ruey_NN1 och_UH Fujing_NP1 (_( 2008_MC )_) study_NN1 investigated_VVD whether_CSW companys_NN2 with_IW an_AT1 audit_NN1 committee_NN1 have_VH0 better_JJR returns_NN2 compared_VVN to_II companys_NN2 without_IW an_AT1 audit_NN1 committee_NN1 ._. 
</s>
<s>
The_AT results_NN2 clearly_RR show_VV0 that_CST companies_NN2 without_IW an_AT1 audit_NN1 committee_NN1 have_VH0 lower_JJR returns_NN2 ._. 
</s>
<s>
The_AT explanation_NN1 to_II this_DD1 was_VBDZ that_CST companies_NN2 with_IW an_AT1 audit_NN1 committee_NN1 tend_VV0 to_TO have_VHI higher_JJR internal_JJ controls_NN2 and_CC better_JJR monitoring_NN1 ._. 
</s>
<s>
This_DD1 gives_VVZ the_AT company_NN1 a_AT1 more_RGR reliable_JJ picture_NN1 to_II investors_NN2 and_CC other_JJ third_MD parties_NN2 ._. 
</s>
<s>
Carcello_NN1 ,_, Hollingsworth_NP1 ,_, Klein_NP1 and_CC Neal_NP1 (_( 2006_MC )_) examine_VV0 the_AT associations_NN2 between_II audit_NN1 committee_NN1 financial_JJ expertise_NN1 and_CC alternate_JJ corporate_JJ governance_NN1 mechanisms_NN2 and_CC earnings_NN2 management_NN1 ._. 
</s>
<s>
The_AT findings_NN2 claim_VV0 that_CST financial_JJ expertise_NN1 does_VDZ indeed_RR reduce_VVI earnings_NN2 management_NN1 for_IF companys_NN2 with_IW weak_JJ alternate_JJ governance_NN1 mechanisms_NN2 ._. 
</s>
<s>
The_AT results_NN2 also_RR show_VV0 that_CST if_CS the_AT company_NN1 has_VHZ alternate_JJ corporate_JJ governance_NN1 mechanisms_NN2 that_CST work_VV0 it_PPH1 is_VBZ an_AT1 effective_JJ substitute_NN1 for_IF the_AT audit_NN1 committee_NN1 ._. 
</s>
<s>
Ernst_NP1 &;_NULL Young_NP1 (_( 2007_MC )_) researched_VVN the_AT audit_NN1 committee_NN1 composition_NN1 ._. 
</s>
<s>
They_PPHS2 surveyed_VVD audit_NN1 committee_NN1 chairs_NN2 ,_, audit_NN1 committee_NN1 members_NN2 ,_, board_NN1 members_NN2 and_CC others_NN2 from_II 176_MC companies_NN2 around_II the_AT world_NN1 ._. 
</s>
<s>
In_II the_AT survey_NN1 the_AT question_NN1 regarding_II audit_NN1 committee_NN1 composition_NN1 was_VBDZ What_DDQ is_VBZ the_AT single_JJ most_RGT important_JJ area_NN1 of_IO expertise_NN1 sought_VVN in_II recruiting_VVG new_JJ audit_NN1 committee_NN1 members_NN2 ?_? 34_MC %_NNU of_IO audit_NN1 committees_NN2 look_VV0 for_IF a_AT1 new_JJ member_NN1 that_CST qualify_VV0 as_II a_AT1 financial_JJ expert_NN1 and_CC 24_MC %_NNU look_NN1 for_IF executive/CEO_NN1 experience_NN1 ._. 
</s>
<s>
15_MC %_NNU indicate_VV0 their_APPGE audit_NN1 committee_NN1 looks_VVZ for_IF new_JJ members_NN2 with_IW industry_NN1 experience_NN1 ,_, 16_MC %_NNU look_NN1 for_IF other_JJ areas_NN2 of_IO expertise_NN1 including_II international_JJ experience_NN1 and_CC diverse_JJ financial_JJ experience_NN1 ._. 
</s>
<s>
Research_NN1 Method_NN1 and_CC Purpose_NN1 The_AT purpose_NN1 of_IO this_DD1 paper_NN1 is_VBZ to_TO present_VVI through_II a_AT1 literature_NN1 overview_NN1 the_AT prior_JJ research_NN1 regarding_II audit_NN1 committee_NN1 members_NN2 characteristics_NN2 and_CC if_CS these_DD2 characteristics_NN2 add_VV0 any_DD more_DAR value_NN1 to_II the_AT company_NN1 ._. 
</s>
<s>
By_II analyzing_VVG the_AT results_NN2 from_II prior_JJ research_NN1 I_PPIS1 will_VM summaries_NN2 the_AT results_NN2 and_CC discuss_VV0 and_CC further_RRR analyze_VV0 them_PPHO2 ._. 
</s>
<s>
Analysis_NN1 and_CC Results_NN2 Due_II21 to_II22 the_AT financial_JJ scandals_NN2 that_CST have_VH0 occurred_VVN many_DA2 financial_JJ experts_NN2 in_II the_AT field_NN1 have_VH0 willingly_RR researched_VVN the_AT question_NN1 regarding_II corporate_JJ governance_NN1 and_CC the_AT audit_NN1 committee_NN1 ._. 
</s>
<s>
Most_DAT of_IO the_AT prior_JJ research_NN1 has_VHZ indeed_RR based_VVN its_APPGE focus_NN1 on_II the_AT members_NN2 characteristics_NN2 and_CC added_JJ value_NN1 that_CST can_VM be_VBI achieved_VVN with_IW an_AT1 effective_JJ audit_NN1 committee_NN1 ._. 
</s>
<s>
As_CSA we_PPIS2 can_VM see_VVI a_AT1 majority_NN1 of_IO the_AT authors_NN2 are_VBR in_II agreement_NN1 that_CST an_AT1 effective_JJ and_CC working_VVG audit_NN1 committee_NN1 has_VHZ to_TO consist_VVI of_IO financial_JJ experts_NN2 ._. 
</s>
<s>
The_AT term_NN1 financial_JJ expert_NN1 is_VBZ discussed_VVN in_II most_DAT of_IO the_AT prior_JJ researches_NN2 and_CC is_VBZ a_RR21 bit_RR22 blurred_VVN ._. 
</s>
<s>
But_CCB according_II21 to_II22 most_DAT of_IO the_AT studies_NN2 a_AT1 financial_JJ expert_NN1 is_VBZ a_AT1 member_NN1 that_CST either_DD1 has_VHZ a_AT1 high_JJ financial_JJ education_NN1 or_CC a_AT1 proven_JJ track_NN1 record_NN1 on_II the_AT job_NN1 market_NN1 ._. 
</s>
<s>
As_CSA we_PPIS2 can_VM see_VVI from_II prior_JJ research_NN1 corporate_JJ governance_NN1 has_VHZ become_VVN more_RGR important_JJ for_IF the_AT large_JJ and_CC multinational_JJ companies_NN2 ._. 
</s>
<s>
Especially_RR Kam_FW and_CC Li_NP1 (_( 2008_MC )_) study_NN1 shows_VVZ the_AT importance_NN1 of_IO good_JJ corporate_JJ governance_NN1 ._. 
</s>
<s>
The_AT authors_NN2 used_VVN as_CSA sample_NN1 the_AT 200_MC biggest_JJT companies_NN2 from_II the_AT Fortune_NN1 500_MC during_II the_AT year_NNT1 2000_MC ._. 
</s>
<s>
And_CC divided_VVD the_AT members_NN2 into_II two_MC different_JJ groups_NN2 expert_JJ independent_JJ directors_NN2 and_CC financed_VVD trained_JJ directors_NN2 ._. 
</s>
<s>
As_RG earlier_RRR mentioned_VVD the_AT results_NN2 clearly_RR show_VV0 that_CST a_AT1 expert_NN1 and_CC financed_VVD trained_JJ director_NN1 will_VM add_VVI value_NN1 to_II the_AT company_NN1 as_CS31 long_CS32 as_CS33 the_AT rest_NN1 of_IO the_AT audit_NN1 committee_NN1 members_NN2 also_RR are_VBR financially_RR literate_JJ ._. 
</s>
<s>
As_CSA stated_VVN earlier_RRR the_AT foundation_NN1 for_IF corporate_JJ governance_NN1 was_VBDZ the_AT separation_NN1 of_IO ownership_NN1 and_CC control_NN1 ._. 
</s>
<s>
Kam_FW and_CC Li_NP1 study_NN1 also_RR sheds_NN2 light_VV0 on_II this_DD1 statement_NN1 ,_, as_CSA there_EX results_NN2 state_VV0 that_CST if_CS the_AT Managing_JJ director_NN1 also_RR acts_VVZ as_II the_AT chairman_NN1 of_IO the_AT board_NN1 this_DD1 significantly_RR effect_VV0 the_AT companies_NN2 value_NN1 ._. 
</s>
<s>
Discussion_NN1 and_CC Conclusion_NN1 
</s>
