<s>
1_MC1 INTRODUCTION_NN1 Ever_RR since_CS the_AT beginning_NN1 of_IO the_AT 21st_MD century_NNT1 ,_, media_NN consumption_NN1 habits_NN2 have_VH0 been_VBN fragmented_VVN exponentially_RR ._. 
</s>
<s>
Large_JJ factor_NN1 in_II this_DD1 transformation_NN1 has_VHZ been_VBN the_AT rise_NN1 of_IO the_AT internet_NN1 era_NN1 ._. 
</s>
<s>
Social_JJ media_NN ,_, smartphones_NN2 ,_, and_CC blogs_NN2 are_VBR just_RR single_JJ examples_NN2 of_IO the_AT technical_JJ and_CC social_JJ advancements_NN2 that_CST shape_VV0 the_AT world_NN1 we_PPIS2 live_VV0 in_RP ._. 
</s>
<s>
This_DD1 has_VHZ led_VVN to_II a_AT1 change_NN1 in_II the_AT way_NN1 consumers_NN2 use_VV0 media_NN ,_, as_CSA more_DAR and_CC more_DAR people_NN are_VBR turning_VVG from_II traditional_JJ media_NN ,_, such_II21 as_II22 newspapers_NN2 ,_, to_II digital_JJ services_NN2 ._. 
</s>
<s>
Consumers_NN2 expect_VV0 advertising_NN1 content_NN1 in_II digital_JJ media_NN to_TO be_VBI tailored_VVN for_IF their_APPGE needs_NN2 ._. 
</s>
<s>
This_DD1 creates_VVZ challenges_NN2 for_IF companies_NN2 but_CCB it_PPH1 also_RR presents_VVZ opportunities_NN2 ._. 
</s>
<s>
In_II 2011_MC the_AT amount_NN1 of_IO media_NN advertising_NN1 in_II Finland_NP1 was_VBDZ 1_MC1 395_MC million_NNO euros_NN2 (_( TNS_NP1 Gallup_NP1 ,_, 2012_MC )_) ._. 
</s>
<s>
In_II Finlands_NP2 scale_VV0 this_DD1 is_VBZ a_AT1 huge_JJ amount_NN1 of_IO money_NN1 to_TO be_VBI distributed_VVN ._. 
</s>
<s>
At_II the_AT moment_NN1 ,_, online_JJ advertising_NN1 is_VBZ the_AT only_JJ form_NN1 of_IO media_NN in_II Finland_NP1 that_CST has_VHZ grown_VVN during_II the_AT first_MD half_NN1 of_IO the_AT year_NNT1 2012_MC ,_, accounting_VVG for_IF 116_MC million_NNO euros_NN2 of_IO the_AT entire_JJ media_NN consumption_NN1 ._. 
</s>
<s>
(_( TNS_NP1 Media_NN Intelligence_NN1 ,_, 2012_MC )_) Why_RRQ is_VBZ online_JJ advertising_NN1 gaining_VVG such_DA popularity_NN1 and_CC how_RRQ can_VM companies_NN2 implement_VVI digital_JJ media_NN channels_NN2 as_II a_AT1 part_NN1 of_IO their_APPGE marketing_NN1 mix_NN1 in_II a_AT1 functional_JJ way_NN1 ?_? 
</s>
<s>
This_DD1 study_NN1 looks_VVZ to_TO answer_VVI those_DD2 questions_NN2 and_CC to_TO make_VVI an_AT1 overview_NN1 of_IO the_AT ongoing_JJ transitional_JJ face_NN1 of_IO the_AT media_NN landscape_NN1 from_II traditional_JJ to_II a_AT1 new_JJ ,_, digital_JJ one_PN1 ._. 
</s>
<s>
Media_NN means_VVZ a_AT1 tool_NN1 for_IF delivering_VVG or_CC storing_VVG information_NN1 ._. 
</s>
<s>
Digital_JJ media_NN in_II its_APPGE original_JJ sense_NN1 means_VVZ an_AT1 electronic_JJ form_NN1 of_IO media_NN where_CS data_NN is_VBZ either_RR stored_VVN or_CC delivered_VVN in_II digital_JJ form_NN1 ,_, such_II21 as_II22 in_II television_NN1 ._. 
</s>
<s>
Today_RT digital_JJ media_NN has_VHZ grown_VVN to_TO be_VBI synonymous_JJ with_IW media_NN delivered_VVN through_II Internet_NP1 or_CC mobile_JJ applications_NN2 ,_, where_CS as_CSA television_NN1 has_VHZ been_VBN labeled_VVN as_II a_AT1 broadcasting_NN1 media_NN ._. 
</s>
<s>
The_AT reason_NN1 for_IF this_DD1 is_VBZ that_CST traditionally_RR broadcasting_JJ media_NN has_VHZ been_VBN a_AT1 one-way_JJ transitional_JJ media_NN ,_, with_IW the_AT possibility_NN1 of_IO only_JJ transmitting_JJ information_NN1 but_CCB not_XX receiving_VVG it_PPH1 ,_, whereas_CS in_II digital_JJ (_( internet_NN1 )_) media_NN the_AT possibility_NN1 of_IO dialogue_NN1 nearly_RR always_RR exists_VVZ ._. 
</s>
<s>
In_II the_AT future_NN1 ,_, when_CS smart-TV_JJ s_ZZ1 will_VM grow_VVI in_II numbers_NN2 ,_, there_EX may_VM be_VBI a_AT1 need_NN1 to_TO revaluate_VVI this_DD1 segmentation_NN1 as_CSA televisions_NN2 will_VM provide_VVI a_AT1 possibility_NN1 for_IF a_AT1 dialogue_NN1 as_RR21 well_RR22 ._. 
</s>
<s>
Here_RL I_PPIS1 will_VM add_VVI more_DAR info_NN1 on_II media_NN industry_NN1 and_CC on_II the_AT basis_NN1 of_IO the_AT research_NN1 METHODS_NN2 This_DD1 research_NN1 will_VM be_VBI conducted_VVN using_VVG qualitative_JJ methods_NN2 such_II21 as_II22 expert_NN1 interviews_NN2 ._. 
</s>
<s>
Part_NN1 of_IO the_AT research_NN1 material_NN1 will_VM be_VBI based_VVN on_II existing_JJ literature_NN1 as_II31 well_II32 as_II33 internet_NN1 sources_NN2 ,_, such_II21 as_II22 newsletters_NN2 and_CC blogs_NN2 ._. 
</s>
<s>
Due_II21 to_II22 the_AT continuous_JJ development_NN1 and_CC transition_NN1 of_IO the_AT industry_NN1 ,_, most_RGT printed_JJ literature_NN1 sources_NN2 are_VBR old_JJ when_CS printed_VVN and_CC do_VD0 not_XX represent_VVI the_AT most_RGT up_JJ31 to_JJ32 date_JJ33 information_NN1 possible_JJ ._. 
</s>
<s>
Therefore_RR printed_JJ literature_NN1 sources_NN2 are_VBR mainly_RR used_VVN for_IF creating_VVG a_AT1 general_JJ overview_NN1 of_IO media_NN industry_NN1 ._. 
</s>
<s>
In_II different_JJ situations_NN2 ,_, if_CS literature_NN1 information_NN1 is_VBZ not_XX available_JJ ,_, the_AT researcher_NN1 will_VM also_RR lean_VVI to_II personal_JJ experience_NN1 from_II the_AT media_NN industry_NN1 ._. 
</s>
<s>
Despite_II this_DD1 ,_, the_AT researcher_NN1 will_VM always_RR look_VVI for_IF to_TO use_VVI literature_NN1 sources_NN2 to_TO protect_VVI ones_NN2 academic_JJ integrity_NN1 from_II making_VVG subjective_JJ assumptions_NN2 ._. 
</s>
<s>
Here_RL I_PPIS1 will_VM add_VVI more_DAR information_NN1 on_II methodology_NN1 ._. 
</s>
<s>
RESULTS_NN2 Here_RL I_PPIS1 will_VM present_VVI results_NN2 once_CS they_PPHS2 are_VBR obtained_VVN ._. 
</s>
<s>
DISCUSSION_NN1 Discussion_NN1 chapter_NN1 REFERENCES_NN2 Reference_VV0 list_NN1 
</s>
