<s>
1_MC1 Introduction_NN1 What_DDQ makes_VVZ a_AT1 trend_NN1 spread_VVN like_II a_AT1 virus_NN1 ?_? 
</s>
<s>
What_DDQ are_VBR the_AT forces_NN2 behind_II it_PPH1 ?_? 
</s>
<s>
This_DD1 paper_NN1 aims_VVZ to_TO find_VVI possible_JJ answers_NN2 to_II these_DD2 questions_NN2 ._. 
</s>
<s>
The_AT world_NN1 today_RT is_VBZ full_JJ of_IO megatrends_NN2 ._. 
</s>
<s>
A_AT1 few_DA2 examples_NN2 include_VV0 Facebook_NP1 ,_, Twitter_VV0 ,_, Angry_JJ Birds_NN2 ,_, Lady_NNB Gaga_NP1 ,_, and_CC many_DA2 others_NN2 ._. 
</s>
<s>
Phenomenons_NN2 like_II Lady_NNB Gaga_NP1 or_CC Facebook_NP1 do_VD0 not_XX occur_VVI every_AT1 year_NNT1 ,_, but_CCB when_CS they_PPHS2 occur_VV0 ,_, they_PPHS2 seem_VV0 to_TO spread_VVI through_II most_DAT of_IO the_AT developed_JJ world_NN1 ._. 
</s>
<s>
How_RRQ does_VDZ this_DD1 happen_VVI ?_? 
</s>
<s>
Is_VBZ it_PPH1 because_II21 of_II22 extensive_JJ marketing_NN1 globally_RR ,_, push_VV0 or_CC pull-strategies_NN2 ,_, the_AT use_NN1 of_IO celebrities_NN2 in_II advertisements_NN2 ,_, luck_NN1 ,_, a_AT1 question_NN1 of_IO timing_NN1 ,_, or_CC is_VBZ it_PPH1 a_AT1 mixture_NN1 of_IO all_DB these_DD2 things_NN2 and_CC even_RR more_RRR ?_? 
</s>
<s>
These_DD2 might_VM be_VBI questions_NN2 we_PPIS2 can_VM not_XX answer_VVI ._. 
</s>
<s>
In_II recent_JJ years_NNT2 ,_, these_DD2 kinds_NN2 of_IO huge_JJ trends_NN2 have_VH0 become_VVN more_RGR frequent_JJ and_CC the_AT world_NN1 has_VHZ become_VVN more_RGR competitive_JJ in_II all_DB branches_NN2 ._. 
</s>
<s>
For_IF this_DD1 reason_NN1 ,_, it_PPH1 is_VBZ important_JJ to_TO consider_VVI which_DDQ factors_NN2 might_VM influence_VVI the_AT birth_NN1 of_IO megatrends_NN2 ,_, as_II31 well_II32 as_II33 finding_VVG possible_JJ patterns_NN2 in_II this_DD1 area_NN1 of_IO study_NN1 ._. 
</s>
<s>
What_DDQ is_VBZ more_RRR ,_, it_PPH1 is_VBZ simply_RR interesting_JJ to_TO investigate_VVI why_RRQ a_AT1 phenomenon_NN1 such_II21 as_II22 Facebook_NP1 has_VHZ recently_RR occupied_VVN the_AT life_NN1 of_IO so_RG many_DA2 and_CC how_RGQ new_JJ similar_JJ trends_NN2 will_VM occupy_VVI the_AT lives_NN2 of_IO many_DA2 in_II the_AT future_NN1 ._. 
</s>
<s>
From_II a_AT1 marketing_NN1 perspective_NN1 ,_, it_PPH1 seems_VVZ as_CS21 if_CS22 it_PPH1 is_VBZ not_XX enough_RR anymore_RR to_TO find_VVI out_RP what_DDQ customers_NN2 want_VV0 or_CC need_VV0 through_II marketing_NN1 research_NN1 ._. 
</s>
<s>
Instead_RR ,_, the_AT focus_NN1 is_VBZ somewhat_RR deeper_JJR ._. 
</s>
<s>
We_PPIS2 need_VV0 to_TO find_VVI out_RP how_RRQ we_PPIS2 can_VM influence_VVI the_AT tipping_NN1 of_IO a_AT1 trend_NN1 and_CC what_DDQ external_JJ factors_NN2 play_VV0 a_AT1 part_NN1 in_II this_DD1 process_NN1 ._. 
</s>
<s>
Malcolm_NP1 Gladwell_NP1 considers_VVZ the_AT phenomenon_NN1 in_II his_APPGE bestselling_JJ book_NN1 The_AT Tipping_NN1 Point_NN1 :_: How_RGQ Little_JJ Things_NN2 Can_VM Make_VV0 a_AT1 Big_JJ Difference_NN1 (_( 2002_MC )_) ._. 
</s>
<s>
He_PPHS1 uses_VVZ examples_NN2 such_II21 as_II22 Airwalk_NP1 ,_, Hush_VV0 Puppies_NN2 ,_, the_AT decreased_JJ crime_NN1 rate_NN1 in_II New_NP1 York_NP1 ,_, Sesame_NP1 Street_NNL1 ,_, as_II31 well_II32 as_II33 many_DA2 others_NN2 ,_, to_TO prove_VVI his_APPGE point_NN1 ._. 
</s>
<s>
Gladwell_NN1 argues_VVZ in_II his_APPGE book_NN1 that_CST trends_NN2 spread_VVN like_II epidemics_NN2 among_II the_AT population_NN1 and_CC that_CST they_PPHS2 may_VM start_VVI from_II the_AT smallest_JJT factor_NN1 ._. 
</s>
<s>
For_REX21 instance_REX22 ,_, one_MC1 child_NN1 goes_VVZ to_II school_NN1 with_IW measles_NN and_CC soon_RR the_AT whole_JJ class_NN1 has_VHZ measles_NN ._. 
</s>
<s>
He_PPHS1 argues_VVZ that_CST trends_NN2 spread_VVN in_II a_AT1 similar_JJ manner_NN1 :_: From_II a_AT1 few_DA2 people_NN to_II thousands_NNO2 ;_; even_RR millions_NNO2 ._. 
</s>
<s>
Gladwell_NN1 introduces_VVZ three_MC rules_NN2 to_TO help_VVI explain_VVI the_AT phenomenon_NN1 of_IO the_AT tipping_NN1 point_NN1 and_CC how_RRQ to_TO reach_VVI it_PPH1 :_: The_AT Law_NN1 of_IO the_AT Few_DA2 ,_, the_AT Stickiness_NN1 Factor_NN1 and_CC the_AT Power_NN1 of_IO Context_NN1 ._. 
</s>
<s>
This_DD1 paper_NN1 will_VM evaluate_VVI how_RRQ Gladwells_VVZ theories_NN2 and_CC rules_NN2 are_VBR applicable_JJ to_II a_AT1 social_JJ network_NN1 called_VVN Facebook_NN1 ._. 
</s>
<s>
Facebook_NN1 is_VBZ an_AT1 interesting_JJ phenomenon_NN1 that_CST has_VHZ reached_VVN its_APPGE tipping_NN1 point_NN1 recently_RR ,_, and_CC its_APPGE growth_NN1 does_VDZ not_XX seem_VVI to_TO stop_VVI ._. 
</s>
<s>
This_DD1 paper_NN1 is_VBZ structured_VVN as_CSA follows_VVZ ._. 
</s>
<s>
Firstly_RR ,_, the_AT three_MC rules_NN2 from_II Gladwells_NP2 book_NN1 will_VM be_VBI described_VVN using_VVG examples_NN2 ._. 
</s>
<s>
Secondly_RR ,_, there_EX will_VM be_VBI a_AT1 short_JJ section_NN1 about_II Facebook_NP1 :_: what_DDQ it_PPH1 is_VBZ and_CC how_RRQ it_PPH1 works_VVZ ._. 
</s>
<s>
Thirdly_RR ,_, there_EX will_VM be_VBI a_AT1 section_NN1 on_II the_AT methods_NN2 used_VMK to_TO collect_VVI data_NN ._. 
</s>
<s>
Then_RT the_AT results_NN2 from_II interviews_NN2 will_VM be_VBI presented_VVN ._. 
</s>
<s>
This_DD1 section_NN1 will_VM include_VVI any_DD possible_JJ patterns_NN2 that_CST might_VM have_VHI been_VBN found_VVN about_II the_AT tipping_NN1 point_NN1 of_IO Facebook_NN1 as_II31 well_II32 as_II33 an_AT1 evalutation_NN1 of_IO how_RRQ Gladwells_VVZ theories_NN2 are_VBR applicable_JJ to_II Facebook_NP1 ._. 
</s>
<s>
The_AT following_JJ section_NN1 will_VM discuss_VVI the_AT phenomenon_NN1 in_RR21 general_RR22 and_CC how_RRQ this_DD1 affects_VVZ possible_JJ future_JJ trends_NN2 ._. 
</s>
<s>
Finally_RR ,_, this_DD1 paper_NN1 will_VM end_VVI with_IW a_AT1 conclusion_NN1 ._. 
</s>
<s>
2_MC The_AT Three_MC Rules_NN2 of_IO Epidemics_NN2 according_II21 to_II22 Gladwell_NP1 According_II21 to_II22 Gladwells_NP2 book_VV0 The_AT Tipping_NN1 Point_NN1 :_: How_RGQ Little_JJ Things_NN2 Can_VM Make_VV0 a_AT1 Big_JJ Difference_NN1 ,_, there_EX are_VBR three_MC rules_NN2 that_CST help_VV0 to_TO explain_VVI the_AT phenomenon_NN1 of_IO the_AT tipping_NN1 point_NN1 ._. 
</s>
<s>
These_DD2 three_MC rules_NN2 are_VBR the_AT Law_NN1 of_IO the_AT Few_DA2 ,_, the_AT Stickiness_NN1 Factor_NN1 ,_, and_CC the_AT Power_NN1 of_IO Context_NN1 ._. 
</s>
<s>
In_II this_DD1 section_NN1 of_IO the_AT paper_NN1 ,_, these_DD2 rules_NN2 will_VM be_VBI explained_VVN ._. 
</s>
<s>
2.1The_FO Law_NN1 of_IO the_AT Few_DA2 The_AT first_MD rule_NN1 is_VBZ called_VVN the_AT Law_NN1 of_IO the_AT Few_DA2 ,_, which_DDQ can_VM be_VBI explained_VVN by_II Paretos_NP2 Principle_NN1 ,_, or_CC more_RGR commonly_RR known_VVN as_II the_AT 80/20_MF Rule_NN1 ._. 
</s>
<s>
The_AT rule_NN1 states_VVZ that_CST in_II many_DA2 events_NN2 ,_, approximately_RR 20_MC percent_NNU of_IO the_AT input_NN1 produces_VVZ 80_MC percent_NNU of_IO the_AT output_NN1 ._. 
</s>
<s>
A_AT1 classical_JJ example_NN1 of_IO this_DD1 (_( and_CC the_AT original_JJ reason_NN1 why_RRQ the_AT principle_NN1 was_VBDZ discovered_VVN )_) is_VBZ the_AT distribution_NN1 of_IO wealth_NN1 in_II country_NN1 ._. 
</s>
<s>
Vilfredo_NP1 Pareto_NP1 discovered_VVD in_II 1906_MC that_CST 20_MC percent_NNU of_IO the_AT population_NN1 owned_VVD 80_MC percent_NNU of_IO the_AT wealth_NN1 in_II Italy_NP1 ._. 
</s>
<s>
What_DDQ this_DD1 means_VVZ in_II31 terms_II32 of_II33 the_AT Law_NN1 of_IO the_AT Few_DA2 ,_, is_VBZ that_DD1 a_AT1 number_NN1 of_IO people_NN (_( roughly_RR 20_MC percent_NNU of_IO the_AT population_NN1 )_) with_IW certain_JJ skills_NN2 have_VH0 a_AT1 great_JJ influence_NN1 on_II the_AT tipping_NN1 of_IO a_AT1 trend_NN1 ._. 
</s>
<s>
According_II21 to_II22 Gladwell_NP1 ,_, these_DD2 people_NN with_IW certain_JJ skills_NN2 are_VBR called_VVN Connectors_NN2 ,_, Mavens_NP1 and_CC Salesmen_NN2 ._. 
</s>
<s>
2.1.1_MC Connectors_NN2 Connectors_NN2 are_VBR people_NN who_PNQS have_VH0 extraordinary_JJ social_JJ skills_NN2 and_CC can_VM be_VBI a_AT1 part_NN1 of_IO many_DA2 different_JJ social_JJ circles_NN2 and_CC subcultures_VVZ at_II the_AT same_DA time_NNT1 ._. 
</s>
<s>
Connectors_NN2 are_VBR the_AT kind_NN1 of_IO people_NN who_PNQS easily_RR make_VV0 new_JJ friends_NN2 and_CC their_APPGE social_JJ networks_NN2 are_VBR extremely_RR large_JJ ._. 
</s>
<s>
Connectors_NN2 also_RR know_VV0 the_AT right_JJ kind_NN1 of_IO people_NN ,_, for_REX21 instance_REX22 ,_, people_NN with_IW high_JJ status_NN1 among_II friends_NN2 ,_, street-credible_JJ hipsters_NN2 ,_, or_CC certain_JJ people_NN among_II certain_JJ niches_NN2 ._. 
</s>
<s>
Gladwell_NN1 points_VVZ out_RP that_CST everyone_PN1 knows_VVZ someone_PN1 who_PNQS is_VBZ a_AT1 connector_NN1 ._. 
</s>
<s>
But_CCB in_II the_AT case_NN1 of_IO Connectors_NN2 ,_, their_APPGE ability_NN1 to_TO span_VVI many_DA2 different_JJ worlds_NN2 is_VBZ a_AT1 function_NN1 of_IO something_PN1 intrinsic_JJ to_II their_APPGE personality_NN1 ,_, some_DD combination_NN1 of_IO curiosity_NN1 ,_, self-confidence_NN1 ,_, sociability_NN1 ,_, and_CC energy_NN1 (_( Gladwell_NP1 2002:49_MC )_) ._. 
</s>
<s>
However_RR ,_, Connectors_NN2 are_VBR not_XX just_RR helpful_JJ because_II21 of_II22 their_APPGE social_JJ personalities_NN2 ._. 
</s>
<s>
The_AT part_NN1 that_CST Connectors_NN2 play_VV0 in_II spreading_VVG social_JJ epidemics_NN2 in_II communities_NN2 is_VBZ word-of-mouth_JJ ._. 
</s>
<s>
Connectors_NN2 share_VV0 their_APPGE knowledge_NN1 about_RP ,_, for_REX21 instance_REX22 ,_, a_AT1 new_JJ virtual_JJ way_NN1 of_IO keeping_VVG in_II touch_NN1 called_VVN Facebook_NP1 ,_, and_CC suddenly_RR a_AT1 very_RG broad_JJ range_NN1 of_IO people_NN from_II different_JJ sub-cultures_NN2 know_VV0 about_II Facebook_NP1 ._. 
</s>
<s>
Word-of-mouth_JJ epidemics_NN2 are_VBR the_AT work_NN1 of_IO Connectors_NN2 (_( Gladwell_NP1 2002:59_MC )_) ._. 
</s>
<s>
However_RR ,_, Connectors_NN2 need_VV0 to_TO get_VVI their_APPGE knowledge_NN1 and_CC the_AT news_NN1 about_II Facebook_NP1 from_II someone_PN1 ,_, and_CC this_DD1 is_VBZ where_RRQ Mavens_NN2 step_VV0 in._NNU 2.1.2_MC Mavens_NN2 Mavens_NN2 are_VBR people_NN who_PNQS have_VH0 a_AT1 great_JJ level_NN1 of_IO knowledge_NN1 ._. 
</s>
<s>
In_II fact_NN1 ,_, Gladwell_NP1 points_VVZ out_RP that_CST the_AT word_NN1 maven_NN1 comes_VVZ from_II Yiddish_NN1 and_CC it_PPH1 means_VVZ someone_PN1 who_PNQS gathers_VVZ knowledge_NN1 ._. 
</s>
<s>
(_( Gladwell_VV0 2002:60_MC )_) ._. 
</s>
<s>
According_II21 to_II22 Gladwell_NP1 ,_, Mavens_NN2 are_VBR the_AT kinds_NN2 of_IO people_NN who_PNQS know_VV0 ,_, for_REX21 instance_REX22 ,_, if_CS products_NN2 in_II a_AT1 supermarket_NN1 are_VBR really_RR on_II sale_NN1 or_CC if_CS the_AT products_NN2 are_VBR exactly_RR the_AT same_DA price_NN1 as_CSA normally_RR but_CCB the_AT price_NN1 tag_NN1 is_VBZ yellow_JJ and_CC it_PPH1 says_VVZ special_JJ price_NN1 on_II it_PPH1 everyday_JJ ._. 
</s>
<s>
(_( Gladwell_VV0 2002:60-61_MCMC )_) ._. 
</s>
<s>
Mavens_NN2 ,_, in_II other_JJ words_NN2 ,_, are_VBR specialists_NN2 of_IO information_NN1 when_RRQ Connectors_NN2 are_VBR specialists_NN2 of_IO people_NN ._. 
</s>
<s>
(_( Gladwell_VV0 2002:59_MC )_) ._. 
</s>
<s>
Gladwell_NN1 describes_VVZ Mavens_NN2 as_II people_NN who_PNQS sincerely_RR want_VV0 to_TO share_VVI their_APPGE knowledge_NN1 with_IW you_PPY in_BCL21 order_BCL22 to_TO help_VVI you_PPY ._. 
</s>
<s>
They_PPHS2 do_VD0 not_XX share_VVI their_APPGE information_NN1 because_CS they_PPHS2 want_VV0 to_TO trick_VVI you_PPY or_CC to_TO brag_VVI on_II their_APPGE expertise_NN1 ,_, they_PPHS2 want_VV0 to_TO educate_VVI you_PPY ._. 
</s>
<s>
These_DD2 people_NN are_VBR crucial_JJ in_II starting_VVG word-of-mouth_JJ epidemics_NN2 since_CS they_PPHS2 are_VBR the_AT ones_NN2 from_II whom_PNQO Connectors_NN2 get_VV0 their_APPGE information_NN1 from_II ._. 
</s>
<s>
Mavens_NN2 are_VBR data_NN banks_NN2 ._. 
</s>
<s>
They_PPHS2 provide_VV0 the_AT message_NN1 ._. 
</s>
<s>
Connectors_NN2 are_VBR social_JJ glue_NN1 :_: they_PPHS2 spread_VV0 it_PPH1 ._. 
</s>
<s>
(_( Gladwell_VV0 2002:70_MC )_) ._. 
</s>
<s>
2.1.3_MC Salesmen_NN2 The_AT third_MD kinds_NN2 of_IO people_NN ,_, who_PNQS are_VBR important_JJ in_II the_AT Law_NN1 of_IO the_AT Few_DA2 ,_, are_VBR Salesmen_NN2 ._. 
</s>
<s>
These_DD2 people_NN step_VV0 in_II the_AT picture_NN1 when_CS we_PPIS2 feel_VV0 insecure_JJ about_II some_DD information_NN1 we_PPIS2 get_VV0 ._. 
</s>
<s>
Salesmen_NN2 persuade_VV0 us_PPIO2 into_II believing_VVG or_CC trying_VVG something_PN1 we_PPIS2 might_VM feel_VVI skeptical_JJ about_II at_RR21 first_RR22 ._. 
</s>
<s>
The_AT most_RGT important_JJ trait_NN1 that_CST a_AT1 Salesman_NN1 possesses_VVZ is_VBZ charisma_NN1 ._. 
</s>
<s>
A_ZZ1 Salespersons_NN2 charisma_NN1 is_VBZ more_DAR than_CSN the_AT ability_NN1 to_TO verbally_RR persuade_VVI ,_, his_APPGE or_CC her_APPGE facial_JJ expression_NN1 and_CC posture_NN1 when_CS talking_VVG to_II another_DD1 person_NN1 makes_VVZ people_NN want_VVI to_TO agree_VVI with_IW the_AT Salesman_NN1 ._. 
</s>
<s>
2.2_MC ._. 
</s>
<s>
The_AT Stickiness_NN1 Factor_NN1 The_AT second_MD rule_NN1 for_IF a_AT1 social_JJ epidemic_NN1 to_TO reach_VVI its_APPGE tipping_NN1 point_NN1 is_VBZ the_AT Stickiness_NN1 Factor_NN1 ._. 
</s>
<s>
According_II21 to_II22 this_DD1 rule_NN1 ,_, any_DD new_JJ product_NN1 ,_, advertisement_NN1 ,_, service_NN1 ,_, show_VV0 ,_, artist_NN1 ,_, etc._RA needs_NN2 to_TO have_VHI some_DD characteristics_NN2 that_CST makes_VVZ it_PPH1 stick_VVI like_II glue_NN1 to_II the_AT minds_NN2 of_IO people_NN ._. 
</s>
<s>
The_AT stickiness_NN1 factor_NN1 can_VM be_VBI ,_, for_REX21 instance_REX22 ,_, repetition_NN1 ,_, a_AT1 clue_NN1 to_II a_AT1 mystery_NN1 ,_, simple_JJ language_NN1 ,_, certain_JJ colors_NN2 ,_, or_CC almost_RR anything_PN1 if_CS used_VVN in_II the_AT proper_JJ way_NN1 ,_, depending_II21 on_II22 the_AT audience_NN1 and_CC in_II what_DDQ ways_NN2 something_PN1 is_VBZ wanted_VVN to_TO become_VVI sticky_JJ ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, the_AT Stickiness_NN1 Factor_NN1 is_VBZ something_PN1 that_CST gets_VVZ the_AT attention_NN1 of_IO the_AT target_NN1 group_NN1 for_IF a_AT1 longer_JJR period_NN1 of_IO time_NNT1 ._. 
</s>
<s>
2.3_MC The_AT Power_NN1 of_IO Context_NN1 The_AT third_MD rule_NN1 is_VBZ called_VVN the_AT Power_NN1 of_IO Context_NN1 ._. 
</s>
<s>
This_DD1 rule_NN1 suggests_VVZ that_CST a_AT1 sudden_JJ event_NN1 or_CC trend_NN1 that_CST tips_VVZ is_VBZ much_RR dependent_JJ on_II the_AT surrounding_JJ environment_NN1 ._. 
</s>
<s>
Epidemics_NN2 are_VBR sensitive_JJ to_II the_AT conditions_NN2 and_CC circumstances_NN2 of_IO the_AT times_NNT2 and_CC places_NN2 in_II which_DDQ they_PPHS2 occur_VV0 ._. 
</s>
<s>
(_( Gladwell_VV0 2002:139_MC )_) ._. 
</s>
<s>
An_AT1 example_NN1 from_II the_AT book_NN1 is_VBZ the_AT Broken_JJ Windows_NN2 theory_NN1 ,_, where_CS one_MC1 window_NN1 is_VBZ broken_VVN in_II a_AT1 city_NN1 and_CC no_PN121 one_PN122 repairs_VVZ it_PPH1 ._. 
</s>
<s>
People_NN start_VV0 to_TO think_VVI that_CST no_PN121 one_PN122 cares_VVZ and_CC no_PN121 one_PN122 is_VBZ in_II charge_NN1 ,_, and_CC soon_RR more_DAR windows_NN2 will_VM be_VBI broken_VVN and_CC the_AT feeling_NN1 that_CST you_PPY can_VM do_VDI anything_PN1 without_IW facing_VVG consequences_NN2 will_VM spread_VVI throughout_II the_AT city_NN1 ._. 
</s>
<s>
This_DD1 might_VM then_RT lead_VVI to_II anarchist_NN1 behavior_NN1 tipping_VVG and_CC criminal_JJ rates_NN2 increasing_VVG ._. 
</s>
<s>
(_( Gladwell_VV0 2002:141_MC )_) ._. 
</s>
<s>
In_II a_AT1 similar_JJ way_NN1 other_JJ events_NN2 can_VM become_VVI more_RGR common_JJ ,_, depending_II21 on_II22 the_AT environment_NN1 ._. 
</s>
<s>
3_MC Facebook_NP1 This_DD1 section_NN1 will_VM shortly_RR describe_VVI what_DDQ Facebook_NN1 is_VBZ ._. 
</s>
<s>
Facebook_NN1 is_VBZ a_AT1 social_JJ network_NN1 developed_VVD my_APPGE Mark_NP1 Zuckerberg_NP1 ._. 
</s>
<s>
Anyone_PN1 who_PNQS has_VHZ access_NN1 to_II the_AT Internet_NN1 can_VM join_VVI Facebook_NP1 ,_, it_PPH1 is_VBZ free_JJ of_IO charge_NN1 ._. 
</s>
<s>
(_( To_TO be_VBI continued_VVN .._... )_) 4_MC Methods_NN2 This_DD1 section_NN1 will_VM shortly_RR describe_VVI the_AT methods_NN2 used_VMK to_TO collect_VVI data_NN for_IF this_DD1 research_NN1 paper_NN1 ._. 
</s>
<s>
An_AT1 interview_NN1 will_VM be_VBI conducted_VVN to_II five_MC respondents_NN2 ._. 
</s>
<s>
The_AT respondents_NN2 have_VH0 been_VBN chosen_VVN according_II21 to_II22 the_AT assumption_NN1 that_CST they_PPHS2 are_VBR familiar_JJ with_IW Facebook_NP1 and_CC that_CST they_PPHS2 are_VBR possible_JJ users_NN2 to_TO get_VVI an_AT1 understanding_NN1 of_IO the_AT phenomenon_NN1 from_II the_AT point_NN1 of_IO view_NN1 of_IO users_NN2 ._. 
</s>
<s>
Three_MC respondents_NN2 were_VBDR males_NN2 and_CC two_MC respondents_NN2 were_VBDR females_NN2 in_BCL21 order_BCL22 to_TO see_VVI if_CSW there_EX were_VBDR any_DD differences_NN2 between_II the_AT genders_NN2 ._. 
</s>
<s>
The_AT interview_NN1 guide_NN1 can_VM be_VBI found_VVN in_II Appendix_NN1 1_MC1 ._. 
</s>
<s>
5_MC Results_NN2 In_II this_DD1 section_NN1 the_AT results_NN2 from_II the_AT interviews_NN2 will_VM be_VBI discussed_VVN ._. 
</s>
<s>
The_AT results_NN2 from_II the_AT interviews_NN2 will_VM be_VBI evaluated_VVN using_VVG Gladwells_NN2 three_MC rules_NN2 (_( the_AT Law_NN1 of_IO the_AT Few_DA2 ,_, the_AT Stickiness_NN1 Factor_NN1 ,_, the_AT Power_NN1 of_IO Context_NN1 )_) ,_, and_CC to_II what_DDQ extent_NN1 they_PPHS2 are_VBR applicable_JJ ._. 
</s>
<s>
The_AT results_NN2 from_II the_AT interviews_NN2 were_VBDR similar_JJ to_II each_PPX221 other_PPX222 ;_; there_EX were_VBDR not_XX a_AT1 wide_JJ range_NN1 of_IO different_JJ answers_NN2 ._. 
</s>
<s>
All_DB respondents_NN2 are_VBR users_NN2 of_IO Facebook_NP1 and_CC all_DB of_IO them_PPHO2 log_NN1 in_II daily_JJ ._. 
</s>
<s>
The_AT reasons_NN2 for_IF joining_VVG Facebook_NP1 were_VBDR similar_JJ for_IF almost_RR all_DB respondents_NN2 :_: everyone_PN1 had_VHD joined_VVN because_CS other_JJ friends_NN2 were_VBDR on_II Facebook_NP1 ._. 
</s>
<s>
All_DB respondents_NN2 had_VHD heard_VVN about_II Facebook_NP1 from_II friends_NN2 or_CC relatives_NN2 ,_, through_II word-of-mouth_NN1 ._. 
</s>
<s>
One_MC1 respondent_NN1 had_VHD heard_VVN about_II Facebook_NP1 from_II friends_NN2 who_PNQS used_VVD MySpace_NP1 (_( a_AT1 social_JJ network_NN1 as_RR21 well_RR22 )_) ,_, and_CC one_MC1 male_JJ respondent_NN1 said_VVD he_PPHS1 had_VHD heard_VVN about_II Facebook_NP1 from_II his_APPGE brother_NN1 who_PNQS used_VMK to_TO study_VVI computer_NN1 engineering_NN1 ._. 
</s>
<s>
This_DD1 respondent_NN1 said_VVD he_PPHS1 was_VBDZ one_MC1 of_IO the_AT first_MD ones_NN2 of_IO his_APPGE friends_NN2 to_TO join_VVI the_AT social_JJ network_NN1 ,_, and_CC he_PPHS1 was_VBDZ the_AT one_PN1 who_PNQS suggested_VVD it_PPH1 to_II his_APPGE friends_NN2 ._. 
</s>
<s>
Reasons_NN2 to_TO be_VBI on_II Facebook_NP1 were_VBDR also_RR quite_RG similar_JJ to_II each_PPX221 other_PPX222 :_: all_DB respondents_NN2 also_RR said_VVD they_PPHS2 were_VBDR on_II Facebook_NP1 in_II order_NN1 to_TO easily_RR connect_VVI with_IW other_JJ friends_NN2 ._. 
</s>
<s>
One_MC1 male_JJ respondent_NN1 also_RR said_VVD that_CST one_MC1 of_IO his_APPGE main_JJ reasons_NN2 for_IF joining_VVG and_CC being_VBG on_II Facebook_NP1 is_VBZ because_CS it_PPH1 is_VBZ an_AT1 efficient_JJ tool_NN1 for_IF the_AT promotion_NN1 of_IO his_APPGE companies_NN2 ._. 
</s>
<s>
Other_JJ reasons_NN2 to_TO be_VBI on_II Facebook_NP1 were_VBDR ,_, for_REX21 instance_REX22 ,_, to_TO look_VVI at_II pictures_NN2 ,_, follow_VV0 parties_NN2 and_CC events_NN2 (_( get_VV0 invitations_NN2 )_) ,_, follow_VV0 the_AT newsfeed_NN1 ,_, kill_VV0 time_NNT1 ,_, follow_VV0 what_DDQ friends_NN2 are_VBR up_II21 to_II22 ,_, stalk_VV0 peoples_NN2 lives_NN2 ,_, good_JJ entertainment_NN1 ,_, networking_VVG and_CC searching_VVG for_IF information_NN1 about_II people_NN ,_, and_CC chatting_VVG ._. 
</s>
<s>
Most_DAT respondents_NN2 said_VVD they_PPHS2 are_VBR hooked_VVN on_II Facebook_NP1 ,_, only_RR one_MC1 male_JJ respondent_NN1 said_VVD he_PPHS1 was_VBDZ not_XX ._. 
</s>
<s>
The_AT reasons_NN2 for_IF being_VBG hooked_VVN on_II the_AT social_JJ network_NN1 were_VBDR much_RR the_AT same_DA as_CSA the_AT reasons_NN2 for_IF being_VBG on_II Facebook_NP1 :_: looking_VVG at_II pictures_NN2 ,_, staying_VVG connected_JJ with_IW friends_NN2 ,_, and_CC following_VVG other_JJ peoples_NN2 lives_NN2 and_CC events_NN2 ._. 
</s>
<s>
One_MC1 female_JJ respondent_NN1 said_VVD she_PPHS1 is_VBZ hooked_VVN on_II Facebook_NP1 because_CS she_PPHS1 is_VBZ curious_JJ to_TO see_VVI what_DDQ is_VBZ going_VVG on_RP in_II her_APPGE friends_NN2 lives_NN2 ._. 
</s>
<s>
None_PN of_IO the_AT respondents_NN2 said_VVD they_PPHS2 were_VBDR hooked_VVN on_II games_NN2 or_CC other_JJ applications_NN2 than_CSN the_AT chat_NN1 ._. 
</s>
<s>
One_MC1 male_NN1 and_CC one_MC1 female_JJ respondent_NN1 said_VVD that_CST they_PPHS2 have_VH0 become_VVN hooked_VVN on_II Facebook_NP1 after_CS they_PPHS2 got_VVD Iphones_NP1 since_CS they_PPHS2 log_VV0 in_II more_RGR often_RR ._. 
</s>
<s>
It_PPH1 has_VHZ become_VVN a_AT1 habit_NN1 because_CS it_PPH1 is_VBZ very_RG easy_JJ to_TO log_VVI in_RP ._. 
</s>
<s>
The_AT female_JJ respondent_NN1 said_VVD that_CST she_PPHS1 logs_VVZ in_RP when_CS walking_VVG to_II the_AT University_NN1 ,_, when_CS sitting_VVG in_II the_AT tram_NN1 ,_, during_II lectures_NN2 ,_, and_CC in_II other_JJ places_NN2 as_RR21 well_RR22 ._. 
</s>
<s>
The_AT attitudes_NN2 towards_II Facebook_NP1 in_II the_AT beginning_NN1 when_CS the_AT respondents_NN2 first_MD heard_VVN of_IO it_PPH1 were_VBDR somewhat_RR differing_VVG ._. 
</s>
<s>
Three_MC respondents_NN2 thought_VVD it_PPH1 was_VBDZ interesting_JJ concept_NN1 and_CC wanted_VVD to_TO try_VVI it_PPH1 because_CS it_PPH1 was_VBDZ something_PN1 new_JJ to_II them_PPHO2 ._. 
</s>
<s>
One_MC1 respondent_NN1 ,_, who_PNQS was_VBDZ a_AT1 user_NN1 of_IO MySpace_NP1 at_II the_AT time_NNT1 ,_, thought_VVD that_DD1 Facebook_NN1 would_VM be_VBI one_MC1 of_IO those_DD2 networks_NN2 again_RT ,_, and_CC was_VBDZ skeptical_JJ about_II its_APPGE functionality_NN1 ._. 
</s>
<s>
One_MC1 male_JJ respondent_NN1 did_VDD not_XX want_VVI to_TO join_VVI Facebook_NN1 because_CS everyone_PN1 joined_VVD it_PPH1 and_CC hyped_VVD about_II it_PPH1 ;_; he_PPHS1 said_VVD he_PPHS1 boycotted_VVD the_AT network_NN1 at_RR21 first_RR22 ._. 
</s>
<s>
However_RR ,_, the_AT attitudes_NN2 towards_II Facebook_NP1 have_VH0 changed_VVN over_II time_NNT1 ._. 
</s>
<s>
Most_DAT respondents_NN2 said_VVD they_PPHS2 see_VV0 the_AT network_NN1 now_RT as_II a_AT1 useful_JJ tool_NN1 to_TO stay_VVI connected_JJ and_CC informed_VVN about_II events_NN2 ._. 
</s>
<s>
One_MC1 female_JJ respondent_NN1 ,_, who_PNQS at_RR21 first_RR22 thought_VVN that_CST Facebook_NP1 was_VBDZ very_RG exciting_JJ and_CC interesting_JJ ,_, thought_VVD that_CST Facebook_NP1 has_VHZ become_VVN useless_JJ for_IF her_PPHO1 because_CS she_PPHS1 only_RR looks_VVZ at_II pictures_NN2 and_CC she_PPHS1 does_VDZ not_XX like_VVI the_AT fact_NN1 that_CST it_PPH1 is_VBZ a_AT1 competition_NN1 of_IO who_PNQS has_VHZ the_AT most_DAT friends_NN2 ._. 
</s>
<s>
Another_DD1 female_JJ respondent_NN1 ,_, who_PNQS thought_VVD of_IO Facebook_NP1 still_RR as_II a_AT1 useful_JJ tool_NN1 to_TO stay_VVI connected_JJ ,_, did_VDD not_XX like_VVI the_AT fact_NN1 that_CST the_AT network_NN1 has_VHZ become_VVN very_RG public_JJ and_CC people_NN whom_PNQO you_PPY do_VD0 not_XX even_RR know_VVI can_VM like_VVI pictures_NN2 of_IO you_PPY (_( if_CS they_PPHS2 are_VBR friends_NN2 with_IW other_JJ people_NN who_PNQS are_VBR in_II the_AT same_DA pictures_NN2 with_IW you_PPY )_) ._. 
</s>
<s>
The_AT results_NN2 indicate_VV0 that_CST The_AT Law_NN1 of_IO the_AT Few_DA2 does_VDZ apply_VVI for_IF Facebook_NN1 to_II a_AT1 certain_JJ degree_NN1 ._. 
</s>
<s>
All_DB respondents_NN2 had_VHD heard_VVN about_II the_AT network_NN1 from_II someone_PN1 else_RR ._. 
</s>
<s>
In_II most_DAT cases_NN2 the_AT respondents_NN2 seemed_VVD to_TO have_VHI heard_VVN from_II their_APPGE friends_NN2 ,_, possible_JJ Connectors_NN2 ._. 
</s>
<s>
Two_MC male_JJ respondents_NN2 had_VHD heard_VVN about_II the_AT network_NN1 from_II possible_JJ Mavens_NN2 ;_; one_MC1 Maven_NN1 being_VBG the_AT brother_NN1 who_PNQS studied_VVD computer_NN1 engineering_NN1 and_CC the_AT other_JJ Mavens_NN2 being_VBG friends_NN2 who_PNQS used_VVD MySpace_NP1 before_CS anyone_PN1 had_VHD ever_RR heard_VVN of_IO it_PPH1 or_CC Facebook_NP1 ._. 
</s>
<s>
They_PPHS2 seemed_VVD to_TO be_VBI some_DD sort_NN1 of_IO experts_NN2 within_II the_AT field_NN1 of_IO computers_NN2 and_CC social_JJ networks_NN2 ._. 
</s>
<s>
However_RR ,_, there_EX seemed_VVD to_TO be_VBI little_JJ indication_NN1 from_II the_AT interviews_NN2 that_CST Salesmen_NN2 existed_VVD ._. 
</s>
<s>
Possible_JJ Salesmen_NN2 might_VM have_VHI been_VBN the_AT few_DA2 friends_NN2 that_CST talked_VVD over_RP one_MC1 male_JJ respondent_NN1 who_PNQS was_VBDZ unwilling_JJ to_TO join_VVI Facebook_NP1 at_RR21 first_RR22 ._. 
</s>
<s>
The_AT results_NN2 indicate_VV0 that_CST Facebook_NP1 has_VHZ a_AT1 clear_JJ Stickiness_NN1 Factor_NN1 ,_, which_DDQ is_VBZ the_AT fact_NN1 that_CST the_AT respondents_NN2 can_VM follow_VVI their_APPGE friends_NN2 lives_NN2 ._. 
</s>
<s>
Curiosity_NN1 seems_VVZ to_TO be_VBI the_AT weakness_NN1 of_IO people_NN that_CST makes_VVZ Facebook_NN1 so_RG sticky_JJ ._. 
</s>
<s>
All_DB respondents_NN2 said_VVD that_CST they_PPHS2 scroll_VV0 down_RP the_AT newsfeed_NN1 every_AT1 time_NNT1 that_CST they_PPHS2 log_VV0 into_II Facebook_NP1 ,_, and_CC most_DAT respondents_NN2 also_RR said_VVD they_PPHS2 look_VV0 at_II friends_NN2 pictures_NN2 ._. 
</s>
<s>
(_( To_TO be_VBI continued_VVN )_) 6_MC Discussion_NN1 In_II this_DD1 section_NN1 a_AT1 discussion_NN1 will_VM take_VVI place_NN1 ._. 
</s>
<s>
7_MC Conclusion_NN1 
</s>
