<s>
Does_VDZ familiarity_NN1 with_IW internal_JJ controls_NN2 make_VV0 internal_JJ auditors_NN2 experts_NN2 in_II risk_NN1 management_NN1 Introduction_NN1 Internal_JJ auditing_NN1 has_VHZ come_VVN a_AT1 long_JJ way_NN1 from_II being_VBG a_AT1 clerical_JJ service_NN1 function_NN1 and_CC monitoring_VVG activities_NN2 to_II being_VBG an_AT1 assurance_NN1 and_CC consultative_JJ function_NN1 that_CST is_VBZ involved_JJ in_II a_AT1 wide_JJ range_NN1 of_IO services_NN2 (_( Moeller_NP1 ,_, 2009_MC ,_, pp.11-14_MC )_) ._. 
</s>
<s>
According_II21 to_II22 the_AT Institute_NN1 of_IO Internal_JJ Auditors_NN2 (_( IIA_NP1 )_) ,_, 2010_MC )_) ,_, internal_JJ auditors_NN2 have_VH0 an_AT1 in-depth_JJ understanding_NN1 of_IO the_AT business_NN1 culture_NN1 ,_, systems_NN2 ,_, and_CC processes_NN2 of_IO the_AT organisations_NN2 they_PPHS2 are_VBR working_VVG for_IF ._. 
</s>
<s>
This_DD1 knowledge_NN1 stems_VVZ from_II the_AT wide_JJ ranging_JJ activities_NN2 they_PPHS2 perform_VV0 for_IF their_APPGE organisations_NN2 (_( Moeller_NP1 ,_, 2009_MC ,_, pp.11-14_MC )_) ._. 
</s>
<s>
The_AT IIA_NP1 also_RR asserts_VVZ that_CST the_AT internal_JJ audit_NN1 function_NN1 provides_VVZ assurance_NN1 that_CST internal_JJ controls_NN2 in_II place_NN1 are_VBR adequate_JJ to_TO mitigate_VVI risks_NN2 ,_, governance_NN1 processes_NN2 are_VBR effective_JJ and_CC efficient_JJ ,_, and_CC organizational_JJ goals_NN2 and_CC objectives_NN2 are_VBR met_VVN ._. 
</s>
<s>
They_PPHS2 in_II effect_NN1 assess_VV0 and_CC evaluate_VV0 the_AT systems_NN2 designed_VVN and_CC implemented_VVN by_II management_NN1 ._. 
</s>
<s>
This_DD1 assurance_NN1 service_NN1 calls_VVZ for_IF professional_JJ judgment_NN1 from_II internal_JJ auditors_NN2 which_DDQ is_VBZ reported_VVN to_II the_AT board_NN1 of_IO directors_NN2 through_II an_AT1 independent_JJ audit_NN1 committee_NN1 (_( Moeller_NP1 ,_, 2009_MC ;_; Spira_NP1 and_CC Page_NN1 ,_, 2003_MC ;_; BPP_NP1 Publishing_NN1 ,_, 2005_MC )_) ._. 
</s>
<s>
A_AT1 survey_NN1 by_II Leung_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2003_MC )_) found_VVD that_CST the_AT role_NN1 of_IO the_AT internal_JJ audit_NN1 activity_NN1 revolved_VVD around_RP internal_JJ controls_NN2 ,_, risks_NN2 and_CC compliance_NN1 with_IW corporate_JJ governance_NN1 requirements_NN2 ._. 
</s>
<s>
Another_DD1 key_JJ finding_NN1 was_VBDZ that_DD1 internal_JJ auditors_NN2 also_RR reported_VVD having_VHG access_NN1 to_II the_AT board_NN1 and_CC the_AT audit_NN1 committee_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ significant_JJ because_CS senior_JJ management_NN1 is_VBZ accountable_JJ to_II the_AT board_NN1 and_CC the_AT internal_JJ audit_NN1 function_NN1 can_VM only_RR be_VBI effective_JJ in_II adding_VVG value_NN1 if_CS management_NN1 adopts_VVZ their_APPGE recommendations_NN2 ._. 
</s>
<s>
The_AT internal_JJ audit_NN1 function_NN1 is_VBZ itself_PPX1 an_AT1 internal_JJ control_NN1 system_NN1 put_VVN in_II place_NN1 by_II management_NN1 to_TO ensure_VVI that_DD1 management_NN1 control_NN1 systems_NN2 are_VBR running_VVG effectively_RR and_CC efficiently_RR ,_, to_TO safeguard_VVI the_AT assets_NN2 of_IO the_AT company_NN1 and_CC to_TO be_VBI a_AT1 deterrent_NN1 to_II fraud_NN1 (_( BPP_NP1 Publishing_NN1 ,_, 2005_MC )_) ._. 
</s>
<s>
It_PPH1 is_VBZ also_RR required_VVN to_TO serve_VVI as_II a_AT1 watchdog_NN1 gauging_VVG and_CC reporting_VVG on_II any_DD significant_JJ risks_NN2 and_CC loopholes_NN2 in_II the_AT control_NN1 environment_NN1 that_CST will_VM have_VHI a_AT1 negative_JJ impact_NN1 in_II achieving_VVG the_AT organisations_NN2 objectives_NN2 (_( Moeller_NP1 ,_, 2009_MC )_) ._. 
</s>
<s>
Implementing_VVG a_AT1 strong_JJ internal_JJ control_NN1 is_VBZ important_JJ because_CS one_MC1 of_IO the_AT reasons_NN2 advanced_VVN for_IF the_AT failures_NN2 of_IO giants_NN2 like_II Enron_NP1 and_CC WorldCom_NP1 was_VBDZ the_AT absence_NN1 or_CC abuse_NN1 of_IO their_APPGE internal_JJ control_NN1 systems_NN2 (_( Verschoor_NP1 ,_, 2002_MC )_) ._. 
</s>
<s>
Link_VV0 auditors_NN2 to_TO risk_VVI management_NN1 and_CC focus_VVI on_II significance_NN1 of_IO risk_NN1 management_NN1 Internal_JJ auditing_NN1 is_VBZ a_AT1 component_NN1 of_IO a_AT1 good_JJ internal_JJ control_NN1 system_NN1 (_( Spira_NP1 and_CC Page_NN1 ,_, 2003_MC )_) The_AT significance_NN1 of_IO the_AT Internal_JJ controls_NN2 system_NN1 Following_VVG the_AT demise_NN1 of_IO many_DA2 large_JJ corporate_JJ giants_NN2 ,_, regulators_NN2 have_VH0 sponsored_VVN research_NN1 such_II21 as_II22 the_AT Turnbull_NP1 report_NN1 in_II the_AT UK_NP1 ,_, COSO_NP1 in_II the_AT US_NP1 ,_, the_AT King_NN1 report_NN1 in_II South_NP1 Africa_NP1 etc_RA ._. 
</s>
<s>
The_AT objective_NN1 of_IO these_DD2 reports_NN2 has_VHZ being_NN1 to_TO recommend_VVI a_AT1 conceptual_JJ framework_NN1 for_IF implementing_VVG a_AT1 sound_NN1 system_NN1 of_IO internal_JJ control_NN1 ._. 
</s>
<s>
The_AT collapse_NN1 of_IO Enron_NP1 ,_, WorldCom_NP1 ,_, etc_RA has_VHZ being_VBG blamed_VVN on_II the_AT absence_NN1 or_CC lack_NN1 of_IO an_AT1 effective_JJ system_NN1 of_IO control_NN1 (_( Zhou_NP1 and_CC Zhou_NP1 ,_, 2007_MC )_) ._. 
</s>
<s>
The_AT Committee_NN1 of_IO Sponsoring_VVG Organisations_NN2 (_( COSO_NP1 )_) has_VHZ the_AT most_RGT widely_RR used_VVN and_CC recognised_JJ definition_NN1 of_IO internal_JJ controls_NN2 ._. 
</s>
<s>
COSO_NP1 (_( 1992_MC )_) ,_, defines_VVZ internal_JJ control_NN1 as_II ;_; ..._... a_AT1 process_NN1 ,_, affected_VVN by_II an_AT1 entitys_NN2 board_NN1 of_IO directors_NN2 ,_, management_NN1 ,_, and_CC other_JJ personnel_NN2 ,_, designed_VVN to_TO provide_VVI reasonable_JJ assurance_NN1 regarding_II the_AT achievement_NN1 of_IO objectives_NN2 in_II the_AT following_JJ categories_NN2 :_: effectiveness_NN1 and_CC efficiency_NN1 of_IO operations_NN2 ;_; reliability_NN1 of_IO financial_JJ reporting_NN1 and_CC compliance_NN1 with_IW applicable_JJ laws_NN2 and_CC regulations_NN2 The_AT internal_JJ control_NN1 system_NN1 is_VBZ the_AT responsibility_NN1 of_IO management_NN1 (_( Krishnan_NP1 ,_, 2005_MC )_) ._. 
</s>
<s>
A_AT1 sound_JJ internal_JJ control_NN1 system_NN1 will_VM provide_VVI management_NN1 with_IW reasonable_JJ assurance_NN1 that_CST its_APPGE corporate_JJ objectives_NN2 are_VBR being_VBG met_VVN (_( office_NN1 of_IO Audit_NN1 and_CC Compliance_NN1 Review_NN1 )_) ._. 
</s>
<s>
It_PPH1 is_VBZ also_RR a_AT1 key_JJ factor_NN1 in_II the_AT production_NN1 of_IO quality_NN1 financial_JJ reports_NN2 (_( Krishnan_NP1 ,_, 2005_MC )_) ._. 
</s>
<s>
It_PPH1 serves_VVZ as_II a_AT1 deterrent_NN1 to_II fraud_NN1 and_CC misstatements_NN2 in_II the_AT financial_JJ reports_NN2 and_CC is_VBZ crucial_JJ in_II promoting_VVG corporate_JJ governance_NN1 (_( Spira_NP1 and_CC Page_NN1 ,_, 2003_MC )_) ._. 
</s>
<s>
The_AT Combined_JJ Code_NN1 stated_VVD that_CST companies_NN2 without_IW an_AT1 internal_JJ audit_NN1 department_NN1 should_VM annually_RR review_VVI the_AT need_NN1 for_IF one_MC1 (_( p.36_FO )_) ._. 
</s>
<s>
According_II21 to_II22 Jan_NPM1 (_( 2005_MC )_) ,_, the_AT internal_JJ audit_NN1 function_NN1 serves_VVZ as_II an_AT1 enabler_NN1 of_IO corporate_JJ governance_NN1 ._. 
</s>
<s>
The_AT report_NN1 by_II the_AT Cadbury_NP1 Committee_NN1 (_( 1992_MC ,_, 4.32_MC )_) recommended_VVD that_DD1 ;_; directors_NN2 should_VM make_VVI a_AT1 statement_NN1 in_II the_AT report_NN1 and_CC accounts_NN2 on_II the_AT effectiveness_NN1 of_IO their_APPGE system_NN1 of_IO internal_JJ control_NN1 and_CC that_CST the_AT auditors_NN2 should_VM report_VVI thereon_RR ._. 
</s>
<s>
The_AT committee_NN1 asserts_VVZ that_CST a_AT1 sound_NN1 system_NN1 of_IO internal_JJ control_NN1 will_VM enhance_VVI and_CC protect_VVI stakeholder_NN1 value_NN1 ._. 
</s>
<s>
COSO_NP1 (_( 2010_MC )_) also_RR believes_VVZ that_CST such_DA a_AT1 system_NN1 will_VM result_VVI in_II increased_JJ profitability_NN1 and_CC reduction_NN1 in_II unwanted_JJ risks_NN2 and_CC surprises_NN2 ._. 
</s>
<s>
A_AT1 good_JJ internal_JJ control_NN1 system_NN1 depends_VVZ on_II the_AT control_NN1 environment_NN1 (_( Krishnan_NP1 ,_, 2005_MC )_) ._. 
</s>
<s>
A_AT1 strong_JJ control_NN1 environment_NN1 is_VBZ the_AT overall_JJ attitude_NN1 ,_, awareness_NN1 and_CC actions_NN2 of_IO directors_NN2 and_CC managers_NN2 regarding_II internal_JJ controls_NN2 and_CC their_APPGE importance_NN1 to_II the_AT entity_NN1 ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, it_PPH1 is_VBZ the_AT tone_NN1 from_II the_AT top_NN1 because_CS it_PPH1 is_VBZ affected_VVN by_II the_AT actions_NN2 of_IO management_NN1 such_II21 as_II22 management_NN1 style_NN1 and_CC philosophy_NN1 ,_, organisational_JJ culture_NN1 ,_, segregation_NN1 of_IO duties_NN2 (_( BPP_NP1 Publishing_NN1 ,_, 2005_MC )_) ._. 
</s>
<s>
Management_NN1 is_VBZ accountable_JJ to_II the_AT board_NN1 of_IO directors_NN2 and_CC audit_NN1 committees_NN2 for_IF the_AT internal_JJ control_NN1 system_NN1 ._. 
</s>
<s>
There_EX have_VH0 being_NN1 calls_VVZ from_II regulators_NN2 ,_, professionals_NN2 and_CC academics_NN2 for_IF audit_NN1 committees_NN2 to_TO review_VVI and_CC monitor_VVI the_AT internal_JJ control_NN1 environment_NN1 (_( Krishnan_NP1 ,_, 2005_MC )_) ._. 
</s>
<s>
Krishnan_NP1 (_( 2005_MC )_) investigated_VVD the_AT quality_NN1 of_IO audit_NN1 committees_NN2 and_CC internal_JJ controls_NN2 in_II the_AT US_NP1 and_CC found_VVD that_CST companies_NN2 with_IW independent_JJ audit_NN1 committees_NN2 where_CS at_RR21 least_RR22 one_MC1 member_NN1 had_VHD a_AT1 financial_JJ background_NN1 suffered_VVD less_RGR internal_JJ control_NN1 setbacks_NN2 ._. 
</s>
<s>
Internal_JJ control_NN1 deficiencies_NN2 are_VBR also_RR common_JJ among_II firms_NN2 that_CST are_VBR small_JJ ,_, younger_JJR ,_, and_CC lack_VV0 an_AT1 internal_JJ audit_NN1 department_NN1 (_( Ge_NP1 and_CC McVay_NP1 ,_, 2005_MC ;_; Doyle_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2005_MC ;_; Doyle_NP1 and_CC McVay_NP1 ,_, 2007_MC )_) ._. 
</s>
<s>
One_MC1 of_IO the_AT reasons_NN2 cited_VVN for_IF the_AT failure_NN1 of_IO Enron_NP1 was_VBDZ its_APPGE lack_NN1 of_IO a_AT1 good_JJ internal_JJ control_NN1 system_NN1 (_( Verschoor_NP1 2002_MC )_) ._. 
</s>
<s>
Ashbaugh-Skaife_NP1 et_RA21 al._RA22 (_( )_) also_RR found_VVN that_CST firms_NN2 that_CST invested_VVD less_DAR resources_NN2 in_II their_APPGE internal_JJ control_NN1 experienced_VVD more_DAR problems_NN2 with_IW their_APPGE systems_NN2 ._. 
</s>
<s>
Other_JJ studies_NN2 in_II this_DD1 area_NN1 have_VH0 looked_VVN at_II impact_NN1 that_CST a_AT1 sound_NN1 system_NN1 of_IO internal_JJ control_NN1 has_VHZ on_II stakeholder_NN1 value_NN1 ._. 
</s>
<s>
Jacqueline_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2008_MC )_) found_VVD that_CST investors_NN2 used_JJ information_NN1 about_II a_AT1 companys_NN2 internal_JJ control_NN1 such_II21 as_II22 the_AT effectiveness_NN1 of_IO the_AT system_NN1 ,_, and_CC its_APPGE integrity_NN1 when_CS deciding_VVG to_TO invest_VVI in_II that_DD1 company_NN1 ._. 
</s>
<s>
The_AT authors_NN2 also_RR report_VV0 that_DD1 policy_NN1 makers_NN2 want_VV0 investors_NN2 to_TO be_VBI aware_JJ that_CST deficiencies_NN2 in_II a_AT1 companys_NN2 internal_JJ control_NN1 system_NN1 is_VBZ an_AT1 indication_NN1 that_CST future_JJ financial_JJ reports_NN2 will_VM be_VBI misstated_VVN and_CC misleading_JJ ._. 
</s>
<s>
There_EX has_VHZ being_VBG a_AT1 consensus_NN1 finding_VVG that_CST a_AT1 firm_NN1 that_CST reports_VVZ a_AT1 weakness_NN1 in_II its_APPGE internal_JJ control_NN1 system_NN1 will_VM suffer_VVI a_AT1 negative_JJ return_NN1 from_II investors_NN2 (_( Beneish_NN1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2008_MC )_) ;_; Ge_NP1 and_CC mcVay_NN1 (_( 2005_MC )_) ;_; Jacqueline_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2008_MC )_) )_) ._. 
</s>
<s>
One_MC1 other_JJ major_JJ finding_NN1 registered_VVN by_II some_DD of_IO the_AT researchers_NN2 already_RR mentioned_VVN above_RL is_VBZ that_DD1 audit_NN1 committee_NN1 independence_NN1 is_VBZ a_AT1 strong_JJ indicator_NN1 of_IO a_AT1 sound_JJ internal_JJ control_NN1 system_NN1 ._. 
</s>
<s>
The_AT audit_NN1 committee_NN1 therefore_RR acts_VVZ on_II31 behalf_II32 of_II33 the_AT board_NN1 to_TO ensure_VVI that_CST the_AT internal_JJ control_NN1 system_NN1 put_VVN in_II place_NN1 by_II management_NN1 is_VBZ sound_JJ and_CC effective_JJ in_II meeting_VVG corporate_JJ objectives_NN2 ._. 
</s>
<s>
The_AT audit_NN1 committee_NN1 delegates_NN2 this_DD1 responsibility_NN1 to_II the_AT internal_JJ auditors_NN2 ._. 
</s>
<s>
The_AT job_NN1 entails_VVZ reviewing_VVG ;_; ..._... all_DB the_AT policies_NN2 and_CC procedures_NN2 (_( internal_JJ controls_NN2 )_) adopted_VVN by_II the_AT directors_NN2 ..._... of_IO an_AT1 entity_NN1 to_TO ensure_VVI ,_, as_CS31 far_CS32 as_CS33 practicable_JJ ,_, the_AT orderly_JJ and_CC efficient_JJ conduct_NN1 of_IO its_APPGE business_NN1 ,_, including_II adherence_NN1 to_II internal_JJ policies_NN2 ,_, the_AT safeguarding_NN1 of_IO assets_NN2 ,_, the_AT prevention_NN1 and_CC detection_NN1 of_IO fraud_NN1 and_CC error_NN1 ,_, the_AT accuracy_NN1 and_CC completeness_NN1 of_IO financial_JJ records_NN2 ,_, and_CC the_AT timely_JJ preparation_NN1 of_IO reliable_JJ financial_JJ information_NN1 ..._... 
</s>
<s>
(_( BPP_NP1 Publishing_NN1 ,_, 2005_MC )_) ._. 
</s>
<s>
Internal_JJ auditors_NN2 are_VBR therefore_RR assisting_VVG management_NN1 to_TO successfully_RR carryout_VVI their_APPGE tasks_NN2 ._. 
</s>
<s>
They_PPHS2 also_RR provide_VV0 reasonable_JJ assurance_NN1 to_II management_NN1 as_II21 to_II22 the_AT adequacy_NN1 ,_, sufficiency_NN1 ,_, integrity_NN1 and_CC reliability_NN1 of_IO the_AT internal_JJ control_NN1 system_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ achieved_VVN by_II continuous_JJ testing_NN1 ,_, assessment_NN1 ,_, monitoring_VVG and_CC evaluation_NN1 of_IO the_AT system_NN1 (_( Fadzil_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2005_MC )_) ._. 
</s>
<s>
According_II21 to_II22 Sawyer_NP1 and_CC Vinten_NP1 (_( 1996_MC )_) ,_, internal_JJ auditors_NN2 provide_VV0 a_AT1 better_JJR foundation_NN1 for_IF management_NN1 judgments_NN2 through_II better_JJR quality_NN1 information_NN1 which_DDQ is_VBZ timely_JJ ,_, reliable_JJ and_CC significant_JJ to_II both_DB2 strategic_JJ and_CC operational_JJ decision-making_NN1 ._. 
</s>
<s>
They_PPHS2 can_VM accomplish_VVI this_DD1 task_NN1 and_CC add_VVI value_NN1 to_II their_APPGE organisations_NN2 because_CS they_PPHS2 have_VH0 a_AT1 more_RGR thorough_JJ understanding_NN1 of_IO the_AT organisational_JJ units_NN2 than_CSN anyone_PN1 else_RR (_( Spira_NP1 and_CC Page_NN1 ,_, 2003_MC )_) ._. 
</s>
<s>
Internal_JJ auditing_NN1 Over_II the_AT last_MD couple_NN1 of_IO years_NNT2 ,_, the_AT internal_JJ auditing_NN1 function_NN1 has_VHZ evolved_VVN from_II an_AT1 entirely_RR monitoring_VVG role_NN1 that_CST focuses_VVZ primarily_RR on_II reporting_VVG to_II management_NN1 and_CC the_AT directors_NN2 on_II the_AT adequacy_NN1 and_CC effectiveness_NN1 of_IO components_NN2 of_IO the_AT accounting_NN1 and_CC internal_JJ control_NN1 systems_NN2 (_( BPP_NP1 Publishing_NN1 ,_, 2005_MC )_) ._. 
</s>
<s>
As_CSA defined_VVN by_II the_AT Chartered_JJ Institute_NN1 of_IO Internal_JJ Auditors_NN2 (_( IIA_NP1 )_) UK_NP1 ,_, that_DD1 role_NN1 has_VHZ changed_VVN and_CC internal_JJ auditors_NN2 now_RT have_VH0 more_DAR responsibility_NN1 and_CC scope_NN1 to_TO make_VVI an_AT1 impact_NN1 on_II shareholder_NN1 value_NN1 within_II an_AT1 organisation_NN1 ._. 
</s>
<s>
The_AT Chartered_JJ Institute_NN1 of_IO Internal_JJ Auditors_NN2 UK_NP1 defines_VVZ internal_JJ auditing_NN1 as_CSA follows_VVZ ;_; Internal_JJ auditing_NN1 is_VBZ an_AT1 independent_JJ ,_, objective_JJ assurance_NN1 and_CC consulting_JJ activity_NN1 designed_VVN to_TO add_VVI value_NN1 and_CC improve_VVI an_AT1 organization_NN1 's_GE operations_NN2 ._. 
</s>
<s>
It_PPH1 helps_VVZ an_AT1 organization_NN1 accomplish_VVI its_APPGE objectives_NN2 by_II bringing_VVG a_AT1 systematic_JJ ,_, disciplined_JJ approach_NN1 to_TO evaluate_VVI and_CC improve_VVI the_AT effectiveness_NN1 of_IO risk_NN1 management_NN1 ,_, control_NN1 ,_, and_CC governance_NN1 processes_NN2 ._. 
</s>
<s>
The_AT definition_NN1 considers_VVZ the_AT work_NN1 of_IO internal_JJ auditors_NN2 to_TO be_VBI independent_JJ even_CS21 though_CS22 they_PPHS2 are_VBR employed_VVN by_II management_NN1 ,_, to_TO perform_VVI tasks_NN2 assigned_VVN to_II them_PPHO2 by_II management_NN1 and_CC can_VM be_VBI dismissed_VVN by_II management_NN1 ._. 
</s>
<s>
One_MC1 reason_NN1 is_VBZ that_CST most_DAT internal_JJ auditors_NN2 today_RT are_VBR trained_VVN and_CC professionally_RR qualified_VVN ._. 
</s>
<s>
Research_NN1 has_VHZ shown_VVN that_CST internal_JJ audit_NN1 departments_NN2 are_VBR found_VVN in_II large_JJ companies_NN2 which_DDQ in_II most_DAT instances_NN2 have_VH0 audit_NN1 committees_NN2 to_II whom_PNQO the_AT internal_JJ auditors_NN2 report_VV0 to_TO thereby_RR asserting_VVG their_APPGE independence_NN1 (_( )_) ._. 
</s>
<s>
The_AT Institute_NN1 of_IO Internal_JJ Auditors_NN2 UK_NP1 and_CC Ireland_NP1 issued_VVD a_AT1 position_NN1 statement_NN1 to_II its_APPGE members_NN2 entitled_VVN The_AT Role_NN1 of_IO Internal_JJ Audit_NN1 in_II Risk_NN1 Management_NN1 in_II 2002_MC to_TO guide_VVI members_NN2 on_II what_DDQ activities_NN2 they_PPHS2 could_VM engage_VVI in_RP without_IW compromising_VVG their_APPGE independence_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ shown_VVN in_II figure_NN1 1_MC1 below_RL ._. 
</s>
<s>
This_DD1 guidance_NN1 strongly_RR encourage_VV0 members_NN2 to_TO be_VBI engaged_VVN in_II activities_NN2 such_II21 as_II22 evaluating_VVG and_CC reviewing_VVG risk_NN1 management_NN1 processes_NN2 and_CC reports_NN2 ,_, and_CC assurance_NN1 services_NN2 for_IF their_APPGE companies_NN2 ._. 
</s>
<s>
In_II a_AT1 bid_NN1 to_TO preserve_VVI their_APPGE independence_NN1 ,_, the_AT IIA_NP1 UK_NP1 and_CC Ireland_NP1 not_XX be_VBI involved_JJ in_II activities_NN2 that_CST require_VV0 them_PPHO2 to_II setting_NN1 of_IO risk_NN1 appetite_NN1 and_CC management_NN1 of_IO risks_NN2 ,_, assuming_VVG risks_NN2 or_CC be_VBI accountable_JJ for_IF risks_NN2 ._. 
</s>
<s>
These_DD2 areas_NN2 will_VM cause_VVI conflicts_NN2 for_IF the_AT internal_JJ auditors_NN2 for_REX21 instance_REX22 if_CS they_PPHS2 are_VBR accountable_JJ for_IF a_AT1 risk_NN1 ,_, and_CC give_VV0 an_AT1 assurance_NN1 or_CC an_AT1 opinion_NN1 on_II it_PPH1 ,_, there_EX will_VM a_AT1 conflict_NN1 of_IO interest_NN1 problem_NN1 ._. 
</s>
<s>
Moeller_NN1 and_CC Herbert_NP1 (_( 2009_MC )_) in_II their_APPGE book_NN1 Brinks_NN2 Modern_JJ Internal_JJ Auditing_NN1 are_VBR of_IO the_AT opinion_NN1 that_CST internal_JJ auditors_NN2 can_VM assume_VVI the_AT roles_NN2 shown_VVN in_II figure_NN1 1_MC1 because_CS they_PPHS2 have_VH0 a_AT1 much_RR better_JJR understanding_NN1 of_IO their_APPGE companys_NN2 organisational_JJ units_NN2 than_CSN anyone_PN1 else_RR in_II the_AT organisation_NN1 ._. 
</s>
<s>
They_PPHS2 can_VM thus_RR assess_VVI and_CC review_VVI the_AT operations_NN2 of_IO their_APPGE organisations_NN2 in_II every_AT1 possible_JJ area_NN1 from_II the_AT highest_JJT to_II the_AT lowest_JJT level_NN1 ._. 
</s>
<s>
The_AT 1947_MC definition_NN1 by_II the_AT Institute_NN1 of_IO Internal_JJ Auditors_NN2 (_( cited_VVN in_II Davis_NP1 1956_MC ,_, p.227_FO )_) emphasised_VVD the_AT role_NN1 of_IO internal_JJ auditors_NN2 as_CSA ..._... the_AT basis_NN1 for_IF protective_JJ and_CC constructive_JJ service_NN1 to_II management_NN1 ..._... and_CC their_APPGE sole_JJ purpose_NN1 is_VBZ to_TO assist_VVI management_NN1 in_II achieving_VVG the_AT most_RGT efficient_JJ administration_NN1 of_IO the_AT operations_NN2 of_IO the_AT organisation_NN1 ._. 
</s>
<s>
They_PPHS2 perform_VV0 this_DD1 role_NN1 by_II reporting_VVG to_II management_NN1 as_CSA needed_VVN on_II the_AT efficiency_NN1 and_CC adequacy_NN1 of_IO the_AT internal_JJ control_NN1 systems_NN2 while_CS also_RR highlighting_VVG areas_NN2 that_CST need_VV0 improvement_NN1 (_( Davis_NP1 ,_, 1956_MC ,_, pp._NNU2 227-233_MCMC )_) ._. 
</s>
<s>
The_AT collapse_NN1 of_IO giants_NN2 like_II Enron_NP1 has_VHZ shown_VVN us_PPIO2 that_CST a_AT1 lack_NN1 of_IO internal_JJ controls_NN2 is_VBZ a_AT1 recipe_NN1 for_IF disaster_NN1 for_IF any_DD organisation_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ why_RRQ management_NN1 employs_VVZ internal_JJ auditors_NN2 to_TO act_VVI on_II their_APPGE behalf_NN1 with_IW regards_VVZ to_II internal_JJ controls_NN2 and_CC add_VV0 value_NN1 to_II the_AT organisation_NN1 by_II reporting_VVG on_II their_APPGE findings_NN2 directly_RR to_II the_AT audit_NN1 committee_NN1 ._. 
</s>
<s>
The_AT audit_NN1 committee_NN1 is_VBZ formed_VVN by_II the_AT board_NN1 of_IO directors_NN2 and_CC constitutes_VVZ independent_JJ directors_NN2 ._. 
</s>
<s>
Internal_JJ auditors_NN2 can_VM report_VVI weaknesses_NN2 and_CC any_DD fraud_NN1 being_VBG perpetuated_VVN by_II management_NN1 without_IW any_DD fear_NN1 of_IO recrimination_NN1 from_II management_NN1 ._. 
</s>
<s>
Internal_JJ auditors_NN2 and_CC risk_NN1 management_NN1 According_II21 to_II22 Krogstad_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 1999_MC )_) ,_, the_AT purpose_NN1 of_IO controls_NN2 is_VBZ to_TO assist_VVI management_NN1 to_TO successfully_RR handle_VVI its_APPGE organisational_JJ risks_NN2 while_CS also_RR promoting_VVG good_JJ governance_NN1 ._. 
</s>
<s>
Internal_JJ auditing_NN1 is_VBZ considered_VVN to_TO be_VBI a_AT1 form_NN1 of_IO internal_JJ control_NN1 (_( Moeller_NP1 ,_, 2009_MC )_) ._. 
</s>
<s>
Internal_JJ auditors_NN2 perceive_VV0 internal_JJ controls_NN2 as_II a_AT1 subset_NN1 of_IO risk_NN1 management_NN1 (_( IIA_NP1 UK_NP1 ,_, 1999_MC )_) ._. 
</s>
<s>
While_CS research_NN1 is_VBZ still_RR not_XX clear_JJ on_II which_DDQ of_IO risk_NN1 or_CC control_NN1 should_VM come_VVI first_MD ,_, Blackburn_NP1 (_( 1999_MC ,_, p.36_FO )_) has_VHZ stated_VVN that_CST the_AT emphasis_NN1 should_VM be_VBI on_II the_AT functions_NN2 that_CST assists_VVZ the_AT organisation_NN1 in_II meeting_VVG its_APPGE corporate_JJ objectives_NN2 ._. 
</s>
<s>
This_DD1 view_NN1 is_VBZ also_RR shared_VVN by_II the_AT Canadian_JJ Institute_NN1 of_IO Chartered_JJ Accountants_NN2 which_DDQ believes_VVZ controls_NN2 include_VV0 identifying_VVG or_CC recognising_VVG and_CC mitigating_JJ risks_NN2 (_( CICA_NP1 1999_MC ,_, p.9_FO )_) ._. 
</s>
<s>
A_AT1 survey_NN1 by_II Paape_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 2003_MC )_) in_II 15_MC European_JJ countries_NN2 found_VVD that_DD1 risk_NN1 management_NN1 was_VBDZ already_RR a_AT1 significant_JJ part_NN1 of_IO the_AT internal_JJ audit_NN1 function_NN1 ._. 
</s>
<s>
Allegrini_NN2 and_CC D'Onza_NP1 (_( 2003_MC )_) also_RR found_VVN that_CST within_II large_JJ Italian_JJ companies_NN2 ,_, internal_JJ auditors_NN2 were_VBDR part_NN1 of_IO the_AT risk_NN1 management_NN1 process_NN1 ._. 
</s>
<s>
They_PPHS2 acted_VVD as_CSA consultants_NN2 ,_, reporting_VVG ,_, assessing_VVG and_CC monitoring_VVG the_AT risk_NN1 management_NN1 process_NN1 and_CC reporting_VVG their_APPGE findings_NN2 to_II management_NN1 ._. 
</s>
<s>
Senior_JJ management_NN1 also_RR agrees_VVZ that_CST the_AT internal_JJ audit_NN1 function_NN1 has_VHZ moved_VVN away_II21 from_II22 compliance_NN1 to_II strategic_JJ risk_NN1 management_NN1 (_( Sarens_NP1 and_CC Beelde_NP1 ,_, 2006_MC ;_; Allegrini_NP1 and_CC D'Onza_NP1 ,_, 2003_MC )_) ._. 
</s>
<s>
A_AT1 survey_NN1 of_IO Belgian_JJ companies_NN2 operating_VVG in_II Belgium_NP1 and_CC the_AT US_NP1 by_II Sarens_NP1 and_CC Beelde_NP1 (_( 2006_MC )_) concluded_VVD that_CST the_AT role_NN1 of_IO internal_JJ audit_NN1 in_II risk_NN1 management_NN1 and_CC assessment_NN1 is_VBZ having_VHG a_AT1 significant_JJ impact_NN1 on_II global_JJ audit_NN1 planning_NN1 and_CC individual_JJ audits_NN2 ._. 
</s>
<s>
The_AT Institute_NN1 of_IO Chartered_JJ Accountants_NN2 of_IO England_NP1 and_CC Wales_NP1 (_( ICAEW_NP1 )_) advises_VVZ that_DD1 implementation_NN1 of_IO the_AT Turnbull_NP1 guidance_NN1 of_IO 1999_MC should_VM involve_VVI a_AT1 combination_NN1 of_IO internal_JJ controls_NN2 and_CC risk_NN1 management_NN1 (_( Jones_NP1 and_CC Sutherland_NP1 ,_, 1999_MC )_) ._. 
</s>
<s>
The_AT ICAEW_NP1 (_( 2000_MC ,_, p.9_FO )_) also_RR considers_VVZ internal_JJ auditors_NN2 as_CSA key_JJ advisers_NN2 on_II internal_JJ controls_NN2 and_CC risks_NN2 because_II21 of_II22 their_APPGE status_NN1 and_CC role_NN1 within_II the_AT organisational_JJ hierarchy_NN1 and_CC their_APPGE independent_JJ status_NN1 ._. 
</s>
<s>
The_AT internal_JJ audit_NN1 function_NN1 has_VHZ and_CC is_VBZ undergoing_VVG changes_NN2 partly_RR in_II31 response_II32 to_II33 research_NN1 papers_NN2 for_REX21 instance_REX22 (_( Selim_NP1 and_CC McNamee_NP1 ,_, 1999_MC )_) that_CST have_VH0 proposed_VVN that_CST internal_JJ audit_NN1 must_VM evolve_VVI in_II culture_NN1 and_CC competencies_NN2 before_CS it_PPH1 can_VM be_VBI effectively_RR aligned_VVN to_TO risk_VVI management_NN1 (_( Spira_NP1 and_CC Page_NN1 ,_, 2003_MC )_) ._. 
</s>
<s>
A_AT1 research_NN1 by_II KPMG_NP1 (_( 1999_MC )_) found_VVD that_CST internal_JJ auditors_NN2 have_VH0 a_AT1 fundamental_JJ role_NN1 to_TO play_VVI in_II identifying_VVG ,_, mitigating_VVG and_CC evaluating_VVG their_APPGE organisational_JJ risks_NN2 ._. 
</s>
<s>
According_II21 to_II22 Spira_NP1 and_CC Page_NN1 (_( 2003_MC )_) ,_, internal_JJ auditing_NN1 professional_JJ bodies_NN2 are_VBR exhorting_VVG their_APPGE members_NN2 to_TO present_VVI themselves_PPX2 as_CSA experts_NN2 in_II risk_NN1 management_NN1 by_II improving_VVG on_II their_APPGE professional_JJ skills_NN2 ._. 
</s>
<s>
This_DD1 can_VM be_VBI done_VDN through_II the_AT identification_NN1 of_IO their_APPGE most_RGT significant_JJ risks_NN2 that_CST must_VM be_VBI mitigated_VVN or_CC exploited_VVN in_BCL21 order_BCL22 to_TO add_VVI stakeholder_NN1 value_NN1 (_( Sarens_NP1 and_CC Beelde_NP1 ,_, 2006_MC )_) ._. 
</s>
<s>
The_AT significance_NN1 of_IO categorising_VVG internal_JJ auditors_NN2 as_CSA risk_NN1 experts_NN2 can_VM be_VBI seen_VVN through_II the_AT lenses_NN2 of_IO corporate_JJ governance_NN1 were_VBDR risk_NN1 management_NN1 is_VBZ a_AT1 component_NN1 ._. 
</s>
<s>
The_AT objective_NN1 of_IO corporate_JJ governance_NN1 is_VBZ to_TO ensure_VVI that_CST the_AT agents_NN2 (_( senior_JJ management_NN1 )_) are_VBR devoting_VVG their_APPGE time_NNT1 and_CC knowhow_VV0 for_IF the_AT maximisation_NN1 of_IO short_JJ -and_CC long_JJ values_NN2 for_IF the_AT principals_NN2 (_( stakeholders_NN2 )_) ._. 
</s>
<s>
The_AT role_NN1 of_IO internal_JJ audit_NN1 in_II enterprise_NN1 risk_NN1 management_NN1 (_( ERM_FU )_) One_MC1 of_IO the_AT first_MD reports_VVZ that_CST underscored_VVD the_AT relationship_NN1 between_II internal_JJ control_NN1 and_CC risk_NN1 management_NN1 was_VBDZ the_AT Turnbull_NP1 report_NN1 (_( 1999_MC )_) in_II the_AT UK_NP1 (_( Sarens_NP1 and_CC Beelde_NP1 ,_, 2006_MC )_) ._. 
</s>
<s>
The_AT Institute_NN1 of_IO Internal_JJ Auditors-_NN1 UK_NP1 (_( IIA_NP1 UK_NP1 )_) ,_, has_VHZ stated_VVN that_CST internal_JJ auditors_NN2 plays_VVZ a_AT1 key_JJ role_NN1 in_II implementing_VVG ERM_NN1 ._. 
</s>
<s>
ERM_NN1 has_VHZ evolved_VVN from_II the_AT concept_NN1 of_IO risk_NN1 management_NN1 in_II the_AT financial_JJ and_CC insurance_NN1 sectors_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ considered_VVN to_TO be_VBI a_AT1 holistic_JJ process_NN1 which_DDQ is_VBZ carried_VVN out_RP from_II an_AT1 enterprise-wide_JJ perspective_NN1 ._. 
</s>
<s>
Its_APPGE goal_NN1 is_VBZ to_TO assist_VVI management_NN1 in_II meeting_VVG its_APPGE organisational_JJ objectives_NN2 ._. 
</s>
<s>
While_CS the_AT onus_NN1 on_II ERM_NN1 remains_VVZ with_IW the_AT board_NN1 ,_, the_AT IIA_NP1 ,_, UK_NP1 believes_VVZ the_AT internal_JJ audit_NN1 function_NN1 can_VM provide_VVI reasonable_JJ assurance_NN1 to_II management_NN1 as_II21 to_II22 the_AT effectiveness_NN1 of_IO its_APPGE risk_NN1 management_NN1 strategies_NN2 ._. 
</s>
<s>
According_II21 to_II22 Sarens_NP1 and_CC Beelde_NP1 (_( 2006_MC )_) ,_, respondents_NN2 from_II a_AT1 survey_NN1 in_II the_AT US_NP1 have_VH0 stated_VVN that_CST their_APPGE organisations_NN2 can_VM not_XX subsist_VVI without_IW a_AT1 sound_JJ internal_JJ control_NN1 system_NN1 ._. 
</s>
<s>
They_PPHS2 also_RR contend_VV0 that_CST companies_NN2 are_VBR meeting_VVG this_DD1 need_NN1 by_II formally_RR documenting_VVG and_CC communicating_JJ policies_NN2 on_II risk_NN1 management_NN1 and_CC internal_JJ control_NN1 to_TO key_VVI stakeholders_NN2 notably_RR employees_NN2 and_CC the_AT board_NN1 ._. 
</s>
<s>
The_AT comparative_JJ study_NN1 conducted_VVN by_II Sarens_NP1 and_CC Beelde_NP1 (_( 2006_MC )_) titled_VVN internal_JJ auditors_NN2 perception_NN1 about_II their_APPGE role_NN1 in_II risk_NN1 management_NN1 :_: a_AT1 comparison_NN1 between_II US_NP1 and_CC Belgian_JJ companies_NN2 found_VVD that_CST internal_JJ auditors_NN2 are_VBR deeply_RR involved_JJ in_II the_AT following_JJ areas_NN2 of_IO ERM_NN1 ;_; development_NN1 ,_, re-engineering_NN1 and_CC facilitation_NN1 ._. 
</s>
<s>
Internal_JJ auditors_NN2 are_VBR heavily_RR involved_JJ in_II the_AT early_JJ stages_NN2 of_IO designing_VVG an_AT1 ERM_NN1 system_NN1 with_IW possible_JJ questionnaire_NN1 development_NN1 ,_, but_CCB as_CSA the_AT project_NN1 progresses_VVZ ,_, their_APPGE role_NN1 decreases_VVZ ._. 
</s>
<s>
They_PPHS2 also_RR organise_VV0 training_NN1 sessions_NNT2 at_II the_AT behest_NN1 of_IO management_NN1 on_II risk_NN1 management_NN1 and_CC provide_VV0 formal_JJ reports_NN2 on_II their_APPGE findings_NN2 on_II the_AT internal_JJ control_NN1 and_CC risk_NN1 management_NN1 system_NN1 ._. 
</s>
<s>
This_DD1 also_RR contributes_VVZ to_II transparency_NN1 and_CC enhances_VVZ their_APPGE role_NN1 another_DD1 role_NN1 for_IF internal_JJ auditors_NN2 as_CSA facilitators_NN2 of_IO corporate_JJ governance_NN1 ._. 
</s>
<s>
A_AT1 role_NN1 brought_VVN to_II prominence_NN1 by_II the_AT emphasis_NN1 that_CST regulators_NN2 and_CC investors_NN2 have_VH0 placed_VVN on_II the_AT internal_JJ control_NN1 environment_NN1 which_DDQ provides_VVZ the_AT platform_NN1 for_IF effective_JJ risk_NN1 management_NN1 ._. 
</s>
<s>
Other_JJ professional_JJ bodies_NN2 see_VV0 internal_JJ auditors_NN2 as_CSA adding_VVG value_NN1 to_II their_APPGE organisations_NN2 through_II risk_NN1 management_NN1 (_( Sarens_NP1 and_CC Beelde_NP1 ,_, 2006_MC )_) ._. 
</s>
<s>
ERM_NN1 is_VBZ effective_JJ when_CS embedded_VVN in_II the_AT strategic_JJ decision_NN1 planning_NN1 process_NN1 by_II management_NN1 ._. 
</s>
<s>
Internal_JJ auditors_NN2 will_VM identify_VVI ,_, assess_VVI ,_, and_CC monitor_VVI any_DD deficiencies_NN2 during_II and_CC after_CS the_AT implementation_NN1 of_IO an_AT1 ERM_NN1 by_II the_AT chief_JJ risk_NN1 officer_NN1 ._. 
</s>
<s>
They_PPHS2 should_VM therefore_RR play_VVI a_AT1 very_RG limited_JJ role_NN1 in_II advising_VVG management_NN1 on_II how_RRQ to_TO implement_VVI an_AT1 ERM_NN1 system_NN1 to_TO avoid_VVI compromising_VVG their_APPGE independence_NN1 when_CS evaluating_VVG and_CC reporting_VVG on_II the_AT effectiveness_NN1 of_IO the_AT system_NN1 ._. 
</s>
<s>
Their_APPGE general_JJ understanding_NN1 of_IO the_AT functioning_NN1 of_IO the_AT organisational_JJ structure_NN1 make_VV0 them_PPHO2 consultants_NN2 and_CC increases_VVZ the_AT role_NN1 they_PPHS2 play_VV0 at_II early_JJ stages_NN2 of_IO the_AT ERM_NN1 implementation_NN1 process_NN1 ._. 
</s>
<s>
The_AT scope_NN1 of_IO their_APPGE role_NN1 will_VM depend_VVI on_II the_AT resources_NN2 available_JJ ._. 
</s>
<s>
Notably_RR qualified_VVN and_CC experienced_JJ staff_NN to_TO act_VVI as_II a_AT1 leader_NN1 and_CC enabler_NN1 of_IO the_AT ERM_NN1 process_NN1 ._. 
</s>
<s>
The_AT presence_NN1 of_IO an_AT1 audit_NN1 committee_NN1 to_II whom_PNQO they_PPHS2 can_VM report_VVI to_II will_VM help_VVI in_II preserving_VVG their_APPGE independence_NN1 and_CC give_VVI them_PPHO2 managerial_JJ prominence_NN1 within_II the_AT organisation_NN1 (_( Spira_NP1 and_CC page_NN1 ,_, 2003_MC )_) ._. 
</s>
<s>
It_PPH1 should_VM also_RR emphasised_VVN that_CST internal_JJ auditors_NN2 can_VM only_RR add_VVI value_NN1 by_II collaborating_VVG with_IW management_NN1 ._. 
</s>
<s>
That_REX21 is_REX22 ,_, when_CS management_NN1 implements_NN2 or_CC at_RR21 least_RR22 considers_VVZ their_APPGE recommendations_NN2 when_CS making_VVG decisions_NN2 on_II policy_NN1 issues_NN2 ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) Analysis_NN1 and_CC Discussion_NN1 Conclusion_NN1 and_CC further_JJR research_NN1 
</s>
