<s>
Organisational_JJ Selling_NN1 of_IO Services_NN2 1_MC1 ._. 
</s>
<s>
Introduction_NN1 There_EX are_VBR many_DA2 different_JJ definitions_NN2 of_IO the_AT term_NN1 selling_NN1 ._. 
</s>
<s>
All_DB of_IO these_DD2 definitions_NN2 explain_VV0 that_CST a_AT1 salesman_NN1 must_VM through_II the_AT usage_NN1 of_IO a_AT1 selling_NN1 message_NN1 control_VV0 the_AT potential_JJ customers_NN2 decision_NN1 process_NN1 ._. 
</s>
<s>
For_REX21 example_REX22 ,_, Mercuri_JJ International_JJ defines_VVZ selling_VVG as_II :_: Influencing_VVG the_AT other_JJ party_NN1 in_II a_AT1 manor_NN1 that_CST results_NN2 in_II positive_JJ decision_NN1 making_VVG for_IF the_AT salesman_NN1 The_AT salesmans_NN2 competitors_NN2 are_VBR not_XX only_RR the_AT direct_JJ competitors_NN2 ,_, but_CCB also_RR the_AT customers_NN2 possibility_NN1 of_IO conducting_VVG the_AT job_NN1 by_II themselves_PPX2 or_CC refraining_VVG from_II using_VVG the_AT service_NN1 can_VM be_VBI regarded_VVN as_CSA competing_JJ alternatives_NN2 ._. 
</s>
<s>
In_II31 addition_II32 to_II33 these_DD2 there_RL are_VBR also_RR several_DA2 external_JJ company-specific_JJ factors_NN2 that_CST influence_VV0 the_AT potential_JJ customers_NN2 purchasing_VVG behaviour_NN1 ._. 
</s>
<s>
The_AT model_NN1 below_RL is_VBZ directed_VVN to_II companies_NN2 that_CST sell_VV0 services_NN2 ,_, but_CCB can_VM also_RR be_VBI used_VVN to_TO describe_VVI the_AT situation_NN1 of_IO the_AT potential_JJ clients_NN2 company_NN1 ._. 
</s>
<s>
Factors_NN2 affecting_VVG the_AT selling_NN1 of_IO services_NN2 :_: As_CSA we_PPIS2 can_VM see_VVI from_II the_AT model_NN1 ,_, the_AT result_NN1 of_IO sales_NN is_VBZ a_AT1 multifactorial_JJ function_NN1 which_DDQ makes_VVZ selling_VVG a_AT1 very_RG complex_JJ process._NNU 1.1_MC ._. 
</s>
<s>
Purpose_VV0 The_AT purpose_NN1 of_IO this_DD1 paper_NN1 is_VBZ to_TO determine_VVI the_AT factors_NN2 that_CST affect_VV0 the_AT potential_JJ customers_NN2 decision-making_NN1 at_II a_AT1 sales_NN opportunity_NN1 and_CC the_AT various_JJ methods_NN2 by_II which_DDQ sellers_NN2 can_VM meet_VVI their_APPGE goals_NN2 of_IO getting_VVG the_AT potential_JJ customer_NN1 to_TO commit_VVI to_II a_AT1 purchase._NNU 1.2_MC ._. 
</s>
<s>
Structure_NN1 of_IO the_AT paper_NN1 Since_CS the_AT clients_NN2 needs_NN2 and_CC concerns_NN2 are_VBR the_AT root_NN1 of_IO all_DB sales_NN the_AT paper_NN1 will_VM first_MD present_VVI the_AT purchasing_NN1 behaviour_NN1 of_IO companies_NN2 ._. 
</s>
<s>
Thereafter_RT the_AT process_NN1 that_CST a_AT1 salesman_NN1 goes_VVZ through_RP in_BCL21 order_BCL22 to_TO conduct_VVI a_AT1 sale_NN1 is_VBZ presented_VVN ._. 
</s>
<s>
Then_RT a_AT1 few_DA2 frameworks_NN2 for_IF customer-focused_JJ argumentation_NN1 that_CST can_VM be_VBI used_VVN during_II the_AT selling_NN1 process_NN1 will_VM be_VBI presented_VVN ._. 
</s>
<s>
However_RR ,_, it_PPH1 is_VBZ important_JJ for_IF the_AT salesman_NN1 to_TO understand_VVI what_DDQ kind_NN1 of_IO questions_NN2 should_VM be_VBI asked_VVN in_BCL21 order_BCL22 to_TO receive_VVI the_AT necessary_JJ information_NN1 that_CST salesmen_NN2 can_VM base_VVI their_APPGE argumentations_NN2 on_RP ,_, and_CC therefore_RR a_AT1 few_DA2 different_JJ questioning_JJ techniques_NN2 will_VM also_RR be_VBI presented._NNU 2_MC ._. 
</s>
<s>
Organizational_JJ purchasing_NN1 behaviour_NN1 The_AT customers_NN2 decision-making_JJ process_NN1 consists_VVZ of_IO ,_, according_II21 to_II22 Mercuri_JJ International_JJ ,_, 20%_NNU rational_JJ factors_NN2 and_CC 80%_NNU emotional_JJ factors_NN2 ._. 
</s>
<s>
Jobber_NN1 ,_, Lancaster_NP1 (_( 2007_MC )_) claims_VVZ that_CST organizational_JJ buyers_NN2 are_VBR less_RRR affected_VVN by_II emotional_JJ factors_NN2 than_CSN consumer_NN1 buyers_NN2 ._. 
</s>
<s>
Gathered_VVN below_RL is_VBZ a_AT1 table_NN1 presenting_VVG different_JJ rational_JJ and_CC emotional_JJ factors_NN2 ._. 
</s>
<s>
Rational_JJ factors_NN2 Emotional_JJ factors_NN2 Price_VV0 Prestige_NN1 Delivery_NN1 Personal_JJ risk_NN1 minimization_NN1 Productivity_NN1 Entertainment_NN1 Life_NN1 cycle_NN1 costs_VVZ Reciprocity_NN1 Reliability_NN1 Confidence_NN1 Durability_NN1 Comfort_NN1 Safety_NN1 Quiet_JJ life_NN1 However_RR ,_, all_DB of_IO these_DD2 factors_NN2 ,_, whether_CSW rational_JJ or_CC emotional_JJ ,_, relate_VV0 to_II the_AT needs_NN2 of_IO the_AT customer_NN1 ._. 
</s>
<s>
According_II21 to_II22 Jobber_NN1 ,_, Lancaster_NP1 (_( 2007_MC )_) ,_, the_AT needs_NN2 of_IO organizational_JJ buyers_NN2 can_VM be_VBI divided_VVN into_II three_MC categories_NN2 that_CST make_VV0 up_RP a_AT1 process_NN1 :_: 1_MC1 ._. 
</s>
<s>
Structure_NN1 :_: the_AT Who_NP1 factor_NN1 reflects_VVZ who_PNQS participates_VVZ in_II the_AT decision-making_NN1 and_CC their_APPGE specific_JJ roles._NNU 2_MC ._. 
</s>
<s>
Process_VV0 :_: The_AT How_RRQ factor_NN1 describes_VVZ the_AT pattern_NN1 of_IO information_NN1 retrieval_NN1 ,_, analysis_NN1 ,_, evaluation_NN1 and_CC decision_NN1 making_VVG that_CST occurs_VVZ when_RRQ a_AT1 buying_NN1 organization_NN1 moves_VVZ toward_II a_AT1 decision_NN1 3_MC ._. 
</s>
<s>
Content_NN1 :_: The_AT What_DDQ factor_NN1 describes_VVZ the_AT choice_NN1 of_IO criteria_NN2 used_VVN at_II different_JJ stages_NN2 of_IO the_AT process_NN1 and_CC by_II different_JJ makers_NN2 ._. 
</s>
<s>
Even_CS21 though_CS22 some_DD companies_NN2 follow_VV0 the_AT organizational_JJ buying_NN1 behaviour_NN1 described_VVN by_II Jobber_NN1 ,_, Lancaster_NP1 (_( 2007_MC )_) ,_, it_PPH1 is_VBZ still_RR important_JJ to_TO realize_VVI that_CST it_PPH1 is_VBZ ultimately_RR people_NN who_PNQS buy_VV0 ,_, not_XX organizations_NN2 ._. 
</s>
<s>
This_DD1 is_VBZ important_JJ to_TO remember_VVI when_RRQ the_AT seller_NN1 takes_VVZ the_AT customers_NN2 needs_VVZ to_II account._NNU 2.1_MC ._. 
</s>
<s>
The_AT Customers_NN2 Needs_VVZ Developers_NN2 can_VM take_VVI advantage_NN1 of_IO using_VVG the_AT customers_NN2 needs_VVZ as_II the_AT basis_NN1 of_IO their_APPGE argumentation_NN1 ._. 
</s>
<s>
When_CS they_PPHS2 sell_VV0 by_II first_MD finding_VVG out_RP and_CC understanding_VVG the_AT customer_NN1 needs_NN2 and_CC then_RT base_VV0 the_AT sale_NN1 on_II those_DD2 needs_NN2 (_( Strandvik_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2012_MC )_) ._. 
</s>
<s>
The_AT customers_NN2 needs_NN2 are_VBR based_VVN on_II their_APPGE mental_JJ models_NN2 about_II their_APPGE company_NN1 and_CC the_AT strategy_NN1 that_CST influences_VVZ their_APPGE priorities_NN2 ,_, decision-making_JJ and_CC actions_NN2 (_( Strandvik_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2012_MC )_) ._. 
</s>
<s>
Companies_NN2 often_RR explain_VV0 that_CST their_APPGE strategies_NN2 and_CC goals_NN2 are_VBR not_XX respected_VVN by_II salesmen_NN2 ,_, who_PNQS tend_VV0 to_II only_JJ present_NN1 their_APPGE own_DA products_NN2 or_CC services_NN2 (_( Strandvik_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2012_MC )_) ._. 
</s>
<s>
It_PPH1 thus_RR appears_VVZ that_CST the_AT salesmans_NN2 mental_JJ models_NN2 differ_VV0 from_II that_DD1 of_IO their_APPGE potential_JJ customers_NN2 ._. 
</s>
<s>
Several_DA2 companies_NN2 further_RRR explain_VV0 that_CST salesmen_NN2 should_VM be_VBI willing_JJ to_TO understand_VVI the_AT business_NN1 of_IO their_APPGE potential_JJ customers_NN2 as_II31 well_II32 as_II33 how_RRQ their_APPGE product_NN1 or_CC service_NN1 can_VM be_VBI used_VVN to_TO improve_VVI the_AT business_NN1 (_( Strandvik_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2012_MC )_) ._. 
</s>
<s>
Customers_NN2 ,_, their_APPGE strategies_NN2 and_CC goals_NN2 are_VBR the_AT primary_JJ drivers_NN2 of_IO business_NN1 ,_, not_XX salesmen_NN2 and_CC their_APPGE products_NN2 (_( Strandvik_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2012_MC )_) ._. 
</s>
<s>
Salesmen_NN2 must_VM therefore_RR take_VVI the_AT potential_JJ customers_NN2 strategy_NN1 ,_, mission_NN1 and_CC vision_NN1 into_II account_NN1 when_CS they_PPHS2 sell_VV0 ._. 
</s>
<s>
Customers_NN2 needs_NN2 can_VM be_VBI split_VVN into_II three_MC categories_NN2 :_: task-oriented_JJ needs_NN2 ,_, experience-oriented_JJ needs_NN2 and_CC time-based_JJ needs_NN2 (_( Strandvik_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2012_MC )_) ._. 
</s>
<s>
These_DD2 are_VBR the_AT needs_NN2 that_CST salesmen_NN2 should_VM try_VVI to_TO satisfy_VVI with_IW the_AT help_NN1 of_IO the_AT products_NN2 or_CC services_NN2 that_CST they_PPHS2 sell_VV0 :_: value_NN1 is_VBZ created_VVN when_CS these_DD2 needs_NN2 are_VBR satisfied_JJ ._. 
</s>
<s>
Value_NN1 can_VM be_VBI created_VVN for_IF task-oriented_JJ needs_NN2 when_RRQ the_AT customers_NN2 daily_JJ work_NN1 is_VBZ made_VVN easier_RRR ._. 
</s>
<s>
Value_NN1 can_VM be_VBI created_VVN for_IF experience-oriented_JJ needs_NN2 when_RRQ the_AT customers_NN2 performance_NN1 is_VBZ improved_VVN through_II the_AT usage_NN1 of_IO the_AT salesmans_NN2 product_NN1 or_CC service_NN1 ._. 
</s>
<s>
Value_NN1 can_VM also_RR be_VBI created_VVN for_IF time-based_JJ needs_NN2 when_RRQ the_AT customer_NN1 can_VM improve_VVI their_APPGE use_NN1 of_IO time_NNT1 with_IW the_AT help_NN1 of_IO the_AT product_NN1 or_CC service_NN1 that_CST the_AT salesman_NN1 provides_VVZ ._. 
</s>
<s>
(_( Strandvik_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2012_MC )_) ._. 
</s>
<s>
By_II combining_VVG the_AT claim_NN1 that_CST 80%_NNU of_IO companies_NN2 decision_NN1 making_NN1 is_VBZ based_VVN on_II emotional_JJ factors_NN2 with_IW the_AT results_NN2 of_IO the_AT Strandvik_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2012_MC study_NN1 we_PPIS2 can_VM understand_VVI that_CST the_AT customer_NN1 needs_VVZ to_TO receive_VVI an_AT1 emotional_JJ benefit_NN1 to_II their_APPGE task-_NN1 ,_, experience-_NN1 ,_, or_CC time-oriented_JJ problems_NN2 before_II the_AT customer_NN1 makes_VVZ a_AT1 decision_NN1 to_II buy._NNU 2.2_MC ._. 
</s>
<s>
The_AT Power_NN1 of_IO Recommendations_NN2 Recommendations_NN2 can_VM and_CC should_VM be_VBI used_VVN by_II salesman_NN1 when_CS dealing_VVG with_IW objections_NN2 ._. 
</s>
<s>
Upon_II being_VBG recommended_VVN to_II a_AT1 potential_JJ client_NN1 the_AT chances_NN2 of_IO completing_VVG a_AT1 sale_NN1 will_VM be_VBI much_RR higher_JJR ._. 
</s>
<s>
Lets_VVZ take_VVI the_AT accounting_NN1 market_NN1 ,_, where_CS the_AT usage_NN1 of_IO recommendations_NN2 has_VHZ been_VBN proven_VVN to_TO be_VBI the_AT most_RGT important_JJ method_NN1 of_IO sales_NN (_( O'Donohoes_NP1 ,_, 1991_MC )_) ,_, as_CSA an_AT1 example_NN1 ._. 
</s>
<s>
Out_II21 of_II22 290_MC companies_NN2 interviewed_VVN in_II the_AT U.S._NP1 ,_, 72%_NNU claimed_VVD that_CST recommendations_NN2 influenced_VVN their_APPGE decision_NN1 making_VVG when_CS choosing_VVG an_AT1 accountant_NN1 (_( George_NP1 ,_, 1980_MC )_) ._. 
</s>
<s>
When_CS someone_PN1 recommends_VVZ an_AT1 accountant_NN1 to_II a_AT1 company_NN1 ,_, the_AT company_NN1 creates_VVZ an_AT1 image_NN1 of_IO the_AT accountants_NN2 reputation_NN1 ._. 
</s>
<s>
The_AT word_NN1 reputation_NN1 is_VBZ defined_VVN as_II an_AT1 informal_JJ description_NN1 of_IO someone_PN1 or_CC something_PN1 based_VVN on_II the_AT hearsay_NN1 (_( Sasser_NP1 ,_, 2011_MC )_) ._. 
</s>
<s>
Wheiler_NP1 (_( Wheiler_NP1 ,_, 1987_MC )_) examined_VVD the_AT recommendations_NN2 of_IO accountants_NN2 ,_, bankers_NN2 and_CC lawyers_NN2 in_II the_AT United_NP1 States_NP1 ._. 
</s>
<s>
It_PPH1 was_VBDZ found_VVN that_CST a_AT1 person_NN1 who_PNQS recommends_VVZ a_AT1 service_NN1 has_VHZ to_TO have_VHI trust_NN1 in_CS21 that_CS22 the_AT service_NN1 will_VM be_VBI able_JK to_TO deliver_VVI promptly_RR ,_, be_VBI good_JJ at_II customer_NN1 relations_NN2 and_CC provide_VV0 access_NN1 to_II the_AT managers_NN2 (_( Wheiler_NP1 ,_, 1987_MC )_) ._. 
</s>
<s>
In_II other_JJ words_NN2 the_AT accountants_NN2 reputation_NN1 has_VHZ to_TO be_VBI good_JJ enough_RR to_TO deserve_VVI being_VBG recommended_VVN ._. 
</s>
<s>
How_RRQ companies_NN2 experienced_VVD the_AT accountants_NN2 reputation_NN1 was_VBDZ proven_VVN to_TO be_VBI the_AT primary_JJ factor_NN1 during_II the_AT selection_NN1 of_IO an_AT1 accountant_NN1 (_( Taylor_NP1 ,_, 1962_MC )_) ._. 
</s>
<s>
A_AT1 good_JJ reputation_NN1 that_CST leads_VVZ to_II recommendations_NN2 in_II this_DD1 case_NN1 can_VM be_VBI created_VVN from_II such_DA ledgers_NN2 of_IO quality_NN1 ._. 
</s>
<s>
3_MC ._. 
</s>
<s>
The_AT Sales_NN Process_VV0 Among_II the_AT better_JJR known_JJ frameworks_NN2 of_IO the_AT sales_NN process_NN1 is_VBZ the_AT AIDA_NP1 model_NN1 developed_VVN by_II Strong_NP1 (_( 1925_MC )_) in_II his_APPGE book_NN1 The_AT Psychology_NN1 of_IO Selling_NN1 ._. 
</s>
<s>
According_II21 to_II22 the_AT AIDA_NP1 model_NN1 ,_, the_AT customer_NN1 needs_VVZ to_TO pass_VVI through_II four_MC mental_JJ states_NN2 before_II purchasing_VVG a_AT1 product_NN1 or_CC service_NN1 ._. 
</s>
<s>
The_AT salesman_NN1 must_VM first_MD create_VVI awareness_NN1 of_IO the_AT potential_JJ customer_NN1 (_( attention_NN1 )_) ,_, then_RT raise_VV0 the_AT interest_NN1 of_IO the_AT potential_JJ customer_NN1 ,_, where_CS after_CS the_AT interest_NN1 needs_VVZ to_TO be_VBI turned_VVN into_II desire_NN1 resulting_VVG in_II action_NN1 ._. 
</s>
<s>
However_RR ,_, the_AT AIDA_NP1 model_NN1 has_VHZ been_VBN criticized_VVN for_IF being_VBG more_RRR marketing_VVG oriented_JJ than_CSN sales_NN oriented_VVD ._. 
</s>
<s>
Regardless_RR of_IO which_DDQ model_NN1 is_VBZ used_VVN to_TO analyse_VVI the_AT sales_NN process_VV0 there_EX are_VBR a_AT1 few_DA2 unavoidable_JJ events_NN2 that_CST occur_VV0 when_CS selling_VVG services_NN2 ._. 
</s>
<s>
These_DD2 are_VBR the_AT sales_NN call_VV0 ,_, the_AT meeting_NN1 and_CC the_AT decision-making_NN1 ._. 
</s>
<s>
The_AT transitions_NN2 between_II these_DD2 events_NN2 will_VM also_RR demand_VVI preparation_NN1 by_II both_DB2 the_AT salesman_NN1 and_CC the_AT potential_JJ client_NN1 ._. 
</s>
<s>
Even_CS21 though_CS22 selling_VVG is_VBZ a_AT1 process_NN1 that_CST is_VBZ commonly_RR regarded_VVN as_CSA independent_JJ from_II other_JJ functions_NN2 of_IO companies_NN2 ,_, it_PPH1 has_VHZ been_VBN proven_VVN that_CST the_AT support_NN1 functions_NN2 provided_VVN by_II companies_NN2 have_VH0 a_AT1 great_JJ impact_NN1 on_II the_AT total_JJ sales._NNU 3.1_MC ._. 
</s>
<s>
The_AT Sales_NN Call_VV0 According_II21 to_II22 Mercuri_JJ International_JJ ,_, a_AT1 good_JJ build_VV0 up_RP of_IO a_AT1 sale_NN1 call_NN1 includes_VVZ :_: 1_MC1 ._. 
</s>
<s>
A_AT1 brief_JJ introduction_NN1 including_II a_AT1 break_NN1 2_MC ._. 
</s>
<s>
An_AT1 explanation_NN1 of_IO where_RRQ you_PPY are_VBR calling_VVG from_II 3_MC ._. 
</s>
<s>
An_AT1 answer_NN1 to_II the_AT question_NN1 why_RRQ should_VM the_AT customer_NN1 see_VVI me_PPIO1 ?_? 4_MC ._. 
</s>
<s>
A_AT1 few_DA2 date_NN1 proposals_NN2 5_MC ._. 
</s>
<s>
A_AT1 confirmation_NN1 and_CC a_AT1 nice_JJ ending_NN1 3.2_MC ._. 
</s>
<s>
Preparing_VVG for_IF a_AT1 Meeting_NN1 A_ZZ1 salesman_NN1 can_VM prepare_VVI for_IF a_AT1 sales_NN call_VV0 by_II formulating_VVG clear_JJ arguments_NN2 ._. 
</s>
<s>
A_AT1 brief_JJ background_NN1 study_NN1 and_CC drafting_VVG the_AT questions_NN2 concerning_II the_AT identification_NN1 of_IO the_AT clients_NN2 situation_NN1 belongs_VVZ to_II a_AT1 well-prepared_JJ salesmans_NN2 preparation_NN1 activities_NN2 ._. 
</s>
<s>
A_AT1 salesman_NN1 should_VM avoid_VVI making_VVG assumptions_NN2 as_CSA these_DD2 may_VM lead_VVI to_II the_AT salesman_NN1 steering_VVG the_AT meeting_NN1 in_II the_AT wrong_JJ direction_NN1 ._. 
</s>
<s>
The_AT planning_NN1 of_IO the_AT argument_NN1 should_VM be_VBI based_VVN on_II the_AT claim_NN1 the_AT 80%_NNU of_IO the_AT customer_NN1 decision-making_NN1 is_VBZ based_VVN on_II emotional_JJ factors_NN2 ._. 
</s>
<s>
The_AT salesman_NN1 has_VHZ three_MC types_NN2 of_IO arguments_NN2 to_II his_APPGE or_CC her_APPGE disposal_NN1 :_: what_DDQ the_AT product_NN1 or_CC service_NN1 is_VBZ ,_, what_DDQ the_AT product_NN1 or_CC service_NN1 gives_VVZ to_II the_AT customer_NN1 and_CC what_DDQ the_AT product_NN1 or_CC service_NN1 means_VVZ to_II the_AT customer_NN1 ._. 
</s>
<s>
Arguing_VVG by_II explaining_VVG what_DDQ the_AT product_NN1 or_CC service_NN1 is_VBZ ineffective_JJ since_CS there_EX usually_RR are_VBR an_AT1 abundance_NN1 of_IO alternatives_NN2 on_II the_AT market_NN1 ._. 
</s>
<s>
By_II using_VVG the_AT arguments_NN2 of_IO what_DDQ the_AT service_NN1 gives_VVZ and_CC means_NN for_IF the_AT customer_NN1 the_AT salesman_NN1 can_VM easier_RRR infiltrate_VVI the_AT emotional_JJ factors_NN2 that_CST compose_VV0 the_AT potential_JJ customers_NN2 decision-making_JJ process_NN1 ._. 
</s>
<s>
A_AT1 good_JJ salesman_NN1 lays_VVZ emphasis_NN1 on_II arguments_NN2 related_VVN to_II what_DDQ the_AT product_NN1 or_CC service_NN1 gives_VVZ and_CC means_VVZ to_II the_AT potential_JJ customer._NNU 3.3_MC ._. 
</s>
<s>
The_AT Meeting_NN1 Here_RL I_PPIS1 will_VM present_VVI the_AT SATA_NN1 and_CC FOCA_NN1 models._NNU 3.4_MC ._. 
</s>
<s>
How_RRQ to_TO handle_VVI objections_NN2 3.5_MC ._. 
</s>
<s>
Encouraging_JJ Decision-making_NN1 3.6_MC ._. 
</s>
<s>
The_AT contents_NN2 of_IO a_AT1 formal_JJ proposal_NN1 3.7_MC ._. 
</s>
<s>
Re-occurring_VVG Sales_NN &;_NULL Customer_NN1 Relations_NN2 3.8_MC ._. 
</s>
<s>
The_AT Strategy_NN1 Should_VM Support_VV0 the_AT Sale_NN1 4_MC ._. 
</s>
<s>
Customer_NN1 Oriented_JJ Reasoning_NN1 4.1_MC ._. 
</s>
<s>
FOCA_NP1 4.2_MC ._. 
</s>
<s>
DABA_NP1 5_MC ._. 
</s>
<s>
The_AT Importance_NN1 of_IO Question_NN1 Asking_VVG 5.1_MC ._. 
</s>
<s>
The_AT Difference_NN1 Between_II Open_JJ and_CC Closed_JJ Questions_NN2 5.2_MC ._. 
</s>
<s>
Some_DD Practical_JJ Tips_NN2 for_IF the_AT Presentation_NN1 of_IO Good_JJ Questions_NN2 6_MC ._. 
</s>
<s>
Summary_NN1 Here_RL I_PPIS1 will_VM summarize_VVI the_AT models_NN2 into_II a_AT1 one-page_JJ executive_NN1 summary_NN1 and_CC an_AT1 info-graph_NN1 ._. 
</s>
