<s>
Culture_NN1 consumption_NN1 of_IO Japanese_JJ popular_JJ culture_NN1 in_II Finland_NP1 Introduction_NN1 Research_NN1 on_II Japanese_JJ popular_JJ culture_NN1 consumption_NN1 in_II Finland_NP1 focus_NN1 on_II Fans_NN2 who_PNQS devote_VV0 themselves_PPX2 to_II Japanese_JJ popular_JJ culture_NN1 positively_RR ._. 
</s>
<s>
Fewer_DAR studies_NN2 examine_VV0 the_AT attitudes_NN2 and_CC consumption_NN1 on_II Japanese_JJ popular_JJ culture_NN1 of_IO Finns_NN2 beyond_II the_AT Fans_NN2 ._. 
</s>
<s>
In_II31 terms_II32 of_II33 business_NN1 potential_NN1 ,_, those_DD2 Finns_NN2 still_RR could_VM be_VBI profit_NN1 resource_NN1 of_IO Japanese_JJ popular_JJ culture_NN1 business_NN1 as_CS31 long_CS32 as_CS33 businessmen_NN2 know_VV0 their_APPGE preference_NN1 ._. 
</s>
<s>
This_DD1 paper_NN1 seeks_VVZ to_TO contribute_VVI to_II the_AT study_NN1 of_IO culture_NN1 consumption_NN1 and_CC social_JJ perception_NN1 on_II Japanese_JJ popular_JJ cultural_JJ of_IO Finns_NN2 who_PNQS are_VBR out_II21 of_II22 the_AT Fans_NN2 community_NN1 ._. 
</s>
<s>
Specifically_RR ,_, this_DD1 paper_NN1 identifies_VVZ the_AT most_RGT attractive_JJ business_NN1 potential_NN1 of_IO Japanese_JJ popular_JJ culture_NN1 in_II Finland_NP1 by_II investigating_VVG Finns_NN2 consumption_NN1 preferences_NN2 ._. 
</s>
<s>
Foundations_NN2 of_IO Japanese_JJ popular_JJ culture_NN1 are_VBR manga_NN1 ,_, anime_NN1 ,_, fashion_NN1 ,_, video_NN1 games_NN2 ,_, music_NN1 ,_, film_NN1 and_CC television_NN1 ._. 
</s>
<s>
There_EX is_VBZ a_AT1 huge_JJ value_NN1 space_NN1 for_IF those_DD2 industries_NN2 and_CC the_AT peripheral_JJ products_NN2 ._. 
</s>
<s>
In_II Italy_NP1 ,_, anime_NN1 and_CC manga_NN1 emerged_VVD as_CSA media_NN for_IF children_NN2 ._. 
</s>
<s>
In_II US_NP1 ,_, back_RP to_II 1977_MC ,_, a_AT1 local_JJ organization_NN1 in_II Los_NP1 Angels_NP1 started_VVD regularly_RR screening_VVG Japanese_JJ anime_NN1 ._. 
</s>
<s>
(_( Ishida_NN1 ,_, 2010_MC )_) The_AT prevalence_NN1 of_IO anime_NN1 and_CC manga_NN1 catalyzed_VVD businesses_NN2 such_II21 as_II22 language_NN1 translation_NN1 and_CC clothing_NN1 and_RR31 so_RR32 on_RR33 ._. 
</s>
<s>
However_RR ,_, in_II Finland_NP1 ,_, compared_VVN to_II other_JJ markets_NN2 worldwide_RL ,_, the_AT Finnish_JJ market_NN1 exhibits_VVZ a_AT1 degree_NN1 of_IO disadvantage_NN1 in_II the_AT potential_JJ growth_NN1 of_IO anime_NN1 and_CC manga_NN1 ._. 
</s>
<s>
(_( Ishida_NN1 ,_, 2010_MC )_) Culture_NN1 difference_NN1 is_VBZ the_AT stumbling_NN1 block_NN1 of_IO prevalence_NN1 of_IO Japanese_JJ popular_JJ culture_NN1 in_II Finland_NP1 ._. 
</s>
<s>
Though_CS the_AT history_NN1 of_IO manga_NN1 and_CC anime_NN1 in_II Finland_NP1 begins_VVZ in_II the_AT 1970s_MC2 ,_, it_PPH1 is_VBZ only_RR in_II recent_JJ years_NNT2 that_CST they_PPHS2 have_VH0 infiltrated_VVN Finnish_JJ popular_JJ culture_NN1 ._. 
</s>
<s>
At_II the_AT time_NNT1 when_RRQ the_AT first_MD anime_NN1 productions_NN2 were_VBDR on_II TV_NN1 ,_, they_PPHS2 were_VBDR very_RG well_RR received_VVN ._. 
</s>
<s>
However_RR ,_, it_PPH1 was_VBDZ notunderstood_VVN until_CS the_AT 90_MC221 's_MC222 that_CST those_DD2 productions_NN2 were_VBDR specifically_RR anime._NNU (_( Ishida_NP1 ,_, 2010_MC )_) Obviously_RR ,_, in_BCL21 order_BCL22 to_TO be_VBI accepted_VVN immediately_RR and_CC successfully_RR in_II Finland_NP1 ,_, the_AT foreign_JJ culture_NN1 embedded_VVN in_II the_AT business_NN1 has_VHZ to_TO be_VBI understood_VVN by_II Finns_NN2 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, overcoming_VVG those_DD2 barriers_NN2 requires_VVZ perception_NN1 on_II Finns_NN2 acceptance_NN1 of_IO Japanese_JJ popular_JJ culture_NN1 ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, businessmen_NN2 must_VM understand_VVI what_DDQ Finns_NN2 intend_VV0 to_TO purchase_VVI ._. 
</s>
<s>
Therefore_RR ,_, this_DD1 paper_NN1 investigates_VVZ Finns_NN2 preference_NN1 and_CC culture_NN1 consumption_NN1 habitat_NN1 on_II Japanese_JJ popular_JJ culture_NN1 to_TO provide_VVI initial_JJ information_NN1 on_II choosing_VVG a_AT1 profitable_JJ Japanese_JJ popular_JJ culture_NN1 business_NN1 ._. 
</s>
<s>
This_DD1 paper_NN1 investigates_VVZ Finns_NN2 attitudes_NN2 on_II certain_JJ dimensions_NN2 of_IO Japanese_JJ popular_JJ culture_NN1 that_CST involve_VV0 in_II Finns_NN2 daily_JJ life_NN1 instead_II21 of_II22 study_NN1 Fans_NN2 community_NN1 ._. 
</s>
<s>
The_AT research_NN1 question_NN1 is_VBZ what_DDQ Japanese_JJ culture_NN1 product_NN1 will_VM be_VBI accepted_VVN with_IW minimumrejection_NN1 by_II Finns_NN2 ._. 
</s>
<s>
In_II doing_VDG so_RR ,_, this_DD1 paper_NN1 enriches_VVZ the_AT lacking_JJ information_NN1 of_IO influence_NN1 of_IO Japanese_JJ popular_JJ culture_NN1 on_II Finns_NN2 daily_JJ life_NN1 of_IO previous_JJ studies_NN2 ._. 
</s>
<s>
This_DD1 paper_NN1 is_VBZ organized_VVN into_II five_MC sections_NN2 ._. 
</s>
<s>
Following_VVG this_DD1 introduction_NN1 ,_, the_AT second_MD section_NN1 provides_VVZ a_AT1 conceptual_JJ overview_NN1 of_IO Japanese_JJ popular_JJ culture_NN1 consumption_NN1 in_II Finland_NP1 including_II the_AT relationship_NN1 between_II different_JJ dimensions_NN2 of_IO Japanese_JJ popular_JJ culture_NN1 and_CC Finns_NN2 daily_JJ life_NN1 ._. 
</s>
<s>
The_AT third_MD section_NN1 presents_VVZ the_AT papers_NN2 data_NN and_CC methodology_NN1 ._. 
</s>
<s>
This_DD1 section_NN1 explores_VVZ the_AT background_NN1 information_NN1 of_IO each_DD1 Japanese_JJ popular_JJ culture_NN1 factor_NN1 that_CST Finns_NN2 might_VM concern_VVI ._. 
</s>
<s>
Section_NN1 four_MC presents_VVZ the_AT results_NN2 of_IO interviews_NN2 of_IO Finns_NN2 attitudes_NN2 and_CC their_APPGE consumption_NN1 habitats_NN2 on_II Japanese_JJ popular_JJ culture_NN1 ._. 
</s>
<s>
The_AT conclusion_NN1 section_NN1 surmises_VVZ the_AT indication_NN1 of_IO research_NN1 results_NN2 and_CC suggests_VVZ on_II business_NN1 potential_NN1 of_IO Japanese_JJ popular_JJ culture_NN1 in_II Finland_NP1 ._. 
</s>
<s>
Literature_NN1 review_NN1 Be_VBI local_JJ or_CC global_JJ :_: a_AT1 debate_NN1 on_II culture_NN1 and_CC consumption_NN1 A_ZZ1 critical_JJ issue_NN1 for_IF retailors_NN2 and_CC manufactures_VVZ who_PNQS are_VBR seeking_VVG to_TO expand_VVI their_APPGE operations_NN2 internationally_RR is_VBZ whether_CSW adapting_VVG products_NN2 for_IF local_JJ markets_NN2 ._. 
</s>
<s>
According_II21 to_II22 Levitt_NP1 and_CC his_APPGE supporters_NN2 ,_, a_AT1 standard_JJ global_JJ product_NN1 can_VM be_VBI successful_JJ in_II all_DB markets_NN2 because_CS the_AT world_NN1 is_VBZ becoming_VVG increasingly_RR homogenized_VVD ._. 
</s>
<s>
However_RR ,_, this_DD1 proposition_NN1 then_RT challenged_VVN by_II Littler_NP1 and_CC Schlieper_NN1 with_IW the_AT argument_NN1 that_CST Levitts_VVZ theory_NN1 fails_VVZ to_TO take_VVI into_II account_NN1 consumer_NN1 influences_NN2 on_II the_AT way_NN1 the_AT product_NN1 is_VBZ used_VVN ,_, positioned_VVN and_CC perceived._NNU (_( Deirdre_NP1 ,_, 1998_MC )_) In_II developed_JJ countries_NN2 ,_, consumption_NN1 has_VHZ moved_VVN beyond_II its_APPGE primary_JJ function_NN1 of_IO serving_VVG basic_JJ human_JJ needs_NN2 and_CC is_VBZ increasingly_RR linked_VVN to_II symbolic_JJ meanings_NN2 ,_, values_NN2 and_CC lifestyles_NN2 that_CST are_VBR likely_JJ to_TO be_VBI specific_JJ to_II local_JJ cultures_NN2 ._. 
</s>
<s>
Usunier_NP1 noted_VVD that_CST there_EX is_VBZ few_DA2 truly_RR universal_JJ products_NN2 exist_VV0 due_II21 to_II22 culture_NN1 differences_NN2 across_II countries_NN2 that_CST remain_VV0 a_AT1 significant_JJ barrier_NN1 to_II internationalization_NN1 ,_, especially_RR in_II culture-bound_JJ industries_NN2 ,_, such_II21 as_II22 food_NN1 and_CC beverages_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ clearly_RR that_DD1 consumption_NN1 decisions_NN2 are_VBR inextricably_RR linked_VVN to_II their_APPGE cultural_JJ context_NN1 ._. 
</s>
<s>
The_AT culture_NN1 background_NN1 of_IO consumers_NN2 is_VBZ a_AT1 potential_JJ barrier_NN1 to_TO market_VVI development_NN1 ._. 
</s>
<s>
To_TO overcome_VVI this_DD1 barrier_NN1 ,_, organizations_NN2 must_VM develop_VVI a_AT1 deeper_JJR understanding_NN1 of_IO local_JJ cultures_NN2 and_CC their_APPGE influence_NN1 upon_II purchasing_VVG decisions_NN2 ._. 
</s>
<s>
(_( Deirdre_NP1 ,_, 1998_MC )_) What_DDQ links_VVZ culture_NN1 ,_, consumption_NN1 and_CC product_NN1 choice_NN1 ?_? 
</s>
<s>
A_AT1 conceptualizing_JJ relationship_NN1 between_II culture_NN1 ,_, consumption_NN1 and_CC product_NN1 choice_NN1 developed_VVN by_II Deirdre_NP1 (_( 1998_MC )_) indicates_VVZ that_CST the_AT presence_NN1 of_IO culture_NN1 affects_VVZ individual_JJ tastes_NN2 and_CC preferences_NN2 ,_, which_DDQ ultimately_RR influences_VVZ consumption_NN1 behavior_NN1 ._. 
</s>
<s>
First_MD ,_, at_II the_AT broadest_JJT level_NN1 ,_, culture_NN1 is_VBZ a_AT1 shared_JJ experience_NN1 ,_, consisting_VVG of_IO learned_JJ behaviors_NN2 that_CST directly_RR impinge_VV0 on_II individual_JJ consumer_NN1 decisions_NN2 within_II a_AT1 society_NN1 ._. 
</s>
<s>
Consumption_NN1 has_VHZ become_VVN an_AT1 active_JJ social_JJ process_NN1 ,_, deeply_RR rooted_VVN in_II cultural_JJ procedures_NN2 ._. 
</s>
<s>
Second_MD ,_, culture_NN1 impacts_NN2 on_II consumer_NN1 product_NN1 choice_NN1 by_II its_APPGE influence_NN1 in_II the_AT formation_NN1 of_IO beliefs_NN2 and_CC attitudes_NN2 ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, beyond_II personal_JJ preference_NN1 ,_, culture_NN1 context_NN1 is_VBZ the_AT foundation_NN1 of_IO consumers_NN2 choice_NN1 ._. 
</s>
<s>
Personal_JJ preference_NN1 affects_VVZ the_AT general_JJ choice_NN1 such_II21 as_II22 color_NN1 and_CC price_NN1 while_CS culture_NN1 impacts_NN2 the_AT essential_JJ product_NN1 rang_VVD ,_, for_REX21 example_REX22 ,_, which_DDQ item_NN1 would_VM be_VBI popular_JJ in_II target_NN1 market_NN1 depends_VVZ on_II the_AT culture_NN1 embedded_VVN in_II the_AT market_NN1 ._. 
</s>
<s>
Culture_NN1 product_NN1 and_CC consumption_NN1 :_: a_AT1 framework_NN1 of_IO culture_NN1 consumption_NN1 in_II Finland_NP1 Culture_NN1 marketing_NN1 is_VBZ the_AT art_NN1 of_IO making_VVG contact_NN1 with_IW market_NN1 segments_VVZ that_CST are_VBR likely_JJ to_TO be_VBI interested_JJ in_II the_AT product_NN1 by_II adapting_VVG the_AT marketing_NN1 variables-price_NN1 ,_, distribution_NN1 and_CC promotion-in_NN1 order_NN1 to_TO put_VVI the_AT product_NN1 in_II31 contact_II32 with_II33 a_AT1 sufficient_JJ number_NN1 of_IO consumers._NNU Although_CS culture_NN1 product_NN1 represents_VVZ its_APPGE original_JJ culture_NN1 ,_, it_PPH1 still_RR needs_VVZ to_TO be_VBI adapted_VVN to_TO fit_VVI in_II different_JJ market_NN1 segments_NN2 ._. 
</s>
<s>
Therefore_RR ,_, culture_NN1 product_NN1 contains_VVZ multiple_JJ culture_NN1 factors_NN2 rather_II21 than_II22 its_APPGE original_JJ one_PN1 ._. 
</s>
<s>
Culture_NN1 product_NN1 distribution_NN1 is_VBZ determined_VVN by_II consumers_NN2 form_NN1 of_IO consumption_NN1 ._. 
</s>
<s>
It_PPH1 designed_VVD for_IF both_DB2 collective_JJ consumption_NN1 and_CC individual_JJ consumption_NN1 ._. 
</s>
<s>
Collective_JJ consumption_NN1 products_NN2 to_II consumers_NN2 gain_VV0 access_NN1 by_II gathering_VVG in_II one_MC1 place_NN1 for_IF a_AT1 set_NN1 period_NN1 time_NNT1 such_II21 as_II22 a_AT1 show_NN1 or_CC a_AT1 film_NN1 ._. 
</s>
<s>
For_IF individual_JJ consumption_NN1 ,_, which_DDQ consumers_NN2 can_VM enjoy_VVI whenever_RRQV and_CC wherever_RRQV they_PPHS2 desire_VV0 ._. 
</s>
<s>
For_REX21 instance_REX22 ,_, recordings_NN2 ,_, books_NN2 and_CC visual_JJ works_NN of_IO art_NN1 owned_VVN by_II the_AT consumer_NN1 are_VBR individual_JJ consumption_NN1 products_NN2 ._. 
</s>
<s>
In_II Finland_NP1 ,_, the_AT culture_NN1 consumption_NN1 pattern_NN1 has_VHZ been_VBN changed_VVN a_RR21 lot_RR22 since_II 1990s_MC2 ._. 
</s>
<s>
Traditional_JJ culture_NN1 consumption_NN1 pattern_NN1 in_II Finland_NP1 have_VH0 more_DAR weight_NN1 on_II collective_JJ elements_NN2 rather_II21 than_II22 strategies_NN2 of_IO distinction_NN1 that_CST take_VV0 unity_NN1 and_CC homogeneity_NN1 as_CSA key_JJ values_NN2 ._. 
</s>
<s>
There_EX is_VBZ a_AT1 preference_NN1 for_IF cultural_JJ products_NN2 of_IO domestic_JJ origin_NN1 in_II Finland_NP1 ._. 
</s>
<s>
However_RR ,_, in_II recent_JJ years_NNT2 ,_, there_EX are_VBR changes_NN2 in_II both_DB2 the_AT frequency_NN1 of_IO consumption_NN1 and_CC the_AT choices_NN2 themselves_PPX2 ._. 
</s>
<s>
The_AT nature_NN1 of_IO culture_NN1 consumption_NN1 is_VBZ becoming_VVG less_RGR serious_JJ ,_, more_RGR touristy_JJ ,_, more_RRR a_AT1 genuine_JJ pleasure_NN1 ,_, more_RRR related_VVN to_II personality_NN1 ._. 
</s>
<s>
(_( Likkanen_NP1 )_) One_MC1 stable_JJ aspect_NN1 of_IO culture_NN1 consumption_NN1 in_II Finland_NP1 is_VBZ that_CST men_NN2 and_CC women_NN2 take_VV0 different_JJ attitudes_NN2 towards_II art_NN1 and_CC culture_NN1 ._. 
</s>
<s>
Based_VVN on_II the_AT theory_NN1 of_IO gender_NN1 system_NN1 that_CST developed_VVN by_II Yvonne_NP1 Hirdman_NP1 ,_, separation_NN1 and_CC hierarchy_NN1 are_VBR two_MC key_JJ principles_NN2 of_IO study_NN1 gender_NN1 system_NN1 ._. 
</s>
<s>
Separation_NN1 implies_VVZ that_DD1 woman_NN1 and_CC womanhood_NN1 can_VM be_VBI clearly_RR distinguished_VVN from_II man_NN1 and_CC manhood_NN1 ;_; and_CC hierarchy_NN1 that_CST man_NN1 and_CC manhood_NN1 are_VBR more_RGR highly_RR valued_VVN than_CSN woman_NN1 and_CC womanhood._NNU (_( Liikkanen_NP1 )_) In_II Finland_NP1 ,_, men_NN2 are_VBR still_RR heavily_RR oriented_VVN towards_II technology_NN1 ,_, engineering_NN1 sciences_NN2 ,_, economic_JJ sciences_NN2 ,_, in_RR21 general_RR22 towards_II professional_JJ occupations_NN2 ._. 
</s>
<s>
On_II the_AT contrary_NN1 ,_, women_NN2 read_VV0 more_DAR than_CSN men_NN2 ;_; they_PPHS2 show_VV0 a_AT1 strong_JJ orientation_NN1 to_II non-fiction_NN1 ,_, entertainment_NN1 and_CC high_JJ culture_NN1 ._. 
</s>
<s>
Those_DD2 differences_NN2 are_VBR still_RR clear_JJ in_II their_APPGE leisure_NN1 choices_NN2 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, younger_JJR generations_NN2 show_VV0 a_AT1 stronger_JJR preference_NN1 for_IF audiovisual_JJ culture_NN1 and_CC for_IF foreign_JJ products_NN2 ,_, especially_RR among_II young_JJ males_NN2 ._. 
</s>
<s>
Young_JJ women_NN2 are_VBR still_RR fancy_VV0 traditional_JJ leisure_NN1 even_RR they_PPHS2 are_VBR also_RR quite_RG keen_JJ in_II everything_PN1 that_CST is_VBZ new_JJ ._. 
</s>
<s>
(_( Japanese_JJ pop_NN1 culture_NN1 consumption_NN1 and_CC consumption_NN1 in_II Finland_NP1 Pop_NN1 culture_NN1 is_VBZ viewed_VVN as_CSA emerging_VVG from_II a_AT1 continually_RR changing_VVG and_CC socially_RR related_JJ set_NN1 of_IO contemporary_JJ behaviors_NN2 ,_, images_NN2 ,_, practices_NN2 and_CC product_NN1 that_CST result_VV0 form_VV0 the_AT interaction_NN1 of_IO individuals_NN2 ,_, groups_NN2 ,_, media_NN ,_, the_AT art_NN1 ,_, and_CC organizations_NN2 as_CSA they_PPHS2 attempt_VV0 to_TO entertain_VVI ,_, communicate_VV0 ideas_NN2 ,_, and_CC give_VVI meaning_VVG to_II a_AT1 range_NN1 of_IO symbols_NN2 ,_, activities_NN2 and_CC social_JJ developments_NN2 in_II a_AT1 society_NN1 ._. 
</s>
<s>
(_( Simeon_NP1 ,_, 2006_MC )_) the_AT nature_NN1 of_IO pop_NN1 culture_NN1 is_VBZ dynamic_JJ which_DDQ correspond_VV0 to_II the_AT nature_NN1 of_IO culture_NN1 consumption_NN1 ._. 
</s>
<s>
Generally_RR ,_, Japanese_JJ pop_NN1 culture_NN1 refers_VVZ to_II manga_NN1 ,_, anime_NN1 ,_, fashion_NN1 ,_, video_NN1 games_NN2 ,_, music_NN1 ,_, film_NN1 and_CC television_NN1 ._. 
</s>
<s>
Obviously_RR ,_, Japanese_JJ pop_NN1 culture_NN1 is_VBZ a_AT1 culture-bound_JJ business_NN1 that_CST emphasis_NN1 the_AT importance_NN1 of_IO understanding_VVG Finnish_JJ consumption_NN1 culture_NN1 ._. 
</s>
<s>
)_) Lacking_VVG information_NN1 ,_, need_VV0 to_TO be_VBI revised_JJ Methodology_NN1 The_AT study_NN1 model_NN1 used_VMK to_TO analyze_VVI Finns_NN2 consumption_NN1 preference_NN1 on_II Japanese_JJ popular_JJ culture_NN1 product_NN1 is_VBZ based_VVN on_II the_AT secondary_JJ data_NN and_CC study_NN1 reviews_NN2 of_IO pervious_JJ studies_NN2 in_II the_AT form_NN1 of_IO qualitative_JJ research_NN1 method_NN1 ._. 
</s>
<s>
This_DD1 paper_NN1 focus_NN1 on_II individual_JJ consumption_NN1 that_CST product_NN1 are_VBR occupied_VVN personally_RR ._. 
</s>
<s>
According_II21 to_II22 Deirdre_NP1 (_( 1998_MC )_) and_CC Liikkanen_NP1 ,_, culture_NN1 rooted_VVN in_II consumers_NN2 background_NN1 impacts_NN2 consumption_NN1 and_CC product_NN1 choices_NN2 ._. 
</s>
<s>
Therefore_RR ,_, when_CS studying_VVG the_AT potential_JJ profit_NN1 space_NN1 of_IO a_AT1 new_JJ product_NN1 ,_, the_AT consumption_NN1 culture_NN1 of_IO target_NN1 market_NN1 is_VBZ the_AT essential_JJ starting_NN1 point_NN1 ._. 
</s>
<s>
In_II this_DD1 study_NN1 ,_, the_AT equivalent_JJ starting_NN1 point_NN1 is_VBZ market_NN1 segmentation_NN1 specifying_VVG by_II gender_NN1 ._. 
</s>
<s>
The_AT components_NN2 of_IO Japanese_JJ popular_JJ culture_NN1 are_VBR classified_VVN according_II21 to_II22 gender_NN1 because_II21 of_II22 the_AT significant_JJ difference_NN1 on_II culture_NN1 consumption_NN1 between_II women_NN2 and_CC men_NN2 in_II Finland_NP1 ._. 
</s>
<s>
The_AT component_NN1 of_IO Japanese_JJ popular_JJ is_VBZ not_XX failed_VVN into_II gender_NN1 category_NN1 randomly_RR ,_, a_AT1 pre-analysis_NN1 of_IO nature_NN1 of_IO each_DD1 component_NN1 shows_VVZ the_AT potential_JJ gender_NN1 classification_NN1 ._. 
</s>
<s>
Future_NN1 ,_, the_AT gender_NN1 segmentations_NN2 are_VBR refined_VVN by_II age_NN1 and_CC social_JJ class_NN1 to_TO locate_VVI Finns_NN2 consumption_NN1 preference_NN1 more_RGR detailed_JJ ._. 
</s>
<s>
Result_VV0 Gender_NN1 definition_NN1 of_IO Japanese_JJ popular_JJ culture_NN1 component_NN1 &lsqb;_( Table_NN1 &rsqb;_) Discussion_NN1 Conclusion_NN1 
</s>
