<s>
Introduction_NN1 Online_JJ shopping_NN1 is_VBZ one_MC1 of_IO the_AT modern_JJ technical_JJ solutions_NN2 ,_, which_DDQ has_VHZ seen_VVN daylight_NN1 due_II21 to_II22 the_AT fact_NN1 that_CST Internet_NP1 is_VBZ available_JJ almost_RR everywhere_RL and_CC to_II everyone_PN1 ._. 
</s>
<s>
More_RRR and_CC more_DAR people_NN around_II the_AT world_NN1 buy_VV0 some_DD of_IO their_APPGE clothing_NN1 from_II online_JJ shops_NN2 ._. 
</s>
<s>
This_DD1 can_NN1 been_VBN noticed_VVN as_CSA online_JJ shops_NN2 have_VH0 grown_VVN a_RR21 lot_RR22 ,_, and_CC there_EX are_VBR more_RGR and_CC more_DAR actors_NN2 in_II this_DD1 specific_JJ field_NN1 of_IO business_NN1 ._. 
</s>
<s>
What_DDQ are_VBR the_AT reasons_NN2 for_IF consumers_NN2 buy_VV0 clothing_NN1 online_RR ?_? 
</s>
<s>
To_TO understand_VVI this_DD1 question_NN1 ,_, a_AT1 study_NN1 about_II online_JJ clothing_NN1 shops_NN2 will_VM be_VBI conducted_VVN ._. 
</s>
<s>
The_AT study_NN1 will_VM concentrate_VVI on_II two_MC mainissues_NN2 ;_; what_DDQ attracts_VVZ customers_NN2 to_II online_JJ shops_NN2 ,_, and_CC what_DDQ makes_VVZ them_PPHO2 buy_VVI clothing_NN1 online_RR ._. 
</s>
<s>
The_AT reason_NN1 for_IF this_DD1 study_NN1 is_VBZ to_TO get_VVI knowledge_NN1 ofwhy_NN1 consumers_NN2 buy_VV0 clothing_NN1 online_RR ._. 
</s>
<s>
This_DD1 information_NN1 can_VM be_VBI important_JJ and_CC later_RRR used_VVN by_II my_APPGE own_DA company_NN1 ._. 
</s>
<s>
I_PPIS1 havefounded_VVD anonline_NN1 shop_NN1 with_IW a_AT1 partner_NN1 a_AT1 few_DA2 weeks_NNT2 ago_RA ._. 
</s>
<s>
We_PPIS2 will_VM sell_VVI street_NN1 wear_VV0 for_IF male_JJ adults_NN2 between_II 18-35_MCMC ._. 
</s>
<s>
The_AT study_NN1 will_VM give_VVI us_PPIO2 valuable_JJ information_NN1 of_IO our_APPGE target_NN1 group_NN1 ,_, and_CC will_VM give_VVI an_AT1 advantage_NN1 to_TO succeed_VVI over_II the_AT competitors_NN2 ._. 
</s>
<s>
The_AT target_NN1 group_NN1 of_IO the_AT study_NN1 will_VM be_VBI restrictedto_NN1 a_AT1 specificage_NN1 group_NN1 ._. 
</s>
<s>
This_DD1 group_NN1 consists_VVZ of_IO young_JJ male_JJ adults_NN2 between_II 18-35_MCMC years_NNT2 old_JJ ._. 
</s>
<s>
The_AT reason_NN1 for_IF this_DD1 is_VBZ that_CST this_DD1 specific_JJ target_NN1 group_NN1 is_VBZ the_AT target_NN1 group_NN1 for_IF my_APPGE own_DA company_NN1 and_CC this_DD1 information_NN1 gives_VVZ valuable_JJ information_NN1 ._. 
</s>
<s>
The_AT other_JJ thing_NN1 is_VBZ that_DD1 different_JJ consumer_NN1 groups_NN2 behave_VV0 differently_RR and_CC therefore_RR it_PPH1 is_VBZ important_JJ to_TO tie_VVI the_AT data_NN gathering_VVG to_II a_AT1 certain_JJ target_NN1 group_NN1 ._. 
</s>
<s>
This_DD1 will_VM also_RR help_VVI me_PPIO1 to_TO draw_VVI specific_JJ conclusions_NN2 of_IO the_AT consumers_NN2 I_PPIS1 try_VV0 to_TO attract_VVI ._. 
</s>
<s>
The_AT paper_NN1 will_VM be_VBI structured_VVN in_II five_MC parts_NN2 ._. 
</s>
<s>
These_DD2 will_VM be_VBI ;_; Introduction_NN1 ,_, Method_NN1 ,_, Results_NN2 ,_, Discussion_NN1 ,_, and_CC Conclusion.In_NP1 the_AT methods_NN2 part_VV0 I_PPIS1 will_VM discuss_VVI and_CC open_VVI the_AT methods_NN2 that_CST are_VBR going_VVGK to_TO be_VBI used_VVN ,_, where_CS the_AT data_NN will_VM be_VBI gathered_VVN from_II ,_, and_CC how_RRQ it_PPH1 will_VM be_VBI done_VDN ._. 
</s>
<s>
In_II the_AT results_NN2 part_VV0 I_PPIS1 will_VM just_RR present_VVI the_AT findings_NN2 ._. 
</s>
<s>
The_AT results_NN2 will_VM be_VBI then_RT analyzed_VVN and_CC discussed_VVN ._. 
</s>
<s>
In_II the_AT end_NN1 a_AT1 conclusion_NN1 of_IO the_AT study_NN1 will_VM be_VBI available_JJ ._. 
</s>
<s>
This_DD1 study_NN1 will_VM most_RGT likely_RR answer_VVI why_RRQ men_NN2 ,_, between_II 18-35_MCMC years_NNT2 old_JJ ,_, buy_VV0 street_NN1 wear_VV0 online_RR ._. 
</s>
<s>
Im_VV0 hoping_VVG to_TO be_VBI able_JK to_TO use_VVI this_DD1 valuable_JJ information_NN1 for_IF my_APPGE own_DA business_NN1 and_CC gain_VV0 an_AT1 advantage_NN1 over_II the_AT competitors_NN2 ._. 
</s>
<s>
Online_JJ shops_NN2 Online_JJ shops_NN2 are_VBR shops_NN2 where_CS you_PPY can_VM buy_VVI items_NN2 online_RR ._. 
</s>
<s>
The_AT customer_NN1 can_VM often_RR choose_VVI between_II several_DA2 payment_NN1 methods_NN2 ,_, e.g._REX credit_NN1 or_CC debit_VV0 card_NN1 ,_, cash_NN1 on_II delivery_NN1 ,_, postal_JJ order_NN1 money_NN1 ,_, gift_NN1 cards_NN2 ,_, wire_NN1 transfer_NN1 ._. 
</s>
<s>
Then_RT the_AT items_NN2 will_VM be_VBI delivered_VVN according_II21 to_II22 the_AT available_JJ options_NN2 ._. 
</s>
<s>
These_DD2 are_VBR most_RGT likely_JJ shipping_NN1 or_CC pickup_NN1 ._. 
</s>
<s>
The_AT biggest_JJT online_JJ shops_NN2 worldwide_RL are_VBR Ebay_NP1 and_CC Amazon.com_NP1 ,_, and_CC in_II Finland_NP1 NetAnttila_NP1 ,_, Hobby_NN1 Hall_NN1 and_CC verkkokauppa.com_NNU ._. 
</s>
<s>
(_( Wikipedia_NP1 )_) Online_JJ shops_NN2 are_VBR to_TO be_VBI used_VVN and_CC visited_VVN with_IW Internet_NN1 browsers_NN2 ._. 
</s>
<s>
During_II recent_JJ times_NNT2 some_DD shops_NN2 have_VH0 even_RR developed_VVN sub_JJ sites_NN2 for_IF mobile_NN1 and_CC tablet_NN1 users_NN2 (_( Mashable_NP1 ,_, 2012_MC )_) ._. 
</s>
<s>
Advantages_NN2 of_IO online_JJ shops_NN2 If_CS normal_JJ shops_NN2 are_VBR compared_VVN to_II online_JJ shops_NN2 ,_, there_EX are_VBR a_AT1 few_DA2 obvious_JJ advantages_NN2 ._. 
</s>
<s>
Online_JJ shops_NN2 are_VBR basically_RR always_RR available_JJ ,_, whereas_CS normal_JJ shops_NN2 are_VBR open_RR only_RR on_II daytime_NNT1 ._. 
</s>
<s>
Therefore_RR the_AT consumer_NN1 can_VM buy_VVI and_CC order_VVI items_NN2 whenever_RRQV it_PPH1 fits_VVZ their_APPGE schedule_NN1 ._. 
</s>
<s>
In_RR21 addition_RR22 customers_NN2 can_VM constantly_RR get_VVI information_NN1 about_II the_AT items_NN2 ,_, brands_NN2 ,_, and_CC their_APPGE quality_NN1 ._. 
</s>
<s>
In_II normal_JJ stores_NN2 ,_, the_AT customers_NN2 cant_JJ reach_NN1 other_JJ customers_NN2 reviews_NN2 and_CC opinions_NN2 ._. 
</s>
<s>
They_PPHS2 just_RR need_VV0 to_TO trust_VVI their_APPGE instinct_NN1 ._. 
</s>
<s>
Some_DD online_JJ shops_NN2 allow_VV0 customers_NN2 to_II rate_NN1 and_CC give_VV0 feedback_NN1 according_II21 to_II22 their_APPGE experiences_NN2 of_IO the_AT items_NN2 and_CC the_AT service_NN1 ._. 
</s>
<s>
The_AT available_JJ information_NN1 concern_NN1 also_RR price_VV0 comparison_NN1 between_II online_JJ shops_NN2 ._. 
</s>
<s>
While_CS comparing_VVG prices_NN2 ,_, customers_NN2 can_VM also_RR compare_VVI what_DDQ paying_JJ and_CC delivery_NN1 options_NN2 are_VBR available_JJ ._. 
</s>
<s>
Disadvantages_NN2 of_IO online_JJ shops_NN2 As_RG earlier_RRR mentioned_VVN ,_, there_EX are_VBR definite_JJ pros_NN2 while_CS shopping_VVG online_RR ._. 
</s>
<s>
However_RR ,_, there_EX are_VBR also_RR cons_VVZ ._. 
</s>
<s>
Customers_NN2 cant_NN1 see_VV0 or_CC try_VV0 the_AT products_NN2 while_CS shopping_VVG online_RR ._. 
</s>
<s>
They_PPHS2 have_VH0 to_TO trust_VVI the_AT available_JJ information_NN1 and_CC pictures_NN2 ._. 
</s>
<s>
Especially_RR when_CS buying_VVG items_NN2 of_IO an_AT1 unknown_JJ brand_NN1 ,_, there_EX is_VBZ a_AT1 risk_NN1 of_IO not_XX getting_VVG the_AT quality_NN1 ,_, which_DDQ is_VBZ expected_VVN ._. 
</s>
<s>
If_CS a_AT1 customer_NN1 wants_VVZ to_TO ask_VVI something_PN1 ,_, often_RR one_MC1 have_VH0 to_TO send_VVI an_AT1 email_NN1 to_TO get_VVI an_AT1 answer_NN1 ,_, whereas_CS at_II a_AT1 physical_JJ store_NN1 the_AT clerk_NN1 can_VM help_VVI immediately_RR ._. 
</s>
<s>
Security_NN1 is_VBZ always_RR an_AT1 issue_NN1 when_CS shopping_VVG online_RR ._. 
</s>
<s>
As_CSA customers_NN2 cant_NN1 see_VV0 the_AT product_NN1 before_II payment_NN1 ,_, one_PN1 can_VM receive_VVI something_PN1 that_CST was_VBDZ not_XX desired_VVN ._. 
</s>
<s>
Another_DD1 issue_NN1 is_VBZ the_AT robbery_NN1 of_IO confidential_JJ information_NN1 like_II credit_NN1 card_NN1 details_NN2 ._. 
</s>
<s>
If_CS this_DD1 happens_VVZ ,_, one_MC1 cant_NN1 notice_VV0 this_DD1 before_II money_NN1 is_VBZ spent_VVN ._. 
</s>
<s>
However_RR there_EX is_VBZ ways_NN2 to_TO ensure_VVI that_CST the_AT sites_NN2 are_VBR secured_VVN and_CC have_VH0 legit_NN1 certification_NN1 to_TO encrypt_VVI valuable_JJ information_NN1 ._. 
</s>
<s>
Secondly_RR ,_, a_AT1 customer_NN1 can_VM always_RR search_VVI for_IF other_JJ customers_NN2 reviews_VVZ about_II the_AT service_NN1 and_CC see_VV0 if_CSW someone_PN1 has_VHZ had_VHN any_DD problems_NN2 before_RT ._. 
</s>
<s>
One_PN1 could_VM say_VVI :_: the_AT bigger_JJR and_CC more_RGR known_JJ shop_NN1 ,_, the_AT better_JJR and_CC secure_VV0 it_PPH1 is_VBZ ._. 
</s>
<s>
As_RG earlier_RRR mentioned_VVN ,_, a_AT1 customer_NN1 cant_NN1 see_VV0 the_AT product_NN1 before_CS they_PPHS2 receive_VV0 it_PPH1 ._. 
</s>
<s>
Therefore_RR the_AT return_NN1 of_IO the_AT items_NN2 could_VM be_VBI counted_VVN in_II disadvantages_NN2 ,_, as_CSA one_PN1 has_VHZ to_TO deliver_VVI them_PPHO2 back_RP to_II the_AT shop_NN1 and_CC wait_VV0 for_IF the_AT money_NN1 return_NN1 ._. 
</s>
<s>
Research_NN1 question_NN1 and_CC limits_VVZ This_DD1 research_NN1 will_VM aim_VVI to_TO study_VVI the_AT reasons_NN2 for_IF consumers_NN2 clothing_NN1 shopping_VVG online_RR ._. 
</s>
<s>
To_TO limit_VVI the_AT study_NN1 to_TO be_VBI more_RGR specific_JJ ,_, it_PPH1 will_VM consider_VVI two_MC main_JJ questions_NN2 ;_; what_DDQ attracts_VVZ consumers_NN2 to_II online_JJ shops_NN2 ,_, andwhat_NN1 makes_VVZ them_PPHO2 buy_VVI clothing_NN1 online_RR ._. 
</s>
<s>
To_TO limit_VVI the_AT results_NN2 to_TO be_VBI more_RGR specific_JJ ,_, the_AT study_NN1 will_VM consider_VVI only_RR male_JJ consumers_NN2 aged_VVN between_II 18_MC and_CC 35_MC ._. 
</s>
<s>
To_TO get_VVI valuable_JJ and_CC relevant_JJ results_NN2 a_AT1 preliminary_JJ interview_NN1 will_VM be_VBI made_VVN with_IW a_AT1 person_NN1 who_PNQS works_VVZ at_II an_AT1 online_JJ shop_NN1 ._. 
</s>
<s>
Thereafter_RT two_MC interviews_NN2 will_VM be_VBI conducted_VVN with_IW potential_JJ customers.This_NNU limits_VVZ the_AT data_NN and_CC results_NN2 to_TO be_VBI relevant_JJ only_RR at_II the_AT local_JJ market_NN1 ._. 
</s>
<s>
Method_NN1 In_BCL21 order_BCL22 to_TO gather_VVI data_NN a_AT1 preliminary_JJ interview_NN1 will_VM be_VBI conducted_VVN with_IW a_AT1 person_NN1 who_PNQS has_VHZ knowledge_NN1 of_IO online_JJ shops_NN2 ._. 
</s>
<s>
Thereafter_RT the_AT data_NN will_VM be_VBI analyzed_VVN and_CC key_JJ issues_NN2 are_VBR pointed_VVN out_RP in_BCL21 order_BCL22 to_TO be_VBI able_JJ create_VV0 more_RGR specific_JJ questions_NN2 for_IF two_MC additional_JJ interviews_NN2 with_IW potential_JJ customers_NN2 ._. 
</s>
<s>
The_AT preliminary_JJ interview_NN1 will_VM be_VBI totally_RR open_JJ ,_, where_CS the_AT respondent_NN1 has_VHZ a_AT1 chance_NN1 to_TO tell_VVI all_DB about_II online_JJ shops_NN2 and_CC their_APPGE customers_NN2 ._. 
</s>
<s>
The_AT two_MC other_JJ interviews_NN2 are_VBR semi-open_JJ ,_, where_CS the_AT questions_NN2 are_VBR based_VVN on_II the_AT results_NN2 of_IO the_AT preliminary_JJ interview_NN1 ._. 
</s>
<s>
The_AT data_NN will_VM be_VBI later_RRR analyzed_VVN and_CC compared_VVN with_IW the_AT theoretical_JJ framework_NN1 ._. 
</s>
<s>
The_AT theoretical_JJ framework_NN1 will_VM be_VBI built_VVN according_II21 to_II22 earlier_JJR research_NN1 about_II online_JJ shopping_NN1 ._. 
</s>
<s>
Theoretical_JJ framework_NN1 The_AT theoretical_JJ framework_NN1 will_VM be_VBI built_VVN under_II this_DD1 subtitle_NN1 ._. 
</s>
<s>
It_PPH1 will_VM be_VBI based_VVN on_II earlier_JJR studies_NN2 and_CC literature_NN1 about_II consumer_NN1 online_JJ shopping_NN1 ._. 
</s>
<s>
Online_JJ shopping_NN1 Theory_NN1 about_II consumer_NN1 behavior_NN1 online_JJ Data_NN gathering_VVG The_AT data_NN will_VM be_VBI gathered_VVN from_II interviews_NN2 ._. 
</s>
<s>
First_MD a_AT1 preliminary_JJ interview_NN1 will_VM be_VBI made_VVN to_TO confirm_VVI the_AT relevance_NN1 of_IO the_AT theoretical_JJ framework_NN1 ._. 
</s>
<s>
The_AT preliminary_JJ interview_NN1 will_VM be_VBI conducted_VVN as_II an_AT1 open_JJ interview_NN1 ,_, where_CS my_APPGE co-worker_NN1 tells_VVZ about_II aspects_NN2 ,_, which_DDQ attract_VV0 consumers_NN2 and_CC get_VV0 them_PPHO2 buy_VV0 online_RR ._. 
</s>
<s>
It_PPH1 works_VVZ also_RR as_II a_AT1 test_NN1 if_CS there_EX are_VBR additional_JJ aspects_NN2 that_CST were_VBDR not_XX included_VVN in_II the_AT theory_NN1 ._. 
</s>
<s>
More_RRR about_II the_AT preliminary_JJ interview_NN1 and_CC the_AT method_NN1 After_II the_AT preliminary_JJ interview_NN1 two_MC additional_JJ interviews_NN2 are_VBR conducted_VVN with_IW potential_JJ customers_NN2 within_II the_AT target_NN1 group_NN1 ._. 
</s>
<s>
Due_JJ to_TO lack_VVI of_IO time_NNT1 ,_, the_AT data_NN gathering_NN1 will_VM be_VBI a_RR21 bit_RR22 shallow_JJ and_CC wont_NN1 consider_VV0 that_CST large_JJ of_IO a_AT1 population_NN1 ._. 
</s>
<s>
To_TO get_VVI more_DAR data_NN ,_, one_PN1 could_VM conduct_VVI a_AT1 quantitative_JJ study_NN1 ._. 
</s>
<s>
However_RR ,_, the_AT analysis_NN1 would_VM take_VVI more_DAR time_NNT1 and_CC would_VM not_XX be_VBI relevant_JJ for_IF the_AT amount_NN1 of_IO work_NN1 needed_VVD to_TO conduct_VVI this_DD1 specific_JJ study_NN1 ._. 
</s>
<s>
A_AT1 laptop_NN1 will_VM be_VBI available_JJ if_CS the_AT respondents_NN2 have_VH0 problems_NN2 describing_VVG the_AT details_NN2 that_CST they_PPHS2 feel_VV0 are_VBR valuable_JJ ._. 
</s>
<s>
More_RRR about_II the_AT interviews_NN2 and_CC the_AT method_NN1 Interviews_NN2 The_AT preliminary_JJ interview_NN1 will_VM be_VBI made_VVN with_IW Emilia_NP1 Lindfors_NP1 ._. 
</s>
<s>
Lindfors_NN2 is_VBZ the_AT other_JJ person_NN1 who_PNQS founded_VVD an_AT1 online_JJ shop_NN1 with_IW me_PPIO1 ._. 
</s>
<s>
She_PPHS1 is_VBZ 23_MC years_NNT2 old_JJ and_CC studies_NN2 the_AT fourth_MD year_NNT1 at_II Svenska_NP1 Handelshgskolan_NP1 ._. 
</s>
<s>
The_AT two_MC other_JJ interviews_NN2 will_VM be_VBI made_VVN with_IW two_MC potential_JJ customers_NN2 ,_, as_RG earlier_RRR mentioned_VVN ._. 
</s>
<s>
The_AT other_JJ respondent_NN1 will_VM be_VBI my_APPGE brother_NN1 ,_, Alex_NP1 Ttterman_NP1 ._. 
</s>
<s>
Ttterman_NN1 is_VBZ 21_MC years_NNT2 old_JJ and_CC studies_NN2 business_NN1 at_II Arcada_NP1 ._. 
</s>
<s>
The_AT other_JJ respondent_NN1 will_VM be_VBI Daniel_NP1 Remy_NP1 ._. 
</s>
<s>
Remy_NP1 is_VBZ an_AT1 old_JJ friend_NN1 who_PNQS is_VBZ close_JJ to_II end_NN1 his_APPGE studies_NN2 at_II Hanken_NP1 ._. 
</s>
<s>
Analysis_NN1 of_IO the_AT data_NN After_II the_AT preliminary_JJ interview_NN1 the_AT data_NN will_VM be_VBI compared_VVN with_IW the_AT theoretical_JJ framework_NN1 ._. 
</s>
<s>
With_IW this_DD1 I_PPIS1 will_VM confirm_VVI that_CST the_AT theoretical_JJ framework_NN1 is_VBZ relevant_JJ ._. 
</s>
<s>
Also_RR new_JJ aspects_NN2 can_VM be_VBI considered_VVN if_CS there_EX are_VBR any_DD ._. 
</s>
<s>
After_CS the_AT whole_JJ data_NN has_VHZ been_VBN gathered_VVN ,_, it_PPH1 will_VM be_VBI analyzed_VVN ._. 
</s>
<s>
The_AT results_NN2 will_VM be_VBI thereafter_RT compared_VVN to_II the_AT theoretical_JJ framework_NN1 ._. 
</s>
<s>
If_CS there_EX are_VBR similarities_NN2 with_IW the_AT framework_NN1 ,_, they_PPHS2 will_VM be_VBI pointed_VVN out_RP ._. 
</s>
<s>
More_RRR about_II analysis_NN1 Discussion_NN1 Conclustion_NN1 Further_JJR research_NN1 
</s>
