<s>
Are_VBR Finnish_JJ CEOs_NN2 overpaid_VVN ?_? 1_MC1 ._. 
</s>
<s>
Introduction_NN1 The_AT discussion_NN1 around_II widening_JJ income_NN1 gaps_NN2 has_VHZ been_VBN ongoing_JJ for_IF ages_NN2 but_CCB especially_RR in_II recent_JJ years_NNT2 it_PPH1 has_VHZ become_VVN an_AT1 even_RR bigger_JJR issue_NN1 for_IF many_DA2 people_NN ._. 
</s>
<s>
Without_IW a_AT1 doubt_NN1 one_MC1 of_IO the_AT reasons_NN2 behind_II the_AT widely_RR spread_VV0 discussion_NN1 is_VBZ the_AT enormous_JJ salaries_NN2 of_IO some_DD executive_NN1 directors_NN2 ,_, and_CC of_RR21 course_RR22 other_JJ people_NN earning_VVG hundreds_NNO2 of_IO thousands_NNO2 or_CC up_II21 to_II22 several_DA2 millions_NNO2 as_II salary_NN1 and_CC bonuses_NN2 ._. 
</s>
<s>
The_AT still_JJ ongoing_JJ financial_JJ crisis_NN1 has_VHZ escalated_VVN the_AT top_JJ management_NN1 remuneration_NN1 discussion_NN1 for_IF several_DA2 years_NNT2 already_RR ._. 
</s>
<s>
The_AT current_JJ financial_JJ crisis_NN1 blew_VVD up_RP in_II 2007_MC when_RRQ the_AT CDO_NN1 market_NN1 in_II the_AT US_NP1 started_VVD to_TO decelerate_VVI ._. 
</s>
<s>
That_DD1 is_VBZ only_RR six_MC years_NNT2 after_CS we_PPIS2 witnessed_VVD the_AT collapse_NN1 of_IO Enron_NN1 ._. 
</s>
<s>
In_II some_DD sense_NN1 the_AT problem_NN1 with_IW these_DD2 two_MC cases_NN2 is_VBZ the_AT same_DA ,_, the_AT generous_JJ remuneration_NN1 packages_NN2 presented_VVN for_IF CEOs_NN2 and_CC other_JJ key_JJ persons_NN2 drove_VVD people_NN to_TO take_VVI huge_JJ short_RR sighted_VVN risks_NN2 ._. 
</s>
<s>
Since_CS Enron_NP1 bankruptcy_NN1 the_AT remuneration_NN1 practices_NN2 have_VH0 been_VBN developing_VVG to_II a_AT1 direction_NN1 where_RRQ the_AT managers_NN2 remuneration_NN1 is_VBZ increasingly_RR tide_NN1 to_II a_AT1 long_JJ term_NN1 performance_NN1 of_IO the_AT company_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ definitely_RR an_AT1 improvement_NN1 in_II the_AT system_NN1 but_CCB it_PPH1 still_RR has_VHZ its_APPGE flaws_NN2 ._. 
</s>
<s>
During_II the_AT beginning_NN1 of_IO year_NNT1 2012_MC we_PPIS2 have_VH0 had_VHN two_MC peculiar_JJ corporate_JJ governance-cases_NN2 in_II Finland_NP1 where_RRQ state-owned_JJ companies_NN2 have_VH0 been_VBN involved_JJ in_II ._. 
</s>
<s>
The_AT first_MD one_PN1 was_VBDZ a_AT1 mortgage_NN1 deal_NN1 made_VVN between_II the_AT CEO_NN1 of_IO Finnair_NP1 ,_, Mika_NP1 Vehvilinen_NP1 and_CC the_AT pension_NN1 fund_NN1 Ilmarinen_NN1 and_CC the_AT second_MD one_PN1 was_VBDZ the_AT remuneration_NN1 of_IO the_AT CEO_NN1 of_IO Stora_NP1 Enso_NP1 ,_, JoukoKarvinen_NP1 ._. 
</s>
<s>
Vehvilinen_NN1 is_VBZ a_AT1 member_NN1 in_II the_AT supervisory_JJ board_NN1 of_IO Ilmarinen_NP1 and_CC then_RT again_RT the_AT CEO_NN1 of_IO Ilmarinen_NP1 ,_, HarriSailas_NP2 is_VBZ the_AT cahirman_NN1 in_II the_AT board_NN1 of_IO directors_NN2 in_II Finnair_NP1 ._. 
</s>
<s>
The_AT outcome_NN1 of_IO this_DD1 was_VBDZ that_RG 23.2.2012_MC Vehvilinen_NP1 announced_VVD that_CST he_PPHS1 will_VM not_XX continue_VVI as_II a_AT1 member_NN1 of_IO thesupervisory_JJ board_NN1 of_IO Ilmarinen_NN1 ._. 
</s>
<s>
This_DD1 case_NN1 is_VBZ a_AT1 good_JJ example_NN1 of_IO the_AT problem_NN1 that_CST the_AT Finnish_JJ business_NN1 sector_NN1 have_VH0 concerning_II the_AT top_JJ management_NN1 and_CC boards_NN2 of_IO directors_NN2 ._. 
</s>
<s>
In_II my_APPGE opinion_NN1 the_AT problem_NN1 is_VBZ that_DD1 top_JJ management_NN1 persons_NN2 in_II Finland_NP1 are_VBR so_RG few_DA2 that_CST the_AT ones_NN2 that_CST exist_VV0 are_VBR monitoring_VVG each_PPX221 other_PPX222 on_II operational_JJ management_NN1 posts_NN2 and_CC boards_NN2 of_IO directors_NN2 ._. 
</s>
<s>
The_AT discussion_NN1 in_II Finland_NP1 is_VBZ two-parted_JJ ,_, on_II the_AT one_MC1 hand_NN1 we_PPIS2 have_VH0 regular_JJ publicly_RR listed_JJ companies_NN2 that_CST pay_VV0 big_JJ compensation_NN1 to_II a_AT1 small_JJ group_NN1 of_IO employees_NN2 and_CC on_II the_AT other_JJ hand_NN1 we_PPIS2 have_VH0 state_NN1 owned_VVN companies_NN2 ,_, which_DDQ are_VBR also_RR publicly_RR listed_VVN ,_, that_CST pay_VV0 maybe_RR even_RR bigger_JJR compensation_NN1 to_II their_APPGE executives_NN2 and_CC other_JJ key_JJ employees_NN2 ._. 
</s>
<s>
Despite_II the_AT split_NN1 up_RP between_II state-owned_JJ and_CC private_JJ owned_JJ companies_NN2 the_AT problem_NN1 for_IF these_DD2 two_MC types_NN2 is_VBZ the_AT same_DA ._. 
</s>
<s>
The_AT second_MD case_NN1 of_IO doubtful_JJ CEO_NN1 remuneration_NN1 came_VVD out_RP on_II Tuesday_NPD1 21.2.2012_MC where_RRQ HelsinginSanomat_NP1 wrote_VVD that_CST the_AT CEO_NN1 of_IO Stora_NP1 Enso_NP1 ,_, JoukoKarvinen_NP1 had_VHD an_AT1 increase_NN1 in_II his_APPGE salary_NN1 of_IO 132%_NNU in_II year_NNT1 2011_MC ._. 
</s>
<s>
HelsinginSanomat_NP1 calculated_VVD that_CST Karvinens_NP1 earnings_NN2 were_VBDR the_AT same_DA as_CSA the_AT salary_NN1 of_IO 42_MC highly_RR experienced_JJ paper_NN1 machine_NN1 workers_NN2 ._. 
</s>
<s>
His_APPGE earnings_NN2 were_VBDR approximately_RR 1_MC1 million_NNO euros_NN2 and_CC he_PPHS1 got_VVD a_AT1 bonus_NN1 that_CST was_VBDZ almost_RR 2_MC million_NNO euros_NN2 ._. 
</s>
<s>
At_II the_AT same_DA time_NNT1 the_AT companys_NN2 net_JJ profit_NN1 (_( before_CS extraordinary_JJ items_NN2 )_) shrunk_VVN 56%_NNU from_II 769,3_MC million_NNO euros_NN2 to_II 342,2_MC million_NNO euros_NN2 ._. 
</s>
<s>
With_IW these_DD2 figures_NN2 one_PN1 has_VHZ to_TO wonder_VVI ifKarvinen_JJ and_CC other_JJ CEOs_NN2 are_VBR overpaid_VVN ._. 
</s>
<s>
On_II31 top_II32 of_II33 the_AT fuzz_NN1 caused_VVN of_IO Karvinens_NP1 big_JJ remuneration_NN1 in_II year_NNT1 2011_MC HelsinginSanomat_NP1 pointed_VVD out_RP on_II Wednesday_NPD1 22.2.2012_MC that_CST the_AT State_NN1 of_IO Finland_NP1 is_VBZ one_PN1 the_AT largest_JJT shareholder_NN1 in_II Stora_NP1 Enso_NP1 through_II Solidium_NP1 and_CC KELA_NP1 (_( The_AT Social_JJ Insurance_NN1 Institution_NN1 of_IO Finland_NP1 )_) ._. 
</s>
<s>
The_AT problem_NN1 is_VBZ that_CST Stora_NP1 Enso_NP1 has_VHZ given_VVN Karvinen_NN1 a_AT1 higher_JJR performance_NN1 bonus_NN1 than_CSN what_DDQ is_VBZ the_AT state-owners_NN2 instruction_NN1 ._. 
</s>
<s>
According_II21 to_II22 the_AT Cabinet_NN1 Committee_NN1 on_II Economic_JJ Policy_NN1 ,_, the_AT maximum_JJ level_NN1 of_IO annual_JJ performance_NN1 bonuses_NN2 in_II state-owned_JJ companies_NN2 is_VBZ 40%_NNU of_IO the_AT annual_JJ basic_JJ salary_NN1 but_CCB Stora_NP1 Enso_NP1 paid_VVD Karvinen_JJ 60%_NNU ._. 
</s>
<s>
Stora_NP1 Enso_NP1 did_VDD not_XX however_RR break_VVI their_APPGE own_DA rules_NN2 ,_, which_DDQ give_VV0 them_PPHO2 the_AT right_NN1 to_TO pay_VVI the_AT CEO_NN1 70%_NNU performance_NN1 bonus_NN1 ._. 
</s>
<s>
1.1_MC Aim_NN1 of_IO the_AT study_NN1 My_APPGE purpose_NN1 in_II this_DD1 paper_NN1 is_VBZ to_TO make_VVI an_AT1 assessment_NN1 if_CS the_AT CEOs_NN2 of_IO Finnish_JJ publicly_RR listed_JJ companies_NN2 are_VBR overpaid_VVN or_CC not.My_NNU main_JJ point_NN1 of_IO view_NN1 will_VM not_XX be_VBI the_AT same_DA as_CSA Kaplan_NP1 had_VHD in_II his_APPGE study_NN1 done_VDN 2008_MC Are_VBR U.S._NP1 CEOs_NN2 overpaid_VVN ?_? ._. 
</s>
<s>
Kaplan_NP1 discussed_VVD mainly_RR around_II the_AT topic_NN1 if_CS U.S._NP1 CEOs_NN2 are_VBR overpaid_VVN compared_VVN to_II CEOs_NN2 in_II other_JJ countries.My_NNU intention_NN1 is_VBZ to_TO evaluate_VVI if_CS one_MC1 person_NN1 is_VBZ that_DD1 valuable_JJ to_II a_AT1 company_NN1 or_CC not_XX ._. 
</s>
<s>
The_AT measurement_NN1 of_IO one_MC1 persons_VVZ value_NN1 is_VBZ difficult_JJ to_TO measure_VVI as_CSA it_PPH1 has_VHZ to_TO be_VBI done_VDN as_II a_AT1 qualitative_JJ analysis_NN1 instead_II21 of_II22 a_AT1 quantitative_JJ analysis_NN1 ._. 
</s>
<s>
1.2_MC Limitations_NN2 Due_II21 to_II22 time_NNT1 limitations_NN2 I_PPIS1 will_VM have_VHI focus_NN1 on_II Finnish_JJ publicly_RR listed_JJ companies_NN2 that_CST are_VBR currently_RR in_II the_AT OMX_NP1 Helsinki_NP1 25_MC index_NN1 ._. 
</s>
<s>
The_AT index_NN1 includes_VVZ 25_MC most_RGT traded_JJ stocks_NN2 in_II OMX_NP1 Helsinki_NP1 ._. 
</s>
<s>
The_AT companies_NN2 studied_VVN in_II this_DD1 paper_NN1 are_VBR listed_VVN in_II Table_NN1 1_MC1 ._. 
</s>
<s>
I_PPIS1 have_VH0 also_RR excluded_VVN Nordea_NP1 Bank_NN1 and_CC TeliaSonera_NP1 from_II the_AT empirical_JJ part_NN1 because_II21 of_II22 them_PPHO2 being_VBG located_VVN abroad_RL ._. 
</s>
<s>
The_AT earnings_NN2 of_IO the_AT CEOs_NN2 of_IO these_DD2 two_MC companies_NN2 were_VBDR not_XX available_JJ for_IF the_AT whole_JJ research_NN1 period_NN1 ._. 
</s>
<s>
1.3_MC Structure_NN1 of_IO the_AT study_NN1 I_PPIS1 will_VM begin_VVI with_IW the_AT theory_NN1 closely_RR related_VVN to_II the_AT topic_NN1 ._. 
</s>
<s>
This_DD1 includes_VVZ basic_JJ theory_NN1 around_II corporate_JJ governance_NN1 ,_, some_DD special_JJ features_NN2 with_IW state-owned_JJ companies_NN2 ,_, the_AT purpose_NN1 of_IO the_AT board_NN1 of_IO directors_NN2 and_CC some_DD things_NN2 related_VVN to_II these_DD2 ._. 
</s>
<s>
After_CS the_AT theory_NN1 I_PPIS1 will_VM make_VVI some_DD comparison_NN1 between_II the_AT CEO_NN1 salaries_NN2 and_CC the_AT performance_NN1 of_IO the_AT company_NN1 in_II question_NN1 ._. 
</s>
<s>
This_DD1 gives_VVZ a_AT1 good_JJ insight_NN1 regarding_II the_AT correlation_NN1 between_II the_AT CEO_NN1 salary_NN1 and_CC the_AT performance_NN1 of_IO the_AT company_NN1 ,_, do_VD0 they_PPHS2 go_VVI hand_NN1 in_II hand_NN1 or_CC can_VM there_EX be_VBI seen_VVN some_DD skew_NN1 towards_II some_DD direction_NN1 ._. 
</s>
<s>
In_II other_JJ words_NN2 this_DD1 gives_VVZ a_AT1 good_JJ picture_NN1 if_CS the_AT CEOs_NN2 salary_NN1 follows_VVZ the_AT performance_NN1 of_IO the_AT company_NN1 ._. 
</s>
<s>
After_CS this_DD1 I_PPIS1 will_VM try_VVI to_TO evaluate_VVI the_AT input_NN1 of_IO a_AT1 certain_JJ CEO_NN1 for_IF a_AT1 company_NN1 ._. 
</s>
<s>
1.4_MC Problems_NN2 with_IW the_AT study_NN1 The_AT study_NN1 has_VHZ some_DD big_JJ problems_NN2 that_CST might_VM affect_VVI the_AT results_NN2 of_IO the_AT empirical_JJ part_NN1 of_IO the_AT study_NN1 ._. 
</s>
<s>
The_AT first_MD and_CC biggest_JJT problem_NN1 is_VBZ the_AT valuation_NN1 of_IO a_AT1 CEO_NN1 to_II a_AT1 company_NN1 ._. 
</s>
<s>
Usually_RR the_AT work_NN1 of_IO a_AT1 CEO_NN1 does_VDZ not_XX include_VVI tasks_NN2 that_CST can_VM be_VBI valued_VVN quantitatively_RR but_CCB the_AT tasks_NN2 use_VV0 to_TO be_VBI qualitatively_RR measurable.YrjKopra_NNU ,_, the_AT CEO_NN1 of_IO Alexander_NP1 Corporate_JJ Finance_NN1 ,_, a_AT1 company_NN1 which_DDQ plans_VVZ remuneration_NN1 programs_NN2 ,_, says_VVZ that_CST the_AT added_JJ value_NN1 that_CST a_AT1 certain_JJ CEO_NN1 brings_VVZ to_II a_AT1 company_NN1 can_VM probably_RR not_XX ever_RR be_VBI measured_VVN with_IW scientific_JJ accuracy_NN1 ._. 
</s>
<s>
The_AT second_MD problem_NN1 is_VBZ the_AT access_NN1 to_II CEO_NN1 salaries_NN2 and_CC remuneration_NN1 packages_NN2 ._. 
</s>
<s>
The_AT remuneration_NN1 packages_NN2 are_VBR relatively_RR complex_JJ and_CC thus_RR the_AT valuation_NN1 and_CC sorting_VVG out_II21 of_II22 these_DD2 can_VM be_VBI difficult_JJ ._. 
</s>
<s>
The_AT complexity_NN1 and_CC the_AT fact_NN1 that_CST the_AT packages_NN2 are_VBR based_VVN on_II long-term_JJ performance_NN1 lead_VV0 also_RR to_II a_AT1 problem_NN1 in_II comparing_VVG the_AT CEO_NN1 salary_NN1 and_CC the_AT company_NN1 performance_NN1 each_DD1 year_NNT1 ._. 
</s>
<s>
The_AT long-term_JJ CEO_NN1 remuneration_NN1 leads_VVZ to_II that_DD1 payments_NN2 related_VVN to_II a_AT1 certain_JJ year_NNT1 are_VBR realized_VVN in_II another_DD1 year_NNT1 which_DDQ again_RT makes_VVZ the_AT comparison_NN1 between_II CEO_NN1 remuneration_NN1 and_CC company_NN1 performance_NN1 difficult_JJ ._. 
</s>
<s>
The_AT limitation_NN1 of_IO studied_JJ companies_NN2 can_VM also_RR skew_VVI the_AT empirical_JJ results_NN2 because_CS the_AT studied_JJ companies_NN2 are_VBR among_II the_AT biggest_JJT in_II the_AT OMX_NP1 Helsinki_NP1 exchange_NN1 ._. 
</s>
<s>
The_AT payoff_NN1 for_IF CEOs_NN2 in_II OMX_NP1 Helsinki_NP1 25_MC companies_NN2 is_VBZ probably_RR on_II average_JJ higher_JJR than_CSN for_IF all_DB CEOs_NN2 in_II OMX_NP1 Helsinki_NP1 companies_NN2 ._. 
</s>
<s>
Despite_II this_DD1 I_PPIS1 think_VV0 the_AT empirical_JJ part_NN1 is_VBZ at_RR21 least_RR22 indicative_JJ for_IF all_DB companies_NN2 in_II OMX_NP1 Helsinki_NP1 ._. 
</s>
<s>
2_MC Corporate_JJ Governance_NN1 in_II Finland_NP1 The_AT good_JJ corporate_JJ governance_NN1 in_II Finland_NP1 consists_VVZ of_IO three_MC main_JJ factors_NN2 ,_, the_AT Finnish_JJ legislation_NN1 ,_, remarkable_JJ EU_NP1 directives_NN2 and_CC the_AT Finnish_JJ Corporate_JJ Governance_NN1 Code_NN1 2010_MC ._. 
</s>
<s>
The_AT central_JJ legislations_NN2 for_IF listed_JJ companies_NN2 in_II Finland_NP1 are_VBR the_AT Companies_NN2 Act_VV0 ,_, the_AT Security_NN1 Markets_NN2 Act_VV0 ,_, the_AT Auditing_NN1 Act_NN1 and_CC the_AT Accounting_NN1 Act_NN1 ._. 
</s>
<s>
The_AT most_RGT noticeable_JJ EU_NP1 directives_NN2 are_VBR the_AT fourth_MD company_NN1 law_NN1 directive_NN1 and_CC the_AT directive_NN1 on_II shareholders_NN2 rights_NN2 ._. 
</s>
<s>
As_CSA I_PPIS1 call_VV0 it_PPH1 ,_, the_AT Finnish_JJ corporate_JJ governance_NN1 problem_NN1 ._. 
</s>
<s>
As_CSA shortly_RR described_VVN in_II the_AT introduction_NN1 ,_, the_AT Finnish_JJ business_NN1 society_NN1 is_VBZ so_RG small_JJ that_CST the_AT top_JJ management_NN1 is_VBZ supervising_VVG each_PPX221 other_PPX222 in_II different_JJ companies_NN2 ._. 
</s>
<s>
This_DD1 is_VBZ a_AT1 problem_NN1 that_CST has_VHZ been_VBN recognized_VVN for_IF almost_RR a_AT1 hundred_NNO years_NNT2 ago_RA ._. 
</s>
<s>
In_II the_AT beginning_NN1 of_IO 20th_MD century_NNT1 companies_NN2 grew_VVD in_II scale_NN1 ,_, became_VVD more_RGR diverse_JJ and_CC spread_VV0 geographically_RR ,_, so_RR did_VDD their_APPGE public_JJ shareholders_NN2 ._. 
</s>
<s>
It_PPH1 was_VBDZ not_XX feasible_JJ for_IF the_AT large_JJ number_NN1 of_IO shareholders_NN2 ,_, located_VVN around_II the_AT country_NN1 and_CC sometimes_RT around_II the_AT world_NN1 ,_, to_TO influence_VVI decisions_NN2 on_II directors_NN2 appointment_NN1 or_CC re-appointment_NN1 ._. 
</s>
<s>
The_AT directors_NN2 of_IO major_JJ listed_JJ companies_NN2 were_VBDR now_RT being_VBG chosen_VVN by_II the_AT existing_JJ directors_NN2 ,_, particularly_RR the_AT executive_NN1 directors_NN2 ,_, and_CC routinely_RR approved_VVN by_II shareholders_NN2 in_II their_APPGE annual_JJ general_JJ meeting_NN1 ._. 
</s>
<s>
Critics_NN2 complained_VVD that_CST boards_NN2 can_VM become_VVI self-perpetuating_JJ clubs_NN2 of_IO like-minded_JJ people_NN ,_, routinely_RR chosen_VVN from_II small_JJ networks_NN2 of_IO influence_NN1 ._. 
</s>
<s>
This_DD1 problem_NN1 was_VBDZ widely_RR noticed_VVN all_RR over_II the_AT world_NN1 ,_, in_II the_AT US_NP1 ,_, UK_NP1 and_CC France_NP1 ._. 
</s>
<s>
Unfortunately_RR this_DD1 is_VBZ the_AT present_JJ state_NN1 in_II Finland_NP1 despite_II globalization_NN1 and_CC the_AT foreign_JJ owners_NN2 of_IO Finnish_JJ listed_JJ companies_NN2 ._. 
</s>
<s>
Some_DD critics_NN2 of_IO the_AT system_NN1 in_II Finland_NP1 have_VH0 demanded_VVN for_IF more_RGR foreign_JJ members_NN2 in_II the_AT boards_NN2 ._. 
</s>
<s>
This_DD1 would_VM be_VBI an_AT1 easy_JJ and_CC efficient_JJ way_NN1 to_TO broaden_VVI the_AT member_NN1 base_NN1 in_II the_AT boards_NN2 of_IO Finnish_JJ companies_NN2 ._. 
</s>
<s>
Among_II others_NN2 a_AT1 member_NN1 of_IO parliament_NN1 ,_, Ben_NP1 Zyskowicz_NP1 has_VHZ criticized_VVN the_AT situation_NN1 in_II Finland_NP1 ._. 
</s>
<s>
He_PPHS1 has_VHZ said_VVN that_CST the_AT salaries_NN2 of_IO CEOs_NN2 are_VBR rising_VVG because_CS there_EX are_VBR friends_NN2 improving_VVG each_PPX221 other_PPX222 remuneration_NN1 packages_NN2 ._. 
</s>
<s>
2.1_MC The_AT Finnish_JJ corporate_JJ governance_NN1 code_NN1 The_AT first_MD corporate_JJ governance_NN1 recommendation_NN1 was_VBDZ issued_VVN in_II 1997_MC by_II the_AT Central_JJ Chamber_NN1 of_IO Commerce_NN1 of_IO Finland_NP1 and_CC the_AT then_JJ Confederation_NN1 of_IO Finnish_JJ Industry_NN1 and_CC Employers_NN2 (_( nowadays_RT the_AT Confederation_NN1 of_IO Finnish_JJ Industries_NN2 EK_VV0 )_) ._. 
</s>
<s>
In_II the_AT beginning_NN1 of_IO 2003_MC the_AT significance_NN1 and_CC international_JJ development_NN1 of_IO the_AT Corporate_JJ Governance_NN1 practices_NN2 grew_VVD and_CC led_VVN to_II that_CST a_AT1 working_JJ group_NN1 was_VBDZ established_VVN for_IF amending_VVG the_AT recommendations_NN2 ._. 
</s>
<s>
Therefore_RR a_AT1 new_JJ recommendation_NN1 was_VBDZ published_VVN in_II December_NPM1 2003_MC ._. 
</s>
<s>
The_AT recommendation_NN1 issued_VVN in_II 2003_MC worked_VVD well_RR and_CC it_PPH1 met_VVD the_AT high_JJ international_JJ standards_NN2 but_CCB as_CSA the_AT regulation_NN1 changed_VVN and_CC the_AT markets_NN2 developed_VVD was_VBDZ it_PPH1 again_RT time_NNT1 to_TO update_VVI the_AT recommendation_NN1 ._. 
</s>
<s>
The_AT Board_NN1 of_IO the_AT Securities_NN2 Market_VV0 Association_NN1 appointed_VVN a_AT1 working_JJ group_NN1 to_TO review_VVI the_AT recommendation_NN1 and_CC a_AT1 new_JJ version_NN1 was_VBDZ approved_VVN in_II October_NPM1 2008_MC ._. 
</s>
<s>
Once_RR21 again_RR22 in_II 2009_MC a_AT1 working_JJ group_NN1 was_VBDZ established_VVN to_TO prepare_VVI self-regulation_NN1 in_II31 relation_II32 to_II33 remuneration_NN1 of_IO listed_JJ companies_NN2 directors_NN2 due_II21 to_II22 international_JJ development_NN1 of_IO directors_NN2 remuneration_NN1 ._. 
</s>
<s>
The_AT Securities_NN2 Markets_NN2 Association_NN1 approved_VVD the_AT Finnish_JJ Corporate_JJ Governance_NN1 Code_NN1 2010_MC as_II the_AT latest_JJT version_NN1 of_IO the_AT recommendation_NN1 in_II June_NPM1 2010_MC ._. 
</s>
<s>
The_AT state-owned_JJ companies_NN2 are_VBR not_XX following_VVG the_AT Finnish_JJ Corporate_JJ Governance_NN1 Code_NN1 2010_MC but_CCB the_AT owner_NN1 control_NN1 has_VHZ been_VBN centralized_VVN to_II the_AT Owner_NN1 Control_NN1 Department_NN1 of_IO the_AT chancellery_NN1 of_IO Council_NN1 of_IO State_NN1 in_II 2007._MC the_AT states_NN2 procedure_NN1 for_IF nominating_VVG the_AT board_NN1 member_NN1 candidates_NN2 has_VHZ been_VBN cleared_VVN in_II the_AT Ministerial_JJ Committee_NN1 for_IF Economic_JJ Policys_NN2 statement_NN1 Nominating_VVG the_AT Board_NN1 Member_NN1 Candidates_NN2 of_IO state-owned_JJ companies_NN2 and_CC associated_JJ companies_NN2 (_( 17.2.2004_MC )_) ._. 
</s>
<s>
3_MC Organizational_JJ design_NN1 From_II a_AT1 corporate_JJ governance_NN1 perspective_NN1 the_AT corporate_JJ architecture_NN1 can_VM be_VBI divided_VVN in_II three_MC key_JJ elements_NN2 :_: The_AT assignment_NN1 of_IO decision-making_JJ authority_NN1 Performance_NN1 evaluation_NN1 Compensation_NN1 structure_NN1 These_DD2 three_MC main_JJ points_NN2 are_VBR devised_VVN and_CC concluded_VVN by_II the_AT owners_NN2 ,_, boards_NN2 of_IO directors_NN2 and_CC board_NN1 committees_NN2 ._. 
</s>
<s>
The_AT owners_NN2 assign_VV0 the_AT decision-making_JJ authorities_NN2 and_CC the_AT board_NN1 and_CC the_AT committees_NN2 build_VV0 up_RP the_AT remuneration_NN1 structure_NN1 and_CC evaluate_VV0 the_AT performance_NN1 ._. 
</s>
<s>
In_II the_AT next_MD part_NN1 the_AT above_JJ mentioned_VVD groups_NN2 are_VBR shortly_RR presented_VVN ._. 
</s>
<s>
3.1_MC Shareholders_NN2 Shareholders_NN2 invest_VV0 in_II the_AT company_NN1 and_CC thus_RR they_PPHS2 are_VBR a_AT1 vital_JJ part_NN1 of_IO a_AT1 companys_NN2 funding_NN1 ._. 
</s>
<s>
Monitoring_VVG shareholder_NN1 rights_NN2 is_VBZ one_MC1 of_IO the_AT essential_JJ reasons_NN2 why_RRQ corporate_JJ governance_NN1 has_VHZ evolved_VVN to_II the_AT form_NN1 it_PPH1 nowadays_RT is_VBZ in_RP ._. 
</s>
<s>
The_AT current_JJ premier_JJ business_NN1 mantra_NN1 is_VBZ maximizing_VVG shareholder_NN1 value_NN1 and_CC thus_RR the_AT role_NN1 of_IO shareholder_NN1 rights_NN2 has_VHZ become_VVN more_RGR crucial_JJ ._. 
</s>
<s>
3.2_MC Board_NN1 of_IO directors_NN2 The_AT Board_NN1 of_IO Directors_NN2 is_VBZ responsible_JJ for_IF the_AT administration_NN1 and_CC the_AT proper_JJ organization_NN1 of_IO the_AT operations_NN2 of_IO the_AT company_NN1 ._. 
</s>
<s>
The_AT board_NN1 also_RR supervises_VVZ and_CC controls_VVZ the_AT operative_JJ management_NN1 of_IO the_AT company_NN1 ,_, appoints_VVZ and_CC dismisses_VVZ the_AT managing_JJ director_NN1 ,_, approves_VVZ the_AT strategic_JJ goals_NN2 and_CC the_AT principles_NN2 of_IO risk_NN1 management_NN1 for_IF the_AT company_NN1 and_CC ensures_VVZ the_AT proper_JJ operation_NN1 of_IO the_AT management_NN1 system_NN1 ._. 
</s>
<s>
According_II21 to_II22 good_JJ corporate_JJ governance_NN1 ,_, the_AT board_NN1 also_RR ensures_VVZ that_CST the_AT company_NN1 has_VHZ duly_RR endorsed_VVN the_AT corporate_JJ values_NN2 applied_VVN to_II its_APPGE operations_NN2 ._. 
</s>
<s>
The_AT duty_NN1 of_IO the_AT board_NN1 is_VBZ to_TO promote_VVI the_AT best_JJT interest_NN1 of_IO the_AT company_NN1 and_CC all_DB its_APPGE shareholders_NN2 ._. 
</s>
<s>
The_AT boards_NN2 of_IO directors_NN2 have_VH0 a_AT1 legal_JJ responsibility_NN1 to_TO make_VVI decisions_NN2 on_II31 behalf_II32 of_II33 shareholders_NN2 and_CC to_TO adopt_VVI performance_NN1 measures_NN2 and_CC compensation_NN1 plans_VVZ that_CST provide_VV0 managers_NN2 with_IW cost-effective_JJ incentives_NN2 to_TO maximize_VVI current_JJ and_CC future_JJ cash_NN1 flows_NN2 ._. 
</s>
<s>
The_AT general_JJ meeting_NN1 of_IO the_AT company_NN1 shall_VM elect_VVI the_AT directors_NN2 in_II the_AT board_NN1 ._. 
</s>
<s>
By_II electing_VVG the_AT directors_NN2 ,_, the_AT shareholders_NN2 contribute_VV0 to_II the_AT administration_NN1 of_IO the_AT company_NN1 ,_, and_CC thereby_RR to_II the_AT operations_NN2 of_IO the_AT entire_JJ company_NN1 ,_, directly_RR and_CC efficiently_RR ._. 
</s>
<s>
This_DD1 statement_NN1 works_VVZ in_II theory_NN1 but_CCB the_AT reality_NN1 is_VBZ something_PN1 else_RR ._. 
</s>
<s>
The_AT boards_NN2 of_IO Finnish_JJ listed_JJ companies_NN2 usually_RR consist_VV0 of_IO non-executive_JJ directors_NN2 but_CCB there_EX can_VM be_VBI found_VVN some_DD exceptions_NN2 ._. 
</s>
<s>
For_REX21 example_REX22 two_MC of_IO the_AT OMX_NP1 Helsinki_NP1 25_MC companies_NN2 have_VH0 their_APPGE CEOs_NN2 also_RR as_CSA members_NN2 of_IO the_AT Board_NN1 of_IO Directors_NN2 ,_, these_DD2 are_VBR JussiPesonen_JJ in_II UPM-Kymmene_NP1 and_CC Kim_NP1 Gran_NN1 in_II NokianRenkaat._NP1 3.2.1_MC Board_NN1 Committees_NN2 In_II recent_JJ years_NNT2 the_AT corporate_JJ governance_NN1 has_VHZ gone_VVN through_II an_AT1 important_JJ development_NN1 phase_NN1 in_II form_NN1 of_IO formalization_NN1 of_IO board_NN1 committees_NN2 ._. 
</s>
<s>
The_AT three_MC principal_JJ committees_NN2 are_VBR the_AT audit_NN1 committee_NN1 ,_, the_AT remuneration_NN1 committee_NN1 and_CC the_AT nominating_NN1 committee_NN1 ._. 
</s>
<s>
These_DD2 committees_NN2 have_VH0 been_VBN established_VVN for_IF specific_JJ purposes_NN2 ._. 
</s>
<s>
Each_DD1 of_IO these_DD2 committees_NN2 focus_VV0 on_II essential_JJ parts_NN2 of_IO the_AT company_NN1 in_II question_NN1 but_CCB despite_II that_DD1 there_EX are_VBR the_AT same_DA members_NN2 making_VVG the_AT decisions_NN2 ._. 
</s>
<s>
The_AT indisputable_JJ benefit_NN1 of_IO these_DD2 committees_NN2 is_VBZ that_CST by_II using_VVG them_PPHO2 ,_, the_AT board_NN1 is_VBZ able_JK to_TO focus_VVI the_AT knowhow_NN1 of_IO members_NN2 to_II matters_NN2 that_CST they_PPHS2 are_VBR specialized_VVN in_RP ._. 
</s>
<s>
According_II21 to_II22 the_AT recommendation_NN1 of_IO the_AT Finnish_JJ Corporate_JJ Governance_NN1 Code_NN1 2010_MC each_DD1 committee_NN1 should_VM have_VHI at_RR21 least_RR22 three_MC members_NN2 and_CC the_AT members_NN2 of_IO the_AT committee_NN1 shall_VM have_VHI expertise_NN1 and_CC experience_NN1 required_VVN by_II the_AT duties_NN2 of_IO the_AT committee_NN1 ._. 
</s>
<s>
This_DD1 recommendation_NN1 ensures_VVZ that_CST all_DB of_IO the_AT committees_NN2 have_VH0 skilled_JJ and_CC talented_JJ members_NN2 making_VVG the_AT decisions_NN2 ._. 
</s>
<s>
In_II41 the_II42 light_II43 of_II44 this_DD1 information_NN1 should_VM there_EX be_VBI no_AT question_NN1 concerning_II the_AT remuneration_NN1 of_IO CEOs_NN2 in_II Finnish_JJ listed_JJ companies_NN2 ._. 
</s>
<s>
3.3_MC Operational_JJ Management_NN1 The_AT operational_JJ management_NN1 consists_VVZ of_IO people_NN who_PNQS are_VBR in_II31 charge_II32 of_II33 the_AT business_NN1 day_NNT1 to_II day_NNT1 activity_NN1 and_CC the_AT Chief_JJ Executive_NN1 Officer_NN1 is_VBZ the_AT highest_JJT ranked_JJ manager_NN1 in_II the_AT whole_JJ company_NN1 ._. 
</s>
<s>
The_AT operational_JJ management_NN1 is_VBZ managed_VVN and_CC supervised_VVN by_II the_AT board_NN1 of_IO directors_NN2 ._. 
</s>
<s>
4_MC Remuneration_NN1 of_IO the_AT operational_JJ management_NN1 Remuneration_NN1 of_IO CEOs_NN2 and_CC other_JJ executive_NN1 managers_NN2 is_VBZ the_AT essential_JJ part_NN1 of_IO this_DD1 study_NN1 ._. 
</s>
<s>
There_EX are_VBR as_RG many_DA2 remuneration_NN1 packages_NN2 as_CSA there_EX are_VBR companies_NN2 ,_, and_CC thus_RR a_AT1 generalization_NN1 of_IO the_AT packages_NN2 would_VM not_XX be_VBI fair_JJ ._. 
</s>
<s>
Despite_II different_JJ versions_NN2 of_IO remuneration_NN1 can_VM there_EX be_VBI pointed_VVN out_RP consistent_JJ parts_NN2 in_II most_DAT of_IO them_PPHO2 ._. 
</s>
<s>
The_AT basic_JJ remuneration_NN1 of_IO a_AT1 CEO_NN1 includes_VVZ a_AT1 basic_JJ salary_NN1 ,_, fees_NN2 ,_, pension_NN1 arrangements_NN2 ,_, golden_JJ parachutes_NN2 ,_, options_NN2 to_TO acquire_VVI shares_NN2 in_II the_AT company_NN1 and_CC some_DD other_JJ benefits_NN2 as_CSA travel_NN1 costs_NN2 ,_, use_NN1 of_IO company_NN1 jets_NN2 ,_, memberships_NN2 of_IO clubs_NN2 ,_, housing_VVG costs_NN2 ,_, etc_RA ._. 
</s>
<s>
Due_II21 to_II22 the_AT nature_NN1 of_IO the_AT matters_NN2 that_CST the_AT remuneration_NN1 committee_NN1 deals_VVZ with_IW ,_, neither_RR the_AT managing_JJ director_NN1 nor_CC executive_NN1 directors_NN2 may_VM be_VBI members_NN2 of_IO the_AT committee_NN1 ._. 
</s>
<s>
A_AT1 central_JJ observation_NN1 in_II the_AT study_NN1 made_VVN by_II Steven_NP1 N._NP1 Kaplan_NP1 was_VBDZ that_CST the_AT remuneration_NN1 of_IO CEOs_NN2 in_II the_AT US._NP1 is_VBZ mainly_RR a_AT1 result_NN1 of_IO a_AT1 functioning_JJ market_NN1 rather_II21 than_II22 overpayment_NN1 ._. 
</s>
<s>
While_CS CEO_NN1 pay_NN1 has_VHZ increased_VVN substantially_RR since_CS the_AT early_JJ 1990s_MC2 ,_, the_AT pay_NN1 of_IO other_JJ talented_JJ and_CC fortunate_JJ groups_NN2 has_VHZ increased_VVN by_II at_RR21 least_RR22 as_RG much_DA1 ._. 
</s>
<s>
The_AT increase_NN1 in_II hedge_NN1 fund_NN1 ,_, private_JJ equity_NN1 and_CC venture_VV0 capital_NN1 investor_NN1 fees_NN2 have_VH0 translated_VVN into_II very_RG high_JJ pay_NN1 for_IF those_DD2 groups_NN2 ._. 
</s>
<s>
By_II one_MC1 estimate_NN1 ,_, the_AT top_NN1 20_MC hedge_NN1 fund_NN1 managers_NN2 earned_VVD more_RRR in_II 2005_MC than_CSN all_DB 500_MC CEOs_NN2 in_II the_AT S_NP1 &P500.;_NULL This_DD1 is_VBZ most_RGT definitely_RR true_JJ but_CCB the_AT comparison_NN1 group_NN1 could_VM be_VBI better_JJR ._. 
</s>
<s>
The_AT fact_NN1 that_CST the_AT US_NP1 and_CC world_NN1 economy_NN1 went_VVD through_II a_AT1 huge_JJ rally_NN1 in_II21 between_II22 2002_MC and_CC 2007_MC led_VVD to_II the_AT salaries_NN2 rose_VVD indiscreet_JJ ._. 
</s>
<s>
Especially_RR hedge_VV0 funds_NN2 were_VBDR the_AT ones_NN2 to_TO take_VVI advantage_NN1 of_IO the_AT situation_NN1 at_II that_DD1 time_NNT1 ._. 
</s>
<s>
The_AT sub-prime_JJ bubble_NN1 growth_NN1 in_II the_AT US_NP1 probably_RR peaked_VVN around_RG 2005_MC and_CC at_II the_AT same_DA time_NNT1 investment_NN1 banks_NN2 were_VBDR printing_VVG and_CC selling_VVG CDOs_NN2 as_RG much_DA1 as_CSA they_PPHS2 could_VM ._. 
</s>
<s>
Kaplans_NP1 suggestion_NN1 that_CST the_AT high_JJ remuneration_NN1 of_IO CEOs_NN2 is_VBZ an_AT1 outcome_NN1 of_IO a_AT1 functioning_JJ market_NN1 is_VBZ probably_RR also_RR true_JJ ,_, but_CCB the_AT main_JJ question_NN1 is_VBZ if_CS the_AT market_NN1 has_VHZ right_RR or_CC not_XX ?_? 
</s>
<s>
The_AT argument_NN1 is_VBZ especially_RR current_JJ in_II Finland_NP1 at_II the_AT moment_NN1 ._. 
</s>
<s>
The_AT Ilmarinen_NN1 /_FO Finnair_NN1 case_NN1 shortly_RR presented_VVN in_II the_AT beginning_NN1 led_VVN to_II several_DA2 other_JJ similar_JJ discussions_NN2 in_II other_JJ firms_NN2 ._. 
</s>
<s>
This_DD1 cross-management_NN1 in_II Finnish_JJ listed_JJ companies_NN2 lead_VV0 to_II that_CST the_AT market_NN1 might_VM be_VBI distorted_VVN in_II the_AT sense_NN1 of_IO management_NN1 remuneration_NN1 ._. 
</s>
<s>
In_II a_AT1 way_NN1 ,_, the_AT CEO_NN1 remuneration_NN1 situation_NN1 in_II Finland_NP1 could_VM be_VBI described_VVN as_II a_AT1 cartel_NN1 where_RRQ the_AT top_JJ management_NN1 of_IO listed_JJ companies_NN2 is_VBZ involved_JJ in_II ._. 
</s>
<s>
A_AT1 recent_JJ article_NN1 published_VVN in_II Corporate_JJ Governance_NN1 :_: An_AT1 International_JJ Review_NN1 discusses_VVZ critically_RR the_AT executive_NN1 remuneration_NN1 design_NN1 process_NN1 in_II 23_MC Finnish_JJ state-owned_JJ companies_NN2 ._. 
</s>
<s>
The_AT authors_NN2 findings_NN2 show_VV0 that_CST restrictive_JJ remuneration_NN1 guidelines_NN2 can_VM be_VBI ineffective_JJ and_CC lead_VV0 to_II standardized_JJ pay_NN1 designs_NN2 without_IW providing_VVG comparative_JJ advantage_NN1 ._. 
</s>
<s>
Shareholders_NN2 should_VM request_VVI greater_JJR transparency_NN1 concerning_II remuneration_NN1 design_NN1 ._. 
</s>
<s>
The_AT role_NN1 of_IO consultants_NN2 should_VM be_VBI considered_VVN proactively_RR in_II the_AT guidelines_NN2 ,_, even_RR by_II limiting_VVG the_AT length_NN1 of_IO the_AT consultant-client_JJ relationship_NN1 or_CC increasing_VVG their_APPGE transparency.In_NNU the_AT same_DA article_NN1 the_AT authors_NN2 brought_VVD up_RP the_AT problem_NN1 in_II using_VVG consultants_NN2 in_II CEO_NN1 remuneration_NN1 design_NN1 process_NN1 and_CC benchmarking_NN1 CEO_NN1 remuneration_NN1 ._. 
</s>
<s>
In_II Finland_NP1 ,_, the_AT usage_NN1 of_IO consultants_NN2 and_CC benchmarking_NN1 (_( for_IF state-owned_JJ companies_NN2 )_) is_VBZ closely_RR related_VVN as_II the_AT market_NN1 is_VBZ highly_RR concentrated_VVN ._. 
</s>
<s>
International_JJ benchmarking_NN1 of_IO CEO_NN1 remuneration_NN1 should_VM be_VBI carried_VVN out_RP extremely_RR deliberately_RR ._. 
</s>
<s>
Only_RR comparing_VVG CEO_NN1 remuneration_NN1 is_VBZ not_XX enough_RR ,_, there_EX should_VM also_RR be_VBI taken_VVN into_II account_NN1 cultural_JJ ,_, organizational_JJ ,_, geographical_JJ and_CC historical_JJ differences_NN2 ._. 
</s>
<s>
Another_DD1 central_JJ piece_NN1 in_II CEO_NN1 remuneration_NN1 packages_NN2 is_VBZ the_AT golden_JJ parachute_NN1 which_DDQ is_VBZ a_AT1 widely_RR used_JJ practice_NN1 as_II a_AT1 part_NN1 of_IO CEO_NN1 remuneration_NN1 ._. 
</s>
<s>
This_DD1 goes_VVZ for_IF most_DAT of_IO the_AT OMX_NP1 Helsinki_NP1 25_MC companies_NN2 that_CST are_VBR studied_VVN in_II this_DD1 paper_NN1 ._. 
</s>
<s>
According_II21 to_II22 a_AT1 study_NN1 made_VVN by_II Talouselm_NP1 in_II 2010_MC ,_, there_EX is_VBZ building_VVG a_AT1 practice_NN1 where_CS the_AT CEO_NN1 gets_VVZ a_AT1 12_MC or_CC 18_MC month_NNT1 salary_NN1 in_CS21 case_CS22 the_AT CEO_NN1 is_VBZ fired_VVN ._. 
</s>
<s>
On_II31 top_II32 of_II33 this_DD1 most_DAT of_IO the_AT CEOs_NN2 are_VBR entitled_VVN to_II 6_MC month_NNT1 salary_NN1 in_CS21 case_CS22 they_PPHS2 get_VV0 fired_VVN ._. 
</s>
<s>
Some_DD CEOs_NN2 have_VH0 managed_VVN to_TO negotiate_VVI a_AT1 golden_JJ parachute_NN1 that_CST includes_VVZ 24_MC month_NNT1 salary_NN1 in_II31 case_II32 of_II33 being_VBG fired_VVN ._. 
</s>
<s>
This_DD1 kind_NN1 of_IO golden_JJ parachute_NN1 practice_NN1 combined_VVN with_IW high_JJ performance_NN1 related_JJ bonuses_NN2 should_VM be_VBI critically_RR discussed_VVN ._. 
</s>
<s>
The_AT incentive_NN1 to_TO take_VVI big_JJ ,_, short_RR sighted_VVN risks_NN2 becomes_VVZ even_RR higher_JJR because_CS the_AT golden_JJ parachute_NN1 works_VVZ as_II a_AT1 safety_NN1 net_NN1 incase_NN1 the_AT risk_NN1 taking_NN1 misfires._NNU 5_MC Agency_NN1 problem_NN1 The_AT simple_JJ form_NN1 of_IO the_AT agency_NN1 problem_NN1 is_VBZ whenever_RRQV the_AT owner_NN1 of_IO wealth_NN1 contracts_NN2 with_IW someone_PN1 else_RR to_TO manage_VVI his_APPGE or_CC her_APPGE affairs_NN2 ._. 
</s>
<s>
At_II this_DD1 point_NN1 the_AT owner_NN1 has_VHZ to_TO deliberate_VVI if_CSW the_AT agent_NN1 can_VM and_CC will_VM manage_VVI the_AT wealth_NN1 solely_RR in_II the_AT interest_NN1 of_IO the_AT owner_NN1 ._. 
</s>
<s>
The_AT agency_NN1 problem_NN1 has_VHZ existed_VVN for_IF ages_NN2 :_: The_AT directors_NN2 of_IO companies_NN2 ,_, being_VBG managers_NN2 of_IO other_JJ peoples_NN2 money_NN1 ,_, can_VM not_XX be_VBI expected_VVN to_TO watch_VVI over_II it_PPH1 with_IW the_AT same_DA vigilance_NN1 with_IW which_DDQ they_PPHS2 watch_VV0 their_APPGE own_DA (_( Smith_NP1 1776_MC )_) How_RRQ to_TO ensure_VVI that_CST the_AT agent_NN1 acts_VVZ solely_RR in_II the_AT interest_NN1 of_IO the_AT owner_NN1 is_VBZ the_AT challenge_NN1 ._. 
</s>
<s>
At_II the_AT moment_NN1 in_II Finland_NP1 the_AT problem_NN1 has_VHZ been_VBN widely_RR solved_VVN with_IW an_AT1 arrangement_NN1 such_CS21 that_CS22 a_AT1 major_JJ part_NN1 of_IO board_NN1 seats_NN2 are_VBR occupied_VVN by_II managers_NN2 from_II other_JJ major_JJ corporations_NN2 ._. 
</s>
<s>
This_DD1 arrangement_NN1 goes_VVZ especially_RR between_II the_AT large_JJ Finnish_JJ pension_NN1 funds_NN2 as_CSA Ilmarinen_NP1 and_CC Varma_NP1 and_CC the_AT companies_NN2 that_CST they_PPHS2 are_VBR majority_NN1 shareholders_NN2 in_RP ._. 
</s>
<s>
From_II a_AT1 certain_JJ perspective_NN1 does_VDZ it_PPH1 seem_VVI reasonable_JJ that_CST the_AT majority_NN1 shareholders_NN2 are_VBR so_RR to_TO say_VVI monitoring_VVG their_APPGE investments_NN2 by_II sitting_VVG in_II the_AT boards_NN2 of_IO the_AT companies_NN2 they_PPHS2 have_VH0 invested_VVN in_RP ._. 
</s>
<s>
The_AT problem_NN1 in_II Finland_NP1 is_VBZ the_AT cross_NN1 ownership_NN1 within_II these_DD2 firms_NN2 ._. 
</s>
<s>
The_AT agency_NN1 problem_NN1 arises_VVZ as_II the_AT board_NN1 of_IO directors_NN2 might_VM be_VBI deciding_VVG the_AT remuneration_NN1 package_NN1 of_IO a_AT1 close_JJ friend_NN1 or_CC in_II the_AT worst_JJT case_NN1 the_AT chairman_NN1 of_IO the_AT board_NN1 in_II the_AT company_NN1 where_CS one_PN1 works_VVZ as_CSA CEO_NN1 in_RP ._. 
</s>
<s>
This_DD1 kind_NN1 of_IO situations_NN2 opens_VVZ the_AT door_NN1 for_IF making_VVG decisions_NN2 that_CST are_VBR not_XX the_AT best_JJT possible_JJ for_IF maximizing_VVG shareholder_NN1 wealth_NN1 ._. 
</s>
<s>
There_EX is_VBZ evidence_NN1 that_CST the_AT independence_NN1 of_IO boards_NN2 might_VM be_VBI only_RR virtual_JJ and_CC there_RL actually_RR can_VM be_VBI found_VVN solidarity_NN1 amongst_II decision_NN1 makers_NN2 ._. 
</s>
<s>
This_DD1 evidence_NN1 goes_VVZ for_IF Finnish_JJ state-owned_JJ companies_NN2 but_CCB there_EX is_VBZ no_AT reason_NN1 to_TO see_VVI the_AT case_NN1 would_VM be_VBI different_JJ for_IF private-owned_JJ companies_NN2 ._. 
</s>
<s>
All_DB the_AT boards_NN2 of_IO Finnish_JJ listed_JJ state-owned_JJ companies_NN2 are_VBR chaired_VVN and_CC dominated_VVN by_II current_JJ or_CC former_DA executives_NN2 of_IO other_JJ companies_NN2 ._. 
</s>
<s>
Thus_RR ,_, the_AT boards_NN2 may_VM be_VBI formally_RR independent_JJ from_II the_AT executives_NN2 of_IO the_AT respective_JJ company_NN1 ,_, though_CS the_AT mindset_NN1 is_VBZ in_II most_DAT cases_NN2 aligned_VVN with_IW its_APPGE executives_NN2 ._. 
</s>
<s>
The_AT criticism_NN1 against_II the_AT Finnish_JJ system_NN1 is_VBZ quite_RG heavy_JJ and_CC reflecting_VVG to_II Kopras_NP2 statement_NN1 it_PPH1 is_VBZ also_RR appropriate_JJ ._. 
</s>
<s>
Kopra_NN1 says_VVZ that_CST the_AT concentration_NN1 of_IO the_AT consultancy_NN1 business_NN1 for_IF state-owned_JJ companies_NN2 is_VBZ good_JJ because_CS otherwise_RR ,_, with_IW a_AT1 wide_JJ spread_NN1 consultancy_NN1 market_VV0 none_PN of_IO the_AT actors_NN2 would_VM have_VHI reliable_JJ market_NN1 data_NN on_II remuneration_NN1 matters_NN2 ._. 
</s>
<s>
Despite_II Kopras_NP2 statement_NN1 the_AT reliability_NN1 of_IO the_AT market_NN1 data_NN remains_VVZ questionable_JJ if_CS it_PPH1 is_VBZ based_VVN on_II one_MC1 actors_VVZ review_VV0 on_II a_AT1 market_NN1 where_RRQ he_PPHS1 is_VBZ the_AT only_JJ actor_NN1 ._. 
</s>
<s>
The_AT use_NN1 of_IO consultants_NN2 in_II designing_VVG CEO_NN1 remuneration_NN1 is_VBZ criticized_VVN elsewhere_RL ._. 
</s>
<s>
The_AT use_NN1 of_IO consultants_NN2 can_VM be_VBI explained_VVN within_II the_AT optimal_JJ contracting_JJ framework_NN1 on_II grounds_NN2 that_CST they_PPHS2 supply_VV0 useful_JJ information_NN1 and_CC contribute_VV0 expertise_NN1 on_II the_AT design_NN1 of_IO compensation_NN1 packages_NN2 ._. 
</s>
<s>
But_CCB although_CS compensation_NN1 consultants_NN2 might_VM play_VVI a_AT1 useful_JJ role_NN1 ,_, they_PPHS2 also_RR can_VM help_VVI in_II camouflaging_VVG rents_NN2 ._. 
</s>
<s>
The_AT incentives_NN2 of_IO compensation_NN1 consultants_NN2 and_CC the_AT evidence_NN1 regarding_II their_APPGE use_NN1 suggest_VV0 that_CST these_DD2 consultants_NN2 are_VBR often_RR used_VVN to_TO justify_VVI executive_NN1 pay_NN1 rather_CS21 than_CS22 optimize_VVI it_PPH1 ._. 
</s>
<s>
6_MC Data_NN The_AT data_NN set_VVN in_II this_DD1 study_NN1 is_VBZ limited_VVN to_II 25_MC companies_NN2 which_DDQ all_DB are_VBR included_VVN in_II the_AT OMX_NP1 Helsinki_NP1 25_MC index_NN1 ._. 
</s>
<s>
The_AT OMX_NN1 25_MC index_NN1 is_VBZ suitable_JJ for_IF the_AT purpose_NN1 of_IO this_DD1 study_NN1 ,_, as_CSA it_PPH1 includes_VVZ both_RR private_JJ and_CC state-owned_JJ companies_NN2 ._. 
</s>
<s>
State-owned_JJ companies_NN2 do_VD0 get_VVI special_JJ attention_NN1 from_II the_AT public_NN1 and_CC therefore_RR is_VBZ it_PPH1 even_RR more_RGR vital_JJ that_CST the_AT CEO_NN1 remuneration_NN1 isnt_VV0 doubtful_JJ in_II these_DD2 companies_NN2 ._. 
</s>
<s>
The_AT data_NN has_VHZ been_VBN collected_VVN from_II Bloomberg_NP1 ,_, HS.fi_NP1 ,_, company_NN1 websites_NN2 and_CC annual_JJ reports_NN2 ._. 
</s>
<s>
The_AT CEO_NN1 earnings_NN2 have_VH0 been_VBN collected_VVN through_II HS.fi_NP1 website_NN1 and_CC company_NN1 annual_JJ reports_NN2 ._. 
</s>
<s>
In_II some_DD cases_NN2 the_AT problem_NN1 is_VBZ that_CST there_EX can_VM not_XX be_VBI distinguished_VVN where_CS the_AT earnings_NN2 are_VBR paid_VVN from_II ._. 
</s>
<s>
Despite_II this_DD1 problem_NN1 I_PPIS1 will_VM assume_VVI that_CST a_AT1 major_JJ part_NN1 of_IO the_AT CEOs_NN2 income_NN1 comes_VVZ from_II the_AT CEO_NN1 remuneration_NN1 package_NN1 they_PPHS2 are_VBR given_VVN from_II the_AT company_NN1 they_PPHS2 work_VV0 for_IF ._. 
</s>
<s>
The_AT unconventional_JJ situation_NN1 on_II the_AT financial_JJ markets_NN2 has_VHZ increased_VVN the_AT volatility_NN1 on_II the_AT stock_NN1 market_NN1 during_II the_AT period_NN1 the_AT study_NN1 focus_VV0 on_RP ._. 
</s>
<s>
This_DD1 could_VM be_VBI seen_VVN in_II company_NN1 performance_NN1 figures_NN2 through_II huge_JJ changes_NN2 in_II net_JJ profits_NN2 ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 it_PPH1 could_VM also_RR have_VHI been_VBN affecting_VVG CEO_NN1 remuneration_NN1 through_II dismissals_NN2 and_CC changes_NN2 in_II CEOs_NN2 ._. 
</s>
<s>
To_TO prevent_VVI skew_NN1 caused_VVN by_II these_DD2 extreme_JJ values_NN2 in_II the_AT percentage_NN1 changes_NN2 in_II either_RR CEO_NN1 remuneration_NN1 or_CC in_II company_NN1 net_NN1 profits_VVZ the_AT data_NN set_NN1 has_VHZ been_VBN adjusted_VVN ._. 
</s>
<s>
The_AT maximum_NN1 and_CC minimum_JJ values_NN2 have_VH0 been_VBN removed_VVN for_IF each_DD1 year_NNT1 ._. 
</s>
<s>
The_AT data_NN set_NN1 is_VBZ between_II years_NNT2 2006_MC and_CC 2011_MC ._. 
</s>
<s>
Approximately_RR half_DB of_IO the_AT period_NN1 is_VBZ stressed_VVN by_II the_AT financial_JJ crisis_NN1 that_CST burst_VVD in_II the_AT end_NN1 of_IO 2008_MC with_IW the_AT Lehman_NN1 Brothers_NN2 bankruptcy_NN1 ._. 
</s>
<s>
Despite_II this_DD1 I_PPIS1 do_VD0 nt_XX think_VVI it_PPH1 has_VHZ a_AT1 too_RG large_JJ effect_NN1 on_II my_APPGE results_NN2 for_IF the_AT empirical_JJ study_NN1 ._. 
</s>
<s>
7_MC Results_VVZ The_AT empirical_JJ part_NN1 of_IO the_AT study_NN1 was_VBDZ carried_VVN out_RP by_II using_VVG simple_JJ statistical_JJ measures_NN2 ._. 
</s>
<s>
The_AT comparison_NN1 is_VBZ made_VVN by_II using_VVG average_JJ and_CC median_NN1 of_IO each_DD1 of_IO the_AT measured_JJ figures_NN2 ._. 
</s>
<s>
The_AT measures_NN2 that_CST were_VBDR taken_VVN into_II the_AT study_NN1 are_VBR the_AT nominal_JJ values_NN2 of_IO CEO_NN1 remuneration_NN1 and_CC the_AT net_JJ profits_NN2 (_( before_CS extraordinary_JJ items_NN2 )_) for_IF the_AT companies_NN2 in_II question_NN1 ,_, and_CC the_AT percentage_NN1 change_NN1 in_II both_DB2 of_IO the_AT measures_NN2 ._. 
</s>
<s>
I_PPIS1 also_RR used_VVD the_AT performance_NN1 of_IO the_AT OMX_NP1 Helsinki_NP1 25_MC index_NN1 to_TO compare_VVI it_PPH1 with_IW the_AT companies_NN2 performance_NN1 ._. 
</s>
<s>
As_CSA can_VM be_VBI seen_VVN in_II Figure_NN1 1_MC1 the_AT percentage_NN1 change_NN1 in_II companies_NN2 net_JJ profits_NN2 goes_VVZ hand_NN1 in_II hand_NN1 with_IW the_AT index_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ obvious_JJ because_CS the_AT studied_JJ companies_NN2 build_VV0 up_RP the_AT index_NN1 ._. 
</s>
<s>
Differences_NN2 can_VM be_VBI seen_VVN ,_, especially_RR in_II 2009_MC but_CCB this_DD1 can_VM be_VBI explained_VVN with_IW the_AT fact_NN1 that_CST company_NN1 profits_NN2 are_VBR based_VVN on_II the_AT current_JJ situation_NN1 and_CC the_AT stock_NN1 index_NN1 price_NN1 reflect_VV0 the_AT future_JJ expectations.There_NNU is_VBZ definitely_RR a_AT1 lead-lag_JJ relation_NN1 between_II these_DD2 two_MC measures_NN2 and_CC that_DD1 causes_VVZ the_AT difference_NN1 in_II the_AT performance_NN1 ._. 
</s>
<s>
This_DD1 study_NN1 will_VM not_XX respond_VVI to_II the_AT question_NN1 if_CS the_AT stock_NN1 market_NN1 is_VBZ right_JJ or_CC wrong_JJ with_IW the_AT future_JJ predictions_NN2 ._. 
</s>
<s>
The_AT comparison_NN1 between_II changes_NN2 in_II CEO_NN1 remuneration_NN1 and_CC company_NN1 performance_NN1 is_VBZ the_AT essential_JJ part_NN1 of_IO this_DD1 study_NN1 ._. 
</s>
<s>
Figure_NN1 2_MC shows_NN2 how_RRQ these_DD2 two_MC measures_NN2 compare_VV0 to_II each_PPX221 other_PPX222 ._. 
</s>
<s>
From_II the_AT results_NN2 can_VM be_VBI seen_VVN that_CST these_DD2 measures_NN2 go_VV0 hand_NN1 in_II hand_NN1 what_DDQ come_VV0 to_II the_AT direction_NN1 ._. 
</s>
<s>
In_II approximately_RR 60%_NNU of_IO the_AT companies_NN2 showed_VVD a_AT1 change_NN1 of_IO CEO_NN1 remuneration_NN1 in_II the_AT same_DA direction_NN1 as_CSA the_AT change_NN1 in_II company_NN1 performance_NN1 ._. 
</s>
<s>
Despite_II the_AT direction_NN1 in_II the_AT change_NN1 was_VBDZ the_AT same_DA ,_, the_AT proportion_NN1 of_IO the_AT changes_NN2 was_VBDZ not_XX parallel_RR ._. 
</s>
<s>
In_II 65%_NNU of_IO the_AT cases_NN2 the_AT CEO_NN1 remuneration_NN1 fell_VVD less_RRR ,_, or_CC rose_VVD more_DAR than_CSN the_AT company_NN1 net_NN1 profit_NN1 ._. 
</s>
<s>
To_II some_DD extent_NN1 can_VM this_DD1 result_VVI be_VBI affected_VVN by_II the_AT fact_NN1 that_CST a_AT1 large_JJ part_NN1 of_IO CEO_NN1 bonuses_NN2 are_VBR often_RR paid_VVN afterwards_RT as_CSA bonuses_NN2 (_( and_CC option_NN1 plans_NN2 etc_RA ._. )_) ._. 
</s>
<s>
This_DD1 causes_VVZ an_AT1 effect_NN1 where_CS the_AT CEO_NN1 remuneration_NN1 can_VM be_VBI disproportionally_RR high_RR compared_VVN to_II the_AT performance_NN1 of_IO the_AT company_NN1 ._. 
</s>
<s>
In_II this_DD1 case_NN1 the_AT problem_NN1 can_VM be_VBI stated_VVN to_TO be_VBI a_AT1 minor_JJ one_PN1 based_VVN on_II the_AT fact_NN1 that_CST during_II the_AT research_NN1 period_NN1 the_AT CEO_NN1 remuneration_NN1 held_VVD relatively_RR stable_JJ ._. 
</s>
<s>
The_AT average_JJ CEO_NN1 remuneration_NN1 for_IF the_AT period_NN1 between_II 2007-2011_MCMC was_VBDZ 1.640.000_MC euros_NN2 for_IF the_AT studied_JJ companies_NN2 ._. 
</s>
<s>
As_CSA can_VM be_VBI seen_VVN in_II Figure_NN1 3_MC ,_, exceptionally_RR in_II year_NNT1 2007_MC the_AT median_JJ remuneration_NN1 was_VBDZ higher_JJR than_CSN the_AT average_NN1 ._. 
</s>
<s>
Otherwise_RR the_AT remuneration_NN1 seems_VVZ stable_JJ despite_II the_AT relatively_RR high_JJ overall_JJ level_NN1 ._. 
</s>
<s>
8_MC Conclusions_NN2 The_AT assessment_NN1 of_IO how_RGQ valuable_JJ a_AT1 person_NN1 is_VBZ for_IF a_AT1 company_NN1 is_VBZ difficult_JJ ,_, especially_RR when_CS one_PN1 is_VBZ trying_VVG to_TO evaluate_VVI qualitative_JJ factors_NN2 ._. 
</s>
<s>
Based_VVN on_II the_AT results_NN2 from_II the_AT comparisons_NN2 made_VVN in_II this_DD1 study_NN1 I_PPIS1 would_VM say_VVI that_CST the_AT CEO_NN1 remuneration_NN1 and_CC company_NN1 performance_NN1 does_VDZ not_XX go_VVI hand_NN1 in_II hand_NN1 ._. 
</s>
<s>
A_AT1 positive_JJ surprise_NN1 in_II the_AT results_NN2 was_VBDZ the_AT fact_NN1 that_CST ,_, at_RR21 least_RR22 on_II average_NN1 ,_, the_AT direction_NN1 of_IO CEO_NN1 remuneration_NN1 follows_VVZ the_AT performance_NN1 of_IO the_AT company_NN1 ._. 
</s>
<s>
By_II studying_VVG the_AT CEO_NN1 remuneration_NN1 and_CC company_NN1 performance_NN1 figures_NN2 on_II company_NN1 level_NN1 ,_, there_EX could_VM be_VBI seen_VVN several_DA2 exceptions_NN2 to_II this_DD1 perception_NN1 ._. 
</s>
<s>
The_AT results_NN2 show_VV0 that_CST the_AT CEO_NN1 remuneration_NN1 follows_VVZ to_II some_DD extent_NN1 the_AT company_NN1 performance_NN1 but_CCB is_VBZ the_AT absolute_JJ level_NN1 too_RG high_JJ ?_? 
</s>
<s>
Based_VVN on_II the_AT results_NN2 from_II this_DD1 study_NN1 and_CC the_AT CEO_NN1 remuneration_NN1 practices_NN2 is_VBZ my_APPGE conclusion_NN1 that_CST the_AT CEOs_NN2 are_VBR overpaid_VVN ._. 
</s>
<s>
The_AT question_NN1 is_VBZ complex_JJ because_CS there_EX are_VBR several_DA2 things_NN2 to_TO take_VVI under_II consideration_NN1 when_CS making_VVG an_AT1 assessment_NN1 on_II the_AT matter_NN1 ._. 
</s>
<s>
The_AT basic_JJ salary_NN1 of_IO CEOs_NN2 in_II Finnish_JJ listed_JJ companies_NN2 is_VBZ on_II an_AT1 absolute_JJ level_NN1 which_DDQ ensures_VVZ the_AT CEO_NN1 a_AT1 decent_JJ payoff_NN1 disregarding_VVG the_AT company_NN1 performance_NN1 ._. 
</s>
<s>
I_PPIS1 often_RR hear_VV0 and_CC read_VVN about_II the_AT downside_NN1 risk_NN1 for_IF the_AT CEO_NN1 but_CCB I_PPIS1 do_VD0 nt_XX think_VVI there_RL is_VBZ a_AT1 downside_NN1 ._. 
</s>
<s>
If_CS the_AT company_NN1 succeeds_VVZ ,_, the_AT CEO_NN1 gets_VVZ big_JJ bonuses_NN2 and_CC if_CS the_AT company_NN1 does_VDZ nt_XX perform_VVI the_AT CEO_NN1 gets_VVZ a_AT1 relatively_RR high_JJ basic_JJ salary_NN1 ,_, which_DDQ is_VBZ enough_DD to_TO cover_VVI regular_JJ expenses_NN2 ._. 
</s>
<s>
The_AT worst_JJT case_NN1 scenario_NN1 is_VBZ that_CST the_AT CEO_NN1 gets_VVZ fired_JJ ,_, but_CCB then_RT he/she_PPHS1 usually_RR has_VHZ a_AT1 deal_NN1 where_CS he/she_PPHS1 gets_VVZ 12-24_MCMC month_NNT1 salary_NN1 ._. 
</s>
<s>
If_CS the_AT CEO_NN1 is_VBZ not_XX competent_JJ the_AT dismissal_NN1 could_VM turn_VVI into_II the_AT worst_JJT case_NN1 scenario_NN1 for_IF the_AT company_NN1 ._. 
</s>
<s>
The_AT currently_RR used_JJ long-term_JJ bonus_NN1 packages_NN2 have_VH0 both_RR pros_NN2 and_CC cons_NN2 ._. 
</s>
<s>
The_AT main_JJ advantage_NN1 of_IO these_DD2 packages_NN2 is_VBZ that_CST they_PPHS2 commit_VV0 the_AT CEO_NN1 for_IF a_AT1 longer_JJR time-period_NN1 in_II the_AT company_NN1 ._. 
</s>
<s>
Then_RT again_RT the_AT downside_NN1 is_VBZ the_AT ,_, usually_RR unlimited_JJ upside_NN1 especially_RR associated_VVN in_II option-plans_NN2 ._. 
</s>
<s>
An_AT1 increase_NN1 in_II the_AT basic_JJ salary_NN1 would_VM prevent_VVI the_AT problem_NN1 associated_VVN with_IW abnormal_JJ bonuses_NN2 but_CCB then_RT again_RT it_PPH1 would_VM raise_VVI the_AT discussion_NN1 of_IO too_RG high_JJ remuneration_NN1 when_CS the_AT company_NN1 performs_VVZ badly_RR ._. 
</s>
<s>
Especially_RR the_AT state_NN1 ownership_NN1 control_NN1 should_VM monitor_VVI closely_RR the_AT remuneration_NN1 of_IO CEOs_NN2 and_CC they_PPHS2 should_VM be_VBI ready_JJ to_TO make_VVI decisions_NN2 when_CS needed_VVN ._. 
</s>
