<s>
The_AT Financial_JJ Crisis_NN1 :_: How_RRQ it_PPH1 affected_VVD the_AT risk_NN1 management_NN1 of_IO financial_JJ companies_NN2 Introduction_NN1 In_II recent_JJ years_NNT2 ,_, we_PPIS2 have_VH0 been_VBN following_VVG the_AT development_NN1 of_IO the_AT Global_JJ Financial_JJ Crisis_NN1 (_( GFC_NP1 )_) ,_, which_DDQ struck_VVD hard_RR on_II financial_JJ institutions_NN2 and_CC whole_JJ countries_NN2 ._. 
</s>
<s>
The_AT crisis_NN1 has_VHZ affected_VVN a_AT1 large_JJ part_NN1 of_IO the_AT financial_JJ system_NN1 ,_, increasing_JJ regulation_NN1 ,_, and_CC placing_VVG more_DAR weight_NN1 in_II risk_NN1 management_NN1 in_II financial_JJ institutions_NN2 ._. 
</s>
<s>
Today_RT ,_, the_AT regulation_NN1 of_IO risk_NN1 management_NN1 in_II financial_JJ companies_NN2 has_VHZ been_VBN revised_VVN in_BCL21 order_BCL22 to_TO avoid_VVI the_AT birth_NN1 of_IO similar_JJ problems_NN2 in_II the_AT future_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ generally_RR accepted_VVN that_CST the_AT main_JJ reasons_NN2 for_IF the_AT crisis_NN1 where_CS :_: the_AT de-regulated_JJ financial_JJ market_NN1 and_CC inadequate_JJ risk_NN1 management_NN1 of_IO financial_JJ institutions_NN2 ._. 
</s>
<s>
1Basel_FO II_MC ,_, implemented_VVN in_II 2007_MC to_II 2009_MC ,_, increased_VVD the_AT regulation_NN1 ,_, with_IW Basel_NP1 III_MC currently_RR being_VBG developed_VVN to_TO further_RRR improve_VVI the_AT current_JJ regulation_NN1 ._. 
</s>
<s>
The_AT Basel_NP1 regulations_NN2 change_VV0 the_AT rules_NN2 of_IO risk_NN1 management_NN1 in_II financial_JJ institutions_NN2 ,_, which_DDQ helps_VVZ to_TO identify_VVI problems_NN2 in_II future_NN1 ._. 
</s>
<s>
All_DB actions_NN2 are_VBR being_VBG taken_VVN in_BCL21 order_BCL22 to_TO increase_VVI the_AT level_NN1 of_IO risk_NN1 management_NN1 in_II the_AT financial_JJ system_NN1 ._. 
</s>
<s>
In_II previous_JJ studies_NN2 ,_, the_AT political_JJ regulation_NN1 ,_, in_II fact_NN1 de-regulation_NN1 ,_, is_VBZ blamed_VVN for_IF the_AT crisis_NN1 (_( Tarr_NP1 ,_, 2010_MC ;_; Taylor_NP1 ,_, 2009_MC )_) ._. 
</s>
<s>
The_AT development_NN1 of_IO complex_JJ instruments_NN2 and_CC new_JJ financial_JJ innovations_NN2 has_VHZ also_RR been_VBN presented_VVN to_TO cause_VVI the_AT crisis_NN1 (_( Acharaya_NP1 ,_, Philippon_NP1 ,_, Richardson_NP1 and_CC Roubini_NP1 2009_MC )_) ._. 
</s>
<s>
Acharaya_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
also_RR claim_VV0 that_CST the_AT inadequate_JJ risk_NN1 management_NN1 of_IO banks_NN2 is_VBZ one_MC1 of_IO the_AT main_JJ points_NN2 that_CST allowed_VVD the_AT crisis_NN1 to_TO grow_VVI as_RG large_JJ as_CSA it_PPH1 did_VDD ._. 
</s>
<s>
Many_DA2 of_IO the_AT previous_JJ studies_NN2 have_VH0 concentrated_VVN on_II the_AT question_NN1 :_: what_DDQ caused_VVD the_AT crisis_NN1 ?_? 
</s>
<s>
To_TO answer_VVI this_DD1 ,_, studies_NN2 have_VH0 discussed_VVN why_RRQ different_JJ institutions_NN2 acted_VVN as_CSA they_PPHS2 did_VDD to_TO motivate_VVI their_APPGE actions_NN2 ._. 
</s>
<s>
This_DD1 paper_NN1 will_VM provide_VVI a_AT1 contribution_NN1 to_II previous_JJ studies_NN2 by_II examining_VVG more_RGR closely_RR on_II the_AT risk_NN1 management_NN1 decision_NN1 in_II financial_JJ institutions_NN2 more_RGR closely_RR ,_, and_CC how_RRQ the_AT financial_JJ crisis_NN1 affected_VVN the_AT risk_NN1 management_NN1 ._. 
</s>
<s>
As_II a_AT1 result_NN1 ,_, this_DD1 paper_NN1 will_VM bring_VVI forward_RL how_RRQ the_AT risk_NN1 management_NN1 has_VHZ changed_VVN due_II21 to_II22 the_AT GFC_NP1 and_CC how_RRQ this_DD1 affects_VVZ the_AT operations_NN2 of_IO banks_NN2 ._. 
</s>
<s>
To_TO explain_VVI the_AT risk_NN1 management_NN1 and_CC the_AT development_NN1 of_IO it_PPH1 ,_, the_AT paper_NN1 will_VM concentrate_VVI on_II examining_VVG the_AT informational_JJ and_CC incentive_NN1 problems_NN2 in_II financial_JJ institutions_NN2 ._. 
</s>
<s>
As_II a_AT1 part_NN1 of_IO risk_NN1 management_NN1 ,_, especially_RR the_AT market_NN1 risks_NN2 of_IO the_AT institutions_NN2 are_VBR especially_RR examined_VVN ,_, and_CC how_RRQ the_AT risk_NN1 management_NN1 of_IO market_NN1 risk_NN1 has_VHZ changed_VVN due_II21 to_II22 the_AT crisis_NN1 ._. 
</s>
<s>
The_AT remainder_NN1 of_IO the_AT paper_NN1 is_VBZ divided_VVN into_II five_MC sections_NN2 ;_; the_AT first_MD section_NN1 provides_VVZ an_AT1 insight_NN1 into_II the_AT risk_NN1 management_NN1 of_IO banks_NN2 and_CC how_RRQ they_PPHS2 differ_VV0 from_II other_JJ companies_NN2 ;_; the_AT second_MD section_NN1 will_VM explain_VVI the_AT market_NN1 risks_NN2 of_IO the_AT banks_NN2 ;_; the_AT third_MD will_VM go_VVI through_II the_AT regulation_NN1 and_CC how_RRQ it_PPH1 has_VHZ affected_VVN the_AT risk_NN1 management_NN1 ;_; and_CC the_AT fourth_MD analyses_NN2 what_DDQ kind_NN1 of_IO effect_NN1 the_AT changes_NN2 in_II risk_NN1 management_NN1 will_VM have_VHI ._. 
</s>
<s>
The_AT fifth_MD section_NN1 will_VM be_VBI a_AT1 conclusion_NN1 and_CC discussion_NN1 of_IO the_AT findings_NN2 in_II the_AT paper_NN1 ._. 
</s>
<s>
Risk_VV0 management_NN1 in_II banks_NN2 Risk_VV0 management_NN1 in_II banks_NN2 has_VHZ experienced_VVN great_JJ changes_NN2 in_II the_AT latest_JJT years_NNT2 due_II21 to_II22 the_AT financial_JJ crisis_NN1 ._. 
</s>
<s>
The_AT economy_NN1 is_VBZ also_RR under_RG continuous_JJ development_NN1 ,_, and_CC risk_NN1 management_NN1 must_VM keep_VVI up_RP with_IW this_DD1 development_NN1 ,_, and_CC must_VM therefore_RR go_VVI through_II changes_NN2 ._. 
</s>
<s>
To_TO understand_VVI what_DDQ drives_VVZ the_AT risk_NN1 management_NN1 decisions_NN2 in_II banks_NN2 ,_, one_PN1 must_VM know_VVI what_DDQ affects_VVZ the_AT decisions_NN2 the_AT bank_NN1 makes_VVZ to_TO manage_VVI risk_NN1 ._. 
</s>
<s>
Because_CS banks_NN2 are_VBR important_JJ financial_JJ intermediaries_NN2 whose_DDQGE business_NN1 differs_VVZ from_II other_JJ industries_NN2 ,_, they_PPHS2 have_VH0 different_JJ features_NN2 that_CST drive_VV0 their_APPGE risk_NN1 management_NN1 ._. 
</s>
<s>
Banks_NN2 have_VH0 three_MC important_JJ features_NN2 that_CST affect_VV0 their_APPGE risk_NN1 management_NN1 :_: credit_NN1 sensitivity_NN1 of_IO customers_NN2 ,_, opaqueness_NN1 and_CC high_JJ liquidity_NN1 ,_, and_CC the_AT highly_RR competitive_JJ market_NN1 where_RRQ profits_NN2 depend_VV0 on_II the_AT cost_NN1 of_IO capital_NN1 (_( Merton_NP1 &;_NULL Perold_NP1 ,_, 1998_MC )_) ._. 
</s>
<s>
The_AT three_MC features_NN2 are_VBR explained_VVN more_RGR closely_RR in_II the_AT next_MD section_NN1 ._. 
</s>
<s>
Customer_NN1 credit_NN1 sensitivity_NN1 Banks_NN2 differ_VV0 from_II other_JJ companies_NN2 because_CS their_APPGE customers_NN2 are_VBR large_JJ liability_NN1 holders_NN2 ._. 
</s>
<s>
In_II31 addition_II32 to_II33 investors_NN2 ,_, also_RR customers_NN2 have_VH0 invested_VVN in_II the_AT bank_NN1 by_II their_APPGE deposits_NN2 ._. 
</s>
<s>
The_AT customers_NN2 do_VD0 not_XX want_VVI that_CST the_AT value_NN1 of_IO their_APPGE deposits_NN2 will_VM be_VBI depending_II21 on_II22 the_AT success_NN1 of_IO the_AT bank_NN1 ,_, and_CC therefore_RR safe_JJ banks_NN2 with_IW low_JJ risk_NN1 of_IO default_NN1 ._. 
</s>
<s>
Because_CS the_AT risk_NN1 of_IO default_NN1 is_VBZ determined_VVN by_II the_AT rating_NN1 of_IO the_AT bank_NN1 ,_, customers_NN2 seek_VV0 banks_NN2 with_IW high_JJ ratings_NN2 ._. 
</s>
<s>
The_AT credit_NN1 sensitivity_NN1 of_IO customer_NN1 leads_VVZ to_II a_AT1 rating_NN1 sensitivity_NN1 of_IO banks_NN2 ._. 
</s>
<s>
To_TO minimize_VVI the_AT market_NN1 risk_VV0 the_AT banks_NN2 use_VV0 derivative_JJ instruments_NN2 to_TO hedge_VVI themselves_PPX2 against_II risk_NN1 ._. 
</s>
<s>
By_II effective_JJ risk_NN1 management_NN1 banks_NN2 can_VM hedge_VVI the_AT market_NN1 risks_NN2 they_PPHS2 do_VD0 not_XX want_VVI to_TO bear_VVI ,_, and_CC by_II doing_VDG this_DD1 minimize_VVI the_AT risk_NN1 of_IO default_NN1 ._. 
</s>
<s>
An_AT1 important_JJ notice_NN1 is_VBZ that_CST only_RR known_VVN risks_NN2 can_VM be_VBI hedged_VVN ,_, but_CCB hedging_VVG cant_NN1 be_VBI used_VVN against_II unknown_JJ risks_NN2 ._. 
</s>
<s>
Opaqueness_NN1 and_CC high_JJ liquidity_NN1 Financial_JJ institutions_NN2 differ_VV0 from_II other_JJ companies_NN2 because_II21 of_II22 their_APPGE non-transparency_NN1 ._. 
</s>
<s>
Because_CS they_PPHS2 are_VBR non-transparent_JJ ,_, the_AT monitoring_NN1 by_II shareholders_NN2 and_CC customers_NN2 is_VBZ difficult_JJ ,_, and_CC therefore_RR regulation_NN1 is_VBZ needed_VVN to_TO keep_VVI the_AT customers_NN2 safe_JJ ._. 
</s>
<s>
Moreover_RR ,_, the_AT financial_JJ companies_NN2 have_VH0 often_RR high_JJ liquidity_NN1 ,_, which_DDQ allows_VVZ them_PPHO2 to_TO make_VVI changes_NN2 in_II their_APPGE portfolios_NN2 and_CC risks_NN2 quickly_RR ,_, before_CS the_AT market_NN1 has_VHZ time_NNT1 to_TO react_VVI ._. 
</s>
<s>
Before_CS the_AT GFC_NP1 the_AT economy_NN1 trusted_VVD more_RRR on_II self-regulation_NN1 ,_, and_CC that_CST banks_NN2 would_VM manage_VVI their_APPGE risks_NN2 properly_RR because_II21 of_II22 their_APPGE loyalty_NN1 to_II the_AT customers_NN2 and_CC investors_NN2 ._. 
</s>
<s>
It_PPH1 has_VHZ though_RR been_VBN shown_VVN that_CST this_DD1 is_VBZ not_XX the_AT case_NN1 ._. 
</s>
<s>
Because_CS the_AT market_NN1 cant_NN1 manage_VV0 the_AT risk_NN1 because_CS the_AT banks_NN2 opaqueness_NN1 ,_, the_AT task_NN1 is_VBZ given_VVN to_II regulators_NN2 ,_, and_CC supervision_NN1 of_IO banks_NN2 is_VBZ increased_VVN ._. 
</s>
<s>
The_AT changes_NN2 in_II a_AT1 bank_NN1 's_GE risk_NN1 management_NN1 by_II regulation_NN1 are_VBR discussed_VVN in_II chapter_NN1 three_MC ._. 
</s>
<s>
High_JJ competition_NN1 and_CC cost_NN1 of_IO capital_NN1 The_AT third_MD factor_NN1 arises_VVZ from_II the_AT fact_NN1 that_CST banks_NN2 sell_VV0 and_CC buy_VV0 capital_NN1 ,_, and_CC at_II the_AT same_DA time_NNT1 they_PPHS2 sell_VV0 and_CC buy_VV0 risks_NN2 linked_VVN to_II the_AT capital_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ all_DB done_VDN in_II a_AT1 highly_RR competitive_JJ market_NN1 ,_, where_CS banks_NN2 makes_VVZ profits_NN2 by_II the_AT spread_NN1 between_II the_AT risks_NN2 they_PPHS2 buy_VV0 and_CC sell_VV0 ._. 
</s>
<s>
The_AT level_NN1 of_IO competition_NN1 brings_VVZ down_RP the_AT profits_NN2 of_IO banks_NN2 and_CC their_APPGE profitability_NN1 depends_VVZ on_II the_AT cost_NN1 of_IO capital_NN1 ,_, especially_RR the_AT cost_NN1 of_IO risk_NN1 capital_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ important_JJ that_CST banks_NN2 can_VM borrow_VVI cheaply_RR to_TO be_VBI able_JK to_TO compete_VVI on_II the_AT market_NN1 ._. 
</s>
<s>
Because_II21 of_II22 the_AT high_JJ competition_NN1 ,_, banks_NN2 must_VM also_RR have_VHI an_AT1 effective_JJ risk_NN1 management_NN1 ,_, which_DDQ costs_VVZ cant_NN1 exceed_VV0 profits_NN2 they_PPHS2 can_VM make_VVI ._. 
</s>
<s>
Market_VV0 Risk_NN1 Market_NN1 risk_NN1 is_VBZ defined_VVN as_II the_AT risks_NN2 in_II assets_NN2 ,_, foreign_JJ exchange_NN1 ,_, and_CC interest_NN1 rates_NN2 ._. 
</s>
<s>
In_II a_AT1 banks_NN2 operation_NN1 it_PPH1 is_VBZ important_JJ to_TO control_VVI the_AT risks_NN2 in_II market_NN1 variables_NN2 ._. 
</s>
<s>
First_MD market_NN1 risks_NN2 affecting_VVG ;_; asset_NN1 prices_NN2 ,_, foreign_JJ exchange_NN1 and_CC interest_NN1 rate_NN1 risk_NN1 is_VBZ presented_VVN ;_; then_RT liquidity_NN1 risk_NN1 and_CC system_NN1 risk_NN1 is_VBZ discussed_VVN because_II21 of_II22 their_APPGE linkage_NN1 to_II the_AT first_MD three_MC risks_NN2 ._. 
</s>
<s>
Asset_NN1 price_NN1 risk_NN1 Asset_NN1 price_NN1 risk_NN1 is_VBZ the_AT risk_NN1 of_IO a_AT1 decline_NN1 in_II asset_NN1 prices_NN2 ,_, affecting_VVG the_AT banks_NN2 '_GE balance_NN1 ._. 
</s>
<s>
The_AT total_JJ risk_NN1 in_II asset_NN1 prices_NN2 can_VM of_RR21 course_RR22 be_VBI diversified_VVN ,_, but_CCB not_XX all_DB the_AT risk_NN1 can_VM be_VBI diversified_VVN away_RL ._. 
</s>
<s>
The_AT risk_NN1 in_II asset_NN1 price_NN1 decline_NN1 is_VBZ counted_VVN with_IW a_AT1 maximal_JJ loss_NN1 on_II a_AT1 specified_JJ confidence_NN1 interval_NN1 within_II a_AT1 specified_JJ time_NNT1 horizon_NN1 ._. 
</s>
<s>
To_TO cover_VVI the_AT risk_NN1 some_DD capital_NN1 must_VM be_VBI reserved_VVN ._. 
</s>
<s>
Foreign_JJ Exchange_NN1 risk_NN1 Foreign_JJ exchange_NN1 risk_NN1 is_VBZ the_AT risk_NN1 in_II value_NN1 change_NN1 of_IO a_AT1 currency_NN1 ,_, and_CC affects_VVZ investments_NN2 made_VVN in_II other_JJ foreign_JJ currencies_NN2 ._. 
</s>
<s>
The_AT risk_NN1 can_VM be_VBI easily_RR hedged_VVN with_IW derivative_JJ instruments_NN2 like_II forwards_RL and_CC futures_NN2 ,_, and_CC does_VDZ not_XX bring_VVI additional_JJ significant_JJ risks_NN2 to_II banks_NN2 ._. 
</s>
<s>
Interest_NN1 rate_NN1 risk_NN1 Interest_NN1 rate_NN1 risk_NN1 is_VBZ the_AT risk_NN1 of_IO changes_NN2 in_II the_AT interest_NN1 rates_NN2 ,_, which_DDQ will_VM affect_VVI the_AT banks_NN2 '_GE profits_NN2 ._. 
</s>
<s>
The_AT interest_NN1 rate_NN1 risk_NN1 is_VBZ more_RGR difficult_JJ to_TO handle_VVI than_CSN for_REX21 example_REX22 foreign_JJ exchange_NN1 risk_NN1 ,_, because_CS the_AT interest_NN1 rate_NN1 is_VBZ affected_VVN by_II many_DA2 different_JJ factors_NN2 ._. 
</s>
<s>
In_RR21 addition_RR22 there_EX are_VBR many_DA2 different_JJ interest_NN1 rates_NN2 that_CST is_VBZ used_VVN ._. 
</s>
<s>
Interest_NN1 rates_NN2 can_VM be_VBI managed_VVN within_II the_AT bank_NN1 by_II controlling_VVG the_AT contracts_NN2 banks_NN2 do_VD0 ,_, or_CC with_IW outside_JJ partners_NN2 by_II interest_NN1 rate_NN1 swaps_NN2 ._. 
</s>
<s>
With_IW todays_NN2 developed_VVD financial_JJ tools_NN2 it_PPH1 is_VBZ possible_JJ to_TO manage_VVI the_AT interest_NN1 rate_NN1 so_CS21 that_CS22 the_AT net_JJ income_NN1 from_II the_AT interest_NN1 rates_NN2 is_VBZ held_VVN stable_JJ (_( Hull_NP1 ,_, 2010_MC )_) Liquidity_NN1 risk_NN1 Liquidity_NN1 risk_NN1 is_VBZ not_XX by_II definition_NN1 a_AT1 market_NN1 risk_NN1 ,_, but_CCB the_AT market_NN1 risks_NN2 can_VM lead_VVI to_II liquidity_NN1 risk_NN1 ._. 
</s>
<s>
The_AT risk_NN1 is_VBZ that_CST the_AT liquidity_NN1 disappears_VVZ from_II the_AT market_NN1 ,_, which_DDQ is_VBZ serious_JJ for_IF the_AT financial_JJ sector_NN1 ._. 
</s>
<s>
If_CS there_EX is_VBZ not_XX enough_DD liquidity_NN1 on_II the_AT financial_JJ sector_NN1 ,_, the_AT banks_NN2 can_VM not_XX continue_VVI their_APPGE task_NN1 to_TO distribute_VVI money_NN1 by_II lending_NN1 and_CC borrowing_NN1 ._. 
</s>
<s>
This_DD1 will_VM eventually_RR shut_VVI down_RP the_AT whole_JJ financial_JJ system_NN1 ._. 
</s>
<s>
The_AT liquidity_NN1 risk_NN1 can_VM be_VBI protected_VVN with_IW increased_JJ liquid_JJ assets_NN2 in_II the_AT banks_NN2 ,_, that_DD1 is_VBZ higher_JJR capital_NN1 requirements_NN2 ._. 
</s>
<s>
The_AT risk_NN1 can_VM be_VBI reduced_VVN by_II more_DAR transparency_NN1 in_II the_AT banks_NN2 ,_, so_CS21 that_CS22 the_AT banks_NN2 situation_NN1 is_VBZ known_VVN by_II the_AT market_NN1 and_CC other_JJ banks_NN2 ._. 
</s>
<s>
If_CS the_AT banks_NN2 were_VBDR more_RGR transparent_JJ then_RT some_DD banks_NN2 in_II good_JJ shape_NN1 could_VM continue_VVI their_APPGE operation_NN1 in_II difficult_JJ times_NNT2 ,_, and_CC banks_NN2 in_II bad_JJ shape_NN1 would_VM probably_RR default_VVI ._. 
</s>
<s>
System_NN1 risk_VV0 The_AT system_NN1 risk_NN1 is_VBZ that_CST a_AT1 default_NN1 of_IO one_MC1 bank_NN1 will_VM lead_VVI to_II problems_NN2 in_II other_JJ banks_NN2 ._. 
</s>
<s>
System_NN1 risk_NN1 is_VBZ an_AT1 important_JJ factor_NN1 in_II the_AT financial_JJ sector_NN1 because_CS the_AT banks_NN2 risks_NN2 are_VBR highly_RR correlated_VVN with_IW each_PPX221 other_PPX222 ._. 
</s>
<s>
The_AT system_NN1 risk_NN1 can_VM start_VVI a_AT1 snowball_NN1 effect_NN1 if_CS risks_NN2 are_VBR not_XX managed_VVN properly_RR ._. 
</s>
<s>
Regulation_NN1 Regulation_NN1 of_IO financial_JJ companies_NN2 ,_, especially_RR banks_NN2 ,_, has_VHZ become_VVN current_JJ under_II the_AT recent_JJ years_NNT2 ._. 
</s>
<s>
Before_CS the_AT GFC_NP1 there_EX was_VBDZ a_AT1 belief_NN1 that_CST the_AT market_NN1 would_VM regulate_VVI itself_PPX1 ,_, but_CCB this_DD1 has_VHZ proven_VVN to_TO be_VBI wrong_JJ ,_, and_CC regulation_NN1 is_VBZ needed_VVN ._. 
</s>
<s>
Motives_NN2 to_TO regulate_VVI banks_NN2 One_MC1 reason_NN1 to_TO regulate_VVI banks_NN2 is_VBZ that_CST the_AT banks_NN2 have_VH0 enough_DD capital_NN1 reserved_VVN against_II the_AT risks_NN2 they_PPHS2 take_VV0 ._. 
</s>
<s>
It_PPH1 has_VHZ been_VBN shown_VVN the_AT economy_NN1 suffers_VVZ from_II different_JJ kind_NN1 of_IO crisis_NN1 that_CST also_RR affects_VVZ banks_NN2 ._. 
</s>
<s>
During_II difficult_JJ times_NNT2 bank_NN1 crashes_NN2 happen_VV0 ,_, and_CC they_PPHS2 have_VH0 proven_VVN to_TO be_VBI difficult_JJ or_CC even_RR impossible_JJ to_TO eliminate_VVI (_( Hull_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
To_TO minimize_VVI the_AT possibility_NN1 of_IO a_AT1 bank_NN1 failure_NN1 different_JJ kind_NN1 of_IO regulation_NN1 has_VHZ been_VBN put_VVN on_II place_NN1 ._. 
</s>
<s>
The_AT goal_NN1 of_IO the_AT regulation_NN1 is_VBZ to_TO create_VVI a_AT1 stable_JJ economy_NN1 for_IF individuals_NN2 and_CC companies_NN2 ._. 
</s>
<s>
To_TO build_VVI a_AT1 stable_JJ economy_NN1 and_CC reduce_VVI the_AT possibility_NN1 of_IO a_AT1 bank_NN1 failure_NN1 there_EX is_VBZ a_AT1 system_NN1 that_CST lessens_VVZ the_AT motives_NN2 for_IF risk_NN1 management_NN1 in_II a_AT1 bank_NN1 ,_, namely_REX government_NN1 deposit_NN1 insurance_NN1 ._. 
</s>
<s>
The_AT deposit_NN1 insurance_NN1 helps_VVZ to_TO create_VVI a_AT1 stable_JJ economy_NN1 ,_, as_CSA the_AT customer_NN1 concern_NN1 of_IO losing_VVG money_NN1 is_VBZ decreased_VVN ._. 
</s>
<s>
The_AT deposit_NN1 insurance_NN1 can_VM also_RR create_VVI moral_JJ hazard_NN1 in_II banks_NN2 ,_, as_CSA the_AT bank_NN1 knows_VVZ that_CST the_AT government_NN1 secures_VVZ the_AT depositors_NN2 ._. 
</s>
<s>
This_DD1 is_VBZ the_AT last_MD thing_NN1 the_AT governments_NN2 want_VV0 to_TO achieve_VVI ,_, and_CC therefore_RR deposit_VVI insurances_NN2 are_VBR connected_VVN to_II capital_NN1 requirements_NN2 ._. 
</s>
<s>
An_AT1 important_JJ factor_NN1 of_IO the_AT regulations_NN2 is_VBZ the_AT management_NN1 of_IO system_NN1 risk_NN1 ._. 
</s>
<s>
The_AT system_NN1 risk_NN1 arise_VV0 from_II the_AT strong_JJ correlation_NN1 between_II the_AT banks_NN2 ,_, which_DDQ leads_VVZ to_II the_AT fact_NN1 that_CST if_CS one_PN1 banks_VVZ defaults_NN2 it_PPH1 affects_VVZ other_JJ banks_NN2 ._. 
</s>
<s>
A_AT1 larger_JJR bank_NN1 has_VHZ a_AT1 larger_JJR impact_NN1 on_II the_AT system_NN1 ,_, and_CC if_CS a_AT1 large_JJ bank_NN1 defaults_NN2 ,_, it_PPH1 can_VM start_VVI a_AT1 snowball_NN1 effect_NN1 taking_VVG many_DA2 other_JJ banks_NN2 to_TO default_VVI state_NN1 ._. 
</s>
<s>
This_DD1 could_VM finally_RR lead_VVI to_II a_AT1 total_JJ collapse_NN1 of_IO the_AT financial_JJ system_NN1 (_( Hull_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
To_TO avoid_VVI this_DD1 situation_NN1 the_AT governments_NN2 must_VM take_VVI difficult_JJ decisions_NN2 when_RRQ a_AT1 bank_NN1 is_VBZ in_II a_AT1 risk_NN1 of_IO failure_NN1 :_: to_TO let_VVI the_AT bank_NN1 fail_VVI or_CC to_TO save_VVI it_PPH1 ._. 
</s>
<s>
If_CS the_AT banks_NN2 fails_VVZ it_PPH1 increases_VVZ the_AT system_NN1 risk_NN1 ._. 
</s>
<s>
If_CS it_PPH1 is_VBZ saved_VVN ,_, it_PPH1 can_VM give_VVI a_AT1 wrong_JJ message_NN1 to_II the_AT market_NN1 that_CST the_AT government_NN1 will_VM save_VVI the_AT banks_NN2 ,_, and_CC they_PPHS2 can_VM increase_VVI their_APPGE risks_NN2 to_TO get_VVI higher_JJR profits_NN2 ._. 
</s>
<s>
The_AT purpose_NN1 of_IO the_AT regulation_NN1 is_VBZ to_TO kick_VVI in_RP before_II the_AT banks_NN2 are_VBR in_II risk_NN1 of_IO failure_NN1 ,_, which_DDQ motives_NN2 the_AT regulation_NN1 of_IO banks_NN2 ._. 
</s>
<s>
Regulations_NN2 today_RT Basel_NP1 II_MC Today_RT the_AT bank_NN1 sector_NN1 is_VBZ regulated_VVN by_II the_AT Basel_NP1 regulations_NN2 made_VVN by_II the_AT Basel_NP1 Committee_NN1 on_II Banking_NN1 Supervision_NN1 ._. 
</s>
<s>
The_AT objective_NN1 of_IO the_AT Basel_NP1 regulations_NN2 is_VBZ to_TO control_VVI the_AT risk_NN1 taking_NN1 of_IO banks_NN2 and_CC increase_VV0 the_AT supervision_NN1 of_IO the_AT banking_NN1 sector_NN1 ._. 
</s>
<s>
Basel_VV0 II_MC was_VBDZ implemented_VVN in_II 2007_MC ,_, and_CC the_AT way_NN1 it_PPH1 regulates_VVZ the_AT banking_NN1 sector_NN1 is_VBZ divided_VVN in_II three_MC pillars_NN2 :_: 1_MC1 ._. 
</s>
<s>
capital_NN1 requirements_NN2 ,_, 2._MC supervision_NN1 and_CC 3._MC market_NN1 discipline_NN1 ._. 
</s>
<s>
The_AT three_MC pillars_NN2 is_VBZ discussed_VVN following_VVG ._. 
</s>
<s>
Pillar_NN1 1_MC1 capital_NN1 requirements_NN2 The_AT pillar_NN1 one_PN1 consists_VVZ of_IO capital_NN1 requirements_NN2 to_TO protect_VVI the_AT bank_NN1 against_II various_JJ risks_NN2 ._. 
</s>
<s>
Capital_NN1 requirements_NN2 differentiates_VVZ from_II other_JJ risk_NN1 management_NN1 techniques_NN2 because_CS it_PPH1 is_VBZ a_AT1 protection_NN1 against_II all_DB types_NN2 of_IO risk_NN1 ,_, known_VVN and_CC unknown_JJ ._. 
</s>
<s>
Basel_VV0 II_MC made_VVD some_DD changes_NN2 in_II the_AT way_NN1 credit_NN1 risk_NN1 is_VBZ calculated_VVN compared_VVN to_II Basel_NP1 I_ZZ1 ,_, and_CC brought_VVN a_AT1 new_JJ risk_NN1 class_NN1 :_: Operational_JJ risk_NN1 ._. 
</s>
<s>
In_RR21 addition_RR22 in_II Basel_NP1 II_MC it_PPH1 was_VBDZ decided_VVN that_CST the_AT credit_NN1 rating_NN1 of_IO companies_NN2 assets_NN2 in_II a_AT1 banks_NN2 balance_NN1 should_VM affect_VVI how_RGQ much_DA1 capital_NN1 is_VBZ required_VVN from_II the_AT bank_NN1 ._. 
</s>
<s>
In_II Basel_NP1 I_ZZ1 the_AT capital_NN1 requirement_NN1 was_VBDZ same_DA for_IF an_AT1 A_ZZ1 rated_JJ company_NN1 as_CSA for_IF an_AT1 BB_NP1 rated_VVD ,_, which_DDQ lead_VV0 to_II more_DAR risk_NN1 taking_NN1 by_II banks_NN2 because_CS they_PPHS2 had_VHD a_AT1 larger_JJR spread_NN1 on_II the_AT BB_NP1 companies_NN2 ,_, and_CC wanted_VVD as_RG much_DA1 of_IO these_DD2 instead_II21 of_II22 A_ZZ1 companies_NN2 ._. 
</s>
<s>
The_AT capital_NN1 requirement_NN1 for_IF banks_NN2 is_VBZ 8_MC %_NNU of_IO their_APPGE risk-_JJ weighted_JJ assets_NN2 (_( RWA_NP1 )_) ._. 
</s>
<s>
Total_JJ capital_NN1 requirement_NN1 =_FO 0,08_MC *_FU (_( Credit_NN1 Risk_NN1 RWA_NN1 +_FO Market_NN1 Risk_NN1 RWA_NN1 +_FO Operational_JJ Risk_NN1 RWA_NN1 )_) Pillar_NN1 2_MC Supervision_NN1 Supervision_NN1 and_CC regulation_NN1 was_VBDZ increased_VVN and_CC standardized_VVN in_II Basel_NP1 II_MC ._. 
</s>
<s>
The_AT goal_NN1 is_VBZ to_TO take_VVI care_NN1 of_IO the_AT problems_NN2 before_CS they_PPHS2 arise_VV0 ,_, and_CC to_TO encourage_VVI banks_NN2 to_TO develop_VVI their_APPGE risk_NN1 management_NN1 ._. 
</s>
<s>
As_II a_AT1 part_NN1 of_IO the_AT pillar_NN1 2_MC ,_, stress_NN1 testing_NN1 was_VBDZ implemented_VVN to_II the_AT banking_NN1 sector_NN1 ,_, in_II which_DDQ banks_VVZ risk_NN1 profile_NN1 and_CC risk_NN1 management_NN1 is_VBZ tested_VVN ._. 
</s>
<s>
Pillar_NN1 3_MC Market_NN1 Discipline_NN1 The_AT third_MD pillar_NN1 requires_VVZ the_AT banks_NN2 to_TO disclose_VVI more_DAR information_NN1 how_RRQ their_APPGE capital_NN1 is_VBZ allocated_VVN and_CC what_DDQ kind_NN1 of_IO risks_NN2 they_PPHS2 have_VH0 ._. 
</s>
<s>
The_AT goal_NN1 of_IO this_DD1 is_VBZ to_TO develop_VVI the_AT risk_NN1 management_NN1 of_IO the_AT bank_NN1 ,_, so_CS21 that_CS22 the_AT investors_NN2 and_CC depositors_NN2 get_VV0 to_TO know_VVI the_AT real_JJ situation_NN1 of_IO the_AT banks_NN2 ._. 
</s>
<s>
Development_NN1 of_IO Basel_NP1 II_MC As_CSA noted_VVN earlier_RRR ,_, the_AT GFC_NP1 has_VHZ caused_VVN changes_NN2 in_II the_AT risk_NN1 management_NN1 of_IO financial_JJ companies_NN2 ,_, and_CC much_DA1 of_IO the_AT changes_NN2 come_VV0 from_II increased_JJ regulation_NN1 ._. 
</s>
<s>
Basel_VV0 II_MC is_VBZ further_RRR developed_VVN ,_, and_CC in_II 2013_MC Basel_NP1 III_MC is_VBZ going_VVGK to_TO take_VVI effect_NN1 ._. 
</s>
<s>
In_II this_DD1 chapter_NN1 ,_, I_PPIS1 am_VBM going_VVGK to_TO present_VVI the_AT development_NN1 and_CC changes_NN2 in_II Basel_NP1 II_MC and_CC present_JJ Basel_NP1 III_MC shortly_RR in_II the_AT next_MD chapter_NN1 ._. 
</s>
<s>
To_TO be_VBI better_RRR prepared_VVN against_II future_JJ crisis_NN1 ,_, the_AT development_NN1 of_IO the_AT regulation_NN1 is_VBZ made_VVN to_TO protect_VVI against_II the_AT risks_NN2 that_CST has_VHZ caused_VVN problems_NN2 in_II the_AT last_MD years_NNT2 ._. 
</s>
<s>
Under_II the_AT last_MD crisis_NN1 liquidity_NN1 caused_VVD much_DA1 discussion_NN1 because_CS almost_RR all_DB liquidity_NN1 disappeared_VVD from_II the_AT interbank_JJ market_NN1 ._. 
</s>
<s>
This_DD1 happened_VVD because_CS the_AT banks_NN2 could_VM not_XX trust_VVI other_JJ banks_NN2 because_II21 of_II22 opaqueness_NN1 of_IO banks_NN2 ._. 
</s>
<s>
The_AT situation_NN1 was_VBDZ difficult_JJ due_II21 to_II22 different_JJ financial_JJ innovations_NN2 and_CC a_AT1 de-regulated_JJ market_NN1 ,_, but_CCB the_AT main_JJ point_NN1 is_VBZ that_CST almost_RR all_DB liquidity_NN1 disappeared_VVD ._. 
</s>
<s>
Now_RT regulators_NN2 have_VH0 developed_VVN instruments_NN2 to_TO ensure_VVI that_CST banks_NN2 have_VH0 enough_DD liquidity_NN1 ,_, and_CC that_CST the_AT risk_NN1 management_NN1 of_IO liquidity_NN1 crashes_NN2 is_VBZ on_II a_AT1 good_JJ level_NN1 ._. 
</s>
<s>
Another_DD1 important_JJ development_NN1 factor_NN1 is_VBZ the_AT introduction_NN1 of_IO stress_NN1 tests_NN2 to_II the_AT banking_NN1 sector_NN1 ._. 
</s>
<s>
The_AT stress_NN1 tests_NN2 is_VBZ done_VDN to_TO measure_VVI the_AT banks_NN2 '_GE ability_NN1 to_TO survive_VVI future_JJ crisis_NN1 ._. 
</s>
<s>
In_II the_AT stress_NN1 tests_VVZ an_AT1 imaginary_JJ situations_NN2 is_VBZ made_VVN up_RP ,_, and_CC then_RT test_VV0 the_AT banks_NN2 '_GE ability_NN1 to_TO survive_VVI different_JJ scenarios_NN2 ._. 
</s>
<s>
A_AT1 third_MD development_NN1 to_II the_AT Basel_NP1 II_MC is_VBZ to_TO increase_VVI the_AT capital_NN1 requirement_NN1 for_IF securitized_JJ assets_NN2 (_( for_REX21 example_REX22 MBS_NNU2 )_) ._. 
</s>
<s>
This_DD1 is_VBZ also_RR an_AT1 affect_NN1 from_II the_AT last_MD crisis_NN1 ,_, when_CS securitized_JJ assets_NN2 cased_JJ problems_NN2 in_II the_AT banks_NN2 balances_VVZ ._. 
</s>
<s>
Two_MC risk_NN1 management_NN1 changes_NN2 for_IF banks_NN2 Changes_NN2 have_VH0 not_XX only_RR been_VBN done_VDN to_II the_AT regulative_JJ part_NN1 ,_, but_CCB also_RR to_II the_AT risk_NN1 management_NN1 in_II the_AT banks_NN2 ._. 
</s>
<s>
To_TO improve_VVI the_AT risk_NN1 management_NN1 two_MC new_JJ measures_NN2 of_IO risk_NN1 has_VHZ been_VBN implemented_VVN :_: Incremental_JJ Risk_NN1 Charge_NN1 (_( IRC_NP1 )_) and_CC stressed_VVD VaR_NP1 ._. 
</s>
<s>
Both_DB2 of_IO the_AT measures_NN2 will_VM increase_VVI the_AT capital_NN1 requirement_NN1 for_IF banks_NN2 ._. 
</s>
<s>
IRC_NP1 is_VBZ implemented_VVN because_CS the_AT Basel_NP1 Committee_NN1 where_CS worried_JJ that_CST the_AT banks_NN2 would_VM shift_VVI their_APPGE assets_NN2 from_II the_AT banking_NN1 book_NN1 to_II the_AT trading_NN1 book_NN1 ._. 
</s>
<s>
The_AT change_NN1 of_IO the_AT assets_NN2 from_II the_AT banking_NN1 to_II trading_NN1 book_NN1 is_VBZ possible_JJ by_II securitization_NN1 and_CC structured_JJ products_NN2 ._. 
</s>
<s>
An_AT1 example_NN1 of_IO this_DD1 is_VBZ the_AT trading_NN1 of_IO real_JJ estate_NN1 mortgages_NN2 as_II MBS_NNU2 securities_NN2 ._. 
</s>
<s>
In_II normal_JJ cases_NN2 the_AT risk_NN1 of_IO the_AT assets_NN2 in_II the_AT trading_NN1 book_NN1 was_VBDZ accounted_VVN had_VHD different_JJ risk_NN1 profiles_NN2 than_CSN in_II the_AT banking_NN1 book_NN1 ._. 
</s>
<s>
Now_RT assets_NN2 from_II the_AT banking_NN1 book_NN1 was_VBDZ transferred_VVN to_II the_AT trading_NN1 book_NN1 ,_, which_DDQ would_VM mean_VVI that_CST a_AT1 bank_NN1 can_VM take_VVI more_DAR risk_NN1 because_CS the_AT risk_NN1 profile_NN1 of_IO the_AT assets_NN2 in_II the_AT banking_NN1 book_NN1 were_VBDR more_RGR strict_JJ ._. 
</s>
<s>
The_AT Basel_NP1 Committee_NN1 has_VHZ proposed_VVN that_CST structured_JJ assets_NN2 in_II the_AT trading_NN1 book_NN1 should_VM be_VBI accounted_VVN with_IW the_AT same_DA risk_NN1 profile_NN1 as_CSA the_AT products_NN2 in_II the_AT banking_NN1 book_NN1 ._. 
</s>
<s>
IRC_NP1 will_VM be_VBI implemented_VVN during_II 2011_MC ._. 
</s>
<s>
Another_DD1 improvement_NN1 to_II the_AT risk_NN1 management_NN1 is_VBZ implementation_NN1 of_IO a_AT1 measure_NN1 called_VVN stressed_JJ VaR_NN1 ._. 
</s>
<s>
In_II normal_JJ risk_NN1 management_NN1 VaR_NN1 is_VBZ accounted_VVN for_IF a_AT1 period_NN1 of_IO two_MC to_II four_MC years_NNT2 ._. 
</s>
<s>
Stressed_JJ VaR_NN1 is_VBZ accounted_VVN from_II market_NN1 variables_NN2 during_II one_MC1 year_NNT1 of_IO losses_NN2 ._. 
</s>
<s>
This_DD1 would_VM give_VVI the_AT banks_NN2 a_AT1 sum_NN1 of_IO loss_NN1 that_CST would_VM not_XX be_VBI exceeded_VVN (_( on_II a_AT1 99%_NNU chance_NN1 )_) even_RR the_AT economy_NN1 would_VM be_VBI in_II recession_NN1 ._. 
</s>
<s>
The_AT Basel_NP1 Committee_NN1 have_VH0 proposed_VVN that_CST the_AT market_NN1 risk_NN1 of_IO banks_NN2 is_VBZ calculated_VVN of_IO the_AT sum_NN1 of_IO VaR_NP1 and_CC stressed_VVD VaR_NP1 ._. 
</s>
<s>
These_DD2 changes_NN2 will_VM at_RR21 least_RR22 double_VVI the_AT capital_NN1 requirement_NN1 for_IF market_NN1 risk_NN1 banks_NN2 have_VH0 (_( Hull_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
Stressed_JJ VaR_NN1 will_VM be_VBI implemented_VVN in_II the_AT late_JJ 2011_MC ._. 
</s>
<s>
Basel_VV0 III_MC The_AT development_NN1 of_IO Basel_NP1 II_MC has_VHZ gone_VVN towards_II increased_JJ regulation_NN1 ,_, and_CC Basel_NP1 III_MC makes_VVZ changes_NN2 towards_II even_RR more_DAR regulation_NN1 and_CC supervision_NN1 ._. 
</s>
<s>
This_DD1 papers_VVZ presentation_NN1 of_IO Basel_NP1 III_MC is_VBZ based_VVN on_II meeting_VVG notes_NN2 of_IO Nout_NP1 Wellink_NP1 ,_, the_AT president_NN1 of_IO Basel_NP1 Committee_NN1 and_CC Banking_NN1 Supervision_NN1 ,_, from_II a_AT1 meeting_NN1 in_II Malaysia_NP1 17_MC January_NPM1 2011_MC ._. 
</s>
<s>
In_II the_AT notes_NN2 Wellink_VV0 presents_NN2 that_CST Basel_NP1 III_MC is_VBZ made_VVN to_TO prepare_VVI the_AT banks_NN2 against_II future_JJ crisis_NN1 ._. 
</s>
<s>
The_AT globalization_NN1 and_CC financial_JJ innovations_NN2 puts_VVZ higher_JJR demand_NN1 on_II capital_NN1 requirements_NN2 ,_, and_CC increased_JJ liquidity_NN1 must_VM be_VBI implemented_VVN in_II the_AT system_NN1 to_TO protect_VVI against_II unknown_JJ ,_, unexpected_JJ risks_NN2 ._. 
</s>
<s>
The_AT problems_NN2 that_CST caused_VVD the_AT last_MD crisis_NN1 must_VM be_VBI manageable_JJ in_II the_AT future_NN1 ._. 
</s>
<s>
Wellink_NN1 brings_VVZ forward_RL the_AT main_JJ points_NN2 that_CST caused_VVD the_AT crisis_NN1 which_DDQ must_VM be_VBI protected_VVN in_II the_AT future_NN1 :_: The_AT primary_JJ reason_NN1 why_RRQ the_AT GFC_NP1 began_VVD was_VBDZ :_: excess_JJ global_JJ liquidity_NN1 ,_, too_RG high_JJ usage_NN1 of_IO leverage_NN1 ,_, too_RG little_DA1 good_JJ quality_NN1 capital_NN1 ,_, and_CC inadequate_JJ capital_NN1 reserved_VVN for_IF liquidity_NN1 problems_NN2 The_AT crisis_NN1 worsened_VVN when_CS international_JJ financial_JJ companies_NN2 ,_, which_DDQ were_VBDR too-big-to-fail_JJ ,_, decreased_VVD their_APPGE indebtedness_NN1 (_( decrease_VV0 leverage_NN1 )_) at_II the_AT same_DA time_NNT1 ._. 
</s>
<s>
As_CSA they_PPHS2 all_DB sold_VVD their_APPGE assets_NN2 the_AT prices_NN2 plummeted_VVD ._. 
</s>
<s>
Additional_JJ reasons_NN2 for_IF the_AT crisis_NN1 were_VBDR inadequate_JJ risk_NN1 management_NN1 ,_, corporate_JJ governance_NN1 ,_, and_CC transparency_NN1 ._. 
</s>
<s>
There_EX were_VBDR also_RR wrong_JJ incentives_NN2 in_II compensation_NN1 systems_NN2 and_CC bad_JJ quality_NN1 supervision_NN1 ._. 
</s>
<s>
The_AT risk_NN1 management_NN1 and_CC supervision_NN1 failed_VVN because_CS the_AT understanding_NN1 on_II system_NN1 risk_NN1 under_II recession_NN1 was_VBDZ not_XX adequate_JJ ._. 
</s>
<s>
To_TO develop_VVI and_CC improve_VVI the_AT risk_NN1 management_NN1 in_II the_AT future_JJ Basel_NP1 III_MC is_VBZ going_VVGK to_TO manage_VVI both_DB2 company_NN1 specific_JJ risks_NN2 and_CC market_VV0 risk_NN1 on_II the_AT banking_NN1 sector_NN1 ._. 
</s>
<s>
The_AT company_NN1 specific_JJ risks_NN2 in_II handled_VVD through_II rules_NN2 and_CC regulations_NN2 ,_, when_CS the_AT market_NN1 risk_VV0 in_RP handled_VVD on_II a_AT1 macro-level_NN1 that_CST will_VM give_VVI information_NN1 about_II the_AT system_NN1 risk_NN1 and_CC the_AT connections_NN2 between_II banks_NN2 ._. 
</s>
<s>
Basel_VV0 III_MC will_VM contain_VVI the_AT following_JJ improvements_NN2 on_II a_AT1 company_NN1 level_NN1 :_: Increase_VV0 the_AT quantity_NN1 and_CC quality_NN1 on_II capital_NN1 requirements_NN2 Implement_VV0 stressed_JJ VaR_NN1 ,_, which_DDQ i_MC1 explained_VVD earlier_JJR Banks_NN2 must_VM keep_VVI more_DAR capital_NN1 for_IF less_RGR liquid_JJ credit_NN1 sensitive_JJ assets_NN2 Capital_NN1 requirements_NN2 for_IF securitized_JJ assets_NN2 will_VM be_VBI made_VVN consistent_JJ with_IW the_AT capital_NN1 requirements_NN2 in_II the_AT banking_NN1 book_NN1 (_( higher_JJR capital_NN1 requirements_NN2 )_) Increase_VV0 the_AT supervision_NN1 ,_, risk_NN1 management_NN1 and_CC transparency_NN1 Improvements_NN2 on_II macro_JJ level_NN1 :_: The_AT financial_JJ companies_NN2 should_VM have_VHI capital_NN1 reserved_VVN for_IF credit_NN1 bubbles_NN2 ._. 
</s>
<s>
This_DD1 reserved_JJ capital_NN1 can_VM be_VBI used_VVN in_II a_AT1 crisis_NN1 ._. 
</s>
<s>
A_AT1 new_JJ ,_, easy_JJ to_TO understand_VVI ratio_NN1 ,_, will_VM be_VBI established_VVN that_CST will_VM put_VVI an_AT1 end_NN1 to_II the_AT risk_NN1 driven_JJ system_NN1 we_PPIS2 have_VH0 today_RT A_AT1 tool_NN1 to_TO handle_VVI international_JJ liquidity_NN1 will_VM be_VBI created_VVN To_TO summarize_VVI Basel_NP1 III_MC will_VM increase_VVI the_AT level_NN1 of_IO regulation_NN1 ,_, supervision_NN1 and_CC raise_VV0 the_AT capital_NN1 requirements_NN2 ._. 
</s>
<s>
This_DD1 will_VM have_VHI an_AT1 influence_NN1 on_II the_AT whole_NN1 financial_JJ system_NN1 by_II affecting_VVG banks_NN2 risk_VV0 management_NN1 ._. 
</s>
<s>
Analysis_NN1 How_RRQ the_AT changes_NN2 affect_VV0 banks_NN2 All_DB the_AT development_NN1 and_CC changes_NN2 in_II risk_NN1 management_NN1 and_CC regulation_NN1 will_VM affect_VVI the_AT operations_NN2 of_IO banks_NN2 ._. 
</s>
<s>
These_DD2 changes_NN2 are_VBR done_VDN so_CS21 that_CS22 consumers_NN2 and_CC companies_NN2 would_VM have_VHI a_AT1 stable_JJ market_NN1 ,_, with_IW secure_JJ banks_NN2 ._. 
</s>
<s>
The_AT changes_NN2 affect_VV0 different_JJ parts_NN2 of_IO a_AT1 bank_NN1 's_GE operations_NN2 ,_, of_IO which_DDQ three_MC important_JJ changes_NN2 will_VM be_VBI analysed_VVN :_: increased_JJ capital_NN1 requirements_NN2 ,_, transparency_NN1 and_CC supervision_NN1 ,_, and_CC developed_JJ risk_NN1 management_NN1 ._. 
</s>
<s>
Additionally_RR the_AT planned_JJ international_JJ liquidity_NN1 tools_NN2 are_VBR analysed_VVN on_II macro_JJ level_NN1 ._. 
</s>
<s>
Increased_JJ capital_NN1 requirements_NN2 Many_DA2 points_NN2 of_IO the_AT development_NN1 in_II risk_NN1 management_NN1 are_VBR done_VDN to_TO increase_VVI the_AT capital_NN1 requirements_NN2 for_IF banks_NN2 ._. 
</s>
<s>
This_DD1 point_NN1 will_VM be_VBI analysed_VVN because_CS capital_NN1 requirements_NN2 are_VBR connected_VVN to_II the_AT central_JJ operations_NN2 for_IF banks_NN2 ._. 
</s>
<s>
How_RRQ to_TO increase_VVI To_TO increase_VVI the_AT amount_NN1 of_IO capital_NN1 in_II their_APPGE reserves_NN2 ,_, banks_NN2 would_VM in_II theory_NN1 have_VH0 a_AT1 couple_NN1 choices_NN2 ._. 
</s>
<s>
If_CS the_AT capital_NN1 requirement_NN1 would_VM be_VBI increased_VVN immediately_RR ,_, banks_NN2 would_VM have_VHI the_AT choice_NN1 to_TO sell_VVI their_APPGE assets_NN2 and_CC reduce_VVI the_AT total_JJ assets_NN2 ,_, and_CC at_II the_AT same_DA time_NNT1 ,_, the_AT amount_NN1 of_IO capital_NN1 would_VM increase_VVI ._. 
</s>
<s>
Another_DD1 choice_NN1 would_VM be_VBI to_TO keep_VVI the_AT old_JJ assets_NN2 ,_, and_CC only_RR raise_VV0 their_APPGE spread_NN1 on_II money_NN1 ._. 
</s>
<s>
In_II practice_NN1 banks_NN2 would_VM have_VHI to_TO do_VDI the_AT both_RR ,_, which_DDQ brings_VVZ us_PPIO2 to_II the_AT problems_NN2 in_II future_JJ problems_NN2 in_II raising_VVG capital_NN1 requirements_NN2 ._. 
</s>
<s>
If_CS one_MC1 bank_NN1 would_VM want_VVI to_TO sell_VVI its_APPGE assets_NN2 to_TO increase_VVI the_AT capital_NN1 requirement_NN1 ,_, it_PPH1 would_VM not_XX be_VBI an_AT1 problem_NN1 ._. 
</s>
<s>
The_AT problems_NN2 start_VV0 when_RRQ all_DB the_AT banks_NN2 do_VD0 this_DD1 at_II the_AT same_DA time_NNT1 ._. 
</s>
<s>
Then_RT there_EX is_VBZ an_AT1 increase_NN1 in_II the_AT supply_NN1 of_IO assets_NN2 ,_, which_DDQ pushes_VVZ the_AT prices_NN2 of_IO assets_NN2 down_RP ._. 
</s>
<s>
When_CS the_AT prices_NN2 fall_VV0 ,_, so_RR does_VDZ also_RR the_AT price_NN1 of_IO the_AT assets_NN2 still_RR left_VVN in_II the_AT banks_NN2 '_GE balance_NN1 ,_, which_DDQ the_AT banks_NN2 want_VV0 to_TO avoid_VVI ._. 
</s>
<s>
The_AT other_JJ choice_NN1 is_VBZ to_TO increase_VVI the_AT spread_NN1 ;_; and_CC through_II this_DD1 get_VV0 a_AT1 larger_JJR profit_NN1 on_II the_AT money_NN1 ._. 
</s>
<s>
Increasing_VVG the_AT spread_NN1 would_VM have_VHI an_AT1 effect_NN1 on_II the_AT banks_NN2 competitive_JJ position_NN1 if_CS other_JJ banks_NN2 would_VM not_XX do_VDI the_AT same_DA at_II the_AT same_DA time_NNT1 ._. 
</s>
<s>
This_DD1 ,_, in_II contrast_NN1 to_II asset_NN1 sales_NN ,_, should_VM be_VBI done_VDN synchronized_JJ by_II all_DB banks_NN2 ,_, because_CS otherwise_RR the_AT competition_NN1 would_VM make_VVI the_AT bank_NN1 lose_VVI its_APPGE customers_NN2 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, this_DD1 would_VM increase_VVI the_AT cost_NN1 of_IO money_NN1 on_II the_AT market_NN1 ,_, which_DDQ affects_VVZ the_AT whole_JJ development_NN1 of_IO the_AT economy_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ tough_JJ a_AT1 difficult_JJ question_NN1 for_IF regulators_NN2 ,_, who_PNQS are_VBR looking_VVG for_IF the_AT best_JJT answer_NN1 to_II the_AT economy_NN1 ._. 
</s>
<s>
How_RRQ the_AT changes_NN2 affect_VV0 banks_NN2 Interesting_JJ in_II this_DD1 that_CST the_AT banks_NN2 must_VM make_VVI these_DD2 changes_NN2 ,_, and_CC therefore_RR it_PPH1 is_VBZ important_JJ that_CST the_AT changes_NN2 are_VBR done_VDN on_II a_AT1 long_JJ time_NNT1 horizon_NN1 ._. 
</s>
<s>
How_RRQ the_AT changes_NN2 can_VM affect_VVI the_AT operation_NN1 of_IO banks_NN2 is_VBZ discussed_VVN next_MD ._. 
</s>
<s>
I_PPIS1 will_VM start_VVI by_II making_VVG a_AT1 short_JJ conclusion_NN1 on_II what_DDQ assets_NN2 banks_NN2 must_VM increase_VVI capital_NN1 ._. 
</s>
<s>
Capital_NN1 requirements_NN2 are_VBR increased_VVN on_RP ;_; credit_NN1 risk_NN1 ,_, operational_JJ risk_NN1 ,_, securitized_VVD assets_NN2 ,_, non-liquid_JJ assets_NN2 ,_, and_CC preparation_NN1 for_IF difficult_JJ times_NNT2 and_CC credit_NN1 bubbles_NN2 ._. 
</s>
<s>
Moreover_RR ,_, the_AT capital_NN1 requirement_NN1 depends_VVZ on_II the_AT rating_NN1 of_IO companies_NN2 banks_NN2 operate_VV0 with_IW ._. 
</s>
<s>
By_II all_DB these_DD2 regulations_NN2 and_CC rules_NN2 banks_NN2 are_VBR forced_VVN to_TO increase_VVI their_APPGE capital_NN1 ,_, without_IW rules_NN2 how_RRQ to_TO do_VDI it_PPH1 ._. 
</s>
<s>
The_AT interesting_JJ thing_NN1 with_IW rating_NN1 based_VVN capital_NN1 requirements_NN2 is_VBZ that_CST one_PN1 can_VM choose_VVI a_AT1 low_JJ risk_NN1 customer_NN1 that_CST pays_VVZ a_AT1 low_JJ spread_NN1 ,_, or_CC a_AT1 high-risk_JJ customer_NN1 that_CST pays_VVZ a_AT1 high_JJ spread_NN1 ._. 
</s>
<s>
In_II the_AT latter_DA case_NN1 a_AT1 bank_NN1 must_VM reserve_VVI more_DAR capital_NN1 ,_, that_DD1 will_VM decrease_VVI their_APPGE other_JJ operations_NN2 ._. 
</s>
<s>
I_PPIS1 think_VV0 that_CST this_DD1 will_VM lead_VVI to_II banks_NN2 searching_VVG companies_NN2 that_CST have_VH0 a_AT1 higher_JJR rating_NN1 than_CSN believed_VVN ,_, and_CC thus_RR the_AT capital_NN1 requirement_NN1 is_VBZ lower_JJR than_CSN it_PPH1 should_VM be_VBI ._. 
</s>
<s>
The_AT bank_NN1 can_VM have_VHI this_DD1 information_NN1 if_CS a_AT1 company_NN1 is_VBZ a_AT1 customer_NN1 of_IO a_AT1 bank_NN1 ,_, then_RT the_AT bank_NN1 has_VHZ insider_NN1 information_NN1 that_CST rating_VVG agencies_NN2 do_VD0 not_XX ._. 
</s>
<s>
Therefore_RR ,_, in_II the_AT end_NN1 the_AT system_NN1 can_VM lead_VVI to_II more_DAR risk_NN1 taking_NN1 by_II bank_NN1 that_CST does_VDZ not_XX show_VVI anywhere_RL ._. 
</s>
<s>
Transparency_NN1 and_CC supervision_NN1 Developed_JJ risk_NN1 management_NN1 -_- :_: stress_NN1 testing_NN1 ,_, IRC_NP1 ,_, stressed_VVD VaR_NP1 International_JJ liquidity_NN1 tools_NN2 Conclusions_NN2 
</s>
