<s>
1_MC1 ._. 
</s>
<s>
Introduction_NN1 The_AT rise_NN1 of_IO the_AT Internet_NN1 has_VHZ both_DB2 challenged_VVN and_CC provided_VVD companies_NN2 with_IW new_JJ opportunities_NN2 ._. 
</s>
<s>
The_AT influence_NN1 of_IO the_AT Internet_NN1 has_VHZ been_VBN especially_RR strong_JJ on_II marketing_NN1 and_CC communication_NN1 efforts_NN2 (_( Heinen_NP1 1996_MC )_) ._. 
</s>
<s>
Today_RT ,_, it_PPH1 is_VBZ not_XX only_JJ companies_NN2 that_CST can_VM reach_VVI bigger_JJR audiences_NN2 at_II a_AT1 lower_JJR cost_NN1 than_CSN ever_RR before_RT ,_, but_CCB it_PPH1 is_VBZ also_RR the_AT first_MD time_NNT1 in_II our_APPGE history_NN1 that_CST individuals_NN2 can_VM easily_RR publicise_VVI their_APPGE thoughts_NN2 ,_, reactions_NN2 ,_, and_CC emotions_NN2 to_II the_AT global_JJ network_NN1 of_IO Internet_NN1 users_NN2 (_( Dellarocas_NN2 2003_MC )_) ._. 
</s>
<s>
The_AT Internet_NN1 is_VBZ developing_VVG into_II a_AT1 medium_NN1 where_RRQ companies_NN2 and_CC customers_NN2 can_VM interact_VVI with_IW each_PPX221 other_PPX222 ,_, changing_VVG the_AT marketers_NN2 role_NN1 (_( Heinen_NP1 1996_MC )_) ._. 
</s>
<s>
Traditionally_RR ,_, the_AT marketer_NN1 has_VHZ been_VBN the_AT sender_NN1 of_IO messages_NN2 and_CC the_AT customer_NN1 the_AT receiver_NN1 of_IO them_PPHO2 ._. 
</s>
<s>
Today_RT ,_, both_RR marketers_NN2 and_CC customers_NN2 are_VBR sending_VVG and_CC receiving_VVG messages_NN2 (_( Leskovec_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2008_MC )_) ._. 
</s>
<s>
Moreover_RR ,_, customers_NN2 are_VBR communicating_VVG with_IW one_PPX121 another_PPX122 in_II more_RGR efficient_JJ ways_NN2 than_CSN ever_RR before_II (_( Dellarocas_NN2 2003_MC ,_, Leskovec_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2008_MC )_) ._. 
</s>
<s>
The_AT development_NN1 of_IO the_AT Internet_NN1 has_VHZ enabled_VVN consumers_NN2 to_TO communicate_VVI with_IW one_PPX121 another_PPX122 on_II completely_RR new_JJ platforms_NN2 ,_, transforming_VVG traditional_JJ word-of-mouth_NN1 (_( WOM_NP1 )_) to_II electronic-word-of-mouth_NN1 ,_, eWOM_NN1 (_( Dellarocas_NN2 2003_MC )_) ._. 
</s>
<s>
Recently_RR ,_, several_DA2 studies_NN2 have_VH0 been_VBN conducted_VVN on_II eWOM_NN1 ._. 
</s>
<s>
(_( Heinen_NP1 1996_MC ,_, Dellarocas_NN2 2003_MC ,_, Mazzarol_NP1 2007_MC )_) ._. 
</s>
<s>
The_AT content_NN1 of_IO WOM_NP1 has_VHZ traditionally_RR been_VBN unknown_JJ to_II marketers_NN2 ,_, even_CS21 though_CS22 WOM_NP1 has_VHZ been_VBN defined_VVN as_II the_AT most_RGT efficient_JJ communications_NN2 channel_NN1 (_( Keller_NP1 2007_MC )_) ._. 
</s>
<s>
The_AT nature_NN1 of_IO the_AT Internet_NN1 has_VHZ enabled_VVN marketers_NN2 to_TO reach_VVI the_AT unknown_JJ ,_, since_CS all_DB online_JJ communication_NN1 can_VM be_VBI traced_VVN ._. 
</s>
<s>
Marketers_NN2 are_VBR now_RT increasingly_RR interested_JJ in_II using_VVG the_AT previously_RR unreachable_JJ communication_NN1 channel_NN1 ,_, but_CCB in_BCL21 order_BCL22 to_TO do_VDI so_RR ,_, further_JJR research_NN1 is_VBZ needed_VVN (_( Shao_NP1 2008_MC )_) ._. 
</s>
<s>
As_RG several_DA2 studies_NN2 have_VH0 concluded_VVN ,_, consumer-to-consumer_JJ communication_NN1 ,_, or_CC WOM_NP1 ,_, has_VHZ a_AT1 great_JJ influence_NN1 on_II consumers_NN2 purchase_VV0 decisions_NN2 and_CC brand_NN1 attitude_NN1 ._. 
</s>
<s>
(_( Engel_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
1966_MC ;_; Herr_NN1 et_RA21 al_RA22 ._. 
</s>
<s>
1991_MC ;_; Bone_NN1 ,_, 1995_MC )_) ._. 
</s>
<s>
Even_CS21 though_CS22 many_DA2 researchers_NN2 have_VH0 studied_VVN eWOM_NN1 ,_, only_RR a_AT1 few_DA2 have_VH0 studied_VVN the_AT motives_NN2 of_IO individuals_NN2 to_TO participate_VVI in_II eWOM_NN1 (_( Hennig-Thurau_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2004_MC ,_, Sen_NP1 &Lerman;_NULL 2007_MC ,_, Shao_NP1 2008_MC ._. 
</s>
<s>
In_II their_APPGE study_NN1 about_II eWOM_NN1 ,_, Hennig-Thurau_NP1 (_( 2004_MC )_) defined_VVD different_JJ consumer_NN1 segments_NN2 according_II21 to_II22 consumers_NN2 motives_NN2 to_II post_NN1 content_NN1 online_RR ._. 
</s>
<s>
The_AT study_NN1 was_VBDZ quantitative_JJ and_CC employed_VVD statistical_JJ methods_NN2 to_TO define_VVI four_MC segments_NN2 ._. 
</s>
<s>
1.1_MC ._. 
</s>
<s>
Aim_NN1 of_IO the_AT Study_NN1 To_TO understand_VVI the_AT motives_NN2 that_CST consumers_NN2 have_VH0 to_TO articulate_VVI themselves_PPX2 via_II eWOM_NN1 ,_, this_DD1 study_NN1 shifts_VVZ the_AT focus_NN1 from_II studying_VVG the_AT masses_NN2 (_( Hennig-Thurau_NP1 2004_MC )_) to_II studying_VVG the_AT individual_NN1 ._. 
</s>
<s>
The_AT aim_NN1 is_VBZ to_TO understand_VVI why_RRQ one_MC1 individual_JJ posts_NN2 comments_VVZ online_RR ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, what_DDQ are_VBR the_AT various_JJ motivations_NN2 of_IO an_AT1 individual_JJ to_TO participate_VVI in_II eWOM_NN1 ?_? 
</s>
<s>
This_DD1 study_NN1 aims_VVZ at_II deep_JJ knowledge_NN1 on_II consumer_NN1 motivations_NN2 to_TO participate_VVI in_II eWOM_NN1 ._. 
</s>
<s>
The_AT aim_NN1 is_VBZ depth_NN1 ,_, not_XX breadth_NN1 ._. 
</s>
<s>
According_II21 to_II22 Patton_NP1 (_( 2002:244_MC )_) in-depth_JJ information_NN1 can_VM be_VBI very_RG valuable_JJ ._. 
</s>
<s>
Considering_CS21 that_CS22 there_EX is_VBZ broad_JJ knowledge_NN1 on_II the_AT phenomenon_NN1 (_( e.g._REX Hennig-Thurau_NP1 2004_MC )_) ,_, in-depth_JJ knowledge_NN1 is_VBZ valuable_JJ both_RR for_IF the_AT researcher_NN1 and_CC marketers._NNU 1.2_MC ._. 
</s>
<s>
The_AT Structure_NN1 of_IO the_AT Paper_NN1 This_DD1 paper_NN1 will_VM try_VVI to_TO find_VVI an_AT1 answer_NN1 to_II the_AT research_NN1 question_NN1 according_II21 to_II22 the_AT following_JJ structure:in_FO the_AT next_MD section_NN1 ,_, the_AT theoretical_JJ framework_NN1 of_IO consumers_NN2 motivates_VVZ to_TO participate_VVI ineWOM_NN1 will_VM be_VBI described_VVN ,_, followed_VVN by_II a_AT1 description_NN1 of_IO the_AT method_NN1 deployed_VVN to_TO conduct_VVI the_AT empirical_JJ study_NN1 ._. 
</s>
<s>
The_AT paper_NN1 will_VM continue_VVI with_IW the_AT results_NN2 and_CC analysis_NN1 of_IO the_AT data.The_NNU paper_NN1 will_VM end_VVI with_IW conclusions_NN2 and_CC recommendations_NN2 for_IF future_JJ research_NN1 ._. 
</s>
<s>
2_MC ._. 
</s>
<s>
Theoretical_JJ Framework_NN1 The_AT theoretical_JJ framework_NN1 is_VBZ based_VVN on_II Hennig-Thuraus(2004)_JJ quantitative_JJ study_NN1 on_II consumers_NN2 motives_NN2 to_TO participate_VVI in_II eWOM_NN1 ._. 
</s>
<s>
In_II his_APPGE study_NN1 ,_, he_PPHS1 identified_VVD four_MC different_JJ segments_NN2 according_II21 to_II22 eight_MC motives_NN2 that_CST consumers_NN2 have_VH0 for_IF participating_VVG in_II eWOM_NN1 ._. 
</s>
<s>
Table_NN1 1_MC1 summarizes_VVZ the_AT findings_NN2 ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) Drawing_VVG from_II Hennig-Thuraus_NP1 (_( 2004_MC )_) results_NN2 ,_, it_PPH1 can_VM be_VBI stated_VVN that_CST different_JJ according_II21 to_II22 motives_NN2 that_CST individuals_NN2 have_VH0 to_TO participate_VVI in_II eWOM_NN1 ,_, various_JJ consumer_NN1 segments_NN2 exist_VV0 ._. 
</s>
<s>
However_RR ,_, the_AT question_NN1 remains_VVZ ,_, what_DDQ kind_NN1 of_IO motives_NN2 one_MC1 individual_NN1 may_VM have_VHI to_TO participate_VVI in_II eWOM_NN1 ._. 
</s>
<s>
The_AT following_JJ will_VM shortly_RR describe_VVI the_AT different_JJ segments_NN2 and_CC the_AT relative_JJ motives_NN2 (_( 1-8_MCMC )_) ._. 
</s>
<s>
2.1_MC ._. 
</s>
<s>
Self-Interested_JJ Helpers_NN2 Individuals_NN2 in_II this_DD1 segment_NN1 are_VBR motivated_VVN to_II post_NN1 online_JJ comments_NN2 because_CS they_PPHS2 are_VBR driven_VVN by_II economic_JJ incentives_NN2 ._. 
</s>
<s>
A_AT1 platform_NN1 operator_NN1 can_VM offer_VVI economic_JJ rewards_NN2 to_II those_DD2 individuals_NN2 that_CST are_VBR active_JJ (_( Hennig-Thurau_NP1 2004_MC )_) ._. 
</s>
<s>
According_II21 to_II22 Lawler_NP1 (_( 2003_MC )_) economic_JJ incentives_NN2 are_VBR an_AT1 important_JJ tool_NN1 in_II influencing_VVG human_JJ behaviour_NN1 ,_, which_DDQ is_VBZ the_AT case_NN1 also_RR in_II online_JJ behaviour_NN1 ._. 
</s>
<s>
According_II21 to_II22 Hennig-Thuraus_NP1 study_NN1 ,_, most_DAT (_( 34%_NNU )_) of_IO the_AT consumers_NN2 participating_VVG in_II eWOM_NN1 belong_VV0 to_II this_DD1 segment_NN1 ._. 
</s>
<s>
2.2_MC ._. 
</s>
<s>
Multiple-Motive_JJ Consumers_NN2 Individuals_NN2 in_II this_DD1 segment_NN1 are_VBR motivated_VVN to_TO participate_VVI in_II eWOM_NN1 for_IF a_AT1 variety_NN1 of_IO reasons_NN2 ._. 
</s>
<s>
The_AT first_MD motive_NN1 ,_, platform_NN1 assistance_NN1 refers_VVZ to_II an_AT1 individual_JJ participating_JJ in_II eWOM_NN1 because_CS she_PPHS1 hopes_VVZ that_CST the_AT platform_NN1 operator_NN1 could_VM assist_VVI her_APPGE problem_NN1 solving_NN1 ._. 
</s>
<s>
The_AT second_MD motive_NN1 ,_, venting_VVG negative_JJ feelings_NN2 refers_VVZ to_II an_AT1 individual_JJ participating_JJ in_II eWOM_NN1 to_TO complain_VVI or_CC in_II other_JJ ways_NN2 express_VV0 negative_JJ feelings_NN2 ._. 
</s>
<s>
Not_XX only_RR does_VDZ an_AT1 individual_NN1 participate_VVI in_II eWOM_NN1 to_TO express_VVI negative_JJ emotions_NN2 ,_, but_CCB also_RR to_TO enhance_VVI oneself_PNX1 positively_RR ._. 
</s>
<s>
The_AT motive_NN1 rises_VVZ from_II an_AT1 individuals_NN2 need_VV0 to_TO gain_VVI acceptance_NN1 from_II others_NN2 (_( Sundraram_NP1 et_RA21 al_RA22 1998_MC )_) ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO gain_VVI acceptance_NN1 ,_, individuals_NN2 seek_VV0 to_TO show_VVI a_AT1 positive_JJ image_NN1 of_IO themselves_PPX2 ,_, therefore_RR participating_VVG in_II positive_JJ eWOM_NN1 (_( Shao_NP1 2008_MC )_) ._. 
</s>
<s>
Finally_RR ,_, individuals_NN2 participate_VV0 in_II eWOM_NN1 to_TO get_VVI help_NN1 from_II peers_NN2 ,_, in_II other_JJ words_NN2 seek_VV0 for_IF advice_NN1 ._. 
</s>
<s>
2.3_MC ._. 
</s>
<s>
Consumer_NN1 Advocates_NN2 Individuals_NN2 in_II this_DD1 segment_NN1 participate_VV0 in_II eWOM_NN1 mainly_RR out_II21 of_II22 concern_NN1 for_IF other_JJ consumers_NN2 (_( Hennig-Thurau_NP1 2004_MC )_) ._. 
</s>
<s>
According_II21 to_II22 Carman_NP1 (_( 1992_MC )_) ,_, individuals_NN2 are_VBR motivated_VVN to_TO participate_VVI in_II communication_NN1 because_CS they_PPHS2 believe_VV0 it_PPH1 is_VBZ beneficial_JJ for_IF other_JJ consumers_NN2 ._. 
</s>
<s>
2.4_MC ._. 
</s>
<s>
True_JJ Altruists_NN2 The_AT true_JJ altruists_NN2 participate_VV0 in_II eWOM_NN1 out_II21 of_II22 selfless_JJ motives_NN2 :_: they_PPHS2 seek_VV0 tohelp_VV0 other_JJ consumers_NN2 or_CC companies_NN2 (_( Hennig-Thurau_NP1 2004_MC )_) ._. 
</s>
<s>
According_II21 to_II22 Sundaram_NP1 et_RA21 al_RA22 (_( 1998_MC )_) ,_, consumers_NN2 are_VBR motivated_VVN to_TO help_VVI companies_NN2 mainly_RR out_II21 of_II22 being_VBG satisfied_VVN with_IW the_AT companys_NN2 products_NN2 or_CC services_NN2 ._. 
</s>
<s>
If_CS the_AT consumers_NN2 expectations_NN2 are_VBR exceeded_VVN ,_, she_PPHS1 may_VM experience_VVI feelings_NN2 of_IO guilt_NN1 ._. 
</s>
<s>
Therefore_RR ,_, she_PPHS1 wants_VVZ to_TO give_VVI something_PN1 back_RP to_II the_AT company_NN1 ._. 
</s>
<s>
eWOM_NN1 is_VBZ an_AT1 effective_JJ channel_NN1 to_TO reach_VVI other_JJ consumers_NN2 ,_, and_CC a_AT1 perfect_JJ platform_NN1 to_TO help_VVI a_AT1 company_NN1 ._. 
</s>
<s>
The_AT consumer_NN1 may_VM also_RR want_VVI to_TO help_VVI other_JJ consumers_NN2 ._. 
</s>
<s>
This_DD1 motive_NN1 is_VBZ closely_RR related_VVN to_TO concern_VVI for_IF other_JJ consumers_NN2 ,_, discussed_VVN above_RL ._. 
</s>
<s>
The_AT main_JJ difference_NN1 between_II the_AT two_MC motives_NN2 is_VBZ that_CST in_II helping_VVG other_JJ consumers_NN2 ,_, the_AT individual_NN1 is_VBZ participating_VVG in_II eWOM_NN1 out_II21 of_II22 entirely_RR selfless_JJ motives_NN2 ._. 
</s>
<s>
When_CS participating_VVG in_II eWOM_NN1 out_II21 of_II22 concern_NN1 for_IF others_NN2 ,_, the_AT individual_NN1 may_VM have_VHI some_DD selfish_JJ motives_NN2 (_( Hennig-Thurau_NP1 2004_MC )_) ._. 
</s>
<s>
3_MC ._. 
</s>
<s>
Method_NN1 This_DD1 section_NN1 describes_VVZ the_AT sampling_NN1 and_CC analytical_JJ methods_NN2 that_CST were_VBDR employed_VVN in_II the_AT study_NN1 ._. 
</s>
<s>
3.1_MC ._. 
</s>
<s>
Sample_VV0 This_DD1 study_NN1 will_VM deploy_VVI purposeful_JJ sampling_NN1 ,_, as_CSA is_VBZ the_AT case_NN1 in_II most_DAT qualitative_JJ studies_NN2 (_( Patton_NP1 2002:227_MC )_) ._. 
</s>
<s>
Furthermore_RR ,_, the_AT sampling_NN1 strategy_NN1 is_VBZ a_AT1 combination_NN1 of_IO intensity_NN1 and_CC criterion_NN1 sampling_NN1 ._. 
</s>
<s>
Since_CS the_AT aim_NN1 is_VBZ to_TO find_VVI a_AT1 unit_NN1 of_IO analysis_NN1 that_CST can_VM provide_VVI rich_JJ information_NN1 about_II his/her_APPGE motivations_NN2 for_IF eWOM_NN1 ,_, the_AT intensity_NN1 strategy_NN1 is_VBZ applicable_JJ ._. 
</s>
<s>
In_II31 addition_II32 to_II33 finding_VVG an_AT1 information-rich_JJ interviewee_NN1 ,_, he/she_PPHS1 must_VM fulfil_VVI the_AT following_JJ criterion_NN1 ._. 
</s>
<s>
The_AT informant_NN1 must_VM be_VBI an_AT1 active_JJ user_NN1 of_IO social_JJ media_NN ,_, i.e._REX participator_NN1 in_II eWOM_NN1 ._. 
</s>
<s>
In_II the_AT study_NN1 an_AT1 active_JJ person_NN1 is_VBZ defined_VVN as_CSA someone_PN1 who_PNQS ,_, on_II a_AT1 daily_JJ basis_NN1 ,_, uses_VVZ several_DA2 social_JJ media_NN platforms_NN2 (_( e.g._REX Facebook_NP1 ,_, Twitter_VV0 ,_, LinkedIn_NP1 )_) ._. 
</s>
<s>
Furthermore_RR ,_, the_AT individual_NN1 uses_VVZ several_DA2 devices_NN2 (_( mobile_JJ phone_NN1 ,_, computer_NN1 )_) in_II his/her_APPGE social_JJ media_NN activities_NN2 ._. 
</s>
<s>
The_AT criterion_NN1 is_VBZ based_VVN on_II the_AT notion_NN1 that_CST a_AT1 non-participator_NN1 in_II eWOM_NN1 will_VM not_XX be_VBI able_JK to_TO provide_VVI information_NN1 about_II why_RRQ he/she_PPHS1 participates_VVZ in_II eWOM._NNU 3.2_MC ._. 
</s>
<s>
Data_NN collection_NN1 The_AT data_NN was_VBDZ collected_VVN by_II an_AT1 in-depth_JJ interview_NN1 ._. 
</s>
<s>
The_AT informant_NN1 is_VBZ a_AT1 23-year-old_JJ male_NN1 ,_, who_PNQS is_VBZ a_AT1 student_NN1 and_CC part-time_JJ employee_NN1 ._. 
</s>
<s>
He_PPHS1 fills_VVZ the_AT criterion_NN1 defined_VVD above_RL :_: he_PPHS1 is_VBZ an_AT1 active_JJ user_NN1 of_IO social_JJ media_NN ,_, and_CC he_PPHS1 participates_VVZ in_II eWOM_NN1 using_VVG several_DA2 devices_NN2 ._. 
</s>
<s>
The_AT interview_NN1 was_VBDZ conducted_VVN on_II Thursday_NPD1 ,_, the_AT 23rdFebruary_FO ,_, 2011_MC ._. 
</s>
<s>
The_AT interview_NN1 lasted_VVD from_II 21:01_MC to_II 22:04_MC ._. 
</s>
<s>
The_AT method_NN1 for_IF data_NN collection_NN1 was_VBDZ the_AT general_JJ interview-guide-approach_NN1 (_( Patton_NP1 2002_MC )_) ._. 
</s>
<s>
The_AT approach_NN1 has_VHZ a_AT1 set_NN1 of_IO predetermined_JJ questions_NN2 ,_, which_DDQ are_VBR formulated_VVN according_II21 to_II22 the_AT research_NN1 area_NN1 ._. 
</s>
<s>
The_AT guide_NN1 provides_VVZ topics_NN2 or_CC areas_NN2 within_II which_DDQ the_AT interviewer_NN1 can_VM (_( )_) explore_VV0 ,_, probe_NN1 and_CC ask_VV0 questions_NN2 that_CST will_VM illuminate_VVI that_DD1 particular_JJ subject_NN1 (_( Patton_NP1 2002:342_MC )_) ._. 
</s>
<s>
The_AT interviewer_NN1 can_VM ask_VVI ad-hoc_JJ questions_NN2 ,_, engage_VV0 in_II conversation_NN1 ,_, and_CC formulate_VV0 questions_NN2 spontaneously_RR ._. 
</s>
<s>
The_AT focus_NN1 does_VDZ ,_, however_RR ,_, need_VVI to_TO stay_VVI in_II the_AT predetermined_JJ subject/area_NN1 ._. 
</s>
<s>
The_AT interview_NN1 was_VBDZ recorded_VVN and_CC transcribed_VVN ._. 
</s>
<s>
Patton_NP1 (_( 2002:381-382_MCMC )_) and_CC Silverman_NP1 (_( 2006:113_MC )_) describe_VV0 recording_VVG interviews_NN2 as_CSA essential_JJ in_II gathering_VVG interview_NN1 data_NN ._. 
</s>
<s>
The_AT interview_NN1 was_VBDZ conducted_VVN in_II Finnish_JJ ,_, which_DDQ is_VBZ the_AT maternal_JJ language_NN1 of_IO the_AT interviewee._NNU 3.3_MC ._. 
</s>
<s>
Analysis_NN1 There_EX are_VBR five_MC clear_JJ stages_NN2 that_CST can_VM be_VBI defined_VVN in_II the_AT analytical_JJ process_NN1 of_IO this_DD1 study_NN1 ._. 
</s>
<s>
(_( I_ZZ1 )_) The_AT interview_NN1 guide_NN1 was_VBDZ formulated_VVN according_II21 to_II22 the_AT theoretical_JJ framework_NN1 of_IO the_AT research_NN1 area_NN1 ._. 
</s>
<s>
To_TO do_VDI so_RR ,_, some_DD initial_JJ analysis_NN1 was_VBDZ required_VVN ._. 
</s>
<s>
(_( II_MC )_) The_AT interview_NN1 was_VBDZ conducted_VVN ._. 
</s>
<s>
According_II21 to_II22 Belk_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 1998_MC )_) ,_, the_AT analysis_NN1 of_IO the_AT data_NN begins_VVZ already_RR at_II the_AT interview_NN1 situation_NN1 ._. 
</s>
<s>
(_( III_MC )_) The_AT researcher_NN1 transcribed_VVD the_AT recorded_JJ interview.During_NNU the_AT transcription_NN1 process_NN1 ,_, the_AT researcher_NN1 conducted_VVD some_DD initial_JJ analysis_NN1 ._. 
</s>
<s>
(_( IV_MC )_) The_AT interview_NN1 was_VBDZ read_VVN and_CC categorized_VVN by_II codes_NN2 that_CST were_VBDR defined_VVN inductively_RR ,_, in_II31 accordance_II32 with_II33 the_AT vocabulary_NN1 used_VVN by_II the_AT interviewee_NN1 ._. 
</s>
<s>
(_( V_ZZ1 )_) The_AT interview_NN1 was_VBDZ re-read_VVN twice_RR to_TO be_VBI able_JK to_TO analyse_VVI it_PPH1 and_CC build_VVI abstraction_NN1 (_( Spiggle1994_FO )_) ._. 
</s>
<s>
The_AT researcher_NN1 constantly_RR iterated_VVN between_II the_AT steps_NN2 ,_, which_DDQ were_VBDR not_XX carried_VVN out_RP in_II sequential_JJ order_NN1 ._. 
</s>
<s>
There_EX was_VBDZ a_AT1 constant_JJ dialogue_NN1 between_II analysis_NN1 ,_, data_NN recording_VVG ,_, and_CC theory_NN1 building_NN1 ._. 
</s>
<s>
3.3.1_MC ._. 
</s>
<s>
Categorization_NN1 &;_NULL Abstraction_NN1 Categorization_NN1 refers_VVZ to_II classifying_VVG and/or_CC labeling_VVG units_NN2 of_IO data_NN ._. 
</s>
<s>
In_II qualitative_JJ research_NN1 ,_, categorization_NN1 is_VBZ done_VDN by_II coding_VVG the_AT data_NN ._. 
</s>
<s>
The_AT idea_NN1 is_VBZ to_TO categorize_VVI a_AT1 unit_NN1 of_IO data_NN as_II part_NN1 of_IO a_AT1 more_RGR general_JJ phenomenon_NN1 ._. 
</s>
<s>
Categorization_NP1 (_( coding_NN1 )_) can_VM be_VBI done_VDN deductively_RR or_CC inductively_RR ._. 
</s>
<s>
The_AT prior_RR refers_VVZ to_II coding_VVG the_AT data_NN according_II21 to_II22 a_JJ21 priori_JJ22 contexts_NN2 (_( e.g._REX theoretical_JJ framework_NN1 )_) ,_, and_CC the_AT latter_DA to_II identifying_VVG (_( )_) emerging_JJ categories_NN2 from_II the_AT data_NN (_( Spiggle_NP1 1994_MC ._. )_) 
</s>
<s>
In_II this_DD1 study_NN1 ,_, the_AT data_NN were_VBDR categorized_VVN inductively_RR ._. 
</s>
<s>
The_AT codes_NN2 emerged_VVD from_II reviewing_VVG the_AT interview_NN1 transcripts_NN2 ._. 
</s>
<s>
The_AT codes_NN2 weredefined_VVD from_II the_AT interviewees_NN2 vocabulary_NN1 and_CC translated_VVN into_II English_NN1 ._. 
</s>
<s>
Abstraction_NN1 builds_VVZ on_II categorization_NN1 ._. 
</s>
<s>
Abstraction_NN1 is_VBZ about_II finding_VVG more_RGR general_JJ constructs_NN2 under_II which_DDQ the_AT categories_NN2 (_( codes_NN2 )_) can_VM be_VBI sorted_VVN ._. 
</s>
<s>
Abstraction_NN1 takes_VVZ categorization_NN1 to_II the_AT next_MD level_NN1 by_II identifying_VVG a_AT1 few_DA2 general_JJ concepts_NN2 ._. 
</s>
<s>
Furthermore_RR ,_, at_II this_DD1 stage_NN1 the_AT data_NN is_VBZ re-organized_VVN according_II21 to_II22 the_AT constructs_NN2 analysis_NN1 is_VBZ no_RR21 longer_RR22 bound_VVN to_II the_AT temporal_JJ order_NN1 of_IO the_AT interviews_NN2 ._. 
</s>
<s>
Also_RR constructsare_VV0 defined_VVN inductively_RR or_CC deductively_RR ._. 
</s>
<s>
In_II this_DD1 study_NN1 ,_, the_AT categories_NN2 emerged_VVD from_II the_AT theoretical_JJ framework_NN1 ,_, in_II other_JJ words_NN2 ,_, inductively_RR ._. 
</s>
<s>
The_AT constructs_NN2 ,_, under_II which_DDQ the_AT various_JJ motives_NN2 can_VM be_VBI sorted_VVN ,_, are_VBR defined_VVN according_II21 to_II22 the_AT segments_NN2 described_VVN by_II Hennig-Thurau_NP1 (_( 2004_MC )_) :_: self-interest_NN1 ,_, multi-motive_JJ ,_, true_JJ altruism_NN1 ,_, and_CC consumer_NN1 advocacy_NN1 ._. 
</s>
<s>
4_MC ._. 
</s>
<s>
Data_NN The_AT respondent_NN1 identified_VVN twenty-five_MC different_JJ motives_NN2 for_IF him_PPHO1 participating_VVG in_II eWOM_NN1 ._. 
</s>
<s>
Table_NN1 2_MC summarizes_VVZ the_AT motives_NN2 found_VVN in_II the_AT interview_NN1 data_NN ._. 
</s>
<s>
Even_CS21 though_CS22 this_DD1 is_VBZ a_AT1 qualitative_JJ data_NN ,_, the_AT motives_NN2 were_VBDR analysed_VVN quantitatively_RR to_TO be_VBI able_JK to_TO compare_VVI findings_NN2 to_II those_DD2 of_IO Hennig-Thurau_NP1 (_( 2004_MC )_) ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) 5_MC ._. 
</s>
<s>
Analysis_NN1 In_II this_DD1 section_NN1 the_AT above_JJ results_NN2 are_VBR analysed_VVN according_II21 to_II22 the_AT four_MC segments_NN2 defined_VVN by_II Hennig-Thurau_NP1 (_( 2004_MC )_) ,_, described_VVN in_II section_NN1 3._MC 5.1_MC ._. 
</s>
<s>
Self-Interest_NN1 The_AT interviewee_NN1 described_VVD twelve_MC motives_NN2 ,_, which_DDQ originated_VVD from_II self-interest_NN1 ._. 
</s>
<s>
Interestingly_RR ,_, the_AT majority_NN1 (_( 44%_NNU )_) of_IO motives_NN2 to_TO participate_VVI in_II eWOM_NN1 were_VBDR selfish_JJ ._. 
</s>
<s>
This_DD1 is_VBZ in_II31 line_II32 with_II33 Hennig-Thuraus_NP1 (_( 2004_MC )_) findings_NN2 ,_, according_II21 to_II22 which_DDQ the_AT largest_JJT segment_NN1 of_IO consumers_NN2 participating_VVG in_II eWOM_NN1 is_VBZ the_AT self-interested_JJ helpers_NN2 representing_VVG 36%_NNU of_IO the_AT eWOM_NN1 participators._NNU 5.2_MC ._. 
</s>
<s>
Multiple-Motives_NN2 5.3_MC ._. 
</s>
<s>
Consumer_NN1 Advocacy_NN1 5.4_MC ._. 
</s>
<s>
True_JJ Altruism_NN1 Segments_NN2 according_II21 to_II22 the_AT different_JJ motives_NN2 -_- marketers_NN2 6_MC ._. 
</s>
<s>
Discussion_NN1 7_MC ._. 
</s>
<s>
Conclusions_NN2 
</s>
