<s>
Social_JJ media-_NN1 an_AT1 Angel_NN1 or_CC a_AT1 Terrorist_NN1 ?_? 
</s>
<s>
Introduction_NN1 I_PPIS1 plan_VV0 to_TO write_VVI my_APPGE end-of-term_JJ paper_NN1 on_II social_JJ media_NN ._. 
</s>
<s>
I_PPIS1 will_VM focus_VVI on_RP how_RGQ social_JJ media_NN has_VHZ evolved_VVN and_CC developed_VVN throughout_II the_AT years_NNT2 and_CC become_VV0 a_AT1 crucial_JJ part_NN1 of_IO everyday_JJ life_NN1 ._. 
</s>
<s>
The_AT aim_NN1 of_IO my_APPGE paper_NN1 is_VBZ to_TO find_VVI out_RP what_DDQ the_AT most_RGT important_JJ reasons_NN2 are_VBR for_IF one_PN1 to_TO use_VVI social_JJ media_NN ;_; what_DDQ one_PN1 sees_VVZ as_II the_AT most_RGT gratifying_JJ experience_NN1 of_IO using_VVG social_JJ media_NN ._. 
</s>
<s>
I_PPIS1 also_RR plan_VV0 to_TO discover_VVI some_DD of_IO the_AT negative_JJ outcomes_NN2 that_CST Facebook_NP1 can_VM convey_VVI and_CC the_AT risks_NN2 it_PPH1 can_VM bring_VVI to_II an_AT1 individual_NN1 ._. 
</s>
<s>
There_EX are_VBR many_DA2 different_JJ programs_NN2 one_PN1 can_VM use_VVI to_TO stay_VVI in_II31 touch_II32 with_II33 friends_NN2 ,_, increase_VV0 their_APPGE social_JJ life_NN1 ,_, and_CC share_NN1 information_NN1 with_IW coworkers_NN2 ._. 
</s>
<s>
Examples_NN2 of_IO these_DD2 different_JJ forums_NN2 of_IO social_JJ media_NN are_VBR :_: Twitter_VV0 ,_, Facebook_NP1 ,_, YouTube_NP1 ,_, Wikipedia_NP1 and_CC MySpace_NP1 ._. 
</s>
<s>
Facebook_NP1 became_VVD a_AT1 hit_NN1 about_II exactly_RR eight_MC years_NNT2 ago_RA ._. 
</s>
<s>
It_PPH1 was_VBDZ launched_VVN in_II the_AT United_NP1 States_NP1 ._. 
</s>
<s>
It_PPH1 did_VDD nt_XX become_VVI popular_JJ in_II Finland_NP1 until_II 2007_MC but_CCB now_RT has_VHZ become_VVN a_AT1 regular_JJ networking_NN1 site_NN1 for_IF almost_RR everyone_PN1 ._. 
</s>
<s>
As_II21 of_II22 January_NPM1 ,_, 2009_MC ,_, Facebook_NP1 was_VBDZ ranked_VVN as_II the_AT most_RGT preferred_JJ networking_NN1 site_NN1 according_II21 to_II22 the_AT website_NN1 compete.com_NNU ._. 
</s>
<s>
Because_II21 of_II22 Facebook_NP1 being_VBG the_AT most_RGT used_JJ social_JJ media_NN ,_, I_PPIS1 plan_VV0 to_TO focus_VVI my_APPGE study_NN1 on_II this_DD1 networking_NN1 site_NN1 above_II the_AT others_NN2 ._. 
</s>
<s>
What_DDQ social_JJ networks_NN2 are_VBR mostly_RR used_VVN and_CC why_RRQ ?_? 
</s>
<s>
The_AT consumer_NN1 has_VHZ an_AT1 increasing_JJ role_NN1 for_IF social_JJ media_NN through_II Twitter_NN1 ,_, Facebook_NP1 ,_, Youtube_NP1 ,_, MySpace_NP1 and_CC Wikipedia_NP1 ._. 
</s>
<s>
As_CSA consumers_NN2 are_VBR increasingly_RR performing_VVG activities_NN2 previously_RR controlled_VVN by_II companies_NN2 ,_, the_AT entire_JJ marketing_NN1 landscape_NN1 is_VBZ changing_VVG ._. 
</s>
<s>
Social_JJ media_NN ,_, such_II21 as_II22 social_JJ networking_NN1 sites_NN2 and_CC user-generated_JJ services_NN2 ,_, have_VH0 emerged_VVN into_II mass_JJ use_NN1 rather_RG recently_RR ,_, basically_RR from_II 2003_MC onward_RL (_( Boyd_NP1 &;_NULL Ellison_NP1 ,_, 2008_MC )_) ._. 
</s>
<s>
What_DDQ are_VBR the_AT drivers_NN2 of_IO this_DD1 rather_RG recent_JJ trend_NN1 of_IO socialization_NN1 through_II media_NN ?_? 
</s>
<s>
What_DDQ drives_VVZ the_AT desire_NN1 to_TO use_VVI social_JJ media_NN ?_? 
</s>
<s>
What_DDQ does_VDZ the_AT consumer_NN1 want_VVI from_II using_VVG social_JJ media_NN ?_? 
</s>
<s>
Marketing_NN1 is_VBZ a_AT1 two-way_JJ procedure_NN1 between_II the_AT customer_NN1 and_CC company_NN1 ._. 
</s>
<s>
Consumers_NN2 nowadays_RT have_VH0 the_AT power_NN1 over_II companies_NN2 when_CS interacting_VVG on_II the_AT web_NN1 because_CS consumers_NN2 react_VV0 to_II companies_NN2 online_RR branding_VVG and_CC marketing_NN1 ._. 
</s>
<s>
The_AT companies_NN2 have_VH0 to_TO react_VVI to_II customers_NN2 wishes_NN2 and_CC feedback_NN1 ._. 
</s>
<s>
When_CS using_VVG Facebook_NN1 for_REX21 example_REX22 ,_, banners_NN2 and_CC advertisements_NN2 are_VBR seen_VVN constantly_RR on_II the_AT sides_NN2 of_IO the_AT screen_NN1 ._. 
</s>
<s>
To_II a_AT1 certain_JJ extent_NN1 ,_, consumers_NN2 usually_RR like_II this_DD1 but_CCB where_RRQ is_VBZ the_AT boundary_NN1 on_II what_DDQ is_VBZ enough_RR ?_? 
</s>
<s>
Research_NN1 Problem_NN1 The_AT purpose_NN1 of_IO this_DD1 essay_NN1 is_VBZ to_TO find_VVI out_RP what_DDQ benefits_NN2 and_CC advantages_NN2 social_JJ media_NN brings_VVZ for_IF an_AT1 individual_NN1 ._. 
</s>
<s>
I_PPIS1 also_RR plan_VV0 to_TO research_VVI on_II what_DDQ negative_JJ aspects_NN2 and_CC risks_NN2 social_JJ media_NN conveys_VVZ for_IF the_AT society_NN1 and_CC an_AT1 individual_JJ in_RR21 particular_RR22 ._. 
</s>
<s>
How_RGQ important_JJ is_VBZ social_JJ media_NN for_IF every_AT1 individual_JJ and_CC how_RRQ has_VHZ the_AT importance_NN1 of_IO social_JJ media_NN changed_VVN for_IF the_AT interviewee_NN1 during_II the_AT past_JJ five_MC years_NNT2 ?_? 
</s>
<s>
How_RRQ has_VHZ social_JJ media_NN altered_VVD the_AT workplace_NN1 atmosphere_NN1 and_CC what_DDQ negative_JJ affects_NN2 and_CC security_NN1 risks_NN2 are_VBR brought_VVN forth_RR by_II the_AT increasing_JJ use_NN1 of_IO social_JJ media_NN ?_? 
</s>
<s>
What_DDQ role_NN1 does_VDZ the_AT consumer_NN1 have_VHI in_II social_JJ media_NN versus_II the_AT company_NN1 ?_? 
</s>
<s>
My_APPGE study_NN1 consists_VVZ of_IO four_MC parts_NN2 :_: theoretical_JJ background_NN1 ,_, method_NN1 of_IO research_NN1 ,_, empirical_JJ analysis_NN1 and_CC results_NN2 and_CC managerial_JJ implications_NN2 to_TO discuss_VVI the_AT results_NN2 ._. 
</s>
<s>
In_II the_AT theoretical_JJ framework_NN1 ,_, I_PPIS1 plan_VV0 to_TO discuss_VVI and_CC explain_VVI more_RRR in_II detail_NN1 what_DDQ the_AT concepts_NN2 of_IO Facebook_NP1 and_CC social_JJ media_NN are_VBR and_CC what_DDQ they_PPHS2 are_VBR used_VVN for_IF ._. 
</s>
<s>
Also_RR ,_, I_PPIS1 plan_VV0 to_TO explain_VVI why_RRQ the_AT use_NN1 of_IO social_JJ media_NN has_VHZ increased_VVN so_RG rapidly_RR ?_? 
</s>
<s>
Why_RRQ is_VBZ one_MC1 media_NN better_RRR than_CSN the_AT other_JJ one_PN1 ?_? 
</s>
<s>
The_AT method_NN1 of_IO research_NN1 used_VVN for_IF my_APPGE paper_NN1 will_VM be_VBI a_AT1 questionnaire_NN1 and_CC interview_NN1 ._. 
</s>
<s>
I_PPIS1 will_VM conclude_VVI my_APPGE paper_NN1 with_IW results_NN2 and_CC managerial_JJ implications_NN2 ._. 
</s>
<s>
How_RRQ has_VHZ the_AT role_NN1 of_IO the_AT company_NN1 as_II the_AT marketer_NN1 changed_VVN into_II the_AT role_NN1 of_IO the_AT marketer_NN1 being_VBG the_AT customer_NN1 ?_? 
</s>
<s>
The_AT control_NN1 of_IO information_NN1 has_VHZ shifted_VVN from_II marketers_NN2 to_II consumers_NN2 ,_, because_CS the_AT Internet_NN1 allows_VVZ consumers_NN2 to_TO find_VVI any_DD information_NN1 they_PPHS2 need_VV0 very_RG easily_RR (_( Weber_NP1 ,_, 2007_MC )_) ._. 
</s>
<s>
The_AT consumer_NN1 is_VBZ recently_RR seen_VVN to_TO be_VBI having_VHG the_AT bigger_JJR role_NN1 in_II contributing_VVG to_II social_JJ media_NN by_II marketing_NN1 content_NN1 ._. 
</s>
<s>
In_BCL21 order_BCL22 for_IF both_DB2 the_AT company_NN1 and_CC the_AT consumer_NN1 to_TO benefit_VVI from_II social_JJ media_NN ,_, companies_NN2 need_VV0 to_TO see_VVI social_JJ media_NN with_IW eyes_NN2 of_IO the_AT consumer_NN1 ._. 
</s>
<s>
Social_JJ media_NN sites_NN2 like_II Twitter_NN1 and_CC Facebook_NP1 are_VBR seen_VVN as_CSA useful_JJ tools_NN2 for_IF marketers_NN2 to_TO communicate_VVI ._. 
</s>
<s>
The_AT use_NN1 of_IO Facebook_NP1 and_CC other_JJ social_JJ media_NN at_II work_NN1 has_VHZ become_VVN so_RG popular_JJ that_CST some_DD companies_NN2 have_VH0 even_RR prohibited_VVN the_AT use_NN1 of_IO such_DA sites_NN2 at_II work_NN1 ._. 
</s>
<s>
Whether_CSW it_PPH1 involves_VVZ using_VVG employer_NN1 computers_NN2 to_TO check_VVI personal_JJ e-mail_NN1 and_CC social_JJ network_NN1 pro_NN1 ?_? les_FW or_CC sending_VVG text_NN1 messages_NN2 on_II employer_NN1 provided_CS communications_NN2 devices_NN2 ,_, employee_NN1 use_NN1 of_IO boundary-crossing_JJ technologies_NN2 in_II the_AT workplace_NN1 for_IF personal_JJ purposes_NN2 is_VBZ prevalent_JJ ._. 
</s>
<s>
Social_JJ media_NN ,_, in_RR21 particular_RR22 ,_, has_VHZ permeated_VVN modern_JJ culture_NN1 and_CC the_AT daily_JJ lives_NN2 of_IO the_AT incoming_JJ workforce._NNU (_( Sanchez_NP1 Abril_NP1 ,_, Levin_NP1 ,_, &;_NULL Del_NP1 Riego_NP1 ,_, 2012_MC )_) ._. 
</s>
<s>
The_AT use_NN1 of_IO these_DD2 sites_NN2 in_II both_DB2 everyday_JJ life_NN1 and_CC at_II work_NN1 derives_VVZ many_DA2 legal_JJ ,_, ethical_JJ and_CC business-related_JJ concerns_NN2 ._. 
</s>
<s>
Employer_NN1 intrusion_NN1 into_II an_AT1 employees_NN2 personal_JJ life_NN1 threatens_VVZ the_AT employees_NN2 freedom_NN1 ,_, dignity_NN1 ,_, and_CC privacyand_NN1 may_VM lead_VVI to_II discriminatory_JJ practices_NN2 ._. 
</s>
<s>
A_AT1 considerable_JJ body_NN1 of_IO business_NN1 research_NN1 indicates_VVZ that_DD1 employer_NN1 invasiveness_NN1 may_VM lead_VVI to_II higher_JJR levels_NN2 of_IO employee_NN1 stress_NN1 ,_, lower_JJR levels_NN2 of_IO productivity_NN1 ,_, and_CC worse_JJR employee_NN1 health_NN1 and_CC morale._NNU (_( Sanchez_NP1 Abril_NP1 ,_, Levin_NP1 ,_, &;_NULL Del_NP1 Riego_NP1 ,_, 2012_MC )_) ._. 
</s>
<s>
There_EX are_VBR many_DA2 other_JJ ways_NN2 than_CSN those_DD2 contributing_VVG to_TO work_VVI that_CST can_VM affect_VVI an_AT1 individual_JJ negatively_RR ._. 
</s>
<s>
There_EX are_VBR constantly_RR many_DA2 under_II aged_JJ signing_NN1 up_RP on_II Face_NN1 book_NN1 who_PNQS necessarily_RR do_VD0 not_XX understand_VVI the_AT risks_NN2 of_IO talking_VVG to_II strangers_NN2 ,_, giving_VVG out_RP personal_JJ information_NN1 etc_RA ._. 
</s>
<s>
I_PPIS1 recently_RR read_VV0 an_AT1 article_NN1 of_IO a_AT1 girl_NN1 being_VBG bullied_VVN on_II Facebook_NN1 which_DDQ led_VVD her_PPHO1 to_TO commit_VVI suicide_NN1 ,_, and_CC another_DD1 girl_NN1 being_VBG raped_VVN as_II a_AT1 consequence_NN1 of_IO her_PPHO1 updating_VVG her_APPGE status_NN1 saying_VVG where_RRQ she_PPHS1 was_VBDZ at_II a_AT1 certain_JJ time_NNT1 ._. 
</s>
<s>
These_DD2 kinds_NN2 of_IO things_NN2 should_VM never_RR happen_VVI ,_, and_CC they_PPHS2 most_RRT likely_JJ had_VHD been_VBN avoided_VVN without_IW Facebook_NP1 ._. 
</s>
<s>
Method_NN1 I_PPIS1 plan_VV0 to_TO interview_VVI about_RG 30_MC of_IO my_APPGE peers_NN2 ,_, and_CC about_RG 10_MC adults_NN2 (_( people_NN in_II full-time_JJ positions_NN2 )_) on_II their_APPGE usage_NN1 of_IO social_JJ media_NN I_PPIS1 plan_VV0 to_TO use_VVI qualitative_JJ methods_NN2 in_II deriving_VVG results_NN2 and_CC answers_NN2 ._. 
</s>
<s>
Qualitative_JJ in-depth_JJ interviews_NN2 and_CC a_AT1 questionnaire_NN1 ware_NN1 used_VMK to_TO gain_VVI information_NN1 about_II why_RRQ one_PN1 wants_VVZ to_TO use_VVI social_JJ media_NN ,_, and_CC if_CS one_PN1 recognizes_VVZ in_II his/her_APPGE life_NN1 any_DD negative_JJ aspects_NN2 of_IO social_JJ media_NN ._. 
</s>
<s>
My_APPGE sample_NN1 was_VBDZ be_VBI 40_MC people_NN ,_, of_IO whom_PNQO 30_MC were_VBDR my_APPGE peers_NN2 and_CC 10_MC adults_NN2 in_II full-time_JJ positions_NN2 ._. 
</s>
<s>
I_PPIS1 chose_VVD my_APPGE sample_NN1 randomly_RR by_II a_AT1 girl-boy-basis_NN1 ._. 
</s>
<s>
Analysis_NN1 and_CC results_VVZ The_AT answers_NN2 and_CC results_NN2 to_II my_APPGE interviews_NN2 and_CC questionnaires_NN2 were_VBDR somewhat_RR what_DDQ I_PPIS1 expected_VVD ._. 
</s>
<s>
Most_DAT people_NN blogged_VVD for_IF the_AT social_JJ experience_NN1 ,_, get_VV0 to_TO know_VVI knew_VVD people_NN ,_, share_VV0 their_APPGE thoughts_NN2 ,_, influence_VV0 other_JJ people_NN ,_, staying_VVG in_II31 touch_II32 with_II33 others_NN2 and_CC to_TO mingle_VVI ._. 
</s>
<s>
There_EX were_VBDR very_RG few_DA2 individuals_NN2 who_PNQS had_VHD ever_RR thought_VVN about_II the_AT negative_JJ outcomes_NN2 of_IO using_VVG social_JJ media_NN ._. 
</s>
<s>
Most_DAT of_IO the_AT ones_NN2 ,_, who_PNQS even_RR had_VHD acknowledged_VVN negative_JJ aspects_NN2 existed_VVD ,_, were_VBDR amongst_II the_AT 10_MC adults_NN2 interviewed_VVD ._. 
</s>
<s>
They_PPHS2 had_VHD thought_VVN about_II these_DD2 negative_JJ aspects_NN2 because_II21 of_II22 their_APPGE young_JJ children_NN2 signing_VVG up_RP on_II Facebook_NN1 for_REX21 example_REX22 ._. 
</s>
<s>
Conclusions_NN2 After_II the_AT rapid_JJ development_NN1 of_IO technology_NN1 ,_, I_PPIS1 sit_VV0 here_RL and_CC wonder_VV0 on_II how_RRQ our_APPGE grandmas_NN2 and_CC earlier_JJR generations_NN2 have_VH0 lived_VVN ?_? 
</s>
<s>
They_PPHS2 do_VD0 not_XX have_VHI a_AT1 single_JJ clue_NN1 on_II how_RRQ the_AT world_NN1 has_VHZ changed_VVN and_CC how_RRQ by_II a_AT1 few_DA2 clicks_NN2 ,_, you_PPY can_VM stay_VVI in_II31 touch_II32 with_II33 your_APPGE friend_NN1 in_II Africa_NP1 !_! 
</s>
<s>
The_AT relevance_NN1 of_IO my_APPGE study_NN1 in_RR21 particular_RR22 ,_, for_IF the_AT community_NN1 ,_, is_VBZ not_XX that_DD1 high_JJ since_CS this_DD1 subject_NN1 has_VHZ been_VBN written_VVN on_II a_AT1 million_NNO times_NNT2 ._. 
</s>
<s>
I_PPIS1 do_VD0 see_VVI it_PPH1 ,_, however_RR ,_, as_CSA an_AT1 interesting_JJ topic_NN1 to_TO write_VVI on_RP and_CC learn_VVI from_II ._. 
</s>
<s>
We_PPIS2 use_VV0 Facebook_NN1 every_AT1 day_NNT1 ,_, but_CCB do_VD0 we_PPIS2 really_RR know_VVI how_RRQ it_PPH1 evolved_VVD ,_, who_PNQS all_RR uses_VVZ it_PPH1 ,_, what_DDQ it_PPH1 can_VM bring_VVI forth_RR ;_; the_AT good_JJ and_CC the_AT bad_JJ ?_? 
</s>
<s>
I_PPIS1 can_VM also_RR see_VVI social_JJ media_NN as_II a_AT1 topic_NN1 being_VBG dwelled_VVN upon_II on_II its_APPGE positive_JJ effects_NN2 but_CCB I_PPIS1 havent_VV0 read_VV0 many_DA2 articles_NN2 on_II the_AT negative_JJ sides_NN2 and_CC the_AT turnbacks_NN2 that_CST social_JJ media_NN affects_VVZ people_NN with_IW ?_? 
</s>
<s>
I_PPIS1 think_VV0 most_DAT people_NN only_RR see_VV0 Facebook_NN1 as_II a_AT1 good_JJ form_NN1 of_IO media_NN ._. 
</s>
<s>
Do_VD0 they_PPHS2 ever_RR think_VVI about_II the_AT negative_JJ outcomes_NN2 that_CST Facebook_NP1 brings_VVZ ?_? 
</s>
<s>
Social_JJ media_NN has_VHZ become_VVN an_AT1 excellent_JJ tool_NN1 for_IF some_DD purposes_NN2 ,_, and_CC a_AT1 good_JJ device_NN1 for_IF social_JJ mingling_NN1 ,_, but_CCB we_PPIS2 should_VM always_RR remember_VVI to_TO be_VBI careful_JJ with_IW what_DDQ we_PPIS2 use_VV0 it_PPH1 for_IF and_CC what_DDQ kind_NN1 of_IO information_NN1 we_PPIS2 share_VV0 ._. 
</s>
<s>
Interview_NN1 design_NN1 All_DB my_APPGE interviews_NN2 took_VVD place_NN1 in_II Helsinki_NP1 ,_, Finland_NP1 during_II March_NPM1 2012_MC ._. 
</s>
<s>
There_EX were_VBDR 40_MC interviews_NN2 that_CST lasted_VVD about_RG 15_MC minutes_NNT2 each_DD1 ._. 
</s>
<s>
Most_DAT of_IO my_APPGE interviews_NN2 and_CC questionnaires_NN2 were_VBDR conducted_VVN at_II school_NN1 but_CCB some_DD were_VBDR conducted_VVN at_II the_AT interviewees_NN2 homes_NN2 ._. 
</s>
<s>
There_EX were_VBDR many_DA2 questions_NN2 in_II the_AT beginning_NN1 about_II general_JJ aspects_NN2 and_CC thoughts_NN2 on_II social_JJ media_NN ._. 
</s>
<s>
These_DD2 easier_JJR questions_NN2 were_VBDR followed_VVN by_II more_RGR in-depth_JJ questions_NN2 that_CST required_VVD one_PN1 to_TO think_VVI ._. 
</s>
<s>
An_AT1 interview_NN1 guide_NN1 with_IW predetermined_JJ topics_NN2 was_VBDZ used_VVN for_IF the_AT interviews_NN2 because_CS it_PPH1 gives_VVZ the_AT researcher_NN1 the_AT freedom_NN1 to_TO keep_VVI the_AT conversational_JJ style_NN1 while_CS interviewing_VVG without_IW losing_VVG focus_NN1 (_( Patton_NP1 ,_, 2002_MC )_) ._. 
</s>
