<s>
Exploring_VVG the_AT advantages_NN2 and_CC disadvantages_NN2 of_IO implementing_VVG the_AT Helsinki_NP1 metropolitan_JJ mass_JJ transportation_NN1 information_NN1 into_II Google_NP1 Maps_NN2 1_MC1 ._. 
</s>
<s>
Introduction_NN1 Background_NN1 regarding_II Google_NP1 ,_, Google_VV0 Maps_NN2 ,_, HSL_NP1 and_CC Reittiopas_NP2 Aim_NN1 of_IO the_AT study_NN1 Limitations_NN2 2_MC ._. 
</s>
<s>
Technical_JJ background_NN1 on_II Google_NP1 Maps_NN2 3_MC ._. 
</s>
<s>
Method_NN1 of_IO the_AT study_NN1 4_MC ._. 
</s>
<s>
Analysis_NN1 (_( pros_NN2 /_FO cons_VVZ on_II major_JJ factors_NN2 )_) Centralized_JJ database_NN1 Real-time_NN1 Information_NN1 Mobile_NP1 applications_NN2 5_MC ._. 
</s>
<s>
Conclusions_NN2 
</s>
