<s>
INTRODUCTION_NN1 The_AT theoretical_JJ tools_NN2 for_IF employee_NN1 work_NN1 motivation_NN1 that_CST are_VBR presented_VVN for_REX21 example_REX22 on_II leadership_NN1 books_NN2 seem_VV0 to_TO have_VHI remained_VVN the_AT same_DA for_IF decades_NNT2 ._. 
</s>
<s>
For_REX21 example_REX22 ,_, from_II the_AT theories_NN2 in_II Rollinson_NP1 (_( 2002_MC )_) ,_, the_AT newest_JJT theory_NN1 on_II motivation_NN1 content_NN1 is_VBZ from_II the_AT 1970s_MC2 ._. 
</s>
<s>
Motivation_NN1 is_VBZ still_RR important_JJ ;_; it_PPH1 drives_VVZ the_AT employees_NN2 behaviour_NN1 that_CST influences_VVZ their_APPGE performance_NN1 (_( Rollinson_NP1 ,_, 2002_MC )_) ._. 
</s>
<s>
In_II the_AT same_DA time_NNT1 ,_, the_AT business_NN1 world_NN1 is_VBZ welcoming_VVG a_AT1 new_JJ generation_NN1 of_IO employees_NN2 :_: the_AT Generation_NN1 Y_ZZ1 (_( GenY_NP1 )_) ._. 
</s>
<s>
The_AT years_NNT2 when_RRQ these_DD2 GenYs_NN2 are_VBR born_VVN vary_VV0 within_II the_AT literature_NN1 ,_, as_II31 well_II32 as_II33 the_AT terminology_NN1 used_VMK to_TO describe_VVI them_PPHO2 ._. 
</s>
<s>
For_REX21 example_REX22 Smola_NP1 and_CC Sutton_NP1 (_( 2002_MC )_) call_VV0 these_DD2 the_AT Millennials_NP1 ,_, born_VVN between_II 1979_MC and_CC 1994_MC ,_, and_CC again_RT Twenge_VV0 ,_, Campbell_NP1 ,_, Hoffman_NP1 and_CC Lance_NN1 (_( 2010_MC )_) name_VV0 them_PPHO2 Generation_NN1 Me_PPIO1 ,_, born_VVN between_II 1982_MC and_CC 1999_MC ._. 
</s>
<s>
What_DDQ they_PPHS2 all_DB have_VH0 in_RR21 common_RR22 is_VBZ that_CST the_AT Generation_NN1 Y_ZZ1 is_VBZ the_AT -_- recent_JJ demographic_JJ group_NN1 to_TO have_VHI entered_VVN higher_JJR education_NN1 and_CC the_AT world_NN1 of_IO work_NN1 (_( Shaw_NP1 and_CC Fairhurst_NP1 ,_, 2008_MC :_: 367_MC )_) ._. 
</s>
<s>
They_PPHS2 are_VBR seen_VVN an_AT1 important_JJ asset_NN1 due_II21 to_II22 their_APPGE skills_NN2 :_: high_JJ level_NN1 of_IO education_NN1 ,_, technological_JJ whit_NN1 ,_, and_CC productivity_NN1 (_( Herbison_NP1 and_CC Boseman_NP1 ,_, 2009_MC )_) ._. 
</s>
<s>
Research_NN1 Problem_NN1 Although_CS the_AT generation_NN1 studies_NN2 have_VH0 gained_VVN attention_NN1 within_II the_AT field_NN1 of_IO business_NN1 ,_, most_DAT of_IO the_AT studies_NN2 focus_VV0 on_II comparing_VVG work_NN1 values_NN2 and_CC generations_NN2 (_( e.g._REX Smola_NP1 and_CC Sutton_NP1 ,_, 2002_MC ;_; Twenge_NP1 et_RA21 al._RA22 ,_, 2008_MC )_) ._. 
</s>
<s>
However_RR ,_, the_AT studies_NN2 concerning_II the_AT GenY_NN1 is_VBZ said_VVN to_TO be_VBI scarce_JJ (_( Twenge_NP1 et_RA21 al._RA22 ,_, 2010_MC )_) ._. 
</s>
<s>
Taking_VVG into_II account_NN1 the_AT motivation_NN1 theories_NN2 ,_, which_DDQ are_VBR still_RR taught_VVN in_II schools_NN2 and_CC the_AT features_NN2 of_IO the_AT Generation_NN1 Y_ZZ1 ,_, the_AT fact_NN1 which_DDQ really_RR motivates_VVZ the_AT newest_JJT recruits_NN2 should_VM be_VBI studies_NN2 ._. 
</s>
<s>
For_REX21 instance_REX22 ,_, the_AT answer_NN1 is_VBZ not_XX as_RG simple_JJ as_CSA more_DAR pay_NN1 ,_, as_CSA the_AT GenY_NN1 employees_NN2 are_VBR said_VVN to_TO be_VBI looking_VVG more_RRR from_II their_APPGE work_NN1 than_CSN just_RR financial_JJ gains_NN2 (_( Ng_NP1 ,_, Schweitzer_NP1 and_CC Lyons_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
Aim_NN1 of_IO the_AT study_NN1 The_AT purpose_NN1 of_IO this_DD1 study_NN1 is_VBZ to_TO research_VVI the_AT current_JJ literature_NN1 on_II work_NN1 motivation_NN1 ,_, especially_RR with_IW the_AT Generation_NN1 Y_ZZ1 employees_NN2 ._. 
</s>
<s>
Thus_RR ,_, the_AT aim_NN1 of_IO the_AT study_NN1 is_VBZ to_TO examine_VVI what_DDQ has_VHZ been_VBN identified_VVN as_CSA motivators_NN2 for_IF employees_NN2 from_II the_AT Generation_NN1 Y._NP1 Delimitations_NP1 Due_II21 to_II22 the_AT time_NNT1 limitations_NN2 given_VVN to_II the_AT study_NN1 ,_, it_PPH1 will_VM be_VBI only_RR relying_VVG on_II secondary_JJ research_NN1 ._. 
</s>
<s>
This_DD1 means_VVZ ,_, that_CST the_AT results_NN2 only_RR reflect_VV0 the_AT existing_JJ literature_NN1 and_CC studies_NN2 within_II the_AT subject_NN1 field_NN1 ._. 
</s>
<s>
GENERATION_NN1 Y_ZZ1 WHO_NP1 THEY_PPHS2 ARE_VBR Before_II discussing_VVG the_AT theory_NN1 on_II motivation_NN1 and_CC analysing_VVG the_AT current_JJ literature_NN1 on_II Generation_NN1 Y_ZZ1 employees_NN2 motivation_NN1 ,_, it_PPH1 is_VBZ needed_VVN to_TO define_VVI what_DDQ is_VBZ meant_VVN by_II Generation_NN1 Y._NP1 This_DD1 chapter_NN1 focuses_VVZ on_II this_DD1 newest_JJT demographic_JJ group_NN1 to_TO enter_VVI the_AT working_NN1 life_NN1 (_( Shaw_NP1 and_CC Fairhurst_NP1 ,_, 2008_MC )_) :_: how_RRQ they_PPHS2 are_VBR described_VVN in_II the_AT literature_NN1 ._. 
</s>
<s>
Although_CS it_PPH1 is_VBZ known_VVN that_DD1 Generation_NN1 Y_ZZ1 is_VBZ the_AT newest_JJT generation_NN1 ,_, problematic_JJ is_VBZ that_CST there_EX can_VM be_VBI found_VVN multiple_JJ terms_NN2 and_CC birth_NN1 years_NNT2 for_IF them_PPHO2 :_: e.g._REX Gen-Y_NP1 born_VVN between_II 1978_MC and_CC 1999_MC (_( Herbison_NP1 and_CC Boseman_NP1 ,_, 2009_MC )_) or_CC 1982-2000_MCMC (_( Wong_NP1 ,_, Gardiner_NP1 ,_, Lang_NP1 and_CC Coulon_NP1 ,_, 2008_MC )_) ,_, Millenials_NP1 born_VVN between_II 1979_MC and_CC 1994_MC (_( Smola_NP1 and_CC Sutton_NP1 ,_, 2002_MC )_) ,_, and_CC Generation_NN1 Me_PPIO1 born_JJ between_II 1982_MC and_CC 1999_MC (_( Twenge_NP1 et_RA21 al._RA22 ,_, 2010_MC )_) ._. 
</s>
<s>
For_IF this_DD1 study_NN1 ,_, all_DB of_IO these_DD2 articles_NN2 will_VM be_VBI used_VVN ,_, and_CC thus_RR the_AT birth_NN1 years_NNT2 will_VM be_VBI from_II 1979_MC until_II 2000_MC ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, despite_II the_AT various_JJ terms_NN2 ,_, this_DD1 study_NN1 will_VM use_VVI the_AT term_NN1 Generation_NN1 Y_ZZ1 (_( Gen_NNB Y_NP1 )_) ._. 
</s>
<s>
The_AT current_JJ literature_NN1 has_VHZ a_AT1 wide_JJ list_NN1 of_IO adjectives_NN2 by_II which_DDQ the_AT newest_JJT group_NN1 is_VBZ discussed_VVN by_RP ;_; although_CS there_EX are_VBR some_DD positive_JJ and_CC negative_JJ ones_NN2 ,_, they_PPHS2 all_DB seem_VV0 to_TO reveal_VVI the_AT demanding_JJ nature_NN1 of_IO these_DD2 belonging_VVG to_II the_AT group_NN1 ._. 
</s>
<s>
The_AT most_RGT noted_JJ description_NN1 has_VHZ to_TO do_VDI with_IW technology_NN1 :_: the_AT Generation_NN1 Y_ZZ1 is_VBZ known_VVN to_TO have_VHI technological_JJ abilities_NN2 (_( Sujansky_NP1 and_CC Ferri-Reed_NP1 ,_, 2010_MC ;_; Martin_NP1 ,_, 2005_MC )_) as_CSA they_PPHS2 are_VBR called_VVN even_RR as_II an_AT1 electronic_JJ generation_NN1 (_( Herbison_NP1 and_CC Boseman_NP1 ,_, 2009_MC )_) ._. 
</s>
<s>
In_II relations_NN2 ,_, the_AT Gen_NNB Ys_NP1 are_VBR said_VVN to_TO be_VBI highly_RR educated_VVN (_( Martin_NP1 ,_, 2005_MC )_) and_CC even_RR claimed_VVN of_IO being_VBG the_AT most_RGT educated_JJ from_II all_DB the_AT generation_NN1 within_II the_AT work_NN1 force_NN1 (_( Herbison_NP1 and_CC Boseman_NP1 ,_, 2009_MC )_) ._. 
</s>
<s>
However_RR ,_, this_DD1 does_VDZ not_XX mean_VVI that_CST the_AT Gen_NNB Y_NP1 employees_NN2 should_VM be_VBI left_VVN dealing_VVG with_IW their_APPGE work_NN1 on_II their_APPGE own_DA :_: Gen_NNB Ys_NP1 need_VV0 coaching_NN1 (_( Herbison_NP1 and_CC Boseman_NP1 ,_, 2009_MC )_) and_CC they_PPHS2 believe_VV0 in_II group_NN1 effort_NN1 (_( Sujansky_NP1 and_CC Ferri-Reed_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
However_RR ,_, Gen_NNB Y_NP1 employees_NN2 are_VBR claimed_VVN to_TO have_VHI with_IW low_JJ organisational_JJ commitment_NN1 (_( Martin_NP1 ,_, 2005_MC )_) ,_, which_DDQ would_VM mean_VVI that_CST their_APPGE turnover_NN1 rate_NN1 is_VBZ rather_RG high_JJ ._. 
</s>
<s>
Thus_RR ,_, it_PPH1 is_VBZ important_JJ to_TO understand_VVI these_DD2 newest_JJT recruits_NN2 as_CSA regardless_RR of_IO their_APPGE high_JJ demand_NN1 level_NN1 ,_, Gen_NNB Y_NP1 employees_NN2 are_VBR productive_JJ for_IF the_AT organisation_NN1 due_II21 to_II22 their_APPGE high_JJ level_NN1 of_IO work_NN1 performance_NN1 (_( Herbison_NP1 and_CC Boseman_NP1 ,_, 2009_MC ;_; Martin_NP1 ,_, 2005_MC )_) ._. 
</s>
<s>
WORK_VV0 MOTIVATION_NN1 Essentially_RR ,_, motivation_NN1 has_VHZ long_RR been_VBN the_AT subject_NN1 of_IO interest_NN1 among_II managers_NN2 and_CC practitioners_NN2 (_( Guha_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
Motivation_NN1 is_VBZ something_PN1 coming_VVG from_II within_II the_AT employee_NN1 focusing_VVG on_II the_AT needs_NN2 and_CC expectations_NN2 of_IO a_AT1 person_NN1 ,_, and_CC ultimately_RR defining_VVG the_AT direction_NN1 ,_, intensity_NN1 and_CC persistence_NN1 of_IO their_APPGE behaviour_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ described_VVN to_TO be_VBI invisible_JJ ;_; a_AT1 concept_NN1 ,_, which_DDQ the_AT managers_NN2 can_VM not_XX force_VVI on_II employees_NN2 ._. 
</s>
<s>
(_( Rollinson_NN1 ,_, 2002_MC )_) This_DD1 chapter_NN1 focuses_VVZ on_II the_AT general_JJ definition_NN1 of_IO the_AT term_NN1 by_II discussing_VVG briefly_RR the_AT two_MC viewpoints_NN2 of_IO motivation_NN1 :_: content_JJ and_CC process_VV0 theories_NN2 ._. 
</s>
<s>
In_II content_JJ theory_NN1 ,_, the_AT aim_NN1 is_VBZ to_TO satisfy_VVI the_AT needs_NN2 of_IO the_AT employees_NN2 ._. 
</s>
<s>
The_AT two_MC most_RGT known_JJ content_JJ theories_NN2 are_VBR Maslows_NN2 hierarchy_NN1 of_IO needs_NN2 and_CC Hertzbergs_NP2 two-factor_JJ theory_NN1 ._. 
</s>
<s>
Figure_VV0 1_MC1 presents_VVZ the_AT two-factor_JJ theory_NN1 :_: there_EX are_VBR certain_JJ hygiene_NN1 factors_NN2 that_CST are_VBR required_VVN to_TO prevent_VVI dissatisfaction_NN1 and_CC again_RT motivators_NN2 that_CST ensure_VVI satisfaction_NN1 ._. 
</s>
<s>
(_( Rollinson_NN1 ,_, 2002_MC )_) This_DD1 theory_NN1 is_VBZ an_AT1 example_NN1 on_II the_AT current_JJ literature_NN1 and_CC what_DDQ is_VBZ seen_VVN as_CSA motivating_VVG for_IF employees_NN2 ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) If_CS content_JJ theory_NN1 focuses_VVZ on_II the_AT what_DDQ aspect_NN1 of_IO motivation_NN1 ,_, process_VV0 theory_NN1 is_VBZ more_RRR about_II the_AT how.The_NNU three_MC most_RGT known_JJ theories_NN2 are_VBR expectancy_NN1 ,_, equity_NN1 ,_, and_CC goal-setting_JJ theories_NN2 (_( Rollinson_NP1 ,_, 2002_MC )_) ._. 
</s>
<s>
This_DD1 study_NN1 will_VM focus_VVI more_RRR on_II the_AT content_JJ theories_NN2 due_II21 to_II22 the_AT time_NNT1 and_CC length_NN1 restrictions_NN2 ._. 
</s>
<s>
METHODOLOGY_NN1 The_AT aim_NN1 of_IO this_DD1 study_NN1 is_VBZ to_TO examine_VVI what_DDQ has_VHZ been_VBN identified_VVN as_CSA motivators_NN2 for_IF Generation_NN1 Y_ZZ1 employees_NN2 ._. 
</s>
<s>
The_AT study_NN1 is_VBZ exploratory_JJ by_II its_APPGE nature_NN1 ;_; I_PPIS1 will_VM search_VVI the_AT current_JJ literature_NN1 to_TO find_VVI more_DAR knowledge_NN1 on_II my_APPGE research_NN1 problem_NN1 (_( Saunders_NP1 ,_, Lewis_NP1 and_CC Thornhill_NP1 ,_, 2007_MC )_) ._. 
</s>
<s>
I_PPIS1 chose_VVD to_TO conduct_VVI the_AT research_NN1 based_VVN on_II secondary_JJ data_NN mainly_RR due_II21 to_II22 the_AT time_NNT1 and_CC financial_JJ restrictions_NN2 ;_; especially_RR the_AT ability_NN1 of_IO secondary_JJ data_NN to_TO provide_VVI information_NN1 fast_RR is_VBZ seen_VVN as_II an_AT1 advantage_NN1 of_IO secondary_JJ research_NN1 (_( Saunders_NP1 et_RA21 al._RA22 ,_, 2007_MC )_) ._. 
</s>
<s>
The_AT access_NN1 to_II the_AT data_NN was_VBDZ via_II the_AT Hanken_JJ database_NN1 ;_; I_PPIS1 searched_VVD for_IF relevant_JJ articles_NN2 from_II scholar_NN1 journal_NN1 through_II databases_NN2 in_II Nelli_NP1 ._. 
</s>
<s>
Although_CS the_AT database_NN1 is_VBZ rather_RG extensive_JJ ,_, it_PPH1 still_RR is_VBZ a_AT1 limitation_NN1 to_II the_AT study_NN1 as_CSA some_DD of_IO the_AT articles_NN2 can_VM not_XX be_VBI found_VVN in_RR21 full_RR22 text.As_NNU the_AT studys_NN2 primary_JJ target_NN1 is_VBZ Generation_NN1 Y_ZZ1 employees_NN2 born_VVN approximately_RR after_II 1979_MC I_PPIS1 set_VV0 a_AT1 specific_JJ timeline_NN1 for_IF the_AT acquired_JJ data_NN ._. 
</s>
<s>
I_PPIS1 chose_VVD mainly_RR articles_NN2 written_VVN after_II 2001_MC ,_, since_CS that_DD1 is_VBZ when_RRQ the_AT first_MD Generation_NN1 Y_ZZ1 employees_NN2 have_VH0 started_VVN to_TO emerge_VVI to_II the_AT work_NN1 life_NN1 ;_; the_AT researchers_NN2 seem_VV0 to_TO have_VHI become_VVN more_RGR interested_JJ in_II these_DD2 new_JJ generations_NN2 after_CS they_PPHS2 have_VH0 started_VVN working_VVG and_CC not_XX much_RR before_II that_DD1 ._. 
</s>
<s>
MOTIVATING_NP1 GENERATION_NN1 Y_ZZ1 EMPLOYEES_NN2 (_( NOT_XX FINISHED_VVN )_) As_II the_AT Generation_NN1 Y_ZZ1 has_VHZ become_VVN the_AT newest_JJT employees_NN2 ,_, it_PPH1 raises_VVZ a_AT1 challenge_NN1 to_II the_AT organisation_NN1 as_CSA especially_RR to_II managers_NN2 ._. 
</s>
<s>
Currently_RR there_EX are_VBR altogether_RR four_MC different_JJ demographic_JJ groups_NN2 working_VVG side_NN1 by_II side_NN1 a_AT1 situation_NN1 that_CST has_VHZ not_XX happened_VVN before_II (_( Shaw_NP1 and_CC Fairhurst_NP1 ,_, 2008_MC )_) ._. 
</s>
<s>
What_DDQ then_RT makes_VVZ the_AT Generation_NN1 Y_ZZ1 employees_NN2 differ_VV0 from_II its_APPGE predecessors_NN2 ?_? 
</s>
<s>
Although_CS the_AT rising_JJ interest_NN1 is_VBZ noted_VVN (_( e.g._REX Wong_NP1 et_RA21 al._RA22 ,_, 2008_MC )_) ,_, the_AT empirical_JJ research_NN1 conducted_VVN regarding_II Generation_NN1 Y_ZZ1 is_VBZ still_RR rather_RG scarce_JJ (_( Twenge_NP1 et_RA21 al._RA22 ,_, 2010_MC )_) ._. 
</s>
<s>
This_DD1 is_VBZ especially_RR true_JJ with_IW the_AT research_NN1 concerning_II the_AT differences_NN2 in_II motivation_NN1 ,_, which_DDQ has_VHZ been_VBN limited_VVN regarding_II the_AT working_JJ environment_NN1 (_( Wong_NP1 et_RA21 al._RA22 ,_, 2008_MC )_) ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, despite_II the_AT noted_JJ importance_NN1 of_IO the_AT demands_NN2 of_IO Generation_NN1 Y_ZZ1 among_II managers_NN2 ,_, only_RR little_JJ action_NN1 has_VHZ been_VBN made_VVN to_TO cater_VVI the_AT needs_NN2 of_IO the_AT new_JJ employee_NN1 group_NN1 (_( Herbison_NP1 and_CC Boseman_NP1 ,_, 2009_MC )_) ._. 
</s>
<s>
As_CSA motivation_NN1 theory_NN1 discusses_VVZ the_AT fulfilment_NN1 of_IO employee_NN1 needs_NN2 ,_, there_EX is_VBZ a_AT1 challenge_NN1 with_IW the_AT Generation_NN1 Y-ers_NN2 ;_; these_DD2 employees_NN2 are_VBR demanding_VVG quickness_NN1 and_CC quantity_NN1 from_II their_APPGE employers_NN2 when_CS it_PPH1 comes_VVZ to_II their_APPGE needs_NN2 (_( Ng_NP1 et_RA21 al._RA22 ,_, 2010_MC )_) ._. 
</s>
<s>
CONCLUSION_NN1 This_DD1 study_NN1 examined_VVD the_AT current_JJ literature_NN1 on_II work_NN1 motivation_NN1 concerning_II the_AT Generation_NN1 Y_ZZ1 employees_NN2 ,_, the_AT most_RGT latest_JJT demographic_JJ group_NN1 that_CST has_VHZ entered_VVN the_AT working_NN1 life_NN1 ._. 
</s>
<s>
The_AT aim_NN1 of_IO the_AT study_NN1 was_VBDZ to_TO find_VVI out_RP the_AT identified_JJ motivation_NN1 methods_NN2 to_II the_AT newest_JJT generation_NN1 ,_, which_DDQ is_VBZ described_VVN as_CSA technological_JJ and_CC demanding_VVG ._. 
</s>
