<s>
Influence_NN1 of_IO diversity_NN1 of_IO board_NN1 of_IO directors_NN2 to_II corporate_JJ :_: UPM_NP1 Case_NN1 1_MC1 ._. 
</s>
<s>
Introduction_NN1 Corporate_JJ governance_NN1 is_VBZ one_MC1 of_IO the_AT most_RGT important_JJ facets_NN2 that_CST determine_VV0 the_AT success_NN1 or_CC failure_NN1 of_IO any_DD organization_NN1 ,_, especially_RR under_II this_DD1 competitive_JJ business_NN1 environment_NN1 ._. 
</s>
<s>
Since_CS the_AT corporate_JJ governance_NN1 plays_VVZ a_AT1 significant_JJ role_NN1 in_II the_AT company_NN1 operation_NN1 ,_, the_AT capability_NN1 of_IO the_AT committee_NN1 which_DDQ takes_VVZ control_NN1 of_IO this_DD1 management_NN1 should_VM always_RR catch_VVI publics_NN2 eyes_NN2 and_CC keep_VVI enhancing_VVG under_II the_AT examination_NN1 ._. 
</s>
<s>
So_RR which_DDQ part_NN1 of_IO the_AT company_NN1 is_VBZ mainly_RR responsible_JJ for_IF the_AT corporate_JJ governance_NN1 and_CC affects_VVZ the_AT diversity_NN1 of_IO firm_NN1 ,_, or_CC to_II another_DD1 word_NN1 ,_, which_DDQ committee_NN1 guides_NN2 the_AT firm_JJ to_TO develop_VVI to_II the_AT right_JJ direction_NN1 with_IW crucial_JJ strategic_JJ mechanisms_NN2 ?_? 
</s>
<s>
The_AT answer_NN1 for_IF the_AT above_JJ questions_NN2 is_VBZ obvious_JJ :_: the_AT board_NN1 of_IO directors_NN2 ._. 
</s>
<s>
Board_NN1 is_VBZ the_AT group_NN1 and_CC committee_NN1 of_IO people_NN responsible_JJ for_IF supervising_VVG the_AT affairs_NN2 of_IO a_AT1 corporation_NN1 ._. 
</s>
<s>
Members_NN2 are_VBR selected_VVN by_II the_AT firms_NN2 stockholders_NN2 and_CC they_PPHS2 generally_RR set_VV0 broad_JJ corporate_JJ policy_NN1 rather_II21 than_II22 participating_VVG in_II the_AT daily_JJ managerial_JJ decisions_NN2 ._. 
</s>
<s>
(_( Morten_NP1 Huse_NP1 ,_, 2007_MC )_) They_PPHS2 normally_RR guide_VV0 the_AT floor_NN1 level_NN1 to_TO operate_VVI the_AT corporate_JJ on_II the_AT right_JJ way_NN1 ._. 
</s>
<s>
So_RR the_AT diversity_NN1 of_IO boards_NN2 of_IO directors_NN2 will_VM bring_VVI the_AT significant_JJ influence_NN1 to_II the_AT diversity_NN1 of_IO the_AT corporate_JJ ,_, such_II21 as_II22 the_AT structure_NN1 ,_, company_NN1 strategy_NN1 and_CC policy_NN1 and_RR31 so_RR32 on_RR33 ._. 
</s>
<s>
In_II this_DD1 study_NN1 ,_, the_AT author_NN1 will_VM investigate_VVI the_AT relationship_NN1 between_II the_AT diversity_NN1 of_IO corporate_JJ and_CC board_NN1 ._. 
</s>
<s>
The_AT UPM_NP1 ,_, which_DDQ is_VBZ a_AT1 bioenergy_NN1 manufacture_NN1 company_NN1 leads_VVZ integration_NN1 bio_NN1 and_CC forest_NN1 industries_NN2 in_II Finland_NP1 ,_, will_VM be_VBI the_AT main_JJ candidate_NN1 of_IO the_AT case_NN1 study_NN1 ._. 
</s>
<s>
The_AT saying_NN1 goes_VVZ ,_, one_PN1 should_VM learn_VVI from_II past_JJ mistakes_NN2 and_CC experiences_NN2 ._. 
</s>
<s>
This_DD1 can_VM certainly_RR be_VBI applicable_JJ to_TO UPM_VVI ._. 
</s>
<s>
It_PPH1 should_VM understand_VVI which_DDQ way_NN1 do_VD0 they_PPHS2 walk_VVI on_RP and_CC how_RRQ do_VDI they_PPHS2 remain_VVI advantages_NN2 as_II a_AT1 serious_JJ competitor_NN1 and_CC keep_VV0 away_II21 from_II22 global_JJ competition_NN1 ._. 
</s>
<s>
The_AT fundamental_JJ question_NN1 at_II UPM_NP1 today_RT is_VBZ :_: how_RRQ does_VDZ the_AT diversity_NN1 of_IO its_APPGE board_NN1 of_IO directors_NN2 perform_VV0 ,_, what_DDQ influence_VV0 does_VDZ the_AT diversity_NN1 bring_VVI to_II the_AT operation_NN1 of_IO corporate_JJ ,_, and_CC what_DDQ future_JJ version_NN1 or_CC strategy_NN1 for_IF the_AT diversity_NN1 of_IO its_APPGE board_NN1 ._. 
</s>
<s>
These_DD2 The_AT intention_NN1 of_IO this_DD1 paper_NN1 is_VBZ therefore_RR to_TO build_VVI an_AT1 understanding_NN1 of_IO the_AT diversity_NN1 and_CC operation_NN1 of_IO UPMs_NP1 board_NN1 and_CC by_II dong_NN1 this_DD1 gets_VVZ a_AT1 deeper_JJR insight_NN1 to_II the_AT multi_JJ disciplinary_JJ nature_NN1 of_IO corporate_JJ governance_NN1 ._. 
</s>
<s>
The_AT diversity_NN1 of_IO board_NN1 of_IO directors_NN2 will_VM be_VBI approved_VVN from_II various_JJ perspectives_NN2 and_CC disciplines_NN2 in_II the_AT following_JJ order_NN1 :_: gender_NN1 ,_, nationality_NN1 and_CC age_NN1 ._. 
</s>
<s>
Each_DD1 discipline_NN1 has_VHZ its_APPGE set_NN1 of_IO concerns_NN2 and_CC influence_VV0 to_II corporate_JJ and_CC by_II trying_VVG to_TO understand_VVI the_AT issues_NN2 from_II different_JJ perspectives_NN2 ._. 
</s>
<s>
Finally_RR ,_, the_AT central_JJ issues_NN2 are_VBR presented_VVN in_II a_AT1 conclusion_NN1 ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO support_VVI the_AT UPM_JJ case_NN1 study_NN1 ,_, the_AT researcher_NN1 also_RR compares_VVZ the_AT Nokia_NP1 with_IW it_PPH1 together_RL through_II the_AT previous_JJ case_NN1 study_NN1 and_CC research_NN1 ._. 
</s>
<s>
This_DD1 will_VM be_VBI more_RGR clear_JJ and_CC easier_RRR to_TO see_VVI how_RRQ the_AT diversity_NN1 of_IO board_NN1 of_IO directors_NN2 affects_VVZ the_AT diversity_NN1 of_IO corporate_JJ ._. 
</s>
<s>
1.1_MC Basic_JJ background_NN1 1.1.1_MC Company_NN1 UPM-Kymmene_JJ Corporation_NN1 is_VBZ a_AT1 Finnish_JJ pulp_NN1 ,_, paper_NN1 and_CC timber_NN1 manufacturer_NN1 ._. 
</s>
<s>
UPM_NP1 was_VBDZ built_VVN by_II Repola_NP1 Ltd_JJ and_CC Kymmene_NP1 Corporation_NN1 and_CC its_APPGE subsidiary_JJ United_JJ Paper_NN1 Mills_NP1 Ltd_JJ in_II 1996_MC ._. 
</s>
<s>
Its_APPGE headquarter_NN1 is_VBZ located_VVN in_II Helsinki_NP1 ,_, Finland_NP1 ._. 
</s>
<s>
Until_CS 2012_MC ,_, there_EX are_VBR nine_MC board_NN1 directors_NN2 stand_VV0 for_IF the_AT UPM_NP1 ,_, which_DDQ Bjrn_NP1 Wahlroos_NP1 works_VVZ as_II the_AT chairman_NN1 and_CC Jussi_JJ Pesonen_NN1 is_VBZ voted_VVN as_II the_AT president_NN1 and_CC CEO_NN1 ._. 
</s>
<s>
The_AT company_NN1 employs_VVZ about_RG 24,000_MC people_NN around_II the_AT worldwide_JJ and_CC expands_VVZ its_APPGE production_NN1 plants_NN2 in_II 16_MC countries_NN2 ._. 
</s>
<s>
Among_II these_DD2 groups_NN2 ,_, the_AT EU_NP1 employees_NN2 occupy_VV0 80%_NNU while_CS Europe_NP1 indicates_VVZ 85%_NNU ._. 
</s>
<s>
UPM_NP1 is_VBZ the_AT worlds_NN2 leading_VVG producer_NN1 of_IO graphic_JJ papers_NN2 and_CC second-largest_JJT producer_NN1 of_IO self-adhesive_JJ label_NN1 materials_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ listed_VVN in_II the_AT NASDAQ_NP1 OMX_NP1 Helsinki_NP1 stock_NN1 exchange_NN1 ._. 
</s>
<s>
The_AT company_NN1 logo_NN1 ,_, the_AT griffin_NN1 ,_, was_VBDZ designed_VVN by_II Hugo_NP1 Simberg_NP1 in_II 1899_MC ._. 
</s>
<s>
The_AT reason_NN1 why_RRQ griffin_NN1 was_VBDZ chosen_VVN as_II the_AT company_NN1 logo_NN1 is_VBZ that_CST because_CS it_PPH1 represents_VVZ a_AT1 guardian_NN1 of_IO the_AT northern_JJ forests_NN2 ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) UPM_NP1 consists_VVZ of_IO six_MC independent_JJ business_NN1 areas_NN2 :_: Energy_NN1 ,_, Pulp_NN1 ,_, Forest_NN1 and_CC timber_NN1 ,_, Paper_NN1 ,_, Label_NN1 and_CC Plywood_NN1 ._. 
</s>
<s>
Fibre-and_CC biomass-based_JJ business_NN1 ,_, recyclable_JJ raw_JJ materials_NN2 and_CC products_NN2 are_VBR cornerstones_NN2 of_IO UPMs_NP1 business_NN1 ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) UPM_NP1 has_VHZ created_VVN the_AT biofore_RR term_VV0 to_TO describe_VVI new_JJ forest_NN1 industry_NN1 ._. 
</s>
<s>
Bio_NN1 stands_VVZ sustainable_JJ solutions_NN2 and_CC environmental_JJ performance_NN1 ._. 
</s>
<s>
Fore_RR stands_VVZ for_IF forest_NN1 and_CC the_AT companys_NN2 position_VV0 at_II the_AT forefront_NN1 of_IO the_AT development_NN1 ._. 
</s>
<s>
UPM_NP1 create_VV0 value_NN1 from_II renewable_JJ and_CC recyclable_JJ materials_NN2 by_II combining_VVG its_APPGE expertise_NN1 and_CC technologies_NN2 within_II fibre-based_NN1 ,_, energy-related_JJ and_CC engineered_JJ materials_NN2 business_NN1 ._. 
</s>
<s>
Furthermore_RR UPM_NP1 keep_VV0 looking_VVG for_IF new_JJ business_NN1 opportunities_NN2 in_II Grada_NP1 ,_, ProFi_NP1 ,_, Fibril_NP1 Cellulose_NP1 ,_, ForMi_NP1 ,_, BioVerno_NP1 and_CC Living_JJ area_NN1 ._. 
</s>
<s>
The_AT sales_NN of_IO UPM_NP1 exceed_VV0 10_MC billion_NNO euros_NN2 in_II 2011_MC ._. 
</s>
<s>
The_AT biggest_JJT markets_NN2 are_VBR Europe_NP1 which_DDQ occupy_VV0 69%_NNU market_NN1 share_NN1 in_II total_NN1 ._. 
</s>
<s>
And_CC the_AT Asia_NP1 market_NN1 is_VBZ 14%_NNU while_VV0 North_ND1 America_NP1 states_VVZ 11%_NNU ._. 
</s>
<s>
It_PPH1 indicates_VVZ that_CST in_II recent_JJ years_NNT2 ,_, UPM_NP1 keep_VV0 looking_VVG for_IF and_CC expanding_VVG broader_JJR overseas_JJ markets_NN2 ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) &lsqb;_( Figure_NN1 &rsqb;_) 1.1.2_MC Board_NN1 of_IO directors_NN2 There_EX are_VBR 9_MC members_NN2 in_II the_AT board_NN1 ,_, among_II which_DDQ are_VBR elected_VVN the_AT Chairman_NN1 and_CC the_AT Vice_JJ Chairman_NN1 ._. 
</s>
<s>
The_AT election_NN1 or_CC reelection_NN1 of_IO the_AT members_NN2 of_IO the_AT Board_NN1 is_VBZ proposed_VVN by_II the_AT Nomination_NN1 and_CC Corporate_JJ Governance_NN1 Committee_NN1 during_II the_AT Annual_JJ General_JJ Meeting_NN1 ._. 
</s>
<s>
Both_DB2 genders_NN2 shall_VM be_VBI represented_VVN in_II the_AT board_NN1 ._. 
</s>
<s>
Every_AT1 member_NN1 of_IO the_AT board_NN1 has_VHZ to_TO be_VBI independent_JJ ,_, except_CS the_AT CEO_NN1 of_IO UPM_NP1 ,_, which_DDQ is_VBZ a_AT1 requirement_NN1 applicable_JJ to_TO publicly_RR listed_JJ companies_NN2 in_II Finland_NP1 ._. 
</s>
<s>
He_PPHS1 also_RR has_VHZ to_TO be_VBI significant_JJ shareholder_NN1 ,_, in_BCL21 order_BCL22 to_TO be_VBI well_JJ representative_NN1 of_IO the_AT shareholders_NN2 interests_NN2 ._. 
</s>
<s>
UPM_NP1 chose_VVD to_TO elect_VVI only_RR qualified_JJ directors_NN2 ._. 
</s>
<s>
This_DD1 fact_NN1 seems_VVZ to_TO reflect_VVI the_AT resource-_JJ dependence_NN1 vision_NN1 of_IO UPM_NP1 ,_, according_II21 to_II22 which_DDQ directors_NN2 have_VH0 to_TO bring_VVI to_II the_AT company_NN1 some_DD resources_NN2 (_( financial_JJ ,_, expertise_NN1 ,_, networks_NN2 ,_, etc_RA ._. )_) ._. 
</s>
<s>
Some_DD directors_NN2 can_VM have_VHI functions_NN2 in_II other_JJ companies_NN2 only_RR if_CS they_PPHS2 manage_VV0 to_TO devote_VVI the_AT necessary_JJ time_NNT1 and_CC attention_NN1 to_TO UPM_VVI ._. 
</s>
<s>
In_II fact_NN1 ,_, all_DB members_NN2 are_VBR chairmen_NN2 or_CC CEO_NN1 of_IO another_DD1 company_NN1 ,_, which_DDQ can_VM contribute_VVI to_II the_AT network_NN1 and_CC the_AT knowledge_NN1 of_IO the_AT environment_NN1 ._. 
</s>
<s>
UPM-Kymmene_JJ Corporations_NN2 (_( UPM_NP1 )_) control_NN1 and_CC governance_NN1 seems_VVZ mostly_RR ensured_VVN by_II the_AT board_NN1 of_IO directors_NN2 of_IO the_AT company_NN1 considering_II the_AT roles_NN2 attributed_VVN by_II UPM_NP1 to_II the_AT board_NN1 ._. 
</s>
<s>
However_RR ,_, regarding_VVG the_AT following_JJ scheme_NN1 ,_, the_AT board_NN1 seems_VVZ to_TO have_VHI a_AT1 limited_JJ role_NN1 in_II the_AT strategy_NN1 formulation_NN1 ,_, but_CCB it_PPH1 is_VBZ more_RGR present_JJ for_IF the_AT strategy_NN1 evaluation_NN1 ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) 1.2_MC Problem_NN1 statement_NN1 From_II the_AT research_NN1 and_CC study_NN1 of_IO UPM_NP1 from_II its_APPGE business_NN1 and_CC board_NN1 management_NN1 versions_NN2 ,_, the_AT authors_NN2 aim_VV0 to_TO analyze_VVI their_APPGE diversity_NN1 of_IO UPM_NP1 board_NN1 ._. 
</s>
<s>
With_IW the_AT quick_JJ development_NN1 around_II the_AT worldwide_JJ and_CC overseas_JJ area_NN1 ,_, the_AT international_JJ and_CC foreign_JJ employees_NN2 will_VM join_VVI the_AT UPM_JJ group_NN1 and_CC contribute_VVI to_II its_APPGE future_JJ operation_NN1 ._. 
</s>
<s>
So_RR this_DD1 phenomenon_NN1 also_RR will_VM bring_VVI a_AT1 significant_JJ influence_NN1 to_II the_AT board_NN1 management_NN1 and_CC operation_NN1 under_II this_DD1 global_JJ trend_NN1 ._. 
</s>
<s>
Under_II the_AT same_DA global_JJ business_NN1 trend_NN1 ,_, why_RRQ Nokia_NP1 becomes_VVZ the_AT specific_JJ international_JJ corporate_JJ with_IW the_AT international_JJ and_CC various_JJ board_NN1 directors_NN2 team_NN1 ,_, while_CS the_AT UPM_NP1 remains_VVZ more_RGR local_JJ top-management_JJ group_NN1 ?_? 
</s>
<s>
How_RRQ this_DD1 phenomenon_NN1 brings_VVZ the_AT effect_NN1 to_II their_APPGE company_NN1 ?_? 
</s>
<s>
What_DDQ do_VD0 they_PPHS2 think_VVI of_IO the_AT diversity_NN1 of_IO board_NN1 ?_? 
</s>
<s>
So_RR the_AT authors_NN2 look_VV0 forward_RL to_TO study_VVI that_CST whether_CSW the_AT UPM_JJ board_NN1 has_VHZ realized_VVN this_DD1 diversity_NN1 problem_NN1 and_CC how_RRQ could_VM they_PPHS2 face_VVI to_II this_DD1 trend_NN1 which_DDQ will_VM be_VBI a_AT1 double-edged_JJ sword_NN1 to_II the_AT company_NN1 operation_NN1 ._. 
</s>
<s>
Is_VBZ there_EX any_DD possibility_NN1 that_CST the_AT Finnish_JJ local_JJ board_NN1 will_VM accept_VVI more_RGR foreign_JJ members_NN2 join_VV0 in_II the_AT group_NN1 ?_? 1.3_MC Scope_NN1 and_CC limitations_NN2 of_IO research_NN1 The_AT diversity_NN1 of_IO the_AT board_NN1 includes_VVZ many_DA2 various_JJ aspects_NN2 ,_, such_II21 as_II22 :_: gender_NN1 ,_, age_NN1 and_CC nationality_NN1 ._. 
</s>
<s>
So_RR the_AT most_RGT efficient_JJ way_NN1 to_TO find_VVI out_RP the_AT reality_NN1 is_VBZ that_CST the_AT author_NN1 need_NN1 to_TO interview_VVI with_IW the_AT directors_NN2 of_IO board_NN1 in_II UPM_NP1 face-to-face_JJ ._. 
</s>
<s>
This_DD1 maybe_RR means_VVZ that_CST it_PPH1 is_VBZ not_XX too_RG much_DA1 practical_JJ to_TO carry_VVI out_RP a_AT1 research_NN1 on_II the_AT whole_JJ field_NN1 of_IO board_NN1 ._. 
</s>
<s>
Because_CS obviously_RR the_AT top_JJ management_NN1 directors_NN2 are_VBR usually_RR busy_JJ so_CS21 that_CS22 maybe_RR have_VH0 no_AT time_NNT1 to_TO interview_VVI the_AT author_NN1 in_II some_DD specific_JJ place_NN1 at_II the_AT specific_JJ time_NNT1 ._. 
</s>
<s>
And_CC furthermore_RR ,_, to_TO protect_VVI UPM_NP1 ,_, it_PPH1 seems_VVZ that_CST not_XX everyone_PN1 will_VM tell_VVI the_AT true_JJ story_NN1 or_CC the_AT inside_JJ reality_NN1 about_II the_AT diversity_NN1 of_IO UPM_NP1 board_NN1 ._. 
</s>
<s>
As_II such_DA ,_, the_AT researcher_NN1 will_VM limit_VVI the_AT scope_NN1 of_IO this_DD1 research_NN1 to_TO enable_VVI her_PPHO1 concentrate_VV0 and_CC focus_VVI on_II a_AT1 particular_JJ issue_NN1 of_IO particular_JJ importance_NN1 to_II the_AT field_NN1 ._. 
</s>
<s>
1.4_MC Objective_NN1 of_IO research_NN1 The_AT author_NN1 will_VM be_VBI guided_VVN by_II one_MC1 major_JJ objective_NN1 throughout_II the_AT research_NN1 ._. 
</s>
<s>
The_AT major_JJ objective_NN1 of_IO the_AT research_NN1 will_VM be_VBI to_TO address_VVI the_AT nature_NN1 of_IO the_AT relationship_NN1 between_II the_AT diversity_NN1 of_IO corporate_JJ and_CC board_NN1 ._. 
</s>
<s>
The_AT research_NN1 aims_VVZ to_TO find_VVI out_RP why_RRQ the_AT diversity_NN1 of_IO the_AT board_NN1 will_VM influence_VVI the_AT diversity_NN1 of_IO company_NN1 ,_, how_RRQ could_VM it_PPH1 influence_VVI and_CC the_AT final_JJ results_NN2 it_PPH1 makes_VVZ ._. 
</s>
<s>
2_MC ._. 
</s>
<s>
Literature_NN1 review_NN1 Previous_JJ research_NN1 on_II diversity_NN1 typically_RR follows_VVZ two_MC general_JJ distinctions_NN2 :_: the_AT observable_JJ (_( demographic_JJ )_) and_CC the_AT non-observable_JJ (_( cognitive_JJ )_) ._. 
</s>
<s>
For_REX21 example_REX22 ,_, the_AT observable_JJ diversity_NN1 is_VBZ generally_RR gender_NN1 ,_, age_NN1 ,_, race_NN1 and_CC ethnicity_NN1 ,_, while_CS the_AT non-observable_JJ are_VBR knowledge_NN1 ,_, education_NN1 ,_, personality_NN1 characteristics_NN2 and_CC perception_NN1 (_( Maznevski_NP1 ,_, 1994_MC ;_; Milliken_NP1 and_CC Martins_NP2 ,_, 1996_MC ;_; Pelled_JJ ,_, et_RA21 al_RA22 ,_, 1996_MC )_) However_RR most_DAT research_NN1 on_II diversity_NN1 and_CC its_APPGE effects_NN2 on_II performance_NN1 focus_NN1 on_II observable_JJ or_CC demographic_JJ diversity_NN1 ._. 
</s>
<s>
Thus_RR the_AT author_NN1 defines_VVZ diversity_NN1 as_II the_AT representation_NN1 of_IO gender_NN1 ,_, age_NN1 and_CC ethnic_JJ differences_NN2 on_RL21 board_RL22 of_IO directors_NN2 ._. 
</s>
<s>
This_DD1 study_NN1 considers_VVZ the_AT diversity_NN1 as_CSA it_PPH1 directly_RR reflects_VVZ the_AT increasing_JJ numbers_NN2 of_IO women_NN2 ,_, Asian_JJ and_CC Black_JJ entering_VVG into_II the_AT management_NN1 labor_NN1 market_NN1 (_( Conyon_NP1 and_CC Mallin_NP1 ,_, 1997_MC )_) and_CC the_AT average_NN1 is_VBZ decreasing_VVG down_RP from_II 58_MC years_NNT2 old_JJ ._. 
</s>
<s>
There_EX is_VBZ research_NN1 that_CST suggests_VVZ that_DD1 diversity_NN1 is_VBZ increasing-especially_RR by_II gender_NN1 ._. 
</s>
<s>
Daily_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
(_( 1999_MC )_) concluded_VVD that_CST for_IF a_AT1 study_NN1 of_IO Fortune_NN1 500_MC firms_NN2 ,_, that_CST women_NN2 have_VH0 made_VVN significant_JJ progress_NN1 in_II31 terms_II32 of_II33 assuming_VVG seats_NN2 on_II boards_NN2 of_IO directors_NN2 ,_, but_CCB have_VH0 not_XX in_II31 terms_II32 of_II33 taking_VVG CEO_NN1 positions_NN2 ._. 
</s>
<s>
Bilimoria_NP1 (_( 2000_MC )_) reports_VVZ that_CST even_CS21 though_CS22 the_AT number_NN1 of_IO female_JJ board_NN1 members_NN2 is_VBZ increasing_VVG slightly_RR ,_, few_DA2 companies_NN2 actively_RR recruit_VV0 females_NN2 and_CC there_EX is_VBZ still_JJ sex_NN1 bias_NN1 ,_, stereotyping_NN1 and_CC tokenism_NN1 on_II boards_NN2 where_RRQ women_NN2 serve_VV0 ._. 
</s>
<s>
Mattis_NP1 (_( 2000_MC )_) concludes_VVZ that_CST women_NN2 board_VV0 members_NN2 are_VBR increasing_VVG in_II numbers_NN2 but_CCB the_AT changes_NN2 are_VBR small_JJ and_CC incremental_JJ ._. 
</s>
<s>
While_CS this_DD1 research_NN1 focuses_VVZ more_RRR on_II gender_NN1 rather_II21 than_II22 racial_JJ diversity_NN1 ,_, the_AT evidence_NN1 suggests_VVZ that_CST the_AT composition_NN1 of_IO boards_NN2 of_IO directors_NN2 in_II American_JJ corporations_NN2 is_VBZ beginning_VVG to_TO increasingly_RR reflect_VVI the_AT changes_NN2 in_II workforce_NN1 diversity_NN1 (_( Burke_NP1 ,_, 1995_MC )_) ._. 
</s>
<s>
3_MC ._. 
</s>
<s>
Research_NN1 Methodology_NN1 In_II the_AT research_NN1 ,_, the_AT qualitative_JJ analysis_NN1 and_CC quantitative_JJ analysis_NN1 approach_NN1 have_VH0 been_VBN used_VVN to_TO collect_VVI the_AT information_NN1 and_CC analyze_VVI the_AT data_NN ._. 
</s>
<s>
Among_II the_AT research_NN1 process_NN1 ,_, both_RR primary_JJ and_CC secondary_JJ data_NN are_VBR needed_VVN for_IF analysis_NN1 ,_, which_DDQ are_VBR gathered_VVN from_II various_JJ sources_NN2 to_TO address_VVI research_NN1 questions_NN2 and_CC finish_VVI the_AT project_NN1 ._. 
</s>
<s>
3.1_MC Methodology_NN1 Theory_NN1 Qualitative_JJ research_NN1 is_VBZ a_AT1 type_NN1 of_IO scientific_JJ research_NN1 approach_NN1 ._. 
</s>
<s>
It_PPH1 mainly_RR includes_VVZ following_VVG characteristics_NN2 ,_, seeking_VVG answers_NN2 to_II a_AT1 question_NN1 ,_, systematically_RR using_VVG a_AT1 predefined_JJ set_NN1 of_IO procedures_NN2 to_TO answer_VVI a_AT1 question_NN1 ,_, collecting_VVG evidence_NN1 and_CC information_NN1 and_CC indicating_VVG outcome_NN1 that_CST were_VBDR marked_VVN to_TO analyze_VVI in_II advance_NN1 ._. 
</s>
<s>
(_( Sharan_NP1 B_ZZ1 ,_, 2009_MC )_) There_EX are_VBR three_MC most_RGT common_JJ qualitative_JJ methods_NN2 which_DDQ are_VBR participant_NN1 observation_NN1 ,_, in-depth_JJ interviews_NN2 and_CC focus_VV0 group_NN1 ._. 
</s>
<s>
The_AT types_NN2 of_IO data_NN qualitative_JJ methodology_NN1 are_VBR field_NN1 notes_NN2 ,_, audio_NN1 /_FO video_NN1 recording_NN1 ,_, and_CC transcripts_NN2 ._. 
</s>
<s>
(_( fhi360.org_FO )_) Qualitative_JJ research_NN1 method_NN1 mainly_RR aims_VVZ at_II understanding_NN1 and_CC answers_VVZ primarily_RR to_II how_RRQ ._. 
</s>
<s>
Compared_VVN to_II the_AT qualitative_JJ research_NN1 method_NN1 ,_, quantitative_JJ research_NN1 aims_VVZ at_II explanation_NN1 and_CC answers_VVZ to_II why_RRQ ._. 
</s>
<s>
It_PPH1 focuses_VVZ more_RRR on_II the_AT collection_NN1 and_CC analysis_NN1 of_IO numerical_JJ data_NN and_CC statistics_NN with_IW questionnaires_NN2 and_CC etc_RA ._. 
</s>
<s>
The_AT observation_NN1 units_NN2 of_IO quantitative_JJ method_NN1 are_VBR group_NN1 ,_, institutions_NN2 ,_, texts_NN2 and_CC event_NN1 or_CC activity_NN1 ._. 
</s>
<s>
(_( Books_NN2 Llc_NP1 ,_, 2010_MC )_) The_AT basic_JJ differences_NN2 between_II quantitative_JJ and_CC qualitative_JJ research_NN1 methods_NN2 are_VBR as_CSA follows_VVZ :_: Analytical_JJ objectives_NN2 Types_NN2 of_IO questions_NN2 they_PPHS2 explore_VV0 Types_NN2 of_IO data_NN collection_NN1 instrument_NN1 and_CC methods_NN2 they_PPHS2 use_VV0 Forms_NN2 of_IO data_NN they_PPHS2 produce_VV0 Degree_NN1 of_IO flexibility_NN1 built_VVN into_II study_NN1 design_NN1 (_( fhi360.org_FO )_) &lsqb;_( Table_NN1 &rsqb;_) Referring_VVG to_II the_AT research_NN1 data_NN ,_, primary_JJ data_NN is_VBZ mainly_RR to_TO collect_VVI new_JJ data_NN specially_RR for_IF a_AT1 purpose_NN1 while_CS secondary_JJ data_NN is_VBZ the_AT data_NN and_CC source_NN1 have_VH0 been_VBN gathered_VVN for_IF some_DD previous_JJ other_JJ purpose_NN1 or_CC scientific_JJ study_NN1 ._. 
</s>
<s>
(_( Sharan_NP1 B_ZZ1 ,_, 2009_MC )_) 3.2_MC Overview_NN1 of_IO the_AT Empirical_JJ Research_NN1 In_II this_DD1 thesis_NN1 ,_, interview_NN1 is_VBZ chosen_VVN as_II an_AT1 approach_NN1 of_IO qualitative_JJ research_NN1 method_NN1 ._. 
</s>
<s>
Directors_NN2 of_IO board_NN1 from_II UPM_NP1 are_VBR invited_VVN to_TO attend_VVI the_AT interview_NN1 ._. 
</s>
<s>
The_AT chance_NN1 of_IO the_AT interview_NN1 with_IW the_AT top_JJ managers_NN2 of_IO UPM_NP1 is_VBZ really_RR precious_JJ ._. 
</s>
<s>
And_CC the_AT author_NN1 met_VVD one_MC1 of_IO the_AT directors_NN2 of_IO UPM_NP1 in_II one_MC1 guest_NN1 lecturer_NN1 in_II Hanken_JJ School_NN1 of_IO economics_NN1 ._. 
</s>
<s>
And_CC they_PPHS2 discussed_VVD with_IW the_AT manager_NN1 when_CS lecture_NN1 finished_VVN about_II whether_CSW they_PPHS2 could_VM interview_VVI the_AT directors_NN2 of_IO board_NN1 of_IO UPM_NP1 ._. 
</s>
<s>
And_CC fortunately_RR the_AT director_NN1 agreed_VVN and_CC he_PPHS1 also_RR promised_VVN that_CST he_PPHS1 will_VM invite_VVI some_DD more_DAR members_NN2 to_TO join_VVI in_II this_DD1 meeting_NN1 ._. 
</s>
<s>
Referring_VVG to_II the_AT quantitative_JJ method_NN1 ,_, the_AT primary_JJ data_NN and_CC information_NN1 are_VBR collected_VVN through_II interview_NN1 and_CC questionnaires_NN2 from_II the_AT directors_NN2 and_CC staff_NN of_IO UPM_NP1 ._. 
</s>
<s>
The_AT secondary_JJ data_NN is_VBZ collected_VVN from_II internet_NN1 resources_NN2 and_CC literature_NN1 ._. 
</s>
<s>
The_AT print-questionnaires_NN2 contain_VV0 about_RG 10_MC questions_NN2 and_CC all_DB the_AT questions_NN2 made_VVN for_IF research_NN1 are_VBR valid_JJ and_CC credible_JJ ._. 
</s>
<s>
The_AT authors_NN2 will_VM provide_VVI and_CC ask_VVI some_DD more_DAR flexible_JJ and_CC detailed_JJ questions_NN2 to_II the_AT board_NN1 members_NN2 to_TO explore_VVI the_AT deeper_JJR and_CC inside_JJ reality_NN1 ._. 
</s>
<s>
4_MC ._. 
</s>
<s>
Results_NN2 From_II the_AT interview_NN1 and_CC analysis_NN1 of_IO the_AT questionnaires_NN2 ,_, the_AT author_NN1 find_VV0 that_CST the_AT diversity_NN1 f_ZZ1 the_AT UPM_JJ board_NN1 does_VDZ not_XX perform_VVI obviously_RR and_CC actively_RR ._. 
</s>
<s>
The_AT composition_NN1 of_IO the_AT board_NN1 :_: (_( chairman_NN1 )_) Bjrn_NP1 Wahlroos_NP1 ,_, 60_MC years_NNT2 old_JJ ,_, Ph.D_NP1 ._. 
</s>
<s>
(_( Econ_NN1 ._. )_) ,_, 
</s>
<s>
Chairman_NN1 of_IO the_AT Board_NN1 of_IO Directors_NN2 of_IO Sampo_NP1 Plc._NN1 (_( vice_JJ chairman_NN1 )_) Berndt_NP1 Brunow_NP1 ,_, 62_MC years_NNT2 old_JJ ,_, B.Sc_NP1 ._. 
</s>
<s>
(_( Econ_NN1 ._. )_) ,_, 
</s>
<s>
Chairman_NN1 of_IO the_AT Board_NN1 of_IO Directors_NN2 of_IO Oy_UH Karl_NP1 Fazer_NP1 Ab_FO ._. 
</s>
<s>
Matti_NP1 Alahuhta_NP1 ,_, 60_MC years_NNT2 old_JJ ,_, D.Sc_NP1 ._. 
</s>
<s>
(_( Eng_NP1 ._. )_) ,_, 
</s>
<s>
President_NN1 and_CC CEO_NN1 of_IO KONE_NP1 Corporation_NN1 Karl_NP1 Grotenfelt_NP1 ,_, 68_MC years_NNT2 old_JJ ,_, LL.M._NP1 ,_, Chairman_NN1 of_IO the_AT Board_NN1 of_IO Directors_NN2 of_IO Famigro_NN1 Oy_UH Wendy_NP1 E._NP1 Lane_NNL1 ,_, 61_MC years_NNT2 old_JJ ,_, MBA_NN1 (_( Harvard_NP1 Graduate_NN1 School_NN1 of_IO Business_NN1 Administration_NN1 )_) ,_, Chairman_NN1 of_IO the_AT Board_NN1 of_IO Directors_NN2 of_IO Lane_NN1 Holdings_NN2 ,_, Inc_JJ ._. 
</s>
<s>
Jussi_NP1 Pesonen_NP1 ,_, 52_MC years_NNT2 old_JJ ,_, M.Sc_NP1 ._. 
</s>
<s>
(_( Eng_NP1 ._. )_) ,_, 
</s>
<s>
President_NN1 and_CC CEO_NN1 of_IO UPM-Kymmene_JJ Corporation_NN1 Ursula_NP1 Ranin_NP1 ,_, 49_MC years_NNT2 old_JJ ,_, LL.M._NP1 ,_, B.Sc_NP1 ._. 
</s>
<s>
(_( Econ._NP1 )_) ,_, member_NN1 of_IO the_AT Board_NN1 of_IO Directors_NN2 of_IO Finnair_NP1 Plc_NN1 ._. 
</s>
<s>
Veli-Matti_JJ Reinikkala_NP1 ,_, 55_MC years_NNT2 old_JJ ,_, eMBA_NN1 ,_, President_NN1 of_IO ABB_NP1 Process_NN1 Automation_NN1 Division_NN1 Kim_NP1 Wahl_NP1 ,_, 52_MC years_NNT2 old_JJ ,_, MBA_NN1 ,_, BA_NP1 ,_, Business_NN1 Economics_NN1 ,_, Owner_NN1 and_CC Chairman_NN1 of_IO the_AT Board_NN1 of_IO the_AT investment_NN1 firm_NN1 Stromstangen_NN1 AS_CSA (_( 1_MC1 )_) It_PPH1 indicates_VVZ that_CST the_AT average_JJ age_NN1 of_IO the_AT members_NN2 of_IO board_NN1 is_VBZ around_RG 55.7_MC years_NNT2 old_JJ ._. 
</s>
<s>
(_( 2_MC )_) Most_DAT of_IO them_PPHO2 are_VBR local_JJ Finnish_JJ and_CC only_RR two_MC of_IO the_AT directors_NN2 come_VV0 from_II Canada_NP1 and_CC USA._NP1 (_( 3_MC )_) Among_II the_AT 9_MC members_NN2 of_IO board_NN1 ,_, UPM_NP1 has_VHZ two_MC female_JJ directors_NN2 ._. 
</s>
<s>
5_MC ._. 
</s>
<s>
Conclusion_NN1 Though_CS with_IW some_DD limitations_NN2 ,_, this_DD1 study_NN1 has_VHZ contributed_VVN important_JJ information_NN1 relating_VVG to_II diversity_NN1 effects_NN2 on_II the_AT operation_NN1 of_IO corporate_JJ ._. 
</s>
<s>
Accordingly_RR ,_, this_DD1 research_NN1 has_VHZ significant_JJ theoretical_JJ ,_, practical_JJ and_CC empirical_JJ implications_NN2 ._. 
</s>
<s>
Under_II the_AT serious_JJ competition_NN1 around_II the_AT worldwide_JJ and_CC overseas_JJ business_NN1 ,_, UPM_NP1 should_VM seriously_RR consider_VVI the_AT potential_NN1 for_IF the_AT enhanced_JJ representation_NN1 and_CC perspective_NN1 diversity_NN1 might_VM create_VVI ._. 
</s>
<s>
The_AT diversity_NN1 of_IO board_NN1 of_IO directors_NN2 will_VM made_VVD great_JJ contributions_NN2 to_II the_AT diversity_NN1 of_IO UPM_NP1 ._. 
</s>
<s>
They_PPHS2 may_VM think_VVI about_RPK to_TO accept_VVI more_RGR foreign_JJ members_NN2 to_TO deal_VVI with_IW the_AT international_JJ trade_NN1 and_CC partner_NN1 relationship_NN1 ._. 
</s>
<s>
And_CC also_RR the_AT international_JJ group_NN1 will_VM broaden_VVI horizon_NN1 and_CC explore_VVI wider_JJR overseas_JJ marketing_NN1 ._. 
</s>
<s>
The_AT younger_JJR directors_NN2 also_RR can_VM provide_VVI the_AT fresh_JJ and_CC advanced_JJ ideas_NN2 and_CC strategy_NN1 to_II the_AT company_NN1 ._. 
</s>
<s>
All_DB of_IO above_JJ will_NN1 motive_NN1 and_CC promote_VV0 UPM_NP1 operate_VV0 on_II the_AT right_NN1 and_CC advanced_JJ position_NN1 compared_VVN to_II its_APPGE competitors_NN2 nowadays_RT ._. 
</s>
