<s>
Demographics_NN2 and_CC Buying_VVG Behaviour_NN1 of_IO E-commerce_JJ Customers_NN2 :_: A_AT1 Case_NN1 Study_NN1 1_MC1 INTRODUCTION_NN1 1.1_MC ._. 
</s>
<s>
Motivation_NN1 for_IF the_AT Term_NN1 Paper_NN1 The_AT e-commerce_JJ business_NN1 to_II consumer_NN1 market_NN1 has_VHZ been_VBN growing_VVG significantly_RR during_II the_AT last_MD years_NNT2 in_II Finland_NP1 ._. 
</s>
<s>
Across_II the_AT board_NN1 the_AT percentage_NN1 of_IO people_NN regularly_RR doing_VDG online_JJ shopping_NN1 has_VHZ been_VBN steadily_RR growing_VVG during_II the_AT last_MD years_NNT2 ._. 
</s>
<s>
The_AT available_JJ general_JJ statistics_NN over_II the_AT Internet_NN1 usage_NN1 of_IO the_AT population_NN1 also_RR shows_VVZ that_CST the_AT trend_NN1 is_VBZ for_IF both_RR older_JJR and_CC other_JJ community_NN1 groups_NN2 to_TO take_VVI part_NN1 in_II the_AT online_JJ experience_NN1 ._. 
</s>
<s>
(_( OSF_NP1 2011_MC )_) To_TO understand_VVI your_APPGE customers_NN2 is_VBZ a_AT1 key_JJ success_NN1 factor_NN1 when_CS running_VVG an_AT1 online_JJ retail_JJ business_NN1 ._. 
</s>
<s>
By_II having_VHG an_AT1 understanding_NN1 of_IO who_PNQS you_PPY customers_NN2 are_VBR and_CC what_DDQ influences_VVZ their_APPGE buying_NN1 behaviour_NN1 everything_PN1 from_II marketing_NN1 to_II stock_NN1 choices_NN2 can_VM be_VBI optimized_VVN in_BCL21 order_BCL22 to_TO achieve_VVI larger_JJR profit_NN1 margins_NN2 ._. 
</s>
<s>
Therefore_RR also_RR the_AT research_NN1 community_NN1 is_VBZ increasing_VVG its_APPGE interest_NN1 as_II the_AT e-commerce_JJ activity_NN1 is_VBZ increasing_VVG ._. 
</s>
<s>
This_DD1 term_NN1 paper_NN1 will_VM focus_VVI on_II explaining_VVG what_DDQ predicts_VVZ the_AT behaviour_NN1 of_IO the_AT e-_JJ commerce_NN1 customers_NN2 of_IO the_AT case_NN1 company_NN1 ._. 
</s>
<s>
When_CS combining_VVG this_DD1 knowledge_NN1 with_IW general_JJ theories_NN2 this_DD1 study_NN1 aims_VVZ to_TO be_VBI able_JK to_TO provide_VVI empirical_JJ evidence_NN1 for_IF their_APPGE applicability_NN1 in_II practice_NN1 ._. 
</s>
<s>
Furthermore_RR ,_, this_DD1 information_NN1 is_VBZ of_IO interest_NN1 for_IF the_AT case_NN1 company_NN1 and_CC thus_RR warrants_VVZ a_AT1 discussion_NN1 on_II how_RRQ to_TO utilize_VVI the_AT information_NN1 ._. 
</s>
<s>
The_AT paper_NN1 will_VM use_VVI a_AT1 unique_JJ data_NN set_VV0 containing_VVG detailed_JJ information_NN1 on_II the_AT visitors_NN2 to_II an_AT1 e-commerce_JJ website_NN1 ._. 
</s>
<s>
The_AT data_NN set_NN1 contains_VVZ both_RR information_NN1 on_II visitors_NN2 that_CST finished_VVD their_APPGE transaction_NN1 ,_, and_CC visitors_NN2 that_CST aborted_VVD their_APPGE checkout_NN1 process_NN1 ._. 
</s>
<s>
This_DD1 term_NN1 paper_NN1 may_VM therefore_RR also_RR shed_VVI some_DD light_NN1 on_II which_DDQ kind_NN1 of_IO people_NN abort_VV0 their_APPGE buying_NN1 decision._NNU 1.2_MC ._. 
</s>
<s>
Research_NN1 Question_NN1 Several_DA2 of_IO the_AT previous_JJ research_NN1 papers_NN2 done_VDN on_II demographics_NN2 and_CC e-commerce_JJ customer_NN1 behaviour_NN1 have_VH0 either_RR used_VVN the_AT same_DA background_NN1 material_NN1 ,_, or_CC used_JJ interviews_NN2 of_IO e-commerce_JJ users_NN2 as_CSA their_APPGE source_NN1 of_IO information_NN1 ._. 
</s>
<s>
As_CSA this_DD1 study_NN1 will_VM use_VVI a_AT1 unique_JJ data_NN set_VV0 gathered_VVN from_II a_AT1 running_JJ e-commerce_JJ business_NN1 the_AT study_NN1 will_VM be_VBI able_JK to_TO answer_VVI more_RGR statistically_RR how_RRQ the_AT visitors_NN2 are_VBR behaving_VVG and_CC whom_PNQO they_PPHS2 are_VBR ._. 
</s>
<s>
This_DD1 study_NN1 also_RR needs_VVZ to_TO develop_VVI a_AT1 novel_JJ model_NN1 for_IF determining_VVG the_AT demographics_NN1 from_II an_AT1 incomplete_JJ data_NN set_VV0 ._. 
</s>
<s>
Thus_RR this_DD1 study_NN1 aims_VVZ to_TO answer_VVI the_AT following_JJ main_JJ research_NN1 question_NN1 :_: How_RRQ can_VM the_AT available_JJ characteristics_NN2 explain_VV0 the_AT buying_NN1 behaviour_NN1 of_IO the_AT e-_JJ commerce_NN1 website_NN1 visitors_NN2 ?_? 1.3_MC ._. 
</s>
<s>
Limitations_NN2 The_AT data_NN is_VBZ already_RR gathered_VVN ,_, and_CC due_II21 to_II22 time_NNT1 constraints_NN2 the_AT researcher_NN1 will_VM not_XX be_VBI able_JK to_TO use_VVI qualitative_JJ methods_NN2 in_BCL21 order_BCL22 to_TO profile_VVI the_AT demographics_NN1 ._. 
</s>
<s>
Only_RR the_AT data_NN already_RR recorded_VVN by_II the_AT e-commerce_JJ system_NN1 of_IO the_AT case_NN1 company_NN1 will_VM be_VBI used._NNU 1.4_MC ._. 
</s>
<s>
Structure_NN1 of_IO the_AT Term_NN1 Paper_NN1 The_AT remainder_NN1 of_IO this_DD1 paper_NN1 is_VBZ structured_VVN as_CSA follows_VVZ ._. 
</s>
<s>
The_AT following_JJ chapter_NN1 presents_VVZ the_AT research_NN1 methodology_NN1 used_VVD ._. 
</s>
<s>
Next_MD ,_, the_AT chapter_NN1 reviewing_VVG previous_JJ literature_NN1 with_IW relevance_NN1 to_II the_AT research_NN1 question_NN1 follows_VVZ ._. 
</s>
<s>
Following_VVG the_AT literature_NN1 review_NN1 ,_, there_EX is_VBZ an_AT1 analysis_NN1 of_IO the_AT material_NN1 collected_VVN and_CC how_RRQ the_AT research_NN1 questions_NN2 could_VM be_VBI answered_VVN ._. 
</s>
<s>
Finally_RR ,_, there_EX is_VBZ a_AT1 chapter_NN1 with_IW concluding_JJ remarks_NN2 on_II the_AT research_NN1 questions._NNU 2_MC RESEARCH_NN1 METHODOLOGY_NN1 This_DD1 chapter_NN1 presents_VVZ the_AT research_NN1 methods_NN2 in_II this_DD1 study_NN1 ._. 
</s>
<s>
It_PPH1 walks_VVZ through_II the_AT literature_NN1 review_NN1 process_NN1 ,_, describes_VVZ the_AT case_NN1 study_NN1 methodology_NN1 chosen_VVN ,_, and_CC thereby_RR provides_VVZ a_AT1 basis_NN1 for_IF the_AT further_JJR analysis_NN1 ._. 
</s>
<s>
The_AT unit_NN1 of_IO analysis_NN1 in_II this_DD1 study_NN1 is_VBZ the_AT visitors_NN2 to_II the_AT e-commerce_JJ website_NN1 of_IO the_AT case_NN1 company_NN1 ._. 
</s>
<s>
Therefore_RR ,_, a_AT1 mainly_RR quantitative_JJ research_NN1 method_NN1 is_VBZ used_VVN ,_, but_CCB as_CSA the_AT study_NN1 is_VBZ done_VDN as_II a_AT1 specific_JJ case_NN1 the_AT aspects_NN2 of_IO a_AT1 single_JJ case_NN1 study_NN1 must_VM be_VBI taken_VVN into_II account_NN1 ._. 
</s>
<s>
The_AT empirical_JJ data_NN is_VBZ collected_VVN using_VVG the_AT e-commerce_JJ solution_NN1 provided_VVN by_II the_AT case_NN1 company._NNU 2.1_MC ._. 
</s>
<s>
Literature_NN1 Review_NN1 Process_NN1 According_II21 to_II22 Yin_NP1 (_( 2002_MC )_) in_II his_APPGE book_NN1 on_II case_NN1 studies_NN2 the_AT aim_NN1 of_IO a_AT1 literature_NN1 review_NN1 is_VBZ to_TO "_" help_VVI develop_VVI sharper_JJR and_CC more_RGR detailed_JJ questions_NN2 "_" ._. 
</s>
<s>
Thus_RR the_AT literature_NN1 review_NN1 has_VHZ been_VBN focusing_VVG on_II developing_VVG the_AT subject_NN1 matters_NN2 in_II such_DA a_AT1 way_NN1 that_CST it_PPH1 will_VM support_VVI the_AT empirical_JJ stage_NN1 in_II this_DD1 study_NN1 ._. 
</s>
<s>
When_CS an_AT1 interesting_JJ article_NN1 has_VHZ been_VBN found_VVN the_AT references_NN2 of_IO that_DD1 article_NN1 has_VHZ been_VBN used_VVN in_BCL21 order_BCL22 to_TO find_VVI out_RP how_RRQ the_AT original_JJ researcher_NN1 supported_VVD his_APPGE arguments_NN2 ._. 
</s>
<s>
Thereby_RR finding_VVG out_RP more_DAR relevant_JJ and_CC in-depth_JJ information_NN1 on_II the_AT subject_NN1 matter_NN1 ._. 
</s>
<s>
Furthermore_RR ,_, articles_NN2 citing_VVG the_AT identified_JJ interesting_JJ piece_NN1 of_IO research_NN1 were_VBDR investigated_VVN ._. 
</s>
<s>
As_CSA Webster_NP1 and_CC Watson_NP1 (_( 2002_MC )_) argue_VV0 that_CST you_PPY need_VV0 to_TO go_VVI both_RR forwards_RL and_CC backwards_RL from_II your_APPGE literature_NN1 sources_NN2 in_BCL21 order_BCL22 to_TO get_VVI at_II complete_JJ consensus_NN1 of_IO the_AT concepts_NN2 reviewed._NNU 2.2_MC ._. 
</s>
<s>
Single_JJ Case_NN1 Study_NN1 Method_NN1 This_DD1 study_NN1 uses_VVZ the_AT single_JJ case_NN1 study_NN1 method_NN1 since_CS it_PPH1 fulfils_VVZ the_AT criteria_NN2 posed_VVN by_II Yin_NP1 (_( 2002_MC )_) for_IF motivating_VVG a_AT1 case_NN1 study_NN1 ._. 
</s>
<s>
Yin_NP1 (_( 2002_MC )_) argues_VVZ that_DD1 case_NN1 studies_NN2 are_VBR primarily_RR aimed_VVN at_II solving_VVG problems_NN2 that_CST can_VM be_VBI formulated_VVN as_II how_RRQ and_CC why_RRQ questions_NN2 when_RRQ the_AT researcher_NN1 can_VM not_XX influence_VVI the_AT outcome_NN1 to_II a_AT1 large_JJ extent_NN1 and_CC the_AT focus_NN1 is_VBZ on_II a_AT1 real-life_JJ contemporary_JJ phenomena_NN2 (_( Yin_NP1 2002_MC )_) ._. 
</s>
<s>
Moreover_RR when_CS the_AT research_NN1 question_NN1 is_VBZ formulated_VVN as_II a_AT1 how_RRQ question_VV0 it_PPH1 automatically_RR leads_VVZ to_II a_AT1 more_RGR explanatory_JJ study_NN1 where_CS case_NN1 study_NN1 would_VM be_VBI preferred_VVN ._. 
</s>
<s>
According_II21 to_II22 Eisenhardt_NP1 (_( 1989_MC )_) and_CC Yin_NP1 (_( 2002_MC )_) a_AT1 case_NN1 study_NN1 can_VM contain_VVI any_DD mix_NN1 of_IO qualitative_JJ and_CC quantitative_JJ data_NN ._. 
</s>
<s>
Yin_NP1 (_( 2002_MC )_) presents_NN2 and_CC discusses_VVZ six_MC sources_NN2 of_IO evidence_NN1 ;_; documentation_NN1 ,_, archival_JJ records_NN2 ,_, interviews_NN2 ,_, direct_JJ observations_NN2 ,_, participant-_JJ observation_NN1 and_CC physical_JJ artefacts_NN2 ._. 
</s>
<s>
In_II this_DD1 study_NN1 the_AT documentation_NN1 provided_CS the_AT primary_JJ source_NN1 of_IO case_NN1 data_NN and_CC is_VBZ therefore_RR discussed_VVN in_II a_AT1 separate_JJ section_NN1 ._. 
</s>
<s>
Other_JJ sources_NN2 of_IO evidence_NN1 used_VVN are_VBR archival_JJ records_NN2 and_CC direct_JJ observations_NN2 ._. 
</s>
<s>
Using_VVG multiple_JJ data_NN collection_NN1 methods_NN2 will_VM help_VVI in_II making_VVG the_AT points_NN2 clearer_JJR and_CC more_RGR robust_JJ ._. 
</s>
<s>
Finally_RR ,_, it_PPH1 is_VBZ important_JJ that_CST a_AT1 reader_NN1 is_VBZ able_JK to_TO follow_VVI the_AT chain_NN1 of_IO the_AT research_NN1 ._. 
</s>
<s>
In_II practice_NN1 it_PPH1 means_VVZ that_CST you_PPY are_VBR able_JK to_TO go_VVI back_RP from_II the_AT conclusions_NN2 to_II the_AT original_JJ data_NN ._. 
</s>
<s>
The_AT chain_NN1 of_IO evidence_NN1 needs_VVZ to_TO be_VBI communicated_VVN clearly_RR in_BCL21 order_BCL22 to_TO raise_VVI the_AT validity_NN1 of_IO the_AT arguments_NN2 and_CC results_NN2 from_II the_AT study_NN1 ._. 
</s>
<s>
The_AT researcher_NN1 should_VM also_RR show_VVI that_CST he_PPHS1 has_VHZ made_VVN his_APPGE best_JJT to_TO collect_VVI all_DB relevant_JJ information._NNU 2.2.1_MC ._. 
</s>
<s>
Data_NN Collection_NN1 and_CC Statistical_JJ Analysis_NN1 As_II the_AT researcher_NN1 has_VHZ direct_JJ access_NN1 to_II the_AT e-commerce_JJ solution_NN1 of_IO the_AT case_NN1 company_NN1 ,_, the_AT data_NN will_VM be_VBI directly_RR extracted_VVN from_II their_APPGE database_NN1 ._. 
</s>
<s>
The_AT extracted_JJ data_NN will_VM then_RT be_VBI processed_VVN and_CC refined_JJ in_BCL21 order_BCL22 to_TO help_VVI the_AT final_JJ analysis_NN1 ._. 
</s>
<s>
Descriptive_JJ statistics_NN will_VM be_VBI presented_VVN of_IO the_AT collected_JJ data_NN ._. 
</s>
<s>
Furthermore_RR ,_, some_DD sort_NN1 of_IO multiple_JJ regression_NN1 analysis_NN1 will_VM be_VBI performed_VVN on_II the_AT data_NN set_VVN in_BCL21 order_BCL22 to_TO be_VBI able_JK to_TO present_VVI a_AT1 solution_NN1 to_II the_AT research_NN1 question_NN1 ._. 
</s>
<s>
For_IF analysing_VVG the_AT collected_JJ data_NN the_AT statistical_JJ program_NN1 Stata_NP1 is_VBZ used_VVN ._. 
</s>
<s>
The_AT program_NN1 has_VHZ good_JJ reputation_NN1 in_II academic_JJ research_NN1 and_CC provides_VVZ many_DA2 of_IO the_AT tools_NN2 needed_VVN for_IF generating_VVG proper_JJ and_CC clear_JJ presentation_NN1 of_IO the_AT results_NN2 ._. 
</s>
<s>
(_( Stata_NN1 2012_MC )_) 3_MC LITERATURE_NN1 REVIEW_VV0 This_DD1 chapter_NN1 presents_VVZ literature_NN1 with_IW relevance_NN1 to_II the_AT research_NN1 question_NN1 in_BCL21 order_BCL22 to_TO be_VBI able_JK to_TO perform_VVI a_AT1 more_RGR developed_JJ argumentation_NN1 in_II the_AT empirical_JJ part_NN1 ._. 
</s>
<s>
The_AT chapter_NN1 concludes_VVZ in_II a_AT1 synthesis_NN1 ,_, which_DDQ will_VM be_VBI used_VVN as_II a_AT1 starting_NN1 point_NN1 for_IF the_AT empirical_JJ analysis._NNU 3.1_MC ._. 
</s>
<s>
Overview_NN1 of_IO E-commerce_JJ Business_NN1 What_DDQ characterizes_VVZ the_AT e-commerce_JJ business_NN1 in_II Finland_NP1 is_VBZ currently_RR the_AT immense_JJ growth_NN1 that_CST it_PPH1 is_VBZ showing_VVG on_II all_DB fronts_NN2 ._. 
</s>
<s>
There_EX is_VBZ first_MD of_IO all_DB an_AT1 overall_JJ growth_NN1 of_IO online_JJ spending_NN1 among_II all_DB age_NN1 groups_NN2 ._. 
</s>
<s>
The_AT growth_NN1 is_VBZ also_RR explained_VVN by_II the_AT increasing_JJ number_NN1 of_IO online_JJ shops_NN2 in_II itself_PPX1 ,_, and_CC thereby_RR the_AT increase_NN1 in_II product_NN1 categories_NN2 available_JJ online_JJ ._. 
</s>
<s>
A_AT1 research_NN1 performed_VVN by_II TNS_NP1 Gallup_NP1 puts_VVZ the_AT size_NN1 of_IO online_JJ business_NN1 in_II Finland_NP1 to_II over_RG 10_MC billion_NNO euro_NN1 for_IF 2011_MC (_( Kaupan_NP1 liitto_NN1 2012_MC )_) ,_, while_CS showing_VVG a_AT1 10_MC %_NNU average_JJ growth_NN1 across_II all_DB sectors_NN2 ._. 
</s>
<s>
The_AT five_MC largest_JJT sectors_NN2 in_II Finland_NP1 ,_, according_II21 to_II22 their_APPGE research_NN1 are_VBR :_: travelling_NN1 ,_, motor_NN1 ,_, electronics_NN1 ,_, living_VVG and_CC energy_NN1 ,_, and_CC gambling_NN1 ._. 
</s>
<s>
The_AT product_NN1 retailing_NN1 stood_VVD for_IF 47_MC %_NNU of_IO the_AT total_JJ e-commerce_NN1 revenue._NNU 3.2_MC ._. 
</s>
<s>
Online_RR Buying_VVG Behaviour_NN1 The_AT most_RGT significant_JJ difference_NN1 when_CS comparing_VVG to_II a_AT1 traditional_JJ shopping_NN1 experience_NN1 is_VBZ that_CST in_II an_AT1 online_JJ environment_NN1 the_AT customer_NN1 is_VBZ more_RRR in_II control_NN1 of_IO which_DDQ choices_NN2 he_PPHS1 makes_VVZ in_BCL21 order_BCL22 to_TO find_VVI a_AT1 potential_JJ buy_NN1 ._. 
</s>
<s>
The_AT intent_NN1 might_VM even_RR be_VBI very_RG unclear_JJ from_II the_AT beginning_NN1 ,_, as_CSA when_CS browsing_VVG or_CC searching_VVG the_AT Internet_NN1 the_AT website_NN1 visitor_NN1 might_VM be_VBI influenced_VVN to_TO make_VVI a_AT1 buy_NN1 ._. 
</s>
<s>
Low_JJ conversion_NN1 rate_NN1 compared_VVN to_II traditional_JJ shops_NN2 ._. 
</s>
<s>
One_MC1 reason_NN1 might_VM be_VBI the_AT very_JJ low_JJ cost_NN1 for_IF the_AT website_NN1 visitor_NN1 to_II only_JJ browse_NN1 ,_, without_IW feeling_VVG pressure_NN1 from_II the_AT assistants_NN2 in_II the_AT shop_NN1 or_CC using_VVG energy_NN1 in_II his_APPGE activities_NN2 ._. 
</s>
<s>
You_PPY need_VV0 to_TO convert_VVI the_AT mindset_NN1 of_IO the_AT website_NN1 visitor_NN1 into_II buying_NN1 ._. 
</s>
<s>
What_DDQ their_APPGE objective_NN1 is_VBZ from_II the_AT start_NN1 is_VBZ very_RG hard_JJ to_TO deduce_VVI ._. 
</s>
<s>
Another_DD1 important_JJ attribute_NN1 is_VBZ that_CST your_APPGE website_NN1 needs_VVZ to_TO communicate_VVI trust_NN1 ._. 
</s>
<s>
An_AT1 e-commerce_JJ site_NN1 might_VM also_RR adopt_VVI a_AT1 value-added_JJ strategy_NN1 instead_II21 of_II22 price_NN1 competition_NN1 ._. 
</s>
<s>
(_( Chen_NP1 &;_NULL Dubinsky_NP1 2003_MC )_) 3.3_MC ._. 
</s>
<s>
Predicting_VVG E-commerce_JJ Behaviour_NN1 Direct_JJ access_NN1 to_II the_AT website_NN1 would_VM be_VBI more_RGR likely_JJ to_TO purchase_VVI than_CSN the_AT visitors_NN2 who_PNQS access_VV0 the_AT site_NN1 through_II transferring_VVG websites_NN2 (_( indirect_JJ visit_NN1 )_) (_( Park_NP1 2009_MC )_) ._. 
</s>
<s>
The_AT website_NN1 visitor_NN1 might_VM only_RR be_VBI browsing_VVG ,_, searching_VVG for_IF information_NN1 or_CC ready_JJ to_TO make_VVI a_AT1 purchase_NN1 ._. 
</s>
<s>
Therefore_RR ,_, especially_RR in_II the_AT case_NN1 of_IO the_AT first_MD two_MC actions_NN2 ,_, the_AT website_NN1 owner_NN1 need_NN1 to_TO be_VBI able_JK to_TO ;_; firstly_RR ,_, identify_VV0 the_AT action_NN1 pattern_NN1 of_IO the_AT visitor_NN1 ;_; and_CC secondly_RR ,_, take_VV0 responsive_JJ action_NN1 in_BCL21 order_BCL22 to_TO convert_VVI the_AT intent_NN1 of_IO the_AT visitor_NN1 into_II a_AT1 purchase_NN1 action_NN1 ._. 
</s>
<s>
The_AT fact_NN1 that_CST different_JJ kind_NN1 of_IO design_NN1 and_CC colours_NN2 impact_VV0 the_AT choices_NN2 of_IO customers_NN2 browsing_VVG a_AT1 web_NN1 site_NN1 is_VBZ proved_VVN by_II for_REX21 example_REX22 Mandel_NP1 and_CC Johnson_NP1 (_( 1999_MC )_) ._. 
</s>
<s>
Furthermore_RR ,_, they_PPHS2 go_VV0 on_RP to_TO prove_VVI that_DD1 which_DDQ information_NN1 that_CST the_AT customers_NN2 are_VBR exposed_VVN to_II impacts_NN2 their_APPGE decisions_NN2 ._. 
</s>
<s>
Hubl_VV0 and_CC Trifts_NP1 (_( 2000_MC )_) also_RR show_VV0 this_DD1 and_CC that_CST the_AT customers_NN2 purchase_VV0 quality_NN1 ,_, i.e._REX their_APPGE conversion_NN1 rate_NN1 ,_, increases_NN2 ._. 
</s>
<s>
Therefore_RR the_AT design_NN1 and_CC usability_NN1 considerations_NN2 are_VBR of_IO utmost_JJ importance_NN1 to_II a_AT1 serious_JJ e-commerce_JJ vendor_NN1 ._. 
</s>
<s>
As_CSA by_II prediction_NN1 of_IO the_AT behaviour_NN1 you_PPY are_VBR able_JK to_TO choose_VVI such_DA design_NN1 and_CC in-site_JJ marketing_NN1 choices_NN2 that_CST will_VM result_VVI in_II the_AT highest_JJT sales_NN conversion_NN1 rate_NN1 ,_, which_DDQ will_VM in_II the_AT end_NN1 influence_VV0 your_APPGE bottom-line_NN1 in_II a_AT1 positive_JJ way_NN1 ._. 
</s>
<s>
Research_VV0 also_RR confirms_VVZ the_AT advantage_NN1 that_CST online_JJ retailers_NN2 can_VM get_VVI when_CS predicting_VVG their_APPGE customer_NN1 's_GE behaviour_NN1 (_( Andersen_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2000_MC ;_; Bucklin_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2002_MC )_) ._. 
</s>
<s>
Hubl_VV0 and_CC Trifts_NP1 (_( 2000_MC )_) conclude_VV0 that_CST aids_NN2 should_VM be_VBI available_JJ for_IF helping_VVG the_AT customer_NN1 choose_VVI the_AT right_JJ products_NN2 ._. 
</s>
<s>
These_DD2 aids_NN2 should_VM in_II theory_NN1 be_VBI able_JK to_TO perfectly_RR suggest_VVI which_DDQ product_NN1 the_AT visitor_NN1 wants_VVZ to_TO buy._NNU 3.4_MC ._. 
</s>
<s>
Literature_NN1 Synthesis_NN1 It_PPH1 is_VBZ essential_JJ to_TO be_VBI able_JK to_TO predict_VVI behaviour_NN1 in_BCL21 order_BCL22 to_TO optimize_VVI marketing_NN1 material_NN1 ._. 
</s>
<s>
Additionally_RR ,_, in-site_JJ product_NN1 advertisements_NN2 or_CC even_RR discounts_NN2 presented_VVN to_II some_DD type_NN1 of_IO users_NN2 in_BCL21 order_BCL22 to_TO encourage_VVI a_AT1 buy_NN1 ._. 
</s>
<s>
In_II this_DD1 study_NN1 the_AT case_NN1 material_NN1 only_RR consists_VVZ of_IO registered_JJ users_NN2 ._. 
</s>
<s>
That_DD1 means_VVZ that_CST the_AT visitors_NN2 have_VH0 already_RR trusted_VVN the_AT e-commerce_JJ site_NN1 to_II some_DD degree_NN1 ._. 
</s>
<s>
To_TO further_RRR measure_VVI the_AT trust_NN1 the_AT non-obligatory_JJ variables_NN2 age_NN1 and_CC gender_NN1 could_VM be_VBI used_VVN ._. 
</s>
<s>
The_AT visitors_NN2 stemming_VVG from_II direct_JJ traffic_NN1 should_VM be_VBI more_RGR goal-oriented_JJ ._. 
</s>
<s>
(_( Park_NN1 2009_MC )_) 4_MC EMPIRICAL_JJ FINDINGS_NN2 This_DD1 chapter_NN1 focuses_VVZ on_II presentation_NN1 and_CC analysis_NN1 of_IO the_AT collected_JJ case_NN1 data_NN within_II the_AT context_NN1 of_IO the_AT research_NN1 question_NN1 ._. 
</s>
<s>
The_AT chapter_NN1 concludes_VVZ in_II a_AT1 discussion_NN1 of_IO the_AT findings._NNU 4.1_MC ._. 
</s>
<s>
Presentation_NN1 of_IO the_AT Data_NN Set_VV0 The_AT main_JJ data_NN set_VV0 and_CC focus_NN1 of_IO this_DD1 empirical_JJ analysis_NN1 contains_VVZ details_NN2 of_IO visitors_NN2 who_PNQS completed_VVD the_AT registration_NN1 process_NN1 of_IO the_AT e-commerce_JJ site_NN1 ._. 
</s>
<s>
Both_DB2 those_DD2 who_PNQS registered_VVD as_II a_AT1 guest_NN1 and_CC as_II a_AT1 permanent_JJ user_NN1 are_VBR included_VVN ._. 
</s>
<s>
The_AT main_JJ difference_NN1 and_CC focus_NN1 of_IO attention_NN1 is_VBZ whether_CSW the_AT payment_NN1 process_NN1 was_VBDZ successfully_RR completed_VVN ._. 
</s>
<s>
See_VV0 Table_NN1 2_MC for_IF the_AT complete_JJ descriptive_JJ statistical_JJ overview_NN1 of_IO the_AT data_NN set_VV0 ._. 
</s>
<s>
The_AT most_RGT novel_JJ characteristic_NN1 in_II the_AT main_JJ data_NN set_NN1 is_VBZ the_AT independent_JJ variable_NN1 nearestdist_NN1 ._. 
</s>
<s>
This_DD1 variable_NN1 measures_VVZ the_AT distance_NN1 from_II the_AT visitor_NN1 to_II the_AT nearest_JJT shopping_NN1 centre_NN1 ._. 
</s>
<s>
The_AT location_NN1 of_IO a_AT1 shopping_NN1 centre_NN1 has_VHZ been_VBN approximated_VVN in_II this_DD1 study_NN1 to_II the_AT location_NN1 of_IO a_AT1 Hennes_NN2 &;_NULL Mauritz_VV0 store_NN1 (_( 2012_MC )_) ,_, since_CS the_AT fact_NN1 is_VBZ that_CST they_PPHS2 are_VBR very_RG well_RR represented_VVN in_II all_DB larger_JJR locations_NN2 in_II Finland_NP1 ._. 
</s>
<s>
The_AT other_JJ characteristics_NN2 can_VM be_VBI observed_VVN in_II Table_NN1 1_MC1 ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) The_AT plan_NN1 is_VBZ to_TO use_VVI isorder_NN1 as_II the_AT dependent_JJ variable_NN1 for_IF the_AT statistical_JJ analysis_NN1 ._. 
</s>
<s>
As_II the_AT variable_NN1 is_VBZ a_AT1 dummy_NN1 ,_, the_AT model_NN1 chosen_VVN for_IF estimating_VVG it_PPH1 is_VBZ logistic_JJ regression_NN1 (_( also_RR called_VVN logit_NN1 model_NN1 )_) ._. 
</s>
<s>
4.2_MC ._. 
</s>
<s>
Preliminary_JJ Results_NN2 &lsqb;_( Table_NN1 &rsqb;_) The_AT preliminary_JJ analysis_NN1 with_IW the_AT logit_NN1 model_NN1 shows_VVZ that_CST the_AT AUC_NN1 criterion_NN1 holds_VVZ ,_, as_CSA it_PPH1 is_VBZ larger_JJR than_CSN the_AT null-model_NN1 benchmark_NN1 of_IO 0.5_MC ._. 
</s>
<s>
The_AT area_NN1 under_II ROC_NP1 curve_NN1 is_VBZ 0.6986_MC for_IF 554_MC observations_NN2 ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) &lsqb;_( Table_NN1 &rsqb;_) The_AT current_JJ preliminary_JJ results_NN2 seem_VV0 good_JJ for_IF further_JJR investigation_NN1 and_CC validation_NN1 of_IO the_AT statistical_JJ methods_NN2 and_CC results._NNU 4.3_MC ._. 
</s>
<s>
Demographics_NN2 of_IO Buyers_NN2 and_CC Non-payers_NN2 4.4_MC ._. 
</s>
<s>
Prediction_NN1 of_IO Behaviour_NN1 4.5_MC ._. 
</s>
<s>
Discussion_NN1 5_MC CONCLUSIONS_NN2 This_DD1 chapter_NN1 is_VBZ still_RR under_II consideration_NN1 in_II this_DD1 version_NN1 of_IO the_AT paper_NN1 draft._NNU 5.1_MC ._. 
</s>
<s>
Results_NN2 The_AT most_RGT novel_JJ theoretical_JJ and_CC empirical_JJ contribution_NN1 of_IO this_DD1 paper_NN1 is_VBZ the_AT usage_NN1 of_IO the_AT distance_NN1 to_II the_AT nearest_JJT shopping_NN1 centre_NN1 for_IF profiling_VVG the_AT demographics_NN1 and_CC behaviour_NN1 of_IO the_AT e-commerce_JJ visitor._NNU 5.2_MC ._. 
</s>
<s>
Value_NN1 for_IF the_AT Case_NN1 Company_NN1 This_DD1 research_NN1 paper_NN1 confirms_VVZ the_AT feelings_NN2 for_IF the_AT customer_NN1 demographics_NN2 that_CST the_AT case_NN1 company_NN1 had_VHD ._. 
</s>
<s>
The_AT paper_NN1 will_VM act_VVI as_II a_AT1 starting_NN1 point_NN1 for_IF site_NN1 optimization_NN1 with_IW regards_VVZ to_II buying_VVG behaviour_NN1 analysis_NN1 ._. 
</s>
<s>
The_AT case_NN1 company_NN1 should_VM include_VVI the_AT implementations_NN2 of_IO the_AT findings_NN2 in_II this_DD1 research_NN1 paper_NN1 for_IF the_AT marketing_NN1 and_CC e-commerce_JJ platform_NN1 design_NN1 ._. 
</s>
<s>
This_DD1 paper_NN1 also_RR shows_VVZ that_CST there_EX is_VBZ a_AT1 need_NN1 for_IF the_AT case_NN1 company_NN1 to_TO also_RR start_VVI logging_VVG the_AT clickstream_NN1 of_IO the_AT website_NN1 visitors_NN2 in_II such_DA a_AT1 way_NN1 that_CST the_AT data_NN can_VM be_VBI analyzed_VVN on-the-_JJ flow_NN1 by_II the_AT e-commerce_JJ application_NN1 in_BCL21 order_BCL22 to_TO take_VVI more_RGR dynamic_JJ stance_NN1 for_IF what_DDQ to_TO show_VVI to_II the_AT visitor_NN1 (_( Andersen_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2000_MC )_) ._. 
</s>
<s>
5.3_MC ._. 
</s>
<s>
Further_JJR Research_NN1 There_EX might_VM be_VBI more_DAR variables_NN2 that_CST could_VM be_VBI considered_VVN for_IF inclusion_NN1 in_II the_AT empirical_JJ analysis_NN1 that_CST would_VM bring_VVI more_RGR light_JJ into_II the_AT case_NN1 ._. 
</s>
<s>
For_REX21 example_REX22 the_AT past_JJ buying_NN1 behaviour_NN1 of_IO the_AT visitors_NN2 should_VM be_VBI taken_VVN into_II account_NN1 ._. 
</s>
<s>
When_CS the_AT clickstream_NN1 data_NN has_VHZ been_VBN gathered_VVN ,_, it_PPH1 should_VM be_VBI combined_VVN with_IW all_DB characteristics_NN2 identified_VVN in_II this_DD1 report_NN1 and_CC then_RT analyzed_VVD on_II the_AT basis_NN1 of_IO how_RGQ well_RR different_JJ buying_NN1 aids_NN2 are_VBR able_JK to_TO influence_VVI the_AT decisions_NN2 of_IO the_AT visitors_NN2 ._. 
</s>
<s>
This_DD1 would_VM further_RRR increase_VVI the_AT value_NN1 of_IO the_AT work_NN1 done_VDN for_IF this_DD1 report_NN1 ._. 
</s>
