<s>
How_RGQ evolving_JJ from_II service_NN1 marketing_NN1 to_TO design_VVI thinking_NN1 affects_VVZ business_NN1 :_: A_ZZ1 comparative_JJ study_NN1 of_IO Bang_NN1 &;_NULL Olufsen_NP1 and_CC Nike_NP1 1_MC1 INTRODUCTION_NN1 This_DD1 study_NN1 compares_VVZ the_AT service_NN1 marketing_NN1 and_CC design_NN1 thinking_VVG strategies_NN2 of_IO Bang_NN1 &;_NULL Olufsen_NP1 and_CC Nike_NP1 in_BCL21 order_BCL22 to_TO examine_VVI how_RRQ implementing_NN1 these_DD2 have_VH0 affected_VVN their_APPGE business_NN1 ._. 
</s>
<s>
By_II reviewing_VVG the_AT theories_NN2 behind_II these_DD2 strategies_NN2 and_CC comparing_VVG them_PPHO2 to_II practical_JJ cases_NN2 ,_, the_AT author_NN1 is_VBZ able_JK to_TO pinpoint_VVI some_DD of_IO the_AT fundamental_JJ success_NN1 factors_NN2 these_DD2 strategies_NN2 provide_VV0 ._. 
</s>
<s>
Using_VVG qualitative_JJ data_NN gathered_VVN from_II case_NN1 articles_NN2 the_AT author_NN1 then_RT tests_VVZ the_AT relationship_NN1 between_II service_NN1 marketing_NN1 and_CC design_NN1 thinking_NN1 in_BCL21 order_BCL22 to_TO establish_VVI what_DDQ common_JJ denominators_NN2 can_VM be_VBI identified_VVN ._. 
</s>
<s>
Finally_RR the_AT author_NN1 will_VM assume_VVI the_AT synergies_NN2 of_IO the_AT two_MC theories_NN2 and_CC suggest_VV0 possible_JJ areas_NN2 for_IF further_JJR research._NNU 1.2_MC PURPOSE_NN1 OF_IO THE_AT STUDY_NN1 In_II recent_JJ years_NNT2 ,_, confronting_VVG the_AT current_JJ economic_JJ climate_NN1 ,_, companies_NN2 have_VH0 actively_RR been_VBN exploring_VVG new_JJ business_NN1 models_NN2 to_TO improve_VVI their_APPGE market_NN1 position_NN1 ._. 
</s>
<s>
Globalization_NN1 has_VHZ led_VVN to_II increased_JJ access_NN1 to_II goods_NN2 ,_, innovation_NN1 and_CC raw_JJ material_NN1 that_CST have_VH0 propelled_VVN companies_NN2 to_TO bring_VVI out_RP new_JJ products_NN2 at_II intensifying_VVG speed_NN1 ._. 
</s>
<s>
As_CSA these_DD2 resources_NN2 are_VBR becoming_VVG more_RGR widely_RR available_JJ ,_, an_AT1 increasing_JJ amount_NN1 of_IO companies_NN2 are_VBR able_JK to_TO enter_VVI the_AT market_NN1 ._. 
</s>
<s>
However_RR ,_, this_DD1 presents_VVZ challenges_NN2 in_II31 terms_II32 of_II33 differentiating_JJ ones_NN2 offerings_NN2 from_II competitors_NN2 offering_VVG the_AT same_DA product_NN1 ._. 
</s>
<s>
This_DD1 study_NN1 focus_NN1 on_II the_AT service_NN1 perspective_NN1 in_II which_DDQ added_VVD services_NN2 ,_, supporting_VVG the_AT core_NN1 product_NN1 ,_, brings_VVZ the_AT desired_JJ effects_NN2 of_IO differentiation_NN1 ._. 
</s>
<s>
This_DD1 study_NN1 compares_VVZ the_AT service_NN1 marketing_NN1 and_CC design_NN1 thinking_VVG strategies_NN2 of_IO Bang_NN1 &;_NULL Olufsen_NP1 and_CC Nike_NP1 ,_, with_IW the_AT aim_NN1 of_IO establishing_VVG common_JJ denominators_NN2 of_IO success_NN1 in_II the_AT who_PNQS models._NNU 1.3_MC LIMITATIONS_NN2 The_AT scope_NN1 of_IO this_DD1 study_NN1 ,_, comparing_VVG cases_NN2 of_IO two_MC companies_NN2 ,_, will_VM not_XX sufficiently_RR represent_VVI applications_NN2 in_II the_AT wider_JJR world_NN1 or_CC in_II other_JJ areas_NN2 of_IO business_NN1 ._. 
</s>
<s>
Nevertheless_RR ,_, in_II creating_VVG the_AT assessment_NN1 based_VVN on_II theories_NN2 and_CC comparing_VVG them_PPHO2 to_II actual_JJ events_NN2 will_VM give_VVI an_AT1 indication_NN1 on_II the_AT impact_NN1 of_IO the_AT given_JJ methods_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ also_RR difficult_JJ to_TO project_VVI the_AT alternative_JJ implications_NN2 other_JJ product_NN1 development_NN1 or_CC marketing_NN1 efforts_NN2 might_VM have_VHI had_VHN ,_, as_CSA the_AT events_NN2 unfolded_VVN in_II the_AT cases_NN2 can_VM not_XX be_VBI reversed._NNU 1.4_MC RESEARCH_NN1 PROBLEM_NN1 In_II the_AT past_NN1 ,_, product_NN1 differentiation_NN1 strategies_NN2 have_VH0 relied_VVN heavily_RR on_II product_NN1 development_NN1 and_CC innovation_NN1 by_II adding_VVG new_JJ features_NN2 ,_, making_VVG products_NN2 lighter_NN1 ,_, or_CC tougher_JJR ,_, or_CC otherwise_RR differentiate_VV0 themselves_PPX2 from_II the_AT competition_NN1 ._. 
</s>
<s>
In_II the_AT 1970_MC221 's_MC222 service_NN1 marketing_NN1 emerged_VVD ,_, shifting_JJ focus_NN1 from_II product_NN1 to_II customer_NN1 ._. 
</s>
<s>
More_RGR recently_RR ,_, a_AT1 supporting_JJ method_NN1 has_VHZ emerged_VVN out_II21 of_II22 the_AT field_NN1 of_IO art_NN1 and_CC design_NN1 ,_, known_VVN as_II design_NN1 thinking_NN1 ,_, as_CSA "_" functional_JJ benefits_NN2 alone_RR ,_, it_PPH1 seems_VVZ ,_, are_VBR no_RR21 longer_RR22 enough_RR to_TO capture_VVI or_CC create_VVI the_AT brand_NN1 distinction_NN1 "_" Brown_NP1 (_( 2009_MC )_) ._. 
</s>
<s>
What_DDQ is_VBZ the_AT difference_NN1 between_II service_NN1 marketing_NN1 and_CC design_NN1 thinking_NN1 ?_? 
</s>
<s>
Are_VBR there_EX any_DD similarities_NN2 ,_, and_CC if_CS so_RR ,_, how_RRQ are_VBR they_PPHS2 accomplished_VVN ?_? 
</s>
<s>
This_DD1 paper_NN1 aims_VVZ to_TO evaluate_VVI impact_NN1 ,_, if_CS any_DD ,_, service_NN1 marketing_NN1 and_CC design_NN1 thinking_NN1 ,_, or_CC lack_NN1 thereof_RR ,_, have_VH0 had_VHN on_II the_AT business_NN1 of_IO Bang_NN1 &;_NULL Olufsen_NP1 and_CC Nike_VV0 respectively._NNU 2_MC THEORETICAL_JJ FRAMEWORK_NN1 On_II one_MC1 hand_NN1 ,_, academic_JJ research_NN1 on_II service_NN1 marketing_NN1 is_VBZ rigorous_JJ and_CC plenty_PN ,_, on_II the_AT other_JJ hand_NN1 not_XX much_DA1 research_NN1 have_VH0 been_VBN conducted_VVN regarding_II design_NN1 thinking_NN1 ._. 
</s>
<s>
Despite_II this_DD1 ,_, their_APPGE similarities_NN2 are_VBR remarkable_JJ ,_, considering_CS the_AT fact_NN1 that_CST service_NN1 marketing_NN1 stems_VVZ from_II marketing_NN1 within_II economics_NN1 ,_, while_CS design_NN1 thinking_VVG stems_NN2 from_II design_NN1 within_II the_AT arts_NN2 ._. 
</s>
<s>
To_TO start_VVI with_IW ,_, both_DB2 consider_VV0 themselves_PPX2 perspectives_NN2 ,_, as_II31 opposed_II32 to_II33 rigorous_JJ quantitatively_RR measurable_JJ theories_NN2 or_CC clear_RR cut_VVN methods_NN2 of_IO conduct._NNU 2.1_MC SERVICE_NN1 MARKETING_NN1 AS_II A_AT1 CONCEPT_NN1 Origins_NN2 of_IO the_AT logic_NN1 of_IO service_NN1 marketing_NN1 can_VM be_VBI found_VVN in_II basic_JJ human_JJ psychology_NN1 and_CC is_VBZ fundamentally_RR considered_VVN a_AT1 perception_NN1 ._. 
</s>
<s>
"_" Customers_NN2 do_VD0 not_XX buy_VVI goods_NN2 or_CC services_NN2 ,_, they_PPHS2 buy_VV0 the_AT benefits_NN2 goods_NN2 and_CC services_NN2 provide_VV0 them_PPHO2 with_IW "_" Grnroos_NP1 (_( 2007_MC ,_, p._NN1 4_MC )_) ,_, as_CSA originally_RR found_VVN by_II Theodore_NP1 Levitt_NP1 (_( 1980_MC ,_, p._NNU 83-91_MCMC )_) ._. 
</s>
<s>
Products_NN2 and_CC services_NN2 are_VBR consumed_VVN by_II customers_NN2 to_TO fulfill_VVI their_APPGE needs_NN2 ._. 
</s>
<s>
The_AT premise_NN1 of_IO service_NN1 marketing_NN1 is_VBZ to_TO put_VVI the_AT customer_NN1 in_II focus_NN1 in_II the_AT product_NN1 development_NN1 process_NN1 ,_, rather_II21 than_II22 the_AT product_NN1 itself_PPX1 ,_, and_CC thereby_RR companies_NN2 is_VBZ able_JK to_TO offer_VVI more_RGR satisfying_JJ solutions_NN2 to_II its_APPGE customers_NN2 ._. 
</s>
<s>
An_AT1 ongoing_JJ debate_NN1 have_VH0 been_VBN going_VVG on_RP since_CS before_CS the_AT Levitt_NP1 article_NN1 was_VBDZ published_VVN ,_, on_II why_RRQ companies_NN2 have_VH0 such_DA difficulties_NN2 changing_VVG their_APPGE old_JJ product_NN1 centered_VVD behavior_NN1 ._. 
</s>
<s>
Positive_JJ effects_NN2 of_IO service_NN1 marketing_NN1 have_VH0 been_VBN proven_VVN through_II extensive_JJ academic_JJ research_NN1 (_( Gummesson_NP1 ,_, 2002_MC ;_; Grnroos_NP1 ,_, 2006_MC )_) and_CC it_PPH1 is_VBZ generally_RR accepted_VVN that_DD1 service_NN1 marketing_NN1 improves_VVZ customer_NN1 satisfaction_NN1 and_CC loyalty_NN1 (_( Grnroos_NP1 ,_, (_( 2007_MC )_) ._. 
</s>
<s>
But_CCB despite_II numerous_JJ and_CC overwhelmingly_RR clear_JJ findings_NN2 ,_, very_RG few_DA2 companies_NN2 today_RT have_VH0 managed_VVN to_TO change_VVI their_APPGE perspectives_NN2 ._. 
</s>
<s>
New_JJ strategies_NN2 have_VH0 to_TO be_VBI implemented_VVN ,_, as_CSA Christian_JJ Grnroos_NN2 (_( 2007_MC ,_, p._NN1 7_MC )_) identifies_VVZ four_MC key_JJ strategic_JJ perspectives_NN2 in_II marketing_NN1 as_II ;_; core_NN1 product_NN1 ,_, price_NN1 ,_, service_NN1 and_CC image._NNU 2.2_MC DESIGN_NN1 THINKING_VVG AS_II A_AT1 CONCEPT_NN1 Design_NN1 thinking_NN1 ,_, also_RR conceived_VVN in_II the_AT 1970_MC `_" s_ZZ1 ,_, stems_VVZ from_II human-centered_JJ design_NN1 ,_, as_CSA designer_NN1 Rolf_NP1 Faste_NP1 expanded_VVD on_II design_NN1 engineer_NN1 Robert_NP1 McKim_NP1 's_GE book_NN1 Experience_NN1 in_II Visual_JJ Thinking_NN1 (_( 1973_MC )_) while_CS teaching_VVG at_II Stanford_NP1 University_NN1 ._. 
</s>
<s>
Fundamentally_RR ,_, it_PPH1 is_VBZ a_AT1 method_NN1 for_IF designers_NN2 to_TO solve_VVI problems_NN2 during_II the_AT design_NN1 process_NN1 mainly_RR in_II architecture_NN1 ,_, product_NN1 design_NN1 and_CC service_NN1 design_NN1 (_( Buchanan_NP1 ,_, 1992_MC )_) ._. 
</s>
<s>
It_PPH1 's_VBZ teachings_NN2 was_VBDZ adapted_VVN into_II business_NN1 use_NN1 by_II design_NN1 consultancy_NN1 firm_NN1 IDEO_NP1 founders_NN2 Tim_NP1 Brown_NP1 and_CC David_NP1 Kelley_NP1 ._. 
</s>
<s>
However_RR ,_, as_CSA Tim_NP1 Brown_NP1 explains_VVZ in_II his_APPGE book_NN1 Change_NN1 by_II Design_NN1 (_( Brown_NP1 ,_, 2009_MC )_) design_NN1 thinking_NN1 has_VHZ not_XX been_VBN studied_VVN academically_RR and_CC thus_RR not_XX reached_VVN very_RG far_RR beyond_II the_AT design_NN1 community_NN1 ._. 
</s>
<s>
In_II the_AT same_DA book_NN1 ,_, which_DDQ the_AT author_NN1 have_VH0 found_VVN is_VBZ the_AT best_JJT account_NN1 of_IO design_NN1 thinking_VVG to_II date_NN1 ,_, Brown_NP1 talks_VVZ extensively_RR about_II the_AT importance_NN1 of_IO meaning_NN1 and_CC storytelling_NN1 ._. 
</s>
<s>
How_RRQ a_AT1 product_NN1 or_CC service_NN1 is_VBZ perceived_VVN by_II a_AT1 customer_NN1 directly_RR affects_VVZ the_AT kinds_NN2 of_IO feelings_NN2 the_AT person_NN1 have_VH0 for_IF the_AT good_JJ ,_, both_RR positively_RR and_CC negatively_RR ._. 
</s>
<s>
Design_NN1 thinking_NN1 is_VBZ about_II the_AT designer_NN1 being_VBG able_JK to_TO take_VVI the_AT perspective_NN1 of_IO the_AT customer_NN1 in_BCL21 order_BCL22 to_TO understand_VVI how_RRQ the_AT person_NN1 thinks_VVZ and_CC behaves_VVZ in_II certain_JJ situations._NNU 2.3_MC CONNECTING_VVG THE_AT DOTS_NN2 As_CSA already_RR mentioned_VVN above_RL ,_, the_AT need_NN1 for_IF alternative_JJ methods_NN2 of_IO differentiation_NN1 is_VBZ needed_VVN for_IF companies_NN2 in_II a_AT1 globally_RR connected_JJ world_NN1 ._. 
</s>
<s>
From_II the_AT previous_JJ two_MC paragraphs_NN2 we_PPIS2 can_VM conclude_VVI that_DD1 service_NN1 marketing_NN1 and_CC design_NN1 thinking_NN1 are_VBR different_JJ stages_NN2 of_IO the_AT same_DA process_NN1 ,_, only_RR the_AT approach_NN1 is_VBZ what_DDQ separates_VVZ them_PPHO2 ._. 
</s>
<s>
We_PPIS2 can_VM establish_VVI from_II this_DD1 ,_, that_CST by_II utilizing_VVG the_AT framework_NN1 for_IF design_NN1 thinking_VVG in_II product_NN1 development_NN1 processes_NN2 ,_, companies_NN2 are_VBR able_JK to_TO incorporate_VVI the_AT functionality_NN1 needed_VVD to_TO lay_VVI the_AT groundwork_NN1 for_IF what_DDQ service_NN1 marketing_NN1 will_NN1 at_II a_AT1 later_JJR stage_NN1 be_VBI able_JK to_TO support_VVI ._. 
</s>
<s>
And_CC as_CSA we_PPIS2 will_VM see_VVI later_RRR in_II this_DD1 study_NN1 ,_, if_CS the_AT two_MC entities_NN2 do_VD0 not_XX match_VVI the_AT consequences_NN2 can_VM be_VBI detrimental_JJ to_II the_AT companies_NN2 image._NNU 3_MC COMPARATIVE_JJ STUDY_NN1 In_BCL21 order_BCL22 to_TO lay_VVI the_AT foundations_NN2 for_IF this_DD1 study_NN1 the_AT author_NN1 chose_VVD to_TO select_VVI two_MC companies_NN2 with_IW different_JJ approaches_NN2 and_CC perspectives_NN2 on_II product_NN1 development_NN1 and_CC design_NN1 ._. 
</s>
<s>
Taking_VVG a_AT1 look_NN1 at_II a_AT1 case_NN1 concerning_II each_DD1 company_NN1 illustrates_VVZ the_AT difference_NN1 starting_NN1 point_NN1 they_PPHS2 represent_VV0 ,_, but_CCB at_II the_AT same_DA time_NNT1 demonstrate_VV0 how_RGQ powerful_JJ service_NN1 marketing_NN1 and_CC design_NN1 thinking_NN1 can_VM be_VBI when_CS introduced_VVN into_II a_AT1 corporate_JJ culture_NN1 ._. 
</s>
<s>
As_CSA explained_VVN in_II the_AT cases_NN2 below_II it_PPH1 is_VBZ obvious_JJ that_CST Bang_VV0 &;_NULL Olufsen_NP1 have_VH0 embedded_VVN these_DD2 perspectives_NN2 since_CS the_AT company_NN1 was_VBDZ founded_VVN in_II 1925_MC ,_, while_CS it_PPH1 took_VVD Nike_NP1 over_RG three_MC decades_NNT2 to_TO fully_RR comprehend_VVI the_AT implications_NN2 of_IO putting_VVG its_APPGE customers_NN2 in_II focus._NNU 3.1_MC CASE_NP1 :_: BANG_FU &;_NULL OLUFSEN_NN1 The_AT danish_JJ consumer_NN1 electronics_NN1 company_NN1 Bang_NN1 &;_NULL Olufsen_NP1 operates_VVZ on_II a_AT1 holistic_JJ design_NN1 driven_JJ innovation_NN1 model_NN1 ._. 
</s>
<s>
That_DD1 incorporates_VVZ merging_VVG all_DB its_APPGE offerings_NN2 to_TO work_VVI in_II tandem_NN1 with_IW each_PPX221 other_PPX222 in_II a_AT1 way_NN1 supporting_VVG different_JJ customer_NN1 needs_VVZ with_IW various_JJ products_NN2 ._. 
</s>
<s>
When_CS a_AT1 customer_NN1 buys_VVZ a_AT1 television_NN1 from_II Bang_NN1 &;_NULL Olufsen_NP1 one_MC1 year_NNT1 and_CC then_RT buys_VVZ external_JJ speakers_NN2 from_II the_AT same_DA company_NN1 the_AT next_MD year_NNT1 ,_, the_AT customer_NN1 can_VM be_VBI sure_JJ the_AT speakers_NN2 will_VM connect_VVI seamlessly_RR to_II the_AT television_NN1 ._. 
</s>
<s>
Even_RR the_AT same_DA remote_JJ control_NN1 is_VBZ used_VVN to_TO control_VVI all_DB the_AT companies_NN2 products_NN2 ,_, as_II31 opposed_II32 to_II33 most_DAT other_JJ consumer_NN1 electronics_NN1 companies_NN2 where_RRQ radios_NN2 and_CC television_NN1 remote_JJ controls_NN2 change_VV0 from_II year-to-_JJ year_NNT1 ._. 
</s>
<s>
Even_RR the_AT variation_NN1 in_II different_JJ models_NN2 on_II sale_NN1 during_II the_AT same_DA time_NNT1 period_NN1 can_VM have_VHI countless_JJ variations_NN2 in_II their_APPGE remote_JJ controls_NN2 ,_, resulting_VVG in_II people_NN having_VHG a_AT1 myriad_NN1 of_IO remote_JJ controls_NN2 at_II their_APPGE house_NN1 performing_VVG different_JJ tasks_NN2 ,_, with_IW only_RR a_AT1 handful_NN1 of_IO buttons_NN2 being_VBG useful_JJ on_II each_DD1 remote_JJ (_( Austin_NP1 and_CC Beyersdorfer_NP1 ,_, 2007_MC )_) ._. 
</s>
<s>
When_CS a_AT1 new_JJ product_NN1 is_VBZ being_VBG conceived_VVN by_II Bang_NN1 &;_NULL Olufsen_NP1 designers_NN2 ,_, the_AT first_MD and_CC foremost_JJT focus_NN1 have_VH0 always_RR been_VBN its_APPGE customers_NN2 ._. 
</s>
<s>
The_AT emphasis_NN1 is_VBZ made_VVN on_II the_AT environments_NN2 in_II which_DDQ their_APPGE customers_NN2 live_VV0 and_CC how_RGQ well_RR the_AT product_NN1 will_VM blend_VVI in_RP to_II those_DD2 surroundings_NN2 ,_, as_RG beautifully_RR as_CSA the_AT art_NN1 and_CC decorations_NN2 previously_RR occupying_VVG their_APPGE spaces_NN2 ._. 
</s>
<s>
However_RR ,_, not_XX only_RR the_AT looks_NN2 of_IO the_AT products_NN2 are_VBR taken_VVN into_II considered_JJ at_II this_DD1 early_JJ stage_NN1 of_IO product_NN1 development_NN1 ,_, aspects_NN2 such_II21 as_II22 ease_NN1 of_IO use_NN1 and_CC how_RGQ intuitive_JJ the_AT operation_NN1 of_IO the_AT products_NN2 will_VM be_VBI is_VBZ put_VVN in_II focus_NN1 ._. 
</s>
<s>
The_AT combination_NN1 of_IO the_AT considerations_NN2 of_IO these_DD2 matters_NN2 are_VBR what_DDQ makes_VVZ Bang_NN1 &;_NULL Olufsen_NN1 what_DDQ is_VBZ is_VBZ ,_, even_CS21 though_CS22 all_DB of_IO the_AT components_NN2 inside_II their_APPGE machines_NN2 are_VBR the_AT very_RG same_DA components_NN2 used_VVN and_CC manufactured_VVN by_II its_APPGE competitors_NN2 ._. 
</s>
<s>
Only_RR the_AT reason_NN1 for_IF Bang_NN1 &;_NULL Olufsen_NN1 being_VBG able_JK to_TO charge_VVI a_AT1 premium_NN1 for_IF their_APPGE products_NN2 is_VBZ the_AT fact_NN1 that_CST every_AT1 aspect_NN1 of_IO the_AT product_NN1 ,_, when_CS placed_VVN into_II the_AT reality_NN1 of_IO its_APPGE customers_NN2 use_VV0 is_VBZ taught_VVN through_RP from_II start_NN1 to_TO finnish_VVI ._. 
</s>
<s>
Put_VV0 into_II the_AT context_NN1 of_IO Grnroos_NP1 four_MC strategic_JJ perspectives_NN2 Bang_VV0 &;_NULL Olufsen_NP1 is_VBZ categorized_VVN into_II the_AT service_NN1 perspective._NNU 3.2_MC CASE_NP1 :_: NIKE_VV0 In_II 1999_MC Nike_NP1 became_VVD the_AT center_NN1 of_IO attention_NN1 in_II a_AT1 scandal_NN1 as_II a_AT1 result_NN1 of_IO child_NN1 labour_NN1 and_CC poor_JJ working_JJ conditions_NN2 being_VBG exposed_VVN by_II Naomi_NP1 Klein_NP1 in_II her_APPGE book_NN1 No_AT Logo_NN1 ._. 
</s>
<s>
Not_XX only_RR did_VDD the_AT message_NN1 emerging_VVG from_II this_DD1 book_NN1 not_XX resonate_JJ with_IW the_AT clean_JJ and_CC sporty_JJ image_NN1 Nike_NP1 wanted_VVD to_TO portray_VVI ,_, but_CCB it_PPH1 did_VDD not_XX support_VVI any_DD of_IO the_AT marketing_NN1 material_NN1 in_II the_AT campaigns_NN2 being_VBG executed_VVN worldwide_RL by_II the_AT company_NN1 at_II that_DD1 time_NNT1 ._. 
</s>
<s>
Marketing_NN1 money_NN1 was_VBDZ proving_VVG to_TO be_VBI worthless_JJ against_II the_AT newly_RR emerged_VVD public_NN1 opinion_NN1 and_CC Nike_NP1 quickly_RR realized_VVN that_CST it_PPH1 was_VBDZ time_NNT1 to_TO improve_VVI its_APPGE workers_NN2 '_GE conditions_NN2 in_II its_APPGE production_NN1 plants_NN2 ._. 
</s>
<s>
(_( Klein_NN1 ,_, 1999_MC )_) ._. 
</s>
<s>
As_II31 opposed_II32 to_II33 Bang_NN1 &;_NULL Olufsen_NP1 ,_, according_II21 to_II22 the_AT Grnroos_NN2 for_IF strategic_JJ perspectives_NN2 model_NN1 ,_, Nike_NP1 clearly_RR utilize_VV0 the_AT image_NN1 perspective_NN1 ._. 
</s>
<s>
Such_DA a_AT1 company_NN1 is_VBZ much_RR more_RGR prone_JJ to_II scrutiny_NN1 ,_, as_CSA such_DA a_AT1 large_JJ part_NN1 of_IO what_DDQ Nike_NP1 is_VBZ offering_VVG is_VBZ based_VVN purely_RR on_II the_AT company_NN1 logo_NN1 printed_VVN or_CC sown_VVN on_II its_APPGE garments_NN2 and_CC apparel_NN1 ._. 
</s>
<s>
Studying_VVG the_AT No_AT Logo_NN1 case_NN1 it_PPH1 becomes_VVZ clear_JJ that_CST what_DDQ was_VBDZ revealed_VVN about_II the_AT company_NN1 not_XX only_RR affected_VVN Nike_NP1 ,_, but_CCB actually_RR affected_VVN the_AT whole_JJ industry_NN1 as_II a_AT1 whole_NN1 ._. 
</s>
<s>
Certainly_RR Nike_NP1 was_VBDZ at_II the_AT time_NNT1 being_VBG affected_VVN most_DAT ,_, but_CCB it_PPH1 was_VBDZ how_RRQ its_APPGE managers_NN2 and_CC CEO_NN1 reacted_VVD to_II the_AT scandal_NN1 that_CST was_VBDZ impressive_JJ ._. 
</s>
<s>
Instead_II21 of_II22 trying_VVG to_TO blame_VVI anyone_PN1 else_RR ,_, they_PPHS2 initially_RR publicly_RR apologized_VVD and_CC made_VVD some_DD changes_NN2 at_II their_APPGE production_NN1 plants_NN2 ._. 
</s>
<s>
In_II 2004_MC they_PPHS2 founded_VVD The_AT Nike_NP1 Foundation_NN1 ,_, focusing_VVG on_II improving_VVG the_AT lives_NN2 of_IO workers_NN2 in_II countries_NN2 they_PPHS2 manufactures_VVZ in_RP ,_, with_IW special_JJ emphasis_NN1 on_II girls_NN2 (_( Nike_NP1 Foundation_NN1 ,_, 2004_MC )_) ._. 
</s>
<s>
Later_RRR ,_, a_AT1 new_JJ research_NN1 division_NN1 focusing_VVG solely_RR on_II customers_NN2 desires_NN2 was_VBDZ founded_VVN ,_, where_CS ideas_NN2 such_II21 as_II22 the_AT electronic_JJ running_JJ aid_NN1 for_IF iPhone_NN1 and_CC iPod_NN1 ,_, Nike+_FO was_VBDZ released_VVN ._. 
</s>
<s>
From_II the_AT same_DA laboratories_NN2 emerged_VVD an_AT1 online_JJ tool_NN1 on_II Nike_NP1 's_GE website_NN1 for_IF people_NN to_TO engage_VVI in_II the_AT design_NN1 process_NN1 by_II decorating_VVG their_APPGE own_DA shoes_NN2 ._. 
</s>
<s>
But_CCB the_AT most_RGT important_JJ break_NN1 through_II have_VH0 been_VBN discovering_VVG new_JJ ways_NN2 to_TO manufacture_VVI shoes_NN2 ,_, with_IW the_AT aim_NN1 of_IO zero_NN1 waist_NN1 material_NN1 (_( Mc_NNU Girt_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
The_AT ultimate_JJ goal_NN1 with_IW innovating_JJ new_JJ methods_NN2 is_VBZ to_TO make_VVI production_NN1 cheap_JJ enough_RR to_TO bring_VVI back_RP the_AT production_NN1 to_II homeland_NN1 markets_NN2 ,_, such_II21 as_II22 the_AT USA_NP1 ._. 
</s>
<s>
As_II a_AT1 result_NN1 ,_, both_DB2 working_VVG conditions_NN2 as_II31 well_II32 as_II33 costs_NN2 can_VM be_VBI more_RGR easily_RR controlled_VVN ,_, while_CS demand_NN1 for_IF products_NN2 in_II original_JJ production_NN1 countries_NN2 is_VBZ on_II the_AT rise_NN1 and_CC thus_RR securing_VVG jobs_NN2 over_RP there_RL as_RR21 well_RR22 (_( Hunter_NP1 ,_, 2012_MC )_) ._. 
</s>
<s>
4_MC DISCUSSION_NN1 Studying_VVG the_AT methodology_NN1 of_IO Bang_NN1 &;_NULL Olufsen_NP1 and_CC Nike_NP1 initially_RR exposed_VVD two_MC very_RG different_JJ approaches_NN2 to_II product_NN1 development_NN1 ._. 
</s>
<s>
But_CCB as_CSA Nike_NP1 ensued_VVD criticism_NN1 for_IF its_APPGE conducts_NN2 and_CC ethical_JJ choices_NN2 ,_, they_PPHS2 knew_VVD they_PPHS2 had_VHD to_TO alter_VVI their_APPGE methods_NN2 or_CC loose_JJ business_NN1 ._. 
</s>
<s>
What_DDQ they_PPHS2 did_VDD was_VBDZ incorporated_VVN design_NN1 thinking_VVG during_II its_APPGE production_NN1 phases_NN2 and_CC adopting_VVG a_AT1 service_NN1 marketing_NN1 into_II its_APPGE company_NN1 culture_NN1 ,_, something_PN1 already_RR embodied_VVN in_II the_AT Bang_NN1 &;_NULL Olufsen_NP1 DNA_NN1 since_CS its_APPGE foundation_NN1 ._. 
</s>
<s>
The_AT alternative_NN1 is_VBZ grim_JJ ,_, as_CSA was_VBDZ briefly_RR demonstrated_VVN in_II the_AT Nike_NP1 case_NN1 ,_, where_CS Nike_NP1 for_IF years_NNT2 after_II the_AT scandal_NN1 had_VHD problems_NN2 with_IW its_APPGE reputation_NN1 ._. 
</s>
<s>
Slowly_RR building_VVG itself_PPX1 back_RP up_RP and_CC regaining_VVG momentum_NN1 have_VH0 proven_VVN the_AT right_JJ strategy_NN1 for_IF them_PPHO2 in_II a_AT1 bid_NN1 to_TO keep_VVI at_II the_AT forefront_NN1 of_IO innovation_NN1 and_CC desirability_NN1 within_II their_APPGE field_NN1 ._. 
</s>
<s>
Bang_VV0 &;_NULL Olufsen_NP1 on_II the_AT other_JJ hand_NN1 have_VH0 not_XX been_VBN as_RG successful_JJ in_II reinventing_VVG themselves_PPX2 ,_, despite_II a_AT1 good_JJ strategy_NN1 ,_, but_CCB that_DD1 will_VM have_VHI to_TO be_VBI left_VVN as_II the_AT topic_NN1 for_IF another_DD1 study._NNU 5_MC CONCLUSIONS_NN2 Companies_NN2 are_VBR facing_VVG increased_JJ competition_NN1 from_II globalization_NN1 ,_, while_CS at_II the_AT same_DA time_NNT1 consumers_NN2 get_VV0 more_RGR conscious_JJ and_CC thus_RR demand_VV0 greater_JJR transparency_NN1 ._. 
</s>
<s>
Inevitably_RR ,_, as_CSA Grnroos_NP1 has_VHZ already_RR concluded_VVN companies_NN2 need_VV0 to_TO start_VVI applying_VVG service_NN1 marketing_NN1 to_II their_APPGE thinking_NN1 ._. 
</s>
<s>
As_CSA have_VH0 been_VBN interesting_JJ to_TO observe_VVI in_II this_DD1 study_NN1 ,_, the_AT world_NN1 of_IO production_NN1 and_CC design_NN1 have_VH0 its_APPGE own_DA method_NN1 for_IF answering_VVG the_AT same_DA challenges_NN2 ,_, design_NN1 thinking_NN1 ._. 
</s>
<s>
This_DD1 study_NN1 clearly_RR show_VV0 a_AT1 strong_JJ relationship_NN1 between_II these_DD2 strategies_NN2 ,_, that_DD1 suggests_VVZ the_AT combined_JJ used_JJ of_IO both_DB2 perspectives_NN2 each_DD1 in_II its_APPGE own_DA respective_JJ stage_NN1 is_VBZ appropriate_JJ ._. 
</s>
<s>
Thus_RR ,_, companies_NN2 who_PNQS adapt_VV0 both_RR design_VV0 thinking_VVG in_II their_APPGE product_NN1 development_NN1 and_CC interaction_NN1 with_IW customers_NN2 on_II a_AT1 product_NN1 level_NN1 ,_, while_CS embracing_VVG a_AT1 service_NN1 marketing_NN1 logic_NN1 throughout_II its_APPGE organization_NN1 and_CC market_VV0 communication_NN1 will_VM pass_VVI the_AT test_NN1 of_IO the_AT consumers_NN2 ,_, will_VM be_VBI the_AT most_RGT desired_JJ brands_NN2 and_CC be_VBI the_AT winners_NN2 of_IO the_AT future_NN1 ._. 
</s>
<s>
The_AT author_NN1 suggests_VVZ more_RGR thorough_JJ research_NN1 in_II this_DD1 are_VBR be_VBI conducted_VVN in_BCL21 order_BCL22 to_TO establish_VVI the_AT relevance_NN1 of_IO each_DD1 component_NN1 and_CC determine_VV0 the_AT relationship_NN1 of_IO the_AT two_MC co-existing_VVG as_RG equally_RR important_JJ components_NN2 for_IF business_NN1 success_NN1 ._. 
</s>
