<s>
Differences_NN2 between_II Finland_NP1 and_CC Austria_NP1 among_II the_AT political_JJ and_CC economical_JJ landscape_NN1 1_MC1 ._. 
</s>
<s>
Introduction_NN1 Recently_RR ,_, there_EX has_VHZ been_VBN wide_JJ interest_NN1 in_II the_AT connection_NN1 between_II politics_NN1 and_CC business_NN1 in_II Austria_NP1 ._. 
</s>
<s>
Many_DA2 politicians_NN2 ,_, who_PNQS had_VHD important_JJ political_JJ positions_NN2 ten_MC years_NNT2 ago_RA ,_, are_VBR now_RT suspected_VVN to_TO have_VHI been_VBN corruptive_JJ during_II their_APPGE term_NN1 of_IO office_NN1 ._. 
</s>
<s>
Due_II21 to_II22 the_AT reason_NN1 ,_, that_CST I_PPIS1 am_VBM exchange_NN1 student_NN1 in_II Finland_NP1 at_II the_AT moment_NN1 ,_, I_PPIS1 started_VVD to_TO scrutinize_VVI the_AT way_NN1 politics_NN1 are_VBR made_VVN in_II Finland_NP1 ._. 
</s>
<s>
There_EX is_VBZ much_DA1 evidence_NN1 to_TO support_VVI the_AT hypothesis_NN1 ,_, that_DD1 corruption_NN1 is_VBZ spread_VVN wider_JJR among_II the_AT southern_JJ parts_NN2 of_IO Europe_NP1 than_CSN for_REX21 instance_REX22 the_AT Scandinavian_JJ area_NN1 ._. 
</s>
<s>
The_AT Corruption_NN1 Perceptions_NN2 Index_VV0 2010_MC of_IO Transparency_NN1 International_JJ shows_NN2 ,_, that_CST Finland_NP1 is_VBZ getting_VVG the_AT best_JJT grade_NN1 for_IF its_APPGE transparency_NN1 ,_, whereas_CS Austria_NP1 is_VBZ valued_VVN two_MC categories_NN2 lower_VV0 ._. 
</s>
<s>
(_( Transparency_NN1 International_JJ ,_, 2012_MC )_) But_CCB also_RR data_NN have_VH0 been_VBN presented_VVN in_II the_AT literature_NN1 ,_, explained_VVN by_II Richard_NP1 D._NP1 Lewis_NP1 that_CST Finns_NN2 open_VV0 and_CC conduct_VV0 meetings_NN2 with_IW the_AT premise_NN1 that_CST stating_VVG the_AT truth_NN1 ,_, whether_CSW pleasant_JJ or_CC not_XX ,_, is_VBZ the_AT best_JJT way_NN1 to_TO achieve_VVI a_AT1 successful_JJ outcome_NN1 ._. 
</s>
<s>
Furthermore_RR he_PPHS1 points_VVZ out_RP that_CST Finns_NN2 are_VBR individualists_NN2 ,_, but_CCB in_II Finland_NP1 individualism_NN1 does_VDZ not_XX involve_VVI breaking_VVG the_AT law._NNU (_( Lewis_NP1 R._NP1 D._NP1 ,_, 2004_MC )_) Nevertheless_RR the_AT cultural_JJ and_CC ethical_JJ differences_NN2 between_II these_DD2 two_MC countries_NN2 and_CC their_APPGE effects_NN2 on_II politics_NN1 ,_, as_II31 well_II32 as_II33 the_AT field_NN1 of_IO business_NN1 ,_, require_VV0 further_JJR investigation_NN1 ._. 
</s>
<s>
Business_NN1 and_CC politics_NN1 are_VBR closely_RR linked_VVN to_II each_PPX221 other_PPX222 in_II Austria_NP1 ,_, and_CC the_AT higher_JJR willingness_NN1 of_IO politicians_NN2 to_TO act_VVI not_XX completely_RR legally_RR ,_, shows_VVZ the_AT importance_NN1 of_IO investigating_VVG reasons_NN2 for_IF this_DD1 behaviour_NN1 ._. 
</s>
<s>
Despite_II the_AT importance_NN1 of_IO cultural_JJ differences_NN2 between_II countries_NN2 ,_, moderate_JJ research_NN1 has_VHZ been_VBN done_VDN which_DDQ focuses_VVZ on_II the_AT effects_NN2 of_IO these_DD2 differences_NN2 on_II the_AT political_JJ landscape_NN1 ._. 
</s>
<s>
Therefore_RR the_AT questions_NN2 remain_VV0 :_: How_RRQ does_VDZ the_AT culture_NN1 of_IO a_AT1 country_NN1 influence_VV0 the_AT political_JJ landscape_NN1 ?_? 
</s>
<s>
As_II31 well_II32 as_II33 :_: Why_RRQ is_VBZ it_PPH1 common_JJ in_II Finland_NP1 ,_, to_TO have_VHI more_DAR trust_NN1 into_II the_AT political_JJ system_NN1 and_CC their_APPGE politicians_NN2 ?_? 
</s>
<s>
My_APPGE paper_NN1 evaluates_VVZ the_AT differences_NN2 between_II Finland_NP1 and_CC Austria_NP1 concerning_II the_AT culture_NN1 and_CC ethics_NN ._. 
</s>
<s>
After_II knowing_VVG the_AT main_JJ differences_NN2 ,_, I_PPIS1 will_VM focus_VVI on_RP ,_, how_RRQ these_DD2 differences_NN2 are_VBR causing_VVG the_AT problems_NN2 the_AT Austrian_JJ political_JJ system_NN1 is_VBZ suffering_VVG at_II the_AT moment_NN1 and_CC why_RRQ Finland_NP1 is_VBZ in_II so_RG many_DA2 indexes_NN2 on_II the_AT first_MD place_NN1 ._. 
</s>
<s>
This_DD1 paper_NN1 hopes_VVZ to_TO show_VVI that_CST it_PPH1 is_VBZ doable_JJ to_TO change_VVI parts_NN2 of_IO the_AT political_JJ system_NN1 of_IO a_AT1 country_NN1 as_II31 well_II32 as_II33 some_DD ethics_NN in_BCL21 order_BCL22 to_TO make_VVI politics_NN1 more_RGR trustworthy_JJ and_CC to_TO increase_VVI the_AT general_JJ welfare_NN1 among_II the_AT citizens_NN2 ._. 
</s>
<s>
2_MC ._. 
</s>
<s>
The_AT political_JJ system_NN1 in_II Finland_NP1 In_II March_NPM1 2000_MC Finland_NP1 rewrote_VV0 its_APPGE constitution_NN1 ,_, which_DDQ had_VHD effects_NN2 on_II the_AT power_NN1 of_IO the_AT president_NN1 ._. 
</s>
<s>
From_II that_DD1 time_NNT1 on_RP ,_, Finland_NP1 has_VHZ a_AT1 mixed_JJ system_NN1 with_IW executive_NN1 powers_NN2 divided_VVN between_II the_AT president_NN1 ,_, who_PNQS has_VHZ primary_JJ responsibility_NN1 for_IF national_JJ security_NN1 and_CC foreign_JJ affairs_NN2 ,_, and_CC the_AT prime_JJ minister_NN1 ,_, who_PNQS has_VHZ primary_JJ responsibility_NN1 for_IF all_DB other_JJ areas_NN2 ,_, including_II European_JJ Union_NN1 (_( EU_NP1 )_) issues._NNU (_( EBSCO_NP1 ,_, 2010_MC )_) Since_II March_NPM1 2012_MC the_AT president_NN1 of_IO Finland_NP1 is_VBZ Sauli_JJ Niinist_NN1 ,_, which_DDQ is_VBZ directly_RR elected_VVN by_II the_AT citizens_NN2 for_IF six_MC years_NNT2 and_CC for_IF a_AT1 maximum_NN1 of_IO two_MC following_RA consecutive_JJ terms_NN2 ._. 
</s>
<s>
The_AT 200_MC members_NN2 of_IO the_AT unicameral_JJ parliament_NN1 are_VBR elected_VVN for_IF four_MC years_NNT2 and_CC their_APPGE head_NN1 is_VBZ the_AT prime_JJ minister_NN1 ,_, who_PNQS is_VBZ currently_RR Jyrki_JJ Katainen_NN1 ._. 
</s>
<s>
Finland_NP1 was_VBDZ the_AT first_MD country_NN1 worldwide_RL ,_, which_DDQ introduced_VVD the_AT female_JJ suffrage_NN1 in_II 1906_MC ._. 
</s>
<s>
From_II that_DD1 time_NNT1 on_RP ,_, the_AT parliament_NN1 has_VHZ been_VBN dominated_VVN by_II three_MC main_JJ parties_NN2 ;_; the_AT Centre_NN1 Party_NN1 ,_, the_AT National_JJ Coalition_NN1 Party_NN1 and_CC the_AT Social_JJ Democrats_NN2 ._. 
</s>
<s>
But_CCB during_II the_AT elections_NN2 in_II 2011_MC the_AT increasing_JJ amounts_NN2 of_IO votes_NN2 for_IF the_AT True_JJ Finns_NN2 Party_NN1 ,_, showed_VVD a_AT1 clear_JJ step_NN1 to_II the_AT right_NN1 ._. 
</s>
<s>
The_AT True_JJ Finns_NN2 are_VBR now_RT on_II the_AT third_MD place_NN1 with_IW about_RG 34_MC %_NNU of_IO votes_NN2 ._. 
</s>
<s>
(_( Wikipedia_NN1 ,_, 2012_MC )_) 3_MC ._. 
</s>
<s>
The_AT political_JJ system_NN1 in_II Austria_NP1 The_AT head_NN1 of_IO state_NN1 in_II Austria_NP1 is_VBZ the_AT Federal_JJ President_NN1 ,_, who_PNQS is_VBZ Heinz_NP1 Fischer_NP1 at_II the_AT moment_NN1 ._. 
</s>
<s>
He_PPHS1 is_VBZ elected_VVN directly_RR from_II the_AT citizens_NN2 and_CC gets_VVZ elected_VVN for_IF six_MC years_NNT2 for_IF maximum_NN1 two_MC times_NNT2 ._. 
</s>
<s>
The_AT president_NN1 also_RR appoints_VVZ the_AT chairman_NN1 of_IO the_AT Federal_JJ Government_NN1 ,_, which_DDQ is_VBZ called_VVN the_AT Federal_JJ Chancellor_NN1 ,_, and_CC currently_RR Werner_NP1 Faymann_NP1 ._. 
</s>
<s>
In_II Austria_NP1 the_AT executive_NN1 power_NN1 is_VBZ exercised_VVN by_II local_JJ and_CC federal_JJ governments_NN2 ._. 
</s>
<s>
Federal_JJ legislative_JJ power_NN1 is_VBZ made_VVN by_II two_MC chambers_NN2 of_IO parliament_NN1 ,_, namely_REX the_AT National_JJ Council_NN1 and_CC the_AT Federal_JJ Council_NN1 ._. 
</s>
<s>
The_AT more_RGR dominant_JJ chamber_NN1 is_VBZ the_AT National_JJ Council_NN1 which_DDQ has_VHZ 183_MC members_NN2 and_CC is_VBZ elected_VVN for_IF five_MC years_NNT2 by_II proportional_JJ representation_NN1 ._. 
</s>
<s>
(_( Wikipedia_NN1 ,_, 2012_MC )_) Since_II 1949_MC two_MC main_JJ parties_NN2 are_VBR dominant_JJ among_II Austrias_NP2 political_JJ landscape_NN1 :_: the_AT conservative_JJ Austrian_JJ People_NN 's_GE Party_NN1 (_( VP_NP1 )_) and_CC the_AT center-left_NN1 Social_JJ Democratic_JJ Party_NN1 of_IO Austria_NP1 (_( SP_NN1 )_) ._. 
</s>
<s>
Also_RR in_II Austria_NP1 there_EX is_VBZ a_AT1 right_JJ wing_NN1 party_NN1 which_DDQ gained_VVD its_APPGE votes_NN2 over_II the_AT years_NNT2 ._. 
</s>
<s>
It_PPH1 is_VBZ called_VVN Freedom_NN1 Party_NN1 (_( FP_NP1 )_) and_CC started_VVD to_TO become_VVI more_RGR popular_JJ when_CS Jrg_NP1 Haider_NP1 took_VVD over_II the_AT leadership_NN1 of_IO the_AT party_NN1 in_II 1986_MC until_CS they_PPHS2 got_VVD 27_MC %_NNU during_II the_AT elections_NN2 in_II 1999_MC ._. 
</s>
<s>
After_CS a_AT1 reduce_VV0 in_II 2002_MC to_II 10_MC %_NNU ,_, they_PPHS2 could_VM still_RR increase_VVI their_APPGE votes_NN2 again_RT in_II 2008_MC to_II 17.5_MC %_NNU ._. 
</s>
<s>
(_( Wikipedia_NN1 ,_, 2012_MC )_) 4_MC ._. 
</s>
<s>
How_RRQ are_VBR politics_NN1 and_CC business_NN1 linked_VVN to_II each_PPX221 other_PPX222 in_II these_DD2 countries_NN2 ?_? 4.1_MC ._. 
</s>
<s>
What_DDQ is_VBZ corruption_NN1 ?_? 
</s>
<s>
A_AT1 simple_JJ definition_NN1 of_IO corruption_NN1 is_VBZ the_AT use_NN1 of_IO political_JJ power_NN1 for_IF private_JJ gain_NN1 ._. 
</s>
<s>
Or_CC defined_VVN by_II Shahabuddin_NP1 Syed_NP1 :_: corruption_NN1 is_VBZ the_AT abuse_NN1 of_IO public_JJ offices_NN2 by_II public_JJ officials_NN2 in_II which_DDQ they_PPHS2 accept_VV0 or_CC demand_NN1 bribes_VVZ in_II31 return_II32 for_II33 favors_NN2 such_II21 as_II22 to_TO perform_VVI their_APPGE official_JJ duties_NN2 expeditiously_RR or_CC to_TO skew_VVI laws_NN2 in_II31 favor_II32 of_II33 the_AT giver._NNU Shahabuddin_NN1 also_RR describes_VVZ that_CST there_EX are_VBR two_MC main_JJ conditions_NN2 which_DDQ either_RR encourage_VV0 or_CC discourage_VV0 corruption_NN1 ._. 
</s>
<s>
Firstly_RR it_PPH1 depends_VVZ on_II how_RGQ much_DA1 punishment_NN1 is_VBZ given_VVN by_II the_AT law_NN1 of_IO a_AT1 society_NN1 for_IF abusing_VVG political_JJ power_NN1 and_CC secondly_RR the_AT amount_NN1 of_IO cultural_JJ acceptance_NN1 in_II a_AT1 society_NN1 ._. 
</s>
<s>
But_CCB in_BCL21 order_BCL22 to_TO understand_VVI how_RRQ these_DD2 conditions_NN2 are_VBR creating_VVG environments_NN2 in_II which_DDQ corruption_NN1 is_VBZ possible_JJ ,_, it_PPH1 is_VBZ important_JJ to_TO take_VVI a_AT1 look_NN1 on_II what_DDQ is_VBZ influencing_VVG these_DD2 conditions_NN2 ._. 
</s>
<s>
(_( Shahabuddin_NN1 ,_, 2007_MC )_) The_AT amount_NN1 of_IO income_NN1 in_II a_AT1 country_NN1 is_VBZ one_MC1 of_IO the_AT first_MD incentives_NN2 for_IF the_AT amount_NN1 of_IO corruption_NN1 ._. 
</s>
<s>
People_NN with_IW low_JJ incomes_NN2 have_VH0 higher_JJR marginal_JJ value_NN1 for_IF additional_JJ income._NNU Countries_NN2 with_IW low_JJ income_NN1 levels_NN2 give_VV0 government_NN1 jobs_NN2 a_AT1 high_JJ potential_NN1 for_IF earning_VVG extra_JJ money_NN1 ._. 
</s>
<s>
Nevertheless_RR ,_, just_RR paying_VVG people_NN in_II governmental_JJ positions_NN2 a_AT1 higher_JJR amount_NN1 of_IO money_NN1 does_VDZ not_XX lower_VVI the_AT risk_NN1 of_IO corrupting_VVG ._. 
</s>
<s>
The_AT punishment_NN1 for_IF doing_VDG so_RR has_VHZ to_TO be_VBI high_JJ in_II these_DD2 countries_NN2 and_CC societies_NN2 as_RR21 well_RR22 ,_, otherwise_RR the_AT potential_NN1 of_IO corruption_NN1 is_VBZ staying_VVG at_II a_AT1 high_JJ level_NN1 ._. 
</s>
<s>
(_( Shahabuddin_NN1 ,_, 2007_MC )_) But_CCB also_RR economical_JJ theories_NN2 for_IF corruption_NN1 can_VM be_VBI found_VVN ._. 
</s>
<s>
According_II21 to_II22 Scott_NP1 ,_, the_AT greater_JJR the_AT size_NN1 of_IO a_AT1 public_JJ sector_NN1 ,_, the_AT greater_JJR its_APPGE potential_NN1 for_IF corruption._NNU But_CCB also_RR the_AT degree_NN1 of_IO governmental_JJ control_NN1 of_IO economic_JJ activity_NN1 is_VBZ related_VVN to_II corruption_NN1 ._. 
</s>
<s>
If_CS economies_NN2 are_VBR highly_RR controlled_VVN ,_, the_AT people_NN who_PNQS are_VBR taking_VVG governmental_JJ jobs_NN2 are_VBR making_VVG nearly_RR all_DB economic_JJ decisions_NN2 ._. 
</s>
<s>
Their_APPGE decisions_NN2 will_VM have_VHI the_AT power_NN1 in_BCL21 order_BCL22 to_TO say_VVI who_PNQS has_VHZ economic_JJ success_NN1 ._. 
</s>
<s>
Of_RR21 course_RR22 the_AT result_NN1 is_VBZ ,_, that_DD1 bribery_NN1 makes_VVZ it_PPH1 possible_JJ for_IF citizens_NN2 to_TO achieve_VVI higher_JJR economic_JJ success_NN1 and_CC wealth_NN1 ._. 
</s>
<s>
Additionally_RR to_II that_DD1 Levin_NN1 and_CC Renelt_NP1 ,_, and_CC Barro_NP1 found_VVD a_AT1 strong_JJ relationship_NN1 between_II school_NN1 enrollment_NN1 and_CC educational_JJ attainment_NN1 and_CC economic_JJ growth_NN1 ._. 
</s>
<s>
An_AT1 educated_JJ population_NN1 results_NN2 in_II higher_JJR economic_JJ growth_NN1 that_CST causes_VVZ equal_JJ distribution_NN1 of_IO resources_NN2 among_II people._NNU (_( Shahabuddin_NP1 ,_, 2007_MC )_) 4.2_MC ._. 
</s>
<s>
Lobbyism_NN1 Interaction_NN1 between_II business_NN1 and_CC politics_NN1 The_AT etymology_NN1 of_IO the_AT word_NN1 lobbyism_NN1 comes_VVZ from_II the_AT word_NN1 lobby_NN1 ,_, but_CCB in_RR21 particular_RR22 the_AT lobbies_NN2 or_CC hallways_NN2 of_IO the_AT House_NN1 of_IO Parliament_NN1 are_VBR meant_VVN ._. 
</s>
<s>
Dictionary_NN1 definitions_NN2 are_VBR Lobbying_VVG is_VBZ a_AT1 form_NN1 of_IO advocacy_NN1 with_IW the_AT intention_NN1 of_IO influencing_VVG decisions_NN2 made_VVN by_II the_AT government_NN1 by_II individuals_NN2 or_CC more_RGR usually_RR by_II Lobby_NN1 groups_NN2 ;_; it_PPH1 includes_VVZ all_DB attempts_NN2 to_TO influence_VVI legislators_NN2 and_CC officials_NN2 ,_, whether_CSW by_II other_JJ legislators_NN2 ,_, constituents_NN2 ,_, or_CC organized_VVD groups._NNU (_( Wikipedia_NP1 ,_, 2012_MC )_) 4.3_MC ._. 
</s>
<s>
The_AT situation_NN1 in_II Finland_NP1 4.4_MC ._. 
</s>
<s>
The_AT situation_NN1 in_II Austria_NP1 5_MC Effects_NN2 of_IO cultural_JJ differences_NN2 on_II the_AT political_JJ and_CC economical_JJ landscape_NN1 6_MC Conclusion_NN1 
</s>
