<s>
Barriers_NN2 for_IF coordination_NN1 in_II Humanitarian_JJ Logistics_NN1 1.0_MC Introduction_NN1 and_CC problem_NN1 definition_NN1 The_AT field_NN1 of_IO humanitarian_JJ logistics_NN1 is_VBZ a_AT1 very_RG relevant_JJ subject_NN1 in_II todays_NN2 world_NN1 as_CSA both_RR natural_JJ and_CC man-made_JJ disasters_NN2 are_VBR becoming_VVG more_RGR frequent_JJ ,_, the_AT total_JJ number_NN1 of_IO natural_JJ disasters_NN2 has_VHZ multiplied_VVN six-_JJ fold_NN1 during_II the_AT last_MD 30_MC years_NNT2 (_( Schulz_NP1 &;_NULL Blecken_NP1 ,_, 2010_MC ;_; CRED_NP1 ,_, 2007-2008_MCMC )_) ._. 
</s>
<s>
The_AT effectiveness_NN1 of_IO logistics_NN1 activities_NN2 in_II disaster_NN1 areas_NN2 relies_VVZ on_II several_DA2 different_JJ things_NN2 ._. 
</s>
<s>
The_AT level_NN1 of_IO preparation_NN1 ,_, expertise_NN1 ,_, materials_NN2 ,_, and_CC finance_NN1 are_VBR all_DB areas_NN2 on_II which_DDQ a_AT1 humanitarian_JJ aid_NN1 operation_NN1 can_VM stand_VVI or_CC fall_VVI ._. 
</s>
<s>
The_AT field_NN1 has_VHZ also_RR caught_VVN the_AT researchers_NN2 eye_NN1 as_II the_AT agility_NN1 of_IO humanitarian_JJ logistics_NN1 is_VBZ considered_VVN to_TO be_VBI of_IO very_RG high_JJ standards_NN2 (_( Oloruntoba_NP1 &;_NULL Gray_NP1 ,_, 2006_MC )_) ._. 
</s>
<s>
This_DD1 agility_NN1 is_VBZ considered_VVN to_TO be_VBI the_AT result_NN1 of_IO constantly_RR dealing_VVG with_IW unpredictability_NN1 in_II operations_NN2 and_CC because_II21 of_II22 this_DD1 being_VBG very_RG responsive_JJ to_II disruptions_NN2 in_II the_AT supply_NN1 chain_NN1 ._. 
</s>
<s>
Despite_II this_DD1 agility_NN1 there_EX are_VBR several_DA2 major_JJ natural_JJ and_CC organizational_JJ barriers_NN2 that_CST hinder_VV0 humanitarian_JJ aid_NN1 operations_NN2 and_CC no_RGQV31 matter_RGQV32 how_RGQV33 well_RR prepared_VVN or_CC financed_VVD an_AT1 organization_NN1 is_VBZ ,_, the_AT overall_JJ functionality_NN1 still_RR depends_VVZ on_II the_AT level_NN1 of_IO coordination_NN1 between_II the_AT organizations_NN2 in_II the_AT relief_NN1 area_NN1 ._. 
</s>
<s>
There_EX are_VBR no_AT relief_NN1 organizations_NN2 that_CST can_VM single-handedly_RR respond_VVI effectively_RR to_II a_AT1 major_JJ disaster_NN1 ;_; therefore_RR the_AT coordination_NN1 both_RR pre-disaster_JJ as_II31 well_II32 as_II33 post-disaster_NN1 is_VBZ vital_JJ for_IF the_AT effectiveness_NN1 of_IO the_AT operation_NN1 ._. 
</s>
<s>
Humanitarian_JJ organizations_NN2 are_VBR also_RR constantly_RR faced_VVN with_IW scarce_JJ resources_NN2 ,_, little_JJ knowledge_NN1 flow_NN1 and_CC uncertainty_NN1 of_IO the_AT operation_NN1 ,_, which_DDQ further_RRR motivates_VVZ the_AT aim_NN1 for_IF coordination_NN1 between_II organizations_NN2 ._. 
</s>
<s>
(_( Balcik_NN1 ,_, Beamon_NP1 ,_, Krejci_NP1 ,_, Muramatsu_NP1 ,_, and_CC Ramirez_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
The_AT business_NN1 sector_NN1 has_VHZ also_RR taken_VVN an_AT1 interest_NN1 in_II how_RGQ humanitarian_JJ organizations_NN2 tend_VV0 to_II their_APPGE logistics_NN1 operations_NN2 ,_, as_CSA a_AT1 major_JJ disaster_NN1 might_VM disrupt_VVI the_AT global_JJ supply_NN1 chains_NN2 that_CST many_DA2 multinational_JJ corporations_NN2 have_VH0 today_RT ._. 
</s>
<s>
This_DD1 further_RRR motivates_VVZ this_DD1 research_NN1 as_CSA it_PPH1 is_VBZ in_II both_DB2 private_JJ corporations_NN2 as_II31 well_II32 as_II33 humanitarian_JJ organizations_NN2 interest_NN1 to_TO effectively_RR outline_VVI the_AT existing_JJ barriers_NN2 to_II coordination_NN1 ._. 
</s>
<s>
1.1_MC Aim_NN1 of_IO research_NN1 :_: The_AT difficulty_NN1 to_II effective_JJ coordination_NN1 is_VBZ by_RR31 no_RR32 means_RR33 a_AT1 new_JJ phenomenon_NN1 in_II the_AT humanitarian_JJ aid_NN1 community_NN1 ,_, there_EX are_VBR several_DA2 examples_NN2 concerning_II material_NN1 scarcity_NN1 ,_, ineffective_JJ knowledge_NN1 or_CC information_NN1 flow_NN1 ,_, and_CC differences_NN2 in_II goals_NN2 and_CC perspectives_NN2 (_( Balcik_NP1 et_RA21 al._RA22 ,_, 2010_MC )_) ._. 
</s>
<s>
This_DD1 study_NN1 seeks_VVZ to_TO outline_VVI the_AT logistical_JJ aspects_NN2 of_IO relief_NN1 operations_NN2 in_II todays_NN2 disaster_NN1 prone_JJ world_NN1 ._. 
</s>
<s>
In_II31 light_II32 of_II33 the_AT difficulties_NN2 with_IW achieving_VVG well_RR coordinated_JJ operations_NN2 ,_, this_DD1 paper_NN1 seeks_VVZ to_TO further_RRR outline_VVI the_AT major_JJ logistical_JJ barriers_NN2 that_CST relief_NN1 organizations_NN2 face_VV0 when_CS cooperating_VVG alongside_II other_JJ organizations_NN2 in_II relief_NN1 areas_NN2 ._. 
</s>
<s>
While_CS humanitarian_JJ aid_NN1 can_VM be_VBI researched_VVN as_II a_AT1 field_NN1 alone_RR ,_, this_DD1 paper_NN1 will_VM focus_VVI on_II the_AT logistical_JJ aspects_NN2 connected_VVN to_II this_DD1 field_NN1 and_CC not_XX as_RG such_DA to_II the_AT actual_JJ humanitarian_JJ aid_NN1 that_CST is_VBZ given_VVN ._. 
</s>
<s>
Hence_RR the_AT barriers_NN2 in_II humanitarian_JJ aid_NN1 operations_NN2 will_VM only_RR be_VBI measured_VVN from_II a_AT1 logistical_JJ point_NN1 of_IO view_NN1 ._. 
</s>
<s>
1.2_MC Structure_NN1 This_DD1 study_NN1 is_VBZ structured_VVN as_CSA follows_VVZ ._. 
</s>
<s>
First_MD ,_, the_AT area_NN1 of_IO interest_NN1 is_VBZ introduced_VVN after_II which_DDQ the_AT major_JJ problems_NN2 are_VBR highlighted_VVN and_CC discussed_VVN ._. 
</s>
<s>
Secondly_RR ,_, the_AT theoretical_JJ framework_NN1 and_CC the_AT data_NN analysis_NN1 tools_NN2 are_VBR introduced_VVN ,_, being_VBG followed_VVN by_II the_AT actual_JJ research_NN1 ._. 
</s>
<s>
The_AT study_NN1 concludes_VVZ with_IW an_AT1 analysis_NN1 of_IO the_AT findings_NN2 from_II the_AT research_NN1 and_CC the_AT following_JJ conclusions_NN2 ._. 
</s>
<s>
The_AT study_NN1 is_VBZ concluded_VVN with_IW a_AT1 discussion_NN1 of_IO the_AT findings_NN2 and_CC possible_JJ future_JJ development_NN1 measures_NN2 concerning_II the_AT area_NN1 of_IO interest_NN1 ._. 
</s>
<s>
1.3_MC Data_NN collection_NN1 :_: The_AT data_NN will_VM be_VBI collected_VVN through_II examining_VVG articles_NN2 discussing_VVG humanitarian_JJ aid_NN1 logistics_NN1 international_JJ relief_NN1 operations_NN2 ._. 
</s>
<s>
From_II these_DD2 articles_NN2 a_AT1 literature_NN1 review_NN1 will_VM be_VBI conducted_VVN and_CC the_AT logistical_JJ barriers_NN2 highlighted_VVD ._. 
</s>
<s>
These_DD2 barriers_NN2 will_VM then_RT be_VBI presented_VVN and_CC discussed_VVN from_II a_AT1 logistical_JJ point_NN1 of_IO view_NN1 in_BCL21 order_BCL22 to_TO convey_VVI what_DDQ impact_NN1 they_PPHS2 have_VH0 on_II the_AT relief_NN1 operations_NN2 ._. 
</s>
<s>
2.0_MC Method_NN1 and_CC theory_NN1 discussion_NN1 2.1_MC Methodology_NN1 A_ZZ1 qualitative_JJ research_NN1 approach_NN1 will_VM be_VBI used_VVN in_BCL21 order_BCL22 to_TO discuss_VVI and_CC contemplate_VVI on_II the_AT barriers_NN2 in_II question_NN1 ._. 
</s>
<s>
Applying_VVG stakeholder_NN1 theory_NN1 on_II the_AT barriers_NN2 found_VVN in_II the_AT logistics_NN1 literature_NN1 ,_, will_VM convey_VVI any_DD logistical_JJ implications_NN2 the_AT barriers_NN2 have_VH0 on_II relief_NN1 operations_NN2 ._. 
</s>
<s>
Stakeholder_VV0 theory_NN1 takes_VVZ into_II account_NN1 the_AT different_JJ stakeholders_NN2 ,_, e.g._REX people_NN that_CST an_AT1 organization_NN1 affects_VVZ or_CC is_VBZ affected_VVN by_II ._. 
</s>
<s>
It_PPH1 is_VBZ further_RRR suitable_JJ for_IF studying_VVG humanitarian_JJ logistics_NN1 as_CSA it_PPH1 examines_VVZ a_AT1 particular_JJ organization_NN1 not_XX from_II its_APPGE profit_NN1 seeking_VVG potential_JJ but_CCB from_II its_APPGE implications_NN2 on_II the_AT people_NN that_CST it_PPH1 works_VVZ with_IW ._. 
</s>
<s>
(_( Freeman_NN1 &;_NULL McVea_NP1 ,_, 1994_MC )_) 2.2_MC Literature_NN1 review_NN1 :_: The_AT literature_NN1 review_NN1 that_CST will_VM function_VVI as_II a_AT1 basis_NN1 for_IF this_DD1 research_NN1 is_VBZ provided_VVN mainly_RR from_II academic_JJ articles_NN2 discussing_VVG humanitarian_JJ logistics_NN1 operations_NN2 ._. 
</s>
<s>
In_II31 addition_II32 to_II33 this_DD1 ,_, lectures_NN2 and_CC guest-lectures_NN2 from_II the_AT course_NN1 Humanitarian_JJ Logistics_NN1 by_II Gyngyi_NP1 Kovacs_NP2 (_( 2011_MC )_) ,_, also_RR discussing_VVG the_AT aforementioned_JJ subject_NN1 is_VBZ also_RR used_VVN ._. 
</s>
<s>
The_AT academic_JJ articles_NN2 are_VBR in_II turn_NN1 gathered_VVN from_II a_AT1 number_NN1 of_IO academic_JJ journals_NN2 focusing_VVG on_II the_AT area_NN1 of_IO interest_NN1 ._. 
</s>
<s>
Primarily_RR the_AT following_JJ journals_NN2 have_VH0 been_VBN used_VVN ;_; 1_MC1 ._. 
</s>
<s>
The_AT Journal_NN1 of_IO Physical_JJ Distribution_NN1 and_CC Logistics_NN1 Management_NN1 2_MC ._. 
</s>
<s>
International_JJ Journal_NN1 of_IO Logistics_NN1 :_: Research_NN1 and_CC Applications_NN2 3_MC ._. 
</s>
<s>
Supply_VV0 Chain_NN1 Management_NN1 4_MC ._. 
</s>
<s>
International_JJ Journal_NN1 of_IO Production_NN1 Economics_NN1 5_MC ._. 
</s>
<s>
Journal_NN1 of_IO the_AT Operational_JJ Research_NN1 Society_NN1 The_AT guest_NN1 lecturers_NN2 in_II question_NN1 are_VBR Susanne_NP1 Hertz_NNU from_II Jnkping_VVG International_JJ Business_NN1 School_NN1 ,_, Sweden_NP1 ,_, and_CC Paul_NP1 D._NP1 Larson_NP1 from_II the_AT University_NN1 of_IO Manitoba_NP1 ,_, Canada_NP1 ._. 
</s>
<s>
2.3_MC Definitions_NN2 In_BCL21 order_BCL22 for_IF this_DD1 study_NN1 to_TO be_VBI more_RGR comprehensible_JJ ,_, some_DD key_JJ aspects_NN2 should_VM be_VBI properly_RR defined_VVN and_CC discussed_VVN ._. 
</s>
<s>
2.3.1_MC Disaster_NN1 There_EX are_VBR several_DA2 definitions_NN2 as_II21 to_II22 what_DDQ a_AT1 disaster_NN1 is_VBZ ,_, and_CC entails_VVZ ._. 
</s>
<s>
van_NP1 Wassenhove_NP1 (_( 2006_MC )_) defines_VVZ a_AT1 disaster_NN1 as_II a_AT1 disruption_NN1 that_CST physically_RR affects_VVZ a_AT1 system_NN1 as_II a_AT1 whole_NN1 and_CC threatens_VVZ its_APPGE priorities_NN2 and_CC goals._NNU ,_, The_AT United_JJ Nations_NN2 International_JJ Strategy_NN1 for_IF Disaster_NN1 Reduction_NN1 (_( UN/ISDR_NP1 )_) defines_VVZ a_AT1 disaster_NN1 as_II :_: &lsqb;_( ._. 
</s>
<s>
._. ._. &rsqb;_) a_AT1 serious_JJ disruption_NN1 of_IO the_AT functioning_NN1 of_IO society_NN1 ,_, posing_VVG a_AT1 significant_JJ ,_, widespread_JJ threat_NN1 to_II human_JJ life_NN1 ,_, health_NN1 ,_, property_NN1 or_CC the_AT environment_NN1 ,_, whether_CSW caused_VVN by_II accident_NN1 ,_, nature_NN1 or_CC human_JJ activity_NN1 ,_, and_CC whether_CSW developing_VVG suddenly_RR or_CC as_II a_AT1 result_NN1 of_IO complex_NN1 ,_, long-term_JJ processes_NN2 ._. 
</s>
<s>
This_DD1 definition_NN1 ,_, while_CS being_VBG somewhat_RR longer_JJR and_CC perhaps_RR more_RGR difficult_JJ to_TO comprehend_VVI is_VBZ however_RR more_RGR suitable_JJ for_IF this_DD1 study_NN1 as_CSA it_PPH1 highlights_VVZ the_AT fact_NN1 that_CST the_AT process_NN1 is_VBZ complex_JJ with_IW many_DA2 aspects_NN2 to_TO consider_VVI ._. 
</s>
<s>
Therefore_RR it_PPH1 is_VBZ the_AT definition_NN1 of_IO the_AT UN/ISDR_NP1 that_CST will_VM be_VBI used_VVN in_II this_DD1 study_NN1 ._. 
</s>
<s>
2.3.2_MC Humanitarian_JJ aid_NN1 organizations_NN2 As_CSA mentioned_VVN earlier_RRR ,_, some_DD challenges_NN2 linked_VVN to_II disaster_NN1 relief_NN1 logistics_NN1 are_VBR created_VVN by_II the_AT mere_JJ number_NN1 of_IO humanitarian_JJ aid_NN1 organizations_NN2 involved_VVD ,_, these_DD2 organizations_NN2 range_VV0 from_II supranational_JJ aid_NN1 agencies_NN2 and_CC governmental_JJ organizations_NN2 (_( GO_VV0 )_) to_II non-governmental_JJ organizations_NN2 (_( NGOs_NP2 )_) and_CC one-man_JJ non-governmental_JJ donors_NN2 ._. 
</s>
<s>
There_EX are_VBR also_RR big_JJ international_JJ non-governmental_JJ organizations_NN2 (_( BINGOs_NN2 )_) ._. 
</s>
<s>
These_DD2 organizations_NN2 differ_VV0 in_II scale_NN1 ,_, local_JJ presence_NN1 and_CC mandates_NN2 ,_, and_CC most_RGT importantly_RR speed_VV0 ._. 
</s>
<s>
The_AT larger_JJR a_AT1 humanitarian_JJ organization_NN1 is_VBZ the_AT slower_RRR its_APPGE supply_NN1 chain_NN1 will_VM function_VVI ._. 
</s>
<s>
(_( Kovcs_NP1 &;_NULL Spens_NP1 ,_, 2009_MC )_) ._. 
</s>
<s>
Almost_RR all_DB aid_NN1 organizations_NN2 function_VV0 accordingly_RR to_II some_DD form_NN1 of_IO pre-positioned_JJ principles_NN2 which_DDQ might_VM hinder_VVI them_PPHO2 from_II working_VVG together_RL with_IW other_JJ organizations_NN2 or_CC governments_NN2 ,_, as_CSA the_AT actions_NN2 of_IO these_DD2 partner_NN1 organizations_NN2 might_VM not_XX accord_VVI with_IW the_AT principles_NN2 ._. 
</s>
<s>
This_DD1 might_VM not_XX be_VBI considered_VVN as_CSA such_DA a_AT1 major_JJ barrier_NN1 ,_, but_CCB when_CS considering_CS21 that_CS22 the_AT major_JJ source_NN1 of_IO funds_NN2 for_IF these_DD2 organization_NN1 are_VBR based_VVN on_II donations_NN2 from_II governments_NN2 and_CC private_JJ individuals_NN2 ,_, that_CST are_VBR likeminded_VVN when_CS it_PPH1 comes_VVZ to_II these_DD2 principles_NN2 ,_, the_AT cooperative_JJ partner_NN1 of_IO an_AT1 individual_JJ humanitarian_JJ aid_NN1 organization_NN1 must_VM be_VBI chosen_VVN with_IW this_DD1 in_II mind_NN1 ._. 
</s>
<s>
(_( Kovcs_NP1 &;_NULL Spens_NP1 ,_, 2009_MC )_) 2.3.3_MC Beneficiaries_NN2 A_ZZ1 beneficiary_NN1 is_VBZ considered_VVN a_AT1 person_NN1 in_II31 need_II32 of_II33 urgent_JJ or_CC long-term_JJ humanitarian_JJ aid_NN1 in_II a_AT1 disaster_NN1 area_NN1 ._. 
</s>
<s>
The_AT beneficiary_NN1 can_VM be_VBI seen_VVN as_II the_AT equivalence_NN1 of_IO a_AT1 customer_NN1 in_II business_NN1 logistics_NN1 ,_, obviously_RR with_IW altering_VVG demands_NN2 and_CC needs_NN2 ._. 
</s>
<s>
(_( Kovcs_NP1 ,_, Lecture_NN1 ,_, 2011_MC )_) 2.3.4_MC Differing_JJ features_NN2 in_II Business_NN1 and_CC Humanitarian_JJ Logistics_NN1 Balcik_NN1 and_CC Beamon_NP1 (_( 2008_MC )_) identify_VV0 a_AT1 number_NN1 of_IO crucial_JJ characteristics_NN2 of_IO humanitarian_JJ logistics_NN1 that_CST differ_VV0 from_II business_NN1 logistics_NN1 ;_; the_AT unpredictability_NN1 of_IO demand_NN1 ,_, the_AT suddenness_NN1 of_IO the_AT demand_NN1 occurrence_NN1 ,_, the_AT high_JJ stakes_NN2 associated_VVN with_IW the_AT timeliness_NN1 of_IO delivery_NN1 ,_, and_CC the_AT lack_NN1 of_IO resources_NN2 ._. 
</s>
<s>
These_DD2 features_NN2 make_VV0 this_DD1 form_NN1 of_IO logistics_NN1 operations_NN2 very_RG difficult_JJ to_TO grasp_VVI in_II a_AT1 larger_JJR aspect_NN1 as_II the_AT number_NN1 of_IO actors_NN2 ,_, beneficiaries_NN2 and_CC materials_NN2 tend_VV0 to_TO blend_VVI together_RL into_II a_AT1 large_JJ entity_NN1 without_IW clear_JJ coordination_NN1 ._. 
</s>
<s>
When_CS comparing_VVG business_NN1 and_CC humanitarian_JJ logisticians_NN2 it_PPH1 is_VBZ fairly_RR obvious_JJ that_CST the_AT later_JJR ones_NN2 have_VH0 far_RG greater_JJR challenges_NN2 in_II collaboration_NN1 and_CC coordination_NN1 efforts_NN2 ._. 
</s>
<s>
The_AT great_JJ number_NN1 of_IO actors_NN2 involved_VVD ,_, both_RR international_JJ and_CC local_JJ ,_, all_DB with_IW their_APPGE own_DA agendas_NN2 and_CC ways_NN2 of_IO operating_NN1 ,_, pose_VV0 a_AT1 major_JJ barrier_NN1 ._. 
</s>
<s>
Relief_NN1 operations_NN2 are_VBR often_RR described_VVN and_CC criticized_VVN for_IF their_APPGE lack_NN1 of_IO collaboration_NN1 ,_, redundancies_NN2 and_CC duplicated_VVD efforts_NN2 and_CC materials_NN2 ._. 
</s>
<s>
(_( Larson_NN1 ,_, lecture_NN1 2011_MC )_) 2.3.5_MC Coordination_NN1 There_EX are_VBR several_DA2 definitions_NN2 for_IF coordination_NN1 ._. 
</s>
<s>
The_AT broadest_JJT and_CC also_RR most_RGT comprehensible_JJ definition_NN1 is_VBZ coordination_NN1 is_VBZ the_AT act_NN1 of_IO working_VVG together_RL (_( Malone_NP1 &;_NULL Crowston_NP1 ,_, 1991_MC )_) ._. 
</s>
<s>
The_AT coordination_NN1 aspect_NN1 in_II this_DD1 paper_NN1 is_VBZ considered_VVN as_II the_AT functional_JJ management_NN1 and_CC information_NN1 flow_NN1 within_II a_AT1 supply_NN1 chain_NN1 of_IO a_AT1 humanitarian_JJ organization_NN1 in_II a_AT1 relief_NN1 area_NN1 ._. 
</s>
<s>
Essentially_RR ,_, it_PPH1 is_VBZ the_AT act_NN1 of_IO all_DB the_AT involved_JJ organizations_NN2 working_VVG together_RL in_BCL21 order_BCL22 to_TO reach_VVI the_AT beneficiary_NN1 as_RG effectively_RR as_CSA possible_JJ ._. 
</s>
<s>
The_AT coordination_NN1 function_NN1 is_VBZ usually_RR managed_VVN by_II some_DD of_IO the_AT larger_JJR organizations_NN2 ,_, such_II21 as_II22 WFP_NP1 (_( which_DDQ specializes_VVZ on_II logistics_NN1 )_) or_CC UNICEF_NP1 ._. 
</s>
<s>
Coordination_NN1 must_VM not_XX only_RR be_VBI considered_VVN as_II the_AT obedience_NN1 of_IO orders_NN2 from_II the_AT smaller_JJR humanitarian_JJ organizations_NN2 ,_, but_CCB rather_RR the_AT pro-active_JJ behavior_NN1 of_IO these_DD2 organizations_NN2 with_IW an_AT1 extensive_JJ information_NN1 flow_NN1 between_II the_AT larger_JJR organizations_NN2 and_CC the_AT smaller_JJR ones_NN2 ._. 
</s>
<s>
Some_DD direct_JJ benefits_NN2 from_II effective_JJ coordination_NN1 is_VBZ ;_; cost_VV0 reductions_NN2 in_II purchasing_NN1 of_IO material_NN1 ,_, risk_NN1 reduction_NN1 ,_, access_NN1 to_II resources_NN2 ,_, and_CC knowledge/learning_NN1 sharing_VVG ._. 
</s>
<s>
3.0_MC Theoretical_JJ framework_NN1 3.1_MC Stakeholder_NP1 theory_NN1 Stakeholder_NN1 theory_NN1 is_VBZ originally_RR an_AT1 organizational_JJ management_NN1 theory_NN1 that_CST addresses_VVZ the_AT need_NN1 for_IF business_NN1 ethics_NN ,_, morals_NN2 and_CC company_NN1 values_NN2 in_II effective_JJ management_NN1 of_IO an_AT1 organization_NN1 ._. 
</s>
<s>
The_AT focus_NN1 of_IO stakeholder_NN1 theory_NN1 is_VBZ basically_RR based_VVN on_II two_MC main_JJ questions_NN2 ._. 
</s>
<s>
First_MD the_AT theory_NN1 questions_NN2 the_AT purpose_NN1 of_IO the_AT firm_NN1 or_CC organization_NN1 ;_; this_DD1 gives_VVZ incentive_NN1 for_IF the_AT organization_NN1 to_TO pursue_VVI its_APPGE goals_NN2 as_CSA they_PPHS2 have_VH0 been_VBN outlined_VVN ._. 
</s>
<s>
Secondly_RR ,_, the_AT theory_NN1 questions_NN2 what_DDQ responsibility_NN1 the_AT management_NN1 has_VHZ to_II the_AT organizations_NN2 stakeholders_NN2 ;_; this_DD1 in_II turn_NN1 motivates_VVZ the_AT management_NN1 to_TO manage_VVI the_AT organization_NN1 according_II21 to_II22 the_AT established_JJ principles_NN2 (_( Freeman_NN1 ,_, Wicks_NP2 &;_NULL Parmar_NN1 ,_, 2004_MC )_) ._. 
</s>
<s>
The_AT stakeholder_NN1 theory_NN1 is_VBZ applied_VVN to_II humanitarian_JJ logistics_NN1 in_II the_AT sense_NN1 where_CS the_AT individual_JJ organization_NN1 must_VM consider_VVI all_DB its_APPGE stakeholders_NN2 when_CS making_VVG decisions_NN2 on_II cooperation_NN1 and_CC coordination_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ in_II practice_NN1 applied_VVN by_II assessing_VVG the_AT different_JJ barriers_NN2 discussed_VVN in_II the_AT assessed_JJ academic_JJ journals_NN2 and_CC considering_II which_DDQ barriers_NN2 have_VH0 the_AT largest_JJT impact_NN1 on_II the_AT stakeholders_NN2 ._. 
</s>
<s>
While_CS the_AT stakeholder_NN1 theory_NN1 is_VBZ based_VVN on_II a_AT1 business_NN1 concept_NN1 ,_, the_AT same_DA stakeholders_NN2 can_VM be_VBI found_VVN in_II a_AT1 humanitarian_JJ organization_NN1 ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) 3.2_MC Humanitarian_JJ Logistics_NN1 Thomas_NP1 and_CC Mizushima_NP1 (_( 2005_MC ,_, p._NN1 60_MC )_) defined_VVD humanitarian_JJ logistics_NN1 as_II the_AT process_NN1 of_IO planning_NN1 ,_, implementing_VVG ,_, and_CC controlling_VVG the_AT efficient_JJ ,_, cost-effective_JJ flow_NN1 and_CC storage_NN1 of_IO goods_NN2 and_CC materials_NN2 ,_, as_II31 well_II32 as_II33 related_JJ information_NN1 ,_, from_II the_AT point_NN1 of_IO origin_NN1 of_IO consumption_NN1 for_IF the_AT purpose_NN1 of_IO meeting_VVG the_AT end_NN1 beneficiarys_NN2 requirements_NN2 ._. 
</s>
<s>
This_DD1 definition_NN1 can_VM to_II almost_RR all_DB aspects_NN2 be_VBI effectively_RR compared_VVN to_II logistics_NN1 in_II a_AT1 business_NN1 context_NN1 ._. 
</s>
<s>
However_RR ,_, the_AT actors_NN2 involved_JJ in_II humanitarian_JJ logistics_NN1 are_VBR not_XX motivated_VVN by_II personal_JJ gain_NN1 or_CC profit_NN1 ,_, and_CC the_AT beneficiary_NN1 e.g._REX customer_NN1 is_VBZ usually_RR in_II a_AT1 life_NN1 threatening_VVG situation_NN1 that_CST does_VDZ not_XX give_VVI him/her_PPHO1 the_AT luxury_NN1 of_IO choosing_VVG between_II products_NN2 ._. 
</s>
<s>
If_CS these_DD2 aspects_NN2 are_VBR taken_VVN into_II consideration_NN1 ,_, the_AT supply_NN1 chain_NN1 of_IO a_AT1 humanitarian_JJ aid_NN1 operation_NN1 differs_VVZ quite_RG remarkably_RR from_II a_AT1 supply_NN1 chain_NN1 in_II a_AT1 business_NN1 context_NN1 ._. 
</s>
<s>
While_CS the_AT demand_NN1 and_CC supply_VV0 usually_RR is_VBZ fairly_RR easily_RR definable_JJ in_II a_AT1 business_NN1 supply_NN1 chain_NN1 ,_, the_AT same_DA can_VM not_XX be_VBI said_VVN for_IF a_AT1 humanitarian_JJ supply_NN1 chain_NN1 as_II the_AT products_NN2 demand_VV0 is_VBZ created_VVN overnight_RT or_CC under_II a_AT1 short_JJ time_NNT1 span_NN1 with_IW supplies_NN2 usually_RR being_VBG scarce_JJ and_CC not_XX easily_RR accessible_JJ ._. 
</s>
<s>
(_( Kovacs_NP1 &;_NULL Spens_NP1 ,_, 2009_MC )_) While_CS the_AT field_NN1 of_IO implementation_NN1 for_IF humanitarian_JJ logistics_NN1 focuses_VVZ on_II a_AT1 wide_JJ range_NN1 of_IO different_JJ disasters_NN2 ;_; earthquakes_NN2 ,_, tsunamis_NN1 ,_, hurricanes_NN2 ,_, epidemics_NN2 ,_, famines_NN2 ,_, terrorist_JJ attacks_NN2 ,_, and_CC war_NN1 situations_NN2 ,_, the_AT differentiation_NN1 is_VBZ still_RR somewhat_RR unclear_JJ as_II21 to_II22 which_DDQ organizations_NN2 tend_VV0 to_II which_DDQ disaster_NN1 most_RGT effectively_RR and_CC in_II what_DDQ kind_NN1 of_IO combination_NN1 ._. 
</s>
<s>
More_RRR over_II the_AT causes_NN2 ,_, effects_NN2 and_CC scale_NN1 of_IO the_AT disasters_NN2 tend_VV0 to_TO differ_VVI in_II the_AT same_DA manner_NN1 as_CSA the_AT number_NN1 of_IO organizations_NN2 involved_JJ in_II the_AT mitigation_NN1 ._. 
</s>
<s>
(_( Kovcs_NP1 &;_NULL Spens_NP1 ,_, 2009_MC )_) The_AT primary_JJ objective_NN1 for_IF humanitarian_JJ organizations_NN2 is_VBZ as_CSA discussed_VVN ,_, to_TO effectively_RR provide_VVI aid_NN1 and_CC materials_NN2 to_II people_NN in_II disaster_NN1 areas_NN2 ._. 
</s>
<s>
This_DD1 function_NN1 is_VBZ hindered_JJ foremost_JJT by_II the_AT unpredictability_NN1 of_IO the_AT demand_NN1 ,_, in_II31 terms_II32 of_II33 timing_NN1 ,_, location_NN1 ,_, type_NN1 and_CC size_NN1 ._. 
</s>
<s>
While_CS a_AT1 disaster_NN1 to_II some_DD degree_NN1 is_VBZ predictable_JJ ,_, the_AT scale_NN1 of_IO the_AT destruction_NN1 of_IO infrastructure_NN1 and_CC the_AT impact_NN1 on_II local_JJ populous_JJ is_VBZ impossible_JJ to_TO predict_VVI ._. 
</s>
<s>
A_AT1 disaster_NN1 can_VM also_RR occur_VVI very_RG suddenly_RR ,_, for_REX21 example_REX22 an_AT1 earthquake_NN1 or_CC a_AT1 tsunami_NN2 ,_, which_DDQ may_VM lead_VVI to_II increased_JJ numbers_NN2 of_IO beneficiaries_NN2 injured_VVN or_CC killed_VVD ._. 
</s>
<s>
It_PPH1 can_VM also_RR leave_VVI the_AT local_JJ relief_NN1 organizations_NN2 (_( which_DDQ usually_RR are_VBR the_AT first_MD ones_NN2 to_TO arrive_VVI at_II the_AT disaster_NN1 area_NN1 )_) unable_JK to_TO function_VVI ._. 
</s>
<s>
The_AT suddenness_NN1 of_IO a_AT1 disaster_NN1 also_RR creates_VVZ a_AT1 large_JJ demand_NN1 for_IF supplies_NN2 to_II a_AT1 possibly_RR inaccessible_JJ area_NN1 where_CS the_AT beneficiaries_NN2 lives_NN2 are_VBR depending_II21 on_II22 the_AT lead_NN1 times_NNT2 of_IO the_AT relief_NN1 organizations_NN2 ._. 
</s>
<s>
(_( Kovcs_NP1 &;_NULL Spens_NP1 ,_, 2009_MC )_) 3.3_MC Challenges_NN2 in_II Humanitarian_JJ Logistics_NN1 In_II this_DD1 chapter_NN1 the_AT major_JJ challenges_NN2 will_VM be_VBI presented_VVN ,_, as_CSA they_PPHS2 have_VH0 been_VBN discussed_VVN in_II the_AT journals_NN2 or_CC lectures_NN2 mentioned_VVD earlier_RRR in_II the_AT text_NN1 ._. 
</s>
<s>
These_DD2 challenges_NN2 are_VBR all_DB related_VVN to_II humanitarian_JJ logistics_NN1 and_CC are_VBR considered_VVN as_CSA barriers_NN2 of_IO bigger_JJR or_CC smaller_JJR proportions_NN2 for_IF effective_JJ coordination_NN1 ._. 
</s>
<s>
In_II a_AT1 broader_JJR sense_NN1 the_AT major_JJ barriers_NN2 can_VM be_VBI divided_VVN into_II five_MC categories_NN2 ,_, as_CSA most_DAT barriers_NN2 are_VBR in_II some_DD way_NN1 linked_VVN to_II these_DD2 categories_NN2 ._. 
</s>
<s>
The_AT categories_NN2 are_VBR ;_; politics_NN1 ,_, ideologies_NN2 ,_, religions_NN2 ,_, bureaucracies_NN2 ,_, and_CC competition_NN1 of_IO donors_NN2 (_( Lecture_NN1 ,_, Hertz_NNU 2011_MC )_) ._. 
</s>
<s>
These_DD2 categories_NN2 will_VM now_RT be_VBI presented_VVN in_II a_AT1 more_RGR detailed_JJ manner_NN1 in_II order_NN1 to_TO properly_RR describe_VVI the_AT way_NN1 they_PPHS2 function_VV0 as_II a_AT1 barrier_NN1 ._. 
</s>
<s>
3.3.1_MC Politics_NN1 The_AT political_JJ situation_NN1 in_II a_AT1 relief_NN1 area_NN1 is_VBZ always_RR considered_VVN as_II an_AT1 important_JJ factor_NN1 ,_, as_CSA it_PPH1 is_VBZ for_IF some_DD organizations_NN2 necessary_JJ for_IF the_AT disaster_NN1 struck_VVD country_NN1 to_TO officially_RR request_VVI assistance_NN1 ,_, before_CS the_AT organizations_NN2 can_VM enter_VVI the_AT country_NN1 in_II question_NN1 ._. 
</s>
<s>
The_AT unstable_JJ political_JJ situation_NN1 in_II a_AT1 country_NN1 may_VM lead_VVI to_II ineffective_JJ information_NN1 flow_NN1 or_CC indecisiveness_NN1 as_II21 to_II22 where_RRQ the_AT relief_NN1 aid_NN1 is_VBZ needed_VVN ._. 
</s>
<s>
The_AT whole_JJ operation_NN1 can_VM be_VBI disrupted_VVN by_II the_AT political_JJ parties_NN2 arguing_VVG about_II who_PNQS should_VM be_VBI in_II31 charge_II32 of_II33 coordination_NN1 with_IW aid_NN1 organizations_NN2 ._. 
</s>
<s>
Another_DD1 aspect_NN1 of_IO the_AT politics_NN1 involved_JJ in_II a_AT1 relief_NN1 operation_NN1 ,_, is_VBZ the_AT mandates_NN2 that_CST are_VBR necessary_JJ for_IF the_AT larger_JJR organizations_NN2 ,_, as_CSA they_PPHS2 are_VBR not_XX allowed_VVN into_II a_AT1 country_NN1 with_IW a_AT1 proper_JJ mandate_NN1 ._. 
</s>
<s>
A_AT1 political_JJ situation_NN1 in_II the_AT form_NN1 of_IO military_JJ conflicts_NN2 is_VBZ also_RR something_PN1 that_CST affects_VVZ and_CC humanitarian_JJ operation_NN1 ._. 
</s>
<s>
The_AT presence_NN1 of_IO armed_JJ forces_NN2 ,_, works_VVZ a_AT1 double-edged_JJ sword_NN1 ,_, as_CSA the_AT cooperation_NN1 with_IW the_AT military_NN1 may_VM provide_VVI transportation_NN1 and_CC logistics_NN1 services_NN2 ,_, but_CCB on_II the_AT other_JJ hand_NN1 the_AT beneficiaries_NN2 may_VM not_XX trust_VVI the_AT military_JJ forces_NN2 or_CC any_DD organizations_NN2 working_VVG with_IW them_PPHO2 ._. 
</s>
<s>
(_( Hertz_NNU ,_, Lecture_NN1 ,_, 2011_MC )_) 3.3.2_MC Ideologies_NN2 Most_RGT humanitarian_JJ aid_NN1 organizations_NN2 function_VV0 according_II21 to_II22 a_AT1 set_NN1 of_IO principles_NN2 and_CC an_AT1 ideology_NN1 ._. 
</s>
<s>
These_DD2 principles_NN2 usually_RR highlight_VV0 aspects_NN2 such_II21 as_II22 humanity_NN1 ,_, impartiality_NN1 ,_, neutrality_NN1 and_CC independence_NN1 ._. 
</s>
<s>
Many_DA2 humanitarian_JJ organizations_NN2 tend_VV0 to_TO not_XX cooperate_VVI with_IW the_AT local_JJ military_JJ as_CSA this_DD1 obviously_RR would_VM violate_VVI the_AT principle_NN1 of_IO impartiality_NN1 ._. 
</s>
<s>
The_AT ideologies_NN2 or_CC principles_NN2 of_IO humanitarian_JJ aid_NN1 organizations_NN2 are_VBR dependent_JJ on_II the_AT type_NN1 of_IO organization_NN1 ._. 
</s>
<s>
Also_RR these_DD2 ideologies_NN2 may_VM even_RR prevent_VVI some_DD organizations_NN2 from_II even_RR entering_VVG a_AT1 country_NN1 where_CS another_DD1 organization_NN1 is_VBZ active_JJ ._. 
</s>
<s>
A_AT1 prime_JJ example_NN1 of_IO distinctive_JJ and_CC controlling_VVG ideologies_NN2 is_VBZ the_AT independent_JJ organization_NN1 Doctors_NN2 Without_IW Borders_NP1 (_( Medecins_NN31 Sans_NN32 Frontieres_NN33 )_) (_( MFS_NP1 )_) ,_, which_DDQ to_II a_AT1 large_JJ extent_NN1 is_VBZ extremely_RR cautious_JJ to_II cooperating_VVG with_IW other_JJ aid_NN1 organizations_NN2 ,_, and_CC is_VBZ unconditionally_RR neutral_JJ in_II any_DD relief_NN1 operation_NN1 ._. 
</s>
<s>
The_AT choice_NN1 of_IO neutrality_NN1 might_VM be_VBI admirable_JJ to_II some_DD extent_NN1 but_CCB it_PPH1 also_RR decreases_VVZ the_AT information_NN1 flow_NN1 of_IO beneficiary_NN1 needs_VVZ to_II other_JJ organizations_NN2 that_CST might_VM be_VBI able_JK to_TO deliver_VVI aid_NN1 in_II other_JJ forms_NN2 than_CSN medical_JJ care_NN1 ._. 
</s>
<s>
(_( Kovcs_NP1 ,_, Lecture_NN1 2011_MC )_) ._. 
</s>
<s>
As_II a_AT1 result_NN1 of_IO the_AT principles_NN2 that_CST humanitarian_JJ organizations_NN2 follow_VV0 ,_, a_AT1 major_JJ barrier_NN1 is_VBZ presented_VVN in_II the_AT conundrum_NN1 ,_, how_RRQ to_TO keep_VVI your_APPGE ideology_NN1 and_CC still_RR cooperate_VV0 ?_? 
</s>
<s>
._. (_( Susanne_NN1 Hertz_NNU ,_, Lecture_NN1 2011_MC )_) 3.3.3_MC Religions_NN2 The_AT religious_JJ aspect_NN1 of_IO humanitarian_JJ aid_NN1 is_VBZ always_RR very_RG present_JJ as_II the_AT religion_NN1 of_IO the_AT beneficiary_NN1 must_VM be_VBI taken_VVN into_II account_NN1 when_CS providing_VVG relief_NN1 aid_NN1 ._. 
</s>
<s>
As_II an_AT1 example_NN1 stands_VVZ the_AT division_NN1 of_IO the_AT International_JJ Committee_NN1 of_IO the_AT Red_JJ Cross/Crescent_NN1 (_( ICRC_NP1 )_) ,_, depending_II21 on_II22 the_AT majority_NN1 of_IO the_AT beneficiaries_NN2 in_II a_AT1 country_NN1 being_VBG either_RR Christian_JJ or_CC Muslim_JJ ._. 
</s>
<s>
While_CS this_DD1 division_NN1 has_VHZ been_VBN proven_VVN functional_JJ for_IF the_AT ICRC_NN1 ,_, other_JJ Christian_JJ or_CC Muslim_JJ aid_NN1 organizations_NN2 may_VM have_VHI some_DD very_RG strong_JJ ideologies_NN2 based_VVN on_II their_APPGE religions_NN2 ,_, which_DDQ may_VM hinder_VVI them_PPHO2 from_II effectively_RR reaching_VVG beneficiaries_NN2 or_CC cooperating_VVG with_IW certain_JJ organizations_NN2 ._. 
</s>
<s>
(_( Hertz_NNU ,_, Lecture_NN1 ,_, 2011_MC )_) 3.3.4_MC Bureaucracies_NN2 Bureaucracy_NN1 in_II humanitarian_JJ aid_NN1 operations_NN2 is_VBZ an_AT1 unfortunate_JJ reality_NN1 that_CST all_DB organizations_NN2 must_VM endure_VVI ._. 
</s>
<s>
While_CS organizations_NN2 in_II developed_JJ countries_NN2 might_VM be_VBI used_VVN to_II an_AT1 effective_JJ customs_NN2 in_II their_APPGE home_NN1 country_NN1 ,_, the_AT reality_NN1 is_VBZ something_PN1 quite_RG different_JJ as_CSA vital_JJ humanitarian_JJ aid_NN1 material_NN1 and_CC goods_NN2 might_VM get_VVI stuck_JJ in_II customs_NN2 procedures_NN2 for_IF days_NNT2 before_CS they_PPHS2 reach_VV0 the_AT beneficiaries_NN2 just_RR because_II21 of_II22 the_AT bureaucracy_NN1 involved_VVD ._. 
</s>
<s>
The_AT situation_NN1 will_VM furthermore_RR deteriorate_VVI with_IW the_AT enormous_JJ amounts_NN2 of_IO aid_NN1 material_NN1 that_CST tend_VV0 to_TO be_VBI delivered_VVN at_II the_AT same_DA time_NNT1 from_II organizations_NN2 across_II the_AT world_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ for_IF this_DD1 reason_NN1 that_CST some_DD aid_NN1 organizations_NN2 tend_VV0 to_TO stick_VVI to_II themselves_PPX2 as_II the_AT find_VV0 the_AT process_NN1 of_IO customs_NN2 declarations_NN2 easier_RRR if_CS they_PPHS2 do_VD0 nt_XX have_VHI to_TO think_VVI about_II other_JJ parties_NN2 involved_VVD ._. 
</s>
<s>
(_( Hertz_NNU ,_, Lecture_NN1 2011_MC &;_NULL Kovcs_NP2 Lecture_NN1 ,_, 2011_MC )_) 3.3.5_MC Competition_NN1 of_IO donors_NN2 The_AT lifeline_NN1 of_IO most_DAT humanitarian_JJ organizations_NN2 is_VBZ the_AT financial_JJ donations_NN2 from_II private_JJ donors_NN2 ._. 
</s>
<s>
These_DD2 donations_NN2 facilitate_VV0 the_AT ongoing_JJ procurement_NN1 of_IO relief_NN1 material_NN1 and_CC keeping_VVG the_AT organization_NN1 functional_JJ ._. 
</s>
<s>
The_AT donors_NN2 usually_RR tend_VV0 to_TO donate_VVI monetary_JJ or_CC material_NN1 aid_NN1 to_II the_AT humanitarian_JJ organizations_NN2 that_CST they_PPHS2 can_VM relate_VVI to_II ,_, or_CC the_AT principles_NN2 they_PPHS2 can_VM relate_VVI to_II ._. 
</s>
<s>
Under_II this_DD1 premise_NN1 of_IO future_JJ donations_NN2 ,_, it_PPH1 is_VBZ understandable_JJ that_CST aid_NN1 organizations_NN2 tend_VV0 to_TO aim_VVI for_IF both_DB2 beneficiaries_NN2 as_II31 well_II32 as_II33 donor_NN1 satisfaction_NN1 ._. 
</s>
<s>
Hence_RR ,_, the_AT choice_NN1 of_IO coordination_NN1 with_IW other_JJ organizations_NN2 is_VBZ not_XX only_RR depending_II21 on_II22 the_AT most_RGT effective_JJ logistical_JJ solution_NN1 but_CCB also_RR on_II the_AT beneficiaries_NN2 and_CC donors_NN2 ._. 
</s>
<s>
(_( Kovcs_NP1 ,_, Lecture_NN1 2011_MC )_) 4.0_MC Analysis_NN1 of_IO barrier_NN1 implication_NN1 on_II the_AT stakeholder_NN1 The_AT barriers_NN2 presented_VVN in_II the_AT previous_JJ chapter_NN1 function_NN1 on_II a_AT1 fundamental_JJ level_NN1 as_II a_AT1 hinder_VV0 for_IF the_AT individual_JJ stakeholder_NN1 to_II the_AT humanitarian_JJ organization_NN1 ._. 
</s>
