<s>
How_RGQ purchasing_JJ management_NN1 reinforce_VV0 the_AT business_NN1 competitiveness_NN1 of_IO a_AT1 firm_NN1 1_MC1 ._. 
</s>
<s>
2_MC ._. 
</s>
<s>
Introduction_NN1 :_: Recently_RR ,_, a_AT1 so-called_JJ electricity_NN1 supplier_NN1 price_NN1 war(2012)_FO ,_, which_DDQ was_VBDZ brought_VVN up_RP by_II one_MC1 of_IO Chinese_JJ largest_JJT online_JJ retailers_NN2 -_- Jingdong_VV0 mall_NN1 -_- happened_VVD among_II the_AT 3_MC Chinese_JJ largest_JJT electricity_NN1 retailers_NN2 ,_, Jingdong_NP1 ,_, Guomei_NP1 and_CC Suning_NP1 ,_, and_CC it_PPH1 has_VHZ raised_VVN a_AT1 widespread_JJ concern_NN1 in_II the_AT whole_JJ community_NN1 ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO attract_VVI the_AT attention_NN1 of_IO consumers_NN2 and_CC gain_VVI the_AT popularity_NN1 and_CC market_NN1 share_NN1 of_IO the_AT company_NN1 ,_, these_DD2 companies_NN2 decided_VVD to_TO cut_VVI prices_NN2 for_IF all_DB of_IO the_AT products_NN2 by_II a_AT1 wide_JJ margin_NN1 and_CC compete_VV0 who_PNQS will_VM keep_VVI offering_VVG the_AT lowest_JJT price_NN1 of_IO the_AT war_NN1 ._. 
</s>
<s>
Generally_RR ,_, it_PPH1 was_VBDZ considered_VVN as_II a_AT1 normal_JJ competition_NN1 among_II companies_NN2 ,_, even_CS21 if_CS22 the_AT prices_NN2 of_IO products_NN2 have_VH0 been_VBN reduced_VVN greatly_RR ;_; however_RR ,_, it_PPH1 is_VBZ convinced_VVN firmly_RR that_CST the_AT companies_NN2 still_RR have_VH0 good_JJ profits_NN2 to_II some_DD extent_NN1 ._. 
</s>
<s>
So_RR who_PNQS will_VM be_VBI the_AT winner_NN1 in_II the_AT end_NN1 ?_? 
</s>
<s>
This_DD1 paper_NN1 seeks_VVZ to_TO find_VVI the_AT reasons_NN2 of_IO why_RRQ these_DD2 retailers_NN2 dare_VV0 to_TO receive_VVI such_DA a_AT1 risky_JJ challenge_NN1 and_CC what_DDQ factors_VVZ ultimately_RR determine_VV0 the_AT victory_NN1 of_IO the_AT price_NN1 war_NN1 ?_? 
</s>
<s>
An_AT1 investment_NN1 advisor_NN1 in_II the_AT retail_JJ industry_NN1 pointed_VVD out_RP that_DD1 price_NN1 war_NN1 as_CSA one_MC1 of_IO the_AT most_RGT direct_JJ ,_, fastest_RRT ,_, most_RGT effective_JJ means_NN of_IO competition_NN1 ,_, it_PPH1 fully_RR reflected_VVD the_AT comprehensive_JJ strength_NN1 of_IO the_AT businesses_NN2 ,_, and_CC especially_RR the_AT capability_NN1 of_IO a_AT1 corporates_NN2 supply_VV0 chain_NN1 management_NN1 (_( Liu_NP1 ,_, 2012_MC )_) ._. 
</s>
<s>
Supply_VV0 chain_NN1 management_NN1 is_VBZ a_AT1 decisive_JJ factor_NN1 of_IO the_AT price_NN1 war_NN1 (_( Liu_NP1 ,_, 2012_MC )_) ._. 
</s>
<s>
That_REX41 is_REX42 to_REX43 say_REX44 ,_, business_NN1 with_IW high_JJ efficient_JJ supply_NN1 chain_NN1 management_NN1 capabilities_NN2 is_VBZ essential_JJ for_IF a_AT1 firm_JJ to_TO be_VBI more_RGR competitive_JJ in_II the_AT market_NN1 ._. 
</s>
<s>
However_RR ,_, purchasing_VVG management_NN1 as_II the_AT priority_NN1 part_NN1 of_IO the_AT supply_NN1 chain_NN1 management_NN1 definitely_RR plays_VVZ an_AT1 important_JJ role_NN1 in_II a_AT1 successful_JJ business_NN1 as_RR21 well_RR22 ._. 
</s>
<s>
In_II the_AT modern_JJ enterprise_NN1 management_NN1 ,_, the_AT functionality_NN1 of_IO purchasing_VVG management_NN1 has_VHZ become_VVN increasingly_RR important_JJ ._. 
</s>
<s>
Firstly_RR ,_, costs_NN2 of_IO products_NN2 or_CC materials_NN2 normally_RR account_VV0 for_IF relatively_RR large_JJ proportion_NN1 (_( 60%-70%_FO )_) of_IO the_AT total_JJ costs_NN2 of_IO a_AT1 corporate_JJ (_( Madison_NP1 ,_, 2007_MC )_) ._. 
</s>
<s>
So_RR if_CS the_AT procurement_NN1 costs_NN2 can_VM be_VBI managed_VVN and_CC controlled_VVN well_RR ,_, then_RT the_AT firm_NN1 will_VM have_VHI more_DAR extra_JJ money_NN1 to_TO invest_VVI and_CC develop_VVI other_JJ parts_NN2 of_IO the_AT supply_NN1 chain_NN1 to_TO enhance_VVI its_APPGE business_NN1 ._. 
</s>
<s>
Secondly_RR ,_, the_AT purchasers_NN2 or_CC buyers_NN2 are_VBR responsible_JJ for_IF the_AT evaluation_NN1 of_IO the_AT materials_NN2 and_CC products_NN2 they_PPHS2 purchased_VVD in_II31 terms_II32 of_II33 price_NN1 ,_, quality_NN1 ,_, service_NN1 ,_, availability_NN1 ,_, reliability_NN1 and_RR31 so_RR32 forth_RR33 (_( Benton_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
Hence_RR ,_, a_AT1 purchasing_NN1 management_NN1 will_VM directly_RR influence_VVI the_AT continuity_NN1 of_IO the_AT whole_JJ supply_NN1 chain_NN1 and_CC the_AT quality_NN1 of_IO the_AT final_JJ products_NN2 ._. 
</s>
<s>
Thirdly_RR ,_, purchasing_VVG management_NN1 devotes_VVZ enterprises_NN2 to_TO choose_VVI right_JJ suppliers_NN2 and_CC establish_VVI good_JJ communication_NN1 and_CC long-term_JJ partnership_NN1 with_IW suppliers_NN2 (_( Benton_NP1 ,_, 2010_MC )_) ,_, so_CS21 that_CS22 to_TO provide_VVI the_AT company_NN1 a_AT1 very_RG strong_JJ and_CC stable_JJ source_NN1 base_NN1 to_TO pursue_VVI higher_JJR profits_NN2 ._. 
</s>
<s>
All_DB in_II all_DB ,_, the_AT price_NN1 war_NN1 is_VBZ eventually_RR a_AT1 test_NN1 to_TO supply_VVI chain_NN1 management_NN1 of_IO a_AT1 company_NN1 ;_; meanwhile_RR ,_, it_PPH1 is_VBZ a_AT1 test_NN1 to_II purchasing_VVG management_NN1 of_IO this_DD1 company_NN1 as_RR21 well_RR22 ._. 
</s>
<s>
This_DD1 paper_NN1 aims_VVZ to_TO investigate_VVI how_RGQ purchasing_JJ management_NN1 will_VM affect_VVI the_AT whole_JJ supply_NN1 chain_NN1 of_IO a_AT1 company_NN1 as_II31 well_II32 as_II33 a_AT1 corporate_JJ business_NN1 and_CC its_APPGE competitiveness_NN1 in_II the_AT market_NN1 ,_, and_CC specify_VV0 the_AT importance_NN1 of_IO procurement_NN1 and_CC purchasing_VVG management_NN1 in_II a_AT1 good_JJ supply_NN1 chain_NN1 management_NN1 ._. 
</s>
<s>
It_PPH1 will_VM not_XX highlight_VVI the_AT functionality_NN1 of_IO supply_NN1 chain_NN1 management_NN1 but_CCB will_VM be_VBI mentioned_VVN and_CC described_VVN ._. 
</s>
<s>
It_PPH1 will_VM also_RR give_VVI a_AT1 case_NN1 study_NN1 to_TO illustrate_VVI how_RRQ an_AT1 enterprise_NN1 conducts_NN2 purchasing_VVG management_NN1 successfully_RR in_II the_AT procurement_NN1 process_NN1 ._. 
</s>
<s>
This_DD1 paper_NN1 is_VBZ organized_VVN in_II following_VVG way_NN1 ._. 
</s>
<s>
After_CS this_DD1 introduction_NN1 ,_, the_AT second_MD part_NN1 will_VM be_VBI divided_VVN into_II two_MC sections_NN2 :_: 1_MC1 )_) mainly_RR identifying_VVG the_AT key_JJ factors_NN2 impacting_VVG on_II implementation_NN1 of_IO procurement_NN1 management_NN1 in_II purchasing_VVG process_NN1 ;_; 2_MC )_) Clarifying_VVG the_AT relationship_NN1 between_II procurement_NN1 and_CC other_JJ parts_NN2 of_IO supply_NN1 chain_NN1 and_CC displaying_VVG how_RRQ the_AT purchasing_NN1 will_VM be_VBI integrated_VVN with_IW other_JJ parts_NN2 of_IO supply_NN1 chain_NN1 to_TO improve_VVI the_AT corporate_JJ competitiveness_NN1 ._. 
</s>
<s>
The_AT third_MD section_NN1 is_VBZ followed_VVN by_II a_AT1 case_NN1 study_NN1 about_II Volvos_NP2 procurement_NN1 strategies_NN2 in_BCL21 order_BCL22 to_TO analyze_VVI in_II which_DDQ aspects_NN2 should_VM be_VBI concentrated_VVN on_II21 to_II22 implement_NN1 the_AT purchasing_NN1 strategies_NN2 successfully_RR ._. 
</s>
<s>
Lastly_RR ,_, by_II evaluating_VVG the_AT functions_NN2 of_IO purchasing_VVG management_NN1 in_II the_AT enterprise_NN1 to_TO gain_VVI a_AT1 deeper_JJR understanding_NN1 of_IO the_AT importance_NN1 of_IO implementing_VVG purchasing_NN1 management_NN1 and_CC arouse_VV0 other_JJ companies_NN2 attention_NN1 to_TO concentrate_VVI on_II it_PPH1 ._. 
</s>
<s>
3_MC ._. 
</s>
<s>
Methodology_NN1 A_ZZ1 variety_NN1 of_IO existing_JJ documentation_NN1 (_( literature_NN1 books_NN2 ,_, publications_NN2 ,_, journals_NN2 ,_, internet_NN1 ,_, etc._RA )_) are_VBR evaluated_VVN and_CC verified_VVN in_BCL21 order_BCL22 to_TO provide_VVI the_AT theory_NN1 for_IF the_AT topic_NN1 and_CC confirm_VV0 the_AT used_JJ knowledge_NN1 is_VBZ correct_JJ ._. 
</s>
<s>
Documents_NN2 referring_VVG to_II the_AT purchasing_NN1 management_NN1 are_VBR available_JJ ._. 
</s>
<s>
Literature_NN1 book_NN1 Purchasing_NN1 and_CC supply_VV0 chain_NN1 management_NN1 is_VBZ used_VVN as_II the_AT main_JJ reference_NN1 to_TO help_VVI to_TO analyze_VVI the_AT purchasing_NN1 function_NN1 in_II supply_NN1 chain_NN1 as_II31 well_II32 as_II33 the_AT corporate_JJ business_NN1 ._. 
</s>
<s>
A_AT1 case_NN1 study_NN1 about_II Volvos_NP2 purchasing_VVG strategy_NN1 was_VBDZ analyzed_VVN by_II having_VHG an_AT1 interview_NN1 with_IW the_AT manager_NN1 of_IO Global_JJ logistics_NN1 ,_, Per_II Dalheim_NP1 ._. 
</s>
<s>
This_DD1 will_VM explain_VVI in_II which_DDQ aspects_NN2 should_VM be_VBI concentrated_VVN on_II21 to_II22 implement_NN1 the_AT purchasing_NN1 strategies_NN2 successfully_RR ._. 
</s>
<s>
While_CS ,_, it_PPH1 aims_VVZ also_RR to_TO stress_VVI the_AT importance_NN1 of_IO different_JJ purchasing_NN1 strategies_NN2 to_II a_AT1 firm_NN1 in_II contributing_VVG to_II the_AT reduction_NN1 of_IO the_AT overall_JJ costs_NN2 and_CC elimination_NN1 of_IO risks_NN2 in_II purchasing_VVG process_NN1 ._. 
</s>
<s>
4_MC ._. 
</s>
<s>
Theory_NN1 research_NN1 3.1_MC Analysis_NN1 of_IO purchasing_VVG process_NN1 From_II the_AT example_NN1 of_IO price_NN1 war_NN1 mentioned_VVD before_RT ,_, it_PPH1 has_VHZ indicated_VVN that_CST implementing_VVG purchasing_NN1 management_NN1 successfully_RR has_VHZ great_JJ benefit_NN1 on_II saving_VVG cost_NN1 ;_; meanwhile_RR ,_, it_PPH1 offers_VVZ a_AT1 strong_JJ basis_NN1 for_IF the_AT business_NN1 competitiveness_NN1 in_II the_AT fierce_JJ competitive_JJ market_NN1 ._. 
</s>
<s>
However_RR ,_, a_AT1 good_JJ purchasing_NN1 management_NN1 utilized_VVD well_RR should_VM be_VBI on_II the_AT basis_NN1 of_IO the_AT interaction_NN1 among_II the_AT each_DD1 step_NN1 of_IO procurement_NN1 process_NN1 ._. 
</s>
<s>
A_AT1 standard_JJ procurement_NN1 process_NN1 is_VBZ included_VVN five_MC steps_NN2 ._. 
</s>
<s>
Firstly_RR ,_, defining_VVG the_AT business_NN1 needs_NN2 ._. 
</s>
<s>
This_DD1 means_VVZ that_CST the_AT purchasers_NN2 or_CC the_AT buyers_NN2 must_VM understand_VVI the_AT fundamental_JJ and_CC specific_JJ requirement_NN1 to_II the_AT company_NN1 before_II starting_VVG the_AT procurement_NN1 ._. 
</s>
<s>
Secondly_RR ,_, developing_VVG the_AT purchasing_NN1 strategy_NN1 ,_, which_DDQ is_VBZ responsible_JJ for_IF searching_VVG the_AT market_NN1 ,_, looking_VVG for_IF the_AT potential_JJ solutions_NN2 to_TO meet_VVI the_AT companys_NN2 requirements_NN2 and_CC selecting_VVG the_AT suppliers_NN2 ,_, is_VBZ seen_VVN as_II the_AT significant_JJ part_NN1 of_IO the_AT purchasing_NN1 process_NN1 ._. 
</s>
<s>
Whether_CSW the_AT company_NN1 will_VM get_VVI the_AT cost_NN1 effectiveness_NN1 ,_, the_AT goods_NN2 will_VM be_VBI delivered_VVN to_II the_AT right_JJ place_NN1 on_II time_NNT1 at_II the_AT mutually_RR agreeable_JJ terms_NN2 ,_, they_PPHS2 all_DB require_VV0 a_AT1 detailed_JJ and_CC precise_JJ purchasing_NN1 strategy_NN1 ._. 
</s>
<s>
Thirdly_RR ,_, it_PPH1 should_VM be_VBI selecting_VVG and_CC evaluating_VVG the_AT suppliers_NN2 ._. 
</s>
<s>
There_EX is_VBZ no_AT doubt_NN1 that_CST right_JJ suppliers_NN2 have_VH0 the_AT capability_NN1 to_TO meet_VVI the_AT companys_NN2 needs_VVZ to_TO ensure_VVI the_AT whole_JJ operation_NN1 of_IO the_AT company_NN1 goes_VVZ properly_RR and_CC smoothly_RR ._. 
</s>
<s>
Take_VV0 the_AT electricity_NN1 retailer_NN1 Suning_VVG mall_NN1 for_REX21 example_REX22 ,_, it_PPH1 was_VBDZ said_VVN that_CST one_MC1 of_IO the_AT important_JJ reasons_NN2 to_TO receive_VVI the_AT price_NN1 war_NN1 is_VBZ that_CST Suning_NP1 mall_NN1 is_VBZ fairly_RR confident_JJ to_II their_APPGE suppliers_NN2 ._. 
</s>
<s>
Additionally_RR ,_, negotiation_NN1 and_CC award_NN1 is_VBZ a_AT1 step_NN1 which_DDQ directly_RR connected_VVN with_IW the_AT companys_NN2 costs_NN2 and_CC other_JJ benefits_NN2 ._. 
</s>
<s>
Negotiating_VVG a_AT1 low-cost_JJ with_IW a_AT1 high-quality_JJ is_VBZ always_RR the_AT objective_NN1 of_IO the_AT company_NN1 ;_; while_CS ,_, it_PPH1 is_VBZ definitely_RR essential_JJ to_TO sign_VVI a_AT1 completely_RR and_CC clearly_RR contract_VV0 to_TO ensure_VVI the_AT correct_JJ quantity_NN1 of_IO products_NN2 and_CC products_NN2 delivery_NN1 time_NNT1 and_CC all_DB the_AT other_JJ necessary_JJ information_NN1 ._. 
</s>
<s>
Associate_VV0 this_DD1 with_IW the_AT price_NN1 war_NN1 again_RT ,_, the_AT 3_MC largest_JJT retails_NN2 dare_VV0 to_TO offer_VVI such_DA low_JJ sales_NN prices_NN2 for_IF most_DAT products_NN2 ,_, it_PPH1 is_VBZ somewhat_RR related_VVN to_II the_AT buyers_NN2 ability_NN1 of_IO negotiation_NN1 ._. 
</s>
<s>
Last_MD but_CCB not_XX least_RRT is_VBZ induction_NN1 and_CC integration_NN1 ._. 
</s>
<s>
It_PPH1 refers_VVZ to_II that_DD1 after_II reaching_VVG the_AT agreement_NN1 with_IW suppliers_NN2 ,_, the_AT buyers_NN2 have_VH0 to_TO keep_VVI tracking_JJ and_CC reporting_VVG the_AT purchased_JJ products_NN2 to_TO prevent_VVI any_DD potential_JJ risks_NN2 within_II the_AT procurement_NN1 process_NN1 ._. 
</s>
<s>
3.2_MC Relationship_NN1 between_II purchasing_VVG management_NN1 and_CC supply_VV0 chain_NN1 management_NN1 After_II analyzing_VVG the_AT five_MC steps_NN2 of_IO purchasing_VVG process_NN1 ,_, it_PPH1 indicated_VVD that_CST if_CS an_AT1 enterprise_NN1 wants_VVZ to_TO implement_VVI a_AT1 successful_JJ procurement_NN1 management_NN1 to_TO work_VVI on_II their_APPGE overall_JJ objective_NN1 ,_, each_DD1 step_NN1 within_II the_AT purchasing_NN1 process_NN1 has_VHZ to_TO work_VVI with_IW each_PPX221 other_PPX222 closely_RR and_CC be_VBI conducted_VVN carefully_RR ._. 
</s>
<s>
Purchasing_VVG professionally_RR will_VM not_XX only_RR add_VVI value_NN1 to_II organization_NN1 in_II controlling_VVG supply_NN1 costs_NN2 ,_, but_CCB also_RR have_VH0 large_JJ influence_NN1 on_II the_AT other_JJ parts_NN2 of_IO management_NN1 in_II supply_NN1 chain_NN1 as_II31 well_II32 as_II33 the_AT business_NN1 of_IO the_AT firm_NN1 ._. 
</s>
<s>
3.2.1_MC Supply_NN1 management_NN1 In_II the_AT supply_NN1 chain_NN1 ,_, it_PPH1 consists_VVZ of_IO three_MC entities_NN2 :_: customers_NN2 ,_, manufacturers_NN2 and_CC the_AT producers_NN2 suppliers_NN2 ._. 
</s>
<s>
Whereas_CS the_AT supply_NN1 chain_NN1 management_NN1 is_VBZ for_IF optimizing_VVG the_AT processes_NN2 of_IO acquiring_VVG inputs_NN2 from_II suppliers_NN2 ,_, converting_VVG those_DD2 inputs_NN2 into_II final_JJ products_NN2 and_CC then_RT delivering_VVG to_II customers_NN2 (_( Patrik_NP1 2008_MC )_) ._. 
</s>
<s>
Among_II them_PPHO2 ,_, purchasing_VVG management_NN1 is_VBZ responsible_JJ for_IF the_AT communication_NN1 with_IW suppliers_NN2 to_TO process_VVI the_AT acquired_JJ inputs_NN2 and_CC ensure_VVI the_AT finished_JJ goods_NN2 can_VM be_VBI transformed_VVN continuously_RR to_II the_AT customers_NN2 ._. 
</s>
<s>
Then_RT the_AT supply_NN1 management_NN1 should_VM be_VBI considered_VVN as_CSA priority_NN1 to_TO integrate_VVI with_IW the_AT purchasing_NN1 ._. 
</s>
<s>
Supply_VV0 management_NN1 exists_VVZ to_TO explore_VVI business_NN1 opportunities_NN2 and_CC utilize_VVI supply_NN1 strategies_NN2 that_CST deliver_VV0 the_AT possible_JJ value_NN1 to_II the_AT organization_NN1 ,_, its_APPGE suppliers_NN2 and_CC its_APPGE customers_NN2 (_( Benton_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
It_PPH1 aims_VVZ to_TO control_VVI the_AT transformation_NN1 of_IO raw_JJ materials_NN2 and_CC component_NN1 parts_NN2 into_II shipped_JJ or_CC inventory_NN1 goods_NN2 to_TO improve_VVI the_AT competitive_JJ position_NN1 and_CC customer_NN1 satisfaction_NN1 ._. 
</s>
<s>
(_( Benton_NP1 ,_, 2010_MC )_) Due_II21 to_II22 these_DD2 reasons_NN2 ,_, the_AT supply_NN1 managers_NN2 ,_, buyers_NN2 ,_, and_CC purchasing_VVG agents_NN2 seek_VV0 to_TO get_VVI the_AT highest-quality_JJ products_NN2 at_II the_AT lowest_JJT possible_JJ purchase_NN1 cost_NN1 for_IF their_APPGE employers_NN2 ._. 
</s>
<s>
In_RR21 general_RR22 ,_, the_AT purchasers_NN2 buy_VV0 goods_NN2 and_CC services_NN2 for_IF resale_NN1 ._. 
</s>
<s>
They_PPHS2 determine_VV0 which_DDQ commodities_NN2 or_CC services_NN2 are_VBR the_AT specific_JJ requirement_NN1 satisfying_VVG the_AT customers_NN2 ,_, choose_VV0 the_AT suppliers_NN2 ,_, negotiate_VV0 the_AT lowest_JJT price_NN1 ,_, and_CC award_NN1 contracts_VVZ that_CST guarantee_VV0 the_AT correct_JJ amount_NN1 of_IO the_AT product_NN1 or_CC service_NN1 is_VBZ received_VVN at_II the_AT appropriate_JJ time_NNT1 with_IW good_JJ quality_NN1 ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO accomplish_VVI these_DD2 tasks_NN2 ,_, it_PPH1 requires_VVZ the_AT purchasing_NN1 managers_NN2 ,_, buyers_NN2 ,_, and_CC purchasing_VVG agents_NN2 could_VM identify_VVI the_AT potential_JJ suppliers_NN2 no_AT matter_NN1 they_PPHS2 are_VBR in_II foreign_JJ or_CC in_II domestic_JJ ._. 
</s>
<s>
Furthermore_RR ,_, they_PPHS2 also_RR need_VV0 to_TO evaluate_VVI suppliers_NN2 on_II the_AT bases_NN2 of_IO price_NN1 ,_, quality_NN1 ,_, service_NN1 support_NN1 ,_, availability_NN1 ,_, reliability_NN1 ,_, by_II researching_VVG their_APPGE reputation_NN1 and_CC history_NN1 ,_, examining_VVG products_NN2 and_CC services_NN2 ,_, assessing_VVG a_AT1 suppliers_NN2 production_NN1 and_CC distribution_NN1 capabilities_NN2 and_CC other_JJ technical_JJ problems_NN2 (_( Benton_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
Once_RR all_DB of_IO the_AT necessary_JJ information_NN1 is_VBZ confirmed_VVN ,_, the_AT purchasers_NN2 will_VM place_VVI the_AT orders_NN2 and_CC award_NN1 contracts_NN2 to_II suppliers_NN2 who_PNQS meet_VV0 their_APPGE needs_NN2 ._. 
</s>
<s>
Integrated_JJ purchasing_NN1 and_CC supply_VV0 management_NN1 still_RR conducts_VVZ the_AT cost_NN1 analysis_NN1 ,_, transportation_NN1 of_IO the_AT materials_NN2 ,_, inventory_NN1 problems_NN2 ,_, quality_NN1 problems_NN2 etc._RA after_II procurement_NN1 to_TO ensure_VVI the_AT products_NN2 and_CC services_NN2 will_VM be_VBI transferred_VVN and_CC utilized_VVN in_II following_VVG process_NN1 successfully_RR ._. 
</s>
<s>
3.2.2_MC Business_NN1 strategy_NN1 The_AT critical_JJ to_TO implement_VVI the_AT integrated_JJ supply_NN1 management_NN1 is_VBZ the_AT issue_NN1 of_IO business_NN1 strategy_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ pointed_VVN out_RP by_II Srivastava_NP1 ,_, The_AT purchasing_NN1 actions_NN2 designed_VVN to_TO reinforce_VVI the_AT firms_NN2 competitive_JJ priorities_NN2 can_VM give_VVI the_AT firm_JJ advantages_NN2 over_II its_APPGE competitors_NN2 ._. 
</s>
<s>
(_( Benton_NP1 ,_, 2010_MC )_) It_PPH1 indicates_VVZ that_CST either_RR purchasing_VVG decisions_NN2 or_CC actions_NN2 are_VBR determined_VVN by_II some_DD certain_JJ factors_NN2 which_DDQ are_VBR corporates_NN2 competitive_JJ priorities_NN2 ,_, its_APPGE resource_NN1 capabilities_NN2 ,_, the_AT organizations_NN2 strengths_NN2 and_CC weaknesses_NN2 as_II31 well_II32 as_II33 the_AT competitive_JJ environment_NN1 ._. 
</s>
<s>
So_RR in_II the_AT formulation_NN1 of_IO purchasing_VVG strategy_NN1 ,_, these_DD2 factors_NN2 must_VM be_VBI considered_VVN (_( Benton_NP1 ,_, 2010_MC )_) ._. 
</s>
<s>
The_AT so_JJ21 called_JJ22 competitive_JJ priorities_NN2 can_VM be_VBI explained_VVN simply_RR that_CST the_AT purchasing_NN1 decision_NN1 maker_NN1 needs_VVZ to_II very_RG clear_JJ about_II what_DDQ they_PPHS2 are_VBR competing_VVG on_RP in_II the_AT market_NN1 before_II procurement_NN1 ._. 
</s>
<s>
For_REX21 example_REX22 ,_, if_CS a_AT1 firm_NN1 competes_VVZ on_II cost_NN1 ,_, so_CS the_AT purchasing_NN1 costs_NN2 will_VM be_VBI treated_VVN as_II the_AT priority_NN1 to_TO drive_VVI the_AT purchasing_NN1 manager_NN1 to_TO take_VVI action_NN1 that_CST keep_VV0 material_NN1 costs_VVZ low_JJ ,_, but_CCB other_JJ criteria_NN2 may_VM be_VBI neglected_VVN ._. 
</s>
<s>
However_RR ,_, competitive_JJ priorities_NN2 not_XX always_RR dominate_VV0 the_AT purchasing_NN1 decision_NN1 and_CC action_NN1 ._. 
</s>
<s>
If_CS a_AT1 manufactory_NN1 competes_VVZ on_II flexibility_NN1 ,_, then_RT the_AT lead_NN1 time_NNT1 will_VM be_VBI the_AT primary_JJ requirement_NN1 to_II the_AT suppliers_NN2 when_CS buying_VVG products_NN2 ._. 
</s>
<s>
The_AT suppliers_NN2 with_IW short_JJ lead_NN1 time_NNT1 give_VV0 the_AT manufactory_NN1 the_AT ability_NN1 to_TO respond_VVI to_II the_AT customers_NN2 or_CC changing_JJ situations_NN2 quickly_RR ,_, but_CCB it_PPH1 requests_VVZ the_AT manufactory_NN1 carry_VV0 more_DAR inventories_NN2 to_TO buffer_VVI against_II uncertainties_NN2 ._. 
</s>
<s>
Inventory_NN1 is_VBZ an_AT1 expensive_JJ alternative_NN1 which_DDQ in_II turn_NN1 may_VM raise_VVI the_AT overall_JJ costs_NN2 of_IO the_AT firm_NN1 ._. 
</s>
<s>
As_CSA costs_VVZ is_VBZ always_RR the_AT dominant_JJ criterion_NN1 in_II evaluating_VVG the_AT performance_NN1 of_IO purchasing_NN1 ,_, hence_RR ,_, this_DD1 example_NN1 tells_VVZ us_PPIO2 that_CST when_CS making_VVG the_AT purchasing_NN1 strategy_NN1 ,_, other_JJ factors_NN2 have_VH0 to_TO be_VBI taken_VVN into_II consideration_NN1 as_RR21 well_RR22 ,_, irrespective_II21 of_II22 the_AT competitive_JJ priority_NN1 ._. 
</s>
<s>
In_II a_AT1 more_RGR comprehensive_JJ perspective_NN1 ,_, cost_NN1 minimization_NN1 may_VM be_VBI the_AT dominant_JJ objective_NN1 in_II buying_VVG and_CC has_VHZ contributed_VVN a_RR21 lot_RR22 to_II increase_NN1 the_AT business_NN1 competitiveness_NN1 ._. 
</s>
<s>
But_CCB in_II todays_NN2 competitive_JJ business_NN1 environment_NN1 ,_, the_AT quality_NN1 issue_NN1 ,_, delivery_NN1 performance_NN1 should_VM also_RR be_VBI regarded_VVN with_IW the_AT cost_NN1 at_II the_AT same_DA time_NNT1 ,_, which_DDQ requires_VVZ each_DD1 part_NN1 of_IO the_AT supply_NN1 chain_NN1 work_VV0 together_RL and_CC keep_VV0 consistent_JJ with_IW each_PPX221 other_PPX222 to_TO devote_VVI to_II strengthening_VVG the_AT competitiveness_NN1 of_IO the_AT firm_NN1 ._. 
</s>
<s>
5_MC ._. 
</s>
<s>
How_RRQ to_TO implement_VVI the_AT purchasing_NN1 strategies_NN2 in_II a_AT1 firm_NN1 As_II the_AT purchasing_NN1 plays_VVZ an_AT1 important_JJ role_NN1 in_II an_AT1 enterprise_NN1 business_NN1 ,_, therefore_RR ,_, which_DDQ aspects_NN2 need_VV0 to_TO be_VBI focused_VVN on_RP ,_, or_CC in_II other_JJ words_NN2 ,_, the_AT company_NN1 will_VM use_VVI what_DDQ sort_NN1 of_IO procurement_NN1 strategies_NN2 to_TO ensure_VVI the_AT purchasing_NN1 process_NN1 proceed_VV0 smoothly_RR ._. 
</s>
<s>
A_AT1 research_NN1 study_NN1 made_VVN in_II Volvo_NP1 may_VM give_VVI some_DD indications_NN2 ._. 
</s>
<s>
Purchasing_VVG strategy_NN1 of_IO Volvo_NP1 The_AT purchasing_NN1 strategies_NN2 for_IF Volvo_NP1 are_VBR referred_VVN by_RP Per_II Dalheim_NP1 (_( manager_NN1 of_IO Global_JJ logistic_JJ in_II Volvo_NP1 )_) in_II 3_MC parts_NN2 ._. 
</s>
<s>
First_MD is_VBZ how_RRQ to_TO establish_VVI a_AT1 good_JJ relationship_NN1 with_IW existing_JJ suppliers_NN2 ._. 
</s>
<s>
Second_MD ,_, how_RRQ to_TO control_VVI purchasing_NN1 cost_NN1 to_TO reduce_VVI the_AT overall_JJ cost_NN1 ._. 
</s>
<s>
Thirdly_RR ,_, evaluate_VV0 the_AT potential_JJ risks_NN2 before_II purchasing_NN1 and_CC how_RRQ to_TO manage_VVI the_AT risks_NN2 ._. 
</s>
<s>
Partnership_NN1 In_II31 terms_II32 of_II33 relationship_NN1 between_II Volvo_NP1 and_CC their_APPGE suppliers_NN2 ,_, the_AT first_MD thing_NN1 of_RR21 course_RR22 is_VBZ choosing_VVG right_JJ and_CC reliable_JJ suppliers_NN2 ._. 
</s>
<s>
For_IF Volvo_NP1 ,_, they_PPHS2 would_VM like_VVI to_TO work_VVI with_IW those_DD2 big_JJ reliable_JJ suppliers_NN2 with_IW large_JJ capacity_NN1 and_CC knowledge_NN1 ,_, and_CC then_RT establish_VV0 a_AT1 long-term_JJ partnership_NN1 with_IW suppliers_NN2 ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO establish_VVI the_AT long-term_JJ and_CC reliable_JJ co-operation_NN1 ,_, both_DB2 the_AT Volvo_NP1 and_CC its_APPGE suppliers_NN2 are_VBR inclined_JJ to_TO trust_VVI each_PPX221 other_PPX222 entirely_RR by_II sharing_VVG the_AT relative_JJ information_NN1 such_II21 as_II22 production_NN1 ideas_NN2 ,_, price_NN1 information_NN1 and_CC IT_NN1 system_NN1 information_NN1 and_RR31 so_RR32 on_RR33 ._. 
</s>
<s>
Purchasing_VVG cost_NN1 Due_II21 to_II22 the_AT reduction_NN1 of_IO purchasing_VVG cost_NN1 ,_, Per_II Dalheim_NP1 mainly_RR referred_VVN to_II 4_MC strategies_NN2 ._. 
</s>
<s>
First_MD ,_, they_PPHS2 outsourcing_VVG their_APPGE components_NN2 design_VV0 work_NN1 to_II their_APPGE suppliers_NN2 ,_, because_CS they_PPHS2 are_VBR professional_JJ at_II design_NN1 work_NN1 and_CC they_PPHS2 know_VV0 how_RRQ to_TO do_VDI to_TO get_VVI high_JJ quality_NN1 components_NN2 with_IW lowest_RRT cost_VV0 ._. 
</s>
<s>
Then_RT the_AT total_JJ cost_NN1 of_IO purchasing_VVG components_NN2 can_VM be_VBI reduced_VVN to_II a_AT1 large_JJ extent_NN1 ._. 
</s>
<s>
However_RR ,_, this_DD1 decision_NN1 is_VBZ also_RR definitely_RR depending_II21 on_II22 strong_JJ partnership_NN1 between_II corporates_NN2 ._. 
</s>
<s>
Second_NNT1 is_VBZ reducing_VVG suppliers_NN2 ._. 
</s>
<s>
It_PPH1 says_VVZ that_CST there_EX is_VBZ a_AT1 policy_NN1 in_II Volvo_NP1 to_TO reduce_VVI the_AT number_NN1 of_IO suppliers_NN2 ._. 
</s>
<s>
That_REX41 is_REX42 to_REX43 say_REX44 ,_, focus_VV0 on_II the_AT big_JJ suppliers_NN2 and_CC get_VV0 rid_VVN of_IO the_AT small_JJ suppliers_NN2 ._. 
</s>
<s>
Because_CS more_DAR suppliers_NN2 means_NN cost_VV0 more_RRR on_II establishing_VVG relationship_NN1 ,_, such_II21 as_II22 IT_NN1 charges_NN2 ,_, handle_VV0 invoice_NN1 charges_NN2 ,_, administrative_JJ cost_NN1 and_CC transportation_NN1 cost_NN1 ._. 
</s>
<s>
Third_MD ,_, in_II31 terms_II32 of_II33 transportation_NN1 costs_NN2 ,_, the_AT Volvo_NP1 think_VV0 that_CST before_II sourcing_VVG the_AT materials_NN2 around_II the_AT world_NN1 ,_, they_PPHS2 have_VH0 to_TO consider_VVI variety_NN1 factors_NN2 like_II low_JJ labor_NN1 cost_NN1 ,_, low-cost_JJ material_NN1 ,_, inventory_NN1 costs_NN2 etc._RA together_RL with_IW the_AT transportation_NN1 fee_NN1 ._. 
</s>
<s>
These_DD2 must_VM be_VBI planned_VVN comprehensively_RR ahead_RL to_TO reach_VVI the_AT lowest_JJT costs_NN2 ._. 
</s>
<s>
Lastly_RR ,_, Volvo_NP1 says_VVZ negotiation_NN1 is_VBZ always_RR the_AT direct_JJ and_CC efficient_JJ way_NN1 to_TO reduce_VVI the_AT purchasing_NN1 cost_NN1 ._. 
</s>
<s>
Risk_VV0 management_NN1 It_PPH1 is_VBZ significant_JJ to_TO evaluate_VVI any_DD potential_JJ risks_NN2 when_CS planning_VVG the_AT purchasing_NN1 to_TO eliminate_VVI or_CC minimize_VVI risks_NN2 during_II the_AT procurement_NN1 process_NN1 ._. 
</s>
<s>
In_II production_NN1 sites_NN2 ,_, when_CS new_JJ parts_NN2 are_VBR produced_VVN ,_, the_AT purchaser_NN1 is_VBZ very_RG much_RR involved_VVN ._. 
</s>
<s>
The_AT changes_NN2 of_IO design_NN1 are_VBR inevitable_JJ ,_, and_CC it_PPH1 affects_VVZ the_AT cost_NN1 as_RR21 well_RR22 ._. 
</s>
<s>
In_II this_DD1 phase_NN1 ,_, the_AT purchaser_NN1 can_VM negotiate_VVI to_TO control_VVI the_AT cost_NN1 and_CC ensure_VVI the_AT design_NN1 and_CC the_AT quality_NN1 is_VBZ appropriate_JJ ._. 
</s>
<s>
For_REX21 instance_REX22 ,_, they_PPHS2 can_VM take_VVI some_DD samples_NN2 back_RP and_CC test_VVI whether_CSW the_AT dimension_NN1 or_CC other_JJ properties_NN2 are_VBR right_JJ ._. 
</s>
<s>
However_RR ,_, once_CS the_AT supplier_NN1 start_NN1 manufacturing_NN1 ,_, then_RT the_AT buyers_NN2 could_VM not_XX be_VBI involved_VVN even_RR problems_NN2 occur_VV0 ._. 
</s>
<s>
If_CS there_EX are_VBR quality_NN1 problem_NN1 ,_, there_EX will_VM be_VBI the_AT plant_NN1 taking_VVG care_NN1 of_IO it_PPH1 ,_, but_CCB the_AT purchaser_NN1 should_VM be_VBI brought_VVN in_RP and_CC help_VV0 contact_NN1 suppliers_NN2 to_TO find_VVI and_CC solve_VVI the_AT problems_NN2 together_RL with_IW Volvo_NP1 ._. 
</s>
<s>
In_II31 addition_II32 to_II33 that_DD1 ,_, Per_II Dalheim_NP1 stressed_VVD that_CST a_AT1 valid_JJ and_CC legal_JJ contract_NN1 is_VBZ the_AT big_JJ insurance_NN1 to_TO protect_VVI both_DB2 parts_NN2 benefits_NN2 and_CC choosing_VVG the_AT right_JJ suppliers_NN2 is_VBZ the_AT key_JJ part_NN1 of_IO minimizing_VVG the_AT purchasing_NN1 risk_NN1 ._. 
</s>
<s>
All_DB the_AT strategies_NN2 that_CST Volvo_NP1 referred_VVD above_RL are_VBR the_AT three_MC important_JJ parts_NN2 of_IO purchasing_VVG strategy_NN1 ._. 
</s>
<s>
I_PPIS1 think_VV0 that_CST no_DDQV31 matter_DDQV32 what_DDQV33 kind_NN1 of_IO enterprise_NN1 is_VBZ or_CC whatever_DDQV the_AT products_NN2 they_PPHS2 produced_VVD ,_, establishing_VVG the_AT partnership_NN1 ,_, reducing_VVG purchasing_NN1 cost_NN1 and_CC conducting_VVG the_AT risk_NN1 management_NN1 can_VM not_XX be_VBI neglected_VVN by_II the_AT firms_NN2 ._. 
</s>
<s>
These_DD2 have_VH0 the_AT same_DA function_NN1 for_IF those_DD2 electricity_NN1 retailers_NN2 in_II the_AT price_NN1 war_NN1 ._. 
</s>
<s>
Assume_VV0 that_CST they_PPHS2 did_VDD not_XX have_VHI good_JJ and_CC strong_JJ relationship_NN1 ,_, with_IW their_APPGE vendors_NN2 ,_, how_RRQ can_VM they_PPHS2 survive_VVI from_II the_AT large_JJ daily_JJ sales_NN in_II hundreds_NNO2 areas_NN2 without_IW continuous_JJ supplying_VVG resources_NN2 ._. 
</s>
<s>
If_CS they_PPHS2 did_VDD not_XX have_VHI an_AT1 enough_RR strict_JJ risk_NN1 management_NN1 ,_, how_RRQ could_VM they_PPHS2 ensure_VVI the_AT quality_NN1 of_IO the_AT products_NN2 ,_, and_CC how_RRQ could_VM they_PPHS2 dare_VVI to_TO challenge_VVI the_AT price_NN1 war_NN1 happened_VVD unexpected_JJ ._. 
</s>
<s>
Obviously_RR ,_, it_PPH1 is_VBZ not_XX enough_RR to_TO only_RR use_VVI these_DD2 3_MC strategies_NN2 ._. 
</s>
<s>
Evaluating_VVG and_CC optimizing_VVG the_AT vendors_NN2 ,_, carrying_VVG out_RP the_AT quality_NN1 management_NN1 ,_, choosing_VVG the_AT right_NN1 sourcing_VVG strategies_NN2 are_VBR all_DB necessary_JJ for_IF a_AT1 company_NN1 to_TO conduct_VVI ._. 
</s>
<s>
All_DB in_II all_DB ,_, each_DD1 company_NN1 has_VHZ to_TO make_VVI a_AT1 proper_JJ purchasing_NN1 strategies_NN2 relying_VVG on_II their_APPGE own_DA companys_NN2 conditions_NN2 ._. 
</s>
<s>
Integrate_VV0 each_DD1 internal_JJ strategy_NN1 and_CC consistent_JJ purchasing_NN1 with_IW other_JJ parts_NN2 of_IO the_AT company_NN1 to_TO strive_VVI for_IF and_CC realize_VVI the_AT maximum_JJ profit_NN1 for_IF the_AT enterprise_NN1 ._. 
</s>
<s>
6_MC ._. 
</s>
<s>
Discussion_NN1 and_CC conclusion_NN1 In_II todays_NN2 turbulent_JJ supply_NN1 markets_NN2 ,_, professional_JJ purchasing_NN1 is_VBZ expected_VVN to_TO be_VBI developed_VVN and_CC help_VV0 business_NN1 units_NN2 remain_VV0 competitive_JJ ._. 
</s>
<s>
But_CCB only_RR managing_VVG an_AT1 action_NN1 can_VM not_XX achieve_VVI the_AT goal_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ suggested_VVN that_CST there_EX should_VM be_VBI more_RGR comprehensive_JJ integration_NN1 of_IO the_AT purchasing_NN1 function_NN1 with_IW the_AT strategic_JJ and_CC competitive_JJ goals_NN2 of_IO a_AT1 firm_NN1 ._. 
</s>
<s>
There_EX is_VBZ no_AT single_JJ strategic_JJ goal_NN1 for_IF any_DD competitive_JJ firm_NN1 ._. 
</s>
<s>
Cost_VV0 minimization_NN1 is_VBZ not_XX always_RR the_AT only_JJ goal_NN1 that_CST the_AT company_NN1 pursues_VVZ ._. 
</s>
<s>
In_II turn_NN1 ,_, high-quality_JJ pursuing_JJ ,_, reliable_JJ delivery_NN1 performances_NN2 ,_, advanced_JJ IT_NN1 system_NN1 are_VBR goals_NN2 for_IF a_AT1 competitive_JJ firm_NN1 seek_VV0 to_TO reach_VVI as_RR21 well_RR22 ._. 
</s>
<s>
As_II a_AT1 result_NN1 ,_, purchasing_NN1 is_VBZ only_RR a_AT1 function_NN1 part_NN1 to_TO contribute_VVI to_II improvement_NN1 of_IO the_AT business_NN1 competitiveness_NN1 ._. 
</s>
<s>
Linkages_NN2 between_II purchasing_VVG decisions_NN2 and_CC firms_NN2 other_JJ competitive_JJ strategies_NN2 is_VBZ the_AT trend_NN1 and_CC the_AT key_JJ to_TO formulate_VVI a_AT1 competitive_JJ company_NN1 and_CC win_VVI a_AT1 position_NN1 in_II the_AT market_NN1 ._. 
</s>
<s>
In_II the_AT price_NN1 war_NN1 ,_, purchasing_VVG management_NN1 definitely_RR provides_VVZ a_AT1 strong_JJ bases_NN2 to_II the_AT electricity_NN1 retailers_NN2 ,_, and_CC its_APPGE functionality_NN1 can_VM not_XX be_VBI neglected_VVN when_CS evaluating_VVG the_AT performance_NN1 of_IO each_DD1 corporate_JJ ;_; nevertheless_RR ,_, a_AT1 firm_NN1 could_VM not_XX survive_VVI by_II only_RR implementing_VVG the_AT purchasing_NN1 management_NN1 ,_, it_PPH1 still_RR needs_VVZ an_AT1 integrated_JJ work_NN1 within_II each_DD1 function_NN1 of_IO the_AT firm_NN1 and_CC external_JJ partners_NN2 ._. 
</s>
