<s>
FEASIBILITY_NN1 STUDY_NN1 OF_IO BUSINESS_NN1 OPPORTUNITY_NN1 1_MC1 ._. 
</s>
<s>
Introduction_NN1 In_II China_NP1 ,_, knowledge_NN1 about_II Finland_NP1 is_VBZ limited_VVN at_II Scandinavian_JJ country_NN1 ,_, together_RL with_IW some_DD distinguishing_JJ images_NN2 such_II21 as_II22 Santa_NP1 Clause_NN1 and_CC Nokia_NP1 ._. 
</s>
<s>
There_EX are_VBR not_XX many_DA2 Chinese_JJ come_VV0 to_II Finland_NP1 and_CC settle_VV0 down_RP in_II the_AT country_NN1 for_IF longer_JJR period_NN1 compared_VVN with_IW the_AT population_NN1 Chinese_NN1 have_VH0 in_II other_JJ countries_NN2 ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 ,_, to_II the_AT writer_NN1 's_GE knowledge_NN1 ,_, Finnish_JJ culture_NN1 has_VHZ not_XX been_VBN promoted_VVN by_II any_DD non-_JJ governmental_JJ organization_NN1 up_II21 to_II22 now_RT ._. 
</s>
<s>
There_EX is_VBZ inner-connection_JJ between_II those_DD2 mentioned_VVN facts_NN2 ,_, which_DDQ has_VHZ impact_NN1 on_II causing_VVG the_AT vague_JJ image_NN1 of_IO Finland_NP1 among_II Chinese_JJ ._. 
</s>
<s>
Six_MC years_NNT2 in_II Finland_NP1 allows_VVZ the_AT writer_NN1 to_TO gain_VVI opportunities_NN2 to_TO familiarise_VVI with_IW Finland_NP1 ,_, and_CC to_TO acquire_VVI distinguishing_JJ features_NN2 of_IO the_AT country_NN1 ._. 
</s>
<s>
The_AT writer_NN1 appreciates_VVZ typically_RR lifestyle_NN1 and_CC attitude_NN1 of_IO Finns._NP1 1.1_MC ._. 
</s>
<s>
Purpose_VV0 The_AT purpose_NN1 of_IO the_AT study_NN1 is_VBZ to_TO evaluate_VVI feasibility_NN1 of_IO the_AT business_NN1 idea_NN1 ,_, and_CC come_VV0 up_RP with_IW practical_JJ solutions_NN2 for_IF it._NNU 1.2_MC ._. 
</s>
<s>
Objectives_NN2 The_AT writer_NN1 determines_VVZ to_TO carry_VVI on_RP the_AT business_NN1 idea_NN1 to_II practice_NN1 so_BCL21 as_BCL22 to_TO promote_VVI Finland_NP1 and_CC its_APPGE distinguishing_JJ features_NN2 to_II people_NN in_II China_NP1 ,_, especially_RR those_DD2 in_II Shanghai_NP1 ,_, in_II the_AT caf_NN1 Caf_NP1 Suomi_NP1 ;_; more_RRR importantly_RR ,_, the_AT caf_NN1 can_VM bring_VVI financial_JJ profitability_NN1 to_II the_AT writer._NNU 1.3_MC ._. 
</s>
<s>
Structure_NN1 In_II the_AT study_NN1 ,_, the_AT writer_NN1 will_VM identify_VVI the_AT business_NN1 and_CC its_APPGE opportunities_NN2 in_II chapter_NN1 2_MC ;_; in_II chapter_NN1 3_MC ,_, theoretical_JJ framework_NN1 is_VBZ given_VVN to_TO emphasize_VVI the_AT business_NN1 followed_VVN by_II analysis_NN1 of_IO feasibility_NN1 categories_NN2 in_II chapter_NN1 4_MC ,_, which_DDQ includes_VVZ product/service_NN1 ,_, market/industry_NN1 ,_, financial_JJ issues_NN2 ,_, and_CC organization_NN1 feasibility_NN1 ;_; in_II chapter_NN1 5_MC ,_, the_AT writer_NN1 will_VM have_VHI a_AT1 discussion_NN1 about_II analysis_NN1 ;_; last_MD but_CCB not_XX least_RRT ,_, summary_NN1 and_CC conclusion_NN1 are_VBR conducted_VVN in_II chapter_NN1 6._MC 2_MC ._. 
</s>
<s>
Business_NN1 in_RR21 brief_RR22 The_AT business_NN1 is_VBZ defined_VVN in_II four_MC phases_NN2 fundamentally_RR :_: Caf_VV0 as_RG elementary_JJ level_NN1 ,_, Caf_VV0 along_II21 with_II22 distinguishing_VVG Finnish_JJ features_NN2 in_II intermediate_JJ level_NN1 ,_, and_CC information_NN1 services_NN2 as_II31 well_II32 as_II33 in-store_JJ demonstration_NN1 are_VBR added_VVN up_RP in_II advanced_JJ level_NN1 ;_; for_IF long-term_JJ period_NN1 ,_, the_AT writer_NN1 intends_VVZ to_TO make_VVI Caf_NP1 Suomi_NP1 to_TO be_VBI a_AT1 Themed/Branding_JJ House_NN1 with_IW the_AT functions_NN2 of_IO encouraging_JJ people_NN to_TO spend_VVI their_APPGE leisure_NN1 time_NNT1 but_CCB also_RR being_VBG the_AT representative_JJ media_NN for_IF marketing_NN1 activities_NN2 about_II Finland_NP1 in_II Shanghai_NP1 even_RR in_II China_NP1 ._. 
</s>
<s>
Companies_NN2 will_VM be_VBI able_JK to_TO utilize_VVI Caf_NP1 Suomi_NP1 as_CSA platform_NN1 to_TO test_VVI business_NN1 opportunities_NN2 ,_, for_REX21 instance_REX22 ,_, expansion_NN1 ,_, and_CC merge_VV0 investment_NN1 ,_, before_II entering_VVG into_II the_AT massive_JJ Chinese_JJ market_NN1 ._. 
</s>
<s>
The_AT writer_NN1 understands_VVZ this_DD1 as_CSA business_NN1 opportunity_NN1 due_II21 to_II22 her_APPGE business_NN1 background_NN1 and_CC enthusiasms_NN2 to_II Finland_NP1 ._. 
</s>
<s>
She_PPHS1 believes_VVZ that_CST the_AT business_NN1 can_VM turn_VVI to_TO be_VBI profitable_JJ in_RR21 short_RR22 period_NN1 ,_, and_CC promote_VV0 Finland_NP1 through_II non-organizational_JJ channels._NNU 3_MC ._. 
</s>
<s>
Method_NN1 3.1_MC ._. 
</s>
<s>
Brand_NN1 positioning_NN1 Positioning_VVG the_AT brand_NN1 has_VHZ been_VBN long_RR acknowledged_VVN as_II a_AT1 core_NN1 branding_VVG activity_NN1 ._. 
</s>
<s>
This_DD1 involves_VVZ selecting_VVG specific_JJ attributes_NN2 with_IW which_DDQ it_PPH1 is_VBZ desirable_JJ for_IF the_AT brand_NN1 to_TO be_VBI associated_VVN ._. 
</s>
<s>
The_AT marketing/brand_NN1 manager_NN1 then_RT develops_VVZ a_AT1 plan_NN1 to_TO establish_VVI and/or_CC strengthen_VVI this_DD1 association_NN1 via_II marketing_NN1 communications_NN2 ._. 
</s>
<s>
(_( Romaniuk_VV0 2001_MC )_) 3.2_MC ._. 
</s>
<s>
Feasibility_NN1 study_NN1 A_ZZ1 feasibility_NN1 study_NN1 aligns_VVZ the_AT findings_NN2 with_IW functional_JJ processes_NN2 of_IO an_AT1 enterprise_NN1 which_DDQ an_AT1 audience_NN1 can_VM easily_RR understand_VVI ._. 
</s>
<s>
(_( Thompson_NP1 2003a_FO )_) ._. 
</s>
<s>
It_PPH1 provides_VVZ the_AT stakeholders_NN2 with_IW varying_JJ degrees_NN2 of_IO evidence_NN1 that_CST a_AT1 business_NN1 concept_NN1 will_NN1 in_II fact_NN1 be_VBI viable_JJ (_( Hoagland_NP1 and_CC Williamson_NP1 2000_MC ;_; Thompson_NP1 2003c_FO ;_; Thompson_NP1 2003a_FO ;_; Wickham_NP1 2004_MC )_) ._. 
</s>
<s>
4_MC ._. 
</s>
<s>
Analysis_NN1 4.1_MC ._. 
</s>
<s>
Product/Service_NN1 The_AT analysis_NN1 begins_VVZ with_IW introducing_VVG the_AT arrangement_NN1 of_IO business_NN1 by_II describing_VVG products_NN2 offered_VVN and_CC displayed_VVN in_II Caf_NP1 Suomi_NP1 ,_, its_APPGE related_JJ services_NN2 ,_, and_CC functions_NN2 at_II different_JJ stages_NN2 ._. 
</s>
<s>
Phase_NN1 1_MC1 :_: Caf_VV0 The_AT core_NN1 business_NN1 is_VBZ caf_NN1 ._. 
</s>
<s>
It_PPH1 serves_VVZ coffee_NN1 products_NN2 from_II Finland_NP1 i.e._REX Paulig_NP1 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, Caf_NP1 Suomi_NP1 offers_VVZ various_JJ refreshment_NN1 products_NN2 from_II Fazer_NN1 i.e._REX chocolate_NN1 ,_, biscuits_NN2 ,_, confectionery_NN1 and_CC bakeries_NN2 ._. 
</s>
<s>
Phase_NN1 2_MC :_: Caf_NP1 ,_, Apart_II21 from_II22 Phase_NN1 1_MC1 ,_, coffee_NN1 products_NN2 and_CC refreshments_NN2 will_VM be_VBI carried_VVN by_II Iittala_NP1 and_CC Arabia_NP1 ,_, which_DDQ have_VH0 products_NN2 for_IF eating_NN1 ,_, drinking_VVG ,_, cooking_VVG and_CC decorating_NN1 ._. 
</s>
<s>
Phase_NN1 3_MC :_: Caf_NP1 ,_, ,_, Finnish_JJ distinguishing_JJ features_NN2 Besides_II Phase_NN1 2_MC ,_, some_DD distinguishing_JJ features_NN2 will_VM be_VBI either_RR displayed_VVN or_CC used_VVN in_II the_AT cafeteria_NN1 ._. 
</s>
<s>
Moomin_NN1 ,_, Marimekko_NP1 ,_, and_CC Finnish_JJ designs_NN2 will_VM be_VBI presented_VVN ._. 
</s>
<s>
Phase_NN1 4_MC :_: Caf_NP1 ,_, ,_, Finnish_JJ distinguishing_JJ features_NN2 ,_, Information_NN1 Services/In-store_FU demonstration_NN1 In_II Phase_NN1 4_MC ,_, information_NN1 services_NN2 will_VM be_VBI added_VVN to_II value_NN1 proposition_NN1 ._. 
</s>
<s>
Information_NN1 related_VVN to_II Finland_NP1 will_VM be_VBI displayed_VVN ._. 
</s>
<s>
It_PPH1 contains_VVZ general_JJ information_NN1 about_II Finland_NP1 ,_, tourism_NN1 information_NN1 ,_, Finnish_JJ education_NN1 ,_, and_CC Finnish_JJ representative_JJ brands_NN2 ._. 
</s>
<s>
The_AT theme_NN1 of_IO the_AT caf_NN1 will_VM be_VBI elements_NN2 of_IO Finland_NP1 ,_, therefore_RR ,_, it_PPH1 only_RR serves_VVZ stuff_NN1 represent_VV0 Finland_NP1 or_CC from_II the_AT country_NN1 ._. 
</s>
<s>
Moreover_RR ,_, adaptions_NN2 to_II local_JJ business_NN1 environment_NN1 and_CC consumer_NN1 needs_NN2 are_VBR necessary_JJ ._. 
</s>
<s>
Proportion_NN1 in_II different_JJ food_NN1 and_CC drink_VV0 products_NN2 will_VM be_VBI adjusted_VVN to_TO appropriate_VVI local_JJ preferences_NN2 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, size_NN1 of_IO products_NN2 will_VM be_VBI adapted_VVN according_II21 to_II22 the_AT requirements_NN2 of_IO local_JJ people._NNU 4.2_MC ._. 
</s>
<s>
Market/Industry_NN1 The_AT writer_NN1 will_VM discuss_VVI the_AT market_NN1 of_IO the_AT business_NN1 ,_, outlining_VVG how_RRQ it_PPH1 should_VM be_VBI sold_VVN ._. 
</s>
<s>
It_PPH1 is_VBZ valuable_JJ to_TO understand_VVI current_JJ market_NN1 and_CC related_JJ consumer_NN1 base_NN1 before_II entering_VVG the_AT market_NN1 ._. 
</s>
<s>
Planning_VVG on_II brand_NN1 positioning_NN1 and_CC marketing_NN1 activities_NN2 need_VV0 to_TO be_VBI considered_VVN as_RR21 well._RR22 4.2.1_MC ._. 
</s>
<s>
City_NN1 background_NN1 Shanghai_NP1 is_VBZ one_MC1 of_IO the_AT largest_JJT cities_NN2 by_II population_NN1 in_II China_NP1 with_IW a_AT1 total_JJ population_NN1 of_IO over_RG 23_MC million_NNO as_II21 of_II22 2010_MC ._. 
</s>
<s>
With_IW the_AT rapid_JJ development_NN1 ,_, it_PPH1 becomes_VVZ a_AT1 global_JJ city_NN1 and_CC financial_JJ center_NN1 ,_, with_IW significant_JJ influence_NN1 in_II commerce_NN1 ,_, culture_NN1 ,_, finance_VV0 ,_, fashion_NN1 ,_, and_RR31 so_RR32 forth_RR33 ._. 
</s>
<s>
Shanghai_NP1 is_VBZ located_VVN in_II the_AT Yangtze_NP1 River_NNL1 Delta_NN1 in_II estern_JJ China_NP1 ,_, in_II the_AT middle_JJ portion_NN1 of_IO the_AT Chinese_JJ coast_NN1 ._. 
</s>
<s>
Due_II21 to_II22 the_AT favorable_JJ location_NN1 ,_, Shanghai_NP1 was_VBDZ one_MC1 of_IO the_AT cities_NN2 opened_VVN to_II foreign_JJ trade_NN1 in_II 1842_MC ._. 
</s>
<s>
The_AT city_NN1 flourished_VVD as_II a_AT1 center_NN1 of_IO commerce_NN1 between_II east_ND1 and_CC west_ND1 ,_, and_CC become_VV0 a_AT1 multinational_JJ hub_NN1 of_IO finance_NN1 and_CC business_NN1 since_CS the_AT 1930s_MC2 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, Shanghai_NP1 is_VBZ also_RR a_AT1 popular_JJ tourist_NN1 destination_NN1 ._. 
</s>
<s>
The_AT factors_NN2 make_VV0 the_AT city_NN1 to_TO be_VBI easy_JJ to_TO adapt_VVI ._. 
</s>
<s>
Today_RT ,_, Shanghai_NP1 is_VBZ one_MC1 of_IO the_AT most_RGT prosperous_JJ cities_NN2 in_II the_AT world_NN1 ._. 
</s>
<s>
Its_APPGE cosmopolitan_JJ character_NN1 ,_, sophisticated_JJ and_CC affluent_JJ consumers_NN2 ,_, and_CC highly_RR educated_JJ skilled_JJ labor_NN1 force_NN1 make_VV0 it_PPH1 highly_RR attractive_JJ to_II overseas_JJ investors._NNU 4.2.2_MC ._. 
</s>
<s>
Younger_JJR generation_NN1 Michael_NP1 Stanat_NP1 wrote_VVD in_II his_APPGE book_NN1 (_( Homa_NP1 &;_NULL Sekey_NP1 Books_NN2 2005_MC )_) :_: By_II the_AT year_NNT1 2020_MC ,_, China_NP1 is_VBZ expected_VVN to_TO become_VVI the_AT second_MD largest_JJT economy_NN1 in_II the_AT world_NN1 ,_, developing_VVG into_II a_AT1 vast_JJ consumer_NN1 market_NN1 with_IW a_AT1 sizeable_JJ middle_JJ class_NN1 ._. 
</s>
<s>
On_II every_AT1 newsstand_NN1 sits_VVZ a_AT1 magazine_NN1 issue_NN1 on_II China_NP1 fever_NN1 ._. 
</s>
<s>
Yet_RR even_RR after_II The_AT Reform_NN1 Era_NN1 in_II China_NP1 ,_, little_DA1 is_VBZ known_VVN about_II China_NP1 's_GE Generation_NN1 Y_ZZ1 ,_, consisting_VVG of_IO approximately_RR 200_MC million_NNO young_JJ individuals_NN2 born_VVN between_II 1980_MC and_CC 1989_MC ._. 
</s>
<s>
The_AT consuming_JJ capability_NN1 of_IO younger_JJR generation_NN1 becomes_VVZ stronger_JJR ,_, which_DDQ helps_VVZ stimulate_VVI economic_JJ growth_NN1 ._. 
</s>
<s>
They_PPHS2 have_VH0 money_NN1 for_IF their_APPGE disposals_NN2 and_CC are_VBR willing_JJ to_TO spend_VVI if_CSW the_AT products/services_NN2 match_VV0 their_APPGE personal_JJ positions_NN2 and_CC images_NN2 ._. 
</s>
<s>
Therefore_RR ,_, demanding_VVG for_IF theme_NN1 caf_NN1 such_II21 as_II22 Caf_NP1 Suomi_NP1 will_VM be_VBI a_AT1 hit_NN1 for_IF the_AT market_NN1 ._. 
</s>
<s>
Caf_VV0 Suomi_NP1 delivers_VVZ experience_NN1 to_II customers_NN2 as_CSA described_VVN below_RL that_DD1 is_VBZ where_RRQ value_NN1 comes_VVZ from._NNU 4.2.3_MC ._. 
</s>
<s>
Target_NN1 segment_NN1 The_AT caf_NN1 targets_NN2 younger_JJR generation_NN1 ,_, 20-35_MCMC year-old_JJ ascending_JJ middle_JJ class_NN1 who_PNQS are_VBR sophisticated_JJ and_CC have_VH0 disposable_JJ income_NN1 ._. 
</s>
<s>
They_PPHS2 pay_VV0 attention_NN1 to_II quality_NN1 and_CC want_VV0 to_TO enjoy_VVI life_NN1 with_IW a_AT1 little_JJ bit_NN1 of_IO the_AT indulgence_NN1 life_NN1 ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 ,_, earn_VV0 face_NN1 is_VBZ important_JJ for_IF Chinese_JJ people_NN by_II having_VHG high-end_JJ and_CC well-known_JJ stuff_NN1 ._. 
</s>
<s>
And_CC people_NN are_VBR willing_JJ to_TO show_VVI off_RP to_TO earn_VVI face_NN1 ._. 
</s>
<s>
Cafe_NN1 Suomi_NN1 will_VM make_VVI use_NN1 of_IO this_DD1 characteristic_NN1 to_TO attract_VVI customers._NNU 4.3_MC ._. 
</s>
<s>
Marketing_NN1 activities_NN2 Communication_NN1 is_VBZ vital_JJ in_II business_NN1 ._. 
</s>
<s>
The_AT business_NN1 communication_NN1 of_IO marketing_NN1 activities_NN2 includes_VVZ advertising_NN1 ,_, public_JJ relations_NN2 ,_, personal_JJ selling_NN1 ,_, and_CC any_DD form_NN1 of_IO communication_NN1 between_II the_AT firm_NN1 and_CC the_AT consumer_NN1 ._. 
</s>
<s>
The_AT writer_NN1 is_VBZ certainly_RR not_XX the_AT `_" first_MD mover'_NN1 of_IO this_DD1 kind_NN1 of_IO business_NN1 but_CCB it_PPH1 is_VBZ believed_VVN to_TO be_VBI the_AT first_MD one_PN1 who_PNQS brings_VVZ Finnish_JJ elements_NN2 to_II Shanghai_NP1 via_II non-governmental_JJ channel_NN1 ._. 
</s>
<s>
Therefore_RR ,_, differentiation_NN1 and_CC creative_JJ will_VM be_VBI selling_VVG points_NN2 ._. 
</s>
<s>
Scandinavia_NP1 characters_NN2 such_II21 as_II22 taste_NN1 ,_, decoration_NN1 ,_, ingredients_NN2 ,_, and_CC attitude_NN1 are_VBR emphasized_VVN as_CSA different_JJ spheres_NN2 to_II customers_NN2 in_II Shanghai_NP1 ._. 
</s>
<s>
Nowadays_RT people_NN in_II Shanghai_NP1 are_VBR busy_JJ in_II working_VVG and_CC improving_JJ financial_JJ conditions_NN2 so_CS21 that_CS22 they_PPHS2 forget_VV0 to_TO make_VVI kindly_RR break_VV0 sometimes_RT ._. 
</s>
<s>
Caf_VV0 Suomi_NP1 aims_VVZ to_TO be_VBI presented_VVN as_II a_AT1 place_NN1 where_RRQ people_NN can_VM relieve_VVI and_CC get_VVI more_DAR information_NN1 about_II the_AT country_NN1 ,_, and_CC perhaps_RR will_VM visit_VVI it_PPH1 later_RRR ,_, or_CC bring_VV0 mutual_JJ benefits_NN2 to_II both_DB2 countries_NN2 from_II various_JJ areas._NNU 4.3.1_MC ._. 
</s>
<s>
Convenience_NN1 With_IW the_AT rise_NN1 of_IO internet_NN1 and_CC hybrid_JJ models_NN2 of_IO information_NN1 gathering_NN1 and_CC exchanging_VVG as_RR21 well_RR22 sharing_VVG ,_, consumers_NN2 takes_VVZ convenience_NN1 into_II account_NN1 which_DDQ means_VVZ the_AT ease_NN1 of_IO buying_VVG the_AT product_NN1 as_II31 well_II32 as_II33 finding_VVG the_AT product_NN1 and_CC its_APPGE information._NNU -_- Location_NN1 Finding_NN1 business_NN1 location_NN1 is_VBZ crucial_JJ ._. 
</s>
<s>
There_EX will_VM be_VBI merely_RR the_AT caf_NN1 located_VVN in_II city_NN1 centre_NN1 area_NN1 ._. 
</s>
<s>
It_PPH1 can_VM be_VBI either_RR in_RP or_CC around_II big_JJ shopping_NN1 malls_NN2 or_CC quiet_JJ block_NN1 so_BCL21 as_BCL22 to_TO reinforce_VVI the_AT super-premium_JJ image_NN1 ._. 
</s>
<s>
The_AT only_JJ channel_NN1 people_NN can_VM buy_VVI or_CC perceive_VVI products_NN2 is_VBZ from_II the_AT caf_NN1 in_II where_RRQ it_PPH1 is_VBZ the_AT ideal_JJ environment_NN1 customers_NN2 can_VM experience_VVI everything_PN1 from_II Finland._NP1 -_- Information_NN1 finding_VVG People_NN can_VM find_VVI information_NN1 about_II Caf_NP1 Suomi_NP1 and_CC all_DB the_AT things_NN2 presented_VVN in_II the_AT store_NN1 from_II internet_NN1 ._. 
</s>
<s>
Moreover_RR ,_, the_AT writer_NN1 will_VM utilize_VVI various_JJ channels_NN2 to_TO promote_VVI ,_, e.g._REX official_JJ website_NN1 ,_, social_JJ media_NN (_( renren_NN1 ,_, kaixin_NN1 ,_, sinaweibo_NN1 and_CC etc._RA )_) ,_, and_CC personal_JJ blogs._NNU 4.3.2_MC ._. 
</s>
<s>
Brand_NN1 positioning_NN1 Country_NN1 of_IO origin_NN1 may_VM affect_VVI the_AT image_NN1 of_IO Caf_NP1 Suomi_NP1 favorably_RR ._. 
</s>
<s>
When_CS an_AT1 association_NN1 is_VBZ favorable_JJ ,_, the_AT country_NN1 of_IO origin_NN1 may_VM be_VBI emphasized_VVN ._. 
</s>
<s>
There_EX will_VM be_VBI diffusion_NN1 of_IO the_AT concept_NN1 ,_, and_CC moreover_RR ,_, the_AT brand_NN1 which_DDQ carries_VVZ the_AT concept_NN1 ._. 
</s>
<s>
Social_JJ class_NN1 is_VBZ going_VVGK to_TO be_VBI used_VVN in_II the_AT positioning_NN1 of_IO Caf_NP1 Suomi_NP1 ._. 
</s>
<s>
Up-ward_JJ pull_NN1 marketing_NN1 ,_, involves_VVZ positioning_VVG the_AT caf_NN1 for_IF mainstream_JJ consumers_NN2 but_CCB portraying_VVG it_PPH1 as_CSA being_VBG consumed_VVN by_II upper_JJ class_NN1 consumers_NN2 ._. 
</s>
<s>
Caf_VV0 Suomi_NN1 will_VM be_VBI careful_JJ when_CS selecting_VVG elements_NN2 including_II surroundings_NN2 ,_, decorations_NN2 and_CC etc_RA ,_, to_TO portray_VVI upscale_NN1 living._NNU 4.3.3_MC ._. 
</s>
<s>
Promotion_NN1 TV_NN1 exposure_NN1 :_: There_EX is_VBZ a_AT1 famous_JJ TV_NN1 channel_NN1 in_II Shanghai_NP1 ._. 
</s>
<s>
Its_APPGE target_NN1 audience_NN1 is_VBZ younger_JJR generation_NN1 with_IW the_AT ages_NN2 from_II 15_MC to_II 35_MC years_NNT2 old_JJ who_PNQS keep_VV0 updated_VVN about_II fashion_NN1 and_CC are_VBR willing_JJ to_TO pay_VVI for_IF that_DD1 ._. 
</s>
<s>
The_AT writer_NN1 will_VM get_VVI contact_NN1 with_IW the_AT channel_NN1 and_CC it_PPH1 's_VBZ the_AT most_RGT popular_JJ TV_NN1 program_NN1 ,_, obtaining_VVG an_AT1 opportunity_NN1 to_TO have_VHI an_AT1 interview_NN1 and_CC making_VVG video_NN1 clips_VVZ to_TO introduce_VVI Caf_NP1 Suomi_NP1 ._. 
</s>
<s>
Word_NN1 of_IO mouth_NN1 :_: Spread_VV0 the_AT messages_NN2 to_II Chinese_NP1 who_PNQS live_VV0 in_II Finland_NP1 as_RG much_DA1 as_CSA possible_JJ ,_, especially_RR to_II those_DD2 people_NN who_PNQS are_VBR from_II Shanghai_NP1 ,_, giving_VVG out_RP updated_JJ information_NN1 from_II social_JJ media_NN ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 ,_, send_VV0 electronic_JJ vouchers_NN2 to_II those_DD2 people_NN and_CC encourage_VV0 them_PPHO2 to_TO visit_VVI the_AT caf_NN1 when_CS they_PPHS2 go_VV0 back_RP Shanghai_NP1 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, ask_VV0 them_PPHO2 to_TO give_VVI those_DD2 vouchers_NN2 to_II their_APPGE friends_NN2 ,_, especially_RR those_DD2 in_II Shanghai_NP1 ._. 
</s>
<s>
Moreover_RR ,_, the_AT vouchers_NN2 will_VM be_VBI given_VVN to_II international_JJ people_NN ,_, especially_RR Finns_NN2 ,_, encouraging_VVG them_PPHO2 to_TO check_VVI out_RP the_AT caf_NN1 when_CS they_PPHS2 visit_VV0 Shanghai_NP1 ,_, giving_VVG them_PPHO2 the_AT opportunity_NN1 to_TO experience_VVI things_NN2 from_II home_NN1 country_NN1 when_CS they_PPHS2 are_VBR abroad_RL ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, there_EX is_VBZ an_AT1 association_NN1 for_IF Finnish_JJ people_NN who_PNQS live_VV0 in_II Shanghai_NP1 which_DDQ is_VBZ called_VVN Shanghain_JJ Suomalaisten_NP1 ._. 
</s>
<s>
The_AT writer_NN1 will_VM pay_VVI much_DA1 attention_NN1 to_II it_PPH1 and_CC eatablish_JJ relationship_NN1 with_IW the_AT association_NN1 ,_, encouraging_VVG those_DD2 Finns_NN2 in_II Shanghai_NP1 to_TO visit_VVI the_AT place_NN1 and_CC make_VVI contributions._NNU 4.3.4_MC ._. 
</s>
<s>
Competitors_NN2 Nestle_VV0 and_CC Unilever_NP1 are_VBR two_MC of_IO the_AT biggest_JJT competitors_NN2 ._. 
</s>
<s>
The_AT writer_NN1 will_VM have_VHI further_JJR investigation_NN1 in_II this_DD1 part._NNU 4.3.5_MC ._. 
</s>
<s>
Best_JJT practices_NN2 Hgen-Dazs_NN2 is_VBZ a_AT1 typical_JJ case_NN1 ._. 
</s>
<s>
It_PPH1 has_VHZ only_RR been_VBN in_II China_NP1 for_IF 15_MC years_NNT2 ,_, but_CCB it_PPH1 has_VHZ already_RR been_VBN the_AT No.2_FO foreign_JJ market_NN1 in_II its_APPGE business_NN1 ._. 
</s>
<s>
According_II21 to_II22 CNN_NP1 money_NN1 ,_, in_II China_NP1 alone_RR ,_, Hagen-Dazs_NN2 last_MD year_NNT1 brought_VVN in_II revenue_NN1 of_IO about_RG $100_NNU million_NNO ._. 
</s>
<s>
In_II the_AT last_MD three_MC years_NNT2 there_RL ,_, Hagen-Dazs_NN2 has_VHZ grown_VVN at_II an_AT1 annualized_JJ rate_NN1 of_IO 21%_NNU (_( CNN_NP1 MONEY_NN1 )_) ._. 
</s>
<s>
Evian_NN1 ,_, Zara_NP1 and_CC IKEA_NP1 are_VBR also_RR some_DD of_IO the_AT best_JJT practices_NN2 which_DDQ will_VM be_VBI studied_VVN by_II the_AT writer_NN1 for_IF further_JJR investigation._NNU 4.4_MC ._. 
</s>
<s>
Financial_JJ issues_NN2 Financial_JJ part_NN1 is_VBZ crucial_JJ in_II every_AT1 business_NN1 ._. 
</s>
<s>
In_II this_DD1 section_NN1 ,_, the_AT writer_NN1 will_VM illustrate_VVI general_JJ revenue_NN1 and_CC cost_NN1 ,_, i.e._REX how_RRQ money_NN1 will_VM be_VBI used_VVN and_CC how_RRQ it_PPH1 can_VM be_VBI accumulated_VVN ._. 
</s>
<s>
Cost_NN1 comes_VVZ always_RR early_JJ than_CSN revenue_NN1 ,_, thus_RR it_PPH1 is_VBZ necessary_JJ to_TO be_VBI aware_JJ of_IO it_PPH1 and_CC check_VV0 it_PPH1 time_NNT1 to_II time_NNT1 so_CS that_DD1 plan_NN1 can_VM be_VBI adjusted_VVN and_CC reactions_NN2 can_VM be_VBI done_VDN regarding_II to_II business_NN1 conditions_NN2 ._. 
</s>
<s>
The_AT business_NN1 has_VHZ the_AT principle_NN1 of_IO making_VVG a_AT1 large_JJ margin_NN1 on_II each_DD1 unit_NN1 it_PPH1 sells_VVZ and_CC settling_VVG for_IF fewer_DAR volumes_NN2 ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 ,_, the_AT writer_NN1 will_VM maximize_VVI captial_JJ by_II having_VHG supports_NN2 from_II funding_NN1 ,_, affiliating_VVG and_CC sponsoring_VVG ._. 
</s>
<s>
Cash_NN1 budget_NN1 will_VM be_VBI listed_VVN at_II the_AT beginning_NN1 of_IO every_AT1 month_NNT1 ,_, and_CC accounts_NN2 will_VM be_VBI settled_VVN by_II the_AT end_NN1 of_IO the_AT month_NNT1 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, observe_VV0 the_AT cash_NN1 flow_NN1 and_CC expenditure_NN1 from_RR41 time_RR42 to_RR43 time_RR44 ._. 
</s>
<s>
Product_NN1 and_CC material_NN1 ,_, rent_NN1 and_CC insurances_NN2 ,_, salaries_NN2 ,_, marketing_NN1 materials_NN2 ,_, travel_VV0 costs_NN2 ,_, taxes_NN2 ,_, investment_NN1 ,_, accounting_VVG ,_, and_CC legal_JJ advice_NN1 and_CC other_JJ expert_NN1 services_NN2 as_II31 well_II32 as_II33 phone_NN1 and_CC office_NN1 expenses_NN2 are_VBR primary_JJ issues_NN2 concerned_JJ in_II business_NN1 ,_, which_DDQ depend_VV0 on_II local_JJ business_NN1 situations_NN2 ,_, varied_VVN by_II economic_JJ conditions_NN2 ._. 
</s>
<s>
The_AT writer_NN1 is_VBZ going_VVGK to_TO make_VVI a_AT1 seperated_JJ plan_NN1 for_IF that_DD1 ._. 
</s>
<s>
Therefore_RR ,_, basic_JJ calculations_NN2 will_VM be_VBI made_VVN in_II this_DD1 study._NNU 4.4.1_MC ._. 
</s>
<s>
Product_NN1 and_CC material_NN1 Most_DAT of_IO the_AT products_NN2 and_CC raw_JJ materials_NN2 will_VM be_VBI shipped_VVN from_II supplier_NN1 companies_NN2 in_II Finland_NP1 if_CS they_PPHS2 can_VM not_XX be_VBI found_VVN in_II Shanghai_NP1 from_II those_DD2 original_JJ companies_NN2 ._. 
</s>
<s>
Seth_NP1 Gordin_NP1 (_( 2005_MC )_) stated_VVD in_II his_APPGE book_NN1 that_CST raw_JJ material_NN1 shares_NN2 small_JJ part_NN1 of_IO the_AT cost_NN1 along_II21 with_II22 working_VVG labor_NN1 ,_, shipping_VVG ._. 
</s>
<s>
However_RR ,_, retailers_NN2 have_VH0 good_JJ shares_NN2 on_II it_PPH1 ._. 
</s>
<s>
Therefore_RR ,_, try_VV0 to_TO get_VVI materials_NN2 and_CC products_NN2 from_II manufacturer_NN1 companies_NN2 will_VM minimize_VVI fixed_JJ prices_NN2 for_IF daily_JJ operation_NN1 ._. 
</s>
<s>
The_AT final_JJ price_NN1 to_II consumers_NN2 will_VM still_RR keep_VVI higher_JJR than_CSN normal_JJ caf_NN1 ,_, thus_RR ,_, the_AT margin_NN1 will_VM be_VBI better_JJR ._. 
</s>
<s>
For_REX21 instance_REX22 ,_, due_II21 to_II22 the_AT fact_NN1 that_CST raw_JJ material_NN1 will_VM be_VBI cheaper_JJR than_CSN end-products_NN2 ,_, therefore_RR ,_, coffee_NN1 bean_NN1 will_VM be_VBI shipped_VVN so_CS21 that_CS22 they_PPHS2 can_VM be_VBI processed_VVN in_II the_AT cafeteria_NN1 and_CC made_VVN to_II cups_NN2 of_IO coffee_NN1 by_II coffee_NN1 makers_NN2 bought_VVN in_II Shanghai._NP1 4.4.2_MC Rent_NN1 Rent_NN1 depends_VVZ on_II different_JJ district_NN1 and_CC type_NN1 of_IO places_NN2 ._. 
</s>
<s>
The_AT rent_NN1 of_IO the_AT place_NN1 is_VBZ ranged_VVN from_II 2000_MC euros_NN2 to_II 4000_MC eurosn_VV0 per_II month._NNU 4.4.3_MC ._. 
</s>
<s>
Insurance_NN1 It_PPH1 various_JJ at_II different_JJ companies_NN2 and_CC will_VM be_VBI decided_VVN later_RRR on._RP 4.4.4_MC ._. 
</s>
<s>
Salaries_NN2 Everyone_PN1 who_PNQS works_VVZ for_IF the_AT caf_NN1 will_VM have_VHI salary_NN1 including_II the_AT writer_NN1 ._. 
</s>
<s>
The_AT writer_NN1 will_VM get_VVI approximately_RR 300_MC euros_NN2 per_II month_NNT1 which_DDQ is_VBZ standard_JJ for_IF university_NN1 graduates_NN2 in_II Shanghai_NP1 ._. 
</s>
<s>
Those_DD2 employees_NN2 who_PNQS work_VV0 in_II the_AT caf_NN1 will_VM get_VVI similar_JJ salaries_NN2 as_II the_AT writer._NNU 4.4.5_MC ._. 
</s>
<s>
Marketing_NN1 activities_NN2 Marketing_NN1 will_VM be_VBI done_VDN via_II social_JJ media_NN channels_NN2 ,_, thus_RR ,_, word_NN1 of_IO mouth_NN1 will_VM be_VBI one_MC1 of_IO the_AT major_JJ channels_NN2 which_DDQ means_VVZ marketing_NN1 cost_NN1 will_VM be_VBI lower_JJR ._. 
</s>
<s>
Nevertheless_RR ,_, business_NN1 treatments_NN2 will_VM be_VBI major_JJ part_NN1 in_II the_AT activities_NN2 ._. 
</s>
<s>
It_PPH1 will_VM cost_VVI 1000_MC euros_NN2 per_II month_NNT1 at_II the_AT first_MD half_NN1 year._NNU 4.4.6_MC ._. 
</s>
<s>
Travel_VV0 costs_NN2 Since_CS the_AT business_NN1 is_VBZ between_II Finland_NP1 and_CC China_NP1 ,_, the_AT writer_NN1 will_VM travel_VVI between_II Finland_NP1 and_CC Shanghai_NP1 at_RR21 least_RR22 3_MC times_NNT2 a_AT1 year_NNT1 ,_, which_DDQ means_VVZ 3_MC times_NNT2 in_II 600_MC euros_NN2 ,_, i.e._REX 1800_MC euros_NN2 per_II year._NNU 4.4.7_MC ._. 
</s>
<s>
Investment_NN1 It_PPH1 is_VBZ main_JJ sources_NN2 of_IO captial_JJ in_II this_DD1 businss_NN1 ._. 
</s>
<s>
Government_NN1 and_CC company_NN1 assistance_NN1 will_VM be_VBI the_AT way_NN1 to_II attain._NNU 4.4.8_MC ._. 
</s>
<s>
Other_JJ expenditures_NN2 Other_JJ expenditures_NN2 such_II21 as_II22 taxes_NN2 ,_, accounting_VVG ,_, and_CC legal_JJ advice_NN1 and_CC other_JJ expert_NN1 services_NN2 vary_VV0 from_II locals_NN2 ._. 
</s>
<s>
Thus_RR ,_, it_PPH1 will_VM be_VBI investigated_VVN later._NNU 4.4.9_MC ._. 
</s>
<s>
Revenue_NN1 Selling_NN1 products_NN2 will_VM be_VBI the_AT source_NN1 of_IO revenue_NN1 in_II daily_JJ business_NN1 ._. 
</s>
<s>
Furthermore_RR ,_, when_CS Cafe_NN1 Suomi_NN1 gain_NN1 reputation_NN1 and_CC establish_VV0 brand_NN1 equity_NN1 ,_, companies_NN2 want_VV0 to_TO do_VDI marketing_NN1 activities_NN2 in_II Cafe_NN1 Suomi_NN1 will_VM pay_VVI for_IF that_DD1 ,_, which_DDQ is_VBZ another_DD1 revenue_NN1 for_IF business._NNU 4.5_MC ._. 
</s>
<s>
Organizational_JJ feasibility_NN1 The_AT writer_NN1 will_VM describe_VVI the_AT organization_NN1 structure_NN1 in_II the_AT section_NN1 ._. 
</s>
<s>
The_AT founder_NN1 of_IO Caf_NP1 Suomi_NP1 is_VBZ the_AT writer_NN1 who_PNQS is_VBZ in_II31 charge_II32 of_II33 most_DAT of_IO the_AT business_NN1 at_II the_AT very_JJ beginning_NN1 ._. 
</s>
<s>
She_PPHS1 will_VM contact_VVI all_DB kinds_NN2 of_IO companies_NN2 and_CC organizations_NN2 ._. 
</s>
<s>
Business_NN1 partners_NN2 help_VV0 to_TO deal_VVI with_IW business_NN1 contacts_NN2 and_CC information_NN1 fulfilment_NN1 as_RG well_RR as_CSA set_VVN up_RP appointments_NN2 ._. 
</s>
<s>
There_EX will_VM be_VBI 2-3_MCMC person_NN1 hired_VVN in_II the_AT caf_NN1 ,_, making_VVG products_NN2 ,_, taking_VVG care_NN1 of_IO customers_NN2 and_CC introducing_VVG related_JJ issues_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ not_XX necessary_JJ for_IF them_PPHO2 to_TO have_VHI uniform_JJ but_CCB they_PPHS2 will_VM be_VBI required_VVN to_TO present_VVI products_NN2 from_II Finland_NP1 such_II21 as_II22 Marimekko_NP1 products_NN2 or_CC some_DD accessories._NNU 5_MC ._. 
</s>
<s>
Discussion_NN1 This_DD1 is_VBZ the_AT first_MD draft_NN1 of_IO feasibility_NN1 study_NN1 of_IO the_AT Cafe_NN1 Suomi_NN1 ._. 
</s>
<s>
Further_JJR modification_NN1 ,_, research_NN1 and_CC investigation_NN1 will_VM be_VBI carried_VVN out_RP based_VVN on_II the_AT original_JJ one_PN1 later_RRR on_RP ._. 
</s>
<s>
Consumer_NN1 behaviours_NN2 and_CC their_APPGE consuming_JJ patterns_NN2 are_VBR different_JJ from_II Europe_NP1 ._. 
</s>
<s>
It_PPH1 can_VM not_XX be_VBI explained_VVN clearly_RR in_RR21 short_RR22 pages_NN2 ._. 
</s>
<s>
However_RR ,_, it_PPH1 is_VBZ going_VVGK to_TO be_VBI one_MC1 of_IO the_AT key_JJ elements_NN2 in_II achieving_VVG business_NN1 success_NN1 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, financial_JJ part_NN1 will_VM be_VBI specified_VVN to_II detail_NN1 ._. 
</s>
<s>
The_AT writer_NN1 will_VM have_VHI other_JJ studies_NN2 for_IF related_JJ topics_NN2 to_TO help_VVI investors_NN2 to_TO gain_VVI better_JJR understanding_NN1 ._. 
</s>
<s>
There_EX are_VBR also_RR useful_JJ links_NN2 to_TO assist_VVI the_AT writer_NN1 to_TO process_VVI business_NN1 idea_NN1 into_II practice._NNU 6_MC ._. 
</s>
<s>
Summary_NN1 and_CC Conclusion_NN1 
</s>
