<s>
The_AT use_NN1 of_IO video_NN1 in_II online_JJ marketing_NN1 1_MC1 INTRODUCTION_NN1 The_AT use_NN1 of_IO video_NN1 in_II online_JJ marketing_NN1 has_VHZ experienced_VVN a_AT1 rapid_JJ growth_NN1 over_II the_AT last_MD decade_NNT1 or_CC so_RG mainly_RR due_II21 to_II22 technological_JJ advances_NN2 ._. 
</s>
<s>
Klejna_NP1 (_( 2011:36_MC )_) states_VVZ that_CST in_II 2011_MC the_AT spending_NN1 in_II online_JJ video_NN1 advertisement_NN1 is_VBZ expected_VVN to_TO grow_VVI to_II $2.1_NNU billion_NNO ._. 
</s>
<s>
The_AT dynamic_JJ growth_NN1 of_IO the_AT industry_NN1 ,_, as_II31 well_II32 as_II33 its_APPGE cost-efficiency_NN1 ,_, makes_VVZ it_PPH1 an_AT1 increasingly_RR important_JJ medium_NN1 for_IF marketers_NN2 to_TO explore_VVI (_( New_JJ Media_NN Age_NN1 2004_MC ;_; Miller_NP1 2007_MC )_) ._. 
</s>
<s>
There_EX has_VHZ been_VBN extensive_JJ research_NN1 into_II what_DDQ kind_NN1 of_IO a_AT1 platform_NN1 the_AT Internet_NN1 provides_VVZ for_IF viewing_VVG animated_JJ material_NN1 (_( e.g._REX Kuisma_NP1 ,_, Simola_NP1 ,_, Uusitalo_NP1 ,_, and_CC rni_NN2 2010_MC )_) ,_, as_RG well_RR as_CSA about_II the_AT use_NN1 of_IO video_NN1 specifically_RR in_II online_JJ marketing_NN1 ._. 
</s>
<s>
The_AT approach_NN1 is_VBZ often_RR a_AT1 managerial_JJ one_PN1 ,_, where_CS the_AT issue_NN1 is_VBZ approached_VVN from_II the_AT "_" how-to_RRQ "_" angle_NN1 ._. 
</s>
<s>
The_AT questions_NN2 being_VBG asked_VVN are_VBR ,_, for_REX21 instance_REX22 :_: "_" how_RRQ to_TO get_VVI consumer_NN1 to_TO pay_VVI attention_NN1 to_II online_JJ video_NN1 advertising_NN1 ,_, "_" or_CC :_: "_" how_RRQ to_TO increase_VVI the_AT click-through_JJ rates_NN2 of_IO online_JJ video_NN1 ads_NN2 ._. "_" 
</s>
<s>
In_II31 addition_II32 to_II33 often_RR having_VHG a_AT1 managerial_JJ approach_NN1 ,_, the_AT articles_NN2 in_II this_DD1 field_NN1 are_VBR often_RR single-issue_JJ articles_NN2 ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, online_JJ marketing_NN1 articles_NN2 in_RR21 general_RR22 focus_VV0 on_II analysing_VVG a_AT1 particular_JJ issue_NN1 within_II this_DD1 field_NN1 ,_, such_II21 as_II22 animation_NN1 ,_, attitudes_NN2 ,_, recall_VV0 ,_, interactivity_NN1 ,_, experiences_NN2 ,_, attention_NN1 ,_, and_CC such_DA (_( see_VV0 e.g._REX Hoffmann_NP1 and_CC Novak_NP1 1996_MC ;_; Coyle_NP1 and_CC Thorson_NP1 2001_MC ;_; Kuisma_NP1 et_RA21 al_RA22 2010_MC )_) ._. 
</s>
<s>
There_EX is_VBZ ,_, however_RR ,_, very_RG little_DA1 research_NN1 that_CST brings_VVZ together_RL knowledge_NN1 from_II the_AT different_JJ angles_NN2 related_VVN to_II online_JJ video_NN1 marketing_NN1 ._. 
</s>
<s>
The_AT overall_JJ goal_NN1 of_IO this_DD1 study_NN1 is_VBZ to_TO accumulate_VVI some_DD of_IO the_AT collective_JJ knowledge_NN1 about_II the_AT use_NN1 of_IO video_NN1 in_II online_JJ marketing_NN1 ,_, and_CC analyze_VV0 its_APPGE current_JJ status_NN1 through_II a_AT1 content_JJ analysis_NN1 ._. 
</s>
<s>
Firstly_RR ,_, the_AT aim_NN1 is_VBZ to_TO provide_VVI a_AT1 comprehensive_JJ look_NN1 into_II what_DDQ is_VBZ meant_VVN by_II online_JJ video_NN1 advertising_NN1 ;_; this_DD1 is_VBZ done_VDN through_II a_AT1 literature_NN1 review_NN1 ._. 
</s>
<s>
Secondly_RR ,_, there_EX will_VM be_VBI an_AT1 examination_NN1 of_IO what_DDQ online_JJ video_NN1 advertising_NN1 ,_, also_RR known_VVN as_II viral_JJ video_NN1 marketing_NN1 ,_, looks_VVZ like_II today_RT by_II conducting_VVG a_AT1 content_JJ analysis_NN1 ._. 
</s>
<s>
In_II the_AT analysis_NN1 ,_, the_AT content_NN1 of_IO the_AT 10_MC of_IO most_DAT popular_JJ online_JJ viral_JJ advertisement_NN1 will_VM be_VBI carefully_RR analyzed_VVN ._. 
</s>
<s>
The_AT ultimate_JJ goal_NN1 is_VBZ to_TO give_VVI the_AT reader_NN1 a_AT1 thorough_JJ view_NN1 into_II the_AT world_NN1 online_JJ video_NN1 marketing_NN1 ._. 
</s>
<s>
There_EX exists_VVZ very_RG little_DA1 ,_, if_CS any_DD ,_, prior_JJ research_NN1 where_CS this_DD1 kind_NN1 of_IO compilation_NN1 has_VHZ been_VBN administered_VVN within_II one_MC1 study_NN1 ._. 
</s>
<s>
The_AT study_NN1 is_VBZ arranged_VVN as_CSA follows_VVZ :_: after_CS the_AT introduction_NN1 ,_, the_AT second_MD chapter_NN1 includes_VVZ the_AT literature_NN1 review_NN1 ._. 
</s>
<s>
The_AT third_MD chapter_NN1 includes_VVZ the_AT content_JJ analysis_NN1 of_IO the_AT chosen_JJ viral_JJ advertisements_NN2 ._. 
</s>
<s>
In_II the_AT fourth_MD and_CC final_JJ chapter_NN1 ,_, a_AT1 discussion_NN1 about_II the_AT results_NN2 and_CC their_APPGE limitations_NN2 is_VBZ enclosed._NNU 2_MC LITERATURE_NN1 REVIEW_NN1 In_II this_DD1 chapter_NN1 ,_, the_AT literature_NN1 review_VV0 in_RP regards_VVZ to_II interactive_JJ online_JJ marketing_NN1 and_CC the_AT use_NN1 of_IO online_JJ video_NN1 are_VBR included_VVN ._. 
</s>
<s>
This_DD1 chapter_NN1 aims_VVZ to_TO acquaint_VVI the_AT reader_NN1 with_IW the_AT origins_NN2 and_CC evolution_NN1 of_IO online_JJ video_NN1 with_IW a_AT1 focus_NN1 on_II marketing._NNU 2.1_MC ._. 
</s>
<s>
Video_NN1 in_II online_JJ marketing_NN1 When_CS the_AT Internet_NN1 first_MD started_VVD to_TO become_VVI popular_JJ amongst_II mass_JJ audiences_NN2 ,_, the_AT possibilities_NN2 it_PPH1 offered_VVD to_II marketers_NN2 seemed_VVD endless_JJ ,_, even_RR revolutionary_JJ ,_, according_II21 to_II22 some_DD early_JJ research_NN1 (_( e.g._REX Hoffman_NP1 and_CC Novak_NP1 1996_MC )_) ._. 
</s>
<s>
What_DDQ was_VBDZ revolutionary_JJ about_II the_AT World_NN1 Wide_JJ Web_NN1 was_VBDZ ,_, that_DD1 is_VBZ was_VBDZ changing_VVG the_AT way_NN1 in_II which_DDQ companies_NN2 could_VM communicate_VVI with_IW their_APPGE customers_NN2 ._. 
</s>
<s>
Up_II21 to_II22 this_DD1 stage_NN1 ,_, the_AT way_NN1 companies_NN2 carried_VVD out_RP their_APPGE communications_NN2 was_VBDZ with_IW an_AT1 orientation_NN1 to_II masses_NN2 (_( Hoffman_NP1 and_CC Novak_NP1 1996_MC )_) ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, a_AT1 firm_NN1 would_VM design_VVI a_AT1 standardized_JJ marketing_NN1 message_NN1 ,_, or_CC content_NN1 ,_, and_CC choose_VV0 a_AT1 mass_JJ media_NN outlet_NN1 (_( e.g._REX TV_NN1 )_) through_II which_DDQ the_AT content_NN1 would_VM be_VBI distributed_VVN to_II a_AT1 mass_JJ audience_NN1 (_( see_VV0 Figure_NN1 1_MC1 )_) ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) With_IW the_AT introduction_NN1 of_IO the_AT Internet_NN1 ,_, the_AT mass-approach_NN1 started_VVD to_TO change_VVI radically_RR ._. 
</s>
<s>
Developing_JJ online_JJ technology_NN1 allowed_VVD communication_NN1 to_TO evolve_VVI from_II the_AT "_" one-to-many_DA2 model_NN1 "_" to_II a_AT1 more_RGR interpersonal_JJ ,_, interactive_JJ ,_, and_CC two-way_JJ model_NN1 ,_, or_CC as_CSA Hoffman_NP1 and_CC Novak_NP1 (_( 1996_MC )_) describe_VV0 it_PPH1 :_: "_" many-to-many_DA2 model_NN1 "_" (_( see_VV0 Figure_NN1 2_MC )_) ._. 
</s>
<s>
&lsqb;_( Figure_NN1 &rsqb;_) Even_CS21 though_CS22 the_AT Internet_NP1 seemed_VVD to_TO offer_VVI endless_JJ marketing_NN1 possibilities_NN2 ,_, there_EX was_VBDZ also_RR some_DD scepticism_NN1 about_II the_AT effectiveness_NN1 of_IO the_AT new_JJ ,_, interactive_JJ medium_NN1 ._. 
</s>
<s>
Some_DD academics_NN2 questioned_VVD whether_CSW the_AT new_JJ medium_NN1 was_VBDZ ,_, in_II fact_NN1 ,_, superior_JJ to_II standard_JJ marketing_NN1 formats_NN2 ,_, or_CC just_RR an_AT1 overly_RR hyped_JJ phenomenon_NN1 (_( e.g._REX Bezjian-Avery_NP1 ,_, Calder_NP1 ,_, and_CC Iacobucci_NP1 1998_MC )_) ._. 
</s>
<s>
Technology_NN1 played_VVD a_AT1 quite_RG important_JJ part_NN1 in_II this_DD1 discussion_NN1 ;_; still_RR in_II the_AT 1990_MC 's_VBZ compared_VVN to_II today_RT the_AT Internet_NN1 was_VBDZ still_RR in_II its_APPGE infancy_NN1 in_II the_AT ability_NN1 to_TO show_VVI ,_, for_REX21 example_REX22 ,_, online_JJ videos_NN2 ._. 
</s>
<s>
Most_DAT Internet_NN1 users_NN2 were_VBDR still_RR using_VVG dial-up_NN1 connections_NN2 ,_, which_DDQ were_VBDR quite_RG slow_JJ and_CC not_XX able_JK to_TO handle_VVI large_JJ amounts_NN2 of_IO information_NN1 at_RR21 once_RR22 ._. 
</s>
<s>
Hence_RR ,_, the_AT use_NN1 of_IO ,_, for_REX21 instance_REX22 ,_, animated_JJ content_NN1 in_II marketing_NN1 was_VBDZ often_RR seen_VVN detrimental_JJ to_II the_AT success_NN1 of_IO the_AT marketed_JJ content_NN1 simply_RR because_CS the_AT medium_NN1 was_VBDZ not_XX able_JJ the_AT support_NN1 such_DA rich_JJ information_NN1 design_NN1 ._. 
</s>
<s>
The_AT shift_NN1 forward_RL both_RR in_II academic_JJ discussion_NN1 and_CC consumer_NN1 opinions_NN2 came_VVD with_IW the_AT introduction_NN1 of_IO new_JJ technologies_NN2 ,_, such_II21 as_II22 broadband_JJ connections_NN2 and_CC improved_JJ computer_NN1 capabilities_NN2 (_( e.g._REX faster_JJR and_CC increasingly_RR efficient_JJ laptops_NN2 and_CC desktops_NN2 )_) ._. 
</s>
<s>
From_II early_JJ 2000_MC221 's_MC222 onwards_RL ,_, it_PPH1 is_VBZ noticeable_JJ that_CST marketing-related_JJ scholarly_JJ discussion_NN1 moved_VVN from_II discussing_VVG the_AT nature_NN1 of_IO the_AT Internet_NN1 ,_, and_CC if_CS it_PPH1 should_VM be_VBI used_VVN in_II marketing_NN1 ,_, to_II how_RRQ it_PPH1 should_VM be_VBI used_VVN (_( e.g._REX Papacharissi_NP1 and_CC Rubin_NP1 2000_MC ;_; Dijkstra_NP1 ,_, Buijtels_NP2 ,_, and_CC van_NP1 Raaij_NP1 2005_MC ;_; Jensen_NP1 2008_MC ;_; Klejna_NP1 2011_MC )_) ._. 
</s>
<s>
The_AT technological_JJ developments_NN2 also_RR facilitated_VVD the_AT growth_NN1 of_IO the_AT internet_NN1 video_NN1 market_NN1 ._. 
</s>
<s>
Although_CS online_JJ videos_NN2 existed_VVD already_RR in_II the_AT 1990_MC221 's_MC222 (_( Bezjian-Avery_NP1 et_RA21 al._RA22 1998_MC )_) ,_, the_AT explosive_JJ growth_NN1 of_IO the_AT Internet_NN1 video_NN1 did_VDD not_XX take_VVI place_NN1 until_CS the_AT technological_JJ developments_NN2 enabled_VVD its_APPGE extensive_JJ and_CC effective_JJ use_NN1 ._. 
</s>
<s>
Today_RT ,_, the_AT market_NN1 continues_VVZ to_TO grow_VVI :_: based_VVN on_II a_AT1 survey_NN1 conducted_VVN in_II 2007_MC (_( Reynolds_NP1 2010_MC ,_, p._NN1 242_MC )_) ,_, where_CS 235_MC interactive_JJ marketers_NN2 were_VBDR asked_VVN "_" in_II the_AT next_MD three_MC years_NNT2 ,_, do_VD0 you_PPY think_VVI marketing_NN1 's_GE effectiveness_NN1 will_VM increase_VVI ,_, stay_VV0 the_AT same_DA ,_, or_CC decrease_VV0 in_RP ..._... the_AT following_JJ media_NN ?_? "_" approximately_RR 85%_NNU of_IO the_AT respondents_NN2 thought_VVD that_CST the_AT effectiveness_NN1 of_IO online_JJ video_NN1 would_VM increase_VVI ,_, ranking_VVG it_PPH1 the_AT 4th_MD effectiveness_NN1 increasing_VVG media_NN after_II social_JJ media_NN ,_, search_NN1 engine_NN1 marketing_NN1 ,_, and_CC mobile_NN1 ._. 
</s>
<s>
Furthemore_NN1 ,_, Klejna_NP1 (_( 2011:36_MC )_) estimated_VVD that_CST in_II 2011_MC ,_, the_AT online_JJ video_NN1 advertising_NN1 spending_NN1 would_VM amount_NN1 to_II over_RG 2.1_MC billion_NNO US_NP1 dollars_NNU2 ._. 
</s>
<s>
Thus_RR ,_, it_PPH1 is_VBZ quite_RG evident_JJ that_CST within_II the_AT marketing_NN1 discipline_NN1 ,_, online_JJ video_NN1 advertising_NN1 has_VHZ become_VVN a_AT1 key_JJ issue_NN1 ._. 
</s>
<s>
There_EX are_VBR many_DA2 different_JJ uses_NN2 of_IO online_JJ video_NN1 advertising_NN1 in_II existence_NN1 today_RT ,_, such_II21 as_II22 pre/post-roll_FU video_NN1 ,_, animated_JJ banners_NN2 ,_, and_CC viral_JJ videos_NN2 ._. 
</s>
<s>
Some_DD employ_VV0 techniques_NN2 from_II more_RGR traditional_JJ media_NN ._. 
</s>
<s>
For_REX21 example_REX22 ,_, the_AT video_NN1 commercials_NN2 often_RR seen_VVN in_II the_AT beginning_NN1 ,_, in_II the_AT middle_NN1 ,_, or_CC at_II the_AT end_NN1 of_IO another_DD1 video_NN1 that_CST a_AT1 consumer_NN1 is_VBZ watching_VVG ,_, also_RR known_VVN as_II linear_JJ in-stream_JJ advertisements_NN2 (_( Klejna_NP1 2011_MC )_) ,_, are_VBR types_NN2 of_IO videos_NN2 that_CST use_VV0 similar_JJ advertising_NN1 tactics_NN2 than_CSN traditional_JJ TV_NN1 advertising_NN1 ._. 
</s>
<s>
Especially_RR in_II the_AT infancy_NN1 of_IO the_AT online_JJ video_NN1 market_NN1 ,_, these_DD2 types_NN2 of_IO videos_NN2 were_VBDR typically_RR used_VVN as_CSA their_APPGE content_NN1 and_CC style_NN1 was_VBDZ easily_RR adoptable_JJ from_II the_AT traditional_JJ marketing_NN1 paradigm_NN1 ._. 
</s>
<s>
However_RR ,_, there_EX has_VHZ been_VBN some_DD criticism_NN1 against_II using_VVG the_AT so-called_JJ "_" one-way_JJ "_" traditional_JJ advertising_NN1 approaches_VVZ in_II the_AT virtual_JJ world_NN1 ,_, because_II21 of_II22 their_APPGE suggested_JJ unsuitability_NN1 for_IF the_AT Internet_NN1 ,_, which_DDQ is_VBZ seen_VVN as_II an_AT1 interactive_JJ "_" two-way_JJ "_" medium_NN1 ;_; also_RR ,_, such_DA advertisement_NN1 are_VBR seen_VVN to_TO disrupt_VVI the_AT experienced_JJ freedom_NN1 of_IO the_AT Internet_NP1 (_( i.e._REX the_AT freedom_NN1 to_TO choose_VVI to_TO view_VVI ,_, or_CC not_XX to_TO view_VVI ,_, particular_JJ content_NN1 )_) that_DD1 is_VBZ one_MC1 of_IO its_APPGE defining_JJ characteristics_NN2 (_( e.g._REX Liu_NP1 and_CC Shrum_NP1 2002_MC ;_; Wu_NP1 2006_MC )_) ._. 
</s>
<s>
Due_II21 to_II22 the_AT criticism_NN1 of_IO using_VVG traditional_JJ advertising_NN1 techniques_NN2 on_II the_AT Internet_NN1 ,_, and_CC the_AT increased_JJ realizations_NN2 of_IO its_APPGE opportunities_NN2 as_II a_AT1 creative_JJ medium_NN1 (_( Hampp_NP1 2011_MC )_) ,_, marketers_NN2 have_VH0 approached_VVN the_AT issue_NN1 in_II other_JJ ways_NN2 ._. 
</s>
<s>
Perhaps_RR one_MC1 of_IO the_AT most_RGT popular_JJ approaches_NN2 to_II online_JJ video_NN1 in_II the_AT recent_JJ years_NNT2 has_VHZ been_VBN the_AT utilization_NN1 of_IO the_AT viral_JJ video_NN1 ._. 
</s>
<s>
Viral_JJ videos_NN2 are_VBR videos_NN2 that_CST companies_NN2 create_VV0 for_IF marketing_NN1 purposes_NN2 ,_, often_RR with_IW funny_JJ or_CC clever_JJ content_NN1 ,_, that_CST become_VV0 popular_JJ by_II people_NN sharing_VVG them_PPHO2 with_IW each_PPX221 other_PPX222 through_II email_NN1 ,_, blogs_NN2 ,_, YouTube_NP1 ,_, and_CC other_JJ social_JJ media_NN websites_NN2 (_( Broxton_NP1 ,_, Interian_JJ ,_, Vaver_NP1 ,_, and_CC Wattenhofer_VV0 2011_MC )_) ._. 
</s>
<s>
Armstrong_NP1 and_CC Kotler_NP1 (_( as_CSA cited_VVN in_II Kulp_NP1 2007_MC )_) ,_, define_VV0 viral_JJ marketing_NN1 as_CSA "_" the_AT internet_NN1 version_NN1 of_IO word-of-mouth_JJ marketing--e-mail_JJ messages_NN2 or_CC other_JJ marketing_NN1 events_NN2 that_CST are_VBR so_RG infectious_JJ that_CST customers_NN2 will_VM want_VVI to_TO pass_VVI them_PPHO2 along_RP to_II friends_NN2 ._. "_" 
</s>
<s>
Viral_JJ videos_NN2 have_VH0 become_VVN to_TO represent_VVI one_MC1 of_IO the_AT most_RRT ,_, if_CS not_XX the_AT most_RRT ,_, popular_JJ advertising_NN1 techniques_NN2 used_VVN in_II viral_JJ marketing_NN1 campaigns_NN2 currently_RR (_( Cruz_NP1 and_CC Fill_VV0 2008_MC )_) ._. 
</s>
<s>
Thus_RR ,_, because_II21 of_II22 their_APPGE increasing_JJ importance_NN1 within_II the_AT marketing_NN1 ,_, and_CC particularly_RR e-marketing_JJ paradigm_NN1 ,_, popular_JJ viral_JJ videos_NN2 have_VH0 been_VBN chosen_VVN as_II the_AT subject_NN1 of_IO the_AT content_JJ analysis_NN1 ,_, which_DDQ is_VBZ included_VVN in_II next_MD chapter._NN1 3_MC CONTENT_JJ ANALYSIS_NN1 This_DD1 chapter_NN1 includes_VVZ the_AT content_JJ analysis_NN1 of_IO the_AT 10_MC most_RRT viewed_VVN online_RR viral_JJ advertisements_NN2 as_CSA listed_VVN by_II Advertising_NN1 Age_NN1 ._. 
</s>
<s>
The_AT chapter_NN1 begins_VVZ with_IW an_AT1 explanation_NN1 of_IO the_AT chosen_JJ videos_NN2 and_CC continues_VVZ with_IW the_AT analysis_NN1 of_IO the_AT content._NNU 3.1_MC ._. 
</s>
<s>
Choice_NN1 of_IO content_NN1 The_AT content_NN1 chosen_VVN for_IF this_DD1 analysis_NN1 originated_VVN from_II an_AT1 article_NN1 in_II the_AT magazine_NN1 Advertising_NN1 Age_NN1 (_( September_NPM1 2010_MC )_) ._. 
</s>
<s>
The_AT article_NN1 lists_VVZ the_AT 10_MC most_RRT viewed_VVN viral_JJ ad_NN1 campaign_NN1 of_IO all_DB time_NNT1 (_( up_RG21 to_RG22 2010_MC )_) ._. 
</s>
<s>
The_AT list_NN1 has_VHZ been_VBN compiled_VVN based_VVN on_II unique_JJ views_NN2 ,_, which_DDQ refers_VVZ to_II the_AT times_NNT2 a_AT1 viral_JJ video_NN1 has_VHZ been_VBN watched_VVN in_II total_NN1 ;_; unique_JJ views_NN2 are_VBR irrespective_JJ to_II how_RGQ many_DA2 times_NNT2 a_AT1 single_JJ user_NN1 has_VHZ watched_VVN it_PPH1 (_( businessdictionary.com_NNU )_) ._. 
</s>
<s>
The_AT videos_NN2 chosen_VVN for_IF the_AT analysis_NN1 are_VBR (_( brand_NN1 name_NN1 of_IO the_AT commercial_JJ how_RGQ many_DA2 total_JJ views_NN2 )_) :_: 1_MC1 ._. 
</s>
<s>
Blendtec_NP1 Will_NP1 It_NN1 Blend_NN1 134.2_MC million_NNO views_NN2 2_MC ._. 
</s>
<s>
Evian_JJ Live_JJ Young_JJ 103.9_MC million_NNO views_NN2 3_MC ._. 
</s>
<s>
Old_JJ Spice_NN1 Responses_NN2 57.1_MC million_NNO views_NN2 4_MC ._. 
</s>
<s>
Pepsi_NP1 Gladiator_NP1 46.7_MC million_NNO views_NN2 5_MC ._. 
</s>
<s>
Microsoft_NP1 Xbox_NP1 Project_NP1 Natal_NP1 42.7_MC million_NNO views_NN2 6_MC ._. 
</s>
<s>
Dove_NN1 Evolution_NN1 41.1_MC million_NNO views_NN2 7_MC ._. 
</s>
<s>
T-Mobile_JJ T-Mobile_JJ Dance_NN1 -_- 35.5_MC million_NNO views_NN2 8_MC ._. 
</s>
<s>
Doritos_NN2 Crash_VV0 the_AT Super_JJ Bowl_NN1 2010_MC 34.2_MC million_NNO views_NN2 9_MC ._. 
</s>
<s>
Old_JJ Spice_NN1 Odor_NP1 Blocker_NP1 34_MC million_NNO views_NN2 10_MC ._. 
</s>
<s>
DC_NP1 Shoes_NN2 Gymkhana_NP1 Two_MC 32.9_MC million_NNO views_NN2 3.2_MC ._. 
</s>
<s>
Analysis_NN1 of_IO content_JJ Like_JJ mentioned_VVN above_RL ,_, there_EX were_VBDR all_DB together_RL 10_MC viral_JJ videos_NN2 whose_DDQGE content_NN1 will_VM be_VBI analyzed_VVN in_II this_DD1 chapter_NN1 ._. 
</s>
<s>
Table_NN1 1_MC1 includes_VVZ the_AT description_NN1 of_IO each_DD1 commercial_JJ ,_, their_APPGE duration_NN1 ,_, and_CC their_APPGE style_NN1 ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) As_CSA we_PPIS2 can_VM see_VVI from_II the_AT table_NN1 ,_, this_DD1 group_NN1 of_IO videos_NN2 is_VBZ quite_RG heterogeneous_JJ in_II content_NN1 ,_, in_II length_NN1 ,_, and_CC in_II style_NN1 ._. 
</s>
<s>
Humor_NN1 ,_, however_RR ,_, seems_VVZ to_TO be_VBI a_AT1 connecting_JJ factor_NN1 ._. 
</s>
<s>
Humor_NN1 was_VBDZ a_AT1 central_JJ style_NN1 theme_NN1 in_II 4_MC out_II21 of_II22 10_MC videos_NN2 ._. 
</s>
<s>
Perhaps_RR due_II21 to_II22 the_AT fact_NN1 that_CST most_DAT of_IO these_DD2 commercials_NN2 are_VBR by_II American_JJ companies_NN2 ,_, the_AT humor_NN1 is_VBZ very_RG forward_RL ,_, even_RR deliberately_RR underlining_VVG ,_, as_II31 opposed_II32 to_II33 being_VBG the_AT more_RGR British-type_JJ ,_, subtle_JJ humor_NN1 ._. 
</s>
<s>
Cleverness_NN1 is_VBZ another_DD1 unifying_JJ characteristic_NN1 in_RP regards_VVZ to_II some_DD of_IO the_AT videos_NN2 ._. 
</s>
<s>
There_EX seems_VVZ to_TO be_VBI something_PN1 clever_JJ and_CC attention_NN1 capturing_VVG about_II many_DA2 of_IO the_AT videos_NN2 ,_, which_DDQ usually_RR comes_VVZ from_II a_AT1 good_JJ story_NN1 line_NN1 ,_, great_JJ editing_NN1 ,_, and_CC the_AT skillful_JJ use_NN1 of_IO music_NN1 ._. 
</s>
<s>
For_REX21 example_REX22 ,_, in_II the_AT Evian_JJ "_" Live_JJ Young_JJ "_" video_NN1 ,_, the_AT content_NN1 might_VM not_XX be_VBI as_RG funny_JJ if_CS the_AT song_NN1 "_" Rapper_NP1 's_GE Delight_NN1 "_" by_II the_AT Sugar_NP1 Hill_NNL1 Gang_NN1 was_VBDZ not_XX playing_VVG in_II the_AT background_NN1 ._. 
</s>
<s>
A_AT1 quite_RG perplexing_JJ feature_NN1 that_CST most_DAT of_IO the_AT videos_NN2 (_( 6/10_MF )_) seems_VVZ to_TO have_VHI in_RR21 common_RR22 ,_, is_VBZ that_DD1 they_PPHS2 are_VBR TV_NN1 commercial-like_JJ in_II their_APPGE content_NN1 ,_, and_CC how_RRQ the_AT content_NN1 is_VBZ presented_VVN to_II the_AT viewer_NN1 ._. 
</s>
<s>
This_DD1 is_VBZ an_AT1 unexpected_JJ result_NN1 ,_, because_CS research_NN1 would_VM suggest_VVI ,_, that_CST those_DD2 viral_JJ videos_NN2 where_RRQ the_AT brand_NN1 is_VBZ not_XX the_AT focal_JJ point_NN1 of_IO the_AT commercial_JJ are_VBR the_AT most_RGT successful_JJ ._. 
</s>
<s>
Hampp_NP1 (_( 2011_MC )_) states_VVZ that_CST :_: "_" Lightly_RR branded_JJ videos_NN2 that_CST function_NN1 as_CSA standalone_NN1 content_NN1 were_VBDR found_VVN to_TO be_VBI four_MC times_NNT2 more_RRR effective_JJ than_CSN heavily_RR branded_JJ videos_NN2 and_CC 10_MC times_NNT2 more_RRR effective_JJ than_CSN clips_NN2 with_IW a_AT1 call_NN1 to_II action_NN1 ._. "_" 
</s>
<s>
This_DD1 content_JJ analysis_NN1 disagrees_VVZ with_IW this_DD1 finding_NN1 ,_, because_CS in_II most_DAT of_IO the_AT videos_NN2 the_AT brand_NN1 is_VBZ at_II the_AT center_NN1 of_IO the_AT commercial_JJ and_CC quite_RG heavily_RR promoted_VVN ._. 
</s>
<s>
Regarding_II the_AT length_NN1 of_IO the_AT viral_JJ videos_NN2 ,_, most_DAT of_IO the_AT videos_NN2 are_VBR approximately_RR 2_MC minutes_NNT2 in_II length_NN1 ;_; all_DB together_RL 6_MC out_II21 of_II22 10_MC videos_NN2 are_VBR under_RG 2_MC minutes_NNT2 ._. 
</s>
<s>
However_RR ,_, the_AT length_NN1 of_IO the_AT videos_NN2 varies_VVZ from_II 30_MC seconds_NNT2 to_II over_RG 7_MC minutes_NNT2 ._. 
</s>
<s>
Thus_RR ,_, there_EX seems_VVZ to_TO be_VBI no_AT standard_NN1 to_II the_AT length_NN1 of_IO online_JJ advertising_NN1 videos_NN2 ._. 
</s>
<s>
This_DD1 says_VVZ something_PN1 about_II the_AT unrestricted_JJ nature_NN1 of_IO the_AT medium_NN1 ;_; most_DAT TV_NN1 commercials_NN2 tend_VV0 to_TO be_VBI quite_RG short_JJ as_CSA commercial_JJ breaks_NN2 need_VV0 to_TO include_VVI multiple_JJ commercials_NN2 in_II a_AT1 span_NN1 of_IO about_RG 5_MC minutes_NNT2 or_CC so_RG online_JJ videos_NN2 are_VBR not_XX bound_VVN by_II this_DD1 limitation_NN1 ._. 
</s>
<s>
Overall_RR ,_, the_AT Internet_NN1 as_II a_AT1 medium_NN1 offers_VVZ an_AT1 advertiser_NN1 quite_RG much_DA1 freedom_NN1 ,_, not_XX only_RR regards_VVZ to_II the_AT length_NN1 of_IO online_JJ videos_NN2 ,_, but_CCB also_RR their_APPGE creative_JJ content_NN1 ;_; it_PPH1 is_VBZ also_RR cost-_JJ effective_JJ ._. 
</s>
<s>
Any_DD company_NN1 ,_, either_RR small_JJ or_CC multinational_JJ ,_, can_VM produce_VVI clever_JJ content_NN1 on_II YouTube_NP1 ,_, for_REX21 example_REX22 ,_, and_CC get_VV0 millions_NNO2 of_IO views_NN2 within_II weeks_NNT2 ._. 
</s>
<s>
This_DD1 is_VBZ not_XX possible_JJ with_IW traditional_JJ mass_JJ marketing_NN1 where_CS a_AT1 two-week_JJ TV_NN1 campaign_NN1 might_VM cost_VVI hundreds_NNO2 of_IO thousands_NNO2 ._. 
</s>
<s>
As_CSA we_PPIS2 can_VM see_VVI from_II the_AT top_NN1 10_MC viral_JJ video_NN1 list_NN1 ,_, any_DD kind_NN1 of_IO online_JJ content_NN1 can_VM reach_VVI a_AT1 gigantic_JJ number_NN1 of_IO views_NN2 within_II a_AT1 relatively_RR limited_JJ time_NNT1 span_NN1 ;_; according_II21 to_II22 the_AT Advertising_NN1 Age_NN1 article_NN1 ,_, most_DAT of_IO the_AT videos_NN2 were_VBDR published_VVN after_II 2009_MC ,_, with_IW the_AT exception_NN1 of_IO two_MC videos_NN2 published_VVN in_II 2006_MC and_CC one_MC1 in_II 2004_MC ._. 
</s>
<s>
In_RP regards_VVZ to_II the_AT creative_JJ content_NN1 ,_, the_AT videos_NN2 on_II the_AT list_NN1 highlight_VV0 the_AT fact_NN1 that_CST the_AT content_NN1 of_IO an_AT1 online_JJ video_NN1 can_VM be_VBI highly_RR varying_VVG ._. 
</s>
<s>
For_REX21 example_REX22 ,_, the_AT T-Mobile_JJ video_NN1 can_VM be_VBI considered_VVN as_CSA quite_RG "_" viral-esque_JJ "_" meaning_NN1 that_CST it_PPH1 shows_VVZ real_JJ people_NN in_II a_AT1 real_JJ environment_NN1 with_IW something_PN1 extraordinary_JJ taking_JJ place_NN1 in_II this_DD1 everyday_JJ setting_NN1 ._. 
</s>
<s>
The_AT DC_NP1 Shoes_NN2 video_VV0 ,_, on_II the_AT other_JJ hand_NN1 ,_, has_VHZ a_AT1 "_" reality_NN1 "_" approach_NN1 as_RR21 well_RR22 but_CCB the_AT ad_NN1 is_VBZ structured_VVN similarly_RR to_II a_AT1 mini-documentary_NN1 with_IW people_NN in_II the_AT video_NN1 making_VVG comments_NN2 about_II the_AT surrounding_JJ events_NN2 ._. 
</s>
<s>
Furthermore_RR ,_, the_AT Blendtech_NN1 video_NN1 takes_VVZ a_AT1 subtle_JJ jab_NN1 at_II infomercials_NN2 ;_; the_AT Pepsi_NP1 video_NN1 relies_VVZ strongly_RR on_II the_AT celebrity_NN1 power_NN1 of_IO the_AT singers_NN2 Britney_NP1 Spears_NN2 ,_, Pink_JJ ,_, Beyonce_NP1 and_CC Enrique_NP1 Inglesias_NN2 ;_; the_AT Old_JJ Spice_NN1 commercials_NN2 feature_VV0 ex-NFL_JJ football_NN1 players_NN2 in_II the_AT shower_NN1 it_PPH1 seems_VVZ that_CST in_II a_AT1 viral_JJ video_NN1 ,_, almost_RR anything_PN1 goes._NNU 4_MC DISCUSSION_NN1 Based_VVN on_II this_DD1 content_JJ analysis_NN1 ,_, it_PPH1 can_VM be_VBI stated_VVN that_CST viral_JJ videos_NN2 are_VBR highly_RR varying_VVG in_RP regards_VVZ to_II their_APPGE length_NN1 ,_, content_NN1 ,_, and_CC style_NN1 ._. 
</s>
<s>
This_DD1 underlines_VVZ something_PN1 about_II the_AT medium_NN1 where_CS they_PPHS2 are_VBR presented_VVN ;_; for_IF a_AT1 marketer_NN1 ,_, the_AT Internet_NN1 offers_VVZ creative_JJ opportunities_NN2 that_CST are_VBR not_XX available_JJ in_II traditional_JJ media_NN ._. 
</s>
<s>
Humour_NN1 and_CC cleverness_NN1 ,_, however_RR ,_, seem_VV0 to_TO be_VBI two_MC universal_JJ features_NN2 found_VVN in_II many_DA2 viral_JJ videos_NN2 ._. 
</s>
<s>
According_II21 to_II22 Advertising_NN1 Age_NN1 ,_, humour_NN1 is_VBZ a_AT1 theme_NN1 that_CST seems_VVZ to_TO cross_VVI cultures_NN2 and_CC the_AT reason_NN1 it_PPH1 is_VBZ often_RR applied_VVN to_II viral_JJ videos_NN2 ._. 
</s>
<s>
The_AT key_JJ issue_NN1 when_CS it_PPH1 comes_VVZ to_II viral_JJ videos_NN2 seems_VVZ to_TO be_VBI the_AT creation_NN1 of_IO highly_RR clever_JJ and_CC universally_RR appealing_JJ content_NN1 ._. 
</s>
<s>
Hampp_NP1 (_( 2011_MC )_) notes_VVZ that_CST when_CS designing_VVG a_AT1 viral_JJ video_NN1 ,_, a_AT1 company_NN1 should_VM pick_VVI a_AT1 creative_JJ concept_NN1 with_IW the_AT ultimate_JJ intention_NN1 of_IO grab_NN1 attention_NN1 ,_, and_CC grabbing_VVG attention_NN1 quickly_RR ;_; "_" Stories_NN2 and_CC videos_NN2 that_CST gain_VV0 traction_NN1 in_II social_JJ media_NN do_VD0 so_RR quickly_RR ,_, often_RR within_II hours_NNT2 of_IO initial_JJ reports_NN2 ,_, and_CC they_PPHS2 fade_VV0 quickly_RR as_RR21 well_RR22 ._. "_" 
</s>
<s>
(_( Broxton_NP1 et_RA21 al_RA22 ._. 
</s>
<s>
2011_MC )_) However_RR ,_, some_DD videos_NN2 perhaps_RR the_AT ones_NN2 that_CST become_VV0 the_AT so-called_JJ classics_NN2 have_VH0 staying_NN1 power_NN1 like_II the_AT videos_NN2 on_II the_AT top_NN1 10_MC list_NN1 indicate_VV0 ._. 
</s>
<s>
The_AT Pepsi_NP1 video_NN1 was_VBDZ made_VVN in_II 2004_MC and_CC it_PPH1 is_VBZ still_RR one_MC1 of_IO the_AT most_RRT watched_VVN viral_JJ videos_NN2 of_IO all_DB time_NNT1 ._. 
</s>
<s>
It_PPH1 must_VM be_VBI stated_VVN that_CST even_CS21 though_CS22 viral_JJ videos_NN2 can_VM be_VBI immensely_RR popular_JJ ,_, as_CSA the_AT top_NN1 10_MC videos_NN2 indicate_VV0 ,_, not_XX all_DB viral_JJ videos_NN2 ,_, in_II fact_NN1 ,_, go_VV0 viral_JJ ._. 
</s>
<s>
This_DD1 is_VBZ one_MC1 of_IO the_AT disadvantages_NN2 of_IO using_VVG viral_JJ videos_NN2 in_II marketing_NN1 ;_; the_AT marketer_NN1 has_VHZ little_RR control_VV0 over_RP whether_CSW the_AT content_NN1 is_VBZ going_VVGK to_TO become_VVI popular_JJ or_CC not_XX ._. 
</s>
<s>
Watts_NP1 ,_, Peretti_NP1 ,_, and_CC Frumin_NP1 note_VV0 that_CST "_" For_IF every_AT1 high_JJ profile_NN1 example_NN1 of_IO a_AT1 viral_JJ product_NN1 ,_, there_EX are_VBR many_DA2 unsuccessful_JJ attempts_NN2 that_CST one_PN1 never_RR hears_VVZ about_II ..._... 
</s>
<s>
After_CS the_AT fact_NN1 ,_, it_PPH1 is_VBZ usually_RR possible_JJ to_TO understand_VVI what_DDQ was_VBDZ entertaining_JJ ,_, titillating_VVG ,_, or_CC otherwise_RR intriguing_JJ about_II a_AT1 given_JJ viral_JJ entity_NN1 ;_; but_CCB it_PPH1 is_VBZ rarely_RR obvious_JJ in_II advance_NN1 ._. "_" 
</s>
<s>
4.1_MC ._. 
</s>
<s>
Limitations_NN2 The_AT Doritos_NN2 commercial_JJ "_" Crash_NN1 the_AT Super_JJ Bowl_NN1 "_" was_VBDZ not_XX available_JJ for_IF viewing_VVG at_II the_AT time_NNT1 of_IO the_AT content_JJ analysis_NN1 ._. 
</s>
