<s>
1_MC1 ._. 
</s>
<s>
INTRODUCTION_NN1 1.1_MC Establishing_VVG A_AT1 Territory_NN1 In_II recent_JJ years_NNT2 ,_, there_EX have_VH0 been_VBN many_DA2 papers_NN2 doing_VDG research_NN1 on_II the_AT Corporate_JJ Social_JJ Responsibility_NN1 (_( CSR_NP1 )_) for_IF the_AT company_NN1 's_GE effects_NN2 on_II the_AT phenomenon_NN1 and_CC influences_NN2 on_II social_JJ welfare_NN1 ._. 
</s>
<s>
Also_RR there_EX has_VHZ been_VBN a_AT1 wide_JJ interest_NN1 of_IO firms_NN2 and_CC organizations_NN2 that_CST how_RRQ they_PPHS2 can_VM enhance_VVI their_APPGE brand_NN1 effects_NN2 by_II increasing_JJ brand_NN1 equity_NN1 in_II marketplaces_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ generally_RR accepted_VVN that_CST companies_NN2 nowadays_RT put_VV0 more_DAR effort_NN1 into_II strengthen_VV0 their_APPGE social_JJ awareness_NN1 when_CS they_PPHS2 implement_VV0 different_JJ kinds_NN2 of_IO marketing_NN1 activities_NN2 ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 ,_, naturally_RR ,_, the_AT company_NN1 's_GE brand_NN1 building_NN1 is_VBZ always_RR strategic_JJ and_CC necessary_JJ ._. 
</s>
<s>
Therefore_RR ,_, this_DD1 paper_NN1 intends_VVZ to_TO put_VVI eyesight_NN1 on_II brand_NN1 equity_NN1 enhancing_VVG ,_, in_II which_DDQ is_VBZ more_RGR practical_JJ and_CC differentiated_VVN if_CS the_AT company_NN1 's_GE social_JJ participations_NN2 involved_VVD ._. 
</s>
<s>
There_EX are_VBR observations_NN2 by_II Kapferer_NP1 (_( 2008_MC ,_, 1_MC1 )_) suggesting_VVG that_CST customers_NN2 are_VBR more_RRR empowered_VVN today_RT ;_; organizations_NN2 have_VH0 to_TO refine_VVI their_APPGE brands_NN2 and_CC optimize_VVI their_APPGE brand_NN1 strategies_NN2 accordingly_RR ._. 
</s>
<s>
Brand_NN1 equity_NN1 has_VHZ never_RR been_VBN more_RGR significant_JJ than_CSN it_PPH1 is_VBZ today_RT ._. 
</s>
<s>
At_II the_AT same_DA time_NNT1 ,_, there_EX is_VBZ now_RT much_DA1 evidence_NN1 by_II Lai_NP1 (_( et_RA21 al_RA22 ,_, 2010_MC )_) to_TO support_VVI the_AT idea_NN1 that_CST the_AT effects_NN2 of_IO corporate_JJ social_JJ responsibility_NN1 strengthen_VV0 the_AT organization_NN1 's_GE social_JJ relationship_NN1 with_IW the_AT target_NN1 customers_NN2 and_CC the_AT organization_NN1 's_GE reputation_NN1 so_CS21 that_CS22 the_AT brand_NN1 performance_NN1 can_VM be_VBI completed_VVN well_RR ._. 
</s>
<s>
1.2_MC Establishing_VVG A_AT1 Niche_NN1 However_RR ,_, this_DD1 view_NN1 is_VBZ challenged_VVN recently_RR ._. 
</s>
<s>
Since_CS previous_JJ studies_NN2 of_IO Temporal_JJ (_( 2010_MC ,_, 4_MC )_) highlighted_VVD that_DD1 brand_NN1 image_NN1 ,_, brand_NN1 identity_NN1 and_CC brand_NN1 awareness_NN1 can_VM be_VBI regarded_VVN as_II a_AT1 package_NN1 to_TO build_VVI a_AT1 company_NN1 's_GE whole_JJ brand_NN1 equity_NN1 ;_; at_II the_AT same_DA time_NNT1 ,_, corporate_JJ social_JJ responsibility_NN1 usually_RR covers_VVZ the_AT performances_NN2 from_II a_AT1 brand_NN1 's_GE image_NN1 and_CC identity_NN1 perspective_NN1 ._. 
</s>
<s>
Therefore_RR ,_, there_EX will_VM be_VBI a_AT1 stronger_JJR need_NN1 to_TO investigate_VVI the_AT CSR_NP1 's_GE influence_NN1 on_II brand_NN1 and_CC brand_NN1 equity_NN1 ._. 
</s>
<s>
As_II a_AT1 result_NN1 ,_, no_AT comprehensive_JJ theory_NN1 appears_VVZ to_TO exist_VVI ._. 
</s>
<s>
Despite_II the_AT importance_NN1 of_IO that_DD1 CSR_NP1 impacts_NN2 brand_VV0 image_NN1 and_CC brand_NN1 reputation_NN1 in_II customers_NN2 '_GE mind_NN1 ;_; few_DA2 researchers_NN2 have_VH0 studied_VVN further_RRR the_AT internal_JJ connection_NN1 between_II CSR_NP1 and_CC brand_NN1 equity_NN1 in_II an_AT1 organization_NN1 's_GE perspective_NN1 ._. 
</s>
<s>
Therefore_RR ,_, the_AT remaining_JJ and_CC unclear_JJ situation_NN1 leads_VVZ to_II a_AT1 question_NN1 :_: how_RRQ does_VDZ the_AT corporate_JJ social_JJ responsibility_NN1 effect_NN1 an_AT1 organization_NN1 's_GE brand_NN1 equity_NN1 in_II a_AT1 positive_JJ way_NN1 ?_? 1.3_MC Occupying_VVG the_AT Niche_NN1 The_AT statements_NN2 mentioned_VVN above_RL actually_RR present_VV0 a_AT1 research_NN1 gap_NN1 ._. 
</s>
<s>
This_DD1 paper_NN1 evaluates_VVZ the_AT effect_NN1 on_II current_JJ research_NN1 both_RR corporate_JJ social_JJ responsibility_NN1 and_CC brand_NN1 equity_NN1 by_II studying_VVG a_AT1 famous_JJ English_JJ football_NN1 club_NN1 Manchester_NP1 United_JJ ._. 
</s>
<s>
Many_DA2 newly_RR information_NN1 concerning_II sport_NN1 and_CC football_NN1 industry_NN1 under_II social_JJ context_NN1 will_VM be_VBI provided_VVN ._. 
</s>
<s>
This_DD1 paper_NN1 contributes_VVZ to_TO understand_VVI how_RRQ Manchester_NP1 United_JJ Football_NN1 Club_NN1 enriches_VVZ brand_NN1 equity_NN1 in_II target_NN1 fans_NN2 '_GE minds_NN2 by_II implementing_VVG the_AT differentiated_JJ aspects_NN2 from_II corporate_JJ social_JJ activity_NN1 ._. 
</s>
<s>
Both_DB2 the_AT qualitative_JJ and_CC quantitative_JJ research_NN1 methord_NN1 are_VBR adapted_VVN ._. 
</s>
<s>
Qualitative_JJ research_NN1 data_NN adapted_VVN in_II this_DD1 paper_NN1 are_VBR gathered_VVN during_II an_AT1 interview_NN1 of_IO companies_NN2 ,_, social_JJ organizations_NN2 and_CC fans_NN2 forums_NN2 ;_; quantitative_JJ research_NN1 data_NN are_VBR collected_VVN by_II delivering_VVG questionnaire_NN1 to_II big_JJ fans_NN2 database_NN1 ._. 
</s>
<s>
This_DD1 rest_NN1 of_IO paper_NN1 is_VBZ structured_VVN into_II five_MC sections_NN2 :_: 1_MC1 )_) The_AT definition_NN1 ,_, properties_NN2 and_CC features_NN2 of_IO both_RR CSR_NP1 and_CC brand_NN1 equity_NN1 will_VM be_VBI presented_VVN as_CSA literature_NN1 reviews_NN2 ._. 
</s>
<s>
2_MC )_) Each_DD1 segmental_JJ item_NN1 and_CC sub-concept_NN1 concerning_II CSR_NP1 will_VM be_VBI explained_VVN separately_RR ,_, combining_VVG the_AT intentions_NN2 towards_II brand_NN1 equity_NN1 reinforcement_NN1 ._. 
</s>
<s>
3_MC )_) The_AT methodology_NN1 used_VVN in_II the_AT study_NN1 will_VM be_VBI discussed_VVN ._. 
</s>
<s>
4_MC )_) The_AT results_NN2 of_IO the_AT empirical_JJ findings_NN2 will_VM be_VBI illuminated_VVN ._. 
</s>
<s>
5_MC )_) A_ZZ1 summary_NN1 and_CC conclusion_NN1 will_VM be_VBI established_VVN according_II21 to_II22 a_AT1 research_NN1 framework_NN1 and_CC empirical_JJ findings_NN2 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, a_AT1 managerial_JJ implication_NN1 for_IF further_JJR research_NN1 will_VM be_VBI drawn_VVN at_RR21 last_RR22 ._. 
</s>
<s>
2_MC ._. 
</s>
<s>
LITERRETURE_NP1 REVIEW_NN1 2.1_MC What_DDQ Is_VBZ Brand_NP1 ?_? 
</s>
<s>
A_AT1 brand_NN1 can_VM be_VBI defined_VVN as_II a_AT1 name_NN1 or_CC term_NN1 ,_, a_AT1 sign_NN1 or_CC symbol_NN1 ,_, a_AT1 design_NN1 ,_, or_CC a_AT1 mix_NN1 of_IO all_DB the_AT previous_JJ ;_; it_PPH1 intends_VVZ to_TO recognize_VVI goods_NN2 or_CC services_NN2 of_IO a_AT1 seller_NN1 while_CS distinguishing_VVG them_PPHO2 from_II those_DD2 of_IO others_NN2 ._. 
</s>
<s>
(_( American_JJ Marketing_NN1 Association_NN1 2011_MC )_) Kotler_NP1 (_( 1999_MC ,_, 404_MC )_) figured_VVD out_RP brand_NN1 as_II a_AT1 promise_NN1 from_II seller_NN1 ;_; the_AT promise_NN1 spreads_VVZ a_AT1 set_NN1 of_IO benefits_NN2 ,_, characteristics_NN2 ,_, services_NN2 to_II the_AT buyer_NN1 ._. 
</s>
<s>
Kapferer_NP1 (_( 2008_MC ,_, 9-10_MCMC )_) defined_VVD brand_NN1 from_II a_AT1 customer-orientated_JJ way_NN1 ._. 
</s>
<s>
He_PPHS1 thought_VVD brand_NN1 has_VHZ value_NN1 to_TO create_VVI awareness_NN1 ,_, belief_NN1 ,_, and_CC bond_VVI into_II receivers_NN2 '_GE minds_NN2 and_CC hearts_NN2 ._. 
</s>
<s>
However_RR ,_, Van_NP1 Gelder_NP1 (_( 2003_MC ,_, 1_MC1 )_) proposed_JJ brand_NN1 strategically_RR :_: brand_NN1 is_VBZ innovated_VVN ,_, stimulated_JJ and_CC operated_VVN by_II staffs_NN2 in_II organization_NN1 that_CST induce_VV0 behavior_NN1 benefits_NN2 back_RP to_II companies_NN2 ._. 
</s>
<s>
In_II this_DD1 paper_NN1 ,_, a_AT1 brand_NN1 is_VBZ an_AT1 intangible_JJ asset_NN1 held_VVN by_II the_AT service_NN1 providers_NN2 ;_; it_PPH1 dumps_NN2 an_AT1 organization_NN1 's_GE business_NN1 concepts_NN2 into_II the_AT customers_NN2 '_GE brains_NN2 ._. 
</s>
<s>
To_TO be_VBI precise_JJ ,_, brand_NN1 is_VBZ not_XX only_RR an_AT1 objective_NN1 we_PPIS2 can_VM look_VVI and_CC touch_VVI ,_, but_CCB also_RR an_AT1 image_NN1 we_PPIS2 can_VM think_VVI and_CC reflect_VVI ;_; Furthermore_RR ,_, it_PPH1 creates_VVZ a_AT1 relationship_NN1 of_IO interaction_NN1 between_II the_AT customers_NN2 and_CC the_AT service_NN1 providers_NN2 ._. 
</s>
<s>
2.2_MC What_DDQ Is_VBZ Brand_NP1 Equity_NN1 ?_? 
</s>
<s>
Weng_NP1 (_( 2006_MC ,_, 147-148_MCMC )_) proposed_VVD that_DD1 brand_NN1 equity_NN1 is_VBZ a_AT1 set_NN1 of_IO brand_NN1 assets_NN2 and_CC liabilities_NN2 attached_VVN to_II a_AT1 brand_NN1 ,_, whose_DDQGE name_NN1 and_CC symbol_NN1 subtracted_VVN from_II the_AT value_NN1 that_CST provided_VVD to_II companies_NN2 and_CC customers_NN2 ._. 
</s>
<s>
Views_NN2 from_II this_DD1 paper_NN1 ,_, brand_NN1 equity_NN1 impacts_NN2 information_NN1 proceeding_VVG ,_, creates_VVZ greater_JJR decision_NN1 making_VVG ,_, thereby_RR meets_VVZ customers_NN2 '_GE satisfaction_NN1 ._. 
</s>
<s>
He_PPHS1 continually_RR pointed_VVD out_RP that_DD1 brand_NN1 equity_NN1 assists_VVZ sellers_NN2 to_TO promote_VVI marketing_NN1 efficiency_NN1 and_CC effectiveness_NN1 ,_, establish_VV0 brand_NN1 loyalty_NN1 ,_, improve_VV0 profit_NN1 margins_NN2 ,_, receive_VV0 leverage_NN1 over_II retailers_NN2 and_CC fulfill_VV0 diversities_NN2 over_II the_AT competition_NN1 ._. 
</s>
<s>
Aaker_NN1 and_CC McLoughlin_NP1 (_( 2007_MC ,_, 174_MC )_) presented_VVD the_AT sources_NN2 of_IO brand_NN1 equity_NN1 :_: brand_NN1 awareness_NN1 ,_, perceived_VVD quality_NN1 ,_, brand_NN1 associations_NN2 ,_, and_CC brand_NN1 loyalty_NN1 ._. 
</s>
<s>
Brand_NN1 Awareness_NN1 is_VBZ the_AT strength_NN1 of_IO a_AT1 brand_NN1 's_GE presence_NN1 in_II the_AT mindset_NN1 of_IO a_AT1 consumer_NN1 ;_; it_PPH1 makes_VVZ customer_NN1 to_TO buy_VVI the_AT product_NN1 and_CC creates_VVZ a_AT1 foundation_NN1 of_IO relationship_NN1 that_CST binds_VVZ the_AT customer_NN1 and_CC service_NN1 provider_NN1 ._. 
</s>
<s>
High_JJ brand_NN1 awareness_NN1 associates_NN2 customer_NN1 strongly_RR and_CC makes_VVZ him_PPHO1 or_CC her_PPHO1 purchased_VVD the_AT thing_NN1 more_RGR frequently_RR ._. 
</s>
<s>
Sponsorship_NN1 is_VBZ an_AT1 important_JJ tool_NN1 to_TO constitute_VVI brand_NN1 awareness_NN1 ._. 
</s>
<s>
(_( Aaker_NN1 and_CC McLoughlin_NP1 2007_MC ,_, 174_MC )_) Perceived_VVD Quality_NN1 concentrates_VVZ on_II how_RRQ the_AT quality_NN1 perceptions_NN2 affect_VV0 a_AT1 customer_NN1 's_GE purchasing_NN1 behavior_NN1 ._. 
</s>
<s>
Its_APPGE technical_JJ and_CC functional_JJ aspects_NN2 make_VV0 a_AT1 larger_JJR amount_NN1 of_IO customers_NN2 to_TO patronize_VVI the_AT brand_NN1 ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 ,_, the_AT customer_NN1 's_GE pursuit_NN1 of_IO the_AT perceived_JJ quality_NN1 forms_VVZ quality_NN1 advancements_NN2 backwards_RL the_AT brand_NN1 provider_NN1 ._. 
</s>
<s>
(_( Aaker_NN1 and_CC McLoughlin_NP1 2007_MC ,_, 174_MC )_) Brand_NN1 Associations_NN2 are_VBR made_VVN with_IW a_AT1 brand_NN1 by_II consumer_NN1 ._. 
</s>
<s>
The_AT associations_NN2 help_VV0 a_AT1 consumer_NN1 to_TO connect_VVI with_IW the_AT brand_NN1 so_CS21 that_CS22 the_AT consumer_NN1 recall_NN1 or_CC rebuy_NN1 the_AT brand_NN1 ._. 
</s>
<s>
The_AT associations_NN2 can_VM be_VBI any_DD aspects_NN2 relate_VV0 to_TO brand_VVI ,_, such_II21 as_II22 brand_NN1 design_NN1 ,_, brand_NN1 symbol_NN1 ,_, and_CC brand_NN1 term_NN1 ._. 
</s>
<s>
Marketer_NN1 creates_VVZ brand_NN1 associations_NN2 ,_, usaully_RR ,_, by_II using_VVG marketing_NN1 mix_NN1 elements_NN2 :_: product_NN1 ,_, price_NN1 ,_, place_VV0 ,_, and_CC promotion_NN1 ._. 
</s>
<s>
(_( Aaker_NN1 and_CC McLoughlin_NP1 2007_MC ,_, 174_MC )_) Brand_NN1 Loyalty_NN1 is_VBZ the_AT key_JJ consideration_NN1 when_CS brand_NN1 provider_NN1 adds_VVZ value_NN1 into_II a_AT1 brand_NN1 ;_; it_PPH1 measures_VVZ or_CC determines_VVZ whether_CSW a_AT1 customer_NN1 is_VBZ willing_JJ to_II rebuy_NN1 the_AT brand_NN1 ._. 
</s>
<s>
A_AT1 center_NN1 issue_NN1 of_IO brand_NN1 loyalty_NN1 is_VBZ that_CST whether_CSW the_AT consumer_NN1 promotes_VVZ a_AT1 brand_NN1 to_II others_NN2 by_II word-of-mouth_NN1 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, the_AT already-made_JJ brand_NN1 loyalty_NN1 helps_VVZ brand_NN1 provider_NN1 to_TO get_VVI supports_NN2 from_II retailers_NN2 ;_; extensions_NN2 of_IO good_JJ brand_NN1 is_VBZ more_RGR attractive_JJ to_II retailers_NN2 ._. 
</s>
<s>
(_( Aaker_NN1 and_CC McLoughlin_NP1 2007_MC ,_, 174_MC )_) 2.3_MC What_DDQ is_VBZ CRM_NP1 ?_? 
</s>
<s>
To_TO define_VVI the_AT notion_NN1 of_IO CSR_NP1 (_( which_DDQ is_VBZ called_VVN fully_RR as_CSA corporate_JJ social_JJ responsibility_NN1 )_) is_VBZ more_RGR difficult_JJ than_CSN ever_RR before_RT ._. 
</s>
<s>
Each_DD1 organization_NN1 can_VM describe_VVI it_PPH1 from_II individual_JJ business_NN1 background_NN1 ._. 
</s>
<s>
Here_RL ,_, Schwartz_NP1 (_( 2011_MC ,_, 18_MC )_) brought_VVD an_AT1 idea_NN1 that_CST corporate_JJ social_JJ responsibility_NN1 is_VBZ an_AT1 extra_JJ obligation_NN1 of_IO responsibility_NN1 if_CS companies_NN2 have_VH0 only_RR economic_JJ and_CC legal_JJ obligations_NN2 ;_; the_AT social_JJ responsibility_NN1 acts_VVZ as_II the_AT obligations_NN2 drives_VVZ managers_NN2 to_TO promote_VVI and_CC improve_VVI the_AT fortune_NN1 of_IO the_AT society_NN1 along_II21 with_II22 their_APPGE own_DA interests_NN2 ._. 
</s>
<s>
He_PPHS1 continuelly_RR commended_VVD that_CST CSR_NP1 contributes_VVZ the_AT economic_JJ development_NN1 and_CC improves_VVZ the_AT quality_NN1 of_IO life_NN1 ;_; the_AT community_NN1 and_CC society_NN1 at_II large_JJ will_VM get_VVI benefits_NN2 from_II it_PPH1 ._. 
</s>
<s>
In_II Ruschak_NP1 's_GE (_( 2010_MC ,_, 8_MC )_) paper_NN1 ,_, he_PPHS1 inserted_VVD a_AT1 definition_NN1 from_II The_AT European_JJ Commission_NN1 that_CST corporate_JJ social_JJ responsibility_NN1 refers_VVZ to_II organization_NN1 's_GE performances_NN2 to_TO maintain_VVI developments_NN2 ._. 
</s>
<s>
The_AT main_JJ understanding_NN1 from_II CSR_NP1 activities_NN2 is_VBZ the_AT reflection_NN1 of_IO social_JJ importance_NN1 and_CC social_JJ consequences_NN2 that_CST are_VBR created_VVN from_II business_NN1 success_NN1 ._. 
</s>
<s>
In_II my_APPGE own_DA view_NN1 ,_, CSR_NP1 brings_VVZ an_AT1 idea_NN1 of_IO sustainable_JJ development_NN1 for_IF enterprises_NN2 that_CST need_VV0 to_TO consider_VVI other_JJ social_JJ issues_NN2 out_II21 of_II22 their_APPGE business_NN1 ._. 
</s>
<s>
Moreover_RR ,_, CSR_NP1 reflects_VVZ the_AT enterprises_NN2 responsibility_NN1 for_IF some_DD societal_JJ goods_NN2 not_XX only_RR in_II economic_JJ or_CC political_JJ ways_NN2 ,_, but_CCB also_RR in_II social_JJ way_NN1 ._. 
</s>
<s>
In_II the_AT other_JJ words_NN2 ,_, Enterprises_NN2 should_VM concern_VVI about_II outside_JJ groups_NN2 that_CST affected_VVD by_II themselves_PPX2 ._. 
</s>
<s>
2.4_MC Two_MC out_II21 of_II22 Four_MC Aspects_NN2 of_IO CSR_NP1 's_GE Effect_NN1 Although_CS we_PPIS2 have_VH0 talked_VVN much_RR about_II what_DDQ CSR_NP1 is_VBZ ,_, how_RRQ it_PPH1 influences_VVZ the_AT inside_NN1 of_IO an_AT1 organization_NN1 ?_? 
</s>
<s>
Paetzold_NP1 (_( 2010_MC ,_, 23_MC )_) here_RL listed_VVD 4_MC aspects_NN2 of_IO the_AT role_NN1 and_CC potential_NN1 of_IO CSR_NP1 that_CST can_VM influence_VVI the_AT organizations_NN2 '_GE business_NN1 activities_NN2 ._. 
</s>
<s>
The_AT four_MC aspects_NN2 are_VBR human_JJ resources_NN2 management_NN1 ,_, brand_NN1 differentiation_NN1 ,_, organizations_NN2 image_NN1 enhancement_NN1 ,_, and_CC revenues_NN2 improvement_NN1 ._. 
</s>
<s>
In_II this_DD1 paper_NN1 ,_, two_MC focuses_VVZ on_II CSR_NP1 Brand_NP1 Differentiation_NN1 and_CC CSR_NP1 Organizations_NN2 image_NN1 are_VBR unfolded_VVN ,_, because_CS they_PPHS2 are_VBR practical_JJ to_TO consider_VVI how_RRQ CSR_NP1 increases_VVZ brand_NN1 equity_NN1 of_IO one_MC1 organization_NN1 ._. 
</s>
<s>
Corporate_JJ social_JJ responsibility_NN1 can_VM be_VBI a_AT1 source_NN1 for_IF Brand_NN1 differentiation_NN1 ._. 
</s>
<s>
(_( Esposito_NN1 2009_MC ,_, 213_MC )_) He_PPHS1 pointed_VVD out_RP that_CST as_II the_AT customers_NN2 '_GE social_JJ awareness_NN1 increase_NN1 ;_; customers_NN2 are_VBR receptive_JJ to_II the_AT social_JJ responsibility_NN1 ,_, which_DDQ is_VBZ treated_VVN as_II an_AT1 approach_NN1 by_II companies_NN2 to_TO produce_VVI products_NN2 and_CC services_NN2 ._. 
</s>
<s>
At_II the_AT same_DA time_NNT1 ,_, these_DD2 customers_NN2 are_VBR willing_JJ to_TO pay_VVI a_AT1 higher_JJR price_NN1 for_IF more_RGR sustainable_JJ products_NN2 ._. 
</s>
<s>
Therefore_RR ,_, CRS_NP1 creates_VVZ explicit_JJ functions_NN2 (_( social_JJ ,_, public-interested_JJ ,_, sustainable_JJ ,_, or_CC environmental_JJ )_) into_II one_MC1 company_NN1 's_GE products_NN2 and_CC brand_NN1 ,_, so_CS21 that_CS22 customers_NN2 feel_VV0 differently_RR about_II the_AT influence_NN1 this_DD1 brand_NN1 brought_VVD compared_VVN with_IW that_DD1 of_IO others_NN2 brands_NN2 provided_VVN ._. 
</s>
<s>
The_AT excellent_JJ executed_JJ operation_NN1 of_IO CSR_NP1 can_VM be_VBI seen_VVN as_II an_AT1 important_JJ factor_NN1 leading_VVG an_AT1 organization_NN1 to_TO create_VVI a_AT1 positive_JJ image_NN1 in_II customers_NN2 '_GE mindset_NN1 and_CC to_TO be_VBI outstanding_JJ in_II the_AT competition_NN1 ._. 
</s>
<s>
(_( Ciszewski_NP1 ,_, 2012_MC )_) The_AT organization_NN1 's_GE image_NN1 can_VM be_VBI shifted_VVN into_II the_AT brand_NN1 image_NN1 if_CS the_AT branding_JJ activity_NN1 is_VBZ emphasized_VVN all_DB the_AT time_NNT1 by_II this_DD1 organization_NN1 ._. 
</s>
<s>
Organization_NN1 uses_VVZ CSR_NP1 to_TO improve_VVI its_APPGE brand_NN1 identity_NN1 and_CC brand_NN1 awareness_NN1 in_II customer_NN1 's_GE heart_NN1 ,_, usually_RR and_CC naturally_RR ,_, the_AT brand_NN1 image_NN1 is_VBZ enhanced_VVN ._. 
</s>
<s>
2.5_MC The_AT Pyramid_NN1 Model_NN1 of_IO CSR_NP1 Carroll_NP1 (_( 199_MC ,_, 500_MC )_) defined_VVD the_AT CSR_NP1 as_II the_AT "_" the_AT social_JJ responsibility_NN1 of_IO business_NN1 encompasses_VVZ the_AT economic_JJ ,_, legal_JJ ,_, ethical_JJ ,_, and_CC discretionary_JJ expectations_NN2 that_CST society_NN1 has_VHZ of_IO organizations_NN2 at_II a_AT1 given_JJ point_NN1 in_II time_NNT1 "_" ._. 
</s>
<s>
Dusuki_NN2 (_( 2008_MC )_) suggested_VVD that_CST for_IF a_AT1 corporate_JJ to_TO fully_RR comply_VVI with_IW its_APPGE social_JJ obligation_NN1 ,_, all_DB these_DD2 four_MC types_NN2 of_IO expectation_NN1 must_VM be_VBI matched_VVN ._. 
</s>
<s>
Carroll_NP1 named_VVD these_DD2 four_MC elements_NN2 in_II a_AT1 model_NN1 called_VVN the_AT Pyramid_NN1 of_IO CSR_NP1 ._. 
</s>
<s>
The_AT bottom_NN1 of_IO the_AT pyramid_NN1 is_VBZ economic_JJ responsibilities_NN2 ._. 
</s>
<s>
The_AT economic_JJ issue_NN1 is_VBZ the_AT initial_JJ stage_NN1 of_IO any_DD business_NN1 actions_NN2 made_VVN from_II an_AT1 organization_NN1 ;_; it_PPH1 must_VM be_VBI managed_VVN before_II the_AT organization_NN1 being_VBG engaged_VVN in_II any_DD social_JJ activities_NN2 ,_, such_II21 as_II22 charity_NN1 ._. 
</s>
<s>
The_AT economic_JJ responsibility_NN1 leads_VVZ to_II products_NN2 being_VBG sold_VVN at_II fair_JJ prices_NN2 in_II the_AT society_NN1 ,_, and_CC creates_VVZ profits_NN2 to_TO sustain_VVI the_AT organizations_NN2 '_GE development_NN1 ._. 
</s>
<s>
(_( Dusuki_NP1 2008_MC )_) The_AT dimension_NN1 in_II the_AT 3rd_MD layer_NN1 is_VBZ legal_JJ responsibilities_NN2 ._. 
</s>
<s>
Even_CS21 though_CS22 a_AT1 firms_NN2 '_GE business_NN1 is_VBZ expected_VVN with_IW high_JJ profit_NN1 ,_, it_PPH1 should_VM be_VBI sure_JJ that_CST business_NN1 activities_NN2 must_VM be_VBI fulfilled_VVN with_IW legal_JJ requirements_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ important_JJ for_IF a_AT1 firm_JJ to_TO undertake_VVI business_NN1 following_VVG government_NN1 and_CC legislation_NN1 obligations_NN2 ._. 
</s>
<s>
(_( Dusuki_NP1 2008_MC )_) The_AT next_MD dimension_NN1 in_II the_AT 2nd_MD layer_NN1 is_VBZ ethical_JJ responsibilities_NN2 ,_, which_DDQ refers_VVZ to_II the_AT organizations_NN2 '_GE social_JJ actions_NN2 and_CC should_VM be_VBI done_VDN ethically_RR ._. 
</s>
<s>
The_AT organization_NN1 should_VM try_VVI to_TO avoid_VVI any_DD business_NN1 actions_VVZ that_CST are_VBR forbidden_VVN by_II society_NN1 (_( although_CS those_DD2 are_VBR accepted_VVN by_II law_NN1 )_) ._. 
</s>
<s>
This_DD1 kind_NN1 of_IO responsibility_NN1 is_VBZ specially_RR related_VVN to_II those_DD2 social_JJ communities_NN2 who_PNQS expect_VV0 their_APPGE rights_NN2 are_VBR respected_VVN ._. 
</s>
<s>
Organizations_NN2 are_VBR required_VVN to_TO treat_VVI the_AT expectations_NN2 of_IO ethical_JJ norms_NN2 kindly_RR ,_, meanwhile_RR recognized_VVN and_CC respect_VV0 the_AT new_JJ ethical_JJ norms_NN2 adopted_VVN by_II society_NN1 ._. 
</s>
<s>
(_( Dusuki_NP1 2008_MC )_) The_AT last_MD dimension_NN1 on_II the_AT top_NN1 of_IO the_AT pyramid_NN1 is_VBZ philanthropic_JJ responsibilities_NN2 ._. 
</s>
<s>
The_AT philanthropic_JJ issue_NN1 drives_VVZ business_NN1 to_TO insert_VVI philanthropic_JJ activities_NN2 ._. 
</s>
<s>
The_AT philanthropic_JJ responsibilities_NN2 can_VM be_VBI in_II the_AT form_NN1 of_IO charities_NN2 ,_, donations_NN2 ,_, social-related_JJ sponsorships_NN2 ,_, or_CC voluntary_JJ contributions_NN2 ,_, which_DDQ are_VBR highly_RR appreciated_VVN by_II the_AT society_NN1 because_CS they_PPHS2 are_VBR naturally_RR voluntary_JJ ._. 
</s>
<s>
Organizations_NN2 are_VBR recommended_VVN to_TO encourage_VVI different_JJ communities_NN2 of_IO people_NN to_TO join_VVI in_II voluntary_JJ and_CC charitable_JJ activities_NN2 ,_, so_CS21 that_CS22 a_AT1 community_NN1 's_GE quality_NN1 of_IO life_NN1 can_VM be_VBI enhanced_VVN ._. 
</s>
<s>
(_( Dusuki_NP1 2008_MC )_) 3_MC ._. 
</s>
<s>
METHODOLOGY_NN1 3.1_MC Research_NN1 Method_NN1 Qualitative_JJ research_NN1 is_VBZ one_MC1 kind_NN1 of_IO inquiry_NN1 appropriate_JJ to_II specific_JJ topics_NN2 ._. 
</s>
<s>
Collecting_VVG and_CC gathering_VVG deeper_JJR understandings_NN2 of_IO human_JJ behavior_NN1 is_VBZ the_AT goal_NN1 of_IO qualitative_JJ research_NN1 ._. 
</s>
<s>
This_DD1 method_NN1 mainly_RR explores_VVZ the_AT why_RRQ ?_? and_CC how_RRQ ?_? of_IO decision_NN1 making_VVG ,_, not_XX only_RR what_DDQ ,_, where_RRQ ,_, or_CC when_RRQ ._. 
</s>
<s>
Therefore_RR ,_, the_AT smaller_JJR and_CC targeted_VVD sample_NN1 groups_NN2 are_VBR highly_RR welcomed_VVN to_TO be_VBI picked_VVN up_RP ,_, rather_II21 than_II22 large_JJ random_JJ sample_NN1 groups_NN2 ._. 
</s>
<s>
In_II the_AT other_JJ words_NN2 ,_, the_AT qualitative_JJ research_NN1 method_NN1 is_VBZ an_AT1 unstructured_JJ methodology_NN1 based_VVN on_II certain_JJ targeted_JJ groups_NN2 to_TO investigate_VVI insight_NN1 understanding_NN1 ._. 
</s>
<s>
(_( See_VV0 Denzin_NP1 K_NP1 &;_NULL Lincoln_NP1 2005_MC ,_, 1-3_MCMC )_) Quantitative_JJ research_NN1 is_VBZ a_AT1 more_RGR systematic_JJ and_CC scientific_JJ investigation_NN1 approach_NN1 ._. 
</s>
<s>
Conducting_VVG and_CC developing_JJ mathematical_JJ models_NN2 and_CC theories_NN2 or_CC anything_PN1 involve_VV0 natural_JJ senses_NN2 ._. 
</s>
<s>
Measurement_NN1 is_VBZ the_AT main_JJ and_CC central_JJ issue_NN1 of_IO quantitative_JJ research_NN1 ._. 
</s>
<s>
It_PPH1 connects_VVZ empirical_JJ observation_NN1 and_CC mathematical_JJ expression_NN1 ._. 
</s>
<s>
Therefore_RR ,_, quantitative_JJ research_NN1 is_VBZ a_AT1 structured_JJ methodology_NN1 according_II21 to_II22 wider_JJR sample_NN1 groups_NN2 to_TO quantify_VVI the_AT date_NN1 form_NN1 of_IO statistical_JJ analysis_NN1 ._. 
</s>
<s>
(_( See_VV0 Black_JJ 1999_MC ,_, 9-10_MCMC )_) In_II this_DD1 study_NN1 ,_, the_AT focus_NN1 is_VBZ on_II the_AT combination_NN1 of_IO both_DB2 quantitative_JJ research_NN1 method_NN1 and_CC the_AT qualitative_JJ research_NN1 method_NN1 ._. 
</s>
<s>
3.2_MC Sample_NN1 and_CC Data_NN Collection_NN1 3.3_MC Questionnaire_NN1 Design_NN1 3.4_MC Data_NN Analysis_NN1 Method_NN1 3.5_MC Reliability_NN1 and_CC Validity_NN1 4_MC ._. 
</s>
<s>
RESULTS_NN2 ANALYSIS_NN1 5_MC ._. 
</s>
<s>
DISCUSSION_NN1 6_MC ._. 
</s>
<s>
CONCLUSION_NN1 
</s>
