<s>
A_AT1 Qualitative_JJ Study_NN1 on_II Fairness_NN1 Factors_NN2 in_II Service_NN1 Recovery_NN1 1_MC1 ._. 
</s>
<s>
Introduction_NN1 Although_CS companies_NN2 strive_VV0 against_II errors_NN2 or_CC breakdowns_NN2 during_II service_NN1 delivery_NN1 ,_, it_PPH1 is_VBZ still_RR inevitable_JJ that_CST service_NN1 failures_NN2 do_VD0 happen_VVI in_II the_AT service_NN1 processes_NN2 ._. 
</s>
<s>
With_IW customers_NN2 '_GE increasing_JJ ability_NN1 to_TO influence_VVI others_NN2 ,_, any_DD service_NN1 failure_NN1 ,_, if_CS not_XX well_RR handled_VVN ,_, can_VM become_VVI a_AT1 disaster_NN1 for_IF service_NN1 providers_NN2 ._. 
</s>
<s>
According_II21 to_II22 one_MC1 study_NN1 ,_, customers_NN2 who_PNQS were_VBDR satisfied_VVN with_IW a_AT1 firms_NN2 recovery_NN1 efforts_NN2 told_VVD an_AT1 average_NN1 of_IO 7_MC people_NN ,_, whereas_CS those_DD2 customers_NN2 who_PNQS were_VBDR dissatisfied_JJ with_IW the_AT response_NN1 told_VVD an_AT1 average_NN1 of_IO 25_MC people_NN (_( Granier_NP1 et_RA21 al_RA22 ,_, 2004_MC )_) ._. 
</s>
<s>
It_PPH1 is_VBZ widely_RR accepted_VVN that_CST the_AT cost_NN1 of_IO attracting_VVG a_AT1 new_JJ customer_NN1 substantially_RR exceeds_VVZ the_AT cost_NN1 of_IO retaining_VVG an_AT1 existing_JJ customer_NN1 (_( Kotler_NP1 et_RA21 al._RA22 ,_, 2003_MC )_) ._. 
</s>
<s>
Therefore_RR ,_, it_PPH1 is_VBZ important_JJ for_IF companies_NN2 to_TO design_VVI and_CC manage_VVI service_NN1 recovery_NN1 process_NN1 so_CS21 that_CS22 they_PPHS2 can_VM build_VVI long-term_JJ relationships_NN2 with_IW existing_JJ customers_NN2 ._. 
</s>
<s>
Most_DAT of_IO the_AT previous_JJ studies_NN2 refer_VV0 to_II building_NN1 theories_NN2 describing_VVG service_NN1 recovery_NN1 processes_NN2 or_CC concerns_VVZ to_II how_RRQ to_TO restore_VVI consumer_NN1 satisfaction_NN1 (_( Tax_NN1 and_CC Brown_NP1 ,_, 1998_MC ,_, Bansal_NP1 and_CC Taylor_NP1 ,_, 1999_MC ,_, Seawright_NP1 et_RA21 al._RA22 ,_, 2007_MC ,_, Swanson_NP1 ,_, 2001_MC )_) ,_, but_CCB it_PPH1 is_VBZ still_RR unclear_JJ how_RRQ customers_NN2 evaluate_VV0 the_AT recovery_NN1 process_NN1 ,_, or_CC how_RRQ fairness_NN1 factors_NN2 intertwined_VVN to_TO influence_VVI customer_NN1 satisfaction_NN1 ._. 
</s>
<s>
Based_VVN on_II the_AT three_MC fairness_NN1 themes_NN2 in_II service_NN1 recovery_NN1 proposed_VVN by_II Wilson_NP1 et_RA21 al._RA22 (_( 2008_MC )_) ,_, this_DD1 study_NN1 aims_VVZ to_TO explore_VVI how_RRQ the_AT three_MC fairness_NN1 dimensions_NN2 work_VV0 and_CC affect_VV0 the_AT outcomes_NN2 of_IO service_NN1 recovery_NN1 ._. 
</s>
<s>
To_TO achieve_VVI this_DD1 goal_NN1 ,_, this_DD1 paper_NN1 examines_VVZ the_AT following_JJ questions_NN2 :_: what_DDQ do_VD0 customers_NN2 expect_VVI when_RRQ they_PPHS2 complain_VV0 ;_; how_RRQ do_VD0 customers_NN2 perceive_VVI justice_NN1 in_II the_AT service_NN1 recovery_NN1 process_NN1 ;_; and_CC how_RRQ does_VDZ a_AT1 service_NN1 recovery_NN1 ,_, successful_JJ or_CC unsuccessful_JJ ,_, affect_VV0 the_AT relationships_NN2 between_II customer_NN1 and_CC the_AT service_NN1 provider_NN1 ?_? 
</s>
<s>
To_TO achieve_VVI these_DD2 objectives_NN2 ,_, the_AT article_NN1 is_VBZ structured_VVN as_CSA follows_VVZ ._. 
</s>
<s>
First_MD we_PPIS2 will_VM briefly_RR introduce_VVI two_MC important_JJ theories_NN2 we_PPIS2 adopted_VVD in_II this_DD1 paper_NN1 ._. 
</s>
<s>
Then_RT the_AT methodology_NN1 of_IO the_AT empirical_JJ study_NN1 ,_, which_DDQ involves_VVZ the_AT presentation_NN1 of_IO the_AT interview_NN1 guide_NN1 and_CC data_NN collection_NN1 ._. 
</s>
<s>
The_AT third_MD part_NN1 contains_VVZ the_AT summary_NN1 of_IO the_AT interviews_NN2 as_II31 well_II32 as_II33 the_AT discussion_NN1 about_II the_AT data_NN analyses_NN2 ._. 
</s>
<s>
Finally_RR ,_, I_PPIS1 will_VM conclude_VVI with_IW managerial_JJ implications_NN2 of_IO the_AT findings_NN2 and_CC suggest_VV0 some_DD directions_NN2 for_IF further_JJR research_NN1 ._. 
</s>
<s>
2_MC ._. 
</s>
<s>
Theoretician_NN1 framework_NN1 2.1_MC Service_NN1 recovery_NN1 effects_NN2 Service_VV0 recovery_NN1 refers_VVZ to_II the_AT actions_NN2 taken_VVN by_II an_AT1 organization_NN1 in_II31 response_II32 to_II33 a_AT1 service_NN1 failure_NN1 (_( Wilson_NP1 et_RA21 al._RA22 ,_, 2008_MC )_) ._. 
</s>
<s>
Service_NN1 failure_NN1 occur_VV0 for_IF all_DB kins_NN2 of_IO reasons_NN2 ,_, the_AT service_NN1 may_VM be_VBI unavailable_JJ when_CS promised_VVN ,_, it_PPH1 may_VM be_VBI delivered_VVN late_JJ or_CC too_RG slow_JJ ,_, the_AT outcome_NN1 may_VM be_VBI incorrect_JJ or_CC poorly_RR executed_VVN or_CC employees_NN2 may_VM be_VBI rude_JJ or_CC uncaring_JJ (_( Wilson_NP1 et_RA21 al._RA22 ,_, 2008_MC )_) ._. 
</s>
<s>
Companies_NN2 have_VH0 realized_VVN that_CST attracting_VVG a_AT1 new_JJ customer_NN1 costs_VVZ much_DA1 more_DAR than_CSN retaining_VVG an_AT1 existing_JJ customer_NN1 ,_, this_DD1 means_VVZ if_CS companies_NN2 can_VM implement_VVI effective_JJ service_NN1 recovery_NN1 strategies_NN2 ,_, they_PPHS2 are_VBR more_RGR likely_JJ to_TO keep_VVI a_AT1 long-term_JJ relationship_NN1 with_IW their_APPGE customers_NN2 in_II a_AT1 cost-effective_JJ way.Previous_NNU studies_NN2 have_VH0 shown_VVN that_CST resolving_VVG customer_NN1 problems_NN2 effectively_RR has_VHZ a_AT1 strong_JJ impact_NN1 on_II customer_NN1 satisfaction_NN1 ,_, loyalty_NN1 ,_, world-of-mouth_JJ communication_NN1 and_CC bottom-line_JJ performance_NN1 (_( Wilson_NP1 et_RA21 al._RA22 ,_, 2008_MC )_) ._. 
</s>
<s>
Unfortunately_RR ,_, many_DA2 firms_NN2 do_VD0 not_XX employ_VVI effective_JJ recovery_NN1 strategies_NN2 ._. 
</s>
<s>
Studies_NN2 have_VH0 shown_VVN that_CST as_RG many_DA2 as_CSA half_DB of_IO businesses_NN2 '_GE responses_NN2 to_II problems_NN2 actually_RR intensifyrather_NN1 than_CSN mitigatecustomers_NN2 '_GE negative_JJ feelings_NN2 toward_II the_AT organization_NN1 (_( HarHart_NP1 et_RA21 al._RA22 ,_, 1990_MC )_) ._. 
</s>
<s>
While_CS a_AT1 good_JJ service_NN1 recovery_NN1 design_NN1 can_VM significantly_RR enhance_VVI a_AT1 customer_NN1 's_GE perceptions_NN2 of_IO the_AT quality_NN1 of_IO products_NN2 or_CC services_NN2 already_RR purchased_VVN ,_, the_AT organization_NN1 's_GE competence_NN1 ,_, and_CC the_AT value_NN1 of_IO the_AT organization_NN1 's_GE other_JJ offerings_NN2 (_( Zemke_NP1 and_CC Bell_NP1 ,_, 1990_MC )_) ._. 
</s>
<s>
Swanson(2001)_FO have_VH0 categorized_VVN service_NN1 recovery_NN1 outcomes_NN2 into_II four_MC types_NN2 ,_, including_II two_MC evaluative_JJ outcomes_NN2 and_CC two_MC behaviour_NN1 outcomes_NN2 ._. 
</s>
<s>
The_AT evaluative_JJ outcomes_NN2 are_VBR perceived_VVN service_NN1 quality_NN1 and_CC customer_NN1 satisfaction_NN1 ._. 
</s>
<s>
Perceived_JJ service_NN1 quality_NN1 refers_VVZ to_II technical_JJ quality_NN1 and_CC process_NN1 or_CC functional_JJ quality_NN1 ._. 
</s>
<s>
The_AT former_DA related_JJ to_II what_DDQ is_VBZ delivered_VVN ,_, and_CC is_VBZ judged_VVN by_II the_AT customer_NN1 after_II the_AT service_NN1 is_VBZ performed_VVN ._. 
</s>
<s>
The_AT latter_DA relates_VVZ to_II the_AT experience_NN1 that_CST a_AT1 customer_NN1 has_VHZ while_CS the_AT need_NN1 is_VBZ being_VBG met_VVN ._. 
</s>
<s>
Customer_NN1 satisfaction_NN1 concerns_VVZ the_AT level_NN1 of_IO "_" consumption-related_JJ fulfillment_NN1 "_" (_( Oliver_NP1 ,_, 1997_MC )_) ._. 
</s>
<s>
Word-of-mouth_JJ intentions_NN2 and_CC repurchase_NN1 intentions_NN2 are_VBR the_AT two_MC behavior_NN1 outcomes_NN2 of_IO service_NN1 failure_NN1 encounter_NN1 ._. 
</s>
<s>
Customers_NN2 '_GE word-of-mouth_NN1 may_VM appears_VVZ as_CSA talking_VVG to_II others_NN2 about_II the_AT experiences_NN2 ,_, complaining_VVG to_TO service_VVI providers_NN2 or_CC through_II third_MD parties_NN2 ,_, such_II21 as_II22 the_AT Internet_NN1 ._. 
</s>
<s>
After_CS service_NN1 recovery_NN1 ,_, customers_NN2 choose_VV0 to_TO stay_VVI or_CC switch_VVI to_II another_DD1 service_NN1 provider_NN1 ._. 
</s>
<s>
"_" The_AT past_JJ studies_NN2 are_VBR more_DAR focus_NN1 on_II the_AT selection_NN1 and_CC application_NN1 of_IO service_NN1 recovery_NN1 strategies_NN2 after_II service_NN1 failure_NN1 "_" (_( Lin_NP1 ,_, 2009_MC )_) and_CC exploring_VVG the_AT the_AT types_NN2 of_IO service_NN1 failure_NN1 and_CC compensation_NN1 ._. 
</s>
<s>
Previous_JJ studies_NN2 concerning_II fairness_NN1 effects_NN2 usually_RR try_VV0 to_TO measure_VVI fairness_NN1 factors_NN2 '_GE influence_NN1 to_II recovery_NN1 outcomes_NN2 by_II testing_VVG hypotheses_NN2 through_II quantitative_JJ research_NN1 or_CC mathematical_JJ models_NN2 ._. 
</s>
<s>
This_DD1 study_NN1 aims_VVZ to_TO supplement_VVI how_RRQ the_AT perceived_JJ justice_NN1 affect_NN1 customers_NN2 '_GE perceptions_NN2 on_II service_NN1 recovery_NN1 through_II a_AT1 qualitative_JJ way_NN1 ,_, which_DDQ enables_VVZ us_PPIO2 to_TO view_VVI the_AT service_NN1 recovery_NN1 processes_NN2 from_II a_AT1 customer_NN1 's_GE perspective_NN1 ._. 
</s>
<s>
2.2_MC Customers_NN2 '_GE recovery_NN1 expectation_NN1 and_CC fairness_NN1 factors_NN2 Tax_VV0 et_RA21 al._RA22 (_( 1998_MC )_) documented_VVD three_MC dimensions_NN2 of_IO justices_NN2 which_DDQ help_VV0 to_TO understand_VVI customers_NN2 '_GE complaint_NN1 process_NN1 from_II initiation_NN1 to_II completion_NN1 ._. 
</s>
<s>
They_PPHS2 argued_VVD that_CST customers_NN2 are_VBR looking_VVG for_IF distributive_JJ justice_NN1 ,_, procedural_JJ justice_NN1 ,_, and_CC interactional_JJ justice_NN1 ._. 
</s>
<s>
In_II another_DD1 study_NN1 ,_, they_PPHS2 used_VVD the_AT term_NN1 "_" outcome_NN1 fairness_NN1 "_" ,_, "_" procedural_JJ fairness_NN1 "_" ,_, and_CC "_" interactional_JJ fairness_NN1 "_" correspondingly_RR ._. 
</s>
<s>
Wilson_NP1 et_RA21 al._RA22 (_( 2008_MC )_) explained_VVD the_AT three_MC dimensions_NN2 of_IO fairness_NN1 in_II a_AT1 more_RGR specific_JJ way_NN1 ._. 
</s>
<s>
"_" Outcome_NN1 justice_NN1 concerns_VVZ the_AT results_NN2 that_CST customers_NN2 receive_VV0 from_II their_APPGE complaints_NN2 ,_, procedural_JJ justice_NN1 refers_VVZ to_II the_AT policies_NN2 ,_, rules_NN2 ,_, and_CC timeliness_NN1 of_IO the_AT complaint_NN1 process_NN1 ,_, and_CC interactional_JJ justice_NN1 focuses_VVZ on_II the_AT interpersonal_JJ treatment_NN1 received_VVN during_II the_AT complaint_NN1 process_NN1 "_" (_( Wilson_NP1 et_RA21 al._RA22 ,_, 2008_MC )_) ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) Outcome_NN1 fairness_NN1 concerns_VVZ the_AT outcome_NN1 or_CC compensations_NN2 customers_NN2 expect_VV0 to_TO match_VVI the_AT service_NN1 failure_NN1 they_PPHS2 experienced_VVD ._. 
</s>
<s>
The_AT compensations_NN2 can_VM take_VVI form_NN1 of_IO actual_JJ monetary_JJ compensation_NN1 ,_, an_AT1 apology_NN1 ,_, future_JJ free_JJ services_NN2 ,_, reduced_VVD charges_NN2 ,_, repair_NN1 or_CC replacement_NN1 (_( Wilson_NP1 et_RA21 al._RA22 ,_, 2008_MC )_) ._. 
</s>
<s>
Customers_NN2 use_VV0 equity_NN1 principle_NN1 consciously_RR or_CC unconsciously_RR to_TO evaluate_VVI whether_CSW companies_NN2 have_VH0 paid_VVN for_IF their_APPGE failures_NN2 ._. 
</s>
<s>
They_PPHS2 want_VV0 the_AT companies_NN2 to_TO pay_VVI for_IF the_AT mistakes_NN2 ,_, and_CC they_PPHS2 expect_VV0 similar_JJ treatment_NN1 with_IW those_DD2 who_PNQS had_VHD experienced_VVN the_AT same_DA failures_NN2 before_RT ._. 
</s>
<s>
Tax_NN1 et_RA21 al._RA22 (_( 1998_MC )_) stated_VVD that_CST customers_NN2 may_VM assess_VVI the_AT fairness_NN1 of_IO compensation_NN1 differently_RR on_II the_AT basis_NN1 of_IO their_APPGE prior_JJ experiences_NN2 with_IW the_AT company_NN1 in_CS21 case_CS22 ,_, other_JJ people_NN 's_GE similar_JJ experiences_NN2 ,_, and_CC their_APPGE perceptions_NN2 about_II the_AT lose_VV0 resulted_VVN by_II the_AT service_NN1 failure_NN1 ._. 
</s>
<s>
Procedural_JJ fairness_NN1 refers_VVZ to_II the_AT policies_NN2 ,_, rules_NN2 ,_, and_CC timeliness_NN1 of_IO the_AT complaint_NN1 process_NN1 ._. 
</s>
<s>
Customers_NN2 want_VV0 easy_JJ access_NN1 to_TO complain_VVI and_CC they_PPHS2 want_VV0 their_APPGE problems_NN2 to_TO be_VBI solved_VVN as_RG soon_RR as_CSA possible_JJ ._. 
</s>
<s>
Customers_NN2 are_VBR more_RGR likely_JJ to_TO feel_VVI satisfied_JJ if_CS their_APPGE problems_NN2 can_VM be_VBI addressed_VVN by_II the_AT first_MD service_NN1 person_NN1 they_PPHS2 complained_VVD to_II ,_, and_CC if_CS the_AT company_NN1 can_VM take_VVI customers_NN2 '_GE individual_JJ circumstances_NN2 into_II consideration_NN1 ._. 
</s>
<s>
"_" Fair_JJ procedures_NN2 are_VBR characterised_VVN by_II clarity_NN1 ,_, speed_NN1 ,_, and_CC absence_NN1 of_IO difficulties_NN2 ._. 
</s>
<s>
Unfair_JJ procedures_NN2 are_VBR those_DD2 that_CST customers_NN2 perceive_VV0 as_RG slow_JJ ,_, prolonged_JJ and_CC inconvenient_JJ "_" (_( Wilson_NP1 et_RA21 al._RA22 ,_, 2008_MC )_) ._. 
</s>
<s>
During_II the_AT complaint_NN1 process_NN1 ,_, customers_NN2 also_RR expect_VV0 interactional_JJ fairness_NN1 ,_, which_DDQ concerns_VVZ how_RRQ they_PPHS2 are_VBR treated_VVN by_II the_AT service_NN1 people_NN ._. 
</s>
<s>
Customers_NN2 want_VV0 to_TO feel_VVI caring_JJ and_CC sympathy_NN1 from_II the_AT service_NN1 people_NN ,_, they_PPHS2 want_VV0 to_TO be_VBI treated_VVN politely_RR and_CC honestly_RR ._. 
</s>
<s>
Uncaring_JJ attitude_NN1 and_CC lack_NN1 of_IO action_NN1 to_TO solve_VVI the_AT problem_NN1 may_VM lead_VVI to_II the_AT feeling_NN1 that_CST their_APPGE problems_NN2 are_VBR not_XX taken_VVN seriously_RR by_II the_AT company_NN1 ,_, therefore_RR ,_, customers_NN2 may_VM feel_VVI that_CST they_PPHS2 are_VBR treated_VVN unfairly_RR ._. 
</s>
<s>
Wilson_NP1 et_RA21 al._RA22 (_( 2008_MC )_) pointed_VVD out_RP that_DD1 lack_NN1 of_IO training_NN1 and_CC empowerment_NN1 can_VM result_VVI employees_NN2 '_GE wrong_JJ behavior_NN1 when_CS dealing_VVG with_IW complaint_NN1 customers_NN2 ._. 
</s>
<s>
"_" A_AT1 frustrated_JJ front-line_JJ employee_NN1 who_PNQS has_VHZ no_AT authority_NN1 to_TO compensate_VVI the_AT customer_NN1 may_VM easily_RR respond_VVI in_II a_AT1 aloof_JJ or_CC uncaring_JJ manner_NN1 ,_, especially_RR if_CS the_AT customer_NN1 is_VBZ angry_JJ and/or_CC rude_JJ "_" ._. 
</s>
<s>
They_PPHS2 also_RR argued_VVD that_CST even_CS21 though_CS22 the_AT outcome_NN1 and_CC procedural_JJ fairness_NN1 is_VBZ managed_VVN in_II a_AT1 good_JJ way_NN1 by_II the_AT provider_NN1 ,_, the_AT interactional_JJ fairness_NN1 can_VM dominate_VVI these_DD2 other_JJ two_MC types_NN2 ,_, if_CS it_PPH1 is_VBZ managed_VVN poorly_RR ._. 
</s>
<s>
3_MC ._. 
</s>
<s>
Method_NN1 3.1_MC Design_NN1 Aiming_VVG to_TO explore_VVI how_RRQ the_AT perceived_JJ justice_NN1 affect_NN1 customers_NN2 '_GE perceptions_NN2 on_II service_NN1 recovery_NN1 ,_, this_DD1 study_NN1 was_VBDZ based_VVN on_II interviews_NN2 rather_II21 than_II22 questionnaires_NN2 ._. 
</s>
<s>
I_PPIS1 interviewed_VVD customers_NN2 who_PNQS had_VHD complained_VVN experiences_NN2 as_CSA I_PPIS1 felt_VVD that_CST complaining_VVG customers_NN2 would_VM like_VVI to_TO talk_VVI about_II their_APPGE experiences_NN2 and_CC may_VM provide_VVI interesting_JJ information_NN1 ._. 
</s>
<s>
Considering_CS21 that_CS22 the_AT complaint_NN1 processes_NN2 are_VBR complex_JJ ,_, and_CC full_JJ of_IO different_JJ kinds_NN2 of_IO emotions_NN2 which_DDQ the_AT respondents_NN2 themselves_PPX2 may_VM not_XX realized_VVN clearly_RR ,_, a_AT1 combination_NN1 of_IO interview_NN1 guide_NN1 approach_NN1 and_CC informal_JJ conversation_NN1 interview_NN1 approach_NN1 was_VBDZ conducted_VVN ._. 
</s>
<s>
The_AT informal_JJ conversational_JJ interview_NN1 is_VBZ the_AT most_RGT open-ended_JJ approach_NN1 to_II interviewing_VVG (_( Patton_NP1 ,_, 1990:281_MC )_) ._. 
</s>
<s>
It_PPH1 relies_VVZ entirely_RR on_II the_AT spontaneous_JJ generation_NN1 of_IO questions_NN2 in_II the_AT natural_JJ flow_NN1 of_IO an_AT1 interaction_NN1 ._. 
</s>
<s>
This_DD1 approach_NN1 "_" maintains_VVZ maximum_JJ flexibility_NN1 to_TO pursue_VVI information_NN1 in_II whatever_DDQV direction_NN1 appears_VVZ to_TO be_VBI appropriate_JJ "_" ._. 
</s>
<s>
A_AT1 general_JJ interview_NN1 guide_NN1 was_VBDZ designed_VVN before_II hand_NN1 to_TO keep_VVI the_AT conversations_NN2 go_VV0 to_II the_AT right_JJ direction_NN1 ._. 
</s>
<s>
Patton(1990)_FO described_VVN six_MC types_NN2 of_IO questions_NN2 that_CST consist_VV0 the_AT content_NN1 of_IO the_AT interview_NN1 ,_, these_DD2 are_VBR experience_NN1 questions_NN2 ,_, opinion_NN1 questions_NN2 ,_, felling_VVG questions_NN2 ,_, knowledge_NN1 questions_NN2 ,_, sensory_JJ questions_NN2 ,_, and_CC background_NN1 questions_NN2 ._. 
</s>
<s>
Table_NN1 2._MC illustrates_VVZ the_AT interview_NN1 questions_NN2 based_VVN on_II different_JJ types_NN2 of_IO questions_NN2 ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) During_II the_AT interviews_NN2 ,_, the_AT respondent_NN1 was_VBDZ positioned_VVN as_II the_AT expert_NN1 and_CC the_AT interviewer_NN1 as_II the_AT facilitator_NN1 of_IO the_AT discovery_NN1 process_NN1 ._. 
</s>
<s>
Respondents_NN2 were_VBDR encouraged_VVN to_TO talk_VVI about_II their_APPGE experiences_NN2 as_RG much_DA1 as_CSA possible_JJ ,_, after_II that_DD1 ,_, the_AT researcher_NN1 tried_VVD to_TO identify_VVI how_RRQ did_VDD fairness_NN1 factors_NN2 work_VV0 in_II these_DD2 service_NN1 recovery_NN1 processes_NN2 ._. 
</s>
<s>
3.2_MC Data_NN collection_NN1 Before_II the_AT interview_NN1 ,_, the_AT respondents_NN2 were_VBDR informed_VVN about_II the_AT aim_NN1 of_IO the_AT study_NN1 ,_, which_DDQ was_VBDZ to_TO understand_VVI rather_II21 than_II22 to_II judge_NN1 ,_, so_CS21 that_CS22 the_AT respondents_NN2 knew_VVD there_EX was_VBDZ no_AT right_NN1 or_CC wrong_JJ answers_NN2 ,_, and_CC the_AT data_NN collection_NN1 was_VBDZ anonymous_JJ ._. 
</s>
<s>
The_AT conversation_NN1 started_VVD with_IW a_AT1 professional_JJ ,_, friendly_JJ atmosphere_NN1 ._. 
</s>
<s>
Some_DD irrelevant_JJ chatting_NN1 before_II the_AT interview_NN1 was_VBDZ necessary_JJ to_TO relax_VVI the_AT respondents_NN2 and_CC build_VVI rapport_NN1 ,_, so_CS21 that_CS22 the_AT respondent_NN1 would_VM feel_VVI free_JJ and_CC comfortable_JJ to_TO provide_VVI information_NN1 ._. 
</s>
<s>
The_AT concept_NN1 "_" service_NN1 recovery_NN1 "_" was_VBDZ explained_VVN to_II all_DB the_AT respondents_NN2 at_II the_AT beginning_NN1 of_IO the_AT interview_NN1 to_TO ensure_VVI all_DB the_AT respondents_NN2 understand_VV0 it_PPH1 correctly_RR ._. 
</s>
<s>
The_AT data_NN was_VBDZ collected_VVN from_II eight_MC interviewees_NN2 who_PNQS had_VHD complained_VVN experiences_NN2 ._. 
</s>
<s>
Intensity_NN1 sampling_NN1 strategy_NN1 was_VBDZ applied_VVN in_II choosing_VVG interviewees_NN2 ._. 
</s>
<s>
This_DD1 approach_NN1 focuses_VVZ on_II information-rich_JJ cases_NN2 that_CST manifest_VV0 the_AT phenomenon_NN1 intensely_RR ,_, but_CCB not_XX extremely_RR (_( Patton_NP1 ,_, 1990_MC )_) ._. 
</s>
<s>
The_AT interviewees_NN2 were_VBDR asked_VVN about_II his/her_APPGE experience_NN1 about_II service_NN1 recovery_NN1 ._. 
</s>
<s>
When_RRQ respondents_NN2 had_VHD experienced_VVN more_DAR than_CSN one_MC1 failure_NN1 in_II their_APPGE experiences_NN2 ,_, they_PPHS2 were_VBDR asked_VVN to_TO consider_VVI the_AT most_RGT important_JJ one_PN1 ._. 
</s>
<s>
As_II an_AT1 informal_JJ conversation_NN1 interview_NN1 approach_NN1 was_VBDZ employed_VVN ,_, the_AT interviews_NN2 were_VBDR not_XX tap-recorded_JJ ._. 
</s>
<s>
The_AT interviewer_NN1 made_VVD notes_NN2 during_II the_AT conversation_NN1 and_CC then_RT organized_VVD the_AT notes_NN2 into_II short_JJ summary_NN1 for_IF each_DD1 interview_NN1 ._. 
</s>
<s>
In_BCL21 order_BCL22 to_TO assess_VVI the_AT trustworthiness_NN1 of_IO the_AT data_NN ,_, Silverman(2006)_FO and_CC Wallendorf_NP1 and_CC Belk's(1989)_FO eight_MC criteria_NN2 were_VBDR used_VVN to_TO assess_VVI this_DD1 study_NN1 ._. 
</s>
<s>
Table_NN1 3_MC shows_VVZ the_AT measurement_NN1 ._. 
</s>
<s>
&lsqb;_( Table_NN1 &rsqb;_) 4_MC ._. 
</s>
<s>
Result_VV0 There_EX are_VBR many_DA2 similar_JJ patterns_NN2 among_II the_AT eight_MC interviews_NN2 ._. 
</s>
<s>
To_TO begin_VVI with_IW ,_, there_EX are_VBR only_RR two_MC people_NN were_VBDR happy_JJ after_II the_AT service_NN1 recovery_NN1 ,_, interviewee_NN1 number_NN1 1_MC1 and_CC interviewee_NN1 number_NN1 3_MC ._. 
</s>
<s>
These_DD2 two_MC happy_JJ interviewees_NN2 share_VV0 a_AT1 similarity_NN1 that_CST they_PPHS2 both_DB2 got_VVD something_PN1 extra_JJ when_CS they_PPHS2 complained_VVD ,_, except_II21 for_II22 the_AT returned_JJ money_NN1 or_CC a_AT1 new_JJ product_NN1 ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, the_AT outcome_NN1 fairness_NN1 has_VHZ been_VBN achieved_VVN or_CC surpassed_VVD ._. 
</s>
<s>
They_PPHS2 both_DB2 described_VVD how_RRQ they_PPHS2 were_VBDR pleasantly_RR surprised_JJ and_CC thought_VVD that_CST it_PPH1 was_VBDZ too_RG much_DA1 ._. 
</s>
<s>
Quoting_VVG interviewee_NN1 number_NN1 1_MC1 :_: I_PPIS1 was_VBDZ upset_VVN when_CS we_PPIS2 arrived_VVD at_II the_AT second_MD restaurant_NN1 ,_, I_PPIS1 mean_VV0 we_PPIS2 are_VBR all_RR over_RG 70_MC and_CC had_VHD to_TO walk_VVI that_DD1 distance_NN1 !_! 
</s>
<s>
But_CCB they_PPHS2 were_VBDR so_RG nice_RR had_VHD set_VVN up_RP such_DA a_AT1 nice_JJ table_NN1 for_IF us_PPIO2 ,_, so_CS we_PPIS2 were_VBDR quite_RG happy_JJ again_RT when_CS we_PPIS2 sat_VVD down_RP ._. 
</s>
<s>
And_CC then_RT they_PPHS2 brought_VVD out_RP the_AT sparkling_JJ wine_NN1 ,_, and_CC we_PPIS2 were_VBDR all_DB so_RG amazed_JJ !_! 
</s>
<s>
Interviewee_NN1 number_NN1 3_MC also_RR described_VVN how_RGQ pleasantly_RR surprised_VVD she_PPHS1 was_VBDZ when_RRQ she_PPHS1 did_VDD not_XX only_RR get_VVI a_AT1 new_JJ taco_NN1 sauce_NN1 ,_, but_CCB a_AT1 lot_NN1 of_IO other_JJ products_NN2 as_RR21 well_RR22 for_IF free_JJ ._. 
</s>
<s>
Additionally_RR ,_, interviewees_NN2 who_PNQS were_VBDR unsatisfied_JJ with_IW the_AT service_NN1 recovery_NN1 also_RR said_VVD that_CST they_PPHS2 would_VM not_XX use_VVI that_DD1 particular_JJ service_NN1 again_RT or_CC recommend_VV0 it_PPH1 to_II their_APPGE friends_NN2 ._. 
</s>
<s>
However_RR ,_, there_EX is_VBZ an_AT1 exception_NN1 ,_, interviewee_NN1 number_NN1 5_MC ._. 
</s>
<s>
Although_CS she_PPHS1 was_VBDZ unhappy_JJ to_TO wait_VVI for_IF a_AT1 very_RG long_JJ time_NNT1 to_TO get_VVI her_APPGE furniture_NN1 delivered_VVN ,_, and_CC had_VHD to_TO connect_VVI the_AT delivery_NN1 firm_NN1 herself_PPX1 ,_, she_PPHS1 says_VVZ she_PPHS1 will_VM probably_RR go_VVI to_II the_AT same_DA store_NN1 again_RT ,_, because_CS her_APPGE prior_JJ experiences_NN2 with_IW the_AT company_NN1 were_VBDR pleasant_JJ ._. 
</s>
<s>
She_PPHS1 said_VVD in_II the_AT interview_NN1 :_: ..._... considering_CS most_DAT of_IO my_APPGE shopping_NN1 experiences_NN2 (_( in_II the_AT store_NN1 )_) were_VBDR pleasant_JJ ,_, I_PPIS1 guess_VV0 sometimes_RT problems_NN2 just_RR happen_VV0 ._. 
</s>
<s>
I_MC1 still_JJ use_NN1 the_AT service_NN1 but_CCB I_PPIS1 do_VD0 not_XX trust_VVI it_PPH1 like_CS I_PPIS1 did_VDD before_RT ._. 
</s>
<s>
This_DD1 case_NN1 reflects_VVZ that_DD1 customer_NN1 's_GE previous_JJ relationship_NN1 with_IW the_AT service_NN1 provider_NN1 affects_VVZ the_AT way_NN1 he/she_PPHS1 reacts_VVZ to_II the_AT service_NN1 recovery_NN1 process_NN1 ._. 
</s>
<s>
The_AT impact_NN1 of_IO previous_JJ experiences_NN2 can_VM also_RR be_VBI found_VVN in_II the_AT experience_NN1 of_IO interviewee_NN1 7_MC ,_, who_PNQS had_VHD to_TO wait_VVI for_IF a_AT1 very_RG long_JJ time_NNT1 for_IF her_APPGE food_NN1 and_CC then_RT eventually_RR was_VBDZ served_VVN cold_JJ food_NN1 ._. 
</s>
<s>
The_AT service_NN1 people_NN responded_VVD well_RR to_II her_APPGE complaint_NN1 ,_, and_CC did_VDD only_RR charge_VVI her_APPGE party_NN1 for_IF the_AT alcohol_NN1 and_CC not_XX for_IF the_AT children_NN2 's_GE meals_NN2 even_CS21 though_CS22 the_AT children_NN2 were_VBDR content_JJ with_IW their_APPGE food_NN1 and_CC drinks_NN2 ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, they_PPHS2 basically_RR experienced_JJ outcome_NN1 fairness_NN1 ,_, procedural_JJ fairness_NN1 and_CC interactional_JJ fairness_NN1 ._. 
</s>
<s>
Still_RR ,_, the_AT person_NN1 and_CC her_APPGE family_NN1 were_VBDR unhappy_JJ and_CC she_PPHS1 said_VVD they_PPHS2 would_VM never_RR go_VVI back_RP ._. 
</s>
<s>
When_CS asked_VVN why_RRQ ,_, she_PPHS1 responded_VVD I_PPIS1 have_VH0 experienced_VVN bad_JJ service_NN1 there_RL before_RT ,_, and_CC that_DD1 was_VBDZ just_RR the_AT last_MD drop_NN1 !_! 
</s>
<s>
Although_CS all_DB the_AT three_MC dimensions_NN2 of_IO fairness_NN1 have_VH0 been_VBN achieved_VVN in_II this_DD1 case_NN1 ,_, the_AT interviewee_NN1 was_VBDZ unhappy_JJ and_CC felt_VVD repeating_JJ similar_JJ mistakes_NN2 in_II the_AT same_DA service_NN1 provider_NN1 is_VBZ intolerable_JJ ._. 
</s>
<s>
Interviewee_NN1 number_NN1 4_MC ,_, who_PNQS returned_VVD the_AT broken_JJ mobile_JJ phone_NN1 ,_, basically_RR got_VVN what_DDQ he_PPHS1 wanted_VVD a_AT1 new_JJ phone_NN1 but_CCB was_VBDZ still_RR unhappy_JJ because_CS the_AT unfriendly_JJ attitude_NN1 of_IO the_AT service_NN1 people_NN and_CC those_DD2 procedures_NN2 he_PPHS1 had_VHD to_TO follow_VVI before_CS he_PPHS1 actually_RR talked_VVN to_II the_AT person_NN1 who_PNQS can_VM made_VVD decision_NN1 ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, there_EX was_VBDZ outcome_NN1 fairness_NN1 ,_, but_CCB not_XX procedural_JJ fairness_NN1 or_CC interactional_JJ fairness_NN1 ._. 
</s>
<s>
Interviewee_NN1 number_NN1 6_MC ,_, who_PNQS was_VBDZ served_VVN the_AT bad_JJ fish_NN ,_, was_VBDZ in_II a_AT1 similar_JJ way_NN1 upset_VVN because_CS he_PPHS1 too_RR had_VHN to_TO fight_VVI with_IW the_AT personnel_NN2 before_II getting_VVG their_APPGE service_NN1 recovery_NN1 ._. 
</s>
<s>
Service_NN1 people_NN 's_GE willingness_NN1 to_TO help_VVI seems_VVZ to_TO be_VBI an_AT1 important_JJ factor_NN1 in_II achieving_VVG interactional_JJ fairness_NN1 ._. 
</s>
<s>
Almost_RR all_DB interviewees_NN2 mentioned_VVD trust_NN1 at_II some_DD point_NN1 during_II the_AT interview_NN1 ._. 
</s>
<s>
In_II most_DAT of_IO the_AT cases_NN2 ,_, the_AT trust_NN1 for_IF the_AT company_NN1 was_VBDZ at_RR21 least_RR22 partly_RR lost_VVN ,_, for_IF various_JJ periods_NN2 of_IO time_NNT1 ._. 
</s>
<s>
How_RGQ much_DA1 and_CC for_IF how_RGQ long_RR ,_, depends_VVZ on_II the_AT kind_NN1 of_IO service_NN1 and_CC the_AT degree_NN1 of_IO inconvenience_NN1 the_AT problem_NN1 caused_VVD the_AT customer_NN1 ,_, and_CC how_RGQ effective_JJ the_AT service_NN1 recovery_NN1 was_VBDZ ._. 
</s>
<s>
Interviewee_NN1 number_NN1 2_MC ,_, who_PNQS bought_VVD the_AT channel_NN1 package_NN1 that_CST actually_RR was_VBDZ not_XX available_JJ in_II his_APPGE area_NN1 ,_, said_VVD he_PPHS1 most_RGT definitely_RR would_VM not_XX use_VVI any_DD of_IO the_AT company_NN1 's_GE services_NN2 again_RT because_CS he_PPHS1 thought_VVD they_PPHS2 were_VBDR so_RG incompetent_JJ ._. 
</s>
<s>
To_TO win_VVI back_RP his_APPGE trust_NN1 ,_, could_VM prove_VVI hard_RR to_II the_AT company_NN1 ._. 
</s>
<s>
The_AT man_NN1 said_VVD that_CST he_PPHS1 went_VVD to_II their_APPGE shop_NN1 again_RT after_CS he_PPHS1 got_VVD his_APPGE money_NN1 back_NN1 and_CC his_APPGE faulty_JJ package_NN1 cancelled_VVD ,_, just_RR to_TO let_VVI them_PPHO2 know_VVI how_RGQ annoyed_JJ he_PPHS1 felt_VVD ._. 
</s>
<s>
Had_VHD the_AT company_NN1 then_RT given_VVN him_PPHO1 some_DD kind_NN1 of_IO additional_JJ compensation_NN1 for_IF the_AT inconvenience_NN1 ,_, the_AT man_NN1 might_VM have_VHI felt_VVN that_CST he_PPHS1 got_VVD better_JJR outcome_NN1 fairness_NN1 and_CC thereby_RR felt_VVN better_RRR about_II the_AT company_NN1 all_DB in_II all_DB ._. 
</s>
<s>
Interviewee_NN1 number_NN1 8_MC ,_, who_PNQS got_VVD the_AT stone_NN1 in_II his_APPGE plum_NN1 ,_, said_VVD that_CST he_PPHS1 had_VHD not_XX bought_VVN the_AT same_DA plums_NN2 again_RT but_CCB that_CST he_PPHS1 was_VBDZ not_XX sure_JJ if_CS it_PPH1 was_VBDZ just_RR because_II21 of_II22 the_AT incident_NN1 ._. 
</s>
<s>
In_II any_DD case_NN1 ,_, it_PPH1 had_VHD not_XX affected_VVN his_APPGE trust_NN1 for_IF the_AT whole_JJ company_NN1 and_CC all_DB its_APPGE products_NN2 ,_, i.e._REX he_PPHS1 would_VM still_RR buy_VVI other_JJ products_NN2 from_II them_PPHO2 ._. 
</s>
<s>
It_PPH1 is_VBZ evident_JJ ,_, based_VVN on_II these_DD2 empirical_JJ studies_NN2 ,_, that_CST a_AT1 customer_NN1 's_GE feeling_NN1 of_IO distrust_NN1 and_CC inconvenience_NN1 after_II a_AT1 problem_NN1 has_VHZ occurred_VVN can_VM be_VBI reduced_VVN if_CS the_AT service_NN1 recovery_NN1 process_NN1 is_VBZ good_JJ enough_RR ._. 
</s>
<s>
Interviewee_NN1 number_NN1 3_MC ,_, who_PNQS bought_VVD the_AT taco_NN1 sauce_NN1 ,_, was_VBDZ very_RG upset_JJ at_RR21 first_RR22 because_CS she_PPHS1 was_VBDZ having_VHG people_NN over_RP for_IF a_AT1 taco_NN1 dinner_NN1 and_CC suddenly_RR she_PPHS1 had_VHD no_AT taco_NN1 sauce_NN1 to_TO offer_VVI and_CC that_DD1 was_VBDZ a_AT1 great_JJ inconvenience_NN1 ._. 
</s>
<s>
After_II having_VHG received_VVN the_AT package_NN1 from_II the_AT manufacturer_NN1 ,_, she_PPHS1 was_VBDZ a_AT1 happy_JJ customer_NN1 again_RT ._. 
</s>
<s>
Interviewee_NN1 number_NN1 8_MC also_RR bought_VVN a_AT1 faulty_JJ product_NN1 ,_, and_CC not_XX only_RR was_VBDZ it_PPH1 inconvenient_JJ for_IF him_PPHO1 he_PPHS1 was_VBDZ also_RR slightly_RR injured_VVN ._. 
</s>
<s>
He_PPHS1 did_VDD ,_, however_RR ,_, only_RR get_VV0 a_AT1 gift_NN1 card_NN1 for_IF a_AT1 new_JJ product_NN1 ,_, and_CC was_VBDZ not_XX happy_JJ because_CS he_PPHS1 did_VDD not_XX feel_VVI that_CST there_EX was_VBDZ outcome_NN1 fairness_NN1 ._. 
</s>
<s>
Quoting_VVG :_: And_CC can_VM you_PPY believe_VVI it_PPH1 ,_, the_AT new_JJ pack_NN1 of_IO stone_NN1 less_DAR plums_NN2 had_VHD stones_NN2 in_II them_PPHO2 as_RR21 well_RR22 !_! 
</s>
<s>
The_AT second_MD time_NNT1 around_RP I_PPIS1 did_VDD n't_XX complain_VVI anymore_RR ._. 
</s>
<s>
I_PPIS1 was_VBDZ tired_JJ of_IO the_AT company_NN1 and_CC the_AT plums_NN2 ..._... 
</s>
<s>
In_II this_DD1 case_NN1 ,_, the_AT manufacturers_NN2 would_VM probably_RR have_VHI stood_VVN a_AT1 better_JJR chance_NN1 to_TO keep_VVI him_PPHO1 as_II a_AT1 plum-customer_NN1 had_VHD they_PPHS2 sent_VVN him_PPHO1 something_PN1 else_RR as_RR21 well_RR22 ._. 
</s>
<s>
5_MC ._. 
</s>
<s>
Discussion_NN1 Through_II the_AT interviews_NN2 ,_, several_DA2 factors_NN2 affect_VV0 the_AT service_NN1 recovery_NN1 result_NN1 have_VH0 been_VBN identified_VVN ._. 
</s>
<s>
These_DD2 factors_NN2 are_VBR :_: quality_NN1 of_IO the_AT recovery_NN1 ,_, surprise_NN1 factor_NN1 ,_, friendliness_NN1 of_IO personnel_NN2 and_CC previous_JJ relationship_NN1 with_IW the_AT company_NN1 ._. 
</s>
<s>
Surprise_NN1 factors_NN2 ,_, including_II extra_JJ discount_NN1 and_CC free_JJ gifts_NN2 can_VM be_VBI attributed_VVN to_II compensations_NN2 which_DDQ are_VBR important_JJ in_II helping_VVG restore_VVI customers_NN2 '_GE perceptions_NN2 of_IO outcome_NN1 fairness_NN1 ._. 
</s>
<s>
Quality_NN1 of_IO service_NN1 recovery_NN1 is_VBZ related_VVN to_II the_AT procedural_JJ fairness_NN1 perceptions_NN2 ._. 
</s>
<s>
The_AT speed_NN1 by_II which_DDQ service_VV0 failures_NN2 are_VBR corrected_VVN or_CC complaints_NN2 are_VBR handled_VVN is_VBZ one_MC1 of_IO the_AT major_JJ determinants_NN2 of_IO customers_NN2 '_GE perceptions_NN2 of_IO procedural_JJ fairness_NN1 (_( Blodgett_NP1 et_RA21 al._RA22 ,_, 1997_MC ;_; Tax_NN1 et_RA21 al._RA22 ,_, 1998_MC )_) ._. 
</s>
<s>
Friendliness_NN1 of_IO the_AT personnel_NN2 ,_, which_DDQ can_VM be_VBI reflected_VVN through_II apology_NN1 and_CC service_NN1 attitude_NN1 ,_, is_VBZ linked_VVN to_II the_AT interactional_JJ fairness_NN1 ._. 
</s>
<s>
Previous_JJ relationship_NN1 with_IW the_AT company_NN1 ,_, also_RR affect_VV0 the_AT result_NN1 of_IO service_NN1 recovery_NN1 to_II some_DD extent.the_NNU following_RA are_VBR some_DD main_JJ findings_NN2 :_: First_MD ,_, the_AT outcome_NN1 fairness_NN1 plays_VVZ a_AT1 critical_JJ role_NN1 in_II customers_NN2 '_GE perceptions_NN2 to_TO service_VVI recovery_NN1 ,_, but_CCB not_XX a_AT1 determinant_NN1 one_MC1 ._. 
</s>
<s>
Our_APPGE interviews_NN2 imply_VV0 that_DD1 solving_NN1 problems_NN2 and_CC compensations_NN2 like_II free_JJ gifts_NN2 and_CC discounts_NN2 do_VD0 not_XX necessarily_RR lead_VVI to_II customers_NN2 satisfaction_NN1 even_CS21 though_CS22 apologies_NN2 and_CC explanations_NN2 were_VBDR made_VVN immediately_RR by_II the_AT service_NN1 provider_NN1 ._. 
</s>
<s>
However_RR ,_, I_PPIS1 noticed_VVD that_CST among_II all_DB the_AT interviewees_NN2 ,_, two_MC interviewees_NN2 who_PNQS were_VBDR satisfied_VVN with_IW the_AT recovery_NN1 received_VVD free_JJ gifts_NN2 as_CSA compensations_NN2 and_CC the_AT four_MC interviewees_NN2 who_PNQS did_VDD not_XX received_VVN gifts_NN2 or_CC discounts_NN2 were_VBDR all_DB dissatisfied_JJ ._. 
</s>
<s>
Secondly_RR ,_, compensations_NN2 can_VM help_VVI to_TO make_VVI up_RP for_IF the_AT failure_NN1 of_IO unconvinced_JJ complain_VV0 channels_NN2 or_CC no_AT apology_NN1 ,_, however_RR ,_, when_CS complaints_NN2 can_VM not_XX be_VBI solved_VVN quickly_RR together_RL with_IW no_AT apology_NN1 or_CC no_AT explanation_NN1 ,_, the_AT compensation_NN1 was_VBDZ useless_JJ ._. 
</s>
<s>
The_AT interviews_NN2 imply_VV0 that_CST when_CS the_AT procedural_JJ fairness_NN1 can_VM not_XX be_VBI achieved_VVN ,_, customers_NN2 felt_VVD that_CST only_RR an_AT1 apology_NN1 was_VBDZ not_XX good_JJ enough_RR ,_, they_PPHS2 felt_VVD they_PPHS2 deserve_VVI to_TO get_VVI extra_JJ compensations_NN2 for_IF the_AT unfair_JJ treatments_NN2 ._. 
</s>
<s>
It_PPH1 seems_VVZ that_CST if_CS there_EX are_VBR no_AT compensations_NN2 ,_, service_NN1 providers_NN2 should_VM make_VVI sure_JJ that_CST they_PPHS2 can_VM achieve_VVI both_RR procedural_JJ fairness_NN1 and_CC interactional_JJ fairness_NN1 so_CS21 that_CS22 it_PPH1 is_VBZ possible_JJ to_TO achieve_VVI customer_NN1 satisfaction_NN1 ._. 
</s>
<s>
Additionally_RR ,_, except_II21 for_II22 the_AT three_MC fairness_NN1 dimensions_NN2 ,_, customers_NN2 '_GE previous_JJ experiences_NN2 with_IW the_AT service_NN1 providers_NN2 can_VM affect_VVI the_AT results_NN2 of_IO the_AT service_NN1 recovery_NN1 ._. 
</s>
<s>
If_CS the_AT customers_NN2 '_GE experiences_NN2 with_IW the_AT service_NN1 providers_NN2 were_VBDR pleasant_JJ ,_, they_PPHS2 are_VBR more_RGR likely_JJ to_TO give_VVI them_PPHO2 a_AT1 second_MD chance_NN1 ._. 
</s>
<s>
However_RR ,_, if_CS the_AT service_NN1 providers_NN2 had_VHD made_VVN mistakes_NN2 before_RT ,_, customers_NN2 tend_VV0 to_TO switch_VVI provider_NN1 and_CC avoid_VVI using_VVG the_AT same_DA service_NN1 provider_NN1 in_II the_AT future_NN1 ._. 
</s>
<s>
There_EX are_VBR two_MC interviewees_NN2 who_PNQS received_VVD compensations_NN2 and_CC apologies_NN2 and_CC did_VDD not_XX meet_VVI any_DD trouble_NN1 when_CS complained_VVN ,_, but_CCB they_PPHS2 still_RR not_XX satisfied_VVN with_IW the_AT results_NN2 ._. 
</s>
<s>
Both_DB2 of_IO them_PPHO2 had_VHD unpleasant_JJ experiences_NN2 with_IW the_AT service_NN1 providers_NN2 ._. 
</s>
<s>
Although_CS all_DB the_AT three_MC fairness_NN1 dimensions_NN2 had_VHD been_VBN achieved_VVN ,_, they_PPHS2 choose_VV0 to_TO switch_VVI provider_NN1 ._. 
</s>
<s>
Finally_RR ,_, although_CS service_NN1 failures_NN2 do_VD0 happen_VVI ,_, if_CS well_RR handled_VVN ,_, a_AT1 successful_JJ recovery_NN1 can_VM strengthen_VVI the_AT relationship_NN1 between_II complained_VVD customers_NN2 and_CC the_AT service_NN1 provider_NN1 ._. 
</s>
<s>
The_AT interview_NN1 also_RR shows_VVZ that_DD1 service_NN1 recovery_NN1 can_VM be_VBI used_VVN as_II a_AT1 chance_NN1 for_IF marketing_NN1 communications_NN2 ._. 
</s>
<s>
By_II sending_VVG gifts_NN2 or_CC new_JJ products_NN2 as_CSA compensations_NN2 ,_, companies_NN2 can_VM introduce_VVI new_JJ products_NN2 to_II customers_NN2 ,_, they_PPHS2 can_VM use_VVI the_AT recovery_NN1 as_II a_AT1 chance_NN1 to_TO get_VVI the_AT customer_NN1 interested_JJ in_II and_CC aware_JJ of_IO more_DAR of_IO their_APPGE products_NN2 ._. 
</s>
<s>
The_AT experience_NN1 of_IO interviewee_NN1 number_NN1 3_MC is_VBZ a_AT1 good_JJ example_NN1 ._. 
</s>
<s>
The_AT package_NN1 of_IO products_NN2 they_PPHS2 sent_VVD her_PPHO1 as_CSA compensation_NN1 only_RR cost_VV0 little_RR for_IF the_AT company_NN1 ,_, and_CC it_PPH1 made_VVD her_APPGE happy_JJ and_CC aware_JJ of_IO other_JJ products.It_NNU actually_RR resulted_VVN in_II me_PPIO1 buying_VVG more_DAR of_IO their_APPGE products_NN2 !_! 
</s>
<s>
Some_DD of_IO the_AT other_JJ products_NN2 that_CST they_PPHS2 sent_VVD me_PPIO1 in_II the_AT package_NN1 I_PPIS1 would_VM probably_RR not_XX have_VHI thought_VVN of_IO buying_VVG before_RT ,_, but_CCB after_II having_VHG tried_VVN them_PPHO2 I_PPIS1 have_VH0 bought_VVN them_PPHO2 several_DA2 times.On_NNU the_AT country_NN1 ,_, a_AT1 poor_JJ recovery_NN1 or_CC a_AT1 recovery_NN1 neither_RR too_RG good_JJ nor_CC too_RG bad_JJ can_VM weaken_VVI the_AT relationship_NN1 ._. 
</s>
<s>
Meanwhile_RR ,_, it_PPH1 is_VBZ not_XX only_RR the_AT result_NN1 of_IO the_AT recovery_NN1 but_CCB also_RR customers_NN2 experiences_NN2 with_IW the_AT service_NN1 provider_NN1 before_RT influence_VV0 their_APPGE decisions_NN2 about_II whether_CSW to_TO stay_VVI or_CC switch_NN1 ._. 
</s>
<s>
6_MC ._. 
</s>
<s>
Managerial_JJ implications_NN2 and_CC limitations_NN2 The_AT findings_NN2 of_IO this_DD1 study_NN1 suggest_VV0 that_CST when_CS dealing_VVG with_IW unsatisfied_JJ customers_NN2 ,_, service_NN1 providers_NN2 should_VM pay_VVI attention_NN1 to_II the_AT three_MC dimensions_NN2 of_IO fairness_NN1 ._. 
</s>
<s>
Service_NN1 providers_NN2 should_VM ensure_VVI that_CST their_APPGE service_NN1 recovery_NN1 processes_NN2 are_VBR well_RR handled_VVN ._. 
</s>
<s>
Apology_NN1 should_VM be_VBI made_VVN immediately_RR and_CC it_PPH1 should_VM be_VBI easy_JJ for_IF unsatisfied_JJ customers_NN2 to_TO complain_VVI ._. 
</s>
<s>
When_CS the_AT recovery_NN1 processes_NN2 are_VBR well_RR handled_VVN ,_, compensations_NN2 are_VBR not_XX necessary_JJ ._. 
</s>
<s>
However_RR ,_, when_CS there_EX is_VBZ delay_NN1 or_CC inconvenience_NN1 or_CC lack_NN1 of_IO apology_NN1 in_II the_AT process_NN1 ,_, compensations_NN2 can_VM be_VBI used_VVN to_TO restore_VVI customers_NN2 '_GE perceptions_NN2 of_IO outcome_NN1 fairness_NN1 ._. 
</s>
<s>
For_IF companies_NN2 ,_, to_TO apologize_VVI and_CC satisfy_VVI customers_NN2 '_GE needs_NN2 immediately_RR is_VBZ perhaps_RR the_AT most_RRT cost_VV0 effective_JJ way_NN1 to_TO keep_VVI customers_NN2 ._. 
</s>
<s>
When_RRQ problems_NN2 can_VM be_VBI solved_VVN quickly_RR and_CC with_IW good_JJ service_NN1 attitude_NN1 ,_, companies_NN2 do_VD0 not_XX need_VVI to_TO pay_VVI extra_JJ to_TO restore_VVI customers_NN2 '_GE perceptions_NN2 of_IO outcome_NN1 fairness_NN1 ._. 
</s>
<s>
This_DD1 suggests_VVZ that_DD1 service_NN1 providers_NN2 should_VM teach_VVI the_AT front-line_JJ employees_NN2 how_RRQ to_TO react_VVI to_II customer_NN1 complain_VV0 immediately_RR ,_, and_CC front-line_JJ employees_NN2 should_VM be_VBI authorized_VVN to_TO handle_VVI the_AT complaints_NN2 with_IW some_DD flexibility_NN1 ,_, like_VV0 to_TO offer_VVI some_DD compensation_NN1 ._. 
</s>
<s>
Besides_RR ,_, service_NN1 providers_NN2 should_VM find_VVI ways_NN2 to_TO avoid_VVI commit_VV0 similar_JJ mistakes_NN2 ._. 
</s>
<s>
For_IF any_DD service_NN1 providers_NN2 ,_, service_NN1 failures_NN2 are_VBR inevitable_JJ ,_, but_CCB if_CS customers_NN2 experience_VV0 the_AT same_DA mistake_NN1 again_RT and_CC again_RT ,_, finally_RR ,_, they_PPHS2 would_VM choose_VVI another_DD1 service_NN1 provider_NN1 rather_CS21 than_CS22 complain_VVI ._. 
</s>
<s>
To_TO make_VVI things_NN2 even_RR worse_JJR ,_, these_DD2 disappointed_JJ customers_NN2 are_VBR very_RG likely_JJ to_TO spread_VVI bad_JJ words_NN2 to_TO influence_VVI other_JJ customers_NN2 and_CC the_AT potential_JJ customers_NN2 ._. 
</s>
<s>
If_CS the_AT service_NN1 failure_NN1 were_VBDR serious_JJ ,_, unsatisfied_JJ customers_NN2 may_VM turn_VVI to_TO sue_VVI the_AT service_NN1 provider_NN1 through_II legal_JJ procedures_NN2 ._. 
</s>
<s>
There_EX are_VBR some_DD limitations_NN2 about_II this_DD1 study_NN1 ._. 
</s>
<s>
First_MD ,_, this_DD1 study_NN1 is_VBZ based_VVN on_II eight_MC interviews_NN2 ,_, and_CC most_DAT of_IO these_DD2 interviewees_NN2 '_GE experiences_NN2 were_VBDR related_VVN to_II retailing_NN1 and_CC restaurant_NN1 services_NN2 ._. 
</s>
<s>
There_EX are_VBR only_RR a_AT1 limited_JJ number_NN1 of_IO interviews_NN2 ,_, to_TO better_RRR reflect_VVI how_RRQ the_AT three_MC fairness_NN1 dimensions_NN2 affect_VV0 the_AT service_NN1 recovery_NN1 results_NN2 and_CC customers_NN2 '_GE relationships_NN2 with_IW the_AT providers_NN2 and_CC generalize_VV0 the_AT findings_NN2 ,_, a_AT1 large_JJ number_NN1 of_IO interviews_NN2 are_VBR necessary_JJ ._. 
</s>
<s>
Besides_RR ,_, theses_NN2 interviews_NN2 can_VM not_XX reflect_VVI situations_NN2 in_II fields_NN2 which_DDQ customers_NN2 do_VD0 not_XX have_VHI much_DA1 choice_NN1 ,_, like_II insurance_NN1 and_CC bank_NN1 services_NN2 and_CC transportation_NN1 services_NN2 ._. 
</s>
<s>
Further_JJR study_NN1 could_VM do_VDI a_AT1 wider_JJR field_NN1 study_NN1 to_TO explore_VVI the_AT service_NN1 recovery_NN1 situations_NN2 in_II different_JJ service_NN1 fields_NN2 ._. 
</s>
<s>
Additionally_RR ,_, in_II the_AT interviews_NN2 ,_, I_PPIS1 noticed_VVD that_CST there_EX are_VBR other_JJ factors_NN2 ,_, like_II the_AT previous_JJ experiences_NN2 with_IW the_AT service_NN1 providers_NN2 ,_, the_AT perceptions_NN2 about_II the_AT brand_NN1 and_CC expectations_NN2 about_II the_AT service_NN1 recovery_NN1 can_VM also_RR affect_VVI the_AT results_NN2 ._. 
</s>
