<s>
Motivating_VVG employees_NN2 Abastract_VV0 All_DB motivated_JJ employees_NN2 perform_VV0 better_RRR when_CS their_APPGE leaders_NN2 understand_VV0 how_RRQ to_TO support_VVI them_PPHO2 ._. 
</s>
<s>
Many_DA2 studies_NN2 have_VH0 been_VBN conducted_VVN to_TO understand_VVI human_JJ behaviour_NN1 and_CC there_EX are_VBR no_AT consensus_NN1 about_II which_DDQ theory_NN1 is_VBZ the_AT best_JJT ._. 
</s>
<s>
Scientific_JJ management_NN1 was_VBDZ very_RG popular_JJ in_II the_AT early_JJ years_NNT2 of_IO XX_MC century_NNT1 ,_, however_RR today_RT people_NN appreciate_VV0 more_RRR the_AT Content_NN1 and_CC Process_VV0 theories_NN2 ._. 
</s>
<s>
This_DD1 paper_NN1 sets_VVZ to_TO explain_VVI those_DD2 theories_NN2 in_II a_AT1 workplace_NN1 and_CC discuss_VV0 their_APPGE advantages_NN2 and_CC disadvantages_NN2 ._. 
</s>
<s>
By_II understanding_VVG the_AT advantanges_NN2 of_IO each_DD1 theory_NN1 we_PPIS2 can_VM construct_VVI a_AT1 framework_NN1 for_IF motivating_VVG people_NN and_CC answer_VV0 the_AT question_NN1 of_IO what_DDQ leaders_NN2 can_VM actually_RR do_VDI ._. 
</s>
<s>
Introduction_NN1 Motivation_NN1 is_VBZ a_AT1 fascinating_JJ topic_NN1 to_II social_JJ scientists_NN2 ;_; however_RR it_PPH1 has_VHZ a_AT1 very_RG practical_JJ use_NN1 for_IF managers_NN2 ._. 
</s>
<s>
By_II understanding_NN1 what_DDQ motivates_VVZ people_NN ,_, managers_NN2 are_VBR able_JK to_TO incentive_NN1 them_PPHO2 to_TO be_VBI more_RGR satisfied_JJ with_IW their_APPGE work_NN1 and_CC to_TO perform_VVI better_RRR ._. 
</s>
<s>
The_AT question_NN1 of_IO what_DDQ and_CC how_RRQ to_TO motivate_VVI employees_NN2 within_II an_AT1 organization_NN1 has_VHZ been_VBN a_AT1 subject_NN1 for_IF many_DA2 years_NNT2 ,_, that_CST started_VVD with_IW the_AT early_JJ work_NN1 of_IO Frederick_NP1 Taylor_NP1 (_( 1911_MC )_) ,_, the_AT originator_NN1 of_IO scientific_JJ management_NN1 ,_, however_RR there_RL still_RR are_VBR no_AT definitive_JJ answers_NN2 ._. 
</s>
<s>
The_AT concept_NN1 of_IO scientific_JJ management_NN1 ,_, which_DDQ is_VBZ not_XX a_AT1 theory_NN1 of_IO work_NN1 motivation_NN1 ,_, but_CCB ,_, a_AT1 technique_NN1 to_TO make_VVI labor_NN1 more_RGR efficient_JJ is_VBZ very_RG important_JJ to_II managers_NN2 due_II21 to_II22 its_APPGE assumptions_NN2 that_CST include_VV0 motivational_JJ implications_NN2 ._. 
</s>
<s>
The_AT most_RGT important_JJ implication_NN1 obtained_VVD states_NN2 that_CST payment_NN1 is_VBZ the_AT main_JJ driver_NN1 for_IF employees_NN2 ._. 
</s>
<s>
This_DD1 concept_NN1 does_VDZ not_XX take_VVI into_II consideration_NN1 people_NN who_PNQS do_VD0 well_RR in_II their_APPGE jobs_NN2 but_CCB receive_VV0 low_JJ economic_JJ rewards_NN2 and_CC the_AT next_MD findings_NN2 took_VVD a_AT1 different_JJ view_NN1 ._. 
</s>
<s>
This_DD1 was_VBDZ the_AT Hawthorne_NP1 Studies_NN2 ,_, a_AT1 new_JJ school_NN1 of_IO management_NN1 thinking_NN1 ,_, which_DDQ raise_VV0 the_AT importance_NN1 of_IO peoples_NN2 social_JJ needs_NN2 as_II31 well_II32 as_II33 economics_NN1 payments_NN2 ._. 
</s>
<s>
It_PPH1 includes_VVZ 2_MC different_JJ groups_NN2 ._. 
</s>
<s>
There_EX are_VBR Content_JJ theories_NN2 ,_, which_DDQ focuses_VVZ on_II the_AT factors_NN2 that_CST initiate_VV0 and_CC direct_JJ certain_JJ behaviors_NN2 ;_; and_CC Process_VV0 theories_NN2 ,_, which_DDQ describes_VVZ the_AT psychological_JJ process_NN1 that_CST takes_VVZ place_NN1 in_II the_AT workplace_NN1 ._. 
</s>
<s>
Despite_II the_AT importance_NN1 of_IO these_DD2 theories_NN2 ,_, there_EX are_VBR still_RR many_DA2 limitations_NN2 to_II it_PPH1 ._. 
</s>
<s>
The_AT content_JJ theories_NN2 of_IO motivation_NN1 include_VV0 Maslows_NP1 needs_VVZ theory_NN1 ,_, Aderfers_NP1 theory_NN1 ,_, Herzbergs_NP2 Two-factor_JJ Theory_NN1 and_CC McClellands_NP1 Theory_NN1 of_IO Learned_JJ needs_NN2 ._. 
</s>
<s>
These_DD2 theories_NN2 explain_VV0 human_JJ behaviour_NN1 in_II different_JJ perspectives_NN2 and_CC the_AT simple_JJ answer_NN1 to_II which_DDQ one_PN1 is_VBZ more_RGR accurate_JJ is_VBZ impossible_JJ ._. 
</s>
<s>
None_PN should_VM be_VBI considered_VVN as_CSA being_VBG superior_JJ to_II others_NN2 on_II defining_VVG human_JJ needs_NN2 and_CC they_PPHS2 should_VM complement_VVI each_PPX221 other_PPX222 ._. 
</s>
<s>
For_REX21 example_REX22 Maslow_NP1 does_VDZ not_XX take_VVI into_II consideration_NN1 individual_JJ differences_NN2 and_CC the_AT effect_NN1 of_IO changing_JJ needs_NN2 ._. 
</s>
<s>
One_MC1 of_IO the_AT most_RGT visible_JJ limitations_NN2 of_IO the_AT content_JJ theories_NN2 adresses_VVZ the_AT lack_NN1 of_IO a_AT1 process_NN1 to_TO motivate_VVI ,_, or_CC how_RRQ a_AT1 particular_JJ individual_NN1 come_VV0 to_TO be_VBI motivated_VVN ._. 
</s>
<s>
To_TO answer_VVI this_DD1 limitation_NN1 process_NN1 theories_NN2 were_VBDR created_VVN ._. 
</s>
<s>
These_DD2 theories_NN2 sets_VVZ the_AT direction_NN1 ,_, intensity_NN1 and_CC persistence_NN1 of_IO workers_NN2 while_CS recognizing_VVG that_CST most_DAT people_NN have_VH0 preferences_NN2 for_IF specific_JJ outcomes_NN2 rather_II21 than_II22 others_NN2 ._. 
</s>
<s>
This_DD1 paper_NN1 intends_VVZ to_TO show_VVI that_CST there_EX is_VBZ no_AT perfect_JJ approach_NN1 concerning_II motivating_VVG employees_NN2 ,_, however_RRQV it_PPH1 underlies_VVZ some_DD theories_NN2 that_CST can_VM be_VBI useful_JJ in_II the_AT role_NN1 of_IO a_AT1 leader_NN1 ,_, helping_VVG them_PPHO2 make_VVI better_JJR decisions_NN2 ._. 
</s>
<s>
The_AT beginning_NN1 of_IO this_DD1 study_NN1 starts_VVZ by_II defining_VVG motivation_NN1 in_II a_AT1 work_NN1 context_NN1 and_CC the_AT process_NN1 of_IO motivation_NN1 ._. 
</s>
<s>
It_PPH1 continues_VVZ by_II presenting_VVG different_JJ theories_NN2 of_IO work_NN1 motivation_NN1 and_CC ends_VVZ up_RP linking_VVG the_AT theories_NN2 to_TO better_RRR understand_VVI and_CC influence_VVI employees_NN2 behaviors_NN2 ._. 
</s>
<s>
Method/Materials_FU I_PPIS1 will_VM explain_VVI each_DD1 theory_NN1 individually_RR by_II pointing_VVG key_JJ features_NN2 and_CC characteristics_NN2 ._. 
</s>
<s>
Results_NN2 (_( Analysis_NN1 )_) I_PPIS1 will_VM discuss_VVI advantages_NN2 and_CC disadvantages_NN2 of_IO each_DD1 theory_NN1 individually_RR ._. 
</s>
<s>
Discussion_NN1 Conclusions_NN2 I_PPIS1 will_VM try_VVI to_TO summarize_VVI my_APPGE main_JJ findings_NN2 and_CC explain_VVI how_RRQ each_DD1 theory_NN1 can_VM compliment_VVI each_PPX221 other_PPX222 ._. 
</s>
<s>
In_II the_AT end_NN1 I_PPIS1 will_VM give_VVI some_DD practical_NN1 advises_VVZ for_IF leaders_NN2 to_TO use_VVI when_RRQ they_PPHS2 need_VV0 it_PPH1 ._. 
</s>
